### ISSUE TITLE
Manual device status change not read for TS011F (_TZ3000_cphmq0q7) smart plug

### ISSUE THREAD

**Issue by rsettembrini** [Koenkk/zigbee2mqtt#10018]
## What happened
@Koenkk I see a lot of issues about this device. Fortunately, the most resolved. Now, I am facing with a strange problem. When I change manually device status on the device, it does not reflect into HA. During such operation, checking zigbee2mqtt log at debug level I cannot see anything. With Tuya gateway it works fine. Could I do something with Tuya gateway in order to fix such wrong behaviour?
Converter used y default by zigbee2mqtt is TS011F_plug_3

## What did you expect to happen
after manual status change on the device, new status triggered by zigbee2mqtt and HA. The status change only if I click refresh status.

## How to reproduce it (minimal and precise)
change status directly on the device and check any update on zigbee2mqtt

## Debug info
Zigbee2MQTT version: 1.22.1-1
Adapter hardware: CC2652R1FRGZR
Adapter firmware version: I don't know how to check it

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/9057#issuecomment-971992470
