### ISSUE TITLE
thermostat TS0601 and manufacturer code _TZE200_hue3yfsn,

### ISSUE THREAD

**Issue by Hewelius** [Koenkk/zigbee2mqtt#10036]
Dear colleagues programmers,
I'm trying to add to my system Tuya heater thermostat TS0601 and manufacturer code _TZE200_hue3yfsn. Generally it looks to be supported. I have checked in tuya.js. But I'm still getting info from z2m that it is not supported. I have been trying to add local converter but other problem appears: e.window_open is not a function.
Sorry for screenshot in polish.

![Screenshot_20211205-211221062](https://user-images.githubusercontent.com/93792752/144762303-0c6395aa-2c3b-446b-88d3-a216cecd67d0.jpg)

_Originally posted by @Hewelius in https://github.com/Koenkk/zigbee2mqtt/discussions/10031_

**Comment by fardem** [comment]
Hi,

do you have updated the zigmee2mqtt? In the newest version must be you're device are included.

look here and search for you device "TZE200_hue3yfsn"

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js

**Comment by Hewelius** [comment]
Hi, 
I was pretty sure, that this is up to date, because of set "automatic updates". And finally the version of z2m was outdated.

Thank you a lot.

**Comment by Chaosinme666** [comment]
@Hewelius I got the same problem as well. Z2M update doesn't help at all. Do you have any solution?
