### ISSUE TITLE
cc2530 running with EspEasy with Ser2net on Esp8266

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#1006]
I wonder if there any interest of documentation for Zigbee cc2530 running on esp8266 ser2net over wifi mounted with socat. I got it running and it works with zigbee2mqtt.
Thank you for the cc2530 firmware @ptvoinfo
![img_20190201_212259](https://user-images.githubusercontent.com/22047436/52179453-1ed35c00-27db-11e9-815a-1b8b81bdcdbe.jpg)

**Comment by deennoo** [comment]
Not to much interférences between zigbee and wifi ?

**Comment by JLFN** [comment]
@deennoo not if you use the right channel.

**Comment by JLFN** [comment]
See docs

**Comment by snakuzzo** [comment]
Hi @JLFN, I'm testing this solution, but I've got some problems using ESPEasy (mega-20191208) + CC2530 with 1.2 firmware...can you help me to find a solution ?
Here there are details about the issue...

https://github.com/Koenkk/zigbee2mqtt/issues/2512

**Comment by younessaneie** [comment]
How can I setup cc2530 with esp32 is there any source?
