### ISSUE TITLE
Xiaomi Gas sensor has wrong homeassistant config

### ISSUE THREAD

**Issue by rzhukov** [Koenkk/zigbee2mqtt#1007]
1. The device doesn't have battery, it mains powered, but mqtt dicsovery config provides battery sensor. https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L390
2. Density sensor configured with wrong json attribute `gas_density` https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L181, but converter generates `density` attr: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L962, so it always in "unavailable" state

**Comment by Koenkk** [comment]
@rzhukov thanks for spotting this. Could you make a PR? For point 2, I think the converter should be updated to `gas_density`.

**Comment by Koenkk** [comment]
Merged, thanks!
