### ISSUE TITLE
Please add new manufacture for Tuya TS0505B Led Strip.

### ISSUE THREAD

**Issue by vlforte** [Koenkk/zigbee2mqtt#10081]
This device when paired is reported as 

Model: TS0505B 
Manufacturer ID: _TZ3210_0rn9qhnu

Looking at the Tuya.js code I can see that this Model is supported on various other manufacturer Ids. 

Is it possible to update the tuya.js code for it to work?

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
