### ISSUE TITLE
New Trascievers

### ISSUE THREAD

**Issue by Odianosen25** [Koenkk/zigbee2mqtt#101]
hello @Koenkk,

How possible is it, for other Zigbee tranceieves be supported, like the [Telegesis  RX357 Zigbee Module](https://www.silabs.com/products/wireless/mesh-networking/telegesis-modules-gateways/etrx357-zigbee-radio-module).

Thanks

**Comment by ptvoinfo** [comment]
This is almost impossible because this device uses another SDK and stack. zigbee-shepherd (the base module of zigbee2mqtt) is designed for  TI's SDK and stack.

**Comment by Odianosen25** [comment]
Oh ok, well that answers my question then.

Thanks and kind regards
