### ISSUE TITLE
[QUESTION] reset zigbee2mqtt repository

### ISSUE THREAD

**Issue by yaniv1111** [Koenkk/zigbee2mqtt#1010]
Hi,
I have tested zigbee with my xiaomi hub and it works great, but I haven't enabled it security
1. is there a way to enabled it without repairing all devices?
2. if not, how can i revert zigbee2mqtt configuration to starting point?
3. is there support with ssl certificate between zigbee2mqtt and mosquitto?

thanks

Yaniv

**Comment by yaniv1111** [comment]
thank for the quick respond,

what is the advance configuration for setup ssl?
e.g
m2mqtt_ca.crt  : CA Certificate
m2mqtt_ca.key  : CA key pair (private, public)
m2mqtt_ca.srl  : CA serial number file
m2mqtt_srv.crt : server certificate
m2mqtt_srv.csr : certificate sign request, not needed any more
m2mqtt_srv.key : server key pair

https://mcuoneclipse.com/2017/04/14/enable-secure-communication-with-tls-and-the-mosquitto-broker/

thanks again
Yaniv

**Comment by Koenkk** [comment]
I'm not sure about that, I assume the url has to be something like `mqtts://localhost:1883` (the underlying MQTT library supports this: https://www.npmjs.com/package/mqtt)

**Comment by ben423423n32j14e** [comment]
Did you figure this out?

I've tried mqtts://localhost:1883 but can't get it to connect.

**Comment by ben423423n32j14e** [comment]
I found a (not ideal) solution which was to set: require_certificate false in mosquitto.conf
