### ISSUE TITLE
Sorting by power on the frontend works not as expected

### ISSUE THREAD

**Issue by Gooman-rus** [Koenkk/zigbee2mqtt#10110]
## What happened
I have updated to the 1.22.1-1 and sorting of devices by power on the frontend stopped working. Now it works very strange. Before 1.22.1-1 it was working great. 
![image](https://user-images.githubusercontent.com/3216521/145383034-65f32f47-ca6f-486d-b712-74fe5eaf994c.png)

## What did you expect to happen
Sorting by power works as expected.

## How to reproduce it (minimal and precise)
Go to frontend and try to sort devices by power.

## Debug info
Zigbee2MQTT version: 1.22.1-1
Adapter hardware: CC2538
Adapter firmware version: 20200211

**Comment by Danit2** [comment]
This bug is already known:

https://github.com/nurikk/zigbee2mqtt-frontend/issues/1141
