### ISSUE TITLE
Philips Hue Play - 440400982842

### ISSUE THREAD

**Issue by valfr** [Koenkk/zigbee2mqtt#10136]
## Information about the device + link
Philips HUE PLAY
New model ID = 440400982842
Same as = 915005733701
https://www.zigbee2mqtt.io/devices/915005733701.html#philips-915005733701

Link to support Herdsman => https://github.com/Koenkk/zigbee-herdsman-converters/actions/runs/1555052205

## data/database.db entry of the device

`{"id":11,"type":"Router","ieeeAddr":"0x001788010b4ccd13","nwkAddr":13618,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"440400982842","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"440400982842","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1639165440656}`

Thanks :)

**Comment by HB25** [comment]
Hi,
  quick question: I have the same device and want to add support for it.  Do I have to do it the same way as described for new devices, i.e. create an external converter?   Since it has already been integrated in zigbee-herdsman-converters I was hoping to just update this and I'm fine but it did not work.

I tried to  npm update zigbee-herdsman-converters and I also patched the philips.cs with what I found on Github. This did not help.  

Heiko

**Comment by valfr** [comment]
Hello,
Any idea to get it worked ?

Thx

**Comment by Koenkk** [comment]
This device is already supported in the dev branch (and next release on 1 January). (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by valfr** [comment]
many thanks :)

**Comment by HB25** [comment]
Hello,

I just updated to the latest release but I still have no luck to have it added to the network.

Touchlink scan finds it: `{"data":{"found":[{"channel":11,"ieee_address":"0x001788010b438b17"}]},"status":"ok"}`
It also appears in the network map below `data/links` as follows but does not appear in `data/nodes` or in my HA network map. 

Neither touchlink reset nor the 5s power reset seems to work (although the device flashes after the reset).

I have the feeling that the device is already paired from release 1.22.1. It is already present in configuration.yaml with a friendly name.  Uncommenting it did not help but it also does not appear in HA with this name.

Has anybody hints where to look at or what to try to get this running?


```
             {
                    "depth": 15,
                    "linkquality": 132,
                    "lqi": 132,
                    "relationship": 2,
                    "routes": [],
                    "source": {
                        "ieeeAddr": "0x001788010b438b17",
                        "networkAddress": 42410
                    },
                    "sourceIeeeAddr": "0x001788010b438b17",
                    "sourceNwkAddr": 42410,
                    "target": {
                        "ieeeAddr": "0x0017880108fbd5d3",
                        "networkAddress": 5611
                    },
                    "targetIeeeAddr": "0x0017880108fbd5d3"
                }
```

Thanks in advance and  Happy new year everyone!

**Comment by anthonycvella** [comment]
@Koenkk Was this released with 1.18.1 because it shows as unsupported for me still.

**Comment by Koenkk** [comment]
@anthonycvella 
If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0

**Comment by anthonycvella** [comment]
@Koenkk I realized that when I was looking at the version :P, been re-interviewing all my devices today since I couldn't migrate them, but this seems to be working great now!
