### ISSUE TITLE
Incorrect battery state for Immax 07502L

### ISSUE THREAD

**Issue by z0diak** [Koenkk/zigbee2mqtt#10138]
## What happened
[Immax 07502L](https://www.zigbee2mqtt.io/devices/07502L.html) is supported by Zigbee2MQTT shows battery state as zero.
Example of state reported in Web UI:
```
{
    "battery": 0,
    "humidity": 36,
    "illuminance": 20148,
    "illuminance_lux": 103,
    "keep_time": 30,
    "led_enable": true,
    "linkquality": 42,
    "occupancy": false,
    "pir_enable": true,
    "reporting_enable": true,
    "reporting_time": 5,
    "sensitivity": "medium",
    "tamper": false,
    "temperature": 22.8,
    "voltage": 3200,
    "humidity_calibration": null,
    "illuminance_calibration": null,
    "temperature_calibration": null
}
```

Replacing batteries, using only 1 or both (device can run even on only 1) didn't have any effect. Issue present for all 3 devices I just bought. 

## What did you expect to happen
Battery state reported as for other devices (value or boolean).

## How to reproduce it (minimal and precise)
Pair device and see that immediately. 

## Debug info
Zigbee2MQTT version: 1.22.1
Adapter hardware: CC2652R (Electrolama zig-a-zig-ah! (zzh!))
Adapter firmware version: 20210708

**Comment by mbloodk** [comment]
problem is still there, I see N/A
