### ISSUE TITLE
Problems pairing a second Lightify Gardenstpot RGB

### ISSUE THREAD

**Issue by YamiFrankc** [Koenkk/zigbee2mqtt#1014]
Hello,

Right now im running the dev branch. I was able to pair my first Gardenspot without any problem, worked flawlessly. But now I am trying to join a second one and im having trouble doing so. I am following the instructions listed [here](https://www.belkin.com/us/support-article?articleNum=159343) to reset them and get in pairing mode. They do not flash 3 times, but they color cycle like mentioned [here](https://community.smartthings.com/t/osram-sylvania-gardenspot-pairing-issue/60008).
I dont really see anything in the logs, [https://pastebin.com/6D0Pvchh](https://pastebin.com/6D0Pvchh)

any tips?

Thanks

**Comment by Koenkk** [comment]
Did you pair them to a other hub previously?

**Comment by YamiFrankc** [comment]
Yes. They were paired to another previous instance of zigbee2mqtt using the same stick.
Since then I have moved to a new install using the dev branch a reflashed the stick

**Comment by Koenkk** [comment]
@YamiFrankc are they still in the `database.db`?

**Comment by YamiFrankc** [comment]
They arent

**Comment by Koenkk** [comment]
When pairing and running with `DEBUG=* npm start`, do you see any logging appearing when trying to pair?

**Comment by YamiFrankc** [comment]
not really, this is what i get: [pastebin](https://pastebin.com/6mYAxfLy)

**Comment by Koenkk** [comment]
@YamiFrankc did you successfully pair this device to another hub?

**Comment by YamiFrankc** [comment]
This device im having problems with is actually the one I made a post about before, so it was paired  with an older install of zigbe2mqtt with this same stick,
Right now I tried to pair other devices and they dont work. Noting appears in the logs with any device

**Comment by Koenkk** [comment]
Did you reflash the stick in between?

**Comment by YamiFrankc** [comment]
Yes

**Comment by Koenkk** [comment]
Can you post your complete zigbee2mqtt startup log?

**Comment by YamiFrankc** [comment]
Here: [pastebin](https://pastebin.com/rqVeHHcx)

**Comment by Koenkk** [comment]
Is `permit_join: true` in `configuration.yaml`?

Your log shows:
`2/7/2019, 7:03:20 AM - info: Zigbee: disabling joining new devices.`

**Comment by YamiFrankc** [comment]
Its not, but I use the HA automation that is in the wiki to enable joining. Been working perfectly until now

**Comment by Koenkk** [comment]
Please set `permit_join: true` in `configuration.yaml`, from the log I cannot see that joining is enabled, and try again to pair devices.

**Comment by YamiFrankc** [comment]
[Output log](https://pastebin.com/93VdGpE8)

**Comment by Koenkk** [comment]
Are all the not paired Zigbee devices offline? As the devices of the old zigbee network (before flashing your stick) could still form a zigbee network. When trying to pair devices, they will prefer to reconnect to the network they were already paired to (the old network).

**Comment by YamiFrankc** [comment]
All on the other devices paired were working correctly.
The problem fixed itself when I restarted the raspberry running zigbee2mqtt, I was able to pair devices again
