### ISSUE TITLE
Question to Vima Smart Lock (no issue)

### ISSUE THREAD

**Issue by mpuff** [Koenkk/zigbee2mqtt#1017]
Hello,

will it be possible in the future to aktivate/deactivate an key for the Vima Smart Lock and read the battery status of this device?

**Comment by segalion** [comment]
Please open this issue again?. 

I think Vima Smartlock has not:
- Key management (enable/disable/temporary keys)
- Battery level

This two options are absolutelly needed. If not available in zigbee2mqtt, xiaomi gateway is needed, so you cant use it in zigbee2mqtt.

Could be great to remove old state after some timeout.
