### ISSUE TITLE
Firmware version not beeing displayed

### ISSUE THREAD

**Issue by T-IOOO** [Koenkk/zigbee2mqtt#10172]
I have an issue with one bulb not displaying firmware version in the frontend.
I have tried to repair the device to see if it changes.
Anyone else having this issue?
@nurikk Im not sure if this is frontend-related or not?

![image](https://user-images.githubusercontent.com/59575587/145991195-4e7cd83a-ace3-4518-a2ce-a9a598ebb2f7.png)

**Comment by nurikk** [comment]
no

**Comment by groenmarsmannetje** [comment]
What happens if you remove the device, restart z2m and pair the device again?

**Comment by T-IOOO** [comment]
I was hoping that would be the last thing to do. I have three other bulbs in the same armature 😫

**Comment by sudofly** [comment]
> I was hoping that would be the last thing to do. I have three other bulbs in the same armature 😫

unscrew the working ones and do the switch dance ?

**Comment by T-IOOO** [comment]
I removed the bulb from the network and then preformed a reset. Now it's back to normal.

This can now be closed
