### ISSUE TITLE
Danfoss Ally 014G2461 new firmware introduces "Radiator Covered" boolean

### ISSUE THREAD

**Issue by davidramiro** [Koenkk/zigbee2mqtt#10185]
## Is your feature request related to a problem? Please describe
Currently the `external_measured_room_sensor` works fairly well, but digging a bit deeper, several users reported that it rather uses an average of the `local_temperature` and the external one instead of the external temp as an absolute value.

Danfoss recently released version 1.18 of the firmware, and judging from their docs, they introduced a boolean called "Radiator Covered" at `0x4016`. They describe it as follows:

FALSE = **Auto Offset Mode** for Exposed Radiators
TRUE = Room Sensor Mode (allows Covered Radiators)

They also updated the external sensor description as follows:

**Depending on 0x4016**:
0x4016 FALSE: Recommended to be received from Gateway at least every 3 hours but not more often than every 30 minutes @ every 0,1K change
0x4016 TRUE: At least every 30 minutes but not more often than every 5minutes @ every 0,1K change for covered radiators 

Which makes it seem like indeed, with this boolean set to true, the device solely relies on the external sensor instead of using an offset.

## Describe the solution you'd like
I would really appreciate this value to be accessible via Z2M. I am absolutely willing to help implement it, although I am not familiar with the ecosystem of Z2M, especially zigbee-herdsman. If there is anything I can do to help or if there are some docs on how to properly implement new clusters, please let me know.

## Additional context
Updated spec sheet for 1.18 firmware: https://assets.danfoss.com/documents/193613/AM375549618098en-000102.pdf

**Comment by lux73** [comment]
And please add:

- 0x404B Regulation SetPoint Offset
- 0x404C Adaptation run control
- 0x404D Adaptation run status
- 0x404E Adaptation run settings

i bought a few of them to replace my buggy Eurotronics - the Eurotronics overheated extremely

the new Danfoss otherwise needs to much time to heat up from 18.7°C to 21°C - it needs 5-6 Hours...  very disappointed actually :-/

if anybody point me in the right Direction (which Files to edit) i'm willing to implement this share for merge

**Comment by codingcatgirl** [comment]
@lux73 this was added in https://github.com/Koenkk/zigbee-herdsman/pull/439 already :)

**Comment by lux73** [comment]
that's correct - but there are no entrys in 'zigbee-herdsman-converters'

i had added these missing entry's & used the above PR as "template" - but no luck after z2m restart...

**i'm not sure if a simple restart is enough after editing the converter file?!?** i even had made some additions to 'fromZigbee.js' & 'toZigbee.js' & 'danfoss.js' -but could not seen the additional Topic. When i try to publish it gave me a warning that the converter is not found/available

a few Weeks ago i made some Changes under devices/miboxer.js for testing - these changes are immediatly online after z2m restart

**Comment by codingcatgirl** [comment]
It sounds like a good idea to make your own ticket about this, since this one, based on its title, should probably be closed.

**Comment by davidramiro** [comment]
Indeed, this got merged in 1.22.2 and I've successfully tested it. I'll close this here :)
