### ISSUE TITLE
Not starting anymore after edge update today

### ISSUE THREAD

**Issue by dreimer1986** [Koenkk/zigbee2mqtt#1018]
Two strange things in this log:
- "Zigbee2mqtt requires node version 10, you are running v8.14.0!"
- Error at the end

```
[Info] Configuration file found: /share/zigbee2mqtt/configuration.yaml
[Info] Configuration written to /share/zigbee2mqtt/configuration.yaml
2019-02-04T19:14:10: PM2 log: Launching in no daemon mode
2019-02-04T19:14:11: PM2 log: App [npm:0] starting in -fork mode-
2019-02-04T19:14:11: PM2 log: App [npm:0] online
> zigbee2mqtt@1.1.0 start /app
> node index.js
		Zigbee2mqtt requires node version 10, you are running v8.14.0!
  zigbee2mqtt:info 2019-2-4 19:14:15 Logging to directory: '/share/zigbee2mqtt/log/2019-02-04.19-14-15'
  zigbee2mqtt:info 2019-2-4 19:14:17 Starting zigbee2mqtt version 1.1.0 (commit #6d16875)
  zigbee2mqtt:info 2019-2-4 19:14:17 Starting zigbee-shepherd
  zigbee2mqtt:info 2019-2-4 19:14:20 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
  zigbee2mqtt:info 2019-2-4 19:15:20 Starting zigbee-shepherd
  zigbee2mqtt:error 2019-2-4 19:15:23 Error while starting zigbee-shepherd!
  zigbee2mqtt:error 2019-2-4 19:15:23 Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 2019-2-4 19:15:23 Failed to start
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
```

Config in Hass.IO 0.87.0b4 arm64 (CC2530 in use)

```
{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": true,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://homeassistant",
  "serial_port": "/dev/ttyUSB0",
  "devices": [],
  "network_key": [],
  "rtscts": false
}
```

**Comment by Koenkk** [comment]
It seems that zigbee shepherd cannot connect to the cc2530, can you replug it and verify that the path to the cc2530 is still correct?

**Comment by dreimer1986** [comment]
Replugging and even rebooting does not change anything. Path is correct according to HassOS hardware tab. While we are at HassOS... I updated that one, too. 2.8 is recent now... Testing zigbee2mqtt release now and if that fails... downgrade to HassOS 2.7 as test.

**Comment by universal** [comment]
hmm, after a reboot of the raspberry pi i have to disconnect the vcc in of the cc2530, otherwise i get the same error. that is on 1.11 though.

**Comment by dreimer1986** [comment]
OK, back at 2.8 after I tried 2.7 and reverted to a snapshot. Still the same. Went back to my cc2532 backup device and POOF all works fine. I am 99% sure that my hardware is dead. In this case the cc2530 itself and not the serial converter. Gonna investigate further another day.

**Comment by MikeVol** [comment]
> hmm, after a reboot of the raspberry pi i have to disconnect the vcc in of the cc2530, otherwise i get the same error. that is on 1.11 though.

zigbee2mqtt:debug 2019-2-5 02:54:28 Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 2019-2-5 02:59:28 Saving state to file /share/zigbee2mqtt/state.json
2019-02-04T22:01:36.246Z zigbee-shepherd Starting a software reset...
2019-02-04T22:01:36.254Z zigbee-shepherd zigbee-shepherd is stopping.
2019-02-04T22:01:36.259Z zigbee-shepherd:msgHdlr IND <-- SYS:resetInd
2019-02-04T22:01:36.260Z zigbee-shepherd zigbee-shepherd is stopped.
2019-02-04T22:01:36.261Z zigbee-shepherd:init zigbee-shepherd booting...
2019-02-04T22:01:36.277Z zigbee-shepherd Reset had an error Error: Port is already open
    at SerialPort.open (/zigbee2mqtt-1.1.1/node_modules/serialport/lib/serialport.js:222:29)
    at CcZnp.init (/zigbee2mqtt-1.1.1/node_modules/cc-znp/lib/ccznp.js:141:8)
    at Promise.post (/zigbee2mqtt-1.1.1/node_modules/q/q.js:1181:36)
    at Promise.promise.promiseDispatch (/zigbee2mqtt-1.1.1/node_modules/q/q.js:808:41)
    at /zigbee2mqtt-1.1.1/node_modules/q/q.js:1411:14
    at runSingle (/zigbee2mqtt-1.1.1/node_modules/q/q.js:137:13)
    at flush (/zigbee2mqtt-1.1.1/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  zigbee2mqtt:error 2019-2-5 03:01:36 
	{"message":"Port is already open","stack":"Error: Port is already open\n    at SerialPort.open (/zigbee2mqtt-1.1.1/node_modules/serialport/lib/serialport.js:222:29)\n    at CcZnp.init (/zigbee2mqtt-1.1.1/node_modules/cc-znp/lib/ccznp.js:141:8)\n    at Promise.post (/zigbee2mqtt-1.1.1/node_modules/q/q.js:1181:36)\n    at Promise.promise.promiseDispatch (/zigbee2mqtt-1.1.1/node_modules/q/q.js:808:41)\n    at /zigbee2mqtt-1.1.1/node_modules/q/q.js:1411:14\n    at runSingle (/zigbee2mqtt-1.1.1/node_modules/q/q.js:137:13)\n    at flush (/zigbee2mqtt-1.1.1/node_modules/q/q.js:125:13)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/next_tick.js:181:9)"}

**Comment by Koenkk** [comment]
@MikeVol are you sure the path to your CC2531 is correct?
