### ISSUE TITLE
Search Device when adding Devices to a group

### ISSUE THREAD

**Issue by chrisrock1984** [Koenkk/zigbee2mqtt#10196]
## Is your feature request related to a problem? Please describe
I'm always frustrated when adding devices to a group, and you have to scroll through the devices to find the corresponding MAC address.

## Describe the solution you'd like
It would be nice, to be able to start typing within the dropdown menu to find the device more easily by typing a part of the MAC address.

## Describe alternatives you've considered
-
## Additional context
-

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/z2m-frontend/issues
