### ISSUE TITLE
Sorting option in the frontend is broken

### ISSUE THREAD

**Issue by the-cyberspace** [Koenkk/zigbee2mqtt#10190]
## What happened

The sorting option in the frontend is broken.  See following screenshot:

Begin:
![afbeelding](https://user-images.githubusercontent.com/46862733/146158894-8a255696-ad31-4925-9e66-6c7e596fc46f.png)

In this screenshot the name table is sorted alphabetically but i`m having a sensor for a 3dprinter (see screenshot below) and as far as i know numbers appear first when you sort alphabetically. 

End:
![afbeelding](https://user-images.githubusercontent.com/46862733/146160568-e9278212-0bee-4c04-869c-644e91f3a3c0.png)

## What did you expect to happen

See info above..

## Debug info
Zigbee2MQTT version:  1.22.1-dev commit: d875b29
Adapter hardware: ConBee2/RaspBee2
Adapter firmware version: 0x26720700

**Comment by tteck** [comment]
May want to open an issue here
https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by the-cyberspace** [comment]
> May want to open an issue here https://github.com/nurikk/zigbee2mqtt-frontend/issues

Done that, i didn`t now that`s the right place for bugs in the frontend. Will close this issue :)
