### ISSUE TITLE
Failed to read state after reconnect genOnOff(["onOff"]

### ISSUE THREAD

**Issue by wb-adegtyarev** [Koenkk/zigbee2mqtt#10198]
## What happened
Hi. The device gives an error when reconnecting
```
Failed to read state of '0x842e14fffe8b184e' after reconnect (Read 0x842e14fffe8b184e/1 genOnOff(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE'))
```
## What did you expect to happen
This is strange, since there is no subscription to this attribute and cluster in the device template.
If you remove device information from files and MQTT, then the first pairing goes fine and there are no errors.

## How to reproduce it (minimal and precise)
This plays on my device:
- Pair the device, wait for the end of the setup. 
- Check that everything works. 
- Break the connection with the device. 
- Pair the device again and get an error.

Helps to restart the zigbee2mqtt or completely deleting data about the device and re-pairing.

Configure section in the converter:
```
configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint1 = device.getEndpoint(1);
        const binds = ['genBasic','msTemperatureMeasurement', 'msIlluminanceMeasurement', 'msRelativeHumidity', 'msOccupancySensing', 'msCO2'];
        await reporting.bind(endpoint1, coordinatorEndpoint, binds);
```
The full text of the converter can be viewed at the link: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3529

![image](https://user-images.githubusercontent.com/77433258/146374094-368d63ff-47f8-4482-92f5-d2a34578c9c0.png)

## Debug info
Zigbee2MQTT version: 1.22.1
Adapter hardware: CC2530
Adapter firmware version: CC2530_CC2592_DEFAULT_20211115

**Comment by mcinnes01** [comment]
I'm also seeing this issue, just wondered if there is anything to resolve this yet? I've see a few issues very similar seeming to relate to updates in HA or in zigbee2mqtt but no fixes as I can see as yet?
