### ISSUE TITLE
Availability Timeout not working

### ISSUE THREAD

**Issue by timstanley1985** [Koenkk/zigbee2mqtt#1020]
Did you read the FAQ?
https://koenkk.github.io/zigbee2mqtt/information/FAQ.md

Unsupported device?
https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html

A question?
Read the documentation: https://koenkk.github.io/zigbee2mqtt/

Bug report:
- First make sure your on the latest version of zigbee2mqtt.
- Make sure you are running the latest CC253X firmware from https://github.com/koenkk/z-stack-firmware.
- Provide a clear description of the problem.
- If applicable, provide steps how to reproduce the problem.
- Provide a log with `log_level` set to `debug`, see https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html
- DON'T copy logs directly here, post a link to https://hastebin.com/ or https://pastebin.com/.

Hi, firstly zigbee2mqtt is a great piece of work. It took me 5 minutes with zero issues to get this set up and replace my existing xaiomi hub.  

Zigbee2mqtt has been running flawlessly for one week except for one small point.  I have set availability_timeout to 3600 seconds but after 12 hours without a message from one of my aqara temperature sensors the sensor is still reported as online.  The expected behaviour in this situation would be that the sensor retorts unavailable after 1 hour

**Comment by Bruceforce** [comment]
Please see #775
>Device availability is only checked for AC powered routers.

This is not a bug. Since your sensor is battery powered (==end device) it is desired behavior to not show availability status, because this would drain the battery unnecessarily.

**Comment by Koenkk** [comment]
Updated documentation and added this as a feature request to #775.
