### ISSUE TITLE
New Philips HUE White Ambiance 1100 lm LTA009 Not supported

### ISSUE THREAD

**Issue by dverhaert** [Koenkk/zigbee2mqtt#10230]
## Information about the device + link

I got the Philips Hue White Ambiance E27 1100 lumen Bluetooth last week, however when pairing it with zigbee2mqtt it shows as non supported. I am not too familiar with the specifics of adding new devices in this Github, so hope someone can help me out with this as it should be very similar to the older model. 

**Image of lamp**
![image](https://user-images.githubusercontent.com/4787591/140605524-b94cfbf2-0e79-4fe1-bf3a-7188ac94479f.png)

I am also not sure what is meant with the database entry, maybe this helps:
![image](https://user-images.githubusercontent.com/6087525/146653652-35a63938-f483-45fe-826e-0172a03b93fa.png)

link to product: https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-1-pack-e27/8719514291119#specifications

Thanks in advance!

**Comment by Koenkk** [comment]
Already supported in the dev branch (and next release on 1 Jan).  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
