### ISSUE TITLE
Problem on Master  SRLRA== integrity checksum failed when using sha512: wanted sha512-

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#1026]
I tried to reinstall my zigbee2mqtt with https://github.com/Koenkk/zigbee2mqtt.git and got problem with sha do not match. I tried the dev that works.
https://pastebin.com/fVQJtPxM

**Comment by JanJaapKo** [comment]
Same issue here, but am not able to pull dev (gives merge conflicts which is beyond my knowledge to fix). @JLFN  how did you pull the dev version?

**Comment by Koenkk** [comment]
Thanks, fixed!
