### ISSUE TITLE
NAS-WR01B

### ISSUE THREAD

**Issue by totom80** [Koenkk/zigbee2mqtt#10263]
Hello,
I've buy some wall plug NAS-WR01B (Tuya like) and I can't use them.
When I paired, I've a warning log: 
Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_gjnozsaz'

model link:
[https://fr.aliexpress.com/item/1005003444957152.html?spm=a2g0s.9042311.0.0.3aff6c37Ux7Dsz](url)

Is it possible to add in a futur version ?

Thanks

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by PrzemekSkw** [comment]
Hello, I use that plug for some time but now when I try to pair again I cannot. Nothing happen. I click button on my plug for 5 or 10 seconds but nothing happen. There was some error show in z2m dashboard but now when I try again there's no info in logs also. Can I do something or plug is trash?
Regard

**Comment by zhuykovkb** [comment]
@PrzemekSkw i have the same problem. it looks like better to open new issue, because current is closed

**Comment by PrzemekSkw** [comment]
Hi, I get rid of that plug. I think ZigBee module was broken.
Regards.
