### ISSUE TITLE
zigbee2mqtt service conencted through tcp stop to responding after remote hub with socat was restarted

### ISSUE THREAD

**Issue by deg026** [Koenkk/zigbee2mqtt#10283]
Zigbee2MQTT version 1.22.1

i am using Xiaomi mgl03 gateway as network zigbee stick through "socat"

configured as:
```
serial:
  adapter: ezsp
  port: tcp://192.168.1.99:8888
```

everything works fine, until i have to reboot the gateway
after rebooting the xiaomi hub is finished - zigbee2mqtt service by system process monitoring seems to continue working
and also "systemctl status zigbee2mqtt.service" reporting as Active: active (running)

but from this point is
1. nothing happend in logs
2. related mqtt topics stop updating
3. and also WEB GUI is stop responding

so only one thing help me to make system work again - restart zigbee2mqtt service

sorry for my english, and report format, it is first time i am doing it

**Comment by Koenkk** [comment]
Please report this issue here: https://github.com/Koenkk/zigbee-herdsman/issues/319 

The EZSP integration is currently in a very experimental stage without any developers working on it, therefore all issues are gathered in https://github.com/Koenkk/zigbee-herdsman/issues/319
