### ISSUE TITLE
 LED1624G9 does not expose color temperature

### ISSUE THREAD

**Issue by neobonde** [Koenkk/zigbee2mqtt#10285]
## What happened
I have paired an IKEA light LED1624G9, it is a color and color temperature lamp. It exposes the state, brightness, color_xy, and effect. When trying to set the color to the 3 ikea color temperature colors; "Warm white", "cozy" and "focus" via color_xy, I end up with some sort of approximation of the color. It seems that it is only using the RGB LEDs and not the dedicated color temperature leds

## What did you expect to happen
I would expect it to expose color_temp as well, and that this would control the dedicated color temperature LEDs built into the light.

## How to reproduce it (minimal and precise)

- Permit Join
- Put light in paring mode (6 quick power cycles)
- Wait for the light to join
- In the frontend open the light, and check the "Exposes" tab

## Debug info
Zigbee2MQTT version: 1.18.1
Adapter hardware: ConBee2/RaspBee2
Adapter firmware version: ?? 
Coordinator revision: 0x26660700
Frontend version: 0.3.76

**Comment by Koenkk** [comment]
Already fixed in more recent z2m versions.
