### ISSUE TITLE
TuYa TS1101_dimmer_module _TZ3000_xfs39dbf

### ISSUE THREAD

**Issue by ovcze** [Koenkk/zigbee2mqtt#10297]
## What happened
Dimmer TuYa TS1101_dimmer_module _TZ3000_xfs39dbf is only 1 channel dimmer, but it is exposing as 2 channnel dimmer (_TZ3000_7ysdnebc).

AliExpress link: https://www.aliexpress.com/item/1005003012298844.html

## What did you expect to happen
Dimmer TuYa TS1101_dimmer_module _TZ3000_xfs39dbf should have only one endpoint not two.

## How to reproduce it (minimal and precise)
After pairing the TuYa TS1101_dimmer_module _TZ3000_xfs39dbf is created wrongly with 2 endpoints. 

## Debug info
Zigbee2MQTT version: 1.22.1 
Adapter hardware: CC2530
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
@PshemoSK since you added this in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3322, can you confirm `_TZ3000_xfs39dbf` is indeed a one channel dimmer?

**Comment by marthubner** [comment]
@Koenkk `_TZ3000_xfs39dbf` really is a one channel dimmer and mine just got recognized as a two channel.
It is this device in the picture 
![Screenshot 2021-12-29 18 13 46](https://user-images.githubusercontent.com/86839034/147687206-46c5152a-a763-432a-ba95-702bd3256bc0.png)
![Screenshot 2021-12-29 18 15 52](https://user-images.githubusercontent.com/86839034/147687404-c4f94a57-8958-44ac-84e7-978816493fc5.png)

**Comment by Koenkk** [comment]
I see, fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
