### ISSUE TITLE
Cannot read property 'manufacturerID' of undefined

### ISSUE THREAD

**Issue by flatsiedatsie** [Koenkk/zigbee2mqtt#10298]
I could not find a similar issue in the issue cue, and a web search also found no relevant results.

## What happened

Zigbee2MQTT did not seem to start properly.

## What did you expect to happen

I expected it to start.

## How to reproduce it (minimal and precise)

Rapsberry Pi 4 with official power supply
CR2531 with recent flash of stable firmware. Flashed from Linux.

I only tried using this stick because I had some trouble getting the Sonoff 3.0 Plus stick to recognise an IKEA light, and wanted to experiment and see if pairing it with this USB stick did work.

After a reboot the issue was gone. Perhaps it was related to using these two different sticks in a row.

I just tried it the other way around, and got the same error.
- run Zigbee2MQTT with CC2531
- unplug device and stop Zigbee2MQTT
- Plug in Sonoff stick
- Run Zigbee2MQTT
- same error

It's clearly not an important issue with these little sticks being deprecated and all. But I thought I'd share anyway.

## Debug info
Zigbee2MQTT version: 1.22.1 (commit #42569d6)
Adapter hardware: CC2531
Adapter firmware version: latest normal stable, CC2531ZNP-Prod.hex

**Comment by Koenkk** [comment]
Please provide a debug log of this

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
