### ISSUE TITLE
No converter for KS-SM001

### ISSUE THREAD

**Issue by GSanCap** [Koenkk/zigbee2mqtt#1029]
Hi, I bought a KS-SM001 and works like a charm, I only need to send the state ON / OFF JSON message and switch the relay state, but, in the zigbee2mqtt state appears the following message:

"No converter available for 'KS-SM001' with cid 'genOnOff', type 'devChange' and data '{"cid":"ge
nOnOff","data":{"onOff":1}}' "

How can i fix it?

Thanks!

**Comment by Koenkk** [comment]
Can you try with the dev branch?

**Comment by GSanCap** [comment]
Thanks @Koenkk i prefer to wait for a stable release with the fix inside ;)

Thank you very much!
