### ISSUE TITLE
BSEED Curtain switch (Model: TS0601, Manufacturer: _TZE200_yenbr4om)

### ISSUE THREAD

**Issue by Volcano0** [Koenkk/zigbee2mqtt#10300]
Hi Koenk,
## Information about the device + link
I bought the Curtain switch by BSEED, because Tuya CS by WeLaik me me crying.

https://pl.aliexpress.com/item/1005003475719946.html?spm=a2g0o.productlist.0.0.386523eedwy7T5&algo_pvid=55ee5dc8-e4b8-4e3f-8bd5-a725ecb2e56c&algo_exp_id=55ee5dc8-e4b8-4e3f-8bd5-a725ecb2e56c-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000025957280479%22%7D

What I'm receiving in the log file (debug):

debug 2021-12-21 20:20:58: Received MQTT message on 'homeassistant/switch/0x04cd15fffe8ddf3f/switch/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/0x04cd15fffe8ddf3f/set","device":{"identifiers":["zigbee2mqtt_0x04cd15fffe8ddf3f"],"manufacturer":"BSEED","model":"Curtain switch (TS0601)","name":"0x04cd15fffe8ddf3f","sw_version":"Zigbee2MQTT 1.21.1-dev"},"json_attributes_topic":"zigbee2mqtt/0x04cd15fffe8ddf3f","name":"0x04cd15fffe8ddf3f","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x04cd15fffe8ddf3f","unique_id":"0x04cd15fffe8ddf3f_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
debug 2021-12-21 20:20:58: Received MQTT message on 'homeassistant/sensor/0x04cd15fffe8ddf3f/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x04cd15fffe8ddf3f"],"manufacturer":"BSEED","model":"Curtain switch (TS0601)","name":"0x04cd15fffe8ddf3f","sw_version":"Zigbee2MQTT 1.21.1-dev"},"enabled_by_default":false,"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x04cd15fffe8ddf3f","name":"0x04cd15fffe8ddf3f linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x04cd15fffe8ddf3f","unique_id":"0x04cd15fffe8ddf3f_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

My external converter looks like:
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0601'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'TS0601', // Vendor model number, look on the device for a model number
    vendor: 'BSEED', // Vendor of the device (only used for documentation and startup logging)
    description: 'Curtain switch', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.switch()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};
module.exports = definition;

I haven't seen any .js for Bseed products. I tried to use Livolo.js defitintion, but it failed.

## data/database.db entry of the device
..

**Comment by sjorge** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/6640de0174b16a76e1746d323e3c3522cd7e8aeb/devices/tuya.js#L784

I'd try by appending it here, although I'm not sure on what values to use as you didn't provide a database entry for the device.

Would be my guess but it could be way off:
```
{modelID: 'Curtain switch (TS0601)', manufacturerName: 'BSEED'},
```
