### ISSUE TITLE
Sensor picture in the UI is cropped

### ISSUE THREAD

**Issue by ngosang** [Koenkk/zigbee2mqtt#10315]
## What happened

Sensor picture in the UI is cropped

![image](https://user-images.githubusercontent.com/10577978/147144014-49ebed7c-bae2-4dc0-b157-34c154da9d13.png)

## What did you expect to happen

The image should be complete when you only have 1 device.

## How to reproduce it (minimal and precise)

Have 1 devise and mouse over the image.

## Debug info
Zigbee2MQTT version: 1.22.1 Docker
Adapter hardware: Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment]
Please open issues related to the frontend here: https://github.com/nurikk/z2m-frontend/issues
