### ISSUE TITLE
Show Zigbee2MQTT version in the Web UI

### ISSUE THREAD

**Issue by ngosang** [Koenkk/zigbee2mqtt#10316]
## Is your feature request related to a problem? Please describe
Show Zigbee2MQTT version in the Web UI. I know it's easy to get the version from the logs but reporting bugs will be easier.

## Describe the solution you'd like
Preferably in the header or the footer (all pages). 

## Describe alternatives you've considered
Not much to consider.

**Comment by Koenkk** [comment]
See settings -> about

<img width="580" alt="Screenshot 2021-12-22 at 20 30 54" src="https://user-images.githubusercontent.com/2892853/147145568-26ee5838-adde-4d6d-b6d4-b87e93ce4952.png">
