### ISSUE TITLE
Elelabs elr023

### ISSUE THREAD

**Issue by RogerSero** [Koenkk/zigbee2mqtt#10333]
Hi, I recently purchased the Elelabs Zigbee Raspberry Pi Shield, based on ezsp. I have tried to get it to work with zigbee2mqtt without much luck. I wanted to know if it is possible that it works and what would be the steps to follow to achieve it? Is it necessary to update the firmware? What should be changed in the configuration?

**Comment by Koenkk** [comment]
Please ask this in https://github.com/Koenkk/zigbee-herdsman/issues/319 (EZSP adapter support is in a very experimental phase)
