### ISSUE TITLE
Tuya Motion Sensor device - _TZ3000_kmh5qpmb

### ISSUE THREAD

**Issue by fabrew4n** [Koenkk/zigbee2mqtt#10342]
### Link

https://www.aliexpress.com/item/1005003677293451.html?spm=a2g0o.productlist.0.0.13d07348nOEAni&algo_pvid=c6252977-9f37-498a-b1e6-70a16f369e08&algo_exp_id=c6252977-9f37-498a-b1e6-70a16f369e08-6&pdp_ext_f=%7B%22sku_id%22%3A%2212000026760777667%22%7D&pdp_pi=-1%3B8.99%3B-1%3B-1%400%3BUSD%3Bsearch-mainSearch

### Database entry

{"id":57,"type":"EndDevice","ieeeAddr":"0xa4c138a5c1361d85","nwkAddr":19177,"manufId":4417,"manufName":"_TZ3000_kmh5qpmb","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"T3000_kmh5qpmb","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00258d4742","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSS0202","manufacturerName":"_TZeen":1640344701493,"useImplicitCheckin":true}

### Comments

        fingerprint: [{modelID: 'TS0202', manufacturerName: '_TYZB01_ef5xlc9q'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_vwqnz1sn'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_2b8f6cio'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_dl7cejts'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_qjqgmqxr'},
            {modelID: 'TS0202', manufacturerName: '_TZ3000_mmtwjmaq'},
            {modelID: 'TS0202', manufacturerName: '_TZ3000_mcxw5ehu'},
            {modelID: 'TS0202', manufacturerName: '_TZ3000_msl6wxk9'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_hqbdru35'},
            {modelID: 'WHD02', manufacturerName: '_TZ3000_hktqahrq'}],
        model: 'TS0202',
        vendor: 'TuYa',
        description: 'Motion sensor',
        whiteLabel: [{vendor: 'Mercator Ikuü', model: 'SMA02P'}],
        fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery, fz.ignore_basic_report, fz.ias_occupancy_alarm_1_report],
        toZigbee: [],
        exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.battery()],

- Looked at the manufacturer name and does not have the _TZ3000_kmh5qpmb.
- 
![image](https://user-images.githubusercontent.com/47353708/147349098-9a65cfab-d52b-4cee-a883-ee17c6168249.png)
- Warning Received message from unsupported device with Zigbee model 'TS0202' and manufacturer name '_TZ3000_kmh5qpmb'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
