### ISSUE TITLE
Hue Fair model 929003054701

### ISSUE THREAD

**Issue by alterna-libor** [Koenkk/zigbee2mqtt#10357]
### Link

https://www.philips-hue.com/cs-cz/p/hue-white-ambiance-stropni-svitidlo-fair/4034031P6

### Database entry

{"id":15,"type":"Router","ieeeAddr":"0x0017880109c6a7ef","nwkAddr":28541,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003054701","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003054701","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211021","swBuildId":"1.93.3"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211021","swBuildId":"1.93.3","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1640454043481,"useImplicitCheckin":true}

### Comments

Black Philips hue Fair (white ambiance)

**Comment by Koenkk** [comment]
I need some more info to add support for this light. I've just extended the new support device request form for lights, could you try it? https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=new+device+support&template=new_device_support.yaml&title=%5BNew+device+support%5D%3A+ 

Especially the section under "Lights" is important.
