### ISSUE TITLE
[New device support]: Please add support for Tuya Smart water/gas valve _TZ3000_h3noz0a5

### ISSUE THREAD

**Issue by josemaX** [Koenkk/zigbee2mqtt#10374]
### Link

https://es.aliexpress.com/item/1005002633228786.html

### Database entry

{"id":31,"type":"Router","ieeeAddr":"0xa4c1380c03167559","nwkAddr":52907,"manufId":4417,"manufName":"_TZ3000_h3noz0a5","powerSource":"Mains (single phase)","modelId":"TS0001","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0001","manufacturerName":"_TZ3000_h3noz0a5","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff07095c","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1640538319163,"useImplicitCheckin":true}

### Comments

I've just bought an Smart water/gas valve (URL in link)

This seems exactly the Tuya valve: https://www.zigbee2mqtt.io/devices/ZN231392.html however, upon pairing, it is identified as a TS0001 and image shown as a switch. Works Ok.

Can you add this device and the image (the ZN231392 look exactly equals)

Thanks,

**Comment by Koenkk** [comment]
Added. 


Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
