### ISSUE TITLE
Tradfri Linkquality

### ISSUE THREAD

**Issue by sargent-penguin** [Koenkk/zigbee2mqtt#1037]
The link quality of Tradfri bulbs is displayed on the lines in the Graphviz, but not send as a json value in the MQTT topic.

Could this be added as an attribute, to be able to monitor it in home assistant for example?

**Comment by Koenkk** [comment]
TRADFRI bulbs normally don't produce any messages, therefore the linkquality cannot be acquired. Wit h the new reporting functionality they will. Docs: https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/configuration/device_specific_configuration.md

**Comment by frogale** [comment]
Can I ask for more information? Provided link is not working.. :-(

**Comment by Koenkk** [comment]
@frogale https://github.com/Koenkk/zigbee2mqtt.io/blob/master/configuration/device_specific_configuration.md (note that this also requires the dev branch).

**Comment by sargent-penguin** [comment]
Thanks for the info.
Just wondered, because the Osram Smart Plug sends its linkquality already, without the specific config.
Will this behaviour be changed for consistency?

**Comment by Koenkk** [comment]
Thats because the osram plug sends zigbee messages to the coordinator, tradfri bulbs dont do this by default, but should do when using report.

**Comment by sargent-penguin** [comment]
That makes sense!
Thanks for the insight and help!
