### ISSUE TITLE
Feature request: Update Philips hue bulb firmware via zigbee2mqtt

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#1038]
I no longer have a philips hue hub.  I would like to be able to update the firmware on my Philips Hue bulbs though zigbee2mqtt.  Would this be possible or should I buy another hub?

**Comment by Koenkk** [comment]
Are the hue firmwares publicly available?

**Comment by kiwinol** [comment]
It looks like this is already being discussed elsewhere.  I cant find any public repo for them :(
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/270](url)
I will will open a new request if I find a way to get the files.
