### ISSUE TITLE
[Problem]: 

### ISSUE THREAD

**Issue by ybizeul** [Koenkk/zigbee2mqtt#10381]
### What happened?

Configuration (Specific) shows JSON instead of an actual menu or text field.

![image](https://user-images.githubusercontent.com/182035/147450366-99d95e71-1333-42be-ab53-7dfcbfe7ac92.png)

### What did you expect to happen?

I'm assuming this should be displayed as a text field, but "list" type might not be handled by the UI ?

### How to reproduce it (minimal and precise)

Join a RTCGQ11LM Aqara human body movement and illuminance sensor and display the Configuration (Specific) page.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20201026

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

### Debug log

Nothing relevant

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/z2m-frontend/issues
