### ISSUE TITLE
Log too verbose ? 

### ISSUE THREAD

**Issue by H3llK33p3r** [Koenkk/zigbee2mqtt#1039]
Hi just to give a quick feeling on the application. First thank you for this great project.

Am I the only one that consider that sending the JSON message in "zigbee2mqtt:**info** MQTT publish: topic" is too much verbose ? More over the deletion of previous log folders is done only when 10  directories have been created. For me, the project is not restarted very often so logs collected are huge. 

Can you consider to refactor some messages to put them in debug only for example (to avoir to fork this project ^^)  ? 

Thank you in advance for the response.

**Comment by Koenkk** [comment]
The log is automatically rotated, per directory, max 3 files with a max file size of 10mb each are kept.

**Comment by clockbrain** [comment]
Try it with log level of 'warn' which doesn't include the mqtt messages.

**Comment by H3llK33p3r** [comment]
@Koenkk  ok thanks for this information so max 3 * 10 * 10 that's no so bad :) (I do not see the 10Mb part sorry) . 
@clockbrain : it's that I have done.
