### ISSUE TITLE
[Problem]: Tuya TS0216 not router ?

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#10401]
### What happened?

Hello,

I am with raspberry pi4, and zigbeemqtt and a Conbee2 key. All works very well, I just bought this siren: Tuya TS0216 which was paired on my network without problem.
I just have a question this device works with a backup battery and is electrically connected, why suddenly it's not a router?
Thank you

### What did you expect to happen?

Juste one question.

### How to reproduce it (minimal and precise)

Juste one question.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

 0x26680700

### Adapter

ConBee2/RaspBee2

### Debug log

no log
![TS0216](https://user-images.githubusercontent.com/55591810/147549233-2dd7760d-84aa-4c55-8119-2182af696b6b.jpg)

**Comment by Koenkk** [comment]
A mains powered device is not always a router (like in this case). The device type is reported by the device itself, so not something that comes from z2m.

**Comment by kwetnico** [comment]
thanks
