### ISSUE TITLE
[Problem]: 

### ISSUE THREAD

**Issue by jojo1985** [Koenkk/zigbee2mqtt#10457]
### What happened?

I am using zigbee2mqtt in domoticz with the new firmware zStack12 20211115 on a cc2531 stick. Now if I update zigbee with git pull in putty plugins and I restart domoticz service. then changed in domoticz plugin zigbee2mqtt hardware to version (v.3.1.0-beta)
zigbee tab doesn't load anymore and domoticz collapses completely but in putty the zigbee service is active and (running) without any errors. if you update zigbee and you use domoticz check if the version of zigbee has not jumped to version v. 3.1.0-beta this does not work under domoticz hardware

### What did you expect to happen?

why change this plugin to a beta version?

### How to reproduce it (minimal and precise)

not use version v. 3.1.0-beta on domoticz hardware
i use now v.3.0

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

 20211115

### Adapter

CC2531

## v3.0
- Add Universal Adapter
- Ability to disable link quality and battery devices
- Blacklist support to overcome limit of 255 logical devices in Domoticz

**Comment by Koenkk** [comment]
Please create issue related to the zigbee2mqtt domitcz plugin here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
