### ISSUE TITLE
QBKG12LM not compatible with Home Assistant 0.87

### ISSUE THREAD

**Issue by oischinger** [Koenkk/zigbee2mqtt#1046]
I'm running zigbee2mqtt 1.1.1 with Home Assistant 0.87 which seemed to have put more restrictions on the json keys allowed.

“command_topic_prefix” is no longer a valid configuration option, and yet the device sent it as part of the discovery string (it sent ‘command_topic_prefix’: ‘left’). That’s the error.

See the discussion in the Home assistant 0.87 release notes:
https://community.home-assistant.io/t/0-87-smartthings-areas-and-entity-registry-ui/97324/41

**Comment by Koenkk** [comment]
Can you check if this has been fixed in the dev branch?

**Comment by oischinger** [comment]
You're right, it's fixed with commit 7ee6e2c on dev branch. Thanks!
