### ISSUE TITLE
[New device support]: Nous E6 - time settings

### ISSUE THREAD

**Issue by stomko11** [Koenkk/zigbee2mqtt#10470]
### Link

https://nous.technology/product/e6.html

### Database entry

0xa4c138ea9f44ca91 (0x358B)

### Comments

This device is partially supported in the dev branch - exposes temperature, humidity and battery.
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/nous.js

However the device itself features a clock display on the device's display. Once paired, it shows random time (this is not synced with anything). If the device is paired to controller that does not have any converter for the device, it does not show any clock at all. Therefore I assume that due to device being (partially) identified, it shows random clock. It is annoying - I would rather like to see no time than wrong time. Would someone be capable of adding option to either set the correct time, or turn the clock display off?

**Comment by Koenkk** [comment]
Seems the same issue as #10489, should be fixed in the dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
