### ISSUE TITLE
[Problem]: Xiaomi MFKZQ01LM no battery

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#10481]
### What happened?

Hello, I have a problem with the battery information feedback on fronted with my xiaomi cube.
The battery information goes up correctly except on the main page
![1](https://user-images.githubusercontent.com/55591810/147855192-a8b74394-4647-41da-9588-4f34ecbcdb0a.jpg)

![2](https://user-images.githubusercontent.com/55591810/147855193-e0cc61cf-bc6f-4821-b12b-501a3d73e908.jpg)
.

Thanks

### What did you expect to happen?

The battery information goes back correctly like other devices

### How to reproduce it (minimal and precise)

.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

 0x26680700

### Adapter

ConBee2/RaspBee2

### Debug log

![3](https://user-images.githubusercontent.com/55591810/147855292-1e0728b2-6475-48fd-8dde-2bc6e055deef.jpg)

**Comment by kwetnico** [comment]
No idea ? thanks

**Comment by Koenkk** [comment]
Can you upgrade to 1.22.2 and provide the herdsman debug logging when force removing the device and pairing it again?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by kwetnico** [comment]
> Can you upgrade to 1.22.2 and provide the herdsman debug logging when force removing the device and pairing it again?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

I am already in 1.22.2
