### ISSUE TITLE
[Problem]: Node version for Z2M on PI4 ?

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#10482]
### What happened?

Hello, I am using a PI4 with Debian.
i have the latest version of Z2M: 1.22.2 but when i installed i got messages for outdated versions of node and npm.

Which version should I install with Z2M? and what are the commands to update under Debian? 
Thank you

Error : 
![npm install](https://user-images.githubusercontent.com/55591810/147855805-00219f8e-b432-45e9-880c-47fcd0b065fa.jpg)

NPM et NODE Version : 
![version](https://user-images.githubusercontent.com/55591810/147855820-c6ddb2b6-dbab-429b-a190-b6acd274e24c.jpg)

### What did you expect to happen?

Update version.

### How to reproduce it (minimal and precise)

.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

 0x26680700

### Adapter

ConBee2/RaspBee2

### Debug log

.

**Comment by lux73** [comment]
https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing - there are all Information you need.

btw. i'm running z2m under Debian 11 Buster - no problems so far

```
[21:05:57] root@apu:~# node -v
v14.18.1
[21:06:00] root@apu:~# npm -v
8.1.4
[21:06:05] root@apu:~#
```

**Comment by kwetnico** [comment]
> https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing - there are all Information you need.
> 
> btw. i'm running z2m under Debian 11 Buster - no problems so far
> 
> ```
> [21:05:57] root@apu:~# node -v
> v14.18.1
> [21:06:00] root@apu:~# npm -v
> 8.1.4
> [21:06:05] root@apu:~#
> ```

**Comment by kwetnico** [comment]
> > https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing - there are all Information you need.
> > btw. i'm running z2m under Debian 11 Buster - no problems so far
> > ```
> > [21:05:57] root@apu:~# node -v
> > v14.18.1
> > [21:06:00] root@apu:~# npm -v
> > 8.1.4
> > [21:06:05] root@apu:~#
> > ```

Ok but my z2m has been running for over a year but how can I manually update node and npm?

**Comment by lux73** [comment]
https://docs.npmjs.com/cli/v7/commands/npm-update/

`npm update -g` should do

node should be updated via apt update manager - package called nodejs

i could not furnish a guarantee that the cmd's above work without Problems on your System - use it carefully please & **do a backup before proceeding!**

**Comment by kwetnico** [comment]
> https://docs.npmjs.com/cli/v7/commands/npm-update/
> 
> `npm update -g` should do
> 
> node should be updated via apt update manager - package called nodejs
> 
> i could not furnish a guarantee that the cmd's above work without Problems on your System - use it carefully please & **do a backup before proceeding!**

After npm update-g :
![Screenshot_20220101-222427_RaspController](https://user-images.githubusercontent.com/55591810/147860478-fce9c516-7b97-4f7b-bb11-138fa3a6ac1c.jpg)

**Comment by kwetnico** [comment]
I manually install nodejs 14.xx and npm
![Screenshot_20220101-225837_RaspController](https://user-images.githubusercontent.com/55591810/147861019-f15a5817-ada5-429f-9ba6-82cbcf8824a7.jpg)

**Comment by Koenkk** [comment]
The warnings from your first post can be ignored, recommended version can be found here: https://www.zigbee2mqtt.io/guide/installation/01_linux.html#determine-location-of-the-adapter-and-checking-user-permissions 

> node --version  # Should output v10.X, v12.X, v14.X, v15.X or V16.X

**Comment by kwetnico** [comment]
> The warnings from your first post can be ignored, recommended version can be found here: https://www.zigbee2mqtt.io/guide/installation/01_linux.html#determine-location-of-the-adapter-and-checking-user-permissions
> 
> > node --version  # Should output v10.X, v12.X, v14.X, v15.X or V16.X

Thanks but I can't find which version you recommend? V12? V14 or V16 (even if z2M works with all)

**Comment by Koenkk** [comment]
16 then, since it is the latest lts

**Comment by kwetnico** [comment]
> 16 then, since it is the latest lts

I updated to the latest V16.13.1 but apparently you compiled with an older version, Z2M refused to start.
I reinstall node V14 and it is very good for the moment.
