### ISSUE TITLE
No data in Domoticz on new installed BlitzWolf SHP-15 

### ISSUE THREAD

**Issue by WBoerhoop** [Koenkk/zigbee2mqtt#10493]
### What happened?

After installing 1.22.2, pairing was not a problem anymore with blitzWolf SHP-15 and Zigbee2mqtt on Domoticz.
After installation I discovered that no data was imported in Domoticz.

i connected for a test a activated laserprinter to test on BWPL03 between 22:45 and 23:15 ( see log)

![2022-01-01_23-01-47](https://user-images.githubusercontent.com/58995189/147861146-f1d1aec4-8593-4e1d-8daa-87361a88bed4.png)

### What did you expect to happen?

After connecting a device that need power to the plug, so that i can read a power consumption inside Domoticz to perform related actions.

### How to reproduce it (minimal and precise)

connect a laserprinter to BWPL03 test plug and test with printing

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

zStack3x0 20210120

### Adapter

Slaesh's CC2652RB

### Debug log

 info  2022-01-01 22:31:29: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:31:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:31:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":1.07,"energy":78.78,"linkquality":45,"power":208,"state":"ON","voltage":233}'
info  2022-01-01 22:31:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":69,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:31:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":1.07,"energy":78.78,"linkquality":42,"power":208,"state":"ON","voltage":233}'
info  2022-01-01 22:32:54: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":1.07,"energy":78.79,"linkquality":72,"power":208,"state":"ON","voltage":233}'
info  2022-01-01 22:32:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":1.07,"energy":78.79,"linkquality":72,"power":208,"state":"ON","voltage":233}'
info  2022-01-01 22:32:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:32:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:32:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":1.07,"energy":78.79,"linkquality":72,"power":208,"state":"ON","voltage":233}'
info  2022-01-01 22:33:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:33:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.89,"energy":78.79,"linkquality":39,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:33:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:33:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.89,"energy":78.79,"linkquality":42,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:34:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:34:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.79,"linkquality":42,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:34:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:34:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.79,"linkquality":39,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:35:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.79,"linkquality":42,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:35:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.79,"linkquality":42,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:35:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:35:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:36:27: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:36:47: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":69,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:36:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:36:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":72,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:36:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:36:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":72,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:37:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":69,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:37:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":45,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:37:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:37:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":48,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:38:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:38:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":39,"power":152,"state":"ON","voltage":234}'
info  2022-01-01 22:38:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:38:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.8,"linkquality":39,"power":152,"state":"ON","voltage":234}'
info  2022-01-01 22:39:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:39:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.8,"linkquality":39,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:39:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:39:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.8,"linkquality":42,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:40:47: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.81,"linkquality":72,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:40:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.81,"linkquality":72,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:40:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:40:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.81,"linkquality":72,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:40:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:41:26: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:41:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":69,"power":0,"state":"ON","voltage":231}'
info  2022-01-01 22:41:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.81,"linkquality":39,"power":150,"state":"ON","voltage":232}'
info  2022-01-01 22:41:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":231}'
info  2022-01-01 22:41:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.81,"linkquality":39,"power":150,"state":"ON","voltage":232}'
info  2022-01-01 22:42:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":231}'
info  2022-01-01 22:42:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.81,"linkquality":75,"power":148,"state":"ON","voltage":232}'
info  2022-01-01 22:42:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":231}'
info  2022-01-01 22:42:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.81,"linkquality":72,"power":148,"state":"ON","voltage":232}'
info  2022-01-01 22:43:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:43:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.81,"linkquality":72,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:43:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:43:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.81,"linkquality":72,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:44:48: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.9,"energy":78.82,"linkquality":39,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:44:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.82,"linkquality":39,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:44:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:44:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.82,"linkquality":42,"power":150,"state":"ON","voltage":233}'
info  2022-01-01 22:44:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:45:12: MQTT publish: topic 'zigbee2mqtt/Aqara Movement Sensor', payload '{"battery":100,"illuminance":3,"illuminance_lux":3,"linkquality":39,"occupancy":false,"temperature":23,"voltage":3025}'
info  2022-01-01 22:45:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:45:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.89,"energy":78.82,"linkquality":75,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:45:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":72,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:45:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.89,"energy":78.82,"linkquality":75,"power":148,"state":"ON","voltage":233}'
info  2022-01-01 22:46:24: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":232}'
info  2022-01-01 22:46:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:46:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.82,"linkquality":42,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:46:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:46:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.88,"energy":78.82,"linkquality":39,"power":150,"state":"ON","voltage":234}'
info  2022-01-01 22:47:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:47:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.86,"energy":78.82,"linkquality":39,"power":140,"state":"ON","voltage":234}'
info  2022-01-01 22:47:57: MQTT publish: topic 'zigbee2mqtt/BWPL01-Slaapkamer', payload '{"current":0,"energy":3.82,"linkquality":75,"power":0,"state":"ON","voltage":233}'
info  2022-01-01 22:47:57: MQTT publish: topic 'zigbee2mqtt/BWPL02-Zolder', payload '{"current":0.86,"energy":78.82,"linkquality":39,"power":140,"state":"ON","voltage":234}'

**Comment by WBoerhoop** [comment]
on https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html  
In the options I read that the plug must be actively approached to read the electrical data

Options
How to use device type specific configuration

measurement_poll_interval: This device does not support reporting electric measurements so it is polled instead. The default poll interval is 60 seconds, set to -1 to disable. The value must be a number with a minimum value of -1

**Comment by WBoerhoop** [comment]
The function of the switch (on/off) is the only action that works.

**Comment by WBoerhoop** [comment]
Part of DB
{"id":13,"type":"Router","ieeeAddr":"0x540f57fffefdc4ee","nwkAddr":30287,"manufId":4098,"manufName":"**_TZ3000_u5u4cakc**","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":

**Comment by Koenkk** [comment]
Looking at your logs zigbee2mqtt publishes values to MQTT: `'{"current":0.89,"energy":78.82,"linkquality":75,"power":148,"state":"ON","voltage":233}'`, so this seems to be a Domoticz issue to me.

**Comment by WBoerhoop** [comment]
Check, that's right, because BWPL01 and 02 are not SHP-15 but SHP-13 and have been running for a while and working as expected and so is this data.

The 3 new Blitzwolf SHP-15 are new for 2 days, there is no data in the log.
And after I pair them, the only activity that works is turning on and off via the device switch.

Perhaps it have something to do with what i read on https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html

In the options I read that the plug must be actively approached to read the electrical data

"Options
Use device type specific configuration

Measurement_poll_interval: This device does not support electrical measurement reporting, so it is polled instead. The default poll interval is 60 seconds, set to -1 to disable. The value must be a number with a minimum value of -1"

**Comment by Koenkk** [comment]
@WBoerhoop does any value show up when going to the device in the z2m frontend -> exposes -> and refresh the power or energy value?

**Comment by WBoerhoop** [comment]
Will do a test with copy through the laser printer connected to BWPL03 that's a SHP-15, picture voor and after the copy
![voor 2022-01-02_22-52-43](https://user-images.githubusercontent.com/58995189/147890484-badb9ab0-4439-4acc-afdc-4718f803267a.png)
![After 2022-01-02_22-54-28](https://user-images.githubusercontent.com/58995189/147890490-dacf4658-883c-46ed-bfcc-705d348f8522.png)

No difference at all

**Comment by Koenkk** [comment]
Could you provide the zigbee2mqtt debug log at the moment you press the refresh button for power in the z2m frontend?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by WBoerhoop** [comment]
Ohhh, first got an error message that zigbee was already started, then I started domoticz all over again and data came in from the SHP-15 plugs. Please keep an eye on it to see if it continues to work normally, thank you very much in any case.

**Comment by WBoerhoop** [comment]
Everything is working properly, so close the issue
