### ISSUE TITLE
Make entities unavailable when no new messages for specified period of time

### ISSUE THREAD

**Issue by milakov** [Koenkk/zigbee2mqtt#1050]
Hi, is there a way to add new parameter, for example, availability_timeout_passive (default: 0), which is, if not 0, sets entities to unavailable if no messages were received from the corresponding nodes for this period of time? All my sensors are sending I_am_alive messages at least every hour, that would be an easy way to detect if there are any issues with devices.

Thanks!
Max.

**Comment by Koenkk** [comment]
This will be implemented in #775
