### ISSUE TITLE
[Problem]: Non-sensical (?) payload constantly sent from one device after update

### ISSUE THREAD

**Issue by SHxKM** [Koenkk/zigbee2mqtt#10505]
### What happened?

After updating the firmware for a Philips Hue Single Pilar light (I have 3 of them) and Z2M to ver 1.22.2, when I turn on the debug logs I see these messages every 30 seconds:

> Received Zigbee message from 'up_ph_pillar_single_ceiling_1', type 'attributeReport', cluster 'genBasic', data '{"32":"0:PWRON@0","33":10046}' from endpoint 11 with groupID null

### What did you expect to happen?

Not to see this weird payload

### How to reproduce it (minimal and precise)

I'm not sure.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

0x26580700

### Adapter

Conbee II

### Debug log

> Received Zigbee message from 'up_ph_pillar_single_ceiling_1', type 'attributeReport', cluster 'genBasic', data '{"32":"0:PWRON@0","33":10046}' from endpoint 11 with groupID null

**Comment by SHxKM** [comment]
I just found out the device supposedly has a bound like this:
<img width="1642" alt="Screen Shot 2022-01-02 at 15 31 56" src="https://user-images.githubusercontent.com/6573474/147877405-0ba96e4a-6433-4037-ad95-6863f06a8a32.png">

However any attempt to remove this bind fails, either via the UI, or through the MQTT endpoint.

**Comment by SHxKM** [comment]
I finally decided to unpair and repair the device. The problem went away. This can be closed I’ll just leave it to stale.

**Comment by Koenkk** [comment]
Not sure what happend, seems to be a bug on the device side.
