### ISSUE TITLE
[Problem]: MOES BHT-002 Thermostat error

### ISSUE THREAD

**Issue by KameDomotics** [Koenkk/zigbee2mqtt#10519]
### What happened?

Whit last zigbee2mqtt update, in Home Assistant log there is this error:

`Logger: homeassistant.components.mqtt.number
Source: components/mqtt/number.py:173 
Integration: MQTT (documentation, issues) 
First occurred: 20:36:39 (683 occurrences) 
Last logged: 20:50:55

Invalid value for number.termostato_deadzone_temperature: 0 (range 1.0 - 5.0)`

Practically with a deadzone of 0.5 it creates an error (despite the deadzone 0.5 it works).

This forces you to set a deadzone of 1 degree.

This forces you to set a deadzone of 1 degree.

### What did you expect to happen?

X

### How to reproduce it (minimal and precise)

Setting deadzone to 0 (corresponds to 0.5)

### Zigbee2MQTT version

1.22.2-1

### Adapter firmware version

20201010

### Adapter

CC2538

### Debug log

X

**Comment by Koenkk** [comment]
Changed the range min to 0.1

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
