### ISSUE TITLE
How many devices can i connect with 4 cc2531 routers

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#1052]
I looking FAQ for optimal network as i understand CC2531 routers give me max devices to add is that right? Because iam thinking of because Ikea Extender if thats not the case.

**Comment by Koenkk** [comment]
@ptvoinfo Do you know how many devices can connect through the CC2531 router with your firmware? (what's the `NWK_MAX_DEVICE_LIST`?)

**Comment by ptvoinfo** [comment]
`NWK_MAX_DEVICE_LIST` is 21

**Comment by JLFN** [comment]
@Koenkk  does this mean teoretic i can have 15 devices redirect to the cordinator and 21 for each cc2531 router ?  15+21+21+21+21 is that really correct?

**Comment by Koenkk** [comment]
11 to coordinator (15 - 4 routers) + 21 to each router = 95 devices

**Comment by JLFN** [comment]
@Koenkk  @ptvoinfo Can you please add an FAQ that compares the different firmware. Thanks in advance.

**Comment by Koenkk** [comment]
@JLFN done!
