### ISSUE TITLE
[Problem]: QBKG23LM Aqara switch recognized as RTCGQ11LM Aqara motion detector since upgrade to 1.2.2

### ISSUE THREAD

**Issue by bigramonk** [Koenkk/zigbee2mqtt#10541]
### What happened?

After upgrading to 1.2.2, my QBKG23LM Aqara switch shows up as a Xiaomi RTCGQ11LM motion sensor and obviously can no longer be operated remotely as a switch.

### What did you expect to happen?

My QBKG23LM switch to be recognized as a switch and not a motion sensor.

### How to reproduce it (minimal and precise)

Pair a QBKG23LM switch.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20201026

### Adapter

slae.sh_cc2652rb_stick

### Debug log

info  2022-01-03 17:33:54: Zigbee: allowing new devices to join.
info  2022-01-03 17:33:54: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"6nh5u-5"}'
info  2022-01-03 17:34:07: Zigbee: disabling joining new devices.
info  2022-01-03 17:34:08: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"6nh5u-6"}'
info  2022-01-03 17:34:37: Zigbee: allowing new devices to join.
info  2022-01-03 17:34:37: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"dzyuh-4"}'
warn  2022-01-03 17:34:48: Device '0x00158d0005e4ef12' left the network
info  2022-01-03 17:34:49: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0005e4ef12","ieee_address":"0x00158d0005e4ef12"},"type":"device_leave"}'
info  2022-01-03 17:34:49: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00158d0005e4ef12"},"type":"device_removed"}'
info  2022-01-03 17:35:02: Device '0x00158d0005e4ef12' joined
info  2022-01-03 17:35:02: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0005e4ef12","ieee_address":"0x00158d0005e4ef12"},"type":"device_joined"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x00158d0005e4ef12"},"type":"device_connected"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/binary_sensor/0x00158d0005e4ef12/occupancy/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"motion","json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/temperature/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"temperature","enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 temperature","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_temperature_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/illuminance_lux/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"illuminance","enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 illuminance lux","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_illuminance_lux_zigbee2mqtt","unit_of_measurement":"lx","value_template":"{{ value_json.illuminance }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/illuminance/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"device_class":"illuminance","enabled_by_default":false,"json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 illuminance","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_illuminance_zigbee2mqtt","unit_of_measurement":"lx","value_template":"{{ value_json.illuminance }}"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'homeassistant/sensor/0x00158d0005e4ef12/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005e4ef12"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0005e4ef12"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x00158d0005e4ef12","name":"0x00158d0005e4ef12 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0005e4ef12","unique_id":"0x00158d0005e4ef12_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2022-01-03 17:35:02: Starting interview of '0x00158d0005e4ef12'
info  2022-01-03 17:35:02: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0005e4ef12","ieee_address":"0x00158d0005e4ef12","status":"started"},"type":"device_interview"}'
info  2022-01-03 17:35:02: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x00158d0005e4ef12"},"type":"pairing"}'
info  2022-01-03 17:35:03: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0005e4ef12","ieee_address":"0x00158d0005e4ef12"},"type":"device_announce"}'
info  2022-01-03 17:35:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00158d0005e4ef12"},"type":"device_announced"}'
info  2022-01-03 17:35:03: Successfully interviewed '0x00158d0005e4ef12', device has successfully been paired
info  2022-01-03 17:35:03: Device '0x00158d0005e4ef12' is supported, identified as: Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)
info  2022-01-03 17:35:03: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Aqara human body movement and illuminance sensor","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates whether the device detected occupancy","name":"occupancy","property":"occupancy","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Voltage of the battery in millivolts","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"description":"Measured illuminance in lux","name":"illuminance_lux","property":"illuminance","type":"numeric","unit":"lx"},{"access":1,"description":"Measured illuminance in lux","name":"illuminance","property":"illuminance","type":"numeric","unit":"lx"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"RTCGQ11LM","options":[{"access":2,"description":"Time in seconds after which occupancy is cleared after detecting it (default 90 seconds).","name":"occupancy_timeout","property":"occupancy_timeout","type":"numeric","value_min":0},{"access":2,"description":"Sends a message the last time occupancy was detected. When setting this for example to [10, 60] a `{\"no_occupancy_since\": 10}` will be send after 10 seconds and a `{\"no_occupancy_since\": 60}` after 60 seconds.","item_type":"number","name":"no_occupancy_since","property":"no_occupancy_since","type":"list"},{"access":2,"description":"Number of digits after decimal point for illuminance, takes into effect on next report of device.","name":"illuminance_precision","property":"illuminance_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the illuminance value (percentual offset), takes into effect on next report of device.","name":"illuminance_calibration","property":"illuminance_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for illuminance_lux, takes into effect on next report of device.","name":"illuminance_lux_precision","property":"illuminance_lux_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the illuminance_lux value (percentual offset), takes into effect on next report of device.","name":"illuminance_lux_calibration","property":"illuminance_lux_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for temperature, takes into effect on next report of device.","name":"temperature_precision","property":"temperature_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the temperature value (absolute offset), takes into effect on next report of device.","name":"temperature_calibration","property":"temperature_calibration","type":"numeric"}],"supports_ota":false,"vendor":"Xiaomi"},"friendly_name":"0x00158d0005e4ef12","ieee_address":"0x00158d0005e4ef12","status":"successful","supported":true},"type":"device_interview"}'
info  2022-01-03 17:35:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Aqara human body movement and illuminance sensor","friendly_name":"0x00158d0005e4ef12","model":"RTCGQ11LM","supported":true,"vendor":"Xiaomi"},"type":"pairing"}'
info  2022-01-03 17:35:03: MQTT publish: topic 'zigbee2mqtt/0x00158d0005e4ef12', payload '{"battery":null,"illuminance":null,"linkquality":15,"occupancy":null,"temperature":25,"voltage":null}'
info  2022-01-03 17:35:16: Zigbee: disabling joining new devices.
info  2022-01-03 17:35:16: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"dzyuh-5"}'

**Comment by Koenkk** [comment]
Found the issue and fixed it, see https://github.com/Koenkk/zigbee2mqtt/issues/10656#issuecomment-1008048372
