### ISSUE TITLE
Frient device = Develco device

### ISSUE THREAD

**Issue by RitaSghe** [Koenkk/zigbee2mqtt#10543]
### Link

https://frient.com/products/motion-sensor/

### Database entry

xxxx

### Comments

Frient device are clearly Develco device with another brand, but are the same ...
Motion sensor, smart plug, button, door sensor are the same ....

Can you duplicate the Develco device to pairing the Frient devices also?

**Comment by rindlerblabla** [comment]
If you add a Frient device it is successfully added if there's support for the respective Develco device. They share the same ID which is recognised by zigbee2mqtt.

**Comment by RitaSghe** [comment]
Yes, I was hoping so, but .....
FRIENT SMART PLUG: pairing ok but also in state OFF the plug send status constantly, every 2/3 seconds and I don't want this; when the status is ON, yes also for monitoring power, but why in OFF?

FRIENT MOTION SENSOR: unrecognized device but there is in Develco device, the same .....

**Comment by RobLeighton67** [comment]
I'd also raise the issue that the MOSZB-140 motion sensor has very short minimum reporting intervals and low reporting thresholds - my device is reporting Illuminance and Temperature every 12s or so !

**Comment by Claude2666** [comment]
I have also a Frient smart plug, and after pairing, several entries in the reporting tab of the front end appeared to reduce the number of reports. Maybe try remove and pair again?

![image](https://user-images.githubusercontent.com/43413877/148406207-8ca66e22-c3ab-4295-aa74-eca6ebfd9884.png)

I have noticed that for some devices it is possible to control the reporting via the reporting tab, but not for all...

**Comment by RobLeighton67** [comment]
I've solved the issue by modifying the settings for MOSZB-140 in the Develco.js devices file.

**Comment by RitaSghe** [comment]
@Claude2666
Thank you ....
