### ISSUE TITLE
[Problem]:  S26R2ZB goes offline after a period of time

### ISSUE THREAD

**Issue by paul-b-richardson** [Koenkk/zigbee2mqtt#10559]
### What happened?

After some time (24hr +) all my sockets appear offline and are unresponsive unless I turn the off/on physically at the socket.

### What did you expect to happen?

They remain online.

### How to reproduce it (minimal and precise)

Plug the socket in, wait ~24hr and try and access socket via zigbee2mqtt

### Zigbee2MQTT version

1.22.1 commit: 42569d6c

### Adapter firmware version

20211217

### Adapter

slaesh CC2652R stick

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/7806859/log.txt)

**Comment by daufinsyd** [comment]
It seems like we are facing the same issue : #10282

**Comment by Hedda** [comment]
FYI, there is also more general discussions about non-specific performance issues with ITead Sonoff S26R2ZB plugs here -> https://github.com/Koenkk/zigbee2mqtt/discussions/10909
