### ISSUE TITLE
[Problem]: IKEA ICPSHC24-30EU-IL-1 is marked as unsupported device

### ISSUE THREAD

**Issue by BiasF** [Koenkk/zigbee2mqtt#10550]
### What happened?

I tried multiple times to Pair the IKEA ICPSHC24-30EU-IL-1 with no success.
The interview is always failed and the device marked as unsupported. 

- multiple reset. 
- Tried to pair directly near to my Slaesh's CC2652RB stick
- Powered off IKEA bulbs near by

### What did you expect to happen?

Successful paired device because it should be a supported device 

### How to reproduce it (minimal and precise)

- Reset the LED Driver
- Try to pair the Driver

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20201026

### Adapter

Slaesh's CC2652RB 

### Debug log

No logs available (Only interview is failed)

**Comment by airsailor** [comment]
Same problem with sonoff dongle 3.0 plus with the last firmware.
The ICPSHC24-30EU-IL-1 is detected but is not supported by zigbee2mqqt.
Any help?

**Comment by Twit123** [comment]
What does the log have during the interview process, it should show IKEA as the manufacturer and the model number that it is picking up from the unit.

Just checking that Z2M is being given the correct model number from the unit as manufacturers sometimes make small changes.

Simon

**Comment by airsailor** [comment]
> 

Hello Simon.
Thanks for your reply.
I've tried again and again and always the same problem.
My logs are in the attached files
If you have any ideas please let me know.
Thanks
![Uploading IMG_20220108_112220.jpg…]()

**Comment by airsailor** [comment]
> 
![IMG_20220108_112220](https://user-images.githubusercontent.com/69041226/148648682-d568656a-8152-401e-833f-1a57042724fd.jpg)

**Comment by BiasF** [comment]
> ![IMG_20220108_112220](https://user-images.githubusercontent.com/69041226/148648682-d568656a-8152-401e-833f-1a57042724fd.jpg)

Its the same message as for me :(

**Comment by BiasF** [comment]
No idea?

**Comment by airsailor** [comment]
The problem remains.

**Comment by Koenkk** [comment]
The interview is failing, I suggest to first update your coordinator fw since you are running an outdated one (20201026)

**Comment by goddenrich** [comment]
Im having the same issue
```
Starting interview of '0xb4e3f9fffe441ff1'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb4e3f9fffe441ff1","ieee_address":"0xb4e3f9fffe441ff1","status":"started"},"type":"device_interview"}'
Error Failed to interview '0xb4e3f9fffe441ff1', device has not successfully been paired
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb4e3f9fffe441ff1","ieee_address":"0xb4e3f9fffe441ff1","status":"failed"},"type":"device_interview"}'
```

**Comment by danickel** [comment]
@goddenrich Are here any updates? I now bought the same IKEA device and I'm running into the same problem as you. Also using coordinator revision 20211217

**Comment by goddenrich** [comment]
@danickel I didn't get it working and returned the device to IKEA

**Comment by danickel** [comment]
ok thanks for the fast reply. I'm using also the TRADRI power supplies and there are working fine. 
@Koenkk: is there a chance to add support for this device?

**Comment by Koenkk** [comment]
@danickel is is already supported for the `ICPSHC24-30EU-IL-1 `: https://www.zigbee2mqtt.io/devices/ICPSHC24-30EU-IL-1.html#ota-updates

**Comment by yschen5812** [comment]
@danickel  @Koenkk  I guess for some reason there is a newer ICPSHC24-30EU-IL-1 (). I'm not sure if that would make sense to you but I bought my first one last year and was able to check/update the firmware via OTA (20211025 | 2.3.086). Then I bought another one recently, it shows up as ICPSHC24-30EU-IL-1 too however when checking new firmware it always show "No update available". The current firmware is 20181203 | 1.0.002

**Comment by federicosantolini** [comment]
@yschen5812  I can confirm they changed something. The latest LED controllers are always unsupported and all the packaging seems relabeled. I got mine and despite it looking like the same old one, it cannot be paired like the others I bought last year. @Koenkk, is there anything I can send you to check if there is something we can do?
![Immagine WhatsApp 2023-11-26 ore 12 47 23_c6ec08c4](https://github.com/Koenkk/zigbee2mqtt/assets/94896891/62284cd0-ed48-4a94-9c11-7b02b8a98e3b)
![Immagine WhatsApp 2023-11-26 ore 12 36 53_90d92b59](https://github.com/Koenkk/zigbee2mqtt/assets/94896891/18da2b42-fcb6-4c9d-a3e8-9b9663d4dc16)
![Immagine WhatsApp 2023-11-26 ore 12 47 22_11a3d242](https://github.com/Koenkk/zigbee2mqtt/assets/94896891/851be969-1314-40e0-b246-75dd8b78c9f7)
![Immagine WhatsApp 2023-11-26 ore 12 36 37_d46b1a8e](https://github.com/Koenkk/zigbee2mqtt/assets/94896891/c7270235-46c2-4e2f-a2c6-38264cd6a288)
![Immagine WhatsApp 2023-11-26 ore 12 41 17_89c6a0e4](https://github.com/Koenkk/zigbee2mqtt/assets/94896891/9e6bc6f9-ad5f-4195-8c05-28765c80e28c)
