### ISSUE TITLE
Invalid value for max temperature

### ISSUE THREAD

**Issue by michalk-k** [Koenkk/zigbee2mqtt#10564]
### What happened?

For my BRT-100-TRV, Home Assistant reports value out of range for max temperature

```
2022-01-04 12:37:59 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.trv_bedroom_max_temperature: 45 (range 15.0 - 35.0)
```
I can see in z2m GUI, indeed value 45. 
![image](https://user-images.githubusercontent.com/7868445/148064417-b217625f-6de5-4d1f-b9f1-eaccc36d7313.png)

but once I touch it, it turns into 35 as maximum available value. 

![image](https://user-images.githubusercontent.com/7868445/148064691-88597b0a-33f7-430c-8f86-1d03ea0441ef.png)

Have no idea where 45 came from. Anyway it might potentially cause troubles until handled manually

### What did you expect to happen?

No error raised by HA.
Max 35 forced if previous value of 45 is not valid anymore

### How to reproduce it (minimal and precise)

1. using TRV GUI, set max temperature to 45 degree C
2. look at HA logs

### Zigbee2MQTT version

1.22.2-1

### Adapter firmware version

0x26700700

### Adapter

ConBee2

### Debug log

N/A

**Comment by Koenkk** [comment]
This has already been fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3599  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
