### ISSUE TITLE
[Problem]: Livolo TI0001-switch becomes unavailable after pairing

### ISSUE THREAD

**Issue by juanmgimenezmora** [Koenkk/zigbee2mqtt#10568]
### What happened?

I recently bought a new zigbee livolo switch, but they sent me the square format that matches, I believe, the TI0001-switch model,
https://es.aliexpress.com/item/1005003677425366.html?spm=a2g0o.search0304.0.0.714d3093mCmIcR&algo_pvid=97ee60b2-041e-4c1e-9942-b2f3fd6154eb&algo_exp215-ee432e

After several attempts, zigbe2mqtt recognizes it as such, but after successfully pairing it after a few seconds it becomes inaccessible, during the pairing I have been able to turn on the switch from the frontend, but its status is not updated and after those seconds it becomes inaccessible. I think this log shows it clearly

It struck me that the state field goes from ON to OFF by itself. I don't know if it has something to do with the fact that it cannot read the state correctly with the field being OFF or it is simply not supported

Thanks a lot

### What did you expect to happen?

The interreptor should accept the on / off messages and it should be possible to know their status

### How to reproduce it (minimal and precise)

Erasing the device and repairing it after a few seconds, it becomes inaccessible. You can never recover the state

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210319

### Adapter

 zStack3x0

### Debug log

info  2022-01-04 16:32:57: Successfully interviewed '0x00124b0023522804', device has successfully been paired
info  2022-01-04 16:32:57: Device '0x00124b0023522804' is supported, identified as: Livolo Zigbee switch 1 gang (TI0001-switch)
info  2022-01-04 16:32:57: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee switch 1 gang","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TI0001-switch","options":[],"supports_ota":false,"vendor":"Livolo"},"friendly_name":"0x00124b0023522804","ieee_address":"0x00124b0023522804","status":"successful","supported":true},"type":"device_interview"}'
info  2022-01-04 16:32:57: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:32:58: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:32:59: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":30,"state":"OFF"}'
info  2022-01-04 16:33:00: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:33:01: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:33:02: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:33:03: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":27,"state":"OFF"}'
info  2022-01-04 16:33:04: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":30,"state":"OFF"}'
info  2022-01-04 16:33:05: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"OFF"}'
info  2022-01-04 16:33:06: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"OFF"}'
info  2022-01-04 16:33:06: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":30,"state":"OFF","state_left":"ON"}'
info  2022-01-04 16:33:07: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"ON","state_left":"ON"}'
info  2022-01-04 16:33:07: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"OFF","state_left":"ON"}'
info  2022-01-04 16:33:08: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":30,"state":"OFF","state_left":"ON"}'
info  2022-01-04 16:33:09: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"OFF","state_left":"ON"}'
info  2022-01-04 16:33:10: MQTT publish: topic 'zigbee2mqtt/0x00124b0023522804', payload '{"linkquality":33,"state":"OFF","state_left":"ON"}'
error 2022-01-04 16:34:33: Publish 'set' 'state' to '0x00124b0023522804' failed: 'Error: Command 0x00124b0023522804/6 genOnOff.toggle({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":0,"writeUndiv":false}) failed (Timeout - 31992 - 6 - 0 - 6 - 11 after 10000ms)'

**Comment by systemiii** [comment]
@juanmgimenezmora if it helps, you can find my external converter, which supports the new Livolo devices, here #8075
