### ISSUE TITLE
[Problem]: L441C/N4411C/NT4411C dimmer doesn't change the brightness

### ISSUE THREAD

**Issue by drubens** [Koenkk/zigbee2mqtt#10580]
### What happened?

Hello dears,
happy new year!

I'm new on Zigbee2Mqtt so please be patience with me.

I've configured everything and everything seems working correctly on pairing side and HA communication but I'm having some issues with BTICINO stuff.

I've the living now L441C/N4411C/NT4411C dimmer and brightness seems not working. I can switch on and off the light but it is not possible at all dimmer the light.

Moreover all Bticino connected tools got a led that can be configured but I don't find anything about that.

Thanks in advance for any your help.
have a nice rest of 2022.
R

### What did you expect to happen?

Bticino L441C/N4411C/NT4411C should be dimmerable.
Moreover the Light of the led for Bticino connected series tools should be configurable. 

### How to reproduce it (minimal and precise)

Pair the L441C/N4411C/NT4411C with zigbee2Mqtt then try to dimmer. Log show the right message but nothing happens on the light.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210708

### Adapter

Slaesh's CC2652RB stick

### Debug log

info  2022-01-05 00:59:14: Luce Cucina (0x0004740000a20f63): L441C/N4411C/NT4411C - BTicino Dimmer switch with neutral (Router)
debug 2022-01-05 00:59:15: Received MQTT message on 'zigbee2mqtt/bridge/info' with data '{"commit":"unknown","config":{"advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221],"homeassistant_discovery_topic":"homeassistant","homeassistant_legacy_entity_attributes":true,"homeassistant_legacy_triggers":true,"homeassistant_status_topic":"hass/status","last_seen":"disable","legacy_api":true,"log_directory":"/config/special/log","log_file":"log.txt","log_level":"debug","log_output":["console","file"],"log_rotation":true,"log_symlink_current":false,"log_syslog":{},"pan_id":6754,"report":false,"soft_reset_timeout":0,"timestamp_format":"YYYY-MM-DD HH:mm:ss"},"availability":false,"ban":[],"blocklist":[],"device_options":{},"devices":{"0x00047400009370de":{"friendly_name":"Prese Giardino"},"0x0004740000a16698":{"friendly_name":"MAIN Power"},"0x0004740000a1d424":{"friendly_name":"Fuochi"},"0x0004740000a1d42d":{"friendly_name":"Lavastoviglie"},"0x0004740000a1d431":{"friendly_name":"Prese Taverna"},"0x0004740000a1fd8c":{"friendly_name":"Lavanderia"},"0x0004740000a20f63":{"friendly_name":"Luce Cucina"},"0x0004740000a20fbf":{"friendly_name":"Luce giardino"},"0x0004740000a2106c":{"friendly_name":"Luce sala"},"0x0004740000b4dfd5":{"friendly_name":"Luce BOX"},"0x0017880102b10ab0":{"friendly_name":"Luce divano","transition":1},"0x0017880102b22d3d":{"friendly_name":"Luce Pale"},"0x8418260000caa0bb":{"friendly_name":"Luce TV"}},"experimental":{"output":"json"},"external_converters":[],"frontend":{"port":8099},"groups":{},"homeassistant":true,"map_options":{"graphviz":{"colors":{"fill":{"coordinator":"#e04e5d","enddevice":"#fff8ce","router":"#4ea3e0"},"font":{"coordinator":"#ffffff","enddevice":"#000000","router":"#ffffff"},"line":{"active":"#009900 ...
debug 2022-01-05 00:59:15: Received MQTT message on 'zigbee2mqtt/bridge/devices' with data '[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"10":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"11":{"bindings":[],"clusters":{"input":["ssIasAce"],"output":["ssIasZone","ssIasWd"]},"configured_reportings":[],"scenes":[]},"110":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"12":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]},"configured_reportings":[],"scenes":[]},"2":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"242":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"3":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"4":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"47":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"5":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"6":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]},"8":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Coordinator","ieee_address":"0x00124b0022988a3c","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"date_code":"20140331CNWT****","definition":{"description":"Flex RGBW","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightn ...
debug 2022-01-05 00:59:15: Received MQTT message on 'zigbee2mqtt/Luce Cucina/availability' with data 'online'
info  2022-01-05 00:59:15: MQTT publish: topic 'homeassistant/light/0x0004740000a20f63/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"brightness":true,"brightness_scale":254,"command_topic":"zigbee2mqtt/Luce Cucina/set","device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina","schema":"json","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_light_zigbee2mqtt"}'
info  2022-01-05 00:59:15: MQTT publish: topic 'homeassistant/sensor/0x0004740000a20f63/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2022-01-05 00:59:15: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":254,"linkquality":null,"state":"ON"}'
debug 2022-01-05 00:59:15: Received MQTT message on 'homeassistant/light/0x0004740000a20f63/light/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"brightness":true,"brightness_scale":254,"command_topic":"zigbee2mqtt/Luce Cucina/set","device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina","schema":"json","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_light_zigbee2mqtt"}'
debug 2022-01-05 00:59:16: Received MQTT message on 'homeassistant/sensor/0x0004740000a20f63/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2022-01-05 00:59:16: Received MQTT message on 'homeassistant/device_automation/0x0004740000a20f63/action_identify/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"Zigbee2MQTT 1.22.0"},"payload":"identify","subtype":"identify","topic":"zigbee2mqtt/Luce Cucina/action","type":"action"}'
debug 2022-01-05 00:59:16: Received MQTT message on 'homeassistant/light/0x0004740000a20f63/light/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"brightness":true,"brightness_scale":254,"command_topic":"zigbee2mqtt/Luce Cucina/set","device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina","schema":"json","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_light_zigbee2mqtt"}'
debug 2022-01-05 00:59:16: Received MQTT message on 'homeassistant/sensor/0x0004740000a20f63/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x0004740000a20f63"],"manufacturer":"BTicino","model":"Dimmer switch with neutral (L441C/N4411C/NT4411C)","name":"Luce Cucina","sw_version":"0014"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Luce Cucina","name":"Luce Cucina linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Luce Cucina","unique_id":"0x0004740000a20f63_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2022-01-05 00:59:29: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "ON", "brightness": 122}'
debug 2022-01-05 00:59:29: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 00:59:29: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":122,"linkquality":75,"state":"ON"}'
debug 2022-01-05 00:59:30: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "OFF"}'
debug 2022-01-05 00:59:30: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 00:59:31: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":122,"linkquality":75,"state":"OFF"}'
debug 2022-01-05 00:59:32: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "ON"}'
debug 2022-01-05 00:59:32: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 00:59:32: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":122,"linkquality":72,"state":"ON"}'
debug 2022-01-05 00:59:35: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "ON", "brightness": 41}'
debug 2022-01-05 00:59:35: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 00:59:35: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":41,"linkquality":72,"state":"ON"}'
debug 2022-01-05 00:59:37: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "ON", "brightness": 246}'
debug 2022-01-05 00:59:37: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 00:59:37: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":246,"linkquality":72,"state":"ON"}'
debug 2022-01-05 00:59:39: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "OFF"}'
debug 2022-01-05 00:59:39: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 00:59:39: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":246,"linkquality":72,"state":"OFF"}'
debug 2022-01-05 00:59:39: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state": "ON"}'
debug 2022-01-05 00:59:39: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 00:59:39: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":246,"linkquality":75,"state":"ON"}'
debug 2022-01-05 01:00:26: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"brightness":72}'
debug 2022-01-05 01:00:26: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 01:00:26: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":72,"linkquality":78,"state":"ON"}'
debug 2022-01-05 01:00:29: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state":"OFF"}'
debug 2022-01-05 01:00:29: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 01:00:29: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":72,"linkquality":78,"state":"OFF"}'
debug 2022-01-05 01:00:29: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state":"ON"}'
debug 2022-01-05 01:00:29: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 01:00:29: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":72,"linkquality":81,"state":"ON"}'
debug 2022-01-05 01:00:32: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"brightness":254}'
debug 2022-01-05 01:00:32: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 01:00:32: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":254,"linkquality":78,"state":"ON"}'
debug 2022-01-05 01:00:33: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"brightness":114}'
debug 2022-01-05 01:00:33: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 01:00:33: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":114,"linkquality":78,"state":"ON"}'
debug 2022-01-05 01:00:35: Received MQTT message on 'zigbee2mqtt/Luce Cucina/get' with data '{"brightness":""}'
debug 2022-01-05 01:00:35: Publishing get 'get' 'brightness' to 'Luce Cucina'
debug 2022-01-05 01:00:35: Received Zigbee message from 'Luce Cucina', type 'readResponse', cluster 'genLevelCtrl', data '{"currentLevel":254}' from endpoint 1 with groupID 0
info  2022-01-05 01:00:35: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":254,"linkquality":78,"state":"ON"}'
debug 2022-01-05 01:00:36: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"brightness":17}'
debug 2022-01-05 01:00:36: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 01:00:36: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":17,"linkquality":69,"state":"ON"}'
debug 2022-01-05 01:00:39: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state":"OFF"}'
debug 2022-01-05 01:00:39: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 01:00:39: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":17,"linkquality":78,"state":"OFF"}'
debug 2022-01-05 01:00:41: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"state":"ON"}'
debug 2022-01-05 01:00:41: Publishing 'set' 'state' to 'Luce Cucina'
info  2022-01-05 01:00:41: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":17,"linkquality":78,"state":"ON"}'
debug 2022-01-05 01:00:43: Received MQTT message on 'zigbee2mqtt/Luce Cucina/set' with data '{"brightness":254}'
debug 2022-01-05 01:00:43: Publishing 'set' 'brightness' to 'Luce Cucina'
info  2022-01-05 01:00:43: MQTT publish: topic 'zigbee2mqtt/Luce Cucina', payload '{"brightness":254,"linkquality":78,"state":"ON"}'

**Comment by Yonn-Trimoreau** [comment]
You should:
- Reset & associate your device back to the official BTicino gateway
- Wait for 24 hours for your device's firmware to be upgraded
- Reset & associate your device to your own Zigbee gateway
- Upgrade zigbee2mqtt to the latest version
- Enable dimmer & define values for ballast_minimum_level and ballast_maximum_level (1 and 254 usually)
- Try again setting the brightness

**Comment by drubens** [comment]
Thank you @Yonn-Trimoreau  sorry for my late answer.
I will try to do that but I'm not sure if I got how can I do that (Enable dimmer & define values for ballast_minimum_level and ballast_maximum_level (1 and 254 usually). Maybe this is my issue, I've not activated something.

let's keep updated.
Grazie grazie
R

**Comment by drubens** [comment]
@Yonn-Trimoreau unfortunately I followed what you suggested but no way to have Brightness.
I've also updated the slaesh usb coordinator.
the firmware of the dimmer looks the "20" on home+control app and after 1 week nothing updated and fw is still "20".

Any suggestion or different procedure that should I've to follow please? Any other user is experiencing same issue with dimmer?

thanks again yonn and everybody.
ciao

**Comment by drubens** [comment]
I see full setup now.
Fixed.
Thanks for all your work.

![20220202_102449](https://user-images.githubusercontent.com/90654490/152127226-e73588e3-7dcf-4ca4-b4dc-2d6fe167415c.jpg)
