### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by mchacher** [Koenkk/zigbee2mqtt#1058]
Hi,

I am trying to add a new device, and this device is not reporting anything. The documentation specifies that in this case, one should add a configure section ... unfortunately, the link to the examples is broken. Can you fix it?
_"In case your device is not reporting anything, it could be that this device requires additional configure. This can be done by adding a configure: section, **examples**."_

Thanks

Marc

**Comment by Koenkk** [comment]
fixed, thanks!
