### ISSUE TITLE
Xiaomi H1 with neutral WS-EUK04 not updating status's [Problem]: 

### ISSUE THREAD

**Issue by daserra23** [Koenkk/zigbee2mqtt#10586]
### What happened?

This 2 way switch won't update it's status's in the frontend unless I click "refresh" in the "exposes" tab. It worked with the previous version. 

Re-adding the device doesn't change anything, not does enabling or disabling "control relay/decoupled".

I would be interested in learning if/how I can downgrade to the previous version, I am struggling to find any information on this. I am on Raspbian Buster.

### What did you expect to happen?

I expected that the frontend would show the updated status after pressing either button but it doesn't and therefore actions supposedly triggered by the buttons are not triggered.

### How to reproduce it (minimal and precise)

Press the right button, observe the non-reaction of the device in the frontend, then click the "state_right" refresh icon and watch the status update.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210120

### Adapter

Slaesh CC2652RB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/7814984/log.txt)

**Comment by daserra23** [comment]
After some testing I have fixed this issue by configuring the reporting manually. Not too much spamming with these settings.
![switch](https://user-images.githubusercontent.com/94075121/148255441-1d351959-38d0-4889-a50c-97f683b4b757.jpg)

**Comment by ilvi80** [comment]
Не работает отвязка клавиш. Не переключает в логический режим
