### ISSUE TITLE
[Problem]: Xiaomi QBKG23LM reports wrong device attributes after pairing

### ISSUE THREAD

**Issue by sll1001** [Koenkk/zigbee2mqtt#10610]
### What happened?

I am new to Zigbee2MQTT. Starting to use it with the latest software and firmware. 

I have paired a Aqara D1 3 gang switch with neutral wire (QBKG26LM) and it seems to work correctly. I am using homebridge plugin homebridge-z2m to connect to homekit and it works almost the same as it was connected to Aqara gateway.

However, I got a different behaviour with the Aqara D1 single switch with neutral wire (QBKG23LM). After pairing is successful, QBKG23LM appears in the Devices screen on the Frontend. Strangely the Power attribute is reported as "?" whereas the 3 gang switch reported correctly as AC wired.

Looking at the MQTT devices topic, QBKG23LM is reported as battery powered and is an "Enddevice"
Inside IOS Home App, the device differs from the 3 gang device. It doesn't allow me to set the room for the device as I can do with the gang device.

  {
    "definition": {
      "description": "Aqara D1 1 gang smart wall switch (with neutral wire)",
      "exposes": [
        {
          "features": [
            {
              "access": 7,
              "description": "On/off state of the switch",
              "name": "state",
              "property": "state",
              "type": "binary",
              "value_off": "OFF",
              "value_on": "ON",
              "value_toggle": "TOGGLE"
            }
          ],
          "type": "switch"
        },
        {
          "access": 5,
          "description": "Instantaneous measured power",
          "name": "power",
          "property": "power",
          "type": "numeric",
          "unit": "W"
        },
        {
          "access": 1,
          "description": "Sum of consumed energy",
          "name": "energy",
          "property": "energy",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Measured temperature value",
          "name": "temperature",
          "property": "temperature",
          "type": "numeric",
          "unit": "°C"
        },
        {
          "access": 1,
          "description": "Measured electrical potential value",
          "name": "voltage",
          "property": "voltage",
          "type": "numeric",
          "unit": "V"
        },
        {
          "access": 1,
          "description": "Triggered action (e.g. a button click)",
          "name": "action",
          "property": "action",
          "type": "enum",
          "values": [
            "single",
            "release"
          ]
        },
        {
          "access": 7,
          "description": "Decoupled mode",
          "name": "operation_mode",
          "property": "operation_mode",
          "type": "enum",
          "values": [
            "control_relay",
            "decoupled"
          ]
        },
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "QBKG23LM",
      "options": [
        {
          "access": 2,
          "description": "Number of digits after decimal point for temperature, takes into effect on next report of device.",
          "name": "temperature_precision",
          "property": "temperature_precision",
          "type": "numeric",
          "value_max": 3,
          "value_min": 0
        },
        {
          "access": 2,
          "description": "Calibrates the temperature value (absolute offset), takes into effect on next report of device.",
          "name": "temperature_calibration",
          "property": "temperature_calibration",
          "type": "numeric"
        }
      ],
      "supports_ota": false,
      "vendor": "Xiaomi"
    },
    "endpoints": {
      "1": {
        "bindings": [],
        "clusters": {
          "input": [],
          "output": []
        },
        "configured_reportings": [],
        "scenes": []
      }
    },
    "friendly_name": "Utility Room Light",
    "ieee_address": "0x00158d0004525b09",
    "interview_completed": true,
    "interviewing": false,
    "manufacturer": "LUMI",
    "model_id": "lumi.switch.b1nacn02",
    "network_address": 59435,
    "power_source": "Battery",
    "supported": true,
    "type": "EndDevice"
  }

### What did you expect to happen?

The switch should be reported as a Router and "Mains (single phasse)" as power_source.

Its behaviour inside Homekit should be the same as a normal smart switch which allows me to select which room it is in.

### How to reproduce it (minimal and precise)

Pairing the device.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Debug log

Debug log while pairing.

nfo Device '0x00158d0004525b09' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0004525b09","ieee_address":"0x00158d0004525b09"},"type":"device_joined"}'
Info Starting interview of '0x00158d0004525b09'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0004525b09","ieee_address":"0x00158d0004525b09","status":"started"},"type":"device_interview"}'
Debug Device '0x00158d0004525b09' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d0004525b09","ieee_address":"0x00158d0004525b09"},"type":"device_announce"}'
Debug Received MQTT message on 'zigbee2mqtt/0x00158d0004525b09/get' with data '{"state":0}'
Debug Publishing get 'get' 'state' to '0x00158d0004525b09'
Debug Received Zigbee message from '0x00158d0004525b09', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x00158d0004525b09', payload '{"linkquality":69,"state":"OFF"}'
Debug Received Zigbee message from '0x00158d0004525b09', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x00158d0004525b09', type 'attributeReport', cluster 'genBasic', data '{"appVersion":1,"modelId":"lumi.switch.b1nacn02"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x00158d0004525b09', type 'read', cluster 'genTime', data '["time"]' from endpoint 1 with groupID 0
Info Successfully interviewed '0x00158d0004525b09', device has successfully been paired
Info Device '0x00158d0004525b09' is supported, identified as: Xiaomi Aqara D1 1 gang smart wall switch (with neutral wire) (QBKG23LM)
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Aqara D1 1 gang smart wall switch (with neutral wire)","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":5,"description":"Instantaneous measured power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":1,"description":"Sum of consumed energy","name":"energy","property":"energy","type":"numeric","unit":"kWh"},{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Measured electrical potential value","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single","release"]},{"access":7,"description":"Decoupled mode","name":"operation_mode","property":"operation_mode","type":"enum","values":["control_relay","decoupled"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"QBKG23LM","options":[{"access":2,"description":"Number of digits after decimal point for temperature, takes into effect on next report of device.","name":"temperature_precision","property":"temperature_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the temperature value (absolute offset), takes into effect on next report of device.","name":"temperature_calibration","property":"temperature_calibration","type":"numeric"}],"supports_ota":false,"vendor":"Xiaomi"},"friendly_name":"0x00158d0004525b09","ieee_address":"0x00158d0004525b09","status":"successful","supported":true},"type":"device_interview"}'
Debug Received Zigbee message from '0x00158d0004525b09', type 'attributeReport', cluster 'genBasic', data '{"65281":{"100":0,"149":58.063045501708984,"152":0,"154":0,"3":24,"5":22,"8":4159,"9":256}}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x00158d0004525b09', payload '{"consumption":58.06,"energy":58.06,"linkquality":61,"power":0,"state":"OFF","temperature":24}'
Debug Saving state to file /app/data/state.json

**Comment by Koenkk** [comment]
Forced it to be a mains powered router now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
