### ISSUE TITLE
Integration of iaomi Mijia Temperature & Humidity Sensor (display version) 

### ISSUE THREAD

**Issue by knopserl** [Koenkk/zigbee2mqtt#1061]
I wanted to integrate a new prmising device from Xiaomi from the Mijia series, a Temp/Hum sensor with display, but can't get it to pair with zigbee2mqtt.
I have tried to follow exactly the instructions to flash/install zigbee2mqtt und the CC2531 seem to be recognized, read the firmware version and is seeking for new devices allowing theme to join.
I think I have found out the reason, why did devices might not work: it's using bluetooth rather than zigbee. THis is the model: YWSDCGQ/01ZM
Here is a shop link:
https://de.aliexpress.com/item/Xiaomi-Mijia-Bluetooth-Hygrothermograph-High-Sensitive-Hygrometer-Thermometer-LCD-Bildschirm-Smart-Home-Temperatur-Feuchtigkeit-Sensor/32846083629.html?spm=a2g0s.9042311.0.0.27424c4d5xBXks

Is there any chance to include with the zigbee coordinator HW and or zigbee2mqtt or do I need a parall pure bluetooth dongle or the PI 3B+ internal bluetooth to integrate it and the CC2531 and the zigbee coordinatore is unusable for integration with it or could it be extended to also include the new Xiaomi Mijia BT devices ? Or do I need to flash another firmware to the CC2531 to get it paired?
I have seen people integrating it with BT HW and a script running in a cron job (I did nit like that so much, it's a fallback solution for me).

Here is the zigbee2mqqt log at startup and it does not react on pairing request from the sensor (BT icon is blinking)

 zigbee2mqtt:info 2019-2-10 14:43:54 Logging to directory: '/opt/zigbee2mqtt/data/log/2019-02-10.14-43-54'
  zigbee2mqtt:info 2019-2-10 14:43:55 Starting zigbee2mqtt version 1.1.1 (commit #a497cf0)
  zigbee2mqtt:info 2019-2-10 14:43:55 Starting zigbee-shepherd
  zigbee2mqtt:info 2019-2-10 14:43:56 zigbee-shepherd started
  zigbee2mqtt:info 2019-2-10 14:43:56 Coordinator firmware version: '20190109'
  zigbee2mqtt:info 2019-2-10 14:43:56 Currently 0 devices are joined:
  zigbee2mqtt:warn 2019-2-10 14:43:56 `permit_join` set to  `true` in configuration.yaml.
  zigbee2mqtt:warn 2019-2-10 14:43:56 Allowing new devices to join.

**Comment by Koenkk** [comment]
Bluetooth devices cannot be paired to zigbee2mqtt. Zigbee2mqtt only supports zigbee devices.
