### ISSUE TITLE
[Problem]: ZemiSmart Smart 6 key scene switch does not work

### ISSUE THREAD

**Issue by RJArmitage** [Koenkk/zigbee2mqtt#10615]
### What happened?

1.22.2 adds support for the Smart 6 key scene switch from ZemiSmart. Using this version, and also with hassio-edge I can add the device and it claims to be supported. However the buttons don't do anything. Checking the log I see that a command message is received but that zb2m reports there is no converter

### What did you expect to happen?

Clicking on a device button should send an action message

### How to reproduce it (minimal and precise)

1. Pair device
2. Wait for interview to complete
3. Click on a device button

### Zigbee2MQTT version

1.22.2-dev commit: 43ded11

### Adapter firmware version

0x26660700

### Adapter

ConBee2

### Debug log

![Screenshot 2022-01-06 at 13 36 35](https://user-images.githubusercontent.com/60395804/148392382-a9355a40-cc39-4842-b124-f389ac535a12.png)
![Screenshot 2022-01-06 at 13 43 17](https://user-images.githubusercontent.com/60395804/148392431-fffaf1d2-5dbc-4925-8ee4-3a29362b4b55.png)

**Comment by Koenkk** [comment]
Did an attempt to fix it, could you check if it works?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by RJArmitage** [comment]
I'm using the hassio plugin so I'll need to wait for the edge plugin build to include your change. I'll let you know...

**Comment by RJArmitage** [comment]
Have retested - that change seems to have got the messages flowing. However I now see that it is not handling battery reporting properly. The battery state is sent as a 4 byte integer in DP10. However the plugin is treating this as an unknown action message for button 10. So I would say that for dp10 you could parse as: 
```
const button = dpValue.dp;
if (button == 10) {
    const batteryValue = tuya.getDataValue(dpValue);
    return {battery: batteryValue};
} else { 
    const actionValue = tuya.getDataValue(dpValue);
    ....
    return {action: `button_${button}_${action}`};
}
```
and resurrect 
```
    exposes: [e.battery(), e.action([...
```

**Comment by DHM47** [comment]
The device is working again with the latest edge version

**Comment by Koenkk** [comment]
@RJArmitage applied, can this be closed?

**Comment by RJArmitage** [comment]
I can retest tomorrow morning. I’ll let you know if we’re all ok.

**Comment by RJArmitage** [comment]
Have retested the latest dev. All seems to be working correctly. Battery is being reported correctly and appears in Home Assistant. I think we can close this now. Thanks.

**Comment by RJArmitage** [comment]
> I just tested and everything is working.
> @RJArmitage thanks for solving the battery reading.

No problem

**Comment by DavidFFerreira** [comment]
no probleme now, everything works great :D
