### ISSUE TITLE
TRADFRIbulbE27WSglobeopal1055lm Support status      Unsupported

### ISSUE THREAD

**Issue by tiesto4ever** [Koenkk/zigbee2mqtt#10625]
### Link

https://www.ikea.com/nl/en/p/tradfri-led-bulb-e27-1055-lumen-wireless-dimmable-white-spectrum-globe-opal-white-40486783/

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0x2c1165fffec040a8","nwkAddr":52807,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRIbulbE27WSglobeopal1055lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRIbulbE27WSglobeopal1055lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":3,"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20201111","swBuildId":"1.0.012"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20201111","swBuildId":"1.0.012","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1641496579749}

### Comments

This IKEA light bulb should be supported, but adding it to my zigbee2mqtt gave this "unsupported" status. 
Please assist

### Supported color modes

white spectrum/globe opal white

**Comment by Koenkk** [comment]
`TRADFRIbulbE27WSglobeopal1055lm` is supported in zigbee2mqtt 1.22.1

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
