### ISSUE TITLE
Previous Firmware Versions

### ISSUE THREAD

**Issue by lonebaggie** [Koenkk/zigbee2mqtt#1063]
Did you read the FAQ?
https://koenkk.github.io/zigbee2mqtt/information/FAQ.md

Yes

Unsupported device?
https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html

Yes

A question?
Read the documentation: https://koenkk.github.io/zigbee2mqtt/

Yes

Bug report:
- First make sure your on the latest version of zigbee2mqtt.
- Make sure you are running the latest CC253X firmware from https://github.com/koenkk/z-stack-firmware.
- Provide a clear description of the problem.
- If applicable, provide steps how to reproduce the problem.
- Provide a log with `log_level` set to `debug`, see https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html
- DON'T copy logs directly here, post a link to https://hastebin.com/ or https://pastebin.com/.

I have been running Zigbee2mqtt for awhile with 6 tradfri bulbs. I updated to the latest firmware to test groups so I could dim the lights. Now Im getting errors and reboots of the zigbee Shepard. Where can I downgrade to a previous version to eliminate other errors

**Comment by Koenkk** [comment]
`20181024`: https://github.com/Koenkk/Z-Stack-firmware/blob/f4f0e66902eb143c59f1c5208d4ef61094ba344e/coordinator/CC2531/bin/CC2531ZNP-Prod_20181024.zip

**Comment by lonebaggie** [comment]
Thank you
