### ISSUE TITLE
[New device support]: Evanell EZ200

### ISSUE THREAD

**Issue by tux2000** [Koenkk/zigbee2mqtt#10636]
### Link

https://www.amazon.co.uk/Evanell%C2%B0-Thermostat-Starterskit-Intelligent-Programmable/dp/B08RBC838L?th=1

### Database entry

{"Id":2,"Type":"Enddevice","Ieeeaddr":"0x9035eafffe34b766","Nwkaddr":5245,"Manufid":4098,"Manufname":"_Tze200_Dmfguuli","Powersource":"Battery","Modelid":"Ts0601","Eplist":[1],"Endpoints":{"1":{"Profid":260,"Epid":1,"Devid":81,"Inclusterlist":[0,4,5,61184],"Outclusterlist":[25,10],"Clusters":{"Genbasic":{"Attributes":{"65503":"%�J)\U0011","65506":31,"65508":0,"Modelid":"Ts0601","Manufacturername":"_Tze200_Dmfguuli","Powersource":3,"Zclversion":3,"Appversion":70,"Stackversion":0,"Hwversion":1,"Datecode":""}}},"Binds":[{"Cluster":0,"Type":"Endpoint","Deviceieeeaddress":"0x00124b001cd49c8f","Endpointid":1}],"Configuredreportings":[],"Meta":{}}},"Appversion":70,"Stackversion":0,"Hwversion":1,"Datecode":"","Zclversion":3,"Interviewcompleted":True,"Meta":{"Configured":821693351},"Lastseen":1641555845204,"Useimplicitcheckin":True}

### Comments

I have managed to get basic functions supported and will add a PR to https://github.com/Koenkk/zigbee-herdsman-converters soon

**Comment by Koenkk** [comment]
added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3635
