### ISSUE TITLE
"User ratings" for devices database

### ISSUE THREAD

**Issue by rsteininger** [Koenkk/zigbee2mqtt#10634]
### Is your feature request related to a problem? Please describe

I have been following zigbee2mqtt for a while and I am very much impressed with all the work that goes into running and maintaining this website! The device section has grown to very impressive dimensions!

I have one "big" request though - as new devices flood the market, when researching a "fit" for a planned home automation expansion, I more and more turn to your website to look up devices that have been integrated already. 

However, as I had to find out "painfully" myself with a growing pile of bought but soon discarded zigbee devices, "not all are being built equal".  

### Describe the solution you'd like

And thus, I was wondering, if it is possible to add a user rating / experience feedback to your device section. I am not 100% certain myself on which categories to rate the devices on and how to verify that this is real feedback (and not a personal vendetta against the device / manufacturer) but things like: 
- "ease of integration" (any tricks to be performed for integration?), 
- "functionality" (does the device really do what it claims to do, e.g. a number of thermometers have infrequent temperature updates or the brightness value of some of my motion sensors are next to useless) and 
- "long term stability" (meaning, is the device e.g. prone to drop off an active connection and needs to be re-paired to resume services), etc. etc. Maybe also something 
- to rate real life battery consumption, etc. 

I would think this would add a lot of value to users like myself! And I would be more than happy to share my experiences on the (countless - at least that is what it feels like it?) devices I have and had in use! 

Thanks for your consideration! 

### Describe alternatives you've considered

I am not aware of another portal. Reviews on e.g. Aliexpress are not "really" device related rather than are tagged to the seller. 
Same on ebay and Amazon is rather limited on that front as well. 

### Additional context

nothing to add, sorry!

**Comment by Fabiancrg** [comment]
Totally agree with you, would be nice to see comments from users.
Also, some devices supported by Z2M are impossible to buy online so if possible to add links to online stores too.
