### ISSUE TITLE
[Problem]: Aqara devices are not connected to CC2530 router

### ISSUE THREAD

**Issue by shalwia** [Koenkk/zigbee2mqtt#10642]
### What happened?

I was using Zigbee2MQTT for about two years. After reinstalling of the network (due to the Raspberry malfunction), I noticed none of the Aqara devices are connecting to the CC2530 router, but they're getting into the connection with the coordinator directly (despite the fact coordinator is located far from part of the sensors than the router).

### What did you expect to happen?

I expected that the sensors located close to router are to going to connect directly to that device.

### How to reproduce it (minimal and precise)

I don't know how to reproduce the problem.

### Zigbee2MQTT version

 1.22.2 commit: 301ba14b

### Adapter firmware version

20210120

### Adapter

zStack3x0

### Debug log

![75706D3A-CD4C-4D7A-B258-A4001D11A830](https://user-images.githubusercontent.com/52470311/148550704-8b04e043-1081-4047-ba92-242034ba1ff4.jpeg)

**Comment by Koenkk** [comment]
This is a known issue, see https://www.zigbee2mqtt.io/guide/faq/#why-are-some-links-missing-from-my-networkmap
