### ISSUE TITLE
[Problem]: TuYa TS0601_thermostat gui programing mode not working, work only from publish mqtt

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#10641]
### What happened?

TuYa TS0601_thermostat gui programing mode not working work, only from publish mqtt

![image](https://user-images.githubusercontent.com/59237288/148550082-a747a508-4aec-4e08-90df-d89cf9df32dd.png)

Clicking on the gui got nothing happening. Checking with MQTT Explorer changes in section programing_mode don't publish changes in mqtt.

### What did you expect to happen?

I should change programing mode in web gui.

### How to reproduce it (minimal and precise)

Open web gui and ctry change something in programming_mode section.

### Zigbee2MQTT version

 1.22.2 

### Adapter firmware version

20211217

### Adapter

Slaesh's CC2652RB

### Debug log

No appear error in logs.

**Comment by buddy31130** [comment]
same for me. The values do not show up in GUI but when modified, it is published in MQTT

**Comment by garykrige** [comment]
Same for me
