### ISSUE TITLE
Question: MQTT Broker

### ISSUE THREAD

**Issue by imbaimbaimba** [Koenkk/zigbee2mqtt#1066]
Hi!
So I know zero about MQTT, but I want to set up Zigbee/2mqtt to get my Xiaomi stuff to Home Assistant without a bridge and Chinese cloud.
I could not find anything in your documentation about broker, other than adding it. Any good resource to go for, for this? I would like to learn about broker in a way specific to this usecase.
Also, can I run Home Assistant, MQTT broker and Zigbee2mqtt on one Raspberry Pi B 3+?
Thanks in advance !

**Comment by clockbrain** [comment]
You can use any MQTT broker - that's the point. Easiest to setup would be the [embedded one in Home Assistant](https://www.home-assistant.io/components/mqtt/).

A good way to get started is Hassio plus zigbee2mqtt addon - [https://github.com/danielwelch/hassio-zigbee2mqtt](https://github.com/danielwelch/hassio-zigbee2mqtt)

Info on Mqtt is everywhere - e.g. [http://www.steves-internet-guide.com/install-mosquitto-linux/](http://www.steves-internet-guide.com/install-mosquitto-linux/). I also recommend getting a desktop MQTT client such as mqtt.fx so you can easily monitor and interact with zigbee2mqtt.

Yes, you can run all this on one Raspberry Pi B 3+ however that would only be advisable for an experimental setup. Home Assistant can be heavy on writes to storage which can kill the sd card over time. For a more stable setup either switch to disk storage for the Pi or run the Home Assistant portion elsewhere. My setup is Home Assistant and MQTT broker as 2 docker containers on Synology NAS and zigbee2mqtt on a Raspberry Pi.
