### ISSUE TITLE
Module Import failed: ' Name: DomoticzEx'[Problem]: 

### ISSUE THREAD

**Issue by NicoWasserman** [Koenkk/zigbee2mqtt#10679]
### What happened?

Starting domoticz creates a error in the log when starting zigbee2mqtt

### What did you expect to happen?

ik was hoping to add zigbee2mqtt to my domoticz

### How to reproduce it (minimal and precise)

restart domoticz

### Zigbee2MQTT version

Zigbee2MQTT Plugin (v. 3.1.0-beta)

### Adapter firmware version

?

### Adapter

Texas Instruments CC2351

### Debug log

022-01-09 18:50:08.810 Error: Zigbee2MQTT: (Zigbee2MQTT) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/zigbee2mqtt/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2022-01-09 18:50:08.810 Error: Zigbee2MQTT: (Zigbee2MQTT) Module Import failed, exception: 'ModuleNotFoundError'
2022-01-09 18:50:08.810 Error: Zigbee2MQTT: (Zigbee2MQTT) Module Import failed: ' Name: DomoticzEx'
2022-01-09 18:50:08.810 Error: Zigbee2MQTT: (Zigbee2MQTT) Error Line details not available.

**Comment by Koenkk** [comment]
Issues related to the domticz plugin should be created here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
