### ISSUE TITLE
[Problem]:  Danfoss 014G2461

### ISSUE THREAD

**Issue by 2Max2Pax** [Koenkk/zigbee2mqtt#10678]
### What happened?

I have 9 Danfoss 014G2461, every 2-3 hours zigbee2mqtt stops communicating with one or two devices (not always the same one) in both directions.
The only way to restart the communication is restarting zigbee2mqtt.
I cannot see any error in the logs of z2m or mosquitto.

### What did you expect to happen?

Once started the communication shold be stable.

### How to reproduce it (minimal and precise)

Try to change the temperature publishing:
Topic: zigbee2mqtt/FRIENDLY_NAME/set
Payload: {"occupied_heating_setpoint":TEMPERATURE}

### Zigbee2MQTT version

1.22.2 commit: 414c51f

### Adapter firmware version

20211217

### Adapter

Gio-dot Z-Bee Duo with CC2652P

### Debug log

[logz2m.txt](https://github.com/Koenkk/zigbee2mqtt/files/7835606/logz2m.txt)
The device that is not working is :
```
0x84fd27fffed4388c:
friendly_name: trv_ingresso
```
All TRVs' friendly names are: trv_XXXX

**Comment by lux73** [comment]
how many other Devices so you have?

How many Routers/Bulb, which Manufacturer?

I have some Danfoss too - there ist no problem with communication so far...

**Comment by 2Max2Pax** [comment]
28 devices:
17 Vimar switches that act as routers
9 Danfoss 014G2461 (battery)
1 Aqara WSDCGQ11LM (battery)
1 Aqara MCCGQ11LM (battery)

**Comment by lux73** [comment]
don't know the mentioned Vimar Switches

but had same some serious issues with some Zigbee Devices that act as Router: eg IKEA Bulbs und lastly with a MiBoxer RGB CCT Controller - they work terrible as Router. I had to remove them to stabilize my Network :-(

even don't know your Coordintor: Gio-dot Z-Bee Duo with CC2652P

lastly another User had serious Problems with a ConBee Stick: https://github.com/Koenkk/zigbee2mqtt/discussions/10119#discussioncomment-1865407

**Comment by 2Max2Pax** [comment]
> 
> don't know the mentioned Vimar Switches
> 

See: [Vimar 14592](https://www.zigbee2mqtt.io/devices/14592.0.html) 

> but had same some serious issues with some Zigbee Devices that act as Router: eg IKEA Bulbs und lastly with a MiBoxer RGB CCT Controller - they work terrible as Router. I had to remove them to stabilize my Network :-(
> 

This would be the last chance, I spent over 500 Eur for those switches. 
For the time being I created an automation that restarts z2m every hour .....

> even don't know your Coordintor: Gio-dot Z-Bee Duo with CC2652P

See: [Z Bee Duo](https://github.com/Gio-dot/Z-Bee-Duo)
There are no issues about it as far as I know

**Comment by lux73** [comment]
> This would be the last chance, I spent over 500 Eur for those switches. For the time being I created an automation that restarts z2m every hour .....

could not imagine thats good for your z2m Mesh Network...  I'm using slaesh's CC2652RB and stopping my z2m for Updates or slightly changes in the configuration only

I'm even not using Docker - runs on bare Metal APU 2C4 Debian Buster

**Comment by 2Max2Pax** [comment]
I forgot that I have also a Vimar 14594 (cover) , which is zigbee 2.0.
I've excluded it from my zigbee network.... I hope the problem was only that device.

If not I must build a second zigbee network. In this case, could I run a second instance of z2m in a docket container? 
For sure buying a new zigbee coordinator + a router is cheaper than changing my end devices.

**Comment by lux73** [comment]
> ... could I run a second instance of z2m in a docket container? For sure buying a new zigbee coordinator + a router is cheaper than changing my end devices.

no problem - make sure you use a **different Channel, PAN ID & ext PAN ID**

btw the Problem that some zigbee Devices crashes the Zigbee Mesh has nothing to do with zigbee 2.0 - even 3.0 Devices are crappy...

**Comment by 2Max2Pax** [comment]
The problem still happens. I cannot exclude a problem with the routers/devices but the behavior of the web frontend is strange: when one of the TRV does not communicate and I set the temperature (occupied_heating_setpoint), or any other attribute,  through the web frontend nothing is published.

**Comment by antst** [comment]
I also got issues with those TRVs lately. Can not pair properly new TRVs, even if they are 20 cm from router. Interview never completes anymore.

**Comment by antst** [comment]
Was to quick, old TRVs now also went to 
```"interview_completed":false,```

**Comment by antst** [comment]
After  many retries, I managed to get them somehow working again, but still they marked as failed interview, even if they seems to pass interview and bind to coordinator for reporting again.
![image](https://user-images.githubusercontent.com/2550573/149010461-2be0b196-455c-418d-b66c-4d7a04a80b16.png)

**Comment by antst** [comment]
There should be some regression somewhere.

**Comment by 2Max2Pax** [comment]
> After many retries, I managed to get them somehow working again, but still they marked as failed interview, even if they seems to pass interview and bind to coordinator for reporting again.

Try this:
unpair the 2 new TRVs and make the factory reset procedure.
pair them again.

**Comment by 2Max2Pax** [comment]
New update.
Since the day before yesterday everything works fine. This makes finding the reason of the problem even more difficult.

**Comment by 2Max2Pax** [comment]
I haven't seen the problem in the last 4 days.
There are no more communication problems.

**Comment by DonDonatello** [comment]
This resembles the issue in #13478, might be related
