### ISSUE TITLE
Adding new device: LivingWise (Orvibo) Dimmer Switch

### ISSUE THREAD

**Issue by dev-abo** [Koenkk/zigbee2mqtt#1071]
I'm trying to add LivingWise Smart Dimmer (https://www.primecables.ca/p-368972-lvs-zb500d-neutral-zigbee-smart-dimmerus-type-120v500va) as a new device, but having issues with receiving the status.  Also i could find the same model ID as Orvibo Smart Dimmer (https://www.orvibo.com/en/product/us_dimmerswitch.html). 

After adding the model to devices.js i was able to pair and control it successfully (On/Off/Set brightness), but cannot receive any status updates. 

devices.js:
```
	{
        zigbeeModel: ['abb71ca5fe1846f185cfbda554046cce'],
        model: 'abb71ca5fe1846f185cfbda554046cce',
        vendor: 'LivingWise',
        description: 'Dimmer',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: [],
        toZigbee: generic.light_onoff_brightness().toZigbee,
    },
```

Wireshark can catch the status updates, but none of them appears in zigbee2mqtt logs: [LivingWise.pcapng](https://github.com/dev-abo/sharedfiles/raw/master/LivingWise.pcapng)

I believe, i need to add `configure:` section to the devices.js, but none of the existing examples worked. 
I'd appreciate any help with this.

**Comment by khzd** [comment]
Hi
Did you fill this section : fromZigbee: [], ?

**Comment by dev-abo** [comment]
Hi, 

Yes, i did try to use `fromZigbee: generic.light_onoff_brightness.fromZigbee,`, but could see no incoming messages.

**Comment by Koenkk** [comment]
Can you control the device? (by sending to `zigbee2mqtt/[DEVICE_ID]/set` `ON`)

**Comment by dev-abo** [comment]
yes,
i'm able to control the switch: turn On/Off and set brightness, but do not get any status updates from it.

**Comment by Koenkk** [comment]
Try with
```js
{
        zigbeeModel: ['abb71ca5fe1846f185cfbda554046cce'],
        model: 'abb71ca5fe1846f185cfbda554046cce',
        vendor: 'LivingWise',
        description: 'Dimmer',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: [],
        toZigbee: generic.light_onoff_brightness().toZigbee,
configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];

            execute(device, actions, callback);
        },
},

**Comment by dev-abo** [comment]
now i'm getting

` zigbee-shepherd-converters:devices Configured '(cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb)' with result 'Error: Timed out after 30000 ms' +30s`

**Comment by Koenkk** [comment]
Can you post your `database.db`?

**Comment by dev-abo** [comment]
Sure [Database.db](https://hastebin.com/okocadivux.json)

**Comment by Koenkk** [comment]
While looking at your wireshark capture, I don't think this device needs a `configure` (sorry). Somehow the messages don't end up in zigbee2mqtt.

Could you replace the contents of `node_modules/zigbee-shepherd/lib/component/af.js` with the one from https://raw.githubusercontent.com/Koenkk/zigbee-shepherd/fix/lib/components/af.js (this has improved logging). Trigger some status updates and post the log here.

**Comment by dev-abo** [comment]
Unfortunately, still no incoming messages. I can see additional debug info from my other devices (xiaomi), but nothing from the dimmer. 

I uploaded some outgoing messages (mqtt => zigbee) with additional info here [outgoing log](https://hastebin.com/xusiqaqulu.coffeescript), maybe this can give something.

**Comment by Koenkk** [comment]
@dev-abo somehow that links give me an empty page.

I expect to receive messages when you manually toggle the switch, is this the case?

**Comment by dev-abo** [comment]
Weird...the link is broken for me as well. I'll upload it again once I get home.

Yes, I'm trying to get status change when I physically press buttons (on/off/brightness).

**Comment by dev-abo** [comment]
this link should work [out.log](https://raw.githubusercontent.com/dev-abo/sharedfiles/master/out.log)

**Comment by Koenkk** [comment]
@dev-abo in the log you also toggle the switch from zigbee2mqtt, can you provide a log where you only toggle the switch manually (physically), otherwise I cannot distinguish the messages.

**Comment by dev-abo** [comment]
@Koenkk that's correct, this is the issue i'm trying to fix. The attached log has only events triggered from mqtt, but i toggled the switch manually as well, but as you can see, none of the messages from switch appeared in the log. It looks like they've been skipped/filtered out for some reason.

**Comment by Koenkk** [comment]
@dev-abo that means we have to dive deeper here.

When running with `DEBUG=* npm start`; do you see any direct output when you manually toggle the switch?

**Comment by dev-abo** [comment]
@Koenkk i've tried `DEBUG=* npm start` as well. I do not think there was anything from that switch. However, i clearly saw output from my other devices. 
Is there something i can search for in the DEBUG output which can help?

**Comment by Koenkk** [comment]
@dev-abo if you don't see anything directly, there is nothing to look into. I see that the device send it's report to coordinator endpoint `10`. let's see if we can change that.

Can you try with:

```js
{
        zigbeeModel: ['abb71ca5fe1846f185cfbda554046cce'],
        model: 'abb71ca5fe1846f185cfbda554046cce',
        vendor: 'LivingWise',
        description: 'Dimmer',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: [],
        toZigbee: generic.light_onoff_brightness().toZigbee,
       configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
            ];

            execute(device, actions, callback);
        },
},
```

**Comment by dev-abo** [comment]
@Koenkk still no incoming messages.

The only message related to the dimmer is that it's configured successfully:

` zigbee2mqtt:info 2019-2-15 18:52:23 Succesfully configured zbDimmer1 (0x00124b001a4ddba6)`

**Comment by Koenkk** [comment]
Can you sniff the traffic again?

**Comment by dev-abo** [comment]
Here is a log from Wireshark [zb-dimmer.pcapng](https://github.com/dev-abo/sharedfiles/raw/master/zb-dimmer.pcapng).

I believe, the device i'm trying to connect has Source = 0x026e.
so, i can see
**On event**:
![on](https://user-images.githubusercontent.com/26031505/52904443-f7748a00-31f1-11e9-98c0-c3ee31393059.JPG)
**Off event**:
![off](https://user-images.githubusercontent.com/26031505/52904445-01968880-31f2-11e9-8d75-864e044d307f.JPG)

and **brightness report**:
![brightness](https://user-images.githubusercontent.com/26031505/52904447-09eec380-31f2-11e9-8ff8-945082374a27.JPG)

**Comment by Koenkk** [comment]
can you also expand the network and application support layer data?

**Comment by dev-abo** [comment]
- **On:**

![zb-on](https://user-images.githubusercontent.com/26031505/52914696-3e658c80-3291-11e9-838a-bca54ee927cd.JPG)

- **Off:**
![zb-off](https://user-images.githubusercontent.com/26031505/52914712-6654f000-3291-11e9-864c-de9b144966a2.JPG)

- **Brightness:**
![zb-brightness](https://user-images.githubusercontent.com/26031505/52914725-7c62b080-3291-11e9-8885-e10c02383aaf.JPG)

**Comment by Koenkk** [comment]
Thanks, can you try with the following CC2531 firmware: https://drive.google.com/open?id=10341IaglXLet65mZeEGd4jEI6P3_oAJG ?

**Comment by dev-abo** [comment]
after re-pairing the dimmer i can see the warning message "No converter available for...", full log is here [log](https://pastebin.com/raw/27y3Y3HT). 

All my other devices stopped report their status, but i can still control them - should i re-pair them also?

**Comment by Koenkk** [comment]
looks good! what do you mean with reporting their status? can you provide the log?

**Comment by dev-abo** [comment]
There is nothing in the log. I just had to pair all my devices again. Now it works.

**Comment by Koenkk** [comment]
Great, could you make a pr for the device?

**Comment by dev-abo** [comment]
sure, i will. 
Let me finish with converters and adding some comments first, and then i'll make a pr.

**Comment by tradenet** [comment]
> sure, i will.
> Let me finish with converters and adding some comments first, and then i'll make a pr.

Will you be adding  more LivingWise (printcables) Orvibo devices? Thx.

**Comment by dev-abo** [comment]
I do not have any other devices at the moment. In case I get one, I'll add it.

**Comment by tradenet** [comment]
> I do not have any other orvibo devices at the moment. In case I get one, I'll add it.

OK thanks for adding the switch BTW.

**Comment by tradenet** [comment]
> I do not have any other orvibo devices at the moment. In case I get one, I'll add it.

@dev-abo I've added the LivingWise door/window sensor. Works great.
