### ISSUE TITLE
Fork documentation into a new repository

### ISSUE THREAD

**Issue by dgomes** [Koenkk/zigbee2mqtt#1072]
Looking at the commit history, most of it is related to documentation.

I believe the documentation has grown into a stage that it should live in it's own repo, else it's very difficult to track actual changes in zigbee2mqtt.

**Comment by Bruceforce** [comment]
Or use a wiki in the main repo maybe?

**Comment by ryanbeaton** [comment]
@Bruceforce It used to be in the wiki.  It was moved into the repo in November

**Comment by dgomes** [comment]
it just needs to go into it's own repo... "zigbee2mqtt-doc"

**Comment by Koenkk** [comment]
@dgomes completly agree, as this changes the url, ive registered http://www.zigbee2mqtt.io . Will point this to the zigbee2mqtt-docs repo.

**Comment by Koenkk** [comment]
Done, docs are now in https://github.com/Koenkk/zigbee2mqtt.io, available under https://www.zigbee2mqtt.io/
