### ISSUE TITLE
[Problem]: With latest dev branch device.settings is undefined

### ISSUE THREAD

**Issue by okastl** [Koenkk/zigbee2mqtt#10734]
### What happened?

Updating from release v1.22.2 to dev 1.22.2-dev commit: 00124215 broke my extensions.

``
class StorenSwitch {
    constructor(zigbee, mqtt, state, publishEntityState, eventBus, settings, logger) {
        this.zigbee = zigbee;
        this.mqtt = mqtt;
        this.eventBus = eventBus;
        this.logger = logger;
    }

    async start() {
        this.logger.info(`Starting ${this.constructor.name}`);

        // attach to events
        this.eventBus.on('stateChange', this.onStateChange.bind(this), this);
    }
    
    async onStateChange(data) {
        const device = data.entity; // actually device or group
        if( !device.isDevice()) {
            // This entity is no device!
            return;
        }
        const settings = device.settings;

With the latest dev version device.settings is now undefined.
Maby this is a bug, or is there an api change?
I attach the full extension
[StorenSwitchNew.zip](https://github.com/Koenkk/zigbee2mqtt/files/7855512/StorenSwitchNew.zip)
.

### What did you expect to happen?

dev version should work.

### How to reproduce it (minimal and precise)

try the extension. ;)

### Zigbee2MQTT version

1.22.2-dev commit: 00124215

### Adapter firmware version

20211217

### Adapter

Electrolama zzh

### Debug log

error "settings undefined".

**Comment by Koenkk** [comment]
`device.settings` has been renamed to `device.options`.

**Comment by okastl** [comment]
> `device.settings` has been renamed to `device.options`.

Thank you!
