### ISSUE TITLE
Output to state.json is delayed

### ISSUE THREAD

**Issue by sebastianheyn** [Koenkk/zigbee2mqtt#1073]
Bug report:
i'm using zigbee2mqtt in connection with prtg - my reading the state.json file via http
parsing etc works fine, however I noticed there is quite a delay between the action and the write to file
is this intentionally? can I change this behaviour?
https://pasteboard.co/I0Ml1FR.png

greetings, basti

**Comment by Koenkk** [comment]
`state.json` is only written every 5 minutes. Apart from that, this file shouldn't be used externally, subscribe to the MQTT topics instead.
