### ISSUE TITLE
[New device support]: Schneider Electric - Wiser shutter control - NU350818

### ISSUE THREAD

**Issue by cavallaroe** [Koenkk/zigbee2mqtt#10742]
### Link

https://www.se.com/ww/en/product/NU350818/new-unica-wiser-blind-control-switch-white/

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0x680ae2fffe116e49","nwkAddr":62995,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Mains (single phase)","modelId":"NHPB/SHUTTER/1","epList":[5,21,242],"endpoints":{"5":{"profId":260,"epId":5,"devId":514,"inClusterList":[0,3,4,5,258,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"closuresWindowCovering":{"attributes":{"57360":0,"57363":0,"currentPositionLiftPercentage":98}}},"binds":[{"cluster":258,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db226","endpointID":242},{"cluster":258,"type":"endpoint","deviceIeeeAddress":"0x00124b00238db226","endpointID":1}],"configuredReportings":[{"cluster":258,"attrId":8,"minRepIntval":1,"maxRepIntval":62000,"repChange":1}],"meta":{}},"21":{"profId":260,"epId":21,"devId":260,"inClusterList":[0,3,2821,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"modelId":"NHPB/SHUTTER/1","manufacturerName":"Schneider Electric","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":6,"hwVersion":1,"dateCode":"","swBuildId":"002.004.016 R"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":6,"hwVersion":1,"dateCode":"","swBuildId":"002.004.016 R","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1260137254},"lastSeen":1642013023040,"useImplicitCheckin":true}

### Comments

I tried to follow the support new device page but I am not able to follow it step-by-step as I am using the Zigbee2mqtt addon for Home Assistant and it seems to be somehow different there.
The device I am trying to configure is a shutter control swithc from Schneider Electric from the Wiser Unica series, and I am using the Zigbee2mqtt addon (v 1.22.2-1) for Home Assistant installed on a Raspberry Pi with a [CC2652R1 adapter](https://shop.electrolama.com/collections/usb-rf-sticks/products/zzh-multiprotocol-rf-stick).
The device was found by the zigbee2mqtt and successfully paired but it is identified as a [different model](https://www.zigbee2mqtt.io/devices/S520567.html#schneider%2520electric-s520567). The available commands (open, close, stop) work correctly also for this device, but other configurations are not available (duration, led behaviour)

I will be happy to contribute in achieving full support for this device but I will need some help from the community.

**Comment by fariouche** [comment]
I'm using them and they work perfectly fine

**Comment by cavallaroe** [comment]
Hi fariouche, it is working for me as well. But I would like to set the drive time and turn off the led and I don't see these options in the configuration for the S520567 shutter

**Comment by fariouche** [comment]
Oh, I see an error in the integration of the lift duration feature @Koenkk 
In schneider_electric.js, tzLocal.lift_duration was only added to 'PUCK/SHUTTER/1' and missing for 'NHPB/SHUTTER/1'

@cavallaroe , I'm not sure that the led can be controlled

**Comment by cavallaroe** [comment]
Thanks fariouche,
The led settings can be modified when connnected via bluetooth to the SE Wiser mobile app, so I expect it can be done with zigbee as well. But I may be wrong

**Comment by fariouche** [comment]
I have the wiser hub home touch, and there is no led option. So either the led cannot be controlled over zigbee or they didn't offer the option in the home touch and in that case we have now way to know the command to send

**Comment by cavallaroe** [comment]
Ok, I see. So the led settings cannot be changed but the drive duration yes. 
You already identified what is missing, should I add it on my local version or there will be an update?

**Comment by fariouche** [comment]
until @Koenkk  add it to the NHPB/SHUTTER/1 device in zigbee-herdsman, you can use an external converter (see https://github.com/Koenkk/zigbee2mqtt/issues/10019) or modify schneider_electric.js in herdsman/devices to add localTz like PUCK/SHUTTER/1

**Comment by Vebryn** [comment]
Also interested 👍

**Comment by Vebryn** [comment]
> until @Koenkk add it to the NHPB/SHUTTER/1 device in zigbee-herdsman, you can use an external converter (see #10019) or modify schneider_electric.js in herdsman/devices to add localTz like PUCK/SHUTTER/1

Is external converter specified into #10019 compatible with NHPB/SHUTTER/1 ?

**Comment by fariouche** [comment]
the converter in #10019 is for NHPB/SHUTTER/1 but seem to be the same as PUCK/SHUTTER/1
