### ISSUE TITLE
[New device support]: Zemismart Zigbee Smart Outlet Universal Socket with USB Port

### ISSUE THREAD

**Issue by H4ss2** [Koenkk/zigbee2mqtt#10753]
### Link

https://www.zemismart.com/products/b90

### Database entry

{"id":46,"type":"Router","ieeeAddr":"0x9035eafffe054312","nwkAddr":38197,"manufId":4098,"manufName":"_TZ3000_zigisuyh","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_zigisuyh","stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022a54fe9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022a54fe9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1499018984},"lastSeen":1642073612896,"useImplicitCheckin":true}

### Comments

the USB ports and the main power socket controlled separately .
as this is my first time i'm trying to add a support for a device please make sure that my External Converter code is right

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {


    fingerprint: [
        {
            modelID: 'TS011F',
            manufacturerName: '_TZ3000_zigisuyh'
        },
    ],
    model: 'ZIGBEE-B09-UK',
    vendor: 'Zemismart',
    description: 'Zemismart Zigbee Smart Outlet Universal Socket with USB Port',
    supports: 'switch',
    fromZigbee: [
        fz.on_off, 
        fz.tuya_switch_power_outage_memory,
    ],
    toZigbee: [
        tz.on_off,
        tz.tuya_switch_power_outage_memory,
    ],
   exposes: [
       e.switch().withEndpoint('l1'), 
       e.switch().withEndpoint('l2'),
       exposes.enum('power_outage_memory', ea.STATE_SET, ['on', 'off', 'restore']).withDescription('Recover state after power outage')
   ],
    endpoint: (device) => {
        return {'l1': 1, 'l2': 2};
    },
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1),coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(device.getEndpoint(1));
		await reporting.onOff(device.getEndpoint(2));

    },

};

module.exports = definition;
```

**Comment by Koenkk** [comment]
added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
