### ISSUE TITLE
[Feature request]: Disable the device's ROUTER function

### ISSUE THREAD

**Issue by KameDomotics** [Koenkk/zigbee2mqtt#10754]
### Is your feature request related to a problem? Please describe

Many times Zigbee end-devices connect to Router devices that have stability problems or difficulties.

### Describe the solution you'd like

It would be useful to have the possibility to disable / inhibit the ROUTER function of the devices, and use them as simple end-devices.

### Describe alternatives you've considered

No alternatives

### Additional context

No Additional context

**Comment by sjorge** [comment]
AFAIK there is no way for the coordinator to influence the which routers end devices use.

**Comment by Koenkk** [comment]
This is not possible indeed.
