### ISSUE TITLE
[Feature request]:  Multiple Instances of Zigbee2MQTT in Home Assistant Supervised

### ISSUE THREAD

**Issue by AlohaFlyer** [Koenkk/zigbee2mqtt#10765]
### Is your feature request related to a problem? Please describe

I am only able to cleanly install a single Zigbee2MQTT coordinator in my Home Assistant instance. I have a large system (189 lights) and need to use 4 coordinators on different Zigbee channels.

### Describe the solution you'd like

I would like to see if we can build the Zigbee2MQTT HA Add On to allow for multiple coordinators.  

### Describe alternatives you've considered

Example: SmartThings and Hubitat can do this already.  At the moment I am stuck using 4 SmartThings hubs as coordinators. 

The alternative is to run Zigbee2MQTT for a single coordinator, then ZHA for another and something else for the other two. 

It would be cleaner to support to run them all as the same system if possible. 

I have tested many times, running a single large Zigbee mesh with good coordinators. But its never reliable until I split the system into smaller segments on different channels. 

### Additional context

Zigbee coordinators can really only handle 45-50 zigbee devices (In my case LEDVANCE lights) in a single mesh. Even with good routers it is not stable after about 50 devices.  I want to run almost 200 lights hence 4 coordinators.

**Comment by Koenkk** [comment]
Please create issue related to the ha addon here: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues
