### ISSUE TITLE
[Problem]: ZNLDP12LM by Xiaomi (Aqara) has wrong maximal color temperature

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#10775]
### What happened?

The highest color temperature which the device will store is 370 mired. Everthing above will be ignored by the device.

Zigbee2MQTT does show 500 mired as maximum in the GUI and export this to HA. So the GUI in HA will allow users to set values which the device won't accept.

### Zigbee2MQTT version

1.22.1-1

### Adapter firmware version

unknown

### Adapter

Slaesh's CC2652RB

**Comment by Koenkk** [comment]
fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
