### ISSUE TITLE
Hanging when not using channel 11 on CC2530

### ISSUE THREAD

**Issue by nanosonde** [Koenkk/zigbee2mqtt#1077]
I cannot use other channels than channel 11.

The log says:
```
 zigbee-shepherd:init Start the ZNP as a coordinator... +0ms
  zigbee-shepherd:request REQ --> ZDO:startupFromApp +4ms
  zigbee-shepherd:msgHdlr IND <-- ZDO:stateChangeInd +1s
```
And then it keeps hanging forever.

zigbee2mqtt version 1.1.1 (commit #a2d378c)
Coordinator firmware version: '20190109'
CC2530 without HW handshake (RTS/CTS)

**Comment by JLFN** [comment]
Iam running it on 1.1.1 with no problem
```.yaml
serial:
  port: /opt/zigbee2mqttdev/vusb/zigbee_cc2530
  disable_led: false
advanced:
  pan_id: 6754
  channel: 26
  cache_state: true
  log_level: info
  log_directory: data/log/%TIMESTAMP%
  baudrate: 115200
  rtscts: false
  soft_reset_timeout: 0
```

**Comment by Koenkk** [comment]
Can you try with the latest dev branch?

**Comment by nanosonde** [comment]
Oh. Embarrassing. I was think in terms of Wifi channels (1-11) and Zigbee channels (11-22, [23-26]).
Saw it here: https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence

**Comment by nanosonde** [comment]
I think there should be a check for the valid channel range which bails out if it is out of range.

**Comment by Koenkk** [comment]
@nanosonde done.
