### ISSUE TITLE
IKEA LED1546G12 shows as not supported

### ISSUE THREAD

**Issue by sebastianengman** [Koenkk/zigbee2mqtt#10814]
### What happened?

Adding IKEA LED1546G12 which is in the list of supported devices, but the bulb shows as not supported.

I figure it has something to do with the weird symbol in the model description?

**From the device page:**

Friendly name
Köket - Matbord
Last seen
N/A
Availability
Online
Device type
Router
Zigbee Model
TRADFRI bulb E27 WS�clear 950lm
Zigbee Manufacturer
IKEA of Sweden
Support status
Not supported

IEEE Address
0x000b57fffe0c994e
Network address
0x64AF
Firmware build date
20211102
Firmware version
2.3.087
Power
Interview completed
True

https://www.zigbee2mqtt.io/devices/LED1546G12.html
<img width="1013" alt="Skärmavbild 2022-01-15 kl  17 00 07" src="https://user-images.githubusercontent.com/59333304/149628629-25d34fcd-dbd9-4faf-abe9-e5bc289eb71b.png">

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

26720700

### Adapter

ConBee2

### Debug log

warn  2022-01-15 16:54:50: Received message from unsupported device with Zigbee model 'TRADFRI bulb E27 WS�clear 950lm' and manufacturer name 'IKEA of Sweden'
warn  2022-01-15 16:54:50: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
could you provide the data/database.db entry of this device?

**Comment by sebastianengman** [comment]
Attached!

**Comment by Koenkk** [comment]
I don't see it, could you copy paste it here?

**Comment by sebastianengman** [comment]
> I don't see it, could you copy paste it here?

Can you see it now?

**Comment by Koenkk** [comment]
yes, should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by sebastianengman** [comment]
> yes, should be fixed now.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Thank you very much. How do I know when the dev branch update is available?

Also, do I need to delete the device in Z2M or will it get fixed by itself?

Thanks!

**Comment by Koenkk** [comment]
> Thank you very much. How do I know when the dev branch update is available?

build is running , will be done in 10 mins for now, so update in 1 hour should be good

> Also, do I need to delete the device in Z2M or will it get fixed by itself?

no repair needed.

**Comment by sebastianengman** [comment]
> > Thank you very much. How do I know when the dev branch update is available?
> 
> build is running , will be done in 10 mins for now, so update in 1 hour should be good
> 
> > Also, do I need to delete the device in Z2M or will it get fixed by itself?
> 
> no repair needed.

![image](https://user-images.githubusercontent.com/59333304/149635735-a12fdaad-839b-4419-87a0-11de60ae7daa.png)

**Comment by Koenkk** [comment]
perfect!
