### ISSUE TITLE
Don't use a router as a router

### ISSUE THREAD

**Issue by marcotini** [Koenkk/zigbee2mqtt#1081]
Is it possible to not use a router, for example a Osram plug as a end device and not a router? Since if the power goes out, everything stop working even if I've the coordinator online.

I've try to edit the database.db file but I don't know if it's really used as a end device, since I don't know which device is connected to the coordinator or to the router (Osram plug or some Hue bulb).

**Comment by Koenkk** [comment]
No, this can not be influenced by the coordinator (the device itself has to be changed for this).
