### ISSUE TITLE
Re-join devices

### ISSUE THREAD

**Issue by ajcb69** [Koenkk/zigbee2mqtt#1082]
Raspberry 3b+ home assistant.
I had to format sd and reinstall ha because don´t run.
When I install zigbee2mqtt, i have restored the data directory with a backup stored.
Now in Home assistant recognize the entities but don´t record any activity from sensors when p.e. a door is opened or closed.
![sensors](https://user-images.githubusercontent.com/45384079/52715279-5214a880-2f9c-11e9-8e38-b2cdfe61fb76.jpg)

I can see the old zigbbe map but not update
![map](https://user-images.githubusercontent.com/45384079/52715285-580a8980-2f9c-11e9-91ad-c76680e92b27.jpg)

It´s possible to repair or i have to rejoin all sensors?
Thank you and excuse me for my bad english

**Comment by JLFN** [comment]
I had the same problem if you enable join and then press the button it might repair it self if not. You need to Remove state.json and rejoin.
