### ISSUE TITLE
[Feature request]: Could led_enable's display name be "led" to make it easier to work with voice control?

### ISSUE THREAD

**Issue by flatsiedatsie** [Koenkk/zigbee2mqtt#10820]
### Is your feature request related to a problem? Please describe

The Ikea air purifier has a _propertiy_ called `led_enable`. It's _name_ is the same.

In the Webthings gateway users cannot change the names of properties of devices, which means the device has this:

![Screenshot 2022-01-15 at 19 59 29](https://user-images.githubusercontent.com/805405/149634575-718f9589-2d80-4a71-a355-48eef2d9ad4c.png)

The local voice control system allows users to interact with properties by using the display name. For example:

`What is the state of the air purifier?` or `enable the child lock of the air purifier`.

However, this gets a little weird with `Led enable`, since voice control sees `enable` as an actuator word. To turn on the led with their voice, the user could in theory say "enable led enable", which could confuse voice control systems. In practise they'll probably say "turn on led enable" or something to that effect, but it still a bit strange, and could still confuse these systems.

### Describe the solution you'd like

Would it be an idea to change the expose `name` from `led enable` to just `led`? If `led` is too short, how about `led indicator` or `status light` or...

### Describe alternatives you've considered

This is of course totally not important, and I can easily fix this in the Zigbee2MQTT addon. But I thought I'd share the idea. When I did a search I saw that the led_enable name occurs in multiple devices.

### Additional context

So far all the other properties I've seen in Z2M work great with voice control.

**Comment by sjorge** [comment]
The cluster value actually got renamed to `controlPanelLight` from the old `ledEnabled`.

@Koenkk would it be considered a breaking change to just rename the property to `control_panel_light` ?

**Comment by Koenkk** [comment]
@sjorge there are multiple properties that and with `_enable` (e.g. `pir_enable`) and I don't think we should rename those. This is a very specific problem, it sounds more logical to me if webthings supports a feature where you can rename those sensors and can use those in the voice recognition (in HA I also do it this way)

**Comment by sjorge** [comment]
Fine by me, I think I originally had led_enabled and change it to _enable to match other like pir_enable (without d)

**Comment by flatsiedatsie** [comment]
> it sounds more logical to me if webthings supports a feature where you can rename those sensors

I fully agree. Unfortunately that feature isn't there right now.

I'll try to fix it in the Z2M addon, no problem. I just wanted to make sure it wasn't better to do it upstream first.
