### ISSUE TITLE
Smart Power Strip - Model: SM-SO306E-1Z

### ISSUE THREAD

**Issue by KochergaAlex** [Koenkk/zigbee2mqtt#10841]
### Link

https://a.aliexpress.com/_Akm8hS

### Database entry

{"definition":null,"friendly_name":"0xa4c1380d1921c5aa","ieee_address":"0xa4c1380d1921c5aa","status":"successful","supported":false},"type":"device_interview"}'

### Comments

Hi,
I have this log in mqtt add-on. Could you support my device?
Thank you.

Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5' is NOT supported
Smart Power Strip - Model: SM-SO306E-1Z

Device '0xa4c1380d1921c5aa' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0xa4c1380d1921c5aa","ieee_address":"0xa4c1380d1921c5aa","status":"successful","supported":false},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0xa4c1380d1921c5aa","supported":false},"type":"pairing"}'
Warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5'

**Comment by giejay** [comment]
Was about to buy the same but guess I'll checkout others first.
