### ISSUE TITLE
lidl HG07834C

### ISSUE THREAD

**Issue by zymex22** [Koenkk/zigbee2mqtt#10874]
### What happened?

Hello im new to zigbee2mqtt so sorry if its just me being stupid here.

anyways just swapped from Deconz to zigbee2mqtt, no real problems i could connect all my old bulbs and led strips from ikea/lidl.
but just went out to buy a new E27 HG07834C RGB bulb, i was looking at black adder list and should be compat. but when i pair it up it goes in as unknown
(latest lidl batch)

![image](https://user-images.githubusercontent.com/41029070/149962759-b60a2c20-ea1f-4195-8d83-fce49f67141b.png)

as far i can see it goes in as wrong ID if i can understand this correct it should have gotten TS0505A and not TS0505B as mine has.

is there anything i can do to fix this manually or does it need a firmware update or something?

### Zigbee2MQTT version

1.18.1

### Adapter firmware version

0x26660700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
You are running a very old z2m version (1.18.1)

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
