### ISSUE TITLE
IKEA STYRBAR sends redundant empty message? 

### ISSUE THREAD

**Issue by SHxKM** [Koenkk/zigbee2mqtt#10884]
### What happened?

When I press the “brightness_up”/“on” button on IKEA `E2002` I see this in Z2M logs: 

```
MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59', payload '{"action":"on","battery":100,"linkquality":167,"update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59', payload '{"action":"","battery":100,"linkquality":167,"update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59/action', payload 'on'
```

Same for any other action: 

```
Info MQTT publish: topic 'zigbee2mqtt/kitchen_remote', payload '{"action":"arrow_right_click","battery":null,"linkquality":207,"update":{"state":null},"update_available":null}'
Info MQTT publish: topic 'zigbee2mqtt/kitchen_remote', payload '{"action":"","battery":null,"linkquality":207,"update":{"state":null},"update_available":null}'
Info MQTT publish: topic 'zigbee2mqtt/kitchen_remote/action', payload 'arrow_right_click'
```

Is this expected? Is the second info message in the chain just resetting the action value? It's causing some automations to trigger twice or even thrice.

Re-pairing does not help.

### What did you expect to happen?

I’m not sure. But I think only one update should be sent.

### How to reproduce it (minimal and precise)

Pair IKEA 2002 remote, press any button.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

0x26580700

### Adapter

Conbee II

### Debug log

MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59', payload '{"action":"on","battery":100,"linkquality":167,"update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59', payload '{"action":"","battery":100,"linkquality":167,"update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/0x0c4314fffedbba59/action', payload 'on'

**Comment by SHxKM** [comment]
From what I'm reading this is *not* the expected behavior, but I just want to verify.

**Comment by florianbrede-ayet** [comment]
@SHxKM if you have `homeassistant: true` set in your `configuration.yaml`, this is expected behaviour.
What automations are you referring to, because I'd say your scripts might not be setup correctly?

**Comment by SHxKM** [comment]
> @SHxKM if you have `homeassistant: true` set in your `configuration.yaml`, this is expected behaviour.
> What automations are you referring to, because I'd say your scripts might not be setup correctly?

Yes. I’m using Home Assistant. I’m using the Controller automation by EPMatt (blueprint). These are considered well-crafted ones but yeah there may be a bug in there. If you’re sure this is the correct behavior I’ll just close this one.

**Comment by florianbrede-ayet** [comment]
@SHxKM i checked the blueprint and it's correctly checking for `{{ trigger_action not in ["","None"] }}`.
So I don't think your issue is related to the empty message at all.
Either your switch is sending multiple button events per press (then use debounce) or you might accidentally have enabled multiple automations on the same trigger entity.
