### ISSUE TITLE
[New device support]: Moes TS0601 _TZE200_fjjbhx9d, 2 Gang EU Smart Light Dimmer Switch

### ISSUE THREAD

**Issue by MiKn1** [Koenkk/zigbee2mqtt#10892]
### Link

https://www.moeshouse.com/collections/new-arrivals/products/new-zigbee-1-gang-eu-smart-light-dimmer-switch-independent-control-smart-life-tuya-app-relay-status-backlight-switch-off-rf-remote-control-works-with-alexa-google-voice-assistants-%E7%9A%84%E5%89%AF%E6%9C%AC

### Database entry

{"id":57,"type":"Router","ieeeAddr":"0xa4c138557cb35182","nwkAddr":27679,"manufId":4417,"manufName":"_TZE200_fjjbhx9d","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":32,"65508":0,"stackVersion":0,"dateCode":"","appVersion":64}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1642549033929,"defaultSendRequestWhen":"immediate"}

### Comments

Used Platform: 
Zigbee2MQTT Version 1.22.2-dev commit: 8e53d745

**Comment by MiKn1** [comment]
> ### Link
> 
> https://www.moeshouse.com/collections/new-arrivals/products/new-zigbee-1-gang-eu-smart-light-dimmer-switch-independent-control-smart-life-tuya-app-relay-status-backlight-switch-off-rf-remote-control-works-with-alexa-google-voice-assistants-%E7%9A%84%E5%89%AF%E6%9C%AC
> ### Database entry
> 
> {"id":57,"type":"Router","ieeeAddr":"0xa4c138557cb35182","nwkAddr":27679,"manufId":4417,"manufName":"_TZE200_fjjbhx9d","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":32,"65508":0,"stackVersion":0,"dateCode":"","appVersion":64}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1642549033929,"defaultSendRequestWhen":"immediate"}
> ### Comments
> 
> Used Platform: Zigbee2MQTT Version 1.22.2-dev commit: [8e53d74](https://github.com/Koenkk/zigbee2mqtt/commit/8e53d745cd0a1051d39c45f06f7fb2b55322514e)
> ### External converter

Intermins test with external converter:
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_fjjbhx9d'}],
    model: 'Wall touch light dimmer switch (2 gang)',
    vendor: 'Moes',
    description: '2 Channel Smart Dimmer Switch Module 10A/16A',
        fromZigbee: [fz.moes_105_dimmer, fz.ignore_basic_report],
        toZigbee: [tz.moes_105_dimmer],
        meta: {turnsOffAtBrightness1: true, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            if (device.getEndpoint(2)) await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        },
        exposes: [e.light_brightness().withEndpoint('l1').setAccess('state', ea.STATE_SET).setAccess('brightness', ea.STATE_SET),
            e.light_brightness().withEndpoint('l2').setAccess('state', ea.STATE_SET).setAccess('brightness', ea.STATE_SET)],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 1};
        },
    };
module.exports = definition;
`
Switch On Off seems to working fine, dimmer function need to test when I receive dimmer bulbs end of the week.

**Comment by MiKn1** [comment]
its reacting very slow with these external converter and regulary there is no response anymore. What can I do to help you for an proper integration. Thank you

**Comment by MiKn1** [comment]
anything I can do to get these devices support beside listing it on Tuya dev platform and to use fhempy with tuya_cloud_connector instead? I ordered the Tuya gateway, may this can help you anyhow??

**Comment by rhayun** [comment]
i am having this issue also - any new on this?

**Comment by rediculum** [comment]
I have 1.27.0 running and the device has not been recognized. Is it still not supported by release?

Just a remark about pairing, here's the original text from the manual:
_Press the switch button for 6 times, and hold on the 6th time, then release until the blue indicator flashing fast_
