### ISSUE TITLE
Lidl Smart Mood light claims to be not supported even when it is present in lidl.js 

### ISSUE THREAD

**Issue by E1m0W** [Koenkk/zigbee2mqtt#10900]
### What happened?

I paired Livarno Lux smart LED mood light with the exact same fingerprint than what can be found in the lidl.js file in the master branch, but after pairing the following log message was generated and the suggestion was to add follow the new device guide. 

`"Device '0x04cd15fffea036be' with Zigbee model 'TS0505B' and manufacturer name '_TZ3210_r0xgkft5' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html"`

I started making the ext_converter.js according to the "Support new device", but realized that the exact same fingerprint was already in the [lidl.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/lidl.js):
```
        fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3210_r0xgkft5'}],
        model: '14156506L',
        vendor: 'Lidl',
        description: 'Livarno Lux smart LED mood light',
```
I refreshed the converters with npm install but that did not help.

How do I get the light to be recognized?

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211115

### Adapter

CC2351 stick

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/7900062/log.txt)

**Comment by Koenkk** [comment]
this device has been added 4 days ago (https://github.com/Koenkk/zigbee2mqtt/issues/10823), it is only supported in the dev-branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) yet and will be supported in the next release on 1 January.
