### ISSUE TITLE
[New device support]: Philips HUE 929003055801

### ISSUE THREAD

**Issue by Klapperman** [Koenkk/zigbee2mqtt#10926]
### Link

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-adore-badkamer-inbouwdownlight/8719514340794

### Database entry

{"id":49,"type":"Router","ieeeAddr":"0x0017880109e49cc0","nwkAddr":54369,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003055801","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1642757618538,"useImplicitCheckin":true}

### Comments

I tried adding the device but it came up as unknown. After creating a External Converter I came to the conclusion that it's just another variant of the already existing 3418411P6 model. I'm however unsure how to add a variant to an already existing entry (although I've seen examples). Maybe someone can point me to those instructions?

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['929003055801'],
    model: '929003055801',
    vendor: 'Philips',
    description: 'Hue white ambiance bathroom ceiling light Adore with Bluetooth',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

{colorTempRange: [153, 454]}

**Comment by Koenkk** [comment]
Added. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
