### ISSUE TITLE
IKEA LED2005R5 Unsupported

### ISSUE THREAD

**Issue by timknowlden** [Koenkk/zigbee2mqtt#10940]
### What happened?

I have 5 new IKEA LED2005R5 Bulbs and all of them are picked up by zigbee2mqtt but on interview say they are unsupported.

The documentation states that they are supported here: https://www.zigbee2mqtt.io/devices/LED2005R5.html#ikea-led2005r5

### What did you expect to happen?

I expected them to work with Z2M

### How to reproduce it (minimal and precise)

Pairing process, 6 off and ons and they interview.

### Zigbee2MQTT version

1.18.1 commit: 1.18.1

### Adapter firmware version

20210120

### Adapter

ZZH

### Debug log

Successfully interviewed '0x50325ffffe22faed', device has successfully been paired
Warning Device '0x50325ffffe22faed' with Zigbee model 'TRADFRIbulbGU10WS345lm' and manufacturer name 'IKEA of Sweden' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x50325ffffe22faed","ieee_address":"0x50325ffffe22faed","status":"successful","supported":false},"type":"device_interview"}'
Info Successfully interviewed '0x0c4314fffebbf99b', device has successfully been paired
Warning Device '0x0c4314fffebbf99b' with Zigbee model 'TRADFRIbulbGU10WS345lm' and manufacturer name 'IKEA of Sweden' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x0c4314fffebbf99b","ieee_address":"0x0c4314fffebbf99b","status":"successful","supported":false},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x50325ffffe22faed","supported":false},"type":"pairing"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x0c4314fffebbf99b","supported":false},"type":"pairing"}'
Info Accepting joining not in blocklist device '0x0c4314fffea6463f'
Info Device '0x0c4314fffea6463f' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffea6463f","ieee_address":"0x0c4314fffea6463f"},"type":"device_joined"}'
Info Starting interview of '0x0c4314fffea6463f'

**Comment by Koenkk** [comment]
1.18.1 is very old, update to the latest z2m.

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
