### ISSUE TITLE
Aqara E1 door & window contact sensor [MCCGQ14LM] not working properly

### ISSUE THREAD

**Issue by Block4r** [Koenkk/zigbee2mqtt#10951]
### Link

https://www.zigbee2mqtt.io/devices/MCCGQ14LM.html#adapter-firmware

### Database entry

{"id":11,"type":"EndDevice","ieeeAddr":"0x54ef44100025955e","nwkAddr":11151,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.magnet.acn001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,64704],"outClusterList":[3,25],"clusters":{"ssIasZone":{"attributes":{"iasCieAddr":"0x0000000000000000","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":1642862408769,"defaultSendRequestWhen":"immediate"}

### Comments

Hi All!
Sensors are paring but i see only linkquality. 
I updated Conbee II firmware (according to https://www.zigbee2mqtt.io/devices/MCCGQ14LM.html#adapter-firmware) and trying few times paring and unpairing sensors - the same problem. 
![obraz](https://user-images.githubusercontent.com/97193814/150642930-b93bb349-980f-42a1-9e91-3692cf77a5b4.png)
![obraz](https://user-images.githubusercontent.com/97193814/150642943-ddbc4200-6564-4a06-95c4-faccab384e8e.png)
![obraz](https://user-images.githubusercontent.com/97193814/150642968-9fd29cb9-94c1-41af-87cd-9fdab1d875e5.png)
Any idea what to do? or i should return sensors?

**Comment by metlinux** [comment]
I have the exact same model and have no problem at all. I am using Zigbee2Mqtt 1.22.2 (not the dev but 1.22.2 commit: 414c51f)
It worked out the box for me:
![Capture1](https://user-images.githubusercontent.com/46293765/150792251-79da9aa3-0863-461d-88b5-67884820b4d8.PNG)
![Capture2](https://user-images.githubusercontent.com/46293765/150792260-624ddeb1-11cd-4c6c-9e56-5c56141445ac.PNG)

**Comment by Block4r** [comment]
It's Works! :) i Switched to Z2M without "dev", pair again and it worked. After that i Switched back to "Dev" and sensors working properly. Thank you.

**Comment by ToXinE** [comment]
I have the same issue with 1.23.0 release.
![image](https://user-images.githubusercontent.com/6205053/153605614-5bd55907-e737-4ee7-ac84-52c168cce72b.png)

 Does 1.22.2-dev have been merged ? Does 1.22.2-dev contains fixes that are not in 1.23.0 ?

![image](https://user-images.githubusercontent.com/6205053/153605728-3278dcc6-08ee-4407-b078-c1e9ecdd41cf.png)
![image](https://user-images.githubusercontent.com/6205053/153605768-6474c54f-2202-4385-91ca-036283a323a4.png)

**Comment by metlinux** [comment]
In 1.23.0 it is still working for me. Have you upgraded the firmware of your adapter ? Maybe that is causing this.....

PS this issue was closed.....

**Comment by ToXinE** [comment]
yep ! as you can see in screenshots,my coordinator is conbee2 with last firmware 0x26720700
