### ISSUE TITLE
Device compatibility with ZigBee channel 26

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#1095]
I have been reading:
[https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html](url)

That says:
```
ZigBee channel 26 is usually relatively unaffected by WiFi, but many ZigBee devices do not support it.
```

Is there any way for me to verify if all my devices support channel 26?

**Comment by JLFN** [comment]
@kiwinol Change your zigbee2mqtt config to channel 26 and then try to pair it!

**Comment by khzd** [comment]
Hi
We are implementing support to livolo zigbee working Only on channel 26, so I test many Xiaomi devices and gledopto on this channel and work fine 
Didn’t have all other devices to test...

**Comment by Koenkk** [comment]
As this is not an zigbee2mqtt issue I will close this issue.

Feel free to continue the discussion.
