### ISSUE TITLE
Zigbee RGB Light missing extra feature

### ISSUE THREAD

**Issue by McGyver64** [Koenkk/zigbee2mqtt#10953]
### What happened?

After a crash and rebuild of RPI + Z2M + Domoticz etc. I was in process of pairing all devices again, but one device is missing functionality. I restored an pre-crash backup and it shows 2 devices, as after the crash I only get one device. I have both /domoticz/plugins data available

### What did you expect to happen?

That after repairing this Zigbee RGB light , the whole functionality was back

### How to reproduce it (minimal and precise)

when I restore an pra-crash database of Domoticz I get both devices. After new install en repairing devices, I only get one device

Before Crash

<img width="1185" alt="Schermafbeelding 2022-01-22 om 15 27 04" src="https://user-images.githubusercontent.com/69874589/150643710-6d1f366c-23f3-48df-84b8-60f6c1b47488.png">

<img width="791" alt="Schermafbeelding 2022-01-22 om 15 26 25" src="https://user-images.githubusercontent.com/69874589/150643634-702e375e-c05c-403f-804d-89ca8c3431d0.png">

###### After new install and repairing

<img width="1182" alt="Schermafbeelding 2022-01-22 om 15 06 44" src="https://user-images.githubusercontent.com/69874589/150643245-cc5717b7-eeb4-40c7-89c0-523d24f63183.png">
<img width="400" alt="Schermafbeelding 2022-01-22 om 15 07 01" src="https://user-images.githubusercontent.com/69874589/150643247-7d909a24-c66f-49b1-9145-6b3827603a1d.png">
<img width="791" alt="Schermafbeelding 2022-01-22 om 15 26 25" src="https://user-

 

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20211217

### Adapter

CC2562RB

**Comment by Koenkk** [comment]
Can you check if it works correctly via the z2m frontend? If yes, please create an issue here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues

**Comment by McGyver64** [comment]
<img width="1628" alt="Schermafbeelding 2022-01-23 om 14 02 07" src="https://user-images.githubusercontent.com/69874589/150679741-1db38f85-9e28-4dee-a5ea-1bd0f5162370.png">

<img width="835" alt="Schermafbeelding 2022-01-23 om 14 03 24" src="https://user-images.githubusercontent.com/69874589/150679772-76435823-3041-4fb7-b8d9-c562f3a92341.png">
