### ISSUE TITLE
Zemismart Tuya Zigbee Roller - TS0601_cover version2 support

### ISSUE THREAD

**Issue by perseus177** [Koenkk/zigbee2mqtt#10968]
### What happened?

Hello 
Currently I have TS0601_cover  and I am very satisfied with the product and control it via zigbee2mqtt and HA. 

I wanted buy additional TS0601_cover  but I saw in review that aliexpress started send new version of the device. 
Currently exists: 

- [TS0601_cover  version 1](https://www.zigbee2mqtt.io/devices/TS0601_cover.html#tuya-ts0601_cover)- old version
- TS0601_cover  version 2 - new version 

From Aliexpress: 
[TS0601_cover  ](https://www.aliexpress.com/item/1005001375412422.html?spm=a2g0o.cart.0.0.54793c005kvpZE&mp=1)

There are two versions now: 

- old version: only can set limits on the motor
- update version(V2):only can set limits in tuya app - Original zigbee hub is required
- (If there is no remarks, the warehouse will ship randomly)

Review on store: 

> WARNING: selling is sending a V2 version of this item. DO NOT BUY V2 version is you want Zigbee controls. Initially I bought one and was very happy with it. So therefore I wanted a second zemismart roller shade driver with zigbee and bought the same product of seller on the same product page of seller. After receiving the product it seems there now is a V2 version of this product! This is not communicated by seller on the product page of anywhere else! Problem with the V2 version is that you need the original TUYA app and TUYA zigbee bridge to set the UPPER, MIDDLE & LOWER limits for your shades. Also, the 1CH of 6CH remote can NOT be used with the V2 version of this product. I reached out to seller and they say only TUYA support, no ZIGBEE or anything els anymore. And seller is not giving any solution for this problem. So if you want to use this product with your own ZIGBEE setup (like HA + ZHA / Z2MQTT) then DONT buy this product!!!

### What did you expect to happen?

 And now my question: Is it possible to add support to the Zigbee2Mqtt for set limits without original zigbee hub ?

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210319

### Adapter

CC2652

**Comment by Albi83** [comment]
The M515EGZT arrived today. Unfortunately in version 2 and I was not aware of the problem described above.

Maybe there's a solution here, but I haven't been able to get it working yet:

https://github.com/Koenkk/zigbee2mqtt/issues/11164#issuecomment-1087377722
