### ISSUE TITLE
[New device support]: Philips HUE 929003055901

### ISSUE THREAD

**Issue by Klapperman** [Koenkk/zigbee2mqtt#10962]
### Link

https://www.philips-hue.com/nl-be/p/hue-white-ambiance-adore-badkamer-inbouwdownlight/8719514340817

### Database entry

{"id":51,"type":"Router","ieeeAddr":"0x0017880109dc8fe0","nwkAddr":57204,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003055901","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003055901","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1642923000311,"useImplicitCheckin":true}

### Comments

Another variant of the already existing 3418411P6 model same as my previous [Support Request.](https://github.com/Koenkk/zigbee2mqtt/issues/10926).

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['929003055901'],
    model: '929003055901',
    vendor: 'Philips',
    description: 'Hue white ambiance bathroom ceiling light Adore with Bluetooth',
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

{colorTempRange: [153, 454]}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
