### ISSUE TITLE
TuYa WSD500A does not expose battery or voltage

### ISSUE THREAD

**Issue by oh2xx** [Koenkk/zigbee2mqtt#10963]
### What happened?

TuYa WSD500A does not expose battery or voltage. The device [document](https://www.zigbee2mqtt.io/devices/WSD500A.html) should be updated accordingly.

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211210

### Adapter

Sonoff Zigbee 3.0

**Comment by rwb196884** [comment]
I have experinced this and thought it was probably a bug. But apparently it _can't_ work?

**Comment by oh2xx** [comment]
> 

Yes, it looks like those parameters are not exposed:
![image](https://user-images.githubusercontent.com/20955652/151695064-8447b6d5-f34c-4ba9-88a5-35d2ae878d9c.png)

**Comment by starox** [comment]
Same problem with z2m 1.24.0 commit: 7a2ddf2)
