### ISSUE TITLE
[New device support]: Prolight E27 WARM WHITE 

### ISSUE THREAD

**Issue by Bumblebeee19** [Koenkk/zigbee2mqtt#10977]
### Link

https://www.prolight.eu/fr/cat%C3%A9gories/ampoules/
Other link to a supplier : https://www.hubo.be/fr/p/prolight-smart-ampoule-led-e27-9w-dimmable/917704.html

### Database entry

{"id":10,"type":"Router","ieeeAddr":"0x00158d00046ff8db","nwkAddr":41723,"manufId":4717,"manufName":"Prolight","powerSource":"Mains (single phase)","modelId":"PROLIGHT E27 WARM WHITE","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"PROLIGHT E27 WARM WHITE","manufacturerName":"Prolight","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20181029-17","swBuildId":"2.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20181029-17","swBuildId":"2.7","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1642955621934,"useImplicitCheckin":true}

### Comments

Hello everyone,

I'm trying to help on my level and add a 'warm white E27 LED bulb' from Prolight. I think this model is no longer commercialized but in the meantime I still have some.

I followed the explanations given to add the device and took inspiration from this (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/prolight.js) to adapt the converter.

I don't know what to do now? :smile: 

Here is the debug message I get now:

`Received Zigbee message from '0x00158d00046ff8db', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":554112359,"imageType":12545,"manufacturerCode":4717}' from endpoint 1 with groupID null`

Thank you in advance for your help and congratulations for the work done!

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['PROLIGHT E27 WARM WHITE'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '5412748727364', // Vendor model number, look on the device for a model number
    vendor: 'Prolight', // Vendor of the device (only used for documentation and startup logging)
    description: 'E27 bulb dimmable', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    //fromZigbee: [fz.light_onoff_brightness], // We will add this later
    //toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    extend: extend.light_onoff_brightness(),
    //exposes: [e.battery(), e.temperature(), e.humidity()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

### Supported color modes

no color mode

**Comment by Koenkk** [comment]
added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
