### ISSUE TITLE
Device Availability works but not showing in State

### ISSUE THREAD

**Issue by Papi77** [Koenkk/zigbee2mqtt#10981]
### What happened?

When **Availability** & **Last seen** are enabled they both show-up in the dashboard as expected.
However, when viewing the State of the device - only **Last seen** is included - **Availability** is missing in the message:

![image](https://user-images.githubusercontent.com/26800136/150692677-2b52d0ae-b6f9-4aa1-af52-c728f5f7f32f.png)

-> This likely causes MQTT broker on HA not to discover the **Availability** state of the device!(?)

### What did you expect to happen?

To see "Availability" in the parameters of the State and to see it auto-discovered in HA as entity (the same way it works for last_seen).

![image](https://user-images.githubusercontent.com/26800136/150692945-40a7db2f-846e-4a1e-8ea6-ecb0e2f07c99.png)

### How to reproduce it (minimal and precise)

Enable availability: true -> view that it is shown in Z2M dashboard (column Availability will display Online or Offline) -> but no availability entity is created in HA

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210708

### Adapter

cc2652p2lan

**Comment by sjorge** [comment]
Availability is published under a different topic, it is published to `zigbee2mqtt/<device>/availability` with a payload of `offline` or `online`.

**Comment by Papi77** [comment]
So, no ability to expose it as a device entity in HA? I think it would be helpful if we also get it configured as an entity….to possibility easily display this information in Lovelace, use in automations etc. - just like we can do with “last seen”

**Comment by Koenkk** [comment]
> So, no ability to expose it as a device entity in HA?

It is not exposed separately indeed, all entities of the device will be marked as `unavailable` when it is unavailable, so you can pick any entity of the device.
