### ISSUE TITLE
Sengled Element Classic support?

### ISSUE THREAD

**Issue by Antoni-K** [Koenkk/zigbee2mqtt#11]
Would it be possible to add support for the Sengled element classic series of lightbulbs? (They are a good low cost hue white alternative).

**Comment by Koenkk** [comment]
Probably yes but I need your help for it. Can you try pairing a bulb with zigbee2mqtt?

**Comment by Koenkk** [comment]
I've created a guide on how to support new devices: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices

**Comment by Koenkk** [comment]
Let me know if you are still interested to bring support to this device, otherwise I will close this issue.
