### ISSUE TITLE
Aqara WRS-R02 double rocker not binding the second button

### ISSUE THREAD

**Issue by Steekvlam** [Koenkk/zigbee2mqtt#11002]
### What happened?

Im trying to bind the Aqara H1 wireless double rocker (WRS-R02) with the left button for lights hallway & right button for lights upstairs.
Now when I bind the left key, it works great as expected, but somehow the right key also binds with the left button so I can only bind 1 devices for both buttons.

### What did you expect to happen?

I expect to bind both left and right key to different devices.

### How to reproduce it (minimal and precise)

Operation_mode setted to 'command' under the tab Bind, selected which endpoint to destination endpoint with OnOff

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

0x26580700

### Adapter

DECONZ ConBee II Zigbee

**Comment by Koenkk** [comment]
@kirovilya do you know if the device supports this?

**Comment by kirovilya** [comment]
I couldn't get it to work in a two-button binding.
left a comment about this here https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/xiaomi.js#L1577
Perhaps Aqara will fix it with new firmware, but I have not seen them yet.

**Comment by bzeiss** [comment]
Even though this issue is closed, I do wonder if there is any chance in making this work (see also last comment in https://github.com/Koenkk/zigbee-herdsman-converters/issues/2620). It would be really great if it was possible to differentiate the buttons when the device is in command mode.
