### ISSUE TITLE
Stability problem (more month)

### ISSUE THREAD

**Issue by MikeVRT** [Koenkk/zigbee2mqtt#1101]
Perhaps I found "longtime" stability problem - zigbee2mqtt stay unstable after big log.txt (10 MB) and starts new log1.txt.
So:
1. all works to 10Mb log
2. after start new log1, all works not more then 1 day

In my case its take more then 1 month, and then log looks like:
```
2019-2-12 07:19:12 - error: Not connected to MQTT server!
2019-2-12 07:19:12 - error: Cannot send message: topic: 'zigbee2mqtt/router_cc2531', payload: '{"state":false,"linkquality":0}
2019-2-12 07:19:15 - error: Not connected to MQTT server!
2019-2-12 07:19:25 - error: Not connected to MQTT server!
2019-2-12 07:19:30 - error: Not connected to MQTT server!
2019-2-12 07:19:30 - error: Cannot send message: topic: 'zigbee2mqtt/bedroom_thp', payload: '{"temperature":19.87,"linkquality":56,"humidity":23.94,"pressure":990,"battery":99,"voltage":3015}
2019-2-12 07:19:30 - error: Not connected to MQTT server!
2019-2-12 07:19:30 - error: Cannot send message: topic: 'zigbee2mqtt/bedroom_thp', payload: '{"temperature":19.83,"linkquality":56,"humidity":24.09,"pressure":990.5,"battery":99,"voltage":3015}
2019-2-12 07:19:35 - error: Not connected to MQTT server!
2019-2-12 07:19:45 - error: Not connected to MQTT server!
2019-2-12 07:19:55 - error: Not connected to MQTT server!
2019-2-12 07:20:05 - error: Not connected to MQTT server!
2019-2-12 07:20:12 - error: Not connected to MQTT server!
2019-2-12 07:20:12 - error: Cannot send message: topic: 'zigbee2mqtt/router_cc2531', payload: '{"state":false,"linkquality":43}
2019-2-12 07:20:15 - error: Not connected to MQTT server!
2019-2-12 07:20:25 - error: Not connected to MQTT server!
2019-2-12 07:20:35 - error: Not connected to MQTT server!
2019-2-12 07:20:45 - error: Not connected to MQTT server!
2019-2-12 07:20:55 - error: Not connected to MQTT server!
2019-2-12 07:21:05 - error: Not connected to MQTT server!
2019-2-12 07:21:12 - error: Not connected to MQTT server!
2019-2-12 07:21:12 - error: Cannot send message: topic: 'zigbee2mqtt/router_cc2531', payload: '{"state":false,"linkquality":43}
2019-2-12 07:21:15 - error: Not connected to MQTT server!
2019-2-12 07:21:25 - error: Not connected to MQTT server! 
```

Can you check this part (10M+ = log->log1) of code, please?

**Comment by Koenkk** [comment]
Looking at the log, it seems that it cannot connect to the MQTT server, I don't see a direct relation with this and the log size. 

Are you sure that your MQTT server is still running? Can you connect with e.g. MQTT.fx (https://mqttfx.jensd.de/)

**Comment by MikeVRT** [comment]
> Looking at the log, it seems that it cannot connect to the MQTT server
yes, but it's only final, I think.

In reality restart of only zigbee2mqtt service helps (new log started). And restart of HASS or power off/on of USB Stick (CC2531) not needed.

**Comment by Koenkk** [comment]
So did you try if you can still connect to the MQTT server when this happens?

**Comment by MikeVRT** [comment]
I use buildin HASS mqtt, in preview case it's works, yes. When situation repeated (for repeat we must don't touch anything more than month...) - I only restarted zigbee2mqtt service, HASS still working ok, so buildin mqtt too again, I think.

**Comment by marc-gist** [comment]
Have you been able to repeat the issue? MQTT could be the issue as I've had the mosquitto mqtt broker go down without reason before.

**Comment by MikeVRT** [comment]
@marc-gist, HASS contains an embedded MQTT broker called HBMQTT, it's still works when problem happens and not needed to restart after restart of zigbee2mqtt.
I repeated this issue only 2 times, because it's need to many time for happen...

**Comment by prein2** [comment]
last week I had many things logging (debug mode and node-red dashboard generating lots of logging). within 1 day I had log1, log2 and log3. Everything still worked. So not shure the problem lies in the log names/filesize. hass integrated mqtt broker is often problematic, even within hass. hass also suggests using mosquitto is the better option. Mosquitto can be installed on the same instance as hass, so why not test it?

**Comment by MikeVRT** [comment]
> hass integrated mqtt broker is often problematic
Only one known issue was about memory leak in some cases, and now it's problem deleted from description - solved. I have no any problem with it at all. in my env. memory leaks never happens - I can show mem graph. log.
(in my case not debug mode and month+ work - it's more stressful then one week, but about log was just a hunch of cause)
