### ISSUE TITLE
[New device support]: TS0501B  _TZ3210_yluvwhjc

### ISSUE THREAD

**Issue by huizebruin** [Koenkk/zigbee2mqtt#11023]
### Link

https://www.ecodim.nl/ed-10042.html

### Database entry

{"id":42,"type":"Router","ieeeAddr":"0x0c4314fffe9ae865","nwkAddr":16203,"manufId":4098,"manufName":"_TZ3210_yluvwhjc","powerSource":"Mains (single phase)","modelId":"TS0501B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0501B","manufacturerName":"_TZ3210_yluvwhjc","powerSource":1,"zclVersion":3,"appVersion":89,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":89,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1643142952141,"useImplicitCheckin":true}

### Comments

i tried to follow te supporting page for a new device but it doesn't work.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition =[
        {
        fingerprint: [{modelID: 'TS0501B', manufacturerName: '_TZ3000_4whigl8i'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_4whigl8i'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_9q49basr'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_grnwgegn'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_yluvwhjc'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_wuheofsg'}],
        model: 'TS0501B',
        description: 'Zigbee led filament lamp dimbaar E27, globe G125, flame 2200K',
        vendor: 'EcoDim',
        extend: extend.light_onoff_brightness(),
        },
]

module.exports = definition;
```

### Supported color modes

onoff and brightness

**Comment by Koenkk** [comment]
`ED-10042` is already supported in the dev branch. (and next release on 1 Feburary) (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
