### ISSUE TITLE
[New device support]: Woox R7048 Smart Humidity & Temperature Sensor

### ISSUE THREAD

**Issue by chrisob** [Koenkk/zigbee2mqtt#11026]
### Link

https://wooxhome.com/woox-r7048-smart-humidity-temperature-sensor-p48

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xbc33acfffe26e60d","nwkAddr":49852,"manufId":4098,"manufName":"_TZ3000_rusu2vzb","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,10,1,1026,1029],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"�>�)\u0011","modelId":"TS0201","manufacturerName":"_TZ3000_rusu2vzb","stackVersion":0,"dateCode":""}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2313}},"msRelativeHumidity":{"attributes":{"measuredValue":3997}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1643149318626,"useImplicitCheckin":true}

### Comments

By default, it seems this device is mistakenly recognized as a Tuya TS0201 (I think due to using the same `modelId`?). Probably I could have left it and it would've worked fine, but the incorrect picture is bugging me ;)

I'll probably submit a PR for this soon

### External converter

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0201'],
    fingerprint: [{manufacturerName: '_TZ3000_rusu2vzb'}],
    model: 'R7048',
    vendor: 'Woox',
    description: 'Smart Humidity & Temperature Sensor',
    fromZigbee: [fz.battery, fz.temperature, fz.humidity],
    toZigbee: [],
    exposes: [e.battery(), e.temperature(), e.humidity(), e.battery_voltage()],
    configure: async (device, coordinatorEndpoint, logger) => {
        try {
            const endpoint = device.getEndpoint(1);
            const bindClusters = ['msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg'];
            await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
            await reporting.temperature(endpoint);
            await reporting.humidity(endpoint);
            await reporting.batteryVoltage(endpoint);
            await reporting.batteryPercentageRemaining(endpoint);
        } catch (e) {/* Not required for all: https://github.com/Koenkk/zigbee2mqtt/issues/5562 */
            logger.error(`Configure failed: ${e}`);
        }
    },
};

module.exports = definition;
```

**Comment by chrisob** [comment]
PR for docs: https://github.com/Koenkk/zigbee2mqtt.io/pull/1186

**Comment by chrisob** [comment]
PR for device support: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3778

**Comment by tyloch** [comment]
It does not detect my R7048 device properly.
Instead, it is identified by z2m (current installed version: 1.23.0-1 )
as https://www.zigbee2mqtt.io/devices/TS0201.html#tuya-ts0201
<img width="627" alt="Screenshot 2022-02-13 at 14 50 11" src="https://user-images.githubusercontent.com/783887/153756201-98a2ebde-937f-455c-aac9-8644540517ef.png">

**Comment by brechtvhb** [comment]
Hi,

I bought 2 of these sensors but when I added them to Z2M they did not et recognized as woox R7048 but as Tuya TS0201.
Technically not a big issue as they report the same sensors but how could I make sure zigbee recognizes it as the correct sensor?

This info might be useful for debugging:
![image](https://user-images.githubusercontent.com/330772/211645642-944ae989-8c2b-4f22-840f-58ad39490a78.png)


It took also about half an hour before it started reporting the battery status but maybe that's normal?

**Comment by trollix** [comment]
Hello,
woox R7048 : https://www.zigbee2mqtt.io/devices/R7048.html is recognize as Tuya TS0201.
