### ISSUE TITLE
Moes ZK-EU-2U Identifies as Nue / 3A HGZB-01

### ISSUE THREAD

**Issue by maoravi456** [Koenkk/zigbee2mqtt#11039]
### What happened?

When I pair new device(Moes ZK-EU-2U - Zigbee 3.0 dual USB wireless socket plug) it Identified as Nue / 3A HGZB-01 - Smart Zigbee 3.0 light controller

- Missing state_l1 and state_l2

### What did you expect to happen?

Identifies the correct model

### Zigbee2MQTT version

1.22.1-dev commit: 7625d26

### Adapter firmware version

6.7.10.0 build 423

### Adapter

Xiaomi Gateway 3(AlexxIT addon)

**Comment by Koenkk** [comment]
Make sure this also happens on z2m 1.22.2, if yes, please provide the data/database.db entry of this device?
