### ISSUE TITLE
Allow Join Button is super confusing

### ISSUE THREAD

**Issue by avviano** [Koenkk/zigbee2mqtt#11045]
### Is your feature request related to a problem? Please describe

Right now the button says either "Disable join (All)" or "Permit Join (All). I have no idea what the text actually indicated. Does it say "Permit join (all)" if you click me or is that already the actual state it is in.

There is nothing in the manual / description that hints at which state the JOIN button is actually in. I find it confusing and still to this day cannot figure out if the network is in JOIN state or not. I always have to go into the configuration to finally realize which state the button is in. Can you please make it more apparent by adding maybe a green or red light. Or at least mention it in the description. 

### Describe the solution you'd like

make the button say "Join is now active" and make it green
make the button say "Join is now deactivated" and make it red.

### Describe alternatives you've considered

nothing else to add

### Additional context

nothing else to add

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/z2m-frontend/issues
