### ISSUE TITLE
New device Paulmann zigbee remote

### ISSUE THREAD

**Issue by MarcSN311** [Koenkk/zigbee2mqtt#1104]
Hello!

I am trying to add a new device, the Paulman zigbee remote: https://de.paulmann.com/innenleuchten/smart-home/zigbee/smarthome-zigbee-fernbedienung-gent-mit-wandhalterung/50067

This is my device entry:
```
    {
        zigbeeModel: ['RemoteControl '],
        model: '50067',
        vendor: 'Paulmann',
        descriptio: 'Zigbee Remote',
        supports: 'remote',
        fromZigbee: [],
        toZigbee: [],
    },
```

The log when pairing looks like this:
https://pastebin.com/tkM99syb

When pressing a button on the remote I get nothing. Any advice on debugging that?

Thanks,
Marc

**Comment by Koenkk** [comment]
Maybe this device requires the coordinator to be added to a group, please follow https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/information/coordinator_group.md

**Comment by MarcSN311** [comment]
Thank you! I'll get another CC2531 stick and try sniffing!

**Comment by martin3000** [comment]
> Thank you! I'll get another CC2531 stick and try sniffing!

What groups did it use?
