### ISSUE TITLE
Unable to pair devices after upgrading from CC2531 to Sonoff USB 3.0 dongle

### ISSUE THREAD

**Issue by danneh82** [Koenkk/zigbee2mqtt#11053]
### What happened?

I recently upgraded from a CC2531 to the Sonoff USB 3.0 Dongle. I copied the IEEE address and after updating Z2M 1.22.2-1 all my devices reconnected and it was far more stable than the old CC2531.

After about a week the batteries died in my ikea E1743 switches. I replaced the batteries but the switches didnt reconnect. 

I tried resetting the switches, put them in pair mode and enabled permit join but when checking the logs in debug there is no messages being received. 

When trying to pair one of the switches it then took control of one of my LIDL HG06492C bulbs which now can no longer be controlled by Z2M.

I have tried putting the bulb into pair mode and enabled permit join and again there is nothing appearing in the logs.

### What did you expect to happen?

Devices to pair

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

Sonoff USB 3.0

**Comment by Koenkk** [comment]
Could be related to https://github.com/Koenkk/zigbee2mqtt/issues/9117#issuecomment-1017479712
