### ISSUE TITLE
[Feature request]: Use debug log level for MQTT publish messages

### ISSUE THREAD

**Issue by pypb** [Koenkk/zigbee2mqtt#11050]
### Is your feature request related to a problem? Please describe

At log level _info_ the log gets saturated by MQTT publish messages, which in my opinion are more debug level messages than informational. At log level _warn_ you get rid of those, but on the other hand miss out on more useful messages like startup/shutdown, connection etc.

### Describe the solution you'd like

Use _debug_ log level for MQTT publish log messages.

### Describe alternatives you've considered

A configurable log filter would be an alternative, where one could set certain messages to be excluded from the logs.

### Additional context

With 25 Zigbee devices, I get around 1000 MQTT publish log messages per hour at log level _info_.

**Comment by pypb** [comment]
> Related to #10922

Ah, yes. I missed that one - I was only looking at Issues.

However, if I understood it correctly, it seems like that PR will still output MQTT publish messages on log level _info_. I'd like to be able to have the log level at _info_ in order to see startup/shutdown messages and so on, but not the MQTT publish messages.

Perhaps a configuration option where you can choose if MQTT publish messages should be at _info_ or _debug_ would be a solution?

**Comment by Koenkk** [comment]
> Perhaps a configuration option where you can choose if MQTT publish messages should be at info or debug would be a solution?

Let's see if more people are interested in this. So those interested please do a thumbs up on the OP.

**Comment by darroyod** [comment]
Hello,

I'm also interested in this feature. It is overwhelming the amount of messages being logged when you have several devices.
Please, consider it.

Thanks in advance.
