### ISSUE TITLE
Recently added device ERS-10TZBVK-AA is not fully supported

### ISSUE THREAD

**Issue by r-vit** [Koenkk/zigbee2mqtt#11061]
### What happened?

The device got paired successfully and reports brightness_step_up, brightness_step_down and toggle events.

According to the manual there's supposed to be 'long press' and 'press and rotate' events too, which are currently not supported.

In addition to that, the devices can be switched to a so called 'scene mode' by clicking the button three times. In that mode z2m doesn't report any events.

The device seems to be bound to the default group, so it switches my xiaomi power plug on an off. I wasn't able to prevent it from doing so - I tried to remove both of the devices from the default_bind_group, which didn't help. Binding the remote to other devices or groups doesn't seem to work either, though z2m reports that the binding process was successful.

### Zigbee2MQTT version

1.2.2

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee 3.0 USB dongle

**Comment by sokolov-ml** [comment]
after last update z2m actions were changed from toggle/brightness_step_up/brightness_step_down to:
single
double
rotate_left - without any details (step size, step quantity)
rotate_right - without any details (step size, step quantity)

I`ve lost all of my scenarios with this device

**Comment by kirovilya** [comment]
Chsnge operation mode from "event" to "command"

**Comment by r-vit** [comment]
After the last update all the actions work now, thank you. 

The only problem which remains is the binding. My device is still bound to the Xiaomi Power Plug (ZNCZ02LM) and cannot be unbound from it and bound to other devices or groups.

**Comment by kirovilya** [comment]
@r-vit for the device to accept a command (for example, exclusion from the group) - you need to wake it up, twist it or press it

**Comment by r-vit** [comment]
yep, doing exactly that. z2m reports that binding was successful yet nothing changes

**Comment by kirovilya** [comment]
@r-vit here the binding does not work - it works only in a group. add a knob to the group with light bulbs - it will control them

**Comment by r-vit** [comment]
ah, nice, thank you. it does work that way - quite unusual

**Comment by itairaz1** [comment]
Hi @kirovilya I have similar problem, I just pair the device, switched it to be a command as advised, and from that stage, each click toggle both of my power plugs (Xiaomi | ZNCZ02LM), I didn't bind or do anything before. Any idea?

**Comment by kirovilya** [comment]
@itairaz1 create a group and add this device there

**Comment by itairaz1** [comment]
> @itairaz1 create a group and add this device there

<img width="685" alt="image" src="https://user-images.githubusercontent.com/6906194/155895283-c0f912ed-7d60-444a-b7a1-facf7ca28f15.png">
Tried, and it doesn't help, what am I miss?

**Comment by itairaz1** [comment]
After removing it and add it back the problem solved, thanks @kirovilya
