### ISSUE TITLE
Conbee 2 on fresh install. Zigbee2MQTT won't start

### ISSUE THREAD

**Issue by mime29** [Koenkk/zigbee2mqtt#11075]
### What happened?

The service won't start up successfully

### What did you expect to happen?

It should start up without errors

### How to reproduce it (minimal and precise)

In Home Assistant

  1. Install MQTT Add on
  2. Install Zigbee2MQTT Add on
  3. Flash your Conbee II with latest firmware, in this case `deCONZ_ConBeeII_0x26720700.bin.GCF`
  4. Startup your Home Assistant
  5. Observe the following error

I actually ran it once without flashing the conbee ii in the first place and I got a warning saying that I should flash the firmware. Which I did. 

```
[00:18:39] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-01-29 00:18:55: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-29 00:18:55: Failed to start zigbee
Zigbee2MQTT:error 2022-01-29 00:18:55: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-29 00:18:55: Exiting...
Zigbee2MQTT:error 2022-01-29 00:18:55: undefined
```

With zigbee_herdsman_debug: true

```
[00:37:05] INFO: Zigbee Herdsman debug logging enabled
[00:37:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
2022-01-28T15:37:12.145Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-01-28T15:37:12.154Z zigbee-herdsman:deconz:driver Set delay to 0
CREATED DECONZ ADAPTER
2022-01-28T15:37:12.157Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-01-28T15:37:12.158Z zigbee-herdsman:deconz:driver Opening with /dev/ttyACM0
2022-01-28T15:37:12.173Z zigbee-herdsman:deconz:driver Serialport opened
2022-01-28T15:37:12.174Z zigbee-herdsman:controller:log Started with result 'resumed'
2022-01-28T15:37:12.175Z zigbee-herdsman:controller:log Injected database: true, adapter: true
2022-01-28T15:37:12.183Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
2022-01-28T15:37:15.159Z zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
2022-01-28T15:37:15.167Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 2 request id: 1
2022-01-28T15:37:22.184Z zigbee-herdsman:deconz:driver Timeout for request - CMD: 0xa seqNr: 1
Zigbee2MQTT:error 2022-01-29 00:37:22: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-29 00:37:22: Failed to start zigbee
Zigbee2MQTT:error 2022-01-29 00:37:22: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-29 00:37:22: Exiting...
Zigbee2MQTT:error 2022-01-29 00:37:22: undefined
```

### Zigbee2MQTT version

1.22.2-1

### Adapter firmware version

0x26720700

### Adapter

Conbee II

### Debug log

Device details:

```
ttyACM0
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2478344-if00
Subsystem:
tty
Device path:
/dev/ttyACM0
ID:
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2478344-if00
Attributes:
DEVLINKS: >-
  /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2478344-if00
  /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
DEVNAME: /dev/ttyACM0
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
ID_BUS: usb
ID_MODEL: ConBee_II
ID_MODEL_ENC: ConBee\x20II
ID_MODEL_ID: '0030'
ID_PATH: platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0
ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3_1_0
ID_REVISION: '0100'
ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2478344
ID_SERIAL_SHORT: DE2478344
ID_TYPE: generic
ID_USB_DRIVER: cdc_acm
ID_USB_INTERFACES: ':020201:0a0000:'
ID_USB_INTERFACE_NUM: '00'
ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
ID_VENDOR_ID: 1cf1
MAJOR: '166'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '506042428'
```

In Home Assistant logs
```
Unexpected transmit confirm for request id 1, Status: TXStatus.SUCCESS
12:42:20 AM – (WARNING) /usr/local/lib/python3.9/site-packages/zigpy_deconz/zigbee/application.py - message first occurred at 12:11:29 AM and shows up 108 times
No watchdog response
12:41:01 AM – (WARNING) /usr/local/lib/python3.9/site-packages/zigpy_deconz/zigbee/application.py
No response to 'Command.write_parameter' command with seq id '0xe9'
12:41:01 AM – (WARNING) /usr/local/lib/python3.9/site-packages/zigpy_deconz/api.py
```

If I don't set the adapter: deconz, I get the following error:

```
Zigbee2MQTT:error 2022-01-29 11:41:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-29 11:41:54: Failed to start zigbee
Zigbee2MQTT:error 2022-01-29 11:41:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-29 11:41:54: Exiting...
Zigbee2MQTT:error 2022-01-29 11:41:55: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
```

**Comment by mime29** [comment]
Config
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

**Comment by Koenkk** [comment]
@chrishae could you check this?

**Comment by mime29** [comment]
I had the following integration installed and it seems it was the reason behind this problem...
The fact that HA detects and proposes to install this by default is just annoying because it causes incompatibility issues without explicit error messages anywhere.

Integration
"ConBee II - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2478344-if00, s/n: DE2478344 - dresden elektronik ingenieurtechnik GmbH - 1CF1:0030
Zigbee Home Automation"

Hopefully it will help other people in the future

**Comment by Koenkk** [comment]
@mime29 so the fix was uninstalling the deconz addon?

**Comment by IanAdd** [comment]
I have the same problem, I had 'ignored' the ZHA integration. Is this the problem? Does it need to be 'removed'? If so how?

**Comment by mime29** [comment]
> @mime29 so the fix was uninstalling the deconz addon?

The fix was:
- Uninstall the Deconx Add On
- Uninstall the Zigbee integration
- Reboot

**Comment by mime29** [comment]
> I have the same problem, I had 'ignored' the ZHA integration. Is this the problem? Does it need to be 'removed'? If so how?

If you ignored it, I think it means that it's already uninstalled (or at least you never installed it in the first place)

**Comment by IanAdd** [comment]
Thanks, @mime29 , my config seems to start up ok according to the logs and connects to mqtt broker, however I cannot get to the UI. The system log shows:
ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]

Any ideas?

**Comment by mime29** [comment]
> Thanks, @mime29 , my config seems to start up ok according to the logs and connects to mqtt broker, however I cannot get to the UI. The system log shows: ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
> 
> Any ideas?

No. I actually have the exact same problem.
I have to restart the zigbee2mqtt service, wait for like 30 seconds and then I can access the web interface.
I think that's not normal but that might be another bug, unrelated to this one. No idea what to do about this.

**Comment by mime29** [comment]
I tried to permit join and got the following error 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[15:35:35] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[15:35:36] INFO: MQTT available, fetching server detail ...
[15:35:36] INFO: MQTT server settings not configured, trying to auto-discovering ...
[15:35:37] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[15:35:37] INFO: Previous config file found, checking backup
[15:35:37] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[15:35:37] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:35:38] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-01-31 15:36:45: Failed to set permit join to false
```

**Comment by SamMousa** [comment]
@mime29 you're unfortunately hijacking your own thread! 

I've got the same issue as you described in your original post. Rebooting the host after removing the ZHA integration unfortunately does not resolve it.

I did not have the deconz addon installed.

**Comment by mime29** [comment]
> @mime29 you're unfortunately hijacking your own thread!
> 
> I've got the same issue as you described in your original post. Rebooting the host after removing the ZHA integration unfortunately does not resolve it.
> 
> I did not have the deconz addon installed.
> 
> Edit: reactivating the ZHA integration does show me the connected devices so it feels like the adapter itself is working...

What do you mean by I'm "Hijacking" my thread ? :)

**Comment by SamMousa** [comment]
Hijacking is when someone describes an issue A and someone else, in this case the same person adds a different issue B to the same thread. This makes it harder for everyone to discuss.

**Comment by cbachmann987** [comment]
I have exactly the same problem as originally described above. No Deconz integration or ZHA integraton had been installed, so problem not solved. Anybody has further ideas?

**Comment by Woutoud** [comment]
In ended up fixing this issue by creating a new user in Home Assistant and using those credentials to configure the Mosquitto broker integration, after that I reinstalled Zigbee2MQTT and used the following config:
```
mqtt
server: mqtt://core-mosquitto:1883
user: mosquitto_password
password: mosquitto_password

serial
port: /dev/ttyACM0
adapter: deconz
```

**Comment by Soukyuu** [comment]
If someone stumbles upon this like I did: in my case I did a firmware downgrade of the Conbee II to the last recommended version and despite it saying the flashing was successful, it seemingly was not. Tje only way I could get zigbee2mqtt to start was to actually reflash the same firmware on the Conbee II

**Comment by andreas-bulling** [comment]
Which version is the latest recommended one, if I may ask?
