### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by quentinreytinas** [Koenkk/zigbee2mqtt#11070]
### Link

https://casaia.fr/product/module-relais-contact-sec-zigbee-2/

### Database entry

{"id":51,"type":"Router","ieeeAddr":"0x3c6a2cfffed0ecb3","nwkAddr":2620,"manufId":4412,"manufName":"CASAIA","powerSource":"Unknown","modelId":"CSLC601-D-E","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"CSLC601-D-E","manufacturerName":"CASAIA","powerSource":0,"zclVersion":3,"dateCode":"20210616"}}},"binds":[],"configuredReportings":[],"meta":{}}},"dateCode":"20210616","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1643369887921,"useImplicitCheckin":true}

### Comments

Hello,
I am using home assistant on a raspberrypi. For now, I already use devices that are compatible with Zigbee2Mqtt but I need this device for connected my gaz boiler to home assistant.
Could you help me to add it please? I have no idea to use herdsmann converter on home assistant. I don't use a docker or something else. Just a raspberrypi with only home assistant on it.
I try to create a file chaudiere.js with the indications on your page.
Thanks a lot.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['CSLC601-D-E'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'CSLC601-D-E', // Vendor model number, look on the device for a model number
    vendor: 'CASAIA', // Vendor of the device (only used for documentation and startup logging)
    description: 'Dry contact relay switch module in 220v AC for gaz boiler', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.on_off], // We will add this later
    toZigbee: [tz.on_off], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.switch()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
