### ISSUE TITLE
Message missing in hassio

### ISSUE THREAD

**Issue by neerdoc** [Koenkk/zigbee2mqtt#1108]
I have two setups which I switch between. First is a zigbee2mqtt in a terminal window where I debug and code. Second is "production" which is a HassIO-installation on a Raspberry Pi.

I have recently added battery measurements to the smoke detector HS1SA which works perfectly fine in the terminal installation. The battery measurement is sent to the MQTT.

However, in the HassIO-installation, it does not. I'm running the "dev"-branch of the zigbee2mqtt container and it states that it is on version 1.1.1 (commit #3d15129), which should contain my changes and thus include the battery report. 

The difference can be seen [here](https://pastebin.com/epP8GVLc).

What am I missing? Do I have to make an adaptation somewhere else to get it to work in HassIO?

**Comment by Koenkk** [comment]
Changes in zigbee-shepherd-converters are not automatically used by zigbee2mqtt.

- First a new version of zigbee-shepherd-converters has to be generated: (https://github.com/Koenkk/zigbee-shepherd-converters/commit/b4ac88327b8d7f131ccf951272792d297d88444b)
- Then zigbee2mqtt has to use this new version of zigbee-shepherd-converters. (https://github.com/Koenkk/zigbee2mqtt/commit/a20ec7caa1c3224667c6141568e2f0ba6b3b838d)

I've just done this, your changes are in the `dev` branch now
