### ISSUE TITLE
[New device support]: Smoke sensor TS0601 _TZE200_yh7aoahi

### ISSUE THREAD

**Issue by jocamane** [Koenkk/zigbee2mqtt#11119]
### Link

https://pt.aliexpress.com/item/1005002284013316.html?gatewayAdapt=glo2bra&spm=a2g0s.12269583.0.0.14d66f73TAcBoa

### Database entry

{"id":36,"type":"EndDevice","ieeeAddr":"0x84fd27fffeca5ada","nwkAddr":32700,"manufId":4098,"manufName":"_TZE200_yh7aoahi","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_yh7aoahi","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1643548709601,"useImplicitCheckin":true}

### Comments

Warning Device '0x84fd27fffeca5ada' with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_yh7aoahi'
Warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by jocamane** [comment]
hi, would it be possible for someone to help me.
thanks

**Comment by jocamane** [comment]
Hum....

Itried to do an External by myself, but something is not right.

After adding the device to the z2m it gives the following errors in the log: 

Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Error Failed to configure '0x84fd27fffeca5ada', attempt 2 (Error: Bind 0x84fd27fffeca5ada/1 genBasic from '0x00212effff07afaa/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:753:19) at runMicrotasks (<anonymous>) at runNextTicks (internal/process/task_queues.js:60:5) at processTimers (internal/timers.js:497:9) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:522:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9) at Object.configure (/app/dist/util/externally-loaded.js:25:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))


MY External:
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition =[
    {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_t5p1vj8r'}, 
            {modelID: 'TS0601', manufacturerName: '_TZE200_uebojraa'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_yh7aoahi'}],
        model: 'TS0601_smoke',
        vendor: 'TuYa',
        description: 'Smoke sensor',
        whiteLabel: [{vendor: 'TuYa ', model: 'TS0601_smoke'}],
        fromZigbee: [fz.tuya_smoke],
        toZigbee: [],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
        exposes: [e.smoke(), e.battery_low(), e.tamper(), e.battery()],
    },
]

module.exports = definition;


what is not ok ?

**Comment by jocamane** [comment]
![image](https://user-images.githubusercontent.com/32019937/152702220-0bdf4bb3-1420-4bbe-9fb1-e67385fdd49c.png)

**Comment by jocamane** [comment]
can anyone help me?

**Comment by jocamane** [comment]
I asked for help but one at a time please !!!

**Comment by Koenkk** [comment]
Seems this device uses different data points compared to already supported TS0601 smoke sensors. You can find out which via https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html

**Comment by jocamane** [comment]
Thanks Koenkk,
After i find the "codes" what do i need to do ?

In my case:
silence = Code 16
smoke detection state = code 1
Fault Alarm = Code 11
battery level state = code 14
battery level = Code 15

![image](https://user-images.githubusercontent.com/32019937/159085881-a423878b-e147-4e29-9f9a-a29878417f36.png)

**Comment by Koenkk** [comment]
That looks like the correct info, if 1 is indeed the smoke state it should already work with the converter from https://github.com/Koenkk/zigbee2mqtt/issues/11119#issuecomment-1030918708 , what is logged when you trigger the sensor with smoke?

**Comment by jocamane** [comment]
Hi,
When exist smoke the sensor work ok and indicate true, but the battery don't work and errors continue to appear in the log:

Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}

**Comment by jocamane** [comment]
and after errors :

Error Failed to configure '0x84fd27fffeca5ada', attempt 1 (Error: Bind 0x84fd27fffeca5ada/1 genBasic from '0x00212effff07afaa/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:761:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:34:9) at Object.configure (/app/dist/util/externally-loaded.js:23:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))

**Comment by jocamane** [comment]
and after each detection:

Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #14 with data {"dp":14,"datatype":4,"data":{"type":"Buffer","data":[2]}}
Warning zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #15 with data {"dp":15,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,100]}}

**Comment by Koenkk** [comment]
Could you try with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const fzLocal = {
    tuya_smoke: {
        cluster: 'manuSpecificTuya',
        type: ['commandDataResponse', 'commandDataReport'],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            for (const dpValue of msg.data.dpValues) {
                const dp = dpValue.dp;
                const value = tuya.getDataValue(dpValue);
                switch (dp) {
                case tuya.dataPoints.state:
                    result.smoke = value === 0;
                    break;
                case 14:
                    // battery state, ignore
                    break
                case 15:
                    result.battery = value;
                    break;
                default:
                    meta.logger.warn(`zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #${ dp} with data ${JSON.stringify(dpValue)}`);
                }
            }
            return result;
        },
    }
}

const definition = {
    zigbeeModel: ['5p1vj8r'],
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_t5p1vj8r'}, {modelID: 'TS0601', manufacturerName: '_TZE200_uebojraa'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_yh7aoahi'}],
    model: 'TS0601_smoke',
    vendor: 'TuYa',
    description: 'Smoke sensor',
    fromZigbee: [fzLocal.tuya_smoke],
    toZigbee: [],
    exposes: [e.smoke(), e.battery_low()],
};

module.exports = definition;

```

**Comment by jocamane** [comment]
It's better. No errors, but...
The battery apear in "state" but not in "Exposes",

![image](https://user-images.githubusercontent.com/32019937/159128518-355ce145-4646-49db-93b3-6c667d3e256e.png)
![image](https://user-images.githubusercontent.com/32019937/159128529-eed4e0e9-83c2-4439-ab9d-1e87fcd980dd.png)
![image](https://user-images.githubusercontent.com/32019937/159128607-c727bdac-fedc-4e27-83fe-08ea9c548cc3.png)

strange

also in HA devices:
![image](https://user-images.githubusercontent.com/32019937/159128587-c28604a3-ce17-4681-87e0-abf4548a6fd4.png)

**Comment by Koenkk** [comment]
try with:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const fzLocal = {
    tuya_smoke: {
        cluster: 'manuSpecificTuya',
        type: ['commandDataResponse', 'commandDataReport'],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            for (const dpValue of msg.data.dpValues) {
                const dp = dpValue.dp;
                const value = tuya.getDataValue(dpValue);
                switch (dp) {
                case tuya.dataPoints.state:
                    result.smoke = value === 0;
                    break;
                case 14:
                    // battery state, ignore
                    break
                case 15:
                    result.battery = value;
                    break;
                default:
                    meta.logger.warn(`zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #${ dp} with data ${JSON.stringify(dpValue)}`);
                }
            }
            return result;
        },
    }
}

const definition = {
    zigbeeModel: ['5p1vj8r'],
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_t5p1vj8r'}, {modelID: 'TS0601', manufacturerName: '_TZE200_uebojraa'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_yh7aoahi'}],
    model: 'TS0601_smoke',
    vendor: 'TuYa',
    description: 'Smoke sensor',
    fromZigbee: [fzLocal.tuya_smoke],
    toZigbee: [],
    exposes: [e.smoke(), e.battery()],
};

module.exports = definition;

```

**Comment by jocamane** [comment]
spectacular !! Thank you

PS: Can you now solve the others that have been pending for some time? 
ie. https://github.com/Koenkk/zigbee2mqtt/issues/11392 and the #10903

**Comment by jocamane** [comment]
Please include more this  TS0601_TZE200_vzekyi4c
is another smoke sensor that i have.
I will try add in external, but in future versions include twice

thanks

**Comment by jocamane** [comment]
The new version:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const fzLocal = {
    tuya_smoke: {
        cluster: 'manuSpecificTuya',
        type: ['commandDataResponse', 'commandDataReport'],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            for (const dpValue of msg.data.dpValues) {
                const dp = dpValue.dp;
                const value = tuya.getDataValue(dpValue);
                switch (dp) {
                case tuya.dataPoints.state:
                    result.smoke = value === 0;
                    break;
                case 14:
                    // battery state, ignore
                    break
                case 15:
                    result.battery = value;
                    break;
                default:
                    meta.logger.warn(`zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #${ dp} with data ${JSON.stringify(dpValue)}`);
                }
            }
            return result;
        },
    }
}

const definition = {
    zigbeeModel: ['5p1vj8r'],
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_t5p1vj8r'}, {modelID: 'TS0601', manufacturerName: '_TZE200_uebojraa'},
        {modelID: 'TS0601', manufacturerName: '_TZE200_yh7aoahi'}, {modelID: 'TS0601', manufacturerName: '_TZE200_vzekyi4c'}],
    model: 'TS0601_smoke',
    vendor: 'TuYa',
    description: 'Smoke sensor',
    fromZigbee: [fzLocal.tuya_smoke],
    toZigbee: [],
    exposes: [e.smoke(), e.battery()],
};

module.exports = definition;

**Comment by Koenkk** [comment]
great, pushed the fix

**Comment by jocamane** [comment]
ok
Z2M getting better 

you are the boss :)

**Comment by viko-repo** [comment]
Hi, can you help please
Hey
I have it appears exactly as it says here but there is still an error

https://www.aliexpress.com/item/1005002214198266.html

Manufacturer: _TZE200_dq1mfjug

<img width="388" alt="0" src="https://user-images.githubusercontent.com/14986387/165811392-a858a1e7-acf1-4f50-b79c-ace9b439a36a.png">
<img width="941" alt="1" src="https://user-images.githubusercontent.com/14986387/165811401-3287da23-3686-4ac0-a95c-b45cadf87805.png">
<img width="791" alt="2" src="https://user-images.githubusercontent.com/14986387/165811406-e527ebc2-0cb2-4134-ba43-06ffde96de5d.png">

**Comment by jmarfer** [comment]
> The new version:
> 
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee'); const tz = require('zigbee-herdsman-converters/converters/toZigbee'); const exposes = require('zigbee-herdsman-converters/lib/exposes'); const reporting = require('zigbee-herdsman-converters/lib/reporting'); const extend = require('zigbee-herdsman-converters/lib/extend'); const ota = require('zigbee-herdsman-converters/lib/ota'); const e = exposes.presets; const ea = exposes.access; const tuya = require('zigbee-herdsman-converters/lib/tuya');
> 
> const fzLocal = { tuya_smoke: { cluster: 'manuSpecificTuya', type: ['commandDataResponse', 'commandDataReport'], convert: (model, msg, publish, options, meta) => { const result = {}; for (const dpValue of msg.data.dpValues) { const dp = dpValue.dp; const value = tuya.getDataValue(dpValue); switch (dp) { case tuya.dataPoints.state: result.smoke = value === 0; break; case 14: // battery state, ignore break case 15: result.battery = value; break; default: meta.logger.warn(`zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #${ dp} with data ${JSON.stringify(dpValue)}`); } } return result; }, } }
> 
> const definition = { zigbeeModel: ['5p1vj8r'], fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_t5p1vj8r'}, {modelID: 'TS0601', manufacturerName: '_TZE200_uebojraa'}, {modelID: 'TS0601', manufacturerName: '_TZE200_yh7aoahi'}, {modelID: 'TS0601', manufacturerName: '_TZE200_vzekyi4c'}], model: 'TS0601_smoke', vendor: 'TuYa', description: 'Smoke sensor', fromZigbee: [fzLocal.tuya_smoke], toZigbee: [], exposes: [e.smoke(), e.battery()], };
> 
> module.exports = definition;

Good afternoon, where do I have to put this code for the smoke sensor to work?

Thank you
