### ISSUE TITLE
Philips 3261330P6 [New device support]: 

### ISSUE THREAD

**Issue by jay-jey** [Koenkk/zigbee2mqtt#11118]
### Link

https://www.zigbee2mqtt.io/devices/3261331P6.html

### Database entry

{"id":74,"type":"Router","ieeeAddr":"0x00178801098149aa","nwkAddr":6392,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"3261330P6","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,""inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":972D,"inClusterList":[],"outClusterL2Dist":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2D2,"stackVersion":1,"hwVersion":0,"dateCode":"20190529","swBuildId":"1.56.7_r29434","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1643456571747,"defaultSendRequestWhen":"immediate"}

### Comments

Hello, I have a Philips 3261330 bulb here. It is basically the same as the Philips 3261331. Which is allready supported. If changed the entry in the phlips.js from 
zigbeeModel: ['3261331P6'],
to 
zigbeeModel: ['3261331P6' , '3261330P6'],
(line 1302)
and it works. So just a little change. Hope you cloud accept this without the hole convert thing and pull request. 

### Supported color modes

color Temperature

### Color temperature range

{colorTempRange: [153, 454]}),

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) (and in the next release on 1 February)

**Comment by jay-jey** [comment]
Thanks.
