### ISSUE TITLE
Erroneous reporting old values on restart (with persistence off) 

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#11115]
### What happened?

That's quite a minor issue, but it throws off the whole whole energy consumption calculation from HA:

I got four TuYa TS0121_plug and at least 3 of them show (what looks like) random drops <strike>to 0 kWh</strike> on the energy meter. The graph is hiding a bit how low the value drops (I guess).

![IMG_20220130_070034](https://user-images.githubusercontent.com/614929/151688749-d62e0445-610e-4e37-896e-eacdaf666a0d.jpg)
![IMG_20220130_070132](https://user-images.githubusercontent.com/614929/151688751-c37829cd-8161-4248-b921-b3954b76a4c2.jpg)
![Screenshot_2022-01-30-07-00-56-632_com brave browser](https://user-images.githubusercontent.com/614929/151688755-e3e7a568-8b5a-4777-908f-3c323b4683a1.jpg)

Not sure if a configuration setting is responsible for that:

```
"availability_timeout": 3600,
"cache_state": true,
"cache_state_persistent": false,
"cache_state_send_on_startup": false,
"homeassistant_legacy_entity_attributes": true,
"homeassistant_legacy_triggers": true,
"last_seen": "disable",
"legacy_api": false,
```

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20201026

### Adapter

Slaesh's CC2652RB

**Comment by RubenKelevra** [comment]
Here's such an event more detailed. Looks not like a drop to 0 but some old value to be pushed to HA before the device has send its own new value.

Could there be an issue with turned off persistence, that still the some values are stored and then restored? 🤔

![IMG_20220130_113036](https://user-images.githubusercontent.com/614929/151696076-3f7674c3-869d-4e22-96df-88de13c2b400.jpg)

**Comment by RubenKelevra** [comment]
I think if that's the case it would also explain this behaviour:

![IMG_20220128_120408](https://user-images.githubusercontent.com/614929/151696181-eccaf8a7-5041-430b-a2e0-43b2b2777ca9.jpg)

The switch turns "on" for HA from unavailable and 20 seconds later it turns "off". After a restart of Z2M.

While the switch remained in the off position all the time.

That's kind of messing with my automations, since they react to on/off changes of the switch which then turns the smart light bulb on/off (which has power permanently).

This switch is a ZB Mini.

**Comment by RubenKelevra** [comment]
I can confirm this bug for [1.23.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.23.0) as well:

![wrong energy counting](https://user-images.githubusercontent.com/614929/152687208-9f41e042-4748-4b14-bfa9-c60a81c51ff5.png)

**Comment by maxbec** [comment]
Hey guys. Any fix on this?
