### ISSUE TITLE
zigbee2mqtt fails to start - - serial must be object

### ISSUE THREAD

**Issue by thetravellor** [Koenkk/zigbee2mqtt#11121]
### What happened?

I replaced a dead 2652R (zzh) with a 2652RB stick (slae.sh)

I have flashed the 2652RB with coordinator firmware

When attempting to restart zigbee2mqtt, the startup fails.

When I restart zigbee2mqtt I get:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY

Refusing to start because configuration is not valid, found the following errors:
- serial must be object

If you don't know how to solve this, read https://www.zigbee2mqtt.io/guide/configuration

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.22.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-30T13_30_43_561Z-debug.log

### What did you expect to happen?

Zigbee2m

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

Z-Stack-firmware/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20211217.hex

### Adapter

Slaes CC2652RB

### Debug log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v14.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.22.1~prestart: zigbee2mqtt@1.22.1
6 info lifecycle zigbee2mqtt@1.22.1~start: zigbee2mqtt@1.22.1
7 verbose lifecycle zigbee2mqtt@1.22.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.22.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle zigbee2mqtt@1.22.1~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.22.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.22.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.22.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.22.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid zigbee2mqtt@1.22.1
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.10.63-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.18.2
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.22.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.22.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Koenkk** [comment]
The syntax of your `configuration.yaml` is correct, see https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html
