### ISSUE TITLE
[New device support]:  _TZ3000_6uzkisv2 Tuya Temperature & Humidity Sensor

### ISSUE THREAD

**Issue by grzegorzmik** [Koenkk/zigbee2mqtt#11133]
### Link

https://pl.aliexpress.com/i/1005003020786455.html

### Database entry

{"id":35,"type":"EndDevice","ieeeAddr":"0x2c1165fffe513da0","nwkAddr":2631,"manufId":4098,"manufName":"_TZ3000_6uzkisv2","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,1,3,1026,1029],"outClusterList":[25,10,3],"clusters":{"genBasic":{"attributes":{"modelId":"TS0201","manufacturerName":"_TZ3000_6uzkisv2","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1643566147149,"useImplicitCheckin":true}

### Comments

Currently z2m (version: 1.22.2-1) treats this device as a temperature & humidity sensor with LCD display (the same as _TZ2000_a476raq2) however it doesn't have the screen and is few times smaller.

It is pairing but no exposes are shown (n/a from  top to bottom, with exception of link quality).

I tried to follow the add new devices support page but after adding my .js file to external_converters, zigbee2mqtt crashes.

I've created external converter based on other Tuya model (but cannot verify if it works due to the crash in z2m).

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const devices = [
    {
    fingerprint: [
            {type: 'EndDevice', manufacturerID: 4098},
            {manufacturerName: '_TZ3000_6uzkisv2'},
        ],
        //zigbeeModel: ['TS0201'],
        model: 'TS0201',
        vendor: 'PCBLab',
        description: 'Temperature & humidity sensor without display',
        fromZigbee: [fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.temperature(), e.humidity()],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement']);
            await reporting.temperature(endpoint);
        },
    },
];
module.exports = devices;
```

**Comment by wuzyzy** [comment]
I have a similar sensor, and the manufacturerName is "_TZ3000_hzkeh3nv" and all response is the same as [grzegorzmik](https://github.com/grzegorzmik)'s issue! It would be great if you guys can support this device.
