### ISSUE TITLE
configuration.yaml documentation improvement

### ISSUE THREAD

**Issue by segaura** [Koenkk/zigbee2mqtt#11163]
### What happened?

Sorry if this is the wrong place to submit these issue, but the documentation github does not provide issues.

The documentation page here

https://www.zigbee2mqtt.io/advanced/zigbee/02_improve_network_range_and_stability.html#reduce-wi-fi-interference-by-changing-the-zigbee-channel

states that the `channel` parameter can be set in `configuration.yaml` and link this page

https://www.zigbee2mqtt.io/guide/configuration/

but in this page no detail is provided regarding `channel` anche the whole `advanced` section of the yaml file.

### What did you expect to happen?

https://www.zigbee2mqtt.io/guide/configuration/

should contain documentation regarding `channel` anche the whole `advanced` section

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20211220

### Adapter

Sonoff ZigBee 3.0 Dongle Plus

**Comment by Koenkk** [comment]
Fixed, thanks for reporting.
