### ISSUE TITLE
lot of traffic in zigbee2mqtt/bridge/config/devices

### ISSUE THREAD

**Issue by geieraffe** [Koenkk/zigbee2mqtt#11162]
### What happened?

Today I noticed a lot of traffic in zigbee2mqtt/bridge/config/devices.
The payload seems to be a timestamp.
I tried to read out more information of the message, but I couldn't find anything interessting, like a sender or something.
Messages occur every ~4sec.

This also triggers logging under zigbee2mqtt/bridge/log.
But comparing two consecutive logs, most time only lastSeen of the coordinator changed.
But it's not the timestamp I received just before.

### What did you expect to happen?

I didn't expect to get so much traffic from these messages.
Especially since I know it hasn't always been like this and I have no idea where this timestamp comes from.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20190223

### Adapter

CC2531 Stick

**Comment by RobLeighton67** [comment]
I'd recommend flashing to a more recent firmware from
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin
for build 1.22.1 as there's definitely been some changes that seem to need it - plus it fixes the need to power cycle the CC2531 if you restart z2m
