### ISSUE TITLE
[New device support]: _TZ3210_it1u8ahz [TS0505B] GU10 RGBCW Bulb

### ISSUE THREAD

**Issue by reaper7** [Koenkk/zigbee2mqtt#11176]
### Link

https://shopee.pl/READY-tuya-ZigBee-Smart-Gu10-%C5%BCar%C3%B3wka-LED-Reflektor-tuya-inteligentna-%C5%BCywotno%C5%9B%C4%87-aplikacja-3.5W-RGBCW-Sterowanie-g%C5%82osowe-Praca-z-Alexa-Google-Home-marg-i.545212414.14205395307

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0xa4c13820f2798ffb","nwkAddr":40780,"manufId":4417,"manufName":"_TZ3210_it1u8ahz","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_it1u8ahz","powerSource":1,"zclVersion":3,"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":20480,"currentY":21558,"currentHue":4,"currentSaturation":254,"colorTemperature":500}},"genOnOff":{"attributes":{"onOff":0}},"manuSpecificTuya_3":{"attributes":{}},"genLevelCtrl":{"attributes":{"currentLevel":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1643743063376,"defaultSendRequestWhen":"immediate"}

### Comments

My external converter based on the existing one for TuYa TS0505B.
Unlike the currently supported TS0505B devices this one doesn't seem to support ColorTempStartup,
also all default effects for TS0505B family on this one looks the same...
so, in my external converter I turned them off.

On this temporary converter the device often does not respond properly,
triggering from HA scenes with the following parameters 
```
      state: on
      color_mode: "color_temp"
      brightness: 10
      color_temp: 500
```

Sometimes it works as it should, but often it just turns off automatically after being turned on (~1sec)
and it does not matter whether I turn it on via HA or directly via the Z2M panel,
in this case only a change of brightness or turning ON twice turns on the bulb permanently.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0505B',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZ3210_it1u8ahz'
        },
    ],
    model: 'TS0505B',
    vendor: 'TuYa',
    description: 'Zigbee RGB+CCT light',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color(
        {disableColorTempStartup: true, colorTempRange: [153, 500], disableEffect: true}),
    meta: {applyRedFix: true, enhancedHue: false},
};

module.exports = definition;
```

### Supported color modes

color_temp, xy

### Color temperature range

153-500

**Comment by fifisoft57** [comment]
Hello

despite the update, the device is still not supported

where we are ?

thank you
