### ISSUE TITLE
Legrand 067774 "off" issue in 1.23.0

### ISSUE THREAD

**Issue by wurff** [Koenkk/zigbee2mqtt#11188]
### What happened?

After updating to 1.23.0 two button Legrand 067774 wireless swithes work incorrectly - both buttons produce "off" events instead of 'off-left' and 'off-right'.

Apparently this is caused by lsat changes to legrand.js 
This part 
```
const fzLocal = {
    command_off: {
        cluster: 'genOnOff',
        type: 'commandOff',
        convert: (model, msg, publish, options, meta) => {
            return {action: 'off'};
        },
    },
};
```
should be probably replaced by 
```
const fzLocal = {
    command_off: {
        cluster: 'genOnOff',
        type: 'commandOff',
        convert: (model, msg, publish, options, meta) => {
            const payload = {action: utils.postfixWithEndpointName('off', msg, model)};
            utils.addActionGroup(payload, msg, model);
            return payload;
        },
    },
};
```

### What did you expect to happen?

Expected to see them producing 'off_left' and 'off_right' for respective buttons.

### How to reproduce it (minimal and precise)

Just update to 1.23.0

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20210708

### Adapter

CC2652 Egony

**Comment by Koenkk** [comment]
thanks, fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
