### ISSUE TITLE
[New device support]: Philips Hue Gradient Signe floor lamp (Black)

### ISSUE THREAD

**Issue by Klangen82** [Koenkk/zigbee2mqtt#11186]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-gradient-signe-floor-lamp/8718696176283

### Database entry

{"id":50,"type":"Router","ieeeAddr":"0x001788010b9153db","nwkAddr":47743,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"915005987201","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210407","swBuildId":"1.86.6","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1643799229389,"defaultSendRequestWhen":"immediate"}'

### Comments

Believe that Philips started to come out with some gen 2 of the same devices as my Philips Hue Gradient Signe floor lamp (Black) reports model number 915005987201 and not 4080248U9

https://www.zigbee2mqtt.io/devices/4080248U9.html

Please let me know if more info is needed!

### Supported color modes

light (state, brightness, color_temp, color_temp_startup, color_xy, color_hs), effect, linkquality

### Color temperature range

 [hueExtend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]})]

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Klangen82** [comment]
Thanks @Koenkk fast you are = I like :) Keep up the great work!
