### ISSUE TITLE
TS0601_TZE200_iossyxra lost cover entity in 1.23.0

### ISSUE THREAD

**Issue by VladNord** [Koenkk/zigbee2mqtt#11190]
### What happened?

After updating to latest z2m 1.23.0 TS0601_TZE200_iossyxra lost cover entity in latest update.
just select entities.
<img width="684" alt="Снимок экрана 2022-02-02 в 17 09 49" src="https://user-images.githubusercontent.com/51515620/152181631-0842cf24-fa98-43f9-97cf-1c3dc0b2c9fb.png">

in previous version everything is ok

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

conbee2

**Comment by Koenkk** [comment]
This was done in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3677 by @Burki24. @Burki24 could make a pr to correct this?

**Comment by Burki24** [comment]
> This was done in [Koenkk/zigbee-herdsman-converters#3677](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3677) by @Burki24. @Burki24 could make a pr to correct this?

Yes, I'm working on it ASAP.

**Comment by Burki24** [comment]
@VladNord 

Work is done: 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3836#issuecomment-1031644151
![image](https://user-images.githubusercontent.com/20765982/152919650-49cd5ee0-46a0-4c79-b1fb-de69ff8a550e.png)

**Comment by VladNord** [comment]
> @VladNord
> 
> Work is done, please verify that local, so we can close this issue, thanks. [Koenkk/zigbee-herdsman-converters#3836 (comment)](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3836#issuecomment-1031644151) ![image](https://user-images.githubusercontent.com/20765982/152919650-49cd5ee0-46a0-4c79-b1fb-de69ff8a550e.png) ![image](https://user-images.githubusercontent.com/20765982/152919858-cb23ece1-20a2-47c2-a961-74d6b7a10d21.png)

Thanks!
Can you send manual how I can test this improvement before release, please?

**Comment by Burki24** [comment]
@VladNord This update was merged 10 days ago. So it's allready included in mster-branch.
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3836#issuecomment-1031644151
