### ISSUE TITLE
Zigstar usb led

### ISSUE THREAD

**Issue by mazmar** [Koenkk/zigbee2mqtt#11198]
### What happened?

This might not be related to zigbee2mqtt. But i bought zigstar usb dongle with z2m firmware and i cannot tur off the led

i’ve tried using disable_led: true but it didn’t work

any ideas how to check what fw i have? I am running debian linux with docker on raspberry pi

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20210218

### Adapter

Zigstar dongle

**Comment by Koenkk** [comment]
LED control has been added in the 20210708 firmware, you are on an older firmware so please upgrade (https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/CHANGELOG.md)
