### ISSUE TITLE
[New device support]: Please add support for Yale YMF40A RL

### ISSUE THREAD

**Issue by juslex** [Koenkk/zigbee2mqtt#11199]
### Link

https://www.yalehome.com.br/pt-BR/produtos1/products/fechaduras-digitais-biometricas/fechadura-digital-ymf40arl/

### Database entry

{"id":24,"type":"EndDevice","ieeeAddr":"0x000d6f00168a4334","nwkAddr":58632,"manufId":4491,"manufName":"ASSA ABLOY iRevo","powerSource":"Battery","modelId":"06ffff2027","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":10,"inClusterList":[0,1,3,4,5,9,10,32,257],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"06ffff2027","manufacturerName":"ASSA ABLOY iRevo","powerSource":3,"zclVersion":1,"appVersion":11,"hwVersion":0}},"genPollCtrl":{"attributes":{"checkinInterval":360}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":100}},"closuresDoorLock":{"attributes":{"lockState":1}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f070","endpointID":1},{"cluster":257,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f070","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f070","endpointID":1}],"configuredReportings":[{"cluster":257,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":11,"hwVersion":0,"zclVersion":1,"interviewCompleted":true,"meta":{"configured":923668394},"lastSeen":1643830970574,"defaultSendRequestWhen":"fastpoll"}

### Comments

I added the following entry to yale.js using the same code as YMF40/YDM4109+ but I don't have correct information about the lock battery. apart from this error, the lock seems to work correctly

### External converter

```shell
{
        zigbeeModel: ['06ffff2027'],
        model: 'YMF40A',
        vendor: 'Yale',
        description: 'Real living lock / Intelligent biometric digital lock',
        extend: lockExtend(),
    },
```

**Comment by juslex** [comment]
<img width="1079" alt="Captura de Tela 2022-02-02 às 16 47 06" src="https://user-images.githubusercontent.com/66561713/152225950-e6b7378f-0f6f-4d21-ac26-96a9690dda58.png">

**Comment by juslex** [comment]
<img width="272" alt="Captura de Tela 2022-02-02 às 16 47 36" src="https://user-images.githubusercontent.com/66561713/152226022-9492a186-3ffb-45cb-809c-9b33a7c38a94.png">

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3802

**Comment by cmagno369** [comment]
@Koenkk 
Can you please add for YMF40A RL:

 {
        zigbeeModel: ['06e01d220c'],
        model: 'YMF40A RL',
        vendor: 'ASSA ABLOY iRevo',
        description: 'Real living lock / Intelligent biometric digital lock',
        extend: lockExtend(),
    }

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
