### ISSUE TITLE
Error in console.log : 'GL-C-006P' has configure in extend and device, this is not allowed

### ISSUE THREAD

**Issue by EXP-Carthage** [Koenkk/zigbee2mqtt#11208]
### What happened?

When Zigbee2MQTT is launched, this information is displayed in the terminal :
```
npm start

> zigbee2mqtt@1.23.0 start /opt/zigbee2mqtt
> node index.js

'GL-C-006P' has configure in extend and device, this is not allowed
'GL-C-007P' has configure in extend and device, this is not allowed
'GL-C-003P' has configure in extend and device, this is not allowed
'GL-C-008P' has configure in extend and device, this is not allowed
'GL-C-009P' has configure in extend and device, this is not allowed
Zigbee2MQTT:debug 2022-02-03 16:37:19: Loaded state from file /opt/zigbee2mqtt/data/state.json 
```

At first sight, this does not prevent the operation but during pull requests, an error automatically comes out because of the `console.log` 
```
'GL-C-006P' has configure in extend and device, this is not allowed
'GL-C-007P' has configure in extend and device, this is not allowed
'GL-C-003P' has configure in extend and device, this is not allowed
'GL-C-008P' has configure in extend and device, this is not allowed
'GL-C-009P' has configure in extend and device, this is not allowed
```

The problem exists on the master branch as well as the dev branch.

### How to reproduce it (minimal and precise)

Upgrade to v1.23.0 and launch with `npm start`

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

**Comment by palnic59** [comment]
The same error here

**Comment by Koenkk** [comment]
Does this still happen after executing `npm ci` in the `/opt/zigbee2mqtt` directory?

**Comment by zmottie** [comment]
This is happening for me as well on Home Assistant.  There's no /opt/zigbee2mqtt but if you can point me towards HA specific troubleshooting I'm happy to help.

**Comment by palnic59** [comment]
Yesterday I have updated Zgbee2mqtt dev with
 git pull
 npm ci
npm start
and got this error
Everything was worked perfect before: Rpi4-Raspbee2-Domoticz

**Comment by EXP-Carthage** [comment]
I just tested by updating the local repository after the commit [0a46663](https://github.com/Koenkk/zigbee-herdsman-converters/commit/0a46663f6a8513527a8dc1ba7342178cc43b4921), and the console.log errors disappeared
