### ISSUE TITLE
Tuya SNTZ007 alternative name

### ISSUE THREAD

**Issue by mgmtotorsperformance** [Koenkk/zigbee2mqtt#11214]
### What happened?

The Tuya Zigbee contact sensor is available on compatible devices, but is not recognized.

Here it is  info:
Device type
: EndDevice
Zigbee Model : TS0601
Zigbee Manufacturer: _TZE200_fwoorn8y

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

20210708

### Adapter

 zStack3x0

**Comment by Upgreydd** [comment]
Have the same issue.
