### ISSUE TITLE
Broken link (another one ... sorry ;-) )

### ISSUE THREAD

**Issue by mchacher** [Koenkk/zigbee2mqtt#1122]
Hi,
another broken link detected in the FAQ (https://www.zigbee2mqtt.io/information/FAQ.html)
"you can even use another **CC2530/CC2531 as a router**". The link is broken.

I take the opportunity to ask you a question: if I connect a second USB CC2531 to my Raspberry, how do I enable the router once I have flashed the right firmware? Is the router automatically detected by the coordinator?

Thanks

**Comment by Koenkk** [comment]
Thanks fixed the link.

After flashing the CC2531 with the router firmware, just power it and set `permit_join: true` in `configuration.yaml`, the CC2531 will automatically join.
