### ISSUE TITLE
SmartThings IM6001-WLP01 water leak sensor stopped working after HA update

### ISSUE THREAD

**Issue by artohi** [Koenkk/zigbee2mqtt#11223]
### What happened?

I have two SmartThings IM6001-WLP01 water leak sensors. They have worked fine for a long time. Today I updated Home Assistant to the latest version 2022.2.1 and after that the water leak sensor says "water_leak" => N/A. Same thing with battery_low and tamper. Temperature, battery and linkquality are still working.

### What did you expect to happen?

Everything should work

### How to reproduce it (minimal and precise)

Update to the latest Home Assistant (2022.2.1)

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20220103

### Adapter

SONOFF ZigBEE 3.0 USB Dongle Plus

### Debug log

Received 09:26:48
QoS: 0
Payload: battery: 80
battery_low: null
linkquality: 65
tamper: null
temperature: 23.17
voltage: 2900
water_leak: null

**Comment by artohi** [comment]
<img width="420" alt="Screenshot 2022-02-04 at 13 53 51" src="https://user-images.githubusercontent.com/1082923/152524894-6a371138-0519-4798-b708-5d5127f8029b.png">

**Comment by Koenkk** [comment]
Try triggering it once

**Comment by artohi** [comment]
> 

That worked! Both sensors are now working. Thank you for the tip!
