### ISSUE TITLE
Failed test HomeAssistant extension

### ISSUE THREAD

**Issue by EXP-Carthage** [Koenkk/zigbee2mqtt#11243]
### What happened?

Test failure after the commit [`0a07b41`](https://github.com/Koenkk/zigbee-herdsman-converters/commit/0a07b418b4a13e5538dfbdc99040bfca6c2d5c8e).

![Screenshot_20220205_133252](https://user-images.githubusercontent.com/94924417/152642665-cd8f9dfe-fb76-47de-be17-89c2c2e5c1de.png)

### How to reproduce it (minimal and precise)

`npm test`

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
I cannot reproduce this locally with `npm tst`, also the CI on github actions succeeds so this looks to be something with your setup.

**Comment by EXP-Carthage** [comment]
Yes, this may be due to my system configuration.
Even though I have done a clean installation, I still have the same problem. In this case, I will close the issue.
Thanks anyway for taking the time to test ;)
