### ISSUE TITLE
[New device support]: Another Tuya Zigbee Temperature Humidity Sensor (modelID: 'TS0601', manufacturerName: '_TZE200_locansqn')

### ISSUE THREAD

**Issue by kalbfuss** [Koenkk/zigbee2mqtt#11246]
### Link

https://de.aliexpress.com/item/1005003004237625.html?gatewayAdapt=glo2deu&spm=a2g0s.12269583.0.0.c5b733c3vdYH8M

### Database entry

{"id":15,"type":"EndDevice","ieeeAddr":"0xa4c138ed08f17a94","nwkAddr":25419,"manufId":4417,"manufName":"_TZE200_locansqn","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�Y�)i�Y�)i�Y�)i�Y�)i�]�)i�]�)i�]�)i�]�)i�]�)i�]�)i�]�)iv^�)f","65506":49,"65508":0,"stackVersion":0,"dateCode":"","appVersion":67}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1644074002797,"useImplicitCheckin":true}

### Comments

I bought a Chinese Tuya Zigbee temperature and humidity sensor with display from AliExpress. The device was not automatically detected by zigbee2mqtt. Since it was claimed to be a Tuya device I checked in the sources of zigbee-herdsman-converters and attempted my luck with the entry for model TS0601_temperature_humidity_sensor, copying it into an external converter file and adapting the manufacturerName.

This worked out of the box. I am receiving temperature, humidity and battery data. The only minor disturbance are the following log entries, which indicate that the converter is not yet complete:

```
zigbee-herdsman-converters:maa_tuya_temp_sensor: NOT RECOGNIZED DP #20 with data {"seq":1024,"dp":20,"datatype":2,"fn":0,"data":{"type":"Buffer","data":[0,0,0,6]}}
debug Received Zigbee message from '0xa4c138ed08f17a94', type 'raw', cluster 'manuSpecificTuya', data '{"data":[9,78,36,5,0],"type":"Buffer"}' from endpoint 1 with groupID null
debug No converter available for 'TS0601_temperature_humidity_sensor' with cluster 'manuSpecificTuya' and type 'raw' and data '{"data":[9,78,36,5,0],"type":"Buffer"}'
```

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');


const definition = {
      fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_locansqn'}],
      model: 'TS0601_temperature_humidity_sensor',
      vendor: 'TuYa',
      description: 'Temperature and humidity sensor with display',
      fromZigbee: [fz.tuya_temperature_humidity_sensor],
      toZigbee: [],
      exposes: [e.temperature(), e.humidity(), e.battery()],
};

module.exports = definition;
```

**Comment by little-dgek** [comment]
Hm. I have zemismart tuya curtains (_TZE200_cf1sl3tj, TS0601). After this update - it is recognized as your sensor. Before this update - it wasn't recoznized at all.
