### ISSUE TITLE
Help on MQTT publish

### ISSUE THREAD

**Issue by goldriver2** [Koenkk/zigbee2mqtt#1125]
I am working at integrating a Stelpro baseboard thermostat in zigbe2mqtt, so far I have been able to pair the device. I figured out the FromZigee an To Zigbee and I have been able to see payload from the thermostat in my MQTT server

{"local_temperature":23,"linkquality":28,"occupied_heating_setpoint":24,"pi_heating_demand":0}

Where does the payload structure come from ? linkquality and pl_heating_demand are coming from ?
how can one get more info from the thermostat ? (tried the get but zigbe2mqtt crashes)

**Comment by carldebilly** [comment]
@goldriver2 You may be interested by this PR: https://github.com/Koenkk/zigbee2mqtt/pull/2628
