### ISSUE TITLE
Tuya TRV TS0601 firmware update fails

### ISSUE THREAD

**Issue by guidokieboom** [Koenkk/zigbee2mqtt#11252]
### What happened?

Firmware updates for TS0601 thermostat valve fail to complete.

### What did you expect to happen?

OTA firmware update would complete successfully

### How to reproduce it (minimal and precise)

In Z2M OTA section at first check for new firmware, then click on 'update device firmware'
<img width="1024" alt="Screenshot 2022-02-05 at 21 57 51" src="https://user-images.githubusercontent.com/65387179/152659121-228b782c-9ab8-49fc-8215-4d004790674e.png">

Tried again by force removing the TRV, then pairing again. Same result: firmware fails between 5-15% progress.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26580700

### Adapter

Conbee 2 USB stick with Z2M (no ZHA, no Deconz)

### Debug log

<img width="1006" alt="Screenshot 2022-02-05 at 21 58 38" src="https://user-images.githubusercontent.com/65387179/152659029-6f43b006-878b-436d-8cb6-30e75f5813b7.png">
<img width="1016" alt="Screenshot 2022-02-05 at 22 01 38" src="https://user-images.githubusercontent.com/65387179/152659031-50a69dfb-0275-4761-bb37-8910520f248b.png">
<img width="1009" alt="Screenshot 2022-02-05 at 22 02 55" src="https://user-images.githubusercontent.com/65387179/152659034-5c3736ba-2c3c-4f9d-967c-efd0d2de6585.png">

**Comment by guidokieboom** [comment]
noticed following in the Home Assistant supervisor log:
<img width="1000" alt="Screenshot 2022-02-05 at 22 22 14" src="https://user-images.githubusercontent.com/65387179/152659488-9f872426-689e-4d1c-b4b5-7cd9be2bb684.png">

**Comment by Lyr3x** [comment]
I thought too its not working, but check the OTA troubleshooting:
https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#troubleshooting

I removed the battery of my valves for a few seconds and updated successfully afterwards.

**Comment by guidokieboom** [comment]
Thanks Lyr3x for your suggestions. I tried this and unfortunately still no OTA.....Then I realized I recently changed my USB hub with an USB extension cable.... After re-using the USB hub (between Conbee2 and RPi4) my Z2M works like a charm again including successful OTA of the TRV.

**Comment by guidokieboom** [comment]
use USB hub between Conbee2 stick and Raspberry PI.

**Comment by KimHEF** [comment]
Is it possible to OTA-Update these TVRs (Tuya TS0601) with z2m and CC2531?
