### ISSUE TITLE
Failed to configure Tuya TS0121 Plug

### ISSUE THREAD

**Issue by quantummobile** [Koenkk/zigbee2mqtt#11274]
### What happened?

After removing Tuya smart plug TS0121 and pairing it again, power, current, voltage N/A.
After second attempt to pair current, voltage, linkqulity, power outage sensors became unavailable in Home Assistant.

### What did you expect to happen?

All sensors and values available after pairing.

### How to reproduce it (minimal and precise)

Remove device, pair device again.

### Zigbee2MQTT version

1.23.0-1 

### Adapter firmware version

20211217

### Adapter

Texas Instruments LAUNCHXL-CC1352P-2

### Debug log

`Info Device '0x60a423fffe61d11c' is supported, identified as: TuYa 10A UK or 16A EU smart plug (TS0121_plug)
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"10A UK or 16A EU smart plug","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Instantaneous measured power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":1,"description":"Instantaneous measured electrical current","name":"current","property":"current","type":"numeric","unit":"A"},{"access":1,"description":"Measured electrical potential value","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":1,"description":"Sum of consumed energy","name":"energy","property":"energy","type":"numeric","unit":"kWh"},{"access":3,"description":"Recover state after power outage","name":"power_outage_memory","property":"power_outage_memory","type":"enum","values":["on","off","restore"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0121_plug","options":[{"access":2,"description":"This device does not support reporting electric measurements so it is polled instead. The default poll interval is 60 seconds, set to -1 to disable.","name":"measurement_poll_interval","property":"measurement_poll_interval","type":"numeric","value_min":-1},{"access":2,"description":"Calibrates the power value (percentual offset), takes into effect on next report of device.","name":"power_calibration","property":"power_calibration","type":"numeric"},{"access":2,"description":"Calibrates the current value (percentual offset), takes into effect on next report of device.","name":"current_calibration","property":"current_calibration","type":"numeric"},{"access":2,"description":"Calibrates the voltage value (percentual offset), takes into effect on next report of device.","name":"voltage_calibration","property":"voltage_calibration","type":"numeric"}],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0x60a423fffe61d11c","ieee_address":"0x60a423fffe61d11c","status":"successful","supported":true},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"10A UK or 16A EU smart plug","friendly_name":"0x60a423fffe61d11c","model":"TS0121_plug","supported":true,"vendor":"TuYa"},"type":"pairing"}'
Info MQTT publish: topic 'zigbee2mqtt/0x60a423fffe61d11c', payload '{"current":null,"energy":null,"linkquality":87,"power":null,"power_outage_memory":null,"state":"OFF","voltage":null}'
Error Failed to configure '0x60a423fffe61d11c', attempt 3 (Error: Bind 0x60a423fffe61d11c/1 genOnOff from '0x00124b001ca1bc05/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))`

**Comment by raulmorales** [comment]
I have same problem. In my case, I have three TS0121_plug, one of this is configured ok.

Same version of firmware and Zigbee2MQTT. My adapter is SONOFF ZigBEE 3.0 USB Dongle Plus
