### ISSUE TITLE
Follow new supported devices 

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#1128]
Is there a way to follow newly added devices?

I sometimes look up this link to see if there are new devices again.
http://www.zigbee2mqtt.io/information/supported_devices.html

I’m always curious for that new devices, because maybe I want to have them too.

So is there a way to get a notification on that? RSS feed?

The only thing I can think of is watching the number of the supported devices with an automation.
But this would not point you to the new device, it would only tell you “hey one new device of 194, search for it”

**Comment by Koenkk** [comment]
New supported devices are added to the changelog: https://github.com/Koenkk/zigbee2mqtt/releases
