### ISSUE TITLE
[New device support]: Please add new manufacture for Tuya TS0504B RGBW

### ISSUE THREAD

**Issue by ellucasso** [Koenkk/zigbee2mqtt#11287]
### Link

https://a.aliexpress.com/_v5ofVy

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0xa4c1387da8fdd2b2","nwkAddr":57863,"manufId":4417,"manufName":"_TZ3210_i2i0bsnv","powerSource":"Mains (single phase)","modelId":"TS0504B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00212effff07e41c","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":91,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":821693351},"lastSeen":1644255670326,"defaultSendRequestWhen":"immediate"}

### Comments

Hello, Is it possible to update the tuya.js code for it to work?
Thanks

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
