### ISSUE TITLE
Could not open specified HEX file

### ISSUE THREAD

**Issue by eflemingtra** [Koenkk/zigbee2mqtt#113]
Hi,

Sorry, newbie here. When trying to flash my CC2531 via the SmartRF Flash Programmer, I get the error:

Could not open specified HEX file

![error](https://user-images.githubusercontent.com/13082155/41269399-585094e0-6e48-11e8-8544-53d9d522835b.png)

After this, the USB dongle green light goes out and I have to reinsert the dongle for it to reactivate.

When downloading the .hex file, all I am doing is right clicking and saving it. There's nothing else required, correct?  Windows device manager shows both the CC debugger and USB dongle drivers installed correctly.

**Comment by eflemingtra** [comment]
Fixed with alternate download options.

**Comment by joonhshin** [comment]
> Fixed with alternate download options.

I'm having the same issue. What alternate download options did you use?

**Comment by Koenkk** [comment]
Download from here: https://github.com/Koenkk/Z-Stack-firmware/tree/optimize/coordinator/CC2531/bin
