### ISSUE TITLE
Err - Develco Air quality sensor AQSZB-110

### ISSUE THREAD

**Issue by RitaSghe** [Koenkk/zigbee2mqtt#11301]
### What happened?

I try to modify interval min rep of air quality - temperature - humidity - but  the value don't change ...

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700 - 0x00212effff07359e - 0.6.71

### Adapter

Conbee II

### Debug log

error 2022-02-08 14:34:34: Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'Bind 0x0015bc00360010d6/38 develcoSpecificAirQuality from '0x00212effff07359e/1' failed (waiting for response TIMEOUT)'

**Comment by soend** [comment]
Having exact same problem here, i tried @sjorge suggestion wo keep clicking the button but it does not help.
