### ISSUE TITLE
UI does not scale correctly horizontally (no scroll bar either)

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#11302]
### What happened?

When opening the Zigbee2MQTT GUI in Home Assistant it seems to be unable to correctly scale on a vertical monitor setup. So the icons to manage an device are not visible and cannot be reached by scrolling right.

https://user-images.githubusercontent.com/614929/153011681-bf87c466-33c4-444e-9939-8e84738b9809.mp4

### What did you expect to happen?

A scroll bar should make it able to reach those hidden icons

### How to reproduce it (minimal and precise)

Use the Zigbee2MQTT GUI via a vertical monitor

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20201026

### Adapter

Slaesh's CC2652RB

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
