### ISSUE TITLE
Error reporting in MQTT message (enhancement)

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#1134]
This refers to the recent commit: https://github.com/Koenkk/zigbee2mqtt/commit/ec0ee53c7a1e69cbf66b09ad8d162ce527280966

Could you also log the following type of messages through MQTT? This would make my smart home aware that a device is not (yet) paired.

> error: Failed to find device with ieeAddr: '0x000a41fdda353163'

**Comment by Koenkk** [comment]
Merged.
