### ISSUE TITLE
Failed to perform OTA on IKEA E1744 SYMFONISK

### ISSUE THREAD

**Issue by tjxism** [Koenkk/zigbee2mqtt#11354]
### What happened?

I recently got an IKEA SYMFONISK (FW 2.1.024) remote and Z2M is reminding me an update is available. 
When I try updating it always aborts after about 5 mins. Log shows "Update of 'IKEA SYMFONISK Rotary Remote' failed (Update failed with reason: 'aborted by device')". Once it became idle and killed the battery overnight. 

Tried checking/unchecking IKEA TRADFRI test url, same behavior. 
Killed 3 new batteries for the update.

#using EZSP v8 cordinator provided by XGG (z2m.wiki)

Remote state:
{
    "battery": 100,
    "brightness": 255,
    "update": {
        "state": "available"
    },
    "update_available": true,
    "action": null,
    "device": {
        "applicationVersion": 33,
        "dateCode": "20190710",
        "friendlyName": "IKEA SYMFONISK Rotary Remote",
        "hardwareVersion": 1,
        "ieeeAddr": "0x5c0272fffe5bda5d",
        "manufacturerID": 4476,
        "manufacturerName": "IKEA of Sweden",
        "model": "E1744",
        "networkAddress": 35023,
        "powerSource": "Battery",
        "softwareBuildID": "2.1.024",
        "stackVersion": 98,
        "type": "EndDevice",
        "zclVersion": 3
    },
    "linkquality": 255,
    "action_rate": 195
}

### What did you expect to happen?

OTA to complete. 

### How to reproduce it (minimal and precise)

Pair E1744 with the coordinator;
Check OTA available;
Click Update, click remote to ensure the OTA starts.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

6.7.8.0 build 373

### Adapter

XGG efr32 wired adapter (new white model)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8047554/log.txt)

**Comment by Hedda** [comment]
> ### Adapter firmware version
> 6.7.8.0 build 373
> 
> ### Adapter
> XGG efr32 wired adapter (new white model)

Not sure if related but see EZSP discussions in https://github.com/Koenkk/zigbee-herdsman/issues/319 which mention that while Silicon Labs EmberZNet 6.7.8 firmware is minimum for EFR32 Zigbee chip it is recommended to update to newer Zigbee Coordinator firmware.

Firmware is normally updated with Elelabs EZSP Firmware Update Utility or the Zigbee firmware updater image by walthowd:

https://github.com/zigpy/zigpy/wiki/Coordinator-Firmware-Updates#recommended-firmware-version-for-ezsp-coordinators
https://github.com/Elelabs/elelabs-zigbee-ezsp-utility
https://github.com/walthowd/husbzb-firmware
https://github.com/grobasoz/zigbee-firmware/
https://github.com/xsp1989/zigbeeFirmware/
https://github.com/zha-ng/EZSP-Firmware

I have however not heard of "XGG efr32 wired adapter (new white model)" myself so not sure where to get compatible firmware.

If it does help with new Zigbee Coordinator firmware then might also want to mention this issue in https://github.com/Koenkk/zigbee-herdsman/issues/319
