### ISSUE TITLE
Missing package in package.json

### ISSUE THREAD

**Issue by Vincere1st** [Koenkk/zigbee2mqtt#11356]
### What happened?

Hello,
I'm working on nodejs project with an integration of your excellent project.
And i use typescript.
After clone your repository, i found an error (i'm pretty sure)
Here: https://github.com/Koenkk/zigbee2mqtt/blob/6ea61bae2cf441e15612dc68c257797fba46312b/lib/extension/bridge.ts#L5
This file wants to use winston-transport, but it is not installed.
I checked the package.json and it is not present.
My idea also confirms it to me.
And when I run pnpm it also gives me an error with others errors.
I think winston-transport should be added to package.json if still in use. And if I look at the code it is well used here:
Here: https://github.com/Koenkk/zigbee2mqtt/blob/6ea61bae2cf441e15612dc68c257797fba46312b/lib/extension/bridge.ts#L54

I can make a PR, but wich version, i think the last the 4.5.0 ?

### What did you expect to happen?

Add to package.json the winston-transport but wich version? The last 4.5.0?

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20201127

### Adapter

CC2531 Zigbee Usb key

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
