### ISSUE TITLE
[Feature request]: Need command "Write Attribute Response" in order support Livolo devices

### ISSUE THREAD

**Issue by systemiii** [Koenkk/zigbee2mqtt#11370]
### Is your feature request related to a problem? Please describe

Because of the ZCL malformed packets used by Livolo devices, command "Write Attribute Response" is needed in order to send leave/unpair packet to device, otherwise the device will try repeatedly to pair.

The packet is this
_ZigBee Cluster Library Frame, Mfr: Unknown (0x1ad2), Command: Write Attributes Response, Seq: 233_
7c d2 1a e9 **04** 06 92 42  3f 00 00 00 00 00 00 00

### Describe the solution you'd like

Implement an option (example writeResp) similar to writeUndiv for the method write of entity class, so I can use the following code in external converter

await entity.write('genPowerCfg', payloadUnpair,
      {
          manufacturerCode: 0x1ad2, disableDefaultResponse: true, disableResponse: true,
          reservedBits: 3, direction: 1, transactionSequenceNumber: 0xe9, **writeResp: true,**
      });

### Describe alternatives you've considered

No alternatives available i think

### Additional context

![image](https://user-images.githubusercontent.com/57064524/153677609-3a361ce3-62ae-4315-adee-bcfa3c9030e3.png)

**Comment by Koenkk** [comment]
Since the direction is the opposite of write/writeUndiv, this should be a new method similar to readResponse (https://github.com/Koenkk/zigbee-herdsman/blob/85cd71a7a1e400de9ec85af79375e48b66ed2b7f/src/controller/model/endpoint.ts#L447). Could you try to make an implementation?

**Comment by systemiii** [comment]
Sure, I'll try.
Thank you

**Comment by systemiii** [comment]
I opened the pull request
https://github.com/Koenkk/zigbee-herdsman/pull/501

**Comment by Gruffuss** [comment]
Hi! 

Is the a chance you could share the external convertor?
