### ISSUE TITLE
failed to join due to error: Unable to read genBasic, likely communication error

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#1137]
Hi friends,
I want to add a new device to zigbee2mqtt, but after some data exchange, finally I see "failed to join due to error: Unable to read genBasic, likely communication error" message and the joining procedure is not finished. what's the problem? should I provide a new application like cieApp?

**Comment by Koenkk** [comment]
I've never seen this error yet, can you provide the log?

**Comment by msadeghz** [comment]
OK
you can find it in attached file.
the device address is 0x00124b0018dd053d
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/2896680/log.txt)

**Comment by Koenkk** [comment]
What device are you trying to pair?

**Comment by msadeghz** [comment]
a temperature and humidity sensor which sends data repeatedly

**Comment by Koenkk** [comment]
Can you provide an url to the device?

**Comment by msadeghz** [comment]
[http://www.fbeeinside.com/zigbee-temperature-and-humidity-sensor-fzb870ath-s1-p00015p1.html](url)
the company says its zigbee profile is Standard HA 1.2. It seems that it can;t join and tries and tries to join

**Comment by Koenkk** [comment]
Did you keep the device awake while joining? (by continuously pressing a button on it?)

**Comment by msadeghz** [comment]
yes, the device doesn't need to be kept awake, it retries the join procedure automatically.

**Comment by msadeghz** [comment]
An abstract log!
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/2897778/log.txt)

**Comment by Koenkk** [comment]
This device doesn't seem to be zigbee HA compliant, otherwise it would allow reading of the `genBasic` cluster. With what bridge is this device normally used?

**Comment by msadeghz** [comment]
I think I found the problem
I use a zigbee sniffer. the ZNP wants to read genBasic attribute but the device responds the command is not supported.
so the zigbee2mqtt sends leave command to the device

![image](https://user-images.githubusercontent.com/22853649/53299585-77819c00-3851-11e9-862e-e9c9e0143213.png)

**Comment by msadeghz** [comment]
I flashed the ZNP by z-stack 3, which wants the forked zigbee-shepherd. the data request command used for fined the modelID and ... in the forked version is different from default version of zigbee shepherd.

the default zigbee-shepherd command (uses read attribute command)
[default.txt](https://github.com/Koenkk/zigbee2mqtt/files/2897983/default.txt)

the forked version (uses discover attribute command)
[forked.txt](https://github.com/Koenkk/zigbee2mqtt/files/2897984/forked.txt)
