### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by NightFalcon650** [Koenkk/zigbee2mqtt#11390]
### Is your feature request related to a problem? Please describe

Hue entertainment and syncing on spotify music doesnt work with gledopto gu10 bulbs. Does anybody tried to flash hue firmware on gledopto bulbs or change the firmware so the hue bridge recognizes them as hue gu10 bulbs?

### Describe the solution you'd like

Sollution 1: Gledopto gu10 bulbs being recognized by hue bridge as hue gu10 bulbs.
Sollution 2: Possibility to flash hue firmware on gledopto bulb

### Describe alternatives you've considered

Changing the essential variables in the gledopto firmware so they are recognize as hue bulbs in the hue bridge.

### Additional context

The gledopto bulbs have pin connectors on the circuit what looks like seriële (flashing) points.

**Comment by Koenkk** [comment]
I don't see how this is related to z2m, closing.
