### ISSUE TITLE
[New device support]: Hue Runner 2

### ISSUE THREAD

**Issue by yorickri** [Koenkk/zigbee2mqtt#11409]
### Link

https://www.philips-hue.com/nl-be/p/hue-white-ambiance-runner-2-licht-spotbalk/8719514338166

### Database entry

{"id":36,"type":"Router","ieeeAddr":"0x001788010bca08f4","nwkAddr":7072,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003045701_01","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1644781043921,"defaultSendRequestWhen":"immediate"}

### Comments

Looks to be the exact same as 5309230P6, which is already supported by Zigbee2MQTT

### External converter
`const { toZigbeeConverters: tz, fromZigbeeConverters: fz, exposes } = require('zigbee-herdsman-converters');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

// Copied from zigbee-herdsman-converters/devices/philips.js with no modifications
const hueExtend = {
  light_onoff_brightness: (options = {}) => ({
    ...extend.light_onoff_brightness(options),
    toZigbee: extend.light_onoff_brightness(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_colortemp: (options = {}) => ({
    ...extend.light_onoff_brightness_colortemp(options),
    toZigbee: extend.light_onoff_brightness_colortemp(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_color: (options = {}) => ({
    ...extend.light_onoff_brightness_color({ supportsHS: true, ...options }),
    toZigbee: extend.light_onoff_brightness_color({ supportsHS: true, ...options }).toZigbee
      .concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_colortemp_color: (options = {}) => ({
    ...extend.light_onoff_brightness_colortemp_color({ supportsHS: true, ...options }),
    toZigbee: extend.light_onoff_brightness_colortemp_color({ supportsHS: true, ...options })
      .toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
};

module.exports = [{
  zigbeeModel: ['929003045701_01', '929003045701_02'],
  model: '929003045701_01',
  vendor: 'Philips',
  description: 'Hue White ambiance Runner double spotlight',
  meta: { turnsOffAtBrightness1: true },
  extend: hueExtend.light_onoff_brightness_colortemp_color({ colorTempRange: [153, 500] }),
  ota: ota.zigbeeOTA,
}];`

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
