### ISSUE TITLE
Cover group of Zigbee motors show error 'TypeError: Cannot read property 'manufacturerName' of null' when trying to OPEN/CLOSE

### ISSUE THREAD

**Issue by rrlevy** [Koenkk/zigbee2mqtt#11405]
### What happened?

I created a group in Zigbee2MQTT for a few Covers (roller blind motor).
The devices are all of the same kind: a Zemismart tubular motor. https://www.zigbee2mqtt.io/devices/TS0601_cover.html

After adding the group, it shows in Home Assistant, but when trying to OPEN/CLOSE it, I get only the following error in Zigbee2MQTT log:

```
Error Publish 'set' 'state' to 'Cortinas Canto' failed: 'TypeError: Cannot read property 'manufacturerName' of null'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Cortinas Canto' failed: 'TypeError: Cannot read property 'manufacturerName' of null'","meta":{"friendly_name":"Cortinas Canto"},"type":"zigbee_publish_error"}'
```

No other log is shown

### What did you expect to happen?

Covers would open/close as commanded

### How to reproduce it (minimal and precise)

1) Adding the following group in Zigbee2MQTT (I added using the web interface, and copied below the resulting groups.yaml:

```
'5':
  friendly_name: Cortinas Canto
  devices:
    - 0xcc86ecfffexxxxxx/1
    - 0x847127fffexxxxxx/1
    - 0x5c0272fffexxxxxx/1
    - 0x0c4314fffexxxxxx/1
```

2) Going to Home assistant entities list, and trying to command the new entity shown to OPEN/CLOSE

### Zigbee2MQTT version

 1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

info  2022-02-13 13:10:02: Adding 'Cortina 4' to 'Cortinas Canto'
info  2022-02-13 13:10:03: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Cortina 4","group":"Cortinas Canto"},"type":"device_group_add"}'
info  2022-02-13 13:10:03: MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0xcc86ecfffexxxxxx/1","group":"Cortinas Canto"},"status":"ok","transaction":"4mrrd-12"}'
info  2022-02-13 13:10:03: MQTT publish: topic 'homeassistant/cover/1221051039810110150109113116116_5/cover/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Cortinas Canto/set","device":{"identifiers":["zigbee2mqtt_1221051039810110150109113116116_5"],"name":"Cortinas Canto","sw_version":"Zigbee2MQTT 1.23.0"},"json_attributes_topic":"zigbee2mqtt/Cortinas Canto","name":"Cortinas Canto","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Cortinas Canto","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Cortinas Canto/set","unique_id":"5_cover_zigbee2mqtt"}'
info  2022-02-13 13:10:03: MQTT publish: topic 'zigbee2mqtt/Abajur Sofá Sala de Estar', payload '{"current":0,"energy":0.22,"linkquality":255,"power":0,"power_outage_memory":"restore","state":"OFF","voltage":130}'
info  2022-02-13 13:10:05: Adding 'Cortina 5' to 'Cortinas Canto'
info  2022-02-13 13:10:05: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Cortina 5","group":"Cortinas Canto"},"type":"device_group_add"}'
info  2022-02-13 13:10:05: MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x847127fffexxxxxx/1","group":"Cortinas Canto"},"status":"ok","transaction":"4mrrd-13"}'
info  2022-02-13 13:10:05: MQTT publish: topic 'homeassistant/cover/1221051039810110150109113116116_5/cover/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Cortinas Canto/set","device":{"identifiers":["zigbee2mqtt_1221051039810110150109113116116_5"],"name":"Cortinas Canto","sw_version":"Zigbee2MQTT 1.23.0"},"json_attributes_topic":"zigbee2mqtt/Cortinas Canto","name":"Cortinas Canto","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Cortinas Canto","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Cortinas Canto/set","unique_id":"5_cover_zigbee2mqtt"}'
info  2022-02-13 13:10:07: Adding 'Cortina 6' to 'Cortinas Canto'
info  2022-02-13 13:10:07: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Cortina 6","group":"Cortinas Canto"},"type":"device_group_add"}'
info  2022-02-13 13:10:07: MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x5c0272fffexxxxxx/1","group":"Cortinas Canto"},"status":"ok","transaction":"4mrrd-14"}'
info  2022-02-13 13:10:08: MQTT publish: topic 'homeassistant/cover/1221051039810110150109113116116_5/cover/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Cortinas Canto/set","device":{"identifiers":["zigbee2mqtt_1221051039810110150109113116116_5"],"name":"Cortinas Canto","sw_version":"Zigbee2MQTT 1.23.0"},"json_attributes_topic":"zigbee2mqtt/Cortinas Canto","name":"Cortinas Canto","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Cortinas Canto","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Cortinas Canto/set","unique_id":"5_cover_zigbee2mqtt"}'
info  2022-02-13 13:10:10: Adding 'Cortina 7' to 'Cortinas Canto'
info  2022-02-13 13:10:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Cortina 7","group":"Cortinas Canto"},"type":"device_group_add"}'
info  2022-02-13 13:10:10: MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x0c4314fffxxxxxx/1","group":"Cortinas Canto"},"status":"ok","transaction":"4mrrd-15"}'
info  2022-02-13 13:10:10: MQTT publish: topic 'homeassistant/cover/1221051039810110150109113116116_5/cover/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/Cortinas Canto/set","device":{"identifiers":["zigbee2mqtt_1221051039810110150109113116116_5"],"name":"Cortinas Canto","sw_version":"Zigbee2MQTT 1.23.0"},"json_attributes_topic":"zigbee2mqtt/Cortinas Canto","name":"Cortinas Canto","position_template":"{{ value_json.position }}","position_topic":"zigbee2mqtt/Cortinas Canto","set_position_template":"{ \"position\": {{ position }} }","set_position_topic":"zigbee2mqtt/Cortinas Canto/set","unique_id":"5_cover_zigbee2mqtt"}'
error 2022-02-13 13:10:42: Publish 'set' 'state' to 'Cortinas Canto' failed: 'TypeError: Cannot read property 'manufacturerName' of null'
info  2022-02-13 13:10:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Cortinas Canto' failed: 'TypeError: Cannot read property 'manufacturerName' of null'","meta":{"friendly_name":"Cortinas Canto"},"type":"zigbee_publish_error"}'

**Comment by rrlevy** [comment]
Haven't anyone had any similar issues?

Are cover groups supported or not?

**Comment by zhufeng88** [comment]
> 

maybe you can rewrite tuya_cover_control, this function is use 'meta.device.manufacturerName' this attr,but group is not have this attr, i think use like this ,i testing is right to use now.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/98304762/161210187-b1fe21c0-e502-4de1-bf13-89fc096e45f3.png">

**Comment by rrlevy** [comment]
@zhufeng88 Have you done a pull request for this fix at zigbee-herdsman-converters already?

> > 
> 
> maybe you can rewrite tuya_cover_control, this function is use 'meta.device.manufacturerName' this attr,but group is not have this attr, i think use like this ,i testing is right to use now.
>
