### ISSUE TITLE
Zen Thermostat not exposing occupied cooling setpoint 

### ISSUE THREAD

**Issue by spicyguap** [Koenkk/zigbee2mqtt#11425]
### What happened?

I got the thermostat paired but can only control the heating setpoint. 

### What did you expect to happen?

The ability to control the cooling set point 

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20211217

### Adapter

zStack3x0

**Comment by spicyguap** [comment]
Any insight here?

**Comment by Bomberski** [comment]
Works fine on zha
