### ISSUE TITLE
Nyce motion sensor NCZ-3043-HA battery level incorrect, and temperature/humidity not updating

### ISSUE THREAD

**Issue by 35gh** [Koenkk/zigbee2mqtt#11422]
### What happened?

The [Nyce motion sensor NCZ-3043-HA](https://www.zigbee2mqtt.io/devices/NCZ-3043-HA.html#nyce-ncz-3043-ha) is properly detected by v1.23.0. There are however several problems:

1. Battery level is incorrectly reported (142% in the example below)
```
{
    "battery": 142,
    "battery_low": false,
    "humidity": 44,
    "linkquality": 255,
    "occupancy": false,
    "tamper": false,
    "temperature": 22.9,
    "voltage": 2700
}
```

2. Temperature and humidity are not updating. However they do when the sensor is manually queried.
Before query: see above
After manual query:
`Read result of 'msTemperatureMeasurement': {"measuredValue":2220}`
`Read result of 'msRelativeHumidity': {"measuredValue":3800}`

```
{
    "battery": 142,
    "battery_low": false,
    "humidity": 38,
    "linkquality": 255,
    "occupancy": false,
    "tamper": false,
    "temperature": 22.2,
    "voltage": 2700
}
```

3. Picture is wrong
Current picture is from wall sensor [NCZ-3041-HA](https://www.nycesensors.com/product/motion-sensor)
![NCZ-3043-HA](https://user-images.githubusercontent.com/90415090/153916991-c896a53e-0732-4b83-a4a9-06feb6d4e428.jpg)

while the [NCZ-3043-HA](https://www.nycesensors.com/product/ceiling-motion-sensor) is ceiling mounted:
<img width="343" alt="Capture d’écran 2022-02-14 à 18 39 25" src="https://user-images.githubusercontent.com/90415090/153917093-8ee6dbfa-209d-4cd0-ba33-ec5910a28035.png">

Note: motion detection works properly
Note 2: battery, humidity and temperature are correctly reported and updating when using DeconZ

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26660700

### Adapter

Conbee II

**Comment by 35gh** [comment]
Thanks! Battery seems OK now, but temperature/humidity (and I believe tamper as well) are still not updating.

```
{
    "battery": 70,
    "battery_low": false,
    "humidity": 41,
    "linkquality": 255,
    "occupancy": false,
    "tamper": false,
    "temperature": 23.3,
    "voltage": 2700
}
```

Tried to remove and re-add device as well.

Note: I see the following error in logs:  Failed to configure 'Sensor name', attempt 3 (ReferenceError: overides is not defined at Object.configure (/opt/zigbee2mqtt/dist/util/externally-loaded.js:22:47) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13))

**Comment by 35gh** [comment]
Update 2: now temperature and humidity are updating about every 2 hours.

**Comment by Koenkk** [comment]
Made a mistake in the external converter which gives you the failed to configure error, try with:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['3043'],
    model: 'NCZ-3043-HA',
    vendor: 'Nyce',
    description: 'Ceiling motion sensor CUSTOM',
    fromZigbee: [fz.occupancy, fz.humidity, fz.temperature, fz.ignore_basic_report, fz.ignore_genIdentify, fz.ignore_poll_ctrl,
        fz.battery, fz.ignore_iaszone_report, fz.ias_occupancy_alarm_2],
    toZigbee: [],
    exposes: [e.occupancy(), e.humidity(), e.temperature(), e.battery(), e.battery_low(), e.tamper()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'msTemperatureMeasurement', 'msRelativeHumidity']);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.temperature(endpoint);
        await reporting.humidity(endpoint);
    },
};

module.exports = definition;
```

After this configure the device via the z2m frontend -> device page -> yellow refresh button (make sure to wakeup the device right before clicking the button)

**Comment by 35gh** [comment]
Thank you! Device configuration works now, but temperature/humidity still don't update until I query the clusters manually.

**Comment by Koenkk** [comment]
So it says configured successfully? Can you wait a few more hours and see if it works after that?

**Comment by 35gh** [comment]
Sensor still updates temperature/humidity every 2 hours only...
![temp](https://user-images.githubusercontent.com/90415090/154161952-c9d3ff0e-8401-419b-8bcf-b566f1d73a5d.png)
.

**Comment by Koenkk** [comment]
Then I expect this sensor does not support change the report interval.

**Comment by 35gh** [comment]
Well my point is that this sensor was working perfectly when using DeconZ (reporting temp/humifidty as they change), while with Zigbee2mqtt I only get updates every 2 hours.

**Comment by Koenkk** [comment]
Interesting, could you play with the configure reporting option in the frontend? In the frontend -> click on your device -> reporting, try e.g. setting the min rep change to 0 and min rep interval to 1. Before pressing apply make sure to wakeup the device.

**Comment by 35gh** [comment]
It works thanks! I used Min rep interval=20 for humidity, and Min rep interval=60 for temperature, Min rep change=0 for both.

This sensor has a 0.1°C precision for temperature. Is it possible to report temperature changes every 0.5°C? Min rep change does not seem to have any effect.

<img width="1370" alt="temp" src="https://user-images.githubusercontent.com/90415090/154574442-d22e7b0a-5637-4b3c-b279-65c2da3df497.png">
