### ISSUE TITLE
[Feature request]: Include a Device Name and TimeStamp in the message payload.

### ISSUE THREAD

**Issue by nothingmn** [Koenkk/zigbee2mqtt#11446]
### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

I would like to see two additional properties added to the JSON payload sent to MQTT.  

DeviceName
- Right now im parsing the topic to get the device name, but I would rather skip that step and just have it provided.
 
Timestamp
- In UTC / ISO 8601 Format
- Or just time since epoc, in milliseconds precision, in UTC

The primary scenario is to avoid any pre-processing of the prior to storage or event triggering...

### Describe alternatives you've considered

Right now I pre-process all incoming data and then republish it for my primary workflows.  

### Additional context

None.

**Comment by sjorge** [comment]
You can configure advanced -> last_seen or advanced -> elapsed to get the timestamp you want:
https://www.zigbee2mqtt.io/guide/configuration/mqtt.html#server-connection

**Comment by nothingmn** [comment]
Thanks @sjorge 

I also noticed there is a flag in the UI to send "Device Information" as well.  That solves both of my questions

Great project.  Love it.
