### ISSUE TITLE
Options cannot be set in the configure_reporting

### ISSUE THREAD

**Issue by wb-adegtyarev** [Koenkk/zigbee2mqtt#11442]
### What happened?

Hi, please help me.

I send to the topic `zigbee2mqtt/bridge/request/device/configure_reporting`:
```
{
  "id": "0x842e14fffe8b184e/1",
  "options": {"manufacturerCode":26214},
  "cluster": "msOccupancySensing",
  "attribute": "sprutOccupancyLevel",
  "minimum_report_interval": 5,
  "maximum_report_interval": 10,
  "reportable_change": 10
}
```
But the manufacturerCode option is not passed and in response it writes that the attribute is not supported.

### What did you expect to happen?

I was expecting the attribute to be found based on the manufacturer's code.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20211115

### Adapter

CC2530

### Debug log
```
Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x842e14fffe8b184e/1 msOccupancySensing([{"attribute":"sprutOccupancyLevel","minimumReportInterval":10,"maximumReportInterval":15,"reportableChange":10}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

**Comment by Koenkk** [comment]
Added this now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by wb-adegtyarev** [comment]
> Added this now.

Thanks, I'll test. Tell me more, what should I do to add clusters of my device to the report settings?
![zigbee2mqtt-settings](https://user-images.githubusercontent.com/77433258/154538544-c62b2c3b-d65a-4d30-81e5-3ec13480d9eb.png)

**Comment by Koenkk** [comment]
I believe the frontend doesn't support clusters via ID (number), only the ones in https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts so this would be a feature request for https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by wb-adegtyarev** [comment]
> I believe the frontend doesn't support clusters via ID (number), only the ones in https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts so this would be a feature request for https://github.com/nurikk/zigbee2mqtt-frontend/issues
Hi.
The clusters and attributes of my device are described in cluster.ts. I expected them to be added to the frontend automatically, but they didn't.

The options in the configure_reporting work, thanks.

![изображение](https://user-images.githubusercontent.com/77433258/154913207-b78b2277-8b91-4609-9d5f-5685c8b7159a.png)
![изображение](https://user-images.githubusercontent.com/77433258/154913262-2ed902a0-c6e2-4c4f-b0e4-f725ba7369ea.png)

**Comment by Koenkk** [comment]
@wb-adegtyarev regarding the clusters please create an issue here: https://github.com/nurikk/zigbee2mqtt-frontend/issues

Since the options are working now I will close this.
