### ISSUE TITLE
Develco energy meter, some readings changed from float to int

### ISSUE THREAD

**Issue by mikke49** [Koenkk/zigbee2mqtt#11463]
### What happened?

After update to verison 1.23.0 the volt and current readings on phases B and C lost fractional digits, i.e. is reported as int instead of float. Volt and current on phase A remain as expected with fractional digits.

I'm using the Develco HAN dongle for Norwegian energy meters.

Cluster as viewed in deConz application shows correct values:
![image](https://user-images.githubusercontent.com/35665809/154491375-d95b8855-2f01-471c-9c26-b82c60b7b992.png)

Z2M trucates/rounds values for phases B and C:
![image](https://user-images.githubusercontent.com/35665809/154491503-a68051c9-d82f-4699-b6f5-93e05c6edd62.png)

### What did you expect to happen?

Volt and current readings for all three phases reported as floats.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26580700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
Should be fixed now, please confirm.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mikke49** [comment]
On vacation, will check as soon as back home later this week. Thanks.

**Comment by mikke49** [comment]
Tested now, everything seems ok. The voltage and current readings on phases B and C are reverted to floats.
