### ISSUE TITLE
When to update the Coordinator firmware?

### ISSUE THREAD

**Issue by naitsimp** [Koenkk/zigbee2mqtt#1146]
I am currently running `Coordinator firmware version: '20180815'`.

When is it necessary to upgrade to a newer firmware?
Do I have to repair every device if I upgrade, or is there a way to save the paired devices before upgrading?

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/information/what_does_and_doesnt_require_repairing.md
