### ISSUE TITLE
Zigbee 3.0 dual USB wireless socket plug incorrectly identified

### ISSUE THREAD

**Issue by NeuerUser** [Koenkk/zigbee2mqtt#11460]
### What happened?

Added the following device to z2m:
https://www.zigbee2mqtt.io/devices/ZP-LZ-FR2U.html
The interview works wirthout problems, but the device gets recognized as a different plug:
https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3

Zigbee model: TS011F  ( _TZ3000_2xlvlnez)

The effect is that the endpoint for the USB outlets is missing and instead it tries to show power metering values that the device is not reporting.

### What did you expect to happen?

To get it recognized as the correct device.

### Zigbee2MQTT version

1.23.0-dev commit: f284a5d

### Adapter firmware version

20211219

### Adapter

zStack3x0 zigStarGW

**Comment by NeuerUser** [comment]
Could be the same problem as here: https://github.com/Koenkk/zigbee2mqtt/issues/10812
Except mine has a CH plug type and a different manufacturerName.

**Comment by NeuerUser** [comment]
Yes, it is this device (except with a Swiss plug). I got it working with an external converter, using the one listed in #10812 with an adapted manufacturerName.
I commented in this issue.
Interesting side node is that the device also supports "child lock/unlock", which worked when it was incorrectly identified as the Tuya plug, but it's not included in the external converter for the Moe's plug.

**Comment by Koenkk** [comment]
@jzmudzinski can you confirm?

**Comment by jzmudzinski** [comment]
Yes, I confirm. That is the device. Sorry for any inconvenience my commit caused.

**Comment by Koenkk** [comment]
@jzmudzinski thanks,

Fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by NeuerUser** [comment]
Confirmed. Working correctly now. Thanks!

**Comment by sliwma** [comment]
Affirmative, work now. And, besides "child lock", LED state select is missing - it also worked.

**Comment by Barrysv** [comment]
@sliwma Hi there - are you saying there is a way to turn off the power LED via MQTT? Is that what you mean by "LED state select"? If so that would be great - what is the topic/command?  Cheers
