### ISSUE TITLE
Xiaomi Aqara Door Sensor P1 MCCGQ13LM reporting contact state "null" when paired with Sonoff Zigbee 3.0 dongle

### ISSUE THREAD

**Issue by tjxism** [Koenkk/zigbee2mqtt#11462]
### What happened?

Xiaomi Aqara Door Sensor P1 MCCGQ13LM successfully paired through the Sonoff Zigbee 3.0 dongle (coordinator), but the contact state is always Null. Repair doesn't fix the issue. 

While paired with Silicon Labs EZSP v8 adapter as the coordinator, the reporting is responsive and correct.

### What did you expect to happen?

Correctly expose contact state. 

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee 3.0 dongle

**Comment by Dragonlord2005** [comment]
I have the same Problem: 

**What did you expect to happen?**
Correctly expose contact state.

**How to reproduce it (minimal and precise)**
No response

**Zigbee2MQTT version**
1.23.0-1

**Adapter firmware version**
0x26720700

**Adapter**
Conbee 2

**Debug log**
No response

{
"battery": 100,
"gas": false,
"gas_sensitivity": "10%LEL",
"linkquality": 255,
"monitoring_mode": "left_right",
"state": "ON",
"temperature": 25,
"voltage": 3327,
"contact": null
}
