### ISSUE TITLE
Hue wall switch module cant change device_mode

### ISSUE THREAD

**Issue by JunkStar2k** [Koenkk/zigbee2mqtt#11477]
### What happened?

Wanted to change "device_mode" for my Hue Wall Switch Module from "single_rocker" to "dual_push_button" and it failed. I have tried moving it closer to the coordinator but with no luck

https://www.zigbee2mqtt.io/devices/929003017102.html#philips-929003017102

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26660700

### Adapter

ConBee2/RaspBee2

### Debug log

debug Received MQTT message on 'zigbee2mqtt/Hue wall switch module 3/set' with data '{"device_mode":"dual_push_button"}'

debug Publishing 'set' 'device_mode' to 'Hue wall switch module 3'

error Publish 'set' 'device_mode' to 'Hue wall switch module 3' failed: 'Error: Write 0x001788010b0295cf/1 genBasic({"52":{"value":3,"type":48}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4107,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'

info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'device_mode' to 'Hue wall switch module 3' failed: 'Error: Write 0x001788010b0295cf/1 genBasic({\"52\":{\"value\":3,\"type\":48}}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4107,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"Hue wall switch module 3"},"type":"zigbee_publish_error"}'

**Comment by Chriz-123** [comment]
have same issue cant change device_mode

**Comment by JunkStar2k** [comment]
Issue still there on version 1.24

**Comment by dansanders** [comment]
I also have this issue with version 1.27.2-1.
