### ISSUE TITLE
Battery reporting TS0201 broken

### ISSUE THREAD

**Issue by eloo** [Koenkk/zigbee2mqtt#11470]
### What happened?

It seems that the battery reporting of the TS0201 seems to be broken.
It is reporting most of the time 100% but then drops every 4h to the real value. 

![image](https://user-images.githubusercontent.com/2631895/154566778-4ebfa717-0d5e-4599-8569-ba06b8619c1b.png)

Maybe the device is not reporting the battery time and them zigbee2mqtt is setting it to 100%?

I see this behaviour for all my 4 devices

### What did you expect to happen?

That the battery value is not jumping back to 100% every time.

### How to reproduce it (minimal and precise)

Bind a TS0201 and check battery reporting

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
Could you provide the debug log when 100% is reported?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by Koenkk** [comment]
This looks like a bug in the device itself, I expect you see the same behaviour when pairing it with the TuYa gateway

Here you see the device sends `"batteryPercentageRemaining":60` (you have to divide this value by 2 to get the %)

```
Zigbee2MQTT:debug 2022-02-19 00:07:38: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":60,"batteryVoltage":25}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2022-02-19 00:07:38: MQTT publish: topic 'zigbee2mqtt/TS0201 - 4', payload '{"battery":30,"humidity":43.5,"last_seen":1645225658535,"linkquality":255,"temperature":23.8,"voltage":2500}'
```

And here it sends `"batteryPercentageRemaining":200` (= 100%)

```
Zigbee2MQTT:debug 2022-02-19 00:19:17: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":25}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2022-02-19 00:19:17: MQTT publish: topic 'zigbee2mqtt/TS0201 - 4', payload '{"battery":100,"humidity":42.5,"last_seen":1645226357913,"linkquality":255,"temperature":23.8,"voltage":2500}'
```

**Comment by eloo** [comment]
Okay.. really weird

Maybe we can add a mitigation? 
Like drop all 200(100%) values? 
Or that the battery voltage compared to percentage makes sense.. 
Maybe if battery voltage is below is below 30 or 28 (I can check what is reported with brand new batteries) and the percentage is 100% then it's dropped?

What do you think? 
Maybe this could be a small config option in z2m?

**Comment by Koenkk** [comment]
> Like drop all 200(100%) values?

But what to report when battery is 100%? That would mean if you insert new batteries the old value is kept which doesn't make sense

**Comment by eloo** [comment]
Thats why i mentioned maybe we need to check the voltage as wel.. 
e.g.

{"batteryPercentageRemaining":200,"batteryVoltage":25}  -> drop
{"batteryPercentageRemaining":120,"batteryVoltage":25}  -> keep
{"batteryPercentageRemaining":200,"batteryVoltage":30}  -> keep

the idea is that the percentage can only be 100(200) if the voltage is also over a specific value. 
but first we need to check what this threshold could be. sadly i don't have any new batteries here right now. 

what do you think?

**Comment by Koenkk** [comment]
We can do that indeed, but could you first check what voltage is reported with new batteries?

**Comment by eloo** [comment]
yes of course.
i will feedback as soon as have new batteries here :+1:

**Comment by johare279** [comment]
Hi - I am probably jumping in where I am not wanted, but I have a temperature and humidity sensor identifying as a TS0201 and I am getting null vales in the log for both battery and voltage. It is probably a cheap clone I have, but the battery was reporting back on ZHA (recently changed to zigbee2mqtt as got now coordinator). Do you know if there is any way to get the battery to show up? - not sure about voltage - or was zha just showing battery as 100% as it didn't have a value?
MQTT publish: topic 'zigbee2mqtt/Ensuite Temp Humid', payload '{"battery":null,"humidity":64.03,"linkquality":160,"temperature":22.7,"voltage":null}'
![temp humid](https://user-images.githubusercontent.com/60519583/155015013-b79394b9-64b9-4173-8e67-e6ad7d7273a1.jpg)

**Comment by eloo** [comment]
@Koenkk 

here is a short debug log with brand new energizer batteries:

```
Zigbee2MQTT:debug 2022-02-24 20:12:41: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 20:12:43: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":30}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 20:27:52: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 20:58:20: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 21:13:33: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 21:28:48: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 21:44:01: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 22:14:30: Received Zigbee message from 'TS0201 - 4', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID null
```

and we can see that the battery voltage is 31 or 30 with percentage 200
but for now this reporting is not running more than 4h (the already know real battery reporting window)
i will observe it over the night as well

**Comment by eloo** [comment]
and here is an example with new rechargeable batteries (eneloop)

```
Zigbee2MQTT:debug 2022-02-24 22:09:59: Received Zigbee message from 'TS0201 - 3', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":23}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 22:24:52: Received Zigbee message from 'TS0201 - 3', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":23}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 22:29:16: Received Zigbee message from 'TS0201 - 3', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":27}' from endpoint 1 with groupID null
Zigbee2MQTT:debug 2022-02-24 22:29:18: Received Zigbee message from 'TS0201 - 3', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":160,"batteryVoltage":27}' from endpoint 1 with groupID null
```

**Comment by eloo** [comment]
@Koenkk okay i see the same values over the night.
so the already mentioned values seems to be correct.
so maybe everything below voltage 30 is not a valid percentage of 200?

**Comment by Koenkk** [comment]
@eloo so what logic do you propose?

**Comment by eloo** [comment]
Hmmm maybe a good starter would be to drop 200 percentage values if voltage is below 30?

**Comment by Koenkk** [comment]
Done now, messsages with batteryVoltage < 30 will be ignored.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by eloo** [comment]
Awesome.
Will give it a try the next days

**Comment by gradvis** [comment]
> Hi - I am probably jumping in where I am not wanted, but I have a temperature and humidity sensor identifying as a TS0201 and I am getting null vales in the log for both battery and voltage. It is probably a cheap clone I have, but the battery was reporting back on ZHA (recently changed to zigbee2mqtt as got now coordinator). Do you know if there is any way to get the battery to show up? - not sure about voltage - or was zha just showing battery as 100% as it didn't have a value? MQTT publish: topic 'zigbee2mqtt/Ensuite Temp Humid', payload '{"battery":null,"humidity":64.03,"linkquality":160,"temperature":22.7,"voltage":null}' ![temp humid](https://user-images.githubusercontent.com/60519583/155015013-b79394b9-64b9-4173-8e67-e6ad7d7273a1.jpg)

Have the same issue.

Additionally:  _TZ3000_fllyghyj - sensor **without display** detected as TS0201 _TZ2000_a476raq2 sensor **with display**

**Comment by johare279** [comment]
I got the battery to report by clicking the button at back. 1 short click. But still no voltage. Though, battery is all I wanted.

**Comment by eloo** [comment]
@Koenkk 
Hi i have tested your dev build but it seems that now no battery reporting is working anymore.
Related to the code this is clear because this line:
```
            if (msg.data.batteryVoltage < 30) return;
```
will drop mostly everthing.

The condition here needs to check also the batteryPercentage as well.

e.g. 
```
            if (msg.data.batteryPercentageRemaining == 200 &&  msg.data.batteryVoltage < 30) return;
```

because the idea is only to drop the message if the batteryPercentage does not fit to the voltage

**Comment by Koenkk** [comment]
@eloo done.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by eloo** [comment]
@Koenkk 

```
Zigbee2MQTT:debug 2022-03-06 20:34:16: Received Zigbee message from 'TS0201 - 3', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":25}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2022-03-06 20:34:16: MQTT publish: topic 'zigbee2mqtt/TS0201 - 3', payload '{"battery":30,"humidity":37.2,"last_seen":1646595256150,"linkquality":255,"temperature":25,"voltage":2500}
```

![image](https://user-images.githubusercontent.com/2631895/156939313-969beba8-405c-4fbb-8fdd-b25ded60c576.png)

looks good so far :+1:
