### ISSUE TITLE
Unable to bind TS0001's ?

### ISSUE THREAD

**Issue by mzealey** [Koenkk/zigbee2mqtt#11479]
### What happened?

I have 3 TS0001 which I would like to be in sync with each other ie when one button gets pressed all of them toggle. I believe this is device binding, I guess for the `OnOff` cluster. But when I go into the binding tab of the device, the only clusters are `Ota` and `genTime` even though `OnOff` is shown on the controller bind
![image](https://user-images.githubusercontent.com/6083471/154733318-c6681c15-fe02-4075-b437-c13089b33086.png)

### What did you expect to happen?

I was expecting that I could bind (either to each other, or to a group which I have created) the state of these devices together

### Zigbee2MQTT version

1.23.0 (commit #6ea61ba) from Docker

### Adapter firmware version

20211217

### Adapter

Sonoff SNZB-1 zStack3x0

**Comment by olili** [comment]
I'm interessted in this feature as well.
 
I think TUYA calls this feature "muti-control association" and according sales statement this feature is also available at least with some TS0001.

**Comment by vk496** [comment]
Me too. Not sure if is Tuya devices problem or is limited to only few devices to bind

**Comment by toxuin** [comment]
Why is this closed as completed? This is still happening and is still indeed a problem.

**Comment by setfire2** [comment]
I would be interested in a solution as well. I think it's the intended way you do changeover switching with these kind of switches. A quite common use case.

**Comment by olili** [comment]
feature request was closed due to missing interesst...
[https://github.com/Koenkk/zigbee2mqtt/issues/13323](url)
