### ISSUE TITLE
Tuya TS011F power report

### ISSUE THREAD

**Issue by phoxy84** [Koenkk/zigbee2mqtt#11474]
### What happened?

Strange power report readings. Constant drop in the report.

![Power report](https://user-images.githubusercontent.com/39917461/154653200-25145d9d-5a24-4b1c-ad0a-dc6e9c9b633b.png)

i have a:
Zigbee model: TS011F
Zigbee Fabrikant: _TZ3000_typdpbpg

### What did you expect to happen?

I expect a consistent report. The power does not drop that often.

### How to reproduce it (minimal and precise)

Just turn on the device and the report shows. In the z2m logs i can see the power readings, not the drops to 0 power.

is it a home assistant problem of z2m?

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

20211217

### Adapter

Zzh

**Comment by McGiverGim** [comment]
I have a TS011F_plug_1 and it seems to work right:

![image](https://user-images.githubusercontent.com/2673520/154656200-4b22b649-5f67-4ae9-845c-acca8ba35f2c.png)

What model have you? plug_1, plug_2 or plug_3? 

To get something from here, you will need to capture logs in DEBUG mode, to see what is happening exactly.

**Comment by phoxy84** [comment]
I have plug_1. Will try to get the debug data. Do i need that data only for this device? Or all the debug data for a period of time when the device registers power?

**Comment by phoxy84** [comment]
I have some debug data:

`Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID 0
Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0
Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":183}' from endpoint 1 with groupID 0
Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":40}' from endpoint 1 with groupID 0
Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,69]}' from endpoint 1 with groupID 0
Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,70]}' from endpoint 1 with groupID 0 `

**Comment by McGiverGim** [comment]
For the next time, try to get the log from the log file that zigbee2mqtt creates, it contains at least return at the end of lines and a timestamp at the beginning. And a log a little longer can give more information.

What I see in the log, is that the device is sending the messsage `haElectricalMeasurement` with `activePower` zero:
```log
Debug Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0 
```
And the definition of the converter for this device uses this value for the power, returning the value to zero:
```log
Info MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":0.7,"linkquality":61,"power":0,"power_outage_memory":"on","state":"ON","voltage":236}'
```
A little later you can see it again, giving value of 41:
```log
Debug Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":41}' from endpoint 1 with groupID 0 
Info MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":0.7,"linkquality":61,"power":41,"power_outage_memory":"on","state":"ON","voltage":236}'
```
I have debugged my device too, that is working right, and it seems to not send zero in the `activePower` while it is `ON`. Zigbee2mqtt simply shows this value, that is being sent by your device.
I don't know if someone more can have another idea, but what I see is that is the device who sends the zero. I don't know why.

**Comment by phoxy84** [comment]
It looks like it's the device. Is it possible to ignore the single 0 reading?


`info  2022-02-22 08:28:40: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":40,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:28:40: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":40,"power":0,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:28:45: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":32,"power":41,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:28:45: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":1.74,"linkquality":36,"power":41,"power_outage_memory":"on","state":"ON","voltage":234}'`

`info  2022-02-22 08:33:10: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":25,"power":41,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:33:10: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":29,"power":0,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:33:15: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":25,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:33:15: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":1.74,"linkquality":25,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'
info  2022-02-22 08:33:15: MQTT publish: topic 'zigbee2mqtt/iMac', payload '{"current":0.41,"energy":0.26,"linkquality":43,"power":98,"power_outage_memory":"on","state":"ON","voltage":232}'
info  2022-02-22 08:33:15: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":1.74,"linkquality":29,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'`

**Comment by phoxy84** [comment]
With debug:
`Zigbee2MQTT:debug 2022-02-22 08:42:07: Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-02-22 08:42:07: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":25,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'
Zigbee2MQTT:debug 2022-02-22 08:42:07: Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-02-22 08:42:07: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0,"energy":1.74,"linkquality":21,"power":0,"power_outage_memory":"on","state":"ON","voltage":234}'
Zigbee2MQTT:debug 2022-02-22 08:42:08: Received Zigbee message from 'iMac', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":91}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-02-22 08:42:08: MQTT publish: topic 'zigbee2mqtt/iMac', payload '{"current":0.45,"energy":0.28,"linkquality":112,"power":91,"power_outage_memory":"on","state":"ON","voltage":232}'
Zigbee2MQTT:debug 2022-02-22 08:42:12: Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":183}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-02-22 08:42:12: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":1.74,"linkquality":14,"power":0,"power_outage_memory":"on","state":"ON","voltage":234}'
Zigbee2MQTT:debug 2022-02-22 08:42:12: Received Zigbee message from 'Vloerverwarming ', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":40}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-02-22 08:42:12: MQTT publish: topic 'zigbee2mqtt/Vloerverwarming ', payload '{"current":0.18,"energy":1.74,"linkquality":18,"power":40,"power_outage_memory":"on","state":"ON","voltage":234}'`

**Comment by McGiverGim** [comment]
> It looks like it's the device. Is it possible to ignore the single 0 reading?

I doubt it is possible. In the worst case I suppose you can create some alternate sensor in Home Assistant that ignores the zero when state is ON.

What have you connected to the plug? Maybe is something that has some fast on/off behaviour?

**Comment by phoxy84** [comment]
I have a computer and floor heating, both have the same experience.

**Comment by Frixtr** [comment]
Hi, I'm having exactly the same issue so you're not alone. I also thought that in case of last resort, I'll use node red to filter the 0. I'm afraid that this is bug in the device itself. I'm experiencing this behaviour with older type without Polling and I believe that it's the same type. I have one newer piece TS011F_plug_3 and with polling configured to every 2 sec, there is no issue.

**Comment by phoxy84** [comment]
Thanks for the response. I have a plug_3 as well without problems. Maybe the Plug_1 can be OTA updated in the future and the problem will be solved. They are busy with that.

**Comment by navycrow** [comment]
The power report is not good. Sometimes, there's no device plugged on the socket and current reported is ZERO. Perfect !!
But how the power could equal to 9W ???

![image](https://user-images.githubusercontent.com/4997731/158026337-bff18582-68e8-4b7e-8c3e-28a73e6de904.png)

**Comment by Flappje** [comment]
I know it's a bit late, But I also have this problem.

I have 4 plugs that show up as TS011F_plug_1. two I bought as NAS-WR01B and report as "_TZ3000_gjnozsaz" and those 2 don't have problems. 
The other two I bought as TS011F and report as "_TZ3000_typdpbpg" have this exact problem (so that my graphs in Home assistant go to 0 all the time, what I have seen it's the current and power that have this problem the voltage works fine.

at least one of my "broken" plugs also have the problem descripted in #11648. 

did you guys already solved this somehow?

**Comment by elenril2** [comment]
I've just bought _TZ3000_gjnozsaz and they don't report energy, power and current.

**Comment by vincentscode** [comment]
I have the same issue. The socket reports to be `_TZ3000_gvn91tmx` (model: `TS011F_plug_1`) and is running the latest firmware (version 192).
This is what it looks like in home assistant.
![image](https://user-images.githubusercontent.com/26576880/230650702-764db6a5-aed9-4a07-8d16-2c0912eb0a09.png)
