### ISSUE TITLE
Aqara T1 switches dont report power anymore

### ISSUE THREAD

**Issue by sygys** [Koenkk/zigbee2mqtt#11480]
### What happened?

After updating to version 1.23.0-1 all 3 of my aqara T1 switches (Xiaomi DLKZMK11LM) stopped reporting power usage and energy (kwh and watts) temperature and controlling the switch keep working. 

i tried re-pairing the devices but that give me this error:

error 2022-02-18 18:52:09: Failed to configure '0x54ef44100009be5b', attempt 1 (Error: Bind 0x54ef44100009be5b/1 genOnOff from '0x00124b00237e0705/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))

### What did you expect to happen?

I expected them to work properly and give me power and energy after the update

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

20210120

### Adapter

cc2652p2

### Debug log

error 2022-02-18 18:52:09: Failed to configure '0x54ef44100009be5b', attempt 1 (Error: Bind 0x54ef44100009be5b/1 genOnOff from '0x00124b00237e0705/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))

**Comment by Koenkk** [comment]
Try updating your coordinator firmware and repair the device (the devices are now expected to be in "xiaomi" mode which require this firmware)

**Comment by sygys** [comment]
I reverted back to the old z2mqtt version and it is working again. I dont understand why updates always have to break stuff that works perfectly...

**Comment by Koenkk** [comment]
@z-x-f could you add back the standard power converters for Aqara devices? (https://github.com/Koenkk/zigbee-herdsman-converters/pull/3292) However I'm not sure if that introduces flipping in precisions

**Comment by z-x-f** [comment]
I think it is better to use an external converter, if you are not going to update the firmware of the coordinator.

**Comment by Koenkk** [comment]
@sygys following external converter should do it:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.switch.n0acn2'],
    model: 'DLKZMK11LM',
    vendor: 'Xiaomi',
    description: 'Aqara single switch module T1 (with neutral)',
    fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple],
    toZigbee: [tz.on_off, tz.xiaomi_power, tz.xiaomi_switch_type, tz.xiaomi_switch_power_outage_memory, tz.xiaomi_led_disabled_night, fz.metering, fz.electrical_measurement],
    exposes: [e.switch(), e.power().withAccess(ea.STATE_GET), e.energy(), e.temperature().withAccess(ea.STATE),
        e.voltage().withAccess(ea.STATE), e.power_outage_memory(), e.led_disabled_night(), e.switch_type()],
    configure: async (device, coordinatorEndpoint, logger) => {
        await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
    },
    ota: ota.zigbeeOTA,
};

module.exports = definition;

```

**Comment by soebbing** [comment]
I have the same issue of power not being reported at all. I tried the external converter above, but `ota.zigbeeOTA` was missing a `require`. I tried the following:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const zigbeeOTA = require('zigbee-herdsman-converters/lib/ota/zigbeeOTA');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.switch.n0acn2'],
    model: 'DLKZMK11LM',
    vendor: 'Xiaomi',
    description: 'Aqara single switch module T1 (with neutral)',
    fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple],
    toZigbee: [tz.on_off, tz.xiaomi_power, tz.xiaomi_switch_type, tz.xiaomi_switch_power_outage_memory, tz.xiaomi_led_disabled_night, fz.metering, fz.e
    exposes: [e.switch(), e.power().withAccess(ea.STATE_GET), e.energy(), e.temperature().withAccess(ea.STATE),
        e.voltage().withAccess(ea.STATE), e.power_outage_memory(), e.led_disabled_night(), e.switch_type()],
    configure: async (device, coordinatorEndpoint, logger) => {
        await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
    },
    ota: zigbeeOTA,
};

module.exports = definition;
```

In the end, nothing changed, though. Still no power is being reported. If there is anything I can help with to make this work, I'm more than happy try stuff out or deliver logs or something!

**Comment by sygys** [comment]
It all started when the z2mqtt update messed up the setup for me. The problem is that the coordinator firmware needs te be updated to the latest version for the to switch to work properly again. I really don't understand why every update seems to break more then it fixes. I decided to just stop updating z2mqtt. The only reason for this is that updates made by koenk seems to keep breaking already working devices forcing to upgrade coordinators and God knows what that can only mess more things up. If everything works just stop updating z2mqtt. There is absolutely no reason to update a perfect working setup. Especially not z2mqtt in which updates tend to have absolutely no value to existing systems and only mess things up

**Comment by soebbing** [comment]
Thanks for your reply! Please excuse my ignorance: what is the coordinator in this context? The Zigbee USB stick I am using? 
Which version of zigbee2mqtt are you using? I don't know how to downgrade it on Hassos, but I'm eager to check it out!

**Comment by sygys** [comment]
Not sure if downgrading will help I posted this issue a while back after which someone replied that the coordinator firmware needed to be upgraded. I'm using a zigbee to Ethernet coordinator from tube's website it uses a CC2652P2 zigbee chip. This thing can be upgraded to the latest firmware. But reading your post I start to wonder if upgrading will fix it. Because if you use an USB stick I don't think that this is the problem. I use an external converter that does work by the way.

**Comment by sygys** [comment]
try this:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.switch.n0agl1'],
    model: 'SSM-U01',
    vendor: 'Xiaomi',
    description: 'Aqara single switch module T1 (with neutral)',
    fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple],
    toZigbee: [tz.on_off, tz.xiaomi_power, tz.xiaomi_switch_type, tz.xiaomi_switch_power_outage_memory, tz.xiaomi_led_disabled_night, fz.metering, fz.electrical_measurement],
    exposes: [e.switch(), e.power().withAccess(ea.STATE_GET), e.energy(), e.temperature().withAccess(ea.STATE),
        e.voltage().withAccess(ea.STATE), e.power_outage_memory(), e.led_disabled_night(), e.switch_type()],
    configure: async (device, coordinatorEndpoint, logger) => {
        await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
    },
    ota: ota.zigbeeOTA,
};

module.exports = definition;
```

**Comment by sygys** [comment]
This works with my T1's

**Comment by soebbing** [comment]
After the firmware update alone didn't fix it, I just tried to re-add the device into the network. After the device got interviewed correctly, it doesn't seem to be working at all. The values/states that worked (On/off, temperature, e.g.) are recognized, but not working. It looks like the connection get's dropped after the interview.

I tried the same with your converter, with similar results.

I'll try to downgrade the coordinator later and repeat the process. :(

**Comment by soebbing** [comment]
I downgraded the coordinator to https://github.com/Koenkk/Z-Stack-firmware/blob/467eee408c37c3c4bee956877e2f7aabf9b007e4/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20220103.zip (the previous version) and removed your external converter. This seems to have fixed the issue: I can control the switch and can read values for power, energy and temperature!

I have no insight in how these firmwares are built - is there a place to check for changes between 20220103 and 20220219?

**Comment by FaGerstenlauer** [comment]
Why ist it closed?

The Problem is still there. And the custom converter doesn't work either.  :-(

**Comment by jmcollin78** [comment]
Hello, with the same problem I try to install the converter. At Z2M restart I have this error:
```
Zigbee2MQTT
[19:11:13] INFO: Preparing to start...
[19:11:14] INFO: Socat not enabled
[19:11:17] INFO: Starting Zigbee2MQTT...

/app/node_modules/zigbee-herdsman-converters/index.js:172
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:172:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
```

And Z2M doesn't start anymore.
Because the UI is no more available I cannot remove the aqara-t1.js from external converters and It seems not configured in config files.
So i'm totally stuck.

The converter I get is the one listed above:
```
const fz = require("zigbee-herdsman-converters/converters/fromZigbee");
const tz = require("zigbee-herdsman-converters/converters/toZigbee");
const exposes = require("zigbee-herdsman-converters/lib/exposes");
const reporting = require("zigbee-herdsman-converters/lib/reporting");
const ota = require("zigbee-herdsman-converters/lib/ota");
const extend = require("zigbee-herdsman-converters/lib/extend");
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ["lumi.switch.n0agl1"],
    model: "SSM-U01",
    vendor: "Xiaomi",
    description: "Aqara single switch module T1 (with neutral)",
    fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple],
    toZigbee: [
        tz.on_off,
        tz.xiaomi_power,
        tz.xiaomi_switch_type,
        tz.xiaomi_switch_power_outage_memory,
        tz.xiaomi_led_disabled_night,
        fz.metering,
        fz.electrical_measurement,
    ],
    exposes: [
        e.switch(),
        e.power().withAccess(ea.STATE_GET),
        e.energy(),
        e.temperature().withAccess(ea.STATE),
        e.voltage().withAccess(ea.STATE),
        e.power_outage_memory(),
        e.led_disabled_night(),
        e.switch_type(),
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        await device
            .getEndpoint(1)
            .write(
                "aqaraOpple",
                { mode: 1 },
                { manufacturerCode: 0x115f, disableResponse: true }
            );
    },
    ota: ota.zigbeeOTA,
};

module.exports = definition;
```

**Comment by petravic** [comment]
This converter works with latest release and fixed the power not reporting problem for me.

**Comment by jmcollin78** [comment]
> This converter works with latest release and fixed the power not reporting problem for me.
> 
> ```
> const {} = require('zigbee-herdsman-converters/lib/modernExtend');
> 
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const ota = require('zigbee-herdsman-converters/lib/ota');
> const utils = require('zigbee-herdsman-converters/lib/utils');
> const globalStore = require('zigbee-herdsman-converters/lib/store');
> const lumi = require('zigbee-herdsman-converters/lib/lumi');
> const e = exposes.presets;
> const ea = exposes.access;
> 
> const definition = {
>     zigbeeModel: ['lumi.switch.n0agl1'],
>     model: 'SSM-U01',
>     vendor: 'Aqara',
>     description: 'Single switch module T1 (with neutral)',
>     extend: [],
>     fromZigbee: [fz.on_off, fz.metering, fz.electrical_measurement, fz.device_temperature, lumi.fromZigbee.lumi_specific],
>     exposes: [e.switch(), e.energy(), e.power(), e.device_temperature(), e.power_outage_memory(), e.power_outage_count(), e.switch_type(), e.voltage(), e.current()],
>     toZigbee: [lumi.toZigbee.lumi_switch_type, tz.on_off, lumi.toZigbee.lumi_switch_power_outage_memory, lumi.toZigbee.lumi_led_disabled_night],
>     configure: async (device, coordinatorEndpoint) => {
>         const endpoint = device.getEndpoint(1);
>         await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering', 'genDeviceTempCfg']);
>         await reporting.onOff(endpoint);
>         await endpoint.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);
>         await reporting.readMeteringMultiplierDivisor(endpoint);
>         await reporting.currentSummDelivered(endpoint);
>         await reporting.activePower(endpoint, {min: 5, max: 600, change: 10});
>         await reporting.deviceTemperature(endpoint);
>         device.powerSource = 'Mains (single phase)';
>         device.type = 'Router';
>         device.save();
>     }
> };
> ```

last line is missing. See post above.

**Comment by jmcollin78** [comment]
> Hello, with the same problem I try to install the converter. At Z2M restart I have this error:
> 
> ```
> Zigbee2MQTT
> [19:11:13] INFO: Preparing to start...
> [19:11:14] INFO: Socat not enabled
> [19:11:17] INFO: Starting Zigbee2MQTT...
> 
> /app/node_modules/zigbee-herdsman-converters/index.js:172
>         if (converter.options) {
>                       ^
> TypeError: Cannot read properties of undefined (reading 'options')
>     at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:172:23)
>     at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
>     at new Controller (/app/lib/controller.ts:84:58)
>     at start (/app/index.js:106:18)
> ```
> 
> And Z2M doesn't start anymore. Because the UI is no more available I cannot remove the aqara-t1.js from external converters and It seems not configured in config files. So i'm totally stuck.
> 
> The converter I get is the one listed above:
> 
> ```
> const fz = require("zigbee-herdsman-converters/converters/fromZigbee");
> const tz = require("zigbee-herdsman-converters/converters/toZigbee");
> const exposes = require("zigbee-herdsman-converters/lib/exposes");
> const reporting = require("zigbee-herdsman-converters/lib/reporting");
> const ota = require("zigbee-herdsman-converters/lib/ota");
> const extend = require("zigbee-herdsman-converters/lib/extend");
> const e = exposes.presets;
> const ea = exposes.access;
> 
> const definition = {
>     zigbeeModel: ["lumi.switch.n0agl1"],
>     model: "SSM-U01",
>     vendor: "Xiaomi",
>     description: "Aqara single switch module T1 (with neutral)",
>     fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple],
>     toZigbee: [
>         tz.on_off,
>         tz.xiaomi_power,
>         tz.xiaomi_switch_type,
>         tz.xiaomi_switch_power_outage_memory,
>         tz.xiaomi_led_disabled_night,
>         fz.metering,
>         fz.electrical_measurement,
>     ],
>     exposes: [
>         e.switch(),
>         e.power().withAccess(ea.STATE_GET),
>         e.energy(),
>         e.temperature().withAccess(ea.STATE),
>         e.voltage().withAccess(ea.STATE),
>         e.power_outage_memory(),
>         e.led_disabled_night(),
>         e.switch_type(),
>     ],
>     configure: async (device, coordinatorEndpoint, logger) => {
>         await device
>             .getEndpoint(1)
>             .write(
>                 "aqaraOpple",
>                 { mode: 1 },
>                 { manufacturerCode: 0x115f, disableResponse: true }
>             );
>     },
>     ota: ota.zigbeeOTA,
> };
> 
> module.exports = definition;
> ```

Finally I got it working !

I press the both button on Zigbee2mqtt which seems to do a kind of soft pairing of the device:
![Capture d’écran 2024-06-18 à 18 57 42](https://github.com/Koenkk/zigbee2mqtt/assets/1712374/90f20944-b4e7-446f-a5d0-ba5e0c1163be)

The power instantaneously comes back !

**Comment by Kiezelke** [comment]
thanks, works now. Reconfiguration did the trick.

**Comment by hexer4u** [comment]
Hi
I tried the converter mentioned above, and initially ran into an issue because it was using 
`const extend = require('zigbee-herdsman-converters/lib/extend'); `
which was not supported anymore. I removed it.
Then I got 
`Failed to load external converter file 'aqara-t1.js' (Cannot read properties of undefined (reading 'options'))`
and now i'm stuck.

Any ideas?
Thanks

**Comment by g-lom** [comment]
put the file aqara-t1.js in the directory config/zigbee2mqtt/external_converters

**Comment by jmcollin78** [comment]
Personnaly I get bored of this issue and I remove all Aqara T1 from my env. There is Nous switch, smaller and that just work out of the box.

**Comment by hexer4u** [comment]
Update to my previous note, the converter stopped working.

I also found that Nous relays work out-of-the-box with z2m. The only downside is the LQI, which is much better for Aqara T1, since it has an external antena. Nous are also cheaper.

Good news: I just downgraded my T1 using the firmware from here https://github.com/Koenkk/zigbee2mqtt/issues/19902 and for now (1h only) it seems to work perfectly.

**Comment by KingTomaHawk** [comment]
Here is a modified version that works (for me) on the latest Z2M builds. The code was corrected using AI, which took about 10 attempts to fix. I accept no responsibility for damage, problems or malfunctions of the device due to this code:

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');

const e = exposes.presets;

const fromZigbee = [
    fz.on_off,
    fz.metering,
    fz.electrical_measurement,
    fz.device_temperature,
    fz.aqara_opple || { key: ['aqara_opple_dummy'], convert: () => {} }
].filter(c => c !== undefined);

const toZigbee = [
    tz.on_off,
].filter(c => c !== undefined);

const definition = {
    zigbeeModel: ['lumi.switch.n0agl1'],
    model: 'SSM-U01',
    vendor: 'Aqara',
    description: 'Single switch module T1 (with neutral) - Manual Fix',

    fromZigbee: fromZigbee,
    toZigbee: toZigbee,

    exposes: [
        e.switch(),
        e.energy(),
        e.power(),
        e.device_temperature(),
        e.voltage(),
        e.current()
    ],

    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);

        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering', 'genDeviceTempCfg']);
        await reporting.onOff(endpoint);

        try {
            await endpoint.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);

            await reporting.readMeteringMultiplierDivisor(endpoint);
            await reporting.currentSummDelivered(endpoint);
            await reporting.activePower(endpoint, {min: 5, max: 600, change: 10});

            await reporting.deviceTemperature(endpoint);
        } catch (error) {
            console.log('Aqara Custom Configure Warning: ' + error.message);
        }

        device.powerSource = 'Mains (single phase)';
        device.type = 'Router';
        device.save();
    }
};

module.exports = definition;

**Comment by Andry772** [comment]
> Here is a modified version that works (for me) on the latest Z2M builds. The code was corrected using AI, which took about 10 attempts to fix. I accept no responsibility for damage, problems or malfunctions of the device due to this code:
> 
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> 
> const e = exposes.presets;
> 
> const fromZigbee = [
>     fz.on_off,
>     fz.metering,
>     fz.electrical_measurement,
>     fz.device_temperature,
>     fz.aqara_opple || { key: ['aqara_opple_dummy'], convert: () => {} }
> ].filter(c => c !== undefined);
> 
> const toZigbee = [
>     tz.on_off,
> ].filter(c => c !== undefined);
> 
> const definition = {
>     zigbeeModel: ['lumi.switch.n0agl1'],
>     model: 'SSM-U01',
>     vendor: 'Aqara',
>     description: 'Single switch module T1 (with neutral) - Manual Fix',
> 
>     fromZigbee: fromZigbee,
>     toZigbee: toZigbee,
> 
>     exposes: [
>         e.switch(),
>         e.energy(),
>         e.power(),
>         e.device_temperature(),
>         e.voltage(),
>         e.current()
>     ],
> 
>     configure: async (device, coordinatorEndpoint) => {
>         const endpoint = device.getEndpoint(1);
> 
>         await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering', 'genDeviceTempCfg']);
>         await reporting.onOff(endpoint);
> 
>         try {
>             await endpoint.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);
> 
>             await reporting.readMeteringMultiplierDivisor(endpoint);
>             await reporting.currentSummDelivered(endpoint);
>             await reporting.activePower(endpoint, {min: 5, max: 600, change: 10});
> 
>             await reporting.deviceTemperature(endpoint);
>         } catch (error) {
>             console.log('Aqara Custom Configure Warning: ' + error.message);
>         }
> 
>         device.powerSource = 'Mains (single phase)';
>         device.type = 'Router';
>         device.save();
>     }
> };
> 
> module.exports = definition;

it works for me - thank you

**Comment by soebbing** [comment]
How do i make sure the custom integration setting is being used? I added the file to the config, but the custom description ("manual fix") is not showing up in the logs after a restart and a reconfiguration of the device.

**Comment by Andry772** [comment]
> How do i make sure the custom integration setting is being used? I added the file to the config, but the custom description ("manual fix") is not showing up in the logs after a restart and a reconfiguration of the device.

mkdir external_converters in homeassistant/zigbee2mqtt
make file aquara.js
paste code

check there is an arrow next to the device

<img width="64" height="55" alt="Image" src="https://github.com/user-attachments/assets/d60558a6-12b3-420f-bcc6-afb844d8d3e7" />

**Comment by soebbing** [comment]
Thanks for your reply, that helped! I didn't have the subdirectory `external_converters`, instead I added the filename to an `external_converters:` list in the configuration yaml, but that didn't do the trick. Now I see the arrow, and the modified description.

Unfortunately, I am using the relais to monitor my little PV installation, which right now doesn't generate any power anymore. We'll see tomorrow
