### ISSUE TITLE
Z2M-frontend not working without internet-connection

### ISSUE THREAD

**Issue by VladNord** [Koenkk/zigbee2mqtt#11482]
### What happened?

My ISP was having problems, so no internet connection.
until the Internet connection was restored, it was impossible to use z2m.
the following error was displayed. dump attached
![image](https://user-images.githubusercontent.com/51515620/154770872-cd5c7edb-4a9d-4c09-92fc-0d5df24724eb.png)

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

0x26720700

### Adapter

deconz

### Debug log

[initialState.json.zip](https://github.com/Koenkk/zigbee2mqtt/files/8100837/initialState.json.zip)

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by iluminat23** [comment]
https://github.com/nurikk/zigbee2mqtt-frontend/issues/1364
