### ISSUE TITLE
Tuya S-LUX-ZB maximum lux output stops at 1,000, sensor generates values 0.01 to 830,000 lux

### ISSUE THREAD

**Issue by deepcoder** [Koenkk/zigbee2mqtt#11484]
### What happened?

I am experimenting with the newer version of this Tuya Illuminance Sensor
```
TS0601
_TZE200_pisltm67
```
The values reported by zigbee2mqtt max out at 1000, however the device instructions show it being able to generate values up 830000 lux.

I am trying to measure outdoor lux levels and they clearly go above 1000. As is described in this Wikipedia entry:

https://en.wikipedia.org/wiki/Lux

If I read the Zigbee Cluster Specification correctly, the lux value should be returned by the devices as 16 bit value with a range of 1 to 0xFFFE corresponding to lux values from 1 to 3,576,000. I am out of league here, but I understand Tuya devices report differently, perhaps this could be part of the problem. Also, I note that there can be max and min limits specified, but I hope a 1,000 lux limit is not specified.

In searching similar issues, I found this discussion where there is some question about the correct formula:

https://github.com/Koenkk/zigbee-herdsman-converters/issues/1506#issuecomment-683387479

Below is a table showing using the Zigbee specification formula to generate the full range of values supported:

23.2 Illuminance Measurement Structure and Attributes

![lux_calc](https://user-images.githubusercontent.com/1409547/154780203-eb65c376-a5b5-4446-acc6-5392f97e3706.jpg)

### What did you expect to happen?

Lux values should go above 1,000 as per Zigbee specs.

### Zigbee2MQTT version

 1.23.0-dev commit: ba1843f

### Adapter firmware version

 20211217

### Adapter

 zStack3x0

### Debug log

```
info  20220218-135230: MQTT publish: topic 'test_zigbee2mqtt/0xa4c138ec16265b02', payload '{"battery":"100.0","battery_low":"2.0","elapsed":6442,"illuminance_lux":"1000","last_seen":"2022-02-18T13:52:30-08:00","linkquality":102}'
info  20220218-135230: MQTT publish: topic 'test_zigbee2mqtt/0xa4c138ec16265b02', payload '{"battery":"100.0","battery_low":"2.0","elapsed":110,"illuminance_lux":"1000","last_seen":"2022-02-18T13:52:30-08:00","linkquality":98}'
info  20220218-135236: MQTT publish: topic 'test_zigbee2mqtt/0xa4c138ec16265b02', payload '{"battery":"100.0","battery_low":"2.0","elapsed":6443,"illuminance_lux":"718","last_seen":"2022-02-18T13:52:36-08:00","linkquality":98}'

```

**Comment by leroyloren** [comment]
viz. https://github.com/Koenkk/zigbee-herdsman-converters/issues/3893#issue-1143301451

The device sends the level in percentage **0-1000%**

**Comment by deepcoder** [comment]
I'm confused by your post. Are you saying that the device sends a value between 0% and 1000% both on zigbee2mqtt and on the native Tuya zigbee system?

As much as I try to embrace a way of life based on the philosophy from the movie Spinal Tap, where all the knobs and dials in my house go up to eleven rather than ten. I am not sure how to interpret a 'light level' of 1000 percent...

I have no Chinese language reading skills, and since the manual that came with my device is only in Chinese, I'm at a great disadvantage here but is seems as though the device measures a range of 0.01 to 830,000 lux. Are you saying that the device does not send these values out via it's zigbee communication?
![lux-sensor-range](https://user-images.githubusercontent.com/1409547/154810682-93d79b9b-ea6c-4838-8cea-ad7a7a0c0c84.jpg)

**Comment by leroyloren** [comment]
I don't know if it doesn't send, but in the Tuya app everything is displayed 0-1000% with the possibility of defining the range (low, medium, high) intensity.

**Comment by deepcoder** [comment]
Thanks for the info, frustrating! Two more devices destine for the bottom drawer of the desk that is labeled 'e-waste/junk'. Especially, since they were not 'low cost', I paid USD 20 each, I should have sucked it up and bought the Hue devices, since I have wasted enough time to more and make up the difference.

I sure hope the zigbee2mqtt folks can find a way to add a 'user experience' section to the device database.
Good hunting!

**Comment by leroyloren** [comment]
At first I was so skeptical, but after a day in operation I am finally satisfied, the device sends some real values to work with and personally I do not care in which units. In addition, conversion from % to lux will certainly not be a problem.

Just to say, it really only measures daylight, no night LED lighting at all.

**Comment by aarenzanac** [comment]
I have the same problem. The iluminance_lux stops at 1000lx.
Is there a solution to this problem?
Or is there another device zigbee that really works to lux measure?
Thanks

**Comment by deepcoder** [comment]
I agree @aarenzanac , very frustrating ! I am still far from a useful device to monitor lux level on a logarithmic scale from night to intense light. Why is this so hard????

Hue devices just seem to emphasize motion over light and are not a good solution IMHO.

I am evaluating a custom build zigbee device using a combo of CC2530, ptvo firmware and BH1750 lux sensor. That said, I am still far from a useful device. 

This should not be so hard, this does not appear to be more complex than reading temperature and humidity in a a 'relative' real time perspective!

The tuya device are junk IMHO, no understanding of lux scale, no support, no firmware revisions. Crap!
