### ISSUE TITLE
[New device support]: Wall Plug switch  model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'

### ISSUE THREAD

**Issue by patrick-foubert-56770** [Koenkk/zigbee2mqtt#11490]
### Link

https://fr.aliexpress.com/item/1005002248492657.html?gatewayAdapt=glo2fra&spm=a2g0o.9042311.0.0.27426c37coD5kg

### Database entry

{"id":33,"type":"Router","ieeeAddr":"0xa4c1380b9246be94","nwkAddr":2299,"manufId":4417,"manufName":"_TZ3000_kx0pris5","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"seMetering":{"attributes":{"currentSummDelivered":[0,0],"status":0}},"genOnOff":{"attributes":{"20480":1,"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2684564,"53251":124,"53252":11332,"53253":1340,"53264":0,"switchType":0}},"genScenes":{"attributes":{"count":0}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":237}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1645282047061,"useImplicitCheckin":true}

### Comments

My HA logs: 
 Device '0xa4c1380b9246be94' joined
info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c1380b9246be94","ieee_address":"0xa4c1380b9246be94"},"type":"device_joined"}'
info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xa4c1380b9246be94"},"type":"device_connected"}'
info Starting interview of '0xa4c1380b9246be94'
info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c1380b9246be94","ieee_address":"0xa4c1380b9246be94","status":"started"},"type":"device_interview"}'
info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0xa4c1380b9246be94"},"type":"pairing"}'
debug Received Zigbee message from '0xa4c1380b9246be94', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID null
debug Skipping message, definition is undefined and still interviewing
debug Received Zigbee message from '0xa4c1380b9246be94', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID null
debug Skipping message, definition is undefined and still interviewing
debug Received Zigbee message from '0xa4c1380b9246be94', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID null
debug Skipping message, definition is undefined and still interviewing
info Successfully interviewed '0xa4c1380b9246be94', device has successfully been paired
warning Device '0xa4c1380b9246be94' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0xa4c1380b9246be94","ieee_address":"0xa4c1380b9246be94","status":"successful","supported":false},"type":"device_interview"}'
info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0xa4c1380b9246be94","supported":false},"type":"pairing"}'
debug Received Zigbee message from '0xa4c1380b9246be94', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,0]}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,216,10,1,208,72,2,0,6],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,216,10,1,208,72,2,0,6],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,216,10,1,208,72,2,0,6],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,216,10,1,208,72,2,0,6],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,216,10,1,208,72,2,0,6],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'raw', cluster '57344', data '{"data":[8,217,10,2,208,72,2,0,10],"type":"Buffer"}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'attributeReport', cluster 'genOnOff', data '{"20480":1,"32768":0,"moesStartUpOnOff":0,"offWaitTime":0,"onOff":0,"onTime":0,"tuyaBacklightMode":1}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'attributeReport', cluster 'manuSpecificTuya_3', data '{"53248":1,"53249":0,"53250":2684564,"53251":124,"53252":11332,"53253":1340,"53264":0,"switchType":0}' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug Received Zigbee message from '0xa4c1380b9246be94', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID null
warning Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_kx0pris5'
warning Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### External converter

```shell
not now
```

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
