### ISSUE TITLE
[New device support]: Hue White Ambiance Pillar

### ISSUE THREAD

**Issue by yorickri** [Koenkk/zigbee2mqtt#11508]
### Link

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-pillar--enkele-spot/8719514338524

### Database entry

{"id":38,"type":"Router","ieeeAddr":"0x001788010bbb41dd","nwkAddr":62910,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003046501","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1645361169510,"defaultSendRequestWhen":"immediate"}

### Comments

Same as 5633030P6, which is already supported.

### External converter

```shell
const { toZigbeeConverters: tz, fromZigbeeConverters: fz, exposes } = require('zigbee-herdsman-converters');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

// Copied from zigbee-herdsman-converters/devices/philips.js with no modifications
const hueExtend = {
  light_onoff_brightness: (options = {}) => ({
    ...extend.light_onoff_brightness(options),
    toZigbee: extend.light_onoff_brightness(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_colortemp: (options = {}) => ({
    ...extend.light_onoff_brightness_colortemp(options),
    toZigbee: extend.light_onoff_brightness_colortemp(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
};

module.exports = [{
  zigbeeModel: ['929003046501'],
  model: '5633030P6',
  vendor: 'Philips',
  description: 'Hue White ambiance Pillar spotlamp',
  meta: { turnsOffAtBrightness1: true },
  extend: hueExtend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
  ota: ota.zigbeeOTA,
}];
```

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
