### ISSUE TITLE
Slider is not adjustable less than 1

### ISSUE THREAD

**Issue by zgdump** [Koenkk/zigbee2mqtt#11514]
### What happened?

I am developing my own zigbee thermostat. In the converter, in exposes, I wrote `climate()` with a fractional step for adjusting the temperature and target temperature. Like this:

```js
exposes.climate()
    .withSystemMode(['off', 'auto'])
    .withLocalTemperature()
    .withLocalTemperatureCalibration(0.0, 2.5, 0.5)
    .withSetpoint('occupied_heating_setpoint', 15.0, 50.0, 0.5)
    .withEndpoint(epName),
```

But the slider step still remains 1. If I change the value from the thermostat itself, the slider correctly displays a fractional value

### What did you expect to happen?

The slider must have the step that is prescribed by the author of the converter

### How to reproduce it (minimal and precise)

I don't know which devices have a slider in the converter

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20210120

### Adapter

SONOFF ZigBEE 3.0 USB Dongle Plus

**Comment by Koenkk** [comment]
issues related to the frontend should be created here https://github.com/nurikk/zigbee2mqtt-frontend/issues
