### ISSUE TITLE
Configuring sleeping devices right after receiving data from them

### ISSUE THREAD

**Issue by vke** [Koenkk/zigbee2mqtt#1151]
@Koenkk is it possible to postpone configuration of battery powered always sleeping devices until data is received from them?

I have more than 10 sleeping devices and after startup zigbee2mqtt is flooding network and logs with configuration messages and configuration fails.

I see in sniffer that Ikea's devices are awaking every ~298 seconds and asking for data (IEEE 802.15.4 Data Request) and going to sleep again.

Is it possible to send configuration only upon receiving Data Request or other type of messages (button click, for example) if device is battery powered and sleeping?

**Comment by Koenkk** [comment]
Currently both are done (so on startup, if this fails, a retry when a message from the device is received).

When removing the configuration on startup, in cases where you manually wake up the device (which does not always have to produce a message) during the start of zigbee2mqtt, the configuration wouldn't be executed.

I don't see a reason to remove it.
