### ISSUE TITLE
No endpoint names other than l1 and l2 work

### ISSUE THREAD

**Issue by zgdump** [Koenkk/zigbee2mqtt#11517]
### What happened?

I am developing my own zigbee thermostat. In the converter, in exposes, I wrote `climate()` with some field. Like this:

```js
exposes.climate()
    .withSystemMode(['off', 'auto'])
    .withLocalTemperature()
    .withLocalTemperatureCalibration(0.0, 2.5, 0.5)
    .withSetpoint('occupied_heating_setpoint', 15.0, 50.0, 0.5)
    .withEndpoint(epName),
```

I have two thermostat endpoints in my device, I wrote this in the converter: 

```js
meta: {
    multiEndpoint: true
},
endpoint: (device) => {
    return {
        'l1': 1,
        'l2': 2
    };
},
```

And everything works. 
But should I change `l1` to `thermostat_1` or `th1` and always get this:

![image](https://user-images.githubusercontent.com/60278551/154854305-77db7c1f-37ce-428e-9e17-712a1f121255.png)

Which names are allowed and which are not? Is it possible to make readable names for the user, and leave l1 and l2 under the hood? 

### What did you expect to happen?

Any name for the endpoint is valid and does not cause strange errors 

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20210120

### Adapter

SONOFF ZigBEE 3.0 USB Dongle Plus

**Comment by Koenkk** [comment]
only endpoint names in https://github.com/Koenkk/zigbee2mqtt/blob/6ea61bae2cf441e15612dc68c257797fba46312b/lib/util/utils.ts#L30 can be used

**Comment by zgdump** [comment]
> only endpoint names in
> 
> https://github.com/Koenkk/zigbee2mqtt/blob/6ea61bae2cf441e15612dc68c257797fba46312b/lib/util/utils.ts#L30
> can be used

Thanks, now I understand! Will arbitrary names be supported? Is it possible to create a user-friendly name for the endpoint, an alias?

**Comment by Koenkk** [comment]
Only if they are added to endpoint names

**Comment by zgdump** [comment]
Sad, thank you
