### ISSUE TITLE
[Feature request]: Add `last_motion` for motion sensors

### ISSUE THREAD

**Issue by 0ip** [Koenkk/zigbee2mqtt#11528]
### Is your feature request related to a problem? Please describe

On my home automation dashboard I would like to display the date and time of the last movements my motion sensors have registered. For that, I currently need an additional layer between Z2M and the dashboard that keeps looking for `occupancy: true` messages and injects a `last_motiont` field based on the previous changes. A similar approach could be taken with contact sensors.

### Describe the solution you'd like

Ideally, Z2M would offer a `last_motion` or `last_occupancy` field for all motion sensors. This feature could be extended to contact sensors as well.

### Describe alternatives you've considered

An alternative would be additional software that watches for state changes and updates/injects said fields. 

‎

**Comment by sjorge** [comment]
This seems like something that should be easy to do with a [user-extensions](https://www.zigbee2mqtt.io/advanced/more/user_extensions.html#user-extensions).

You can hook into onDeviceMessage and if it has the motion or occupancy attribute inject the timestamp before publishing.

**Comment by 0ip** [comment]
Perhaps someone more knowledgable than me w/ user extensions can pull this off. Maybe one can also think about a fixed integration. @Koenkk @sjorge

**Comment by 0ip** [comment]
still relevant

**Comment by 0ip** [comment]
Perhaps someone more knowledgable than me w/ user extensions can pull this off. Maybe one can also think about a fixed integration considering it's a basic and quite useful feature. @Koenkk @sjorge

**Comment by 0ip** [comment]
Still relevant
