### ISSUE TITLE
Light level RTCGQ01LM possible?

### ISSUE THREAD

**Issue by iFloris** [Koenkk/zigbee2mqtt#1154]
Hello, after figuring out why my sensors were not connecting(#696), I am now well on my way to connect everything zigbee to zigbee2mqtt, thanks!

After connecting rtcgq01lm (Xiaomi Mijia RTCGQ01LM Human Body Sensor) I noticed that the sensor only shows up as motion sensor, not as a light sensor. I used to have some automations that turned on lights if 1. light level was below x and 2. motion was seen for longer than x seconds.
Is it possible to get the light level from RTCGQ01LM as well?

**Comment by Koenkk** [comment]
No, the RTCGQ01LM doesn't have an illuminance sensor, buy the RTCGQ**1**1LM  if you want illuminance.

**Comment by iFloris** [comment]
Thanks @Koenkk for the quick response. I am a bit confused, as I was able to get light level information from the sensor with the xiaomi hub. I will look into the model you suggested, thanks!

**Comment by thomashogema** [comment]
I just started converting to zigbee2mqtt (working great so far!), but can also confirm the RTCGQ01LM human body sensor _does_ include illumination when interacting via the Aqara hub. Is it possible to add this functionality, or was the Aqara gateway faking data somehow before?

**Comment by Koenkk** [comment]
@thomashogema strange that the gateway shows values, an easy check to see if they make sense is to first put the sensor in dark (check values of gateway) and then put it in full day light (check values again), do the values on the gateway significantly change?

**Comment by thomashogema** [comment]
@Koenkk thanks for the quick reply!
I've just removed the old entry from HA so unfortunately I can't look back at the history anymore. However, I am quite sure that the sensor values made sense (value between 0 and 1000 depending on the time of day).

If I can be of any help by reconnecting it to the aqara gateway and check some values let me know!
