### ISSUE TITLE
Linkind ZS130000078 : The automation server must validate the request and send a notification to the keypad

### ISSUE THREAD

**Issue by kris969** [Koenkk/zigbee2mqtt#11564]
### What happened?

I am using z2m 1.23 release version
my setup : z2m / mosquitto / node-red

This LINKING keypad is paired and well recognized by z2m.
When I am doing "Arming/Disarming from the server" as explained in z2m documentation : it works
When I am doing "Arming/Disarming from the keypad" as explained in z2m documentation :
- The correct message is received in node-red, exactly as describe in documentation
- I tune a node-red node to answer back to the keyboard, following the topic in documentation, let's say : 

if (msg.payload.action != undefined)
{
    node.warn("transaction code: " + msg.payload.action_transaction)
    var newMsg = {payload: {arm_mode: {mode: "exit_delay", transaction: msg.payload.action_transaction}}} 
     return newMsg;
}

adding around this with as many debug nodes as useful...
I confirm the correct message is sent back to the keypad, but the keypad seems not to understand it. Unless of taking this in account it repeats its previous message twice !

As anyone seen similar issue?
any idea?

note: I have tried the dev branch due to the fact it doesn't start with my configuration ! It was working a couple of days but it doesn't work anymore. I have to understand this point to.

Any idea will be welcome ;)

 

### What did you expect to happen?

The keyboard to take the message in account, with relative button showing the new mode stored.

### How to reproduce it (minimal and precise)

Try to send back message from server to keypad

### Zigbee2MQTT version

1.23

### Adapter firmware version

 0x26720700

### Adapter

CONBEE II

**Comment by russdan** [comment]
Not sure I can help with the Node Red but my test Python script will arm / disarm from the keypad - I don't think you have enough commands to achieve the outcome, and if you only send some of the commands it repeats them, which sounds like what you're seeing.... hopefully this code snippet helps :

```
    json_object = json.loads(message.payload.decode("utf-8"))

    if message.topic == 'zigbee2mqtt/Linkind Keypad':

        action = json_object['action']
        action_code = json_object['action_code']
        action_transaction = json_object['action_transaction']
        occupancy = json_object['occupancy']
        tamper = json_object['tamper']

        if tamper:
            print('Tamper switch triggered, raising alarm')
            msg = {"arm_mode": { "mode": "in_alarm"}}
            client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))

        elif action != 'null' and action != '' and action is not None:

            print(f'status: {alarm_status}, action: {action}, action_code: {action_code}, action_transaction: {action_transaction}')
            if action == 'arm_day_zones' or action == 'arm_all_zones':
                print('Arming alarm')
                msg = {"arm_mode": {"transaction": action_transaction, "mode": action}}
                client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))

                # Does exit_delay actually do anything??
                msg = {"arm_mode": {"mode": "exit_delay"}}
                client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))
                time.sleep(5)

                msg = {"arm_mode": {"mode": action}}
                client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))

                alarm_status = action
                print('Armed')

            if action == 'disarm' and action_code == user_code:
                print('Disarming alarm')
                msg = {"arm_mode": {"transaction": action_transaction, "mode": action}}
                client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))

                msg = {"arm_mode": { "mode": "disarm"}}
                client.publish('zigbee2mqtt/Linkind Keypad/set', json.dumps(msg))

                alarm_status = action
                print('Disarmed')
```

`alarm_status` is held externally (I use Domoticz) so on restart of z2m it will resume the previous state, and `user_code` is also held in Domoticz as the user PIN code.

I'm not sure a number of features work as (I) expect, namely `exit_delay`, `entry_delay` and `in_alarm` - exit/entry delay don't seem to wait (and where does the duration get defined), and I expected `in_alarm`  to cause the panel to show the alarm had been triggered but it does nothing meaningful... 

I think there's still more to do with respect to integration of these alarm panels...  for example, how do you query the panel for the state its in (it knows its armed, but where is this persisted and passed back via mqtt)?
