### ISSUE TITLE
TuYa [TV02] Wrong current_heating_setpoint after switching to manual preset mode

### ISSUE THREAD

**Issue by Udeson** [Koenkk/zigbee2mqtt#11576]
### What happened?

Using [Zigbee Thermostat radiator valve](https://de.aliexpress.com/item/1005003443511426.html) `Model TS0601 `Zigbee `Manufacturer _TZE200_e9ba97vf` recognized as TuYa [TV02-Zigbee](https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html#tuya-tv02-zigbee).

When switching from preset **auto** to **manual** with a payload like `{"preset":"manual","current_heating_setpoint":"25.0"}` the current_heating_setpoint changes to the last known current_heating_setpoint set in manual preset mode before instead of the value of the payload.

### What did you expect to happen?

Manual preset mode should adjust current_heating_setpoint corresponding to the payload value instead of last known current_heating_setpoint  value from manual preset mode.

### How to reproduce it (minimal and precise)

Via frontend or MQTT cli:
- In preset mode auto switch to preset manual mode without setting current_heating_setpoint value and look for changed current_heating_setpoint value
or
- In preset mode auto switch to preset manual mode with set current_heating_setpoint value and look for changed current_heating_setpoint value

### Zigbee2MQTT version

 version 1.23.0 commit: 6ea61bae

### Adapter firmware version

20211217

### Adapter

Electrorama zzh

### Debug log
Commented  debug log
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8120996/log.txt)

**Comment by jypsie** [comment]
I have a related? problem. My TV02 stays offline.

![image](https://user-images.githubusercontent.com/80754897/155481270-95383615-9feb-43ac-bfba-6f5b916f3f9d.png)

**Comment by Udeson** [comment]
> I have a related? problem. My TV02 stays offline.

What is your understanding of "stays offline"?

What is also crappy on the device behaviour is that you cannot change `current_heating_setpoint in preset: auto mode`... You can adjust temperature on the device itself (without changing preset mode) but not via mqtt command (setting current_heating_setpoint triggers change to preset: manual)...

Accidentally I saw in the OEM manual for my device that the device's model name is `TV01` not `TV02`, so maybe all this is an implementation issue in zigbee2mqtt....

**Comment by jypsie** [comment]
Sorry, I mean disabled see picture, Is this normal?

**Comment by Udeson** [comment]
Mine is showing disabled as well...

**Comment by Udeson** [comment]
As a first ugly workaround I switched order of lines (for tvMode and tvHeatingSetpoint in /converters/toZigbee.js to:

```
case 'current_heating_setpoint':
await tuya.sendDataPointEnum(entity, tuya.dataPoints.tvMode, 1 /* manual */);
await utils.sleep(500);
await tuya.sendDataPointValue(entity, tuya.dataPoints.tvHeatingSetpoint, value * 10);
break;
```

**Comment by Udeson** [comment]
Moreover I have issues with heating at all. Seems like the internal temperature sensor of the device needs to be minimum >4-5 °C bigger than the desired temperature of the device before valve opens.
So in all the device is almost useless to me... shit happens ;-)
