### ISSUE TITLE
RTCGQ13LM not working

### ISSUE THREAD

**Issue by kusok18** [Koenkk/zigbee2mqtt#11586]
### What happened?

Sorry for my English, it's not my native language.
RTCGQ13LM does not work.
The "occupancy" entity is always in the "unknown" state.
I reconfigured the device many times, reinstalled the add-on.
Nothing helps, help revive these sensors.
Before the latest update they worked great.

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

20200211

### Adapter

Texas_Instruments_CC2538_USB

**Comment by Koenkk** [comment]
You need a CC2538 firmware with a Xiaomi fix in it. @0x3ec is this already available?

**Comment by kusok18** [comment]
<img width="1116" alt="Снимок экрана 2022-02-23 в 22 54 07" src="https://user-images.githubusercontent.com/53447958/155388682-da12765d-53fa-4160-a602-3bcbdee935f4.png">
<img width="1402" alt="Снимок экрана 2022-02-23 в 22 57 25" src="https://user-images.githubusercontent.com/53447958/155388768-04ce2401-40f7-4ad0-a1e7-57e79ea73dc7.png">
<img width="964" alt="Снимок экрана 2022-02-23 в 22 57 47" src="https://user-images.githubusercontent.com/53447958/155388800-4a5a38ac-0a32-41b5-a329-2f73d59b7d76.png">

**Comment by kusok18** [comment]
> Вам нужна прошивка CC2538 с исправлением Xiaomi. @0x3EC это уже доступно?

Tell me, can I flash this whistle without additional equipment?

**Comment by Koenkk** [comment]
I think you need a JTag flasher

**Comment by Otnow** [comment]
As a workaround, you can use the [previous version of the converter](https://github.com/Koenkk/zigbee2mqtt/issues/5203#issuecomment-1006955549).

**Comment by phobosdigg** [comment]
I had the same problem as kusok18 and the Otnow method solved my problem. Thanks!
