### ISSUE TITLE
[New device support]: CO2 sensor NDIR

### ISSUE THREAD

**Issue by yuriybabiy** [Koenkk/zigbee2mqtt#11581]
### Link

https://www.aliexpress.com/item/1005003446514631.html?spm=a2g0o.order_list.0.0.21ef1802riG2pR

### Database entry

0xa4c138a8b452524c TS0601 _TZE200_ogkdpgy2

### Comments

Please add support for an interesting device.

**Comment by noogugae** [comment]
This code works for me.
   {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ogkdpgy2'}],
        model: 'TS0601_co2_sensor',
        vendor: 'TuYa',
        description: 'Air quality sensor',
        fromZigbee: [fz.tuya_air_quality],
        toZigbee: [],
        exposes: [e.co2()],
    }

**Comment by yuriybabiy** [comment]
Hooray! Working. Many thanks to all!

**Comment by flatsiedatsie** [comment]
Thank for this.

Unfortunately the readings seem to be inaccurate. 

As an additional test I've placed it outside, where the value should be stable around 430ppm. In practise it's not stable at all, and much higher than expected.

![average_co2_values_every_2_minutes](https://user-images.githubusercontent.com/805405/174591328-f5a065d5-5294-4e5b-9cce-00da32baf4be.png)
_My Candle smart home controller has a feature to only log an average reading every 2 minutes, so this log isn't even as wild as it could be._

Perhaps (if possible) lowering the frequency with which readings are taken could help? Currently it sends data every second or two, which in itself is quite a lot. Some sensors need some time to settle in between readings.

**Comment by yuriybabiy** [comment]
There is no temperature and humidity in my sensor.
There are sensors with these parameters on sale, but the CO2 sensor there is chemical. He shows the devil knows what.
