### ISSUE TITLE
PIR Sensor CR0202 Tuya occupancy false

### ISSUE THREAD

**Issue by c0dr1ver** [Koenkk/zigbee2mqtt#11582]
### What happened?

Tuya CR0202 motion sensor change occupancy to 'false' after occupancy_timeout is expired, but "last seen" value not changed

```
MQTT publish: topic 'zigbee2mqtt/EntranceDD', payload '{"battery":100,"battery_low":false,"device":{"applicationVersion":68,"friendlyName":"EntranceDD","ieeeAddr":"0x847127fffe219a0a","manufacturerID":0,"manufacturerName":"_TYZB01_jytabjkb","model":"TS0202_CR","networkAddress":45129,"powerSource":"Battery","type":"EndDevice","zclVersion":3},"last_seen":"2022-02-22T15:05:30.292Z","linkquality":61,"occupancy":true,"tamper":false}'
Info MQTT publish: topic 'zigbee2mqtt/EntranceDD', payload '{"battery":100,"battery_low":false,"device":{"applicationVersion":68,"friendlyName":"EntranceDD","ieeeAddr":"0x847127fffe219a0a","manufacturerID":0,"manufacturerName":"_TYZB01_jytabjkb","model":"TS0202_CR","networkAddress":45129,"powerSource":"Battery","type":"EndDevice","zclVersion":3},"last_seen":"2022-02-22T15:05:30.292Z","linkquality":61,"occupancy":false,"tamper":false}'
```
The problem is compounded by the fact that the sensor does not send a new value until the movement physically stops. I bought 2 sensors and both work the same way

are there any differences between TS0202_CR and TS0202 ?

### Zigbee2MQTT version

1.23

### Adapter firmware version

20211114

### Adapter

zStack3x0

**Comment by McGiverGim** [comment]
If I'm not wrong, the false is sent by zigbee2mqtt with a timeout over the last true... So the last seen is correct because the device has not been seen since the true.
