### ISSUE TITLE
WS-EUK02 No longer sends actions

### ISSUE THREAD

**Issue by cirdanmiriel** [Koenkk/zigbee2mqtt#11613]
### What happened?

(not sure if this is a zigbee2mqtt problem or a switch problem)
My Aqara Wall Switch WS-EUK02 was working like a charm for days now, but suddenly it disconnected from the zigbee network, so I reinitialized it (5sec on both buttons) and it went back on, BUT now it no longer send actions in the mqtt (with mqttexplorer I no longer see the switch sends actions (like 'single-left' or 'double-both'))
This is a real problem and I can't see what causes this problem...

### What did you expect to happen?

When buttons clicked, an action is sent via mqtt

### How to reproduce it (minimal and precise)

Not sure how to get to that failed mode :(

### Zigbee2MQTT version

1.23.0 commit: 6ea61ba

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

**Comment by jred1337** [comment]
In case you're still having this issue... I had the same problem and found that the "mode" of the device was incorrect.

Try opening the "dev console" tab for the device.

Then select
 endpoint=1,
 cluster=aqaraOpple
 attribute=mode
If you read this and it returns {"mode":0} then this is the same problem I had.

Write 1 to this attribute - after a few seconds you'll get an error which you can ignore. 
However, if you read the "mode" attrbute again it should now be set to 1 and you should get state updates again.
