### ISSUE TITLE
CC2531 LED Control broken in Dev branch?

### ISSUE THREAD

**Issue by marc-gist** [Koenkk/zigbee2mqtt#1162]
I flashed by CC2531 to the latest dev branch firmware.  I have led config set to

    serial:
      port:...
      disabled_led: true

yet after restart of z2m, LED still shining bright!

**Comment by BudBundi** [comment]
> ```
> serial:
>   port:...
>   disabled_led: true
> ```

You have a typo it shoud be `disable_led: true`

**Comment by marc-gist** [comment]
<hand to face> wow, good thing I copied and pasted... clearly i needed to get some sleep. Thanks!!
