### ISSUE TITLE
[New device support]: 915005997801 Philips Hue White and Color Ambiance Xamento M

### ISSUE THREAD

**Issue by caveman2st** [Koenkk/zigbee2mqtt#11635]
### Link

https://www.philips-hue.com/de-at/p/hue-white---color-ambiance-xamento--mittelgrose-deckenleuchte/4116731P9

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0x001788010b4190c3","nwkAddr":41900,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"915005997801","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"915005997801","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1645954932568,"useImplicitCheckin":true}

### Comments

I think, it's similar to [929002966401] https://www.zigbee2mqtt.io/devices/929002966401.html

### Supported color modes

color and temp

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
