### ISSUE TITLE
Sniffing Xiaomi - cannot decrypt packets

### ISSUE THREAD

**Issue by timdonovanuk** [Koenkk/zigbee2mqtt#1164]
Hi,

Has anyone had success sniffing this traffic? I can sniff the packets, but they do not decrypt using the standard Trust Center link key of 5A:69:67:42:65:65:41:6C:6C:69:61:6E:63:65:30:39 (ZigBeeAlliance09). I have tried with two separate sniffing applications now and two different sniffing firmwares on the CC2531.

Stuck right now.

Cheers.

**Comment by Koenkk** [comment]
You need to sniff the (second) encryption key first (as explained in step 3 of http://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by timdonovanuk** [comment]
The **second** encryption key **first**?

The instructions say "Add the Trust Center link key" first - are you saying I need to ignore this and add the Transport Key first?

I have added the Trust Center link key, but it doesn't work, hence the ticket. I cannot decrpyt the second key (Transport Key) if the first Trust Center link key doesn't work, because the Transport Key will be encrypted still....

**Comment by timdonovanuk** [comment]
FINALLY. The instructions you made assume that the Zigbee devices you want to sniff are on channel 11. This is not always the case, for example Xiaomi devices are often on channel 20. 

If using Zboss Sniffer change the right hand dropdown to your desired channel:

![image](https://user-images.githubusercontent.com/8156439/53517979-e5cf9400-3ac7-11e9-9601-1a07b899f7ce.png)

**Comment by dzungpv** [comment]
Use trial version of ubiqua sniffer and then it will automatically detect the key, after that copy to wireshark. You can try all channel from 11 to 26 one by one until it get the packet

**Comment by Koenkk** [comment]
@timdonovanuk so where did the packets come from which you were sniffing on channel 11?

**Comment by timdonovanuk** [comment]
Its possible to have more than one zigbee gateway..? Hue/Tradfri/SmartThings/Hive etc. all have zigbee hubs.
