### ISSUE TITLE
Some config can't be set via environment variables

### ISSUE THREAD

**Issue by NathanSweet** [Koenkk/zigbee2mqtt#11659]
### What happened?

I'm unable to set, for example, `mqtt.server` using `ZIGBEE2MQTT_MQTT_SERVER` or `serial.port` using `ZIGBEE2MQTT_SERIAL_PORT`.

### What did you expect to happen?

To be able to set any config setting via environment variables. Specifically the host name and port numbers are specified elsewhere and I want to pass them in. Currently I have to parse the YAML, edit it, save it, then start zigbee2mqtt.

### How to reproduce it (minimal and precise)

Eg, on Windows:
```
set ZIGBEE2MQTT_MQTT_SERVER=moo
npm start
```
Expected: zigbee2mqtt should try to connect to the MQTT broker `moo`.
Actual: zigbee2mqtt uses the `mqtt.server` specified in `configuration.yaml`.

### Zigbee2MQTT version

1.23.0-dev

### Adapter firmware version

n/a

### Adapter

n/a

**Comment by Koenkk** [comment]
`ZIGBEE2MQTT_MQTT_SERVER` should be `ZIGBEE2MQTT_CONFIG_MQTT_SERVER`

**Comment by NathanSweet** [comment]
JFC, carry on...

![](http://n4te.com/x/4156-bushes.gif)
