### ISSUE TITLE
[New device support]: Moes ZTS-EUB

### ISSUE THREAD

**Issue by ciB89** [Koenkk/zigbee2mqtt#11665]
### Link

https://de.aliexpress.com/item/1005002755082045.html

### Database entry

{"id":9,"type":"EndDevice","ieeeAddr":"0x60a423fffe3296ab","nwkAddr":56737,"manufId":4098,"manufName":"_TZE200_amp6tsvy","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_amp6tsvy","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0012023164","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0012023164","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1482240604},"lastSeen":1646173532555,"defaultSendRequestWhen":"immediate"}

### Comments

In z2m, the device is recognised as a [ZTS-EU_1gang](https://www.zigbee2mqtt.io/devices/ZTS-EU_1gang.html), which has no neutral wire. My version has an optional neutral wire (which I have attached) which should make it a router and according to the product page, binding should also be possible.

**Comment by f0gster** [comment]
I have 100% the same issue using zigbee2mqtt@1.28.1

The switch was detected as ZTS-EU_1gang, while it looks like ZS-EUB_1gang (mine has neutral wire)...

Here is record from database.db:

{"id":3,"type":"EndDevice","ieeeAddr":"0x540f57fffe37caea","nwkAddr":48409,"manufId":4098,"manufName":"_TZE200_amp6tsvy","powerSo
urce":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[
0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"{\t�*\u0013�\t�*\u0012�\t�*\u0012","65506":31,"65
508":0,"modelId":"TS0601","manufacturerName":"_TZE200_amp6tsvy","stackVersion":0,"dateCode":"","appVersion":68}}},"binds":[{"clus
ter":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bfd765","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVers
ion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1482240604},"
lastSeen":1667411820149,"defaultSendRequestWhen":"immediate"}
