### ISSUE TITLE
error when want update: '45df7312_zigbee2mqtt'

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#11666]
### What happened?

error when want update: '45df7312_zigbee2mqtt'

### What did you expect to happen?

just update

### How to reproduce it (minimal and precise)

click update

### Zigbee2MQTT version

1.23.0-1

### Adapter firmware version

0x26700700

### Adapter

con2bee

### Debug log

Failed to to call /store/addons/45df7312_zigbee2mqtt/update - '45df7312_zigbee2mqtt'
![zigb2mqt](https://user-images.githubusercontent.com/91805313/156274166-b749fed7-b9d2-4e53-b014-555df4558ad8.jpg)

**Comment by jalejandro0211** [comment]
same issue

**Comment by Koenkk** [comment]
Is it solved by uninstalling and installing the addon?
