### ISSUE TITLE
Xiaomi LLKZMK11LM is not updating energy, temperature and voltage

### ISSUE THREAD

**Issue by DJTerentjev** [Koenkk/zigbee2mqtt#11678]
### What happened?

I try both last stable (1.24.0-1) and last edge version of Z2M. Relay is updated to  9-22-2021. I tried with 2 sticks cc2538 version 20211222 with support Aqara devices and SONOFF 20220103. Both same result: LLKZMK11LM is not updating energy, temperature and voltage:
![image](https://user-images.githubusercontent.com/1267473/156387453-4d7e8d3d-c87e-4c75-bbb1-c84038b35ed2.png)
I tried to connect same module to Xiaomi gateway and got energy:
![image](https://user-images.githubusercontent.com/1267473/156389064-af2d9441-2a28-455f-813f-9b5b59384d3a.png)
Also I know at least two users wth same behavior  
I sniff the traffic between xiaomi gateway and relay module while pairing and while energy was growing.  

Could you please check this out and fix it if possible.
Please let me know if i can provide extra information

### Zigbee2MQTT version

1.24.0-1

### Adapter firmware version

20220103

### Adapter

SONOFF

### Debug log

[zigbee(pairing).pcapng.txt](https://github.com/Koenkk/zigbee2mqtt/files/8170682/zigbee.pairing.pcapng.txt)
[zigbee(energy).pcapng.txt](https://github.com/Koenkk/zigbee2mqtt/files/8170692/zigbee.energy.pcapng.txt)
[zigbee log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8170887/zigbee.log.txt)

**Comment by McGiverGim** [comment]
Look here 
https://github.com/Koenkk/zigbee2mqtt/issues/7112

**Comment by DJTerentjev** [comment]
> Look here #7112

I saw it, but that issue is closed and no solution.

**Comment by Koenkk** [comment]
@McGiverGim if I understand correctly, the code from https://github.com/Koenkk/zigbee2mqtt/issues/7112#issuecomment-1057111602 should fix this. @DJTerentjev can you confirm this?

Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/7112
