### ISSUE TITLE
Delays or slow response with SONOFF ZBMINI-L Zigbee 3.0 Smart Switch by ITead

### ISSUE THREAD

**Issue by codegourou** [Koenkk/zigbee2mqtt#11676]
### What happened?

After a few minutes/hours after pairing the ZBMINI-L start to get delay that increase with time. 

It seems that I'm not alone with the issue : 
https://community.home-assistant.io/t/sonoff-zbmini-l-zigbee-3-0-smart-switch-by-itead-works-without-neutral-wire-and-based-on-cc2652p-so-should-be-a-good-zigbee-router/384644/42

ZBMINI-L Firmware : 1.0.4

### What did you expect to happen?

A fast response (the same as just after the pairing of the device).

### How to reproduce it (minimal and precise)

- Pair the device
- Use it a few time threw home assistant or zigbee2mqtt or with the switch directly to ensure it's working properly. When used threw Homeassistant or Zigbee2mqtt : the device answer in a few ms.
- Try again after an hour (switch with zigbee)
- The device will respond after multiple seconds
- The device still work properly when activated with the physical switch button linked to it.

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20210708

### Adapter

SONOFF ZigBEE 3.0 USB Dongle Plus

**Comment by hevili** [comment]
can confirm same Problem

**Comment by Hedda** [comment]
> It seems that I'm not alone with the issue :
> https://community.home-assistant.io/t/sonoff-zbmini-l-zigbee-3-0-smart-switch-by-itead-works-without-neutral-wire-and-based-on-cc2652p-so-should-be-a-good-zigbee-router/384644/42

FYI, ITead SONOFF ZBMINI-L Zigbee 3.0 Smart Switch installs without neutral wire and is based on the CC2652P (CC2652 P1F) chip.

* https://itead.cc/product/sonoff-zbmini-l-zigbee-smart-switch-no-neutral-wire-required/
* https://sonoff.tech/product/diy-smart-switch/zbmini-l/

I don't own this device myself but there are some basic things all should try and more detailed information will also be needed:

1. We already also know from reports in https://community.home-assistant.io/t/sonoff-zbmini-l-zigbee-3-0-smart-switch-by-itead-works-without-neutral-wire-and-based-on-cc2652p-so-should-be-a-good-zigbee-router/384644/ that the ITead SONOFF ZBMINI-L is based on a Texas Instruments TI CC2652P (CC2652 P1F) MCU chip, which is also used in some of ITead's other Sonoff branded Zigbee devices like their [SONOFF S26R2ZB Zigbee Smart Plug](https://itead.cc/product/sonoff-s26r2zb-zigbee-smart-plug-uk-de-fr/) as well as the very latest shipping revision of the [SONOFF ZBMINI Zigbee Two Way Smart Switch](https://itead.cc/product/sonoff-zbmini-zigbee-smart-switch/) (which previous revisions was based on Silicon Labs EFR32MG21).
2. We also already know from reports in https://community.home-assistant.io/t/sonoff-zbmini-l-zigbee-3-0-smart-switch-by-itead-works-without-neutral-wire-and-based-on-cc2652p-so-should-be-a-good-zigbee-router/384644/ that unlike most other Sonoff branded Zigbee devices with the same TI CC2652P MCU chip the firmware shipping with ITead SONOFF ZBMINI-L is configured as a Zigbee End-Device (non-routing device) and not a Zigbee Router device config.
3. Which exact firmware version is on each and every ITead SONOFF ZBMINI-L device with this delay problem?
4. Verify that it is still a problem after update the Zigbee Coordinator adapter firmware to at least the latest from Koenkk master branch https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin or better yet to latest develop branch https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin as those contain many upstream bug fixes from Texas Instruments.
5. If possible verify that it is also the same problem in the latest Zigbee2MQTT Edge/Dev release (zigbee2mqtt-edge latest dev branch) https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html 
6. Is the the ITead SONOFF ZBMINI-L connected though a Zigbee Router device or directly to the Zigbee Coordinator? 
7. If it is connected to through a  Zigbee Router device then which exact Zigbee Router device model and firmware on that?
8. Enable Zigbee2MQTT debug logging and Zigbee-herdsman debug logging and provide debug logs https://www.zigbee2mqtt.io/guide/usage/debug.html

**Comment by raz0rf0x** [comment]
I have this device on a Conbee2 ver 0x26580700. My ZBMINI-L is being routed through one node. 
Link from coordinator to first node is 225, then from that node to the ZBMINI is 150.

There is a 5 second delay when switching this on or off remotely. Manual activation of this device causes instantaneous state change to be indicated in ZB2MQTT.

**Comment by codegourou** [comment]
I didn't talk about it, but when I activate the physical switch the state is also instantaneous. 
The delay is only when activate the switch remotely. But I experience way more than 5s on my side.

**Comment by hevili** [comment]
i am on 30+ seconds sometimes.. tried with conbee 2 in combination with both zha and zigbee2mqtt. Currently on zha but exactly the same issues here

**Comment by Hedda** [comment]
FYI, there are now some probably related tips posted about [PTVO firmware](https://ptvo.info/cc2652r1-cc2652rb-cc2652p-cc1352p2-configurable-router-firmware-748/) on other CC2652P based Sonoff branded Zigbee devices from ITead in [https://github.com/Koenkk/Z-Stack-firmware/issues/273](https://github.com/Koenkk/Z-Stack-firmware/issues/273) and [https://github.com/Koenkk/zigbee2mqtt/issues/10282](https://github.com/Koenkk/zigbee2mqtt/issues/10282)

The tip is that might be a good idea to try PTVO firmware but **select the CC2652R chip type (and not CC2652P) in the PTVO firmware configurator** to get firmware omage without power amplifier enabled.

It seems that at least some of the radio board modules in ITead's newer products look to have a design flaw/limititation/flaw with missing components needed for using  CC2652P with power amplifier enabled as per https://ptvo.info/custom-firmware-for-sonoff-zbmini-01minizb-and-ewelink-switch-zr-02-923/

So as a workaround to use PTVO firmware it is probably very likely that [selecting CC2652R chip type in the PTVO firmware configurator](https://ptvo.info/custom-firmware-for-sonoff-zbmini-01minizb-and-ewelink-switch-zr-02-923/) will result in a working firmware image on the ITead Sonoff ZBMINI-L similar to the new Sonoff ZBMINI (01MINIZB) as both use CC2652P (CC2652 P1F) chip model and their radio modules have same design flaws/limitations/optimizations?

**Comment by Hedda** [comment]
Be sure to also submit tickets to ITead/Sonoff as the manufacturer as well so they can keep statistics:

https://itead.freshdesk.com/support/home

Based on their support orginazation history ITead/Sonoff had a tendency to not react to reports of clear firmware bugs until enough people have reported the same problem, even if some in community show how to replicate issue to prove fault.

Again for reference also see → https://community.home-assistant.io/t/sonoff-zbmini-l-zigbee-3-0-smart-switch-by-itead-works-without-neutral-wire-and-based-on-cc2652p-so-should-be-a-good-zigbee-router/384644/

**Comment by Christophe999s** [comment]
Same issue here. I've logged a ticket with Sonoff and have received this response:
'For the ZBMINI-L and HA problem, it is the differences of the trigger mechcanism between HA and our ZBMINI-L.  For the problem, our technicans are trying to talk with HA about this problem, please kindly wait for the update of the HA.
And if any news, we will also let you know.'

**Comment by Hedda** [comment]
> Same issue here. I've logged a ticket with Sonoff and have received this response: 'For the ZBMINI-L and HA problem, it is the differences of the trigger mechcanism between HA and our ZBMINI-L. For the problem, our technicans are trying to talk with HA about this problem, please kindly wait for the update of the HA. And if any news, we will also let you know.'

Sounds as if their support/technicans are confusing [Zigbee2MQTT](https://www.zigbee2mqtt.io/) with the [ZHA integration for Home Assistant](https://www.home-assistant.io/integrations/zha), or?

**Comment by CaptFennec** [comment]
Same issue here.
Do you know of good alternatives?
(those where cheap and no neutral needed... sounded perfect!)

**Comment by Koenkk** [comment]
I've fixed the issue now, please check if it works after:
- updating to the latest dev (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
- repair the ZBMINI-L

**Comment by codegourou** [comment]
Hello @Koenkk ! Thanks for the fix. 

Really want to try it, but If I see it right, the commit seems not available on on Zigbee2mqtt as an Add-On for HASS. Can you Update the Zigbee2mqtt version in the Add-on dev branch ? (Zigbee2mqtt-edge)
As currently I have not other setup to test it. 
I try to have a look at how I can do that by myself, but can't find the version number of the dev package of Zigbee2mqtt to bump the Add-on version ... Not really used to GitHub and that kind of shared project :( Sorry !

**Comment by codegourou** [comment]
Hello @Koenkk ! Thanks for the fix. 

Really want to try it, but If I see it right, the commit seems not available on on Zigbee2mqtt as an Add-On for HASS. Can you Update the Zigbee2mqtt version in the Add-on dev branch ? (Zigbee2mqtt-edge)
As currently I have not other setup to test it. 
I try to have a look at how I can do that by myself, but can't find the version number of the dev package of Zigbee2mqtt to bump the Add-on version ... Not really used to GitHub and that kind of shared project :( Sorry !

**Comment by Koenkk** [comment]
@codegourou the fix is available in the edge version of the addon (uninstall and install it again to get the latest version)

**Comment by codegourou** [comment]
The issue seems fixed 🥳
The module I paired yesterday is still fast to respond. I paired the other module installed this morning. Will keep you informed of the status 🙂
As a reminder previously, only half an hour of time made the module useless. So I'm really confident !

**Comment by Koenkk** [comment]
Awesome, the problem should appear in one hour after pairing.

**Comment by codegourou** [comment]
Work as a charm ! Thanks !!!!! 
Let the automation begin :-D

**Comment by codegourou** [comment]
Work as a charm ! Thanks !!!!! 
Let the automation begin :-D

**Comment by DolceTriade** [comment]
I updated to the dev branch1.25.0-dev commit: [d90be2d](https://github.com/Koenkk/zigbee2mqtt/commit/d90be2d) and I reconfigured the device. Is that sufficient? to test? For now, there appears to be no change.

**Comment by codegourou** [comment]
You need to remove and re-pair your device(s). It still work with no latency at all on my side 👍

**Comment by codegourou** [comment]
You need to remove and re-pair your device(s). It still work with no latency at all on my side 👍

**Comment by jonmasters** [comment]
Super awesome to see the proactive fix! I'm about to install a few of these and was super pumped to see this was fixed :)

**Comment by rdorys** [comment]
Hi all, 
It seems that the same problem appears on the ZBMINI-L2. Has anyone has both models to compare?

**Comment by pernatiy** [comment]
Sorry for commenting in an year old issue, but I don't think that it worth to create a new one.

Came here from comment on [sonoff.js:62](https://github.com/Koenkk/zigbee-herdsman-converters/blame/master/devices/sonoff.js#L62). I've got fresh ZBMINIL2 switches with FW 1.0.10 and during pairing I see error
```
Failed to configure 'ZBMINIL2_MAC', attempt 1 (Error: Unbind ZBMINIL2_MAC/1 genPollCtrl from 'COORDINATOR_MAC/1' failed (Error: status: 136) at DeconzAdapter.unbind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:820:19) at Endpoint.unbind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:596:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/sonoff.js:62:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))
```
As I understood "status 136" means "nothing to unbind". The problem is that exception prevents normal device pairing completion. Is it enough just to wrap the call to `unbind` in the `try` block or some more complicated logic should be introduced?

**Comment by D3SL** [comment]
Has this been integrated into the mainline HA add-on yet? I've got both a zbminiL (firmware 1.1.1) and zbminiL2 and both have an inconsistent but always noticeable delay, even when using the physical switch.

**Comment by bushbrother** [comment]
I have a ZBMINIL2 and also notice delay when using physical switch. FW is 10.0.10. Trying to do OTA causes errors:

 2023-05-05 16:52:47 Failed to check if update available for 'Bathroom Switch' (No image available for imageType '4')

I assume that is because there simply isnt one? It is not in the OTA images on github ...

Anything else to check?

**Comment by D3SL** [comment]
I've just wired up my last two unused ZBMini-L's (firmware 1.1.1), grouping them in HA, and the lag is unreasonable. They never respond in less than a full second, very often take up to several seconds, and don't properly follow zigbee2mqtt grouping (they'll show as if they've been toggled on or off but not actually change state in real life).

**Comment by Lucas-Haux** [comment]
Bought two ZbminiL2 the other day and installed them both today. Everything went smoothly, no binding problems or anything but like others here I have a small, less than one-second delay on both HA and with the physical switch. 

It has firmware ID `1.0.14 20230505` and firmware version `4110 App: 0.0 build 0 | Stack: 1.0 build 14`. It seems like others here have a newer firmware version than me even tho 2mqtt says it's the latest. 

Any help would be greatly appreciated, but I might just buy a different no neutral device
