### ISSUE TITLE
ZSDR-850 Smoke Detector from Klik Aan Klik Uit (Trust) 

### ISSUE THREAD

**Issue by guidokieboom** [Koenkk/zigbee2mqtt#11687]
### Link

https://www.trust.com/en/product/71197-zigbee-smoke-detector-zsdr-850#

### Database entry

{"id":12,"type":"EndDevice","ieeeAddr":"0x000d6f00162c242d","nwkAddr":41663,"manufId":4619,"manufName":"Trust","powerSource":"Battery","modelId":"SmokeSensor-EM","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,1282],"outClusterList":[25],"clusters":{"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff0810d3","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":21,"stackVersion":2,"hwVersion":16,"dateCode":"2020.10.14","swBuildId":"1.1.1","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1646292224377,"defaultSendRequestWhen":"immediate"}

### Comments

Smoke detector paired successfully. However, it is seen as a HEIMAN HS3SA, where I consider this more a HEIMAN HS1SA. I've seen similar issues in https://github.com/Koenkk/zigbee2mqtt/issues/9919. I have the latest Z2M (1.24.0) installed. I'm using a ConbeeII zigbee router (not using ZHA, nor the Conbee/Deconz interface; just directly the Z2M). Multiple screenshots see below. Request is to add this ZSDR-850 device to the devices list.

After successful pairing and device rename:
<img width="602" alt="Screenshot 2022-03-03 at 08 59 24" src="https://user-images.githubusercontent.com/65387179/156521745-aa4fc00a-f2a8-4892-aed3-be606bea925a.png">

State info:
<img width="327" alt="Screenshot 2022-03-03 at 09 00 56" src="https://user-images.githubusercontent.com/65387179/156522340-f1526d86-d251-46da-991b-740c5bfa0cfc.png">

Debug log around a device self-test:
<img width="833" alt="Screenshot 2022-03-03 at 09 07 07" src="https://user-images.githubusercontent.com/65387179/156522975-8a5162db-94c0-4305-8970-b077d55bf99a.png">

Picture of the ZSDR-850 device:
<img width="391" alt="Screenshot 2022-03-03 at 08 57 26" src="https://user-images.githubusercontent.com/65387179/156521445-3c92989c-a2bf-4fc6-9adc-f7fd126897de.png">

**Comment by Katamave** [comment]
I have the same problem.

**Comment by leoGr3006** [comment]
I'm a starter and like to connect this device (ZSDR-850) to my Aeotec Smartthings hub but can't find the handler (GitHub and included drivers)
Thanks for your help.
