### ISSUE TITLE
Problems starting zigbee2mqtt

### ISSUE THREAD

**Issue by doppiej** [Koenkk/zigbee2mqtt#1168]
Hello,

I am having problems with starting zigbee2mqtt.
After running npm start I am receiving this. What am I doing wrong?

Output: [https://pastebin.com/XYXwDPBN](https://pastebin.com/XYXwDPBN)
This is my config file: [https://pastebin.com/3fDvq4Du](https://pastebin.com/3fDvq4Du)

**Comment by Koenkk** [comment]
Did you make any changes to `zigbee-shepherd-converters`?

**Comment by doppiej** [comment]
No, I am still trying to set zigbee2mqtt up! However I can't get it to work unfortunately.

**Comment by Koenkk** [comment]
What instructions did you follow?

**Comment by doppiej** [comment]
Yours, on https://www.zigbee2mqtt.io/

**Comment by Koenkk** [comment]
Can you do:

```bash
rm -rf node_modules
npm install
```

**Comment by doppiej** [comment]
I tried. Same issue.
This is the npm log, maybe something you could use: [https://pastebin.com/Cc89r5Yh](https://pastebin.com/Cc89r5Yh)

**Comment by Koenkk** [comment]
What is the output of 

`cat node_modules/zigbee-shepherd-converters/index.js` 

and 

`cat node_modules/zigbee-shepherd-converters/converters/toZigbee.js`

**Comment by doppiej** [comment]
Both are shown here: [https://pastebin.com/aAUqHDpQ](https://pastebin.com/aAUqHDpQ)

**Comment by Koenkk** [comment]
What is the output of `npm ls zigbee-shepherd-converters` (your `index.js` is from an old version).

**Comment by doppiej** [comment]
Shown here: [https://pastebin.com/bQ6du4jh](https://pastebin.com/bQ6du4jh)
Do I need to make an update?

**Comment by Koenkk** [comment]
What is the output of:

```bash
rm -rf node_modules
npm install
```

**Comment by doppiej** [comment]
Shown here: [https://pastebin.com/zySU5t73](https://pastebin.com/zySU5t73)

**Comment by Koenkk** [comment]
What is the output of `git status` and `git diff`?

**Comment by doppiej** [comment]
Shown here: [https://pastebin.com/k0SCvbMK](https://pastebin.com/k0SCvbMK)

**Comment by doppiej** [comment]
I guess I copied not all from `git diff`: [https://pastebin.com/QSamiVbz](https://pastebin.com/QSamiVbz)

**Comment by Koenkk** [comment]
Can you update npm to the latest version and try again?

```bash
sudo npm install -g npm
rm -rf node_modules
npm install
npm start
```

**Comment by doppiej** [comment]
This is the response: [https://pastebin.com/YUjqZn2T](https://pastebin.com/YUjqZn2T)
However the 3rd command wasn't in the original reply I guess, so I missed it. Should I still perform it now?

**Comment by Koenkk** [comment]
Looks good! Seem that your original problem has been solved now. 

Some other process is locking your sniffer, verify that the path to the sniffer in `configuration.yaml` is correct and try rebooting the system.

**Comment by RobertTheLink** [comment]
my responses of 
`rm -rf node_modules`
`npm install`
`npm start`
reboot of RasPi
`npm start`. ( did not change anything)
 are here: https://pastebin.com/RP1kTwKz

unfortunately this did not yet help

**Comment by Koenkk** [comment]
`Error: Connection refused: Not authorized`

Did you set-up a MQTT server with a password? You need to add that to `configuration.yaml` (http://www.zigbee2mqtt.io/configuration/configuration.html)

**Comment by doppiej** [comment]
> Looks good! Seem that your original problem has been solved now.
> 
> Some other process is locking your sniffer, verify that the path to the sniffer in `configuration.yaml` is correct and try rebooting the system.

I tried the reboot and it looks promising.
However, when performing the showing of the status I am getting this:
pi@RP-Domoticz:~$ systemctl status zigbee2mqtt.service
● zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled)
   Active: active (running) since Wed 2019-03-06 20:00:58 CET; 15h ago
 Main PID: 606 (npm)
   CGroup: /system.slice/zigbee2mqtt.service
           ├─606 npm
           ├─954 sh -c node index.js
           └─956 node index.js

Instead of what you show in the documentation:
pi@raspberry:/opt/zigbee2mqtt $ systemctl status zigbee2mqtt.service
● zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-06-07 20:27:22 BST; 3s ago
 Main PID: 665 (npm)
   CGroup: /system.slice/zigbee2mqtt.service
           ├─665 npm
           ├─678 sh -c node index.js
           └─679 node index.js

Jun 07 20:27:22 raspberry systemd[1]: Started zigbee2mqtt.
Jun 07 20:27:23 raspberry npm[665]: > zigbee2mqtt@0.1.0 start /opt/zigbee2mqtt
Jun 07 20:27:23 raspberry npm[665]: > node index.js
Jun 07 20:27:24 raspberry npm[665]: 2018-6-7 20:27:24 INFO Starting zigbee-shepherd
Jun 07 20:27:25 raspberry npm[665]: 2018-6-7 20:27:25 INFO zigbee-shepherd started

**Comment by Koenkk** [comment]
@doppiej did zigbee2mqtt start? You can find the logging in `data/log`.

**Comment by doppiej** [comment]
Hmm, I guess not. It looks like it only shows logs of when I performed the `npm start` commands...
However, I also performed all the steps mentioned in "Running as a daemon with systemctl" and when I show the status it says that it is active and running.
So what am I doing wrong?

**Comment by RobertTheLink** [comment]
Thx Koenkk,
it's working for me now. Mosquitto was starting manually, but failing to start as service, and therefore was off after reboot.
