### ISSUE TITLE
[New device support]: Aqara Feeder C1

### ISSUE THREAD

**Issue by SPRZZZ** [Koenkk/zigbee2mqtt#11692]
### Link

https://www.aqara.com/cn/productDetail/Aqara-Pet-Feeder-C1

### Database entry

{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0024c2413a","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterLis

### Comments

Thanks to z2m for supporting so many zigbee devices, it brings me a lot of convenience, my new device is aqara c1 feeder, I found that it can't get z2m adapt, I can't find the same type of products in z2m .

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['aqara.feeder.acn001'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'WSDCGQ01LM', // Vendor model number, look on the device for a model number
    vendor: 'Aqara', // Vendor of the device (only used for documentation and startup logging)
    description: 'Aqara pet feeder', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.aqara_opple_on, fz.aqara_opple_off, fz.battery, fz.aqara_opple], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.action(), e.switch(), e.battery()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by rchiileea** [comment]
will this be added soon?

**Comment by rchiileea** [comment]
I pulled this from the the device if its of any help 

button order from left to right

first button

debug 2022-08-16 10:49:20: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'genBasic', data '{"appVersion":33,"modelId":"aqara.feeder.acn001"}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:20: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:20: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug 2022-08-16 10:49:21: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[5,33,29,0,13,35,33,37,0,0,9,33,0,16],"type":"Buffer"}}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:21: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:21: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

second button (feed)

debug 2022-08-16 10:49:37: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'aqaraOpple', data '{"65521":{"data":[0,5,83,4,21,2,188,4,48,49,48,49],"type":"Buffer"}}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:37: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:37: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug 2022-08-16 10:49:37: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'aqaraOpple', data '{"65521":{"data":[0,5,84,13,104,0,85,2,0,4],"type":"Buffer"}}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:37: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:37: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug 2022-08-16 10:49:37: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'aqaraOpple', data '{"65521":{"data":[0,5,85,13,105,0,85,4,0,0,0,32],"type":"Buffer"}}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:37: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:37: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
debug 2022-08-16 10:49:37: Received Zigbee message from '0x54ef441000458b29', type 'attributeReport', cluster 'aqaraOpple', data '{"65521":{"data":[0,5,86,13,11,0,85,1,0],"type":"Buffer"}}' from endpoint 1 with groupID null
warn  2022-08-16 10:49:37: Received message from unsupported device with Zigbee model 'aqara.feeder.acn001' and manufacturer name 'undefined'
warn  2022-08-16 10:49:37: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

3rd button no response

**Comment by rchiileea** [comment]
Just to Add to this the 1st button is a reset button so not needed, the second is the important feed button and 3rd is just for voice recording.

**Comment by MichaelMure** [comment]
Maybe open a PR to https://github.com/Koenkk/zigbee-herdsman-converters ?

**Comment by Koenkk** [comment]
Being worked on in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4775
