### ISSUE TITLE
[Feature request]: Please add YALE YMF30 with device model "0600000001"

### ISSUE THREAD

**Issue by GuidoKJ** [Koenkk/zigbee2mqtt#11718]
### Is your feature request related to a problem? Please describe

Yale YMF30 sometimes reports itself as "iZBModule01" and also "0600000001". Configuration is the same as YMF40 (https://www.zigbee2mqtt.io/devices/YMF40_YDM4109+.html) despite the lock does not have a fingerprint reader. The exact model is https://www.yalelatinoamerica.com/es/productos-digitales-yale/cerraduras-digitales-seguridad/cerraduras-digitales-tarjeta/ymf30/.

### Describe the solution you'd like

Add to the Yale YMF40 device category another lock which is Yale YMF30 with the device model "0600000001" https://www.zigbee2mqtt.io/devices/YMF40_YDM4109+.html

### Describe alternatives you've considered

I modified zigbee DB in order to show the lock as one of the supported ones but it is better if it is included for everybody with the correct device model.

### Additional context

None.

**Comment by Koenkk** [comment]
added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
