### ISSUE TITLE
Group and Color Temp

### ISSUE THREAD

**Issue by UweLoyal** [Koenkk/zigbee2mqtt#11714]
### What happened?

Changing Color Temp generates a Warning:
unread colortemp change for group members ["0xXXXXXX1","0xXXXXXX2","0xXXXXXX3","0xXXXXXX4","0xXXXXXX5"]
The Lanps in Group are Lidl HG06106A

### What did you expect to happen?

I think the numberrage of Color Temp is not identical.
Group 200-9000
Lamp 150-500

### How to reproduce it (minimal and precise)

with Groupslider or value in Object

### Zigbee2MQTT version

2-1.2.7.1.

### Adapter firmware version

20210708

### Adapter

ioBroker ZigBee 1.6.16

**Comment by Koenkk** [comment]
Please create issues related to iobroker.zigbee here; https://github.com/ioBroker/ioBroker.zigbee/issues
