### ISSUE TITLE
Clean install HA, restoring backup of Z2M only, will this re-populate HA with all entities again?

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee2mqtt#11721]
Hi @Koenkk 

Just a practical question; if I decide to re-install HA with a clean install, and do a manual restore of the previous `zigbee2mqtt` directory, will the database of entities automatically re-populate on HA?

- Home Assistant OS
- Z2M Addon

**Comment by Koenkk** [comment]
Yes!
