### ISSUE TITLE
Huge delays and intermittent operation, started today

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#11736]
### What happened?

No issues for 3 years, since today, huge delays (like 5-10s), missed Zigbee button presses (but all devices do work eventually). At least 50 % of all zigbee button presses are missed, probably more like 80 %. Various Aqara buttons that have been working flawlessly for three years. All of them exhibit the issue all of a sudden.

LQI/signal is fine, 50-135. I DO use a USB extension cable. 

Updating the coordinator FW did not fix the issue.
Disabling Amazon Sidewalk (uses 900Mhz like Zigbee and BLE) did look promising but ultimately didn't fix the issue.

Creating Zigbee Map results in lots of "Failed to execute LQI" even for devices right next to the CB2652 stick.

### How to reproduce it (minimal and precise)

All Zigbee operation is affected.

### Zigbee2MQTT version

 1.24.0-1. Edge as well.

### Adapter firmware version

20210120

### Adapter

Slaeh.sh CC2652RB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8193248/log.txt)

**Comment by Sku1ly** [comment]
Huge delay? Mine just took 4 hours to respond! :(

**Comment by Stooovie** [comment]
On the missed button presses, I only see this in the log:
`Debug Received Zigbee message from 'Xiaomi Button Bed', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0`

the actual payload is and MQTT PUBLISH is totally missing

**Comment by Stooovie** [comment]
Also the map now looks like this, which is super weird and not at all how it looked before
![Snímek obrazovky 2022-03-07 001523](https://user-images.githubusercontent.com/10572373/156946507-357902ad-6809-407c-8aa2-69d43a960f00.png)
.

**Comment by Stooovie** [comment]
It looks like the Slaeh.sh stick has failed, I have swapped in the old CC2531 and it all just works again. Thanks!

**Comment by Stooovie** [comment]
No, not hardware problem. The CC2531 is starting to flake out too. It's unlikely that two Zigbee sticks would fail at the same time. Any tips? Thanks!

**Comment by Stooovie** [comment]
To add to my own comments for posterity - is it possible that **Amazon Sidewalk** that got turned ON by an Echo device reset is the culprit? It does use the same frequency of 900MHz (BLE does too)... Too early to tell but after turning it off, it seems my network is stable again.

**Comment by Stooovie** [comment]
The problem is gone, fine for three days... I can't make any sense of it.
