### ISSUE TITLE
[New device support]: Iluminize 511.544 Zigbee 3.0 wall dimmer RGBW 4 zone ZGRC-TEUR-001

### ISSUE THREAD

**Issue by dzerrenner** [Koenkk/zigbee2mqtt#11748]
### Link

https://www.iluminize.com/de/shop/led-steuerung/wand-dimmer/product/499-511-544-zigbee-wand-dimmer-schalter-rgb-rgbw-rgbws-led-4z.html

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0x000d6f001668b890","nwkAddr":18407,"manufId":4644,"manufName":"iluminize","powerSource":"Mains (single phase)","modelId":"ZGRC-TEUR-001","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":261,"inClusterList":[0,3,2821,4096],"outClusterList":[3,4,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"modelId":"ZGRC-TEUR-001","manufacturerName":"iluminize","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.3.1_r28"}},"genOnOff":{"attributes":{}},"lightingColorCtrl":{"attributes":{}},"genLevelCtrl":{"attributes":{}},"genIdentify":{"attributes":{"identifyTime":0}},"genOnOffSwitchCfg":{"attributes":{}},"genGroups":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":261,"inClusterList":[0,3,2821,4096],"outClusterList":[3,4,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":261,"inClusterList":[0,3,2821,4096],"outClusterList":[3,4,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":261,"inClusterList":[0,3,2821,4096],"outClusterList":[3,4,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.3.1_r28","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1646664689137,"defaultSendRequestWhen":"immediate"}

### Comments

The device is a 4 zone version of ZGRC-TEUR-002 / model 511.541, which is supported. Copying th config does not work, because it is a multi endpoint device (see external converter file, `meta: {multiEndpoint: true}`.

I'm a bit lost on the following converter:
```
debug 2022-03-07 16:27:31: Received Zigbee message from 'RGB-Regler', type 'commandMoveWithOnOff', cluster 'genLevelCtrl', data '{"movemode":0,"rate":50}' from endpoint 1 with groupID 59137
debug 2022-03-07 16:27:31: No converter available for '511.544' with cluster 'genLevelCtrl' and type 'commandMoveWithOnOff' and data '{"movemode":0,"rate":50}'
```
I don't know what to do with that. `commandMoveWithOnOff` seems to need a converter of some sort.

In addition, the device requests an OTA. Is there a way to enable this? I'm not seeing it at the OTA page on the frontend.

I'll publish the full doc / configuration / etc via PR when i'm done, but i need some help with this issue.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZGRC-TEUR-001'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '511.544', // Vendor model number, look on the device for a model number
    vendor: 'Iluminize', // Vendor of the device (only used for documentation and startup logging)
    description: 'Zigbee 3.0 wall dimmer RGBW 4 zone', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [ 
        fz.command_move_to_color, fz.command_move_hue, fz.command_on, fz.command_off
    ],
    toZigbee: [],
    exposes: [e.action([
            'color_move', 'color_temperature_move', 'hue_move', 'hue_stop', 'brightness_step_up', 'brightness_step_down',
            'recall_*', 'on', 'off'])],  // copied from: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/iluminize.js, ZG2819S-RGBW
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {ep1: 1, ep2: 2, ep3: 3, ep4: 4};
    },	
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
For `commandMoveWithOnOff` you can re-use `fz.command_move`

**Comment by dzerrenner** [comment]
Thanks! This seems to work. This is the new externale converte file:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZGRC-TEUR-001'],
    model: '511.544',
    vendor: 'Iluminize',
    description: 'Zigbee 3.0 wall dimmer RGBW 4 zone',
    fromZigbee: [
        fz.command_move_to_color, fz.command_move_hue, fz.command_on, fz.command_off, fz.command_move
    ],
    toZigbee: [],
    exposes: [e.action([
            'color_move', 'color_temperature_move', 'hue_move',
        'hue_stop', 'brightness_step_up', 'brightness_step_down',
            'recall_*', 'on', 'off'])],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {ep1: 1, ep2: 2, ep3: 3, ep4: 4};
    },
};

module.exports = definition;
```

I'm not sure about the exposes section, I just copied it from the single zone version.
