### ISSUE TITLE
[Feature request]: Woox R7060 Garden irrigation control Battery Level

### ISSUE THREAD

**Issue by RenePhilipse** [Koenkk/zigbee2mqtt#11751]
### Is your feature request related to a problem? Please describe

The Woox R7060 Garden irrigation control is supported in zigbee2mqtt, but only for switching it on or off. The device is reporting a battery level, but is is not viewable via zigbee2mqtt.

### Describe the solution you'd like

I like to see the status of the battery of my Woox garden irrigation control in zigbee2mqtt and, even better, in Home Assistant.

### Describe alternatives you've considered

I already tried some things myself, but I do not know where to start exactly. Already posted a discussion (#9826) to help get me started, but it got no responses.

### Additional context

See discussion topic #9826.

**Comment by Koenkk** [comment]
Added this.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by RenePhilipse** [comment]
Wow! That’s fast! Thanks and I will have a look at it.

**Comment by RenePhilipse** [comment]
Hi @Koenkk I've checked the solution using the DEV branch, and I can confirm that the Battery Level is indeed reported and visible now! Great! Thank you very much for your quick support! Kind Regards, Rene.

**Comment by Remko76** [comment]
I am using the Dev branch as well, but do not get the battery level. It only shows "N/A" or "NULL". Is there anything I am missing, or do I need to unlink the device from the network and repair it?

![image](https://user-images.githubusercontent.com/75678314/162167140-303895ef-1312-4b9c-b7c4-18b2136a9e42.png)

**Comment by RenePhilipse** [comment]
@Remko76 
It is already in the latest production branch at the moment. It works fine at my side. Maybe remove and re-add the device?
![3E61DE74-BE2A-43F4-AB99-39BD9CB8BC7E](https://user-images.githubusercontent.com/17746965/162250097-9000c46f-20aa-4151-821e-7f31a8454c47.jpeg)

**Comment by RenePhilipse** [comment]
It can take some time to get the values filled in for the first time. Has to do with the fact that it are battery operated devices that do not communicate that often to save power. Maybe wait for 24 hours to be sure?

**Comment by Remko76** [comment]
I did get strange warnings in the log, I do not know if that means anything though (long time HASS user, but pretty new to Zigbee, actually my first Zigbee device...)

```
Warning zigbee-herdsman-converters:WooxR7060: Unrecognized DP #107 with data {"dp":107,"datatype":4,"data":{"type":"Buffer","data":[0]}}
Warning zigbee-herdsman-converters:WooxR7060: Unrecognized DP #106 with data {"dp":106,"datatype":3,"data":{"type":"Buffer","data":[48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48]}}
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"oq2ab-4"}'
```

**Comment by RenePhilipse** [comment]
That technical log is also to technical for me, but maybe @Koenkk can tell if that could be an issue.

**Comment by helepeut** [comment]
Hi, same for me here, I was waiting for the battery control for the woox irrigation in the production release, but nothing since the beginning of the week :(

**Comment by floow77** [comment]
@Koenkk hello, do you know when this fix will be in production release ? Thanks

**Comment by Koenkk** [comment]
This is in 1.25.0, but if it doesn't work lets continue in https://github.com/Koenkk/zigbee2mqtt/issues/12163

**Comment by floow77** [comment]
Yes it doesn't work in 1.25.0.1.
If I understand well, it'necessary to have a tuya gateway ?

**Comment by floow77** [comment]
Ok but this gateway is necessary to retrieve %batterie or using the edge branch is enough ?

**Comment by jjaviercs** [comment]
Updated zigbee2mqtt to version 1.27 to test... I had backup but I lost all devices and problem persist, not solve.

**Comment by acaonweb** [comment]
#13649
