### ISSUE TITLE
Xiaomi Plug Read Power Usage

### ISSUE THREAD

**Issue by soloam** [Koenkk/zigbee2mqtt#1175]
Hello, the report time of the power usage of the Xiaomi plug is to slow... Is it possible to pull the data from the plug?

Thank You

**Comment by Koenkk** [comment]
Please make the following changes: https://github.com/Koenkk/zigbee-shepherd-converters/commit/b363df9285647eb4a301c4ab6a2c2a74802680a1  and send to `zigbee2mqtt/[DEVICE_FRIENDLY_NAME/get` payload: `{"power": ""}`
