### ISSUE TITLE
[New device support]: Aubess Tuya Smart Plug (ZT2S)

### ISSUE THREAD

**Issue by KrX3D** [Koenkk/zigbee2mqtt#11761]
### Link

https://www.aliexpress.com/item/1005003749369777.html?spm=a2g0o.order_list.0.0.21ef180229sYcF

### Database entry

/

### Comments

Hello,

i got a zigbee smart plug which i could not connect. i tried the dev branch but still no luck. it shows up like this:

![image](https://user-images.githubusercontent.com/18599852/157260730-8018984d-e043-4dfa-af9b-95f22c724a9f.png)

my version (switched back from dev branch) :

![image](https://user-images.githubusercontent.com/18599852/157261255-462e3b04-b838-4363-9e86-d17eef34e557.png)

i tried to create an external converter but im not sure how to do it right even with the how to.

i opened the device up and the chip says ZT2S

![20220308_152930](https://user-images.githubusercontent.com/18599852/157261407-30f4c101-6312-470d-8430-d766f10925cb.jpg)
![20220308_152940](https://user-images.githubusercontent.com/18599852/157261442-cc2fd174-8068-4cbf-808a-311ea9735978.jpg)
![20220308_153009](https://user-images.githubusercontent.com/18599852/157261459-77eda26e-6078-4596-be69-8faa3421c65a.jpg)
![20220308_153053](https://user-images.githubusercontent.com/18599852/157261488-a9915d0c-15ee-4235-a797-84f795c95747.jpg)
![20220308_153111](https://user-images.githubusercontent.com/18599852/157261521-82564b40-bf4f-4d54-9ee6-f13f53881b3c.jpg)
![20220308_153157](https://user-images.githubusercontent.com/18599852/157261543-fa9dc182-5442-4885-92f0-d1cacb984ce6.jpg)

hopefully someonce can help me.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'ZT2S',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_c88teujp'
        },
    ],
    model: 'ZT2S-Zigbee',
    vendor: 'Aubess',
    description: 'EU Plug',
    fromZigbee: [
        fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
        fz.tuya_data_point_dump, // This is a debug converter, it will be described in the next part
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        // Here you should put all functionality that your device exposes
    ],
};

module.exports = definition;
```

**Comment by KrX3D** [comment]
ok nevermind, i got some problems with connecting devices to my network. now it works.

Zigbee Modell
TS011F
Zigbee Hersteller
_TZ3000_typdpbpg

**Comment by joggs** [comment]
So you still have to use the converter to get it working? or did it work without converter when you fixed the joining for your network?
