### ISSUE TITLE
[New device support]: SLV GU10 ES111 LED light bulb VALETO

### ISSUE THREAD

**Issue by kalbfuss** [Koenkk/zigbee2mqtt#11765]
### Link

https://www.amazon.de/gp/product/B07KSFLM1F/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0x00158d000507f397","nwkAddr":23757,"manufId":4608,"manufName":"SLV","powerSource":"Mains (single phase)","modelId":"ZBT-RGBWLight-AR0844","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":556}},"genBasic":{"attributes":{"zclVersion":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190123-27","swBuildId":"2.2","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1646770324267,"defaultSendRequestWhen":"immediate"}

### Comments

I have used the standard template for smart light bulbs and it seems to work out of the box.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBT-RGBWLight-AR0844'],
    model: 'ZBT-RGBWLight-AR0844',
    vendor: 'SLV',
    description: 'SLV GU10 ES111 LED-Leuchtmittel VALETO',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color(),
};
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":556}

**Comment by Koenkk** [comment]
added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
