### ISSUE TITLE
Hue dimmer switch : PM Failed to configure

### ISSUE THREAD

**Issue by Bastiencc** [Koenkk/zigbee2mqtt#1177]
Hey.

My hue dimmer switches are paired and works great.
But when I restart zigbee2mqtt I get this (it's not always the same switch that have error) : 

`
Mar 02 16:19:40 raspberrypi npm[5510]:   zigbee2mqtt:error 3/2/2019, 4:19:40 PM Failed to configure hue_switch_2 (0x0017880104af5115) ('undefined')
Mar 02 16:19:40 raspberrypi npm[5510]:   zigbee2mqtt:error 3/2/2019, 4:19:40 PM Failed to configure hue_switch_3 (0x001788010408bb63) ('undefined')
Mar 02 16:19:40 raspberrypi npm[5510]:   zigbee2mqtt:error 3/2/2019, 4:19:40 PM Failed to configure hue_switch_1 (0x001788010408cda7) ('undefined')
`

What do I need to do ?

**Comment by Koenkk** [comment]
This fails because the device is sleeping, not a problem as it only has to succeeds once (it has if it is working).

Logging has already been adapted in the dev branch to prevent confusion

**Comment by Bastiencc** [comment]
Ok great, thanks for your answer ! And also, thanks for your great work !!!
