### ISSUE TITLE
SEA802-Zigbee Local Temperatur calibration error

### ISSUE THREAD

**Issue by gomble** [Koenkk/zigbee2mqtt#11777]
### What happened?

I am getting following error:

Logger: homeassistant.components.mqtt.number
Source: components/mqtt/number.py:191
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 23:20:05 (16 occurrences)
Last logged: 23:45:21

Invalid value for number.thermostat_esszimmer_local_temperature_calibration: -32.0 (range -30.0 - 30.0)
Invalid value for number.thermostat_esszimmer_local_temperature_calibration: -33.0 (range -30.0 - 30.0)

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
Try setting the local_temperature_calibration once via the frontend (so it comes in the -30 till 30 range)

**Comment by gomble** [comment]
> Try setting the local_temperature_calibration once via the frontend (so it comes in the -30 till 30 range)

the problem is that i can only go -6 to 6 celsius if i go more then -6 or 6 then the temperature does not change.
But the slider on the frontend goes from -30 to 30 
Also some automatisations in homeassistant do not work to sync the trv with temperature sensor

**Comment by Koenkk** [comment]
Changed the limits to -6 - 6 now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by gomble** [comment]
Okay one more info the calibration does not work for numbers with decimal
This does not change the temperature:
![image](https://user-images.githubusercontent.com/6769445/157902444-695f97ce-b4e1-49cb-834e-6f103be1fed4.png)
But this is working:
![image](https://user-images.githubusercontent.com/6769445/157902542-b501cf15-9d92-4f05-8bc9-8ab57801c970.png)

Possible numbers are:
-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6

I will test it in the dev branch

**Comment by Koenkk** [comment]
@gomble also updated the step size.

**Comment by gomble** [comment]
Hey that worked 
![image](https://user-images.githubusercontent.com/6769445/158082800-3c496bc4-d4d4-42e2-85a1-25e0ec2c3745.png)

**Comment by gomble** [comment]
when this will be merged to a release ?

**Comment by ItsMisterP** [comment]
Hey @gomble do you investigate, why this aint work with decimals?
Regards
Philip

**Comment by gomble** [comment]
> Hey @gomble do you investigate, why this aint work with decimals?
> 
> Regards
> 
> Philip

Yes it was fixed in the next release
But you can only calibrate from -10 to 10

**Comment by ewolf29** [comment]
Are we certain that decimal step sizes are not supported by the device? Decimal number calibration does actually not make any sense in this case. 

I would volunteer to test it if it gets changed on the dev branch.
