### ISSUE TITLE
LELLKI JZ-ZB-001 "power_outage_memory" not supported

### ISSUE THREAD

**Issue by NeuerUser** [Koenkk/zigbee2mqtt#11771]
### What happened?

Bought two of these smart plugs from LELLKI. 

Zigbee Modell:   JZ-ZB-001
Zigbee Hersteller:   LELLKI
Firmware: 2.0.1 (20211016)

Pairing and interview successful. Switch can be turned on/off successfully. Setting "power_outage_memory" however gives:

`Publish 'set' 'power_outage_memory' to '0xa4c13801ed661ed3' failed: 'Error: Write 0xa4c13801ed661ed3/1 genOnOff({"32770":{"value":1,"type":48}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

### What did you expect to happen?

No error message, but a success message. :-)

### How to reproduce it (minimal and precise)

Insert the plug, pair it, goto Details page and try to set any "power_outage_memory" option.

### Zigbee2MQTT version

1.23.0-dev commit: afe94a7

### Adapter firmware version

20211219

### Adapter

zStack3x0 zigStarGW

**Comment by mashiahd** [comment]
@NeuerUser found a fix?
i have it too
