### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by aceindy** [Koenkk/zigbee2mqtt#11786]
### Link

https://phoscon.de/en/conbee2

### Database entry

{"id":1,"type":"Coordinator","ieeeAddr":"0x00212effff07faaa","nwkAddr":0,"manufId":4405,"epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[0,10,25],"outClusterList":[1,32,1280],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":100,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null,"defaultSendRequestWhen":"immediate"}

### Comments

On my previous C2531 I used TCP with
serial:
port: tcp://192.168.101.8:5001

However, on the Conbee this doesn't seem to work...
Zigbee2MQTT:info 2022-02-25 09:40:49: Starting Zigbee2MQTT version 1.18.1 (commit https://github.com/Koenkk/zigbee2mqtt/pull/1.18.1)
Zigbee2MQTT:info 2022-02-25 09:40:49: Starting zigbee-herdsman (0.13.71)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-02-25 09:41:00: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-02-25 09:41:00: Failed to start zigbee
Zigbee2MQTT:error 2022-02-25 09:41:00: Exiting...
Zigbee2MQTT:error 2022-02-25 09:41:00: undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: node index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-02-25T08_41_00_091Z-debug.log

Also adding 
adapter: deconz
doesn't help

Any ideas?

(I am forced to run Zigbee2MQTT now on Node.js on my w10 machine, but I'd rather run it as HA AddOn ;)

**Comment by Koenkk** [comment]
Adapter over socket is not supported for the Conbee
