### ISSUE TITLE
Zigbee model 'LTA012' and manufacturer name 'Signify Netherlands B.V.' is NOT supported

### ISSUE THREAD

**Issue by gregjwinter** [Koenkk/zigbee2mqtt#11794]
### What happened?

When trying to pair I get this message: 
Zigbee2MQTT:debug 2022-03-10 17:14:17: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2022-03-10 17:14:17: Successfully interviewed '0x001788010bb0fd72', device has successfully been paired
Zigbee2MQTT:warn  2022-03-10 17:14:17: Device '0x001788010bb0fd72' with Zigbee model 'LTA012' and manufacturer name 'Signify Netherlands B.V.' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:info  2022-03-10 17:14:17: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001788010bb0fd72","ieee_address":"0x001788010bb0fd72","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:info  2022-03-10 17:14:17: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x001788010bb0fd72","supported":false},"type":"pairing"}'

### What did you expect to happen?

New Philips Hue White Ambiance 1600 does not pair.  Model number is: 9290024720.  Expected to come right up like all my Hue devices.

### How to reproduce it (minimal and precise)

Reset the lamp to factory default.  Plug it in right next to adapter and hit pair devices button.  It sees it just fine but gives me this error: Zigbee model 'LTA012' and manufacturer name 'Signify Netherlands B.V.' is NOT supported

### Zigbee2MQTT version

1.24.0-dev commit: 8f98a2f

### Adapter firmware version

20211217

### Adapter

zStack3x0

### Debug log

Zigbee2MQTT:debug 2022-03-10 17:14:17: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2022-03-10 17:14:17: Successfully interviewed '0x001788010bb0fd72', device has successfully been paired
Zigbee2MQTT:warn  2022-03-10 17:14:17: Device '0x001788010bb0fd72' with Zigbee model 'LTA012' and manufacturer name 'Signify Netherlands B.V.' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:info  2022-03-10 17:14:17: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001788010bb0fd72","ieee_address":"0x001788010bb0fd72","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:info  2022-03-10 17:14:17: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x001788010bb0fd72","supported":false},"type":"pairing"}'

**Comment by Koenkk** [comment]
9290024720/LTA012 is not supported yet, please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=new+device+support&template=new_device_support.yaml&title=%5BNew+device+support%5D%3A+
