### ISSUE TITLE
Can this system work with a zigbee usb

### ISSUE THREAD

**Issue by marc-gist** [Koenkk/zigbee2mqtt#118]
Can zigbee2mqtt work with say ELELABS ZIGBEE, or Linear HUSBZB-1, etc?

Thanks,

**Comment by ciotlosm** [comment]
Unfortunately not. Only TI chips like CC2530/2531

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/101 also
