### ISSUE TITLE
Poor linkquality (range) of CC2530 + CC2591 

### ISSUE THREAD

**Issue by celeroll** [Koenkk/zigbee2mqtt#1180]
Based on the instructions [here](https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html) I have bought from Aliexpress this [part](https://www.aliexpress.com/item/ZigBee-Conversion-Serial-port-TTL-uart-Wireless-PA-Module-CC2530-CC2591/32868797542.html).

I have a CC2351 as a coordinator with a firmware from last year. 
Today I flashed CC2530 with the newest router firmware from [here](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2530_CC2591/bin). 
I was able to pair the router with my existing network, but the linkquality of the new router (CC2530 + CC2591 ) is very poor. It is sitting 1 meter away from the coordinator and linkquality is about 20. 

What is the issue here?

**Comment by pcb1962** [comment]
Not an answer to your question celeroll, but I wouldn't worry too much about linkquality, I have sensors which report linkquality in single digits, even zero, yet I still receive all the data I need from them. I have repeaters (Tradfri outlets) situated just meters form the sensors which the networkmap shows as not being used but I suspect that they are. Perhaps the linkquality reported is direct to the coordinator but the actual data transmission is via the router.
