### ISSUE TITLE
color_temp_startup Error for https://www.zigbee2mqtt.io/devices/TS0505B.html#tuya-ts0505b

### ISSUE THREAD

**Issue by acaonweb** [Koenkk/zigbee2mqtt#11812]
### What happened?

In settings, changing color_temp_startup I got an error
![DF447E23-67FD-469D-A382-29AD5CFF3E4E](https://user-images.githubusercontent.com/22882393/158007965-881d70b1-3c64-4274-81a9-1b7205871a1c.jpeg)

### What did you expect to happen?

Non error at all

### How to reproduce it (minimal and precise)

Just changing settimg

### Zigbee2MQTT version

 1.24.0 commit: 7a2ddf24

### Adapter firmware version

20210120

### Adapter

ZZH MULTIPROTOCOL RF STICK (CC2652R1 - EXTERNAL ANTENNA)

### Debug log

 Publish 'set' 'color_temp_startup' to 'Bulbo Lampada Camera' failed: 'Error: Write 0xa4c138184db92f42/1 lightingColorCtrl({"startUpColorTemperature":153}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by acaonweb** [comment]
No ideas?

**Comment by Koenkk** [comment]
`UNSUPPORTED_ATTRIBUTE` -> this device doesn't support it.
