### ISSUE TITLE
New Blitzwolf SHP-13 unsupported (Probably changed to TS011F)

### ISSUE THREAD

**Issue by wilqq-the** [Koenkk/zigbee2mqtt#11837]
### What happened?

Recently I bought additional plugs from Blitzwolf (SHP13) - I have already like 5 of them and they are working perfectly fine. New ones are appearing as unsupported - probably something changed inside (firmware).

Old ones reported as TS0121_plug.
![image](https://user-images.githubusercontent.com/19674548/158070102-1fe275b3-1abf-4037-b7df-4344287b5e69.png)

News ones reporting as TS011F.
![image](https://user-images.githubusercontent.com/19674548/158070116-cc8e0afd-a048-4dfa-bff0-371d41e25cc5.png)

### What did you expect to happen?

Expected to add BW-SHP13 without problems to Z2M.

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20210708

### Adapter

 zStack3x0 (Sonoff Zigbee USB dongle)

**Comment by Koenkk** [comment]
Please provide the data/database.db entry of this device.

**Comment by nohn** [comment]
Looks like #11703 to me.
