### ISSUE TITLE
[New device support]: Hue White Ambiance Runner Triple Spotlight

### ISSUE THREAD

**Issue by yorickri** [Koenkk/zigbee2mqtt#11832]
### Link

https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-runner-3-lichts-spotbalk/8719514338388

### Database entry

{"id":42,"type":"Router","ieeeAddr":"0x001788010c3e562c","nwkAddr":42224,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003046301_02","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003046301_02","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1647173547446,"defaultSendRequestWhen":"immediate"}

### Comments

Same as 5309331P6, which is already supported.

### External converter

```shell
const { toZigbeeConverters: tz, fromZigbeeConverters: fz, exposes } = require('zigbee-herdsman-converters');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

// Copied from zigbee-herdsman-converters/devices/philips.js with no modifications
const hueExtend = {
  light_onoff_brightness: (options = {}) => ({
    ...extend.light_onoff_brightness(options),
    toZigbee: extend.light_onoff_brightness(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_colortemp: (options = {}) => ({
    ...extend.light_onoff_brightness_colortemp(options),
    toZigbee: extend.light_onoff_brightness_colortemp(options).toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_color: (options = {}) => ({
    ...extend.light_onoff_brightness_color({ supportsHS: true, ...options }),
    toZigbee: extend.light_onoff_brightness_color({ supportsHS: true, ...options }).toZigbee
      .concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
  light_onoff_brightness_colortemp_color: (options = {}) => ({
    ...extend.light_onoff_brightness_colortemp_color({ supportsHS: true, ...options }),
    toZigbee: extend.light_onoff_brightness_colortemp_color({ supportsHS: true, ...options })
      .toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
  }),
};

module.exports = [{
  zigbeeModel: ['929003046301_01', '929003046301_02', '929003046301_03'],
  model: '929003046301',
  vendor: 'Philips',
  description: 'Hue White ambiance Runner triple spotlight',
  meta: { turnsOffAtBrightness1: true },
  extend: hueExtend.light_onoff_brightness_colortemp_color({ colorTempRange: [153, 500] }),
  ota: ota.zigbeeOTA,
}];
```

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
