### ISSUE TITLE
[New device support]: TUYA ts0601 Garage Door Opener z2m

### ISSUE THREAD

**Issue by atika1988** [Koenkk/zigbee2mqtt#11836]
### Link

https://www.aliexpress.com/item/1005003610757320.html?spm=a2g0o.order_list.0.0.21ef1802mSmhPI

### Database entry

router/0xa4c138d418010297/0xE517/ts0601/_TZE200_nklqjk62

### Comments

failed to connect because it is not supported. I would like to apply for support

**Comment by Koenkk** [comment]
`_TZE200_nklqjk62` is already supported z2m 1.24.0
