### ISSUE TITLE
[New device support]: please can you add the ledvance PAR16S TW

### ISSUE THREAD

**Issue by dj9p** [Koenkk/zigbee2mqtt#11838]
### Link

https://www.ledvance.fr/particuliers/produits/smart-home/lampes-smart-home/smart-zigbee/spot-smart-spot-avec-technologie-zigbee/ampoules-led-reflecteur-avec-technologie-smart-home--temperature-de-couleur-reglable--par16-c6270

### Database entry

Adresse IEEE     0xf0d1b800001c0bd7 Adresse réseau     0x465B Version Firmware     02136550

### Comments

Sorry but i'm french and i don't understand how to use converter can you help me?
I have test to add the new device but doesn't work...
![ledvance](https://user-images.githubusercontent.com/25746092/158072924-561c330a-29f3-4c77-a4d9-b2f643ca8879.jpg)

### Supported color modes

color temperature 2700-6500 K

**Comment by Koenkk** [comment]
Please provide the correct color temp range as explained on https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device

**Comment by dj9p** [comment]
sorry but i have nothing in the consol dev see,
![consol dev](https://user-images.githubusercontent.com/25746092/158073650-ebb1c1e0-6a2f-431a-a080-bad44fa47a6e.jpg)

**Comment by dj9p** [comment]
![led](https://user-images.githubusercontent.com/25746092/158073797-8e432975-0c13-454b-95a1-9af2548b374f.jpg)

**Comment by dj9p** [comment]
i can't read the color temp range. Please see : 
![colortemp](https://user-images.githubusercontent.com/25746092/158073972-cef37dff-d25b-4061-bd30-1454c381c569.jpg)

**Comment by Koenkk** [comment]
Added the device.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
