### ISSUE TITLE
[New device support]: Please add new manufacture for Tuya TS0505B

### ISSUE THREAD

**Issue by loy1020** [Koenkk/zigbee2mqtt#11852]
### Link

https://www.aliexpress.com/item/1005003767081949.html?spm=a2g0o.detail.0.0.51b931f2xgdV4D&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.274681.0&scm_id=1007.13339.274681.0&scm-url=1007.13339.274681.0&pvid=8caa77ca-1bf5-468b-a65b-b447d1d12ab7&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.274681.0,pvid:8caa77ca-1bf5-468b-a65b-b447d1d12ab7,tpp_buckets:668%232846%238108%231977&pdp_ext_f=%257B%2522sku_id%2522%253A%252212000027095482117%2522%252C%2522sceneId%2522%253A%25223339%2522%257D&pdp_pi=-1%253B14.0%253B-1%253B-1%2540salePrice%253BUSD%253Brecommend-recommend

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0xa4c138856686ecf2","nwkAddr":23986,"manufId":4417,"manufName":"_TZ3210_ejctepku","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1647335998542,"defaultSendRequestWhen":"immediate"}

### Comments

I manually add the manufacture name into tuya.js and it works just fine

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: 
        [{modelID: 'TS0505B', manufacturerName: '_TZ3210_ejctepku'}],
        model: 'TS0505B',
        vendor: 'TuYa',
        description: 'Zigbee RGB+CCT light',
        whiteLabel: [{vendor: 'Mercator Ikuü', model: 'SMD4106W-RGB-ZB'},
            {vendor: 'TuYa', model: 'A5C-21F7-01'}, {vendor: 'Mercator Ikuü', model: 'S9E27LED9W-RGB-Z'},
            {vendor: 'Aldi', model: 'L122CB63H11A9.0W', description: 'LIGHTWAY smart home LED-lamp - bulb'},
            {vendor: 'Lidl', model: '14153706L', description: 'Livarno smart LED ceiling light'},
        ],
        extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}),
        meta: {applyRedFix: true, enhancedHue: false},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
