### ISSUE TITLE
Brightness regulation on Tuya wall dimmer TS0601 

### ISSUE THREAD

**Issue by ceromanc** [Koenkk/zigbee2mqtt#11856]
### What happened?

Hello, I'm using the following rotary dimmer switch:

https://www.moeshouse.com/collections/smart-dimmer-switch/products/new-zigbee-smart-rotary-light-dimmer-switch-brightness-memory-smart-life-tuya-app-remote-control-works-with-alexa-google-eu

The dimmer was recognized as:

Zigbee model: 			TS0601
Zigbee manufacturer: 		_TZE200_dfxkcots
Manufacturer 				[TuYa](https://www.zigbee2mqtt.io/supported-devices/#v=TuYa)
Model 					[TS0601_dimmer](https://www.zigbee2mqtt.io/devices/TS0601_dimmer.html#tuya-ts0601_dimmer)

and the status is: supported.

On/Off works perfectly. Only when I try to change the brightness via HA, the target value is reduced by 2. For example, I would like to change the brightness to 50, but the value immediately jumps to 48. Even if I just click the input field and then outside with the mouse, the actual value is reduced by 2 each time until the value becomes a minus value, after which an error message appears.

Here is device info from database:

`{"id":20,"type":"Router","ieeeAddr":"0x84fd27fffe8d4b00","nwkAddr":44276,"manufId":4098,"manufName":"_TZE200_dfxkcots","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_dfxkcots","stackVersion":0,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00258d4ced","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b00258d4ced","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1647369459265,"defaultSendRequestWhen":"immediate"}`

Any idea how to correct it?

Many thanks in advance.

### How to reproduce it (minimal and precise)

Just try to change the brightness via input field or slider

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20211217

### Adapter

SONOFF ZB Dongle-P CC2652P

### Debug log

![2022-03-14 13_23_33-Clipboard](https://user-images.githubusercontent.com/96552409/158386479-aed42a43-df5f-44dc-a6ce-3241567c2945.png)

**Comment by ceromanc** [comment]
Added animated gif to show the issue

![z2m](https://user-images.githubusercontent.com/96552409/163991500-ddb72bfb-36cb-4d45-81e6-436d5b551400.gif)

**Comment by ceromanc** [comment]
After update to Zigbee2MQTT Version
 1.25.1 issue is solved.

**Comment by bort900** [comment]
I am having the exact same issue as described here.

I have a MOES branded Tuya TS0601 wall dimmer and it will respond to on/off commands but not brightness commands. You can manually adjust the dimmer at the switch and it will reflect the state properly, but you cant set brightness from Zigbee2MQTT

I am using Zigbee2MQTT 1.26.0 with zStack3x0 2022021 on a SONOFF Zigbee 3.0 USB adapter.
