### ISSUE TITLE
[New device support]: LeakSMART water valve v2.10

### ISSUE THREAD

**Issue by sambeetm** [Koenkk/zigbee2mqtt#11871]
### Link

https://shopleaksmart.com/collections/leak-detector-products/products/new-protect-by-leaksmart-water-shut-off-valve

### Database entry

{"id":11,"type":"EndDevice","ieeeAddr":"0x0022a300000f9e9e","nwkAddr":39208,"manufId":4411,"manufName":"WAXMAN","powerSource":"Mains (single phase)","modelId":"leakSMART Water Valve v2.10","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2,"inClusterList":[0,1,3,6,32,2818,64514],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":28}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024bc1704","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":25,"stackVersion":1,"hwVersion":10,"dateCode":"20150723","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1647446560908,"defaultSendRequestWhen":"fastpoll"}

### Comments

It works

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['leakSMART Water Valve v2.10'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'leakSMART', // Vendor model number, look on the device for a model number
    vendor: 'WAXMAN', // Vendor of the device (only used for documentation and startup logging)
    description: 'Smart Water Valve', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.on_off], // We will add this later
    toZigbee: [tz.on_off], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.switch().setAccess('state', ea.STATE_SET)], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
    // The configure method below is needed to make the device reports on/off state changes
    // when the device is controlled manually through the button on it.
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(endpoint);
    },
};

module.exports = definition;
```

**Comment by sambeetm** [comment]
I see this device is supported as of 1.24.0. but its shown as v2.0. Mine is leakSMART Water Valve v2.10. is it because of the version no that mine is not configuring automatically ?

**Comment by Koenkk** [comment]
Yours had a different model and therefore was not supported yet, added it now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by sambeetm** [comment]
Appreciate for the quick fix!!
