### ISSUE TITLE
[New device support]: Aubess GU10 bulb (TS0505B, _TZ3210_qxenlrin)

### ISSUE THREAD

**Issue by g189ffin** [Koenkk/zigbee2mqtt#11882]
### Link

https://www.aliexpress.com/item/1005003754490865.html

### Database entry

{"id":81,"type":"Router","ieeeAddr":"0xa4c138178b55e26a","nwkAddr":7311,"manufId":4417,"manufName":"_TZ3210_qxenlrin","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_qxenlrin","powerSource":1,"zclVersion":3,"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b001949ad80","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":821693351},"lastSeen":1647521955935,"defaultSendRequestWhen":"immediate"}

### Comments

Followed the instructions to get the "code" (https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#_5-adding-your-first-data-point) 

Light to wake: 32
On/Off: 1
Power Off Memory: 33
Mode: 2
Do not disturb: 34
Brightness: 3
On/Off Gradient:35
Colour Temp: 4
Colourful: 5
Scene: 6
Timer: 7
Music: 8
Adjust: 9
Zigbee light link threshold: 81
Cycle timing: 209
Vacation Timing: 210
Rhythms: 30
Light to sleep: 31

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0505B',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZ3210_qxenlrin'
        },
    ],
    model: 'GU10RGB',
    vendor: 'Aubess',
    description: 'GU10 colour spot light',
    fromZigbee: [
        fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
        fz.tuya_data_point_dump, // This is a debug converter, it will be described in the next part
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        // Here you should put all functionality that your device exposes
    ],
};

module.exports = definition;
```

### Supported color modes

colour temp, rgb

### Color temperature range

153, 500

**Comment by Koenkk** [comment]
Was just added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4012

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by g189ffin** [comment]
> Was just added in [Koenkk/zigbee-herdsman-converters#4012](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4012)
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Thanks @Koenkk for the speedy response. The bulb is marked as supported now but there is nothing exposed. Do you know how I can get the light controls on there? I've tried pairing the device again but the only thing that is exposed is linkquality.

**Comment by Koenkk** [comment]
Could you make a screenshot of the z2m frontend -> click on device -> exposes?

**Comment by g189ffin** [comment]
![image](https://user-images.githubusercontent.com/33321926/159034669-5feafbca-40f1-4ba1-920a-efbc09541c7c.png)

**Comment by Koenkk** [comment]
@[daniel100097](https://github.com/daniel100097) does it work correctly for you?

**Comment by g189ffin** [comment]
@Koenkk is there anything I can provide for you in the logs, etc that will help you?

**Comment by Koenkk** [comment]
@g189ffin are you sure you removed your external converter from the configuration.yaml?

**Comment by g189ffin** [comment]
@Koenkk fixed it - I switched to the edge version and the config didn't have the external converter but when I went to the folder the configuration.yaml file had the old converters. I removed the line and restarted. Repairing again detected the devices straight away with all exposes. Thanks!

**Comment by psychowood** [comment]
I'm using z2m edge and this bulb is recognized and working.
Can someone confirm that, while it keeps brightness when it is powered off using a physical switch, it loses the color/temperature setting resetting to the cool white default, .moreover reporting the previously set.temperature?

This is the way I use to replicate the issue:
- turn on (physical switch)
- set color temperature (e.g. 2700k) from default (e.g. 4000k)
- set brightness (e.g. 50%)
- turn off (physical switch)
- turn on (physical switch)
- bulb will be at 50% brightness and 4000k
- Dashboard will show 50% and 2700K
