### ISSUE TITLE
Publishing to homeassistant topic not happening 

### ISSUE THREAD

**Issue by MGlants** [Koenkk/zigbee2mqtt#11889]
### What happened?

Publishing to homeassistant MQTT topics done only after restarting of z2m. Updating of sensors not posting to those topics. 

### What did you expect to happen?

Updating homeassistant/ toppics acording to zigbee2mqtt/ topic.

### How to reproduce it (minimal and precise)

`advanced:
  channel: 11
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: homeassistant/status
  last_seen: ISO_8601
  log_level: info
  log_output:
    - console
  network_key:
   - HIDDEN
  pan_id: 6754
  homeassistant_legacy_entity_attributes: true
  homeassistant_legacy_triggers: false
  ikea_ota_use_test_url: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
experimental:
  new_api: true
  transmit_power: 20
homeassistant: true
frontend:
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  include_device_information: true
  server: mqtt://emqx
  client_id: zigbee2mqtt
  keepalive: 60
  password: HIDDEN
  reject_unauthorized: true
  user: HIDDEN
  version: 4
  force_disable_retain: true
permit_join: false
serial:
  port: tcp://172.16.10.20:20108
  disable_led: false
  adapter: auto
devices:
HIDDEN
availability: true`

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20210813

### Adapter

zStack3x0

**Comment by MGlants** [comment]
Probably longer period for posting it

**Comment by MGlants** [comment]
after ha reboot 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/35956828/158913746-4cf9983b-d8ab-40df-a914-1d90b9f43a1c.png">

**Comment by MGlants** [comment]
after ha reboot 
<img width="290" alt="image" src="https://user-images.githubusercontent.com/35956828/158913812-dae5d8bb-88d6-43ca-9c75-41f21f03a712.png">

**Comment by va4ok** [comment]
Hi, looks i have the same issue.
From time to time zigbee2mqtt addon hangs until reboot plugin.

No new values get or set, plugin CPU load > 20%, RAM > 11%, Embeded UI not responding.

Looks like some memory leak

Gaps on card in HA
![image](https://user-images.githubusercontent.com/5189009/160788967-923b0122-916a-40cf-92fd-08e781933a42.png)

RAM and CPU usages by plugin
![image](https://user-images.githubusercontent.com/5189009/160789238-f4dade21-1dd9-4098-afb7-55ec62aa1763.png)

CPU for HA system
![image](https://user-images.githubusercontent.com/5189009/160789491-b2493502-e710-40b9-b355-db5ff184f55c.png)

RAM for HA system
![image](https://user-images.githubusercontent.com/5189009/160789584-2a475a97-356b-4355-839c-bb01875609f6.png)

**Comment by va4ok** [comment]
I've removed and install addon one more time and looks it works.
