### ISSUE TITLE
Wrong device information

### ISSUE THREAD

**Issue by dexsta** [Koenkk/zigbee2mqtt#11893]
### What happened?

So I'm trying to add this device which says it is supported.

![tuya-repeater](https://user-images.githubusercontent.com/41833996/158919788-c0242882-a27a-4555-8147-b287a8719fc6.png)

However, the device is coming up as a Water leak detector ?

![water-leak](https://user-images.githubusercontent.com/41833996/158919885-361d8100-d05e-4288-9d24-e910f7849c60.png)

The Model #'s are nearly the same, except my device has `_repeater` at the end.

![leak](https://user-images.githubusercontent.com/41833996/158920682-9ffdc574-125f-4dab-aaae-723951ea67da.png)

And in the Map option shows this

![map](https://user-images.githubusercontent.com/41833996/158920943-49cad86b-367a-4c0f-92d8-1e99fa489ca2.png)

How would I go about fixing this, or is it a Bug ? Tried many times removing/re-adding the device. 

Thanks.

### Zigbee2MQTT version

1.18.1 commit: 1.18.1

### Adapter firmware version

20211217

### Adapter

Sonoff  ZigBee 3.0 USB Dongle plus

**Comment by Koenkk** [comment]
you are using an outdated z2m version.

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0

**Comment by dexsta** [comment]
@Koenkk thanks for replying. Please excuse my dumbness, couple questions. I just installed this like yesterday, would it not already come with the latest version? I have turned on Auto update but still the same. Or I need to do something else?

![Screenshot_2022-03-19-02-59-48-00_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/41833996/159039951-23dfd602-658c-4e5c-b843-78f25f36c1d3.jpg)

So 124.0-1 is that the latest ? Big difference to what I have at the moment.

![Screenshot_2022-03-19-03-01-59-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41833996/159040914-e2073559-5854-4b39-a5d5-8b1983d16134.jpg)

Thanks for your assistance 👍

**Comment by dexsta** [comment]
Ok, so I had to change to the new Repo. 👌 Can close.
