### ISSUE TITLE
Version number on application startup

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt#119]
An application version number should be displayed when starting up. 

This can be:
- commit number for those running out of master
- actual release version for those running a final version from a tag/release (available after 0.1)

**Comment by Koenkk** [comment]
Yes that would be nice!

**Comment by ciotlosm** [comment]
I think best approach would be to create a script that users can run as a "setup" before they start zigbee2mqtt to generate the proper file for the commit hash. This way this is ready for future usage. 
```
git rev-parse --short HEAD
```

@danielwelch maybe we can add this into `run.sh` for the addon to achieve the same thing there.
