### ISSUE TITLE
unsupported device Zigbee model 'TS011F'

### ISSUE THREAD

**Issue by nurbecause** [Koenkk/zigbee2mqtt#11902]
### What happened?

Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_cfnprab5'
Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Could you add the Model TS011F to default?**

Its this: https://www.ebay.de/itm/265483689288

### Zigbee2MQTT version

1.18.1-1 hassio

### Adapter firmware version

CC2652P + CP2102N 

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus https://www.amazon.de/gp/product/B09KXTCMSC/ref=ppx_yo_dt_b_asin_title_o01_s04

**Comment by Koenkk** [comment]
Should be fixed in the latest z2m version already.

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
