### ISSUE TITLE
Zemismart ZM-AM02 RF Dongle - Add more than one blind

### ISSUE THREAD

**Issue by lukaaars** [Koenkk/zigbee2mqtt#11918]
### What happened?

I have two blinds that I can control separately with a RF remote in one room.
If I add the device in zigbee2mqtt I can just use one command. Does anybody know how to add a second command for another blind?

### What did you expect to happen?

The official product descriptions says it's possible to control several devices (see https://images-txsh.tuyacn.com/ecommerce/1624011804a4e7f9ddd93.jpg)

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20211115

### Adapter

Zemismart ZM-AM02_cover

**Comment by mgwoj** [comment]
Actually it is possible to control all blinds at the same time when they are controllable with the same remote. According to the instruction you can add more than one remote to each motor. To make it working, let's assume that you have each blind assigned to dedicated channel on the remote. Then you:
* change remote into group mode using left/right arrow until all digits are lit. 
* enter pairing mode: press STOP of the programmed transmitter for 5s, motor jog once, press OPEN on the z2m control page for the AM02 dongle, motor jog once

After completing those steps you can control all blinds at the same using single AM02 dongle.
