### ISSUE TITLE
After updating to from 1.22.0 to 1.24.0 Frontend is empty/bugged

### ISSUE THREAD

**Issue by sir-harlekin** [Koenkk/zigbee2mqtt#11917]
### What happened?

After updating from 1.22.0 to 1.24.0 Frontend is empty and shows no devices. Settings show no data. But the log attached looks like its working (?).
![image](https://user-images.githubusercontent.com/20474014/159257947-01eb8f20-b070-4042-a196-f541997b885e.png)
![image](https://user-images.githubusercontent.com/20474014/159257980-b89aa302-35f9-4c94-90b0-92289c9453a2.png)

### What did you expect to happen?

Frontend working, devices displayed.

### How to reproduce it (minimal and precise)

I am sorry, i dont know. I just updated using the avaiable guide.

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

can not check settings broken

### Adapter

Conbee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8315241/log.txt)

/edit: a small update: it seems to be working in general, because i can now add new hue motion sensors through the FHEM frontend. but i can still not use the zigbee2mqtt frontend or see any data.

/edit2: closing the issue. i was not logged in to frontend via auth token after updating.

**Comment by jagjordi** [comment]
Hello! How did you solve this? I am having the same issue :/
