### ISSUE TITLE
zigbee2mqtt.io DNS is down

### ISSUE THREAD

**Issue by fsevilla3** [Koenkk/zigbee2mqtt#11910]
### What happened?

The zigbee2mqtt.io domain fails to resolve, rendering the website is inaccessible. Even the initial name server lookup doesn't return any results. In addition to a local query that uses Cloudflare DNS (1.1.1.1), I also checked this independently using https://mxtoolbox.com/SuperTool.aspx?action=dns%3azigbee2mqtt.io&run=toolpage.

### What did you expect to happen?

zigbee2mqtt.io to resolve and website to be accessible

### How to reproduce it (minimal and precise)

dig zigbee2mqtt.io ns

### Zigbee2MQTT version

N/A

### Adapter firmware version

N/A

### Adapter

N/A

**Comment by Koenkk** [comment]
Seems to work again:

<img width="1118" alt="Screenshot 2022-03-20 at 16 15 10" src="https://user-images.githubusercontent.com/2892853/159169300-e108ed1e-3d6f-4242-a726-37159d42b09c.png">

**Comment by GerdRuetten** [comment]
Yes allways work well
