### ISSUE TITLE
zigbee2mqtt config not paying attention to my friendly names

### ISSUE THREAD

**Issue by roygbiv856** [Koenkk/zigbee2mqtt#1192]
Back when I was on hassio on a pi, I could change the friendly names in the z2m/config and see the new names in the logs. I recently moved to a NUC, still running hassio like on the pi, but my new friendly names are not reflected in the logs. After a restart of hassio, my friendly names completely reset to the default friendly names of a long string of numbers. Where exactly should I go to change the friendly names and have them reflected in the logs?

**Comment by Koenkk** [comment]
Can you post your zigbee2mqtt logs?

**Comment by roygbiv856** [comment]
@Koenkk Here you are, buddy

https://pastebin.com/SWd0Ppp1

**Comment by Koenkk** [comment]
Can you share you `configuration.yaml` (don't forget to mask sensitive information like passwords).

**Comment by roygbiv856** [comment]
@Koenkk The friendly names often get reset back to their default long number names, so here I only have 1 changed:

https://pastebin.com/g8nstyGE

The friendly name never appears in the logs

**Comment by Koenkk** [comment]
Could you provide your startup log after changing 1 friendly name? I guess the real issue here is that the friendly names get reset automatically, could you find out how to reproduce this?

**Comment by Andreln** [comment]
I just paired a IKEA outlet and I get the same error. Homeassistant doesn't register the device with friendly name instead it takes the id and appends _switch (switch.0x000d6ffffef5119a_switch). 

After pairing I added a friendly name and restarted both zigbee2mqtt and homeassistant.

**Comment by Koenkk** [comment]
@Andreln changing this after the device got discovered by HA is not possible (limitation of HA). http://www.zigbee2mqtt.io/integration/home_assistant.html#im-confused-about-the-different-device-ids-names-and-friendly-names
