### ISSUE TITLE
Error pairing Tint-Bulb

### ISSUE THREAD

**Issue by CyberianD** [Koenkk/zigbee2mqtt#1193]
I got an CC2530 flashed with the latest coordinator firmware and I am using mosquitto as the mqtt-server.

When I try to pair a tint bulb the following error:

```
Mär 05 12:10:58 raspberrypi npm[497]:         {"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_m\n    at CcZnp.emit (events.js:189:13)\n    at Timeout.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:433:5)\n    at Timer.processTimers (timers.js:223:10)"}
Mär 05 12:10:58 raspberrypi npm[497]:   zigbee2mqtt:info 2019-3-5 12:10:58 MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","per
Mär 05 12:11:06 raspberrypi npm[497]:   zigbee2mqtt:error 2019-3-5 12:11:06 Cannot get the Node Descriptor of the Device: 0x00158d0002fd8b56 (Error: request
```
But the bulb gives the pairing answer (one flash).
I deleted all informations depending `0x00158d0002fd8b56` in the `database.db` but the problem won't solve.

When I try to pair with my CC2531 coordinator the device won't pair.

**Comment by DerElch87** [comment]
I can't really help here, only confirm that in my case pairing works as expected.
Coordinator:   CC2531
Bulbs:             Tint Color and Tint White
So from a firmware / software point of view it should work.
