### ISSUE TITLE
NEO SMART plug (07048L) doesn't show power consumption anymore

### ISSUE THREAD

**Issue by outkastm** [Koenkk/zigbee2mqtt#11943]
### What happened?

I have 5 pieces NEO SMART plug (07048L) which one by one stoped showing the power consumption. 
Tha last one which was still working, after directly removal from the network and adding back, it sopped showing the power consumption

If i add the devices using Zigbee Home Automation integration, the power consumption is reported correctly

### What did you expect to happen?

Show the power consumption

### Zigbee2MQTT version

1.24.0-1

### Adapter firmware version

20211210

### Adapter

Texas Instruments LAUNCHXL-CC26X2R1 #Other

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8337110/log.txt)

**Comment by mountainsandcode** [comment]
Unfortunately, the consumption is still not visible on 1.25.1
