### ISSUE TITLE
[New device support]: IMMAX NEO CANTO

### ISSUE THREAD

**Issue by lamosty** [Koenkk/zigbee2mqtt#11978]
### Link

https://www.immax.cz/immax-neo-canto-smart-stropni-svitidlo-80x80cm-60w-cerne-zigbee-3-0-p8787/?cid=348

### Database entry

{"id":50,"type":"Router","ieeeAddr":"0x60a423fffe652f23","nwkAddr":24662,"manufId":4098,"manufName":"_TZ3000_ogceypug","powerSource":"Mains (single phase)","modelId":"TS0502B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,4096,8,768],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0502B","manufacturerName":"_TZ3000_ogceypug","stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1648564344158,"defaultSendRequestWhen":"immediate"}

### Comments

Hi.

I've just managed to pair this light. I had to put the following into the `immax.js` file in `zigbee-herdsman-converters` for it to work:

```
    {
        fingerprint: [{modelID: 'TS0502B', manufacturerName: '_TZ3000_ogceypug'}],
        model: 'TS0502B',
        vendor: 'Immax',
        description: 'NEO SMART LED E27 5W',
        extend: extend.light_onoff_brightness_colortemp(),
    },
```

It's probably not precise since it's not a "smart led" but got it running. The light has brightness and colortemp controls.

Thanks!

**Comment by Koenkk** [comment]
added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
