### ISSUE TITLE
[New device support]: New fingerprint for TuYa TM001-ZA/TM081

### ISSUE THREAD

**Issue by hgokduman** [Koenkk/zigbee2mqtt#11989]
### Link

https://www.zigbee2mqtt.io/devices/TM001-ZA_TM081.html

### Database entry

{"id":22,"type":"EndDevice","ieeeAddr":"0xa4c138167c7ae7c3","nwkAddr":65293,"manufId":4417,"manufName":"_TZE200_pay2byax","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_pay2byax","powerSource":3,"zclVersion":3,"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00239326a8","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1648625776042,"defaultSendRequestWhen":"immediate"}

### Comments

{modelID: 'TS0601', manufacturerName: '_TZE200_fwoorn8y'}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
