### ISSUE TITLE
No converter for SM11

### ISSUE THREAD

**Issue by yehonadav** [Koenkk/zigbee2mqtt#1199]
from Orvibo:
https://www.google.co.il/search?q=Orvibo+sm11&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiOm6ebyu3gAhUU7aYKHf_dDYUQ_AUIDigB&biw=1229&bih=578

the device is not configured in the devices.js
also there is no converter in the fromZigbee.js

**Comment by Koenkk** [comment]
This device is not supported yet, in case you have this device, please follow: http://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
