### ISSUE TITLE
Incorrect action report for Moes Smart Portable Universal remote (recognized as Tuya TS0044)

### ISSUE THREAD

**Issue by vasimv** [Koenkk/zigbee2mqtt#11992]
### What happened?

Moes Smart Portable Universal remote (4-buttons remote, recognized as Tuya TS0044 remote) often sends double action reports when button pressed (like "1_single" and "1_undefined" together). That causes problems for openhab who can't react properly on "X_single" action report because "X_undefined" is received at same time.

I've made hotfix for this to filter out those unwanted reports (seems the remote sends incremental action number or something like that in second message):

```
*** node_modules/zigbee-herdsman-converters/converters/fromZigbee.js.old	Wed Mar 30 15:30:51 2022
--- node_modules/zigbee-herdsman-converters/converters/fromZigbee.js	Wed Mar 30 15:31:43 2022
***************
*** 2611,2616 ****
--- 2611,2617 ----
          type: 'raw',
          convert: (model, msg, publish, options, meta) => {
              if (hasAlreadyProcessedMessage(msg, msg.data[1])) return;
+ 	    if (msg.data[3] > 2) return;
              const clickMapping = {0: 'single', 1: 'double', 2: 'hold'};
              let buttonMapping = null;
              if (model.model === 'TS0042') {

```

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee 3.0

**Comment by callacomp** [comment]
Do you mean this one?
https://banggood.onelink.me/zMT7/l9amh0us
Other than being picked up as the wrong device as you've said but this works fine in HA. I'm using single and double clicks without an issue.
I do find battery status is odd mind, it stays at 100%, never changes but dies in weeks. Changed 5 batteries since Christmas.
