### ISSUE TITLE
Resolving for "Support: planned to support devices."

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#12]
Hey Koenkk,

I see your List of "Planned to Supported Devices" , maybe you will find some of the Resolving at these cool File [https://github.com/kirovilya/ioBroker.zigbee/blob/master/main.js](url)

The Cool Guy included the 
"MFKZQ01LM Xiaomi Magic Cube Controller (shake, slide, flip90, flip180, tap, rotate, fall, wakeup, voltage)"  
and 
"JTYJ-GD-01LM/BW Xiaomi Smoke Alarm (detected, voltage)"

**Comment by Koenkk** [comment]
Thanks for letting me know, this will definitely help me in supporting these 2 devices.

My MFKZQ01LM and TYJ-GD-01LM/BW are currently being shipped so I'm waiting for them to arrive.

Let's continue in #4
