### ISSUE TITLE
Upgrading to 1.25 - all zigbee devices will stop working?? Am I reading this right? Is this a joke? 

### ISSUE THREAD

**Issue by dnedeltchev** [Koenkk/zigbee2mqtt#12012]
### What happened?

According to the release notes of 1.25 all zigbee devices will stop working. This is a joke right? 

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

29211210

### Adapter

zzh

**Comment by rob1981forest** [comment]
its 1st April - surely a joke ?

**Comment by dnedeltchev** [comment]
And then I looked at the date... 1 April!

**Comment by dnedeltchev** [comment]
Yep, it is. 😁
