### ISSUE TITLE
all problems after the last update

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#12017]
### What happened?

After the update, the whole Zigbee network reacts very slowly and strangely.
The lqi is always 0-47, although it was well over 100 before.
Timeouts always occur.

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20220219

### Adapter

LAUNCHXL-CC1352P-2

### Debug log

Publish 'set' 'state' to 'Baum-Licht-ST' failed: 'Error: Command 0x84fd27fffece98e9/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 6493 - 1 - 194 - 6 - 11 after 10000ms)'

**Comment by salopette** [comment]
![sshot-1](https://user-images.githubusercontent.com/32480002/161244386-b2b3ef33-297f-4552-9287-a02a742ef9fe.jpg)

**Comment by xekil** [comment]
same problem, i also updated my stick zzh! but without success...

**Comment by 1800Zeta** [comment]
seeing similar, have rolled back ZZH firmware and the addon version but it's still the same

**Comment by 1800Zeta** [comment]
OK now fully updated, had to force a couple of devices to 'check in' with a state change but things seem to be working again with ZZH 20220219 and Z2M 1.25

**Comment by stoinov** [comment]
Same here. I've only noticed my warnings after the zzh! flash, but they were possibly there before that.
Managed to fix some of the lights by resetting them (4-5 times turning them on/off), but some are not joining after that manipulation.
