### ISSUE TITLE
TuYa U86KCJ-ZP（zigbeeModel: 005f0c3b）

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#12023]
### What happened?

Not added in version 1.25.0
TuYa U86KCJ-ZP there is another model of this device. Please add it. thank you！
zigbeeModel: 005f0c3b
![159493369-7ed078a5-c587-439d-9d37-d0c2ae2d9c25](https://user-images.githubusercontent.com/40196105/161288733-79897eed-abed-4f2f-b72a-a2d78bac9473.jpg)

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210319

### Adapter

cc2652p

**Comment by unpack8866** [comment]
Sorry, the zigbeeModel is wrong

<img width="726" alt="AE58D8F5-726F-4171-A40A-53A072A3B11C" src="https://user-images.githubusercontent.com/40196105/161376741-7e88835c-f4e7-4302-8bed-2f7beae2b371.png">


correct zigbeeModel: 005f0c3b

**Comment by Koenkk** [comment]
fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
