### ISSUE TITLE
Error converting file（spotmau 1 gang）

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#12022]
### What happened?

Sorry, there is an error in the conversion file of the one gang switch, which makes it unusable; Please modify it!
![12121212](https://user-images.githubusercontent.com/40196105/161287556-c2cedbd0-ea3c-48e0-ac76-530afec06e4c.jpg)

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210319

### Adapter

cc2652p

**Comment by unpack8866** [comment]
exposes: [e.switch().withEndpoint('l1')],
    endpoint: (device) => {
        return {'l1': 16};
    },    

Need to add endpoint: 16; It cannot be used normally without adding. The default status will be obtained from endpoint 1

**Comment by Koenkk** [comment]
Done!

**Comment by unpack8866** [comment]
> Done!

The switch is normal, thank you!
