### ISSUE TITLE
Siren M0L0-HS2WD-TY 

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#12024]
### Link

https://m0l0.com/m0l0-powered-by-tuya-sirena-de-alarma-zigbee.html

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0xec1bbdfffee4cf8d","nwkAddr":56454,"manufId":4619,"manufName":"_TYZB01_8scntis1","powerSource":"Mains (single phase)","modelId":"TS0216","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClusterList":[0,1,3,1280,1282,2821],"outClusterList":[4,25],"clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":0}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca168ea","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":2,"hwVersion":1,"dateCode":"2019.6.23","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1648825549045,"defaultSendRequestWhen":"immediate"}

### Comments

Can you please add that siren?
Posted before but not edited.

https://github.com/Koenkk/zigbee2mqtt/issues/11382

**Comment by salopette** [comment]
@Koenkk 
Do you need more info or other parameters for support?

**Comment by Koenkk** [comment]
@salopette please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions
