### ISSUE TITLE
missing web ui after update to Matter, cannot see anything

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#12035]
### What happened?

Like the head says

### What did you expect to happen?

works as before

### How to reproduce it (minimal and precise)

I did the upgrade like always, include the backup and restore option.
Is this perhas wrong?

I run Domoticz on a Odroid N2 with Armbian  [ not in docker ]

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

do not kwow, cannot see this at the moment

### Adapter

same as firmware

### Debug log

Use domoticz, matter devices working fine

Only where to find the webui?

**Comment by dev-a** [comment]
I have the same problem 
I don't have a 404 error or anything else just a blank page 
the node client seems to be running (via ps aux and systemctl status zigbee2mqtt.service)

**Comment by Dylantje** [comment]
> I have the same problem I don't have a 404 error or anything else just a blank page the node client seems to be running (via ps aux and systemctl status zigbee2mqtt.service)

What domotica system you are running? on what hardware?

**Comment by dev-a** [comment]
> > I have the same problem I don't have a 404 error or anything else just a blank page the node client seems to be running (via ps aux and systemctl status zigbee2mqtt.service)
> 
> What domotica system you are running? on what hardware?

in my case I do not use a home automation system, I use only nodered & zigbee2mqtt ui  directly on my raspberry pi

**Comment by Dylantje** [comment]
u used als the webui form z2m?

**Comment by ondrejbaranek** [comment]
Same issue on rpi3b+ with bullseye, standalone z2m on it

**Comment by aarpi3** [comment]
Same here. Rpi3b+, buster, standalone z2m.

**Comment by ondrejbaranek** [comment]
Looks to be chrome(ium) related. Works fine in Firefox.

**Comment by dev-a** [comment]
Indeed , on firefox work correctly

**Comment by ondrejbaranek** [comment]
Clearing cache in Chrome app settings on Android helps. So this release could break something in the cache for some people :)

**Comment by dev-a** [comment]
Hello , 
as far as I am concerned, I use brave
I looked at the functions available on the brave shield
I have deactivated. "update connections to https"
since i have access to ui correctly

I did a small search on google "chrome "+ "https"
It appears that there has been an update of chrome on this subject in March

**Comment by samme78** [comment]
Clearing the cache in my Chrome browser solved the issue for me.
