### ISSUE TITLE
[New device support]: Philips Infuse (new model) 915005998201

### ISSUE THREAD

**Issue by CaliLuke** [Koenkk/zigbee2mqtt#12044]
### Link

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-infuse-hue-ceiling-lamp/4116331U9

### Database entry

"0x001788010b41a6e5": {             "date_code": "20210305",             "definition": null,             "endpoints": {                 "11": {                     "bindings": [],                     "clusters": {                         "input": [                             "genBasic",                             "genIdentify",                             "genGroups",                             "genScenes",                             "genOnOff",                             "genLevelCtrl",                             "touchlink",                             "lightingColorCtrl",                             "manuSpecificUbisysDimmerSetup"                         ],                         "output": [                             "genOta"                         ]                     },                     "configured_reportings": [],                     "scenes": []                 },                 "242": {                     "bindings": [],                     "clusters": {                         "input": [],                         "output": [                             "greenPower"                         ]                     },                     "configured_reportings": [],                     "scenes": []                 }             },             "friendly_name": "0x001788010b41a6e5",             "ieee_address": "0x001788010b41a6e5",             "interview_completed": true,             "interviewing": false,             "manufacturer": "Philips",             "model_id": "915005998201",             "network_address": 21504,             "power_source": "Mains (single phase)",             "software_build_id": "1.82.10",             "supported": false,             "type": "Router"         }

### Comments

Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

Product pagE: https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-infuse-hue-ceiling-lamp/4116331U9

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
