### ISSUE TITLE
Eurotronic  SPZB0001

### ISSUE THREAD

**Issue by bluenazgul** [Koenkk/zigbee2mqtt#12054]
### What happened?

I have 3 of this devices running,

Zigbee Modell
SPZB0001
Zigbee Hersteller
Eurotronic

they are working but often get the following error in Logs

### What did you expect to happen?

Error Publish 'set' 'occupied_heating_setpoint' to 'Heizkörper Wohnzimmer Tür' failed: 'Error: Write 0x00158d0007743572/1 hvacThermostat({"occupiedHeatingSetpoint":2400}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 3698 - 1 - 166 - 513 - 4 after 10000ms)'

### Zigbee2MQTT version

1.25.0-1

### Adapter firmware version

latest

### Adapter

Sonoff Zigbee

**Comment by lux73** [comment]
I'm using two of them - never seen such an Issue

could you please trying delete & re-pair?
