### ISSUE TITLE
SMHM-I1 fix

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#12076]
### What happened?

Request deletion'' e.tamper()'',There is no such thing.
<img width="613" alt="84B33009-E532-4D74-8AC7-66D8B13A0934" src="https://user-images.githubusercontent.com/40196105/161701205-82aeebec-5c9a-4655-915c-113c2b5beab5.png">

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210309

### Adapter

cc2652p

**Comment by Koenkk** [comment]
Done.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by unpack8866** [comment]
> Done.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Repair the battery level display！
<img width="653" alt="5BCF388B-D4E9-4B50-B285-DD4C7DEDD985" src="https://user-images.githubusercontent.com/40196105/163698941-da22c8a6-5eb0-4eeb-bda9-f63113035e6d.png">

const device = {
    zigbeeModel: ['SMHM-I1', 'PIR_TPV12'],
    model: 'SMHM-I1',
    vendor: 'HEIMAN',
    description: 'Smart motion sensor',
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
    toZigbee: [],
    exposes: [e.occupancy(), e.battery_low(), e.battery()],  
    meta: {battery: {voltageToPercentage: '3V_2500'}},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.batteryVoltage(endpoint);
    },
};

module.exports = device;
