### ISSUE TITLE
FNB56-GAS05FB1.4 fix

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#12077]
### What happened?

Request deletion'' e.tamper()&e.battery_low()'',There is no such thing.
<img width="504" alt="DA3BFE8F-21ED-4EF5-81E3-75AE9ECBF4B7" src="https://user-images.githubusercontent.com/40196105/161702255-5f22a5d6-14f7-4eba-b2f2-52bd6256790d.png">

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210319

### Adapter

cc2652p

**Comment by Koenkk** [comment]
Done

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
