### ISSUE TITLE
Paulmann 939.99 is detected as Paulmann 500.45 and wrong picture for 500.45

### ISSUE THREAD

**Issue by antoninblanc** [Koenkk/zigbee2mqtt#12099]
### What happened?

Paulmann 939.99 is detected as Paulmann 500.45

Here is my database.db : 

`{"id":6,"type":"Router","ieeeAddr":"0x00158d000579d282","nwkAddr":3900,"manufId":4151,"manufName":"Paulmann Licht","powerSource":"DC Source","modelId":"500.45","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,4,3,6,8,5,4096,25],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"500.45","manufacturerName":"Paulmann Licht","powerSource":4,"zclVersion":3,"appVersion":12,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swBuildId":"1400-0001"}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":167}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":12,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swBuildId":"1400-0001","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1649278647433,"defaultSendRequestWhen":"immediate"}
`

I dont know why Zigbee Model isnt `H036-0001` ... maybe it's a manufacturer issue / kind of rebranded product ? If someone can confirm this, I can ask them If it's possible to fix the Zigbee Model, otherwise i assume only way to fix detection is by using some ugly fingerprint ?

For me, it's not a big issue tho. Paulmann 939.99 and 500.45 are both light_onoff_brightness devices. Everything works as expected. 

However, for 500.45, the picture is wrong : https://www.zigbee2mqtt.io/devices/500.45.html (I think this picture is for Paulmann 798.15) The right picture for 500.45 is this one https://content.paulmann.com/media/ba/12/03/1618895878/50045ip01.jpg.

Ref https://github.com/Koenkk/zigbee2mqtt/issues/3087

Thanks.
 
### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus (zStack3x0)

**Comment by Koenkk** [comment]
This device identifies itself as as 500.45 (look at your database.db entry: `,"modelId":"500.45"`). So it looks to be a whitelabel which we cannot distinguish from the 500.45.
