### ISSUE TITLE
[New device support]: Ajax Online Zignito GU10 RBG+CW+WW

### ISSUE THREAD

**Issue by Xaldimo** [Koenkk/zigbee2mqtt#12105]
### Link

https://www.ajaxonline.co.uk/product/zignito-gu10-spotlight-bulb/

### Database entry

{"id":22,"type":"Router","ieeeAddr":"0xa4c138beea61f7ab","nwkAddr":51302,"manufId":4417,"manufName":"_TZ3210_mzdax7ha","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_mzdax7ha","powerSource":1,"zclVersion":3,"appVersion":91,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"61440":0,"onOff":1}},"lightingColorCtrl":{"attributes":{"57600":[79,65536120],"61447":[],"61448":[],"61449":[],"61453":0,"tuyaRgbMode":0,"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"currentHue":null}},"genLevelCtrl":{"attributes":{"61440":79}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":91,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1649346671205,"defaultSendRequestWhen":"immediate"}

### Comments

It announces itself as a Tuya device (even though the packaging says Ajax Online). I was able to make it work by editing the tuya.js file and search for "TS0505B", then add an extra entry with ManufacturerName "_TZ3210_mzdax7ha". Change below is the middle line:

            {modelID: 'TS0505B', manufacturerName: '_TZ3210_qxenlrin'},
            {modelID: 'TS0505B', manufacturerName: '_TZ3210_mzdax7ha'}],
        model: 'TS0505B',

I assume this is just a rebranded version, and not directly from Ajax Online.

### Supported color modes

color_temp, color_temp_startup, color_xy

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
