### ISSUE TITLE
images.find is not a function

### ISSUE THREAD

**Issue by ptrdvds** [Koenkk/zigbee2mqtt#12126]
### What happened?

Installed Develco EMIZB-132 to Norwegian HAN port and try to upgrade the firmware.
Reason for upgrade is that i have no readings that make sense.

{
    "current": 65535,
    "current_phase_b": 65535,
    "current_phase_c": 65535,
    "energy": 0,
    "interface_mode": "norwegian_han",
    "power": -8388608,
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "voltage": 65535,
    "voltage_phase_b": 65535,
    "voltage_phase_c": 65535,
    "linkquality": 255
}

### What did you expect to happen?

I expected to upgrade the firmware or firmware check without an error message.
Expected to have sensible readings from the Develco device.

### How to reproduce it (minimal and precise)

Click OTA ->  Check for new updates

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

0x26720700

### Adapter

Conbee II 

### Debug log

Zigbee2MQTT:error 2022-04-09 18:45:18: Failed to check if update available for 'sen13.energy' (images.find is not a function)
Zigbee2MQTT:info  2022-04-09 18:51:56: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"sen13.energy"},"error":"Failed to check if update available for 'sen13.energy' (images.find is not a function)","status":"error","transaction":"0gyky-3"}'

**Comment by davidjb** [comment]
This is due to the zigbee-OTA index.json file being invalid JSON. https://github.com/Koenkk/zigbee-OTA/pull/107 fixes the syntax.
