### ISSUE TITLE
rob_200-017-1 

### ISSUE THREAD

**Issue by WBoerhoop** [Koenkk/zigbee2mqtt#12134]
### What happened?

After the installation of ROBB ROB_200-017-1de pairing performed and everything is visible normally. However, in the zigbee log both ROB_200-017-1 states "Failed to configure 'RobPlug0x'" resulting in no kWh notation.

### What did you expect to happen?

Normal use notation kWh

### Zigbee2MQTT version

v.1.25.0 (zStack3x0 20210120)

### Adapter firmware version

20210120

### Adapter

Slaesh's CC2652RB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8458671/log.txt)

**Comment by WBoerhoop** [comment]
inclusive debug
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8458742/log.txt)

**Comment by WBoerhoop** [comment]
![2022-04-10_12-26-22](https://user-images.githubusercontent.com/58995189/162613931-885e6927-6675-460b-82f2-1275054aa571.png)

**Comment by smulle48** [comment]
Try to update to lates dev. It should be fixed there. Same issue as this:

https://github.com/Koenkk/zigbee2mqtt/issues/12000

**Comment by WBoerhoop** [comment]
Ok, I updated to latest dev, and as far as i can see now , it's fixed
Thanks
