### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by nicks123** [Koenkk/zigbee2mqtt#12148]
### Link

https://www.zigbee2mqtt.io/devices/HS1SA.html

### Database entry

{"id":36,"type":"EndDevice","ieeeAddr":"0x005043c9a7392958","nwkAddr":7490,"manufId":48042,"manufName":"Heiman","powerSource":"Battery","modelId":"SMOK_HV14","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280,1,9,1282],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SMOK_HV14","manufacturerName":"Heiman","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"2018.06.29"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0024c6a3d9","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"2018.06.29","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1649714808283}

### Comments

Please can you add support for Heiman HS1SA-M Smoke Detector that appears to have different model name. 

Zigbee Model: SMOK_HV14

Warning Received message from unsupported device with Zigbee model 'SMOK_HV14' and manufacturer name 'Heiman'

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
