### ISSUE TITLE
Aqara XDD13LM brightness control problem.

### ISSUE THREAD

**Issue by z-x-f** [Koenkk/zigbee2mqtt#12154]
### What happened?

When the brightness is set to 1, the light is turned off, however, when the light is turned on again, the brightness remains at 1, which will cause the light to be turned off again.
I use node-red to control the light, when I use the `brightness_step` parameter to reduce the brightness, the light will be forced off when it is reduced to 1, how can I solve this problem, I remember there was no such problem before.

### What did you expect to happen?

The light will not be turned off when the brightness is reduced to 1.

### Zigbee2MQTT version

1.25

### Adapter firmware version

20220219

### Adapter

zigstar

**Comment by Koenkk** [comment]
Could you add the `turnsOffAtBrightness1` meta option like we do for Philips: https://github.com/Koenkk/zigbee-herdsman-converters/blob/383caa3f380332bd6abebd8c0457a645bbb1cbcc/devices/philips.js#L116

**Comment by z-x-f** [comment]
I tried adding this option but it didn't change anything.

**Comment by z-x-f** [comment]
When the `brightness` is 1, there is a delay of about 2 seconds, then the light will be turned off, and then the `STATE` is still `ON`.
Add or not add `turnsOffAtBrightness1` are the same.

**Comment by Koenkk** [comment]
Could you provide the herdsman debug log when setting brightness 1 (so the light turns off but state stays ON) with `turnsOffAtBrightness1: true`?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by z-x-f** [comment]
Today after I reinstalled z2m and added `turnsOffAtBrightness1`, strangely enough, I could not reproduce the previous problem. This should not be a bug in z2m, I will close this issue, thanks :)
