### ISSUE TITLE
[New device support]: TS0505B / _TZB210_tmi0rihb "Zigbee 3.0 5 in 1 LED Strip Controller Model LM052"

### ISSUE THREAD

**Issue by adgenet** [Koenkk/zigbee2mqtt#12168]
### Link

https://www.amazon.com/dp/B09NSK9ZBK/

### Database entry

{"id":7,"type":"Router","ieeeAddr":"0xa4c1386ad69c73e9","nwkAddr":10818,"manufId":4417,"manufName":"_TZB210_tmi0rihb","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZB210_tmi0rihb","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1649900210479,"defaultSendRequestWhen":"immediate"}

### Comments

I just bought this untested controller and it identifies itself as a "TS0505B" which sounds like it is a supported bulb, but I believe the manufacturer ID "_TZB210_tmi0rihb" is new so it comes up as unsupported.

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
