### ISSUE TITLE
no log more in telnet since the update

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#1218]
Hello, since the update no log comes in SSH/ Telnet, if one enters this command (sudo journalctl -u zigbee2mqtt.service -f)

**Comment by Koenkk** [comment]
Does it work when manually executing `npm start`? (make sure the service isn't running).

**Comment by jeromelaban** [comment]
Nice work on the release !!

I've got a similar issue, but from docker. the logs coming up as empty strings (from a `docker attach`)

**Comment by Koenkk** [comment]
Should be fixed in zigbee2mqtt 1.2.1

**Comment by jeromelaban** [comment]
Works great, thanks for the fast update !

**Comment by salopette** [comment]
It work!!!
