### ISSUE TITLE
Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_c2fmom5z'

### ISSUE THREAD

**Issue by horve000** [Koenkk/zigbee2mqtt#12182]
### Link

https://www.aliexpress.com/item/1005004042745851.html?spm=a2g0o.productlist.0.0.1aa26a9cnC6NQy&algo_pvid=a518bb50-daec-46e6-ac4d-0d8bb06929fe&algo_exp_id=a518bb50-daec-46e6-ac4d-0d8bb06929fe-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000027834253548%22%7D&pdp_pi=-1%3B25.69%3B-1%3B-1%40salePrice%3BEUR%3Bsearch-mainSearch

### Database entry

{"id":16,"type":"Router","ieeeAddr":"0xa4c138d0f1fac722","nwkAddr":9031,"manufId":4417,"manufName":"_TZE200_c2fmom5z","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�B�)i�B�)i�B�)i�B�)i�B�)i�B�)f�B�)i�B�)i","65506":54,"65508":0,"stackVersion":0,"dateCode":"","appVersion":70}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1650027363344,"defaultSendRequestWhen":"immediate"}

### Comments

when i add the device zigbee2mqtt shows me the  error endless only after deleting the the device the error stops.

**Comment by mpavlikWandera** [comment]
@horve000 this seems to be a good place to start 
https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html#instructions 
I know it can be intimidating at first, but @Koenkk cannot add all the devices by himself .... it is just too much
