### ISSUE TITLE
TS011F_plug_3 switching state not fully responding

### ISSUE THREAD

**Issue by WBoerhoop** [Koenkk/zigbee2mqtt#12188]
### What happened?

Did a new pairing with the TS011F_plug_3, 6 Devices were neatly created. 
After creating it I want to turn on the device via state and that worked,  but the "state" was still off and no change in the icon.

### What did you expect to happen?

Changing the display to "on"  and the state icon with a red dot in it.
Also the option to turn the state off again which doesn't work.

### How to reproduce it (minimal and precise)

delete the device and paired it again.
![2022-04-15_21-23-37](https://user-images.githubusercontent.com/58995189/163624346-c6bdae9c-2217-4b28-92d8-eefb62d671c5.jpg)

### Zigbee2MQTT version

V.1.25.0-latest dev

### Adapter firmware version

20210120

### Adapter

Slaesh's CC2652RB

**Comment by WBoerhoop** [comment]
[after restart.txt](https://github.com/Koenkk/zigbee2mqtt/files/8499536/after.restart.txt)

**Comment by SargonofAssyria** [comment]
I had the same problem. In my case the problem was caused by the child_lock.
I created an external converter from the same device but without the child_lock.
Then everything worked as it should.

**Comment by WBoerhoop** [comment]
> I had the same problem. In my case the problem was caused by the child_lock. I created an external converter from the same device but without the child_lock. Then everything worked as it should.

Ok, I can try that, will you upload your "external converter" ??

**Comment by SargonofAssyria** [comment]
[TS011F_TZ3000.js.txt](https://github.com/Koenkk/zigbee2mqtt/files/8501853/TS011F_TZ3000.js.txt)
Remove the .txt and place the file in the data dir and add the external converter.

**Comment by WBoerhoop** [comment]
Used external converter file and Check, it´s working again, 
Thanks SargonofAssyria
