### ISSUE TITLE
[New device support]: Namron Touch Thermostat Black (Namron 4512738)

### ISSUE THREAD

**Issue by robertkj** [Koenkk/zigbee2mqtt#12196]
### Link

https://www.namron.com/products/namron-zigbee-touch-termostat-16a-sort/

### Database entry

{"id":4,"type":"Router","ieeeAddr":"0x1fff000200000200","nwkAddr":20495,"manufId":4644,"manufName":"NAMRON AS","powerSource":"Mains (single phase)","modelId":"4512738","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,3,4,5,9,10,513,516,1794,2820],"outClusterList":[3,1030],"clusters":{"genBasic":{"attributes":{"stackVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":7,"inClusterList":[0,3],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"stackVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"6.9.1.0_r4","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1650181038479,"defaultSendRequestWhen":"immediate"}

### Comments

Same as Namron [4512737](https://www.zigbee2mqtt.io/devices/4512737.html), only black model.

Attempted to add it on my own, but I was not able to get it working. Using code from [4512737](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/namron.js) and the [guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html) I could get it to work in Zigbee2mqtt (I think), but it did not show up in Mosquitto broker/Home assistant so i assume I did something wrong.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
