### ISSUE TITLE
  [New device support]: TS0505B / _TZB210_1ecortg6 "Zigbee 3.0 5 in 1 LED Strip Controller Model LM052"

### ISSUE THREAD

**Issue by adgenet** [Koenkk/zigbee2mqtt#12194]
### Link

https://www.amazon.com//dp/B09PDZN5S7/

### Database entry

{"id":10,"type":"Router","ieeeAddr":"0x003c84fffec8d954","nwkAddr":11338,"manufId":4098,"manufName":"_TZB210_1ecortg6","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZB210_1ecortg6","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1650147308789,"defaultSendRequestWhen":"immediate"}

### Comments

Another version of the controller from #12168, but with Manufacturer: _TZB210_1ecortg6

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
