### ISSUE TITLE
Zigbee2MQTT and Sonoff Zigbee 3.0 Dongle Plus Error

### ISSUE THREAD

**Issue by MI-HASS** [Koenkk/zigbee2mqtt#12199]
### What happened?

I have a RaspberryPi4 running HASS OS. About a week ago I did get Zigbee2MQTT running on a Deconz Conbee II adapter without any problem but I wanted to change it to a Sonoff Zigbee 3.0 Dongle. So I got a new coordinator and I began by stopping the Mosquito broker and then the Zigbee2MQTT add-on's in HA. Then I shutdown the Pi4 to swap USB adapters. When everything came back on, the Mosquito and the Zigbee2MQTT apps were running before I had the opportunity to change the configuration file on the Zigbee2MQTT. I then stopped them both, update the configuration of Zigbee2MQTT with the new "Device Path" for the Sonoff adapter and restarted everything. Now, I'm getting an error that says the following,

`> zigbee2mqtt@1.25.0 start
> node index.js
Zigbee2MQTT:info  2022-04-17 12:18:26: Logging to console and directory: '/config/zigbee2mqtt/log/2022-04-17.12-18-24' filename: log.txt
Zigbee2MQTT:info  2022-04-17 12:18:26: Starting Zigbee2MQTT version 1.25.0 (commit #unknown)
Zigbee2MQTT:info  2022-04-17 12:18:26: Starting zigbee-herdsman (0.14.20)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-04-17 12:18:37: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-04-17 12:18:37: Failed to start zigbee
Zigbee2MQTT:error 2022-04-17 12:18:37: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-04-17 12:18:37: Exiting...
Zigbee2MQTT:error 2022-04-17 12:18:37: undefined
[12:18:39] INFO: Handing over control to Zigbee2mqtt Core ...`

### What did you expect to happen?

Zigbee2MQTT start correctly and devices communicating with HA

### How to reproduce it (minimal and precise)

Doing the steps I describe above

### Zigbee2MQTT version

1.25.0-1

### Adapter firmware version

Z-Stack_3.x.0 firmware

### Adapter

Texas Instrument CC2652P

**Comment by Eggn1n3** [comment]
Try to remove your database.db and state.json files (first backup) and restart the coordinator.
Also, unplug the USB Sonoff for a moment and then restart zigbee2mqtt again without mentioned files.
