### ISSUE TITLE
SMHM-I1 fix battery level and voltage

### ISSUE THREAD

**Issue by unpack8866** [Koenkk/zigbee2mqtt#12204]
### What happened?

Repair battery level and voltage; But I don't know how to modify the voltage unit.
Voltage 2800v is modified to 2800mv; How to modify?

<img width="655" alt="2259741F-5901-4679-B36E-6D0E144295B4" src="https://user-images.githubusercontent.com/40196105/163738458-7b6b34c5-ffe0-41ad-8aa7-7f639e9294d7.png">

const device = {
zigbeeModel: ['SMHM-I1', 'PIR_TPV12'],
model: 'SMHM-I1',
vendor: 'HEIMAN',
description: 'Smart motion sensor',
fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
toZigbee: [],
exposes: [e.occupancy(), e.battery_low(), e.battery(), e.voltage()],
meta: {battery: {voltageToPercentage: '3V_2500'}},
configure: async (device, coordinatorEndpoint, logger) => {
const endpoint = device.getEndpoint(1);
const bindClusters = ['genPowerCfg'];
await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
await reporting.batteryPercentageRemaining(endpoint);
await reporting.batteryVoltage(endpoint);
},
};

module.exports = device;

### Zigbee2MQTT version

1.25

### Adapter firmware version

20220301

### Adapter

cc2652p

**Comment by Koenkk** [comment]
Change `e.voltage()` -> `e.battery_voltage()`

**Comment by unpack8866** [comment]
> Change `e.voltage()` -> `e.battery_voltage()`

It's right! Please fix it, thank you!
<img width="701" alt="A9B1DF27-A573-43E0-A515-385018F225B6" src="https://user-images.githubusercontent.com/40196105/163902056-f9925e90-7de7-458f-9458-33cdc3bc1928.png">

const device = {
    zigbeeModel: ['SMHM-I1', 'PIR_TPV12'],
    model: 'SMHM-I1',
    vendor: 'HEIMAN',
    description: 'Smart motion sensor',
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
    toZigbee: [],
    exposes: [e.occupancy(), e.battery_low(), e.battery(), e.battery_voltage()],  
    meta: {battery: {voltageToPercentage: '3V_2500'}},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.batteryVoltage(endpoint);

   },
};

module.exports = device;

**Comment by Koenkk** [comment]
great, added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
