### ISSUE TITLE
TuYa TS011F_plug_1 Indicator_mode function broken.

### ISSUE THREAD

**Issue by redpixy** [Koenkk/zigbee2mqtt#12219]
### What happened?

Tried changing the Indicator_mode to off on TuYa TS011F_plug_1.
The plug's led indication remains lit up

### What did you expect to happen?

Led Indicator light to go off

### How to reproduce it (minimal and precise)

Changed the state to off in the GUI.

### Zigbee2MQTT version

 1.25.0

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by Koenkk** [comment]
Probably your device uses a different data point (this can very per plug model). To find out which follow https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#requirements-and-caveats
