### ISSUE TITLE
Callback not defined

### ISSUE THREAD

**Issue by maxpd1** [Koenkk/zigbee2mqtt#1222]
Yesterday my zigbee adapter again lost connection to zigbee and now throws the following error messages when I want to restart the adapter. Restart doesn't work. Have to restart the raspberry completely.

zigbee.0 | 2019-03-10 07:53:14.667 | error | exception by stop: callback is not defined
-- | -- | -- | --
zigbee.0 | 2019-03-10 07:53:14.666 | error | at Signal.wrap.onsignal (internal/process.js:208:44)
zigbee.0 | 2019-03-10 07:53:14.666 | error | at process.emit (events.js:208:7)
zigbee.0 | 2019-03-10 07:53:14.666 | error | at emitNone (events.js:106:13)
zigbee.0 | 2019-03-10 07:53:14.666 | error | at Object.onceWrapper (events.js:313:30)
zigbee.0 | 2019-03-10 07:53:14.666 | error | at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5023:21)
zigbee.0 | 2019-03-10 07:53:14.666 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:52:11)
zigbee.0 | 2019-03-10 07:53:14.666 | error | ReferenceError: callback is not defined
zigbee.0 | 2019-03-10 07:53:14.665 | error | uncaught exception: callback is not defined

zigbee.0 | 2019-03-10 07:53:08.607 | error | exception by stop: callback is not defined
-- | -- | -- | --
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:780:25)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at process.exit (internal/process.js:157:15)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at process.emit (events.js:211:7)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at emitOne (events.js:116:13)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Object.onceWrapper (events.js:315:30)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at process.stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5023:21)
zigbee.0 | 2019-03-10 07:53:08.607 | error | at Object.unload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:52:11)
zigbee.0 | 2019-03-10 07:53:08.607 | error | ReferenceError: callback is not defined
zigbee.0 | 2019-03-10 07:53:08.606 | error | uncaught exception: callback is not defined
zigbee.0 | 2019-03-10 07:53:08.590 | error | already running

**Comment by Koenkk** [comment]
This is the zigbee2mqtt issue tracker, as your are using iobroker, please open na issue there.
