### ISSUE TITLE
Only first bulb in group is updated when using `color_temp_step` or `color_temp_move`

### ISSUE THREAD

**Issue by andrebk** [Koenkk/zigbee2mqtt#12254]
### What happened?

I have an [IKEA bulb](https://www.zigbee2mqtt.io/devices/LED1537R6_LED1739R5.html#ikea-led1537r6%252Fled1739r5) that supports using `color_temp_step` and `color_temp_move` commands to change the color temperature, in addition to just setting an absolute value as normal.

I have created a group with a few of these bulbs, and use the step and move commands to control the color temperature using an [IKEA remote](https://www.zigbee2mqtt.io/devices/E1524_E1810.html#ikea-e1524%252Fe1810) and home assistant. This works great, all the bulbs respond quickly, super happy.

The problem is that when looking at the state of the bulbs in z2m UI (or in home assistant) only the first bulb in the group has its state updated when the color temperature changes. For the other bulbs the color temperature value remains unchanged.

### What did you expect to happen?

I expected that the values for the bulbs state in z2m would reflect it's real world state, and that the state would update when the real world state changes.

### How to reproduce it (minimal and precise)

1. Add a couple of bulbs that support `color_temp_step` command
2. Create a group in z2m containing the bulbs (friendly name `office/lights` for this example)
3. Publish the following MQTT message
```
topic: zigbee2mqtt/office/lights/set
payload: {"color_temp_step": 100}
```
4. Observe that only the first bulb in the group has its color temperature updated in z2m UI

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

```
Zigbee2MQTT:debug 2022-04-23 17:22:29: Received Zigbee message from 'office/remote', type 'commandTradfriArrowSingle', cluster 'genScenes', data '{"value":256,"value2":13}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-04-23 17:22:29: MQTT publish: topic 'zigbee2mqtt/office/remote', payload '{"action":"arrow_right_click","battery":87,"linkquality":132,"update":{"state":"idle"},"update_available":null}'
Zigbee2MQTT:info  2022-04-23 17:22:29: MQTT publish: topic 'zigbee2mqtt/office/remote/action', payload 'arrow_right_click'
Zigbee2MQTT:debug 2022-04-23 17:22:29: Received MQTT message on 'zigbee2mqtt/office/ceiling_lights/set' with data '{"color_temp_step": 102, "transition": 1}'
Zigbee2MQTT:debug 2022-04-23 17:22:29: Publishing 'set' 'color_temp_step' to 'office/ceiling_lights'
Zigbee2MQTT:debug 2022-04-23 17:22:31: Received Zigbee message from 'office/bulb_1', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTemperature":352}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-04-23 17:22:31: MQTT publish: topic 'zigbee2mqtt/office/ceiling_lights', payload '{"brightness":71,"color_mode":"color_temp","color_temp":352,"state":"ON"}'
Zigbee2MQTT:info  2022-04-23 17:22:31: MQTT publish: topic 'zigbee2mqtt/office/bulb_1', payload '{"brightness":200,"color_mode":"color_temp","color_temp":352,"color_temp_startup":65535,"linkquality":138,"power_on_behavior":"previous","state":"ON","update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:debug 2022-04-23 17:22:31: Publishing 'set' 'transition' to 'office/ceiling_lights'

```

**Comment by martonperei** [comment]
I'm having the same issue with Hue bulbs and a sonoff zigbee coordinator. 
Only the first bulb updates color temp in the UI. If I click the refresh button, it updates to the correct value.
