### ISSUE TITLE
[New device support]: Orvibo DS20Z07B - zigbee model 4a33f5ea766a4c96a962b371ffde9943

### ISSUE THREAD

**Issue by RatheeM** [Koenkk/zigbee2mqtt#12252]
### Link

http://orvibo.ae/s/

### Database entry

const definition = {     zigbeeModel: ['4a33f5ea766a4c96a962b371ffde9943'],     model: 'DS20Z07B',     vendor: 'ORVIBO',     description: 'Downlight (S series)',     fromZigbee: [], // We will add this later     toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).     extend: extend.light_onoff_brightness_colortemp({colorTempRange: [166, 370]}), };

### Comments

Paired the device to Z2M - pair successfull but unsupported

Created orvibo.js in zigbee2mqtt folder next to config.yaml with the following:
const definition = {
    zigbeeModel: ['4a33f5ea766a4c96a962b371ffde9943'],
    model: 'DS20Z07B',
    vendor: 'ORVIBO',
    description: 'Downlight (S series)',
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [166, 370]}),
};

Added orvibo.js to external_connector in config.yaml, and changed log level to debug.

Now unsupported tag disappeared from Z2M UI, exposes are visible. But when I execute anything it says"
No converter available - in the log

I could not understand the further instructions in Z2M website regarding adding converter. 

Please help. 

Hardware:
HA with Supervisor on Debian 11 - HA supervised install
Z2M through Conbee II

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['4a33f5ea766a4c96a962b371ffde9943'],
    model: 'DS20Z07B',
    vendor: 'ORVIBO',
    description: 'Downlight (S series)',
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [166, 370]}),
};

module.exports = definition;
```

### Supported color modes

onoff_brightness_colortemp

### Color temperature range

166-370 probably. Not sure. The min max through Dev Console - Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":0,"colorTempPhysicalMax":65279}

**Comment by Koenkk** [comment]
Try removing:

```js
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
```

**Comment by RatheeM** [comment]
Thanks for your reply. Already tried that. Does not work.

**Comment by Koenkk** [comment]
I'm quite certain it should work, added it directly now can you check the latest dev branch?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by RatheeM** [comment]
Controls still do not work.

I have shifted to Z2M Edge.

Log:
Debug 2022-04-24 23:16:37Received MQTT message on 'zigbee2mqtt/0x847127fffe6519ec/set' with data '{"state":"OFF"}'
Debug 2022-04-24 23:16:37Publishing 'set' 'state' to '0x847127fffe6519ec'
Warning 2022-04-24 23:16:41Failed to ping '0x847127fffe6519ec' (attempt 1/1, Read 0x847127fffe6519ec/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))

**Comment by RatheeM** [comment]
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://core-mosquitto
serial:
  port: /dev/ttyACM0
  adapter: deconz
external_converters:
  - orvibo.js

**Comment by RatheeM** [comment]
Orvibo.js is
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['4a33f5ea766a4c96a962b371ffde9943'],
    model: 'DS20Z07B',
    vendor: 'ORVIBO',
    description: 'Downlight (S series)',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [166, 370]}),
};

module.exports = definition;`

**Comment by RatheeM** [comment]
Working now. Thanks.

**Comment by hirzel23** [comment]
hi @RatheeM may I ask? is it all working fine include adjusting the brightness?

**Comment by RatheeM** [comment]
Yes. It’s working wonderful.

**Comment by RatheeM** [comment]
Dev.
