### ISSUE TITLE
First thank you and then request

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#1226]
First of all, thank you very much for getting us to update the firmware without having to pair the devices again, now I can even change USB and the 2 minutes the network is completely stable.

If we don't manually change the PanID configuration in configuration.yaml, we can move the data folder to another installation and keep it working?, it would be interesting for a High Availability solution.

Another question is, can you show the current firmware version in HomeAssistant? In the integrations appears "Zigbee2Mqtt 1.2.1" is it possible something like "Zigbee2Mqtt 1.2.1 (XXXX)"?

![image](https://user-images.githubusercontent.com/15717847/54087718-0dd7b680-4356-11e9-9654-aa2b8c1af755.png)

**Comment by Koenkk** [comment]
- You can indeed move the data folder to other systems for this purpose.
- I will take a look at the firmware version, something similar has been requested in #1213, this is planned for zigbee2mqtt 1.3
