### ISSUE TITLE
No converter available for 'on_time' 

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#12276]
### What happened?

When trying to use the `on_time` property for genOnOff which does work, we get an error:
```
No converter available for 'on_time' (3)
```

I set the state like this:
```bash
mosquitto_pub -t zigbee2mqtt/light/office/desk/bulb/set -m '{"state": "ON", "on_time": 3}'
```

It does actually work as expected though, so I think the error is just not correct?

### What did you expect to happen?

No message about no converter

### How to reproduce it (minimal and precise)

```bash
mosquitto_pub -t zigbee2mqtt/light/office/desk/bulb/set -m '{"state": "ON", "on_time": 3}'
```

### Zigbee2MQTT version

1.25.0-dev commit: 11b41563

### Adapter firmware version

20220219

### Adapter

zzhp

**Comment by Koenkk** [comment]
For what device is this? The `on_time` should be matched by the `on_off` https://github.com/Koenkk/zigbee-herdsman-converters/blob/87c2535737b04e6d69703ad77dd0281e4cd0d4f8/converters/toZigbee.js#L265

**Comment by sjorge** [comment]
On 2022-04-25 20:20, Koen Kanters wrote:

> For what device is this? The on_time should be matched by the on_off 
> https://github.com/Koenkk/zigbee-herdsman-converters/blob/87c2535737b04e6d69703ad77dd0281e4cd0d4f8/converters/toZigbee.js#L265
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

I tried with a Hue BT GU10 and with an Ikea GU10, yeah it should match 
so I'm not understanding why it is complaining

-- 
~ sjorge

Links:
------
[1] 
https://github.com/Koenkk/zigbee2mqtt/issues/12276#issuecomment-1108892989
[2]

**Comment by sjorge** [comment]
Also it’s sending the correct payload to the device too, just spewing the error

**Comment by Koenkk** [comment]
Found the issue, should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by sjorge** [comment]
Yep that seems to have done the trick
