### ISSUE TITLE
[Feature request]: Z-Stack_3.x.0 Zigbee packet sniffer firmware images for CC2652/CC1352 to use with Wireshark?

### ISSUE THREAD

**Issue by Hedda** [Koenkk/zigbee2mqtt#12274]
### Is your feature request related to a problem? Please describe

Requesting Z-Stack_3.x.0 Zigbee packet sniffer firmware images for CC2652P//CC2652R/CC2652RB/CC1352P to use with Wireshark:

https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

https://github.com/Koenkk/Z-Stack-firmware/

https://software-dl.ti.com/simplelink/esd/simplelink_cc13x2_26x2_sdk/3.30.00.03/exports/docs/zigbee/html/zigbee/packet_sniffer.html

### Describe the solution you'd like

Z-Stack_3.x.0 Zigbee packet sniffer firmware images for CC2652P//CC2652RCC2652RB/CC1352P on https://github.com/Koenkk/Z-Stack-firmware/

### Describe alternatives you've considered

Trying to build and compile firmware image following https://software-dl.ti.com/simplelink/esd/simplelink_cc13x2_26x2_sdk/3.30.00.03/exports/docs/zigbee/html/zigbee/packet_sniffer.html

### Additional context

Would be interesting to have easy access to Zigbee packet sniffer firmware images for the most popular CC26x2/CC13x2 adapters:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md

Personally think most popular adapters are Electrolama zzh (CC2652R) + SONOFF Zigbee 3.0 USB Dongle Plus by ITead (CC2652P)

**Comment by Hedda** [comment]
Still wanted I think?

**Comment by Koenkk** [comment]
I don't see a sniffer project in the simplelink SDK. Seems this is already included in the smart rf packet sniffer 2 package

<img width="909" alt="Screenshot 2022-05-26 at 18 58 32" src="https://user-images.githubusercontent.com/2892853/170537674-c1a33064-dfa4-451b-95bb-5f39bf01d0c9.png">
