### ISSUE TITLE
[New device support]: Coswall Zigbee 3.0 Tuya Wall EU Socket 

### ISSUE THREAD

**Issue by don8atas** [Koenkk/zigbee2mqtt#12293]
### Link

https://www.aliexpress.com/item/1005002518419678.html?spm=a2g0o.order_list.0.0.45171802m4Du5t

### Database entry

{"id":20,"type":"Router","ieeeAddr":"0x60a423fffe92c338","nwkAddr":14542,"manufId":4098,"manufName":"_TZ3000_rul9yxcc","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_rul9yxcc","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1651002387390,"defaultSendRequestWhen":"immediate"}

### Comments

Zigbee Model
    TS011F
Zigbee Manufacturer
    _TZ3000_rul9yxcc
Support status
   Not supported

**Comment by st-pavel** [comment]
+
