### ISSUE TITLE
Nous A1Z does not return energy

### ISSUE THREAD

**Issue by angustPL** [Koenkk/zigbee2mqtt#12314]
### What happened?

Nous A1Z does not return energy
in the Tuya app, the value is correctly set

{"id":6,"type":"Router","ieeeAddr":"0xa4c1389bb6508073","nwkAddr":7346,"manufId":4417,"manufName":"_TZ3000_ksw8qtmt","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":236,"activePower":0,"rmsCurrent":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,14]}},"genOnOff":{"attributes":{"20480":1,"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"53264":1,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022ab744f","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0022ab744f","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0022ab744f","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":680236614},"lastSeen":1651224436756,"defaultSendRequestWhen":"immediate"}

state_class: total_increasing
child_lock: UNLOCK
current: 0
device:
  applicationVersion: 74
  dateCode: ''
  friendlyName: Kuchnia Czajnik
  hardwareVersion: 1
  ieeeAddr: '0xa4c1389bb6508073'
  manufacturerID: 4417
  manufacturerName: _TZ3000_ksw8qtmt
  model: TS011F_plug_1
  networkAddress: 7346
  powerSource: Mains (single phase)
  stackVersion: 0
  type: Router
  zclVersion: 3
energy: null
indicator_mode: off/on
linkquality: 36
power: 0
power_outage_memory: 'on'
update:
  state: null
update_available: null
voltage: 234
unit_of_measurement: kWh
device_class: energy
friendly_name: Kuchnia Czajnik energy
last_reset: '2022-04-29T10:30:00+00:00'

### Zigbee2MQTT version

1.25.0-1

### Adapter firmware version

20211217

### Adapter

CC2652P

**Comment by espeka44** [comment]
I have the same issue after did a new z2m installation and re-pair devices again.
@angustPL, you've closed this issue but how did you do to solve it ?
