### ISSUE TITLE
HS1VS-EF seems to have different names

### ISSUE THREAD

**Issue by Oggymator** [Koenkk/zigbee2mqtt#12310]
### What happened?

Hi,

I have the HS1VS-EF from HEIMAN and the Name of the device is "Vibration-EF-3.0".
In the dev Branch the HS1VS-EF already exists, but with a different name "Vibration-EF_3.0".
It looks like, that HEIMAN use sometimes underline and sometimes minus.

kind regards
Tobias

### What did you expect to happen?

Vibration-EF-3.0 is the same like Vibration-EF_3.0

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

0x26660700

### Adapter

conbee II

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) (and next release on 1 May)
