### ISSUE TITLE
[New device support]: Villeroy & Boch Subway 3.0 ZigBee Home Automation Kit

### ISSUE THREAD

**Issue by tobiasfrank87** [Koenkk/zigbee2mqtt#12323]
### Link

https://www.villeroy-boch.de/bad-und-wellness/produkte/Subway-3.0-ZigBeeR-Home-Automation-Kit-fuer-Waschbeckenunterschrank-Rechteck-C5850000.html

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0xb4e3f9fffeb291e8","nwkAddr":39998,"manufId":4644,"manufName":"L&S","powerSource":"Mains (single phase)","modelId":"5991711","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.5.3_r57","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1651346847257,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to connect this device with both the standard and the edge variant but no luck. With ZHA via homeassistant, the device works and is beeing recognized correctly.

![L S S-ER1 2 24 5 A](https://user-images.githubusercontent.com/93088246/166120175-d87adb86-87f1-45a2-ae5f-a771bf29f066.jpg)
![L S S-ER1 2 24 5 A_2](https://user-images.githubusercontent.com/93088246/166120176-c7e2e777-eff5-4260-8502-5999b27ed6ea.jpg)
.

### Supported color modes

coldwhite & warmwhite

### Color temperature range

{"colorTempPhysicalMin":160,"colorTempPhysicalMax":450}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
