### ISSUE TITLE
OTA updates hang and are not updated by Tuya TS0601_thermostat _TZE200_ckud7u2l

### ISSUE THREAD

**Issue by VikeDragon** [Koenkk/zigbee2mqtt#12339]
### What happened?

Greetings!
OTA updates hang and are not updated by Tuya TS0601_thermostat _TZE200_ckud7u2l.
Why are updates requested, but I get an error when updating
"Update of '0x....' failed (No new image available)"?
Please help me figure this out.
![изображение](https://user-images.githubusercontent.com/44431640/166159705-1d844953-bb3b-4fdb-9e34-7271532b2d0a.png)

### What did you expect to happen?

OTA updates my thermostats

### How to reproduce it (minimal and precise)

Start Ota update

### Zigbee2MQTT version

1.25.0-1 

### Adapter firmware version

20211217

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus (zStack3x0)

### Debug log

error 2022-05-01 23:28:34: Update of '0x....' failed (No new image available)

**Comment by VikeDragon** [comment]
Help needed !

**Comment by VikeDragon** [comment]
Not solved ...

**Comment by VikeDragon** [comment]
Not solved ...

**Comment by staastas** [comment]
Maybe this will help you https://github.com/Koenkk/zigbee2mqtt/issues/14345

**Comment by VikeDragon** [comment]
Not solved ...

**Comment by VikeDragon** [comment]
Not solved...

**Comment by m0wlheld** [comment]
Still not addressed / solved. Columns Firmware Date and Firmware Version stay empty and requesting OTA check results in error (2 times):

> Failed to check if update available for '0x00....270c' (No image available for imageType '5634')

**Comment by m0wlheld** [comment]
Still unresolved in 1.29.1 ... when checking for update, the error message is

> Failed to check if update available for '0x00....270c' (No image available for imageType '5634')

**Comment by Koenkk** [comment]
We don't have an image for this device yet. To find out follow: https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html

**Comment by m0wlheld** [comment]
Okay, to much effort for an update (for me). Unsubscribing from this issue. Thanks for the feedback.

**Comment by florian-asche** [comment]
just for documentation: i checked tuya for updates, there is currently nothing new.
