### ISSUE TITLE
configuration-adapter mismatch - but what is the mismatch?

### ISSUE THREAD

**Issue by MrRusch** [Koenkk/zigbee2mqtt#12331]
### What happened?

Zigbee devices suddenly stopped responding. Restarted zigbee2mqtt service and notice the attached debug log.

### What did you expect to happen?

I expected there to be some hint as to what the mismatch is. But the values that are displayed are all the same.

### How to reproduce it (minimal and precise)

Restart service and check logs.

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

<= 20201101

### Adapter

CC2538+CC2592 ZB3.0

### Debug log

May  1 15:07:16 raspberrypi systemd[1]: Started zigbee2mqtt.
May  1 15:07:16 raspberrypi npm[22032]: > zigbee2mqtt@1.25.0 start /opt/zigbee2mqtt
May  1 15:07:16 raspberrypi npm[22032]: > node index.js
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:debug 2022-05-01 15:07:20: Loaded state from file /opt/zigbee2mqtt/data/state.json
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:info  2022-05-01 15:07:20: Logging to console and directory: '/var/log' filename: zigbee2mqtt2.log
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:info  2022-05-01 15:07:20: Starting Zigbee2MQTT version 1.25.0 (commit #6f1460e4)
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:info  2022-05-01 15:07:20: Starting zigbee-herdsman (0.14.20)
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:debug 2022-05-01 15:07:20: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":true},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"path":"/dev/ttyACM0"}}'
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: Configuration is not consistent with adapter state/backup!
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: - PAN ID: configured=6755, adapter=6755
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: - Extended PAN ID: configured=00124b0009d7f112, adapter=00124b0009d7f112
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: - Network Key: configured=XXX, adapter=XXX
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: - Channel List: configured=11, adapter=11
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: Please update configuration to prevent further issues.
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: If you wish to re-commission your network, please remove coordinator backup at /opt/zigbee2mqtt/data/coordinator_backup.json.
May  1 15:07:20 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:20: Re-commissioning your network will require re-pairing of all devices!
May  1 15:07:21 raspberrypi npm[22032]: (node:22044) UnhandledPromiseRejectionWarning: Error: startup failed - configuration-adapter mismatch - see logs above for more information
May  1 15:07:21 raspberrypi npm[22032]:     at ZnpAdapterManager.determineStrategy (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
May  1 15:07:21 raspberrypi npm[22032]:     at ZnpAdapterManager.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
May  1 15:07:21 raspberrypi npm[22032]: (node:22044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
May  1 15:07:21 raspberrypi npm[22032]: (node:22044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
May  1 15:07:21 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:21: Error while starting zigbee-herdsman
May  1 15:07:21 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:21: Failed to start zigbee
May  1 15:07:21 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:21: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
May  1 15:07:21 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:21: Exiting...
May  1 15:07:21 raspberrypi npm[22032]: Zigbee2MQTT:error 2022-05-01 15:07:21: Error: startup failed - configuration-adapter mismatch - see logs above for more information
May  1 15:07:21 raspberrypi npm[22032]:     at ZnpAdapterManager.determineStrategy (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
May  1 15:07:21 raspberrypi npm[22032]:     at ZnpAdapterManager.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
May  1 15:07:21 raspberrypi npm[22032]: (node:22044) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

**Comment by Gadzhi13** [comment]
@MrRusch any luck with the problem? having the same one right now

**Comment by Koenkk** [comment]
Fixed now thanks to @gneely74 !

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.
