### ISSUE TITLE
[New device support]: Philips Hue Wellner white ambiance E27 806lm with Bluetooth 929003054101

### ISSUE THREAD

**Issue by wila91** [Koenkk/zigbee2mqtt#12348]
### Link

https://www.philips-hue.com/fi-fi/p/hue-white--tunnelmavalo-wellner-poytalamppu/8719514341395

### Database entry

{"id":24,"type":"Router","ieeeAddr":"0x001788010b9d9fd1","nwkAddr":4447,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003054101","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"startUpColorTemperature":366,"colorMode":2,"colorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20211210","swBuildId":"1.93.7","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1651483459142,"defaultSendRequestWhen":"immediate"}

### Comments

I think i got it working. Seams like this Philips Hue White Ambiance Wellner Light is only on limited marked but would be good if there is build in support.

The lamp inside is Philips Hue Wellner white ambiance E27 806lm with Bluetooth

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['929003054101'],
    model: '929003054101',
    vendor: 'Philips',
    description: 'Philips Hue Wellner white ambiance E27 806lm with Bluetooth!',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]})
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    // - extend.light_onoff_brightness_colortemp_color(),
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

### Supported color modes

white ambiance

### Color temperature range

 2022-05-02 14:06:36Read result of 'lightingColorCtrl': {"colorTempPhysicalMax":454,"colorTempPhysicalMin":153}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
