### ISSUE TITLE
Vimar 19592 - absurd problem

### ISSUE THREAD

**Issue by ghost** [Koenkk/zigbee2mqtt#12360]
### What happened?

It's been months I have 9 smart switch Vimar 19592 setting in zigbee2mqtt, pairing without problem, operating without problem.
Yesterday I pairing the new Vimar but the pairing was able after many attempts.
So I restart my Raspberry and now I have only 3 switch that work fine, the other 7 the LQI is N/A and don't work.
The other device, Frient (temperature sensor) and Sonoff (door sensor) work fine, but the Vimar have problem ....

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

0x26720700

### Adapter

Conbee II

### Debug log

No problem evidenced in the log file ....

**Comment by RitaSghe** [comment]
Update to the 1.25.1 version but nothing is change ...

**Comment by RitaSghe** [comment]
Today after many test no Vimar work ....

**Comment by RitaSghe** [comment]
What is the problem stupid arrogant baby?
You do it on purpose to look the other way or you are a really dickhead?

**Comment by RitaSghe** [comment]
Fuck you stupid shitface ...
I know you read my post, asshole, fuck you .....

**Comment by RitaSghe** [comment]
So, what is your problem?
You hate woman? You're misogynist?
You hate italian? You're racist?
Or simply you're astupid arrogant baby?

Maybe all three, in any case, fuck you ......

**Comment by RitaSghe** [comment]
Now I know who you are ...
You are frustrated at the work and submissive in family ...
Everyone laughs at you, you are the greatest fool in the village ......
This project is the only place where you can control, but in any case you're still the same stupid idiot .....
