### ISSUE TITLE
Heiman SMHM-I1 Motion Sensor tamper entity

### ISSUE THREAD

**Issue by migor7** [Koenkk/zigbee2mqtt#12375]
### What happened?

After updating z2m to version 1.25.1-1, the tamper entity disappeared from the Heiman SMHM-I1 Motion Sensor

### Zigbee2MQTT version

1.25.1-1

### Adapter firmware version

20201010

### Adapter

zStack30x

**Comment by Koenkk** [comment]
This is not supported by the device, see https://github.com/Koenkk/zigbee2mqtt/issues/12076 (CC @unpack8866)

**Comment by migor7** [comment]
> This is not supported by the device, see #12076 (CC @unpack8866)

If I restore version 1.25.1-0, tamper works fine and responds to contact opening

**Comment by unpack8866** [comment]
> > This is not supported by the device, see #12076 (CC @unpack8866)
> 
> If I restore version 1.25.1-0, tamper works fine and responds to contact opening

This is my device pcb board; no tamper on it
![411651712980_ pic](https://user-images.githubusercontent.com/40196105/166850809-8033862f-7038-40fe-8340-d629c59802d2.jpg)
![421651712980_ pic](https://user-images.githubusercontent.com/40196105/166850822-5a0e1c77-c3f5-4300-a33d-ca9075f247f1.jpg)

**Comment by migor7** [comment]
> > > This is not supported by the device, see #12076 (CC @unpack8866)
> > 
> > 
> > If I restore version 1.25.1-0, tamper works fine and responds to contact opening
> 
> This is my device pcb board; no tamper on it ![411651712980_ pic](https://user-images.githubusercontent.com/40196105/166850809-8033862f-7038-40fe-8340-d629c59802d2.jpg) ![421651712980_ pic](https://user-images.githubusercontent.com/40196105/166850822-5a0e1c77-c3f5-4300-a33d-ca9075f247f1.jpg)

![IMG_20220505_060131](https://user-images.githubusercontent.com/75983798/166858140-da29cf0c-cd1f-43e0-a4a8-015ab87c9183.jpg)
I have this version. there is a tamper button

**Comment by unpack8866** [comment]
maybe two hardware versions；Does your version have a voltage display?

**Comment by migor7** [comment]
> maybe two hardware versions；Does your version have a voltage display?

my version without voltage display

**Comment by Koenkk** [comment]
Can you both provide the data/database.db of this device?

**Comment by migor7** [comment]
> Can you both provide the data/database.db of this device?

{"id":28,"type":"EndDevice","ieeeAddr":"0x000d6f0010dceb04","nwkAddr":24429,"manufId":4619,"manufName":"GS","powerSource":"Battery","modelId":"SMHM-I1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,65526],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SMHM-I1","manufacturerName":"GS","powerSource":3,"zclVersion":1,"appVersion":22,"stackVersion":2,"hwVersion":16,"dateCode":"2018.3.7","swBuildId":"1.1.1"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00194b4faa","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00194b4faa","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":22,"stackVersion":2,"hwVersion":16,"dateCode":"2018.3.7","swBuildId":"1.1.1","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1045631717},"lastSeen":1651693804349,"defaultSendRequestWhen":"immediate"}

**Comment by unpack8866** [comment]
{"id":5,"type":"EndDevice","ieeeAddr":"0x00124b0014afcd96","nwkAddr":61936,"manufId":0,"manufName":"Feibit","powerSource":"Battery","modelId":"SMHM-I1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClusterList":[0,1,1280],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"SMHM-I1","manufacturerName":"Feibit","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":4,"hwVersion":1,"dateCode":"08/09/2021 19:57","swBuildId":"08/09/2021 19:57"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0022ab7114","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":31}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0022ab7114","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":3,"stackVersion":4,"hwVersion":1,"dateCode":"08/09/2021 19:57","swBuildId":"08/09/2021 19:57","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1045631717},"lastSeen":1651737303857,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
So seems some version of this device have the tamper switch and some don't (you can see the `dateCode` differs). I would actually prefer to add the tamper back and make a note on the device page (this keeps things simple).

**Comment by unpack8866** [comment]
> So seems some version of this device have the tamper switch and some don't (you can see the `dateCode` differs). I would actually prefer to add the tamper back and make a note on the device page (this keeps things simple).

Yes, you're right!

**Comment by Koenkk** [comment]
Added it back

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
