### ISSUE TITLE
[New device support]: LDS ZBT-CCTLight-GU100001

### ISSUE THREAD

**Issue by timwar** [Koenkk/zigbee2mqtt#12371]
### Link

https://www.ledlampenkopen.nu/led-spots/led-lamp-gu10-ynoa-smart-home-zigbee-3-0-cct-dimbaar.html

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0x847127fffe99deef","nwkAddr":27437,"manufId":4456,"manufName":"LDS","powerSource":"Mains (single phase)","modelId":"ZBT-CCTLight-GU100001","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64642],"outClusterList":[25],"clusters":{"genIdentify":{"attributes":{"identifyTime":0}},"genOnOff":{"attributes":{"onOff":1}},"genBasic":{"attributes":{"powerSource":1,"zclVersion":3}}},"binds":[{"cluster":33,"type":"endpoint","deviceIeeeAddress":"0x00212effff0614a1","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff0614a1","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff0614a1","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":60,"maxRepIntval":3600,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20200803","swBuildId":"2.07.03","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1651602027936,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to create the converter file, but still get 'Empty exposes definition'. Tried to put cluster information into fromZigbee and toZigbee. But after restarting of Zigbee2mqtt, I get an "bad gateway" while reaching 
 (http://192.168.178.152:8123/xxxxxxxx_zigbee2mqtt).
I have put 'ynoalds.js' in the same directory as configuration.yaml and submitted the 'ynoalds.js' at External converters under settings of Zigbee2mqtt.
version: 1.25.1-1

### log information of Zigbee2mqtt
Zigbee2MQTT:warn  2022-05-03 20:10:26: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-05-03 20:10:26: Succesfully pinged '0x847127fffe99deef' (attempt 1/2)
Zigbee2MQTT:debug 2022-05-03 20:13:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:18:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:20:27: Received Zigbee message from '0x847127fffe99deef', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2022-05-03 20:20:27: Received message from unsupported device with Zigbee model 'ZBT-CCTLight-GU100001' and manufacturer name 'LDS'
Zigbee2MQTT:warn  2022-05-03 20:20:27: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-05-03 20:20:27: Succesfully pinged '0x847127fffe99deef' (attempt 1/2)
Zigbee2MQTT:debug 2022-05-03 20:23:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:28:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:30:29: Received Zigbee message from '0x847127fffe99deef', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2022-05-03 20:30:29: Received message from unsupported device with Zigbee model 'ZBT-CCTLight-GU100001' and manufacturer name 'LDS'
Zigbee2MQTT:warn  2022-05-03 20:30:29: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-05-03 20:30:29: Succesfully pinged '0x847127fffe99deef' (attempt 1/2)
Zigbee2MQTT:debug 2022-05-03 20:33:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:38:25: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-05-03 20:40:30: Received Zigbee message from '0x847127fffe99deef', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2022-05-03 20:40:30: Received message from unsupported device with Zigbee model 'ZBT-CCTLight-GU100001' and manufacturer name 'LDS'
Zigbee2MQTT:warn  2022-05-03 20:40:30: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-05-03 20:40:30: Succesfully pinged '0x847127fffe99deef' (attempt 1/2)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['BT-CCTLight-GU100001'],
    model: 'ZBT-CCTLight-GU100001',
    vendor: 'LDS',
    description: 'Smart LED GU10 White CCT',
   // fromZigbee: [fz.genBasic,fz.genIdentity,fz.genGroups,fz.genScenes,fz.genOnOff,fz.genLevelCtrl,fz.lightingColorCtrl,fz.touchlink,fz.heimanSpecificInfraRedRemote],
    //toZigbee: [tz.genOta],
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

### Supported color modes

none

### Color temperature range

none

**Comment by timwar** [comment]
I have reset the lamp to factory default and attached the bulb to a Hue bridge to see wait information I could get from this bulb. I managed the get this information in json format, with the help of Hue debug tool, from the bulb:
{
	"state": {
		"on": true,
		"bri": 50,
		"ct": 370,
		"alert": "select",
		"colormode": "ct",
		"mode": "homeautomation",
		"reachable": true
	},
	"swupdate": {
		"state": "notupdatable",
		"lastinstall": "2022-05-04T14:58:15"
	},
	"type": "Color temperature light",
	"name": "Ynoa1",
	"modelid": "ZBT-CCTLight-GU100001",
	"manufacturername": "LDS",
	"productname": "Color temperature light",
	"capabilities": {
		"certified": false,
		"control": {
			"ct": {
				"min": 153,
				"max": 370
			}
		},
		"streaming": {
			"renderer": false,
			"proxy": false
		}
	},
	"config": {
		"archetype": "ceilinground",
		"function": "functional",
		"direction": "omnidirectional"
	},
	"uniqueid": "84:71:27:ff:fe:99:de:ef-01",
	"swversion": "2.07.03"
}
Can I use this in the converter file?

**Comment by SjaakvE** [comment]
Any update on this. Did anyone got this device to work? I received 4 units and they come up as unsupported.

**Comment by timwar** [comment]
> Any update on this. Did anyone got this device to work? I received 4 units and they come up as unsupported.

Hey SjaakvE, I'm lost in trying to solve this. I did not managed to create a correct convertor file. I keep having an unsopprted file as well :(.
Tim

**Comment by timwar** [comment]
I retried it again to create an config file. Atleast I'm a step further, because after using the converter file Zigbee2MQTT keeps running.
I got this message in my log file:
------------------------------------------------------------
Zigbee2MQTT:debug 2022-08-11 14:38:01: Received Zigbee message from 'Ynoa_white_01', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Zigbee2MQTT:warn  2022-08-11 14:38:01: Received message from unsupported device with Zigbee model 'ZBT-CCTLight-GU100001' and manufacturer name 'LDS'
Zigbee2MQTT:warn  2022-08-11 14:38:01: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-08-11 14:38:01: Device 'Ynoa_white_01' reconnected
Zigbee2MQTT:info  2022-08-11 14:38:01: MQTT publish: topic 'zigbee2mqtt/Ynoa_white_01/availability', payload 'online'
Zigbee2MQTT:debug 2022-08-11 14:38:01: Succesfully pinged 'Ynoa_white_01' (attempt 1/1)
----------------------------------------------------
----------------------------------------------------
Convertor file contains:
----------------------------------------------------
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['BT-CCTLight-GU100001'],
    model: 'ZBT-CCTLight-GU100001',
    vendor: 'LDS',
    description: 'Ynoa smart LED GU10 White',
    extend: extend.light_onoff_brightness_color()
};

module.exports = definition;
----------------------------------------------------
----------------------------------------------------

**Comment by timwar** [comment]
Was able to create external convertor file and created a new ticket for some support.
https://github.com/Koenkk/zigbee2mqtt/issues/13513
external convertor file is available in the new ticket.
