### ISSUE TITLE
[New device support]: GL-B-002P Gledopto ST64 7W Led ZigBee Filament Bulb

### ISSUE THREAD

**Issue by oat1** [Koenkk/zigbee2mqtt#12394]
### Link

https://www.gledopto.eu/led-e27-bulb-zigbee-st64-cct-color-temperature-eng

### Database entry

{"id":22,"type":"Router","ieeeAddr":"0xa4c138a1c7543073","nwkAddr":14865,"manufId":4687,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-B-002P","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"hwVersion":0}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":158,"colorTempPhysicalMax":495}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"dateCode":"20210712","swBuildId":"10051203","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1651778148101,"defaultSendRequestWhen":"immediate"}

### Comments

Please add the official support for GL-B-002P Gledopto ST64 7W Led ZigBee Filament Bulb.
I was able to make a working external converter, which should be attached 

It's a white spectrum, dimming filament bulb but it also exposes color:

payload '{"brightness":193,"color":{"h":40,"hue":40,"s":49,"saturation":49,"x":0.3804,"y":0.3767},"color_mode":"color_temp","color_temp":250,"color_temp_startup":65535,"last_seen":"2022-05-06T08:33:18+02:00","linkquality":255,"state":"ON"}'

I think it also supports OTA :

Debug 2022-05-06 08:38:48 Device 'Żarówka Taras' requested OTA

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['GL-B-002P'],
    model: 'GL-B-002P',
    vendor: 'Gledopto',
    description: 'ZigBee Smart Filament LED Bulb',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [158, 495]}),
};

module.exports = definition;
```

### Supported color modes

brightness, color teperature, color

### Color temperature range

{colorTempRange: [158, 495]}

**Comment by Koenkk** [comment]
added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
