### ISSUE TITLE
[Feature request]: Make use of new HA update entity

### ISSUE THREAD

**Issue by niklasweber** [Koenkk/zigbee2mqtt#12391]
### Is your feature request related to a problem? Please describe

In Home Assistant Release 2022.4 the new [update entity](https://www.home-assistant.io/blog/2022/04/06/release-20224/#introducing-update-entities) was introduced. Zigbee2mqtt already provides an update available entity in the form of a binary_sensor. However it is only a binary sensor and automations need to be added manually for more convenience. Maybe the new update entity could be added to allow convenient updates of zigbee devices from within Home Assistant?

### Describe the solution you'd like

I would be amazing if zigbee2mqtt could create an update entity where applicable which allows for an easy update with one tab from within home-assistant.

### Describe alternatives you've considered

The alternative would be to create an automation which triggers when the existing binary sensor changes. As far a I know I would have to open the zigbee2mqtt interface and start an update from there.

### Additional context

Update integration documentation: [https://www.home-assistant.io/integrations/update/]()
Home Assistant 2022.4 Release Party introduction of update entities (49:05): [https://youtu.be/wOrJUWYYWdY?t=2945]()

**Comment by McGiverGim** [comment]
It is being discussed here https://github.com/Koenkk/zigbee2mqtt/pull/11999

It seems the update sensor is not available to mqtt sensors at this moment.
