### ISSUE TITLE
IMMAX NEO SMART plug (07048L) doesn't show power consumption

### ISSUE THREAD

**Issue by mountainsandcode** [Koenkk/zigbee2mqtt#12400]
### What happened?

IMMAX NEO SMART plug (07048L) does support a continuous power consumption measurement, i.e., (k)Wh consumed in total. However, this value is not being shown in Z2M.

I've previously seen this working on ZHA and Deconz. According to #11943, this may have also been previously possible in Z2M (unfortunately, this ticket was closed as stale and I can't reopen it).

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

Latest

### Adapter

Conbee II

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition =     {
    zigbeeModel: ['Plug-230V-ZB3.0'],
    model: '07048L',
    vendor: 'Immax',
    description: 'NEO SMART plug CUSTOM',
    fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering],
    toZigbee: [tz.on_off],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
        await reporting.onOff(endpoint);
        await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
        await reporting.readMeteringMultiplierDivisor(endpoint);
        await reporting.currentSummDelivered(endpoint);
        await reporting.currentSummReceived(endpoint);
        await reporting.activePower(endpoint);
    },
    exposes: [e.switch(), e.power()],
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by mountainsandcode** [comment]
Hi @Koenkk,

Thanks for the very speedy reply, much appreciated!

```
error 2022-05-06 18:05:55: Failed to configure 'Tumble Dryer Plug', attempt 1 (Error: ConfigureReporting 0xcccccc<sanitized>/1 seMetering([{"attribute":"currentSummReceived","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":[1,1]}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22)
    at Object.currentSummReceived (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:123:9)
    at Object.configure (/app/dist/util/externally-loaded.js:23:9)
    at Configure.configure (/app/lib/extension/configure.ts:115:13)
    at Configure.start (/app/lib/extension/configure.ts:68:13)
    at Controller.callExtensions (/app/lib/controller.ts:316:17)
    at Controller.start (/app/lib/controller.ts:153:9)
    at start (/app/index.js:110:5))
```

Commenting out `await reporting.currentSummReceived(endpoint);` appears to rectify this issue.

In state, I can now see something called energy, which could be the cumulative consumption - what would be the next step to expose this as a sensor towards MQTT/HA?


```
{
    "energy": 5.36,
    "linkquality": 255,
    "power": 70,
    "state": "ON"
}
```

Once again, any help is much appreciated!

**Comment by Koenkk** [comment]
Great, try with:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition =     {
    zigbeeModel: ['Plug-230V-ZB3.0'],
    model: '07048L',
    vendor: 'Immax',
    description: 'NEO SMART plug CUSTOM',
    fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering],
    toZigbee: [tz.on_off],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
        await reporting.onOff(endpoint);
        await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
        await reporting.readMeteringMultiplierDivisor(endpoint);
        await reporting.currentSummDelivered(endpoint);
        await reporting.activePower(endpoint);
    },
    exposes: [e.switch(), e.power(), e.energy()],
};

module.exports = definition;
```

**Comment by mountainsandcode** [comment]
Works, thanks so much for your help and have a great weekend, @Koenkk!

**Comment by Koenkk** [comment]
Great, integrated this.

Will be included in the next release on 1 June

**Comment by sebul0n** [comment]
Hi,

Im having same issue:
![image](https://user-images.githubusercontent.com/29020051/191761301-e6367724-5faa-4a99-a393-78c8fd248e15.png)

**Zigbee2MQTT version**
1.27.2-1

**Device info:
Firmware build date:**
20190709-164

**Firmware version:**
2.0

**Zigbee Model**
Plug-230V-ZB3.0

I already added a "ext_converter.js" like instructed, and added it to zigbee2mqtt's configuration.yaml. After that I restarted the zigbee2mqtt.

I have also removed the device and paired and also configured it again. None helps.

I see in the logs that energy and power are null:
MQTT publish: topic 'zigbee2mqtt/0xccccccfffee988ec', payload '{"energy":null,"linkquality":138,"power":null,"state":"ON"}'

I see that device Description changed to:
NEO SMART plug CUSTOM

So it seems to have taken the "ext_converter.js" into use.

Please help, any ideas from @Koenkk would be very much appreciated? The firmware for the device is quite old, but I dont know how to update that, because it is not in the zigbee2mqtt's OTA list.

**Comment by teufelschultz** [comment]
I have the same issue.
I've had this problem before. At that time I paired the SMART plug with my Alexa and then again with the zigbee2mqtt. Then it worked again. But surely that can't be necessary all the time?

**Comment by sebul0n** [comment]
Hi @teufelschultz and @Koenkk,

I got this issue solved. The "activePower" attribute's "Min rep change" was too high (around 100) so the power was never updated. I changed it to "1" and now every time wattages changes more than 1W, it will update the attribute as well! So all is working now!=)

![image](https://user-images.githubusercontent.com/29020051/197622038-489bf5d2-7fca-4552-8362-0298939e7a98.png)

![image](https://user-images.githubusercontent.com/29020051/197622401-79474fd0-255f-45b5-8091-f66ca753c6bf.png)

Maybe similar happened when you paired the device with your Alexa.

**Comment by Koenkk** [comment]
@sebul0n what about setting `5` instead of `1`? `1` will make the device very spammy.

**Comment by sebul0n** [comment]
@Koenkk good point! I was looking the logs and they were indeed very spammy!:) Thanks for the advise.

**Comment by teufelschultz** [comment]
@sebul0n @Koenkk 
Thanks for this solution.
I save the solution. Currently (after connecting to Alexa) my plug are all working again.
When I go to the named setting, it currently also shows me 1 at "Min rep Change". Was possibly set by Alexa.

**Comment by Koenkk** [comment]
Great, pushed the fix (setting default rep change to 5)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
