### ISSUE TITLE
[New device support]: Philips Hue Runner double spotlight

### ISSUE THREAD

**Issue by philyholiday** [Koenkk/zigbee2mqtt#12410]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-ambiance-runner-double-spotlight/8719514338142

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0x001788010b5497b4","nwkAddr":43258,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003045601_02","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1651869456678,"defaultSendRequestWhen":"immediate"}

### Comments

Could you please add 929003045601_01 + 929003045601_02 to the Philips Runner Double Spotlight?

I guess they added a new batch with new number.
Thank you so much.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
