### ISSUE TITLE
New devices interview failed after update

### ISSUE THREAD

**Issue by sfedostsev** [Koenkk/zigbee2mqtt#12411]
### What happened?

After the update, interview failed for new and old devices. Tested with seveal instances IKEA 1743, even with the instance, which was successfully used and paired before. Another devices, failed to pair: IKEA LED1836G9. Tested with 2 different sticks, both based on CC2531.

### What did you expect to happen?

New devices can be successfully paired. 

### Zigbee2MQTT version

1.25.0 commit: 6f1460e4

### Adapter firmware version

CC2531_DEFAULT_20211115

### Adapter

CC2531

### Debug log

[pairing.log](https://github.com/Koenkk/zigbee2mqtt/files/8645017/pairing.log)

**Comment by GarionBracken** [comment]
I have the same issue, pair but don't interview and show as 'unsupported'. I had the issue with 1.24 too and hoped the update would sort it out.
![image](https://user-images.githubusercontent.com/16231898/167293731-c5937324-be31-475a-a73d-068029cbb78c.png)
