### ISSUE TITLE
Using the board CC2530/CC2591 with usb adapter

### ISSUE THREAD

**Issue by erazor666** [Koenkk/zigbee2mqtt#1242]
After reading the WIKI and doing a few builds some questions have come up.

There are 2 pins labeled _VCC_, there is an additional _GND_ pin on the **CC2530/CC2591** board. Is the extra _VCC_ and _GND_ supposed to be ignored when using usb adapter?
I'm referring to the image material in the [router guide](https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html)

I'm gonna use the **CC2530/CC2591** as coordinator with a Raspberry PI. Could I connect the pins
_3.3v (vcc) 
Gnd (gnd) 
P02 (tx)
P03 (rx)_
be interfaced directly to the raspberry **GPIO** by any chance? if so, whats needed for this to work? (os configuration, zigbee2mqtt)

**Comment by kquinsland** [comment]
all the `VCC` pins are tied together. same with all the `GND`.  You can use any pin labeled `VCC` /  `GND`.

i don't know what the logic levels are on the rPI or how to use the software serial port on it, but i would imagine that it's possible.
