### ISSUE TITLE
Xiaomi Wall Switch control from two concentrators

### ISSUE THREAD

**Issue by miroslavpetrov** [Koenkk/zigbee2mqtt#1243]
I have a running zigbee network with cc2531 concentrator and around 10 devices. I have installed zigbee2mqtt on another raspberry pi in order to test the new GBAN cc2530 concentrator that I bought. Both concentrators are in my house and the strange thing is that the GBAN paired with my xiaomi wall switch which is already paired to my main network. The interesting thing is that it is now possible to control the switch from both networks but it takes 2-3 seconds before it reacts.

Can someone explain how is this possible? And if its not some sort of bug but a zigbee feature it can be useful for some scenarios.

**Comment by Koenkk** [comment]
A zigbee device is not paired to a concentrator but to a zigbee network.

I assume that you are using the same network key, pan id, and channel (this is the case when you haven't put anything specific in `configuration.yaml`), which allows the second zigbee2mqtt setup to communicate with the same zigbee network.
