### ISSUE TITLE
Can't upgrade to 1.25.1 from 1.22.0 docker container

### ISSUE THREAD

**Issue by fraddygil** [Koenkk/zigbee2mqtt#12440]
### What happened?

can't upgrade to 1.25.1 from 1.22.0 docker container

![image](https://user-images.githubusercontent.com/21328059/167757498-b8bb8b00-357d-4939-8595-7ae4383783cd.png)
![image](https://user-images.githubusercontent.com/21328059/167757572-6a05a601-966c-4594-9b53-f8d6cfba01b2.png)

### What did you expect to happen?

When I upgrade the image I get the following message.

**LOG**

Using '/app/data' as data directory
Fatal error in , line 0
unreachable code
FailureMessage Object: 0xbecd662c

**LOG END**

### How to reproduce it (minimal and precise)

I have a docker 1.22.0 image and I want to update to 1.25.1 or latest and it returns this error.

**Error does not happen if I have version 1.22.0**

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by Shred99** [comment]
Sounds a lot like this: #7662

**Comment by Shred99** [comment]
[https://www.zigbee2mqtt.io/guide/installation/02_docker.html#notes-for-raspberry-pi-users](url)

**Comment by fraddygil** [comment]
Thanks for your help @Shred99 , I managed to solve with the last link you sent me.
