### ISSUE TITLE
Configured loop - #159 basic implementation / rework

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#1244]
Hi @Koenkk 
I´m on the way to implement #159 but found a strange issue.

As you could see at this pastebin export the configured part seems to be fine but loop directly.
https://pastebin.com/dRts17T9

Actually i´m on ``zigbee2mqtt version 1.1.1 (commit #a20ec7c)``

Maybe you´v got a idea what this could happen and how we could fix them ?

**Comment by Koenkk** [comment]
This should be fixed in zigbee2mqtt 1.2.1

**Comment by tb-killa** [comment]
Thanks
