### ISSUE TITLE
some problems went wrong with TUYA TS0002

### ISSUE THREAD

**Issue by huahuazi** [Koenkk/zigbee2mqtt#12481]
### What happened?

when I click L1 on， then L2 will on, too.
when I click L1 off， then L2 will off, too.

I cannot control one of them in ha
However, when I press the switch on the wall physically, the switch works normally, and L1 and L2 will not be turned on or off at the same time. However, when I use ha to switch L1 and L2, they will be turned on and off at the same time. The two switches like be linked.

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20210708

### Adapter

sonoff

### Debug log

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.5.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.9.9",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Shanghai",
    "os_name": "Linux",
    "os_version": "5.10.108",
    "supervisor": "2022.05.1",
    "host_os": "Home Assistant OS 7.6",
    "docker_version": "20.10.9",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "xiaomi_gateway3": {
      "version": "2.0.9",
      "requirements": [
        "zigpy>=0.33.0"
      ]
    },
    "auto_backup": {
      "version": "0.10.1",
      "requirements": []
    },
    "esxi_stats": {
      "version": "0.6.4",
      "requirements": [
        "pyvmomi==7.0.3"
      ]
    },
    "colorfulclouds": {
      "version": "1.2.5",
      "requirements": []
    },
    "nodered": {
      "version": "1.0.8",
      "requirements": []
    },
    "xiaomi_miot": {
      "version": "0.5.7",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "hacs": {
      "version": "1.24.5",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "peacefair_energy": {
      "version": "v0.7.2",
      "requirements": []
    },
    "sonoff": {
      "version": "v2.4.6",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "smartac": {
      "version": "1.2.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "mqtt",
    "name": "MQTT",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/mqtt",
    "requirements": [
      "paho-mqtt==1.6.1"
    ],
    "dependencies": [
      "http"
    ],
    "codeowners": [
      "@emontnemery"
    ],
    "iot_class": "local_push",
    "is_built_in": true
  },
  "data": {
    "connected": true,
    "mqtt_config": {
      "birth_message": {
        "topic": "homeassistant/status",
        "payload": "online",
        "qos": 0,
        "retain": false
      },
      "discovery": true,
      "port": 1883,
      "tls_version": "auto",
      "will_message": {
        "topic": "homeassistant/status",
        "payload": "offline",
        "qos": 0,
        "retain": false
      },
      "broker": "core-mosquitto",
      "username": "**REDACTED**",
      "password": "**REDACTED**",
      "protocol": "3.1.1",
      "keepalive": 60,
      "discovery_prefix": "homeassistant"
    },
    "device": {
      "id": "459bd39484e72b7b18bd81e8c59d1988",
      "name": "0xa4c138a75a17fa91",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "switch.0xa4c138a75a17fa91_l1",
          "icon": null,
          "original_device_class": null,
          "original_icon": null,
          "state": {
            "entity_id": "switch.0xa4c138a75a17fa91_l1",
            "state": "off",
            "attributes": {
              "linkquality": 87,
              "state_l1": "OFF",
              "state_l2": "OFF",
              "friendly_name": "0xa4c138a75a17fa91 l1"
            },
            "last_changed": "2022-05-15T06:30:03.387957+00:00",
            "last_updated": "2022-05-15T06:30:03.578220+00:00"
          },
          "unit_of_measurement": null
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "switch.0xa4c138a75a17fa91_l2",
          "icon": null,
          "original_device_class": null,
          "original_icon": null,
          "state": {
            "entity_id": "switch.0xa4c138a75a17fa91_l2",
            "state": "off",
            "attributes": {
              "linkquality": 87,
              "state_l1": "OFF",
              "state_l2": "OFF",
              "friendly_name": "0xa4c138a75a17fa91 l2"
            },
            "last_changed": "2022-05-15T06:30:03.580984+00:00",
            "last_updated": "2022-05-15T06:30:03.580984+00:00"
          },
          "unit_of_measurement": null
        },
        {
          "device_class": null,
          "disabled_by": "integration",
          "disabled": true,
          "entity_category": "diagnostic",
          "entity_id": "sensor.0xa4c138a75a17fa91_linkquality",
          "icon": null,
          "original_device_class": null,
          "original_icon": "mdi:signal",
          "state": null,
          "unit_of_measurement": "lqi"
        }
      ]
    },
    "mqtt_debug_info": {
      "entities": [
        {
          "entity_id": "switch.0xa4c138a75a17fa91_l1",
          "subscriptions": [
            {
              "topic": "zigbee2mqtt/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2022-05-15T06:09:51.005792+00:00",
                  "topic": "zigbee2mqtt/bridge/state"
                },
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2022-05-15T06:09:51.057409+00:00",
                  "topic": "zigbee2mqtt/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "messages": [
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"ON\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:21.664185+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.070329+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.088780+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":102,\"state_l1\":\"OFF\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.262393+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":117,\"state_l1\":\"ON\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.493575+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"ON\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.499249+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"ON\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.677406+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.386283+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.388789+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":87,\"state_l1\":\"OFF\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.577748+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                }
              ]
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/switch/0xa4c138a75a17fa91/switch_l1/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee2mqtt/bridge/state"
                }
              ],
              "command_topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set",
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0xa4c138a75a17fa91"
                ],
                "manufacturer": "TuYa",
                "model": "2 gang switch (TS0002)",
                "name": "0xa4c138a75a17fa91"
              },
              "json_attributes_topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "name": "0xa4c138a75a17fa91 l1",
              "payload_off": "OFF",
              "payload_on": "ON",
              "state_topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "unique_id": "0xa4c138a75a17fa91_switch_l1_zigbee2mqtt",
              "value_template": "{{ value_json.state_l1 }}",
              "platform": "mqtt"
            }
          },
          "transmitted": [
            {
              "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set",
              "messages": [
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:53.708218+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:55.077469+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:56.325140+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:57.476705+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:58.561357+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:00.239980+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:02.021913+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:03.646626+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:30:00.468080+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:30:03.316862+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l1/set"
                }
              ]
            }
          ]
        },
        {
          "entity_id": "switch.0xa4c138a75a17fa91_l2",
          "subscriptions": [
            {
              "topic": "zigbee2mqtt/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2022-05-15T06:09:51.005792+00:00",
                  "topic": "zigbee2mqtt/bridge/state"
                },
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2022-05-15T06:09:51.057409+00:00",
                  "topic": "zigbee2mqtt/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "messages": [
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"ON\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:21.664185+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.070329+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.088780+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":102,\"state_l1\":\"OFF\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:23:22.262393+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":117,\"state_l1\":\"ON\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.493575+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":114,\"state_l1\":\"ON\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.499249+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"ON\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:01.677406+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.386283+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":111,\"state_l1\":\"OFF\",\"state_l2\":\"ON\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.388789+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                },
                {
                  "payload": "{\"linkquality\":87,\"state_l1\":\"OFF\",\"state_l2\":\"OFF\"}",
                  "qos": 0,
                  "retain": 0,
                  "time": "2022-05-15T06:30:03.577748+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91"
                }
              ]
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/switch/0xa4c138a75a17fa91/switch_l2/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee2mqtt/bridge/state"
                }
              ],
              "command_topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set",
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0xa4c138a75a17fa91"
                ],
                "manufacturer": "TuYa",
                "model": "2 gang switch (TS0002)",
                "name": "0xa4c138a75a17fa91"
              },
              "json_attributes_topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "name": "0xa4c138a75a17fa91 l2",
              "payload_off": "OFF",
              "payload_on": "ON",
              "state_topic": "zigbee2mqtt/0xa4c138a75a17fa91",
              "unique_id": "0xa4c138a75a17fa91_switch_l2_zigbee2mqtt",
              "value_template": "{{ value_json.state_l2 }}",
              "platform": "mqtt"
            }
          },
          "transmitted": [
            {
              "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set",
              "messages": [
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:52.909935+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:54.358870+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:55.754265+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:56.933336+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:58.002916+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:19:59.113195+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:00.828764+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:05.164674+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "ON",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:06.041813+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                },
                {
                  "payload": "OFF",
                  "qos": 0,
                  "retain": false,
                  "time": "2022-05-15T06:20:07.011644+00:00",
                  "topic": "zigbee2mqtt/0xa4c138a75a17fa91/l2/set"
                }
              ]
            }
          ]
        }
      ],
      "triggers": []
    }
  }
}

**Comment by huahuazi** [comment]
> Should be fixed now.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

When will this version be updated to the official version? not the dev version

**Comment by Impact123** [comment]
[Judging from the release history so far](https://github.com/Koenkk/zigbee2mqtt/tags) I'd say `June 1`

**Comment by BogdanValea** [comment]
hello all, any news on when this issue is gonna be solved in the master branch ? thanks all for the great effort.

**Comment by dmitry-pervushin** [comment]
Apparently not in 1.28.0-1 ? :)
