### ISSUE TITLE
Error in Herdsman

### ISSUE THREAD

**Issue by Gotcha182** [Koenkk/zigbee2mqtt#12495]
### What happened?

zigbee2mqtt did not start with a clean install and flash on the Raspberry pi. I had just flashed the Sonoff Zigbee 3.0 to most recent FW and getting this installed for the first time as well has gathered the failure/error below:

Zigbee2MQTT:error 2022-05-15 21:38:35: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-05-15 21:38:35: Failed to start zigbee
Zigbee2MQTT:error 2022-05-15 21:38:35: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-05-15 21:38:35: Exiting...
Zigbee2MQTT:error 2022-05-15 21:38:35: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code 1
npm ERR! path /opt/zigbee2mqtt
npm ERR! command failed
npm ERR! command sh -c node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-05-16T04_38_35_732Z-debug.log

### What did you expect to happen?

properly starting

### Zigbee2MQTT version

1.25.1 - dev

### Adapter firmware version

20220219

### Adapter

CC2562P

**Comment by Koenkk** [comment]
`Error: Error Resource temporarily unavailable Cannot lock port` this means another program on your Pi is already locking the port: https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-resource-temporarily-unavailable-cannot-lock-port
