### ISSUE TITLE
Cant add new devices

### ISSUE THREAD

**Issue by Kotitonttu1** [Koenkk/zigbee2mqtt#12505]
### What happened?

At some point lost connection to Lidl filament bulb. Couldnt reconnect it. Bought few Ikea buttons and motion sensors, couldnt connect any of them. Bought two Xiaomi temperature sensors, connected well but after a week lost connection to them.

Frustrated and upgraded the coordinator fw. Doesnt work any better. 12 working devices, cant add more. Probably those 12 will disappear one by one at some point.

### What did you expect to happen?

Expected home automation make life nicer 

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

CC2652R_coordinator_20220219

### Adapter

Electrolama 2652R

### Debug log

Doesnt give anything to log when trying to add new device. Some times rarely "interview failed"

**Comment by cddu33** [comment]
Check configuration.yaml and remove groups
