### ISSUE TITLE
[New device support]: Tuya Smart ZigBee IR Remote Control 

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#12517]
### Link

https://www.aliexpress.com/item/1005003887817601.html

### Database entry

{"id":29,"type":"Router","ieeeAddr":"0x2c1165fffe661f1f","nwkAddr":43162,"manufId":4098,"manufName":"_TZ3290_acv1iuslxi3shaaj","powerSource":"Mains (single phase)","modelId":"TS1201","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":61440,"inClusterList":[0,4,5,3,60672,57348,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS1201","manufacturerName":"_TZ3290_acv1iuslxi3shaaj","stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1652796441330,"defaultSendRequestWhen":"immediate"}

### Comments

![image](https://user-images.githubusercontent.com/47602733/168838812-ff75e5c3-4b61-4241-9479-5aab805bf8bf.png)

The device is not supported when I try to pair is the msg, Can you please help me in order to get this device working?

Thank you for your support

**Comment by iba0q** [comment]
Are those affiliate links you're posting in your issues? If they are, would be nice if you contributed your earnings to this project?

**Comment by Impact123** [comment]
No, but I don't like those links either. Here's where it links: <https://www.aliexpress.com/item/1005003887817601.html>

**Comment by MiAutomations** [comment]
> Are those affiliate links you're posting in your issues? If they are, would be nice if you contributed your earnings to this project?

Sorry I just short the link ... Now is correct no more shorted links post thank you

**Comment by MiAutomations** [comment]
> I don't like those links either. Here's where it links: https://www.aliexpress.com/item/1005003887817601.html

I just edit and post the original link, thank you

**Comment by nmaster2042** [comment]
I think there is already an issue see here Issue #11633
