### ISSUE TITLE
VOCKQJK11LM does not show battery voltage report

### ISSUE THREAD

**Issue by inode64** [Koenkk/zigbee2mqtt#12532]
### What happened?

VOCKQJK11LM does not show battery voltage report

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

[VOCKQJK11LM.log](https://github.com/Koenkk/zigbee2mqtt/files/8721231/VOCKQJK11LM.log)

**Comment by Otnow** [comment]
If I understand the problem correctly, then you need to add `e.battery_voltage()` to `exposes` in the [converter](https://github.com/Koenkk/zigbee-herdsman-converters/blob/88fa4b76373b3a208c688b5c795e3766d06028c6/devices/xiaomi.js#L1781).

Of greater interest is the ability to parse the structure of the _heartbeat-message_ from the sensor:

```javascript
Zigbee2MQTT:debug 2022-05-19 00:15:05: Received Zigbee message from '0x54ef441000106f3b', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,95,11,3,40,29,4,33,168,1,5,33,16,0,6,36,5,0,0,0,0,8,33,29,1,10,33,0,0,12,32,1,100,41,161,11,101,33,185,24,102,33,40,0,103,32,1],"type":"Buffer"}}' from endpoint 1 with groupID null
```

If you have such an opportunity, then please add `fz.aqara_opple` to `fromZigbee` in the [converter](https://github.com/Koenkk/zigbee-herdsman-converters/blob/88fa4b76373b3a208c688b5c795e3766d06028c6/devices/xiaomi.js#L1778) and write a log with the following actions:

- sensor pairing (_wait for the end_)
- press button on sensor once and wait 10 sec. (_until receipt heartbeat-message_)
