### ISSUE TITLE
[New device support]: SLC SmartOne AC Wall dimmer 250W Zigbee

### ISSUE THREAD

**Issue by aravndal** [Koenkk/zigbee2mqtt#12538]
### Link

https://www.tlg.no/slc-smartone-ac-wall-dimmer-300w-zigbee

### Database entry

{"id":33,"type":"Router","ieeeAddr":"0x9035eafffeb81376","nwkAddr":16675,"manufId":4644,"manufName":"The Light Group AS","powerSource":"Mains (single phase) ","modelId":"S24019","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2820,2821,4096],"outClusterList" :[25],"clusters":{"genBasic":{"attributes":{"modelId":"S24019","manufacturerName":"The Light Group AS","powerSource":1,"zclVersion":3,"appVersion":0,"stackV ersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r54"}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":127," onOffTransitionTime":1,"startUpCurrentLevel":255}},"seMetering":{"attributes":{"currentSummDelivered":[0,2991635]}},"haElectricalMeasurement":{"attributes": {"rmsVoltage":1771,"rmsCurrent":117,"activePower":186}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00212effff069298","endpointID":1},{" cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00212effff069298","endpointID":1},{"cluster":2821,"type":"endpoint","deviceIeeeAddress":"0x00212effff069 298","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff069298","endpointID":1},{"cluster":5,"type":"endpoint","deviceIeeeAddre ss":"0x00212effff069298","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff069298","endpointID":1},{"cluster":2820,"type":"end point","deviceIeeeAddress":"0x00212effff069298","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff069298","endpointID":1}], "configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval": 3600,"repChange":1}],"meta":{"scenes":{"10_6":{"name":"Stue Morgen","state":{"state":"OFF","brightness":127,"color_mode":"color_temp","color_temp":415}}}}}, "242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appV ersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r54","zclVersion":3,"interviewCompleted":true,"meta":{"configured":382471163}, "lastSeen":1652993281822,"defaultSendRequestWhen":"immediate"}

### Comments

Support for new device attached.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes;
const ep = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['S24019'],
    model: 'S24019',
    vendor: 'The Light Group',
    description: 'SLC SmartOne Led Dimmer',
    fromZigbee: [fz.on_off, fz.brightness, fz.metering, fz.electrical_measurement],
    toZigbee: [tz.light_onoff_brightness, tz.level_config],
    exposes: [ep.light_brightness().withLevelConfig()],
    configure: async (device, coordinatorEndpoint, logger) => {
        // Endporint 1
        const endpoint1 = device.getEndpoint(1);
        const binds1 = ['genOnOff','genLevelCtrl','haElectricalMeasurement','seMetering'];
        await reporting.bind(endpoint1, coordinatorEndpoint, binds1);
        await reporting.onOff(endpoint1);
        await reporting.brightness(endpoint1);
        await endpoint1.read('haElectricalMeasurement', ['acCurrentMultiplier','acCurrentDivisor']);
        await endpoint1.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);
        await endpoint1.read('haElectricalMeasurement', ['acVoltageMultiplier', 'acVoltageDivisor']);
        await reporting.activePower(endpoint1, {min: 5, max: 3600, change: 1000});
        await reporting.rmsCurrent(endpoint1, {min: 5, max: 3600, change: 100});
        await reporting.rmsVoltage(endpoint1, {min: 5, max: 3600, change: 100});
        // read switch state
        await endpoint1.read('genOnOff', ['onOff']);
    },
};

module.exports = definition;
~

```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
