### ISSUE TITLE
OTA index override only work for `ota.zigbeeOTA`

### ISSUE THREAD

**Issue by Danit2** [Koenkk/zigbee2mqtt#12554]
### What happened?

The function `OTA index override` only work for converters with `ota.zigbeeOTA` and not for the manufacturerspecific OTA Script.

### What did you expect to happen?

It would be great if the function could also be used for the converter with manufacturerspecific OTA Script.

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20211217

### Adapter

Sonoff USB

**Comment by Danit2** [comment]
This is not stale. 
This is still a problem.

**Comment by pfak** [comment]
This is still an issue.
