### ISSUE TITLE
Unable to Join Zigbee devices...

### ISSUE THREAD

**Issue by deltabert** [Koenkk/zigbee2mqtt#12557]
### What happened?

Hello all,
I am using a fresh install of Home Assistant (On RPi4/Debian 11) with just only Mosquitto and Zigbee2MQTT installed.
As coordinator,i have the Sonoff Zigbee 3.0 USB Dongle Plus, which i flashed successfully with fw: CC1352P2_CC2652P_launchpad_coordinator_20220219

The configuration in zigbee2mqtt is as following:

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  server: mqtt://192.168.178.222:1883
  base_topic: zigbee2mqtt
  user: z2m
  password: <mqtt-pw>
serial:
  port: /dev/ttyUSB0

Which is looking OK according to the zigbee2mqtt log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[15:47:52] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:47:54] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1 start
> node index.js
Zigbee2MQTT:info  2022-05-21 15:48:00: Logging to console and directory: '/config/zigbee2mqtt/log/2022-05-21.15-47-58' filename: log.txt
Zigbee2MQTT:info  2022-05-21 15:48:00: Starting Zigbee2MQTT version 1.25.1 (commit #unknown)
Zigbee2MQTT:info  2022-05-21 15:48:00: Starting zigbee-herdsman (0.14.27)
Zigbee2MQTT:info  2022-05-21 15:48:01: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-05-21 15:48:01: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2022-05-21 15:48:01: Currently 0 devices are joined:
Zigbee2MQTT:info  2022-05-21 15:48:01: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-05-21 15:48:01: Connecting to MQTT server at mqtt://192.168.178.222:1883
Zigbee2MQTT:info  2022-05-21 15:48:01: Connected to MQTT server
Zigbee2MQTT:info  2022-05-21 15:48:01: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-05-21 15:48:01: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2022-05-21 15:48:01: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20220219,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b0024bc4722","panID":6754},"permit_join":false,"version":"1.25.1"}'
Zigbee2MQTT:info  2022-05-21 15:48:01: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-05-21 15:48:26: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-05-21 15:48:26: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"721zq-1"}'
Zigbee2MQTT:info  2022-05-21 15:51:47: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-05-21 15:51:47: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"yz4ul-1"}'
Zigbee2MQTT:info  2022-05-21 15:53:06: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-05-21 15:53:07: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"v71at-1"}'

As you can see in the log i activate and stop the 'Permit Join' button in the GUI.

But i am unable to get my devices to Join. I tried it with 3 different Aqara Door Sensors and a Sonoff SNZB-01 switch.
These devices have been working on an other system which uses a deCONZ Combee 2 stick.

I hope anyone can help me find a solution...
Kind regards, Bert

### What did you expect to happen?

I was expecting the devices to Join.

### How to reproduce it (minimal and precise)

See my description in What Happened? Here i sumorize the configuration

### Zigbee2MQTT version

1.25.1-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by atimchula** [comment]
What channel are you using? I had the same problem where I defined my channel as 25 but my devices didn't support it. I set the channel to 20 and it worked.

add 

```
advanced: 
  channel: 20
```

to your config
