### ISSUE TITLE
 RWL022 has simulated_brightness but RWL021 doesn't?

### ISSUE THREAD

**Issue by Bascht74** [Koenkk/zigbee2mqtt#12562]
### What happened?

I set the `simulated_brightness` settings to a lot of my hue and Ikea devices and I can set this setting to every device I got except the RWL021 dimmer switch. 

Is there a reason for that or was it simply forgotten?

### What did you expect to happen?

I want to set the `simulated_brightness` settings on the RWL021 dimmer switches as well (RWL022 and any other switch I got works).

### How to reproduce it (minimal and precise)

Open the RWL021 settings --> no `simulated_brightness` settings
Open the RWL022 (or any other ikea switch) settings --> `simulated_brightness` settings available

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

zStack3x0 Coordinator Version 20220219

### Adapter

Zonoff Zigbee 3.0 Plus

### Debug log

no log

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
