### ISSUE TITLE
Unsupported RTX ZVG1

### ISSUE THREAD

**Issue by nagyidai88** [Koenkk/zigbee2mqtt#12573]
### What happened?

I bought a RTX ZVG1 smart valve which is Z2M supported based on the official site but when I connected to HA through my Ziogbee dongle, it says unsupported. [https://www.zigbee2mqtt.io/devices/ZVG1.html](url)

Friendly name
Kerti_csap
Description
Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
EndDevice
Zigbee Model
TS0601
Zigbee Manufacturer
_TZE200_81isopgh
Support status
Not supported

IEEE Address
0x040d84fffe96b9dc
Network address
0x9C1A
Power
Battery 
Interview completed
True

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20210319

### Adapter

zStack3x0

### Debug log

Debug 2022-05-23 08:58:21Received Zigbee message from 'Kerti_csap', type 'commandMcuSyncTime', cluster 'manuSpecificTuya', data '{"payloadSize":0}' from endpoint 1 with groupID 0
Warning 2022-05-23 08:58:21Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_81isopgh'
Warning 2022-05-23 08:58:21Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
`_TZE200_81isopgh` is already supported in the latest dev branch and next release on 1 June. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
