### ISSUE TITLE
[New device support]: Philips 1745130P7  (Hue Calla outdoor with power supply)

### ISSUE THREAD

**Issue by Seb0815** [Koenkk/zigbee2mqtt#12579]
### Link

https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-calla-grose-sockelleuchte/1745130P7

### Database entry

{"id":29,"type":"Router","ieeeAddr":"0x0017880109ef09a8","nwkAddr":28972,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"1745130P7","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"1745130P7","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1653337960042,"defaultSendRequestWhen":"immediate"}

### Comments

seems to be identical to Philips [1743730P7](https://www.zigbee2mqtt.io/devices/1743730P7.html#philips-1743730p7) 
I purchased one with power supply (1745130P7) and one without (1743730P7), only one gets identified 

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['1745130P7'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '1745130P7', // Vendor model number, look on the device for a model number
    vendor: 'Philips', // Vendor of the device (only used for documentation and startup logging)
    description: 'Hue Calla outdoor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
