### ISSUE TITLE
Problem with adding Woox R7051 smart siren

### ISSUE THREAD

**Issue by grain111** [Koenkk/zigbee2mqtt#12584]
### What happened?

I was trying to pair Woox R7051 which according to supported devices page should work, but got an error message that it's not supported. 
Device '0x2c1165fffed7310e' with Zigbee model 'TS0219' and manufacturer name '_TYZB01_bwsijaty' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle-P ZigBee Dongle Plus CC2652P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8764740/log.txt)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
