### ISSUE TITLE
[New device support]: Letsleds Mondo (Led strip controller HLC929-Z-RGBW-4C-IA-OTA-3.0)

### ISSUE THREAD

**Issue by Dragonfly-terra** [Koenkk/zigbee2mqtt#12586]
### Link

https://letsleds.nl/product/set-3x-mondo-ondiepe-inbouwspot-white-color-rond-nikkel-8watt-ip65-zigbee-3/

### Database entry

{"id":28,"type":"Router","ieeeAddr":"0x94deb8fffe2919e9","nwkAddr":57385,"manufId":34457,"manufName":"Letsleds China","powerSource":"Unknown","modelId":"RGBW Down Light","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[64513,0,3,4,5,6,8,768,4096,65518],"outClusterList":[25,4096,65518],"clusters":{"genBasic":{"attributes":{"modelId":"RGBW Down Light","manufacturerName":"Letsleds China","powerSource":0,"zclVersion":8,"appVersion":1,"stackVersion":3,"hwVersion":2,"dateCode":"20210302","swBuildId":"3.1.0"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":3,"hwVersion":2,"dateCode":"20210302","swBuildId":"3.1.0","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1653420242846,"defaultSendRequestWhen":"immediate"}

### Comments

I have created a External converter and checkt the cluster. But to be fair I have no idea what I am doing.
If somebody could help me understanding (or add the device) that would be great
![Letsleds Mondo - Cluster](https://user-images.githubusercontent.com/64733289/170120831-8d567d6c-add9-4341-b526-891bef2f027d.png)
.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['RGBW Down Light'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'MONDO', // Vendor model number, look on the device for a model number
    vendor: 'Letsleds China', // Vendor of the device (only used for documentation and startup logging)
    description: 'Letsleds RGBW Down Light', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.switch(), extend.light_onoff_brightness(), extend.light_onoff_brightness_colortemp(), extend.light_onoff_brightness_color(), extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

### Supported color modes

RGBW

### Color temperature range

"colorTempPhysicalMin":153,"colorTempPhysicalMax":370

**Comment by Koenkk** [comment]
Try changing `    extend: extend.switch(), extend.light_onoff_brightness(), extend.light_onoff_brightness_colortemp(), extend.light_onoff_brightness_color(), extend.light_onoff_brightness_colortemp_color(),` to

```js
    extend: extend.light_onoff_brightness_colortemp_color(),
```

and see if it is controllable from the frontend.

**Comment by Dragonfly-terra** [comment]
That was the trick.
The External converter converter is now:
`
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['RGBW Down Light'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'MONDO', // Vendor model number, look on the device for a model number
    vendor: 'Letsleds China', // Vendor of the device (only used for documentation and startup logging)
    description: 'Letsleds RGBW Down Light', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 370]}),
};

module.exports = definition;
`
Everything seems to work in the frontend. Funny behaviour is the Cool shows warm light and the Warm shows cool light.
Any idea how I could fix this? Also in home assistant in the devices I can only see light switch on off. No brightness, color or colortemp settings.

**Comment by Dragonfly-terra** [comment]
I reconfigured the device and now it is showing.
Only the behaviour of the color temperature is the opposite of what is showen (Cool = Warm & Warm = Cool)

**Comment by Koenkk** [comment]
@Dragonfly-terra strange, does the color temperature control work correctly? Lower color temp = cooler, higher color temp = warmer

**Comment by Dragonfly-terra** [comment]
@Koenkk  No the exact opposite happens. Lower = warmer and Higher = cooler

**Comment by Koenkk** [comment]
That explains why this happens:

> Only the behaviour of the color temperature is the opposite of what is showen (Cool = Warm & Warm = Cool)

This is a bug in the device itself, seems they made a mistake when implementing the Zigbee spec.

**Comment by Koenkk** [comment]
Good, added the device with a note about the color temp in the description (will be supported out-of-the-box in the next release)
