### ISSUE TITLE
[New device support]: Philips Hue Go portable light (7602031N6)

### ISSUE THREAD

**Issue by KurtBoswood** [Koenkk/zigbee2mqtt#12591]
### Link

https://www.philips-hue.com/content/B2C/en_AU/CONSUMER/7602031N6.html

### Database entry

{"id":41,"type":"Router","ieeeAddr":"0x001788010b408127","nwkAddr":23483,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"7602031N6","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"7602031N6","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1653464538215,"defaultSendRequestWhen":"immediate"}

### Comments

Firstly, thank you to Koenkk, and everyone that contributes to this amazing project!

It looks like there's a new Philips Hue "Go" product  ("7602031N6"), and i'm hoping you may be able to support.

I think I've filled out this correctly, but sing out if i missed something.  :)

thanks in advance, 
Kurt.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['7602031N6'],
    model: '7602031N6',
    vendor: 'Philips',
    description: 'Go portable light',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
