### ISSUE TITLE
Zigbee2MQTT control panel doesn't show in the iPhone app for Home Assistant

### ISSUE THREAD

**Issue by jrhansen** [Koenkk/zigbee2mqtt#12607]
### What happened?

When using the app for Home Assistant on my iPhone, the control panel for Zigbee2MQTT is inaccessible. When selecting either from the "Burger" menu or from the integrations page, the display turns blank. Only the top line with the "burger" menu with the word "Zigbee2mqtt" next to it is visible. The same thing happens for the three HA installations that I have access to via the app.

I can view the control panel using Safari on the same phone, and also on a computer. Zigbee2MQTT is the only integration doing that.

Any idea what could have happened?

### Zigbee2MQTT version

1.25.1-1

### Adapter firmware version

20211217

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by michalk-k** [comment]
dup: https://github.com/Koenkk/zigbee2mqtt/issues/12312

**Comment by jrhansen** [comment]
Resetting the frontend cache as described in the other thread worked perfectly.

Thanks, mikchalk-k, for pointing out the other thread.
