### ISSUE TITLE
Unstable connection with WOOX 7060 irrigation Valve

### ISSUE THREAD

**Issue by nielsvlaarhoven** [Koenkk/zigbee2mqtt#12619]
### What happened?

I recentle purchased a WOOX R7060 water valve for the irrigation of my garden.
I added it to HA using the deCONZ addon, which didn't want to accept it at first but worked after pairing a few times. 
After rebooting HA or deCONZ the WOOX R7060 loses connection to the zigbee network (see attached screendump)
![image](https://user-images.githubusercontent.com/59313935/170817592-ddec074e-a009-4292-b134-a502b140671d.png)
Even after a day or two it loses connection by itsself, the closest (stable) zigbee device is not even 2.5 meters away from the WOOX R7060.
I have tried to integrate it in ZHA to rule out deCONZ which is losing the connection, but when using ZHA it loses connection as wel.
I have to pair the device again to make it work again.

Using HA (running as a virtual machine on ESX host);
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

deCONZ;
6.13.0

Conbee II;
Version; 2.15.03 / 4/21/2022
Firware; 26660700

### What did you expect to happen?

the connection with the WOOX R7060 remains 

### How to reproduce it (minimal and precise)

Pair the WOOX R7060 and restart HA or deCONZ makes it lose connection.

### Zigbee2MQTT version

n.a.

### Adapter firmware version

2.15.03 / 4/21/2022

### Adapter

CONBEE II

**Comment by nielsvlaarhoven** [comment]
As you can see in the attached screendump, in the mesh map it only has one active connection (with a device quite far away eventhough there are several devices much closer). 
![image](https://user-images.githubusercontent.com/59313935/170837433-f9752433-8a34-4abc-bada-05a4aad035d2.png)

**Comment by GSzabados** [comment]
Try to use the option to pair it to a specific device. But why are you posting here an issue if you do not even use Zigbee2MQTT???

**Comment by Koenkk** [comment]
Indeed not a Zigbee2MQTT issue, please create it in to Deconz issue tracker: https://github.com/dresden-elektronik/deconz-rest-plugin/issues

**Comment by nielsvlaarhoven** [comment]
Sorry for my stupidity posting it in the wrong topic. @Koenkk thnx for the tip.
