### ISSUE TITLE
[New device support]: unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_zloso4jk'

### ISSUE THREAD

**Issue by Nickje1989** [Koenkk/zigbee2mqtt#12636]
### Link

https://nl.aliexpress.com/item/1005003444957152.html?srcSns=sns_WhatsApp&spreadType=socialShare&bizType=ProductDetail&social_params=60152907984&aff_fcid=cdfe8089df6843279fc0a5b0864f25f9-1653851083929-05382-_vkPFK0&tt=MG&aff_fsk=_vkPFK0&aff_platform=default&sk=_vkPFK0&aff_trace_key=cdfe8089df6843279fc0a5b0864f25f9-1653851083929-05382-_vkPFK0&shareId=60152907984&businessType=ProductDetail&platform=AE&terminal_id=01f92b5dec1a41319711bc54afff0cbc&afSmartRedirect=y

### Database entry

{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b001949dc14","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"10":{"profId":260,"epId":10,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[1281],"outClusterList":[1280,1282],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}

### Comments

i tried to configure this smart plug but i can't get it to work. The plug is paired but I can't get any further. who can help me?

Zigbee2MQTT:warn  2022-05-29 21:17:56: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_zloso4jk'
Zigbee2MQTT:warn  2022-05-29 21:17:56: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

![Schermafbeelding 2022-05-29 211251](https://user-images.githubusercontent.com/106490224/170887666-01322ede-b777-4ecd-95bb-48f891a4e94b.png)

**Comment by Koenkk** [comment]
`_TZ3000_zloso4jk` will be supported in the next z2m version (which will be released on 1 June)
