### ISSUE TITLE
LIDL HG06336 Door sensor N/A contact, battery_low, tamper and LQI

### ISSUE THREAD

**Issue by seederp2p** [Koenkk/zigbee2mqtt#12649]
### What happened?

I'm using LIDL HG06336 Door sensor with HA 2022.5.5 and Zigbee2mqtt 1.18.1-1.

My coordinator is SONOFF Zigbee 3.0 firmware version 20220219

The sensor itself shows firmware version: 2019.12.12

The device is listed but 

### What did you expect to happen?

It should show real data and not "N/A" on contact, battery_low, tamper and LQI

### How to reproduce it (minimal and precise)

I can remove the device and try again with the same result.

### Zigbee2MQTT version

1.18.1-1

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 firmware version 20220219

**Comment by seederp2p** [comment]
Update:

Using ZHA works perfectly.

So, maybe, this is a Z2M bug?

**Comment by Koenkk** [comment]
You are using a very old z2m version, try updating to the latest and wait 24 hours so that the sensor can report its data.

If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0

**Comment by seederp2p** [comment]
Hi ! @Koenkk 

Ok. So I fresh installed my Z2M.

Right now is running version 1.25.1-2

Re-added my door contact sensor and got the same results:

contact
N/A

battery_low
N/A

tamper
N/A

battery
Remaining battery in %
100%

linkquality
145lqi

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by seederp2p** [comment]
Hello,

After upgrading Z2M to 1.25.2-1 and today, HA to 2022.6.1, I re-added the device.

It looked like the same but I tried to reconfigure it as your said previously.

For some reason it now works.

Anyway, how can I retrieve the data/database.db inside HA?
