### ISSUE TITLE
[New device support]: ENVILAR ZG50CC-CCT-DRIVER

### ISSUE THREAD

**Issue by jrosenkjaer** [Koenkk/zigbee2mqtt#12643]
### Link

https://www.plusled.dk/zigbee-led-driver-12v-controller-m-indbygget-stromforsyning-cct-kelvin-styring-0-50w.html

### Database entry

{"id":38,"type":"Router","ieeeAddr":"0x84ba20fffe345d59","nwkAddr":15169,"manufId":4107,"manufName":"ENVILAR","powerSource":"Mains (single phase)","modelId":"ZG50CC-CCT-DRIVER","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r60","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1653919270792,"defaultSendRequestWhen":"immediate"}

### Comments

I have tried to create an external converter for this, but keeps saying NOT supported.

This seems to be a whitelabel product, and can't find the manufacturer product page, only the reseller product page.

I am willing to keep trying, but I just seem to be stuck for now, so any hints or help would be appriciated.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZG50CC-CCT-DRIVER'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'ZG50CC-CCT-DRIVER', // Vendor model number, look on the device for a model number
    vendor: 'ENVILAR', // Vendor of the device (only used for documentation and startup logging)
    description: 'ENVILAR ZG50CC-CCT-DRIVER', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    extend: extend.light_onoff_brightness(),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added the device, can you check if it works?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
