### ISSUE TITLE
ZNJLBL01LM state is always "OFF"

### ISSUE THREAD

**Issue by negmos** [Koenkk/zigbee2mqtt#12647]
### What happened?

ZNJLBL01LM state is always reported as "OFF" although it shall be [Open, Close, Stop].

The state is "OFF" whether it is reported after any action or using "/get" topic.

Setting the "state" with Open, Close, or Stop works fine, but the value reported back is always "OFF".

Example of the output reported after a state change:
`info  2022-05-30 19:02:44: MQTT publish: topic 'zigbee2mqtt/xiaomi_roller_1', payload '{"battery":88,"charging_status":false,"illuminance":0,"illuminance_lux":0,"linkquality":83,"motor_state":"pause","position":100,"running":false,"state":"OFF","temperature":22,"update":{"state":"idle"}}'`

### What did you expect to happen?

It is expected that the "state" will reflect the actual state of the cover (Open, Close, Stop)

### How to reproduce it (minimal and precise)

use the topic "/get" with the ZNJLBL01LM and with paylod = {"status": ""}, the reported state will always be "OFF"

### Zigbee2MQTT version

1.25.1 commit: 3f6a137

### Adapter firmware version

20220219

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

**Comment by Otnow** [comment]
Please write a [debug log](https://www.zigbee2mqtt.io/guide/usage/debug.html#enabling-logging) with the following actions:

- press the pairing button once and wait 10 seconds
- set the `position` **to 0** and wait for the motor to reach this position
- press the pairing button once and wait 10 seconds
- set the `position` **to 50** and wait for the motor to reach this position
- press the pairing button once and wait 10 seconds
- set the `position` **to 100** and wait for the motor to reach this position
- press the pairing button once and wait 10 seconds
- set the `position` **to 0** and wait for the motor to reach this position
