### ISSUE TITLE
Legrand 067726 Position set not working

### ISSUE THREAD

**Issue by cyrilphoenix71** [Koenkk/zigbee2mqtt#12655]
### What happened?

Legrand 067776 White model is pairing ok
State seems to be ok :
{
    "device": {
        "applicationVersion": 0,
        "dateCode": " \u000020220401\u0000\u0000\u0000\u0000\u0000",
        "friendlyName": "Volet Salle",
        "hardwareVersion": 1,
        "ieeeAddr": "0x0004740000b99330",
        "manufacturerID": 4129,
        "manufacturerName": " Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
        "model": "067776",
        "networkAddress": 12211,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "001a",
        "stackVersion": 65,
        "type": "Router",
        "zclVersion": 2
    },
    "last_seen": "2022-05-31T00:39:57+02:00",
    "linkquality": 255,
    "position": 66,
    "action": ""
}
But we cannot play with position command, only 100% to open completely works and any value from 0 to 99% goes to close the shutter completely.

### What did you expect to happen?

I want to send (with z2m position slider) 50% in position to open the shutter to 50% level

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

26660700

### Adapter

Conbee2

### Debug log

Info 2022-05-31 00:47:09Succesfully changed options
Info 2022-05-31 00:47:09MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"lq8sz-2"}'
Debug 2022-05-31 00:47:22Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":100}'
Debug 2022-05-31 00:47:22Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:47:22MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:47:19+02:00","linkquality":95,"position":48}'
Info 2022-05-31 00:47:22MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:47:19+02:00","linkquality":95,"position":100}'
Debug 2022-05-31 00:47:28Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":46}'
Debug 2022-05-31 00:47:28Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:47:28MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:47:25+02:00","linkquality":247,"position":100}'
Info 2022-05-31 00:47:28MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:47:25+02:00","linkquality":247,"position":46}'
Debug 2022-05-31 00:48:09Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":68}'
Debug 2022-05-31 00:48:09Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:48:10MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:06+02:00","linkquality":215,"position":46}'
Info 2022-05-31 00:48:10MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:06+02:00","linkquality":215,"position":68}'
Debug 2022-05-31 00:48:46Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":88}'
Debug 2022-05-31 00:48:46Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:48:47MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:44+02:00","linkquality":215,"position":68}'
Info 2022-05-31 00:48:47MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:44+02:00","linkquality":215,"position":88}'
Debug 2022-05-31 00:48:49Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":95}'
Debug 2022-05-31 00:48:49Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:48:49MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:46+02:00","linkquality":215,"position":88}'
Info 2022-05-31 00:48:49MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:46+02:00","linkquality":215,"position":95}'
Debug 2022-05-31 00:48:51Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":100}'
Debug 2022-05-31 00:48:51Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:48:51MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:48+02:00","linkquality":215,"position":95}'
Info 2022-05-31 00:48:51MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:48+02:00","linkquality":215,"position":100}'
Debug 2022-05-31 00:48:52Received Zigbee message from 'Volet Salle', type 'attributeReport', cluster 'genIdentify', data '{"identifyTime":180}' from endpoint 1 with groupID null
Info 2022-05-31 00:48:52MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"action":"identify","device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:48+02:00","linkquality":223,"position":100}'
Info 2022-05-31 00:48:52MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"action":"","device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:48+02:00","linkquality":223,"position":100}'
Info 2022-05-31 00:48:52MQTT publish: topic 'zigbee2mqtt/Volet Salle/action', payload 'identify'
Debug 2022-05-31 00:48:54Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"state":"STOP"}'
Debug 2022-05-31 00:48:54Publishing 'set' 'state' to 'Volet Salle'
Info 2022-05-31 00:48:55MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:52+02:00","linkquality":255,"position":100}'
Debug 2022-05-31 00:48:55Received Zigbee message from 'Volet Salle', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":50}' from endpoint 1 with groupID null
Info 2022-05-31 00:48:55MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:52+02:00","linkquality":247,"position":50}'
Debug 2022-05-31 00:48:59Received Zigbee message from 'Volet Salle', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":50}' from endpoint 1 with groupID null
Info 2022-05-31 00:48:59MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:48:56+02:00","linkquality":255,"position":50}'
Warning 2022-05-31 00:48:59Failed to ping '0x0017880108b37a64' (attempt 1/1, Read 0x0017880108b37a64/11 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))
Debug 2022-05-31 00:49:02Active device '0x0017880108b37a64' was last seen '144.94' minutes ago.
Warning 2022-05-31 00:50:24Failed to ping '0x00178801064c1529' (attempt 1/1, Read 0x00178801064c1529/11 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))
Debug 2022-05-31 00:50:27Active device '0x00178801064c1529' was last seen '488.05' minutes ago.
Debug 2022-05-31 00:51:08Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":100}'
Debug 2022-05-31 00:51:08Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:51:08MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:05+02:00","linkquality":255,"position":50}'
Info 2022-05-31 00:51:08MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:05+02:00","linkquality":255,"position":100}'
Debug 2022-05-31 00:51:32Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"position":44}'
Debug 2022-05-31 00:51:32Publishing 'set' 'position' to 'Volet Salle'
Info 2022-05-31 00:51:32MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:29+02:00","linkquality":231,"position":100}'
Info 2022-05-31 00:51:32MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:29+02:00","linkquality":231,"position":44}'
Debug 2022-05-31 00:51:32Received Zigbee message from 'Volet Salle', type 'attributeReport', cluster 'genIdentify', data '{"identifyTime":180}' from endpoint 1 with groupID null
Info 2022-05-31 00:51:32MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"action":"identify","device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:29+02:00","linkquality":215,"position":44}'
Info 2022-05-31 00:51:32MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"action":"","device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:29+02:00","linkquality":215,"position":44}'
Info 2022-05-31 00:51:32MQTT publish: topic 'zigbee2mqtt/Volet Salle/action', payload 'identify'
Debug 2022-05-31 00:51:36Saving state to file /app/data/state.json
Debug 2022-05-31 00:52:00Received MQTT message on 'zigbee2mqtt/Volet Salle/set' with data '{"state":"CLOSE"}'
Debug 2022-05-31 00:52:00Publishing 'set' 'state' to 'Volet Salle'
Info 2022-05-31 00:52:01MQTT publish: topic 'zigbee2mqtt/Volet Salle', payload '{"device":{"applicationVersion":0,"dateCode":" \u000020220401\u0000\u0000\u0000\u0000\u0000","friendlyName":"Volet Salle","hardwareVersion":1,"ieeeAddr":"0x0004740000b99330","manufacturerID":4129,"manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","model":"067776","networkAddress":12211,"powerSource":"Mains (single phase)","softwareBuildID":"001a","stackVersion":65,"type":"Router","zclVersion":2},"last_seen":"2022-05-31T00:51:58+02:00","linkquality":231,"position":44}'

**Comment by bemble** [comment]
I think to be able to have it work we need the `lift_duration` to be set or find a way to automatically calibrate the module (my enocean shutter modules were able to automatically calibrate the lift duration).

Another thing, we are not able to set how the led behave. When I take a look at the converter ([legrand.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/legrand.js#L109)), we should be able to set how the led behaves.

**Comment by bemble** [comment]
Setting position is not even possible in legrand app, we have to wait a firmware update from legrand and hope it would be available.
