### ISSUE TITLE
npm ERR! zigbee2mqtt@1.2.1 start: node index.js Start Error

### ISSUE THREAD

**Issue by djuscha** [Koenkk/zigbee2mqtt#1265]
get after the installationof zigbee2mqtt not to run that I get as error message. What am I doing wrong
[code](https://hastebin.com/deyobitima.rb)
firmware  CC2531ZNP-Prod_20190223

**Comment by Koenkk** [comment]
The syntax in your `configuration.yaml` is invalid, fix it by using e.g. http://www.yamllint.com/

**Comment by djuscha** [comment]
that's how the configuration.yaml looks like and still Errors

`permit_join: true
# MQTT settings
mqtt:
# MQTT base topic for zigbee2mqtt MQTT messages
base_topic: zigbee2mqtt
# MQTT server URL
server: 'mqtt://localhost'
# MQTT server authentication, uncomment if required:
user: openhabian
password: openhabian
# Serial settings
serial:
# Location of CC2531 USB sniffer
port: /dev/ttyACM1
`

**Comment by Koenkk** [comment]
you need to put spaces in the section between `mqtt` and `serial` example: http://www.zigbee2mqtt.io/configuration/configuration.html

**Comment by djuscha** [comment]
have deleted everything and made new now it . 
now everything is good :)
