### ISSUE TITLE
Cover _TZE200_xuzcvlku bad position report

### ISSUE THREAD

**Issue by leroyloren** [Koenkk/zigbee2mqtt#12679]
### What happened?

after this commit ( [_TZE200_xuzcvlku](https://github.com/Koenkk/zigbee-herdsman-converters/issues/4140) ) the cover do not report current position and state. State is still open when the cover is closed.

### What did you expect to happen?

1) Current position is reporting
2) state is open/close

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220507

### Adapter

zzh!

### Debug log

`Debug 2022-06-01 21:57:58Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,99],"type":"Buffer"},"datatype":2,"dp":2}],"seq":15}' from endpoint 1 with groupID 0
Info 2022-06-01 21:57:58MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:57:58+02:00","linkquality":142,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:57:59Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,97],"type":"Buffer"},"datatype":2,"dp":2}],"seq":15}' from endpoint 1 with groupID 0
Info 2022-06-01 21:57:59MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:57:59+02:00","linkquality":138,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:12Received MQTT message on 'zigbee2mqtt/Roleta pokoj/set' with data 'OPEN'
Debug 2022-06-01 21:58:12Publishing 'set' 'state' to 'Roleta pokoj'
Debug 2022-06-01 21:58:13Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":1}],"seq":34}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:13MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:14+02:00","linkquality":149,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:14Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,95],"type":"Buffer"},"datatype":2,"dp":2}],"seq":34}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:14MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:15+02:00","linkquality":138,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:15Received MQTT message on 'zigbee2mqtt/Roleta pokoj/set' with data 'STOP'
Debug 2022-06-01 21:58:15Publishing 'set' 'state' to 'Roleta pokoj'
Debug 2022-06-01 21:58:15Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,94],"type":"Buffer"},"datatype":2,"dp":2}],"seq":34}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:15MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:16+02:00","linkquality":145,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:16Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":1}],"seq":35}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:16MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:16+02:00","linkquality":149,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:16Received Zigbee message from 'Roleta pokoj', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,93],"type":"Buffer"},"datatype":2,"dp":2}],"seq":35}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:16MQTT publish: topic 'zigbee2mqtt/Roleta pokoj', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:17+02:00","linkquality":145,"position":0,"running":true,"state":"CLOSE"}'
Debug 2022-06-01 21:58:18Received MQTT message on 'zigbee2mqtt/Roleta pokoj 2/set' with data 'CLOSE'
Debug 2022-06-01 21:58:18Publishing 'set' 'state' to 'Roleta pokoj 2'
Debug 2022-06-01 21:58:19Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":1}],"seq":36}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:19MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:19+02:00","linkquality":102,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:19Received MQTT message on 'zigbee2mqtt/Roleta pokoj 2/set' with data 'OPEN'
Debug 2022-06-01 21:58:19Publishing 'set' 'state' to 'Roleta pokoj 2'
Debug 2022-06-01 21:58:20Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":1}],"seq":37}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:20MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:20+02:00","linkquality":116,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:21Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,98],"type":"Buffer"},"datatype":2,"dp":2}],"seq":37}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:21MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:22+02:00","linkquality":105,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:22Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,96],"type":"Buffer"},"datatype":2,"dp":2}],"seq":37}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:22MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:23+02:00","linkquality":105,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:23Received MQTT message on 'zigbee2mqtt/Roleta pokoj 2/set' with data 'CLOSE'
Debug 2022-06-01 21:58:23Publishing 'set' 'state' to 'Roleta pokoj 2'
Debug 2022-06-01 21:58:24Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":1}],"seq":38}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:24MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:24+02:00","linkquality":98,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:25Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,98],"type":"Buffer"},"datatype":2,"dp":2}],"seq":38}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:25MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:26+02:00","linkquality":98,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:26Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,99],"type":"Buffer"},"datatype":2,"dp":2}],"seq":38}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:26MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:27+02:00","linkquality":105,"position":4,"running":true,"state":"OPEN"}'
Debug 2022-06-01 21:58:27Received Zigbee message from 'Roleta pokoj 2', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,100],"type":"Buffer"},"datatype":2,"dp":2}],"seq":38}' from endpoint 1 with groupID 0
Info 2022-06-01 21:58:27MQTT publish: topic 'zigbee2mqtt/Roleta pokoj 2', payload '{"color_mode":"xy","last_seen":"2022-06-01T21:58:28+02:00","linkquality":102,"position":4,"running":true,"state":"OPEN"}'`

**Comment by Cameleon99** [comment]
Position is also now broken on my 'Tuya  TS0601_cover' (M515EGZT). This previously worked great (albeit saying always running but HA and HomeKit ignored this). Now always reports 100%. Please revert.

**Comment by Cameleon99** [comment]
Having hacked around a bit with the external converter mentioned here - https://github.com/Koenkk/zigbee-herdsman-converters/pull/4001#issuecomment-1067956559 - I have been able to get it working. It appears that _TZE200_xuzcvlku / TS0601 / M515EGZT is only reporting tuya.dataPoints.coverChange and tuya.dataPoints.coverPosition and not tuya.dataPoints.coverArrived. So it thinks the cover has never arrived at the required position. Hacking it, I am getting it to report position and this has it working again in HA/Homekit (via HA).

Another thing to note, and not sure if this is expected behaviour for this device, when I have the limits set, if I call open/close, it will report the absolute position. In my case the blind only opens 77 to 100. Calling open will move it to 100, and close will move it to 77. If you call a position less than 77 the blind will start to wind back up the other way! So I have had to create a template device in HA to convert the absolute position of 77-100 to relative positions of 0-100.

**Comment by aatemes** [comment]
Same error with my [TS0601_cover]

**Comment by tungmeister** [comment]
Just checked the latest dev branch and it's still broken.

**Comment by hys1304** [comment]
Me too. Same problem with my [
TS0601_cover, TZE200_r0jdjrvi
Curtain State, position not seen

**Comment by jdbrookes** [comment]
Darn it, just updated zigbee2mqtt this morning and now seeing this issue for this exact model, will probably need to roll back.

Somewhat related, for others with this model _TZE200_xuzcvlku do you frequently see that the device will ignore commands from zigbee2mqtt and home assistant? Opening or closing commands are ignored, but the state of the blind is immediately reported if the blinds are triggered using the RF remote or the device buttons. Often it will start working again by itself, but otherwise i need to quickly Re-add to the zigbee network. I've 3 of these blind motors so not sure if operating them in a group is causing this issue.

**Comment by Cameleon99** [comment]
> Somewhat related, for others with this model _TZE200_xuzcvlku do you frequently see that the device will ignore commands from zigbee2mqtt and home assistant? Opening or closing commands are ignored, but the state of the blind is immediately reported if the blinds are triggered using the RF remote or the device buttons. 

Yes I get this too. It was very stable. However I have recently moved an old HUE Bloom into the same room and it seems to be routing via that, which it wasn't before. So not sure if the HUE is the cause or MQTT. I've removed the HUE for now and it seems to be working ok again, however this morning my wake up routine did not open the blind. I will see how it goes with that HUE out of the loop for a while, I have a feeling it was just a coincidence and there is another issue with MQTT.

**Comment by tungmeister** [comment]
> Darn it, just updated zigbee2mqtt this morning and now seeing this issue for this exact model, will probably need to roll back.
> 
> Somewhat related, for others with this model _TZE200_xuzcvlku do you frequently see that the device will ignore commands from zigbee2mqtt and home assistant? Opening or closing commands are ignored, but the state of the blind is immediately reported if the blinds are triggered using the RF remote or the device buttons. Often it will start working again by itself, but otherwise i need to quickly Re-add to the zigbee network. I've 3 of these blind motors so not sure if operating them in a group is causing this issue.

Yes I've had this a few times over the last 7 months

**Comment by leroyloren** [comment]
Resolved https://github.com/Koenkk/zigbee2mqtt/issues/12719
