### ISSUE TITLE
Fail ocuppancy detection of device Neo TS0202 on Z2M 1.25.2-1

### ISSUE THREAD

**Issue by Rubquila** [Koenkk/zigbee2mqtt#12682]
### What happened?

I lose the functionality of Ocuppancy detection of device Neo NAS-AB02B2  (TS0202 _TZ3000_kmh5qpmb) on the last version of Zigbee2Mqtt 1.25.2-1

### How to reproduce it (minimal and precise)

Install Zigbee2Mqtt 1.25.2-1

### Zigbee2MQTT version

1.25.2-1

### Adapter firmware version

20210708

### Adapter

Sonoff

### Debug log

Zigbee2MQTT:error 2022-06-01 22:48:27: Failed to configure 'Detector de la cocina', attempt 1 (Error: Command 0xa4c138c54c6cff74/1 manuSpecificTuya.dataQuery({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:414:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))
Zigbee2MQTT:error 2022-06-02 01:05:04: Publish 'set' 'alarm' to 'Detector de la cocina' failed: 'Error: Command 0xa4c138c54c6cff74/1 manuSpecificTuya.dataRequest({"seq":0,"dpValues":[{"dp":13,"datatype":1,"data":[0]}]}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'

**Comment by markvan74** [comment]
I'm getting the same issue when updating to v1.26.0-1. Says my motion sensor is an alarm, and it no longer functions as a motion sensor.
