### ISSUE TITLE
Müller Licht 45317 is missidentified

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#12690]
### What happened?

The Müller Licht 45317 Bulb (E27) is misidentified as the following:

https://www.zigbee2mqtt.io/devices/404036_45327.html

The docs should be extended to reflect that the 45317 is also part of this group (if more specific identification isn't possible.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB stick

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
