### ISSUE TITLE
State issue with a group composed of one Lidl HG06338

### ISSUE THREAD

**Issue by Nardol** [Koenkk/zigbee2mqtt#12693]
### What happened?

I have created a group with all endpoints of a lidl [HG06338](https://www.zigbee2mqtt.io/devices/HG06338.html#lidl-hg06338)
If I restart Home Assistant, state is not recognized correctly:
![Capture multi-prises deux boutons](https://user-images.githubusercontent.com/2864821/171676907-233931d3-8501-4b8d-b7cd-6c2f1f2cfafc.png)
If I press one of these two buttons or change state of one of the switches of the group, state becomes OK.
![Capture multi-prises interrupteur normal](https://user-images.githubusercontent.com/2864821/171677159-eb67c394-2344-438e-945f-832b8c57a1d0.png)
For another group but with Hue lights, I don't observe this behavior.

### What did you expect to happen?

I expected a real state after I reboot HA, in fact as the second screenshot.

### How to reproduce it (minimal and precise)

First create a group with only the trhee endpoint of this Lidl device, after some minutes restart Home Assistant and the state will be as the first screenshot.
In the joined debug log I switched off then on one of the switches at 18:06

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

[log-debug-zb2mqtt.txt](https://github.com/Koenkk/zigbee2mqtt/files/8825766/log-debug-zb2mqtt.txt)

**Comment by Nardol** [comment]
When reading the log in info level which I better understand, it looks like the state of the three switches is published but not the state of the group itself.

**Comment by Nardol** [comment]
Another thing because I still try to understand even if my knowledge is poor about that, it looks like the device publishes its state very rarely so maybe state is not published when Home Assistant get it on MQTT?

**Comment by Nardol** [comment]
> This is the moment Home Assistant says "I'm online", now Zigbee2MQTT will wait 30 seconds to republish the state of this device (to give HA some time to startup, during these 30 seconds the state might be incorrect)
> 
> ```
> info  02/06/2022 18:09:29: MQTT publish: topic 'zigbee2mqtt/Multi-prises Commode Chambre', payload '{"linkquality":65,"state_l1":"ON","state_l2":"ON","state_l3":"ON"}'
> ```

Sorry, as it was something on HA side I forgot to mention I renamed the group in Home Assistant.
Multi-Prises commode Chambre is the name of the device in Zigbee2MQTT but not the group name, which is Prises Commode Chambre.
In Home Assistant I named the ZB2MQTT group Prises Commode Chambre as Multi-Prises Commode Chambre
And during the period of 30 seconds after HA is online I don't find any publish to the topic `zigbee2mqtt/prises Commode Chambre` which is the group topic, except if I make another mistake.

Zigbee2MQTT group configuration:

```yaml
'3':
  friendly_name: Prises Commode Chambre
  devices:
    - 0xec1bbdfffefd2dbe/1
    - 0xec1bbdfffefd2dbe/2
    - 0xec1bbdfffefd2dbe/3
```

I hop I don't forget something else.

**Comment by Koenkk** [comment]
I found out the group states were not send at all! Added this now, can you check if this is fixed?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Nardol** [comment]
I confirm the fix, when restarting Home Assistant groups states are OK.
Thanks!

**Comment by sj3fk3** [comment]
Very much awesomeness.. I sooo love zigbee2mqtt and it's dev's ;-)

**Comment by sj3fk3** [comment]
> I found out the group states were not send at all! Added this now, can you check if this is fixed?
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Hi Koen, I've also installed the dev branch and I'm still seeing the same behaviour. Zigbee groups "Unavailable" after HA restart and the are OK again after I restart zigbee2mqtt.

Also, thanks for the "howto" on switching to the dev branch, maybe also add how to switch back? I'm guessing same procedure but "Master" instead of "dev", right?
