### ISSUE TITLE
Zigbee Modul

### ISSUE THREAD

**Issue by MiguelESP89** [Koenkk/zigbee2mqtt#127]
Hey ich habe noch ein Zigbeemodul von Dresden Elektronik rumliegen

https://shop.dresden-elektronik.de/raspbee.html

Ist der zufällig auch kompatibel? Dann bräuchte ich mir den USB Stick nicht holen.

Vielen Dank

Miguel

**Comment by Koenkk** [comment]
No, only TI usb sniffers are compatible (CC2530/CC2531).
