### ISSUE TITLE
button Xiaomi WXKG1 has appeared in the dashboard since the last update with a not very fair temperature.

### ISSUE THREAD

**Issue by Jeepmg** [Koenkk/zigbee2mqtt#12700]
### What happened?

button Xiaomi WXKG1 has appeared in the dashboard since the last update with a not very fair temperature.

### What did you expect to happen?

How to make it disappear from the dashbard.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

zStack3x0

**Comment by Otnow** [comment]
Please provide the exact device model and provide a screenshot and/or [debug log](https://www.zigbee2mqtt.io/guide/usage/debug.html#enabling-logging) showing the problem.

**Comment by Jeepmg** [comment]
Sorry; Exact model : WXKG1LM

![Capture d’écran du 2022-06-03 14-15-24](https://user-images.githubusercontent.com/103240876/171852278-c2d9ba6f-5e69-40d0-a77d-966bc7d792aa.png)

This tile did not appear with z2m V 1.25.1 because there was no published value for the device temperature.

this device has no reason to appear in the dashboard.

**Comment by Otnow** [comment]
You seem to be referring to the [WXKG11LM](https://www.zigbee2mqtt.io/devices/WXKG11LM.html) model.

For her, the `device_temperatur`e was indeed recently [exposed](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4265) and this is not a problem, because this is not a climatic value, such as for [WSDCGQ11LM](https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html), but a service value (**chip temperature** on the device board).

**Comment by Jeepmg** [comment]
It's actually the WXKG11LM I'm talking about. However, other Aqara sensors have seen their "climate sensor" switch to "device sensor", such as Aqara water leak sensor (Xiaomi SJCGQ11LM).

It's all a bit confusing.

How could we do without "chip temperature" until today?

Why settle for a clear and readable dashbard when you can have one full of useless tiles?

**Comment by Otnow** [comment]
Until recently, there really was confusion with the temperature values, so the name was changed and a clear division into climatic temperature (`temperature`) and service temperature of the chip (`device_temperature`) was made.

For example, the [WSDCGQ12LM](https://www.zigbee2mqtt.io/devices/WSDCGQ12LM.html) and [VOCKQJK11LM](https://www.zigbee2mqtt.io/devices/VOCKQJK11LM.html) sensors report both temperature values.
