### ISSUE TITLE
[New device support]: GU10 Bulb KURVIA ZB-CL01 

### ISSUE THREAD

**Issue by XeonStaf** [Koenkk/zigbee2mqtt#12715]
### Link

https://drive.google.com/file/d/1M1HaVj0bS-lg9RgYfPFLDguIF4wwU8ck/view?usp=sharing

### Database entry

{"id":7,"type":"Router","ieeeAddr":"0xa4c1385fcd35895e","nwkAddr":56679,"manufId":4107,"manufName":"KURVIA","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"hwVersion":0}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{"scenes":{"0_0":{"name":"Scene 0","state":{"state":"ON","brightness":254,"color_mode":"color_temp","color":{"x":0.3804,"y":0.3767},"color_temp":250}}}}}},"appVersion":3,"stackVersion":2,"hwVersion":0,"dateCode":"20211229","swBuildId":"2.0.1","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1654367521613,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to code a converter, but I was stuck with a problem that the bulb does not turn off completely when I use HueConverter. (light doesn't turn off, it is just set to minimum brightness)
When I use _extend.light_onoff_brightness_colortemp_color({colorTempRange: [250, 454]}),_ builb works fine, but I need to configure power-on behavior.
I can set it via Hue, since this bulb supportss Hue, so I want to use the "power_on_behaivor" function. 

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;


const extendDontUse = require('zigbee-herdsman-converters/lib/extend');
const extend = {switch: extendDontUse.switch};

const hueExtend = {
    light_onoff_brightness_colortemp_color: (options={}) => ({
        ...extendDontUse.light_onoff_brightness_colortemp_color({supportsHS: true, ...options}),
        toZigbee: extendDontUse.light_onoff_brightness_colortemp_color({supportsHS: true, ...options})
            .toZigbee.concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
};

module.exports = [
    {
        zigbeeModel: ['ZB-CL01'],
        model: 'ZB-CL01',
        vendor: 'KURVIA', 
        description: 'GU10 GRBWC Built from Aliexpress',
        extend: hueExtend.light_onoff_brightness_colortemp_color({colorTempRange: [250, 454]}),
 meta: {turnsOffAtBrightness1: true}
    }
]
```

### Supported color modes

color temperature, color

### Color temperature range

{"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}

**Comment by azuanaa** [comment]
Please refer to #12053 for the same product. It just it has not been included in the main supported device.
