### ISSUE TITLE
Müller Licht remote is detected as non-battery device

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#12717]
### What happened?

I have some Zigbee remotes from Müller Licht which are also missidentified as a different model right now (see #12651) but additionally the model seems to either report its energy source wrongly via Zigbee or the database in Zigbee2MQTT is wrong here:

![IMG_20220605_015232](https://user-images.githubusercontent.com/614929/172029457-457e38b3-2e74-41bd-808d-e190aed5fe6b.jpg)

### What did you expect to happen?

Powersource should show a battery symbol, as those devices are battery operated. 

### How to reproduce it (minimal and precise)

- Pair a Müller Licht 404049C remote
- Go to the device list
- see a "power plug" symbol as power source 

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB stick

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
