### ISSUE TITLE
[New device support]: Moes TS0011 Manufacturer _TZ3000_hhiodade

### ISSUE THREAD

**Issue by digitui** [Koenkk/zigbee2mqtt#12739]
### Link

https://github.com/Koenkk/zigbee-herdsman-converters/blob/70027fcd1598ef93edf54e8ee9e95b2fbb1708a2/devices/moes.js

### Database entry

IEEE Address 0xa4c138e5fd7f53a6 Network address 0x95FB TS0011 Zigbee Manufacturer _TZ3000_hhiodade

### Comments

Seems this device is not fully supported. This devices does allow some extra features, as per.
https://www.zigbee2mqtt.io/devices/ZTS-EU_1gang.html

**Comment by mak-42** [comment]
I received the same switches and create the external converter to add some missing functionality. It works for me. But I like someone to test it as well. I'll create a MR if the the test passes successfully.

You need to unpack the external converter into Z2M config folder, add it to the configuration (using web UI or directly into "configuration.yaml") and restart Z2M.
[ZS-EUB.zip](https://github.com/Koenkk/zigbee2mqtt/files/9447536/ZS-EUB.zip)
