### ISSUE TITLE
[New device support]: Tuya plug EU 16A - TS011F manufacturer _TZ3000_iksasdbv 

### ISSUE THREAD

**Issue by ivdimitro** [Koenkk/zigbee2mqtt#12743]
### Link

https://zigbee.blakadder.com/Tuya_TS011F.html

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0x84ba20fffe77af87","nwkAddr":32488,"manufId":4098,"manufName":"_TZ3000_iksasdbv","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1654597597884,"defaultSendRequestWhen":"immediate"}

### Comments

I think the device should be supported already. Only missing the specific device id and manufacturer. 
Thanks.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
