### ISSUE TITLE
[New device support]: Temperature & Humidity Sensor IH-K009

### ISSUE THREAD

**Issue by MrSimpa** [Koenkk/zigbee2mqtt#12759]
### Link

https://zigbee.blakadder.com/Tuya_IH-K009.html

### Database entry

{"id":17,"type":"EndDevice","ieeeAddr":"0xa4c138de14b2e8c3","nwkAddr":58677,"manufId":4417,"manufName":"_TZ3000_dowj6gyi","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,3,1026,1029,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u001c\u0000\u0000\u0000\u0012","65506":51,"65508":1,"65534":0,"modelId":"TS0201","manufacturerName":"_TZ3000_dowj6gyi","powerSource":3,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2410}},"msRelativeHumidity":{"attributes":{"measuredValue":6525}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":126974596},"lastSeen":1654773484239,"defaultSendRequestWhen":"immediate"}

### Comments

In Z2M in Homeassistant it is recognized as: 
Zigbee Model: TS0201
Zigbee Manufacturer: _TZ3000_dowj6gyi

Must be model: IH-K009

I have 5 of them but i can pair just one at the same time and battery and voltage data is not shown.
Link from Aliexpress:
https://www.aliexpress.com/item/1005003187008387.html?spm=a2g0o.productlist.0.0.7c2f1585QcNYe0&algo_pvid=3645cc40-dedc-4521-b965-a63a1ab1e05b&algo_exp_id=3645cc40-dedc-4521-b965-a63a1ab1e05b-1&pdp_ext_f=%7B%22sku_id%22%3A%2212000024655138867%22%7D&pdp_npi=2%40dis%21EUR%21%215.57%21%21%21%21%21%40210318b916547747524964736e07a0%2112000024655138867%21sea

**Comment by thierrybla** [comment]
I also want this device to work, I bought a lot of them but now it doesn't show anything in Home assistant :(

**Comment by thierrybla** [comment]
Maybe this might be helpful? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5483

**Comment by timnolte** [comment]
I too just got a couple of these and thought it was the same model as one listed as supported.

**Comment by timnolte** [comment]
I just decided to try adding my device and it registered and started working just fine even though it was identified as a WSD500A. So the device looks to be perfectly usable. I'm going to have to do some testing to confirm the readings are correct and updating in Home Assistant as well.

**Comment by thierrybla** [comment]
Nothing shows up for me in home assistant, where did you try it?

**Comment by timnolte** [comment]
I simply turned on pairing in Z2M put the device into pairing mode. It recognized the device and it's showing up all correct in Home Assistant under my Mosquitto Broker MQTT devices.

**Comment by thierrybla** [comment]
Could you send me a picture? I am really experiencing something else.. are you sure you have exactly this device?
![image](https://user-images.githubusercontent.com/28044044/180050260-642e13e7-1072-4138-98e8-696ab1859b66.png)

**Comment by timnolte** [comment]
Are you actually using Zigbee2MQTT or are you using Zigbee Home Assistant(ZHA). You have a big ZigBee logo not an MQTT logo.
![Selection_145](https://user-images.githubusercontent.com/4312062/180051250-d30dce3c-55cf-4d6a-8ebc-95c15162042d.jpg)
![PXL_20220720_180331431](https://user-images.githubusercontent.com/4312062/180051700-5a3885b1-e336-4710-b5f0-118a51624d2b.jpg)

**Comment by timnolte** [comment]
Here is my device as was recognized in Z2M.
![Selection_146](https://user-images.githubusercontent.com/4312062/180052020-0eb99868-52b6-4e18-87b1-4589e1080482.jpg)

**Comment by antonio1475** [comment]
@timnolte  thank you for the information and photos you provided. Great to know that it works.

@MrSimpa Can you confirm if yours work now? And then close the ticket I suppose.

I ended up buying the Xiaomi BLE ones due to this one not being supported, but my decision could have been different with this information.

**Comment by timnolte** [comment]
I also have a PR open to have the details updated on the [ZigBee Blakadder site](https://zigbee.blakadder.com/Tuya_IH-K009.html).

**Comment by timnolte** [comment]
Once the new release of Z2M comes out, with https://github.com/Koenkk/zigbee-herdsman-converters/pull/4471 , this device will be properly identified and this issue can be closed.

**Comment by gobris** [comment]
I have a pair of  same  device bought from AliExpress. Working fine with temp and humidity but both are lack of battery information.  Battery percentage was visible with zhm and also from smart life application.

![Image](https://github.com/user-attachments/assets/b7b4efb8-300a-4e71-8f97-6f0bee871edd)
