### ISSUE TITLE
[New device support]:TS110E  _TZ3210_pagajpog

### ISSUE THREAD

**Issue by rajil** [Koenkk/zigbee2mqtt#12763]
### Link

https://www.ebay.com/itm/284539508090

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0xa4c1384f0c7f5f2d","nwkAddr":25400,"manufId":4417,"manufName":"_TZ3210_pagajpog","powerSource":"Mains (single phase)","modelId":"TS110E","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[5,4,6,8,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":257,"inClusterList":[5,4,6,8,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1654785083694,"defaultSendRequestWhen":"immediate"}

### Comments

The device looks exactly like https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-2C-LN.html and has the same model number. Unfortunately, it is showing up as not supported.

![image](https://user-images.githubusercontent.com/379266/172877427-7c7b56f8-abef-45c6-80e1-90998729a4d1.png)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by rajil** [comment]
Thanks for making the changes. I can confirm that 'On/Off' works for both the gangs now. However, the brightness slider has no impact.

I tried [this](https://github.com/Koenkk/zigbee2mqtt/issues/11853#issuecomment-1106803448) external convertor, and the brightness slider worked. How the convertor is written for a 1 gang switch only, while mine is a 2 gang switch (hence 2nd switch isnt exposed in the convertor).

I can live without the brightness control as i need the ON/OFF state only. Unfortunately, the brightness is set to a low value as a default and i want it to be set to the highest value if their is no brightness control.

**Comment by rajil** [comment]
I took hints from [Lonsonho](https://github.com/Koenkk/zigbee-herdsman-converters/commit/22f4e590544d7bf39a95870f81f241d8c05f8d9a#diff-267612a10c7b5615a642f4fe6cd0e24efb82436736e476fb0dba10d2762af0fd) device and modified this [definition](https://github.com/Koenkk/zigbee2mqtt/issues/11853#issuecomment-1106803448) for the two states.
```
const definition = {
  fingerprint: [
      {
          // The model ID from: Device with modelID 'TS0601' is not supported
          // You may need to add \u0000 at the end of the name in some cases
          modelID: 'TS110E',
          // The manufacturer name from: Device with modelID 'TS0601' is not supported.
          manufacturerName: '_TZ3210_pagajpog'
      },
  ],
  model: 'QS-Zigbee-D02-TRIAC-LN', // Vendor model number, look on the device for a model number
  vendor: 'TuYa', // Vendor of the device (only used for documentation and startup logging)
  description: 'TuYa Two Channel Dimmer', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
  fromZigbee: [
    fz.on_off,
    fz.moes_power_on_behavior,
    fzLocal.ts110e_brightness,
    fzLocal.brightness_min,
    fzLocal.brightness_max,
    fzLocal.led_type,
  ],
  toZigbee: [
    tz.on_off,
    tz.moes_power_on_behavior,
    tzLocal.light_onoff_brightness,
    tzLocal.ts110e_brightness_min,
    tzLocal.ts110e_brightness_max,
    tzLocal.ts110e_led_type,
  ],
  exposes: [
    e.light_brightness().withEndpoint('l1').setAccess('brightness', ea.STATE_SET),
    e.light_brightness().withEndpoint('l2').setAccess('brightness', ea.STATE_SET),
    exposes.numeric("brightness_min", ea.ALL),
    exposes.numeric("brightness_max", ea.ALL),
    exposes
      .enum("led_type", ea.ALL, ["led", "incandescent", "halogen"])
      .withDescription("Controls the type led"),
    exposes
      .enum("power_on_behavior", ea.ALL, ["off", "previous", "on"])
      .withDescription("Controls the behaviour when the device is powered on"),
  ],
  meta: {multiEndpoint: true},
  configure: async (device, coordinatorEndpoint, logger) => {
    const endpoint = device.getEndpoint(1);
    await extend
      .light_onoff_brightness()
      .configure(device, coordinatorEndpoint, logger);
    await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, [
      "genOnOff",
      "genLevelCtrl",
    ]);
    await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, [
      "genOnOff",
      "genLevelCtrl",
    ]);
    await reporting.onOff(device.getEndpoint(1));
    await reporting.onOff(device.getEndpoint(2));
  },
  endpoint: (device) => {
       return {l1: 1, l2: 2};
        },
};

module.exports = definition;
```
With this i am able to get brightness and On/Off control for both switches.

**Comment by DesertF0x** [comment]
> The S1physical switch acts weird though. It doesnt tongle the ON/Off state, rather it steps down the brightness. I would rather have it turn off the device instead of modifying the brightness.

This sounds like you use a switch instead of a push button:
> A switch has an "on" and "off" position. A button is a device with a momentary on and off position. The button can be used to send a signal to another device to change it's state from "off" to "on" or the reverse.

**Comment by rajil** [comment]
Thats right i have a rocker switch rather than a push button as my wall switch. Can this device not work with a rocker switch?

**Comment by DesertF0x** [comment]
> Thats right i have a rocker switch rather than a push button as my wall switch. Can this device not work with a rocker switch?
Yes, this devices only needs a short on-off input on the switch input for turning on off. A longer input will do a dim action. For dimming modules it is quite common to use a switch/button which returns to off as soon as you release / do not push it anymore. This is because it is usable for dimming and switching. Most wall switches are replaceable by theses ones which return to off automatically. I have replaced several wall switches for this reason.

**Comment by rajil** [comment]
Unfortunately, the led light which i want turn on and off is not a dimmable kind. So i will need to replace both the wall switch and the led batten. 

Is it possible to make software changes for the smart switch to work with a rocker switch? I dont need the dimming function.

 I am using home assistant here.

**Comment by DesertF0x** [comment]
> Is it possible to make software changes for the smart switch to work with a rocker switch? I dont need the dimming function.

No, it is the internal software of the module, not the smart home software...
