### ISSUE TITLE
[New device support]: KlikAanKlikUit (Trust) ZSDR-850

### ISSUE THREAD

**Issue by Step-han** [Koenkk/zigbee2mqtt#12773]
### Link

https://klikaanklikuit.nl/product/slimme-draadloze-rookmelder/

### Database entry

{"id":59,"type":"EndDevice","ieeeAddr":"0x000d6f001698e4c6","nwkAddr":28028,"manufId":4619,"manufName":"Trust","powerSource":"Battery","modelId":"SmokeSensor-EM","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,1282],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SmokeSensor-EM","manufacturerName":"Trust","powerSource":3,"zclVersion":1,"appVersion":21,"stackVersion":2,"hwVersion":16,"dateCode":"2020.10.14","swBuildId":"1.1.1"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00215ffec5","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00215ffec5","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":21,"stackVersion":2,"hwVersion":16,"dateCode":"2020.10.14","swBuildId":"1.1.1","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1654848967653,"defaultSendRequestWhen":"immediate"}

### Comments

Its paired as a HEIMAN HS3SA:

![image](https://user-images.githubusercontent.com/54219681/173035169-8560644b-194f-4347-8020-6adba57de666.png)

![image](https://user-images.githubusercontent.com/54219681/173035198-450f0d75-2f14-4889-85e5-1e1606ecf8a0.png)

![image](https://user-images.githubusercontent.com/54219681/173035241-ef2f17e1-50f9-4898-a08c-4c7740d384b0.png)

In HomeAssistant:
![image](https://user-images.githubusercontent.com/54219681/173035393-14d0203b-566d-4b0a-9170-3c6f2393fe6e.png)

Its working but i dunno if you want to support it as a ZSDR-850.

If you need something let me know.

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Step-han** [comment]
Thanks!

**Comment by asychev** [comment]
@Koenkk I think it is actually [HEIMAN HS1SA](https://www.zigbee2mqtt.io/devices/HS1SA.html), not [HS3SA](https://www.zigbee2mqtt.io/devices/HS3SA.html), at least visually

**Comment by Koenkk** [comment]
@asychev I don't understand what you mean, it will be recognised as a Trust ZSDR-850 now, not HEIMAN HS1SA

**Comment by asychev** [comment]
@Koenkk Yep, after update to [1.26.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.26.0) it is now properly detected, thanks!

**Comment by osker2k** [comment]
Hi,

Sorry for my bad English.  I bought 5 of these devices and connected them successfully too.  Unfortunately I don't see a way if one triggers the other ones too.  Is it possible that the alarm can also be triggered as an action?

**Comment by lukasmedia** [comment]
I have the same issue as @osker2k
Also the battery level is not showing on the dashboard; only at zigbee devices. How to fix this?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/11347254/e311d70a-40e0-43a8-aa5e-010264236e0f)

Note: the slider above is not working. Smoke detection is.

**Comment by TheoSl93** [comment]
I'mj having the same issue @osker2k, I would like to trigger all the sirens if one of the sensors detects smoke. Is it possible to do it?

**Comment by lukasmedia** [comment]
> I'mj having the same issue @osker2k, I would like to trigger all the sirens if one of the sensors detects smoke. Is it possible to do it?

Hi Theo, no this is not possible with these kind of smoke detectors. These are "1 way" and you (we) need smoke detectors which are bi directional.

**Comment by piwy84** [comment]
Is it worth conneting these kaku smoke detectors via zigbee2mqtt?
Mine are currently  connected with zigbee (sonoff3.0dongle)
Will i have more options if i move them to zigbee2mqtt? (Like triggering the alarms with an automation)
