### ISSUE TITLE
permit_join does not work as expected

### ISSUE THREAD

**Issue by debnetjm** [Koenkk/zigbee2mqtt#12775]
### What happened?

permit_join timer shorter than expected

When you enable permit_join from frontend it is counting down from 4:14.

In logs I can see it sets

Zigbee2MQTT:info  2022-06-10 14:54:36: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"uer2w-3"}'

make sense 254=4m14s

but after 120s on the frontend and in logs I can see z2m goes back to disable_join mode without finishing countdown

`

`

### What did you expect to happen?

revert permit_join after 254s not after 120s

### How to reproduce it (minimal and precise)

set permit_join from frontend and check logs/frontend after 120s

### Zigbee2MQTT version

1.25.2-dev commit: 4f181b0

### Adapter firmware version

20220219

### Adapter

slae.sh

### Debug log

`
Zigbee2MQTT:info  2022-06-10 14:54:36: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-06-10 14:54:36: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"uer2w-3"}'
Zigbee2MQTT:info  2022-06-10 14:56:36: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-10 14:56:36: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
Zigbee2MQTT:info  2022-06-10 14:56:36: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-10 14:56:36: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
Zigbee2MQTT:info  2022-06-10 15:00:13: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-06-10 15:00:13: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"uer2w-4"}'
Zigbee2MQTT:info  2022-06-10 15:02:13: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-10 15:02:13: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
Zigbee2MQTT:info  2022-06-10 15:02:13: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-06-10 15:02:13: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
`

**Comment by Koenkk** [comment]
Can you provide the debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by debnetjm** [comment]
@Koenkk 
[permit_join_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8899903/permit_join_log.txt)

**Comment by Koenkk** [comment]
In your log I see zigbee2mqtt recieves a request to disable the joining so the behaviour is as expected:

```
debug 2022-06-14 14:56:18: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"d1ylf-5","value":true}'
info  2022-06-14 14:56:18: Zigbee: allowing new devices to join.
info  2022-06-14 14:56:18: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"d1ylf-5"}'
...
debug 2022-06-14 14:58:18: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data 'false'
info  2022-06-14 14:58:18: Zigbee: disabling joining new devices.
info  2022-06-14 14:58:18: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
debug 2022-06-14 14:58:18: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data 'false'
info  2022-06-14 14:58:18: Zigbee: disabling joining new devices.
info  2022-06-14 14:58:18: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":false},"status":"ok"}'
```

**Comment by Koenkk** [comment]
@debnetjm a request to disable joining is received after 120 seconds (so the 254 timeout doesn't happen). This request is send via your MQTT server so you should figure out who sends this message (try to stop e.g. all services on your pc except the MQTT server and z2m)

**Comment by debnetjm** [comment]
@Koenkk indeed messages comes from HA but it seems it was configured according to z2m documentation :)

that page shows how to control z2m using HA : https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#controlling-zigbee2mqtt-via-home-assistant

it creates join disable job and timer set to 120s

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

and that caused the issue.

Maybe you should sync the values between z2m and HA setup ?

**Comment by Koenkk** [comment]
Updated the value!

Assuming this can be closed now.
