### ISSUE TITLE
Tuya TS0215A_sos not working

### ISSUE THREAD

**Issue by asekijima** [Koenkk/zigbee2mqtt#12770]
### What happened?

So I added the device. First interview failed, then I was able to add it but it can't seems to work because it does nothing when I press the button.

### What did you expect to happen?

I expected it would identify button press.

### How to reproduce it (minimal and precise)

Press button, nothing happens.

### Zigbee2MQTT version

 1.25.1-1

### Adapter firmware version

20210708

### Adapter

tubesZB

### Debug log

![Captura de Tela 2022-06-09 às 19 37 45](https://user-images.githubusercontent.com/6145390/172956759-888a7576-f3a9-4740-893a-9915cbeb9f31.png)
![Captura de Tela 2022-06-09 às 19 30 24](https://user-images.githubusercontent.com/6145390/172956763-2255aac6-affa-4ba6-8503-70c569d53ac4.png)
![Captura de Tela 2022-06-09 às 19 30 13](https://user-images.githubusercontent.com/6145390/172956767-db9b4750-5c0b-4c71-8503-83f0b3ebc378.png)

**Comment by louismulder** [comment]
see: [https://github.com/Koenkk/zigbee2mqtt/issues/13159]
