### ISSUE TITLE
[New device support]: _TZ3000_cehuw1lw 

### ISSUE THREAD

**Issue by bjornberg** [Koenkk/zigbee2mqtt#12789]
### Link

This is same device...
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f-plug-1

### Database entry

{"id":36,"type":"Router","ieeeAddr":"0xa4c1387b1a40a0b6","nwkAddr":43158,"manufId":4417,"manufName":"_TZ3000_cehuw1lw","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_cehuw1lw","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}},"seMetering":{"attributes":{"currentSummDelivered":[0,0]}},"genOnOff":{"attributes":{"20480":1,"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2387214,"53251":136,"53252":12026,"53253":1508,"53264":0,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1654960323945,"useImplicitCheckin":true}

### Comments

Could somebody try to add this as a new device?

**Comment by Koenkk** [comment]
Already supported in the latest dev (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
