### ISSUE TITLE
Aqara/Xiaomi Magic Cube null values in Home Assistant

### ISSUE THREAD

**Issue by marcor2196** [Koenkk/zigbee2mqtt#12784]
### What happened?

Hi all, i have added a Aqara/Xiaomi Magic Cube device in my Home Assistant zigbee2mqtt integration.
Z2M have successfully interviewed the device but when i perform an action with the cube, the exposed attributes remain null and the "action" attribute is an empty string:

![Schermata 2022-06-11 alle 10 37 48](https://user-images.githubusercontent.com/39311786/173180599-e143ecb9-3d31-485e-aba2-4c869221dee5.png)

I think it's because of this problem that the automations I created don't work in home assistant, every time I do an action with the cube I get an empty string in the linked entity.

I can however see correct data passing through Z2M logs:

`Info 2022-06-11 10:42:22MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"slide","action_angle":null,"action_from_side":null,"action_side":null,"action_to_side":null,"battery":99,"current":0,"device_temperature":24,"linkquality":42,"power":86,"power_outage_count":null,"side":0,"voltage":2985}'
Info 2022-06-11 10:42:22MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"","action_angle":null,"action_from_side":null,"action_side":null,"action_to_side":null,"battery":99,"current":0,"device_temperature":24,"linkquality":42,"power":86,"power_outage_count":null,"side":0,"voltage":2985}'
Info 2022-06-11 10:42:22MQTT publish: topic 'zigbee2mqtt/Magic Cube/action', payload 'slide'
Info 2022-06-11 10:42:38MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"flip90","action_angle":null,"action_from_side":0,"action_side":1,"action_to_side":1,"battery":99,"current":0,"device_temperature":24,"linkquality":75,"power":86,"power_outage_count":null,"side":1,"voltage":2985}'
Info 2022-06-11 10:42:38MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"","action_angle":null,"action_from_side":null,"action_side":null,"action_to_side":null,"battery":99,"current":0,"device_temperature":24,"linkquality":75,"power":86,"power_outage_count":null,"side":1,"voltage":2985}'
Info 2022-06-11 10:42:38MQTT publish: topic 'zigbee2mqtt/Magic Cube/action', payload 'flip90'
Info 2022-06-11 10:42:44MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"flip90","action_angle":null,"action_from_side":1,"action_side":2,"action_to_side":2,"battery":99,"current":0,"device_temperature":24,"linkquality":66,"power":86,"power_outage_count":null,"side":2,"voltage":2985}'
Info 2022-06-11 10:42:44MQTT publish: topic 'zigbee2mqtt/Magic Cube', payload '{"action":"","action_angle":null,"action_from_side":null,"action_side":null,"action_to_side":null,"battery":99,"current":0,"device_temperature":24,"linkquality":66,"power":86,"power_outage_count":null,"side":2,"voltage":2985}'
Info 2022-06-11 10:42:44MQTT publish: topic 'zigbee2mqtt/Magic Cube/action', payload 'flip90'`

I already tried to delete the device and rejoin it on my network.

### What did you expect to happen?

That Z2M expose properly the cube data

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20210708

### Adapter

zStack3x0 (SONOFF Zigbee 3.0 USB Dongle)

**Comment by Koenkk** [comment]
This is expected behaviour: https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty
