### ISSUE TITLE
[New device support]: LEDVANCE AC33897

### ISSUE THREAD

**Issue by kris969** [Koenkk/zigbee2mqtt#12791]
### Link

https://www.ledvance.fr/particuliers/produits/smart-home/lampes-smart-home/smart-zigbee/ampoules-smart-forme-classique-avec-filament-et-technologie-zigbee/lampe-de-forme-flamme-avec-technologie-zigbee-c6387

### Database entry

4058075208421

### Comments

I use a newly purchase LEDVANCE BULB refereed as AC33897 on the box.
It works fine with zb2mqtt except it as been identified as a 4058075208421 model, that is a SMART+ candle E14 dimmable white rather than the model used that is a Smart+ LED classic E27 Zigbee 9W/806lm dimmable white.

I haven't check on dev branch if it as be already solved.

**Comment by Trashwarez** [comment]
Same issue here device still wrongly recognized
