### ISSUE TITLE
[New device support]: KlikAanKlikUit (Trust) ZCO-900

### ISSUE THREAD

**Issue by Step-han** [Koenkk/zigbee2mqtt#12808]
### Link

https://klikaanklikuit.nl/product/slimme-draadloze-koolmonoxidemelder/

### Database entry

{"id":66,"type":"EndDevice","ieeeAddr":"0x000d6f00165ffea0","nwkAddr":54770,"manufId":4619,"manufName":"Trust","powerSource":"Battery","modelId":"COSensor-EM","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"COSensor-EM","manufacturerName":"Trust","powerSource":3,"zclVersion":1,"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2020.10.14","swBuildId":"1.1.1"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002393376e","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002393376e","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":20,"stackVersion":2,"hwVersion":16,"dateCode":"2020.10.14","swBuildId":"1.1.1","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1655115669431,"defaultSendRequestWhen":"immediate"}

### Comments

Its paired as a HEIMAN HS1CA-E:

![image](https://user-images.githubusercontent.com/54219681/173341791-558877f7-3fce-487c-ade5-ed65d50278c5.png)

![image](https://user-images.githubusercontent.com/54219681/173341818-0e802c90-5e48-4e60-b7b6-5999f88f950a.png)

![image](https://user-images.githubusercontent.com/54219681/173341859-c706cb52-5b57-4725-871b-ff5f05f26108.png)

In HA:
![image](https://user-images.githubusercontent.com/54219681/173341934-3dbc7fb3-cc14-4cfb-b72d-5d662e74dde7.png)

If you need something let me know.

**Comment by sjorge** [comment]
It looks to just be a rebrand of the HEIMAN one. Unless it's not working properly, nothing to worry  about.
