### ISSUE TITLE
Tuya TS0215A_sos  SOS Button Not Working

### ISSUE THREAD

**Issue by MaxDucy** [Koenkk/zigbee2mqtt#12819]
### What happened?

Hi,

Recently got Tuya SOS Button. When I paired the button. No action triggered at all. Only link quality got updated.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Debug log

Zigbee2MQTT:info  2022-06-14 13:16:10: Device '0x0c4314fffe03c247' joined
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffe03c247","ieee_address":"0x0c4314fffe03c247"},"type":"device_joined"}'
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'homeassistant/sensor/0x0c4314fffe03c247/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0c4314fffe03c247/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe03c247"],"manufacturer":"TuYa","model":"SOS button (TS0215A_sos)","name":"0x0c4314fffe03c247"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x0c4314fffe03c247","name":"0x0c4314fffe03c247 battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x0c4314fffe03c247","unique_id":"0x0c4314fffe03c247_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'homeassistant/sensor/0x0c4314fffe03c247/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0c4314fffe03c247/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe03c247"],"manufacturer":"TuYa","model":"SOS button (TS0215A_sos)","name":"0x0c4314fffe03c247"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/0x0c4314fffe03c247","name":"0x0c4314fffe03c247 action","state_topic":"zigbee2mqtt/0x0c4314fffe03c247","unique_id":"0x0c4314fffe03c247_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'homeassistant/sensor/0x0c4314fffe03c247/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0c4314fffe03c247/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0c4314fffe03c247"],"manufacturer":"TuYa","model":"SOS button (TS0215A_sos)","name":"0x0c4314fffe03c247"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x0c4314fffe03c247","name":"0x0c4314fffe03c247 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x0c4314fffe03c247","unique_id":"0x0c4314fffe03c247_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2022-06-14 13:16:10: Starting interview of '0x0c4314fffe03c247'
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffe03c247","ieee_address":"0x0c4314fffe03c247","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2022-06-14 13:16:10: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffe03c247","ieee_address":"0x0c4314fffe03c247"},"type":"device_announce"}'
Zigbee2MQTT:info  2022-06-14 13:16:17: Successfully interviewed '0x0c4314fffe03c247', device has successfully been paired
Zigbee2MQTT:info  2022-06-14 13:16:17: Device '0x0c4314fffe03c247' is supported, identified as: TuYa SOS button (TS0215A_sos)
Zigbee2MQTT:info  2022-06-14 13:16:17: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"SOS button","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["emergency"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0215A_sos","options":[],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0x0c4314fffe03c247","ieee_address":"0x0c4314fffe03c247","status":"successful","supported":true},"type":"device_interview"}'

**Comment by louismulder** [comment]
See : [https://github.com/Koenkk/zigbee2mqtt/issues/13159]
