### ISSUE TITLE
BHT-002-GCLZB Thermostat showing wrong local temperature. Divided by 10

### ISSUE THREAD

**Issue by chrisazzopardi** [Koenkk/zigbee2mqtt#12811]
### What happened?

{
    "child_lock": null,
    "current_heating_setpoint": 19,
    "linkquality": 116,
    **"local_temperature": 2.4,**
    "local_temperature_calibration": null,
    "max_temperature": 35,
    "preset": "hold",
    "preset_mode": "hold",
    "sensor": "OU",
    "system_mode": "heat",
    "deadzone_temperature": null,
    "max_temperature_limit": null,
    "running_state": null
}

### What did you expect to happen?

Temperature should be 24 and not 2.4

### Zigbee2MQTT version

1.25.0-dev commit: 47ed86d

### Adapter firmware version

20211217

### Adapter

 zStack3x0

**Comment by chrisazzopardi** [comment]
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE200_ztvwu4nk
Description: Moes BHT series Thermostat
Manufacturer: [Moes](https://www.zigbee2mqtt.io/supported-devices/#v=Moes)
Model: [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb)

**Comment by Koenkk** [comment]
Should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by chrisazzopardi** [comment]
Confirmed fixed
