### ISSUE TITLE
[New device support]: tuya curtains

### ISSUE THREAD

**Issue by MihVS** [Koenkk/zigbee2mqtt#12815]
### Link

https://a.aliexpress.com/_A0JXeH

### Database entry

{"id":20,"type":"Router","ieeeAddr":"0xa4c13834a015d6ed","nwkAddr":25858,"manufId":4417,"manufName":"_TZE200_r0jdjrvi","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_r0jdjrvi","powerSource":1,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1655150617744}

### Comments

I bought such an engine for tuya curtains. It is in the list of supported devices, but I get a message when connecting: "A device with the model ID 'TS0601' is not supported."

**Comment by nurikk** [comment]
Hey, this device is supported by [zhc](https://github.com/Koenkk/zigbee-herdsman-converters/blob/bc3f57ac7c8613ec3fa04c7bce863a86be75456b/devices/tuya.js#L1266)  

can you try to update to the latest release version. If it doesn’t work, then try to switch to latest dev branch
