### ISSUE TITLE
TuYa PJ-ZGD01 Garage door opener trigger doesn't toggle

### ISSUE THREAD

**Issue by mcruscher** [Koenkk/zigbee2mqtt#12823]
### What happened?

When pressing the trigger in Zigbee2MQTT it doesn't toggle

### What did you expect to happen?

The trigger should turn back to its original state

### How to reproduce it (minimal and precise)

Just press the trigger switch.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20201127

### Adapter

zStack12

**Comment by initd0** [comment]
Same issue here after having just bought the Tuya PJ-ZGD01

Zigbee2MQTT version
1.25.0-1

Adapter & firmware version
CC2652R_coordinator_20210708

Basically, the toggle-on switch does nothing, if you toggle it back only then it will *click*, then to activate the garage door again you need to toggle it twice again for it to activate/click.   Seems there's a double toggle issue, of which the first toggle does nothing.

Also, i am getting a specific error in the logs which i am not sure if it has anything to do with it:
```
2022-06-17 01:25:05 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_binary_sensor_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'device': {'identifiers': ['zigbee2mqtt_0xa7c1381aa79d04ef'], 'manufacturer': 'TuYa', 'model': 'Garage door opener (PJ-ZGD01)', 'name': 'Garage Roller Door'}, 'device_class': 'garage', 'json_attributes_topic': 'zigbee2mqtt/Garage Roller Door', 'name': 'Garage Roller Door garage door contact', 'payload_off': False, 'payload_on': True, 'state_topic': 'zigbee2mqtt/Garage Roller Door', 'unique_id': '0xa7c1381aa79d04ef_garage_door_contact_zigbee2mqtt', 'value_template': '{{ value_json.garage_door_contact }}', 'platform': 'mqtt'},)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 333, in async_discover
config = schema(discovery_payload)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected BinarySensorDeviceClass or one of 'battery', 'battery_charging', 'carbon_monoxide', 'cold', 'connectivity', 'door', 'garage_door', 'gas', 'heat', 'light', 'lock', 'moisture', 'motion', 'moving', 'occupancy', 'opening', 'plug', 'power', 'presence', 'problem', 'running', 'safety', 'smoke', 'sound', 'tamper', 'update', 'vibration', 'window' for dictionary value @ data['device_class']
```
@Koenkk

**Comment by initd0** [comment]
There is no issue on my end, it turns out i had to keep the contact sensor connected and (closed/open) to have the relay trigger correctly.  My issue is probably unrelated to the OP's issue above.

**Comment by alexeiw123** [comment]
I'm seeing this as well. Zigbee2MQTT shows trigger as a switch, however true-state does nothing and false-state triggers a momentary close of contact. The ideal would be for this to be a push button action for the false-state.

![image](https://user-images.githubusercontent.com/77809797/176584450-cd42ec0e-fdc4-4fb6-8205-fc30d99df282.png)

**Comment by garanda21** [comment]
> I'm seeing this as well. Zigbee2MQTT shows trigger as a switch, however true-state does nothing and false-state triggers a momentary close of contact. The ideal would be for this to be a push button action for the false-state.
> 
> edit: it seems the reverse is true when the closed sensor is true.
> 
> ![image](https://user-images.githubusercontent.com/77809797/176584450-cd42ec0e-fdc4-4fb6-8205-fc30d99df282.png)

I have this exact same behaviour, only OFF position triggers the door, I don't want to use the contact sensor, I have my own sonoff sensor. Exists any workaround to make it work properly ?

**Comment by Pavel-Demidyuk** [comment]
The issue is actual for me as well..

**Comment by TRIROG** [comment]
It’s a tricky one: seems relay teiggering is codependant with contact sensor state.
If contact state is false, then sending command false will activate relay.
If contact state is true, then sending command true will activate the relay.

**Comment by alexeiw123** [comment]
> It’s a tricky one: seems relay teiggering is codependant with contact sensor state. If contact state is false, then sending command false will activate relay. If contact state is true, then sending command true will activate the relay.

It seems odd when you first interact with it, but it works fine once you add it in to the cover integration.

```
cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        unique_id: garage_door_cover
        value_template: >-
          {% if is_state('binary_sensor.garage_door_garage_door_contact', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        open_cover:
          service: switch.turn_on
          target:
            entity_id: switch.garage_door_trigger
        close_cover:
          service: switch.turn_off
          target:
            entity_id: switch.garage_door_trigger
        stop_cover:
          service: switch.turn_off
          target:
            entity_id: switch.garage_door_trigger
```

**Comment by MardariG** [comment]
I got same issue. From what I understood this is dependent on the board door is using. My board for example is expecting this trigger to happen under a second. So for it to work the relay must really fast become ON and OF. Currently when I trigger it, it becomes ON then waits a few seconds, then becomes OFF, and my board do not react to this at all. Not sure if this can be fixed on zigbee2mqtt side or at firmware level though. It feels like there should be a settings for this.
