### ISSUE TITLE
Zigbee CC2531 4dBm Wireless Transceiver E18-2G4U04B ?

### ISSUE THREAD

**Issue by tradenet** [Koenkk/zigbee2mqtt#1283]
Has anyone tried this device?
[https://www.aliexpress.com/i/32973371661.html?spm=2114.12057483.0.0.3c7451efLVrfMq](https://www.aliexpress.com/i/32973371661.html?spm=2114.12057483.0.0.3c7451efLVrfMq)

User manual here:
[http://www.ebyte.com/en/downpdf.aspx?id=523](http://www.ebyte.com/en/downpdf.aspx?id=523)

I haven't seen any feedback on this device that I can find.
200 m operating distance is an interesting spec.

**Comment by h4nc** [comment]
I mean both links here:

Both of your links go here https://github.com/Koenkk/zigbee2mqtt/issues/url

**Comment by james-fry** [comment]
It seems to have no programming header

**Comment by james-fry** [comment]
OK it does have a header, but you'd need to solder or use pogo pins to program it from the cc debugger.
IMO go for the old style green pcb ones unless you are ok with the programming connections.

**Comment by tradenet** [comment]
> I mean both links here:
> 
> Both of your links go here https://github.com/Koenkk/zigbee2mqtt/issues/url

Yeah, I think I fixed that. It's githubs weird URL formatting.

**Comment by tradenet** [comment]
> OK it does have a header, but you'd need to solder or use pogo pins to program it from the cc debugger.
> IMO go for the old style green pcb ones unless you are ok with the programming connections.

Well, what's interesting to me is it's 200m operating distance. Which the green pcb's seem lacking.

**Comment by matejzero** [comment]
The antenna looks the same (is the same), so I doubt it will have a better range then the green PCB. But I could be mistaken.

**Comment by h4nc** [comment]
Yeah may the CC2531 also has a 200m range with perfect conditions and without walls. 

Antenna looks the same as @matejzero said

**Comment by fred-c1** [comment]
"200m" or even "200 meters" means nothing (beside "we want your money")
No standard "CC debugger" connector
PCB/board antenna layout seems poor (/ not as good as Texas Instruments reference design)
Conclusion = avoid E18-2G4U04B

**Comment by mabusdogma** [comment]
Actually is as easy to flash as "normal" CC2531 ones
You need a CC debugger and 5 DuPont male-to-female cables

Method is described here:
https://community.home-assistant.io/t/flash-zigbee-e18-2g4u04b-without-soldering-zigbee2mqtt/253953
