### ISSUE TITLE
[New device support]: IKEA ”LED2003G10" made by IKEA sold in Japan is not recognized

### ISSUE THREAD

**Issue by nbc8915** [Koenkk/zigbee2mqtt#12830]
### Link

https://www.ikea.com/jp/ja/p/tradfri-led-bulb-e26-1160-lumen-wireless-dimmable-white-spectrum-globe-opal-white-00489750/

### Database entry

{"data":{"friendly_name":"0x94deb8fffea099b5","ieee_address":"0x94deb8fffea099b5"},"type":"device_announce"}

### Comments

The zigbeeModelname of the IKEA LED2003G10 sold in Japan is not "TRADFRIbulbE27WSglobeopal1055lm" but "TRADFRIbulbE26WSglobeopal1160lm", so the device will not work.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
