### ISSUE TITLE
Skydance Tuya WZ5 LED 5 in 1 - No converter available for 'get' 'color' ()

### ISSUE THREAD

**Issue by jmbinette** [Koenkk/zigbee2mqtt#12837]
### What happened?

When trying to get the color status, we get the error :
No converter available for 'get' 'color' ()

I have no experience in writing converters. 
@kirovilya could you help ?

### What did you expect to happen?

Get the actual color status of the controller (Could be changed via a RF Remote)

### How to reproduce it (minimal and precise)

In the EXPOSE section of the device, click the refresh button on the left of colors

### Zigbee2MQTT version

1.25.2-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0

**Comment by jmbinette** [comment]
bump anyone ?

**Comment by Sangoku** [comment]
bumpt again?

**Comment by pLavrenov** [comment]
up

**Comment by Koenkk** [comment]
TuYa device don't support reading attributes, that's why you get the error.

**Comment by pLavrenov** [comment]
> Устройство TuYa не поддерживает чтение атрибутов, поэтому вы получаете сообщение об ошибке.

What needs to be done to send parameters “h” and “s” to the mqtt /set channel. Now "hex" is sent and it doesn't work on the device. I rewrote the converter but it seems to me that this is not a very universal approach

[https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/skydance.ts](url)
