### ISSUE TITLE
Aqara water leak sensor returns `null` instead of `false`

### ISSUE THREAD

**Issue by lukepighetti** [Koenkk/zigbee2mqtt#12858]
### What happened?

- Paired Aqara water leak sensor
- `water_leak` was `null` until I exposed it to water, where it displayed `true`, and then when dried displayed `false`

```
{
    "battery": 100,
    "battery_low": false,
    "device_temperature": 26,
    "linkquality": 21,
    "power_outage_count": null,
    "voltage": 3055,
    "water_leak": null,
    "tamper": false
}
```

### What did you expect to happen?

I expected the `water_leak` value to be `false` when it was first powered up

**Comment by Koenkk** [comment]
This is expected since we don't know the state of this sensor when you initially pair it. We need to wait until it reports it status at least once.
