### ISSUE TITLE
Device Remove Not working after Failed to remove device

### ISSUE THREAD

**Issue by King-anderson** [Koenkk/zigbee2mqtt#12867]
### What happened?

Hi
I received below log from zigbee2mqtt when I want to remove a battery powered device:

![Untitled](https://user-images.githubusercontent.com/22853649/174616939-d2db01c8-768c-430a-a5a4-9f30e317ae1f.png)

but after this error, when I send remove command I don't see its log in zigbee2mqtt log. it seems that the topic 
`zigbee2mqtt/bridge/request/device/remove` topic is unsubscribed!

### What did you expect to happen?

I what to see remove command log on zigbee2mqttt log output.

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20211115

### Adapter

CC2530

**Comment by benjR** [comment]
@msadeghz Not an expert, but I think you have to force remove the device now

**Comment by msadeghz** [comment]
when you publish a command, you should see a log says a command received.
but after seeing this failure log, I don't see any log about receiving remove command.

**Comment by Koenkk** [comment]
Can you provide the debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by msadeghz** [comment]
Hi @Koenkk 
you can see debug log in below image:

![Untitled](https://user-images.githubusercontent.com/22853649/174614959-1e764df1-0593-494d-bf18-f4233eab3a6a.png)

after I send "remove command" and it fails, when I send "remove command" again, I didn't see any log indicating an MQTT command received. it seems that the remove command topic is unsubscribed.

**Comment by Koenkk** [comment]
I see the issue, but I cannot explain it yet. can you provide your `configuration.yaml`?

**Comment by msadeghz** [comment]
> I see the issue, but I cannot explain it yet. can you provide your `configuration.yaml`?

thank you. it's relevant that I get `zigbee-herdsman` error connection with the zigbee adapter (my zigbee adapter is serial CC2530). I have to reprogram CC2530  or reset it to resolve the issue. 

![image](https://user-images.githubusercontent.com/22853649/174824401-0dfca4ba-bc36-439f-9767-e790f03833b3.png)

**Comment by King-anderson** [comment]
@Koenkk 
did you check my logs? is there any bug in zigbee2mqtt?

**Comment by Koenkk** [comment]
Can you make sure this also happens with z2m 1.25.2?

**Comment by King-anderson** [comment]
the issue was in 1.25.1. it is resolved in 1.25.2.
thank you

**Comment by karlhuther** [comment]
I am running 1.35.1 and getting the same error but with with a SONOFF motion sensor. This is happening through the frontend of Z2M. What was changed in the configuration.yaml to make this go away? I am also using a CC2652P for my coordinator.
