### ISSUE TITLE
cache_state - Dont create file of false state is set.

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#1287]
I see that if i set the ``cache_state`` on the configuration.yaml file with ``false`` it doesnt use the cache but create ``state.json`` with ``{}``.

This should be fixed because if this state is configured to be ``false`` it doesn´t should create the empty file.
Maybe also delete them up because it could be give a wrong state on User View Point.

**Comment by Koenkk** [comment]
Fixed!

**Comment by tb-killa** [comment]
Thanks.
