### ISSUE TITLE
Please add a few more models to [Keen Home] @devices.js

### ISSUE THREAD

**Issue by vesomo** [Koenkk/zigbee2mqtt#1288]
// Keen Home
    {
        zigbeeModel: ['SV01-410-MP-1.0', 'SV01-410-MP-1.4', 'SV01-410-MP-1.5', 'SV01-412-MP-1.0', 'SV01-610-MP-1.0', 'SV01-612-MP-1.0'],

Thanks!!!

**Comment by Koenkk** [comment]
done, thanks!
