### ISSUE TITLE
Philips HUE 929003055801 not showing OTA updates

### ISSUE THREAD

**Issue by Klapperman** [Koenkk/zigbee2mqtt#12899]
### What happened?

The Philips HUE 929003055**8**01 doesn't show in the OTA update list, whilst the Philips HUE 929003055**9**01 does. They are seemingly for all intents and purposes the same device so this is strange. 

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20210708

### Adapter

zzh!

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
