### ISSUE TITLE
Pls add TuYa model: TS0215A_sos in fingerprint: modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'

### ISSUE THREAD

**Issue by louismulder** [Koenkk/zigbee2mqtt#12910]
### Link

https://nl.aliexpress.com/item/1005004198981729.html?spm=a2g0o.productlist.0.0.1a481457wBuqWh&algo_pvid=b5856b03-a152-4d77-afdf-5a9cb8f1f2a2&algo_exp_id=b5856b03-a152-4d77-afdf-5a9cb8f1f2a2-1&pdp_ext_f=%7B%22sku_id%22%3A%2212000028353511244%22%7D&pdp_npi=2%40dis%21EUR%21%2118.06%2118.06%21%21%21%21%400b0a050116559201304511937eda98%2112000028353511244%21sea

### Database entry

Device '0x2c1165fffe7bb0d0' with Zigbee model 'TS0215A' and manufacturer name '_TZ3000_tj4pwzzm' is NOT supported

### Comments

Pls add modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'
   
 {
        fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_wr2ucaj9'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'}],
        model: 'TS0215A_sos',
        vendor: 'TuYa',
        description: 'SOS button',
        fromZigbee: [fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['emergency'])],
        toZigbee: [],
    },

**Comment by Koenkk** [comment]
Done!
