### ISSUE TITLE
check battery status for xiaomi devices

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#12922]
### What happened?

all my xiaomi devices are 100% battery

### What did you expect to happen?

the status is wrong. 
for Devs MCCGQ11LM, WSDCGQ01LM, RTCGQ01LM and others

i found this refactoring
https://github.com/Koenkk/zigbee-herdsman-converters/commit/2554e6d1673b4d315f07a1562a7b95d1fe2d05d8

### How to reproduce it (minimal and precise)

trigger manual a Dev WSDCGQ01LM (push the button) and look the battery state

### zigbee-herdsman-converters

.554

### Adapter firmware version

null

### Adapter

sonoff usb stick

**Comment by Koenkk** [comment]
This is being discussed in https://github.com/Koenkk/zigbee2mqtt/issues/8499, please propose a better battery % calculation.
