### ISSUE TITLE
Aqara Water Leak Sensor (SJCGQ11LM) 

### ISSUE THREAD

**Issue by Jens-Wymeersch** [Koenkk/zigbee2mqtt#12924]
### What happened?

In short, I don't get a value for water_leak, battery_low and power_outage_count. 

### What did you expect to happen?

Nothing special happened, just don't get this reading

### How to reproduce it (minimal and precise)

I have 2 devices like this, both have the same problem.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

ZZH!

**Comment by ashokaiyar** [comment]
I have several of these with the same version of zigbee2mqtt (1.25.2) and my coordinator (slaesh's stick) is flashed with the same coordinator version.

The sensors pair and report fine. Here's what the state looks like:

```
{
    "battery": 100,
    "battery_low": false,
    "device_temperature": 26,
    "last_seen": 1656118444933,
    "linkquality": 83,
    "tamper": false,
    "temperature": 26,
    "voltage": 3025,
    "water_leak": false
}
```

**Comment by Jens-Wymeersch** [comment]
I re-paired the sensor and now all got sorted ! Thanks !
