### ISSUE TITLE
[New device support]: IKEA TRADFRIbulbE26WSglobeopal1055lm zigbeemodel

### ISSUE THREAD

**Issue by mixtempo** [Koenkk/zigbee2mqtt#12932]
### Link

https://ikea.com

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0x84ba20fffe3de9d7","nwkAddr":26397,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRIbulbE26WSglobeopal1055lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20201111","swBuildId":"1.0.012","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1656155104626,"defaultSendRequestWhen":"immediate"}

### Comments

plz add TRADFRIbulbE26WSglobeopal1055lm model in LED2003G10.
It is not supported because there is only the E27 model. thanks a lot.

{
        zigbeeModel: ['**TRADFRIbulbE26WSglobeopal1055lm**', 'TRADFRIbulbE27WSglobeopal1055lm', 'TRADFRIbulbE26WSglobeopal1100lm', 'TRADFRIbulbE26WSglobeopal1160lm'],
        model: 'LED2003G10',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E26/27 1100/1055/1160 lumen, dimmable, white spectrum, opal white',
        extend: tradfriExtend.light_onoff_brightness_colortemp(),
    },

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
