### ISSUE TITLE
Temperature and power values stuck after zigbee2mqtt upgrade

### ISSUE THREAD

**Issue by fapgomes** [Koenkk/zigbee2mqtt#12935]
### What happened?

After an upgrade of zigbee2mqtt software, the values for temperature and power of xiaomi devices are stuck.
Attached some examples
![Screenshot_20220625_153010](https://user-images.githubusercontent.com/39247306/175778091-b4f8112f-344b-424a-83a0-1083711fcfa1.png)
![Screenshot_20220625_153049](https://user-images.githubusercontent.com/39247306/175778131-4e11c449-af7f-4efd-988d-e6bf4b71879e.png)
![Screenshot_20220625_153245](https://user-images.githubusercontent.com/39247306/175778188-7ed8d939-cded-4cc4-875d-e88e545983d3.png)
.

### Zigbee2MQTT version

1.25.2 commit: 9b2a9210

### Adapter firmware version

20211116

### Adapter

CC2531

**Comment by ashokaiyar** [comment]
Which Xiaomi devices? Perhaps your observation is related to this change?

https://github.com/Koenkk/zigbee-herdsman-converters/pull/4275

**Comment by fapgomes** [comment]
That I notice, this: https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html#xiaomi-mccgq11lm (on this is the temperature issue)
and this: https://www.zigbee2mqtt.io/devices/SSM-U01.html#xiaomi-ssm-u01 (on this is the power issue)

@ashokaiyar On the temperature, it can be what you write :) Thanks.

On the power value, you have an idea? It can be because I change the coordinator firmware to the routing firmware?

Thanks,

**Comment by ashokaiyar** [comment]
Can you describe the power issue in more detail? What is the message that you expect to see? Are you doing this in node-red? If so, which node-red integration for zigbee2mqtt are you using? Can you use MQTT Explorer (or something similar) to see what values are being sent by z2m to your MQTT daemon?

**Comment by fapgomes** [comment]
Hi,

 I use MQTT Explorer to see the value, and the value is stuck on 5.13W  (and I sure that is not the correct value, when I turn on the electric pump):

![Screenshot_20220625_211812](https://user-images.githubusercontent.com/39247306/175789332-c5f0298a-66ac-43de-ab91-c0c871ea409f.png)
 
On z2m frontend the value is the same that I see in MQTT Explorer, and the same that I've on openhab and grafana.

@ashokaiyar  Based on that, you can help?

Thanks,

**Comment by ashokaiyar** [comment]
There are no recent changes that should affected power reporting. Have you considered resetting and re-pairing the device? It will pair back using its existing Friendly Name and IEEE address.

**Comment by fapgomes** [comment]
Humm, I think with the re-pair it worked!! Thank you very much.
