### ISSUE TITLE
Logging retention policy seems to not work correct

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [Koenkk/zigbee2mqtt#12937]
### What happened?

When checking the logs of Zigbee2Mqtt I observed that the log folder (/config/zigbee2mqtt/log) does contain several subfolders (timestamped), in which there seem to be 1-n files calle log{n}.txt. This ic confirmed by the defaul log configuration.

Logpath: /config/zigbee2mqtt/log/%TIMESTAMP%
Logfile: log.txt

Log rotation is active. 
However how is the rentention policy? How many of these folders and files are created? How big can they get? Not that these files are extremly big on me end, but without a cleanup, I know what happens.

### What did you expect to happen?

I would have expected to be able to configure a retention policy, so that the folders and files are getting cleaned up.
Either by saying to keep only x-days of logs or keep only x-number of logfiles (irregardless of folder structure).

### How to reproduce it (minimal and precise)

Just run the HA addon.

### Zigbee2MQTT version

1.25.2 

### Adapter firmware version

20210708

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by ashokaiyar** [comment]
The dates correspond to when you stopped/re-started zigbee2mqtt. And you can configure log rotation under Settings/Advanced using the zigbee2mqtt GUI on port 8080.
