### ISSUE TITLE
[New device support]: Niko socket outlet 170-34605

### ISSUE THREAD

**Issue by diegomontanaduarte** [Koenkk/zigbee2mqtt#12941]
### Link

https://www.niko.eu/en/article/170-34605

### Database entry

{"id":14,"type":"Router","ieeeAddr":"0x14b457fffe21e0b6","nwkAddr":36812,"manufId":4703,"manufName":"NIKO NV","powerSource":"Mains (single phase)","modelId":"Connected socket outlet","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,2821,64512],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Connected socket outlet","manufacturerName":"NIKO NV","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":6,"hwVersion":5,"dateCode":"20191128","swBuildId":"313-286-00"}},"haElectricalMeasurement":{"attributes":{"acPowerMultiplier":1123,"acPowerDivisor":10000,"acCurrentDivisor":1000,"acVoltageMultiplier":1,"acVoltageDivisor":10,"acCurrentMultiplier":1,"rmsVoltage":2287,"rmsCurrent":435,"activePower":596}},"seMetering":{"attributes":{"multiplier":1,"divisor":10000,"currentSummDelivered":[0,2763]}},"manuSpecificPhilips":{"attributes":{"outletChildLock":1,"outletLedState":1}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff06cfc5","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff06cfc5","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff06cfc5","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":1000},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":100},{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":100},{"cluster":1794,"attrId":0,"minRepIntval":60,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":6,"hwVersion":5,"dateCode":"20191128","swBuildId":"313-286-00","zclVersion":3,"interviewCompleted":true,"meta":{"configured":104667205},"lastSeen":1656187979913,"defaultSendRequestWhen":"immediate"}

### Comments

Device supported and working fine but it's showing a different model (170-33505) that doesn't match with currently device being used 

![image](https://user-images.githubusercontent.com/2682853/175790710-e26fd509-6beb-462a-971e-4ed0a8540e34.png)

**Comment by Koenkk** [comment]
Seems both models user the same zigbee model id (making it impossible to distinguish them from each other). I've renamed to model to `170-33505/170-34605`

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
