### ISSUE TITLE
[New device support]: LIDL Livarno LED Aussenstrahler

### ISSUE THREAD

**Issue by DrMucki** [Koenkk/zigbee2mqtt#12940]
### Link

https://www.lidl.de/p/livarno-home-aussenstrahler-mit-lichtfarbensteuerung-und-rgb-zigbee-smart-home/p100341862

### Database entry

{"id":21,"type":"Router","ieeeAddr":"0x04cd15fffe5d4a99","nwkAddr":51439,"manufId":4098,"manufName":"_TZ3210_umi6vbsz","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_umi6vbsz","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorTemperature":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1656184831397,"defaultSendRequestWhen":"immediate"}

### Comments

Desktop app works, i used a bulb converter, but it does not work with node red via mqtt

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0505B'],
    model: 'LED Aussenstrahler',
    vendor: 'LIDL-Livarno',
    description: 'RGB LED Aussenstrahler!',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

### Supported color modes

onoff_brightness_colortemp_color({colorTempRange: [153, 454]})

**Comment by Koenkk** [comment]
This device is already supported in the latest dev (and next release on 1 jul)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
