### ISSUE TITLE
dependency issue with cc-znp

### ISSUE THREAD

**Issue by webster42** [Koenkk/zigbee2mqtt#1295]
@Koenkk 
While trying to build a nix package for zigbee2mqtt (using node2nix) I stumbled across an issue with cc-znp.
When last updating the serialport version used by cc-znp you forgot to update npm-shrinkwrap.json, see here: https://github.com/Koenkk/cc-znp/commit/7a57508a2a462808e34f2c9d6fc7b7a98040781d
It seems this leads to node2nix using the 2.0.5 version of the serial port bindings.
Would be nice if you could fix this.

Thanks

**Comment by Koenkk** [comment]
thanks, done!

**Comment by webster42** [comment]
@Koenkk 
Sorry for bugging again, but I just noticed, that the npm-shrinkwrap of the zigbee2mqtt repo is affected, too.
It also references the old serial port bindings.

**Comment by Koenkk** [comment]
I'm not sure how to fix that/what is wrong there, the npm-shrinkwrap.json was regenerated afterwards.

**Comment by webster42** [comment]
I just realized it's a bit more complicated.
The problem is, the zigbee2mqtt package.json references a specific commit of zigbee-shepherd, which itself references a specific commit of cc-znp.
So the solution is to first update the commit hash of cc-znp in the zigbee-shepherd package.json and update the shrinkwrap file there.
The second step would be to update the zigbee-shepherd version in the zigbee2mqtt package.json with the new commit hash and then update the shrinkwrap file there.

**Comment by webster42** [comment]
Just saw that you already updated the commit hash of cc-znp in the package.json of zigbee-shepherd.
So the only thing left to do is update the zigbee-shepherd version in the zigbee2mqtt repo.

**Comment by Koenkk** [comment]
I already did that in: https://github.com/Koenkk/zigbee2mqtt/commit/24cf72f166f089eb8c8165e8d26e0f377e722cf8

**Comment by webster42** [comment]
Thanks, I looked at the wrong branch. 👍

**Comment by Koenkk** [comment]
good! Is everything ok now?

**Comment by webster42** [comment]
Yes, no more segfaults.
