### ISSUE TITLE
LoraTap Tuya ZigBee 3.0 EU Double Curtain Switch - incorrect identification

### ISSUE THREAD

**Issue by suchecki83** [Koenkk/zigbee2mqtt#12968]
### What happened?

I have a problem with the LoraTap Tuya ZigBee 3.0 EU Double Curtain Switch https://www.aliexpress.com/item/1005003308586552.html - the device is recognized as a single TS130F, 

### What did you expect to happen?

It should be recognized as a TS130F_dual double switch.

### Zigbee2MQTT version

1.25.2 

### Adapter firmware version

20210319

### Adapter

 zStack3x0

**Comment by Koenkk** [comment]
Please provide the data/database.db entry of this device.

**Comment by suchecki83** [comment]
Thank you, it works!
