### ISSUE TITLE
Sengled E1E-G7F binds not working with group of Philips Hue 5996511U5 bulbs

### ISSUE THREAD

**Issue by JackPala** [Koenkk/zigbee2mqtt#12978]
### What happened?

Tried to bind a Sengled E1E-G7F to the Philips Hue 5996511U5 bulbs (group of 3 bulbs). When pressing the buttons on the switch, the button presses appear in the logs but the presses have no effect on the bulbs.

![Oops](https://user-images.githubusercontent.com/2214871/176338335-bfc8ecf9-90e4-4a07-b798-a084a817a783.png)

### What did you expect to happen?

The bulbs turn and off and dim in according with the buttons I press

### Zigbee2MQTT version

 1.25.2 commit: 3c5854fa

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus zStack3x0

**Comment by Koenkk** [comment]
The `E1E-G7F` sends non standard zigbee commands (based on the [custom converter](https://github.com/Koenkk/zigbee-herdsman-converters/blob/b401692532ae75538974621c1fb898c24e793b85/converters/fromZigbee.js#L5136)) which the Hue bulbs don't understand.

This cannot be fixed from z2m.
