### ISSUE TITLE
Question for owner of Hue outdoor motion sensor

### ISSUE THREAD

**Issue by way2many** [Koenkk/zigbee2mqtt#1297]
Hi all,

quick question that I couldn't find anywhere. Is the distance on the Hue outdoor motion adjustable?
From the docs it's 12 meters which is way too far for my use case as from my home to the street I have 6 meters. Wouldn't want passersby and cars being detected as a movement.
Or should I calculate based on the angle of detection at which height I should place it ?

Thanks.

**Comment by jonnycastaway** [comment]
No, actually you can not adjust the distance

**Comment by way2many** [comment]
Great thank you very much for the answer. I was afraid of this.
