### ISSUE TITLE
[New device support]: Add new manufacture for TS0505B

### ISSUE THREAD

**Issue by loy1020** [Koenkk/zigbee2mqtt#12974]
### Link

https://item.taobao.com/item.htm?spm=a230r.1.14.22.25a54edfDnQCcV&id=637472445075&ns=1&abbucket=20#detail

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0xa4c1384f24e62858","nwkAddr":12410,"manufId":4417,"manufName":"_TZ3210_cuqkfz2q","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_cuqkfz2q","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":0,"currentY":0,"currentHue":0,"currentSaturation":254,"colorTemperature":153}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1656424916669,"defaultSendRequestWhen":"immediate"}

### Comments

Works perfect.

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
