### ISSUE TITLE
Router unavailability not send to Mqtt

### ISSUE THREAD

**Issue by PuckStar** [Koenkk/zigbee2mqtt#1298]
When the router is unavailable it's not broadcasted to the Mqtt broker.
I only see this in the log:

3/16/2019, 11:12:10 PM - debug: Check online Router 1 0x00124b001936b47c
3/16/2019, 11:12:20 PM - debug: Failed to ping 0x00124b001936b47c

So then Home Assistant still thinks the Router is connected (active/available) while in fact it's not.

![image](https://user-images.githubusercontent.com/19824801/54710574-46db0c80-4b48-11e9-8977-7e0d1a6ed0b3.png)

![image](https://user-images.githubusercontent.com/19824801/54710593-5195a180-4b48-11e9-85d6-314432ace40b.png)

**Comment by Koenkk** [comment]
This will only be done when the availability feature is enabled: https://github.com/Koenkk/zigbee2mqtt/issues/775, do you have this enabled?
