### ISSUE TITLE
No Update Firmware Error

### ISSUE THREAD

**Issue by maxbec** [Koenkk/zigbee2mqtt#12997]
### What happened?

Zigbee2Mqtt is showing that there is no update available for a Philipps Hue Bar. For the other with the exact same Product ID there was a succesful update.
![Screenshot 2022-06-30 at 15 59 32](https://user-images.githubusercontent.com/8254514/176696590-1dd6552c-8691-445e-9253-5ecb9bb00334.png)

### What did you expect to happen?

Showing that there is a new update available.

### How to reproduce it (minimal and precise)

No Idea.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Plus Dongle

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9020401/log.txt)

**Comment by maxbec** [comment]
Any idea?

**Comment by Koenkk** [comment]
Maybe the cached info at the z2m side is incorrect. Update it by doing a read on the following attributes via the z2m frontend and restart z2m:

<img width="1067" alt="Screenshot 2022-07-11 at 17 35 45" src="https://user-images.githubusercontent.com/2892853/178301872-8f05f85e-1fee-498e-9ffd-02176c152309.png">

**Comment by maxbec** [comment]
> Maybe the cached info at the z2m side is incorrect. Update it by doing a read on the following attributes via the z2m frontend and restart z2m:
> 
> <img alt="Screenshot 2022-07-11 at 17 35 45" width="1067" src="https://user-images.githubusercontent.com/2892853/178301872-8f05f85e-1fee-498e-9ffd-02176c152309.png">

Done! But it still shows the old version:
![Screenshot 2022-08-12 at 08 36 20](https://user-images.githubusercontent.com/8254514/184298098-b63aff33-0292-46dd-b5bc-f6632cee209f.png)

Three same bulbs with everyone on a different version. Check for update brings no update!
![Screenshot 2022-08-12 at 08 36 51](https://user-images.githubusercontent.com/8254514/184298162-bc361929-9222-4879-a0e1-609013955bd9.png)

**Comment by maxbec** [comment]
Can you give an update here?
