### ISSUE TITLE
Hassio doesn’t connect to zigbee2mqtt

### ISSUE THREAD

**Issue by michaeldbr** [Koenkk/zigbee2mqtt#1299]
Hi Guys, I migrated Hassio to a Synology 218+ with VMM. The weird thing is, Zigbee2MQTT is working completely. But I got the idea Hassio doesn’t read the status of the add-on and Zigbee devices...  I have some Xiaomi devices who send info. Temp, humidity and movement. I can see all this info in the add-on but Hassio can’t read.. sensors are all unknown.. also the bridge state from the Danielwelch add on is unknown...

Does anybody has an answer?? Thanks guys

**Comment by michaeldbr** [comment]
Also there are no error logs in Hassio or the add-on.

**Comment by hgelpke** [comment]
Do you have autodiscovery on in your mqtt integration?

Do you have homeassitant: true in your Z2M configuration.yaml?

**Comment by olegbuk** [comment]
Having similar issues with my setup. Any help would be greatly appreciated.

**Comment by hgelpke** [comment]
Can you be more specific on the problem?

I wen through a lot of potential issues so I think I can help but need more
details on what you've tried.

Did it work before?

Are you ale to pull any info from the logs of Zigbee2MQTT or MQTT itsself?

Does HA recognize other MQTT devices?

**Comment by Podds84** [comment]
This worked for me:
mqtt:
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

Should be part of documentation... took me hours to find..
