### ISSUE TITLE
Develco SMSZB-120 sensor "test" not working with Sonoff Zigbee 3.0 dongle

### ISSUE THREAD

**Issue by BoneheadFraggle** [Koenkk/zigbee2mqtt#13007]
### What happened?

I have four Develco SMSZB-120 smoke sensors. 
The devices are included without problem. All expected sensors are exposed. 
temperature, battery, smoke tested and works fine. 
Sensor test does not report at all.
The devices were previously paired with Conbee I with deCONZ, then test sensor worked.

I can't test battery_low, max_duration, alarm, reliability, fault, linkquality

### What did you expect to happen?

That test sensor should change state when test button is pressed :-)

### Zigbee2MQTT version

1.25.2-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0

### Debug log

Can't see anything in the logs. No entries when I push the test buttons.

**Comment by squadramunter** [comment]
On the cluster page you can see all the function for each Endpoint

**Comment by BoneheadFraggle** [comment]
@squadramunter I think I have tried every combination I can think of, but I am probably doing something wrong.
Do you have the same type and does it report correctly when you press the test button?

**Comment by BoneheadFraggle** [comment]
Actually I just found out that it works - but I need to press the test button for 8-10 seconds. In deConz it was immediate.
