### ISSUE TITLE
[Feature request]: Automated backups with retention

### ISSUE THREAD

**Issue by onedr0p** [Koenkk/zigbee2mqtt#13017]
### Is your feature request related to a problem? Please describe

Would it be possible extend the current implementation to have backups automated and stored on disk? 

### Describe the solution you'd like

The below pseudo-config would backup once a day and only retain 7 days of backups and the zips would be stored in the /config/backups directory. This would be very helpful at looking at configuration drift and correcting mistakes by looking at old configs. Thanks!

```yaml
backup_interval: 1d
backup_retain: 7d
backup_path: /config/backups
```

This would be especially help in a container install of z2m where automating this outside the z2m container is more difficult.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by Hedda** [comment]
+1
