### ISSUE TITLE
postponed data with debounce option

### ISSUE THREAD

**Issue by King-anderson** [Koenkk/zigbee2mqtt#13032]
### What happened?

Hi Friends,
I have enabled the "debounce" option for my Xiaomi door sensor. I see the published data after enabling this option is reverted. when I open the door, z2m publishes close status. It seems the data is postponed by single event.
how can I handle this issue?

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20211115

### Adapter

CC2530

**Comment by McGiverGim** [comment]
A debug log can help with this.

**Comment by King-anderson** [comment]
actually, the device sends its battery status each 1 hr. but I want to be sent one time in a day. howere, as you said, the debounce package sends previous data.
is there any other solution to satisfy my requirement?
