### ISSUE TITLE
GLEDOPTO GL-C-006P is seen as GL-D-005P

### ISSUE THREAD

**Issue by Loic691** [Koenkk/zigbee2mqtt#13038]
### What happened?

The GL-C-006P is seen as DL-D-005P which is a RGB LED instead of a cold/warm light.
The consequence is the settings of color temperature of the controleur not working property.
Tested on other one device which is correct.

### What did you expect to happen?

I expected that the device will be correctly seen with the good refID

### How to reproduce it (minimal and precise)

Just include the controler to see the modelID is not correct.
An other same device don't have this issue...

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

0x26720700

### Adapter

Conbee2

**Comment by Loic691** [comment]
So a strange update.
I tryed another GL-C-006P wich is seen correctly and worky perfected.
So the only problem is my old device GL-C-006P is not seen correctly.
I tryed to reset it and reinclude but it the same. I think ther is a firmware problem on the device...
I updated the issue

**Comment by Koenkk** [comment]
This is an issue with the firmware of the device, stopping z2m and manually changing the modelID in the data/database.db is a workaround.
