### ISSUE TITLE
设备已经识别，但是提示设备不支持

### ISSUE THREAD

**Issue by songtiantian2022** [Koenkk/zigbee2mqtt#13058]
### Link

Konke温湿度传感器

### Database entry

{"id":3,"type":"EndDevice","ieeeAddr":"0x84fd27fffe98fe64","nwkAddr":7441,"manufId":4712,"manufName":"Konke","powerSource":"Battery","modelId":"3AFE090103021000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,1,3,1024,1026,1029,2821,64704],"outClusterList":[25],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2840}},"msRelativeHumidity":{"attributes":{"measuredValue":5570}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":17324}},"genBasic":{"attributes":{"modelId":"3AFE090103021000","manufacturerName":"Konke","powerSource":3,"zclVersion":3,"appVersion":9,"stackVersion":0,"hwVersion":1,"dateCode":"20210909","swBuildId":"01-2019120401"}},"genPowerCfg":{"attributes":{"batteryVoltage":29,"batteryPercentageRemaining":184}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":9,"stackVersion":0,"hwVersion":1,"dateCode":"20210909","swBuildId":"01-2019120401","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1657098468898,"defaultSendRequestWhen":"immediate"}

### Comments

Warning 2022-07-06 17:04:48Device '0x84fd27fffe98fe64' left the networkkkkkkkkkkkkk
Info 2022-07-06 17:04:48MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_leave"}'
Info 2022-07-06 17:04:48MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_removed"}'
Info 2022-07-06 17:05:37Device '0x84fd27fffe98fe64' joined88888888888
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_joined"}'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_connected"}'
Info 2022-07-06 17:05:37Starting interview of '0x84fd27fffe98fe64'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"started"},"type":"device_interview"}'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"pairing"}'
Debug 2022-07-06 17:05:44Device '0x84fd27fffe98fe64' announced itself
Info 2022-07-06 17:05:44MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_announce"}'
Info 2022-07-06 17:05:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_announced"}'
Debug 2022-07-06 17:06:02Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2790}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:02Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:02Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":5570}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:02Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:13Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:13Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:18Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:18Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:20Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":10414}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:20Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:20Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:20Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:21Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:21Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:23Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:23Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:24Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:24Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:28Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":185,"batteryVoltage":29}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:28Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:29Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":184}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:29Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:03Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2840}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:03Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:09Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Konke"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:09Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:14Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Konke"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:14Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:19Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:19Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:21Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:21Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:25Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:25Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:27Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:27Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:29Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"appVersion":9}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:29Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:31Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"appVersion":9}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:31Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:33Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:33Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:35Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:35Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:37Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:37Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:39Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:39Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:41Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210909"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:41Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:43Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210909"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:43Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:45Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":17324}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:45Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:45Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"01-2019120401"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:45Skipping message, definition is undefined and still interviewing
Info 2022-07-06 17:07:45Successfully interviewed '0x84fd27fffe98fe64', device has successfully been paired
Warning 2022-07-06 17:07:45Device '0x84fd27fffe98fe64' with Zigbee model '3AFE090103021000' and manufacturer name 'Konke' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:45MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"successful","supported":false},"type":"device_interview"}'
Info 2022-07-06 17:07:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x84fd27fffe98fe64","supported":false},"type":"pairing"}'
Debug 2022-07-06 17:07:48Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"01-2019120401"}' from endpoint 1 with groupID 0
Warning 2022-07-06 17:07:48Received message from unsupported device with Zigbee model '3AFE090103021000' and manufacturer name 'Konke'
Warning 2022-07-06 17:07:48Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:48Successfully interviewed '0x84fd27fffe98fe64', device has successfully been paired
Warning 2022-07-06 17:07:48Device '0x84fd27fffe98fe64' with Zigbee model '3AFE090103021000' and manufacturer name 'Konke' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:48MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"successful","supported":false},"type":"device_interview"}'
Info 2022-07-06 17:07:48MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x84fd27fffe98fe64","supported":false},"type":"pairing"}'
Debug 2022-07-06 17:07:52Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":10792}' from endpoint 1 with groupID 0
Warning 2022-07-06 17:07:52Received message from unsupported device with Zigbee model '3AFE090103021000' and manufacturer name 'Konke'
Warning 2022-07-06 17:07:52Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### External converter

```shell
Warning 2022-07-06 17:04:48Device '0x84fd27fffe98fe64' left the networkkkkkkkkkkkkk
Info 2022-07-06 17:04:48MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_leave"}'
Info 2022-07-06 17:04:48MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_removed"}'
Info 2022-07-06 17:05:37Device '0x84fd27fffe98fe64' joined88888888888
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_joined"}'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_connected"}'
Info 2022-07-06 17:05:37Starting interview of '0x84fd27fffe98fe64'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"started"},"type":"device_interview"}'
Info 2022-07-06 17:05:37MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"pairing"}'
Debug 2022-07-06 17:05:44Device '0x84fd27fffe98fe64' announced itself
Info 2022-07-06 17:05:44MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64"},"type":"device_announce"}'
Info 2022-07-06 17:05:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x84fd27fffe98fe64"},"type":"device_announced"}'
Debug 2022-07-06 17:06:02Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2790}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:02Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:02Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":5570}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:02Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:13Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:13Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:18Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:18Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:20Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":10414}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:20Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:20Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:20Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:21Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:21Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:23Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:23Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:24Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"modelId":"3AFE090103021000"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:24Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:28Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":185,"batteryVoltage":29}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:28Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:06:29Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":184}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:06:29Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:03Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":2840}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:03Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:09Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Konke"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:09Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:14Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Konke"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:14Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:19Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:19Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:21Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:21Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:25Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:25Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:27Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:27Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:29Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"appVersion":9}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:29Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:31Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"appVersion":9}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:31Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:33Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:33Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:35Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:35Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:37Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:37Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:39Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:39Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:41Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210909"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:41Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:43Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210909"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:43Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:45Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":17324}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:45Skipping message, definition is undefined and still interviewing
Debug 2022-07-06 17:07:45Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"01-2019120401"}' from endpoint 1 with groupID 0
Debug 2022-07-06 17:07:45Skipping message, definition is undefined and still interviewing
Info 2022-07-06 17:07:45Successfully interviewed '0x84fd27fffe98fe64', device has successfully been paired
Warning 2022-07-06 17:07:45Device '0x84fd27fffe98fe64' with Zigbee model '3AFE090103021000' and manufacturer name 'Konke' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:45MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"successful","supported":false},"type":"device_interview"}'
Info 2022-07-06 17:07:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x84fd27fffe98fe64","supported":false},"type":"pairing"}'
Debug 2022-07-06 17:07:48Received Zigbee message from '0x84fd27fffe98fe64', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"01-2019120401"}' from endpoint 1 with groupID 0
Warning 2022-07-06 17:07:48Received message from unsupported device with Zigbee model '3AFE090103021000' and manufacturer name 'Konke'
Warning 2022-07-06 17:07:48Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:48Successfully interviewed '0x84fd27fffe98fe64', device has successfully been paired
Warning 2022-07-06 17:07:48Device '0x84fd27fffe98fe64' with Zigbee model '3AFE090103021000' and manufacturer name 'Konke' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-07-06 17:07:48MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x84fd27fffe98fe64","ieee_address":"0x84fd27fffe98fe64","status":"successful","supported":false},"type":"device_interview"}'
Info 2022-07-06 17:07:48MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x84fd27fffe98fe64","supported":false},"type":"pairing"}'
Debug 2022-07-06 17:07:52Received Zigbee message from '0x84fd27fffe98fe64', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":10792}' from endpoint 1 with groupID 0
Warning 2022-07-06 17:07:52Received message from unsupported device with Zigbee model '3AFE090103021000' and manufacturer name 'Konke'
Warning 2022-07-06 17:07:52Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
```

**Comment by keith-kl** [comment]
作者不懂中文的, 嘗試自己加
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
