### ISSUE TITLE
[New device support]: ADEO/Lexman ENKI Lexman E27 LED white - ZBEK-8

### ISSUE THREAD

**Issue by NicolasQuenon** [Koenkk/zigbee2mqtt#13072]
### Link

https://www.leroymerlin.fr/produits/decoration-eclairage/ampoule-et-led/ampoule-led/ampoule-e27/ampoule-connectee-led-globe-95-mm-e27-1055-lm-75-w-variation-de-blancs-lexman-84372279.html?clk=true

### Database entry

{"id":42,"type":"Router","ieeeAddr":"0x0c4314fffef91f21","nwkAddr":4527,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"ZBEK-8","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599,64642],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"ZBEK-8","manufacturerName":"Adeo","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20210714","swBuildId":"2.09.00"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20210714","swBuildId":"2.09.00","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1657230647435,"defaultSendRequestWhen":"immediate"}

### Comments

The reference on the box is : iG-CDZFB2AG009RA-MZN-02
I found also those informations : https://media.adeo.com/marketplace/LMFR/84372279/81354dc5-5cf1-41c0-8fc4-128a89b6d329.pdf
Thanks for your help !

### External converter

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBEK-8'],
    model: 'IG-CDZFB2G009RA-MZN-02',
    vendor: 'Xiaomi',
    description: 'ENKI LEXMAN E27 LED white fil 1055 lumens',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;

### Supported color modes

color temperature

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
