### ISSUE TITLE
OWON PIR313-E not supported 

### ISSUE THREAD

**Issue by Krinou3000** [Koenkk/zigbee2mqtt#13088]
### What happened?

The OWON PIR313-E is no longer supported.

### What did you expect to happen?

A new compatibility.

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus TI CC2652P

### Debug log

- Info 2022-07-09 23:07:04Device '0x3c6a2cfffed1b13a' joined
- Info 2022-07-09 23:07:04MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed1b13a","ieee_address":"0x3c6a2cfffed1b13a"},"type":"device_joined"}'
- Info 2022-07-09 23:07:04Starting interview of '0x3c6a2cfffed1b13a'
- Info 2022-07-09 23:07:04MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed1b13a","ieee_address":"0x3c6a2cfffed1b13a","status":"started"},"type":"device_interview"}'
- Debug 2022-07-09 23:07:04Device '0x3c6a2cfffed1b13a' announced itself
- Info 2022-07-09 23:07:04MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed1b13a","ieee_address":"0x3c6a2cfffed1b13a"},"type":"device_announce"}'
- Debug 2022-07-09 23:07:04Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
- Debug 2022-07-09 23:07:04Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:05Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
- Debug 2022-07-09 23:07:05Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:07Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 2 with groupID 0
- Debug 2022-07-09 23:07:07Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:09Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 2 with groupID 0
- Debug 2022-07-09 23:07:09Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:17Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
- Debug 2022-07-09 23:07:17Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:20Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 3 with groupID 0
- Debug 2022-07-09 23:07:20Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:22Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 3 with groupID 0
- Debug 2022-07-09 23:07:22Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:24Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":0}' from endpoint 1 with groupID 0
- Debug 2022-07-09 23:07:24Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:29Received Zigbee message from '0x3c6a2cfffed1b13a', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":53}' from endpoint 1 with groupID 0
- Debug 2022-07-09 23:07:29Skipping message, definition is undefined and still interviewing
- Debug 2022-07-09 23:07:30Received Zigbee message from '0x3c6a2cfffed1b13a', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b0024c82a97","zoneState":1}' from endpoint 1 with groupID 0
- Debug 2022-07-09 23:07:30Skipping message, definition is undefined and still interviewing
- Info 2022-07-09 23:07:30Successfully interviewed '0x3c6a2cfffed1b13a', device has successfully been paired
- Warning 2022-07-09 23:07:30Device '0x3c6a2cfffed1b13a' with Zigbee model 'PIR313' and manufacturer name 'OWON' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
- Info 2022-07-09 23:07:30MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x3c6a2cfffed1b13a","ieee_address":"0x3c6a2cfffed1b13a","status":"successful","supported":false},"type":"device_interview"}'
- Debug 2022-07-09 23:07:35Received Zigbee message from '0x3c6a2cfffed1b13a', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":53}' from endpoint 1 with groupID 0
- Warning 2022-07-09 23:07:35Received message from unsupported device with Zigbee model 'PIR313' and manufacturer name 'OWON'
- Warning 2022-07-09 23:07:35Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Krinou3000** [comment]
Thanks a lot !! ;)

**Comment by Uhmoja** [comment]
Hi !
I'm trying to use the OWON PIR313-E sensor.
The sensor is well recognized and noted as supported, but the problem is that I don't have all the data normally available.

The sensor transmits :
- Battery status.
- The quality of the signal.
- The presence detection.
- The detection of manipulation.

However, it does not transmit (null value):
- The temperature measurement.
- Humidity measurement.
- Luminosity measurement.

Here is an example of a communication received:
_
nov. 02 14:05:13 raspberrypi npm[3251]: Zigbee2MQTT:info  2022-11-02 14:05:13: MQTT publish: topic 'zigbee2mqtt/Multi sensor OWON', payload '{"battery_low":false,"humidity":null,"illuminance":null,"illuminance_lux":null,"linkquality":255,"occupancy":true,"tamper":true,"temperature":null}'
_

Can I do something to resolve it ?

Thanks.
