### ISSUE TITLE
Immax Motion Senzor ZB3.0

### ISSUE THREAD

**Issue by DobrakAG** [Koenkk/zigbee2mqtt#13082]
### Link

Not in catalog anymore

### Database entry

{"id":16,"type":"EndDevice","ieeeAddr":"0x000d6ffffe407781","nwkAddr":60332,"manufId":4151,"manufName":"Immax","powerSource":"Battery","modelId":"Motion-Sensor-ZB3.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1280,2821,64641],"outClusterList":[25],"clusters":{"ssIasZone":{"attributes":{"65531":1,"iasCieAddr":"0x00124b001cdd435f","zoneState":1,"currentZoneSensitivityLevel":0}},"genPollCtrl":{"attributes":{"checkinInterval":6480}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b001cdd435f","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001cdd435f","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":37,"stackVersion":2,"hwVersion":1,"dateCode":"20190220-16","swBuildId":"2.1","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1657384508234,"defaultSendRequestWhen":"active"}

### Comments

I have found Immax device which was on market 3-4 years ago. Actually is not available in stores, but plenty of them are still alive. I create converter for it, please feel free to add it into your library. Picture I will also try to request, can be used the same as 07047L .
If you will need help file for pairing, let me know, I will try to create something. 

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {

        zigbeeModel: ['Motion-Sensor-ZB3.0'],
        model: '07043M',
        vendor: 'Immax',
        description: 'Motion sensor',
        fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery],
        toZigbee: [],
        exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.battery()],

};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
