### ISSUE TITLE
Reporting is removed when remote is removed from group

### ISSUE THREAD

**Issue by NicolaiPetri** [Koenkk/zigbee2mqtt#13115]
### What happened?

When removing / un-binding remote from a group, then the auto created reporting configurations are deleted.
This seems to stop my home assistant to get updates from bulbs. 
Also, it could be beneficial to always configure reporting for (certain) devices no matter if they are in a group or not. It seems counter intuitive that the auto-reporting only is configured in groups and when a remote is bound.

### What did you expect to happen?

That I by default or after setting some configuration value, will get automatic reporting of status from my devices (esp. lights) on a regular interval.
This is especially important for where devices state can be changed without involving the coordinator. This could be by power cycling a device or where it might have local controls available. 

### How to reproduce it (minimal and precise)

Bind an remote to a group with devices, remove it and reportings are deleted.

### Zigbee2MQTT version

1.26.0-dev commit: 8af3ad55

### Adapter firmware version

20220219

### Adapter

zzh

### Debug log

-

**Comment by sjorge** [comment]
It's by design  that reporting is removed when unbinding a remote from a group, it's by design (Annoying, I know)

If you unbind via mqtt instead of the frontend, you can prevent it by adding `{"skip_disable_reporting": true}` to the payload:
https://www.zigbee2mqtt.io/guide/usage/binding.html#when-to-use-this

**Comment by NicolaiPetri** [comment]
@sjorge Thanks for that insight. That’s interesting news. I will sleep on this and see if this is enough for me. 
But I do somehow feel that this approach maybe should be changed, but I’m not completely sure about best alternative.

**Comment by sjorge** [comment]
Yeah I too would prefer the reporting to remain :( but for now this is a workable solution for me.

There is IMHO stuff to improve wrt to reporting:
- option in confit to remove reporting unbind or not
- user default reporting config on a ‘per device model’ basis that gets applied to every new device of that model that gets joined/after every reconfigure for the device
- …
