### ISSUE TITLE
[Feature request]: no_occupancy_since for TuYa IH012-RT01

### ISSUE THREAD

**Issue by Bastiencc** [Koenkk/zigbee2mqtt#13119]
### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Is it possible to add the great feature "no_occupancy_since" and "occupancy_timeout" for TuYa IH012-RT01 device ?
Thank you for the excellent work you !

### Describe alternatives you've considered

-

### Additional context

-

**Comment by marine1988** [comment]
does you sensor work good? my is allways saying ocupied

**Comment by Bastiencc** [comment]
Yes, all good

**Comment by Bastiencc** [comment]
up :)

**Comment by messyjoes1** [comment]
no_occupancy_since is essential feature and would be great to have it for Tuya. At least someone who knows could tell us if this feature comes from zigbee2mqtt or is it device event
