### ISSUE TITLE
update.sh script not working when pull.rebase is globally set to true for git

### ISSUE THREAD

**Issue by mgisbers** [Koenkk/zigbee2mqtt#13116]
### What happened?

On the local installation the update.sh script is run and should update the git repository.
When trying to pull from github an error message is shown and the script continues without updating local repository.

```
# bash update.sh 
Stopping Zigbee2MQTT...
Creating backup of configuration...
Updating...
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
Installing dependencies...
[...]
```

### What did you expect to happen?

I expected the local repository being updated and a new version gets installed.

### How to reproduce it (minimal and precise)

Change git to do pull with rebase instead of merge.

`git config --global pull.rebase true`

To get around the problem change the global config in the local repository by running

`git config pull.rebase false`

in the local repository working directory or by changing

`git pull`

into

`git pull --rebase=false`

within `update.sh`.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

n/a

### Adapter

Shaesh's CC2652RB stick

**Comment by Hoerli1337** [comment]
Also have the error, with me it shows only a little more.

```
root@raspberrypi4B:/opt/zigbee2mqtt# ./update.sh
Stopping Zigbee2MQTT...
Creating backup of configuration...
Updating...
Update bc4ffc00..a9b88082
error: Your local changes in the following files would be overwritten by the merge will be overwritten:
        package-lock.json
Please commit or stash your changes before you merge.
Abort
```
