### ISSUE TITLE
EMIZB-132 current calibration on phase b/c

### ISSUE THREAD

**Issue by toremick** [Koenkk/zigbee2mqtt#13126]
### What happened?

current_calibrate only affects device_current, not device_current_phase_b or c (same for voltage)

### What did you expect to happen?

That current calibrate would calibrate either all phases, or a current_phase_x_calibrate possibility

### How to reproduce it (minimal and precise)

set a value for current_calibrate

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20210120

### Adapter

CC2652 board

**Comment by Koenkk** [comment]
I expect this already works by setting `current_phase_b_calibrate` or `current_phase_c_calibrate`

**Comment by toremick** [comment]
> I expect this already works by setting `current_phase_b_calibrate` or `current_phase_c_calibrate`

Im sorry to say, no. (wrote wrong in my report, its not calibrate, its calibration. The 'current_calibration' is added from web, and the one for phase_b is added manually, then z2m is restarted)

from configuration.yaml


  
' 0x0015bc001b02508c':  
friendly_name: '0x0015bc001b02508c'   
interface_mode: kaifa_and_kamstrup  
current_calibration: -99  
current_phase_b_calibration: -99  
power_calibration: 0  
voltage_calibration: 0  


Result:
![image](https://user-images.githubusercontent.com/47187504/178916837-51e8a774-f623-4400-99f8-e654dcaaac4b.png)

**Comment by Koenkk** [comment]
Pushed a possible fix, please check. Note that the calibration is applied only after the device reports a new value.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by toremick** [comment]
> Pushed a possible fix, please check. Note that the calibration is applied only after the device reports a new value.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

It works (both b/c) !

![image](https://user-images.githubusercontent.com/47187504/179157336-5bb0714f-7b30-4375-8525-f1db4d9bc9f8.png)

**Comment by Koenkk** [comment]
Cool! 😄
