### ISSUE TITLE
Xiaomi SP-EUC01, 0 values for "power" and "energy"

### ISSUE THREAD

**Issue by sagittarius0815** [Koenkk/zigbee2mqtt#13120]
### What happened?

Xiaomi SP-EUC01 does not expose "voltage" and "current".
The values for "power" and "energy" are 0.

### What did you expect to happen?

Referring the relase note "voltage", "current",  "power" and "energy" should be exposed by Xiaomi SP-EUC01

### Zigbee2MQTT version

1.26.0-dev

### Adapter firmware version

{"meta":{"maintrel":0,"majorrel":38,"minorrel":88,"product":0,"revision":"0x26580700","transportrev" :0},"type":"ConBee2/RaspBee2"}

### Adapter

ConBee2/RaspBee2

### Debug log

{"device_temperature":38,"energy":0,"linkquality":167,"power":0,"power_outage_memory":true,"state":"ON","update":{"state":"idle"},"update_available":false}

**Comment by Koenkk** [comment]
Try upgrading your Conbee 2 firmware to at least [0x26720700](http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26720700.bin.GCF) and repair the device.

**Comment by sagittarius0815** [comment]
running now latest ccordinator firmware version ConBee2/RaspBee2 0x26780700
but nothing changed:
"energy":0, "power".0
"voltage" and "current" are not expose (which is no problem for me)

**Comment by sagittarius0815** [comment]
Sorry, but now I understand the meaning of "repair" - not fix up / put right, but re-pair the device :)
Yes! Now "energy", "power", "voltage" and "current" are exposed with values.
Problem solved.
