### ISSUE TITLE
[New device support]: Livarno outdoor LED light chain HG08383A

### ISSUE THREAD

**Issue by malosaa** [Koenkk/zigbee2mqtt#13133]
### Link

https://www.lidl.de/p/livarno-home-led-bodenlichterkette-5er-dimmbar-zigbee-smart-home/p100347334

### Database entry

{"id":24,"type":"Router","ieeeAddr":"0x003c84fffed6dcdd","nwkAddr":42128,"manufId":4098,"manufName":"_TZ3000_taspddvq","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"61440":0,"onOff":1}},"lightingColorCtrl":{"attributes":{"57344":1000,"61447":[],"61448":[],"61449":[],"61453":0,"tuyaRgbMode":0,"currentHue":null}},"genLevelCtrl":{"attributes":{"61440":1000}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1657726240126,"defaultSendRequestWhen":"immediate"}

### Comments

The HG08383B is already supported.

but this is the HG08383A version.

its not the round ones, but round/flat ones.

### External converter
![image](https://user-images.githubusercontent.com/13116501/178775923-54a8d98d-28c1-4e64-8ee5-649c894192aa.png)

_No response_

### Supported color modes

RGB and WHITE

**Comment by Koenkk** [comment]
`_TZ3000_taspddvq` is already supported in the latest dev

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by malosaa** [comment]
@Koenkk 

Can i run Edge and stable version together on Homeassistant without losing settings ?

regards

**Comment by Koenkk** [comment]
You can only run 1 z2m instance at a time (stable or edge, not both)

**Comment by Koenkk** [comment]
> So i basically can stop my stable release and run the edge instead and it should use the same config of the stable release ?

Exactly!
