### ISSUE TITLE
Moes TS0112 not updating status when physical button is pushed

### ISSUE THREAD

**Issue by pedromargarido** [Koenkk/zigbee2mqtt#13138]
### What happened?

If I press the physical button on my Moes TS0112 the on/off status on Zigbee2Mqtt is not being updated and I get errors on the log:
![image](https://user-images.githubusercontent.com/53160650/178830469-ee220a41-0fb3-4048-9278-90a9bec8baa8.png)

If I control using the Zigbee2Mqtt the status is updated.

This is the device:
![image](https://user-images.githubusercontent.com/53160650/178830980-0f3eaa85-fd40-4a28-b0f4-6d291a38453a.png)

### What did you expect to happen?

The status should be updated and I should see no errors.

### How to reproduce it (minimal and precise)

Just press the physical button

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20190608

### Adapter

CC2531

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0112'],
    model: 'ZK-EU-2U',
    vendor: 'Moes',
    description: 'Zigbee 3.0 dual USB wireless socket plug',
    extend: extend.switch(),
    exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2')],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        const hasEndpoint2 = !!device.getEndpoint(2);
        return {l1: 1, l2: hasEndpoint2 ? 2 : 7};
    },
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await device.getEndpoint(1).read('genBasic',
            ['manufacturerName', 'zclVersion', 'appVersion', 'modelId', 'powerSource', 0xfffe]);
    },
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by pedromargarido** [comment]
![image](https://user-images.githubusercontent.com/53160650/179023901-6bf6365a-768e-4723-bee5-aa7b097d64ea.png)

Same problem:

![image](https://user-images.githubusercontent.com/53160650/179023542-90dd8131-aaff-4cd5-846d-92e302bd3575.png)

**Comment by Koenkk** [comment]
Updated https://github.com/Koenkk/zigbee2mqtt/issues/13138#issuecomment-1184549678 , can you try again?

**Comment by pedromargarido** [comment]
Same.

![image](https://user-images.githubusercontent.com/53160650/179307072-1d244b2b-5ceb-4cd5-b069-d60ccca386fa.png)

**Comment by Koenkk** [comment]
I've added some more debug logging, can you update to the latest dev branch and provide me the debug logging?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by pedromargarido** [comment]
![image](https://user-images.githubusercontent.com/53160650/179637671-93049832-b3ca-46a1-9803-56ed2631e8c0.png)

I've added zigbee_herdsman_debug: true on mu configuration.yaml

Turned on -> Turned off:

![image](https://user-images.githubusercontent.com/53160650/179637605-96f4f30c-70ee-4332-8442-22e54afb2f91.png)

**Comment by Koenkk** [comment]
Can you provide the logging again with this converter?


```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0112'],
    model: 'ZK-EU-2U',
    vendor: 'Moes',
    description: 'Zigbee 3.0 dual USB wireless socket plug',
    extend: extend.switch(),
    exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2')],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        throw new Error("THIS IS THE DEVICE " + JSON.stringify(device));
        const hasEndpoint2 = !!device.getEndpoint(2);
        return {l1: 1, l2: hasEndpoint2 ? 2 : 7};
    },
};

module.exports = definition;

```

**Comment by pedromargarido** [comment]
Debug 2022-07-19 13:20:32Received Zigbee message from 'smartphone_charger', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

Error 2022-07-19 13:20:32Exception while calling fromZigbee converter: THIS IS THE DEVICE {"zh":{"_events":{},"_eventsCount":0,"ID":4,"_type":"Router","_ieeeAddr":"0xec1bbdfffe66b673","_networkAddress":17408,"_manufacturerID":0,"_endpoints":[{"_events":{},"_eventsCount":0,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0112","manufacturerName":"_TYZB01_b1ngbmlm","powerSource":1,"zclVersion":3,"appVersion":67}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"ID":2,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"_TYZB01_b1ngbmlm","_powerSource":"Mains (single phase)","_modelID":"TS0112","_applicationVersion":67,"_zclVersion":3,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-1235914622},"_lastSeen":1658247637202,"_defaultSendRequestWhen":"immediate","_linkquality":55},"_definition":{"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l1","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l1"}],"endpoint":"l1"},{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l2","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l2"}],"endpoint":"l2"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","on_time","off_wait_time"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"zigbeeModel":["TS0112"],"model":"ZK-EU-2U","vendor":"Moes","description":"Zigbee 3.0 dual USB wireless socket plug","meta":{"multiEndpoint":true},"options":[]},"_definitionModelID":"TS0112"}}

Debug 2022-07-19 13:20:32Error: THIS IS THE DEVICE {"zh":{"_events":{},"_eventsCount":0,"ID":4,"_type":"Router","_ieeeAddr":"0xec1bbdfffe66b673","_networkAddress":17408,"_manufacturerID":0,"_endpoints":[{"_events":{},"_eventsCount":0,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0112","manufacturerName":"_TYZB01_b1ngbmlm","powerSource":1,"zclVersion":3,"appVersion":67}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"ID":2,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"_TYZB01_b1ngbmlm","_powerSource":"Mains (single phase)","_modelID":"TS0112","_applicationVersion":67,"_zclVersion":3,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-1235914622},"_lastSeen":1658247637202,"_defaultSendRequestWhen":"immediate","_linkquality":55},"_definition":{"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l1","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l1"}],"endpoint":"l1"},{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l2","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l2"}],"endpoint":"l2"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","on_time","off_wait_time"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"zigbeeModel":["TS0112"],"model":"ZK-EU-2U","vendor":"Moes","description":"Zigbee 3.0 dual USB wireless socket plug","meta":{"multiEndpoint":true},"options":[]},"_definitionModelID":"TS0112"} at Object.endpoint (/app/dist/util/externally-loaded.js:20:15) at postfixWithEndpointName (/app/node_modules/zigbee-herdsman-converters/lib/utils.js:118:31) at Object.convert (/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:780:34) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:538:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27) at Controller.emit (node:events:526:28) at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:495:14) at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:706:18)

Debug 2022-07-19 13:20:32Received Zigbee message from 'smartphone_charger', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 2 with groupID 0

Error 2022-07-19 13:20:32Exception while calling fromZigbee converter: THIS IS THE DEVICE {"zh":{"_events":{},"_eventsCount":0,"ID":4,"_type":"Router","_ieeeAddr":"0xec1bbdfffe66b673","_networkAddress":17408,"_manufacturerID":0,"_endpoints":[{"_events":{},"_eventsCount":0,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0112","manufacturerName":"_TYZB01_b1ngbmlm","powerSource":1,"zclVersion":3,"appVersion":67}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"ID":2,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"_TYZB01_b1ngbmlm","_powerSource":"Mains (single phase)","_modelID":"TS0112","_applicationVersion":67,"_zclVersion":3,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-1235914622},"_lastSeen":1658247637228,"_defaultSendRequestWhen":"immediate","_linkquality":57},"_definition":{"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l1","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l1"}],"endpoint":"l1"},{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l2","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l2"}],"endpoint":"l2"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","on_time","off_wait_time"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"zigbeeModel":["TS0112"],"model":"ZK-EU-2U","vendor":"Moes","description":"Zigbee 3.0 dual USB wireless socket plug","meta":{"multiEndpoint":true},"options":[]},"_definitionModelID":"TS0112"}}

Debug 2022-07-19 13:20:32Error: THIS IS THE DEVICE {"zh":{"_events":{},"_eventsCount":0,"ID":4,"_type":"Router","_ieeeAddr":"0xec1bbdfffe66b673","_networkAddress":17408,"_manufacturerID":0,"_endpoints":[{"_events":{},"_eventsCount":0,"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0112","manufacturerName":"_TYZB01_b1ngbmlm","powerSource":1,"zclVersion":3,"appVersion":67}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"ID":2,"profileID":260,"deviceID":81,"inputClusters":[0,3,4,5,6,1794,2820],"outputClusters":[25],"deviceNetworkAddress":17408,"deviceIeeeAddress":"0xec1bbdfffe66b673","clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e271b9","endpointID":1}],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"_TYZB01_b1ngbmlm","_powerSource":"Mains (single phase)","_modelID":"TS0112","_applicationVersion":67,"_zclVersion":3,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":-1235914622},"_lastSeen":1658247637228,"_defaultSendRequestWhen":"immediate","_linkquality":57},"_definition":{"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l1","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l1"}],"endpoint":"l1"},{"type":"switch","features":[{"type":"binary","name":"state","property":"state_l2","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE","endpoint":"l2"}],"endpoint":"l2"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","on_time","off_wait_time"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"zigbeeModel":["TS0112"],"model":"ZK-EU-2U","vendor":"Moes","description":"Zigbee 3.0 dual USB wireless socket plug","meta":{"multiEndpoint":true},"options":[]},"_definitionModelID":"TS0112"} at Object.endpoint (/app/dist/util/externally-loaded.js:20:15) at postfixWithEndpointName (/app/node_modules/zigbee-herdsman-converters/lib/utils.js:118:31) at Object.convert (/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:780:34) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:538:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27) at Controller.emit (node:events:526:28) at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:495:14) at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:706:18)

**Comment by Koenkk** [comment]
Found the issue, should be fixed now, make sure to remove your external converter.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
