### ISSUE TITLE
Last seen not updating for bulbs that are part of a group

### ISSUE THREAD

**Issue by drjjr2** [Koenkk/zigbee2mqtt#13131]
### What happened?

I have two **Philips Zigbee Model LWB004 Hue Lux A19 bulb E27** that are part of a group. When I control the group, it responds properly and the bulbs are working as expected. But "last seen" does not get updated unless I access the bulbs individually.

### What did you expect to happen?

Expected that both bulbs would have their last seen be the last time that the group was controlled since both bulbs would have been controlled at that time.

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20220219

### Adapter

Sonoff USB Zigbee 3.0 Dongle

**Comment by Koenkk** [comment]
This is expected, when controlling Zigbee device through groups the bulbs don't report anything back to the coordinator so the last seen will not update.
