### ISSUE TITLE
[New device support]: PSE03-V1.1.0 Vendor : EVOLOGY

### ISSUE THREAD

**Issue by mickadam29** [Koenkk/zigbee2mqtt#13143]
### Link

https://www.leroymerlin.fr/produits/electricite-domotique/alarme-camera-de-surveillance-et-detecteur-de-fumee/alarme-maison/sirene-alarme/sirene-interieure-connectee-evology-80123668.html

### Database entry

{"id":56,"type":"Router","ieeeAddr":"0x000d6f000f1957ad","nwkAddr":4500,"manufId":65440,"manufName":"","powerSource":"DC Source","modelId":"PSE03-v1.1.0","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClusterList":[0,1,9,1280,1282],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"PSE03-v1.1.0","manufacturerName":"","powerSource":4,"zclVersion":1,"appVersion":0,"stackVersion":0,"hwVersion":0,"swBuildId":"1.1.0"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00258dd909","zoneState":1,"zoneId":23,"zoneStatus":0,"zoneType":549}},"ssIasWd":{"attributes":{"maxDuration":180}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00258dd909","endpointID":1},{"cluster":1280,"type":"endpoint","deviceIeeeAddress":"0x00124b00258dd909","endpointID":1},{"cluster":1282,"type":"endpoint","deviceIeeeAddress":"0x00124b00258dd909","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b00258dd909","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"swBuildId":"1.1.0","zclVersion":1,"interviewCompleted":true,"meta":{"configured":131383979},"lastSeen":1657790435901,"defaultSendRequestWhen":"immediate"}

### Comments

@Koenkk 

With this external converter device works fine
Could you add it into evology.js as a new zigbee-herdsman-converters
Strobe doesn't work, only then siren does
By default, is it possible to hide strobe functionality ?

![2022-07-14 11_31_25-Dashboard - Jeedom et 9 pages de plus - Profil 1 – Microsoft​ Edge](https://user-images.githubusercontent.com/36518012/178951726-5ff2f80a-560c-4209-a2de-460be8ca3e84.png)

Alarme (mode and duration) and stop functionality work fine

Thk's

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const constants = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

module.exports = {
    zigbeeModel: ['PSE03-V1.1.0'],
    model: 'PSE03-V1.1.0',
    vendor: 'EVOLOGY',
    description: 'Sound and Flash Siren',
    fromZigbee: [fz.ignore_basic_report,fz.ias_wd, fz.ias_enroll, fz.ias_siren],
    toZigbee: [tz.warning],
    meta: {disableDefaultResponse: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'ssIasZone', 'ssIasWd', 'genBasic']);
        await endpoint.read('ssIasZone', ['zoneState', 'iasCieAddr', 'zoneId', 'zoneStatus']);
        await endpoint.read('ssIasWd', ['maxDuration']);
    },
    exposes: [e.warning()],
};
```

**Comment by Clem-** [comment]
Hi, I have no action nor status (except linkquality) on HomeAssistant for this device. 
Do you know why?
Thanks!

**Comment by Koenkk** [comment]
@Clem- this is because Home Assistant does not support the warning type (where you can start the siren from). As a workaround you can publish an MQTT message from z2m with the following format: https://www.zigbee2mqtt.io/devices/PSE03-V1.1.0.html#warning-composite

**Comment by Clem-** [comment]
Thank you very much for your reply :)What is the benefit of exposing a warning type, though ?Le 27 avr. 2023 à 19:10, Koen Kanters ***@***.***> a écrit :﻿
@Clem- this is because Home Assistant does not support the warning type (where you can start the siren from). As a workaround you can publish an MQTT message from z2m with the following format: https://www.zigbee2mqtt.io/devices/PSE03-V1.1.0.html#warning-composite
