### ISSUE TITLE
[New device support]: ADEO ZBEK-9 -- IA-CDZFB2AA007NA-MZN-02

### ISSUE THREAD

**Issue by inoxas78** [Koenkk/zigbee2mqtt#13144]
### Link

https://www.leroymerlin.fr/produits/decoration-eclairage/ampoule-et-led/ampoule-led/ampoule-e27/ampoule-connectee-led-standard-e27-806-lm-60-w-variation-de-blancs-lexman-84372280.html?fwd=3276007273922

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0x50325ffffe208241","nwkAddr":61576,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"ZBEK-9","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599,64642],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"ZBEK-9","manufacturerName":"Adeo","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20210714","swBuildId":"2.09.00"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20210714","swBuildId":"2.09.00","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1657792534286,"defaultSendRequestWhen":"immediate"}

### Comments

very similar with ZBEK-12 : IA-CDZFB2AA007NA-MZN-01
Code on box: IA-CDZFB2AA007NA-MZN-02

01 is with an opaque glass
02 is crytal glass with "filaments"

![image](https://user-images.githubusercontent.com/21035583/178959331-800d0a70-b1f4-4e27-a8cf-8a30da383676.png)

### External converter

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBEK-9'],
    model: 'IA-CDZFB2AA007NA-MZN-02',
    vendor: 'ADEO',
    description: 'ENKI LEXMAN E27 LED white',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 454]}),
};

module.exports = definition;

**-----------> Working very well**

### Supported color modes

white temperature

### Color temperature range

[153, 454]

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by inoxas78** [comment]
❤️❤️
