### ISSUE TITLE
routing problems with tuya zigbee bulbs

### ISSUE THREAD

**Issue by heliosgg** [Koenkk/zigbee2mqtt#13152]
### What happened?

I suppose my bulbs cannot cannot work as mesh network. Those bulbs that are far away from my coordinator show low lqi, but there are intermediate routers (same bulbs) between them and coordinator.
When I try to get a network map in MQTT Explorer (zigbee2mqtt/bridge/request/networkmap ({"type": "graphviz", "routes": true})) I get errors in Z2M logs such as:
Failed to execute routing table for 'bulb_5'
For each tuya bulb.
I think the problem is here.
Thanks in advance.

### What did you expect to happen?

Working routing on tuya bulbs

### How to reproduce it (minimal and precise)

Publish {"type": "graphviz", "routes": true} to zigbee2mqtt/bridge/request/networkmap

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20220219

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Debug log

[z2m.log](https://github.com/Koenkk/zigbee2mqtt/files/9114979/z2m.log)

**Comment by heliosgg** [comment]
Bulb model TS0505B

**Comment by heliosgg** [comment]
[zigbee_networkmap.zip](https://github.com/Koenkk/zigbee2mqtt/files/9123824/zigbee_networkmap.zip)
I sniffed zigbee during zigbee2mqtt/bridge/request/networkmap.
I hope it will help

**Comment by heliosgg** [comment]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9126510/log.txt)
I think previous debug log is wrong. Im sorry. it's probably correct

**Comment by heliosgg** [comment]
@Koenkk can you please help? I dont know what to do

**Comment by Koenkk** [comment]
`Failed to execute routing table for 'bulb_5'` this means this device does not support the routing table command. (cannot be fixed from z2m)

**Comment by heliosgg** [comment]
Thank you for your reply. Does it mean that problem is on bulb firmware side?

**Comment by Koenkk** [comment]
> Does it mean that problem is on bulb's firmware side?

yes

**Comment by heliosgg** [comment]
OK, thank you. I will try to get my money back.

**Comment by mrmaximas** [comment]
> does not support the routing table command

@Koenkk Does it mean that such devices should not be used at all for building zigbee networks?
I can confirm that this my tuya-based devices does not support the routing table command:
_TZ3000_air9m6af
_TZ3000_iedbgyxt
_TZ3210_weaqkhab
_TZ3210_ngqk6jia
_TZ3000_mtnpt6ws
_TZ3000_4rbqgcuv
GLEDOPTO GL-C-009P

**Comment by Koenkk** [comment]
They support the router functionality, but do not support a getting the routing table from it.

**Comment by mrmaximas** [comment]
> They support the router functionality, but do not support a getting the routing table from it.

@Koenkk thank you. Please tell me, I have several tuya-based routers, which after rebooting gradually reduce LQI, for example from 100-120 to 25-30 and, accordingly, after some time (0.5-2h) stop responding, while with similar devices nearby this does not happen, in general I have a fairly high density of routers in the building, on the map most of the links with LQI 100-150, but 2-3 routers are no longer available after time, physical replacement does not help, I have already wondered whether my decision was correct to get away from wi-fi as much as possible ;) 
What does LQI even mean? How does the router see the coordinator directly or through a chain of routers? It seems that several of my devices do not want to work through intermediate routers.

**Comment by Koenkk** [comment]
The LQI is of the last hop (so from router -> coordinator)
