### ISSUE TITLE
IKEA Remote Color switching doesn't work (even with group 65289)

### ISSUE THREAD

**Issue by freundTech** [Koenkk/zigbee2mqtt#13151]
### What happened?

I've switched from the IKEA gateway to Z2M using a SONOFF Zigbee 3.0 USB today.

After connecting my bulbs and remotes and binding them I set up the "magic group" as described at https://www.zigbee2mqtt.io/devices/E1524_E1810.html#binding

This group contains all my bulbs, however switching scenes using the remote only works on half of my bulbs.

It works on my 3 [LED1537R6/LED1739R5](https://www.zigbee2mqtt.io/devices/LED1537R6_LED1739R5.html), which are in a group and individually bound to a [E1524/E1810](https://www.zigbee2mqtt.io/devices/E1524_E1810.html) Remote, but doesn't work on my 3 [LED1923R5](https://www.zigbee2mqtt.io/devices/LED1923R5.html), which are also in another group and individually bound to another[E1524/E1810](https://www.zigbee2mqtt.io/devices/E1524_E1810.html) Remote.

Could it be possible that those bulbs use another number for the magic group? Or are there problems using the magic group with mixed rgb and color temperature bulbs?

### What did you expect to happen?

The Bulbs should switch scene when pressing the left or right button

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB

**Comment by freundTech** [comment]
Bump

**Comment by freundTech** [comment]
Bump

**Comment by freundTech** [comment]
Bump

**Comment by freundTech** [comment]
bump

**Comment by freundTech** [comment]
bump

**Comment by JayJay-Master** [comment]
I have a similar problem with changing color temperatur of IKEA LED1732G11. A month ago all worked well, but now nothing happens.
Toggle and brightness click and move works as expected.

Zigbee2MQTT Version: 1.30.1-dev commit: [a35705c]
Firmware version of Remot Control:  24.4.5 and previous vorsion 2.3.080
Firmware version of LED Lamp: 2.3.095

**Comment by JayJay-Master** [comment]
bump
