### ISSUE TITLE
TuYa SOS button NOT receiving action. TS0215A_sos _TZ3000_4fsgukof

### ISSUE THREAD

**Issue by louismulder** [Koenkk/zigbee2mqtt#13159]
### What happened?

The button is pairing, but not receiving the action, when I push the button

### What did you expect to happen?

That the action "emergency" was received

### How to reproduce it (minimal and precise)

First joining the device.
Then push the button

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20210708

### Adapter

SONOFF 3.0 dongle

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9119808/log.txt)

**Comment by louismulder** [comment]
I think I know the solution for this issue, but don't know how to implement this.
What was the situation?:
First I bought a SOS button  modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'
I did asked to add this device as new device. See issue #[https://github.com/Koenkk/zigbee2mqtt/issues/12910](url) but I noticed that the button didn't respond. So I ask the AliExpress seller to refund the money.
Then I bought a new one with modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'. This button didn't respond either. So I returned it to the seller.

After searching the internet, I saw that more systems had the same issue, but someone solved it with the driver from Nedis. I still had my {modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'} to experiment with.
So I have tried to use the other declaration TS0215A from Nedis model 'TS0215A_remote'.

I was surprised that is working now.

   {
        fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_wr2ucaj9'}],
        model: 'TS0215A_sos',
        vendor: 'TuYa',
        description: 'SOS button',
        fromZigbee: [fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['emergency'])],
        toZigbee: [],
    },
    {
        fingerprint: [{modelID: 'TS0215A', manufacturerName: '_TZ3000_p6ju8myv'},
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_fsiepnrh'}**,
            {modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'}**],
        model: 'TS0215A_remote',
        vendor: 'TuYa',
        description: 'Security remote control',
        fromZigbee: [fz.command_arm, fz.command_emergency, fz.battery],
        exposes: [e.battery(), e.action(['disarm', 'arm_day_zones', 'arm_night_zones', 'arm_all_zones', 'exit_delay', 'emergency'])],
        toZigbee: [],
        whiteLabel: [{vendor: 'Woox', model: 'R7054'}, {vendor: 'Nedis', model: 'ZBRC10WT'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genTime', 'genBasic', 'ssIasAce', 'ssIasZone']);
        },
    },

So I have removed {modelID: 'TS0215A', manufacturerName: '_TZ3000_tj4pwzzm'} from model 'TS0215A_sos' and added in model: 'TS0215A_remote'.

My concern now is that I don't know how to implement {modelID: 'TS0215A', manufacturerName: '_TZ3000_4fsgukof' without disturbing current environments.

**Comment by Koenkk** [comment]
Pushed the fix, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by louismulder** [comment]
> Pushed the fix, thanks!
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Hi Koen,

I have now tried another solution, which looks also good.
I have added the fz.command_arm to the fromZigbee item of model: 'TS0215A_sos' 
        fromZigbee: [fz.command_arm, fz.command_emergency, fz.battery],

Maybe this is a better solution than moving to model: 'TS0215A_remote'

**Comment by Koenkk** [comment]
@louismulder does the device send the `emergency` action when clicking it? If not then it should be in TS0215A_remote

**Comment by louismulder** [comment]
> @louismulder does the device send the `emergency` action when clicking it? If not then it should be in TS0215A_remote

Hi Koen,

Yes the action = emergency

**Comment by Koenkk** [comment]
Pushed the fix, can you check if it still works?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by louismulder** [comment]
Hi Koen,

works like a charm

Thanks for your quick support.
