### ISSUE TITLE
Statistic power consumption

### ISSUE THREAD

**Issue by AndreaNizzola** [Koenkk/zigbee2mqtt#13181]
### What happened?

I have a Legrand 412015 power meter, it works great however I would like to add it onto the Energy tab to keep a log of the power consumption of the house. The home assistant support says that the integration developers need to change the settings of the device to allow for it to be used as a statistic device.
The HA link is: https://www.home-assistant.io/more-info/statistics/
That also contains a link on how to do it.

I really hope you can fix it and I really like the work you have been doing. KEEP IT UP!!!

### What did you expect to happen?

Device not available for long term statistic

### How to reproduce it (minimal and precise)

Connect the device and try to add it in the energy tab

### Zigbee2MQTT version

1.26.0-1

### Adapter firmware version

003e

### Adapter

Legrand 412015

**Comment by shanelord01** [comment]
I use this excellent HACS Add-on called Powercalc to handle this. Highly recommended.

https://github.com/bramstroker/homeassistant-powercalc
