### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by yaniv1111** [Koenkk/zigbee2mqtt#1319]
I'm building a new mqtt2zigbee server and got this error while comping npm install.

root@mqtt:/opt/zigbee2mqtt# npm audit fix

> @serialport/bindings@2.0.7 install /opt/zigbee2mqtt/node_modules/cc-znp/node_modules/serialport/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=arm platform=linux)
make: Entering directory '/opt/zigbee2mqtt/node_modules/cc-znp/node_modules/serialport/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:41:75: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value path(Nan::To<v8::String>(info[0]).ToLocalChecked());
                                                                           ^
In file included from /root/.node-gyp/10.15.3/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../../../../nan/nan.h:53,
                 from ../src/./serialport.h:6,
                 from ../src/serialport.cpp:1:
/root/.node-gyp/10.15.3/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.15.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
  CXX(target) Release/obj.target/bindings/src/poller.o
  CXX(target) Release/obj.target/bindings/src/serialport_linux.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/opt/zigbee2mqtt/node_modules/cc-znp/node_modules/serialport/node_modules/@serialport/bindings/build'
removed 52 packages and moved 2 packages in 39.037s
fixed 0 of 3 vulnerabilities in 2344 scanned packages
  3 vulnerabilities required manual review and could not be updated

**Comment by Koenkk** [comment]
It's not an error but a warning of the compilation of one of the dependencies, nothing to worry about :smile:
