### ISSUE TITLE
Reading battery status issue for Woox R7060

### ISSUE THREAD

**Issue by RobsonAutomator** [Koenkk/zigbee2mqtt#13208]
### What happened?

Hello,
I'm using the following devices https://www.zigbee2mqtt.io/devices/R7060.html
Devices are properly recognized and added to Home Assistant but there is an issue with the battery data. 
I see the following logs:
Zigbee2MQTT:warn  2022-07-19 12:56:19: zigbee-herdsman-converters:WooxR7060: Unrecognized DP #107 with data {"dp":107,"datatype":4,"data":{"type":"Buffer","data":[0]}}
Zigbee2MQTT:warn  2022-07-19 12:56:19: zigbee-herdsman-converters:WooxR7060: Unrecognized DP #106 with data {"dp":106,"datatype":3,"data":{"type":"Buffer","data":[48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48]}}

### What did you expect to happen?

I want to have a proper battery information.

### How to reproduce it (minimal and precise)

Probably you need my devices :(

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

### Debug log

Zigbee2MQTT:info  2022-07-19 12:56:19: MQTT publish: topic 'zigbee2mqtt/zaworekA', payload '{"battery":null,"linkquality":135,"state":"OFF"}'
Zigbee2MQTT:info  2022-07-19 12:56:19: MQTT publish: topic 'zigbee2mqtt/zaworekA', payload '{"battery":null,"linkquality":143,"state":"OFF"}'
Zigbee2MQTT:warn  2022-07-19 12:56:19: zigbee-herdsman-converters:WooxR7060: Unrecognized DP #107 with data {"dp":107,"datatype":4,"data":{"type":"Buffer","data":[0]}}
Zigbee2MQTT:warn  2022-07-19 12:56:19: zigbee-herdsman-converters:WooxR7060: Unrecognized DP #106 with data {"dp":106,"datatype":3,"data":{"type":"Buffer","data":[48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48]}}

**Comment by ytzelf** [comment]
Have you seen #12163 ? The latest converter there reports accurate battery level for my devices
