### ISSUE TITLE
Router added via external_converters cannot be used by other devices

### ISSUE THREAD

**Issue by sejbr** [Koenkk/zigbee2mqtt#13201]
### What happened?

I've added Aeotec Range Extender Zi to my network and added a new external_converters listing.
```js
const definition = {
    zigbeeModel: ['WG001-Z01'],
    model: 'WG001-Z01',
    vendor: 'Aeotec',
    description: 'Range Extender Zi (Router)',
    fromZigbee: [fz.linkquality_from_basic],
    toZigbee: [],
    exposes: [],
};
```
The device is being recognized as a Router 
![image](https://user-images.githubusercontent.com/6895093/179618455-149c58b0-2216-4b43-946e-6bf5463aaef0.png)
but when I try to pair a Xiaomi Aqara sensor - it either connects to the coordinator or doesn't connect to anything?
What I mean by doesn't connect - It is visible in the devices listing with LQI which would suggest it used the router but it does not expose any clusters and no info from it is available.
![image](https://user-images.githubusercontent.com/6895093/179620741-8ad03dbe-4721-4075-9d4e-94830a53a212.png)
![image](https://user-images.githubusercontent.com/6895093/179620709-a41e872f-d76d-4725-aca6-4fb45201df70.png)
It also does not link to the router on the map and does not respond to any dev console reads:
![image](https://user-images.githubusercontent.com/6895093/179618368-b34025fe-cb2a-479b-b349-0d03724af81c.png)

Any way to fix this? Is it an issue with the range extender not being officially supported? Should I have used some specific router configuration in the device definition?

On a side note, I've noticed that the extender model listed on Z2M does not match official model listing nor does it match the model printed on the device itself https://device.report/aeotec/zga001-c15
When I tried adding the converter with correct model it did not get recognized. Not sure if that matters at all.

I am using the Home Assistant OS with Z2M addon.

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20210708

### Adapter

Sonoff ZigBee CC2652P

### Debug log

[z2m.log](https://github.com/Koenkk/zigbee2mqtt/files/9135853/z2m.log)

**Comment by sejbr** [comment]
Do you mean to remove the router, force remove the sensor, restart z2m and pair the sensor without the router in the network?
I believe I tried that but here are a few retries

1. 
- Router removed, Xiaomi force removed and reset via battery removal
- Rebooted Z2M addon
- Enabled pairing and paired xiaomi without the router present in the network
![image](https://user-images.githubusercontent.com/6895093/179808370-b0948e4f-cc36-4895-a55a-b8a92fd8049f.png)
2. 
- Router removed, Xiaomi force removed and reset via battery removal
- Rebooted Z2M addon
- Enabled pairing
- Readded router and paired xiaomi with close proximity to the router
![image](https://user-images.githubusercontent.com/6895093/179809639-b16168d4-d541-40bc-b86b-2c0ef1c28f09.png)
3. 
- Router removed, Xiaomi force removed and reset via battery removal
- Rebooted Z2M addon
- Enabled pairing
- Readded router and paired xiaomi with close proximity to the coordinator
![image](https://user-images.githubusercontent.com/6895093/179810289-7ce9979f-4e2e-4dd6-8109-e36010f37e8e.png)
4.
- Router removed, xiaomi force removed and reset via battery removal
- Removed my external_converter for the router
- Rebooted Z2M addon
- Enabled pairing
- Readded router - now it is still recognized as a router but I get the unsupported notification with the "Add support" documentation link
- Paired xiaomi with close proximity to the router
- Same result as map from # 3. The sensor connected to the coordinator instead of the router despite being 6m from the coordinator and only a few cm from the router.

I'm not sure what else to try. I also assumed as you've said that the router should run out of the box with Z2M hence I bought it instead of other devices for which I have no use for the time being.

**Comment by Koenkk** [comment]
Can you provide the debug log when the network map is made?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by sejbr** [comment]
Ah sorry, sure
1. 
[z2m1.txt](https://github.com/Koenkk/zigbee2mqtt/files/9143783/z2m1.txt)

2. 
[z2m2.txt](https://github.com/Koenkk/zigbee2mqtt/files/9143982/z2m2.txt)

4.
[z2m4.txt](https://github.com/Koenkk/zigbee2mqtt/files/9143827/z2m4.txt)

It took a while so I did not try recreating # 3 since it was pretty much the same as 2 only with me being closer to coordinator.
Also in 4 I had some trouble pairing the sensor correctly so there were a few more tries during that one. But each of these logs ends up with the same map.

**Comment by Koenkk** [comment]
I expect that something is wrong in the router firmware which makes it not return all neighbours. The xiaomi device should definitely be there shortly after pairing. Anyway, it is not something to worry about, most Xiaomi devices will appear unconnected after some time, see https://www.zigbee2mqtt.io/guide/faq/#why-are-some-links-missing-from-my-networkmap

**Comment by Koenkk** [comment]
> but I assume that despite not being shown correctly on the map, the sensor should still reply to read queries and report it's state

Read queries won't work but state reporting should. 

> State json is empty, and the clusters information does not list anything

The reason for this is that Xiaomi devices are tricky to interview, they sleep to early which causes z2m to not gather all info. That doesn't affect the sensor functionality.

> State json returns basic device information, nothing sensor specific

Can you try triggering a state update by e.g. blowing in the sensor? If that doesn't help I need to have a sniff when the sensor sends a data update. https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

**Comment by sejbr** [comment]
> The reason for this is that Xiaomi devices are tricky to interview, they sleep to early which causes z2m to not gather all info. That doesn't affect the sensor functionality.

If by that you mean that it should still report state changes and being readable in something like nodered - it wasn't. Nothing in HA could read anything from it.

I might be a bit early on that but an hour ago I have finaly had time to mess around a bit, flashed tasmota on a sonoff zbbridge and set it as a router. The sensor paired to it on my second try and so far, after a few tries I see that state is somewhat updated (relevant info like vibration, sensitivity and linkquality are available), and these states can be used in nodered with no issue.

It looks like that was really an Aeotec router issue. With the tasmota flashed sonoff zbbridge even the map is rendered correctly
![image](https://user-images.githubusercontent.com/6895093/182048500-7facd539-67c1-4145-9b5a-6473b2417552.png)

I think the issue can be closed. It will be a while before I'll be able to spare some more time to this especially with the more complicated things you'd require to push this towards a resolution. I might check what board is inside that router, maybe it uses a decent board and could be flashed with better software or something.
