### ISSUE TITLE
state inconsistency when turning Osram bulb off using brightness parameter

### ISSUE THREAD

**Issue by thewilli** [Koenkk/zigbee2mqtt#1321]
> Environment: 
> * zigbee2mqtt Docker container tag 1.2.1
> * CC2531 firmware: CC2531ZNP-Prod_20190223.zip

If I send a message`{ "brightness" : 0}` to the control topic of an OSRAM Smart+ bulb (model: `Classic A60 W clear - LIGHTIFY`), it turns off. That is not only expected but comes in handy when I want to bind a *virtual dimmer* in a Smart Home automation software to that property.
 
The bulb does not only turn off, but a new state message is sent:

```json
{"state":"ON","linkquality":65,"brightness":1}
```
I think that's very confusing, especially as setting a `brightness` of 1 does not turn the bulb off but set it to its lowest brightness. Therefore, the reported and actual state do not correspond. I would have expected that either `state` becomes `OFF`, or `brightness` remains `0` as long as the bulb is actually off.

**Comment by user1o1** [comment]
I have exactly the same problem even on the latest dev branch
