### ISSUE TITLE
TS011F_plug_1 not reporting power anymore

### ISSUE THREAD

**Issue by niekveldhuizen** [Koenkk/zigbee2mqtt#13222]
### What happened?

Hi,

I have multiple of the TS011F plugs (all plug_1 versions.) and one stoped reporting power. The Power/Current/Voltage all stay at 0.

The on off function is working and indicator_mode/lqi are also working fine. Tryed removing and pairing again, still no Power/Current/Voltage. Is this a sofware issue or is the plug just broken?

Other plugs (the same one) all stil work fine.

Manufacturer: _TZ3000_mraovvmm

### What did you expect to happen?

I expect it to send Power/Current/Voltage info

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20210708

### Adapter

zStack3x0

**Comment by malosaa** [comment]
Buy the round ones

**Comment by gyrex** [comment]
I have the same issue. Bought Australian plugs from a seller on Aliexpress: https://trade.aliexpress.com/order_detail.htm?orderId=8153763973618261

Current and voltage is being reported but power usage is 0W despite there being 0.13A of current being measured @ 240V.

Database entry:

`{"id":6,"type":"Router","ieeeAddr":"0xa4c138cf5e6f6532","nwkAddr":37648,"manufId":4417,"manufName":"_TZ3000_typdpbpg","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�Ւ*\u0003","65506":54,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_typdpbpg","powerSource":1,"zclVersion":3,"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":239,"rmsCurrent":137,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,2]}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":3850787,"53251":124,"53252":7366,"53253":934,"powerOnBehavior":0,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1798312590},"lastSeen":1660971938850,"defaultSendRequestWhen":"immediate"}`

**Comment by malosaa** [comment]
Yes, lets hope there will be a fix for that

**Comment by manny199** [comment]
Same problem, anyone resolved power 0 issue?

**Comment by niekveldhuizen** [comment]
> Same problem, anyone resolved power 0 issue?

For me still no solution. I am using this specific plug now for on off purpose only.

**Comment by manny199** [comment]
> > Same problem, anyone resolved power 0 issue?
> 
> For me still no solution. I am using this specific plug now for on off purpose only.

thank you, Do you think this is a problem that could be solved with a new future blitzwolf firmware?
In the meantime I ask you if you know another plug that detects the consumption of 2 or 3 watts well

**Comment by malosaa** [comment]
For my plugs not even 1 power off problem for weeks.

But that silly 0 watt problem needs to be solved, and i'm pretty sure it can be done within Z2M software.
As tuya doesnt report that 0 watt issue.. so it's within Z2M

**Comment by manny199** [comment]
> For my plugs not even 1 power off problem for weeks.
> 
> But that silly 0 watt problem needs to be solved, and i'm pretty sure it can be done within Z2M software. As tuya doesnt report that 0 watt issue.. so it's within Z2M

Should try with a tuya hub that I don't have.  Has anyone done the test with hub other than z2m, if it shows 0 watt problem?

**Comment by jontofront** [comment]
same problem :(

**Comment by malosaa** [comment]
Well i gonna order a couple and try with the tuya hub,   stay tuned.
I will report here soon.

But depending on the holidays it could take longer before i receive the new ones.
I will order from different suppliers. 

regards

**Comment by MoonLiightz** [comment]
I have the same problem, has anyone found out anything new?

**Comment by MoonLiightz** [comment]
I think this issue is still relevant and should not be closed.

**Comment by mikedm139** [comment]
I'm also seeing no power monitoring reported for my plug which is identified as TS011F_plug_1. It only shows as "null".

<details>
<summary>database entry</summary>

{"id":14,"type":"Router","ieeeAddr":"0x70b3d52b6001b0fb","nwkAddr":27250,"manufId":4660,"manufName":"_TZ3000_okaz9tjs","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,6,3,4,5,57345,2820,1794],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":3,"dateCode":"20210625","swBuildId":"20B+TZSKT11BS108","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1680897485595,"defaultSendRequestWhen":"immediate"}

</details>
<details>
<summary>State json</summary>

{
    "child_lock": "UNLOCK",
    "last_seen": 1680899901520,
    "linkquality": 51,
    "state": "OFF",
    "current": null,
    "energy": null,
    "indicator_mode": null,
    "power": null,
    "power_outage_memory": null,
    "update": {
        "state": null
    },
    "update_available": null,
    "voltage": null
}
</details>

<details>
<summary>Captured some debug logging</summary

2023-04-07 14:38:21Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genBasic', data '{"appVersion":100}' from endpoint 1 with groupID 0
2023-04-07 14:43:59Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genBasic', data '{"appVersion":100}' from endpoint 1 with groupID 0
2023-04-07 14:44:53Received MQTT message on 'zigbee2mqtt/Coffee Maker/set' with data '{"state":"ON"}'
2023-04-07 14:44:53Publishing 'set' 'state' to 'Coffee Maker'
2023-04-07 14:44:53Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
2023-04-07 14:45:05Received MQTT message on 'zigbee2mqtt/Coffee Maker/set' with data '{"power_outage_memory":"restore"}'
2023-04-07 14:45:05Publishing 'set' 'power_outage_memory' to 'Coffee Maker'
2023-04-07 14:45:06Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genOnOff', data '{"moesStartUpOnOff":2}' from endpoint 1 with groupID 0
2023-04-07 14:45:06Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'manuSpecificTuya_3', data '{"powerOnBehavior":2}' from endpoint 1 with groupID 0
2023-04-07 14:45:12Received MQTT message on 'zigbee2mqtt/Coffee Maker/set' with data '{"indicator_mode":"off/on"}'
2023-04-07 14:45:12Publishing 'set' 'indicator_mode' to 'Coffee Maker'
2023-04-07 14:45:12Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genOnOff', data '{"tuyaBacklightMode":1}' from endpoint 1 with groupID 0
2023-04-07 14:45:15Received MQTT message on 'zigbee2mqtt/Coffee Maker/set' with data '{"indicator_mode":"on/off"}'
2023-04-07 14:45:15Publishing 'set' 'indicator_mode' to 'Coffee Maker'
2023-04-07 14:45:15Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genOnOff', data '{"tuyaBacklightMode":2}' from endpoint 1 with groupID 0
2023-04-07 14:49:42Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genBasic', data '{"appVersion":100}' from endpoint 1 with groupID 0
2023-04-07 14:55:30Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genBasic', data '{"appVersion":100}' from endpoint 1 with groupID 0
2023-04-07 14:59:25Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,1]}' from endpoint 1 with groupID 0
2023-04-07 15:01:18Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'genBasic', data '{"appVersion":100}' from endpoint 1 with groupID 0
</details>

I think that this line is perhaps most relevant...
```
2023-04-07 14:59:25Received Zigbee message from 'Coffee Maker', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,1]}' from endpoint 1 with groupID 0
```

Not exactly sure where to go from here though.

**Comment by mikedm139** [comment]
As noted in my previous comment, I recently got one of these TS011F_plug_1 devices. The box is actually labelled "BSD20W-US-POWER-20A" as it is a US style 20A plug with power monitoring. [Aliexpress link.](https://www.aliexpress.com/item/1005004049920059.html) On first and subsequent (re)pairing it identified as TS011F_plug_1. Throughout that process, no matter how long I left something drawing power, the power, current, voltage, and energy were all reported as either "null" or "N/A". When I added the zigbee-herdsman debug command to my Z2M docker container and restarted it, the plug was then identified as TS011F_plug_3 and it started reporting power properly.

Prior to enabling debug logging for zigbee-herdsman I tried removing and repairing the plug as well as adding flags for `measurement_poll_interval` (as well as `voltage_precision`, `current_precision` and `power_precision`) to my configuration.yaml. To make sure the change in the config was picked up I did restart Z2M using the button in the UI (Settings > Tools > Restart Zigbee2MQTT). <details><summary>configuration.yaml entry</summary>

```
'0x70b3d52b6001b0fb':
    friendly_name: Coffee Maker
    description: Tuya smart plug from AliExpress attached to kitchen coffee maker.
    voltage_calibration: 0
    voltage_precision: 2
    current_calibration: 0
    current_precision: 2
    power_calibration: 0
    power_precision: 2
    measurement_poll_interval: 1
```
</details>

<details>
<summary>Here is the database entry of the same plug in it's working configuration. As compared to the non-power-reporting configuration shown in my previous comment.</summary>

{"id":14,"type":"Router","ieeeAddr":"0x70b3d52b6001b0fb","nwkAddr":27250,"manufId":4660,"manufName":"_TZ3000_okaz9tjs","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,6,3,4,5,57345,2820,1794],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"32768":0,"onOff":1,"moesStartUpOnOff":2,"tuyaBacklightMode":2}},"genBasic":{"attributes":{"appVersion":100,"manufacturerName":"_TZ3000_okaz9tjs","zclVersion":2,"modelId":"TS011F","powerSource":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}},"seMetering":{"attributes":{"currentSummDelivered":[0,8],"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":118,"rmsCurrent":348,"activePower":42,"acCurrentDivisor":1000,"acCurrentMultiplier":1}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c83671","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":3,"dateCode":"20210625","swBuildId":"20B+TZSKT11BS108","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2123427102},"lastSeen":1680920961734,"defaultSendRequestWhen":"immediate"}
</details>

It still isn't perfect as Z2M seems to have trouble identifying the firmware and thus is an update is available. However, as long as it works as I need it to, I'm not to concerned about that.

At this point, I'm not sure if the change in behaviour has anything to do with enabling debug logging for zigbee-herdsman (seems unlikely) or rather the full recreation of the container that was necessary to do so. My next step is going to be to disable debug logging on the zigbee-herdsman which will again require recreating the container. Hopefully, the power reporting will continue to work. I will update again after some testing.

**Comment by mikedm139** [comment]
Following removal of the `-e DEBUG=zigbee-herdsman*` from the docker container and recreating it, the plug is still identified as TS011F_plug_3 and power reporting seems to be working. Not sure if that means that my issue was different from others but hopefully this helps someone either with their own issues or finding the bug that leads to this odd behaviour.

**Comment by Aasikki** [comment]
I reported a similar issue with a Girier plug that gets detected as TuYa TS011F_plug_3 #17319
With this plug, it stops reporting after being unplugged and plugged back in, but also randomly. After restarting z2m it immediately starts working again.

**Comment by mikedm139** [comment]
> Following removal of the `-e DEBUG=zigbee-herdsman*` from the docker container and recreating it, the plug is still identified as TS011F_plug_3 and power reporting seems to be working. Not sure if that means that my issue was different from others but hopefully this helps someone either with their own issues or finding the bug that leads to this odd behaviour.

Oddly enough, the plug completely died a day later. Doesn't pass power through, not responsive to Z2M, no response to the physical button. I'm currently trying to arrange a replacement from the AliExpress seller. I doubt it has anything to do with the other issues and I certainly didn't overload the plug as it's (supposedly) rated for 20 amps and I just had my kitchen coffee maker attached which has been running happily with other appliances on a shared 15amp circuit.

**Comment by vahaldor** [comment]
Same here. However,  I have been using eight of these plugs throughout my house and all of them began having this issue in one moment. What triggered it is beyond my knowledge but I found out that e.g. when dish washer finishes it's cycle, the plug is stuck at 70W while there is no consumption, energy sensor is not increasing. The others do the same. I have TuYa TS011F_plug_1

**Comment by TangoJoker** [comment]
+1 Same issue.

**Comment by machintrucbidule** [comment]
> I have the same issue. Bought Australian plugs from a seller on Aliexpress: https://trade.aliexpress.com/order_detail.htm?orderId=8153763973618261
> 
> Current and voltage is being reported but power usage is 0W despite there being 0.13A of current being measured @ 240V.
> 
> Device is being reported as plug_1. Screenshot of device info from zigbee2mqtt: https://imgur.com/a/Mdf5TOa
> 
> Database entry:
> 
> `{"id":6,"type":"Router","ieeeAddr":"0xa4c138cf5e6f6532","nwkAddr":37648,"manufId":4417,"manufName":"_TZ3000_typdpbpg","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�Ւ*\u0003","65506":54,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_typdpbpg","powerSource":1,"zclVersion":3,"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":239,"rmsCurrent":137,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,2]}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":3850787,"53251":124,"53252":7366,"53253":934,"powerOnBehavior":0,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c6d1b6","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1798312590},"lastSeen":1660971938850,"defaultSendRequestWhen":"immediate"}`

Exact same issue here too

**Comment by sereda-oleg** [comment]
+1 Same issue

**Comment by Koenkk** [comment]
Please provide the stdout when using the ext converter mentioned here https://github.com/Koenkk/zigbee2mqtt/issues/16709

**Comment by machintrucbidule** [comment]
I tried the fix, but no change, and nothing in zigbee2mqtt logs (is that what you meant by stdout?).
But I'm not sure this fix was for the same issue: if I understand well the fix was to wait 5s after a power reported to 0 to ensure consistent readings. While the issue raised by gyrex, and which I'm facing too, is current and voltage correctly, but Power falsely set to 0 :
![image](https://github.com/Koenkk/zigbee2mqtt/assets/75478334/e32e22c8-23e5-44a3-b5cf-3bd4d1ce9928)
Here Power should be around 14W?

**Comment by gianlucasullazzo** [comment]
Hi, same for me:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/75364722/8a5240e5-9d11-4ad5-b159-e6583b9f49f3)
An echo dot is plugged on, so at least 3/4 W.

**Comment by IngAley** [comment]
Same problem here, and I have already the round ones. Is there already a solution by now? 
Here "Voltage" and "sum of consumed energy" is shown, but the rest not... :-(

**Comment by ingoratsdorf** [comment]
I have the same TS011F_plug_1 that just stopped reporting power. Everything else worked okay, current, energy, everything else worked, just not power.
I connected the troublesome plug to a Tuya zigbee gateway and there power reporting works.
So my conclusion is that this is a software issue, not a hardware issue.
Tuya app screenshots attached:

![Screenshot_20240411_091922_Smart Life](https://github.com/Koenkk/zigbee2mqtt/assets/3344778/bce8705d-4638-4cfc-9efb-f7d2ec283315)
![Screenshot_20240411_092243_Smart Life](https://github.com/Koenkk/zigbee2mqtt/assets/3344778/0affb820-34fb-4ea2-ba38-0bed3f56941d)

Reconnected plug to Z2M:

Autogenerated external converter for info:

```
const {identify, onOff, electricityMeter} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS011F'],
    model: 'TS011F',
    vendor: '_TZ3000_typdpbpg',
    description: 'Automatically generated definition',
    extend: [identify(), onOff({"powerOnBehavior":false}), electricityMeter()],
    meta: {},
};

module.exports = definition;
```

Database info:

`{"id":38,"type":"Router","ieeeAddr":"0xa4c138dc17dcd096","nwkAddr":12992,"manufId":4417,"manufName":"_TZ3000_typdpbpg","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_typdpbpg","zclVersion":3,"appVersion":192,"modelId":"TS011F","powerSource":1}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":2000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffeb1caf7","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffeb1caf7","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffeb1caf7","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5,"manufacturerCode":null},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50,"manufacturerCode":null},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1],"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1712784333782}`

Screen shot at same power use as it was for the Tuya app:

![Screenshot 2024-04-11 093039](https://github.com/Koenkk/zigbee2mqtt/assets/3344778/990c9918-1686-453f-8252-3f080d06b6d1)

Result: No reporting of power.

**Comment by kanzie** [comment]
Same problem here. It stopped reporting data and is now on top of that randomly shutting off. This has happened to three of my plugs, all at around the same time. They are useless now

**Comment by nukleuz80** [comment]
Same issue here with 3 of 5 Plugs i‘m using… mhhh

**Comment by kajmaj** [comment]
After the plug (TS011F_plug) update to the latest FW everything seems to be working.

**Comment by gianlucasullazzo** [comment]
Hi @kajmaj what FW version do you have?
Thanks

**Comment by kajmaj** [comment]
Hi @gianlucasullazzo I wish I could tell you, but it is not displayed in Z2M dashboard. I received related plugs today, freshly paired with z2m and current/power was 0, no matter if connected 100W testing bulb was powered or not. I went to z2m OTA  check upgrades, it offered upgrade>>confirmed>>wait approx 15 mins>>upgrade done >> now all new plugs measure all as it should. I could try to verify FW version via tuya app, but on Wed the soonest.

**Comment by gianlucasullazzo** [comment]
Ok, also for me it's not displayed. Are your plugs like this?
![image](https://github.com/user-attachments/assets/db79acd5-9405-45e4-9e9e-346f7ae3bfc2)

**Comment by kajmaj** [comment]
[![image](https://github.com/user-attachments/assets/b3e5cf1d-16fa-4059-8e25-6ccd9c3077dc)](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)

**Comment by gianlucasullazzo** [comment]
ok..mine are the "oranges" one but they are recognized as TS011F_plug_1 as well. Unfortunately no OTA available at the moment.

**Comment by hvandervegt** [comment]
Please can any body conform that for this device in the reporting tab changing "Minimum reporting change" to 0 zero brings back power measurements ? 
For meaning of this setting is explained in
https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request
What could be the impact this setting to 0, will it gave some stress in the zigbee communication ?

**Comment by gianlucasullazzo** [comment]
> Please can any body conform that for this device in the reporting tab changing "Minimum reporting change" to 0 zero brings back power measurements ? For meaning of this setting is explained in https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request What could be the impact this setting to 0, will it gave some stress in the zigbee communication ?

I'm not able ti change to 0 via UI. After switching back to reporting tab, It reset to 5 again. No errore log.

**Comment by hvandervegt** [comment]
After the change I see twee power entry rows , one as the original entry and one with the new value
![powermodification](https://github.com/user-attachments/assets/c4a4d3c7-aa84-40aa-852b-3bdf347d3425)
Then also after a reboot the result is perfect
![powerbeforeandafter](https://github.com/user-attachments/assets/4919b43c-a1e3-4dbf-a716-188101b7cf81)

**Comment by AbelLykens** [comment]
Added that setting, will let you know what happens!

**Comment by pedroan8** [comment]
> After the change I see twee power entry rows , one as the original entry and one with the new value ![powermodification](https://private-user-images.githubusercontent.com/149686023/393499774-c4a4d3c7-aa84-40aa-852b-3bdf347d3425.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgxMzUsIm5iZiI6MTczNDUwNzgzNSwicGF0aCI6Ii8xNDk2ODYwMjMvMzkzNDk5Nzc0LWM0YTRkM2M3LWFhODQtNDBhYS04NTJiLTNiZGYzNDdkMzQyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNzQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGE2MWUyMjA0ZjllOGYxYmMyNGE0MzA2NWU4MjVmZjZlZjU1MGQzMTgyMTg4Y2FiMDcyMThiNmY2ZjIwYzVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h9NnARZLYkDTCVwAMa0ahmym2hvPLrQRIIkP-av3cYc) Then also after a reboot the result is perfect ![powerbeforeandafter](https://private-user-images.githubusercontent.com/149686023/393499848-4919b43c-a1e3-4dbf-a716-188101b7cf81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgxMzUsIm5iZiI6MTczNDUwNzgzNSwicGF0aCI6Ii8xNDk2ODYwMjMvMzkzNDk5ODQ4LTQ5MTliNDNjLWExZTMtNGRiZi1hNzE2LTE4ODEwMWI3Y2Y4MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNzQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzk3MGIwNmE1Mjg2NzhlNDc0ZjM5MWExYzAwZDlkODNiODVkOTU0ZjgxOTM1YjJlYzBiMWE1NDI4NTNlYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rMzj8XZs9IvsRjqqNYfpvIZko3BWcgTuNPB5zNZIjDI)

Worked for me fine! THX (Orange round plug)

**Comment by radry** [comment]
@hvandervegt 

This worked but there is no decimal point precision, only integer values.

**Comment by tonyschuite** [comment]
to add some extra info: I had a comparable issue. however after playing with the precision settings (set to 3) it started working.
