### ISSUE TITLE
[New device support]: Tuya plug BR 16 A - TS011F manufacturer _TZ3000_5f43h46b

### ISSUE THREAD

**Issue by rodrigorsdev** [Koenkk/zigbee2mqtt#13236]
### Link

https://pt.aliexpress.com/item/1005003059126398.html?spm=a2g0o.order_list.0.0.66cccaa49GfB6c&gatewayAdapt=glo2bra

### Database entry

{"id":43,"type":"Router","ieeeAddr":"0xa4c138ef106afdae","nwkAddr":5435,"manufId":4417,"manufName":"_TZ3000_5f43h46b","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_5f43h46b","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1658436237362}

### Comments

I tried to create external converter but no success

**Comment by Koenkk** [comment]
`_TZ3000_5f43h46b` is already supported

**Comment by rodrigorsdev** [comment]
![image](https://user-images.githubusercontent.com/5364277/180317811-d25f2658-b002-4809-92ed-7f0931a70021.png)

Status unsupported, theres something can I do?

**Comment by Koenkk** [comment]
What z2m version are you using?

**Comment by rodrigorsdev** [comment]
![IMG_20220723_193401.jpg](https://user-images.githubusercontent.com/5364277/180625081-d85f3b45-68e2-46c9-ade6-ba6fad32ff64.jpg)

**Comment by Koenkk** [comment]
If you are still on 1.18.1 check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
