### ISSUE TITLE
IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (LED1924G9) not pairing / throwing Errors

### ISSUE THREAD

**Issue by lephisto** [Koenkk/zigbee2mqtt#13231]
### What happened?

I Just got a set of Tradfri E27 Bulbs, they didn't pair with my supercheap CC2531 adapter. Just to be sure I replaced it with a Conbee II, still, it refuses to pair properly. Sometimes, after 1-2 Days, it starts to appear as paired, but refuses to take commands.

I also tried to pair it right next to the Conbee stick. Same behaviour. I also put the Conbee on a USB extension to avoid any intererence with the Raspberry Pi it's connected to.

### What did you expect to happen?

I would expect the bulb to pair flawless. 

### How to reproduce it (minimal and precise)

Get a IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (LED1924G9), try to pair it.

### Zigbee2MQTT version

1.26.0-dev (commit #4ef9ea7)

### Adapter firmware version

Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x2672070 0","transportrev":0},"type":"ConBee2/RaspBee2"}'

### Adapter

Conbee 2

### Debug log

This is how Pairing requests look like initially:

`zigbee2mqtt    | Zigbee2MQTT:info  2022-07-19 19:36:08: Starting interview of '0x2c1165fffebc91cf'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-19 19:36:08: MQTT publish: topic 'zigbee2mqtt-space/bridge/event', payload '{"data":{"friendly_name":"0x2c1165fffebc91cf","ieee_address":"0x2c1165fffebc91cf","status":"started"},"type":"device_interview"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-19 19:36:08: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:error 2022-07-19 19:37:10: Failed to interview '0x2c1165fffebc91cf', device has not successfully been paired
`

After some time it looks like:

`
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:24:18: Starting interview of '0x2c1165fffebc91cf'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:24:18: MQTT publish: topic 'zigbee2mqtt-space/bridge/event', payload '{"data":{"friendly_name":"0x2c1165fffebc91cf","ieee_address":"0x2c1165fffebc91cf","status":"started"},"type":"device_interview"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:24:18: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:error 2022-07-20 07:26:19: Failed to interview '0x2c1165fffebc91cf', device has not successfully been paired
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:26:19: MQTT publish: topic 'zigbee2mqtt-space/bridge/event', payload '{"data":{"friendly_name":"0x2c1165fffebc91cf","ieee_address":"0x2c1165fffebc91cf","status":"failed"},"type":"device_interview"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:26:19: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:33:11: Starting interview of '0x2c1165fffebc91cf'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:33:11: MQTT publish: topic 'zigbee2mqtt-space/bridge/event', payload '{"data":{"friendly_name":"0x2c1165fffebc91cf","ieee_address":"0x2c1165fffebc91cf","status":"started"},"type":"device_interview"}'
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:33:11: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"pairing"}'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:11: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:11: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"appVersion":80}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:12: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"stackVersion":101}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:12: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:12: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"dateCode":"2019062886LEL08N"}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-20 07:33:12: Received Zigbee message from '0x2c1165fffebc91cf', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"1.0.021"}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:33:12: Successfully interviewed '0x2c1165fffebc91cf', device has successfully been paired
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-20 07:33:12: Device '0x2c1165fffebc91cf' is supported, identified as: IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (LED1924G9)
`

Still, when trying to issue a command it looks like:

`
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:33:04: Received MQTT message on 'zigbee2mqtt-space/0x2c1165fffebc91cf/set' with data '{"state":"ON"}'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:33:04: Publishing 'set' 'state' to '0x2c1165fffebc91cf'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:33:08: Received MQTT message on 'zigbee2mqtt-space/0x2c1165fffebc91cf/set' with data '{"state":"OFF"}'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:33:08: Publishing 'set' 'state' to '0x2c1165fffebc91cf'
zigbee2mqtt    | Zigbee2MQTT:error 2022-07-21 15:34:05: Publish 'set' 'state' to '0x2c1165fffebc91cf' failed: 'Error: Command 0x2c1165fffebc91cf/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:05: Error: Command 0x2c1165fffebc91cf/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-21 15:34:05: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x2c1165fffebc91cf' failed: 'Error: Command 0x2c1165fffebc91cf/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"zigbee_publish_error"}'
zigbee2mqtt    | Zigbee2MQTT:error 2022-07-21 15:34:09: Publish 'set' 'state' to '0x2c1165fffebc91cf' failed: 'Error: Command 0x2c1165fffebc91cf/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:09: Error: Command 0x2c1165fffebc91cf/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)
zigbee2mqtt    | Zigbee2MQTT:info  2022-07-21 15:34:09: MQTT publish: topic 'zigbee2mqtt-space/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x2c1165fffebc91cf' failed: 'Error: Command 0x2c1165fffebc91cf/1 genOnOff.off({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"0x2c1165fffebc91cf"},"type":"zigbee_publish_error"}'
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:41: Received Zigbee message from '0x2c1165fffebc91cf', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":268572245,"imageType":10242,"manufacturerCode":4476}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:41: Device '0x2c1165fffebc91cf' requested OTA
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:47: Received Zigbee message from '0x2c1165fffebc91cf', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":268572245,"imageType":10242,"manufacturerCode":4476}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:47: Device '0x2c1165fffebc91cf' requested OTA
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:50: Received Zigbee message from '0x2c1165fffebc91cf', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":268572245,"imageType":10242,"manufacturerCode":4476}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:50: Device '0x2c1165fffebc91cf' requested OTA
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:53: Received Zigbee message from '0x2c1165fffebc91cf', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":268572245,"imageType":10242,"manufacturerCode":4476}' from endpoint 1 with groupID null
zigbee2mqtt    | Zigbee2MQTT:debug 2022-07-21 15:34:53: Device '0x2c1165fffebc91cf' requested OTA
`

**Comment by maxi1134** [comment]
I have this same problem..

Did anyone ever found a solution?

I just tried pairing 3 bulbs and they pair but I lose control on them a few minutes after that
