### ISSUE TITLE
IKEA E1524 without battery information?

### ISSUE THREAD

**Issue by Maik-100** [Koenkk/zigbee2mqtt#1324]
In payload of IKEA E1524 are information about pressing the buttons.
Other sensors sends information about the battery state. In the MQTT log in the payload area, I am able to find infos for linkquality, but not for battery, why?

**Comment by Koenkk** [comment]
This should be reported after +- 1 day of uptime

**Comment by Maik-100** [comment]
What you mean with uptime?
My E1524 is peered for days per zigbee2mqtt to the MQTT-Brocker, but no battery state information.
Or is it importend that to the MQTT-Brocker is an application like Domotizz (with a plugin) is connected? The plugin gets support for E1524 today. So I had to update the plugin and to wait one or two days.

**Comment by Koenkk** [comment]
I've just checked, this has been recently added and is not in the release version yet. In case you want battery information you should switch to the dev branch (edge for hassio).

**Comment by jlo88** [comment]
I'm running edge and I see the battery level in the zigbee2mqtt logs but not in home assistant. I just switched to edge because I like this feature. Should I wait for one day of uptime of zigbee2mqtt or home assistant?
