### ISSUE TITLE
Ikea Tradfri Motion Sensor Timeout

### ISSUE THREAD

**Issue by SebastienLemayeur** [Koenkk/zigbee2mqtt#13259]
### What happened?

When setting the Ikea Motion Sensor Occupancy Timeout to 15 seconds, the sensor correctly sends the "off" event after 15 seconds. However, it then remains unresponsive for about 90 seconds to any new motion. So it seems like the default value of 90 seconds is still maintained somewhere and blocking the sensor from checking new motion.

### What did you expect to happen?

Setting the occupancy timeout should not only send the "off" event after the set amount of second but also enable the sensor to check for new motion.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

0x26780700

### Adapter

Conbee II

**Comment by Paladin1404** [comment]
You are talking about https://www.zigbee2mqtt.io/devices/E1525_E1745.html 
I had the same issue and finally I recognized that this is the default behavior of the device and can't be changed.
I brought them back to IKEA and switched to others.

It was already discussed 2019 e.g. here
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1676

Please note that there are 2 versions available and the "new" has this issue, the older was better.

I only know 2 motion sensors without those big delays.
1) https://www.zigbee2mqtt.io/devices/9290012607.html
  Disadvantage expensive.
2) https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html
  Hardware modification necessary but cheap. https://community.smartthings.com/t/making-xiaomi-motion-sensor-a-super-motion-sensor/139806
