### ISSUE TITLE
[New device support]: AUBESS TS0601 _TZE200_qyflbnbj Tuya ZigBee Smart Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by jrb5665** [Koenkk/zigbee2mqtt#13250]
### Link

https://www.aliexpress.com/item/1005004212078770.html?spm=a2g0o.detail.1000014.1.29224795oFjkzO&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.281175.0&scm_id=1007.40050.281175.0&scm-url=1007.40050.281175.0&pvid=e29fc883-e049-4d8e-832f-42caa3399dec&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.281175.0,pvid:e29fc883-e049-4d8e-832f-42caa3399dec,tpp_buckets:668%232846%238108%231977&pdp_ext_f=%7B%22sku_id%22%3A%2212000028396405011%22%2C%22sceneId%22%3A%2230050%22%7D&pdp_npi=2%40dis%21AUD%21%2160.0%21%21%21%21%21%400b89a67916585641763631991e4b6c%2112000028396405011%21rec

### Database entry

{"id":23,"type":"EndDevice","ieeeAddr":"0x8cf681fffeccd348","nwkAddr":1794,"manufId":4098,"manufName":"_TZE200_qyflbnbj","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"��n*\u0012��n*\u0012","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_qyflbnbj","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1658565085817,"defaultSendRequestWhen":"immediate"}

### Comments

This is the code I put in the tuya.js file to get it to work

    {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_qyflbnbj'},
            {modelID: 'TS0601', manufacturerName: '_TZE200_qyflbnbj'}],
        model: 'TS0601_temperature_humidity_sensor',
        vendor: 'TuYa',
        description: 'Temperature & humidity sensor',
        fromZigbee: [fz.tuya_temperature_humidity_sensor],
        toZigbee: [],
        exposes: [e.temperature(), e.humidity(), e.battery()],
    },

**Comment by Koenkk** [comment]
This device was already added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4408 and will be supported in the next z2m release.
