### ISSUE TITLE
[New device support]: TS011F _TZ3000_aim0ztek

### ISSUE THREAD

**Issue by Gugulator** [Koenkk/zigbee2mqtt#13251]
### Link

https://aliexpress.com/item/1005002679735460.html

### Database entry

{"id":26,"type":"Router","ieeeAddr":"0xa4c1384690f973a1","nwkAddr":37505,"manufId":4417,"manufName":"_TZ3000_aim0ztek","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_aim0ztek","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":1,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"powerOnBehavior":1,"switchType":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1658566082275,"defaultSendRequestWhen":"immediate"}

### Comments

This is switch for boiler to heating water, with power monitoring option.
Bought from LoraTap official store at AliExpress.
Works fine with Tuya/SmartHome systems.
Problem to complete setup in HA due to unsupported model/manufacturer.

Device type: Router
Zigbee Model: TS011F
Zigbee Manufacturer: _TZ3000_aim0ztek
IEEE Address: 0xa4c1384690f973a1
Network address: 0x9281

**Comment by Gugulator** [comment]
still not fixed in any system update...

**Comment by danieledwardgeorgehitchcock** [comment]
I'll have a look at this tomorrow. Can't promise anything though

**Comment by morhimi** [comment]
any chance this will be supported? right now the device is identified is a Plug
