### ISSUE TITLE
Aqarq smoke detector JY-GZ-01AQ device temperatur is 25°C

### ISSUE THREAD

**Issue by Danit2** [Koenkk/zigbee2mqtt#13253]
### What happened?

The device temperatur on this device is 25° and never change. This is also not the right temperatur.
![image](https://user-images.githubusercontent.com/71522810/180600788-4d38468a-ebbf-4d0f-8f79-743c6a65444d.png)

### What did you expect to happen?

Delete the device temperatur when it is not supportet or fix it. 

### Zigbee2MQTT version

 1.26.0

### Adapter firmware version

20211217

### Adapter

Sonoff CC2652P

**Comment by Otnow** [comment]
Unfortunately, when checking, it turned out that this detector really always reports the static value of `device_temperature` equal to 25 °C, so I created a [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4473) to remove `device_temperature` for it.
