### ISSUE TITLE
Two messages on response

### ISSUE THREAD

**Issue by pyxiscloud** [Koenkk/zigbee2mqtt#13269]
### What happened?

Hi
I'm sending message to my dimmer: 
_Received MQTT message on '/0x00158d00045cc95b/set' with data '{"brightness":81.6,"state":"ON"}'_

It's one message, but I've got two different responses.
_Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"OFF"}'
Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81.6,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"ON"}'_

### What did you expect to happen?

Think should be one response like this:
Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81.6,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"ON"}'

### How to reproduce it (minimal and precise)

Send to dimmer brightness and state in one message

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20201010

### Adapter

CC2652P1

### Debug log

Zigbee2MQTT:debug 2022-07-24 11:59:58: Received MQTT message on '/0x00158d00045cc95b/set' with data '{"brightness":81.6,"state":"ON"}'
Zigbee2MQTT:debug 2022-07-24 11:59:58: Publishing 'set' 'state' to '0x00158d00045cc95b'
Zigbee2MQTT:debug 2022-07-24 11:59:58: Received Zigbee message from '0x00158d00045cc95b', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":117440515,"currentLevel":81}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-07-24 11:59:58: Received Zigbee message from '0x00158d00045cc95b', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":15737344,"currentLevel":81}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"OFF"}'
Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"OFF"}'
Zigbee2MQTT:info  2022-07-24 11:59:58: MQTT publish: topic '/0x00158d00045cc95b', payload '{"brightness":81.6,"color_mode":"color_temp","color_temp":153,"linkquality":110,"state":"ON"}'

**Comment by sjorge** [comment]
I think it is because there are 2 attributeReport coming on, only attribute 61440 is different, not sure which seems to be a manufacturer specific attribute we do not decode.

Setting `debounce: 1` for the device will collapse them into a single publish.
