### ISSUE TITLE
[New device support]: MiBoxer FUT066Z and FUT068Z

### ISSUE THREAD

**Issue by Mouhwahno** [Koenkk/zigbee2mqtt#13265]
### Link

https://miboxer.com/light/xqy/fut066z.html

### Database entry

{"id":13,"type":"Router","ieeeAddr":"0x003c84fffebb7ce1","nwkAddr":26455,"manufId":4098,"manufName":"_TZ3210_zrvxvydd","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_zrvxvydd","powerSource":1,"zclVersion":3,"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorMode":2,"currentX":0,"currentY":0,"currentHue":86,"currentSaturation":254,"colorTemperature":153}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":98,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1658597583349,"defaultSendRequestWhen":"immediate"}

### Comments

Share same fingerprint with the smaller model https://miboxer.com/light/xqy/fut068z.html

### External converter

```shell
const fz = require("zigbee-herdsman-converters/converters/fromZigbee");
const tz = require("zigbee-herdsman-converters/converters/toZigbee");
const exposes = require("zigbee-herdsman-converters/lib/exposes");
const reporting = require("zigbee-herdsman-converters/lib/reporting");
const extend = require("zigbee-herdsman-converters/lib/extend");
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
  fingerprint: [{ modelID: "TS0505B", manufacturerName: "_TZ3210_zrvxvydd" }],
  model: "FUT066Z",
  vendor: "MiBoxer",
  description: "RGB+CCT LED Downlight",
  toZigbee: extend
    .light_onoff_brightness_colortemp_color()
    .toZigbee.concat([tz.tuya_do_not_disturb, tz.tuya_color_power_on_behavior]),
  meta: { applyRedFix: true, enhancedHue: false },
  fromZigbee: extend.light_onoff_brightness_colortemp_color().fromZigbee,
  exposes: [
    e
      .light_brightness_colortemp_colorhs([153, 500])
      .removeFeature("color_temp_startup"),
    exposes
      .binary("do_not_disturb", ea.STATE_SET, true, false)
      .withDescription("Do not disturb mode"),
    exposes
      .enum("color_power_on_behavior", ea.STATE_SET, [
        "initial",
        "previous",
        "cutomized",
      ])
      .withDescription("Power on behavior state"),
  ],
};
module.exports = definition;
```

### Supported color modes

color_temp, color_hs

### Color temperature range

Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
