### ISSUE TITLE
Neo NAS-PD07  Motion Sensor 

### ISSUE THREAD

**Issue by Profixit** [Koenkk/zigbee2mqtt#13264]
### What happened?

After the latest update my Neo NAS-PD07 Motion Sensor is not recognised properly. It's recognised as a NEO camcool ZigBee Siren Alarm Tuya. Before the update it was fine.

Zigbee2mqtt Dev branch recognises it, exposes many features but doesn't populate with values. Shows "N/A". I understand that there are two different types of this senser, with or without temperature. 

![IMG_20220603_173723](https://user-images.githubusercontent.com/104282040/180619270-c80b983d-4104-4f0e-9ed8-4dd748880f63.jpg)
.
Above Motion Sensor Recognised as below Siren.

![e2a5e110fb1997b2c1f554a76848d39305b17d2a_original](https://user-images.githubusercontent.com/104282040/180619222-01d83f45-d01d-4d2e-af4d-b1001ab0aa23.jpeg)

### What did you expect to happen?

After updating, I didn't expect the device type to change to another device. 

### How to reproduce it (minimal and precise)

Every time you pair the device using Zigbee2mqtt standard.

### Zigbee2MQTT version

1.26.0-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus 

### Debug log

I'll try and add some useful Debug info at some point.

**Comment by Koenkk** [comment]
Probably a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/12710 and already fixed in the dev branch  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Profixit** [comment]
Thanks for the reply.
I'm using the dev branch since yesterday, easy to switch with my setup. Odroid N2+. Installed the add-on, stopped the standard one, started the Dev branch and it took over. Very impressed.
It is recognised but not actually working. I was hoping it would populate exposed values over night. Unfortunately not. No occupancy showing just N/A on all exposed.
No biggie, I only have one.
Thanks again.

**Comment by Profixit** [comment]
I've given the other issue a look. I need time to make sense of it. I'll give it some study. I can see you've pushed the fix through in Dev branch.
Recognised, but not working. I'll give more testing...

**Comment by petergerdes** [comment]
Same issue here on docker-dev-image (pulled this morning), only state passed is linkquality.

**Comment by Profixit** [comment]
No cure. Even the with the latest Version Standard or Dev. Still the same. No Biggie. Only got one of these.
