### ISSUE TITLE
Device 'xxx' left the network

### ISSUE THREAD

**Issue by maciekh** [Koenkk/zigbee2mqtt#13268]
### What happened?

When I try to pair a new device to the network I get a message:

Zigbee2MQTT:warn  2022-07-24 10:42:39: Device '0xb4e3f9fffe19eb0e' left the network

I use SONOFF Zigbee 3.0 USB Dongle Plus with the newest firmware, z2m  version 1.26.
Previously those devices were used with another coordinator with no problems. 
I cleaned the whole z2m config (I hope), uninstalled and installed z2m again. And still the same error. Any ideas on what more can be done?

### What did you expect to happen?

I would expect supported devices to pair without a problem.

### Zigbee2MQTT version

1.26.0 

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

Zigbee2MQTT:warn  2022-07-24 10:42:39: Device '0xb4e3f9fffe19eb0e' left the network
Zigbee2MQTT:info  2022-07-24 10:42:39: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb4e3f9fffe19eb0e","ieee_address":"0xb4e3f9fffe19eb0e"},"type":"device_leave"}'
Zigbee2MQTT:info  2022-07-24 10:42:39: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0xb4e3f9fffe19eb0e"},"type":"device_removed"}'

**Comment by Koenkk** [comment]
In case you have a CC2531 lying around, could you make a sniff of this? (https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531)
