### ISSUE TITLE
Issue updating ZNCLDJ12LM (B1 Curtain Motor) Firmware

### ISSUE THREAD

**Issue by rodgrech** [Koenkk/zigbee2mqtt#13297]
### What happened?

I get an error 2022-07-26 21:24:02Failed to check if update available for 'Bedroom Curtains' (Failed to find endpoint which support OTA cluster) when trying to check for updates for my B1 Curtain Motor

### What did you expect to happen?

To get an up to date notification or get a update needed notification

### How to reproduce it (minimal and precise)

First go to OTA, Select Update Device Firmware

### Zigbee2MQTT version

1.26.0-dev commit: [343ef7f]

### Adapter firmware version

6.7.8.0 build 373

### Adapter

EZSP v8

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9189385/log.txt)

**Comment by ep1cman** [comment]
I have the same issue but for the [ZNGZDJ11LM](https://www.zigbee2mqtt.io/devices/ZNGZDJ11LM.html#xiaomi-zngzdj11lm)
