### ISSUE TITLE
[New device support]: IKEA Tradfri bulb

### ISSUE THREAD

**Issue by dinojascur** [Koenkk/zigbee2mqtt#13299]
### Link

https://www.ikea.com/cz/en/p/tradfri-led-bulb-e27-250-lumen-wireless-dimmable-warm-white-globe-clear-40439254/

### Database entry

TRADFRIbulbE27WWclear250lm

### Comments

I've got a new Ikea Tradfri bulb, but it's not yet supported.
Can you add support for it?

https://www.ikea.com/cz/en/p/tradfri-led-bulb-e27-250-lumen-wireless-dimmable-warm-white-globe-clear-40439254/

![image](https://user-images.githubusercontent.com/67243036/181018363-ae08da35-f7c0-4a2d-ae35-c4f13c6b13c1.png)

**Comment by Koenkk** [comment]
Already supported in the dev branch next z2m release on 1 August  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
