### ISSUE TITLE
3D Printed case for CC2530 router from wiki?

### ISSUE THREAD

**Issue by hgelpke** [Koenkk/zigbee2mqtt#1331]
I see a lot of minimal cases but has anybody designed a case to function in place of the aliexpress project box in the wiki?

**Comment by JLFN** [comment]
check the forum

**Comment by JLFN** [comment]
check the forum

**Comment by hgelpke** [comment]
I see like 4 posts in the forum.

Am I missing something?

**Comment by jjrh** [comment]
Little confused what you're after - 
https://www.zigbee2mqtt.io/information/3d_cases.html 

What's this aliexpress project box?

**Comment by hgelpke** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html

**Comment by jjrh** [comment]
Ah missed that. It's a pretty standard box.  Look on digikey/mouser or whatever your electronics distributor is if you don't want to go the aliexpress route.

**Comment by hgelpke** [comment]
I was hoping somebody had designed a 3d printed version already laid out.
