### ISSUE TITLE
[New device support]: Halemeier GmbH - HA-ZM12/24-1K

### ISSUE THREAD

**Issue by svh1985** [Koenkk/zigbee2mqtt#13316]
### Link

https://api.halemeier.de/storage/S-Mitter+Smartempfaenger_12V_24V.pdf

### Database entry

{"id":5,"type":"Router","ieeeAddr":"0x847127fffedb534b","nwkAddr":30246,"manufId":4723,"manufName":"Halemeier GmbH","powerSource":"Mains (single phase)","modelId":"HA-ZM12/24-1K","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"HA-ZM12/24-1K","manufacturerName":"Halemeier GmbH","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.5.3_r51"}},"lightingColorCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.5.3_r51","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1658945264938,"defaultSendRequestWhen":"immediate"}

### Comments

The External converter does the job. But I Don't know how to create a pull request to add support for other users.

I could only find a PDF file of the controller, it's described on page 7.

Image:
![image](https://user-images.githubusercontent.com/5213210/181343671-a84bafb8-a2e6-4dff-a877-72b63068ea0f.png)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['HA-ZM12/24-1K'],
    model: 'HA-ZM12/24-1K',
    vendor: 'Halemeier',
    description: '1-channel Smart Receiver',
    extend: extend.light_onoff_brightness(),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
