### ISSUE TITLE
[QUESTION] Why not all routers are pinged

### ISSUE THREAD

**Issue by milakov** [Koenkk/zigbee2mqtt#1332]
Hi, I have 5 routers: 2 Xiaomi smart plugs and 3 Gledopto lamps. I am curious why z2m is pinging plugs only, every 1 minutes, but doesn't do so for lamps?

**Comment by Koenkk** [comment]
Xiaomi routers are pinged because otherwise they tend to fall asleep. (something that @ptvoinfo has found out if I remember correctly).

**Comment by milakov** [comment]
Thanks! I didn't know about that.
