### ISSUE TITLE
Tuya TS0201 Reporting Humidity off by factor of 10

### ISSUE THREAD

**Issue by dfiore1230** [Koenkk/zigbee2mqtt#13328]
### What happened?

Connected a Tuya TS0201 and watch reporting. Temperature is correct, Humidity displays 47.3% (on screen) but reports 4.73 via MQTT

`log/2022-07-21.23-42-25/log.txt:info  2022-07-29 11:28:22: MQTT publish: topic 'zigbee2mqtt/Primary Bathroom Sensor', payload '{"battery":100,"humidity":4.73,"linkquality":79,"temperature":22.33,"voltage":3000}'
`
![Screen Shot 2022-07-29 at 11 29 55 AM](https://user-images.githubusercontent.com/3728160/181793348-3a203add-d7e6-4474-af10-fba8ec5ee320.png)

### What did you expect to happen?

Reporting matches display

### How to reproduce it (minimal and precise)

Add device to network, observe logs, front-end and device display

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

0x26680700

### Adapter

ConbeeII

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by kirovilya** [comment]
Use humidity10 converter https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js#L512

**Comment by dfiore1230** [comment]
Here is the database.db entry

`{"id":25,"type":"EndDevice","ieeeAddr":"0xa4c138c788411dca","nwkAddr":30887,"manufId":4417,"manufName":"_TZ3000_itnrsufe","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,3,1026,1029,57346,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011z\u0000\u0000\u0000\u0012","65506":51,"65508":1,"65534":0,"modelId":"TS0201","manufacturerName":"_TZ3000_itnrsufe","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2251}},"msRelativeHumidity":{"attributes":{"measuredValue":501}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":192,"batteryVoltage":29}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":126974596},"lastSeen":1659357364608,"defaultSendRequestWhen":"immediate"}`

I wouldnt know where to start using humidity10, but reading the code quickly, it seems to me to be dividing by 10, where as this needs to be multiplied by 10.

**Comment by kirovilya** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js#L3023
Here I have the same device as you and the required converter is used there. wait for today's release and everything will work

**Comment by dfiore1230** [comment]
Many thanks.
