### ISSUE TITLE
Zen Thermostat not working 

### ISSUE THREAD

**Issue by rlambord** [Koenkk/zigbee2mqtt#13341]
### What happened?

Installed Zen ZigBee Thermostat. It connects and shows all good in home assistant/zigbee2mqtt but none of the target temps are correct and I can not change any values via zigbee2mqtt
For some reason the values are 16.6 c. I also changed settings to Fahrenheit but non updated

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20220507

### Adapter

Sonoff

**Comment by maxwondercorn** [comment]
@rlambord This issue might help you https://github.com/Koenkk/zigbee2mqtt/issues/4320.  There still be issues with setting the cooling setpoit
