### ISSUE TITLE
Wrong Device beqause of PR #4467

### ISSUE THREAD

**Issue by Danit2** [Koenkk/zigbee2mqtt#13369]
### What happened?

Bequase of the PR [4467](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4467) in herdaman-converters my `PTM215Z` Module is identify as `LED Trading FOH smart switch 9125`

The Device `LED Trading FOH smart switch 9125` should be a white label device of the `PTM215Z` and not a new device. 

### What did you expect to happen?

Roll back the PR [4467](https://github.com/Koenkk/zigbee-herdsman-converters/pull/4467) in herdaman-converters and make a white label device. 

### Zigbee2MQTT version

1.27

### Adapter firmware version

- 

### Adapter

-

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Danit2** [comment]
Thanks
