### ISSUE TITLE
Application panic'd due to nodeId unrecognized

### ISSUE THREAD

**Issue by jemershaw** [Koenkk/zigbee2mqtt#13366]
### What happened?

The application panic'd and restarted but this is the error captured -- I'm not entirely sure what what triggered this message.
```
Error: Unrecognized nodeId:4597
    at Driver.networkIdToEUI64 (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:511:19)
    at Driver.handleRouteError (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:338:22)
```

### What did you expect to happen?

Not to panic

### How to reproduce it (minimal and precise)

Not entirely sure.

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

6.7.8.0 build 373

### Adapter

GoControl CECOMINOD016164 HUSBZB-1 USB Hub

**Comment by kirovilya** [comment]
need to update Z2M to 1.27 version
