### ISSUE TITLE
Support for profalux MOT-C1Z10C and its associated remote MAI-ZTS

### ISSUE THREAD

**Issue by Sigfrodr** [Koenkk/zigbee2mqtt#13377]
### Link

https://www.profalux-pro.com/documentations/1.%20Notices,%20Plans,%20Technique/1.%20Volets%20roulants/3.%20Moteurs%20Commandes%20et%20Accessoires/1.%20Moteur/Moteur%20Profalux%20Zigbee/

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0x20918a000010dd07","nwkAddr":61422,"manufId":4368,"manufName":"Profalux","powerSource":"Mains (single phase)","modelId":"MOT-C1Z10C\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":512,"inClusterList":[0,3,4,5,6,8,10,21,256,64544,64545],"outClusterList":[3,10,64544],"clusters":{"genBasic":{"attributes":{"modelId":"MOT-C1Z10C\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","manufacturerName":"Profalux","powerSource":1,"zclVersion":3,"appVersion":24,"hwVersion":29,"dateCode":"20000101","swBuildId":"Release"}},"genLevelCtrl":{"attributes":{"currentLevel":250}}},"binds":[{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c211bc","endpointID":1}],"configuredReportings":[{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{}},"2":{"profId":260,"epId":2,"devId":514,"inClusterList":[0,1,2,3,4,5,9,10,21,258,2821,64514,64544,64545],"outClusterList":[3,10,25,32,64544],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":24,"hwVersion":29,"dateCode":"20000101","swBuildId":"Release","zclVersion":3,"interviewCompleted":true,"meta":{"configured":734529022},"lastSeen":1659463873932,"defaultSendRequestWhen":"immediate"} {"id":3,"type":"EndDevice","ieeeAddr":"0x20918a000010dd08","nwkAddr":56300,"manufId":4368,"manufName":"Profalux","powerSource":"Battery","modelId":"MAI-ZTS","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":513,"inClusterList":[0,3,21,64514,64544],"outClusterList":[3,4,5,6,8,256,64544,64545],"clusters":{"genBasic":{"attributes":{"modelId":"MAI-ZTS","manufacturerName":"Profalux","powerSource":3,"zclVersion":3,"appVersion":25,"hwVersion":29,"dateCode":"Jun 10 2021","swBuildId":"Release"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":515,"inClusterList":[0,1,2,3,9,21,32,64514,64544],"outClusterList":[3,4,5,25,258,64544,64545],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":1200}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c211bc","endpointID":242}],"configuredReportings":[],"meta":{}}},"appVersion":25,"hwVersion":29,"dateCode":"Jun 10 2021","swBuildId":"Release","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1659463607169,"defaultSendRequestWhen":"fastpoll"}root@openmediavault:/srv/dev-disk-by-label-data/appdata/zigbee2mqtt# 

### Comments

Needed to make a custom converter for this model and its associated remote

What has changed vs defaut profalux.js:

 zigbeeModel: ['MOT-C1Z10C\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'], for cover
 zigbeeModel: ['MAI-ZTS'], for remote

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['MAI-ZTS'],
        fingerprint: [{manufId: 4368, endpoints: [{ID: 1, profileID: 260, deviceID: 513, inputClusters: [0, 3, 21],
            outputClusters: [3, 4, 5, 6, 8, 256, 64544, 64545]}]}],
        model: 'NB102',
        vendor: 'Profalux',
        description: 'Cover remote',
        fromZigbee: [],
        toZigbee: [],
        exposes: [],
    },
    {
        zigbeeModel: ['MOT-C1Z10C\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'],
        fingerprint: [{manufId: 4368, endpoints: [{ID: 1, profileID: 260, deviceID: 512,
            inputClusters: [0, 3, 4, 5, 6, 8, 10, 21, 256, 64544, 64545], outputClusters: [3, 64544]}]}],
        model: 'NSAV061',
        vendor: 'Profalux',
        description: 'Cover',
        fromZigbee: [fz.cover_position_via_brightness, fz.cover_state_via_onoff],
        toZigbee: [tz.cover_via_brightness],
        exposes: [e.cover_position().setAccess('state', ea.ALL)],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genLevelCtrl']);
            await reporting.brightness(endpoint);
        },
    },
];
```

**Comment by Sigfrodr** [comment]
Not stale

**Comment by Sigfrodr** [comment]
not stale

**Comment by dim6003** [comment]
User of Remote model MAI-ZTG here, don't if compatible from ZigBee point of view with the MAI-ZTS, but interested anyway, can provide  data if needed.

**Comment by dim6003** [comment]
not stale

**Comment by dim6003** [comment]
not stale

**Comment by dim6003** [comment]
..

**Comment by Jeepmg** [comment]
Why is this shutter and its remote still not integrated into the profalux.js file of herdsman-converters?

**Comment by dim6003** [comment]
What can be done to make this go forward?

**Comment by sven337** [comment]
The shutter actually works as far as I can tell. The remote appears as "unsupported" but the Zigbee logs show some traffic that shouldn't be too hard to figure out. I guess this needs a contribution.

**Comment by sven337** [comment]
Interesting: my cover is paired, reports its position properly, but I can't set its position from zigbee2mqtt (it's like it was ignored).
Open/close/stop similarly don't work. Does anybody else see that ?

**Comment by Iroamstaff** [comment]
Sven337 j'ai l'intégration z2m ha sur raspberry pi il m'a suffit de redémarrer le raspberry pi pour que tout fonctionne correctement j'ai eu ce souci sur chaques volets jumelée

**Comment by sven337** [comment]
It's not that - see issue #17674
