### ISSUE TITLE
Woox R7054

### ISSUE THREAD

**Issue by wisienoza** [Koenkk/zigbee2mqtt#13379]
### What happened?

Hello,
I have a problem with a Woxx 7054 remote control. it appears as supported on the zigbee2mqtt device list (https://www.zigbee2mqtt.io/devices/TS0215A_remote.html#tuya-ts0215a_remote) but unfortunately I am unable to pair it. When I add the device to Home Assistant, the device is recognized as unsupported. I have zigbee2mqtt installed as an addon.
![2022-08-02 22_56_43-Window](https://user-images.githubusercontent.com/108104414/182471965-0968651d-48c1-4e45-8189-4036904326e0.jpg)

I will be very grateful for your help.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
Please provide the data/database.db entry of your device.

**Comment by wisienoza** [comment]
database.db below:


{"id":1,"type":"Coordinator","ieeeAddr":"0x00212effff082229","nwkAddr":0,"manufId":4405,"epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[0,10,25],"outClusterList":[1,32,1280],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":100,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null,"defaultSendRequestWhen":"immediate"}
{"id":2,"type":"Router","ieeeAddr":"0x00158d0007092cd1","nwkAddr":22681,"manufId":4447,"manufName":"LUMI","powerSource":"DC Source","modelId":"lumi.light.aqcn02","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[0,4,3,5,10,258,13,19,6,1,1030,8,768,1027,1029,1026],"outClusterList":[25,10,13,258,19,6,1,1030,8,768],"clusters":{"genBasic":{"attributes":{"65281":{"3":41,"5":75,"8":288,"9":1539,"10":0,"100":0,"101":35,"102":370},"modelId":"lumi.light.aqcn02","appVersion":32,"dateCode":"09-01-2020"}},"genOnOff":{"attributes":{"61440":117440534,"onOff":0}},"genLevelCtrl":{"attributes":{"61440":5806336,"currentLevel":35}},"lightingColorCtrl":{"attributes":{"colorTemperature":370,"tuyaRgbMode":5806336,"colorMode":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":32,"stackVersion":2,"hwVersion":1,"dateCode":"09-01-2020","swBuildId":"1.32\u0000","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1659546157298,"defaultSendRequestWhen":"immediate"}
{"id":3,"type":"EndDevice","ieeeAddr":"0x00158d0007bccc1f","nwkAddr":7183,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_switch","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":1},{"elmType":33,"elmVal":3012},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":76},{"elmType":32,"elmVal":78}],"modelId":"lumi.sensor_switch","appVersion":10}},"genOnOff":{"attributes":{"32768":128,"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":10,"interviewCompleted":true,"meta":{},"lastSeen":1659544002482,"defaultSendRequestWhen":"immediate"}
{"id":4,"type":"EndDevice","ieeeAddr":"0x00158d0007e68653","nwkAddr":62736,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.weather","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65281":{"1":3005,"4":5032,"5":8,"6":[0,1],"10":0,"100":2488,"101":5360,"102":100427},"modelId":"lumi.weather","appVersion":5}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2490}},"msRelativeHumidity":{"attributes":{"measuredValue":5448}},"msPressureMeasurement":{"attributes":{"measuredValue":1004,"scale":-1,"scaledValue":10043}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":5,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1659545315287,"defaultSendRequestWhen":"immediate"}
{"id":5,"type":"EndDevice","ieeeAddr":"0x804b50fffe04702e","nwkAddr":57443,"manufId":4098,"manufName":"_TZE200_d0yu2xgi","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0011","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_d0yu2xgi","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-201703211},"lastSeen":1659543812401,"defaultSendRequestWhen":"immediate"}
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d0007e639e1","nwkAddr":22975,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3025,"3":29,"4":5032,"5":14,"6":[0,7],"10":0,"100":0},"modelId":"lumi.sensor_magnet.aq2","appVersion":3,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1496948516},"lastSeen":1659545571575,"defaultSendRequestWhen":"immediate"}
{"id":7,"type":"EndDevice","ieeeAddr":"0x00158d0007e2ac06","nwkAddr":64009,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_motion.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,65535,1030,1024,1280,1,3],"outClusterList":[0,25],"clusters":{"genBasic":{"attributes":{"65281":{"1":3015,"3":33,"4":5032,"5":10,"6":[0,12],"10":0,"11":18,"100":0},"modelId":"lumi.sensor_motion.aq2","appVersion":5,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20170627","swBuildId":"3000-0001"}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":8}},"msOccupancySensing":{"attributes":{"occupancy":1}},"ssIasZone":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":5,"stackVersion":2,"hwVersion":1,"dateCode":"20170627","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1659544676136,"defaultSendRequestWhen":"immediate"}
{"id":8,"type":"Router","ieeeAddr":"0x54ef441000320a1f","nwkAddr":11207,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.sensor_gas.acn02","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280,9,4],"outClusterList":[10,25,4],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.sensor_gas.acn02","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":14,"stackVersion":2,"hwVersion":1,"dateCode":"01-05-2022"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff082229","zoneState":1}},"aqaraOpple":{"attributes":{"2":1,"220":{"type":"Buffer","data":[79,102,125,42,119,196,199,43,0,0,255,233]},"223":{"type":"Buffer","data":[22,33,0,0,23,33,0,0,12,33,210,2,24,33,44,4,30,33,16,13,31,33,170,121,32,33,223,243,34,33,185,163,35,33,0,0,36,32,0,37,35,178,218,101,91,254,35,128,0,4,0]},"229":{"type":"Buffer","data":[2,0,2,119,196,37,29,153,88,37,76]},"247":{"type":"Buffer","data":[5,33,1,0,8,33,14,1,9,33,0,2,10,33,153,88,11,32,0,12,32,1,154,32,0,159,32,2,160,33,0,0,161,32,0,162,32,0,163,32,0,164,32,0,165,32,0,166,32,0]},"268":2,"294":0,"295":0,"313":0,"314":0,"315":0,"331":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":14,"stackVersion":2,"hwVersion":1,"dateCode":"01-05-2022","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1831405904},"lastSeen":1659545120837,"defaultSendRequestWhen":"immediate"}
{"id":9,"type":"EndDevice","ieeeAddr":"0x00158d0007bcc54c","nwkAddr":30283,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_switch","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":1},{"elmType":33,"elmVal":3032},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,3]},{"elmType":33,"elmVal":102},{"elmType":32,"elmVal":84}],"modelId":"lumi.sensor_switch","appVersion":10}},"genOnOff":{"attributes":{"32768":2,"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":10,"interviewCompleted":true,"meta":{},"lastSeen":1659546001244,"defaultSendRequestWhen":"immediate"}
{"id":10,"type":"EndDevice","ieeeAddr":"0x00158d000726d966","nwkAddr":32023,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_wleak.aq1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65281":{"1":3035,"3":30,"4":5032,"5":18,"6":[0,1],"8":518,"10":0,"100":0},"modelId":"lumi.sensor_wleak.aq1","appVersion":6}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":6,"stackVersion":2,"hwVersion":2,"dateCode":"20200310","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1659544555420,"defaultSendRequestWhen":"immediate"}
{"id":11,"type":"EndDevice","ieeeAddr":"0x00158d0006e97b2c","nwkAddr":53911,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_wleak.aq1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65281":{"1":3035,"3":28,"4":5032,"5":9,"6":[0,1],"8":518,"10":0,"100":0},"modelId":"lumi.sensor_wleak.aq1","appVersion":6}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":6,"stackVersion":2,"hwVersion":2,"dateCode":"20200310","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1659545309521,"defaultSendRequestWhen":"immediate"}
{"id":12,"type":"EndDevice","ieeeAddr":"0x00158d0006eb9688","nwkAddr":37334,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_cube.aqgl01","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,25,18],"outClusterList":[0,4,3,5,25,18],"clusters":{"genBasic":{"attributes":{"65281":{"1":3015,"3":25,"4":5032,"5":98,"6":[0,1],"10":22681,"151":0,"152":1865,"153":1695,"154":4},"modelId":"lumi.sensor_cube.aqgl01","appVersion":5}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"epId":2,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":2}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"epId":3,"inClusterList":[],"outClusterList":[],"clusters":{"genAnalogInput":{"attributes":{"65285":500,"presentValue":-52.26999282836914}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":5,"stackVersion":2,"dateCode":"20160704","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1659545741703,"defaultSendRequestWhen":"immediate"}
{"id":13,"type":"EndDevice","ieeeAddr":"0x00158d0008378966","nwkAddr":46585,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3045,"3":38,"4":5032,"5":20,"6":[0,1],"10":0,"100":1},"modelId":"lumi.sensor_magnet.aq2","appVersion":3,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1496948516},"lastSeen":1659543168100,"defaultSendRequestWhen":"immediate"}
{"id":14,"type":"EndDevice","ieeeAddr":"0x00158d000836ea77","nwkAddr":5607,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3075,"3":32,"4":5032,"5":9,"6":[0,1],"10":0,"100":1},"modelId":"lumi.sensor_magnet.aq2","appVersion":3,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1496948516},"lastSeen":1659545645694,"defaultSendRequestWhen":"immediate"}
{"id":15,"type":"EndDevice","ieeeAddr":"0x00158d000832fd14","nwkAddr":63965,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3095,"3":29,"4":5032,"5":7,"6":[0,1],"10":0,"100":1},"modelId":"lumi.sensor_magnet.aq2","appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1496948516},"lastSeen":1659543223979,"defaultSendRequestWhen":"immediate"}
{"id":16,"type":"EndDevice","ieeeAddr":"0x00158d0008378daa","nwkAddr":8367,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_magnet.aq2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":24321,"inClusterList":[0,3,65535,6],"outClusterList":[0,4,65535],"clusters":{"genBasic":{"attributes":{"65281":{"1":3075,"3":31,"4":5032,"5":6,"6":[0,1],"10":0,"100":0},"modelId":"lumi.sensor_magnet.aq2","appVersion":3,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":2,"dateCode":"20161128","swBuildId":"3000-0001","zclVersion":1,"interviewCompleted":true,"meta":{"configured":-1496948516},"lastSeen":1659545627384,"defaultSendRequestWhen":"immediate"}
{"id":17,"type":"Router","ieeeAddr":"0x54ef4410004dd76f","nwkAddr":50295,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,21,31,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,64704],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":41,"stackVersion":2,"hwVersion":1,"dateCode":"12-06-2021"}},"haElectricalMeasurement":{"attributes":{"acPowerMultiplier":1,"acPowerDivisor":10}},"aqaraOpple":{"attributes":{"220":{"type":"Buffer","data":[158,28,124,42,119,196,0,0,192,230,255,233]},"223":{"type":"Buffer","data":[22,33,0,0,23,33,0,0,12,33,0,0,24,33,23,12,30,33,18,0,31,33,155,16,32,33,175,37,34,33,91,140,35,33,0,0,36,32,0,37,35,36,191,7,184,250,33,0,0,251,33,0,0,252,35,0,0,0,0,253,35,0,0,0,0,254,35,128,0,4,0]},"229":{"type":"Buffer","data":[3,0,3,0,0,4,61,153,88,37,72,199,43,37,30]},"247":{"type":"Buffer","data":[100,16,0,3,40,30,152,57,0,0,0,0,149,57,109,138,97,62,150,57,0,224,18,69,151,57,0,0,0,0,5,33,1,0,154,32,0,8,33,41,1,9,33,0,3,11,32,0,155,16,1,10,33,0,0,12,32,1]},"513":1,"519":1}},"seMetering":{"attributes":{"multiplier":1,"divisor":1000}},"genOnOff":{"attributes":{"245":117440559,"onOff":0}},"genDeviceTempCfg":{"attributes":{"currentTemperature":30}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff082229","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff082229","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff082229","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":0}],"meta":{}},"21":{"profId":260,"epId":21,"devId":81,"inClusterList":[12],"outClusterList":[],"clusters":{"genAnalogInput":{"attributes":{"presentValue":0}}},"binds":[],"configuredReportings":[],"meta":{}},"31":{"profId":260,"epId":31,"devId":81,"inClusterList":[12],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":41,"stackVersion":2,"hwVersion":1,"dateCode":"12-06-2021","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1278759219},"lastSeen":1659545009616,"defaultSendRequestWhen":"immediate"}
{"id":19,"type":"EndDevice","ieeeAddr":"0xa4c138c99f3c2925","nwkAddr":26209,"manufId":4417,"manufName":"_TZ3000_0zrccfgx","powerSource":"Battery","modelId":"TS0215A","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1025,"inClusterList":[1,3,1280,0],"outClusterList":[1281,25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff082229","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1659531038557,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
The one with manufacturer name `_TZ3000_0zrccfgx` was not supported yet, I added it now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
