### ISSUE TITLE
R7060 is sometimes reporting wrong status

### ISSUE THREAD

**Issue by graphicsxp** [Koenkk/zigbee2mqtt#13384]
### What happened?

I have two of these devices for watering my garden. They seem to randomly report the wrong ON/OFF status. Sometimes they won't turn on and sometimes (worse in the case of watering) they won't turn off. Note that if I press manually the ON/OFF button on the device, then they always work as expected. And once I pressed the button manually, they work again normally in home assistant... for a while until again I have this issue.
It seems to occur after a idle period. I would typically water the garden in the morning and then they will stay idle until the next day. 
If I turn them ON/OFF from HA regularly (every few hours) they seem to work just fine.

When I have this issue, if I check the logbook in HA, I can see their state changing, although in z2m, it doesn't. 

I had the battery status report issue like others on this forum and I solved it using the converter suggested [here](https://github.com/Koenkk/zigbee2mqtt/issues/12163) .

The LQI is strong enough ( >100)

I don't know if it's an issue with zigbee2mqtt or with the device itself. It obviously make them unreliable and I wouldn't trust them while on holidays....

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

no coordinator revision under about (has it moved ?)

### Adapter

Conbee2

**Comment by stefangries** [comment]
Unfortunately, I experienced the same thing with this device. My schedule turned the device on while I was on vacation and reportedly turned it off. It was also displayed as off. Unfortunately, it stayed on. Even after another ON/OFF cycle. I had to manually turn it off with the red button when I was back home. So over my entire vacation, my garden was watered and tons of electricity and water were wasted.

Even though the problem happened only three times for me, it is not reliable enough. I am now switching to a different device.
