### ISSUE TITLE
Tuya TS0601, too high PM2.5 values

### ISSUE THREAD

**Issue by jeroenhubgit** [Koenkk/zigbee2mqtt#13388]
### What happened?

My new Tuya Smart air house TS0601 sensor, has measured PM2.5 values which are unrealistically high. I have the sensor indoor and since today I have it close to a open window (outside the PM2.5 is now 8 µg/m³ as reference)
Is this the software, or would my sensor be broken on arrival?

![Tuya Smart air house TS0601](https://user-images.githubusercontent.com/88284339/182589656-84b72d4b-14d3-4cc7-83a3-0fdc3d277bf7.png)

### What did you expect to happen?

Lower PM 2.5 values between 0 and 25

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

6.7.8.0 build 373

### Adapter

ezsp via tcp - Sonoff zigbee bridge

**Comment by Koenkk** [comment]
Does the device report correct values when paired to the TuYa gateway?

**Comment by jeroenhubgit** [comment]
Thank you for your message. I would like to know, but I don't have the TuYa gateway. Is there a other way I could check the raw data?

**Comment by Koenkk** [comment]
@jeroenhubgit yes, by enabling the debug logging: 
See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
