### ISSUE TITLE
Lidl HG08164 Error message

### ISSUE THREAD

**Issue by peterossege** [Koenkk/zigbee2mqtt#13383]
### What happened?

When I add a Lidl Lidl HG08164 device I get an error message:

Received message from 
unsupported devvice with Zigbee
model 'TS004F' an
manufacturer name
'_TZ3000_rco1yzb1'

I tried two devices.

### What did you expect to happen?

I thought it would work but it dont.

### How to reproduce it (minimal and precise)

It always happens

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

SONOFF Zigbee 3.0 USB Dongle

**Comment by Koenkk** [comment]
This device is supported in z2m 1.27.0 (you are on 1.22.2)
