### ISSUE TITLE
Documentation page for hue smart plug is actually for a hue bulb

### ISSUE THREAD

**Issue by robvdl** [Koenkk/zigbee2mqtt#13380]
### What happened?

Go to https://www.zigbee2mqtt.io/devices/8719514342361.html it describes a bulb rather than a plug

### What did you expect to happen?

It describes the smart plug

### How to reproduce it (minimal and precise)

Just look at the page https://www.zigbee2mqtt.io/devices/8719514342361.html

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

20220219

### Adapter

zStack3x0

**Comment by Koenkk** [comment]
Fixed, thanks for reporting.
