### ISSUE TITLE
[Profalux shutters] Periodic movement

### ISSUE THREAD

**Issue by Sigfrodr** [Koenkk/zigbee2mqtt#13399]
### What happened?

Every few minutes, all my Profalux shutters are doing a quick up/down movement (less than 1 second).
I have 4 shutters, and they are all doing the same movement at the same time.
If I turn the gateway down, the movement does not occur anymore, so the movement is related to the gateway.

Same problem as here, it occurs on z2m too:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3102

NB: only occurs while pairing mode is active

### What did you expect to happen?

No shutters movement when no action performed.

### How to reproduce it (minimal and precise)

Profalux shutters paired (version MOT-C1Z10C)

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 plus

**Comment by letroll** [comment]
I have the same problem with home assistant and zha. So probably more related to home assistant
