### ISSUE TITLE
Touchlink and max device list in firmware

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee2mqtt#134]
I found some intresting moments here https://github.com/Tropicao/zigbridge/blob/master/doc/firmware_instructions.md

> NWK_MAX_DEVICE_LIST=0 

Already there are remarks about the number of connected devices. This setting assumes that the device list is stored in the application, not in the cc253x. This presumably eliminates the problem with the count.

> INTER_PAN

This allow to use touchlink mode for ZLL lamp.

It remains only to assemble the firmware and try to use it :)

**Comment by Koenkk** [comment]
I've compiled a firmware with these settings: https://github.com/Koenkk/Z-Stack-firmware/tree/experimental/coordinator/CC2531 (see `bin` folder). Currently working good with 1 motion sensor and 1 bulb, need to do more tests but looks promising!

This also allows us to set a very high `MAXMEMHEAP` which can improve stability.

**Comment by kirovilya** [comment]
@Koenkk Good! Need tester with many devices...

**Comment by Koenkk** [comment]
It seems to after testing again, I cannot connect more than one (end) device. Note that the link from OP uses Z-Stack 3.0.1 so there might be some differences here..

**Comment by kirovilya** [comment]
@Koenkk :( Bad...
So... closing issue?

**Comment by Koenkk** [comment]
No, touchlink is still there!

**Comment by Koenkk** [comment]
Closing as the required options are enabled in the firmware.
