### ISSUE TITLE
[New device support]: TS0502A Tuya CCT Driver

### ISSUE THREAD

**Issue by shbkrm** [Koenkk/zigbee2mqtt#13426]
### Link

https://www.zigbee2mqtt.io/devices/TS0502A.html#tuya-ts0502a

### Database entry

{"id":23,"type":"Router","ieeeAddr":"0xb4e3f9fffe7ca74b","nwkAddr":14802,"manufId":4098,"manufName":"_TZ3210_yvsmueix","powerSource":"Mains (single phase)","modelId":"TS0502A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,61184],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":1,"offWaitTime":0}},"lightingColorCtrl":{"attributes":{"61453":0,"tuyaRgbMode":0,"colorTemperature":250,"colorMode":2,"colorCapabilities":16}},"genLevelCtrl":{"attributes":{"currentLevel":128}},"genBasic":{"attributes":{"modelId":"TS0502A","manufacturerName":"_TZ3210_yvsmueix","stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1658920287264,"defaultSendRequestWhen":"immediate"}

### Comments

The device interview completed successfully. 
The capabilities are also shown
![Screen Shot 2022-08-06 at 3 10 46 PM](https://user-images.githubusercontent.com/9065106/183243637-61edc9ce-66ea-47e4-9970-36f73773a154.png)
 None of the controls - power ON/OFF, brightness or color_temp are working.

The same device works properly with Tuya gateway.

### Supported color modes

color temperature

**Comment by Tonio16** [comment]
Did you solve it?
