### ISSUE TITLE
Not able to connect Gledopto GL-C-008W

### ISSUE THREAD

**Issue by nielstermeer86** [Koenkk/zigbee2mqtt#13450]
### What happened?

Not able to connect Gledopto GL-C-008W 

### What did you expect to happen?

At least be be able to see it in Z2M

### How to reproduce it (minimal and precise)

perform a device reset. cut power on DC side 5 times. The light strip fades in and out slowly 10x (which is not written anywhere) then nothing.
of course it's right next to the adapter

### Zigbee2MQTT version

1.27.0-1

### Adapter firmware version

20180507

### Adapter

CC2531 USB stick

**Comment by embcla** [comment]
Got two GL-C-008something
deConz recognized them as GL-C-008
zigbee2mqtt as GL-C-008-1ID

they both work, had to wait a few seconds after detection before they appeared in the web panel
