### ISSUE TITLE
Most routers offline no pairing 

### ISSUE THREAD

**Issue by mullischlumpf** [Koenkk/zigbee2mqtt#1345]
Hi i have the problem, that i could not integrate my new Xiaomi Aqara Motion Sensor and Door Sensors to me zigbee network. I have 26 devices with many routers so i think there should be no problem to add more devices. In the network map i saw, that many of my routers are marked as offline?!? But they work without problems. Is there a way to get them online or what is the problem?

Here is a part of my network map.
 "0x00124b001936ada8" [style="bold", label="{0x00124b001936ada8|Coordinator|No model information available|online}"];                                                        
  "0x84182600000cfa47" [style="rounded", label="{appletv|Router|OSRAM Smart+ plug (AB3257001NJ)|offline}"];                                                                   
  "0x0017880102e24363" [style="rounded, dashed", label="{wohnzimmerschalter|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];                                    
  "0x00178801102d0556" [style="rounded", label="{schlafzimmerlicht|Router|Philips Hue white ambiance E26/E27 (8718696548738)|offline}"];                                      
  "0x0017880102e242af" [style="rounded, dashed", label="{schlafzimmerschalter1|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];                                 
  "0x0017880102d56dcb" [style="rounded, dashed", label="{schlafzimmerschalter3|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];                                 
  "0x0017880102e499e1" [style="rounded", label="{esstischlicht1|Router|Philips Hue white ambiance GU10 (8718696598283)|offline}"];                                            
  "0x0017880102e49d6d" [style="rounded", label="{esstischlicht2|Router|Philips Hue white ambiance GU10 (8718696598283)|offline}"];                                            
  "0x0017880102e24757" [style="rounded, dashed", label="{toilettenlichtschalter|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];                                
  "0x00178801102eb231" [style="rounded", label="{badlicht|Router|Philips Hue white ambiance E26/E27 (8718696548738)|offline}"];                                               
  "0x0017880102e24792" [style="rounded, dashed", label="{badlichtschalter|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];                                      
  "0x00178801026c1be7" [style="rounded", label="{ankleidelicht|Router|Philips Hue White Single bulb B22 (8718696449691)|online}"];                                            
  "0x00178801025ffae1" [style="rounded", label="{stehlampe|Router|Philips Hue white ambiance E26/E27 (8718696548738)|offline}"];                                              
  "0x000b57fffeb1a2ab" [style="rounded", label="{toilettenlicht1|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|offline}"];                                
  "0x000b57fffeaf96a3" [style="rounded", label="{toilettenlicht2|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|online}"];                                 
  "0x00178801029adaa9" [style="rounded", label="{küchenlicht|Router|Philips Hue white ambiance E14 (8718696695203)|offline}"];                                                
  "0x00178801103fca24" [style="rounded, dashed", label="{küchenlichtschalter|EndDevice|Philips Hue dimmer switch (324131092621)|online}"];                                    
  "0x000b57fffe9e4f52" [style="rounded", label="{lichtpanel|Router|IKEA FLOALT LED light panel, dimmable, white spectrum (30x90 cm) (L1528)|offline}"];                       
  "0x0017880102e4536f" [style="rounded", label="{flurlicht1|Router|Philips Hue white ambiance GU10 (8718696598283)|offline}"];                                                
  "0x00178801023933ca" [style="rounded", label="{flurlicht2|Router|Philips Hue white ambiance GU10 (8718696598283)|offline}"];                                                
  "0x0017880102e45f36" [style="rounded", label="{flurlicht3|Router|Philips Hue white ambiance GU10 (8718696598283)|offline}"];                                                
  "0x90fd9ffffe7171ad" [style="rounded", label="{terrassenlicht|Router|IKEA TRADFRI LED bulb E26/E27 950 lumen, dimmable, white spectrum, clear (LED1546G12)|off              
line}"];                                                                                                                                                                      
  "0x7cb03eaa00a9faa5" [style="rounded", label="{terrassenleiste1|Router|OSRAM Outdoor Flex RGBW (4058075036185)|offline}"];                                                  
  "0x0017880102e23eaf" [style="rounded, dashed", label="{schlafzimmerschalter2|EndDevice|Philips Hue dimmer switch (324131092621)|online}"];                                  
  "0x8418260000dabc86" [style="rounded", label="{küchenleiste1|Router|OSRAM Flex RGBW (4052899926110)|offline}"];                                                             
  "0x8418260000dabaa9" [style="rounded", label="{küchenleiste2|Router|OSRAM Flex RGBW (4052899926110)|offline}"];                                                             
  "0x84182600000db28a" [style="rounded", label="{ankleideleiste|Router|OSRAM Smart+ plug (AB3257001NJ)|online}"];                                                             
}'

**Comment by djchen** [comment]
Thats perfectly normal for the routers to show offline. Do you see any other devices connected to them?

Pairing the Xiaomi sensors is extremely finicky. You need to pick them right up against your coordinator and make sure to follow the tips here very precisely (https://www.zigbee2mqtt.io/getting_started/pairing_devices.html). It took me quite a few tries for the door/window sensors.

**Comment by mullischlumpf** [comment]
i still had noch success with the xiaomi sensor :-( I had a message "device incoming" but then nothing happens. I then tried to add another ikea bulb but also with no success. Nothing happens in the log when i try to join devices...

**Comment by mullischlumpf** [comment]
It seems, that the maximum of devices is reached in my zigbee cc2531. I reset the stick and readd all devices. I could add 29 devices (including xiaomi sensor) without any problems. Now no new device could join the network. I thought the limit is higher with many routers connected?!? 
But it seems not to be a bug so you could close the issue.

**Comment by tyjtyj** [comment]
> It seems, that the maximum of devices is reached in my zigbee cc2531. I reset the stick and readd all devices. I could add 29 devices (including xiaomi sensor) without any problems. Now no new device could join the network. I thought the limit is higher with many routers connected?!?
> But it seems not to be a bug so you could close the issue.

Sorry to bring this 1 year old tread up. I reach device limit with 3 router and 20 xiaomi sensor. 
I believe the 20 xiaomi sensor is the limit regardless how many router you have you. 

Do you have work around on your issue ? Does source routing firmware allow beyond 20 xiaomi sensor ?
