### ISSUE TITLE
Xiaomi power plug ZNCZ04LM - after upgrade OTA fw to 01-23-2022 energy amount has been reset to zero

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#13463]
### What happened?

As a title

lumi.plug.mmeu01 Xiaomi power plug ZigBee ZNCZ04LM
After upgrade firmware via zigbee2mqtt web panel OTA tab, to newest 01-23-2022 my previous energy amounthas been reset to zero

### What did you expect to happen?

Energy amount stay old counter

### How to reproduce it (minimal and precise)

go to z2mqt panel, go to OTA tab, check fw ugrade avialable for this device, and click: upgrade. Wait about 30 mins, and energy go to zero :/

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

![Adnotacja 2022-08-08 211248](https://user-images.githubusercontent.com/91805313/183497385-70711042-7556-40ed-80e2-46ec633eca69.jpg)
![Adnotacja 2022-08-08 211152](https://user-images.githubusercontent.com/91805313/183498081-1bfe557a-9c10-487b-b4a6-aef5c2336a9e.jpg)
![Adnotacja 2022-08-08 211026](https://user-images.githubusercontent.com/91805313/183497393-f32fd193-1749-49f4-a9c7-e350534f29a5.jpg)
![Adnotacja 2022-08-08 210848](https://user-images.githubusercontent.com/91805313/183497395-802cfecd-ee5f-4919-86a5-da0fafed3a86.jpg)
![Adnotacja 2022-08-08 210806](https://user-images.githubusercontent.com/91805313/183497396-45c2e2db-3eb6-4d1f-ac49-1957138bd9df.jpg)

**Comment by Koenkk** [comment]
I guess the FW update does this, not something that can be fixed from z2m.

**Comment by KitHubek** [comment]
I wonder if this counter reset after updating the software, if it broke and will no longer work. so far it still shows zero but there is very little consumption on this socket, it consumes about 2-3W so it will take a while before there is any consumption. 

Is there any way to send a command to the device that will record the state of consumed energy for example 20kWh and the device will now send this measurement + new consumption to add to it. And is there any option to downgrade the software to the previous one that worked properly?

**Comment by KitHubek** [comment]
Update just reset energy counter. After some time it starts counting from zero. 

![Adnotacja 2022-08-08 234841](https://user-images.githubusercontent.com/91805313/183520517-c00ec8f4-6487-4311-83a6-ff7f68c82216.jpg)

Is there any way to send a command to the device that will record the state of consumed energy for example 20kWh and the device will now send this measurement + new consumption to add to it.

**Comment by Koenkk** [comment]
> Is there any way to send a command to the device that will record the state of consumed energy for example 20kWh and the device will now send this measurement + new consumption to add to it.

The is no standard command available for this. In case there is such a command (should be checked with the original Xiaomi gateway) a sniff of this is necessary to add support for it. https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

**Comment by KitHubek** [comment]
ok. thanks for support
