### ISSUE TITLE
zigbee web login

### ISSUE THREAD

**Issue by JacekKac** [Koenkk/zigbee2mqtt#13495]
### What happened?

If you provide wrong password during initial login you are not able to correct it. Browser (chrome) remembers password, whole GUI is empty you cant re-type the password. Only going into Private mode helps. 

### What did you expect to happen?

wrong password dialog, and re-typing

### Zigbee2MQTT version

all

### Adapter firmware version

all

### Adapter

all

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
