### ISSUE TITLE
Using --production flag in npm install makes following start fail.

### ISSUE THREAD

**Issue by Lovasz-Akos** [Koenkk/zigbee2mqtt#13494]
### What happened?

If I use npm install --production command (mainly to save space) the followin npm start fails with this message
![image](https://user-images.githubusercontent.com/55391231/184094327-6da6005d-7d77-43b6-ac25-426389081116.png)

### What did you expect to happen?

initial build runs the same as if I installed it without production flag

### How to reproduce it (minimal and precise)

`npm install --production`
`npm start`

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

irrelevant

### Adapter

irrelevant

**Comment by Koenkk** [comment]
If you want to use `npm install --production` use the following commands:

```
npm ci
npm run build
rm -rf node_modules
npm install --production
```
