### ISSUE TITLE
Philips Hue 4023330P7 not supported

### ISSUE THREAD

**Issue by StigoSvK** [Koenkk/zigbee2mqtt#13492]
### What happened?

Succesfuly added Philips Hue Amaze suspension light in my zigbee2mqtt instance but I'm getting "Support status:
Not supported".
I'm able to add and fully control light via Philips Hue mobile app. Light is listed in my netwokrunder product number 929003054901 and regonized as router.  

Is this a new device?

Note:
I also have 2x Philips Hue white ambiance Still 3261330P6 which works like a charm.

Device is listed as supported https://www.zigbee2mqtt.io/devices/4023330P7.html
Product page https://www.philips-hue.com/en-gb/p/hue-white-ambiance-amaze-suspension-light/8719514341074#specifications

![image](https://user-images.githubusercontent.com/28844291/183996921-c614004e-0f51-40e0-bf99-b409457dc4b1.png)

Thanks for your help.

### What did you expect to happen?

Light shoud be added and recognized as other supported devices.

### How to reproduce it (minimal and precise)

Reset light and connect it into network.

### Zigbee2MQTT version

1.27.0-1

### Adapter firmware version

Z-Stack_Home_1.2 20211115/20211116

### Adapter

CC2531

### Debug log

[z2mlogs.txt](https://github.com/Koenkk/zigbee2mqtt/files/9303715/z2mlogs.txt)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
