### ISSUE TITLE
HA: invalid color mode

### ISSUE THREAD

**Issue by boehser-enkel** [Koenkk/zigbee2mqtt#13502]
### What happened?

Logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:336
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 14:15:45 (22 occurrences)
Last logged: 15:35:54

    Invalid color mode received
    Invalid or incomplete color value received

### What did you expect to happen?

No error

### How to reproduce it (minimal and precise)

Nothing. It gets logged from time to time

### Zigbee2MQTT version

1.27.0 commit: a9b8808 and also dev

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9309198/log.txt)

**Comment by groenmarsmannetje** [comment]
I also see the "Invalid color mode received" error appear frequently in my logs.
