### ISSUE TITLE
Group state based on individual devices states

### ISSUE THREAD

**Issue by Bojan023** [Koenkk/zigbee2mqtt#1351]
I've updated today to the latest firmware version for my CC2531 coordinator since I wanted support for groups. I'm using Homeassistant to control 12 Ikea bulbs plus 8 Aqara sensors and 3 wall switches. So far I can conclude it increases reliability enormously, my compliments! 

The thing which really bothers me is that state changes of devices (originating from outside a group) are not linked to/reported as group state afterwards. For instance: turn on all lights from group X with group command --> shut off all lamps within that group without group command --> group state still on (at least, in Homeassistant). It would be a pain in the ass to make automations for all Zigbee groups to check whenever group states should be changed if devices with a group are changing states. 

Is a group state report/sync functionality something that should be build into zigbee2mqtt or should this be implemented elsewhere?

**Comment by xoxys** [comment]
Would be awesome to have this in zigbee2mqtt

**Comment by Koenkk** [comment]
I'm currently working on this and it's almost ready, expect this soon (#1464)

**Comment by xoxys** [comment]
Good news

**Comment by xoxys** [comment]
@Koenkk Groups lost his state after restart home assistant is this also a known issue?

**Comment by Koenkk** [comment]
@xoxys that depends on how you configured groups in home assistant. Correct configuration can be found here: http://www.zigbee2mqtt.io/integration/home_assistant.html#groups

**Comment by Koenkk** [comment]
Implemented, for more info see: https://github.com/Koenkk/zigbee2mqtt/issues/764#issuecomment-487696964
