### ISSUE TITLE
[New device support]: Ynoa LA-GU10-CCT

### ISSUE THREAD

**Issue by timwar** [Koenkk/zigbee2mqtt#13513]
### Link

-

### Database entry

Zigbee2MQTT:debug 2022-08-12 11:36:27: Received MQTT message on 'homeassistant/light/0x847127fffe8cd1b5/light/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Ynoa_eettafel_01/availability"}],"availability_mode":"all","brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/Ynoa_eettafel_01/set","device":{"identifiers":["zigbee2mqtt_0x847127fffe8cd1b5"],"manufacturer":"Ynoa","model":"Ynoa Smart spot White Tones (LA-GU10-CCT)","name":"Ynoa_eettafel_01","sw_version":"2.07.03"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"json_attributes_topic":"zigbee2mqtt/Ynoa_eettafel_01","max_mireds":500,"min_mireds":150,"name":"Ynoa_eettafel_01","schema":"json","state_topic":"zigbee2mqtt/Ynoa_eettafel_01","supported_color_modes":["xy","color_temp"],"unique_id":"0x847127fffe8cd1b5_light_zigbee2mqtt"}' Zigbee2MQTT:debug 2022-08-12 11:36:27: Received MQTT message on 'homeassistant/sensor/0x847127fffe8cd1b5/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Ynoa_eettafel_01/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x847127fffe8cd1b5"],"manufacturer":"Ynoa","model":"Ynoa Smart spot White Tones (LA-GU10-CCT)","name":"Ynoa_eettafel_01","sw_version":"2.07.03"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Ynoa_eettafel_01","name":"Ynoa_eettafel_01_linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Ynoa_eettafel_01","unique_id":"0x847127fffe8cd1b5_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

### Comments

Was able to create convertor file, but bulb exposes more than what it actually can do. It is a warm white GU10 Bulb, but it exposes extra information like:
- **color_temp_startup**

Color temperature after cold power on of this light

- **color_xy**

Color of this light in the CIE 1931 color space (x/y)

Is this something caused by a fault in external conferter file or something the bulb exposes?

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBT-CCTLight-GU100001'],
    model: 'LA-GU10-CCT',
    vendor: 'Ynoa',
    description: 'Ynoa Smart spot White Tones',
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

### Supported color modes

-

### Color temperature range

-

**Comment by Koenkk** [comment]
Change `    extend: extend.light_onoff_brightness_colortemp_color(),` to `    extend: extend.light_onoff_brightness_colortemp(),`

Also please add the color temperature range as described on https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device
