### ISSUE TITLE
Livolo switch status change issues

### ISSUE THREAD

**Issue by sanychonline** [Koenkk/zigbee2mqtt#13531]
### What happened?

After changing switch status it incorrectly shows in Home app as not change, or does not show real status.
Example: trying to switch off light it shows switch off, then on, then off again. Sometimes it shows status as on, but switch is off. This issue does not exist in version 1.24.0 (still using it, as it works properly)

### What did you expect to happen?

Example: trying to switch off light it shows switch off, then on, then off again. Sometimes it shows status as on, but switch is off. This issue does not exist in version 1.24.0 (still using it, as it works properly)

### How to reproduce it (minimal and precise)

Example: trying to switch off light it shows switch off, then on, then off again. Sometimes it shows status as on, but switch is off. This issue does not exist in version 1.24.0 (still using it, as it works properly)

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20190608

### Adapter

CC2531 ZigBee - Texas Instruments, Inc.

### Debug log

16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/BathroomAccesoriesLights', payload '{"linkquality":49,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/LivingRoomLED', payload '{"linkquality":5,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/LivingRoomLights', payload '{"linkquality":7,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/KitchenLights', payload '{"linkquality":0,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:01
Zigbee2MQTT:info  2022-08-13 13:29:01: MQTT publish: topic 'zigbee2mqtt/ShowerLights', payload '{"linkquality":26,"state_bottom_left_bottom_left":"OFF","state_bottom_right_bottom_right":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:02
Zigbee2MQTT:info  2022-08-13 13:29:02: MQTT publish: topic 'zigbee2mqtt/KitchenLights', payload '{"linkquality":0,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:29:12
Zigbee2MQTT:info  2022-08-13 13:29:12: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":10,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:12
Zigbee2MQTT:info  2022-08-13 13:29:12: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":13,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:12
Zigbee2MQTT:info  2022-08-13 13:29:12: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":13,"state_left":"OFF","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:12
Zigbee2MQTT:info  2022-08-13 13:29:12: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:18
Zigbee2MQTT:info  2022-08-13 13:29:18: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":10,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:18
Zigbee2MQTT:info  2022-08-13 13:29:18: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"OFF","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:18
Zigbee2MQTT:info  2022-08-13 13:29:18: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:23
Zigbee2MQTT:info  2022-08-13 13:29:23: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":13,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:24
Zigbee2MQTT:info  2022-08-13 13:29:24: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"OFF","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:24
Zigbee2MQTT:info  2022-08-13 13:29:24: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":10,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:26
Zigbee2MQTT:info  2022-08-13 13:29:26: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":13,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:27
Zigbee2MQTT:info  2022-08-13 13:29:27: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":13,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:30
Zigbee2MQTT:info  2022-08-13 13:29:30: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:29:30
Zigbee2MQTT:info  2022-08-13 13:29:30: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"ON","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:29:30
Zigbee2MQTT:info  2022-08-13 13:29:30: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":21,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:32:57
Zigbee2MQTT:info  2022-08-13 13:32:57: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":18,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:32:57
Zigbee2MQTT:info  2022-08-13 13:32:57: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":18,"state_left":"OFF","state_left_left":"ON","state_right":"OFF"}'
stdout
16:32:57
Zigbee2MQTT:info  2022-08-13 13:32:57: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":15,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:33:02
Zigbee2MQTT:info  2022-08-13 13:33:02: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":18,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:33:02
Zigbee2MQTT:info  2022-08-13 13:33:02: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":21,"state_left":"ON","state_left_left":"ON","state_right":"OFF"}'
stdout
16:33:02
Zigbee2MQTT:info  2022-08-13 13:33:02: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":21,"state_left":"ON","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:02
Zigbee2MQTT:info  2022-08-13 13:33:02: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":23,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:16
Zigbee2MQTT:info  2022-08-13 13:33:16: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:16
Zigbee2MQTT:info  2022-08-13 13:33:16: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":52,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:16
Zigbee2MQTT:info  2022-08-13 13:33:16: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":52,"state_bottom_left_bottom_left":"OFF","state_left":"ON","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:25
Zigbee2MQTT:info  2022-08-13 13:33:25: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":52,"state_bottom_left_bottom_left":"OFF","state_left":"ON","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:25
Zigbee2MQTT:info  2022-08-13 13:33:25: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":52,"state_bottom_left_bottom_left":"OFF","state_left":"ON","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:27
Zigbee2MQTT:info  2022-08-13 13:33:27: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":52,"state_bottom_left_bottom_left":"OFF","state_left":"ON","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:28
Zigbee2MQTT:info  2022-08-13 13:33:28: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"ON","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:28
Zigbee2MQTT:info  2022-08-13 13:33:28: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:49
Zigbee2MQTT:info  2022-08-13 13:33:49: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:49
Zigbee2MQTT:info  2022-08-13 13:33:49: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:49
Zigbee2MQTT:info  2022-08-13 13:33:49: MQTT publish: topic 'zigbee2mqtt/HallLED', payload '{"linkquality":5,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:49
Zigbee2MQTT:info  2022-08-13 13:33:49: MQTT publish: topic 'zigbee2mqtt/BathroomAccesoriesLights', payload '{"linkquality":49,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:49
Zigbee2MQTT:info  2022-08-13 13:33:49: MQTT publish: topic 'zigbee2mqtt/BedroomLights', payload '{"linkquality":0,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/BedroomLights', payload '{"linkquality":5,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/Wardrobe', payload '{"linkquality":23,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/LivingRoomLED', payload '{"linkquality":5,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/HallLights', payload '{"linkquality":2,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/LivingRoomLights', payload '{"linkquality":10,"state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/BathroomLights', payload '{"linkquality":55,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/ShowerLights', payload '{"linkquality":26,"state_bottom_left_bottom_left":"OFF","state_bottom_right_bottom_right":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:33:50
Zigbee2MQTT:info  2022-08-13 13:33:50: MQTT publish: topic 'zigbee2mqtt/KitchenLights', payload '{"linkquality":0,"state_bottom_left_bottom_left":"OFF","state_left":"OFF","state_left_left":"OFF","state_right":"OFF","state_right_right":"OFF"}'
stdout
16:34:21
Zigbee2MQTT:info  2022-08-13 13:34:21: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
stdout
16:34:21
Zigbee2MQTT:info  2022-08-13 13:34:21: Disconnecting from MQTT server
stdout
16:34:21
Zigbee2MQTT:info  2022-08-13 13:34:21: Stopping zigbee-herdsman...
stdout
16:34:22
Zigbee2MQTT:info  2022-08-13 13:34:22: Stopped zigbee-herdsman
stdout
16:34:22
Zigbee2MQTT:info  2022-08-13 13:34:22: Stopped Zigbee2MQTT

**Comment by ashway83** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4550

**Comment by Koenkk** [comment]
Fixed by @ashway83 in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4550

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
