### ISSUE TITLE
Possible to have router to router connections?

### ISSUE THREAD

**Issue by LucaKaufmann** [Koenkk/zigbee2mqtt#1353]
I've been trying to move all my Zigbee devices to Zigbee2MQTT but have been struggling to get it to work reliably. I think the issue is that I have too many light bulbs (around 13 right now, about to add some more). When checking the network map, they all seem to connect to the coordinator. Eventually they build up a network, but every bulb always has a direct connection to the coordinator. Is this just how Zigbee is supposed to work? Routers are connecting to the Coordinator and end devices connecting to the routers? Or is it possible to have a Router > Router > Coordinator connection.

How do other people here handle networks with a lot of light bulbs? I only have about half of them connected now and it seems to work mostly stable, but I'd eventually like to have just one single Zigbee network.

**Comment by Koenkk** [comment]
Routers can also connect to routers, note that the networkmap isn't completely reliable. I wouldn't worry if everything works reliable, Zigbee will figure this out for you.
