### ISSUE TITLE
INNR SP 120 not reporting measurements anymore

### ISSUE THREAD

**Issue by Vout** [Koenkk/zigbee2mqtt#1354]
Not sure why it is happening, it worked for a few months but since an week i'm having issues with the measurements of the INNR SP 120 power plugs.

Switching the plugs on and off works fine but i'm getting these messages also,

```AM No converter available for 'SP 120' with cid 'seMetering', type 'devChange' and data '{"cid":"seMetering","data":{"currentSummDelivered":[null,5068]}}'```

Which is kind of strange because it all worked before. I'm not aware of something that has changed last week that could be the cause of this, Hassio latest version 0.90.2 + zigbee2mqtt latest version of software and firmware.

I tried repairing the plugs but i can't get the measurements working anymore. Strange thing is that sometimes i'm seeing these messages.... 

```zigbee2mqtt:info 3/31/2019, 10:06:46 AM MQTT publish: topic 'zigbee2mqtt/INNR powerplug 1', payload '{"state":"ON","linkquality":94,"power":6,"voltage":241,"current":0.04}'```

So it looks like it some kind of working but i'm getting these messages once every x minutes while before i had a message every 5 seconds.

**Comment by Koenkk** [comment]
The message that you see are probably (old) cached values. I've also experienced this once with my SP 120, still not sure what caused this. I got it fixed by removing (http://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove) the device and re-pairing it.
