### ISSUE TITLE
Legrand 600086: no synchronization of the position when managing the shutter manually

### ISSUE THREAD

**Issue by Alindil** [Koenkk/zigbee2mqtt#13566]
### What happened?

The position does not synchronise when closing or opening the shutters manually. But wehn
![image](https://user-images.githubusercontent.com/30829631/184910641-b7d964bc-403f-47fe-8765-c66ef7bb20b9.png)
But if I click on the position sync. The value is well synchronised

### What did you expect to happen?

I think that the synchronization should be done automatically after a given time

### How to reproduce it (minimal and precise)

Device: Legrand dooxie 600086 but when I associate, it is recognised as 067776
![image](https://user-images.githubusercontent.com/30829631/184911698-3402fea6-cd04-4aaa-9744-b985f4643900.png)

You just have to close and open the flaps manually to see that the position is not updated
![image](https://user-images.githubusercontent.com/30829631/184912489-a9e9ce77-7a89-4341-b622-4a450f53a7d4.png)

### Zigbee2MQTT version

1.27.0 commit: a9b8808

### Adapter firmware version

20210708

### Adapter

SONOFF ZigBee 3.0 USB

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: [' Shutter switch with neutral\u0000\u0000\u0000'],
    model: '067776',
    vendor: 'Legrand',
    description: 'Netatmo wired shutter switch',
    // the physical LED will be green when permit join is true, off otherwise and red when not linked
    fromZigbee: [
        // Devices can send an identify message when the configuration button is pressed
        // (behind the physical buttons)
        // Used on the official gateway to send to every devices an identify command (green)
        fz.identify, fz.ignore_basic_report,
        // support binary report on moving state (supposed)
        fz.legrand_binary_input_moving, fz.cover_position_tilt],
    toZigbee: [tz.cover_state, tz.cover_position_tilt, tz.legrand_identify, tz.legrand_settingAlwaysEnableLed],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBinaryInput', 'closuresWindowCovering', 'genIdentify']);
        await reporting.currentPositionLiftPercentage(endpoint);
    },
    exposes: [e.cover_position()],
};

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Alindil** [comment]
Hello,
the correction works perfectly. 
I would like to take advantage of this issue to suggest another point. 
When you click on the close, open and stop buttons in zigbee2mqtt, the position is not updated either. It might be better if open = 100 (if not inverted), close = 0 (if not inverted) and stop = 50
![image](https://user-images.githubusercontent.com/30829631/185076645-50c0795d-e158-4562-bf8e-de2f2b26dae9.png)

**Comment by Alindil** [comment]
@Koenkk 
I tested under docker on the image koenkk/zigbee2mqtt:latest-dev and it does not work. 
Initial status with the shutter open:
![image](https://user-images.githubusercontent.com/30829631/185426841-8416efc1-9ec0-4bce-90e0-3eb8e0ba10a6.png)

When I click on the closed button:
![image](https://user-images.githubusercontent.com/30829631/185427186-fcd4c68e-5b99-4f8b-bd89-6fc8dbf421f1.png)

When I click on the synchronization button:
![image](https://user-images.githubusercontent.com/30829631/185427432-b5a462a3-a158-4dfb-9af6-c6e4716867d8.png)

**Comment by Koenkk** [comment]
Does the `state` updated when you change the shutter position manually? Position 0 should show `CLOSE`, anything else `OPEN`.

**Comment by Alindil** [comment]
Yes, manually it works. And when I ask for the action to close for mqtt (not using the position 0), the shutter closes well but the status is still open and the position is at 100And when I ask for the action to close (not using the action position= 0), the shutter closes well but the status is still open and the position is 100 (or 50 if it was between open)

**Comment by M-Gregoire** [comment]
I believe this issue is not stale as the problem described is still existing.
I'd be happy to help in the resolution if I can.

**Comment by novisys** [comment]
same issue here !
Can reopen this issue or we need to open new one ?
Thanks
