### ISSUE TITLE
Tuya Girier and Lonsonho Dimmer issue

### ISSUE THREAD

**Issue by roy81f** [Koenkk/zigbee2mqtt#13561]
### What happened?

i tried Gierier and Lonsonho Dimmers, both are suffering the same issue, it's possible to turn them manually On\Off (Z2M expose implementation) but both don't light on automations, it doesn't matter if I'm using Device Light on or Call Service,   it seems the switch is turned on by Z2M interface but no light.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20220219

### Adapter

ZZH

**Comment by Koenkk** [comment]
If I understand correctly; when trying to turn on a device from HA nothing happens in z2m? If yes, can you provide me the z2m debug log the moment you turn the device on from HA

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
