### ISSUE TITLE
Remove device in mosquitto.db

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#1356]
Hi,

I have a problem in HomeAssistant, when I delete a Z2M zigbee device, mqtt does not remove it from its database, and in home assistant appears continuously, is it possible that when doing the remove to Z2M, it is also removed from the mqtt database?
I have in HA several devices that I no longer have connected.

**Comment by frank3523** [comment]
Maybe this link is helpfull

https://github.com/Koenkk/zigbee2mqtt/issues/835
