### ISSUE TITLE
Z2M accepting colour temp when light is off, but not reflecting it when light is turned on

### ISSUE THREAD

**Issue by amilanov75** [Koenkk/zigbee2mqtt#13562]
### What happened?

Colour temp values sent to Philips Hue White Ambience GU10 and Ikea Tradfri 345w bulbs, when the bulbs are off, are accepted by Z2M. 
When the lights are subsequently turned on, the colour temp is at the last value when the light was turned off

### What did you expect to happen?

Either the colour temp command should NOT be accepted by Z2M, or when the light is subsequently turned on, the colour temp should be set to the value sent to the light when it was turned turned off i.e. the value that Z2M is currently accepting when the light is off

### How to reproduce it (minimal and precise)

Described above - send colour temp value to light when off, turn light on.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220302

### Adapter

cc2652P2 USB stick zigbee2mqtt ZigBee Zigstar v4

### Debug log

coming

**Comment by sjorge** [comment]
Depending on the light you need to configure it to allow color changes when off.

```
mosquitto_pub -t zigbee2mqtt/FRIENDLYNAME/set/color_options -m '{"execute_if_off": true}'
```
