### ISSUE TITLE
[New device support]: Tuya RGBCW Downlight, modelID 'TS0505B', manufacturerName: '_TZ3210_3lbtuxgp'

### ISSUE THREAD

**Issue by Yami661995** [Koenkk/zigbee2mqtt#13579]
### Link

https://www.lazada.vn/products/10w12w-tuya-zigbee-30-smart-led-downlight-rgbcw-354-inch-round-ceiling-lamp-indoor-spot-lighting-alexa-smartthings-i1635053360-s7149162202.html?

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xa4c138e1183cf41c","nwkAddr":2370,"manufId":4417,"manufName":"_TZ3210_3lbtuxgp","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1660731307808,"defaultSendRequestWhen":"immediate"}

### Comments

Hello, i bought some RGBCW LED Downlights but they are not supported.
I added them successfully with external converter, but there still missing converter for type 'commandActiveStatusReport', 

info 2022-08-17 17:15:05Successfully interviewed '0xa4c138e1183cf41c', device has successfully been paired
info 2022-08-17 17:15:05Device '0xa4c138e1183cf41c' is supported, identified as: TuYa Zigbee smart downlight RGB+CCT (TS0505B)
info 2022-08-17 17:15:05MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee smart downlight RGB+CCT","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":150},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500}],"property":"color_temp","type":"numeric","unit":"mired","value_max":500,"value_min":150},{"access":7,"description":"Color temperature after cold power on of this light","name":"color_temp_startup","presets":[{"description":"Coolest temperature supported","name":"coolest","value":150},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500},{"description":"Restore previous color_temp on cold power on","name":"previous","value":65535}],"property":"color_temp_startup","type":"numeric","unit":"mired","value_max":500,"value_min":150},{"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0505B","options":[{"access":2,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).","name":"transition","property":"transition","type":"numeric","value_min":0},{"access":2,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).","name":"color_sync","property":"color_sync","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0xa4c138e1183cf41c","ieee_address":"0xa4c138e1183cf41c","status":"successful","supported":true},"type":"device_interview"}'
info 2022-08-17 17:15:05Configuring '0xa4c138e1183cf41c'
debug 2022-08-17 17:15:05Received Zigbee message from '0xa4c138e1183cf41c', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorCapabilities":25}' from endpoint 1 with groupID 0
debug 2022-08-17 17:15:05Missing colorTempPhysicalMin and/or colorTempPhysicalMax for endpoint 0xa4c138e1183cf41c!
info 2022-08-17 17:15:05MQTT publish: topic 'zigbee2mqtt/0xa4c138e1183cf41c', payload '{"color_mode":"xy","linkquality":66,"state":null}'
debug 2022-08-17 17:15:05Received Zigbee message from '0xa4c138e1183cf41c', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTempPhysicalMax":500,"colorTempPhysicalMin":153}' from endpoint 1 with groupID 0
info 2022-08-17 17:15:05MQTT publish: topic 'zigbee2mqtt/0xa4c138e1183cf41c', payload '{"color_mode":"xy","linkquality":63,"state":null}'
info 2022-08-17 17:15:05Successfully configured '0xa4c138e1183cf41c'
debug 2022-08-17 17:15:06Received Zigbee message from '0xa4c138e1183cf41c', type 'commandActiveStatusReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[255,255,255,206],"type":"Buffer"},"datatype":2,"dp":81}],"seq":256}' from endpoint 1 with groupID 0
debug 2022-08-17 17:15:06No converter available for 'TS0505B' with cluster 'manuSpecificTuya' and type 'commandActiveStatusReport' and data '{"dpValues":[{"data":{"data":[255,255,255,206],"type":"Buffer"},"datatype":2,"dp":81}],"seq":256}'

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    fingerprint: [
        {
            modelID: 'TS0505B',
            manufacturerName: '_TZ3210_3lbtuxgp'
        },
    ],
    model: 'TS0505B',
    vendor: 'TuYa',
    description: 'Zigbee smart downlight RGB+CCT',
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}),
};

module.exports = definition;
```

### Supported color modes

color temperature, rgb

### Color temperature range

colorTempPhysicalMin:153, colorTempPhysicalMax:500

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
