### ISSUE TITLE
KCTW1Z No battery reading

### ISSUE THREAD

**Issue by whakru** [Koenkk/zigbee2mqtt#13598]
### What happened?

https://www.zigbee2mqtt.io/devices/KCTW1Z.html
no indicators:
battery_low
battery

![image](https://user-images.githubusercontent.com/22603145/185502231-38ce6115-74f0-4a82-8ccf-857b630194e7.png)

### Zigbee2MQTT version

 1.27.0

### Adapter firmware version

20220301

### Adapter

zStack3x0

**Comment by whakru** [comment]
not fixed

**Comment by Koenkk** [comment]
@kirovilya do we know the data points for this?

**Comment by kirovilya** [comment]
It is good for me when click on back button:
![image](https://user-images.githubusercontent.com/8360230/191098282-b7edfd9e-1703-444d-a1fb-c9b8d50b133d.png)
![image](https://user-images.githubusercontent.com/8360230/191098322-bc1677d9-924b-4d3c-a14a-0f8efc3d8c46.png)
Let's try to add reporting...

**Comment by whakru** [comment]
Indeed, after pressing the back button, the battery readings appear.

**Comment by Koenkk** [comment]
Should be fixed now!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
