### ISSUE TITLE
[New device support]: Philips Hue Sana 929003053001

### ISSUE THREAD

**Issue by callaa** [Koenkk/zigbee2mqtt#13606]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-and-colour-ambiance-sana-wall-light/8719514343405

### Database entry

{"id":53,"type":"Router","ieeeAddr":"0x0017880109c68c41","nwkAddr":34750,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003053001","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003053001","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1660921109341,"defaultSendRequestWhen":"immediate"}

### Comments

I tested this with the same converter as model 4090130P7. Setting brightness, temperature and color all work.

### External converter

```shell
{
                zigbeeModel: ['929003053001'],
                model: '929003053001',
                vendor: 'Philips',
                description: 'Hue Sana',
                extend: hueExtend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}),
        }
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
