### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by Suligol** [Koenkk/zigbee2mqtt#13605]
### Link

https://www.amazon.fr/gp/product/B09W8JHQX9/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0xa4c13831f6af2dc1","nwkAddr":25265,"manufId":4417,"manufName":"_TZ3210_95txyzbx","powerSource":"Mains (single phase)","modelId":"TS0503B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0503B","manufacturerName":"_TZ3210_95txyzbx","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1660920802051,"defaultSendRequestWhen":"immediate"}

### Comments

Hi,
It's an TS0503B from Tuya but with another manufacter ( _TZ3210_95txyzbx )
per advance, lot of thanks ;)
Jérôme.

**Comment by Koenkk** [comment]
`_TZ3210_95txyzbx` is already supported in the dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
