### ISSUE TITLE
Confusing dashbord items Blitzwolf TS11F_plug_3

### ISSUE THREAD

**Issue by dykst002** [Koenkk/zigbee2mqtt#13612]
### What happened?

![28C155BF-4727-4109-91F9-48515F9E460F](https://user-images.githubusercontent.com/59477706/185698746-72ec0467-28fd-4a53-8315-f71e25b6de18.jpeg)

### What did you expect to happen?

See my picture

### How to reproduce it (minimal and precise)

The shows the solution

### Zigbee2MQTT version

1.27.0-1

### Adapter firmware version

2022

### Adapter

Sonoff zigbee 3.0

### Debug log

No logging

**Comment by dykst002** [comment]
Sorry did not know the firmware version of my sonoff stick. I found it “20210708” so an old version. I think this nothing to do with my issue

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by dykst002** [comment]
OK
