### ISSUE TITLE
Issue connecting to frontend

### ISSUE THREAD

**Issue by rodgrech** [Koenkk/zigbee2mqtt#13614]
### What happened?

error 502 when accessing the front end

this has been happening for the last week

### What did you expect to happen?

to access the frontend and be able to control devices

### How to reproduce it (minimal and precise)

multiple reinstalls of edge or normal variant

### Zigbee2MQTT version

1.27.0-dev (commit #304bb7b)

### Adapter firmware version

20220820

### Adapter

EZSP v8

### Debug log

info  2022-08-20 07:38:16: Logging to console and directory: '/config/zigbee2mqtt/log/2022-08-20.07-38-16' filename: log.txt
info  2022-08-20 07:38:16: Starting Zigbee2MQTT version 1.27.0-dev (commit #304bb7b)
info  2022-08-20 07:38:16: Starting zigbee-herdsman (0.14.48)
error 2022-08-20 07:38:16: Error while starting zigbee-herdsman
error 2022-08-20 07:38:16: Failed to start zigbee
error 2022-08-20 07:38:16: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-08-20 07:38:16: Exiting...
error 2022-08-20 07:38:16: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:146:24)
    at Socket.emit (node:events:539:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Koenkk** [comment]
> error 2022-08-20 07:38:16: Error: Error while opening socket

Your adapter configuration is not correct; check your adapter and config.
