### ISSUE TITLE
Pairing new devices with SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P as coordinator doesn't work

### ISSUE THREAD

**Issue by mcruscher** [Koenkk/zigbee2mqtt#13633]
### What happened?

Trying to add new devices to my network. With my previous coordinator (CC2531) no problems adding devices. After upgrade to CC2652P (Sonoff) adding devices isn't working. Other devices that were previous added with CC2531 are working fine.

### What did you expect to happen?

To add devices to my network.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20220219

### Adapter

CC2652P - Sonoff Zigbee - P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9389721/log.txt)

**Comment by Koenkk** [comment]
Let's keep this in https://github.com/Koenkk/zigbee2mqtt/issues/12916
