### ISSUE TITLE
Problem with ZB_A60_RGBCW not turning off when transition is specified

### ISSUE THREAD

**Issue by TrueCyberAxe** [Koenkk/zigbee2mqtt#13632]
### What happened?

I have 2 of these bulbs in my kitchen, if any transition value is given when turning the bulbs off this will prevent the bulbs turning off, reguardless of given as off or given as brightness: 0, the current support adds Settings (specific) with a transition value, but if any value is used even 0 then it causes the bulb to not turn off, the only way to fix this is to manually edit the zigbee2mqtt > devices.yaml and delete the transition values under the device

To get these bulbs to smoothly transition off they have to be set to a brightness of 1 with desired transition (I have seen behaviour where any value less than 3 will result in bulbs remaining on at low light level but reporting as off, however not able to recreate currently), and then turned off without a transition value

I have tried various values, it seems the bulbs do support them for turning on but when turning off it just causes the bulbs to stop working.

Also the name for them should probbaly be changed in description from "Smart Zigbee pro 12W A60 RGBCW bulb" to "Smart Zigbee 12W A60 bulb" as these are just the non pro version that the AJ_ZIGPROA60 has replaced

### What did you expect to happen?

I expected bulbs to turn off, but they did not change at all, mqtt explorer confirmed the correct values were being sent to the bulb

### How to reproduce it (minimal and precise)

Under Settings (specific) change transition to any value

With the light turned on try to toggle state to off, or change brightness to 0

bulb will remain at previous state

### Zigbee2MQTT version

1.27.0-1

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee 3.0 USB Dongle plus

**Comment by teewhey** [comment]
Facing this issue as well. 
Using this device : https://www.zigbee2mqtt.io/devices/ZB-RGBCW.html#lonsonho-zb-rgbcw

So I removed the device and re-pair it and left the Transition settings alone.
