### ISSUE TITLE
[Feature request]: Add the option to define 'Friendly name' also for bridges/gateways

### ISSUE THREAD

**Issue by jsponz** [Koenkk/zigbee2mqtt#13639]
### Is your feature request related to a problem? Please describe

Not, really. But I have two bridges at home and I would like to be able to manage them independently. 

### Describe the solution you'd like

Create a variable in the config file in a similar way as for the devices, or for the base topic.

### Describe alternatives you've considered

None. 

### Additional context

None.

**Comment by Koenkk** [comment]
The base topic can be defined with the `base_topic` option as documented here: https://www.zigbee2mqtt.io/guide/configuration/mqtt.html
