### ISSUE TITLE
NPM errors after running on Raspberry - failed to start

### ISSUE THREAD

**Issue by Kratax** [Koenkk/zigbee2mqtt#1364]
Running fresh install, following the instructions, end up with the following log... Latest firmware and version of zigbee2mqtt.

Tried to restart on the stick and also raspberry. 

Thanks a lot for help!

https://pastebin.com/9frBq15A

**Comment by joostjdj** [comment]
I actually have the exact same issue. Installed today as well.

**Comment by jonnycastaway** [comment]
You have to install Nodejs 10. With Raspbain an older Nodejs is installed.

**Comment by joostjdj** [comment]
For me 10 is already installed now, and still issues

Op wo 3 apr. 2019 10:15 schreef jonnycastaway <notifications@github.com>:

**Comment by Koenkk** [comment]
Please provide the `npm start` log

**Comment by Kratax** [comment]
Hi,
thanks for suggestion, I have tried to update Nodejs, still not working, log attached below...

https://pastebin.com/r5MUmxD9

**Comment by Koenkk** [comment]
This is not the kind of log I'm expecting, you can find the correct logs in `data/log`

**Comment by Kratax** [comment]
Hi, 
Here you go

https://pastebin.com/LfmcW76A


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Koenkk** [comment]
What is the output of `ls /dev` and whats in your configuration.yaml?

**Comment by Kratax** [comment]
Ls /dev 
https://pastebin.com/0CpA4PQA

Config
https://pastebin.com/CN9WN4wi


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Koenkk** [comment]
Can you both follow: http://www.zigbee2mqtt.io/information/zigbee2mqtt_fails_to_start.html

**Comment by Kratax** [comment]
Hi, I have followed the steps... unfortunatelly no success, details from terminal attached...

https://pastebin.com/y3JB29AN

**Comment by Koenkk** [comment]
Unfortunately, everything looks OK, somehow the communication with the CC2531 fails. Can you try this on a different system? My other guess is that the CC2531 is broken somehow.

**Comment by didiht** [comment]
Did you reset the Zigbee Stick?
