### ISSUE TITLE
RTCGQ11LM Temperature Issues

### ISSUE THREAD

**Issue by Wikibear** [Koenkk/zigbee2mqtt#13653]
### What happened?

Topic temperature doesn't change and stay at 23°C.
Topic device temperature to high.
Missing temperature at details web gui.

### What did you expect to happen?

Temperature no needed? Only device temperature?
If no, then both temperatures must be shown on details page of web gui.
Expect both same temperatures.

### Zigbee2MQTT version

1.27.0-dev commit: 9e6b4083

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

![grafik](https://user-images.githubusercontent.com/18314278/186222243-5dd7b4fa-8327-4429-9df8-aa01a3108fc7.png)
![grafik](https://user-images.githubusercontent.com/18314278/186222503-772319fd-0b46-4aa6-bffe-31b4995514dd.png)

**Comment by Koenkk** [comment]
`temperature` has been renamed to `device_temperature`, you have to remove the stale `temperature` value from the `data/state.json` manually (first stop z2m)
