### ISSUE TITLE
[New device support]: TS0502B - _TZB210_nfzrlz29 LED dimmer

### ISSUE THREAD

**Issue by NuttShell** [Koenkk/zigbee2mqtt#13666]
### Link

https://aliexpress.ru/item/1005003379938506.html?sku_id=12000025512743438

### Database entry

{"id":29,"type":"Router","ieeeAddr":"0xa4c1384cb6f5215b","nwkAddr":33580,"manufId":4417,"manufName":"_TZB210_nfzrlz29","powerSource":"Mains (single phase)","modelId":"TS0502B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":"","zclVersion":3}},"lightingColorCtrl":{"attributes":{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1661344053502,"defaultSendRequestWhen":"immediate"}

### Comments

Not supported in z2m and z2m edge.

### External converter

Tryed this:

// modelID: TS0502B
// manufacturerName:_TZB210_nfzrlz29
// model: ZB3.0-CCT

const extend = require('zigbee-herdsman-converters/lib/extend');
const definition = {
        fingerprint: [{modelID: 'TS0502B', manufacturerName: '_TZB210_nfzrlz29'},],
        model: 'ZB3.0-CCT',
        vendor: 'TuYa',
        description: 'ZB3.0-CCT',
        whiteLabel: [
            {vendor: 'MJJC', model: 'ZB3.0-CCT'},
        ],
	extend: extend.light_onoff_brightness_color(),
        meta: {applyRedFix: true, enhancedHue: false},
};
module.exports = definition;

It works, but transition is very strange. If set transition to 0 and decrease brightness from big to very small value, it seems like transition is very big.

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
