### ISSUE TITLE
Many reconnect attempts after mqtt server shortly unavailable

### ISSUE THREAD

**Issue by y0ast** [Koenkk/zigbee2mqtt#1367]
Last night I accidentally flooded the network of my pi, so z2m wasn't able to connect to the mqtt server:

```
4/3/2019, 9:44:40 PM - error: Not connected to MQTT server!
4/3/2019, 9:44:47 PM - error: Not connected to MQTT server!
4/3/2019, 9:44:57 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:00 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:00 PM - error: Cannot send message: topic: 'zigbee2mqtt/0x00158d000257f40b', payload: '{"illuminance":0,"linkquality":39,"occupancy":false,"battery":100,"voltage":3015}
4/3/2019, 9:45:00 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:00 PM - error: Cannot send message: topic: 'zigbee2mqtt/0x00158d000257f40b', payload: '{"illuminance":0,"linkquality":39,"occupancy":true,"battery":100,"voltage":3015}
4/3/2019, 9:45:07 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:17 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:27 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:37 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:47 PM - error: Not connected to MQTT server!
4/3/2019, 9:45:57 PM - error: Not connected to MQTT server!
4/3/2019, 9:46:07 PM - error: Not connected to MQTT server!
4/3/2019, 9:46:13 PM - info: Connected to MQTT server
4/3/2019, 9:46:13 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
```

It then reconnected a whole bunch of times within 3 seconds:

```
4/3/2019, 9:46:33 PM - info: Connected to MQTT server
...
4/3/2019, 9:46:37 PM - info: Connected to MQTT server
...
4/3/2019, 9:46:40 PM - info: Connected to MQTT server
```
etc etc. I have about 22MB of logs spread over 3 files with just reconnect output.

On every connection it sends the templates to HA, creating huge amounts of MQTT traffic and killing the CPU (also caused by HA).

From the logs it seems that every 10 seconds there is a ping from z2m to see if the mqtt server is online (+ extra times when a zigbee message arrives). However the reconnects happen every 3 seconds, so could it be that there are many reconnect attempts queued up and not properly freed?

 Perhaps an exponentially growing reconnect attempt time would help.

The only solution to my problem was to stop z2m or the network flood. It would have been nice if z2m failed gracefully instead of swamping the CPU.

**Comment by mitzuca** [comment]
Hi i have same problem ...........
