### ISSUE TITLE
Possible to change broker IP when running docker cotainer?

### ISSUE THREAD

**Issue by seaside1** [Koenkk/zigbee2mqtt#1371]
Fist off, awesome work in this project!

For the docker image, it would be handy to have a way of specifying mqtt topic and broker ip when running the docker image. I know this can be changed in configuration.yaml, but for us that are not using HASS this would be handy and building the docker image from the source is somewhat cumbersome.

**Comment by j4c3** [comment]
I keep that file out of the docker image using the following in my docker command.  Then you can just modify the configuration.yaml and restart the container:

-v /share/CACHEDEV1_DATA/Store/HomeAutomation/zigbee2mqtt/data:/app/data

**Comment by seaside1** [comment]
That works!
Thanks!
