### ISSUE TITLE
Force battery powered devices to connect only to a specific Router

### ISSUE THREAD

**Issue by avvalex** [Koenkk/zigbee2mqtt#13726]
### What happened?

I have two Vimar 14592.0 two-way switch that works very well, and that offer very good connection (70-100 LQI) to a IKEA Tradfri Button and to a Develco smoke detector.
But i have an annoying problem: when there is a power outage, my coordinator is under UPS while my Vimars are not, so end devices loses connection with router and reconnect almost instantly to coordinator with very poor LQI (0 to 3), and smoke detector after some time gives red triangle and connection problems. Apparently the don't switch back to router.
Is there a way to lock connection to router, permit join only to router, or block connection to coordinator. How can i solve tris problem?

### What did you expect to happen?

End devices reconnects always with same router.

### How to reproduce it (minimal and precise)

Remove power to Vimar switches for some minutes.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20220219

### Adapter

Z-Bee Duo. Modular CC2652P zigbee 3.0 adapter

**Comment by Koenkk** [comment]
This is not possible, Zigbee doesn't have such feature.
