### ISSUE TITLE
Change status topic to HA default values

### ISSUE THREAD

**Issue by lsaadeh** [Koenkk/zigbee2mqtt#13759]
### What happened?

HA default values: homeassistant/status
Zigbee2mqtt default values: hass/status

https://www.home-assistant.io/docs/mqtt/birth_will/

### Zigbee2MQTT version

latest

### Adapter firmware version

n/a

### Adapter

n/a

**Comment by Koenkk** [comment]
This is to prevent a breaking change. `homeassistant/status` will always be used, see https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html#advanced-configuration
