### ISSUE TITLE
[New device support]: EasyFingerTouch, Onesti Products AS

### ISSUE THREAD

**Issue by ricmik** [Koenkk/zigbee2mqtt#13768]
### Link

https://easyaccess.no/product/easyring-lock-module/

### Database entry

{"id":9,"type":"EndDevice","ieeeAddr":"0xf4ce366aa3221da3","nwkAddr":60658,"manufId":4660,"manufName":"Onesti Products AS","powerSource":"DC Source","modelId":"EasyFingerTouch","epList":[11],"endpoints":{"11":{"profId":260,"epId":11,"devId":10,"inClusterList":[0,1,3,5,4,257,65186],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"EasyFingerTouch","manufacturerName":"Onesti Products AS","powerSource":4,"zclVersion":2,"appVersion":7,"stackVersion":10,"hwVersion":11,"dateCode":"20220614","swBuildId":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":10,"hwVersion":11,"dateCode":"20220614","swBuildId":"","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1661863897829,"defaultSendRequestWhen":"immediate"}

### Comments

I requested a firmware file from EasyAccess for my EasyFingerTouch lock since I did not get any user reports when using the lock, but got a new module sent to me instead.

The old module had the Zigbee model "easyCodeTouch_v1" but the new module is Zigbee model "EasyFingerTouch" and is not supported by zigbee2mqtt.

**Comment by ricmik** [comment]
By the way, I wonder why it reports that it is powered by DC power, when it is actually powered by batteries..

**Comment by Koenkk** [comment]
Added the new model and fixed the power source.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
