### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by dalet11** [Koenkk/zigbee2mqtt#13770]
### Link

https://www.aliexpress.com/item/1005004247445088.html?spm=a2g0o.order_list.0.0.1f241802lk2R0f

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0xa4c1383017736675","nwkAddr":44784,"manufId":4417,"manufName":"_TZ3210_r5afgmkl","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":"","zclVersion":3,"appVersion":101}},"genOnOff":{"attributes":{"onOff":1}},"genIdentify":{"attributes":{"identifyTime":0}},"genScenes":{"attributes":{"currentScene":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":101,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1661876998607,"defaultSendRequestWhen":"immediate"}

### Comments

i but it from AliExpress, its Tuya. some comments on product page say it was working fine with z2m so i guess i got a new sub-model or something. i can see that basicly TS0505B is supported.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
