### ISSUE TITLE
I"Invalid color mode received" on autodetected light group

### ISSUE THREAD

**Issue by JanJoh** [Koenkk/zigbee2mqtt#13779]
### What happened?

I added two new IKEA [LED2003G10](https://www.zigbee2mqtt.io/devices/LED2003G10.html#ikea-led2003g10) and created a group. 

The devices show in Zigbee2mqtt as having brightness and color temp as expected. 

In HA the group only shows as "On off" light and I get many of the following

Logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:336
Integration: MQTT (documentation, issues)
First occurred: 12:38:18 (94 occurrences)
Last logged: 16:21:54

Invalid color mode received

### Zigbee2MQTT version

1.27.0 

### Adapter firmware version

20220219

### Adapter

Slaesh CC2652RB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9462414/log.txt)

**Comment by groenmarsmannetje** [comment]
I also see the "Invalid color mode received" error appear frequently in my logs.
And also have mainly, multiple IKEA light bulbs together with some Muller Light and Trust bulbs.
