### ISSUE TITLE
Ugly OTA message: No image available for imageType '5634'

### ISSUE THREAD

**Issue by inrepublica** [Koenkk/zigbee2mqtt#13787]
### What happened?

When asking for updates, an ugly error appears. I don't know if this is expected, but seems more like a no controlled error. The device is a TS011F_plug_3.
[https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3](url)

### How to reproduce it (minimal and precise)

Simply go to OTA page and press to ckeck for updates.

### Zigbee2MQTT version

1.27.1-1

### Adapter firmware version

20210708

### Adapter

zStack3x0

### Debug log

```
error Failed to check if update available for 'interrupteur_chauffage_lit_cecilia' (No image available for imageType '5634')
error Failed to check if update available for 'interrupteur_chauffage_lit_micka' (No image available for imageType '5634')
```

**Comment by Koenkk** [comment]
This means we don't have an image available for this plug. To retrieve it follow: https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html

**Comment by inrepublica** [comment]
Ah ok, i don't have Xiaomi or tuya gateway. Thanks for your work 👍
