### ISSUE TITLE
CC2531 as router allways connected

### ISSUE THREAD

**Issue by hernanjc** [Koenkk/zigbee2mqtt#1380]
I have a CC2531 configured as a Roouter. I connect it and sends likquiality and state "{{ value_json.state }}". But when I unplugged it Home Assistant shows last state and likquality before unplugging.

Zigbee2Mqtt config:
devices:
  '0x00124b0014b940e1':
    friendly_name: ZigBee_Router_UP
    id: '0x00124b0014b940e1'
    retain: false

HomeAssistant configuration.yaml
sensor:
  - platform: "mqtt"
    name: "ZigBee_Router_UP linkquality"
    icon: "mdi:signal-cellular-2"
    state_topic: "zigbee2mqtt/ZigBee_Router"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

binary_sensor:
  - platform: "mqtt"
    name: "ZigBee_Router_UP"
    state_topic: "zigbee2mqtt/ZigBee_Router"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.state}}"
    device_class: "connectivity"

Any ideas? Thanx

**Comment by Koenkk** [comment]
If you want the device to be offline when it's unplugged, you should use availability: #775
