### ISSUE TITLE
[New device support]: Sylvania 73742 Variant (LEDVANCE RT TW)

### ISSUE THREAD

**Issue by hcgonzalezpr** [Koenkk/zigbee2mqtt#13803]
### Link

https://www.amazon.com/73742-SYLVANIA-Adjustable-SmartThings-Assistant/dp/B015KQ29JI

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0xf0d1b8000002d110","nwkAddr":54448,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"RT TW","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[0,3,4,5,6,8,768,2821,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"dateCode":"Jan  7 2019\u0000\u0000\u0000\u0000\u0000","appVersion":1,"manufacturerName":"LEDVANCE","modelId":"RT TW","locationDesc":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370,"colorMode":2,"colorTemperature":370,"coupleColorTempToLevelMin":0,"currentHue":0,"currentSaturation":254,"options":0,"whitePointX":0,"whitePointY":0,"currentX":24939,"currentY":24701}},"genLevelCtrl":{"attributes":{"currentLevel":254,"remainingTime":0}},"genIdentify":{"attributes":{"identifyTime":0}},"msTemperatureMeasurement":{"attributes":{}},"genScenes":{"attributes":{"count":0,"nameSupport":0}},"msIlluminanceMeasurement":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":0,"dateCode":"Jan  7 2019\u0000\u0000\u0000\u0000\u0000","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1662039174526,"defaultSendRequestWhen":"immediate"}

### Comments

Sylvania seems to be selling 2 variants with the same model number but different [packaging](https://i.imgur.com/NVR7zum.jpg).

The original supported variant has a reports as:
```
zigbeeModel: ['LIGHTIFY RT Tunable White'],
model: '73742',
vendor: 'Sylvania',
```

The new variant I purchased from Amazon reports as:
```
zigbeeModel: ['RT TW''],
model: '73742',
vendor: 'LEDVANCE',
```

I check the existing Sylvania 73742 converter and it seems it does not have the same colorTempRange limits.

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extend = require('zigbee-herdsman-converters/lib/extend');

const definition  =  {
        zigbeeModel: ['RT TW'],
        model: '73742',
        vendor: 'LEDVANCE',
        description: 'Smart+ LED adjustable white RT 5/6',
        extend: extend.ledvance.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
        ota: ota.ledvance
    }

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
