### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by okas19** [Koenkk/zigbee2mqtt#13802]
### Link

https://itead.cc/product/sonoff-t4eu1c-wi-fi-smart-single-wire-wall-switch/

### Database entry

 Set to pairing mode nothing happens. dongle is operating well for other sonoff devices.

### Comments

docker image: koenkk/zigbee2mqtt@sha256:08b096a7cff5e23983a72ea0e7052798fd2ecae00ab0014678c2efafe71ff39c
machine: xavier nx ubuntu 
zbdongle-p flashed latest firmware

**Comment by jerrm** [comment]
The link is to a wifi switch, not zigbee.

**Comment by okas19** [comment]
Should have read carefully, thanks closing

**Comment by okas19** [comment]
Done
