### ISSUE TITLE
The graph representing the status of the battery in Xiaomi components is different color for a similar value

### ISSUE THREAD

**Issue by mrochette01** [Koenkk/zigbee2mqtt#13815]
### What happened?

In the "devices" display, some Xiaomi components show a "battery" in green and others in black. I tried to understand the algorithm that conditions this display without succeeding. Is it when the battery value is < 50%? In some cases, before the last update where all batteries are now at 100%, these batteries were in black.

Even with the current version 1.27.2-1, some batteries are still in black.

### What did you expect to happen?

A precision concerning the algorithm and a similar behavior for all type of devices.

### How to reproduce it (minimal and precise)

I don't know, here is a screenshot.
![2022-09-02_06-10-36](https://user-images.githubusercontent.com/90461724/188117556-51fda99a-ba8a-4b90-9192-48b468380a2b.jpg)

### Zigbee2MQTT version

1.27.2-1

### Adapter firmware version

20220802.0

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9477074/log.txt)

**Comment by sjorge** [comment]
Similar to https://github.com/nurikk/zigbee2mqtt-frontend/issues/1523, the green battery is only when a `battery_low` attribute exists and is not true.

**Comment by mrochette01** [comment]
Thank you
