### ISSUE TITLE
npm WARN EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by Flappiee** [Koenkk/zigbee2mqtt#13810]
### What happened?

Updated Zigbee2MQTT to version 1.27.2

While updating, i see this messages:

Installing dependencies...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'zigbee2mqtt@1.27.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

After updating, it still works while i have nodejs 12 installed. However, nothing about this (new?) requirements can be found in the release notes.

### What did you expect to happen?

I expected that there was an notice about this new requirements in the release notes.

### How to reproduce it (minimal and precise)

Update to Zigbee2MQTT latest version with NodeJS 12 installed.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Zig-a-Zig-ah!

### Debug log

administrator@HOMEASSISTANT1:/opt/zigbee2mqtt$ ./update.sh
Stopping Zigbee2MQTT...
Creating backup of configuration...
Updating...
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
remote: Enumerating objects: 779, done.
remote: Counting objects: 100% (639/639), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 779 (delta 547), reused 563 (delta 487), pack-reused 140
Receiving objects: 100% (779/779), 522.51 KiB | 4.18 MiB/s, done.
Resolving deltas: 100% (576/576), completed with 51 local objects.
From https://github.com/Koenkk/zigbee2mqtt
   a252914e..7dc48fb6  master       -> origin/master
   3498c6e2..178f72c3  dev          -> origin/dev
 * [new branch]        install_code -> origin/install_code
 * [new tag]           1.27.2       -> 1.27.2
 * [new tag]           1.26.0       -> 1.26.0
 * [new tag]           1.27.0       -> 1.27.0
 * [new tag]           1.27.1       -> 1.27.1
Updating a252914e..7dc48fb6
Fast-forward
 .github/ISSUE_TEMPLATE/new_device_support.yaml |    1 +
 .github/workflows/ci.yml                       |   48 +-
 .github/workflows/depsreview.yaml              |    2 +-
 .github/workflows/ghcr_cleanup.yml             |    4 +-
 .github/workflows/stale.yml                    |    2 +-
 docker/Dockerfile                              |    6 +-
 lib/controller.ts                              |   12 +-
 lib/extension/bind.ts                          |   10 +-
 lib/extension/bridge.ts                        |   15 +
 lib/extension/groups.ts                        |   35 +-
 lib/extension/homeassistant.ts                 |  171 ++-
 lib/extension/publish.ts                       |    3 +-
 lib/extension/receive.ts                       |    4 +-
 lib/mqtt.ts                                    |   31 +-
 lib/state.ts                                   |   20 +-
 lib/types/types.d.ts                           |    9 +-
 lib/util/settings.schema.json                  |   33 +-
 lib/util/settings.ts                           |   18 +-
 lib/util/utils.ts                              |   23 +
 lib/zigbee.ts                                  |    4 +
 npm-shrinkwrap.json => package-lock.json       | 6206 +++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------
 package.json                                   |   45 +-
 test/bind.test.js                              |    3 +-
 test/bridge.test.js                            |   41 +-
 test/controller.test.js                        |   62 +
 test/group.test.js                             |   24 +
 test/homeassistant.test.js                     |   25 +-
 test/networkMap.test.js                        |    4 +-
 test/publish.test.js                           |    4 +-
 test/receive.test.js                           |   12 +-
 test/settings.test.js                          |   46 +
 test/stub/data.js                              |    3 +
 test/stub/zigbeeHerdsman.js                    |    5 +
 update.sh                                      |    1 -
 34 files changed, 3789 insertions(+), 3143 deletions(-)
 rename npm-shrinkwrap.json => package-lock.json (78%)
Installing dependencies...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'zigbee2mqtt@1.27.2',
npm WARN EBADENGINE   required: { node: '^14 || ^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

added 836 packages, and audited 837 packages in 14s

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Restore configuration...
Starting Zigbee2MQTT...
Done!

**Comment by Koenkk** [comment]
Node 12 was dropped in 1.25.2 since it is EOL (https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.25.2) however z2m will still work fine with node 12.
