### ISSUE TITLE
[New device support]: GIDERWEL Home Smart Zigbee LED Controller RGBCCT

### ISSUE THREAD

**Issue by jdohn15** [Koenkk/zigbee2mqtt#13824]
### Link

https://www.amazon.com/dp/B07FTD9H7T?ref=ppx_yo2ov_dt_b_product_details&th=1

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0xa4c138f695497a0b","nwkAddr":17561,"manufId":4417,"manufName":"_TZ3210_ijczzg9h","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_ijczzg9h","powerSource":1,"zclVersion":3,"appVersion":101,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":101,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1662142926690,"defaultSendRequestWhen":"immediate"}

### Comments

Similar to #7869 as it has the TS0505B but it is a different manufacturer. 

### Supported color modes

rgbw ww cw

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
