### ISSUE TITLE
Paulmann 500.49 - Color Code [255,0,0] can't be sent. Every other works fine

### ISSUE THREAD

**Issue by sebaschn** [Koenkk/zigbee2mqtt#13840]
### What happened?

I've paired the Paulmann 500.49 LED controller 
(https://www.zigbee2mqtt.io/devices/50049_500.63.html#paulmann-50049-500-63)
into my Home Assistant installation via Zigbee2MQTT, using the (now older ^^) sonoff stick.

But i can't get it to display full red [255,0,0] on the RBG LED Strip attached.
If i send this color command to the device, simply nothing changes = previous color is still shown.
But in HA the full red is shown in the icon and also selected in the color wheel.

As you can see in the protocol (see below), obviously the red command is exactly the same as the previous.
So the true red might be ...idk...out of range?

Closest i can manage to send is [255,0,1].

Using it in ZHA works just fine.
So the device itself and the RGB strip isn't faulty.

Re-pairing it didnt fix the problem.

Any suggestions?

THANKS!

Workaround: from now on i'll have to use [255,0,1] as the new true red.

### What did you expect to happen?

LED strip changes color after sending [255,0,0] 

### How to reproduce it (minimal and precise)

* pair a Paulmann 500.49 LED strip controller to Zigbee2MQTT
* select color [255,0,0] 
* --> either inside Zigbee2MQTT --> device --> exposes --> color_xy --> color selection (right square)
* --> or inside HA --> device --> color wheel

### Zigbee2MQTT version

1.27.2-1

### Adapter firmware version

20220507

### Adapter

zStack3x0 / SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

Protocol:

**sending blue:**
Zigbee2MQTT:info  2022-09-03 22:34:50: MQTT publish: topic 'zigbee2mqtt/LED_Strip02', payload '{"brightness":41,"color":{"h":0,"hue":0,"s":100,"saturation":100,"x":0.701,"y":0.299},"color_mode":"xy","color_temp":159,"linkquality":167,"state":"ON"}'

**sending red:**
Zigbee2MQTT:info  2022-09-03 22:34:51: MQTT publish: topic 'zigbee2mqtt/LED_Strip02', payload '{"brightness":41,"color":{"h":0,"hue":0,"s":100,"saturation":100,"x":0.701,"y":0.299},"color_mode":"xy","color_temp":159,"linkquality":171,"state":"ON"}'

**sending green:**
Zigbee2MQTT:info  2022-09-03 22:35:47: MQTT publish: topic 'zigbee2mqtt/LED_Strip02', payload '{"brightness":41,"color":{"h":123,"hue":123,"s":100,"saturation":100,"x":0.17,"y":0.703},"color_mode":"xy","color_temp":153,"linkquality":182,"state":"ON"}'

**Comment by IetIesAai** [comment]
This seems to be the same issue as #6059 - but for paulmann led drivers. I could only test with a 500.47, but the behaviour is exactly the same as described above and in #6059 - when color code "x":0.701,"y":0.299 is requested (which home assistant sends if you request rgb 255 0 0) the driver ignores it. If you ask for pure red through z2m gui, the value is   "x": 0.7006, "y": 0.2993 whicj does work. the other color bulbs I have also seem to actually report being set to "x": 0.7006, "y": 0.2993 when  "x":0.701,"y":0.299 is requested...
