### ISSUE TITLE
[New device support]: TRADFRI LED1937T5_E26_470lm

### ISSUE THREAD

**Issue by nara1111** [Koenkk/zigbee2mqtt#13851]
### Link

https://www.ikea.com/kr/ko/p/tradfri-led-bulb-e26-470-lumen-wireless-dimmable-white-spectrum-tube-shaped-white-frosted-glass-90461921/

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0x9035eafffe26e66d","nwkAddr":10410,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRIbulbT120E26WSopal470lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20200826","swBuildId":"1.0.010","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1662285907448,"defaultSendRequestWhen":"immediate"}

### Comments

It's noted 450lm in USA, but in South Korea, it's 470lm.
May I create new device description file in devices folder?

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
