### ISSUE TITLE
Aurora RGBW Bulbs

### ISSUE THREAD

**Issue by zakery292** [Koenkk/zigbee2mqtt#13854]
### What happened?

Uk versions of the Aurora bulbs currently supported come with a different model number which is unsupported by MQTT whats the workaround for this i've attempted to add the device configuration as per instructions but it wont work unless im being thick... 

### What did you expect to happen?

Aurora AU-A1GUZBRGBWB link with a different model number [RGBGU10Bulb50AU2]

### Zigbee2MQTT version

1.27.2-dev commit: 24d83b0

### Adapter firmware version

0x26780700

### Adapter

 ConBee2/RaspBee2

**Comment by Koenkk** [comment]
Added it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
