### ISSUE TITLE
[New device support]: Tuya 6 scene switch 

### ISSUE THREAD

**Issue by Jeff89L** [Koenkk/zigbee2mqtt#13857]
### Link

https://www.alibaba.com/product-detail/SQIVO-High-end-Hotel-Tuya-Zigbee_1600457684553.html?spm=a2700.galleryofferlist.normal_offer.d_title.40102ef1HclCt0

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0xa4c166fnk1f89439v4","nwkAddr":24471,"manufId":4417,"manufName":"_TZ3002_m3aeya68","powerSource":"Mains (single phase)","modelId":"TS0026","epList":[1,2,3,4,5,6,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":4,"inClusterList":[4,5,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0026","manufacturerName":"_TZ3002_m3aeya68","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genScenes":{"attributes":{"count":0}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc4259","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc4259","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc4259","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc4259","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":4,"inClusterList":[4,5,57344],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":4,"inClusterList":[4,5,57344],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":4,"inClusterList":[4,5,57344],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":260,"epId":5,"devId":4,"inClusterList":[4,5,57344],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":260,"epId":6,"devId":4,"inClusterList":[4,5,57344],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":821693351},"lastSeen":1662128837126,"defaultSendRequestWhen":"immediate"}

### Comments

Need help
I bought 100 pcs for customers
its a new tuya device
Log
Received Zigbee message from '0xa4c166fnk1f89439v4', type 'raw', cluster 'genOnOff', data '{"data":[1,52,253,0],"type":"Buffer"}' from endpoint 1 with groupID 0

Received Zigbee message from '0xa4c166fnk1f89439v4', type 'raw', cluster 'genOnOff', data '{"data":[1,52,254,0],"type":"Buffer"}' from endpoint 2 with groupID 0
Received Zigbee message from '0xa4c166fnk1f89439v4', type 'raw', cluster 'genOnOff', data '{"data":[1,52,255,0],"type":"Buffer"}' from endpoint 3 with groupID 0
etc

**Comment by evangelo18** [comment]
I am also trying to pair this device.
Database entry
{"id":10,"type":"Router","ieeeAddr":"0x8cf681fffeaf27d2","nwkAddr":58627,"manufId":4098,"manufName":"_TZ3000_zua10nyz","powerSource":"Mains (single phase)","modelId":"TS0026","epList":[1,2,3,4,5,6],"endpoints":{"1":{"profId":260,"epId":1,"devId":4,"inClusterList":[0,4,5,6],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"genBasic":{"attributes":{"modelId":"TS0026","manufacturerName":"_TZ3000_zua10nyz","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":260,"epId":5,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":260,"epId":6,"devId":4,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1664274847807,"defaultSendRequestWhen":"immediate"}
