### ISSUE TITLE
[New device support]: TuYa TS0501B Zigbee light (third party device)

### ISSUE THREAD

**Issue by DesmondDu** [Koenkk/zigbee2mqtt#13867]
### Link

https://item.jd.com/10051475760529.html#none

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0xe0798dfffe41ce14","nwkAddr":20042,"manufId":4098,"manufName":"_TZ3210_aurnbfv4","powerSource":"Mains (single phase)","modelId":"TS0501B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"61440":0,"onOff":1}},"lightingColorCtrl":{"attributes":{"57344":1000,"61447":[],"61448":[],"61449":[],"61453":0,"tuyaRgbMode":0,"currentHue":null}},"genLevelCtrl":{"attributes":{"61440":1000}},"genBasic":{"attributes":{"modelId":"TS0501B","manufacturerName":"_TZ3210_aurnbfv4","powerSource":1,"zclVersion":3,"appVersion":99,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":99,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1662346646775,"defaultSendRequestWhen":"immediate"}

### Comments

It is Tuya Zigbee light but shows unsopported in zigbee2mqtt. I edits its database with supported database [TS0501B Zigbee light](https://www.zigbee2mqtt.io/devices/TS0501B.html#tuya-ts0501b), and works fine.

in database I only edited:
"manufName":"_TZ3210_i680rtja"

### Supported color modes

single color temperature

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
