### ISSUE TITLE
[New device support]: BSEED Smart socket (with power monitoring)

### ISSUE THREAD

**Issue by Malaysk** [Koenkk/zigbee2mqtt#13881]
### Link

https://aliexpress.com/item/1005003624122067.html?pdp_npi=2%40dis%21RUB%211%C2%A0663%2C19%20%D1%80%D1%83%D0%B1.%211%C2%A0164%2C30%20%D1%80%D1%83%D0%B1.%21%21%21%21%21%4021135c3816624439421726257e1d93%2112000026544411306%21sh&sku_id=12000026544411306&spm=a2g0o.store_pc_groupList.8148356.8.9dca5aabT1y3bI

### Database entry

{"id":25,"type":"Router","ieeeAddr":"0xa4c1381a79a9a78d","nwkAddr":35658,"manufId":4417,"manufName":"_TZ3000_b28wrpvx","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_b28wrpvx","powerSource":1,"zclVersion":3,"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":""}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,0]}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1,"rmsVoltage":217,"rmsCurrent":0,"activePower":0}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"moesStartUpOnOff":2,"tuyaBacklightMode":1,"onTime":0,"offWaitTime":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2883992,"53251":118,"53252":10522,"53253":1248,"powerOnBehavior":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00215b273c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00215b273c","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b00215b273c","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-2046940934},"lastSeen":1662443787349,"defaultSendRequestWhen":"immediate"}

### Comments

Zigbee model
TS011F
Producer Zigbee
_TZ3000_b28wrpvx
Support status
Not supported

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of Tuya devices use the same modelID, but use different data points
    // it's usually necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS011F' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS011F',
            // The manufacturer name from: Device with modelID 'TS011F' is not supported.
            manufacturerName: '_TZ3000_b28wrpvx'
        },
    ],
    model: 'TS011F_plug_1',
        description: 'Smart socket (with power monitoring)',
        vendor: 'TuYa',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, fz.tuya_switch_power_outage_memory,
            fz.ts011f_plug_indicator_mode],
        toZigbee: [tz.on_off, tz.tuya_switch_power_outage_memory, tz.ts011f_plug_indicator_mode],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
            endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
            endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {
                acVoltageMultiplier: 1, acVoltageDivisor: 1, acCurrentMultiplier: 1, acCurrentDivisor: 1000, acPowerMultiplier: 1,
                acPowerDivisor: 1,
            });
            try {
                await reporting.currentSummDelivered(endpoint);
            } catch (error) {/* fails for some https://github.com/Koenkk/zigbee2mqtt/issues/11179 */}
            await endpoint.read('genOnOff', ['onOff', 'moesStartUpOnOff', 'tuyaBacklightMode']);
        },
        options: [exposes.options.measurement_poll_interval()],
        // This device doesn't support reporting correctly.
        // https://github.com/Koenkk/zigbee-herdsman-converters/pull/1270
        exposes: [e.switch(), e.power(), e.current(), e.voltage().withAccess(ea.STATE),
            e.energy(), exposes.enum('power_outage_memory', ea.ALL, ['on', 'off', 'restore'])
                .withDescription('Recover state after power outage'),
            exposes.enum('indicator_mode', ea.ALL, ['off', 'off/on', 'on/off']).withDescription('LED indicator mode')
    ],
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`_TZ3000_b28wrpvx` is supported in the latest dev branch now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
