### ISSUE TITLE
Cannot get the Node Descriptor of the Device: <0xdevice_id> (Error: request unssuccess: 194) on startup

### ISSUE THREAD

**Issue by MichielMag** [Koenkk/zigbee2mqtt#1388]
# Bug Report
## What happened
Whenever I start zigbee2mqtt, this happens:
` zigbee2mqtt:info 4/8/2019, 6:16:41 AM Starting zigbee-shepherd

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe8f1e3f (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe0244f0 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe8f1e3f (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe8f1e3f (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:52 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe0244f0 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:53 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:53 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:53 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe0244f0 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:53 AM Cannot get the Node Descriptor of the Device: 0x90fd9ffffe0244f0 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:16:53 AM Cannot get the Node Descriptor of the Device: 0x000b57fffed51a18 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:18:25 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:18:35 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

  zigbee2mqtt:error 4/8/2019, 6:18:45 AM Cannot get the Node Descriptor of the Device: 0x000b57fffeab5de2 (Error: request unsuccess: 194)

`

Also I see the light's blinking before the software gives me this error.
Every one of these devices is tradfri.

## What did you expect to happen
Everything worked fine before a restart, but suddenly it began doing this.

## How to reproduce it (minimal and precise)
Only thing I changed, which should be unrelated is add 2 groups to my configuration.yaml. Was going to experiment with them.

## Debug Info
zigbee2mqtt version: 1.2.1 (commit #4048cb8)
CC253X firmware version: 2019-02-23

**Comment by Koenkk** [comment]
Can you provide the output of `DEBUG=* npm start`.
