### ISSUE TITLE
All devices reporting 100% battery

### ISSUE THREAD

**Issue by psleep** [Koenkk/zigbee2mqtt#13906]
### What happened?

Following update to 1.27.2, all of my battery powered devices (mostly Xiaomi motion sensors RTCGQ01LM) are reporting 100% battery power.

Before the update, battery levels appear to have being reported correctly.

### What did you expect to happen?

Battery status to be reported as accurately as possible according to the device, not just report100%

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Sonoff 3 zStack3x0

**Comment by Koenkk** [comment]
In 1.27.2 the battery % calculation has been changed. It is derived from the voltage, anything above 3000mv will give 100% (I expect all your sensors do). A discussion about this can be found here: https://github.com/Koenkk/zigbee2mqtt/issues/8499
