### ISSUE TITLE
[Feature request]: TS130F UP and DOWN calibration time

### ISSUE THREAD

**Issue by mariomare22** [Koenkk/zigbee2mqtt#13908]
### Is your feature request related to a problem? Please describe

I realized that my curtain has ~20s to go down and ~40s to go up but I have only one calibration_time .

### Describe the solution you'd like

I would like to have different calibration time instead 

### Describe alternatives you've considered

I sat up the calibration_time to 40s but that means that the state stays 20 more seconds DOWN before changing to STOP.

### Additional context

N/A

**Comment by dagope** [comment]
I have the same problem. The calibration time is different when the blind goes up and when it goes down. 5 seconds difference means that they then desynchronize when putting them in X position. Devices like the Shelly have much better calibration.

Could we open this feature?
