### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by Japander** [Koenkk/zigbee2mqtt#13904]
### Is your feature request related to a problem? Please describe

I want to upgrade the firmware of IKEA Starkwind Device, but even though a newer firmware is avaiable at http://fw.ota.homesmart.ikea.net/feed/version_info.json , the device isnt listed as being able to do a OTA

### Describe the solution you'd like

Add a way to enable OTA

### Describe alternatives you've considered

-

### Additional context

[Device Link](https://www.zigbee2mqtt.io/devices/E2007.html#ikea-e2007)

**Comment by sjorge** [comment]
Let me look at this, I probably messed up while adding support for this device.

**Comment by sjorge** [comment]
Indeed, I messed up, sorry.
