### ISSUE TITLE
Removed to much in commit :: added support tuya motion sensor TS0202 _TZ3000_lltemgsf 

### ISSUE THREAD

**Issue by yormedia** [Koenkk/zigbee2mqtt#13919]
### What happened?

In the commit added support tuya motion sensor TS0202 _TZ3000_lltemgsf  you also removed the battery level. 

### What did you expect to happen?

The battery level should be available, I had to restore previous version

### Zigbee2MQTT version

1.27.1

### Adapter firmware version

20220219

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by Koenkk** [comment]
Added it back!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
