### ISSUE TITLE
Is my configuration set in HomeAssistant ignored?

### ISSUE THREAD

**Issue by iz3man** [Koenkk/zigbee2mqtt#13922]
### What happened?

Setting parameters in yaml edit mode in z2m add-on configuration tab seems to be ignored.

This is my config, and I set channel to 15, but in z2m the dongle's channel still remains on 11.
pan_id is set to GENERATE, but it still remains GENERATE after restart, or reboot.

So basically everything below "advanced" seems ignored?!

`data_path: /config/z2m
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fe373a119f19ec119b3a37cc47486eb0-if00-port0
advanced:
  pan_id: GENERATE
  channel: 15
  last_seen: ISO_8601_local
device_options:
  homeassistant:
    last_seen:
      enabled_by_default: true
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500`

### What did you expect to happen?

I was expecting the settings to be read and used

### How to reproduce it (minimal and precise)

Go to yaml edit, change to what I posted above, save and restart.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Sonoff 3.0 P

![image](https://user-images.githubusercontent.com/11553674/189191061-64fbbb64-90c8-440f-b8f2-88fa888d0738.png)

**Comment by Koenkk** [comment]
Only MQTT and serial section can be configured via this page, rest is done via the UI

**Comment by iz3man** [comment]
Ah! Makes sense. So if I want to change Zigbee channel 11 -> 15 I remove EVERYTHING under the port setting, and do my changes in the UI?

![image](https://user-images.githubusercontent.com/11553674/189301146-50d23a1e-d5cc-4b3c-8d6a-5456474c59e4.png)


And the "device_options" with "last seen" etc goes where? In the main HomeAssistant configuration.yaml?

Thanks!!

**Comment by Koenkk** [comment]
> So if I want to change Zigbee channel 11 -> 15 I remove EVERYTHING under the port setting, and do my changes in the UI?

Only change the channel and save

> And the "device_options" with "last seen" etc goes where? In the main HomeAssistant configuration.yaml?

All in the z2m configuration.yaml (can be configured from the ui)

**Comment by Stooovie** [comment]
yes, same here. Channel set in yaml is ignored, and stays as before in Z2M UI.
