### ISSUE TITLE
Unable to re-pair device after 1st incorrect pair.

### ISSUE THREAD

**Issue by SergioRius** [Koenkk/zigbee2mqtt#13939]
### What happened?

I got some IH012-RT01 devices so I started to pair the first one.
The device was detected as a different one, so I checked if a new z2m version was available, in case this sensor was added recently.
I upgraded z2m to 1.27.2 commit: 7dc48fb6 from IIRC 1.25
I removed the previously device and re-paired it. The device showed the correct model.
So I paired the rest of them, all correct and nice.
Then I noticed that the 1st sensor was showing '?' as battery level. All other sensors showed correct and 'green'.
I saw that the sensors status is always {} or { "linquality": 176 }
The database file for this device shows that clusters are not setup correctly (this device "5" on top of a correct setup one "6"):
```json
{"id":5,"type":"EndDevice","ieeeAddr":"0xa4c138a36e0251e2","nwkAddr":34441,"manufId":4417,"manufName":"_TZ3000_mcxw5ehu","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1662715566947,"defaultSendRequestWhen":"immediate"}
{"id":6,"type":"EndDevice","ieeeAddr":"0xa4c13883cf18f22f","nwkAddr":38263,"manufId":4417,"manufName":"_TZ3000_mcxw5ehu","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x9035eafffe51bb8b","zoneState":1,"currentZoneSensitivityLevel":1,"zoneStatus":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1662715658478,"defaultSendRequestWhen":"immediate"}
```
I've tried to remove and repair numerous times without any change. It's like something is stuck that survives a re-pair.

This already happened to me with another device, and the solution was raising another empty zigbee2mqtt instance, pairing the device there and transferring the correct database line to the production one.
It's a recurring problem that seems to have survived a program upgrade.

### What did you expect to happen?

The devices being correctly and totally removed, wiping all wrong information could exist and allowing a fresh pairing.

### How to reproduce it (minimal and precise)

I don't know. Is something that happens from time to time with the first device of a brand new batch. Others pair without a glitch.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

6.7.8.0 build 373

### Adapter

EZSP v8

### Debug log

Logs don't show anything wrong. The normal pairing process.

**Comment by wenjiavv** [comment]
Same issue. :(
