### ISSUE TITLE
Eurotronic SPZB0001 does not report correct system_mode

### ISSUE THREAD

**Issue by arsensbur** [Koenkk/zigbee2mqtt#13946]
### What happened?

Hi!

Whenever I try to change system_mode, new mode is set on device, but Z2M UI and MQTT still report "auto"
Attached log contains testing on "Bedroom Thermostat" device

### What did you expect to happen?

Correct state reporting

### How to reproduce it (minimal and precise)

1. Pair Eurotronic SPZB0001, wait for interview to complete
2. Try to change system_mode to any accepted value
3. Observe the device: device mode changed, but there it is not reflected in MQTT messages, nor Z2M UI

### Zigbee2MQTT version

1.27.0, 1.27.2, 1.27.2-dev

### Adapter firmware version

 20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9538476/log.txt)

**Comment by arsensbur** [comment]
Still an issue in 1.28.0

**Comment by PetrP2B** [comment]
I paired the whole zigbee network yesterday and the SPZB0001 is not working properly. I have always used the latest version of Z2M or Z2M-edge. Now the device cannot be switched to OFF and does not report the set temperature. I found that it is listed completely differently in state.json.
OLD (functional):
    "0x00158d00032f7007": {
        "eurotronic_host_flags": {
            "mirror_display": false,
            "boost": false,
            "window_open": true,
            "child_protection": false
        },
        "system_mode": "off",
        "eurotronic_system_mode": 17,
        "local_temperature": 20,
        "occupied_heating_setpoint": 5,
        "unoccupied_heating_setpoint": 16,
        "pi_heating_demand": 0,
        "current_heating_setpoint": 5,
        "eurotronic_error_status": 1,
        "battery": 0.5,
        "battery_low": true,
        "update": {
            "state": "idle"
        },
        "update_available": false,
        "linkquality": 45
    },

NEW:
   "0x00158d00032f7007": {
        "local_temperature": 21,
        "occupied_heating_setpoint": 5,
        "unoccupied_heating_setpoint": 16,
        "pi_heating_demand": 0,
        "running_state": "idle",
        "current_heating_setpoint": 5,
        "child_protection": false,
        "mirror_display": false,
        "boost": false,
        "window_open": false,
        "system_mode": "auto",
        "linkquality": 60,
        "error_status": 0,
        "update": {
            "state": "idle"
        },
        "update_available": false,
        "battery": 20
    },

Until I uninstalled Z2M yesterday and deleted all its files, the thermostats were working properly.

database.db:
OLD(functional:
{"id":6,"type":"EndDevice","ieeeAddr":"0x00158d00032f7007","nwkAddr":37092,"manufId":4151,"manufName":"Eurotronic","powerSource":"Battery","modelId":"SPZB0001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,513,25,10],"outClusterList":[0,1,3,4,513,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"SPZB0001","manufacturerName":"Eurotronic","powerSource":3,"zclVersion":2,"appVersion":22,"stackVersion":5,"hwVersion":35,"dateCode":"20191014","swBuildId":"22190930"}},"genPowerCfg":{"attributes":{"batteryAlarmState":1,"batteryPercentageRemaining":1}},"hvacThermostat":{"attributes":{"16386":1,"16387":500,"16392":17,"localTemp":2000,"pIHeatingDemand":0,"occupiedHeatingSetpoint":500,"unoccupiedHeatingSetpoint":1600}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b000be873ad","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b000be873ad","endpointI
D":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b000be5aead","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b000be5aead","endpointID":1}],"configuredReportings":[{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":8,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},"cluster":513,"attrId":20,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},"cluster":513,"attrId":16387,"minRepIntval":0,"maxRepIntval":3600,"repChange":25},"cluster":513,"attrId":16392,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":}}},"appVersion":22,"stackVersion":5,"hwVersion":35,"dateCode":"20191014","swBuildId":"22190930","zclVersion":2,"interviewCompleted":true,"meta":"configured":1138500639},"lastSeen":1664146098081,"defaultSendRequestWhen":"immediate"}

NEW:
{"id":30,"type":"EndDevice","ieeeAddr":"0x00158d00032f7007","nwkAddr":41939,"manufId":4151,"manufName":"Eurotronic","powerSource":"Battery","modelId":"SPZB0001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,513,25,10],"outClusterList":[0,1,3,4,513,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"SPZB0001","manufacturerName":"Eurotronic","powerSource":3,"zclVersion":2,"appVersion":22,"stackVersion":5,"hwVersion":35,"dateCode":"20191014","swBuildId":"22190930"}},"hvacThermostat":{"attributes":{"16386":0,"16387":500,"16392":17,"localTemp":2100,"pIHeatingDemand":0,"occupiedHeatingSetpoint":500,"unoccupiedHeatingSetpoint":1600}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":40}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0ec56","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0ec56","endpointID":1}],"configuredRe
portings":[{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":8,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":20,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":16387,"minRepIntval":0,"maxRepIntval":3600,"repChange":25},{"cluster":513,"attrId":16392,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":}}},"appVersion":22,"stackVersion":5,"hwVersion":35,"dateCode":"20191014","swBuildId":"22190930","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1138500639},"lastSeen":1666245334329,"defaultSendRequestWhen":"immediate"}

Thank you for your help.

**Comment by PetrP2B** [comment]
I was able to get the thermostats back to working order as they were before yesterday. It was necessary to select Celsius and legacy mod in the specific settings. After some time, the thermostat behaves correctly.

**Comment by arsensbur** [comment]
> I was able to get the thermostats back to working order as they were before yesterday. It was necessary to select Celsius and legacy mod in the specific settings. After some time, the thermostat behaves correctly.

thanks a lot, that actually helped!
