### ISSUE TITLE
TS011F_plug_1 pair after force remove

### ISSUE THREAD

**Issue by PepaRokos** [Koenkk/zigbee2mqtt#13943]
### What happened?

Hi,
I have had successfully paired this plug, but I accidentally removed it with "Force remove" checked. Now I'm not able to pair it again. When I try to pair it I get error message "Device 'dev' left the network". What should I have to do?

### What did you expect to happen?

Removed device correctly pair again.

### How to reproduce it (minimal and precise)

Force remove and pair it again.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20201127

### Adapter

CC2531

### Debug log

Info 2022-09-09 14:02:31MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"cerpadlo","ieee_address":"0xa4c1380ac30cab74"},"type":"device_leave"}'
Info 2022-09-09 14:02:31MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0xa4c1380ac30cab74"},"type":"device_removed"}'

**Comment by davrodfer** [comment]
I have the same problem. But when I put the device near the coordinator, the pair is completed. When I move de device far from the coordinator, where others devices are working ok, TS011F_plug_1 stops connecting. If I repair, never gets connected again when is far from coordinator.

Last version of firmware provided, is installed.


Zigbee2MQTT version

1.27.2
