### ISSUE TITLE
[New device support]: 2 Gang ZigBee Switch RR620ZB (Tuya TS0002 alike)

### ISSUE THREAD

**Issue by saper-2** [Koenkk/zigbee2mqtt#13951]
### Link

https://pcblab.io/podw%C3%B3jny-przeka%C5%BAnik-do-puszki-zigbee-tuya.html

### Database entry

{"id":18,"type":"Router","ieeeAddr":"0x84ba20fffe2ab96b","nwkAddr":6129,"manufId":4098,"manufName":"_TZ3000_7ed9cqgi","powerSource":"Mains (single phase)","modelId":"TS0002","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0002","manufacturerName":"_TZ3000_7ed9cqgi","stackVersion":0,"dateCode":""}},"manuSpecificTuya_3":{"attributes":{"switchType":2}},"genOnOff":{"attributes":{"moesStartUpOnOff":0,"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022983a41","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022983a41","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1884513748},"lastSeen":1662819997676,"defaultSendRequestWhen":"immediate"}

### Comments

There is no logo, only the seller (pcblab.io), so I used it as part of manufacturer.

Generally it's recognized as Wall Switch Tuya TS0002 , so there is no option to change input type from ```switch``` (toggle/state?) to ```button``` (momentary).

I did a little experiment, and I just copied config from ```TS0002_switch_module``` that have setting for input type, tweaked fingerprint, and **it works**, even power_on_behavior do **works**. I did not test anything else. 

I found some of those on Ali ```RR620ZB``` - on some you can spot in photos brand "LoraTap" .

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition ={
        fingerprint: [{modelID: 'TS0002', manufacturerName: '_TZ3000_7ed9cqgi'}],
        model: 'TS0002_switch_module',
        vendor: 'TuYa',
        description: '2 gang switch module',
        whiteLabel: [{vendor: 'unknown/pcblab.io', model: 'RR620ZB'}],
        toZigbee: extend.switch().toZigbee.concat([tz.moes_power_on_behavior, tz.tuya_switch_type]),
        fromZigbee: extend.switch().fromZigbee.concat([fz.moes_power_on_behavior, fz.tuya_switch_type]),
        exposes: [
            e.switch().withEndpoint('l1'),
            e.switch().withEndpoint('l2'),
            exposes.presets.power_on_behavior(),
            exposes.presets.switch_type_2(),
        ],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        },
    };
	
module.exports = definition;
```

**Comment by Koenkk** [comment]
Added it to TS0002_switch_module, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
