### ISSUE TITLE
Something isn't right with routers and pairing.

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#1396]
I am running dev SW with dev FW.
Coordinator: CC2530

Currently it has attached 5 devices to coordinator (and 4 of them are routers: CC2530+CC2591, tradfri singnal repeater and two tradfri outlets) and I can not pair anything anymore to it.
I want to stress that it is default firmware (which is not limited to 5 devices), although it is flashed (twice!)  on top of max_stability FW.
With max_stability FW it was all the same story, it would not pair anything beyond 5 devs connected to coordinator.

So, i see two problems:

1) max_stability isn't fully overwritten by default
2) when coordinator is limited to 5 devices, then no luck to go beyond with routers. 

In fact, I had the same issue with default FW, it just cap would be at 15 devices, and routers would not help. This is reason why I wanted to try "max_stability" in the first place.

**Comment by Koenkk** [comment]
The direct device limit of the max_stability firmware is 5 devices, so it seems that at least some connected via a router. To verify this, can you try with the max devices firmware (https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/max_devices/CC2531, ony for CC2531, do you have one?)? This firmware allows for up-to 44 direct devices. In this way we can exclude the firmware for being the problem.

**Comment by antst** [comment]
Actually, it was exactly 5 devices (4 routers and tradfri remote)! I couldn't  get more than that.
Now it is running with default firmware, and i have more than 15 devices, although to some of the communication is unstable.
