### ISSUE TITLE
Failed to send PIN code to the door Lock

### ISSUE THREAD

**Issue by he902** [Koenkk/zigbee2mqtt#1397]
I'm adding the support for my Yunmi Door Lock.
The MQTT can correctly receive messages from the Lock device when I physically unlock the door.
Now, I'm trying to unlock the door remotely by sending PIN code to the Lock device, but failed.

I tried the App comes with my Yunmi Door Lock, it can unlock the door remotely by sending PIN code (via the vendor's zigbee gateway).
Here is the sniffer data sent from the vendor's zigbee gateway to the Lock device, when the App unlocking the door remotely:
```
IEEE 802.15.4 Data, Dst: 0xd811, Src: 0x0000
ZigBee Network Layer Data, Dst: 0xd811, Src: 0x0000
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 11
    Frame Control Field: Data (0x00)
    Destination Endpoint: 1
    Cluster: Door Lock (0x0101)
    Profile: Home Automation (0x0104)
    Source Endpoint: 11
    Counter: 116
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
    Sequence Number: 52
    Command: Unlock Door (0x01)
    Payload
```
And the Payload binary is:
```
0000   08 47 4c 4f 44 4e 45 4e 45 00 00 00 00            .GLODNENE....
```
You can see the PIN code sent to the Lock device is "GLODNENE", and with 4 zero bytes suffixed.
Here is my piece of toZigbee.js:
```
    lock_unlock: {
        key: ['state'],
        convert: (key, value, message, type, postfix) => {
            if (type === 'set') {
                return {
                    cid: 'closuresDoorLock',
                    cmd: `${value.toLowerCase()}Door`,
                    cmdType: 'functional',
                    zclData: {
                        'pincodevalue': 'GOLDNENE',
                    },
                    readAfterWriteTime: 200,
                };
            }
        },
    },
```
Here is the zigbee2mqtt debug log:
```
  zigbee2mqtt:debug 4/8/2019, 8:55:59 PM Received MQTT message on 'zigbee2mqtt/yunmi_lock/set' with data 'UNLOCK'
  zigbee2mqtt:info 4/8/2019, 8:55:59 PM Zigbee publish to device '0x00158d0002ac2222', closuresDoorLock - unlockDoor - {"pincodevalue":"GOLDNENE"} - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 1 +41s
  cc-znp:SREQ --> AF:dataRequest, { dstaddr: 63910, destendpoint: 1, srcendpoint: 1, clusterid: 257, transid: 1, options: 48, radius: 30, len: 12, data: <Buffer 01 01 01 08 47 4f 4c 44 4e 45 4e 45> } +41s
  serialport/stream _write 27 bytes of data +793ms
  serialport/binding-abstract write 27 bytes +793ms
  serialport/bindings/unixWrite Starting write 27 bytes offset 0 bytesToWrite 27 +41s
  serialport/bindings/unixWrite write returned null 27 +3ms
  serialport/bindings/unixWrite wrote 27 bytes +0ms
  serialport/bindings/unixWrite Finished writing 27 bytes +0ms
  serialport/stream binding.write write finished +4ms
```
You can see the PIN code "GLODNENE" is not with 4 zero bytes suffixed.
And the zigbee2mqtt received the response with status of failed (=1):
```
 zigbee2mqtt:debug 4/8/2019, 8:56:00 PM Received zigbee message of type 'cmdUnlockDoorRsp' with data '{"cid":"closuresDoorLock","data":{"status":1}}' of device 'FNB56-DOR23FB1.3' (0x00158d0002ac2222)
```
Then I tried to modify the toZigbee.js to add a 32 bits parameter "timestamp": 0x0 in the zclData just after pincodevalue:
```
    lock_unlock: {
        key: ['state'],
        convert: (key, value, message, type, postfix) => {
            if (type === 'set') {
                return {
                    cid: 'closuresDoorLock',
                    cmd: `${value.toLowerCase()}Door`,
                    cmdType: 'functional',
                    zclData: {
                        'pincodevalue': 'GOLDNENE',
                        'timestamp': 0x0
                    },
                    readAfterWriteTime: 200,
                };
            }
        },
    },
```
But I still not see such 4 zero bytes suffixed with the PIN code in the debug log:
```
  zigbee2mqtt:debug 4/9/2019, 7:38:52 PM Received MQTT message on 'zigbee2mqtt/yunmi_lock/set' with data 'UNLOCK'
  zigbee2mqtt:info 4/9/2019, 7:38:52 PM Zigbee publish to device '0x00158d0002ac2222', closuresDoorLock - unlockDoor - {"pincodevalue":"GOLDNENE","timestamp":0} - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 1 +28s
  cc-znp:SREQ --> AF:dataRequest, { dstaddr: 50976, destendpoint: 1, srcendpoint: 1, clusterid: 257, transid: 1, options: 48, radius: 30, len: 12, data: <Buffer 01 01 01 08 47 4f 4c 44 4e 45 4e 45> } +28s
```
How can I add such 4 zero bytes suffixed with the PIN code?

**Comment by he902** [comment]
After up dated /opt/zigbee2mqtt//node_modules/zcl-packet/lib/defs/zcl_meta.json with:
```
            "unlockDoor":{
                "params":[
                    {"pincodevalue":"stringPreLen"},
                    {"timestamp":"uint32"}
                ],
```
It is able to send out the PIN code with 4 zero bytes suffixed.
But still got failed response: status = 1 (status: 1=failed, 0=success) from the Lock device, and I can hear two "bee" sounds from the Lock device (indicate failure).

Is it possible that the Lock device will verify the MAC address of the coordinator? And fail the unlock request sent from any coordinator which not belong to vendor Yunmi?
If so, how can I simulate a MAC address for the coordinator (here is CC2531)?

**Comment by Koenkk** [comment]
Hi, interesting!

Does the zigbee2mqtt now send the same message as the gateway (verified with zigbee sniffing?)

**Comment by he902** [comment]
I do not have another CC2531 to do sniffing at this moment (will buy one later).
From the zigbee2mqtt debug log, they have the same ZCL frame data in the unlock request sent to the Lock device, the differences I thought are sequence#, MAC address.

**Comment by he902** [comment]
Just received another CC2531, so I'm able do the zigbee sniffing.

Here is the Wireshark file for zigbee2mqtt (remote unlock by PIN code "GOLDNENE" -- fail):
[https://github.com/he902/Yunmi-Lock/blob/master/zigbee2mqtt_remote.pcapng]

Here is the Wireshark file for vendor's coordinator/gateway (join and remote unlock by PIN code "GOLDNENE" -- success):
[https://github.com/he902/Yunmi-Lock/blob/master/yunmi_join_remote.pcapng]

You can see the zigbee2mqtt has no defaultRsp msg send to the Lock device when receive deviceEnabled msg from the Lock device, and the Lock device keep sending deviceEnabled to zigbee2mqtt.. Any further commands sent to the Lock device are treated as unsupported or failed.

How to auto response device msg with defaultRsp?

**Comment by Koenkk** [comment]
Can you see these request when running with `DEBUG=zigbee-shepherd:af* npm start`?

**Comment by he902** [comment]
I was using `DEBUG=*`, there is no defaultRsp msg send to the Lock device when received deviceEnabled msg:
```
2019-04-10T12:47:14.186Z zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object]
^[[34m  zigbee2mqtt:debug^[[39m 4/10/2019, 8:47:14 PM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"deviceEnabled":1}}' of device 'FNB56-DOR23FB1.3' (0x00158d0002acba74)
2019-04-10T12:47:15.551Z serialport/bindings/poller received "readable"
```

**Comment by Koenkk** [comment]
@he902 but the  deviceEnabled  is received right? 

```
^[[34m  zigbee2mqtt:debug^[[39m 4/10/2019, 8:47:14 PM Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"deviceEnabled":1}}' of device 'FNB56-DOR23FB1.3' (0x00158d0002acba74)
```

**Comment by he902** [comment]
> @he902 but the deviceEnabled is received right?
> 
Yes, `deviceEnabled` received is right, and is the same as seeing in the sniffing by using vendor Yunmi's coordinator.

**Comment by Koenkk** [comment]
@he902 you need to add a new extension to zigbee2mqtt: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/extensionTemplate.js and respond to the corresponding message.

Documentation:
https://github.com/zigbeer/zigbee-shepherd/wiki#API_foundation
https://github.com/zigbeer/zcl-packet/wiki/6.-Appendix#FoundCmdTbl

**Comment by he902** [comment]
The auto response device msg with `defaultRsp `has been done by:
[https://github.com/Koenkk/zigbee2mqtt/issues/1402](https://github.com/Koenkk/zigbee2mqtt/issues/1402)
The clone of MAC addresss has been done by:
[https://github.com/Koenkk/Z-Stack-firmware/issues/72](https://github.com/Koenkk/Z-Stack-firmware/issues/72)

But still received failure of sending PIN code!
What remained difference with the vendor's coordinator are:
1) zigbee2mqtt sends extra command: `Discover Attributes (0x0c)` during pairing, but the Lock device responses with `unsupported` . The re-sending of many times of such unsupported command may have caused the Lock device un-trust the zigbee2mqtt coordinator, thus disabled the remote unlock function.
How to disable such `Discover Attributes (0x0c)` command during pairing?

2) The EndPoint of vendor's coordinator is always 11, while zigbee2mqtt coordinator is 1. Not sure this is the cause of sending PIN code failure.
How to let zigbee2mqtt coordinator to use EndPoint 11?

**Comment by Koenkk** [comment]
1. For this, you need to modify the pairing procedure, which can be found here: https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/components/event_handlers.js#L84

2. You need to hijack https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/shepherd.js#L705 and https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/shepherd.js#L727 to set `srcEp` to endpoint 11 of the coordinator, some pointers how to find the ep can be found here: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/zigbee.js#L237
