### ISSUE TITLE
Heiman HS2WD-E siren - no switch in Home Assistant

### ISSUE THREAD

**Issue by fribse** [Koenkk/zigbee2mqtt#13986]
### What happened?

I have two Heiman [HS2WD-E](https://www.zigbee2mqtt.io/devices/HS2WD-E.html#heiman-hs2wd-e) sirens.
Looking in z2m they show up like this:
![billede](https://user-images.githubusercontent.com/13660621/189719003-6a66f76f-c545-4aed-a41b-c9f45b40ed11.png)
Which is great, but when I look at it in Home Assistant I just see this:
![billede](https://user-images.githubusercontent.com/13660621/189719150-ff801ec1-b683-45b1-9c73-19311bac6f63.png)
So no way of turning the siren on from within Home Assistant (except issuing MQTT commands).

https://www.zigbee2mqtt.io/devices/HS2WD-E.html

I can turn it on / off by sending MQTT messages to the siren, but it would be great if it showed normally in HA.

I don't see anything in MQTT either, just these three topics:

```
homeassistant/sensor/0x000d6f00161bb7ca/battery/config
homeassistant/sensor/0x000d6f00161bb7ca/linkquality/config
homeassistant/sensor/0x000d6f00161bb7ca/last_seen/config

```
### What did you expect to happen?

I expected to see the siren, flash, flash frequency etc. to appear as switches and sliders in HA.

### How to reproduce it (minimal and precise)

Add the siren to z2m.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

TubesZB CC2652P2

**Comment by lavinir** [comment]
I'm seeing the same thing. The device was previously paired with ZHA which created a dedicated Siren entity for this.

**Comment by Home9096** [comment]
Facing the same issue, however I am not able to make it sound with any type of automation nor even get a signal. The only place I am able to make it sound is in z2m on expose. I have tried following guides and codes of other people making it work, still no luck from my side.

Would be great if anyone could help out or give a clear "how-to". :)

I have tried the following: 
<img width="1163" alt="Screen Shot 2023-01-17 at 10 40 37" src="https://user-images.githubusercontent.com/117691372/213919819-275bcbde-e1a3-4837-bb95-8fe0088350f8.png">

Nothing really happens except that I get :
<img width="472" alt="script" src="https://user-images.githubusercontent.com/117691372/213919853-080ee416-a1c3-41d1-90b4-346cb7a0c86a.png">

**Comment by luixal** [comment]
Hi  @Home9096 , in order to make it work have a look at [this comment](https://github.com/Koenkk/zigbee2mqtt/issues/14424#issuecomment-1374786659) in issue #14424 

It doesn't fix z2m support for this device, but at least you can start/stop the siren.
