### ISSUE TITLE
Add invert open/close commands on cover for Smartwings WM25L-Z 

### ISSUE THREAD

**Issue by digiblur** [Koenkk/zigbee2mqtt#13982]
### Is your feature request related to a problem? Please describe

The states are correct but it seems in some configurations these covers have the commands reversed where open actually closes it and close actually opens the blinds.  

### Describe the solution you'd like

Add Settings Specific option to reverse the commands much like you can with reversing the state.

### Describe alternatives you've considered

I've tried reversing the cover with the remote but this causes other issues with the states and the remote itself.

### Additional context

Nothing else to add, just reverse the commands being sent would be great!

**Comment by digiblur** [comment]
Still needed mr bot

**Comment by digiblur** [comment]
Doesn't look like anyone needs this feature Mr Bot so you're good to do your thing.  I'll work around it in other ways.

**Comment by latez** [comment]
Any chance to resurrect this request, this is still badly needed!

**Comment by digiblur** [comment]
Indeed! An awesome feature for all cover devices under settings specific. Invert cover state, commands and percents.

**Comment by mikerenna** [comment]
This fixed an issue for me where the zigbee2mqtt commands were reversed. Not sure if this is the root cause of this item, but if so, this may help. 
![image](https://user-images.githubusercontent.com/44856262/230632176-2e6d7408-ae38-4107-b91f-efa12f796a64.png)
