### ISSUE TITLE
coordinator hangs under load

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#1399]
I noticed issue, which I observed many times.

If simultaneously multiple request are issued (like turning off 10 lights from single automation), then my coordinator (CC2530) hangs. And the only solutions is to replug coordinator.

Sometimes even toggling group of 4 lights results in this.

Could it be related to software flow control in latest FW?

I run dev version of zigbee2mqtt and dev version of FW.

**Comment by Koenkk** [comment]
I would recommend the max stability firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

**Comment by Koenkk** [comment]
Let's continue here: #1396
