### ISSUE TITLE
Lutron Connected Bulb Remote

### ISSUE THREAD

**Issue by TaylorTWBrown** [Koenkk/zigbee2mqtt#14]
Is it possible to add the Lutron Connected Bulb Remote? It is a 4-button ZLL dimmer.

It's a bit of an odd device, as it is generally paired to the bulbs directly rather than the hub. The 4 buttons connect directly to bulbs to do the following:

- Light - 100%
- Brighter
- Dimmer
- Light - 0%

Ideally, zigbee2mqtt would be able to read the commands directly, so that I could use them as plain old button controllers.

Before I buy a bunch of ZigBee hardware from China to test this, are there any caveats I should be aware of?

**Comment by foxy82** [comment]
I'd be interested in using these devices as input to Home Assistant or similar as well.

**Comment by TaylorTWBrown** [comment]
Alright, great! I've ordered a CC2531 and programmer. I'll test out my Lutron remote when it gets here.

**Comment by Koenkk** [comment]
I cannot get the Tradfri remote control to send button commands to zigbee-shepherd. I found out that the Tradfri Remote Control has profileID: 0xC05E, which seems not supported by zigbee-shepherd at the moment. This is the Touchlink profile https://github.com/zigbeer/zigbee-shepherd/issues/11

**Comment by Koenkk** [comment]
My current understanding of the Tradfri remote control is that instead of emitting button press events it directly controls bulbs. Reading various topics this seems to be a strange device. Therefore I still have trust that the Lutron connected bulb remote can be supported.
