### ISSUE TITLE
How to On/off Bulb without homeassistant?

### ISSUE THREAD

**Issue by aaamitsingh** [Koenkk/zigbee2mqtt#140]
How to on/off a zigbee bulb by simply firing MQTT command without using homeassistant?

**Comment by ciotlosm** [comment]
@aaamitsingh check documentation here: https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure

**Comment by clockbrain** [comment]
@aaamitsingh you can just send MQTT from command line, e.g. following turns on Phillips Hue bulb.

`mosquitto_pub -t "zigbee2mqtt/0x0017880103564be9/set" -h 192.168.x.x -u mqttuser -m "ON"`
