### ISSUE TITLE
Automation inside zigbee2mqtt

### ISSUE THREAD

**Issue by directman66** [Koenkk/zigbee2mqtt#1400]
Koen, please consider introducing automation at the zigbee2mqtt level. I would like to be able to customize the simplest automation scenarios through zigbee2mqtt. Bind in this case does approximately the same, but without using a coordinator. Not all devices support the bind, so the built-in automation would be a good idea for replacing the bandage (for example, turn on the light by pressing a certain button on the WXKG02LM wall-mounted remote control). I would like to make this functionality from other automation systems, this can increase the overall reliability of the system.

**Comment by Koenkk** [comment]
This would indeed be but is currently not high on my priority list (duplicate of #903)
