### ISSUE TITLE
firmware update gone wrong (Dannfoss Ally thermostat)

### ISSUE THREAD

**Issue by mvogt1** [Koenkk/zigbee2mqtt#14006]
### What happened?

After the firmware update, the thermostat reports:

Model   [014G2461] (https://www.zigbee2mqtt.io/devices/014G2461.html#danfoss-014g2461)
Firmware build date 20210227
Firmware version AAAABBBBCCCCDDDD

### What did you expect to happen?

The updates firmware wit the correct version.

### How to reproduce it (minimal and precise)

Not really to reproduce. I have two Ally thermostats, one updated fine, the other not.

The device with the wrong fw seems to work, I think.

It would be nice if I could force a firmwareupdate with the current version. 
(The frontend seems not support that.)

### Zigbee2MQTT version

1.27.2-1

### Adapter firmware version

20210120

### Adapter

Slaesh

**Comment by lux73** [comment]
i had a similar issue last Year after updating my Allys

i only could resolve this Issue after removing the Devices & completely new pair with z2m
