### ISSUE TITLE
Device state details not updated after OTA completes

### ISSUE THREAD

**Issue by ptr727** [Koenkk/zigbee2mqtt#14021]
### What happened?

Perform OTA on device, OTA completes successfully, device state still reports old version information.

### What did you expect to happen?

After OTA completes expect device state to show current version information.

### How to reproduce it (minimal and precise)

- Aqara TVOC out of box pair.
- Note the JSON state information, `"applicationVersion": 24,` `"dateCode": "20210204",`
- OTA check for update (difficult to get going, easiest to long press, re-pair, then immediately check for OTA)
- Apply OTA
- OTA completes successfully, popup message reports new datecode.
- Review JSON device state, still old datecode and version.
- Long hold button, device removes itself from network.
- Re-add device
- State now reports correct datecode
- App version is still old (see https://github.com/Koenkk/zigbee2mqtt/issues/13200 where Aqara M2 updated devices report new app version but Z2M devices report same version)

### Zigbee2MQTT version

1.27.2 commit: 7dc48fb

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Debug log

[z2mlog.zip](https://github.com/Koenkk/zigbee2mqtt/files/9580188/z2mlog.zip)

**Comment by ptr727** [comment]
Still an issue.

**Comment by lost-carrier** [comment]
same here...

```
[...]
Zigbee2MQTT:info  2022-10-26 00:34:48: Update of '0x54ef441000445055' at 99.14%, ≈ 0 minutes remaining
Zigbee2MQTT:info  2022-10-26 00:34:48: MQTT publish: topic 'zigbee2mqtt/0x54ef441000445055', payload '{"battery":49,"device_temperature":23,"display_unit":"ppb_celsius","humidity":64.54,"linkquality":222,"power_outage_count":23,"temperature":22.02,"update":{"progress":99.14,"remaining":30,"state":"updating"},"voc":121,"voltage":2923}'
Zigbee2MQTT:info  2022-10-26 00:35:19: Update of '0x54ef441000445055' at 100.00%
[...]
Zigbee2MQTT:info  2022-10-26 00:37:19: Finished update of '0x54ef441000445055'
```

...but still showing as...
```
Firmware build date
    20210204
Firmware version
    2020www.
```
