### ISSUE TITLE
Devices being "far" from the coordinator don't work as expected even if they had lots of repeaters around.

### ISSUE THREAD

**Issue by joaquinvacas** [Koenkk/zigbee2mqtt#14036]
### What happened?

They show a "low" linkquality. But this isn't always the case. It can show 21 lqi and 70 in the next report.
They are fine reporting its state, even showing "0 lqi" they are able to report if they turn on or off (using a button switch or pressing the device's button to switch off/on)

They show this kind of errors "Data request failed with error: 'MAC no ack'" instead of switching off/on, but after some time, let's say 15-30s, they start switching fast as much as you tried before the error appeared.

![image](https://user-images.githubusercontent.com/4403750/190789727-5248ff60-8d02-4050-b709-d0309722531e.png)

Somehow, after some time, they "work fine" but after a while they are a bit unreliable.

Also, trying to switch, works for the first time, maybe turning it off again, but the third time, will get stuck and show some errors like this one:
![image](https://user-images.githubusercontent.com/4403750/190804396-89f505f6-85be-435a-8edc-19eb052d4f6a.png)

It has a "good" number of repeaters around, even more (3 more, 1 this week) expected to be added soon.

But no direct communication with the coordinator.

![image](https://user-images.githubusercontent.com/4403750/190807219-2d7a2840-7a4f-45c1-b9fc-265f176a03e1.png)

Tried with -dev version but nothing changes.

Also, using CC2652P (Sonoff ITead Zigbee USB), not sure if +20dBm is working, changed config in Zigbee2mqtt settings to 20 (maybe any firmware config that I should change too?)

### What did you expect to happen?

All devices to work fine, closer or far away to the coordinator, that's the way you expect mesh networks to work.

### How to reproduce it (minimal and precise)

Add a new device, the interview goes fine, stand far away from coordinator but have many repeaters around.

Try to switch on and off couple times in a row.

Wait until you get stuck with latest status of the device without being able to switch it on or off and "MAC no ack" error to appear.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

 20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus by ITead CC2652P

**Comment by joaquinvacas** [comment]
![Screenshot_20220917_005338_Home Assistant~2](https://user-images.githubusercontent.com/4403750/190828106-be4520ee-fccf-4031-bff5-597dfa98aa98.jpg)
![Screenshot_20220917_005330_Home Assistant~2](https://user-images.githubusercontent.com/4403750/190828110-b745de37-1d85-4b8e-a6b6-ef3e459dcfe7.jpg)
![Screenshot_20220917_005151_Home Assistant~2](https://user-images.githubusercontent.com/4403750/190828112-29aa5f5d-a6ee-44be-b21c-4b043e248766.jpg)


Those are some screenshots from logs where you can check how it's showing errors and then sending all previous commands (stuck before the error) at the same time

**Comment by jerrm** [comment]
Assuming you have checked the normal interfenece culprits, I would try dropping the coordinator down to the default +9db, or maybe even lower. 

Having it shout so loudly can confuse devices to try linking with the coordinator directly when they shouldn't.  Also, it looks like there are some bulbs in the grayed out part of the map. Make sure they are always powered.

**Comment by joaquinvacas** [comment]
> Assuming you have checked the normal interfenece culprits, I would try dropping the coordinator down to the default +9db, or maybe even lower.
> 
> Having it shout so loudly can confuse devices to try linking with the coordinator directly when they shouldn't. Also, it looks like there are some bulbs in the grayed out part of the map. Make sure they are always powered.


WiFi was made from zero to prevent interferences with Zigbee, Bluetooth isn't nearby and also tried disabling it at all.

Everything is always powered, you see greyed bulbs because when you touch a device only shows the links they made with another device

**Comment by joaquinvacas** [comment]
Somehow dropping the coordinator to default dBm value "fixes" the issue. (Deleting the  transmit_power line in configuration.yaml)

20dBm breaks almost every connection that's far from coordinator.

Not sure why, maybe firmware problems?

**Comment by joaquinvacas** [comment]
Not stale.

**Comment by joaquinvacas** [comment]
Not stale.

**Comment by 877dev** [comment]
> Somehow dropping the coordinator to default dBm value "fixes" the issue. (Deleting the transmit_power line in configuration.yaml)
> 
> 20dBm breaks almost every connection that's far from coordinator.
> 
> Not sure why, maybe firmware problems?

Having a similar issue where devices next to a router and instead connecting to the coordinator. I will try dropping down the coordinator transmit power, mine is a ZZH so I believe the only way is via `configuration.yaml`.

**Comment by joaquinvacas** [comment]
Not stale.

**Comment by joaquinvacas** [comment]
> > Somehow dropping the coordinator to default dBm value "fixes" the issue. (Deleting the transmit_power line in configuration.yaml)
> > 20dBm breaks almost every connection that's far from coordinator.
> > Not sure why, maybe firmware problems?
> 
> Having a similar issue where devices next to a router and instead connecting to the coordinator. I will try dropping down the coordinator transmit power, mine is a ZZH so I believe the only way is via `configuration.yaml`.
> 
> On a similar topic, wondering what the transmit power limits are, i.e. is it 0-5 (zzh) or can it be negative i.e. -5 to 5?

Not sure if they can be lower

**Comment by joaquinvacas** [comment]
Not stale. Maybe related to fw issues.

**Comment by joaquinvacas** [comment]
Nope

**Comment by joaquinvacas** [comment]
Not stale
