### ISSUE TITLE
After a host reboot most of the lights are set to brightness 1

### ISSUE THREAD

**Issue by Tyraenor** [Koenkk/zigbee2mqtt#14055]
### What happened?

When I restart the host (Raspbian on Raspberry Pi 4) with a docker container of Zigbee2MQTT, Homebridge, Node-RED, Mosquitto, Traefik and Pi-hole installed, most of the lights are set to brightness 1, as soon as the docker container comes up again.

This has been reported in issue #11864 but has been marked as fixed there.

### What did you expect to happen?

The brightness should stay the same as before the reboot

### How to reproduce it (minimal and precise)

Reboot the host

### Zigbee2MQTT version

1.27.0 commit: a9b8808

### Adapter firmware version

0x26680700

### Adapter

ConBee2/RaspBee2

### Debug log

[debug_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9593796/debug_log.txt)

**Comment by daftndaze** [comment]
Same problem here with newer bulbs of brand IKEA and Ledvance.
