### ISSUE TITLE
NAS-AB02B0 slow on receiving the MQTT commands

### ISSUE THREAD

**Issue by AymanFadda** [Koenkk/zigbee2mqtt#14053]
### What happened?

As soon as the device is paired it behaves correctly. Some seconds later it starts to become slow on executing the commands. Fo example when I set the Alarm command {"alarm": true}, it takes from 1 to 5 seconds to start ringing. Through MQTT explorer I see the command sent but I get the status (answer) from the device after a variable time. Supplied with battery or USB it continues to behave the same way. 

### What did you expect to happen?

I expect the same reaction time as per all the other Zigbee devices on my network i. e. Less than 1 second.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee Plus

**Comment by jerrm** [comment]
The device always behaves as a battery device with or without mains power. It is sleepy, waking up every few seconds. 

I think it behaved the same using a tuya gateway/app but can't swear so. That gateway died and tested months ago. 

The "[no sensors](https://www.zigbee2mqtt.io/devices/NAS-AB02B2.html#neo-nas-ab02b2)" version acts like a normal mains device and responds immediately. Just be aware it will drain the battery in a day or two if not connected to mains.
