### ISSUE TITLE
Can't change channel

### ISSUE THREAD

**Issue by oupengopu** [Koenkk/zigbee2mqtt#14054]
### What happened?

The channel configuration is 25, the error can only be set to 11, cc2652p serial port CH340 The same goes for changing other channels
![6b08b6e5c5649a8c124091438f44832](https://user-images.githubusercontent.com/34147042/190893896-6dbdd483-52cc-4696-91a2-2a062ccdaebf.jpg)
![2a7bb77a1b12712b1c2336e7a8b162e](https://user-images.githubusercontent.com/34147042/190893902-dd3edcbc-d2f4-41ee-9300-ae0c3e39a46f.jpg)
![6b08b6e5c5649a8c124091438f44832](https://user-images.githubusercontent.com/34147042/190893906-9178f795-c628-477e-a619-9111c115e154.jpg)
my config file，God please help

external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.31.34/:1883
  user: zigbee2Mqtt
  password: zigbee2Mqtt
  force_disable_retain: false
serial:
  port: /dev/ttyUSB0
  baudrate: 115200
  rtscts: false
advanced:
  experimental:
    transmit_power: 20
  log_level: error
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  last_seen: disable
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: true

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

cc2652p serial port CH340 

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9593484/log.txt)

**Comment by Koenkk** [comment]
It is mandatory to remove your `coordinator_backup.json` before starting z2m when changing the channel.
