### ISSUE TITLE
Osram Smart+ Motion Sensor still does not work?

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#1406]
I got an Osram motion sensor, but it still does not work?
He is listed as supported in the list of supported devices?
I have the last DEV, but the sensor is not recognized

https://github.com/Koenkk/zigbee2mqtt/issues/507#issuecomment-481718610

https://github.com/Koenkk/zigbee2mqtt/issues/507

**Comment by Koenkk** [comment]
can you post your zigbee2mqtt startup log?

**Comment by salopette** [comment]
https://pastebin.com/gzMpMbMu

.db

https://pastebin.com/0TTSBA0w

**Comment by Koenkk** [comment]
The device was not paired correctly it seems (undefined model). Please remove it and re-pair.

**Comment by salopette** [comment]
no matter what I do, it connects again and again!

https://pastebin.com/ZTEVHtSU

**Comment by salopette** [comment]
Yesterday I completely deleted the zigbee2mqtt folder and set everything up again. And the motion detector was immediately recognized correctly
