### ISSUE TITLE
Automations not triggering

### ISSUE THREAD

**Issue by petro49er** [Koenkk/zigbee2mqtt#1407]
I've got a weird problem with automations sometimes not triggering.  Right now I am simply testing with xiaomi motion sensors triggering a switch (Lutron Caseta) to come on.  Sometimes it triggers, sometimes it doesn't.  I can see the motion in the zigbee2mqtt log and occupancy shows as true, but no automation kicks off.  I'm not sure where the breakdown is occurring.  Any idea where I can view logs to see where the breakdown might be happening?  I am running the following:
HASSIO 0.91.2 
zigbee2mqtt 1.2.1
Mosquito broker 4.1
Nod-RED 2.0.2

Thanks for any suggestions.

**Comment by 22MarioZ** [comment]
I had similar issue. It start working when I enable the automation..  Check in HA the state of the automation.

**Comment by petro49er** [comment]
Mario,
This is probably a dumb question but where do I check the status of an automation?  In my configuration.yaml file, the only thing I have that says anything about automation is:

automation: !include automations.yaml

Thank you for your help on this!

**Comment by petro49er** [comment]
> I had similar issue. It start working when I enable the automation.. Check in HA the state of the automation.

Mario,
This is probably a dumb question but where do I check the status of an automation? In my configuration.yaml file, the only thing I have that says anything about automation is:

automation: !include automations.yaml

Thank you for your help on this!

**Comment by 22MarioZ** [comment]
Open in the HA client (web) left side panel and at the bottom you have Developer tools. Click on <> and you will get new window "States". In the table you can see all HA entities and their states. Check the State column for specific automation if is on or off. If you click the icon in-front of the entity name an window will open where you can switch the automation on or off.

**Comment by petro49er** [comment]
> Open in the HA client (web) left side panel and at the bottom you have Developer tools. Click on <> and you will get new window "States". In the table you can see all HA entities and their states. Check the State column for specific automation if is on or off. If you click the icon in-front of the entity name an window will open where you can switch the automation on or off.

Mario,

When I check that page (<>) I can't seem to find an automation.  It's a simple automation created in Node-RED that says if motion is detected, turn on light.  If I look on the developer page, I see entries for the motion sensor and Caseta light switch.  I can't seem to turn the occupancy sensor on as there is no option for on when I click the link.  Am I not looking at the correct area?

Thanks,

Brian

**Comment by 22MarioZ** [comment]
Sorry. I thought you are using native HA automations. I cannot help you with Node-RED.

**Comment by petro49er** [comment]
> Sorry. I thought you are using native HA automations. I cannot help you with Node-RED.

No problem.  I appreciate your help!
