### ISSUE TITLE
Heimann smoke-detector no data

### ISSUE THREAD

**Issue by geeano** [Koenkk/zigbee2mqtt#14086]
### What happened?

Issue with 1 of two Heiman HS1SA-E smoke-detectors.
No data is retrieved from this sensor, reseting and new attempt to pair does not recover issue.

### What did you expect to happen?

That the sensor would work properly after pairing / reconnection

### How to reproduce it (minimal and precise)

After reset Heimann smokesensor (model HS1SA-E) the status remains as mentioned above. 
Not able to get any status update or alarm data.

### Zigbee2MQTT version

plugin: v.3.2.0-beta, zigbee2mqtt: v.1.24.0-dev (zStack12 20190608)

### Adapter firmware version

no data found

### Adapter

TI CC2531 (for several years)

### Debug log

{"definition":{"description":"Smoke detector","model":"HS3SA","supports":"smoke, battery_low, battery, linkquality","vendor":"HEIMAN"},"friendlyName":"keuken_rookmelder","ieeeAddr":"0x000d6f0015658a3d","lastSeen":1663605479895,"manufacturerName":"HEIMAN","modelID":"SmokeSensor-EM","networkAddress":34388,"type":"EndDevice"}

{"description":"Smoke detector","model":"HS3SA","supports":"smoke, battery_low, battery, linkquality","vendor":"HEIMAN"},"friendlyName":"boven_rookmelder","ieeeAddr":"0x000d6f00156541b4","lastSeen":1663604200619,"manufacturerName":"HEIMAN","modelID":"SmokeSensor-EM","networkAddress":38978,"type":"EndDevice"}

I do not get further data from the first sensor:
After reset follow output is given in the log:

debug 2022-09-19 19:02:25: Device 'keuken_rookmelder' announced itself

info  2022-09-19 19:02:26: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"keuken_rookmelder","ieee_address":"0x000d6f0015658a3d"},"type":"device_announce"}'

info  2022-09-19 19:02:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"keuken_rookmelder"},"type":"device_announced"}'

debug 2022-09-19 19:02:28: Retrieving state of 'keuken_rookmelder' after reconnect

No further messages appears from this sensor with exception of:
debug 2022-09-19 19:05:20: Device 'keuken_rookmelder' requested OTA

**Comment by annunity** [comment]
I was able to get data after I pressed the red button on the sound. Just cover your ears.

**Comment by geeano** [comment]
I pressed it also, but did not resulting in retrieving data..

**Comment by geeano** [comment]
Issue still not resolved, please give some guidance
