### ISSUE TITLE
Docker on Synology NAS

### ISSUE THREAD

**Issue by 19Homer73** [Koenkk/zigbee2mqtt#141]
Hello,

how can I run this docker container on an Synology NAS?
How does it finds the zwave-stick on the usb-slot?

Many thanks in advance!

Greetings,
Homer

**Comment by ciotlosm** [comment]
@19Homer73 you need to use docker to pass the device inside the container and reference it there through the configuration. 

- On your host do ls /dev/ and find the device you want to map inside the container. 
- Map the device inside the container (see: https://www.safaribooksonline.com/library/view/docker-cookbook/9781783984862/ch02s13.html)
- In your configuration, just point to the device inside the container.

**Comment by 19Homer73** [comment]
Ok, thank you, it works!!! GREAT!!!

One little thing:

The output in iobroker looks like this:
**{"temperature":23.2,"humidity":39.46}**

But I would like to have this:
**temperature:      23.2 °C**
**humidity:            39.46 %**

What do I have to change for that?
Many thanks in advance!

**Comment by 19Homer73** [comment]
Everything ist working fine now! Ticket can be closed!
