### ISSUE TITLE
Improve history view in homeassistant

### ISSUE THREAD

**Issue by Secretowo** [Koenkk/zigbee2mqtt#14103]
### What happened?

When viewing a generic sensors history, homeassistant displays the values seperately. 
![image](https://user-images.githubusercontent.com/63597541/191298632-7d56c505-6a02-41b2-a350-348e71093d25.png)

It seems that Homeassistant requires the unit_of_measurement key to be set, even without a value, to show a graph. 

Manually adding the key using the developer options makes the history show up as it should:
![image](https://user-images.githubusercontent.com/63597541/191299733-36cd76d0-878d-4f13-a8cf-26f8cde80a10.png)
![image](https://user-images.githubusercontent.com/63597541/191299744-58a565ed-5c6f-43be-b900-90206f549f4b.png)

Adding an empty unit_of_measurement to all sensors by defualt would likely fix this issue.

### What did you expect to happen?

I expected a nice graph, since its a numeric value.

### How to reproduce it (minimal and precise)

Have a generic sensor (One without a unit_of_measurement like °C, W, kW etc.) and view its history in Homeassistant.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

 0x26580700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
> Adding an empty unit_of_measurement to all sensors by defualt would likely fix this issue.

Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
