### ISSUE TITLE
NAS-AB02B0 reporting temperature with uneven steps

### ISSUE THREAD

**Issue by kds69** [Koenkk/zigbee2mqtt#14117]
### What happened?

Device NAS-AB02B0 is reporting only xx.9°C as temperature (19.9C, 20.9C, 21.9C etc), regardless precision settings (0, 1 or 2 doesn't change results in any way) in zigbee2mqtt console.
No specific error logs to show here.
Bug in conversion? presuming 19.9C means 20C.

### What did you expect to happen?

NAS-AB02B0 would report temperature according to precision settings and preferably with well rounded température.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

not reported by device, manufacturer model _TZE200_d0yu2xgi

### Adapter

zzh!

**Comment by lpriemis** [comment]
Hi All,

I have the same problem with the NAS-PD07.
![image](https://user-images.githubusercontent.com/42553253/193762019-6ae0a44b-ae26-474b-b93b-c0385fd85686.png)

At first i thought that it was not working at all but the temparature in my living room was just not fluctuating enough to change. As shown in the screenshot it's the same problem for the humidity. it's rounded by 5% for some reason.

I have 3 sensors like this and they all have the same problem.

I want to use them for controling the underfloor heating in the different rooms so this is really annoying. Any help would be great!

I tried messing around with the device specific settings but that is not really doing anything even the Farenheit vs Celcius setting is not doing anything.

KR Laurens
