### ISSUE TITLE
[New device support]: Philips Hue Xamento L - 915005997901

### ISSUE THREAD

**Issue by Bastian007** [Koenkk/zigbee2mqtt#14118]
### Link

https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-xamento--grose-deckenleuchte/4116831P9

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0x001788010bec0b34","nwkAddr":12701,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"915005997901","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"915005997901","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20220502","swBuildId":"1.93.11"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20220502","swBuildId":"1.93.11","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1663740315015,"defaultSendRequestWhen":"immediate"}

### Comments

Similar Model is already known and supported:
https://www.zigbee2mqtt.io/devices/915005997801.html

I guess the difference is only the size.
915005997801 vs. 915005997901
Philips Hue Xamento M vs. Philips Hue Xamento L

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.sens'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '915005997901', // Vendor model number, look on the device for a model number
    vendor: 'Philips', // Vendor of the device (only used for documentation and startup logging)
    description: 'Hue White & Color Ambiance Xamento L', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.battery(), e.temperature(), e.humidity()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Bastian007** [comment]
Great! Works as epxeced. Thanks for quick action.
