### ISSUE TITLE
Moes BRT-100-TRV does not update current_heating_temperature on mode switch

### ISSUE THREAD

**Issue by Udeson** [Koenkk/zigbee2mqtt#14115]
### What happened?

When switching from manual to programming mode (sending payload "preset": "programming") current_heating_temperature do not change/update to the scheduled temperature in the zigbee2mqtt frontend

current_heating_temperature updates (on zigbee2mqtt frontend) in the moment touching the TVR surface.

Finding: When changing the mode on the TVR itself no single payload is sent but the whole command set.

### What did you expect to happen?

When switched to programming mode via frontend (not changing the mode on the TVR itself!) current_heating_temperature should update to scheduled temperature.

### How to reproduce it (minimal and precise)

Change TRV mode via SmartHome (FHEM) front end via sending payload "preset": "programming".

### Zigbee2MQTT version

1.27.0 commit: a9b8808

### Adapter firmware version

20211217

### Adapter

Electrorama zig-a-zig-ah!

### Debug log

[logfile.txt](https://github.com/Koenkk/zigbee2mqtt/files/9611569/logfile.txt)

Devicename: zigbee2mqtt/SCH_ZIG_THERMOSTAT

**Comment by rotilho** [comment]
I had BRT-100-TRV and returned after I realized the calibration didn't trig any update. It wasn't Z2M problem but the TRV itself

**Comment by Udeson** [comment]
> I had BRT-100-TRV and returned after I realized the calibration didn't trig any update. It wasn't Z2M problem but the TRV itself

Sounds like bad news. On the other side wondering that there are many people here using this TRV model with no problems(?). But not updating the current_heating_setpoint to the programmed/schedule temperature is a deal breaker to me.

**Comment by rotilho** [comment]
I don't think so. It's a firmware defect and last time I checked it's not patched

**Comment by Udeson** [comment]
> I don't think so. It's a firmware defect and last time I checked it's not patched

So you are thinking the mentioned behaviour will be fixed via firmware ota update?

**Comment by willhaggan** [comment]
well it should work its based on tuya device which work from experienece of other devices
