### ISSUE TITLE
[New device support]: _TZ3000_7dndcnnb TS011F

### ISSUE THREAD

**Issue by amgstone** [Koenkk/zigbee2mqtt#14141]
### Link

https://www.aliexpress.com/item/1005004564755069.html?spm=a2g0o.order_list.0.0.10ea1802Xnlose

### Database entry

{"id":18,"type":"Router","ieeeAddr":"0xa4c1385221d10415","nwkAddr":49903,"manufId":4417,"manufName":"_TZ3000_7dndcnnb","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"seMetering":{"attributes":{"currentSummDelivered":[0,0]}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":229,"rmsCurrent":0,"activePower":0}},"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_7dndcnnb","powerSource":1,"zclVersion":3,"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2404276,"53251":134,"53252":12276,"53253":1497,"powerOnBehavior":2,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1663613980581,"defaultSendRequestWhen":"immediate"}

### Comments

LELLKI Tuya 220V Smart Switch 25A Plug Zigbee Light Switches Energy Monitor
![zxc](https://user-images.githubusercontent.com/63303107/191807248-b69ccda2-4825-41d3-acff-3d24e8b8b2ed.jpg)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by amgstone** [comment]
So there should be an update in 2 hours Zigbee2MQTT Edge?

**Comment by amgstone** [comment]
![zxcv](https://user-images.githubusercontent.com/63303107/191854594-2be54831-6a67-4de4-8150-41ca64bfe248.jpg)

**Comment by Koenkk** [comment]
You need to uninstall and install the addon again to update to the latest edge version.
