### ISSUE TITLE
Incorrect device type ZG50CC-CCT-DRIVER

### ISSUE THREAD

**Issue by draconight** [Koenkk/zigbee2mqtt#14144]
### What happened?

Device type incorrectly identified - ENVILAR ZG50CC-CCT-DRIVER identified as unsupported router.

"Zigbee2MQTT:warn  2022-09-22 20:42:37: Received message from unsupported device with Zigbee model 'HK-CCT' and manufacturer name 'Sunricher'"

### What did you expect to happen?

Correct identification and Support status Supported:
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/ZG50CC-CCT-DRIVER.md

### Zigbee2MQTT version

1.27.2-1

### Adapter firmware version

20220219

### Adapter

ZBDongle-P CC2652P

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
