### ISSUE TITLE
Commit hash always 'unknown' 

### ISSUE THREAD

**Issue by CodeFinder2** [Koenkk/zigbee2mqtt#1414]
I am using the latest zigbee2mqtt with the [HassIO addon](https://github.com/danielwelch/hassio-zigbee2mqtt) and observed that it always publishes something like
`AM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.3.0","commit":"unknown","coordinator_firmware":20190109,"log_level":"debug","permit_join":false}'`

I am referring to the "commit":"unknown" here. Should be just a minor issue. Or do I miss something? (I am not sure whether it's related to the HA plugin.)

**Comment by Koenkk** [comment]
This is an issue of the addon, please create it here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
