### ISSUE TITLE
[New device support]: _TZ3000_7dndcnnb, TS011F

### ISSUE THREAD

**Issue by amgstone** [Koenkk/zigbee2mqtt#14156]
### Link

599,00 грн.  47%OFF | LELLKI Tuya 220V Smart Switch 25A Plug Zigbee Light Switches Energy Monitor With Google Home Alexa Yandex Station Free Shipping https://a.aliexpress.com/_mMCg9uG

### Database entry

{"id":18,"type":"Router","ieeeAddr":"0xa4c1385221d10415","nwkAddr":49903,"manufId":4417,"manufName":"_TZ3000_7dndcnnb","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"seMetering":{"attributes":{"currentSummDelivered":[0,0]}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":229,"rmsCurrent":0,"activePower":0}},"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_7dndcnnb","powerSource":1,"zclVersion":3,"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2404276,"53251":134,"53252":12276,"53253":1497,"powerOnBehavior":2,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1663613980581,"defaultSendRequestWhen":"immediate"}

### Comments

not work in zigbee2mqtt

**Comment by Koenkk** [comment]
`_TZ3000_7dndcnnb` is already supported in the dev branch. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
