### ISSUE TITLE
HVAC-Mode Problem with Siterwell GS361A-H04 TRV

### ISSUE THREAD

**Issue by Ecronika** [Koenkk/zigbee2mqtt#14164]
### What happened?

The target temperature is not changed by the thermostat via the Home Assistant service Climate.Set_Temperature if the HVAC mode "heat" is set at the same time.

Without an HVAC mode, the temperature can be changed and the HVAC mode can also be changed via the "Climate.Set_HVAC_Mode" service, but setting both via Climate.Set_Temperature is not possible.

I'm not sure if the problem is with HA, Zigbee2MQTT or the device definition.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by kalda123** [comment]
I also have a similar problem, in about 50% of cases I can't control the temperature of the radiator using the service or automation.
