### ISSUE TITLE
Tuya RH3040 stuck in motion detected state

### ISSUE THREAD

**Issue by SnakeZi** [Koenkk/zigbee2mqtt#14175]
### What happened?

I have just received a new unit after warranty claim. The first one was actually killed by Home Assistant. It seems this new unit is approaching the same fate.

https://www.houseiq.pl/pl/p/Mini-czujnik-ruchu-obecnosci-PIR-ZigBee-3.0-TUYA/1230

I have put the PIR sensor into the box so it couldn't detect any motion. Still it is refreshing its occupancy:true state every minute. You can see this in debug logs.

I think the most important part - when I take the sensor from the box and start waving before it, I don't see any new mqtt messages in debug log. PIR is triggering itself alone and because of the 1 minute re-arm time it doesn't react to anything between. So this is not only the software thing.

Database entry:
`{"id":52,"type":"EndDevice","ieeeAddr":"0x000d6ffffe65311f","nwkAddr":53158,"manufId":0,"manufName":"TUYATEC-i9TxRD2l","powerSource":"Battery","modelId":"RH3040","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{"appVersion":67,"modelId":"RH3040","manufacturerName":"TUYATEC-i9TxRD2l","powerSource":3,"zclVersion":2,"stackVersion":0,"dateCode":"20180512"}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryPercentageRemaining":200}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0024c2d3f9","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"dateCode":"20180512","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1664016744800,"defaultSendRequestWhen":"immediate"}`

### What did you expect to happen?

The sensor resets its occupancy state correctly in Tuya app (Silvercrest gateway) and can be used for automation. I'd like it to work the same with Home Assistant/Z2M.

### How to reproduce it (minimal and precise)

Just join it to Z2M.

Rebooting whole Home Assistant doesn't help.
Rejoining device doesn't help.
Adding "occupancy_timeout: 60" to configuration.yaml (no such option for this device in frontend) doesn't help.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle-P ZigBee Dongle Plus CC2652P

### Debug log

Debug 2022-09-24 12:44:38Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":0}' from endpoint 1 with groupID 0
Info 2022-09-24 12:44:38MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":25,"occupancy":false,"tamper":false}'
Debug 2022-09-24 12:44:39Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
Info 2022-09-24 12:44:39MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":25,"occupancy":true,"tamper":false}'
Debug 2022-09-24 12:45:39Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":0}' from endpoint 1 with groupID 0
Info 2022-09-24 12:45:39MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":36,"occupancy":false,"tamper":false}'
Debug 2022-09-24 12:45:40Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
Info 2022-09-24 12:45:40MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":40,"occupancy":true,"tamper":false}'
Debug 2022-09-24 12:46:40Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":0}' from endpoint 1 with groupID 0
Info 2022-09-24 12:46:40MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":102,"occupancy":false,"tamper":false}'
Debug 2022-09-24 12:46:40Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
Info 2022-09-24 12:46:40MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":102,"occupancy":true,"tamper":false}'
Debug 2022-09-24 12:47:41Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":0}' from endpoint 1 with groupID 0
Info 2022-09-24 12:47:41MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":102,"occupancy":false,"tamper":false}'
Debug 2022-09-24 12:47:41Received Zigbee message from '0x000d6ffffe65311f', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
Info 2022-09-24 12:47:41MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe65311f', payload '{"battery":null,"battery_low":false,"linkquality":102,"occupancy":true,"tamper":false}'

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/30f6773fb437dbe2f7e3e33473349b5e

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Koenkk** [comment]
Updated https://gist.github.com/Koenkk/30f6773fb437dbe2f7e3e33473349b5e

**Comment by Koenkk** [comment]
> And when sensor is closed in the box it still detects movement every minute

This doesn't look good, seems it detects occupancy without it actually being there. Looks like the unit is faulty if that is the case.

**Comment by Koenkk** [comment]
Thats strange indeed, I can check what the difference is if you provide me a sniff when pairing it to the TuYa gateway and triggering occupancy with it: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by kyberias** [comment]
I can confirm this is still an issue. Just tried it with the latest version of zigbee2mqtt and observed the same behavior: the sensor is stuck in detecting motion (occupancy: true).
