### ISSUE TITLE
Develco SPLZB-132 - incorrect power (wattage) reporting 

### ISSUE THREAD

**Issue by f432** [Koenkk/zigbee2mqtt#14176]
### What happened?

Power reporting is incorrect for this device

![image](https://user-images.githubusercontent.com/67050404/192105421-f81edd85-99dd-4c38-99ab-206b155856c8.png)

So 234.13 x 0.12 = 28.095W

So a /1000 error ?

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20210708

### Adapter

Slaesh CC2652rb stick

**Comment by Koenkk** [comment]
@NameLessJedi does this device still work correctly for you?

**Comment by NameLessJedi** [comment]
Actually I did not check this that carefully till now.
One thing is that reporting of each value might be taken at different point of time so the value might not match.
@f432 please check the "Reporting" tab of device and see how (and if) rep intervals and min rep change are set.
Put some constant load on this device and check again.
I'll try to check this too

**Comment by f432** [comment]
Sorry about delay, been away for work. Using a tumble dryer i get a constant reading but not 100% correct. Reporting is default

![image](https://user-images.githubusercontent.com/67050404/195057190-1ec6e544-2665-40b7-81a7-bccda34a189d.png)

Below is the reporting for all devices incl where I am getting a 0.1 W reading. No Min rep change setting for "seMetering" if that makes a difference 

![image](https://user-images.githubusercontent.com/67050404/195058074-650f6358-a89d-469b-9d76-54a915a05d13.png)
