### ISSUE TITLE
Zigbee2MQTT shows hundreds of unknown devices

### ISSUE THREAD

**Issue by and7ey** [Koenkk/zigbee2mqtt#14183]
### What happened?

The main page of Zigbee2MQTT HA addon shows hundreds of unknown devices:
<img width="1177" alt="Снимок экрана 2022-09-25 в 10 46 48" src="https://user-images.githubusercontent.com/900474/192133569-879b877a-7c90-4200-868f-9ab0194e6830.png">
I would like to understand why they appeared and how to delete them in bulk (clicking 'delete', then 'force remove' one by one will take a lot of time).

### Zigbee2MQTT version

1.27.2 commit: unknown

### Adapter firmware version

6.7.10.0 build 423

### Adapter

EZSP v8 (xiaomi gateway 3)

**Comment by sergeymatsay** [comment]
After updating to 1.27.2, all tuya ts0011 relays stopped working.  when trying to paring gives the same error.
![Screenshot_20220926_172621_Browser](https://user-images.githubusercontent.com/95618955/192315150-ff0567ca-32b5-4190-86b5-b39cec08010e.jpg)

**Comment by marwonn** [comment]
> ### What happened?
> The main page of Zigbee2MQTT HA addon shows hundreds of unknown devices: <img alt="Снимок экрана 2022-09-25 в 10 46 48" width="1177" src="https://user-images.githubusercontent.com/900474/192133569-879b877a-7c90-4200-868f-9ab0194e6830.png"> I would like to understand why they appeared and how to delete them in bulk (clicking 'delete', then 'force remove' one by one will take a lot of time).
> 
> ### What did you expect to happen?
> _No response_
> 
> ### How to reproduce it (minimal and precise)
> _No response_
> 
> ### Zigbee2MQTT version
> 1.27.2 commit: unknown
> 
> ### Adapter firmware version
> 6.7.10.0 build 423
> 
> ### Adapter
> EZSP v8 (xiaomi gateway 3)
> 
> ### Debug log
> _No response_

Same here. Dozens of unknown devices since a few days.

**Comment by Koenkk** [comment]
@kirovilya could you check this?

**Comment by kirovilya** [comment]
@marwonn @sergeymatsay @and7ey Please check on the latest/edge dev version of z2m - changes have been made to improve device pairing.
But! You need to create a new network! To do this, you should change the channel or panId - in this case, the list of devices will be cleared and you will have to pair the devices again.

**Comment by and7ey** [comment]
Thanks. I've just deleted unknown devices manually from .db file. Works well now.
