### ISSUE TITLE
Aeotec Zi extender does not work. 

### ISSUE THREAD

**Issue by jeremynieuwpoort** [Koenkk/zigbee2mqtt#14189]
### What happened?

I connected my Aeotec Extender Zi in Zigbee2MQTT. 
I received the messages about unavailable device. 
Then I created a WG001-Z01.js file next to log and state.json 

WG001-Z01.js is like: 
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['WG001-Z01'],
        model: 'WG001',
        vendor: 'Aeotec',
        description: 'Range extender Zi',
        fromZigbee: [fz.linkquality_from_basic],
        toZigbee: [],
        exposes: [],
    },
];

module.exports = definition;

======
After that I changed the configuration.yaml. as in the manual:
advanced:
  log_level: info
to:
advanced:
  log_level: debug
external_converters:
  - WG001-Z01.js

After that I get the 502: bad gateway error. After changing the configuration.yaml to log_level: info it is working again. But the Aeotec Extender Zi is not working.

I hope somebody can help me! 

Thanks a lot.

### Zigbee2MQTT version

1.27.2 commit: unknown

### Adapter firmware version

0x26780700

### Adapter

Conbee 2

**Comment by amoi69** [comment]
Hi,

I am getting the same device and wondering if you were able to add it to Z2M?
 None of the external converters I tried is working.

Thank you
