### ISSUE TITLE
Norwegian language is just English

### ISSUE THREAD

**Issue by Lovasz-Akos** [Koenkk/zigbee2mqtt#14194]
### What happened?

Switched language to Norwegian and it's just English

### What did you expect to happen?

The language will be Norwegian

### How to reproduce it (minimal and precise)

Click Norwegian in the language selector

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

ezsp v8

### Adapter

ezsp

**Comment by sjorge** [comment]
The frontend has it's own repo here: https://github.com/nurikk/zigbee2mqtt-frontend
You probably want to file the report there.

**Comment by Lovasz-Akos** [comment]
ah okay thank you
