### ISSUE TITLE
Pinging to a working device keeps failing

### ISSUE THREAD

**Issue by YamiFrankc** [Koenkk/zigbee2mqtt#1420]
Hello,

I noticed that zigbee2mqtt keeps sending failed pings to a device that is working correctly( AduroSmart ERIA colors and white shades smart light bulb A19 )

I updated to latest dev a few moments ago, here is the log: [log](https://pastebin.com/U4z8Na2Y)

So Im wondering why is that happening and if it might cause problems.
Thanks

**Comment by Koenkk** [comment]
Can you post your `database.db` file?

**Comment by YamiFrankc** [comment]
[Pastebin](https://pastebin.com/wKQDupej)

**Comment by Koenkk** [comment]
can you check if this is fixed in the latest dev branch?

**Comment by YamiFrankc** [comment]
Seems like its working now. It not pinging it anymore!
Thanks

**Comment by Koenkk** [comment]
great!
