### ISSUE TITLE
IKEA E1524/E1810 control loses binding with some devices after a while

### ISSUE THREAD

**Issue by groenmarsmannetje** [Koenkk/zigbee2mqtt#14215]
### What happened?

I have a couple of IKEA E1524/E1810 controls with latest firmware (Firmware build date 20210727 Firmware version 2.3.080). They have bindings with multiple lights because binding to a group was not possible anymore. I notice that often with several of these controls the binding with one or more of the lights is not working anymore after a while. To solve this I need to manually unbind and bind again to make it work again for a while.

This doesn't happen to other E1524/E1810 controls that I did not upgrade with latest firmware, because for those I want them to bind on group level.

### What did you expect to happen?

Bindings remain working over time

### How to reproduce it (minimal and precise)

After a while a light that was bound will not turn on/off anymore when you press the on/off button. Not sure what causes this. The binding itself is still visible when you look at the bindings in the Z2M user interface. 

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20211217

### Adapter

Zzh!

**Comment by Visje31** [comment]
It seems I'm havin g a similar problem. Not just the controls (E1525/E1745), but also all the IKEA Tradfri lights are unresponsive all of a sudden.
I have a Aqara door & window ([MCCGQ11LM]) which still works fine, but all Tradfri devices are offline.

**Comment by groenmarsmannetje** [comment]
That is different then my problem. I can still control the individual lights with HA.
