### ISSUE TITLE
Xiaomi JY-GZ-01AQ  Selftest not working in HA

### ISSUE THREAD

**Issue by koemat** [Koenkk/zigbee2mqtt#14236]
### What happened?

The  detector self test from HA does not work. When i use the button in the Zigbee2Mqtt addon, the self test is working correct.
![Zigbee2mqtt](https://user-images.githubusercontent.com/95163242/192852021-0e117bd5-4537-4a0a-a18a-7f8ce8fc5fd4.jpg)

### How to reproduce it (minimal and precise)

The dropdown menu for selftest in the device menu in HA is empty.
![HA](https://user-images.githubusercontent.com/95163242/192851755-43613f4f-cc2f-4403-b695-7d17f0b8826d.jpg)

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

20220219

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle

**Comment by Danit2** [comment]
I have the same issues. 
I have make a PR to correct them. 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/4720
