### ISSUE TITLE
[New device support]: Essentials radiator thermostat

### ISSUE THREAD

**Issue by konvex1337** [Koenkk/zigbee2mqtt#14239]
### Link

https://www.globus-baumarkt.de/essentials-smart-home-heizkoerperthermostat-zigbee?utm_source=awin&utm_medium=176013_RedBrain&utm_campaign=awo&utm_content=0&utm_term=26068275667&awc=11830_1664396331_181d5f856dc4fb5bb39cc41791b288c7

### Database entry

debug 2022-09-28 22:20:33Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,153],"type":"Buffer"},"datatype":2,"dp":34}],"seq":8704}' from endpoint 1 with groupID 0 info 2022-09-28 22:20:33zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #34 from 0x84ba20fffe3246a1 with raw data '{"dp":34,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,153]}}': type='commandDataReport', datatype='value', value='153', known DP# usage: [] debug 2022-09-28 22:21:03Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,45],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4096}' from endpoint 1 with groupID 0 info 2022-09-28 22:21:03zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #16 from 0x84ba20fffe3246a1 with raw data '{"dp":16,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,45]}}': type='commandDataReport', datatype='value', value='45', known DP# usage: ["moesHeatingSetpoint","tvHeatingSetpoint","haozeeMaxTemp","AM02Border","x5hSetTemp","connecteHeatingSetpoint","alectoSilence"] debug 2022-09-28 22:22:12Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,34],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4096}' from endpoint 1 with groupID 0 info 2022-09-28 22:22:12zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #16 from 0x84ba20fffe3246a1 with raw data '{"dp":16,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,34]}}': type='commandDataReport', datatype='value', value='34', known DP# usage: ["moesHeatingSetpoint","tvHeatingSetpoint","haozeeMaxTemp","AM02Border","x5hSetTemp","connecteHeatingSetpoint","alectoSilence"] debug 2022-09-28 22:22:59Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":2}],"seq":512}' from endpoint 1 with groupID 0 info 2022-09-28 22:22:59zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #2 from 0x84ba20fffe3246a1 with raw data '{"dp":2,"datatype":4,"data":{"type":"Buffer","data":[2]}}': type='commandDataReport', datatype='enum', value='2', known DP# usage: ["heatingSetpoint","coverPosition","eardaDimmerLevel","moesHold","moesSheatingSetpoint","silvercrestChangeMode","tuyaSabCO2","tuyaSahkMP25","tuyaSabCO","moes105DimmerLevel1","trsSensitivity","trsfSensitivity","tvMode","haozeeHeatingSetpoint","nousHumidity","tthHumidity","tIlluminanceLux","evanellMode","AM02PercentControl","x5hMode","connecteMode","tshpscSensitivity","alectoSmokeValue"] debug 2022-09-28 22:23:48Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":2}],"seq":512}' from endpoint 1 with groupID 0 info 2022-09-28 22:23:48zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #2 from 0x84ba20fffe3246a1 with raw data '{"dp":2,"datatype":4,"data":{"type":"Buffer","data":[1]}}': type='commandDataReport', datatype='enum', value='1', known DP# usage: ["heatingSetpoint","coverPosition","eardaDimmerLevel","moesHold","moesSheatingSetpoint","silvercrestChangeMode","tuyaSabCO2","tuyaSahkMP25","tuyaSabCO","moes105DimmerLevel1","trsSensitivity","trsfSensitivity","tvMode","haozeeHeatingSetpoint","nousHumidity","tthHumidity","tIlluminanceLux","evanellMode","AM02PercentControl","x5hMode","connecteMode","tshpscSensitivity","alectoSmokeValue"] debug 2022-09-28 22:24:50Received Zigbee message from '0x84ba20fffe3246a1', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,43],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4096}' from endpoint 1 with groupID 0 info 2022-09-28 22:24:50zigbee-herdsman-converters:tuya_data_point_dump: Received Tuya DataPoint #16 from 0x84ba20fffe3246a1 with raw data '{"dp":16,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,43]}}': type='commandDataReport', datatype='value', value='43', known DP# usage: ["moesHeatingSetpoint","tvHeatingSetpoint","haozeeMaxTemp","AM02Border","x5hSetTemp","connecteHeatingSetpoint","alectoSilence"]

### Comments

Need help to setup the external converter.
The device looks like the silvercrest thermostat from the vendor lidl.
I tested some changes in the line "fromzigbee" and "tozigbee" but nothing worked.
I copyed the lines of the lidl device to my external converter file but zigbee did not restart "Error const" not find
Changed the const lines to the lidl once but the same happens.

Did i have to creat a fromzigbee.js and tozigbee.js file in any folder ?

Thank you

### Supported color modes

no

### Color temperature range

no

**Comment by konvex1337** [comment]
i think it is the same issue as #13962

**Comment by konvex1337** [comment]
get suck with the payload test

topic :
zigbee2mqtt/0x84ba20fffe3246a1/set/tuya_data_point_test
payload :
16,2,[0,0,0,45]
is it the correct payload ?

**Comment by Longlife4ever** [comment]
I have the same Valve, need help, too.

What has to be done to get all the information for a full support of the device?

**Comment by TAKeanice** [comment]
Someone was successful (at least partially) by adding the device identifier _TZE200_i48qyn9s to this line https://github.com/Koenkk/zigbee-herdsman-converters/blob/b776f639bc37339b328abd612a6fb367a5cba76b/devices/lidl.js#L842 in the lidl.js device adapter, in this issue: https://github.com/ioBroker/ioBroker.zigbee/issues/1400. Of course, this is kind of hacky.

Allegedly this converter https://gist.github.com/serrj-sv/af142b25de2d7ac54c3a2eb2623d9a6d is what solved the issue in the forum entry https://forum.iobroker.net/topic/58272/essentials-zigbee-thermostat-external-converter-einbinden (at least on the Zigbee2Mqtt side) and led to the already mentioned issue https://github.com/ioBroker/ioBroker.zigbee/issues/1527

**Comment by TAKeanice** [comment]
I can report that https://gist.github.com/serrj-sv/af142b25de2d7ac54c3a2eb2623d9a6d really seems to cover and properly parse all the data points from the essentials thermostat. I will work a little on the exposes part of the definition and then publish my solution as a basis for integrating it into the main converter repo.

**Comment by konvex1337** [comment]
THX

**Comment by TAKeanice** [comment]
So far, I have this:
```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const tuyaLocal = {
  dataPoints: {
  sh4Mode: 2,
  sh4HeatingSetpoint: 16,
  sh4LocalTemp: 24,
  sh4ChildLock: 30,
  sh4Battery: 34,
  sh4FaultCode: 45,
  sh4ComfortTemp: 101,
  sh4EcoTemp: 102,
  sh4VacationPeriod: 103,
  sh4TempCalibration: 104,
  sh4ScheduleTempOverride: 105,
  sh4RapidHeating: 106,
  sh4WindowStatus: 107,
  sh4Hibernate: 108,
  sh4ScheduleMon: 109,
  sh4ScheduleTue: 110,
  sh4ScheduleWed: 111,
  sh4ScheduleThu: 112,
  sh4ScheduleFri: 113,
  sh4ScheduleSat: 114,
  sh4ScheduleSun: 115,
  sh4OpenWindowTemp: 116,
  sh4OpenWindowTime: 117,
  sh4RapidHeatCntdownTimer: 118,
  sh4TempControl: 119,
  sh4RequestUpdate: 120,
  },
};
const fzLocal = {
  sh4_thermostat: {
    cluster: 'manuSpecificTuya',
    type: ['commandDataResponse', 'commandDataReport'],
    convert: (model, msg, publish, options, meta) => {
      //const dp = msg.data.dp;
      //const value = tuya.getDataValue(msg.data.datatype, msg.data.data);
      const dpValue = tuya.firstDpValue(msg, meta, 'sh4_thermostat');
      const dp = dpValue.dp;
      const value = tuya.getDataValue(dpValue);
      function weeklySchedule(day, value) {
        // byte 0 - Day of Week (0~7 = Mon ~ Sun) <- redundant?
        // byte 1 - 1st period Temperature (1~59 = 0.5~29.5°C (0.5 step))
        // byte 2 - 1st period end time (1~96 = 0:15 ~ 24:00 (15 min increment, i.e. 2 = 0:30, 3 = 0:45, ...))
        // byte 3 - 2nd period Temperature
        // byte 4 - 2nd period end time
        // ...
        // byte 16 - 8th period end time
        // byte 17 - 9th period Temperature
        let daySchedule = {};
        for (let i = 1; i <= 9; i++) {
          const tempId = ((i-1) * 2) +1;
          const timeId = ((i-1) * 2) +2;
          setpoint = {};
          setpoint['temperature'] = (value[tempId] / 2).toFixed(1);
          if (i!=9) {
              setpoint['hour'] = Math.floor(value[timeId] / 4).toString().padStart(2, '0');
              setpoint['minute'] = ((value[timeId] % 4) *15).toString().padStart(2, '0');
          }
          daySchedule[`${i}`] = setpoint
        }
        const weekDays=['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
        return {[weekDays[day]]: daySchedule};
      }
      switch (dp) {
      case tuyaLocal.dataPoints.sh4Mode: // 2
        // 0-Schedule; 1-Manual; 2-Away
        if (value == 0) {
          return {
          system_mode: 'auto',
          current_heating_setpoint: meta.state.schedule_heating_setpoint_override
          };
        } else if (value == 1) {
          return {
          system_mode: 'heat',
          current_heating_setpoint: meta.state.manual_heating_setpoint
          };
        } else if (value == 2) {
          return {
          system_mode: 'off',
          current_heating_setpoint: -1 // need implement read away_preset_temperature
          };
        };
        meta.logger.warn(`zigbee-herdsman-converters:essentialsThermostat: NOT RECOGNIZED MODE #${value}`);
        break;
      case tuyaLocal.dataPoints.sh4HeatingSetpoint: // 16
        // 0 - Valve full OFF, 60 - Valve full ON : only in "manual" mode
        return {
          manual_heating_setpoint: (value / 2).toFixed(1),
          current_heating_setpoint: (value / 2).toFixed(1)
        };
      case tuyaLocal.dataPoints.sh4LocalTemp: // 24
        return {local_temperature: (value / 10).toFixed(1)};
      case tuyaLocal.dataPoints.sh4ChildLock: // 30
        return {child_lock: value ? 'LOCK' : 'UNLOCK'};
      case tuyaLocal.dataPoints.sh4Battery: // 34
        return {
          battery: value > 130 ? 100 : value < 70 ? 0 : ((value - 70)*1.7).toFixed(1),
          battery_low: value < 90,
        };
      case tuyaLocal.dataPoints.sh4FaultCode: // 45
        meta.logger.warn(`zigbee-herdsman-converters:essentialsThermostat: ERROR CODE received: ${JSON.stringify(msg.data)}`);
        break;
      case tuyaLocal.dataPoints.sh4ComfortTemp: // 101
        return {comfort_temperature: (value / 2).toFixed(1)};
      case tuyaLocal.dataPoints.sh4EcoTemp: // 102
        return {eco_temperature: (value / 2).toFixed(1)};
      case tuyaLocal.dataPoints.sh4VacationPeriod: // 103
        return {
          away_setting: {
            year: value[0]+2000,
            month: value[1],
            day: value[2],
            hour: value[3],
            minute: value[4],
            away_preset_temperature: (value[5] /2).toFixed(1),
            away_preset_days: value[6]<< 8 | value[7],
          },
        };
        // byte 0 - Start Year (0x00 = 2000)
        // byte 1 - Start Month
        // byte 2 - Start Day
        // byte 3 - Start Hour
        // byte 4 - Start Minute
        // byte 5 - Temperature (1~59 = 0.5~29.5°C (0.5 step))
        // byte 6-7 - Duration in Hours (0~2400 (100 days))
      case tuyaLocal.dataPoints.sh4TempCalibration: // 104
        return {local_temperature_calibration: value > 55 ?
          ((value - 0x100000000)/10).toFixed(1): (value/ 10).toFixed(1)};
      case tuyaLocal.dataPoints.sh4ScheduleTempOverride: // 105
        if (meta.state.system_mode == 'auto') {
          return {
          schedule_heating_setpoint_override: (value / 2).toFixed(1),
          current_heating_setpoint: (value / 2).toFixed(1)
          }
        } else {
          return {schedule_heating_setpoint_override: (value / 2).toFixed(1)}
        }
      case tuyaLocal.dataPoints.sh4RapidHeating: // 106
        break; //TODO
      case tuyaLocal.dataPoints.sh4WindowStatus: // 107
        return {window_open: value ? 'YES' : 'NO'};
      case tuyaLocal.dataPoints.sh4Hibernate: // 108
        break; //TODO
      case tuyaLocal.dataPoints.sh4ScheduleMon: // 109
        return weeklySchedule(0, value);
      case tuyaLocal.dataPoints.sh4ScheduleTue: // 110
        return weeklySchedule(1, value);
      case tuyaLocal.dataPoints.sh4ScheduleWed: // 111
        return weeklySchedule(2, value);
      case tuyaLocal.dataPoints.sh4ScheduleThu: // 112
        return weeklySchedule(3, value);
      case tuyaLocal.dataPoints.sh4ScheduleFri: // 113
        return weeklySchedule(4, value);
      case tuyaLocal.dataPoints.sh4ScheduleSat: // 114
        return weeklySchedule(5, value);
      case tuyaLocal.dataPoints.sh4ScheduleSun: // 115
        return weeklySchedule(6, value);
      case tuyaLocal.dataPoints.sh4OpenWindowTemp: // 116
        return {open_window_temperature: (value / 2).toFixed(1)};
      case tuyaLocal.dataPoints.sh4OpenWindowTime: // 117
        return {detectwindow_timeminute: value};
      case tuyaLocal.dataPoints.sh4RapidHeatCntdownTimer: // 118
        break; //TODO
      case tuyaLocal.dataPoints.sh4TempControl: // 119
        break; //TODO
      case tuyaLocal.dataPoints.sh4RequestUpdate: // 120
        break; //TODO
      default:
        meta.logger.warn(`zigbee-herdsman-converters:essentialsThermostat: NOT RECOGNIZED DP #${dp} with data ${JSON.stringify(msg.data)}`);
      }
    },
  },
};

const tzLocal = {
  sh4_thermostat_current_heating_setpoint: {
    key: ['current_heating_setpoint'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      if (meta.state.system_mode == 'heat') {
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4HeatingSetpoint, temp);
      } else if (meta.state.system_mode == 'auto') {
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ScheduleTempOverride, temp);
      }
    },
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_comfort_temp_preset: {
    key: ['comfort_temperature'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ComfortTemp, temp);
    },
  },
  sh4_thermostat_eco_temp_preset: {
    key: ['eco_temperature'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4EcoTemp, temp);
    },
  },
  sh4_thermostat_schedule_override_setpoint: {
    key: ['schedule_override_setpoint'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ScheduleTempOverride, temp);
    },
  },
  sh4_thermostat_get_data: {
    key: ['local_temperature'],
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_mode: {
    key: ['system_mode'],
    convertSet: async (entity, key, value, meta) => {
      if ( value == 'auto' ) {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 0);
      } else if ( value == 'heat' ) {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 1);
      } else if ( value == 'off') {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 2);
        //await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4HeatingSetpoint, 0);
      }
    },
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_open_window_temp: {
    key: ['open_window_temperature'],
    convertSet: async (entity, key, value, meta) => {
        let temp = Math.round(value * 2);
        if (temp<=0) temp = 1;
        if (temp>=60) temp = 59;
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4OpenWindowTemp, temp);
    },
  },
  sh4_thermostat_open_window_time: {
    key: ['detectwindow_timeminute'],
    convertSet: async (entity, key, value, meta) => {
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4OpenWindowTime, value);
    },
  },
  sh4_thermostat_away: {
    key: ['away_setting'],
    convertSet: async (entity, key, value, meta) => {
      const output= new Uint8Array(8);
      // byte 0 - Start Year (0x00 = 2000)
      // byte 1 - Start Month
      // byte 2 - Start Day
      // byte 3 - Start Hour
      // byte 4 - Start Minute
      // byte 5 - Temperature (1~59 = 0.5~29.5°C (0.5 step))
      // byte 6-7 - Duration in Hours (0~2400 (100 days))
      output[0]=value.year > 2000 ? value.year-2000 : value.year; // year
      output[1]=value.month; // month
      output[2]=value.day; // day
      output[3]=value.hour; // hour
      output[4]=value.minute; // min
      output[5]=Math.round(value.away_preset_temperature * 2);
      output[7]=value.away_preset_days & 0xFF;
      output[6]=value.away_preset_days >> 8;
      meta.logger.info(JSON.stringify({'send to tuya': output, 'value was': value, 'key was': key}));
      await tuya.sendDataPointRaw(entity, tuyaLocal.dataPoints.sh4VacationPeriod, output);
    },
  },
  sh4_thermostat_schedule: {
    key: ['monday' , 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    convertSet: async (entity, key, value, meta) => {
      // byte 0 - Day of Week (0~7 = Mon ~ Sun) <- redundant?
      // byte 1 - 1st period Temperature (1~59 = 0.5~29.5°C (0.5 step))
      // byte 2 - 1st period end time (1~96 = 0:15 ~ 24:00 (15 min increment, i.e. 2 = 0:30, 3 = 0:45, ...))
      // byte 3 - 2nd period Temperature
      // byte 4 - 2nd period end time
      // ...
      // byte 16 - 8th period end time
      // byte 17 - 9th period Temperature
      const output= new Uint8Array(18); // empty output byte buffer
      meta.logger.info(`schedule received with key: ${key}\nvalue: ${Json.stringify(value)}`)
    },
  },
  sh4_thermostat_child_lock: {
    key: ['child_lock'],
    convertSet: async (entity, key, value, meta) => {
      await tuya.sendDataPointBool(entity, tuyaLocal.dataPoints.sh4ChildLock,
        ['LOCKED', 'ON', 'LOCK'].includes(value.toUpperCase()));
    },
  },
  sh4_thermostat_calibration: {
    key: ['local_temperature_calibration'],
    convertSet: async (entity, key, value, meta) => {
      if (value > 0) value = value*10;
      if (value < 0) value = value*10 + 0x100000000;
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4TempCalibration, value);
    },
  },
};

const device = {
  fingerprint: [
    {
      modelID: 'TS0601',
      manufacturerName: '_TZE200_i48qyn9s'
    },
  ],
  model: 'SH4 Zigbee eTRV',
  vendor: 'Tuya',
  description: 'Zigbee Radiator Thermostat',
  fromZigbee: [
    fz.ignore_basic_report,
    fzLocal.sh4_thermostat,
  ],
  toZigbee: [
    tzLocal.sh4_thermostat_current_heating_setpoint,
    tzLocal.sh4_thermostat_comfort_temp_preset,
    tzLocal.sh4_thermostat_eco_temp_preset,
    tzLocal.sh4_thermostat_away,
    tzLocal.sh4_thermostat_mode,
    tzLocal.sh4_thermostat_child_lock,
    tzLocal.sh4_thermostat_calibration,
    tzLocal.sh4_thermostat_schedule_override_setpoint,
    tzLocal.sh4_thermostat_schedule,
    tzLocal.sh4_thermostat_get_data,
    tzLocal.sh4_thermostat_open_window_temp,
    tzLocal.sh4_thermostat_open_window_time,
    tz.tuya_data_point_test,
  ],
  onEvent: tuya.onEventSetLocalTime,
  exposes: [
    e.battery(),
    e.battery_low(),
    e.child_lock(),
    exposes.climate().withSetpoint('current_heating_setpoint', 0.5, 29.5, 0.5)
                     .withLocalTemperature()
                     .withLocalTemperatureCalibration(-12.5, 5.5, 0.1, ea.STATE_SET)
                     .withSystemMode(['auto','heat','off'], ea.ALL, 'Mode auto: schedule active. Mode heat: manual temperature setting. Mode off: "away" setting active'),
    e.comfort_temperature(),
    e.eco_temperature(),
    e.open_window_temperature()
                      .withDescription('open winow detection temperature'),
    exposes.binary('window_open', ea.STATE, 'YES', 'NO')
                      .withDescription('Open window detected'),
    exposes.numeric('detectwindow_timeminute', ea.STATE_SET)
                     .withUnit('min')
                     .withDescription('Open window time in minutes')
                     .withValueMin(0).withValueMax(1000),
    exposes.composite('away_setting', 'away_setting')
                     .withFeature(e.away_preset_days())
                     .withFeature(e.away_preset_temperature())
                     .withFeature(exposes.numeric('year', ea.STATE_SET).withUnit('year').withDescription('Start away year 20xx'))
                     .withFeature(exposes.numeric('month', ea.STATE_SET).withUnit('month').withDescription('Start away month'))
                     .withFeature(exposes.numeric('day', ea.STATE_SET).withUnit('day').withDescription('Start away day'))
                     .withFeature(exposes.numeric('hour', ea.STATE_SET).withUnit('hour').withDescription('Start away hours'))
                     .withFeature(exposes.numeric('minute', ea.STATE_SET).withUnit('min').withDescription('Start away minutes')),
    ...['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'].map((day) => {
      const expose = exposes.composite(`${day}_schedule`, day);
      [1, 2, 3, 4, 5, 6, 7, 8, 9].forEach((i) => {
        const ex = exposes.composite(`setpoint_${i}`, `${i}`)
          ex.withFeature(exposes.numeric('temperature', ea.STATE_SET).withValueMin(0.5)
              .withValueMax(29.5).withValueStep(0.5).withUnit('°C').withDescription(`Temperature ${i}`));
          if (i < 9) {
            ex.withFeature(exposes.enum('hour', ea.STATE_SET,
                ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09',
                    '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
                    '20', '21', '22', '23', '24']).withDescription(`Hour TO for temp ${i}`));
            ex.withFeature(exposes.enum('minute', ea.STATE_SET, ['00', '15', '30', '45'])
                .withDescription(`Minute TO for temp ${i}`));
          }
          expose.withFeature(ex);
      });
      return expose;
    }),
  ],
};

module.exports = device;

```

However, as you can see, the "to-zigbee" part of the week schedule is not there. This is because the handling of composites seems broken or I am doing something very wrong, but I cannot get any value to be sent to this endpoint. When I call it from the UI shipping with Zigbee2mqtt, the sliders, dropdowns and radio buttons just don´t do anything. When using the channel zigbee2mqtt/thermostat/set/<weekday>-<number>-<temperature/hour/minute>, a value is sent to Zigbee2mqtt, but the log says there is "no converter" for that channel (although the same channel without /set delivers the numbers correctly). Can anyone help me with that part?

**Comment by TAKeanice** [comment]
I assume the same is true for away_schedule, which is also a composite

**Comment by IerwinDE** [comment]
I tried the essentials.js from TAKeanice as an external converter with the Zigbeee2Mqtt based Adapter in ioBroker.
The thermostat is detected but the only value I an able to set on the device is the mode (off/auto/heat).
The only values that is sucessfully received seems to be local_temperature and Im not even sure that one updates.

Is anyone else using the converter with ioBroker and can confirm if it works for them?

**Comment by TAKeanice** [comment]
I have tested with my essentials smart home thermostat. With the gui of Zigbee2Mqtt the converter works fine. Do you have logs which can tell me a little more about the problems?

The Lidl renaming trick works but there are missing values (i.e., warnings) and some other minor differences.

I will overhaul the converter anyway, as suggested above, and revisit if there are any problems or differences to my local version.

**Comment by Longlife4ever** [comment]
> I have tested with my essentials smart home thermostat. With the gui of Zigbee2Mqtt the converter works fine. Do you have logs which can tell me a little more about the problems?
> 
> The Lidl renaming trick works but there are missing values (i.e., warnings) and some other minor differences.
> 
> I will overhaul the converter anyway, as suggested above, and revisit if there are any problems or differences to my local version.

Hi TAKeanice,

is there a way to get this implementet in the Zigbee Adapter of iobroker? Thought it is based on the Zigbee2Mqtt.

**Comment by TAKeanice** [comment]
@Longlife4ever I think that is true, but I am using Zigbee2Mqtt in Openhab, so I don´t really know how IOBroker handles things. I just know that the converter should convert zigbee messages correctly to mqtt messages, and that the exposes definition of the adapter makes the UI that zigbee2mqtt shows work correctly. But as I said, I will look into it shortly.

**Comment by mucke1985** [comment]
> > I have tested with my essentials smart home thermostat. With the gui of Zigbee2Mqtt the converter works fine. Do you have logs which can tell me a little more about the problems?
> > The Lidl renaming trick works but there are missing values (i.e., warnings) and some other minor differences.
> > I will overhaul the converter anyway, as suggested above, and revisit if there are any problems or differences to my local version.
> 
> Hi TAKeanice,
> 
> is there a way to get this implementet in the Zigbee Adapter of iobroker? Thought it is based on the Zigbee2Mqtt.

Hello I have the same problem I opened a thread in the IoBroker forum

(German language)

https://forum.iobroker.net/topic/60098/zigbee2mqtt-converter-me16

**Comment by TAKeanice** [comment]
@mucke1985 I realized that the converter only works as external converter currently, because I didn't change all paths of the dependencies of the converter when I moved it. Could you try to take the essentials.js out of the devices folder, put it into the data folder of zigbee2mqtt and register it as external converter in the config file?

I will refactor and test the converter this weekend, afterwards you can retest it.

**Comment by mucke1985** [comment]
> 

I tested the converter file me167.js in several locations, it always ends up with the same result.

Unfortunately, I can't follow the instructions on the zigbee2mqtt page for inserting the converter because the file structure in connection with the IoBroker adapter is different.

Unfortunately, I don't have any idea where I could look for the problem because my JS knowledge is not sufficient to understand how the three components (zigbee2mqtt/Converter/IoBroker) work together

I have also read in another forum post that some data is only sent every 10 minutes, which should also be the case with the current temperature.

I'm not sure what the problem is, I have three options.

1, The converter works correctly but the data is not transferred correctly to the iobroker adapter

2, The converter works correctly but the incoming data such as the temperature is always overwritten with (null) because these are only sent every 10 minutes.

3, the converter does not work properly

**Comment by mucke1985** [comment]
> @Longlife4ever I think that is true, but I am using Zigbee2Mqtt in Openhab, so I don´t really know how IOBroker handles things. I just know that the converter should convert zigbee messages correctly to mqtt messages, and that the exposes definition of the adapter makes the UI that zigbee2mqtt shows work correctly. But as I said, I will look into it shortly.

**Comment by TAKeanice** [comment]
@mucke1985 I just realized that the thermostat you have and the converter you use for it is a different one than this issue talks about. Please open an issue for your converter after ruling out that there is some other problem with your setup.

**Comment by mucke1985** [comment]
> @mucke1985 I just realized that the thermostat you have and the converter you use for it is a different one than this issue talks about. Please open an issue for your converter after ruling out that there is some other problem with your setup.

oh sorry i completely overlooked that

**Comment by TAKeanice** [comment]
Another 30 days... But I am still on it. A bit difficult in Christmas time to find time.

**Comment by TAKeanice** [comment]
The integration is essentially ready (no pun intended). @Koenkk requested that I make the schedule a general function to use in other converters, that's why this is still open. Has anyone in this issue already tested the most current version on my fork of the converters project?

**Comment by pianojockl** [comment]
Yes, I've been using it for about a week with homeassistant. Everything seems to work - really the only thing is the difference in interface between the essentials thermostat and another one I have (https://www.zigbee2mqtt.io/devices/TS0601_thermostat_1.html).
I'm not using the heating schedule and instead letting homeassistant handle setting the desired temperatures - for the TS0601 that means setting "system_mode" to auto and "preset" to manual. For the essential thermostat however, I'm setting "system_mode" to manual and there's no "preset" option. Also, the TS0601 shows me its "position", i.e. how far its valve is opened.
If anything, it'd be nice to have a consistent behavior throughout different models...
In any case though: thank you so much for your work already!

**Comment by TAKeanice** [comment]
Thank you for the feedback! Happy to hear it's working for you. I may take a look at the valve position variable in the definition of your thermostat and if it exists in the essentials thermostat, too. There is just one variable to set the mode of operation on the essentials thermostat, but the definition I used as starting point distributed it to a "preset" and "mode" variable. I would not like to do that, because it creates strange dependencies between two seemingly independent settings.
