### ISSUE TITLE
Relay TS011F _TZ3000_7dndcnnb

### ISSUE THREAD

**Issue by amgstone** [Koenkk/zigbee2mqtt#14233]
### What happened?

after each update for a minute, current and power are reset to 0 and then immediately restore the value. i have 2 relay, one of them works like this.
![Огляд – Home Assistant - Google Chrome](https://user-images.githubusercontent.com/63303107/192818815-b65e5451-7b2a-4d82-9e24-bc46c7746c57.jpg)

### Zigbee2MQTT version

edge

### Adapter firmware version

edge

### Adapter

CC2538

**Comment by Malaysk** [comment]
_TZ3000_b28wrpvx
also this behavior. Sets to 0 every 2-3 minutes
![Screenshot_1](https://user-images.githubusercontent.com/22643931/192949846-36222d1f-3a6f-4859-8058-4439d276c7fe.png)

**Comment by amgstone** [comment]
energy count, but curwnt and powers are not updated

**Comment by zhvial** [comment]
I have the same problem.
Updated to the latest firmware and that didn't solve the problem.
![image](https://user-images.githubusercontent.com/60042073/204476628-88d5dcf2-b7f7-4b45-b0a4-947dbc870387.png)
Voltage drops occure the same time power drops to 0.
