### ISSUE TITLE
Firmware data not correct in UI

### ISSUE THREAD

**Issue by Scoff123** [Koenkk/zigbee2mqtt#14245]
### What happened?

I am seeing the incorrect firmware data reported for one of my Philips Hue bulbs in the Z2M UI. This is subsequent to using the OTA firmware feature in Z2M for this device. The old firmware version still shows in the UI.

I have tried force removing the device, restarting Z2M and adding the device fresh, but still the old incorrect firmware data shows in the UI once the device is successfully added.

This same issue was raised previously here: https://github.com/Koenkk/zigbee2mqtt/issues/9918

### What did you expect to happen?

I expected the new version and build data data to show in the Z2M UI. 

Conversely, I updated an identical Philips Hue bulb using the Philips Hue app on my smartphone, and the new firmware data shows correctly in Z2M. 

### How to reproduce it (minimal and precise)

Update firmware of Philips Hue Bulb using OTA firmware update process in Z2M.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

6.7.8.0 build 373

### Adapter

Sonoff ZBBridge

**Comment by Koenkk** [comment]
Probably the OTA update failed because this device requires OTA updates in 2 steps (first an older FW before the newer one). What Hue model is this?

**Comment by Scoff123** [comment]
The device is a Philips Hue white ambiance E27 1100lm with Bluetooth bulb,
LTA009
Zigbee Manufacturer
Signify Netherlands B.V.

There was only one firmware update available for the device, which was updating from 1.93.7 to 1.93.11 according to the Hue app.

Using the Hue app to carry the update out on one of my 2 identical bulbs worked correctly, and the updated firmware shows for that bulb in my Z2M UI.
Using the Z2M OTA upgrade on the second bulb appears to have been successful, as viewing this bulb in the Hue app now shows the newer updated firmware. 
Unfortunately Z2M is still showing the old firmware version, but this is incorrect and not what is actually installed on the device. Removing and rejoining the device to Z2M makes no difference, as if the old firmware version is somehow cached or the database entry for firmware version and build date are not getting overwritten correctly for this device following the OTA update.

**Comment by Koenkk** [comment]
Can you remove the device, restart z2m and repair the device?

**Comment by Scoff123** [comment]
Yes I've tried doing that but unfortunately it makes no difference and the older firmware version and firmware build date show in the Z2M UI oddly

**Comment by Koenkk** [comment]
What shows up when you read the values through the z2m frontend -> device -> dev console?

<img width="967" alt="Screenshot 2022-09-30 at 20 30 23" src="https://user-images.githubusercontent.com/2892853/193334276-79302505-7d65-45a9-b362-896613ac8dcd.png">

**Comment by Scoff123** [comment]
Interesting, that shows the correct build date and firmware version 

![Screenshot_20220930-194827_Home Assistant](https://user-images.githubusercontent.com/96984460/193337277-8d053a82-6d67-401d-9726-29e4ab3f5046.jpg)

Whereas on the main device info page it shows the old data

![Screenshot_20220930-194731_Home Assistant](https://user-images.githubusercontent.com/96984460/193337369-ee369443-5bb4-4105-85cf-01c66a642a6d.jpg)

**Comment by Koenkk** [comment]
It should show the correct info when restarting z2m now.

**Comment by Scoff123** [comment]
It does indeed - thank you :) 
![Screenshot_20220930_201436](https://user-images.githubusercontent.com/96984460/193341063-e9fc33be-d1b4-4cc9-bbf1-845635c1424c.jpg)

How does reading the attribute cause the update of data shown in the UI, and is there any way this can happen automatically without a manual read in future?

**Comment by Koenkk** [comment]
When you update the bulb through z2m, z2m should read these attributes after the fw update. It seems something went wrong there. Any chances you still have the debug log of that update?

**Comment by Scoff123** [comment]
No unfortunately not :( I'll just keep an eye the next time there is an update, and open an issue with the logs then, if it does the same. I'll close this one down now - thanks for your help.
