### ISSUE TITLE
[New device support]: Schneider Electric WDE002924

### ISSUE THREAD

**Issue by verydrunk** [Koenkk/zigbee2mqtt#14251]
### Link

https://www.se.com/ww/en/product/WDE002924/pushbutton-wiser-exxact-batterypowered-2gang-white/

### Database entry

{"id":46,"type":"EndDevice","ieeeAddr":"0x04cd15fffeb71163","nwkAddr":31939,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Battery","modelId":"FLS/SYSTEM-M/4","epList":[21,22,23,24],"endpoints":{"21":{"profId":260,"epId":21,"devId":260,"inClusterList":[0,1,3,32,65303],"outClusterList":[3,4,5,6,8,25,258],"clusters":{"genBasic":{"attributes":{"modelId":"FLS/SYSTEM-M/4","manufacturerName":"Schneider Electric","powerSource":3,"zclVersion":3,"appVersion":2,"stackVersion":6,"hwVersion":1,"dateCode":"","swBuildId":"002.005.030 R"}},"genPollCtrl":{"attributes":{"checkinInterval":86400}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"genOnOff":{"attributes":{}},"genOnOffSwitchCfg":{"attributes":{}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}},"22":{"profId":260,"epId":22,"devId":260,"inClusterList":[0,1,3,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b73a61","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}},"23":{"profId":260,"epId":23,"devId":260,"inClusterList":[0,1,3,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"24":{"profId":260,"epId":24,"devId":260,"inClusterList":[0,1,3,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"genOnOff":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":6,"hwVersion":1,"dateCode":"","swBuildId":"002.005.030 R","zclVersion":3,"interviewCompleted":true,"meta":{"configured":25281963},"lastSeen":1664469233676,"defaultSendRequestWhen":"active"}

### Comments

Schneider Electric WDE002906 (Wiser wireless switch 1-gang) needs an extension to WDE002924 - (Wiser, wireless switch 2-gang)
Help please

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['FLS/SYSTEM-M/4'],
    model: 'WDE002924',
    vendor: 'Schneider Electric',
    description: 'Wiser wireless switch 2-gang',
    fromZigbee: [fz.command_on, fz.command_off, fz.command_move, fz.command_stop, fz.battery],
    toZigbee: [],
    exposes: [e.action(['on_1', 'off_1', 'brightness_move_up_1', 'brightness_move_down_1', 'brightness_stop_1',
    'on_2', 'off_2', 'brightness_move_up_2', 'brightness_move_down_2', 'brightness_stop_2']),
    	e.battery()],
    meta: {disableActionGroup: true, multiEndpoint: true},
    // The configure method below is needed to make the device reports on/off state changes
    // when the device is controlled manually through the button on it.
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint1 = device.getEndpoint(21);
        await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl', 'genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint1);
        const endpoint2 = device.getEndpoint(22);
        await reporting.bind(endpoint2, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl', 'genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint2);
    },
};

module.exports = definition;
```

**Comment by treeman** [comment]
Just got this device, but I haven't even figured out how to get it to enter pairing mode. Anyone has any ideas?
