### ISSUE TITLE
Pairing xiaomi aqara motion RTCGQ11LM device unsupported

### ISSUE THREAD

**Issue by jlo88** [Koenkk/zigbee2mqtt#1426]
# Bug Report
## What happened
I'm trying to pair a xiaomi aqara RTCGQ11LM, in the zigbee2mqtt log I see device incoming and pairing but it reports as undefined. It also does not show up under integrations in home assistant. It does show up in devices.yaml:

```
'0x00158d0003665269':
  friendly_name: '0x00158d0003665269'
  retain: false
```

 and in the database: 

```
{"id":38,"type":"EndDevice","ieeeAddr":"0x00158d0003665269","nwkAddr":37537,"manufId":4151,"epList":[1],"status":"online","joinTime":1555232692,"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,1,3,1024,1030,1280,65535],"outClusterList":[0,25],"clusters":{}}},"_id":"ukotEDsNL7iZ8aKk"}
{"id":38,"type":"EndDevice","ieeeAddr":"0x00158d0003665269","nwkAddr":37537,"manufId":4151,"epList":[1],"status":"online","joinTime":1555232692,"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,1,3,1024,1030,1280,65535],"outClusterList":[0,25],"clusters":{"genBasic":{"dir":{"value":3},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"msIlluminanceMeasurement":{"dir":{"value":1},"attrs":{}},"msOccupancySensing":{"dir":{"value":1},"attrs":{}},"ssIasZone":{"dir":{"value":1},"attrs":{}},"manuSpecificCluster":{"dir":{"value":1},"attrs":{}}}}},"_id":"ukotEDsNL7iZ8aKk"}
```

Relevant lines from log: 
```
4/14/2019, 11:05:22 AM - info: Device incoming...
4/14/2019, 11:05:22 AM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
4/14/2019, 11:05:22 AM - warn: Device with modelID 'undefined' is not supported.
4/14/2019, 11:05:22 AM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
4/14/2019, 11:05:22 AM - debug: Received zigbee message of type 'devStatus' with data '"online"' of device 'undefined' (0x00158d0003665269) of endpoint 1
4/14/2019, 11:05:22 AM - warn: Device with modelID 'undefined' is not supported.
4/14/2019, 11:05:22 AM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
4/14/2019, 11:05:25 AM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genBasic","data":{"modelId":"lumi.sensor_motion.aq2"}}' of device 'undefined' (0x00158d0003665269) of endpoint 1
```
## What did you expect to happen
Pairing and showing up of the device in home assistant.

## How to reproduce it (minimal and precise)
Stop zigbee2mqtt
remove the device from devices.yaml and database.db 
start zigbee2mqtt
pair the device 

## Debug Info
zigbee2mqtt version: Edge 1.3.0
CC253X firmware version: 20190315

log: https://pastebin.com/zWWjiMVs

**Comment by Koenkk** [comment]
Should be fixed in the latest dev branch (please checkout latest edge in +- 2 hours). 

You should be easy to simply fix this by pressing the reset button on the device once.

**Comment by skjnldsv** [comment]
Similar to #1425 ?

**Comment by esas** [comment]
I can confirm that it now works..

**Comment by skjnldsv** [comment]
@esas any specific procedure you followed?

**Comment by esas** [comment]
Just used the latest-dev docker image and that worked. I couldn't find the changes on git though.

**Comment by skjnldsv** [comment]
@esas and clean install, long press, allow pairing , wait for the paired notification in log and that's it?

**Comment by esas** [comment]
Actually I kept the old config files. Didn't have to repair. The device was already in the configuration.yaml. It just worked as soon as the now container (tag: latest-dev) started. Before this I had the same problems as you described running ver. 1.3.0.

**Comment by jlo88** [comment]
I can also confirm that this is working now with 1.3.1. I paired a sensor yesterday without any problems.

**Comment by Koenkk** [comment]
Great, looks that this has been solved, feel free to comment in case you are still having problems.
