### ISSUE TITLE
[Feature request]: Add Power-on behavior for HEIMAN HS2WDS

### ISSUE THREAD

**Issue by olivr2s** [Koenkk/zigbee2mqtt#14287]
### Is your feature request related to a problem? Please describe

The HEIMAN HS2WDS bulb light support the `Power-on behavior`.
https://www.zigbee2mqtt.io/devices/HS2WDS.html#heiman-hs2wds

I tried with MQTT-explorer and it works perfectly.
Is it possible to add this parameter in the template.

### Describe the solution you'd like

Add `Power-on behavior`.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by olivr2s** [comment]
Do I have to provide other information to add the function?

**Comment by Koenkk** [comment]
Added this now! (for all lights supporting it).

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
