### ISSUE TITLE
Aqara QBKG12LM and QBKG11LM after return wrong power source (battery) fix still end device on network map

### ISSUE THREAD

**Issue by mikolka-lsh** [Koenkk/zigbee2mqtt#14280]
### What happened?

After solving issue #14253 in last update 1.28.0 - in network map -I still see this two switches not as a router but as end devices...
You could see it here on screenshot in left side:
![SmartSelect_20221001_151523_Chrome](https://user-images.githubusercontent.com/74327614/193440786-419bdf15-d0cc-425b-ab88-e5a4943e43c4.jpg)

### What did you expect to happen?

Wall switches must be a routers in network

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20210813

### Adapter

zStack3x0

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when pairing the device? I requested this in https://github.com/Koenkk/zigbee2mqtt/issues/14253#issuecomment-1264704617 but the herdsman debug log is not included.

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by mikolka-lsh** [comment]
[log.zip](https://github.com/Koenkk/zigbee2mqtt/files/9700635/log.zip)
Here it is.
What I done:

1. Add zigbee_herdsman_debug: true to HA addon
2. Restart addon
3. Delete guest.room-switch from Z2M UI
4. Add this device again
5. Open SSH and grub all logs from Z2M container

And now this switch still as a end device on map of my network...

**Comment by Koenkk** [comment]
Lets continue in https://github.com/Koenkk/zigbee2mqtt/issues/14253
