### ISSUE TITLE
[New device support]: Sunricher ZG2835RAC - zigbeeModel HK-SL-DIM-EU-A

### ISSUE THREAD

**Issue by snurre0** [Koenkk/zigbee2mqtt#14315]
### Link

https://www.sunricher.com/zigbee-rotary-manual-control-wall-mounted-ac-phase-cut-dimmer-sr-zg2835rac.html

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0x9035eafffeb43832","nwkAddr":26228,"manufId":4107,"manufName":"Sunricher","powerSource":"Mains (single phase)","modelId":"HK-SL-DIM-EU-A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2820,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":10,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":10,"activePower":72,"rmsVoltage":1540,"rmsCurrent":56}},"seMetering":{"attributes":{"multiplier":1,"divisor":3600000,"currentSummDelivered":[0,5894075]}},"genLevelCtrl":{"attributes":{"currentLevel":70}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff093715","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff093715","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff093715","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00212effff093715","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":1},{"cluster":2820,"attrId":1288,"minRepIntval":10,"maxRepIntval":3600,"repChange":10},{"cluster":2820,"attrId":1285,"minRepIntval":10,"maxRepIntval":3600,"repChange":1},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r54","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1861546705},"lastSeen":1664821509011,"defaultSendRequestWhen":"immediate"}

### Comments

Hi,
Since model number ZG2835RAC is already supported, but with a different zigbeeModel, I got this device to work by copying the converter for the existing ZG2835RAC.
I can make a simple PR for this, but I'm unsure of certain things and I don't know for sure if this is a 100% match or if something is off with this converter, so that's why I'm creating this issue first.

Can I just add another zigbeeModel to the same entry or need to make another section for this zigbeeModel. I could not find any information about that particular config option(but I probably don't know where to look).
This is the entry in sunricher.js that I'm unsure about, is this a comma separated list of supported zigbeeModels? The first one seems really generic, so that's what threw me off here:
`zigbeeModel: ['Micro Smart Dimmer', 'SM311', 'HK-SL-RDIM-A']`

Also, does the below converter config seem fine, or am I missing something important?
It seems to be working fine for me, both for lights on/off, dimming and all the power sensors.

### External converter

```shell
const definition = {
    zigbeeModel: ['HK-SL-DIM-EU-A'],
    model: 'ZG2835RAC',
    vendor: 'Sunricher',
    description: 'ZigBee knob smart dimmer',
    fromZigbee: extend.light_onoff_brightness().fromZigbee.concat([fz.electrical_measurement, fz.metering, fz.ignore_genOta]),
    toZigbee: extend.light_onoff_brightness().toZigbee,
    exposes: [e.light_brightness(), e.power(), e.voltage(), e.current(), e.energy()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const binds = ['genOnOff', 'genLevelCtrl', 'haElectricalMeasurement', 'seMetering'];
        await reporting.bind(endpoint, coordinatorEndpoint, binds);
        await reporting.onOff(endpoint);
        await reporting.brightness(endpoint);
        await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
        await reporting.activePower(endpoint);
        await reporting.rmsCurrent(endpoint, {min: 10, change: 10});
        await reporting.rmsVoltage(endpoint, {min: 10});
        await reporting.readMeteringMultiplierDivisor(endpoint);
        await reporting.currentSummDelivered(endpoint);
    },
};
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
