### ISSUE TITLE
[New device support]: Tuya Smart ZigBee 16A  from MatSee Plus

### ISSUE THREAD

**Issue by mpmguedes** [Koenkk/zigbee2mqtt#14329]
### Link

https://es.aliexpress.com/item/1005004128359494.html?spm=a2g0o.order_detail.0.0.62fd39d3LepjAr&gatewayAdapt=glo2esp

### Database entry

{"id":56,"type":"Router","ieeeAddr":"0xa4c138fcb1f391ec","nwkAddr":62343,"manufId":4417,"manufName":"_TZ3000_cjrngdr3","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"20480":1,"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"53264":0,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1664890271134,"defaultSendRequestWhen":"immediate"}

### Comments

I added it and it just pops up another switch and it says not supported. 

### External converter

```shell
I did not try.
```

**Comment by Koenkk** [comment]
`_TZ3000_cjrngdr3` is supported in z2m 1.28.0
