### ISSUE TITLE
Is rename feature broken?

### ISSUE THREAD

**Issue by EmmanuelLM** [Koenkk/zigbee2mqtt#1434]
Using version 1.3.0, when I try to rename an entity through mqtt with...

{"topic":"zigbee2mqtt/bridge/config/rename","payload":"{old: '0x00158d0002ede2ab', new: 'Utility light switch'}"}

...I get the following error:

  zigbee2mqtt:error 4/15/2019, 5:45:11 PM Invalid rename message format expected {old: 'friendly_name', new: 'new_name} got {old: '0x00158d0002ede2ab', new: 'Utility light switch'}

I'm probably missing something simple...

**Comment by BudBundi** [comment]
Maybe  the spaces. What happen when you use underscores?

**Comment by Koenkk** [comment]
Should be `{"old": '0x00158d0002ede2ab', "new": 'Utility light switch'}` (quotes are missing)

**Comment by tb-killa** [comment]
@Koenkk we should integrate something like slugify convert as it would do in web development to prevent strange results.
I prever this as it build standard naming. 
What do you think?

**Comment by Koenkk** [comment]
@tb-killa sounds good!

**Comment by EmmanuelLM** [comment]
> Should be `{"old": '0x00158d0002ede2ab', "new": 'Utility light switch'}` (quotes are missing)

Sadly, this is invalid JSON format in the MQTT publish service I am using under home-assistant.... (i.e. it seems quotes are not within the payload).

**Comment by tb-killa** [comment]
> @tb-killa sounds good!

@Koenkk maybe this would help ?
```
return string.toLowerCase()
  .replace(/[^\w\s-]/g, '') // remove non-word [a-z0-9_], non-whitespace, non-hyphen characters
  .replace(/[\s_-]+/g, '-') // swap any length of whitespace, underscore, hyphen characters with a single -
  .replace(/^-+|-+$/g, ''); // remove leading, trailing -
```

**Comment by ShonkyCH** [comment]
> > Should be `{"old": '0x00158d0002ede2ab', "new": 'Utility light switch'}` (quotes are missing)
> 
> Sadly, this is invalid JSON format in the MQTT publish service I am using under home-assistant.... (i.e. it seems quotes are not allowed within the payload).

Escape them seems to work:
{
"topic":"zigbee2mqtt/bridge/config/rename",
"payload":"{\"old\": \"0x00158d0002ede2ab\", \"new\": \"Utility light switch\"}"
}

**Comment by Koenkk** [comment]
@tb-killa yes, can you make a PR and introduce extra tests for this?

**Comment by tb-killa** [comment]
@Koenkk yes

**Comment by OmgImAlexis** [comment]
Any chance this could be reopened? I can't rename my devices as I just get an error and I'm guessing this is what's causing it as I'm using this with Home Assistant.

**Comment by Koenkk** [comment]
@OmgImAlexis please provide the debug logging of this.

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
