### ISSUE TITLE
[Feature request]: Device status available as Home Assistant entity

### ISSUE THREAD

**Issue by FabioEight** [Koenkk/zigbee2mqtt#14343]
### Is your feature request related to a problem? Please describe

I'm looking for a way to monitor the status of my >25 zigbee devices. Sometimes, they go offline and I notice that only days later.

### Describe the solution you'd like

Since the Z2M dashboard shows the online/offline status of the devices, is it possible to expose the devices status as entity on HA?

### Describe alternatives you've considered

For the time being, I monitor the last change of values and notify myself in case of no updates during the last >24 hours. This method works for temperature sensors only. For PIR devices, I would have to introduce the check if I'm home or not.

### Additional context

None

**Comment by Koenkk** [comment]
You can use any entity of the device in HA, the will be marked as unavailable whenever the device is offline.
