### ISSUE TITLE
Problem Xiaomi ZNCZ04LM

### ISSUE THREAD

**Issue by satelitman** [Koenkk/zigbee2mqtt#14378]
### What happened?

Hello - I am asking for your help. I have 24 sockets in my house - Xiaomi ZNCZ04LM. These sockets were in the list of supported devices - ((switch (state), power, energy, device_temperature, voltage, current, consumer_connected, led_disabled_night, power_outage_memory, auto_off, overload_protection, linkquality)). On this basis, I decided to buy them. I gradually bought 24 pieces and gradually placed them in my house. Everything worked perfectly. I can control the outlet (on/off) - I used information about consumption, current total, etc. I try to keep my consumption under control. This information is very important to me. After updating the sockets, all 24 sockets stopped displaying important information - hardly any data is displayed. Please, can we help you somehow. Thank you in advance for any answer and help. I'm sorry for my english.

### Zigbee2MQTT version

1.28.0-1 

### Adapter firmware version

01-23-2022

### Adapter

Xiaomi - ZNCZ04LM

### Debug log

info  2022-09-28 11:44:36: Logging to console and directory: '/config/zigbee2mqtt/log/2022-09-28.11-44-36' filename: log.txt
info  2022-09-28 11:44:36: Starting Zigbee2MQTT version 1.27.2-dev (commit #1e24734)
info  2022-09-28 11:44:36: Starting zigbee-herdsman (0.14.55)
info  2022-09-28 11:44:36: zigbee-herdsman started (resumed)
info  2022-09-28 11:44:36: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210319,"transportrev":2},"type":"zStack3x0"}'
info  2022-09-28 11:44:36: Set transmit power to '20'
info  2022-09-28 11:44:36: Currently 72 devices are joined:
info  2022-09-28 11:44:36: zasuvka Veľká chodba (0x04cf8cdf3c7e3cd7): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Spálňa za posteľou (0x04cf8cdf3c8e442e): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Spálňa DECO-GOOGLE MAX (0x04cf8cdf3c8e416a): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Spálňa televízor LG (0x04cf8cdf3c8e2f49): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka spalna satelit (0x04cf8cdf3c8e4379): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Technická miestnosť KOTOL (0x04cf8cdf3c8a2bf8): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Technická miestnosť MRAZNIČKA (0x04cf8cdf3c8a2966): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Technická miestnosť PRÁČKA (0x04cf8cdf3c8a2b7c): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Technická miestnosť SERVER (0x04cf8cdf3c8a2dd0): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: vlhkost Kúpeľňa rodičia (0x00158d000587c866): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Kúpeľňa rodičia (0x00158d0006c51200): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Kupelna rodičia (0x00158d0003c7a3b8): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Spálňa šatník (0x00158d0003c7a3ca): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Spálňa komoda smer kúpeľňa (0x00158d00068a00e5): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Spálňa posteľ (0x00158d0006a3d0d9): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Vstup do domu (0x00158d00068a1e81): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Vstupná chodba (0x00158d00067cf6b3): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Mala prechodova chodbicka do garáže (0x00158d00068a048a): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Vstup do garaze mala chodba (0x00158d0003981f17): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: Garáž ĽAVÁ otvorené (0x00158d0007e4c770): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: Garáž PRAVÁ otvorená (0x00158d0007ed12e3): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: Garáž PRAVÁ zatvorené (0x00158d0007ef9926): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: Garáž ĽAVÁ zatvorené (0x00158d0007e61f86): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: zasuvka Kuchyna KaVOVAR (0x04cf8cdf3c759783): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Kuchyna GOOGLE-ROBOT (0x04cf8cdf3c8a2d1f): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: Kuchyňa chodba 02 (0x00158d00024f5467): 07004D/07005L - Immax Neo SMART LED E27/E14 color, dimmable, Zigbee 3.0 (Router)
info  2022-09-28 11:44:36: Kuchyňa chodba 01 (0x00158d00024f4c14): 07004D/07005L - Immax Neo SMART LED E27/E14 color, dimmable, Zigbee 3.0 (Router)
info  2022-09-28 11:44:36: zasuvka Obývačka PC SERVER (0x04cf8cdf3c8a319a): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Obyvacka HIFI CLASSE (0x04cf8cdf3c8a30ba): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Obývačka TV LG (0x04cf8cdf3c8a36cb): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Kancelaria PC (0x04cf8cdf3c7598ca): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka kancelaria siet (0x04cf8cdf3c867bcb): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka chlapci led (0x04cf8cdf3c76414f): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka chlapci jakub pc (0x04cf8cdf3c7c11b4): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Detská izba ANNA LED PÁSIK (0x04cf8cdf3c763a71): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Detska izba ANNA PC (0x04cf8cdf3c8a2f31): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: Obývačka RGB HIFI (0x00158d00024f57c0): 07004D/07005L - Immax Neo SMART LED E27/E14 color, dimmable, Zigbee 3.0 (Router)
info  2022-09-28 11:44:36: Obývačka RGB knižnica (0x00158d00024f530c): 07004D/07005L - Immax Neo SMART LED E27/E14 color, dimmable, Zigbee 3.0 (Router)
info  2022-09-28 11:44:36: zasuvka obyvacka satelit (0x04cf8cdf3c8e3196): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka Obývačka video (0x04cf8cdf3c8a38ce): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: zasuvka obyvacka netatmo ir (0x04cf8cdf3c8e2a9d): ZNCZ04LM - Xiaomi Mi power plug ZigBee EU (Router)
info  2022-09-28 11:44:36: dvere Kuchyna spajza (0x00158d00067cf5b2): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: lux Hlavný (0x54ef4410000c20dd): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Kuchyna linka chladnicka (0x00158d0006b22941): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Kuchyna skrinka nad stolom (0x00158d0006a2629d): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Obyvacka knižnica (0x00158d0006beb761): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Obyvacka vychod na zahradu (0x00158d0003981f1a): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere obyvacka suflik tv (0x00158d0007ec8f9e): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Obývačka suflik HIFI 01 (0x00158d0007ef4c00): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Obývačka suflik HIFI 02 (0x00158d0007ef4ca7): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Kúpeľňa detí (0x00158d0003981fd8): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: vlhkost Kúpeľňa deti (0x00158d000587c822): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Kúpeľňa deti sprcha (0x00158d0006beb7ee): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Kúpeľňa deti umývadlo (0x00158d0006ca3fb1): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Malý záchod (0x00158d00067cf6f0): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb chodba velka zo spalne (0x00158d0006a2432b): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb chodba velka 01 preklad (0x00158d00068a1258): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Chodba veľká 02 od kuchyne (0x00158d0006b79d74): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: dvere Technická miestnosť (0x00158d00067cf778): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Chodba k izbám zachodik (0x00158d000689da95): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Chodba k izbám kuchyna (0x00158d00068a220a): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: pohyb Chodba k izbam 01 (0x00158d0006b79e36): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
info  2022-09-28 11:44:36: IKEA obývačka stôl (0xbc33acfffe8f7124): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
info  2022-09-28 11:44:36: IKEA kuchyňa linka (0xbc33acfffed4503f): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
info  2022-09-28 11:44:36: IKEA chodba skriňa (0x60a423fffececeb4): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
info  2022-09-28 11:44:36: IKEA spálňa JANETTE (0x804b50fffeef7a11): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
info  2022-09-28 11:44:36: IKEA spálňa MILAN (0x84fd27fffe025174): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
info  2022-09-28 11:44:36: IKEA ofiice (0x84fd27fffe025188): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
info  2022-09-28 11:44:36: ikea jedalen (0x804b50fffeef9028): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
info  2022-09-28 11:44:36: svetlo zahrada markiza (0x00178801099f4ec6): 9290023349 - Philips Hue white A67 bulb E26 with Bluetooth (1600 Lumen) (Router)
info  2022-09-28 11:44:36: Kocka ANNA (0x00158d00051dff04): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
info  2022-09-28 11:44:36: Kocka CHLAPCI (0x00158d0005291e8a): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
info  2022-09-28 11:44:36: Zigbee: disabling joining new devices.
info  2022-09-28 11:44:37: Connecting to MQTT server at mqtt://core-mosquitto
error 2022-09-28 11:44:37: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:37: MQTT failed to connect, exiting...
info  2022-09-28 11:44:37: Stopping zigbee-herdsman...
error 2022-09-28 11:44:38: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:39: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:40: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:41: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:42: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:43: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:44: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:45: MQTT error: Connection refused: Not authorized
error 2022-09-28 11:44:46: MQTT error: Connection refused: Not authorized
info  2022-09-28 11:44:46: Stopped zigbee-herdsman

**Comment by satelitman** [comment]
<img width="1627" alt="Snímka obrazovky 2022-10-08 o 21 01 59" src="https://user-images.githubusercontent.com/15339892/194723459-dbc038da-cc91-4a6c-ab29-f4527298b8cc.png">
<img width="821" alt="Snímka obrazovky 2022-10-08 o 21 02 05" src="https://user-images.githubusercontent.com/15339892/194723461-c73025f0-8bfe-4f22-bdcf-46a100cf67d1.png">

**Comment by satelitman** [comment]
Please, is it possible to downgrade the ZNCZ04LM socket.
I found an alternative, but I don't know if it's feasible.
I lost information on 24 outlets that were important to me.
Thank you for any help and support - I sent and will definitely send for coffee (Satelitman)
<img width="1642" alt="Snímka obrazovky 2022-10-08 o 21 08 04" src="https://user-images.githubusercontent.com/15339892/194723656-c77af117-5535-4666-a31d-609c1199ef44.png">
<img width="934" alt="Snímka obrazovky 2022-10-08 o 21 05 12" src="https://user-images.githubusercontent.com/15339892/194723667-82c508f2-fa03-4b10-bd93-853ea19d825a.png">

**Comment by Whippie72** [comment]
I'm having the same issue. I did the update (01-23-2022) to 3 Xiaomi ZNCZ04LM plugs. 2 of them are working pretty well after the update. But one plug does not deliver any values. I only can switch it on/off.

{
    "linkquality": 48,
    "state": "ON",
    "update": {
        "state": "idle"
    }
}

**Comment by Koenkk** [comment]
@satelitman you need to update your coordinator to the latest firmware and repair the device, that should solve the issue

**Comment by satelitman** [comment]
Thank you very much for your help and guidance - is there any way to upgrade the coordinator??? thank you very much I have a chance thank you thank you

**Comment by Koenkk** [comment]
Instructions and firmware for each adapter can be found on this page: https://www.zigbee2mqtt.io/guide/adapters/#recommended

**Comment by satelitman** [comment]
it works, thank you very much
<img width="948" alt="Snímka obrazovky 2022-10-09 o 19 58 55" src="https://user-images.githubusercontent.com/15339892/194772309-4998556c-ba7a-427c-b85f-9f157e8fbbf2.png">

**Comment by satelitman** [comment]
thank you very much

**Comment by satelitman** [comment]
thank you very much

**Comment by Koenkk** [comment]
Great! 🥳
