### ISSUE TITLE
Aqara Smoke Detector JY-GZ-01AQ

### ISSUE THREAD

**Issue by elmasryahmed** [Koenkk/zigbee2mqtt#14399]
### What happened?

Linkage alarm is not working, as well temperature value is stuck att 25 Celsius.

### What did you expect to happen?

when a smoke alarm got triggered, alarm siren should start on other linked smoke detectors

### Zigbee2MQTT version

1.25.1

### Adapter firmware version

20220219

### Adapter

SONOFF usb 3.0

**Comment by Danit2** [comment]
Please update to the current version.

**Comment by elmasryahmed** [comment]
@Danit2 thanks for your reply, updated to the current version as well checked #13548, but can’t figure out how to trigger the alarm if smoke is detected within other sensor.

**Comment by elmasryahmed** [comment]
Thanks @Danit2, I'm using HomeKit via Homebridge, unfortunately can't find a way to achieve it, i guess will have to wait for a future update.

**Comment by ciB89** [comment]
I have created a blueprint in home assistant to achieve this functionality:

https://community.home-assistant.io/t/aqara-smoke-detector-linkage-alarm/517656
