### ISSUE TITLE
Add channel 26 compatibility to supported devices?

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#1439]
Hi All,

I have just switched to channel 26 and repaired all my devices (Xiaomi and Philips Hue).  All work on channel 26.  I read somewhere that not ALL zigbee devices will work on channel 26 (Are they hard coded?)

Is it worth adding this information somewhere in the supported devices documentation, I dont mind starting it but not sure if its worth the effort and dont want to clutter the documentation if its not going to provide real value.

**Comment by Koenkk** [comment]
I haven't seen any devices yet that don't work on channel 26

**Comment by kiwinol** [comment]
Thanks Koen, coming from you it doesn't sound like it's required :)
