### ISSUE TITLE
TuYa TM001-ZA/TM081, NOT RECOGNIZED DP

### ISSUE THREAD

**Issue by salvq** [Koenkk/zigbee2mqtt#14394]
### What happened?

I a having physically & visually 10 same window / door sensors. 4pcs are detected as TuYa TS0203 and 6pcs as TuYa TM001-ZA/TM081.

All of them works just fine (contact result or battery), TS0203 provides more data such as battery_low, tamper or voltage.

The issue is I am getting an warning messages (repeatelly and often) in Z2M for all of the TuYa TM001-ZA/TM081
`Warning 2022-10-07 18:47:01zigbee-herdsman-converters:TM081: NOT RECOGNIZED DP #101 with data {"dp":101,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,41]}}
`

### What did you expect to happen?

No warning messages

### How to reproduce it (minimal and precise)

Warning messages appears on all 6 same type sensors (TuYa TM001-ZA/TM081) even after several reset of the sensors or force remove and pairing again.

### Zigbee2MQTT version

1.27.2 commit: 7dc48fb

### Adapter firmware version

20211217

### Adapter

SMARTLIGHT CC2652P Zigbee USB Adapter SLZB-02

### Debug log

**Detected sensor, but visually looks different, looks like TuYa TS0203**
![image](https://user-images.githubusercontent.com/43242348/194611967-d9c38a93-7a2f-4f57-acf4-a8c4db1ecb3e.png)

**Debug log**
```
Debug 2022-10-07 18:46:54Received Zigbee message from '0xa4c138054200c570', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":1}],"seq":22528}' from endpoint 1 with groupID 0
Info 2022-10-07 18:46:54MQTT publish: topic 'zigbee2mqtt/0xa4c138054200c570', payload '{"battery":100,"contact":false,"linkquality":0}'
Debug 2022-10-07 18:46:57Received Zigbee message from '0xa4c138054200c570', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,38],"type":"Buffer"},"datatype":2,"dp":101}],"seq":22784}' from endpoint 1 with groupID 0
Warning 2022-10-07 18:46:57zigbee-herdsman-converters:TM081: NOT RECOGNIZED DP #101 with data {"dp":101,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,38]}}
Debug 2022-10-07 18:46:58Received Zigbee message from '0xa4c138054200c570', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":1}],"seq":23040}' from endpoint 1 with groupID 0
Info 2022-10-07 18:46:58MQTT publish: topic 'zigbee2mqtt/0xa4c138054200c570', payload '{"battery":100,"contact":true,"linkquality":58}'
Debug 2022-10-07 18:47:01Received Zigbee message from '0xa4c138054200c570', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,41],"type":"Buffer"},"datatype":2,"dp":101}],"seq":23296}' from endpoint 1 with groupID 0
Warning 2022-10-07 18:47:01zigbee-herdsman-converters:TM081: NOT RECOGNIZED DP #101 with data {"dp":101,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,41]}}
Debug 2022-10-07 18:47:03Received Zigbee message from '0xa4c138054200c570', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":1}],"seq":23552}' from endpoint 1 with groupID 0
Info 2022-10-07 18:47:03MQTT publish: topic 'zigbee2mqtt/0xa4c138054200c570', payload '{"battery":100,"contact":true,"linkquality":69}'
```

**Comment by Koenkk** [comment]
To figure out what these dps mean, please check: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#requirements-and-caveats
