### ISSUE TITLE
[New device support]: Add Keen Vent SV02-412-MP-1.2 to SV02

### ISSUE THREAD

**Issue by mrrobotnic** [Koenkk/zigbee2mqtt#14409]
### Link

https://keenhome.io/products/smart-vent

### Database entry

{"id":15,"type":"EndDevice","ieeeAddr":"0x000b57fffe955eda","nwkAddr":52912,"manufId":4443,"manufName":"Keen Home Inc","powerSource":"Battery","modelId":"SV02-412-MP-1.2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":3,"inClusterList":[0,1,3,4,5,6,8,32,1026,1027,2821,64513,64514],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":240}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c7b325","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":33,"stackVersion":81,"dateCode":"20180208R100214","swBuildId":"2.1.9","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1665263016206,"defaultSendRequestWhen":"fastpoll"}

### Comments

Keen vent model that is not falling under the generic SV02 list of supported devices"

"SV02-412-MP-1.2"

Currently using HA Add-on version 1.28.0-1

Thanks for the help!

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
