### ISSUE TITLE
friendly_names in topicnames instead of DEVICE_ID

### ISSUE THREAD

**Issue by nibi79** [Koenkk/zigbee2mqtt#1440]
hi,

I've updated my installation to version 1.3.0. I don't know if this behavior was in 1.2.0 too, because I don't use friendly_names before.

When I configure friendly_names zigbee2mqtt publishes all messages to:
`zigbee2mqtt/[friendly_name]`
instead of:
`zigbee2mqtt/[DEVICE_ID]`
 
Is that correct ?
Perhaps I only misunderstood the documentation:

![2019-04-17_144813](https://user-images.githubusercontent.com/20107317/56288870-f55e7700-611f-11e9-907b-5c8d58d1e367.png)

so DEVICE_ID = friendly_name?

**Comment by Koenkk** [comment]
Can you provide your zigbee2mqtt startup log?

**Comment by nibi79** [comment]
sorry their were some retained messages which results in some strange behaviour. 
I edited my post a second ago.

**Comment by Koenkk** [comment]
Yes, device id is the `friendly_name` from `configuration.yaml`.

**Comment by nibi79** [comment]
Thank you for the clarification!
