### ISSUE TITLE
[Feature Request] Led control CC253X

### ISSUE THREAD

**Issue by emouawad** [Koenkk/zigbee2mqtt#1442]
[Feature Request]

Ability to control Led on CC253X via mqtt just like any other configurable value (like permit_join), this way it can be controlled by any other logic dynamically.

**Comment by emouawad** [comment]
I believe this hasn't been implemented yet?
Please let me know if it is not clear.

**Comment by ciotlosm** [comment]
This would be really cool, to allow automation to flash the LED when in pairing mode for example.

**Comment by Koenkk** [comment]
@ciotlosm good idea!

**Comment by emouawad** [comment]
@Koenkk ?
