### ISSUE TITLE
Namron 4512737/4512738 - dry mode missing

### ISSUE THREAD

**Issue by ctvedt** [Koenkk/zigbee2mqtt#14427]
### What happened?

Dry mode is missing for Namron 4512737/4512738. From dev console it is possible to activate it, but mode is not exposed to  GUI (or Home Assistant).

### What did you expect to happen?

Be able to activate dry mode from GUI (or Home Assistant)

### How to reproduce it (minimal and precise)

Open dev console, set systemMode to 8 for cluster hvacThermostat.

![image](https://user-images.githubusercontent.com/19466426/194915239-f3f530d7-8094-4de2-9689-de5fa451c714.png)

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20210708

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by owangen** [comment]
@ctvedt I have this issue on my radar now and will implement support for it when time permits.

**Comment by owangen** [comment]
This is fixed with mentioned PR and this issue should be closed.

**Comment by ctvedt** [comment]
Thanks!
