### ISSUE TITLE
ZNCLDJ11LM	Xiaomi Aqara curtain motor not described in statesMapping.

### ISSUE THREAD

**Issue by MerleHH** [Koenkk/zigbee2mqtt#1443]
I have:
ZNCLDJ11LM	Xiaomi Aqara curtain motor
It is in the list supported devices
https://www.zigbee2mqtt.io/information/supported_devices.html

I try to pair it with adapter 0.10.3
It paired, but as unknown (?)
The log:

zigbee.0	2019-04-17 16:02:00.656	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 16:02:00.254	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 16:01:59.315	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 16:01:59.251	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:59:02.586	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:55:37.665	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:55:35.593	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:55:35.583	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:52:43.569	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:46:47.743	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:46:47.712	error	Device 00158d0002ec2804 "lumi.curtain" not described in statesMapping.
zigbee.0	2019-04-17 15:46:38.154	info	Successfully configured 0x84182600000ebe0d Plug 01
zigbee.0	2019-04-17 15:46:37.283	info	new dev 0x84182600000ebe0d 41456 Plug 01
zigbee.0	2019-04-17 15:46:33.582	info	new dev 0x0017880100c0644c 17180 LLC010
zigbee.0	2019-04-17 15:45:30.422	info	Successfully configured 0x84182600000ebe0d Plug 01
zigbee.0	2019-04-17 15:44:59.037	info	13 (0x84182600000ebe0d): AB3257001NJ - OSRAM Smart+ plug (Router)
zigbee.0	2019-04-17 15:44:59.026	info	12 (0x00158d0002ec2804): ZNCLDJ11LM - Xiaomi Aqara curtain motor (Router)
zigbee.0	2019-04-17 15:44:59.026	info	11 (0x00158d0001e13679): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.025	info	10 (0x00158d0002ebe5d2): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.025	info	9 (0x00158d0002a63f48): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.025	info	8 (0x00158d0002ebe556): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.024	info	7 (0x00158d0001dc8c97): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.024	info	6 (0x0017880100c0644c): 7199960PH - Philips Hue Iris (Router)
zigbee.0	2019-04-17 15:44:59.023	info	5 (0x00158d00027ce1a4): MFKZQ01LM - Xiaomi Mi/Aqara smart home cube (EndDevice)
zigbee.0	2019-04-17 15:44:59.018	info	4 (0x00158d0001e1a5c4): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.017	info	3 (0x00158d00029133c3): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.014	info	2 (0x00158d0001e1a5af): MCCGQ01LM - Xiaomi MiJia door & window contact sensor (EndDevice)
zigbee.0	2019-04-17 15:44:59.010	info	1 (0x00158d0002b94f0c): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
zigbee.0	2019-04-17 15:44:58.719	info	zigbee-shepherd ready. version: 2.6.3 rev 20181122
zigbee.0	2019-04-17 15:44:58.667	info	zigbee-shepherd started
zigbee.0	2019-04-17 15:44:52.661	info	Starting zigbee-shepherd

I have tried several times, even with only a minimal distance to the CC2530
What can I do? Tyia

**Comment by Koenkk** [comment]
As you are using iobroker, please create this issue here https://github.com/ioBroker/ioBroker.zigbee/issues
