### ISSUE TITLE
[New device support]: 929003054601 philips hue ceiling not recognized

### ISSUE THREAD

**Issue by cynfi** [Koenkk/zigbee2mqtt#14430]
### Link

https://www.philips-hue.com/en-hk/p/hue-white-ambiance-fair-ceiling-light/8719514341272#specifications

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0x001788010bef1cb0","nwkAddr":59316,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003054601","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20220502","swBuildId":"1.93.11","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1665430095840,"defaultSendRequestWhen":"immediate"}p

### Comments

![image](https://user-images.githubusercontent.com/115337689/194939446-7bf79943-01a3-47f8-8ea6-8a971b0a3209.png)

Hue light unsupported. It should be zigbee compatible

### Supported color modes

white

**Comment by danieledwardgeorgehitchcock** [comment]
I'll add this. You should be able to get the response from the color temperature range query though..?
