### ISSUE TITLE
Hue Smart Plug shows up in HA as Switch instead of light

### ISSUE THREAD

**Issue by kapitein187** [Koenkk/zigbee2mqtt#14447]
### What happened?

As far as I understood the Hue Smart Plugs always showed up as lights in the Hue App. Now via Z2M it is only useable as a Switch instead of a light. This makes things a bit more cumbersome. 

### What did you expect to happen?

Expect to have the Hue smart plug show up as light, similar as via Hue bridge 

### Zigbee2MQTT version

1.28.0-1

### Adapter firmware version

20210708

### Adapter

SONOFF ZigBee 3.0 USB Dongle Plus

**Comment by Koenkk** [comment]
It is a switch and thus should be exposed as a switch.

If you want to expose this as a light to Home Assistant see: https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light

**Comment by kapitein187** [comment]
Dank je wel.
Komt dit uiteindelijk ook naar de GUI?


Op wo 12 okt. 2022 om 16:13 schreef Koen Kanters ***@***.***>:

**Comment by Koenkk** [comment]
Only the HA ui, I don't see why you want to see it as a switch in the Z2M ui.

**Comment by kapitein187** [comment]
Hmm. I am indeed looking looking for it in HA, but cant find it. Can you
point me in the right direction?

Op wo 12 okt. 2022 om 21:13 schreef Koen Kanters ***@***.***>
