### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by OgnevOA** [Koenkk/zigbee2mqtt#14451]
### What happened?

Unable to start Z2M on home assistant on orange pi 4 lts

### Zigbee2MQTT version

1.28.0-1

### Adapter firmware version

?

### Adapter

sonoff Zigbee 3.0 USB dongle plus

### Debug log

[10:28:19] INFO: Preparing to start...
[10:28:20] INFO: Socat not enabled
[10:28:21] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-10-12 10:28:25: Logging to console and directory: '/config/zigbee2mqtt/log/2022-10-12.10-28-25' filename: log.txt
Zigbee2MQTT:info  2022-10-12 10:28:25: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-12 10:28:25: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:error 2022-10-12 10:28:26: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-12 10:28:26: Failed to start zigbee
Zigbee2MQTT:error 2022-10-12 10:28:26: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-12 10:28:26: Exiting...
Zigbee2MQTT:error 2022-10-12 10:28:26: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by sereneking** [comment]
I also have this same issue as well.

`[20:07:47] INFO: Preparing to start...
[20:07:48] INFO: Socat not enabled
[20:07:50] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-11-03 20:07:55: Logging to console and directory: '/config/zigbee2mqtt/log/2022-11-03.20-07-55' filename: log.txt
Zigbee2MQTT:info  2022-11-03 20:07:55: Starting Zigbee2MQTT version 1.28.1 (commit #unknown)
Zigbee2MQTT:info  2022-11-03 20:07:55: Starting zigbee-herdsman (0.14.68)
Zigbee2MQTT:error 2022-11-03 20:07:55: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-11-03 20:07:55: Failed to start zigbee
Zigbee2MQTT:error 2022-11-03 20:07:55: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-11-03 20:07:55: Exiting...
Zigbee2MQTT:error 2022-11-03 20:07:55: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`
