### ISSUE TITLE
Aurora AU-A1ZBPIAB  Plug-in Socket not reporting all values

### ISSUE THREAD

**Issue by dizzi77** [Koenkk/zigbee2mqtt#14456]
### What happened?

This Socket is only reporting Switch-State, Power and LQI. 

'Zigbee Model' reports as 'SingleSocket50AU'

### What did you expect to happen?

I expected that Current and Voltage would also be reported - only reports 'NULL'

I had expected 'Zigbee Model' to be - 'SingleSocket51AU' - Blakadder's Repository

### How to reproduce it (minimal and precise)

Inspecting the Herdsman convertor the older AU-A1ZBPIA version references Zigbee Model 'SingleSocket51AU', not SingleSocket50AU as I would have expected. Similarly the newer AU-A1ZBPIAB version references Zigbee Model 'SingleSocket50AU'. 

It looks although these Sockets have their Versions transposed

### Zigbee2MQTT version

1.28.0-1

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle PLUS -P

**Comment by jimmer74** [comment]
Hi, hate to me-too, but I've got a bunch of these and they all report power usage fine and can be turned on and off just fine, but no current or voltage measurements (frontend just reports "Null" as their values).

![Screenshot 2023-06-21 at 06 49 14](https://github.com/Koenkk/zigbee2mqtt/assets/1271067/08f190c2-6046-484a-9082-780196612387)

![Screenshot 2023-06-21 at 06 43 00](https://github.com/Koenkk/zigbee2mqtt/assets/1271067/4fb1f79f-be7b-4cb7-a4cb-d651050db4bf)

Is there anything I can try to change/tweak in the settings? Appreciate any help/pointers you can provide!

**Comment by jimmer74** [comment]
Just to add, on blakadder: it says it exposes power measurement & on/off, and has the correct image:
 
![Screenshot 2023-06-21 at 08 34 03](https://github.com/Koenkk/zigbee2mqtt/assets/1271067/0e08d5aa-c311-4807-aef6-cb63d6b90ff2)

However on the zigbee2mqtt info page it says it exposes on/off, power, voltage, current, linkquality, but the image is of the prior model (AU-A1ZBPIA - without the B):

![Screenshot 2023-06-21 at 08 34 30](https://github.com/Koenkk/zigbee2mqtt/assets/1271067/1bd16de7-a333-412b-b09e-9a87a70c0964)

Have tried transposing the models in ./zigbee-herdsman-converters/devices/aurora_lighting.js, but this effectively does nothing. What's the next thing I can try (or does this model not have voltage/current caps)?
