### ISSUE TITLE
Eglo Crosslink-Z not recognized correctly

### ISSUE THREAD

**Issue by deliwyn** [Koenkk/zigbee2mqtt#14483]
### What happened?

As per https://www.zigbee2mqtt.io/devices/33955.html my Eglo Crosslink-Z device should be recognized, but it's not, it appears as "Unsupported" as illustrated below.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/64557996/195879152-68ab3e82-591e-4fe7-b625-9a17b8ff5b10.png">

Here is what I can see in the database.db

`
{"id":56,"type":"Router","ieeeAddr":"0xa4c1388f445a652c","nwkAddr":55079,"manufId":4417,"manufName":"AwoX","powerSource":"Mains (single phase)","modelId":"EGLO_ZM_TW","epList":[1,242,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599,10],"outClusterList":[6],"clusters":{"genBasic":{"attributes":{"modelId":"EGLO_ZM_TW","manufacturerName":"AwoX","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":1,"hwVersion":60,"swBuildId":"2.3.12_250"}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":4751,"epId":3,"devId":268,"inClusterList":[65360,65361,4],"outClusterList":[65360,65361],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":60,"swBuildId":"2.3.12_250","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1665758996082,"defaultSendRequestWhen":"immediate"}`

What can I do? Thank you.

### What did you expect to happen?

I expected that my device would be recognized :)

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

2022-10-14 17:00:04Received message from unsupported device with Zigbee model 'EGLO_ZM_TW' and manufacturer name 'AwoX'
2022-10-14 17:00:04Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
The one with `EGLO_ZM_TW` was not supported yet, added it now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
