### ISSUE TITLE
Device "Led Trading 9133" wrongly discoverd as "Led Trading 9125"

### ISSUE THREAD

**Issue by lozwei** [Koenkk/zigbee2mqtt#14484]
### What happened?

When I pair the device [Led Trading 9133](https://www.zigbee2mqtt.io/devices/9133.html) an error message "LED Trading 9125: missing command '224'" appears and the device is added as "Led Trading 9125". It's working but with the wrong button actions.

### What did you expect to happen?

The device will be added as "Led Trading 9133"

### How to reproduce it (minimal and precise)

Go into pairing mode on the device and in z2m. The device will be added as the wrong device.

### Zigbee2MQTT version

1.26.0-dev commit: 7f28c55

### Adapter firmware version

0x26660700

### Adapter

ConBee2

**Comment by Koenkk** [comment]
These devices carry the same model number as many other "greenpower" devices. Therefore in z2m 1.28.0 it will be detected as `PTM 215Z` from Enocean (since that is the used module).

**Comment by lozwei** [comment]
Unfortunately this is a mix-up of two complete different devices. The device I am trying to use is mains powered, has different button actions and is (as far as I know) originally produced by Sunricher.

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of your device?

**Comment by Koenkk** [comment]
Given that the ieeeAddress starts with `0x00000000017` I'm pretty sure it contains an EnOcean PTM 215Z. This also means we cannot distinguish it from the PTM 215Z. The best we can do is to fix the `missing command '224'` error, how should this action be named?

**Comment by lozwei** [comment]
I don't know whats behind the "command 224", I'm not so deep in this topic right now.
What I really like to have, are those actions listed on the device page: press_1, hold_1, press_2, hold_2, press_3, hold_3, press_4, hold_4. Especially the "hold_x" ones.

In the meanwhile I found, what I think is the original product: [SR-ZG2833PAC-FOH](https://www.sunricher.com/zigbee-push-button-coupler-foh-version-sr-zg2833pac-foh.html)

**Comment by Koenkk** [comment]
I've added the command now, it should be exposes as `unknown_224`.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by lozwei** [comment]
Now they all get mapped to PTM 215Z. Unfortunately that's not what I want.
I seems my modules have a "wrong" ieeeAddress but I have no idea why. According to the herdsman sources it should start with 0x00000000427.
In this https://github.com/Koenkk/zigbee2mqtt/issues/8048 Issue, it's mentioned that a "Philips Hue device" is necessary in order to setup the modules correctly, which I don't have... but I doubt if this would change the ieeeAddress of the devices(???)

BTW: thank you very much for your support.

**Comment by Koenkk** [comment]
That won't change the ieeaddr, can you try to open your module to see what is inside?

**Comment by lozwei** [comment]
Here is the very delayed photo.
![20231128_193604](https://github.com/Koenkk/zigbee2mqtt/assets/93318463/5711e8ce-748d-4f57-8998-6b60b57c0f17)
