### ISSUE TITLE
Gledopto GL-S-006P GU10 not recognized 

### ISSUE THREAD

**Issue by xking3** [Koenkk/zigbee2mqtt#14482]
### What happened?

Gledopto GL-S-006P GU10 is not recognized. Version 1.4.0 & 1.5.0
It shows unsupported device.

### Zigbee2MQTT version

1.5.0

### Adapter firmware version

20220219

### Adapter

 zStack3x0

### Debug log

warn 14-10-2022 15:58:46: Received message from unsupported device with Zigbee model 'GL-S-006P' and manufacturer name 'GLEDOPTO'
warn 14-10-2022 15:58:46: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
`GL-S-006P` is supported in zigbee2mqtt 1.28.0

**Comment by xking3** [comment]
But I can Max have 1.6???
https://wiki.loxberry.de/plugins/zigbee2mqtt_plugin/start
