### ISSUE TITLE
[Feature request]: Allow to sort by first seen date in devices overview

### ISSUE THREAD

**Issue by CodingSpiderFox** [Koenkk/zigbee2mqtt#14494]
### Is your feature request related to a problem? Please describe

Currently migrating all tradfri devices to zigbee2mqtt with USB dongle.

I have to rename every new device

Don't want to scroll down in the list all the time

### Describe the solution you'd like

Introduce new, sortable column "first seen"

### Describe alternatives you've considered

Sort by number?

### Additional context

None

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by CodingSpiderFox** [comment]
Done -> https://github.com/nurikk/zigbee2mqtt-frontend/issues/1584
