### ISSUE TITLE
Docker Container stopped ervery couple of hours

### ISSUE THREAD

**Issue by 19Homer73** [Koenkk/zigbee2mqtt#145]
Hello,

my docker-container stoppes every couple hours with this log-message:

```
{"message":"request timeout","stack":"Error: request timeout
    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:254:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at CcZnp.emit (events.js:211:7)
    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:233:18)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)"}
```
Automatic restart is not possible.
I have to stop and start the container manually, then it works fine again.

Can anyone help me with this problem, please?

**Comment by ciotlosm** [comment]
Please update stick firmware to latest provided

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
@19Homer73 Can you please post the zigbee2mqtt version (it's shown when started) and if you have the firmware version md5 hash or URL that you used to install + date when you flashed the stick?

**Comment by 19Homer73** [comment]
The log says:

2018-6-25 07:39:07 INFO Starting zigbee2mqtt version 0.0.0 (commit #094c288)

I just downloaded the "RAW" file, doing a right mouseclick and save as **CC2531ZNP-Prod.hex**

I flashed the stick last week friday, 22nd June

**Comment by ciotlosm** [comment]
@19Homer73 it might be that you flashed latest "stable" or "master. The fixes so far are in the "experimental" branch. See my link above. 

I'd recommend you flash this and help us out with a test. So far it's been reported to be far better stability.

**Comment by ciotlosm** [comment]
yes

**Comment by 19Homer73** [comment]
OK, I will try later and give you response on it!
Thanks!!!

**Comment by ciotlosm** [comment]
@19Homer73 any update?

**Comment by 19Homer73** [comment]
Sorry, very busy days...
Yes, I did an update on the docker-container on sunday evening.
Because that was easier for me than flashing the USB-stick.
Since then, there are no problems anymore...
It's running for 4 days now.

**Comment by Koenkk** [comment]
Looks good, I will close this issue for now, in case you experience any problems please reopen.
