### ISSUE TITLE
Another "HS1CA-M" Device

### ISSUE THREAD

**Issue by MiddleSiggy** [Koenkk/zigbee2mqtt#14518]
### Link

https://www.aliexpress.us/item/3256803248629969.html?spm=a2g0o.productlist.0.0.22ed4adalzTieQ&algo_pvid=b64958bf-3ccb-4c8e-9c93-04583b559265&algo_exp_id=b64958bf-3ccb-4c8e-9c93-04583b559265-7&pdp_ext_f=%7B%22sku_id%22%3A%2212000025773734125%22%7D&pdp_npi=2%40dis%21USD%2141.5%2134.03%21%21%21%21%21%402101e9d016659856429134990ec527%2112000025773734125%21sea&curPageLogUid=HIIGPVQzUN5O

### Database entry

{"id":32,"type":"EndDevice","ieeeAddr":"0x005043c9172f3b44","nwkAddr":43220,"manufId":4627,"manufName":"Heiman","powerSource":"Battery","modelId":"CO_CTPG","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280,1,9],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0024c866e5","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"20150330","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1665985264213,"defaultSendRequestWhen":"immediate"}

### Comments

This is another version of the Heiman Smart Carbon Monoxide Sensor, but it is not in your supported list:
"modelId":"CO_CTPG"

If you can add it, that would be great.

When you press the button, this is the message I found in the Logs:
Debug 2022-10-17 00:45:17Received Zigbee message from 'Monoxide Sensor 03', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":33}' from endpoint 1 with groupID 0
Debug 2022-10-17 00:45:17No converter available for 'HM-H51CA-M' with cluster 'ssIasZone' and type 'commandStatusChangeNotification' and data '{"extendedstatus":0,"zonestatus":33}'

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Heiman'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'CO_CTPG', // Vendor model number, look on the device for a model number
    vendor: 'Heiman', // Vendor of the device (only used for documentation and startup logging)
    description: 'HS1CA-M - Smart carbon monoxide sensor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.ias_carbon_monoxide_alarm_1, fz.battery], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    /*
    onfigure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint);
        await reporting.batteryAlarmState(endpoint);
    },
    */
    exposes: [e.carbon_monoxide(), e.battery_low(), e.battery()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
