### ISSUE TITLE
[New device support]: IH-K009 _TZ3000_8ybe88nf

### ISSUE THREAD

**Issue by comperta** [Koenkk/zigbee2mqtt#14517]
### Link

 https://a.aliexpress.com/_EJ89k7f

### Database entry

{"id":37,"type":"EndDevice","ieeeAddr":"0xa4c13865280080bf","nwkAddr":14624,"manufId":4417,"manufName":"_TZ3000_8ybe88nf","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,3,1026,1029,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"65503":"+k9\u0000\u0012�m9\u0000\u0012%\u0000\u0000\u0000\u0012fc\u0000\u0000\u0012tz�*\u0011","65506":51,"65508":1,"65534":0,"modelId":"TS0201","manufacturerName":"_TZ3000_8ybe88nf","powerSource":3,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}},"msTemperatureMeasurement":{"attributes":{"measuredValue":1973}},"msRelativeHumidity":{"attributes":{"measuredValue":6374}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":126974596},"lastSeen":1665691303853,"defaultSendRequestWhen":"immediate"} {"id":38,"type":"EndDevice","ieeeAddr":"0xa4c138c705b05834","nwkAddr":7412,"manufId":4417,"manufName":"_TZ3000_8ybe88nf","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,3,1026,1029,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0011#�*\u0012","65506":51,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_8ybe88nf","zclVersion":3,"appVersion":69,"modelId":"TS0201","powerSource":3}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":118,"batteryVoltage":27}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2075}},"msRelativeHumidity":{"attributes":{"measuredValue":5836}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":126974596},"lastSeen":1665756712237,"defaultSendRequestWhen":"immediate"}

### Comments

In Z2M in Homeassistant it is recognized as:
Zigbee Model: TS0201
Zigbee Manufacturer: _TZ3000_8ybe88nf

Must be model: IH-K009

I have 3 of them and when i pair it the battery, température and voltage data is update and After that it freeze (no more update)
Link from Aliexpress:
https://a.aliexpress.com/_EJ89k7f

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
