### ISSUE TITLE
VZM31-SN is missing clusters LevelCtrl and OnOff when binding to Endpoint 1

### ISSUE THREAD

**Issue by kylehendricks** [Koenkk/zigbee2mqtt#14525]
### What happened?

Just received my [VZM31-SN](https://www.zigbee2mqtt.io/devices/VZM31-SN.html#inovelli-vzm31-sn) and everything is working great except I can't bind it to other devices.  Following [this thread](https://community.inovelli.com/t/blue-switch-ha-zha-unable-to-bind-group-to-switch/11821/18), it seems like it was also an issue in ZHA.

If I understand correctly, `LevelCtrl` and `OnOff` clusters should be appearing when binding Endpoint 1.  They only seem to be showing up on Endpoint 2.

### What did you expect to happen?

`LevelCtrl` and `OnOff` to appear when binding Endpoint 1.

### How to reproduce it (minimal and precise)

1. Go to the bind page for the device and select Endpoint 1.
2. Only the `Ota` cluster shows up.

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20220219

### Adapter

CC2652P2 Based Zigbee to PoE Coordinator 2022 WL

**Comment by MrBamse** [comment]
@kylehendricks did you ever find a solution to this? I have the exact same issue with a TS0601_dimmer_1_gang_1 and I noticed this while troubleshooting why it all of a sudden started to turn off at random intervals.
