### ISSUE TITLE
[New device support]: Bluetooth Buckram double spotlight

### ISSUE THREAD

**Issue by christofferdanielsson** [Koenkk/zigbee2mqtt#14521]
### Link

https://www.philips-hue.com/sv-se/p/hue-white-ambiance-buckram-dubbel-spot/8719514339088#specifications

### Database entry

.

### Comments

zigbeeModel: ['929003047901']
        model: '8719514339088',
        vendor: 'Philips',
        description: 'Hue White ambiance Buckram double spotlight with bluetooth',

Seems similar to this Philips 5047230P6 (https://www.zigbee2mqtt.io/devices/5047230P6.html). Its two individually adresses 929003047901_01 and 929003047901_02 after its paired.

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

I've just made a PR for the new quad and triple units.

If you can get me the database.db entry for your device, I can tag it in with the rest
