### ISSUE TITLE
 Schneider Electric EER50000 wrong entities exposed

### ISSUE THREAD

**Issue by benoithcc** [Koenkk/zigbee2mqtt#14542]
### What happened?

When EER50000 is linked to zigbeee2mqtt, climate (occupied_heating_setpoint, local_temperature) and linkquality are exposed.

### What did you expect to happen?

EER50000 should expose switch (state), power, energy and linkquality as the Schneider Electric EER42000.
EER50000 is not a climate device but a relay device with power and energy meter (to control heater but it is only a relay)

Link to the EER50000 : https://www.zigbee2mqtt.io/devices/EER50000.html
Link to the EER42000 : https://www.zigbee2mqtt.io/devices/EER42000.html

### How to reproduce it (minimal and precise)

Pair a EER50000 device.

### Zigbee2MQTT version

1.28.0-1

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 Plus

**Comment by benoithcc** [comment]
Hi,
I think it should at least have the same behavior as the CCTFR6700, otherwise we can’t control the heater at all without an external temperature or manual mode (off/auto/heat) https://www.zigbee2mqtt.io/devices/CCTFR6700.html
Or can someone explain how to switch on or off the heater without those functionalities (it works well with the Schneider box)
Thanks!

**Comment by coelhoricardo** [comment]
Hi, I have the same issue.

**Comment by coelhoricardo** [comment]
@benoithcc can you reopen the issue ?

**Comment by coelhoricardo** [comment]
(let's try to ping the original developer)
@pklokke Hi, can you help us ?

**Comment by pklokke** [comment]
The EER50000 (aka HACT) has a thermostat application loaded, so it relies on temperature reports to control its Relay/Fil Pilote outputs.

The EER42000 (aka LACT) acts as you describe.

The HW between the two is identical, but changing the application over requires directly reprogramming the MSP430 application processor onboard.

The original principle for the HACT is that it should work directly with an RTS and form a heating control loop, which will operate even if the gateway is offline.  Note that any temperature sensor in principle should work, as long as it can be bound to the temperature measurement client cluster exposed on endpoint 0x0b.

**Comment by coelhoricardo** [comment]
@benoithcc you can join the discussion on https://discord.com/channels/556563650429583360/1052136886912688199/1053262346988036136

**Comment by benoithcc** [comment]
> https://discord.com/channels/556563650429583360/1052136886912688199/1053262346988036136
I see nothing there... is it the right link?

**Comment by coelhoricardo** [comment]
Sorry, you have to join first : https://discord.gg/NyseBeK

**Comment by benoithcc** [comment]
Perfect I joined the discussion.

**Comment by coelhoricardo** [comment]
@benoithcc It's fixed on the latest release

**Comment by benoithcc** [comment]
@coelhoricardo Thanks for the update, I will test it this weekend.

**Comment by coelhoricardo** [comment]
@benoithcc I only tested, you should thank @pklokke ;-)
