### ISSUE TITLE
Awox / EGLO Pir sensor EPIR_Zm

### ISSUE THREAD

**Issue by adultano** [Koenkk/zigbee2mqtt#14554]
### Link

https://www.eglo.com/en/accessory-connect-z-sensor-99106.html

### Database entry

Device 0xa4c138a0f146a96c „EPIR_Zm“ not described in states mapping

### Comments

I am using Iobroker zigbee adapter which links to zigbee2mqtt herdsman. The pir sensor device got paired but is missing the config i guess. I tries to map it based on other pir sensors but i failed. Attached the details from iobroker. I guess it could be added to awox.js but i dont know how. Can anyone assist please? Thanks in advance. 
![828103F0-748A-4071-B36A-1F27AC73EA3B](https://user-images.githubusercontent.com/83014329/196749474-38a605b0-7641-4f82-a559-78d3b3fcad0a.jpeg)

**Comment by Koenkk** [comment]
Iobroker users should create issues in the iobroker issue tracker, not the zigbee2mqtt one.

**Comment by adultano** [comment]
Well it is not an iobroker issue - is it?! It clearly results from a missing config in zigbee2mqtt...

**Comment by Koenkk** [comment]
zigbee2mqtt != zigbee-herdsman

> Device 0xa4c138a0f146a96c „EPIR_Zm“ not described in states mapping

this is really an iobroker issue.

**Comment by adultano** [comment]
My bad - apologies. Agreed - but zigbee-herdsman seems also supported by you I think. Let me check and repost on the correct forum then.
