### ISSUE TITLE
How to disable the extra APS: Ack

### ISSUE THREAD

**Issue by he902** [Koenkk/zigbee2mqtt#1455]
With zigbee sniffing, I noticed an extra **APS: Ack** responded from my Yunmi Lock device for each Request sent from **zigbee2mqtt** to it.

You can see, there is:
`Acknowledgement Request: True` in the `Frame Control Field` in the APS layer

How to disable such extra APS: Ack via setting:
`Acknowledgement Request: False` ?

<img width="571" alt="zigbee2mqtt_APS_ACK" src="https://user-images.githubusercontent.com/8500278/56470878-2a4f2e80-647e-11e9-9333-2eacb17da658.PNG">

**Comment by he902** [comment]
With the Yunmi vendor's coordinator (gateway), there is no such extra APS: Ack responded from my Yunmi Lock device:

You can see, there is:
`Acknowledgement Request: False` in the `Frame Control Field` in the APS layer:

<img width="570" alt="yunmi_APS_ACK" src="https://user-images.githubusercontent.com/8500278/56470958-1f48ce00-647f-11e9-97b7-858f58d95c22.PNG">

**Comment by Koenkk** [comment]
I've found some documentation here: http://weber.itn.liu.se/~qinye29/tne090/Z-Stack%20Developer's%20Guide.pdf (8. End-to-end acknowledgements)

Currently zigbee-shepherd doesn't allow to pass this option externally. However you should be able to achieve this by changing https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/components/af.js#L787 to `    var afOptions = ZSC.AF.options.DISCV_ROUTE;    // ACK_REQUEST (0x10), DISCV_ROUTE (0x20)`

Why do you require this?

**Comment by he902** [comment]
Thanks @Koenkk, it works!

The reason I require this is that I'm trying to fully simulate the zigbee conversation between Yunmi vendor's coordinator and the Lock device.

The root cause is under investigation for why the PIN code sent to the Lock device is failed.
Another action I'm taking is to clone the MAC address, see discussion [here](https://github.com/Koenkk/Z-Stack-firmware/issues/72) (need your help too).
