### ISSUE TITLE
Legrand connected outlet not answering from time to time

### ISSUE THREAD

**Issue by jiquem** [Koenkk/zigbee2mqtt#14558]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9824145/log.txt)
### What happened?

A legrand connected outlet [067775_741811](https://www.zigbee2mqtt.io/devices/067775_741811.html#legrand-067775%252F741811) don't respond during some hours, then came back, then restop.
What is quite strange, is that it is at near the Zigbee adapter and that I've have two others who are far away and they answer well. (I have around 40 routers in my setup)

### What did you expect to happen?

I didn't expect the connected outlet to stop responding

### Zigbee2MQTT version

1.28.0 

### Adapter firmware version

20220219

### Adapter

SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator

### Debug log

the device is legrand_power_ilot
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/9824149/log.txt)

**Comment by trollix** [comment]
Hello,
It's the same for me...

<img width="434" alt="screenshot_978" src="https://user-images.githubusercontent.com/3890545/199978927-89f3e14e-7076-417f-8d52-677e428ca570.png">

<img width="1477" alt="screenshot_979" src="https://user-images.githubusercontent.com/3890545/199979029-f7388ebb-aaa1-432e-8296-e3cfa99c3a03.png">
