### ISSUE TITLE
[New device support]: OSRAM LIGHTIFY Under Cabinet TW

### ISSUE THREAD

**Issue by adgenet** [Koenkk/zigbee2mqtt#14562]
### Link

https://www.amazon.com//dp/B01M98S1LW

### Database entry

{"id":28,"type":"Router","ieeeAddr":"0x7cb03eaa00a5c60d","nwkAddr":43279,"manufId":48042,"manufName":"OSRAM","powerSource":"Mains (single phase)","modelId":"LIGHTIFY Under Cabinet TW","epList":[3],"endpoints":{"3":{"profId":260,"epId":3,"devId":258,"inClusterList":[0,3,4,5,6,8,768,64527],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LIGHTIFY Under Cabinet TW","manufacturerName":"OSRAM","powerSource":1,"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20150601N****"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20150601N****","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1666253839808,"defaultSendRequestWhen":"immediate"}

### Comments

Included converter tested working.

### External converter

```shell
{
    zigbeeModel: ['LIGHTIFY Under Cabinet TW'],
    model: 'LIGHTIFY Under Cabinet TW',
    vendor: 'OSRAM',
    description: 'LIGHTIFY Under Cabinet TW',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
    exposes: [e.light_brightness_colortemp([153, 370]).removeFeature('color_temp_startup')],
    ota: ota.ledvance
    },
```

### Supported color modes

color temperature

### Color temperature range

Device does not report colorTempPhysicalMin or colorTempPhysicalMax, but values in the included converter appear to be min and max.

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4805 by @danieledwardgeorgehitchcock 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
