### ISSUE TITLE
[New device support]: New model of an already supported device

### ISSUE THREAD

**Issue by Lovasz-Akos** [Koenkk/zigbee2mqtt#14563]
### Link

not public yet

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xa4c1382f0f83723d","nwkAddr":42040,"manufId":4417,"manufName":"_TZ3000_yujkchbz","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"inClusterList":[3,4,5,6,1794,2820,57345,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_yujkchbz","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"powerOnBehavior":0,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1666271020670,"defaultSendRequestWhen":"immediate"}

### Comments

I'd like to ask if there's a quick way to add a device that's basically just a facelift version of an already existing device, nothing changed about the internals or exposes.

**Comment by Lovasz-Akos** [comment]
supposed to use same internals as [this plug](https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html), with a new shell

**Comment by Lovasz-Akos** [comment]
that could work, thanks :D 

at some point I'd like to create it's own entry as it looks different and the vendor will be Moes (and probably a different model number)

**Comment by danieledwardgeorgehitchcock** [comment]
If that's the case, I'd just ad a whitelabel entry to the TS011F converter rather than adding a complete new entry

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/4806

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
