### ISSUE TITLE
TS601 commit revert

### ISSUE THREAD

**Issue by zsoltty91** [Koenkk/zigbee2mqtt#14578]
### What happened?

Dear Koenkk,

I have an Avatto ME167 TRV, Z2M does not support now.

I raise a ticket with the problem:
https://github.com/Koenkk/zigbee2mqtt/issues/14441

There was a fix to pair the device as a TS601 but it not works unfortunately.
Your last commit was this on the converters projects:
https://github.com/Koenkk/zigbee-herdsman-converters/commit/2950b897d6202dc1c1a948e57757a3fa5ef69662

Can you revert this commit due to this fix is not working.

This device will be supported by this ticket:
https://github.com/Koenkk/zigbee-herdsman-converters/issues/4694

Thank you for your help, and looking forward to the feature that will support this TRV!

### Zigbee2MQTT version

1221

### Adapter firmware version

202110

### Adapter

slaesh

**Comment by Koenkk** [comment]
Done! I will wait for a merge request to get the device supported.
