### ISSUE TITLE
[New device support]: Third Reality 3RTHS24BZ Temperature and Humidity Sensor with LCD Display

### ISSUE THREAD

**Issue by didgeriwho** [Koenkk/zigbee2mqtt#14603]
### Link

https://www.amazon.com/THIRDREALITY-Temperature-Monitoring-Automation-Batteries/dp/B0BF9W3WMK

### Database entry

{"id":27,"type":"EndDevice","ieeeAddr":"0x282c02bfffe39613","nwkAddr":36900,"manufId":4659,"manufName":"Third Reality, Inc","powerSource":"Mains (single phase)","modelId":"3RTHS24BZ","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,1,1026,1029],"outClusterList":[25],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2260}},"msRelativeHumidity":{"attributes":{"measuredValue":4200}},"genBasic":{"attributes":{"hwVersion":0,"swBuildId":"1.00.20"}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":20,"stackVersion":2,"hwVersion":0,"swBuildId":"1.00.20","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1666487502166,"defaultSendRequestWhen":"immediate"}

### Comments

New device from this company - would like to see if I can get this compatible with HA with Zigbee2MQTT. I have it connected to SmartThings just fine but it doesn't pass through the data to HA via the integration.

**Comment by Koenkk** [comment]
`3RTHS24BZ` will be supported in the next release and is already supported in the dev branch (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
