### ISSUE TITLE
[New device support]: TUYA TS0601  _TZE200_2hf7x9n3 

### ISSUE THREAD

**Issue by KinDR007** [Koenkk/zigbee2mqtt#14615]
### Link

https://www.aliexpress.com/item/1005003590413708.html?spm=a2g0o.store_pc_allProduct.8148356.1.22975a9bIhWeis&pdp_npi=2%40dis%21USD%21US%20%2435.91%21US%20%2418.31%21%21%21%21%21%400b0a0ae216665454645482234ed5a6%2112000026402282681%21sh

### Database entry

{"id":61,"type":"Router","ieeeAddr":"0xa4c13853863d2c4f","nwkAddr":19963,"manufId":4417,"manufName":"_TZE200_2hf7x9n3","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�d�)f�d�)\u0012","65506":48,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE200_2hf7x9n3","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genGroups":{"attributes":{"nameSupport":0}},"genScenes":{"attributes":{"count":0,"currentScene":0,"nameSupport":0,"currentGroup":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca16426","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca16426","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-742127450},"lastSeen":1666544707863,"defaultSendRequestWhen":"immediate"}

### Comments

Please add this *TUYA* device 
manufacture  : 
 _TZE200_2hf7x9n3
model : 
 TS0601

**Comment by Koenkk** [comment]
`_TZE200_2hf7x9n3` will be supported in the next release on 1 November.
