### ISSUE TITLE
Blitzwolf BW-SHP13 plug (TS011F_plug_1) does not detect power below 10 watt

### ISSUE THREAD

**Issue by manny199** [Koenkk/zigbee2mqtt#14629]
### What happened?

My Blitzwolf BW-SHP13 plug does not detect watt below 10 watt. Basically, the value it shows with consumption below 8/10 watts is equal to ZERO.
For example, if I put a webcam it does not detect its consumption in watt because webcam have low consumption

### What did you expect to happen?

I expect power detection below 10 watt

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

2021

### Adapter

Sonoff ZigBee 3.0

### Debug log

I have a bit of a weird problem. My Blitzwolf BW-SHP13 plug does not detect watt below 10 watt. Basically, the value it shows with consumption below 8/10 watts is equal to ZERO.
For example, if I put a webcam it does not detect its consumption in watt.
The Plug is detected as TS011F_plug_1 and the firmware has been updated. The production is _TZ3000_amdymr7l
I tried with tuya gateway and it detect power also about 1 watt but not with zigbee2mqtt.
What the solution to this problem?

**Comment by ster1um** [comment]
is not problem a zigbee2mqtt...
The plug it's not much sensitive is cheap plug.

**Comment by manny199** [comment]
> The plug it's not much sensitive is cheap plug

Can you suggest me a quality plug that also detects below 2 watts?

**Comment by ster1um** [comment]
I have 2 same plug and start measurement to 6W, for my scope it is not needed.
You wait other suggestion or try different plug in the device list

**Comment by Koenkk** [comment]
Closing as this is an hardware issue of the plug, not something we can solve from z2m.

**Comment by manny199** [comment]
Although these plugs have the same name BW-SHP13, they have different hardware. Convenient to buy TS0121 to have reading above 1.5 watts. The model with hardware TS011F_plug_1 does not detect below 10 watts
