### ISSUE TITLE
[Feature request]: SONOFF S31/S40 Energy Monitor Support

### ISSUE THREAD

**Issue by bfmcneill** [Koenkk/zigbee2mqtt#14634]
### Is your feature request related to a problem? Please describe

Sonoff S30ZB/S40ZB shows it can measure power consumption metrics - current, power, voltage in addition to on/off but the zigbee2mqtt docs show on/off is the only available data. 

Is it possible to make energy monitoring metrics available to the zigbee2mqtt?

### Describe the solution you'd like

get these two devices to have energy monitoring available in zigbee2mqtt message

[Amazon SONOFF S40](https://www.amazon.com/gp/product/B0B2RBLKBY)
[zigbee2mqtt docs SONOFF S40](https://www.zigbee2mqtt.io/devices/S40ZBTPB.html)

[Amazon SONOFF S31](https://www.amazon.com/dp/B08X2944W7/ref=twister_B0B4MZF171)
[zigbee2mqtt docs SONOF S31](https://www.zigbee2mqtt.io/devices/S31ZB.html)

### Describe alternatives you've considered

It looks like only one zigbee2mqtt smart plug device is configured to expose energy metrics which is roughly 3x the price of sonoff s40 / s31 smart plugs with energy metrics.

sengled smart plug 4 pack [amazon](https://www.amazon.com/Sengled-Compatible-Required-Appliances-Certified/dp/B092DBFFBY/)

[zigbee2mqtt docs](https://www.zigbee2mqtt.io/devices/E1C-NB7.html)

### Additional context

Thanks, this is my first request with the zigbee2mqtt open source project.

**Comment by jerrm** [comment]
The hardware doesn't support it.  The zigbee plug models are actually labeled as S31 _**Lite**/S40_ **_Lite_** by [Sonoff](https://itead.cc/product/sonoff-zigbee-smart-plug-iplug-lite/).   They don't currently make a "non-Lite" US zigbee plug.  Sonoff "Lite" plugs, zigbee or WiFi, don't do power monitoring.

You're pricing is off as well.  Your Amazon links are for the WIFi versions of the plug, which are less expensive than the zigbee version.  The Sengled zigbee plugs go "on sale" quite often via something like Prime Day or via "coupon."

I just checked and the S40 Lite ZB is $11.70/ea (w/coupon) net before tax.  The Sengled plugs are $10.04/ea in a 4 pack w/coupon, or $11.70/ea in a 2 pack w/coupon.  Pricing could change in five minutes, but if you keep watch the deal will pop back up.
