### ISSUE TITLE
[New device support]: Philips Hue 4090131P9

### ISSUE THREAD

**Issue by kocurak** [Koenkk/zigbee2mqtt#14649]
### Link

https://www.dmlights.com/philips_hue_sana_white_and_colored_light_bluetooth_white~1876M

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0x0017880106fb5078","nwkAddr":44354,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"4090131P9","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20190529","swBuildId":"1.56.7_r29434","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1666710651443,"defaultSendRequestWhen":"immediate"} 

### Comments

Hi, I tried to add this model using an external converter but with no luck, not sure what I'm doing wrong. Would you be so kind and add it please? Thank you.
Should be similar to model 4090130P7.

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by danieledwardgeorgehitchcock** [comment]
On it!
