### ISSUE TITLE
OWON PC321 Can't modify report timing

### ISSUE THREAD

**Issue by renaiku** [Koenkk/zigbee2mqtt#14645]
### What happened?

The device reports change between 3 and 5 times per minutes so my Home Assistant database is giant because of this.

I tried to change the report frequency in z2m.

Setting this in the UI:
![image](https://user-images.githubusercontent.com/17033907/197772023-bfce634c-6b87-487a-a081-7a0fc9c273ee.png)

Gives this error.
```
error 2022-10-25 14:21:22Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x3c6a2cfffed21266/1 seMetering([{"attribute":"owonL1PhasePower","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":"1"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 6252 - 1 - 238 - 1794 - 7 after 10000ms)'
```

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20220103

### Adapter

zzh

**Comment by danieledwardgeorgehitchcock** [comment]
If your device is battery powered, it needs to be awake while setting the reporting interval

**Comment by renaiku** [comment]
It is not https://www.zigbee2mqtt.io/devices/PC321.html

**Comment by cddu33** [comment]
Hello, I have the same problem, I think the action does not exist in the convertissuer but I do not have the skill to modify it

Here is the info:
![image](https://user-images.githubusercontent.com/59371705/198884054-628dc0ae-74f3-478f-b991-a147668d6ae3.png)

**Comment by renaiku** [comment]
Oh perfect! If nobody tried in a few days I'll check it. I don't have time this weekend !

**Comment by renaiku** [comment]
I don't find examples on how to add writeable config.
The file to update would be this one: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/owon.js

@cddu33 where did you find this file ?

**Comment by cddu33** [comment]
Hi, here https://github.com/zigpy/zha-device-handlers/issues/1657

**Comment by renaiku** [comment]
Still an issue.
