### ISSUE TITLE
Mount CC2531 USB sniffer in Hyper-V VM

### ISSUE THREAD

**Issue by SpeedBlack** [Koenkk/zigbee2mqtt#1466]
Hi,

I'm looking for how to mount the CC2531 USB sniffer in in Hyper-V VM (Debian).
The host system of Hyper-V is a Windows Server 2012 R2.

Do you have any idea ?

In advance, thank you for your help !

**Comment by brent0np** [comment]
Hi, I believe you will need to use some third party software as hyperv won't allow the device to be passed through.
