### ISSUE TITLE
Aqara D1 triple wall switch with neutral (QBKG26LM) - buttons presses not seen by Z2M

### ISSUE THREAD

**Issue by ASAujla** [Koenkk/zigbee2mqtt#14673]
### What happened?

I've just installed one of these, and I can control my lights via the buttons and via Home Assistant using the Z2M integration. However, physical button presses do not seem to reflect in Home Assistant and MQTT Explorer suggests that physical button presses are not published to MQTT, unlike commands from Home Assistant. I think this means that Z2M is not seeing any actions being reported by the D1 switch. I am also unable to create an automation using "action" as I do with my Aqara H1 double wall switch with neutral, as actions do not seem to work with the D1.

Does anyone have this working?

### What did you expect to happen?

I expected button presses to be published to MQTT and for "actions" to work as they do with the H1.

### Zigbee2MQTT version

1.28.0-1 (Home Assistant Add-on)

### Adapter firmware version

0x26580700

### Adapter

ConBee2

**Comment by ASAujla** [comment]
Closed as I realised this is an ongoing issue in another thread.

**Comment by ASAujla** [comment]
Reopening as, after reading other issues, it seems this may be fixed for other controllers but not for the ConBee2. Is there a fix for this? Any help much appreciated! I am using the Home Assistant Z2M add-on (dev branch).

**Comment by umedsondoniyor** [comment]
I have 24 such QBKG26LM devices, 18 of them have firmware version 08-13-2021, these work fine, 6 other firmware versions 11-08-2021 has the same issue as mentioned above. @ASAujla  can someone help? @dustin @azuwis @tomusher @shish

**Comment by ASAujla** [comment]
> I have 24 such QBKG26LM devices, 18 of them have firmware version 08-13-2021, these work fine, 6 other firmware versions 11-08-2021 has the same issue as mentioned above. @ASAujla can someone help? @dustin @azuwis @tomusher @shish

Sorry, I still have the same problem. I can confirm that my firmware version is also 11-08-2021. It looks like the newer firmware may have wrecked the device. I don't have an Aqara hub, so no way of changing the firmware, unfortunately. The rest of my switches are Aqara H1s and they all work well. I just wish they would the 3-button version in the UK.

**Comment by AlexFoks2103** [comment]
> У меня есть 24 таких устройства QBKG26LM, 18 из них имеют версию прошивки 08-13-2021, они работают нормально, 6 других с версией прошивки 11-08-2021 имеют ту же проблему, что и упомянутая выше.[@ASAujla](https://github.com/ASAujla) может кто-нибудь помочь?[@dustin](https://github.com/dustin) [@azuwis](https://github.com/azuwis) [@tomusher](https://github.com/tomusher) [@shish](https://github.com/shish)

Hi, were you able to find the firmware for QBKG26LM from 08-13-2021?
