### ISSUE TITLE
[New device support]: Aurora Smart16ARelay51AU

### ISSUE THREAD

**Issue by poirs01** [Koenkk/zigbee2mqtt#14678]
### Link

https://zigbee.blakadder.com/Aurora_AU-A1ZBR16A.html

### Database entry

0x0015bc0037000dcd

### Comments

Thank you for your help in adapting this module

**Comment by Pel1can111** [comment]
Looked into getting this working. This was my first time trying to get an unsupported device to work so I can't imagine its done correctly but currently have the following. I also had to add some stuff to the reporting tab to get things to update properly.

`const {deviceEndpoints, onOff, electricityMeter, deviceTemperature} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['Smart16ARelay51AU'],
    model: 'Smart16ARelay51AU',
    vendor: 'Aurora',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"2":2}}), onOff({"powerOnBehavior":false,"endpointNames":["2"]}), electricityMeter({"endpointNames":["2"]}), deviceTemperature({"endpointNames":["2"]})],
    meta: {"multiEndpoint":true},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(2);
        await reporting.rmsVoltage(endpoint);
        await reporting.rmsCurrent(endpoint);
        await reporting.acFrequency(endpoint);
        await reporting.currentSummReceived(endpoint);
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acFrequencyMultiplier: 1, acFrequencyDivisor: 1000,});
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acVoltageMultiplier: 1, acVoltageDivisor: 1000,});
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentMultiplier: 1, acCurrentDivisor: 1000,});
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 1000, multiplier: 1});
    },
};

module.exports = definition;
`
