### ISSUE TITLE
[New device support]: Motion Sensor TS0202_TZ3040_fwxuzcf4

### ISSUE THREAD

**Issue by gargamelonly** [Koenkk/zigbee2mqtt#14693]
### Link

https://www.aliexpress.com/item/1005004383804073.html?spm=a2g0o.order_detail.0.0.30b4f19cUqjOcl

### Database entry

{"id":6,"type":"EndDevice","ieeeAddr":"0xa4c138b1ffc14cde","nwkAddr":38852,"manufId":4417,"manufName":"_TZ3040_fwxuzcf4","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,4,1280,0],"outClusterList":[4,6,4096,25,10],"clusters":{"genBasic":{"attributes":{"65503":"q\u0000\u0000\u0000\u0012�\u0000\u0000\u0000\u0012\u0002\u0001\u0000\u0000\u0012\u0011�*\u0011","65506":55,"65508":1,"65534":0,"modelId":"TS0202","manufacturerName":"_TZ3040_fwxuzcf4","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x00124b002281a219","zoneState":1,"currentZoneSensitivityLevel":1,"zoneStatus":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":126974596},"lastSeen":1666983704434,"defaultSendRequestWhen":"immediate"}

### Comments

I created a new device file "js" according to instructions. 
The device works but I am not familiar with how to submit new devices so I do not want to make any error in the process.
Attaching the working js file.
[fwxuzcf4.zip](https://github.com/Koenkk/zigbee2mqtt/files/9891245/fwxuzcf4.zip)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0202'],
    model: 'LQ-CG01-IR',
    vendor: 'TuYa', // Vendor of the device (only used for documentation and startup logging)
    description: 'Motion sensor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery, fz.ignore_basic_report, fz.ZM35HQ_attr,],
    toZigbee: [tz.ZM35HQ_attr], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.occupancy(), e.battery_low(), e.linkquality(), e.tamper(), e.battery(), 
            exposes.enum('sensitivity', ea.ALL, ['low', 'medium', 'high']).withDescription('PIR sensor sensitivity'),
            exposes.enum('keep_time', ea.ALL, [30, 60, 120]).withDescription('PIR keep time in seconds'),	
	],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await endpoint.read('genBasic', ['manufacturerName', 'zclVersion', 'appVersion', 'modelId', 'powerSource', 0xfffe]);
    },	
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
