### ISSUE TITLE
Support for Philips Hue Garnea 5110731H5

### ISSUE THREAD

**Issue by fantasynite** [Koenkk/zigbee2mqtt#14701]
### Link

https://www.philips-hue.com/en-sg/p/hue-white-ambiance-garnea-hue-white-ambience-downlight/5110731H5

### Database entry

0x00178801085feac3

### Comments

ZigBee ID LTD007 unsupported yet.

[https://imgur.com/a/pVv2s5q](url)

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/4849 by @danieledwardgeorgehitchcock ❤️ 

 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
