### ISSUE TITLE
Router and GL-C-008 

### ISSUE THREAD

**Issue by Ulli2k** [Koenkk/zigbee2mqtt#1470]
# Bug Report
## What happened
I have successfuly paired the GL-C-008 and I can control the LED strip without any issues.
But what is not working:
* the GL-C is not working like a router. 
* zigbee2mqtt always show offline @GL-C

## What did you expect to happen
* to see how other xiaomi devices are connected to GL-C. I checked it with the networkmap

## How to reproduce it (minimal and precise)
always the same issue

## Debug Info
zigbee2mqtt version: 1.3.1
CC253X firmware version: 20181024

Networkmap is the following
`digraph G {
node[shape=record];
  "0x00124b001936646c" [style="bold", label="{0x00124b001936646c|Coordinator|No model information available|online}"];
  "0x00158d0002e98f0b" [style="rounded, dashed", label="{0x00158d0002e98f0b|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0002e93c1e" [style="rounded, dashed", label="{0x00158d0002e93c1e|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0002e93c1e" -> "0x00124b001936646c" [label="37"]
  "0x00124b001d10f506" [style="rounded", label="{0x00124b001d10f506|Router|Gledopto Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer (GL-C-008)|offline}"];
  "0x00124b001d10f506" -> "0x00124b001936646c" [label="35"]
  "0x00158d0002f9257b" [style="rounded, dashed", label="{0x00158d0002f9257b|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d0002f9257b" -> "0x00124b001936646c" [label="35"]
  "0x00158d00027d9f53" [style="rounded, dashed", label="{0x00158d00027d9f53|EndDevice|Xiaomi Mi/Aqara smart home cube (MFKZQ01LM)|online}"];
  "0x00158d00027d9f53" -> "0x00124b001936646c" [label="75"]
  "0x00158d0002e2e0f5" [style="rounded, dashed", label="{0x00158d0002e2e0f5|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d00025eeb44" [style="rounded, dashed", label="{0x00158d00025eeb44|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d00025eeb44" -> "0x00124b001936646c" [label="43"]
  "0x00158d0002c12956" [style="rounded, dashed", label="{0x00158d0002c12956|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0002c12956" -> "0x00124b001936646c" [label="170"]
  "0x00158d0002c90429" [style="rounded, dashed", label="{0x00158d0002c90429|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0002c90429" -> "0x00124b001936646c" [label="69"]
  "0x00158d0002c1292b" [style="rounded, dashed", label="{0x00158d0002c1292b|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0002c1292b" -> "0x00124b001936646c" [label="170"]
  "0x00158d000312220c" [style="rounded, dashed", label="{0x00158d000312220c|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d000312220c" -> "0x00124b001936646c" [label="66"]
  "0x00158d0002f9113a" [style="rounded, dashed", label="{0x00158d0002f9113a|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d0002f9113a" -> "0x00124b001936646c" [label="44"]
  "0x00158d0002ecf09c" [style="rounded, dashed", label="{0x00158d0002ecf09c|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d000312dfff" [style="rounded, dashed", label="{0x00158d000312dfff|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
}`

**Comment by dh-harald** [comment]
Based on the latest dev branch which has better working network map support, I can confirm, that GL-C-008 can act as a router... (for me it could connect to IKEA repeater and Xiaomi wall switches)
