### ISSUE TITLE
Aqara FP1 Performance Issues on Z2M vs Aqara E1 Hub

### ISSUE THREAD

**Issue by amilanov75** [Koenkk/zigbee2mqtt#14739]
### What happened?

The FP1 does not perform well when connected to Z2M.
When I connect the same device to an Aqara E1 Hub it detects presence in around 5-6 seconds and usually detects absence in less than 10 seconds. 
On Z2M, detection can happen in 5-6 seconds, however sometimes and depending on the location the person is, it can take well over 10 seconds, or not ever detect presence. Detecting absence generally does not happen faster than 15 seconds up to 25 seconds when it is working well, and sometimes much longer, when it is not working well.

Has anyone else experienced something like this?

### What did you expect to happen?

I thought all the processing happened on the Aqara FP1, in which case messages would be sent from the sensor exactly the same regardless of what hub/controller it is connected to.
Although I appreciate that with the Aqara Hubs you can use zoning to improve performance, my testing was with keeping the settings identical on both Z2M and Aqara E1.

### How to reproduce it (minimal and precise)

Tried 4x difference FP1s, on 2x Z2M sticks and compared vs Aqara E1 Hub.
Settings where factory default and also extended the range to "far" when testing in a larger room.

### Zigbee2MQTT version

1.28.0 commit: 03ba647d

### Adapter firmware version

20220219

### Adapter

cc2652P USB stick zigbee2mqtt ZigBee Zigstar v4

**Comment by cantfindanam** [comment]
Yep same for me.
