### ISSUE TITLE
[Feature request]: Use MQTT update feature in HA

### ISSUE THREAD

**Issue by andriej** [Koenkk/zigbee2mqtt#14748]
### Is your feature request related to a problem? Please describe

Since 2022.11 in HA there will be possibility to use 'update' platform for firmware updates
That could be used for OTA-available firmwares in z2m

https://github.com/home-assistant/core/pull/81131

### Describe the solution you'd like

Show 'update' possibility in HA when new firmware available for device

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by bkbilly** [comment]
I've just created a new python package which works as a service that you might be interested on trying out.
It reads the current version and the latest version of zigbee2mqtt and other services and creates a new update sensor with the ability to install the newest version.
You can find it here: https://pypi.org/project/service-updater/

It would be great if we could have this feature directly on zigbee2mqtt, but for now I hope this helps.

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee2mqtt/pull/14905

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
