### ISSUE TITLE
Z2M GUI -> Exposes never shows state

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#14756]
### What happened?

The Exposes pamne in the Z2M control GUI never shows last used state. All actions only show for a fraction of a second (not really recognizable to a human eye) and then goes back to None (Null). My devices work but this makes troubleshooting and setup unnecessarily hard. For example, if a device sends specific command such as "longpress_up", I don't see it and have to go to console for that. 
It has always been like this for me, for almost four years now.

### What did you expect to happen?

I expect to see the last action clearly on screen.

### How to reproduce it (minimal and precise)

Go to any device, go to Exposes, do an action with the device.

### Zigbee2MQTT version

1.28.00

### Adapter firmware version

20220219

### Adapter

Slaeh.sh CC2652RB

**Comment by Koenkk** [comment]
See https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty why this happens. You can use the logging instead
