### ISSUE TITLE
[Feature request]: Add long-press to Aqara switches

### ISSUE THREAD

**Issue by B-roox** [Koenkk/zigbee2mqtt#14755]
### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Add support for long-press automations to Aqara wall switches (particularly the WS-USC03).

### Describe alternatives you've considered

...HomeKit?

### Additional context

None

**Comment by ZZJHONS** [comment]
It would be nice, but checking the Aqara app it seems is only possible with the Wireless switch and not an option for the wired ones
