### ISSUE TITLE
BHT-002

### ISSUE THREAD

**Issue by ilvi80** [Koenkk/zigbee2mqtt#14767]
### What happened?

Устройство поддерживает регулировку температуры до +35С. 
Но в z2m можно выставить максимум +30, почему? Сделайте, пожалуйста, поддержку температуры корректно. 

### Zigbee2MQTT version

1.28.1

### Adapter firmware version

20220219

### Adapter

Сс2652р

**Comment by Koenkk** [comment]
English only.
