### ISSUE TITLE
IKEA	E1744 actions are not published on MQTT

### ISSUE THREAD

**Issue by thekoma** [Koenkk/zigbee2mqtt#14796]
### What happened?

All (3) of my remotes E1744 stopped working.
I don't use those often but they worked previously.

### What did you expect to happen?

By clicking or rotating the remote the action should be published in MQTT but the action is only registered not published.

### How to reproduce it (minimal and precise)

Use E1744 on the following version:

### Zigbee2MQTT version

1.28.1-1

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Debug log

Debug 2022-11-03 22:22:53Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":0,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:54Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:54Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":0,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:54Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:54Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:55Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:55Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:55Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:55Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":1,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:55Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:56Received Zigbee message from 'volume_soppalco', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":0,"rate":195}' from endpoint 1 with groupID 0
Debug 2022-11-03 22:22:57Received Zigbee message from 'volume_soppalco', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0****

**Comment by domidyon** [comment]
Same issue here. Reverted the update back, no problems anymore. I'll hold off for now.
