### ISSUE TITLE
Problems with groups/optimistic setting

### ISSUE THREAD

**Issue by tamueller** [Koenkk/zigbee2mqtt#14800]
### What happened?

I'm having a lot of trouble with groups and individual lights with Z2M and HA. I want to have a group with 6 lights, where I can turn them on/off together with one zigbee command, but also be able to turn one light on individually without all other lights going on.
I was told, setting "optimistic" to false should do exactly that, but it doesn't work for me. This is what happens here:

When I don't specify optimistic at all, I can switch on/off the group as expected, but If I switch on an individual light, the whole group will switch to state on, which will issue an MQTT command notifying HA that the Group turned on, which then makes HA send a request to turn the whole Group on, and then all lights in the group go on as well. I'm not sure if thats a bug in HA, or intended behaviour.

When I specify optimistic: true something strange happens: In Node-Red using node-red-contrib-zigbee2mqtt all groups disappear, and I can't select them in the device selection anymore, and can't send commands to them. It still works directly in HA, but I'm not sure whether thats a bug in this repo or the node-red-contrib repo.

When I specify optimistic: false, and send a command to turn on the group (either with HA or with NodeRed Z2M contrib), all the lights turn on physically, but the state of all lamps and the state of the group remain off in HA / Z2M. Therefore any "toggle" command, or any logic using the state of the lights fail, as they report the wrong state. This seems to be a bug in Zigbee2Mqtt.

### How to reproduce it (minimal and precise)

* create a group with optimistic: false
* turn on the group with a group command
* check the state of the lights

### Zigbee2MQTT version

1.28.1

### Adapter firmware version

20220219

### Adapter

SonCC2652P

**Comment by SHxKM** [comment]
@tamueller ever found a solution to this?
