### ISSUE TITLE
No Max Brightness on TS0601_Dimmer

### ISSUE THREAD

**Issue by JoeAstor** [Koenkk/zigbee2mqtt#14805]
### What happened?

In the "Exposes" Tab there is a option to set max Brightness, but in the "State" Tab There is no max brigtness.
Therefor it is not possible to set max brightness in "Exposes" tab and always stays at 0 and will not save on change.

![Screenshot_20221103_200740_Home Assistant](https://user-images.githubusercontent.com/50339032/199968816-c37ac748-a3be-428c-bce8-3f096b7a2a31.jpg)
![Screenshot_20221103_200745_Home Assistant](https://user-images.githubusercontent.com/50339032/199968824-b2a731ea-9dfd-4375-985a-2ad57981b417.jpg)

Hardware:
![20221103_202812](https://user-images.githubusercontent.com/50339032/199969625-0cf192a9-7969-41fd-820f-cf5ef85bc559.jpg)

Autodetected TS0601_Dimmer

### Zigbee2MQTT version

1.28.1

### Adapter firmware version

20210120

### Adapter

Silicon_Labs_Slae.sh_cc2652rb_stick

**Comment by danieledwardgeorgehitchcock** [comment]
If you enable debug logging, do you get any messages or errors when setting the `max_brightness` via the exposes control?
