### ISSUE TITLE
X5H-GB-B thermostat with wrong time

### ISSUE THREAD

**Issue by sheaur** [Koenkk/zigbee2mqtt#14811]
### What happened?

The time that the thermostat sets is incorrect, it is 2 days of the week behind and the time is wrong.

### What did you expect to happen?

Correct time

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

Sonoff zigbee 3.0 USB dongle P

### Debug log

{"id":6,"type":"Router","ieeeAddr":"0xa4c13851bf0f0033","nwkAddr":50299,"manufId":4417,"manufName":"_TZE200_2ekuz3dz","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"l\u0006�*i","65506":54,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","appVersion":70,"zclVersion":3}},"genTime":{"attributes":{}},"genOta":{"attributes":{"upgradeServerId":"0xffffffffffffffff","currentFileVersion":70}}},"binds":[{"cluster":10,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b869e1","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1667579340902,"defaultSendRequestWhen":"immediate"}

**Comment by vladyspavlov** [comment]
Duplicate https://github.com/Koenkk/zigbee2mqtt/issues/14037
