### ISSUE TITLE
Docker container not responding to stopping command (and gets killed)

### ISSUE THREAD

**Issue by Bojan023** [Koenkk/zigbee2mqtt#1482]
I'm running a Docker container with Zigbee2MQTT which is working perfectly. But it seems that Zigbee2MQTT does not respond to the stop signal from Docker (docker stop) and therefore Docker kills the container. This results in a hard stop instead of a proper shut down (e.g. no 'Zigbee2MQTT is offline' broadcast over MQTT is sent).

Every time I (re)start the container, the Zigbee network has to be reinitialized (no routes found). Although I'm not really sure this is correlated to the problem above. 

Unfortunately I'm not an experienced programmer but I was wondering if it is possible, e.g. via the Dockerfile/Docker image, to execute a stopping command of the Zigbee2MQTT service before the container gets killed.

**Comment by Koenkk** [comment]
Thanks, fixed!
