### ISSUE TITLE
Xiaomi door sensor battery info missing for some sensor

### ISSUE THREAD

**Issue by Maurotb** [Koenkk/zigbee2mqtt#1484]
Hi,
i have installed 12 xiaomi door sensor,
some sensor show battery info
4/30/2019, 10:47:43 PM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'lumi.sensor_magnet.aq2' (0x00158d0002bfa366) of endpoint 1
4/30/2019, 10:47:43 PM - info: MQTT publish: topic 'zigbee2mqtt/Sensore-Porta-Ingresso', payload '{"contact":true,"linkquality":31,"battery":100,"voltage":3015}'
4/30/2019, 10:47:43 PM - debug: Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'lumi.sensor_magnet.aq2' (0x00158d0002bfa366) of endpoint 1

other not

4/30/2019, 10:47:45 PM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'lumi.sensor_magnet.aq2' (0x00158d0002bfa323) of endpoint 1
4/30/2019, 10:47:45 PM - info: MQTT publish: topic 'zigbee2mqtt/Sensore-Salone-Centrale', payload '{"contact":true,"linkquality":2}'
4/30/2019, 10:47:45 PM - debug: Received zigbee message of type 'devChange' with data '{"cid":"genOnOff","data":{"onOff":0}}' of device 'lumi.sensor_magnet.aq2' (0x00158d0002bfa323) of endpoint 1

i noted this, 
when i have paired my sensor, battery is displayed , when i have restarted my docker zigbee2mqtt, i have lost this info for some sonsor...

**Comment by Bastiencc** [comment]
take a look at this [#1450](https://github.com/Koenkk/zigbee2mqtt/issues/1450)
