### ISSUE TITLE
[New device support]: 2ch zigbee dimmer module

### ISSUE THREAD

**Issue by bertvdw** [Koenkk/zigbee2mqtt#14864]
### Link

https://nl.aliexpress.com/item/1005003693644741.html?spm=a2g0o.order_list.0.0.30bb79d2HxXo4w&gatewayAdapt=glo2nld

### Database entry

{"id":14,"type":"Router","ieeeAddr":"0xa4c1382254bc1d25","nwkAddr":60093,"manufId":4417,"manufName":"_TZ3210_3mpwqzuu","powerSource":"Mains (single phase)","modelId":"TS110E","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[4,5,3,6,8,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"61440":0,"onOff":1,"onTime":0,"moesStartUpOnOff":2}},"genLevelCtrl":{"attributes":{"61440":640,"64514":0,"64515":11,"64516":1000,"currentLevel":163}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002393377a","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b002393377a","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":257,"inClusterList":[4,5,3,6,8,61184],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"61440":0,"onOff":0,"onTime":0,"moesStartUpOnOff":2}},"genLevelCtrl":{"attributes":{"61440":1000,"64514":0,"64515":11,"64516":1000,"currentLevel":255}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002393377a","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b002393377a","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-683022859},"lastSeen":1667574407230,"useImplicitCheckin":true}

### Comments

I bought another version of  the TS1101 2ch dimmer module of Girier.
At first it was not recognised.
I copied the external converter from a previous TS1101 new device question.

Now the dimmer module is recognised. I only get a error message when i try to set the minimum brightness level

![2022-11-07 20_03_10-Window](https://user-images.githubusercontent.com/88714001/200397229-279a3e71-bd32-4471-a827-3d09534f7481.jpg)
![ScreenshotDeviceExposes](https://user-images.githubusercontent.com/88714001/200398471-ca0c2ee1-27c6-494f-b2bc-d734a2ae9fd1.jpg)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        fingerprint: [{modelID: 'TS110E', manufacturerName: '_TZ3210_3mpwqzuu'}],
        model: 'TS110E_dimmer_module_2ch',
        vendor: 'TuYa',
        description: 'Zigbee dimmer module 2 channel',
        fromZigbee: extend.light_onoff_brightness().fromZigbee.concat([fz.tuya_min_brightness]),
        toZigbee: extend.light_onoff_brightness().toZigbee.concat([tz.tuya_min_brightness]),
        exposes: [e.light_brightness().withMinBrightness().withEndpoint('l1'),
            e.light_brightness().withMinBrightness().withEndpoint('l2')],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await extend.light_onoff_brightness().configure(device, coordinatorEndpoint, logger);
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`_TZ3210_3mpwqzuu`  is already supported in z2m 1.28.2
