### ISSUE TITLE
WV704R0A0902 no Converter available

### ISSUE THREAD

**Issue by Sany-IO** [Koenkk/zigbee2mqtt#14875]
### What happened?

I have 4 Schneider Electric, pairing is successfully, and configuration is fine.

```
debug 2022-11-08 11:16:52Received Zigbee message from 'Heizkörper Kinderzimmer', type 'read', cluster 'hvacThermostat', data '["occupiedHeatingSetpoint","localTemp","pIHeatingDemand","systemMode"]' from endpoint 2 with groupID 0
debug 2022-11-08 11:16:52No converter available for 'WV704R0A0902' with cluster 'hvacThermostat' and type 'read' and data '["occupiedHeatingSetpoint","localTemp","pIHeatingDemand","systemMode"]'
debug 2022-11-08 11:16:52Received Zigbee message from 'Heizkörper Kinderzimmer', type 'read', cluster 'genBasic', data '["zclVersion"]' from endpoint 1 with groupID 0
debug 2022-11-08 11:16:54Received Zigbee message from 'Heizkörper Kinderzimmer', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ADC,1399,1395,1379,217,-32768,2100,0,0,100,217,218,224"}' from endpoint 1 with groupID 0
info 2022-11-08 11:16:54MQTT publish: topic 'zigbee2mqtt/Heizkörper Kinderzimmer', payload '{"ADC":"1399,1395,1379,217,-32768,2100,0,0,100,217,218,224","ALG":"d,1,210,217,-7,0,0,0,0,0,100","MOT":"Stall","battery":88,"elapsed":60123,"keypad_lockout":"unlock","linkquality":69,"local_temperature":21.7,"occupied_heating_setpoint":21,"pi_heating_demand":0,"voltage":2.9}'
debug 2022-11-08 11:16:54Received Zigbee message from 'Heizkörper Kinderzimmer', type 'attributeReport', cluster 'wiserDeviceInfo', data '{"deviceInfo":"ALG,d,1,210,217,-7,0,0,0,0,0,100"}' from endpoint 1 with groupID 0
info 2022-11-08 11:16:54MQTT publish: topic 'zigbee2mqtt/Heizkörper Kinderzimmer', payload '{"ADC":"1399,1395,1379,217,-32768,2100,0,0,100,217,218,224","ALG":"d,1,210,217,-7,0,0,0,0,0,100","MOT":"Stall","battery":88,"elapsed":16,"keypad_lockout":"unlock","linkquality":72,"local_temperature":21.7,"occupied_heating_setpoint":21,"pi_heating_demand":0,"voltage":2.9}'
debug 2022-11-08 11:16:54Received Zigbee message from 'Heizkörper Kinderzimmer', type 'attributeReport', cluster 'haDiagnostic', data '{"lastMessageLqi":108,"lastMessageRssi":-73}' from endpoint 1 with groupID 0
debug 2022-11-08 11:16:54Received Zigbee message from 'Heizkörper Kinderzimmer', type 'attributeReport', cluster 'haDiagnostic', data '{"57345":0}' from endpoint 1 with groupID 0
```

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

Sonoff USB

**Comment by Sany-IO** [comment]
Actually i got this error, after 1h of pairing:

error 2022-11-08 11:59:18Failed to configure 'Heizkörper Badezimmer', attempt 1 (Error: Bind 0x90fd9ffffe8e8390/1 genBasic from '0x00124b0025e15a22/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7))

**Comment by Sany-IO** [comment]
This is actually my new Device file:
`const fz = {... require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const constants = require('zigbee-herdsman-converters/lib/constants');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['iTRV'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
        model: 'WV704R0A0902', // Vendor model number, look on the device for a model number
        vendor: 'Schneider Electric', // Vendor of the device (only used for documentation and startup logging)
        description: 'Eberle/Schneider Electric TRV Fixed Version', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
        fromZigbee: [fz.ignore_basic_report, fz.ignore_haDiagnostic, fz.ignore_genOta, fz.ignore_zclversion_read,
            fz.legacy.wiser_thermostat,fz.legacy.wiser_itrv_battery, fz.hvac_user_interface, fz.wiser_device_info],
        toZigbee: [tz.thermostat_occupied_heating_setpoint, tz.thermostat_keypad_lockout], // Should be empty, unless device can be controlled (e.g. lights, switches).
        exposes: [exposes.climate().withSetpoint('occupied_heating_setpoint', 7, 30, 1).withLocalTemperature(ea.STATE).withRunningState(['idle', 'heat'], ea.STATE).withPiHeatingDemand()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint, logger) => {
            let endpoint = device.getEndpoint(1);
            const binds = ['genBasic', 'genPowerCfg', 'hvacThermostat', 'haDiagnostic'];
            await reporting.bind(endpoint, coordinatorEndpoint, binds);
            await reporting.batteryVoltage(endpoint);
            await reporting.thermostatTemperature(endpoint);
            await reporting.thermostatOccupiedHeatingSetpoint(endpoint);
            await reporting.thermostatPIHeatingDemand(endpoint);
            // bind of hvacUserInterfaceCfg fails with 'Table Full', does this have any effect?
            await endpoint.configureReporting('hvacUserInterfaceCfg', [{attribute: 'keypadLockout', reportableChange: 1,
            minimumReportInterval: constants.repInterval.MINUTE, maximumReportInterval: constants.repInterval.HOUR}]);
        }
}];`

How can i add a Converter for Endpoint 2 / hvacThermostat and systemMode ?
On Endpoint 2 and hvacThermostat is systemMode available...

Thank you!

**Comment by GSzabados** [comment]
systemMode has been removed recently as it was not working

https://github.com/Koenkk/zigbee2mqtt/issues/13582
