### ISSUE TITLE
ADEO HR-C99C-Z-C045-B

### ISSUE THREAD

**Issue by totom80** [Koenkk/zigbee2mqtt#14885]
### What happened?

New version of ADEO HR-C99C-Z-C045 in grey finition (white before)
I can pair the remote but only scenes buttons are ok on log

https://www.leroymerlin.fr/produits/electricite-domotique/domotique-et-objets-connectes/domotique/solutions-de-commande/telecommande-pour-ampoules-connectees-zigbee-lexman-enki-84372300.html?src=clk

### Zigbee2MQTT version

1.28.2-dev

### Adapter firmware version

0x26720700

### Adapter

Conbee2

### Debug log

**_After Pairing_** :

Debug 2022-11-08 15:55:59Received Zigbee message from '0xcc86ecfffea93f9c', type 'raw', cluster '65024', data '{"data":[13,119,18,116,0,10,1],"type":"Buffer"}' from endpoint 1 with groupID null
Info 2022-11-08 15:55:59MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"scene_1","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:55:59MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:55:59MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c/action', payload 'scene_1'

Debug 2022-11-08 15:57:20Received Zigbee message from '0xcc86ecfffea93f9c', type 'raw', cluster '65024', data '{"data":[13,119,18,120,0,11,1],"type":"Buffer"}' from endpoint 1 with groupID null
Info 2022-11-08 15:57:20MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"scene_2","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:57:20MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:57:20MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c/action', payload 'scene_2'

Debug 2022-11-08 15:57:52Received Zigbee message from '0xcc86ecfffea93f9c', type 'raw', cluster '65024', data '{"data":[13,119,18,121,0,12,1],"type":"Buffer"}' from endpoint 1 with groupID null
Info 2022-11-08 15:57:52MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"scene_3","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:57:52MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:57:52MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c/action', payload 'scene_3'

Debug 2022-11-08 15:58:08Received Zigbee message from '0xcc86ecfffea93f9c', type 'raw', cluster '65024', data '{"data":[13,119,18,122,0,13,1],"type":"Buffer"}' from endpoint 1 with groupID null
Info 2022-11-08 15:58:08MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"scene_4","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:58:08MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c', payload '{"action":"","battery":null,"device":{"applicationVersion":41,"dateCode":"20210524","friendlyName":"0xcc86ecfffea93f9c","hardwareVersion":2,"ieeeAddr":"0xcc86ecfffea93f9c","manufacturerID":4727,"manufacturerName":"ADEO","model":"HR-C99C-Z-C045","networkAddress":2638,"powerSource":"Battery","softwareBuildID":"2.09.03","stackVersion":6,"type":"EndDevice","zclVersion":3},"linkquality":255}'
Info 2022-11-08 15:58:08MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffea93f9c/action', payload 'scene_4'

**_When Pairing :_**

Info 2022-11-08 16:59:44Device '0xcc86ecfffea93f9c' joined
Info 2022-11-08 16:59:44MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xcc86ecfffea93f9c","ieee_address":"0xcc86ecfffea93f9c"},"type":"device_joined"}'
Info 2022-11-08 16:59:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xcc86ecfffea93f9c"},"type":"device_connected"}'
Info 2022-11-08 16:59:44MQTT publish: topic 'homeassistant/sensor/0xcc86ecfffea93f9c/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c battery","state_class":"measurement","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Info 2022-11-08 16:59:44MQTT publish: topic 'homeassistant/sensor/0xcc86ecfffea93f9c/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c action","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Info 2022-11-08 16:59:44MQTT publish: topic 'homeassistant/sensor/0xcc86ecfffea93f9c/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2022-11-08 16:59:44Starting interview of '0xcc86ecfffea93f9c'
Info 2022-11-08 16:59:44MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xcc86ecfffea93f9c","ieee_address":"0xcc86ecfffea93f9c","status":"started"},"type":"device_interview"}'
Info 2022-11-08 16:59:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0xcc86ecfffea93f9c"},"type":"pairing"}'
Debug 2022-11-08 16:59:44Received MQTT message on 'homeassistant/sensor/0xcc86ecfffea93f9c/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c battery","state_class":"measurement","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Debug 2022-11-08 16:59:44Received MQTT message on 'homeassistant/sensor/0xcc86ecfffea93f9c/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c action","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Debug 2022-11-08 16:59:44Received MQTT message on 'homeassistant/sensor/0xcc86ecfffea93f9c/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0xcc86ecfffea93f9c"],"manufacturer":"ADEO","model":"RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)","name":"0xcc86ecfffea93f9c","sw_version":"2.09.03"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","name":"0xcc86ecfffea93f9c linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0xcc86ecfffea93f9c","unique_id":"0xcc86ecfffea93f9c_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2022-11-08 16:59:45Successfully interviewed '0xcc86ecfffea93f9c', device has successfully been paired
Info 2022-11-08 16:59:45Device '0xcc86ecfffea93f9c' is supported, identified as: ADEO RGB CTT LEXMAN ENKI remote control (HR-C99C-Z-C045)
Info 2022-11-08 16:59:45MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"RGB CTT LEXMAN ENKI remote control","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["on","off","scene_1","scene_2","scene_3","scene_4","color_saturation_step_up","color_saturation_step_down","color_stop","color_hue_step_up","color_hue_step_down","color_temperature_step_up","color_temperature_step_down","brightness_step_up","brightness_step_down","brightness_stop"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HR-C99C-Z-C045","options":[{"description":"Simulate a brightness value. If this device provides a brightness_move_up or brightness_move_down action it is possible to specify the update interval and delta.","features":[{"access":2,"description":"Delta per interval, 20 by default","name":"delta","property":"delta","type":"numeric","value_min":0},{"access":2,"description":"Interval duration","name":"interval","property":"interval","type":"numeric","unit":"ms","value_min":0}],"name":"simulated_brightness","property":"simulated_brightness","type":"composite"}],"supports_ota":false,"vendor":"ADEO"},"friendly_name":"0xcc86ecfffea93f9c","ieee_address":"0xcc86ecfffea93f9c","status":"successful","supported":true},"type":"device_interview"}'
Info 2022-11-08 16:59:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"RGB CTT LEXMAN ENKI remote control","friendly_name":"0xcc86ecfffea93f9c","model":"HR-C99C-Z-C045","supported":true,"vendor":"ADEO"},"type":"pairing"}'

**Comment by LoicRivoal** [comment]
Same issue, used to work and now on the scenes buttons generate events.
