### ISSUE TITLE
After OTA Device reports old firmware version

### ISSUE THREAD

**Issue by stu1811** [Koenkk/zigbee2mqtt#14891]
### What happened?

I updated an Inovelli VZM31-SN via the OTA function from 2.06 to 2.07. The OTA screen after the update still shows 2.06. I tried doing a force remove, factory reset of the switch, and then pair. Switch included but still showed the old version. I ran the check update function again in debug and it reports the current version is 2.07.

```
Debug 2022-11-08 20:26:39Is new image available for '0x385b44fffee8eb39', current '{"fieldControl":0,"manufacturerCode":4655,"imageType":257,"fileVersion":16908807}', latest meta '{"fileVersion":16908807,"url":"[https://files.inovelli.com/firmware/VZM31-SN/Beta/2.07/VZM31-SN_2.07.ota"}'](https://files.inovelli.com/firmware/VZM31-SN/Beta/2.07/VZM31-SN_2.07.ota%22%7D%27)
Debug 2022-11-08 20:26:39Update available for '0x385b44fffee8eb39': NO
```

![image](https://user-images.githubusercontent.com/12236842/200719691-f849ea29-f37d-49c0-b63d-ad6a9b6c0818.png)

I removed the switch from Z2M again and added to ZHA. The ZHA toolkit reports the correct version.
The version numbers by ZHA and Z2M are in different bases.
16908807 = 0x1020207
![image](https://user-images.githubusercontent.com/12236842/200719800-4290b26a-d540-4bbf-80ad-3492b08232c7.png)

### What did you expect to happen?

I expected the firmware version reported after the update to be 2.07

### How to reproduce it (minimal and precise)

Update an Inovelli VZM31-SN and see if the new version is reported on the OTA page.

### Zigbee2MQTT version

 1.28.2

### Adapter firmware version

20220928

### Adapter

Sonoff USB Dongle 3.0 - P

**Comment by epower53** [comment]
I see similar, but slightly different behavior. Running 1.28.2 in standalone mode. Whenever Inovelli pushes a firmware update, I see 1 revision previous. For example, they pushed 2.06, and my z2m UI reported 2.05 was available. Now that 2.07 is published, I was able to update to 2.06, which my z2m UI claims is the latest. Using the debug console confirms that my switch has 2.06 installed, now.

**Comment by ThreeFN** [comment]
I have discovered a kludgy work around.  I can confirm this solution works for Inovelli and IKEA devices.

1. From the dev console for the device select genBasic / swBuildId and read the value (returns the correct firmware version below).
2. from the device 'main page' select the yellow 'reconfigure' button.  The correct firmware version and build date will show.

Not sure how this is diagnostic to the bug in Z2M.  Completing either step 1 or 2 on their own will not update the firmware version to the correct number, only doing the dev console then reconfig in that order will cause the main page to update.

**Comment by stu1811** [comment]
> I have discovered a kludgy work around.  I can confirm this solution works for Inovelli and IKEA devices.
> 
> 1. From the dev console for the device select genBasic / swBuildId and read the value (returns the correct firmware version below).
> 2. from the device 'main page' select the yellow 'reconfigure' button.  The correct firmware version and build date will show.
> 
> Not sure how this is diagnostic to the bug in Z2M.  Completing either step 1 or 2 on their own will not update the firmware version to the correct number, only doing the dev console then reconfig in that order will cause the main page to update.

That worked for my Inovelli too. Thanks!

**Comment by KennethLavrsen** [comment]
For the 4 button Philips Hue remote I had 2 of 5 showing the symptom. I uograded then multiple times and the version appeared to be the old. My theory us that the remotes are upgraded but not booting to the new image.

So what fixed it for both was to reset the remotes first which for the Hue switches is holding all 4 buttons down for 10 seconds. And once reconnected I could do an interview using the blue i button followed by a reconfigure. And then finally they were on latest revision.

**Comment by Morasta** [comment]
This version display issue is still happening for firmware 3.04 with some freshly upgraded original release switches after a manual firmware flash. Noting the manual querying of the version still works. However, it'd be nice if we could figure out a resolution for the issue.
