### ISSUE TITLE
STYRBAR remote control - no power value after changing batteries

### ISSUE THREAD

**Issue by jtbgroup** [Koenkk/zigbee2mqtt#14893]
### What happened?

Hi,

The batteries of my remote control were empty, so I changed them. I could directly use it again and all the MQTT messages were sent as it should. But the power value was still 0. 

To get the correct value, I had to remove and pair the device again. 

### What did you expect to happen?

I expected a correct battery value after changing the batteries

### Zigbee2MQTT version

1.28.2 commit: 360a777

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by mdehaas** [comment]
I have seen this behavior with other IKEA remotes and feel this is a problem in the implantation of the device (No GET/SET possible according to [the documentation](https://www.zigbee2mqtt.io/devices/E2001_E2002.html#battery-numeric)). So I think this is not something Z2M is to blame for.
