### ISSUE TITLE
Problem Updating Sylvania Smart+ A19 RGBW Firmware Model 73693

### ISSUE THREAD

**Issue by coolspot18** [Koenkk/zigbee2mqtt#14901]
### What happened?

When I click the Check for New Firmware button, I get the following error:

![image](https://user-images.githubusercontent.com/5160442/200916701-9bd92a9c-7cc8-4337-9bf2-051b4e38ea73.png)

`Debug 2022-11-09 13:47:36Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"Family Room Light","transaction":"h4va3-4"}'
Info 2022-11-09 13:47:36Checking if update available for 'Family Room Light'
Debug 2022-11-09 13:47:36Check if update available for '0x7cb03eaa00a5de09' (LIGHTIFY A19 RGBW)
Debug 2022-11-09 13:47:36Using endpoint '3'
Debug 2022-11-09 13:47:36Received Zigbee message from 'Family Room Light', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16909458,"imageType":24,"manufacturerCode":4364}' from endpoint 3 with groupID 0
Debug 2022-11-09 13:47:36Got OTA request '{"fieldControl":0,"manufacturerCode":4364,"imageType":24,"fileVersion":16909458}'
Info 2022-11-09 13:47:37MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Family Room Light"},"error":"Failed to check if update available for 'Family Room Light' (No image available for manufacturerCode '4364' imageType '24')","status":"error","transaction":"h4va3-4"}'
Error 2022-11-09 13:47:37Failed to check if update available for 'Family Room Light' (No image available for manufacturerCode '4364' imageType '24')
Debug 2022-11-09 13:47:37AssertionError [ERR_ASSERTION]: No image available for manufacturerCode '4364' imageType '24' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/ledvance.js:17:5) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:265:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:256:23) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:192:39)`

Any ideas why Zigbee2MQTT is throwing an error?

![image](https://user-images.githubusercontent.com/5160442/200916392-f0ebc743-cbeb-485b-822d-fc4ec63883dc.png)

### What did you expect to happen?

Return the status of new firmware if available or not.

### How to reproduce it (minimal and precise)

1. Click Check Firmware Button.

### Zigbee2MQTT version

 1.28.2

### Adapter firmware version

20220219

### Adapter

Sonoff zbdongle-p adapter zigbee 3.0

### Debug log

`Debug 2022-11-09 13:47:36Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"Family Room Light","transaction":"h4va3-4"}'
Info 2022-11-09 13:47:36Checking if update available for 'Family Room Light'
Debug 2022-11-09 13:47:36Check if update available for '0x7cb03eaa00a5de09' (LIGHTIFY A19 RGBW)
Debug 2022-11-09 13:47:36Using endpoint '3'
Debug 2022-11-09 13:47:36Received Zigbee message from 'Family Room Light', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16909458,"imageType":24,"manufacturerCode":4364}' from endpoint 3 with groupID 0
Debug 2022-11-09 13:47:36Got OTA request '{"fieldControl":0,"manufacturerCode":4364,"imageType":24,"fileVersion":16909458}'
Info 2022-11-09 13:47:37MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Family Room Light"},"error":"Failed to check if update available for 'Family Room Light' (No image available for manufacturerCode '4364' imageType '24')","status":"error","transaction":"h4va3-4"}'
Error 2022-11-09 13:47:37Failed to check if update available for 'Family Room Light' (No image available for manufacturerCode '4364' imageType '24')
Debug 2022-11-09 13:47:37AssertionError [ERR_ASSERTION]: No image available for manufacturerCode '4364' imageType '24' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/ledvance.js:17:5) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:265:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:256:23) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:192:39)`

**Comment by Koenkk** [comment]
This means that no FW is available for this device (none at all)
