### ISSUE TITLE
MOES BRT-100-TRV doesn't update valve position

### ISSUE THREAD

**Issue by Ivano62** [Koenkk/zigbee2mqtt#14909]
### What happened?

When the room temperature drops below the set point the valve opens, the "valve_state" attribute changes value from CLOSED to OPEN, but the opening percentage, "position" attribute, remains fixed at **0%**.
Before version 1.28.2 everything worked fine
![MOES BRT-100-TRV](https://user-images.githubusercontent.com/43061741/200939815-4155a255-9762-45e5-b029-b9badfa004d7.png)

### What did you expect to happen?

The "position" attribute indicates the valve opening percentage

### Zigbee2MQTT version

1.28.2-dev commit: 672da64

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by catalinescu-sudo** [comment]
Hi, please take a look at my issue https://github.com/Koenkk/zigbee2mqtt/issues/14940 do you have the same problem? Thank you!

Regarding your issue I can tell that my valve position is getting updated
<img width="406" alt="Screenshot 2022-11-13 at 00 49 36" src="https://user-images.githubusercontent.com/64982743/201497579-814f2a54-ae6f-45a3-be48-18cbcfa171af.png">

**Comment by Ivano62** [comment]
After latest update position seems working correctly.

**Comment by harristom** [comment]
I see a similar issue - valve is reported as closed but with position 25%

![image](https://user-images.githubusercontent.com/51212431/208321850-1bf3b669-30fd-4ddb-b466-f0dee6e94e9c.png)

**Comment by almirus** [comment]
Is it normal behavior to frequently turn on and off?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16898685/7737c00a-b40a-4d45-9423-2597d53b2f01)
