### ISSUE TITLE
Must restart z2m after a coordinator or lan router reboot.

### ISSUE THREAD

**Issue by JackTalisker** [Koenkk/zigbee2mqtt#14944]
### What happened?

With recent releases, if for some reason I have to restart my wifi router or simply restarting the coordinator, z2m lose its devices and must be restarted to regain control. 
This did not happen until recently.

### What did you expect to happen?

a z2m normal behaviour after a network or coordinator reboot.

### How to reproduce it (minimal and precise)

Reboot the router or the coordinator (e.g. after a firmware upgrade). Z2m loses control over its devices,
Have to restart z2m.

Debug log attached with z2m manual restart at 14:15:52

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

6.7.9.0 build 405

### Adapter

Sonoff ZBBridge Tasmota flashed

### Debug log

Debug 2022-11-12 14:13:37Received MQTT message on 'zigbee2mqtt/wayang/set' with data 'ON'
Debug 2022-11-12 14:13:37Publishing 'set' 'state' to 'wayang'
Debug 2022-11-12 14:13:38Received MQTT message on 'zigbee2mqtt/wayang/set' with data 'OFF'
Debug 2022-11-12 14:13:38Publishing 'set' 'state' to 'wayang'
Error 2022-11-12 14:13:39Publish 'set' 'state' to 'wayang' failed: 'Error: Command 0x7cb03eaa0a083cab/3 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
Debug 2022-11-12 14:13:39Error: Command 0x7cb03eaa0a083cab/3 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:465:19) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Info 2022-11-12 14:13:39MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'wayang' failed: 'Error: Command 0x7cb03eaa0a083cab/3 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (sendZclFrameToEndpointInternal error)'","meta":{"friendly_name":"wayang"},"type":"zigbee_publish_error"}'
Error 2022-11-12 14:13:41Publish 'set' 'state' to 'wayang' failed: 'Error: Command 0x7cb03eaa0a083cab/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
Debug 2022-11-12 14:13:41Error: Command 0x7cb03eaa0a083cab/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:465:19) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Info 2022-11-12 14:13:41MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'wayang' failed: 'Error: Command 0x7cb03eaa0a083cab/3 genOnOff.off({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (sendZclFrameToEndpointInternal error)'","meta":{"friendly_name":"wayang"},"type":"zigbee_publish_error"}'
Warning 2022-11-12 14:13:48Failed to ping 'lumino' (attempt 1/2, Read 0x7cb03eaa0a083b12/3 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
Warning 2022-11-12 14:13:53Failed to ping 'lumino' (attempt 2/2, Read 0x7cb03eaa0a083b12/3 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
Debug 2022-11-12 14:13:56Active device 'lumino' was last seen '1.50' minutes ago.
Debug 2022-11-12 14:13:56Device 'lumino' reconnected
Info 2022-11-12 14:13:56MQTT publish: topic 'zigbee2mqtt/lumino/availability', payload 'online'
Debug 2022-11-12 14:13:58Retrieving state of 'lumino' after reconnect
Error 2022-11-12 14:14:00Failed to read state of 'lumino' after reconnect (Read 0x7cb03eaa0a083b12/3 genOnOff(["onOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
Warning 2022-11-12 14:14:02Failed to ping 'wayang' (attempt 1/2, Read 0x7cb03eaa0a083cab/3 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
Warning 2022-11-12 14:14:07Failed to ping 'wayang' (attempt 2/2, Read 0x7cb03eaa0a083cab/3 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
Debug 2022-11-12 14:14:10Active device 'wayang' was last seen '10.25' minutes ago.
Info 2022-11-12 14:14:10MQTT publish: topic 'zigbee2mqtt/wayang/availability', payload 'offline'
Debug 2022-11-12 14:14:36Received MQTT message on 'zigbee2mqtt/sala_2/set' with data '{"state":"ON"}'
Debug 2022-11-12 14:14:36Publishing 'set' 'state' to 'sala_2'
Error 2022-11-12 14:14:38Publish 'set' 'state' to 'sala_2' failed: 'Error: Command 0xd0cf5efffef13574/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
Debug 2022-11-12 14:14:38Error: Command 0xd0cf5efffef13574/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:465:19) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Info 2022-11-12 14:14:38MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'sala_2' failed: 'Error: Command 0xd0cf5efffef13574/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (sendZclFrameToEndpointInternal error)'","meta":{"friendly_name":"sala_2"},"type":"zigbee_publish_error"}'
Debug 2022-11-12 14:14:39Saving state to file /app/data/state.json
Debug 2022-11-12 14:15:52Received MQTT message on 'zigbee2mqtt/bridge/request/restart' with data '{"transaction":"s2sce-1"}'
Info 2022-11-12 14:15:52Restarting Zigbee2MQTT
Info 2022-11-12 14:15:52MQTT publish: topic 'zigbee2mqtt/bridge/response/restart', payload '{"data":{},"status":"ok","transaction":"s2sce-1"}'
Debug 2022-11-12 14:16:07Retrieving state of 'luce_ingresso' after reconnect
Debug 2022-11-12 14:16:07Received Zigbee message from 'luce_ingresso', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info 2022-11-12 14:16:07MQTT publish: topic 'zigbee2mqtt/luce_ingresso', payload '{"brightness":254,"color_mode":"color_temp","color_temp":402,"last_seen":"2022-11-12T13:16:06.086Z","linkquality":160,"power_on_behavior":"off","state":"OFF","update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:08Received Zigbee message from 'wayang', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 3 with groupID 0
Debug 2022-11-12 14:16:08Device 'wayang' reconnected
Info 2022-11-12 14:16:08MQTT publish: topic 'zigbee2mqtt/wayang/availability', payload 'online'
Info 2022-11-12 14:16:08MQTT publish: topic 'zigbee2mqtt/wayang', payload '{"last_seen":"2022-11-12T13:16:06.350Z","linkquality":120,"state":"OFF","update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:08Succesfully pinged 'wayang' (attempt 1/1)
Debug 2022-11-12 14:16:10Retrieving state of 'wayang' after reconnect
Debug 2022-11-12 14:16:10Received Zigbee message from 'wayang', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 3 with groupID 0
Info 2022-11-12 14:16:10MQTT publish: topic 'zigbee2mqtt/wayang', payload '{"last_seen":"2022-11-12T13:16:08.522Z","linkquality":116,"state":"OFF","update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:10Received Zigbee message from 'cippalippa', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-11-12 14:16:10Device 'cippalippa' reconnected
Info 2022-11-12 14:16:10MQTT publish: topic 'zigbee2mqtt/cippalippa/availability', payload 'online'
Info 2022-11-12 14:16:10MQTT publish: topic 'zigbee2mqtt/cippalippa', payload '{"last_seen":"2022-11-12T13:16:08.836Z","linkquality":100,"state":"OFF"}'
Debug 2022-11-12 14:16:10Succesfully pinged 'cippalippa' (attempt 1/1)
Debug 2022-11-12 14:16:12Retrieving state of 'cippalippa' after reconnect
Debug 2022-11-12 14:16:12Received Zigbee message from 'cippalippa', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info 2022-11-12 14:16:12MQTT publish: topic 'zigbee2mqtt/cippalippa', payload '{"last_seen":"2022-11-12T13:16:11.082Z","linkquality":96,"state":"OFF"}'
Debug 2022-11-12 14:16:12Received Zigbee message from 'repeater_letto', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2022-11-12 14:16:12Device 'repeater_letto' reconnected
Info 2022-11-12 14:16:12MQTT publish: topic 'zigbee2mqtt/repeater_letto/availability', payload 'online'
Info 2022-11-12 14:16:12MQTT publish: topic 'zigbee2mqtt/repeater_letto', payload '{"last_seen":"2022-11-12T13:16:11.104Z","linkquality":144,"update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:12Succesfully pinged 'repeater_letto' (attempt 1/1)
Debug 2022-11-12 14:16:14Retrieving state of 'repeater_letto' after reconnect
Debug 2022-11-12 14:16:35Received MQTT message on 'zigbee2mqtt/sala_2/set' with data '{"state":"ON"}'
Debug 2022-11-12 14:16:35Publishing 'set' 'state' to 'sala_2'
Info 2022-11-12 14:16:35MQTT publish: topic 'zigbee2mqtt/sala_2', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"last_seen":"2022-11-12T13:16:33.814Z","linkquality":224,"power_on_behavior":null,"state":"OFF","update":{"state":"idle"},"update_available":false}'
Info 2022-11-12 14:16:35MQTT publish: topic 'zigbee2mqtt/sala_2', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"last_seen":"2022-11-12T13:16:33.814Z","linkquality":224,"power_on_behavior":null,"state":"ON","update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:36Received MQTT message on 'zigbee2mqtt/sala_2/set' with data '{"state":"OFF"}'
Debug 2022-11-12 14:16:36Publishing 'set' 'state' to 'sala_2'
Info 2022-11-12 14:16:37MQTT publish: topic 'zigbee2mqtt/sala_2', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"last_seen":"2022-11-12T13:16:35.335Z","linkquality":220,"power_on_behavior":null,"state":"ON","update":{"state":"idle"},"update_available":false}'
Info 2022-11-12 14:16:37MQTT publish: topic 'zigbee2mqtt/sala_2', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"last_seen":"2022-11-12T13:16:35.335Z","linkquality":220,"power_on_behavior":null,"state":"OFF","update":{"state":"idle"},"update_available":false}'
Debug 2022-11-12 14:16:38Received Zigbee message from 'cc2531', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 8 with groupID 0
Info 2022-11-12 14:16:38MQTT publish: topic 'zigbee2mqtt/cc2531', payload '{"last_seen":"2022-11-12T13:16:37.134Z","led":true,"linkquality":100}'

**Comment by JackTalisker** [comment]
That is a problem since my wifi router is scheduled for reboot once a week...

**Comment by Hedda** [comment]
Also FYI, keep in mind that the EZSP support is currently experimental, so you can follow and try to help the ezsp developer here:

https://github.com/Koenkk/zigbee-herdsman/issues/319
