### ISSUE TITLE
TV02-Zigbee incorrectly shows the temperature in automatic mode.

### ISSUE THREAD

**Issue by iksrd** [Koenkk/zigbee2mqtt#14947]
### What happened?

TV02-Zigbee incorrectly shows the temperature in automatic mode. The following schedule is set 04:00/22 09:00/21.5 18:00/22 21:30/21 24:00/21. In reality, the temperature does not match the schedule. It feels like time is jumping.
![2022-11-12_19-47-50](https://user-images.githubusercontent.com/81743791/201485090-0289e0bd-9f50-40b5-b55a-dc3190af9429.png)
![2022-11-12_19-52-13](https://user-images.githubusercontent.com/81743791/201485203-9137b580-32bf-426a-9239-902b3d864af4.png)

### What did you expect to happen?

When the schedule is running automatically, it corresponds to the set time.

### How to reproduce it (minimal and precise)

Set up a schedule with different temperatures for different times and observe

### Zigbee2MQTT version

 1.28.2

### Adapter firmware version

 20211217

### Adapter

zStack3x0

**Comment by vladyspavlov** [comment]
Could you please provide the manufacturer ID of your TRV?

**Comment by iksrd** [comment]
TS0601
_TZE200_e9ba97v

**Comment by vladyspavlov** [comment]
Does the time set on TRV match your real time? I can't reproduce it on my TRV with the same manuf id.

**Comment by iksrd** [comment]
Yes, the time corresponds. I recently reset the thermal heads to the factory state.

**Comment by iksrd** [comment]
I'll check, in my opinion I just misunderstood the principle of the schedule.
