### ISSUE TITLE
State update not reported in mqtt (and logs), although the device sends a new state

### ISSUE THREAD

**Issue by ingar195** [Koenkk/zigbee2mqtt#14968]
### What happened?

z2m is not sending any message if the state is the same as you are trying to change it to. no trace of it in the logs or in MQTT messages 

I know this device is sending this message because I used it in zha for automation before migrating to z2m

I'm using this device:
[WDE002386 ](https://www.zigbee2mqtt.io/devices/WDE002386.html#schneider%2520electric-wde002386)

### What did you expect to happen?

Expected all Zigbee events to be passed to MQTT, even if the state is on the same as the button press 

### How to reproduce it (minimal and precise)

have a light that's on then press the physical on button
then nothing will appear in the logs or in MQTT

Also tested on the latest dev docker image

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

0x26780700

### Adapter

Conbee II

**Comment by ingar195** [comment]
Can this be reopned

**Comment by ingar195** [comment]
@Koenkk sorry for tagging, I know this is an issue since the switches sent this message with ZHA. have verified with  DEBUG=zigbee-herdsman* environment var enabled nothing in logs.

**Comment by Cyberfly100** [comment]
I think I have the same problem, too.
