### ISSUE TITLE
Moes Thermostat can only set whole degrees

### ISSUE THREAD

**Issue by PulsarFX** [Koenkk/zigbee2mqtt#14965]
### What happened?

Temperature target value for the [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb)  is reported in whole degrees and can only be set as whole degrees, whereas the device reports and changes in .5 degree steps. 

### What did you expect to happen?

I'd like to see and set current_heating_setpoint in .5 degree steps via mqtt like it is possible at the device itself. 

### How to reproduce it (minimal and precise)

Try to set a temperature for current_heating_setpoint with .5 degrees. 

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus,TI CC2652P

**Comment by PulsarFX** [comment]
Is there a way to test it with a different definition?
In z2m gui I can also set only whole degrees. Does it ise the same definition?

**Comment by cambro1995** [comment]
Same problem with MOES [BHT-002-GCLZB]

**Comment by TTR6214** [comment]
I also confirm that we cannot step by 0.5 degree for MOES BRT-100-TRV.

**Comment by PulsarFX** [comment]
So I started digging around and found this:

my model starts here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/moes.js#L98
and states:
`fromZigbee: [fz.moes_thermostat],`

which is:
`const fz = require('../converters/fromZigbee');`

this is where the settings for moes_thermostat starts:
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L3896
relevant snippet for local temp:
```
  case tuya.dataPoints.moesLocalTemp:
      temperature = value & 1<<15 ? value - (1<<16) + 1 : value;
      if (!['_TZE200_ztvwu4nk', '_TZE200_ye5jkfsb'].includes(meta.device.manufacturerName)) {
          // https://github.com/Koenkk/zigbee2mqtt/issues/11980
          temperature = temperature / 10;
      }

      return {local_temperature: parseFloat(temperature.toFixed(1))};
```

relevant snippet for heating setpoint:
```
case tuya.dataPoints.moesHeatingSetpoint:
    return {current_heating_setpoint: value};
```

my question is: 
- is fromZigbee.js right to convert heatingSetpoint as non-float? 
- is there a way to see the raw zigbee message from the thermostat to verify incoming data?

**Comment by PulsarFX** [comment]
has anyone tested this thermostat with the smartlife/tuya/moes app if .5°C is possible there? MOES support wants me to show them with their app, that I can only set 1C steps...

**Comment by Ivano62** [comment]
On MOES BRT-100-TRV With physical input on the device the step is 0.5 °C, I don't use app

**Comment by PulsarFX** [comment]
Yes, that's why I contacted support, as the display accepts .5C steps whereas zigbee can only set 1C steps. The question is: is it a zigbee2mqtt issue or a general issue with the device?

**Comment by PulsarFX** [comment]
Moes support states, that the thermostat can be set in .5C steps via Smartlife or their app.

**Comment by osnwt** [comment]
Anyone has Tuya app to verify? I have no Tuya hub yet, so can't try myself.
Perhaps, this TRV has firmware update, but it isn't shown in Z2M. Maybe it will work with original Tuya app, and after update we would have better position reporting and proper setpoint option?..

**Comment by PulsarFX** [comment]
I bought the moes wireless zigbee hub and connected it with one of my thermostats.
Guess what: smartlife app only allows to set whole degrees, too.  >:-(
The thermostat reports these versions:
zigbee module 1.0.8
mcu model: 2.0.1

**Comment by osnwt** [comment]
Sad...

**Comment by PulsarFX** [comment]
I've sent a Video to moes support and got this response:

"I  checked with TUYA team,zigbee thermostat can only set the temperature according to 1 C at present.
Wifi thermostat can set 0.5C,hope you understand.
I will apply for TUYA engineer to improve this function in the future."

Let's hope they get this fixed.
For now there is nothing z2m can do to improve the implementation.

**Comment by guny74** [comment]
Very strage, because via program e.g.  "weekdays_pX_temperature" it is possible to set .5 Degrees values...why not for setpoint ?!

**Comment by PulsarFX** [comment]
A year later, I asked again (also with the hint, that the program schedule can set .5 degrees) and got this reply from support :
"This is indeed a fixed specification parameter of graffiti technology at present.
We have also submitted an application, and hope that they can revise this problem as soon as possible after reviewing it. Thank you for your feedback again."

Honestly, I don't understand what they are trying to say :-D

**Comment by PulsarFX** [comment]
@ all subscribers: please see #19991 and check your device code
