### ISSUE TITLE
MAC no ACK for 88+ devices

### ISSUE THREAD

**Issue by NikitaKorneev** [Koenkk/zigbee2mqtt#14971]
### What happened?

Recently I finished renovations and installed all of around 80 magnetic track zigbee lights based on Tuya. 

I wrote external converter, turned on pairing and just powered on the whole house. 

Some joined, some failed. I re-paired them manually. 

Two days have passed and they worked fine, but tonight I was not able to control any of them with the following error on all of them:

2022-11-14 01:47:44Publish 'set' 'state' to 'bigbathroom_down_1' failed: 'Error: Command 0xe0798dfffece1c1e/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'

When I power them off and power back on they come online after a while.

Any ideas what might be the problem?

![image](https://user-images.githubusercontent.com/60179299/201548732-2f5b2ae2-811d-407a-9bfd-5a09374339d5.png)

![image](https://user-images.githubusercontent.com/60179299/201548739-99f165d7-a7b9-4da8-94c2-f51beb2e7398.png)

External converter:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0502B', manufacturerName: '_TZ3210_okcysjdv'}],
        model: 'TS0502B', 
        vendor: 'TuYa', 
        description: 'Zigbee track and spot lights from MSR company.', 
        extend: extend.light_onoff_brightness_colortemp(),
};

module.exports = definition;
```

### What did you expect to happen?

Control all the devices constantly without any problem

### How to reproduce it (minimal and precise)

Set up Z2M, connect 70+ Tuna lights at once, wait couple of days.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20211217

### Adapter

Egony Stick V4

**Comment by precchia** [comment]
Hello. Just to tell, I got exactly the same error on a set of router devices:

2025-01-10 14:53:44z2m: Failed to ping 'sw4' (attempt 1/1, ZCL command 0xa4c1380caedbe668/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
warning 2025-01-10 14:54:39z2m: Failed to ping 'sw3' (attempt 1/1, ZCL command 0x84b4dbfffefec2ef/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
warning 2025-01-10 14:56:02z2m: Failed to ping 'lampe bureau' (attempt 1/1, ZCL command 0xf4b3b1fffec3f386/1 genBasic.read(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
