### ISSUE TITLE
WXKG01LM reports long_release instead of single click

### ISSUE THREAD

**Issue by scasic** [Koenkk/zigbee2mqtt#1501]
Could you please clarify how click event is being identified for WXKG01LM?

When I push the button which is close to coordinator I get click:single in the log:
`zigbee2mqtt:info 5/5/2019, 2:34:40 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00016d8a67', payload '{"linkquality":123,"duration":86,"battery":100,"voltage":3022,"click":"single"}'`

But when I move button to the longer distance where linkquality is around 0 and push it again I get click:long or click:long_release:
`  zigbee2mqtt:info 5/5/2019, 2:36:08 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00016d8a67', payload '{"linkquality":0,"duration":41,"battery":100,"voltage":3022,"click":"long_release"}'`

I thought type of event is being sent by button itself. Am I wrong?

**Comment by Koenkk** [comment]
This message is not send by the device. I've added an extra option, see: https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/configuration/device_specific_configuration.md#wxkg01lm
