### ISSUE TITLE
[New device support]: 45856GE Energy Monitoring Missing

### ISSUE THREAD

**Issue by coolspot18** [Koenkk/zigbee2mqtt#15014]
### Link

https://www.zigbee2mqtt.io/devices/45856GE.html

### Database entry

{ 	"id": 33, 	"type": "Router", 	"ieeeAddr": "0x0022a300002535d9", 	"nwkAddr": 62324, 	"manufId": 4388, 	"manufName": "Jasco Products", 	"powerSource": "Mains (single phase)", 	"modelId": "45856", 	"epList": [1, 2], 	"endpoints": { 		"1": { 			"profId": 260, 			"epId": 1, 			"devId": 256, 			"inClusterList": [0, 3, 4, 5, 6, 2821, 1794], 			"outClusterList": [10, 25], 			"clusters": { 				"genBasic": { 					"attributes": { 						"modelId": "45856", 						"manufacturerName": "Jasco Products", 						"powerSource": 1, 						"zclVersion": 1, 						"appVersion": 18, 						"stackVersion": 80, 						"hwVersion": 1 					} 				} 			}, 			"binds": [{ 				"cluster": 6, 				"type": "endpoint", 				"deviceIeeeAddress": "0x00124b0026b698e5", 				"endpointID": 1 			}], 			"configuredReportings": [{ 				"cluster": 6, 				"attrId": 0, 				"minRepIntval": 0, 				"maxRepIntval": 3600, 				"repChange": 0 			}], 			"meta": {} 		}, 		"2": { 			"profId": 260, 			"epId": 2, 			"devId": 259, 			"inClusterList": [0, 3, 2821], 			"outClusterList": [3, 6], 			"clusters": { 				"genBasic": { 					"attributes": {} 				} 			}, 			"binds": [], 			"configuredReportings": [], 			"meta": {} 		} 	}, 	"appVersion": 18, 	"stackVersion": 80, 	"hwVersion": 1, 	"zclVersion": 1, 	"interviewCompleted": true, 	"meta": { 		"configured": 1 	}, 	"lastSeen": 1668590701451, 	"defaultSendRequestWhen": "immediate" }

### Comments

This device is supported for basic on/off, but energy monitoring information is not reported by Zigbee2MQTT. 

According to the BlackAdder documentation, deConz supports energy monitoring.

Is it possible to have energy information added to Z2M?

### External converter

I wrote this external converter, and it seems Watts and Energy is being recorded:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    zigbeeModel: ['45856'],
    model: '45856GE',
    vendor: 'Jasco Products',
    description: 'GE ZigBee In-Wall On/Off Smart Switch with Energy Monitoring and HA1.2 Certification',
    fromZigbee: [fz.on_off, fz.metering],
    toZigbee: [tz.on_off],
    exposes: [e.switch(), e.energy(), e.power()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
        await reporting.instantaneousDemand(endpoint);
        await reporting.currentSummDelivered(endpoint);
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 10000, multiplier: 1});
    },
};
 
module.exports = definition;
```

Perhaps someone can check it over and see if it is correct.

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by coolspot18** [comment]
> Added, thanks!
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Hi @Koenkk I noticed OnOff reporting is not enabled on the switch, but even though I added it to the converter? The convert might need a small fix.

![image](https://user-images.githubusercontent.com/5160442/202657753-8b389142-1e8f-4f52-a041-1969af93e60c.png)

**Comment by Koenkk** [comment]
The onOff reporting was not in your converter, only the bind. I added it now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
