### ISSUE TITLE
Silvercrest HG08673-FR - Not Supported

### ISSUE THREAD

**Issue by Kuliss9** [Koenkk/zigbee2mqtt#15013]
### What happened?

I bought in Lidl shop 2 Silvercrest HG086373-FR smart plugs which should be supported. Unfortunately after pairing it showed me NOT SUPPORTED.

I use Loxberry plug-in version 1.6.0. with Zigbee2Mqtt version 1.28.0 and adapter zigbee CC2652P.

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

Dont know

### Adapter

zigbee CC2652P 

### Debug log

![Snímek obrazovky 2022-11-16 v 10 23 51](https://user-images.githubusercontent.com/118347297/202141208-334ccf7a-2bbe-403e-a02b-33e55f6fe0ff.png)

![Snímek obrazovky 2022-11-16 v 10 24 21](https://user-images.githubusercontent.com/118347297/202141310-5a332697-9d37-47dd-984e-d2aa9d6dad03.png)

**Comment by danieledwardgeorgehitchcock** [comment]
This was indeed added to the Z2M codebase back in August / September time see Koenkk/zigbee-herdsman-converters@5c870fe0c2324800a957d1e809dd491ad6e0338b

Are you using an up-to-date version of Z2M? - Please post a screenshot of the Settings->About tab in the GUI

**Comment by Kuliss9** [comment]
I use last version of Loxberry plugin for Loxone SmartHome - https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/releases/tag/1.6.0

![Snímek obrazovky 2022-11-16 v 12 01 54](https://user-images.githubusercontent.com/118347297/202163591-11ab3bcc-9988-4919-a83c-bc05ba2ecee6.png)

**Comment by nathan-gs** [comment]
These are supported from 1.28.1, see the changelog: https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.1

**Comment by Kuliss9** [comment]
Thanks a lot. Do you know if there is any way how to update Z2M version without new release of Loxberry plugin?

**Comment by danieledwardgeorgehitchcock** [comment]
Please could you close this issue?
