### ISSUE TITLE
Legrand 600086 (067776): the position is not updated either !

### ISSUE THREAD

**Issue by novisys** [Koenkk/zigbee2mqtt#15010]
### What happened?

        @Koenkk 
I tested under docker on the image koenkk/zigbee2mqtt:latest-dev and it does not work. 
Initial status with the shutter open:
![image](https://user-images.githubusercontent.com/30829631/185426841-8416efc1-9ec0-4bce-90e0-3eb8e0ba10a6.png)

When I click on the closed button:
![image](https://user-images.githubusercontent.com/30829631/185427186-fcd4c68e-5b99-4f8b-bd89-6fc8dbf421f1.png)

When I click on the synchronization button:
![image](https://user-images.githubusercontent.com/30829631/185427432-b5a462a3-a158-4dfb-9af6-c6e4716867d8.png)

_Originally posted by @Alindil in https://github.com/Koenkk/zigbee2mqtt/issues/13566#issuecomment-1219599525_
     Still have the same problem, any update about this ?
Thanks

### Zigbee2MQTT version

1.28.2-1

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by novisys** [comment]
Any help ? @Koenkk

**Comment by Koenkk** [comment]
Can you try changing the reporting of `currentPositionLiftPercentage` of the `closuresWindowCovering` in the "reporting" tab of the device?

**Comment by novisys** [comment]
> Can you try changing the reporting of `currentPositionLiftPercentage` of the `closuresWindowCovering` in the "reporting" tab of the device?

hi, thanks for the response
but this option don't exist on the list of the Closures Options 
i have: 
- windowCoverrigType
- windowCoverrigMode

**Comment by novisys** [comment]
Here is the options possible and working on ConsoleDev:
`2022-11-20 12:23:22Read result of 'closuresWindowCovering': {"windowCoveringMode":0,"windowCoveringType":2,"configStatus":3,"currentPositionLiftPercentage":0,"installedOpenLimitLiftCm":0,"installedClosedLimitLiftCm":65535}`
<img width="1380" alt="Capture d’écran 2022-11-20 à 12 23 55" src="https://user-images.githubusercontent.com/35895513/202899375-0e6c6fa5-a208-423f-9c48-8559f727484f.png">

**Comment by Koenkk** [comment]
Not the dev tab but the reporting one

**Comment by novisys** [comment]
> Not the dev tab but the reporting one

I know !
to be more clear, here is a screenshot withe error get when trying to change to the value you telled:
<img width="1438" alt="Capture d’écran 2022-11-20 à 18 52 05" src="https://user-images.githubusercontent.com/35895513/202917970-6fe9cf7f-89e8-4da5-9b38-2ada2169f84a.png">
<img width="1412" alt="Capture d’écran 2022-11-20 à 18 54 58" src="https://user-images.githubusercontent.com/35895513/202917972-cb0ddb69-0365-445f-a72e-8464d932b13a.png">
<img width="1428" alt="Capture d’écran 2022-11-20 à 18 55 23" src="https://user-images.githubusercontent.com/35895513/202917973-41532fcd-90a3-4775-9ff7-5e08a81bb364.png">

**Comment by Koenkk** [comment]
Seems this cover cannot reports its position. One thing we can do is to always return position 0 when you send CLOSE and 100 when you send OPEN.

**Comment by novisys** [comment]
> Seems this cover cannot reports its position. One thing we can do is to always return position 0 when you send CLOSE and 100 when you send OPEN.

you are true,
i passed my week learning Legrand documentation and other Deconz ressources and conclude that this one don't support position %  👎
