### ISSUE TITLE
Sonoff SNZB-04 devices leave network 256 minutes after last activity.

### ISSUE THREAD

**Issue by SeanCline** [Koenkk/zigbee2mqtt#15027]
### What happened?

I have a very small network of 4 devices connected to a [Sonoff ZBDongle-E](https://www.zigbee2mqtt.io/guide/adapters/#based-on-silicon-labs-efr32mg2x-mgm21x-and-efr32mg1x-mgm1x-series). The two [Sonoff SNZB-01](https://www.zigbee2mqtt.io/devices/SNZB-01.html) buttons have been rock solid, but the [Sonoff SNZB-04](https://www.zigbee2mqtt.io/devices/SNZB-04.html) contact sensors periodically fall off the network. This happens about once a day and the SNZB-04's need to be re-paired with the coordinator each time.

Below, I've attached the full zigbee-herdsman log along with the snippet of the devices leaving the network.

One thing that's suspicious is that the `FrontDoorLock` device falls off the network 1 second after the `FrontDoor` device. According to HomeAssistant, I locked the door 1 second after it closed. Even more curious is that this is exactly 256 minutes from the last activity. Perhaps this can be explained by an [End Device Poling Timeout](https://community.silabs.com/s/article/how-to-set-the-end-device-timeout-parameter-of-end-device-timeout-request-comman?language=en_US).

Just to be safe, I've taken the steps documented in [Improve network range and stability](https://www.zigbee2mqtt.io/advanced/zigbee/02_improve_network_range_and_stability.html). Picking a zigbee channel away from my wifi channel, using a USB extension cable, and changing adapter orientation all have no effect. Link quality typically stays above 150, yet the SNZB-04's still leave the network.

This is my first time using Zigbee. When I deployed Zigbee2MQTT a couple months ago, I did not have this issue. Just a guess, but perhaps now that the [`CONFIG_END_DEVICE_POLL_TIMEOUT` is left unset](https://github.com/Koenkk/zigbee-herdsman/commit/8c258b7183bf22457800a0a90a223e43d949d0a8#diff-15e4606db5360428adba0efc271801c8512faa0ff99c1e78e63c4aef037ee7deL439), it's defaulting to 256 minutes, which is too short for some sleepy devices.

Any ideas that would get to the root of the problem would be welcome.

### What did you expect to happen?

The SNZB-04 devices should be as stable as the SNZB-01 devices on the same network.

### How to reproduce it (minimal and precise)

Pair an SNZB-04 to a ZBDongle-E and wait about a day.

### Zigbee2MQTT version

1.28.2-dev commit: 16398b7

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E

#### Full log:
[z2m_edge.log](https://github.com/Koenkk/zigbee2mqtt/files/10023024/z2m_edge.log)

#### Snippet of devices leaving:
```
2022-11-16T07:41:23.185Z zigbee-herdsman:adapter:ezsp:uart <-- [2350b1a9772a15b2d2a9003de77092028e4e233e8c7e]
2022-11-16T07:41:23.185Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (2,3,0): 2350b1a9772a15b2d2a9003de77092028e4e233e8c7e
2022-11-16T07:41:23.186Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (3)
2022-11-16T07:41:23.186Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e]
2022-11-16T07:41:23.186Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 129001230000008b3d4a184d25004b120004
2022-11-16T07:41:23.187Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x23: {"_id_":35,"_cls_":"childJoinHandler","_isRequest_":false,"index":0,"joining":0,"childId":15755,"childEui64":{"type":"Buffer","data":[0,18,75,0,37,77,24,74]},"childType":4}
2022-11-16T07:41:23.187Z zigbee-herdsman:adapter:ezsp:debg Device left network request received: 15755 00124b00254d184a
2022-11-16T07:41:23.187Z zigbee-herdsman:controller:log Device leave '0x00124b00254d184a'
2022-11-16T07:41:23.188Z zigbee-herdsman:controller:log Removing device from database '0x00124b00254d184a'
Zigbee2MQTT:warn  2022-11-16 02:41:23: Device 'FrontDoor' left the network
Zigbee2MQTT:info  2022-11-16 02:41:23: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"FrontDoor","ieee_address":"0x00124b00254d184a"},"type":"device_leave"}'
Zigbee2MQTT:info  2022-11-16 02:41:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00124b00254d184a"},"type":"device_removed"}'
2022-11-16T07:41:23.989Z zigbee-herdsman:adapter:ezsp:uart <-- [3350b1a9772a14b25eec75e5e27092028e4e230c347e]
2022-11-16T07:41:23.990Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (3,3,0): 3350b1a9772a14b25eec75e5e27092028e4e230c347e
2022-11-16T07:41:23.990Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (4)
2022-11-16T07:41:23.990Z zigbee-herdsman:adapter:ezsp:uart --> [8430fc7e]
2022-11-16T07:41:23.990Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 1290012300010007783fc04825004b120004
2022-11-16T07:41:23.990Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x23: {"_id_":35,"_cls_":"childJoinHandler","_isRequest_":false,"index":1,"joining":0,"childId":30727,"childEui64":{"type":"Buffer","data":[0,18,75,0,37,72,192,63]},"childType":4}
2022-11-16T07:41:23.991Z zigbee-herdsman:adapter:ezsp:debg Device left network request received: 30727 00124b002548c03f
2022-11-16T07:41:23.991Z zigbee-herdsman:controller:log Device leave '0x00124b002548c03f'
2022-11-16T07:41:23.991Z zigbee-herdsman:controller:log Removing device from database '0x00124b002548c03f'
Zigbee2MQTT:warn  2022-11-16 02:41:23: Device 'FrontDoorLock' left the network
Zigbee2MQTT:info  2022-11-16 02:41:24: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"FrontDoorLock","ieee_address":"0x00124b002548c03f"},"type":"device_leave"}'
Zigbee2MQTT:info  2022-11-16 02:41:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00124b002548c03f"},"type":"device_removed"}'
```

**Comment by SeanCline** [comment]
### Update
I've recreated the Zigbee network with a new panID, and re-paired all 4 devices.  Now, even the SNZB-04 buttons, which were stable, fall off the network exactly 256 minutes after they were last pressed. I've since disabled Z2M and added my 4 devices to ZHA, where they've stated on the network for the last week.

This is appears to be regression in ZBDongle-E support, perhaps related to #15066.

**Comment by marinus61** [comment]
Hi SeanCline

I experience the same on one of my HA z2m installations. But I have since 8.11.2022 filed a error report and refiled it monday, but no one seems to be looking into these error reports.

filed under 14818 and 15068 (i though I had cancelled the first one, but seems still active)

So if someone does comment on yours, I would appriciate a message
Marinus

**Comment by kirovilya** [comment]
@SeanCline @marinus61  I saw your error messages. but I can’t quickly restore the adapter’s work, because I don’t find these errors in myself installation.

@SeanCline I see you tried to learn something about this error. can you test the guess and restore setup CONFIG_END_DEVICE_POLL_TIMEOUT = 14 setting? then test.
I removed the parameter settings in order to use the parameters from the firmware, I hoped that this would be more correct.

**Comment by kirovilya** [comment]
Made changes, in the hope that the loss of devices will leave

**Comment by kirovilya** [comment]
the changes are merged. try to check the work on the updated dev / edge version of z2m

**Comment by marinus61** [comment]
@kirovilya the CONFIG_END_DEVICE_POLL_TIMEOUT = 14 is that in z2m config file or in the GUI to be added?

Marinus

**Comment by kirovilya** [comment]
@marinus61 no. this needs to be edited in the zigbee-herdsman file... the changes have already been merged into the dev|edge branch and you can update, without file editing

**Comment by marinus61** [comment]
@kirovilya 
thks for the quit reply, I will try when returning home tonight.
Appriciated that you assist us here :)

**Comment by marinus61** [comment]
@kirovilya
thks for the quit reply, i have looked intot he github and see that there is an update to 0.14.76. I am on 0.14.68
However I am unable to find out howto update to latest level, since I installed Z2M via HACS and see no update here that has not been performed.
Sorry to bather with low level questions
Appriciated that you assist us here :)

**Comment by redsam69** [comment]
Hi, I also join the question how to upgrade zigbee-herdsman to version 0.14.76?

**Comment by marinus61** [comment]
@redsam69 

As I havebeen able to find on the github written by Koenkk, seems we need to use Z2M EDGE (experimental/beta) to be able touse the "in between" updates.

**Comment by marinus61** [comment]
> ### Update
> I recreated the Z2M network with a new panID, and re-paired all 4 devices. Now, even the SNZB-01 buttons, which were stable, fall off the network exactly 256 minutes after they were last pressed. I've since disabled Z2M and added my 4 devices to ZHA, where they've stayed on the network for the last week.
> 
> This is appears to be regression in ZBDongle-E support, perhaps related to #15066.

@SeanCline 
Yes it is the same error I face and several other. Funny though that after SB-02 "left" the system, it suddenly reappeared, although with an error
In order to repair with success, i need to pair, remove and new pair

**Comment by Dominator86** [comment]
I switched to Z2M Edge and my SNZB-01 buttons are still leaving the network.
Interestingly one of the buttons seems to have rejoined on its own although I haven't permitted joining.
It's showing a red exclamation mark which says "Interview failed" when hovering.
But the weirdest thing by far is that it seems to be bound to the closest Aqara smart plug now.
You can probably imagine my surprise when I pressed the button and my PC turned off.

**Comment by marinus61** [comment]
> I switched to Z2M Edge and my SNZB-01 buttons are still leaving the network. Interestingly one of the buttons seems to have rejoined on its own although I haven't permitted joining. It's showing a red exclamation mark which says "Interview failed" when hovering. But the weirdest thing by far is that it seems to be bound to the closest Aqara smart plug now. You can probably imagine my surprise when I pressed the button and my PC turned off.

@Dominator86 
thks for the update, I have chosen not to go for EDGE and wait a little longer for an update from @koenkk to the stable version. If no solution is found I am thinking switching to ZHA 

Meantime I installed some IKEA bulbs, and the SNZB-02 that suddently reappeared after some time had the same exclamation mark on it. In order to rejoin correct, I have to join the unit, delete it and join again, then it is back to normal for 256 minutes

**Comment by marinus61** [comment]
@Dominator86 

Seems that the error only exists when pairing direct to the Sonoff dongle E, the system infected is not my main residens, so I will test further when I get back there, but the units paired to the IKEA bulp seems to stay online but with the exclamtion mark on it (did not remove and repair it, so I will try that, to see if the X mark vanished)

**Comment by Dominator86** [comment]
> Yes, if i pair with aqara plug, everything works seeamless

The problem with that is that in my case the button then toggles the plug (even though it's bound to the coordinator, not the plug) but I need my buttons to control lights.

When I pair my buttons with the dongle or my Hue and Tradfri bulbs instead they don't stay in the network.

**Comment by marinus61** [comment]
@kirovilya 

any chance that you could assist in how we can make this work or how to update the files without going via EDGE 
Marinus

**Comment by kirovilya** [comment]
@marinus61 I'm at a loss... Sonoff sensors are so capricious.
What firmware version do you have? 7.1.1

**Comment by kirovilya** [comment]
@marinus61 Not this. 
![image](https://user-images.githubusercontent.com/8360230/206442034-a45a5def-8a46-4ef8-a9ca-85cfdd028fab.png)

**Comment by marinus61** [comment]
@kirovilya 

thanks for fast reply.
![Zigbee](https://user-images.githubusercontent.com/103131648/206461512-c5ee765e-d315-4d79-a5c2-b4e538c84784.png)

**Comment by marinus61** [comment]
@kirovilya 

I found the version you had, the one I had installed was the one I had foundon Sonoff link.

Update went well, SNZB-2 and -4 are now showing all info after delete and repair.

I will update tomorrow if the link stays on

Thks for your support
Marinus

**Comment by marinus61** [comment]
@kirovilya 

Sonoff SNZB-04 still drop connection to system, so not even the latest updates secure the stability of the connection

Any further ideas

Marinus

**Comment by marinus61** [comment]
@kirovilya 

Hi again, have you had a chance to look into this persisting problem

@Dominator86 is your SNZB still online, mine drop out even when paired with other Zigbee units that the Sonoff stick

Marinus

**Comment by kirovilya** [comment]
@marinus61 I don't have a solution yet, but I'm trying to find it. I'm seeing a similar problem with Legrand buttons

**Comment by marinus61** [comment]
@kirovilya 

thks for the update, i will cross my fingers, let me know if you need any log files
Marinus

**Comment by Dominator86** [comment]
> @Dominator86 is your SNZB still online, mine drop out even when paired with other Zigbee units that the Sonoff stick

@marinus61 I "fixed" my issue by flashing my old Sonoff ZBBridge with router firmware and pairing the buttons with that instead of the Dongle-E.

**Comment by kminhtri** [comment]
Hello everybody,

Same issue here with a SNZB-04 (multiple disconnection) and sometimes the SNZB-02 disappears too.
I also have the Sonoff Dongle-E, here the firmware version :
<img width="592" alt="Capture d’écran 2022-12-21 à 00 00 08" src="https://user-images.githubusercontent.com/2980358/208782868-c0862360-cdd4-4aae-888d-8da260d42fb6.png">
and fyi, I also sync an aqara door sensor -> zero disconnection, seems the sonoff sensors are really capricious !
If I can provide any help or test with my devices, let me know :)

**Comment by marinus61** [comment]
> > @Dominator86 is your SNZB still online, mine drop out even when paired with other Zigbee units that the Sonoff stick
> 
> @marinus61 I "fixed" my issue by flashing my old Sonoff ZBBridge with router firmware and pairing the buttons with that instead of the Dongle-E.

@Dominator86 , I am thinking to go same way or maybe go to ZHA, I prefer Z2M, but seems this problem might be there to stay, thks for the update

**Comment by marinus61** [comment]
> Hello everybody,
> 
> Same issue here with a SNZB-04 (multiple disconnection) and sometimes the SNZB-02 disappears too. I also have the Sonoff Dongle-E, here the firmware version : <img alt="Capture d’écran 2022-12-21 à 00 00 08" width="592" src="https://user-images.githubusercontent.com/2980358/208782868-c0862360-cdd4-4aae-888d-8da260d42fb6.png"> and fyi, I also sync an aqara door sensor -> zero disconnection, seems the sonoff sensors are really capricious ! If I can provide any help or test with my devices, let me know :)

@kminhtri, updating firmware to latest ersion (see above) solved issues with  SNZB-02 dropping out, only SNZB-02 is still an issue

**Comment by Casper-O** [comment]
Also having issues with SNZB-04 showing up with red exclamation mark which says "Interview failed" when hovering and later disapear.

Dongle: ZBDongle-E

![image](https://user-images.githubusercontent.com/956154/210452177-cf23b5c9-5789-4f70-ac25-ef909392f75b.png)

**Comment by VS-X** [comment]
I found a workaround for my case. For all affected so off devices I went into the Reporting tab, and changed the max rep interval to 7200 for the battery attribute. This way buttons are reporting something at least every 2 hours, and are not disappearing from the network.
Not ideal, but seems to work

**Comment by VS-X** [comment]
I found a workaround for my case. For all affected so off devices I went into the Reporting tab, and changed the max rep interval to 7200 for the battery attribute. This way buttons are reporting something at least every 2 hours, and are not disappearing from the network.
Not ideal, but seems to work

**Comment by Koenkk** [comment]
Seems similar to https://github.com/Koenkk/zigbee2mqtt/issues/13600 which is fixed now. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Casper-O** [comment]
I have installed Edge version now and installed a test sensor that is laying on my desk. I will come back with result tomorrow

**Comment by marinus61** [comment]
> Seems similar to #13600 which is fixed now. Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

@Koenkk 
any idea when it will be on general update, for us not so super programmers like you
Marinus

**Comment by silvinojr** [comment]
I hope I'm not hijacking the thread.
My setup has a ZBDongle-P as coordinator and the SNZB-04s are also dropping from the network after a few hours.
Same results with a few router models, including a Sonoff Bridge flashed as router.
Once it becomes unresponsive, the only way to make it work again is to force remove the device and re-pair.

Zigbee2MQTT version: 1.29.0 commit: [unknown]
Coordinator type: zStack3x0
Coordinator revision: 20220219
Frontend version: 0.6.121

**Comment by Casper-O** [comment]
Update:

I been on the Edge version since yesterday evening - it seems to solve the issue.

**Comment by marinus61** [comment]
@Koenkk 
thank you for that.
marinus

**Comment by Koenkk** [comment]
Release is out (1.29.1), assuming this can be closed now.

**Comment by marinus61** [comment]
> Release is out (1.29.1), assuming this can be closed now.

Hi @Koenkk 
installed, great work, thanks for the support. I will revert if problem re surfaces.

**Comment by kminhtri** [comment]
Hello,

I'm on edge version : 1.29.0-dev commit: [cf80134](https://github.com/Koenkk/zigbee2mqtt/commit/cf80134)
Looks to be stable for sonoff [SNZB-02] and [SNZB-04] !!!
I saw the release, I will update to 1.29.1 now :)

Great work @Koenkk !

Thanks

**Comment by Koenkk** [comment]
All credits go to @blacknell
