### ISSUE TITLE
Skydance WZ5_cct -move and step doesn't work

### ISSUE THREAD

**Issue by zonive** [Koenkk/zigbee2mqtt#15058]
### What happened?

I'm trying to use move and step for brightness and color. 
Log from z2m frontend says: "No converter available for (...) " for any combination of brightness/color with move/step.

### How to reproduce it (minimal and precise)

Publish payload eg. {"color_temp_move": 40}

### Zigbee2MQTT version

1.28.2 

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle-P

### Debug log

error 2022-11-17 22:18:12: No converter available for 'color_temp_step' (-40)
error 2022-11-17 22:18:18: No converter available for 'brightness_move' (-40)
error 2022-11-17 22:18:25: No converter available for 'brightness_step' (40)

**Comment by Koenkk** [comment]
The Skydance WZ5 uses a custom TuYa API which does not support this. The documentation will be updated to correct this with the next release
