### ISSUE TITLE
ThirdReality (3reality) Zigbee Devices OTA Support

### ISSUE THREAD

**Issue by ahahamyan** [Koenkk/zigbee2mqtt#15051]
### Is your feature request related to a problem? Please describe

OTA Support for ThirdReality Zigbee devices. 

### Describe the solution you'd like

I noticed that ThirdReality is starting to provide OTA Support for their Zigbee devices - see https://github.com/Koenkk/zigbee-herdsman-converters/issues/4928 and hoping that it would also be available in zigbee2mqtt as well. I use Z2M with HA and it works great, but unable to update firmware on devices. Thank you very much.

### Describe alternatives you've considered

N/A

### Additional context

Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
Zigbee2MQTT -  1.28.2-1

**Comment by danieledwardgeorgehitchcock** [comment]
It looks like this has been added via the issue that you have referenced above..?
