### ISSUE TITLE
TuYa TS0012_switch_module changing states of both switches even if only one was triggered

### ISSUE THREAD

**Issue by dtrochow** [Koenkk/zigbee2mqtt#15068]
### What happened?

I paired my "GIRIER Tuya ZigBee 3.0 Smart Light Switch Module No Neutral Wire Required" module ([link](https://pl.aliexpress.com/item/1005003439384086.html?spm=a2g0o.order_list.0.0.21ef1c24RAkgWI&gatewayAdapt=glo2pol)), which was detected in the GUI as TuYa TS0012_switch_module.
 
 After triggering one of the switches in GUI, the both of them are changing the state (either to on or to off state).
  
![Screenshot 2022-11-18 at 16 59 15](https://user-images.githubusercontent.com/44304731/202747897-edb66490-cd21-46c4-87d7-c9e0127d5a8c.png)
![Screenshot 2022-11-18 at 16 59 52](https://user-images.githubusercontent.com/44304731/202747904-a8750090-1b46-4669-86f2-4f006dc186bc.png)

 
 Interesting thing is, that when I use the physical module inputs to change the state of the switch, it affects only one of them.
 
 

### What did you expect to happen?

The software switches in the device card change the states of the each switch (relay) independently.

### How to reproduce it (minimal and precise)

1. Pair the device
2. Go to the device card in Zigbee2MQTT GUI -> then Exposes tab
3. Try to switch left or right switch (the both of them will change the state, even if only one was triggered)

### Zigbee2MQTT version

1.28.2-1

### Adapter firmware version

 20220219

### Adapter

SONOFF ZBDongle-P/ ZBDongle-E

**Comment by dtrochow** [comment]
Replicates the [#13656](https://github.com/Koenkk/zigbee2mqtt/issues/13656)

**Comment by lvs-vladimir** [comment]
Hello, I have the same problem. The latest version of z2m is installed.

**Comment by omolko** [comment]
same problem with ZHA or Mqtt. Did someone get a soluce?
