### ISSUE TITLE
Hue GO impossible to reset (and so to pair)

### ISSUE THREAD

**Issue by septeven** [Koenkk/zigbee2mqtt#1507]
Hi,

I have recently sold my Hue bridge (because I’m moving out of the country I’m currently living in) and have decided to use my zigbee2mqtt system to control my hue bulbs for the weeks before I move. I have perfectly paired all of them but the Hue Go which won’t want to reset at all.

I’m using the same method than for all others, which is holding ON and OFF button of a dimmer switch closeby the lamp, hue go power coor plugged in, but the lamp stays on and won’t flash.

Is there any of you who has experienced that?
Any help will be much appreciated.

Thanks

**Comment by Koenkk** [comment]
The pairing procedure for the Hue go is a bit more complicated (I also own one). Instructions can be found here http://www.zigbee2mqtt.io/getting_started/pairing_devices.html#philips-hue (third bullet).

**Comment by septeven** [comment]
Thanks @Koenkk - draining the battery worked :)

**Comment by hay11mac** [comment]
Wondering if anyone can help, I sold my Philips hue go lamp and the buyer is unable to connect it to their hub even searching via serial number they’re still unable to find it. Are they able to reset it? Does it need to come back to me to reset? Before selling I removed it from my Philips hue I thought that would be enough, but obviously not.

I see the comment about draining the battery, so is that just turning the lamp on with no power lead until the light goes off?

would really appreciate the help with this

**Comment by luchtgitaar** [comment]
If anyone comes here via Google. Holding the button on the device for about 1 minute also resets the device.

**Comment by davidcartwright** [comment]
Except when it doesn't. Which is what brought me here. My second day with a used Hue go, it  came on fine this morning then suddenly flicked off. I have no idea if it's just suddenly otherwise dead or not.
