### ISSUE TITLE
Documentation: SLZB-02 not sold anymore - still recommend it?

### ISSUE THREAD

**Issue by SVNKoch** [Koenkk/zigbee2mqtt#15091]
### What happened?

In https://www.zigbee2mqtt.io/guide/adapters/#recommended you recommend the SMLIGHT CC2652P Zigbee USB Adapter SLZB-02. The direct website Link and the Ebay Link are both dead. In the description of the linked Telegrams user the product isn't mentioned either.

Should it still be recommended if not sold anymore?

### What did you expect to happen?

* remove the buy links or
* not recommend the SLZB-02 anymore

### Zigbee2MQTT version

-

### Adapter firmware version

-

### Adapter

-

**Comment by sergge1** [comment]
Links were corrected in [this](https://github.com/Koenkk/zigbee2mqtt.io/pull/1715) pull request. thanks for letting us know
