### ISSUE TITLE
Ikea Tradfri state

### ISSUE THREAD

**Issue by jay-jey** [Koenkk/zigbee2mqtt#151]
Hello, 

would it be possible to get the state of the ikea tradfri bulbs? At the moment I don't know if the bulb is on or off when it is switched on, because not all of my bulbs are constantly powered.

**Comment by ciotlosm** [comment]
@jay-jey you could setup on your mqtt `expire_after` to know when a bulb goes into unknown state and setup a templated sensor to mark it as off if unknown.

**Comment by jay-jey** [comment]
okay I that would help when I switch the bulb off. But the light also don't give a signal when it is switch on. So it would stand at off the hole time.

**Comment by ciotlosm** [comment]
@jay-jey I don't have the device so I can't help much, maybe @Koenkk has more knowledge on this

**Comment by Koenkk** [comment]
@ciotlosm what do you think about pinging all devices which don't have a battery? That would also partly solve #13

**Comment by ciotlosm** [comment]
I think that would work. Just to make sure we don't ping devices that have a battery but don't report it yet to avoid draining.

**Comment by ryanbeaton** [comment]
@ciotlosm I though battery devices sleep and wouldn’t answer anyway

**Comment by ciotlosm** [comment]
You might catch a device out of deep sleep and just force it to answer again draining battery unnecessary.

**Comment by tb-killa** [comment]
The best Thing would be to check via ```devleave``` event who is actually ignored.

**Comment by ppnacho** [comment]
Hi, I like your work. I have a TRADFRI LED1537R6, I've paired the bulb and I can switch on /off  the bulb. This bulb has two types of LEDs, for wharm white and for cold white. With IKEA controller it's possible switch on/off both separately, and change the brigtness individually or join. How can control all functions from HA. I have mqtt2zigbee conected to HA.
Thanks,

**Comment by Koenkk** [comment]
@ppnacho this can be done by changing the color temperature via HA

**Comment by ppnacho** [comment]
OK, but whay type of device have I configure in configuration.yaml? I have a light with mqtt_json platform. Please, could you tell me about the configuration.yaml? I'm learning about HA and different devices, Wemos, Xiaomi, etc..
Thanks

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-Home-Assistant#led1537r6
