### ISSUE TITLE
[New device support]: new converter for unsupported eva motion sensor

### ISSUE THREAD

**Issue by Joibjorn** [Koenkk/zigbee2mqtt#15106]
### Link

https://datek.fra1.digitaloceanspaces.com/HOME/Produktark/Eva-Smart-Home/Eva-Motion-Sensor.pdf

### Database entry

"id":77,"type":"EndDevice","ieeeAddr":"0x680ae2fffe06fb2b","nwkAddr":7645,"manufId":4919,"manufName":"Eva","powerSource":"Battery","modelId":"Motion Sensor","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1024,1026,1030,1280,65261],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"Motion Sensor","manufacturerName":"Eva","powerSource":3,"zclVersion":8,"appVersion":3,"stackVersion":106,"swBuildId":"0.3"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff0654e3","zoneState":1,"currentZoneSensitivityLevel":3}},"genPollCtrl":{"attributes":{"checkinInterval":14400}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2335}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":27789,"minMeasuredValue":1,"maxMeasuredValue":27789,"lightSensorType":0}},"msOccupancySensing":{"attributes":{"occupancy":1,"occupancySensorType":0,"pirOToUDelay":900}},"msIlluminanceLevelSensing":{"attributes":{}},"genLevelCtrl":{"attributes":{}},"elkoOccupancySettingClusterServer":{"attributes":{}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00212effff0654e3","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00212effff0654e3","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":106,"swBuildId":"0.3","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1668962437224,"defaultSendRequestWhen":"active"}

### Comments

Unsupported EVA motion sensor, model HSE2927E, looks like DATEK is the manufacturer. I was successful in creating a conversion file, and have pasted the code below for that. Attributes now supported are occupancy, illuminance, temperature, battery and tamper.
![image](https://user-images.githubusercontent.com/21249609/202914768-706f6e62-d5cb-4945-b281-c184a06ded03.png)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Motion Sensor'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'Motion Sensor', // Vendor model number, look on the device for a model number
    vendor: 'Eva', // Vendor of the device (only used for documentation and startup logging)
    description: 'Eva zigbee motion sensor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.ias_occupancy_alarm_1_with_timeout, fz.illuminance, fz.temperature], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.illuminance(), e.illuminance_lux(), e.temperature()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
