### ISSUE TITLE
Zigbee2mqtt fail to start

### ISSUE THREAD

**Issue by kiker666** [Koenkk/zigbee2mqtt#15102]
### What happened?

Hello, i am stuck with this issue. Could anyone help me a bit pleaseee?
NAS synology dsm7.1 version. 
HA running in a docker. Mqtt addon installed and running.
I bought sonoff dongle plus p, flashed zigbee2mqtt coordinator firmware.
I add drivers and controllers, and NAS detect usb as /dev/ttyUSB0:
![image](https://user-images.githubusercontent.com/47297919/202903253-8fe01a82-105d-41b6-86e1-685eef3c395e.png)
Then i created a docker container zigbee2mqtt ( yaml pic attached)
![image](https://user-images.githubusercontent.com/47297919/202903197-d5d8ab81-cf11-44b4-be07-052af3868f30.png)
But then, when i try to run it, says:
![image](https://user-images.githubusercontent.com/47297919/202903151-e57f12e4-4507-407e-af35-b59ea3fb42bc.png)

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20220219

### Adapter

Dongle Plus "ZBDongle-P" (based on CC2652P)

**Comment by Brix1330** [comment]
Got this problem as well after updating HA to 2022.11.3, somehow after updating the dongle is no longer detected on _/dev/ttyUSB0_ but moved to _/dev/ttyUSB1_. 

Have you checked on _HA > Settings > System > Hardware > All Hardware_ (under three dots; right corner)?

**Comment by thomashogema** [comment]
Had a similar issue after updating to 2022.11.3 while running Home Assistant. The dongle location in the hardware tab did not change, but Z2M could not find it.
For me, the solution was to restart the host machine.
