### ISSUE TITLE
[New device support]: Bseed Zigbee Glass Touch 2gang

### ISSUE THREAD

**Issue by Hausy1986** [Koenkk/zigbee2mqtt#15108]
### Link

https://de.aliexpress.com/item/1005002842345807.html?spm=a2g0o.productlist.0.0.69645327XLPIBu&algo_pvid=f16dfabe-2215-46ed-b221-079285dfd9cf&aem_p4p_detail=202211201008345513992527262440005301746&algo_exp_id=f16dfabe-2215-46ed-b221-079285dfd9cf-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000028845537231%22%7D&pdp_npi=2%40dis%21EUR%2138.1%2111.0%21%21%21%21%21%402100bde116689677146098317e47fb%2112000028845537231%21sea&curPageLogUid=2vZwyV9pVa2G&ad_pvid=202211201008345513992527262440005301746_1&ad_pvid=202211201008345513992527262440005301746_1

### Database entry

**_from zigbee-adapter in iobroker (/opt/iobroker/iobroker-data/zigbee_0/shepherd.db_**
{"id":22,"type":"EndDevice","ieeeAddr":"0xa4c138ee93b4c098","nwkAddr":25984,"manufId":4417,"manufName":"_TZ3000_e98krvvk","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff07c0ce","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff07c0ce","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1670152722644,"defaultSendRequestWhen":"immediate"}

### Comments

Hallo, hoffe mir kann hier einer helfen und dieses Gerät implementieren. Ich weiß das leider nicht mehr weiter.
![BSEED-Zigbee-Touch-Schalter-1-2-3Gang-Smart-Licht-Schalter-Drahtlose-Steuerung-ber-Google-Smart-Leben jpg_640x640](https://user-images.githubusercontent.com/118669239/202919237-139644af-0d9d-42d1-95df-ed0ce691e533.jpg)

Und zwar folgendes: Der Lichtschalter von Bseed mit den 2 Touch-Relais wird zwar erkannt, aber als ein anderes Gerät = [https://www.zigbee2mqtt.io/devices/TS0012.html](url)
![1](https://user-images.githubusercontent.com/118669239/202919109-98b850b4-2ad2-4874-a5fb-60400064594c.png)

Eigentlich wäre es kein Problem, weil bei dem Lichtschalter mit einem touch funktioniert es auch, nur hier schalten sich immer **beide Relais** mit, egal ob ich left oder right state anwähle. Auch das löschen eines der state's bringt keine Veränderung. 

Ich würde mich freuen, wenn sich einer findet und mir hilft bzw. das Gerät mit aufnimmt, da ich leider mehrere davon nutzen wollte/muss :D. Ich würde auch gerne noch mehr Daten bereitstellen nur habe ich das mit Zigbee2mqtt und mosquito nicht hinbekommen, musste sogar ein komplettes Backup auf meinem Raspberry neu aufspielen.

Gruß 
Hausy

**Comment by danieledwardgeorgehitchcock** [comment]
It is common for Zigbee2MQTT to support generic white labelled devices using a single converter as you see above.

I believe that there is already a bug report (will update my comment when I find it) regarding TS0012 device states working incorrectly

**Comment by Hausy1986** [comment]
Erstmal vielen Dank für die Hilfestellung. Ich habe versucht Zigbee2MQTT auf meinen RaspberryPi zu installieren, leider kriege ich es nicht hin und musste schon wieder für das ganze System ein Backup einspielen, da auch der Zigbee Adapter im Iobroker, womit ich die Geräte hinzufüge, nicht mehr funktionierte.

Gibt es eine Möglichkeit über den Adapter im Iobroker an die Daten zu kommen? 

_Google Translate:_
Many thanks for your help. I tried to install Zigbee2MQTT on my RaspberryPi, unfortunately I can't do it and had to import a backup for the whole system again, because the Zigbee adapter in Iobroker, with which I add the devices, no longer worked.

Is there a way to get the data via the adapter in the iobroker?
