### ISSUE TITLE
Homekit shows the opposite in term of blinds position

### ISSUE THREAD

**Issue by 1HyperZ** [Koenkk/zigbee2mqtt#15117]
### What happened?

when the blinds are open i can see on z2m that theyre open but in homekit and homebridge it shows closed

### What did you expect to happen?

i expect homekit to show the real position of the blinds

### How to reproduce it (minimal and precise)

?

### Zigbee2MQTT version

1.28.2-dev

### Adapter firmware version

20220507

### Adapter

Sonoff stick

### Debug log

Debug 2022-11-21 12:16:59Received MQTT message on 'zigbee2mqtt/0x84b4dbfffec833cd/set' with data '{"position":0}'
Debug 2022-11-21 12:16:59Publishing 'set' 'position' to 'Front Gate'
Debug 2022-11-21 12:17:00Received Zigbee message from 'Front Gate', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":100}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:00MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":120,"motor_reversal":null,"moving":null,"position":0,"state":"OPEN"}'
Debug 2022-11-21 12:17:00Received Zigbee message from 'iPad’s Motion Sensor', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":1}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:00MQTT publish: topic 'zigbee2mqtt/iPad’s Motion Sensor', payload '{"battery_low":false,"device":{"applicationVersion":70,"dateCode":"","friendlyName":"iPad’s Motion Sensor","hardwareVersion":1,"ieeeAddr":"0xa4c13824b909b3a4","manufacturerID":4417,"manufacturerName":"_TZ3000_mcxw5ehu","model":"IH012-RT01","networkAddress":15651,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"keep_time":null,"linkquality":69,"occupancy":true,"sensitivity":null,"tamper":false}'
Info 2022-11-21 12:17:00MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":120,"motor_reversal":null,"moving":null,"position":0,"state":null}'
Debug 2022-11-21 12:17:00Received Zigbee message from 'Front Gate', type 'attributeReport', cluster 'closuresWindowCovering', data '{"tuyaMovingState":0}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:00MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":123,"motor_reversal":null,"moving":"UP","state":null}'
Debug 2022-11-21 12:17:01Received MQTT message on 'zigbee2mqtt/0x84b4dbfffec833cd/set' with data '{"position":100}'
Debug 2022-11-21 12:17:01Publishing 'set' 'position' to 'Front Gate'
Debug 2022-11-21 12:17:01Received Zigbee message from 'Front Gate', type 'attributeReport', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:01MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":123,"motor_reversal":null,"moving":null,"position":100,"state":"CLOSE"}'
Info 2022-11-21 12:17:01MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":123,"motor_reversal":null,"moving":null,"position":100,"state":null}'
Debug 2022-11-21 12:17:01Received Zigbee message from 'Front Gate', type 'attributeReport', cluster 'closuresWindowCovering', data '{"tuyaMovingState":2}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:01MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":120,"motor_reversal":null,"moving":"DOWN","state":null}'
Debug 2022-11-21 12:17:02Received Zigbee message from 'Front Gate', type 'attributeReport', cluster 'closuresWindowCovering', data '{"tuyaMovingState":1}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:02MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":127,"motor_reversal":null,"moving":"STOP","state":null}'
Debug 2022-11-21 12:17:05Received MQTT message on 'zigbee2mqtt/0x84b4dbfffec833cd/get' with data '{"position":0}'
Debug 2022-11-21 12:17:05Publishing get 'get' 'position' to 'Front Gate'
Debug 2022-11-21 12:17:05Received Zigbee message from 'Front Gate', type 'readResponse', cluster 'closuresWindowCovering', data '{"currentPositionLiftPercentage":0}' from endpoint 1 with groupID 0
Info 2022-11-21 12:17:05MQTT publish: topic 'zigbee2mqtt/Front Gate', payload '{"calibration_time":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Front Gate","hardwareVersion":1,"ieeeAddr":"0x84b4dbfffec833cd","manufacturerID":4098,"manufacturerName":"_TZ3000_1dd0d5yi","model":"MS-108ZR","networkAddress":32893,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"linkquality":123,"motor_reversal":null,"moving":null,"position":100,"state":"CLOSE"}'

**Comment by danieledwardgeorgehitchcock** [comment]
Have you raised this as an issue in the Homebridge project - this sounds like a better fit for over there...
