### ISSUE TITLE
OTA image block requests get dropped by ZC partly through the upgrade

### ISSUE THREAD

**Issue by nickrbogdanov** [Koenkk/zigbee2mqtt#15139]
### What happened?

I am using zigbee2mqtt to run OTA updates on a couple of identical devices.  Once in a while the OTA update succeeds, but often it fails part of the way through the update sequence.  This happens at random points in the image, never at the same offset.

In Wireshark I see that at the point of the failure, the device is sending Image Block Requests but never receiving an Image Block Response.  In this run, Seq 151 was the last good response:

![image](https://user-images.githubusercontent.com/63979903/203496762-47233bb8-d11a-4db1-9b6e-2b7c8481cc6d.png)

The device continues sending Image Block Request packets for the next 90 seconds, then it gives up:

![image](https://user-images.githubusercontent.com/63979903/203496949-8342e243-ab3f-4fc9-bb64-5e804965fbf4.png)

I do see an 802.15 Ack after each of the ignored packets:

![image](https://user-images.githubusercontent.com/63979903/203497102-1a6ba853-24b5-4371-9d61-28e1a29375c8.png)

To see whether the software was receiving the missing packets, I enabled logging using `DEBUG="zigbee-herdsman:adapter:zStack:*"`.  What this showed me was that the software got an `AREQ <-- AF - incomingMsg` for Seq 152 (and all previous packets).  There was no AREQ for 153 or 154.  Then it got an AREQ for Seq 155, the Upgrade End Request packet.  At this point it logged the event indicating that the OTA had failed.

Every time I see an OTA failure it's the same basic pattern: z2m just quits responding to the Image Block Requests and the device keeps retrying for the next 90 seconds before giving up.  It doesn't seem consistent with random indiscriminate packet loss or corruption.  And I think z2m always receives the Upgrade End Request (although I'm running more tests to be sure).

Is this a firmware issue?  I am running the latest `CC1352P2_CC2652P_launchpad_coordinator_20220219.hex` on a Sonoff 3.0 dongle.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

Sonoff 3.0

### Debug log

Can send logs + pcaps privately if needed

**Comment by sjorge** [comment]
I noticed something similar too after https://github.com/Koenkk/zigbee2mqtt/commit/60de5b7676192a56cb02ca5335472541e3910cf9

before I could update like 4-8 bulbs at a time, it'd be slow but a day later they were all upgraded. Now max I can do is maybe 2, but even doing 1 now sometimes just fails.

But don't think that commit would explain what you're seeing.

**Comment by nickrbogdanov** [comment]
Also: I first saw this on an older installation that predates 60de5b7 by several months.  I updated all modules + FW so that I wouldn't be submitting a problem report against an ancient version, but the error persisted.
