### ISSUE TITLE
And again .... OSRAM Smart+ motion

### ISSUE THREAD

**Issue by thissiac** [Koenkk/zigbee2mqtt#1513]
2019-5-9 11:28:20 Logging to directory: '/opt/zigbee2mqtt/data/log/2019-05-09.11-28-20'
2019-5-9 11:28:21 Starting zigbee2mqtt version 1.1.1 (commit #92d88b6)
2019-5-9 11:28:21 Starting zigbee-shepherd
2019-5-9 11:28:22 zigbee-shepherd started
2019-5-9 11:28:22 Coordinator firmware version: '20180815'

**And again the OSRAM Smart Motion Sensor**

After i couldn't pair the old motion sensor anymore, i got myself a new one. Now the situation is different again.

**This was the first message that came after activation:**

Mai 09 08:01:21 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:21 MQTT publish: topic 'z2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
Mai 09 08:01:24 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:24 Connecting with device...
Mai 09 08:01:24 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:24 MQTT publish: topic 'z2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 Connecting with device...
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 MQTT publish: topic 'z2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 Device incoming...
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 MQTT publish: topic 'z2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 New device with address 0x000d6f000f83f7f8 connected!
Mai 09 08:01:25 openHABianPi npm[24526]:   zigbee2mqtt:info 2019-5-9 08:01:25 MQTT publish: topic 'z2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x000d6f000f83f7f8"}'
Mai 09 08:01:26 openHABianPi npm[24526]:   zigbee2mqtt:error 2019-5-9 08:01:26 Failed to configure 0x000d6f000f83f7f8 (0x000d6f000f83f7f8) ('Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.')

**After stopping z2mqtt and restarting it, the problem looks like this:**

2019-5-9 09:35:14 MQTT publish: topic 'z2mqtt/0x000d6f000f83f7f8', payload '{"occupancy":false,"tamper":false,"battery_low":false}'
zigbee2mqtt:error 2019-5-9 09:35:27 Failed to configure 0x000d6f000f83f7f8 (0x000d6f000f83f7f8) ('unsupAttribute')
2019-5-9 09:40:53 MQTT publish: topic 'z2mqtt/0x000d6f000f83f7f8', payload '{"occupancy":false,"tamper":false,"battery_low":false,"temperature":21.73,"linkquality":21}'

From now on I get regular entries in the log file, but except for the values for temperature nothing changes. And even the temperatures change like in slow motion.

**After stopping z2mqtt and restarting 2. time, the problem looks like this:**

2019-5-9 11:28:23 Failed to configure 0x000d6f000f83f7f8 (0x000d6f000f83f7f8) ('Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.')

No further entries visible in the log.

Every time I start with "npm start" I see an entry which looks fine.

2019-5-9 11:44:10 MQTT publish: topic 'z2mqtt/0x000d6f000f83f7f8', payload '{"occupancy":false,"tamper":false,"battery_low":false,"temperature":22.97,"linkquality":15}'

Immidently the next entry

2019-5-9 11:44:11 Failed to configure 0x000d6f000f83f7f8 (0x000d6f000f83f7f8) ('Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.')

What next?

Maybe the Smart+ Motion Sensor is not the right product for zigbee2mqtt?

**Comment by Koenkk** [comment]
- First make sure you are running the latest zigbee2mqtt version.
- Please also try with the latest dev firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/dev/coordinator/Z-Stack_Home_1.2/bin
