### ISSUE TITLE
can not bind a Mijia MCCGQ01LM on clean installation

### ISSUE THREAD

**Issue by chrisdaloa** [Koenkk/zigbee2mqtt#1514]
Hi, I can not bind a Mijia MCCGQ01LM.

The error I receive is "zigbee2mqtt:error 5/9/2019, 10:11:28 PM Cannot get the Node Descriptor of the Device: 0x00158d0002ea057a (Error: Timed out after 10000 ms)"

I know that there are many posts about this issue, I read every existing post and trying every procedures you suggest but with no results.

So to be sure I made a clean installation of zigbee2mqtt with no other devices and I run debug mode: same issue.

Here is my debug log (shepherd + zigbee2mqtt): https://pastebin.com/s5EuVW57

zigbee2mqtt version: 1.3.1
CC253X firmware version: 20190223

All works good with the Aqara MCCGQ11LM.

Thanks for your support.

**Comment by tricoos** [comment]
It worked for me when I kept pressing the button every second or so until I saw that the device had been connected successfully in the log file.
