### ISSUE TITLE
backlight_mode bug

### ISSUE THREAD

**Issue by StopDragon** [Koenkk/zigbee2mqtt#15145]
### What happened?

On some models the backlight_mode can be seen in the settings, 
on some models I have checked the backlight_mode cannot be set.

available: TS0013
not available: TS0011, TS0012

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

SONOFF ZB USB (version p)

**Comment by danieledwardgeorgehitchcock** [comment]
This isn't a bug.

You are correct, support for the backlight settings have not been implemented in the device converter for the TS0011 and TS0012 devices but has been in the TS0013 devices.

Are you sure that the backlight can indeed be controlled on the other devices via the TuYa app? If so, it is more of a feature request and we would need to confirm the Data Point for that setting from TuYa

**Comment by StopDragon** [comment]
Yes.
Then may I make a request?

**Comment by danieledwardgeorgehitchcock** [comment]
Could you find the data point for the backlight setting?

**Comment by StopDragon** [comment]
> Could you find the data points used by the different devices for the backlight setting?

I'm sorry but I didn't understand what you said. where can i see that?

**Comment by danieledwardgeorgehitchcock** [comment]
[Find TuYa Data Points](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html)

**Comment by ajunio3** [comment]
backlight DP is 16

**Comment by ajunio3** [comment]
really need this for tuya TS0013 3gang with neutral

**Comment by ajunio3** [comment]
and yes i can control backlight and last_state in Smart life for this device
