### ISSUE TITLE
Schneider Wiser WDE002182 identified as ELKO EKO09738

### ISSUE THREAD

**Issue by tkarlsson** [Koenkk/zigbee2mqtt#15147]
### What happened?

When paired, Schneider Wiser WDE002182 is identified as ELKO EKO09738

### What did you expect to happen?

To be showing as Schneider Wiser WDE002182

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

**Comment by enoch85** [comment]
Can one bump this, have the same issue....
