### ISSUE TITLE
 SIN-4-1-20 not working

### ISSUE THREAD

**Issue by ML-DOMO** [Koenkk/zigbee2mqtt#15169]
### What happened?

The SIN-4-1-20 module does not take into account the sending of ON or OFF commands.

On the other hand, when manually pressing the module, the status feedback is good.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

SONOFF ZB Dongle Plus

**Comment by euidzero** [comment]
https://github.com/Koenkk/zigbee2mqtt/discussions/15683
Seems like epList is wrong.
