### ISSUE TITLE
Mercator AC fan controller model SSWF01G incorrectly reporting fan state

### ISSUE THREAD

**Issue by Anhvariel** [Koenkk/zigbee2mqtt#15186]
### What happened?

Mercator fan controller model SSWF01G regularly reports fan state as on when it is not.  Both the "State" tab and "Exposes" tab show this incorrect fan_state value.  Pressing the refresh button on the "Exposes" tab next to fan state will update the value and show it correctly.  Also toggling the physical switch will update the value correctly.  It seems as though the device regularly publishes an attribute report with fanmodesequence data which is being interpreted incorrectly as the fan being on. Se bolded log line below.

### What did you expect to happen?

Fan state operating correctly.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 Dongle Plus (Model ZBDongle-P)

### Debug log

**2022-11-27 10:52:42Received Zigbee message from 'Mercator Fan Controller - Patio', type 'attributeReport', cluster 'hvacFanCtrl', data '{"fanModeSequence":1}' from endpoint 1 with groupID 0**
Info 2022-11-27 10:52:42MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_state":"ON","last_seen":"2022-11-27T10:52:40+11:00","linkquality":51,"state":"OFF"}'
Debug 2022-11-27 10:52:53Received MQTT message on 'zigbee2mqtt/Mercator Fan Controller - Patio/set/fan_state' with data 'OFF'
Debug 2022-11-27 10:52:53Publishing 'set' 'fan_state' to 'Mercator Fan Controller - Patio'
Info 2022-11-27 10:52:53MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_state":"ON","last_seen":"2022-11-27T10:52:51+11:00","linkquality":51,"state":"OFF"}'
Info 2022-11-27 10:52:53MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:52:51+11:00","linkquality":51,"state":"OFF"}'
Debug 2022-11-27 10:53:12Received MQTT message on 'zigbee2mqtt/Mercator Fan Controller - Patio/set/fan_state' with data 'ON'
Debug 2022-11-27 10:53:12Publishing 'set' 'fan_state' to 'Mercator Fan Controller - Patio'
Info 2022-11-27 10:53:12MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:53:10+11:00","linkquality":43,"state":"OFF"}'
Debug 2022-11-27 10:53:12Received Zigbee message from 'Mercator Fan Controller - Patio', type 'attributeReport', cluster 'hvacFanCtrl', data '{"fanMode":4}' from endpoint 1 with groupID 0
Info 2022-11-27 10:53:12MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"on","fan_state":"ON","last_seen":"2022-11-27T10:53:10+11:00","linkquality":43,"state":"OFF"}'
Info 2022-11-27 10:53:12MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"on","fan_state":"ON","last_seen":"2022-11-27T10:53:10+11:00","linkquality":43,"state":"OFF"}'
Debug 2022-11-27 10:53:56Received MQTT message on 'zigbee2mqtt/Mercator Fan Controller - Patio/set/fan_state' with data 'OFF'
Debug 2022-11-27 10:53:56Publishing 'set' 'fan_state' to 'Mercator Fan Controller - Patio'
Debug 2022-11-27 10:53:56Received Zigbee message from 'Mercator Fan Controller - Patio', type 'attributeReport', cluster 'hvacFanCtrl', data '{"fanMode":0}' from endpoint 1 with groupID 0
Info 2022-11-27 10:53:56MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:53:54+11:00","linkquality":51,"state":"OFF"}'
Info 2022-11-27 10:53:56MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:53:54+11:00","linkquality":51,"state":"OFF"}'
Info 2022-11-27 10:53:56MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:53:54+11:00","linkquality":51,"state":"OFF"}'
Debug 2022-11-27 10:54:13Received Zigbee message from 'Mercator Fan Controller - Patio', type 'attributeReport', cluster 'genBasic', data '{"appVersion":69}' from endpoint 1 with groupID 0
Info 2022-11-27 10:54:13MQTT publish: topic 'zigbee2mqtt/Mercator Fan Controller - Patio', payload '{"fan_mode":"off","fan_state":"OFF","last_seen":"2022-11-27T10:54:11+11:00","linkquality":51,"state":"OFF"}'

**Comment by davidjb** [comment]
I'm seeing this also, on z2m 1.29.1 - same behaviour with the same model of device.
