### ISSUE TITLE
Energy, power and device temperature stoped working for aqara switch SSM-U01 since zigbee2mqtt version 1.23.0 

### ISSUE THREAD

**Issue by pdalak** [Koenkk/zigbee2mqtt#15197]
### What happened?

Energy, power and device temperature stoped working for aqara switch SSM-U01 since zigbee2mqtt version 1.23.0 

### In version 1.22.2 and earlier: 
* Metrics are showed correctly
<img width="872" alt="zigbee2mqtt 1_22_2" src="https://user-images.githubusercontent.com/3317329/204095804-b69c895c-c8d0-46c9-9a71-274f8d31dc41.png">

### In version 1.23.0:
* frontend looks same, but values are not working anymore
<img width="906" alt="zigbee2mqtt 1_23_0" src="https://user-images.githubusercontent.com/3317329/204095846-fb5ee25e-1084-40ef-aa99-2f9dc64007a6.png">

### In version 1.24.0 and later:
* There are new fields in frontend, voltage, temperature, current. All of them are also N/A. 
<img width="881" alt="zigbee2mqtt 1_24_0" src="https://user-images.githubusercontent.com/3317329/204095953-3971086e-1346-4859-b108-a62df3358f0d.png">

### This is exact model of aqara switch:
**Zigbee Model:** lumi.switch.n0agl1
**Description:** Aqara single switch module T1 (with neutral) 
**Firmware build date:** Dec 30 2021 (Same behavior was with older FW, I do not remember exact date of previous FW)
**Manufacturer:** Xiaomi
**Model:** [SSM-U01](https://www.zigbee2mqtt.io/devices/SSM-U01.html#xiaomi-ssm-u01)

> Just a note, I have another aqara smart plug SP-EUC01 and it work correctly in all versions of zigbee2mqtt

### What did you expect to happen?

Energy, power and device temperature should be reported correctly as before.

### How to reproduce it (minimal and precise)

* Pair aqara switch device into zigbee2mqtt version 1.22.2 or any earlier - It works as it should. 
* Pair aquara switch to any version later than 1.23.0. Now Energy, power and device temperature are not working anymore, and zigbee2mqtt frontend shows N/A. 

### Zigbee2MQTT version

1.23.0 and any later

### Adapter firmware version

0x26660700

### Adapter

Deconz ConBee2/RaspBee2

**Comment by pdalak** [comment]
Remove stale.

**Comment by Koenkk** [comment]
Try updating the conbee firmware to at least [0x26720700](http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26720700.bin.GCF) and repair the device.

**Comment by pdalak** [comment]
Thank You for an advice. It works now. Sorry, I did not found this advice anywhere before.
