### ISSUE TITLE
[New device support]: Cosmo CFK8L - underfloor heating distributor

### ISSUE THREAD

**Issue by indikat0r** [Koenkk/zigbee2mqtt#15208]
### Link

https://www.cosmo-info.de/produkte/heizungstechnik/fussbodenheizungen/regelungen/8-zonen-funk-regelklemmleiste

### Database entry

{"id":45,"type":"Router","ieeeAddr":"0x001e5e090901ab17","nwkAddr":1474,"manufId":4216,"manufName":"Computime","powerSource":"Unknown","epList":[8],"endpoints":{"8":{"profId":260,"epId":8,"devId":0,"inClusterList":[0,3,64512],"outClusterList":[3,25,64512],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"hwVersion":1,"zclVersion":0,"interviewCompleted":false,"meta":{},"lastSeen":1669545686128,"defaultSendRequestWhen":"immediate"}

### Comments

Hello,

i have tried to add the converter file. but the Device always reconnects.
and i always get the same message. and the Device doesnt stay connected to the Network.
any help is apreciatet.

Debug 2022-11-27 11:33:59Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:33:59Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{"zclVersion":0}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:33:59Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:00Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:00Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:00Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Info 2022-11-27 11:34:00Successfully interviewed '0x001e5e090901ab17', device has successfully been paired
Warning 2022-11-27 11:34:00Device '0x001e5e090901ab17' with Zigbee model 'undefined' and manufacturer name 'Computime' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-11-27 11:34:00MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17","status":"successful","supported":false},"type":"device_interview"}'
Warning 2022-11-27 11:34:10Device '0x001e5e090901ab17' left the network
Info 2022-11-27 11:34:10MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17"},"type":"device_leave"}'
Warning 2022-11-27 11:34:12Device '0x001e5e090901ab17' left the network
Info 2022-11-27 11:34:12MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17"},"type":"device_leave"}'
Warning 2022-11-27 11:34:12Device '0x001e5e090901ab17' left the network
Info 2022-11-27 11:34:12MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17"},"type":"device_leave"}'
Info 2022-11-27 11:34:12Device '0x001e5e090901ab17' joined
Info 2022-11-27 11:34:12MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17"},"type":"device_joined"}'
Info 2022-11-27 11:34:12Starting interview of '0x001e5e090901ab17'
Info 2022-11-27 11:34:12MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17","status":"started"},"type":"device_interview"}'
Debug 2022-11-27 11:34:13Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:14Received Zigbee message from '0x001e5e090901ab17', type 'raw', cluster 'manuSpecificUbisysDeviceSetup', data '{"data":[21,120,16,41,16,255,0,255,24,4,25,32],"type":"Buffer"}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{"zclVersion":0}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Debug 2022-11-27 11:34:23Received Zigbee message from '0x001e5e090901ab17', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 8 with groupID 0
Info 2022-11-27 11:34:23Successfully interviewed '0x001e5e090901ab17', device has successfully been paired
Warning 2022-11-27 11:34:23Device '0x001e5e090901ab17' with Zigbee model 'undefined' and manufacturer name 'Computime' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2022-11-27 11:34:24MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x001e5e090901ab17","ieee_address":"0x001e5e090901ab17","status":"successful","supported":false},"type":"device_interview"}'

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['cfkl8'], 
    model: 'CFKL8', // Vendor model number, look on the device for a model number
    vendor: 'Cosmo', // Vendor of the device (only used for documentation and startup logging)
    description: 'Cosmo Regelklemmleiste CFKL8', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [e.battery(), e.temperature(), e.humidity()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by danieledwardgeorgehitchcock** [comment]
I think the is a whitelabel of the Salus KL08RF - I did some investigation on it a while ago (use the Git search). My investigation found that due to the way the device is programmed, it is pretty much useless inZ2M as it uses groups and bindings to control relays (I.e. it isn't controllable via endpoints as most relay devices)
