### ISSUE TITLE
[New device support]: Nedis Climate sensor ZBSC10WT 

### ISSUE THREAD

**Issue by LateWiksi** [Koenkk/zigbee2mqtt#15210]
### Link

https://nedis.com/en-us/product/smart-home/climate/monitoring/550726063/smart-climate-sensor-zigbee-30-battery-powered-android-ios-white

### Database entry

{"id":2,"type":"Unknown","ieeeAddr":"0xa4c138c6a7b19f9a","nwkAddr":52263,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1669557176647,"defaultSendRequestWhen":"immediate"}

### Debug log
info 2022-11-27 16:19:16Device '0xa4c138c6a7b19f9a' joined
info 2022-11-27 16:19:16MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138c6a7b19f9a","ieee_address":"0xa4c138c6a7b19f9a"},"type":"device_joined"}'
info 2022-11-27 16:19:16MQTT publish: topic 'zigbee2mqtt/0xa4c138c6a7b19f9a', payload '{"last_seen":"2022-11-27T16:19:16+02:00"}'
info 2022-11-27 16:19:16Starting interview of '0xa4c138c6a7b19f9a'
info 2022-11-27 16:19:16MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138c6a7b19f9a","ieee_address":"0xa4c138c6a7b19f9a","status":"started"},"type":"device_interview"}'
error 2022-11-27 16:20:48Failed to interview '0xa4c138c6a7b19f9a', device has not successfully been paired
info 2022-11-27 16:20:48MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138c6a7b19f9a","ieee_address":"0xa4c138c6a7b19f9a","status":"failed"},"type":"device_interview"}'
debug 2022-11-27 16:21:37Saving state to file /config/zigbee2mqtt/state.json
error 2022-11-27 16:22:20Failed to interview '0xa4c138c6a7b19f9a', device has not successfully been paired
info 2022-11-27 16:22:20MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138c6a7b19f9a","ieee_address":"0xa4c138c6a7b19f9a","status":"failed"},"type":"device_interview"}'

### Similar device data from Tuya Cloud (just to let you know if it helps)

{
  "active_time": 1639470429,
  "biz_type": 0,
  "category": "wsdcg",
  "create_time": 1665041019,
  "icon": "smart/icon/ay1513237774906SMBA3/d0ba959023b24177f16f68f8e5d00a3e.png",
  "id": "bf8c13a3229d5cac50o41v",
  "ip": "",
  "lat": "xxx",
  "local_key": "9ddee3f4c9f3a16c",
  "lon": "xxx",
  "model": "ZBSC10WT",
  "name": "Small Bedroom",
  "node_id": "a4c132de2fef8f9c",
  "online": true,
  "owner_id": "62334715",
  "product_id": "fie1dpkm",
  "product_name": "Climate Sensor",
  "status": [
    {
      "code": "va_temperature",
      "value": 225
    },
    {
      "code": "va_humidity",
      "value": 414
    },
    {
      "code": "battery_percentage",
      "value": 100
    }
  ],
  "sub": true,
  "time_zone": "+03:00",
  "uid": "eu16588590666570GDCP",
  "update_time": 1669470429,
  "uuid": "a4c138de2fff899c"
}

### Comments

Nedis Climate sensor ZBSC10WT does not seems to be supported.
Info that the sensor provides: temperature, humidity, batter 

### External converter

```shell
SonOff Zigbee 3.0 USB Dongle Plus-P
```

**Comment by LateWiksi** [comment]
This is not fixed.

**Comment by LateWiksi** [comment]
Opened a new ticket:
#17051 https://github.com/Koenkk/zigbee2mqtt/issues/17051

**Comment by LateWiksi** [comment]
Up

**Comment by mattiaskagstrom** [comment]
Still not fixed. Sensors is identified as TS0201 instead. However the temperature and humidity does work. but not the battery state. (and it gets the wrong icon)
mostly minor inconveniences 

![image](https://github.com/user-attachments/assets/7aef4aec-cdba-4a78-871a-0dea84366891)
