### ISSUE TITLE
[Feature request]: Make friendly name visible on top of device page

### ISSUE THREAD

**Issue by saspol** [Koenkk/zigbee2mqtt#15240]
### Is your feature request related to a problem? Please describe

When have dozens of devices with original IEEE name, it is difficult to understand where are you at the moment.

### Describe the solution you'd like

I suggest make device page looks like this.

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/16889941/204530440-0eb27643-7e4c-445f-988f-b70538aeb98b.png)

### Additional context

I found better dont rename devices itself, since they can change location and purpose of use. But custom name will stuck in scripts.

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
