### ISSUE TITLE
[New device support]: Philips Hue White 1100 lumen E26 A19 "A" variant

### ISSUE THREAD

**Issue by savingprivatebryan** [Koenkk/zigbee2mqtt#15267]
### Link

https://www.amazon.com/dp/B095KTKDSY

### Database entry

{"id":31,"type":"Router","ieeeAddr":"0x001788010d3dfaf7","nwkAddr":33408,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LWA029","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":257,"inClusterList":[0,3,4,5,6,8,4096,64515,64514],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20220502","swBuildId":"1.93.11","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1669835996849,"defaultSendRequestWhen":"immediate"}

### Comments

The model number on the box is 9290024691A.
Not sure what the difference is if any with the already supported model LWA019 (9290024691 without the A)

**Comment by Koenkk** [comment]
Added! Device will be supported in tomorrow's new release.
