### ISSUE TITLE
Error when starting the zigbee2mqtt add-on in hassio

### ISSUE THREAD

**Issue by shadow-fight** [Koenkk/zigbee2mqtt#1527]
The CC2531 Device was working well for over 1 month until yesterday morning. The LED on sniffer display green so I reboot the hassio and the add-on, the following warning message appeared.

![图片](https://user-images.githubusercontent.com/33606388/57659482-5f145880-75da-11e9-9408-953d04c4f6fc.png)

I have already tried to re-install the hassio and the add-on, tried on another board but the problem still there.

Because I don't have the debugger so it is difficult to re-flash the firmware or check it.

Anyone could help me? Thanks in advance

**Comment by Koenkk** [comment]
Can you check http://www.zigbee2mqtt.io/information/zigbee2mqtt_fails_to_start.html#verify-that-you-put-the-correct-port-in-configurationyaml

**Comment by gewoonik** [comment]
you can check this site https://medium.com/@fedorets.alex/hass-io-zigbee2mqtt-io-the-simplest-way-b7375c9fba22

**Comment by shadow-fight** [comment]
Thanks For all the help. Have configured in the raspberry pi and all setting are correct. Finally it restored after I flash the latest version firmware in. 

Seems it just not in the working mode so that zigbee2mqtt could not communicate with the stick even if it connected in the right port.

Thanks again for all the respond.
