### ISSUE TITLE
Silvercrest 3 gang switch "HG06338" problem

### ISSUE THREAD

**Issue by jangelgon** [Koenkk/zigbee2mqtt#15284]
### What happened?

In the latest version 1.28.3 there is a problem with Silvercrest 3 gang switch "HG06338" it has stopped working, now it detects it as "TS011F_plug_3" and only the first socket can be controlled.

### Zigbee2MQTT version

1.28.3

### Adapter firmware version

20220928

### Adapter

zStack3x0

**Comment by Koenkk** [comment]
Lets continue in https://github.com/Koenkk/zigbee2mqtt/issues/15282

**Comment by Koenkk** [comment]
Fixed in 1.28.4!
