### ISSUE TITLE
Moes 2 gang zigbee + rf - recognised as TS011F_plug_3 after upgrading to version 1.28.3

### ISSUE THREAD

**Issue by gamajunior** [Koenkk/zigbee2mqtt#15280]
### What happened?

My Moes with 2-gang device was recognised normally, but after the last update it is now recognised as a smart plug
![moes](https://user-images.githubusercontent.com/78893093/205121917-217329b3-b398-4d44-8d69-84d6166bdbad.jpg)

As is being recognised now.

![now](https://user-images.githubusercontent.com/78893093/205123373-b5bba4e5-119a-4abd-a4f7-4d7b9ad0ae7c.jpg)

### What did you expect to happen?

Back to how it was in the previous version.

### Zigbee2MQTT version

1.28.3

### Adapter firmware version

20220219

### Adapter

SONOFF ZBDongle-P

**Comment by heinzma** [comment]
Same for Lidl HG06338. Repairing doesn't help.

**Comment by Koenkk** [comment]
Same as https://github.com/Koenkk/zigbee2mqtt/issues/15282, lets continue there.

**Comment by Koenkk** [comment]
Fixed in 1.28.4!

**Comment by Safs** [comment]
Problem still exists for TS011F_plug_1 plug.

**Comment by Safs** [comment]
Is anybody here?
