### ISSUE TITLE
Sengled E21-N1EA unsuport attribute

### ISSUE THREAD

**Issue by marc3k18** [Koenkk/zigbee2mqtt#15295]
### What happened?

{
    "brightness": 152,
    "color": {
        "x": 0.242,
        "y": 0.089
    },
    "color_mode": "xy",
    "color_temp": 500,
    "energy": 0.04,
    "last_seen": "2022-12-01T16:06:07-05:00",
    "level_config": {
        "on_level": "previous"
    },
    "linkquality": 117,
    "power": 0.2,
    "state": "OFF",
    "update": {
        "installed_version": "unknown",
        "state": "idle"
    },
    "device": {
        "applicationVersion": 38,
        "friendlyName": "Z2M - L - Ambiance Salon Gauche",
        "hardwareVersion": 1,
        "ieeeAddr": "0xb0ce1814001802c3",
        "manufacturerID": 4448,
        "manufacturerName": "sengled",
        "model": "E21-N1EA",
        "networkAddress": 45716,
        "powerSource": "Mains (single phase)",
        "stackVersion": 55,
        "type": "EndDevice",
        "zclVersion": 3
    },
    "power_on_behavior": null,
    "update_available": null
}

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20210708

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Error 2022-12-01 15:58:24Publish 'set' 'power_on_behavior' to 'Z2M - L - Garde-robe' failed: 'Error: Write 0xb0ce1814001816b3/1 genOnOff({"startUpOnOff":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by DanielWinks** [comment]
I can also confirm this is an issue.

When trying to set power_on_behavior for Sengled E21-N1EA bulbs, it results in an UNSUPPORTED_ATTRIBUTE error.

From my understanding, these bulbs added power on behavior options in one of the more recent firmware updates, so this should be a supported option in Z2M.

I can set the power on behavior for these bulbs when they're pair to Hubitat, as well, so it's definitely an available setting, and the firmware on my bulbs does indeed support it.
