### ISSUE TITLE
Can't pair more than 6 Xiaomi Devices

### ISSUE THREAD

**Issue by BenKuch** [Koenkk/zigbee2mqtt#1529]
I have issues to add more than 6 Xiaomi WSDCGQ11LM Device, after trying to add the 7th Sensor joining is refused, the blue LED on the Sensor is blinking just one time not 3 times short. There is no Debug information, nothing in the log. It seems to that the Coordinator is refusing to add the seventh Sensor. I run in this issue the second time with a second coordinator.

# Bug Report
## Debug Info
zigbee2mqtt version: 1.4.0
CC253X firmware version: 20190315

**Comment by Koenkk** [comment]
Can you try with the latest firmware?

**Comment by boojew** [comment]
I had a similar issue. 20190425 seems to have solved it.
