### ISSUE TITLE
Updates flagged for devices on Home Assistant restart

### ISSUE THREAD

**Issue by uvjim** [Koenkk/zigbee2mqtt#15293]
### What happened?

When restarting Home Assistant a numbr of devices report as having updates.  Looking at the Home Assistant UI though it appears that the version is listed as the JSON payload as per screenshot.

![image](https://user-images.githubusercontent.com/8431065/205148876-689ccf54-036d-4b36-9ba5-cf745c02dcda.png)

### What did you expect to happen?

Either the version to be displayed or no update to be flagged if there wasn't an update.

### Zigbee2MQTT version

1.28.3

### Adapter firmware version

0x26780700

### Adapter

RaspBee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10135849/log.txt)

**Comment by Koenkk** [comment]
What HA version is this?

**Comment by uvjim** [comment]
Sorry thought I'd put that in. 🤦‍♂️

![SmartSelect_20221202_160026_Home Assistant.jpg](https://user-images.githubusercontent.com/8431065/205334430-55c487b2-9b5d-4a1d-b6fa-803bad2a2932.jpg)

**Comment by Koenkk** [comment]
I cannot explain why this happens, it looks to me as a HA bug.

Zigbee2MQTT publishes this:

```
info  2022-12-01 20:00:06: MQTT publish: topic 'zigbee2mqtt/Gym - Right', payload '{"child_lock":null,"current":null,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Gym - Right","hardwareVersion":1,"ieeeAddr":"0xcc86ecfffe3b9b3b","manufacturerID":4098,"manufacturerName":"_TYZB01_hlla45kx","model":"TS011F_plug_3","networkAddress":63051,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"energy":null,"indicator_mode":null,"last_seen":"2022-12-01T20:00:06.769Z","linkquality":255,"power":null,"power_outage_memory":null,"state":"OFF","state_l1":"OFF","state_l2":"OFF","update":{"installed_version":"unknown","state":null},"update_available":null,"voltage":null}'

```

And the discovered value template is: `"value_template":"{{ value_json['update']['installed_version'] }}`


```
info  2022-12-01 19:59:55: MQTT publish: topic 'homeassistant/update/0xcc86ecfffe3b9b3b/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0xcc86ecfffe3b9b3b"],"manufacturer":"TuYa","model":"Smart plug (with power monitoring by polling) (TS011F_plug_3)","name":"Gym - Right"},"device_class":"firmware","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","json_attributes_topic":"zigbee2mqtt/Gym - Right","latest_version_template":"{% if value_json['update']['state'] == \"available\" %}{{ 'newer' }}{% else %}{{ value_json['update']['installed_version'] }}{% endif %}","latest_version_topic":"zigbee2mqtt/Gym - Right","name":"Gym - Right","payload_install":"{\"id\": \"0xcc86ecfffe3b9b3b\"}","state_topic":"zigbee2mqtt/Gym - Right","unique_id":"0xcc86ecfffe3b9b3b_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
```

**Comment by uvjim** [comment]
Interesting. It's not happening now after updating to `1.28.4` which also solved the issue I had with the TuYa devices - I wonder if that had anything to do with it.

I'll close this off and see if it happens again.

Thanks for looking into it.
