### ISSUE TITLE
Some devices disappeared from list but are still working

### ISSUE THREAD

**Issue by Kefut** [Koenkk/zigbee2mqtt#15316]
### What happened?

I have a few devices that dissapeared from the device list but are still visible in the config and are also still working. However as they are not in the list, I cannot do new configurations wih them.
Here you can see it in the RAW data:
![Bild1](https://user-images.githubusercontent.com/70171384/205317293-bdfa59e2-b463-41c7-91f6-7cdc9a2a13cb.png)
But it cannot be found under devices
![Bild2](https://user-images.githubusercontent.com/70171384/205317307-c3297bec-852a-49b4-9606-804309c417ce.png)

Additionally, you can see 7 devices in the group RAW data:
![Bild3](https://user-images.githubusercontent.com/70171384/205317624-3964a201-5679-470c-825f-1089784e73d5.png)
But in the list, you can only find 2:
![Bild4](https://user-images.githubusercontent.com/70171384/205317752-ca80ee5d-7d26-461c-82b1-4d294239b54c.png)

### What did you expect to happen?

I would expect to see all devices in the list that are also in the config. 

### How to reproduce it (minimal and precise)

I don't know

### Zigbee2MQTT version

1.28.2 commit: e66fe85

### Adapter firmware version

20201127

### Adapter

 Texas Instruments, Inc. CC2531 ZigBee

**Comment by Koenkk** [comment]
@nurikk this seems to be an issue in the frontend

**Comment by Kefut** [comment]
> @nurikk this seems to be an issue in the frontend

I also connect to the instance through node red and there I can only select the devices that are listed in the device list

**Comment by Kefut** [comment]
Any feedback on the issue?

**Comment by Koenkk** [comment]
Can you provide the ieee address of these device, your `data/database.db` and your zigbee2mqtt start debug log?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by Kefut** [comment]
> Can you provide the ieee address of these device, your `data/database.db` and your zigbee2mqtt start debug log?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

Hi,

files are attached: [Archiv.zip](https://github.com/Koenkk/zigbee2mqtt/files/10351658/Archiv.zip)

The missing devices are (I can find all of them in the raw config):
0xa4c13850a29eaaba
0xa4c13858c5bf3b68
0xa4c1386bec3453fb
0xa4c1388167dcca52
0xa4c138dbbb8d27db

Thanks for your help.

**Comment by Koenkk** [comment]
`0xa4c13850a29eaaba` is not in your database.db file. Probably it has left the network. Can you provide the herdsman debug log starting from the point where the device is paired until is disappears? 

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by Kefut** [comment]
> 

Hi,
do you mean that I should try to pair it again? Because the stupid thing for me is that it is actually controlled, but doesn't appear anymore.
The only time it currently appears in the herdsman debug is here:
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
Zigbee2MQTT:error 2023-01-06 13:40:36: Cannot find '0xa4c13850a29eaaba/1' of group 'OG2Carl Deckenlich'
Zigbee2MQTT:error 2023-01-06 13:40:36: Cannot find '0xa4c1388167dcca52/1' of group 'OG2Carl Deckenlich'
Zigbee2MQTT:error 2023-01-06 13:40:36: Cannot find '0xa4c13858c5bf3b68/1' of group 'OG2Carl Deckenlich'
Zigbee2MQTT:error 2023-01-06 13:40:37: Cannot find '0xa4c1386bec3453fb/1' of group 'OG2Carl Deckenlich'
Zigbee2MQTT:error 2023-01-06 13:40:37: Cannot find '0xa4c138dbbb8d27db/1' of group 'OG2Carl Deckenlich'

Thanks,
Christoph

**Comment by Koenkk** [comment]
Yes, pair them again.
