### ISSUE TITLE
Heiman HS2SK is missing energy consumption parameter

### ISSUE THREAD

**Issue by geelenbert** [Koenkk/zigbee2mqtt#15310]
### What happened?

I've switched from deconz to Z2MQTT with great results. But my Heiman HS2SK plugs don't report energy consumption under Zigbee 2 mqtt. 

When i was using Deconz, this paramter was available. 
![Screenshot 2022-12-02 at 10 40 12](https://user-images.githubusercontent.com/91923/205263204-cbf6d071-a119-4b6e-b28f-4eda5f4539cd.png)
![Screenshot 2022-12-02 at 10 42 29](https://user-images.githubusercontent.com/91923/205270546-03fa33da-311c-49fa-9ec2-f4286ab03dfc.png)
![Screenshot 2022-12-02 at 10 42 37](https://user-images.githubusercontent.com/91923/205270577-426395e2-0602-4575-b3bd-b7340e1edd7c.png)

### What did you expect to happen?

I expected the device to also have reporting of energy.

Tried to modify my own converter but it does not result un energy metering:

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['SmartPlug', 'SmartPlug-EF-3.0'],
        model: 'HS2SK',
        description: 'Smart metering plug',
        vendor: 'HEIMAN',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering],
        toZigbee: [tz.on_off],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement','seMetering']);
            await reporting.onOff(endpoint);
            await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
            await reporting.readMeteringMultiplierDivisor(endpoint);
            await reporting.rmsVoltage(endpoint);
            await reporting.rmsCurrent(endpoint);
            await reporting.activePower(endpoint);
        },
        exposes: [e.switch(), e.power(), e.current(), e.voltage(),e.energy()],
    },
];
`

But this results in values being NULL
![Screenshot 2022-12-02 at 11 19 59](https://user-images.githubusercontent.com/91923/205270762-e0aaf63f-d8b5-49c8-868e-7e4dc2424a3d.png)

### How to reproduce it (minimal and precise)

Addming device to Zigbee 2 mqtt

### Zigbee2MQTT version

1.28.4-1 

### Adapter firmware version

20220219

### Adapter

Zigstar Lan

**Comment by geelenbert** [comment]
In addidtion, i found this device under the zigbee certified devices:

[](https://csa-iot.org/csa_product/smart-metering-plug/
)

And the compliance documentation states the following clusters/attributes are supported:
 `<cluster>
<name>Simple Metering</name>
<code>0x0702</code>
<define>SIMPLE_METERING_CLUSTER</define>
<attribute side="server" code="0x0000" define="CURRENT_SUMMATION_DELIVERED" mandatory="true" name="current summation delivered">TRUE</attribute>
<attribute side="server" code="0x0200" define="STATUS" mandatory="true" name="status">TRUE</attribute>
<attribute side="server" code="0x0300" define="UNIT_OF_MEASURE" mandatory="true" name="unit of measure">TRUE</attribute>
<attribute side="server" code="0x0301" define="MULTIPLIER" mandatory="false" name="multiplier">TRUE</attribute>
<attribute side="server" code="0x0302" define="DIVISOR" mandatory="false" name="divisor">TRUE</attribute>
<attribute side="server" code="0x0303" define="SUMMATION_FORMATTING" mandatory="true" name="summation formatting">TRUE</attribute>
<attribute side="server" code="0x0304" define="DEMAND_FORMATTING" mandatory="false" name="demand formatting">TRUE</attribute>
<attribute side="server" code="0x0306" define="METERING_DEVICE_TYPE" mandatory="true" name="metering device type">TRUE</attribute>
<command receivedBy="client" code="0x00" name="GetProfileResponse" mandatory="false"/>
<command receivedBy="client" code="0x01" name="RequestMirror" mandatory="false"/>
<command receivedBy="client" code="0x02" name="RemoveMirror" mandatory="false"/>
<command receivedBy="client" code="0x03" name="RequestFastPollModeResponse" mandatory="false"/>
<command receivedBy="server" code="0x00" name="GetProfile" mandatory="false">FALSE</command>
<command receivedBy="server" code="0x01" name="RequestMirrorResponse" mandatory="false">FALSE</command>
<command receivedBy="server" code="0x02" name="MirrorRemoved" mandatory="false">FALSE</command>
<command receivedBy="server" code="0x03" name="RequestFastPollMode" mandatory="false">FALSE</command>
</cluster>`

**Comment by geelenbert** [comment]
Manualy reading these attributes results in:
![Screenshot 2022-12-02 at 12 09 04](https://user-images.githubusercontent.com/91923/205279716-81aad88f-14c8-4b40-b764-b18cbf855993.png)

Info 2022-12-02 12:08:50Read result of 'seMetering': {"unitOfMeasure":0,"multiplier":1,"currentSummDelivered":[0,241843],"divisor":10000,"summaFormatting":42,"demandFormatting":44,"meteringDeviceType":0}

**Comment by geelenbert** [comment]
I created a custom converter:

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;


module.exports = [
    {
        zigbeeModel: ['SmartPlug', 'SmartPlug-EF-3.0'],
        model: 'HS2SK',
        description: 'Smart metering plug',
        vendor: 'HEIMAN',
        fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering],
        toZigbee: [tz.on_off],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement','seMetering']);
            await reporting.onOff(endpoint);
            await reporting.readEletricalMeasurementMultiplierDivisors(endpoint);
            await reporting.rmsVoltage(endpoint);
            await reporting.rmsCurrent(endpoint);
            await reporting.activePower(endpoint);
            await reporting.readMeteringMultiplierDivisor(endpoint);
            await reporting.currentSummDelivered(endpoint);
        },
        exposes: [e.switch(), e.power(), e.current(), e.voltage(),e.energy()],
    },
];
`
![Screenshot 2022-12-28 at 08 40 43](https://user-images.githubusercontent.com/91923/209776582-5543b6b4-b6c4-40fb-9b8a-e45bac676cb0.png)

This results in the expected behaviour.  
@Koenkk  Suggestion to fix this in the main branch?

**Comment by Koenkk** [comment]
Done, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
