### ISSUE TITLE
Aqara S1 smart touch panel The switch text cannot be edited

### ISSUE THREAD

**Issue by MeowRay** [Koenkk/zigbee2mqtt#15318]
### What happened?

After I enter text for the switch, I can't click "Apply"
![image](https://user-images.githubusercontent.com/29674595/205330408-88047656-0160-4dbf-8bb1-7bd47e9f9f8f.png)

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

 20220219

### Adapter

CC2652P LAN

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend
