### ISSUE TITLE
Many devices have become disconnected, shown via Network map any sugestions 

### ISSUE THREAD

**Issue by c3reeman** [Koenkk/zigbee2mqtt#1531]
<img width="1205" alt="Screenshot 2019-05-15 at 16 59 55" src="https://user-images.githubusercontent.com/39133440/57790869-8468aa00-7733-11e9-84ee-c1685b925c2f.png">

As you can see by my network many of my devices have become disconnected pressing the reset button on the door sensors don't help.

Is there away to establish com's again without having to rebuild the network from scratch and having to re-flash my Diy routers, Interestingly these DIY routers show as connected in home assistant, but as the map shows clearly there not

Thanks in advance

**Comment by mpuff** [comment]
i have the same3 problem on all router devices.
but the devices are working.

![2019-05-16_19h28_52](https://user-images.githubusercontent.com/13885599/57874432-de8b6d00-7810-11e9-92c1-26963d9d9d84.png)

**Comment by mrosseel** [comment]
possibly related do #1536 ?
