### ISSUE TITLE
Light bulb Immax 07001L recognized as Immax 07005B

### ISSUE THREAD

**Issue by vahaldor** [Koenkk/zigbee2mqtt#15338]
### What happened?

Wrong identification of a zigbee device. Light bulb Immax 07001L recognized as Immax 07005B

### Zigbee2MQTT version

 1.28.4-1

### Adapter firmware version

 20210708

### Adapter

zStack3x0 - Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by Koenkk** [comment]
The zigbee model of this device is `IM-Z3.0-DIM`. Seems both devices use the same, so we cannot distinguish them.  I've changed the model to `07001L/07005B`

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
