### ISSUE TITLE
Centralite 3315-Geu

### ISSUE THREAD

**Issue by ExMacro** [Koenkk/zigbee2mqtt#15352]
### Link

https://www.centralite.com/products/water-sensor

### Database entry

{"id":64,"type":"EndDevice","ieeeAddr":"0x000d6f000a863685","nwkAddr":58837,"manufId":4174,"manufName":"CentraLite","powerSource":"Battery","modelId":"3315-Geu","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff095e5d","zoneState":1}},"genPollCtrl":{"attributes":{"checkinInterval":14400}},"genPowerCfg":{"attributes":{"batteryVoltage":30}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00212effff095e5d","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00212effff095e5d","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff095e5d","endpointID":1}],"configuredReportings":[{"cluster":1026,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}},"2":{"profId":49887,"epId":2,"devId":12,"inClusterList":[0,1,3,15,2821],"outClusterList":[3],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"stackVersion":2,"hwVersion":1,"dateCode":"����������������","zclVersion":1,"interviewCompleted":true,"meta":{"configured":574458647},"lastSeen":1670172788990,"defaultSendRequestWhen":"active"}

### Comments

I tried to pair this water leak sensor to Zigbee2MQTT but it wasn't recognized. Almost the same devices are found in the database but this reported itself after pairing as "3315-Geu". After making my own .js file and experimenting I got it working. I basically copied the settings of Iris 3315 leak sensor and updated the model name reported by Zigbee2MQTT. This is sold at least here in Finland (an EU version of the leak sensor I think) so it would make a good addon to the supported devices list.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['3315-Geu'],
        model: '3315-Geu',
        vendor: 'Centralite',
        description: 'Centralite 3-Series Water Sensor',
        fromZigbee: [fz.temperature, fz.ias_water_leak_alarm_1, fz.battery],
        exposes: [e.temperature(), e.water_leak(), e.battery_low(), e.tamper(), e.battery()],
        toZigbee: [],
        meta: {battery: {voltageToPercentage: '3V_2500'}},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'genPowerCfg']);
            await reporting.temperature(endpoint);
            await reporting.batteryVoltage(endpoint);
        },    
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
