### ISSUE TITLE
Philips Hue  Xamento middelgrote plafondlamp

### ISSUE THREAD

**Issue by Creepyki** [Koenkk/zigbee2mqtt#15370]
### Link

https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-xamento-middelgrote-plafondlamp/8719514452251

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0x001788010c685412","nwkAddr":33014,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003526301","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1670254577465,"defaultSendRequestWhen":"immediate"}

### Comments

I think this lamp is the same as the lamp below, but it is not yet supported. Perhaps the country of origin is a problem here. This lamp was purchased from Philips in the Netherlands. I've tried to create it via an external converter, but I can't get it to work. Can someone explain to me what I'm doing wrong or add it?

915005997801 (Philips Hue Xamento M) vs. 915005997901 (Philips Hue Xamento L)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['929003526301'],
    model: '929003526301',
    vendor: 'Signify Netherlands B.V.',
    description: 'Hue White & Color Ambiance Xamento M',
    extend: hueExtend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]})
};

module.exports = definition;
```

**Comment by danieledwardgeorgehitchcock** [comment]
Can you check the color temp range by following [this guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-1-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature)
