### ISSUE TITLE
[Feature request]: Split Aqara from Xiaomi

### ISSUE THREAD

**Issue by ZZJHONS** [Koenkk/zigbee2mqtt#15388]
### Is your feature request related to a problem? Please describe

Aqara is an independent company from Xiaomi, not a white label like Roborock or MiJia

<img width="558" alt="image" src="https://user-images.githubusercontent.com/1063368/205875162-733ecd9a-ca6b-4985-b116-f7c6a6b6d814.png">

https://www.reddit.com/r/homeautomation/comments/wi0jc0/new_aqara_s1_scene_plates_installed/is9vpgb/?context=3

https://www.crunchbase.com/search/funding_rounds/field/organizations/funding_total/lumi-united-technology

### Describe the solution you'd like

Create a new Vendor and move the Aqara devices.

### Describe alternatives you've considered

Aqara is gaining marketshare and it's releasing new products each years so I think it's better to split ASAP as official Xiaomi brands will grow too.

Actually the name of the company is Lumi and Aqara the brand of products:

https://www.linkedin.com/company/lumi-united-technology-co-ltd/about/

### Additional context

AndrewFromAqara is a worker that usually replies in the Aqara subreddit

PD: Will a Issue in the fronted also be needed?

**Comment by ZZJHONS** [comment]
Headsup

**Comment by ZZJHONS** [comment]
More comments about this:

https://www.reddit.com/r/HomeKit/comments/103zy5a/comment/j3bp269/?context=3

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1063368/211158458-d1f3b3d6-c5e6-4645-8953-2f98c5701cc7.png">

**Comment by ZZJHONS** [comment]
headsup!

**Comment by ZZJHONS** [comment]
:(

**Comment by Koenkk** [comment]
Could you make a pr to do the split?

**Comment by ZZJHONS** [comment]
Sorry, I don't have the time or expertise to do this now
