### ISSUE TITLE
coordinator_backup.json is not created

### ISSUE THREAD

**Issue by moritzbeck01** [Koenkk/zigbee2mqtt#15408]
### What happened?

I noticed that the `coordinator_backup.json` file was not present under the `/app/data` path on my Docker install.
The Docker logs do mention that this directory is used for backups. All the other files are also present there.
I run a fairly newly migrated (by copying the `database.db` and `configuration.yaml` files) install with maybe a dozen devices.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

0x26580700

### Adapter

ConBee 2

**Comment by moritzbeck01** [comment]
> You can create it probably via /settings/tools -> request z2m backup in UI.

That doesn't actually create anything, it just zips the mentioned directory and makes it available for download.

**Comment by samip5** [comment]
Huh, for me it does create that file although not using ConBee. :)

**Comment by moritzbeck01** [comment]
> 

So if you delete the file and then request a backup, it gets recreated?

**Comment by moritzbeck01** [comment]
> Conbee II doesn't support backups, so no `coordinator_backup.json` will be created when using this adapter. Only Texas Instruments based adapters support this.

Ah, makes sense then. The docs are really ambiguous about this, even with hindsight.
So how would I go about migrating to e.g. ZHA/zigpy then?

**Comment by Koenkk** [comment]
> The docs are really ambiguous about this, even with hindsight.

You are right, I updated the docs.

> So how would I go about migrating to e.g. ZHA/zigpy then?

This will require repairing all devices. Even when you would have a `coordinator_backup.json` migrating without repairing is not possible since ZHA is not compatible with the Z2M `database.db` (and vice-versa).

**Comment by moritzbeck01** [comment]
> You are right, I updated the docs.

Thanks!

> This will require repairing all devices. Even when you would have a `coordinator_backup.json` migrating without repairing is not possible since ZHA is not compatible with the Z2M `database.db` (and vice-versa).

I thought both support the open coordinator backup?

**Comment by Koenkk** [comment]
> I thought both support the open coordinator backup?

Yes we do, but this does contain the information stored in `database.db` which zigbee2mqtt requires (I have no clue if ZHA has such file). The `coordinator_backup.json` file only contains the data stored on the coordinator side.
