### ISSUE TITLE
missing state change for ubisys s2

### ISSUE THREAD

**Issue by usrstephan** [Koenkk/zigbee2mqtt#15437]
### What happened?

set up a new machine with zigbee2mqtt 1.28.4 and added my devices.
after changing the state (state_l1) with the integrated button no changes are reported

### What did you expect to happen?

changes of the state triggered by the integrated button should change the state value

### How to reproduce it (minimal and precise)

no problem in older versions (installed 2 years ago and regularly updated)

### Zigbee2MQTT version

1.28.4 commit: 52e545f9

### Adapter firmware version

20221102

### Adapter

CC2652RB

**Comment by Nezz** [comment]
I have the same issue with S2 and D1.

**Comment by usrstephan** [comment]
for me the following setup works
![dimmer](https://user-images.githubusercontent.com/38238708/207262748-6c45ff1b-4dd0-4d5f-b2e7-b35e8b08859b.png)
does anyone know, why they changed automatic reporting settings or how to change these settings?

**Comment by Nezz** [comment]
`ubisysMinimumOnLevel` sounds incorrect to me. That's the attribute for the minimum brightness when turning on the light, not the current brightness. When I try to bind `currentLevel`:
![image](https://user-images.githubusercontent.com/431167/207309138-f2e8a2ec-6f30-4411-8543-207a30920462.png)
It gets bound as `ubisysMinimumOnLevel` just like you have it.

**Comment by WhistleMaster** [comment]
I have the same issue. I've added 15 Ubisys S2 to my setup and for all of them, the states are not reported in Z2M when operated locally / manually.
