### ISSUE TITLE
Cannot Start Add-on

### ISSUE THREAD

**Issue by thanhkeyi** [Koenkk/zigbee2mqtt#1544]
When I want to start the add-on this is shown in the log. What can I do now?

Log: 

> ./run.sh: line 10:    10 Illegal instruction     (core dumped) python3 set_config.py "$CONFIG_PATH" "$DATA_PATH"
> ./run.sh: line 25:    11 Illegal instruction     (core dumped) ZIGBEE2MQTT_DATA="$DATA_PATH" pm2-runtime start npm -- start

My Config:

> {
>   "data_path": "/share/zigbee2mqtt",
>   "homeassistant": true,
>   "permit_join": true,
>   "mqtt_base_topic": "zigbee2mqtt",
>   "mqtt_server": "mqtt://homeassistant",
>   "serial_port": "/dev/ttyACM0",
>   "devices": [],
>   "network_key": [],
>   "mqtt_user": "...",
>   "mqtt_pass": "..."
> }

**Comment by Koenkk** [comment]
Could you open this issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues ? (as this is about the addon).
