### ISSUE TITLE
[Feature request]: ZigBee GU10 Smart Sync Full Color LED Dimmable Party Light Bulbs RGBCCT 2200-6500K C+W 5W

### ISSUE THREAD

**Issue by Hadatko** [Koenkk/zigbee2mqtt#15451]
### Is your feature request related to a problem? Please describe

Hello i bought this smart bulb: https://www.moeshouse.com/collections/smart-light/products/zb-td5-rcw-gu10-ms
In z2m it is showing up as https://www.zigbee2mqtt.io/devices/ZLD-RCW.html
![image](https://user-images.githubusercontent.com/13130700/206594396-1afbed4a-27bc-4e05-a540-34b2e778a6d5.png)

I thought it is ok as it worked more or less, but by the time (1h) it stopped responding the request. Hopefully support for device will solve the issue.

### Describe the solution you'd like

I will try to add PR during this week.

### Describe alternatives you've considered

You can add support :D

### Additional context

;)

**Comment by Dutchy-79** [comment]
I have the same bulbs and yesterday all 5 stopped responding and show offline.
