### ISSUE TITLE
[New device support]: Danfoss Ally 'eTRV0103'

### ISSUE THREAD

**Issue by lux73** [Koenkk/zigbee2mqtt#15464]
### Link

https://www.zigbee2mqtt.io/devices/014G2461.html

### Database entry

{"id":48,"type":"EndDevice","ieeeAddr":"0x70ac08fffe548519","nwkAddr":2171,"manufId":4678,"manufName":"Danfoss\u0000","powerSource":"Battery","modelId":"eTRV0103","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,10,32,513,516,2821],"outClusterList":[0,25],"clusters":{"genBasic":{"attributes":{"modelId":"eTRV0103","manufacturerName":"Danfoss\u0000","powerSource":3,"zclVersion":3,"appVersion":20,"stackVersion":8,"hwVersion":69,"dateCode":"20221130","swBuildId":"00.20.0008 00.20"}},"genPollCtrl":{"attributes":{"checkinInterval":1200}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"hvacThermostat":{"attributes":{"localTemp":2165,"pIHeatingDemand":0,"danfossWindowOpenFeatureEnable":1,"danfossWindowOpenExternal":0,"danfossDayOfWeek":4,"danfossTriggerTime":660,"danfossAlgorithmScaleFactor":1,"danfossHeatAvailable":1,"danfossMountedModeControl":0,"danfossMountedModeActive":0,"danfossExternalMeasuredRoomSensor":-8000,"danfossRadiatorCovered":0,"danfossLoadBalancingEnable":1,"danfossLoadRoomMean":-8000,"danfossAdaptionRunControl":0,"danfossAdaptionRunSettings":1,"systemMode":4,"danfossLoadEstimate":147,"danfossThermostatOrientation":0,"occupiedHeatingSetpoint":1600,"setpointChangeSource":2,"danfossWindowOpenInternal":1,"danfossAdaptionRunStatus":0,"danfossHeatRequired":0}},"hvacUserInterfaceCfg":{"attributes":{"keypadLockout":0}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b002390da8c","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002390da8c","endpointID":1},{"cluster":513,"type":"endpoint","deviceIeeeAddress":"0x00124b002390da8c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":513,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":18,"minRepIntval":0,"maxRepIntval":3600,"repChange":10},{"cluster":513,"attrId":16402,"minRepIntval":60,"maxRepIntval":62000,"repChange":1},{"cluster":513,"attrId":16384,"minRepIntval":60,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16433,"minRepIntval":60,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16405,"minRepIntval":60,"maxRepIntval":62000,"repChange":1},{"cluster":513,"attrId":16461,"minRepIntval":60,"maxRepIntval":3600,"repChange":1},{"cluster":513,"attrId":16463,"minRepIntval":60,"maxRepIntval":62000,"repChange":1},{"cluster":513,"attrId":8,"minRepIntval":0,"maxRepIntval":"60","repChange":"1"}],"meta":{}}},"appVersion":20,"stackVersion":8,"hwVersion":69,"dateCode":"20221130","swBuildId":"00.20.0008 00.20","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-867661285},"lastSeen":1670604267225,"defaultSendRequestWhen":"fastpoll"}

### Comments

today i got a new Danfoss Ally with ZigbeeModel: **eTRV0103** - it's declared as unsupported

after changing "zigbee-herdsman-converters/devices/danfoss.js" line 14 

from:

`zigbeeModel: ['eTRV0100', 'eTRV0101'],`

to:

`zigbeeModel: ['eTRV0100', 'eTRV0101', 'eTRV0103'],`

anything working as expected like my old Allys (eTRV0101)

Please add to repo

Thank you :-)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
