### ISSUE TITLE
[New device support]: New manufacturer TuYA TS0601_thermostat

### ISSUE THREAD

**Issue by radekposvar** [Koenkk/zigbee2mqtt#15466]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

### Database entry

{"id":27,"type":"EndDevice","ieeeAddr":"0x04cd15fffe3b7397","nwkAddr":51745,"manufId":4098,"manufName":"_TZE200_do5qy8zo","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_do5qy8zo","stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1670604374759,"defaultSendRequestWhen":"immediate"}

### Comments

Hello, I just bought another TRV MOES TS0601 _TZE200_do5qy8zo and I suddenly realized it is not supported. I have the same looking one from manufacturer _TZE200_ywdxldoj which works fine. Is it possible to add support also for this one? I belive it works the same as the previous one.

Thank you very much,
Radek

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
