### ISSUE TITLE
Green Power Switch - Vimar 03906 issue

### ISSUE THREAD

**Issue by datsrt02** [Koenkk/zigbee2mqtt#15471]
### What happened?

I use GreenPower switch vimar 03906 and Sonoff Dongle P. I paired it success in zigbee2mqtt dashboard. 
But when i press any button on switch, i cant see any messsage in log of zigbee2mqtt. 

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

2022.11.2

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

[10:49:33] INFO: Preparing to start...
[10:49:34] INFO: Socat not enabled
[10:49:35] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2022-12-10 10:49:36: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-12-10 10:49:36: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-10.10-49-36' filename: log.txt
Zigbee2MQTT:info  2022-12-10 10:49:36: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-10 10:49:36: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:debug 2022-12-10 10:49:36: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyS1"}}'
Zigbee2MQTT:info  2022-12-10 10:49:39: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-12-10 10:49:39: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:debug 2022-12-10 10:49:39: Zigbee network parameters: {"channel":11,"extendedPanID":"0x00124b0029daebe7","panID":6754}
Zigbee2MQTT:info  2022-12-10 10:49:39: Currently 1 devices are joined:
Zigbee2MQTT:info  2022-12-10 10:49:39: 03906 (0x000000000170e1e9): PTM 215Z - EnOcean Pushbutton transmitter module (GreenPower)
Zigbee2MQTT:info  2022-12-10 10:49:39: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2022-12-10 10:49:40: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:debug 2022-12-10 10:49:40: Using MQTT login with username: mqtt-user
Zigbee2MQTT:info  2022-12-10 10:49:40: Connected to MQTT server
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-12-10 10:49:40: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:debug 2022-12-10 10:49:40: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b0029daebe7","panID":6754},"permit_join":false,"version":"1.28.4"}'
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0x00124b0029daebe7","panID":6754},"permit_join":false,"version":"1.28.4"}'
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'homeassistant/sensor/0x000000000170e1e9/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 action","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'homeassistant/sensor/0x000000000170e1e9/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2022-12-10 10:49:40: MQTT publish: topic 'zigbee2mqtt/03906', payload '{"action":null,"linkquality":null}'
Zigbee2MQTT:info  2022-12-10 10:49:40: Zigbee2MQTT started!
Zigbee2MQTT:debug 2022-12-10 10:49:40: Received MQTT message on 'homeassistant/sensor/0x000000000170e1e9/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 action","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:debug 2022-12-10 10:49:40: Received MQTT message on 'homeassistant/sensor/0x000000000170e1e9/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:debug 2022-12-10 10:49:40: Received MQTT message on 'homeassistant/sensor/0x000000000170e1e9/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 action","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:debug 2022-12-10 10:49:40: Received MQTT message on 'homeassistant/sensor/0x000000000170e1e9/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x000000000170e1e9"],"manufacturer":"EnOcean","model":"Pushbutton transmitter module (PTM 215Z)","name":"03906"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/03906","name":"03906 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/03906","unique_id":"0x000000000170e1e9_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:debug 2022-12-10 10:54:36: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-12-10 10:59:36: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2022-12-10 11:04:36: Saving state to file /config/zigbee2mqtt/state.json

**Comment by pawelwaniek** [comment]
@datsrt02 can you share any details how you fixed it?
