### ISSUE TITLE
Update from Webui

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#15475]
### Is your feature request related to a problem? Please describe

If possible update z2m from the webui.

### Describe the solution you'd like

a button upddate by the settings

### Describe alternatives you've considered

Hope this is possibel

### Additional context

Love z2m very much only update manualy in a home autamation :-)

**Comment by Grumpelumpf** [comment]
or at least an Update notification at the webUI is possible? "Update 1.28.4 is availible now"

P.S. this tool is realy great work ! Thank you.
