### ISSUE TITLE
[Feature request]: Vimar 14593 switch missing activePower

### ISSUE THREAD

**Issue by mattiazeni** [Koenkk/zigbee2mqtt#15482]
### Is your feature request related to a problem? Please describe

I have a Vimar 14593 switch with embedded power sensor. I correctly added it to zigbe2mqtt and to HA and I am able to switch it on and off. However, it seems the active power consumption is not available. The sensor is connected in zigbee mode.

### Describe the solution you'd like

I would like this device to expose also the active power consumed in realtime. 

### Describe alternatives you've considered

I don't think there is an alternative.

### Additional context

I explored the device in the zigbee2mqtt windows in HA and I can see it exposes a cluster haElectricalMeasurement.

<img width="311" alt="Screenshot 2022-12-10 at 7 37 34 PM" src="https://user-images.githubusercontent.com/8925776/206870564-b6813e0a-4965-4d76-a181-a7993458a6e3.png">

I then went to the Dev console and I am able to retrieve the power consumption value as showed below:
 
<img width="823" alt="Screenshot 2022-12-10 at 7 46 21 PM" src="https://user-images.githubusercontent.com/8925776/206870636-b31b111e-4de0-460f-806c-5b627c0e1f97.png">

And the logs:

> Zigbee2MQTT:debug 2022-12-10 20:34:04: Received MQTT message on 'zigbee2mqtt/Presa Tv/10/set' with data '{"read":{"attributes":["activePower"],"cluster":"haElectricalMeasurement","options":{}}}'
> Zigbee2MQTT:debug 2022-12-10 20:34:04: Publishing 'set' 'read' to 'Presa Tv'
> Zigbee2MQTT:debug 2022-12-10 20:34:04: Received Zigbee message from 'Presa Tv', type 'readResponse', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 10 with groupID 0
> Zigbee2MQTT:debug 2022-12-10 20:34:04: No converter available for '14593' with cluster 'haElectricalMeasurement' and type 'readResponse' and data '{"activePower":0}'

**Comment by mattiazeni** [comment]
I am new to zigbee2mqtt and HA but I am a Software Engineer, if you can point me to what I should modify and an example I can probably help.

**Comment by danieledwardgeorgehitchcock** [comment]
I have one of these units - will see if I can add the functionality over the next few days

**Comment by mattiazeni** [comment]
I made some progress yesterday but being the first time I'm not sure this is the correct way, I started with HA and zigbee2mqtt only two days ago :)

With this:


> zigbeeModel: ['Mains_Power_Outlet_v1.0'],
> model: '14593',
> vendor: 'Vimar',
> description: '16A outlet IoT connected',
> extend: extend.switch(),
> fromZigbee: [fz.electrical_measurement],
> configure: async (device, coordinatorEndpoint, logger) => {
>        const endpoint = device.getEndpoint(10);
>        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
> },
> exposes: [e.switch(), e.power()]


It correctly shows power consumption. 

<img width="391" alt="Screenshot 2022-12-11 at 9 32 06 AM" src="https://user-images.githubusercontent.com/8925776/206894002-6781de8e-e54f-4c4c-b8e0-033e03807342.png">

<img width="438" alt="Screenshot 2022-12-11 at 9 36 15 AM" src="https://user-images.githubusercontent.com/8925776/206894097-eaa374e6-6d65-4dad-b47e-9fdb610e1554.png">

However the value it 10x the actual one. It can be fixed playing with the power_calibration parameter:
<img width="546" alt="Screenshot 2022-12-11 at 9 32 24 AM" src="https://user-images.githubusercontent.com/8925776/206894005-f6ddd285-9a8f-4959-ac1e-9c619aadc3e1.png">

**Comment by mattiazeni** [comment]
There is no readEletricalMeasurementConverterAttributes() function in fromZigbee.js even though I see a comment that refers to it:

```
Zigbee2MQTT:error 2022-12-11 10:46:08: Failed to configure 'Presa Tv', attempt 3 (ReferenceError: readEletricalMeasurementConverterAttributes is not defined
```

**Comment by danieledwardgeorgehitchcock** [comment]
D'oh!

I saw that and thought that might be the solution! It looks like it should be but yes, when I was looking at it, I couldn't find it either.. Not even an issue about it which is strange..?

Out of curiosity, do you get any response from reading the `multiplier` or `devisor` attributes from `haElectricalMeasurement`?

**Comment by mattiazeni** [comment]
Yep I can read them:

```
2022-12-11 11:17:00Read result of 'haElectricalMeasurement': {"acPowerMultiplier":10,"acPowerDivisor":1}
```

**Comment by danieledwardgeorgehitchcock** [comment]
Ok,

So I think this may be a quirk of the Vimar device.

The factor calculation for the converter is `acPowerMultiplier` * `acPowerDivisor` which in this case, would equate to 10 which is the factor offset that you are experiencing.

For this to be calculated correctly for the device, I'd have thought both the `acPowerMultiplier` and `acPowerDivisor` should have a value of 1.

We can get around this by creating a local fromZigbee converter:

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const fzLocal = {
    vimar_active_power: {
        cluster: 'haElectricalMeasurement',
        type: ['attributeReport', 'readResponse'],
        convert: async (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty('activePower')) {
                payload.power = msg.data['activePower'];
            };
        return payload;
        },
    },
};

const definition = {
    zigbeeModel: ['Mains_Power_Outlet_v1.0'],
    model: '14593',
    vendor: 'Vimar',
    description: '16A outlet IoT connected',
    fromZigbee: [fz.on_off, fz.ignore_basic_report, fzLocal.vimar_active_power],
    toZigbee: [tz.on_off],
    exposes: [e.switch(), e.power()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(10);
        await readEletricalMeasurementConverterAttributes(endpoint);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
    },
};

module.exports = definition;
```

**Comment by mattiazeni** [comment]
It works! Thanks a lot.

Just a minor fix, we need to declare the payload variable :)

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const fzLocal = {
    vimar_active_power: {
        cluster: 'haElectricalMeasurement',
        type: ['attributeReport', 'readResponse'],
        convert: async (model, msg, publish, options, meta) => {
            var payload = {}
            if (msg.data.hasOwnProperty('activePower')) {
                payload.power = msg.data['activePower'];
            };
            return payload;
        },
    },
};

const definition = {
    zigbeeModel: ['Mains_Power_Outlet_v1.0'],
    model: '14593',
    vendor: 'Vimar',
    description: '16A outlet IoT connected',
    fromZigbee: [fz.on_off, fz.ignore_basic_report, fzLocal.vimar_active_power],
    toZigbee: [tz.on_off],
    exposes: [e.switch(), e.power()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(10);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
    },
};

module.exports = definition;
```

**Comment by danieledwardgeorgehitchcock** [comment]
That we do! Good spot!

Do you want to submit a PR or do you want me to?

**Comment by mattiazeni** [comment]
You solved it, the honour is yours :)

**Comment by mattiazeni** [comment]
I found some time today, I did it [here](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5147).

**Comment by mattiazeni** [comment]
I made a brand new installation of HA and with the stock config such as below and without multipliers it works correctly.

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['Mains_Power_Outlet_v1.0'],
    model: '14593',
    vendor: 'Vimar',
    description: '16A outlet IoT connected',
    fromZigbee: [fz.on_off, fz.ignore_basic_report, fz.electrical_measurement],
    toZigbee: [tz.on_off],
    exposes: [e.switch(), e.power()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(10);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
    },
};

module.exports = definition;
```
