### ISSUE TITLE
End Devices (mostly Tuya) are unable to join via router on EZSP

### ISSUE THREAD

**Issue by AlexMKX** [Koenkk/zigbee2mqtt#15507]
### What happened?

Hello. 
Please find my report below.
While creating network with EZSP (ZB Dongle-E) I noticed that some end devices are unable to join via routers.  
In the end, if I move device to the coordinator - it will join without any problems.

The steps are folowing : 
1. Select "Permit join" - to allow joining through the any device. 
2. Move away from coordinator, to have the devices join via nearest router.
3. Start the join procedure.
4. Observe that nothing is happened : 
4.1. No notices in Z2M dashboard
4.2. Device tries to join for a long time without success.

This is related to "join-permit-generic" logs

1. Select the "allow join through specific device" and choose the nearest router.
2. Repeat join procedure (move away from coordinator, etc).
3. Observe, that device is trying to join:
3.1. Join notifications appear in the Z2M dashboard
4. In couple seconds after the join attempt, the device leaving network on it's own and it tries to join couple times again. Without success.
5. Join never completes, though Z2M says : join request, joining, joined supported device, configuring, configured. And finally : left the network

The above is related to "join-permit-specific" logs folder from the attached tar.gz 
I have attached logs with serial dumps and application logs.

In the first case I see following errors in the log : 
```
 2022-12-12T10:48:49.323Z zigbee-herdsman:adapter:ezsp:uart Error while parsing to ZpiObject 'RangeError: Attempt to access memory outside buffer bounds
     at new NodeError (node:internal/errors:393:5)
     at boundsError (node:internal/buffer:84:11)
     at Buffer.readUInt16LE (node:internal/buffer:243:5)
     at Buffer.readUIntLE (node:internal/buffer:180:17)
     at Function.deserialize (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/types/basic.ts:19:67)
     at new EZSPFrameData (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:83:54)
     at Ezsp.onFrameReceived (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:294:21)
     at SerialDriver.emit (node:events:513:28)
     at SerialDriver.handleDATA (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:228:14)
     at SerialDriver.onParsed (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:175:22)'

```
The mentioned device mac is 0xa4c13834f8a77989 (kabinet-occupancy-3)

The mentioned logs are for the IH012-RT01 PIR sensor, same happens to TS0203 door sensor. This happens with different routers (all routers) I have on network.

### Zigbee2MQTT version

1.28.4-dev commit: 21a30fc

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8 ZB-Dongle-E

### Debug log

[join-logs.tar.gz](https://github.com/Koenkk/zigbee2mqtt/files/10207306/join-logs.tar.gz)

**Comment by AlexMKX** [comment]
Some additional information. I have noticed that some devices are still leaving/joining on voluntary basis : 
```
info  2022-12-13 12:18:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"1f-shower-room-occupancy","ieee_address":"0xb4e3f9fffe02e267"},"type":"device_leave"}'
info  2022-12-13 12:18:12: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"1f-shower-room-occupancy","ieee_address":"0xb4e3f9fffe02e267"},"type":"device_joined"}'
info  2022-12-13 12:18:12: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"1f-shower-room-occupancy","ieee_address":"0xb4e3f9fffe02e267","status":"started"},"type":"device_interview"}'

```
These is a IH012-RT01, it have been paired hour before this rejoin occured. Today morning I have noticed that some RT01 devices were rejoining as well. 
The major problem here is a battery drain. Since RT01 is a battery powered device, it drains much faster with such rejoins.

**Comment by LeoDJ** [comment]
This issue is not stale

**Comment by kirovilya** [comment]
try with 1.30.2 version

**Comment by mdzhigarov** [comment]
same problem with 1.32.2

**Comment by Kitchigo** [comment]
I have change to ZBDongle-E to ZBDongle-P, and now all work perfectectly in 1.30.1.

**Comment by mdzhigarov** [comment]
Changed how? Did you buy another device?

**Comment by Kitchigo** [comment]
> 

Yes, I buy a ZBDongle-P (CC2652P), is stable than a model -E

**Comment by ThatMishakov** [comment]
Hello. I have changed my coordinator, and have the same issue, on 1.35.3-dev commit: [22d3336](https://github.com/Koenkk/zigbee2mqtt/commit/22d3336) and EZSP v13 (7.4.0.0 build 0). None of my devices (Philips, Innr, Ledvance, Ikea, Aqara, Gledopto, TuYa), both routers and end devices, can join through any of the routers, but do join and work fine if I bring them to the coordinator (though I have some devices which I cannot move and thus can't pair them) and also steer to use a router once I move them away from the coordinator. Once joined, I haven't noticed any issues (and the network seems to be quicker than with CC2652P). In addition, to endless joining, I have seen Z2M crash with the following errors:
```
Error: Failure send findKeyTableEntry:{"type":"Buffer","data":[231,0,1,117,0,246,45,248,254,255,219,180,132,1]}
    at /home/misha/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:646:23
    at Queue.execute (/home/misha/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Driver.cleanupTClinkKey (/home/misha/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:419:24)
```
```
/home/misha/zigbee2mqtt/lib/zigbee.ts:89
            await device.resolveDefinition();
                         ^
TypeError: Cannot read properties of undefined (reading 'resolveDefinition')
    at Controller.<anonymous> (/home/misha/zigbee2mqtt/lib/zigbee.ts:89:26)
    at Controller.emit (node:events:518:28)
    at Controller.selfAndDeviceEmit (/home/misha/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:529:14)
    at Controller.onDeviceJoined (/home/misha/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:588:22)
```
After the second error, the devices normally leave the join mode (e.g. indicator stops blinking)

I have also seen my adapter just disconnect when trying to join some devices (adapter disconnected error)
    
I don't have a sniffer anymore, but here are some logs from ZBDongle-E working as a router attempting to join a network through another router (Philips Hue White light, the new one with Bluetooth), may be those could be of a help: https://pastebin.com/cA0HMJZc
Here are some more logs of ZBDongle-E trying to join https://pastebin.com/kvaZVWmH
While the joining is in progress, Z2M says that the device has interviewed successfully, and I could sometimes even briefly send commands and control the devices, but they themselves indicate that they have not joined the network, and endlessly leave and rejoin it
