### ISSUE TITLE
Smarthings Water leak sensor (2018 model) - IM6001-WLP01

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#15523]
### What happened?

For some reason when I pair the advice i cant get all the entities exposed. 
![image](https://user-images.githubusercontent.com/58960644/207228927-8993cbad-a2ef-4709-8ef0-10c44848b720.png)

But if i try and repair i get the opposite entities (see example of another ST Water Sensor that shows Battery etc
![image](https://user-images.githubusercontent.com/58960644/207228984-041db60d-5607-4e9d-b5e6-25f23e3f9acf.png)

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20220219

### Adapter

Sonoff Coordinator

**Comment by sjorge** [comment]
Do the nulls disapear if you manually bridge the contact? (A drop of water should work)

The missing values after you repaired are on the ssIasZone cluster which AFAIK has no steps in the configure function to setup.
Only msTempersture and genPowerCfg do, and those are the only values populated.

**Comment by cloudbr34k84** [comment]
Thanks, you I bridged the gap as you call it. Seems to be working now thanks !!
