### ISSUE TITLE
NOT ISSUE: Fothcoming Aqara T1 Sensor

### ISSUE THREAD

**Issue by GerSant** [Koenkk/zigbee2mqtt#1554]
Hi, do you known if zigbee2mqtt will be compatible with forthcoming Aqara T1 sensors? That sensors will be compatible with Zigbee 3.0

Regards

**Comment by Koenkk** [comment]
Probably yes

**Comment by james-fry** [comment]
Any links for these?

**Comment by Koenkk** [comment]
Once the device is released support will probably be added, closing for now.

**Comment by rkarma69** [comment]
Hi Koenkk
I am testing Aqara T1 versions at the moment. I am afraid that it doesn't work.
Please kindly support us to test it.
Thanks in advance.

**Comment by Koenkk** [comment]
Where can I buy them?
