### ISSUE TITLE
No Start after Update to newest HOAS Base System

### ISSUE THREAD

**Issue by sebjosb** [Koenkk/zigbee2mqtt#15541]
### What happened?

After Updating to the newest Home Assistant Base System 9.4, the Add On will not start 

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

2022.11.2

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_

### Debug log

[23:25:06] INFO: Preparing to start...
[23:25:06] INFO: Socat not enabled
[23:25:08] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-12-13 23:25:13: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-13.23-25-13' filename: log.txt
Zigbee2MQTT:info  2022-12-13 23:25:13: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-13 23:25:13: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:error 2022-12-13 23:26:57: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-13 23:26:57: Failed to start zigbee
Zigbee2MQTT:error 2022-12-13 23:26:57: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-13 23:26:57: Exiting...
Zigbee2MQTT:error 2022-12-13 23:26:57: Error: Failure send setConfigurationValue:{"type":"Buffer","data":[3,0,1,83,0,18,48,117]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:516:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by AliakseiT** [comment]
The problem is observed with both Stable and Edge add-ons.

**Comment by vitaly-i** [comment]
Hello!
I have the same problem.
The port specified is correct /dev/ttyACM0

![2022-12-22_14-32-40](https://user-images.githubusercontent.com/13113165/209064691-21c2f27e-8530-4402-818c-4d7425049797.png)
![2022-12-22_14-37-37](https://user-images.githubusercontent.com/13113165/209064756-ae2c1ba5-57b4-41d8-ab25-cbd81678a289.png)
![2022-12-22_14-38-09](https://user-images.githubusercontent.com/13113165/209064815-1478a635-1f0e-4827-b3ef-cd0b5ce1f167.png)
