### ISSUE TITLE
Namron Panelheater Model 5401395: Power consumption reporting in kWh not working

### ISSUE THREAD

**Issue by Gjaevert** [Koenkk/zigbee2mqtt#15548]
### What happened?

The panel heater is not reporting consistent incremental consumption numbers in kWh. The heater is currently reporting intermittent values both significantly lower and higher than the expected "slow rising" curve. 
The power numbers in Watts are reported correctly, in direct correlation to when the oven is setting heating to on / off.

### What did you expect to happen?

I would expect the oven to report a steady rise in power consumption, measured in kWh, then the oven is in use.

### How to reproduce it (minimal and precise)

Have the oven turn on for a period and watch the kWh reported usage send certain values totally off the normal curve.

See the bottom graph and reported values in the attached screenshot from Homeasisstant.

![Screenshot 2022-12-14 at 12 01 33](https://user-images.githubusercontent.com/1225015/207592003-92d601a2-dc8b-4c6c-b1e7-c9a93717dbb2.png)

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20211217

### Adapter

Electrolama zig-a-zig-ah

**Comment by owangen** [comment]
You want the sum of power usage instead of current power usage? If so take a look at https://www.home-assistant.io/docs/energy/individual-devices/#devices-with-power-w-sensors.

**Comment by Gjaevert** [comment]
I have set up a Riemann helper, so have solved this locally actually :)
But I think its valuable to mention that the built in kWh sensor is not working as it should, as you see in the image it intermittently reports values way above/below the expected curve.
