### ISSUE TITLE
Legrand 741807 ( 067776 on Z2M) reports 'CLOSED' when opened and vice versa

### ISSUE THREAD

**Issue by SirJohnDoe** [Koenkk/zigbee2mqtt#15545]
### What happened?

I'm not sure exactly what changed, but ever since [this ](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.3)update the shade cover reports the wrong state. Regardless of the 'Invert_cover' setting, the switch reports 'CLOSE' as state when it's up (opened). Personally I think the naming is quite confusing, as you could describe it as open/close for either position: up (open) and down (closed) would make more sense to me. In any case, in HA it shows as closed (pic from [this](https://www.home-assistant.io/integrations/cover/) page):

![cover_classes_icons](https://user-images.githubusercontent.com/11654657/206904672-0375090c-7f65-4d70-a79a-128ebbbb8304.png)

Inverting (=true) works, as the buttons will show in HA as open, but the toggle service in HA won't work due to the state still being 'CLOSE' and the history in HA will also show closed. I would say that the state should match the position as described at the 'invert_cover' toggle, this is currently not the case. Invert = false shows position as 0, state is CLOSE (is in fact open). Invert = true shows position is 100, state is CLOSE (is in fact open). The wiring of the switch is correct, as the physical buttons work as expected.

The firmware/builddate of the Legrand is 001a/20200605. The switch is a [Legrand 741807](https://www.elektrobode.nl/products/legrand-valena-next-with-netatmo-valena-next-wn-geconnecteerde-rolluikschakelaar-wit-741807) that shows up as Legrand 067776.

_Originally posted by @SirJohnDoe in https://github.com/Koenkk/zigbee2mqtt/issues/15101#issuecomment-1345554942_
      

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20211217

### Adapter

Sonoff ZigBee 3.0 Dongle Plus

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/15101
