### ISSUE TITLE
 LLKZMK11LM power supply unknown ?

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#15546]
### What happened?

device  LLKZMK11LM show power supply unknown. System dont know if this is batterry powered or some  else?

![Adnotacja 2022-12-14 111820](https://user-images.githubusercontent.com/91805313/207568997-11c2d541-4f69-4d53-a6c6-74900e364739.jpg)

### What did you expect to happen?

this device should be power supply AC online

### How to reproduce it (minimal and precise)

link device and see this bug

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
