### ISSUE TITLE
[New device support]: ALCHEMY_VIII - AL8RGB13W-AP

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#15560]
### Link

https://www.amazon.com.au/Downlight-Automation-Compatible-SmartThings-Lightify/dp/B07KWXFDQC

### Database entry

IEEE: 0x00124b001a53b1db Nwk: 0xBAA6 Device Type: Router LQI: Unknown RSSI: Unknown Last Seen: 2022-01-07T08:41:17 Power Source: Powered

### Comments

New device

### Supported color modes

Colour Temp, RGBWW

**Comment by cloudbr34k84** [comment]
This would be great to get this device supported  as we already support another one from the same manufacturer?

**Comment by cloudbr34k84** [comment]
@Koenkk hey any chance of getting this device supported??

**Comment by Koenkk** [comment]
Can you provide the database.db entry of this device and the color temp range? https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device

**Comment by cloudbr34k84** [comment]
@Koenkk sorry still new to this, but where do i find the database.db for this device?? is that a HA database or Z2m?
when i try and get the colour range i get this error
Publish 'set' 'read' to '0x00124b001a53b1db' failed: 'Error: Read 0x00124b001a53b1db/11 lightingColorCtrl(["colorTempPhysicalMin","colorTempPhysicalMax"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

![image](https://user-images.githubusercontent.com/58960644/211115804-85214a08-deee-46e0-a34a-13337ac87c21.png)

**Comment by cloudbr34k84** [comment]
@Koenkk ok i think i know what you mean and i cant find the devices in the database even after restarting.
![image](https://user-images.githubusercontent.com/58960644/211118309-423847cc-2cb4-4f21-bd6e-1f33ed94a8a6.png)

**Comment by Koenkk** [comment]
Can you click on the device and provide a screenshot of the about page?

**Comment by cloudbr34k84** [comment]
@Koenkk here you go
![Screenshot_20230108-204235.png](https://user-images.githubusercontent.com/58960644/211191747-68e32df3-e0a9-4937-a48f-0ca5904db76a.png)

**Comment by Koenkk** [comment]
Thanks, added!


Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by cloudbr34k84** [comment]
@Koenkk Legend! appreciate it
