### ISSUE TITLE
DLKZMK11LM device power source unknown

### ISSUE THREAD

**Issue by Quitsoon** [Koenkk/zigbee2mqtt#15568]
### What happened?

Hi ! This device is powered from main, but report an unknown power source

![DLKZMK11LM](https://user-images.githubusercontent.com/72099942/207926367-697d894b-73bb-4b6f-9fc2-150f02bc3535.jpg)

### What did you expect to happen?

It should report being powered by mains.

### How to reproduce it (minimal and precise)

Add the device.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20221102

### Adapter

  Zigbee 3.0 USB Dongle plus P (CC2652P)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Quitsoon** [comment]
Thank you very much !
