### ISSUE TITLE
[Feature request]: NAMRON -> 4512735

### ISSUE THREAD

**Issue by roysve** [Koenkk/zigbee2mqtt#15572]
### Is your feature request related to a problem? Please describe

I hope you can add this to core. 
https://www.elektroimportoren.no/namron-zigbee-skjoeteledning-4-veis-2-usb/4512735/Product.html (Norwegian page)

Message:
This text comes for 1 to 5 on endpoint and onOff 1 or 0. Endpoint 5 is the USB outlet.
Debug 2022-12-14 21:02:34Received Zigbee message from '0x94deb8fffe73e4c9', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID null

This text comes for OTA
Debug 2022-12-14 22:04:30Received Zigbee message from '0x94deb8fffe73e4c9', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":7,"imageType":112,"manufacturerCode":4644}' from endpoint 1 with groupID null

There is a Button on top of this extension cord that act as an group button when it's pushed it will turn off all 5 outlets.

![Screenshot 2022-12-15 202219](https://user-images.githubusercontent.com/120679440/207948705-385be1dd-b222-4235-a8fc-28eaa48d5346.png)

### Describe the solution you'd like

This is my config file for herdsman converters:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const definition = [{
    zigbeeModel: ['4512735'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '4512735', // Vendor model number, look on the device for a model number
    vendor: 'NAMRON AS', // Vendor of the device (only used for documentation and startup logging)
    description: 'Multiprise with 4 AC outlets and 2 USB super charging ports (16A)', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.on_off], // We will add this later
    toZigbee: [tz.on_off], // Should be empty, unless device can be controlled (e.g. lights, switches).
    extend: extend.switch(),
    exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3'), e.switch().withEndpoint('l4'), e.switch().withEndpoint('l5')], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
    endpoint: (device) => {return {'l1': 1, 'l2': 2, 'l3': 3, 'l4': 4, 'l5': 5};},
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        try {
            for (const ID of [1, 2, 3, 4,5]) {
                const endpoint = device.getEndpoint(ID);
                await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            }
        }
        catch (e) {
            // Fails for some: https://github.com//issues/4872
        }
        device.powerSource = 'Mains (single phase)';
        device.save();
    },
}
]

module.exports = definition;

### Describe alternatives you've considered

.

### Additional context

.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
