### ISSUE TITLE
Bosch Smart Thermostat 2 parring problem

### ISSUE THREAD

**Issue by norbertbxl** [Koenkk/zigbee2mqtt#15595]
### What happened?

Hello
Can someone help me pair this thermostat with z2m,
I think I'm setting the pairing mode wrong, but I can't find any information on how to do it anywhere,
thank you

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

0x26720700

### Adapter

conbee2

**Comment by danieledwardgeorgehitchcock** [comment]
You may need to use an install code to pair a bosch device

**Comment by danieledwardgeorgehitchcock** [comment]
There may be a label with a QR code on your device - the install code should be printed on that. Use it with [this MQTT topic](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-install-code-add)

**Comment by norbertbxl** [comment]
> There may be a label with a QR code on your device - the install code should be printed on that. Use it with [this MQTT topic](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-install-code-add)

A
![IMG_1801](https://user-images.githubusercontent.com/57253004/208178934-0e8d99a2-acbf-4c5d-8939-12f8a6c2e331.jpeg)

**Comment by norbertbxl** [comment]
I found this information , my conbee coordinator could be the problem?


https://github.com/Koenkk/zigbee2mqtt/pull/13780

**Comment by itkama** [comment]
Correct, it currently does not work with a Conbee.
