### ISSUE TITLE
[New device support]: Aqara S3 Smart thermostat

### ISSUE THREAD

**Issue by masafra86** [Koenkk/zigbee2mqtt#15600]
### Link

https://www.aqara.com/Smart-Thermostat-S3_overview

### Database entry

{"id":23,"type":"EndDevice","ieeeAddr":"0x54ef44100057c835","nwkAddr":28185,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.airrtc.agl001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,64704,10,513],"outClusterList":[3,64704,513],"clusters":{"genBasic":{"attributes":{"appVersion":25,"modelId":"lumi.airrtc.agl001"}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[3,40,21,5,33,1,0,10,33,0,74,13,35,25,8,0,0,17,35,1,0,0,0,101,32,0,102,41,194,6,103,41,214,6,104,35,1,0,0,0,105,32,100,106,32,0]},"252":0,"625":1,"626":0,"627":1,"628":1,"629":1,"630":{"type":"Buffer","data":[4,62,1,224,0,0,9,96,4,56,0,0,6,164,5,100,0,0,8,152,129,224,0,0,8,152]},"631":1,"633":500,"634":0,"635":1,"636":0,"637":0,"638":0,"640":0,"1034":100}},"hvacThermostat":{"attributes":{"localTemp":1750,"occupiedHeatingSetpoint":1750}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":25,"hwVersion":1,"dateCode":"Jun  7 2022","swBuildId":"0.0.0_0025","zclVersion":3,"interviewCompleted":true,"meta":{"configured":744871269},"lastSeen":1671264476118,"defaultSendRequestWhen":"immediate"}

### Comments

I'm following all the steps to add this thermostat, but I'm not able to get past the pairing step, after pairing it, creating the .js file and adding it to the external converters entry in the configuration, I still get the same error.
I'm trying to modify another file about a similar device i found, that is this one:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const manufacturerOptions = {
    xiaomi: {manufacturerCode: 0x115f, disableDefaultResponse: true},
};

const tzLocal = {
    ZNCJMB14LM: {
        key: ['theme'
        ],
        convertSet: async (entity, key, value, meta) => {
            if (key === 'theme') {
                const lookup = {'classic': 0, 'concise': 1};
                await entity.write('aqaraOpple', {0x0215: {value: lookup[value], type: 0x20}}, manufacturerOptions.xiaomi);
                return {state: {theme: value}};
            } else {
                throw new Error(`Not supported: '${key}'`);
            }
        },
    },
};

const fzLocal = {
    ZNCJMB14LM: {
        cluster: 'aqaraOpple',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            const result = {};
            if (msg.data.hasOwnProperty(0x0215)) {
                const lookup = {0: 'classic', 1: 'concise'};
                result.theme = lookup[msg.data[0x0215]];
            }
            return result;
        },
    },
};

const definition = {
        zigbeeModel: ['lumi.switch.n4acn4'],
        model: 'ZNCJMB14LM',
        vendor: 'Xiaomi',
        description: 'Aqara S1 Smart Touch Panel',
        fromZigbee: [fz.on_off, fzLocal.ZNCJMB14LM],
        toZigbee: [tz.on_off, tzLocal.ZNCJMB14LM],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3};
        },
        exposes: [
            e.switch()
                .withEndpoint('l1')
                .setAccess('state', ea.STATE_SET),
            e.switch()
                .withEndpoint('l2')
                .setAccess('state', ea.STATE_SET),
            e.switch()
                .withEndpoint('l3')
                .setAccess('state', ea.STATE_SET),
            exposes.enum('theme', ea.SET, ['classic', 'concise'])
                .withDescription('Display theme'),
        ],
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(device.getEndpoint(1));
        },
        ota: ota.zigbeeOTA,
    };

module.exports = definition;

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['lumi.airrtc.pcacn2'],
    model: 'SLR1',
    vendor: 'Aqara',
    description: 'Heating thermostat',
    fromZigbee: [fz.thermostat_att_report, fz.thermostat_weekly_schedule_rsp],
    toZigbee: [tz.thermostat_local_temperature, tz.thermostat_system_mode, tz.thermostat_running_state,
        tz.thermostat_occupied_heating_setpoint, tz.thermostat_control_sequence_of_operation, tz.thermostat_weekly_schedule,
        tz.thermostat_clear_weekly_schedule, tz.thermostat_temperature_setpoint_hold, tz.thermostat_temperature_setpoint_hold_duration],
    exposes: [exposes.climate().withSetpoint('occupied_heating_setpoint', 7, 30, 1).withLocalTemperature()
        .withSystemMode(['off', 'auto', 'heat']).withRunningState(['idle', 'heat']).withPiHeatingDemand()],
    meta: {disableDefaultResponse: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(5);
        const binds = ['genBasic', 'genIdentify', 'genAlarms', 'genTime', 'hvacThermostat'];
        await reporting.bind(endpoint, coordinatorEndpoint, binds);
        await reporting.thermostatTemperature(endpoint, {min: 0, max: constants.repInterval.HOUR, change: 1});
        await reporting.thermostatRunningState(endpoint);
        await reporting.thermostatOccupiedHeatingSetpoint(endpoint);
        await reporting.thermostatTemperatureSetpointHold(endpoint);
        await reporting.thermostatTemperatureSetpointHoldDuration(endpoint);
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`lumi.airrtc.agl001` is supported in the latest dev (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
