### ISSUE TITLE
Sonoff ZBDongle-E doesn't work with Aqara PIR and IKEA dimmer

### ISSUE THREAD

**Issue by boschr** [Koenkk/zigbee2mqtt#15625]
### What happened?

Last week I started using the Zigbee2MQTT project with the Sonoff ZBDongle-E stick. Everything went well, so I connected my first sensor: Aqara PIR (RTCGQ11LM). Pairing the sensor is not a problem, but after pairing I do not receive any update via MQTT.

After that i tried two more sensors: Aqara temp/humidity sensor (WSDCGQ11LM) and a IKEA dimmer button (E1743). The temp sensor works well, but from the IKEA dimmer I also do not get any updates via MQTT.

Besides that i don't see any errors in de output logs from the docker container.

### What did you expect to happen?

MQTT messages from state update from the device.

### Zigbee2MQTT version

1.28.4 commit: 52e545f

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus ZBDongle-E

**Comment by MattWestb** [comment]
IKEA controllers can needing being reconfigured after paring for getting the reporting working OK.
