### ISSUE TITLE
[New device support]: TS0202 - _TZ3000_6ygjfyll - Human Motion Sensor

### ISSUE THREAD

**Issue by nikitah4x** [Koenkk/zigbee2mqtt#15626]
### Link

https://www.aliexpress.com/item/1005003187399208.html?spm=a2g0o.order_list.order_list_main.23.2350586as8BW9c&gatewayAdapt=glo2isr

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c13802c1184273","nwkAddr":32786,"manufId":4417,"manufName":"_TZ3000_6ygjfyll","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0202","manufacturerName":"_TZ3000_6ygjfyll","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x00124b0026b73f72","zoneState":1,"currentZoneSensitivityLevel":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1671378157472,"defaultSendRequestWhen":"immediate"}

### Comments

Hey,
I tried to add it by myself, but it didn't work, and I spend a lot of time trying to do it.
Please help me with it.
I edited the external converter and added the fingerprint for this device but still it doesn't work.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: tuya.fingerprint('TS0202', ['_TZ3000_6ygjfyll', '_TZ3040_6ygjfyll']),
    model: 'IH012-RT01',
    vendor: 'TuYa',
    description: 'Motion sensor',
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.ignore_basic_report, fz.ZM35HQ_attr, fz.battery],
    toZigbee: [tz.ZM35HQ_attr],
    exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.battery(), e.battery_voltage(),
        exposes.enum('sensitivity', ea.ALL, ['low', 'medium', 'high']).withDescription('PIR sensor sensitivity'),
        exposes.enum('keep_time', ea.ALL, [30, 60, 120]).withDescription('PIR keep time in seconds'),
        ],
};

module.exports = definition;
```

**Comment by rapejim** [comment]
@nikitah4x this master commit have your device:
https://github.com/Koenkk/zigbee-herdsman-converters/commit/ae34a0fc0d50289582c126a4991bb6aadb44b7ee

**Comment by nikitah4x** [comment]
Hey,
@rapejim I fixed it by moving to the Zigbee2MQTT Edge addon instead of the regular one.

**Comment by rapejim** [comment]
> Hey, @rapejim I fixed it by moving to the Zigbee2MQTT Edge addon instead of the regular one.

Then, @nikitah4x, the issue can be closed, right?

**Comment by nikitah4x** [comment]
@rapejim Yes.
