### ISSUE TITLE
Incorrectly recognized tuya switch module model

### ISSUE THREAD

**Issue by chryss44** [Koenkk/zigbee2mqtt#15623]
### What happened?

Incorrectly recognized tuya switch module model, i bought this module https://www.aliexpress.com/item/1005004371232755.html?spm=a2g0o.order_list.order_list_main.11.4e661802S6JndI
Supposed to have switch (state), power_on_behavior, switch_type, linkquality.
It should be recognized as TS0002_switch_module but it is recognized as TuYa TS0002
<img width="886" alt="Capture d’écran 2022-12-18 à 13 00 14" src="https://user-images.githubusercontent.com/32177747/208297218-399160fb-3391-4872-8c8e-dbcd126fb2d9.png">

<img width="424" alt="Capture d’écran 2022-12-18 à 13 01 33" src="https://user-images.githubusercontent.com/32177747/208297239-103e4a87-db98-4d2b-95ae-04c7b4ddf895.png">

### What did you expect to happen?

be recognized as TS0002_switch_module fully featured

### Zigbee2MQTT version

 1.28.2 commit: e66fe853

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

Info 2022-12-18 13:07:54Accepting joining not in blocklist device '0xa4c1380b303112dc'
Info 2022-12-18 13:07:54Device '0xa4c1380b303112dc' joined
Info 2022-12-18 13:07:55MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c1380b303112dc","ieee_address":"0xa4c1380b303112dc"},"type":"device_joined"}'
Info 2022-12-18 13:07:55MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xa4c1380b303112dc"},"type":"device_connected"}'
Info 2022-12-18 13:07:55Starting interview of '0xa4c1380b303112dc'
Info 2022-12-18 13:07:55MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c1380b303112dc","ieee_address":"0xa4c1380b303112dc","status":"started"},"type":"device_interview"}'
Info 2022-12-18 13:07:55MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0xa4c1380b303112dc"},"type":"pairing"}'
Info 2022-12-18 13:07:56Successfully interviewed '0xa4c1380b303112dc', device has successfully been paired
Info 2022-12-18 13:07:56Device '0xa4c1380b303112dc' is supported, identified as: TuYa 2 gang switch (TS0002)
Info 2022-12-18 13:07:56MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"2 gang switch","exposes":[{"endpoint":"l1","features":[{"access":7,"description":"On/off state of the switch","endpoint":"l1","name":"state","property":"state_l1","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"endpoint":"l2","features":[{"access":7,"description":"On/off state of the switch","endpoint":"l2","name":"state","property":"state_l2","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0002","options":[],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0xa4c1380b303112dc","ieee_address":"0xa4c1380b303112dc","status":"successful","supported":true},"type":"device_interview"}'
Info 2022-12-18 13:07:56Configuring '0xa4c1380b303112dc'
Info 2022-12-18 13:07:56MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"2 gang switch","friendly_name":"0xa4c1380b303112dc","model":"TS0002","supported":true,"vendor":"TuYa"},"type":"pairing"}'
Info 2022-12-18 13:07:56Successfully configured '0xa4c1380b303112dc'
Info 2022-12-18 13:08:00MQTT publish: topic 'zigbee2mqtt/0xa4c1380b303112dc', payload '{"linkquality":255,"state_l1":"ON"}'
Info 2022-12-18 13:08:00MQTT publish: topic 'zigbee2mqtt/0xa4c1380b303112dc', payload '{"linkquality":255,"state_l1":"ON","state_l2":"ON"}'

**Comment by Koenkk** [comment]
Already fixed in z2m 1.28.4.
