### ISSUE TITLE
fly end devices between coordinators

### ISSUE THREAD

**Issue by CodingLLC** [Koenkk/zigbee2mqtt#15644]
### What happened?

There are 3 Lan coordinators in the network. Each has its own routers and end devices. Due to power outages, some end devices start to be transferred to another coordinator (both coordinators in the coverage area).
At the same time, pairing of new devices is not allowed on the coordinator.
As a result, here are such mismatches (the same sensor on both coordinators). Pan_ID on coordinators is different.
http://joxi.ru/E2pPqgkTjxvzQ2

### Zigbee2MQTT version

 1.28.4-1

### Adapter firmware version

20220219

### Adapter

zStack3x0

**Comment by MattWestb** [comment]
Do you 3 network have unique `Network key`, `PAN-ID`, `Extended PAN-ID` **and** the the coordinator `IEEE` ?
If no on one of the questions you is getting problem sooner or later.

**Comment by CodingLLC** [comment]
> 

thanks
