### ISSUE TITLE
Sinopé RM3250ZB appears as "Unsupported"

### ISSUE THREAD

**Issue by ck-01** [Koenkk/zigbee2mqtt#15648]
### What happened?

I tried to configure the [Sinopé RM3250ZB ](https://www.zigbee2mqtt.io/devices/RM3250ZB.html )in Zigbee2Mqtt. The devices is quickly paired and appears in the device list but it appears as "unsupported". The model "RM3250ZB" is detected though.

- I tried deleting and re-pairing the device
- I tried creating an external converter for the device

Logs:
`2022-12-19 09:28:20 Received message from unsupported device with Zigbee model 'RM3250ZB
2022-12-19 09:28:20 Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html`

### What did you expect to happen?

I was expecting the device to be recognized "out of the box" as it is in the supported device list

### How to reproduce it (minimal and precise)

Unsure. I get the issue as soon as I pair the device. 

### Zigbee2MQTT version

1.28.4 

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle-P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10260329/log.txt)

**Comment by Koenkk** [comment]
Already supported in the dev branch  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) and in the next release on 1 January.
