### ISSUE TITLE
[Question] Zigbee2Mqtt compatible UK wall socket

### ISSUE THREAD

**Issue by Woodpeckercz** [Koenkk/zigbee2mqtt#1564]
Hi guys,
Not sure where to post a question like this.
Does anyone know if there is a wall socket/outlet or preferably double outlet that works with zigbee2mqtt?

Thanks

**Comment by james-fry** [comment]
You can see here:
https://www.zigbee2mqtt.io/information/supported_devices.html

Hive
Salus
Ikea tradfri might also work, but its not verified.

**Comment by Woodpeckercz** [comment]
The thing is I want a built in socket not a smart plug, having a hard time finding one. The like lightwave but zigbee controlled not 433mhz.

**Comment by james-fry** [comment]
Ah right. got you.
An alternative is a wifi socket that can be flashed with tasmota.
AFAIK there is only one: https://blakadder.github.io/templates/vigica_VGSPK00815.html
You can get them on amazon uk and they have mixed reviews.

**Comment by timstanley1985** [comment]
I use sonoffs flashed with tasmota

**Comment by Woodpeckercz** [comment]
Sonoff wall socket? Never saw one.
I'm after double in-wall sockets, not wall plugs.

**Comment by james-fry** [comment]
> The thing is I want a built in socket not a smart plug

@Woodpeckercz - just found these:

https://aone.auroralighting.com/ProductDetails/AU-A1ZBDSS

not supported by Z2M... yet. But they are zigbee.
