### ISSUE TITLE
Moes BHT series Thermostat (BHT-002-GCLZB) wrong sensors

### ISSUE THREAD

**Issue by zeminator** [Koenkk/zigbee2mqtt#15654]
### What happened?

I have few new BHT-002-GCLZB devices, and I was doing test and configurations I noticed that Z2M has wrong AL and OU sensor (mixed between each and other). Meaning that OU (in Z2M) is actually AL (in device), and AL (in Z2M) is actual OU (in device).

ps. Also current_heating_setpoint can only set 10-35c (not from 5c to 35c)
### What did you expect to happen?

when setting sensor it would be correct sensor. :)

### How to reproduce it (minimal and precise)

change sensor from device and check how Z2M sees it.

### Zigbee2MQTT version

1.28.4 commit: unknown

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus, TI CC2652P + CP2102(N) Zigbee USB Stick

**Comment by zeminator** [comment]
also temperature calibration is is allowed set only by integers (without decimals, -9 to 9). And device have 0.5c accurate for current temperature (at least screen is showing 0.5 accurate values), so it would be nice to see same values from Z2M.

**Comment by alienatedsec** [comment]
Are you holding two buttons on the left to get into system settings? For some reason, I cannot access the system settings menu to change sensors.

**Comment by zeminator** [comment]
> Are you holding two buttons on the left to get into system settings? For some reason, I cannot access the system settings menu to change sensors.

Yes, but you need to put thermostat first off. You can't configure it when it is on.

Ps. Sadly also noticed just yesterday that if thermostat is off it will not update temperature reading. So sad...

**Comment by alienatedsec** [comment]
> You need to put thermostat first off, then far left and far right buttons. You can't configure it when it is on.

@zeminator thanks
Sure thing - its not working - have a look at this thread https://github.com/Koenkk/zigbee2mqtt/issues/4185#issuecomment-1401897521

**Comment by alienatedsec** [comment]
> Ps. Sadly also noticed just yesterday that if thermostat is off it will not update temperature reading. So sad...

Mine is turned off and is updating the temperature regularly

```
{"child_lock":"LOCK","current_heating_setpoint":20,"deadzone_temperature":0,"heat":"OFF","linkquality":127,"local_temperature":19.5,"local_temperature_calibration":0,"max_temperature":35,"max_temperature_limit":0,"min_temperature_limit":5,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":6,"saturday_p1_minute":0,"saturday_p1_temperature":20,"saturday_p2_hour":12,"saturday_p2_minute":0,"saturday_p2_temperature":20,"saturday_p3_hour":14,"saturday_p3_minute":30,"saturday_p3_temperature":20,"saturday_p4_hour":17,"saturday_p4_minute":30,"saturday_p4_temperature":20,"sunday_p1_hour":6,"sunday_p1_minute":0,"sunday_p1_temperature":20,"sunday_p2_hour":12,"sunday_p2_minute":30,"sunday_p2_temperature":20,"sunday_p3_hour":14,"sunday_p3_minute":30,"sunday_p3_temperature":20,"sunday_p4_hour":18,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":20,"weekdays_p2_hour":11,"weekdays_p2_minute":30,"weekdays_p2_temperature":20,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":20,"weekdays_p4_hour":17,"weekdays_p4_minute":30,"weekdays_p4_temperature":20},"running_state":"idle","sensor":"IN","system_mode":"off"}
```

You can see the graph when I turned the PC back on and it started listening - the spike is when I tested the sensor and its reporting

![image](https://user-images.githubusercontent.com/73167064/214542666-97bd4ec5-5e51-4ab8-911b-3cbf2ec1164d.png)
