### ISSUE TITLE
[New device support]: Philips Hue Go 7602031K6

### ISSUE THREAD

**Issue by Seoulcialite** [Koenkk/zigbee2mqtt#15667]
### Link

https://www.philips-hue.com/ko-kr/p/hue-white-and-color-ambiance-go-portable-light--latest-model-/7602031K6

### Database entry

{}

### Comments

I believe 7602031K6 is the Korean version of 7602031N6. I would attempt to try to add this device myself but already at my limit of technical know-how.

### External converter

```shell
# I tried adding the following to philips.js right under the entry 7602031N6 for but I wasn't able to get Zigbee2MQTT addon to start
    {
        zigbeeModel: ['7602031K6'],
        model: '7602031K6',
        vendor: 'Philips',
        description: 'Hue Go portable light',
        extend: hueExtend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
    },
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
