### ISSUE TITLE
[New device support]: Schneider Wiser Smoke Alarm CCT599001

### ISSUE THREAD

**Issue by mandrean** [Koenkk/zigbee2mqtt#15660]
### Link

https://www.se.com/ww/en/product/CCT599001/smoke-alarm-wiser-battery-10-years-lifetime-white-ip20/

### Database entry

{}

### Comments

Seems like a solid zigbee smoke alarm!

Would add support for it myself if I had a Schneider gateway to sniff, but I don't.

![image](https://user-images.githubusercontent.com/4631744/208678173-dc50cf36-fb31-4ef2-9a51-da111d32197a.png)

**Comment by mandrean** [comment]
After some Googling I found this GH issue with some additional info:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6617

**Comment by dennisgranasen** [comment]
No need to sniff any gateway for the basic functionality anyway. I made a PR for this just by implementing standard fZ clusters. It seems to work just fine, but more testing is of course welcome. https://github.com/Koenkk/zigbee-herdsman-converters/pull/5292

**Comment by t112013** [comment]
Hello. is there any works on getting the function for triggering the alarm working ? 
That is very crutial to me if i would decide to buy these units

**Comment by t112013** [comment]
Could this please be open and see if any nice sould out there can work on triggering the alarm ?
