### ISSUE TITLE
Dimmer Nue / 3A HGZB-02A - power on behavior issue

### ISSUE THREAD

**Issue by SAOPP** [Koenkk/zigbee2mqtt#15670]
### What happened?

In the current December release, this device has a power-on behavior setting, you can read and set the state, but in fact this setting does not work. Was wondering if it could be implemented? Because the dimmer is always on when power is applied.

![image](https://user-images.githubusercontent.com/5647009/208753859-e8093a5a-52bd-40a0-8c7e-2eef001b4b21.png)

### What did you expect to happen?

The ability to control the initial state of the device.

### Zigbee2MQTT version

1.28.4-dev commit: 0e4ea6a

### Adapter firmware version

20220219

### Adapter

ZigStar Lan POE

**Comment by Koenkk** [comment]
Seems the device does not support it, disabled it.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
