### ISSUE TITLE
Cannot add external convertor - the text box disappears

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#15676]
### What happened?

When I try to add an external convertor, the text entry box disappears very shortly after I press the Plus sign. Happens in Edge on Mac as well as the HA app on iPhone.

### What did you expect to happen?

Being able to enter text

### How to reproduce it (minimal and precise)

Go to Settings, External convertor, add

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

20220219

### Adapter

Slaeh.sh CC2652RB

**Comment by zegl** [comment]
@Stooovie This sounds like it's an issue with the frontend, please open an issue in the frontend project instead: https://github.com/nurikk/zigbee2mqtt-frontend

For now, you can configure an external converted by editing the configuration yaml file manually.
