### ISSUE TITLE
Current_heating_setpoint gone. Solved on HA community board

### ISSUE THREAD

**Issue by moskovskiy82** [Koenkk/zigbee2mqtt#15690]
### What happened?

Take a look at this post by petro from HA

https://community.home-assistant.io/t/attribute-current-heating-setpoint-is-gone/486246/10

### Zigbee2MQTT version

1.22

### Adapter firmware version

Doesn't matter

### Adapter

Doesn't matter

**Comment by Koenkk** [comment]
With what device is this? (Please provide the exact model number)
