### ISSUE TITLE
Lidl HG08164 none action 

### ISSUE THREAD

**Issue by lzahradil** [Koenkk/zigbee2mqtt#15691]
### What happened?

the button does not send the correct action when pressed. Action is null

{
"action": null,
"battery": 58,
"last_seen": "2022-12-19T22:19:44+01:00",
"linkquality": 52
}

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

6.5.0.0 build 188

### Adapter

EZSP v7 Lidl gateway

### Debug log

Info 2022-12-21 22:28:45MQTT publish: topic 'zigbee2mqtt/bouda-vypinac1', payload '{"action":null,"battery":58,"last_seen":"2022-12-21T22:28:44+01:00","linkquality":48}'
Info 2022-12-21 22:28:46MQTT publish: topic 'zigbee2mqtt/bouda-vypinac1', payload '{"action":null,"battery":58,"last_seen":"2022-12-21T22:28:45+01:00","linkquality":48}'
Info 2022-12-21 22:28:46MQTT publish: topic 'zigbee2mqtt/bouda-vypinac1', payload '{"action":null,"battery":58,"last_seen":"2022-12-21T22:28:46+01:00","linkquality":48}'

**Comment by ErikT80** [comment]
I have the same issue with a CC2531 coordinator. Tried pairing it in both 'modes' (3 times quick press on the button). And also switched modes after pairing. In one mode I do not get any updates, in the other the action stays 'null'. Hopefully there is someone with a solution
