### ISSUE TITLE
[New device support]: Hue white ambiance Still

### ISSUE THREAD

**Issue by rikmueller** [Koenkk/zigbee2mqtt#15701]
### Link

https://www.philips-hue.com/de-de/p/hue-white-ambiance-still-deckenleuchte/8719514341333

### Database entry

{"id":23,"type":"Router","ieeeAddr":"0x0017880109c03520","nwkAddr":28032,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003055401","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"zclVersion":8}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"colorTemperature":280,"startUpColorTemperature":260}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false,"scenes":{"0_7":{"name":"Standard","state":{"color_mode":"color_temp","brightness":254,"state":"ON","color_temp":260}}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20211210","swBuildId":"1.93.7","zclVersion":8,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1671718197660,"defaultSendRequestWhen":"immediate"}

### Comments

Hue White Ambiance Still light is available in three color variants. 
The black model (929003055501) is already supported in Z2M out of the box.
The aluminium model (929003055401) and the white model (929003055301) aren´t supported yet.

Searching the forums I managed to create a working converter (see below).

### External converter

```shell
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extendDontUse = require('zigbee-herdsman-converters/lib/extend');

const hueExtend = {
    light_onoff_brightness_colortemp: (options={}) => ({
        ...extendDontUse.light_onoff_brightness_colortemp(options),
        ota: ota.zigbeeOTA,
        meta: {turnsOffAtBrightness1: true},
        toZigbee: extendDontUse.light_onoff_brightness_colortemp(options).toZigbee
            .concat([tz.hue_power_on_behavior, tz.hue_power_on_error]),
    }),
};

const definition = {
    zigbeeModel: ['929003055401'],
    model: '929003055401',
    vendor: 'Philips',
    description: 'Hue white ambiance Still',
    extend: hueExtend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

### Color temperature range

"colorTempPhysicalMin":153,"colorTempPhysicalMax":454

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
