### ISSUE TITLE
Some IRIS sensors do not have a tamper reset, recommend not exposing on those.

### ISSUE THREAD

**Issue by tsspmq** [Koenkk/zigbee2mqtt#15709]
### What happened?

First time reporting with this, and just now starting to tinker with drivers.   

Some Iris sensors are reporting tampered incorrectly and after digging around I can see where its being exposed in the iris driver.

### What did you expect to happen?

Iris sensors 3320-L and 3326-L do not have an ability to clear the tamper alarm even though they report it (always).    Would like to have e.tamper removed from the exposes on those two models.  

### Zigbee2MQTT version

1.28.4-dev commit: 566fc62

### Adapter firmware version

6.7.8.0 build 373

### Adapter

EZSP_v8

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
