### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by fulup-bzh** [Koenkk/zigbee2mqtt#15702]
### Link

https://moeshouse.com/collections/smart-pir-sensor/products/smart-zigbee-pir-motion-sensor-human-sensor-detector

### Database entry

{"id":6,"type":"EndDevice","ieeeAddr":"0x5c0272fffec355d1","nwkAddr":35015,"manufId":4098,"manufName":"_TYZB01_vwqnz1sn","powerSource":"Battery","modelId":"TS0202","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,1280],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\f\u0000\u0000\u0000\u0000\u0012+)7+\u0012","65506":31,"65534":0,"modelId":"TS0202","manufacturerName":"_TYZB01_vwqnz1sn","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x50325ffffe0074af","zoneState":1,"currentZoneSensitivityLevel":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x50325ffffe0074af","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":262,"inClusterList":[1024],"outClusterList":[],"clusters":{"msIlluminanceMeasurement":{"attributes":{"measuredValue":8452}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1671723326148,"defaultSendRequestWhen":"immediate"}

### Comments

Motion Sensor TS0202/_TYZB01_vwqnz1sn is defined within tuya.js as an alias of TYZB01_dr6sduka  when it is not.
 ```
fingerprint: [{modelID: 'TS0202', manufacturerName: '_TYZB01_dr6sduka'}
            {modelID: 'TS0202', manufacturerName: '_TYZB01_ef5xlc9q'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_vwqnz1sn'},
```
Here after an external converter that work for this device and report correctly
- motion detection
- battery level
- luminescence
- tampering

As I'm not an zigbee2mqtt expert some data from the fromZigbee might be removed.

### External converter

```shell
# external converter for MOES Smart PIR Motion Sensor
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: tuya.fingerprint('TS0202', ['_TYZB01_vwqnz1sn']),
    model: 'TS0202',
    vendor: 'TuYa',
    description: 'Motion Detector',
    fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery, fz.ignore_basic_report, fz.ias_occupancy_alarm_1_report, fz.illuminance],
    toZigbee: [],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: tuya.configureMagicPacket,
    exposes: [
        e.occupancy(),e.battery_low(), e.battery(),e.tamper(),e.illuminance_lux(),
    ],
};
module.exports = definition;
```
```


### Supported color modes

_No response_

### Color temperature range

_No response_

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
