### ISSUE TITLE
LEDVANCE Smart+ Gardenpole Mini

### ISSUE THREAD

**Issue by Roarrk** [Koenkk/zigbee2mqtt#15710]
### What happened?

The device is seemingly correctly added, interview completes, power on/off works and I can change between Red and Green but no other color works (and it is green when selecting blue). Changing Hue changes from OFF, to Red, to Green, to OFF again. Trying to change color just turns it off except for blue which turns the device green. 

I would have written this off as a faulty device if it wasn't because I found an old issue that resembles the one I have. For them it was solved by a Z2M update - and now I can't find the issue....

I cannot update the firmware. As far as I can see a new update is avialable on update.ledvance.com (Gardenpole Mini RGBW Z3 | 3/17/2022 | 0x1189 | 0x0040 | 01066400) but Z2m detects manufacturerCode '4489' imageType '64'.

I have tried repairing multiple times. If anyone has any tips or things I can try I would appreciate it, otherwise I will return them after xmas.

### What did you expect to happen?

It is a White/Yellow + Color LED - it should work in all colors.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB

**Comment by HJoost** [comment]
I had the same issue on mine. The solution was that the connector between the poles and the controller was not alligned correctly (which is very easy to do if you don't pay full attention!). After assembling it right it works without problems :-)

**Comment by Roarrk** [comment]
Holy crap you are right. Awesome! Thank you.

**Comment by Roarrk** [comment]
> I had the same issue on mine. The solution was that the connector between the poles and the controller was not alligned correctly (which is very easy to do if you don't pay full attention!). After assembling it right it works without problems :-)

I had actually given up on these! It works. Thank you.
