### ISSUE TITLE
Some Aqara switches do not pair to zigbee2mqtt

### ISSUE THREAD

**Issue by alamoudimoh** [Koenkk/zigbee2mqtt#15737]
### What happened?

i have been struggling to get some of my aqara switches paired with zigbee2mqtt.

they were working before i had to re-setup everything.

it gets deducted but cannot have the full interview successfully done.

the below are the logs

### What did you expect to happen?

to get successfully paired

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

0x26660700

### Adapter

conbe

### Debug log

Error 2022-12-24 17:14:58Failed to interview '0x00158d00068a1398', device has not successfully been paired
Info 2022-12-24 17:14:58MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d00068a1398","ieee_address":"0x00158d00068a1398","status":"failed"},"type":"device_interview"}'
Info 2022-12-24 17:14:58MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x00158d00068a1398"},"type":"pairing"}'
Debug 2022-12-24 17:15:08Received Zigbee message from 'Kids Switch 01', type 'attributeReport', cluster 'genBasic', data '{"65281":{"100":0,"101":0,"149":133.16123962402344,"152":0,"154":0,"3":26,"5":76,"8":4158,"9":2816}}' from endpoint 1 with groupID null
Debug 2022-12-24 17:15:58Received Zigbee message from 'Master Switch 01', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,1,101,16,1,102,16,1,3,40,44,152,57,109,66,87,66,149,57,37,97,223,62,150,57,110,118,15,69,151,57,146,75,243,67,5,33,5,0,154,32,0,8,33,32,1,9,33,0,23,11,32,0,15,35,195,58,72,0],"type":"Buffer"}}' from endpoint 1 with groupID null
Debug 2022-12-24 17:15:58lumi.switch.n3acn3: Processed buffer into data {"3":44,"5":5,"8":288,"9":5888,"11":0,"15":4733635,"100":1,"101":1,"102":1,"149":0.4362880289554596,"150":2295.40185546875,"151":486.59039306640625,"152":53.81486892700195,"154":0}
Debug 2022-12-24 17:15:58lumi.switch.n3acn3: unknown key 15 with value 4733635
Debug 2022-12-24 17:15:58lumi.switch.n3acn3: Processed data into payload {"device_temperature":44,"power_outage_count":4,"state":"ON","energy":0.44,"consumption":0.44,"voltage":229.5,"current":0.4866,"power":53.81}
Debug 2022-12-24 17:15:58lumi.switch.n3acn3: Processed data into payload {"device_temperature":44,"power_outage_count":4,"state":"ON","energy":0.44,"consumption":0.44,"voltage":229.5,"current":0.4866,"power":53.81}
Info 2022-12-24 17:15:58MQTT publish: topic 'zigbee2mqtt/Master Switch 01', payload '{"action":null,"consumption":0.44,"current":0.4866,"device_temperature":44,"energy":0.44,"flip_indicator_light":null,"led_disabled_night":null,"linkquality":255,"operation_mode_center":null,"operation_mode_left":null,"operation_mode_right":null,"power":53.81,"power_outage_count":4,"power_outage_memory":null,"state":"ON","state_center":"ON","state_left":"ON","state_right":"ON","update":{"installed_version":"unknown","state":null},"update_available":null,"voltage":229.5}'
Debug 2022-12-24 17:16:10Received Zigbee message from 'Stairs Switch 01', type 'attributeReport', cluster 'genBasic', data '{"65281":{"100":0,"101":0,"149":23.818439483642578,"152":0,"154":0,"3":25,"5":31,"8":4158,"9":2817}}' from endpoint 1 with groupID null
Debug 2022-12-24 17:16:16Received Zigbee message from 'Master WC Switch', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,0,101,16,0,102,16,0,3,40,31,152,57,0,55,138,60,149,57,85,45,218,61,150,57,240,109,15,69,151,57,0,0,0,0,5,33,3,0,154,32,0,8,33,32,1,9,33,0,21,11,32,0,15,35,195,58,62,0],"type":"Buffer"}}' from endpoint 1 with groupID null
Debug 2022-12-24 17:16:16lumi.switch.n3acn3: Processed buffer into data {"3":31,"5":3,"8":288,"9":5376,"11":0,"15":4078275,"100":0,"101":0,"102":0,"149":0.1065317764878273,"150":2294.87109375,"151":0,"152":0.016871929168701172,"154":0}
Debug 2022-12-24 17:16:16lumi.switch.n3acn3: unknown key 15 with value 4078275
Debug 2022-12-24 17:16:16lumi.switch.n3acn3: Processed data into payload {"device_temperature":31,"power_outage_count":2,"state":"OFF","energy":0.11,"consumption":0.11,"voltage":229.5,"current":0,"power":0.02}
Debug 2022-12-24 17:16:16lumi.switch.n3acn3: Processed data into payload {"device_temperature":31,"power_outage_count":2,"state":"OFF","energy":0.11,"consumption":0.11,"voltage":229.5,"current":0,"power":0.02}
Info 2022-12-24 17:16:16MQTT publish: topic 'zigbee2mqtt/Master WC Switch', payload '{"action":null,"consumption":0.11,"current":0,"device_temperature":31,"energy":0.11,"flip_indicator_light":null,"led_disabled_night":null,"linkquality":255,"operation_mode_center":null,"operation_mode_left":null,"operation_mode_right":null,"power":0.02,"power_outage_count":2,"power_outage_memory":null,"state":"OFF","state_center":"OFF","state_left":"OFF","state_right":"OFF","update":{"installed_version":"unknown","state":null},"update_available":null,"voltage":229.5}'
Debug 2022-12-24 17:16:18Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"0x00158d00068a1398","transaction":"hv8f5-1"}'
Info 2022-12-24 17:16:18MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x00158d00068a1398"},"error":"Device '0x00158d00068a1398' cannot be configured","status":"error","transaction":"hv8f5-1"}'

**Comment by elliotcourant** [comment]
I'm having a similar problem; my `WS-USC01` was connected for maybe a few hours and then stopped responding completely. Trying to reconnect it after force-removing it I've had no luck. Not even getting to an interview stage with Zigbee2Mqtt. (sorry if this should have been in a separate issue).
