### ISSUE TITLE
EcoDim ED-10015 reports 200% battery level

### ISSUE THREAD

**Issue by geelenbert** [Koenkk/zigbee2mqtt#15767]
### What happened?

All EcoDim ED10015 devices report 200% battery level.
![Screenshot 2022-12-27 at 11 46 16](https://user-images.githubusercontent.com/91923/209655537-79707383-b871-4deb-b8f2-98f1573dde92.png)

I also have some ROB_200-025-0 devices that are essential the same models, which reports the battery level correctly. 
![Screenshot 2022-12-27 at 11 46 03](https://user-images.githubusercontent.com/91923/209655565-77cd16c4-1913-4d41-aa66-6ff7a0631b80.png)

### What did you expect to happen?

New battery level should not be more than 100%

### How to reproduce it (minimal and precise)

Fresh add a device, reports 100%

### Zigbee2MQTT version

1.28.4 

### Adapter firmware version

20220219

### Adapter

Zigstar Lan

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
