### ISSUE TITLE
Cannot remove attribute elapsed

### ISSUE THREAD

**Issue by waiweng83** [Koenkk/zigbee2mqtt#1576]
I enabled the attribute elapsed in the MQTT message for testing previously, after that I decided to disable it. However, the attribute is still appear in the MQTT message. The only different is the value does not get updated after disabled.

How do I remove it completely from the MQTT message?

**Comment by Koenkk** [comment]
Should be fixed in the latest dev branch

**Comment by waiweng83** [comment]
Thanks. Didn't notice it.
