### ISSUE TITLE
[New device support]: Marmitek Sense ME

### ISSUE THREAD

**Issue by Peterpc58** [Koenkk/zigbee2mqtt#15772]
### Link

https://marmitek.com/products/sense-me-motion-sensor-wireless-scene-activation-zigbee-3-0?scr=yes

### Database entry

{"id":83,"type":"EndDevice","ieeeAddr":"0x8cf681fffeba94eb","nwkAddr":40761,"manufId":4098,"manufName":"_TYZB01_yr95mpib","powerSource":"Battery","modelId":"SM0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,61183],"outClusterList":[25],"clusters":{"genPowerCfg":{"attributes":{"batteryVoltage":32,"batteryPercentageRemaining":200}},"genBasic":{"attributes":{"modelId":"SM0202","manufacturerName":"_TYZB01_yr95mpib","zclVersion":3,"appVersion":73,"powerSource":3}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0022a54ffb","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":7,"hwVersion":1,"dateCode":"20190728","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1672152455032,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to follow the supporting new device page but got stuck on how to upload an image and the .js file.
[Marmitek_SenseME.zip](https://github.com/Koenkk/zigbee2mqtt/files/10309467/Marmitek_SenseME.zip)

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'SM0202',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TYZB01_yr95mpib',
        },
    ],
    model: 'Sense ME',
    vendor: 'Marmitek',
    description: 'Motion sensor',
    fromZigbee: [fz.ias_occupancy_alarm_1_with_timeout, fz.battery],
    toZigbee: [],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: tuya.configureMagicPacket,
    exposes: [e.occupancy(), e.battery_low(), e.battery()],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
        ],
    },
};

module.exports = definition;

**Comment by Peterpc58** [comment]
Can this device be added?

**Comment by Peterpc58** [comment]
Is this the right place to add a device, or must I place it somewhere else to add it?

**Comment by Peterpc58** [comment]
Can this device be added?

**Comment by Peterpc58** [comment]
Bump

**Comment by Peterpc58** [comment]
Bump

**Comment by Koenkk** [comment]
To confirm, does the external converter in the OP work?

**Comment by Peterpc58** [comment]
Yes, the external converter is working.

**Comment by Koenkk** [comment]
added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
