### ISSUE TITLE
Unable to get devices in HASSIO ( Ikea bulb not recoqnized? )

### ISSUE THREAD

**Issue by Bart-1992** [Koenkk/zigbee2mqtt#1577]
# Bug Report
## What happened

I've tried to get Zigbee2mqtt up and running via the Hassio intergrated add-on. Looking at the log's everything is running fine however the device i'm trying to control is not recognized --> see log @ line 19/21. Probably the device is not appearing in the Hassio UI because it's not parsed to the MQTT broker? 

[https://hastebin.com/xebibixexa.sql](url)

## What did you expect to happen
It should be recognized since it's in the supported devices list? 

## Debug Info
zigbee2mqtt version:
Running on zigbee2mqtt 1.4. Hassio add-on

**Comment by Koenkk** [comment]
On line 23 you see that the device discovery message is send.

- Did you enable discovery in home assistant? (http://www.zigbee2mqtt.io/integration/home_assistant.html#mqtt-discovery)
- Is there anything under Home Assistant -> Configuration -> Integrations -> MQTT?

**Comment by Bart-1992** [comment]
Thanks, got it working!
Apparently something was wrong within the broker settings....!
