### ISSUE TITLE
SNZB-02 keeps disconnecting / freezing

### ISSUE THREAD

**Issue by JacekKac** [Koenkk/zigbee2mqtt#15776]
### What happened?

SNBZ-02 often keeps freezing - they are not reporting. Keeping 5sec gives "Device left" and then reconnecting - but configuration gives 
`
 2022-12-28 14:24:48: Configure failed: Error: Bind 0x00124b002549bfd4/1 msTemperatureMeasurement from '0x00124b00257939b2/1' failed (AREQ - ZDO - bindRsp after 10000ms)
`
i need to force remove the device and repair again

Don't know exactly the reason.. nothing regular. Range is ok.

### What did you expect to happen?

constantly reporting

### How to reproduce it (minimal and precise)

not sure

### Zigbee2MQTT version

1.28.0-dev commit: f8d64b67 but happens on many

### Adapter firmware version

20220219

### Adapter

zStack3x0 /  usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_464f59958012ec11a5ec23c7bd930c07-if00-port0 

### Debug log

no logging available

**Comment by Olomonster** [comment]
Did you try to force remove, restart z2m and then repair it?
Maybe adding a smaller report interval helps also.

**Comment by JacekKac** [comment]
yes when i do this it's working fine, but not sure if it will be stable in the future. Recently my whole (small - 7 end devices network) was affected when i temporarly unpluged wall socket (repeater).  4 of SNZB-02 stopped reporting,pluging back the wall socket didn't help they where freazed

**Comment by mimas71** [comment]
I confirm, after a power outage it is not possible to connect in the place where it worked normally before. When approaching the coordinator, after pressing the button it is possible to connect, after returning the snzb02 to its place, after about 28 hours it stops transmitting the status, but it is connected in zigbee2mqtt.

domoticz - plugin: v.3.2.0-beta, zigbee2mqtt: v.1.28.4 (zStack3x0 20210708)

**Comment by JacekKac** [comment]
What is interesting that these sensor are not willing to use router wall plug as the Tuya thermostats do. numbers are rooms. Router wallplug is in room 1 - temp 1 should definitivly use wallplug instead of direct / poor connection to coordinator

![image](https://user-images.githubusercontent.com/72306272/210050739-1cb33a67-908d-453e-b6dd-9fdf6f0aa314.png)

**Comment by JacekKac** [comment]
> I confirm, after a power outage it is not possible to connect in the place where it worked normally before. When approaching the coordinator, after pressing the button it is possible to connect, after returning the snzb02 to its place, after about 28 hours it stops transmitting the status, but it is connected in zigbee2mqtt.
> 
> domoticz - plugin: v.3.2.0-beta, zigbee2mqtt: v.1.28.4 (zStack3x0 20210708)

imho it's range issue and putting them back on place after reconfigure will not guarantee stable reporting
