### ISSUE TITLE
CC2531 Zigbee3.0 does not work

### ISSUE THREAD

**Issue by guitar9** [Koenkk/zigbee2mqtt#1579]
With the zigbee 1.2 Version everythinks works fine. With the zigbee 3.0 version it does not work.
I tried to put the reset Button.

I am using docker. This is how I am starting it.

```
docker run \
   -it \
   --name=zigbee2mqtt \
   --restart=always \
   -v /home/pi/mqtt/zigbee2mqtt:/app/data \
   --net=host \
   --device=/dev/ttyACM0 \
   koenkk/zigbee2mqtt
```

I get this error:
![Bildschirmfoto_2019-05-27_21-23-25](https://user-images.githubusercontent.com/25721108/58436585-5f2a5300-80c6-11e9-99f8-41440f0c6879.png)

**Comment by ccalica** [comment]
1.3.0 is pretty old, try upgrading.  Be sure to update npm_modules to grab newest zigbee-shepherd too. 

Just noticed you're using docker.  Try repulling?

**Comment by Koenkk** [comment]
Zigbee 3.0 requires zigbee2mqtt 1.4. In case of any further issue please continue in #1445
