### ISSUE TITLE
Classic B40 TW - LIGHTIFY

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#158]
same as PAR16 50 TW but other socket

**Comment by Koenkk** [comment]
Can you follow: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices?

**Comment by arteck** [comment]
done

**Comment by ciotlosm** [comment]
@arteck a pull request with the support for the devices would be more than welcome

**Comment by arteck** [comment]
its done
