### ISSUE TITLE
[New device support]: Aqara H1 Switches

### ISSUE THREAD

**Issue by ChengyiP** [Koenkk/zigbee2mqtt#15800]
### Link

https://www.aqara.com/cn/d27_overview

### Database entry

{"id":34,"type":"Router","ieeeAddr":"0x54ef441000277067","nwkAddr":30772,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.n2acn1","epList":[1,2,21,41,42,51,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.n2acn1","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":51,"stackVersion":2,"hwVersion":1,"dateCode":"02-17-2022"}},"aqaraOpple":{"attributes":{"15":{"type":"Buffer","data":[1,10,0,0,0,0,16,16,51,0,0,0,2,10,0,240,2,0,0,240,15,0,0,0]},"223":{"type":"Buffer","data":[22,33,0,0,23,33,0,0,12,33,1,0,24,33,201,6,30,33,31,0,31,33,208,86,32,33,142,235,34,33,24,43,35,33,0,0,36,32,0,37,35,20,180,55,118,254,35,144,0,8,0]},"229":{"type":"Buffer","data":[23,17,6,244,173,37,80,181,197,37,161,166,135,37,125,42,254,37,70,0,0,36,97,187,69,37,101]},"238":3891,"240":1,"247":{"type":"Buffer","data":[100,16,0,101,16,0,3,40,30,152,57,0,0,0,0,149,57,0,0,0,0,150,57,244,13,21,69,151,57,0,0,0,0,5,33,2,0,154,32,0,9,33,2,21,13,35,51,15,0,0,14,35,0,0,0,0,10,33,0,0,12,32,1,17,35,1,0,0,0]},"512":0,"513":1,"515":1,"670":0}},"genOnOff":{"attributes":{"245":117440551,"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"245":117440552,"onOff":0}},"aqaraOpple":{"attributes":{"512":0}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"epId":21,"inClusterList":[],"outClusterList":[],"clusters":{"genAnalogInput":{"attributes":{"presentValue":0}}},"binds":[],"configuredReportings":[],"meta":{}},"41":{"epId":41,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"42":{"epId":42,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"51":{"epId":51,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":51,"stackVersion":2,"hwVersion":1,"dateCode":"02-17-2022","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2114939527},"lastSeen":1672307890105,"defaultSendRequestWhen":"immediate"} {"id":35,"type":"Router","ieeeAddr":"0x54ef4410002c417f","nwkAddr":64945,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.n3acn1","epList":[1,2,3,21,31,41,42,43,51,52,53,61,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6,18,64704],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.n3acn1","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":51,"stackVersion":2,"hwVersion":1,"dateCode":"02-17-2022"}},"aqaraOpple":{"attributes":{"15":{"type":"Buffer","data":[1,10,0,0,0,0,16,16,51,0,0,0,2,10,0,240,3,0,0,240,15,0,0,0]},"223":{"type":"Buffer","data":[22,33,0,0,23,33,0,0,12,33,1,0,24,33,244,2,30,33,23,0,31,33,149,86,32,33,169,188,34,33,120,43,35,33,0,0,36,32,0,37,35,127,40,221,123,254,35,144,0,8,0]},"229":{"type":"Buffer","data":[22,17,5,214,90,37,109,78,184,37,105,194,162,37,88,87,162,37,86,187,57,37,100]},"238":3891,"240":1,"247":{"type":"Buffer","data":[100,16,0,101,16,0,102,16,0,3,40,31,152,57,0,0,0,0,149,57,0,0,0,0,150,57,220,198,21,69,151,57,0,0,0,0,5,33,2,0,154,32,0,9,33,1,21,13,35,51,15,0,0,14,35,0,0,0,0,10,33,187,57,12,32,1,17,35,1,0,0,0]},"512":0,"670":0}},"genOnOff":{"attributes":{"245":117440524,"onOff":0}}},"binds":[],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6,18,64704],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"245":117440524,"onOff":0}},"aqaraOpple":{"attributes":{"512":0}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[0,3,4,5,6,18,64704],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"genOnOff":{"attributes":{"245":117440531,"onOff":0}},"aqaraOpple":{"attributes":{"512":0}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"profId":260,"epId":21,"devId":256,"inClusterList":[12],"outClusterList":[],"clusters":{"genAnalogInput":{"attributes":{"presentValue":0}}},"binds":[],"configuredReportings":[],"meta":{}},"31":{"profId":260,"epId":31,"devId":256,"inClusterList":[12],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"41":{"profId":260,"epId":41,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"42":{"profId":260,"epId":42,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":2}}},"binds":[],"configuredReportings":[],"meta":{}},"43":{"profId":260,"epId":43,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":2}}},"binds":[],"configuredReportings":[],"meta":{}},"51":{"profId":260,"epId":51,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"52":{"profId":260,"epId":52,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"53":{"profId":260,"epId":53,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"61":{"profId":260,"epId":61,"devId":256,"inClusterList":[18],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":51,"stackVersion":2,"hwVersion":1,"dateCode":"02-17-2022","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1776901250},"lastSeen":1672310170237,"defaultSendRequestWhen":"immediate"} {"id":46,"type":"EndDevice","ieeeAddr":"0x04cf8cdf3c88858c","nwkAddr":36998,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.l2acn1","epList":[1,2,41,42,51,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6,9],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.l2acn1","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":33,"stackVersion":2,"hwVersion":1,"dateCode":"05-17-2020"}},"aqaraOpple":{"attributes":{"238":3617,"247":{"type":"Buffer","data":[100,16,1,101,16,1,3,40,26,5,33,3,0,154,32,0,10,33,71,60,11,32,0,13,35,33,14,0,0,14,35,0,0,0,0]},"512":0}},"genOnOff":{"attributes":{"245":117440561,"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6,18,64704],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"245":117440535,"onOff":1}},"genBasic":{"attributes":{}},"aqaraOpple":{"attributes":{"512":0}}},"binds":[],"configuredReportings":[],"meta":{}},"41":{"epId":41,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"42":{"epId":42,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"51":{"epId":51,"inClusterList":[],"outClusterList":[],"clusters":{"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":33,"stackVersion":2,"hwVersion":1,"dateCode":"05-17-2020","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2114939527},"lastSeen":1672307764792,"defaultSendRequestWhen":"immediate"}

### Comments

Manage to add Aqara H1 pro 3 gang switches(with neutral) and Aqara H1 2 gang(without neutral) switches 

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const constants = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const globalStore = require('zigbee-herdsman-converters/lib/store');
const xiaomi = require('zigbee-herdsman-converters/lib/xiaomi');
const utils = require('zigbee-herdsman-converters/lib/utils');
const {
    precisionRound, mapNumberRange, isLegacyEnabled, toLocalISOString, numberWithinRange, hasAlreadyProcessedMessage,
    calibrateAndPrecisionRoundOptions, addActionGroup, postfixWithEndpointName, getKey,
    batteryVoltageToPercentage, getMetaValue,
} = require('zigbee-herdsman-converters/lib/utils');

const preventReset = async (type, data, device) => {
    if (
        // options.allow_reset ||
        type !== 'message' ||
        data.type !== 'attributeReport' ||
        data.cluster !== 'genBasic' ||
        !data.data[0xfff0] ||
        // eg: [0xaa, 0x10, 0x05, 0x41, 0x87, 0x01, 0x01, 0x10, 0x00]
        !data.data[0xFFF0].slice(0, 5).equals(Buffer.from([0xaa, 0x10, 0x05, 0x41, 0x87]))
    ) {
        return;
    }
    const options = {manufacturerCode: 0x115f};
    const payload = {[0xfff0]: {
        value: [0xaa, 0x10, 0x05, 0x41, 0x47, 0x01, 0x01, 0x10, 0x01],
        type: 0x41,
    }};
    await device.getEndpoint(1).write('genBasic', payload, options);
};

const aqara_multi_action = {
        cluster: 'genMultistateInput',
        type: ['attributeReport'],
        convert: (model, msg, publish, options, meta) => {
            if (hasAlreadyProcessedMessage(msg, model)) return;
            let actionLookup = {0: 'hold', 1: 'single', 2: 'double', 3: 'triple', 255: 'release'};
            let buttonLookup = null;
            if (['QBKG28LM'].includes(model.model)) {
                buttonLookup = {
                    41: 'left', 42: 'right', 51: 'both'
                };
            }
            if (['QBKG32LM'].includes(model.model)) {
                buttonLookup = {
                    41: 'left', 42: 'center', 43: 'right',
                    51: 'left_center', 52: 'left_right', 53: 'center_right',
                    61: 'all',
                };
            }
            const action = actionLookup[msg.data['presentValue']];
            if (buttonLookup) {
                const button = buttonLookup[msg.endpoint.ID];
                if (button) {
                    return {action: `${action}_${button}`};
                }
            } else {
                return {action};
            }
        },
};


const definition = [
        {
        zigbeeModel: ['lumi.switch.n1acn1'],
        model: 'QBKG30LM',
        vendor: 'Xiaomi',
        description: 'Aqara smart wall switch H1 Pro (with neutral, single rocker)',
        fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple, fz.xiaomi_multistate_action],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode_opple, tz.xiaomi_switch_power_outage_memory,
            tz.xiaomi_led_disabled_night, tz.xiaomi_flip_indicator_light],
        exposes: [
            e.switch(), e.action(['single', 'double']), e.power().withAccess(ea.STATE), e.energy(),
            e.voltage().withAccess(ea.STATE), e.device_temperature().withAccess(ea.STATE),
            e.power_outage_memory(), e.led_disabled_night(), e.flip_indicator_light(),
            exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
                .withDescription('Decoupled mode for left button'),
        ],
        onEvent: preventReset,
        ota: ota.zigbeeOTA,
    },
    {
        zigbeeModel: ['lumi.switch.l2acn1'],
        model: 'QBKG28LM',
        vendor: 'Aqara',
        description: 'Aqara smart wall switch H1 (non neutral, double rocker)',
        fromZigbee: [fz.on_off, fz.aqara_opple, aqara_multi_action],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode_opple, tz.xiaomi_flip_indicator_light],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'right': 2};
        },
        exposes: [
            e.switch().withEndpoint('left'),
            e.switch().withEndpoint('right'),
            e.power().withAccess(ea.STATE_GET),
           e.action([
                'single_left', 'single_right', 'single_both',
                'double_left', 'double_right', 'double_both']),
            exposes.enum('operation_mode', ea.ALL, ['control_left_relay', 'decoupled'])
                .withDescription('Decoupled mode for left button')
                .withEndpoint('left'),
            exposes.enum('operation_mode', ea.ALL, ['control_right_relay', 'decoupled'])
                .withDescription('Decoupled mode for right button')
                .withEndpoint('right'),
        ],
        configure: async (device, coordinatorEndpoint, logger) => {
            await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
        },
        onEvent: preventReset,
        ota: ota.zigbeeOTA,
    },
    {
        zigbeeModel: ['lumi.switch.n3acn1'],
        model: 'QBKG32LM',
        vendor: 'Aqara',
        description: 'Aqara smart wall switch H1 Pro (with neutral, three rocker)',
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'right': 2, 'center': 3};
        },
        fromZigbee: [fz.on_off, fz.xiaomi_power, fz.aqara_opple, aqara_multi_action],
        toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode_opple, tz.xiaomi_switch_power_outage_memory,
            tz.xiaomi_led_disabled_night, tz.xiaomi_flip_indicator_light],
        exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('right'), e.switch().withEndpoint('center'), e.power(), e.energy(), e.voltage(),
            e.device_temperature(), e.power_outage_memory(), e.led_disabled_night(), e.flip_indicator_light(),
            e.action([
                'left', 'right', 'center']),
            exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
                .withDescription('Decoupled mode for left button').withEndpoint('left'),
            exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
                .withDescription('Decoupled mode for right button').withEndpoint('right'),
            exposes.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled'])
                .withDescription('Decoupled mode for right button').withEndpoint('center')],
        onEvent: preventReset,
        ota: ota.zigbeeOTA,
    },
];

module.exports = definition;
```

**Comment by Keglerz** [comment]
when will H1 3gang no neutral be added?
