### ISSUE TITLE
Moes Smart dimmer module (MS-105Z)

### ISSUE THREAD

**Issue by Steini1984** [Koenkk/zigbee2mqtt#15804]
### What happened?

I installed some [MS-105Z](https://moeshouse.com/products/zigbee-dimmer-module) and have found three issues I wanted to report: 

**1: I cannot bind** the modules to my wall switches (ZG2833K8_EU05) and Z2M gives this error: "Nothing to bind". I guess it´s because the "genOnOff" is not mapped as a input cluster:
![image](https://user-images.githubusercontent.com/5666926/209961852-2269870f-90d3-4915-8f23-b10797336531.png)

I maybe thought it was not supported from the manufacturer, but I also installed a Moes MS-104NZ Switch module which can bind without problems. 
![image](https://user-images.githubusercontent.com/5666926/209961943-5bd03c94-7acb-4cd6-8342-3cbf9afdfd38.png)

**2: Transition.** I use this with Home Assistant and when I set transition as a parameter I get this error:
![image](https://user-images.githubusercontent.com/5666926/209962372-5ae3754e-39e3-4639-b468-e4f3f0383f96.png)
The problem for is that when this fails it also fails for the other parameters, like transition (which work fine on their own)

**3: Wrong identification:** It is presented as a TS0601_dimmer_1 from TuYa and shows a wrong icon for a wall switch:
![image](https://user-images.githubusercontent.com/5666926/209961561-8c077254-2ba2-46c2-9cfd-9e26a963d4bc.png)

This would be more fitting:
![image](https://user-images.githubusercontent.com/5666926/209961579-8e420f7d-dee1-4bb8-8344-2d7574370e77.png)

### What did you expect to happen?

1: That I can bind the dimmer to my wall switch for on/off and dimming functions without using Z2M and Home assistant

2: That I could either set the transition time, or Z2M would gracefully ignore that request but set the brightness from the request

3: That I would get the correct name and icon for the module 

### How to reproduce it (minimal and precise)

1: Go to a wall switch and try to bind it to the dimming module:
![image](https://user-images.githubusercontent.com/5666926/209962991-740a5921-9ee1-4185-ac79-5ec8cd90a0fa.png)

2: Turn on the light via Home Assistant with a brightness and transition parameteres:
```
service: light.turn_on
data:
  brightness: 255
  transition: 1
target:
  entity_id: light.gangur_kristall
```

3: Add a Moes MS-105Z device to Z2M and go to "Devices"

### Zigbee2MQTT version

1.28.4 commit: unknown

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

**Comment by arveeproject** [comment]
Anybody already looked into it? I have the same problem see #15803

**Comment by Steini1984** [comment]
I tried making a custom converter to see if I can fix some of the bugs.

I´m running Homeassistant and the zigbee2mqtt as an addon. I tried making a custom converter from the (What I think are) the relevant parts of https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js  and also added 
"tz.ignore_transition" which I hope fixes issue nr 2. 

After some adjustments the converter does not give any errors and z2m loads, but I dont know **how to make z2m prefer my custom converter** over the default one. Any ideas?

Here is my custom converter: https://pastebin.com/raw/sB52tMME

**Comment by ambarusa** [comment]
@Steini1984 Hi, I am also having the same blocker. Could you progress with the converter?

**Comment by Steini1984** [comment]
> @Steini1984 Hi, I am also having the same blocker. Could you progress with the converter?

Sorry did not see you comment until now, but no I kinda gave up :(

**Comment by juagicre** [comment]
How do you put the device in pairing mode?? 
Manual says: "After the wiring of a switch module is done, press the return button switch for 10 times (keep time interval not too short) until the beep sound continuously and rapidly as Di-Di-Di.... for pairing mode". 
In my case I don't want to use any switch, so I did not connect any (they show a diagram for this case in the manual as well!). 
Should I connect it just for this purpose? Would a regular ON/OFF switch work and myself doing the return action manually?

**Comment by chelming** [comment]
> How do you put the device in pairing mode?

damn this was annoying (and the first result on google)

To put the device into pairing mode you need to connect `L` to `S` ten times in quick succession and then give it a second after the tenth one. I just used a multimeter to do this instead of connecting a switch. You'll hear three loud beeps then rapid beeps. It took me three tries to get it in pairing mode.

**Comment by EuthaNasi** [comment]
> > How do you put the device in pairing mode?
> 
> damn this was annoying (and the first result on google)
> 
> To put the device into pairing mode you need to connect `L` to `S` ten times in quick succession and then give it a second after the tenth one. I just used a multimeter to do this instead of connecting a switch. You'll hear three loud beeps then rapid beeps. It took me three tries to get it in pairing mode.

Thanks for your insight, I connected a regular light switch to it and turned it on-off for 10 times and it worked like a charm. Based on the manual I thought you needed a smart switch but luckily not!
