### ISSUE TITLE
Bridge stats 

### ISSUE THREAD

**Issue by timoline** [Koenkk/zigbee2mqtt#15815]
### Is your feature request related to a problem? Please describe

Maybe its an idea to put the frontend stats in the backend (bridge topic)

### Describe the solution you'd like

Add stats to the bridge topic

### Describe alternatives you've considered

none

### Additional context

<img width="479" alt="image" src="https://user-images.githubusercontent.com/680252/210043622-a555596f-f623-4f32-b805-38b2b0dde7c1.png">

**Comment by Bascht74** [comment]
Yes! An please add a last device udate timestamp that you can use to check if everything is working the way it should.
