### ISSUE TITLE
unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_cpmgn2cf'

### ISSUE THREAD

**Issue by 4sp3c** [Koenkk/zigbee2mqtt#15817]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0x84ba20fffe7a935c","nwkAddr":52876,"manufId":4098,"manufName":"_TZE200_cpmgn2cf","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_cpmgn2cf","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1672390439046,"useImplicitCheckin":true}

### Comments

Zigbee2MQTT:info  2022-12-30 09:53:48: Device '0x84ba20fffe7a935c' joined
Zigbee2MQTT:info  2022-12-30 09:53:48: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84ba20fffe7a935c","ieee_address":"0x84ba20fffe7a935c"},"type":"device_joined"}'
Zigbee2MQTT:info  2022-12-30 09:53:48: Starting interview of '0x84ba20fffe7a935c'
Zigbee2MQTT:info  2022-12-30 09:53:48: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84ba20fffe7a935c","ieee_address":"0x84ba20fffe7a935c","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:debug 2022-12-30 09:53:49: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZE200_cpmgn2cf","modelId":"TS0601"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:49: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:52: Received Zigbee message from '0x84ba20fffe7a935c', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:52: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:52: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:53: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:53: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:53: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"appVersion":85}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:53: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:53: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:54: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:58: Received Zigbee message from '0x84ba20fffe7a935c', type 'commandSetTimeRequest', cluster 'manuSpecificTuya', data '{"payloadSize":7680}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:58: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:58: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:58: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:58: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:58: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2022-12-30 09:53:59: Received Zigbee message from '0x84ba20fffe7a935c', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2022-12-30 09:53:59: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2022-12-30 09:53:59: Successfully interviewed '0x84ba20fffe7a935c', device has successfully been paired
Zigbee2MQTT:warn  2022-12-30 09:53:59: Device '0x84ba20fffe7a935c' with Zigbee model 'TS0601' and manufacturer name '_TZE200_cpmgn2cf' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:info  2022-12-30 09:53:59: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x84ba20fffe7a935c","ieee_address":"0x84ba20fffe7a935c","status":"successful","supported":false},"type":"device_interview"}'
Zigbee2MQTT:debug 2022-12-30 09:54:18: Received Zigbee message from '0x84ba20fffe7a935c', type 'raw', cluster 'manuSpecificTuya', data '{"data":[9,39,17,0,31,102],"type":"Buffer"}' from endpoint 1 with groupID 0
Zigbee2MQTT:warn  2022-12-30 09:54:18: Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_cpmgn2cf'
Zigbee2MQTT:warn  2022-12-30 09:54:18: Please see: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Zigbee2MQTT:debug 2022-12-30 09:54:20: Received MQTT message on 'zigbee2mqtt/0x84ba20fffe7a935c/set/force' with data 'open'
Zigbee2MQTT:error 2022-12-30 09:54:20: Cannot publish to unsupported device '0x84ba20fffe7a935c'

*******************************************************************

I wrote on configuration.yalm these lines

externals_converters:
  - TuYa.js

on this file (on the same directory of configuration.yalm) i put the file from link
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js

on line 2087 there is 

{modelID: 'TS0601', manufacturerName: '_TZE200_cpmgn2cf'},

I don't understand how to solve it

***********************************************************************

thank you for your help

**Comment by Koenkk** [comment]
Should be supported in z2m 1.28.4
