### ISSUE TITLE
Sorting devices on Availability doesnt sort Disabled items together

### ISSUE THREAD

**Issue by ahd71** [Koenkk/zigbee2mqtt#15854]
### What happened?

Minor issue but sorting of Availability doesn't seemt to respect the new Disabled state yet.

### What did you expect to happen?

Group them together (online, offline and disabled devices in three different consecutive blocks)

### How to reproduce it (minimal and precise)

Disable at least a few devices and sort all

### Zigbee2MQTT version

1.29

### Adapter firmware version

NA

### Adapter

NA (but I have zzh)

**Comment by ahd71** [comment]
![Uploading Screenshot_20230101_115616_Chrome.jpg…]()

**Comment by ahd71** [comment]
![Screenshot_20230101_115616_Chrome](https://user-images.githubusercontent.com/1518011/210168260-026f08e8-2c12-40a2-a92b-080064e1939c.jpg)

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend
