### ISSUE TITLE
Docker issue after 1.29.0

### ISSUE THREAD

**Issue by Tolriq** [Koenkk/zigbee2mqtt#15853]
### What happened?

After update image is broken

Logs shows:
```
Using '/app/data' as data directory

/usr/local/bin/docker-entrypoint.sh: exec: line 17: npm: not found
```

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

N/A

### Adapter

Conbee2

### Debug log

Using '/app/data' as data directory

/usr/local/bin/docker-entrypoint.sh: exec: line 17: npm: not found

**Comment by goessensj** [comment]
Same issue here

**Comment by Tolriq** [comment]
From https://github.com/Koenkk/zigbee2mqtt/commit/8d8c46ecaef526a2077d740eb292f196f38a7962 seems like when updating docker via like portainer with a pull latest image, it does not run the necessary steps to install the missing pieces.

It probably require some migration steps, but I don't really know how.

Backup the config and restart from 1.29 probably works, will wait for @Koenkk feedback before attempting this.

**Comment by Koenkk** [comment]
It seems you are overriding the default command (probably via portainer). `npm` has been removed from the image to reduce the image size. So either don't override the default command or change it to `/sbin/tini -- node index.js`

**Comment by Tolriq** [comment]
I have not changed anything.

![image](https://user-images.githubusercontent.com/932609/210212031-acc17557-fbc1-4b8a-8c61-618391bb2441.png)

**Comment by Koenkk** [comment]
And here https://docs.portainer.io/user/docker/containers/advanced ?

**Comment by Tolriq** [comment]
Nope no override, but I just started fresh as a good test for my backup strategy and it works.

So I probably missed something at some point in a previous release, this container was quite old.

Anyway thanks for the help.
