### ISSUE TITLE
Home assistant plugin can't start

### ISSUE THREAD

**Issue by seri530** [Koenkk/zigbee2mqtt#15855]
### What happened?

Hi,
After I updated to this version, the home assistant plugin can't start. The advanced settings are missing from the configuration tab. No other steps/updates happened between the update and the fail.
I don't see any notes or logs about any deprecated setting or required update.

It looks like it could not detect the non-default pan id, but I'm not sure.

The system is running on a Raspberry Pi 4 with Electrolama zig-a-zig-ah! (zzh!)
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

### How to reproduce it (minimal and precise)

After the update it fails every time

### Zigbee2MQTT version

1.29.0-1

### Adapter firmware version

can't start it to see

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

### Debug log

[12:26:04] INFO: Preparing to start...
[12:26:05] INFO: Socat not enabled
[12:26:07] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-01 12:26:13: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-01.12-26-13' filename: log.txt
Zigbee2MQTT:info  2023-01-01 12:26:13: Starting Zigbee2MQTT version 1.29.0 (commit #unknown)
Zigbee2MQTT:info  2023-01-01 12:26:13: Starting zigbee-herdsman (0.14.83)
Zigbee2MQTT:error 2023-01-01 12:26:13: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2023-01-01 12:26:13: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2023-01-01 12:26:13: - Extended PAN ID: configured=5ce9878be2c3dddd, adapter=00124b0022b77eaa
Zigbee2MQTT:error 2023-01-01 12:26:13: - Network Key: configured=01030507090b0d0f00020406080a1c1d, adapter=01030507090b0d0f00020406080a1c0d
Zigbee2MQTT:error 2023-01-01 12:26:13: - Channel List: configured=11, adapter=11
Zigbee2MQTT:error 2023-01-01 12:26:13: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2023-01-01 12:26:13: If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json.
Zigbee2MQTT:error 2023-01-01 12:26:13: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2023-01-01 12:26:13: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-01 12:26:13: Failed to start zigbee
Zigbee2MQTT:error 2023-01-01 12:26:13: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-01 12:26:13: Exiting...
Zigbee2MQTT:error 2023-01-01 12:26:14: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by Koenkk** [comment]
Try setting the network key and extended pan id manually in the z2m `configuration.yaml`.
