### ISSUE TITLE
Error in documentation on Danfoss thermostat (and Popp)

### ISSUE THREAD

**Issue by branexius** [Koenkk/zigbee2mqtt#15869]
### What happened?

The documentation is contradictory in regards to the meaning of the setting of the Radiator_covered setting under section "External_measured_room_sensor (numeric)" and "Radiator_covered (binary)".
[https://www.zigbee2mqtt.io/devices/014G2461.html](url)
![Snipaste_2023-01-01_21-47-07](https://user-images.githubusercontent.com/84248070/210184209-5bd00f13-c788-4de2-84ef-5d940a0ad43b.png)

### What did you expect to happen?

Unified meanining

### How to reproduce it (minimal and precise)

It just existst.

### Zigbee2MQTT version

1.29.0-1

### Adapter firmware version

20221213.0

### Adapter

CC2652P

**Comment by TomTonic** [comment]
Just checked the Danfoss docu:

_FALSE = Auto Offset Mode for Exposed Radiators
TRUE = Room Sensor Mode (allows Covered Radiators)_
