### ISSUE TITLE
version information is wrong

### ISSUE THREAD

**Issue by SVH-Powel** [Koenkk/zigbee2mqtt#15877]
### What happened?

All light is suddenly reporting strange version information. The light in the log is a Philips Hue Fair model 4034031P7

### What did you expect to happen?

I expect it to report installed version to be 1.88.1. The user interface in the OTA section shows 1.88.1 in the firmware version column.

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

Sonoff type P, zStack3x0

### Debug log

2023-01-02 09:57:17Checking if update available for 'Gang 1. etg b'
Info 2023-01-02 09:57:17MQTT publish: topic 'zigbee2mqtt/Gang 1. etg b', payload '{"brightness":100,"color_mode":"color_temp","color_temp":454,"last_seen":"2023-01-02T09:57:00+01:00","linkquality":98,"power_on_behavior":"off","state":"OFF","update":{"installed_version":16785152,"latest_version":16786176,"state":"idle"},"update_available":null}'
Info 2023-01-02 09:57:17No update available for 'Gang 1. etg b'

**Comment by stigvi** [comment]
The first one have a state with correct version information.
```
{
    "brightness": 147,
    "color_mode": "color_temp",
    "color_temp": 274,
    "last_seen": "2023-01-03T15:11:35+01:00",
    "linkquality": 153,
    "power_on_behavior": "off",
    "state": "OFF",
    "update": {
        "installed_version": "1.88.1",
        "state": "available"
    }
}
```

This lamps state is showing version 16785152, but in reality it is 1.88.1 and the same as the light state for the lamp above.
```
{
    "brightness": 129,
    "color_mode": "color_temp",
    "color_temp": 274,
    "last_seen": "2023-01-03T15:58:33+01:00",
    "linkquality": 102,
    "power_on_behavior": "off",
    "state": "ON",
    "update": {
        "installed_version": 16785152,
        "latest_version": 16786176,
        "state": "idle"
    }
}
```
