### ISSUE TITLE
Moes BRT-100-TRV (TS0601 - _TZE200_b6wax7g0) - system mode "off" seem not work

### ISSUE THREAD

**Issue by Ivano62** [Koenkk/zigbee2mqtt#15887]
### What happened?

When I click on the "off" value nothing happens, as far as I can see it seems that the mqtt message with the correct value is not being sent. However, the state of the valve does not change and the HA climate remains unchanged.

### Zigbee2MQTT version

1.29.0-dev (commit: 826f032)

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by Ivano62** [comment]
The problem persists even with the latest dev version

**Comment by Ivano62** [comment]
The problem persists even with the latest version 1.29.1

**Comment by Ivano62** [comment]
The problem persists even with the latest version 1.29.1-dev commit: [e773511]

**Comment by Ivano62** [comment]
The problem persists with the latest version 1.29.1-dev commit [d90dae5]

**Comment by Ivano62** [comment]
problem persists with the latest version 1.29.1-dev commit [1d8b19d]

**Comment by Ivano62** [comment]
Nothing, problem persists with the latest version 1.29.2

**Comment by airestonia** [comment]
I can confirm that unfortunately this indeed doesn't work, even on the latest dev branch of the Zigbee2MQTT Edge.

**Comment by Ivano62** [comment]
Problem persists with the latest dev version

**Comment by rtsymbal** [comment]
I have same issue

**Comment by svisso** [comment]
I have used couple of these TRVs up and until V 1.28.0. After upgrading to 1.28.1 and (today) 1.29.1, the Thermostats don't get read correctly, mostly returning null values to z2m. Unusable. I have to stick with 1.28.0 until rescue will be engineered.
Any help highly appreciated.

**Comment by Ivano62** [comment]
I don't think it's a hardware problem, however with the latest dev versions the "off" value has been removed. Thanks
