### ISSUE TITLE
Error message when adding Philips HUE Festavia (929003535301) into my network

### ISSUE THREAD

**Issue by FredericGuardia** [Koenkk/zigbee2mqtt#15883]
### What happened?

During initial interview of the device,  some error messages appear in the log file during the configuration step.
This error message appears several time inside log:
Failed to configure '0x001788010d629539', attempt 1 (TypeError: extendDontUse.light_onoff_brightness_colortemp_color(...).configure is not a function

### What did you expect to happen?

I expect to have device integrated and configured without any troubles during the interview phase.

### How to reproduce it (minimal and precise)

Integrate this device into your network and check zigbee2mqtt logs.

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20221102

### Adapter

SMLIGHT CC2652P Zigbee USB Adapter SLZB-02

### Debug log

info  2023-01-02 09:41:07: Device '0x001788010d629539' joined
info  2023-01-02 09:41:07: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d629539","ieee_address":"0x001788010d629539"},"type":"device_joined"}'
info  2023-01-02 09:41:07: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x001788010d629539"},"type":"device_connected"}'
info  2023-01-02 09:41:07: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539/availability', payload 'online'
info  2023-01-02 09:41:07: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","model":"unknown","networkAddress":2368,"type":"Unknown"},"last_seen":"2023-01-02T09:41:07+01:00"}'
info  2023-01-02 09:41:07: Starting interview of '0x001788010d629539'
info  2023-01-02 09:41:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d629539","ieee_address":"0x001788010d629539","status":"started"},"type":"device_interview"}'
info  2023-01-02 09:41:08: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x001788010d629539"},"type":"pairing"}'
info  2023-01-02 09:41:08: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","model":"unknown","networkAddress":2368,"type":"Unknown"},"last_seen":"2023-01-02T09:41:08+01:00"}'
info  2023-01-02 09:41:09: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010d629539","ieee_address":"0x001788010d629539"},"type":"device_announce"}'
info  2023-01-02 09:41:09: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001788010d629539"},"type":"device_announced"}'
info  2023-01-02 09:41:09: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"model":"unknown","networkAddress":2368,"type":"Router"},"last_seen":"2023-01-02T09:41:09+01:00","linkquality":61}'
info  2023-01-02 09:41:09: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"type":"Router"},"last_seen":"2023-01-02T09:41:09+01:00","linkquality":105}'
info  2023-01-02 09:41:09: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","type":"Router"},"last_seen":"2023-01-02T09:41:09+01:00","linkquality":105}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":98}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":102}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"friendlyName":"0x001788010d629539","ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","stackVersion":1,"type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":98}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"friendlyName":"0x001788010d629539","hardwareVersion":1,"ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","stackVersion":1,"type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":69}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"dateCode":"20220928","friendlyName":"0x001788010d629539","hardwareVersion":1,"ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","stackVersion":1,"type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":43}'
info  2023-01-02 09:41:10: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"dateCode":"20220928","friendlyName":"0x001788010d629539","hardwareVersion":1,"ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"unknown","networkAddress":2368,"powerSource":"Mains (single phase)","softwareBuildID":"1.101.1","stackVersion":1,"type":"Router","zclVersion":8},"last_seen":"2023-01-02T09:41:10+01:00","linkquality":58}'
info  2023-01-02 09:41:10: Successfully interviewed '0x001788010d629539', device has successfully been paired
info  2023-01-02 09:41:10: Device '0x001788010d629539' is supported, identified as: Philips Hue Festavia gradient light string 250 (929003535301)
info  2023-01-02 09:41:11: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Hue Festavia gradient light string 250","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":153},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500}],"property":"color_temp","type":"numeric","unit":"mired","value_max":500,"value_min":153},{"access":7,"description":"Color temperature after cold power on of this light","name":"color_temp_startup","presets":[{"description":"Coolest temperature supported","name":"coolest","value":153},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500},{"description":"Restore previous color_temp on cold power on","name":"previous","value":65535}],"property":"color_temp_startup","type":"numeric","unit":"mired","value_max":500,"value_min":153},{"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"},{"description":"Color of this light expressed as hue/saturation","features":[{"access":7,"name":"hue","property":"hue","type":"numeric"},{"access":7,"name":"saturation","property":"saturation","type":"numeric"}],"name":"color_hs","property":"color","type":"composite"}],"type":"light"},{"access":7,"description":"Controls the behavior when the device is powered on after power loss","name":"power_on_behavior","property":"power_on_behavior","type":"enum","values":["off","on","toggle","previous"]},{"access":2,"name":"gradient_scene","property":"gradient_scene","type":"enum","values":["blossom","crocus","precious","narcissa","beginnings","first_light","horizon","valley_dawn","sunflare","emerald_flutter","memento","resplendent","scarlet_dream","lovebirds","smitten","glitz_and_glam","promise","ruby_romance","city_of_love","honolulu","savanna_sunset","golden_pond","runy_glow","tropical_twilight","miami","cancun","rio","chinatown","ibiza","osaka","tokyo","motown","fairfax","galaxy","starlight","blood moon","artic_aurora","moonlight","nebula","sundown","blue_lagoon","palm_beach","lake_placid","mountain_breeze","lake_mist","ocean_dawn","frosty_dawn","sunday_morning","emerald_isle","spring_blossom","midsummer_sun","autumn_gold","spring_lake","winter_mountain","midwinter","amber_bloom","lily","painted_sky","winter_beauty","orange_fields","forest_adventure","blue_planet","soho","vapor_wave","magneto","tyrell","disturbia","hal","golden_star","under_the_tree","silent_night","rosy_sparkle","festive_fun","colour_burst","crystalline"]},{"access":7,"description":"List of RGB HEX colors","item_type":{"access":"Color in RGB HEX format (eg #663399)","name":"hex","type":"text"},"length_max":9,"length_min":1,"name":"gradient","property":"gradient","type":"list"},{"access":2,"name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","candle","fireplace","colorloop","sunrise","finish_effect","stop_effect","stop_hue_effect","sparkle"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"929003535301","options":[{"access":2,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).","name":"transition","property":"transition","type":"numeric","value_min":0},{"access":2,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).","name":"color_sync","property":"color_sync","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"Philips"},"friendly_name":"0x001788010d629539","ieee_address":"0x001788010d629539","status":"successful","supported":true},"type":"device_interview"}'
info  2023-01-02 09:41:11: Configuring '0x001788010d629539'
info  2023-01-02 09:41:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Hue Festavia gradient light string 250","friendly_name":"0x001788010d629539","model":"929003535301","supported":true,"vendor":"Philips"},"type":"pairing"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/light/0x001788010d629539/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x001788010d629539/set","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","candle","fireplace","colorloop","sunrise","finish_effect","stop_effect","stop_hue_effect","sparkle"],"json_attributes_topic":"zigbee2mqtt/0x001788010d629539","max_mireds":500,"min_mireds":153,"name":"0x001788010d629539","schema":"json","state_topic":"zigbee2mqtt/0x001788010d629539","supported_color_modes":["xy","color_temp"],"unique_id":"0x001788010d629539_light_zigbee2mqtt"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/sensor/0x001788010d629539/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 power on behavior","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/select/0x001788010d629539/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0x001788010d629539/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"entity_category":"config","icon":"mdi:power-settings","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/select/0x001788010d629539/gradient_scene/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0x001788010d629539/set/gradient_scene","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 gradient scene","options":["blossom","crocus","precious","narcissa","beginnings","first_light","horizon","valley_dawn","sunflare","emerald_flutter","memento","resplendent","scarlet_dream","lovebirds","smitten","glitz_and_glam","promise","ruby_romance","city_of_love","honolulu","savanna_sunset","golden_pond","runy_glow","tropical_twilight","miami","cancun","rio","chinatown","ibiza","osaka","tokyo","motown","fairfax","galaxy","starlight","blood moon","artic_aurora","moonlight","nebula","sundown","blue_lagoon","palm_beach","lake_placid","mountain_breeze","lake_mist","ocean_dawn","frosty_dawn","sunday_morning","emerald_isle","spring_blossom","midsummer_sun","autumn_gold","spring_lake","winter_mountain","midwinter","amber_bloom","lily","painted_sky","winter_beauty","orange_fields","forest_adventure","blue_planet","soho","vapor_wave","magneto","tyrell","disturbia","hal","golden_star","under_the_tree","silent_night","rosy_sparkle","festive_fun","colour_burst","crystalline"],"unique_id":"0x001788010d629539_gradient_scene_zigbee2mqtt"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/sensor/0x001788010d629539/gradient/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 gradient","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_gradient_zigbee2mqtt","value_template":"{{ value_json.gradient }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/select/0x001788010d629539/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0x001788010d629539/set/effect","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"enabled_by_default":false,"icon":"mdi:palette","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 effect","options":["blink","breathe","okay","channel_change","candle","fireplace","colorloop","sunrise","finish_effect","stop_effect","stop_hue_effect","sparkle"],"unique_id":"0x001788010d629539_effect_zigbee2mqtt"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/sensor/0x001788010d629539/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/sensor/0x001788010d629539/last_seen/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"device_class":"timestamp","enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:clock","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 last seen","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_last_seen_zigbee2mqtt","value_template":"{{ value_json.last_seen }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/sensor/0x001788010d629539/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 update state","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/binary_sensor/0x001788010d629539/update_available/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"device_class":"update","enabled_by_default":false,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539 update available","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_update_available_zigbee2mqtt","value_template":"{{ value_json['update']['state'] == \"available\" }}"}'
info  2023-01-02 09:41:11: MQTT publish: topic 'homeassistant/update/0x001788010d629539/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x001788010d629539/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0x001788010d629539"],"manufacturer":"Philips","model":"Hue Festavia gradient light string 250 (929003535301)","name":"0x001788010d629539","sw_version":"1.101.1"},"device_class":"firmware","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","json_attributes_topic":"zigbee2mqtt/0x001788010d629539","latest_version_template":"{{ value_json['update']['latest_version'] }}","latest_version_topic":"zigbee2mqtt/0x001788010d629539","name":"0x001788010d629539","payload_install":"{\"id\": \"0x001788010d629539\"}","state_topic":"zigbee2mqtt/0x001788010d629539","unique_id":"0x001788010d629539_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
error 2023-01-02 09:41:11: Failed to configure '0x001788010d629539', attempt 1 (TypeError: extendDontUse.light_onoff_brightness_colortemp_color(...).configure is not a function
    at Object.result.configure (/app/node_modules/zigbee-herdsman-converters/devices/philips.js:89:18)
    at Configure.configure (/app/lib/extension/configure.ts:117:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:81:62)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitDeviceInterview (/app/lib/eventBus.ts:74:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:86:27)
    at Controller.emit (node:events:513:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14)
    at Controller.onDeviceJoined (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:570:22))
....
error 2023-01-02 09:41:38: Failed to configure '0x001788010d629539', attempt 2 (TypeError: extendDontUse.light_onoff_brightness_colortemp_color(...).configure is not a function
    at Object.result.configure (/app/node_modules/zigbee-herdsman-converters/devices/philips.js:89:18)
    at Configure.configure (/app/lib/extension/configure.ts:117:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:82:62)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:52:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (node:events:513:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:727:18)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70))
info  2023-01-02 09:41:48: Configuring '0x001788010d629539'
info  2023-01-02 09:41:48: MQTT publish: topic 'zigbee2mqtt/0x001788010d629539', payload '{"device":{"applicationVersion":2,"dateCode":"20220928","friendlyName":"0x001788010d629539","hardwareVersion":1,"ieeeAddr":"0x001788010d629539","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"929003535301","networkAddress":2368,"powerSource":"Mains (single phase)","softwareBuildID":"1.101.1","stackVersion":1,"type":"Router","zclVersion":8},"gradient":null,"last_seen":"2023-01-02T09:41:48+01:00","linkquality":54,"power_on_behavior":null,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
error 2023-01-02 09:41:48: Failed to configure '0x001788010d629539', attempt 3 (TypeError: extendDontUse.light_onoff_brightness_colortemp_color(...).configure is not a function
    at Object.result.configure (/app/node_modules/zigbee-herdsman-converters/devices/philips.js:89:18)
    at Configure.configure (/app/lib/extension/configure.ts:117:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:82:62)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:52:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (node:events:513:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:730:18)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70))
.....
info  2023-01-02 09:45:41: Configuring '0x001788010d629539'
error 2023-01-02 09:45:41: Failed to configure '0x001788010d629539', attempt 4 (TypeError: extendDontUse.light_onoff_brightness_colortemp_color(...).configure is not a function
    at Object.result.configure (/app/node_modules/zigbee-herdsman-converters/devices/philips.js:89:18)
    at Configure.configure (/app/lib/extension/configure.ts:117:37)
    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:32)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:140:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:118:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20)
    at Receiver.emit (node:events:513:28))

**Comment by zegl** [comment]
@FredericGuardia Could you please try upgrading to the latest version (v1.29.0) and try again?

**Comment by FredericGuardia** [comment]
I am already on v1.29.0 version.

**Comment by zegl** [comment]
Sorry, I see that now. I think I know what the issue is, I'm working on a fix!
