### ISSUE TITLE
Device added to blocklist via Remove's prevent rejoin option does not appear in the settings Blocklist list

### ISSUE THREAD

**Issue by adamawolf** [Koenkk/zigbee2mqtt#15901]
### What happened?

I deleted a device and checked "Prevent from rejoining" (or whatever the wording was).

This worked, and I saw three consecutive attempts from that device to rejoin immediately with the message that "ID prevent from joining due to being on the blocklist" (paraphrased).

However, I don't see anywhere in the settings that I can someday remove this device from the blocklist. When I look in Settings->Blocklist the list is empty.

### What did you expect to happen?

I expect to see my device listed in the blocklist list, so that I can un-block it.

### How to reproduce it (minimal and precise)

Delete a paired Hue bulb. Select the "prevent from rejoining" option. Wait and see that the device does not rejoin (correctly).

Then navigate to settings -> Blocklist and observe the device is not listed there.

### Zigbee2MQTT version

 1.29.0 commit: unknown

### Adapter firmware version

20220219

### Adapter

Sonof 3.0

**Comment by dancwilliams** [comment]
@adamawolf Did you ever figure this out? Running into the same issue.
