### ISSUE TITLE
[Feature request]: Battery level for Zemismart roller shade motors (specifically ZM25SEL-08

### ISSUE THREAD

**Issue by statzern** [Koenkk/zigbee2mqtt#15931]
### Is your feature request related to a problem? Please describe

Lack of support for battery level is really important for devices that are going to be placed in difficult or even impossible to reach locations. These motors are amazing compared to very expensive options I have tried from other manufacturers, and this capability is definitely possible since it works with the stock Smart Life app as well as Hubitat. 

### Describe the solution you'd like

Battery level reporting - very important for hard to reach windows where removal and/or charging is not practical. 

### Describe alternatives you've considered

Using ZHA. Not available. It is however available in Hubitat, so apparently this feature is solvable. 

### Additional context

Links to working Hubitat implementation:
https://community.hubitat.com/t/release-zemismart-zigbee-blind-driver/67525/232
https://raw.githubusercontent.com/amosyuen/hubitat-zemismart-zigbee/development/Zemismart%20Zigbee%20Blind.groovy

Integrating the roller shade with the Tuya integration returns the following in logs: 
`2023-01-03 18:09:00.660 DEBUG (SyncWorker_0) [tuya_iot] Response: {
  "result": [
    {
      "active_time": 1669611065,
      "biz_type": 18,
      "category": "cl",
      "create_time": 1668647306,
      "icon": "smart/icon/ay1535532217868NsRD0/b9b292aa9513768e03818f275fb8be83.png",
      "id": "eb9a5c818253e7d1aegndh",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "",
      "name": "Bonus Room Shade",
      "node_id": "003c84fffefb3011",
      "online": false,
      "owner_id": "2482276",
      "product_id": "68nvbio9",
      "product_name": "",
      "status": [
        {
          "code": "control",
          "value": "stop"
        },
        {
          "code": "percent_control",
          "value": 0
        },
        {
          "code": "percent_state",
          "value": 30
        },
        {
          "code": "mode",
          "value": "morning"
        },
        {
          "code": "control_back_mode",
          "value": "forward"
        },
        {
          "code": "work_state",
          "value": "opening"
        },
        {
          "code": "situation_set",
          "value": "fully_open"
        },
        {
          "code": "fault",
          "value": 0
        },
        {
          "code": "battery_percentage",
          "value": 75
        },
        {
          "code": "border",
          "value": "up"
        },
        {
          "code": "position_best",
          "value": 0
        },
        {
          "code": "click_control",
          "value": "down"
        }
      ],
      "sub": true,
      "time_zone": "-06:00",
      "uid": "***",
      "update_time": 1669611065,
      "uuid": "003c84fffefb3011"
    },
`

Not sure if that is helpful or not. 

Thank you in advance for considering this issue

**Comment by iancoop** [comment]
Would love to see this implemented too.

Thanks,
