### ISSUE TITLE
Müller Licht bulb model 45328 is identified as model "404036/45327/45317"

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#15935]
### What happened?

I got some Müller Licht bulbs with the model number 45328, a E14 candle style bulb with RGB+WW. Zigbee2MQTT identifies this bulb with model "404036/45327/45317" - so it's missing in the list.

Docs: https://www.zigbee2mqtt.io/devices/404036_45327_45317.html

### What did you expect to happen?

It should be listed as one of the devices.

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB stick

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
