### ISSUE TITLE
[New device support]: Hiluz DZ8

### ISSUE THREAD

**Issue by ChristianHC** [Koenkk/zigbee2mqtt#15953]
### Link

https://detled.dk/led-spots/6951-hilux-dz8-zigbee-led-indb-spot-7w-i-ambiance-ra93-i-hvid-5714255004137.html

### Database entry

id":37,"type":"Router","ieeeAddr":"0x00124b0022ed3204","nwkAddr":39973,"manufId":0,"manufName":"Hilux Denmark","powerSource":"Mains (single phase)","modelId":"Hilux DZ8","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":544,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Hilux DZ8","manufacturerName":"Hilux Denmark","powerSource":1,"zclVersion":1,"appVersion":13,"stackVersion":2,"hwVersion":1,"dateCode":"20201216","swBuildId":"1.0.13"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":13,"stackVersion":2,"hwVersion":1,"dateCode":"20201216","swBuildId":"1.0.13","zclVersion":1,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1672869477915,"defaultSendRequestWhen":"immediate"} {"id":38,"type":"Router","ieeeAddr":"0x00124b0022ed4c12","nwkAddr":10002,"manufId":0,"manufName":"Hilux Denmark","powerSource":"Mains (single phase)","modelId":"Hilux DZ8","epList":[1,13],"endpoints":{"1":{"profId":49246,"epId":1,"devId":544,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Hilux DZ8","manufacturerName":"Hilux Denmark","powerSource":1,"zclVersion":1,"appVersion":13,"stackVersion":2,"hwVersion":1,"dateCode":"20201216","swBuildId":"1.0.13"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":49246,"epId":13,"devId":57694,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":13,"stackVersion":2,"hwVersion":1,"dateCode":"20201216","swBuildId":"1.0.13","zclVersion":1,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1672868878148,"defaultSendRequestWhen":"immediate"}

### Comments

color_temp_startup and power_on_behavior is not support on this light "UNSUPPORTED_ATTRIBUTE" is thrown

on_off, brightness and color_temp works fine

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	zigbeeModel: ['Hilux DZ8'],
	model: 'DZ8',
	vendor: 'Hilux',
	description: 'Hilux DZ8',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

{colorTempRange: [153, 370]}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
