### ISSUE TITLE
Sinopé SP2600ZB not reporting  consumed energy - Null value

### ISSUE THREAD

**Issue by maxperron** [Koenkk/zigbee2mqtt#15950]
### What happened?

Hello, I just bought 2 [Sinopé SP2600ZB](https://www.zigbee2mqtt.io/devices/SP2600ZB.html) switches. I added them to my network and the exposed energy attributes is always null kWh (I waited 48 hours).

![image](https://user-images.githubusercontent.com/4964696/210638789-72ed095a-e3dd-4c56-8915-3b13aabe50d8.png)

Switch details:
![image](https://user-images.githubusercontent.com/4964696/210640158-4f606d69-b06a-4dc9-aa70-04b7e05869db.png)

### What did you expect to happen?

As per the documentation, I should see a value for the sum of consumed energy.

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0

### Debug log

MQTT publish: topic 'zigbee2mqtt/BUR Server Switch Switch Sinope', payload '{"ac_frequency":60,"current":0.19,"energy":null,"linkquality":116,"power":13,"state":"ON","voltage":116.62}'

**Comment by maxperron** [comment]
I'm now on 1.29.1 version and still have the issue.

**Comment by maxperron** [comment]
In the meantime I created a custom sensor that calculate the energy based on the current watt.

**Comment by Koenkk** [comment]
@mattL0 could you check this?

**Comment by maxperron** [comment]
Thanks, it's working!
