### ISSUE TITLE
Xiaomi Aqara sensors not responding to 'get' command

### ISSUE THREAD

**Issue by tenspot** [Koenkk/zigbee2mqtt#1596]
# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by tenspot** [comment]
Hi,
I have recently installed a zigbee2mqtt setup and have it working with three devices:
Xiaomi Aqara temperature, humidity and pressure sensor (temperature, humidity and pressure). Model: WSDCGQ11LM
Xiaomi Aqara door & window contact sensor.  Model: MCCGQ11LM
Ikea TRADFRI control outlet. Model: E1603

However, when I try and read the status of either of the Aqara sensors using the 'get' command in MQTT Explorer, I get no response. When I send a 'get' command to the Ikea outlet, I get the device status back.
The commands I have tried are:
    for the door & window contact:
    zigbee2mqtt/deviceID/get/status   payload: empty
    zigbee2mqtt/deviceID/get   payload: {"status": ""}

   temperature, humidity and pressure sensor:
    zigbee2mqtt/deviceID/get/temperature   payload: empty
    zigbee2mqtt/deviceID/get   payload: {"temperature": ""}

**Comment by CypherMK** [comment]
I guess it's because these xiaomi sensors are battery powered and only report their status on their own.

**Comment by Koenkk** [comment]
@CypherMK is right, the device is probably sleeping when you do the request.

**Comment by tenspot** [comment]
Ah yes, never thought of that. I'm new to low power battery tech. 
Many thanks for pointing this out.
