### ISSUE TITLE
OTA Update available (and not) at the same time.

### ISSUE THREAD

**Issue by trackhacs** [Koenkk/zigbee2mqtt#15969]
### What happened?

I paired   IKEA E1744. 

Afterwards HASS showed me that an update is available.

![image](https://user-images.githubusercontent.com/121126824/210853145-9e6a4f45-0002-4fe1-bc20-3d5f9625a7fe.png)

Going afterwards to Z2MQtt   via UI and checking for update gives: "no update available". 

![image](https://user-images.githubusercontent.com/121126824/210853655-c324b8e2-e6de-4254-a939-8ed540e9e68f.png)

The state.json:

![image](https://user-images.githubusercontent.com/121126824/210853889-d779c5e3-86d5-4baf-882c-4d5815966ba9.png)

### What did you expect to happen?

a)  same feedback from HASS and Z2M about available firmware update.

b) same coding/naming of available updates in human readable notion.

### How to reproduce it (minimal and precise)

pair  E1744

wait for HASS showing update availabel 

test via Z2M  for an update 

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

0x26720700

### Adapter

Conbee2

### Debug log

```
Debug 2023-01-05 19:35:27Received Zigbee message from '0x60a423fffef48f79', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553797169,"imageType":4554,"manufacturerCode":4476}' from endpoint 1 with groupID null
Info 2023-01-05 19:35:27MQTT publish: topic 'zigbee2mqtt/0x60a423fffef48f79', payload '{"action":null,"battery":60,"last_seen":"2023-01-05T18:35:27.602Z","linkquality":255,"update":{"installed_version":553797169,"latest_version":587728433,"state":"idle"},"update_available":null}'
Debug 2023-01-05 19:35:27Device '0x60a423fffef48f79' requested OTA
Debug 2023-01-05 19:35:30Received Zigbee message from '0x60a423fffef48f79', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553797169,"imageType":4554,"manufacturerCode":4476}' from endpoint 1 with groupID null
Info 2023-01-05 19:35:30MQTT publish: topic 'zigbee2mqtt/0x60a423fffef48f79', payload '{"action":null,"battery":60,"last_seen":"2023-01-05T18:35:30.711Z","linkquality":255,"update":{"installed_version":553797169,"latest_version":587728433,"state":"idle"},"update_available":null}'
Debug 2023-01-05 19:35:30Device '0x60a423fffef48f79' requested OTA
Debug 2023-01-05 19:35:34Received Zigbee message from '0x60a423fffef48f79', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553797169,"imageType":4554,"manufacturerCode":4476}' from endpoint 1 with groupID null
Info 2023-01-05 19:35:34MQTT publish: topic 'zigbee2mqtt/0x60a423fffef48f79', payload '{"action":null,"battery":60,"last_seen":"2023-01-05T18:35:33.809Z","linkquality":255,"update":{"installed_version":553797169,"latest_version":587728433,"state":"idle"},"update_available":null}'
Debug 2023-01-05 19:35:34Device '0x60a423fffef48f79' requested OTA
```

**Comment by jakemauer** [comment]
Wow we posted the same issue like a minute a part lol.

**Comment by trackhacs** [comment]
;)

yes you right. now I can trigger it via HASS too. Tried before and didnt start.

**Comment by stigvi** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/15877#issue-1516178147

**Comment by Koenkk** [comment]
Will be fixed on todays hotfix release.
