### ISSUE TITLE
CC2531 physical buttons

### ISSUE THREAD

**Issue by mclaudiopt** [Koenkk/zigbee2mqtt#1597]
Hello
what is the function of the 2 physical buttons present on the cc2531 stick?
thanks

**Comment by Koenkk** [comment]
![image](https://user-images.githubusercontent.com/2892853/59134395-4bf76d00-897b-11e9-95e5-af30b99a3ab1.png)

- S2 is reset button
- S1 I'm not sure about, @ptvoinfo do you know where it is used for by default?

**Comment by ptvoinfo** [comment]
The coordinator firmware does not use S1. 

My router  firmware uses these buttons:

S1 – Changes a virtual state of the router (the router sends it in a diagnostic report) and the state of the green light.

S2:
    Short single press – to re-send a binding request to a coordinator (it allows you to test a connection).
    Long single press (about 5 seconds) – to reset the router and initiate a joining process.

**Comment by Koenkk** [comment]
Closing this one as the question is answered.
