### ISSUE TITLE
Can't pair to Schneider Wiser

### ISSUE THREAD

**Issue by Sim7b** [Koenkk/zigbee2mqtt#15982]
### What happened?

Going from ZHA (Home assistant) to Zigbee2MQTT, schneider wiser modules was connected to ZHA with Conbee 2.
Can't pair to Zigbee2MQTT after migration.

**Schneider Wiser :**
- Cover Module S520567W
- Dimmer Module (Push type) S520522W

### What did you expect to happen?

Do you know if there is something wrong with the default configuration and Wiser module ?
Logs returns nothing...

### How to reproduce it (minimal and precise)

Pushing 3 times UP on module within 5 seconds, green led blinking, nothing on debug logs. Worked before with ZHA.

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

0x26780700

### Adapter

deconz

**Comment by devildant** [comment]
Hi its work now for the S520522W? I don't see any ref on zigbee2mqtt
