### ISSUE TITLE
 How to remove device from network?

### ISSUE THREAD

**Issue by tutis51** [Koenkk/zigbee2mqtt#160]
What is the proper way of removing device form network/database/configuration.yaml

thank you.

**Comment by Koenkk** [comment]
https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttbridgeconfigremove

**Comment by tutis51** [comment]
Thank you! Was reading wiki several times, but some how missed this...

Successfully removed devices!

**Comment by enishoca** [comment]
@Koenkk Looks like the wiki is gone - and I don't see this in the documentation.  How do you remove/unpair a device?
