### ISSUE TITLE
[New device support]: lumi.remote.cagl02 - Cube T1 Pro

### ISSUE THREAD

**Issue by hyperfive** [Koenkk/zigbee2mqtt#16006]
### Link

https://www.aqara.com/en/product/cube-t1-pro

### Database entry

Unknown

### Comments

Hello,

I am fairly certain the integration of this device will be very similar if not identical to the original version - https://www.aqara.com/us/cube.html

**Comment by kariudo** [comment]
This is a duplicate of #15652
