### ISSUE TITLE
TS011F _TZ3000_okaz9tjs not fully working

### ISSUE THREAD

**Issue by havlejan** [Koenkk/zigbee2mqtt#16016]
### What happened?

I have two devices Girier Plug 16A.
One device is TS011F_TZ3000_r6buo8ba with sw_version "20B+TZSKT41BS103". It was successfully connected as TS011F_plug_3 and is fully functional.
Second device is TS011F _TZ3000_okaz9tjs with sw_version":"20B+TZSKT11BS108". It was successfully connected as TS011F_plug_1 and is not fully functional:

Exposes "state", "powe_outage_memory", "indicator_mode" and "child_lock" is workinkg
Power Monitoring is not functional (power, current, voltage, energy) no data recieved

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

### Debug log

info  2023-01-07 19:26:51: Configuring 'Girier Plug 2'
debug 2023-01-07 19:26:51: Received Zigbee message from 'Girier Plug 2', type 'readResponse', cluster 'genBasic', data '{"appVersion":100,"manufacturerName":"_TZ3000_okaz9tjs","modelId":"TS011F","powerSource":1,"zclVersion":2}' from endpoint 1 with groupID 0
debug 2023-01-07 19:26:51: TuYa configureMagicPacket failed, ignoring...
error 2023-01-07 19:26:51: Failed to configure 'Girier Plug 2', attempt 2 (Error: ConfigureReporting 0x70b3d52b6001ba9a/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:694:22)
    at Object.rmsVoltage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:211:9)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/tuya.js:2496:13)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:117:13))

**Comment by WilkoKetelaar** [comment]
I seem to have the same problem, plug with software version 20B+TZSKT11BS107 seems to be functioning correct, and plug with software version 20B+TZSKT11BS108 is not working fully?

**Comment by Dobarekk** [comment]
+1

**Comment by xicoamaral** [comment]
Using zigbee2mqtt edge and still no values on the power. Repaired and still null W, null A, null V and null kWh.
Detected as TS011F_plug_3, firmware version 20B+TZSKT11BS108 and firmware build date 20210625.

**Comment by havlejan** [comment]
I tried to switch to dev branch. Same result as xicoamaral, still power is Null W, currect is Null A, voltage is Null V and energy is Null kWh.
Detected as TS011F_Plug_1, firmware version 20B+TZSKT11BS108, firmware build date 20210625.

**Comment by geronimo76** [comment]
I had the same issue, after updating to 1.30.1 it was resolved.
Both _TZ3000_r6buo8ba and _TZ3000_okaz9tjs are now connected as TS011F_plug_3 and are fully functional.

**Comment by havlejan** [comment]
> I had the same issue, after updating to 1.30.1 it was resolved.
> Both _TZ3000_r6buo8ba and _TZ3000_okaz9tjs are now connected as TS011F_plug_3 and are fully functional.

Thank you for your info. After updating my Z2M to 1.30.1 all my TS011F _TZ3000_okaz9tjs devices are connected as TS011F_plug_3 and are also fully functional.
