### ISSUE TITLE
[New device support]: Schneider Electric Wiser Smoke Alarm

### ISSUE THREAD

**Issue by dennisgranasen** [Koenkk/zigbee2mqtt#16012]
### Link

https://www.se.com/ww/en/product/CCT599001/smoke-alarm-wiser-battery-10-years-lifetime-white-ip20/

### Database entry

{"id":44,"type":"EndDevice","ieeeAddr":"0x2c1165fffeebb32d","nwkAddr":2064,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Battery","modelId":"W599001","epList":[20],"endpoints":{"20":{"profId":260,"epId":20,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821,64516],"outClusterList":[3,25],"clusters":{"64516":{"attributes":{"0":0,"3":0}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00212effff040c21","zoneState":1,"zoneId":23}},"genPollCtrl":{"attributes":{"checkinInterval":14400}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00212effff040c21","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00212effff040c21","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff040c21","endpointID":1},{"cluster":1280,"type":"endpoint","deviceIeeeAddress":"0x00212effff040c21","endpointID":1},{"cluster":2821,"type":"endpoint","deviceIeeeAddress":"0x00212effff040c21","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1026,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100}],"meta":{}}},"appVersion":1,"stackVersion":6,"hwVersion":1,"dateCode":"20211120","swBuildId":"2111201","zclVersion":8,"interviewCompleted":true,"meta":{"configured":-918967226},"lastSeen":1673107089376,"defaultSendRequestWhen":"active"}

### Comments

I tried to add the device with a custom converter as per the guide, tried a few different options but I'm not getting any readings into z2m. Not really sure what to expect so I tried to log incoming ssIasZone messages, but reading attempts from the dev console render nothing. I am also not getting any battery or temperature updates, so I realize that there is something major I'm missing.

There's also an unidentified cluster 0xFC04 that I do not know anything about. Is there an easy way to figure out what's inside it?

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;
const ea = exposes.access;

const ias_smoke_alarm_schneider = {
    cluster: 'ssIasZone',
    type: 'commandStatusChangeNotification',
    convert: (model, msg, publish, options, meta) => {
        meta.logger.debug(`from schneider, msg=[${msg}]`);
        const zoneStatus = msg.data.zonestatus;
        return {
            smoke: (zoneStatus & 1) > 0,
            tamper: (zoneStatus & 1<<2) > 0,
            battery_low: (zoneStatus & 1<<3) > 0,
            supervision_reports: (zoneStatus & 1<<4) > 0,
            restore_reports: (zoneStatus & 1<<5) > 0,
            trouble: (zoneStatus & 1<<6) > 0,
            ac_status: (zoneStatus & 1<<7) > 0,
            test: (zoneStatus & 1<<8) > 0,
        };
    },
};

const definition = {
        zigbeeModel: ['W599001'],
        model: 'W599001',
        vendor: 'Schneider Electric',
        description: 'Wiser smoke alarm CCT599001',
        fromZigbee: [ias_smoke_alarm_schneider],
        toZigbee: [tz.warning, tz.ias_max_duration, tz.warning_simple],
        ota: ota.zigbeeOTA,
        exposes: [
            e.smoke(), 
            e.battery_low(),
            e.tamper(), 
            e.warning(),
            e.battery(), 
            e.battery_voltage(),
            e.temperature()
        ],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(20);
            const binds = ['msTemperatureMeasurement', 'genPowerCfg'];
            await reporting.bind(endpoint, coordinatorEndpoint, binds);
            await reporting.batteryPercentageRemaining(endpoint);
            await reporting.batteryVoltage(endpoint);
            await reporting.temperature(endpoint);
            await endpoint.read('ssIasZone', ['iasCieAddr', 'zoneState', 'zoneId']);
            await endpoint.read('genPowerCfg', ['batteryVoltage', 'batteryPercentageRemaining']);
        },
};

module.exports = definition;
```

**Comment by mandrean** [comment]
Duplicate: https://github.com/Koenkk/zigbee2mqtt/issues/15660
