### ISSUE TITLE
TS110E_2gang stopped reacting to "state": "toggle"

### ISSUE THREAD

**Issue by ikarisan** [Koenkk/zigbee2mqtt#16011]
### What happened?

I am using a "TS110E_2gang" dimmer (_TZ3210_3mpwqzuu) and sudenly it stopped reacting to the {"state": "toggle"} command. 
In the response the states changes from

{
"state": "OFF",
"state_l1": "OFF",
"state_l2": "OFF",
}

to 

{
"state": "OFF",
"state_l1": "ON",
"state_l2": "OFF",
}

but nothing happens. 
When requesting the current state (zigbee2mqtt/Dimmer1/get) the state is still OFF. But the zigbee2mqtt GUI shows "ON".
If I use "state": "on" and "state": "off" instead the lights turn on and off. 

### What did you expect to happen?

I expected that the state of the light changes as it does when sending {"state": "on"/"off"}

### How to reproduce it (minimal and precise)

Pair a TuYa TS110E_2gang and send

{
  "state_l1": "toggle"
}

to zigbee2mqtt/friendlyname/set

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

20201010

### Adapter

CC2538+CC2592, zStack30x

### Debug log

This is the corresponding debug log:

```
debug 2023-01-07 18:39:21: Received Zigbee message from 'TuYa_Vierfach_Schalter', type 'raw', cluster 'genOnOff', data '{"data":[1,54,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
info  2023-01-07 18:39:21: MQTT publish: topic 'zigbee2mqtt/TuYa_Vierfach_Schalter', payload '{"action":"4_single","battery":100,"device":{"applicationVersion":65,"dateCode":"","friendlyName":"TuYa_Vierfach_Schalter","hardwareVersion":1,"ieeeAddr":"0x84fd27fffe8d3e0c","manufacturerID":4098,"manufacturerName":"_TZ3000_xabckq1v","model":"TS004F","networkAddress":53107,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"last_seen":"2023-01-07T18:39:21+01:00","linkquality":68,"voltage":3000}'
debug 2023-01-07 18:39:21: Received MQTT message on 'zigbee2mqtt/Dimmer1/set' with data '{"state_l1":"TOGGLE"}'
debug 2023-01-07 18:39:21: Publishing 'set' 'state' to 'Dimmer1'
info  2023-01-07 18:39:21: MQTT publish: topic 'zigbee2mqtt/Dimmer1', payload '{"brightness":254,"brightness_l1":254,"brightness_l2":255,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Dimmer1","hardwareVersion":1,"ieeeAddr":"0xa4c13801e3dcd9b5","manufacturerID":4417,"manufacturerName":"_TZ3210_3mpwqzuu","model":"TS110E_2gang","networkAddress":37924,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2023-01-07T18:39:21+01:00","linkquality":26,"max_brightness":255,"max_brightness_l1":255,"max_brightness_l2":255,"min_brightness":1,"min_brightness_l1":1,"min_brightness_l2":1,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"off","power_outage_memory_l1":"restore","power_outage_memory_l2":"restore","state":"OFF","state_l1":"OFF","state_l2":"OFF","switch_type":"toggle","switch_type_l1":"momentary","switch_type_l2":"momentary"}'
info  2023-01-07 18:39:21: MQTT publish: topic 'zigbee2mqtt/Dimmer1', payload '{"brightness":254,"brightness_l1":254,"brightness_l2":255,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Dimmer1","hardwareVersion":1,"ieeeAddr":"0xa4c13801e3dcd9b5","manufacturerID":4417,"manufacturerName":"_TZ3210_3mpwqzuu","model":"TS110E_2gang","networkAddress":37924,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2023-01-07T18:39:21+01:00","linkquality":26,"max_brightness":255,"max_brightness_l1":255,"max_brightness_l2":255,"min_brightness":1,"min_brightness_l1":1,"min_brightness_l2":1,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"off","power_outage_memory_l1":"restore","power_outage_memory_l2":"restore","state":"OFF","state_l1":"ON","state_l2":"OFF","switch_type":"toggle","switch_type_l1":"momentary","switch_type_l2":"momentary"}'
debug 2023-01-07 18:39:22: Received Zigbee message from 'TuYa_Vierfach_Schalter', type 'raw', cluster 'genOnOff', data '{"data":[1,54,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
info  2023-01-07 18:39:22: MQTT publish: topic 'zigbee2mqtt/TuYa_Vierfach_Schalter', payload '{"battery":100,"device":{"applicationVersion":65,"dateCode":"","friendlyName":"TuYa_Vierfach_Schalter","hardwareVersion":1,"ieeeAddr":"0x84fd27fffe8d3e0c","manufacturerID":4098,"manufacturerName":"_TZ3000_xabckq1v","model":"TS004F","networkAddress":53107,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"last_seen":"2023-01-07T18:39:22+01:00","linkquality":68,"voltage":3000}'
debug 2023-01-07 18:39:23: Received Zigbee message from 'TuYa_Vierfach_Schalter', type 'raw', cluster 'genOnOff', data '{"data":[1,54,253,0],"type":"Buffer"}' from endpoint 4 with groupID 0
info  2023-01-07 18:39:23: MQTT publish: topic 'zigbee2mqtt/TuYa_Vierfach_Schalter', payload '{"battery":100,"device":{"applicationVersion":65,"dateCode":"","friendlyName":"TuYa_Vierfach_Schalter","hardwareVersion":1,"ieeeAddr":"0x84fd27fffe8d3e0c","manufacturerID":4098,"manufacturerName":"_TZ3000_xabckq1v","model":"TS004F","networkAddress":53107,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"last_seen":"2023-01-07T18:39:23+01:00","linkquality":68,"voltage":3000}'
debug 2023-01-07 18:39:42: Received Zigbee message from 'Dimmer1', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":64}' from endpoint 1 with groupID 0
info  2023-01-07 18:39:42: MQTT publish: topic 'zigbee2mqtt/Dimmer1', payload '{"brightness":254,"brightness_l1":254,"brightness_l2":255,"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Dimmer1","hardwareVersion":1,"ieeeAddr":"0xa4c13801e3dcd9b5","manufacturerID":4417,"manufacturerName":"_TZ3210_3mpwqzuu","model":"TS110E_2gang","networkAddress":37924,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2023-01-07T18:39:42+01:00","linkquality":26,"max_brightness":255,"max_brightness_l1":255,"max_brightness_l2":255,"min_brightness":1,"min_brightness_l1":1,"min_brightness_l2":1,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"off","power_outage_memory_l1":"restore","power_outage_memory_l2":"restore","state":"OFF","state_l1":"ON","state_l2":"OFF","switch_type":"toggle","switch_type_l1":"momentary","switch_type_l2":"momentary"}'
```

**Comment by ikarisan** [comment]
Extract of my database.db file

[device.json.txt](https://github.com/Koenkk/zigbee2mqtt/files/10368708/device.json.txt)

**Comment by ikarisan** [comment]
I think I found the reason for not reacting to the toggle copmmand.
zigbee2mqtt sends an unknown on/off command to the device.

When switching the light on via {"status": "on"} or {"state": "off"} it is translated to

Cluster: On/Off (0x0006)
Profile: Home Automation (0x0104)
[..]
Command: On (0x01)

or

Cluster: On/Off (0x0006)
Profile: Home Automation (0x0104)
[..]
Command: On (0x00)

But if I use "toggle" the folowing is send to the dimmer two times

Source Endpoint: 4
Destination Endpoint: 1
Cluster: On/Off (0x0006)
Profile: Home Automation (0x0104)
Counter: 187
[..]
Sequence Number: 80
Command: Unknown (0xfd)

Followed by:

Source Endpoint: 1
Destination Endpoint: 1
Cluster: On/Off (0x0006)
Profile: Home Automation (0x0104)
Counter: 220
[..]
Sequence Number: 177
Command: Toggle (0x02)

Followed by (again, 4 times):

Source Endpoint: 4
Destination Endpoint: 1
Cluster: On/Off (0x0006)
Profile: Home Automation (0x0104)
Counter: 188
[..]
Sequence Number: 80
Command: Unknown (0xfd)

**Comment by ikarisan** [comment]
On request, I can provide a pcapng file.

**Comment by ikarisan** [comment]
After sending

{"switch_type": "toggle"}
{"switch_type_l1": "toggle"}
{"switch_type_l2": "toggle"}
{"state": "off"}
{"state_l1": "off"}
{"state_l2": "off"}
{"state": "on", brightness: 254}
{"state_l1": "on", brightness: 254}
{"state_l2": "on", brightness: 254}

the 

{"switch_type_l1": "toggle"}

command works again.

**Comment by ikarisan** [comment]
No, sorry. It only switches off the light.
Now, with every {"state": "toggle"} the dimmer turns on and off. But with every togle the "brightness" status is decreased by 1.
254...253...252...251...

**Comment by joggs** [comment]
I also have problems with this device.
I cannot change states .

Zigbee Model: TS110E
Zigbee Manufacturer: _TZ3210_wdexaypg

Error: Publish 'set' 'state' to 'Hemmabio ' failed: 'Error: Command 0xa4c13840794a9452/1 genLevelCtrl.moveToLevelWithOnOff({"level":129,"transtime":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 36645 - 1 - 167 - 8 - 11 after 10000ms)'

**Comment by ikarisan** [comment]
For the moment I use a work around, implemented in a Node2Red flow. With every received message from the device I save the current state to a persistance file. Then at every "toggle" command from a button I read the state from file and generate the needed ON/OFF message for the dimmer. But I don't like this and the causative bug should be fixed.
