### ISSUE TITLE
[New device support]: Ledvance SMART+ FILAMENT GLOBE DIMMABLE G120 6W E27 - EAN 4058075528215 

### ISSUE THREAD

**Issue by TPlamen** [Koenkk/zigbee2mqtt#16034]
### Link

https://www.ledvance.com/consumer/products/smart-home/smart-lamps/smart-zigbee/smart-classic-filament-lamps-with-zigbee-technology/classic-globe-shape-with-filament-style-with-zigbee-technology-c141280

### Database entry

{"id":13,"type":"Router","ieeeAddr":"0xf0d1b8000019e0f8","nwkAddr":54048,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"LEDVANCE DIM","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LEDVANCE DIM","manufacturerName":"LEDVANCE","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"00203045"}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"00203045","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1673202004464,"defaultSendRequestWhen":"immediate"}

### Comments

Misrecognized Ledvance SMART+ FILAMENT GLOBE DIMMABLE - EAN 4058075528215. Zigbee2mqtt 1.29.1 recognizes as https://www.zigbee2mqtt.io/devices/4058075208421.html#ledvance-4058075208421 and offers incorrect new firmware for the device. From the functions
"effect" and "power_on_behavior" do not work. Other functions work properly.

### Supported color modes

only 2400K

**Comment by tetzlav** [comment]
same problem with my [SMART+ Filament Edison 52 E27 Amber dimmable](https://www.zigbee2mqtt.io/devices/4058075729223.html) which is detected as [SMART+ candle E14 dimmable white](https://www.zigbee2mqtt.io/devices/4058075208421.html)...
