### ISSUE TITLE
Sniffer firmware for CC2531 flash frozen (Alternative flashing methods)

### ISSUE THREAD

**Issue by antiogenesneto** [Koenkk/zigbee2mqtt#1603]
Hi,

I tried to flash my sniffer zigbee cc2531 using a raspberry pi 3b and the procedure was frozen in step "writing page 1/128".

![WhatsApp Image 2019-06-06 at 08 31 25](https://user-images.githubusercontent.com/51444620/59030741-30377e00-8838-11e9-8c16-fbd9444e6c28.jpeg)
![WhatsApp Image 2019-06-06 at 08 31 26](https://user-images.githubusercontent.com/51444620/59030756-3af21300-8838-11e9-812c-42e9dc9fd606.jpeg)

**Comment by rickkdotnet** [comment]
7fff looks like it can't read the flash. I'd doublecheck the wiring.

**Comment by simfun** [comment]
It must be a power issue. I had this error too and after i connected a 2A power supply on RPI Zero it flashed the stick steadily.
