### ISSUE TITLE
[Feature request]: Latest SDK 6.x

### ISSUE THREAD

**Issue by gui28347** [Koenkk/zigbee2mqtt#16040]
### Is your feature request related to a problem? Please describe

Do you plan to support and create a firmware.patch for latest sdk sdk_6_40_00_13?

### Describe the solution you'd like

Have the most up-to-date firmware

### Describe alternatives you've considered

using current firmware.

### Additional context

How often new updates from TI are released? 1 per year?

**Comment by jerrm** [comment]
https://github.com/Koenkk/Z-Stack-firmware/issues/383

https://github.com/Koenkk/Z-Stack-firmware/tree/develop
