### ISSUE TITLE
Several different errors about "502 Bad Gateway"

### ISSUE THREAD

**Issue by Shwanapacka** [Koenkk/zigbee2mqtt#16047]
### What happened?

Almost a month I can't set up Zigbee Dongle-P stick on my machine with Home Assistant.
Tried to resolve the issue in the Home Assistant community: https://community.home-assistant.io/t/zigbee2mqtt-502-bad-gateway-several-different-errors/507618

First setup procedure:
- Installed MQTT broker
- Plugged in controller (Sonoff Zigbee Dongle-P)
- Installed Zigbee2MQTT add-on through the additional repository in the store
- Added mqtt user
- Updated Z2M config
- Got error 502
- Flashed the adapter according to the instructions (https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) (CC2652P)
- Tried different USB-ports (with ext.cable and without)
- Changed various settings in Z2M config (after each change restarted the addon)
- Periodically restarted the whole system
- Studied the page: Zigbee2MQTT fails to start (command result `test -w /dev/ttyUSB0 && echo success || echo failure` gives `success`)
- After a prompt on HA community, began to use the address of the machine in the configuration

![z2mqtt](https://user-images.githubusercontent.com/116746749/211278942-6db9ecf3-2726-4606-87cd-1db38a0f542a.png)
or
![z2mqtt1](https://user-images.githubusercontent.com/116746749/211279137-8c5816f6-0eec-47ca-947d-989486d08c41.png)

### What did you expect to happen?

Launching the plugin "Zigbee2MQTT", stick work.

### How to reproduce it (minimal and precise)

Configuration:
ProxMox Virtual Environment 7.2-11
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest
Mosquitto broker: 6.1.3
Z2MQTT: 1.29.1-1

I don’t have a ZHA. Zigbee2MQTT - first integration of this type.

### Zigbee2MQTT version

1.29.1-1

### Adapter firmware version

frontend not available

### Adapter

Sonoff Zigbee Dongle-P

### Debug log

![z2mqtt_jo2](https://user-images.githubusercontent.com/116746749/211280340-73127193-16ea-4841-ab6f-5e6f3aa509b4.png)
![z2mqtt_jo3](https://user-images.githubusercontent.com/116746749/211280360-d810a63a-a209-4020-b2ea-75aec98bbed7.png)
![z2mqtt_jo](https://user-images.githubusercontent.com/116746749/211280372-50a8ead9-317c-477b-a9e7-c0f15c1ba977.png)

**Comment by cloudbr34k84** [comment]
You are getting the same error as me - Zigbee2MQTT:error 09-01-2023 19:17:57: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

I think this is because i pressed the reset button on my Sonoff Coordinator instead of the Boot Loader button

https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#texas-instruments-launchxl-cc1352p-2-cc26x2r1-only-press-the-reset-button-on-the-device

**Comment by Shwanapacka** [comment]
I have now pressed RST button after connecting the adapter - nothing has changed.
Also tried to press BOOT - nothing has changed :(

**Comment by cloudbr34k84** [comment]
yeah i have ordered a new coordinator, i dont think this can be fixed

**Comment by Shwanapacka** [comment]
I solved the problem by purchasing another adapter. Dongle-E instead of Dongle-P.
And replace “ezsp” instead of “zstack” in “adapter” config respectively.
Everything worked :)

Thanks to those who responded to the issue.
