### ISSUE TITLE
INFO: Ikea E1702

### ISSUE THREAD

**Issue by raqua** [Koenkk/zigbee2mqtt#1605]
Hi, 

not sure where to contact you, so I am writing here. I have just bought Ikea Tradfri E1702 smart socket (+ switch E1743) and want to report that it works fine although being recognized as E1603 - IKEA TRADFRI control outlet (Router). 
Maybe you would want to add it so supported devices list. 
Thanks for the excellent SW.

Regards, 
Martin

**Comment by Koenkk** [comment]
AFAIK the only difference between these models is the outlet. As the internal zigbee model is identical, we cannot distinguish between E1603 and E1702. 

The next version of zigbee2mqtt will show `E1603/E1702` instead of just `E1603`, thanks!
