### ISSUE TITLE
[New device support]: Philips Hue Perifo base set (3 pendants)

### ISSUE THREAD

**Issue by Harry-1976** [Koenkk/zigbee2mqtt#16079]
### Link

https://www.philips-hue.com/nl-nl/p/hue-white-and-color-ambiance-perifo-rechte-basisplafondset--3-hanglampen-/8719514407725

### Database entry

{"id":72,"type":"Router","ieeeAddr":"0x001788010d1aa2b9","nwkAddr":27670,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003115901","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003115901","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1673306296408,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to follow the instructions on the support new device page but i failed to understand how to use the converter file.

### Supported color modes

White and color ambiance

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by zegl** [comment]
Thanks, I've opened a PR with converters for the Hue Perfio series. :-)
