### ISSUE TITLE
[New device support]: Add support for Phillips Hue LTA006

### ISSUE THREAD

**Issue by jamesgreeley** [Koenkk/zigbee2mqtt#16082]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-ambiance-filament-a60-–-b22-smart-bulb/8719514301443

### Database entry

{"id":22,"type":"Router","ieeeAddr":"0x001788010bf6ebec","nwkAddr":34689,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LTA006","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LTA006","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20201126","swBuildId":"1.78.1"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20201126","swBuildId":"1.78.1","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1673366859825,"defaultSendRequestWhen":"immediate"}

### Comments

LTA006 Appears to be identical to LTA005 but with B22 instead of E27 fixture
https://www.zigbee2mqtt.io/devices/8718699688882.html
https://zigbee.blakadder.com/Philips_LTA005.html

I cannot see it in the Dev branch
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/philips.js
or a existing request in this repo.

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin”:222,” colorTempPhysicalMax":454}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
