### ISSUE TITLE
Temperature step and max value

### ISSUE THREAD

**Issue by ZTHawk** [Koenkk/zigbee2mqtt#16091]
### What happened?

1. I cannot set the Max Temperature (it is always NULL).
2. The temperature can only be set in steps of 1 degree. But the device supports steps of 0.5 degrees.
3. I cannot set the deadzone temperature (it is always NULL).

I get this error (popup message that disappears after ~3 seconds) when trying to set the max/deadzone temperature:
`Failed to call service number/set_value. required key not provided @ data['value']`

I have the following thermostat (https://www.aliexpress.com/item/1005004996552864.html):
- Zigbee Model
  - TS0601
- Zigbee Manufacturer
  - _TZE200_aoclfnxz
- Description
  - Moes BHT series Thermostat
- Support status
  - Supported
- Manufacturer
  - [Moes](https://www.zigbee2mqtt.io/supported-devices/#v=Moes)
- Model
  - [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb)

Here is the state of the device.
```
{
    "child_lock": "LOCK",
    "current_heating_setpoint": 15,
    "heat": "OFF",
    "linkquality": 244,
    "local_temperature": 22,
    "min_temperature_limit": 5,
    "preset": "hold",
    "preset_mode": "hold",
    "running_state": "idle",
    "sensor": "IN",
    "system_mode": "off",
    "deadzone_temperature": null,
    "local_temperature_calibration": null,
    "max_temperature_limit": null
}
```

### What did you expect to happen?

1. I can change the max temperature.
2. I can change the current temperature in 0.5 steps.

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus (ZBDongle-E)

**Comment by ZTHawk** [comment]
This issue still exists using v1.30.1-1

**Comment by ArnSu** [comment]
> This issue still exists using v1.30.1-1

I am having the same issues. I tried Z2M Edge, same problem, cannot set deadzone temp, shows Null.
Any solution?
Thanks

**Comment by dropsmisha** [comment]
I am having the same issues.
"deadzone_temperature": null,
"max_temperature_limit": null,
Any solution?
Thanks

**Comment by phenixar** [comment]
Same issue here with a MOES Serie 006 ZIgbee, it was recognise like a BHT-002
Impossible to change Min / Max value and deadzone.
Other point, when I set a decimal value like 18.5 for example, the value is set to 0 or a strange value like "the max value of integer".
    "child_lock": "UNLOCK",
    "current_heating_setpoint": 18,
    "deadzone_temperature": null,
    "local_temperature": 18,
    "max_temperature_limit": null,
    "min_temperature_limit": 1,
It's become uregent to find a solution because actually I need to manage my device manually to avoid power on boiler every 10 minutes :(
The deadzone is really mandatory to avoid damage a boiler or other device behind.
Thanks.

**Comment by M450NC** [comment]
Same issue here with BHT-002-GCLZB.

Cannot set deadzone, max temp or adjust the programme mode setpoints/time. Apply button is greyed out and cannot get it to save any adjustments made in Z2M...

**Comment by insipiens** [comment]
the device physically [using the buttons] supports 0.5 steps but for some reason Mioes/Tuya imp[lemented the zigbee part of the firmware (not Z2m) with steps of 1 (integers). Annoying but not something that can change through Z2M

{
    "current_heating_setpoint": 11,
    "deadzone_temperature": 1,
    "heat": "OFF",
    "linkquality": 131,
    "local_temperature": 15.5,
    "local_temperature_calibration": -2,
    "max_temperature_limit": 30,
    "min_temperature_limit": 5,
    "preset": "hold",
    "preset_mode": "hold",
    "running_state": "idle",
    "sensor": "IN",
    "system_mode": "heat",
    "child_lock": null
}

**Comment by adorobis** [comment]
Setpoint step is a known limitation for zigbee communication for this device. 
And here is the information from Moes support confirming above limitation:
https://github.com/Koenkk/zigbee2mqtt/issues/14965#issuecomment-1368179306

**Comment by M0DDer** [comment]
> Same issue here with 006 series, shows as BHT-002-GCLZB in Z2M.
> 
> Cannot set deadzone, max temp or adjust the programme mode setpoints/time. Apply button is greyed out and cannot get it to save any adjustments made in Z2M...

I have the same! Two devices not work(

Zigbee2MQTT 1.30.2 & 20221226

**Comment by ZTHawk** [comment]
Still applicable

**Comment by ZTHawk** [comment]
still applicable

**Comment by M450NC** [comment]
Yep, I've decided to bin mine and choose a different thermostat. No idea why this hasn't been resolved when support for other devices seem to be resolved in a matter of days/weeks.

**Comment by ZTHawk** [comment]
still applicable

**Comment by iliesh** [comment]
I have the same issue, after updating zigbee2mqtt to the latest version (1.32.0) - I'm getting the following error:
```
zigbee-herdsman-converters:Moes BHT-002: existing program state not set.
```

**Comment by csszokolai** [comment]
> I have the same issue, after updating zigbee2mqtt to the latest version (1.32.0) - I'm getting the following error:
> 
> ```
> zigbee-herdsman-converters:Moes BHT-002: existing program state not set.
> ```

I have same issue with this comment. I had removed / repaired the device, it does not solved the issue. BTW the other null-s are settable if I manually set the value in.the field not by the slider.

**Comment by zeljkopopovic** [comment]
Hi guys, I am new in the community.
Is there any update about MOES  BHT-006? I just planning to order it and now I am thinking about which thermometer should I buy for underfloor water heating.
MOES  BHT-006 or  BHT-002 ?
Because here they mention that 002 works perfectly (https://github.com/fashberg/WThermostatBeca)
Thank you

**Comment by jayanezj** [comment]
still applicable v1.33.1

**Comment by adorobis** [comment]
This is not going to be implemented. It is a limitation of the device, not the z2m (at least the temp. step - not sure about the max temp limit).

**Comment by jayanezj** [comment]
What about the deadzone? This is important

**Comment by adorobis** [comment]
I can set the deadzone temp as well. The allowed range is from 0 to 5:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19752098/d7b8d92b-e405-4383-842d-cfe9d9c31ae6)

**Comment by adorobis** [comment]
BTW, everything is described in the device documentation:
https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb

**Comment by jayanezj** [comment]
The problem is that the device referred to in the ticket is not the BHT-002-GCLZB, it is BHT-006GAZB.
![Screenshot 2023-10-31 at 12 50 54](https://github.com/Koenkk/zigbee2mqtt/assets/1564947/81f0c7e9-6b32-409f-87b7-75b57c429580)

Although it is recognized by Zigbee2mqtt as a BHT-002-GCLZB. If necessary I can open a new ticket adding debug logs so that the correct compatibility for the model is added.
![Screenshot 2023-10-31 at 12 53 46](https://github.com/Koenkk/zigbee2mqtt/assets/1564947/b8b024b8-2808-4d78-bdd6-2ffada60a974)

Even if values are adjusted in the sliders nothing happens, it still appears as null in the status and the slider is reset.

![Screenshot 2023-10-31 at 12 53 27](https://github.com/Koenkk/zigbee2mqtt/assets/1564947/d95741ad-ee2b-4b5a-b453-75171f8f6f16)



```
{
    ...
    "running_state": "idle",
    "sensor": "IN",
    "system_mode": "off",
    "deadzone_temperature": null,
    "local_temperature_calibration": null,
    "max_temperature_limit": null
}
```

**Comment by adorobis** [comment]
Where? The ticket is opened for a different device, check the first entry by the opener:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19752098/4739bd52-1ea6-4bca-8186-a45233ed3b5c)

**Comment by adorobis** [comment]
In that case you should follow the process to add new device as described:
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by lukeskymuh** [comment]
This is also a problem if you try to use it with "better thermostat". If you set "Local temperature calibration" or "Current heating setpoint" to a non integer  value it results into some crazy random number. It looks like a integer to float conversion problem. As "Better thermostat" manipulates the values with float numbers it results in a random behavior. Is it possible to fix this in Z2M?

My device: MOES BHT-006 Zigbee

**Comment by effgen** [comment]
I have the same problem, was a solution found or not?

**Comment by adorobis** [comment]
As you can see this issue is closed. This is not z2m but a device limitation.. It only allows for 1 degree steps when controlled via zigbee.

**Comment by jayanezj** [comment]
I was doing some research to try to create a new component with full compatibility. I integrated the device with TuYa to check the exact endpoints and found that both the degree step problems, the temperature limits and dead zone work equally bad, so it's not even a limitation of zigbee2mqtt, it's of TuYa's own software. Just make sure Zigbee2mqtt recognizes the device as [BHT002/BHT006](https://www.zigbee2mqtt.io/devices/BHT-002_BHT-006.html#moes-bht-002%252Fbht-006), you're not going to get better results than that.

**Comment by lukeskymuh** [comment]
> As you can see this issue is closed. This is not z2m but a device limitation.. It only allows for 1 degree steps when controlled via zigbee.

Correct , but Z2M cold solve the problem by rounding the numbers for these devices.
