### ISSUE TITLE
[New device support]: Xamento "Hue White and Color Ambiance GU10" specific zigbeeModel number

### ISSUE THREAD

**Issue by aze827** [Koenkk/zigbee2mqtt#16105]
### Link

https://www.philips-hue.com/fr-fr/p/hue-white-and-color-ambiance-spot-encastrable-xamento/8719514355347

### Database entry

{"id":11,"type":"Router","ieeeAddr":"0x001788010c4b0341","nwkAddr":17528,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003074701","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64514,768,64513],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1673464983714,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to set-up my new Xamento light, and noticed a strange behaviour during its discovery on the network.
The model number printed on the GU10 bulb is "9290019531", but the "zigbeeModel" shows up as "929003074701", which is currently unsupported, leading to nothing usable on Home Assistant.

When editing /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/philips.js and changing

`    {
        zigbeeModel: ['LCG002', '929003047701'],
        model: '929001953101',
        vendor: 'Philips',
        description: 'Hue White and Color Ambiance GU10',
        extend: hueExtend.light_onoff_brightness_colortemp_color({
            colorTempRange: [153, 500], disableHueEffects: false,
        }),
    },
`

to

`    {
        zigbeeModel: ['LCG002', '929003047701', '929003074701'],
        model: '929001953101',
        vendor: 'Philips',
        description: 'Hue White and Color Ambiance GU10',
        extend: hueExtend.light_onoff_brightness_colortemp_color({
            colorTempRange: [153, 500], disableHueEffects: false,
        }),
    },
`

It then started to work as intended.

Am I in the right path to add support for that device ?
Sorry if I made any mistake by misunderstanding how model and zigbeeModel work..

Thanks,

Said product web pages below :
https://www.philips-hue.com/fr-fr/p/hue-white-and-color-ambiance-spot-encastrable-xamento/8719514355347
https://www.amazon.fr/gp/product/B09C3STHFL/

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
