### ISSUE TITLE
Device TS0601 not recognized (TZE200_gd4rvykv)

### ISSUE THREAD

**Issue by Shollus** [Koenkk/zigbee2mqtt#16102]
### What happened?

I bought a new thermostat. When I try to connect it to zigbee2MQTT I get message about not recognize device.

- Zigbee model 'TS0601'
- manufacturer name '_TZE200_gd4rvykv'

Someone can help me?

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

CC2652P

**Comment by Kraviecc** [comment]
Hi,

+1. Tried to play a bit with zigbee-herdsman-converters but neither Saswell nor Tyua groups are working correctly (missing values for entities like current_temp). Here you can find my attempts: https://github.com/Koenkk/zigbee-herdsman-converters/compare/master...Kraviecc:zigbee-herdsman-converters:feature/radiator-sanico
