### ISSUE TITLE
Feedback Issue SIN-4-2-20 Node

### ISSUE THREAD

**Issue by pocki013** [Koenkk/zigbee2mqtt#16119]
### What happened?

ISSUS white : SIN-4-2-20 Node
since the last update (which included a change for the model in question), the information on the status of activation or not is not automatically updated when the switch is manually activated (locally in physics) . To have correct information I have to do a "refresh" in the expose menu of the device.

Nothing appears in the log. However the device is controllable via the dashboard and physically

It's annoying because suddenly the information is not updated in the MQTT server and therefore my dashboards are in false state

### What did you expect to happen?

have the correct information on the curent state of the switch

### How to reproduce it (minimal and precise)

flip the switch manually (physically) and find that the state is not updating online

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB

**Comment by furieuxjk** [comment]
I have the same issue. Is it possible to somehow find a solution for this?
