### ISSUE TITLE
New device YPHIX dimmable driver, Sunricher HK-DIM

### ISSUE THREAD

**Issue by mhaast** [Koenkk/zigbee2mqtt#16128]
### Link

https://www.leddirect.nl/yphix-zigbee-led-driver-350-1400ma-50w?gclid=Cj0KCQiA_P6dBhD1ARIsAAGI7HCIRrITeOyS4kXWIzEDY982oEJcvufaedfvkZ2vFsF9AjpVA0IounYaAst3EALw_wcB

### Database entry

{"id":10,"type":"Router","ieeeAddr":"0x9035eafffe64334d","nwkAddr":491,"manufId":4107,"manufName":"Sunricher","powerSource":"Mains (single phase)","modelId":"HK-DIM","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,65535,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"modelId":"HK-DIM","zclVersion":3}},"genOta":{"attributes":{"currentFileVersion":63}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r63","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1673551819021,"defaultSendRequestWhen":"immediate"}

### Comments

When pairing I get a message: device not supported.
I'm quite a newbee, pleassa can you ad this device to the supported devices?

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
