### ISSUE TITLE
[New device support]: Aeotec zigbee range extender

### ISSUE THREAD

**Issue by 2stimpy** [Koenkk/zigbee2mqtt#16130]
### Link

https://www.zigbee2mqtt.io/devices/WG001.html

### Database entry

0xe0798dfffee41678, router, WG001-Z01

### Comments

I paired this new Aeotec Zigbee range extender but I get the message that it is unsupported.
It does seem to work though. 
But every time i go to the Z2Mqtt instance I get the error Received message from unsupported device with Zigbee model 'WG001-Z01' and manufacturer name 'AL001'
I am new to the convertor thing and don't really know how to solve this with a convertor.
Again, it does work but I would like to get rid of the red warning messages.

**Comment by malmaxx** [comment]
I've experienced this too.  I had four paired for over a year.  A few weeks ago found one that was no longer communicating.  Figured it had gone bad and just received a brand new replacement today.  Trying to pair and it attempts to pair for a few minutes before timing out with the Manufacturer as "unsupported".  Never had this issue before with the Zi range extenders.
