### ISSUE TITLE
TuYa TS130F wrong direction

### ISSUE THREAD

**Issue by JakubMartenka** [Koenkk/zigbee2mqtt#16151]
### What happened?

When I physically click close the blind closes. 
But when I click on HA the blind opens.

Zigbee2MQTT - 1.29.1-1

### Zigbee2MQTT version

1.29.1-1

### Adapter firmware version

20230104.0

### Adapter

TS130F

### Producent Zigbee
_TZ3000_wptayaqr

**Comment by JakubMartenka** [comment]
When motor_reversal is ON from HA works perfect but when I click on physically button the opposite turns on

Video:
https://user-images.githubusercontent.com/97041743/212461932-18358ea0-1e0f-479b-8397-2c2cfd1b5dee.MOV

https://vimeo.com/789223128

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by JakubMartenka** [comment]
@Koenkk no problem, but idk how do it :D  where is this file?

**Comment by JakubMartenka** [comment]
@Koenkk this is it? `{"id":6,"type":"Router","ieeeAddr":"0xa4c1385e84caab90","nwkAddr":6943,"manufId":4417,"manufName":"_TZ3000_wptayaqr","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[4,5,6,258,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"tuyaBacklightSwitch":1,"tuyaBacklightMode":1}},"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":18,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":1,"moesCalibrationTime":122}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1673720380138,"defaultSendRequestWhen":"immediate"}
`

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: 

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition =  {
    zigbeeModel: ['TS130F'],
    model: 'TS130F',
    vendor: 'TuYa',
    description: 'Curtain/blind switch',
    fromZigbee: [fz.cover_position_tilt, tuya.fz.backlight_mode_low_medium_high, fz.tuya_cover_options],
    toZigbee: [tz.cover_state, tz.cover_position_tilt, tz.tuya_cover_calibration, tz.tuya_cover_reversal,
        tuya.tz.backlight_indicator_mode],
    whiteLabel: [{vendor: 'LoraTap', model: 'SC400'}],
    exposes: [e.cover_position(), exposes.enum('moving', ea.STATE, ['UP', 'STOP', 'DOWN']),
        exposes.binary('calibration', ea.ALL, 'ON', 'OFF'), exposes.binary('motor_reversal', ea.ALL, 'ON', 'OFF'),
        exposes.enum('backlight_mode', ea.ALL, ['LOW', 'MEDIUM', 'HIGH']),
        exposes.numeric('calibration_time', ea.STATE).withUnit('S').withDescription('Calibration time')],
},;

module.exports = definition;

```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by JakubMartenka** [comment]
@Koenkk the external converter did not fix it. 
I changed the description to make sure it was added.
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/97041743/212549002-823c1c23-024d-40b6-9b54-1411a724c07e.png">

**Comment by JakubMartenka** [comment]
@Koenkk i try to understand how it works and i have one idea. 
Maybe we need here change when motor_reversal to {0: 'DOWN', 1: 'STOP', 2: 'UP'}

<img width="989" alt="image" src="https://user-images.githubusercontent.com/97041743/212685705-7e50ad11-39cf-4fdf-abf7-ffedb0617c2a.png">

**Comment by JakubMartenka** [comment]
@Koenkk  No, the same problem with external_converters too. When i i have disabled motor_reversal on physical buttons it works fine but in HA close = open and open = close and when i enable motor_reversal I still have this problem https://vimeo.com/789223128

**Comment by Koenkk** [comment]
Can you provide the debug log when opening the cover via HA and it closes instead?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by JakubMartenka** [comment]
Open and stop with motor_reversal = ON from HA
![image](https://user-images.githubusercontent.com/97041743/212976962-65ba27ea-7445-4546-89d8-8f12e1ec0295.png)

Close and stop with motor_reversal = ON from HA
![image](https://user-images.githubusercontent.com/97041743/212976905-02753387-c962-4bc9-a8a4-d9c5a9d4cfd3.png)

Open and stop motor_reversal = ON from button
![image](https://user-images.githubusercontent.com/97041743/212977347-805a31f0-e002-471f-aa50-2da9af536cb7.png)

Close and stop motor_reversal = ON from button
![image](https://user-images.githubusercontent.com/97041743/212977488-cc07dea8-9a80-44bb-ab2e-786c80674a6d.png)

Open and stop with motor_reversal = OFF from HA
![image](https://user-images.githubusercontent.com/97041743/212977931-962e799d-4f36-4cc3-8014-4cfe46099c35.png)

Close and stop with motor_reversal = OFF from HA
![image](https://user-images.githubusercontent.com/97041743/212978006-8cd13cc3-07a8-46d8-b675-774b8a5a922c.png)

Open and stop motor_reversal = ON from button
![image](https://user-images.githubusercontent.com/97041743/212978249-c7cd45a2-9cae-4303-927c-24c5640baa7e.png)

Close and stop motor_reversal = OFF from button
![image](https://user-images.githubusercontent.com/97041743/212978338-fde5dffb-ad32-49c6-ac39-f8794f70ea18.png)
