### ISSUE TITLE
[FUT036Z] power_on_behavioir shown but unsupported

### ISSUE THREAD

**Issue by emandtf** [Koenkk/zigbee2mqtt#16153]
### What happened?

Recently for Miboxer FUT036Z devices Z2M started to shown "power_on_behaviour" feature but when used it returns immediately an NOT_SUPPORTED erro as red toast on Z2M's frontend.

I suppose this feature was added by mistake.

### What did you expect to happen?

Not shown an UNSUPPORTED feature on Z2M frontend.

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

0x26780700 (May 2022)

### Adapter

Conbee 2

**Comment by Koenkk** [comment]
Seems this device does not support it, removed it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by JakeMannen** [comment]
This also seems to be the case for the **FUT035Z**. The power_on_behavior is not working.

**Comment by Koenkk** [comment]
@JakeMannen disabled!


Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
