### ISSUE TITLE
Dashboard not showing all devices

### ISSUE THREAD

**Issue by Schmetterfliege** [Koenkk/zigbee2mqtt#16165]
### What happened?

No idea what happened, but I noticed that my dashboard is not showing all devices.
Noticed it on the "switches" - Ikea Tradfri Switches.
![image](https://user-images.githubusercontent.com/76066402/212490814-a6666d10-4b2b-4b1d-9bab-d6cb54950cef.png)
(only showing 2 switches instead of 5)

In the devices list, all of them are shown and all are working fine.
![image](https://user-images.githubusercontent.com/76066402/212490833-db3bb683-c2f1-49aa-a6d4-d44c43e7782e.png)

### What did you expect to happen?

all devices are showing up in the dashboard

### How to reproduce it (minimal and precise)

Don't know :(

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

0x26580700

### Adapter

Conbee II

**Comment by Koenkk** [comment]
Issues related to the frontend should be created here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
