### ISSUE TITLE
TuYa TS011F_plug_1 not expose measurement_poll_interval to spec information on webui

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#16176]
### What happened?

When i edited in yaml file measurement_poll_interval option working like a charm.

![212468603-ac165007-79a0-4931-9200-9bdebb30df2a](https://user-images.githubusercontent.com/59237288/212542913-bb689ffd-af0c-4958-998d-8a2d1fe4155f.jpg)

Propably coverter not expose measurement_poll_interval to webui.

I add issue https://github.com/nurikk/zigbee2mqtt-frontend/issues/1651, but its propably not frontend issue?

### Zigbee2MQTT version

Z2M 1.29.2

### Adapter firmware version

20220219

### Adapter

Sonoff 3 USB

**Comment by thomasloven** [comment]
Still an issue.

**Comment by vahaldor** [comment]
> ~Still an issue.~
> 
> Edit: Sorry, I was mistaken. A device reporting as `TS011F_plug_1` is not supposed to expose `measurement_poll_interval`.

Thomas, I have the plug_1 version and it stopped reporting 0W power. Is it possible to manually force it to do it? Is it possible to configure measurement_poll_interval for this plug as well? Where do you edit the yaml in z2m? thank you
