### ISSUE TITLE
Please add this to devices.js to support Hive Active Light Cool to Warm White TWBulb01US

### ISSUE THREAD

**Issue by mattaw** [Koenkk/zigbee2mqtt#1617]
Using your guide and project I was able to get the  Hive Active Light Cool to Warm White TWBulb01US bulb working great with Zigbee2Mqtt, on/off, brightness and color temp. Zigbee2mqtt made it terribly easy.

Please add it to the official repo and add homeassistant integration publishing.
Hive Active Light Cool to Warm White TWBulb01US 

```
    {
        zigbeeModel: ['TWBulb01US'],
        model: 'HV-GSCXZB269',
        vendor: 'Hive',
        description: 'Hive Active Light Cool to Warm White (E26) ',
        extend: generic.light_onoff_brightness_colortemp,
    },
```

**Comment by Koenkk** [comment]
Thanks, supported in the dev branch now!

**Comment by mattaw** [comment]
Please could you add to the homeassistant.js as well? Or provide a neat way of managing those integrations in devices.js. I saw a homeassistant key, which I approve of (keep all device config in one file, but I couldn't quickly figure out how to use it to get something supported.

I think its a one liner in homeassistant.js, or could we move homeassistant.js to the zigbee-shepherd-converters project, since they both contain device specific information.

**Comment by Koenkk** [comment]
This has already been done in the dev branch.

**Comment by mattaw** [comment]
Could you share the commit? I am having trouble finding the code to do the publishing of the homeassistant/autodetect stuff. I am trying to get a dev environment running so I can do PRs directly for new devices and am very keen to include the homeassistant integration autodetect code (which I thought lived in zigbee2mqtt/lib/extension/homeassistant.js, and not zigbee-shepherd-converters) and if there is a newer way of doing this then I want to follow that. I couldn't find the code in your commit.

Thanks again, M

**Comment by Koenkk** [comment]
@mattaw  see https://github.com/Koenkk/zigbee2mqtt/commit/852950fc09646bd8dc244e4f5e3bd845ad258518#diff-0c056233b68fd3653afb296f98947c8fR734

**Comment by mattaw** [comment]
My fault - I was looking for the Zigbee id, not model number
Thanks for the explaination
