### ISSUE TITLE
TS110E_2gang exposes and state 

### ISSUE THREAD

**Issue by jacekmarek** [Koenkk/zigbee2mqtt#16206]
### What happened?

The device [TS110E_2gang](https://www.zigbee2mqtt.io/devices/TS110E_2gang.html) exposes `state`, `brightness`, `min_brightness`, `max_brightness` for both light: l1 endpoint and l2 endpoint:

![image](https://user-images.githubusercontent.com/63392738/212698265-7371da93-0ff0-4526-8509-9306a694055d.png)

but I get (from _TZ3210_wdexaypg):

    "max_brightness": 255,
    "max_brightness_l1": 255,
    "min_brightness": 255,
    "power_on_behavior": "off",
    "power_on_behavior_l1": "off",
 

### What did you expect to happen?

I expected:

    "max_brightness_l1": 255,
    "max_brightness_l2": 255,
    "min_brightness_l1": 255,
    "min_brightness_l2": 255,
    "power_on_behavior_l1": "off",
    "power_on_behavior_l2": "off",

### Zigbee2MQTT version

 1.29.2

### Adapter firmware version

0x26720700

### Adapter

Conbee2

### Debug log

    info 2023-01-16 15:24:34MQTT publish: topic 'zigbee2mqtt/0xa4c13850173e754f', payload '{"brightness_l1":255,"brightness_l2":255,"last_seen":"2023-01-16T15:24:34+01:00","linkquality":255,"max_brightness":255,"max_brightness_l1":255,"min_brightness":255,"power_on_behavior":"off","power_on_behavior_l1":"off","power_outage_memory_l1":"restore","power_outage_memory_l2":"restore","state_l1":"OFF","state_l2":"OFF","switch_type_l1":"momentary","switch_type_l2":"momentary"}'

    info 2023-01-16 15:24:34MQTT publish: topic 'zigbee2mqtt/0xa4c13850173e754f/l1', payload '{"brightness":255,"max_brightness":255,"power_on_behavior":"off","power_outage_memory":"restore","state":"OFF","switch_type":"momentary"}'

    info 2023-01-16 15:24:34MQTT publish: topic 'zigbee2mqtt/0xa4c13850173e754f/l2', payload '{"brightness":255,"power_outage_memory":"restore","state":"OFF","switch_type":"momentary"}'

**Comment by joggs** [comment]
I have the same issue
