### ISSUE TITLE
Zigbee2mqtt fails to start

### ISSUE THREAD

**Issue by frabar55** [Koenkk/zigbee2mqtt#16203]
### What happened?

Zigbee2mqtt fails to start after upgrade to 1.29.2

cannot open the coordinator

of course all devices are off-line

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

the last one

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Using '/app/data' as data directory
Zigbee2MQTT:info  2023-01-16 14:56:37: Logging to console and directory: '/var/log' filename: log.txt
Zigbee2MQTT:info  2023-01-16 14:56:37: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6)
Zigbee2MQTT:info  2023-01-16 14:56:37: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-16 14:56:38: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-16 14:56:38: Failed to start zigbee
Zigbee2MQTT:error 2023-01-16 14:56:38: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-16 14:56:38: Exiting...
Zigbee2MQTT:error 2023-01-16 14:56:38: Error: Error while opening serialport 'Error: Error: I/O error, cannot open /dev/ttyUSB0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:91:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18

**Comment by wmoss** [comment]
Do you have the E or P version of the Sonoff dongle? I have the E version and upgrading to 1.9.2 required I add `adapter: ezsp` to the `serial` section of my config (see [here](https://www.zigbee2mqtt.io/guide/adapters/#experimental) for more details).
