### ISSUE TITLE
[New device support]: Philips Hue Filament E27 (9290030517)

### ISSUE THREAD

**Issue by rd778** [Koenkk/zigbee2mqtt#16214]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-filament-st64-edison-%E2%80%93-e27-smart-bulb/8718699688868

### Database entry

{"id":16,"type":"Router","ieeeAddr":"0x001788010d3055e4","nwkAddr":10521,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LWV005","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":257,"inClusterList":[0,3,4,5,6,8,4096,64515,64514],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20201126","swBuildId":"1.78.1","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1673894049220,"defaultSendRequestWhen":"immediate"}

### Comments

The Philips Hue filament E27 ST64 bulb is listed as supported (https://www.zigbee2mqtt.io/devices/92900244777.html), except this model number (9290030517) is different to what's listed on the supported list. Presumably the different model number is why the device is showing as not supported when I pair it.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
