### ISSUE TITLE
Sengled Element Plus Z01-A19NAE26 missing power stats, present in ZHA

### ISSUE THREAD

**Issue by redonionking** [Koenkk/zigbee2mqtt#16217]
### What happened?

Z01-A19NAE26 bulbs Element plus (A19) do not report power usage in Zigbee2Mqtt but they do in ZHA

### What did you expect to happen?

Bulbs would report power use

### How to reproduce it (minimal and precise)

Pair bulbs with zigbee2mqtt

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff  EZSP v8

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
