### ISSUE TITLE
Tuya 3 gang switch module recognised as Zemismart ZM-L03E-Z

### ISSUE THREAD

**Issue by kuzabi** [Koenkk/zigbee2mqtt#16216]
### What happened?

I bought 3 gang Tuya switch module:
https://www.aliexpress.com/item/1005004455385232.html?spm=a2g0o.order_list.order_list_main.5.7a491802wdMhmX
![obraz](https://user-images.githubusercontent.com/30179261/212752306-632ce3e6-996f-4c33-b7b3-5e9cd7f1135b.png)

I think it's TS0003_switch_module however it was recognised as a Zemismart ZM-L03E-Z switch panel.
![obraz](https://user-images.githubusercontent.com/30179261/212751859-0b7251c5-b2a0-4133-920f-f47ca4e654e7.png)

### What did you expect to happen?

Module TS0003 (_TZ3000_4o16jdca) to be recognised correctly.

Fix probably similar to: #9539

### How to reproduce it (minimal and precise)

Pair the module

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20220301

### Adapter

CC2652P

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
