### ISSUE TITLE
VZM31-SN Missing Homeassistant discovery topic for "action"

### ISSUE THREAD

**Issue by mdallaire** [Koenkk/zigbee2mqtt#16212]
### What happened?

I installed several VZM31-SN in my house in the last few days and for all of them I have no "action" sensor in Home-Assistant.

- I see the action in z2m (ex: up_double), 
- I see the topic (action) and payload (up_double) under the zigbee2mqtt topic of the switch.
- I don't see a action sensor in Home-Assitant
- I don't see a Home-Assistant discovery topic for the action sensor under the homeassistant topic.

### What did you expect to happen?

I expected to see a action sensor in Home-Assistant.

### How to reproduce it (minimal and precise)

Add VZM31-SN to z2m, check home-assistant for action sensor.

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20220219

### Adapter

zzh

### Debug log

[zigbee.log](https://github.com/Koenkk/zigbee2mqtt/files/10430378/zigbee.log)

**Comment by hexonMD** [comment]
Experiencing the same issue. Tried repairing the switch multiple times with no success. I don't however see any actions within Z2M. The section just shows N/A.

**Comment by InovelliUSA** [comment]
What settings do you have configured for your HA integration in z2m?

![image](https://user-images.githubusercontent.com/37669481/215286917-f8ade83c-1d93-46a5-a905-9dd4516a2881.png)


@hexonMD which coordinator do you have?

**Comment by mdallaire** [comment]
I do not have the legacy trigger checked.

I was able to trigger automations by using the device based triggers in Home-Assistant.

Does that mean the device based triggers are the "not legacy" triggers and that the action sensor is considered a legacy trigger?

**Comment by hexonMD** [comment]
﻿I’m running the Electrolama zig-a-zig-ah! On Jan 28, 2023, at 11:21 AM, Inovelli ***@***.***> wrote:﻿
What settings do you have configured for your HA integration in z2m?

@hexonMD which coordinator do you have?

**Comment by InovelliUSA** [comment]
> I was able to trigger automations by using the device based triggers in Home-Assistant.
> 
> Does that mean the device based triggers are the "not legacy" triggers and that the action sensor is considered a legacy trigger?

Yes, I believe so. I recommend using the device based triggers, but I think enabling the legacy option will enable the other.

@hexonMD I think yours is a different issue and I think I am working with you on that in the support system. The switch is binding to endpoint 0 on your coordinator and the commands are either not being sent or are not being parsed in z2m.

**Comment by InovelliUSA** [comment]
@hexonMD I am trying to force the converter to bind to endpoint 1 of the coordinator, but I am not having success. I am wondering if anyone else has experience doing this? I have searched through a lot of sample code and cannot find anything. This is what I am using and it seems to be binding to the lowest available ep on your coordinator (coordinatorEndpoint - which is 0).

```
configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint ,  [
                'seMetering',
                'haElectricalMeasurement',
                'genOnOff',
                'genLevelCtrl',
            ]);
            await reporting.onOff(endpoint);

            await endpoint.read('haElectricalMeasurement', [
                'acPowerMultiplier',
                'acPowerDivisor',
            ]);
            await reporting.readMeteringMultiplierDivisor(endpoint);
        }
```
