### ISSUE TITLE
[New device support]: Philips Hue white ambiance Cher

### ISSUE THREAD

**Issue by patpac9** [Koenkk/zigbee2mqtt#16226]
### Link

https://www.philips-hue.com/de-at/p/hue-white-ambiance-cher-pendelleuchte/8719514341197

### Database entry

IEEE Addresse     0x0017880108569bbb Netzwerk Adresse     0x4FB2 Firmware-Datum     20190529 Firmware-Version     1.56.7_r29434  Geräte-Typ     Router Zigbee Modell     4076130P6 Zigbee Hersteller     Philips

### Comments

Hi,
I don't know how to access this database file, so I put my dev details in there.

There is the same device with another model number already in there:
In zigbee-herdsman-converters/devices/philips.js

    {
        zigbeeModel: ['4076131P6'],
        model: '4076131P6',
        vendor: 'Philips',
        description: 'Hue white ambiance suspension Cher with bluetooth 3000lm',
        extend: philips.extend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
    },

It just got another Model Number: 4076130P6

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    zigbeeModel: ['4076130P6'],
    model: '4076130P6',
    vendor: 'Philips',
    description: 'Hue white ambiance Cher Light',
    extend: extend.light_onoff_brightness_colortemp(),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added thanks to @zegl 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
