### ISSUE TITLE
Version not available in docker under Unraid->No update possible

### ISSUE THREAD

**Issue by canedje** [Koenkk/zigbee2mqtt#16246]
### What happened?

My Z2M docker under unraid shows version not available and because of that can not update.
Current version Z2M is 1.29.1
Version Unraid: 6.11.5
![image](https://user-images.githubusercontent.com/23150947/213208675-a0d6a240-871b-4e0c-9e68-012231a597dc.png)

### What did you expect to happen?

Expected to see up-to-date or update-available at version column

### How to reproduce it (minimal and precise)

It occurs without handling and is always there

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonof zigbee 3.0 dongle plus-E

### Debug log

There is no debug log.
Docker is running oke
also updating by adding by hand to repository:1.29.2 doesn't update

**Comment by lewistu** [comment]
Sounds similar to this issue: https://github.com/Koenkk/zigbee2mqtt/issues/16201

**Comment by canedje** [comment]
your right. Looks like the same
I didn't found that issue
