### ISSUE TITLE
SMSZB-120 missing sensors

### ISSUE THREAD

**Issue by federicosantolini** [Koenkk/zigbee2mqtt#16244]
### What happened?

Starting from the last two updates of Z2M, I am having problems with the SMSZB-120 siren. Before, I lost the ability to manage the siren independently from the smoke (which worked fine until December). Now it no longer passes me the value of the temperature sensor. Initially, I had to update because I could no longer stop the siren with the siren.turn_off service but since then everything has just gotten worse.

### What did you expect to happen?

See temperature value
![image](https://user-images.githubusercontent.com/94896891/213162361-abf3e7d3-e179-4a80-80f8-77c16af14228.png)

### How to reproduce it (minimal and precise)

pair the SMSZB-120 siren to Z2M using conbee2 dongle

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

26720700

### Adapter

Conbee2

**Comment by federicosantolini** [comment]
Still needing to be fixed.
![image](https://user-images.githubusercontent.com/94896891/220664247-db3c8b7b-2a94-47c2-beec-cfb803f12469.png)

**Comment by garret** [comment]
I have the same issue after having just bought 4 of these smoke detectors (posted my comment here https://github.com/Koenkk/zigbee2mqtt/issues/17983#issuecomment-1925673850) Are you using a conbee usb stick? Maybe the temperature value can be solved by using another stick like the SONOFF one but it is strange that it was working before for you and now not anymore. Then it does not seem like a zigbee antenna issue. Have you tried to revert to a previous release of Z2M when everything was working?

**Comment by Articole** [comment]
Hello,

I have the same problem with Conbee3 with last Firmware.
To getting Temperature and Battery work, i followed this in Z2M for the moment #14997
