### ISSUE TITLE
[Feature request]: Set LED color on Bticino switches

### ISSUE THREAD

**Issue by federicosantolini** [Koenkk/zigbee2mqtt#16245]
### Is your feature request related to a problem? Please describe

Not related to an issue

### Describe the solution you'd like

I would like to have the ability to set the color of the LED on [Bticino switches](https://www.zigbee2mqtt.io/devices/K4003C_L4003C_N4003C_NT4003C.html#bticino-k4003c%252Fl4003c%252Fn4003c%252Fnt4003c).

### Describe alternatives you've considered

no alternatives, just asking for a possibility.

### Additional context

On Bticino switches, it is already possible to control the LED separately (on and off). Since during the configuration the LED can be red, green, blue and purple, I assume it is a small RGB LED. It would be nice to be able to control it. It would have a use, for example, to indicate the state of an alarm (for example red if the alarm is armed).

**Comment by Reinqusito** [comment]
+1 for this feature

**Comment by giodaprile** [comment]
Me too for the feature. Thanks a lot

**Comment by federicosantolini** [comment]
Please reopen it. I still like to have this feature
