### ISSUE TITLE
Try to connect router function with second sonoff zigbee usb 3 stick (with router firmware)

### ISSUE THREAD

**Issue by heuvep** [Koenkk/zigbee2mqtt#16263]
### What happened?

I have a second sonoff usb 3 stick for my home assistant with router firmware connect. But when i connect nothing happens with joined is on. When is push the botton on the sticj closed to the usb then the following happens.
Firs it gives a error and after that it joines but als a coordinator while i have router firmware on it. I see nothing on the zigbee2mqtt screen. I habe used the last version of the firmware and zigbee2mqtt. Also the last version of home assistant.

### How to reproduce it (minimal and precise)

plugin the sonoff zigbee usb stick with router firmware and joined on. Nothing happens and then i use botton on stick closed to usb part and then a error comes (see picture) and after a few message it start joining but as a coordinator (sees picture) 

### Zigbee2MQTT version

1.29.2.1

### Adapter firmware version

last version

### Adapter

sonoff zigbee usb 3

### Debug log

![coordinator](https://user-images.githubusercontent.com/65759210/213490584-bc906c88-8d5b-4607-b521-aad1aebd892c.png)

**Comment by heuvep** [comment]
I also have a sonoff zigbee usb 3 as a coordinator and the zigbee network works well but a want a second sonoff zigbee usb 3 as a router for more signal

**Comment by sambeetm** [comment]
i am planning to have this setup in 2-3 weeks when my 2nd adapter arrives from china. Will update my experience here,

**Comment by heuvep** [comment]
Hello,

 

The sonoff zigbee 3 usb was first the coordinator but it did buy a seccond make the new one the coordinator and the old one i did flash with the router firmware but it still detect it as coordinator.

It there something I need to delect before it detects it a  router?

 

Here some debug info after I push the botton on the sonoff zigbee 3 usb stick (close to the usb part becauseon the reset bottom it does nothing

 

Warning 2023-01-20 16:42:11Device '0x00124b0024c2ba08' left the network

Info 2023-01-20 16:42:12MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0024c2ba08","ieee_address":"0x00124b0024c2ba08"},"type":"device_leave"}'

Info 2023-01-20 16:42:12MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00124b0024c2ba08"},"type":"device_removed"}'

Error 2023-01-20 16:42:12Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:12TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:13Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:13TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:14Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:14TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:15Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:15TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:16Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:16TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:17Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:17TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:18Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:18TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Error 2023-01-20 16:42:19Error: Cannot read properties of undefined (reading 'endpoints')

Debug 2023-01-20 16:42:19TypeError: Cannot read properties of undefined (reading 'endpoints') at Zigbee.firstCoordinatorEndpoint (/app/lib/zigbee.ts:267:64) at Bridge.publishInfo (/app/lib/extension/bridge.ts:577:43) at EventEmitter.<anonymous> (/app/lib/extension/bridge.ts:74:89) at EventEmitter.emit (node:events:513:28) at EventBus.emitPermitJoinChanged (/app/lib/eventBus.ts:24:22) at Controller.<anonymous> (/app/lib/zigbee.ts:69:27) at Controller.emit (node:events:513:28) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:264:30) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)

Info 2023-01-20 16:42:20Device 'Coordinator' joined

Info 2023-01-20 16:42:20MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Coordinator","ieee_address":"0x00124b0024c2ba08"},"type":"device_joined"}'

Info 2023-01-20 16:42:20MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"Coordinator"},"type":"device_connected"}'

Info 2023-01-20 16:42:20Starting interview of 'Coordinator'

Info 2023-01-20 16:42:20MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Coordinator","ieee_address":"0x00124b0024c2ba08","status":"started"},"type":"device_interview"}'

Info 2023-01-20 16:42:20MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"Coordinator"},"type":"pairing"}'

Debug 2023-01-20 16:42:20Device 'Coordinator' announced itself

Info 2023-01-20 16:42:21MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Coordinator","ieee_address":"0x00124b0024c2ba08"},"type":"device_announce"}'

Info 2023-01-20 16:42:21MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Coordinator"},"type":"device_announced"}'

 

Van: sambeetm ***@***.***> 
Verzonden: donderdag 19 januari 2023 20:36
Aan: Koenkk/zigbee2mqtt ***@***.***>
CC: heuvep ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Koenkk/zigbee2mqtt] Try to connect router function with second sonoff zigbee usb 3 stick (with router firmware) (Issue #16263)

 

i am planning to have this setup in 2-3 weeks when my 2nd adapter arrives from china. Will update my experience here,
