### ISSUE TITLE
Ikea E2002 goes offline as soon as paired

### ISSUE THREAD

**Issue by Freeswiss** [Koenkk/zigbee2mqtt#16275]
### What happened?

I installed Haos on my Pi3 with a Conbee2. Got zigbee2mqtt running and startet adding my tradfri devices.

1. One GU10 Bulb
2. One E1810 Remote
3. One E2002 Remote

I worked with Controllerx to get the Remotes to control the Lamp. That all works with the E1810 but I have a Problem with the E2002.

When I pair the E2002 in zigbee2mqtt it shows it as online, but switches to offline immideatly. When I press any buttons I see nothing in the Log. I only get log entrys when Joining or removing the batteries and restarting the remote. It also shows me 255% Battery level all the time.

### What did you expect to happen?

Logs of buttonpresses.
Device online.
Accurate Battery Level.

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

26720700

### Adapter

Conbee2

### Debug log

Zigbee2MQTT:info  2023-01-20 14:05:20: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-01-20 14:05:20: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"z0ioc-1"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: Device '0x842e14fffe70da64' joined
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe70da64","ieee_address":"0x842e14fffe70da64"},"type":"device_joined"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x842e14fffe70da64"},"type":"device_connected"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/sensor/0x842e14fffe70da64/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 battery","state_class":"measurement","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/sensor/0x842e14fffe70da64/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 action","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/sensor/0x842e14fffe70da64/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/sensor/0x842e14fffe70da64/last_seen/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"device_class":"timestamp","enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:clock","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 last seen","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_last_seen_zigbee2mqtt","value_template":"{{ value_json.last_seen }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/sensor/0x842e14fffe70da64/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 update state","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/binary_sensor/0x842e14fffe70da64/update_available/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"device_class":"update","enabled_by_default":false,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64 update available","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_update_available_zigbee2mqtt","value_template":"{{ value_json['update']['state'] == \"available\" }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'homeassistant/update/0x842e14fffe70da64/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x842e14fffe70da64/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0x842e14fffe70da64"],"manufacturer":"IKEA","model":"STYRBAR remote control (E2001/E2002)","name":"0x842e14fffe70da64","sw_version":"2.4.5"},"device_class":"firmware","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","json_attributes_topic":"zigbee2mqtt/0x842e14fffe70da64","latest_version_template":"{{ value_json['update']['latest_version'] }}","latest_version_topic":"zigbee2mqtt/0x842e14fffe70da64","name":"0x842e14fffe70da64","payload_install":"{\"id\": \"0x842e14fffe70da64\"}","state_topic":"zigbee2mqtt/0x842e14fffe70da64","unique_id":"0x842e14fffe70da64_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":null,"last_seen":"2023-01-20T14:05:28+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:05:28: Starting interview of '0x842e14fffe70da64'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe70da64","ieee_address":"0x842e14fffe70da64","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2023-01-20 14:05:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x842e14fffe70da64"},"type":"pairing"}'
Zigbee2MQTT:info  2023-01-20 14:05:30: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":null,"last_seen":"2023-01-20T14:05:30+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:05:31: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":null,"last_seen":"2023-01-20T14:05:31+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:05:31: Successfully interviewed '0x842e14fffe70da64', device has successfully been paired
Zigbee2MQTT:info  2023-01-20 14:05:31: Device '0x842e14fffe70da64' is supported, identified as: IKEA STYRBAR remote control (E2001/E2002)
Zigbee2MQTT:info  2023-01-20 14:05:32: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"STYRBAR remote control","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["on","off","brightness_move_up","brightness_move_down","brightness_stop","arrow_left_click","arrow_right_click","arrow_left_hold","arrow_right_hold","arrow_left_release","arrow_right_release"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"E2001/E2002","options":[{"description":"Simulate a brightness value. If this device provides a brightness_move_up or brightness_move_down action it is possible to specify the update interval and delta. The action_brightness_delta indicates the delta for each interval. ","features":[{"access":2,"description":"Delta per interval, 20 by default","name":"delta","property":"delta","type":"numeric","value_min":0},{"access":2,"description":"Interval duration","name":"interval","property":"interval","type":"numeric","unit":"ms","value_min":0}],"name":"simulated_brightness","property":"simulated_brightness","type":"composite"},{"access":2,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true).","name":"legacy","property":"legacy","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"IKEA"},"friendly_name":"0x842e14fffe70da64","ieee_address":"0x842e14fffe70da64","status":"successful","supported":true},"type":"device_interview"}'
Zigbee2MQTT:info  2023-01-20 14:05:32: Configuring '0x842e14fffe70da64'
Zigbee2MQTT:info  2023-01-20 14:05:32: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"STYRBAR remote control","friendly_name":"0x842e14fffe70da64","model":"E2001/E2002","supported":true,"vendor":"IKEA"},"type":"pairing"}'
Zigbee2MQTT:info  2023-01-20 14:05:33: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":null,"last_seen":"2023-01-20T14:05:33+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:05:34: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:05:34+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:05:34: Successfully configured '0x842e14fffe70da64'
Zigbee2MQTT:info  2023-01-20 14:05:59: MQTT publish: topic 'zigbee2mqtt/Test_Lampe_Zimmer', payload '{"brightness":200,"color":{"h":123,"hue":123,"s":100,"saturation":100,"x":0.17,"y":0.703},"color_mode":"xy","color_temp":250,"color_temp_startup":250,"last_seen":"2023-01-20T14:05:59+01:00","linkquality":255,"power_on_behavior":"toggle","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-01-20 14:06:44: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:06:44+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:06:47: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:06:47+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:06:50: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:06:50+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:06:53: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:06:53+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:06:56: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:06:56+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:14:20: MQTT publish: topic 'zigbee2mqtt/Test_Lampe_Zimmer', payload '{"brightness":200,"color":{"h":40,"hue":40,"s":49,"saturation":49,"x":0.3804,"y":0.3767},"color_mode":"color_temp","color_temp":250,"color_temp_startup":250,"last_seen":"2023-01-20T14:14:20+01:00","linkquality":255,"power_on_behavior":"toggle","state":"ON","update":{"installed_version":268572245,"latest_version":268572245,"state":"idle"},"update_available":false}'
Zigbee2MQTT:info  2023-01-20 14:21:21: MQTT publish: topic 'zigbee2mqtt/0x842e14fffe70da64', payload '{"action":null,"battery":255,"last_seen":"2023-01-20T14:21:21+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Zigbee2MQTT:info  2023-01-20 14:21:22: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe70da64","ieee_address":"0x842e14fffe70da64"},"type":"device_announce"}'
Zigbee2MQTT:info  2023-01-20 14:21:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x842e14fffe70da64"},"type":"device_announced"}'

**Comment by malaakso** [comment]
Seems a duplicate of #15725 , version 2.4.5 not being supported.

**Comment by Freeswiss** [comment]
> Seems a duplicate of #15725 , version 2.4.5 not being supported.

Thanks, I'll close this one.
