### ISSUE TITLE
SMSZB-120 OTA

### ISSUE THREAD

**Issue by Gonioul** [Koenkk/zigbee2mqtt#16280]
### What happened?

Two smoke sensors:

One bought in early December doesn't show it's version, although at some time it said an update was available, and showed 4.0.5 after upgrade for a short time in late December, until it came back to the same display. As 4.0.5 was suppose to need a new zigbee2mqtt version for proper alarm handling, I waited early January.
Note that some values where undefined like reliability until then.

The second bought middle January clearly says it's version is 4.0.7 but OTA complains it's newer than the online version.
All values are available, but I'm afraid there could be some new bugs.

![image](https://user-images.githubusercontent.com/64291573/213814198-23dcb41b-6c47-406a-b10e-347dd92d3c7c.png)

![image](https://user-images.githubusercontent.com/64291573/213814220-997abc1f-c2bd-4954-83d5-318090397bdb.png)

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by MATHZE92** [comment]
Same thing with the MOSZB-140 Motion Sensor, got one with Firmware 4.0.3 and 3 more with 4.0.2. Someone got access to Develco's Support Forum? I dont think that some private person like me get access to that. :D
Greetings Matthias
