### ISSUE TITLE
[New device support]: Bosch Plug Compact BSP-EZ2 for type E socket

### ISSUE THREAD

**Issue by rmi1974** [Koenkk/zigbee2mqtt#16306]
### Link

https://www.bosch-smarthome.com/uk/en/products/devices/plug-compact/

### Database entry

{"id":50,"type":"Router","ieeeAddr":"0x847127fffe2fb543","nwkAddr":23313,"manufId":4617,"manufName":"BOSCH","powerSource":"Mains (single phase)","modelId":"RBSH-SP-ZB-FR","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,1794,2820,2821],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"RBSH-SP-ZB-FR","manufacturerName":"BOSCH","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20201014","swBuildId":"2.5"}},"seMetering":{"attributes":{"multiplier":1,"divisor":100,"currentSummDelivered":[0,0]}},"haElectricalMeasurement":{"attributes":{"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b699be","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b699be","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b699be","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":0},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":0},{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":300,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20201014","swBuildId":"2.5","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1497992357,"reporting":1},"lastSeen":1674410593372,"defaultSendRequestWhen":"immediate"}

### Comments

Hello folks,

follow-up to:

https://github.com/Koenkk/zigbee2mqtt/issues/13069

There is another version of the same Smart Plug, but for type E socket (french market).
It has designation *RBSH-SP-ZB-FR* instead of *RBSH-SP-ZB-EU* (https://github.com/Koenkk/zigbee2mqtt/issues/13069).

Model: BSP-EZ2

https://www.bosch-smarthome.com/uk/media/content/10_bedienungsanleitungen/zwischenstecker_kompakt/bosch_8750001307_plog_compact_en_fr_dk.pdf

You can see the difference on the photo here:

https://www.amazon.de/gp/product/B08W8DMGHM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

It has grounding pin of the type E socket.
Otherwise it's exactly the same specs.

I've worked around using instructions from https://github.com/Koenkk/zigbee2mqtt/issues/13069 (external converter, install code etc).

It would be nice if this variant of the same plug could be supported by default as well.

Regards

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
