### ISSUE TITLE
Sonoff SNZB-02D Configuration Error on battery

### ISSUE THREAD

**Issue by PABHudds** [Koenkk/zigbee2mqtt#16319]
### What happened?

After the Interview configuration I get the following error:
Error 2023-01-23 14:52:20Configure failed: Error: ConfigureReporting 0x30fb10fffe6eaec1/1 genPowerCfg([{"attribute":"batteryVoltage","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')

Seen on two different devices. Repairing etc. does not change this. Battery shows as N/A or null when enabled in HA.

### What did you expect to happen?

No error

### How to reproduce it (minimal and precise)

Force remove device, re-pair.

### Zigbee2MQTT version

1.29.2-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 US Dongle Plus (CC2652P)

**Comment by hankanman** [comment]
Can confirm similar behaviour using Home Assistant Yellow built in radio

**Comment by smh51** [comment]
Can confirm this issue here also with the same adapter running on hass.io

**Comment by Koenkk** [comment]
Will be fixed in the z2m 1 February release.

**Comment by smh51** [comment]
Since 1.30. My SNZB-02D didn't report any measurement. The battery problem was not fixed. I reverted to 1.29.2

**Comment by trollix** [comment]
Zigbee2mqtt version 1.30.4-1 
My SNZB-02D doesn't report well battery level. It's only good on "expose".
![screenshot_1326](https://github.com/Koenkk/zigbee2mqtt/assets/3890545/8c409b0e-f3e8-4eb9-bddf-a44170e639b2)
![screenshot_1325](https://github.com/Koenkk/zigbee2mqtt/assets/3890545/f8474238-a236-4a33-b06e-c89f6fcad803)
![screenshot_1324](https://github.com/Koenkk/zigbee2mqtt/assets/3890545/f44f2c87-3e9e-493c-a454-6f45b23d88b4)

**Comment by sulliwane** [comment]
![Screenshot from 2023-07-28 12-30-42](https://github.com/Koenkk/zigbee2mqtt/assets/1733686/abd71e4f-4817-47a6-96ae-a030dd12d4e7)
![Screenshot from 2023-07-28 12-32-16](https://github.com/Koenkk/zigbee2mqtt/assets/1733686/d05f3956-783d-4278-920d-052d9e7e02b1)
![Screenshot from 2023-07-28 12-32-49](https://github.com/Koenkk/zigbee2mqtt/assets/1733686/b22b92b9-2f7e-412b-b127-ac34d47d1114)


unsupported here :( any idea?
