### ISSUE TITLE
DeviceConfigure failures with UseeLink SM-0306E-2W

### ISSUE THREAD

**Issue by Pla5ma** [Koenkk/zigbee2mqtt#16336]
### What happened?

After restart of Zigbee controller I get DeviceConfigure error messages for the SM-0306E-2W devices with IOBroker adapter for Zigbee:
DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1183:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17) at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:54:21) at async Promise.all (index 1))

Another error pops up from time to time in a regular base:
DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1183:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))

### What did you expect to happen?

-

### How to reproduce it (minimal and precise)

Restart of the IOBroker adapter or Zigbee controller.

### Zigbee2MQTT version

Not exposed in the IOBroker adapter.

### Adapter firmware version

Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20201026}}

### Adapter

CC26X2R1

**Comment by Koenkk** [comment]
You are using iobroker.zigbee, not zigbee2mqtt, please create an issue [here](https://github.com/ioBroker/ioBroker.zigbee/issues)
