### ISSUE TITLE
WZ5 Led controller controller in RGBW mode recognized as TuYa TS0504B

### ISSUE THREAD

**Issue by durkdeboer** [Koenkk/zigbee2mqtt#16338]
### What happened?

WZ5 Led controller controller in RGBW mode recognized as TuYa TS0504B

it show up as worg device 
in rgb mode it works but then the warm withe doesnt work.

### What did you expect to happen?

show up as WZ5 RGBW so i can contol withe collor as well

### How to reproduce it (minimal and precise)

not possible

### Zigbee2MQTT version

1.29.2-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8 sonof

**Comment by migor7** [comment]
I can confirm the issue. New WZ5 recognized as WZ1 (TS0501B) in dimmer mode

**Comment by durkdeboer** [comment]
Still not solved

**Comment by lukiii16** [comment]
Still not solved, my wz5 LED controller is visible as TS0504B. 
Home Assistant 2024.5.5

Do you have any workaround?
