### ISSUE TITLE
Value received via mqtt is multiplied by 10

### ISSUE THREAD

**Issue by chino-lu** [Koenkk/zigbee2mqtt#16346]
### What happened?

When the local temperature calibration of an Eurotronic SPZB0001 should be set via home assistant, the value is multiplied by 10 only if the value is >10.

For example, setting a value of 5, works fine
Setting a value of 20, does not work.

### What did you expect to happen?

if a value, higher than 10, is sent via Home Assistant or MQTT, the value should be applied 1by1, without beeing multiplied.

### How to reproduce it (minimal and precise)

no special steps needed.
just join an eurotronic into the mesh, and send the values via Home Assistant interface.

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20210708

### Adapter

 SONOFF Zigbee 3.0 USB Dongle Plus (P-version)

### Debug log

`2023-01-25 15:32:42Publish 'set' 'local_temperature_calibration' to 'Heizung Schlafzimmer Raoul DG' failed: 'RangeError [ERR_OUT_OF_RANGE]: Write 0x00158d0003c47003/1 hvacThermostat({"localTemperatureCalibration":200}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (The value of "value" is out of range. It must be >= -128 and <= 127. Received 200)'`

**Comment by Koenkk** [comment]
This is correct, the value send to the device is multiplied by 10 as the increments on the device side are per 0.1. 

As can be seen in the Zigbee spec, `localTemperatureCalibration` is an `int8` meaning it can fit any value from -128 till 127 (aka -12.8 between 12.7 degrees Celsius).

![image](https://user-images.githubusercontent.com/2892853/214616267-571f8446-33a7-4c39-a62a-7d33ebafd29b.png)

This is currently not mentioned in the docs, but I've correct the range for all thermostats so it will be with the next z2m release on 1 February.
