### ISSUE TITLE
E1745 occupancy_timeout not working correctly

### ISSUE THREAD

**Issue by SucubusJenny** [Koenkk/zigbee2mqtt#16341]
### What happened?

When the occupancy timeout for the E1745 is set. it does not appear to work in seconds. it appears to work on some other unit. setting the timer at 90 results in a 7-10 minute cooldown and setting it to 18 results in about a 2-4 minute cooldown.
setting the timer at 0 or blank seems to either work correctly or never clear depending on some random factor it seems

### What did you expect to happen?

the timer should work in seconds according to the documentation

### How to reproduce it (minimal and precise)

pair ikea E1745 with Zigbee2MQTT
set occupancy timeout to 90
trigger motion sensor
notice sensor takes approximately 7-10 minutes to revert to clear

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDONGLE-P

**Comment by heinoskov** [comment]
I'm seeing the same issue with Philips Hue Motion Sensor and Smart Things sensors and its not consistent issues..Most of the time its working as supposed too...  
I have multiple sensors and its completely random when then timeout occur

![motion-sensors-occupancy-issue](https://user-images.githubusercontent.com/10467844/214523813-d6de96ec-a6bc-493e-a3c3-791537161194.jpg)

**Comment by SucubusJenny** [comment]
The issue gets weirder.. after I removed the spare sensor I was doing the testing with, the other sensor now has a different behavior with blank occupancy_timeout. It now will instantly or never clear when occupancy timeout I'd set to none

**Comment by SucubusJenny** [comment]
The Issue seems to have been due to a faulty clock sync between the VM and host causing time to run slowly in the VM with Home Assistant and Zigbee2MQTT. Closing due to not a bug with Zigbee2Mqtt
