### ISSUE TITLE
Heiman HS2WD-E errors

### ISSUE THREAD

**Issue by macha8a** [Koenkk/zigbee2mqtt#16347]
### What happened?

debug 2023-01-25 17:05:03Received MQTT message on 'zigbee2mqtt/Siren HS2WD-E/get' with data '{"mode":"","level":"","strobe_level":"","strobe":"","strobe_duty_cycle":"","duration":"","battery":""}'
error 2023-01-25 17:05:03No converter available for 'mode' ("")
error 2023-01-25 17:05:03No converter available for 'level' ("")
error 2023-01-25 17:05:03No converter available for 'strobe_level' ("")
error 2023-01-25 17:05:03No converter available for 'strobe' ("")
error 2023-01-25 17:05:03No converter available for 'strobe_duty_cycle' ("")
error 2023-01-25 17:05:03No converter available for 'duration' ("")
error 2023-01-25 17:05:03No converter available for 'battery' ("")

### What did you expect to happen?

Is there something to do to avoid that?

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSPv8

**Comment by luixal** [comment]
Duplicate of #14424 

Let's see if linking issues brings some attention on this issue.
