### ISSUE TITLE
 [New device support]: Xamento "Hue White and Color Ambiance GU10" (x3 pack) specific zigbeeModel number

### ISSUE THREAD

**Issue by aze827** [Koenkk/zigbee2mqtt#16387]
### Link

https://www.amazon.fr/gp/product/B09C3T16JL/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

### Database entry

{"id":66,"type":"Router","ieeeAddr":"0x001788010c96dab0","nwkAddr":10676,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003074801_01","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64514,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003074801_01","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":29972,"currentY":26871,"colorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1674825546990,"defaultSendRequestWhen":"immediate"}   ---  {"id":90,"type":"Router","ieeeAddr":"0x001788010c9ffd12","nwkAddr":47816,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003074801_02","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64514,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003074801_02","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":29972,"currentY":26871,"colorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1674825558605,"defaultSendRequestWhen":"immediate"}   ---  {"id":91,"type":"Router","ieeeAddr":"0x001788010c9ffc54","nwkAddr":13077,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929003074801_03","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64514,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003074801_03","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":29972,"currentY":26871,"colorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1674825458242,"defaultSendRequestWhen":"immediate"}

### Comments

Hi,

I encountered the same issue as #16105 when setting up a x3 pack of Xamento lights.
Each bulb show a specific _01 / _02 / _03 number, that I needed to add into /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/philips.js

Those numbers are  '929003074801_01', '929003074801_02', '929003074801_03', and the model is still 929001953101

Here is my updated philips.js snippet.

`    {
        zigbeeModel: ['LCG002', '929003047701', '929003074701', '929003074801_01', '929003074801_02', '929003074801_03'],
        model: '929001953101',
        vendor: 'Philips',
        description: 'Hue White and Color Ambiance GU10',
        extend: hueExtend.light_onoff_brightness_colortemp_color({
            colorTempRange: [153, 500], disableHueEffects: false,
        }),
    },
`

**Comment by Koenkk** [comment]
These will be supported in the 1 February release: https://github.com/Koenkk/zigbee-herdsman-converters/blob/af4a31b117140802f7fd5597252bee914c8eb257/devices/philips.js#L2939
