### ISSUE TITLE
Xiaomi Aqara Pet Feeder C1 ZNCWWSQ01LM: Various errors while setting >4 moments schedule. (outside buffer bounds, unknown attributes)

### ISSUE THREAD

**Issue by Gizzje** [Koenkk/zigbee2mqtt#16394]
### What happened?

While applying a schedule with 5 feeding moments, Z2M gives the error 'Attempt to access memory outside buffer bounds'

While applying a schedule with 6 feeding moments, Z2M gives the double warning 'Unknown attribute �' and 'Unknown attribute 0,7F = 7000300'

### What did you expect to happen?

Setting a schedule with multiple scheduled feeding moments without an error.

I do not know how many different feeding moments can normally be set with this feeder. The manual does not mention this and I don't have a Aqara-hub to test it with the Aqara app.

### How to reproduce it (minimal and precise)

Set a 4 item schedule. In my case:

- Everyday, hour 7, minute 0, size 3
- Everyday, hour 12, minute 0, size 3
- Everyday, hour 15, minute 0, size 2
- Everyday, hour 18, minute 0, size 3
Press apply. This should work without an error

Add a fifth moment:

- Everyday, hour 22, minute 0, size 3

Press apply. This should result in the error 'Attempt to access memory outside buffer bounds'

Add a sixth moment:
- Everyday, hour 23, minute 0, size 3

Press apply, this should result in various warnings (not outside buffer bounds, but two unknown attribute errors)

### Zigbee2MQTT version

1.29.2 

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10527040/log.txt)
[log6.txt](https://github.com/Koenkk/zigbee2mqtt/files/10527083/log6.txt)

**Comment by kirovilya** [comment]
try to repair your feeder
