### ISSUE TITLE
New Tuya commands for lightingColorCtrl cluster

### ISSUE THREAD

**Issue by mayongze** [Koenkk/zigbee2mqtt#16404]
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/22066360/212967529-66074707-4903-404b-8b0a-f93ad87c0d33.png">
red: unknown
yellow: onTransitionTime
green: offTransitionTime

https://github.com/Koenkk/zigbee-herdsman/blob/master/src/zcl/definition/cluster.ts
need to add command:
```
tuyaOnOffTransitionTime: {
    ID: 251,
    parameters: [
        { name: 'unknown', type: DataType.uint8 },
        { name: 'onTransitionTime' , type: DataType.uint24 },
        { name: 'offTransitionTime', type: DataType.uint24 },
    ],
},
```
The time uses the big-endian byte from the packet sniffed, but DataType.uint24 is the little-endian byte
DataType Whether a big-endian byte type is directly available?

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/22066360/212969594-f2b1f6b5-a360-4768-8ef5-786ff467de0e.png">

_Originally posted by @mayongze in https://github.com/Koenkk/zigbee2mqtt/discussions/16234_

**Comment by Koenkk** [comment]
Could you make a PR to add this?

**Comment by mayongze** [comment]
I'll make a PR for this, but I need to figure out if there's a big-endian type
60 ea 00 => DataType.uint24
00 ea 60 => ? (DataType.be_uint24)

**Comment by Koenkk** [comment]
Then a new datatype has to be added, example:

- https://github.com/Koenkk/zigbee-herdsman/blob/bb4f9fb5ad0255b98a4fb2b3cc03b3848aae8cf4/src/zcl/definition/cluster.ts#L220
- https://github.com/Koenkk/zigbee-herdsman/blob/bb4f9fb5ad0255b98a4fb2b3cc03b3848aae8cf4/src/zcl/definition/buffaloZclDataType.ts#L14
- https://github.com/Koenkk/zigbee-herdsman/blob/bb4f9fb5ad0255b98a4fb2b3cc03b3848aae8cf4/src/zcl/buffaloZcl.ts#L605
- https://github.com/Koenkk/zigbee-herdsman/blob/bb4f9fb5ad0255b98a4fb2b3cc03b3848aae8cf4/src/zcl/buffaloZcl.ts#L651

**Comment by andrei-lazarov** [comment]
Hello @mayongze, thanks for adding `tuyaOnOffTransitionTime`!
This is very useful, but it's not added to any devices, and it's never exposed to the user.

Can you tell me on what device you found it? `TS05xxx _TZ3xxx_xxxxxxxx`
I want to expose the setting.

I confirm it works on `TS0505B _TZ3210_ifga63rg` and `TS0505B _TZ3210_cieijuw1`.
But the Tuya app does not show it
