### ISSUE TITLE
Support motor speed for lumi.curtain.acn002 - Aqara Roller Shade Driver E1

### ISSUE THREAD

**Issue by akarabach** [Koenkk/zigbee2mqtt#16424]
### What happened?

Motor speed is not defined 

### What did you expect to happen?

Should be possible to se motor_speed

### Zigbee2MQTT version

1.29.2-1

### Adapter firmware version

20220219

### Adapter

Sonoff

**Comment by andyblac** [comment]
would like to see this aswel.

**Comment by akarabach** [comment]
still a problem
