### ISSUE TITLE
Possible to use dongle with a C2630 Chip?

### ISSUE THREAD

**Issue by psyciknz** [Koenkk/zigbee2mqtt#1642]
Just that, there not new devices with an Antennas and it a nicer housing, but they seem to run a C2630 chip.

https://s.click.aliexpress.com/e/bQeRXuHw?channel=twinner

Are these supportable?  Looking at moving off a Xiaomi Aqara Gateway.

**Comment by Koenkk** [comment]
Technically this is possible, you just need to compile a z-stack firmware for this.
