### ISSUE TITLE
state from rtczcgq11lm is wrong

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#16433]
### What happened?

https://github.com/Koenkk/zigbee-herdsman-converters/blob/cee48c8a56a19fc58a1519417e14989b68624173/devices/xiaomi.js#L1684

why is this a enum ???

**Comment by danieledwardgeorgehitchcock** [comment]
enum what is used by Z2M frontend to render buttons - it should still work properly via MQTT messages

**Comment by arteck** [comment]
lol
I would have expected a button

**Comment by danieledwardgeorgehitchcock** [comment]
[Here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/exposes.js#L175-L211) is all of the available item types that can be used in the exposes section - `enum` allows for button groups to be created as well as single buttons in the UI
