### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by notorioustubze** [Koenkk/zigbee2mqtt#16439]
### Is your feature request related to a problem? Please describe

929002422702 - Phillips Hue 55” Gradient light strip doesn’t display any options for Gradient control.

### Describe the solution you'd like

Add the new Gradient support options for this model.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by notorioustubze** [comment]
Amazing! Thank you so much.
