### ISSUE TITLE
[Feature request] Support whitelist devices

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/zigbee2mqtt#1643]
Now in z2m has support blacklist mode:
```
# Optional: ban devices from the network (by ieeeAddr)
ban:
  - '0x000b57fffec6a5b2'
```
But for some purpose like support livolo switch https://github.com/Koenkk/zigbee2mqtt/issues/592 and CC2650/2630 devices, those device sometime automatically leave the network (low link quality) and try to find new parent, make it disconnect with the network  with settings: "permit_join: false".

So i want an option like:

```
# Optional: whitelist devices from the network (by ieeeAddr)
whitelist:
  - '0x000b57fffec6a5b2'
```
and then i can always allow: "permit_join: true" but only with my devices from the whitelist.

**Comment by dmak** [comment]
I have noticed that devices not in whitelist are simply removed:
```
info  2022-06-01 07:20:44: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20201010,"transportrev":2},"type":"zStack30x"}'
warn  2022-06-01 07:20:44: Device which is not on passlist connected (0xd0df5efffe206e7d), removing...
warn  2022-06-01 07:20:54: Device which is not on passlist connected (0x00178d00a33ddfa7), removing...
warn  2022-06-01 07:21:04: Device which is not on passlist connected (0x00258d01048612d2), removing...
```
I would expect that already joined devices should be left in the database... Otherwise why not to combine whitelist with devices from `data/devices.yaml` or have some option to build a whitelist from that YAML? E.g.
```
whitelist: devices
```
