### ISSUE TITLE
[Feature request]: Lidl 14156506L battery state?

### ISSUE THREAD

**Issue by KentuckyMC** [Koenkk/zigbee2mqtt#16437]
### Is your feature request related to a problem? Please describe

I'm not sure if it's possible, but the Lidl 14156506L has a build-in battery. Is there any way to see how full it is? 

### Describe the solution you'd like

A new sensor for the lamp with battery percentage

### Describe alternatives you've considered

-

### Additional context

-

**Comment by tetsuo55** [comment]
Bump
