### ISSUE TITLE
Pairing Issue OSRAM Classic E27 Multicolor

### ISSUE THREAD

**Issue by ToIObroker** [Koenkk/zigbee2mqtt#1644]
Hi,

I could not find any solution to fix the issue with the OSRAM Classic E27 Multicolor.
I could different sensors from Xiaomi and a OSRAM plug, but I still do have issues to fully pair the LED.

Please have a look at the following picture.

![image](https://user-images.githubusercontent.com/51965247/59701251-7821b200-91f5-11e9-92b3-44988c5d55db.png)

I used the zigbee2mqtt adapter, which I could find in the iobroker search in github. I guess it´s from kirovilya - is that an issue? I bought a CC2531 from ebay with firmware flashed on basis of Koenkk. But the Koenkk adapter is not shown in the iobroker seach engine? Do I have to use the manual link?

I am using the latest version 0.11.0

Thanks in advance.

Regards
ToIObroker

**Comment by Koenkk** [comment]
Iobroker issues should be opened here: https://github.com/ioBroker/ioBroker.zigbee/issues
