### ISSUE TITLE
[New device support]: TuYa TS011F_plug_1 > zigbee_TZ3000_okaz9tjs

### ISSUE THREAD

**Issue by jgrzybowski94** [Koenkk/zigbee2mqtt#16453]
### Link

https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

### Database entry

{"id":10,"type":"Router","ieeeAddr":"0x70b3d52b6001bd6e","nwkAddr":3657,"manufId":4660,"manufName":"_TZ3000_okaz9tjs","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,6,3,4,5,57345,2820,1794],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":100}},"genOnOff":{"attributes":{"onOff":1,"moesStartUpOnOff":1,"tuyaBacklightMode":255}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":3,"dateCode":"20210625","swBuildId":"20B+TZSKT11BS108","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1675264741900,"defaultSendRequestWhen":"immediate"}

### Comments

Device paired OK, interview completed successfully.
However the device only reports link quality & on/off switch that is working, the power measurements remain N/A.

After searching is it exactly the same issue as reported here:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3107

However, this time the Zigbee Manufacturer is _TZ3000_ew3ldmgx

Zigbee Model: TS011F
Zigbee Manufacturer : _TZ3000_okaz9tjs
Description: Smart plug (with power monitoring)
Manufacturer: TuYa
Model: TS011F_plug_1

**Comment by Koenkk** [comment]
This should be fixed with z2m 1.30.0
