### ISSUE TITLE
ROBB smarrt ROB_200-007-0 reports 200% battery level

### ISSUE THREAD

**Issue by dkorbee** [Koenkk/zigbee2mqtt#16454]
### What happened?

ROBB smarrt ROB_200-007-0 device reports 200% battery level.
![image](https://user-images.githubusercontent.com/6647506/216093900-63c6347b-3d94-474b-b7db-87162f9c1331.png)

### What did you expect to happen?

battery level should never be more than 100%

### How to reproduce it (minimal and precise)

Just join/pair the device and it will directly reports wrong battery level.
Looks just like this issue: https://github.com/Koenkk/zigbee2mqtt/issues/15767

### Zigbee2MQTT version

1.29.2

### Adapter firmware version

20220219

### Adapter

Sonoff ZigBee 3.0 USB Dongle Plus (CC2652P)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
