### ISSUE TITLE
TS011F_plug_1

### ISSUE THREAD

**Issue by torsteinelv** [Koenkk/zigbee2mqtt#16457]
### What happened?

I have multiple TS011F_plug_1 and no other device wants to use this as a router? Have some devices that have to weak link to the coordinator to even work but they do not use these routers. Anyone know why?

### Zigbee2MQTT version

1.29.2-1

### Adapter firmware version

20210708

### Adapter

Sonoff

**Comment by torsteinelv** [comment]
no one knows about this?

**Comment by andyblac** [comment]
I have same issue, my Aqara Motion Sensors refuse to pair to it.
