### ISSUE TITLE
Crash on interview Home Assistant Yellow

### ISSUE THREAD

**Issue by hankanman** [Koenkk/zigbee2mqtt#16473]
### What happened?

Attempting to repair my network after switching to the new Home Assistant Yellow using the built in adapter. Some devices pair fine, but intermittently crashes whilst interviewing. Usually a so off device, this case was an snzb-03.

Running the add-on version and the add-on only starts 50% of the time too. Guessing something related to the yellow adapter?

### What did you expect to happen?

Interview to complete without crash

### How to reproduce it (minimal and precise)

Add a new device

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Home Assistant Yellow Internal Adapter

### Debug log

`{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:465:19)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)`

**Comment by denis-obukhov** [comment]
I have [similar issue](https://github.com/Koenkk/zigbee2mqtt/issues/18400) with SNZB-03 motion sensor
