### ISSUE TITLE
How Define Self-Defined Cluster

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#1647]
Hi friends,
I want to add a self-defined cluster with a specific Manufacture Code. how can I do that?

**Comment by msadeghz** [comment]
I have a new device which is HA v1.2 and joined successfully on zigbee2mqtt. I want to send it a  command to a self-defined cluster. how can I do that? 
@Koenkk , don't you know how I can find the procedure?

**Comment by Koenkk** [comment]
You can define the `cid` as hex like done with `attrId` here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js#L906

**Comment by msadeghz** [comment]
> You can define the `cid` as hex like done with `attrId` here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js#L906

thank you, I will try and let others know.

**Comment by Koenkk** [comment]
Good! I will close this as it's not an issue, but feel free to ask any other questions.

**Comment by Arminhosseini** [comment]
Hi,
I'm using a new device that has a self_defined cluster with a specific Manufacture Code and joined successfully to zigbee2mqtt.
I'm trying to send a command to a self-defined cluster and I got an error.
Here are my code and error
![zcl](https://user-images.githubusercontent.com/15074910/64107777-86ad4d80-cd90-11e9-953b-298f426b82bb.PNG)
![zcl-2](https://user-images.githubusercontent.com/15074910/64107780-890fa780-cd90-11e9-99b5-d72150f75ae0.PNG)
