### ISSUE TITLE
1.30 update leads to a white web page 

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#16476]
### What happened?

I've updated the HA addon to 1.30-1 and after a couple of hours I've opened the Zigbee2MQTT page. It is only showing a white page.

https://photos.app.goo.gl/hBx7Ro6Ys5Ln6CGQ6

### What did you expect to happen?

Normal GUI

### How to reproduce it (minimal and precise)

Open the menu point in HA for Zigbee2MQTT

### Zigbee2MQTT version

1.30-1

### Adapter firmware version

20220219

### Adapter

Slaesh's CC2652RB stick

**Comment by RubenKelevra** [comment]
After restarting the add-on the web GUI loads again.

**Comment by dickthespoon** [comment]
I also have the issue and no amount of restarting the add-on or completely rebooting the host device will fix it. For me the screen remains blank.
