### ISSUE TITLE
QS-Zigbee-S04-2C-LN two gang switch gets recognized as zemismart 3 gand

### ISSUE THREAD

**Issue by mihaimdinca** [Koenkk/zigbee2mqtt#16485]
### What happened?

I have 2 QS-Zigbee-S04-2C-LN linked to z2m. One gets correctly recognized (_TYZB01_zsl6z0pw) while the other one gets recognized as ZM-L03E-Z (_TYZB01_uqkphoed). I am currently on version 1.30-1 of the z2m home assistant addon. I tried deleting and pairing the device again. Not working. Same result.

### What did you expect to happen?

Both devices should be recognized as QS-Zigbee-S04-2C-LN

### How to reproduce it (minimal and precise)

Try to pair device to z2m

### Zigbee2MQTT version

1.30.0-1

### Adapter firmware version

20221226

### Adapter

Sonoff ZigBee Dongle 3.0 zStack3x0

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by mihaimdinca** [comment]
Thank you!
