### ISSUE TITLE
Moes BHT-002: Unrecognized DP #102 message for BSeed device _TZE200_5toc8efa 

### ISSUE THREAD

**Issue by x5500** [Koenkk/zigbee2mqtt#16499]
### What happened?

Got repeated warning in zigbee2mqtt logs for suported device:
Warning 2023-02-03 10:01:46zigbee-herdsman-converters:Moes BHT-002: Unrecognized DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,205]}}

Device:
Zigbee2MQTT

0x003c84fffed332e6
About
Exposes
Bind
Reporting
Settings
Settings (specific)
State
Clusters
Scene
Dev console

Friendly name
0x003c84fffed332e6
Description
Last seen
54 seconds ago
Availability
Disabled
Device type
Router
Zigbee Model
TS0601
Zigbee Manufacturer
_TZE200_5toc8efa
Description
BSEED Room Thermostat Electric Heating
Support status
Supported

IEEE Address
0x003c84fffed332e6
Network address
0x55E2
Manufacturer
BSEED
Model
HTEZ
Power

### What did you expect to happen?

No annoying warnings

### How to reproduce it (minimal and precise)

Just add device to zigbee network

### Zigbee2MQTT version

1.29.2 commit: 1402139

### Adapter firmware version

20210708

### Adapter

zStack3x0 SONOFF ZB Dongle-P

### Debug log

Debug 2023-02-03 10:17:40Received Zigbee message from '0x003c84fffed332e6', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,205],"type":"Buffer"},"datatype":2,"dp":102}],"seq":25088}' from endpoint 1 with groupID 0
Warning 2023-02-03 10:17:40zigbee-herdsman-converters:Moes BHT-002: Unrecognized DP #102 with data {"dp":102,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,205]}}
Info 2023-02-03 10:17:40MQTT publish: topic 'zigbee2mqtt/0x003c84fffed332e6', payload '{"child_lock":"LOCK","current_heating_setpoint":21,"deadzone_temperature":14,"heat":"OFF","last_seen":"2023-02-03T07:17:39.758Z","linkquality":57,"local_temperature":20.5,"local_temperature_calibration":5,"max_temperature":320,"max_temperature_limit":32,"min_temperature_limit":14,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":220,"saturday_p1_minute":23,"saturday_p1_temperature":0,"saturday_p2_hour":0,"saturday_p2_minute":190,"saturday_p2_temperature":null,"saturday_p3_temperature":null,"saturday_p4_temperature":null,"sunday_p1_temperature":null,"sunday_p2_temperature":null,"sunday_p3_temperature":null,"sunday_p4_temperature":null,"weekdays_p1_hour":7,"weekdays_p1_minute":8,"weekdays_p1_temperature":0,"weekdays_p2_hour":0,"weekdays_p2_minute":205,"weekdays_p2_temperature":5,"weekdays_p3_hour":0,"weekdays_p3_minute":0,"weekdays_p3_temperature":110,"weekdays_p4_hour":18,"weekdays_p4_minute":0,"weekdays_p4_temperature":0},"running_state":"idle","sensor":"OU","system_mode":"off"}'

**Comment by kds69** [comment]
same here

**Comment by VoltickVL** [comment]
I have same problem...
