### ISSUE TITLE
Unsupported device with Zigbee model 'ID Lock 150' and manufacturer name 'Datek'

### ISSUE THREAD

**Issue by davidkson** [Koenkk/zigbee2mqtt#16500]
### What happened?

After the latest release 1.30.0-1 Zigbee model 'ID Lock 150' shows as unsupported and it's not possible to communicate with the lock through Home Assistant

### What did you expect to happen?

To work as before

### How to reproduce it (minimal and precise)

Install 1.30.0-1

### Zigbee2MQTT version

1.30.0-1

### Adapter firmware version

20211217

### Adapter

Sonoff 3.0

**Comment by thrawnarn** [comment]
I have the same problem :(

**Comment by Koenkk** [comment]
Will be fixed in tomorrows hotfix release.

**Comment by odinr** [comment]
I have the same issue, can't find any hotfix or commit for this issue

**Comment by davidkson** [comment]
Iam running the "Edge"-version right now and then the ID Lock works as before
