### ISSUE TITLE
Add support for LWF002

### ISSUE THREAD

**Issue by jvdpas** [Koenkk/zigbee2mqtt#1650]
Added the below code to devices.js  reboot and tested. Switching on off an dimming ok.
`    {
        zigbeeModel: ['LWF002'],
        model: '9290011370B',
        vendor: 'Philips',
        description: 'Hue white A60 bulb E27',
        extend: hue.light_onoff_brightness,
    },
`
6/19/2019, 7:38:05 PM - info: Lamp_wit_1 (0x001788010402490b): 9290011370B - Philips Hue white A60 bulb E27 (Router)
6/19/2019, 7:43:32 PM - info: MQTT publish: topic 'zigbee2mqtt/Lamp_wit_1', payload '{"state":"ON","linkquality":52,"brightness":30}'
6/19/2019, 7:43:35 PM - info: MQTT publish: topic 'zigbee2mqtt/Lamp_wit_1', payload '{"state":"OFF","linkquality":55,"brightness":0}'

![20190619_192837](https://user-images.githubusercontent.com/47483325/59788916-19c80280-92cd-11e9-9296-157551da5c42.jpg)

**Comment by Koenkk** [comment]
Thanks! will be supported in the dev branch in a few hours.
