### ISSUE TITLE
Woox R9077 (TS0505A) power_on_behaviour not working

### ISSUE THREAD

**Issue by buzzcz** [Koenkk/zigbee2mqtt#16505]
### What happened?

Basically a duplicate for https://github.com/Koenkk/zigbee2mqtt/issues/15554 but with a Woox R9077 light.
The power_on_behaviour throws an `UNSUPPORTED_ATTRIBUTE`

### What did you expect to happen?

The correct value is set and the power on behaviour is changed. The correct

### How to reproduce it (minimal and precise)

Add Woox R9077 to Z2MQTT, open the 'Exposes' tab and change the 'power_on_behaviour' value.

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

20220219

### Adapter

Sonoff ZB Dongle-P

### Debug log

```
Publish 'set' 'power_on_behavior' to 'Světlo kuchyně' failed: 'Error: Write 0x588e81fffede3689/1 genOnOff({"startUpOnOff":255}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

**Comment by Koenkk** [comment]
This will be fixed together with https://github.com/Koenkk/zigbee2mqtt/issues/16325
