### ISSUE TITLE
Zigbee2Mqtt kept randomly restarted every now and then

### ISSUE THREAD

**Issue by fliptoback** [Koenkk/zigbee2mqtt#16512]
### What happened?

I am using the latest zigbee2mqtt image via docker on a synology NAS - alongside home-assistant running via its own docker container. Zigbee2mqtt kept restarting every now and then - it is very random and there are no error logs.

### What did you expect to happen?

Zigbee2mqtt do not restart by itself - it should run stable

### How to reproduce it (minimal and precise)

First start docker container for zigbee2mqtt
zigbee2mqtt restart randomly afterwards

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

20190608

### Adapter

CC2531 zigbee dongle

### Debug log

debug 2023-02-04 08:00:06: Loaded state from file /app/data/state.json
info  2023-02-04 08:00:06: Logging to console and directory: '/app/data/log/2023-02-04.08-00-06' filename: log.txt
debug 2023-02-04 08:00:06: Removing old log directory '/app/data/log/2023-02-03.17-59-30'
info  2023-02-04 08:00:06: Starting Zigbee2MQTT version 1.30.0 (commit #8f781db)
info  2023-02-04 08:00:06: Starting zigbee-herdsman (0.14.89)
debug 2023-02-04 08:00:06: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
info  2023-02-04 08:00:07: zigbee-herdsman started (resumed)
info  2023-02-04 08:00:07: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
debug 2023-02-04 08:00:07: Zigbee network parameters: {"channel":25,"extendedPanID":"0x00124b0018e86f98","panID":6754}
info  2023-02-04 08:00:07: Currently 2 devices are joined:
info  2023-02-04 08:00:07: Garage wireless switch (0x00158d0004a02f90): WXKG01LM - Xiaomi MiJia wireless switch (EndDevice)
info  2023-02-04 08:00:07: PIR sensor1 (0x00158d00015caaa8): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
warn  2023-02-04 08:00:07: `permit_join` set to  `true` in configuration.yaml.
warn  2023-02-04 08:00:07: Allowing new devices to join.
warn  2023-02-04 08:00:07: Set `permit_join` to `false` once you joined all devices.
info  2023-02-04 08:00:07: Zigbee: allowing new devices to join.
info  2023-02-04 08:00:08: Connecting to MQTT server at mqtt://192.168.1.111:1883
debug 2023-02-04 08:00:08: Using MQTT login with username: hass
debug 2023-02-04 08:00:08: Using MQTT client ID: 'zigbee2mqtt'
info  2023-02-04 08:00:08: Connected to MQTT server
info  2023-02-04 08:00:08: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-02-04 08:00:08: Started frontend on port 0.0.0.0:8808
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"Garage wireless switch battery","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/action/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"Garage wireless switch action","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"Garage wireless switch voltage","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/power_outage_count/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"name":"Garage wireless switch power outage count","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Garage wireless switch linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d0004a02f90/click/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"icon":"mdi:toggle-switch","name":"Garage wireless switch click","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_click_zigbee2mqtt","value_template":"{{ value_json.click }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d00015caaa8/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"PIR sensor1 battery","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/binary_sensor/0x00158d00015caaa8/occupancy/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"motion","name":"PIR sensor1 occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d00015caaa8/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"PIR sensor1 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d00015caaa8/power_outage_count/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":true,"name":"PIR sensor1 power outage count","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'homeassistant/sensor/0x00158d00015caaa8/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"PIR sensor1 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-02-04 08:00:08: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2023-02-04 08:00:08: MQTT publish: topic 'zigbee2mqtt/Garage wireless switch', payload '{"action":null,"battery":100,"click":null,"device":{"applicationVersion":10,"friendlyName":"Garage wireless switch","ieeeAddr":"0x00158d0004a02f90","manufacturerID":4151,"manufacturerName":"LUMI","model":"WXKG01LM","networkAddress":10972,"powerSource":"Battery","type":"EndDevice"},"linkquality":null,"power_outage_count":151,"voltage":3002}'
info  2023-02-04 08:00:08: MQTT publish: topic 'zigbee2mqtt/PIR sensor1', payload '{"battery":100,"device":{"applicationVersion":11,"friendlyName":"PIR sensor1","ieeeAddr":"0x00158d00015caaa8","manufacturerID":4151,"manufacturerName":"LUMI","model":"RTCGQ01LM","networkAddress":18926,"powerSource":"Battery","type":"EndDevice"},"linkquality":null,"occupancy":false,"power_outage_count":53,"voltage":3035}'
info  2023-02-04 08:00:08: Zigbee2MQTT started!
debug 2023-02-04 08:00:08: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"dddce57","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0x00124b0018e86f98","panID":6754},"permit_join":true,"version":"1.29.0"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'zigbee2mqtt/901/availability' with data 'online'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"Garage wireless switch battery","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"Garage wireless switch action","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"Garage wireless switch voltage","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/power_outage_count/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"name":"Garage wireless switch power outage count","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Garage wireless switch linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/click/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"icon":"mdi:toggle-switch","name":"Garage wireless switch click","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_click_zigbee2mqtt","value_template":"{{ value_json.click }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"PIR sensor1 battery","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"PIR sensor1 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/power_outage_count/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":true,"name":"PIR sensor1 power outage count","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"PIR sensor1 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/device_automation/0x00158d0004a02f90/action_single/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"payload":"single","subtype":"single","topic":"zigbee2mqtt/Garage wireless switch/action","type":"action"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/device_automation/0x00158d0004a02f90/click_single/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"payload":"single","subtype":"single","topic":"zigbee2mqtt/Garage wireless switch/click","type":"click"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/device_automation/0x00158d0004a02f90/action_hold/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"payload":"hold","subtype":"hold","topic":"zigbee2mqtt/Garage wireless switch/action","type":"action"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/device_automation/0x00158d0004a02f90/click_long/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"payload":"long","subtype":"long","topic":"zigbee2mqtt/Garage wireless switch/click","type":"click"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/binary_sensor/0x00158d00015caaa8/occupancy/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"motion","name":"PIR sensor1 occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"Garage wireless switch battery","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/action/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"icon":"mdi:gesture-double-tap","name":"Garage wireless switch action","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_action_zigbee2mqtt","value_template":"{{ value_json.action }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"Garage wireless switch voltage","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/power_outage_count/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":true,"name":"Garage wireless switch power outage count","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Garage wireless switch linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d0004a02f90/click/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0004a02f90"],"manufacturer":"Xiaomi","model":"MiJia wireless switch (WXKG01LM)","name":"Garage wireless switch"},"icon":"mdi:toggle-switch","name":"Garage wireless switch click","state_topic":"zigbee2mqtt/Garage wireless switch","unique_id":"0x00158d0004a02f90_click_zigbee2mqtt","value_template":"{{ value_json.click }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","name":"PIR sensor1 battery","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/binary_sensor/0x00158d00015caaa8/occupancy/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"motion","name":"PIR sensor1 occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"PIR sensor1 voltage","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/power_outage_count/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":true,"name":"PIR sensor1 power outage count","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_power_outage_count_zigbee2mqtt","value_template":"{{ value_json.power_outage_count }}"}'
debug 2023-02-04 08:00:08: Received MQTT message on 'homeassistant/sensor/0x00158d00015caaa8/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00015caaa8"],"manufacturer":"Xiaomi","model":"MiJia human body movement sensor (RTCGQ01LM)","name":"PIR sensor1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"PIR sensor1 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/PIR sensor1","unique_id":"0x00158d00015caaa8_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2023-02-04 08:05:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:10:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:14:44: Received Zigbee message from 'PIR sensor1', type 'attributeReport', cluster 'genBasic', data '{"65282":[{"elmType":16,"elmVal":1},{"elmType":33,"elmVal":3035},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,2]},{"elmType":33,"elmVal":54},{"elmType":32,"elmVal":81}]}' from endpoint 1 with groupID 0
debug 2023-02-04 08:14:44: lumi.sensor_motion: Processed data into payload {"voltage":3035,"battery":100,"power_outage_count":53}
info  2023-02-04 08:14:44: MQTT publish: topic 'zigbee2mqtt/PIR sensor1', payload '{"battery":100,"device":{"applicationVersion":11,"friendlyName":"PIR sensor1","ieeeAddr":"0x00158d00015caaa8","manufacturerID":4151,"manufacturerName":"LUMI","model":"RTCGQ01LM","networkAddress":18926,"powerSource":"Battery","type":"EndDevice"},"linkquality":73,"occupancy":false,"power_outage_count":53,"voltage":3035}'
debug 2023-02-04 08:15:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:18:02: Received MQTT message on 'homeassistant/status' with data 'offline'
debug 2023-02-04 08:18:49: Received MQTT message on 'homeassistant/status' with data 'online'
info  2023-02-04 08:19:19: MQTT publish: topic 'zigbee2mqtt/Garage wireless switch', payload '{"action":null,"battery":100,"click":null,"device":{"applicationVersion":10,"friendlyName":"Garage wireless switch","ieeeAddr":"0x00158d0004a02f90","manufacturerID":4151,"manufacturerName":"LUMI","model":"WXKG01LM","networkAddress":10972,"powerSource":"Battery","type":"EndDevice"},"linkquality":null,"power_outage_count":151,"voltage":3002}'
info  2023-02-04 08:19:19: MQTT publish: topic 'zigbee2mqtt/PIR sensor1', payload '{"battery":100,"device":{"applicationVersion":11,"friendlyName":"PIR sensor1","ieeeAddr":"0x00158d00015caaa8","manufacturerID":4151,"manufacturerName":"LUMI","model":"RTCGQ01LM","networkAddress":18926,"powerSource":"Battery","type":"EndDevice"},"linkquality":73,"occupancy":false,"power_outage_count":53,"voltage":3035}'
debug 2023-02-04 08:20:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:25:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:30:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:35:06: Saving state to file /app/data/state.json
debug 2023-02-04 08:40:06: Saving state to file /app/data/state.json

**Comment by lux73** [comment]
CC2531 are not recommend anymore - they are weak.

in addition your Firmware on your Stick is from 2019 please update at least to the latest one: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default

but i would not spend any time with it - buy a new CC2652x Stick. they are very powerful & stable (but be aware to buy a Sonoff Dongle E - experimental Firmware, not so stable afaik)
