### ISSUE TITLE
Zigbee2MQTT on Linux

### ISSUE THREAD

**Issue by amgstone** [Koenkk/zigbee2mqtt#16547]
### What happened?

![romanraspberrypi opt](https://user-images.githubusercontent.com/63303107/216838114-5971dc48-2742-48d8-a33f-c8e8ec307679.jpg)

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20210319

### Adapter

CC2538

**Comment by dragondagda** [comment]
@amgstone can you add some logs, i.e. by executing `journalctl -u zigbee2mqtt.service` ?

**Comment by ristoavila** [comment]
status=200/CHDIR means that systemd can't access the directory which you have specified in the service configuration. Do you have typo there or is it missing or wrong access rights?

**Comment by amgstone** [comment]
already done everything, everything is fine. what command to update zigbee2mqtt?

**Comment by ristoavila** [comment]
Depends how you installed zigbee2mqtt. If you installed it directly using git please see https://www.zigbee2mqtt.io/guide/installation/01_linux.html#for-later-update-zigbee2mqtt-to-the-latest-version otherwise refer to other guides.

**Comment by amgstone** [comment]
how to make automatic start?
