### ISSUE TITLE
[Feature request]: Settings for the DDS238-2 IVAP

### ISSUE THREAD

**Issue by mihaimdinca** [Koenkk/zigbee2mqtt#16559]
### Is your feature request related to a problem? Please describe

It would be really useful if there was a way to set the parameters of the device (overvoltage, undervoltage, recovery time and so on) without using the Tuya ZigBee Gateway (which I don't have).

### Describe the solution you'd like

Some entities that had values that could be set for the main settings.

### Describe alternatives you've considered

I am not aware of a configuration possibility using the physical button (like with the DDS238-4 W)

### Additional context

The device manual indicates that these parameters can be set from the Tuya app.

**Comment by unCleanCode** [comment]
+1
