### ISSUE TITLE
SA-003-Zigbee exposing a non existent power_on_behavior field

### ISSUE THREAD

**Issue by Ulrar** [Koenkk/zigbee2mqtt#16569]
### What happened?

We bought a bunch of generic SA-003-UK-Zigbee plugs, with no brand name.

They work fine with Z2M (on/off) and they get recognized as 'SA-003-Zigbee' from the brand `eWeLink`, which definitely does not appear on the box.

Rhe power_on_behavior cannot be get nor set, because the plug itself doesn't seem to support it : 

```
Publish 'set' 'power_on_behavior' to 'Plug - Bedroom Blue - Nightstand' failed: 'Error: Write 0x00124b00246cab53/1 genOnOff({"startUpOnOff":255}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

I don't know if that's a difference between the EU / US and UK variants or something else, but these just don't see to support it.

### Zigbee2MQTT version

1.30

### Adapter firmware version

20221226

### Adapter

zStack3x0 - tubeszb-cc2652 PoE model over TCP

**Comment by Koenkk** [comment]
Not supported by the plug it seems, I removed it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
