### ISSUE TITLE
Zigbee2MQTT found my Nous A1Z plugs, but not come up in Mosquitto Broker?

### ISSUE THREAD

**Issue by copadewe** [Koenkk/zigbee2mqtt#16562]
### What happened?

i have 2 Plugs of the NOUS A1Z - worked fine so far. I ordered 4 more and was easy, plug in start searching found and is booked in zigbee2mqtt. But the new ones never appear in Mosquitto Broker.
I tried several times to connect new, with deleting before, without deleet, but no, not came up.
So i deinstalled Z2MQTT and Mosquitto - start the system new, install again, in Z2Mqtt all came up, perfectly. But no i have nothing in Mosquitto. also not the old ones.
Something in the communication must be wrong i think.
Because it worked I don´t have more ideas to solve this.
![grafik](https://user-images.githubusercontent.com/118108456/217076787-fcdb90b1-32ea-4ce1-b366-3ae368e57ff9.png)
It seams like, z2mqtt can´t communicate with the broker
What you need and where I found what you need to maybe assist me?
Also now, when I restart the Z2MQTT is not running - i must make start manually

### What did you expect to happen?

Mosquitto should find the z2mqtt items :-)

### How to reproduce it (minimal and precise)

.

### Zigbee2MQTT version

 1.30.1-1

### Adapter firmware version

 Home Assistant 2023.2.2 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230202.0 - latest 

### Adapter

Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Zigbee2MQTT:info  2023-02-06 21:36:33: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-02-06 21:36:34: Connecting to MQTT server at mqtt://core-mosquitto:1883
Zigbee2MQTT:error 2023-02-06 21:36:34: MQTT error: connect ECONNREFUSED 172.30.33.0:1883
Zigbee2MQTT:error 2023-02-06 21:36:34: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2023-02-06 21:36:34: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2023-02-06 21:36:35: MQTT error: connect ECONNREFUSED 172.30.33.0:1883
Zigbee2MQTT:error 2023-02-06 21:36:36: MQTT error: connect ECONNREFUSED 172.30.33.0:1883
Zigbee2MQTT:error 2023-02-06 21:36:37: MQTT error: connect ECONNREFUSED 172.30.33.0:1883

**Comment by danieledwardgeorgehitchcock** [comment]
The `ECONNREFUSED` error means there is an issue between Z2M and MQTT. Could you check your configuration in both to ensure you have the correct IP, Port and user policy / credentials?
