### ISSUE TITLE
HC-SLM-1 Lock

### ISSUE THREAD

**Issue by onelius** [Koenkk/zigbee2mqtt#16561]
### Is your feature request related to a problem? Please describe

Missing functions for the HC-SLM-1 lock.

- Action_user
- Pin_code

### Describe the solution you'd like

If possible it would be good if these functions could be added to this device.

### Describe alternatives you've considered

Any of the functions would be great.

### Additional context

I have a HC-SLM-1 lock and it works nice with zigbee2mqtt in HA, but i'm missing some functions that i hade when i was running zha on HA. There it was possible to see witch user unlocked the lock, and set pincodes for users.

**Comment by nagydavid** [comment]
It has been fixed.
