### ISSUE TITLE
QS-Zigbee-C01 and QS-Zigbee-C03 Problems in last versions

### ISSUE THREAD

**Issue by antunespa** [Koenkk/zigbee2mqtt#16593]
### What happened?

Curtain modules QS-Zigbee-C01 and QS-Zigbee-C03 after 1.30* updates dont report state correctly, when open or closing dont send percentage of the state and when stop close only show closing and after a long time refresh state to closed, the modules are not reporting the state correctly in version 1.29.2-1 everything works like expected, returned do previous version from backup.

### Zigbee2MQTT version

1.30.*

### Adapter firmware version

20210120

### Adapter

Slaesh's CC2652RB

**Comment by fjterrada69** [comment]
Something similar happens to me. It seems that the device tries to connect to the coordinator before the router devices that are closer.
