### ISSUE TITLE
Sengled E11-N14A and E11-G13 - power_on_behavior is an unsupported attribute

### ISSUE THREAD

**Issue by lravelo** [Koenkk/zigbee2mqtt#16599]
### What happened?

I have an issue with this [bulb](https://www.zigbee2mqtt.io/devices/E11-N13_E11-N13A_E11-N14_E11-N14A.html) and this [bulb](https://www.zigbee2mqtt.io/devices/E11-G13.html#sengled-e11-g13) . Both have the power_on_behavior attribute listed as supported yet when I try to set it in zigbee2mqtt it gives me this error 
![5097DFB8-0893-448A-B3C2-2F50D98E1A6B](https://user-images.githubusercontent.com/17074683/217829850-57fa01d5-794a-4bde-aba9-ea56f6af4de6.jpeg)
Repairing the bulbs didn't fix this issue. I just recently upgraded to 1.30.1 and that didn't fix it either.

### What did you expect to happen?

I expect that a value for this attribute can be set

### How to reproduce it (minimal and precise)

Reproducible on every attempt to set the value for the power_on_behavior attritbute

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20210708

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by Koenkk** [comment]
thanks, disabled it (for all Sengled bulbs)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
