### ISSUE TITLE
[Feature request]: expose current brightness level

### ISSUE THREAD

**Issue by martindinicolino** [Koenkk/zigbee2mqtt#16644]
### Is your feature request related to a problem? Please describe

I've recently been moving from HomeKit to HomeAssistant, this includes getting rid of all zigbee hubs of different brands and consolidating all zigbee devices with the help of Zigbee2Mqtt (so far so good, my zigbee devices have never been this reliable and the network is extremely stable - thank you, great job).

The thing is that in HomeKit i had the ability to easily toggle a light between two different sets of brightness, by retrieving the light‘s current brightness percentage and using it as a condition for an if statement, but i don’t know how to recreate this functionality from within Home Assistant.

### Describe the solution you'd like

It would be great if each bulb/lamp could expose it‘s current brightness level to Home Assistant.
As I can see from the dashboard view, Zigbee2Mqtt is already able to retrieve this information, but I haven‘t been able to use it in my automations.

### Describe alternatives you've considered

I‘ve tried looking for a brightness state within Home Assistant, but I haven‘t been able to find it there.

### Additional context

Thank you for your work with creating and maintaining this platform.

I tried checking if this has been mentioned before, i apologise in advance in case this turns out to be a duplicate issue, or a very simple solution. 

Any help is highly appreciated.

**Comment by junosuarez** [comment]
Hi @martindinicolino! As you mention, zigbee2mqtt already stores the current brightness in the device state (which you can see from the zigbee2mqtt web interface). If I understand what you're trying to achieve correctly, you might have better luck asking at Home Assistent how they can make use of the brightness state exposed by zigbee2mqtt.
