### ISSUE TITLE
TV02-Zigbee: Exception while calling fromZigbee converter: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]

### ISSUE THREAD

**Issue by KalleKal** [Koenkk/zigbee2mqtt#16648]
### What happened?

Once in a minute the error message "Exception while calling fromZigbee converter: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]" shows up. What can I do to determine where it comes from? I am absolutely clueless where to dig in.

### Zigbee2MQTT version

1.30.1-1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

Error: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object] at Object.from (/app/node_modules/zigbee-herdsman-converters/lib/tuya.js:1232:35) at Object.convert (/app/node_modules/zigbee-herdsman-converters/lib/tuya.js:1742:57) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:525:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27) at Controller.emit (node:events:513:28) at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14) at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:726:18) at DeconzAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70)

**Comment by guandalf** [comment]
This is happening to me as well... seems like something is wrong when the valve is set in holiday mode. Maybe it's returning a mode that's not supported?
