### ISSUE TITLE
[Feature request]: Danalock OTA-Updates

### ISSUE THREAD

**Issue by Schluggi** [Koenkk/zigbee2mqtt#16655]
### Is your feature request related to a problem? Please describe

I was recently in contact with the Danalock-support and asked for publicly available firmware files for OTA-Updates. 
Today a got a mail: 
"I promised to let you know when the Zigbee firmware update files and program were online. [...]"

https://danalock.com/zigbee-firmware-update

### Describe the solution you'd like

Providing OTA-Updates for the Danalock V3.

### Describe alternatives you've considered

-

### Additional context
"Please be extra careful NOT to update a Danalock Zigbee 1.2 (model name: V3-BTZB) with the main module firmware (vers 0.21.0) – the one we mention as early access on the page.

If you scan the QR code inside the battery cover you should get a Prod. Date (Production date) – if that date is after 1st of Marts 2021, then the lock is the new Zigbee 3.0 version.

In the first few productions, we sadly printed the wrong model name (the old one) – labeling them as V3-BTZB and not as they should have been labeled V3-BTZBE.

This new update (Both main module and Zigbee module firmware) are NOT compatible with the the old version of the Zigbee lock (V3-BTZB – Zigbee 1.2)" - Danalock Support

**Comment by Schluggi** [comment]
I just found out, how OTA updates in zigbee2mqtt work and created a PR: https://github.com/Koenkk/zigbee-OTA/pull/258

**Comment by Schluggi** [comment]
@Koenkk 
After you merged https://github.com/Koenkk/zigbee-OTA/pull/258 is there anything else to do? How can I help?

My Danalock is not shown up at the OTA menu yet.

**Comment by Koenkk** [comment]
I've enabled the OTA, it will be available in the next release (1 march) and the dev branch in a few hours from now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
