### ISSUE TITLE
HA: MQTT devices become unavailable 

### ISSUE THREAD

**Issue by rbeumer** [Koenkk/zigbee2mqtt#16652]
### What happened?

I upgraded to 1.30.1 and after a day or so (I think) all Zigbee devices connected through Z2M became unavailable. They were working directly through Z2M so it was not a Zigbee related issue. After some troubleshooting I've downgraded to 1.29 and everything is working again.

Please see this topic for more information: https://github.com/home-assistant/core/issues/87929#issuecomment-1427020330

### How to reproduce it (minimal and precise)

Run Z2M 1.30.1

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

0x26580700

### Adapter

Conbee2

**Comment by Anroxo** [comment]
Same here.

**Comment by L-E-0-N** [comment]
Same, happend twice now. The add-on stops running and even though Watchdog is active it ain't activating itself again. When I start the add-on manually the devices become available again.
