### ISSUE TITLE
SONOFF Zigbee Dongle-P doesn't stay connected as a ROUTER - goes offline

### ISSUE THREAD

**Issue by jcat59** [Koenkk/zigbee2mqtt#16663]
I flashed my dongle successfully with the below command and had it working as a router. The problem is that after awhile (from a few minutes to a few hours) the router will go offline and no longer be responsive. From my research - the way to fix this is to configure the device to report periodically to the coordinator (around 4 minutes). I’m not sure if this is related or true or not. The router has never stayed online enough for any device to connect to it (other than coordinator).

Is there some way I can update the device to report to the coordinator so it doesn't go offline? If I have to reflash, can you guide me how I can alter the command line below? -- -command line uses a script here https://github.com/JelmerT/cc2538-bsl/issues/134 to load the firmware to my sonoff.

python cc2538-bsl.py -p COM3 -evw --ieee-address 00:12:4b:00:01:4d:12:34 --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_router_20221102.hex

I'm using ZHA in home assistant just in case that makes any difference.

**Comment by teskanoo** [comment]
I am experiencing the same - the ZHA network map in homeassistant indicates many connections to the dongle but the dongle itself shows as offline

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65863752/866626d3-6bf8-42bf-b743-92eb1cb15811)

**Comment by Ramonix07** [comment]
I have the same problem and I don't know how to solve it. Update sign to CC1352P2_CC2652P_launchpad_router_20221102.hex and sonoff zigbee 3.0 usb dongle plus.

**Comment by Ramonix07** [comment]
This is a router sonoff zigbee 3.0 usb dongle plus, with firmware CC1352P2_CC2652P_launchpad_router_20221102.hex
![Ruter_Zigbee](https://github.com/Koenkk/zigbee2mqtt/assets/125493679/eb904a5e-08ae-4e2d-898c-0680785205f3)
