### ISSUE TITLE
[New device support]: RFPR-ZB-SH-EU Bosch Motion Sensor

### ISSUE THREAD

**Issue by dan3o3** [Koenkk/zigbee2mqtt#16665]
### Link

https://zigbee.blakadder.com/Bosch_RFDL-ZB-MS.html

### Database entry

{"id":23,"type":"Router","ieeeAddr":"0x847127fffe1cd420","nwkAddr":50134,"manufId":4617,"manufName":"BOSCH","powerSource":"Mains (single phase)","modelId":"RBSH-SP-ZB-EU","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,1794,2820,2821],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"RBSH-SP-ZB-EU","manufacturerName":"BOSCH","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20201010","swBuildId":"2.5"}},"genOnOff":{"attributes":{"onOff":0,"startUpOnOff":0}},"seMetering":{"attributes":{"multiplier":1,"divisor":100,"currentSummDelivered":[0,0]}},"haElectricalMeasurement":{"attributes":{"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x680ae2fffe8d8510","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x680ae2fffe8d8510","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x680ae2fffe8d8510","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[0,1]},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20201010","swBuildId":"2.5","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-636797146},"lastSeen":1676325136170,"defaultSendRequestWhen":"immediate"}

### Comments

It seems the current device db lacks this Zigbee ID. I added this to a new external converter, which is working fine except the lumination sensor (reports only N/A), so I removed it.

### External converter

```shell
{
        zigbeeModel: ['RFPR-ZB-SH-EU'],
        model: 'RADON TriTech ZB',
        vendor: 'Bosch',
        description: 'Wireless motion detector',
        fromZigbee: [fz.temperature, fz.battery, fz.ias_occupancy_alarm_1],
        toZigbee: [],
        meta: {battery: {voltageToPercentage: '3V_2500'}},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'genPowerCfg']);
            await reporting.temperature(endpoint);
            await reporting.batteryVoltage(endpoint);
        },
        exposes: [e.temperature(), e.battery(), e.occupancy(), e.battery_low(), e.tamper()],
    },
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
