### ISSUE TITLE
10+ devices just dropped off Network

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#16668]
### What happened?

Devices have just started dropping off the network. I have not changed anything. 

### Zigbee2MQTT version

Zigbee2MQTT Edge

### Adapter firmware version

20220219

### Adapter

Sonoff Coordinator P

### Debug log

[log bunch of devices just go offline.txt](https://github.com/Koenkk/zigbee2mqtt/files/10727389/log.bunch.of.devices.just.go.offline.txt)

**Comment by Koenkk** [comment]
`SRSP - AF - dataRequest after 6000ms` indicates that your stick disconnects. There are many causes of this but usually other processes interfering, bad power supply or other usb devices interfering. Changing from a USB 3 to USB 2 port can also help.

**Comment by cloudbr34k84** [comment]
@Koenkk Thanks for the tips. 
Its on USB2 already
Power is supplied via NUC and 5 meter USB extension cable. maybe thats tooo long?
its a few meters away anything else?? 

What do you mean by "other Processes"

It doesn't happen all the time.

**Comment by Koenkk** [comment]
5 meter may be too long, try a shorter one (50cm)

**Comment by cloudbr34k84** [comment]
> 5 meter may be too long, try a shorter one (50cm)

Ok yeah ill try shorter
