### ISSUE TITLE
Zemismart ZTB25A, is paring as ZM-L03E-Z, but is the same device as TB25 (but with 20a plug)

### ISSUE THREAD

**Issue by SergioFuchs** [Koenkk/zigbee2mqtt#16676]
### Link

https://www.aliexpress.com/item/1005005128359794.html?spm=a2g0o.order_list.order_list_main.5.21ef1802fiWV8k

### Database entry

{"65534":0,"appVersion":82,"manufacturerName":"_TZ3000_f09j9qjb","modelId":"TS0003","powerSource":1,"zclVersion":3}

### Comments

It's pairing as wrong device, but shoud pair as TB25.
The problem today, is that`s missing power_on_behavior

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
