### ISSUE TITLE
[New device support]: modelID: 'TS0049', manufacturerName: '_TZ3000_hwnphliv'

### ISSUE THREAD

**Issue by DarioKTS** [Koenkk/zigbee2mqtt#16671]
### Link

https://www.alibaba.com/product-detail/High-quality-Intelligent-Garden-ZigBee-Wifi_1600703330607.html

### Database entry

'{"65534":0,"appVersion":72,"manufacturerName":"_TZ3000_hwnphliv","modelId":"TS0049","powerSource":3,"zclVersion":3}'

### Comments

Hello this is a request to help me complete the converter for a watering/gardening valve of the tuya ts0049 family, produced by FrankEver
<img width="598" alt="image" src="https://user-images.githubusercontent.com/118348582/217194374-f042290e-bf19-4bba-bd5e-728183643aa2.png">

I've mande already some headway, however looking at the code for many converters around i might well lack the programming skills to correctly complete the converter, so, to anyone experienced: please do chip in!
I'll provide as much detail as i can and do my best.

This seems to work, albeit partially. I'm aware i haven't used all of the imports, was trying to cover my bases for a start:

```
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = {
    fingerprint: [{modelID: 'TS0049', manufacturerName: '_TZ3000_hwnphliv'}],
    model: 'FK-WT03W',
    vendor: 'Frankever',
    description: 'Smart irrigation valve',
    fromZigbee: [fz.battery, tuya.fz.power_on_behavior, tuya.fz.switch_type, fz.on_off, ],
    toZigbee: [tuya.tz.power_on_behavior, tuya.tz.switch_type, tz.on_off ],
    onEvent: tuya.onEventSetLocalTime,
    configure: tuya.configureMagicPacket,
    exposes: [ e.power_on_behavior(), tuya.exposes.switchType(), e.switch(), e.battery(), e.battery_voltage() ], 
  meta: {
           configure: async (device, coordinatorEndpoint, logger) => {
            try {
                const endpoint = device.getEndpoint(1);
                await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            } catch (error) {/* Fails for some*/}
            },
        tuyaDatapoints: [
        ],
    },
};
```
I have also purchased a tuya hub and followed the process described [here ](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html).
The folowing are the Tuya datapoints and the notes i've taken in regards to their funcionality looking at the event details on the tuya platform and comparing them to what i was doingwith the valve:

- **DPI1**: Switch (On/OFF)
- **DPI7** : Battery report in %
- **DPI10** : Weather Delay: 24/48/72/"Delay" in hrs (the value "Delay" seems to mean disabled)
- **DPI11**: Irrigation Time: the default duration of irrigation, like an auto off switch, in seconds. Values are in multiples of 60 secs as the tuya app  allows changing at best minutes). within the Tuya system it gets rewritten only when the valve is turned on by the app, meaning that changing the value in the tuya app but turning the valve on physically with its button, will use the previous value.
- **DPI12**: Work state "Manual"/"Idle"/"Auto". Goes to manual if the device is acted upon physically, else idle. Auto gets reported when a schedule (be it "cycle and soak" or more complicated) is activated, returns to idle if disactivated (could be only reporting?)
- **DPI15**:Once Using Time : i't s the duration of the last irrigatoin, in secs.
- **DPI16**: Cycle irrigation: it refers to what in the app is called "Cycle and soak" irrigation (water for x time every y hours). can have activation days etc.  ("AA==" means disabled i believe. It can be quite a long string, like "AAABfwABBZ8AHgAFZA==" . both of these values are taken form the tuya platform and i don't know how do they get translated to the arrays i've seen i nthe logs)
- **DPI17**: Normal timer: allows for programming a proper weekly schedule of irrigation. ( form the tuya event details: "AAA=" i believe means diabled, "AAAC0AAFAWQBB+cCDQE" meant at noon only on sundays for 5 mins, "AAAC0AAFAWQBB+cCDQEBAAAAPT5kAQfnAg0B" meant mon-fri at ,00:00 for 1 hr 1 min, and i believe "AAAC0AAFAWQAB+cCDQEBAAAAPT5kAAfnAg0B" means "disable the next task" ; again no clue how that is converted to the arrays i see in the logs)

_As of yet unsloved issues:_

- the battery gets reported by Z2M with the percentage halved, which implies i'm calling on the wrong battery converter or i should link it directly to the datapoint (will try)
- I'm experinecing anomalous battery consumption (lasts about a week.......!!!!! This is true also while connected to the tuya hub). Would like to be able to set reporting times to Z2M when idle to longer periods, to see if anything changes. Haven't tried yet, maybe it does already work with the converter, maybe not. This is true also if connected to the tuya hub.
- During announcing phase (after powering down and up the device) i get this log in debug:
`Received Zigbee message from 'VALVE', type 'attributeReport', cluster 'genOnOff', data '{"32768":0,"moesStartUpOnOff":0,"offWaitTime":0,"onOff":0,"onTime":0,"tuyaBacklightMode":1,"tuyaBacklightSwitch":0}' from endpoint 1 with groupID 0`(might be on the way to solving it thanks ot an [advice ](https://github.com/Koenkk/zigbee2mqtt/discussions/16377#discussioncomment-4913902) by toogooda.
- there are few more logs that i haven't gotten to solve yet and Z2M complans that has no no converter for, like:
`Received Zigbee message from 'VALVE', type 'attributeReport', cluster 'genBasic', data '{"65503":"\u0000\u0000\u0000\u0000\u0011"}' from endpoint 1 with groupID 0`
I've seen afew more of these  going value 65506 is 55, value 65508 is 1 .
i've tried to match them respectively to 0xffdf, 0xffe2, 0xffdf and look for them in the [tuya standard](https://developer.tuya.com/en/docs/iot/Zigbee-Water-valve-controller-access-standard?id=Kbahvojbqzvgl) but aside from understanding they are part of acluster they call tuya electrician private cluser, i am clueless as to what to do with them.

`Received Zigbee message from 'VALVE', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0`
and a few array like messages
`Received Zigbee message from 'VALVE', type 'raw', cluster 'manuSpecificTuya_3', data '{"data":[8,81,10,64,208,72,6,11,0,0,2,28],"type":"Buffer"}' from endpoint 1 with groupID 0`
`Received Zigbee message from 'VALVE', type 'raw', cluster 'manuSpecificTuya_3', data '{"data":[8,95,10,64,208,72,3,10,0],"type":"Buffer"}' from endpoint 1 with groupID 0`

### External converter

```shell
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

module.exports = {
    fingerprint: [{modelID: 'TS0049', manufacturerName: '_TZ3000_hwnphliv'}],
    model: 'FK-WT03W',
    vendor: 'Frankever',
    description: 'Smart irrigation valve',
    fromZigbee: [fz.battery, tuya.fz.power_on_behavior, tuya.fz.switch_type, fz.on_off, ],
    toZigbee: [tuya.tz.power_on_behavior, tuya.tz.switch_type, tz.on_off ],
    onEvent: tuya.onEventSetLocalTime,
    configure: tuya.configureMagicPacket,
    exposes: [ e.power_on_behavior(), tuya.exposes.switchType(), e.switch(), e.battery(), e.battery_voltage() ], 
  meta: {
           configure: async (device, coordinatorEndpoint, logger) => {
            try {
                const endpoint = device.getEndpoint(1);
                await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            } catch (error) {/* Fails for some*/}
            },
        tuyaDatapoints: [
        ],
    },
};
```

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/15124
