### ISSUE TITLE
Z-Stack_3.x.0 router 20221102 stays on Firmware version 20220908

### ISSUE THREAD

**Issue by TheLordVader** [Koenkk/zigbee2mqtt#16670]
### What happened?

 When upgrading my two CC2652P (tried more than 5 times using ZigStarGW-MT) router stills stays on Firmware version 20220908 in Zigbee2MQTT.

### What did you expect to happen?

To upgrade router to firmware 20221102

### How to reproduce it (minimal and precise)

Flash new firmware 20221102 on previous 20220908 using ZigStarGW-MT (Ti Flash2 not currently working)

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20220908

### Adapter

CC2652P 'Smartlight'

**Comment by Koenkk** [comment]
You have to re-read the `swBuildId` from the `genBasic` cluster using the dev console (z2m frontend -> device), then restart z2m. z2m doesn't know the device has been upgraded and therefore does not read the version.
