### ISSUE TITLE
[Feature request]: Spammy error popups - configurability

### ISSUE THREAD

**Issue by BradleyFord** [Koenkk/zigbee2mqtt#16678]
### Is your feature request related to a problem? Please describe

At the moment I have Z2M that has most devices offline, I know and decided to do this for my development.

But now I am getting spammed heaps of red boxes poping up on the web interface.

### Describe the solution you'd like

Configuration option to enable or disable the popups.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by Koenkk** [comment]
Issues related to the frontend should be created here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
