### ISSUE TITLE
EcoDim .07 error on OTA update "image not available"

### ISSUE THREAD

**Issue by Millsite** [Koenkk/zigbee2mqtt#16672]
### What happened?

I've got an EcoDim .07 dimmer, connected and paired well, everything works fine except for the OTA update: it returns (No image available for imageType '60').

### What did you expect to happen?

Either start an update or return a message already at latest firmware.

### How to reproduce it (minimal and precise)

Just click on OTA update again

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E

### Debug log

Debug 2023-02-14 13:48:52Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"Eethoek lampen","transaction":"dej21-1"}'Info 2023-02-14 13:48:52Checking if update available for 'Eethoek lampen'Debug 2023-02-14 13:48:52Check if update available for '0x8cf681fffe893dbb' (EcoDim-Zigbee 3.0)Debug 2023-02-14 13:48:52Using endpoint '1'Debug 2023-02-14 13:48:54Received Zigbee message from 'Eethoek lampen', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16869200,"imageType":60,"manufacturerCode":4714}' from endpoint 1 with groupID 0Debug 2023-02-14 13:48:54Got OTA request '{"fieldControl":0,"manufacturerCode":4714,"imageType":60,"fileVersion":16869200}'Debug 2023-02-14 13:48:54ZigbeeOTA: downloaded main indexInfo 2023-02-14 13:48:54MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Eethoek lampen"},"error":"Failed to check if update available for 'Eethoek lampen' (No image available for imageType '60')","status":"error","transaction":"dej21-1"}'Error 2023-02-14 13:48:54Failed to check if update available for 'Eethoek lampen' (No image available for imageType '60')Debug 2023-02-14 13:48:54Error: No image available for imageType '60' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:113:15) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:260:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:29) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:203:45)Debug 2023-02-14 13:48:57Received Zigbee message from 'Eethoek lampen', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16869200,"imageType":60,"manufacturerCode":4714}' from endpoint 1 with groupID 0Debug 2023-02-14 13:48:57Device 'Eethoek lampen' requested OTADebug 2023-02-14 13:48:57Check if update available for '0x8cf681fffe893dbb' (EcoDim-Zigbee 3.0)Debug 2023-02-14 13:48:57ZigbeeOTA: downloaded main indexDebug 2023-02-14 13:48:57Failed to check if update available for 'Eethoek lampen' (No image available for imageType '60')Info 2023-02-14 13:48:57MQTT publish: topic 'zigbee2mqtt/Eethoek lampen', payload '{"brightness":231,"linkquality":216,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":"idle"},"update_available":null}'Debug 2023-02-14 13:48:57Responded to OTA request of 'Eethoek lampen' with 'NO_IMAGE_AVAILABLE'

**Comment by krispek** [comment]
Looks like a duplicate issue?
- https://github.com/Koenkk/zigbee2mqtt/issues/16462
- https://github.com/Koenkk/zigbee2mqtt/issues/15473

I have the same issue as well.

**Comment by Sarnog** [comment]
Still getting the error message with version 1.30.2

```
Failed to check if update available for 'ecodim 07' (No image available for imageType '60')
```

**Comment by Koenkk** [comment]
To add support for this we need to have the OTA file from Ecodim.

**Comment by Sarnog** [comment]
I don't know how to get that. I don't have a hub from edodim.

**Comment by Sarnog** [comment]
Can anybody get that image? Or explain to me how to get it without a bridge?

**Comment by Veldkornet** [comment]
> Can anybody get that image? Or explain to me how to get it without a bridge?

At the time, I did email them and ask them. They said that they didn't have an update for it. 

Perhaps we can at least ask them for the base image for imageType 60 so that the it's check stops failing.
