### ISSUE TITLE
Smartwings WM25/L-Z roller blinds fails to add to zigbee group

### ISSUE THREAD

**Issue by turbotiger74** [Koenkk/zigbee2mqtt#16686]
### What happened?

Smartwings WM25/L-Z roller blinds fails to add to zigbee group.
It also fails to configure

Zigbee2MQTT:error 2023-02-14 20:03:47: Failed to add from group (Command 0xe0798dfffecf6648/1 genGroups.add({"groupid":3,"groupname":""}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 59559 - 1 - 71 - 4 - 0 after 10000ms))
Zigbee2MQTT:info  2023-02-14 20:04:50: MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0xe0798dfffecf67d6/1","group":"light_switch"},"error":"Failed to add from group (Command 0xe0798dfffecf67d6/1 genGroups.add({\"groupid\":3,\"groupname\":\"\"}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 15897 - 1 - 78 - 4 - 0 after 10000ms))","status":"error","transaction":"jlswt-5"}'
Zigbee2MQTT:error 2023-02-14 20:04:50: Failed to add from group (Command 0xe0798dfffecf67d6/1 genGroups.add({"groupid":3,"groupname":""}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 15897 - 1 - 78 - 4 - 0 after 10000ms))

Zigbee2MQTT:error 2023-02-14 19:43:53: Failed to configure 'Front Bedroom Right Blind', attempt 1 (Error: ConfigureReporting 0xe0798dfffecf6648/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 59559 - 1 - 5 - 1 - 7 after 10000ms)
Zigbee2MQTT:error 2023-02-14 19:43:53: Failed to configure 'Middle Bedroom Blind', attempt 1 (Error: Bind 0xe0798dfffecf67d6/1 genPowerCfg from '0x00124b0025e14ed5/1' failed (AREQ - ZDO - bindRsp after 10000ms)
Zigbee2MQTT:error 2023-02-14 19:44:39: Failed to configure 'Middle Bedroom Blind', attempt 2 (Error: ConfigureReporting 0xe0798dfffecf67d6/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 1444 - 1 - 7 - 1 - 7 after 10000ms)

### What did you expect to happen?

it would add to the group successfully

### How to reproduce it (minimal and precise)

Add smartwings to group

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20220219

### Adapter

Sonoff zigbee dongle-p

### Debug log

[zigbee2mqttlogs.txt](https://github.com/Koenkk/zigbee2mqtt/files/10739208/zigbee2mqttlogs.txt)

**Comment by N8BrB** [comment]
Same issue. Is there some limitation preventing these from being grouped? The device seems to have standard controls.
