### ISSUE TITLE
zigbee2mqtt will not start after update.sh ran

### ISSUE THREAD

**Issue by SteEllis** [Koenkk/zigbee2mqtt#16684]
### What happened?

updated zigbee2mqtt using the update.sh script
after completion zigbee2mqtt was not running
checked for adapter and everything appeared correct
tried a reboot
tried to manually run with rpm start to get error log below
ensured npm collected all modules by issuing npm up
no change same error

### What did you expect to happen?

Expected zigbee2mqtt service to start

### How to reproduce it (minimal and precise)

issue npm start and error is visible

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

cannot find requested information frontend not started

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus_0e9e20d7c912ec11b43221c7bd930c07-if00-port0 

### Debug log

> zigbee2mqtt@1.30.1 start
> node index.js

/opt/zigbee2mqtt/node_modules/rimraf/dist/cjs/src/ignore-enoent.js:15
        if (er?.code !== 'ENOENT') {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/node_modules/rimraf/dist/cjs/src/rimraf-posix.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /opt/zigbee2mqtt
npm ERR! command failed
npm ERR! command sh -c node index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zigbee-user/.npm/_logs/2023-02-15T01_45_41_230Z-debug.log

**Comment by Bolten88** [comment]
I've got the same error after updating to 1.30.1. Have you found a solution yet?

**Comment by Bolten88** [comment]
I have reverted to version 1.28.0 and then it was working again. 

Is it related to my raspbian os version?

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by Bolten88** [comment]
I did some trial and error with the versions and i was able to get it work on version 1.29.2. When i go to 1.30.* it fails to start with the above error.

**Comment by SteEllis** [comment]
I did a fresh install and restored the zigbee2mqtt data. This now works with 1.30.1 as such I suspect something with the upgrade, npm packages?

**Comment by Bolten88** [comment]
> I did a fresh install and restored the zigbee2mqtt data. This now works with 1.30.1 as such I suspect something with the upgrade, npm packages?

A fresh install of zigbee2mqtt only or did you reinstall the os as well? I’m aware now that i’m using a legacy os. So i thought maybe it is related.

**Comment by Koenkk** [comment]
You are probably using an outdated node version, try upgrading to node 18 (run `node --version` to get the current version, min required is 14)

**Comment by SteEllis** [comment]
> 

I did a full install including a the OS (raspberry pi)

**Comment by Bolten88** [comment]
> You are probably using an outdated node version, try upgrading to node 18 (run `node --version` to get the current version, min required is 14)

$ node --version
v12.22.12

so I need to update that first. Will try that tomorrow.

**Comment by nilsx** [comment]
upgraded node to v19.6.0 today, but still having the same problem

**Comment by wantuchm** [comment]
I have updated nodejs from v12 to v14.21.2 and it is working for me. On node v12 I have same problem.

**Comment by Bolten88** [comment]
> I have updated nodejs from v12 to v14.21.2 and it is working for me. On node v12 I have same problem.

How did you update to that specific version?

**Comment by chrismast** [comment]
> nodejs

You can follow Option 2 outlined [here](https://phoenixnap.com/kb/update-node-js-version)

**Comment by chrismast** [comment]
@Bolten88 : Have a look in my open (now closed) ticket. I got it working, maybe the steps help you as well.

**Comment by elektron44** [comment]
> I have updated nodejs from v12 to v14.21.2 and it is working for me. On node v12 I have same problem.

This worked for me too.
Thanks guys
