### ISSUE TITLE
Error in HA log

### ISSUE THREAD

**Issue by fewdji** [Koenkk/zigbee2mqtt#16697]
### What happened?

Get error in HA logs everytime.
Device: [Aqara single switch module T1 (without neutral) lumi.switch.l0agl1](https://www.zigbee2mqtt.io/devices/SSM-U02.html#xiaomi-ssm-u02)
`Invalid option for select.spots_relay_switch_type: '' (valid options: ['toggle', 'momentary'])`

### Zigbee2MQTT version

1.30.1 commit: eb878d3

### Adapter firmware version

EZSP v8 (also tested on CC2652P w Koenkk firmware )

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E (also tested on -P version)

### Debug log

![ha_error](https://user-images.githubusercontent.com/13124598/219156401-bfa71d59-8ce2-41fe-87d9-82642cdfbba2.png)
![z2m](https://user-images.githubusercontent.com/13124598/219160285-b52a9d23-b635-49c3-8d64-7d453f02a714.png)
![z2m_logs](https://user-images.githubusercontent.com/13124598/219160301-d618ec38-fac8-4d2b-8c71-85707d075a3e.png)

**Comment by Koenkk** [comment]
This should disappear once you set the switch type once.
