### ISSUE TITLE
Problem with MLI Tint remote control 404049D

### ISSUE THREAD

**Issue by ChrisLSaar** [Koenkk/zigbee2mqtt#16693]
### What happened?

I have a problem with the integration of a MLI Tint remote control.

The model seems to be identical to the remote control 404049C, but has the type designation 404049D.

The debug log shows the familiar message of an unsupported device. Here you can see that the Zigbee model name should be ['Remote Control'] instead of the old name ['tint-Remote-white'].

I have created an external converter ...

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
      zigbeeModel: ['Remote Control'],
        model: '404022/404049C',
        description: 'Tint dim remote control',
        vendor: 'MLI',
        fromZigbee: [fz.command_on, fz.command_off, fz.command_step, fz.command_move, fz.command_stop, fz.command_move_to_color_temp,
            fz.command_move_to_color, fz.tint_scene],
        exposes: [e.action(['on', 'off', 'brightness_step_up', 'brightness_step_down', 'brightness_move_up', 'brightness_move_down',
            'brightness_stop', 'color_temperature_move', 'color_move', 'scene_1', 'scene_2', 'scene_3', 'scene_4', 'scene_5', 'scene_6'])],
        toZigbee: [],
        configure: async (device, coordinatorEndpoint, logger) => {
            device.powerSource = 'Battery';
            device.save();
        },
};

module.exports = definition;
```

With this converter I can integrate the remote control.

![image](https://user-images.githubusercontent.com/40181260/219131413-5ede5696-443d-4d21-9369-6080b2aecec9.png)

However, no actions are triggered.
In the debug log there is no more message at all for this participant, nevertheless the remote control does not work.

I have additionally created a debug log on level zigbee-herdsman*. However, I personally cannot do anything with this log.
I have attached the log.

[ZigbeeHerdsmanLog_404049D.txt](https://github.com/Koenkk/zigbee2mqtt/files/10746659/ZigbeeHerdsmanLog_404049D.txt)

Best regards
Christian

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20180815

### Adapter

CC2531

### Debug log

[ZigbeeHerdsmanLog_404049D.txt](https://github.com/Koenkk/zigbee2mqtt/files/10746678/ZigbeeHerdsmanLog_404049D.txt)

**Comment by Koenkk** [comment]
Can you try this change:

```js
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1); // <- added 
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl', 'lightingColorCtrl']); // <- added 
            device.powerSource = 'Battery';
            device.save();
        },
```

**Comment by ChrisLSaar** [comment]
Hi, yes, tried it directly.
Thanks for the quick feedback.
I have adjusted the external converter as you described.
There are now more debug outputs.
At the end of the pairing there is now an error.
Actions still don't come up.

Attached the new log...

[Zigbee2Mqtt_Log_404049D_new_converter.txt](https://github.com/Koenkk/zigbee2mqtt/files/10759842/Zigbee2Mqtt_Log_404049D_new_converter.txt)

**Comment by Enemyscout** [comment]
Did a quick test. This seems to work for me. 
Device shows up an generates actions when buttons are pressed

**Comment by ChrisLSaar** [comment]
@Enemyscout : 
Are you sure you have the same type of remote as me? 
404049D and not 404049C ?

The remote still does not work for me. No actions are triggered.

**Comment by Koenkk** [comment]
@ChrisLSaar it may help to re-pair the device close to the coordinator. First force remove it through the z2m frontend, restart z2m and re-pair.

**Comment by ChrisLSaar** [comment]
@Koenkk 

I have already tried this several times.
- Forced deletion of the device
- reboot the Zigbee2Mqqt container (also already rebooted the whole server)
- batteries out of the remote, wait, and batteries in again
- reintegrate the remote very close to the coordinator (about 30cm)

Always the same result...
The integration process seems to work but no actions are triggered. 
After some time a LQI is displayed for the device. But actions do not come up.

![image](https://user-images.githubusercontent.com/40181260/219854277-c55171d7-6668-4f2d-928b-37edfd158c75.png)

In the debug log, nothing is entered when a key is pressed.
Can I send you some more detailed logs that might help you?
Is there a possibility to log more deep?
Does the log from the zigbee-herdsman* help you?

**Comment by Koenkk** [comment]
- Does the configure succeed? You can force it via the z2m frontend -> device -> yellow refresh icon. If it fails, try to wakeup the device right before pressing the button
- Can you provide the data/database.db entry of your device?

**Comment by Koenkk** [comment]
I cannot understand why my converter doesn't work (especially since it worked for @Enemyscout). Nothing shows up in the debug log when pressing the buttons?

**Comment by ChrisLSaar** [comment]
Yeah, I don't know either.
I am a software developer myself, but from a different field. 
Normally I shouldn't have been too stupid with the integration.
Two IKEA remote controls run without any problems.

What seems strange to me...
After some unused time the remote control it is displayed as offline.
![image](https://user-images.githubusercontent.com/40181260/220186165-4eedde91-7468-4d9e-b864-31006a1af5f1.png)

When I press a key again the following debug messages are displayed...
![image](https://user-images.githubusercontent.com/40181260/220186527-987f7fa7-6f80-45f1-8c8f-0325f0b104ef.png)
![image](https://user-images.githubusercontent.com/40181260/220186651-443476b4-90dc-4dbb-b62c-a94ddf06c7e0.png)

After that the remote control is shown as ONLINE again,
but still no action triggered and no further debug output on any key press.

**Comment by Koenkk** [comment]
@ChrisLSaar could it be that the remote is broken? (have you seen it working with any other system?)

**Comment by ChrisLSaar** [comment]
I had ordered the remote just before my first post. But of course it is not excluded that it has a defect.
Maybe I'll try a Wireshark trace or I send the remote back and try another model.

Anyway, thanks for your efforts and your impressive project "Zigbee2Mqtt".
I will definitely "buy you some coffee".

**Comment by ChrisLSaar** [comment]
I have sent remote control back to Amazon to not exceed return period.

**Comment by Sir-Pandalot** [comment]
@Koenkk I just received this remote and I cannot get it to work. I added the below converter, but it still gives me this error:

Device '0xa4c13800aa432d18' with Zigbee model 'Remote Control' and manufacturer name 'MLI' is NOT supported

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'Remote Control', manufacturerName: 'MLI'}],
    model: '404049D',
    description: 'Tint dim and color remote control',
    vendor: 'Müller Licht',
    fromZigbee: [fz.command_on, fz.command_off, fz.command_step, fz.command_move, fz.command_stop, fz.command_move_to_color_temp,
        fz.command_move_to_color, fz.tint_scene],
    exposes: [e.action(['on', 'off', 'brightness_step_up', 'brightness_step_down', 'brightness_move_up', 'brightness_move_down',
        'brightness_stop', 'color_temperature_move', 'color_move', 'scene_1', 'scene_2', 'scene_3', 'scene_4', 'scene_5', 'scene_6'])],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1); // <- added 
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl', 'lightingColorCtrl']); // <- added 
        device.powerSource = 'Battery';
        device.save();
    },
},

module.exports = definition;`
