### ISSUE TITLE
TuYa TS0601_dimmer - The "min_brightness" setting reduces the bandwidth of the touch zone - "max_brightness" has no effect

### ISSUE THREAD

**Issue by MauiR** [Koenkk/zigbee2mqtt#16701]
### What happened?

If you increase the "min_brightness" of the TuYa TS0601_dimmer. The range of the running light on the front is shortened. With poorly dimmable LEDs, more than half of the span is lost.

Example "min_brightness" = 90 -> The adjustable range is almost halved.
![20230215_224854242_iOS conv](https://user-images.githubusercontent.com/86602061/219208665-ca9ef9d4-343a-476e-8a01-1b5a5ade2052.jpeg)

This makes it very difficult to dim the light. 

The "max_brightness" on the other hand has no function and is ignored. 

![Unbenannt](https://user-images.githubusercontent.com/86602061/219210738-48fc87e0-32b3-4876-b8e6-0c298cd2b19b.PNG)

### What did you expect to happen?

I expect the running light range will start at "0" regardless of the "min_brightness" setting. 

I expect the "max_brightness" setting to stop the light at this brightness. The running light should go to 100 %. 

### How to reproduce it (minimal and precise)

set "min_brightness" > 0   - >   running light range will be reduced
set " max_brightness" < 255   ->   Light is still dimmabel to 255 (100%)

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

 20211217

### Adapter

Slaesh`s CC265RB stick

**Comment by MauiR** [comment]
Still up to date under the latest homeassistant and zigbe2mqtt verison

**Comment by Sashik259** [comment]
The same [issue](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/454)

**Comment by Sashik259** [comment]
The same with 1.30.4-1 Zigbee2MQTT Addon

**Comment by gdbd** [comment]
have this issue too

**Comment by gdbd** [comment]
i am not have this hub too

**Comment by Sashik259** [comment]
The same issue with 1.32.0 Zigbee2MQTT Addon.
I have no TuYa hub for test.

**Comment by gdbd** [comment]
I am ordered tuya hub, just for this case. Will test on it after arrival

**Comment by gdbd** [comment]
Bad news: i am tested it with 'smart life' app via tya hub and it also cannot set max brigtness:

![Screenshot_20230714-222001](https://github.com/Koenkk/zigbee2mqtt/assets/5655858/59ca3805-655b-423e-be62-76610c784a0f)

only the lower border is draggable and no way to limit the upper value....

but also found it support additional settings to manage how indicator light worked. Would great to support it also:

![Screenshot_20230714-222040](https://github.com/Koenkk/zigbee2mqtt/assets/5655858/40b72f26-51e5-40b9-88c8-bd1d0cbf4483)
