### ISSUE TITLE
SkyConnect & Aqara sensors joining only to coordinator

### ISSUE THREAD

**Issue by jvuotila** [Koenkk/zigbee2mqtt#16715]
### What happened?

Aqara sensors (end devices) like to join to zigbee mesh only thru coordinator which is SkyConnect. This is quite big problem because I lose connection on other end of my house. Philips motion sensors which I also got, use whole mesh. There is mainly Ikea on mesh.

Total 36
By device type
End devices: 21
Router: 15
By power source
Battery: 21
Mains (single phase): 15
By vendor
IKEA of Sweden: 18
LUMI: 13
Signify Netherlands B.V.: 4
Philips: 1
By model
TRADFRIbulbE27WSglobeopal1055lm: 6
lumi.sensor_magnet.aq2: 5
lumi.weather: 4
lumi.sensor_wleak.aq1: 4
TRADFRI on/off switch: 4
TRADFRI control outlet: 3
TRADFRIbulbE14WScandleopal470lm: 2
SML003: 2
TRADFRI Driver 30W: 2
SML004: 2
TRADFRI Driver 10W: 1
LWA001: 1

ID_MODEL: SkyConnect_v1.0
ID_MODEL_ENC: SkyConnect\x20v1.0
ID_MODEL_ID: ea60

### Zigbee2MQTT version

1.30.1-1

### Adapter firmware version

7.1.1.0 build 273

### Adapter

SkyConnect

**Comment by kirovilya** [comment]
try with latest dev/edge version of z2m

**Comment by jvuotila** [comment]
Isn't that 1.30.1-1 latest release?

**Comment by jvuotila** [comment]
Okay, just checked code of dev branch. There is some changes to curtain devices and almost daily update for zigbee-herdsman library. Just wondering that maybe I just wait for the next version then? Seems that there is no direct code changes to this issue.

**Comment by mamrai1** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/16778

**Comment by mamrai1** [comment]
Try to select the nearest router to your aqara sensor and select that for pairing... it actually works

**Comment by jvuotila** [comment]
> Try to select the nearest router to your aqara sensor and select that for pairing... it actually works

Yep, that's incredible tip. I just paired half of my sensors again by this way and it worked perfectly!

**Comment by DannyFeliz** [comment]
> Try to select the nearest router to your aqara sensor and select that for pairing... it actually works

This fixed my issue too, thanks.

**Comment by Nailik** [comment]
How did you actually get it to work with skyconnect i struggle with the error mentioned in https://github.com/Koenkk/zigbee2mqtt/issues/16716

**Comment by mamrai1** [comment]
Ok, which firmware do you have?

**Comment by Nailik** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/13292441/d819a70f-1502-4d05-8379-55f63e97d35b)

I used this site https://skyconnect.home-assistant.io/firmware-update/

**Comment by mamrai1** [comment]
Ok if you used zha or the multiprotocol plugin you have to disablecor uninstall  them first. After doing that can you probe the stick with 'universal-silabs-flasher --verbose --device /dev/ttyACM0 probe'

**Comment by Nailik** [comment]
@mamrai1 thank you very much i only had to remove the multiprotocol plugin!
