### ISSUE TITLE
Aqara presence detector FP1 RTCZCGQ11LM

### ISSUE THREAD

**Issue by Aragon2023** [Koenkk/zigbee2mqtt#16724]
### What happened?

Ich möchte auf Zigbee2Mqtt umsteigen und bekomme beim Koppeln vom Aqara presence detector FP1 RTCZCGQ11LM folgende Warnung Angezeigt.

`warning 2023-02-18 10:22:24zigbee-herdsman-converters:xiaomi:aqara_fp1: Unknown key 0x010c = 3`

Möchte aber erst umsteigen, wenn all meine Geräte zu 100 % korrekt eigebunden werden. 
Vielen Dank für deine Mühe 

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

26780700

### Adapter

ConBee2 / Sonoff USB Stick P

**Comment by arteck** [comment]
this is not a iobroker forum..
