### ISSUE TITLE
Z2M version >1.22.2 fails to start with Raspbian Buster and ConBee II

### ISSUE THREAD

**Issue by KC-inDomus** [Koenkk/zigbee2mqtt#16730]
### What happened?

Hi there,
had an old (1.13.1) Z2M instance running fine on Docker@Raspbian Buster with ConBee II with firmware 266e0700. 
Decided to make an update to latest (1.30.1): no joy, it fails to start. 

Rolled back to 1.13.1 everything works. So I tried every single later version: the last "working" is 1.22.2, starting **1.23.0 it fails to start**, so something changed starting with that version. I even tried with ConBee version 26720700 (latest) firmware, no change. 1.23.0 breaks something. I even tried with a fresh instance 1.30.1's configuration file (plus with port and adapter: deconz), no luck.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

266e0700 / 26720700

### Adapter

ConBee II

**Comment by lux73** [comment]
sounds similar to https://github.com/Koenkk/zigbee2mqtt/issues/16689

**Comment by KC-inDomus** [comment]
> sounds similar to https://github.com/Koenkk/zigbee2mqtt/issues/16689

I'm on docker

**Comment by lux73** [comment]
https://www.zigbee2mqtt.io/guide/installation/02_docker.html#notes-for-raspberry-pi-users

`If you are running Raspbian Buster (not Bullseye!) (find out by executing grep "PRETTY_NAME" /etc/os-release) you need to install libseccomp2`

found this under "Installation/Docker" - don't know if it's related for your Installation because you don't post any error-logs

**Comment by KC-inDomus** [comment]
> https://www.zigbee2mqtt.io/guide/installation/02_docker.html#notes-for-raspberry-pi-users
> 
> 
> 
> `If you are running Raspbian Buster (not Bullseye!) (find out by executing grep "PRETTY_NAME" /etc/os-release) you need to install libseccomp2`
> 
> 
> 
> found this under "Installation/Docker" - don't know if it's related for your Installation because you don't post any error-logs

right, thanks. will try it

**Comment by KC-inDomus** [comment]
> https://www.zigbee2mqtt.io/guide/installation/02_docker.html#notes-for-raspberry-pi-users
> 
> 
> 
> `If you are running Raspbian Buster (not Bullseye!) (find out by executing grep "PRETTY_NAME" /etc/os-release) you need to install libseccomp2`
> 
> 
> 
> found this under "Installation/Docker" - don't know if it's related for your Installation because you don't post any error-logs

tried. not that.

**Comment by KC-inDomus** [comment]
@Koenkk, any clue about what changed after 1.22.2 that may cause this problem?

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when starting 1.30.1?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by KC-inDomus** [comment]
> Can you provide the herdsman debug log when starting 1.30.1?
> 
> 
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

sure, asap.

**Comment by KC-inDomus** [comment]
Here we go with [1.22.2 log](https://pastebin.com/Nx1cUmcZ) and [1.30.0 log](https://pastebin.com/YddHAVBh).

**Comment by Koenkk** [comment]
Try removing the `transmit_power` from the z2m configuration.yaml. This is not supported for the Deconz adapter.

**Comment by KC-inDomus** [comment]
> Try removing the `transmit_power` from the z2m configuration.yaml. This is not supported for the Deconz adapter.

YES! Thaw was the problem. Thanks @Koenkk
