### ISSUE TITLE
[Feature request]: Motor speed for lumi.curtain.acn002 - Aqara Roller Shade Driver E1

### ISSUE THREAD

**Issue by fir3drag0n** [Koenkk/zigbee2mqtt#16734]
### Is your feature request related to a problem? Please describe

No, but due to some options it would be nice to alter the speed as the Aqara App supports it
I do have a heavy blind, so maybe it would close/open better.

### Describe the solution you'd like

integrate the speed option

### Describe alternatives you've considered

none

### Additional context

see here for reference: https://homekitnews.com/2021/11/21/aqara-add-more-functionality-to-the-roller-shade-driver-e1/

**Comment by cryptontgn** [comment]
It will be possible?

**Comment by chaayac** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/7109 is available now in v1.36
