### ISSUE TITLE
Add support by Mozilla's WebThings Gateway to documentation

### ISSUE THREAD

**Issue by flatsiedatsie** [Koenkk/zigbee2mqtt#1673]
Thanks to some hard work by Kabbi there is now an add-on that integrates zigbee2mqtt with Mozilla's WebThings Gateway. It currently supports only a few devices, but the hard work is done. Now it's just a matter of adding some JSON that describes the devices.

Add-on github page:
https://github.com/kabbi/zigbee2mqtt-adapter

Mozilla's page:
https://iot.mozilla.org/gateway/

Since this smart home controller is quickly gaining popularity, I believe it would be worth it to mention it in the documentation.

**Comment by Koenkk** [comment]
Thanks, done!
