### ISSUE TITLE
Philips Hue Tap Dial Switch - Unsupported

### ISSUE THREAD

**Issue by Alfamonk** [Koenkk/zigbee2mqtt#16746]
### What happened?

Hello!
I bought a new Philips Hue Tap Dial Switch, after noticing it is already compatible with Zigbee2MQTT.
When trying to make the  join my Zigbee2MQTT network, I get the message "Unsupported". The model is RDM002.
I have connected it to the Philips Hue hub, and let it update to the latest firmware version, then tried again. Unfortunately, the same issue. Here is the error log:

Zigbee2MQTT:error 2023-02-19 16:59:07: Failed to interview '0x001788010d3556c5', device has not successfully been paired
Zigbee2MQTT:warn  2023-02-19 17:00:19: Device '0x001788010d3556c5' left the network
Zigbee2MQTT:error 2023-02-19 17:03:11: Failed to interview '0x001788010d3556c5', device has not successfully been paired
Zigbee2MQTT:warn  2023-02-19 17:03:14: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'

![2023-02-19_171047](https://user-images.githubusercontent.com/87588396/219956797-3484458f-f889-426b-86b2-a03e21d83021.png)

### What did you expect to happen?

I expected that it would connect to my network and work as I've seen on other people setups.

### How to reproduce it (minimal and precise)

Just trying to join the Zigbee network.

### Zigbee2MQTT version

1.30.1 commit: unknown

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by jannehietamaki** [comment]
Reconfiguring might work. Looks like Tap Dial Switches are extremely unstable. 

I bought five of them. One works perfectly, one fails when trying, three keep timeouting when trying to configure them with `AREQ - ZDO - bindRsp after 10000ms`
