### ISSUE TITLE
no converter available for 'light indicator level' ("") (ZBDongle-E)

### ISSUE THREAD

**Issue by Kitchigo** [Koenkk/zigbee2mqtt#16753]
### What happened?

I have this message with a SonOff  ZBDongle-E with router firmware : ``no converter available for 'light indicator level' ("")``

### How to reproduce it (minimal and precise)

Just with a router firmware

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20210708

### Adapter

ZBDongle-P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10777949/log.txt)

**Comment by Kitchigo** [comment]
I'm now with Zigbee2MQTT 1.30.2 and firmware zStack3x0 20221226 , but same error...

**Comment by HoM3r17** [comment]
I'm using a ZB Dongle E as a router since a few month, and have the same issue, it doesn't seem to affect anything badly, but it shows in the logs every minute...
