### ISSUE TITLE
SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P automatic flashing instructions are broken

### ISSUE THREAD

**Issue by Barsonax** [Koenkk/zigbee2mqtt#16769]
### What happened?

The pdf asks you to Download, unzip and execute the file however its not clear which file this is. I suspect a link is broken here:
![image](https://user-images.githubusercontent.com/19387223/220342013-ea164728-382b-4779-962c-41201f2a74cf.png)

I tested in Brave, Chrome and Edge and all have the same result. Word does show a uartlog.py, which is the script I need I suspect, but I cannot open it

I tried to create a issue at https://github.com/Koenkk/zigbee2mqtt.io but this seems to be disabled there so iam assuming this repo is the correct spot.

### Zigbee2MQTT version

not applicable

### Adapter firmware version

not applicable

### Adapter

not applicable

**Comment by lux73** [comment]
https://www.zigbee2mqtt.io/guide/adapters/flashing/flashing_via_cc2538-bsl.html

dont know from where the mentioned PDF is  - but if you want to flash your Coordinator all is described in the postet link 😉

**Comment by Barsonax** [comment]
https://www.zigbee2mqtt.io/guide/adapters/

It's here if you go to that sonof dongle
