### ISSUE TITLE
[New device support]: Hue Play Gradient Tube Compact Black

### ISSUE THREAD

**Issue by narc792** [Koenkk/zigbee2mqtt#16774]
### Link

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-play-gradient-light-tube-compact/046677803537

### Database entry

{"id":23,"type":"Router","ieeeAddr":"0x001788010b91945b","nwkAddr":50462,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"915005988401","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"915005988401","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210407","swBuildId":"1.86.6"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[{"cluster":64515,"type":"endpoint","deviceIeeeAddress":"0x00124b0022819b51","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[{"cluster":64515,"type":"endpoint","deviceIeeeAddress":"0x00124b0022819b51","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210407","swBuildId":"1.86.6","zclVersion":2,"interviewCompleted":true,"meta":{"configured":-463500028},"lastSeen":1677013335384,"defaultSendRequestWhen":"immediate"}

### Comments

Adding support for the black model of this light. The white is currently supported.

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const philips = require('zigbee-herdsman-converters/lib/philips');
const e = exposes.presets;
const ea = exposes.access;

const extend = require('zigbee-herdsman-converters/lib/extend');

const definition = {
        zigbeeModel: ['915005988401'],
        model: '915005988401',
        vendor: 'Philips',
        description: 'Hue Gradient light tube compact black',
        extend: philips.extend.light_onoff_brightness_colortemp_color_gradient({colorTempRange: [153, 500]}),
};


module.exports = definition;
```

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
