### ISSUE TITLE
[New device support]: Lonsonho ZB-RGBCW weird color interaction

### ISSUE THREAD

**Issue by johnnypr0x** [Koenkk/zigbee2mqtt#16770]
### Link

https://www.amazon.de/dp/B0BF9L8RFB?psc=1&ref=ppx_yo2ov_dt_b_product_details&language=en_GB&currency=EUR

### Database entry

{"id":11,"type":"Router","ieeeAddr":"0xa4c1388730d2290a","nwkAddr":53997,"manufId":4107,"manufName":"eWeLight","powerSource":"Mains (single phase)","modelId":"ZB-CL01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"hwVersion":0}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":24939,"currentY":24701,"currentSaturation":0,"colorTemperature":350}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":6,"stackVersion":2,"hwVersion":0,"dateCode":"20220518","swBuildId":"2.0.1","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1676979262004,"defaultSendRequestWhen":"immediate"}

### Comments

Hello,

Im trying to control my RGB fans with homeassistant through zigbee. I got the arctic P12/P14 RGB fans + a 4PIN Zigbee Lonsonho ZB-RGBCW controller. To power them up Im using a 12V 2A 24W power adapter.

My problem is when I put all four pins in I only get a few colours (blue, purple, white), when I let the pins loose and only three pins connect I get the other colors (green, red, yellow but not blue/purple since blue isnt connected). I also cant turn the colours off, but when I let only three pins connect I can turn it off by turning it blue. 

I wonder what the problem could be?

Best regards, johnny.

### Supported color modes

RGB

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by ingoratsdorf** [comment]
Not sure what you are having. If you have an RGB fan, you need an RGB controller, not an RGBCW controller. Also, as the name suggests, a RGBCW controller has 5 channels with 6 pins (5 channels plus ground).
If your controller has only 4 pins, then it's an RGB controller (R+G+B+ground), which would match your fans.

The Lonsonho eWeLight ZB-CL01 converter is pretty buggered up and there are a few open issues with it. Most likely, you have a different controller than the one it is recognised for. Same here for me. Recognised incorrectly, channels messed up.
