### ISSUE TITLE
Recognizes my device as another

### ISSUE THREAD

**Issue by DjSpiritBG** [Koenkk/zigbee2mqtt#16779]
### What happened?

when I connect my device recognizes it as a device of TuYa TS0505B but my device is GIDEALED ZC05M I am new and do not know how to fix it can you advice 

### What did you expect to happen?

To fix the problem 

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20221226

### Adapter

Sonoff 3.0

**Comment by Koenkk** [comment]
This device is probably internally a `TS0505B` (different from the original ZC05M which has zigbeeModel `A11`). The device should function correctly.

**Comment by DjSpiritBG** [comment]
ok tnx
