### ISSUE TITLE
[Feature request]: Restore color and brightness value after finishing effect 

### ISSUE THREAD

**Issue by rorie1982** [Koenkk/zigbee2mqtt#16811]
### Is your feature request related to a problem? Please describe

It is frustrating when using an effect only the power state is restored but not the other properties like color or brightness. For example: when a led strip is turned off and a I send a effect to blink it goes off again when the effect is finished, when the led strip was on before starting the effect it stays on when finishing.   

### Describe the solution you'd like

When using effects it would be nice to restore the color and brightness to the value it was before the effects was started. 

### Describe alternatives you've considered

Storing the color and brightness by myself before starting the effect.

### Additional context

None

**Comment by junosuarez** [comment]
I think this is device-specific. I just tried with some Ikea Tradfri lights, and after the effect, they do what you describe of going back to their same brightness and color temperature settings. Which device(s) are you seeing this behavior on?

Note - for effects, zigbee2mqtt is just sending an "effect" zigbee message to the device. How the device handles it, and what it does afterwards, is dependent on the device firmware. If the firmware isn't doing what you want, one approach is to script it as a series of messages, for example: get the current brightness + color temp, then set the effect, then wait a little bit, then set the brightness and color temp again. You could achieve this through a zigbee2mqtt Extension, or perhaps through any other tools you might be using with zigbee2mqtt, such as Homeassistant.
