### ISSUE TITLE
Moes Thermostat cannot set current_heating_setpoint in 0.5 steps (which it supports) [ _TZE200_aoclfnxz / TS0601 /  BHT-002-GCLZB ]

### ISSUE THREAD

**Issue by zeroflag0** [Koenkk/zigbee2mqtt#16853]
### What happened?

Can only set current_heating_setpoint in whole integers

### What did you expect to happen?

Setting 0.5°C-steps on all temperature-parameters, which the device supports.

### How to reproduce it (minimal and precise)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/11450358/222057739-f833edbd-c20f-40d9-8370-b9959adbc137.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/11450358/222057750-cb160ef6-2682-4240-8188-16707effef45.png">

### Zigbee2MQTT version

1.30.1 commit: eb878d3

### Adapter firmware version

20221226

### Adapter

usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0

### Debug log

 2023-03-01 07:04:26MQTT publish: topic 'zigbee2mqtt/Heating Livingroom', payload '{"child_lock":null,"current_heating_setpoint":22,"deadzone_temperature":null,"heat":"OFF","linkquality":167,"local_temperature":20,"local_temperature_calibration":-1,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":5,"saturday_p1_minute":0,"saturday_p1_temperature":21.5,"saturday_p2_hour":6,"saturday_p2_minute":30,"saturday_p2_temperature":22,"saturday_p3_hour":13,"saturday_p3_minute":30,"saturday_p3_temperature":22.5,"saturday_p4_hour":21,"saturday_p4_minute":30,"saturday_p4_temperature":20,"sunday_p1_hour":5,"sunday_p1_minute":0,"sunday_p1_temperature":21.5,"sunday_p2_hour":6,"sunday_p2_minute":30,"sunday_p2_temperature":22,"sunday_p3_hour":13,"sunday_p3_minute":30,"sunday_p3_temperature":22.5,"sunday_p4_hour":21,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":5,"weekdays_p1_minute":0,"weekdays_p1_temperature":21.5,"weekdays_p2_hour":6,"weekdays_p2_minute":30,"weekdays_p2_temperature":22,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22.5,"weekdays_p4_hour":21,"weekdays_p4_minute":30,"weekdays_p4_temperature":20},"running_state":"idle","sensor":"OU","system_mode":"off"}'
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":108}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":364}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":620}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":876}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1132}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1388}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:28Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1644}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1900}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":2156}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":2412}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":2668}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":2924}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":3180}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":3436}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":3692}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":3948}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4204}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4460}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4716}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":4972}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":5228}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":5484}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":5740}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":5996}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":6252}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":6508}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":6764}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":7020}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":7276}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:29Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":7532}' from endpoint 1 with groupID 0
Info 2023-03-01 07:04:30MQTT publish: topic 'zigbee2mqtt/Heating Livingroom', payload '{"child_lock":null,"current_heating_setpoint":22,"deadzone_temperature":null,"heat":"OFF","linkquality":174,"local_temperature":20,"local_temperature_calibration":-1,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":5,"saturday_p1_minute":0,"saturday_p1_temperature":21.5,"saturday_p2_hour":6,"saturday_p2_minute":30,"saturday_p2_temperature":22,"saturday_p3_hour":13,"saturday_p3_minute":30,"saturday_p3_temperature":22.5,"saturday_p4_hour":21,"saturday_p4_minute":30,"saturday_p4_temperature":20,"sunday_p1_hour":5,"sunday_p1_minute":0,"sunday_p1_temperature":21.5,"sunday_p2_hour":6,"sunday_p2_minute":30,"sunday_p2_temperature":22,"sunday_p3_hour":13,"sunday_p3_minute":30,"sunday_p3_temperature":22.5,"sunday_p4_hour":21,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":5,"weekdays_p1_minute":0,"weekdays_p1_temperature":21.5,"weekdays_p2_hour":6,"weekdays_p2_minute":30,"weekdays_p2_temperature":22,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22.5,"weekdays_p4_hour":21,"weekdays_p4_minute":30,"weekdays_p4_temperature":20},"running_state":"idle","sensor":"OU","system_mode":"off"}'
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":4972}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":5228}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":5484}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":5740}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":5996}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":6252}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":6508}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:35Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":6764}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":7020}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":7276}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":7532}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":7788}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":8044}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":8300}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":8556}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":8812}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":9068}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":9324}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":9580}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":9836}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":10092}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":10348}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":10604}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":10860}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":11116}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":11372}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":11628}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":11884}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":12140}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":12396}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":12652}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":12908}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:36Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":13164}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:37Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":13420}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:37Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":13676}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:37Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":13932}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:37Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":36}],"seq":14188}' from endpoint 1 with groupID 0
Debug 2023-03-01 07:04:37Received Zigbee message from 'Heating Livingroom', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,200],"type":"Buffer"},"datatype":2,"dp":24}],"seq":9836}' from endpoint 1 with groupID 0
Info 2023-03-01 07:04:38MQTT publish: topic 'zigbee2mqtt/Heating Livingroom', payload '{"child_lock":null,"current_heating_setpoint":22,"deadzone_temperature":null,"heat":"OFF","linkquality":174,"local_temperature":20,"local_temperature_calibration":-1,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":{"saturday_p1_hour":5,"saturday_p1_minute":0,"saturday_p1_temperature":21.5,"saturday_p2_hour":6,"saturday_p2_minute":30,"saturday_p2_temperature":22,"saturday_p3_hour":13,"saturday_p3_minute":30,"saturday_p3_temperature":22.5,"saturday_p4_hour":21,"saturday_p4_minute":30,"saturday_p4_temperature":20,"sunday_p1_hour":5,"sunday_p1_minute":0,"sunday_p1_temperature":21.5,"sunday_p2_hour":6,"sunday_p2_minute":30,"sunday_p2_temperature":22,"sunday_p3_hour":13,"sunday_p3_minute":30,"sunday_p3_temperature":22.5,"sunday_p4_hour":21,"sunday_p4_minute":30,"sunday_p4_temperature":20,"weekdays_p1_hour":5,"weekdays_p1_minute":0,"weekdays_p1_temperature":21.5,"weekdays_p2_hour":6,"weekdays_p2_minute":30,"weekdays_p2_temperature":22,"weekdays_p3_hour":13,"weekdays_p3_minute":30,"weekdays_p3_temperature":22.5,"weekdays_p4_hour":21,"weekdays_p4_minute":30,"weekdays_p4_temperature":20},"running_state":"idle","sensor":"OU","system_mode":"off"}'

**Comment by adorobis** [comment]
As far as I know it is a known limitation of the device when controlling over zigbee. Not specific to zigbee2mqtt.

**Comment by adorobis** [comment]
And here is the information from Moes support confirming above limitation:
https://github.com/Koenkk/zigbee2mqtt/issues/14965#issuecomment-1368179306
