### ISSUE TITLE
zigbee devices tuya

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#1686]
Hola:

I have found several zigbee computers that communicate with a gateway with your application.
Someone has tried some of these devices without their gateway, since they are very cheap

**Comment by JLFN** [comment]
there is one here.
https://github.com/Koenkk/zigbee2mqtt/issues/1690

**Comment by zhapwey** [comment]
then I will get a Chinese tvr of those who do for your application that have a cheap price, have that work and have if I communicate with zigbee2mqtt. So I start with the topic of adding objects.

regards
