### ISSUE TITLE
Decoding issue with MQTT rename command

### ISSUE THREAD

**Issue by jiki974** [Koenkk/zigbee2mqtt#1687]
When the new name contain accent it's not interpreted correclty and put some strange char in the friendly name :

example :"D�tecteur chambre" instead of "Détecteur chambre"

It seems that UTF8 decoding is not applied when Z2M receive rename command.

**Comment by Koenkk** [comment]
I've added a testcase for this and also tried to reproduce the issue on my setup, however I cannot reproduce it.

Does the editor you open the `configuration.yaml` opens it with utf8?
