### ISSUE TITLE
Philips Hue dimmer - action_duration null

### ISSUE THREAD

**Issue by ghost** [Koenkk/zigbee2mqtt#16877]
### What happened?

I'm not sure which is possibly causing this, but I recently updated:
Z2M ➜ 1.30.2
HA ➜ 2023.3.0

I am now getting all my Hue dimmer switches `action_duration' reporting `unknown` in HA - example below:
![Screenshot 2023-03-02 at 09 53 43](https://user-images.githubusercontent.com/34644672/222394222-334546d5-1a45-4f08-8972-4a9a6e7743e6.png)

The switches work fine and show OK for everything else.
![Screenshot 2023-03-02 at 09 54 31](https://user-images.githubusercontent.com/34644672/222394406-5230b6b9-ce5a-4494-90d4-df0bd6dc5551.png)

...all dimmers are reporting `null` in Z2M - example below:
![Screenshot 2023-03-02 at 09 55 10](https://user-images.githubusercontent.com/34644672/222394589-c9430133-6f58-4264-8cbb-b2f6faca062b.png)

### What did you expect to happen?

I didn't expect a permanent state of `unknown` in HA or `null` in Z2M.

I have pressed the buttons to see idk it was only a start-up error.
I also restarted HA in case it was a 1-off upgrade error.

### How to reproduce it (minimal and precise)

It's a permanent status (for me) for:
Z2M ➜ 1.30.2
HA ➜ 2023.3.0

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

2023.3.0

### Adapter

Sonoff 3.0 USB stick ZBDongle-P / zStack3x0 / v20221226

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10870005/log.txt)

**Comment by hellcry37** [comment]
I think this is solved in latest HA

**Comment by JCHH2** [comment]
Still 'unknown' for me on Core 2023.3.2

**Comment by JCHH2** [comment]
I see there is a 'duration' that is correct in Z2M but is not exposed.  Has there simply been a change form `action_duration` to `duration`?

```
{
    "action": "",
    "action_duration": null,
    "battery": 100,
    "brightness": 255,
    "counter": 1,
    "linkquality": 185,
    "update": {
        "installed_version": 1107324829,
        "latest_version": 1107324829,
        "state": "idle"
    },
    "update_available": false,
    "duration": 2.089
}
```
