### ISSUE TITLE
TS0601_thermostat_1 problem with version 1.30.2

### ISSUE THREAD

**Issue by TwoPlayer** [Koenkk/zigbee2mqtt#16881]
### What happened?

After the update to 1.30.2 i can't power on or off my TS0601_thermostat_1 thermostats from the frontend in Home Assistant. When I try to user the power on or power off button of the climate entity nothing happen. I can manually power it off through the zigbee settings or the more info settings, but not through the buttons of the entity or through alexa. 

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20220219

### Adapter

zStack3x0 - Sonoff Zigbee Stick

### Debug log

I already restored the backup of the previous version so I can't give you a debug log. But if it is needed i can upgrade, generate it and downgrade again.

**Comment by Koenkk** [comment]
I think this is caused by https://github.com/Koenkk/zigbee-herdsman-converters/pull/5432, @Delorien84 could you check this?

**Comment by fishi0x01** [comment]
Having the same issue. Also restored the backup shortly after upgrading to 1.30.2, because `service: climate.turn_on` and `service: climate.turn_off` did not work anymore.

**Comment by Delorien84** [comment]
Sorry for that small typo :(
