### ISSUE TITLE
Display update progress on Home Assistant update entities

### ISSUE THREAD

**Issue by jackwilsdon** [Koenkk/zigbee2mqtt#16891]
### Is your feature request related to a problem? Please describe

Pressing the "Update" button on a zigbee2mqtt update entity in Home Assistant doesn't provide any feedback - there's no indication that the update has started or any progress updates on it.

### Describe the solution you'd like

The update entity should display the current update progress.

### Describe alternatives you've considered

Progress is currently displayed as notifications in the zigbee2mqtt dashboard (and in the logs), so I have to check there to see if an update started and its progress.

### Additional context

Here's what the update UI looks like currently for an entity that is in the process of updating:
![Screenshot_20230303-091049](https://user-images.githubusercontent.com/1843197/222679688-2a435727-8d1b-49d2-a8e0-87c88b474ae7.png)

**Comment by Koenkk** [comment]
AFAIK HA doesn't support such thing.
