### ISSUE TITLE
Add "ban" option to Devices if we Remove them.

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#169]
We should extend zigbee2mqtt to allow "device ban" because if you allow joining (default one) and then there is a device near you like something from your neighbour who is in joining mode too, its paired.

Unfortunately, I have just such a device and have to check if it connects flawed i have manually removed them and disable the "allowed joining".

**Comment by tb-killa** [comment]
We could use the https://github.com/zigbeer/zigbee-shepherd/wiki#API_remove function.

**Comment by tb-killa** [comment]
@Koenkk We should add json encode and parse ```friendly_name``` and the optional state ```reJoin``` with true or false (allow rejoin / ban).

**Comment by ryanbeaton** [comment]
Just noting here that blacklist has now been implemented.

https://github.com/Koenkk/zigbee2mqtt/issues/816#issuecomment-452394088
