### ISSUE TITLE
MAC transaction expired  (240) with Aqara roller shade companion E1 device

### ISSUE THREAD

**Issue by lluisd** [Koenkk/zigbee2mqtt#16909]
### What happened?

Aqara roller shade companion E1 device stops working. It was working at least during 3 days and now without doing anything it reports errors, also happens again. Don't know why and what to do. I use sonoff zigbee as coordinator in a synology ds920+

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

20221226

### Adapter

Sonoff zigbee 3.0 P

### Debug log

Zigbee2MQTT:error 2023-02-27 22:30:43: Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Zigbee2MQTT:info 2023-02-27 22:30:43: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"0x54ef4410002e019d"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2023-02-27 23:03:27: Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Zigbee2MQTT:info 2023-02-27 23:03:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"0x54ef4410002e019d"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2023-02-27 23:04:11: Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Zigbee2MQTT:info 2023-02-27 23:04:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"0x54ef4410002e019d"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:info 2023-02-27 23:04:27: Configuring '0x54ef4410002e019d'
Zigbee2MQTT:error 2023-02-27 23:04:55: Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":80,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Zigbee2MQTT:info 2023-02-27 23:04:55: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'position' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":80,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"0x54ef4410002e019d"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2023-02-27 23:05:39: Failed to configure '0x54ef4410002e019d', attempt 1 (Error: Read 0x54ef4410002e019d/1 aqaraOpple([1034], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))
Zigbee2MQTT:info 2023-02-27 23:05:39: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x54ef4410002e019d"},"error":"Failed to configure (Read 0x54ef4410002e019d/1 aqaraOpple([1034], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240)))","status":"error","transaction":"vpxe4-1"}'
Zigbee2MQTT:error 2023-02-27 23:06:23: Publish 'set' 'state' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Zigbee2MQTT:info 2023-02-27 23:06:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x54ef4410002e019d' failed: 'Error: Write 0x54ef4410002e019d/1 genAnalogOutput({"85":{"value":0,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"0x54ef4410002e019d"},"type":"zigbee_publish_error"}'

**Comment by muesli** [comment]
I experience the same issue with a SONOFF motion sensor (SNZB-03). This is a fatal error that terminates zigbee2mqtt (1.30.2) for me:

```
node[87815]: Error: Command 0x00124b0024XXXXXX/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
node[87815]:     at ZStackAdapter.sendZclFrameToEndpointInternal (/usr/share/webapps/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
node[87815]:     at Queue.executeNext (/usr/share/webapps/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```
