### ISSUE TITLE
[Feature request]: Changeability of the primary MQTT identifier for Devices

### ISSUE THREAD

**Issue by Timmmy001** [Koenkk/zigbee2mqtt#16912]
### Is your feature request related to a problem? Please describe

When transmitting via MQTT, the friendly name is used as the primary identifier for Devices ("zigbee2mqtt/**Restroom_Light**/set:...").
The problem starts when you change the friendly name, which is not common, but does happen and makes follow up works.

### Describe the solution you'd like

As in normal programming, it might be better to use the fixed IEEE address as id and to transfer the friendly name as an additional value.

### Describe alternatives you've considered

No other alternatives.

### Additional context

Example:
![grafik](https://user-images.githubusercontent.com/39485318/222903199-0defa18c-14b3-4aea-9170-62544280c531.png)

**Comment by Timmmy001** [comment]
I think it is still a good idea

**Comment by Timmmy001** [comment]
Sorry, but I think it is still a good idea

**Comment by P1Rebo** [comment]
Think also this is a good idea! Until now I used the description and was fine. But when integrating within HomeAssistant the description is not taken, e.g. As name of the device. In HA there can be an object_id which would also better fit to the zigbee2mqtt device identifier field. Friendly name could then be the name in HA.

**Comment by P1Rebo** [comment]
Ping. Come on it's not that much to do ;-)

**Comment by Timmmy001** [comment]
☕

**Comment by ZaikinaEvgeniya-2** [comment]
###

**Comment by Funkisl** [comment]
I also think it is still a good idea
