### ISSUE TITLE
[New device support]: ST72 Edison – E27 smart bulb

### ISSUE THREAD

**Issue by gdp2000** [Koenkk/zigbee2mqtt#16936]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-filament-st72-edison-%E2%80%93-e27-smart-bulb/8719514279179

### Database entry

{"id":63,"type":"Router","ieeeAddr":"0x001788010cc5d0d2","nwkAddr":27177,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LWV007","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":257,"inClusterList":[0,3,4,5,6,8,4096,64515,64514],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20201126","swBuildId":"1.78.1","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1678101130173,"defaultSendRequestWhen":"immediate"}

### Comments

This seems to be an unpopular model of the ST72 filament bulb without color temp adjustments. I wrote an external converter myself (mainly copy and paste, but I don't know if this is fully correct. OTA not working f.e.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['LWV007'],
    model: '9290030523',
    vendor: 'Philips', 
    description: 'Hue white filament Edison ST72 LED',
    extend: extend.light_onoff_brightness(),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
