### ISSUE TITLE
Light / Button Binding works the other way

### ISSUE THREAD

**Issue by Crumar** [Koenkk/zigbee2mqtt#16935]
### What happened?

Sonoff ZBMini is bound to group of Ikea GU 10 Lights, which are not attached to the ZBMini, but permanent Live wire.
![image](https://user-images.githubusercontent.com/2611791/223107282-83865ab4-732f-4a82-bc82-848d4b5459ff.png)
zm_br = light group
buero spots schalter = ZBMini

When I operate the wall switches attached to the ZBMini, nothing happens (except relay click).
When I toggle the light group from Home Assistant, the relay clicks and state changes in Z2M GUI.

### What did you expect to happen?

I expected that toggling the wall switch will turn the lights on/off.
I did not expected the light turning of or on to toggle the relay.

### How to reproduce it (minimal and precise)

Create OnOff Reporting on ZBMini
Bind OnOff to Light Group
Unbind OnOff from Coordinator
Toggle Light Group from Home Assisstant

### Zigbee2MQTT version

1.30.1 commit: eb878d3d

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

Logs:
![image](https://user-images.githubusercontent.com/2611791/223108194-898784d6-395a-44cb-a49c-2c762622284d.png)

**Comment by Crumar** [comment]
Anything that I could test?

**Comment by ulysserevient** [comment]
Hi,
I've you fond a solution to this problem ?
Thx

**Comment by Crumar** [comment]
No, but tested again last week, still same issue

**Comment by ulysserevient** [comment]
ok, but have you find a module that support binding ?

**Comment by Crumar** [comment]
Sadly, not.
