### ISSUE TITLE
Bticino K4027C keeps blinking green light

### ISSUE THREAD

**Issue by Empathy3286** [Koenkk/zigbee2mqtt#16948]
### What happened?

Hi,

I've got a bunch of "Bticino K4027 Shutter SW with level control" in the house.
I can successfully pair them with home assistant via zigbee2mqtt.
The shutter control has a little led light, and it keeps blinking green. 

Note: The green blinking is the "pairing mode" indicator. Even if i pair the device it keeps blinking green. Maybe the device doesn't receive back an "End pairing mode / successfull pairing exit pairing mode" message.

### What did you expect to happen?

The green blinking should turn off once i pair the device 

### How to reproduce it (minimal and precise)

1) "Permit Join" on Zigbee2mqtt
2) Press the little cog icon on the device to activare pairing mode, the led starts blinking green
3) Pairing successfull, led still blinking

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Dongle ZBDongle-E 3.0

**Comment by IvanDeMarco** [comment]
I have the same problems, you solved?

**Comment by Empathy3286** [comment]
> I have the same problems, you solved?

No. I still got the same problem. I've also tried a combee2 Adapter but the problem still persist. 
Maybe try switching to channel 11, and see if that works.

**Comment by managerfx** [comment]
i've the same problem. @Empathy3286 have you resolved?

**Comment by managerfx** [comment]
i've the same problem. @Empathy3286 have you resolved?

**Comment by IvanDeMarco** [comment]
I paring a lot of time the Bticino K4027 with home zigbee2mqtt until it works (also 5 or more times)

**Comment by andreapx** [comment]
> Thx @IvanDeMarco.
> 
> Here's an improved version of the instructions. I have personally executed this process three times in a row, and it worked for me.
> 
>     1. **Resetting the K4027C:**
>        Press the "bulb" shaped button on the K4027C device and hold it until the LED turns red. Wait for the device to reboot, and the LED will remain solid red.
> 
>     2. **Initial Association with Zigbee2MQTT:**
>        Associate the K4027C with Zigbee2MQTT following these steps:
>        a. Activate the association mode on Zigbee2MQTT.
>        b. Initiate the association process on the K4027C. (press the "bulb" button once)
>        c. Monitor the Zigbee2MQTT interface for a series of green pop-ups and the appearance of the new device.
>        d. If the K4027C doesn't complete the association properly, the device will keep flashing green.
> 
>     3. **Association Issue Workaround:**
>        If the K4027C doesn't associate correctly and continues flashing green, proceed as follows:
>        a. Restart the Docker instance of Zigbee2MQTT.
>        b. **Simultaneously** with the restart, perform the reset process on the K4027C until the LED remains red. The goal is to ensure Zigbee2MQTT doesn't detect the button reset, thus keeping it on the list of associated devices.
>        c. Verify that the K4027C is still present in the device list on Zigbee2MQTT.
>        d. Initiate the association process on the K4027C. (press the "bulb" button once)
>        The K4027C should quickly transition from flashing green to a solid green LED, indicating a successful association.
> 
>     4. **Percentage Control of Blinds:**
>        To achieve percentage control of the blinds, initiate a calibration by simultaneously pressing the "up" and "down" buttons on the K4027C until the LED turns orange.

I've tried everything, but for the love of me it keeps blinking green.
The logs on ZigBee2Mqtt says that it successfully paired, but it doesn't publish anything and it keeps blinking green.
I've tried resetting whit the container on, off, deleting it from the configuration, leaving it there, nothing seems to work.
@Koenkk how else can I troubleshoot this problem?
I have about 5 of them with the same problem.
The container is at the latest version.

**Comment by andreapx** [comment]
It appeared that the problem was the outdated (2022) firmware. After the update (the ones that I was able to update, a lot of bTicino devices gives me the "Device didn't respond to OTA request" error) I could pair the roller shutter.

**Comment by Diaoul** [comment]
I successfully applied the workaround from @managerfx above to add a Legrand 067776A. It took me several retries...

It seems that I had better results by enabling pairing from another Legrand device than the coordinator itself. Not sure it's related though but worth a try if you struggle.

**Comment by andreapx** [comment]
I've decided to contact bTicino support and straight away they told me that the gateway had a weak WiFi signal.
I've moved it closer to the AP and all the devices got updated in a short while.
WTF, why don't they put a warning in the app about the WiFi signal???

**Comment by m4r1k** [comment]
I encountered a similar pairing issue with many of these shutters. Here's the process that worked for me:

**Initiate Reset**: Press and hold the pair/reset button until the LED flashes once red.
**Trigger Pairing**: Press the pair/reset button once more (LED should still be steady red).
**Confirm Pairing**: The LED will turn back to blinking green. If it stops blinking after 5-10 seconds, pairing is successful. You may also hear a slight clicking sound. If the LED continues to blink, repeat from step 1.

Some shutters may require multiple pairing attempts. Be patient and persistent, one of mine took more than 20 times.
