### ISSUE TITLE
Cannot set region_upsert - UI keeps disappearing

### ISSUE THREAD

**Issue by markus-barta** [Koenkk/zigbee2mqtt#16940]
### What happened?

When trying to add a region within "region_upsert" and hitting the "+" it shows the UI for a few moments and then disappears again. Tried to empty the browser cache. Used other browser, etc.

See it in action:

[Screen recording 2,6MiB](https://user-images.githubusercontent.com/276789/223149935-942666f3-0814-4dbe-b0fa-f93c27fbe081.mov)

### What did you expect to happen?

UI should stay visible so I can configure the regions.

### How to reproduce it (minimal and precise)

Just hit "+" and wait a bit. See video :)

### Zigbee2MQTT version

 1.30.2 commit: cdf62ea

### Adapter firmware version

20210708

### Adapter

ZIGBEE 3.0 USB DONGLE

**Comment by Koenkk** [comment]
@nurikk I think this happens when states of other devices are published, could this be fixed?

**Comment by markus-barta** [comment]
Saw a PR with several mentions of this. Can I provide additional info or help in any other way?
