### ISSUE TITLE
[Heiman] New Smart occupancy Sensor HS1MIS-EF support

### ISSUE THREAD

**Issue by cespar** [Koenkk/zigbee2mqtt#16969]
### Link

https://www.heimantech.com/product/index.php?type=detail&id=72

### Database entry

{   "id": 11,   "type": "EndDevice",   "ieeeAddr": "0x5c0272fffee9bb8f",   "nwkAddr": 691,   "manufId": 4619,   "manufName": "HEIMAN",   "powerSource": "Battery",   "modelId": "PIRILLSensor-EF-3.0",   "epList": [     1   ],   "endpoints": {     "1": {       "profId": 260,       "epId": 1,       "devId": 263,       "inClusterList": [         0,         1,         3,         32,         1024,         1030,         2821       ],       "outClusterList": [         3,         6,         25,         4096       ],       "clusters": {         "genBasic": {           "attributes": {             "powerSource": 3,             "zclVersion": 3,             "appVersion": 33,             "stackVersion": 2,             "hwVersion": 16,             "dateCode": "2020.12.22"           }         },         "genPollCtrl": {           "attributes": {             "checkinInterval": 14400           }         }       },       "binds": [         {           "cluster": 32,           "type": "endpoint",           "deviceIeeeAddress": "0x00212effff094058",           "endpointID": 1         }       ],       "configuredReportings": [],       "meta": {}     }   },   "appVersion": 33,   "stackVersion": 2,   "hwVersion": 16,   "dateCode": "2020.12.22",   "zclVersion": 3,   "interviewCompleted": true,   "meta": {},   "lastSeen": 1678313389607,   "defaultSendRequestWhen": "active" }

### Comments

It seems that this device, in addition to sending occupancy data, gives luminosity values ​​in lux.
I tried to follow the supporting new device page as motion sensor but got stuck and it doesn't work normally.
It would be great to add it.

**Comment by cespar** [comment]
I would like to insist on asking for help to integrate this device.
I leave more information.
On debug mode I recieve these logs:
`debug 2023-08-08 00:57:05: Received Zigbee message from '0x5c0272fffee9bb8f', type 'raw', cluster 'genBasic', data '{"data":[13,11,18,81,241,200,80,73,82,73,76,76,83,101,110,115,111,114,45,69,70,45,33,2,0,0,0,0,1,7,1,1,1,16,0,200,0,60,0],"type":"Buffer"}' from endpoint 1 with groupID null
debug 2023-08-08 00:57:15: Received Zigbee message from '0x5c0272fffee9bb8f', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID null
debug 2023-08-08 00:57:17: Received Zigbee message from '0x5c0272fffee9bb8f', type 'readResponse', cluster 'genPollCtrl', data '{"checkinInterval":14400}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:01: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:04: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:07: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:10: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:13: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null`

And Z2M gives that cluster info:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/5715701/5455c288-3e10-4364-afb5-eacc02ba0ec7)

With other software I get this cluster info also:

`cespar
.cespar
En línea

Maskaruski — ayer a la 1:40
Imagen
no connection with the coordinator
where can I start debugging?
this happened couple hrs ago, becuase as of this morning all was fine
labaland — ayer a las 3:17
Hi! "Fading_time (numeric)" On my Presence sensor resets itself after some seconds after adding a new value. Is there any setting i can make for it to stay? Or can it be fixed maybe?
https://www.zigbee2mqtt.io/devices/YXZBRB58.html#fading-time-numeric
Rene Tode — ayer a las 4:08
power cycle your coordinator.
Rene Tode — ayer a las 4:10
make sure the device is awake when you send the command to it.
Maskaruski — ayer a las 4:14
Tried that and didn’t work, also rebooted the nuc. I have home assistant running on proxmox. Tried restoring and old HA backup and that didn’t work
Right now I paird a new tradfri router and it looks like that helped to bring the network back
But it’s kind of unstable
Like I said I don’t know what happed because it was working perfectly in the morning and suddenly just stopped working
Mr.Mad — ayer a las 13:38
Hi,
I just tried using Zigbee Dongle E with z2m, upgraded firmware. 
It works but after 28 devices I can’t pair anymore in. Is there anyways fix this. 
If I remove devices then i can pair in more.
Tinkerer — ayer a las 13:39
Are any of those devices routers?
Mr.Mad — ayer a las 13:39
All are routers ( powered ), no battery devices, my bad i didn’t mention it.
I tried pairing by selecting the nearest router permit join.
Chartreusito — ayer a las 13:47
FYI Dongle E is still experimental : https://www.zigbee2mqtt.io/guide/adapters/#experimental
Rene Tode — ayer a las 13:48
do you already use an USB extention cable?
Mr.Mad — ayer a las 13:54
Yes, using extension cable.
Rene Tode — ayer a las 13:55
did you try close to the coordinator, directly to the coordinator?
Mr.Mad — ayer a las 14:03
Yeap. I tried unplugging one light that refused to come in, and tried to pair it closer. No luck.
Also 3 devices keeps going in and out. If i try to repair, it repairs, but the dialogue box ‘ this device has left the network ‘ gets spammed.
Mr.Mad — ayer a las 14:05
Yes i am aware, thank you.
But any ideas on how usable this is Z2M is with this adapter.
Zigbee dongle E Has better LQI than P variant.
I have a friend who tried Skyconnect, which i think has the same Chipset, and he was full of praise.
I was thinking I would receive similar results. 😑
Chartreusito — ayer a las 14:09
I must admit i bought one myself when i first dabbled in home automation. Then i encountered problems as i deployed my network (devices dropping, etc.), and as soon as i realized it was experimental for z2m i returned it and switched to the P version. I know it doesn't help you right now but i felt it was worth sharing
Mr.Mad — ayer a las 14:17
Oh i see. Maybe i ll get myself a P i guess.
I was also trying be future proof.  Saw that adpater E can be flashed with multi-protocol firmware and used for matter. Not sure if i am right tho.
I saw a lot of issues regarding this adapter but also saw experience is generally better than 1 year before. But guess not for me 🤕
Rene Tode — ayer a las 15:01
thats probably causing more trouble then it solves.
you dont want devices in your network that are better at sending then in listening.
Rene Tode — ayer a las 15:04
most likely he uses it with ZHA, or he uses different routers and enddevices.
what devices do you have in your network? because its possible that you got brands that are not very compatible or just plain bad.
teymur88 — ayer a las 16:00
Hi All. My Z2M (version 1.28.4-1) is running on a MI Hub (DGNWG05LM) (Firmware Openwrt). I have 31 devices paired and all have been running no problem. Now I see that a new version of z2m is available (node-zigbee2mqtt - 1.30.3-1) would I be safe installing that? Thanks!
Tinkerer — ayer a las 16:15
1.32.2 is available
You should be absolutely fine to update, and if something goes wrong you can always downgrade
Giancs — ayer a las 16:25
Good morning, anyone knows if TS0049 has been mapped into zigbee2mqtt?
Imagen
Imagen
Rene Tode — ayer a las 16:39
if it is in the supported device list, then it is.
its possible it takes a few times pairing
its possible that you need to replace battery
or pair direct to the coordinator or a specific router
and i hope you took care of interference

its also possible that you got a different modelnr.
or that your z2m is not up to date.
Giancs — ayer a las 17:18
It seems it is in the white list, albeit the image of the website is different than mine.
I tried a couple if time to pair it. I'll check if it works better with the coordinator
teymur88 — ayer a las 17:21
Thanks. See the thing is that this is what I get:

root@MiHub:~# opkg list-upgradable|grep zigbee
node-zigbee2mqtt - 1.28.4-1 - 1.30.3-1

If I upgrade this is what I am going to get. That's the latest available. Unless there is another source where I can pull the 1.32.2 from to run on openwrt. 
Swede — ayer a las 21:32
Oh! I use the same Zigbee Dongle E and own 27 devices. 24 of them paired at this moment. Fingers crossed I won't suffer the same problem soon...
cespar — hoy a las 0:59
hello!!  I'm trying to add new device, could you help me to do it? It's about this: https://www.heimantech.com/product/?type=detail&id=72  HS1MIS or PIRILLSensor-EF-3.0
I recieved this logs
debug 2023-08-08 00:57:05: Received Zigbee message from '0x5c0272fffee9bb8f', type 'raw', cluster 'genBasic', data '{"data":[13,11,18,81,241,200,80,73,82,73,76,76,83,101,110,115,111,114,45,69,70,45,33,2,0,0,0,0,1,7,1,1,1,16,0,200,0,60,0],"type":"Buffer"}' from endpoint 1 with groupID null
debug 2023-08-08 00:57:15: Received Zigbee message from '0x5c0272fffee9bb8f', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID null
debug 2023-08-08 00:57:17: Received Zigbee message from '0x5c0272fffee9bb8f', type 'readResponse', cluster 'genPollCtrl', data '{"checkinInterval":14400}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:01: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:04: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:07: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:10: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
debug 2023-08-08 00:58:13: Received Zigbee message from '0x5c0272fffee9bb8f', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":33,"imageType":17698,"manufacturerCode":4619}' from endpoint 1 with groupID null
And it has those clusters: 
Imagen
I tried use similiar adapter other PIR sensor of heimans but it doesn't work. Also I tried use a common adapter with battery, illuminance and occupancy but it doesn't work. With this information, is it posible integrate this sensor in z2m?
Rene Tode — hoy a la 1:45
if existing code isnt working, that info is most likely not enough.
most likely, you will need a heimann hub, app and sniffer to get the needed information
cespar — hoy a las 7:14
With other software I can read tigso information:
I don't know if you can see the file
{
    "ieee": "5c:02:72:ff:fe:e9:bb:8f",
    "nwk": 151,
    "status": 2,
    "lqi": "255",
    "rssi": "-71",
Expandir
message.txt
6 KB
cespar — hoy a las 7:41
I tested using others convertes like TY0202 or PIR_TPV16 but it doesn't send data
I read this https://zigbee.blakadder.com/Heiman_HS1MS.html but it isn't exactly the same
﻿
{
    "ieee": "5c:02:72:ff:fe:e9:bb:8f",
    "nwk": 151,
    "status": 2,
    "lqi": "255",
    "rssi": "-71",
    "last_seen": "1691471557.795355",
    "node_descriptor": "02:40:80:0b:12:52:52:00:00:2c:52:00:00",
    "endpoints": [
        {
            "id": 1,
            "status": 1,
            "device_type": 263,
            "profile_id": 260,
            "manufacturer": "HEIMAN",
            "model": "PIRILLSensor-EF-3.0",
            "output_clusters": [
                {
                    "id": 3,
                    "name": "Identify",
                    "attributes": []
                },
                {
                    "id": 6,
                    "name": "On\/Off",
                    "attributes": []
                },
                {
                    "id": 25,
                    "name": "Ota",
                    "attributes": []
                },
                {
                    "id": 4096,
                    "name": "LightLink",
                    "attributes": []
                }
            ],
            "input_clusters": [
                {
                    "id": 0,
                    "name": "Basic",
                    "attributes": [
                        {
                            "id": 0,
                            "name": "zcl_version",
                            "value": 3
                        },
                        {
                            "id": 1,
                            "name": "app_version",
                            "value": 33
                        },
                        {
                            "id": 2,
                            "name": "stack_version",
                            "value": 2
                        },
                        {
                            "id": 3,
                            "name": "hw_version",
                            "value": 16
                        },
                        {
                            "id": 4,
                            "name": "manufacturer",
                            "value": "HEIMAN"
                        },
                        {
                            "id": 5,
                            "name": "model",
                            "value": "PIRILLSensor-EF-3.0"
                        },
                        {
                            "id": 6,
                            "name": "date_code",
                            "value": "2020.12.22"
                        },
                        {
                            "id": 7,
                            "name": "power_source",
                            "value": 3
                        }
                    ]
                },
                {
                    "id": 1,
                    "name": "Power Configuration",
                    "attributes": []
                },
                {
                    "id": 3,
                    "name": "Identify",
                    "attributes": []
                },
                {
                    "id": 32,
                    "name": "Poll Control",
                    "attributes": [
                        {
                            "id": 0,
                            "name": "checkin_interval",
                            "value": 14400
                        }
                    ]
                },
                {
                    "id": 1024,
                    "name": "Illuminance Measurement",
                    "attributes": [
                        {
                            "id": 0,
                            "name": "measured_value",
                            "value": 31
                        }
                    ]
                },
                {
                    "id": 1030,
                    "name": "Occupancy Sensing",
                    "attributes": [
                        {
                            "id": 0,
                            "name": "occupancy",
                            "value": 1
                        }
                    ]
                },
                {
                    "id": 2821,
                    "name": "Diagnostic",
                    "attributes": []
                }
            ]
        }
    ],
    "signature": {
        "manufacturer": "HEIMAN",
        "model": "PIRILLSensor-EF-3.0",
        "node_desc": {
            "logical_type": 2,
            "complex_descriptor_available": 0,
            "user_descriptor_available": 0,
            "reserved": 0,
            "aps_flags": 0,
            "frequency_band": 8,
            "mac_capability_flags": 128,
            "manufacturer_code": 4619,
            "maximum_buffer_size": 82,
            "maximum_incoming_transfer_size": 82,
            "server_mask": 11264,
            "maximum_outgoing_transfer_size": 82,
            "descriptor_capability_field": 0
        },
        "endpoints": {
            "1": {
                "profile_id": 260,
                "device_type": 263,
                "input_clusters": [
                    0,
                    1,
                    3,
                    32,
                    1024,
                    1030,
                    2821
                ],
                "output_clusters": [
                    3,
                    6,
                    25,
                    4096
                ]
            }
        }
    },
    "class": "zigpy.device"
}
`
I appreciate your help.
Regards.

**Comment by cespar** [comment]
with deconz software I get this:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5715701/ee4bc60a-ac65-47e0-9491-729e8ae78715)

**Comment by mario42004** [comment]
Regards Cesar. Each converter bases its work on the idea of a group of methods called attributes belonging to a high level structure named cluster. I mean, a cluster is a set of attributes related to a specific endpoint.  So, please take into account that each endpoint performs different task. For instance, the reading of the battery value could be obtained from a different endpoint compared if you are reading a illuminance value. Based on this idea, you have to configure the sensor to read the expected data by the zigbee2mqtt platform. I will share with you an example of a converter.



// Version 1.3
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['PIRILLSensor-EF-3.0'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'HS1MIS-3.0' , // Vendor model number, look on the device for a model number
    vendor: 'HEIMAN', // Vendor of the device (only used for documentation and startup logging)
    description: 'Smart occupancy sensor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
//    fromZigbee: [fz.ias_occupancy_alarm_1],
    fromZigbee: [fz.occupancy, fz.battery, fz.illuminance],
    toZigbee: [],
    //exposes: [e.illuminance()],


   configure: async (device,cordinatorEndpoint,logger)=>{
        const endpoint0 = device.getEndpoint(1)
	const endpoint1 = device.getEndpoint(1)
	await reporting.bind(endpoint0, cordinatorEndpoint, ['msOccupancySensing','genPowerCfg']);
	await reporting.batteryPercentageRemaining(endpoint0)
	await reporting.occupancy(endpoint0)
	await reporting.bind(endpoint1, cordinatorEndpoint, ['msIlluminanceMeasurement']);
	await reporting.illuminance(endpoint1)

},
    exposes: [e.occupancy(), e.battery(),e.illuminance()],

};
module.exports = definition;
