### ISSUE TITLE
[New device support]: IKEA symfonisk sound remotegen2

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#16971]
### Link

https://www.ikea.com/us/en/p/symfonisk-sound-remote-gen-2-30527312/

### Database entry

{"id":61,"type":"EndDevice","ieeeAddr":"0x1c34f1fffea56f3e","nwkAddr":10835,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"SYMFONISK sound remote gen2","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0,1,3,32,4096,64599],"outClusterList":[3,4,6,8,25,4096,64639],"clusters":{"genPollCtrl":{"attributes":{"checkinInterval":172800}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c2772c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":16,"stackVersion":103,"hwVersion":1,"dateCode":"20211214","swBuildId":"1.0.012","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1678364264524,"defaultSendRequestWhen":"active"}

### Comments

Hello 

I try adding this device without success can you please help me in order to get this to work 

Thank you for your support and best regards

**Comment by MattWestb** [comment]
Im very sorry but you have posting data from one `SYMFONISK Sound Controller` and not one `SYMFONISK sound remote gen1`= the first gen round one and not the new 2 gen with 7 buttons.

**Comment by MiAutomations** [comment]
> Im very sorry but you have posting data from one `SYMFONISK Sound Controller` and not one `SYMFONISK sound remote gen1`= the first gen round one and not the new 2 gen with 7 buttons.

Thank you. My mistake I selected  the 1gen instead of the 2Gen 

Now its corrected

**Comment by MattWestb** [comment]
Looks better :-))

Its the chipping version of the firmware `1.0.012` with one EP that is having different commands as the Dirigera is updating to `1.0.32` that is having 3 EPs.

**Comment by MiAutomations** [comment]
> Looks better :-))
> 
> Its the chipping version of the firmware `1.0.012` with one EP that is having different commands as the Dirigera is updating to `1.0.32` that is having 3 EPs.

Yes It's the new version of the SYMFONISK Remote GEN 2 from IKEA that have more buttons, also works with the Sonos Speakers
