### ISSUE TITLE
[New device support]: Added support for Philips Hue White and Color Ambiance Iris Smart Lamp, Works with Amazon Alexa, Apple Homekit and Google Assistant, Bluetooth Compatible, Corded, White

### ISSUE THREAD

**Issue by GoldbergAlexander** [Koenkk/zigbee2mqtt#16976]
### Link

https://www.amazon.com/gp/product/B08K2L89RT

### Database entry

{"id":5,"type":"Router","ieeeAddr":"0x0017880109c3df28","nwkAddr":2088,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929002376901","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1678376885461,"defaultSendRequestWhen":"immediate"}

### Comments

This looks like a model number issue as I see the device should already be supported (https://www.zigbee2mqtt.io/devices/929002376701.html). I've created a PR here to address: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5561

### Supported color modes

color, temperature, RGB

### Color temperature range

Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Merged the pr, thanks!
