### ISSUE TITLE
Some routers have no link to parent on map

### ISSUE THREAD

**Issue by MikOsle** [Koenkk/zigbee2mqtt#16979]
### What happened?

When loading a map some of the routers in my network have no parent link to the coordinator or another router. Some routers seem to exist as small clusters with links only to each other but not the coordinator.
Though, when checking off 'IsASibling' all routers have a link to another router and to the coordinator, except for one which have no solid line to the coordinator. What could be the reason for these missing links?
![Picture1](https://user-images.githubusercontent.com/46725638/224121305-89f5adf2-59ef-4042-9cdd-7a074036459d.png)
![Picture2](https://user-images.githubusercontent.com/46725638/224123047-c16f44f9-3e0d-40d7-8ae7-2ec8aef44f8c.png)

### What did you expect to happen?

All routers to have a link parent

### Zigbee2MQTT version

1.30.2 commit: unknown

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle-E

**Comment by Koenkk** [comment]
See https://www.zigbee2mqtt.io/guide/faq/#why-are-some-links-missing-from-my-networkmap

**Comment by MikOsle** [comment]
> See https://www.zigbee2mqtt.io/guide/faq/#why-are-some-links-missing-from-my-networkmap

Thanks. Yes, I had already read it, but I understand it as only between end device to router or coordinator. My issue is the link between router to router which are not battery powered

**Comment by h00g** [comment]
> > See https://www.zigbee2mqtt.io/guide/faq/#why-are-some-links-missing-from-my-networkmap
> 
> Thanks. Yes, I had already read it, but I understand it as only between end device to router or coordinator. My issue is the link between router to router which are not battery powered

I have the same situation with
- two IKEA Trådfri bulbs forming a cluster of their own without any parent link to a router or coordinator
- two cases of a IKEA Trådfri bulb and plug respectively and a remote forming such separate clusters with no parent

![image](https://github.com/user-attachments/assets/21e06ef9-7b48-464a-9042-e2618b4dac24)
