### ISSUE TITLE
Lixee ZLinky is flooding my System Journal

### ISSUE THREAD

**Issue by ALaDoffe** [Koenkk/zigbee2mqtt#16987]
### What happened?

Hello 

Each minute (as the congfigured polling interval) lixee Zlinky_TIC device writes a line in the journalctl.

![image](https://user-images.githubusercontent.com/62749332/224365340-7cb828d9-4c25-4458-a5a6-35d295ff076b.png)

Nothing about this information in zigbee2mqtt.log 

Is the a way to avoid this behaviour ?

### What did you expect to happen?

Logs should only go the zigbee2mqtt.log regarding the log level setting.

### Zigbee2MQTT version

1.30.2-dev commit: 43394b33

### Adapter firmware version

20221226

### Adapter

CC2652P

**Comment by ALaDoffe** [comment]
Changing z2m log level to warn resolve the issue.

**Comment by tomav** [comment]
@ALaDoffe you're just hiding the problem here.
