### ISSUE TITLE
Tuya TS0601 model BRT-100-TRV OTA update fails with "No image available for imageType '5634'"

### ISSUE THREAD

**Issue by mdzhigarov** [Koenkk/zigbee2mqtt#16989]
### What happened?

Trying to update Tuya TS0601 model BRT-100-TRV via OTA and getting error: "No image available for imageType '5634'"
![image](https://user-images.githubusercontent.com/1481379/224401937-183e660f-b4de-40a0-b74e-c0940c7fc04f.png)
![image](https://user-images.githubusercontent.com/1481379/224402385-80c64936-7ca7-45f3-88a0-af07ccaee3c1.png)

### What did you expect to happen?

Either a successful update or zigbee2mqqt should not suggest that the Tuya device supports OTA updates at all.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ZBDongle-E

### Debug log

[z2m.log](https://github.com/Koenkk/zigbee2mqtt/files/10945160/z2m.log)

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/16584#issuecomment-1422885637

**Comment by mdzhigarov** [comment]
Is there a chance to hide or disable the OTA if it's not supported?

**Comment by Koenkk** [comment]
Currently not, as we don't know wether OTA is supported upfront. It would be better if someone grabs the OTA.
