### ISSUE TITLE
IKEA Styrbar remote E2001/E2002 throws exception when using the on button with zigbee2mqtt versions >1.28.0

### ISSUE THREAD

**Issue by Fruckiwacki** [Koenkk/zigbee2mqtt#16991]
### What happened?

After updating zigbee2mqtt to a version greater than 1.28, my IKEA Styrbar remote (firmware 1.0.024) throws an exception when pushing the on button. 

### What did you expect to happen?

On zigbee2mqtt versions <1.28.1 all buttons work as expected

### How to reproduce it (minimal and precise)

Upgrade zigbee2mqtt to a version >1.28.0 and press the on button.

### Zigbee2MQTT version

>1.28.0

### Adapter firmware version

20221226

### Adapter

SONOFF CC2652P 

### Debug log

Debug 2023-03-10 21:38:49 Received Zigbee message from 'Wohnzimmer STYRBAR remote', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0

Error 2023-03-10 21:38:49 Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'meta')}

Debug 2023-03-10 21:38:49 TypeError: Cannot read properties of undefined (reading 'meta') at Object.hasAlreadyProcessedMessage (/app/node_modules/zigbee-herdsman-converters/lib/utils.js:71:15) at Object.convert (/app/data/extension/externally-loaded.js:19:23) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:525:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27) at Controller.emit (node:events:513:28) at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14) at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:726:18) at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70)

**Comment by Koenkk** [comment]
You are using an incompatible external converter, remove it from your `configuration.yaml` as the device is supported out of the box now.
