### ISSUE TITLE
SJCGQ11LM (Xiaomi Water Leak Sensor) doesn't report immediately

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#17]
But does with the native gateway: https://www.youtube.com/watch?time_continue=149&v=8yGm2vH8HYQ

**Comment by Koenkk** [comment]
@starkun it reports immediately after you drop it into the water? What configuration do you have?

**Comment by tube0013** [comment]
@Koenkk I'm the who posted this in the HA forums.  I just tried running cat /dev/ttyACM0 and immediately get feed back when I drop it into water, also get feedback as soon as I dry it off.

**Comment by kirovilya** [comment]
You try to detect leak event with attReport message. But statusChange event is more good for this.
Look at https://github.com/kirovilya/ioBroker.zigbee/blob/master/main.js#L523

**Comment by ciotlosm** [comment]
@kirovilya do you have a description between the differen attrReport, devChange, statusChange? Would be great when adding more devices.

**Comment by tb-killa** [comment]
@ciotlosm Look here: https://github.com/zigbeer/zigbee-shepherd/wiki#event-ind
- 'ind'

devIncoming
devLeaving
devChange
devStatus
attReport

**Comment by kirovilya** [comment]
@ciotlosm Unfortunately not know. These were obtained by experience and in google.
Different devices uses different message type.

**Comment by ciotlosm** [comment]
Thanks @tb-killa

**Comment by kirovilya** [comment]
You also need modification of zigbee-shepherd library with this events support.
Like commit in my fork https://github.com/kirovilya/zigbee-shepherd/commit/77eee0836bb8866f28e843e89d060376cd9debca from not applied PR https://github.com/zigbeer/zigbee-shepherd/pull/6

**Comment by Koenkk** [comment]
Thank you very much @kirovilya, works perfect now!
