### ISSUE TITLE
LEDVANCE SMART+ panel 60 x 60cm - NO power on behavior after 1.30.2 

### ISSUE THREAD

**Issue by Mosher23** [Koenkk/zigbee2mqtt#17014]
### What happened?

After update to 1.30.2 Power On Behavior disabled in Device settings. 
Trying to set this parameter give an error. See logs.
<img width="658" alt="Screenshot 2023-03-12 at 14 37 53" src="https://user-images.githubusercontent.com/8256425/224548308-b6b09462-f950-46e3-ab9d-74701d666103.png">

Info:
Firmware build date  Sep 29 2021
Firmware version 01056400
Manufacturer  Ledvance
Model  [4058075181472](https://www.zigbee2mqtt.io/devices/4058075181472.html#ledvance-4058075181472)

### What did you expect to happen?

Being able to set PowerOnBeahavior

### How to reproduce it (minimal and precise)

Update Z2M to 1.30.2

### Zigbee2MQTT version

1.30.2 

### Adapter firmware version

20220219

### Adapter

Sonoff USB Dongle-Plus

### Debug log

error 2023-03-12 14:32:37Publish 'set' 'power_on_behavior' to 'Bedroom_Ceiling' failed: 'Error: Write 0xf0d1b8000013cd2b/1 genOnOff({"startUpOnOff":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by Koenkk** [comment]
Disabled it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
