### ISSUE TITLE
RTX ZVG1 ignores the timer value and water consumed

### ISSUE THREAD

**Issue by jvcsw** [Koenkk/zigbee2mqtt#17011]
### What happened?

When I change the timer value (for example, setting 20 minutes) the valve execute auto off after 10  minutes and the water consumed is 0.

These problems has always existed, since the beginning and it still does not work well.

This is the device:

https://www.zigbee2mqtt.io/devices/ZVG1.html

### What did you expect to happen?

Auto off action close the valve accordind to the timer value.
The water consuming value increase.

### How to reproduce it (minimal and precise)

Change the timer value with a value different to 10.
Open valve
Wait 10 minutes.
Check last valve open duration.
Check water consumed sensor value.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

-

### Adapter

-

### Debug log

MQTT publish: topic 'zigbee2mqtt/0xxxxxxxxxxxxxxx', payload '{"battery":50,"cycle_timer_1":"","cycle_timer_2":"","cycle_timer_3":"","cycle_timer_4":"","last_valve_open_duration":10,"linkquality":76,"normal_schedule_timer_1":"","normal_schedule_timer_2":"","normal_schedule_timer_3":"","normal_schedule_timer_4":"","state":"OFF","timer":20,"timer_state":"enabled","timer_time_left":1,"water_consumed":"0.00","weather_delay":"disabled"}'

_No response_

**Comment by jvcsw** [comment]
@Koenkk Do you know how to solve this?

Thanks

**Comment by fliespl** [comment]
@jvcsw did you every sorted it out?

**Comment by fliespl** [comment]
Is your model recognized as well as: _TZE200_81isopgh?

Im my case my only issue is timer being unreliable. Set to 15, but still finishes after 10 minutes.

https://ss.codeone.pl/ss-2023-05-30-11-20-33-1685438433-lIdS4RdL.png
https://ss.codeone.pl/ss-2023-05-30-11-21-11-1685438471-7UumjkDy.png

Yet, water consumption works when I wait for timer to kill (not if I switch it manually).
https://ss.codeone.pl/ss-2023-05-30-11-21-54-1685438514-gnV0CwWa.png

**Comment by markhendrix79** [comment]
I'm having the same issues as well.  I can't disable the timer and any changes do not take affect - it just continues to turn off after 10 minutes, regardless.  Very frustrating.  I'm also not seeing water consumed.  My MQTT device info looks just like the screenshot above.  I'm sad to see this issue is listed as closed, but wanted to add a comment and follow any updates that may appear.

**Comment by cptbucky** [comment]
I'm currently having the same issues, I've never seen a water usage figure come through, as for the timer I appear to be able to set it to 60 and have the timer last for 60 minutes, I think this must follow @ytzelf 's workaround. 

If I switch on the device again the timer remains at 60 but the "time left on the timer" counts down from 10 and shuts off after 10. This feels like a bit of an odd issue, does the device's timer reset on every use? Anyway I'll perhaps follow the workaround for now. Does anyone use the Tuya app to know what the behaviour is? Or know where the device integration lives within z2m that I might look through?

**Comment by zivillian** [comment]
I'm using the following json to enable the valve via MQTT:
```json
{
  "state":"ON",
  "timer":30
}
```

this result in the timer being respected and the water consumed to be reported (even if it is totally wrong):

![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/6039253/a8b3597d-897a-4406-845a-281da2e276d7)

**Comment by jvcsw** [comment]
> I'm currently having the same issues, I've never seen a water usage figure come through, as for the timer I appear to be able to set it to 60 and have the timer last for 60 minutes, I think this must follow @ytzelf 's workaround.
> 
> If I switch on the device again the timer remains at 60 but the "time left on the timer" counts down from 10 and shuts off after 10. This feels like a bit of an odd issue, does the device's timer reset on every use? Anyway I'll perhaps follow the workaround for now. Does anyone use the Tuya app to know what the behaviour is? Or know where the device integration lives within z2m that I might look through?

Here there is the code:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/rtx.ts

I don't understand why using MQTT it works fine and with HA it doesn't.

**Comment by jvcsw** [comment]
Last week @kamaradclimber changed the unit from "l" to "L", maybe that solves the water consumed problem, or not...

https://github.com/Koenkk/zigbee-herdsman-converters/pull/5897/commits/d5ba786745cd8dc9fc6ca080a9db0b96d7faf4d2

**Comment by markhendrix79** [comment]
I just wanted to add here in case anyone finds this thread later - this issue was fixed in release 1.32.2.  I had been using the device through the tuya integration, which still didn't pass in a working timer to home assistant.  I switched back over to z2m today and everything is working - no extra scripts or json mods required.

**Comment by jvcsw** [comment]
It doesn't tell me the water consumed, nor does it respect the watering time.

**Comment by kidekoop2016** [comment]
I an using z2m 1.40.2-1. HA Supervised updated (supervisor-2024.10.2).
Water consumed is always at 0. **It doesn't work.** 
Have you got any solution, please?
thanks

**Comment by PacmanForever** [comment]
I haven't found any solution, everything remains the same.
