### ISSUE TITLE
Philips 9290019758 (re)joins network, even if not allowed

### ISSUE THREAD

**Issue by okastl** [Koenkk/zigbee2mqtt#17038]
### What happened?

Philips 9290019758 Hue motion outdoor sensor can rejoin the network, even if joining of devices is disabled in z2m.
I don't know if this is a problem specific to Philips 9290019758, or if this is a more general security problem.

### What did you expect to happen?

No devices should be able to join, unless joining is allowed.

### How to reproduce it (minimal and precise)

1.) Add Philips 9290019758 to a network.
2.) Disable device joining in z2m.
3.) Remove the Philips 9290019758 from the network.
3a.) Optional: To make sure, there aren't any leftovers, you can reboot z2m.
4.) Wait 3 minutes. The Philips 9290019758 will join the network, interviewed and configured.

I have attached a herdsman log and a normal log without the reboot of z2m.

### Zigbee2MQTT version

1.30.2-dev commit: 4272d9a1

### Adapter firmware version

20221226

### Adapter

Slaesh CC2652RB

### Debug log

[log.zip](https://github.com/Koenkk/zigbee2mqtt/files/10967892/log.zip)
[Philips 9290019758.zip](https://github.com/Koenkk/zigbee2mqtt/files/10967895/Philips.9290019758.zip)

**Comment by hellcry37** [comment]
I have the same problem, just happens to me last night, ohh how I search for this ticket, I knew it was around but could not find it again.

So what happen to me I try to make a motion sensor leave the network, ofc with network closed for joins. The device leaves the network normal way and then, surprise surprise, re joins re configures and works as nothing happen :))
https://www.zigbee2mqtt.io/devices/9290012607.html

Tried to turn on and off again Permit Join for the network, behavior repeats as soon as device leaves the network, it comes back in no problem.

Zigbee2MQTT version:
1.30.3 commit: 24c6b2e

Coordinator revision:
20220219 (for me 20221226 was a fail)

Adapter:
Electrolama zig-a-zig-ah! (zzh!)

**Comment by okastl** [comment]
bump
