### ISSUE TITLE
[Feature request]: Develco KEYZB-110 expose RFID reader

### ISSUE THREAD

**Issue by luisetex84** [Koenkk/zigbee2mqtt#17043]
### Is your feature request related to a problem? Please describe

Develco KEYZB-110 don't show any information when a RFID tag is near its RFID reader

### Describe the solution you'd like

I would like to operate the keypad with RFID tags

### Describe alternatives you've considered

I've considered trying with ZHA if this function is supported but I don't have a ZHA dongle

### Additional context

Other functionality like presence sensor is not supported

**Comment by luisetex84** [comment]
I was using wrong RFID tags. If you use the right ones the info appears in action_code

**Comment by davidsmoker** [comment]
Hello, which RFID tags did you use?
I'm still trying to get this working :-(
