### ISSUE TITLE
[New device support]: Immax Neo lite Smart plug 2 sockets

### ISSUE THREAD

**Issue by wociscz** [Koenkk/zigbee2mqtt#17041]
### Link

https://www.tipa.eu/en/smart-double-socket-immax-neo-07752l-zigbee-tuya/d-262620/

### Database entry

{"id":40,"type":"Router","ieeeAddr":"0xa4c138417d067a80","nwkAddr":7198,"manufId":4417,"manufName":"_TZ3000_jak16dll","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_jak16dll","zclVersion":3,"appVersion":192,"modelId":"TS011F","powerSource":1}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c12ada","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c12ada","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c12ada","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-892627439},"lastSeen":1678808817781,"defaultSendRequestWhen":"immediate"}

### Comments

This device is wrongly detected as TS011F_plug_1 (single socket plug).
It can be operated as a single socket, without ability to control the sockets separately. 
Not supported in dev branch.
Don't know how to proceed with adding new convertor - if it is paired as "known/supported" but with wrong parameters and/or as a wrong device.

**Comment by thebang2** [comment]
Any further infos for that?
