### ISSUE TITLE
Problems with devices in multiple groups even though optimistic = false

### ISSUE THREAD

**Issue by yunoh87** [Koenkk/zigbee2mqtt#17050]
### What happened?

Got 4 zigbee sirens for use as doorbell and alert sounds.

Created group _sirens_doorbells_ containing all 4 devices and a second group _sirens_pending_ only containing 2 of these devices.

Set optimistic: false to both groups.

However, when I send a command to _sirens_pending_ all 4 devices are activated instead of the intended 2 devices.

My best guess is that this is due to optimistic: false is not being respected and the larger _sirens_doorbell_ group is activated due to 2 of them being so.

I may also completely have misunderstood the way this is supposed to function.

From configuration.yaml

  '1':
    friendly_name: sirens_doorbell
    optimistic: false
    devices:
      - 0xa4c13826dcb2a9fc/1
      - 0xa4c1389f4b8acb79/1
      - 0xa4c13828c924a395/1
      - 0xa4c138a8eeb334c6/1
  '2':
    friendly_name: sirens_pending
    optimistic: false
    devices:
      - 0xa4c1389f4b8acb79/1
      - 0xa4c13828c924a395/1

### What did you expect to happen?

I expected only 2 devices to be activated when publishing command to their group.

### How to reproduce it (minimal and precise)

Create 2 groups in z2m
Place all devices in one group
Place a few devices in the other group

Send activation command to the smaller group.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

sonoff zigbee 3.0 usb dongle plus

**Comment by lux73** [comment]
i am using Groups with different Bulbs

try to delete **/1** from your Devices - don't know why you had add this
