### ISSUE TITLE
BRT-100-TRV not recognized

### ISSUE THREAD

**Issue by schumissimo63** [Koenkk/zigbee2mqtt#17067]
### What happened?

Hello everyone, I'm coming to you because I've been struggling with Z2M for 2-3 days, I'm installing a friend's home automation, I need to pair 6 Moes thermostatic valve heads BRT-100-TRV, I have a conbee 2 key , basically when I test on my network the heads are recognized immediately, on the other hand impossible to pair them on its config. I tried everything, I even left on a clean config, nothing to do the peripherals are not recognized or with half of the entities. I put the key of my network on his NUC, same problem, on the other hand I did not test his key on mine because I do not want to risk anything and have to redo everything on my installation. I also installed and uninstalled Z2M several times, it did nothing, I tested with ZHA, same problem, the device is recognized but not completely. I changed the frequency of the key, same result. You are my last hope.....

homeassistant: true
mqtt:
  server: mqtt://192.168.1.173:1883
  user: mathmqtt
  password: XXXXXXXXXX
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2681506-if00
  adapter: deconz
frontend:
  port: 8099
devices: {}
advanced:
  log_level: debug
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 15

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

2.20.01 19/09/2022

### Adapter

ConBee_II_DE2681506-if00

### Debug log

[22:12:30] INFO: Preparing to start...
[22:12:30] INFO: Socat not enabled
[22:12:31] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-03-17 22:12:33: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2023-03-17 22:12:33: Logging to console and directory: '/config/zigbee2mqtt/log/2023-03-17.22-12-33' filename: log.txt
Zigbee2MQTT:debug 2023-03-17 22:12:33: Removing old log directory '/config/zigbee2mqtt/log/2023-03-17.21-33-09'
Zigbee2MQTT:info  2023-03-17 22:12:33: Starting Zigbee2MQTT version 1.30.2 (commit #unknown)
Zigbee2MQTT:info  2023-03-17 22:12:33: Starting zigbee-herdsman (0.14.96)
Zigbee2MQTT:debug 2023-03-17 22:12:33: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[15],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2681506-if00"}}'
Zigbee2MQTT:info  2023-03-17 22:12:33: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-03-17 22:12:33: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
Zigbee2MQTT:debug 2023-03-17 22:12:36: Zigbee network parameters: {"channel":15,"extendedPanID":"0xdddddddddddddddd","panID":6754}
Zigbee2MQTT:info  2023-03-17 22:12:36: Currently 1 devices are joined:
Zigbee2MQTT:info  2023-03-17 22:12:36: 0x003c84fffef2e327 (0x003c84fffef2e327): Not supported (Unknown)
Zigbee2MQTT:info  2023-03-17 22:12:36: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2023-03-17 22:12:37: Connecting to MQTT server at mqtt://192.168.1.173:1883
Zigbee2MQTT:debug 2023-03-17 22:12:37: Using MQTT login with username: mathmqtt
Zigbee2MQTT:info  2023-03-17 22:12:37: Connected to MQTT server
Zigbee2MQTT:info  2023-03-17 22:12:37: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2023-03-17 22:12:37: Started frontend on port 0.0.0.0:8099

**Comment by FPMilan** [comment]
where you able to resolve it? I can also not find 2/3 BRT-100-TRV thermostats in my setup. They not even show up in any z2m logs. Any ideas appreciated, thanks. @schumissimo63
