### ISSUE TITLE
Legrand 067773, 002a firmware only Toggle action 

### ISSUE THREAD

**Issue by mkapuscinski** [Koenkk/zigbee2mqtt#17069]
### What happened?

I have two Legrand switches with firmware 002a

after pressing a button [no difference if ON or OFF button is being pressed], I am getting only TOGGLE action
After pressing it twice, a am getting only OFF action.

This issue is visible only with Legrand 067773 with firmware 002a 

all other Legrand 067773 with older firmware [001e] works OK

### What did you expect to happen?

pressing ON -> ON action
pressing OFF -> OFF action

### How to reproduce it (minimal and precise)

Press the buttons on 067773 with 002a firmware

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

26720700

### Adapter

deconz / conbee II

### Debug log

Info 2023-03-18 14:53:23MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":null,"battery":100,"last_seen":"2023-03-18T13:53:23.866Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"valena_balkon_1","ieee_address":"0x0004740000c44e73"},"type":"device_announce"}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"valena_balkon_1"},"type":"device_announced"}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":null,"battery":100,"last_seen":"2023-03-18T13:53:24.058Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":"toggle","action_group":6,"battery":100,"last_seen":"2023-03-18T13:53:24.082Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":"","battery":100,"last_seen":"2023-03-18T13:53:24.082Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1/action', payload 'toggle'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":null,"battery":100,"last_seen":"2023-03-18T13:53:24.910Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:24MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":null,"battery":100,"last_seen":"2023-03-18T13:53:24.929Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:33MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":"toggle","action_group":6,"battery":100,"last_seen":"2023-03-18T13:53:34.022Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:33MQTT publish: topic 'zigbee2mqtt/valena_balkon_1', payload '{"action":"","battery":100,"last_seen":"2023-03-18T13:53:34.022Z","linkquality":255,"voltage":3000}'
Info 2023-03-18 14:53:33MQTT publish: topic 'zigbee2mqtt/valena_balkon_1/action', payload 'toggle'

**Comment by jiquem** [comment]
Upgrade your firmware. We are at firmware 63 now as indicated here https://community.jeedom.com/t/legrand-with-netatmo-firmware-des-equipements/75218

**Comment by mkapuscinski** [comment]
Hey @jiquem thanks!

I've managed to force the update, a now working on 63 [in the Legrand App] previously it was 40
nevertheless, when I'm connecting it back to Zigbee2mqtt [via home assistant], the problem is still the same.

toggle instead of ON, OFF action. And even when switch is paired to Legrand gateway, behaves the same [toggle instead of ON, OFF]

P.S. zigbee2mqtt still shows firmware at 002a

**Comment by jiquem** [comment]
You're right, I don't know exactly when but the "on / off" feature was changed to "toggle" in one of the firmware revision.
Regarding zigbee2mqtt, the version is never updated

**Comment by Loic691** [comment]
Yes Legrand remove the on/off to toggle

**Comment by paulhenric** [comment]
I have exactly the same problem here.
@mkapuscinski : did you manage to solve your problem?

**Comment by mkapuscinski** [comment]
@paulhenric, unfortunately not. 
I did even pair the switch with official Legrand Hub, and had the same result [both buttons had toggle action]

**Comment by alexhk** [comment]
I think something else is happening here. My test unit was reporting `toggle`, now after pairing it again it is using `on/off`. How? I don't know.


I had the Legrand 067773 connected to zigbee2mqtt at home for a few weeks for testing and it reported toggle as pointed out above. 
Yesterday I moved it to my office (identical zigbee2mqtt setup/zigbee coordinator) and had to write my automation using on/off since now out of a sudden it reports on/off instead of toggle.

I did not change the firmware nor make any other changes. In fact an OTA update seems available but what happens if I update?! 

I attempted the  to reset the device a few times go get it paired, and since I don't know how to reset I was holding the reset button, then rapid pressing 10x etc. until it was in pairing.

Not really sure what is going on.

**Comment by alexhk** [comment]
According to a post on the [Legrand developer forums by Stuart John](https://developer.legrand.com/forums/topic/on-off-information-on-switch-067773/page/2/) (post from March 2025 at 05:00) he also managed to get the on/off back. 
I seem to have accidentally triggered this when I randomly pressed the reset button before pairing at the office....

**Comment by Loic691** [comment]
For my side Z2M last version, these 067773 devices have been updated few month ago on 
```
ID du firmware
004d

20171123

Version du firmware
Inconnu
```
If you have information to switch the device in ON/OFF mode rather than TOGGLE I take your information because TOGGLE mode is not for me an acceptable behaviour when managing HA automation

**Comment by alexhk** [comment]
I don't have any info right now apart from what I posted above. 

But what I have is a second unopened 067773, I will try it later today and report back my findings. Seems by pressing the reset or other buttons with confirmed purple/whatever color LED before pairing invokes this special on/off mode, but according to the dev forum they were not able to reliably reproduce it - wish me luck.

My connected 067773 is on firmware `002a 42` and I don't want to mess it up by doing an OTA update.

**Comment by alexhk** [comment]
I couldn't get the new 067773 to use on/off, and to make things worse, I somehow managed to mess up my first one with on/off and had to re-pair: now it's also on `toggle`. Oh man, this really sucks.

**Comment by oliviertassinari** [comment]
A solution that seems to work reliably: https://github.com/Koenkk/zigbee2mqtt/issues/32608#issuecomment-5737458158 with the latest firmware.
