### ISSUE TITLE
IKEA TRADFRI motion sensor E1525/E1745 stops updating states after a few days

### ISSUE THREAD

**Issue by apfffr** [Koenkk/zigbee2mqtt#17082]
### What happened?

I am using an IKEA motion sensor which will stop updating the proper state (occupancy) after a few days.
There is nothing to be found in the log files. It is just like it does not sense motion anymore.

Anyways if I do the map overview function in Zigbee2MQTT or do pairing again, it will work again for a few days. Then the problem repeats.

Question is how I approach this problem as there is nothing to be found in the log files?

### What did you expect to happen?

I expect the device to just work and update the states correctly without needing to repair it every other day

### How to reproduce it (minimal and precise)

I don't really know what does cause this.
Just happens every few days out of nowhere.

Sometimes it works and 10 minutes later it does not work anymore.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20210708

### Adapter

Electrolama zzh

**Comment by HK-Moebius** [comment]
I have exactly the same problem with one of my E1525 motion sensors.
