### ISSUE TITLE
Error after pairing of water valve GiEX QT06

### ISSUE THREAD

**Issue by terierul** [Koenkk/zigbee2mqtt#17088]
### What happened?

I paired a water valve and in interview was recognized like this one: https://www.zigbee2mqtt.io/devices/QT06.html.
The interview was ok (see the first picture). But after the interview an error comes (second picture) and I am seeing the sensor as offline.
The nice part is that also the valve appears as offline in the exposes I can change the state and is working. Basically the valve is functional, but the state is offline.

![image](https://user-images.githubusercontent.com/64191741/226279312-5902ff81-31c2-4d73-82cb-5e24b915bbce.png)
![image](https://user-images.githubusercontent.com/64191741/226279367-baf5f94a-49e9-46ee-9003-3e86eb207e58.png)

See as offline
![image](https://user-images.githubusercontent.com/64191741/226279924-14b1cabe-d9aa-41be-89a1-059a52115606.png)
![image](https://user-images.githubusercontent.com/64191741/226280715-3d007681-5e58-4514-bdad-7e8d6dd4ba56.png)

I can change the status in offline mode
![image](https://user-images.githubusercontent.com/64191741/226280097-0e98d31d-66eb-404f-b39d-b6e0eac9d206.png)

### Zigbee2MQTT version

1.30.2-1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by machv** [comment]
hi,
I just paired mine and I've also got this error. For a while I could control the valve from Z2M, and manually from the valve (with state properly propagated back to Z2M), but after few hours the valve is not responding to zigbee network at all. Could this connectivity issue be related to that error after pairing?

**Comment by lucode** [comment]
I run two GX-02 valves (2024 version) and I can confirm that are connection issues. I needed to place a Zigbee Router quite near to the two valves to have stable connections. I also discovered that a battery level below 70% reduces the connectivity significant. I run it with ZHA.

**Comment by xnextx** [comment]
I have the same problem :(

**Comment by lucode** [comment]
> I have the same problem :(

According to the GiEX Support, either a fixed firmware or the possibility of getting a new one is under way.
