### ISSUE TITLE
TI CC2651P3 custom device read attributes problem

### ISSUE THREAD

**Issue by mjaneczek** [Koenkk/zigbee2mqtt#17094]
### What happened?

Hello everyone, 

I have bought CC2651P3 more specifically LP-CC2651P3. I have downloaded TI CCS, found a nice example, download it, and of course, it didn't work. The problem was missing the model name, it was "almost" fixed by:
https://github.com/Koenkk/zigbee2mqtt/issues/3885#issuecomment-691691953

```cpp
CONST zclAttrRec_t zclSampleLight_Attrs[] = 
{
    // Other existing attributes
    {
      ZCL_CLUSTER_ID_GEN_BASIC,
      { // Attribute record
        ATTRID_BASIC_MODEL_ID,
        ZCL_DATATYPE_CHAR_STR,
        ACCESS_CONTROL_READ,
        (void *)modelId
      }
    },
};
```

But still, it didn't help, next, I found this patch:
https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_3.x.0/firmware.patch
And realized that @Koenkk added "ACCESS_CONTROL_AUTH_READ" to almost every attribute and actually it was modified a month ago: https://github.com/Koenkk/Z-Stack-firmware/commit/517fbd0d68fc3369c9e49511977aa7594e48d505

I was trying to find any information about "ACCESS_CONTROL_AUTH_READ" but no luck. I have no idea why ACCESS_CONTROL_READ alone not working (cannot get the attribute, the model name undefined) but ACCESS_CONTROL_AUTH_READ works fine.

Is this something related to the pretty new CC2651P3? Can you tell me what is ACCESS_CONTROL_AUTH_READ?
When developing the CC2651P3 end device, should I apply any patch from you?

I am sorry if this is messy, I know it's working now and I am still creating issues but please point me in the right direction because I feel like this programmer from the meme. I hope it will be helpful to someone.

Thank you!

### Zigbee2MQTT version

1.30.2-1

### Adapter firmware version

20210708

### Adapter

SLAE.SH CC2652RB Type 4 SLAESHv4

**Comment by mjaneczek** [comment]
@Koenkk sorry to bother you but it looks like you know what could be an issue here based on your commits

**Comment by Koenkk** [comment]
See https://e2e.ti.com/support/wireless-connectivity/zigbee-thread-group/zigbee-and-thread/f/zigbee-thread-forum/1166669/simplelink-cc13x2-26x2-sdk-reading-attributes-with-simplelink-6-30-00-84-fails-with-software_failure
