### ISSUE TITLE
Update process

### ISSUE THREAD

**Issue by mihalski** [Koenkk/zigbee2mqtt#171]
I have found that I currently need to follow this process to be able to update successfully:
```bash
 cd /opt/zigbee2mqtt/
 sudo supervisorctl stop zigbee2mqtt
 fuser -ku /dev/ttyACM0
 git pull
 rm -rf node_modules; npm install
 sudo supervisorctl start zigbee2mqtt
```
Is the need to kill the process something everyone has? If so could this not be added to the service script? If not, what can I do to fix this requirement?

Thanks in advance!

**Comment by Koenkk** [comment]
You are right, I've updated the updating procedure: https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge#6-for-later-update-zigbee2mqtt-to-the-latest-version (note, supervisorctl is not used anymore, replaced by systemctl)
