### ISSUE TITLE
IKEA Tradfri LED1924G9 transition is 1 second longer than set

### ISSUE THREAD

**Issue by Burned695** [Koenkk/zigbee2mqtt#17106]
### What happened?

I've been trying to set my transition time to 0 on my LED1924G9 lights. I've tried this in the "Settings (specific)" menu as well as manually by calling the service. each time has a transition of 1 second when I turn the light on. 

I've tried with different numbers as well and each time it actually takes 1 second longer than set (if I set to 1 it takes 2 seconds, 5 takes 6 seconds). I did try the quick and dirty way of setting it to negative 1 but still took 1 second.

The same issue does not exist with other variants of the Ikea bulbs.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

 0x26660700

### Adapter

ConBee2/RaspBee2

**Comment by charlesomer** [comment]
I believe I have a similar issue, I am also trying to set the transition time to 0 but when I do the LED1924G9 still has a transition.

**Comment by cmprmsd** [comment]
Same issue here! I hoped to use the lamps for in-house notifications. But blinking effects are not possible it seems :|

**Comment by cmprmsd** [comment]
@Koenkk Sorry to mention you here directly. Do you have an idea how to work around this issue? The minimum transition time appears to be 1 second for the color GU10 LEDs and we can't find out if this is a limitation by z2m.

**Comment by haguenau** [comment]
:wave: I was somehow convinced that this is not a Zigbee2MQTT limitation, but rather an Ikea firmware limitation (i.e., older versions of bulb firmware processed the user-requested ), but I can't immediately find a reference for this thought (I think the other very similar [reported issue](https://github.com/Koenkk/zigbee2mqtt/issues/21396) was from the person I am replying to here).

I'm not sure how we can show that Zigbee2MQTT is sending the correct messages and the bulbs are to blame; that would help settle this discussion.

**Comment by Koenkk** [comment]
@cmprmsd not a z2m limitation, z2m supports < 1 sec transitions (as the ZCL spec supports this)

**Comment by cmprmsd** [comment]
Thank you both. I'll try to figure this out with Ikea. 🙈
