### ISSUE TITLE
[New device support]: Tongou TO-Q-SY2-JZT advanced din rail circuit breaker

### ISSUE THREAD

**Issue by henkiejan1** [Koenkk/zigbee2mqtt#17100]
### Link

https://elcb.net/product/zigbee-smart-circuit-breaker-over-current-under-voltage-protection-to-q-sy2-jzt/

### Database entry

{"id":26,"type":"Router","ieeeAddr":"0x385b44fffe93bfae","nwkAddr":59184,"manufId":4098,"manufName":"_TZ3000_cayepv1a","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,1026,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005","65506":31,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_cayepv1a","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":233,"rmsCurrent":0,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,6723],"status":0}},"manuSpecificBosch":{"attributes":{"53251":"AAAA"}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2502}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":1,"53249":0,"53250":2674,"53251":16229,"53252":12594,"53253":3175,"powerOnBehavior":2,"switchType":0}},"genDeviceTempCfg":{"attributes":{}},"genIdentify":{"attributes":{"identifyTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b943ac","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b943ac","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0014b943ac","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-892627439},"lastSeen":1681244924705,"defaultSendRequestWhen":"immediate"}

### Comments

This is a new smart dinrail switch with more options. Not only is it possible to measure the current and electricity. But also you can set some advanced settings what not is recognized by Zigbee2mqtt:
- Turn off current (0-63A)
- Turn off under voltage
- Turn off over voltage
- Turn off by temperature limit
- Countdown timer

It now detected as a ordinary Tuya TS011_F switch with only power metering. Should be nice to support al functions

**Comment by henkiejan1** [comment]
Does anyone have an idea how to support/add the advanced functions of this device? I read something about external converters but looks really difficult...

**Comment by henkiejan1** [comment]
What i see looks like this device very similar to the Tongou one? Maybe it could be related? https://github.com/Koenkk/zigbee2mqtt/issues/16972

**Comment by matlab22** [comment]
I have the same and mine got detected as "_TZ3000_cayepv1a" with limited functionality.

- Power
- Current
- Voltage
- Energy -> not sure if this is working. I tested it with a 40W bulb and the unit is kWh. Time will tell :D

There is also a Child Lock, when I set it the button on the device is not working as expected, but I can not turn it on remotely ether.

Would be nice to enable the other features as well:

- Turn off current (0-63A)
- Turn off under voltage
- Turn off over voltage
- Turn off by temperature limit
- Countdown timer

Does anybody know how to do this?

**Comment by henkiejan1** [comment]
It's just added with the latest release @matlab22 ! Update to the latest Zigbee2mqtt 1.30.4 and delete and add the switch again. I will close this section.

**Comment by eekamouze** [comment]
Ok, forget about my question, sorry. I found the answer there  #17456

**Comment by NorDroN** [comment]
Hi!
What about OTA updates? 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5458276/8ff6a03e-7176-440d-a067-4c782f712281)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5458276/01256528-e16e-404d-b975-32af1c44e6ce)

Z2M 1.35.1

**Comment by fernandeusto** [comment]
same OTA problem here

**Comment by Elkiff71** [comment]
I have the same problem

**Comment by lolvince** [comment]
I have the same problem

**Comment by CH1CC0** [comment]
me too

**Comment by Trebor87** [comment]
I have the same message occurring as well ;(

**Comment by sarzyk** [comment]
Is possible to add it z2m and Tuya in the same time? (Zígbee version)

**Comment by Rookie805** [comment]
Advanced functions are still not working, but present in device page. Just getting errors, when trying to set.

What did you expect to happen?

I expect that mentioned values are set in device.

How to reproduce it (minimal and precise)

Just try to set values in device page.

Zigbee2MQTT version

2.6.2
Adapter firmware version

EmberZNet 8.0.2 [GA]
Adapter

Sonoff ZBDongle-E
Setup

haos
Debug log

[15.11.2025, 19:50:59] z2m: Publish 'set' 'temperature_threshold' to 'Pump' failed: 'Error: Expected string or number, got: undefined'

[15.11.2025, 19:51:00] z2m: Publish 'set' 'temperature_breaker' to 'Pump' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

[15.11.2025, 19:51:02] z2m: Publish 'set' 'power_threshold' to 'Pump' failed: 'Error: Expected string or number, got: undefined'

[15.11.2025, 19:51:02] z2m: Publish 'set' 'power_breaker' to 'Pump' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

[15.11.2025, 19:51:04] z2m: Publish 'set' 'over_current_threshold' to 'Pump' failed: 'Error: Expected string or number, got: undefined'

[15.11.2025, 19:51:06] z2m: Publish 'set' 'over_current_breaker' to 'Pump' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

[15.11.2025, 19:51:08] z2m: Publish 'set' 'over_voltage_threshold' to 'Pump' failed: 'Error: Expected string or number, got: undefined'

[15.11.2025, 19:51:09] z2m: Publish 'set' 'over_voltage_breaker' to 'Pump' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

[15.11.2025, 19:51:12] z2m: Publish 'set' 'under_voltage_threshold' to 'Pump' failed: 'Error: Expected string or number, got: undefined'

[15.11.2025, 19:51:13] z2m: Publish 'set' 'under_voltage_breaker' to 'Pump' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

**Comment by JordiPF** [comment]
Same error for me. any solution?

**Comment by ShirkovPavel** [comment]
I've got the same problem. Don't work any types of threshold. But in the earlier version of zigbee2mqtt everything worked fine. I can activate/disactivate over voltage, over current and any over kind of protection and set threshold in values in Home assistant. In latest version zigbee2mqtt managing threshold don't work.
