### ISSUE TITLE
_TZ3210_pagajpog not sending brightness data

### ISSUE THREAD

**Issue by soulcola** [Koenkk/zigbee2mqtt#17122]
### What happened?

_TZ3210_pagajpog not sending brightness data if  I change the brightness with a physical switch. Dimming works, but slider value is not updated. Brightness slider in Zigbee2MQTT frontend works fine, on/off works too. 

### How to reproduce it (minimal and precise)

Change brightness with a physical switch (long press)

### Zigbee2MQTT version

 1.30.2

### Adapter firmware version

20220219

### Adapter

ZigStar lan coordinator

### Debug log

`Info 2023-03-23 13:12:13MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l1', payload '{"brightness":127,"max_brightness":220,"min_brightness":60,"power_on_behavior":"previous","state":"ON"}'
Info 2023-03-23 13:12:13MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l2', payload '{"brightness":159,"state":"ON"}'
Debug 2023-03-23 13:12:14Received Zigbee message from 'Dimmer кухня 1', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":545}' from endpoint 1 with groupID 0
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1', payload '{"brightness":138,"brightness_l1":127,"brightness_l2":159,"last_seen":"2023-03-23T10:12:14.069Z","linkquality":36,"max_brightness":255,"max_brightness_l1":220,"min_brightness":4,"min_brightness_l1":60,"power_on_behavior":"previous","power_on_behavior_l1":"previous","state_l1":"ON","state_l2":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l1', payload '{"brightness":127,"max_brightness":220,"min_brightness":60,"power_on_behavior":"previous","state":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l2', payload '{"brightness":159,"state":"ON"}'
Debug 2023-03-23 13:12:14Received Zigbee message from 'Dimmer кухня 1', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":608}' from endpoint 1 with groupID 0
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1', payload '{"brightness":154,"brightness_l1":127,"brightness_l2":159,"last_seen":"2023-03-23T10:12:14.484Z","linkquality":40,"max_brightness":255,"max_brightness_l1":220,"min_brightness":4,"min_brightness_l1":60,"power_on_behavior":"previous","power_on_behavior_l1":"previous","state_l1":"ON","state_l2":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l1', payload '{"brightness":127,"max_brightness":220,"min_brightness":60,"power_on_behavior":"previous","state":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l2', payload '{"brightness":159,"state":"ON"}'
Debug 2023-03-23 13:12:14Received Zigbee message from 'Dimmer кухня 1', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":671}' from endpoint 1 with groupID 0
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1', payload '{"brightness":170,"brightness_l1":127,"brightness_l2":159,"last_seen":"2023-03-23T10:12:14.887Z","linkquality":36,"max_brightness":255,"max_brightness_l1":220,"min_brightness":4,"min_brightness_l1":60,"power_on_behavior":"previous","power_on_behavior_l1":"previous","state_l1":"ON","state_l2":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l1', payload '{"brightness":127,"max_brightness":220,"min_brightness":60,"power_on_behavior":"previous","state":"ON"}'
Info 2023-03-23 13:12:14MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l2', payload '{"brightness":159,"state":"ON"}'
Debug 2023-03-23 13:12:15Received Zigbee message from 'Dimmer кухня 1', type 'attributeReport', cluster 'genLevelCtrl', data '{"61440":624}' from endpoint 2 with groupID 0
Info 2023-03-23 13:12:15MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1', payload '{"brightness":158,"brightness_l1":127,"brightness_l2":159,"last_seen":"2023-03-23T10:12:15.345Z","linkquality":29,"max_brightness":255,"max_brightness_l1":220,"min_brightness":4,"min_brightness_l1":60,"power_on_behavior":"previous","power_on_behavior_l1":"previous","state_l1":"ON","state_l2":"ON"}'
Info 2023-03-23 13:12:15MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l1', payload '{"brightness":127,"max_brightness":220,"min_brightness":60,"power_on_behavior":"previous","state":"ON"}'
Info 2023-03-23 13:12:15MQTT publish: topic 'zigbee2mqtt/Dimmer кухня 1/l2', payload '{"brightness":159,"state":"ON"}'`

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11049651/log.txt)

**Comment by soulcola** [comment]
1.30.3 still not fixed

**Comment by Tribalwarrior** [comment]
any solution find?
