### ISSUE TITLE
Schneider Electric CCT5011-0001/CCT5011-0002/MEG5011-0001 Micro module switch

### ISSUE THREAD

**Issue by Albastraoz** [Koenkk/zigbee2mqtt#17143]
### What happened?

![image](https://user-images.githubusercontent.com/55411469/227730805-fe890a85-3adf-4904-8a11-f14591086f0c.png)

This device keeps complaining about the power_on_behavior. I also have a smart plug from the same brand and that one has this attribute. I tried to set it in zigbee2mqtt but it gives the following error:

![image](https://user-images.githubusercontent.com/55411469/227731177-660f6bb7-4820-47d8-9855-b40caf9789f9.png)

Either something is wrong with my device/setup or this attribute does not exist. :) 

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
Doesn't seem to be supported, disabled it!
