### ISSUE TITLE
 question about error messages

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#1714]
hello:
I have a question when you synchronize a new device, I receive in many cases the message: AM Device with model ID 'undefined' is not supported.
Then the device ends up synchronizing and it works, I do not know if it is like that or because something is wrong.
Today I tested the IKEA E1524 device and received the message many times
('Error: AF data request fails, status code: 240. MAC transaction expired.') (Attempt # 1)
This can be ignored if the device is working properly.

I do not know if receiving these messages is normal.

Greetings and thanks

**Comment by Koenkk** [comment]
That's normal, zigbee2mqtt still needs to retrieve the `modelId` at that point.

Assuming this has been answered.
