### ISSUE TITLE
[Dangerous bug] Danalock V3 - Keeps sending locked/unlocked command every 2 seconds (Edge commit #653334b)

### ISSUE THREAD

**Issue by ASNNetworks** [Koenkk/zigbee2mqtt#17160]
### What happened?
**EDIT: This issue is a lot worse than I thought, since it also sends the unlocked state non-stop if the lock is unlocked. Which means your lock keeps unlocking every 2 seconds, impossible for the door to close. I tried deleting and re-pairing, but doesn't solve anything**

I updated to the latest Edge release 1.30.2-dev (commit #653334b) because I saw it supports the new Symfonisk gen2 remotes (they work fantastic btw). But I noticed that this release has a major bug with the Danalock V3. When I lock my door, it keeps sending the locked command every 2 seconds. Also the state of the device skeeps going from locked to unlocked, while it infact still is locked. But it's actively trying to lock, while in locked mode.

My battery went down like 20% in a single night because appearantly it kept sending the locked command. I tried troubleshooting and noticed when I locked the lock, it kept sending the lock command, while it was already locked. The lock itself also actually tries to lock it. The knob turns and then makes a rejection sound and goes back, since it's already locked.

Since it keeps sending the locked command, it's impossible to even unlock anymore, and your basically locked in (or out). I hope we can fix this issue asap so it never reaches the final release, I can test ofcourse.

### What did you expect to happen?

I expected it to work like on the normal release. For now I stopped the edge add-on and started the normal one, which made all issues go away. Sadly my IKEA Symfonisk remotes now don't work anymore, since those aren't supported in the normal release.

### How to reproduce it (minimal and precise)

Just lock the lock and it will keep sending the lock command. This also happens without locking it yourself. I stopped z2m, and then the locking stopped. I then started z2m again and it kept trying to lock the door, while I never sent a command. 

### Zigbee2MQTT version

1.30.2-dev (commit #653334b)

### Adapter firmware version

20221226

### Adapter

zigstar4

### Debug log

Info 2023-03-27 17:23:17MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:17+02:00","linkquality":76,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:19MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:19+02:00","linkquality":80,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:21MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:21+02:00","linkquality":76,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:23MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:23+02:00","linkquality":80,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:26MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:26+02:00","linkquality":76,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:28MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:28+02:00","linkquality":76,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:31MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:31+02:00","linkquality":80,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'
Info 2023-03-27 17:23:33MQTT publish: topic 'zigbee2mqtt/Hal Slot Voordeur', payload '{"action":null,"action_source_name":null,"action_user":null,"battery":62,"last_seen":"2023-03-27T17:23:33+02:00","linkquality":76,"lock_state":"not_fully_locked","pin_code":null,"state":"UNLOCK","update":{"installed_version":285474816,"latest_version":285474816,"state":"idle"},"update_available":false,"users":{"0":{"status":"available"},"1":{"status":"available"},"2":{"status":"available"},"3":{"status":"available"}}}'

**Comment by sjorge** [comment]
I see you're on the `dev` branch, does this also happen with the `master` branch?
If it only happens on `dev` you might be hitting https://github.com/Koenkk/zigbee-herdsman/pull/676#issuecomment-1483828764

**Comment by ASNNetworks** [comment]
> I see you're on the `dev` branch, does this also happen with the `master` branch? If it only happens on `dev` you might be hitting [Koenkk/zigbee-herdsman#676 (comment)](https://github.com/Koenkk/zigbee-herdsman/pull/676#issuecomment-1483828764)

Hi, no the current latest stable build has no issues. I tried the dev `build` because it added support for IKEA Symfonisk gen2. Then I noticed this bug with the Danalock v3

**Comment by sjorge** [comment]
@Koenkk I think it's the same issue I'm seeing with the reconfigure, where z2m ends up trying that top queued message indefinitely and never finishing the rest of the queue.

**Comment by Koenkk** [comment]
I've reverted the PR, please check if the issue is fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
