### ISSUE TITLE
Clamp Meter _TZE204_cjbofhxw - energy IS not reporting as Sum

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17176]
### What happened?

Clamp Meter _TZE204_cjbofhxw - energy IS not reporting as Sum. Instead its just reporting when there is energy and not continuously adding it up like other entities for other energy monitoring devices
![image](https://user-images.githubusercontent.com/58960644/228527351-62de46c4-a5bd-4355-9cea-821fc1127171.png)
![image](https://user-images.githubusercontent.com/58960644/228527631-4bdb1531-982d-445c-8ddb-678cdd81b7e6.png)

### What did you expect to happen?

I expected the energy to be a continuous sum increase

### Zigbee2MQTT version

 1.30.2 commit: unknown

### Adapter firmware version

20221226

### Adapter

Sonoff Coordinator P

**Comment by cloudbr34k84** [comment]
Keeping open

**Comment by Alexofhiswalnut** [comment]
Open

**Comment by seb49** [comment]
How does "sensor" work ? I can't find documentation

**Comment by Diegocampy** [comment]
Same problem with only one of my two energy metter.

**Comment by Alexofhiswalnut** [comment]
> Same problem with only one of my two energy metter.

The new version is probably better based on the comments

https://fr.aliexpress.com/item/1005005881727281.html

**Comment by unwiredtech** [comment]
I have this device and still the Energy is not adding up.
