### ISSUE TITLE
TS011F_plug_1 energy_precision not taken into account

### ISSUE THREAD

**Issue by sywesk** [Koenkk/zigbee2mqtt#17178]
### What happened?

After setting the `energy_precision` setting, I expected the number of decimals to match the setting, but it never happened. It seems to work only for the `current_precision` setting.

For the record, I also have a wall plug, this time a wall socket from the moes brand, also showing up as "TS011F_plug_1" that exhibit the same behavior.

#### Quick debugging

I've tried using the dev console to read `1 / seMetering / currentSummDelivered`, and got the following output: `Read result of 'seMetering': {"currentSummDelivered":[0,43]}`. Looking at the code it seems like the 0 number is the upper 32 bits, and the 43 number the lower 32 bits. So it seems like the device is returning a value representing "tens" of Wh.

#### Thoughts and questions

After looking for something related to this precision issue on multiple search engines and through the GH issues, i don't seem to find anything explaining what's happening, so I have a few questions:

- How does the "precision" settings work ? 
- Is it only a z2m-local / visual feature, and we don't actually ask the device to change its precision?

Thank you & all the contributors for the wonderful projet.

 

### How to reproduce it (minimal and precise)

1. Pair an Aubess TS011F_plug_1.
2. Go the device's page.
3. Go to the Settings (Specific) tab.
4. Set the energy precision to 3
5. The value's precision never changes

### Zigbee2MQTT version

1.30.2-1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

Sonoff ZDongle-E

### Debug log

I don't think it's a z2m bug, multiple devices exhibit the same problem so I think it more of a tuya platform/firmware issue. But i'll edit and post if required.

**Comment by Koenkk** [comment]
> Is it only a z2m-local / visual feature, and we don't actually ask the device to change its precision?

It's a rounding done by Zigbee2MQTT ("visual feature"), Zigbee doesn't support such thing.

**Comment by sywesk** [comment]
Thanks for you answers guys, closing the issue 🙏
