### ISSUE TITLE
Switch Suddently Started Broadcasting Commands to whole network

### ISSUE THREAD

**Issue by vaderag** [Koenkk/zigbee2mqtt#17183]
### What happened?

I have an [Osram Switch 4x EU-LIGHTIFY](https://www.zigbee2mqtt.io/devices/4058075816459.html#osram-4058075816459) and it was working just fine, and all of a sudden (unsure of the trigger) it has started broadcasting an off command to my entire zigbee network

Seems there is a related issue https://github.com/Koenkk/zigbee2mqtt/issues/962 (for a different switch)

### What did you expect to happen?

Not to broadcast to the entire network

Assumption this is a binding issue but honestly I'm not experienced enough to know what these options mean. Am posting the screenshot of the bind pages in case someone spots something obviously wrong (to be clear, I haven't touched anything in this page!)

![image](https://user-images.githubusercontent.com/17175988/228796743-c08c6dc1-d409-40b7-bcb6-6071a94592e4.png)

### How to reproduce it (minimal and precise)

Press a button. Broadcast occurs
Broadcast does not seem to be picked up by home assistant as device state changes are not updated

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 

### Debug log

No relevant logs

**Comment by vaderag** [comment]
Not stale

**Comment by vaderag** [comment]
Still a thing

**Comment by vaderag** [comment]
Still a thing

**Comment by kkossev** [comment]
> Still a thing

Have you tried to pair the switch again?

This happens if the switch is reset and then not configured properly during the Zigbee pairing.

**Comment by TEF2one** [comment]
Well I have the same issue, I have 4 of the [OSRAM Switch Mini ](https://www.zigbee2mqtt.io/devices/AC0251100NJ_AC0251600NJ_AC0251700NJ.html) and half are now broadcasting to all with the other are fine and I cannot find any difference in their configurations.

**Comment by TEF2one** [comment]
Ok, I got one of the remote to work without broadcast by re-pairing to a specific router that is not the coordinator.
