### ISSUE TITLE
Danfoss Ally valve no converter available for pi_heating _demand 

### ISSUE THREAD

**Issue by Riky-AH** [Koenkk/zigbee2mqtt#17187]
### What happened?

When i tried to set the pi_heating _demand on a Danfoss Ally 014G2461 Zigbee2mqtt reply with "Zigbee2MQTT:error 2023-03-30 15:47:10: No converter available for 'pi_heating_demand' (50)" 

### How to reproduce it (minimal and precise)

-Connect the Danfoss Ally valve to Zigbee2mqtt
-Publish to the valve zigbee2mqtt/[valve friendly name]/set {"pi_heating_demand": 50}

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

{"meta":{"maintrel":"3 ","majorrel":"6","minorrel":"10","product":8,"revision":"6.10.3.0 build 297"},"type":"EZSP v8"}

### Adapter

Sonoff Dongle Plus 3.0 ZBDongle-E

**Comment by sjorge** [comment]
IIRC from my brief time with this device, this is expected as it does not support setting pi_heating_demand.

**Comment by Riky-AH** [comment]
But the Zigbee2MQTT website (https://www.zigbee2mqtt.io/devices/014G2461.html Climate section) say that the pi_heating_demand is supported with both /get and /set, It's possible that it will work with a custom converter or this parameter was put on the website by error and there is no way to use it?

**Comment by sjorge** [comment]
@Koenkk could that code generating it be wrong? https://www.zigbee2mqtt.io/devices/H1.html also lists it under the climate section as settable and it 100% for sure isn't on that one.

@Riky-AH you could try via de dev console
<img width="1367" alt="Screenshot 2023-03-31 at 10 14 33" src="https://user-images.githubusercontent.com/379665/229064453-59fb1be0-d5f1-4f70-9e84-c02ea669845a.png">

But I think it might be an error in the docs that get generated.

**Comment by Riky-AH** [comment]
I have tried with the dev console, i can read it but if i try to write i get an error who say that this parameter is read-only

![danfossTV](https://user-images.githubusercontent.com/125387976/229082144-774869fa-ec79-4f31-9a9d-017db146c32b.png)

And also in the Values section i can see the pi_heating_demand value but there is nothing to change it.

**Comment by sjorge** [comment]
So the READ_ONLY is the device saying you can only read the attribute not write to it. So It's as I remember where the devices does not support writing to it. I'm pretty sure the code that generates the device page has a bug somewhere then, as the H1 also is listed wrong on there.

**Comment by rodolpheAV** [comment]
Hello

I know this is a very old fix but it seems to me that the fix was not correct. instead of changing the doc to say that the property are read only, it now says that the property is write only which is wrong : 

![Image](https://github.com/user-attachments/assets/c378a3fa-7102-4845-bd01-c41ebcd60f82)

So this devices doc is wrong and I think many others too.

**Comment by vilaemail** [comment]
Docs are still incorrect.
