### ISSUE TITLE
Aqara Pet Feeder "apply" button only becomes clickable if entire schedule is changed

### ISSUE THREAD

**Issue by beeinaboats** [Koenkk/zigbee2mqtt#17192]
### What happened?

Whenever you want to update the weekday, hour, second, or feeding size of the schedule part of exposes, you need to update each category in order for the apply button to become clickable

### What did you expect to happen?

You should be able to just update one of the categories, ie weekday, hour, second, or feeding size, instead of needing to update them all for the apply button to be clickable

### How to reproduce it (minimal and precise)

only update one of the following, weekday, hour, second, or feeding size, and the apply button won't be clickable

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20221226

### Adapter

Sonoff ZBDongle-P

**Comment by Rustymage** [comment]
I have this issue and now I can't automatically feed my cat.
