### ISSUE TITLE
Iluminize 511.012 does not report back state

### ISSUE THREAD

**Issue by brushmate** [Koenkk/zigbee2mqtt#17196]
### What happened?

The Iluminize 511.012 ZigBee controller supports an external switch to control the state. Unfortunately these state changes do not show up in Zigbee2MQTT.

### What did you expect to happen?

I would have expected to see the changes in Zigbee2MQTT / Home Assistant.

### How to reproduce it (minimal and precise)

Setup the LED controller and attach an external switch. Press the switch and see that nothing is reported back to Zigbee2MQTT.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20210708

### Adapter

cod.m ZigBee CC2652P2 Raspberry Pi Module

### Additional info

I found  #2502 where someone reported a similar issue. @Koenkk [asked to add an external converter](https://github.com/Koenkk/zigbee2mqtt/issues/2502#issuecomment-949834121) for further debugging. I tried to adapt that, but then Zigbee2MQTT fails to start with the following stacktrace:

```
/app/node_modules/zigbee-herdsman-converters/index.js:65
            assert.fail(`'${definition.model}' has configure in extend and device, this is not allowed`);
                   ^
AssertionError [ERR_ASSERTION]: '511.012' has configure in extend and device, this is not allowed
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:65:20)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
```

**Comment by brushmate** [comment]
I just got feedback from Iluminize. According to them this is known behavior and smart home hubs should actively poll the state of the controller. Is there such a functionality in Zigbee2MQTT and can it be enabled for this controller?

**Comment by brushmate** [comment]
I found the corresponding setting in the Zigbee2MQTT frontend. You can find it under _Devices_ > _Your device_ > _Reporting_. I have configured two reportings for this controller:

```
Endpoint         : 1
Cluster          : LevelCtrl
Attribute        : currentLevel
Min rep interval : 1
max rep interval : 5
Min rep change   : 0
```
```
Endpoint         : 1
Cluster          : OnOff
Attribute        : onOff
Min rep interval : 1
max rep interval : 5
Min rep change   : 0
```

I think I also found the related documentation of this feature: https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-device-configure-reporting

Since this is not a Zigbee2MQTT issue, I am closing it. I will try to convince the vendor to implement 'native reporting'.

**Comment by gregoriusus** [comment]
@brushmate Did they give you any feedback? I have sam issue and thinking to buy another controller.

**Comment by brushmate** [comment]
No, I don't think so. But to be fair, I don't remember if I contacted them again. At least I can't find anything in my email history.

**Comment by peelos** [comment]
> I found the corresponding setting in the Zigbee2MQTT frontend. You can find it under _Devices_ > _Your device_ > _Reporting_. I have configured two reportings for this controller:
> 
> ```
> Endpoint         : 1
> Cluster          : LevelCtrl
> Attribute        : currentLevel
> Min rep interval : 1
> max rep interval : 5
> Min rep change   : 0
> ```
> 
> ```
> Endpoint         : 1
> Cluster          : OnOff
> Attribute        : onOff
> Min rep interval : 1
> max rep interval : 5
> Min rep change   : 0
> ```
> 
> I think I also found the related documentation of this feature: https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-device-configure-reporting
> 
> Since this is not a Zigbee2MQTT issue, I am closing it. I will try to convince the vendor to implement 'native reporting'.

Thanks for this, I used these settings and whilst they worked fine to report status, I have experienced instability with Z2M since, I have since changed them to report immediately without delay when switched, but only update status every hour rather than every 5s: 

```
Endpoint         : 1
Cluster          : LevelCtrl
Attribute        : currentLevel
Min rep interval : 0
max rep interval : 3600
Min rep change   : 10

Endpoint         : 1
Cluster          : OnOff
Attribute        : onOff
Min rep interval : 0
max rep interval : 3600
Min rep change   : 1
```

Will report back if any other issues

**Comment by gregoriusus** [comment]
If I understand correctly, there is still a hope that state is reported back?

**Comment by peelos** [comment]
> If I understand correctly, there is still a hope that state is reported back?

I did speak to the CEO of illuminize and referenced this thread in an email - he said he would speak to the developer, but that Z2M limits the amount of messages they can send by default, although admitted he is not a developer and was not aware of the details.

If anyone can specify exactly what Iluminize need to do to enable native reporting, I can forward him the details.
