### ISSUE TITLE
reflash CC2531 after not work, now pairing problem with xiaomi

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#172]
i have reflash the usb stick.. and now i cant repairing all my xiaomi devices.. 
i used the new flash file https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/bin
its 10 days old....

**Comment by ciotlosm** [comment]
@arteck have you reset the devices? What errors do you get?

**Comment by arteck** [comment]
My devices were not available.. the cc2531 did not respond...

**Comment by ciotlosm** [comment]
Try pressing the reset button on the CC2531

**Comment by arteck** [comment]
which one is it ??? 
left or right from usb port

**Comment by ciotlosm** [comment]
Maybe try complete host reboot as well (let it without power for a minute).

**Comment by arteck** [comment]
hue and osram works..the problem is only xiaomi..

**Comment by ciotlosm** [comment]
Can you post your version on startup of zigbee2mqtt?

**Comment by arteck** [comment]
2018-7-1 19:05:02 INFO Starting zigbee2mqtt version 0.0.0 (commit #7cec5f2)
2018-7-1 19:05:02 INFO Starting zigbee-shepherd
2018-7-1 19:05:03 INFO zigbee-shepherd started

**Comment by ciotlosm** [comment]
Your zigbee2mqtt is latest version. Probably something changed in zcl dependency. @Koenkk maybe latest release broke the xiaomi patch.

**Comment by Koenkk** [comment]
Could you try removing the battery from the Xiaomi devices for a few seconds, and then repeat the pairing procedure?

**Comment by arteck** [comment]
I check that .. but i think the flash file ist buggy
i found other files here https://github.com/kirovilya/files 
any ideas ??

**Comment by Koenkk** [comment]
@arteck can you try the CC2531ZNP-Pro-Secure_LinkKeyJoin.hex from here: https://github.com/mtornblad/zstack-1.2.2a.44539/tree/master/CC2531

**Comment by arteck** [comment]
I'll contact you

**Comment by arteck** [comment]
CC2531ZNP-Pro-Secure_LinkKeyJoin.hex work... 
I look for how long .....
