### ISSUE TITLE
[Feature request]: Reset limit support for ZNCLDJ14LM (Xiaomi Aqara Curtain Motor C2)

### ISSUE THREAD

**Issue by gofort** [Koenkk/zigbee2mqtt#17206]
### Is your feature request related to a problem? Please describe

[Xiaomi ZNCLDJ14LM](https://www.zigbee2mqtt.io/devices/ZNCLDJ14LM.html) is a new version of [Xiaomi ZNCLDJ11LM](https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html).

At the same time, the old version has `reset_limits` option, but I can't find it in the new version.

![Only reverse direction is available for ZNCLDJ14LM](https://user-images.githubusercontent.com/11654185/229275271-03d78017-3864-487a-93b2-591acb09c45b.png)

![reverse_direction, hand_open, reset_limits is available for the older version ZNCLDJ14LM](https://user-images.githubusercontent.com/11654185/229275356-d203ed19-3aad-46d5-83d8-8f75cb4f5888.png)

Please add the option to `reset_limits` for ZNCLDJ14LM.

### Describe the solution you'd like

I'd like to see the ability to reset curtain limits in UI.

### Describe alternatives you've considered

I tried to reset the limits using the button on the device itself, but it reset only pairing, not the limits of curtains.
I have checked the whole internet trying to understand if the button on the device can reset limits, but it looks like it can't and it is available only using the Aqara hub.

### Additional context

Added screenshot to the feature description.

**Comment by mwargocki** [comment]
This motor starts to be popular so it would be great if there would be full support of it.

**Comment by deiger** [comment]
Are `hand_open` and `reset_limits` supported by the motor?
