### ISSUE TITLE
Add device_class for IKEA VINDSTYRKA (E2112).

### ISSUE THREAD

**Issue by AbeltjeNL** [Koenkk/zigbee2mqtt#17208]
### Is your feature request related to a problem? Please describe

No problem. Since the VOC sensor is added there is no device class linked to it.

### Describe the solution you'd like

Add device class: volatile_organic_compounds. 
For example to expose the sensor information to HomeKit. 
I’ve added this in my customize.yaml and it works like expected. 

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by Koenkk** [comment]
From https://www.home-assistant.io/integrations/sensor/

> volatile_organic_compounds: Concentration of volatile organic compounds in µg/m³

The unit has to be µg/m³, which is not the case for this sensor so therefore the device class cannot be set.
