### ISSUE TITLE
No battery status for Legrand 067774 double wireless switch

### ISSUE THREAD

**Issue by Loic691** [Koenkk/zigbee2mqtt#17225]
### What happened?

No battery status is get from the device.
Note I had the problem too with the 067646 roller wireless switch device
![image](https://user-images.githubusercontent.com/60837526/229442407-a96ae7ef-6854-4362-addf-a6628ed78238.png)

### What did you expect to happen?

I saw in other post that the isssue have been solved.
I'm not sur this is really done...

### How to reproduce it (minimal and precise)

Reset the device and then pair it again on Z2M.
The device have been updated with last Legrand firmware 36
I had the same problem with version 31 of the firmware

So another problem is my firmware version is not up to date in the Z2M GUI.
How and when  the firmware version is refreshed ? It appears it's not on interview...

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

7.1.4.0 build 389

### Adapter

Sonoff Dongle E with EFR32 chip

**Comment by cobch** [comment]
Hi, did you manage to fix your issue. All my Legrand wireless switches have same problem and do not report battery level. Please help (-:

**Comment by cobch** [comment]
@Loic691 Did you updated the code of the device?

**Comment by Loic691** [comment]
There is  no update for wireless double switch.
And the update doesnt work with 1.30.2 for the wireless home away button.
The update is been detected with ota in z2m but no update start...

**Comment by mycanaletto** [comment]
Same problem on 067646

**Comment by Loic691** [comment]
Hi no news ?

**Comment by mycanaletto** [comment]
The only solution (I've done it) is to buy a Legrand gateway, link the devices to it, and wait for the update to take place (it works, but you can't force it).

**Comment by cobch** [comment]
> The only solution (I've done it) is to buy a Legrand gateway, link the devices to it, and wait for the update to take place (it works, but you can't force it).
> 
> 
> 
> Then the devices that were blocked on channel 11 take the other channels.

I have done that as well and I am to version 30. But still when the switch join z2m it is not reporting battery level. Do you have the same issue?

**Comment by mycanaletto** [comment]
Yes, and it's a Z2M problem, because since then I've tested it on the deconz gateway and the battery goes back up just fine... (if you use the control unit, because from time to time it loses it, but it comes back when you use it)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/45459269/8c91b6fd-29eb-4274-8c6a-6683a6797a79)

**Comment by cobch** [comment]
Exactly, I come from Deconz and it has always been working fine before. Someone can maybe do a PR to fix that. Any idea how to do that?

**Comment by Loic691** [comment]
Hi @mycanaletto 
I have several problems with my 067774 double wireless switch and home away.
I try to update z2m to last version but this is same.
My legrand device are on last firmware.
I have the dummy group and the devis are long to send zigbee. It's randomly..
Some times the switch event arrives instantanously in HA maybe after 30 secondes....
Do you have same ?
