### ISSUE TITLE
LQI of devices in different menus is different

### ISSUE THREAD

**Issue by garry0garry** [Koenkk/zigbee2mqtt#17223]
### What happened?

LQI. Values in two different menu items. They were taken 30 seconds apart:
![изображение](https://user-images.githubusercontent.com/95581374/229371505-1c9ab2fe-d14b-46f3-810c-845327c4d67b.png)
![изображение](https://user-images.githubusercontent.com/95581374/229371519-9f13360d-c035-45a0-b72c-a1e244df7453.png)

20/82, 57, 255 vs 84, 88, 88

Repeatability 100%. The values never match.

### What did you expect to happen?

Why is the LQI of devices in different menus different?
What values are correct?

### How to reproduce it (minimal and precise)

Use the following menus:
http://ip:port/#/device
http://ip:port/#/map

### Zigbee2MQTT version

1.30.3 commit: 24c6b2e

### Adapter firmware version

7.2.0.0 build 108

### Adapter

Sonoff ZBDongle-E (Dongle Plus V2) / EZSP v9

**Comment by elkarto** [comment]
Same problem here.   

1.30.2
Slaesh' CC2652RB
