### ISSUE TITLE
[New device support]: Namron 4512739 Tunable White Dimmer 400w

### ISSUE THREAD

**Issue by Pythm** [Koenkk/zigbee2mqtt#17254]
### Link

https://www.namron.com/products/namron-zigbee-tunable-white-dimmer-400w/

### Database entry

{"id":15,"type":"Router","ieeeAddr":"0x9035eafffe628880","nwkAddr":23452,"manufId":4644,"manufName":"NAMRON AS","powerSource":"Mai>

### Comments

Im kind of stuck with my first unsupported device but not sure if it is code or lack of compatibility between my Zigbee dimmer and the Led light. I have the Namron Zigbee Tunable White Dimmer connected to a SG Junistar soft TW leddim. https://www.sg-as.com/en-gb/products/junistar-soft-tw

The light turns on/off and dims but the led light does not respond to color temperature changes.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['4512739'],
    model: '4512739',
    vendor: 'Namron',
    description: 'Zigbee Tunable White Dimmer 400W',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [160, 450]}),
    
};

module.exports = definition;
```
Thanks!

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":160,"colorTempPhysicalMax":450}

**Comment by andrei-lazarov** [comment]
Adding here:
- https://github.com/Koenkk/zigbee-herdsman-converters/pull/11256
