### ISSUE TITLE
state is inverted on TS0601_cover_1 (_TZE200_cf1sl3tj)

### ISSUE THREAD

**Issue by magarage** [Koenkk/zigbee2mqtt#17251]
### What happened?

Hi.
I installed tuya zemismart curtain robot (TS0601_cover_1 _TZE200_cf1sl3tj) model for my left curtain.
For left setup, i checked `invert_cover` as `true` on settings to set `position = 0` is `open` and vice versa (left side is open(position 0), right side is closed (position 100).

![image](https://user-images.githubusercontent.com/6888842/230038692-81f8b6d9-48df-4ae3-84ba-8cf1d6101543.png)

`position` is changed as expected, but `state` is not inverted.
(i.e, `state = close` when `position = 0` , `state = open` when `position = 100`)

When i click `open` or `close` state button, curtain and position value are moved correct direction.
but, and then, state is changed inversly.
(ex: click `close` then curtain position move to right end (100) and then state changed `open`)

#### on position 0 (state have to be `open`)
![image](https://user-images.githubusercontent.com/6888842/230035526-94de1c4c-ac34-4074-9208-c93651046635.png)

#### on position 100 (state have to be 'closed')
![image](https://user-images.githubusercontent.com/6888842/230036002-49e42a03-7453-488d-b9b5-1094c742d03b.png)

### What did you expect to happen?

i expected 
when `position = 0 (left end)` then `state = open` 
when `position = 100(right end)` is `state = close` for left curtain. 
if i checked `invert_cover` settings.

### How to reproduce it (minimal and precise)

1. Added Tuya Curtain robot.
2. Changes `invert_cover = true` on settings page.
3. Click `open/close` button or change position value  `0(left)` or `100(right)`.
4. When `position = 0` then `state = close` and vice versa (state is opposite). 

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11157208/log.txt)

**Comment by mrmaximas** [comment]
@Koenkk i have same issue. 
If I send a command to close using the RF remote (for example), the motor configured as “Reverse direction - Back” switches to the "Open" state and 100% after the command is executed, while the motor configured as “Reverse direction - Forward” switches to the “Closed” state and 0%.  When I send a command from the RF remote to "Open" for 30% or 70%, both motors display the correct position (30% or 70%) and show that the is "Open" state. 
Both of my motors the “Invert cover” setting is set to “false”
How to fix it?
Please pay attention. 
Thanks!
