### ISSUE TITLE
Something wrong with multiple copies of devices in database.db

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#1725]
This situation is quite usual, we can have multiple copies of the same device in database.db.
I am unsure it is normal. I have it almost for all my devices.

And another thing I found, which might be related to this.
If you pair device multiple times (I have this during development of device, and this one of the reasons of multiplication of number of copies in DB, but not only one, it looks like), then at some point coordinator start to ignore all packets from the devices (it allow it to pair, but still ignores valid packets) and only one option is to remove device and repair one more time.

**Comment by clockbrain** [comment]
This should probably be an FAQ.

Database.db is logically one row per device but ... zigbee2mqtt indirectly uses NeDB for storage.

From the NeDB page regarding persistence:

> Under the hood, NeDB's persistence uses an append-only format, meaning that all updates and deletes actually result in lines added at the end of the datafile, for performance reasons. The database is automatically compacted (i.e. put back in the one-line-per-document format) every time you load each database within your application.


So you will find one row per device before the index line
```
{"$$indexCreated":{"fieldName":"id","unique":true,"sparse":false}}
```
and potentially multiple rows per device after that line.

I'd avoid messing with the database unless you have to purge a device that won't go away in which case you would delete all lines with the relevant id.

Also see #1315 

Not sure about your issue with re-pairing but would be good practice to first remove device via mqtt message before re-pairing.
