### ISSUE TITLE
[Feature request]: Better capacity checks for coordinators

### ISSUE THREAD

**Issue by olgru** [Koenkk/zigbee2mqtt#17260]
### Is your feature request related to a problem? Please describe

Currenty my Zigbee Network is unstable. Im running HA-OS latest on Proxmox VM with usb connected Conbee 2 stick and - of course - Z2M.
Usually I regain stability by removing some devices from the network. I read a lot about number of parallel devices per coordinator, about additionally Sonoff-Sticks with router firmare for extenting and better coverage and all this. I can not say, that I've understood the logics on the zigbee mesh yet.
There are currecnty 107 devices in my network and stability is bad for a couple of days now. Devices loose connectivity, OTA is not working to INNR bulbs, Devices did not respond or timed out. Maybe this stated after updating Z2M to 1.30.3, but I can't evidence.

### Describe the solution you'd like

I would like to see hints about potential stability problems within the Z2M tools. I understand that this depends on devices and other things to, but I wounder if Z2M would be able to do some messurements regarding reachability, timeouts towards devices - maybe only devices providing router functionality...
The map is a funny connectivity drawing whihc takes a real long time to be build on my system. And after creating it, I didn't find an reasonable help, as any potential change will need 2-5 minutes again for redo the map to verify.

### Describe alternatives you've considered

None - I still have too less information from my systems to understand where the problems starts - maybe even on USB I/O...

### Additional context

None

**Comment by szymucha94** [comment]
Just enable "last seen" stats in HA and start creating automations per-device-class that will notify you if certain devices stop responding on time. Where "on time" values depend on HW you're using. Remember to update all device classes to the same firmware. This is what I do to keep the network stable, or at least minimize downtime as I have some time to manually reconnect a device (maybe once every 4-5 months). I have 72 devices under single sonoff CC2652p.
Keep in mind that zigbee endpoints can switch between routers and this is beyond coordinator's control. And for example aqara devices are known to be not-fully-compliant with zigbee standard.
>I can not say, that I've understood the logics on the zigbee mesh yet.
and you probably never will, as the logic is based on manufacturer-specific implementation. Stable networks usually consist on unified hardware. Often mixing different brands makes zigbee networks unpredictable.

**Comment by olgru** [comment]
You are right. I mixed it up - due to my german GUI... ;-) Last seen is just a status and it's enabled a long time already. However it's not reliable as I have Gledopto GL-MC-001 strips not seen for more than 2 months and still working perfectly (same for some other).
The second idea is not easy to use with HASSOS on VM where Z2M is integrated. I'm thinking about running the SkyConnect Stick (which is attached but in used) with the ZHA integration - maybe this is an idea.

Thank you!

At the end, I still have no idea how I can see if I do have a load problem within the Z2M data flows...
