### ISSUE TITLE
Frontend Interface zeigt auf einmal keine Geräte mehr an.

### ISSUE THREAD

**Issue by Hohenbostler** [Koenkk/zigbee2mqtt#17262]
### What happened?

Hallo, 

ich teste zigbee2mqtt im Docker mit Portainer . Dazu habe ich ein Zigbee LAN/USB/WLAN Gateway CC2652P

Leider habe ich das Problem das auf einmal schlagartig das gesamte Zigbee Netzwerk nicht mehr geht. Auf das Webinterface komme ich drauf leider werden dort keine Gerät mehr angezeigt. Steuern kann ich natürlich entsprechend auch nichts mehr. 

Eigentlich nutze ich Zigbee2mqtt mit iobroker, aber auch der Adapter schaltet dann einfach auf gelb.

Hier mal das log vom Portainer. 

[_Zigbee2Mqtt_logs.txt](https://github.com/Koenkk/zigbee2mqtt/files/11170632/_Zigbee2Mqtt_logs.txt)

Auf dem Frontent vom Zigbee2Mqtt habe ich mal unter Einstellungen den aktuellen Status runtergeladen. 

Hier der nihalt der json.

`{
    "devices": {},
    "deviceStates": {
        "0xdc8e95fffe19e385": {
            "linkquality": 3,
            "state": "OFF"
        },
        "Justin Steckdose": {
            "current": 0,
            "energy": 1165.99,
            "indicator_mode": "off/on",
            "linkquality": 120,
            "power": 0,
            "power_outage_memory": "restore",
            "state": "OFF",
            "voltage": 225
        },
        "Treppe": {
            "linkquality": 21,
            "state": "OFF"
        },
        "Steckdose waschmaschine": {
            "current": 0,
            "energy": 711.41,
            "indicator_mode": "off/on",
            "linkquality": 47,
            "power": 0,
            "power_outage_memory": "restore",
            "state": "ON",
            "voltage": 223
        },
        "Steckdose Firmenpc": {
            "current": 0.15,
            "energy": 807.06,
            "indicator_mode": "off/on",
            "linkquality": 51,
            "power": 14,
            "power_outage_memory": "restore",
            "state": "ON",
            "voltage": 224
        }
    },
    "touchlinkDevices": [],
    "touchlinkScanInProgress": false,
    "touchlinkIdentifyInProgress": false,
    "touchlinkResetInProgress": false,
    "networkGraph": {
        "links": [],
        "nodes": []
    },
    "networkGraphIsLoading": false,
    "groups": [],
    "bridgeState": "online",
    "bridgeConfig": {},
    "bridgeInfo": {
        "configSchema": {
            "properties": {},
            "required": []
        },
        "config": {
            "advanced": {}
        }
    },
    "logs": [],
    "extensions": [],
    "theme": "dark",
    "missingTranslations": {},
    "availability": {},
    "prepearingBackup": false,
    "backup": ""
}`

Hier dazu noch ein Bild 

![image](https://user-images.githubusercontent.com/42488069/230380181-a3683279-5bba-4112-ace3-be8534d47c65.png)

Ein Neustart würde das Problem denke ich beheben aber bevor ich das mache warte ich erstmal hier die antworten ab.

Ich hoffe jemand kann mir hier helfen und weiss wie ich das problem lösen kann.

Vielen Dank. 

### Zigbee2MQTT version

Frontend: 0.6.125

### Adapter firmware version

steht leider nichts

### Adapter

CC2652P + WT32-ETH01,

**Comment by Koenkk** [comment]
English only.
