### ISSUE TITLE
Tuya Temperatur Sensor falsch erkannt

### ISSUE THREAD

**Issue by nicknick25** [Koenkk/zigbee2mqtt#17268]
### What happened?

Ich nutze Tuya NHT01 Sensoren. Diese werden beim anlernen aber als TS0601 Sensoren erkannt. Sie liefern dadurch nur einmal Werte und danach nie wieder. In der Kompatibilitäts Liste ist der Sensor NHT01 gelistet das er funktioniert. Ich nutze 5 dieser Sensoren und alle haben das gleiche Problem.

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

20230405.0

### Adapter

Zigbee2mqtt

**Comment by Koenkk** [comment]
English only
