### ISSUE TITLE
2CH curtain module not showing second channel

### ISSUE THREAD

**Issue by draggero** [Koenkk/zigbee2mqtt#17271]
### What happened?
![image](https://user-images.githubusercontent.com/12039089/230792577-f3abed20-bf05-470a-bdd3-ae5942964dea.png)
Z2M recognizing module as TS130F but not recognized second channel in module
In ZHA showing it properly.
![image](https://user-images.githubusercontent.com/12039089/230792481-fd3ca0db-f835-40d3-a075-928c8b1b24f5.png)

### What did you expect to happen?

I Want to control each channel separately.

### How to reproduce it (minimal and precise)

Just go to configuration :)
![image](https://user-images.githubusercontent.com/12039089/230605962-4ad961c2-66f8-4c9b-84fe-d1d5326cbe3a.png)

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBdongle-E

**Solved**

https://github.com/Koenkk/zigbee2mqtt/issues/8705

**Comment by sodiniss** [comment]
Hello, I have the same problem, how did you fix it? Thanks

**Comment by draggero** [comment]
Hi, i made external converter from here https://github.com/Koenkk/zigbee2mqtt/issues/8705 but not tested yet.
