### ISSUE TITLE
Power Plug (PLUG-001SPB2). Device didn't respond to OTA request

### ISSUE THREAD

**Issue by garry0garry** [Koenkk/zigbee2mqtt#17280]
### What happened?

Model ID: TS011F
Manufacturer name: _TZ3000_gjnozsaz
Zigbee2MQTT 1.30.3

There is an update, but it cannot be installed. Why?

```
{
    "child_lock": "UNLOCK",
    "indicator_mode": "off/on",
    "last_seen": "2023-04-08T17:21:59+03:00",
    "linkquality": 255,
    "power_outage_memory": "restore",
    "state": "ON",
    "update": {
        "installed_version": 77,
        "latest_version": 192,
        "state": "available"
    },
    "voltage": 213,
    "current": 0,
    "energy": 0,
    "power": 0,
    "update_available": null
}

```
`{"id":9,"type":"Router","ieeeAddr":"0xa4c138c20463410f","nwkAddr":63868,"manufId":4417,"manufName":"_TZ3000_gjnozsaz","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�V�+\u0012","65506":54,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_gjnozsaz","zclVersion":3,"appVersion":77,"modelId":"TS011F","powerSource":1}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":216,"rmsCurrent":0,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,0]}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"powerOnBehavior":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe718922","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe718922","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe718922","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-892627439},"lastSeen":1680961504559,"defaultSendRequestWhen":"immediate"}
`

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

7.2.0.0 build 108

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Debug log

debug 2023-04-08 17:13:55 Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"0xa4c138c20463410f","transaction":"ttr7l-28"}'

info 2023-04-08 17:13:55 Updating '0xa4c138c20463410f' to latest firmware

debug 2023-04-08 17:13:55 Updating to latest '0xa4c138c20463410f' (TS011F)

debug 2023-04-08 17:13:55 Using endpoint '1'

debug 2023-04-08 17:13:55 Update of '0xa4c138c20463410f' failed (Error: Device didn't respond to OTA request)

info 2023-04-08 17:13:55 MQTT publish: topic 'zigbee2mqtt/0xa4c138c20463410f', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2023-04-08T17:06:12+03:00","linkquality":255,"power":0,"power_outage_memory":"restore","state":"ON","update":{"installed_version":77,"latest_version":192,"state":"available"},"update_available":null,"voltage":214}'
info 2023-04-08 17:13:55MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"0xa4c138c20463410f"},"error":"Update of '0xa4c138c20463410f' failed (Device didn't respond to OTA request)","status":"error","transaction":"ttr7l-28"}'

error 2023-04-08 17:13:55 Update of '0xa4c138c20463410f' failed (Device didn't respond to OTA request)

debug 2023-04-08 17:13:55 Error: Device didn't respond to OTA request at requestOTA (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:191:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:279:21) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:267:41)

**Comment by garry0garry** [comment]
Solution: downgrade adapter firmware to 6.10.3.

**Comment by malgoe** [comment]
Same problem here except I'm using a Conbee 1. Coordinator revision: 0x26400500. My plug has installed version 74 instead of 77 but otherwise same behaviour.
