### ISSUE TITLE
Can't repair with old device without reset button

### ISSUE THREAD

**Issue by kizovinh** [Koenkk/zigbee2mqtt#17290]
### What happened?

I have a Zigbee led strip controller without any button. It only has the output for the RGBCW Led. I paired it, and then deleted it on zigbee2mqtt web. Then I can't pair it again, permit join, bringing the controller nearby with the coordinator, reconnecting the power plug, restart z2m, v.v... don't work.

Finally, I unplugged and then plugged in the power plug for my controller several times continuously, and it work. I think it is some "safe mode" or "error reset mode" on my controller, and it restores the factory reset state, but what if my controller doesn't have that function, how can I repair an "unrepaired device" without any reset button?

I am using home assistant and Z2M integration. I believe there is some hidden file that saves the id of my controller, so it ignores the controller when it power on, but I don't know where is it.

### What did you expect to happen?

It should have some debugging feature to catch all the Frame on events outside the Zigbee network, and then it should provide the manual config to add a ZigBee device with id or MAC ID or some thing...

### How to reproduce it (minimal and precise)

Pair device, then delete it from Z2M. 

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

 20201010

### Adapter

CC2538 + CC2592

**Comment by szymucha94** [comment]
>I believe there is some hidden file that saves the id of my controller, so it ignores the controller when it power on, but I don't know where is it.
I don't think z2m works that way. I can easily turn pairing mode on any of my deleted devices and as long as z2m is in "permit join" mode they re-pair.
Check your led controller's documentation. If it doesn't have a button to enter "pairing mode" most likely power cycling does that. It's for sure the case for many light bulbs.
