### ISSUE TITLE
Allow new attributes [linkquality] on MQTT messages

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#173]
How difficult would it be to add new attributes to the mqtt messages ?
running zigbee2mqtt with DEBUG=* I can see attributes I would find useful to report:
- linkquality
- timestamp

what's the timestamp reference btw ? is that something the device reports or is that a timestamp the gateway creates ?

**Comment by palitu** [comment]
I really think that link quality would be a handy thing to track.  I am just now realising how poor the range is on these devices.

**Comment by lolorc** [comment]
If I may, could it be possible to add a last_seen attributes to every mqtt payload ?
this timestamp would be generated by the host, and would help to know when was the last update.
it could also be of some use for retained messages.

**Comment by ryanbeaton** [comment]
While being wary of json bloat these would be useful to use

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Koenkk** [comment]
@lolorc yes, this is indeed nice to have.

**Comment by tb-killa** [comment]
@Koenkk We should use the ```pollTimer``` function from ```controller.js``` and use the 
[Query the link quality index from a certain device by its ieee address.](https://github.com/zigbeer/zigbee-shepherd/wiki#lqiieeeaddr-callback) function from zigbee-shepherd.

Or maybe you´v got another idea :) ?

**Comment by Koenkk** [comment]
@tb-killa I think for every received zigbee message we should parse the linkquality and add it to the message.

**Comment by tb-killa** [comment]
@Koenkk do we get the lqi information with each incoming message? I didn´t see this type of message if i use ``DEBUG=* npm start`` ... or I missed her ^^

**Comment by tb-killa** [comment]
I found this information with ``DEBUG=* npm start``, it parsed from ``cc-znp`` like this 

``
cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 3, srcaddr: 14129, srcendpoint: 3, dstendpoint: 1, wasbroadcast: 0, linkquality: 0, securityuse: 0, timestamp: 12584614, transseqnumber: 0, len: 7, data: <Buffer 18 09 0d 01 00 00 21> } +2s
``

@Koenkk Do you know if we got this Information inside zigbee-shepherd too ?
I search for ``link`` and found references inside ``lib/components/af.js``
It seems to be that it could be available via 
```
case 'incomingMsg':
..
case 'incomingMsgExt':
..
case 'zclIncomingMsg':
..
```

If you point me i could maybe help :)

**Comment by Koenkk** [comment]
Added the `linkquality` attribute to the messages.

**Comment by jarrah31** [comment]
Regarding link quality, what do the numbers represent? Lower the number = better or worse signal for example? What's the number range?
TIA

**Comment by talondnb** [comment]
My routers are both at 2 and 5, not a good sign. :(

**Comment by Koenkk** [comment]
The lower the number the worst the signal, 2 and 5 are indeed very low.

In the same room I get somewhere between 50-100.

**Comment by lolorc** [comment]
Hi there,
I've just updated from your latest changes, I correctly get the linkquality attribute, Thanks a lot.
Any idea what would be the higher value ? Been able to get 148 by bringing a device just in front of the coordinator.

**Comment by lolorc** [comment]
how do you plan on implementing the last_seen attribute ? Would it be a simple timestamp locally generated from the local time of the computer running the zigbee2mqtt daemon ?
I guess that would be enough since the zigbee timestamp attribute is holding a relative number.

**Comment by faronov** [comment]
Found some interesting how to get RSSI value
https://sunmaysky.blogspot.com/2017/02/conversion-between-rssi-and-lqi-in-z.html

**Comment by lolorc** [comment]
closing, reporting timestamp/last_seen for later :)
