### ISSUE TITLE
Aqara WS-EUK04 not emitting actions in decoupled mode

### ISSUE THREAD

**Issue by s-nems** [Koenkk/zigbee2mqtt#17305]
### What happened?

Using:

[WS-EUK04](https://www.zigbee2mqtt.io/devices/WS-EUK04.html#xiaomi-ws-euk04)

model: lumi.switch.n2aeu1

In z2m "action" is never triggered in decoupled (wireless) mode.
Also, below fields are reporting N/A:
- power
- energy
- device_temperature

I also have WS-EUK01 (lumi.switch.l1aeu1) - H1 EU (no neutral, single rocker), which works for decoupled mode, but only after changing mode_switch to quick_mode.

For control_relay mode, which is actually a physical switch the action trigger works only after first connecting to ZHA and then moving back to z2m, which is really odd.

### What did you expect to happen?

The state should be updated for decoupled mode with proper actions like single_left, right_left etc.

### How to reproduce it (minimal and precise)

- Connect Aqara lumi.switch.n2aeu1 (Aqara smart wall switch H1 EU with neutral, double rocker)
- Change endpoint state to decoupled
- Click the button, nothing shows in debug logs or state

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

zStack3x0

### Adapter

Sonoff ZBDongle-P CC2652P

**Comment by s-nems** [comment]
Similar issue:
https://github.com/Koenkk/zigbee2mqtt/issues/11507#issuecomment-1111195386

**Comment by calkeo** [comment]
I have the same issue with the WS-EUK01 (single rocker no neutral), where I'm not seeing any state updates for action in either control_relay or decoupled mode.

The device is definitely connected, as I can toggle the relay on and off through z2m, but there's no actions being reported by the switch whatsoever.

**Comment by calkeo** [comment]
I eventually managed to get this working by simply removing the device from z2m and then re-pairing it.

It's worth pointing out for anyone coming across this issue, that the no-neutral version (although @s-nems is using the neutral version) does _not_ work well with decoupled mode if it's being used to toggle a smart bulb on the same electrical loop. As soon as the bulb is toggled off there's not enough power going through the switch to keep it connected, and it just drops off the network until the bulb is toggled on again.

**Comment by s-nems** [comment]
> For z-stack users, please make sure you are running at least firmware `20211114`

Updating to the newest z-stack for Sonoff solved the issue. Thank you! 😄

**Comment by oliverholliday** [comment]
Firmware! I had no idea, I just updated my CC2531 firmware and it started working.

Thanks!

https://github.com/Koenkk/zigbee2mqtt/issues/17477

**Comment by shift-del1** [comment]
I ran into the same issue , my WS-EUK03 worked fine and on last Friday it suddenly stopped. I tried everything with no luck until I found this topic. I upgraded my ConBee II to FW version 26780700, removed and reconnected the switch and action with the 3 sensors started to work again. Thank you for the solution.

**Comment by kaktus11** [comment]
I have exactly the same problem with [WS-EUK04](https://www.zigbee2mqtt.io/devices/WS-EUK04.html#xiaomi-ws-euk04). I use skyconnect dongle with latest firmware. Do anyone have a solution for this? Thank you.

**Comment by abelsolomon-git** [comment]
> I ran into the same issue , my WS-EUK03 worked fine and on last Friday it suddenly stopped. I tried everything with no luck until I found this topic. I upgraded my ConBee II to FW version 26780700, removed and reconnected the switch and action with the 3 sensors started to work again. Thank you for the solution.

Have you had any other issues with this firmware or has it worked smoothly for you since?

**Comment by Vincentiano** [comment]
For Skyconnect users, the problems are fixed using the latest firmware from: https://github.com/darkxst/silabs-firmware-builder/tree/4.4.3/firmware_builds/skyconnect

**Comment by jkufner** [comment]
I followed https://github.com/Koenkk/zigbee2mqtt/discussions/16573#discussioncomment-9430968 and it seems to work.  Upgrading SkyConnect firmware to [ncp-uart-hw-v7.4.3.0-skyconnect-115200.gbl](https://github.com/darkxst/silabs-firmware-builder/blob/4.4.3/firmware_builds/skyconnect/ncp-uart-hw-v7.4.3.0-skyconnect-115200.gbl) fixed the issue. I've also reseted the switch after the upgrade.

**Comment by gregrs-uk** [comment]
I had the same issue with the Aqara WS-EUK04 and Sonoff ZBDongle-P. Updating to the latest firmware (`Z-Stack_3.x.0_coordinator_20240710`) and Zigbee2MQTT 1.40.2 then removing and re-adding the switch to the network fixed it. Thanks.

**Comment by max246** [comment]
That didnt work for me. I updated my firmware and still very confusing how this switch should behave.
I dont get any status on decouple and when is set to decouple it just trigger the relay via HA but it doenst when pressing the button.
