### ISSUE TITLE
Pressing physical button on Xiaomi WS-USC04 does not update state

### ISSUE THREAD

**Issue by ic-dev21** [Koenkk/zigbee2mqtt#17306]
### What happened?

I need to manually press the update button for it to show.

I would like to use the physical pressing for automations but this does not work.

### What did you expect to happen?

When I press the button I expect the state to update.

### How to reproduce it (minimal and precise)

Press the button, does not update.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20210708

### Adapter

Zdongle-P

**Comment by ic-dev21** [comment]
Updated firmware for sonoff stick. Issue remains.

**Comment by ic-dev21** [comment]
Setting up reporting manually fixed this.

**Comment by calkeo** [comment]
@ic-dev21 can you share the reporting that you manually set up for this? Seems to be related to #17305

**Comment by ic-dev21** [comment]
> @ic-dev21 can you share the reporting that you manually set up for this? Seems to be related to #17305

Sure thing, I added the onoff state of both switches as endpoints with a 10s internval. Here you go:

![image](https://user-images.githubusercontent.com/108159253/233494467-cd0ea3d6-d3d3-4ca5-9d31-3122e71b91c4.png)

**Comment by Simon-CR** [comment]
I am still having this issue. (need to remove stale)
