### ISSUE TITLE
Shyne LED Filament (recognized as model EcoDim )flashes sporadically

### ISSUE THREAD

**Issue by richimaint** [Koenkk/zigbee2mqtt#17316]
### What happened?

II have 2 Shyne A-371884 LED filament lamps that are recognized as EcoDim ED-10041 in Z2M. When these are turned off they flash sporadically, likewise when they are turned on these go off briefly.
https://www.lampen1a.de/SHYNE-Smartes-ZigBee-LED-Leuchtmittel-E27-amber-tunable-white-Standard-Birne-A60-7W-650-Lumen-1er-Pack

### What did you expect to happen?

do not flash constantly 

### How to reproduce it (minimal and precise)

do not know how to reproduce this 

### Zigbee2MQTT version

have these only since version 1.29

### Adapter firmware version

20220219

### Adapter

Sonoff ZigBee Dongle 3.0 plus

**Comment by richimaint** [comment]
nobody the same problem?

**Comment by richimaint** [comment]
nobody

**Comment by ckulas** [comment]
I have it too while using 1.35.1.

**Comment by richimaint** [comment]
the same with 1.35.1

**Comment by ckulas** [comment]
Can we identify the exact version where it started?

**Comment by richimaint** [comment]
I suspect that it is not due to Z2M, since I have had these lights, they have been flashing sporadically.

**Comment by ckulas** [comment]
I had them coupled with my Hue bridge - no flashing. I was running (I think) 1.15 and didn't see the flashing. What do you suspect it to be if not Z2M?

**Comment by richimaint** [comment]
I think I've only had Z2M since 1.28.0 and that's where it happened.

**Comment by ckulas** [comment]
Solved my issue by resetting and repairing the lights. This is a pain in the ass with these lights, but I have a smart power outlet which I was scripting for this purpose.

**Comment by richimaint** [comment]
How did you reset them?

**Comment by FrazerDungeon** [comment]
Hello,
I have the same problem with the same product. I use the lamps since almost three years and have had an old version of z2m. About 6 months ago I updated z2m to the latest version and since then this kind of lamps a blinking sporadic. I update since the z2m regularly and also reseted the lamp as described above. But no success. I dont know which version number I had before.
Any suggestions?
