### ISSUE TITLE
[New device support]: LoraTap Zigbee 2-Gang Dimmer Module

### ISSUE THREAD

**Issue by okastl** [Koenkk/zigbee2mqtt#17333]
### Link

https://www.aliexpress.com/item/1005005035307347.html

### Database entry

{"id":5,"type":"Router","ieeeAddr":"0xa4c138da583c9910","nwkAddr":3312,"manufId":4417,"manufName":"_TZE200_gwkapsoq","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0018\u0000\u0000\u0000e\u0019\u0000\u0000\u0000\u0012⮜+\u0017䮜+\u0013䮜+e宜+\u0012\u0011\u0000\u0000\u0000e\u0012\u0000\u0000\u0000\u0012","65506":54,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_gwkapsoq","powerSource":1,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1681472660334,"defaultSendRequestWhen":"immediate"}

### Comments

This is just a variation of this device:
https://www.zigbee2mqtt.io/devices/TS0601_dimmer_2.html

Changing fingerprint in zigbee-herdsman-converters/devices/tuya.js to this:

`        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_fjjbhx9d', '_TZE200_e3oitdyu', '_TZE200_gwkapsoq']),
`
the dimmer works fine.

### External converter

EDIT:
The 2-Gang dimmer version definition in tuya.js of TS601 lacks the "light_type" setting, which is present in the 1-Gang definition.
I attach an external converter which adds light_type to the 2-Gang dimmer similar to the 1-Gang dimmer

[DualDim.zip](https://github.com/Koenkk/zigbee2mqtt/files/11233008/DualDim.zip)

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
