### ISSUE TITLE
[New device support]: Zemismart ZM_JM02

### ISSUE THREAD

**Issue by MHillyer** [Koenkk/zigbee2mqtt#17340]
### Link

https://www.amazon.com/Plantation-Shutters-Electric-Automatic-Rechargeable/dp/B0B74S4FVH?ref_=ast_sto_dp&th=1

### Database entry

Unknown

### Comments

The ZM_JM02 is just a new model name on the ZM_AM02, I was able to get it working by changing the fingerprint in zemismart.js to:

`fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_iossyxra'}, {modelID: 'TS0601', manufacturerName: '_TZE200_cxu0jkjk'}],`

Sorry, I don't know how to make this a pull request but hopefully that's enough to get it implemented.

**Comment by Koenkk** [comment]
Added, thanks!
