### ISSUE TITLE
OSRAM AC03641 occasionally failing

### ISSUE THREAD

**Issue by IrealiTY** [Koenkk/zigbee2mqtt#17353]
### What happened?

One of my bulbs seems to be lagging when triggered or not responding at all

```"Publish 'set' 'state' to 'Corridor Light 1' failed: 'Error: Command 0x7cb03eaa0a04ac17/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 34902 - 3 - 13 - 6 - 11 after 10000ms)'"```

From testing in the past week, it's kind of the only bulb in my network that "fails out" randomly, before I go and buy a new bulb, I wanted to see if there is something I can do to improve the situation? Before z2m I was using Philips Hue and had occasional fall-outs like this with other bulbs too (which got better after z2m) but I always shrugged it off as "Phillips behaving bad with non Philips bulbs).

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

HomeAssistant Yellow (EZSP v8?)

### Debug log

[log (1).txt](https://github.com/Koenkk/zigbee2mqtt/files/11240580/log.1.txt)

**Comment by BerndDA** [comment]
Exact same problem here.
I have 3 of those bulbs and all of them show this behaviour. Worst is that after they reconect to the network, they turn on automatically. Not a good base for discussions if your partner wakes up at night :-)
I ended up replacing the bulb with a tint model...
