### ISSUE TITLE
Possible to back up CC2531 if it needs to be replaced?

### ISSUE THREAD

**Issue by ericmiller777** [Koenkk/zigbee2mqtt#1735]
I'm going to attempt the antenna mod, anyway I can back up my CC2531 in case I break it?

**Comment by sycophantic** [comment]
You should be able to swap devices. Nothing is stored on it, just backup your config files.

**Comment by ericmiller777** [comment]
Okay, so I don't need it's ID or number or anything?

**Comment by Koenkk** [comment]
@ericmiller777 no backup is required indeed, just swap.
