### ISSUE TITLE
Aqara S3 Thermostat

### ISSUE THREAD

**Issue by mehravishay** [Koenkk/zigbee2mqtt#17392]
### Link

https://www.aqara.com/Smart-Thermostat-S3_overview

### Database entry

0x54ef4410005e6ccd

### Comments

I tried to add the Aqara S3 thermostat and it paired however the device is showing unsupported. Can anyone assist me with this?

**Comment by ingria** [comment]
Bump

**Comment by FlyingFinn11** [comment]
Hello can we re-open this file? I just got this device and can confirm the same experience. Only humidity is picked up. I can't control on/off or see current temperature. Happy to chip in with data. Cheers.
