### ISSUE TITLE
Tuya TS0012 _TZ3000_18ejxno0 Dual Gang Switch - Decoupled Mode

### ISSUE THREAD

**Issue by dave21w** [Koenkk/zigbee2mqtt#17398]
### Is your feature request related to a problem? Please describe

Not a problem as such but I need to decouple the physical switch from the controlled output, is this an option that could be added for this device, mine is actually branded as a MOES switch but identifies as the Tuya TS0012 in Z2M.

### Describe the solution you'd like

Option to decouple the physical switch from changing output state of the switch, just send a pressed action to Z2M and let it decide what to do next.

### Describe alternatives you've considered

Too many to mention in trying to resolve the issue I have

### Additional context

None

**Comment by mrdarrengriffin** [comment]
I have the same issue. Did you ever find a solution @dave21w?
