### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by kaelsaes** [Koenkk/zigbee2mqtt#174]
After UPDATE following messages occur:

```
2018-7-3 06:25:39 INFO Starting zigbee2mqtt version 0.0.0 (commit #7cec5f2)
2018-7-3 06:25:39 INFO Starting zigbee-shepherd
2018-7-3 06:25:43 INFO Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
2018-7-3 06:26:43 INFO Starting zigbee-shepherd
2018-7-3 06:26:46 ERROR Error while starting zigbee-shepherd!
2018-7-3 06:26:46 ERROR Press the reset button on the stick (the one closest to the USB) and start again
2018-7-3 06:26:46 ERROR Failed to start
```

```
Jul 03 06:35:33 Raspberry-MQTT systemd[1]: Started zigbee2mqtt.
Jul 03 06:35:34 Raspberry-MQTT npm[809]: > zigbee2mqtt@0.0.0 start /opt/zigbee2mqtt
Jul 03 06:35:34 Raspberry-MQTT npm[809]: > node index.js
Jul 03 06:35:36 Raspberry-MQTT npm[809]: 2018-7-3 06:35:36 INFO Starting zigbee2mqtt version 0.0.0 (commit #7cec5f2)
Jul 03 06:35:36 Raspberry-MQTT npm[809]: 2018-7-3 06:35:36 INFO Starting zigbee-shepherd
Jul 03 06:35:44 Raspberry-MQTT npm[809]: 2018-7-3 06:35:44 INFO Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
Jul 03 06:36:44 Raspberry-MQTT npm[809]: 2018-7-3 06:36:44 INFO Starting zigbee-shepherd
Jul 03 06:36:52 Raspberry-MQTT npm[809]: 2018-7-3 06:36:52 ERROR Error while starting zigbee-shepherd!
Jul 03 06:36:52 Raspberry-MQTT npm[809]: 2018-7-3 06:36:52 ERROR Press the reset button on the stick (the one closest to the USB) and start again
Jul 03 06:36:52 Raspberry-MQTT npm[809]: 2018-7-3 06:36:52 ERROR Failed to start
Jul 03 06:36:52 Raspberry-MQTT npm[809]:        
 {"message":"request timeout","stack":"Error: request timeout
    at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:254:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at CcZnp.emit (events.js:211:7)
    at Timeout.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:233:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)"}
```

**Comment by kaelsaes** [comment]
Yes, I did. Without success.

**Comment by Koenkk** [comment]
Are you running the latest firmware from: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/bin ?

**Comment by kaelsaes** [comment]
With the newest firmware it seems to work fine.

**Comment by RajeeRah** [comment]
Any solution here? i am stuck at the same point, i did reflash / reinstalled / different versions of node and npm ... nothing happens.

ERROR:
018-7-27 23:09:21 INFO Starting zigbee2mqtt version 0.1.0 (commit #ae41b7b)
2018-7-27 23:09:21 INFO Starting zigbee-shepherd
2018-7-27 23:09:21 INFO Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
^C2018-7-27 23:09:30 ERROR Not connected to MQTT server!
2018-7-27 23:09:30 ERROR Cannot send message: topic: 'zigbee2mqtt/bridge/state', payload: 'offline
2018-7-27 23:09:30 INFO zigbee-shepherd stopped

Conf:
# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0

it is something with permission? zigbee2mqtt has pi user permission.

tried with ioBroker: 

Error:
zigbee.0 | 2018-07-28 00:11:11.055 | error | Error while starting zigbee-shepherd!. Error: request timeout

Hope someone can help ...

Thank you in advance.

**Comment by Koenkk** [comment]
What is the output of `ls /dev`? And does it work when running as root?

**Comment by RajeeRah** [comment]
Hi Koenkk, 

Thank you for your Replay and sorry for delay, i was just waiting for the new Zigbee stick.
And this time worked every fine, I think there was an issue with the stick. Both sticks looks same but that one which was not working has always RED LED and the new one GREEN LED.

ls /dev output, was showing same result (everything correctly) as in the tutorial. and it did not run with the root as well.

**Comment by salopette** [comment]
Hello, I just do not get to work.

Everything also installs the right port, but there is always a mistake.
pi@raspberry3:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@0.1.5 start /opt/zigbee2mqtt
> node index.js

  zigbee2mqtt:info 2018-9-23 10:56:32 Logging to directory: '/opt/zigbee2mqtt/data/log/2018-09-23.10-56-32'
  zigbee2mqtt:info 2018-9-23 10:56:33 Starting zigbee2mqtt version 0.1.5 (commit #7d49e13)
  zigbee2mqtt:info 2018-9-23 10:56:33 Starting zigbee-shepherd
  zigbee2mqtt:info 2018-9-23 10:56:33 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
  zigbee2mqtt:info 2018-9-23 10:57:33 Starting zigbee-shepherd
  zigbee2mqtt:error 2018-9-23 10:57:33 Error while starting zigbee-shepherd!
  zigbee2mqtt:error 2018-9-23 10:57:33 Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 2018-9-23 10:57:33 Failed to start
        {"message":"Error Resource temporarily unavailable Cannot lock port","stack":"Error: Error Resource temporarily unavailable Cannot lock port"}
