### ISSUE TITLE
Gledopto is disabled power_on_behavior  on GL-C-009P

### ISSUE THREAD

**Issue by maelcolm** [Koenkk/zigbee2mqtt#17404]
### What happened?

The GL-C-009P LED controller supports power_on_behavior, but was disabled in the last update.

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E (EZSP v8)

**Comment by Koenkk** [comment]
Enabled it again!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
