### ISSUE TITLE
Device Reporting Wrong Colour

### ISSUE THREAD

**Issue by boojew** [Koenkk/zigbee2mqtt#1740]
# Bug Report
When one of the Ecosmart bulbs reports in that it has been turned on, it always seems to report in as red ("x":0.749,"y":0.249) rather than it's actual color - warm white. Manually changing the colour of the bulb in HASS works and it shows the correct colour - additionally if I then set the colour back to red - the bulb does turn red. My guess is when I added support I messed up for warmth? Not sure

zigbee2mqtt version: 1.5 
CC253X firmware version: 20190608

The device in question is 
    { 
        zigbeeModel: ['zhaRGBW'],      
        model: 'D1821',                                   
        vendor: 'EcoSmart',
        description: 'A19 RGB bulb',                                                         
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    }, 

I've tried using the ignore_light_color_colortemp_report fromZigbee parameter in the config, but doesnt change anything.

**Comment by Koenkk** [comment]
The color you see is probably a cached value, does it happen when e.g. change color -> change color temp -> color state is incorrect?

**Comment by boojew** [comment]
Changing the colour always works. But going from on to off always shows
this behaviour. Even in private browsing and with a different browser.

**Comment by Koenkk** [comment]
So when e.g:

- bulb is on and red
- turn bulb off
- turn bulb on
- bulb is not red anymore but still reports red -> is this the problem?

**Comment by boojew** [comment]
1. Bulb is off -> actual bulb is off, hass shows off
2. Bulb is turned on -> actual bulb is white, hass shows red
3. Bulb changes colour -> hass and bulb show correct colour
4. Bulb is turned off -> see 2

I don’t know how to translate the XY colour into rgb, so not sure if
zigbee2mqtt is sending the red or hass is going something weird.

Thanks

**Comment by Koenkk** [comment]
Can you provide me a log showing the problems and annotating the lines where wrong states get published? (make sure to set `log_level: debug`). http://www.zigbee2mqtt.io/configuration/configuration.html
