### ISSUE TITLE
Adding support for the TuYa TS0044 _TZ3000_wkai4ga5 switch.

### ISSUE THREAD

**Issue by mgvelm** [Koenkk/zigbee2mqtt#17402]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Please add to the Zigbee2mqtt: switch TuYa TS0044 _TZ3000_wkai4ga5. This switch is supported by ZHA. It is similar to the Lonsonho TS0044, which is operated by Zigbee2mqtt.

### Describe alternatives you've considered

Nothing

### Additional context

Nothing

**Comment by Koenkk** [comment]
Any device with modelId `TS0044` should be detected as supported, if not, make sure you are running the latest z2m version.
