### ISSUE TITLE
HA State max length is 255 characters - Aqara Pet Feeder C1 (Xiaomi ZNCWWSQ01LM)

### ISSUE THREAD

**Issue by cpvbruno** [Koenkk/zigbee2mqtt#17415]
### What happened?

Logger: homeassistant.components.mqtt.models Source: core.py:1196  Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))  First occurred: April 20, 2023 at 5:56:34 PM (36 occurrences)  Last logged: 10:30:02 PM
* Exception raised when updating state of sensor.aqara_pet_feeder_c1_schedule, topic: 'zigbee2mqtt/Aqara pet feeder C1' with payload: b'{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"schedule","led_indicator":"OFF","linkquality":112,"mode":"schedule","portion_weight":8,"portions_per_day":4,"schedule":[{"days":"everyday","hour":10,"minute":15,"size":1},{"days":"everyday","hour":16,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1},{"days":"everyday","hour":22,"minute":30,"size":1},{"days":"everyday","hour":8,"minute":15,"size":1}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":32}'
* Exception raised when updating state of sensor.aqara_pet_feeder_c1_schedule, topic: 'zigbee2mqtt/Aqara pet feeder C1' with payload: b'{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"schedule","led_indicator":"OFF","linkquality":105,"mode":"schedule","portion_weight":8,"portions_per_day":4,"schedule":[{"days":"everyday","hour":10,"minute":15,"size":1},{"days":"everyday","hour":16,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1},{"days":"everyday","hour":22,"minute":30,"size":1},{"days":"everyday","hour":8,"minute":15,"size":1}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":32}'
* Exception raised when updating state of sensor.aqara_pet_feeder_c1_schedule, topic: 'zigbee2mqtt/Aqara pet feeder C1' with payload: b'{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"schedule","led_indicator":"OFF","linkquality":105,"mode":"schedule","portion_weight":8,"portions_per_day":5,"schedule":[{"days":"everyday","hour":10,"minute":15,"size":1},{"days":"everyday","hour":16,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1},{"days":"everyday","hour":22,"minute":30,"size":1},{"days":"everyday","hour":8,"minute":15,"size":1}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":32}'
* Exception raised when updating state of sensor.aqara_pet_feeder_c1_schedule, topic: 'zigbee2mqtt/Aqara pet feeder C1' with payload: b'{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"schedule","led_indicator":"OFF","linkquality":109,"mode":"schedule","portion_weight":8,"portions_per_day":5,"schedule":[{"days":"everyday","hour":10,"minute":15,"size":1},{"days":"everyday","hour":16,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1},{"days":"everyday","hour":22,"minute":30,"size":1},{"days":"everyday","hour":8,"minute":15,"size":1}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":40}'
* Exception raised when updating state of sensor.aqara_pet_feeder_c1_schedule, topic: 'zigbee2mqtt/Aqara pet feeder C1' with payload: b'{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"schedule","led_indicator":"OFF","linkquality":105,"mode":"schedule","portion_weight":8,"portions_per_day":5,"schedule":[{"days":"everyday","hour":10,"minute":15,"size":1},{"days":"everyday","hour":16,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1},{"days":"everyday","hour":22,"minute":30,"size":1},{"days":"everyday","hour":8,"minute":15,"size":1}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":40}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 689, in _async_write_ha_state
    hass.states.async_set(entity_id, state, attr, self.force_update, self._context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1547, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1196, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.aqara_pet_feeder_c1_schedule. State max length is 255 characters

### What did you expect to happen?

Error is not logged

### How to reproduce it (minimal and precise)

Make a schedule for the pet feeder with 5 events per day. When the feeder feeds, this error will be logged in home assistant
`homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.aqara_pet_feeder_c1_schedule. State max length is 255 characters`

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

 20220219

### Adapter

Sonoff Zigbee 3.0

**Comment by Koenkk** [comment]
This is a HA limitation, see https://github.com/Koenkk/zigbee2mqtt/issues/16460#issuecomment-1466518618 for a workaround.
