### ISSUE TITLE
Only one device appearing on mobile

### ISSUE THREAD

**Issue by Daniel15** [Koenkk/zigbee2mqtt#17418]
### What happened?

When I load Zigbee2MQTT's web UI on my phone (Samsung Galaxy S22), I only see one device:
![image](https://user-images.githubusercontent.com/91933/233751761-37a0289c-9630-49e8-b135-69cc473ca1b6.png)

This happens in both Firefox and Chrome, and still happens when "desktop mode" is enabled.

### What did you expect to happen?

I expect all devices to appear, like what I see on desktop:
![image](https://user-images.githubusercontent.com/91933/233751783-ded12c3e-981a-479f-b3cb-8a3598eaea5a.png)

### How to reproduce it (minimal and precise)

All I'm doing is loading the UI

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20211217

### Adapter

Sonoff USB stick

### Debug log

N/A

**Comment by Koenkk** [comment]
You've filtered the list with a search (`Exter`), removing it should show all devices again.

<img width="578" alt="Screenshot 2023-04-22 at 09 29 53" src="https://user-images.githubusercontent.com/2892853/233769965-054bb206-85de-49a4-8f77-5115da08ae12.png">

**Comment by Daniel15** [comment]
Hahaha wow, I can't believe I didn't notice that. I didn't realise it saved searches, and the saved searches could be different per device (I guess it's in localstorage?)

Sorry for wasting your time 😅

**Comment by Koenkk** [comment]
No problem, enjoy! 😄
