### ISSUE TITLE
Miboxer FUT035Z turns off

### ISSUE THREAD

**Issue by Robotron80** [Koenkk/zigbee2mqtt#17416]
### What happened?

I've got 3 Miboxer FUT035Z LED controllers (KANT_Licht-AF, KANT_Licht-Boden-1, KANT_Licht-Boden-2) in my kitchen. When I turn on those lights, often the LEDs suddenly turns off. Sometimes they slowly fade in again after some minutes. In Home Assistant the lights are shown as turned on. 

Only this model of Zigbee devices creates trouble. I already tried to pair the devices again and even changed the Zigbee dongle from Conbee II to Sonoff Dongle P.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20221226

### Adapter

SONOFF ZBDongle-P

### Debug log

[log1.txt](https://github.com/Koenkk/zigbee2mqtt/files/11299180/log1.txt)

**Comment by lux73** [comment]
few month ago i had baught a MiBoxer FUT039Z from Ali

this Device creates so many trouble in my Network: i am unable to pair new Devices if the MiBoxer is Part of my Mesh, sometimes its slowdown my whole Zigbee Network so i am unable to control anything (must hard power off the MiBoxer), unable to switch off the RGB Stripe connected via MiBoxer Controller (on & changing Color no Problem)

in my experience they are cheap & small but they are crap! i would nobody recommend to buying this...

please note this are my personal experience! ;-)
