### ISSUE TITLE
[New device support]: TS0219

### ISSUE THREAD

**Issue by bistenijoker** [Koenkk/zigbee2mqtt#17419]
### Link

https://es.aliexpress.com/item/1005002346888332.html?spm=a2g0o.order_list.order_list_main.28.733d194dPOJ3Qq&gatewayAdapt=glo2esp

### Database entry

{     "id": 20,     "type": "Router",     "ieeeAddr": "0x847127fffe27cf8f",     "nwkAddr": 16111,     "manufId": 0,     "manufName": "_TYZB01_ynsiasng",     "powerSource": "Mains (3 phase)",     "modelId": "TS0219",     "epList": [         1     ],     "endpoints": {         "1": {             "profId": 260,             "epId": 1,             "devId": 1027,             "inClusterList": [                 0,                 1,                 3,                 4,                 5,                 1280,                 1282,                 61183             ],             "outClusterList": [                 3,                 25             ],             "clusters": {                 "genBasic": {                     "attributes": {                         "modelId": "TS0219",                         "manufacturerName": "_TYZB01_ynsiasng",                         "powerSource": 2,                         "zclVersion": 3,                         "appVersion": 80,                         "stackVersion": 2,                         "hwVersion": 2,                         "dateCode": "20190430"                     }                 },                 "ssIasZone": {                     "attributes": {                         "iasCieAddr": "0x00124b001cd4df47",                         "zoneState": 1,                         "zoneStatus": 16                     }                 },                 "genPowerCfg": {                     "attributes": {                         "batteryVoltage": 41,                         "batteryPercentageRemaining": 199                     }                 },                 "ssIasWd": {                     "attributes": {                         "1": 50,                         "2": 50,                         "3": 0,                         "maxDuration": 240                     }                 }             },             "binds": [],             "configuredReportings": [],             "meta": {}         }     },     "appVersion": 80,     "stackVersion": 2,     "hwVersion": 2,     "dateCode": "20190430",     "zclVersion": 3,     "interviewCompleted": true,     "meta": {},     "lastSeen": 1682120463862 }

### Comments

siren alarm from tuya

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: 

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition  = {
    fingerprint: [{modelID: 'TS0219', manufacturerName: '_TYZB01_ynsiasng'}, {modelID: 'TS0219', manufacturerName: '_TYZB01_bwsijaty'},
        {modelID: 'TS0219', manufacturerName: '_TYZB01_rs7ff6o7'}, {modelID: 'TS0219', manufacturerName: '_TYZB01_ynsiasng'}],
    model: 'R7051',
    vendor: 'Woox',
    description: 'Smart siren',
    fromZigbee: [fz.battery, fz.ts0216_siren, fz.ias_alarm_only_alarm_1, fz.power_source],
    toZigbee: [tz.warning, tz.ts0216_volume, tz.ts0216_duration],
    exposes: [e.battery(), e.battery_voltage(), e.warning(), exposes.binary('alarm', ea.STATE, true, false),
        exposes.binary('ac_connected', ea.STATE, true, false).withDescription('Is the device plugged in'),
        exposes.numeric('volume', ea.ALL).withValueMin(0).withValueMax(100).withDescription('Volume of siren'),
        exposes.numeric('duration', ea.ALL).withValueMin(0).withValueMax(3600).withDescription('Duration of siren')],
    meta: {disableDefaultResponse: true},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.batteryVoltage(endpoint);
        await reporting.batteryPercentageRemaining(endpoint);
    },
};

module.exports = definition;
```

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed
