### ISSUE TITLE
[New device support]: Zigbee Model TS0202 Zigbee Manufacturer _TZ3040_bb6xaihh

### ISSUE THREAD

**Issue by fredqm** [Koenkk/zigbee2mqtt#17424]
### Link

https://www.aliexpress.com/item/1005005099780623.html?spm=a2g0o.order_list.order_list_main.78.71f7caa4ODwHtj&gatewayAdapt=glo2bra

### Database entry

{"id":22,"type":"EndDevice","ieeeAddr":"0xa4c13892b7f9a3ff","nwkAddr":52943,"manufId":4417,"manufName":"_TZ3040_bb6xaihh","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,4,1280,0],"outClusterList":[4,6,4096,25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0024c23a5d","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1682168862967,"defaultSendRequestWhen":"immediate"}

### Comments

I'm a noob. I Copied this external converter and it seems to work, but there is no battery voltage.

### External converter

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0202',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZ3040_bb6xaihh',
        },
    ],
    model: 'TS0202_1',
    vendor: 'TuYa',
    description: 'Motion sensor',
    // Requires alarm_1_with_timeout https://github.com/Koenkk/zigbee2mqtt/issues/2818#issuecomment-776119586
    fromZigbee: [fz.ias_occupancy_alarm_1_with_timeout, fz.battery, fz.ignore_basic_report],
    toZigbee: [],
    exposes: [e.occupancy(), e.battery_low(), e.linkquality(), e.battery(), e.battery_voltage()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint);
    },
};

module.exports = definition;

**Comment by Koenkk** [comment]
`_TZ3040_bb6xaihh` will be supported in the 1 May Zigbee2MQTT release.

**Comment by posreg** [comment]
mind me asking, this device has been paired successsfully, however TS0202_1 points to different picture / model than the linked product

[https://www.zigbee2mqtt.io/devices/TS0202_1.html](url)
versus
[https://www.aliexpress.com/item/1005005099780623.html?spm=a2g0o.order_list.order_list_main.78.71f7caa4ODwHtj&gatewayAdapt=glo2bra](url)

is this expected behaviour ?

thanks!

**Comment by Koenkk** [comment]
@posreg please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=wrong+device&projects=&template=wrong_device.yaml&title=%5BWrong+device%5D%3A+
