### ISSUE TITLE
Spammed Log Files from Occupancy Sensor

### ISSUE THREAD

**Issue by RodneyCapron** [Koenkk/zigbee2mqtt#17433]
### What happened?

I just installed this Occupancy Sensor through the Zigbee2MQTT Add-on. The log files are getting Spammed every few seconds with the following error:

_Logger: homeassistant.components.mqtt.select
Source: components/mqtt/select.py:152
Integration: MQTT (documentation, issues)
First occurred: 8:08:01 AM (127 occurrences)
Last logged: 8:14:31 AM

Invalid option for select.0xb4e3f9fffe47dc9a_tumble_switch: '1' (valid options: ['ON', 'OFF'])_

Below is a link to the Occupancy Sensor:

https://www.zigbee2mqtt.io/devices/MIR-HE200-TY.html#tuya-mir-he200-ty

I have not created any YAML entries or performed any configuration of any kind on the device.

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

20220219

### Adapter

Tube's CC2652P2 Based Zigbee to PoE Coordinator 2022 WL

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter:  https://gist.github.com/Koenkk/bb84c82e1297f0b965332fd6b2e30474

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed
