### ISSUE TITLE
Update cc2531 firmware?

### ISSUE THREAD

**Issue by robyevolution** [Koenkk/zigbee2mqtt#1743]
hi ,I can't find the .hex file of version 1.5.1, where can I find it?

**Comment by JLFN** [comment]
https://github.com/Koenkk/Z-Stack-firmware?files=1

**Comment by robyevolution** [comment]
I can't find the hex file

**Comment by dreimer1986** [comment]
Firmwares have dates as version string, you are citing the zigbee2mqtt version here.

**Comment by pcb1962** [comment]
Download the version you want from here:
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin
Unzip the downloaded file, you will see a bin and a hex file. The hex file is the one you want to flash to your cc253n
