### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by ironboy84** [Koenkk/zigbee2mqtt#17461]
### Link

https://heimgard.com/support/brukerveiledninger/vare-eldre-produkter/home-control-smart-plug-develco-zhwr202

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0x0015bc001d020a19","nwkAddr":28066,"manufId":4117,"manufName":"Develco Products A/S","powerSource":"Mains (single phase)","modelId":"ZigBee Wallplug HA SP2","epList":[33,1],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[2,3],"outClusterList":[1],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"33":{"profId":260,"epId":33,"devId":9,"inClusterList":[0,3,4,5,6,1794,9],"outClusterList":[10,1030],"clusters":{"genBasic":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}}},"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1672055188973,"defaultSendRequestWhen":"immediate"}

### Comments

I get it into HA but get error code: Unsupported

Please add support, i have 3 pieces that i cant use.

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/15758
