### ISSUE TITLE
Danfos Ally eTRV0103 firmware update, wrong image type

### ISSUE THREAD

**Issue by Masoholik** [Koenkk/zigbee2mqtt#17479]
### What happened?

I bought a new Danfos Ally eTRV0103 and the overview is showing the Firmware Version 00.20.0008 00.20 with 20230324 as date.

![image](https://user-images.githubusercontent.com/49479708/235001274-75795983-4d2c-4db6-8867-fe6432a293b8.png)

i would like to update to the 1.20 firmware, but OTA Update says "no image avaiable for image type 288"

> Update of 'Zigbee Küche Heizung' failed (No image available for imageType '288')
Error: No image available for imageType '288' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:113:15) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at getNewImage (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:420:18) at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:282:19) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:267:41)
Debug 2023-04-28 00:25:16Received Zigbee message from 'Zigbee Küche Heizung', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":20,"imageType":288,"manufacturerCode":4678}' from endpoint 1 with groupID 0 <

i saw here: https://github.com/Koenkk/zigbee-OTA/blob/master/index.json that there is already the new Firmware. But with image type 256?

When i use an local index.json file and change "imageType" to 288 and copy the ota file (https://www.danfoss.com/en/products/dhs/smart-heating/smart-heating/danfoss-ally/danfoss-ally-support/#tab-software)  to my server. then i get "image type mismatch".

Is there maybe a solution for this? And why is it showing me 00.20 as firmware version?

### What did you expect to happen?

do a firmware update

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20230410

### Adapter

Zigstar Olizig

**Comment by lux73** [comment]
not possbile -> the new Allys eTRV0103 got a new/different Microcontroller. There is actually no newer Firmware to Update

00.20 is the latest one - please search around the Forums

**Comment by Mikkooooo** [comment]
I‘ve installed a few Popp smart zigbee thermostats.
Trying a FW update also shows :  No image avaiable for image type 288.

How to update with success ?

Mikkooooo
