### ISSUE TITLE
Xiaomi FP1 sensor causing network instability

### ISSUE THREAD

**Issue by sygys** [Koenkk/zigbee2mqtt#17482]
### What happened?

A while back i posted problems with my big network. The problems i had were devices not responding over time. multiple hickups and lag daily. And i never understood what was causing the problems. The last few months the problem didnt occur anymore and i didnt relize what fixed it. Until a few days back i added the FP1 sensor from xiomi back in the network. Almost instantly devices started to show problems. Hue lights not responding anymore. sensors having tremendous delays and problems with the overall stability of the network. Finally after a long while i now found the problem and wanted to share this with you. I think the FP1 sensor wich is added as a router in z2m isnt really a fully functional router. It seems that every router or device that wants to route through the fp1 gets into trouble. These problems are so big that even Hue lights crash to an extend that they wont react to anything anymore until they are disconnected from the power.

I disconnected the fp1 from the network now and all is running rock solid again. There is seriously something wrong with this device or the config in z2mqtt for running this device. 

My guess is that it has something to do with its router role it gets in z2m.

### What did you expect to happen?

FP1 working as a router with other devices

### How to reproduce it (minimal and precise)

Connect a FP1 sensor from xiaomi in a large network (120+ devices)

### Zigbee2MQTT version

1.30.3-1

### Adapter firmware version

20220219

### Adapter

CC2652P2 tube zigbee ethernet

### Debug log

no debug log needed. its an internal zigbee network problem which is not shown in the debug log.

**Comment by lux73** [comment]
can't second this - in my Network (~50 Devices) my FP1 does not trigger any Network Instability

and you are not correct -> **the FP1 Sensor does not act as a Router**, it's only working as End Device. Pls check this in the z2m WebIf, the Sensor is marked as EndDevice under Device Type

don't know whats wrong with your config but from my side the FP1 is rock solid stable ^^
