### ISSUE TITLE
Z2M - AREQ - ZDO - activeEpRsp after 10000ms

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17499]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11360297/log.txt)
### What happened?

- It appears my sonoff coordinator decided to play up overnight. No idea why. it hasn't moved. 
- I have replugged it in and restarted Z2m numerous times
- It seems very slow when I click Join, it can take 10+ seconds actually to show the countdown, whereas yesterday it was instant. and even now as I write this, the countdown is stuck at 6 seconds??
- After restarting all the devices slowly connect, but there is now a huge delay when pressing an action for lights or sometimes nothing at all, ie my office lights are on, but the switch is off in Z2M.

Partial log

Zigbee2MQTT:error 2023-04-30 09:42:17: Exception while calling fromZigbee converter: Command 0x70ac08fffe916c19/1 manuSpecificTuya.mcuGatewayConnectionStatus({"payloadSize":1,"payload":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)}

### Zigbee2MQTT version

 1.30.3 commit: unknown

### Adapter firmware version

20221226

### Adapter

Sonoff Coordinator P

**Comment by cloudbr34k84** [comment]
@Koenkk mate need some help pls. This is the 2nd time within 2 weeks I'm having these issues. I went to bed last night, everything was perfect, woke up to like 80 devices offline and the coordinator I guess not working as well. I have never seen this error before - 0x70ac08fffe916c19/1 manuSpecificTuya.mcuGatewayConnectionStatus({"payloadSize":1,"payload":1. 
Ideas?

I'm starting to think the firmware has trouble with large networks still

**Comment by cloudbr34k84** [comment]
Update:
So i changed to channel 26 and started re-adding devices. Everything going great, but as soon as I hit around 70 devices I think , I start seeing the errors again. and now devices are going offline. Im at 82 devices with another 40 to go. 
and now my stick has decided to restart and now I'm getting an error Error: AREQ - ZDO - activeEpRsp after 10000ms
```
info  2023-04-30 12:55:12: Logging to console and directory: '/config/zigbee2mqtt/log/2023-04-30.12-55-12' filename: log.txt
info  2023-04-30 12:55:12: Starting Zigbee2MQTT version 1.30.3 (commit #unknown)
info  2023-04-30 12:55:12: Starting zigbee-herdsman (0.14.103)
error 2023-04-30 12:55:35: Error while starting zigbee-herdsman
error 2023-04-30 12:55:35: Failed to start zigbee
error 2023-04-30 12:55:35: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-04-30 12:55:35: Exiting...
error 2023-04-30 12:55:35: Error: AREQ - ZDO - activeEpRsp after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by Koenkk** [comment]
Could you try the `20230410` firmware? This might provide some stability improvements in your case: https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin

**Comment by cloudbr34k84** [comment]
> Could you try the `20230410` firmware? This might provide some stability improvements in your case: https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin

ill try now as its happened again. I have been chilling with my baby all morning and I decided to try and pair this device, and then all of a sudden I'm getting errors and devices just dropping off again.. Is there a better stick than the Sonoff P??

**Comment by cloudbr34k84** [comment]
> > Could you try the `20230410` firmware? This might provide some stability improvements in your case: https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin
> 
> ill try now as its happened again. I have been chilling with my baby all morning and I decided to try and pair this device, and then all of a sudden I'm getting errors and devices just dropping off again.. Is there a better stick than the Sonoff P??

So I'm trying to flash this and for some reason, it won't let work, but it will work for launchpad_coordinator_20221226.hex
```
>Initiate access to target: COM4 using 2-pin cJTAG.
>Reading file: C:/Users/cloud/Documents/Zigbee/firmware/CC1352P2_CC2652P_launchpad_coordinator_20230410.hex/CC1352P2_CC2652P_launchpad_coordinator_20230410.hex.
>Unknown record type: 3.
>Reset target ...
>Reset of target successful.
>Initiate access to target: COM4 using 2-pin cJTAG.
>No response from device. Device may not be in bootloader mode. Reset device and try again.
If problem persists, check connection and baud rate.
>Connecting over serial bootloader failed: No response from device. Device may not be in bootloader mode. Reset device and try again.
If problem persists, check connection and baud rate.
>Failed to create device object.
```

**Comment by cloudbr34k84** [comment]
@Koenkk i really don't know what is happening. None of the Sonoff sticks would flash so I had to resort to trying out my Zigstar POE adapter. I have been stuck on this issue" Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby"

How do I just start again??

**Comment by Koenkk** [comment]
what command are you using to flash? command should have `--bootloader-sonoff-usb`

**Comment by cloudbr34k84** [comment]
Im using Smart RF Flash Programmer 2.
How is it i can flash the previous hex file and not this one?

**Comment by cloudbr34k84** [comment]
closing this down to start a new issue.. defiantly something wrong with Z2m on larger networks
