### ISSUE TITLE
Lidl FB20-002 and Lidl HG08164 binding is not working

### ISSUE THREAD

**Issue by josephverburg** [Koenkk/zigbee2mqtt#17513]
### What happened?

I tried binding both buttons to my lamp.
z2m reports binding successful however it does not work.
The button presses are correctly reported in the log in z2m.

Binding using an group containing the lamp also does not work for the lidl buttons.

Binding to the same lamp using an ikea button does work. 

### What did you expect to happen?

The binding to work.

### How to reproduce it (minimal and precise)

- Pair on of the buttons with z2m (wait for the pairing to complete)
- Goto the "Bind" section of the button
- Select Source endpoint "1"
- Select Destination "Lamp"
- Select Destination endpoint "1"
- Select Clusters "LevelCtrl" and "OnOff"
- Press Bind
- Use a button
- Binding completed
- Use the correct button action to change the lamp state
- Nothing happens.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by MattWestb** [comment]
Some tuya remotes like the dimmer switch TS004F and rotating knob is not supporting binding of cluster that shall working with remotes for lights.
But they have putting one cluster for groups that is in like one light (its wrong it shall being out as one remote) and can being added to groups like one light.

In ZHA is working very well but only the last added group is being used to sending commands to lights.
