### ISSUE TITLE
[Wrong device]: NOUS A1Z recognized as TuYa TS011F_plug_1

### ISSUE THREAD

**Issue by LayerCakeMakes** [Koenkk/zigbee2mqtt#17528]
### Link

https://nous.technology/product/a1z-1.html

### Model

A1Z

### Description

Smart plug (with power monitoring)

### Vendor

NOUS

### Picture (link)

https://nous.technology/share/uploads/image/ShopProduct/202/A1Z-1_amazon.jpg

### Database entry

{"id":40,"type":"Router","ieeeAddr":"0xa4c138cc5461bc6c","nwkAddr":7009,"manufId":4417,"manufName":"_TZ3000_2putqrmw","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�GP+\u0003","65506":54,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_2putqrmw","powerSource":1,"zclVersion":3,"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":233,"rmsCurrent":0,"activePower":0}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,1]}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"powerOnBehavior":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0012013931","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0012013931","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0012013931","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10},{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-892627439},"lastSeen":1682982685675,"defaultSendRequestWhen":"immediate"}

### Notes

After seeing the note in the release notes I thought I should report this.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
