### ISSUE TITLE
Legrand 067776 wired shutter switch position issue

### ISSUE THREAD

**Issue by novisys** [Koenkk/zigbee2mqtt#17520]
### Is your feature request related to a problem? Please describe

Hi,
Since the last update of this product it’s support the position % and it’s work verry good with Control Application from LEGRAND NETATMO

### Describe the solution you'd like

Can we try to get it work with z2m and remove the 50% per default option ?

### Describe alternatives you've considered

remove the 50% per default option ?

### Additional context

![IMG_1856](https://user-images.githubusercontent.com/35895513/235482930-39d01a82-7c88-4311-9602-cf5a1e1f09f9.png)
![IMG_1855](https://user-images.githubusercontent.com/35895513/235482939-135c0f0a-7e9c-4406-962e-57b55fb25d95.png)
![IMG_1853](https://user-images.githubusercontent.com/35895513/235482943-5791ece2-3fb6-4809-9ace-0e6d29b85e2b.png)

**Comment by benjR** [comment]
great feature, what is the firmware version you have @novisys maybe it was updated ?
