### ISSUE TITLE
[Wrong device]: 

### ISSUE THREAD

**Issue by ClearlyDazed** [Koenkk/zigbee2mqtt#17526]
### Link

https://zigbee.blakadder.com/Tuya_ZMS01.html

### Model

TS0202    _TZ3000_otvn3lne

### Description

Motion sensor

### Vendor

TuYa

### Picture (link)

https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTMFoyD1f9-rWB3vbr3EgqZej-ZyVlhKmx7pyx-DiLQhT8gcSpx

### Database entry

{"id":23,"type":"EndDevice","ieeeAddr":"0xa4c1381a3e766502","nwkAddr":3719,"manufId":4417,"manufName":"_TZ3000_otvn3lne","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0202","manufacturerName":"_TZ3000_otvn3lne","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x00124b0026b878ba","zoneState":1,"currentZoneSensitivityLevel":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":22}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b878ba","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1475368908},"lastSeen":1682964145671,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
