### ISSUE TITLE
Impossible to use systemctl service

### ISSUE THREAD

**Issue by mitch55500** [Koenkk/zigbee2mqtt#1753]
Hi everyone, 

I've installed Jeedom with docker (I'm on a Synology). 
Everything works with zigbee2mqtt.

But I can't access to systemctl service. 
These lines are added

```
[Unit]
Description=zigbee2mqtt
After=network.target

[Service]
ExecStart=/usr/bin/npm start
WorkingDirectory=/opt/zigbee2mqtt
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target
```

When I verify with these commands "sudo systemctl start zigbee2mqtt" or "systemctl status zigbee2mqtt.service" I have this message : " Failed to connect to bus: No such file or directory".

What's my problem?

**Comment by JLFN** [comment]
Install portainer and you will manage. those commands are not for docker installation.

**Comment by mitch55500** [comment]
Thanks for your help. 
It's done. Now I can see Jeedom installed with docker.

Could you tell me more? How to manage?

**Comment by JLFN** [comment]
Ps basic usage you need to read docker manual. No step by step help here at this level.
