### ISSUE TITLE
[Wrong device]: TS0601

### ISSUE THREAD

**Issue by guandalf** [Koenkk/zigbee2mqtt#17538]
### Link

https://moeshouse.com/products/smart-programmable-valve?variant=39463174668369

### Model

ZTRV-ZX-TV01-MS

### Description

Smart Programmable Radiator Actuator Valve Tuya ZigBee3.0 Round Screen Thermostat Temperature Controller

### Vendor

MOES

### Picture (link)

https://moeshouse.com/cdn/shop/products/tuya-zigbee30-smart-programmable-thermostat-radiator-actuator-valve-temperature-controller-410631.png?v=1663750335

### Database entry

{"definition":{"description":"Thermostat radiator valve","model":"TV02-Zigbee","supports":"battery_low, lock (state), open_window, open_window_temperature, comfort_temperature, eco_temperature, climate (preset, local_temperature_calibration, local_temperature, current_heating_setpoint, system_mode), heating_stop, frost_protection, boost_timeset_countdown, holiday_temperature, holiday_start_stop, working_day, schedule, schedule_monday, schedule_tuesday, schedule_wednesday, schedule_thursday, schedule_friday, schedule_saturday, schedule_sunday, online, error_status, linkquality","vendor":"TuYa"},"friendlyName":"Salone strada","ieeeAddr":"0x5c0272fffebe3ea5","lastSeen":1683026981590,"manufacturerName":"_TZE200_7yoranx2","modelID":"TS0601","networkAddress":32930,"type":"EndDevice"}

**Comment by Koenkk** [comment]
Fixed! (will be included in next release)
