### ISSUE TITLE
[Wrong device]: Picture

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#17540]
### Link

https://de.aliexpress.com/item/1005005175597153.html?pdp_npi=2%40dis%21EUR%21%E2%82%AC%2046.12%21%E2%82%AC%2025.36%21%21%21%21%21%40211b612816830399453507565ec937%2112000031972701604%21btf&_t=pvid%3Ad76401e2-d607-4231-8f38-46c61c944c3c&afTraceInfo=1005005175597153__pc__pcBridgePPC__xxxxxx__1683039945&spm=a2g0o.ppclist.product.mainProduct&gatewayAdapt=glo2deu

### Model

TS0601

### Description

Human Presence Detector

### Vendor

Tuya

### Picture (link)

https://zigbee.blakadder.com/assets/images/devices/Tuya_ZY-M100-S.webp

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0x187a3efffe0f43eb","nwkAddr":39861,"manufId":4098,"manufName":"_TZE204_ztc6ggyl","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���+i","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_ztc6ggyl","powerSource":1,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1683037793298,"defaultSendRequestWhen":"immediate"}

### Notes

The bone has the wrong picture.

**Comment by Koenkk** [comment]
`TS0601` is the generic model number, please provide the model number listed on the device.

**Comment by salopette** [comment]
![sshot-1](https://user-images.githubusercontent.com/32480002/235752355-873a7567-92b9-4759-9ebe-729e057dadd3.jpg)

**Comment by Koenkk** [comment]
The zigbee Manufacturer name is not what I'm searching for. I'm looking for a model number that is written on the device itself.

**Comment by salopette** [comment]
![20230503_202608 (Mittel)](https://user-images.githubusercontent.com/32480002/236010633-74261e46-8e29-4cd2-86e5-757b1d494256.jpg)
![20230503_202613 (Mittel)](https://user-images.githubusercontent.com/32480002/236010637-8a7dbfbb-2a8b-4962-81d5-15fe7fe301d7.jpg)
![20230503_202600 (Mittel)](https://user-images.githubusercontent.com/32480002/236010638-817985ff-d4c8-4dba-95e2-e64bb2516a5f.jpg)

**Comment by Koenkk** [comment]
I see now that this has already been addressed in https://github.com/Koenkk/zigbee2mqtt/issues/17525, fix will be included in the next release.

**Comment by salopette** [comment]
Hello, on 1.6 with the update the right picture was there. now it is again a different picture than built-in version.
