### ISSUE TITLE
Develco SIRZB-110 mode and level mismatch

### ISSUE THREAD

**Issue by singloon** [Koenkk/zigbee2mqtt#17541]
### What happened?

Develco SIRZB-110 observed from 1.30.3 and 1.30.4-dev commit. 

The level and modes are not configuring the correct properties.

- It seems the level is configuring the mode.
-  And the modes is configuring the level (volume).

I haven't been able to figure out what else may not be mapped accordingly.

### What did you expect to happen?

When I set level and mode to be reflected

### How to reproduce it (minimal and precise)

Set the mode and level of device.
Trigger alarm.

### Zigbee2MQTT version

1.30.4-dev commit

### Adapter firmware version

20220219

### Adapter

slaesh's CC2652RB

**Comment by bonjour81** [comment]
Hello @singloon, did you solve the issue?

**Comment by singloon** [comment]
> Hello @singloon, did you solve the issue?

No solution
