### ISSUE TITLE
Crash due to connection to external IP (Strato AG???)

### ISSUE THREAD

**Issue by Chacsam** [Koenkk/zigbee2mqtt#17550]
### What happened?

Since +/- 48 hours, Zigbee2mqtt is randomly crashing on the following error:
```
Error: connect ECONNREFUSED 85.214.195.163:9005
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

**Note**: I only see this error in the _Docker container log_, not in the Zigbee2mqtt log. (attached)

Basically the container starts up correctly, connects to the mosquitto eclipse broker as it should, I even see the values being updated in my Home Assistant, but it crashes after 5 to 10 seconds with the above mentioned error.

Sometimes, it doesn't crash and stays stable, but a restart might get it in crashing mode again.

The lookup of that IP refers to some German Provider called Strato, which I have no contact with.
Does anyone know where it comes from? Zigbee2mqtt? One of my devices?

### What did you expect to happen?

Zigbee2mqtt to stay stable

### How to reproduce it (minimal and precise)

It looks random on start

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20221226

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11380244/log.txt)

**Comment by liakos356** [comment]
I have the same issue with Conbee 2 adapter

**Comment by albertgaes** [comment]
I have the same issue. Mine is pointing another port:

Error: connect ECONNREFUSED 85.214.195.163:9007
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

Sonoff Dongle 3.0

**Comment by Chacsam** [comment]
Surfing to that IP on normal http port is actually pretty surprising...

**Comment by Koenkk** [comment]
can someone provide the herdsman debug log of this?


See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by liakos356** [comment]
> Yes, the exact same IP and port. I'm suspecting that the culprit is my connection that is behind a pi-hole. When I return from work I'll check if there is a new rule that blocks the connection there.

Removed pi-hole filtering. No change. Problem persists.

**Comment by Chacsam** [comment]
> can someone provide the herdsman debug log of this?
> 
> See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

@Koenkk Is this what you are looking for?
[log.zip](https://github.com/Koenkk/zigbee2mqtt/files/11403721/log.zip)

**Comment by liakos356** [comment]
The content on this IP is like the personal file storage of some individual. Movies and series. What can possibly points to that?

**Comment by liakos356** [comment]
I think I've figured it out. In the `./zigbee2mqtt/extension` folder was an `example-user-extension1682976504061.js` file that was making the call to this questionable server. When I rename the file to .bak, everything came back to normal. 

I think that the file was created by me when I wanted to add support to a Chinese no name energy clamp meter. The server url was inside the file contents, and it might point to the personal server of the person that made the guide I've followed. Nevertheless, despite the fix, the clamp meter is still functional.

**Comment by albertgaes** [comment]
> I think I've figured it out. In the `./zigbee2mqtt/extension` folder was an `example-user-extension1682976504061.js` file that was making the call to this questionable server. When I rename the file to .bak, everything came back to normal.
> 
> I think that the file was created by me when I wanted to add support to a Chinese no name energy clamp meter. The server url was inside the file contents, and it might point to the personal server of the person that made the guide I've followed. Nevertheless, despite the fix, the clamp meter is still functional.

Great! I renamed that file and now is working. Thanks a lot.

**Comment by Chacsam** [comment]
> I think I've figured it out. In the `./zigbee2mqtt/extension` folder was an `example-user-extension1682976504061.js` file that was making the call to this questionable server. When I rename the file to .bak, everything came back to normal.
> 
> I think that the file was created by me when I wanted to add support to a Chinese no name energy clamp meter. The server url was inside the file contents, and it might point to the personal server of the person that made the guide I've followed. Nevertheless, despite the fix, the clamp meter is still functional.

That solved the issue for me as well. Thanks

**Comment by liakos356** [comment]
> One question though, @liakos356 , how would that test file created by you end up on my instance?

I can only guess that you might have followed the same guide that included the creation of the file, or that there were files included in that guide and you copied and paste them. Have you ever needed support for a Zigbee device that didn't recognized directly from the UI of the zigbee2mqtt?

**Comment by liakos356** [comment]
> Never, I only have paired devices through the UI (and I only have mainstream devices: Sonoff, Philips, Ikea & Lidl). Also checked my drive and that file was modified on May 2 at 2.01am, which matches the moment when Watchtower updated my Zigbee2mqtt to version 1.30.4...

So your initial suspicion that the update broke the functionality is correct. And when someone downgraded to previous version, the file was still present and broke the installation. The real mystery is the type of content of this ip.

**Comment by Chacsam** [comment]
> The real mystery is the type of content in this ip.

Fully agree. It's still a intriguing question.

**Comment by liakos356** [comment]
Follow up : 
The file seems to be created in the following menu of the UI :

![image](https://user-images.githubusercontent.com/7068274/236487533-312e54fb-3461-4e5a-9941-f1d7dea65681.png)

![image](https://user-images.githubusercontent.com/7068274/236487627-7a243727-0a9a-4e29-bf28-4297d1f2dde6.png)

**Comment by Koenkk** [comment]
Great that you found the issue, lesson learned: don't post random external extension from the internet 😄

**Comment by taimaiduc** [comment]
> I think I've figured it out. In the `./zigbee2mqtt/extension` folder was an `example-user-extension1682976504061.js` file that was making the call to this questionable server. When I rename the file to .bak, everything came back to normal.
> 
> I think that the file was created by me when I wanted to add support to a Chinese no name energy clamp meter. The server url was inside the file contents, and it might point to the personal server of the person that made the guide I've followed. Nevertheless, despite the fix, the clamp meter is still functional.

Thank you for saving my time
