### ISSUE TITLE
ZVG1 no water consumed 

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#17561]
### What happened?

water valve ZVG1 no report water consumed

### What did you expect to happen?

want to see how much water consumed

### How to reproduce it (minimal and precise)

buy this valve, plug in Yours instalation and HA and see that no water consumed 

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2.

### Debug log

{
    "battery": 50,
    "last_seen": "2023-05-04T09:28:35+02:00",
    "last_valve_open_duration": 0,
    "linkquality": 255,
    "state": "ON",
    "timer": 60,
    "timer_state": "enabled",
    "timer_time_left": 41,
    "weather_delay": "disabled",
    "cycle_timer_1": null,
    "cycle_timer_2": null,
    "cycle_timer_3": null,
    "cycle_timer_4": null,
    "normal_schedule_timer_1": null,
    "normal_schedule_timer_2": null,
    "normal_schedule_timer_3": null,
    "normal_schedule_timer_4": null,
    "water_consumed": null
}

**Comment by ScratMan** [comment]
The valve only reports the water consumed after irrigation ends. Please to open the valve and draw water and look for irrigation duration and water consumed after closing the valve.
