### ISSUE TITLE
Tuya Temperature and humidity sensor with clock device - Nous Model SZ-T04 - not updating settings

### ISSUE THREAD

**Issue by bumperboy** [Koenkk/zigbee2mqtt#17599]
### What happened?

I bought and added a Tuya Zigbee Temperature and humidity sensor with clock device to my Z2M instance and it is displayed the expected values:

![image](https://user-images.githubusercontent.com/2044970/236828626-05dca8ad-3d6c-488f-bf25-7f8115a1a501.png)

The problem is that, if I try to change some of the settings (see screenshot) the changes are not applied and the default values are displayed again

![image](https://user-images.githubusercontent.com/2044970/236828261-096f2dd6-b283-4098-ae4a-9a832bd54730.png)

### What did you expect to happen?

N/A

### How to reproduce it (minimal and precise)

N/A

### Zigbee2MQTT version

1.30.1-dev commit: fec7fca

### Adapter firmware version

7.2.0.0 build 108

### Adapter

Zigbee Model TS0601 Zigbee Manufacturer _TZE200_locansqn

### Debug log

Debug 2023-05-08 14:58:00Received MQTT message on 'zigbee2mqtt/Nous Temp Quarto Pais/set' with data '{"temperature_report_interval":5}'
Debug 2023-05-08 14:58:00Publishing 'set' 'temperature_report_interval' to 'Nous Temp Quarto Pais'
Debug 2023-05-08 14:58:01Received MQTT message on 'zigbee2mqtt/Nous Temp Quarto Pais/set' with data '{"humidity_report_interval":120}'
Debug 2023-05-08 14:58:01Publishing 'set' 'humidity_report_interval' to 'Nous Temp Quarto Pais'
Debug 2023-05-08 14:58:01Received MQTT message on 'zigbee2mqtt/Nous Temp Quarto Pais/set' with data '{"humidity_report_interval":10}'
Debug 2023-05-08 14:58:01Publishing 'set' 'humidity_report_interval' to 'Nous Temp Quarto Pais'
Debug 2023-05-08 15:01:02Received MQTT message on 'zigbee2mqtt/Nous Temp Quarto Pais/set' with data '{"temperature_report_interval":5}'
Debug 2023-05-08 15:01:02Publishing 'set' 'temperature_report_interval' to 'Nous Temp Quarto Pais'
Debug 2023-05-08 15:01:08Received MQTT message on 'zigbee2mqtt/Nous Temp Quarto Pais/set' with data '{"temperature_report_interval":5}'
Debug 2023-05-08 15:01:08Publishing 'set' 'temperature_report_interval' to 'Nous Temp Quarto Pais'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":9}],"seq":43008}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,1,134],"type":"Buffer"},"datatype":2,"dp":10}],"seq":43264}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,0],"type":"Buffer"},"datatype":2,"dp":11}],"seq":43520}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,60],"type":"Buffer"},"datatype":2,"dp":12}],"seq":43776}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,20],"type":"Buffer"},"datatype":2,"dp":13}],"seq":44032}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:58Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,120],"type":"Buffer"},"datatype":2,"dp":17}],"seq":44288}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:58MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,120],"type":"Buffer"},"datatype":2,"dp":18}],"seq":44544}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:59MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,6],"type":"Buffer"},"datatype":2,"dp":19}],"seq":44800}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:59MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,6],"type":"Buffer"},"datatype":2,"dp":20}],"seq":45056}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:59MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandMcuSyncTime', cluster 'manuSpecificTuya', data '{"payloadSize":177}' from endpoint 1 with groupID 0
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,201],"type":"Buffer"},"datatype":2,"dp":1}],"seq":45568}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:59MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":64,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:01:59Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,63],"type":"Buffer"},"datatype":2,"dp":2}],"seq":45824}' from endpoint 1 with groupID 0
Info 2023-05-08 15:01:59MQTT publish: topic 'zigbee2mqtt/Nous Temp Quarto Pais', payload '{"battery":18,"humidity":63,"humidity_alarm":"upper_alarm","humidity_report_interval":120,"humidity_sensitivity":6,"linkquality":196,"max_humidity":60,"max_temperature":39,"min_humidity":20,"min_temperature":0,"temperature":20.1,"temperature_alarm":null,"temperature_report_interval":120,"temperature_sensitivity":0.6,"temperature_unit_convert":"celsius"}'
Debug 2023-05-08 15:02:00Received Zigbee message from 'Nous Temp Quarto Pais', type 'commandMcuSyncTime', cluster 'manuSpecificTuya', data '{"payloadSize":181}' from endpoint 1 with groupID 0

**Comment by kam821** [comment]
Same issue, Tuya Temperature & Humidity Sensor identified as TS0601 / _TZE200_locansqn / Nous SZ-T04

**Comment by CaptInsano** [comment]
Just to add,

Same thing here. I cannot change any values:

Reporting Intervals, temp/humidity alarm values. 

Default values just remain. 

Device nought after recommendation here:

https://smarthomescene.com/reviews/zigbee-temperature-humidity-sensor-with-a-screen-sz-t04-review/

**Comment by CaptInsano** [comment]
Fix:

Press the button on the top of the device directly before changing settings in Zigbee2mqtt and the settings changes apply correctly.

Device must not accept settings changes when "asleep".

**Comment by nolashadow** [comment]
What about the time. Want to change from 24 to 12 hour. Can’t find a way to change it.

**Comment by eloo** [comment]
not stale

**Comment by alehuo** [comment]
> Fix:
> 
> Press the button on the top of the device directly before changing settings in Zigbee2mqtt and the settings changes apply correctly.
> 
> Device must not accept settings changes when "asleep".

Same issue with TuYa TH01Z. (Zigbee Model TS0601, Zigbee Manufacturer _TZE200_locansqn).

Pressing the top button and then changing the parameters work. This should be noted in the instructions page of the device: https://www.zigbee2mqtt.io/devices/TH01Z.html

**Comment by mager33** [comment]
How to set the clock?
