### ISSUE TITLE
[Wrong device]: LEDVANCE SMART+ Compact Outdoor Plug EU

### ISSUE THREAD

**Issue by GerdRuetten** [Koenkk/zigbee2mqtt#17609]
### Link

https://www.ledvance.de/consumer/produkte/smart-home/smart-komponenten/smart-zigbee/smart-komponenten-mit-zigbee-technologie-zur-anwendung-im-aussenbereich/smart-steckdosen-mit-zigbee-technologie/kompakte-smarte-aussensteckdose-uber-zigbee-technologie-steuerbar-c141283

### Model

SMART+ Compact Outdoor Plug EU

### Description

Plug

### Vendor

Ledvance

### Picture (link)

https://www.ledvance.de/00_Free_To_Use/12288492/image-thumb__12288492__product_detail/asset-12288492_smart_compact_outdoor_plug_eu.webp

### Database entry

{"id":39,"type":"Router","ieeeAddr":"0xf0d1b800001da993","nwkAddr":42538,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"Plug Value","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Plug Value","manufacturerName":"LEDVANCE","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"02056550"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c12675","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"02056550","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2081751853},"lastSeen":1682867431027,"defaultSendRequestWhen":"immediate"}

### Notes

Hi,

the LEDVANCE SMART+ Compact Outdoor Plug EU is described here:
https://www.zigbee2mqtt.io/devices/4058075729322.html

but it is pairing to this:
https://www.zigbee2mqtt.io/devices/AC26940_AC31266.html

But this are two diffent plugs.

You can it see here:

https://www.zigbee2mqtt.io/devices/4058075729308.html
and
https://www.zigbee2mqtt.io/devices/4058075729322.html

versus

https://www.zigbee2mqtt.io/devices/AC26940_AC31266.html

The last link/description is obsolet.

Please fix it

TIA

Best regards

Gerd

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
