### ISSUE TITLE
[Wrong device]: Incorrect Picture

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17610]
### Link

https://www.zemismart.com/products/zm85el-2z

### Model

ZM85EL-2z

### Description

Zemismart Tuya Zigbee Electric Curtain Robot Rechargeable Motor For Roman Rod I Type U Type Tracks Alexa Google Home Control

### Vendor

Zemismart

### Picture (link)

https://ueeshop.ly200-cdn.com/u_file/UPAC/UPAC387/2210/photo/1b73914871.jpg?x-oss-process=image/format,webp

### Database entry

EndDevice, TS0601, _TZE200_cf1sl3tj, 0x9035eafffe03d467,  0x15BA

**Comment by Koenkk** [comment]
please provide the model written on the device, not `_TZE200_cf1sl3tj` or `TS0601`

**Comment by cloudbr34k84** [comment]
> please provide the model written on the device, not `_TZE200_cf1sl3tj` or `TS0601`

Gotcha,  done

**Comment by Koenkk** [comment]
Thanks, will be fixed with the next release.
