### ISSUE TITLE
Wrong Picture - Temperature & humidity sensor with display

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17611]
### Link

https://www.google.com/aclk?sa=l&ai=DChcSEwiqyuGN3uf-AhW6mmYCHbcHCgQYABAPGgJzbQ&sig=AOD64_0QsB4LqaINPJalJN-RhWV6BGfqHw&adurl&ctype=70&ved=2ahUKEwiz7NeN3uf-AhUrDLcAHWMDDA0Qwg96BAgBEEg

### Model

TS0201

### Description

Tuya Zigbee 3.0 Temperature Humidity Sensor With Display

### Vendor

Tuya

### Picture (link)

https://www.google.com/aclk?sa=l&ai=DChcSEwimp9P_3uf-AhXTfCsKHce9C9sYABBOGgJzZg&sig=AOD64_2rqZX2OFGYAja6eVYMSn4skE6gpg&adurl&ctype=70&ved=2ahUKEwihmsj_3uf-AhXu6XMBHdlXAZsQp6wHegUIARD3Ag

### Database entry

Endpoint ;  _TZ3210_alxkwn0h ;  0xa4c13823789ccd64 ;  0x71E1

**Comment by cloudbr34k84** [comment]
No model number on device.

**Comment by Koenkk** [comment]
Ok, will be fixed with the next release.

**Comment by khayamgondal** [comment]
Error 2024-02-09 14:32:40Failed to configure '0xa4c138061b33d470', attempt 3 (Error: Read 0xa4c138061b33d470/1 hvacUserInterfaceCfg([16], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:22) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:13) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:84:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:141:25) at Configure.configure (/app/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
