### ISSUE TITLE
Cover AM43-0.45/40-ES-EB [_TZE200_zah67ekd] do not report state after HA restart

### ISSUE THREAD

**Issue by reaper7** [Koenkk/zigbee2mqtt#17621]
### What happened?

After upgrade z2m to 1.30.4 and after rebooting HA all my covers (working on AM43-0.45/40-ES-EB [_TZE200_zah67ekd]) do not report their state correctly. All show status unknown. I have to manually trigger the movement for the correct state to appear.

![cover_stat1](https://github.com/Koenkk/zigbee2mqtt/assets/4134851/e52b17aa-e681-4f1b-93a8-b293fbd96723)

![cover_stat2](https://github.com/Koenkk/zigbee2mqtt/assets/4134851/5c6befef-52ca-4dac-83b9-4ae906ca4a7d)

![cover_stat3](https://github.com/Koenkk/zigbee2mqtt/assets/4134851/1ac2902a-a3c8-49ae-9a84-965d3614aeb6)

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20221226

### Adapter

Electrolama

**Comment by cloudbr34k84** [comment]
I noticed this as well. Didn't think anything of it.

**Comment by efranulic** [comment]
I have the dame issue
