### ISSUE TITLE
[Wrong device]: TS0202_1 Tuya instead of Nous E2

### ISSUE THREAD

**Issue by posreg** [Koenkk/zigbee2mqtt#17626]
### Link

https://noussmart.pl/product/e2.html

### Model

E2

### Description

Motion Sensor

### Vendor

Nous

### Picture (link)

https://www.lesalexiens.fr/wp-content/uploads/2022/07/unboxing-nous-e2-pir-motion-sensor-zigbee-amazon-alexa-google-assistant.jpg

### Database entry

{"id":11,"type":"EndDevice","ieeeAddr":"0xa4c138065ab3c24e","nwkAddr":63237,"manufId":4417,"manufName":"_TZ3000_h4wnrtck","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0202","manufacturerName":"_TZ3000_h4wnrtck","powerSource":3,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0014da4b33","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0014da4b33","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1475368908},"lastSeen":1683700992586,"defaultSendRequestWhen":"immediate"}

### Notes

I was not able to find any Issue / Thread for covering this, however this sensor is already on the market for more than year now

![image](https://github.com/Koenkk/zigbee2mqtt/assets/80816020/82c279b6-2ffa-4a9c-a20a-b8774f5fbcfd)

**Comment by Koenkk** [comment]
thanks, will be fixed with the next release.
