### ISSUE TITLE
Innr FL 120C power_on_behavior UNSUPPORTED_ATTRIBUTE

### ISSUE THREAD

**Issue by Lucky2511** [Koenkk/zigbee2mqtt#17624]
### What happened?

Power_on_behavoir is exposed on the device, but unable to set it.

### What did you expect to happen?

Set this visible option

### How to reproduce it (minimal and precise)

Try to set the power_on_behaviour

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus V2

### Debug log

Publish 'get' 'power_on_behavior' to 'Sideboard Küche' failed: 'Error: Read 0x00158d00050336bc/1 genOnOff(["startUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by Koenkk** [comment]
Device doesn't seem to support it, disabled it.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
