### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17639]
### Link

https://a.aliexpress.com/_mOanxNe

### Model

SM-O301-AZ

### Description

AU 4 Plug 10A Power Board + USB

### Vendor

Tuya

### Picture (link)

https://www.google.com/imgres?imgurl=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FH1ded5755178c4b2b8028a9848ed38924f%2FUseeLink-Smart-Power-Strip-Au-Zigbee-Power-Bar-Multiple-Outlet-Extension-Cord-with-4USB-and-4.jpg_640x640.jpg&tbnid=IgbBVtwL8N7OhM&vet=1&imgrefurl=https%3A%2F%2Fwww.aliexpress.com%2Fi%2F4000504463608.html&docid=9D0Pn7QoR8sJQM&w=640&h=640&hl=en-AU&source=sh%2Fx%2Fim

### Database entry

{"id":4,"type":"Router","ieeeAddr":"0x5c0272fffe03cc99","nwkAddr":5430,"manufId":4098,"manufName":"_TZ3000_o005nuxx","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,3,4,5,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_o005nuxx","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00256cd420","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00256cd420","endpointID":1}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00256cd420","endpointID":1}],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00256cd420","endpointID":1}],"configuredReportings":[],"meta":{}},"5":{"profId":260,"epId":5,"devId":266,"inClusterList":[3,4,5,6,57344,57345],"outClusterList":[],"clusters":{},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00256cd420","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1684376784560,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Please post the `data/database.db` entry of this device

**Comment by cloudbr34k84** [comment]
Same comment as before,  my database file does not have the entries?

**Comment by cloudbr34k84** [comment]
Here is the device about page
![Screenshot_20230514-052658](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/74dd5482-ab91-4d24-8430-a0145139de52)

**Comment by Koenkk** [comment]
@nikosillo  you added `_TZ3000_o005nuxx` in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1882, can you confirm your `_TZ3000_o005nuxx` carries model number `SM-SO306EZ-10`?

**Comment by cloudbr34k84** [comment]
I have updated the information with my Database.db file info.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by cloudbr34k84** [comment]
@Koenkk the image doesn't match what i supplied
![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/05529b08-ebde-480b-b790-906012e1e957)

**Comment by Koenkk** [comment]
Added the picture!
