### ISSUE TITLE
Wrong Information

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17635]
### Link

https://a.aliexpress.com/_mKKor2C

### Model

XSH01B

### Description

2 Gang Switch Module - PM

### Vendor

Tuya

### Picture (link)

https://www.google.com/imgres?imgurl=https%3A%2F%2Fae01.alicdn.com%2Fkf%2FS57a90a3c578d4bd99cf7f601fdeaf723e%2F2-Gang-Electricity-Energy-Monitor-Tuya-Zigbee-Smart-Light-Switch-Module-Relay-Wireless-Home-Auto-Alexa.jpg&tbnid=i2_lSqBhg95MmM&vet=1&imgrefurl=https%3A%2F%2Fwww.aliexpress.com%2Fitem%2F1005002605426836.html&docid=cyuh4doC4eHoKM&w=800&h=800&hl=en-AU&source=sh%2Fx%2Fim

### Database entry

Router,  0xa4c1389a34414fb0, _TZ3000_irrmjcgi,  0x9354

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
