### ISSUE TITLE
[Wrong picture]: TS0601 (_TZE200_ztc6ggyl & _TZE204_ztc6ggyl) without device picture

### ISSUE THREAD

**Issue by SAOPP** [Koenkk/zigbee2mqtt#17642]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_smart_human_presence_sensor.html

### Model

TS0601_smart_human_presence_sensor

### Description

Smart Human presence sensor

### Vendor

TuYa

### Picture (link)

https://ae01.alicdn.com/kf/S03606ad5345441988b4a187ff2dbdbabH.jpg

### Database entry

-

### Notes

Hi!

In current dev builds of Z2M the Tuya presence sensor is not have device picture:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/29d3c742-2132-4246-8ea6-cc2101ffa48a)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/a3a857f5-38e6-49b4-a37a-6394ae608ef2)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/d67e8f9d-1994-4480-a9c3-60b3fdfbcc8a)

In previous builds, the picture was present.

**Comment by SAOPP** [comment]
Build: 1.30.4-dev commit: [307e0dc](https://github.com/Koenkk/zigbee2mqtt/commit/307e0dc)

**Comment by Koenkk** [comment]
Fixed (check again in 1 hour from now)

**Comment by SAOPP** [comment]
@Koenkk I just updated to 1.30.4-dev commit: [3085608](https://github.com/Koenkk/zigbee2mqtt/commit/3085608), not sure if it's correct build commits right now, 'coz I didn't found in commits any affilated to my questions strings (maybe I had wrong searching), but here is the consol of the dashboard:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/844df68b-0c2e-40c3-a1fc-6743ddceb2dc)

Here is broken links for me:
```
https://slsys.github.io/Gateway/devices/png/TS0601.png
https://www.zigbee2mqtt.io/images/devices/TS0601_smart_human_presence_sensor_1.jpg
```

Perhaps I was a little hasty?

**Comment by Koenkk** [comment]
I used the wrong file name, should be fixed now.

**Comment by SAOPP** [comment]
Thanks homie! I will check it tomorrow and give feedback. :+1:

**Comment by SAOPP** [comment]
@Koenkk nope :| I don't know what to say, maybe it's my local issue, but? Some of my homies had check it, and do not have the problem with that pictures, but these links above, is not working for they too.

**Comment by Koenkk** [comment]
@SAOPP maybe some browser cache?

**Comment by SAOPP** [comment]
@Koenkk of course I tried another browser and hard reset z2m page, dunno what it is :-|

**Comment by SAOPP** [comment]
Ooops, just check it. :-)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/dc700664-48c4-4c88-bbc6-e3291dfd9133)

**Comment by SAOPP** [comment]
But, need to this:

https://ae01.alicdn.com/kf/S03606ad5345441988b4a187ff2dbdbabH.jpg

**Comment by Koenkk** [comment]
Updated the picture.

**Comment by SAOPP** [comment]
Thanks homie! Issue has been resolved. :fire:

**Comment by SAOPP** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/5647009/7e9bdbc4-8e68-4829-9a78-81fe726f9997)
