### ISSUE TITLE
LEDVANCE 4058075729322: Invalid option „power_on_behavior“

### ISSUE THREAD

**Issue by GerdRuetten** [Koenkk/zigbee2mqtt#17645]
### What happened?

I get this errors in my HA-Log:

```
Logger: homeassistant.components.mqtt.select
Source: components/mqtt/select.py:152
Integration: MQTT (documentation, issues)
First occurred: 14:10:45 (84 occurrences)
Last logged: 17:25:58

Invalid option for select.steckdose_vorgarten_rechts_power_on_behavior: '' (valid options: ['off', 'on', 'toggle', 'previous'])
Invalid option for select.steckdose_vorgarten_links_power_on_behavior: '' (valid options: ['off', 'on', 'toggle', 'previous'])
```

### What did you expect to happen?

No option for power on behavior for this device

### How to reproduce it (minimal and precise)

use this device

### Zigbee2MQTT version

1.30.4-dev commit: 307e0dc

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus,TI CC2652P + CP2102(N)

**Comment by GerdRuetten** [comment]
@Koenkk Dear Koen,

do you need mor informations to fix this error?

Best regards

Gerd

**Comment by suaveolent** [comment]
Can confirm, having the same issue:


`Publish 'set' 'power_on_behavior' to 'Plug' failed: 'Error: Write 0xf0d1b8be2408aae9/1 genOnOff({"startUpOnOff":255}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

**Comment by jesperlowe** [comment]
Device is shown as not supportet.

Zigbee2MQTT version: [1.32.1]
Koordinator type: zStack3x0
Koordinator revision: 20210708
