### ISSUE TITLE
[New device support]: Switch TS0001 no power monitor for _TZ3000_kqvb5akv

### ISSUE THREAD

**Issue by stephdust** [Koenkk/zigbee2mqtt#17657]
### Link

https://www.aliexpress.com/item/1005004229044334.html?spm=a2g0o.order_list.order_list_main.59.59d15e5bHRU8LB&gatewayAdapt=glo2fra

### Database entry

{"id":47,"type":"Router","ieeeAddr":"0xxxxxxxx","nwkAddr":20319,"manufId":4417,"manufName":"_TZ3000_kqvb5akv","powerSource"

### Comments

Hi everyone
I recently received from ali (see the link upper)  a tuya zigbee switch module supposed to monitor the power
but in version 1.30.4 , it's detected as TS0001 with no power monitoring
The zigbee manufacturer is : _TZ3000_kqvb5akv

I added the ID  _TZ3000_kqvb5akv in node_modules/zigbee-herdsman-converters/devices/tuya.js
and it seems to work fine now
![image](https://github.com/Koenkk/zigbee2mqtt/assets/121352566/588a8108-b232-4299-9935-af306bb75822)

I see now power, current with more or less correct values.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/121352566/8439bf7b-242d-41cb-bfc4-0e9c68fd4733)

anyone having this module with no power monitoring  ?

**Comment by Koenkk** [comment]
Integrated the fix, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by JonasKruse1** [comment]
Hi when will the changes be available in the main version? I just received 3 of these too and have no power monitoring

**Comment by stefanmd023** [comment]
Is this still not on mainline? My _TZ3000_kqvb5akv TS0001_power is still being detected as TS0001 with no power. Voltage is being read but not power, current, etc

Does anyone have an external converter for it please?

**Comment by BinaryBrain86** [comment]
I've got the same issue just with  _TZ3000_xkap8wtb TS0001_power. For me it's energy what's read, but also wrong. It's counting to fast. But no actual power, current or voltage.
