### ISSUE TITLE
zigbee2mqtt 1.5.1.1 will not start in Home Assistant

### ISSUE THREAD

**Issue by SpuriousGer** [Koenkk/zigbee2mqtt#1765]
# Bug Report
## What happened

When I updated the add-on to 1.5.1.1 the add-on stopped working and when I click Start, it no longer starts. The logging output in the UI is non-existent.

## What did you expect to happen

The plugin to start, like it usually does.

## How to reproduce it (minimal and precise)

Update to 1.5.1.1 and see what happens. My add-on config has no security settings, but has the network key.
The connection with Home Assistant and the plugin did not work yesterday either. Although the logs showed outputs from the Zigbee devices.

## Debug Info
zigbee2mqtt version: 1.5.1.1

**Comment by Koenkk** [comment]
Please create this issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
