### ISSUE TITLE
Devices keep joining the network (with "Permit join" off)

### ISSUE THREAD

**Issue by hellcry37** [Koenkk/zigbee2mqtt#17656]
### What happened?

Firstly i have this device in my network ( TuYa TS0215A_remote ), all works ok without any issues except i see in the logs something like this fom time to time:

```txt
info  2023-05-11 09:42:50: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 10:03:02: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 10:16:19: Accepting joining not in blocklist device '0x0017880109167f24'
info  2023-05-11 10:16:20: Accepting joining not in blocklist device '0x0017880109167f24'
info  2023-05-11 10:23:15: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 10:43:27: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 11:03:40: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 11:23:52: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 11:44:05: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 12:04:18: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 12:24:30: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 12:44:43: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 13:04:55: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 13:25:08: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 13:45:20: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 14:05:33: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 14:25:46: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 14:45:58: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 15:06:11: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 15:26:24: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 15:46:36: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 16:06:49: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 16:27:02: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 16:27:02: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 16:47:14: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 17:07:26: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 17:27:39: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 17:47:52: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 18:08:04: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 18:28:17: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 18:48:30: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 19:08:42: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 19:28:55: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 19:49:07: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 20:09:20: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 20:29:32: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 20:49:45: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 21:09:58: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 21:30:10: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 21:50:23: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 22:10:36: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 22:30:48: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 22:51:01: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
info  2023-05-11 23:11:14: Accepting joining not in blocklist device '0xbc33acfffe26e4a7'
```
where "0xbc33acfffe26e4a7" is https://www.zigbee2mqtt.io/devices/TS0215A_remote.html#tuya-ts0215a_remote
and "0x0017880109167f24" is https://www.zigbee2mqtt.io/devices/9290012607.html#philips-9290012607

For the remote as you can see the issue is happening all the time. I am not doing anything, just the device is joining the network all the time.

For "Hue motion sensor" is a hole other issue, even if I decide to remove one of the sensors from the network, they will come back again without permit join enabled.

### What did you expect to happen?

Permit join to work as expected for all devices.

### Zigbee2MQTT version

1.30.4 commit: b2dd21e but the issues have a long time (older versions)

### Adapter firmware version

20220219

### Adapter

Electrolama ZZH

**Comment by Koenkk** [comment]
In Zigbee, what permit joining does is enabling the coordinator to send the link key (required to join the network) to devices. In case you set permit join to false but the device still has the link key from an earlier pairing they can keep joining the network. Factory resetting these devices should fix it (as that will make the device forget the link key).

**Comment by hellcry37** [comment]
For "0x0017880109167f24" is https://www.zigbee2mqtt.io/devices/9290012607.html#philips-9290012607 I know as a fact that if u want to push it out you wont succeed, it is gonna exit and rejoin the network right after regardless on what the state of permit join is. From what you say that mean if i ever want to remove a Philips Hue motion sensor the only chance is to reset the device and then force remove it. (according to what you said it should not rejoin)

**For "0xbc33acfffe26e4a7" is https://www.zigbee2mqtt.io/devices/TS0215A_remote.html#tuya-ts0215a_remote what can be done? what can I do to stop it for doing that join?**

**Comment by Koenkk** [comment]
I don't know the TS0215A_remote in detail but if factory resetting doesn't help, you can probably make the device forget the link key by pairing it to a different network.

**Comment by hellcry37** [comment]
I don't want TS0215A_remote out, the only problem is that this device keep joining when it should be joined and stable.

**Comment by Koenkk** [comment]
@hellcry37 this is normal behaviour in Zigbee: https://www.digi.com/resources/documentation/Digidocs/90002002/Concepts/c_zb_rejoining.htm?TocPath=Manage%20End%20Devices%7C_____11

**Comment by hellcry37** [comment]
Okay make sense now, so my problem is the remote keeps dropping of network, I'll investigate this. @Koenkk thank you for your time, for your great work and for all that you teach me.

I consider this matter closed, thanks again.
