### ISSUE TITLE
ZB-SW01 supported but "power_on_behavior"returns "Status 'UNSUPPORTED_ATTRIBUTE' "

### ISSUE THREAD

**Issue by gargamelonly** [Koenkk/zigbee2mqtt#17669]
### What happened?

trying to change an exposed attribute "power_on_behavior" get an error.
see log:
`Publish 'set' 'power_on_behavior' to 'SmartSwitch' failed: 'Error: Write 0x00124b0023ad4412/1 genOnOff({"startUpOnOff":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

### What did you expect to happen?

Expected parameter update

### How to reproduce it (minimal and precise)

Go to exposed attributes and select power_on_behavior setting to some value.

### Zigbee2MQTT version

1.30.4 commit: daedc54d

### Adapter firmware version

20210120

### Adapter

zzh!

**Comment by Koenkk** [comment]
Device doesn't seem to support this, disabled it.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
