### ISSUE TITLE
TuYa TS0601 soil not showing in domoticz

### ISSUE THREAD

**Issue by stack0423** [Koenkk/zigbee2mqtt#17667]
### What happened?

My TuYa TS0601 is showing good in zigbee2mqqt,but the soil is not showing in domoticz. (see screenshot)
Domoticz
![domoticz](https://github.com/Koenkk/zigbee2mqtt/assets/84093737/3873374d-2988-4ca4-bb0e-981c6bcc5790)
zigbee2mqqt
![zigbee2mqqt](https://github.com/Koenkk/zigbee2mqtt/assets/84093737/03784045-26a8-43e4-b7b9-84da6add51f9)

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

**Comment by mattaipm** [comment]
I have a similar problem.

z2m sees correctly - domoticz doesn't
