### ISSUE TITLE
Unable to save config in hassio

### ISSUE THREAD

**Issue by dschierman** [Koenkk/zigbee2mqtt#1766]
# Bug Report
## What happened
Following fresh install of 1.5.1.1 I am unable to save changes to config in hassio add-on window. I get a red text warning "not a valid value for dictionary value @ data['options']. Got {'data_path': ..." which lists all items in config. Unable to save or start. This happens even without making any changes to config.
## What did you expect to happen
Be able to save config changes
## How to reproduce it (minimal and precise)
Uninstalled previous version due to problems with recent upgrade. Installed latest version via Hassio add-on 
## Debug Info
zigbee2mqtt version: 1.5.1.1
CC253X firmware version:

**Comment by Koenkk** [comment]
Please create this issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
