### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by Trevor46** [Koenkk/zigbee2mqtt#17673]
### Link

https://www.zshinehome.com/en-ca/products/zshine-motorized-blackout-window-blinds-remote-control-wireless

### Database entry

0x282c02bfffec0458

### Comments

Hi I have no idea what I'm doing to try to add a new device.  My wife ordered 3 of these zstar roller blind motors.  I can get it paired to the zigbee2mqtt network but it says unsupported.  Can Anyone please help me? I have no idea what to do or how to do it.  My wife loves these blinds and wants to order more. The blind motor says zstar model zm25-eaz.

**Comment by chadtheriault** [comment]
Did you ever get any resolution to this?  I just purchased about 12 blinds with the same ZM25-EAZ motor.  They are detected by ZHA as "manufacturer": "coolkit", "model": "CK-MG22-JLDJ-01(7015)", and in ZHA all buttons and functions work.  However in Z2mqtt they are detected as generic and I cannot figure out how to get the HA front end up, down and stop buttons to work.
