### ISSUE TITLE
[Wrong device]: Tyua instead of Meian

### ISSUE THREAD

**Issue by HittyStorm** [Koenkk/zigbee2mqtt#17679]
### Link

http://meiangroup.com/index.php?r=default/column/index&col=sensor

### Model

SW02

### Description

Water leak sensor

### Vendor

Meian

### Picture (link)

https://zigbee.blakadder.com/Meian_SW02-ZB.html

### Database entry

{"id":13,"type":"EndDevice","ieeeAddr":"0xa4c138b380cdc2a2","nwkAddr":35784,"manufId":4417,"manufName":"_TZ3000_kyb656no","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0207","manufacturerName":"_TZ3000_kyb656no","powerSource":3,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b00060fd6da","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00060fd6da","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":491743244},"lastSeen":1684065805846,"defaultSendRequestWhen":"immediate"}

### Notes

Sensor detects as TuYa with wire, but actually it's Meian SW02 without wire.
Here is a product on Ali:

https://aliexpress.ru/item/1005004765568642.html?sku_id=12000030389476141
Or
https://aliexpress.ru/item/1005004662495000.html?sku_id=12000030023257949

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
