### ISSUE TITLE
I have problems unpairing my devices from zigbee2mqtt. I want to remove a device (Xiaomi humidity sensor) from my zigbee2mqtt. I have domoticz installed with zigbee2mqtt. I do not have node-red. Can someone give me a simple clue on how to do this. I have searched all over this place, but could not find the right tool.

### ISSUE THREAD

**Issue by Rudi1952** [Koenkk/zigbee2mqtt#1767]
# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by ondoteam** [comment]
If you are on Windows you can use MQTT Explorer and the topic zigbee2mqtt/bridge/config/remove with your "device ID" as raw payload. You can read more at https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

Next time, please, as this is not an issue nor a bug but a question you should use discord. Have a good day!
