### ISSUE TITLE
[New device support]:  TS0601 _TZE200_mby4kbtq Gas Sensor

### ISSUE THREAD

**Issue by b2un0** [Koenkk/zigbee2mqtt#17684]
### Link

https://www.aliexpress.com/item/1005004283975462.html

### Database entry

no info

### Comments

Datapoins are sniffed from the iot dev console as described here
https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html

als tried datapoint `13` from here
https://gist.github.com/Koenkk/86ea747a683752fd6ff9390abf9fda55?permalink_comment_id=4387907#gistcomment-4387907
and it also works and the alarm goes on 🎉 

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: tuya.fingerprint('TS0601', ['_TZE200_mby4kbtq']),
        model: 'TS0601_gas_sensor_3',
        vendor: 'TuYa',
        description: 'Gas sensor',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        configure: tuya.configureMagicPacket,
        exposes: [
            e.gas(),
             tuya.exposes.gasValue().withUnit('LEL'), 
             exposes.binary('preheat', ea.STATE, true, false), 
             tuya.exposes.faultAlarm(),
             exposes.binary('alarm_switch', ea.STATE_SET, true, false),
             tuya.exposes.silence()
        ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
                [1, 'gas', tuya.valueConverter.trueFalse0],
                [2, 'gas_value', tuya.valueConverter.divideBy10],
                [10, 'preheat', tuya.valueConverter.raw],
                [11, 'fault_alarm', tuya.valueConverter.trueFalse1],
                [13, 'alarm_switch', tuya.valueConverter.raw],
                [16, 'silence', tuya.valueConverter.raw],
        ],
    },
};

module.exports = definition;
```

**Comment by b2un0** [comment]
the `self_test` DP `8` and `9` does not have any effect on this device.

im not sure if we can merge `mby4kbtq` into the first one?

https://www.zigbee2mqtt.io/devices/TS0601_gas_sensor_1.html

**Comment by b2un0** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/2155498/59203b77-4ee9-4bcb-b1d2-5a49f6f70879)

**Comment by b2un0** [comment]
@Koenkk  not stale.

**Comment by DemotivatorAndy** [comment]
After the next zigbee2mqtt update, the converter proposed above stopped working. After making a few changes in accordance with the recommendations of zigbee2mqtt, Dutchis was again detected as supported and works perfectly.
/const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const modernExtend = require('zigbee-herdsman-converters/lib/modernExtend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_mby4kbtq',
        },
    ],
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE200_mby4kbtq',
    description: 'Gas sensor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime, 
    configure: tuya.configureMagicPacket,
    exposes: [
        e.gas(),
        tuya.exposes.gasValue().withUnit('LEL'), 
        exposes.binary('preheat', ea.STATE, true, false), 
        tuya.exposes.faultAlarm(),
        exposes.binary('alarm_switch', ea.STATE_SET, true, false),
        tuya.exposes.silence()
    ],
    meta: {
        tuyaDatapoints: [
                [1, 'gas', tuya.valueConverter.trueFalse0],
                [2, 'gas_value', tuya.valueConverter.divideBy10],
                [10, 'preheat', tuya.valueConverter.raw],
                [11, 'fault_alarm', tuya.valueConverter.trueFalse1],
                [13, 'alarm_switch', tuya.valueConverter.raw],
                [16, 'silence', tuya.valueConverter.raw],
        ],
    },
};

module.exports = definition;

**Comment by Koenkk** [comment]
@DemotivatorAndy could you make a pull request to add support for this device by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/tuya.ts)?
