### ISSUE TITLE
Setup is not creating a database.db file

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17695]
### What happened?

Im starting again as i had numerous issues that nothing was solving. However, I have noticed that my zigbee addon is not generating a database.db file. 

### What did you expect to happen?

database.db file to be created

### Zigbee2MQTT version

Zigbee2MQTT Edge

### Adapter firmware version

zStack3x0

### Adapter

Zigbee ESP32GW (Zigstar)

**Comment by lux73** [comment]
check user permission folder - your user that is running z2m must have write access

**Comment by cloudbr34k84** [comment]
> check user permission folder - your user that is running z2m must have write access

How do I check that?

**Comment by cloudbr34k84** [comment]
> basic Linux knowledge
> 
> https://linuxize.com/post/understanding-linux-file-permissions/

finally found, VSS had hidden the file somehow
