### ISSUE TITLE
TuYa TS011F_plug_1, Zigbee2MQTT, the power gets stuck

### ISSUE THREAD

**Issue by sved-SI** [Koenkk/zigbee2mqtt#17690]
### What happened?

Tuya smart power, the power gets stuck. I try delete plug and repair.
After first run with heater, plug show correct power and current, after turn off heater, power and current still show same value ( 1150W )
I try smart socket with tuya zigbee hub and work all normal.

![Screenshot 2023-05-15 182125](https://github.com/Koenkk/zigbee2mqtt/assets/43907857/3d468134-eff4-403e-9621-4bb766588161)

### What did you expect to happen?

show correct power and current

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

20210708

### Adapter

Sonoff dongle-P

**Comment by EvgeneF** [comment]
I have exactly the same. Make tests 4 times, problem in last version z2m.

**Comment by jabadabadu** [comment]
I am getting also the same problem with the _TZ3000_gvn91tmx (bought as Aubess 20 Amps). However _TZ3000_hdopuwv6 I have also is not affected with this problem. Using now Z2M version: 1.30.4-1, previously everything was correct.
@sved-SI as you can see under #16709 comment https://github.com/Koenkk/zigbee2mqtt/issues/16709#issuecomment-1512369226 the discussion is in progress.

**Comment by c0mplex1** [comment]
I also have exactly the same problem with 2 of my TS011_plug_1 smart plugs running with Zigbee2mqtt version 1.30.4-1
( _TZ3000_gznh2xla and _TZ3000_gvn91tmx )
The issue started after another fix...
https://github.com/Koenkk/zigbee2mqtt/issues/16709#issuecomment-1512369226

**Comment by EvgeneF** [comment]
> 

Will try on weekend

**Comment by unnaDmed** [comment]
> Looks like a duplicate of #16709, please try with the latest dev branch. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Tried it a few minutes ago and can confirm that it's working like a charm.

Thank you very much!

**Comment by Alexofhiswalnut** [comment]
Hi,
When will there be a stable update available to fix this issue?
@Koenkk

**Comment by Koenkk** [comment]
@Alexofhiswalnut issue will be fixed in the next release on 1 June.

**Comment by rablatbenjamin** [comment]
Hi. Power, current and energy meters doesn't work anymore
