### ISSUE TITLE
OTA updates fail and get stuck at 0% even after a reboot

### ISSUE THREAD

**Issue by benflux** [Koenkk/zigbee2mqtt#17705]
### What happened?

I updated firmware on Hue bulbs and it got stuck at 0% and now I can't update the firmware:

<img width="1424" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/31230445/c08bfd73-76ce-4647-8b72-ceeda47c5e3c">

### What did you expect to happen?

The firmware process would progress from 0% to 100% and complete

### How to reproduce it (minimal and precise)

Update several  devices at once

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20220219

### Adapter

Electrolama zzh!

**Comment by benflux** [comment]
this could have occurred whilst there was wifi interference with the Zigbee channel, I've subsequently fixed that but still can't update these devices stuck in this status

**Comment by lux73** [comment]
in my opinion you should not update more than one Device at time...

as i remember correctly there will be Files to manually delete if the update gets stuck - don't know which Thread i have seen this.

pls search around the forums

**Comment by benflux** [comment]
I was able to get around this issue by starting the install from the Home Assistant notification telling me that an update was available but I think it is still an issue to be solved so that other users don’t get themselves stuck like I was
