### ISSUE TITLE
Bosch Thermostat 2 (BTH-RA) does not report Battery %, but only battery low

### ISSUE THREAD

**Issue by Taraman17** [Koenkk/zigbee2mqtt#17707]
### What happened?

My Thermostat always Reports 8% Battery in the Frontend, no matter how new the batteries are.

It seems, that the thermostat does not report Battery percentage, but only a battery low warnin:
https://community.bosch-smarthome.com/t5/einstieg-und-erste-schritte/batteriestatus/m-p/9906 (only German unfortunately)

I could not find any documentation on what different values are possible and what they mean.

### What did you expect to happen?

Z2M shows Battery info correctly.

### Zigbee2MQTT version

1.30.3-dev commit: 49a1f56

### Adapter firmware version

20221226

### Adapter

ZigStar Stick v4

### Debug log

{
    "battery": 8,
    "boost": "OFF",
    "child_lock": "LOCK",
    "display_brightness": 7,
    "display_ontime": 10,
    "display_orientation": "normal",
    "displayed_temperature": "target",
    "linkquality": 51,
    "local_temperature": 21.9,
    "local_temperature_calibration": 0,
    "occupied_heating_setpoint": 16,
    "pi_heating_demand": 0,
    "remote_temperature": 0,
    "running_state": "idle",
    "system_mode": "heat",
    "update": {
        "installed_version": 872682772,
        "latest_version": 872682772,
        "state": "idle"
    },
    "update_available": false,
    "window_open": "OFF"
}

**Comment by DerDreschner** [comment]
I can't confirm that behavior. At least not with the newest firmware released this week (not yet available in Z2M). I have two thermostats, one reporting `battery: 100`, the other `battery: 97`.

Is the attribute `batteryPercentageRemaining` listed in the reporting tab of the device inside Z2M?

**Comment by Taraman17** [comment]
I only have the attribute "battery" as listed in the JSON included in my report. This always shows "8" no matter which batteries I inserted. Starting with rechargeable ones and meanwhile a fresh set of alkaline which are in for over 2 weeks now.

So maybe this changes with the new firmware version...

**Comment by Taraman17** [comment]
The update is available now, but:
error 2023-05-25 12:32:30Update of 'Thermostat Bennet' failed (Device didn't respond to OTA request)

**Comment by Taraman17** [comment]
Update is successful now - Battery still reporting '8'
