### ISSUE TITLE
[Wrong device]: Zigbee 4 button remote

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17704]
### Link

https://es.aliexpress.com/item/1005003639510755.html?gatewayAdapt=glo2esp

### Model

4CH Wireless Remote

### Description

ZigBee 4 Button Remote - 12 Scene

### Vendor

Tuya

### Picture (link)

https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTtm_RE-WRYpM0adBmFM5O9Pnd1pif0TdUIsTLpAqPEr4lQMBH_

### Database entry

{"id":112,"type":"EndDevice","ieeeAddr":"0xa4c13877de566574","nwkAddr":40355,"manufId":4417,"manufName":"_TZ3000_dziaict4","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[1,6,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011'��+\u0012,��+\u0016\u0000\u0000\u0000\u0000\u0011\n\u0000\u0000\u0000\u0013\u000b\u0000\u0000\u0000\u0012�\u0001\u0000\u0000\u0012","65506":49,"65508":1,"65534":0,"modelId":"TS0044","manufacturerName":"_TZ3000_dziaict4","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1684371292583,"defaultSendRequestWhen":"immediate"}

### Notes

This is the Non Dimmer Remote. Uses the Same Model
When the device pairs none of the actions for each button will appear. You will need to press each button to enable the action to be available
ie: Button 1, press once, double press, and then long press. Do that for each button and they should start showing up under Automation
![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/52d75741-a7ee-4980-ae8c-b4fbc3cb0d9c)

I also got the the device information when access via Tuya Developer
{
  "result": {
    "active_time": 1684312351,
    "category": "wxkg",
    "category_name": "Wireless Switch",
    "create_time": 1684312192,
    "gateway_id": "bf61b5ef56f168251axufi",
    "icon": "smart/icon/ay1532660270361428EU/f890146653aca161407b899f006f83d5.png",
    "id": "bf96b710bb95614bcbwxmg",
    "ip": "",
    "lat": "-26.8170",
    "local_key": "91f6768807d47ecf",
    "lon": "153.0591",
    "model": "4CH Wireless Remote",
    "name": "4CH Wireless Remote",
    "node_id": "a4c13877de566574",
    "online": false,
    "owner_id": "4096575",
    "product_id": "dziaict4",
    "product_name": "4CH Wireless Remote",
    "sub": true,
    "time_zone": "+10:00",
    "update_time": 1684312351,
    "uuid": "a4c13877de566574"
  },
  "success": true,
  "t": 1684312394775,
  "tid": "7740940ef48d11edb63796ce6b547e6f"

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by AJKoster** [comment]
Hi Koenkk
I encounter the same problem: 

Link: https://nl.aliexpress.com/item/1005004007846325.html?spm=a2g0o.order_list.order_list_main.35.18e679d2MzrU90&gatewayAdapt=glo2nld

With 'Zigbee fabrikant'  :   **_TZ3000_mh9px7cq** is connected to TS0044 instead of TS0044_1 and is not recognized in the dashboard.

Can you help me here?
Thanks a lot!
Addy

**Comment by Koenkk** [comment]
- Can you make a screenshot of the device -> about tab? (z2m frontend)
- Can you share the data/database.db entry of this device?

**Comment by AJKoster** [comment]
Hi Koen,
Data/databse.db entry:

{"id":20,"type":"EndDevice","ieeeAddr":"0xa4c138219c70316f","nwkAddr":58913,"manufId":4417,"manufName":"_TZ3000_mh9px7cq","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[1,6,57344,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"1\u0000\u0000\u0000\u0012U�k,\u0012��k,\u0012;�k,\u0012��k,\u0012","65506":49,"65508":1,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_mh9px7cq","zclVersion":3,"appVersion":67,"modelId":"TS0044","powerSource":3}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[6,1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1692112367409,"defaultSendRequestWhen":"immediate"}

Device in the attached file..

![vierstandenschakelaar](https://github.com/Koenkk/zigbee2mqtt/assets/25160347/5a296661-ac46-4dc8-a5b8-8646ce907cce)

Thanks a lot for looking into my issue!
Addy

**Comment by Koenkk** [comment]
- The device will be detected as a `TS0044_1` now.
- Regarding the dashboard, not everything is shown there, only specific entities like lights and switches. So nothing wrong here.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by AJKoster** [comment]
Thanks a lot Koen!
