### ISSUE TITLE
Serial over TCP keepalive

### ISSUE THREAD

**Issue by droopanu** [Koenkk/zigbee2mqtt#17715]
### What happened?

After a network issue, the Serial over TCP connection becomes stale and never recovers.

### What did you expect to happen?

TCP confection closed and/or retried

### How to reproduce it (minimal and precise)

Using a remote device with TCP over serial ("serialPort":{"adapter":"ezsp","path":"tcp://192.168.86.85:8888"}), cause a network outage by disconnecting the remote device from the network for a few minutes. Remote device can also be rebooted while disconnected to make sure the TCP connections is cleared.
The TCP connection becomes stale in z2m and never recovers.

Possible option to fix this is to enable keepalives when setting up the serialPort tcp connection, same way it is done for connection to MQTT server. (socat options) 

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

6.6.5.0 build 204

### Adapter

 EZSP v7 (Aqara HUB)

## Debug log

2023-05-18 08:06:34.790	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:info  2023-05-18 08:06:34: MQTT publish: topic 'zigbee2mqtt/0x54ef441000589663', payload '{"action":null,"approach_distance":"medium","device_temperature":28,"linkquality":152,"monitoring_mode":"undirected","motion_sensitivity":"high","power_outage_count":2,"presence":false,"presence_event":"leave","update":{"installed_version":54,"latest_version":54,"state":"idle"},"update_available":null}'

## 5 minute network outage

2023-05-18 08:10:00.791	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:10:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:15:00.801	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:15:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:20:00.792	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:20:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:25:00.793	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:25:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:30:00.794	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:30:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:35:00.794	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:35:00: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:40:44.066	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:40:44: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:44:52.204	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:error 2023-05-18 08:44:52: Not connected to MQTT server!
2023-05-18 08:46:23.060	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:error 2023-05-18 08:46:23: Not connected to MQTT server!
2023-05-18 08:46:40.410	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:46:40: Saving state to file /config/zigbee2mqtt/state.json
2023-05-18 08:47:20.979	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:error 2023-05-18 08:47:20: Not connected to MQTT server!

## z2m manually restarted

2023-05-18 08:48:34.741	
hassio_supervisor
error
#033[33m23-05-18 08:48:34 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Zigbee2MQTT is failed, restarting...#033[0m
2023-05-18 08:48:36.631	
addon_45df7312_zigbee2mqtt
error
[08:48:36] INFO: #033[32mStarting Zigbee2MQTT...#033[0m
2023-05-18 08:48:38.922	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:48:38: Loaded state from file /config/zigbee2mqtt/state.json
2023-05-18 08:48:38.924	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:info  2023-05-18 08:48:38: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-18.08-48-38' filename: log.txt
2023-05-18 08:48:38.926	
addon_45df7312_zigbee2mqtt
informational
Zigbee2MQTT:debug 2023-05-18 08:48:38: Removing old log directory '/config/zigbee2mqtt/log/2023-04-17.17-13-30'

_No response_

**Comment by CheerpipeTecnova** [comment]
Facing same issue with a wired Multimode Gateway V2
