### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#17711]
### Link

https://www.zemismart.com/products/spm01-d2tz-zm

### Database entry

{"id":81,"type":"Router","ieeeAddr":"0x94deb8fffe37d79a","nwkAddr":29009,"manufId":4098,"manufName":"_TZE200_bcusnqt8","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":31,"65508":1,"appVersion":68,"modelId":"TS0601","manufacturerName":"_TZE200_bcusnqt8","powerSource":1,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1684347730189,"defaultSendRequestWhen":"immediate"}

### Comments

Hello Can you please add the support for this device? 

The device appears as not supported 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/47602733/6eaf7dc3-cd01-4c05-af28-3b9fbf97c2a6)

Thank you

**Comment by TadFocus** [comment]
You managed to add this device, I have exactly the same problem ;)
