### ISSUE TITLE
Ota update show only philips devices

### ISSUE THREAD

**Issue by platini76** [Koenkk/zigbee2mqtt#17716]
### What happened?

<img width="1649" alt="Screenshot 2023-05-18 alle 03 48 19" src="https://github.com/Koenkk/zigbee2mqtt/assets/10352902/0b14c58d-4ff7-4491-91a2-57460d0bb0df">

### What did you expect to happen?

<img width="1319" alt="Screenshot 2023-05-18 alle 03 50 45" src="https://github.com/Koenkk/zigbee2mqtt/assets/10352902/8169a4f1-906d-425c-b113-fab309542fea">

I think images speaks alone... why I see only philips devices on my ota updates check?

### Zigbee2MQTT version

1.30.4-dev

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by lux73** [comment]
obviously only your Philips Devices supports/have available OTA Files ^^

**Comment by Koenkk** [comment]
Not all devices support OTA, see https://www.zigbee2mqtt.io/guide/usage/ota_updates.html
