### ISSUE TITLE
TS130F_dual from LORATAP recognized as TS130F single 

### ISSUE THREAD

**Issue by mickeyva** [Koenkk/zigbee2mqtt#17728]
### What happened?

I have a problem with the LoraTap Tuya ZigBee 3.0 EU Double Curtain Switch https://www.aliexpress.com/item/1005005489937491.html - the device is recognized as a single TS130F.

### What did you expect to happen?

It should be recognized as a TS130F_dual double switch.

### Zigbee2MQTT version

1.30.4-dev commit: bfc51e0

### Adapter firmware version

20210708

### Adapter

sonoff p

###  data/database.db entry of this device

{"id":4,"type":"Router","ieeeAddr":"0xa4c1380e978aa7d1","nwkAddr":42830,"manufId":4417,"manufName":"_TZ3000_esynmmox","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[4,5,6,258,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":"","zclVersion":3}},"genOnOff":{"attributes":{"tuyaBacklightSwitch":1,"tuyaBacklightMode":0}},"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":100,"tuyaMovingState":1,"tuyaCalibration":0,"tuyaMotorReversal":0,"moesCalibrationTime":600}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":514,"inClusterList":[4,5,6,258,57345],"outClusterList":[],"clusters":{"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":100,"tuyaMovingState":1,"tuyaCalibration":0,"tuyaMotorReversal":0,"moesCalibrationTime":600}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1684475598894,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
