### ISSUE TITLE
Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open

### ISSUE THREAD

**Issue by ivanovd** [Koenkk/zigbee2mqtt#17733]
### What happened?

A fresh installation of Debian 11.7.0
Home Assistant v2022.5.3 Supervised (running in a Docker container)
Zigbee2MQTT addon v 1.30.4-1
ZB Router = Sonoff Zigbee 3.0 Dongle (ZBDongle-P)

### What did you expect to happen?

The USB stick is correctly discovered: 

```
ls -l /dev/serial/by-id/
total 0
lrwxrwxrwx 1 root root 13 May 19 17:24 usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e015533c5993eb119dd4214f3d98b6d1-if00-port0 -> ../../ttyUSB0
```
```
test -w /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e015533c5993eb119dd4214f3d98b6d1-if00-port0 && echo success || echo failure
success
```
I seem to have write access to it

However, when trying to start the addon I get the following error:
```
[17:39:55] INFO: Preparing to start...
[17:39:56] INFO: Socat not enabled
[17:39:56] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-05-19 17:39:58: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-19.17-39-58' filename: log.txt
Zigbee2MQTT:info  2023-05-19 17:39:58: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
Zigbee2MQTT:info  2023-05-19 17:39:58: Starting zigbee-herdsman (0.14.111)
Zigbee2MQTT:error 2023-05-19 17:39:58: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-19 17:39:58: Failed to start zigbee
Zigbee2MQTT:error 2023-05-19 17:39:58: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-19 17:39:58: Exiting...
Zigbee2MQTT:error 2023-05-19 17:39:58: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e015533c5993eb119dd4214f3d98b6d1-if00-port0
'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18
```

### How to reproduce it (minimal and precise)

1. Fresh install of Debian 11.7.0
2. Fresh install of Home Assistant Supervised in a Docker container
3. Install Zigbee2MQTT and mosquito broker
4. Insert Sonoff ZBDongle-P
5. Try to start the Zigbee2MQTT addon

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

can't get to the frontend since it can't start, but the firmware is the standard one

### Adapter

Sonoff ZBDongle-P

**Comment by ivanovd** [comment]
The user seems to be in the correct groups:
```
groups skunkix
skunkix : skunkix tty uucp dialout cdrom floppy sudo audio dip video plugdev netdev bluetooth lpadmin scanner docker
```

**Comment by b2un0** [comment]
did you mounted the `/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e015533c5993eb119dd4214f3d98b6d1-if00-port0` to the z2m docker container? 🤔

**Comment by ivanovd** [comment]
@b2un0 yes. It turns out that there is a known issue with Debian 11.7, therefore I installed 11.5 from scratch and everything worked out of the box.
