### ISSUE TITLE
[Wrong device]: eWeLink SA-003-Zigbee

### ISSUE THREAD

**Issue by JJanssen123** [Koenkk/zigbee2mqtt#17731]
### Link

https://zigbee.blakadder.com/eWeLink_SA-003-Zigbee.html

### Model

SA-003-Zigbee

### Description

Switch

### Vendor

Ewelink

### Picture (link)

https://zigbee.blakadder.com/assets/images/devices/eWeLink_SA-003-Zigbee.webp

### Database entry

{"id":13,"type":"Router","ieeeAddr":"0x00124b001b6275c3","nwkAddr":6384,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":9,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"SA-003-Zigbee","manufacturerName":"eWeLink","powerSource":1,"zclVersion":1,"hwVersion":1,"dateCode":"20190907-V102"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00258bde8b","endpointID":1}],"configuredReportings":[],"meta":{}}},"hwVersion":1,"dateCode":"20190907-V102","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1680707076060,"defaultSendRequestWhen":"immediate"}

### Notes

Sorry to point to Blakadder but i can't find any official webpage. Googling the model also shows a plug with this name, that picture is now used in Z2M. Apparently there are two devices using this name. I don't know if Z2M can distinguish between those two?

Here's another picture from the product that I bought on AliExpress: https://ae01.alicdn.com/kf/HTB1jsunbyLxK1Rjy0Ffq6zYdVXaM.jpg_220x220.jpg

**Comment by Koenkk** [comment]
Device uses the same model so unfortunately we cannot distinguish it.
