### ISSUE TITLE
[Wrong device]: TuYa YSR-MINI-Z

### ISSUE THREAD

**Issue by Soulfly999** [Koenkk/zigbee2mqtt#17747]
### Link

https://www.zigbee2mqtt.io/devices/YSR-MINI-Z.html

### Model

YSR-MINI-Z

### Description

2 in 1 dimming remote control and scene control

### Vendor

TuYa

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/YSR-MINI-Z.jpg

### Database entry

EndDevice, 0xa4c138240e38289b, 0xABC6

### Notes

Device is shown as TS0044

**Comment by Koenkk** [comment]
Please provide the `data/database.db` entry of this device.
