### ISSUE TITLE
NWK_TABLE_FULL e.g. when changing color for lightbulb

### ISSUE THREAD

**Issue by markus-barta** [Koenkk/zigbee2mqtt#17742]
### What happened?

When I try to change the color for a [lightbulb](https://www.zigbee2mqtt.io/devices/33943_33944_33946.html), it does not change but an error (0xc7: NWK_TABLE_FULL) appears in the log:

`Publish 'set' 'color' to 'licht/status-dl/wz' failed: 'Error: Command 0xa4c1384953017707/1 lightingColorCtrl.enhancedMoveToHueAndSaturation({"transtime":0,"enhancehue":21914,"direction":0,"saturation":254}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":23600,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'`

### What did you expect to happen?

The color should change.

### How to reproduce it (minimal and precise)

Click on another color that is not currently active in the `Exposes` tab of the device.

### Zigbee2MQTT version

1.30.4 commit: b2dd21e

### Adapter firmware version

20210708 and 20230507 (same problems after update to 20230507)

### Adapter

SONOFF Zigbee 3.0 USB Dongle

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11524424/log.txt)

**Comment by Koenkk** [comment]
This is a known issue of AwoX lights, I recommend not to use AwoX devices in your network.
