### ISSUE TITLE
How could device join the network being still packed?

### ISSUE THREAD

**Issue by quarcko** [Koenkk/zigbee2mqtt#1775]
Not a bug report, just want to share observation
And or get probable explanations, maybe someone had similar accidents :)
So recently i spotted a strange device on zigbee map.
It is Xiaomi wireless switch WXKG11LM. 
It is not connected to any router or anything.

I have lots of devices so i did not payed much attention,
But later on i spotted that all my working swithes are
WXKG12LM, and this one is the only one i have and it is still in factory box!!!!! I never opened the box.
So obviuosly i never pressed pairing button.

But yet device is on map.
I walked through all my log files but sadly 
The moment of pairing was somewhere gone.

So... Does your unboxed devices pair to network? 
Somebody had something like that?

**Comment by Koenkk** [comment]
I've seen that some factory fresh devices (not paired to a network before) automatically enter pairing mode when they are triggered. e.g. for a TRADFRI bulb when they are powered on for the first time. 

In your case, could it be that the button has been pressed while in the box? 

Anyway, note that the issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.
