### ISSUE TITLE
[Wrong device]: Tuya double Curtain Module

### ISSUE THREAD

**Issue by sodiniss** [Koenkk/zigbee2mqtt#17753]
### Link

https://it.aliexpress.com/item/1005005237959410.html?spm=a2g0o.productlist.main.23.6724dd9dwukqZd&algo_pvid=df659f5c-fc7c-49cf-9f67-98974fff244c&algo_exp_id=df659f5c-fc7c-49cf-9f67-98974fff244c-11&pdp_npi=3%40dis%21EUR%2131.41%2118.53%21%21%21%21%21%402100bbf516814630873165402d06f5%2112000032319225893%21sea%21IT%21703783858&curPageLogUid=hMNcgDp64P6I

### Model

Zigbee 2CH Curtain Module

### Description

2CH Curtain Module 4 relays

### Vendor

Tuya

### Picture (link)

https://ae01.alicdn.com/kf/Sae36521e56b048649a66178fe309cce5S.jpg

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xdc8e95fffef7d549","nwkAddr":25601,"manufId":4098,"manufName":"_TZ3000_l6iqph4f","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[0,4,5,6,258,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS130F","manufacturerName":"_TZ3000_l6iqph4f","stackVersion":0,"dateCode":""}},"genOnOff":{"attributes":{"tuyaBacklightSwitch":1,"tuyaBacklightMode":0}},"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":33,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":0,"moesCalibrationTime":100}},"manuSpecificTuya_3":{"attributes":{}},"genLevelCtrl":{"attributes":{}},"genOnOffSwitchCfg":{"attributes":{}},"genIdentify":{"attributes":{}},"nearestGateway":{"attributes":{}},"manuSpecificTuya_2":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":514,"inClusterList":[4,5,6,258,57345],"outClusterList":[],"clusters":{"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":58,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":0,"moesCalibrationTime":50}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1683137690482,"defaultSendRequestWhen":"immediate"}

### Notes

Tuya module for controlling 2 shutters, wrong paired with [this](https://www.zigbee2mqtt.io/devices/TS130F.html) which enabled control for just one shutter. Using the extension below fixes the second shutter, however it's still **probably** missing switchType and other switch controls, since pressing the button **completely** opens/closes the shutter and I hope that's not the intended behaviour. 

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS130F', manufacturerName: '_TZ3000_l6iqph4f'}],
    model: 'TS130F',
    vendor: 'TuYa',
    description: 'Dual curtain/blind module',
    fromZigbee: [fz.cover_position_tilt, fz.tuya_cover_options],
    toZigbee: [tz.cover_state, tz.cover_position_tilt, tz.tuya_cover_calibration, tz.tuya_cover_reversal],
    meta: {multiEndpoint: true},
    endpoint: (device) => {
        return {'l1': 1, 'l2': 2};
    },
    exposes: [
        exposes.enum('moving', ea.STATE, ['UP', 'STOP', 'DOWN']),
        exposes.numeric('calibration_time', ea.STATE).withUnit('S').withDescription('Calibration time'),

        e.cover_position().withEndpoint('l1'),
        exposes.enum('moving', ea.STATE, ['UP', 'STOP', 'DOWN']).withEndpoint('l1'),
        exposes.binary('calibration', ea.ALL, 'ON', 'OFF').withEndpoint('l1'),
        exposes.binary('motor_reversal', ea.ALL, 'ON', 'OFF').withEndpoint('l1'),
        exposes.numeric('calibration_time', ea.STATE).withUnit('S').withDescription('Calibration time').withEndpoint('l1'),
        
        e.cover_position().withEndpoint('l2'),
        exposes.enum('moving', ea.STATE, ['UP', 'STOP', 'DOWN']).withEndpoint('l2'),
        exposes.binary('calibration', ea.ALL, 'ON', 'OFF').withEndpoint('l2'),
        exposes.binary('motor_reversal', ea.ALL, 'ON', 'OFF').withEndpoint('l2'),
        exposes.numeric('calibration_time', ea.STATE).withUnit('S').withDescription('Calibration time').withEndpoint('l2')
    ],
 };

module.exports = definition;
```

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
