### ISSUE TITLE
eWeLink	ZB-SW02:No converter available for 'state_left' (undefined) 

### ISSUE THREAD

**Issue by xav31190** [Koenkk/zigbee2mqtt#17758]
### What happened?

Hi,
The next module [https://www.amazon.fr/gp/product/B09289WDRQ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1](url) is seen as eWeLink ZB-SW02. 
if the "last_seen" command updates successfully, the action ''state_left' , "'state_right" On or OFF commands generate an error No converter available for 'state_l...' (undefined)

### What did you expect to happen?

The command action "state_left" for example must activate the relay of the module

### How to reproduce it (minimal and precise)

by executing one of the action commands of the module, this generates the error in Z2m

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

0x26780700

### Adapter

 ConBee2/RaspBee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11536256/log.txt)
[raw information jEEDOM.txt](https://github.com/Koenkk/zigbee2mqtt/files/11536334/raw.information.jEEDOM.txt)

**Comment by Koenkk** [comment]
Could you provide the debug log of this?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.
