### ISSUE TITLE
TuYa TS0207 Repeater is not repeating

### ISSUE THREAD

**Issue by NeWoKiKi** [Koenkk/zigbee2mqtt#17778]
### What happened?

I bought a TuYa TS0207 Repeater and added it in Zigbee2MQTT without any problem but it's not doing its job.
If I check in Schema section, I can see that my repeater isn't repeating anything (there are some devices closer to the repeater than coordinator).

Schema :
![image](https://github.com/Koenkk/zigbee2mqtt/assets/69678428/23709d4d-a479-4863-b51a-8da5618dfde1)

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

7.2.0.0 build 108

### Adapter

EZSP v9

**Comment by grobihh** [comment]
@NeWoKiKi That repeater model seems to work for other users.
see https://github.com/Koenkk/zigbee2mqtt/issues/19196
![image](https://github.com/Koenkk/zigbee2mqtt/assets/6832312/4c88ced8-0d69-4b12-98cd-aa1fee047b3e)
