### ISSUE TITLE
[New device support]: REJIA HR109 vibration sensor

### ISSUE THREAD

**Issue by fantasyjqc** [Koenkk/zigbee2mqtt#17776]
### Link

I cannot find the link for the product

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xdd16abfff1a36367","nwkAddr":63658,"manufId":48042,"manufName":"REJIA","powerSource":"Battery","modelId":"HR109 V01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1280,3,1],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"HR109 V01","manufacturerName":"REJIA","powerSource":3,"zclVersion":1,"appVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"20150330"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0025792041","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"20150330","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1684839688771,"defaultSendRequestWhen":"immediate"}

### Comments

Info 2023-05-23 19:11:04MQTT publish: topic 'z2m/0xdd16abfff1a36367', payload '{"action":true,"linkquality":142}'

![IMG_1737](https://github.com/Koenkk/zigbee2mqtt/assets/4988150/c5aa1490-69c2-471a-ad1d-10797a62f4b2)

### External converter

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;

const fzLocal = {
    REJIA_vibration: {
        cluster: 'ssIasZone',
        type: 'commandStatusChangeNotification',
        convert: (model, msg, publish, options, meta) => {
            return { action: true };
        },
    }
};

const definition = {
    zigbeeModel: ['HR109 V01'],
    model: 'HR109 V01',
    vendor: 'REJIA',
    description: 'REJIA vibration sensor',
    fromZigbee: [fzLocal.REJIA_vibration],
    exposes: [e.action(['vibration'])],
    toZigbee: []
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Could you create a PR for https://github.com/Koenkk/zigbee-herdsman-converters ?
