### ISSUE TITLE
[New device support]:  orvibo RemoteControl model RC808ZB

### ISSUE THREAD

**Issue by fantasyjqc** [Koenkk/zigbee2mqtt#17775]
### Link

https://smart-homes.ir/shop/products/other-smart-home-gears/hub/%D8%B1%DB%8C%D9%85%D9%88%D8%AA-%DA%A9%D9%86%D8%AA%D8%B1%D9%84%D8%B1-orvibo-%D9%BE%D8%B1%D9%88%D8%AA%DA%A9%D9%84-zigbee/

### Database entry

{"id":27,"type":"EndDevice","ieeeAddr":"0x00124b000413241c","nwkAddr":13862,"manufId":0,"manufName":"ORUIBO          ","powerSource":"Battery","modelId":"RemoteControl-22","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0],"outClusterList":[0,23],"clusters":{"genBasic":{"attributes":{"modelId":"RemoteControl-22","manufacturerName":"ORUIBO          ","powerSource":3,"zclVersion":0,"hwVersion":0,"dateCode":"2012-12-07      "}}},"binds":[],"configuredReportings":[],"meta":{}}},"hwVersion":0,"dateCode":"2012-12-07      ","zclVersion":0,"interviewCompleted":true,"meta":{},"lastSeen":1684838665893,"defaultSendRequestWhen":"immediate"}

### Comments

Info 2023-05-23 18:46:17MQTT publish: topic 'z2m/0x00124b000413241c', payload '{"action":"button_7_click","linkquality":145}'
Info 2023-05-23 18:46:27MQTT publish: topic 'z2m/0x00124b000413241c', payload '{"action":"button_2_click","linkquality":138}'
Info 2023-05-23 18:46:29MQTT publish: topic 'z2m/0x00124b000413241c', payload '{"action":"button_1_click","linkquality":142}'

![Orvibo-Remote-480x760-1](https://github.com/Koenkk/zigbee2mqtt/assets/4988150/7261b5fe-4de7-4233-8d51-a9aca9b9f68b)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;

const fzLocal = {
    orvibo_raw_3: {
        cluster: 23,
        type: 'raw',
        convert: (model, msg, publish, options, meta) => {
            const buttonLookup = {
                1: 'button_all_open',
                2: 'button_at_home',
                21: 'button_sleep',
                4: 'button_all_close',
                3: 'button_leave_home',
                23: 'button_play',
                5: 'button_1',
                6: 'button_2',
                7: 'button_3',
                8: 'button_4',
                9: 'button_5',
                10: 'button_6',
                11: 'button_7',
                12: 'button_8',
                14: 'button_9',
                15: 'button_0',
                17: 'button_lock',
                18: 'button_plus',
                19: 'button_minus',
            };

            const actionLookup = {
                0: 'click',
                2: 'hold',
                3: 'release',
            };
            const button = buttonLookup[msg.data[3]];
            const plus = msg.data[4];
            const action = actionLookup[msg.data[5]];
            if (button) {
                if (plus == 0) {
                    return { action: `${button}_${action}` };
                } else if (plus == 1) {
                    return { action: `button_1plus_${button}_${action}` };
                } else if (plus == 2) {
                    return { action: `button_2plus_${button}_${action}` };
                }
            }
        },
    },
};

const definition = {
    zigbeeModel: ['RemoteControl-22'],
    model: 'RC808ZB',
    vendor: 'ORVIBO',
    description: 'Smart sticker switch',
    fromZigbee: [fzLocal.orvibo_raw_3, fz.battery],
    exposes: [e.battery()],
    toZigbee: [],
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Could you create a PR on https://github.com/Koenkk/zigbee-herdsman-converters ?
