### ISSUE TITLE
GiEx QT06_1 (_TZE200_sh1btabb) unreliability problems

### ISSUE THREAD

**Issue by Cossey** [Koenkk/zigbee2mqtt#17784]
### What happened?

I've had this smart valve for a couple of months now and have noticed some reliability issues.

Sometimes this valve doesn't respond to the controls or sends back any water consumed information like it should.

In the morning I have it turn on for 10 minutes. On rare occasions (maybe once every 10 days) it runs for hours because it didn't turn off automatically - which is not ideal. When this does occur, I noticed zigbee2mqtt says the state is OFF but the valve is still open. I have to toggle the state to ON, then back to OFF again (and sometimes I have to do this 2-3 times) for the valve to actually close. I should note that when it is in this incorrect state, sometimes the `water_consumed` will not change despite water flowing.

I experience this issue in two ways - one where I have a timer in openHAB, in which after 10 minutes it will send the OFF `state` to the valve, and the other is via the `mode = duration` and `irrigation_target = 10` through zigbee2mqtt. In both of these cases I have had that same problem.

Further to this, I've noticed that there has been times where the valve didn't update the `water_consumed` at all. The valve is running, but this value is not being updated.

Re-pairing the device to coordinator seems to fix the `water_consumed` issue and I _feel_ like the device becomes more reliable for a while, until its back to its unreliable self. 

Batteries are still at 100% and the device is signal is 149lqi. According to network map, this device is routed through my Hue white ambiance E26 (LTW015) and then straight to the coordinator. Has anyone experienced an issue with this?

I have not yet had the chance to get the sniffer out to watch the packets when things are going wrong - but I hope to get some time to set this back up soon. I am mainly just posting to see if others in the community are having the same problem.

### What did you expect to happen?

That the valve `state` in zigbee2mqtt would actually reflect the physical state. When in the OFF state, it should be off and the water flow stopped. Also, if the water is flowing, it should always be updating the `water_consumed` state.

### How to reproduce it (minimal and precise)

I have not yet found a way to reproduce this - it occurs sporadically.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20221226

### Adapter

SONOFF ZBDongle-P

**Comment by sander85** [comment]
Hi!

I'm having similar problems. But even more annoying. Quite often I can get data from the device perfectly (I push physical button and the state changes + usage is updating as well) but at the same time it takes 0 commands. Doesn't matter if it's paired to controller or some router. I add it again and all is perfect, until it's not again. lqi is 255.

**Comment by louiezhu2** [comment]
I have experienced the same problems in both Homeassistant and their SmartLife app. The states in zigbee2mqtt or in the app don't always reflect the actual states of the valve. LQI is 165.

**Comment by Cossey** [comment]
I'm wondering if we're unlucky enough to have duds or maybe there's something happening on the Zigbee side that needs to be implemented in z2m. Would aging out cause this (or would it cause complete disconnect)...

**Comment by T123S** [comment]
Hi there. I issue the same problem. I have two of the devices. One is working perfectly. The other not. The not working device lost it's connection after some days. Unfortunately we are on vacation and it should shower tomatoes and other vegetables 🙁

When someone press the physical button long and I press device recognition on zigbee2mqtt, it works again for some time.

**Comment by Cossey** [comment]
@T123S are these both the same model - _TZE200_sh1btabb? This is curious that one has an issue but the offer does not; are both connected directly to the coordinator or through routers?

**Comment by T123S** [comment]
Yes, both are Water irrigation valve (QT06_2)
von GiEX from same vendor from AliExpress. Both are on the same router and from there to coordinater.

The other one works like a charm.

So I fear. One is broken. Unfortunately the wrong one for me 😡 Maybe we can send it back.

**Comment by T123S** [comment]
> @T123S are these both the same model - _TZE200_sh1btabb? This is curious that one has an issue but the offer does not; are both connected directly to the coordinator or through routers?

Zigbee2mqtt is very powerful. Maybe there is a possibility to send a ping every 5 minutes so the device stays alive?

**Comment by danstr1** [comment]
Hi

I have encounter this issue also in my GiEx QT06_1 ZigBee valve
Did you find any solution or workaround to overcome that?
Thanks

**Comment by dada1992bite** [comment]
Same problem too ... Looking for solutions

Thanks

**Comment by peepshow-21** [comment]
Hi,

I have just got one of these and have added it as a device to my Sonoff Zigbee Bridge (with Tasmota). It added as a device easy enough and I can see event from it when I press the of/off button on the water meter
```
20:54:26.372 ZIG: Battery auto-probe `ZbSend {"Device":"0x36A0","Read":{"BatteryPercentage":true,"BatteryVoltage":true}}`
20:54:26.389 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0366":"--:--:--","Endpoint":1,"LinkQuality":61}}}
20:54:26.581 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026F":0,"Endpoint":1,"LinkQuality":61}}}
20:54:26.781 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0102":1,"Endpoint":1,"LinkQuality":61}}}
20:54:26.881 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0365":"08:39:33","Endpoint":1,"LinkQuality":61}}}
20:54:35.682 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026A":0,"Endpoint":1,"LinkQuality":51}}}
20:54:35.833 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0267":0,"Endpoint":1,"LinkQuality":54}}}
20:54:35.981 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0102":0,"Endpoint":1,"LinkQuality":58}}}
20:54:36.133 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0366":"08:39:42","Endpoint":1,"LinkQuality":36}}}
20:54:36.332 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0372":"00:00:09,0","Endpoint":1,"LinkQuality":65}}}
20:54:57.290 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026C":100,"Endpoint":1,"LinkQuality":65}}}
```

However, I'm struggling to find the command to open/close the value from tasmota. I've tried
```
zbsend {"device":"0x36a0","send":{"power":1}}
```
(no idea of that is even right!)

and I get back
```
20:56:27.886 MQT: tele/zigbee_bridge/STATE = {"Time":"2023-10-09T20:56:27","Uptime":"7T00:10:22","UptimeSec":605422,"Heap":158,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":88,"Berry":{"HeapUsed":3,"Objects":44},"Wifi":{"AP":1,"SSId":"Error-404s","BSSId":"00:22:33:44:AA:A0","Channel":10,"Mode":"11n","RSSI":100,"Signal":-17,"LinkCount":59,"Downtime":"0T00:02:47"}}
20:57:24.583 CMD: zbsend {"device":"0x36a0","send":{"power":1}}
20:57:24.597 MQT: stat/zigbee_bridge/RESULT = {"ZbSend":"Done"}
20:57:26.846 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","Reachable":false}}}
20:57:31.148 MQT: tele/zigbee_bridge/RESULT = {"ZbConfirm":{"Endpoint":1,"Status":240,"StatusMessage":""}}
```

Anyone point me in the right direction of what I need to send?

Thanks

**Comment by Cossey** [comment]
> Hi,
> 
> I have just got one of these and have added it as a device to my Sonoff Zigbee Bridge (with Tasmota). It added as a device easy enough and I can see event from it when I press the of/off button on the water meter
> 
> ```
> 20:54:26.372 ZIG: Battery auto-probe `ZbSend {"Device":"0x36A0","Read":{"BatteryPercentage":true,"BatteryVoltage":true}}`
> 20:54:26.389 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0366":"--:--:--","Endpoint":1,"LinkQuality":61}}}
> 20:54:26.581 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026F":0,"Endpoint":1,"LinkQuality":61}}}
> 20:54:26.781 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0102":1,"Endpoint":1,"LinkQuality":61}}}
> 20:54:26.881 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0365":"08:39:33","Endpoint":1,"LinkQuality":61}}}
> 20:54:35.682 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026A":0,"Endpoint":1,"LinkQuality":51}}}
> 20:54:35.833 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0267":0,"Endpoint":1,"LinkQuality":54}}}
> 20:54:35.981 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0102":0,"Endpoint":1,"LinkQuality":58}}}
> 20:54:36.133 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0366":"08:39:42","Endpoint":1,"LinkQuality":36}}}
> 20:54:36.332 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/0372":"00:00:09,0","Endpoint":1,"LinkQuality":65}}}
> 20:54:57.290 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","EF00/026C":100,"Endpoint":1,"LinkQuality":65}}}
> ```
> 
> However, I'm struggling to find the command to open/close the value from tasmota. I've tried
> 
> ```
> zbsend {"device":"0x36a0","send":{"power":1}}
> ```
> 
> (no idea of that is even right!)
> 
> and I get back
> 
> ```
> 20:56:27.886 MQT: tele/zigbee_bridge/STATE = {"Time":"2023-10-09T20:56:27","Uptime":"7T00:10:22","UptimeSec":605422,"Heap":158,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":88,"Berry":{"HeapUsed":3,"Objects":44},"Wifi":{"AP":1,"SSId":"Error-404s","BSSId":"00:22:33:44:AA:A0","Channel":10,"Mode":"11n","RSSI":100,"Signal":-17,"LinkCount":59,"Downtime":"0T00:02:47"}}
> 20:57:24.583 CMD: zbsend {"device":"0x36a0","send":{"power":1}}
> 20:57:24.597 MQT: stat/zigbee_bridge/RESULT = {"ZbSend":"Done"}
> 20:57:26.846 MQT: tele/zigbee_bridge/SENSOR = {"ZbReceived":{"0x36A0":{"Device":"0x36A0","Reachable":false}}}
> 20:57:31.148 MQT: tele/zigbee_bridge/RESULT = {"ZbConfirm":{"Endpoint":1,"Status":240,"StatusMessage":""}}
> ```
> 
> Anyone point me in the right direction of what I need to send?
> 
> Thanks

haha does it work reliably though?

**Comment by peepshow-21** [comment]
> haha does it work reliably though?

How do you mean? It work? I can see what state it is and turn on/off.

WiFi on the Sonoff Zigbee Pro is very poor though. I have about 20 other devices, of different kinds (sonoff too) and all these seem solid. But the ZB Bridge drops packets all over the place. Pings to it are full of 'Request timed out' and you need to refresh pages on the Tas GUI, many times. But it works. 

I have no idea if this is just a 'feature' of the bridge because it's got wifi and zig and that makes interference, or mine is faulty. I only have 1 of this, so can't say.

But basically it works. :)
