### ISSUE TITLE
Bosch BTH-RA - how to pair - unsupported install code

### ISSUE THREAD

**Issue by DSRocker** [Koenkk/zigbee2mqtt#17783]
### What happened?

unsupported install code

### Zigbee2MQTT version

1.30.4 commit: unknown

### Adapter firmware version

0x26690700

### Adapter

ConBee2/RaspBee2

### Debug log

Request 'zigbee2mqtt/bridge/request/install_code/add' failed with error: 'Add install code is not supported'

MQTT publish: topic 'zigbee2mqtt/bridge/response/install_code/add', payload '{"data":{},"error":"Add install code is not supported","status":"error","transaction":"rw4u3-2"}'

**Comment by Koenkk** [comment]
You cannot, as your current adapter doesn't support install codes and the device requires it for pairing.

**Comment by DSRocker** [comment]
Is there any other Devices / ZigbeeDongles that support Bosch?

**Comment by Koenkk** [comment]
All texas instruments dongles support install codes: https://www.zigbee2mqtt.io/guide/adapters/
