### ISSUE TITLE
How to Calculate Distance from the RSSI value

### ISSUE THREAD

**Issue by ChucVanLe** [Koenkk/zigbee2mqtt#1778]
I use CC2531 USB sniffer as coordinator and have have some Zigbee End device.
I can control ON/OFF ZED by CC2531 USB sniffer and zigbee2mqtt.
(mosquitto_pub -h localhost -t zigbee2mqtt/0x00124b00071a0271/set -m “ON”)
I need calculate distance from Coordinator (CC2531 USB sniffer) to Zigbee End Device.
Can you help me?

Thanks and Best regards,

Chuc.Le

**Comment by Koenkk** [comment]
I think this is very hard to do as interference has a high effect on the RSSI, however you could try taking a few reference measurements.

Note that the issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.
