### ISSUE TITLE
[New device support]: add Device LED-Trading 9135 Curtain Motor Controller

### ISSUE THREAD

**Issue by anharald** [Koenkk/zigbee2mqtt#17786]
### Link

https://www.led-trading.de/ZigBee-Einbaudose-Unterputz-Jalousie-Steuergeraet-Controller-ZigBee-30-fuer-Hue

### Database entry

{"id":31,"type":"Router","ieeeAddr":"0x94deb8fffe857e65","nwkAddr":36562,"manufId":4107,"manufName":"Sunricher","powerSource":"Mains (single phase)","modelId":"HK-ZCC-ZLL-A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,258,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"HK-ZCC-ZLL-A","manufacturerName":"Sunricher","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r47"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r47","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1684922000453,"defaultSendRequestWhen":"immediate"}

### Comments

i tried to do external converter and just copied the settings from Sunricher SR-ZG9080A which is already supported in z2m,
it seems to be technical identical with this one. So far with the external converter the device seems to work. but i only have basic knowledge if its done right.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['HK-ZCC-ZLL-A'],
    model: 'Led-Trading-9135',
    vendor: 'Sunricher',
    description: 'Curtain motor controller',
        fromZigbee: [fz.cover_position_tilt],
        toZigbee: [tz.cover_state, tz.cover_position_tilt],
        exposes: [e.cover_position()],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['closuresWindowCovering']);
            await reporting.currentPositionLiftPercentage(endpoint);
        },
};

module.exports = definition;
```

### Supported color modes

-

### Color temperature range

-

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
