### ISSUE TITLE
K4027C/L4027C/N4027C/NT4027C not updating status

### ISSUE THREAD

**Issue by federicosantolini** [Koenkk/zigbee2mqtt#17785]
### What happened?

When my window (connected to the bticino device) changes its state, it is not reported to Z2M until i click the refresh button on the "Exposes" tab. this happens if i click on the physical button, by voice via Alexa\Google and if i open\close it from Z2M\HA.

### What did you expect to happen?

I'd like to have the state\position reported.

### How to reproduce it (minimal and precise)

open\close the window\cover

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

26720700

### Adapter

Conbee2

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/bcd1df5573e7504fe35dfe9fc237104f

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by federicosantolini** [comment]
You are always the best! The converter fixed it! thanks!

**Comment by Koenkk** [comment]
Great, integrated the fix

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by developerGM** [comment]
@federicosantolini 
can you set the percentage to open/close the device using zigbee2mqtt?
because I can only open or close (0, 50, 100)

**Comment by altrdev** [comment]
I have the same problem, if i click on the physical button the state is not updated until I click the refresh button on the "Exposes" tab. 
z2m version 1.33-0.1 .

**Comment by developerGM** [comment]
My problem is different. 
I can't set a percentage to open/close.

@altrdev If you want open at 30%, your K4027C works?

**Comment by federicosantolini** [comment]
@developerGM it should depend on the firmware version you have

**Comment by developerGM** [comment]
Firmware 20211215 and version 0036
If I try to launch ota update I recive this message 

Firmware on xxxx is newer than last firmware online
