### ISSUE TITLE
service don't start after last release

### ISSUE THREAD

**Issue by Grazulex** [Koenkk/zigbee2mqtt#17792]
### What happened?

Hello,

I'm in Jeedom 4.3.17 and I have make the last update of Zigbee2MQTT (via zigbeelinker) 1.30.3 => 1.30.4 but after this, I was not more able to start the service. I have made a full restore to be able to restart my system.

How can I help you to find the problem ?

Thanks

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

EZSP v8

**Comment by gpshml** [comment]
Not sure if you are using !secrets but mine was not starting and it turned out to be that (I believe) there's an issue with Zigbee2MQTT accessing the secrets.yaml file.  Confirmed this by directly adding username and password.
