### ISSUE TITLE
Xiaomi Sensor Pairing Bug

### ISSUE THREAD

**Issue by GuGu927** [Koenkk/zigbee2mqtt#1781]
# Bug Report
## What happened
I'm using latest version of zigbee2mqtt.(Hass.io add-on)
There is a problem with pairing the device(Xiaomi WSDCGQ11LM).

Here's my config : https://pastebin.com/MGzV300N
Here's my db : https://pastebin.com/xUsLPsSM
Here's my log :  https://pastebin.com/63Dt01G3
https://pastebin.com/ui5qjqcE
  zigbee2mqtt:info 7/26/2019, 9:16:45 PM air_livingroom (0x00158d00023711f2): unkown - undefined unknown (EndDevice)
  zigbee2mqtt:info 7/26/2019, 9:16:45 PM air_room1 (0x00158d00022728f7): unkown - undefined unknown (EndDevice)

When sensor updates status : https://pastebin.com/UhLUdbsJ

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version:  CC2531_SOURCE_ROUTING_20190619

**Comment by GuGu927** [comment]
I tested it in various ways.
I found the cause.

"zigbee_shepherd_devices"
This option creates the problem.

When    "zigbee_shepherd_devices": false
Sensor works great, pairing good.
When    "zigbee_shepherd_devices": true
Sensor not works, pairing issue.

**Comment by Koenkk** [comment]
You should only use that option when you are using a custom zigbee-shepherd-converters (for e.g. adding support for unsupported devices). Assuming this can be closed now.

**Comment by GuGu927** [comment]
@Koenkk  I'm using custom zigbee-shepherd-converters.
I'm using unsupported devices... :(

**Comment by GuGu927** [comment]
> You should only use that option when you are using a custom zigbee-shepherd-converters (for e.g. adding support for unsupported devices). Assuming this can be closed now.
@Koenkk I'm using custom zigbee-shepherd-converters.
I'm using unsupported devices... :(

**Comment by GuGu927** [comment]
It was available  zigbee2mqtt  version 1.4.0
