### ISSUE TITLE
Device IKEA SYMFONISK sound controller E1744 do not report "toggle" action after firmware update

### ISSUE THREAD

**Issue by xen-mak** [Koenkk/zigbee2mqtt#17823]
### What happened?

After device OTA firmware update to version [2.3.080], Z2M do not response to press action anymore (was "toggle" in action), while version 2.1.024 is still working fine

### What did you expect to happen?

Device keep report all the same actions like previous firmware version

### How to reproduce it (minimal and precise)

Upgrade E1744 to 2.3.080 from 2.1.024

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF Zigbee 3.0 USB ZBDongle-E

**Comment by Fietspomp86** [comment]
Hi, I just updated my E1744 to same version and to be honest I'm experiencing no issues with the toggle button.

Perhaps try removing/re-pairing the device?
