### ISSUE TITLE
All Tuya thermostats are dangerous for zigbee network.

### ISSUE THREAD

**Issue by NikitaKorneev** [Koenkk/zigbee2mqtt#17833]
### What happened?

_TZE200_ye5jkfsb TS0601, _TZE200_znzs7yaw TS0601, _TZE200_aoclfnxz TS0601 And ALL the other Tuya Zigbee thermostats have a bug in their firmware that floods the network with messages.

Having more than couple of device will shut down an entire network at one point.

debounce option will not help. 

### How to reproduce it (minimal and precise)

Add any Tuya - based zigbee thermostat and sniff the network/look at the info logs. You should see over 50 messages per second.

### Zigbee2MQTT version

latest

### Adapter firmware version

latest (it does not matter, you will see it on any version)

### Adapter

Egony stick v4

**Comment by lux73** [comment]
all Tuya Devices are very noisy ;-)

**Comment by NikitaKorneev** [comment]
> all Tuya Devices are very noisy ;-)

The reason I created this issue is because devices I am talking about paralyze network entirely!

**Comment by gpshml** [comment]
> > all Tuya Devices are very noisy ;-)
> 
> The reason I created this issue is because devices I am talking about paralyze network entirely!

I have just tried adding a Moes based one and it is doing the same thing, even when un-joined.  Going to have to un-install it I think.

**Comment by Koenkk** [comment]
@NikitaKorneev can you confirm this also happens with the TuYa gateway? https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by NikitaKorneev** [comment]
> @NikitaKorneev can you confirm this also happens with the TuYa gateway? https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

I have ordered everything I need for sniffing the network. BRB in about four days. Sorry, cannot do it earlier due to having no hardware

**Comment by NikitaKorneev** [comment]
My apologies - had no time to do the sniffing. I will try to do it by the end of next week.

**Comment by smarticz** [comment]
Yes, I have this problem too.

**Comment by kokireg** [comment]
I have the same problem with TZE204_aoclfnxz

**Comment by NikitaKorneev** [comment]
I was unable to sniff the network to get the logs. Does anyone have such ability?

**Comment by 0anton** [comment]
I can confirm it too.

Not all models are affected, but I met at least two already (one is sold as Beco Zigbee Thermostat, another MOES Smart Tuya).

Some models starts spamming the network almost immediately, other can work for months until they go crazy.

Besides significantly reducing the capacity of the Zigbee network by constantly transmitting void messages, devices also become unmanageable.

This is especially problematic, if those at the remote location. I often experienced that they stuck on the "switched on" mode, overheating the house left uninhabited over the winter. 

Right now thermostat went crazy. It is uncontrollable, spams at rate of multiple messages per second and stuck in the "heat" state.


Frequent status update (typical for all spammy Tuya thermostats):

```
Zigbee2MQTT:info  2024-02-21 00:59:48: MQTT publish: topic 'zigbee2mqtt/Теплый пол кухня 2', payload '{"child_lock":null,"current_heating_setpoint":25,"deadzone_temperature":null,"heat":"OFF","linkquality":21,"local_temperature":4,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}'
Zigbee2MQTT:info  2024-02-21 00:59:49: MQTT publish: topic 'zigbee2mqtt/Теплый пол кухня 2', payload '{"child_lock":null,"current_heating_setpoint":25,"deadzone_temperature":null,"heat":"OFF","linkquality":21,"local_temperature":4,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}'
Zigbee2MQTT:info  2024-02-21 00:59:49: MQTT publish: topic 'zigbee2mqtt/Теплый пол кухня 2', payload '{"child_lock":null,"current_heating_setpoint":25,"deadzone_temperature":null,"heat":"OFF","linkquality":21,"local_temperature":4,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}'
Zigbee2MQTT:info  2024-02-21 00:59:49: MQTT publish: topic 'zigbee2mqtt/Теплый пол кухня 2', payload '{"child_lock":null,"current_heating_setpoint":25,"deadzone_temperature":null,"heat":"OFF","linkquality":21,"local_temperature":4,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}'
```

Dropping duplicate (debouncing) messages Z2M helps only partially, at least reducing the CPU usage of the Home Assistant server.

I wonder if it is possible to remotely restart such thermostat...

![image](https://github.com/Koenkk/zigbee2mqtt/assets/17309924/8bca1d17-aaae-4b7c-b570-948af318df8e)

In this case this is a `_TZE204_aoclfnxz` device.

**Comment by smarticz** [comment]
I also checked the power consumption at iddle 

50-70W!

This device is the worst 😭😭😭

**Comment by monqui-ulia** [comment]
Some problem with MOES BHT002/BHT006 device, _TZE204_aoclfnxz . Does anyone knows how to update firmware?

**Comment by NikitaKorneev** [comment]
> Some problem with MOES BHT002/BHT006 device, _TZE204_aoclfnxz . Does anyone knows how to update firmware?

As I understand it - Tuya and only Tuya can.

**Comment by ubombi** [comment]
That's sad. Also have this problem.  We can ask Beca (manufacturer) to fix their firmware, and share it. Via email, or whatsup/we-chat. [contact page](https://www.becaenergy.com/contact/)
```
sales@becaenergy.com
support@becaenergy.com
skype: Jingzi6789

0086-592-6151256
0086-17850149590
```

**Comment by ubombi** [comment]
Upd: Reasonable response from Beca.
> Thank you for your feedback and for sharing the link, so that we can learn about the user experience first-hand.
>
> Regarding the problem of Zigbee sending data frequently, we have learned about it and upgraded the program for the BHT-> 006GBZB model.
> 
> This problem will not occur again with the new product.
> 
> For customers who have already purchased, if you want to upgrade, you need an update tool worth $50, which is more expensive than the thermostat. It is not recommended to buy it.

Also asked for the new firmware.  Or we can for someone to dump it from a newer device.
I assume it requires a UART adapter, but deeply hope OTA is possible _(by some default Tuya mechanism)_

**Comment by 0anton** [comment]
Got similar response from Chinese representative of the producer (via
Whatsapp, can share the number if needed). Same offer: to reprogram the
devicee using some tool. I believe, anyway that a usual RS232-TTL
programmer will do the job just fine. Only need to know the attachment
points on the board and have an image / programming software. OTA was also
told to me as not possible for this kind of devices. I remember this part
of the conversation (about OTA) very well, because it somehow surprised me
a lot, that they have nothing. He relied, its costs to order the feature in
the firmware (!) and costs to maintain the infrastructure (distribution
point). I was surprised by such cost awareness and also by seeming very
complex and developed ecosystem they live in: hardware manufacturer AND a
specialist firmware developer, which charges per each feature (like OTA)
and the manufacturer carefully choose the feature set…
Still it sucks a lot to have those thermostats with chatter bug, they spam
the network a lot, affecting I believe the responsiveness of other devices,
like light-button systems (those just hang, getting unresponsive then
thermostats fires their bursts of identical messages)…

**Comment by jan0o0sch** [comment]
@0anton 
I would be very interested in a solution to flash a new firmware to these thermostats ... I have a lot of them installed and they are killing my network! I really need a solution .... thanks in advance!

**Comment by jvdburgt** [comment]
I have the same problem (2 of these thermostats on my network).

Previously, I had the same problem with Tuya presence sensors, but managed to fix this by flashing them using an ST-Link and jumper cables. Would be great if that could be done here as well.

**Comment by JagerSprinkles** [comment]
> I have the same problem (2 of these thermostats on my network).
> 
> Previously, I had the same problem with Tuya presence sensors, but managed to fix this by flashing them using an ST-Link and jumper cables. Would be great if that could be done here as well.

Can you provide a link to what you flashed them with? I have multiple of these presence sensors that constantly spam the network. I would like to try flashing a new firmware.

**Comment by jvdburgt** [comment]
> > 
> Can you provide a link to what you flashed them with? I have multiple of these presence sensors that constantly spam the network. I would like to try flashing a new firmware.

Take a coffee, put on some background music, relax, and start reading this thread: https://github.com/Koenkk/zigbee2mqtt/issues/19045#issuecomment-2581286972

Read the first 100-150 posts or so, and you know what to do ;)

**Comment by xBohlix** [comment]
> Got similar response from Chinese representative of the producer (via
> Whatsapp, can share the number if needed). Same offer: to reprogram the
> devicee using some tool. I believe, anyway that a usual RS232-TTL
> programmer will do the job just fine. Only need to know the attachment
> points on the board and have an image / programming software. OTA was also
> told to me as not possible for this kind of devices. I remember this part
> of the conversation (about OTA) very well, because it somehow surprised me
> a lot, that they have nothing. He relied, its costs to order the feature in
> the firmware (!) and costs to maintain the infrastructure (distribution
> point). I was surprised by such cost awareness and also by seeming very
> complex and developed ecosystem they live in: hardware manufacturer AND a
> specialist firmware developer, which charges per each feature (like OTA)
> and the manufacturer carefully choose the feature set…
> Still it sucks a lot to have those thermostats with chatter bug, they spam
> the network a lot, affecting I believe the responsiveness of other devices,
> like light-button systems (those just hang, getting unresponsive then
> thermostats fires their bursts of identical messages)…
> […](#)

Did you get any further with this? I have 7 of these Thermostats and they are constantly spamming my z2m network. I noticed this behaviour the first time when I opened the z2m map, where only these devices were blinking all the time, updating the LQI. Looking into my logs they are constantly sending their payload.

**Comment by Onepamopa** [comment]
Does anyone have newer firmware for the Moes thermostats? 
Zigbee Model
    TS0601
Zigbee Manufacturer
    _TZE204_aoclfnxz
Description
    Smart heating thermostat
Manufacturer
    [Moes](https://www.zigbee2mqtt.io/supported-devices/#v=Moes)
Model
    [BHT-002/BHT-006](https://www.zigbee2mqtt.io/devices/BHT-002_BHT-006.html#moes-bht-002%252Fbht-006)

Got 5 of these in my network, it's barely working......

**Comment by iJuiceman** [comment]
I have the same issue.  I have used the Throttle setting for 30.  This will only let it publish every 30 seconds.  This has made a bit of a difference to the chattyness of several of my Zigbee devices.

**Comment by Onepamopa** [comment]
There is custom firmware -- https://github.com/slacky1965/tuya_thermostat_zrd
If your thermostat is compatible - flash it. The firmware improves things a lot.

**Comment by xBohlix** [comment]
> There is custom firmware -- https://github.com/slacky1965/tuya_thermostat_zrd If your thermostat is compatible - flash it. The firmware improves things a lot.
> 
> Throttling does not help because the devices continue to spam the airwaves, the only difference is that z2m does not see the spam when you throttle it. Doesn't improve things one bit.

I cannot say how much I love you 😄!!
This is awesome! Everything worked as expected. No more chatty devices in my mqtt network. Now my other devices respond much better than before.

**Comment by jvdburgt** [comment]
I followed all steps in the firmware how-to guide. However, after I added 
```
ota:
zigbee_ota_override_index_location: local_ota_index.json
```
in the Z2M configuration.yaml file and restart Z2M, the added lines are gone from the config file. Just to be sure, I renamed the old configuration.yaml file, and uploaded a fresh one with the added lines of code. Still, one restart later and the added lines are gone again. 

Please advice.

**Comment by nocin** [comment]
@jvdburgt make sure to stop Z2M before changing the configuration.yaml, else it will be overwritten each time. At least this was my experience

**Comment by Gerhard2025** [comment]
Zigbee-Modell
TS0601
Zigbee-Hersteller
_TZE204_aoclfnxz

After successfully update and interview i tried to configuration the decice, but error "deivce cannot be configured".
The device was no longer in the z2m list and i cant make a new pairing.

z2m 2.6.1
Zigbee Herdsman Konverter Version
25.14.0
Zigbee Herdsman Version
6.0.4

Whats going wrong

**Comment by Onepamopa** [comment]
> Zigbee-Modell TS0601 Zigbee-Hersteller _TZE204_aoclfnxz
> 
> After successfully update and interview i tried to configuration the decice, but error "deivce cannot be configured". The device was no longer in the z2m list and i cant make a new pairing.
> 
> z2m 2.6.1 Zigbee Herdsman Konverter Version 25.14.0 Zigbee Herdsman Version 6.0.4
> 
> Whats going wrong

Just powercycle it. 1 of my devices also did that after FW upgrade to the custom one.

**Comment by Gerhard2025** [comment]
Thanks, but same after 1min powerless and restart.

BTW: I have 4 more identical devices that are shown in devicelist as:
(They have still the original firmware 4a)
But i cant do configuration here as well and only LQI and identify are shown

Zigbee-Modell
TS0601
Zigbee-Hersteller
_TZE204_aoclfnxz
Beschreibung
Original Tuya thermostat ready for custom Firmware update
Unterstützungsstatus
Unterstützt

IEEE-Addresse
0xa4c138dff26ff0f1
Netzwerk-Adresse
0xCABC / 51900
Hersteller
[Slacky-DIY](https://www.zigbee2mqtt.io/supported-devices/#v=Slacky-DIY)
Modell
[Original Tuya thermostat ready for update](https://www.zigbee2mqtt.io/devices/Original_Tuya_thermostat_ready_for_update.html#slacky-diy-original%2520tuya%2520thermostat%2520ready%2520for%2520update)

**Comment by Onepamopa** [comment]
Force remove? Re-pair, then try interrogation again? Mine are these:

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/f788356f-5df2-4774-97bb-d73a3d429a75" />

**Comment by Gerhard2025** [comment]
Yes that is mine too.
It doesnt work.

What about the external_converter. And the 2 Files inside.
First i skipped this point, because my z2m was 2.6.1, but without i cant see the devices in OTA.
Then i copied the external_converters/tuya_thermostat_orig.js an then the OTA works.

What about the other file there? /tuya_thermostat.js

**Comment by Onepamopa** [comment]
Just follow the instructions, that's how I did it. (note that I removed some stuff recently from there, so I can't say for sure what was what).

**Comment by Gerhard2025** [comment]
Thanks, but the device ist not working for pairing any longer.
Do you know the code for full factory reset on the device. Maybe this could help.

**Comment by PaTara43** [comment]
Hi, guys

I faced the same proble while writing a custom converter for an engo thermostat (it's tuya, basically)

The culprit was `extend: [tuya.modernExtend.tuyaBase({dp: true, forceTimeUpdates: true, timeStart: "1970"})],`


When replaced with 

```
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    extend: [tuya.modernExtend.tuyaBase({respondToMcuVersionResponse: false})],
```

I was actually for another [reason ](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/tuya.ts#L2164)but saved my network as well


p.s. The `tuya.modernExtend.tuyaBase` is necessary for time sync and schedule mode

**Comment by 0anton** [comment]
Cool finding Pavel!

So you say, setting `respondToMcuVersionResponse: false` will prevent those thermostats to flood the network with their updates? This would be indeed a great fix!

**Comment by PaTara43** [comment]
> Cool finding Pavel!
> 
> So you say, setting `respondToMcuVersionResponse: false` will prevent those thermostats to flood the network with their updates? This would be indeed a great fix!

At least for my Engo Thermostats:)

**Comment by PaTara43** [comment]
> Cool finding Pavel!
> 
> So you say, setting `respondToMcuVersionResponse: false` will prevent those thermostats to flood the network with their updates? This would be indeed a great fix!

You may want to try to make an external converter for your device copying the official one and adding the parameter

**Comment by e2drg** [comment]
> Thanks, but same after 1min powerless and restart.
> 
> BTW: I have 4 more identical devices that are shown in devicelist as: (They have still the original firmware 4a) But i cant do configuration here as well and only LQI and identify are shown
> 
> Zigbee-Modell TS0601 Zigbee-Hersteller _TZE204_aoclfnxz Beschreibung Original Tuya thermostat ready for custom Firmware update Unterstützungsstatus Unterstützt
> 
> IEEE-Addresse 0xa4c138dff26ff0f1 Netzwerk-Adresse 0xCABC / 51900 Hersteller [Slacky-DIY](https://www.zigbee2mqtt.io/supported-devices/#v=Slacky-DIY) Modell [Original Tuya thermostat ready for update](https://www.zigbee2mqtt.io/devices/Original_Tuya_thermostat_ready_for_update.html#slacky-diy-original%2520tuya%2520thermostat%2520ready%2520for%2520update)


Gerhard, I have the same same same problem. After updating I could not configure. So I removed the device. Now I cannot pair it anymore. Did you solve your problem? Has anyone any idea?

**Comment by Gerhard2025** [comment]
Hi e2drg,
Try to disconnect power (fuse) device, wait 2 minutes, then allow pairing (Zigbee), then power on the device. It should automatically pair.
Thats how slacky helped me. This worked for me.

**Comment by terragady** [comment]
As I see the custom firmware works only for Telink thermostats but Silabs are not flashable with that firmware. Is there any fix to limit the spam messages from Silabs thermostats (from MOES)?

**Comment by SPEC1AL1ST** [comment]
Same problem. Link quality spam from _TZE204_aoclfnxz
