### ISSUE TITLE
Firmware version wrong IKEA E1743

### ISSUE THREAD

**Issue by lo97** [Koenkk/zigbee2mqtt#17853]
### What happened?

The firmware version for two buttons are reported wrong. Both the firmware version and build date are wrong, since the stated version in the device "state" are the same, but the shown version in the OTA page of Zigbee2MQTT are different. Both are wrong since the update firmware date is 20230308 as for the E1812

<img width="2280" alt="Screenshot 2023-06-01 at 13 19 10" src="https://github.com/Koenkk/zigbee2mqtt/assets/56902258/c9f362f2-3f12-4277-a979-7c61400ca5e7">
<img width="676" alt="Screenshot 2023-06-01 at 13 24 17" src="https://github.com/Koenkk/zigbee2mqtt/assets/56902258/e61c3bf2-fba8-42db-8c82-e9c6d751dbd5">
<img width="674" alt="Screenshot 2023-06-01 at 13 24 11" src="https://github.com/Koenkk/zigbee2mqtt/assets/56902258/0afd2d90-02bf-4016-9265-599e571b23c1">

### Zigbee2MQTT version

1.31.0-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E

**Comment by brhahlen** [comment]
Have the same issue.
One upgraded correctly, the other is supposed to be upgraded, but is giving the wrong versions.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1798663/0743af6c-133d-4a46-a07a-abd7c922af98)

In the logs, it gives this:
`payload '{"action":null,"battery":34,"click":"","last_seen":"2023-06-01T16:10:53+02:00","linkquality":112,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'`

The correct upgraded one shows:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1798663/d303f6e5-6ba1-4861-a36f-48c45bdb1ec5)

The other one gives:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1798663/ad57ff44-29e2-498d-81c2-67def6ee939f)

**Comment by nizaga** [comment]
I have the same issue with E1757 and E1766.

Both upgraded aapparently correctly:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16460521/f487eb7d-76a0-4668-b49b-2a21114344c3)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16460521/49cc9e83-da0f-4b1c-86ff-8d99e061e7dc)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16460521/4564543f-9f9e-4b3e-87c7-58403e55c2ac)

**Comment by Koenkk** [comment]
Firmware date will never equal the `installed_version`/`latest_version`, this is expected in Zigbee (it's a different number)

**Comment by nizaga** [comment]
Thanks for your answer, then i understand E1757 is right but E1766 is not showing the new FW version.

**Comment by lo97** [comment]
But how can you explain that they're the same device, have the same firmware and are showing different numbers

**Comment by Koenkk** [comment]
From the device dev console, can you try to read the firmware date from the basic cluster? Right before doing that wakeup the device by pressing it.

**Comment by bergfalk** [comment]
One of my E1743 switches has through all updates I’ve done on it, reported the same Firmware build date. I guess the date is of the original firmware.
![bild](https://github.com/Koenkk/zigbee2mqtt/assets/31534532/951e3b45-7ab0-4f3e-8b66-388d1c836b24)

**Comment by Jo-Jo1987** [comment]
I am currently facing the same with E1743 but als with E1766 (rollerblind remote)

Can't update, one of my devices is updated. All others are not.

**Comment by brhahlen** [comment]
Activate!

**Comment by GiscardBiamby** [comment]
I have the same issue. These two devices report different firmware in the OTA page and checking for updates on the "older" one finds no updates. I purchased them at the same time so I assume they have identical hardware.

<img width="1096" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/175582/0a97fc95-5c3f-4b25-a3c1-79480f281279">

I think both have the newest FW (2.3.089) because I paired them with the IKEA gateway and the IKEA phone app said both were 2.3.089. 

Device states appear to report the same firmware version, assuming I'm interpreting the properties correctly:

```json
{
    "linkquality": 184,
    "power_on_behavior": "previous",
    "state": "ON",
    "update": {
        "installed_version": 587765297,
        "latest_version": 587765297,
        "state": "idle"
    }
}
```

```json
{
    "linkquality": 216,
    "power_on_behavior": "previous",
    "state": "ON",
    "update": {
        "installed_version": 587765297,
        "latest_version": 587765297,
        "state": "idle"
    },
    "update_available": null
}
```

**Comment by GiscardBiamby** [comment]
I also paired a [E1743](https://www.zigbee2mqtt.io/devices/E1743.html#ikea-e1743) switch and upgraded the firmware via the OTA page in zigbee2mqtt. It seems like the firmware update went OK according to the logs but the OTA page still reports the old FW version.

**Comment by sepodele** [comment]
I had the same issue with E1766. I fixed it by force removing it from Z2M, restarting the addon in HA and repaired.

**Comment by brhahlen** [comment]
Not stale

**Comment by uwen70** [comment]
I also have the problem: After updating an IKEA E1524/E1810 5-fold button from version 1.2.214 with firmware date 20170302 to version 24.4.5 from January 25th, 2023, the old version and the old date remain under OTA. However, the device reports the new version, which can be seen in the info log. Restarting the Z2M container doesn't help...
Does anyone have a suggestion for a solution?

**Comment by GiscardBiamby** [comment]
This issue is not stale. Still a problem

**Comment by henkisdabro** [comment]
I'm also facing a problem here, where the IKEA inspelning devices, bought on the same day from the same tray/batch, all had an update which I performed. Now all are showing the same update 'id' in the state information, but the OTA page in the Z2M frontend tells that the Firmware version is different on the various devices (does not reflect the actual version/id).
