### ISSUE TITLE
AM43-0.45/40-ES-EB [_TZE200_zah67ekd] Open/Close/Stop case independent.

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#17856]
### What happened?

Sending "Open', "Close" or "Stop" does not activate device.

### What did you expect to happen?

Should Open, Close or Stop.
Please make the action independent of the case sent.
Let "Open" and "OPEN" and "open" be the same, etc....

### Zigbee2MQTT version

1.31.0-dev commit: b97a09c7

### Adapter firmware version

20230507

### Adapter

TT CC1352P

**Comment by Koenkk** [comment]
Done!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by SargonofAssyria** [comment]
Perfect Tnx.
