### ISSUE TITLE
With 1.5.1.1 i can't set debug level error 

### ISSUE THREAD

**Issue by asyscom** [Koenkk/zigbee2mqtt#1786]
# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

Hello, I've hassio at latest release and zigbee2mqtt apdated. 
I need to set up un debug log but if i put under advance section the code (log_level: debug) when reload addon or restart HA the code disappear. Ive tried to put into addon code in hassii but i cant save. Ia there a method to set debug log?

**Comment by Koenkk** [comment]
Please create this issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
