### ISSUE TITLE
TS0202( _TZ3040_bb6xaihh) not supported after update to 1.31.0

### ISSUE THREAD

**Issue by Kirk1984** [Koenkk/zigbee2mqtt#17868]
### What happened?

Since the update the mentioned sensor would not show in home asssistant and after removing and repairing zigbee2mqtt says the device is not supported. It worked flawlessly before.

After rolling back to 1.30.4 (docker) it is supported and working again.

### Zigbee2MQTT version

1.31.0

### Adapter firmware version

 20230401

### Adapter

ZBDongle-P

**Comment by Koenkk** [comment]
Please check https://github.com/Koenkk/zigbee2mqtt/issues/17364#issuecomment-1571901794
