### ISSUE TITLE
after 1.31.0 KTNNKG ZB1248-10A relay incorrectly detected as TS011F_plug_1

### ISSUE THREAD

**Issue by swex** [Koenkk/zigbee2mqtt#17881]
### What happened?

[this](https://www.zigbee2mqtt.io/devices/ZB1248-10A.html) device now detected as [another one](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1). State endpoint works but as z2m trying to  reach other endpoints device acts slowly 

### Zigbee2MQTT version

1.31.0

### Adapter firmware version

20210708

### Adapter

Slaesh's adapter

**Comment by Koenkk** [comment]
Please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=wrong+device&projects=&template=wrong_device.yaml&title=%5BWrong+device%5D%3A+
