### ISSUE TITLE
[New device support]: TS0202

### ISSUE THREAD

**Issue by milandzuris** [Koenkk/zigbee2mqtt#17897]
### Link

https://vi.aliexpress.com/item/1005005099780623.html

### Database entry

*

### Comments

Hi i have one TuYa TS0202 Motion Sensor and is supported and other is look same is not supported how fix this?
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42905545/5dc64396-3361-4aa7-b13b-7d67959d5dd0)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42905545/d4b49e25-16a9-4f5e-9d6b-f183027538aa)

**Comment by Koenkk** [comment]
`_TZ3040_bb6xaihh` is supported in z2m 1.31.0

**Comment by milandzuris** [comment]
> `_TZ3040_bb6xaihh` is supported in z2m 1.31.0

i have 1.31.0-1 and nothing

**Comment by milandzuris** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42905545/90365731-712e-4081-b5c3-974bc2e6b8d0)
i dont have settings, and bad image: https://i5.walmartimages.com/asr/022424c9-e5c9-4baa-a88a-7bdeff800248.2e0697d86d6ab382c8e1b04c1d653be9.jpeg

**Comment by milandzuris** [comment]
@Koenkk

**Comment by Anashost** [comment]
@milandzuris It's already supported/fixed, and will be available in the next zigbee2mqtt update.
For now you can use this external converter which will work perfectly:
https://github.com/Koenkk/zigbee2mqtt/issues/17364#issuecomment-1566715618
