### ISSUE TITLE
[Wrong device]: 

### ISSUE THREAD

**Issue by milandzuris** [Koenkk/zigbee2mqtt#17898]
### Link

*

### Model

TS0207

### Description

Water Leak

### Vendor

TuYa

### Picture (link)

https://assets.kogan.com/images/zoestore/ZOE-S4257-1/1-cb2ae53056-s4257-1-1-4f64-diqe.jpg

### Database entry

*

### Notes

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42905545/103b0dec-6673-4a10-aefc-3926a600042b)
and dont have alarm

**Comment by Koenkk** [comment]
Fixed!
