### ISSUE TITLE
[Wrong device]: Wrong Picture for UK IKEA Smart Plug

### ISSUE THREAD

**Issue by busywait** [Koenkk/zigbee2mqtt#17927]
### Link

https://www.ikea.com/gb/en/p/tradfri-wireless-control-outlet-smart-00364477/

### Model

E1704

### Description

TRÅDFRI Wireless control outlet

### Vendor

IKEA

### Picture (link)

https://user-images.githubusercontent.com/3671165/243448501-f6b26dee-e245-4ca4-8e87-104356de3742.jpg
https://www.ikea.com/gb/en/images/products/tradfri-wireless-control-outlet-smart__0515596_pe640308_s5.jpg

### Database entry

{"id":35,"type":"Router","ieeeAddr":"0x2c1165fffea4a881","nwkAddr":31631,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI control outlet","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,8,4096,64636],"outClusterList":[25,32,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI control outlet","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20211118","swBuildId":"2.3.089"}},"genLevelCtrl":{"attributes":{"currentLevel":174}},"genOnOff":{"attributes":{"onOff":0,"startUpOnOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0c196","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0c196","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20211118","swBuildId":"2.3.089","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1466202208},"lastSeen":1685978544061,"defaultSendRequestWhen":"immediate"}

### Notes

The main picture in the IKEA pages is actually upside down - see the product page for an example of the device in use.

Also, the current catalog image looks different to my recently purchased device. I've linked a photo of my version the right way up.

**Comment by sjorge** [comment]
I don't think we can differentiate between type E (BE/FR) / F(NL/DE) / G (UK) / A (US) based on the zigbeeModel `TRADFRI control outlet` It's the same for all of them.
