### ISSUE TITLE
Zigbee2MQTT becomes unresponsive/very slow to respond every few hours

### ISSUE THREAD

**Issue by aatifk** [Koenkk/zigbee2mqtt#17923]
### What happened?

IKEA recently rolled out a firmware update ([24.4.11](https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html)) for FYRTUR blinds (E1757). Since the update, I've noticed really odd behavior with my Z2M network. Every few hours or so, the whole network goes either completely nonresponsive or very slow to respond (like a good 10 minutes between a command being sent vs the action getting carried out). I cannot see any errors in the logs, just a lack of response. Rebooting my virtual machine running Z2M temporarily solves the issue until it pops up again. This started since the blinds got the OTA update so I suspect it has something to do with that. No other variable changed in my setup.

### What did you expect to happen?

The network to continue behaving normally. 

### How to reproduce it (minimal and precise)

I don't know - apply the firmware update for the blinds I guess? 

### Zigbee2MQTT version

1.31.0 commit: f440c860

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11654856/log.txt)

**Comment by sjorge** [comment]
Probably related to https://github.com/Koenkk/zigbee2mqtt/issues/17910 I had 2 active and the spam was insane.

Switching the dev or manually updating the setting using the dev console via de frontend should hopefully help.

**Comment by sjorge** [comment]
<img width="1765" alt="Screenshot 2023-06-05 at 19 27 03" src="https://github.com/Koenkk/zigbee2mqtt/assets/379665/1fa20135-5894-49f4-b64e-db9de403ed18">
<img width="724" alt="Screenshot 2023-06-05 at 19 27 08" src="https://github.com/Koenkk/zigbee2mqtt/assets/379665/b56898b6-6461-476c-b102-57e1296db7a1">
<img width="628" alt="Screenshot 2023-06-05 at 19 27 18" src="https://github.com/Koenkk/zigbee2mqtt/assets/379665/3e4f8d74-0831-43e2-9a20-1494964d9555">

Then hit write

**Comment by sjorge** [comment]
Yes, that should stop them from spamming the network every second

**Comment by gitdanny20** [comment]
@sjorge I've attempted to apply the above fix, but Z2M appears to do nothing when I click "Write" (I also see nothing sent over the network in the Network debug tab). Any idea why the Dev Console would not be working?

**Comment by sjorge** [comment]
Only thing i can think is that the coordinator already hangs somehow.~ sjorgeOn 6 Jun 2023, at 19:53, gitdanny20 ***@***.***> wrote:﻿
@sjorge I've attempted to apply the above fix, but Z2M appears to do nothing when I click "Write" (I also see nothing sent over the network in the Network debug tab). Any idea why the Dev Console would not be working?

**Comment by aatifk** [comment]
> @sjorge I've attempted to apply the above fix, but Z2M appears to do nothing when I click "Write" (I also see nothing sent over the network in the Network debug tab). Any idea why the Dev Console would not be working?

when I applied this yesterday, this happened with one out of my four blinds. What worked for me was restarting the machine running Z2M, then kicking the culprit blind out of the network and binding it again, and then applying the new value using Dev Console. Then it worked. 

My suspicion is that a running network is spammed enough already with these check-in messages that it's not allowing you to write. See if this approach helps

**Comment by sjorge** [comment]
I guess in theory you could also take out all the batteries, and insert one, fix it, insert the next one, fix that one,...

**Comment by aatifk** [comment]
I'm always afraid of taking out the batteries from these TRADFRI blinds. Almost every time when I take them out to charge (once every few months), they take ages to get back on the network (though I don't know if the latest OTA update made it any better). But yeah, that makes sense, too (and easier)

**Comment by gitdanny20** [comment]
Taking the all the batteries out and re-adding them one at a time fixed it! I didn't even have to restart the container. Thank you, @sjorge!

**Comment by sjorge** [comment]
Good you got it stable again, how many did you have?  I have 2 active and it was pretty bad but not mesh crashing bad.


@Koenkk do we perhaps have to pull in the fyrtur/kadrilj/... genPollCtrl fix? I'm guessing people who update and have 2+ of those will have a bad time.

**Comment by gitdanny20** [comment]
I have 7 so my whole Zigbee network has been offline (or requiring frequent restarts) this week. Very glad to have finally found the fix!

**Comment by aatifk** [comment]
even my 4 had wreaked havoc - the network would require a restart about every 10 hours, so yeah, I'd say it'd be pretty horrible for anyone who has these and has applied the OTA update. 

Thank you for the quick fix though.

**Comment by Koenkk** [comment]
@sjorge you mean into a hotfix release?

**Comment by sjorge** [comment]
@Koenkk yes, pull in https://github.com/Koenkk/zigbee-herdsman-converters/pull/5838 into a hotfix release.

That should help with:
- people updating the blinds -> will get reconfigured after the update -> no spamming the mesh
- people with already updated blinds -> will get reconfigured -> eventually fixing it

For those that have too many like @gitdanny20 we can then simply tell them to remove the batteries on all of them, and then insert the batteries one-by-one and waiting for the reconfigure.

**Comment by Koenkk** [comment]
Will create a hotfix release today!

Assuming this can be closed now.
