### ISSUE TITLE
[New device support]: Paulmann RGBW wall light

### ISSUE THREAD

**Issue by fsedarkalex** [Koenkk/zigbee2mqtt#17933]
### Link

https://de.paulmann.com/p/house-led-aussenwandleuchte-smart-home-zigbee-cybo-ip44-eckig-100x100mm-rgbw-2x2-5w-2x150lm-230v-anthrazit-aluminium/94847

### Database entry

{"id":21,"type":"Router","ieeeAddr":"--REDACTED--","nwkAddr":64272,"manufId":4632,"manufName":"Paulmann Licht GmbH","powerSource":"Mains (single phase)","modelId":"RGBW","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,4111],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"RGBW","manufacturerName":"Paulmann Licht GmbH","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":2,"hwVersion":128,"swBuildId":"PBELT401"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":128,"swBuildId":"PBELT401","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1676534437},"lastSeen":1686050178278,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to create a simple converter and it seems to successfully contol one of the LEDs but the lamp has two (one facing up, one facing down). The other one always is illuminated red as soon as I sent the first command with Z2M

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['RGBW'],
    model: 'RGBW',
    vendor: 'Paulmann Licht GmbH',
    description: 'Paulmann Lamp with RGBW support',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_color(),
};

module.exports = definition;
```

### Supported color modes

RGBW

**Comment by Koenkk** [comment]
Added, Thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by fsedarkalex** [comment]
@Koenkk but as I said this seems to not work correctly

**Comment by Koenkk** [comment]
Missed that, in that case devices normally have 2 endpoints but this has only 1 (ep 242 can be ignored, it is a green power endpoint). Meaning that they probably use some proprietary commands. This has to be reverse engineered by sniffing the traffic when used with the original hub. https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by fsedarkalex** [comment]
I just ordered the original hub to sniff the traffic. I also connected my EGLO rmeote to the lamp and it acts totally weird so I guess Paulman did a mess on that lamp's firmware...

Will report back any findings once I got the hub.

Would you mind reopening this issue @Koenkk ?

**Comment by fsedarkalex** [comment]
Just wondering... besides sniffing, this is the official remote for those lamps... would this help in any way?

https://www.zigbee2mqtt.io/devices/500.67.html

**Comment by fsedarkalex** [comment]
Well... I ordered 4 of these, received two yet and I tried the second one... Seems I got delivered a defective unit... Lamp No. 2 is working wll with the converter I posted earlier...

Sorry for the confusion...

**Comment by Koenkk** [comment]
I see, added it again!

Changes will be available in the dev branch tomorrow. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
