### ISSUE TITLE
[New device support]: AwoX dimmable filament lamp ESMLFzm_w6_Dimm 

### ISSUE THREAD

**Issue by fsedarkalex** [Koenkk/zigbee2mqtt#17932]
### Link

https://www.eglo.com/ch/leuchtmittel-12226.html

### Database entry

{"id":20,"type":"Router","ieeeAddr":"---REDACTED---,"nwkAddr":52789,"manufId":4417,"manufName":"AwoX","powerSource":"Mains (single phase)","modelId":"ESMLFzm_w6_Dimm","epList":[1,3,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,768,4096,64599,10],"outClusterList":[6],"clusters":{"genBasic":{"attributes":{"modelId":"ESMLFzm_w6_Dimm","manufacturerName":"AwoX","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":1,"hwVersion":63,"swBuildId":"2.3.13_800"}},"lightingColorCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":4751,"epId":3,"devId":257,"inClusterList":[65360,65361,4],"outClusterList":[65360,65361],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":63,"swBuildId":"2.3.13_800","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1686048166715,"defaultSendRequestWhen":"immediate"}

### Comments

I created an external converter using the tutorial and it seems to work, except the "effects". Breathe starts blinking, all other effects turn the light off.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ESMLFzm_w6_Dimm'],
    model: 'ESMLFzm_w6_Dimm',
    vendor: 'AwoX',
    description: 'Dimmable filament lamp',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness(),
};

module.exports = definition;
```

### Supported color modes

only warm white, dimmable

**Comment by Koenkk** [comment]
added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
