### ISSUE TITLE
AUBESS TS000F with power management not working

### ISSUE THREAD

**Issue by FilipDem** [Koenkk/zigbee2mqtt#17935]
### What happened?

I am trying to get the https://www.zigbee2mqtt.io/devices/TS000F_power.html (Aubess Smart Switch with Power Management) working, however the does not show up in the device list. I carefully followed the discussion in https://github.com/Koenkk/zigbee2mqtt/issues/13929 and https://github.com/Koenkk/zigbee2mqtt/issues/14520.

I have other devices paired in the list (5 Tuya ZTH01 and 1 SONOFF ZBMINI2). So the whole setup is working.

Device is not showing up in the device list... Adding the external converter (don't know if it is really required), generates an error:
```
app/data/extension/externally-loaded.js:55
            .withDescription('Plug LED indicator mode'), e.child_lock(), e.switch_type_2()],
                                                                           ^

TypeError: e.switch_type_2 is not a function
    at /app/data/extension/externally-loaded.js:55:76
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:300:38)
    at loadModuleFromText (/app/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
```

### What did you expect to happen?

Aubess TS000F with power management device should show up in the device list.

### Zigbee2MQTT version

1.31.0

### Adapter firmware version

20211115

### Adapter

CC2531

**Comment by FilipDem** [comment]
Archh... I think I understood the problem... The CC2531 is flashed with the 2.1 firmware... I only have few devices... Do you think the CC2531 would be good enough with 3.0 firmware and few devices?
At term I would need to migrate to a more powerful stick...

**Comment by Koenkk** [comment]
Try removing `, e.switch_type_2()` from your external converter.

**Comment by FilipDem** [comment]
Today I installed my new coordinator SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P supporting Zigbee v3.0 with version 20230507. However the AUBESS TS000F with power management (https://zigbee.blakadder.com/Aubess_AP-SMT-Breaker02-1CH.html) is still not detected...
Any idea what could be the problem? I saw there was a correction in version 1.32 for the value of the power consumption... But it is not working at my side....

**Comment by FilipDem** [comment]
Problem found! I was triggered by a comment of you stating that the Zigbee variants of the AUBESS TS000F are no longer on Aliexpress... Although I ordered the Zigbee variant, it seems that they delivered the Wifi variant... It is a pity I loved to have the Zigbee version to keep all local...

**Comment by krumpholzb** [comment]
Hey everyone, can someone help me here. I can't get the Aubess switch integrated into the zigbee2mqtt. I press the button on the back for about 10 seconds. The blue light starts flashing, but it doesn't connect to my Sonoff dongle. I already have 10 other devices connected to zigbee2mqtt. All without any problems. Do you have to press something else on the switch?? Greetings
