### ISSUE TITLE
ptvo.switch stops working after Z2MQTT upgrade (from 1.30.4-1 to 1.31.0-1)

### ISSUE THREAD

**Issue by OskarL83** [Koenkk/zigbee2mqtt#17931]
### What happened?

Device (ptvo.switch) do not show anything more than linkquality after upgrade of Z2MQTT.
After restore from backup, to previous version of Z2MQTT, it's working again - and everything is exposed. 

### What did you expect to happen?

That the device kept working after Z2MQTT upgrade. 

### How to reproduce it (minimal and precise)

Install 1.31.0-1

### Zigbee2MQTT version

1.31.0-1

### Adapter firmware version

20211217

### Adapter

SONOFF ZigBee 3.0 USB DONGLE PLUS (TI CC2652P+CP2002N)

**Comment by Dennisd80** [comment]
Same issue, under status it only displays link quality. Contacts are not working and only action or off (general) are displayed.

**Comment by C09038** [comment]
I have the same problem.

**Comment by jvan1268** [comment]
Same issue here. Also with Sonoff stick which is on version 20220219.

Update to Zigbee2MQTT 1.31.2 did not solve the problem.
Reconfiguration of the device did not fix the problem either.

Logs display no problems. Latest log info:
2023-06-15 22:14:09MQTT publish: topic 'zigbee2mqtt/fuse box relay', payload '{"last_seen":"2023-06-15T22:14:09+02:00","linkquality":47,"state":"ON","state_action":"OFF","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF","state_l6":"OFF","state_l7":"OFF","state_l8":"OFF"}'

My board has push buttons. Manually turning on either of the 4 relays seem to trigger "state" from "OFF" to "ON". It doesn't matter which of the 4 relays and how many are turned on. "state_I1" through "state_I8" never seem to change.

**Comment by Koenkk** [comment]
@ptvoinfo I think this broke due to https://github.com/Koenkk/zigbee-herdsman-converters/pull/5792

**Comment by evilworm** [comment]
the fix does not work for me, commented in the other issue: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5894#issuecomment-1640917805

**Comment by PetrP2B** [comment]
Not stale.

**Comment by PetrP2B** [comment]
Everything works correctly in the latest version of Edge and Stable. Thanks

**Comment by OskarL83** [comment]
> Everything works correctly in the latest version of Edge and Stable. Thanks

OK. Without wipe and re-pair of devices?

**Comment by PetrP2B** [comment]
I installed the latest versions of Z2M and everything was running. I didn't have to remove and pair the device again.

**Comment by OskarL83** [comment]
> I installed the latest versions of Z2M and everything was running. I didn't have to remove and pair the device again.

Didn't work here. :-(

**Comment by PetrP2B** [comment]
It worked with the Edge version, available on 29/08/2023, but could not get to the interface, see the image above, in this version (1.33.0-dev commit: 3285850) it works correctly for me.
![obrazek](https://github.com/Koenkk/zigbee2mqtt/assets/68032446/32401bec-0ad0-4427-8609-aa21ae30a2ca)
![obrazek](https://github.com/Koenkk/zigbee2mqtt/assets/68032446/fa09b615-9b12-4edb-a9fe-8984882debb7)

**Comment by triosniolin** [comment]
I just had [one of these](https://www.tindie.com/products/a_lab_technology/zigbee-4-channel-relay) delivered and was intending to use it to monitor a few switch inputs; however, Z2M registers it as a ptvo.switch and only exposes the 4 digital outputs. A change of state on the digital inputs comes through as an `action` only, and that action is immediately overwritten by an empty string or the next thing to occur so I can't view the current state of any input.

Is there something I'm missing to get these inputs available in Z2M and therefore Home Assistant?

**Comment by OskarL83** [comment]
Not stale

**Comment by ptvoinfo** [comment]
@OskarL83 Please describe again what is not working in your case. I'm sorry, but I cannot read error messages in your language from the screenshot.

**Comment by OskarL83** [comment]
After upgrade, the multi channel relay is not working.

Before upgrade:
![Screenshot_2023-10-21-11-04-02-153_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/539fe9bb-e442-4124-98af-2ab76b542c3a)
![Screenshot_2023-10-21-11-04-27-665_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/d89d6b8b-acd7-4ae4-9a63-71301ce61297)
![Screenshot_2023-10-21-11-03-13-473_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/314cbb7f-a036-455d-93a8-618bc02c2b22)
![Screenshot_2023-10-21-11-03-28-054_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/2b640e0a-db1b-4748-8905-368f33b20e8c)

After upgrade:
![Screenshot_2023-10-21-09-08-35-832_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/b0d6dbca-1188-4c47-9bda-5c6e35b39ea3)
![Screenshot_2023-10-21-09-08-44-553_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/dec5a169-f741-480a-99ca-b35b1451fe1a)
![Screenshot_2023-10-21-09-09-23-144_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/ba2a5d88-9ef8-4ee0-b4e5-1b03715731d5)

**Comment by OskarL83** [comment]
Above was after this upgrade was done.
![Screenshot_2023-10-21-08-47-55-411_io homeassistant companion android](https://github.com/Koenkk/zigbee2mqtt/assets/80087236/3955837a-c728-4cba-91a0-69f6eea28551)
