### ISSUE TITLE
Same model Aqara switches do `action` enum differently [QBKG41LM, Aqara E1 2-Gang with neutral]

### ISSUE THREAD

**Issue by alryaz** [Koenkk/zigbee2mqtt#17946]
### What happened?

I have 7 switches model mentioned (QBKG41LM), some of which (specifically 4) do not expose their button `action` and `device_temperature` in any mode of operation.

I have so far tried all expected problem-solving attempts:
- updated coordinator firmware (jumped around between 6.7.X.X and 7.2.X.X)
- re-paired devices
- reconfigured using refresh button
- put them into all kinds of couple/decouple modes

This seems weird, as the firmware on those is identical (datecode: _06-15-2022_)

### What did you expect to happen?

Decoupling switches will at least provide `single_left` or `single_right` values for the `action` enum.

### How to reproduce it (minimal and precise)

- Start monitoring `action` enum
- Press any of the buttons
- Action gets set to `unavailable` on Home Assistant (as example) side, then back to `null`

### Zigbee2MQTT version

1.30.1

### Adapter firmware version

6.10.3

### Adapter

ZB-GW04 (USB, EZSPv8)

### Debug log

From a working device:
```
2023-06-07 19:49:24Received Zigbee message from 'Свет на кухне', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,0,101,16,1,3,40,33,5,33,4,0,154,32,0,8,33,25,1,9,33,0,12,11,32,0,10,33,0,0,12,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
2023-06-07 19:49:24lumi.switch.b2nc01: Processed buffer into data {"3":33,"5":4,"8":281,"9":3072,"10":0,"11":0,"12":1,"100":0,"101":1,"154":0}
2023-06-07 19:49:24lumi.switch.b2nc01: Processed data into payload {"device_temperature":33,"power_outage_count":3,"state_left":"OFF","state_right":"ON"}
2023-06-07 19:49:24lumi.switch.b2nc01: Processed data into payload {"device_temperature":33,"power_outage_count":3,"state_left":"OFF","state_right":"ON"}
2023-06-07 19:49:37 Received Zigbee message from 'Свет на кухне', type 'attributeReport', cluster 'aqaraOpple', data '{"223":{"data":[0,35,53,165,9,0,1,35,248,14,1,0,2,35,248,26,0,0,3,35,81,61,0,0,4,33,197,7,5,33,25,1,18,33,148,0,21,33,148,0,6,33,35,4,7,33,1,0,8,33,128,1,9,33,64,17,10,33,21,0,11,33,9,0,19,33,0,0,20,33,0,0],"type":"Buffer"}}' from endpoint 1 with groupID 0
2023-06-07 19:49:37 lumi.switch.b2nc01: unknown key 223 with value #5� #�#�#Q=!�!!�!�!#!!� !@ !! !!
Debug 2023-06-07 19:49:37lumi.switch.b2nc01: Processed data into payload {}
```
_Weirdly enough, no messages related to switches appear, but I will update the issue once encountered_

**Comment by DiukBogdan** [comment]
I've got the same proplem with my two QBKG41LM switches whitch I bought at different time.
In automatisations, trigger "...action_single_right" marked as unnown trigger


Zigbee2MQTT version
1.31.2

Adapter firmware version
20210708

Adapter
Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by jomud9** [comment]
I am not sure if it helps. However from https://github.com/Koenkk/zigbee2mqtt/issues/17477 it suggested upgrade dongle firmware "might" help.

See if it works

**Comment by dashmakov** [comment]
My Aqara E1 2 gang switch (with neutral) (QBKG41LM) connect Zigbee2MQTT Current version: 1.32.2-1 dont transmission single_left or single_right values for the action enum.

**Comment by nightmare04** [comment]
Same problem Aqara E1 2 gang dont transmission any state

**Comment by bartholomuej** [comment]
I have the same issue with both Aqara E1 2 gang and single gang sending "Empty" when pressed

**Comment by welderpb** [comment]
I have same issue with one of my QBKG41LM. The switch not emitting actions in decoupled mode. I'v tried update my dongle(Sonoff Dongle E) to different firmware and different version z2m.
The strange is that it worked normally with this dongle early.. I'v didn't change firmware and z2m version.. Just stop working..

**Comment by pawelbudynek** [comment]
The problem still exists. It's strange, the switch is pairing without any issues, you can switch it to decoupled mode, but then HA is not receiving any actions when you click the switch.
I never had this issue with previous versions of Aqara Wall Switches :(

**Comment by nightmare04** [comment]
> The problem still exists. It's strange, the switch is pairing without any issues, you can switch it to decoupled mode, but then HA is not receiving any actions when you click the switch. I never had this issue with previous versions of Aqara Wall Switches :(

for me helps to change firmware of zigbee stick, try it

**Comment by welderpb** [comment]
> > The problem still exists. It's strange, the switch is pairing without any issues, you can switch it to decoupled mode, but then HA is not receiving any actions when you click the switch. I never had this issue with previous versions of Aqara Wall Switches :(
> 
> for me helps to change firmware of zigbee stick, try it

What stick and firmware do you use?

**Comment by nightmare04** [comment]
> > > The problem still exists. It's strange, the switch is pairing without any issues, you can switch it to decoupled mode, but then HA is not receiving any actions when you click the switch. I never had this issue with previous versions of Aqara Wall Switches :(
> > 
> > 
> > for me helps to change firmware of zigbee stick, try it
> 
> What stick and firmware do you use?

SONOFF Zigbee 3.0 USB Dongle Plus and zStack3x0 version 20230507 works fine with 2 aqara switches
