### ISSUE TITLE
Update 1.31.1-1

### ISSUE THREAD

**Issue by termit0s** [Koenkk/zigbee2mqtt#17945]
### What happened?

After update 1.31.1-1 from 1.31.0-1, all buttons TS004F (TZ3000_xabckq1v) state is single/double/etc without button number.

### Zigbee2MQTT version

1.31.1-1

### Adapter firmware version

20221226

### Adapter

CC2652P

**Comment by Koenkk** [comment]
Could you check if this issue is fixed in the dev branch?. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by termit0s** [comment]
I tried it and it works normal! All buttons!

**Comment by Johnsonsons** [comment]
The Zigbee switch now only transmits the commands "single/double"
Only the button numbers are missing!

Zigbee Modell  TS0044
Wireless switch with 4 buttons

Using: zigbee2mqtt 1.31.1-1
with a request for troubleshooting 🔢

**Comment by 1shkoda1** [comment]
I have two device Zigbee Modell TS0044 on 4 buttons and Zigbee Modell TS0043 on 3 buttons. Situation the same. No working. It send singe/double command only

**Comment by Flash3dee** [comment]
> > I have two device Zigbee Modell TS0044 on 4 buttons and Zigbee Modell TS0043 on 3 buttons. Situation the same. No working. It send singe/double command only
> 
> try the edge version(1.31.0-1. Works fine. Dont forget to restart the host system -_-)

Here the same with TS0043 and TS0044 switches, rolled back to 1.31.0-1 version.
With edge version you mean the previous release 1.31.0-1?

**Comment by Fougues** [comment]
the buttons go up in action but there are systematically 2 actions which go up at the same time.
One empty and another for example 1_single.

Except that the automation sees only one, either the empty one or the other (1_single) when it sees the empty one then nothing happens.

so you can press the button and see nothing happen. it's quite random.
I couldn't find a way to resolve this.

**Comment by Flash3dee** [comment]
> the buttons go up in action but there are systematically 2 actions which go up at the same time. One empty and another for example 1_single.
> 
> Except that the automation sees only one, either the empty one or the other (1_single) when it sees the empty one then nothing happens.
> 
> so you can press the button and see nothing happen. it's quite random. I couldn't find a way to resolve this.

Hi, maybe this helps: https://github.com/home-assistant/core/issues/98739
