### ISSUE TITLE
No success adding HEIMAN CO sensor HS1CA-E 

### ISSUE THREAD

**Issue by iz3man** [Koenkk/zigbee2mqtt#1796]
I purchased a HEIMAN CO Sensor, even though it's not in the supported device list. I was hoping to be able to add it myself (didn't do it before). Guess what, i didn't have success.

This is what happened after I long pressed the pairing button:

```
New device 'undefined' with address 0x000d6f000fadaff2 connected!
MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x000d6f000fadaff2","meta":{}}'
Device with modelID 'undefined' is not supported.
Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Device with modelID 'COSensor-EM' is not supported.
Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

So I added this to fromZigbee.js

```
heiman_co: {
    cid: 'genBasic',
    type: 'devChange',
    convert: (model, msg, publish, options) => {
        console.log(msg.data)
        },
},
```

After restart of zigbee2mqtt this showed up when trying to pair

```
PM Device with modelID 'COSensor-EM' is not supported.
PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

So i added this to devices.js

```
    {
        zigbeeModel: ['COSensor-EM'], 
        model: 'HS1CA-E', 
        vendor: 'HEIMAN', 
        description: 'Heiman Samrt Carbon Monoxide Sensor', 
        supports: 'co level', 
        fromZigbee: [fz.heiman_co],
        toZigbee: [],
    },
```

Now i get this, and am stuck. 

```
PM Message without device!
PM Device with modelID 'undefined' is not supported.
PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
PM Device incoming...
PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
PM Succesfully reenabled joining
```

Can someone please help me? I guess i did everything correctly, but i want to learn to do it, as i got other devices as well that are not supported and which I want to add to the database,

Thanks

Btw: This is what i have in database.db:

{"id":13,"type":"EndDevice","ieeeAddr":"0x000d6f000fadaff2","nwkAddr":21144,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"COSensor-EM","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[],"clusters":{}}},"_id":"xbBFL2KEQ6tGbClH"}

**Comment by Koenkk** [comment]
This device is already supported: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L3571 (switch to zigbee2mqt dev branch).

**Comment by iz3man** [comment]
LOL :) Great. Thanks. Still I'd liked to add it myself. Is someone willing to lead me through the process? There might be other products in the future where i may need to add them by myself.

**Comment by Koenkk** [comment]
Process differs per devices, but main guidelines can be found here: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
