### ISSUE TITLE
E1743 super powered at 200% battery level

### ISSUE THREAD

**Issue by Gonioul** [Koenkk/zigbee2mqtt#17963]
### What happened?

200% level battery since recent update

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

**Comment by Gonioul** [comment]
![Screenshot_20230608_221833](https://github.com/Koenkk/zigbee2mqtt/assets/64291573/2869a41c-e0fe-4d1f-8464-a500faf101ad)

**Comment by Gonioul** [comment]
Note that the firmware version is also wrong. It was updated recently.

**Comment by sjorge** [comment]
The battery info is wrong because for ikea we decide if we should divide or not based on the fw version.

You can try rereading it via the dev console in the frontend. It's on genBasic swBuildId (i think)
