### ISSUE TITLE
WXKG01LM Xiaomi not showing payload 

### ISSUE THREAD

**Issue by boxgr0ve** [Koenkk/zigbee2mqtt#1797]
# Bug Report
When clicking a button the Xiaomi MiJia wireless switch on version 1.1.0.1 it would display the payload, single_click, double_click etc etc however on version 1.5.1.1 it displays blank in the sensor view.   Automations using single, double still work but it would be nice to be able to see the state on the sensors.

**Comment by Koenkk** [comment]
Unfortunately not possible (with `homeassistant: true` in `configuration.yaml`), otherwise the home assistant automations won't work anymore. (see https://github.com/Koenkk/zigbee2mqtt/issues/959#issuecomment-480341347).
