### ISSUE TITLE
GLEDOPTO GL-B-007P add PowerOnBehavior

### ISSUE THREAD

**Issue by deaxx** [Koenkk/zigbee2mqtt#17970]
### What happened?

There is no PowerOnBehavior in the converter

{
        zigbeeModel: ['GL-B-007P'],
        model: 'GL-B-007P',
        vendor: 'Gledopto',
        ota: ota.zigbeeOTA,
        description: 'Zigbee 6W E26/E27 Bulb RGB+CCT (pro)',
        extend: gledoptoExtend.light_onoff_brightness_colortemp_color({**_disablePowerOnBehavior: false_** }),
    },

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

20230507

### Adapter

СС2652P

**Comment by Koenkk** [comment]
Does it work after this change?

**Comment by deaxx** [comment]
> Does it work after this change?

works great

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
