### ISSUE TITLE
Growing instability in my network

### ISSUE THREAD

**Issue by jerome6994** [Koenkk/zigbee2mqtt#17987]
### What happened?

Good evening
I come to you this evening because I have more and more instability on my zigbee network made up of 195 devices (77 routers and 118 end devices of all brands but mainly Xiaomi aqara, HUE, ADEO, IKEA, BLITZWOLF, PROFALUX and NOUS)
My key is a conbee 2 with the latest firmware installed on it and channel 11 since the beginning of z2m
I have a 2 meter extension but that I just put on but I had a 1 meter extension before.
I'm on a NUC8iEBEH server under proxmox with a Docker VM and my z2m has been a container alongside zwavejs UI and mosquitto for a very long time.

My home automation system then is Home Assistant and Node Red for some of my automations.
Since the December 2022 update it's the beginning of instability but manageable but since the last update in early June it's impossible it's almost 10% of the network every day which seems functional but which does not is actually not! Conversely we see devices that are offline when they work really well

I don't really know what to do to regain stability at the top of December 2022!
I always get messages like this:
![IMG_20230610_213121](https://github.com/Koenkk/zigbee2mqtt/assets/66921143/a3423de8-ff3f-4a38-a963-909d4b1f0a12)
![IMG_20230610_213150](https://github.com/Koenkk/zigbee2mqtt/assets/66921143/cf502b9e-87a4-4772-bbc3-df7189d3b8c4)

on devices that I have deleted, I still see error messages even though I no longer have any traces in the configuration.yaml for example.

Is there a way to have a complete clean of my network without having to redo everything at the appears level?

Why suddenly the network would be less good today than yesterday? I haven't had a new neighbor for a while. My Wifi network was changed a little over a month ago with Unifi terminals (UAP AC Pro and U6 LR+) instead of the ORBI Netgear terminal.

I hope you will have a tip to help me at least do a clean install without having to redo everything but having done as much cleaning as possible of the residual trace of my old network and that it will work.

At worst is there a trick to migrate to a clean and new installation with a Sonoff Dongle P USB key?

thanking you for the time to read and analyze

hoping to read you soon

### Zigbee2MQTT version

1.31.2 commit: 21f5125

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11713163/log.txt)

**Comment by tech2mar** [comment]
The same thing happened to me and I don't know how to fix it. I deleted some devices and they are still in the logs, very strange, everything was fine for over 1 year. Now it keeps losing connection to the devices every 14 days.
