### ISSUE TITLE
[New device support]: please add 929003128401

### ISSUE THREAD

**Issue by KHOne23** [Koenkk/zigbee2mqtt#17981]
### Link

https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-tragbare-tischleuchte-hue-go/8719514404571

### Database entry

{"id":67,"type":"Router","ieeeAddr":"0x001788010cb94296","nwkAddr":2681,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003128401","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003128401","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1686397048980,"defaultSendRequestWhen":"immediate"}

### Comments

could you please add Support for 929003128401 is the white variant of 929003128501. All other Setting are same.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const philips = require('zigbee-herdsman-converters/lib/philips');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
     zigbeeModel: ['929003128401'],
     model: '929003128401',
     vendor: 'Philips',
     description: 'Hue Go portable table lamp white',
     extend: philips.extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
