### ISSUE TITLE
Extend Xiaomi power plug device values

### ISSUE THREAD

**Issue by jwillmer** [Koenkk/zigbee2mqtt#18]
The power plug can also transmit current energy consumption. Is it possible to add this?

**Comment by Koenkk** [comment]
This is already supported, after a few seconds of turning the plug on this is reported.

**Comment by jwillmer** [comment]
Cool, can you update the docs for it? https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices

**Comment by Koenkk** [comment]
Its already there, right? Xiaomi Mi power plug ZigBee (on/off, power measurement)

**Comment by jwillmer** [comment]
It is, might have managed to only read on/off the last time I checked.

**Comment by Koenkk** [comment]
Cool!
