### ISSUE TITLE
Corrections for the language selection menu

### ISSUE THREAD

**Issue by hostibus-morte** [Koenkk/zigbee2mqtt#18009]
### What happened?

In the language selection menu all languages are written in their own languages except Turkish (Türkçe), Danish (Dansk) and Norwegian (Norsk). Also the Danish flag icon is not the danish flag, but rather seems like it's a placeholder icon.

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

26660700

### Adapter

ConBee 2

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
