### ISSUE TITLE
LifeControl MCLH-04

### ISSUE THREAD

**Issue by ChapayTv** [Koenkk/zigbee2mqtt#18007]
### What happened?

Battery level always shows 50%

### Zigbee2MQTT version

1.31.2-1

### Adapter firmware version

20221031195840-if00

### Adapter

usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by ChapayTv** [comment]
> ### What happened?
> Battery level always shows 50%
> 
> ### What did you expect to happen?
> _No response_
> 
> ### How to reproduce it (minimal and precise)
> _No response_
> 
> ### Zigbee2MQTT version
> 1.31.2-1
> 
> ### Adapter firmware version
> 20221031195840-if00
> 
> ### Adapter
> usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2
>

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by ChapayTv** [comment]
> Fixed!
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Thanks, I'll be waiting for the general release.
