### ISSUE TITLE
Impossible de faire la mise à jour

### ISSUE THREAD

**Issue by Fafitude** [Koenkk/zigbee2mqtt#18010]
### What happened?

Bonjour,
Lorsque j'essaie de faire la dernière mise à jour j'ai cette erreur 
cp: impossible de créer le répertoire 'data-backup/data/data/data/data/log/2021-12-02.16-56-11': Aucun espace               disponible sur le périphérique

Un idée du problème ?

Merci d'avance.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

24c6b2e2

### Adapter

conbee2

**Comment by Wikibear** [comment]
if you are root you can delete everything you want. but be carefully. check it via search engine. that has nothing to do with z2m issue.
