### ISSUE TITLE
[Wrong device]: TS0121 _TZ3000_8nkb7mof

### ISSUE THREAD

**Issue by rufabf** [Koenkk/zigbee2mqtt#18012]
### Link

https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121-plug

### Model

TS0121  _TZ3000_8nkb7mof

### Description

Plug

### Vendor

Blitzwolf

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/TS0121_plug.jpg

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0x00124b0022d4c386","nwkAddr":15322,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee","epList":[1],"endpoints":{"1":{"profId":49246,"epId":1,"devId":16,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"SA-003-Zigbee","manufacturerName":"eWeLink"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":5,"hwVersion":1,"dateCode":"20201207","swBuildId":"1.0.5","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1686676031525,"defaultSendRequestWhen":"immediate"}

### Notes

the model printed in the plug is XH-002P

**Comment by Koenkk** [comment]
I think you posted the wrong database.db entry, I don't see `TS0121` or `_TZ3000_8nkb7mof`

**Comment by rufabf** [comment]
This is the

> I think you posted the wrong database.db entry, I don't see `TS0121` or `_TZ3000_8nkb7mof`

This is the model that zigbee2mqtt show

**Comment by Koenkk** [comment]
Yes, but the database.db entry you posted doesn't match that (`"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee"`). Please post your complete data/database.db file.

**Comment by rufabf** [comment]
> Yes, but the database.db entry you posted doesn't match that (`"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee"`). Please post your complete data/database.db file.

Thats the model that z2m think it is, i have 2 same plugs one is right and the other it shows like ewelink 

`{"id":1,"type":"Coordinator","ieeeAddr":"0x847127fffec9a54c","nwkAddr":0,"manufId":0,"epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":48879,"inClusterList":[0,3,6,10,25,26,768],"outClusterList":[0,3,4,5,6,8,32,768,1024,1026,1029,1030,1280,2817,2819,2820,1794,4096,64513,64514],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":1686763426494,"defaultSendRequestWhen":"immediate"}
{"id":2,"type":"EndDevice","ieeeAddr":"0x00124b0022eae12c","nwkAddr":46680,"manufId":0,"manufName":"eWeLink","powerSource":"Battery","modelId":"WB01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,3,1],"outClusterList":[6,3],"clusters":{"genBasic":{"attributes":{"modelId":"WB01","manufacturerName":"eWeLink","powerSource":3,"zclVersion":0,"appVersion":5,"hwVersion":0,"dateCode":"20201026"}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryPercentageRemaining":200}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":7200,"repChange":0},{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":7200,"repChange":0}],"meta":{}}},"appVersion":5,"hwVersion":0,"dateCode":"20201026","zclVersion":0,"interviewCompleted":true,"meta":{"configured":956609490},"lastSeen":1686761099923,"defaultSendRequestWhen":"immediate"}
{"id":3,"type":"Router","ieeeAddr":"0x842e14fffe13bd57","nwkAddr":24614,"manufId":4098,"manufName":"_TZ3000_odygigth","powerSource":"Mains (single phase)","modelId":"TS0505A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505A","manufacturerName":"_TZ3000_odygigth","powerSource":1,"zclVersion":3,"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":29}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1686756922125,"defaultSendRequestWhen":"immediate"}
{"id":4,"type":"EndDevice","ieeeAddr":"0x04cf8cdf3c7ca897","nwkAddr":14135,"manufId":4718,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sen_ill.mgl01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":262,"inClusterList":[0,1024,3,1],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.sen_ill.mgl01","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20191118","swBuildId":"2019\u0000www."}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":26929}},"genPowerCfg":{"attributes":{"batteryVoltage":29}}},"binds":[{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1024,"attrId":0,"minRepIntval":15,"maxRepIntval":3600,"repChange":500}],"meta":{}}},"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20191118","swBuildId":"2019\u0000www.","zclVersion":3,"interviewCompleted":true,"meta":{"configured":855622161},"lastSeen":1686763834101,"defaultSendRequestWhen":"immediate"}
{"id":5,"type":"EndDevice","ieeeAddr":"0xa4c138886c1f741a","nwkAddr":9234,"manufId":4417,"manufName":"_TZ3000_oxslv1c9","powerSource":"Battery","modelId":"TS0203","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[3,4,5,6,8,4096,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0203","manufacturerName":"_TZ3000_oxslv1c9","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x847127fffec9a54c","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":166,"batteryVoltage":27}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-305470159},"lastSeen":1686762926240,"defaultSendRequestWhen":"immediate"}
{"id":6,"type":"EndDevice","ieeeAddr":"0xa4c13850c9837670","nwkAddr":35247,"manufId":4417,"manufName":"_TZ3000_mcxw5ehu","powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,3,0],"outClusterList":[4096,6,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0202","manufacturerName":"_TZ3000_mcxw5ehu","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x847127fffec9a54c","zoneState":1,"currentZoneSensitivityLevel":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":29}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1833546852},"lastSeen":1686763025930,"defaultSendRequestWhen":"immediate"}
{"id":7,"type":"Router","ieeeAddr":"0x60a423fffe7ff880","nwkAddr":57257,"manufId":4098,"manufName":"_TZ3000_8nkb7mof","powerSource":"Mains (single phase)","modelId":"TS0121","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_8nkb7mof","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,5101]}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1,"rmsVoltage":231,"rmsCurrent":0,"activePower":0}},"genOnOff":{"attributes":{"onOff":0,"moesStartUpOnOff":0,"tuyaBacklightMode":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]},{"cluster":2820,"attrId":1285,"minRepIntval":5,"maxRepIntval":3600,"repChange":5},{"cluster":2820,"attrId":1288,"minRepIntval":5,"maxRepIntval":3600,"repChange":50},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":10}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-814849522},"lastSeen":1686763000636,"defaultSendRequestWhen":"immediate"}
{"id":8,"type":"Router","ieeeAddr":"0x00124b0022d4c386","nwkAddr":15322,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee","epList":[1],"endpoints":{"1":{"profId":49246,"epId":1,"devId":16,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"SA-003-Zigbee","manufacturerName":"eWeLink"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":5,"hwVersion":1,"dateCode":"20201207","swBuildId":"1.0.5","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1686763947331,"defaultSendRequestWhen":"immediate"}
{"id":9,"type":"EndDevice","ieeeAddr":"0xa4c1380b9b56f328","nwkAddr":9171,"manufId":4417,"manufName":"_TZE200_m9skfctm","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"W1\u001c,\u0011","65506":56,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_m9skfctm","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1686737448203,"defaultSendRequestWhen":"immediate"}
{"id":10,"type":"EndDevice","ieeeAddr":"0x187a3efffe1511dd","nwkAddr":53792,"manufId":4098,"manufName":"_TZ3290_ot6ewjvmejq5ekhl","powerSource":"Battery","modelId":"TS1201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":61440,"inClusterList":[0,4,5,3,1,60672,57348,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS1201","manufacturerName":"_TZ3290_ot6ewjvmejq5ekhl","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryVoltage":15,"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1458185820},"lastSeen":1686758877060,"defaultSendRequestWhen":"immediate"}
{"id":11,"type":"EndDevice","ieeeAddr":"0xdc8e95fffeaa8949","nwkAddr":51041,"manufId":4098,"manufName":"_TZ3000_qja6nq5z","powerSource":"Battery","modelId":"TS004F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[0,1,3,4,6,4096],"outClusterList":[25,10,3,4,5,6,8,4096],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\f\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0012","65506":31,"65508":1,"65534":0,"modelId":"TS004F","manufacturerName":"_TZ3000_qja6nq5z","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"tuyaOperationMode":1}},"manuSpecificTuya_3":{"attributes":{}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x847127fffec9a54c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-429758583},"lastSeen":1686759922191,"defaultSendRequestWhen":"immediate"}`

**Comment by rufabf** [comment]
> I see, if `SA-003-Zigbee` is used as the modelID we cannot distinguish it (since both manufactur name and modelID are the same).

Then how can i modify the ID to use the correct model? 
XH-002P [](https://zigbee.blakadder.com/Tuya_XH-002P.html) 
![IMG_20230614_080718_658](https://github.com/Koenkk/zigbee2mqtt/assets/22416877/1f5c004b-e371-4c86-977d-4252406fd8a3)

With `SA-003-Zigbee` only can on and off there is no power monitor

**Comment by Koenkk** [comment]
> This is the
> 
> 
> 
> > I think you posted the wrong database.db entry, I don't see `TS0121` or `_TZ3000_8nkb7mof`
> 
> 
> 
> This is the model that zigbee2mqtt show 

Where does it show this, can you make a screenshot?

**Comment by rufabf** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/22416877/5e4c3dfa-43b8-416a-8bfd-044cd742e056)The number 3 should be like 2, both where buys at the same time but z2m treated like different

**Comment by Koenkk** [comment]
I think you got 2 different devies but with the same housing. Looking at the inClusterList from the OP, this device does not support electrical measurements.

**Comment by rufabf** [comment]
> I think you got 2 different devies but with the same housing. Looking at the inClusterList from the OP, this device does not support electrical measurements.

Ahh ok, thanks anyway
