### ISSUE TITLE
Three connections on graph

### ISSUE THREAD

**Issue by abmantis** [Koenkk/zigbee2mqtt#1802]
# Bug Report
## What happened
There are three routes between some devices:
![image](https://user-images.githubusercontent.com/974569/62252202-0b9bf480-b3ea-11e9-9f6f-4681b9d63cc3.png)

## What did you expect to happen
Only two connections.

## How to reproduce it (minimal and precise)
Not sure, it just happens.

## Debug Info
zigbee2mqtt version: dev
CC253X firmware version: 20190223

**Comment by Koenkk** [comment]
@clockbrain could you help with this?

**Comment by clockbrain** [comment]
Only a guess but its possible some lqi or route requests from one network scan are still outstanding when later network map scan starts so it collects those results from different scans all together in the one map.

@abmantis how many devices do you have? have you changed the default queue settings? how frequently are you requesting a network map?

**Comment by abmantis** [comment]
@clockbrain  I have 10 devices. I have not changed the queue settings. I don't have it updating automatically ATM. I just update it manually when I want to check it.

**Comment by Woodcat64** [comment]
This happened to me as well
zigbee2mqtt version: 1.5.1.1
CC2531_DEFAULT_20190608

![3lines](https://user-images.githubusercontent.com/50119854/62336765-d6ea7480-b49f-11e9-96d2-66144c9b8cb4.PNG)

**Comment by clockbrain** [comment]
@abmantis & @Woodcat64 are either of you using Admin Panel for Node-Red because that by default triggers a network map request every 30 seconds?

If that regular Node-Red request happens in the background and overlaps with a manually triggered map request then I can see how the results might get mangled.

**Comment by abmantis** [comment]
@clockbrain no, no automatic updates here (and I can be sure of that because of the timestamp on the graph).

**Comment by Woodcat64** [comment]
@clockbrain, no automatic  updates here as well. After z2m restart, all is back to normal.

**Comment by renedis** [comment]
Same story here. HA auto refreshes the map every 10 minutes with an automation.

Currently 38 devices.
zigbee2mqtt version: 1.5.1.1
CC2530_CC2591_SOURCE_ROUTING_20190619

![2019_08_06_09_47_01_](https://user-images.githubusercontent.com/10537789/62521822-a9e7ea00-b830-11e9-897d-75b214d02578.png)

**Comment by clockbrain** [comment]
Can anyone provide a log file with debug so I can figure out what is causing this. At the moment I can only make a guess as I don't see this on my network map.

Is it repeatable or only a very rare occurrence?
