### ISSUE TITLE
LiXee Zlinky: energy values get stuck after a random time

### ISSUE THREAD

**Issue by eekamouze** [Koenkk/zigbee2mqtt#18022]
### What happened?

I'm using a Zlinky device for a couple of months now and I found in HA that energy graphs stopped being updated many times. Looking at the log attached we can clearly see that at some point the value (current_tier2_summ_delivered in this sample) get stuck while there is still energy consumption. Also the MQTT publish pattern changes (less frequent). This happens from a few hours to a couple of days after zigbee2mqtt is running and the only way I found to solve the issue is to restart zigbee2mqtt.

### What did you expect to happen?

zigbee2mqtt should publish an increasing value while there is still power consumption

### How to reproduce it (minimal and precise)

Just wait until it happens

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E (EFR32MG21)

### Debug log

Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.088,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.088,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.088,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.088,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.088,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:37:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

Zigbee2MQTT:info  2023-06-14 09:38:11: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.113,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-06-14 09:38:26: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

###############################
###############################

Zigbee2MQTT:info  2023-06-14 09:39:12: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1440,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":156,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

Zigbee2MQTT:info  2023-06-14 09:40:12: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1450,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":156,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

Zigbee2MQTT:info  2023-06-14 09:41:12: MQTT publish: topic 'zigbee2mqtt/Linky', payload '{"active_register_tier_delivered":"HP..","apparent_power":1430,"available_power":45,"current_tarif":"HC..","current_tier1_summ_delivered":11180.833,"current_tier2_summ_delivered":24297.139,"linkquality":176,"meter_serial_number":"#############","rms_current":6,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'

**Comment by mr2c12** [comment]
I suffer from a similar issue (with an Innr smart plug).
In my case, it seems that hitting the refresh button on the consumption value fix it.
Does it works for you?
