### ISSUE TITLE
General question: Running multiple zigbee2mqtt instances

### ISSUE THREAD

**Issue by pvzweden** [Koenkk/zigbee2mqtt#1803]
Hi,

More of a general question.
I'm trying to use zigbee2mqtt with multiple cc2531 sniffers by means of running multiple instances. My idea is to have every instance running with a separate sniffer, instances run on 1 machine but communicate via ser2net <--> socat with the sniffers.

Would this be feasible? Or will I be running into strange results? Because I don't think zigbee2mqtt supports reading from multiple devices right? (I can for example bundle them via socat into one device, but I think every sniffer needs it's proper init sequence)

Oh, and all zigbee2mqtt instances would be talking to the same mqtt server

Patrick

**Comment by Koenkk** [comment]
1 coordinator = 1 zigbee2mqtt instance, if for some reason you want to use multiple coordinators (note that these will all be different networks)  you have to setup multiple zigbee2mqtt instances (can be done on same pc).

Note that the issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.
