### ISSUE TITLE
TS000F_power wrong current

### ISSUE THREAD

**Issue by timewolf** [Koenkk/zigbee2mqtt#18041]
### What happened?

hi
i've a Zigbee Smart switch with power metering (on zigbee2mqtt it shows as TS000F_power) that have a wrong "current" value, i got 200A..and it's wrong

### Zigbee2MQTT version

1.31.2 commit: 21f5125

### Adapter firmware version

6.10.3.0 build 297

### Adapter

sonoff zb

![current](https://github.com/Koenkk/zigbee2mqtt/assets/44172693/cf307392-ce84-49e7-9147-dba5393970e5)

**Comment by Koenkk** [comment]
It seems the current needs to be divided by 2000. When you connect a higher load, e.g. 100 watt, is the current +- 5x higher?

**Comment by timewolf** [comment]
i will connect some higher and test...now there is only a sky decoder :)

**Comment by timewolf** [comment]
ok i got the point, i've added to tuya, it's mA no A.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/44172693/67b9c546-8efd-4f37-b293-f9888f5c1e15)

**Comment by Koenkk** [comment]
So the value show in z2m should be divided by 1000?

**Comment by timewolf** [comment]
yes

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
