### ISSUE TITLE
Osram LEDVANCE SubstiTUBE Connected Advanced Ultra Output ST8EM-CON

### ISSUE THREAD

**Issue by saschaludwig** [Koenkk/zigbee2mqtt#18087]
### Link

https://www.ledvance.de/professional/produkte/lampen/led-rohren/osram--led-rohren/led-rohre-fur-elektromagnetische-vorschaltgerate-funktionieren-mit-den-connected-sensoren/led-rohre-fur-elektromagnetische-vorschaltgerate-funktionieren-mit-den-connected-sensoren-c7065?productId=117615

### Database entry

{"id":109,"type":"Router","ieeeAddr":"0xf0d1b8000025b80b","nwkAddr":48588,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"Connected Tube Value II","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Connected Tube Value II","manufacturerName":"LEDVANCE","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"02116550"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"02116550","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1687441798582,"defaultSendRequestWhen":"immediate"}

### Comments

I have a ST8EM-CON which isn't currently supported.

I added this below ext converter, and I can now switch the light on/off, change brightness and use effects.
But changing or querying _power_on_behavior_ results is a `failed (Status 'UNSUPPORTED_ATTRIBUTE')` error.

Can I supply more information, so this device will be added?

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Connected Tube Value II'],
    model: 'ST8EM-CON',
    vendor: 'LEDVANCE',
    description: 'SubstiTUBE Connected Advanced Ultra Output',
    extend: extend.light_onoff_brightness(),
};
```

**Comment by Koenkk** [comment]
Added! I've disabled the power on behaviour since the device doesn't support it.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
