### ISSUE TITLE
[Wrong device]: IH-K009

### ISSUE THREAD

**Issue by flbderks** [Koenkk/zigbee2mqtt#18098]
### Link

https://nl.aliexpress.com/item/1005003895106356.html?spm=a2g0o.order_list.order_list_main.217.319779d2J6Ttbh&gatewayAdapt=glo2nld

### Model

ZTH01 / ZTH02

### Description

Temperature & Humitidy sensor

### Vendor

Tuya

### Picture (link)

https://ae01.alicdn.com/kf/Sb7619cb4331b4a8f9b110a68d087ddc2k/Tuya-Zigbee-Smart-Temperatuur-Vochtigheid-Sensor-Hygrometer-Thermometer-Detector-Smart-Leven-Afstandsbediening-Met-Alexa-Google-Thuis.jpg_640x640.jpg

### Database entry

{"id":44,"type":"EndDevice","ieeeAddr":"0xa4c1380d91143be7","nwkAddr":30912,"manufId":4417,"manufName":"_TZ3000_0s1izerx","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,3,1026,1029,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0018\u0000\u0000\u0000\u0012�\u0000\u0000\u0000\u0012","65506":51,"65508":0,"65534":0,"modelId":"TS0201","manufacturerName":"_TZ3000_0s1izerx","powerSource":3,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":138,"batteryVoltage":28}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2838}},"msRelativeHumidity":{"attributes":{"measuredValue":3947}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1687533877467,"defaultSendRequestWhen":"immediate"}

### Notes

Zigbee2mqtt is not giving the proper model outcome

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
