### ISSUE TITLE
Dev Console No longer able to enter values

### ISSUE THREAD

**Issue by ur7x** [Koenkk/zigbee2mqtt#18093]
### What happened?

I attempted to use the Dev Console to update values on my IKEA blinds (to change polling values)

Device -> Dev Console -> Cluster (GenPollCtrl) -> Attribute (CheckInterval) 

This used to result in an input box where I could enter an integer value to be written to the device.

Now the system just offers a small box with an up and a down arrow. 
 

### What did you expect to happen?

I expected the integer input box

### How to reproduce it (minimal and precise)

Select a Zigbee Device...

Then follow

Device -> Dev Console -> Cluster (GenPollCtrl) -> Attribute (CheckInterval) 

### Zigbee2MQTT version

Current version: 1.31.2-1

### Adapter firmware version

20211217

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by Koenkk** [comment]
Please submit issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend/issues
