### ISSUE TITLE
[Wrong device]: 

### ISSUE THREAD

**Issue by vinmar1** [Koenkk/zigbee2mqtt#18102]
### Link

https://www.amazon.com/MHCOZY-Channel-Bluetooth-Wireless-Contact/dp/B09M6HTDVS/ref=sr_1_10?crid=139C8KO6BJSMM&keywords=zigbee+relay+4+channel&qid=1687547527&sprefix=zigbee+relay%2Caps%2C106&sr=8-10

### Model

TYWB 4ch-RF

### Description

4 Channel Relay

### Vendor

MHCOZY (TUYA)

### Picture (link)

https://sc04.alicdn.com/kf/Hf8889c224ea848d5b3786dd8abdb2ce0T.jpg

### Database entry

{"id":32,"type":"Router","ieeeAddr":"0xa4c1389797375c51","nwkAddr":42507,"manufId":4417,"manufName":"_TZ3000_u3oupgdy","powerSource":"Mains (single phase)","modelId":"TS0004","epList":[1,2,3,4,242],"e                      ndpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�?�+\u0012","65506":48,"65508":0,"6553                      4":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_u3oupgdy","zclVersion":3,"appVersion":80,"modelId":"TS0004","powerSource":1}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAABAAABg                      AA"}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior                      ":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b84a95","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inC                      lusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[{"cluster                      ":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b84a95","endpointID":1}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[4,5,6,57345],"outClusterLis                      t":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress                      ":"0x00124b0026b84a95","endpointID":1}],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":256,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attribute                      s":{"onOff":1,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b84a95","endpointID":1}],                      "configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":80                      ,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":889996980},"lastSeen":1687545876734,"defaultSendRequestWhen":"immediate"}

### Notes

Seems to work fine but is definitely not identified correctly. I believe it was correct in version 1.31.0

**Comment by Koenkk** [comment]
Fixed, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
