### ISSUE TITLE
[Feature request]: Integration of Solum E-INK displays / dmitry firmware

### ISSUE THREAD

**Issue by slimline33** [Koenkk/zigbee2mqtt#18104]
### Is your feature request related to a problem? Please describe

Integration of Solum E-INK displays (electronic price tags)

It would be great if the EPS displays could be integrated into the zigbee system.

https://github.com/jjwbruijn/OpenEPaperLink

![IMG_20230623_170342](https://github.com/Koenkk/zigbee2mqtt/assets/3323812/dabda3b7-fae3-406a-bc69-b694518e7ef6)
![IMG_20230623_152140](https://github.com/Koenkk/zigbee2mqtt/assets/3323812/f02fd32a-9711-4388-b66a-369688cb7dd9)
![IMG_20230623_162414](https://github.com/Koenkk/zigbee2mqtt/assets/3323812/d0c9867f-ed32-436a-a45d-cdbe57ae3a05)
![IMG_20230623_144430](https://github.com/Koenkk/zigbee2mqtt/assets/3323812/04ba463f-800c-4b31-8d68-5eef3cf5b2d9)

### Describe the solution you'd like

Addressing via zigbee mqtt with templates for different values

### Describe alternatives you've considered

Nothing

### Additional context

Nothing

**Comment by timoknapp** [comment]
@slimline33 did you make zigbee2mqtt work with those price tags? I have also a couple of them and would be interested too.

@Koenkk ever played around with those tags?

**Comment by slimline33** [comment]
@timoknapp No, the displays transmit via Zigbee, but use a different protocol. An extra Zigbee coordinator is absolutely necessary!

**Comment by timoknapp** [comment]
@slimline33 thanks for the details. I do already have a dedicated AP for the price tags but I am currently unhappy with the network coverage of the price tags within my home. I was therefore wondering if I could leverage the existing smart home ZigBee network to extend the ZigBee network of my price tags. Do you have any idea on improving signal quality?

**Comment by slimline33** [comment]
@timoknapp

What kind of access point are you using? You can use several displays with one esp32 s3, then they will mesh the display network! Why don't you join the oepl discord group, they will be happy to help!
