### ISSUE TITLE
[Wrong device]: 

### ISSUE THREAD

**Issue by vinmar1** [Koenkk/zigbee2mqtt#18107]
### Link

https://www.amazon.com/MHCOZY-Adjustable-Momentary-Interlock-SmartThings/dp/B08YY7XFS3/ref=sr_1_1_sspa?crid=13ESVSEWZK3XZ&keywords=ewelink+ZB-SW02&qid=1687619668&sprefix=ewelink+zb-sw02%2Caps%2C68&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1

### Model

ZB-SW02

### Description

2 Channel 5V 12V ZigBee Smart Relay Switch

### Vendor

MHCOZY (eWeLink)

### Picture (link)

https://forum.arturhome.pl/uploads/default/original/2X/9/90d12fc77fa8a0e59c4e3a53cd46460bea2e4bb0.jpeg

### Database entry

{"id":38,"type":"Router","ieeeAddr":"0x00124b002459afb7","nwkAddr":53836,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"ZB-SW02","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{"modelId":"ZB-SW02","manufacturerName":"eWeLink","powerSource":1,"zclVersion":1,"appVersion":8,"hwVersion":1,"dateCode":"20210703","swBuildId":"1.0.7"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b84a95","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b84a95","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":8,"hwVersion":1,"dateCode":"20210703","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1687617787854,"defaultSendRequestWhen":"immediate"}

### Notes

Seems to operate okay but some descriptions changed after last update.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
