### ISSUE TITLE
Add support for GE PSB19-SW27

### ISSUE THREAD

**Issue by mebrunner24** [Koenkk/zigbee2mqtt#1812]
I'm not sure if this is the correct place to add this, but I have successfully added integration of the GE Link PSB19-SW27 A19 bulb. 

devices.js:
`    {
        zigbeeModel: ['SoftWhite'],
        model: 'PSB19-SW27',
        vendor: 'GE',
        description: 'Link smart LED light bulb, A19 soft white (2700K)',
        extend: generic.light_onoff_brightness,
    },`

homeassistant.js:
`'PSB19-SW27': [configurations.light_brightness],`

**Comment by Koenkk** [comment]
added, thanks! Will be supported in the dev branch soon.
