### ISSUE TITLE
Z2M Map is not showing up anymore

### ISSUE THREAD

**Issue by canedje** [Koenkk/zigbee2mqtt#18131]
### What happened?

Since a while the map is not showing up anymore.
After push the button "load map" The wheel is turning for ever and never shows the map
It did work before.
I restarted the docker, the same result

I'm running Z2M in a Docker under Unraid

### What did you expect to happen?

A shown map with all devices and connections

### How to reproduce it (minimal and precise)

just put the button "load map" again

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonof zigbee 3.0 dongle plus-E

**Comment by kcgthb** [comment]
I have the same issue with 1.39.0, nothing shows in the logs, but the map doesn't load.

**Comment by tackin** [comment]
Found the problem in my case:
If I set docker-compose-file
```
environment:
 - Z2M_WATCHDOG=default

```

The watchdog will kill requests to devices which are not available yet. So the timeout will never reach the card-building processing.
Disable that environment-var solves the card-problem for me immediately.
