### ISSUE TITLE
[Wrong device]: Device ZG-227Z (without display) is detected as ZG-227ZL

### ISSUE THREAD

**Issue by marcelhoogantink** [Koenkk/zigbee2mqtt#18158]
### Link

https://nl.aliexpress.com/item/1005003518393383.html

### Model

ZG-227Z

### Description

Temperature an humidity sensor

### Vendor

Tuya

### Picture (link)

https://nl.aliexpress.com/item/1005003518393383.html

### Database entry

{"id":16,"type":"EndDevice","ieeeAddr":"0xa4c138e79636e7c0","nwkAddr":61087,"manufId":4417,"manufName":"_TZE200_a8sdabtg","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,1026,1029,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011","65506":34,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_a8sdabtg","powerSource":3,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1688150128440,"defaultSendRequestWhen":"immediate"}

### Notes

This Tuya ZG-227Z (ZG-227Z-20230308 according the QR-code) Temperature and Humidity Sensor device is detected as ZG-227ZL, but has no LCD, 
Device is working correct!!
![IMG_1355](https://github.com/Koenkk/zigbee2mqtt/assets/51886888/c8883127-15b9-4114-b197-e594022b98c5)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
