### ISSUE TITLE
ZTH02 small with cr2032 battery not well implemented

### ISSUE THREAD

**Issue by tonbor** [Koenkk/zigbee2mqtt#18153]
### What happened?

The ZTH02 SMALL cr2032 battery is not well implemented, battery state is wrong type

https://a.aliexpress.com/_EQNcYLF

### What did you expect to happen?

To be well implemented

### How to reproduce it (minimal and precise)

Just add to zigbee2mqtt

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

20210708

### Adapter

zStack3x0

### Debug log

![Screenshot_20230630_113844_AliExpress](https://github.com/Koenkk/zigbee2mqtt/assets/42464290/616d5391-187c-4535-b278-32e18f70282a)
![Screenshot_20230630_113151_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/42464290/5c46325a-6359-49e3-8a94-2470c47bbe58)
![Screenshot_20230630_113102_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/42464290/4d9f47ba-0ab8-4040-8c47-d20dab3cca12)

**Comment by tonbor** [comment]
Any news on this problem?

**Comment by tonbor** [comment]
Is somebody going to look into this?

**Comment by tonbor** [comment]
any solution?

**Comment by francisp2** [comment]
Zigbee2MQTT shows the correct entities, Domoticz does not.  Question for Domoticz ?
