### ISSUE TITLE
Konke Pro-Key multi function button

### ISSUE THREAD

**Issue by elpaul** [Koenkk/zigbee2mqtt#1815]
Hi everyone.
I have several Xiaomi devices and several Osram devices. They all work without a problem and they also pair up smoothly.
Today I got the KONKE button. Konke Pro-Key multi function button:
![IMG_20190805_135101](https://user-images.githubusercontent.com/9497662/62469207-14008080-b798-11e9-961d-7e5db2ab2ed6.jpg)
Unfortunately, when I try to pair, I do not receive anything in the logs.
Where to look for a problem?

zigbee2mqtt version: 1.5.1
CC253X firmware version: CC2531_DEFAULT_20190608.

**Comment by ryanbeaton** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/1689#issuecomment-517987242

**Comment by elpaul** [comment]
I am asking for understanding, I am fresh on the subject.

> it's work only on 15, 20, 25 channels

What does it mean?

**Comment by ryanbeaton** [comment]
Cool. Hope that works.
Sorry for the short response before just saw your issue come in and wanted to get you some info quickly but only had a sec.

**Comment by Koenkk** [comment]
Thanks @ryanbeaton !
