### ISSUE TITLE
coordinator, router, low linkquality

### ISSUE THREAD

**Issue by prankousky** [Koenkk/zigbee2mqtt#1816]
Hi,

`{
"version": 1.5.1",
"commit":"unknown",
"coordinator":20190608,
"log_level":"info","
permit_join":true
}`
This is my mqtt output for my `CC2531` coordinator. It is connected to a debian machine on **ground floor** level. Almost right above it, on the **first floor** (but pretty much in the same place) is my `CC2530` repeater.

I flashed the `CC2530` yesterday with `router-cc-2530-diag.hex`. The router has successfully been connected and `home-assistant` displays it as

```
state true
led state false
linkquality 13
description 40725/0x0017880102A2D83F
type NEIGHBOR
rssi 36
```

I am not sure if I should mention this, so I will: I am currently switching from `ioBroker` to `homeassistant` and use one coordinator and one router **for each**. The zigbee Adapter in ioBroker is currently disabled, but I always turn it back on when I am done adding devices (I am doing this so that I don't have to set up all zigbee devices at once; some have been integrated to hass via zigbee2mqtt, others still run on ioBroker and publish via its mqtt). This is probably why I also get this output

```
{"state":true,"led_state":false,"linkquality":10,"description":"3277/0x00158D0002B552F4","type":"CHILD_RFD","rssi":12}
{"state":true,"led_state":false,"linkquality":13,"description":"53251/0x00124B001B7B1646","type":"NEIGHBOR","rssi":26}
{"state":true,"led_state":false,"linkquality":13,"description":"21425/0x00178801001D05FC","type":"NEIGHBOR","rssi":130}
{"state":true,"led_state":false,"linkquality":13,"description":"40725/0x0017880102A2D83F","type":"NEIGHBOR","rssi":35}
```
Devices in my office (where the coordinator is located) run fine. I also get decent reading from first floor, however, my temperature sensor has very low link quality **around 0**! Now that I was going to grab the exact output to paste here it is suddenly around 36..? However, it transmitted values fine when it was around 0 either way.

But I also connected a `Phillips LivingColors Aurora` light. When I set it up in my office, it worked fine. After bringing it to it's designated place upstarts, I was no longer able to control it. Even though it was one room next to the router and the door was open. I could just not turn it on. When I placed it directly next to the router in the other room, it worked fine. I have similar issues with `Xiaomi` push buttons. From the room next to the router, I can use them, *but* sometimes I have to lean and point to the (usually opened) door for them to work. 

Shouldn't the router assure that I had enough signal upstairs? Or are my other coordinator and router messing with reception while they are running? I cannot turn them off until all my devices have been paired to the new coordinator, and since I need to "translate" all my node-red and ioBroker logic to home-assistant **before** re-pairing those devices, I need to run both coordinators and both routers parallel. 

Or is there some way I can pair certain devices **directly with the router** instead of the coordinator? I usually do all the pairing downstairs on my computer, then move the switches, sensors, etc. where ever they need to be. So usually they are much closer the the coordinator when I pair them, but then being placed closer to the router (if they are upstairs devices).

Should I add another router? I have quite a bunch of devices anyway, so I'll need at least one more router, anyway, but for now I am just confused by the poor reception.

Thanks in advance for your support :)

**Comment by Koenkk** [comment]
Device decided by them self were they connect to, it is advised to read: https://www.zigbee2mqtt.io/how_tos/how_to_improve_network_range.html

Note that the issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.
