### ISSUE TITLE
[New device support]: Adeo ZBEK-28 LED panel 42W

### ISSUE THREAD

**Issue by tetienne** [Koenkk/zigbee2mqtt#18195]
### Link

https://www.leroymerlin.fr/produits/electricite-domotique/domotique-et-objets-connectes/eclairage-et-son-connectes/panneau-led-connecte/panneau-led-connecte-gdansk-enki-59-5-x59-5-cm-couleurs-et-blancs-blanc-inspire-84845508.html?src=clk

### Database entry

{"id":36,"type":"Router","ieeeAddr":"0xf082c0fffe5a3a17","nwkAddr":65132,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"ZBEK-28","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,64599,64642],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"ZBEK-28","manufacturerName":"Adeo","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20220727","swBuildId":"2.12.01"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370,"colorMode":1,"currentX":11167,"currentY":46464,"colorTemperature":153,"startUpColorTemperature":65535}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"startUpOnOff":1,"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20220727","swBuildId":"2.12.01","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1688382631319,"defaultSendRequestWhen":"immediate"}

### Comments

Tested on a model bought few hours ago. Adding, the external converter below makes it work like a charm.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8216238/97fbc170-389e-4bb6-85b7-50d3bde5aba5)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBEK-28'],
    model: 'PEZ1-042-1020-C1D1',
    vendor: 'ADEO',
    description: 'Gdansk ENKI',
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMax":370,"colorTempPhysicalMin":153}

**Comment by Koenkk** [comment]
added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
