### ISSUE TITLE
Lidl Livarno HG08010 (TS0505B): LEDs never fullly turn off

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#18224]
### What happened?

As [reported before](https://github.com/Koenkk/zigbee2mqtt/issues/15485#issue-1489576755) by @eerr0EERR there's an issue with the Lidl Livarno HG08010.

If you select "off", the state changes to “OFF”. But the device remains on, at a very low brightness setting.

### What did you expect to happen?

The lamp should turn off

### How to reproduce it (minimal and precise)

Plug in the lamp and select "off" in the GUI.

### Zigbee2MQTT version

1.32.0

### Adapter firmware version

20221226

### Adapter

Slaesh's CC2652RB stick

**Comment by RubenKelevra** [comment]
@github-actions Get lost

**Comment by Sineos** [comment]
https://lamphq.com/led-lights-glow/
It is a common effect and widely known. Especially on lower end products.

**Comment by Sineos** [comment]
I have this device as well and cannot confirm your findings. It shows the typical glow as described in the link above, even if the state is off.

> It's also not a cheap noname product from China.

Let's agree to disagree.

**Comment by RubenKelevra** [comment]
Maybe we talk about something different here? Turning it on brightness 1 does not change the brightness of the device compared to off.

Can you confirm this on your device?

**Comment by bfayers** [comment]
I have 3x Lidl E27 bulbs (_TZ3000_49qchf10 / TS0502A).

2 of them behave correctly, one of them is going to the dim LED behaviour instead of off...

**Comment by edmundwatson** [comment]
I have the same problem. Has anyone attached it the lidl hub and see if the same happens. I don't have one

**Comment by RubenKelevra** [comment]
In the meantime I've talked to the manufacturer. They've sent me two new ones, no questions asked.

But those are having the same issue. 🤷‍♂️

@edmundwatson nope. I don't have the original hub.

**Comment by bfayers** [comment]
Interestingly my 1 of 3 bulbs that was misbehaving is now fine... I haven't even updated Z2M yet it just decided to behave suddenly....

**Comment by wise-rice** [comment]
If you remove the ground wire, the glowing will stop when the device is turned off.
The case will not be grounded anymore, so please do this at **your own risk**, but the case is coated/painted and as long as nothing is damaged internally, nothing should happen on the outside, IMHO.

**Comment by RubenKelevra** [comment]
> If you remove the ground wire, the glowing will stop when the device is turned off.
> The case will not be grounded anymore, so please do this at **your own risk**, but the case is coated/painted and as long as nothing is damaged internally, nothing should happen on the outside, IMHO.

I highly recommend not doing this. While the case is painted, the screws and the connection nut holding the cable is not.

I've checked, while the lights are on they have 117 V AC on them.

That's lethal territory, if enough current can flow through this connection.

Please always connect the ground and better use a zigbee switch in front to turn the power off to them if you don't need them to stop any glowing.
