### ISSUE TITLE
Lidl HG06336 battery=100 and battery_low=true

### ISSUE THREAD

**Issue by Bastian007** [Koenkk/zigbee2mqtt#18228]
### What happened?

After Battery change the device Lidl HG06336
shows  battery 100% but battery_low icon.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12425311/be81b027-30dd-4d02-9b0a-19d5d5dc310c)

{
    **"battery": 100,
    "battery_low": true,**
    "contact": true,
    "linkquality": 43,
    "tamper": false,
    "elapsed": 3631179
}

### What did you expect to happen?

"battery_low": false after battery change.

### Zigbee2MQTT version

1.32.0-2

### Adapter firmware version

Z-Stack_3.x.0 coordinator 20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by Bastian007** [comment]
issue still valid

**Comment by Bastian007** [comment]
issue still exist

**Comment by comprido** [comment]
still reproduced

**Comment by Bastian007** [comment]
issue still exist

**Comment by Bastian007** [comment]
issue still exist with 1.36.1

**Comment by Bastian007** [comment]
issue still exist with 1.38.0-1

**Comment by comprido** [comment]
can this issue be fixed.
It would be great to know when the battery is getting low

**Comment by Koenkk** [comment]
Is `battery_low` always `true`? I think the device doesn't report it properly, so we should ignore it.

**Comment by Bastian007** [comment]
No, it is not always true
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12425311/337f2b6a-4014-4fc1-baf9-634d1ea21df4)

**Comment by Koenkk** [comment]
Removed it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
