### ISSUE TITLE
Availability ping fails for Develco SPLZB-134 due to incorrect endpoint

### ISSUE THREAD

**Issue by siandco** [Koenkk/zigbee2mqtt#18233]
### What happened?

Zigbee2MQTT incorrectly identifies a "Develco SPLZB-134 Power Plug (type G)" device as offline when performing availability ping.

This is because the availability ping is attempting to get the zclVersion attribute from genBasic cluster on endpoint 1 (which does not exist and therefore fails). The zclVersion attribute / genBasic cluster is on endpoint 2.

### What did you expect to happen?

Zigbee2MQTT to use endpoint 2 and report device as online

### How to reproduce it (minimal and precise)

Enable Availability in Zigbee2MQTT
Discover device
Wait for 10 mins (default for powered devices).

### Zigbee2MQTT version

1.32.0 commit: 69638d7

### Adapter firmware version

20230507

### Adapter

Sonoff ZBDongle-P

### Debug log

[SPLZB-134_debug.log](https://github.com/Koenkk/zigbee2mqtt/files/11969748/SPLZB-134_debug.log)

**Comment by siandco** [comment]
I can confirm this is now fixed.

Thank you.

**Comment by Koenkk** [comment]
Great!
