### ISSUE TITLE
Update the version tag with the latest tag on docker hub

### ISSUE THREAD

**Issue by MrAlucardDante** [Koenkk/zigbee2mqtt#18240]
### What happened?

The latest tag got updated, but the current version hasn't.
lastest digest : Digest:sha256:a747dcf4369e9f18635e0903aac37edf158d09c9732ddb2c2ab4dc32d3c69a55
1.32.0 digest : Digest:sha256:530445172873d5a87bef317e956455a9d936074d71c28ecab106125b0fcc750f

There might be an oversight in your release pipeline

### What did you expect to happen?

current version digest matches latest digest

### Zigbee2MQTT version

1.32.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus by ITead

**Comment by Koenkk** [comment]
This was due to a hick-up in the build pipeline, I just released 1.32.1 which equals the latest tag now.
