### ISSUE TITLE
Exception while calling fromZigbee converter: 'power_calibration' is not a number, got string ()}

### ISSUE THREAD

**Issue by fotis3d** [Koenkk/zigbee2mqtt#18253]
### What happened?

Getting the below error with the last 3 updates and therefore the power metering of my plugs stop working.

Exception while calling fromZigbee converter: 'power_calibration' is not a number, got string ()}

I use a Tuya based ZB plug with Power Metering

When I revert to 1.31.2 version everything works fine.

### Zigbee2MQTT version

1.32.1-1

### Adapter firmware version

20220219

### Adapter

Sonoff Dongle Plus (type zStack3x0)

**Comment by Koenkk** [comment]
Same as https://github.com/Koenkk/zigbee2mqtt/issues/18169
