### ISSUE TITLE
(NOT AN ISSUE)  New Smart Bulb working, add support

### ISSUE THREAD

**Issue by drbios** [Koenkk/zigbee2mqtt#1825]
i have a new smart smart bulb to support

/opt/zigbee2mqtt/node_modules/zigbee-shepherd-converters/devices.js
 `{
        zigbeeModel: ['LED_E27_OWDT'],
        model: 'ZA806SQ1TCF',
        vendor: 'Leedarson',
        description: 'LED E27 tunable white',
        extend: generic.light_onoff_brightness_colortemp,
    },`  

/opt/zigbee2mqtt/lib/extension/homeassistant.js´

`'ZA806SQ1TCF': [configurations.light_brightness_colortemp]`

**Comment by Koenkk** [comment]
Added, thanks!
