### ISSUE TITLE
Xiaomi ZNJLBL01LM 

### ISSUE THREAD

**Issue by platte-73** [Koenkk/zigbee2mqtt#18251]
### What happened?

There is a device_temperature: and a Temperature. But Temperature not showing as sensor in home assistant
{
    "battery": 59,
    "charging_status": false,
    "device_temperature": 27,
    "illuminance": 0,
    "illuminance_lux": 0,
    "linkquality": 87,
    "motor_state": "pause",
    "position": 37,
    "power_outage_count": 3,
    "running": false,
    "state": "OFF",
    "temperature": 23,
    "update": {
        "installed_version": 3870,
        "latest_version": 3870,
        "state": "idle"
    },
    "update_available": false
}

### What did you expect to happen?

Dit expect that there was also an sensor for Temperature in Home assistant

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

20230507

### Adapter

Sonoff dongle plus

**Comment by Koenkk** [comment]
`temperature` is deprecated so it will not be exposed to HA.
