### ISSUE TITLE
[Wrong device]: ClickSmart CMA30036

### ISSUE THREAD

**Issue by uvjim** [Koenkk/zigbee2mqtt#18265]
### Link

https://click-smart.com/products/mode-smart-sockets

### Model

CMA30036

### Description

2 Gang Socket Outlet

### Vendor

ClickSmart+

### Picture (link)

https://www.electrical2go.co.uk/media/catalog/product/c/m/cma30036.png

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0x5c0272fffec4f6fb","nwkAddr":59171,"manufId":4098,"manufName":"_TYZB01_hlla45kx","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":9,"inClusterList":[0,10,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0012","65506":22,"65534":0,"modelId":"TS011F","manufacturerName":"_TYZB01_hlla45kx","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":9,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1688911124910,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
