### ISSUE TITLE
[New device support]:  DTS238-7

### ISSUE THREAD

**Issue by Hazard-4** [Koenkk/zigbee2mqtt#18276]
### Link

https://aliexpress.ru/item/1005003034220893.html?spm=a2g2w.orderdetail.0.0.13c64aa6rX8Omp&sku_id=12000023358885913

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0xe0798dfffeda122b","nwkAddr":60056,"manufId":4098,"manufName":"_TZE200_byzdayie","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":31,"65508":1,"modelId":"TS0601","manufacturerName":"_TZE200_byzdayie","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b6a948","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1688995483457,"defaultSendRequestWhen":"immediate"}

### Comments

Hello. I purchased and installed a 3-phase zigby relay (DTS238-7) with energy monitoring, it was defined as a single-phase relay (DTS238-2).
It works and controls the relay, but it may be missing some functionality (I don't know if it is).
If the z2m functionality does not provide more for a given device, then the request can be closed.
Thanks and sorry if I misunderstood something.

![1](https://github.com/Koenkk/zigbee2mqtt/assets/86654112/534e2ed1-9de2-42e9-bb75-40a5533ed51b)
![2](https://github.com/Koenkk/zigbee2mqtt/assets/86654112/2c7f98f2-330f-428b-bda2-4b9743570d50)

**Comment by unCleanCode** [comment]
I have the same device and would really like the support to be added. On top of that - it has a lot of settings and alerts which are only accessible via Tuya app and gateway for now, but I'd really want to get it supported by Zigbee2Mqtt
