### ISSUE TITLE
Tuya MOES stopped receiving messages after connecting to the router

### ISSUE THREAD

**Issue by Nikolay-Ch** [Koenkk/zigbee2mqtt#18270]
### What happened?

I have Tuya MOES switch (3 gang ZS-EUB model). My Z2M instance identify it as TUYA model TS0013.
When I pair my switch all works normally. I can see messages from switch and can change it state by Z2M GUI.

Near of this switch I have Aqara H1 switch. And after a while Tuya connects to Aqara as a router. And after that it stops working.
I can see messages from Tuya device, but can't send any message to it. After 10 seconds I receive:
`Publish 'set' 'state' to 'TuyaMacAddress' failed: 'Error: Command TuyaMacAddress/3 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'Timeout' (9999))'`

### Zigbee2MQTT version

1.32.1 commit: 4ccfdfc

### Adapter firmware version

20211222

### Adapter

zStack30x

### Debug log

Error: Command TuyaMacAddress/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'Timeout' (9999)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by paganl** [comment]
I have the same problem. It was working fine until I switched my adapter to SkyConnect and needed to repair it. I don't know the problem was caused by repairing or if it has something to do with Skyconnect.
