### ISSUE TITLE
Install Code over QR Code. 

### ISSUE THREAD

**Issue by tech2mar** [Koenkk/zigbee2mqtt#18274]
### Is your feature request related to a problem? Please describe

Hi there,

Would it be possible to add and commission devices via QR code scanning, I have some new devices and it would be awesome if I could just scan the devices via the install code, I know there is a way to add this manually or just copy paste from my documents... But I would like to see this in the GUI, I think this could be done. Would be nice. 

### Describe the solution you'd like

Would it not be nice to have some Android App there for the GUI? This would be a dream. 😳 

### Describe alternatives you've considered

That's all. 

### Additional context

Thanks for the great work

**Comment by Koenkk** [comment]
This should be done via the frontend, please create an issue in that repo.

**Comment by tech2mar** [comment]
Thanks 😃 I will.
