### ISSUE TITLE
Problems with Xiaomi/Honeywell smoke detector

### ISSUE THREAD

**Issue by elsaesk** [Koenkk/zigbee2mqtt#1828]
Hi all,

I paired a new Xiaomi/Honeywell smoke detector with success by pressing 3 times the pairing button.

But after the pairing process no data is sent by the detector.

My older Xiaomi/Honeywell smoke detectors work without a problem.

What do I have to do?

Thanks in advance.

**Comment by elsaesk** [comment]
No ideas?

**Comment by carldebilly** [comment]
Try to bring it closer to a router. I have one and the pairing worked on the first try.

**Comment by way2many** [comment]
I have one of those and it was a pain to make it work correctly. Spent couple of hours trying to pair it correctly. After that you just hope that it will work correctly as, in my case, it only reports if there is smoke detected. No battery level and no link quality.

I test it from time to time with a burn out match.
