### ISSUE TITLE
[Wrong device]: BR TuYa (Gleco) 16A Zigbee Smart Plug (BR variant picture - GP100-BRZ) detected as BSD29

### ISSUE THREAD

**Issue by pabloalcantara** [Koenkk/zigbee2mqtt#18299]
### Link

https://www.aliexpress.com/item/1005005073066732.html?spm=a2g0o.order_list.order_list_main.68.21ef18026oEOGw

### Model

GP100-BRZ

### Description

Smart Plug Tuya (Gleco) GP100-BRZ

### Vendor

Tuya (Gleco)

### Picture (link)

https://ae01.alicdn.com/kf/S042dd2a41e634e6185301bf8ff1c99bbH/Tuya-WiFi-Smart-Brasil-Plug-Switch-Zigbee-Smart-Brasil-Socket-Smart-Life-Brasil-Outlet-com-Power.png

### Database entry

{     "device": {         "applicationVersion": 100,         "dateCode": "20210625",         "friendlyName": "0x70b3d52b60027498",         "hardwareVersion": 2,         "ieeeAddr": "0x70b3d52b60027498",         "manufacturerID": 4660,         "manufacturerName": "_TZ3000_okaz9tjs",         "model": "BSD29",         "networkAddress": 36433,         "powerSource": "Mains (single phase)",         "softwareBuildID": "500+TZSKT31BS102",         "stackVersion": 1,         "type": "Router",         "zclVersion": 2     },     "last_seen": "2023-07-12T10:54:58.631Z",     "linkquality": 48,     "child_lock": null,     "current": 0.01,     "energy": 0,     "indicator_mode": null,     "power": 0,     "power_outage_memory": null,     "state": "ON",     "update": {         "installed_version": -1,         "latest_version": -1,         "state": null     },     "update_available": null,     "voltage": 130,     "elapsed": 288 }

### Notes

Every function os working as BSD29, except OTA

![image](https://github.com/Koenkk/zigbee2mqtt/assets/924104/f4a2c0cc-a579-4a4d-9806-8b72a5367a29)

**Comment by Koenkk** [comment]
We don't have an OTA for this device, to grab it a TuYa gateway is required. see https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html

**Comment by matoxbr** [comment]
Pablo how did you add on HA? Because in my case don't work. Showed unsupported.

**Comment by pabloalcantara** [comment]
I didn´t have problems adding the component, only the OTA function didn´t work.

**Comment by matoxbr** [comment]
Do you used Hub or usb dongle at home assistant?

**Comment by pabloalcantara** [comment]
I'm using the sonoff P dongle

Em seg., 18 de set. de 2023 09:26, Mateus Paulino ***@***.***>
escreveu:

**Comment by matoxbr** [comment]
the same me, but when i search for new device at zigbee2mqtt don't work. I think is necessary add for external converters.
