### ISSUE TITLE
Suddenly a second coordinator appeared (0xffffffffffffffff)

### ISSUE THREAD

**Issue by johnnymijnhout** [Koenkk/zigbee2mqtt#1833]
# Bug Report
## What happened
![image](https://user-images.githubusercontent.com/20085533/62731054-9780d280-ba21-11e9-89f3-4906240cc786.png)
Since yesterday, a second coordinator appeared in my Zigbee network. This is impossible as i only have 1 coordinator stick. It has a really weird id (0xffffffffffffffff)
## What did you expect to happen
My network should only have 1 coordinator
## How to reproduce it (minimal and precise)
I have no idea. It was running great for some weeks, and suddenly this second coordinator was there.

I also cannot restart zigbee2mqtt before i:
- Delete the 0xffffffffffffffff device from devices.yaml
- Delete all entries of 0xffffffffffffffff in database.db

If i generate the network map, it immediately appears again after i removed it.

I tried to "ban" the device too in the config, but in my map, it still reappears. Also, all devices connected to the real coordinator are also connected to the "fake coordinator", which makes me think it is a clone of the real coordinator.
## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version: 20190608 DEFAULT

## Some log snippets:
`8/8/2019, 8:47:10 PM - debug: Accept device incoming with ieeeAddr '0xffffffffffffffff' permit join is 'false'
8/8/2019, 8:47:10 PM - info: Banned device tried to connect (0xffffffffffffffff)
8/8/2019, 8:47:25 PM - debug: Received zigbee message of type 'endDeviceAnnce' with data '"0xffffffffffffffff"' of device 'undefined' (0xffffffffffffffff) of endpoint 1`

`8/8/2019, 8:50:58 PM - info: New device 'undefined' with address 0xffffffffffffffff connected!
8/8/2019, 8:50:58 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0xffffffffffffffff","meta":{}}'
8/8/2019, 8:51:00 PM - debug: Received zigbee message of type 'endDeviceAnnce' with data '"0xffffffffffffffff"' of device 'undefined' (0xffffffffffffffff) of endpoint 1`

`8/8/2019, 8:53:11 PM - debug: Received zigbee message of type 'endDeviceAnnce' with data '"0xffffffffffffffff"' of device 'undefined' (0xffffffffffffffff) of endpoint 1
8/8/2019, 8:53:11 PM - warn: Device with modelID 'undefined' is not supported.
8/8/2019, 8:53:11 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

devices.yaml:
`'0xffffffffffffffff':
  friendly_name: '0xffffffffffffffff'
  retain: false`

database.db:
`{"id":25,"type":"Coordinator","ieeeAddr":"0xffffffffffffffff","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1565290256,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280],"clusters":{}}},"_id":"8Fzkej0v3SaSlRwZ"}`

![image](https://user-images.githubusercontent.com/20085533/62730619-a1ee9c80-ba20-11e9-912c-ec4935a97ad8.png)

**Comment by Koenkk** [comment]
Is this device also logged on startup?

**Comment by johnnymijnhout** [comment]
It does not appear in the list of:
`8/9/2019, 4:51:42 PM - info: Currently 21 devices are joined:`

But pretty much immediately after that:
```
 8/9/2019, 4:52:19 PM - info: New device 'undefined' with address 0xffffffffffffffff connected!
8/9/2019, 4:52:19 PM - debug: Saving state to file /opt/zigbee2mqtt/data/state.json
8/9/2019, 4:52:19 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0xffffffffffffffff","meta":{}}'
8/9/2019, 4:52:19 PM - warn: Device with modelID 'undefined' is not supported.
8/9/2019, 4:52:19 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```
Then i see this around every 15s:
```8/9/2019, 4:56:41 PM - debug: Received zigbee message of type 'endDeviceAnnce' with data '"0xffffffffffffffff"' of device 'undefined' (0xffffffffffffffff) of endpoint 1```

**Comment by johnnymijnhout** [comment]
Also, my closest neighbour lives 100m from my house, so it cannot be interference with other coordinators from neighbours.

**Comment by johnnymijnhout** [comment]
Today i erased and reflashed the CC2531 with the source routing firmware, only to discover that immediately the ffffffffff device pops up again :(

**Comment by Koenkk** [comment]
`8/9/2019, 4:56:41 PM - debug: Received zigbee message of type 'endDeviceAnnce' with data '"0xffffffffffffffff"' of device 'undefined' (0xffffffffffffffff) of endpoint 1` makes me think that this is actually a device on the network, do you see any pointers when sniffing? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by johnnymijnhout** [comment]
I will try this, but if this is true, it would be very weird that it has the exact same device connections as the original coordinator has :S

**Comment by johnnymijnhout** [comment]
I was checking the log, and i noticed i didn't see the fffffff notifications anymore. After removing the device again from database.db and devices.yaml, and restarting zigbee2mqtt, it was really gone. 
![image](https://user-images.githubusercontent.com/20085533/62974229-0db57880-be18-11e9-8386-3e61560581a0.png)
I have no idea why this happened, i still have the same devices in my network. Wondering for how long this will last...

**Comment by johnnymijnhout** [comment]
Everything seems to be back to normal, will close this issue now as i seem to be the only one, and i cannot reproduce it anymore
