### ISSUE TITLE
Simplified map

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#1834]
Hm. It all nice to have detailed map. But can we have also option to have simple map based on how routing is working actually? Like in IObroker.
Once you have more than 10 devices, current map becoming rather something of entomological interest, or visual attraction, rather something informative.

Unless you found that this is useful:
![2019-08-08 17 52 18](https://user-images.githubusercontent.com/2550573/62732826-92be1d80-ba25-11e9-9338-479d5523b663.jpg)

I'd rather prefer to see something like this:
![1544990804_727_xiaomi-wireless-devices-in-the-smart-home-iobroker-iobroker-company-blog-habr](https://user-images.githubusercontent.com/2550573/62732787-81751100-ba25-11e9-8fbc-dfbb4e6a395c.png)

At least this shows me clearly how devices are communicate.
Keep in mind, that number of devices are comparable on both maps. One from iobroker you can read and understand. And one from z2m.....

**Comment by dzungpv** [comment]
We could map the model with the devices images, also use all description is to long, like this:
![longname](https://user-images.githubusercontent.com/10563561/62822253-19e8ce00-bbab-11e9-8843-a2c41afb223a.png)

So i prefer short model only instead of long description

**Comment by antst** [comment]
It is not about images. It is about links ) It is just impossible to read picture from map above. Very non-informative. And because of number of links, and all those numbers, it is often impossible to detect which numbers corresponds to which link. And I can't imagine how this looks with 100 devices. And don't want to! )

**Comment by james-fry** [comment]
In that IOBroker diagram is it just one view of routes from leaf nodes to the coordinator?
Otherwise that pink bulb is a pretty big single point of failure...
I would assume that the coordinator also has routes to the other routers, and hence end devices (or what is the point of a mesh network?)

**Comment by antst** [comment]
Yes, it does, but it doesn't plot all of them. Only most likely routes.
As with number of nodes, number of links goes as squared. So, with size of mesh it is less and less meaningful information, as you clearly can see on my plot. I might have all possible links, indeed. But value of this plot is negligibly different from zero. And can you imagine such map for 100 devices with 9900 lines?

**Comment by james-fry** [comment]
Thanks for the explanation. Agree that every link to from every router to every other router is not always useful...

How does the plotting code determine what are
> Only most likely routes.
?
Just from link quality?

What I was thinking about is for the diagram to be dynamically re-plotted in the context of a selected device - ie. as each device is clicked the diagram replots for that device.
In your image the pink bulk looks to be the selected device and shows all links from that device.

**Comment by antst** [comment]
I don't know how it is plotted in IOB, to be honest. But I suspect by using link quality, indeed.

Dynamic plot can be an option also, for sure.

**Comment by antst** [comment]
![rec](https://user-images.githubusercontent.com/2550573/64197303-02d58d00-ce86-11e9-8132-2a5fe25bdc7a.gif)

This is animated gif with how map looks like in IOB. To my taste, it is nearly perfect )

**Comment by james-fry** [comment]
I really like that it displys routes and lq in context when clicking on a device

**Comment by lolorc** [comment]
instead of using Z2M to generate complex graphviz data, it would be easier to handle this with an external tool that generates the themed graphviz or png or svg or whatever (html+css+js)

**Comment by james-fry** [comment]
@carldebilly Is this a potential roadmap item for [zigbee2mqtt assistant](https://github.com/yllibed/Zigbee2MqttAssistant)?

**Comment by carldebilly** [comment]
It is already on the roadmap! 😁

**Comment by kiall** [comment]
I started playing around with the map view, I didn't come up with anything much better ...

Current map view (This is with routes included)...

![image](https://user-images.githubusercontent.com/52713/69885453-29646200-12d5-11ea-9317-b97d99e8904e.png)

Routes only view, though I messed up EndDevices :)

![image](https://user-images.githubusercontent.com/52713/69885509-6af50d00-12d5-11ea-82d9-ad7e12850a08.png)

Routes only view, fixed EndDevices and used the dot "engine" instead of circo.

![image](https://user-images.githubusercontent.com/52713/69885548-8d872600-12d5-11ea-8997-a65c54490ee5.png)
