### ISSUE TITLE
Sonoff ZBMINI - cannot pair - "Received message from unsupported device with Zigbee model undefined..."

### ISSUE THREAD

**Issue by S474N** [Koenkk/zigbee2mqtt#18361]
### What happened?

Cannot pair Sonoff ZBMINI

Number of Zigbee devices: 3

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/037e4739-f959-4dfc-8078-246c5f0d25b0)

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/f8dea5ea-0deb-4d06-b803-8414b8fd1226)

Received message from unsupported device with Zigbee model 'undefined' and manufactrurer name 'undefined':
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/a12bd18b-ab6c-41fc-bb5d-7508d5b817f6)

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/83cc3361-7b9d-478e-bb1d-cae8171a31e5)

Tested also second device, but same error:
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/e57f907d-f6f6-4e50-a5b9-584745cbdd89)

Same device in Deconz/Phoscon via ConBee II:
![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/610ed970-7d5d-4d75-8470-ea0bd38ac9b3)

### What did you expect to happen?

Pair Sonoff ZBMINI devices.

### How to reproduce it (minimal and precise)

Standard pairing procedure.

### Zigbee2MQTT version

1.32.1 (tested also with dev version)

### Adapter firmware version

20230507

### Adapter

SMLIGHT SLZB-05 CC2652P

### Debug log

![image](https://github.com/ptvoinfo/zigbee-configurable-firmware/assets/16512337/d52a92c0-63f8-48c6-8c26-2f13aa52af67)

**Comment by francisp2** [comment]
Bring it close to the coordinator  and pair again

**Comment by S474N** [comment]
@francisp2: tested 1m, 2m, 5m, 10m and nothing.

**Comment by francisp2** [comment]
First remove it from Z2M, then pair again

![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/c564d7ea-b694-4b52-8902-7a6ebc18a3bf)

**Comment by francisp2** [comment]
Last one I installed was 'unsupported' too, but after clicking 'reconfigure' in the front-end it was found correctly.
