### ISSUE TITLE
Aqara WS-USC04 not reporting energy or power

### ISSUE THREAD

**Issue by ic-dev21** [Koenkk/zigbee2mqtt#18380]
### What happened?

Energy and power are both said to be exposed by the doc but neither populates. Both are null. 

### What did you expect to happen?

I’d like to have those values populated. 

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

20221226

### Adapter

Zdongle-p

**Comment by ic-dev21** [comment]
Still an issue

**Comment by ic-dev21** [comment]
Still not fixed

**Comment by Simon-CR** [comment]
still an issue

**Comment by MivraMe** [comment]
still issues
