### ISSUE TITLE
 lumi.curtain.hagl04 ZNCLDJ12LM Aqara B1 curtain motor Failed to find endpoint which support OTA cluster)

### ISSUE THREAD

**Issue by aldarund** [Koenkk/zigbee2mqtt#18386]
### What happened?

When checking for ota updates it errors out right away with

Failed to check if update available for '0x54ef44100011aee1' (Failed to find endpoint which support OTA cluster)

### Zigbee2MQTT version

1.32.1-1

### Adapter firmware version

20221226

### Adapter

 ZigStar Stick v4

### Debug log

Debug 2023-07-21 17:36:09Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"0x54ef44100011aee1","transaction":"tdtjo-2"}'
Info 2023-07-21 17:36:09Checking if update available for '0x54ef44100011aee1'
Debug 2023-07-21 17:36:09Check if update available for '0x54ef44100011aee1' (lumi.curtain.hagl04)
Info 2023-07-21 17:36:09MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"0x54ef44100011aee1"},"error":"Failed to check if update available for '0x54ef44100011aee1' (Failed to find endpoint which support OTA cluster)","status":"error","transaction":"tdtjo-2"}'
Error 2023-07-21 17:36:09Failed to check if update available for '0x54ef44100011aee1' (Failed to find endpoint which support OTA cluster)
Debug 2023-07-21 17:36:09AssertionError [ERR_ASSERTION]: Failed to find endpoint which support OTA cluster at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:256:15) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/zigbeeOTA.ts:145:19) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:203:73) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:140:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:126:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20) at Receiver.emit (node:events:513:28)

**Comment by new-kirte** [comment]
I am seeing the same error
MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Sonya Curtains Wireless"},"error":"Failed to check if update available for 'Sonya Curtains Wireless' (Failed to find endpoint which support OTA cluster)","status":"error","transaction":"tg16d-8"}'
