### ISSUE TITLE
must connect at least 3-4 times until device is not show as unsupportet

### ISSUE THREAD

**Issue by mcdhrts** [Koenkk/zigbee2mqtt#18399]
### What happened?

Hey Together,

when i want to connect (f.e. my blitwolf plugs) i get for at least 3-4 times or more a unsupportet decvice information.
When i want to reconnect the device i got many messages with device xxx leaves the network and nothing more happens. To get another try to connect, i must connect the plug to another zigbee network, clean in zigbee2mqtt the entry in the configuration.yaml and then try again. Mostly 3-4 times and then it works, maybe more. 

Two Version of plugs i tried, same thing:
https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3
https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121_plug
And same thing with HUE Bulbs, i tried with this one:
https://www.zigbee2mqtt.io/devices/9290012573A.html#philips-9290012573a

So it´s not from the devices.

I already have several (22 of the plugs f.e.) of these devices in the network. When i first started (few months ago) the connect works flawless. Now i wanted to move the remaining bulbs und plugs in the network and have this problem. Really annoying and i´m not sure how to fix it. The Logs shows an error when connecting (see logs below)

Example Picture when want to connect:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/37240726/9809e221-24e4-4b6e-b2d1-0d8258ce2fed)

### What did you expect to happen?

The Devices should connect and show as the devices they are

### How to reproduce it (minimal and precise)

Click on "Anlernen aktivieren" (not quite sure about the english naming of that -maybe start connecting)
set the device in connect mode
device connect to the network but with unsupportet

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E"

### Debug log

zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:48: Zigbee: allowing new devices to join.
zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:49: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"4pn5y-2"}'
zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:50: Device '0xe0798dfffeb91860' joined
zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xe0798dfffeb91860","ieee_address":"0xe0798dfffeb91860"},"type":"device_joined"}'
zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:51: Starting interview of '0xe0798dfffeb91860'
zigbee2mqtt  | Zigbee2MQTT:info  2023-07-22 14:58:53: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xe0798dfffeb91860","ieee_address":"0xe0798dfffeb91860","status":"started"},"type":"device_interview"}'
zigbee2mqtt  | Error: Failure send findKeyTableEntry:{"type":"Buffer","data":[48,0,1,117,0,96,24,185,254,255,141,121,224,1]}
zigbee2mqtt  |     at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:562:23
zigbee2mqtt  |     at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
zigbee2mqtt exited with code 0

**Comment by MadMirza** [comment]
I am using the Zigbee Dongle - E , I am having pairing issues as well, Some devices come comes in but stays unsupported, some has a red caution sign which says interview is not complete but just works fine (i guess). 
@mcdhrts how many devices are there in your network, I am stuck 28, anymore i try to pair would not come in. there is no response. When I try to unpair a few devices a give it a go, it pairs until I reach the 28 mark again.

**Comment by mcdhrts** [comment]
Hey @MadMirza, i am at the moment at 42 working Devices.

**Comment by xelemorf** [comment]
I have seen the same with most of my TuYa smart plugs:

- TS011F_plug_1
- BSD29

The only solution I could find is to remove them from Z2M, add them to SmartLife app to a TuYa gateway then to remove them from the app, when removing there is an option to "remove and factory reset", this resolved the issue for me. OFC you'll need a TuYa gateway for this one, I have used this type: "Smart Gateway TYZG1" Zigbee Gateway: https://www.aliexpress.com/item/1005005543390438.html?spm=a2g0o.order_list.order_list_main.343.37a11802UtbeWX
