### ISSUE TITLE
Leviton Zigbee DG15S-1BW Switch power_on_behavior 'unsupported' error

### ISSUE THREAD

**Issue by malmaxx** [Koenkk/zigbee2mqtt#18391]
### What happened?

When attempting to change the power_on_behavior I receive the attached error message.  I have tried changing this setting while in the switch's programming mode and while out of the programming mode.  Clicking the blue arrow button also generates the same error.

![Z2M error](https://github.com/Koenkk/zigbee2mqtt/assets/17691648/54610c95-1022-4c5e-8873-2fc999871859)

### What did you expect to happen?

I expect to be able to change the power_on_behavior

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

20211217

### Adapter

Sonoff ZBDongle-P

### Debug log

![Z2M debug](https://github.com/Koenkk/zigbee2mqtt/assets/17691648/172a16be-f094-4586-a1f9-b82f504c15d1)

**Comment by Koenkk** [comment]
Device doesn't seem to support this feature, disabled it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
