### ISSUE TITLE
request unsuccess: 17

### ISSUE THREAD

**Issue by todfox** [Koenkk/zigbee2mqtt#184]
It would be grand if this bug could be squashed. 

```json
 {"message":"request unsuccess: 17","stack":"Error: request unsuccess: 17
    at /opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21
    at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:257:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at CcZnp.emit (events.js:211:7)
    at CcZnp._mtIncomingDataHdlr(/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:357:14)
    at /opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:333:22
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)"}
```

**Comment by Koenkk** [comment]
Are you running the latest firmware from: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/bin ?

**Comment by todfox** [comment]
Yup. But I can reflash it if you think that that is the reason.

**Comment by Koenkk** [comment]
If you are on the latest version it is ok, does zigbee2mqtt still work after this error?

**Comment by todfox** [comment]
Yes. That said, I have noticed that pairing becomes near impossible
thereafter.

**Comment by todfox** [comment]
After a couple days of faffing around, I re-flashed the sniffer. All seems to be working now.

**Comment by todfox** [comment]
It's back!

**Comment by todfox** [comment]
2018-7-9 13:21:32 INFO
        {"message":"request unsuccess: 17","stack":"Error: request unsuccess: 17\n    at /opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21\n    at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:257:13)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at CcZnp._mtIncomingDataHdlr (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:357:14)\n    at /opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:333:22\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}

**Comment by Koenkk** [comment]
Ok, lets gather more information on when this happens. 

Do you still receive update of the devices after this error?

**Comment by todfox** [comment]
I have found that after flashing the device the error goes away and all is well.

**Comment by Sonsi79** [comment]
Today im also getting this error during start of zigbee2mqtt. 
I have completely update zigbee2mqtt on dev branch.

Should i try to reflash again? Im on newest version of firmware

**Comment by Sonsi79** [comment]
strange. during try of pair there is absolutely no message on screen or log... I have try to pair 2 new devices after start zigbee2mqtt.
Here is my debug log.

Maybe i should go back to master branch and try?
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/2254802/log.txt)

**Comment by Sonsi79** [comment]
Ok. I have reflash the stick and everything works. The Error message is gone and im able to pair new devices... sorry for confusing you

**Comment by kirovilya** [comment]
Because it is fixed by a reflash, then I think this is due to the memory in the chip. And maybe with the number of connected devices.

**Comment by tb-killa** [comment]
What the Status about move Devices to zigbee shepherd alone and have maximum of availabel memory ?

**Comment by Koenkk** [comment]
@tb-killa no update on that yet, if I remember correctly we also need Z-stack 3.0 for that. #211

**Comment by ryanbeaton** [comment]
@Koenkk you said you changed NWK_MAX_DEVICE_LIST=0
in issue https://github.com/Koenkk/zigbee2mqtt/issues/134 from @kirovilya find. Did that not work?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Koenkk** [comment]
@ryanbeaton no that didn't work.

**Comment by Koenkk** [comment]
@cmille34 how many devices have you paired now?

**Comment by cmille34** [comment]
@Koenkk 15 devices now. I can't add a 16th because i get that request unsuccess 17 error.  I was able to add these 3 devices fine yesterday , then I went to add another one and noticed it wouldn't pair.  Reflash and start over or is there any debugging/troubleshooting you would like me to do first?

**Comment by Sonsi79** [comment]
I was also getting these error for a 2nd time. Reflash fixed again. 
I have 18 devices running at the Moment.

**Comment by Koenkk** [comment]
Found out that error code 17 means that the buffer of the CC2531 is full. Honestly I'm a bit lost on how to fix this issue.

@jackchased do you know more about this issue?

**Comment by cmille34** [comment]
@koenkk I just reflashed and repaired a bunch of devices again and after the 16th one I get the error 17.  Once I get that error 17 I have to reflash and start all over. I guess Ill repair only 15 devices and just stay there until more information comes around about why this keeps happening.

**Comment by Koenkk** [comment]
Lets also see what #211 brings us.

**Comment by cmille34** [comment]
I got error 17 after only pairing 13 things yesterday. I just went back to using the Xiaomi gateway for now until this matures a little bit more. I have the flashing hardware and a few cc2531 I can try when this gets a little further along.

**Comment by arteck** [comment]
i have 27 devices online with error code 17...

**Comment by Koenkk** [comment]
I've found some more details about this error. [The buffers can be increased in the firmware](https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/390286?Is-it-possible-and-how-to-increase-the-messages-buffers-in-a-CC2538-ZNP- ).

@arteck let me know if this issue still appears after trying the solution from my previous post. If not, I will compile a firmware with increased buffers.

**Comment by arteck** [comment]
i come from iobroker and we use the libs  zigbee-shepherd and zigbee-shepherd-converters only.
without polling.... 
I would recommend you compile a new firmware an i can test it.. I'm looking forward to reconnect 27 devices.. or it is possible reflashing the new fiirmware without losing the devices ??

**Comment by tb-killa** [comment]
Will the error also occur if you add another router (e.g. Ikea Light) to the mesh network?

**Comment by arteck** [comment]
is the question for me ?? by the way i have here hue and osram router (bulbs, gu10 and plugs)

**Comment by Koenkk** [comment]
@arteck firmware with increased buffer sizes: https://github.com/Koenkk/Z-Stack-firmware/tree/increased_buffer/coordinator/CC2531/bin (4 times more buffers).

**Comment by arteck** [comment]
Ok ... I test it Friday

**Comment by arteck** [comment]
well.. new status.. 
setting from programmer
![grafik](https://user-images.githubusercontent.com/6681528/44165721-be841d00-a0c9-11e8-92cc-0e74758e760a.png)

all router devices are reconnected after OFF and then ON.. all xiaomi battery devices reconnected automatically with the routers.. only hue switches i had to reconnect manually

**Comment by kirovilya** [comment]
@arteck It is very good!
Interesting, if there were sensors connected to the coordinator, would they work or should they be repairing?

**Comment by kirovilya** [comment]
The important part of the flashing it is to save ieee address of coordinator!

**Comment by Koenkk** [comment]
28 devices! :smile: lets monitor this for a few days

**Comment by arteck** [comment]
I still have here 4 router devices..  :-)
until now not connectd

**Comment by arteck** [comment]
problem
![grafik](https://user-images.githubusercontent.com/6681528/44221956-601b7500-a183-11e8-8551-e012ec8c84f1.png)

**Comment by Koenkk** [comment]
@arteck could this be a caused due to an offline router/connection problems?

**Comment by arteck** [comment]
nope all routers are online

**Comment by arteck** [comment]
and i have pairing problem with the new firmware and xiaomi NEW devices.. old devicess works

**Comment by arteck** [comment]
hmm all 31 devices works... 
![grafik](https://user-images.githubusercontent.com/6681528/44223287-83482380-a187-11e8-80ca-69d76a95cd28.png)

**Comment by Sonsi79** [comment]
@arteck Sehe gerade du nutzt die Lampen als Router. Wie kann ich das einstellen? Finde deine Lösung genial :-) Habe mehrere HUE Lampen und würde diese gerne genauso nutzen wie Du

**Comment by arteck** [comment]
die router werden automatisch erzegt.. es sind alle stromgebundenen Geräte wie hue Lampen oder Stripes sowie Osram Plugs oder auch hier Lampen egal ob gu10 oder e27 oder oder.. alles was an Strom hängt wird zur Router.. Zigbee spannt das Netz dann automatisch auf

**Comment by Sonsi79** [comment]
Ok, danke für die Antwort. Eine letzte Frage, wie hast Du dir diese tolle Übersicht anzeigen lassen in der auch sichtbar ist welches Gerät an welchem Router hängt?

**Comment by arteck** [comment]
die Map wird durch den zigbee Adapter aus iobroker generiert

**Comment by Koenkk** [comment]
Ok great, so the firmware is still working OK 😄

**Comment by arteck** [comment]
i think we have a problem

zigbee.0 | 2018-08-18 12:08:08.594 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - off - {} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the n
zigbee.0 | 2018-08-18 12:08:07.640 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - on - {} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the ne
zigbee.0 | 2018-08-18 12:08:01.597 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - off - {} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the n
zigbee.0 | 2018-08-18 12:07:47.930 | info | new dev 0x841826000001170d 397 PAR16 50 TW
zigbee.0 | 2018-08-18 12:07:31.991 | error | Zigbee publish to '0x0017880102de40ac', lightingColorCtrl - moveToColorTemp - {"colortemp":10,"transtime":0} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Pl
zigbee.0 | 2018-08-18 12:07:31.887 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - on - {} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the ne
zigbee.0 | 2018-08-18 12:07:22.559 | error | Zigbee publish to '0x7cb03eaa00a747b1', genOnOff - on - {} - 3 failed with error Error: AF data request fails, status code: 183. APS no ack.
zigbee.0 | 2018-08-18 12:07:15.315 | error | Cannot get the Node Descriptor of the Device: 0x0017880102ca68f3 (Error: Timed out after 10000 ms)
zigbee.0 | 2018-08-18 12:07:14.692 | info | Succesfully configured 0x7cb03eaa00a747b1
zigbee.0 | 2018-08-18 12:07:05.326 | error | Zigbee publish to '0x0017880102de40ac', lightingColorCtrl - moveToColorTemp - {"colortemp":10,"transtime":0} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Pl
zigbee.0 | 2018-08-18 12:07:05.291 | error | Cannot get the Node Descriptor of the Device: 0x7cb03eaa00a747b1 (Error: request unsuccess: 16)
zigbee.0 | 2018-08-18 12:07:05.248 | error | Cannot get the Node Descriptor of the Device: 0x0017880103dcc9d2 (Error: request unsuccess: 16)
zigbee.0 | 2018-08-18 12:07:05.203 | error | Cannot get the Node Descriptor of the Device: 0x0017880103648612 (Error: request unsuccess: 16)
zigbee.0 | 2018-08-18 12:07:05.123 | error | Cannot get the Node Descriptor of the Device: 0x0017880102f054a7 (Error: request unsuccess: 16)
zigbee.0 | 2018-08-18 12:07:05.014 | error | Cannot get the Node Descriptor of the Device: 0x84182600000b911f (Error: request unsuccess: 16)
zigbee.0 | 2018-08-18 12:07:04.991 | error | Failed to configure 0x0017880103caa673
zigbee.0 | 2018-08-18 12:07:04.970 | error | Failed to configure 0x0017880102e251de
zigbee.0 | 2018-08-18 12:07:04.949 | error | Zigbee publish to '0x0017880103648612', genOnOff - off - {} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.928 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - off - {} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.905 | error | Zigbee publish to '0x0017880102de40ac', lightingColorCtrl - moveToColorTemp - {"colortemp":10,"transtime":0} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.883 | error | Zigbee publish to '0x0017880103648612', lightingColorCtrl - moveToColorTemp - {"colortemp":10,"transtime":0} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.859 | error | Zigbee publish to '0x0017880103648612', genOnOff - on - {} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.837 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - on - {} - 11 failed with error Error: rsp error: 16
zigbee.0 | 2018-08-18 12:07:04.743 | error | Zigbee publish to '0x0017880102de40ac', genOnOff - on - {} - 11 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the ne
zigbee.0 | 2018-08-18 12:07:04.662 | info | Succesfully configured 0x84182600000c8b2f
zigbee.0 | 2018-08-18 12:07:04.355 | error | Failed to configure 0x84182600000e4d12
zigbee.0 | 2018-08-18 12:06:50.107 | error | Cannot get the Node Descriptor of the Device: 0x84182600000e4d12 (Error: Timed out after 10000 ms)

**Comment by arteck** [comment]
1 error found,, its a hue switch
![grafik](https://user-images.githubusercontent.com/6681528/44306196-236d9a80-a38a-11e8-9051-8f404128cabc.png)

but it works.. the other one is ok..

**Comment by tb-killa** [comment]
This could be the fault of Power save (sleep Mode).
Please check if you pressed All four Buttons simultan short, this could bring device up and finish your fault check.

**Comment by arteck** [comment]
press one Button help also..

**Comment by matchett808** [comment]
Prior to the new firmware - was it producing error messages like this one?

```
2018-8-20 12:31:57 - error: Zigbee publish to '0x001e5e0902293394', genOnOff - off - {} - null failed with error Error: AF data request fails, status code: 183. APS no ack.    
```

My stick seems to get itself into a state where I can't recover from occasionally (it normally coincides with me messing about with new devices) - I get the error 17 and then things work for 5 minutes before all the devices stop working.

I'm trying to not go for new firmware as I'd need to repair all my devices - but if I have to I'll just wait for the NV_RESTORE firmware (or for it to be ruled out)

**Comment by matchett808** [comment]
That's just a plug

**Comment by arteck** [comment]
which plug ?? hue ?? osram ??

**Comment by dzungpv** [comment]
I have this problem, try all type of firmware from original TI ZNP to the increase buffer size. One reason for this problem is when signal low, for me it often occurs if the signal lower than -60dbm

**Comment by Koenkk** [comment]
@dzungpv do you have this issue with a CC2531 flashed with https://github.com/Koenkk/Z-Stack-firmware/tree/increased_buffer/coordinator/CC2531/bin ?

**Comment by dzungpv** [comment]
@Koenkk yes, it has some more bug like it hang and must reboot PI, I don't know it is zigbee2mqtt or the hardware/firmware

**Comment by worf0r** [comment]
With the iobroker solution error 17 never occurs with the first command sent to a lightbulb. But very often with the second or third command. Even with good signal...

**Comment by arteck** [comment]
only combined with TRADFRI bulb ... did you forget

**Comment by worf0r** [comment]
Not only Tradfri, also Osram, see here: https://forum.iobroker.net/viewtopic.php?f=36&t=14819&start=80#p171563

**Comment by arteck** [comment]
Osram Stripe maybe, only.... my Osram Bulb E14 works..

**Comment by nic0dk** [comment]
@arteck what software are you using to get he map overview? :) running 23 device myself with 1 router, and getting 17 error too :(

**Comment by Koenkk** [comment]
@baseje this is due to an offline device, not an issue with the stick.

**Comment by Koenkk** [comment]
Please let me know if this is still present with the new firmware.

**Comment by apeeters** [comment]
@Koenkk The https://github.com/Koenkk/Z-Stack-firmware/tree/increased_buffer/coordinator/CC2531/bin link is dead. Should we use https://github.com/Koenkk/Z-Stack-firmware/tree/optimize/coordinator/CC2531/bin to fix this issue instead?

**Comment by Koenkk** [comment]
@apeeters please use https://github.com/Koenkk/Z-Stack-firmware/tree/optimize/coordinator (this will be the new firmware, not that the CC2530 firmware is not up yet.)

**Comment by salopette** [comment]
@ Koenkk is this the firmware for the Zigbee stick as a gateway or as a router?

Thank you

**Comment by Koenkk** [comment]
coordinator (gateway). Router firmwares can be found here: https://github.com/Koenkk/Z-Stack-firmware/tree/master/router

**Comment by Alexalex89** [comment]
Is the optimize/coordinator CC2530_CC2591 firmware final?

**Comment by Koenkk** [comment]
yes

**Comment by Alexalex89** [comment]
I just flashed it and got hundreds of 205 "no network route" errors ... What am I doing wrong? Do I have to re-pair all devices after flashing?

**Comment by NiNo-213** [comment]
I´ve the same problem mentioned above with my 2 osram smart plug+. how can i find out which firmware ist flashed on my cc2531 stick & how can I update/upgrade the firmware? any ota possibility, coz I bought the stick flashed from somebody and have not the necessary hardware on hand to flash it by meself once again.. thx + b.rgds

**Comment by Koenkk** [comment]
@NiNo-213 http://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html#how-to-check-the-installed-firmware-version

For the dev firmware you currently need the CC debugger, once it is in master, you can use the TI serial boot loader tool.
