### ISSUE TITLE
Zigbee 2 Bluetooth ?

### ISSUE THREAD

**Issue by podarok** [Koenkk/zigbee2mqtt#1840]
I was trying to run zigbee2mqtt in Android phone
- termux + termux api
- ubuntu in chroot
And compilation went well.
The only complexity is usb is not directly accessible via /dev/ttyXxxx
But Bluetooth - accessible.

Is there a chance to extend cc2531 firmware to send zigbee traffic to Bluetooth?
In this case we would be able to run dongle from power bank and connect to it via Bluetooth from central hub where zigbee2mqtt installed.

**Comment by Koenkk** [comment]
The CC2531 doesnt have bluetooth maybe it would be possible for the CC1352P but for now this is out of scope.

**Comment by JLFN** [comment]
@podarock esp8266 with cc2530 and Vpn hotspot will make it.
