### ISSUE TITLE
Some Gledopto devices don't require transition time multiplier of 3.3

### ISSUE THREAD

**Issue by nick-dijkshoorn** [Koenkk/zigbee2mqtt#18407]
### What happened?

I have a combination of Philips Hue bulbs and Gledopto (Pro) controllers. I've noticed that the Gledopto controllers have a longer transition time compared to the Hue bulbs.

In 2019, a transition time multipliers of 3.3 was implemented for Gledopto devices: https://github.com/Koenkk/zigbee2mqtt/issues/1047
I assume newer Gledopto devices handle the transition time correctly and don't require the multiplier anymore.

The issue is present on all 3 Gledopto (Pro) devices that I have:
- GL-C-009P, firmware 20051203 (20230302)
- GL-C-006P, firmware V1.0.1T1 (20210512)
- GL-C-006P, firmware 10276802 (20210719)

### What did you expect to happen?

When turning on the lights with a transition time of 5, I expect a transition time of 5 seconds instead of ~16.5 seconds.

### How to reproduce it (minimal and precise)

- Turn off light
- Turn on light with transition time of 5 seconds
- Measure transition duration with stopwatch
- Measured transition time is ~16.5 seconds

I've repeated these steps with a transition time of 3 seconds. Same transition time multiplier of 3.3 is measured.

After i've removed the transition time multipliers in zigbee-herdsman-converters/converters/toZigbee.js, the transition times of the Gledopto devices are equal to the Hue devices.

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20230507

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

**Comment by nathbullen** [comment]
Could we reopen this? I've spent weeks trying to debug issues with Gledopto devices transitioning slower than expected (3.3x slower than expected, it turns out) - definitely still a problem
