### ISSUE TITLE
TuYa TS0505B_1_2 brightness not changing.

### ISSUE THREAD

**Issue by LukieOssie** [Koenkk/zigbee2mqtt#18416]
### What happened?

I added this device and everything is working fine, except for the brightness in color mode. When the bulb is in color mode the device doesn't respond to any change in the brightness. However when I check the status in Zigbee2MQTT the brightness value is changed. Is there any way I can fix this?

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

20210708

### Adapter

SONOFF Zb Dongle-P

### Debug log

info  2023-07-24 11:22:56: MQTT publish: topic 'zigbee2mqtt/Hoek 3', payload '{"brightness":254,"color":{"h":240,"hue":240,"s":100,"saturation":100,"x":0.136,"y":0.04},"color_mode":"xy","color_power_on_behavior":null,"color_temp":575,"do_not_disturb":null,"linkquality":69,"state":"OFF"}'
info  2023-07-24 11:22:56: MQTT publish: topic 'zigbee2mqtt/Hoek 2', payload '{"brightness":3,"color":{"h":60,"hue":60,"s":94,"saturation":94,"x":0.432,"y":0.498},"color_mode":"xy","color_power_on_behavior":null,"color_temp":272,"do_not_disturb":null,"linkquality":111,"state":"OFF"}'
info  2023-07-24 11:22:57: MQTT publish: topic 'zigbee2mqtt/Hoek 1', payload '{"brightness":254,"color":{"h":160,"hue":160,"s":100,"saturation":100,"x":0.155,"y":0.416},"color_mode":"xy","color_power_on_behavior":null,"color_temp":76,"do_not_disturb":null,"linkquality":129,"state":"OFF"}'

**Comment by maxgluzman** [comment]
I have the same issue
