### ISSUE TITLE
[Feature request]: ZM85EL-2Z (_TZE200_cf1sl3tj) please add battery sensor DP 13

### ISSUE THREAD

**Issue by VikeDragon** [Koenkk/zigbee2mqtt#18413]
### Is your feature request related to a problem? Please describe

Greetings!
ZM85EL-2Z (_TZE200_cf1sl3tj). Please add battery sensor DP 13
Previously, there was a converter option with a battery charge, now after the changes hit the release, they disappeared after the last update.
https://github.com/Koenkk/zigbee2mqtt/issues/11251#issuecomment-1285207519

### Describe the solution you'd like

Previously, there was a converter option with a battery charge, now after the changes hit the release, they disappeared after the last update. Moreover, the battery charge is displayed on the first tab of the device, but not as a separate sensor.
https://github.com/Koenkk/zigbee2mqtt/issues/11251#issuecomment-1285207519

### Describe alternatives you've considered

ZM85EL-2Z (_TZE200_cf1sl3tj). Please add battery sensor DP 13

### Additional context

https://github.com/Koenkk/zigbee2mqtt/issues/11251#issuecomment-1285207519
Moreover, the battery charge is displayed on the first tab of the device, but not as a separate sensor.
![first_page_with_battery](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/abf8a092-66c8-4f22-b902-4b97e77208ad)
![second_page_without_battery](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/a4bfc5c3-9102-4cd6-8a58-0aff31ef075a)
![mqtt_without_battery](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/d8b1a11d-a4d3-49da-a9e7-55e74b60080d)

**Comment by nimmerpeople** [comment]
Please...

**Comment by VikeDragon** [comment]
Greetings, Koenkk!

Thank you for the converter! I see the charging icon appeared in the list, but this prop is not transmitted to MQTT. I tried to reconnect the device, but there is no battery props in MQTT.

**Comment by Koenkk** [comment]
can you make a screenshot of the device -> state tab?

**Comment by cloudbr34k84** [comment]
@Koenkk 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/f46335d3-ede6-4c15-a429-5c310ea0f28c)

**Comment by VikeDragon** [comment]
> can you make a screenshot of the device -> state tab?

![zm85_state](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/c60b14e1-7e98-42bc-91da-95f2fff08190)

**Comment by Koenkk** [comment]
I made a mistake in the ext converter, with https://gist.github.com/Koenkk/0ed3bbdc0f6246e2b6d73b47aa649a15 battery should show up under exposes, it may take some time before the battery value is reported (24 hours max I expect)

**Comment by cloudbr34k84** [comment]
> I made a mistake in the ext converter, with https://gist.github.com/Koenkk/0ed3bbdc0f6246e2b6d73b47aa649a15 battery should show up under exposes, it may take some time before the battery value is reported (24 hours max I expect)

When will this be pushed through to edge? I prefer to wait till I don't need it as a converter

**Comment by Koenkk** [comment]
> When will this be pushed through to edge? I prefer to wait till I don't need it as a converter

When someone confirms the ext converter works.

**Comment by VikeDragon** [comment]
> I made a mistake in the ext converter, with https://gist.github.com/Koenkk/0ed3bbdc0f6246e2b6d73b47aa649a15 battery should show up under exposes, it may take some time before the battery value is reported (24 hours max I expect)

Greetings, Koenkk!
I try the modified converter, I wait 24 hours until the battery appears.

**Comment by VikeDragon** [comment]
Greetings, Koenkk!
The battery charge has not appeared with the new version of the converter. Here are screenshots. Repaired one of the drives, I'll try what will happen tomorrow.
![zm85_nobatt3](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/7260ffc7-2bb1-43bc-91c9-cc988c8d3fb9)
![zm85_nobatt2](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/78553d8a-273a-4ba8-bba7-5bcaa456efc6)
![zm85_nobatt](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/c638c7c7-0920-4c7c-841c-057af28e5e91)

**Comment by VikeDragon** [comment]
Greetings, Koenkk!
The problem remains. The new converter does not show charge and does not create charge entities in MQTT.

**Comment by Koenkk** [comment]
what was the latest z2m version where this still worked?

**Comment by VikeDragon** [comment]
> what was the latest z2m version where this still worked?

Greetings, Koenkk!
I removed both engines again, cleaned the MQTT from the props. I have overloaded the Home Assistant several times.  I checked the converter that it is connected correctly and works. I connected the engines and everything was created correctly! Everything is wonderful! Batteries shows, new entities have been created! Thank you so much for the converter!!!
![itsworked4](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/6d65fe76-10c4-402f-9767-79c8b6cfecc4)
![itsworked3](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/1f20d2e3-b491-44c0-906e-268dc505a194)
![itsworked2](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/185138bf-8e9f-4702-81da-a318a6e06042)
![itsworked](https://github.com/Koenkk/zigbee2mqtt/assets/44431640/ab08145e-82f5-4f2f-bdaa-d79f79524656)

**Comment by VikeDragon** [comment]
Thank you for your support and help!

**Comment by Koenkk** [comment]
Integrated the fix, you can remove the ext converter after updating to todays release.

**Comment by VikeDragon** [comment]
> Integrated the fix, you can remove the ext converter after updating to todays release.

Thank you! Everything works great after the update, without the converter!
