### ISSUE TITLE
Setting sensitivity on DJT11LM - MAC transaction expired

### ISSUE THREAD

**Issue by tiagofreire-pt** [Koenkk/zigbee2mqtt#1842]
Using this method: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#xiaomi-aqara-vibration-sensor-djt11lm

I get errors on setting the sensitivity:

zigbee2mqtt:info 8/10/2019, 11:42:14 AM Zigbee publish to device '0x00158d000312c3d6', genBasic - write - [{"attrId":65293,"dataType":32,"attrData":1}] - {"manufSpec":1,"disDefaultRsp":1,"manufCode":4447} - null zigbee2mqtt:error 8/10/2019, 11:42:21 AM Zigbee publish to device '0x00158d000312c3d6', genBasic - write - [{"attrId":65293,"dataType":32,"attrData":1}] - {"manufSpec":1,"disDefaultRsp":1,"manufCode":4447} - null failed with error Error: AF data request fails, status code: 240. MAC transaction expired. zigbee2mqtt:info 8/10/2019, 11:42:21 AM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Error: AF data request fails, status code: 240. MAC transaction expired.","meta":{"entity":{"ID":"0x00158d000312c3d6","type":"device","friendlyName":"0x00158d000312c3d6"},"message":"{\n \"sensitivity\": \"high\" \n}"}}' zigbee2mqtt:info 8/10/2019, 11:42:21 AM Zigbee publish to device '0x00158d000312c3d6', genBasic - write - [{"attrId":65293,"dataType":32,"attrData":1}] - {"manufSpec":1,"disDefaultRsp":1,"manufCode":4447} - null zigbee2mqtt:info 8/10/2019, 11:42:22 AM Zigbee publish to device '0x00158d000312c3d6', genBasic - write - [{"attrId":65293,"dataType":32,"attrData":1}] - {"manufSpec":1,"disDefaultRsp":1,"manufCode":4447} - null

**Comment by dzungpv** [comment]
Do you use any router?

**Comment by tiagofreire-pt** [comment]
Yes, I do. But this device is bind directly to the coordinator, as shown on zigbee2mqtt map component in Home Assistant.

**Comment by dzungpv** [comment]
Zigbee map not all true, i advice you remove router from the network and retry, if it work the problem may cause by router

**Comment by tiagofreire-pt** [comment]
I understand, but without the router I can't get communication as the signal is quite weak.
