### ISSUE TITLE
[Feature request]: Aqara Roller Shade Driver E1 motor speed adjustment

### ISSUE THREAD

**Issue by Zicmu69** [Koenkk/zigbee2mqtt#18431]
### Is your feature request related to a problem? Please describe

Please add a feature to adjust a motor speed.

### Describe the solution you'd like

Adding 3 motor speeds in settings: low-mid-high

### Describe alternatives you've considered

1-2-3

### Additional context

Official app supports motor speed adj.

**Comment by JanFoerste** [comment]
+1, was requested before in #18076

**Comment by WorlockM** [comment]
Also waiting for this function. The mentioned one is closed, hoping this can be re-considered.

**Comment by codyc1515** [comment]
Still current.

**Comment by chaayac** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/7109 is available now in v1.36
