### ISSUE TITLE
Devices unavailable after poweroutage

### ISSUE THREAD

**Issue by Drealine** [Koenkk/zigbee2mqtt#18442]
### What happened?

Hi,
I've got a small poweroutage today and all devices are unavalaible until restart Z2M.

### What did you expect to happen?

Devices restore state after poweroutage.

### How to reproduce it (minimal and precise)

My server is connected with an UPS.
The small poweroutage keep Z2M up with this test. So it's not a corrupted database or etc..

### Zigbee2MQTT version

 1.32.1

### Adapter firmware version

20221226

### Adapter

Sonoff ZB Plus

### Debug log

Nothing happen. Just some timeout regarding availibilty of devices.

**Comment by Xeevis** [comment]
Hi, what MQTT broker are you using?

**Comment by Drealine** [comment]
MQTT Addon of HA @Xeevis

**Comment by Drealine** [comment]
Nope. Not stale
