### ISSUE TITLE
(0x11: BUFFER_FULL) when sending a lot of messages

### ISSUE THREAD

**Issue by bamaas** [Koenkk/zigbee2mqtt#18461]
### What happened?

When sending a lot of messages at once sometimes an error log message pops up and it seems like devices dont end up in the desired state.

Zigbee2MQTT:info  2023-07-30 15:11:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp' to 'toilet_light_group' failed: 'Error: Command 5 lightingColorCtrl.moveToColorTemp({\"colortemp\":250,\"transtime\":10}) failed (SREQ '--> AF - dataRequestExt - {\"dstaddrmode\":1,\"dstaddr\":\"0x0000000000000005\",\"destendpoint\":255,\"dstpanid\":0,\"srcendpoint\":1,\"clusterid\":768,\"transid\":106,\"options\":0,\"radius\":30,\"len\":7,\"data\":{\"type\":\"Buffer\",\"data\":[17,33,10,250,0,10,0]}}' failed with status '(0x11: BUFFER_FULL)' (expected '(0x00: SUCCESS)'))'","meta":{"friendly_name":"toilet_light_group"},"type":"zigbee_publish_error"}

### What did you expect to happen?

No error logs and to have the lights in the desired state.

### How to reproduce it (minimal and precise)

Sent a lot of messages to set state of light.

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20211114

### Adapter

 zzh (CC2652R Stick)

### Debug log

[zigbee2mqtt.log](https://github.com/Koenkk/zigbee2mqtt/files/12209290/zigbee2mqtt.log)

**Comment by lux73** [comment]
update your Coordinator to 20221226 Firmware at least

update your z2m to latest Version

Check Logs if Problem is gone
