### ISSUE TITLE
[New device support]: Adeo ZBEK-34 LED Panel extraflat

### ISSUE THREAD

**Issue by cesarblancg** [Koenkk/zigbee2mqtt#18466]
### Link

https://www.leroymerlin.es/productos/iluminacion/iluminacion-interior/iluminacion-para-el-bano/focos-para-bano/downlight-led-redondo-blanco-3100lm-rgb-blanco-calido-a-blanco-frio-ip44-22-5cm-84870058.html

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0xf082c0fffe5a31d8","nwkAddr":58593,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"ZBEK-34","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,64599,64642],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":2,"hwVersion":1,"dateCode":"20220908","swBuildId":"2.12.02","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1690752155664,"defaultSendRequestWhen":"immediate"}

### Comments

Tested with the external converter and works fine except for the effects.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ZBEK-34'],
    model: '84870058',
    vendor: 'ADEO',
    description: 'Extraflat 225 ENKI',
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 370]}),
};

module.exports = definition;
```

### Supported color modes

100lm-3100lm, 2700k-6500k, rgb

### Color temperature range

Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}

**Comment by Koenkk** [comment]
Closing this as https://github.com/Koenkk/zigbee-herdsman-converters/pull/6028 is merged.
