### ISSUE TITLE
Aqara P1 don't want update to the latest

### ISSUE THREAD

**Issue by Drealine** [Koenkk/zigbee2mqtt#18467]
### What happened?

When try to force a check update, Z2M don't want to update to latest firmware. 
Current firmware : 0.0.0_0005
Last firmware available in Aqara repo : 0.0.0_0010
Model : Aqara P1  - RTCGQ14LM

I kown that you've to push pairing button brief before click on Z2M. 

### What did you expect to happen?

Update to latest firmware.

### How to reproduce it (minimal and precise)

Click on pairing button
Go to Z2M, click on check update
Z2M return no update available

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

 7.3.0.0 build 131

### Adapter

Sonoff ZB Plus E (EZSP)

**Comment by glinkin55** [comment]
Hello. Confirm this issue.
