### ISSUE TITLE
Aubess 20A EU smart plugs recognized as BSD29

### ISSUE THREAD

**Issue by c0mplex1** [Koenkk/zigbee2mqtt#18473]
### What happened?

The plug is recognized as another plug.

### What did you expect to happen?

They report themselves as Model BSD29 and not as TS011F_plug_1 as I would expect.

Simple name: 0x70b3d52b6002763f
Description
Last seen: N/A
Available: Disabled
Device Type: Router
Zigbee model: TS011F
Zigbee Manufacturer: _TZ3000_okaz9tjs
Description: Smart plug (with power monitoring by polling)
Support Status: Supported
IEEE address: 0x70b3d52b6002763f
Network address: 0x8A92
Firmware build date: 20210625
Firmware Version: 500+TZSKT31BS102
Manufacturer: TuYa
Model: BSD29

### Zigbee2MQTT version

1.32.1-1

### Adapter firmware version

20230507

### Adapter

Slaesh's CC2652RB stick

**Comment by c0mplex1** [comment]
Please take note, multiple users encountering the same issue.
https://github.com/Koenkk/zigbee2mqtt/discussions/18205

**Comment by Koenkk** [comment]
BSD29 is a whitelabel model of the TS011F_plug, is this device not a BSD29? If yes, then fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=wrong+device&projects=&template=wrong_device.yaml&title=%5BWrong+device%5D%3A+
