### ISSUE TITLE
My router

### ISSUE THREAD

**Issue by z4rn0x** [Koenkk/zigbee2mqtt#1847]
Not an issue, just wanted to share my router, built from the tutorial done by @Koenkk [here](https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html) . Very discrete now, but improve a lot the network range. I love it!
![20190811_121825](https://user-images.githubusercontent.com/34210703/62836691-d8e8cc00-bc33-11e9-9f47-7a2f9f917510.jpg)
![20190811_121817](https://user-images.githubusercontent.com/34210703/62836696-e1410700-bc33-11e9-906e-95d574a40f0b.jpg)
![20190811_122230](https://user-images.githubusercontent.com/34210703/62836702-ef8f2300-bc33-11e9-886f-019fe89e2d62.jpg)
![20190811_122301](https://user-images.githubusercontent.com/34210703/62836706-f3bb4080-bc33-11e9-8f6f-14295d7928ba.jpg)

**Comment by Koenkk** [comment]
Nice one! Perhaps it would also be interesting to put this on the forum: http://zigbee2mqtt.discourse.group/

I will close this as it is not an issue.
