### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by danielsmit15** [Koenkk/zigbee2mqtt#18474]
### Link

https://nl.aliexpress.com/item/1005005408244662.html?spm=a2g0o.order_list.order_list_main.5.605679d2DbZs7d&gatewayAdapt=glo2nld

### Database entry

{"id":47,"type":"Router","ieeeAddr":"0xa4c138551aefdcc7","nwkAddr":5137,"manufId":4417,"manufName":"_TZE204_nklqjk62","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":56,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_nklqjk62","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1690812216091,"defaultSendRequestWhen":"immediate"}

### Comments

All sollutions i found had issues of opening automaticly without People sending commands. therefore i do not want to use those sollutions. They made scripts to prevent that, but that does not feel like the right option for me. Is there a way to propperly add it to z2m?  

i tried this:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
       {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE204_nklqjk62'}],
        model: 'PJ-ZGD01',
        vendor: 'TuYa',
        description: 'Garage door opener',
        fromZigbee: [legacy.fromZigbee.matsee_garage_door_opener, fz.ignore_basic_report],
        toZigbee: [legacy.toZigbee.matsee_garage_door_opener, legacy.toZigbee.tuya_data_point_test],
        whiteLabel: [{vendor: 'MatSee Plus', model: 'PJ-ZGD01'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
        exposes: [e.binary('trigger', ea.STATE_SET, true, false).withDescription('Trigger the door movement'),
            e.binary('garage_door_contact', ea.STATE, true, false)],
};

module.exports = definition;

**Comment by denisjankovic** [comment]
+1

**Comment by denisjankovic** [comment]
@danielsmit15 Hi, i have a question in your code example, where are you geting from legacy.fromZigbee.matsee_garage_door_opener, legacy.toZigbee.matsee_garage_door_opener and legacy.toZigbee.tuya_data_point_test ? Thanks a lot in advance

**Comment by danielsmit15** [comment]
I took the info from an existing code wich is in the database on the zigbee2mqtt website. The code i found was from a simular garagedoor opener from tuya with older software.

**Comment by denisjankovic** [comment]
@danielsmit15 thank you for your fast answare, can you share them ? I'm stuck, can't make it work with Z2M, thanks a lot in advance

**Comment by danielsmit15** [comment]
> @danielsmit15 thank you for your fast answare, can you share them ? I'm stuck, can't make it work with Z2M, thanks a lot in advance

I could not find the proper link sinds i was working. So now that i have acces to my computer, here it is
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts

This is the original code from the older software:

  {
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_nklqjk62'}],
        model: 'PJ-ZGD01',
        vendor: 'TuYa',
        description: 'Garage door opener',
        fromZigbee: [legacy.fromZigbee.matsee_garage_door_opener, fz.ignore_basic_report],
        toZigbee: [legacy.toZigbee.matsee_garage_door_opener, legacy.toZigbee.tuya_data_point_test],
        whiteLabel: [{vendor: 'MatSee Plus', model: 'PJ-ZGD01'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
        exposes: [e.binary('trigger', ea.STATE_SET, true, false).withDescription('Trigger the door movement'),
            e.binary('garage_door_contact', ea.STATE, true, false)],
    },

**Comment by denisjankovic** [comment]
@danielsmit15 thanks for the link, I found it before, did you manage make the device work ?

**Comment by danielsmit15** [comment]
@denisjankovic no unfortunately not. Still trying and tweeking. And hoping that someone else will find the solution

**Comment by danielsmit15** [comment]
@denisjankovic 

This workes perfect thanks so much.
