### ISSUE TITLE
File tuya.ts is updated with new device, how do I update my installation of zigbee2mqtt?

### ISSUE THREAD

**Issue by jbrepogmailcom** [Koenkk/zigbee2mqtt#18470]
### What happened?

Hello, I purchased device (TS011F) that is not supported by my zigbee2mqtt, but I found definition in new tuya.ts file. How do I update my installation with new tuya.ts file? Thanks

### Zigbee2MQTT version

old

### Adapter firmware version

unknown

### Adapter

CC

**Comment by Koenkk** [comment]
You have to update to the dev branch  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) or wait for the next release (tomorrows new release).
