### ISSUE TITLE
1 channel dimmer (QS-Zigbee-D02-TRIAC) recognized as wrong model

### ISSUE THREAD

**Issue by c0mplex1** [Koenkk/zigbee2mqtt#18480]
### What happened?

I bought a 1 gang smart dimmer switch module without neutral
![Dimmer](https://github.com/Koenkk/zigbee2mqtt/assets/81088928/3ac80ff0-daa6-45f4-a7e4-137651621bdc)

After pairing, it reports as:
1 gang smart dimmer switch module with neutral: TS110E_1gang_2 aka QS-Zigbee-D02-TRIAC-LN
![Dimmer overzicht](https://github.com/Koenkk/zigbee2mqtt/assets/81088928/8ab7d564-c4eb-4089-bb0c-c38b1dd7e69b)

### What did you expect to happen?

I expect no errors in log files, but... :

Home Assistant core log:
2023-08-01 09:56:52.901 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.keuken_licht_power_on_behavior: '' (valid options: ['off', 'previous', 'on'])
2023-08-01 09:59:44.248 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'light_type' when rendering '{{ value_json.light_type }}'
2023-08-01 09:59:44.249 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.keuken_licht_light_type: '' (valid options: ['led', 'incandescent', 'halogen'])
2023-08-01 09:59:44.249 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'power_on_behavior' when rendering '{{ value_json.power_on_behavior }}'

Zigbee2MQTT log:
Zigbee2MQTT:info  2023-08-01 10:02:28: MQTT publish: topic 'zigbee2mqtt/Keuken licht', payload '{"brightness":189,"last_seen":"2023-08-01T10:02:28+02:00","linkquality":91,"max_brightness":255,"min_brightness":78,"state":"OFF"}'
Zigbee2MQTT:info  2023-08-01 10:02:28: MQTT publish: topic 'zigbee2mqtt/Keuken licht/type', payload '{}'

### How to reproduce it (minimal and precise)

![Dimmer instellingen](https://github.com/Koenkk/zigbee2mqtt/assets/81088928/88acb359-6fb2-4033-8dd3-231d73f5a244)

When I press the refresh button "light_type" below error is generated:
Zigbee2MQTT:error 2023-08-01 10:11:44: Publish 'get' 'light_type' to 'Keuken licht' failed: 'Error: Read 0xa4c1388972b63ca5/1 genLevelCtrl([64514], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:info  2023-08-01 10:11:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'light_type' to 'Keuken licht' failed: 'Error: Read 0xa4c1388972b63ca5/1 genLevelCtrl([64514], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"Keuken licht"},"type":"zigbee_publish_error"}'

When I press the refresh button "power on behavior" below error is generated:
Zigbee2MQTT:error 2023-08-01 10:16:27: Publish 'get' 'power_on_behavior' to 'Keuken licht' failed: 'Error: Read 0xa4c1388972b63ca5/1 genOnOff(["moesStartUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:info  2023-08-01 10:16:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'power_on_behavior' to 'Keuken licht' failed: 'Error: Read 0xa4c1388972b63ca5/1 genOnOff([\"moesStartUpOnOff\"], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"Keuken licht"},"type":"zigbee_publish_error"}'

### Zigbee2MQTT version

1.32.1-1

### Adapter firmware version

20230507

### Adapter

Slaesh's CC2652RB stick

**Comment by mrmaximas** [comment]
you closed your ticket, did you find a solution?
