### ISSUE TITLE
Log entry for group add is incorrect

### ISSUE THREAD

**Issue by carldebilly** [Koenkk/zigbee2mqtt#1848]
I'm trying to add a device in a group.

## Actual `zigbee2mqtt/bridge/log` entry
Following the add, I'm receiving this payload:
```json
{"type":{"device":"LUM 4007 ch3","group":"1","action":"add"}}
```

## Expected `zigbee2mqtt/bridge/log` entry
I expect this payload to be played instead:
```json
{"type":"device_group_add", "message":{"device":"device_friendly_name","group":"1"}}
```

**Comment by Koenkk** [comment]
Thanks, fixed in the dev branch.
