### ISSUE TITLE
Z2M show LQI 255

### ISSUE THREAD

**Issue by Drealine** [Koenkk/zigbee2mqtt#18492]
### What happened?

Hi
Using multipan protocol (it's experimental). I've got LQI 255 for all devices.

### What did you expect to happen?

LQI normal.

### How to reproduce it (minimal and precise)

Nothing.

### Zigbee2MQTT version

1.32.2-1

### Adapter firmware version

7.3.0.0 build 0

### Adapter

Sonoff ZB E

**Comment by erikpendragon** [comment]
Completed? How did you fix it?
