### ISSUE TITLE
[New device support]: Tuya Presence mmWave Radar Sensor 24G ,  TS0225

### ISSUE THREAD

**Issue by roy81f** [Koenkk/zigbee2mqtt#18497]
### Link

https://www.aliexpress.com/item/1005005767446349.html?spm=a2g0o.order_list.order_list_main.73.2b535c5frPlXjj

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0xa4c1389be966b410","nwkAddr":50306,"manufId":4417,"manufName":"_TZE200_hl0ss9oa","powerSource":"DC Source","modelId":"TS0225","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280,57346,61184,1024],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"TS0225","manufacturerName":"_TZE200_hl0ss9oa","powerSource":4,"zclVersion":3,"appVersion":129,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0021b952c0","zoneState":0}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":1391}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":129,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1690979275349,"defaultSendRequestWhen":"immediate"}

### Comments

Cannot retrive any information from the device.

**Comment by makstech** [comment]
I just received this one and will try to implement it

**Comment by roy81f** [comment]
> I just received this one and will try to implement it

great, thank you

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6036/

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
Ext converter: https://gist.github.com/Koenkk/79a20ea7e5eaf35749e157d0c31a1f9b

**Comment by roy81f** [comment]
Working!!! Thanks a million.

**Comment by roy81f** [comment]
i got same error (No Converter avaible for) when im trying to update a few parameters: 

'large_motion_detection_distance'
'large_motion_detection_sensitivity'
'small_motion_detection_distance'
'small_motion_detection_sensitivity'
'static_motion_detection_distance'
'static_motion_detection_sensitivity'
'alarm_time"

**Comment by Koenkk** [comment]
Whoops, made a mistake, updated https://gist.github.com/Koenkk/79a20ea7e5eaf35749e157d0c31a1f9b

**Comment by roy81f** [comment]
now its working perfectly!  thank you so much.

**Comment by zaneclaes** [comment]
@Koenkk my `TS0225` device is not being matched by these rules, as the manufacturer is actually `_TZ3218_awarhusb`. I suspect if I could just make it match on device model it would work. Is there any easy way for me to do that?

**Comment by makstech** [comment]
@zaneclaes This issue was for `_TZE200_hl0ss9oa`.  
https://github.com/Koenkk/zigbee2mqtt/issues/18637 looks like is for  `_TZ3218_awarhusb`.

**Comment by janmannsbart23** [comment]
I'm just curious, is this sensor working for anyone of you reliable?

**Comment by megamacy** [comment]
nope, not with this ddf :/

**Comment by MaxW95** [comment]
I bought a similar device of same model "TS0225", but its currently not supported:


    modelZigbee:TS0225
    type:Router
    nwk:336
    manuf id:4417
    manufacturer:_TZ321C_fkzihax8
    power:Mains (single phase)
    app version:65
    hard version:1
    zcl version:3
    stack version:1
    date code:
    interviewed:false
    configured:false


    modelZigbee:TS0225
    type:Router
    nwk:336
    manuf id:4417
    manufacturer:_TZ321C_fkzihax8
    power:Mains (single phase)
    app version:65
    hard version:1
    zcl version:3
    stack version:1
    date code:
    interviewed:false
    configured:false
    endpoint:1
    profile:260
    input clusters:genBasic (0)
    genGroups (4)
    genScenes (5)
    ssIasZone (1280)
    output clusters:genTime (10)
    genOta (25)
    endpoint:242
