### ISSUE TITLE
Using zigbee2mqtt as a dependency in a plugin?

### ISSUE THREAD

**Issue by flatsiedatsie** [Koenkk/zigbee2mqtt#1849]
I'm trying to integrate zigbee2mqtt into an add-on for the Mozilla WebThings Gateway. There already is an add-on (which I've pointed out in this queue earlier), but it's not longer available in the WebThings add-ons store. I suspect this is because it still relied on the user to install zigbee2mqtt separately.

I've created a [version of the add-on](https://github.com/flatsiedatsie/zigbee2mqtt-adapter) that automatically installs zigbee2mqtt. Instead of going to 'official' route of creating a daemon, the add-on simply runs zigbee2mqtt in a sub-directory as a sub-proces of itself. This seems to work just fine.

I was wondering: is it's possible to integrate zigbee2mqtt as a dependency instead?

// I think the parlance is: "can zibee2mqtt be used as a module"

**Comment by Koenkk** [comment]
zigbee2mqtt is not meant to be used as a dependency, you should use zigbee-shepherd directly (or zigbee-herdsman but this is still WIP https://github.com/koenkk/zigbee-herdsman)
