### ISSUE TITLE
Cant add Nimly Connect module. / easyCodeTouch_v1 

### ISSUE THREAD

**Issue by bergetun** [Koenkk/zigbee2mqtt#18508]
### What happened?

Have used several of these zigbee modules for Nimly smart door locks earlier in z2m with no problem. 
The new one i just bought doesnt seem to work. The only difference is that this one has a newer firmware: 20230210

Device works in ZHA

Tried with same result in Edge and Stable

Log entry : 
 Warning 2023-08-03 09:14:48Device '0xf4ce368708ef39b2' with Zigbee model 'NimlyIn' and manufacturer name 'Onesti Products AS' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

Device: 
https://zigbee.blakadder.com/Nimly_ZMNC010.html?fbclid=IwAR1ttuPVsuk2jsWjmGIuv0ClOHH2ytZjfeU7Pyzt6zHTTQXU90Gg02kLOeI

Friendly name
0xf4ce368708ef39b2
Description
Last seen
N/A
Availability
[Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type
EndDevice
Zigbee Model
NimlyIn
Zigbee Manufacturer
Onesti Products AS
Support status
Not supported

IEEE Address
0xf4ce368708ef39b2
Network address
0x8587
Firmware build date
20230210
Power
Interview completed
True

### What did you expect to happen?

To be paired

### How to reproduce it (minimal and precise)

Update the module to the latest firmware and pair

### Zigbee2MQTT version

 1.28.0-dev commit: a426ee1

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by bergetun** [comment]
The module indentify as NimlyIn and not NimlyPRO in z2m when installed in a Nimly Indoor lock.    Functionality is the same on  Nimly indoor and Nimly Touch Pro, so it shouldnt matter.

**Comment by Kaptensanders** [comment]
Same problem, also firmware 20230210
