### ISSUE TITLE
Some PowerTag sensors renamed to "MQTT Sensor"

### ISSUE THREAD

**Issue by tkarlsson** [Koenkk/zigbee2mqtt#18511]
### What happened?

Some of the PowerTag sensors (specifically it looks like energy sensors) have been renamed to the generic "MQTT Sensor" in Home Assistant and not containing the PowerTag device name making them indistinguishable in HA.

### What did you expect to happen?

Either be named a long the lines "power phase a" as before.

### Zigbee2MQTT version

1.32.2-dev commit

### Adapter firmware version

20221226

### Adapter

Sonoff

**Comment by tkarlsson** [comment]
Seems to have fixed itself by updating to latest dev and latest stable HA version

**Comment by senna1992** [comment]
please post how you got them working! =)
