### ISSUE TITLE
Add Lupus Device PSMP5_00.00.03.05TC to existing device file

### ISSUE THREAD

**Issue by rseibel63** [Koenkk/zigbee2mqtt#18522]
### Link

https://www.zigbee2mqtt.io/devices/12050.html#lupus-12050

### Database entry

{"id":25,"type":"Router","ieeeAddr":"0x00124b0006fd8fd5","nwkAddr":10289,"manufId":0,"manufName":"ClimaxTechnology","powerSource":"Mains (single phase)","modelId":"PSMP5_00.00.03.05TC","epList":[1,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,1794],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"PSMP5_00.00.03.05TC","manufacturerName":"ClimaxTechnology","powerSource":1,"zclVersion":1,"appVersion":3,"hwVersion":0,"dateCode":"20150915"}},"genOnOff":{"attributes":{"onOff":0}},"seMetering":{"attributes":{"divisor":10,"multiplier":1,"instantaneousDemand":0,"currentSummDelivered":[0,116000]}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffed1ace1","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffed1ace1","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":1024,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}},"4":{"profId":260,"epId":4,"devId":81,"inClusterList":[],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"hwVersion":0,"dateCode":"20150915","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1691146725377,"defaultSendRequestWhen":"immediate"}

### Comments

Works like the existing Lups devices  as listet in lupus.ts:

zigbeeModel: ['PSMP5_00.00.03.11TC', 'PSMP5_00.00.05.12TC'],

please add the PSMP5_00.00.03.05TC

Regards,
Roger

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
