### ISSUE TITLE
Ikea Tradfri outlets not responding

### ISSUE THREAD

**Issue by tediroca** [Koenkk/zigbee2mqtt#18521]
### What happened?

All 4 Ikea Tradri outlets have suddenly stopped working, and when attempting to turn them on/off I get the following error:
```
Error 2023-08-04 09:15:52Publish 'set' 'state' to 'enchufe_destilador' failed: 'Error: Command 0x847127fffebb0a10/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (105))'
```

I'm using Zigbee2MQTT in Home Assistant. I've tried to remove all the Tradfri and adding them again, which makes them work for few minutes and then they becom unresponsive again.

### What did you expect to happen?

Tradfri outlets react to on/off commands.

### How to reproduce it (minimal and precise)

1. Add the Tradfri outlets to Zigbee2MQTT using the Home Assistant add-on.
2. Click in the Expose tab and turn the outlet on - works fine.
3. Wait 5 minutes
4. Try step 2 again - it does not respond.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

```
Zigbee2MQTT:info  2023-08-04 12:13:25: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'enchufe_destilador' failed: 'Error: Command 0x847127fffebb0a10/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (5))'","meta":{"friendly_name":"enchufe_destilador"},"type":"zigbee_publish_error"}'
```

Full debug log after restart:
[debug.log](https://github.com/Koenkk/zigbee2mqtt/files/12259701/debug.log)

**Comment by HHHAAS** [comment]
Hey there, I have the same problem. I’m very new to the topic and set up the system the day before tomorrow, tonight the problems started. I thought there’s maybe another problem with my own setup but I think we have the same problem… Is it working for you again?
