### ISSUE TITLE
Tuya TS0044_1 missing actions

### ISSUE THREAD

**Issue by Rincovanderbeek** [Koenkk/zigbee2mqtt#18528]
### What happened?

The Tuya TS0044_1 does not show double actions for button 2, 3 and 4

### What did you expect to happen?

Having single and double action avaliable for all 4 buttons (and hopefully also a hold action)

### How to reproduce it (minimal and precise)

- Add device
- hold button 1 for 10 seconds till blue led flashes
- wait till it shows up in the device list of Zigbee2mqtt
- change name and have it added to home assistant

In home assistant, add a new automation and refer the trigger to this device
![ts0044_1 issue](https://github.com/Koenkk/zigbee2mqtt/assets/76967369/f314f169-f273-4476-b237-157f6d46aff7)

### Zigbee2MQTT version

 1.32.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zb Dongle-E

**Comment by scaytrase** [comment]
same here, was using these actions before, now they're gone and my automations stopped working
