### ISSUE TITLE
[New device support]: Mercator Ikuü Rotary Dimmer Mechanism

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#18541]
### Link

https://zigbee.blakadder.com/Mercator_SSWRM-ZB.html

### Database entry

n/a

### Comments

I would like to get this device. I can see that it has not been setup with Z2M, but another device very similar has been - https://www.zigbee2mqtt.io/devices/SSWM-DIMZ.html. 

I would think it would be easy enough to copy. 

This device just controls the brightness

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/18847
