### ISSUE TITLE
[Feature request]: Filter in the Card of all my Zigbee devices

### ISSUE THREAD

**Issue by UlrichThiess** [Koenkk/zigbee2mqtt#18548]
### Is your feature request related to a problem? Please describe

I have many devices:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/79257887/e1340e4a-b7a5-463b-b03f-82e572e06f10)

### Describe the solution you'd like

My whis: To filter them. I wan't to see all of my temperature sensors with their way to the coordinator. If i enter "Klima" only devices with "Klima" in its name will be shown and all the devices on the way to the coordinator.

### Describe alternatives you've considered

nn

### Additional context

nn

**Comment by francisp2** [comment]
I think that is more a request for the front-end.
