### ISSUE TITLE
Xiaomi GZCGQ01LM - Device does not support "power_outage_count"

### ISSUE THREAD

**Issue by miwok72** [Koenkk/zigbee2mqtt#18558]
### What happened?

The device does not support power_outage_count, see screenshot.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/46500817/65a19949-125b-430f-b89e-6ac6ae6bf7c2)

Even after removing the battery and reinserting it, the value remains " null ".

Device: [Xiaomi GZCGQ01LM](https://www.zigbee2mqtt.io/devices/GZCGQ01LM.html)

### Zigbee2MQTT version

1.32.0 

### Adapter firmware version

20230507

### Adapter

Slaesh's CC2652RB

**Comment by Koenkk** [comment]
Removed, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
