### ISSUE TITLE
[New device support]: Sonoff ZBmini (neutral, older version)

### ISSUE THREAD

**Issue by gyenesadam** [Koenkk/zigbee2mqtt#18567]
### Link

https://sonoff.tech/product/diy-smart-switches/zbmini/

### Database entry

{"id":15,"type":"Router","ieeeAddr":"0x00124b0024c5d069","nwkAddr":64749,"manufId":4742,"epList":[1,242],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"epId":242,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1691606626957,"defaultSendRequestWhen":"immediate"}

### Comments

I tried to connect to the first zbmini, but i always get fail to interview message, because the device not supported.
Unfortunatelly i haven't got any knowladge for make an external converter, please, somebody could help me?

May the screenshots can help.
![Screenshot_20230809_205609_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/77073590/c5f2b3f8-472a-44a6-90d3-859794db6b8b)
![20230809_205831](https://github.com/Koenkk/zigbee2mqtt/assets/77073590/f7d6d78e-9ad7-4f32-bf8c-505dafc5b84c)
![Screenshot_20230809_210002_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/77073590/5ce2e50c-c5e5-418b-96d9-4cc45fb2759b)

**Comment by gyenesadam** [comment]
Current version: 1.32.2-1

**Comment by Koenkk** [comment]
The device did not pair correctly (interview completed = false). Try force removing the device, restart z2m and re-pair the device. If that doesn't help, re-pair while having the device close to the coordinator.

**Comment by gyenesadam** [comment]
I going to try it tomorrow.

**Comment by gyenesadam** [comment]
> The device did not pair correctly (interview completed = false). Try force removing the device, restart z2m and re-pair the device. If that doesn't help, re-pair while having the device close to the coordinator.

Well, I tried.
The device next to the coordinator, after enable connect, instantly start interview, but interview still failed. 
Have you got any idea?

**Comment by Koenkk** [comment]
Try to other steps from https://www.zigbee2mqtt.io/guide/faq/#why-does-my-device-not-or-fail-to-pair

**Comment by gyenesadam** [comment]
Got it!

The solution if anybody got  the same problem:

Enter "pairing mode" on ZBMINI.
Enable Join in Z2M.
The same time push ZBMINI's button every one sec.

After that the interview complete succesfully!

Thanks for help!!!
