### ISSUE TITLE
[New device support]: Müller Licht 404049D

### ISSUE THREAD

**Issue by Sir-Pandalot** [Koenkk/zigbee2mqtt#18569]
### Link

https://www.mueller-licht.de/produktinformationen/artikel/?q=404049

### Database entry

{"id":31,"type":"EndDevice","ieeeAddr":"0xa4c13800aa432d18","nwkAddr":9634,"manufId":4635,"manufName":"MLI","powerSource":"Battery","modelId":"Remote Control","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2048,"inClusterList":[0,3,4111],"outClusterList":[3,4,5,6,8,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"hwVersion":0,"swBuildId":"MDRM001"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f0f1","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f0f1","endpointID":1},{"cluster":768,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c0f0f1","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDRM001","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-154358438},"lastSeen":1691646803664,"defaultSendRequestWhen":"immediate"}

### Comments

It's actually the same device as [Müller Licht 404022/404049C](https://www.zigbee2mqtt.io/devices/404022_404049C.html). However, it is not automatically recognized by z2m and the device ID on the back of the remote actually is 404049D.

I got it working with the below converter, but I just copy-pasted a bunch of stuff from [Issue #16693](https://github.com/Koenkk/zigbee2mqtt/issues/16693) and https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/m%C3%BCller_licht.ts.

I have no idea if the code is written properly and I am not familiar with creating pull-requests. Hopefully, this helps though. At least it's working for me :)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'Remote Control', manufacturerName: 'MLI'}],
    model: '404049D',
    description: 'Tint remote control',
    vendor: 'Müller Licht',
    fromZigbee: [fz.command_on, fz.command_off, fz.command_toggle, legacy.fz.tint404011_brightness_updown_click,
        legacy.fz.tint404011_move_to_color_temp, legacy.fz.tint404011_move_to_color, fz.tint_scene,
        legacy.fz.tint404011_brightness_updown_release, legacy.fz.tint404011_brightness_updown_hold],
    exposes: [e.action(['on', 'off', 'brightness_step_up', 'brightness_step_down', 'brightness_move_up', 'brightness_move_down',
        'brightness_stop', 'color_temperature_move', 'color_move', 'scene_1', 'scene_2', 'scene_3', 'scene_4', 'scene_5', 'scene_6'])],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1); // <- added 
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl', 'lightingColorCtrl']); // <- added 
        device.powerSource = 'Battery';
        device.save();
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
