### ISSUE TITLE
Zigbee2MQTT cannot support new Tuya Zigbee VRF Air Conditioning Controller

### ISSUE THREAD

**Issue by Bpazy** [Koenkk/zigbee2mqtt#18570]
### What happened?

In the Tuya APP, adding that VRF device to the network first reports the device itself (which Tuya calls the `VRF Gateway`), and then the `VRF Gateway` discovers several other connected devices.
| Adding devices | All devices | `VRF Gateway` discovered several other connected devices |
| --- | --- | --- |
| ![a](https://github.com/Koenkk/zigbee2mqtt/assets/9838749/9157fb95-6767-40c4-837f-2290e45f60fe) | ![a](https://github.com/Koenkk/zigbee2mqtt/assets/9838749/28725251-1701-4278-ae4c-e86df6121155) | ![a](https://github.com/Koenkk/zigbee2mqtt/assets/9838749/d0ffe4ca-6024-4638-a55a-4e9bd6a5a5ab) |

Video preview of adding `VRF gateway`：
https://github.com/Koenkk/zigbee2mqtt/assets/9838749/4a054f67-e63e-40f3-b77d-72af5f2bfd67

But in the Zigbee2MQTT frontend, only the `VRF gateway` can be discovered, no several other connected devices found.

I'm not sure why this is, but I'm guessing that the VRF Air Conditioning Controller is a physical device, and the other devices connected to it are what it virtualizes and reports to the Tuya platform.

Do you have any solution for this please?

### What did you expect to happen?

Zigbee2MQTT can discover the VRF Air Conditioning Controller and **the devices connected to it**.

### How to reproduce it (minimal and precise)

It's possible to reproduce it as I described above. but I think it's device related, so it should be difficult for others to reproduce it.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

ezsp from [Xiaomi Gateway3](https://github.com/AlexxIT/XiaomiGateway3). Not sure about firmware version.

### Adapter

Xiaomi Multimode Gateway 2 (CN), DMWG03LM

**Comment by mayongze** [comment]
这个vrf网关设备添加成功了么, 我也打算买一个

**Comment by Bpazy** [comment]
> 这个vrf网关设备添加成功了么, 我也打算买一个

@mayongze 没有添加成功，目前还在用 Tuya 集成顶着。

**Comment by mayongze** [comment]
@Bpazy 有兴趣的话可以一起分析下这个vrf的zigbee协议

**Comment by Bpazy** [comment]
@mayongze 没问题，但是你怎么确定你的 VRF 网关和我是相同型号的呢？

**Comment by latel** [comment]
我用tuya-local可以接入涂鸦网关下的zigbee空调，试了下断了外网也可用。  但这本身没啥意义，我还不如直接用tuya wifi色vrf。![image](https://github.com/Koenkk/zigbee2mqtt/assets/5621862/932593f0-57b4-4842-92cf-d28acdf8527f)

**Comment by whiteinho** [comment]
楼主是用的多模网关2做Z2M的网关吗？

**Comment by Bpazy** [comment]
> 楼主是用的多模网关2做Z2M的网关吗？

是的

**Comment by Bpazy** [comment]
@latel 没搞成。本来打算搞 z2m 适配器来仔细研究下的，但是太忙没时间搞就搁置了，临时先买了 tuya 网关+集成顶着
