### ISSUE TITLE
Update installation documemntation for Pi Zero

### ISSUE THREAD

**Issue by PianSom** [Koenkk/zigbee2mqtt#1858]
# Bug Report
Documemtation is out of date
On 
https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html
in section 2 it says to install node on a pi Zero like this 
````
# NOTE: For Raspberry Pi Zero follow https://warlord0blog.wordpress.com/2018/06/27/node-js-v8-on-raspberry-pi-zero/
````

While the link is still working, it refers to installation of node v8.11.3, which is no longer sufficiently current for zigbee2mqtt

I followed the same instructions but went for node v10.16.2 using 
````
wget https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-armv6l.tar.xz
tar -xvf node-v10.16.2-linux-armv6l.tar.xz
cd node-v10.16.2-linux-armv6l.tar
sudo cp -R * /usr/local/
````

## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Koenkk** [comment]
Could you make a pr to update https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/getting_started/running_zigbee2mqtt.md?

**Comment by Koenkk** [comment]
Manual is updated
