### ISSUE TITLE
Wrong device identification

### ISSUE THREAD

**Issue by MikhailBaranov** [Koenkk/zigbee2mqtt#18582]
### What happened?

EARU EAKCB-T-M-Z shown as TUYA TS011F_plug_1 so no options power_threshold, power_breaker, over_current_threshold, over_current_breaker, over_voltage_threshold, over_voltage_breaker, under_voltage_threshold, under_voltage_breaker are available.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/244483/f8f6800f-c124-45e5-b5e2-7cda71c2266c)

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

7.1.1.0 build 273

### Adapter

EZSP v9

**Comment by albertoneno** [comment]
Estoy en la misma situación. Me sucede con el modelo:
EAKCB-Z-M
Alguna idea?

I'm in the same situation. It happens to me with the model:
EAKCB-Z-M
Any ideas?

**Comment by MikhailBaranov** [comment]
1.33.0 - problem solved.
