### ISSUE TITLE
Schneider Electric 2GANG/SWITCH/1 MEG5126-0300 

### ISSUE THREAD

**Issue by tech2mar** [Koenkk/zigbee2mqtt#18595]
### Link

https://eref.se.com/de/en/scope/product/MEG5126-0300

### Database entry

{"id":94,"type":"Router","ieeeAddr":"0x04cd15fffeb97d4e","nwkAddr":9308,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Mains (single phase)","modelId":"2GANG/SWITCH/1","epList":[1,21,22,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"2GANG/SWITCH/1","manufacturerName":"Schneider Electric","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":6,"hwVersion":2,"dateCode":"","swBuildId":"002.004.020 R"}},"genOnOff":{"attributes":{}},"genTime":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"profId":260,"epId":21,"devId":260,"inClusterList":[0,3,2821,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"genOnOffSwitchCfg":{"attributes":{}},"genOnOff":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b844eb","endpointID":1}],"configuredReportings":[],"meta":{}},"22":{"profId":260,"epId":22,"devId":260,"inClusterList":[0,3,2821,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"genOnOff":{"attributes":{}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b844eb","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":6,"hwVersion":2,"dateCode":"","swBuildId":"002.004.020 R","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1664969682959,"defaultSendRequestWhen":"immediate"}

### Comments

I make this commit to clarify the difference between the two devices,  MEG5126-0300 and MEG5126-0000
That is supported.

The following converter is also finished,.

I will search for the other modules so that we could have all Schneider Merten supported.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
zigbeeModel: ['2GANG/SWITCH/1'],
model: 'MEG5126-0300',
vendor: 'Schneider Electric',
description: 'Merten MEG5165 PlusLink Shutter insert with Merten Wiser System M Push Button (2fold)',
extend: extend.switch(),
exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2')],
meta: {multiEndpoint: true},
configure: async (device, coordinatorEndpoint, logger) => {
const endpoint1 = device.getEndpoint(1);
await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
await reporting.onOff(endpoint1);
const endpoint2 = device.getEndpoint(22);
await reporting.bind(endpoint2, coordinatorEndpoint, ['genOnOff']);
await reporting.onOff(endpoint2);
},
endpoint: (device) => {
return {l1: 1, l2: 22};
}
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
