### ISSUE TITLE
PC321-Z-TY 3-phase Clamp Power Meter jumping values

### ISSUE THREAD

**Issue by morph027** [Koenkk/zigbee2mqtt#18606]
### What happened?

Just got a PC321-Z-TY 3-phase Clamp Power Meter wired up and connected via brand new z2m installation using a Sonoff USB Stick. Z2M part is working correct, i guess. By looking at https://github.com/Koenkk/zigbee2mqtt/issues/17153, i see weird values too sometimes. Saw them during installation and just flipped the clamp to get proper values. Changing the clamp to another phase shows the wrong values there. Once i got it working, i noticed the behaviour again.

![Screenshot_20230813_191558_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/600106/d2bd320a-017d-40a5-955b-dc611b5375e7)
![Screenshot_20230813_191628_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/600106/f60c554d-91fa-4a52-a415-fc9f6f2df327)
![Screenshot_20230813_191719_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/600106/205cb77c-eb92-45b3-b53b-0bef3e9216ba)
![Screenshot_20230813_191754_Firefox](https://github.com/Koenkk/zigbee2mqtt/assets/600106/9b42c6d4-11ad-454a-b156-79efbf2fed82)

Still not sure what happens there. Not really an Z2M problem, or?

### Zigbee2MQTT version

1.32.2 commit: 1ec1e57

### Adapter firmware version

zStack3x0

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by dhde** [comment]
Same here for me. I see the values like 39.xxx W if the Value that I expect is a negative value. So if the PV generate more energy than in the house is consumed.

**Comment by morph027** [comment]
On this phases, i do not use PV or export to grid, this is attached to a different meter just for the flat within our house. On vacation right now, but will fiddle around with the clamps a bit more. Consumption on the other 2 phases is just 60W which can't be right (regarding the oven or microwave or vacuum)

**Comment by morph027** [comment]
Jip, I've also paired the device unclamped, will try it later as I'm in vacation right now, thanks for the hint 👍

**Comment by morph027** [comment]
Did a reset yesterday and it looks good so far. Will keep an eye on it and if everything works, i can create a docs PR to update device page.

Is there a way to reset the overall stats? I've removed from z2m and paired again, but all consumption values still have the old (wrong) values.

**Comment by morph027** [comment]
Nargh, this morning the strange readings appeared again 😞

**Comment by morph027** [comment]
Just bought this one and it seems to work ;)

https://zigbee.blakadder.com/Zemismart_SPM02-D2TZ.html

**Comment by kouatik** [comment]
hello, I am seeing the same issue. The meter starts dropping out when the current reaches around 65 A, and the reported current value suddenly collapses.

<img width="1785" height="864" alt="Image" src="https://github.com/user-attachments/assets/8569ea33-5591-4e3d-9abb-238770d8d334" />
