### ISSUE TITLE
Group state incorrect when member is unavailable

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#18605]
### What happened?

I have a group that contains multiple lights incl. 1 light that is currently unavailable. The group state is always "ON" since the last state of the unavailable light was "ON".

When I checked how group state is determined, I saw that unavailable and disabled devices are not filtered out of the equation but rather their cached state is used to determine the group state. This IMHO is incorrect as disabled and unavailable devices should not be taken into account.

https://github.com/Koenkk/zigbee2mqtt/blob/1ec1e57244834cc6b9dea6dbd3612b01cd21fa65/lib/extension/groups.ts#L185-L196

### What did you expect to happen?

a) unavailable/disabled devices should lose their cached state
b) unavailable/disabled devices should not be considered when determining the group state
c) devices becoming unavailable or being disabled should trigger re-evaluation of group state

### How to reproduce it (minimal and precise)

- create a group with multiple lights
- turn on all lights => group state is "ON"
- pull power from one light => group state is still "ON"
- turn off all lights => group state is still "ON" but should be off

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

**Comment by andreasbrett** [comment]
Still active

----------------------------------------

Sep 13, 2023 02:02:31 github-actions[bot] - notifications at github.com[https://github.com] ***@***.***>:

**Comment by skytern** [comment]
Hello, I think then your issue is linked to this topic :
https://github.com/Koenkk/zigbee2mqtt/issues/10086#issuecomment-989003017

I had a similar issue and finally I remove my "group" in configuration.yaml.

**Comment by andreasbrett** [comment]
> Hello, thank you for your post, It helped me to understand. I think then your issue is linked to this topic : [#10086 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/10086#issuecomment-989003017)
> 
> I had a similar issue and finally I remove my "group" in configuration.yaml.
> 
> Zigbee2MQTT version: 1.33.0

Thanks, but this is not the issue. It's really about the code logic. If one member of a group is unavailable its cached state is used to determine the group state. I think this is incorrect as unavailable group members should not be considered when evaluating group state.
