### ISSUE TITLE
Dresden elektronik Kobold is not working since 1.32.0

### ISSUE THREAD

**Issue by hodosyp** [Koenkk/zigbee2mqtt#18615]
### What happened?

When doing any functionality I am receiving error.
`error 2023-08-14 18:37:30Publish 'set' 'state' to 'light_dining' failed: 'Error: 'transition' is not a number, got string ()'
info 2023-08-14 18:37:30MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'light_dining' failed: 'Error: 'transition' is not a number, got string ()'","meta":{"friendly_name":"light_dining"},"type":"zigbee_publish_error"}'`

### What did you expect to happen?

Being able to turn on and off or change brightness.

### How to reproduce it (minimal and precise)

On the Device -> Exposes menu clicking on "state" or changing "brightness"

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

0x26780700

### Adapter

ConBee2

### Debug log

`debug 2023-08-14 18:48:05Received MQTT message on 'zigbee2mqtt/light_dining/set' with data '{"state":"ON"}'
debug 2023-08-14 18:48:05Publishing 'set' 'state' to 'light_dining'
error 2023-08-14 18:48:05Publish 'set' 'state' to 'light_dining' failed: 'Error: 'transition' is not a number, got string ()'
info 2023-08-14 18:48:05MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'light_dining' 
failed: 'Error: 'transition' is not a number, got string ()'","meta":{"friendly_name":"light_dining"},"type":"zigbee_publish_error"}'
debug 2023-08-14 18:48:43Received MQTT message on 'zigbee2mqtt/light_dining/set' with data '{"brightness":97}'
debug 2023-08-14 18:48:43Publishing 'set' 'brightness' to 'light_dining'
error 2023-08-14 18:48:43Publish 'set' 'brightness' to 'light_dining' failed: 'Error: 'transition' is not a number, got string ()'
info 2023-08-14 18:48:43MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'light_dining' failed: 'Error: 'transition' is not a number, got string ()'","meta":{"friendly_name":"light_dining"},"type":"zigbee_publish_error"}'`

**Comment by Koenkk** [comment]
Stop z2m, remove the empty transition from your configuration.yaml (`transition: ''`), start z2m and the issue will be fixed.

**Comment by hodosyp** [comment]
Thank you!
