### ISSUE TITLE
KCTW1Z incorrectly reports the percentage of the battery.

### ISSUE THREAD

**Issue by whakru** [Koenkk/zigbee2mqtt#18639]
### What happened?

KCTW1Z incorrectly reports the percentage of the battery.
it can show 1 percent for a very long time.  more than 
30 days.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20220301

### Adapter

zStack3x0

**Comment by suspended** [comment]
Seems like a device-specific issue, and even then, battery levels are usually estimates and might not be accurate
