### ISSUE TITLE
[New device support]: ZigbeeModel: TS0601, Zigbee Manufacturer: _TZE204_nklqjk62

### ISSUE THREAD

**Issue by Twiistz** [Koenkk/zigbee2mqtt#18633]
### Link

https://www.aliexpress.com/item/1005005408244662.html?spm=a2g0o.productlist.main.1.1e6b76det9vY8u&algo_pvid=37317f1a-da25-42d6-b117-8e804a81c959&algo_exp_id=37317f1a-da25-42d6-b117-8e804a81c959-0&pdp_npi=4%40dis%21DKK%21287.95%21133.2%21%21%21307.28%21%21%402101d8b516922084668336921e680b%2112000032981943354%21sea%21DK%210%21A&curPageLogUid=PjaRT3WzDqgh

### Database entry

{"id":32,"type":"Router","ieeeAddr":"0xa4c138056d02e8c6","nwkAddr":6587,"manufId":4417,"manufName":"_TZE204_nklqjk62","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":56,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE204_nklqjk62","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c9ede4","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":132068476},"lastSeen":1692207669530,"defaultSendRequestWhen":"immediate"}

### Comments

The devices is the same as https://www.zigbee2mqtt.io/devices/PJ-ZGD01.html, but the Zigbee Manufacturer ID was different than the ones I could find here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts

### External converter

```shell
This seems to work:

const legacy = require('zigbee-herdsman-converters/lib/legacy');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0601'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '_TZE204_nklqjk62', // Vendor model number, look on the device for a model number
    vendor: 'TuYa', // Vendor of the device (only used for documentation and startup logging)
    description: 'Garage door opener', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [legacy.fromZigbee.matsee_garage_door_opener, fz.ignore_basic_report], // We will add this later
    toZigbee: [legacy.toZigbee.matsee_garage_door_opener, legacy.toZigbee.tuya_data_point_test], // Should be empty, unless device can be controlled (e.g. lights, switches).
    whiteLabel: [{vendor: 'MatSee Plus', model: 'PJ-ZGD01'}],
    configure: async (device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [e.binary('trigger', ea.STATE_SET, true, false).withDescription('Trigger the door movement'),
    e.binary('garage_door_contact', ea.STATE, true, false)], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by fmnamado** [comment]
Can you please post a prinscreen of the expose tab of your zigbee tuya garage door device?
To see what identities if exposes.

Thank you

**Comment by Twiistz** [comment]
@fmnamado 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/77859166/00678f04-fa4a-49d2-ae24-f99a11a34887)

**Comment by fmnamado** [comment]
Thank you for your help.
Before I hate the trigger, which wasn't "clickable" and where it says false (the gate status) it said null.

I tried several things ,several combinations like:

- Switching to dev version
- Installing the external converters
- Repairing several times

Now it is working, but I don't know which one solved it.
I will only messe with it in some time (disabling the external converter, then reverting from dev build)

thank you for your help :D
