### ISSUE TITLE
[Wrong device]: GIRIER Tuya ZigBee Plug 20A Smart Outlet Socket EU with Power Monitoring

### ISSUE THREAD

**Issue by sereda-oleg** [Koenkk/zigbee2mqtt#18642]
### Link

https://aliexpress.ru/item/1005005105319027.html

### Model

JR-ZPM03

### Description

Smart Plug

### Vendor

Girier

### Picture (link)

https://ae04.alicdn.com/kf/Sb635c77754984e97aacca60effdd0340I.jpg_640x640.jpg

### Database entry

{"id":38,"type":"Router","ieeeAddr":"0x70b3d52b60027e03","nwkAddr":54921,"manufId":4660,"manufName":"_TZ3000_okaz9tjs","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,6,3,4,5,57345,2820,1794],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"manufacturerName":"_TZ3000_okaz9tjs","zclVersion":2,"appVersion":100,"modelId":"TS011F","powerSource":1}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,251]}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"moesStartUpOnOff":2,"tuyaBacklightMode":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":2,"dateCode":"20210625","swBuildId":"500+TZSKT31BS102","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2123427102},"lastSeen":1692270089524,"defaultSendRequestWhen":"immediate"}

### Notes

The device is identified as "BSD29"

**Comment by sereda-oleg** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/103273045/aff2e9ee-b515-459f-a58a-0aa68b9e2d08)

**Comment by S474N** [comment]
Same "problem" here, only it identifies as `BSD29_1`. Is it possible to fix it? Also with correct photo of device?
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16512337/72b454d9-2fd9-4626-abfe-24e8b4d23849)

**Comment by tonbor** [comment]
nice if there was some action on this after one year

**Comment by b2un0** [comment]
I have the original device from [Elivico](https://www.zigbee2mqtt.io/devices/LSPA9.html#elivco-lspa9) which has exactly this Tuya identifier (`_TZ3000_okaz9tjs`).

What do you think should happen now?

If we now change the name and the picture to your device, it will be wrong for all others who have the Elivico device (like me).

As our devices were on the market earlier, it can be assumed that your manufacturer ‘`GIRIER`’ used the same firmware
