### ISSUE TITLE
Upgrade lightbulb firmware using zigbee2mqtt

### ISSUE THREAD

**Issue by foxy82** [Koenkk/zigbee2mqtt#1865]
From looking at deConz github it looks like they have managed to perform a light bulb firmware upgrade using their USB stick and not the bulbs proprietary hub.

Is this something that could be implemented into zigbee2mqtt? I'm particularly interested in the tradfri side.

Some links:

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/firmware_update.cpp

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/96

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1516

To get the IKEA OTA files:
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/ikea-ota-download.py

**Comment by Koenkk** [comment]
Note to self: functionality should be implemented in https://github.com/koenkk/zigbee-herdsman, zigbee2mqtt only should act like a frontend.

**Comment by sjorge** [comment]
Looks like the deconz people also found a few Hue firmwares, although they are encrypted... apparently it doesn't matter as the client decodes it on device.

Is this something that could be worked on once zigbee-herdsman is stable?

**Comment by Tosko4** [comment]
Hello friends! Has anyone had time and luck to develop this?

**Comment by sjorge** [comment]
Based on Koenkk/zigbee-herdsman#60 @tb-killa was working on it in his own branch, last update to that was over a month ago so I don't think a whole lot of progress has been made.

**Comment by kiall** [comment]
Also worth mentioning here - https://gist.github.com/hhromic/ddadf70f80aae7b861e4d593ac84cf52

this shows theres also a test update channel for IKEA

**Comment by Koenkk** [comment]
Continuing here: https://github.com/Koenkk/zigbee-herdsman/issues/60
