### ISSUE TITLE
Devices not reporting activity

### ISSUE THREAD

**Issue by RosaEinhorn** [Koenkk/zigbee2mqtt#1867]
I have a question regarding a problem with my network. I have 38 devices in a network and two of my devices (aqara door sensors) suddenly stopped reporting updates to the coordinator. I have no idea why. Can someone help me solve this or point me into a direction on how to analyze the problem? Thanks a lot in advance.

## Debug Info
zigbee2mqtt version: 1.5.1
CC2531 firmware version: 20190619

**Comment by mercs600** [comment]
@RosaEinhorn I have hit the same problem, how did you resolve it ?
