### ISSUE TITLE
TuYa TS011F_plug_1 Blitzwolf problems also occur on Aubess devices

### ISSUE THREAD

**Issue by Insomniac80** [Koenkk/zigbee2mqtt#18673]
### What happened?

Device is Aubess TS011F_plug_1, bought two last month. Both show the same problem.
[Page for it can be found here](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1).
There is already a header for known Blitzwolf problems, but Aubess devices are not mentioned:
"Broken attribute reporting functionality in devices sold as BW-SHP13"
My Aubess devices show almost the same behaviour (real values are 1200W / ~6A) : 
- often (all few minutes), at first power is 0, current is fine. Few seconds later both are 0. Another few seconds later current is fine, power is 0. Few seconds later normal values are sent.
- sometimes (> 1h) both are 0, not followed by a correct value within the next ~30 seconds.
Calling for the state manually results in the same wrong values unless a correct value is sent by the device by itself.

### What did you expect to happen?

No wrong values

### How to reproduce it (minimal and precise)

Buy, pair, use..

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

20220219

### Adapter

SONOFF ZigBee 3.0 USB DONGLE PLUS

**Comment by Tavisco** [comment]
Yes, +1, I have the same setup and observing the same issue on my brazilian variant, and in my case its neither from Blitzwolf nor Aubess, it's from "QNCX".
![image](https://github.com/Koenkk/zigbee2mqtt/assets/4419930/6674249b-930e-415f-a118-1f479291cbee)

Nevertheless, it identifies itself as following:

- Zigbee Model: TS011F
- Zigbee Manufacturer: _TZ3000_fukaa7nc

And, on Home Assistant, the power graph looks like the following:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/4419930/c877a8c8-1858-4d6d-a8e4-6e4ea7545cf9)
