### ISSUE TITLE
[Feature request]: Direct Binding is not working for QBKG40LM and QBKG41LM

### ISSUE THREAD

**Issue by cooldome** [Koenkk/zigbee2mqtt#18687]
### Is your feature request related to a problem? Please describe

AFAIK, Aqara light switches QBKG40LM and QBKG41LM are suppose to support direct binding because they are zigbee 3.0 devices. IMO, the issue is that all control clusters in the switch are marked as input while they both input and output clusters, therefore you can't even select necessary clusters for the direct binding in zigbee2mqtt.

### Describe the solution you'd like

I would like to support 2 use cases:
   direct bind one QBKG40LM to another QBKG40LM to enable light upstairs.
   direct bind QBKG40LM to the smart light bulb like TS0505B.

### Describe alternatives you've considered

none

### Additional context

I am happy to implement this features myself. I have the programming experience but not with zigbee2mqtt, please let me know where to start from.

 Please let me know if someone already tried and failed and the issue is really with the device itself.

**Comment by Koenkk** [comment]
Can you stop z2m, modify the data/database.db entries manually (add to outClusterList), start z2m and see if you can bind now?

**Comment by cooldome** [comment]
Thanks. All Clear. I will do the check in next 3-4 days.

**Comment by itsnot-aduck** [comment]
> Can you stop z2m, modify the data/database.db entries manually (add to outClusterList), start z2m and see if you can bind now?

Can Z2M has any procedures to add outClusterlist automatically? By interview, for example.

**Comment by 0verEngineer** [comment]
I would like to bind some QBKG40LM but i do not know what to do..

**Comment by leloch** [comment]
Same here, I would love to be able to do some QBKG40LM binding, it is such good hardware.
