### ISSUE TITLE
IKEA E1743 randomly loses bindings with Ikea bulbs

### ISSUE THREAD

**Issue by protyposis** [Koenkk/zigbee2mqtt#18695]
### What happened?

I have multiple E1743 switches that are each bound to multiple Ikea Tradfri bulbs, so that each switch controls multiple bulbs. Every once in a while, they seem to lose parts of their bindings. Z2M still lists them, but they only control a subset of devices from that moment on (e.g. 1 out of 2, or 5 out of 7). It doesn't happen to all switches at the same time. Repairing fixes this, until it eventually happens again. 

I assume it must be an issue with direct binding, because the switches still send commands to Z2M, and all bulbs are still controllable by Z2M. It happens with the latest switch firmware (24.4.6) and past versions (2.3.x). I am seeing this since at least two years, so it's also not related to a Z2M update. It's currently happening with a ZStack coordinator, but I believe it also happened with my previously used ConBee II.

I am looking for help on how to debug this:
- Is there a way to validate active bindings (I assume Z2M displays them because they are stored in the DB, not because there's an actual physical binding)? 
- How could I determine whether this is the switches', bulb's, or coordinator's fault?

 

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20221226

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by basilfx** [comment]
Hi @protyposis, did you ever find a solution for this? I also experience this issue, but with a completely different setup.

I doubt this is an issue caused by Zigbee2MQTT, because I observe the same problem with ZHA. I would therefore think it is a TRÅDFRI problem.

I have several groups of light bulbs, but it also happens with single bulbs. In the latter case, you typically assume it's the remote control's fault.

**Comment by protyposis** [comment]
Thanks for confirming the issue! Unfortunately, I didn't find a solution. I guess we could figure out whether it's the switches or bulb's fault by [sniffing the Zigbee traffic](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html), but I don't see how it could help fix the problem, so I didn't invest time in this yet.

**Comment by Koenkk** [comment]
Does this occur after the device did a `deviceAnnounce` (you can check the z2m log for that). TRADFRI devices are known to lose configuration when they restart.

**Comment by protyposis** [comment]
@Koenkk Are they also known to lose just parts of the configuration, or would they lose the complete config including _all_ bindings?

As this happens quite rarely (e.g. every few months), and it usually takes me a while to notice, it's difficult to pinpoint the time this happens and check the logs. My current theory is that it might be related to battery replacements in the remotes, maybe there's also a re-announcement.

Another observation: A switch which is bound to two bulbs (`OnOff` and `LevelCtrl` clusters) lost the ability to switch one bulb and only switches the other. However, it still dims both bulbs. So it seems it doesn't completely lose the binding to a device. @basilfx did you experience this too?

**Comment by Koenkk** [comment]
> My current theory is that it might be related to battery replacements in the remotes, maybe there's also a re-announcement.

Definitely, a battery replacement restarts the device (so it loses configuration). Device will also produce a `deviceAnnounce` in this case.

**Comment by protyposis** [comment]
I tested it multiple times and bindings are kept. I noticed however that if I press the button often enough (e.g. 10 times), the command will eventually work and the bulb will correctly turn on/off. So in all these cases where I thought the binding was lost, it wasn't really lost - there's just a weird random unreliability.

What makes this really curious is that Z2M _always_ receives the commands, so if I wire the switch and bulbs in an automation in Home Assistant, the switch _always_ switches the bulbs reliably (that's my workaround). Seems like only the direct binding is unreliable.

More details:
- Two switches, `S1` and `S2`, both bound with two bulbs `B1` and `B2`.
- Switches, bulbs and coordinator placed within 5 meters of distance and LQI of ~100. `B1` and `B2` are 20 cm apart.
- 100+ devices in total.
- According to network map, `B1` and `B2` are directly connected to coordinator, `S1` is connected to `B1`, and `S2` to an unrelated bulb.
- Even though `S1` is connected to `B1`, it switches `B2` much more reliably.
- `S1` and `S2` exhibit exactly the same behavior.

**Comment by protyposis** [comment]
Just had another instance of this issue. This time the binding was completely broken and even repeated commands didn't work. Had to first unbind both `OnOff` and `LevelCtrl` clusters, then re-bind them. Unbinding/re-binding just the `OnOff` or `LevelCtrl` didn't bring either binding back to life.

**Comment by bipsendk** [comment]
I have seen a similar issue, where an E1743 looses binding to a couple of IKEA GU10 bulbs... In my case, it can be solved by unbinding/binding the affected bulbs with `OnOff`/`LevelCtrl`

**Comment by wgentine** [comment]
I have this recurrent problem for years. Did anyone find a way to fix?

**Comment by sle118** [comment]
I am going to also report similar behavior. I wish there was a way to capture activities in a circular buffer to track the loss in binding and report everything that happened right before.

**Comment by filviu** [comment]
Problem still happens. I have one E1743 bound to a lightbulb and two led transformers. The transformers never drop but the bulb will drop every few weeks and I have to remove binding and re-do it.
