### ISSUE TITLE
Vimar 03981 shows non-existing attribute

### ISSUE THREAD

**Issue by stefa168** [Koenkk/zigbee2mqtt#18693]
### What happened?

I'm not sure from which update this happened, but I noticed that Z2M shows an attribute for Vimar 03981 Relays that the device doesn't have (`startUpOnOff`), and I sometimes get this error:

`ERROR: Publish 'set' 'power_on_behavior' to 'Luci Scale' failed: 'Error: Write 0xf4ce360a9db9369e/10 genOnOff({"startUpOnOff":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

I sent the original suggestion for the converter last year and it didn't have any issue, I checked the commit history on the adapters repository however I couldn't find any change that suggests the introduction of the attribute.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20220726

### Adapter

Sonoff ‎ZBdongle-P

**Comment by Koenkk** [comment]
Thanks, disabled it!

**Comment by stefa168** [comment]
Thank you, as always!Il 22 Ago 2023 20:49, Koen Kanters ***@***.***> ha scritto:
Thanks, disabled it!
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
