### ISSUE TITLE
Can't start as a service

### ISSUE THREAD

**Issue by aymeric106** [Koenkk/zigbee2mqtt#187]
Hello, I installed the bridge and everything is fine except it won't run as a daemon on my Pi

when

> sudo systemctl start zigbee2mqtt 

i got

> 'Erreur de segmentation'

 in french wich can be translated to 'segmentation error' or 'segmentation fault'

The only thing I changed in **zigbee2mqtt.service** is

> 'User=openhabian'

 instead of

> 'User=pi'

 because it runs on a openhab debian distro

Any idea ? Thank you.

Aymeric

**Comment by Koenkk** [comment]
Does it run via `npm start` (executed in the zigbee2mqtt directory)?

**Comment by aymeric106** [comment]
You can close the issue. 
During the install process ( I guess when sudo apt-get install -y nodejs git make g++ gcc ), the whole PI got corrupted. It was systemctl that wasn't working anymore.
Started again from a SD Card backup and it's working now (with a Xiaomi temperature and humidity sensor). Thanks again and sorry for the flase issue
