### ISSUE TITLE
[Feature request]: Hard-mapping by ieeeAddr

### ISSUE THREAD

**Issue by hyosang82** [Koenkk/zigbee2mqtt#18709]
### Is your feature request related to a problem? Please describe

Not a problem. for extension.

### Describe the solution you'd like

There's can be add a new (not defined yet) device by external converters, I know.
But I encounted with EMPTY MANUFACTURE and EMPTY MODEL NAME.
It's a wall-mounted light switch, and it was paired with wallpad same brand.
I want to pair with my HA ecosystem, but I can't add custom device because empty manufacture and model.

Its cluster is simple. 6 endpoints (6-gang switch) and has getBasic, genIdentify, genOnOff each.
There's a genOta, but it's useless, I think.

So I think that's more useful if it maps to general switch profile etc.

### Describe alternatives you've considered

I looked into a herdsman converter code, I can't acknowledge how to do that......

### Additional context

![image](https://github.com/Koenkk/zigbee2mqtt/assets/11169273/cf42da54-0be9-4a24-9173-4dad24200267)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/11169273/6682edd9-3cd0-4e86-8dc2-5df40af09cd4)

**Comment by Koenkk** [comment]
See here how to map by ieeeAddr: https://github.com/Koenkk/zigbee-herdsman-converters/blob/5f9c6a37b61062733f7ffbfb32851c03f83f1641/src/devices/enocean.ts#L8
