### ISSUE TITLE
[Feature request]: Add `topic` option in devices/groups configuration

### ISSUE THREAD

**Issue by Drafteed** [Koenkk/zigbee2mqtt#18710]
### Is your feature request related to a problem? Please describe

As follow-up of https://github.com/Koenkk/zigbee-herdsman-converters/pull/6066

Currently, `friendly_name` is used both as frontend device name/HA device name (if not overridden) and in MQTT topics. 

This approach does not allow using different naming styles in the device name and MQTT topics. For example, I prefer to have the device name written with a capital letter and without underscores, while the MQTT topics are the opposite: all letter in lowercase and underscores.

In addition, it is impossible to "visually" rename the device (e.g. for frontend) - this will cause breaking changes, since the MQTT topics also will change.

### Describe the solution you'd like

My suggestion is add `topic` parameter, that allow to override the MQTT topic of a device. This make possible to change the device name in frontend without changing the MQTT structure.

### Describe alternatives you've considered

As alternative, we can deprecate `friendly_name` and intoduce two new parameters: `name` and `topic`.

`name` - device name that will be used in the frontend, logs and HA, by default = device model name.
`topic` - device name that will be used in MQTT, by default = ieeeAddr.

`friendly_name` for compatibility should set both `name` and `topic` in this case.

But the first option seem much simpler.

### Additional context

If you approve one of the options, I can try to implement it.

**Comment by Koenkk** [comment]
First option sounds the best to me!
