### ISSUE TITLE
Problem with Smart Energy cluster commands on STM32WB55

### ISSUE THREAD

**Issue by Estylos** [Koenkk/zigbee2mqtt#18735]
### What happened?

Hello,

I am trying to integrate a STM32WB55 microcontroller from STMicroelectronics for one of my projects. Using the frontend dev console or the ".read()" function in my converter, I can retrieve the values of my attributes belonging to the Home Automation ZigBee profile clusters. However, when I try to retrieve the value of an attribute belonging to a Smart Energy ZigBee cluster, the STM32 returns the "Unsuported Cluster" response to Z2M.

I've analyzed the traffic with Wireshark and nRF52840 Dongle: you can see the "read" command sent by Z2M to endpoint 1 on the Simple Metering cluster in order to read attribute 0x00. The endpoint, cluster and the server attribute do exist on the STM32.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16976175/26d79b54-eeb8-4c5c-a4ed-d5e7cab49b25)

However, the STM32 replies to Z2M that the cluster is not supported...

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16976175/f20a1057-4e67-436e-a698-b53712e375c8)

I may have an idea of the problem, which could come from the profile. According to the ZigBee Smart Energy Standard document (and several ANs from ST), clusters 0x0700 to 0x0705 and 0x0800 are part of the ZigBee Smart Energy profile and specification. However, on the command frame sent by Z2M and the associated response, we can see that the profile is set to "Home Automation". This would explain my problem if the microcontroller checked the profile before checking the cluster... 

When I configure reporting for an attribute in a SE cluster (previously configured on the STM32 as a reportable attribute), the bind request works, but the configure reporting command fails with the same response as the read command.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16976175/bc1c5f39-ed8c-49a8-8421-19a9934c021a)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16976175/d95ce2e9-b133-45a2-802d-9f6cc80c5758)

However, if I enable "automatic" attribute reporting on the STM32 (by setting a non-zero interval in the program), as soon as the binding is configured by Z2M, the STM32 periodically sends back its attribute:  

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16976175/b01405d3-9aaa-4a8b-89bc-115154d2f245)

And Z2M successfully decodes the encrypted ZigBee message:
`Received Zigbee message from '0x0080e125001b872f', type 'attributeReport', cluster 'seMetering', data '{"65534":1,"currentSummDelivered":[0,98761254]}' from endpoint 1 with groupID 0`

Is there any way I can change the HA profile to SE to test if the STM32 is responding to Z2M requests on this cluster? Or maybe someone has an idea where this problem might come from?

Thanks in advance!

### How to reproduce it (minimal and precise)

STM32WB55 with flashed Zigbee stack and custom program

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20230507

### Adapter

SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P

### Debug log

For the read command:
```
Error: Read 0x0080e125001b872f/1 seMetering(["currentSummDelivered"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14622 - 1 - 24 - 1794 - 1 after 10000ms)
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

For the reporting command:
```
Error: ConfigureReporting 0x0080e125001b872f/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14622 - 1 - 14 - 1794 - 7 after 10000ms)
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

**Comment by FlorentLabrune** [comment]
Hello @Estylos , I encounter the exact same problem... I Use a STM32wb55 with BLE_Zigbee_dynamic FW.
I configured my device with profile Maxstream (0xc105). But when I send request with profile 0xc105 I have a default response with a unsupported cluster status.  But when I send the exact same frame by just changing the profile for HA, my user fw receive the frame.

The simple descriptor with the profile of my stm32wb55
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19490379/b2934f2a-acc6-4411-ba21-1756740bb3c7)

The request and response with Profile 0xc105
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19490379/e9341246-056d-439f-9f55-4e62a867eef8)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19490379/32d7fb19-03a4-49d4-ac62-1a97485bb52c)


The request and response but with Profile 0x0104
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19490379/a3ee9660-1f61-4b14-b728-a45252f46e8f)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/19490379/a623d433-4081-45ff-b945-47ea93b6e6bf)


Did you manage to send and receive frame with another profile ID than HA ?

**Comment by FlorentLabrune** [comment]
I found the solution, when calling 
`void * ZbZclClusterAlloc(struct ZigBeeT *zb, unsigned int alloc_sz, enum ZbZclClusterIdT cluster_id, uint8_t endpoint, enum ZbZclDirectionT direction);` 
from the zcl.h API, by default the profile ID is set to 0x0104 (HA).

You can simply modify it by setting : `clusterPtr->cluster.profileId = 0xc105;`
