### ISSUE TITLE
Pairing Moes MS-105B no longer possible

### ISSUE THREAD

**Issue by marcus0704** [Koenkk/zigbee2mqtt#18744]
### What happened?

After updating to version 1.30.4 it's no longer possible to pair new devices (Moes MS-105B).
Allowing new devices to join does not detect new devices.

### What did you expect to happen?

New devices should be detected.

### How to reproduce it (minimal and precise)

Start Zigbee2MQTT
Click on "detect devices"
Bring Moes MS-105B into pairing mode
--> Zigbee2MQTT did not detect the device

### Zigbee2MQTT version

1.32.2-1

### Adapter firmware version

20210708

### Adapter

Texas Instruments CC1352P-2

**Comment by gaetan-steijaert** [comment]
@marcus0704 were you able to fix this issue?

**Comment by marcus0704** [comment]
@gaetan-steijaert: to be honest I think my issue was caused by too much distance between the coordinator and the device that should be paired. 
I brought device and coordinator in closer distance and the pairing worked fine.
