### ISSUE TITLE
SyntaxError: Unexpected token '(' in node_modules/rimraf/node_modules/minimatch/dist/cjs/ast.js:86

### ISSUE THREAD

**Issue by jpara** [Koenkk/zigbee2mqtt#18752]
### What happened?

Aug 26 19:23:32 SmartHomeNG npm[1337]: /opt/zigbee2mqtt/node_modules/rimraf/node_modules/minimatch/dist/cjs/ast.js:86
Aug 26 19:23:32 SmartHomeNG npm[1337]:     #fillNegs() {
Aug 26 19:23:32 SmartHomeNG npm[1337]:              ^
Aug 26 19:23:32 SmartHomeNG npm[1337]: SyntaxError: Unexpected token '('

### What did you expect to happen?

to start also after the latest update

### How to reproduce it (minimal and precise)

git pull and restart

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

n.a. -> dead!

### Adapter

CC2531

**Comment by Koenkk** [comment]
You are using an unsupported Node.js error, updating it will solve your issue (use e.g. Node.js 18)

**Comment by jpara** [comment]
thanks a lotAm 27.08.2023 um 08:21 schrieb Koen Kanters ***@***.***>:﻿
You are using an unsupported Node.js error, updating it will solve your issue (use e.g. Node.js 18)
