### ISSUE TITLE
BHT-006GBZB issue

### ISSUE THREAD

**Issue by Deub31** [Koenkk/zigbee2mqtt#18769]
### What happened?

Hi.
An error occurs when the "climate.turn_off" service is called.
This service changes the "preset_modes" attribute to "hold" if the thermostat was on "program".
However, the thermostat always remains on the same "preset_modes" before being turned off.
So when you restart the "preset_modes" attribute is no longer correct.
Thanks for your job !!!

### What did you expect to happen?

The  "climate.turn_off" service must not change the "preset_modes" attribute.

### Zigbee2MQTT version

 1.32.2-1

### Adapter firmware version

20230507

### Adapter

Slaesh's CC2652RB stick

**Comment by AArt36** [comment]
+1

and sometimes my zigbee sensors lost when server reboot
