### ISSUE TITLE
Aqara Smart Wall Switch (with neutral, triple Rocker) - SKU AK095GLW01 and S/N: A00385/LS1CQA00311

### ISSUE THREAD

**Issue by Jens-Wymeersch** [Koenkk/zigbee2mqtt#18772]
### Is your feature request related to a problem? Please describe

I'm moving all my LELLKI switches to AQARA. This implies changing 1-rocker, 2-rocker and 3-rocker with neutral switches to aqara H1 switches. 

The single and double rockers are supported. The Triple rocker without neutral (QBKG29LM) is also supported. Only the Triple rocker with neutral isn't. I assume as nobody in Europe has it yet, and it is extremely hard to find... 

### Describe the solution you'd like

I would like to get this switch to be supported like the switch without neutral.

### Describe alternatives you've considered

The only alternative is using the aqara app. However the integration with Home Assistant isn't what it should be.

### Additional context

My Z2M coordinator connects quite quickly to the device (but indicates that it is unsupported).
As stated I have an aqara hub - so tests in all direction can be made.

**Comment by Jens-Wymeersch** [comment]
@Koenkk Can you please help me ? It shouldn't be a big project as the non-neutral switch is already supported. Thank you so much

**Comment by ssnaveen10** [comment]
+1.. I'm based in Singapore and I have a new Aqura SW H1  3-rocker (7 Qty).. as of now I'm using Zigbee-herdsman-converters as a workaround .
[WSDCGQ01LM.js.txt](https://github.com/Koenkk/zigbee2mqtt/files/12485854/WSDCGQ01LM.js.txt)

**Comment by Koenkk** [comment]
thanks @ssnaveen10, added!

Device will be supported in todays release.

**Comment by ssnaveen10** [comment]
@Koenkk - Thank you so much.. Now works with a new update! Have a great weekend!
![Screenshot2023_09_02_095328](https://github.com/Koenkk/zigbee2mqtt/assets/32122558/7e204d5e-e016-4d2d-8939-ab19acdeb464)

**Comment by Jens-Wymeersch** [comment]
@Koenkk Thank you so much. After update, it recognized the device instantly !
