### ISSUE TITLE
Devices suddenly disappearing, unable to re-pair

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#18777]
### What happened?

**All of these issues happened in the last 24 hours.** Slae.sh 2652RB stick on an extension cable. HAOS VM Running on Proxmox 8.0.4. Two months uptime without issues.

Issue 1 - [Tradfri E27 bulb](https://www.zigbee2mqtt.io/devices/LED1732G11.html) left the network, unable to re-pair again. Now it says it's an unsupported device. 

Issue 2 - [Xiaomi motion sensor ](https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html#xiaomi-rtcgq11lm) left network, was able to re-pair.

Issue 3 - Multiple other devices including a [Lidl plug](https://www.zigbee2mqtt.io/devices/HG06337.html#lidl-hg06337) reporting issues now. Failing to ping, stuff like that. Example of an error message:

`Failed to ping 'Ender Plug' (attempt 1/2, Read 0x50325ffffe4e493b/11 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64638 - 11 - 117 - 0 - 1 after 10000ms))`

Issue 4 - [Inmax 07088L filament bulb](https://www.zigbee2mqtt.io/devices/07088L.html#immax-07088l) left the network, re-appeared when I reset the bulb, but says Unsupported (which is wrong). Eventually left the network.

Issue 5 - [Tuya door sensor](https://www.zigbee2mqtt.io/devices/TS0203.html#tuya-ts0203) is paired, supported, no errors - but doesn't update its status. Everything is N/A.

Issue 6 - what does work works very intermittently - reacts sporadically, on every Xth button press, motion sensors sometimes not at all.

[Log including herdsman-debug](https://transfer.sh/z18Js4HXYG/log.txt). All this has been working for years. Please advise. Switching to Z2M Edge did not fix the issue, nor did complete reboot of the HA VM. HAOS VM running under Proxmox 8.0.4 with Z2M passthrough. There has been no update to Proxmox in this time.

### Zigbee2MQTT version

1.32.2-1

### Adapter firmware version

20220219

### Adapter

Slae'sh 2652RB

### Debug log

Log1
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/12453189/log.txt)

Log2
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/12453330/log.txt)

Log3
[https://transfer.sh/lwPda7ABAt/log.txt](url)

**Comment by deanpribetic** [comment]
I'm having a similar issue…lights are suddenly offline (mostly Hue bulbs)

`2023-08-29 16:30:48Failed to ping 'Entrance Light' (attempt 1/1, Read 0x00178801040f685c/11 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (193)))`

**Comment by Stooovie** [comment]
I'm getting MAC channel and ACK errors - am I right this is all caused by some sort of interference that wasn't physically there before?

**Comment by deanpribetic** [comment]
That's what is happening with mine too. I asked in the Home Assistant Discord and they told me it would be interference. Not very helpful as nothing in my set up has changed.
