### ISSUE TITLE
Invalid option for select.cover01_set_bottom_limit: 'True' (valid options: ['SET']) | Moes AM43-0.45/40-ES-EB

### ISSUE THREAD

**Issue by szatan81** [Koenkk/zigbee2mqtt#18788]
### What happened?

After updating HA (2023.8.4) & z2m (1.32.2) to latest versions my HA got flooded with that error for every Moes AM43-0.45/40-ES-EB, example:

Invalid option for select.roleta_salon_01_set_bottom_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_02_set_upper_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_02_set_bottom_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_03_set_upper_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_03_set_bottom_limit: 'True' (valid options: ['SET'])

### What did you expect to happen?

Get rid of an error

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Debug log

Invalid option for select.roleta_salon_01_set_bottom_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_02_set_upper_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_02_set_bottom_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_03_set_upper_limit: 'True' (valid options: ['SET'])
Invalid option for select.roleta_salon_03_set_bottom_limit: 'True' (valid options: ['SET'])

**Comment by szatan81** [comment]
Maybe someone could taka a look on that. It spams my HA log pretty bad:

First occurred: August 29, 2023 at 3:56:47 PM (5834 occurrences) 

It is probably small fix in zigbee-herdsman-converters

Thanks

**Comment by WRLPDZ** [comment]
Same here.
Any info?

**Comment by szatan81** [comment]
What i did:

1.Entered integrations in HA -> MQTT
2. Found cover entity
3. I disabled "set_upper_limit" and "set_bottom_limit" entities in "Controls" card.

It's a workaround but i don't have errors anymore.
