### ISSUE TITLE
Hue / Saturation values stopped working for devices with zigbee2mqtt ≥1.32.0

### ISSUE THREAD

**Issue by dersimn** [Koenkk/zigbee2mqtt#18780]
### What happened?

I discovered this with [Paulmann 371000002](https://www.zigbee2mqtt.io/devices/371000002.html) light, but it could also be the same problem with every generic device, since this is the configuration in [`zigbee-herdsman-converters/src/devices/paulmann.js`](https://github.com/Koenkk/zigbee-herdsman-converters/blob/21a0401168d8a0ddb95de7a53634ae6e416631a2/src/devices/paulmann.ts#L128):

```
{
        zigbeeModel: ['371000002'],
        model: '371000002',
        vendor: 'Paulmann',
        description: 'Amaris LED panels',
        extend: extend.light_onoff_brightness_colortemp_color(),
},
```

Hue / Saturation values were accepted and returned when using 1.31.2, but it stopped working with ≥1.32.0, so currently only xy, RGB can be used to change colours.

### Zigbee2MQTT version

1.32.0

### Adapter firmware version

20200805

### Adapter

zzh!

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6114 thanks to @sjorge 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
