### ISSUE TITLE
Add support Aqara curtain b1 (ZNCLDJ12LM)

### ISSUE THREAD

**Issue by freenetwork** [Koenkk/zigbee2mqtt#1879]
Control message work from ZNCLDJ11LM, but cannot get responce with current position

I capture packets for detect battery level, change direction, auto close/open, clear postion.
I cannot determine responce witch current position

https://github.com/freenetwork/ZNCLDJ12LM

**Comment by Koenkk** [comment]
*I cannot determine responce witch current position* -> are you sure that the ZNCLDJ11LM does support this?

**Comment by freenetwork** [comment]
I am not sure about that. Since I do not have a previous curtain model. I will capture messages the other day with a position.

**Comment by Koenkk** [comment]
So it seems it isn't supported (https://github.com/Koenkk/zigbee-shepherd-converters/issues/545#issuecomment-523628117). That means that we can integrate it, can you make a PR?

**Comment by freenetwork** [comment]
I catch packets. Control message work from old model. Packets in my repo

**Comment by freenetwork** [comment]
Dresden Electronic was aded the aqara b1

**Comment by Koenkk** [comment]
Supported in latest dev now.

**Comment by ArkadiuszNiemiec** [comment]
@Koenkk is that intended?
![Screenshot from 2019-11-19 16-35-57](https://user-images.githubusercontent.com/12136404/69161042-d1667800-0aea-11ea-94d6-a172d1fcd065.png)

**Comment by Koenkk** [comment]
Looks like a zigbee2mqtt assistant issue, discoveries for this device are in place (https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/extension/homeassistant.js#L608). Please open an issue there.

**Comment by ArkadiuszNiemiec** [comment]
Oh ok, it merged back to 1 device after restart. Thank you.
