### ISSUE TITLE
Iris 3460-L OnOff Error (Reverted fix?)

### ISSUE THREAD

**Issue by KyleStilkey** [Koenkk/zigbee2mqtt#18797]
### What happened?

I've tested this on the Edge channel (dev) as well and it seem as if this recent fix might have been reverted as trying to add these buttons results in it not working due to having a OnOff function error.

Failed to configure '0x000d6f000b11bba5', attempt 3 (Error: ConfigureReporting 0x000d6f000b11bba5/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhen":"fastpoll","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:421:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:762:22) at Object.onOff (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:74:5) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/iris.ts:116:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))

https://github.com/Koenkk/zigbee2mqtt/issues/15971

I posted a couple of weeks ago in the original release but I'm sure being closed this was not seen so I wanted to open a new bug report.

### Zigbee2MQTT version

1.32.2-dev commit: 5084b12

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

Sonoff zigbee 3.0 Dongle E

**Comment by Koenkk** [comment]
I see it only partially fixed the problem, pushed a full fix now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
