### ISSUE TITLE
GB-DEVB Development Board doesn't assign port on Linux 

### ISSUE THREAD

**Issue by jpf17** [Koenkk/zigbee2mqtt#1880]
Hello,

I have GB-DEVB Development Board connected via CC-Debugger using a GB2530-S (CC2530 + RFX2401), already followed the path and instructions to Flash the debugger successfully, then switching to Linux to start the Zigbee2mqtt process, when I join /dev and start dmesg command the following thing appears:

[37930.241827] usb usb1-port2: attempt power cycle
[37930.893797] usb 1-2: new full-speed USB device number 12 using xhci_hcd
[37930.893946] usb 1-2: Device not responding to setup address.
[37931.102050] usb 1-2: Device not responding to setup address.
[37931.309747] usb 1-2: device not accepting address 12, error -71
[37931.437851] usb 1-2: new full-speed USB device number 13 using xhci_hcd
[37931.438075] usb 1-2: Device not responding to setup address.
[37931.646034] usb 1-2: Device not responding to setup address.
[37931.853857] usb 1-2: device not accepting address 13, error -71
[37931.853911] usb usb1-port2: unable to enumerate USB device

I tried to Reflash the device with another firmware and nothing happened, i think the issue might be the way im connecting the GB-DEVB to PC (using it through Debugger). I guess there should be a way to tell the board to run on debugger mode or "run" mode. I am concerning at this time the board is always working in debugger mode so Ubuntu is no able to assign the port (/dev/ttyACM0).

I attached the manual for the board I am using now.

[GB-DEVB+development+board+user+manual_2.pdf](https://github.com/Koenkk/zigbee2mqtt/files/3522364/GB-DEVB%2Bdevelopment%2Bboard%2Buser%2Bmanual_2.pdf)

Completing this step is crucial to procced to start running Zigbee2mqtt to this device, i'll really appreciate if you guys can help me.

This is the firmware I am using now: [https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2530_CC2591_DEFAULT_20190608.zip](CC2530_CC2591_DEFAULT_20190608)

I selected that firmware because I read on the issues it works for CC2530 + RFX2401 (GB2530).

Please let me know if you have any idea!

Thanks!

**Comment by TLBM** [comment]
Hi!

> I have GB-DEVB Development Board connected via CC-Debugger using a GB253**0**-S (CC253**0** + RFX2401)

Have you considered the last line on page 5 of the manual 
"5, USB jumper (9) is valid only when connected GB253**1** GB2540 module."?
The CC2530 chip does not have the USB-part of the CC2531.

Can you connect to it directly over RS232 or with a common serial-USB-converter in between?
