### ISSUE TITLE
[Wrong device]: Miboxer FUT035Z+ recognized as Tuya TS0502B Mercator IkuÜ SMD9300 _TZB210_lmqquxus

### ISSUE THREAD

**Issue by filewalker1** [Koenkk/zigbee2mqtt#18810]
### Link

https://miboxer.com/de/produkt/2-in-1-led-controller-zigbee-3-0-2-4g/

### Model

FUT035Z+

### Description

CCT LED Controller

### Vendor

Miboxer

### Picture (link)

https://miboxer.com/wp-content/uploads/a1-51-100x100.jpg

### Database entry

-

**Comment by allthecogs** [comment]
Also, when there is a push type wall switch connected, the state does not update within Z2M, however, if you press the refresh icon on the Exposes > State entry, then the correct state is updated. 
State actions have been set to 'True' and Availability has been reduced to '1', but still requires manually refreshing in Z2M.
Can this be fixed to update when an external switch is used?

**Comment by RdnRzm** [comment]
I have the same problem

**Comment by vladopp** [comment]
I have the issue with the controller. Running latest versions of Z2MQTT and HomeAssistant.
Any way I can help with resolution of the problem?

**Comment by yorickvP** [comment]
See also: https://github.com/Koenkk/zigbee2mqtt/issues/16768

**Comment by yorickvP** [comment]
The + version has some different features though, it can be switched to a mode where it controls a single led strip.
