### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by rax2m** [Koenkk/zigbee2mqtt#18818]
### Link

https://es.aliexpress.com/item/1005003438720832.html?spm=a2g0o.productlist.main.19.52ed31daS6BLXy&algo_pvid=5721fbde-4bd5-416e-8deb-e5244f0e08e1&aem_p4p_detail=202309010648207105162617498400006453215&algo_exp_id=5721fbde-4bd5-416e-8deb-e5244f0e08e1-9&pdp_npi=4%40dis%21AED%2166.59%2127.25%21%21%2118.13%21%21%402101e9d416935761005048117ec5a9%2112000025794706203%21sea%21AE%210%21A&curPageLogUid=rSbVLkPyVC6g&search_p4p_id=202309010648207105162617498400006453215_2

### Database entry

{"id":23,"type":"EndDevice","ieeeAddr":"0x187a3efffe300d02","nwkAddr":14654,"manufId":4098,"manufName":"_TZ3000_cxw02yp3","powerSource":"Battery","modelId":"TS0014","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[3,4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[3,4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":256,"inClusterList":[3,4,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1693428586541,"defaultSendRequestWhen":"immediate"}

### Comments

![111](https://github.com/Koenkk/zigbee2mqtt/assets/85227861/99463721-c280-426b-ac23-005121c7b44c)
Hi 
i bought this 4 gang no neutral switch module it is not supported by z2m. it shows as TS0014. in the zigbee manufacturer it says _TZ3000_cxw02yp3 
so please add support for this device.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
