### ISSUE TITLE
[Wrong device]: IKEA LED1923R5 identified as IKEA LED1925G6

### ISSUE THREAD

**Issue by Joakim-T** [Koenkk/zigbee2mqtt#18821]
### Link

https://www.zigbee2mqtt.io/devices/LED1925G6.html#ikea-led1925g6

### Model

https://www.zigbee2mqtt.io/devices/LED1923R5.html#ikea-led1923r5

### Description

Same as IKEA LED1923R5

### Vendor

Same as IKEA LED1923R5

### Picture (link)

Same as IKEA LED1923R5

### Database entry

Cant find on HA OS

### Notes

Just bought 3 IKEA LED1923R5 lights and paired them. 2 out of 3 pair correctly as IKEA LED1923R5. One pairs as IKEA LED1925G6.
Have tried removing, resetting and re-adding multiple times.
Seems to work fine, just identifies as wrong model.

No idea where to find data/database.db in HA OS.

Interview of device that pairs as the **incorrect** model...

`info  2023-09-01 16:56:28: Device '0x90395efffe537578' joined
info  2023-09-01 16:56:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x90395efffe537578","ieee_address":"0x90395efffe537578"},"type":"device_joined"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/light/0x90395efffe537578/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x90395efffe537578/set","device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":454,"min_mireds":250,"name":"0x90395efffe537578","schema":"json","state_topic":"zigbee2mqtt/0x90395efffe537578","supported_color_modes":["xy","color_temp"],"unique_id":"0x90395efffe537578_light_zigbee2mqtt"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/select/0x90395efffe537578/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x90395efffe537578/set/effect","device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"enabled_by_default":false,"icon":"mdi:palette","name":"0x90395efffe537578 effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0x90395efffe537578_effect_zigbee2mqtt"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/sensor/0x90395efffe537578/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"0x90395efffe537578 power on behavior","state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/select/0x90395efffe537578/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x90395efffe537578/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"entity_category":"config","icon":"mdi:power-settings","name":"0x90395efffe537578 power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/sensor/0x90395efffe537578/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x90395efffe537578 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/sensor/0x90395efffe537578/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","name":"0x90395efffe537578 update state","state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/binary_sensor/0x90395efffe537578/update_available/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"device_class":"update","enabled_by_default":false,"entity_category":"diagnostic","name":"0x90395efffe537578 update available","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_update_available_zigbee2mqtt","value_template":"{{ value_json['update']['state'] == \"available\" }}"}'
info  2023-09-01 16:56:28: MQTT publish: topic 'homeassistant/update/0x90395efffe537578/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0x90395efffe537578"],"manufacturer":"IKEA","model":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)","name":"0x90395efffe537578","sw_version":"1.0.021"},"device_class":"firmware","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","latest_version_template":"{{ value_json['update']['latest_version'] }}","latest_version_topic":"zigbee2mqtt/0x90395efffe537578","name":"0x90395efffe537578","payload_install":"{\"id\": \"0x90395efffe537578\"}","state_topic":"zigbee2mqtt/0x90395efffe537578","unique_id":"0x90395efffe537578_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
info  2023-09-01 16:56:28: Starting interview of '0x90395efffe537578'
info  2023-09-01 16:56:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x90395efffe537578","ieee_address":"0x90395efffe537578","status":"started"},"type":"device_interview"}'
info  2023-09-01 16:56:38: MQTT publish: topic 'zigbee2mqtt/Knapp Vardagsrum Tak', payload '{"action":null,"consumption":0.17,"current":0.02,"device_temperature":28,"energy":0.17,"flip_indicator_light":null,"led_disabled_night":false,"linkquality":204,"operation_mode_left":"decoupled","operation_mode_right":"decoupled","power":2.79,"power_outage_count":5,"power_outage_memory":true,"state":"ON","state_left":"ON","state_right":"ON","voltage":235.69}'
info  2023-09-01 16:56:38: Successfully interviewed '0x90395efffe537578', device has successfully been paired
info  2023-09-01 16:56:38: Device '0x90395efffe537578' is supported, identified as: IKEA TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum (LED1925G6)
info  2023-09-01 16:56:38: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"TRADFRI LED bulb E14 470 lumen, opal, dimmable, white spectrum, color spectrum","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":250},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":454}],"property":"color_temp","type":"numeric","unit":"mired","value_max":454,"value_min":250},{"access":7,"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":7,"description":"Controls the behavior when the device is powered on after power loss","name":"power_on_behavior","property":"power_on_behavior","type":"enum","values":["off","on","toggle","previous"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"LED1925G6","options":[{"access":2,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).","name":"transition","property":"transition","type":"numeric","value_min":0},{"access":2,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).","name":"color_sync","property":"color_sync","type":"binary","value_off":false,"value_on":true},{"access":2,"description":"State actions will also be published as 'action' when true (default false).","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"IKEA"},"friendly_name":"0x90395efffe537578","ieee_address":"0x90395efffe537578","status":"successful","supported":true},"type":"device_interview"}'
info  2023-09-01 16:56:38: Configuring '0x90395efffe537578'
info  2023-09-01 16:56:39: MQTT publish: topic 'zigbee2mqtt/0x90395efffe537578', payload '{"color_mode":"xy","linkquality":228,"power_on_behavior":null,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
info  2023-09-01 16:56:39: MQTT publish: topic 'zigbee2mqtt/0x90395efffe537578', payload '{"color_mode":"xy","linkquality":224,"power_on_behavior":null,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
info  2023-09-01 16:56:39: Successfully configured '0x90395efffe537578'`

Interview of identical device that pairs as the **correct** model...

`info  2023-09-01 16:52:37: Device '0x4c5bb3fffef80df4' joined
info  2023-09-01 16:52:37: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x4c5bb3fffef80df4","ieee_address":"0x4c5bb3fffef80df4"},"type":"device_joined"}'
info  2023-09-01 16:52:37: Starting interview of '0x4c5bb3fffef80df4'
info  2023-09-01 16:53:08: Successfully interviewed '0x4c5bb3fffef80df4', device has successfully been paired
info  2023-09-01 16:53:08: Device '0x4c5bb3fffef80df4' is supported, identified as: IKEA TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)
info  2023-09-01 16:53:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":250},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":454}],"property":"color_temp","type":"numeric","unit":"mired","value_max":454,"value_min":250},{"access":7,"description":"Color temperature after cold power on of this light","name":"color_temp_startup","presets":[{"description":"Coolest temperature supported","name":"coolest","value":250},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":454},{"description":"Restore previous color_temp on cold power on","name":"previous","value":65535}],"property":"color_temp_startup","type":"numeric","unit":"mired","value_max":454,"value_min":250},{"access":7,"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":7,"description":"Controls the behavior when the device is powered on after power loss","name":"power_on_behavior","property":"power_on_behavior","type":"enum","values":["off","on","toggle","previous"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"LED1923R5","options":[{"access":2,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition).","name":"transition","property":"transition","type":"numeric","value_min":0},{"access":2,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true).","name":"color_sync","property":"color_sync","type":"binary","value_off":false,"value_on":true},{"access":2,"description":"State actions will also be published as 'action' when true (default false).","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"IKEA"},"friendly_name":"0x4c5bb3fffef80df4","ieee_address":"0x4c5bb3fffef80df4","status":"successful","supported":true},"type":"device_interview"}'
info  2023-09-01 16:53:08: Configuring '0x4c5bb3fffef80df4'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/light/0x4c5bb3fffef80df4/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x4c5bb3fffef80df4/set","device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":454,"min_mireds":250,"name":"0x4c5bb3fffef80df4","schema":"json","state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","supported_color_modes":["xy","color_temp"],"unique_id":"0x4c5bb3fffef80df4_light_zigbee2mqtt"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/select/0x4c5bb3fffef80df4/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x4c5bb3fffef80df4/set/effect","device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"enabled_by_default":false,"icon":"mdi:palette","name":"0x4c5bb3fffef80df4 effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0x4c5bb3fffef80df4_effect_zigbee2mqtt"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/sensor/0x4c5bb3fffef80df4/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"0x4c5bb3fffef80df4 power on behavior","state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/select/0x4c5bb3fffef80df4/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x4c5bb3fffef80df4/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"entity_category":"config","icon":"mdi:power-settings","name":"0x4c5bb3fffef80df4 power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/sensor/0x4c5bb3fffef80df4/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x4c5bb3fffef80df4 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/sensor/0x4c5bb3fffef80df4/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","name":"0x4c5bb3fffef80df4 update state","state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/binary_sensor/0x4c5bb3fffef80df4/update_available/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"device_class":"update","enabled_by_default":false,"entity_category":"diagnostic","name":"0x4c5bb3fffef80df4 update available","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_update_available_zigbee2mqtt","value_template":"{{ value_json['update']['state'] == \"available\" }}"}'
info  2023-09-01 16:53:08: MQTT publish: topic 'homeassistant/update/0x4c5bb3fffef80df4/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0x4c5bb3fffef80df4"],"manufacturer":"IKEA","model":"TRADFRI LED bulb GU10 345 lumen, dimmable, white spectrum, color spectrum (LED1923R5)","name":"0x4c5bb3fffef80df4","sw_version":"1.0.021"},"device_class":"firmware","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","latest_version_template":"{{ value_json['update']['latest_version'] }}","latest_version_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","name":"0x4c5bb3fffef80df4","payload_install":"{\"id\": \"0x4c5bb3fffef80df4\"}","state_topic":"zigbee2mqtt/0x4c5bb3fffef80df4","unique_id":"0x4c5bb3fffef80df4_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
info  2023-09-01 16:53:09: MQTT publish: topic 'zigbee2mqtt/0x4c5bb3fffef80df4', payload '{"color_mode":"xy","linkquality":204,"power_on_behavior":null,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
info  2023-09-01 16:53:09: MQTT publish: topic 'zigbee2mqtt/0x4c5bb3fffef80df4', payload '{"color_mode":"xy","linkquality":204,"power_on_behavior":null,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
info  2023-09-01 16:53:09: Successfully configured '0x4c5bb3fffef80df4'`

**Comment by Koenkk** [comment]
These devices seem to use the same modelID, I've changed the model to `LED1923R5/LED1925G6`

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by DennisJohnsen** [comment]
Not sure if this is related, but now my LED1923R5 is not showing up with a picture in Zigbee2mqtt frontend, but since i comment here, is because https://www.zigbee2mqtt.io/devices/LED1923R5.html#ikea-led1923r5 is now showing up as 404. So not sure what changed.

**Comment by mrskycriper** [comment]
@Joakim-T Hello, can you please share Zigbee models of those different lamps? I'm doing a bit of a cleanup and it seems that `LED1925G6` is an E12/E14/E17 model. While `LED1923R5` is associated with GU10 bulbs. In fact, LED1925G6 exist in a database separately.

@Koenkk is there any particular reason, as to why the model name was changed? The Zigbee models seem to be unaffected, so it should not have changed the model detection here, just renamed existing GU10 bulbs.

This whole situatuon is looking really confusing to me.

**Comment by Koenkk** [comment]
@mrskycriper if they have different Zigbee models, we can separate them again.

**Comment by mrskycriper** [comment]
> @mrskycriper if they have different Zigbee models, we can separate them again.

The other model is already present in the database. I'm really confused as to why it was written twice.

**Comment by Koenkk** [comment]
It's strange, either the fw @Joakim-T is bugged or it's a one time mess up from IKEA
