### ISSUE TITLE
TS0505B Bulb

### ISSUE THREAD

**Issue by milandzuris** [Koenkk/zigbee2mqtt#18824]
### What happened?

Model: TuYa TS0505B_1_2, i have a problem when im change color on Bulb not change only change color when im change brightness, same problem in Z2M Dashobard, MQTT, HA.

### Zigbee2MQTT version

*

### Adapter firmware version

20221102

### Adapter

Sonoff  zStack3x0

**Comment by milandzuris** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/18416

**Comment by maxgluzman** [comment]
i have the same issue

**Comment by milandzuris** [comment]
@Koenkk

**Comment by maxgluzman** [comment]
still an issue

**Comment by djcrawleravp** [comment]
Still an issue for me, that's why I'm stuck on Z2M 1.33.1
