### ISSUE TITLE
[New device support]: Hive Thermostat SLT3d (easy fix)

### ISSUE THREAD

**Issue by liamstears** [Koenkk/zigbee2mqtt#18844]
### Link

https://www.hivehome.com/guides/hive-heating

### Database entry

{"id":4,"type":"EndDevice","ieeeAddr":"0x001e5e09028fa14d","nwkAddr":53005,"manufId":4153,"manufName":"Computime","powerSource":"Battery","modelId":"SLT3d","epList":[9],"endpoints":{"9":{"profId":260,"epId":9,"devId":770,"inClusterList":[0,1,3,9,10,32,513,516,1026,64768],"outClusterList":[0,3,25,513],"clusters":{"genBasic":{"attributes":{"modelId":"SLT3d","manufacturerName":"Computime","powerSource":3,"zclVersion":8,"appVersion":8,"stackVersion":0,"hwVersion":0,"dateCode":"20210712"}},"genPollCtrl":{"attributes":{"checkinInterval":480}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffeb3d781","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":8,"stackVersion":0,"hwVersion":0,"dateCode":"20210712","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1693704109768,"defaultSendRequestWhen":"fastpoll","checkinInterval":120}

### Comments

I have the newest Hive Thermostat which has receiver SLR1c (already supported) and controller SLT3d (not supported)

I have paired devices and everything works perfectly as expected

I can't find any information about SLT3d and what are differences between it and SLT3c but I think they are exactly the same (must be some minor hardware revision I think) so could we add SLT3d device as supported using SLT3c converted etc?

Thank you in advance and thanks for all the hard work :-D

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
