### ISSUE TITLE
Sonoff Door Sensor False Positives

### ISSUE THREAD

**Issue by BlueWings172** [Koenkk/zigbee2mqtt#18849]
### What happened?

I was using my Sonoff SNZB-04 door sensor with ZHA for months and it was working fine. I switched the zigbee2mqtt and everything seemed fine at the beginning but then I started to noticed that the sensor reports multiple close events when the door is already closed and multiple open events when the door is open to Home Assistant

I don't understand why this happens if no one touched the door. How can I stop my door sensor and HA from hallucinating?

I would appreciate any help.

Thanks

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65966061/943e19d5-26fb-4af3-ad6a-d558adf82076)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65966061/ba8ea4f3-724e-4b46-9002-532d1101eae3)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65966061/3215c1c0-bc15-41bf-b358-af13323086ab)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65966061/fb021c7b-dca0-42e0-be0f-8b3421009834)

### Zigbee2MQTT version

1.32.2 commit: 1ec1e57

### Adapter firmware version

20211115

### Adapter

CC2531

**Comment by BlueWings172** [comment]
Does anyone have an idea how to solve this??
My sensor became completely useless and reports false events all the time.

**Comment by BlueWings172** [comment]
I would appreciate any help on this. Still having the same issue.

**Comment by BlueWings172** [comment]
@KayGt3 
Unfortunately, I haven't.
It appears that zigbee2mqtt reports the battery level and then Home Assistant interprets this as a door action. so if the door is closed, it keeps reporting that door is closed every hour or so again and again and then when the door is opened, it keeps reporting the door is open multiple times.

I don't know how to disable the battery reports in z2m or how to get HA to distinguish between these battery reports and an actual door opening or closing. 

I tried to search online but couldn't find a solution. If you find one, please let me know.

Thanks

**Comment by KayGt3** [comment]
This is the behaviour of mine:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/34492088/923d3f57-b042-4aa4-8644-69ea8b2e9e9c)

I will let you know if i will find something!
