### ISSUE TITLE
Inovelli Blue Dimmer stop supporting multi-tap

### ISSUE THREAD

**Issue by Motya-HA** [Koenkk/zigbee2mqtt#18845]
### What happened?

After latest update, all Inovelli devices stoped supporting multi-tap. In device trigger option "down double" or "up double " not exposed any more

### How to reproduce it (minimal and precise)

Fix the issue

### Zigbee2MQTT version

1.33.0-0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by Raze42** [comment]
Also having this issue and it is described further by other on the inovelli forms at: https://community.inovelli.com/t/blue-2-in-1-firmware-2-15-multi-tap-stoped-working/14963/27
