### ISSUE TITLE
Can only set color temp of Flair RGBW LED bulb

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [Koenkk/zigbee2mqtt#18850]
### What happened?

Hi! After turning on a new Flair RGBW E27 bulb ([Z2M device page](https://www.zigbee2mqtt.io/devices/10454471.html)) the bulb clearly shows it's capable of RGB :) 

However, in Z2M only color temp is being shown. Also from HA I can't set any color, just change the color temp. Also in the Z2M documentation of this device, I see no mention of RGB.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2611894/889740b9-b704-4ff6-ad68-b18b48b23f24)

### What did you expect to happen?

I would expect to be able to set both RGB color and white color temp.

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

20230507

### Adapter

zzh

**Comment by Koenkk** [comment]
Added color support!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
