### ISSUE TITLE
Philips Hue White Filament 9290030517(01) is implemented as Hue White Ambiance Filament

### ISSUE THREAD

**Issue by woerndlit** [Koenkk/zigbee2mqtt#18858]
### What happened?

- Paired the newest generation of Philips Hue White Filament Bulb (929003051701).

- After pairing the device showed options for White Ambiance devices.

- Checked Zigbee2MQTT implentation documentation for the device. 

- Zigbee2MQTT documentation shows the device is Philips Hue White Ambiance.  (https://www.zigbee2mqtt.io/devices/9290030517.html)

- Checked vendor page to verify model is Hue White Filament and not Hue White Ambiance Filament. (https://www.philips-hue.com/en-gb/p/hue-white-filament-st64-edison---e27-smart-bulb/8719514342989#specifications)

- Device 929003051701 is not reacting to White Ambiance commands as expected.

### What did you expect to happen?

Device 929003051701 showing up as Philips Hue White Filament

### How to reproduce it (minimal and precise)

1. Pair 929003051701 deivce
2. Verify controls showing White Ambiance options instead of limited White Filament options.

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF Zigbee Gateway, ZBDongle-E 3.0 USB Dongle Plus,EFR32MG21 + CH9102F Zigbee USB-Stick EFR32MG21 Coordinator

**Comment by zegl** [comment]
@woerndlit Could you please share the entry of this device from `data/database.db`? It's needed to help to disambiguate the two devices.

**Comment by woerndlit** [comment]
@zegl 
You mean this entry?

{"id":25,"type":"Router","ieeeAddr":"0x001788010d305149","nwkAddr":63473,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LWV005","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":257,"inClusterList":[0,3,4,5,6,8,4096,64514],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"dateCode":"20230403","swBuildId":"1.104.2"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":2,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1693820643030,"defaultSendRequestWhen":"immediate"}

**Comment by zegl** [comment]
Thanks, I've created a PR to correctly identify this device. :)

**Comment by woerndlit** [comment]
Thank you.

**Comment by Koenkk** [comment]
Thanks @zegl !

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
