### ISSUE TITLE
Sylvania LIGHTIFY Br30 RGBW changes to LEDVANCE with no modelID cannot control

### ISSUE THREAD

**Issue by haberda** [Koenkk/zigbee2mqtt#1885]
# Bug Report
## What happened
I have several Sylvania/Osram Lightify Br30 bulbs: https://www.zigbee2mqtt.io/devices/73739.html

When they pair they identify in the database as: "manufName":"OSRAM" with "modelId":"LIGHTIFY BR RGBW"

With this configuration the lights work as expected. However, after a day or so both entries change to: "manufName":"LEDVANCE" and "modelId":""

At this point the lights seem to still serve as a router but do not respond to commands. When I manually change the database entries back to when they first paired they work again for a short period (day or so) and then revert back to the LEDVANCE configuration.

I have repaired the lights many times.

## What did you expect to happen

The database entries should not change and the lights should continue to work.

## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Koenkk** [comment]
This is probably an issue from zigbee-shepherd and will be fixed in zigbee-herdsman (see https://github.com/Koenkk/zigbee2mqtt/issues/1888)
