### ISSUE TITLE
[New device support]: Gledopto Light Bar GL-LB-001P

### ISSUE THREAD

**Issue by ov1d1u** [Koenkk/zigbee2mqtt#18870]
### Link

https://www.aliexpress.com/item/1005005732547817.html

### Database entry

{"id":39,"type":"Router","ieeeAddr":"0xa4c138ea59863ae3","nwkAddr":62136,"manufId":4687,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-LB-001P","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"GL-LB-001P","manufacturerName":"GLEDOPTO","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230515","swBuildId":"20251203"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":158,"colorTempPhysicalMax":495}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230515","swBuildId":"20251203","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1693905105092,"defaultSendRequestWhen":"immediate"}

### Comments

I'm using the converter for Gledopto GL-MC-001P for it and everything seems to work normal.

### External converter

```shell
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const utils = require('zigbee-herdsman-converters/lib/utils');
const extend = require('zigbee-herdsman-converters/lib/extend');

const gledoptoExtend = {
    light_onoff_brightness_colortemp_color: (options={}) => ({
        ...extend.light_onoff_brightness_colortemp_color({disablePowerOnBehavior: true, supportsHueAndSaturation: true, ...options}),
        toZigbee: utils.replaceInArray(
            extend.light_onoff_brightness_colortemp_color(options).toZigbee,
            [tz.light_onoff_brightness, tz.light_color_colortemp],
            [tz.gledopto_light_onoff_brightness, tz.gledopto_light_color_colortemp],
        ),
    }),
};

const definition = {
        zigbeeModel: ['GL-LB-001P'],
        model: 'GL-LB-001P',
        vendor: 'Gledopto',
        description: 'Zigbee USB LED BAR RGB+CCT (pro)',
        extend: gledoptoExtend.light_onoff_brightness_colortemp_color(),
    };

module.exports = definition;
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMin":158,"colorTempPhysicalMax":495}

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
