### ISSUE TITLE
Fail to connect to mqtt with no information

### ISSUE THREAD

**Issue by daufinsyd** [Koenkk/zigbee2mqtt#18883]
### What happened?

Zigbee2mqtt won't start because it won't connect to MQTT Server.

Using mqtt explorer i can connect to it and the mqtt server even see the request from z2m coming: 
2023-09-06 15:05:18: New connection from 172.30.32.2:46836 on port 1883.
2023-09-06 15:05:18: Client <unknown> closed its connection

even with debug mod enabled, z2m doesn't give information on why it couldn't connect .

### What did you expect to happen?

Z2M connects to mqtt and starts (opr at least gives more information on why it couldn't connect).

### How to reproduce it (minimal and precise)

here is the config

homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://lvviha1.local.0:1883
  user: USER
  password: PWD
serial:
  port: /dev/ttyUSB0
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  log_level: debug
device_options:
  legacy: false
frontend:
  port: 8080
  host: 0.0.0.0
availability: true

it worked flawlessly until today

### Zigbee2MQTT version

1.33.0 (commit #7ee207f)

### Adapter firmware version

20221102

### Adapter

zStack3x0

### Debug log

podman start -a zigbee2mqtt_zigbee2mqtt_1
[zigbee2mqtt] | Using '/app/data' as data directory
[zigbee2mqtt] | Zigbee2MQTT:debug 2023-09-06 15:10:13: Loaded state from file /app/data/state.json
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:13: Logging to console and directory: '/app/data/log/2023-09-06.15-10-13' filename: log.txt
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:13: Starting Zigbee2MQTT version 1.33.0 (commit #7ee207f)
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:13: Starting zigbee-herdsman (0.18.5)
[zigbee2mqtt] | Zigbee2MQTT:debug 2023-09-06 15:10:13: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: zigbee-herdsman started (resumed)
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20221102,"transportrev":2},"type":"zStack3x0"}'
[zigbee2mqtt] | Zigbee2MQTT:debug 2023-09-06 15:10:25: Zigbee network parameters: {"channel":11,"extendedPanID":"0x00124b0024bc1ac1","panID":6754}
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: Currently 0 devices are joined:
[zigbee2mqtt] | Zigbee2MQTT:warn  2023-09-06 15:10:25: `permit_join` set to  `true` in configuration.yaml.
[zigbee2mqtt] | Zigbee2MQTT:warn  2023-09-06 15:10:25: Allowing new devices to join.
[zigbee2mqtt] | Zigbee2MQTT:warn  2023-09-06 15:10:25: Set `permit_join` to `false` once you joined all devices.
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: Zigbee: allowing new devices to join.
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: Connecting to MQTT server at mqtt://lvviha1.local.0:1883
[zigbee2mqtt] | Zigbee2MQTT:debug 2023-09-06 15:10:25: Using MQTT login with username: sxMqtt
[zigbee2mqtt] | Zigbee2MQTT:error 2023-09-06 15:10:25: MQTT failed to connect, exiting...
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:25: Stopping zigbee-herdsman...
[zigbee2mqtt] | Zigbee2MQTT:info  2023-09-06 15:10:37: Stopped zigbee-herdsman
exit code: 1

**Comment by daufinsyd** [comment]
Starting z2m with koenkk/zigbee2mqtt:1.32.1 does work.

**Comment by Hypfer** [comment]
> lvviha1.local.0

Is that mDNS? I wouldn't use mDNS for the MQTT server.
Also, why the .0?

**Comment by daufinsyd** [comment]
the .0 is my top level name for intern LAN, it works with previous versions (1.32.1).
Before rolling back to this version, I tried with the latest using IP instead of domain name but it didn't work.

**Comment by esackbauer** [comment]
Very similar here after upgrading from 1.32.1 to 1.33.1:
`Zigbee2MQTT:warn  2023-10-07 12:48:59: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2023-10-07 12:48:59: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-10-07 12:48:59: Connecting to MQTT server at mqtt://10.0.0.51
Zigbee2MQTT:error 2023-10-07 12:48:59: MQTT failed to connect: Cannot read properties of undefined (reading 'connect')
Zigbee2MQTT:error 2023-10-07 12:48:59: Exiting...
Zigbee2MQTT:info  2023-10-07 12:48:59: Stopping zigbee-herdsman...
Zigbee2MQTT:info  2023-10-07 12:49:09: Stopped zigbee-herdsman
`

Going back to 1.32.1 and everything is back to normal.

I am running on Windows with nodejs version v16.20.1

**Comment by Koenkk** [comment]
@esackbauer did you do a `npm ci` and `npm run build` after updating z2m?

**Comment by esackbauer** [comment]
> @esackbauer did you do a `npm ci` and `npm run build` after updating z2m?

Yes I did.

**Comment by esackbauer** [comment]
@Koenkk Never mind, I redid everything with a little more time and snapshots, and voila now it works. Don't know what I did different but anyways here are my steps for **Windows**:

1. upgrading first Home Assistant from 2023.8.4 to 2023.10.1
2. Confirm that Zigbee2MQTT version 1.32.1 is still working as expected
3. Backing up Z2Ms data directory
4. deleting the whole Z2M folder
5. extracting the Z2M archive from version 1.33.1 into the Z2M folder
6. npm install
7. npm ci
8. npm run build
9. copy back the saved files into data directory
10. npm start
