### ISSUE TITLE
BE468 smart lock - setting the pin code not working

### ISSUE THREAD

**Issue by RMNB** [Koenkk/zigbee2mqtt#18912]
### What happened?

When using the web ui to set the pin code for users, I get the error message below. This is when setting for users 0-29. Friendly name is "Front Door Lock"

`Publish 'set' 'pin_code' to 'Front Door Lock' failed: 'Error: user must be numbers'`

When try setting a pin code for users outside 0-29 I get an error that the user is out of bounds. 

### What did you expect to happen?

I was previously able to set pin codes using the web ui front end.

### Zigbee2MQTT version

1.33.0-dev commit: ea8de2b

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

2023-09-08 13:11:41Publishing 'set' 'pin_code' to 'Front Door Lock'
2023-09-08 13:11:41Error: user must be numbers at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.js:185:36) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:52) at EventEmitter.emit (node:events:526:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:127:27) at WebSocket.emit (node:events:514:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20) at Receiver.emit (node:events:514:28) at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)

**Comment by alex-siqueira** [comment]
Same problem here: seems to be a recent bug.

**Comment by maxi1134** [comment]
I also have this bug with my schlague lock. Since a few months actually.

**Comment by RMNB** [comment]
I'm going to try setting the code manually using the number pad.

**Comment by maxi1134** [comment]
> I'm going to try setting the code manually using the number pad.

This works for me; But then trying to add a code from Z2M breaks that initial code entered in the lock.

**Comment by Montreal666** [comment]
Same here. following.

**Comment by StephenJondrew** [comment]
I am encountering the same thing with the YRD256.

- When trying to enter a code in Z2M the lock failed: 'Error: user must be numbers'
- This error happens with either an empty or full slot
- When attempting to control a code slot that has a code already, the code is cleared from the lock for that slot

**Comment by AliSuleiman01** [comment]
i have the same issue as well. trying to set one also deletes the one i set manually on the lock itself

**Comment by zecoj** [comment]
I also have the exact same issue and behaviour with this lock [Yale YDD-D4F0-TSDB](https://www.zigbee2mqtt.io/devices/YDD-D4F0-TSDB.html). Trying to set code for an existing user (0-249) will result in that user's code being deleted, and won't work for new users.

**Comment by Montreal666** [comment]
For people experiencing the issue, are you using the Home assistant add-on? Asking because I recently migrated to HA and the pin code feature was working prior. Maybe just a coincidence. Otherwise just wondering how it was broken; other than the Z2M update itself were there any changes to the Yale support code? Did you try rolling back to a prior version?

**Comment by zecoj** [comment]
1. Yes, I'm using the Home Assistant add-on
2. It was working prior, I know this because I used to set up the lock previously. I noticed it stopped working a couple weeks ago but thought it was something wrong with my lock, which I don't think received any update since installed.
3. No I didn't try to roll back z2m, mainly because I don't know when it was broken.

**Comment by RMNB** [comment]
I'm not using the addon. Z2m is installed using docker for me and I have the issue.

**Comment by Montreal666** [comment]
Did anyone have a chance to test with the latest Z2M release ( https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.33.2) ?
I don't see anything Yale related in the fixes but just in case...
will test later has I temporarily switched these locks to a secondary ZHA controller...

**Comment by zecoj** [comment]
I tried to set the pin to a couple of users and it seems to be working. No more error and code is set for the corresponding user ID correctly!

**Comment by RMNB** [comment]
Working for me now as well! I'm going to close the issue.

**Comment by maxi1134** [comment]
Works with the Schlage as well!
