### ISSUE TITLE
Philips Hue LWV006 Not Supported On Device Add

### ISSUE THREAD

**Issue by ei-eiron** [Koenkk/zigbee2mqtt#18911]
### What happened?

Just tried to add this device:

https://zigbee.blakadder.com/Philips_LWV006.html

I'm not sure if it's officially supported or not, but seems to be, based on the above. 
This is giving me a "device not supported error" and exposes no usable functions.

Sorry - Is it officially supported?
If not, what needs to be done to support it?

### What did you expect to happen?

The device to be added like other lightbulbs

### How to reproduce it (minimal and precise)

Tell Z2M to allow all devices

Plug in lightbulb near bridge

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20210708

### Adapter

Sonoff Bridge Type-P

### Debug log

I will add this if there is no obvious solution. Thanks!

**Comment by Koenkk** [comment]
It has been added in z2m 1.33.0
