### ISSUE TITLE
[New device support]: Philips Hue LTA013 Filament A60 550lm E26

### ISSUE THREAD

**Issue by sympapa** [Koenkk/zigbee2mqtt#18915]
### Link

https://www.philips-hue.com/ja-jp/p/hue-white-ambiance-a60---e26-smart-bulb/8720169162471

### Database entry

{"id":116,"type":"Router","ieeeAddr":"0x001788010d880da6","nwkAddr":37915,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LTA013","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230116","swBuildId":"1.101.10","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1694206712668,"defaultSendRequestWhen":"immediate"}

### Comments

Hi!

The Hue Filament bulb A60 550lm E26 was released in Japan this summer.
It is recognized as LTA013 and not supported.
I have created a external converter.
I am new to this but it seems to work fine.

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['LTA013'],
    model: '929003596001',
    vendor: 'Philips',
    description: 'Hue Filament A60 550lm E26',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [222, 454]}),
};

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

 {"colorTempPhysicalMin":222,"colorTempPhysicalMax":454}

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
