### ISSUE TITLE
Devices behind routers stopped working normally after updating

### ISSUE THREAD

**Issue by airens** [Koenkk/zigbee2mqtt#18925]
### What happened?

Hi, yesterday updated my ZigStar ethernet cooridinator to 20230507 and my network really feels bad now. Some devices periodically go offline, other tell that they ok but not report correct state (door sensors) or do not execute commands (curtains). Do I need to repair problematic devices or there is some better way to fix this?

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

20230507

### Adapter

ZigStar CC2652P (zStack3x0)

**Comment by Koenkk** [comment]
Try the 20230901 firmware from [here](https://github.com/Koenkk/Z-Stack-firmware/discussions/474) and provide your feedback there if it improves.
