### ISSUE TITLE
Updating to 1.33 changes Names to "MQTT Sensor"

### ISSUE THREAD

**Issue by PuckStar** [Koenkk/zigbee2mqtt#18930]
### What happened?

Updating to 1.33 changes Names to "MQTT Sensor" or "MQTT Binary Sensor".
I notice I can change it manually again: When I edit an entity and click in the Name field it still shows the old friendly name in light grey. When I type that in and save it it's OK.

However I prefer not to have to do that for the many entities I have so I restored to 1.32.2-1

Not sure if related to this: https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099
But I run Home Assistant 2023.4.2, so no 2023.8.
Unless they are speaking about Supervisor, because that version I have is Supervisor 2023.08.3

### Zigbee2MQTT version

1.32

### Adapter firmware version

n/a

### Adapter

n/a

**Comment by timon** [comment]
Thanks for pin-pointing version. Pinning to `1.32.2` as per your suggestion fixed the issue for me as well

**Comment by Koenkk** [comment]
You need to use at least HA 2023.8 for z2m 1.33.0 (https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.33.0)
