### ISSUE TITLE
Sunricher SR-ZG9080A wrong MQTT state

### ISSUE THREAD

**Issue by BenRyde** [Koenkk/zigbee2mqtt#18945]
### What happened?

Sunricher SR-ZG9080A trained, everything is good.

Roller blind is closed, Sunricher SR-ZG9080A sends the state "open".
Clicking on “open” opens the blind.

Roller blind is open, Sunricher SR-ZG9080A sends the state "closed". Click on “close” to close the blind.

Invert cover helps to invert the position, but not the "state".

Basically, only the wrong state is sent. it should be exactly the other way around.

### What did you expect to happen?

mqtt state should be correct.

Swapping the cables from the roller blind doesn't work either. then the state is correct, but I can no longer use it, ie. If the roller blind is closed, I can only open it again by clicking on "close".

### Zigbee2MQTT version

 1.33.0 commit: f224ef7b

### Adapter firmware version

20220219

### Adapter

tubeszb-cc2652-poe-2022

**Comment by anharald** [comment]
same problem here with LED-Trading 9135 :( no solution until now
