### ISSUE TITLE
 [Wrong device]: TS1101_dimmer_module_2ch recognized as TS0052(1ch)

### ISSUE THREAD

**Issue by Destroyer061090** [Koenkk/zigbee2mqtt#18953]
### Link

https://www.zigbee2mqtt.io/devices/TS1101_dimmer_module_2ch.html

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0xa4c138fd43b5a44b","nwkAddr":14020,"manufId":4417,"manufName":"_TZ3000_zjtxnoft","powerSource":"Mains (single phase)","modelId":"TS0052","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,8,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAA"}},"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":0}},"manuSpecificTuya_3":{"attributes":{"switchType":0}},"genLevelCtrl":{"attributes":{"currentLevel":254,"minLevel":2,"maxLevel":254,"onOffTransitionTime":50}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6,57345,8],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"attributes":{"currentLevel":254,"minLevel":2,"maxLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1694508277478,"defaultSendRequestWhen":"immediate"}

### Comments

i tried to re-pairing several time but without success. I have 2 device with the same issues

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/de21f20612fa9b7ff99fed7300e3a423

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by Destroyer061090** [comment]
Partially it’s works. Now, inside Z2M I see both channel but on MQTT brocker all the entities disappeared.

![IMG_1784](https://github.com/Koenkk/zigbee2mqtt/assets/126196958/68e02c01-29fa-41ca-9e9e-edd858de6ffb)
![IMG_1785](https://github.com/Koenkk/zigbee2mqtt/assets/126196958/92c3e77b-5202-456d-83ac-eb50d1259d4e)

**Comment by Destroyer061090** [comment]
Partially it’s works. Now, inside Z2M I see both channel but on MQTT brocker all the entities disappeared.
![Uploading IMG_1784.jpeg…]()

**Comment by Koenkk** [comment]
Can you try to force remove the device through the z2m frontend and pair it again?

**Comment by Destroyer061090** [comment]
it works! thank you so much!
