### ISSUE TITLE
Lost on/off state for TS0001 switches after 1.33.0-1 update

### ISSUE THREAD

**Issue by patrick-foubert-56770** [Koenkk/zigbee2mqtt#18952]
### What happened?

After udate all TS0001 switches have same issue:

Cette entité n'est plus fournie par l'intégration mqtt. Si l'entité n'est plus utilisée, supprimez-la depuis les paramètres.
This entity was not longer supported by mqtt...

If i look logs during on/off

Info 2023-09-12 09:48:31MQTT publish: topic 'zigbee2mqtt_2/Inter-Etage-Dressing', payload '{"linkquality":98,"power_on_behavior":"previous","state":"ON"}'
Debug 2023-09-12 09:48:32Received Zigbee message from 'Inter-Etage-Dressing', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info 2023-09-12 09:48:32MQTT publish: topic 'zigbee2mqtt_2/Inter-Etage-Dressing', payload '{"linkquality":94,"power_on_behavior":"previous","state":"OFF"}'

But not state change

### What did you expect to happen?

upgrade issue

### Zigbee2MQTT version

1.33.0-1

### Adapter firmware version

20220219

### Adapter

SLZB-06

**Comment by Gollam** [comment]
Same happening with ikea tradfri

**Comment by Paweu00** [comment]
Same problem....
<img width="500" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/82401951/cbcfbf74-c3b4-4a02-aa63-bbbe890d940b">

**Comment by francisp2** [comment]
Are you on HA 2023-9 or 2023-9 ?

**Comment by Gollam** [comment]
@francisp2 You asked the same thing twice, but as for me, I am on 2023.9.2.

**Comment by francisp2** [comment]
Mine work nice, but I only added them on 1.33

![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/7a122aec-1d35-404b-b560-17806ded4857)

**Comment by Gollam** [comment]
I still have this issue with 1.33.1.

**Comment by riegelbrau** [comment]
I have this issue with a "MHCOZY 1 gang switch (TS0001)" and Zigbee2MQTT version 1.35.1 (commit #3c962042) tigether with the homeassistant integration in openHAB 4.0.4.
This is the config payload for the switch in `homeassistant/switch/0xa4c1380868f7bc9b/switch/config`:
`{
	"availability": [
		{
			"topic": "zb2mqtt/bridge/state"
		},
		{
			"topic": "zb2mqtt/0xa4c1380868f7bc9b/availability"
		}
	],
	"availability_mode": "all",
	"command_topic": "zb2mqtt/0xa4c1380868f7bc9b/set",
	"device": {
		"identifiers": [
			"zigbee2mqtt_0xa4c1380868f7bc9b"
		],
		"manufacturer": "TuYa",
		"model": "1 gang switch (TS0001)",
		"name": "0xa4c1380868f7bc9b",
		"via_device": "zigbee2mqtt_bridge_0x00212effff06c0d7"
	},
	"json_attributes_topic": "zb2mqtt/0xa4c1380868f7bc9b",
	"name": null,
	"object_id": "0xa4c1380868f7bc9b",
	"origin": {
		"name": "Zigbee2MQTT",
		"sw": "1.35.1",
		"url": "https://www.zigbee2mqtt.io"
	},
	"payload_off": "OFF",
	"payload_on": "ON",
	"state_topic": "zb2mqtt/0xa4c1380868f7bc9b",
	"unique_id": "0xa4c1380868f7bc9b_switch_zb2mqtt",
	"value_template": "{{ value_json.state }}"
}`
The Thing gets created with all expected config topics:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/73437730/1ac0a05d-627d-4f1c-a1c7-46708d3c9c54)
But only these advaced channels appear:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/73437730/1cf154d1-44bd-4b8e-b224-17f726261b06)

This is the message when I press the button that switches ON/OFF in `zb2mqtt/0xa4c1380868f7bc9b:`
`{"last_seen":"2024-01-24T17:22:35.483Z","linkquality":255,"power_on_behavior":"off","state":"ON"}`
