### ISSUE TITLE
Limitations of amount of groups and devices per group

### ISSUE THREAD

**Issue by kalsan** [Koenkk/zigbee2mqtt#1896]
I'm new to ZigBee, LightLink, Open Source Home Automation and friends. I'm a bit confused by the various limits of devices connected to a ZigBee gateway. Hope the following questions aren't too silly. What confuses me is:

- According to https://www.zigbee2mqtt.io/information/FAQ.html , zigbee2mqtt seem to support up to 25 devices without a router, or 15 routers (is what the calculation suggests) with up to 21 devices per router
- Ikea Gatways seem to support up to 10 groups with up to 10 devices each: https://www.reddit.com/r/tradfri/comments/alazgs/max_number_of_devices_per_gateway/

So what about groups with zigbee2mqtt: Assuming that all devices are Ikea Tradfri, are the Ikea limitations affecting zigbee2mqtt or is that not the case because zigbee2mqtt replaces the Ikea Gateway? In other words, with zigbee2mqtt and end devices (lamps and sensors) by Tradfri as an example,

- is there a limitation of the amount of end devices in a group?
- is there a limitation of the amount of total groups?
- is the total amount of end devices that can be supported by zigbee2mqtt with CC2531 15 routers x 21 devices per router = 315 devices?

Thanks a lot in advance for clarifying this.

**Comment by Koenkk** [comment]
is there a limitation of the amount of end devices in a group?
No

is there a limitation of the amount of total groups?
No, but depending on the device, it can be in a limited amount of groups.

is the total amount of end devices that can be supported by zigbee2mqtt with CC2531 15 routers x 21 devices per router = 315 devices

theoretically yes, but the CC2531 can not handle this, users have reported that 50-60 devices still work well if you dont use the reporting and availability feature. More powerful devices (like CC2652R) are in the process of being supported)

I will close this as its not an issue.
