### ISSUE TITLE
PJ-MGW1203 - does not report energy, all other fields are OK

### ISSUE THREAD

**Issue by papperone** [Koenkk/zigbee2mqtt#18977]
### What happened?

I just bought this device (https://it.aliexpress.com/item/1005004948381800.html) and connected to test its functionality, all seems ok, I can see all values exposed with right numbers but "energy" is always "null", even with a load; I left it working from more than 1h and no changes...

### What did you expect to happen?

I expected "energy" value to appears after a while

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

6.7.9.0 build 405

### Adapter

ZB-GW04 based on EFR32MG21

### Debug log

this is the paylog I keep getting
payload '{"current":0.42,"energy":null,"linkquality":152,"power":94.3,"voltage":227.1}'

**Comment by JanButter** [comment]
Hi, i have the same.  Connected two of these devices and voltage, current and power are working but the amount of energy is not calculated.  
![image](https://github.com/Koenkk/zigbee2mqtt/assets/127992407/69375022-7794-4af9-a697-7345bbc37376)

**Comment by Poupi1972** [comment]
Hello
Same issue for me
Is someone have a solution
Regards

**Comment by Douglasfc** [comment]
Same issue here.
Hope someone can help us.

BR

**Comment by wolfwander** [comment]
Same issue here, it seems it is wrongly calculated.
