### ISSUE TITLE
Impossible to use my zigbee2MQTT since I update from Jessie to Stretch

### ISSUE THREAD

**Issue by tFREYERMUTH** [Koenkk/zigbee2mqtt#1899]
Hello

I have been using a Zigbee2Mqtt gateway for a long time to use my Aqara modules without going through the Xiaomi gateway.

Mosquito is installed on the same raspberry Pi as my Jeedom which uses the MQTT plugin.
Everything worked fine until I made an update of my Linux: I went from Jessie to Stretch.

At first I had some problems with Demon that was no longer launched, but that I was able to quickly adjust by reinstalling the dependencies.

But unfortunately since, I have constantly (every second) a message that says 
                "The client is not currently connected." 
and of course my modules do not go up anymore. yet the demon seems to be working well and the Mosquito looks running.

I reinstalled npm and zigbee2MQTT from scratch but when I start npm through ssh I get the following messages :

> zigbee2mqtt@1.5.1 start /opt/zigbee2mqtt
> node index.js

  zigbee2mqtt:info 2019-8-27 11:59:22 AM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-08-27.11-59-19'
  zigbee2mqtt:info 2019-8-27 11:59:23 AM Starting zigbee2mqtt version 1.5.1 (commit #ac3b924)
  zigbee2mqtt:info 2019-8-27 11:59:23 AM Starting zigbee-shepherd
  zigbee2mqtt:info 2019-8-27 11:59:23 AM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: Error Resource temporarily unavailable Cannot lock port)
  zigbee2mqtt:info 2019-8-27 12:00:23 PM Starting zigbee-shepherd
  zigbee2mqtt:error 2019-8-27 12:00:23 PM Error while starting zigbee-shepherd! (Error: Error Resource temporarily unavailable Cannot lock port)
  zigbee2mqtt:error 2019-8-27 12:00:23 PM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 2019-8-27 12:00:23 PM Failed to start
        {"message":"Error Resource temporarily unavailable Cannot lock port","stack":"Error: Error Resource temporarily unavailable Cannot lock port"}
  zigbee2mqtt:error 2019-8-27 12:00:23 PM Exiting...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-27T10_00_23_365Z-debug.log

Can you please help ?
Thierry

**Comment by jimmyeao** [comment]
Have a read through [(https://github.com/Koenkk/zigbee2mqtt/issues/517)]
