### ISSUE TITLE
How to get the values of new devices

### ISSUE THREAD

**Issue by jwillmer** [Koenkk/zigbee2mqtt#19]
The [docs](https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices) tell me how to support new devices but I'm not sure what to put into `zigbee2mqtt.js`. How do I know that I need to put in `msg.data.data['measuredValue']` - I guess it is not always `msg.data.data['measuredValue']`.

**Comment by Koenkk** [comment]
Thats true, I always start with a `console.log(msg.data)` to see the structure of the messages.

**Comment by jwillmer** [comment]
Could you update the wiki with this information?

**Comment by Koenkk** [comment]
Updated the wiki, thanks!
