### ISSUE TITLE
Difference between CC2531ZNP-Prod.hex and CC2531ZNP-Pro-Secure_LinkKeyJoin_mod.hex

### ISSUE THREAD

**Issue by Darkblade48** [Koenkk/zigbee2mqtt#190]
From what I can see, the only difference between the two is that the former is for flashing via CC Debugger, while the latter is modified (in some way) to flash via Arduino. Is this the only difference?

Which version is being updated the most frequently?

**Comment by Darkblade48** [comment]
Is there any difference between the official and the Arduino flashable version though? I thought the Arduino flashable version was built off the official firmware.

The hex file flashable via Arduino was the one under "alternative flashing methods" in the documentation, so I had assumed they were identical

**Comment by Koenkk** [comment]
Probably yes, as the compile options have been changed recently (like `MAXMEMHEAP`)

**Comment by kirovilya** [comment]
mod-version of firmware got from normal version by removing the second line from the end.
Link to this method exists in wiki for flashing via Arduino - https://github.com/wavesoft/CCLib/issues/19

**Comment by kirovilya** [comment]
May be add this method to wiki...

**Comment by Darkblade48** [comment]
Aha, that clears some things up. 

@kirovilya I followed the write up here: https://github.com/Koenkk/zigbee2mqtt/wiki/Alternative-firmware-flashing-methods 

I believe you originally proposed this and had an article written in Russian before you translated it. It worked fine, but I just wanted to know if there were any significant differences between the Arduino hex file and the CC Debugger hex file.

How up to date is the Arduino flashable hex file?

**Comment by kirovilya** [comment]
> any significant differences between the Arduino hex file and the CC Debugger hex file
 
nothing.

> How up to date is the Arduino flashable hex file?

You can download the CC Debugger hex-file you need and, how described, remove the second line from the end in it.

**Comment by Darkblade48** [comment]
OK, thanks for all the information everyone! I'll close this issue.

**Comment by lancelon** [comment]
I was also confused by the difference in the filename - and am wondering if I'd made a mistake because the files didn't follow the screenshots
