### ISSUE TITLE
Lonsonho QS-Zigbee-D02-TRIAC-L_1 UNSUPPORTED ATRIBUTE

### ISSUE THREAD

**Issue by AUkkers** [Koenkk/zigbee2mqtt#19009]
### What happened?

light_type and power_on_behavior atributes can't be set in zigbee2mqtt for Lonsonho QS-Zigbee-D02-TRIAC-L_1 (https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-L_1.html#lonsonho-qs-zigbee-d02-triac-l_1). But they mark as supported in docs.
Pressing to change values return error like this: 
Error 2023-09-18 18:26:49Publish 'set' 'power_on_behavior' to 'hallway_dimmer' failed: 'Error: Write 0xa4c13809542a70df/1 genOnOff({"moesStartUpOnOff":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
and 
Error 2023-09-18 19:20:08Publish 'set' 'light_type' to 'hallway_dimmer' failed: 'Error: Write 0xa4c13809542a70df/1 genLevelCtrl({"64514":{"value":2,"type":32}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

### What did you expect to happen?

I expected that I can change them from zigbee2mqtt.

### How to reproduce it (minimal and precise)

Just try change their values from software

### Zigbee2MQTT version

1.33.0 commit: unknown

### Adapter firmware version

20221102

### Adapter

Sonoff donle P

### Debug log

Error 2023-09-18 18:26:49Publish 'set' 'power_on_behavior' to 'hallway_dimmer' failed: 'Error: Write 0xa4c13809542a70df/1 genOnOff({"moesStartUpOnOff":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Error 2023-09-18 19:20:08Publish 'set' 'light_type' to 'hallway_dimmer' failed: 'Error: Write 0xa4c13809542a70df/1 genLevelCtrl({"64514":{"value":2,"type":32}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by dariusz-goc** [comment]
I have the same problem. Also transitions don't work and are marked as supported both in device specific options and when operating the device.
