### ISSUE TITLE
[New device support]: TS0601 DM45EAF/SP curtain tubular motor from Dooya

### ISSUE THREAD

**Issue by jaredAmpo** [Koenkk/zigbee2mqtt#19006]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_cover_1.html

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xa46dd4fffeca8ea8","nwkAddr":57374,"manufId":4098,"manufName":"_TZE200_f91miyhj","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\f\u0000\u0000\u0000\u0000\f","65506":31,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZE200_f91miyhj","zclVersion":3,"appVersion":83,"modelId":"TS0601","powerSource":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":83,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1695022977896,"defaultSendRequestWhen":"immediate"}

### Comments

Hi, I need some help with adding the support for a `TS0601 DM45EAF/SP curtain tubular motor from Dooya`. 
I've tried making two external converters. Both are able to open/stop/close the curtain and the first converter is able to report the % position of the curtain correctly. 

The main issue I am trying to resolve is to adjust the position of my curtain from HA, but dragging the slider simply prints the following in the logs, while the motor stays stationary. My motor's friendly name is `blinds`
```
Received MQTT message on 'zigbee2mqtt/blinds/set' with data '{"position":64}'
Publishing 'set' 'position' to 'blinds'
```

When i remove all datapoints except 1, I receive positional updates from `dp 8` as shown 
```
Datapoint 8 not defined for '_TZE200_f91miyhj' with data {"dp":8,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,75]}}
``` 
I am unable to retrieve any other specific datapoints since I am not using a tuya gateway, should i contact the manufacturer?

I've been stuck on this for quite some time and would greatly appreciate some assistance. Thanks!

### External converter

```shell
// First converter: able to open/close/stop & report % position of curtain
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_f91miyhj',
        },
    ],
    model: 'TS0601_new',
    vendor: 'Dooya',
    description: 'Dooya Tubular Motor',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime, 
    configure: tuya.configureMagicPacket,
    exposes: [e.cover_position().setAccess('position', ea.STATE_SET), 
                     e.enum('motor_direction', ea.STATE_SET, ['normal', 'reversed'])],   
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2)})],
            [2, 'position', tuya.valueConverter.coverPosition],
            [8, 'position', tuya.valueConverter.raw],
            [5, 'motor_direction', tuya.valueConverterBasic.lookup({'normal': tuya.enum(0), 'reversed': tuya.enum(1)})],
            // [7, null, null], // work_state, not usefull, ignore
            // [101, 'opening_mode', tuya.valueConverterBasic.lookup({'tilt': tuya.enum(0), 'lift': tuya.enum(1)})],
            // [102, 'factory_reset', tuya.valueConverter.raw],
            // [103, 'set_upper_limit', tuya.valueConverter.setLimit],
            // [104, 'set_bottom_limit', tuya.valueConverter.setLimit],
            // [105, 'motor_speed', tuya.valueConverter.raw],
        ],
    },
};

module.exports = definition;

// Second converter: able to open/close/stop 
// const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
// const tz = require('zigbee-herdsman-converters/converters/toZigbee');
// const exposes = require('zigbee-herdsman-converters/lib/exposes');
// const reporting = require('zigbee-herdsman-converters/lib/reporting');
// const legacy = require('zigbee-herdsman-converters/lib/legacy');
// const extend = require('zigbee-herdsman-converters/lib/extend');
// const ota = require('zigbee-herdsman-converters/lib/ota');
// const tuya = require('zigbee-herdsman-converters/lib/tuya');
// const utils = require('zigbee-herdsman-converters/lib/utils');
// const globalStore = require('zigbee-herdsman-converters/lib/store');
// const e = exposes.presets;
// const ea = exposes.access;

// const definition = {
//     zigbeeModel: [
//         'owvfni3\u0000', 'owvfni3', 'u1rkty3', 'aabybja', // Curtain motors
//         'mcdj3aq', 'mcdj3aq\u0000', // Tubular motors
//     ],
//     fingerprint: [
//         // Curtain motors:
//         {modelID: 'TS0601', manufacturerName: '_TZE200_f91miyhj'},
//     ],
//     model: 'TS0601_cover_1',
//     vendor: 'TuYa',
//     description: 'Curtain motor/roller blind motor/window pusher/tubular motor',
//     fromZigbee: [legacy.fromZigbee.tuya_cover, fz.ignore_basic_report],
//     toZigbee: [legacy.toZigbee.tuya_cover_control, legacy.toZigbee.tuya_cover_options],
//     exposes: [
//         e.cover_position().setAccess('position', ea.STATE_SET),
//         e.composite('options', 'options', ea.STATE_SET)
//         .withFeature(e.numeric('motor_speed', ea.STATE_SET)
//             .withValueMin(0).withValueMax(255).withDescription('Motor speed'))
//         .withFeature(e.binary('reverse_direction', ea.STATE_SET, true, false)
//             .withDescription('Reverse the motor direction'))],
// };

// module.exports = definition;
```

**Comment by nelsonq90** [comment]
Hey there, did you find a solution to adjust the position percentage? I am stuck at the same step.

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_f91miyhj',
        },
    ],
    model: 'TS0601_f91miyhj',
    vendor: 'Dooya',
    description: 'Dooya Tubular Motor with open/close/stop and position reporting',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
    exposes: [
        e.cover_position()
            .setAccess('position', ea.STATE)  // position is read-only
            .withDescription('Current position of the blind'),
        e.enum('motor_direction', ea.STATE_SET, ['normal', 'reversed'])
            .withDescription('Direction the motor turns for opening'),
    ],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverterBasic.lookup({
                OPEN: tuya.enum(0),
                STOP: tuya.enum(1),
                CLOSE: tuya.enum(2),
            })],
            [8, 'position', tuya.valueConverter.coverPosition],  // report only
            [5, 'motor_direction', tuya.valueConverterBasic.lookup({
                normal: tuya.enum(0),
                reversed: tuya.enum(1),
            })],
        ],
    },
};

module.exports = definition;
`
