### ISSUE TITLE
external converter breaks down z2m

### ISSUE THREAD

**Issue by schluese** [Koenkk/zigbee2mqtt#19010]
### What happened?

external converter breaks down z2m ,z2m works well after removing it ,but I need it to use my device
this converter is not compatible with newest z2m version ,but functions with older version

this is the external converter file:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const tuyaLocal = {
  dataPoints: {
  sh4Mode: 2,
  sh4HeatingSetpoint: 16,
  sh4LocalTemp: 24,
  sh4ChildLock: 30,
  sh4Battery: 34,
  sh4FaultCode: 45,
  sh4ComfortTemp: 101,
  sh4EcoTemp: 102,
  sh4VacationPeriod: 103,
  sh4TempCalibration: 104,
  sh4ScheduleTempOverride: 105,
  sh4RapidHeating: 106,
  sh4WindowStatus: 107,
  sh4Hibernate: 108,
  sh4ScheduleMon: 109,
  sh4ScheduleTue: 110,
  sh4ScheduleWed: 111,
  sh4ScheduleThu: 112,
  sh4ScheduleFri: 113,
  sh4ScheduleSat: 114,
  sh4ScheduleSun: 115,
  sh4OpenWindowTemp: 116,
  sh4OpenWindowTime: 117,
  sh4RapidHeatCntdownTimer: 118,
  sh4TempControl: 119,
  sh4RequestUpdate: 120,
  },
};
const fzLocal = {
  sh4_thermostat: {
    cluster: 'manuSpecificTuya',
    type: ['commandDataResponse', 'commandDataReport'],
    convert: (model, msg, publish, options, meta) => {
      //const dp = msg.data.dp;
      //const value = tuya.getDataValue(msg.data.datatype, msg.data.data);
      const dpValue = tuya.firstDpValue(msg, meta, 'sh4_thermostat');
      const dp = dpValue.dp;
      const value = tuya.getDataValue(dpValue);
      function weeklySchedule(day, value) {
        // byte 0 - Day of Week (0~7 = Mon ~ Sun) <- redundant?
        // byte 1 - 1st period Temperature (1~59 = 0.5~29.5°C (0.5 step))
        // byte 2 - 1st period end time (1~96 = 0:15 ~ 24:00 (15 min increment, i.e. 2 = 0:30, 3 = 0:45, ...))
        // byte 3 - 2nd period Temperature
        // byte 4 - 2nd period end time
        // ...
        // byte 16 - 8th period end time
        // byte 17 - 9th period Temperature
        const weekDays=['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
        // we get supplied in value only a weekday schedule, so we must add it to
        // the weekly schedule from meta.state, if it exists
        const weeklySchedule= meta.state.hasOwnProperty('weekly_schedule') ? meta.state.weekly_schedule : {};
        meta.logger.info(JSON.stringify({'received day': day, 'received values': value}));
        let daySchedule = []; // result array
        for (let i=1; i<18 && value[i]; ++i) {
          const aTemp=value[i];
          ++i;
          const time=value[i];
          daySchedule=[...daySchedule, {
            temperature: Math.floor(aTemp/2),
            hour: Math.floor(time/4),
            minute: time % 4 *15,
          }];
        }
        meta.logger.info(JSON.stringify({'returned weekly schedule: ': daySchedule}));
        return {'weekly-schedule': {...weeklySchedule, [weekDays[day]]: daySchedule}};
      }
      switch (dp) {
      case tuyaLocal.dataPoints.sh4Mode: // 2
        // 0-Schedule; 1-Manual; 2-Away
        if (value == 0) {
          return {
          system_mode: 'auto',
          away_mode: 'OFF',
          current_heating_setpoint: meta.state.schedule_heating_setpoint_override
          };
        } else if (value == 1) {
          return {
          system_mode: 'heat',
          away_mode: 'OFF',
          current_heating_setpoint: meta.state.manual_heating_setpoint
          };
        } else if (value == 2) {
          return {
          system_mode: 'off',
          away_mode: 'ON',
          current_heating_setpoint: -1 // need implement read away_preset_temperature
          };
        };
        break;
      case tuyaLocal.dataPoints.sh4HeatingSetpoint: // 16
        // 0 - Valve full OFF, 60 - Valve full ON : only in "manual" mode
        return {
          manual_heating_setpoint: (value / 2).toFixed(1),
          current_heating_setpoint: (value / 2).toFixed(1)
        };
      case tuyaLocal.dataPoints.sh4LocalTemp: // 24
        return {local_temperature: (value / 10).toFixed(1)};
      case tuyaLocal.dataPoints.sh4ChildLock: // 30
        return {child_lock: value ? 'LOCKED' : 'UNLOCKED'};
      case tuyaLocal.dataPoints.sh4Battery: // 34
        return {
          battery: value > 130 ? 100 : value < 70 ? 0 : ((value - 70)*1.7).toFixed(1),
          battery_low: value < 90,
        };
      case tuyaLocal.dataPoints.sh4FaultCode: // 45
        break;        
      case tuyaLocal.dataPoints.sh4ComfortTemp: // 101
        return {comfort_temp_preset: (value / 2).toFixed(1)};
      case tuyaLocal.dataPoints.sh4EcoTemp: // 102
        return {eco_temp_preset: (value / 2).toFixed(1)};
      case tuyaLocal.dataPoints.sh4VacationPeriod: // 103
        return {
          away_data: {
            year: value[0]+2000,
            month: value[1],
            day: value[2],
            hour: value[3],
            minute: value[4],
            temperature: (value[5] /2).toFixed(1),
            away_hours: value[6]<< 8 | value[7],
          },
        };
        // byte 0 - Start Year (0x00 = 2000)
        // byte 1 - Start Month
        // byte 2 - Start Day
        // byte 3 - Start Hour
        // byte 4 - Start Minute
        // byte 5 - Temperature (1~59 = 0.5~29.5°C (0.5 step))
        // byte 6-7 - Duration in Hours (0~2400 (100 days))
      case tuyaLocal.dataPoints.sh4TempCalibration: // 104
        return {local_temperature_calibration: value > 55 ?
          ((value - 0x100000000)/10).toFixed(1): (value/ 10).toFixed(1)};
      case tuyaLocal.dataPoints.sh4ScheduleTempOverride: // 105
        if (meta.state.system_mode == 'auto') {
          return {
          schedule_heating_setpoint_override: (value / 2).toFixed(1),
          current_heating_setpoint: (value / 2).toFixed(1)
          }
        } else {
          return {schedule_heating_setpoint_override: (value / 2).toFixed(1)}
        }
      case tuyaLocal.dataPoints.sh4RapidHeating: // 106
        break;
      case tuyaLocal.dataPoints.sh4WindowStatus: // 107
        break;
      case tuyaLocal.dataPoints.sh4Hibernate: // 108
        break;      
      case tuyaLocal.dataPoints.sh4ScheduleMon: // 109
        return weeklySchedule(0, value);
      case tuyaLocal.dataPoints.sh4ScheduleTue: // 110
        return weeklySchedule(1, value);
      case tuyaLocal.dataPoints.sh4ScheduleWed: // 111
        return weeklySchedule(2, value);
      case tuyaLocal.dataPoints.sh4ScheduleThu: // 112
        return weeklySchedule(3, value);
      case tuyaLocal.dataPoints.sh4ScheduleFri: // 113
        return weeklySchedule(4, value);
      case tuyaLocal.dataPoints.sh4ScheduleSat: // 114
        return weeklySchedule(5, value);
      case tuyaLocal.dataPoints.sh4ScheduleSun: // 115
        return weeklySchedule(6, value);
      case tuyaLocal.dataPoints.sh4OpenWindowTemp: // 116
        break;
      case tuyaLocal.dataPoints.sh4OpenWindowTime: // 117
        break;
      case tuyaLocal.dataPoints.sh4RapidHeatCntdownTimer: // 118
        break;
      case tuyaLocal.dataPoints.sh4TempControl: // 119
        break;
      case tuyaLocal.dataPoints.sh4RequestUpdate: // 120
        break;
      default:
        meta.logger.warn(`zigbee-herdsman-converters:sh4Thermostat: NOT RECOGNIZED DP #${
          dp} with data ${JSON.stringify(msg.data)}`);
      }
    },
  },
};

const tzLocal = {
  sh4_thermostat_current_heating_setpoint: {
    key: ['current_heating_setpoint'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      if (meta.state.system_mode == 'heat') {
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4HeatingSetpoint, temp);
      } else if (meta.state.system_mode == 'auto') {
        await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ScheduleTempOverride, temp);
      }
    },
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_comfort_temp_preset: {
    key: ['comfort_temp_preset'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ComfortTemp, temp);
    },
  },
  sh4_thermostat_eco_temp_preset: {
    key: ['eco_temp_preset'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4EcoTemp, temp);
    },
  },
  sh4_thermostat_schedule_override_setpoint: {
    key: ['schedule_override_setpoint'],
    convertSet: async (entity, key, value, meta) => {
      const temp = Math.round(value * 2);
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4ScheduleTempOverride, temp);
    },
  },
  sh4_thermostat_get_data: {
    key: ['local_temperature'],
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_mode: {
    key: ['system_mode'],
    convertSet: async (entity, key, value, meta) => {
      if ( value == 'auto' ) {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 0);
      } else if ( value == 'heat' ) {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 1);
      } else if ( value == 'off') {
        await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 2);
        //await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4HeatingSetpoint, 0);
      }
    },
    convertGet: async (entity, key, value, meta) => {
      await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4RequestUpdate, 0);
    },
  },
  sh4_thermostat_away: {
    key: ['away_mode', 'away_data'],
    convertSet: async (entity, key, value, meta) => {
      if (key==='away_mode') {
        if ( value == 'ON' ) {
          await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 2);
        } else {
          await tuya.sendDataPointEnum(entity, tuyaLocal.dataPoints.sh4Mode, 0);
        }
      } else if (key==='away_data') {
        const output= new Buffer(8);
        // byte 0 - Start Year (0x00 = 2000)
        // byte 1 - Start Month
        // byte 2 - Start Day
        // byte 3 - Start Hour
        // byte 4 - Start Minute
        // byte 5 - Temperature (1~59 = 0.5~29.5°C (0.5 step))
        // byte 6-7 - Duration in Hours (0~2400 (100 days))
        output[0]=value.year > 2000 ? value.year-2000 : value.year; // year
        output[1]=value.month; // month
        output[2]=value.day; // day
        output[3]=value.hour; // hour
        output[4]=value.minute; // min
        output[5]=Math.round(value.temperature * 2);
        output[7]=value.away_hours & 0xFF;
        output[6]=value.away_hours >> 8;
        meta.logger.info(JSON.stringify({'send to tuya': output, 'value was': value, 'key was': key}));
        await tuya.sendDataPointRaw(entity, tuyaLocal.dataPoints.sh4VacationPeriod, output);
      }
    },
  },
  sh4_thermostat_schedule: {
    key: ['weekly_schedule'],
    convertSet: async (entity, key, value, meta) => {
      const weekDays=['mon' , 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
      // byte 0 - Day of Week (0~7 = Mon ~ Sun) <- redundant?
      // byte 1 - 1st period Temperature (1~59 = 0.5~29.5°C (0.5 step))
      // byte 2 - 1st period end time (1~96 = 0:15 ~ 24:00 (15 min increment, i.e. 2 = 0:30, 3 = 0:45, ...))
      // byte 3 - 2nd period Temperature
      // byte 4 - 2nd period end time
      // ...
      // byte 16 - 8th period end time
      // byte 17 - 9th period Temperature
      // we overwirte only the received days. The other ones keep stored on the device
      const keys = Object.keys(value);
      for (const dayName of keys) { // for loop in order to delete the empty day schedules
        const output= new Buffer(17); // empty output byte buffer
        const dayNo=weekDays.indexOf(dayName);
        output[0]=dayNo+1;
        const schedule=value[dayName];
        schedule.forEach((el, Index) => {
          if (Index <=8) {
            output[1+2*Index]=Math.round(el.temperature*2);
            output[2+2*Index]=el.hour*4+Math.floor((el.minute/15));
          } else {
            meta.logger.warn('more than 8 schedule points supplied for week-day '+dayName +
            ' additional schedule points will be ignored');
          }
        });
        await tuya.sendDataPointRaw(entity, tuyaLocal.dataPoints.sh4ScheduleMon+dayNo, output);
        await new Promise((r) => setTimeout(r, 2000));
        // wait 2 seconds between schedule sends in order not to overload the device
      }
    },
  },
  sh4_thermostat_child_lock: {
    key: ['child_lock'],
    convertSet: async (entity, key, value, meta) => {
      await tuya.sendDataPointBool(entity, tuyaLocal.dataPoints.sh4ChildLock,
        ['LOCKED', 'ON', 'LOCK'].includes(value.toUpperCase()));
    },
  },
  sh4_thermostat_calibration: {
    key: ['local_temperature_calibration'],
    convertSet: async (entity, key, value, meta) => {
      if (value > 0) value = value*10;
      if (value < 0) value = value*10 + 0x100000000;
      await tuya.sendDataPointValue(entity, tuyaLocal.dataPoints.sh4TempCalibration, value);
    },
  },
};

const device = {
  fingerprint: [
    {
      modelID: 'TS0601',
      manufacturerName: '_TZE200_i48qyn9s'
    },
  ],
  model: 'SH4 Zigbee eTRV',
  vendor: 'Tuya',
  description: 'Zigbee Radiator Thermostat',
  fromZigbee: [
    fz.ignore_basic_report,
    fzLocal.sh4_thermostat,
  ],
  toZigbee: [
    tzLocal.sh4_thermostat_current_heating_setpoint,
    tzLocal.sh4_thermostat_comfort_temp_preset,
    tzLocal.sh4_thermostat_eco_temp_preset,
    tzLocal.sh4_thermostat_away,
    tzLocal.sh4_thermostat_mode,
    tzLocal.sh4_thermostat_child_lock,
    tzLocal.sh4_thermostat_calibration,
    tzLocal.sh4_thermostat_schedule_override_setpoint,
    tzLocal.sh4_thermostat_schedule,
    tzLocal.sh4_thermostat_get_data,
    tz.tuya_data_point_test,
  ],
  onEvent: tuya.onEventSetLocalTime,
  exposes: [
    e.battery(), e.battery_low(), e.child_lock(),
    exposes.climate().withSetpoint('current_heating_setpoint', 0.5, 29.5, 0.5)
                     .withLocalTemperature()
                     .withSystemMode(['auto','heat','off'])
  ],
};

module.exports = device;

### Zigbee2MQTT version

 1.33.0

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0

**Comment by schluese** [comment]
Information database.db:

{"id":32,"type":"EndDevice","ieeeAddr":"0x84ba20fffe2dd7c5","nwkAddr":24409,"manufId":4098,"manufName":"_TZE200_i48qyn9s","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,10,4,5,61184],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"�l,\u0011","65506":27,"modelId":"TS0601","manufacturerName":"_TZE200_i48qyn9s","powerSource":3,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1695359977827,"defaultSendRequestWhen":"immediate"}

What did you expect to happen?

help with modifying the external converter file or add device support in z2m directly

**Comment by lux73** [comment]
you had to post/push your external Converter after you got it working with Versions before

I'm sure @Koenkk has it implemented soon. And not you haven't no Problem after upgrade

**Comment by schluese** [comment]
yes, I should have done that :-(

**Comment by Koenkk** [comment]
Could you refactor the ext converter to the new format? I think you can use many things from existing TuYa thermostats, examples:

- https://github.com/Koenkk/zigbee-herdsman-converters/blob/a60d4f6e3b709160a045e836200910a1ab8660dc/src/devices/tuya.ts#L2616
- https://github.com/Koenkk/zigbee-herdsman-converters/blob/a60d4f6e3b709160a045e836200910a1ab8660dc/src/devices/tuya.ts#L2664

**Comment by schluese** [comment]
Hallo, Ich habe den Konverter jetzt so weit, dass z2mqtt nicht mehr abstürzt :-) aber obwohl ich die Datenpunkte vom alten Konverter genommen habe, scheint es nicht zu funktionieren :-( Nur die lokale Temperatur ist korrekt.  Hier sind die Informationen aus dem Protokoll, leider verstehe ich sie nicht:

Debug 2023-09-27 12:58:00Received Zigbee message from 'Regina Fenster Links', type 'commandMcuSyncTime', cluster 'manuSpecificTuya', data '{"payloadSize":65180}' from endpoint 1 with groupID 0
Debug 2023-09-27 12:58:01Received MQTT message on 'zigbee2mqtt/Regina Fenster Links/set' with data '{"system_mode":"heat"}'
Debug 2023-09-27 12:58:01Publishing 'set' 'system_mode' to 'Regina Fenster Links'
Info 2023-09-27 12:58:11MQTT publish: topic 'zigbee2mqtt/Regina Fenster Links', payload '{"away_data":{"away_hours":0,"day":1,"hour":0,"minute":0,"month":1,"temperature":"17.0","year":2019},"away_mode":"OFF","battery":"74.8","battery_low":false,"boost_timeset_countdown":null,"child_lock":"UNLOCKED","comfort_temp_preset":"21.0","comfort_temperature":null,"current_heating_setpoint":8.5,"eco_temp_preset":"17.0","eco_temperature":null,"error_status":null,"frost_protection":null,"heating_stop":null,"holiday_start_stop":null,"holiday_temperature":null,"linkquality":65,"local_temperature":"20.0","local_temperature_calibration":"0.0","manual_heating_setpoint":"23.5","online":null,"open_window":"OFF","open_window_temperature":null,"schedule_friday":null,"schedule_heating_setpoint_override":"23.5","schedule_monday":null,"schedule_saturday":null,"schedule_sunday":null,"schedule_thursday":null,"schedule_tuesday":null,"schedule_wednesday":null,"system_mode":"heat","weekly-schedule":{"fri":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"mon":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"sat":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"sun":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"thu":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"tue":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}],"wed":[{"hour":6,"minute":0,"temperature":17},{"hour":9,"minute":0,"temperature":21},{"hour":17,"minute":0,"temperature":17},{"hour":23,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":24,"minute":0,"temperature":17},{"hour":24,"minute":0,"temperature":21},{"hour":null,"minute":null,"temperature":17}]},"working_day":null}'


here is my converter, I tried both of your tips:

const legacy = require('zigbee-herdsman-converters/lib/legacy');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = {...require('zigbee-herdsman-converters/converters/toZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').toZigbee};
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE200_i48qyn9s',
        },
    ],
    model: 'essentials Heizkörperthermostat',
    vendor: 'TuYa',
    description: 'Zigbee Radiator Thermostat',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: tuya.configureMagicPacket,
    exposes: [
        e.battery(), e.battery_low(), e.child_lock(), e.open_window(), e.open_window_temperature().withValueMin(5).withValueMax(30),
            e.comfort_temperature().withValueMin(5).withValueMax(30), e.eco_temperature().withValueMin(5).withValueMax(30),
            e.climate().withPreset(['auto', 'manual', 'holiday']).withLocalTemperatureCalibration(-5, 5, 0.1, ea.STATE_SET)
                .withLocalTemperature(ea.STATE).withSetpoint('current_heating_setpoint', 5, 30, 0.5, ea.STATE_SET)
                .withSystemMode(['off', 'heat'], ea.STATE_SET, 'Only for Homeassistant'),
            e.binary('heating_stop', ea.STATE_SET, 'ON', 'OFF').withDescription('Battery life can be prolonged'+
                    ' by switching the heating off. To achieve this, the valve is closed fully. To activate the '+
                    'heating stop, the device display "HS", press the pair button to cancel.'),
            tuya.exposes.frostProtection('When Anti-Freezing function is activated, the temperature in the house is kept '+
                    'at 8 °C, the device display "AF".press the pair button to cancel.'),
            e.numeric('boost_timeset_countdown', ea.STATE_SET).withUnit('s').withDescription('Setting '+
                    'minimum 0 - maximum 465 seconds boost time. The boost (â¨) function is activated. The remaining '+
                    'time for the function will be counted down in seconds ( 465 to 0 ).').withValueMin(0).withValueMax(465),
            e.holiday_temperature().withValueMin(5).withValueMax(30),
            e.text('holiday_start_stop', ea.STATE_SET).withDescription('The holiday mode will automatically start ' +
                'at the set time starting point and run the holiday temperature. Can be defined in the following format: ' +
                '`startYear/startMonth/startDay startHours:startMinutes | endYear/endMonth/endDay endHours:endMinutes`. ' +
                'For example: `2022/10/01 16:30 | 2022/10/21 18:10`. After the end of holiday mode, it switches to "auto" ' +
                'mode and uses schedule.'),
            e.enum('working_day', ea.STATE_SET, ['mon_sun', 'mon_fri+sat+sun', 'separate']).withDescription('`mon_sun` ' +
                '- schedule for Monday used for each day (define it only for Monday). `mon_fri+sat+sun` - schedule for ' +
                'workdays used from Monday (define it only for Monday), Saturday and Sunday are defined separately. `separate` ' +
                '- schedule for each day is defined separately.'),
            e.composite('schedule', 'schedule', ea.SET).withFeature(e.enum('week_day', ea.SET, ['monday', 'tuesday',
                'wednesday', 'thursday', 'friday', 'saturday', 'sunday'])).withFeature(e.text('schedule', ea.SET))
                .withDescription('Schedule will work with "auto" preset. In this mode, the device executes ' +
                'a preset week programming temperature time and temperature. Before using these properties, check `working_day` ' +
                'property. Each day can contain up to 10 segments. At least 1 segment should be defined. Different count of segments ' +
                'can be defined for each day, e.g., 3 segments for Monday, 5 segments for Thursday, etc. It should be defined in the ' +
                'following format: `hours:minutes/temperature`. Minutes can be only tens, i.e., 00, 10, 20, 30, 40, 50. Segments should ' +
                'be divided by space symbol. Each day should end with the last segment of 24:00. Examples: `04:00/20 08:30/22 10:10/18 ' +
                '18:40/24 22:50/19.5`; `06:00/21.5 17:20/26 24:00/18`. The temperature will be set from the beginning/start of one ' +
                'period and until the next period, e.g., `04:00/20 24:00/22` means that from 00:00 to 04:00 temperature will be 20 ' +
                'degrees and from 04:00 to 00:00 temperature will be 22 degrees.'),
            ...tuya.exposes.scheduleAllDays(ea.STATE, 'HH:MM/C'),
            e.binary('online', ea.STATE_SET, 'ON', 'OFF').withDescription('The current data request from the device.'),
            tuya.exposes.errorStatus(),
        ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
                [2, 'preset', tuya.valueConverterBasic.lookup({'auto': tuya.enum(0), 'manual': tuya.enum(1), 'holiday': tuya.enum(3)})],
                [107, 'open_window', tuya.valueConverter.onOff],
                [10, null, tuya.valueConverter.TV02FrostProtection],
                [10, 'frost_protection', tuya.valueConverter.TV02FrostProtection],
                [16, 'current_heating_setpoint', tuya.valueConverter.divideBy10],
                [24, 'local_temperature', tuya.valueConverter.divideBy10],
                [104, 'local_temperature_calibration', tuya.valueConverter.localTempCalibration1],
                [31, 'working_day', tuya.valueConverterBasic.lookup({'mon_sun': tuya.enum(0), 'mon_fri+sat+sun': tuya.enum(1),
                    'separate': tuya.enum(2)})],
                [103, 'holiday_temperature', tuya.valueConverter.divideBy10],
                [35, 'battery_low', tuya.valueConverter.trueFalse0],
                [30, 'child_lock', tuya.valueConverter.lockUnlock],
                [45, 'error_status', tuya.valueConverter.raw],
                [46, 'holiday_start_stop', tuya.valueConverter.thermostatHolidayStartStop],
                [118, 'boost_timeset_countdown', tuya.valueConverter.raw],
                [116, 'open_window_temperature', tuya.valueConverter.divideBy10],
                [101, 'comfort_temperature', tuya.valueConverter.divideBy10],
                [102, 'eco_temperature', tuya.valueConverter.divideBy10],
                [105, 'schedule', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [107, null, tuya.valueConverter.TV02SystemMode],
                [107, 'system_mode', tuya.valueConverter.TV02SystemMode],
                [107, 'heating_stop', tuya.valueConverter.TV02SystemMode],
                [120, 'online', tuya.valueConverter.onOffNotStrict],
                [109, 'schedule_monday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [110, 'schedule_tuesday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [111, 'schedule_wednesday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [112, 'schedule_thursday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [113, 'schedule_friday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [114, 'schedule_saturday', tuya.valueConverter.thermostatScheduleDaySingleDP],
                [115, 'schedule_sunday', tuya.valueConverter.thermostatScheduleDaySingleDP],
            ],
    },
};

module.exports = definition;
