### ISSUE TITLE
Best standalone router

### ISSUE THREAD

**Issue by james-fry** [Koenkk/zigbee2mqtt#1901]
This is not an issue per-se.
I’m currently using a few cc2531 sticks as routers and tbh I’m not that happy.

Can anyone recommend any standalone routers that have good range.

What about Ikea signal extenders? They are cheap at £7 each (inc usb charger)

**Comment by Koenkk** [comment]
The issue tracker is meant for tracking bugs, for questions please use http://zigbee2mqtt.discourse.group/ or https://discord.gg/dadfWYE.

**Comment by james-fry** [comment]
Fair enough. 
I raised a topic for this discussion on the discourse:

http://zigbee2mqtt.discourse.group/t/best-router-range-for-z2m/287
