### ISSUE TITLE
OTA AQARA H1 switches

### ISSUE THREAD

**Issue by Jens-Wymeersch** [Koenkk/zigbee2mqtt#19029]
### What happened?

Not all switches are visible on the OTA dashboard. Xiaomi WS-EUK04 isn't showing up (although that it says otherwise on the documentation).
Secondly, for the QBKG32LM, the OTA isn't working. Basically, it updates from null till null. 

### What did you expect to happen?

That all switches are visible in the OTA dashboard and can be updated when applicable.

### Zigbee2MQTT version

1.33.0 

### Adapter firmware version

20230507

### Adapter

SLZB-06

**Comment by Jens-Wymeersch** [comment]
@Koenkk Besides the problems listed above related to OTA, I've noticed that this is valid for all aqara related devices. Anyway around this besides using the aqara hub itself?

**Comment by erasmus83** [comment]
I have an WS-EUK01 & WS-EUK02 - also have the same issue that they are not visible in OTA dashboard

**Comment by sozoalvin** [comment]
have the same problem - QBKG32LM 
tried OTA update but fails with this reason code in z2m logs. 

been trying to debug for days - can't seem to find out the reason why 

Update of '0x24df44100068d456' failed (Update failed with reason: 'undefined')

**Comment by ahma** [comment]
Still an issue.

**Comment by sozoalvin** [comment]
> Still an issue.

are you getting the same logs as I am?

**Comment by ahma** [comment]
@sozoalvin , yeah the same error:
`Error 2023-11-18 22:25:28Update of '0x54ef4410005d6de6' failed (Update failed with reason: 'undefined')`
Furthermore, until I tried to update the switch, it worked fine. But since the update, it hasn't been responsive at all. :(

**Comment by Jens-Wymeersch** [comment]
@Koenkk you have created an amazing platform, and I'm extremely grateful for your efforts. OTA (where possible) as you know is extremely important as the devices need updates. For example, I see one of the H1 switches is acting out and this most probably will be sorted with a firmware update. Can you please have a look at what needs to happen as it will benefit everyone who uses your platform

**Comment by Koenkk** [comment]
We don't have an OTA for this device, to get it follow https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html
