### ISSUE TITLE
[New device support]: Philips Hue Phoenix Ceiling

### ISSUE THREAD

**Issue by gregory-freebird** [Koenkk/zigbee2mqtt#19020]
### Link

https://icecat.biz/en_in/p/philips/3115131ph/ceiling-lighting-8718696126523-31151-31-PH-26204092.html

### Database entry

{"id":34,"type":"Router","ieeeAddr":"0x0017880102327853","nwkAddr":37233,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LLM010","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LLM010","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":10,"dateCode":"20181121","swBuildId":"5.127.1.26420"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":10,"dateCode":"20181121","swBuildId":"5.127.1.26420","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1695116435498,"defaultSendRequestWhen":"immediate"}

### Comments

This Lamp has 3 integrated LEDs that are controllable separately. LLM010, LLM011 and LLM012. They support the same features. Its like having 3 separate lights. I used 3 converters which are the same except for Zigbee Model and description. Now i don't know if I should open 3 request or this one is enough for all 3 LEDs.

{"id":34,"type":"Router","ieeeAddr":"0x0017880102327853","nwkAddr":37233,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LLM010","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LLM010","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":10,"dateCode":"20181121","swBuildId":"5.127.1.26420"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":10,"dateCode":"20181121","swBuildId":"5.127.1.26420","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1695116435498,"defaultSendRequestWhen":"immediate"}

{"id":35,"type":"Router","ieeeAddr":"0x0017880102454af6","nwkAddr":4662,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LLM011","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LLM011","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":11,"dateCode":"20181121","swBuildId":"5.127.1.26420"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":11,"dateCode":"20181121","swBuildId":"5.127.1.26420","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1695116467071,"defaultSendRequestWhen":"immediate"}

{"id":33,"type":"Router","ieeeAddr":"0x0017880102453a49","nwkAddr":25612,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LLM012","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LLM012","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":12,"dateCode":"20181121","swBuildId":"5.127.1.26420"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}},"genLevelCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":12,"dateCode":"20181121","swBuildId":"5.127.1.26420","zclVersion":1,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1695116108807,"defaultSendRequestWhen":"immediate"}

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');

const definition = {
    zigbeeModel: ['LLM010'],
    model: 'LLM010',
    vendor: 'Philips',
    description: 'Hue Phoenix Ceiling LLM010', 
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [154, 455]}),
};

module.exports = definition;
```

### Supported color modes

Not supported

### Color temperature range

{"colorTempPhysicalMin:154", "colorTempPhysicalMax:455"}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
