### ISSUE TITLE
GiEX - QT06_2 (_TZE200_a7sghmms) - State not define anymore

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#19026]
### What happened?

For some reason the State for this device is not defined anymore

![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/7f609314-56f3-4fff-851f-4df9eb565a36)

### Zigbee2MQTT version

 1.33.0-dev commit: 0a69bb5

### Adapter firmware version

20230716

### Adapter

Zigbee ESP32GW (Zigstar)

**Comment by Koenkk** [comment]
Could it be that you are using any external converter for this device?

**Comment by cloudbr34k84** [comment]
> Could it be that you are using an external converter for this device?

No external converter, I only have 2,  the solar siren and the pool tester you are helping me on

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by cloudbr34k84** [comment]
> Pushed a fix!
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

Oh nice!

What happened??

**Comment by Koenkk** [comment]
Bug in the frontend fixed by https://github.com/nurikk/zigbee2mqtt-frontend/commit/912b1b0d0f2c0a2f252ddbeffdc2bdf909bbb042
