### ISSUE TITLE
 Aqara/Xiaomi EU smart plug - slow and inaccurate power report

### ISSUE THREAD

**Issue by bendau28** [Koenkk/zigbee2mqtt#19039]
### What happened?

Hi, im new with zigbee2mqtt and have a problem.

I paired my new Aqara/Xiaomi EU smart plug with zigbee2mqtt, so far the basics work. I can switch the plug on and off and i get some values reportet and some (for me not intresting values) are null. But i recognise that the power reporting is very laggi and inaccurate. Before the plug i used a Shelly Plug S for power monitoring of the same device and the monitoring shows much more fluctuations and updates what is more plausible because i have a TV connected which consume diffrent power at diffrent brightness and scene. It looks like that the value only updates when there is a huge change of more than 5-10 watt in consume, the shelly shows new value allready when 0.5w changes.

I figured out how to get the value more frequently over the dev-console, but i cant configure a sheduled reporting.

value is:
- Endpoint: 1
- Cluster: haElectricalMeasurement
- attribute: activePower

When i put the log-level at debug and try it over dev-console i get:

2023-09-21 19:14:51Read result of 'haElectricalMeasurement': {"activePower":763}

what means 76.3 Watt. 5 Seconds later i try the same again and get another value, so the plug can deliver more accurate values. when i dont do this, sometime the reported value change for over an hour not, because the consume doesnt change more then +- 10watt.

When i try to configure a report i get a failure:
2023-09-21 19:20:32Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x54ef441000811504/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE')'

can someone helf me to fix it?

Here the default configured reportings:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/123270367/58438446-0484-4849-8cff-f07edb88a615)

the device configuration at the moment can find here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/d944a104e38b15edd1eb0daf694b07d1d0fe631c/src/devices/xiaomi.ts#L2089C9-L2089C9

Here the value is called "power":
![image](https://github.com/Koenkk/zigbee2mqtt/assets/123270367/1f7adcf3-d128-49da-8068-8650bbb33a90)

### What did you expect to happen?

Frequently update (maybe every 30 seconds)

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

7.1.1.0 build 273

### Adapter

EZSP v9

**Comment by Sjekke** [comment]
Did you solved the issue?
