### ISSUE TITLE
Namron 1402769 device power source unknown

### ISSUE THREAD

**Issue by EspenJQ** [Koenkk/zigbee2mqtt#19036]
### What happened?

Hi! This device is powered from main, but report an unknown power source.
![namron zigbee dimmer](https://github.com/Koenkk/zigbee2mqtt/assets/133442827/a8393ca4-84f1-47fe-bd35-49229cb0a81f)

### What did you expect to happen?

It should report being powered by mains.

### How to reproduce it (minimal and precise)

Add the device.

### Zigbee2MQTT version

1.33.0 commit: 7ee207f

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle E

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
