### ISSUE TITLE
Reported illuminance is too low on ZY-M100-S_1 (_TZE204_sxm7l9xa)

### ISSUE THREAD

**Issue by seblu** [Koenkk/zigbee2mqtt#19044]
### What happened?

The `illuminance` reported by the Tuya ZY-M100-S_1 (_TZE204_sxm7l9xa) presence sensor is too low and not reacting to ceiling light switching in the room. Looks like the value is percentage lower than illuminance reported by an Aqara Illuminance sensor and an Aqara Motion sensor.

This is happening on both Tuya wall and ceiling sensors version.

Here is a graph of the measured values on few days:
![Screenshot_20230921_230059](https://github.com/Koenkk/zigbee2mqtt/assets/615816/4f36ea46-0393-42ef-9065-b593624bc417)

### What did you expect to happen?

Have the correct lux reported. Probably a factor is missing in the reading.
Note: When no light, the sensor is not reporting 0lx or 1lx but 4lx.

### How to reproduce it (minimal and precise)

- Setup the sensor
- No light in the room 4lx. Ceiling light on 4lx.

### Zigbee2MQTT version

1.33.0 

### Adapter firmware version

20221226

### Adapter

Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001

**Comment by lux73** [comment]
pls Keep in mind that all cheap Sensors sonetimes acting weird measuring Values

My Aqara Motion Sensor with integrated Lux measured crap  compared with my desired Aqara Lux Sensor ^^

Even my Room is completely Dark the Motion Sensor measure 18lx

So i dont give a shit 🙃

**Comment by seblu** [comment]
Yes, I'm aware these sensors do not measure a real lux value, but more something which is proportional to the quantity of light the device is exposed to.

I have 5 different model of illuminance sensors, none is as bad as 18lx when no light. Sorry to hear that.

What is problematic here:
- the measured values is proportional but not precise enough to be used in the lower range
- the value min value is 4 instead of 0 or 1.
- the max value is 25lx when other sensors measure 175lx.
