### ISSUE TITLE
MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#19056]
### What happened?

MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'

@Koenkk Can you have a look at the the bottom of the log and tell me why it would have disconnected??

### Zigbee2MQTT version

 1.33.0-dev commit: e3d1c63

### Adapter firmware version

20230716

### Adapter

Zigbee ESP32GW (Zigstar)

### Debug log

[log1.txt](https://github.com/Koenkk/zigbee2mqtt/files/12705967/log1.txt)

**Comment by Koenkk** [comment]
It looks like you firmware crashes, firwmare `20230716` is not considered stable, I just published 2 new test firmwares: https://github.com/Koenkk/Z-Stack-firmware/discussions/478 . So please provide your feedback there.
