### ISSUE TITLE
[New device support]: Sonoff  TRVZB

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#19051]
### Link

https://itead.cc/product/sonoff-zigbee-thermostatic-radiator-valve/ref/8/

### Database entry

{"id":70,"type":"EndDevice","ieeeAddr":"0x94deb8fffe2b413c","nwkAddr":34169,"manufId":4742,"manufName":"SONOFF","powerSource":"Battery","modelId":"TRVZB","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,6,32,513,64599,64529],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"TRVZB","manufacturerName":"SONOFF","powerSource":3,"zclVersion":8,"appVersion":0,"dateCode":"20230612","swBuildId":"1.0.8"}},"genPollCtrl":{"attributes":{"checkinInterval":14400}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c2772c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"dateCode":"20230612","swBuildId":"1.0.8","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1695391594568,"defaultSendRequestWhen":"active","checkinInterval":3600}

### Comments

Hello 

I try to use this new device from the Sonoff but appears as not supported 

Can you please help in order to get this device as supported in order to bee possible controlling this on the Z2M Home Assistant ? 

Thank you in advance for your support and best regards

**Comment by Koenkk** [comment]
Device will be supported in the 1 October release.

**Comment by stenleo** [comment]
Hi,
It seems auto discovery for HA on this Sonoff valve is not complete. I only seem to be getting battery and battery_low published as discovery topics to HA.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/25526859/257f4bcf-58ae-43d6-8b8f-698dba2e145c)

**Comment by infinitedestiny** [comment]
Occupied heating setpoint cannot be set in Auto mode, it defaults to 16 or 19 degrees celsius (it depends by some hour range defined somewhere). How can I work in AUTO mode? Auto mode I think that could modulate the opening percentage of the valve (with a PI).
