### ISSUE TITLE
Aqara Smart Radiator Thermostat E1: auto/manual mode mixed up

### ISSUE THREAD

**Issue by Ra72xx** [Koenkk/zigbee2mqtt#19070]
### What happened?

The device mentioned in the subject (firmware 0.0.0_0825, SRTS-A01, https://www.zigbee2mqtt.io/devices/SRTS-A01.html#xiaomi-srts-a01) mixes up the presets "automatic" and "manual" both in Homeassistant and in the Zigbee2MQTT web ui. 
If set to manual, the device is in automatic (internal schedule) mode and vice versa. This is the web ui when the device in fact works according to a schedule (the device display also shows a clock icon to signal this preset):

![Eingefügtes Bild](https://github.com/Koenkk/zigbee2mqtt/assets/3582007/a84e2261-ef06-4250-825f-08951a4e3d7f)

### What did you expect to happen?

Setting the thermostat to "auto": Heat according to internal schedule.
Setting the thermostat to "manual": Use manually fixed temperature.

### How to reproduce it (minimal and precise)

Install the thermostat, pair it with Z2M and use it.

### Zigbee2MQTT version

1.33.0 commit: 7ee207f

### Adapter firmware version

7.1.1.0 build 273

### Adapter

SkyConnect (EZSP v9)

**Comment by Ra72xx** [comment]
I guess I misunderstood the meaning of "auto" for this thermostat -> invalid.

**Comment by groenmarsmannetje** [comment]
I have the same expectation. Setting the mode to auto should enable the internal scheduler. Or there should be a different mode (eg "schedule") that you can select. That is how it works in my other Tuya Zigbee TRV's

**Comment by Ra72xx** [comment]
> @Ra72xx so why did you close this ticket? I think you made a valid point.

I assume that it is not a Z2M problem, but a different logic this device is implementing:

- Switch "schedule": Turns on the (very rudimentary) scheduling the device provides
- Mode "automatic": Does something else - maybe using the (with the Aqara app) integrated presence- and window-open sensors, but that I don't know.

I assume both these settings are not related, as both "schedule" and "automatic mode" have their own, not mutually exclusive, symbols in the thermostat display. This wouldn't make sense if "automatic mode" would mean scheduling the heating.

**Comment by groenmarsmannetje** [comment]
Actually in this comment https://github.com/Koenkk/zigbee-herdsman-converters/pull/5058#issuecomment-1334236460 the developer was asking for users feedback to improve this. So re-open this ticket and let this be the feedback that he was looking for.

**Comment by Ra72xx** [comment]
OK, I'll reopen the ticket. However, I assume that it is rather a documentation issue to avoid misunderstanding this thermostat's operating modes.

**Comment by groenmarsmannetje** [comment]
Just for reference. On my other Tuya TRV's I have the following presets (among others):

Schedule - This activates the internal schedular of the device.
Manual - The manually set temperature permanently overrules the internal schedular of the device.
Complex - The manually set temperature only applies until the next set point in time of the internal schedular is reached. After that the internal schedular is used.
