### ISSUE TITLE
Neo NAS-AB06B2 not supported

### ISSUE THREAD

**Issue by chami8i** [Koenkk/zigbee2mqtt#19077]
### What happened?

Although a converter exists in the neo.ts database for  TS0601 _TZE200_nlrfgpny, my device is not supported. I tested it with Tuya and verify datapoints on tuyaIo platform.

### What did you expect to happen?

Help. I tried to clone herdsman converter as a new device. Error on e.enum not a function.

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

na

### Adapter

 EZSP(EFR32/MGM)

### Debug log

[debugAB06B2.txt](https://github.com/Koenkk/zigbee2mqtt/files/12716290/debugAB06B2.txt)

**Comment by chami8i** [comment]
Solved with Z2M v1.33.0

**Comment by averter** [comment]
Hi,
I have the same problem and am on a newer version (below). Can you please 1) let me know how to produce a debug log to diagnose this, and 2) reopen the issue? THanks.

Zigbee2MQTT version
    [1.40.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.1) commit: [403d3c09](https://github.com/Koenkk/zigbee2mqtt/commit/403d3c09)

Coordinator type
    zStack3x0

Coordinator revision
    20230507

Coordinator IEEE Address
    0x00124b002c3a6118

Frontend version
    0.7.4

zigbee-herdsman-converters version
    20.12.1

zigbee-herdsman version
    0.57.3

**Comment by peroanjo** [comment]
Hi @averter, I think we have a similar issue. I opened #24149. Could you check if the manufacturer id is the one I mentioned in that issue? I bought the solar siren a couple weeks ago.

**Comment by averter** [comment]
Wow. I can't believe it but the battery percentage HAS FINALLY SHOWN UP! My manufaturer is the same as before i.e. `_TZE284_nlrfgpny` which was unreported as working as the sirens from @gregoriusus  and others, which were of different manufacturers.

<img width="1640" height="687" alt="Image" src="https://github.com/user-attachments/assets/200f4177-2523-4fe6-9318-5b81a842cf1b" />

<img width="740" height="105" alt="Image" src="https://github.com/user-attachments/assets/6d056afb-2cf3-49c7-9fa1-f255487ff0fe" />

I can confirm that their strategy is the way to go, i.e., keep the siren out of direct sunlight, and very importantly as well, keep constantly activating the lights to drain the battery as much as possible. I ended up doing this last step manually, but as said, it'd be useful to be able to do this with a script in an automated way. Hope this helps others.
