### ISSUE TITLE
The model 'TS0601_din_1' is wrong for manufacturerName '_TZE204_rhblgy0z'

### ISSUE THREAD

**Issue by Hannes5612** [Koenkk/zigbee2mqtt#19080]
### What happened?

The device I bought was wrongly recognized as TS0601_din_1 but is TS0601_din_3. ([d2c0dd2](https://github.com/Koenkk/zigbee-herdsman-converters/commit/d2c0dd2ba1680a94b670c65179715810e5cf1acd)) Thus I can only see energy, the other values are null.
Also see #17080, with the custom converter the correct values are shown.

### Zigbee2MQTT version

1.33.0-1

### Adapter firmware version

 0x26720700

### Adapter

ConBee2/RaspBee2

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
