### ISSUE TITLE
[Wrong device]: "_TZ3000_qeuvnohg" instead of Tongou

### ISSUE THREAD

**Issue by HittyStorm** [Koenkk/zigbee2mqtt#19086]
### Link

https://aliexpress.ru/item/1005004747066832.html

### Model

TO-Q-SY1-JZT

### Description

DIN relay with power metering

### Vendor

TONGOU

### Picture (link)

https://ae04.alicdn.com/kf/S5f1c52dededd4b339fa1ccc6e86efd0aK.jpg

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0xe0798dfffeb8c039","nwkAddr":34249,"manufId":4098,"manufName":"_TZ3000_qeuvnohg","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,1026,57344,57345],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_qeuvnohg","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"haElectricalMeasurement":{"attributes":{"acCurrentDivisor":1000,"acCurrentMultiplier":1,"rmsVoltage":224,"rmsCurrent":5213,"activePower":1174}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,13603]}},"genOnOff":{"attributes":{"onOff":1,"moesStartUpOnOff":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00060fd6da","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00060fd6da","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b00060fd6da","endpointID":1}],"configuredReportings":[{"cluster":2820,"attrId":1285,"minRepIntval":120,"maxRepIntval":3600,"repChange":120},{"cluster":1794,"attrId":0,"minRepIntval":120,"maxRepIntval":3600,"repChange":120},{"cluster":2820,"attrId":1291,"minRepIntval":120,"maxRepIntval":3600,"repChange":120},{"cluster":2820,"attrId":1288,"minRepIntval":120,"maxRepIntval":3600,"repChange":120}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":680236614},"lastSeen":1695734350985,"defaultSendRequestWhen":"immediate"}

### Notes

Wrong picture in device list

**Comment by Koenkk** [comment]
Fix will be included in the next release!
