### ISSUE TITLE
model TS0601_temperature_humidity_sensor_1 

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#19092]
i have here a same sensor but with other model description

![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/6681528/f28a1d18-5055-4e9d-9d4f-85be83bd770c)

what is correct
https://github.com/Koenkk/zigbee-herdsman-converters/blob/cf0d07aeca1d869e6fab911c1eb0a877d26cd3b0/src/devices/tuya.ts#L602

becouse the sensor can not be found..

**Comment by Koenkk** [comment]
Looks like an old zigbee-herdsman-converters version is used? Model is `TS0601_temperature_humidity_sensor` in your screenshot but should be `TS0601_temperature_humidity_sensor_1`

**Comment by arteck** [comment]
strange TZE200_zl1kmjqx works with TS0601_temperature_humidity_sensor_2

**Comment by rocky753** [comment]
with new herdsman version is the same:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/147175034/4b2a6658-bf0a-49e3-b1f4-a87068324673)

but when i change TZE200_zl1kmjqx from TS0601_temperature_humidity_sensor_1 to TS0601_temperature_humidity_sensor_2 its fine. Only battery state isnt shown.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/147175034/d885e00c-f996-44ae-bbfc-df474f738f84)

**Comment by Smo-RBR** [comment]
Have this issue with TZE200_bjawzodf too. Works as TuYa TS0601_temperature_humidity_sensor_2
