### ISSUE TITLE
Xiaomi RTCGQ11LM detecting motion when cleary no motion

### ISSUE THREAD

**Issue by flok** [Koenkk/zigbee2mqtt#1909]
Is there a sensitivity setting for the Aqara Motion Sensors like it is for the Hue Motion Sensor? Because for me the Motions sensor from Aqara are triggering an occupancy 'true' even at night when there is no one walking around the sensor and people are sleeping
![Capture](https://user-images.githubusercontent.com/37000563/64018597-266aa180-cb2d-11e9-92e2-fe26db1c8826.PNG)

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version: CC2531_SOURCE_ROUTING_20190619

**Comment by hawkefly** [comment]
maybe jack and jerry

**Comment by pcb1962** [comment]
I think you have a faulty sensor, I have 12 Aqara motion sensors around the house and I have never seen a false positive.

**Comment by lolorc** [comment]
I've been wondering about false positives with some DJT11LM (vibration sensors)
Haven't really looked at my logs tho. I guess I should sniff my network for several days to see if the devices really send the info.

**Comment by flok** [comment]
> 
> 
> I've been wondering about false positives with some DJT11LM (vibration sensors)
> Haven't really looked at my logs tho. I guess I should sniff my network for several days to see if the devices really send the info.

For me it was occupancy_timeout set to 0. The Motion sensors send a update every 55 Minutes and since it was set to 0 it send not false but true, these where my false positives.
