### ISSUE TITLE
[New device support]: Smart fob 3450-Geu (Same 3450-L)

### ISSUE THREAD

**Issue by LatchyRed** [Koenkk/zigbee2mqtt#19101]
### Link

https://www.leroymerlin.fr/produits/electricite-domotique/domotique-et-objets-connectes/domotique/solutions-de-commande/commande-connectee-portable-4-fonctions-evology-80123662.html

### Database entry

{"id":138,"type":"EndDevice","ieeeAddr":"0x000d6f001086b99a","nwkAddr":24977,"manufId":4174,"manufName":"CentraLite","powerSource":"Battery","modelId":"3450-Geu","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0,1,3,7,32,2821],"outClusterList":[3,6,25],"clusters":{"genBasic":{"attributes":{"modelId":"3450-Geu","manufacturerName":"CentraLite","powerSource":3,"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"����������������"}},"genPollCtrl":{"attributes":{"checkinInterval":480}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00212effff07bc54","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":6,"inClusterList":[7],"outClusterList":[6],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":6,"inClusterList":[7],"outClusterList":[6],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":6,"inClusterList":[7],"outClusterList":[6],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"����������������","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1695890763572,"defaultSendRequestWhen":"fastpoll","checkinInterval":120}

### Comments

Hello, I would like to add the 3450-Geu Smart fob which is, I think, the same as the 3450-L.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
