### ISSUE TITLE
Documentation of the values for pan_id, ext_pan_id & network_key

### ISSUE THREAD

**Issue by TLBM** [Koenkk/zigbee2mqtt#1912]
Hello!

What values of the standard configuration can be changed, and in what range, to improve security? 
Does this impair interoperability with ZigBee devices from different manufacturers?

Is there a system to the network_key to observe or is the standard key, with the odd following the even numbers from 0 to 15 just an example? (Why is 14 missing and 13 double?)

Thank you!

Kind regards
Thomas

**Comment by Koenkk** [comment]
- To improve security: https://www.zigbee2mqtt.io/how_tos/how_to_secure_network.html
- It shouldn't impair interoperability
- The default is just a random example.
