### ISSUE TITLE
MQTT device name is equal to entity name in your config in mqtt edge

### ISSUE THREAD

**Issue by jocamane** [Koenkk/zigbee2mqtt#19145]
### What happened?

Error in mqtt edge but edge is no longer installed.

I upgrade now my z2m to “1.33.0” and the messages appear:

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:296
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 20:03:49 (1 occurrences)
Last logged: 20:03:49

MQTT device name is equal to entity name in your config {‘availability’: [{‘topic’: ‘zigbee2mqtt_EDGE/bridge/state’, ‘payload_not_available’: ‘offline’, ‘payload_available’: ‘online’}], ‘brightness’: True, ‘brightness_scale’: 254, ‘color_mode’: True, ‘command_topic’: ‘zigbee2mqtt_EDGE/Lampadas Movel/set’, ‘device’: {‘identifiers’: [‘zigbee2mqtt_12210510398101101501091131161169569687169_2’], ‘name’: ‘Lampadas Movel’, ‘sw_version’: ‘Zigbee2MQTT 1.32.1-dev’, ‘connections’: []}, ‘json_attributes_topic’: ‘zigbee2mqtt_EDGE/Lampadas Movel’, ‘max_mireds’: 500, ‘min_mireds’: 153, ‘name’: ‘Lampadas Movel’, ‘schema’: ‘json’, ‘state_topic’: ‘zigbee2mqtt_EDGE/Lampadas Movel’, ‘supported_color_modes’: {‘color_temp’, ‘xy’}, ‘unique_id’: ‘2_light_zigbee2mqtt_EDGE’, ‘optimistic’: False, ‘white_scale’: 255, ‘hs’: False, ‘encoding’: ‘utf-8’, ‘flash_time_long’: 10, ‘payload_not_available’: ‘offline’, ‘availability_mode’: ‘latest’, ‘enabled_by_default’: True, ‘xy’: False, ‘rgb’: False, ‘color_temp’: False, ‘payload_available’: ‘online’, ‘retain’: False, ‘qos’: 0, ‘flash_time_short’: 2, ‘effect’: False}, this is not expected. Please correct your configuration. The entity name will be set to null

### What did you expect to happen?

that there was no error

### How to reproduce it (minimal and precise)

when the HA starts it gives an error

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by quadcom** [comment]
So running 1.34.0-1 I am seeing this error in the HA logs as well. In my instance, there are over 120+ log entries. I understood this was resolved back in September with, I think v1.32.
