### ISSUE TITLE
_TZE200_5toc8efa problem with current_heating_setpoint and local_temperature (new)

### ISSUE THREAD

**Issue by drbartek** [Koenkk/zigbee2mqtt#19148]
### What happened?

The problem has already been described several times but unfortunately not solved:
[Koenkk/zigbee2mqtt/issues/18791](https://github.com/Koenkk/zigbee2mqtt/issues/18791)
[Koenkk/zigbee-herdsman-converters#5372](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5372)

### What did you expect to happen?

Restore previous settings from before modification :
[koenkk/zigbee-herdsman-converters/pull/5372](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5372)
as you suggested -> removal of the 'x10' multiplier

### Zigbee2MQTT version

 1.33.0-dev commit: 90763fd

### Adapter firmware version

20230507

### Adapter

CC2652P

**Comment by Koenkk** [comment]
Let's keep it in https://github.com/Koenkk/zigbee2mqtt/issues/18791
