### ISSUE TITLE
[New device support]: Zigbee Computer Power - model 'TS0601' and manufacturer name '_TZE204_6fk3gewc' 

### ISSUE THREAD

**Issue by LuizizM** [Koenkk/zigbee2mqtt#19147]
### Link

https://vi.aliexpress.com/item/1005002776442806.html?spm=a2g0o.order_list.order_list_main.11.6daccaa4F9lIDH&gatewayAdapt=glo2vnm

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0xa4c1382e33144c13","nwkAddr":22241,"manufId":4417,"manufName":"_TZE204_6fk3gewc","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u000e\u0000\u0000\u0000e\u000f\u0000\u0000\u0000\u0012#` ,\u0017$` ,\u0013h\u0007\u0000\u0000ei\u0007\u0000\u0000\u0012 ,f ,\u0012","65506":56,"65508":0,"stackVersion":0,"dateCode":"","appVersion":74}}},"binds":[{"cluster":61184,"type":"endpoint","deviceIeeeAddress":"0x040d84fffe512f0c","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x040d84fffe512f0c","endpointID":1},{"cluster":7,"type":"endpoint","deviceIeeeAddress":"0x040d84fffe512f0c","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"intervewCompleted":true,"meta":{},"lastSeen":1696294086650,"defaultSendRequestWhen":"immediate"}

### Comments

i tried to add this Zigbee adapter but im new and dont know how to get the data from the device and need help with it , is a power switch that allows you to turn on you PC remotely using zigbee, has child lock that dont allow it to be turned on/off from the computer switch only allowing to be turned remotely, also has a feature to bind a 433mhz remote to turn on and off the computer by pressing the remote as well.

**Comment by Fenixekb** [comment]
Yes, I really need this converter too

**Comment by LuizizM** [comment]
up

**Comment by phoenixckua** [comment]
I need too

**Comment by Evililim** [comment]
I have one too :)

In TUYA IoT Platform I have extracted this information :
> {"1":"Switch","101":"ModeReset","102":"RF remote control","103":"RF study","104":"buzzer","105":"Relay Status","106":"Child Lock","209":"Cycle Timing","210":"Random Timing"}

- Switch : to switch the computer on or off
- RF remote control : to enable or disable RF remote control use
- RF study : to pair a RF 433 remote, such as the one supplied with
- buzzer : to activate or deactivate buzzer sounds on relay switching
- Child Lock : to disable or enable the physical power buton of the computer

What other info can i provide to help ?

**Comment by alex-shl** [comment]
i need too

**Comment by Bildas** [comment]
Please, i need it too

**Comment by Bildas** [comment]
Hi, please those who understand it, if you could take a look at it and write at least a converter for zigbee2mqtt, it would certainly make us all very happy :-) And thanks in advance

**Comment by Fenixekb** [comment]
> "Hey guys, I finally did it myself. Main functions such as turning on the PC, child lock, on/off beeper are implemented. Finish the rest, it seems useless to me :-) PS: you know everything is for the zigbee2mqtt converter" [6FK3GEWC.txt](https://github.com/Koenkk/zigbee2mqtt/files/13637200/6FK3GEWC.txt)

Thank you very much!

**Comment by BenJamesAndo** [comment]
Thank you @Bildas for the code.
I've expanded upon it to allow for pairing and using the RF remote that ships with the device. Needs a bit more testing but I was able to pair the remote.
[6FK3GEWC.txt](https://github.com/Koenkk/zigbee2mqtt/files/13882424/6FK3GEWC.txt)
For those unaware, rename it to `6FK3GEWC.js` and then upload it to be in the same folder as the `configuration.yaml` file for zigbee2mqtt. Then restart zigbee2mqtt and it should work.

If I get time I'll see if I can create a pull request so we can get official support for this.

**Comment by BenJamesAndo** [comment]
Hey everyone, the PR I made is coming together. Hoping to finalise it soon. But I need a bit of testing done. I'm not sure what Mode Reset or Relay Status does. Also setting RF remote control to off doesn't disable the RF remote from still working. Below is an updated external converter that you can use to test. Perhaps I wired up my device wrong but if in fact these functions don't do anything then I'll remove them. I didn't add in Cycle Timing or Random Timing as that would probably involve putting in a number value and I'm not sure how to do that. Similar outcomes could likely be achieved with an automation anyway.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const tzDatapoints = {
    ...tuya.tz.datapoints,
        key: ['switch', 'mode_reset', 'buzzer', 'child_lock', 'rf_remote_control', 'rf_study', 'relay_status']
}

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE204_6fk3gewc',
        },
    ],
	model: 'PCI E',
    vendor: 'WETEN',
    description: 'PC SWITCH',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tzDatapoints],
    exposes: [
        e.binary('switch', ea.STATE_SET, 'ON', 'OFF').withDescription('PC Power'),		
        e.binary('mode_reset', ea.STATE_SET, 'ON', 'OFF').withDescription('Perhaps changes between Shutdown or Restart, does not seem to actually do anything'),
        e.binary('relay_status', ea.STATE_SET, 'ON', 'OFF').withDescription('Not sure what this does'),
        e.binary('buzzer', ea.STATE_SET, 'ON', 'OFF').withDescription('Buzzer on means no buzzer noise'),
	e.binary('child_lock', ea.STATE_SET, 'LOCK', 'UNLOCK').withDescription('Child safety lock'),
	e.binary('rf_remote_control', ea.STATE_SET, 'ON', 'OFF').withDescription('To enable or disable the use of RF remote control, does not seem to actually work'),
	e.binary('rf_study', ea.STATE_SET, 'ON', 'OFF').withDescription('To pair a RF 433 remote, such as the one supplied')
        ],
    meta: {
        tuyaDatapoints: [
            [1, 'switch', tuya.valueConverter.onOff],
            [101, 'mode_reset', tuya.valueConverter.onOff],
            [105, 'relay_status', tuya.valueConverter.onOff],
            [104, 'buzzer', tuya.valueConverter.onOff],
            [106, 'child_lock', tuya.valueConverter.lockUnlock],
            [102, 'rf_remote_control', tuya.valueConverter.onOff],
            [103, 'rf_study', tuya.valueConverter.onOff],
        ],
    },
};

module.exports = definition;
```

**Comment by kshexe** [comment]
How do I get into zigbee connection mode?

**Comment by BenJamesAndo** [comment]
> How do I get into zigbee connection mode?

Long press the reset button for 5s until the LED indicator flashes three times, which means the device has entered pairing mode. If buzzer feedback is on then you'll also hear 3 short beeps.
The reset button can be found on the PCIe card.

I'll add the pairing instructions to the device page.

This device has now been officially added so there's no need to use the external converter file and this issue can be closed.

**Comment by kshexe** [comment]
This is my device, but it doesn't stick to z2m after pairing mode.

Tuya PRO Long Zigbee. The seller said they don't support z2m.

**Comment by ZenoBell** [comment]
There are only two  devices that are Zigbee compatibles and there are the same. The difference is one with a long plate for normal pc cases and the other with a short plate for mini atx builds. Seller i guess has outdated info and doesnt still know that i works with z2mqtt.  I still although dont see it on the supported devices page.

**Comment by BenJamesAndo** [comment]
> This is my device, but it doesn't stick to z2m after pairing mode.

What do you mean it doesn't stick to z2m? Who is the seller? I did inform one of the sellers on Aliexpress that this device was now supported.

> I still although dont see it on the supported devices page.

This is the supported devices page: https://www.zigbee2mqtt.io/devices/PCI_E.html

**Comment by kshexe** [comment]
Tuya PRO Long Zigbee model pairing is not possible. Is there a way to check?
