### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by RusselIce** [Koenkk/zigbee2mqtt#19178]
### Link

https://aliexpress.ru/item/1005002776442806.html?spm=a2g2w.orderdetail.0.0.6ed64aa6Aq7B61&sku_id=12000034189168907&_ga=2.53168235.2123802470.1696432918-1411164799.1661953562

### Database entry

{"id":18,"type":"Router","ieeeAddr":"0xa4c138d74b6d163d","nwkAddr":15199,"manufId":4417,"manufName":"_TZE204_6fk3gewc","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�\u001d�,f�\u001d�,\u0012","65506":56,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE204_6fk3gewc","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1696509678244,"defaultSendRequestWhen":"immediate"}

### Comments

![Безымянный](https://github.com/Koenkk/zigbee2mqtt/assets/26179061/655a1e9c-4d16-46b9-b639-970964297c6b)

**Comment by phoenixckua** [comment]
I need this device integrate too

**Comment by Fenixekb** [comment]
Yes, support for this device is very necessary!

**Comment by BenJamesAndo** [comment]
For now you can use custom code from https://github.com/Koenkk/zigbee2mqtt/issues/19147
I might see if I can create a pull request to get this officially added.
