### ISSUE TITLE
[New device support]: CK-BL702-AL-01(7009_Z102LG04-2)

### ISSUE THREAD

**Issue by finn0000** [Koenkk/zigbee2mqtt#19182]
### Link

https://aliexpress.ru/item/1005005077799670.html?spm=a2g2w.orderdetail.0.0.50134aa65eas92&sku_id=12000031553518854

### Database entry

{"id":5,"type":"Router","ieeeAddr":"0x7cb94c77e2cf0000","nwkAddr":19182,"manufId":4742,"manufName":"eWeLink","powerSource":"Unknown","modelId":"CK-BL702-AL-01(7009_Z102LG04-2)","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,61184,64529,64599],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":0,"hwVersion":0,"dateCode":"20230105","swBuildId":"1.2.3","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1696514753067,"defaultSendRequestWhen":"immediate"}

### Comments

Please add or help converter create an external one for the device CK-BL702-AL-01(7009_Z102LG04-2) RGB Lights

### Supported color modes

rgb+cw+ww

### Color temperature range
{"colorTempPhysicalMin":142,"colorTempPhysicalMax":500}
_No response_

additionally, I have a tuya gateway

**Comment by kronna** [comment]
same

**Comment by volodink** [comment]
Same

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
