### ISSUE TITLE
Difference in TS0601 Single and Double Clamp Settings (specific) Tab. 

### ISSUE THREAD

**Issue by MaxLinSG** [Koenkk/zigbee2mqtt#19188]
### What happened?

Difference in Single and Double Clamp Settings (specific) Tab. 

**Single Clamp:** 
Manufacturer: Tuya
Model: [PJ-MGW1203](https://www.zigbee2mqtt.io/devices/PJ-MGW1203.html#tuya-pj-mgw1203)
Zigbee Model TS0601 
Zigbee Manufacturer _TZE204_cjbofhxw
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/c14d1800-92d8-45b3-b4b8-4ddea19336c0)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/585cda35-0811-4d7c-912e-3afc8d2bba1e)

**Double Clamp:**
Manufacturer: Tuya
Model: [PJ-1203A](https://www.zigbee2mqtt.io/devices/PJ-1203A.html#tuya-pj-1203a)
Zigbee Model TS0601 
Zigbee Manufacturer _TZE204_81yrt3lo
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/130e8386-7850-421a-9fb8-2efaff04f877)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/db3e60c5-2fc4-4ab2-8f1e-0bdfd096d4b9)

**Issue**
Unable to adjust Power Precision or Calibration for the double clamp devices https://www.zigbee2mqtt.io/devices/PJ-1203A.html#tuya-pj-1203a
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/756fff3a-c1cc-4e5e-baf4-5a661285a3d1)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/30bd6ee8-3971-46f0-8da2-fdfb638f4f7d)

### What did you expect to happen?

Double clamp should have the Settings to adjust the Power Precision and Calibration of 2 clamps. 

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20220219

### Adapter

Sonoff Usb3.0 Zigbee

**Comment by Emilef22** [comment]
Hi! Have you found a solution to adjust the other specific parameter?

**Comment by PetersPlace** [comment]
Same here only voltage setting.

Other question,  for very small currents i would like to change te CT ratio setting 1:80 change to 1:20   ( 4 windings through the CT clamp)
