### ISSUE TITLE
Add delay to execute

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#192]
We should add configurable delay inside the execute function of the zigbee converter to give end device time for finish.

Could be fix some Bugs where reporting doesnt work.

**Comment by Koenkk** [comment]
Correct me if I'm wrong, but this is already possible via:

```js
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => setTimeout(() => cb(false), 3000),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];
```

**Comment by tb-killa** [comment]
Yes, but if we Integrate it into function it would be easier and work for every cb.
But maybe you have another simple idea :)?

**Comment by Koenkk** [comment]
The default delay is now 300ms. Can this be closed?

**Comment by tb-killa** [comment]
Looks great, work great.
I remove the manually ```(cb) => setTimeout(() => cb(false), 3000),``` and let the new function work.
