### ISSUE TITLE
[Wrong device]: Lidl 399639_2110 recognized as TuYa TS0505B_1

### ISSUE THREAD

**Issue by soundray** [Koenkk/zigbee2mqtt#19204]
### Link

https://www.lidl.de/p/livarno-home-led-deckenleuchte-zigbee-smart-home-16-millionen-farben-38-w/p100357329

### Model

399639_2110

### Description

LED Ceiling Light

### Vendor

Lidl

### Picture (link)

https://www.lidl.de/assets/gcpf4ea260c17ee4c06bb3a21f309ec7110.jpeg

### Database entry

{"id":11,"type":"Router","ieeeAddr":"0xe0798dfffea8827d","nwkAddr":12867,"manufId":4098,"manufName":"_TZ3210_x13bu7za","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_x13bu7za","powerSource":1,"zclVersion":3,"appVersion":107,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":29}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":107,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1842547789},"lastSeen":1696691374757,"defaultSendRequestWhen":"immediate"}

### Notes

Analogous to https://github.com/Koenkk/zigbee2mqtt/issues/18516

**Comment by Koenkk** [comment]
Should already be fixed in z2m 1.33.1
