### ISSUE TITLE
Aqara vibration sensor (DJT11LM) missing battery values?

### ISSUE THREAD

**Issue by Swiftnesses** [Koenkk/zigbee2mqtt#1921]
As per the issue title, I'm unable to get battery readings (angles and actions work fine).

I've tried removing and repairing without luck, can anyone help?

Thank you.

**Comment by Ton1965** [comment]
Hi @Swiftnesses ,
All Xiaomi devices send their battery status once every several hours, not with each data message. I suggest you wait for at least a day and see if you get the battery values.

**Comment by Swiftnesses** [comment]
@Ton1965 Thank you for the clarification, that really helps. I'll close the issue.
