### ISSUE TITLE
TuYa ZTH05 Temp&Humidity

### ISSUE THREAD

**Issue by hometheater13** [Koenkk/zigbee2mqtt#19216]
### Link

https://www.zigbee2mqtt.io/devices/ZTH05.html

### Database entry

Device '0xa4c138ab4677caf4' with Zigbee model 'TS0601' and manufacturer name '_TZE200_upagmta9' is NOT supported

### Comments

Hi 

using version  version: 1.33.1-1

Need small update checked and device is supported but missing manufacture name  : _TZE200_upagmta9

please add support 

thx

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
