### ISSUE TITLE
BREAKER LKNDIZ RDCBC (ID YKLD-ZCH V1.0) tuya app trouble

### ISSUE THREAD

**Issue by nex2000** [Koenkk/zigbee2mqtt#19221]
### What happened?

I purchased some of these switches, they work very well but they have a defect: they do not remember the state before the absence of the mains.
The TUYA app is missing the relay status function . If the utility fails I have to restore it manually. Has anyone managed to solve this problem? The firmware is YKLD-ZCH V1.0
Regards

MDS

### Zigbee2MQTT version

none

### Adapter firmware version

none

### Adapter

none

**Comment by Koenkk** [comment]
This is not the right place to ask questions when using the tuya app and not z2m
