### ISSUE TITLE
Wrong device Tuya TS0601_smoke_5 

### ISSUE THREAD

**Issue by srtxema** [Koenkk/zigbee2mqtt#19238]
### What happened?

A [smoke 5](https://www.zigbee2mqtt.io/devices/TS0601_smoke_5.html) device is recognized like a [smoke 4](https://www.zigbee2mqtt.io/devices/TS0601_smoke_4.html) device

Smoke 5 sensor has exposes for tamper, alarm, fault_alarm but the another one not. 

### What did you expect to happen?

smoke 5 senser was recognized light a smoke 5 sensor with all its exposes

### How to reproduce it (minimal and precise)

pairing

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

0x26720700

### Adapter

conbee

**Comment by Arthur-Askara** [comment]
Did you find any solution ? I have the exact same issue
