### ISSUE TITLE
GLEDOPTO led controller issue

### ISSUE THREAD

**Issue by kgiedrius** [Koenkk/zigbee2mqtt#19237]
### What happened?

<img width="1251" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/15670549/efd7c532-3006-4f93-b19a-a688fc0f8226">

### What did you expect to happen?

no error when changing brightness

### How to reproduce it (minimal and precise)

Error 2023-10-09 23:26:04Publish 'set' 'brightness' to 'led_kontroleris_svetaine_lubu_juostos' failed: 'Error: 'transition' is not a number, got string ()'

no error in 1.30 version

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

20221226

### Adapter

sonoff dongle P

**Comment by Koenkk** [comment]
Your z2m cobfiguration.yaml is invalid, remove the empty transition from it will fix it
