### ISSUE TITLE
Zigbee Thermostat - Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by GotraSYS** [Koenkk/zigbee2mqtt#19240]
### What happened?

I have installed the following Zigbee Thermostat in Home Assistant:
https://www.amazon.de/dp/B09H6L84BB?ref=ppx_yo2ov_dt_b_product_details&th=1

The Thermostat was recognized as “TuYa TV02-Zigbee“ 
https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html

All configurations and settings under "Zigbee2MQTT/Details/" work well
except the schedule "Zigbee2MQTT/Details/Schedule" setting, where I get the following error message:

‘TypeError: Cannot read properties of undefined" (reading ‘toString’)’
.
![zigbee_TypeError_Cannot read properties of undefined_reading _toString_](https://github.com/Koenkk/zigbee2mqtt/assets/142735736/e1adc0db-db32-4181-a9cd-1dd108326a4f)

### What did you expect to happen?

I expected to schedule the temperature for each day..

### How to reproduce it (minimal and precise)

First open under -> Zigbee2MQTT -> Devices 
Then choose the device and klick on -> Exposes 
Then scroll down to -> Schedule
Then choose a day and the error message appear

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

20230508135944

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230508135944

### Debug log

Debug 2023-10-09 23:58:30Received MQTT message on 'zigbee2mqtt/Heizung Arbeitszimmer/set' with data '{"schedule":{"week_day":"tuesday"}}'
Debug 2023-10-09 23:58:30Publishing 'set' 'schedule' to 'Heizung Arbeitszimmer'
Error 2023-10-09 23:58:30Publish 'set' 'schedule' to 'Heizung Arbeitszimmer' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'
Debug 2023-10-09 23:58:30TypeError: Cannot read properties of undefined (reading 'toString') at Object.assertString (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:501:111) at Object.to (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:634:19) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:883:57) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:52) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:127:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)

**Comment by MahrWe** [comment]
I encountered the same issue when trying to set the schedule on my Thermostats.

My Devices are Tuya TV05-ZG which are also recognised as TV02 and have been working fine last winter. 

Z2M Versions 1.33.0 and 1.33.1 are at least effected.

Error message:
Zigbee2MQTT:error 2023-10-11 20:08:40: Exception while calling fromZigbee converter: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]}
Zigbee2MQTT:error 2023-10-11 20:08:42: Exception while calling fromZigbee converter: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]}
Zigbee2MQTT:error 2023-10-11 20:09:01: Publish 'set' 'schedule' to 'Wohnzimmer Thermostat ' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'

**Comment by iatzek** [comment]
1.33.1 in docker with DEBUG=*
```
debug 2023-10-12 14:26:23: Received MQTT message on 'zigbee2mqtt/M_TRV/set' with data '{"schedule":{"schedule":"04:00/23 24:00/21"}}'
debug 2023-10-12 14:26:23: Publishing 'set' 'schedule' to 'M_TRV'
error 2023-10-12 14:26:23: Publish 'set' 'schedule' to 'M_TRV' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'
debug 2023-10-12 14:26:23: TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.assertString (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:501:111)
    at Object.to (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:606:19)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:883:57)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:52)
    at EventEmitter.emit (node:events:526:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:127:27)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)
debug 2023-10-12 14:26:24: Received MQTT message on 'zigbee2mqtt/M_TRV/set' with data '{"schedule":{"week_day":"monday"}}'
debug 2023-10-12 14:26:24: Publishing 'set' 'schedule' to 'M_TRV'
error 2023-10-12 14:26:24: Publish 'set' 'schedule' to 'M_TRV' failed: 'TypeError: Cannot read properties of undefined (reading 'toString')'
debug 2023-10-12 14:26:24: TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.assertString (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:501:111)
    at Object.to (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:634:19)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:883:57)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:52)
    at EventEmitter.emit (node:events:526:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:127:27)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)
```

**Comment by huettenwirt** [comment]
I just installed a new TuYa TV02-Zigbee compatible one and encountered the same issue. My two old ones (same devices) are working with the schedule set then, but I can't adjust the schedule anymore. Getting the "Cannot read properties of undefined (reading 'toString')'" message as well.

**Comment by Koenkk** [comment]
There is currently a bug in the frontend, I will look into it later. For the time being you can set it by publishing an MQTT message.

- Topic: `zigbee2mqtt/my_device_name/set` (change `my_device_name` to your z2m device `friendly_name`)
- Payload: `{"schedule":{"week_day":"saturday", "schedule": "04:00/20 08:30/22 10:10/18 18:40/24 22:50/19.5"}}`

HA users can do this via the developers tools tab:

<img width="1160" alt="Screenshot 2023-10-15 at 20 23 40" src="https://github.com/Koenkk/zigbee2mqtt/assets/2892853/aef79b0f-4754-4920-9dac-fc56a58d89e0">

**Comment by JurajSK** [comment]
for TS0601 it requires different topic
zigbee2mqtt/FRIENDLY_NAME/set/schedule
front end sends wrong topic/payload
I can confirm that it works manualy with developers tools tab with correct topic/payload according [https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html](url)

**Comment by iatzek** [comment]
I can confirm it workarounds my problem with TV02 just fine. 
mosquitto_pub -h msqtt.local -p 8883  -t zigbee2mqtt/M_TRV/set -m '{"schedule":{"week_day":"monday", "schedule": "08:00/18 18:00/21 24:00/21" }}'

**Comment by Zatow** [comment]
I also get this message when I modify "UnitOfMeasure" for Zipulse device
![Capture d'écran 2023-10-19 222533](https://github.com/Koenkk/zigbee2mqtt/assets/59518937/9b47804f-6411-4136-a73f-8f300664a001)

**Comment by Koenkk** [comment]
This should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by osmeest** [comment]
Great news ! Thanks Koen. Looking forward testing the dev branch when I find a minute.

**Comment by huettenwirt** [comment]
I can confirm, it's working with a TS0601. I used the docker image.

Thanks a lot for fixing this!!!

**Comment by git-tail-d** [comment]
Hello,

`# Update
git fetch origin dev
git checkout dev # Change 'dev' to 'master' to switch back to the release version 
git pull
npm ci
`
git checkout dev give the error Pfadspezifikation 'dev' stimmt mit keinen git-bekannten Dateien überein

how it it correct?

**Comment by jiquem** [comment]
Hello @Koenkk I have the same issue with the Zipulses [https://www.zigbee2mqtt.io/devices/ZiPulses.html#lixee-zipulses](url)

**Comment by needles77** [comment]
Hello @Koenkk ,
Same issue than @jiquem  with the lixee-ZiPulse . Same error messages when i want to change divisor or UnitofMeasure.
:(

**Comment by florianbelhomme** [comment]
@jiquem @needles77 You can try this workaround https://github.com/fairecasoimeme/ZiPulses/issues/21#issuecomment-1788820015

**Comment by jiquem** [comment]
Thanks @Koenkk : I will test this weekend

**Comment by joe67** [comment]
Is this bug still present in the version: 1.36.0-1? 
When i publish the schedule in an HA Automation i get the error message "invalid message "null" skipping"

My Automation looks so far:

> service: mqtt.publish
> data_template:
>   topic: zigbee2mqtt/TRV_BZ/set
>   payload: >
>      '{"schedule":{"week_day":"monday", "schedule": "08:00/18 18:00/21 24:00/21" }}'

i also tried over the mqtt exploerer app with this topic 

> zigbee2mqtt/TRV_BZ/set

  and this json data 

> '{"schedule":{"week_day":"monday", "schedule": "08:00/18 18:00/21 24:00/21" }}'

Or do i make something wrong?
