### ISSUE TITLE
[Wrong device]: Woolley SA-035 recognized as eWeLink SWITCH-ZR03-1

### ISSUE THREAD

**Issue by holazit** [Koenkk/zigbee2mqtt#19266]
### Link

https://aliexpress.com/item/1005005630652961.html?spm=a2g0o.order_list.order_list_main.36.40901802pIzdhK

### Model

SA-035

### Description

Wall switch module

### Vendor

Woolley

### Picture (link)

https://www.wbnet.eu/680-wbnet_thickbox/sa-035-smart-switch-wi-fi.webp

### Database entry

{"id":50,"type":"Router","ieeeAddr":"0x7cb94c771de50000","nwkAddr":41009,"manufId":4742,"manufName":"eWeLink","powerSource":"Unknown","modelId":"SWITCH-ZR03-1","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":2,"inClusterList":[0,3,4,5,6,4096,64599,64529],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SWITCH-ZR03-1","manufacturerName":"eWeLink","powerSource":0,"zclVersion":8,"appVersion":1,"stackVersion":0,"hwVersion":0,"dateCode":"20210610-BL","swBuildId":"1.2.1"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00257c8f21","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":0,"hwVersion":0,"dateCode":"20210610-BL","swBuildId":"1.2.1","zclVersion":8,"interviewCompleted":true,"meta":{"configured":-353372667},"lastSeen":1697057036330,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
This is a whitelabel device which uses the same zigbeeModel as the non-whitelabel one, so unfortunately we cannot distinguish it.
