### ISSUE TITLE
[New device support]: Bosch Outdoor Siren

### ISSUE THREAD

**Issue by smarts4home** [Koenkk/zigbee2mqtt#19274]
### Link

https://www.bosch-smarthome.com/uk/en/products/devices/outdoor-siren/

### Database entry

{"id":31,"type":"EndDevice","ieeeAddr":"0x003c84fffee81555","nwkAddr":46660,"manufId":4617,"manufName":"Bosch","powerSource":"DC Source","modelId":"RBSH-OS-ZB-EU","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1027,"inClust erList":[0,1,3,32,1280,1282,2821],"outClusterList":[25],"clusters":{"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0025e15a13","zoneState":1}},"genPowerCfg":{"attributes":{"40960":0,"40961":1,"batteryPercentageRemaining":200,"batteryAl armState":0,"batteryVoltage":39}},"genPollCtrl":{"attributes":{"checkinInterval":6480}},"ssIasWd":{"attributes":{"40960":3,"40961":0,"40962":3,"40963":0,"40964":0,"40965":15}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress": "0x00124b0025e15a13","endpointID":1},{"cluster":1280,"type":"endpoint","deviceIeeeAddress":"0x00124b0025e15a13","endpointID":1},{"cluster":1282,"type":"endpoint","deviceIeeeAddress":"0x00124b0025e15a13","endpointID":1},{"cluster":0,"type ":"endpoint","deviceIeeeAddress":"0x00124b0025e15a13","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":2,"stackVer sion":7,"hwVersion":32,"dateCode":"20211012","swBuildId":"V1.19.00","zclVersion":3,"interviewCompleted":true,"meta":{"configured":939707463},"lastSeen":1697125682289,"defaultSendRequestWhen":"immediate","checkinInterval":1620}

### Comments

Hi,
I'm in the middle of adding new device Bosch Outdoor Siren. 
[https://www.bosch-smarthome.com/uk/en/products/devices/outdoor-siren/](url)
I need to send command **0xF0** to cluster **0x0502** to turn on/off siren, but his command is unavailable for this cluster.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/93162405/003af428-81ef-4da2-a898-3ec653f01ac5)

without this command I can't turn on/off siren alarm.
After this change I'll add new converter for Bosch Outdoor Siren

**Comment by danieledwardgeorgehitchcock** [comment]
This has already been requested and preliminary work done here #13520

**Comment by danieledwardgeorgehitchcock** [comment]
I'm pretty sure as part of the work done above, I added all of the commands. There is however, an issue with the Frontend not allowing the same values to be called accross different clusters which is what you may be experiencing. See nurikk/zigbee2mqtt-frontend#1701 - you should still be able to send the command via MQTT

**Comment by Multipage** [comment]
Anyone having problems with the operation of this device because it isn't working right.

Pairing is OK with the 91 digits but can't turn the alarm on or of 
2024-01-11 16:45:25Publish 'set' 'alarm_state' to '0x385b44fffeaf1b12' failed: 'Error: Cluster 'ssIasWd' has no command '240''

Alarm modes siren, siren sound and sound are totally ignored by the device.

All sound effects are the same and only 3 of them working.

All dipswitsches are in the default ON position

**Comment by smarts4home** [comment]
I solved this problem. pull request was created https://github.com/Koenkk/zigbee-herdsman/pull/900

**Comment by Multipage** [comment]
Thank you very much!!! 

I'll be waiting for the update and then i'll test it!
