### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by smarts4home** [Koenkk/zigbee2mqtt#19273]
### Is your feature request related to a problem? Please describe

Hi,
I'm in the middle of adding new device Bosch Outdoor Siren. 
[https://www.bosch-smarthome.com/uk/en/products/devices/outdoor-siren/](url)
I need to send command 0xF0 to cluster 0x0502 to turn on/off siren, but his command is unavailable for this cluster.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/93162405/003af428-81ef-4da2-a898-3ec653f01ac5)

### Describe the solution you'd like

Please add new command 0xf0 to cluster 0x0502

### Describe alternatives you've considered

no any alternatives

### Additional context

without this command I can't turn on/off siren alarm.
After this change I'll add new converter for Bosch Outdoor Siren
[https://www.bosch-smarthome.com/uk/en/products/devices/outdoor-siren/](url)

**Comment by Koenkk** [comment]
You can add it here: https://github.com/Koenkk/zigbee-herdsman/blob/e6546f2dda7d18f991ed8b9afc6248999ce53649/src/zcl/definition/cluster.ts#L2865
