### ISSUE TITLE
Zigbee adapter stop to communicate with devices

### ISSUE THREAD

**Issue by rdl987** [Koenkk/zigbee2mqtt#19287]
### What happened?

Hello,
I have the same problem but in my case it's regarding all devices, it became unresponsive.

I'm using zigbee2mqtt on docker running in a qnap nas and a SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P.

After a while I got the following error in the log:

`Publish 'set' 'state' to '0x.......' failed: 'Error: Command 0x........../1 genOnOff.on({},`

and every device stop to responde at every zigbee comand.

The only solution is to unplug e plug in again the zigbee adapter or reboot the nas.

Could anyone help me?
Thanks

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

**Comment by StefanGruell** [comment]
I have the same problem with my Nous A1Z, i use also the SONOFF Dongle. The Nous A1Z reports its data but i cant turn it off via the Z2M UI.

**Comment by TEF2one** [comment]
Same problem with by SLZB-06 coordinateur a many devices connected no longer respondoing.

**Comment by biokys** [comment]
Same problem with Deconz

**Comment by rdl987** [comment]
But anyone has a solution?

**Comment by StefanGruell** [comment]
> But anyone has a solution?

For me unplugging also didnt work, i had to remove all devices which were connected to my NOUS A1Z plug. Then remove the plug from the network and repair it in close proximity (for a good LQI). Then i was able to send commands to the plug again and reconnect all other sensors.

**Comment by Shchepotin** [comment]
Same problem with SONOFF (Z2M 1.33.1)

**Comment by rdl987** [comment]
I didn't understand if the problem is related only to docker or some problem with configuration between the container and the nas

**Comment by Shchepotin** [comment]
@rdl987 also problem happen with Operating System installed to Raspberry PI

**Comment by rdl987** [comment]
So, just to recap, the only installation that works is as addon to Home Assistant Operating System. Right?

Could please, anyone, explain the differences between the docker version and addon version?

Thank you
