### ISSUE TITLE
Z2M Frontend not displaying/ or displaying with large images

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#19282]
### What happened?

A few times today, when i load the Z2m FRONTEND its rendered like below

![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/130915d8-b6b5-4591-b630-a327adc4d4d5)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/58960644/6814d19b-8220-4d29-8924-7436a89fb88a)

### Zigbee2MQTT version

1.33.1-dev commit: afb83fc

### Adapter firmware version

20230922

### Adapter

Zigbee ESP32GW (Zigstar)

**Comment by MerekW** [comment]
I also experienced this (large, non-scrollable front-end behavior) as well as a bad gateway message while accessing from the sidebar:
![Screenshot_20231012_210309_Home Assistant.jpg](https://github.com/Koenkk/zigbee2mqtt/assets/123496218/cdd1cf74-18fa-4ed5-95d7-ce3cbf02019c)

**Comment by cloudbr34k84** [comment]
yep i got that screen as well. Pressing crtl f5 helps

**Comment by briangunderson** [comment]
I was hoping someone besides me would have this problem too! Of course it happened to me while I was in the middle of migrating a bunch of devices from one zigbee environment to another so I assumed it was something I did! Guess not! Let me know if screenshots/logs would be helpful to anyone.

**Comment by alexmil72** [comment]
It happened to me too, also the Zigbee devices are unresponsive. Tried to access the Z2M configuration page on HA and I got "The add-on seems to not be ready, it might still be starting. Do you want to try again?", tried to restart Z2M and HA still doesn't work. There are no errors in Z2M logs and HA.

**Comment by Tntdruid** [comment]
The last HA update broke it.

**Comment by msaario** [comment]
I confirm same issue after Home Assistant Core 2023.10.2 update.

**Comment by alexmil72** [comment]
Fixed reverting back HA to 2023.10.1

**Comment by kted** [comment]
Same thing happens with ESPhome, so the update changed something that affects more than one integration.

**Comment by cloudbr34k84** [comment]
Awesome

**Comment by CattDamon** [comment]
> Fixed reverting back HA to 2023.10.1

ha core update --version=2023.10.1       in case anyone didn't know the commands.

**Comment by jvuotila** [comment]
Home Assistant Core 2023.10.2 update and same problems here.

**Comment by MerekW** [comment]
**Appears to be resolved in HA Core 2023.10.3**

**Comment by Tntdruid** [comment]
Works again in Home Assistant 2023.10.3
