### ISSUE TITLE
[Feature request]: Ability for Z2M to restart/reset the adapter

### ISSUE THREAD

**Issue by aurimasniekis** [Koenkk/zigbee2mqtt#19288]
### Is your feature request related to a problem? Please describe

Yes. Multiple types of adapters occasionally become unresponsive or freeze, which may sometimes cause Z2M to crash. The current challenge is that manually resetting or restarting the adapter also causes Z2M to crash, leading to undesirable behavior.

### Describe the solution you'd like

I propose adding a feature in Z2M that allows users to restart or reset the adapter through various methods such as a script command, web hook, or an MQTT message. This built-in functionality would ensure that the adapter can be restarted without crashing Z2M. Implementing this feature within Z2M itself would simplify the process for developers and users.

### Describe alternatives you've considered

Currently, I've attempted to implement a manual adapter restart mechanism. However, this approach causes Z2M to crash, which is not a feasible solution.

### Additional context

Having an integrated solution within Z2M to handle adapter restarts would significantly enhance its robustness and usability, especially in situations where adapters become unresponsive. This would provide a smoother experience for users and developers alike.

### For example:

- For a POE based Z2M adapter, users could have an esphome controlled outlet. This would allow for remote resets of the adapter when needed.
- For USB-based adapters, a similar approach could be used, but with a USB power injector combined with a smart outlet. By powering on/off the USB power brick, the adapter can be reset without causing system-wide disruptions.

These examples further underscore the importance and utility of having a built-in restart/reset feature in Z2M for various adapter types.

**Comment by lux73** [comment]
wouldn't be the better way to buy an Adapter who has not this badly behavior?
