### ISSUE TITLE
"Program" fields for Moes BHT-002-GCLZB (TS0601 _TZE200_aoclfnxz) should be grouped by day

### ISSUE THREAD

**Issue by osmeest** [Koenkk/zigbee2mqtt#19297]
### What happened?

For BHT-002, the schedule is defined as a long list of input fields without separators or labels. User needs to guess that the first 4 segments are for weekdays, next 4 are for Saturday and last 4 are for Sunday.
For other TRVs, the schedule is configured as a string per day, which is already more usable.

### What did you expect to happen?

A group of fields per day and each field labelled as "Segment 1 Start time", "Segment 1 Temp"...

### How to reproduce it (minimal and precise)

- open Zigbee2MQTT Web UI
- select BHT-002 in Devices page
- select Exposes tab
- scroll down to "Program"

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E"

### Debug log

info  2023-10-14 10:34:00: MQTT publish: topic 'zigbee2mqtt/Moes BHT-002', payload '{"child_lock":"UNLOCK","current_heating_setpoint":18,"deadzone_temperature":1,"heat":"OFF","linkquality":160,"local_temperature":20.5,"local_temperature_calibration":-2,"max_temperature":35,"max_temperature_limit":33,"min_temperature_limit":null,"preset":"program","preset_mode":"program","program":{"saturday_p1_hour":7,"saturday_p1_minute":0,"saturday_p1_temperature":21,"saturday_p2_hour":9,"saturday_p2_minute":0,"saturday_p2_temperature":18,"saturday_p3_hour":19,"saturday_p3_minute":0,"saturday_p3_temperature":20,"saturday_p4_hour":23,"saturday_p4_minute":30,"saturday_p4_temperature":16,"sunday_p1_hour":7,"sunday_p1_minute":0,"sunday_p1_temperature":21,"sunday_p2_hour":9,"sunday_p2_minute":30,"sunday_p2_temperature":18,"sunday_p3_hour":19,"sunday_p3_minute":0,"sunday_p3_temperature":20,"sunday_p4_hour":23,"sunday_p4_minute":0,"sunday_p4_temperature":16,"weekdays_p1_hour":6,"weekdays_p1_minute":0,"weekdays_p1_temperature":21,"weekdays_p2_hour":8,"weekdays_p2_minute":30,"weekdays_p2_temperature":18,"weekdays_p3_hour":18,"weekdays_p3_minute":30,"weekdays_p3_temperature":20,"weekdays_p4_hour":23,"weekdays_p4_minute":0,"weekdays_p4_temperature":16},"running_state":"idle","sensor":"IN","system_mode":"heat"}'

**Comment by kds69** [comment]
To add...

Though I praise the idea that drove to this complicated object structure in zigbee2mqtt/HA, I think the cost/benefit ratio is not in favor of this approach.
It makes it so complicated whereas it was very simple months, years ago (and btw aligned to other TRVs)...
As simple as below:
```
{
   "weekdays": "06:00/21°C 08:30/20°C 15:30/21°C 17:30/20°C",
   "saturday": "06:30/21°C 10:00/20°C 15:00/21°C 21:30/20°C", 
   "sunday": "06:30/21°C 10:00/20°C 15:00/21°C 21:30/20°C"
}
```
True it is to the expense of having nice cursors in HA... but the object strucure approach is disgraceful and most impoortantly very difficult to play with in srcipts/nodered and in the end not helping much more the end user vs a stupid text field entry for each sets of days.

Visuals save a lot of words:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/75844627/4dfb537f-3855-4ca5-852a-f5ef1ee8b198)


vs


![image](https://github.com/Koenkk/zigbee2mqtt/assets/75844627/f7776b49-5b28-4070-9d4e-15fc8ae40d87)
