### ISSUE TITLE
Onesti Products AS easyCodeTouch_v1 doesnt show correct battery status 

### ISSUE THREAD

**Issue by stefancn** [Koenkk/zigbee2mqtt#19299]
### What happened?

When the batteries are "empty"  , eq. 20% left ... the doorlock battery (batteryPercentageRemaining) stills shows 100%...  Today my lock blinked red, signaling urgent battery change.   Is this bug fixable. ?

Regards  /Stefan

### Zigbee2MQTT version

1.35.3.1

### Adapter firmware version

7.1.1.0 build 273

### Adapter

HA Skyconnect

**Comment by stefancn** [comment]
After latest update, it shows 200% !!!

**Comment by msandvold** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/21182
Same here.

**Comment by msandvold** [comment]
check this out, waiting for an answer.
[https://github.com/Koenkk/zigbee-herdsman-converters/pull/6940](url)

**Comment by stefancn** [comment]
Thanks... but all other info seems to work, door open/close last used pin... remote opening work. It is only the battery status that is wierd.

**Comment by msandvold** [comment]
It is now fixed with Version 1.36.1 :)

**Comment by stefancn** [comment]
Thanks, but do you have any idea why it now is stucked at 100%...
