### ISSUE TITLE
Could not open secific file

### ISSUE THREAD

**Issue by jonydebu** [Koenkk/zigbee2mqtt#193]
Hi , all goes well until last step . When i run the "perform action" the CC2531 greenled turns off and Smart Flash programm indicate "could not open sepecif file" . TI led Debugger is green .
![image](https://user-images.githubusercontent.com/30730098/42695063-86f45424-86b4-11e8-8450-825fa3b27411.png)
Some idea ? Thanks.

**Comment by Koenkk** [comment]
What are the contents of the .hex file? (open it with e.g. notepad)

**Comment by jonydebu** [comment]
Hi a very long file (I think too large to paste here) . I´ve download it from here : 
![image](https://user-images.githubusercontent.com/30730098/42704445-13732f86-86d0-11e8-80de-9f6214831b61.png)

**Comment by jonydebu** [comment]
oops you´re the owner , great job and thanks for your help.

**Comment by jonydebu** [comment]
Hi , i´ve install this one from this repository and this one seems to flash well .
![image](https://user-images.githubusercontent.com/30730098/42704702-2ff3a838-86d1-11e8-85b9-01d9062582a4.png)
Thanks 4 all .
