### ISSUE TITLE
Tuya leak sensor TS0207 not reporting battery

### ISSUE THREAD

**Issue by Suxsem** [Koenkk/zigbee2mqtt#19308]
### What happened?

Hi bought a couple Aubess IH-K665 (that seems to be a rebranded TS0207, vendor _TZ3000_k4ej3ww2).

It seems to me that device ONLY communicates when leak status changes.

The "last seen" attribute in the Z2M dashboard is always "N/A" (despite having enabled availability and added last_seen: ISO_8601_local to the mqtt configuration. Availability says "online" but I don't know on what it is based.

I tried with this but after pressing apply I always get a timeout error.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/830773/b84f41ee-656b-4b5a-a3e6-7b2d5cb76d5f)

I enabled Z2M logging about an hour ago and so far I didn't get any log about any communication with the device, I will monitor the next 24 hours.

Battery says always 100%, I'm afraid to not get any low battery notification and thus ends with an offline device.

Thank you

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

7.3.1.0 build 0

### Adapter

EZSP v12

**Comment by buddy31130** [comment]
Mine is always showing low battery even with new ones

**Comment by Suxsem** [comment]
They started to working, I think the issue was in my zigbee network. Sorry for the false reporting

**Comment by DwarfDecker** [comment]
I've to devices in to different houses, one repport 0% for weeks and the other get not battery level at all.

Note: Zigbee2MQTT version
[1.40.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.1)

**Comment by shawnhaywood** [comment]
Reviving this post.  I purchased the same device and have the exact same issue.  Device not providing any kind of update unless leak detected.

**Comment by stevenengland** [comment]
related: https://github.com/Koenkk/zigbee2mqtt/issues/21611
