### ISSUE TITLE
[Feature request]: Add support for new Ikea TRADFRI bulb E26 CWS 810lm

### ISSUE THREAD

**Issue by audunmg** [Koenkk/zigbee2mqtt#19306]
### Is your feature request related to a problem? Please describe

Ikea released new 810 lumen bulbs, but  I only have the CWS version.

### Describe the solution you'd like

I will open a small pull request to zigbee-herdsman-converters

### Describe alternatives you've considered

I tested the bulb and it works identically to LED1924G9 bulbs.

### Additional context

Thank you for this excellent piece of software!

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6291, thanks!
