### ISSUE TITLE
[Feature request]: S520567 position states [Stopped/Opening/Closing]

### ISSUE THREAD

**Issue by Matssa56** [Koenkk/zigbee2mqtt#19310]
### Is your feature request related to a problem? Please describe

This is to open the issue #16827 again.

Today we have two states : closed, opened. The idea is to add opening and closing. We know that the official Wiser app reports these informations (see screenshot [in #16827](https://github.com/Koenkk/zigbee2mqtt/issues/16827#issuecomment-1483417802) ).

### Describe the solution you'd like

Motor_state or moving or running or openning or closing state to sned to Home Assistant

### Describe alternatives you've considered

I tried using template covers in Home Assistant and they don't seem to give my the opening or closing, even if I supply the %. I was thinking of making some templates / automations in order to set the opening or closing if n,ew_position > old_position or something like that but we will have at least 1s delay and not sure that it will really work well.

### Additional context

I have several devices and willing to test stuff out but I need help understanding what to do.
Link to the first commit to add in Zigbee2Mqtt : https://github.com/Koenkk/zigbee2mqtt/issues/10303

Here are the reports from the clusters from Zigbee2mqtt : 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16662808/06b59699-f87f-447c-9365-a0d43c69790a)

**Comment by Matssa56** [comment]
Something that we can do is maybe see what changes in terms of cluster or feedback when triggering the openning or closing of the motor, not sure how I can do that though ^^'

**Comment by Pepeanuts** [comment]
Any update for this feature request ?
