### ISSUE TITLE
[Wrong device picture]: thermostat GTZ06 called TS0601_thermostat_1 or _TZE200_z1tyspqw

### ISSUE THREAD

**Issue by pawol** [Koenkk/zigbee2mqtt#19321]
### Link

https://hurt.id3.pl/product-pol-447-Glowica-termostatyczna-GTZ06-ZigBee-3-0-TUYA.html

### Model

GTZ06 called TS0601_thermostat_1 or _TZE200_z1tyspqw

### Description

thermostat

### Vendor

id3

### Picture (link)

https://static3.hurt.id3.pl/pol_pm_Glowica-termostatyczna-GTZ06-ZigBee-3-0-TUYA-447_4.png

### Database entry

{"id":8,"type":"EndDevice","ieeeAddr":"0xa4c13863d1434585","nwkAddr":38073,"manufId":4417,"manufName":"_TZE200_z1tyspqw","powerSource":"Battery","modelId":"TS0601

### Notes

{"id":8,"type":"EndDevice","ieeeAddr":"0xa4c13863d1434585","nwkAddr":38073,"manufId":4417,"manufName":"_TZE200_z1tyspqw","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0002\u0000\u0000\u0000i\u0003\u0000\u0000\u0000i","65506":56,"65508":1,"65534":0,"appVersion":72,"modelId":"TS0601","manufacturerName":"_TZE200_z1tyspqw","powerSource":3,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1697539780792,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
