### ISSUE TITLE
[New device support]: Philips Hue Sphere 9290031512

### ISSUE THREAD

**Issue by aurelienvelat** [Koenkk/zigbee2mqtt#19323]
### Link

https://www.assets.signify.com/is/content/Signify/Assets/signify/global/20221004-philips-hue-color-and-ambiance-lg-bulb.pdf

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0x001788010d257fea","nwkAddr":13467,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCO005","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230116","swBuildId":"1.101.10","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1697557502222,"defaultSendRequestWhen":"immediate"}

### Comments

Got stuck at creating the converter like [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/18465)

It's the same device as the one mentionned, only the form of the bulb differs. (So the ZigbeeModel differs too and it's not supported)

![9290031512](https://github.com/Koenkk/zigbee2mqtt/assets/25060036/c4991292-9f62-4039-bfd2-f0f2e35a717e)

### Supported color modes

color temperature, rgb, dimming

### Color temperature range

Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
