### ISSUE TITLE
[New device support]: ZSS-LP-HP02-MS MOES 

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#19333]
### Link

https://moeshouse.com/products/zigbee-human-presence-sensor

### Database entry

{"id":76,"type":"Router","ieeeAddr":"0xa49e69fffe909250","nwkAddr":58079,"manufId":4098,"manufName":"_TZ3218_awarhusb","powerSource":"Mains (single phase)","modelId":"TS0225","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,4,5,57346,16384,61184,1280],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"TS0225","manufacturerName":"_TZ3218_awarhusb","dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0024c2772c","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":1,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1697635753561,"defaultSendRequestWhen":"immediate"}

### Comments

I tried use the last available release of Z2M and the device appears as not supported yet 

Can you please include this device in a new release? 

Thank you and best regards

**Comment by francisp2** [comment]
Try the external converter from this topic
https://github.com/Koenkk/zigbee2mqtt/issues/18637
