### ISSUE TITLE
XIAOMI and AQARA plugs OTA error: No new image available - but 100% there is new image available

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#19331]
### What happened?

Go to OTA tab, check if is new fw available, and see that: there is. But if click to update - error show: No new image available. Problem with Xiaomi and Aqara plugs models: [SP-EUC01](https://www.zigbee2mqtt.io/devices/SP-EUC01.html#xiaomi-sp-euc01) [ZNCZ04LM](https://www.zigbee2mqtt.io/devices/ZNCZ04LM.html#xiaomi-zncz04lm)

This devices fw date: 09-22-2020 and 09-06-2019 and i have other the same davices and have fw date: 01-23-2022. Iam sure that update pending but cant update fw becauser error

![Adnotacja 2023-10-18 111119](https://github.com/Koenkk/zigbee2mqtt/assets/91805313/6a00da91-f2f1-49c5-b6cb-16d96f82d60d)

![Adnotacja 2023-10-18 111226](https://github.com/Koenkk/zigbee2mqtt/assets/91805313/61e9b883-317a-4ad7-bd39-4addb91028e4)

![Adnotacja 2023-10-18 111306](https://github.com/Koenkk/zigbee2mqtt/assets/91805313/060d1e95-12fd-4f54-9381-216d0c3711f5)

![Adnotacja 2023-10-18 112713](https://github.com/Koenkk/zigbee2mqtt/assets/91805313/85d60337-41c9-4fdc-ba05-ed73100cc26d)

### What did you expect to happen?

when click update button, devices start updating and stays on newest fw without error

### How to reproduce it (minimal and precise)

hard to say, but go to ota tab and check it if You have this devices models i have

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

Error 2023-10-18 11:09:45Update of 'XIAOMI_pluxxxxxxxx' failed (No new image available)
Error 2023-10-18 11:09:52Update of 'XIAOMI_pluxxxxxxx' failed (No new image available)
Error 2023-10-18 11:09:54Update of 'XIAOMI_pluxxxxxxx' failed (No new image available)
Error 2023-10-18 11:09:56Update of 'XIAOMI_pluxxxxxxxxx' failed (No new image available)
Error 2023-10-18 11:11:38Update of 'XIAOMI_pluxxxxxx' failed (No new image available)
Error 2023-10-18 11:11:41Update of 'AQARA_pluxxxxx' failed (No new image available)
Error 2023-10-18 11:12:34Update of 'AQARA_pluxxxxxxxx' failed (No new image available)

**Comment by Koenkk** [comment]
Xiaomi firmwares are not taken directly from their servers, someone has to retrieve them from the Xiaomi servers and upload them to https://github.com/koenkk/zigbee-ota. This was probably not done yet for this firmware, you can find out how to do that here: https://www.zigbee2mqtt.io/advanced/more/tuya_xiaomi_ota_url.html

**Comment by KitHubek** [comment]
unfortunately i havent aqara hub to done this procedure
