### ISSUE TITLE
Error: Exception while calling fromZigbee converter PJ-MGW1203 power meter

### ISSUE THREAD

**Issue by semkyskov** [Koenkk/zigbee2mqtt#19341]
### What happened?

The device PJ-MGW1203 power meter keeps giving an error message:

Error 2023-10-19 10:25:41Exception while calling fromZigbee converter: Command 0x70ac08fffed04a73/1 manuSpecificTuya.mcuGatewayConnectionStatus({"payloadSize":1,"payload":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))}

Error 2023-10-19 10:26:20Exception while calling fromZigbee converter: Command 0x70ac08fffed04a73/1 manuSpecificTuya.mcuGatewayConnectionStatus({"payloadSize":1,"payload":1}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)}

### Zigbee2MQTT version

 1.33.1

### Adapter firmware version

20230507

### Adapter

ZigstarLan zStack3x0

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13035624/log.txt)

**Comment by Koenkk** [comment]
Looks like some unstability in the `20230507` firmware, please follow up here: https://github.com/Koenkk/Z-Stack-firmware/discussions/478
