### ISSUE TITLE
CC2530 CC2591 programming help

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#1935]
I'm trying to flash a 2530 gb and I can't quite understand what I have to do.
Reading and seeing that it is no longer necessary to solder the cables to GND, I have connected the DC Debuger and gb 2530 to usb and between them with a 5-wire cable that comes with the gb2530. The CC deguger light stays red and turns green even if you restart.
Can anyone tell me what am I doing wrong?

**Comment by james-fry** [comment]
Is there a jumper on your gban debug board between pins 9 and 10?
If so try removing it.

**Comment by zhapwey** [comment]
Voucher detected the problem is the 5-pin cable, which is attached in reverse, turn it over and that's it.

Thanksss
