### ISSUE TITLE
Ikea Shortcut Button E1812 send Null

### ISSUE THREAD

**Issue by MorganMLGman** [Koenkk/zigbee2mqtt#19356]
### What happened?

Ikea shortcut button E1812 is sending Null as action value instead of correct value.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/33269270/145b7a10-fdb0-45cc-903a-828d291e996e)

### What did you expect to happen?

Correct action, press, hold, release, etc.

### How to reproduce it (minimal and precise)

1. Join device to the network
2. Button firmware 24.4.6
3. Press a button

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20221226

### Adapter

Sonoff Zigbee 3.0 CC2652P

**Comment by danieledwardgeorgehitchcock** [comment]
This may be the correct behaviour for the device.. [See here](https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty)

**Comment by MorganMLGman** [comment]
But HA also doesn't see state change, it is always "action: none" and if I remember correctly some time ago the behaviour was like shown there [IKEA E1812](https://www.zigbee2mqtt.io/devices/E1812.html#action-enum). But it was some time ago and me moving out, and now in new place I can't get it to work.

**Comment by bazb** [comment]
I have the same issue. Broke my buttons.
