### ISSUE TITLE
Aqara Rolling Shutter Controller

### ISSUE THREAD

**Issue by kvet** [Koenkk/zigbee2mqtt#1937]
Does this project support Aqara ZNGZDJ11LM?

**Comment by Koenkk** [comment]
Supported devices can be found on: https://www.zigbee2mqtt.io/information/supported_devices.html

If it's not supported support can be added for users owning this device: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by kvet** [comment]
But maybe someone tried to pair it? I just want to be sure that it will be working...

**Comment by Koenkk** [comment]
If it's not supported you never know for sure that it will be working, somebody has to be first.
