### ISSUE TITLE
[Wrong device]: TS130F_dual from Lerlink gets recognized as TS130F (single)

### ISSUE THREAD

**Issue by svi-nja** [Koenkk/zigbee2mqtt#19393]
### Link

https://www.alibaba.com/product-detail/1-2-Gang-ZigBee-Curtain-Switch_1600549357157.html?spm=a2700.shop_plgr.41413.26.16473f37lr7FsD

### Model

A2-Z72

### Description

2-gang curtain/blind switch

### Vendor

Tuya

### Picture (link)

https://imgur.com/a/ZFAZxPf

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0xa4c138eeb375de10","nwkAddr":16245,"manufId":4417,"manufName":"_TZ3000_xdo0hj1k","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[4,5,6,258,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":"","zclVersion":3}},"genOnOff":{"attributes":{"tuyaBacklightSwitch":1,"tuyaBacklightMode":1}},"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":100,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":1,"moesCalibrationTime":309}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":514,"inClusterList":[4,5,6,258,57345],"outClusterList":[],"clusters":{"closuresWindowCovering":{"attributes":{"32768":0,"currentPositionLiftPercentage":0,"tuyaMovingState":1,"tuyaCalibration":1,"tuyaMotorReversal":0,"moesCalibrationTime":100}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1698048258491,"defaultSendRequestWhen":"immediate"}

### Notes

This appears similar to issue #17728

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
