### ISSUE TITLE
Ikea 1603/1702 message

### ISSUE THREAD

**Issue by mbrackjr** [Koenkk/zigbee2mqtt#1940]
# Bug Report
## What happened
Unexpected warning shows up in logging, now 2nd time in about a week. Device is sometimes non-responsive, so wonder if it's related.

`warn: No converter available for 'E1603/E1702' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"10":[69,49,54,48,51]}}'`

## What did you expect to happen
No warnings ;-)

## How to reproduce it (minimal and precise)
Not able; can keep an eye out if that helps.

## Debug Info
zigbee2mqtt version: v1.5.1 (hassio plugin)
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
`devChange` event are artificial events generated by zigbee-shepherd. Normally these are ignored, however with zigbee-herdsman (#1888) these events won't be generated at all anymore.

High likely not related to your device being unresponsive.
