### ISSUE TITLE
Aubess WHD02 (without power monitoring) disconnected after a day, now leaves immediately after joining

### ISSUE THREAD

**Issue by andreagdipaolo** [Koenkk/zigbee2mqtt#19403]
### What happened?

When I paired the device the first time it worked for at least 12 hours.
The next day I couldn't find it anymore in the Z2M web ui and I tried to pair it again.
I tried with the dev version too and I updated my coordinator to the latest firmware with no luck.
When I try to pair the device again, in the logs in debug mode I can just see it immediately **leaving**, never joining, nothing else. The device LED blinks for some minutes without ever becoming steady.
I believe it's not a limit on how many devices I can have because I successfully added a couple of new sensors for testing.
**I can see the device in Settings > RAW**

### What did you expect to happen?

The device should pair and stay connected. It's a router and it's powered from mains.

### How to reproduce it (minimal and precise)

Allow joining, press the pairing button for 10 seconds, see logs because nothing happens.

### Zigbee2MQTT version

1.33.1 commit: 7e63039

### Adapter firmware version

7.3.1.0 build 176

### Adapter

Sonoff Dongle-E

### Debug log

```
 2023-10-24 03:27:14 Device 'Interruttore 1' left the network
 2023-10-24 03:27:14 MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Interruttore 1","ieee_address":"0xa4c13886aba19efb"},"type":"device_leave"}'
 2023-10-24 03:27:14 Device 'Interruttore 1' left the network
 2023-10-24 03:27:14 MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Interruttore 1","ieee_address":"0xa4c13886aba19efb"},"type":"device_leave"}'
```

**Comment by andreagdipaolo** [comment]
Seems to be solved after a power cycle.

**Comment by andreagdipaolo** [comment]
Seems to be solved after a device power cycle.

**Comment by andreagdipaolo** [comment]
Disconnected again and a new power cycle won't fix it. Will investigate tomorrow. 
Meanwhile I switched again to dev branch.

**Comment by andreagdipaolo** [comment]
Seems solved after switching to another channel.

**Comment by Nickolay40** [comment]
Hello, which channel you use .. i have same issue with this device ?

**Comment by andreagdipaolo** [comment]
I switched from 11 to 15 even though they are both free here.
I had some other problems but apparently they were fixed after stopping the container, removing the coordinator, leaving it for a minute, plugging it again and starting the container.
Adding another router near it maybe helped too.

**Comment by Nickolay40** [comment]
Ok. I try to fixed it without changing channel, because if I change channel need to fix all network with all devices. just only one of 3 WHD02 has this problem.

**Comment by Nickolay40** [comment]
Hello, I solved my problem without change channel ... Problem was with installetion this switch in socket box. Buttom on switch was always pushed. It caused re-pair this device every time in Z2M.  I just removed plastic bottom.
