### ISSUE TITLE
[New device support]: iHORN LH-99ZB (LH05121)

### ISSUE THREAD

**Issue by benchieng** [Koenkk/zigbee2mqtt#19417]
### Link

https://www.ihorn-tech.com/Product/SensorRF/Smoke/ede29afe-ed6e-40bc-baa7-ccc199583cd6.html

### Database entry

{"id":71,"type":"EndDevice","ieeeAddr":"0x00158d00075b23cc","nwkAddr":54307,"manufId":4628,"manufName":"iHorn","powerSource":"Battery","modelId":"LH05121","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"LH05121","manufacturerName":"iHorn","powerSource":3,"zclVersion":1,"appVersion":15,"stackVersion":2,"hwVersion":17,"dateCode":"20170414"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002a1aa366","zoneState":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":15,"stackVersion":2,"hwVersion":17,"dateCode":"20170414","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1698214021210,"defaultSendRequestWhen":"immediate"}

### Comments

I tried adding this smoke alarm to Z2M but it shows up as unsupported. Also tried pairing within Z2M Edge but still shows up as unsupported.

**Comment by serot23** [comment]
can this be reropend i have several konke smoke detectors, where 1 is supported by z2m and idewntify as:

Apparaat type
EndDevice
Zigbee model
3AFE010104020028
Zigbee Fabrikant
Konke
Omschrijving
Photoelectric smoke detector


Fabrikant
[Konke](https://www.zigbee2mqtt.io/supported-devices/#v=Konke)
Model
[TW-S1](https://www.zigbee2mqtt.io/devices/TW-S1.html#konke-tw-s1)

and several others which are not supported, i bought these first and the voice is in chinese, the internals and exterior looks identical but this identifies as:

Apparaat type
EndDevice
Zigbee model
LH05121
Zigbee Fabrikant
iHorn
Ondersteuningsstatus
Niet ondersteund [(how_to_add_support)](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html)


Firmware build date
20170414

but the exposed stuff isn't the same as the english spoken, supported one. external converter worked untill version 1.36 after the updates, i cant get it to work like the supported one.

when i press generate they generate the same external converter, 

but the supported one works like intended like my old converter:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['LH05121'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'LH05121', // Vendor model number, look on the device for a model number
    vendor: 'Konke', // Vendor of the device (only used for documentation and startup logging)
    description: 'Konke smoke detector', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.ias_smoke_alarm_1],
    toZigbee: [],
    exposes: [e.smoke(), e.battery_low()], // <-- this will define which fields will be exposed in the definition message to configure a front end (e.g. the z2m frontend, Home Assistant, Domoticz)
};

module.exports = definition;
