### ISSUE TITLE
Issue flashing dongle ITEAD Sonoff ZBDongle-P

### ISSUE THREAD

**Issue by lucadjc** [Koenkk/zigbee2mqtt#19418]
### What happened?

Ciao,
i've some troubles flashing device ITEAD Sonoff ZBDongle-P v1.3

flashed on Windows with 
python cc2538-bsl.py -p COM4 -evw --bootloader-sonoff-usb CC1352P2_CC2652P_launchpad_coordinator_20230507.hex

this is the output (it seems ok)
Opening port COM4, baud 500000
Reading data from CC1352P2_CC2652P_launchpad_coordinator_20230507.hex
Your firmware looks like an Intel Hex file
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:2A:2F:1D:D0
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 360448 bytes starting at address 0x00000000
Write 104 bytes at 0x00057F988
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0xe83aa727)

Now when I started zigbee2mqtt on Home assistant i get this errors.

error 2023-10-25 00:27:23: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

tried to re-flash it with smart rf flash programmer but there i got the error
>Initiate access to target: COM4 using 2-pin cJTAG.
>Reading file: D:/Downloads/cc2538-bsl-master/cc2538-bsl-master/CC1352P2_CC2652P_launchpad_router_20221102.hex.
>Unknown record type: 3.
>Reset target ...
>Reset of target successful.

or
>Connecting over serial bootloader failed: No response from device. Device may not be in bootloader mode. Reset device and try again.
If problem persists, check connection and baud rate.
>Failed to create device object.

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

20230507

### Adapter

ITEAD Sonoff ZBDongle-P v1.3

**Comment by francisp2** [comment]
Use https://zig-star.com/radio-docs/zigstar-multi-tool
