### ISSUE TITLE
Wrong payload length in packet via publish

### ISSUE THREAD

**Issue by alexmorbo** [Koenkk/zigbee2mqtt#1941]
# Bug Report
## What happened
Got wrong packet length byte when publish packet include device information (`include_device_information: true`)

## What did you expect to happen

When include_device_information: false in z2m logs:
```
9/8/2019, 10:03:37 PM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":1}}' of device 'lumi.sensor_swit' (0x00158d0001eb90f6) of endpoint 1
9/8/2019, 10:03:37 PM - info: MQTT publish: topic 'zigbee2mqtt/Button', payload '{"linkquality":52,"battery":100,"voltage":3005,"click":"single"}'
```
At my backend (php) i got:
```
0T\x00\x12zigbee2mqtt/Button{"linkquality":57,"battery":100,"voltage":3005,"click":"single"}
```
Byte `T` means payload length is 84, thats correct

Now i turn on include_device_information to true
z2m logs:
```
9/8/2019, 10:08:40 PM - debug: Received zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":1}}' of device 'lumi.sensor_swit' (0x00158d0001eb90f6) of endpoint 1
9/8/2019, 10:08:40 PM - info: MQTT publish: topic 'zigbee2mqtt/Button', payload '{"linkquality":52,"battery":100,"voltage":3005,"click":"single","device":{"ieeeAddr":"0x00158d0001eb90f6","friendlyName":"Button","type":"EndDevice","nwkAddr":5,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_swit","hwVersion":1,"swBuildId":"3000-0001","dateCode":"20180629","status":"online"}}'
```
At my backend (php):
```
b"0Û\x02\x00\x12zigbee2mqtt/Button{"linkquality":52,"battery":100,"voltage":3005,"click":"single","device":{"ieeeAddr":"0x00158d0001eb90f6","friendlyName":"Button","type":"EndDevice","nwkAddr":5,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_swit","hwVersion":1,"swBuildId":"3000-0001","dateCode":"20180629","status":"online"}}"
```
Byte `Û` means payload length is 195, but real length is more than 300 symbols

## Debug Info
zigbee2mqtt version: 1.5.1 (#ac3b924)
CC253X firmware version:

**Comment by Koenkk** [comment]
zigbee2mqtt uses the following MQTT library: https://www.npmjs.com/package/mqtt. 

Could you check, by creating a small example by yourself, if the issue comes from that library?

**Comment by alexmorbo** [comment]
It's strange

In WireShark i got correct **payload length**
![Снимок экрана 2019-09-11 в 9 58 59](https://user-images.githubusercontent.com/435562/64675051-e2f02b80-d47a-11e9-80b6-a2a072a0215d.png)

And this is full **payload** with device info
<img width="854" alt="Снимок экрана 2019-09-11 в 10 00 14" src="https://user-images.githubusercontent.com/435562/64675141-19c64180-d47b-11e9-9d04-9e6a1902893e.png">

**Comment by Koenkk** [comment]
ok, I will close this as it is not a zigbee2mqtt issue.
