### ISSUE TITLE
[New device support]: Philips Hue Lightguide Ellipse

### ISSUE THREAD

**Issue by TomTomB** [Koenkk/zigbee2mqtt#19423]
### Link

https://www.philips-hue.com/en-us/p/bulb-ellipse---e26-smart-bulb/046677577469

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0x001788010d480ecd","nwkAddr":49778,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCZ001","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}},"genBasic":{"attributes":{"zclVersion":8}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1698274723058,"defaultSendRequestWhen":"immediate"}

### Comments

It's pretty much the same as the "Hue white and color ambiance" bulb - just with a different shape. It would be nice to see this one officially supported. 

### External converter

```shell
const definition = {
    zigbeeModel: ['LCZ001'],
    model: '929003151301',
    vendor: 'Philips',
    description: 'Hue Lightguide',
    extend: philips.extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 500]}),
};
```

### Supported color modes

color temperature, color (rgb)

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}

**Comment by Koenkk** [comment]
Device has already been added, will be supported in the 1 November release.
