### ISSUE TITLE
Sber SBDV-00029 ttriggers every 2 hours 

### ISSUE THREAD

**Issue by i-wintermute** [Koenkk/zigbee2mqtt#19439]
### What happened?

Sber SBDV-00029 ttriggers every 2 hours an empty room

### What did you expect to happen?

the room is empty - there should be no alarms

### How to reproduce it (minimal and precise)

standard installation

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20230507

### Adapter

zStack3x0

![image](https://github.com/Koenkk/zigbee2mqtt/assets/37274122/73ccfb0c-9d9b-4ab7-a0a5-42552302cfb7)

**Comment by paradohh** [comment]
I have the exact same problem. 2.9v battery, 95.5%. I replaced the battery with a new one and the false alarms disappeared.
