### ISSUE TITLE
Battery Level eCozy 1TST-EU

### ISSUE THREAD

**Issue by sti0** [Koenkk/zigbee2mqtt#1944]
# Bug Report
## What happened
I paired a eCozy 1TST-EU 4 days ago and it works as expected but I miss the battery level information. I only got the voltage. I'm using the HASSIO plugin and zigbee2mqtt published a battery sensor but the current level is missing. Does this device don't deliver battery level information?

This is the JSON payload that I get:
  zigbee2mqtt:info 9/9/2019, 2:45:36 PM MQTT publish: topic 'zigbee2mqtt/clim_buero', payload '{"voltage":0.29,"linkquality":89,"local_temperature":19.31,"occupied_heating_setpoint":8,"setpoint_change_amount":-8,"setpoint_change_source":2,"setpoint_change_source_timestamp":93125}'

## What did you expect to happen
Get the battery level in JSON payload like for example Xiaomi and Hue devices.

## How to reproduce it (minimal and precise)
Pair the device and wait for MQTT messages.

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version: 20190425
hassio plugin: 1.5.1.2

**Comment by Koenkk** [comment]
What type of battery does this device contain?

**Comment by sti0** [comment]
It contains 4 AA batteries.
https://en.wikipedia.org/wiki/AA_battery

**Comment by Koenkk** [comment]
Knowing that it has 4AA batteries, we need a function to convert the voltage to %, could you do some investigation on this?

**Comment by sti0** [comment]
Ok. Now I got it ;)

Actually I placed 4 new AA batteries and voltage shows 0.29.

I will do further investigation and come back to you.

**Comment by sti0** [comment]
I'm not using this device anymore. Battery consuming is way to much...
