### ISSUE TITLE
[New device support]: Profalux remote MAI-ZTS

### ISSUE THREAD

**Issue by Jeepmg** [Koenkk/zigbee2mqtt#19453]
### Link

https://www.profalux-pro.com/documentations/1.%20Notices,%20Plans,%20Technique/1.%20Volets%20roulants/3.%20Moteurs%20Commandes%20et%20Accessoires/1.%20Moteur/Moteur%20Profalux%20Zigbee/

### Database entry (first at pairing)

{"id":26,"type":"EndDevice","ieeeAddr":"0x20918a000015b57e","nwkAddr":51041,"manufId":4368,"manufName":"Profalux","powerSource":"Battery","modelId":"MAI-ZTS","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":513,"inClusterList":[0,3,21,64514,64544],"outClusterList":[3,4,5,6,8,256,64544,64545],"clusters":{"genBasic":{"attributes":{"modelId":"MAI-ZTS","manufacturerName":"Profalux","powerSource":3,"zclVersion":3,"appVersion":28,"hwVersion":26,"dateCode":"Oct 13 2021","swBuildId":"Release"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":515,"inClusterList":[0,1,3,9,21,32,64514,64544],"outClusterList":[3,4,5,25,258,64544,64545],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":1200}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c8216c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":28,"hwVersion":26,"dateCode":"Oct 13 2021","swBuildId":"Release","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1675699129256,"defaultSendRequestWhen":"fastpoll"}

### Comments

I m not abble to do an external converter.

the current database entry has changed : 

{"id":7,"type":"EndDevice","ieeeAddr":"0x20918a000015b57e","nwkAddr":51041,"manufId":4368,"powerSource":"Unknown","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":513,"inClusterList":[0,3,21],"outClusterList":[3,4,5,6,8,256,64544,64545],"clusters":{"genBasic":{"attributes":{"powerSource":0,"zclVersion":1,"dateCode":"20170309 NA 064"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"epId":2,"inClusterList":[],"outClusterList":[],"clusters":{"genPollCtrl":{"attributes":{"checkinInterval":1200}}},"binds":[],"configuredReportings":[],"meta":{}}},"dateCode":"20170309 NA 064","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1698469133901,"defaultSendRequestWhen":"immediate","checkinInterval":300}

Thank you for help

### External converter

```shell
{
        fingerprint: [{manufId: 4368, endpoints: [{ID: 1, profileID: 260, deviceID: 513, inputClusters: [0,3,21,64514,64544],
            outputClusters: [3, 4, 5, 6, 8, 256, 64544, 64545]}]}],
        model: 'MAI-ZTS',
        vendor: 'Profalux',
        description: 'Cover remote',
        fromZigbee: [],
        toZigbee: [],
        exposes: [],
    },
```

**Comment by Koenkk** [comment]
Added! Fix will be included in the 1 November release.
