### ISSUE TITLE
[New device support]: Add _TZE200_upagmta9 as another option for ZTH05

### ISSUE THREAD

**Issue by pdalak** [Koenkk/zigbee2mqtt#19455]
### Link

https://www.zigbee2mqtt.io/devices/ZTH05.html

### Database entry

{"id":14,"type":"EndDevice","ieeeAddr":"0xa4c138b7b7207213","nwkAddr":45294,"manufId":4417,"manufName":"_TZE200_upagmta9","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1698481250128,"defaultSendRequestWhen":"immediate"}

### Comments

My device is exactly the same as : https://www.zigbee2mqtt.io/devices/ZTH05.html but has different fingerprint TZE200_upagmta9, instead of TZE204_upagmta9 as you recognize it.

**Comment by Koenkk** [comment]
`TZE200_upagmta9` has already been added and will be supported in the 1 November release.
