### ISSUE TITLE
[New device support]: LYWSD03MMC using https://github.com/devbis/z03mmc

### ISSUE THREAD

**Issue by orrpan** [Koenkk/zigbee2mqtt#19477]
### Link

https://www.aliexpress.com/item/1005005916924715.html
### Database entry

{"id":22,"type":"EndDevice","ieeeAddr":"0xa4c138e7285c16e8","nwkAddr":44761,"manufId":4417,"manufName":"Xiaomi","powerSource":"Battery","modelId":"LYWSD03MMC","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,3,1,1029,1026],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":14,"dateCode":"20231027","swBuildId":"3001-1004","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1698601079407,"defaultSendRequestWhen":"immediate"}

### Comments

I don't have time to develop right now, but would be awesome if someone did!
https://github.com/devbis/z03mmc It converts it from a bluetooth to a zigbee

**Comment by Koenkk** [comment]
Already added and will be supported in the 1 November release.

**Comment by salopette** [comment]
Can you please include the 1.0.6 FW update in the database!?

https://github.com/devbis/z03mmc/releases/download/1.0.6/ATC_ota_40000.bin
