### ISSUE TITLE
Please help with adding support for icasa zigbee 3.0 switch ICZB-IW11SW

### ISSUE THREAD

**Issue by rutgerhendriks** [Koenkk/zigbee2mqtt#1947]
# Bug Report
## What happened
While trying to subscribe the icasa ICZB-IW11SW it shows the device is not supported. Some time later it crashes, but that seems to be the same issue as issue #1946 
I'm attaching the debug logging of the pairing attempt. I'm able to edit the devices.js so try to add support for the device, but I am at a loss as to what I need to do. If someone would assist that would be great!
## What did you expect to happen
Support should be added
## How to reproduce it (minimal and precise)
Press the 'reset' button on the ICZB-IW11SW 5 times in a row, then the device will try to repair resulting in the attached logging
[icasa switch subscribe crash.txt](https://github.com/Koenkk/zigbee2mqtt/files/3592197/icasa.switch.subscribe.crash.txt)

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version: 20190619

**Comment by james-fry** [comment]
Do you know what is the difference between the ICZB-IW11SW and the I[CZB-IW11D, which is supported](https://www.zigbee2mqtt.io/devices/ICZB-IW11D.html)?

In devices.js you could try to duplicate the entry for the ICZB-IW11D:

```
    {
        zigbeeModel: ['ICZB-IW11D'],
        model: 'ICZB-IW11D',
        vendor: 'iCasa',
        description: 'Zigbee 3.0 Dimmer',
        extend: generic.light_onoff_brightness,
    },
```

**Comment by rutgerhendriks** [comment]
added to const generic:

> 
    light_onoff: {
        supports: 'on/off',
        fromZigbee: [
            fz.ignore_light_brightness_change, fz.state_change, fz.state, fz.brightness_report,
        ].concat(defaultIgnoreConverters),
        toZigbee: [tz.on_off, tz.ignore_transition, tz.light_alert],
    },


added after ICZB-IW11D:
>
    {                                                               
        zigbeeModel: ['ICZB-IW11SW'],
        model: 'ICZB-IW11SW',
        vendor: 'iCasa',               
        description: 'Zigbee 3.0 Switch',
        extend: generic.light_onoff,                                                           
    },  


This results in the following debug logging:
>
  zigbee2mqtt:debug 9/9/2019, 10:42:46 PM Received MQTT message on 'zigbee2mqtt/bridge/config/log_level' with data 'Debug'
  zigbee2mqtt:info 9/9/2019, 10:42:46 PM Switching log level to 'debug'
  zigbee2mqtt:info 9/9/2019, 10:42:46 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"bd88016","coordinator":20190619,"log_level":"debug","permit_join":false}'
  zigbee2mqtt:debug 9/9/2019, 10:42:47 PM Received MQTT message on 'zigbee2mqtt/bridge/config/permit_join' with data 'true'
  zigbee2mqtt:info 9/9/2019, 10:42:47 PM Zigbee: allowing new devices to join.
  zigbee2mqtt:info 9/9/2019, 10:42:47 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"bd88016","coordinator":20190619,"log_level":"debug","permit_join":true}'
  zigbee2mqtt:debug 9/9/2019, 10:42:54 PM Received zigbee message of type 'devLeaving' with data '"0x14b457fffec4d994"' of endpoint undefined
  zigbee2mqtt:warn 9/9/2019, 10:42:54 PM Message without device!
  zigbee2mqtt:info 9/9/2019, 10:42:58 PM Successfully configured Woonkamer TV Nis links Hue motion (0x00178801032aba3e)
  zigbee2mqtt:debug 9/9/2019, 10:42:58 PM Configuring Trap Hue motion (0x00178801032ab91e) ...
  zigbee2mqtt:debug 9/9/2019, 10:43:00 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"manufacturerName":"icasa","modelId":"ICZB-IW11SW","powerSource":1}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:00 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r40"}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"manufacturerName":"icasa"}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"9":255,"modelId":"ICZB-IW11SW","dateCode":"NULL","powerSource":1,"appProfileVersion":255}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"10":{"type":"Buffer","data":[48,48]},"11":"NULL","16389":0,"30721":49246,"swBuildId":"2.5.3_r40"}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"30722":528,"30723":255,"30724":1,"34819":0,"34820":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"36864":255,"36865":1000,"36866":{"type":"Buffer","data":[92,147,221,104,137,42,50,65,181,244,163,66,198,67,238,2]},"36867":4644,"65533":1}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:01 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'readRsp' with data '{"cid":"genIdentify","data":{"65533":1,"identifyTime":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'readRsp' with data '{"cid":"genGroups","data":{"65533":1,"nameSupport":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'readRsp' with data '{"cid":"genScenes","data":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'readRsp' with data '{"cid":"genScenes","data":{"65533":1}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:02 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"16387":255,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:info 9/9/2019, 10:43:03 PM MQTT publish: topic 'zigbee2mqtt/0x14b457fffec4d994', payload '{"state":"ON","linkquality":39,"device":{"ieeeAddr":"0x14b457fffec4d994","friendlyName":"0x14b457fffec4d994","type":"Router","nwkAddr":33863,"manufId":4644,"manufName":"icasa","powerSource":"Mains (single phase)","modelId":"ICZB-IW11SW","hwVersion":"unknown","swBuildId":"2.5.3_r40","dateCode":"NULL","status":"online"}}'
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"65533":1}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'readRsp' with data '{"cid":"haDiagnostic","data":{"65533":1,"numberOfResets":0,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":0,"lastMessageRssi":0}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:03 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
  zigbee2mqtt:debug 9/9/2019, 10:43:04 PM Received zigbee message of type 'readRsp' with data '{"cid":"lightLink","data":{"65533":1}}' of device 'ICZB-IW11SW' (0x14b457fffec4d994) of endpoint 1
  zigbee2mqtt:debug 9/9/2019, 10:43:04 PM Received zigbee message of type 'devInterview' with data '"0x14b457fffec4d994"'
/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:49
        throw new Error(`Cluster with key '${key}' does not exist`);
        ^

Error: Cluster with key '33' does not exist
    at Object.getCluster (/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:49:15)
    at Object.getAttributeLegacy (/app/node_modules/zigbee-herdsman/dist/zcl/index.js:39:27)
    at /app/node_modules/zigbee-herdsman/dist/lib/shepherd.js:145:36
    at Object._.forEach (/app/node_modules/zigbee-herdsman/node_modules/busyman/index.js:411:27)
    at ZShepherd.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/shepherd.js:144:11)
    at ZShepherd.emit (events.js:182:13)
    at dispatchIncomingMsg (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:565:41)
    at Controller.zclIncomingMsgHandler (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:631:12)
    at Controller.emit (events.js:182:13)
    at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:640:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-09T20_43_04_444Z-debug.log

**Comment by james-fry** [comment]
It got you a bit further :) 
Im sorry but the error is outside my limited expertise and seems to be same issue as you got with the dimmer version in the other issue you posted - https://github.com/Koenkk/zigbee2mqtt/issues/1946

Since the dimmer is supported my guess is that this is a bug from the change to zigbee-herdsman

**Comment by rutgerhendriks** [comment]
Support is added to latest-dev
