### ISSUE TITLE
IKEA E1524/E1810 missing exposes

### ISSUE THREAD

**Issue by tobiasbrage** [Koenkk/zigbee2mqtt#19487]
### What happened?

I'm missing quite a lot of exposes from this remote.

The page on the zigbee2mqtt website states the following:

Action (enum)
Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: arrow_left_click, arrow_left_hold, arrow_left_release, arrow_right_click, arrow_right_hold, arrow_right_release, brightness_down_click, brightness_down_hold, brightness_down_release, brightness_up_click, brightness_up_hold, brightness_up_release, toggle.

I'm not seeing any exposes from either brightness_up og arrow_left.

### What did you expect to happen?

I expected all exposes to be present.

The remote is updated to the latest firmware 24.4.5, as far as I can tell at least.

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20231005.0

### Adapter

Home Assistant SkyConnect

**Comment by larstobi** [comment]
Not stale.

**Comment by dokatomi** [comment]
The arrow_left_hold and arrow_right_hold not working in the 1.37.0-1 version. The previous HA addon version 1.36.1-1 has no issue with this remote.

**Comment by rdbraber** [comment]
Having the same issue after upgrading to 1.37.0. 1.36.0 works fine.

**Comment by der-gordon** [comment]
> The arrow_left_hold and arrow_right_hold not working in the 1.37.0-1 version. The previous HA addon version 1.36.1-1 has no issue with this remote. Others for example brightness_up_hold and brightness_down_hold working for me.

Having exactly the same problem. Does anyone have suggestions?

**Comment by dokatomi** [comment]
Currently I downgraded to the previous version.

**Comment by doctordarko** [comment]
> The arrow_left_hold and arrow_right_hold not working in the 1.37

I have tried just about every combo of device reconfigure, remove device, factory reset, battery out, z2m restart to no avail. Everything but left/right hold works.

**Comment by Xploder** [comment]
Can confirm on my E1810. Since 1.37 left/right hold doesn't work anymore.

**Comment by Koenkk** [comment]
Could you provide the debug log when triggering the left/right hold action?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by Xploder** [comment]
Hey Koenkk, sure thing.

This is with Right Arrow held:
https://pastebin.com/AwuBuWKc

Thank you.

**Comment by Koenkk** [comment]
Does it work after setting `legacy: false` for this device? ([docs](https://www.zigbee2mqtt.io/devices/E1524_E1810.html#options))

**Comment by Xploder** [comment]
This is with `legacy: false`.
`legacy: true` also does not work.

**Comment by Koenkk** [comment]
Pushed a fix, let me know if it works!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by doctordarko** [comment]
> let me know if it works!

Left/right hold actions work on E1810 with 1.37.0-dev commit: [358e2ee]

**Comment by rdbraber** [comment]
I can also confirm the fix works.

**Comment by Koenkk** [comment]
Awesome!
