### ISSUE TITLE
new module switch entity not exposed in HA

### ISSUE THREAD

**Issue by adizag** [Koenkk/zigbee2mqtt#19496]
### What happened?

New switch added to Z2M (Entrance hall outside (0xa4c138b8e75f17ab))  and working fine from Z2M dashboard:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/17390016/4286b7e9-e65d-43b5-a6db-120ff00f0995)

In HA, only 2 entities are exposed, without any switch:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/17390016/8436ab5d-b8ae-42b4-80fc-b34035d16490)

### What did you expect to happen?

show all entities including switches

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-P( zStack3x0)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13214570/log.txt)

**Comment by Mallinanga** [comment]
Same here

**Comment by adizag** [comment]
Please reopen
