### ISSUE TITLE
TRADFRI bulb E27 W opal 1000lm

### ISSUE THREAD

**Issue by jonydebu** [Koenkk/zigbee2mqtt#195]
Hi , cc2531 seems works well , but cant find the Ikea tradfri bulb . Dont think it´s a distance pairing (is a 5cms) . In HA just configure discovery : true 
![image](https://user-images.githubusercontent.com/30730098/42723541-f9481fd2-875f-11e8-9d68-3b75df633f0a.png)
Apreciate any help , thanks .

**Comment by Koenkk** [comment]
So which firmware did you flash? (asking because of #193)

**Comment by jonydebu** [comment]
![image](https://user-images.githubusercontent.com/30730098/42727020-c030be04-879e-11e8-8377-38de49c00d54.png)
This One .

**Comment by Koenkk** [comment]
Can you try running with `DEBUG=* npm start`

**Comment by jonydebu** [comment]
Hi Koenkk ,Hi, I've tried it but nothing's happening yet. Is there any way to check if the zigbee2mqtt CC2531 coordinator is working?

**Comment by Koenkk** [comment]
Can you pair other devices?

**Comment by jonydebu** [comment]
Hi , i buy another Ikea Tradfri model(LED1650R5) and it pairing well . 
the problem seems to be in the bulb that for some reason according to this:           
( https://github.com/athombv/com.ikea.tradfri/issues/4  ) , need a dimmer .

**Comment by jonydebu** [comment]
Finally I´ve got it . Just running ```DEBUG=*npm start``` and the bulb goes on . Perfect , close this isue . 
Thanks all.
