### ISSUE TITLE
Bticino K4027C cover position not working

### ISSUE THREAD

**Issue by syntesys87** [Koenkk/zigbee2mqtt#19509]
### What happened?

I added to Zigbee2Mqtt my 6 covers Bticino K4027C; the problem is that the setting of cover position does not work; works only 0-100 for open or close.

This is the status JSON:
{
    "linkquality": 128,
    "position": 100,
    "state": "CLOSE",
    "tilt": 0,
    "update": {
        "installed_version": 3556351,
        "latest_version": 3556351,
        "state": "idle"
    },
    "action": null,
    "led_in_dark": null,
    "update_available": null
}

And I have not activated "No position support" because in this JSON I see that I have the latest version.

### What did you expect to happen?

The cover sets the right position.

### How to reproduce it (minimal and precise)

Add a new BTicino device and try to set the position.

### Zigbee2MQTT version

1.33.1-1

### Adapter firmware version

7.3.1.0 build 176

### Adapter

EZSP v12 SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by syntesys87** [comment]
Also, I found that in the new release of ZigBee2MQTT there is this commit: [https://github.com/Koenkk/zigbee-herdsman-converters/pull/6333](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6333)... Could this be ported also for Bticino K4027C?

Thank you.

**Comment by syntesys87** [comment]
@FabianMangold I opened yesterday this issue after seeing your [pull request](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6333) and I would integrate it into K4027C, because the cover position and the calibration is not working (I don't know il tilt works, I have covers without tilt)... How did you approach the debug of NLLV firmware and the tries you did for make this working? I would debug how it works in the app and replicate it in Zigbee2MQTT.

I see from logs of Netatmo plugin in Home Assistant this: 2023-11-03 11:47:33.293 DEBUG (MainThread) [pyatmo.home] Setting state for home (62134d6bd95995623b03a8ba) according to {'modules': [{'id': '---', 'target_position': 49, 'bridge': ---'}]} (I removed MAC addresses from component and bridge).

**Comment by syntesys87** [comment]
Thank you for the support! 
I'm using 1.33.2 with HomeAssistant 2023.11.0, last version of everything. Everything is connected to ITEAD Sonoff ZBDongle-E (ZigBee 3.0 USB Dongle Plus v2) with last firmware.
The device is recognized (after last update of Z2M) as 067776A. 
The device works only on up-down-stop, automatic calibration in classic_nllv is not working, works on specific_nllv (but useless, because the position after calibration doesn't work), not working in manual with temporal and venetian.

**Comment by FabianMangold** [comment]
My pleasure, thanks for the update. It makes more sense now.
I've updated the [comment](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6333#issuecomment-1790548665) regarding the calibration modes in the PR#6333.
Basically, classic_nllv seems to be identical to up_down_stop, no calibration required. specific_nllv is the mode that features the automatic calibration.
You may need to calibrate the blind several time before achieving good results, but i found the temporal mode to be more precise as well!
Z2M doesn't do anything here, it merely sets the switch in the right mode, the "rest" is done by the switch firmware itself. We can only hope that newer firmware versions may improve those calibration methods.
When you say the manual temporal / venetian calibration does not work, do you mean the "calibration procedure" or the results afterwards ?

**Comment by syntesys87** [comment]
I mean the calibration procedure, I tested temporal yesterday, following this:
"Once the blind is in the up position, start the calibration by pressing and holding the down button, until the blind reaches to bottom stop. Once there, the relay should click. "
At the end, the relay does not click.

**Comment by FabianMangold** [comment]
Okay, that might be somewhat different on the Bticino. Just skip that part, and continue.
Do you have an original gateway and the corresponding app ? If so, you could try to calibrate the device using those "tools" and update our procedures.
Again, those procedures were determined OK for the Legrand 067776 / 067776A "only".

**Comment by syntesys87** [comment]
It seems that when I press the reset button for run the association, it loses the calibration; I already tested readding to original gateway, calibrating and readding to zigbee2mqtt, but this does not work.

**Comment by FabianMangold** [comment]
The calibration is "stored" in the switch, and re-associating indeed seems to clear those values.
Nevertheless, can you try the "same calibration" procedure once the device is associate to Z2M ?
Is the procedure any different from the one that we had described in the PR ticket ?

**Comment by syntesys87** [comment]
The procedure is the same, on original app it runs an automatic calibration and then it works. With Z2M I set the shutter in specific_nllv mode and it runs automatic calibration... The procedure seems the same! 
In the process there are two things different: the red led does not turn off after the association with Z2M and if I hold up+down button for ten seconds, it doesn't run automatic calibration

**Comment by FabianMangold** [comment]
I was actually tallking about the manual calibration process, not the automatic one.
"What" does work when your use the original app ? The position report ?

Regarding the LED, there is another thread / user reporting the same issue, which i cannot reproduce on my own devices. (See https://github.com/Koenkk/zigbee2mqtt/issues/19108#).
Why would you press Up+Down? Switching modes via Z2M is sufficient to bring the switch into the calibration mode, there is no need for physically pressing the buttons.

**Comment by syntesys87** [comment]
Yes, but tried also original method for seeing the result.
Regarding manual mode, from BTicino it works in this mode: press down button until it closes, press up button until it opens, press down button until the blind touches the window surface, press up button to reopen... But setting temporal mode, after I press the up button, it exit from calibration procedure.

**Comment by FabianMangold** [comment]
OK for the calibration, to be investigated.
> Yes, but tried also original method for seeing the result. 
What does "Yes" refer to?
- Does the position report work after the automatic calibration ? Does it as reliably in Z2M as it does in the original app
- Just to confirm: Tilt doesn't work in that mode right ? Neither in Z2M nor with the original GW

**Comment by syntesys87** [comment]
Yes was an ok for the up+down press for calibration 😁
After automatic calibration, it continues to report 0-100-50 (open, close, other positions), not, for example, 27 or 69.
I don't have blinds with tilt, only up-down.

**Comment by FabianMangold** [comment]
Sorry for the stupid questions, just making sure we are talking about the same things.

Okay, that is really odd, the automatic calibration or temporal mode should actually enable proper position reporting.
Is this also the case with the original GW or only Z2M ?

**Comment by syntesys87** [comment]
With Z2M seems that is not working, with original GW everything works as expeced; also, the position reporting works well with the original Netatmo integration in Home Assistant.

**Comment by FabianMangold** [comment]
Can you provide you database.db here please ?

**Comment by syntesys87** [comment]
No problem, do you need it with a shutter configured? Because, at the moment, they are all connected with original GW.

**Comment by FabianMangold** [comment]
Yes please, whenever you have time, no hurry.

**Comment by syntesys87** [comment]
[database.db.zip](https://github.com/Koenkk/zigbee2mqtt/files/13253062/database.db.zip)

Here attached the file. Now i try temporal mode :)

**Comment by syntesys87** [comment]
[This](https://photos.app.goo.gl/yzbzXbHR5bT6va9YA) is the link of the temporal try. When it starts, it goes on red led and then the switch sets into up_down_stop.

**Comment by FabianMangold** [comment]
Can you please leave the system running for a while and re-upload the database.db ? Unfortunately it doesn't contain yet any attributes, which makes it kind of worthless for now.
Thanks a lot.

**Comment by FabianMangold** [comment]
Thanks for the video, that helps :)
Can you switch it to temporal, and really wait for the blind to go to the upper stop. Once it is there, give it a couple of seconds, and then press the switch. Just don't touch the switch until the blind is in a steady position.

**Comment by syntesys87** [comment]
Yes, no problem, I will send the new file tomorrow, so that attributes could be populated.
In the video, I start from the upper position, but when I click the down button, happens red led and exit from calibration.

**Comment by philippk75** [comment]
hello, with my bticino N4027C the poistion control works, i calibrated it with specific calibration automatic mode, also different percentsges of positions work.

**Comment by syntesys87** [comment]
[database.db.zip](https://github.com/Koenkk/zigbee2mqtt/files/13255997/database.db.zip)
Here attached new database.db. 
@philippk75 what firmware are you running in your N4027C?

**Comment by philippk75** [comment]
> [database.db.zip](https://github.com/Koenkk/zigbee2mqtt/files/13255997/database.db.zip) Here attached new database.db. @philippk75 what firmware are you running in your N4027C?

Firmware-Date
20230406
Firmware-Version
0036

**Comment by syntesys87** [comment]
The version is the same, mine switches has also 0036 firmware. Do you have blinds with tilt or lift only? Could the problem be related to that?

**Comment by philippk75** [comment]
> The version is the same, mine switches has also 0036 firmware. Do you have blinds with tilt or lift only? Could the problem be related to that?

i have both, tilt and non tilt

**Comment by FabianMangold** [comment]
Hi @philippk75 and @syntesys87,

@philippk75:
I've just submitted [PR#6405](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6405) to fix the device detection. Once merged, your switches will be reported as BTicino devices again, still keeping the new feature set.
Please let me know if this worked and if that's okay.

@syntesys87:
Thanks for sharing your database.db, this helped to confirm the HW ID of Bticino switches.
Also, the database shows that your switch is calibrated in NLLV_classic, meaning Up/Down/Stop, which doesn't report any position.
Could you please retry the automatic calibration (NLLV_Specific), and make sure that the "No Position Reporting" option located in the "Settings (Specific)" tabsheet is set to OFF ?

Thanks
Th

**Comment by philippk75** [comment]
> Hi @philippk75 and @syntesys87,
> 
> @philippk75: I've just submitted [PR#6405](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6405) to fix the device detection. Once merged, your switches will be reported as BTicino devices again, still keeping the new feature set. Please let me know if this worked and if that's okay.
> 
> @syntesys87: Thanks for sharing your database.db, this helped to confirm the HW ID of Bticino switches. Also, the database shows that your switch is calibrated in NLLV_classic, meaning Up/Down/Stop, which doesn't report any position. Could you please retry the automatic calibration (NLLV_Specific), and make sure that the "No Position Reporting" option located in the "Settings (Specific)" tabsheet is set to False ?
> 
> Thanks

hello, thanks, this means that we have to wait the next zibee2mqtt update? or can we start somethings manuel?

**Comment by syntesys87** [comment]
Hello all and thanks for the support! 
@FabianMangold no problem for trying, it's very strange that in the frontend I see that calibration mode is set to specific_nllv and in the database is set to classic_nllv... Are you looking to the switch with friendly name 0x0004740000cb2a3b, right?
How can I install last update? Is there a guide to follow for test latest PR?

Thank you!

**Comment by FabianMangold** [comment]
Hello both,
The fix has just been merged, so it should be available in the DEV branch shortly.

Regarding the usage of the DEV branch, you may want to checkout this page and follow the instructions depending on the way you are using Z2M:
https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

And lastly, yes @syntesys87, i was looking at exactly this switch, the entry having ID:7. If you check the reporings in the "closuresWindowCovering" cluster, you will see the calibrationMode and tuyaMotorReversal attributes reading 1, which is classic_nllv. I am quite sure that refreshing the value from the frontend (use the little refresh icon next to the calibration mode drop down) should update the value.
Let me know.

**Comment by syntesys87** [comment]
It's very strange, with the stable branch I can't find the calibrationMode attribute but only tuyaMotorReversal... Also, if I refresh the value on frontend, I can see "specific_nllv". These are the screens:
![Screenshot_20231106_074836](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/cb7be101-42ce-4852-a2f8-48d5ede78881)
![Screenshot_20231106_075602](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/20273654-f022-4090-81a4-b85f3602abe5)
![Screenshot_20231106_075629](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/370630db-b50d-4a1b-a2d4-2d80d88d128b)

Today I'll try dev branch.

**Comment by FabianMangold** [comment]
Hi @syntesys87,
OK, now i understand the issue. You have to use the DEV branch, otherwise the attribute names are not mapped correctly. This is due to the fact, the calibrationMode is a Legrand specific attribute. This was fixed in Zigbee-Herdsman [PR#787](https://github.com/Koenkk/zigbee-herdsman/pull/787), which is not yet available in the stable branch.
Please use the DEV branch until the next stable (next month), so that we are all on the same page and working from the same code base.
Let us know the outcome and have a nice day

**Comment by philippk75** [comment]
> Hi @syntesys87, OK, now i understand the issue. You have to use the DEV branch, otherwise the attribute names are not mapped correctly. This is due to the fact, the calibrationMode is a Legrand specific attribute. This was fixed in Zigbee-Herdsman [PR#787](https://github.com/Koenkk/zigbee-herdsman/pull/787), which is not yet available in the stable branch. Please use the DEV branch until the next stable (next month), so that we are all on the same page and working from the same code base. Let us know the outcome and have a nice day

to swicth to the DEV version in home assiatnt do i have do deinstall the stable version and install the dev version? do i have to make some backups?

**Comment by syntesys87** [comment]
Hello @philippk75, standing to the guide, install ZigBee2Mqtt edge from repositories if you have HAOS installation, copy the addon configuration, stop the stable addon and run edge addon.

**Comment by syntesys87** [comment]
@FabianMangold resolved for one of 6 covers! ID 7 is now working well, position works!

![Screenshot_20231106_084824](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/e6587a37-e6a9-4fba-84cf-440d6ef331c9)

Is there a strange behavior on model of the newly added covers: they are recognized as Legrand instead BTicino... I'll send a new database.db in a couple of hours, waiting for values to populate.

![Screenshot_20231106_084858](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/aa146bc7-373d-4e5d-b027-766c8cc0e42c)

FYI: ID 7 had an old firmware that I updated some minutes before I opened this issue, the other 5 had latest firmware installed before I configured all Zigbee2Mqtt instance.

**Comment by FabianMangold** [comment]
Hi
I‘ve submitted a patch for that yesterday evening. Not sure if your Edge plugin is already up to date. Can you check if you are running the zigbee-herdsman-converters 15.18.0 ?
All devices with HW Version 13 should be reported as BTicino devices now.

On 6 Nov 2023, at 08:49, syntesys87 ***@***.***> wrote:

﻿


@FabianMangold resolved for one of 6 covers! ID 7 is now working well, position works!


Is there a strange behavior on model of the newly added covers: they are recognized as Legrand instead BTicino... I'll send a new database.db in a couple of hours, waiting for values to populate.


FYI: ID 7 had an old firmware that I updated some minutes before I opened this issue, the other 5 had latest firmware installed before I configured all Zigbee2Mqtt instance.

**Comment by syntesys87** [comment]
![Untitled](https://github.com/Koenkk/zigbee2mqtt/assets/43778406/572c7b1a-9bd7-4dbb-b32e-20444a906788)

**Comment by philippk75** [comment]
> @FabianMangold installed edge addon, the problem is resolved for one of 6 covers! ID 7 is now working well, including led change and position!
> 
> ![Screenshot_20231106_084824](https://user-images.githubusercontent.com/43778406/280629025-e6587a37-e6a9-4fba-84cf-440d6ef331c9.png)
> 
> Is there a strange behavior on newly added covers: they are recognized as Legrand instead BTicino... I'll send a new database.db in a couple of hours, waiting for values to populate.
> 
> ![Screenshot_20231106_084858](https://user-images.githubusercontent.com/43778406/280629102-aa146bc7-373d-4e5d-b027-766c8cc0e42c.png)
> 
> FYI: ID 7 had an old firmware that I updated some minutes before I opened this issue, the other 5 had latest firmware installed before I configured all Zigbee2Mqtt instance.

hello, 

for me now it's OK

![image](https://github.com/Koenkk/zigbee2mqtt/assets/107313024/e5e78f05-06fb-4f06-9214-73fbe266f800)

the tilt calibration now is OK or do we have to wait for further developments?

I notice that also standard rollo shutter without venetians have the tilt option which makes less sense? o can i set it as rolloshutter without tilt and this options doesn't appear?

Best regards

Philipp

**Comment by dadino** [comment]
I'm still on the stable channel, as I just read this thread. This morning I tried to calibrate with "temporal" on my BTicino K4027C, I followed the steps by @FabianMangold and left the house while the switch was still in the orange LED step (calibrating). I'm checking it now and the "calibration_mode" field is null, with no position reported (well, it reports 50, which is not correct).

```
{
    "last_seen": "2023-11-06T09:06:47.442Z",
    "led_in_dark": "ON",
    "linkquality": 0,
    "position": 50,
    "state": "OPEN",
    "tilt": 100,
    "update": {
        "installed_version": 3556351,
        "latest_version": 3556351,
        "state": "idle"
    },
    "action": null,
    "calibration_mode": null,
    "update_available": null
}
```

I guess I'll have to wait for the fixes to get to the stable channel and try again, when the switch is correctly recognized as a BTicino cover switch.

**Comment by syntesys87** [comment]
[database.db.zip](https://github.com/Koenkk/zigbee2mqtt/files/13265061/database.db.zip)

@FabianMangold updated database.db with all the other 5 covers recognized as legrand instead bticino.

**Comment by FabianMangold** [comment]
Good evening @philippk75,
Glad to see that the devices are reported correctly again.
I don't understand your question. There is no further development regarding tilt, as already mentioned previously, all Z2M does is tell the switch how to behave (which mode it should run in), and that's basically it.
Is there anything else you are missing, or is it all OK for you now ?

Regarding the "tilt" angle, you've mentioned this before. I am trying to figure out how to do this best, because we are all affected by this "issue". That's just the way Z2M works, and any improvement on that front is a "nice to have". Would you mind opening another "issue" for this, and pin me in there ? I would like to avoid mixing up topics in issues, it's getting complicated to adress everyone's issue in a single thread.
Thanks a lot

**Comment by FabianMangold** [comment]
Hi @syntesys87,
Thanks again for provide the database.db. Looking at it closely, it looks like you have other shutter switch having hardware ID 9. I'll submit a fix shortly, to have this corrected as well.
I am not sure that using the Hardware ID is the way to go really, but only "Legrand" could tell us how to properly differentiate BTicino switches from Legrand switches. It's the only difference i can spot really :/

Please always use the DEV branch when experimenting with new features, otherwise we may spend a lot of time tracking down issues that may already have been fixed. You will indeed need the DEV branch to have the attributes reported correctly (i.e. using the correct name). In our case, calibrationMode is equivalent to tuyaMotorReversal.

Please switch to DEV and let me know the outcome.
In case you are eager to test it, you can probably patch your local legrand.ts (or js) and replace the current fingerprint line in the 067776A device definition with the following:

```
        whiteLabel: [
            {
                model: 'K4027C/L4027C/N4027C/NT4027C', vendor: 'BTicino', description: 'Shutter SW with level control',
                fingerprint: [{hardwareVersion: 9}, {hardwareVersion: 13}],
            },
        ],
```
Happy testing!

**Comment by FabianMangold** [comment]
Hi @dadino,

From your status, the calibrationMode hasn't been set correctly (it's reporting NULL).
Could you please switch to the DEV branch and give it a try ? This is likely due to the fact the attribute names do not get mapped correctly, which has been fixed (or rather improved) in the DEV branch a couple of days ago.
Let me know how that goes.

**Comment by philippk75** [comment]
> Good evening @philippk75, Glad to see that the devices are reported correctly again. I don't understand your question. There is no further development regarding tilt, as already mentioned previously, all Z2M does is tell the switch how to behave (which mode it should run in), and that's basically it. Is there anything else you are missing, or is it all OK for you now ?
> 
> Regarding the "tilt" angle being displayed in all modes, this is somewhat annoying indeed, I agree. You've mentioned this before, and I am trying to figure out how to do this best, because we are all affected by this "issue". That's just the way Z2M works, and any improvement on that front is a "nice to have". Would you mind opening another "issue" for this, and pin me in there?
> 
> I would like to avoid mixing up topics in issues, it's getting complicated to adress everyone's issues in a single thread. Thanks a lot

Hello,

thanks for your effort. maybe you can control the hiding of the options for the inclination of the blinds by taking into account the type in the device itself? Hide for roller shutters, show for Venetian blinds?

Thanks

![image](https://github.com/Koenkk/zigbee2mqtt/assets/107313024/454994c4-27cb-4c48-b0a1-f3fb151539e6)

**Comment by syntesys87** [comment]
> Hi @syntesys87, Thanks again for provide the database.db. Looking at it closely, it looks like you have other shutter switch having hardware ID 9. I'll submit a fix shortly, to have this corrected as well. I am not sure that using the Hardware ID is the way to go really, but only "Legrand" could tell us how to properly differentiate BTicino switches from Legrand switches. It's the only difference i can spot really :/
> 
> Please always use the DEV branch when experimenting with new features, otherwise we may spend a lot of time tracking down issues that may already have been fixed. You will indeed need the DEV branch to have the attributes reported correctly (i.e. using the correct name). In our case, calibrationMode is equivalent to tuyaMotorReversal.
> 
> Please switch to DEV and let me know the outcome. In case you are eager to test it, you can probably patch your local legrand.ts (or js) and replace the current fingerprint line in the 067776A device definition with the following:
> 
> ```
>         whiteLabel: [
>             {
>                 model: 'K4027C/L4027C/N4027C/NT4027C', vendor: 'BTicino', description: 'Shutter SW with level control',
>                 fingerprint: [{hardwareVersion: 9}, {hardwareVersion: 13}],
>             },
>         ],
> ```
> 
> Happy testing!
> 
> Edit: [PR#6423](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6423) for the fix

Thank you for the fix! I'll wait the merge with next release, no problem.

**Comment by FabianMangold** [comment]
HI @syntesys87,
The fix has been merged, let me know if that fixes the remaining issues!
Thanks a lot

**Comment by syntesys87** [comment]
Hi @FabianMangold, all fixed, now I see the new hardware as BTicino instead Legrand!
Last question, do you know if there are open bugs regarding the led that remains green blinking after pairing?

This bug could be closed.

**Comment by philippk75** [comment]
@FabianMangold i opendes this post: https://github.com/Koenkk/zigbee2mqtt/issues/19621

**Comment by syntesys87** [comment]
@FabianMangold yes, this issue could be closed! 
I have not reproduced led problem on my hardware 13 switch, but in all the other hardware 9 switches.
Thank you for the support, you are great!

**Comment by FabianMangold** [comment]
My pleasure @syntesys87, happy to help if i can.
It's odd, if seems that the issue is somehow linked to the hardware ID. Users in the thread i mentioned above report exactly this issue. It might be worth reaching out to Legrand via their forum and ask for some guidance there.
Can you please mark this issue as solved, since you are the one that has opened it ?
Cheers

**Comment by syntesys87** [comment]
@FabianMangold yes, it's very strange... As it's strange that there are multiple hardware IDs for the same component... There isn't any parameter or code that is useful to identify che switch. Here https://github.com/Koenkk/zigbee2mqtt/issues/16948#issuecomment-1680592070 you can find the procedure to workaround the blinking green led problem.

Thank you for your effort!

**Comment by r0bb10** [comment]
I finally managed to get my 7x K4027C working (firmware 36) using the method posted [here](https://github.com/Koenkk/zigbee2mqtt/issues/16948#issuecomment-1680592070) and get rid of the stupid K4510C Gateway.

It was really a pain to fix the green flashing light because in this mode it's not fully paired and the calibration procedure cannot be started.. the first 2 K4027C paired fine but the others was fail&repeat a lot.. eventually fixed and got the purple light on all of them (fully paired) and then the calibration procedure can be started (up+down button for 5 sec).

**Comment by r0bb10** [comment]
> > I finally managed to get my 7x K4027C working (firmware 36) using the method posted [here](https://github.com/Koenkk/zigbee2mqtt/issues/16948#issuecomment-1680592070) and get rid of the stupid K4510C Gateway.
> 
> @r0bb10 How did you update the bTicino devices? I keep getting the error `Device didn't respond to OTA request` I was able to update a couple of K4027C and those I was able to fully pair, but I can't fully pair the other with older firmware.

i have a K4510C gateway and use it only to update the devices, never managed to ota update from z2m or zha.

**Comment by andreapx** [comment]
> i have a K4510C gateway and use it only to update the devices, never managed to ota update from z2m or zha.

You've never tried with Z2M or you've tried and failed?

**Comment by r0bb10** [comment]
> > i have a K4510C gateway and use it only to update the devices, never managed to ota update from z2m or zha.
> 
> You've never tried with Z2M or you've tried and failed?

never tried.

**Comment by andreapx** [comment]
To Update the devices with the gateway you have to pair them all to it and then pair them back to Z2M?

**Comment by r0bb10** [comment]
> To update the devices with the gateway do you have to pair them all to it and then pair them back to Z2M?

exactly, i had everything paired with the bticino gateway, some with new firmware some with older one, i left them all connected and they slowly updated to the latest available and then moved them to z2m (and then to zha).

**Comment by andreapx** [comment]
> exactly, i had everything paired with the bticino gateway, some with new firmware some with older one, i left them all connected and they slowly updated to the latest available and then moved them to z2m (and then to zha).

Damn! I have about 70 devices, it's unthinkable!
Thanks for the feedback!

**Comment by andreapx** [comment]
> > To update the devices with the gateway do you have to pair them all to it and then pair them back to Z2M?
> 
> exactly, i had everything paired with the bticino gateway, some with new firmware some with older one, i left them all connected and they slowly updated to the latest available and then moved them to z2m (and then to zha).

@r0bb10 How did you update the firmware with the bTicino gateway? I've paired some roller shutter, I see that they have different firmware, but I can't find anywhere the option to update the firmware.

**Comment by r0bb10** [comment]
> > > To update the devices with the gateway do you have to pair them all to it and then pair them back to Z2M?
> > 
> > 
> > exactly, i had everything paired with the bticino gateway, some with new firmware some with older one, i left them all connected and they slowly updated to the latest available and then moved them to z2m (and then to zha).
> 
> @r0bb10 How did you update the firmware with the bTicino gateway? I've paired some roller shutter, I see that they have different firmware, but I can't find anywhere the option to update the firmware.

as far as i know you cannot force the update, it's the gateway that handles the update for downstream devices periodically, once paired let them sit and they will update themselves over a period of time.

i know it's annoying but everything bticino (or legrand) does is annoying.

**Comment by andreapx** [comment]
> > > > To update the devices with the gateway do you have to pair them all to it and then pair them back to Z2M?
> > > 
> > > 
> > > exactly, i had everything paired with the bticino gateway, some with new firmware some with older one, i left them all connected and they slowly updated to the latest available and then moved them to z2m (and then to zha).
> > 
> > 
> > @r0bb10 How did you update the firmware with the bTicino gateway? I've paired some roller shutter, I see that they have different firmware, but I can't find anywhere the option to update the firmware.
> 
> as far as i know you cannot force the update, it's the gateway that handles the update for downstream devices periodically, once paired let them sit and they will update themselves over a period of time.
> 
> i know it's annoying but everything bticino (or legrand) does is annoying.

Damn, really? They are VERY annoying!
I hoped that I could pair 2/3 at a time, update them and then pair them back to Z2M, but it seems that it will take a long while if I can't force the updates.
Thanks for the info!

**Comment by andreapx** [comment]
@r0bb10 Do you remember about how long did they take to update? For me it's been a week but none of the 3 got updated.

**Comment by r0bb10** [comment]
> @r0bb10 Do you remember about how long did they take to update? For me it's been a week but none of the 3 got updated.

it's variable, some of the K4411C and K4027C i have got updated almost immediatelly, other K4027C and some K4531C where so slow i dont even remember how much it took, but long.

bticino always amazing.

**Comment by r0bb10** [comment]
@andreapx did you manage to update and pair them correctly? does everything work?

**Comment by andreapx** [comment]
@r0bb10 no, unfortunately they are not updating

**Comment by philippk75** [comment]
i also have problems with updating, some work, other don‘t work

**Comment by syntesys87** [comment]
I opened the issue #20221 3 weeks ago, indicating logs and problem.

**Comment by r0bb10** [comment]
> @r0bb10 no, unfortunately they are not updating

@andreapx so i finally moved away from zha and switched the whole zigbee network to z2m, works way way better (binding and positions).. after the migration i tested the ota function in z2m and all bticino devices had an update that worked pretty much immediately.

k4027c + k4027cwi + k4531c + k4003c and even fc80gcs were updated ota.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16479888/9643f19e-c4fc-49b9-8ef4-bb3045c0bf9a)

**Comment by andreapx** [comment]
> > @r0bb10 no, unfortunately they are not updating
> 
> @andreapx so i finally moved away from zha and switched the whole zigbee network to z2m, works way way better (binding and positions).. after the migration i tested the ota function in z2m and all bticino devices had an update that worked pretty much immediately.
> 
> k4027c + k4027cwi + k4531c + k4003c and even fc80gcs were updated ota.
> 

Damn! Mine still don't want to update, I still get `failed (OTA: Device didn't respond to OTA request)`.
Do you remember the version before the OTA? Mine are: 

- 001c
- 002c
- 003c
- 003e
- 0036

Thanks!

**Comment by dadino** [comment]
> > > @r0bb10 no, unfortunately they are not updating
> > 
> > 
> > @andreapx so i finally moved away from zha and switched the whole zigbee network to z2m, works way way better (binding and positions).. after the migration i tested the ota function in z2m and all bticino devices had an update that worked pretty much immediately.
> > k4027c + k4027cwi + k4531c + k4003c and even fc80gcs were updated ota.
> 
> Damn! Mine still don't want to update, I still get `failed (OTA: Device didn't respond to OTA request)`. Do you remember the version before the OTA? Mine are:
> 
> * 001c
> * 002c
> * 003c
> * 003e
> * 0036
> 
> Thanks!

I've got a [K4003C/L4003C/N4003C/NT4003C] at firmware version 001c that doesn't want to update. I had to update all the others via the BTicino hub, it took 4 days.

**Comment by andreapx** [comment]
Let's hope that the problem is the old firmware.
Do you get a correct position ant tilt?

**Comment by dadino** [comment]
> Let's hope that the problem is the old firmware. Do you get a correct position ant tilt?

No not at all, I've tried even with the original hub. I think there is a problem with the motor.

**Comment by r0bb10** [comment]
> > > @r0bb10 no, unfortunately they are not updating
> > 
> > 
> > @andreapx so i finally moved away from zha and switched the whole zigbee network to z2m, works way way better (binding and positions).. after the migration i tested the ota function in z2m and all bticino devices had an update that worked pretty much immediately.
> > k4027c + k4027cwi + k4531c + k4003c and even fc80gcs were updated ota.
> 
> Damn! Mine still don't want to update, I still get `failed (OTA: Device didn't respond to OTA request)`. Do you remember the version before the OTA? Mine are:
> 
> * 001c
> * 002c
> * 003c
> * 003e
> * 0036
> 
> Thanks!

they were all firmware 0036, build date did not change but version jumped to 0053.. (i had the k4003c acting wierd with the ota respond request but eventually it also updated after several tries).

using the method described (the double pair) allows to calibrate them, and position works.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16479888/ce2dc3e6-4fda-49e1-bbd9-014a1cd828a1)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16479888/0141ca4b-c82e-4e37-8673-8b885620566e)

z2m exposes position AND tilt, and i dont want the entities to have tilt so i had to filter the devices in homeassistant:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/16479888/15c94890-78ba-4623-a5c1-f0bdd874d7ad)

**Comment by philippk75** [comment]
hello, 

i also don't want the tilt funktion, it doesn't work for me. to filter this i have to make this customize_glob.yaml? 

can i insert the text above?

Best regards

**Comment by FabianMangold** [comment]
Hello,
I've just submitted [PR#7412](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7412 to disable the tilt control.
By default, the tilt control will be displayed.

Hope this helps!
Cheers

**Comment by developerGM** [comment]
I have solved the problem abount position:

1. restart zigbee2mqtt integration
2. during restart, hold press on cover reset button...wait red light and than release button
3. wait 2seconds and than click (1 tap) on cover reset button again...now you can see the green light flashing
4. when zigbee2mqtt finish restart the green led will stop flashing and you can listen a little sound
5. configuration now is completed
6. than, to calibrate cover, press up and down buttons in the same time for about 5 seconds...when you see a yellow led flashing, release the buttons and wait about 5minutes...the cover will start to calibrate automatically

with these steps solve the problem

I have another problem...when I use the card to show cover position, I haven't a refresh of the state...I need to refresh state position forcing click on refresh button...why??
