### ISSUE TITLE
[New device support]: Philips LCX015

### ISSUE THREAD

**Issue by theeogflip** [Koenkk/zigbee2mqtt#19508]
### Link

https://www.philips-hue.com/de-de/p/hue-white---color-ambiance-festavia-lichterkette-20m/8720169246621

### Database entry

{"id":28,"type":"Router","ieeeAddr":"0x001788010dd9f58f","nwkAddr":53151,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCX015","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230508","swBuildId":"1.107.1","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1698845982306,"defaultSendRequestWhen":"immediate"}

### Comments

Please support the new Hue Light :)

**Comment by Koenkk** [comment]
Will be supported in todays release thanks to @theeogflip  !
