### ISSUE TITLE
Xiaomi WXKG13LM (Aqara T1 wireless mini switch) does not pair

### ISSUE THREAD

**Issue by AbelLykens** [Koenkk/zigbee2mqtt#19521]
### What happened?

Heya, I have here two new WXKG13LM's. Not sure how to pair. I tried clicking once, twice, and for 5sec. It does not seem to show up in z2m. What can I do? Cheers

### Zigbee2MQTT version

    1.33.1 commit: 7e63039

### Adapter firmware version

20210708

### Adapter

slae.sh

**Comment by Khayoann2** [comment]
Same issue here😭😭😭
