### ISSUE TITLE
ZM25RX-08/30 cover directions are reversed after 1.33.2 upgrade

### ISSUE THREAD

**Issue by burnsie-la** [Koenkk/zigbee2mqtt#19539]
### What happened?

Since upgrading to 1.33.2 my Zemismart tubular blind closes when I send the OPEN command and vice versa.  Changing the motor direction or using the Invert Cover options within Zigbee2MQTT had no effect.  Setting the position of the cover using the 0-100 value works as expected.

Device type: EndDevice
Zigbee Model: TS0601
Zigbee Manufacturer: _TZE200_7eue9vhc
Description: Tubular motor

It seems to have started happening after the introduction of this PR: https://github.com/Koenkk/zigbee-herdsman-converters/pull/6341/files

### What did you expect to happen?

The Close command should close the cover, the open command should open the cover.

### How to reproduce it (minimal and precise)

Pair a _TZE200_7eue9vhc with Z2M.
Press Close in the Exposes tab of the device in the UI
The blind opens, instead of closes.

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

7.1.1.0 build 273

### Adapter

Home Assistant SkyConnect

### Debug log

Topic: zigbee2mqtt/Top Floor Hallway Blind
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13249392/log.txt)

**Comment by burnsie-la** [comment]
This also seems to affect the _TZE200_bv1jcqqu version of the Zemismart ZM25RX-08/30

**Comment by Koenkk** [comment]
@donbobka  could you check this?

**Comment by donbobka** [comment]
@burnsie-la I've set state according to physical buttons+motor direction option. Can you send the photo of your blinds? I think maybe it depends on direction of blinds rolled onto tube 🤔 

P.S.: There's expose option to invert control that can reverse it.

**Comment by Koenkk** [comment]
@donbobka could you make a PR for that?

**Comment by burnsie-la** [comment]
> @burnsie-la I've set state according to physical buttons (buttons at left side)+motor direction option=normal. Can you send the photo of your blinds? It's strange that internal invert option doesn't work
> 
> Open/close actually depends on multiple factors 🤔: left/right side, direction of blinds rolled onto tube (in my case is left + under) ![image](https://user-images.githubusercontent.com/589057/280438197-1cf992cf-2d54-4631-b54f-1e3395a9cfdf.png)
> 
> @Koenkk, I don't think there is right way of installation and the best solution will change it back to keep it backwards compatible. Also maybe we should keep it as standard for tubular motor installation to keep open/close state consistent across all motors: like left side + rolled over (and then we have inverted option to invert it)

![PXL_20231104_094608519](https://github.com/Koenkk/zigbee2mqtt/assets/46924973/5308c358-bcc4-4545-bd8e-ea7da1704a14)
![PXL_20231104_094558713](https://github.com/Koenkk/zigbee2mqtt/assets/46924973/60e9966e-9e4a-48d0-b09c-0bce4b997f5b)

I have blinds that go in both directions, and they previously worked fine with Z2M. I originally set the motor direction and set points with the remote control, and the remote control still functions perfectly making all the blinds go up and down using the physical buttons as expected.

**Comment by KablammoNick** [comment]
Just to add to this - I have a mix of left/right roll-over blinds now doing the same. All are set to Open=100 in z2m, with the inverse set on the motor itself.
I have HA feed the blinds into both Google Home and HomeKit too - strangely HomeKit Open/Close works fine, however HA and GH do not.
Setting a % works correctly (80% = 80% open) in all three.
Using the RF remote works fine.

Zigbee2MQTT version
1.33.2

Adapter firmware version
20210708

Adapter
Sonoff ZBDongle-P

**Comment by TRusselo** [comment]
I have had the problem since the past few updates.

cover position is correct,  0% is fully closed, 100% is fully open
but open/close is reversed.

when the cover is closed 0%, I get one option, Open, clicking open button does nothing.
If I open the cover to 10% clicking Open will Close the blind.

**Comment by TRusselo** [comment]
oh.. and there is no working battery state for this motor, never worked.

**Comment by donbobka** [comment]
I'm back home, let me create PR

**Comment by donbobka** [comment]
I'm back and tested with reverted state values, but it makes open/close action inverted for me 🤔 (different hardware/firmware revision?)
```
[1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
```

@TRusselo @KablammoNick for the following setup (left side) ![image](https://user-images.githubusercontent.com/46924973/280458631-60e9966e-9e4a-48d0-b09c-0bce4b997f5b.jpg)
If you set `Motor direction` to `normal` and click button "down", is direction of rotation the same as in my video? 

https://github.com/Koenkk/zigbee2mqtt/assets/589057/66ce9130-ba88-4496-97ce-387fbfb7b322

**Comment by KablammoNick** [comment]
I'm away for a few days but will have a suss when I get home.

**Comment by donbobka** [comment]
Also my motor with default options `normal` and `not inverted`: position 0 = open, position 100 = close

**Comment by TRusselo** [comment]
changing the "motor direction" does not fix anything in home assistant for me.  cant see **any** change when changing "motor direction" option

**Comment by donbobka** [comment]
@TRusselo Does motor give feedback when you change options: small movement up and down? 

https://github.com/Koenkk/zigbee2mqtt/assets/589057/979a3ac2-29d9-4943-9365-51abd62e8df1

**Comment by donbobka** [comment]
Some photos of internals
![IMG_9800](https://github.com/Koenkk/zigbee2mqtt/assets/589057/d2ed048e-f023-43e0-b8ea-da96a0b37897)
![IMG_9802](https://github.com/Koenkk/zigbee2mqtt/assets/589057/c076469c-2fbf-4038-9099-63c03ec18d73)
![IMG_9798](https://github.com/Koenkk/zigbee2mqtt/assets/589057/f5cb7ec3-f7bb-4c1a-948f-fec1e043983c)
![IMG_9796](https://github.com/Koenkk/zigbee2mqtt/assets/589057/8ef2f777-0954-47bf-a66f-b1044a60c62b)
![IMG_9795](https://github.com/Koenkk/zigbee2mqtt/assets/589057/145ddcae-e9e1-4758-9c93-1f73895e40ba)
![IMG_9794](https://github.com/Koenkk/zigbee2mqtt/assets/589057/66020aab-3fcf-4c69-bf94-2f0344918e59)

**Comment by TRusselo** [comment]
> @TRusselo Does motor give feedback when you change options: small movement up and down? Is your motor `_TZE200_bv1jcqqu` or `_TZE200_7eue9vhc` in Zigbee Manufacturer in zigbee2mqtt?
> 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/1154815/9b7d8cc1-9201-4bdf-b190-0b785aedf738)


_TZE200_7eue9vhc
no reaction from motor when changing motor direction option. not like your video. nothing.

notes:
the up/down was correct couple months ago (or less)
battery % has never worked.

**Comment by donbobka** [comment]
I'll revert changes for _TZE200_7eue9vhc, seems it has different protocol

**Comment by donbobka** [comment]
I'll revert `_TZE200_7eue9vhc` seems it has different protocol

**Comment by burnsie-la** [comment]
> @TRusselo Does motor give feedback when you change options: small movement up and down? Is your motor `_TZE200_bv1jcqqu` or `_TZE200_7eue9vhc` in Zigbee Manufacturer in zigbee2mqtt?
> IMG_9805.mov

I also get no feedback from the motor at all when changing the settings in Z2M.  But I do if I reverse the motor direction using the RF remote that came with the device

**Comment by donbobka** [comment]
@burnsie-la 🤔  and your device is `_TZE200_bv1jcqqu`, isn't it. Did Z2M motor direction option worked before `1.33.1`?

**Comment by burnsie-la** [comment]
> @burnsie-la 🤔 and your device is `_TZE200_bv1jcqqu`, isn't it. Did Z2M motor direction option worked before `1.33.1`?

I have both _TZE200_bv1jcqqu and _TZE200_7eue9vhc, motor direction and battery never worked via Z2M for either. They seem to function the same.

**Comment by donbobka** [comment]
Seems i have and updated revision (just firmware?) that supports zigbee commands for motor direction/set limits. 

[PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6492) with fix

**Comment by KablammoNick** [comment]
> I'm back and tested with reverted state values, but it makes open/close action inverted for me 🤔 (different hardware/firmware revision? i see some visual differences: like on-off button).
> 
> ```
> [1, 'state', tuya.valueConverterBasic.lookup({ 'OPEN': tuya.enum(0), 'STOP': tuya.enum(1), 'CLOSE': tuya.enum(2) })],
> ```
> 
> If i set `Motor direction` to `reverse` to fix open/close actions, then buttons are inverted
> 
> @TRusselo @KablammoNick for the following setup (left side) ![image](https://user-images.githubusercontent.com/46924973/280458631-60e9966e-9e4a-48d0-b09c-0bce4b997f5b.jpg) If you set `Motor direction` to `normal` and click physical buttons, are directions of rotation same as in my video?

No feedback from motor with settings changes... and changing motor_direction in Z2M makes no difference to the physical buttons on my blinds.

All blinds are TS0601 & _TZE200_7eue9vhc.
All blinds are roll-over, with motor side specified... however I can't remember which ones were inverted on the device at installation. I've made the assumption based off your video and flipping it to match roll-over, the ones with the motor on the right side are "correct" with physical up/down buttons.

```
Name			Model	Manufacturer		Motor Side	Z2M Invert Cover	Invert on Device	Z2M motor_direction
blind_backdoor_left	TS0601	_TZE200_7eue9vhc	Left		False			True			blank?
blind_backdoor_right	TS0601	_TZE200_7eue9vhc	Right		False			False			normal
blind_dining		TS0601	_TZE200_7eue9vhc	Left		False			True			blank?
blind_kitchen		TS0601	_TZE200_7eue9vhc	Right		False			False			normal
blind_sidedoor_left	TS0601	_TZE200_7eue9vhc	Left		False			True			blank?
blind_sidedoor_right	TS0601	_TZE200_7eue9vhc	Right		False			False			normal
```

**Comment by TRusselo** [comment]
Im confused why physical buttons have entered the conversation.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/1154815/9eccfa71-10be-4564-a40d-b141cc8ac960)

**Comment by donbobka** [comment]
@TRusselo logical buttons and physical buttons are connected (at least on my motor)
> I'm back and tested with reverted state values, but it makes open/close action inverted for me 🤔

Hopefully this [video](https://www.youtube.com/watch?v=sdjC6S45dmw) from another PR explains it (still waiting for a few more motors to test it completely).

[PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6503) that reverts logical open/close action has been already merged into master
