### ISSUE TITLE
[New device support]: Tuya TS0601 _TZE204_vawy74yh

### ISSUE THREAD

**Issue by Aposei** [Koenkk/zigbee2mqtt#19557]
### Link

https://es.aliexpress.com/item/1005005994003685.html?spm=a2g0o.order_list.order_list_main.5.4d10194dz2u28M&gatewayAdapt=glo2esp

### Database entry

{"id":14,"type":"EndDevice","ieeeAddr":"0xa4c13862871e3f84","nwkAddr":43949,"manufId":4417,"manufName":"_TZE204_vawy74yh","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u001f\u0000\u0000\u0000e \u0000\u0000\u0000\u0012","65506":56,"65508":1,"appVersion":73,"modelId":"TS0601","manufacturerName":"_TZE204_vawy74yh","powerSource":3,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1699095641358,"defaultSendRequestWhen":"immediate"}

### Comments

I don't have enough knowledge to do it myself, can you help to create a converter? Thanks.

### External converter

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    // Since a lot of TuYa devices use the same modelID, but use different datapoints
    // it's necessary to provide a fingerprint instead of a zigbeeModel
    fingerprint: [
        {
            // The model ID from: Device with modelID 'TS0601' is not supported
            // You may need to add \u0000 at the end of the name in some cases
            modelID: 'TS0601',
            // The manufacturer name from: Device with modelID 'TS0601' is not supported.
            manufacturerName: '_TZE204_vawy74yh',
        },
    ],
    model: 'TS0601_Smart_Smoke_Detector',
    vendor: 'TuYa',
    description: 'Smart smoke detector',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime, // Add this if you are getting no converter for 'commandMcuSyncTime'
    configure: tuya.configureMagicPacket,
    whiteLabel: [ tuya.whitelabel('MOES', 'ES1ZZ(TY)', 'Smart smoke detector', ['_TZE204_vawy74yh']), ],
// whiteLabel: [{vendor: 'MOES', model: 'ES1ZZ(TY)'}],
    exposes: [
        // Here you should put all functionality that your device exposes
    ],
    meta: {
        // All datapoints go in here
        tuyaDatapoints: [
        ],
    },
};

module.exports = definition;
```

**Comment by frederick9372** [comment]
Same probleme with same device even update 1.33.2
https://fr.aliexpress.com/item/1005005997839493.html?spm=a2g0o.order_list.order_list_main.17.53075e5bRXG1fg&gatewayAdapt=glo2fra

**Comment by Aposei** [comment]
Hi. I'm trying to map the tuyaDatapoints but in the log I only get this

![log](https://github.com/Koenkk/zigbee2mqtt/assets/92597237/ff5a8454-8ad0-43aa-8d52-fb383ff5f16c)

**Comment by Iroamstaff** [comment]
I also have the same smoke detector, no progress for support?

**Comment by Aposei** [comment]
> I also have the same smoke detector, no progress for support?

I can't find the tuyaDatapoints
