### ISSUE TITLE
Xiaomi sensors report battery as 100%

### ISSUE THREAD

**Issue by radinsky** [Koenkk/zigbee2mqtt#1955]
# Bug Report
## What happened
All my xiaomi aquara sensors (except of temp/humidity) report 100% battery.

## What did you expect to happen
Actual value of the battery

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
What voltage do you get?

**Comment by radinsky** [comment]
3055 or 3065 for motion sensors (RTCGQ11LM) - all of their batteries about 2 years old and in xiaomi app was showing about 40%..
for all door/window sensors (MCCGQ11LM) I got voltage value 3025 (they are also all about 2 years old)

**Comment by Koenkk** [comment]
The batteries in these devices are 3 volts, based on a voltage of 3.055v (3055) I would assume it is full. However it seems that the Xiaomi bridge uses a different algorithm to calculate this. 

The current algorithm that zigbee2mqtt uses can be found here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L55. I'm open for improvements to this.

**Comment by radinsky** [comment]
The issue still exists, looks like it not reading the battery value correct, validated on most recent v.1.7.0
