### ISSUE TITLE
[Feature request]: device 550D6001 battery info

### ISSUE THREAD

**Issue by devildant** [Koenkk/zigbee2mqtt#19552]
### Is your feature request related to a problem? Please describe

Hello, according to the documentation that I have on this device ([550D6001](https://www.zigbee2mqtt.io/devices/550D6001.html#schneider%2520electric-550d6001)), the battery level is supposed to be reported in the wiser applications, so it should be possible to retrieve this information, however no idea how to do this or what to analyze

### Describe the solution you'd like

have battery info

### Describe alternatives you've considered

any

### Additional context

any

**Comment by devildant** [comment]
pull request created :p 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6431

**Comment by Koenkk** [comment]
Thanks!
