### ISSUE TITLE
EAKCB-T-M-Z Increase Overvoltage Limit 

### ISSUE THREAD

**Issue by lucasimons** [Koenkk/zigbee2mqtt#19588]
### What happened?

I use this DIN circuit breaker but the range of overvoltage threshold would be edited ... Now is 220 to 260V but the default value is 265V so we need to ingrease the max value to 265V
 

```
Logger: homeassistant.components.mqtt.number
Source: components/mqtt/number.py:194
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 20:25:45 (13 occurrences)
Last logged: 20:35:55

Invalid value for number.ingresso_enel_inverter_2_over_voltage_threshold: 265 (range 220.0 - 260.0)

```

![image](https://github.com/Koenkk/zigbee2mqtt/assets/67467751/ee173eff-83c2-41c3-9b51-7a257b482977)

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20210120

### Adapter

zStack3x0

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by lucasimons** [comment]
When this fix is available in the normal add on not the edge version?

**Comment by Koenkk** [comment]
Next release is on 1 December.
