### ISSUE TITLE
LED2201G8 has colour despite being a white spectrum device

### ISSUE THREAD

**Issue by fzakfeld** [Koenkk/zigbee2mqtt#19585]
### What happened?

I have an IKEA LED2201G8 bulb that recently got added (see https://github.com/Koenkk/zigbee2mqtt/issues/19118)

However, the light has colour attributes in Home Assistant, which are just "translated" into a warm or cold white. The bulb doesn't support colour, but in the ikea.ts file it extends tradfriExtend.light_onoff_brightness_colortemp_color() - surely this is not supposed to be like that?

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee dongle

**Comment by Koenkk** [comment]
Removed the color support!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
