### ISSUE TITLE
HLD503-Z-CT it is not recognised

### ISSUE THREAD

**Issue by ChrisSmartHome** [Koenkk/zigbee2mqtt#19608]
### What happened?

When connecting HLD503-Z-CT it is not recognised. Adding the model '050' to the zigbeeModel fixes this

`    {
        zigbeeModel: ['HOMA1009', '050'],
        model: 'HLD503-Z-CT',
        vendor: 'Shenzhen Homa',
        description: 'Smart LED driver',
        extend: extend_1.default.light_onoff_brightness_colortemp(),
    },`

### What did you expect to happen?

Device should have been mapped accordingly, this can be achieved by adding the mentioned model '050':

`    {
        zigbeeModel: ['HOMA1009', '050'],
        model: 'HLD503-Z-CT',
        vendor: 'Shenzhen Homa',
        description: 'Smart LED driver',
        extend: extend_1.default.light_onoff_brightness_colortemp(),
    },`

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

0x26720700

### Adapter

ConBee II

**Comment by Koenkk** [comment]
Integrated the fix!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
