### ISSUE TITLE
[Feature request]: demande de rajout des ampoules Ampoule Led Smart couleur & blanc DELTA DORE

### ISSUE THREAD

**Issue by nicoto94** [Koenkk/zigbee2mqtt#19615]
### Is your feature request related to a problem? Please describe

Salut a tous; je souhaiterai faire la demande de rajout des ampoule demande de rajout des ampoules Ampoule Led Smart couleur & blanc DELTA DORE

### Describe the solution you'd like

ajout des ampoule demande de rajout des ampoules Ampoule Led Smart couleur & blanc DELTA DORE

### Describe alternatives you've considered

ajout des ampoule demande de rajout des ampoules Ampoule Led Smart couleur & blanc DELTA DORE

### Additional context

ajout des ampoule demande de rajout des ampoules Ampoule Led Smart couleur & blanc DELTA DORE

**Comment by Koenkk** [comment]
Englisch only.
