### ISSUE TITLE
1.6.0 dev - Network map weirdness

### ISSUE THREAD

**Issue by james-fry** [Koenkk/zigbee2mqtt#1961]
# Bug Report
## What happened
Network map is rendering extremely strangely
![image](https://user-images.githubusercontent.com/5823294/64817359-96534000-d5a1-11e9-8876-9e73ac8c7f60.png)

I can provide logs of the network diagram log.

## What did you expect to happen
Network map will look similar to how it looked on 1.5.1 (or better ;))

## How to reproduce it (minimal and precise)
Unsure

## Debug Info
zigbee2mqtt version:
hassio addon edge (1.6.0 dev)
CC253X firmware version:
CC2530_CC2591_SOURCE_ROUTING_20190619

**Comment by james-fry** [comment]
Thanks @clockbrain.
Def there some issues in my network but I more raised this defect because of the rendering issue where nodes in the graph are plotted in the far extremes

**Comment by Koenkk** [comment]
@james-fry note that the rendering is not done by zigbee2mqtt.

**Comment by james-fry** [comment]
@Koenkk this I understand, but it seems there is data from z2m that is driving these strange maps.
Its not impossible that a problem with my devices suddenly occurred and made this happen, but I think it is related to 1.6.0 upgrade. If this is not correct, please feel free to close the issue.

**Comment by dreimer1986** [comment]
Some things clearly changed in that matter. See above the report I linked to. In the lovelace networkmap by azuwis there are zero links between the devices in 1.6.0 dev and the one by rgruebel looks quite funny on my side, too. Not that strange as the OP pics show, but some links are gone for sure. Both worked fine / looked different in 1.5.1:

rgruebel version (before all devices had links to almost any other device resulting in a massive mesh):
![2019-09-13 13_20_27-Home Assistant](https://user-images.githubusercontent.com/29841368/64859028-6780ac80-d629-11e9-911e-8c4423bea806.png)

azuwis version (before had at least links between each other):
![2019-09-13 13_20_47-Home Assistant](https://user-images.githubusercontent.com/29841368/64859032-6bacca00-d629-11e9-98fd-71f7517e95f7.png)

**Comment by Koenkk** [comment]
@dreimer1986 did any of the scans fail? It may that the output has been changed.

**Comment by dreimer1986** [comment]
Not really. Scans worked on 1.5.1 and do on 1.6.0 as it seems. If you dont see any strange things in that log, I must say all is fine in device using matters.

**Comment by juanjux** [comment]
My network map is also broken in 1.6-dev. Most of the routers are missing (I've more than 50) and there are no lines between the others. It worked on 1.5.1:

![image](https://user-images.githubusercontent.com/277378/65087366-af029200-d9b5-11e9-8064-4944a3c10765.png)

**Comment by dreimer1986** [comment]
After https://github.com/Koenkk/zigbee2mqtt/commit/11aacb86208728cb0f878179cd88b8642cf24ce8 I am out. rgruebel version still looks different to 1.5.1 but maybe this one is the correct one. At least it looks correct connection wise. And azuwis one is fine again too.
![2019-09-18 08_36_14-Home Assistant](https://user-images.githubusercontent.com/29841368/65121679-f0b02e80-d9ef-11e9-8b9a-64c7e5dfa4e3.png)
![2019-09-18 08_40_39-Home Assistant](https://user-images.githubusercontent.com/29841368/65121742-09204900-d9f0-11e9-99c7-6fba0471196e.png)

**Comment by Gesfenlir** [comment]
I have the same issue here...
- (almost all) my router devices got a LQI and show up connected between each other on the map
- none on the endpoint devices are connected to any router (on the map)
- my Ikea Repeater does not show on the map at all (neither in the log)

Nothing special shows up in the log after I launch zigbee2mqtt_networkmap.update service.

Note that all works well, only the map has a weird rendering.

**Comment by lolorc** [comment]
same here, just a few devices connected while it was ok before upgrading to 1.6-dev.
devices work ok as well.
Is anybody running 1.6-dev having a proper map (like it was with 1.5*) ?

**Comment by james-fry** [comment]
I would be happy to close this defect now.
The network map has stabilised for me on 1.6 dev and I didnt see the really weird rendering from my 1st few posts in this issue.

This said I still have the issue with many/most end devices not showing a relationship to a router or the coordinator, and where there is often no bi-directional relationship between routers.

This is how its looking now.

![image](https://user-images.githubusercontent.com/5823294/67952851-e20b8880-fbe5-11e9-9f69-81dfd2573b70.png)

BTW I have this problem with both of the following set ups:

- cc2530, Z-Stack_Home_1.2 (source_routing)
- cc1352P, Z-Stack_3.x.0

I'd really like to get to the bottom of this...

**Comment by lolorc** [comment]
all my devices used to be connected to my coordinator/router, it's not anymore. what shouldn't that be a bug needing a fix ?

**Comment by lolorc** [comment]
it might be related to https://github.com/Koenkk/zigbee-herdsman/issues/69

**Comment by timota** [comment]
Probably i need to put this here, not sure

I made some tests to check:
- if i add only 2 devices (end-devices) to coordinator - i can see `linkquality` for them and so z2mAssistant can build proper map. 
- if i add 3-d device:
    - in logs i can see that device reports `linkquality`
`zigbee2mqtt:info  2019-10-31T19:37:38: MQTT publish: topic 'zigbee2mqtt/0x00158d000274fe84', payload '{"battery":80,"voltage":2965,"contact":false,"linkquality":51,"last_seen":1572550658817,"device":{"friendlyName":"0x00158d000274fe84","ieeeAddr":"0x00158d000274fe84","networkAddress":17964,"type":"EndDevice","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","applicationVersion":3,"stackVersion":2,"zclVersion":1,"hardwareVersion":2,"dateCode":"20161128","softwareBuildID":"3000-0001"}}'`
 
but in z2mAssistant reports all attributes except `Link quality is unknown/255.`, so it cant build map

- if i add to the same setup additional router, and after it add 3 additional end-devices. z2mAssistant reports `linkquolity` for first 2 devices (including router itself) but not for 3-d device.
- same picture if i add another router and next 3 end-devices.

for me it looks like somewhere limit for 3 device (including router/coordinator) has been set. 

i definitely didnt see this issue with Stable 1.6 and CC2531 as coordinator.

BTW: current coordinator is cc1352P2

**Comment by james-fry** [comment]
I think this lines up with what I am seeing, @timota.
Also cc1352p-2, but not sure that matters.

E.g. below, where I have 2 x end devices on the coord, and 2 x end devices on the router.
The rest, nothing.

![image](https://user-images.githubusercontent.com/5823294/67985296-72ff5580-fc20-11e9-9bca-31836438c1b8.png)

**Comment by Koenkk** [comment]
Should be fixed in latest dev (should give same behaviour as 1.6.0). (reference #2307)

**Comment by axiom00** [comment]
Latest dev fixed the mapping issue. Just have to figure out why nothing is using the repeaters.

![image](https://user-images.githubusercontent.com/46800436/68552104-61b50680-03e1-11ea-9126-1eec5934daa5.png)

**Comment by james-fry** [comment]
Maybe the end devices can reach the coordinator directly OR via router.
Then we end up with maps like this (deconz):

![image](https://user-images.githubusercontent.com/5823294/68552144-9b9b0280-040b-11ea-9503-137e4bd0fdc8.png)

I mentioned it in another thread, but I think the best solution is for some form of interactivity in the map to redraw the map in the context of a selected node.
Clearly this is much more development than what we have here...

**Comment by Koenkk** [comment]
@james-fry this is out of scope for zigbee2mqtt and should be done by the application rendering the graph.

Closing as this issue has been fixed.

**Comment by james-fry** [comment]
Don’t disagree at at all.
