### ISSUE TITLE
Bticino N4027C hide tilt options if not in venetian mode

### ISSUE THREAD

**Issue by philippk75** [Koenkk/zigbee2mqtt#19621]
### Is your feature request related to a problem? Please describe

It'possibile to hide the tilt options for Bticino N4027C, i suppose alo Legrand actors, if the rollershutter ist not a venetian? it makes no sense to habe the option foir a standard rollo

### Describe the solution you'd like

I i make the calibrations in venetian mode, show the tile option, if i make the calibration in generic oder specific mode hide the tile option.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by FabianMangold** [comment]
Hi @philippk75 ,

It's been a while (sorry for that), but i have eventually submitted a PR (https://github.com/Koenkk/zigbee-herdsman-converters/pull/7412) to have this fixed.
Could you please have a look as soon as the PR is merged ?

Thanks a lot
