### ISSUE TITLE
Failed to ping Xiaomi Aqara LLKZMK11LM

### ISSUE THREAD

**Issue by LCerebo** [Koenkk/zigbee2mqtt#1962]
# Bug Report
## What happened
I'm having problem with the Xiaomi Aqara LLKZMK11LM, I have two of them and in the log I frequently see "Failed to ping 'device_name'" error.
I also noticed that after few commands they became unresponsive.
I read about the issue #1248 so I checked the log and they are pinged using the basic method.
Other zigbee devices works like a charm.
Am I missing something?

## How to reproduce it (minimal and precise)
Send few commands in rapid sequence to the devices from home assistant.

## Debug Info
zigbee2mqtt version: 1.6.0 (commit #e26ad2a) Docker
CC2531 firmware version: 20190608
home-assistant: 0.98.5

[log](https://pastebin.com/R05W0vCX)

**Comment by LCerebo** [comment]
@Koenkk I done a quick test with latest-dev and the “Failed to ping” message is resolved. The devices seem much more responsive, I only received a few time the error: 
“Publish ‘set’ ‘state’ to ‘device_name’ failed: ‘Error: Data request failed with error: ‘No network route’ (205)’”
Even if the signal is strong enough.
They are connected through a router.

**Comment by Koenkk** [comment]
It is basically the same issue; the device cannot be reached. You may check the networkmap to check what is going on.

**Comment by LCerebo** [comment]
Sorry if I didn't replay sooner but I need to rethink a little my setup to be sure.
Now I placed a philips hue bulb (9290012573A) near (less then 1 meter) the xiaomi smart relay with the  ‘No network route (205)’ problem and I can use the bulb perfectly but not the xiaomi relay.
I'm on the latest dev docker image (version 1.6.0 commit #41c8c2a).
