### ISSUE TITLE
Ikea devices OTA updates stuck on "Installing"

### ISSUE THREAD

**Issue by manodory** [Koenkk/zigbee2mqtt#19634]
### What happened?

I have two Ikea blinds, and they work perfectly. 
A week ago, it seems that Z2M found a firmware update and is trying to install it, but it's just stuck on Installing mode for days now. 

### What did you expect to happen?

I expected that the update will be deployed with no issues. 

### How to reproduce it (minimal and precise)

I don't know. Please let me know what further info is needed.  

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

no coordinator revision option found, 

### Adapter

Zigbee ESP32 GW

### Debug log

[z2m.log](https://github.com/Koenkk/zigbee2mqtt/files/13307534/z2m.log)

**Comment by julianfs** [comment]
This is already logged as #19622
