### ISSUE TITLE
Add support for AOK Curtain Motor

### ISSUE THREAD

**Issue by Jinvis** [Koenkk/zigbee2mqtt#1964]
Hi, 
I am an user of zigbee2mqtt, I have a AOK Curtain Motor(zigbee) in my house, and i want to add it to homeassistant.
I have captured some data with wireshark from ovribo gateway, and try to control it as xiaomi Curtain Motor, but it does not work, Can someone help me with this? Thanks very much.

report attributes pictures:
![image](https://user-images.githubusercontent.com/26951454/64854492-4b443600-d650-11e9-9ec2-08d79279c997.png)

this is close data:
![image](https://user-images.githubusercontent.com/26951454/64854711-dde4d500-d650-11e9-81a5-6c7bdab38047.png)

zigbee2mqtt log:
  zigbee2mqtt:warn 9/13/2019, 6:01:39 PM No converter available for 'AOK_win_motor' with cid 'closuresWindowCovering', type 'attReport' and data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":0}}'

**Comment by Jinvis** [comment]
I try to control as xiaomi motor, it does not work:
return [{
                    cid: 'genAnalogOutput',
                    cmd: 'write',
                    cmdType: 'foundation',
                    zclData: [{
                        attrId: 0x0008,
                        dataType: 0x20,
                        attrData: value,
                    }],
                    cfg: cfg.default,
                }];

**Comment by Koenkk** [comment]
I would recommend adding support for this device in the zigbee2mqtt dev branch (as together with zigbee-herdsman-converters this should be easier). Here it for example shows how to do a write: https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/converters/toZigbee.js#L601
