### ISSUE TITLE
Namron Panel heater energy reporting bug

### ISSUE THREAD

**Issue by Xplode85** [Koenkk/zigbee2mqtt#19644]
### What happened?

Namron Panel heater model 540139X

The energy value has bad readings at some points of the day, sometimes higher and sometimes lower than the real value.
I have 7 of these heaters split between 2 locations/setups and all show the same problem, but weirdly they are randomly fine one day and starts reporting the bad values again the next day.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/72715336/eb2299c7-bb54-4864-a8bb-a8bfaca35a52)

### Zigbee2MQTT version

1.33.2-1 

### Adapter firmware version

7.2.2.0 build 190

### Adapter

EZSP v11

### Debug log

[Varmeovn Sal Midt.txt](https://github.com/Koenkk/zigbee2mqtt/files/13312564/Varmeovn.Sal.Midt.txt)

**Comment by patrikron** [comment]
Same problem.
