### ISSUE TITLE
Some devices offline

### ISSUE THREAD

**Issue by philippk75** [Koenkk/zigbee2mqtt#19648]
### What happened?

Recently it has been happening more and more frequently that some devices in Home Assiatnt with Zigbee2Mqtt are offline or do not respond

### Zigbee2MQTT version

1.33.2-dev 

### Adapter firmware version

7.1.1.0 build 273

### Adapter

Skyconnect Zigbee Adapter

**Comment by kizio1000** [comment]
same here, all after latest update

**Comment by jsb2092** [comment]
Also having the same issue

**Comment by suspended** [comment]
Same issue here. After latest updates.

**Comment by aletzi1** [comment]
Same issue here

**Comment by Lyric41CR** [comment]
Idem pour moi sous 1.33.2 les devices se déco sans raison

**Comment by matidellatorre** [comment]
Same issue with last update

**Comment by helgek** [comment]
Having a similar issue, randomly one of my devices would not respond to commands coming from Z2M, results in a timeout error:https://github.com/Koenkk/zigbee2mqtt/issues/13993#issuecomment-1824743866 - coordinator is the highly praised SLZB-0 (based on stable chipset CC2652P  recommended by Z2M, not the experimental EFR32MG21 chipset).
