### ISSUE TITLE
R[Wrong device]: Ynnwft / Generic Repeater

### ISSUE THREAD

**Issue by IdefixRC** [Koenkk/zigbee2mqtt#19653]
### Link

https://www.aliexpress.com/item/1005005400309837.html

### Model

ZB-R01

### Description

Repeater

### Vendor

Ynnweft

### Picture (link)

https://m.media-amazon.com/images/I/51aoHYH+M0L._AC_SL1001_.jpg

### Database entry

{"id":7,"type":"Router","ieeeAddr":"0x00124b0023a5375a","nwkAddr":27983,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"SA-003-Zigbee","epList":[1],"endpoints":{"1":{"profId":49246,"epId":1,"devId":16,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genOnOff":{"attributes":{"onOff":1}},"genBasic":{"attributes":{"modelId":"SA-003-Zigbee","manufacturerName":"eWeLink","powerSource":1,"zclVersion":1,"appVersion":8,"hwVersion":1,"dateCode":"20210703","swBuildId":"1.0.7"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe9cba32","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":8,"hwVersion":1,"dateCode":"20210703","swBuildId":"1.0.7","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1699618298176,"defaultSendRequestWhen":"immediate"}

### Notes

Repeater is detected as eWeLink Plug - [SA-003-Zigbee]
(https://www.zigbee2mqtt.io/devices/SA-003-Zigbee.html#ewelink-sa-003-zigbee)

This is a cheap Chinese USB repeater so maybe it just uses the same chipset as the sa-003 and hence shows up as a plug.
Based on the DB entry is it possible to identify the device correctly?

Thanks !

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by lrljoe** [comment]
@Koenkk - think this may have broken actual SA-003-Zigbee devices, as I tried to re-add one of my plugs, and it is detected as ZB-R01 instead of SA-003-Zigbee!

**Comment by Koenkk** [comment]
I've reverted the fix. Looking closer at the data/database.db entry this device has `"inClusterList":[0,3,4,5,6]`, `6` = `onOff` cluster which means it is a switch. So seems the vendor was to lazy to use a different firmware for this device. We cannot separate both devices from each other since they share the same fingerprint. So unfortunately  we cannot fix this.
