### ISSUE TITLE
[New device support]: Philips Hue white ambiance Aurelle square panel light, 120x30 cm "929003597701"

### ISSUE THREAD

**Issue by MicEs1** [Koenkk/zigbee2mqtt#19658]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-ambiance-aurelle-rectangle-panel/8720169158955

### Database entry

{"id":74,"type":"Router","ieeeAddr":"0x001788010d21210c","nwkAddr":7284,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003597701","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003597701","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"colorTemperature":369}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1699631798071,"defaultSendRequestWhen":"immediate"}

### Comments

Hello,

as the **Philips Lightpanel with 60x60 cm** was [quickly added](https://github.com/Koenkk/zigbee2mqtt/issues/19604) to Zigbee2MQTT and I am very satisfied with the product I choose to buy another lightpanel from the series.

This time I bought the **`Philips Hue white ambiance Aurelle square panel light`** with **120x30 cm** dimensions.

Here is an Amazon Link to the lightpanel: https://www.amazon.de/dp/B0C61WXY4W

And here directly from Philips itself: 
https://www.philips-hue.com/en-gb/p/hue-white-ambiance-aurelle-rectangle-panel/8720169158955

I made the same actions like the [last time](https://github.com/Koenkk/zigbee2mqtt/issues/19604)

This time the model number is **`929003597701`**.

So here is my new `signify2.js`:

```yaml
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters//lib/ota');
const philips = require('zigbee-herdsman-converters//lib/philips');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
zigbeeModel: ['929003597701'],
model: '929003597701',
vendor: 'Signify Netherlands B.V.',
description: 'Hue white ambiance Aurelle square panel light 120x30',
extend: philips.extend.light_onoff_brightness_colortemp({colorTempRange: [153, 454]}),
};

module.exports = definition;
```

The `database.db` entry is:

```
{"id":74,"type":"Router","ieeeAddr":"0x001788010d21210c","nwkAddr":7284,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003597701","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003597701","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"colorTemperature":369}},"genLevelCtrl":{"attributes":{"currentLevel":254}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1699631798071,"defaultSendRequestWhen":"immediate"}
```

I am able to control light panel in all regards:

- on/off
- dim
- color temperature

Like with the 60x60 cm lightpanel there were also with the new 120x30 cm lightpanel 2 firmware updates in a row:

- original delivered firmware: Date: `20210305`, Version: `1.82.10`
- first updated firmware: Date: `20211210`, Version: `1.93.7`
- second updated firmware: Date: `20230403`, Version: `1.104.2`

So I think it is okay to make another update to the device database. :-)

@Koenkk: Can you please add the new 120x30 cm lightpanel like the last time? Thank you very much.

### Supported color modes

color temperature

### Color temperature range

{colorTempRange: [153, 454]}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by FHEMbeta** [comment]
Could you please add this definition for the Model 929003099102. This ist the same light as this one here just with a white frame instead of black. Zigbee2MQTT says it is unsupported.

**Comment by Koenkk** [comment]
@FHEMbeta added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `929003099102.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by TheSelfHoster** [comment]
Hey guys,

seems that i found another one from the same series. Could you please add the same support also for 929003597702? It's exactly the same device as the 929003597701 here. The updates came correctly as here mentoined but it's listed as unsupported.

**Comment by jathersmith** [comment]
> Hey guys,
> 
> seems that i found another one from the same series. Could you please add the same support also for 929003597702? It's exactly the same device as the 929003597701 here. The updates came correctly as here mentoined but it's listed as unsupported.

I have the same issue, 929003597702 is still showing as not supported in the latest version of zigbee2mqtt. I am running it as an add-on in Home Assistant.
