### ISSUE TITLE
Recent errors and devices not working

### ISSUE THREAD

**Issue by wifiuk** [Koenkk/zigbee2mqtt#19655]
### What happened?

nothing has changed with my setup, but in the last week or two been getting errors and devices just not working with home assistant.

### What did you expect to happen?

it work

### How to reproduce it (minimal and precise)

n/a

### Zigbee2MQTT version

1.33.2-1 

### Adapter firmware version

20231030.1

### Adapter

SONOFF Universal Zigbee 3.0 USB Dongle Plus

### Debug log

here are some of the error logs:

1. Zigbee2MQTT:error 2023-11-10 12:19:31: Publish 'set' 'brightness' to 'Kitchen GROUP' failed: 'Error: Command 3 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}) failed (Cannot execute command, in Inter-PAN mode)'
2. Zigbee2MQTT:error 2023-11-10 12:19:31: Publish 'set' 'brightness' to 'Kitchen GROUP' again failed: 'Error: Command 3 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}) failed (Cannot execute command, in Inter-PAN mode)'
3. Zigbee2MQTT:error 2023-11-10 12:19:31: Publish 'set' 'brightness' to '[Bedroom 1] GROUP' failed: 'Error: Command 7 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}) failed (Cannot execute command, in Inter-PAN mode)'
4. Zigbee2MQTT:error 2023-11-10 12:24:31: Publish 'set' 'state' to '[Bedroom 2] GROUP' failed: 'Error: Command 6 genOnOff.off({}) failed (Cannot execute command, in Inter-PAN mode)'
5. Zigbee2MQTT:error 2023-11-10 12:24:32: Publish 'set' 'state' to '[Wardrobe 1]' failed: 'Error: Command 0x00158d0004731925/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Cannot execute command, in Inter-PAN mode)'
6. Zigbee2MQTT:error 2023-11-10 12:24:32: Publish 'set' 'state' to '[Wardrobe 2]' failed: 'Error: Command 0x00158d000189171b/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Cannot execute command, in Inter-PAN mode)'
7. Zigbee2MQTT:error 2023-11-10 12:24:32: Publish 'set' 'state' to '[Wardrobe 3]' failed: 'Error: Command 0x00158d00026802fb/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Cannot execute command, in Inter-PAN mode)'

**Comment by icagn** [comment]
Hello everyone, I have the same problem
