### ISSUE TITLE
device_group_add/remove log format not correct.

### ISSUE THREAD

**Issue by gdave321** [Koenkk/zigbee2mqtt#1965]
According to zigbee2mqtt/bridge/log
Message are always in the form of {"type":"TYPE","message":"MESSAGE"}

however, after upgrading to 1.6.0 I just noticed the structure like this:

{"type":{"type":"device_group_add","message":{"device":"0x0017880xxxxxx","group":"1"}}}

looks like an extra "type" level added here.

**Comment by Koenkk** [comment]
Thanks, fixed in the dev branch!
