### ISSUE TITLE
Immax NEO Smart remote control identified as Müller Licht MLI-404011/MLI-404049 remote control

### ISSUE THREAD

**Issue by semicolonmystery** [Koenkk/zigbee2mqtt#19673]
### What happened?

Hello, I would like to ask for support for Immax NEO Smart remote V2. I have the same problem as in #18565 that was closed without any response. I really hate that I have to press the off button to wake the remote. Also before I have connected the remote to zigbee I could press on for color change but that doesn't work when connected via zigbee.

### What did you expect to happen?

When click on when it is turned on change color.

### How to reproduce it (minimal and precise)

Operate with remote control, leave it untouched for couple of hours.

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF ZIGBEE 3.0 USB DONGLE PLUS

**Comment by Verustus** [comment]
The battery of it is also ? and with ZHA it was saing 86%.

**Comment by Verustus** [comment]
ping
