### ISSUE TITLE
[Wrong device]: bticino K4027C after update HA is Legrand 067776A

### ISSUE THREAD

**Issue by Bobsilvio** [Koenkk/zigbee2mqtt#19688]
### Link

https://catalogo.bticino.it/prodotto/soluzioni-per-edifici-residenziali-e-nel-terziario/living-now/comandi-per-tapparelle-e-ventole/BTI-K4027C-IT

### Model

BTicino K4027C/L4027C/N4027C/NT4027C

### Description

cover

### Vendor

Bticino

### Picture (link)

https://catalogo.bticino.it/thumbs/md/483925_484223_BTI_K4027C.jpg

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0x0004740000b3e19e","nwkAddr":8760,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Mains (single phase)","modelId":" Shutter SW with level control\u0000","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[0,3,4,5,15,64513,258],"outClusterList":[0,64513,5,25,258],"clusters":{"genBasic":{"attributes":{"modelId":" Shutter SW with level control\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":1,"zclVersion":2,"appVersion":0,"stackVersion":67,"hwVersion":9,"dateCode":" \u000020210203\u0000\u0000\u0000\u0000\u0000","swBuildId":"0036"}},"closuresWindowCovering":{"attributes":{"61444":25,"currentPositionLiftPercentage":100,"tuyaMovingState":100,"tuyaCalibration":1,"tuyaMotorReversal":0,"currentPositionTiltPercentage":0,"moesCalibrationTime":0}},"genBinaryInput":{"attributes":{"presentValue":0}},"genIdentify":{"attributes":{"identifyTime":60}}},"binds":[{"cluster":15,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe168eaa","endpointID":1},{"cluster":258,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe168eaa","endpointID":1},{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe168eaa","endpointID":1}],"configuredReportings":[{"cluster":258,"attrId":8,"minRepIntval":1,"maxRepIntval":62000,"repChange":1},{"cluster":258,"attrId":8,"minRepIntval":1,"maxRepIntval":120,"repChange":1,"manufacturerCode":4129},{"cluster":258,"attrId":9,"minRepIntval":1,"maxRepIntval":120,"repChange":1,"manufacturerCode":4129}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":67,"hwVersion":9,"dateCode":" \u000020210203\u0000\u0000\u0000\u0000\u0000","swBuildId":"0036","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1818048580},"lastSeen":1699758931876,"defaultSendRequestWhen":"immediate"}

**Comment by LamerTex** [comment]
This should be already fixed by [FabianMangold](https://github.com/FabianMangold) in [PR#6405](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6405) and/or [PR#6423](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6423). 
You need to use the DEV branch or wait for the next update
