### ISSUE TITLE
[New device support]: Gledopto GL-C-011P 5 In 1 Zigbee Smart Controller

### ISSUE THREAD

**Issue by Git-Vi** [Koenkk/zigbee2mqtt#19686]
### Link

https://de.aliexpress.com/item/1005005508867041.html?gatewayAdapt=glo2deu

### Database entry

{"id":49,"type":"Router","ieeeAddr":"0xa4c138b80b98d459","nwkAddr":23599,"manufId":4687,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-008P","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"GL-C-008P","manufacturerName":"GLEDOPTO","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230721","swBuildId":"20351203"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":158,"colorTempPhysicalMax":500,"colorMode":1,"currentX":22918,"currentY":23154,"enhancedCurrentHue":0,"currentSaturation":0,"colorTemperature":495,"startUpColorTemperature":65535}},"genLevelCtrl":{"attributes":{"currentLevel":136}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230721","swBuildId":"20351203","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-279112056},"lastSeen":1699798549832,"defaultSendRequestWhen":"immediate"}

### Comments

The device is added to the system as Gledopto GL-C-008P - but it does not work correctly.
Request to add native integration
Thanks in advance

**Comment by baerenmarke90** [comment]
+1 I need this device too.
