### ISSUE TITLE
group published

### ISSUE THREAD

**Issue by VOVAiS** [Koenkk/zigbee2mqtt#1971]
# Bug Report
## What happened
in the FAQ is written
`When one of the devices in a group changes it’s state, the group state will also update. E.g. device A is in group 1 with friendly_name: my_group, when group A turns off, a message to zigbee2mqtt/my_group with payload {"state": "OFF"} will be published.`

this does not work after the update
## Debug Info
zigbee2mqtt version: 1.6.0 f5463db
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
Should be fixed in latest dev.

**Comment by VOVAiS** [comment]
Thanks
