### ISSUE TITLE
[New device support]: Sonoff NS Panel PRO as a Router device

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#19721]
### Link

https://itead.cc/product/sonoff-nspanel-pro-smart-home-control-panel/

### Database entry

{"id":79,"type":"Router","ieeeAddr":"0xe0798dfffeb25098","nwkAddr":18228,"manufId":4098,"manufName":"SONOFF","powerSource":"Unknown","modelId":"NSPanelP-Router","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":7,"inClusterList":[0,3],"outClusterList":[0,3],"clusters":{"genBasic":{"attributes":{"modelId":"NSPanelP-Router","manufacturerName":"SONOFF"}}},"binds":[],"configuredReportings":[],"meta":{}}},"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1700038992754,"defaultSendRequestWhen":"immediate"}

### Comments

Hello Team 

With the new firmware version available for the NSpanel PRO Sonoff Device The device have the possibility ack as zigbee router

I try to add this device as a Router to Z2M but appear as not supported 

I'm sharing the  database entry of this device in order if you can help me to get this device supported in the Z2M list os devices 

Please let me know if you need anything more from my side 

Thank you in advance for your support and best regards

**Comment by Mike1969n** [comment]
I also wish this integration. I also can help.

**Comment by leroyvandijk** [comment]
Would also like to see this device supported

**Comment by pvklink** [comment]
I also like this device supported

**Comment by Koenkk** [comment]
Added! Will be supported in the 1 January release.

**Comment by cobch** [comment]
Is it possible to connect it out of the box to z2m? Want to buy it but want to be sure it will work (-;

**Comment by EnergieZ** [comment]
> Is it possible to connect it out of the box to z2m? Want to buy it but want to be sure it will work (-;

I have the same question ! I just buy it and install it, update to version 3.0, and configure it as a gateway. 
But now i'm stuck ! 
I've configure z2m with tcp and the ip of the nspannel, but it does not work

**Comment by mihaimdinca** [comment]
I set the NSPanel Pro to router mode but not sure how to add it to ZigBee2MQTT. I do not see any option to start pairing mode on the router. It does not work just by pushing the all join button in z2m. Any suggestion would be appreciated. Thank you!

**Comment by mihaimdinca** [comment]
Nevermind. I found it. Another problem though: the device drops from the network very often. No idea why. Any suggestions?

**Comment by mihaimdinca** [comment]
Apparently, it works well now with the latest version of ZigBee2MQTT.

**Comment by Guyvxt** [comment]
Apologies, my update script wasn't working and I was running an older version. Updated properly and now showing as supported. thanks

**Comment by lediable** [comment]
> Nevermind. I found it. Another problem though: the device drops from the network very often. No idea why. Any suggestions?

Sorry it's been a few months but I really couldn't understand how it works

how did you use nspanel pro as a router ( or coordinator? ) on zigbee2mqtt?

What settings did you use? What port did you use? 

Thanks for your future reply

**Comment by MiAutomations** [comment]
> > Nevermind. I found it. Another problem though: the device drops from the network very often. No idea why. Any suggestions?
> 
> Sorry it's been a few months but I really couldn't understand how it works
> 
> how did you use nspanel pro as a router ( or coordinator? ) on zigbee2mqtt?
> 
> What settings did you use? What port did you use?
> 
> Thanks for your future reply

Hello 

You need to change the router or coordinator from the ewelink APP after this you go to your Z2M UI and click to add a new device and on the device  you selected the paring mode

**Comment by lediable** [comment]
> > > Nevermind. I found it. Another problem though: the device drops from the network very often. No idea why. Any suggestions?
> > 
> > 
> > Sorry it's been a few months but I really couldn't understand how it works
> > how did you use nspanel pro as a router ( or coordinator? ) on zigbee2mqtt?
> > What settings did you use? What port did you use?
> > Thanks for your future reply
> 
> Hello
> 
> You need to change the router or coordinator from the ewelink APP after this you go to your Z2M UI and click to add a new device and on the device you selected the paring mode

yes that i have to choose coordinator or router i knew that. i just don't know what to put in the zigbee2mqtt configuration. without configuration it doesn't start, so i can't access this UI

I'm using home assistant

**Comment by BaerHub** [comment]
im also unable to start zigbee2mqtt, in the serial config i dont know what port to add?

**Comment by BaerHub** [comment]
> > > > Nevermind. I found it. Another problem though: the device drops from the network very often. No idea why. Any suggestions?
> > > 
> > > 
> > > Sorry it's been a few months but I really couldn't understand how it works
> > > how did you use nspanel pro as a router ( or coordinator? ) on zigbee2mqtt?
> > > What settings did you use? What port did you use?
> > > Thanks for your future reply
> > 
> > 
> > Hello
> > You need to change the router or coordinator from the ewelink APP after this you go to your Z2M UI and click to add a new device and on the device you selected the paring mode
> 
> yes that i have to choose coordinator or router i knew that. i just don't know what to put in the zigbee2mqtt configuration. without configuration it doesn't start, so i can't access this UI
> 
> I'm using home assistant

did you managed to get it working?

**Comment by pvklink** [comment]
> Added! Will be supported in the 1 January release.

is this z2m 2.0 or 1,42

**Comment by mihaimdinca** [comment]
Not sure I understand correctly. So to use the device as a router was possible for some time now, is it possible to use it as a coordinator as well?

**Comment by pvklink** [comment]
yes, i have HASS running with 4 instances of Z2M each with an own coordinator!
they have each there own IP, port, and mqtt, base topic
IN hass you get 4 bridges with eacht there own devices. On the frontend you only see all devices as usual.

2 RPI connected zigbee sonoff stick with a each a docker z2m
2 NSPANELS with z2m running and mqtt ...

**Comment by mihaimdinca** [comment]
So the z2m instance that uses the nspanel as coordinator is installed on the nspanel itself? Can you point me in the direction on how to do this? Is it like an Android app?

**Comment by mihaimdinca** [comment]
I currently run the addon for home assistant with a single coordinator - Sonoff ZigBee Dongle P

**Comment by pvklink** [comment]
> I currently run the addon for home assistant with a single coordinator - Sonoff ZigBee Dongle P

And yes i added some apps to my panel
the pro_tools
a new loader (so its rooted), 
homeassistant
z2m app via the latest beta pro tools

see 
https://github.com/seaky/nspanel_pro_tools_apk
https://github.com/seaky/nspanel_pro_tools_apk?tab=readme-ov-file#manual-2x-version
https://github.com/seaky/nspanel_pro_tools_apk/discussions/164

https://blakadder.com/nspanel-pro-sideload/
https://blakadder.com/nspanel-pro-secrets/
https://www.youtube.com/watch?v=c1Dqdz8yHDc

https://www.apkmirror.com/apk/home-assistant/home-assistant/

**Comment by mihaimdinca** [comment]
Thank you

**Comment by pvklink** [comment]
more coordinators arent needed, just playing arround, have 70 devices like to do shit stuff

**Comment by mihaimdinca** [comment]
I have a two floor home and experiencing some problems regarding connectivity. I do have a sufficient number of routers but some may be of poor quality (woox and ikea bulbs and sonoff zbmini relays) or may not be working well with aqara end devices. Anyway I am considering options and one if them may be to use a coordinator for each floor.

**Comment by mihaimdinca** [comment]
I guess, testing each will be the way forward.

**Comment by pvklink** [comment]
they all use the same MQTT, but with a different base topic
