### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by XenoUniv3rse** [Koenkk/zigbee2mqtt#19730]
### What happened?

Hi. 

I followed the sets on https://www.zigbee2mqtt.io/guide/installation/01_linux.html#starting-zigbee2mqtt to install Z2M on my raspberry pi. 

When i want to start the service with sudo npm start, i get the below error message. Can someone please assist me? 

> zigbee2mqtt@1.33.2 start
> node index.js

Zigbee2MQTT:info  2023-11-16 01:10:14: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-11-16.01-10-13' filename: log.txt
Zigbee2MQTT:info  2023-11-16 01:10:14: Starting Zigbee2MQTT version 1.33.2 (commit #311ea07)
Zigbee2MQTT:info  2023-11-16 01:10:14: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:error 2023-11-16 01:10:25: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-11-16 01:10:25: Failed to start zigbee
Zigbee2MQTT:error 2023-11-16 01:10:25: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-11-16 01:10:25: Exiting...
Zigbee2MQTT:error 2023-11-16 01:10:25: undefined

Thank you

### What did you expect to happen?

Z2M to start

### How to reproduce it (minimal and precise)

try to start it

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

no idea

### Adapter

Raspbee 2

### Debug log

Zigbee2MQTT:info  2023-11-16 01:10:14: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-11-16.01-10-13' filename: log.txt
Zigbee2MQTT:info  2023-11-16 01:10:14: Starting Zigbee2MQTT version 1.33.2 (commit #311ea07)
Zigbee2MQTT:info  2023-11-16 01:10:14: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:error 2023-11-16 01:10:25: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-11-16 01:10:25: Failed to start zigbee
Zigbee2MQTT:error 2023-11-16 01:10:25: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-11-16 01:10:25: Exiting...
Zigbee2MQTT:error 2023-11-16 01:10:25: undefined

**Comment by haegar33** [comment]
watch out for the proper device port !  In my case **/dev/serial0** (pointing to /dev/ttyS0) was successful
