### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee2mqtt#1973]
# Bug Report 
## What happened
UnhandledPromiseRejectionWarning TypeError: Cannot read property '0x000d6f0004d378e8' of null.
Z2M does not crash.
## How to reproduce it (minimal and precise)
Test bed running locally on a pi4 with lastest z2m dev build and only 1 device joined (attached database content).
Each time the contact door is opened or closed, z2m throw the error above.
Debug Info: https://pastebin.com/u9QQ98QR
zigbee2mqtt version: latest dev build
[database.txt](https://github.com/Koenkk/zigbee2mqtt/files/3612660/database.txt)
CC253X firmware version: latest source routing firmware for cc2531

**Comment by bochelork** [comment]
Still have the same error, Here it comes when a previously paired device which have been removed from database.db, sends a status update.

**Comment by Koenkk** [comment]
@ccorderod your issue should be fixed in latest dev

@bochelork can you provide the log of yours?
