### ISSUE TITLE
Sonoff TRVZB auto discovery not complete

### ISSUE THREAD

**Issue by stenleo** [Koenkk/zigbee2mqtt#19748]
### What happened?

Managed to add the valves to z2mqtt without issues, and they look right and work in the z2mqtt web interface, however they don't seem to report the correct auto discovery topics for Home Assistant to add them properly.

Only battery, battery low and child lock auto discovery topics are available.

<img width="470" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/25526859/2ab03816-80d9-40f2-b279-492ee2043ccf">

### What did you expect to happen?

I expected the auto discovery topics of the other settings to be included, climate, temperature etc.

### How to reproduce it (minimal and precise)

Pair the valve with z2mqtt

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20220219

### Adapter

Slaesh CC2652RB

**Comment by ReallyKrazyDev** [comment]
I can report the exact same issue, here are available data in Z2M 1.34.0 :
{
    "battery": 100,
    "battery_low": null,
    "child_lock": "UNLOCK",
    "closing_steps": 373,
    "frost_protection_temperature": 8,
    "idle_steps": 154,
    "linkquality": 255,
    "local_temperature": 21.7,
    "local_temperature_calibration": -3.2,
    "occupied_heating_setpoint": 20.5,
    "open_window": "OFF",
    "running_state": "idle",
    "system_mode": "heat",
    "update": {
        "state": "idle"
    },
    "update_available": false,
    "valve_closing_limit_voltage": 2783,
    "valve_motor_running_voltage": 1563,
    "valve_opening_limit_voltage": 1392
}

Sadly, in Home Assistant "local_temperature", "occupied_heating_setpoint", "running_state" and "system_mode" are missing.

Missing "local_temperature" and "occupied_heating_setpoint" reduces a lot the abilities of the system

Any idea on how to fix this ?

Versions :
Zigbee2MQTT [1.34.0]
ConBee2/RaspBee2
Zigbee-herdsman-converters 15.130.1
Zigbee-herdsman version 0.25.0

TRVZB Firmware 1.1.1
