### ISSUE TITLE
Hue White Filament Bulbs become unavailable

### ISSUE THREAD

**Issue by garv3** [Koenkk/zigbee2mqtt#19741]
### What happened?

I have two Philips Hue White Filament Bulbs (https://www.zigbee2mqtt.io/devices/8718699688882.html#philips-8718699688882) that do become unavailable very often (about once or twice each day). They simply stop reacting to actions.
The only way to make them respond again is to power cycle them.

I am using the Home Assistant add on and a Conbee II stick. All other zigbee devices (including other Philips Hue models) work just fine!

Any suggestions?
Thanks in advance! 

### What did you expect to happen?

The bulbs should work as expected.

### How to reproduce it (minimal and precise)

Well, nothing special. Pair these bulbs and use them for a while. 

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

0x26780700

### Adapter

Conbee II

**Comment by Ra72xx** [comment]
Same here for Nue/3A LXZB-02A. I have two devices of this kind, and both of them sooner or later go offline and have to be re-plugged. "Going offline" in this case means that sometimes also the hardware button on the device does no longer toggle the switch!
This didn't happen with my previous Conbee II-Setup and only started with SkyConnect / Z2M.
