### ISSUE TITLE
Tradfri GU10 lightbulbs unresponsive

### ISSUE THREAD

**Issue by cinnayyannic** [Koenkk/zigbee2mqtt#1974]
# Bug Report
## What happened
I have a really small test network with just 3 Tradfri GU10 lightbulbs and a single Xiaomi button switch. 

If i try to toggle the bulbs a few times something starts freezing and the following error message is shown:

> 9/14/2019, 3:12:05 PM - error: Publish 'set' 'state' to '0x000d6ffffe4c48f3' failed: 'Error: SRSP - AF - dataRequest after 6000ms'

I trigger the statechange manually and no script or scene is involved.

Since there are so many positive reviews of zigbee2mqtt and the CC2531 stick i really think there is something strange going on.  

I also tried the non Source Routing firmware and the latest master branch release (of zigbee2mqtt) without any success.

Is there anything i could to to narrow down the issue ?

## What did you expect to happen

Manually changing the state of a lightbulb should not cause the nework to freeze after 2-3 state toggles.

## How to reproduce it (minimal and precise)

Pair Tradfri GU10 lightbulb (on latest firmware) with the CC2531 stick and toggle the bulb a few times.

## Log

9/14/2019, 3:11:58 PM - debug: Received MQTT message on 'zigbee2mqtt/0x000d6ffffe4c48f3/set' with data '{"state": "OFF"}'
9/14/2019, 3:11:58 PM - debug: Publishing 'set' 'state' to '0x000d6ffffe4c48f3'
9/14/2019, 3:11:59 PM - debug: Received MQTT message on 'zigbee2mqtt/0x000d6ffffe645334/set' with data '{"state": "OFF"}'
9/14/2019, 3:11:59 PM - debug: Publishing 'set' 'state' to '0x000d6ffffe645334'
9/14/2019, 3:12:00 PM - debug: Received MQTT message on 'zigbee2mqtt/0x000d6ffffe5e7dc6/set' with data '{"state": "ON"}'
9/14/2019, 3:12:00 PM - debug: Publishing 'set' 'state' to '0x000d6ffffe5e7dc6'
9/14/2019, 3:12:00 PM - debug: Received MQTT message on 'zigbee2mqtt/0x000d6ffffe4c48f3/set' with data '{"state": "ON"}'
9/14/2019, 3:12:00 PM - debug: Publishing 'set' 'state' to '0x000d6ffffe4c48f3'
9/14/2019, 3:12:05 PM - error: Publish 'set' 'state' to '0x000d6ffffe4c48f3' failed: 'Error: SRSP - AF - dataRequest after 6000ms'
9/14/2019, 3:12:05 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x000d6ffffe4c48f3' failed: 'Error: SRSP - AF - dataRequest after 6000ms'","meta":{"entity":"0x000d6ffffe4c48f3"}}'
9/14/2019, 3:12:05 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe645334', payload '{"state":"OFF","linkquality":23,"brightness":254,"color_temp":330,"color":{"x":0.4599,"y":0.4106}}'
9/14/2019, 3:12:05 PM - debug: Received Zigbee message from '0x000d6ffffe645334' of type 'attributeReport' with data '{"onOff":0}' from endpoint 1 with groupID 0
9/14/2019, 3:12:05 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe645334', payload '{"state":"OFF","linkquality":36,"brightness":254,"color_temp":330,"color":{"x":0.4599,"y":0.4106}}'
9/14/2019, 3:12:05 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe5e7dc6', payload '{"state":"ON","color_temp":323}'
9/14/2019, 3:12:05 PM - info: MQTT publish: topic 'zigbee2mqtt/0x000d6ffffe4c48f3', payload '{"state":"ON","linkquality":28,"brightness":254,"color_temp":330,"color":{"x":0.4599,"y":0.4106}}'

## Debug Info
-> reporting feature disabled
-> queue: delay: 250 simultaneously: 3

zigbee2mqtt version: Version 1.6.0 (commit #f5463db)
CC253X firmware version: 20190619 with Source routing

**Comment by Koenkk** [comment]
Can you provide the log when running with `DEBUG=* npm start`, please provide the log on pastebin.com and link it here.
