### ISSUE TITLE
[New device support]: Wall Switch MOES ZS-B-US

### ISSUE THREAD

**Issue by tenkaibr** [Koenkk/zigbee2mqtt#19779]
### Link

https://pt.aliexpress.com/item/1005006160698904.html?spm=a2g0o.cart.0.0.47467f06huHrFp&mp=1&gatewayAdapt=glo2bra

### Database entry

Dont have it

### Comments

Does anyone know if this device is compatible? If not, would it be possible to include it? 

Wall Switch MOES ZS-B-US

**Comment by DannyFeliz** [comment]
I hope you guys can add support for this 🙏🏻
