### ISSUE TITLE
Trying to set up SONOFF SNZB-06P timeout - what's the format?

### ISSUE THREAD

**Issue by fribse** [Koenkk/zigbee2mqtt#19771]
### What happened?

I've set up the SONOFF SNZB-06P in Z2M, it is recognized nicely.
There is only one topic in 'Exposes', and that is occupancy

There is no Sensitivity Setting and there is no Timeout setting exposed.
Both of these are available in Sonoff's own Zigbee bridge.
There is some explanation in 'Settings (specific)' that explains
Sends a message after the last time no occupancy (occupancy: false) was detected.
So it looks like you can have it send multiple messages.
It also explains that it should be set to an object like [10,60] and it will then send a message after 10s and after 60s.
But the field shown does not accept objects, only numbers, and setting it to a number doesn't change anything.

### What did you expect to happen?

That I could enter [10] and it would timeout after 10s, or [60] and it would time out after 60s.
When I saw the device was supported, I actually expted it to support the parameters exposed to eWeLink though Sonoff ZBBridge.

### How to reproduce it (minimal and precise)

Just add it to Z2M

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20230507

### Adapter

TubesZB CC2652P2 POE adapter

**Comment by Busta999** [comment]
Same issue.

Tested 2 so far, it reports occupancy indefinitely even when placed in an empty box.

occupancy is permanently on

**Comment by tjeffree** [comment]
@Busta999 I got a couple delivered today. They do work ok at reporting occupancy - it's annoying that I can't adjust the timeout yet so they don't "clear" for 60 seconds.

I did have to reset one a couple of times closer to a coordinator to get it to report something other than "N/A". Press and hold the button for ~5 seconds.

**Comment by nadi1971** [comment]
Same here.
I tried to configure it on both Z2M and ZHA, the status is always occupancy detected

**Comment by ramyaladdin** [comment]
same thing here ,
Its always showing occupancy detected, I did reset it for a couple of times and it gets configured but then shows offline all the time.

**Comment by Busta999** [comment]
I have ordered a Sonoff Hub to test the sensors on. 

Identify if I have bad sensors or an issue in zigbee2MQTT.

should have an answer by Wednesday this week.

**Comment by yanhao666** [comment]
The minimum timeout time can be set to 30 seconds, both ZHA and Z2M can configure it.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42955921/018159f2-98c5-4fad-8996-49f8bd6f5a5e)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42955921/8e1d4764-104c-4d61-8de5-903362c16356)
And it will be optimized to 15s in the V1.0.5 firmware, sonoff is working on it. OTA may be available in the coming weeks.

**Comment by yanhao666** [comment]
> Same issue.
> 
> Tested 2 so far, it reports occupancy indefinitely even when placed in an empty box.
> 
> occupancy is permanently on

In fact, microwave radar can penetrate most non-metallic materials, including walls. Moreover, it has reflection capabilities, meaning that objects in motion behind the sensor or outside of the room may trigger it.

**Comment by Busta999** [comment]
> > Same issue.
> > Tested 2 so far, it reports occupancy indefinitely even when placed in an empty box.
> > occupancy is permanently on
> 
> In fact, microwave radar can penetrate most non-metallic materials, including walls. Moreover, it has reflection capabilities, meaning that objects in motion behind the sensor or outside of the room may trigger it.

Good point, I tested the device in a closed cardboard box with sensor pointing away from towards a wall and it continued to report occupancy.


Overnight the sensor reset to clear, when the room was unoccupied.

I have just returned to the room and the sensor did take 60+ seconds to report occupied.

It went to clear very quickly after leaving the room,  No occupancy is set to 1 second.


I’ll have the sonoff hub hopefully today and will test further.

But your point is valid and I suspect correct, the device was continuing to detect presence, even while sat in cardboard box.

If it continues to function as this morning’s testing indicates then this device will perform as desired.

Use a PIR sensor to detect entrance into the space to turn on lights, then use the Sonoff to detect ongoing presence to stop lights from going off.

My main use case is in rooms where people may be still for longer periods than a PIR sensor time out period, for me Lounge, Kitchen, Office.

At this stage I am not so sure either sensor of zigbee2MQTT is malfunctioning, I suspect the sensor is just slow identifying and reporting occupancy, which for its price, is ok and workable.

Will perform further testing on zigbee2MQTT and sonoff hub.

**Comment by fribse** [comment]
> I have ordered a Sonoff Hub to test the sensors on.
> 
> Identify if I have bad sensors or an issue in zigbee2MQTT.
> 
> should have an answer by Wednesday this week.

I tested with one of these, and in that I can set sensitivity and duration, so it would be nice to be able to set both of these through "Exposes" or at least in the "settings (specific)"

**Comment by fribse** [comment]
> I have ordered a Sonoff Hub to test the sensors on.
> 
> Identify if I have bad sensors or an issue in zigbee2MQTT.
> 
> should have an answer by Wednesday this week.

As I wrote, it was set up with that already, and it works, I can also see it showing clear now, so I guess it's working. And thankyou to all you other guys about how to interpret the explanation on the 'Time' in Settings Specific, seems like the text is simply wrong.

**Comment by Pedro-vk** [comment]
Same issue here, the documentation is not very clear about how to configure the timeout format and, apart from that, it always emits a `{"occupancy": true}`

**Comment by evelant** [comment]
What's needed to allow zigbee2mqtt to configure the sensitivity of the sensor? The product page lists "Three levels of sensitivity (2.5m, 3.5m, 4m)" but there's no way to configure it yet in z2m

**Comment by nanderson97651** [comment]
> What's needed to allow zigbee2mqtt to configure the sensitivity of the sensor? The product page lists "Three levels of sensitivity (2.5m, 3.5m, 4m)" but there's no way to configure it yet in z2m

In addition the marketing materials mention some sort of lux sensor but I don't see it exposed either.

**Comment by Busta999** [comment]
In the Sonoff Hub you can automate against Luminance High/Low with no configuration of thresholds.

I’ll check the exact field names.

**Comment by nanderson97651** [comment]
> In the Sonoff Hub you can automate against Luminance High/Low with no configuration of thresholds.

I'm using Z2M with SkyConnect and Home Assistant so no Sonoff Hub anywhere in my system.  I was hoping to still be able to automate based on ambient brightness.

**Comment by Busta999** [comment]
The hope is that the basic luminance along with presence sensitivity will be added to zigbee2MQTT, I am pretty new to zigbee2MQTT so not yet sure how that happens

**Comment by nanderson97651** [comment]
I'm also new to Z2M, switching from ZHA.  Happy to help where I can to get these added but it's pretty new territory for me.

**Comment by yanhao666** [comment]
> What's needed to allow zigbee2mqtt to configure the sensitivity of the sensor? The product page lists "Three levels of sensitivity (2.5m, 3.5m, 4m)" but there's no way to configure it yet in z2m

The sensitivity can be configured here.    "1" means 2.5m, "2" means 3.5m, "3" means 4m
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42955921/5e46aef1-af76-4d20-a200-e70a88a01ee2)

**Comment by evelant** [comment]
@yanhao666 thanks! How did you find this information? Or rather, where do you find the information about which clusters/attributes can be used to configure any particular device?

**Comment by fribse** [comment]
> 
> The sensitivity can be configured here. "1" means 2.5m, "2" means 3.5m, "3" means 4m ![image](https://user-images.githubusercontent.com/42955921/285097149-5e46aef1-af76-4d20-a200-e70a88a01ee2.png)

Gold information, thankyou @yanhao666 !

**Comment by evelant** [comment]
Hmm it also seems like binding isn't working properly with this sensor. When I try to bind it to a group of lights it doesn't turn them on/off. There's seemingly no way to bind to the on/off cluster of the target. Trying to bind to an individual bulb (ikea tradfri in this case) only shows the "Identify" cluster.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/858965/6ddf56c3-8b6c-4174-b113-4c87470b50cd)

**Comment by KmanOz** [comment]
> > What's needed to allow zigbee2mqtt to configure the sensitivity of the sensor? The product page lists "Three levels of sensitivity (2.5m, 3.5m, 4m)" but there's no way to configure it yet in z2m
> 
> The sensitivity can be configured here. "1" means 2.5m, "2" means 3.5m, "3" means 4m ![image](https://private-user-images.githubusercontent.com/42955921/285097149-5e46aef1-af76-4d20-a200-e70a88a01ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTY5NzgsIm5iZiI6MTcwMTI1NjY3OCwicGF0aCI6Ii80Mjk1NTkyMS8yODUwOTcxNDktNWU0NmFlZjEtYWY3Ni00ZDIwLWEyMDAtZTcwYTg4YTAxZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDExMTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjEwM2E5ZWU0YjAzNzM2YTU1ZmQ1YWY0ZmQ3NjVjYzJjZWNhMmE5ZmE0MjcyY2RkZjk0MDIwZDcyYTg2MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vN7zwC4ocZNmtDL2IjPV-AkV73d5T17MitTLrTjk32s)

Yes this worked for me. Thank you.

**Comment by zaberxxx** [comment]
Mine showing occupied permanently.
I tried chaging the ultrasonicOToUDelay to 30, and ultrasonicUToOThreshold to 1, still no luck.
Will repairing the device to Z2M help?
The firmware is still 1.0.3 and I don't know how to upgrade to 1.0.5 (I don't own a sonoff hub), no upgrade option in Z2M OTA section.

**Comment by Bod1985** [comment]
> Mine showing occupied permanently.
> 
> I tried chaging the ultrasonicOToUDelay to 30, and ultrasonicUToOThreshold to 1, still no luck.
> 
> Will repairing the device to Z2M help?
> 
> The firmware is still 1.0.3 and I don't know how to upgrade to 1.0.5 (I don't own a sonoff hub), no upgrade option in Z2M OTA section.

I had to re-pair mine a few times to make them work. Then when they started working they were fine until I turned off power and rebooted them.

I don't believe 1.0.5 is available yet. 1.0.3 is the current firmware I think

**Comment by linkedupbits** [comment]
> Hmm it also seems like binding isn't working properly with this sensor. When I try to bind it to a group of lights it doesn't turn them on/off. There's seemingly no way to bind to the on/off cluster of the target. Trying to bind to an individual bulb (ikea tradfri in this case) only shows the "Identify" cluster.
> 
> ![image](https://private-user-images.githubusercontent.com/858965/285608974-6ddf56c3-8b6c-4174-b113-4c87470b50cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NjIxODksIm5iZiI6MTcwMTQ2MTg4OSwicGF0aCI6Ii84NTg5NjUvMjg1NjA4OTc0LTZkZGY1NmMzLThiNmMtNDE3NC1iMTEzLTRjODc0NzBiNTBjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQyMDE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjM3MmQ4ZjVjNzkwNTlhZDIwZWE0ODM2N2NjNjlhYzJkYzdkOWIwOTRjMzJmYmRmYzA2NzAzMzMzYzM5NjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yv9B-luoXkxHMUXKOfeCB2AsWxaXakqZgutl-mtHya8)

I raised a ticket with Sonoff, got this reply:
Sorry, now we could not support this function.



Regards,
Frankie in SONOFF

**Comment by KmanOz** [comment]
> Mine showing occupied permanently. I tried chaging the ultrasonicOToUDelay to 30, and ultrasonicUToOThreshold to 1, still no luck. Will repairing the device to Z2M help? The firmware is still 1.0.3 and I don't know how to upgrade to 1.0.5 (I don't own a sonoff hub), no upgrade option in Z2M OTA section.

Mine did that as well. It's very sensitive. I moved the position of mine on the wall and has worked well since.

**Comment by evelant** [comment]
@linkedupbits lol thanks for trying, the product page says `【Local Smart Scene】Scene linkage between Zigbee devices can be executed normally even if there is no internet connection.` which I took to mean it supports bindings. Not sure what else it could mean.

**Comment by Bod1985** [comment]
Zigbee2MQTT update has enabled OTA for these. 

I've just updated mine to 1.0.5, hopefully there's some improvement. 

Does anyone know if/where Sonoff publish firmware changelogs?

**Comment by Bod1985** [comment]
> > Zigbee2MQTT update has enabled OTA for these.
> > I've just updated mine to 1.0.5, hopefully there's some improvement.
> > Does anyone know if/where Sonoff publish firmware changelogs?
> 
> How did you update it? When I try to check for an update it says "Failed to check if update available for 'Office presence sensor' (Unexpected token � in JSON at position 0)".

Strange, all three of my sensors updated without error. Sorry I don't have any suggestions as I haven't done many Z2M OTA upgrades

**Comment by Bod1985** [comment]
> What does
> 
> > > > Zigbee2MQTT update has enabled OTA for these.
> > > > I've just updated mine to 1.0.5, hopefully there's some improvement.
> > > > Does anyone know if/where Sonoff publish firmware changelogs?
> > > 
> > > 
> > 
> > Strange, all three of my sensors updated without error. Sorry I don't have any suggestions as I haven't done many Z2M OTA upgrades
> 
> What does the OTA settings page look like in your Z2M?

Like this, I’m running 1.34.0

![IMG_0698](https://github.com/Koenkk/zigbee2mqtt/assets/1529155/e00580a0-587c-40c2-aab8-35c86dd19c00)

**Comment by hjpfourie** [comment]
When I read or write the settings, I get a visible indictaor that it has either read, or set the values as per screenshot.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/111149833/8af0bb86-e213-47af-b06a-92835d7d92b0)

**Comment by evelant** [comment]
@zaberxxx @hjpfourie There's a silly bug in the UI. If you have filtered the logs tab then messages don't show up in the dev console. Go to the logs tab and make sure log level is set to "info" or "debug" and then you will see readouts in the dev console.

**Comment by yanhao666** [comment]
> Still not able to make mine sensor working properly. Tried numerous times of repairing, off power, change position, upgrade to v1.0.5, reboot zigbee2mqtt service, still not able to get it work... I also tried change settings is dev console but is it normal that when I write the new number into ultrasonicUToOThreshold, there's no indicator on page showed that I successfully wrote in?
> 
> EDIT: I later tried setting the sensor in a blank space with no moving parts to interfere, and it works properly. This sensor is too sensitive and even the bathroom ventilator/dryer will trigger it.

@zaberxxx After configuring the sensitivity, did it work for you? I mean, in the original place.

**Comment by KmanOz** [comment]
I found that after I upgraded to 1.0.5 I have to re-write the register as their firmware seems to have defaulted it back to 3

**Comment by barcelona92** [comment]
> What does
> 
> > > > Zigbee2MQTT update has enabled OTA for these.
> > > > I've just updated mine to 1.0.5, hopefully there's some improvement.
> > > > Does anyone know if/where Sonoff publish firmware changelogs?
> > > 
> > > 
> > > How did you update it? When I try to check for an update it says "Failed to check if update available for 'Office presence sensor' (Unexpected token � in JSON at position 0)".
> > 
> > 
> > Strange, all three of my sensors updated without error. Sorry I don't have any suggestions as I haven't done many Z2M OTA upgrades
> 
> What does the OTA settings page look like in your Z2M?
> 
> ![image](https://private-user-images.githubusercontent.com/22861530/287555352-3945430e-149b-4108-af7b-75af4e82fa08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjIzMDgsIm5iZiI6MTcwMjEyMjAwOCwicGF0aCI6Ii8yMjg2MTUzMC8yODc1NTUzNTItMzk0NTQzMGUtMTQ5Yi00MTA4LWFmN2ItNzVhZjRlODJmYTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDExNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MTIyOGZkMTY5NDU3NzE2ODNlNmRmYTBkMzVkZWFkYzg4NjY2YWUzOTk0YzJlZWYwZjIyY2EzYTg0MTlmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfKEwz4draQ7Kbl6cn1g8i92s-8N9ujV-fWrY8Z0zT8)

Hi,

I have the same problem appear erro with check for update in SNZB-06  the error:
Failed to check if update available for 'Pres entrance' (localIndex.concat(...).map is not a function)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/33433738/eb40ea0c-418b-4410-b596-aee9035dee6c)

**Comment by Typ1er** [comment]
I can neither read nor write the sensor. what am I doing wrong?
![Bildschirmfoto 2023-12-12 um 16 04 38](https://github.com/Koenkk/zigbee2mqtt/assets/39628986/a471e423-2898-4bb7-b71e-4f0c2d025507)

**Comment by hjpfourie** [comment]
> I can neither read nor write the sensor. what am I doing wrong? ![Bildschirmfoto 2023-12-12]

You haven't selected the attribute, only the cluster. Select the attribute you want to read or write.

**Comment by zaberxxx** [comment]
> > Still not able to make mine sensor working properly. Tried numerous times of repairing, off power, change position, upgrade to v1.0.5, reboot zigbee2mqtt service, still not able to get it work... I also tried change settings is dev console but is it normal that when I write the new number into ultrasonicUToOThreshold, there's no indicator on page showed that I successfully wrote in?
> > EDIT: I later tried setting the sensor in a blank space with no moving parts to interfere, and it works properly. This sensor is too sensitive and even the bathroom ventilator/dryer will trigger it.
> 
> @zaberxxx After configuring the sensitivity, did it work for you? I mean, in the original place.

It works 95% of the time, but sometime false recognition still occurs.

**Comment by metec22** [comment]
This device is really disappointing. Is anyone else's sensor behaving like a motion sensor? It's about 2-3 ft away from me and if I sit still, it will stop showing presence (if it's not stuck showing presence for hours when no one is present). I have two of them, one on firmware 	1.0.5 and one on 1.0.3. Both behave the same way.

**Comment by yanhao666** [comment]
> This device is really disappointing. Is anyone else's sensor behaving like a motion sensor? It's about 2-3 ft away from me and if I sit still, it will stop showing presence (if it's not stuck showing presence for hours when no one is present). I have two of them, one on firmware 1.0.5 and one on 1.0.3. Both behave the same way.

@metec22 It seems possible that the radar microwave has been interfered with. Are there metal objects blocking the middle? Or using another radar nearby at the same time?

**Comment by evelant** [comment]
HA 2023.12.x seems to have issues with zigbee, devices go "unavailable" in HA even though z2m is still communicating with them. Other than when the network is working smoothly I don't have any of those issues with these sensors. They respond fast and state stays "occupied" when people are still. I set msOccupancySensing -> ultrasonicUToOThreshold to 3 on all of mine. If you have two or more of the sensors too close to each other or pointed toward each other they can interfere. Any other radar based devices might interfere as well (I think some security systems?).

**Comment by metec22** [comment]
Weird. I don't have any metal objects anywhere near the sensor. I only used one sensor at a time in the same spot. It's also much slower than a motion sensor I was hoping to replace. When I walk into the room, it takes about 2-3 seconds for the light to come on. On the updated sensor, I set the time out to 30s and tried all three settings for threshold. On the one with the older firmware, I haven't changed anything. Maybe there is some interference in the room but nothing obvious.

**Comment by fribse** [comment]
@metec22 , for me it sounds defective. I have three mw sensors on top of each other while testing, they all work perfectly, and with the released notes on how to adjust sensitivity duration, and the firmware at 1.0.3 it works quite nicely.

**Comment by Alfy1080** [comment]
> This device is really disappointing. Is anyone else's sensor behaving like a motion sensor? It's about 2-3 ft away from me and if I sit still, it will stop showing presence (if it's not stuck showing presence for hours when no one is present). I have two of them, one on firmware 1.0.5 and one on 1.0.3. Both behave the same way.

I received 6 of these sensors yesterday. I've set up one per room in z2m and upgraded the firmware to v1.0.5. One of them is in a 5 meter long hallway with no interference source whatsoever, but the detection time sometimes is instantaneous and sometimes it takes about 3 seconds to detect presence.
Another one of these sensors is in my bedroom and while awake and present in the room i see that it properly stays as "Detected" all the time until i leave the room. However, overnight when both me and my wife were sleeping in that bedroom, the sensor switched between "Detected" and "Clear" every few minutes. This has happened with detection sensitivity set to high. If i set it to medium or low it would switch to "Clear" even when I am awake on my laptop in bed. Seems an awful lot like a motion sensor at this point. 
I've now realised that the nest hub that i also have in the bedroom might interfere with the presence sensor as it uses radar to detect gestures and monitor sleep so i've turned off these features, but to me it sounds like that kind of interference should keep the presence sensor in "Detected" state instead of making it think the room is clear. Anyway I'll get back with new info after testing it overnight.

**Comment by Alfy1080** [comment]
I have another update. The bedroom still behaves pretty much the same, but i realised that the behaviour is very much related to the positioning of the sensor. I got much better results when placing the sensors about 1.5 m high on the wall. The bedroom one still stops detecting me from time to time but the bathroom one is now working flawlessly since i repositioned it. I will keep playing with it and report back, but as far as i can tell this is a good sign not to lose faith in this sensor. ATM 5 out of 6 sensors work exactly as expected.

**Comment by rjmcfadd** [comment]
Mine will work amazingly for a little while then go back to detected for hours at a time.

**Comment by johnrobertcobbold** [comment]
I also had a few issues when I installed mine but everything has been flawless since I moved it to a slightly different place. It looks like objects / walls were initially bouncing back the waves. I now wish that the lux could be updated at regular intervals.. It now detects my presence but won't update the lux while I am there, effectively preventing any automation from switching on/off the lights if and when it later gets dark (sunset) / brighter (sunrise)

**Comment by Alfy1080** [comment]
> Mine will work amazingly for a little while then go back to detected for hours at a time.

This happened to me with sensors that were placed very high on the wall and in the corners of the rooms or with the sensor pointing downwards. I found that the sweet spot for me is around 1.5m height, as far from the corners of the wall as possible and with the sensor pointing straight ahead.

For the light intensity issues, i'm just using the data from other light sensors around my home until the ones in the presence sensor get better. The fact that the light intensity only updates upon presence detection is quite stupid especially for a mains powered device that could send updates to z2m as often as it needed without worrying about battery life.

**Comment by evelant** [comment]
[I ripped one open](https://www.reddit.com/r/homeassistant/comments/184svmt/sonoff_snzb06p_teardown/) (for science!) and the photodiode is on the radar board not the mainboard so it may be a firmware thing that it doesn't get illuminance updates until the radar controller sends it to the main board.

**Comment by nanderson97651** [comment]
> so it may be a firmware thing that it doesn't get illuminance updates until the radar controller sends it to the main board

This is why I opened a support ticket with Sonoff directly asking if it can be changed in a future firmware update.  It may be a long shot but they've already updated fw once to reduce the cooldown.  I recommend more people submit a request [here](https://sonoff.tech/support/) to decouple photodetector updates from radar updates.

**Comment by yanhao666** [comment]
> I have another update. The bedroom still behaves pretty much the same, but i realised that the behaviour is very much related to the positioning of the sensor. I got much better results when placing the sensors about 1.5 m high on the wall. The bedroom one still stops detecting me from time to time but the bathroom one is now working flawlessly since i repositioned it. I will keep playing with it and report back, but as far as i can tell this is a good sign not to lose faith in this sensor. ATM 5 out of 6 sensors work exactly as expected.

Maybe, when the sensor is close to the chest of a person, the detection of presence/breathing will be more effective.

**Comment by charlidog** [comment]
There is a useful update [here on the sonoff website](https://sonoff.tech/product-review/tutorial/snzb-06p-firmware-upgrade-and-home-assistant-operation-guide/#2) - the latest firmware 1.0.6 - seems to work well for me

**Comment by Alfy1080** [comment]
> There is a useful update [here on the sonoff website](https://sonoff.tech/product-review/tutorial/snzb-06p-firmware-upgrade-and-home-assistant-operation-guide/#2) - the latest firmware 1.0.6 - seems to work well for me

I can't see any mention of v1.0.6 on that page. Also how did you update? I have v1.0.5 in Z2M and checking for new versions doesn't give me anything.

**Comment by charlidog** [comment]
I did the update manually as per the OTA update ZHA section
>Waiting for the firmware to update automatically may take a considerable amount of time. We recommend proceeding with a manual update. To begin, you’ll need to copy the device’s IEEE address.

**Comment by evelant** [comment]
There is no version 1.0.6 as far as I can tell? 1.0.5 is the latest

**Comment by hjpfourie** [comment]
No option to manually update through Z2M from what I can tell. Z2M also doesn't detect a new firmware update (yet).

**Comment by kennethpangky** [comment]
> There is no version 1.0.6 as far as I can tell? 1.0.5 is the latest

Mine came ootb with 1.0.6. Also having the same issue of being stuck on motion detected. Also, it doesn't even expose the occupany entity.

**Comment by Alfy1080** [comment]
> > There is no version 1.0.6 as far as I can tell? 1.0.5 is the latest
> 
> Mine came ootb with 1.0.6. Also having the same issue of being stuck on motion detected. Also, it doesn't even expose the occupany entity.

The motion entity is the occupancy entity. You just have to change the entity type in HA.

**Comment by kennethpangky** [comment]
> > > There is no version 1.0.6 as far as I can tell? 1.0.5 is the latest
> > 
> > 
> > Mine came ootb with 1.0.6. Also having the same issue of being stuck on motion detected. Also, it doesn't even expose the occupany entity.
> 
> The motion entity is the occupancy entity. You just have to change the entity type in HA.

I see. Because for those who have it connected to ZHA it shows both motion and occupancy. And apparently the occupancy entity works but the motion one doesn't, which is why I was looking for that entity.

If it's a matter of just changing the entity type then it wouldn't work anyway. It's always stuck in detected state.

**Comment by Sr-psycho** [comment]
Anyone whose sensor is stuck in the “detected” state should go to Settings (specific) and select the required time in minutes after which the sensor will report that the object is missing. The sensor with this parameter has been working for the second week without errors. HA rebooted many times during this time. All OK.

**Comment by vcadieux** [comment]
> Guys, whose sensor is stuck in the “detected” state should go to Settings (specific) and select the required time in minutes after which the sensor will report that the object is missing. The sensor with this parameter has been working for the second week without errors. HA rebooted many times during this time. All OK. PS The Occupancy timeout parameter had no effect. FW 1.0.5 Zigbee2MQTT v. 1.35.3-1

What would be the setting in ZHA to change for this ? I have one Sonoff stuck in detected out of 4. I am not using Zigbee2MQTT.

I installed V1.0.5 when I got them.

**Comment by Sr-psycho** [comment]
> What would be the setting in ZHA to change for this ? I have one Sonoff stuck in detected out of 4. I am not using Zigbee2MQTT.
> 


Unfortunately, I can’t tell you how to configure SONOFF SNZB-06P in ZHA.

**Comment by BroncoDJ** [comment]
Background:

I received a few SNZB-06P sensors (Firmware: 0x00001006) yesterday and have already tested a couple on HAOS. They connect without problems and everything seems to be working fine.

Issue:

I suspect that many people are facing the same "problem". The sensor is so sensitive that it is sometimes impossible to block its detection even when placed in a metal box. It detects human presence even through the smallest crack in a slightly opened metal box.

Recommendation:

Before complaining about the permanent "Detected state", I recommend testing the sensor's operation by moving away from it. Even on "Low" detection sensitivity, it "sees" people through walls, reacts to nearby animals, etc. I tried to close it in a cabinet, and it still "sees" too much.

Request:

Realistically, there is a need for a lower sensitivity level than "Low". If anyone has managed to further reduce its sensitivity, please share your solution.. 

Conclusion:

The SNZB-06P motion sensor is a great product, but its high sensitivity can be a problem in some cases. I hope Sonoff will consider adding a lower sensitivity level in future firmware updates.

**Comment by Sr-psycho** [comment]
A sensor with firmware 1.06 will get stuck, unlike 1.05, under the same conditions.

**Comment by Fannangir** [comment]
Same behavior.
The sensor is actually stuck on occupied, set at Low.
Unfortunately, didn't find a solution to reduce sensitivity :(.

**Comment by BroncoDJ** [comment]
To achieve more precise sensor operation, I direct the sensors not directly at the monitored space, but at a 45-degree angle to the ceiling from the door. This makes the sensor sensitivity tolerable and reduces the number of excessive detections.

**Comment by i-m-d** [comment]
I have two SNZB-06P, one with zigbee2mqtt+ha and other in other home with Amazon Alexa Studio (with zigbee hub), both are in the bath (in their respective homes) to swith on/off the light.

With zigbee2mqtt+ha works rather well, may be delay 1 second to light up (perhaps moving orientation works better) and the 15 seconds delay i would prefer 10 or 5 seconds, the light keeps on to much for me.

The problem is with Amazon Alexa Studio, the 80% percent of times do no detect anything so the light do not turn on, besides Alexa/hub APP do not permit anything and the delay is 60 seconds which for me is too much.

Any help or tip ? 
i know this it is for zigbee2mqtt.

**Comment by prahal** [comment]
> > Guys, whose sensor is stuck in the “detected” state should go to Settings (specific) and select the required time in minutes after which the sensor will report that the object is missing. The sensor with this parameter has been working for the second week without errors. HA rebooted many times during this time. All OK. PS The Occupancy timeout parameter had no effect. FW 1.0.5 Zigbee2MQTT v. 1.35.3-1
> 
> What would be the setting in ZHA to change for this ? I have one Sonoff stuck in detected out of 4. I am not using Zigbee2MQTT.
> 
> I installed V1.0.5 when I got them.

I believe the setting is the attribute " ultrasonic_u_to_o_delay (id: 0x0021) " in cluster "OccupancySensing (Endpoint id: 1, Id: 0x0406, Type: in)". Its default read value is "0", I will try setting it to 1 (if time is in minutes, and if "0" does not mean instantaneous, but the default value, it might help). TO access these settings in ZHA you click on the three dots button in the deviceinfo section of the device in Settings
I guess u_to_o means unoccupied to occupied (in minutes?) (while o_to_u was the opposite, but in seconds)
