### ISSUE TITLE
Vimar 14592.0 not report status to Home Assistant

### ISSUE THREAD

**Issue by ontirius** [Koenkk/zigbee2mqtt#19799]
### What happened?

Hi, I have 5 vimar 14592.0 integrated in HA with conbee II and zigbee2mqtt, all working perfectly until I upgraded zigbee2mqtt to the latest release 1.33. 2, now on the interface of zigbee2mqtt, the 5 vimar switches work, I see their status and can change it without any problem, only on HA I don't see their status and I can't even change it (I attach two screenshot, one for zigbee2mqtt interface in which you can see the correct status, and the presence of button switch to change the status, and one for the home assisntance intervace, in which you are able to see that is showed as "disconnect" an no actions available to change the status), they appear as devices, if I change the name on zigbee2mqtt the name also updates on HA, but there is no way to change\see the status.
I have already tried removing the MQTT integration on HA and reinstalling it, unfortunately without success.
Can you please verify this problem?
Thank you very much!
Note: all other zigbee devices (occupancy, temp, luminosity sensors) work without problems, I see them correctly on HA
![luce esterna lato sala zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/assets/21127266/9cdc8051-4bac-4213-8b98-cfeda77a5cc7)
![luce esterna lato sala ha](https://github.com/Koenkk/zigbee2mqtt/assets/21127266/3081a194-5741-464c-a99e-589ede931e39)

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

**Comment by ontirius** [comment]
Hi, any news about that?

**Comment by ontirius** [comment]
Hi all, are there some news?

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following external converter: https://gist.github.com/Koenkk/49608776b57009e68d2e350b21f40c45

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by ontirius** [comment]
Hi Koenkk, many thanks for your support.
I did it, create a new file ext_converter.js inside folder of zigbee2mqtt, in that folder also exists the configuration.yaml, and I added to configuration.yaml the two rows:

external_converters:
   - ext_converter.js

Note: I added this two rows below section experimental: {} and before the section frontend:

I restarted zigbee2mqtt with command "docker-compose restart zigbee2mqtt"

I waited a few minutes... But the situation is still the same. On zigbee2mqtt interface all zigbee devices are see properly, and I can change their status, also vimar devices, but in HA I am able to see only this:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/21127266/5e85b43f-90b8-4650-b5ff-b9abe7b01c35)

Just to translate from Italy: "has become unknown" means "has become unknown", and as you can see no actions are available.

Maybe I wrong to configure the configuration.yaml? I need to put the two rows in a proper position in configuration.yaml?
Many thanks for your patience!
Best regards
Giuseppe

**Comment by Koenkk** [comment]
Can you try with z2m 1.34.0 and the latest HA?

**Comment by ontirius** [comment]
Hi Koenkk,
many thanks for your support! Fixed with upgrade to HA 2023.9.2!
Best regards
Giuseppe
