### ISSUE TITLE
BTicino K4570CWI recognized as Legrand 064873 and impossible to OTA update

### ISSUE THREAD

**Issue by syntesys87** [Koenkk/zigbee2mqtt#19796]
### What happened?

Hello,

I have a couple of BTicino K4570CWI connected to my Z2M instance, but they are recognized as Legrand 064873 and it's impossible to start OTA update with the error _Update of 'Comando Terrazza' failed (Device didn't respond to OTA request)_.

Already tried to remove battery and reset without success.

### Zigbee2MQTT version

1.33.2-dev commit: 5889cdd

### Adapter firmware version

7.3.1.0 build 176

### Adapter

EZSP v12 SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Debug log

Info 2023-11-21 08:30:55MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Comando Terrazza"},"error":"Update of 'Comando Terrazza' failed (Device didn't respond to OTA request)","status":"error","transaction":"4d3o3-1"}'
Error 2023-11-21 08:30:55Update of 'Comando Terrazza' failed (Device didn't respond to OTA request)

**Comment by syntesys87** [comment]
Same problem with 1.33.4.

**Comment by ster1um** [comment]
confirm the problem, I change the battery and pair direct to coordinator, it's impossible to update.
`Update of 'Comando Entra E Esci' failed (Device didn't respond to OTA request)`

**Comment by ster1um** [comment]
Update disappeared from z2m.

**Comment by Bartok92** [comment]
ciao come sei riuscito a collegare l'entra e esci tramite zigbee ?

**Comment by dinukro** [comment]
Hello, please let me know how I can associate K4570CWI to z2m.

Thank you

**Comment by lucaam** [comment]
@syntesys87 any feedback on how you connected this device to z2m?

**Comment by syntesys** [comment]
The issue is resolved and working on latest Z2M version.

**Comment by lucaam** [comment]
> The issue is resolved and working on latest Z2M version.

Yeah but I wanted to ask how you managed to pair it since seems that there is no documentation about it (not even showed as supported). I have one of this device but I cannot pair it with z2m. It was more about the reset/paring process than the issue itself.

**Comment by iBobbe** [comment]
> ask how you managed to pair it since seems that there is no documenta

I have the same difficulties on pairing BT-LN4570CWI to my zigbee network with z2m. No matter what I try (brief press on reset, long press on reset, brief press on both buttons, long press on both buttons etc.) the behavior is always the same: fast green flashing for about 10s then a single red flash and then nothing. During this the device doesn't connect to z2m. I also tried to remove the battery for a minute without luck.

**Comment by lucaam** [comment]
> > ask how you managed to pair it since seems that there is no documenta
> 
> I have the same difficulties on pairing BT-LN4570CWI to my zigbee network with z2m. No matter what I try (brief press on reset, long press on reset, brief press on both buttons, long press on both buttons etc.) the behavior is always the same: fast green flashing for about 10s then a single red flash and then nothing. During this the device doesn't connect to z2m. I also tried to remove the battery for a minute without luck.

I think this is because the command is paired from factory with the gateway, I found reading online that there is no way of pairing the module that is sold in a bundle with the gateway.

**Comment by iBobbe** [comment]
> > > ask how you managed to pair it since seems that there is no documenta
> > 
> > 
> > I have the same difficulties on pairing BT-LN4570CWI to my zigbee network with z2m. No matter what I try (brief press on reset, long press on reset, brief press on both buttons, long press on both buttons etc.) the behavior is always the same: fast green flashing for about 10s then a single red flash and then nothing. During this the device doesn't connect to z2m. I also tried to remove the battery for a minute without luck.
> 
> I think this is because the command is paired from factory with the gateway, I found reading online that there is no way of pairing the module that is sold in a bundle with the gateway.

Oh, then it makes sense. Thanks for the insight!

Edit: I guess you refer to this:
https://github.com/Koenkk/zigbee2mqtt/issues/26150
Just in case someone encounters the same issue.
