### ISSUE TITLE
zlinky not com

### ISSUE THREAD

**Issue by MathildeDec** [Koenkk/zigbee2mqtt#19790]
### What happened?

I have an EDF Zen Flex subscription.
After connecting a zlinky lixe to my ZigBee cluster, Z2M does not discover all the entities:

     {
     "Active_enerfy_out_d01": 16510.062,
     "Active_enerfy_out_d02": 20057.387,
     "Active_enerfy_out_d03": 6538.882,
     "Active_enerfy_out_d04": 7264.517,
     "Active_Power": 2268,
     "Active_Power_max": 5242,
     "Active_Power_Ph_B": 2548,
     "Apparent_Power": 2295,
     "Available_power": 9,
     "AVERAGE_RMS_VOLTAGE_MEAS_PERIOD": 237,
     "Current_date": "H231120204739",
     "Current_index_tarif": 1,
     "Current_price": "HC Jnormal",
     "Current_summ_delivered": 50370.92,
     "Current_tarif": "Mobile tip",
     "Current_tier1_summ_delivered": 24065.695,
     "Drawn_v_a_max_n1": 5196,
     "Last_seen": "2023-11-20t20: 47: 50+01: 00",
     "Linkquality": 147,
     "Message2": "",
     "meter_serial_number": "xxxxxx",
     "Power_threshold": 9,
     "Relay": 0,
     "rms_current": 10,
     "RMS_Volage": 232,
     "site_id": "xxxxxx",
     "Software_revision": 2,
     "start_mobile_point1": 0,
     "start_mobile_point2": 0,
     "start_mobile_point3": 0,
     "status_ record": "xxxxxx",
     "stop_mobile_point1": 0,
     "stop_mobile_point2": 0,
     "stop_mobile_point3": 0,
     "Update": {
         "Installed_version": 13,
         "Latest_version": 13,
         "State": "Idle"
     },
     "Update_available": False,
     "Current_tier10_summ_delivered": null,
     "Current_tier2_summ_delivered": null,
     "current_tier3_summ_delivered": null,
     "Current_tier4_summ_delivered": null,
     "Current_tier5_summ_delivered": null,
     "Current_tier6_summ_delivered": null,
     "current_tier7_summ_delivered": null,
     "Current_tier8_summ_delivered": null,
     "Current_tier9_summ_delivered": null,
     "Days_Number_current_Calendar": Null,
     "Days_Profile_current_Calendar": Null,
     "Days_Profile_NEXT_Calendar": Null,
     "Elapsed": 9026,
     "message1": null
}

In addition, many exhibition entities are absent from the home assistant.

I want to have at least
     "Days_Profile_Next_Calendar"
     "current_tier2_summ_delivered"
     "current_tier3_summ_delivered"
     "current_tier4_summ_delivered"

### What did you expect to happen?

Version de Zigbee2MQTT
    [1.33.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.33.2) commit: [9996c93](https://github.com/Koenkk/zigbee2mqtt/commit/9996c93)

Type de coordinateur
    zStack3x0

Révision du coordinateur
    20210708

Adresse IEEE du Coordinateur
    0x00124b0021b7815a

Version de l'interface
    0.6.142

Zigbee-herdsman-converters version
    15.106.0

Zigbee-herdsman version
    0.21.0

### How to reproduce it (minimal and precise)

I attempted several without success by removing Zlinky.

my settings
Measurement poll interval: 60
Linky mode: standard
Energy phase: single
Production: false
tarif: auto (not pointe mobile)
KWh precision: 3

Measurement poll chunk: empty

Tic command whitelist: ADSC,NGTF,LTARF,NTARF,VTIC,DATE,EAST,EASF01,EASF02,EASF03,EASF04,EASF05,EASF06,EASF07,EASF08,EASF09,EASF10,EASD01,EASD02,EASD03,EASD04,EASD05,EASD06,EASD07,EASD08,IRMS1,URMS1,PREF,STGE,PCOUP,CCASN,CCASN-1,UMOY1,SINSTS,SMAXN,SMAXN-1,MSG1,MSG2,PRM,DPM1,FPM1,NJOURF,PJOURF+1,PPOINTE1.

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

 20210708

### Adapter

zzh

### Debug log

 
debug 2023-11-20 21:12:03Received Zigbee message from 'ZLinky_TIC', type 'readResponse', cluster 'liXeePrivate', data '{"message2":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","relais":0,"startMobilePoint1":0,"startMobilePoint2":0}' from endpoint 1 with groupID 0
info 2023-11-20 21:12:03MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":16510.062,"active_enerfy_out_d02":20057.387,"active_enerfy_out_d03":6538.882,"active_enerfy_out_d04":7265.427,"active_power":2204,"active_power_max":5242,"active_power_ph_b":2268,"apparent_power":2370,"available_power":9,"average_rms_voltage_meas_period":235,"current_date":"H231120211128","current_index_tarif":1,"current_price":"HC Jnormal","current_summ_delivered":50371.822,"current_tarif":"Pointe Mobile","current_tier10_summ_delivered":null,"current_tier1_summ_delivered":24066.597,"current_tier2_summ_delivered":null,"current_tier3_summ_delivered":null,"current_tier4_summ_delivered":null,"current_tier5_summ_delivered":null,"current_tier6_summ_delivered":null,"current_tier7_summ_delivered":null,"current_tier8_summ_delivered":null,"current_tier9_summ_delivered":null,"days_number_current_calendar":null,"days_profile_current_calendar":null,"days_profile_next_calendar":null,"drawn_v_a_max_n1":5196,"elapsed":10630,"last_seen":"2023-11-20T21:12:02+01:00","linkquality":51,"message1":null,"message2":"","meter_serial_number":"xxxx","power_threshold":9,"relais":0,"rms_current":5,"rms_voltage":237,"site_id":"xxxx","software_revision":2,"start_mobile_point1":0,"start_mobile_point2":0,"start_mobile_point3":0,"status_register":"003AC001","stop_mobile_point1":0,"stop_mobile_point2":0,"stop_mobile_point3":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":false}'
debug 2023-11-20 21:12:03Received Zigbee message from 'ZLinky_TIC', type 'readResponse', cluster 'liXeePrivate', data '{"startMobilePoint3":0,"statusRegister":{"data":[48,48,51,65,67,48,48,49],"type":"Buffer"},"stopMobilePoint1":0,"stopMobilePoint2":0}' from endpoint 1 with groupID 0
info 2023-11-20 21:12:03MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":16510.062,"active_enerfy_out_d02":20057.387,"active_enerfy_out_d03":6538.882,"active_enerfy_out_d04":7265.427,"active_power":2204,"active_power_max":5242,"active_power_ph_b":2268,"apparent_power":2370,"available_power":9,"average_rms_voltage_meas_period":235,"current_date":"H231120211128","current_index_tarif":1,"current_price":"HC Jnormal","current_summ_delivered":50371.822,"current_tarif":"Pointe Mobile","current_tier10_summ_delivered":null,"current_tier1_summ_delivered":24066.597,"current_tier2_summ_delivered":null,"current_tier3_summ_delivered":null,"current_tier4_summ_delivered":null,"current_tier5_summ_delivered":null,"current_tier6_summ_delivered":null,"current_tier7_summ_delivered":null,"current_tier8_summ_delivered":null,"current_tier9_summ_delivered":null,"days_number_current_calendar":null,"days_profile_current_calendar":null,"days_profile_next_calendar":null,"drawn_v_a_max_n1":5196,"elapsed":85,"last_seen":"2023-11-20T21:12:02+01:00","linkquality":48,"message1":null,"message2":"","meter_serial_number":"xxxx","power_threshold":9,"relais":0,"rms_current":5,"rms_voltage":237,"site_id":"xxxx","software_revision":2,"start_mobile_point1":0,"start_mobile_point2":0,"start_mobile_point3":0,"status_register":"003AC001","stop_mobile_point1":0,"stop_mobile_point2":0,"stop_mobile_point3":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":false}'
debug 2023-11-20 21:12:03Received Zigbee message from 'ZLinky_TIC', type 'readResponse', cluster 'liXeePrivate', data '{"drawnVAMaxN1":5196,"stopMobilePoint3":0}' from endpoint 1 with groupID 0
info 2023-11-20 21:12:03MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":16510.062,"active_enerfy_out_d02":20057.387,"active_enerfy_out_d03":6538.882,"active_enerfy_out_d04":7265.427,"active_power":2204,"active_power_max":5242,"active_power_ph_b":2268,"apparent_power":2370,"available_power":9,"average_rms_voltage_meas_period":235,"current_date":"H231120211128","current_index_tarif":1,"current_price":"HC Jnormal","current_summ_delivered":50371.822,"current_tarif":"Pointe Mobile","current_tier10_summ_delivered":null,"current_tier1_summ_delivered":24066.597,"current_tier2_summ_delivered":null,"current_tier3_summ_delivered":null,"current_tier4_summ_delivered":null,"current_tier5_summ_delivered":null,"current_tier6_summ_delivered":null,"current_tier7_summ_delivered":null,"current_tier8_summ_delivered":null,"current_tier9_summ_delivered":null,"days_number_current_calendar":null,"days_profile_current_calendar":null,"days_profile_next_calendar":null,"drawn_v_a_max_n1":5196,"elapsed":67,"last_seen":"2023-11-20T21:12:03+01:00","linkquality":51,"message1":null,"message2":"","meter_serial_number":"xxxx","power_threshold":9,"relais":0,"rms_current":5,"rms_voltage":237,"site_id":"xxxx","software_revision":2,"start_mobile_point1":0,"start_mobile_point2":0,"start_mobile_point3":0,"status_register":"003AC001","stop_mobile_point1":0,"stop_mobile_point2":0,"stop_mobile_point3":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":false}'
debug 2023-11-20 21:12:03Received Zigbee message from 'ZLinky_TIC', type 'readResponse', cluster 'seMetering', data '{"meterSerialNumber":{"data":[48,52,49,55,54,52,50,48,54,56,54,55],"type":"Buffer"},"siteId":{"data":[48,54,53,48,53,52,57,57,50,50,54,51,57,55],"type":"Buffer"}}' from endpoint 1 with groupID 0
info 2023-11-20 21:12:03MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":16510.062,"active_enerfy_out_d02":20057.387,"active_enerfy_out_d03":6538.882,"active_enerfy_out_d04":7265.427,"active_power":2204,"active_power_max":5242,"active_power_ph_b":2268,"apparent_power":2370,"available_power":9,"average_rms_voltage_meas_period":235,"current_date":"H231120211128","current_index_tarif":1,"current_price":"HC Jnormal","current_summ_delivered":50371.822,"current_tarif":"Pointe Mobile","current_tier10_summ_delivered":null,"current_tier1_summ_delivered":24066.597,"current_tier2_summ_delivered":null,"current_tier3_summ_delivered":null,"current_tier4_summ_delivered":null,"current_tier5_summ_delivered":null,"current_tier6_summ_delivered":null,"current_tier7_summ_delivered":null,"current_tier8_summ_delivered":null,"current_tier9_summ_delivered":null,"days_number_current_calendar":null,"days_profile_current_calendar":null,"days_profile_next_calendar":null,"drawn_v_a_max_n1":5196,"elapsed":81,"last_seen":"2023-11-20T21:12:03+01:00","linkquality":48,"message1":null,"message2":"","meter_serial_number":"xxxx","power_threshold":9,"relais":0,"rms_current":5,"rms_voltage":237,"site_id":"xxxx","software_revision":2,"start_mobile_point1":0,"start_mobile_point2":0,"start_mobile_point3":0,"status_register":"003AC001","stop_mobile_point1":0,"stop_mobile_point2":0,"stop_mobile_point3":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":false}'
debug 2023-11-20 21:12:03Received Zigbee message from 'ZLinky_TIC', type 'readResponse', cluster 'haMeterIdentification', data '{"availablePower":9,"powerThreshold":9,"softwareRevision":2}' from endpoint 1 with groupID 0
info 2023-11-20 21:12:03MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":16510.062,"active_enerfy_out_d02":20057.387,"active_enerfy_out_d03":6538.882,"active_enerfy_out_d04":7265.427,"active_power":2204,"active_power_max":5242,"active_power_ph_b":2268,"apparent_power":2370,"available_power":9,"average_rms_voltage_meas_period":235,"current_date":"H231120211128","current_index_tarif":1,"current_price":"HC Jnormal","current_summ_delivered":50371.822,"current_tarif":"Pointe Mobile","current_tier10_summ_delivered":null,"current_tier1_summ_delivered":24066.597,"current_tier2_summ_delivered":null,"current_tier3_summ_delivered":null,"current_tier4_summ_delivered":null,"current_tier5_summ_delivered":null,"current_tier6_summ_delivered":null,"current_tier7_summ_delivered":null,"current_tier8_summ_delivered":null,"current_tier9_summ_delivered":null,"days_number_current_calendar":null,"days_profile_current_calendar":null,"days_profile_next_calendar":null,"drawn_v_a_max_n1":5196,"elapsed":78,"last_seen":"2023-11-20T21:12:03+01:00","linkquality":51,"message1":null,"message2":"","meter_serial_number":"xxxx","power_threshold":9,"relais":0,"rms_current":5,"rms_voltage":237,"site_id":"xxxx","software_revision":2,"start_mobile_point1":0,"start_mobile_point2":0,"start_mobile_point3":0,"status_register":"003AC001","stop_mobile_point1":0,"stop_mobile_point2":0,"stop_mobile_point3":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":false}'

**Comment by Mikado8231** [comment]
@MathildeDec could you test the dev branch to check if the PR is complete ?
