### ISSUE TITLE
IKEA E1524/E1810 cannot been paired successfully

### ISSUE THREAD

**Issue by ikarisan** [Koenkk/zigbee2mqtt#19807]
### What happened?

After both of my IKEA E1524/E1810 left the network unexpected I tried to rejoin them both. But this is no longer possible. 
The pairing process ist not successfull. The message is always "Failed to interview '0xxxxxxxxxxxx', device has not successfully been paired".  I tried join the remotes at my coordinator "Sonoff Zigbee 3.0 USB (ZBdongle-P )". No success. Then I tried it at my Tradfri trafo and at a Tradfri light bulb. 

Zigbee2Mqtt shows the remotes as online but with a red exclamation mark. But if I press a button, no messages are reaching Z2M. 

The devices in the log we are looking for are "Tradfri_FB1_" (0x000b57fffeb37047) and "Tradfri_FB2_" (0xbc33acfffe9808d1).

### What did you expect to happen?

Pairing process is finished successfully.

### How to reproduce it (minimal and precise)

0) Install Z2M 1.33.2-dev commit: [61b08c9](https://github.com/Koenkk/zigbee2mqtt/commit/61b08c9)
1) Remove the E1524 from your network
2) Activate joining in Z2M
3) Activate the pairing process at you Tradfri remote

### Zigbee2MQTT version

1.33.2-dev commit: 61b08c9

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 USB (ZBdongle-P)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13429600/log.txt)

**Comment by ikarisan** [comment]
Don't know what happend. But totay both remotes are suddenly beeing successfully faired. I did nothing... O.O

**Comment by BinaryShrub** [comment]
I'm struggling to get mine to pair with an Ikea Tradfri Plug, any suggestions?
