### ISSUE TITLE
[New device support]: OWON THS317-ET-TY (Tuya), model: TS0201, manufacturer: _TZE200_01fvxamo

### ISSUE THREAD

**Issue by soukal24** [Koenkk/zigbee2mqtt#19804]
### Link

https://www.pamitech.cz/kabelovy-zigbee-sensor-teploty-tuya/

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xb43a31fffe66d186","nwkAddr":34055,"manufId":4098,"manufName":"_TZE200_01fvxamo","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,61184,1026,1029,65382],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0201","manufacturerName":"_TZE200_01fvxamo","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1700575181645,"defaultSendRequestWhen":"immediate"}

### Comments

It is a new device similar to THS317-ET but it is based on ZS3L to be supported by Tuya Zigbee gateway. Pairing was successful in Z2M, it looks like TS0201 but does not display any values. It works properly with Tuya Zigbee gateway.
![ths317_1](https://github.com/Koenkk/zigbee2mqtt/assets/98241280/e75d667b-a581-4756-8c33-fa2bd9774a3c)
![ths317_2](https://github.com/Koenkk/zigbee2mqtt/assets/98241280/59079cc3-901e-4847-9bc6-7744ebc9089e)
![IMG_2982](https://github.com/Koenkk/zigbee2mqtt/assets/98241280/ff305d6d-10e0-465b-8413-3627ee1cc5f7)

**Comment by saba01** [comment]
I have the same problem,
tested with last dev release, 1.35.1-dev commit: ce7d022

**Comment by soukal24** [comment]
Here is log from Z2M afr´ter pair device:
`2024-03-01 12:47:49Device '0x3c6a2cfffed3e89a' joined
Info 2024-03-01 12:47:49MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed3e89a","ieee_address":"0x3c6a2cfffed3e89a"},"type":"device_joined"}'
Info 2024-03-01 12:47:49Starting interview of '0x3c6a2cfffed3e89a'
Info 2024-03-01 12:47:49MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed3e89a","ieee_address":"0x3c6a2cfffed3e89a","status":"started"},"type":"device_interview"}'
Debug 2024-03-01 12:47:49Device '0x3c6a2cfffed3e89a' announced itself
Info 2024-03-01 12:47:49MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x3c6a2cfffed3e89a","ieee_address":"0x3c6a2cfffed3e89a"},"type":"device_announce"}'
Debug 2024-03-01 12:47:49Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZE200_01fvxamo","modelId":"TS0201"}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:49Skipping message, still interviewing
Debug 2024-03-01 12:47:50Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:50Skipping message, still interviewing
Debug 2024-03-01 12:47:51Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:51Skipping message, still interviewing
Debug 2024-03-01 12:47:51Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,209],"type":"Buffer"},"datatype":2,"dp":1}],"seq":22784}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:51Skipping message, still interviewing
Debug 2024-03-01 12:47:51Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"appVersion":65}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:51Skipping message, still interviewing
Debug 2024-03-01 12:47:51Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:51Skipping message, still interviewing
Debug 2024-03-01 12:47:51Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:51Skipping message, still interviewing
Debug 2024-03-01 12:47:52Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":23040}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:52Skipping message, still interviewing
Debug 2024-03-01 12:47:52Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:52Skipping message, still interviewing
Debug 2024-03-01 12:47:52Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:52Skipping message, still interviewing
Info 2024-03-01 12:47:52Successfully interviewed '0x3c6a2cfffed3e89a', device has successfully been paired
Info 2024-03-01 12:47:52Device '0x3c6a2cfffed3e89a' is supported, identified as: TuYa Temperature & humidity sensor with display (TS0201)
Info 2024-03-01 12:47:52MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Temperature & humidity sensor with display","exposes":[{"access":1,"category":"diagnostic","description":"Remaining battery in %, can take up to 24 hours before reported","label":"Battery","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Measured temperature value","label":"Temperature","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Measured relative humidity","label":"Humidity","name":"humidity","property":"humidity","type":"numeric","unit":"%"},{"access":1,"category":"diagnostic","description":"Voltage of the battery in millivolts","label":"Voltage","name":"voltage","property":"voltage","type":"numeric","unit":"mV"},{"access":1,"category":"diagnostic","description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"TS0201","options":[{"access":2,"description":"Calibrates the temperature value (absolute offset), takes into effect on next report of device.","label":"Temperature calibration","name":"temperature_calibration","property":"temperature_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for temperature, takes into effect on next report of device. This option can only decrease the precision, not increase it.","label":"Temperature precision","name":"temperature_precision","property":"temperature_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the humidity value (absolute offset), takes into effect on next report of device.","label":"Humidity calibration","name":"humidity_calibration","property":"humidity_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for humidity, takes into effect on next report of device. This option can only decrease the precision, not increase it.","label":"Humidity precision","name":"humidity_precision","property":"humidity_precision","type":"numeric","value_max":3,"value_min":0}],"supports_ota":false,"vendor":"TuYa"},"friendly_name":"0x3c6a2cfffed3e89a","ieee_address":"0x3c6a2cfffed3e89a","status":"successful","supported":true},"type":"device_interview"}'
Info 2024-03-01 12:47:52Configuring '0x3c6a2cfffed3e89a'
Info 2024-03-01 12:47:52MQTT publish: topic 'homeassistant/sensor/0x3c6a2cfffed3e89a/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","object_id":"0x3c6a2cfffed3e89a_battery","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Info 2024-03-01 12:47:52MQTT publish: topic 'homeassistant/sensor/0x3c6a2cfffed3e89a/temperature/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"temperature","enabled_by_default":true,"object_id":"0x3c6a2cfffed3e89a_temperature","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_temperature_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}'
Info 2024-03-01 12:47:52MQTT publish: topic 'homeassistant/sensor/0x3c6a2cfffed3e89a/humidity/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"humidity","enabled_by_default":true,"object_id":"0x3c6a2cfffed3e89a_humidity","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}'
Info 2024-03-01 12:47:52MQTT publish: topic 'homeassistant/sensor/0x3c6a2cfffed3e89a/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","object_id":"0x3c6a2cfffed3e89a_voltage","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
Info 2024-03-01 12:47:52MQTT publish: topic 'homeassistant/sensor/0x3c6a2cfffed3e89a/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Linkquality","object_id":"0x3c6a2cfffed3e89a_linkquality","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Debug 2024-03-01 12:47:52Received MQTT message on 'homeassistant/sensor/0x3c6a2cfffed3e89a/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","object_id":"0x3c6a2cfffed3e89a_battery","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Debug 2024-03-01 12:47:52Received MQTT message on 'homeassistant/sensor/0x3c6a2cfffed3e89a/temperature/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"temperature","enabled_by_default":true,"object_id":"0x3c6a2cfffed3e89a_temperature","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_temperature_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}'
Debug 2024-03-01 12:47:52Received MQTT message on 'homeassistant/sensor/0x3c6a2cfffed3e89a/humidity/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"humidity","enabled_by_default":true,"object_id":"0x3c6a2cfffed3e89a_humidity","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}'
Debug 2024-03-01 12:47:52Received MQTT message on 'homeassistant/sensor/0x3c6a2cfffed3e89a/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","object_id":"0x3c6a2cfffed3e89a_voltage","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_voltage_zigbee2mqtt","unit_of_measurement":"mV","value_template":"{{ value_json.voltage }}"}'
Debug 2024-03-01 12:47:52Received MQTT message on 'homeassistant/sensor/0x3c6a2cfffed3e89a/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x3c6a2cfffed3e89a"],"manufacturer":"TuYa","model":"Temperature & humidity sensor with display (TS0201)","name":"0x3c6a2cfffed3e89a","via_device":"zigbee2mqtt_bridge_0x00124b0024c2b692"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Linkquality","object_id":"0x3c6a2cfffed3e89a_linkquality","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x3c6a2cfffed3e89a","unique_id":"0x3c6a2cfffed3e89a_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Debug 2024-03-01 12:47:52Received Zigbee message from '0x3c6a2cfffed3e89a', type 'readResponse', cluster 'genBasic', data '{"65534":0,"appVersion":65,"manufacturerName":"_TZE200_01fvxamo","modelId":"TS0201","powerSource":3,"zclVersion":3}' from endpoint 1 with groupID 0
Info 2024-03-01 12:47:52Successfully configured '0x3c6a2cfffed3e89a'
Debug 2024-03-01 12:47:54Received Zigbee message from '0x3c6a2cfffed3e89a', type 'attributeReport', cluster 'genBasic', data '{"65506":31,"65508":1,"appVersion":65}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:47:55Received Zigbee message from '0x3c6a2cfffed3e89a', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Debug 2024-03-01 12:48:57Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,213],"type":"Buffer"},"datatype":2,"dp":1}],"seq":23296}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:48:57No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,213],"type":"Buffer"},"datatype":2,"dp":1}],"seq":23296}'
Debug 2024-03-01 12:48:57Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":23552}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:48:57No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":23552}'
Debug 2024-03-01 12:48:59Received Zigbee message from '0x3c6a2cfffed3e89a', type 'attributeReport', cluster 'genBasic', data '{"65503":"\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011"}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:49:00Received Zigbee message from '0x3c6a2cfffed3e89a', type 'attributeReport', cluster 'genBasic', data '{"65503":"\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0006\u0000\u0000\u0000\u0000\u0011"}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:50:19Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,218],"type":"Buffer"},"datatype":2,"dp":1}],"seq":23808}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:50:19No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,218],"type":"Buffer"},"datatype":2,"dp":1}],"seq":23808}'
Debug 2024-03-01 12:50:20Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":24064}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:50:20No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":24064}'
Debug 2024-03-01 12:51:33Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,220],"type":"Buffer"},"datatype":2,"dp":1}],"seq":24320}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:51:33No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,220],"type":"Buffer"},"datatype":2,"dp":1}],"seq":24320}'
Debug 2024-03-01 12:51:34Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":24576}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:51:34No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":24576}'
Debug 2024-03-01 12:52:22Saving state to file /config/zigbee2mqtt/state.json
Debug 2024-03-01 12:52:44Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,222],"type":"Buffer"},"datatype":2,"dp":1}],"seq":24832}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:52:44No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,222],"type":"Buffer"},"datatype":2,"dp":1}],"seq":24832}'
Debug 2024-03-01 12:52:44Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":25088}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:52:44No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":25088}'
Debug 2024-03-01 12:53:08Received Zigbee message from '0x3c6a2cfffed3e89a', type 'attributeReport', cluster 'genBasic', data '{"65506":31,"65508":0,"appVersion":65}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:53:49Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,222],"type":"Buffer"},"datatype":2,"dp":1}],"seq":25344}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:53:49No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,222],"type":"Buffer"},"datatype":2,"dp":1}],"seq":25344}'
Debug 2024-03-01 12:53:50Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":25600}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:53:50No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":25600}'
Debug 2024-03-01 12:54:55Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,221],"type":"Buffer"},"datatype":2,"dp":1}],"seq":25856}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:54:55No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,221],"type":"Buffer"},"datatype":2,"dp":1}],"seq":25856}'
Debug 2024-03-01 12:54:55Received Zigbee message from '0x3c6a2cfffed3e89a', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":26112}' from endpoint 1 with groupID 0
Debug 2024-03-01 12:54:55No converter available for 'TS0201' with cluster 'manuSpecificTuya' and type 'commandDataReport' and data '{"dpValues":[{"data":{"data":[0,0,0,70],"type":"Buffer"},"datatype":2,"dp":4}],"seq":26112}'`

**Comment by awhitwam** [comment]
Same issue here.  Any luck with a solution ?

**Comment by awhitwam** [comment]
ok, i got it working without entirely knowing what i was doing;

Here's the code;

```javascript

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	fingerprint: tuya.fingerprint('TS0201', ['_TZE200_01fvxamo']),
    model: 'THS317-ET-EY',
    vendor: 'Tuya',
    description: 'Temperature Sensor with Probe THS 317-ET',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.fz.datapoints],
    configure: tuya.configureMagicPacket,
    exposes: [e.temperature(), e.battery()],
    meta: {
        tuyaDatapoints: [
            [1, 'temperature', tuya.valueConverter.divideBy10],
            [4, 'battery', tuya.valueConverter.raw],

        ],
    },

};

module.exports = definition;

```

**Comment by Koenkk** [comment]
@awhitwam do you see logging for any other DPs, like for humidity?

**Comment by awhitwam** [comment]
> @awhitwam do you see logging for any other DPs, like for humidity?

No, nothing at all in the logs.  I'm pretty sure it only supports temperature and battery.

see [https://zigbee.blakadder.com/OWON_THS317-ET.html](url)

**Comment by Hoween** [comment]
Hi @soukal24. Looking that we have same issue with same sensor from same e-shop :) Please, can you confirm that THS 317-ET-YT is fully supported in Z2M? According to this closed issue it should be - I have latest stable Z2M, but this sensors is still identified as [TS0201](https://www.zigbee2mqtt.io/devices/TS0201.html#tuya-ts0201). Or do you have any clue how to fix this behaviour?

**Comment by soukal24** [comment]
Hi, here is the newly tested and working converter. Is it possible to add it to the next version, please? @Koenkk

```javascript
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
	fingerprint: tuya.fingerprint('TS0201', ['_TZE200_iq4ygaai']),
    model: 'THS317-ET-TY',
    vendor: 'Tuya',
    description: 'Temperature Sensor with Probe THS 317-ET-TY',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.fz.datapoints],
    configure: tuya.configureMagicPacket,
    exposes: [e.temperature(), e.battery()],
    meta: {
        tuyaDatapoints: [
            [1, 'temperature', tuya.valueConverter.divideBy10],
            [4, 'battery', tuya.valueConverter.raw],

        ],
    },

};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Done!
