### ISSUE TITLE
Upgrade 1.3.0 > 1.6.0 fails with firmware 20190109

### ISSUE THREAD

**Issue by tubededentifrice** [Koenkk/zigbee2mqtt#1980]
#1787 Bug Report
## What happened
After upgrading from 1.3.0 to 1.6.0 (with `./update.sh`), zigbee2mqtt wouldn't start.
Logs can be found at https://pastebin.com/Q2RuWwJt 
CC2531 is on firmware 20190109 and I had it running for months perfectly fine.

After downgrading to 1.3.0 with `git checkout 00ebd44; rm -rf node_modules; npm install`, everything starts just fine again: https://pastebin.com/2JUKP6Hm

I haven't tried to re-flash the CC2531 while on 1.6.0, so it could really be an incompatibility issue beweek 20190109 firmware and 1.6.0. However I haven't seen any such incompatibility disclosed anywhere on the releases page.

## What did you expect to happen
Painless, in-place upgrade

## How to reproduce it (minimal and precise)
- Get a CC2531 on 20190109
- Check that everything works fine on 1.3.0
- run `./update.sh` to go to latest version
- Check that it doesn't start anymore

## Debug Info
zigbee2mqtt version: 1.3.0 to 1.6.0
CC253X firmware version: 20190109

**Comment by tubededentifrice** [comment]
NB: Problem persists with CC2531 on 20190608 (tried on another CC I had though): https://pastebin.com/vcMeQKwN

v1.3.0 is working properly on that CC2531 with 20190608

**Comment by str3000** [comment]
Hello,
only additional info because I had the same problem.
I go back to V1.5.1 and zigbee2mqtt starts now. Puhhh

Differents: 
- CC2531: CC2531_SOURCE_ROUTING_20190619
- nuc i3

[2019_09_15_V1.6-logs.txt](https://github.com/Koenkk/zigbee2mqtt/files/3613853/2019_09_15_V1.6-logs.txt)

**Comment by Koenkk** [comment]
@tubededentifrice can you provide the log when starting with `DEBUG=* npm start`

**Comment by tubededentifrice** [comment]
@Koenkk sure thing, here is one: https://pastebin.com/Mc4gEZ8v

**Comment by tubededentifrice** [comment]
@str3000 I've tried 1.5.1 (commit #ac3b924) but I've the same problems on my install

**Comment by tubededentifrice** [comment]
Other tests:
1.3.0 => 1.3.1: Works fine
1.3.1 => 1.4.0: Works fine
1.4.0 => 1.5.0: Works fine
1.5.0 => 1.5.1: Doesn't work
So it looks like the bug was introduced in 1.5.1

**Comment by str3000** [comment]
ac3b924 works in my environment. 
It seems that everything works fine.
mosquitto version 1.5.8

**Comment by tubededentifrice** [comment]
@Koenkk indeed, the dev branch seems to be working fine, thanks a lot :) when is it "scheduled" to be GA?

**Comment by Koenkk** [comment]
No ETA, first extensive testing needs to be done (as most of the zigbee2mqtt code base has been replaced/touched)

**Comment by jamesawebb** [comment]
FWIW confirmed that a 1.4.0 restore fixes this issue for me.
/ht @tubededentifrice

**Comment by negmos** [comment]
I have the same problem and falling back to 1.4.0 or Dev version doesn't solve it.
My system is:
CC2531: CC2531_SOURCE_ROUTING_20190619
Device: PI3B
Using Docker container

**Comment by thehaxxa** [comment]
I am also having this issue.

**Comment by andreas-bell** [comment]
I also had the issue when upgrading from 1.3.1 to 1.6.0:
zigbee2mqtt did not start, rebooted, unplugged, hit reset, copied the config again, tried the previous firmware, the default 20190608 and the source routing 20190619 firmware, nothing worked with 1.6.0 (different errors).
I then upgraded to the dev branch: (in combination with the source routing 20190619 firmware)
payload '{"version":"1.6.0","commit":"ba92f73"
and then for the first time since the upgrade zigbee2mqtt started again and is processing messages.
I'm not sure if I should stay on the dev branch with my production system, or if I could downgrade to 1.6.0 again.

**Comment by Koenkk** [comment]
Dont worry on staying on the dev branch, this uses zigbee-herdsman (#1888) which is much better than zigbee-shepherd (zigbee2mqtt 1.6). Also this will be close to what zigbee2mqtt 1.7 will be.
