### ISSUE TITLE
[New device support]: TS0601 Boiler Switch with timers 15,30,60,90 min

### ISSUE THREAD

**Issue by moshiko2312** [Koenkk/zigbee2mqtt#19816]
### Link

https://www.smarthome4u.co.il/products.html

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xa4c138192510945e","nwkAddr":60927,"manufId":4417,"manufName":"_TZE204_vqaajp1a","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1700660489583,"defaultSendRequestWhen":"immediate"}

### Comments

Circuit breaker for electric boiler with timer 15,30,60,90 minutes
![BOILER](https://github.com/Koenkk/zigbee2mqtt/assets/48163773/0e1841c9-aad2-4d83-85dc-f8a9cb50742e)
![BOILER TUYA](https://github.com/Koenkk/zigbee2mqtt/assets/48163773/4c74a700-27d5-4e14-bc54-4d9b31b0a1db)

**Comment by pantherale0** [comment]
Not able to test as its not a device I have, but see if this converter works, I found the datapoints over on the smartthings forum.

https://gist.github.com/pantherale0/cca06b9669c07e68addd22d74f0e555d

Sources:
https://docs.google.com/spreadsheets/d/12AsWMyQfc8MoNTGed6p7BPIvi3H2pkar/edit#gid=725399417
https://community.smartthings.com/t/st-edge-personal-tuya-devices-generic-ef00-device/255270/330?page=17

**Comment by moshiko2312** [comment]
Hi thanks 
Its not working good on off not working , what I need to do?
￼
