### ISSUE TITLE
Power of TuYa TS011F_plug_1 is not reported in 1.33.2

### ISSUE THREAD

**Issue by LeeHanYeong** [Koenkk/zigbee2mqtt#19811]
### What happened?

In 1.33.1, Power and Current are reported normally.
In 1.33.2, both remain unchanged from their previous state.

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee Dongle-P

**Comment by johndfoss** [comment]
Same here. This keeps breaking with Updates :-(
