### ISSUE TITLE
Schneider Electric WV704R0A0902 - Running_state, current_heating_setpoint & system_mode values

### ISSUE THREAD

**Issue by juliennnnn** [Koenkk/zigbee2mqtt#19813]
### What happened?

Hello
I bought 3 Schneider Electric WV704R0A0902 valves (https://www.zigbee2mqtt.io/devices/WV704R0A0902.html) but : 
- There is no valid value for "running_state". The current value is "no value". 
- Also, the features "current_heating_setpoint" & "system_mode" are not available. Could it be possible to add them? It will help with the HomeKit integration (https://z2m.dev/climate.html).

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

0x26580700

### Adapter

ConBee2

**Comment by juliennnnn** [comment]
Hello, any update on this please? Still the same issue, even with the last updates. Thanks a lot :)

**Comment by pbranly** [comment]
Hi I would also deeply need that feature for controlling my central heating system
Please push it
Phil
