### ISSUE TITLE
[New device support]: Philips Hue Festavia (40 meters / 500 LEDs)

### ISSUE THREAD

**Issue by Grandma-Betty** [Koenkk/zigbee2mqtt#19814]
### Link

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-festavia-string-lights/046677585365

### Database entry

{"id":122,"type":"Router","ieeeAddr":"0x001788010dd9e2db","nwkAddr":6889,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCX017","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230508","swBuildId":"1.107.1","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1700652368334,"defaultSendRequestWhen":"immediate"}

### Comments

I did not try because of lack of time currently.

**Comment by Koenkk** [comment]
Already supported in the dev branch and will be supported in the 1 December release
