### ISSUE TITLE
[New device support]: Aqara T1 light strip controller ZNDDQDQ12LM

### ISSUE THREAD

**Issue by MiAutomations** [Koenkk/zigbee2mqtt#19833]
### Link

https://www.aqara.cn/light-strip-controller_overview

### Database entry

{"id":80,"type":"Router","ieeeAddr":"0x54ef4410008de36c","nwkAddr":15179,"manufId":4447,"manufName":"Aqara","powerSource":"DC Source","modelId":"lumi.dimmer.acn004","epList":[1,21],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[5,4,3,0,768,8,6,2820,1794,64704],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.dimmer.acn004","manufacturerName":"Aqara","powerSource":4,"zclVersion":3,"appVersion":23,"stackVersion":27,"hwVersion":1,"dateCode":"20230605"}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"profId":260,"epId":21,"devId":0,"inClusterList":[12],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":23,"stackVersion":27,"hwVersion":1,"dateCode":"20230605","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1700755744718,"defaultSendRequestWhen":"immediate"}

### Comments

Hello Team 

Can you please try to add this new device from the Aqara? 

Thank you

**Comment by MiAutomations** [comment]
Hello Any news regarding this device ? 

Thank you

**Comment by Koenkk** [comment]
Does it work out of the box with 1.35.3?

**Comment by MiAutomations** [comment]
> Does it work out of the box with 1.35.3?

No, Still facing the issue as unsupported device even with the last update on Z2M and the device FW 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/47602733/80be349a-4297-4c59-9ed4-fb0e8bb082fd)

**Comment by Koenkk** [comment]
Is nothing exposes when clicking on the device -> expose page? 

Could you try with the [generated external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)?

**Comment by MiAutomations** [comment]
> Is nothing exposes when clicking on the device -> expose page?
> 
> Could you try with the [generated external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition)?

Hello 

In the exposes tab nothing appears as you van check in this image:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/47602733/2ee566bf-cfec-4696-b6bd-68e7bc328550)

As you suggested I try also generated external converter: 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/47602733/68db9121-3cb0-41c8-a146-ec512e02a46c)

But from my understanding the device still without any functions available ....

**Comment by Koenkk** [comment]
What color modes does it support?

**Comment by MiAutomations** [comment]
> What color modes does it support?

Only this ones 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/47602733/a227ea49-51db-4f2c-8d06-faa26a4bc668)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
