### ISSUE TITLE
[Wrong device]:  Moes ZS-US2-WH-MS

### ISSUE THREAD

**Issue by hndrk** [Koenkk/zigbee2mqtt#19897]
### Link

https://moeshouse.com/products/us-zigbee-glass-touch-3-way-light-switch?variant=39797103099985

### Model

ZS-US2-WH-MS

### Description

Smart light switch - 2 gang

### Vendor

_TZ3000_18ejxno0

### Picture (link)

https://judgeme.imgix.net/moes/1688615680__0__1knXYkhF__61_UL39KbtL._SL1600_1__original.jpg?auto=format&w=1024

### Database entry

{"id":6,"type":"EndDevice","ieeeAddr":"0xa4c138885c880f13","nwkAddr":4920,"manufId":4417,"manufName":"_TZ3000_18ejxno0","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,0],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0}},"genBasic":{"attributes":{"65503":" V ,\u0011 V ,\u0011","65506":55,"65508":0,"65534":0,"appVersion":80,"modelId":"TS0012","manufacturerName":"_TZ3000_18ejxno0","powerSource":3,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0029e7307d","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0029e7307d","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":80,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1794938824},"lastSeen":1701135713039,"defaultSendRequestWhen":"immediate"}

### Notes

Seems like the glass touch version is labelled the same as the normal version. Would be good if you could select between the two. In the glass touch version, the buttons are top and bottom, as opposed to left and right.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
