### ISSUE TITLE
frytur not updating

### ISSUE THREAD

**Issue by drumstick77** [Koenkk/zigbee2mqtt#19904]
### What happened?

Since the last update, frytur update kept trying for days..everytime I restarted HA, it will then re attempt the update again, but never completed it.

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

20211217

### Adapter

frytur

**Comment by drumstick77** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1726110/6e2e0245-6fcf-4a07-a293-2e11775e9515)

**Comment by Koenkk** [comment]
This will be fixed in the 1 December release.

**Comment by drumstick77** [comment]
Ah. Many thanks! I thought it's me only. Cheers

**Comment by drumstick77** [comment]
Hi, has it been released yet? Sorry, I'm in UK, not sure the timezone of when this should be released today. Cheers

**Comment by drumstick77** [comment]
Hi, received updates but it is still not updating fyrtur

**Comment by drumstick77** [comment]
restarted HA, restarted host, restarted just the add-on and still getting this 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1726110/1570c0c3-e2bb-4ae8-870c-8e4692f7a983)

**Comment by Koenkk** [comment]
Could you try to force-remove the device and re-pair it?
