### ISSUE TITLE
[New device support]: TuYa MTG235-ZB-RL

### ISSUE THREAD

**Issue by Ferugf** [Koenkk/zigbee2mqtt#19922]
### Link

https://pl.aliexpress.com/item/1005005633355282.html?spm=a2g0o.order_list.order_list_main.27.67515e5bpE050Q&gatewayAdapt=glo2pol

### Database entry

{"id":17,"type":"Router","ieeeAddr":"0x3425b4fffee69b62","nwkAddr":63151,"manufId":4098,"manufName":"_TZE204_clrdrnya","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000e\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0012","65506":31,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE204_clrdrnya","powerSource":1,"zclVersion":3,"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1701274301826,"defaultSendRequestWhen":"immediate"}

### Comments

 ZigBee 24G ceiling -  24G MmWave radar human presence motion sensor, similar to MTG275-ZB-RL
    Router
Model Zigbee   TS0601
Producent Zigbee   _TZE204_clrdrnya
is wrong detected as MTG075-ZB-RL

![24-5,8G](https://github.com/Koenkk/zigbee2mqtt/assets/137459852/c763447c-b517-460c-b50e-dcbdece2829e)

**Comment by srpablillo** [comment]
I am also interested in this same device. I can integrate to ZHA but no info is shown. 

I am running HASSOS on a RP5, last soft version available right now.


![IMG_4954](https://github.com/user-attachments/assets/066c973e-1d46-4600-86fc-74f6afc6109c)

**Comment by austin7777** [comment]
I have one too!
