### ISSUE TITLE
[New device support]: Умный Zigbee 3.0 датчик открытия дверей и окон с Алисой и Google Assistant

### ISSUE THREAD

**Issue by usv** [Koenkk/zigbee2mqtt#19939]
### Link

https://www.ozon.ru/product/umnyy-zigbee-3-0-datchik-otkrytiya-dverey-i-okon-s-alisoy-i-google-assistant-1164726426/?avtc=1&avte=2&avts=1701403427

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c13890b5fd6981","nwkAddr":9845,"manufId":4417,"manufName":"_TZE200_ijey4q29","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,3,1280,57346,61184,60928,57344,1,1024],"outClusterList":[3,57346,61184,60928,57344,1],"clusters":{"msIlluminanceMeasurement":{"attributes":{"measuredValue":28408}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}},"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_ijey4q29","powerSource":3,"zclVersion":3,"appVersion":131,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017"}},"ssIasZone":{"attributes":{"iasCieAddr":"0xe0798dfffebc6c0d","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":131,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701403939757,"defaultSendRequestWhen":"immediate"}

### Comments

Спасибо

**Comment by arikoza** [comment]
The opening sensor still does not work, the version of Home Assistant 2024.12.5 and the latest ZHA are installed
