### ISSUE TITLE
[SNZB-01]  Problem after restart zigbee2mqtt - AREQ - ZDO - bindRsp

### ISSUE THREAD

**Issue by JanLoebel** [Koenkk/zigbee2mqtt#19937]
### What happened?

I've paired Sonoff SNZB-01 and then restartet zigbee2mqtt, afterwards the device is not shown anymore in the device tab and I get the following error. If pressed reconfigure and press the button often the error will go back again, but only till I restart zigbee2mqtt, then the same behaviour occurs. 

`Failed to configure '0xbc026efffe896661', attempt 1 (Error: Bind 0xbc026efffe896661/1 msTemperatureMeasurement from '0x00124b0026d166a2/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))`

Any ideas?

### Zigbee2MQTT version

1.33.2 commit: 311ea070

### Adapter firmware version

20230507

### Adapter

 zStack3x0

**Comment by upandabout** [comment]
I have the same problem, but it's there right from the start, the button just doesn't work. nothing happens in the action field when pressing the button, but it seams to pair OK...
