### ISSUE TITLE
Unknown Power for Sonoff ZBMINIL2

### ISSUE THREAD

**Issue by jamesonuk** [Koenkk/zigbee2mqtt#19946]
### What happened?

Power is showing up as unknown rather than mains powered
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/5fa1ae80-3a18-4761-af99-c5d311b1fbd3)

It does appear to be set in the converter https://github.com/Koenkk/zigbee-herdsman-converters/blob/47f56c19a3fdec5f23e74f805ff640a931721099/src/devices/sonoff.ts#L66C17-L66C17
but isn't being picked up.   I have reconfigured the device and still now joy

### What did you expect to happen?

Devices shows up as mains powered

### Zigbee2MQTT version

1.33.2 commit: 9996c93

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by N3rdix** [comment]
In my case it is correctly displayed, 1.33.2 as well with a Sonoff Dongle E

**Comment by Koenkk** [comment]
@jamesonuk you probably need to restart z2m after configuring it.

**Comment by jamesonuk** [comment]
> @jamesonuk you probably need to restart z2m after configuring it.

I have restarted several times and it still says unknown.   I will try and delete and then rea-adding it tomorrow.   It did do an OTA update soon after first pairing, could it have been an issue with the original firmware and the device is stuck with that now?
