### ISSUE TITLE
[New device support]: Умный Zigbee 3.0 датчик температуры и влажности с Алисой и Google Assistant версия Lite

### ISSUE THREAD

**Issue by usv** [Koenkk/zigbee2mqtt#19940]
### Link

https://www.ozon.ru/product/umnyy-zigbee-3-0-datchik-temperatury-i-vlazhnosti-s-alisoy-i-google-assistant-versiya-lite-1164694860/?_bctx=CAQQi8kG&asb=Sd87Pu5BS5pMOMo1OO79d3oRlNLdcA7FwTCLEPp3MVY%253D&asb2=_YXjfpy52EjZoy9VTBUqRWH6I2iUTCCAos7Dm6E3cq-clu_p1yoeirDIalfJ6IWq&avtc=1&avte=2&avts=1701404315&hs=1

### Database entry

{"id":3,"type":"EndDevice","ieeeAddr":"0xa4c1388745f6a74f","nwkAddr":50562,"manufId":4417,"manufName":"_TZE200_ysm4dsb1","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,3,57346,61184,60928,57344,1,1026,1029],"outClusterList":[],"clusters":{"msTemperatureMeasurement":{"attributes":{"measuredValue":2670}},"msRelativeHumidity":{"attributes":{"measuredValue":4120}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_ysm4dsb1","powerSource":3,"zclVersion":3,"appVersion":130,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":130,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701404448330,"defaultSendRequestWhen":"immediate"}

### Comments

Спасибо

**Comment by mrmaximas** [comment]
This is english speaking community, not russian. Please write in english only. Thank You.
