### ISSUE TITLE
Nodon SIN-4-1-20 error at zigbee2mqtt startup

### ISSUE THREAD

**Issue by chris-1243** [Koenkk/zigbee2mqtt#19957]
### What happened?

I have just updated Zigbee2mqtt to the latest version (1.34.0) and I have the following errors. It is something which was not present on the previous version.

The device seems to work some minutes after the boot.

Maybe the firmware of the sonoff dongle-P ?

### How to reproduce it (minimal and precise)

update from zigbee2mqtt 1.33.2 to 1.34.0 and Nodon module SIN-4-1-2perfectly working and already paired to the network

### Zigbee2MQTT version

1.34.0 (commit: aae7312)

### Adapter firmware version

20231112

### Adapter

Sonoff Dongle-P

### Debug log

The log et startup with zigbee-herdsman log as well

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13527072/log.txt)

**Comment by Koenkk** [comment]
@AlexisPolegato could you check this? Looks like some versions don't support `nodonTransitionTime`

**Comment by AlexisPolegato** [comment]
Ok, I've removed it here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/6606

I will investigate this later

**Comment by chris-1243** [comment]
Thanks for your support. Should I try the latest dev to see if the problem is solved already?

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/6606 , thanks @AlexisPolegato 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
