### ISSUE TITLE
[New device support]: Zigbee Temperature & Humidity Sensor (Powered by Tuya)

### ISSUE THREAD

**Issue by Lucas-Baek-HYU** [Koenkk/zigbee2mqtt#19980]
### Link

https://www.aliexpress.com/item/1005005897159196.html?spm=a2g0o.order_list.order_list_main.30.363e140fQQ8bAf

### Database entry

{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c1383f01cb8ab1","nwkAddr":4780,"manufId":4417,"manufName":"_TZE200_vvmbj46n","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0007��,i\u0007��,i\u0007��,i\u0007��,i\u001e��,i\u001e��,i\u001e��,i\u001e��,i","65506":56,"65508":1,"modelId":"TS0601","manufacturerName":"_TZE200_vvmbj46n","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701531761161} {"id":3,"type":"EndDevice","ieeeAddr":"0xa4c1388ed13c2f0f","nwkAddr":59905,"manufId":4417,"manufName":"_TZE200_vvmbj46n","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":56,"65508":1,"modelId":"TS0601","manufacturerName":"_TZE200_vvmbj46n","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701532144268} {"id":4,"type":"EndDevice","ieeeAddr":"0xa4c1387f1cfff033","nwkAddr":38756,"manufId":4417,"manufName":"_TZE200_vvmbj46n","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":56,"65508":1,"modelId":"TS0601","manufacturerName":"_TZE200_vvmbj46n","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701532220083}

### Comments

It is a newly purchased temperature and humidity sensor, and although it has been successfully connected to MQTT, it has not received the sensor's data properly.

I don't think that product is supported yet.
I'd like to ask you to check.

**Comment by Operrr** [comment]
I'll join the question! The thermometer is quite popular and it is very strange that there is no support without using an external converter
