### ISSUE TITLE
Moes thermostat: Current heating setpoint steps now possible in .5 degree steps, although device doesn't support it

### ISSUE THREAD

**Issue by PulsarFX** [Koenkk/zigbee2mqtt#19991]
### What happened?

Yesterday I upgraded z2m to v1.34.0 from 1.33.x (I think!)
The z2m interface for BHT-002-GCLZB thermostat allows to set .5 degree steps for the current heating setpoint. This is not supported by the device as documented in #14965. 
Now, if I set a .5 value via z2m, the device changes this to 0.0 on the device.

In Home Assistant I can see this as attribute: `target_temp_step: 0.5`

### What did you expect to happen?

- either publish it as the right value with .5° (if the device can handle it) or only allow .0° steps

### How to reproduce it (minimal and precise)

- have temperature set to 20.0° on Current heating setpoint
- change to 20.5° with the slider 
   - device will show 00.0° on its display
   - z2m will stay on 20.5°
- refresh browser window
   - z2m will now show 0 for Current heating setpoint

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20210708

### Adapter

zStack3x0

### Debug log

21.5° payload publishes as 0: 
```
MQTT publish: topic 'zigbee2mqtt/Heizung_2', payload '{"child_lock":"UNLOCK","current_heating_setpoint":0,  ...
```
21.0° payload publishes with the acutual value:
```
MQTT publish: topic 'zigbee2mqtt/Heizung_2', payload '{"child_lock":"UNLOCK","current_heating_setpoint":21, ...
```

**Comment by DasRed** [comment]
@Koenkk I will check this with my device

**Comment by PulsarFX** [comment]
Your device looks very different to the one in the z2m docs, which looks exactly like mine.
On yours, there is no house symbol, the numbers are lit, whereas on mine the whole background gets lit.

Your device identifies as _TZE204_5toc8efa where mine identifies as  _TZE200_aoclfnxz

I think yours is a very different device, although the model name is the same. :-/ Seems like yours needs to have its own handling in z2m to not break the old models. (which I doubt will ever see .5 step support, when they released new models with the same name :-(

**Comment by DasRed** [comment]
Or yours need his own handling. Both device types were there in the code. The handling is for a bunch of device types. How ever, maybe you can provide a pull request for this?

**Comment by PulsarFX** [comment]
That's a rather bold move with all the differences from the docs, don't you think? 
There are 8 or more thermostat models in the list, ranging from 6 months to 2 years old. 
Now you change the stepping for all of them to make one model work different, without verifying that the others can handle this change. I think that's a rather good reason, to get your change fixed! Thanks!
Or better, collect user approval for every affected manufacturer code, to see which other thermostat can handle 0.5 steps. Your model needs special handling for temps, so maybe it is special on temp steps, too. 



@Koenkk can your please revert the PR until this is fixed without side effects?

**Comment by DasRed** [comment]
I can see you don't understand. Well, next time just be kinder. Anyway, I made another pull request just for you. https://github.com/Koenkk/zigbee-herdsman-converters/pull/6634

**Comment by PulsarFX** [comment]
I don't understand what you mean. You break it, you fix it ;-)
From the PR I can see, that your model is named BHT-002-GCLZB+ (with + ) ?
Do you have a link to the shop?

The (original/first) BHT-002-GCLZB looks like this:
![BHT-002-GCLZB](https://github.com/Koenkk/zigbee2mqtt/assets/4960210/8a3cba76-09e4-467b-a424-ce442f2d40c5)

I propose to use this chance to get OK / NOK from users with similar devices to get this sorted out. There are lots of issues which request .5 steps. My original ticket is linked many times , quoting moes support, that it doesn't work.

Currently all these devices are treated the same (which may not be correct):
```
model: 'BHT-002-GCLZB'                                   works with 0.5 steps?
modelID: TS0601,  manufacturerName: _TZE200_aoclfnxz       no
modelID: TS0601,  manufacturerName: _TZE200_ztvwu4nk    
modelID: TS0601,  manufacturerName: _TZE204_5toc8efa       yes
modelID: TS0601,  manufacturerName: _TZE200_5toc8efa    
modelID: TS0601,  manufacturerName: _TZE200_ye5jkfsb    
modelID: TS0601,  manufacturerName: _TZE204_aoclfnxz    
modelID: TS0601,  manufacturerName: _TZE200_u9bfwha0    
modelID: TS0601,  manufacturerName: _TZE204_u9bfwha0    

```

Please have a look at the z2m interface, identify the manufacturer name and check in z2m  v1.34.0 if you can set .5 degree steps.
If it fails, the device will drop to 0°. (see details in the first post) 

Now it's time to tag all users which have previously reported issues with it. I can start with this later this day.

**Comment by Minims** [comment]
_TZE200_aoclfnxz fails. if using 0,5 steps in z2m the device drops to 0°
and I don't think there is a FW update for it.

**Comment by mhu1987** [comment]
z2m 1.34.0-1
_TZE200_u9bfwha0 drops to 0 using 0,5 steps to set current heating setpoint.
A few updates before, there was no 0,5 steps in home assistant frontend and z2m when using heating setpoint. Since FW doesnt support 0,5 steps, that was better, because you cant accidentally set e.g. 22,5 which will drop to 0,0

**Comment by guny74** [comment]
z2m 1.34.0 same same behavior...

**Comment by TTR6214** [comment]
z2m 1.34.0

I have 
Zigbee Model : TS0601
Zigbee Manufacturer : _TZE200_b6wax7g0
Model : MOES
Manufacturer : BRT-100-TRV

I set 20.5 with z2m, the display showed 21 and then z2m showed 21.
I set 22.5 with the display, z2m showed 23.

**Comment by PulsarFX** [comment]
> z2m 1.34.0 same same behavior... I work over the program .... there you could set x.5 values e.g. 20.5 and than in the UI the it is shown as 20.0, but at the device 20.5.

what Zigbee Manufacturer does it show in z2m for you? (The _TZE... string)

**Comment by PulsarFX** [comment]
> z2m 1.34.0
> 
> I have Zigbee Model : TS0601 Zigbee Manufacturer : _TZE200_b6wax7g0 Model : MOES Manufacturer : BRT-100-TRV
> 
> I set 20.5 with z2m, the display showed 21 and then z2m showed 21. I set 22.5 with the display, z2m showed 23.

If it is this device, https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html 
you are not affected by the PR which introduced the temp drops.

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6634

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by M3te0r** [comment]
Hi,
Not to reopen this issue but I was just searching this problem as I'm facing it with my MOES Thermostat
Model : BHT-006GCZB White
Model identified under zigbee2mqtt : [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb) don't know if that makes a difference
Connectivity : Zigbee
Link : https://fr.aliexpress.com/item/1005004219851802.html?spm=a2g0o.order_list.order_list_main.35.65ec5e5bJ2yhcr&gatewayAdapt=glo2fra
I

I hope the fix also works on this model

Thank you !

**Comment by PulsarFX** [comment]
> Hi, Not to reopen this issue but I was just searching this problem as I'm facing it with my MOES Thermostat Model : BHT-006GCZB White Model identified under zigbee2mqtt : [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb) don't know if that makes a difference Connectivity : Zigbee Link : https://fr.aliexpress.com/item/1005004219851802.html?spm=a2g0o.order_list.order_list_main.35.65ec5e5bJ2yhcr&gatewayAdapt=glo2fra I
> 
> I hope the fix also works on this model
> 
> Thank you !

what does it show for Zigbee Manufacturer in z2m? The '_TZE...' string is what group it is put into ;)

**Comment by M3te0r** [comment]
> > Hi, Not to reopen this issue but I was just searching this problem as I'm facing it with my MOES Thermostat Model : BHT-006GCZB White Model identified under zigbee2mqtt : [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb) don't know if that makes a difference Connectivity : Zigbee Link : https://fr.aliexpress.com/item/1005004219851802.html?spm=a2g0o.order_list.order_list_main.35.65ec5e5bJ2yhcr&gatewayAdapt=glo2fra I
> > I hope the fix also works on this model
> > Thank you !
> 
> what does it show for Zigbee Manufacturer in z2m? The '_TZE...' string is what group it is put into ;)

The Zigbee manufacturer under z2m is _TZE200_aoclfnxz

**Comment by PulsarFX** [comment]
then it's fixed with whole degrees again.

**Comment by Caligo82** [comment]
I just got this one from Moes : _TZE204_aoclfnxz

Since I'm using ZHA I had to use a custom quirk found [here](https://github.com/zigpy/zha-device-handlers/issues/2433#issuecomment-1690198060).
I have the same problem though it seems.  It desn't drop the temps to zero however. If I set half a degree more it'll go up a whole degree. Setting it half a degree lower doesn't change the value. Seems its rounding. However it seems from the quirk used that it'll only transmit t.uint32_t which GPT tells me is an unsigned 32-bit integer data type.  

GPT Quote
> As it stands, using t.uint32_t might restrict the thermostat to whole numbers for the target temperature setting due to the inherent limitation of handling only integers.

What are the steps to verify if it can set 0.5 degree values? I should be able to issue a zigbee command using the developer tools somehow?

**Comment by PulsarFX** [comment]
If you are on ZHA, you would have to switch to z2m first. After this, the steps are in https://github.com/Koenkk/zigbee2mqtt/issues/19991#issuecomment-1842651022
z2m has a native web gui to manage mqtt devices:

![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/4960210/cc6c39f5-7d92-4f15-9faa-d271a833f74f)

**Comment by Caligo82** [comment]
Thanks for your fast reply! I just hoped there was an easier way to help out. May sound silly but migrating to z2m seems like climbing K2 atm. Back when I decided between the two my Skyconnect stick caused me to go the other route.

In the end it's not a deal breaker as it will be using Better Thermostat to use it in Homeassistant. It just gets a bit confused when I trigger manual inputs to a half degree state. If there's any way I can test it with ZHA I would.

**Comment by vobelic** [comment]
> I have this device here. And I can set the value in 0.5 steps. I have tested it. I adjust the code directly in the docker container and then I change the values in 0.5 steps. It works very well.
> 
@DasRed Do you have any reference where you found your model (BHT-002 _TZE204_5toc8efa)? It's almost impossible to reference for that exact model.

On a different note, did anyone have an insight if UNSH/Tuya zigbee thermostats are supported with the herdsman converters?
I'm annoyed by that bug on Moes BHT-002 and was looking at this model: https://www.aliexpress.com/item/1005005963529004.html?spm=a2g0o.productlist.main.7.44e7V0JYV0JYe4

Any clue someone tested it and 0.5 degrees works and is even supported (it really looks very similar platform to BHT-002)?

**Comment by Caligo82** [comment]
I read somewhere that the Wifi-Version isn't impacted by this 0.5 degree bug. I do like the Moes Thermostat, it's a very pretty one. But it seems there are different versions for the same Model... at least visually. I got this one:
![moes-white-wifi-smart-thermostat-for-watergas-boiler-3a](https://github.com/Koenkk/zigbee2mqtt/assets/31889595/99d9fc45-689b-4f90-9b24-1429938a453c)

Bought here:
http://www.aliexpress.com/item/1005005230261106.html

I might actually use all with local tuya instead of Zigbee, should be less problematic overall. Apart from the trojan horses. =]

**Comment by vobelic** [comment]
@Caligo82 but that one also has the .5 bug, i.e. it's not the one listed as _TZE204_5toc8efa as the working with 0.5 steps?

**Comment by Caligo82** [comment]
> @Caligo82 but that one also has the .5 bug, i.e. it's not the one listed as _TZE204_5toc8efa as the only model truly working with 0.5 steps?

Are you sure the Wifi version is also impacted by this?

**Comment by RoGu777** [comment]
Hello @PulsarFX 

I have Z2M v1.34.0 and _TZE204_aoclfnxz.

Setting the heating setpoint to 24.5 leads to 00 at the device

If I can help with logs or debugging - please let me know

**Comment by scalmaa** [comment]
Hello from FRANCE

I have one _TZE204_aoclfnxz used for triying to manage one of my four zones of my heat pump based on geothermal energy.

I'm also wait for a fix to have either the capabilitie to have 1°C step on the z2m interface (in HA) or to have 0.5°C step working withe device.

I don't now if i'm able to help.

Thanks for information

**Comment by PulsarFX** [comment]
I've added _TZE204_aoclfnxz  with "no" to the list of tested devices:  https://github.com/Koenkk/zigbee2mqtt/issues/19991#issuecomment-1842651022
