### ISSUE TITLE
Part of Zigbee2mqtt entities are no longer being provided by the mqtt integration

### ISSUE THREAD

**Issue by cancan92** [Koenkk/zigbee2mqtt#20004]
### What happened?

Hello
I'm using Zigbee2mqtt on HA for 4 years and everything was great. This week suddenly I had a mistake, loosing identities coming from Zigbee2mqtt . Ok I have more than 100 zigbee products but it always was ok.
For exemple : I have a switch for my "Bibliothèque". The status is coming right from zigbee but I can't see the identity "switch.bibliotheque" as usual on lovelace (see picture 1 & 2). It is strange because I can still see "sensor.bibliotheque_power".

From Zigbee2mqtt web frontend I am able to use this switch.bibliotheque (see picture 3) !?!

But thus automations and scripts using those entities are no longer working ...
It looks like lot of zigbee switches, lights are no more reachable when other products like temperature, wall switches are ok

I am using Mosquitto broker version: 6.4.0 and last version 1.34.0-1 of Zigbee2mqtt (it is the same trouble with version Edge) and Conbee II key with a cable. I even tried to change with a new Conbee II but no change.

I also tried to delete from HA such an identity no more reachable. I also deleted the MQTT integration. I launched the integration again. It became no more reachable (see picture 4), even when I delete the equipment from the zigbee network and subscribe it again on the zigbee network !

Do you know what is the mistake ? I'm lost ...

Thanks in advance

<img width="333" alt="Capture d’écran 2023-12-02 à 13 22 46" src="https://github.com/Koenkk/zigbee2mqtt/assets/38877466/c7cc5847-2857-44b8-955d-e3e9e882a41d">

<img width="593" alt="Capture d’écran 2023-12-02 à 14 44 25" src="https://github.com/Koenkk/zigbee2mqtt/assets/38877466/b4518923-d09b-4b8d-a3f3-183a7e1e3dd1">

<img width="1026" alt="Capture d’écran 2023-12-02 à 13 38 37" src="https://github.com/Koenkk/zigbee2mqtt/assets/38877466/e79306f6-046e-4bba-948b-68805790d65a">

<img width="312" alt="Capture d’écran 2023-12-03 à 20 36 45" src="https://github.com/Koenkk/zigbee2mqtt/assets/38877466/3797c7a0-3f09-438b-aca5-ff50b333ebb7">

### What did you expect to happen?

I expected to still see my zigbee switch entities from HA to use with scripts & automations 

### How to reproduce it (minimal and precise)

Alway appends

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

NA

### Adapter

Conbee II

### Debug log

no bug seen on logs

**Comment by cancan92** [comment]
Here is the version of my Conbee II

<img width="682" alt="Capture d’écran 2023-12-04 à 08 35 29" src="https://github.com/Koenkk/zigbee2mqtt/assets/38877466/88e89aa7-f256-4222-9ec5-42b92fb14b1a">

**Comment by DubhAd** [comment]
What version of Home Assistant? You need to be on _at least_ 2023.8.0, but ideally newer.

**Comment by cancan92** [comment]
I have version HA Core 2023.7.3. 
I tried with the lastest version 2023.11..3 without solving the bug. I came back to the previous version

**Comment by DubhAd** [comment]
You need to be on at least 2023.8.0.

Changes were made in Z2M 1.33.0 that require this.

**Comment by cancan92** [comment]
@DubhAd 🥇 THANKS A LOT ! I don't know what I have done before but I just installed again version 2023.11.3 and now it works fine. Thanks again for helping me. It's a so real pleasure to find back my switches and their scripts and automations linked 👍
