### ISSUE TITLE
[New device support]: _TZE204_ue3rzddr Tuya Smart Knob Dimmer Switch

### ISSUE THREAD

**Issue by jollyekb** [Koenkk/zigbee2mqtt#20016]
### Link

https://www.alibaba.com/product-detail/Smart-Knob-Dimmer-Switch-WiFi-Tuya_1600574868597.html

### Database entry

{"id":2,"type":"Router","ieeeAddr":"0xa4c138099d6e6eda","nwkAddr":21784,"manufId":4417,"manufName":"_TZE204_ue3rzddr","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1688527822816,"defaultSendRequestWhen":"immediate"}

### Comments

Request support

### Supported color modes

No

### Color temperature range

No

**Comment by jollyekb** [comment]
Can I do something?

**Comment by arrivavorkuta** [comment]
Help!

**Comment by arrivavorkuta** [comment]
https://aliexpress.ru/item/1005005791266171.html?click_id=9mTZ21OIQuZnRYk&af=2926_Y6Ljx9&cn=2uruscsunnfewwax9dvnaue0hp2yfjr8&cv=2&cv_source=default&dp=2uruscsunnfewwax9dvnaue0hp2yfjr8&utm_campaign=2926_Y6Ljx9&utm_content=2&utm_medium=cpa&utm_source=aerkol&aff_fcid=7c547efefaee40c4bfe2d2b90fd17396-1714554419953-07156-_DkdG55l&aff_fsk=_DkdG55l&aff_platform=api-new-link-generate&sk=_DkdG55l&aff_trace_key=7c547efefaee40c4bfe2d2b90fd17396-1714554419953-07156-_DkdG55l&terminal_id=04614618fa0845eda99e3c9fdf503cc6&sku_id=12000034368420074
