### ISSUE TITLE
SYMFONISK sound remote gen2 partially broken in 1.34.0

### ISSUE THREAD

**Issue by SaschaRH** [Koenkk/zigbee2mqtt#20020]
### What happened?

After updating  Zigbee2MQTT to 1.34 the '.' and '..'  (dots_1_initial_press/long_press...) buttons are no longer working. Got it to work again after rollback to 1.33.2.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

**Comment by ChrisHaPunkt** [comment]
Same here, 
1 and 2 dots:
Long press: not working
Single Press: not working
Double Press: working

Downgrade to 1.33.2-1 and the long and single press working again

**Comment by markus-barta** [comment]
**Same problem here: 1 and 2 dot buttons:**
Single Press, Long press: not working
Double Press: working

**Comment by TeHashX** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/19971#issuecomment-1837231063

**Comment by SaschaRH** [comment]
Closed since it's a duplicate of [#19971 ]

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/19971
