### ISSUE TITLE
Zigbe2MQTT blackout?

### ISSUE THREAD

**Issue by LeoeLeoeL** [Koenkk/zigbee2mqtt#20026]
### What happened?

I'm experiencing the temporal unavailability of Zigbee2mqtt

### What did you expect to happen?

I expect zigbee2mqtt operative 14/7 without "holes"

### How to reproduce it (minimal and precise)

Wait until it happens

![image](https://github.com/Koenkk/zigbee2mqtt/assets/65825223/dc36901b-0315-4e09-b008-acc3ca84ecc4)
The only one with continuous row is Luce Camera C because is under HUE bridge.
The hole is 7 minutes 43 second long

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20230507

### Adapter

Sonoff Dongle P zStack3x0

**Comment by DubhAd** [comment]
What's in the Zigbee2MQTT log file for that time?

**Comment by LeoeLeoeL** [comment]
info  2023-12-04 20:15:18: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
info  2023-12-04 20:15:18: Disconnecting from MQTT server
info  2023-12-04 20:15:18: Stopping zigbee-herdsman...
warn  2023-12-04 20:15:26: Failed to ping 'Luce Cucina D2' (attempt 2/2, Read 0x14b457fffe47b259/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)))
info  2023-12-04 20:15:29: MQTT publish: topic 'zigbee2mqtt/Luce Cucina D2/availability', payload '{"state":"offline"}'
info  2023-12-04 20:15:31: MQTT publish: topic 'zigbee2mqtt/Luce Esterna Mansarda/availability', payload '{"state":"offline"}'
info  2023-12-04 20:15:31: Stopped zigbee-herdsman
info  2023-12-04 20:15:31: Stopped Zigbee2MQTT

info  2023-12-04 20:22:58: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-04.20-22-57' filename: log.txt
info  2023-12-04 20:22:58: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
info  2023-12-04 20:22:58: Starting zigbee-herdsman (0.25.0)
info  2023-12-04 20:23:00: zigbee-herdsman started (resumed)
info  2023-12-04 20:23:00: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20230507,"transportrev":2},"type":"zStack3x0"}'
info  2023-12-04 20:23:01: Set transmit power to '20'
info  2023-12-04 20:23:01: Currently 70 devices are joined:

I had 2 very short holes (15 seconds) yesterday evening and today morning

--yesterday evening
info  2023-12-03 20:17:51: Restarting Zigbee2MQTT
info  2023-12-03 20:17:51: MQTT publish: topic 'zigbee2mqtt/bridge/response/restart', payload '{"data":{},"status":"ok","transaction":"uic5q-1"}'
info  2023-12-03 20:17:52: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
info  2023-12-03 20:17:52: Disconnecting from MQTT server
info  2023-12-03 20:17:52: Stopping zigbee-herdsman...
info  2023-12-03 20:18:05: Stopped zigbee-herdsman
info  2023-12-03 20:18:05: Stopped Zigbee2MQTT

info  2023-12-03 20:18:05: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-03.20-18-05' filename: log.txt
info  2023-12-03 20:18:05: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
info  2023-12-03 20:18:06: Starting zigbee-herdsman (0.25.0)
info  2023-12-03 20:18:06: zigbee-herdsman started (resumed)
info  2023-12-03 20:18:06: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20230507,"transportrev":2},"type":"zStack3x0"}'
info  2023-12-03 20:18:06: Set transmit power to '20'
info  2023-12-03 20:18:06: Currently 70 devices are joined:

-- today morning
info  2023-12-04 10:57:42: Restarting Zigbee2MQTT
info  2023-12-04 10:57:42: MQTT publish: topic 'zigbee2mqtt/bridge/response/restart', payload '{"data":{},"status":"ok","transaction":"hhhzm-2"}'
info  2023-12-04 10:57:42: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
info  2023-12-04 10:57:42: Disconnecting from MQTT server
info  2023-12-04 10:57:42: Stopping zigbee-herdsman...
info  2023-12-04 10:57:55: Stopped zigbee-herdsman
info  2023-12-04 10:57:55: Stopped Zigbee2MQTT

info  2023-12-04 10:57:55: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-04.10-57-55' filename: log.txt
info  2023-12-04 10:57:56: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
info  2023-12-04 10:57:56: Starting zigbee-herdsman (0.25.0)
info  2023-12-04 10:57:56: zigbee-herdsman started (resumed)
info  2023-12-04 10:57:56: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20230507,"transportrev":2},"type":"zStack3x0"}'
info  2023-12-04 10:57:56: Set transmit power to '20'
info  2023-12-04 10:57:56: Currently 70 devices are joined:

**Comment by DubhAd** [comment]
Ok, so _something_ is causing Z2M to crash/restart. Look for the _end_ of the previous log file and any container/OS logs.

**Comment by LeoeLeoeL** [comment]
Its' something "unbelievable".
I migrated from Deconz due to restarts of the application (10 seconds) and find this.
In Italy there is the following way of saying: "Cadere dalla padella nella brace".
