### ISSUE TITLE
1.34.0: Lots of `Cannot read properties of undefined (reading 'isDevice')`

### ISSUE THREAD

**Issue by samip5** [Koenkk/zigbee2mqtt#20035]
### What happened?

Upgraded to 1.34.0 and noticed a lot of errors when adding devices as an example.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20220219

### Adapter

Tube's cc2652p2 PoE coordinator

**Comment by samip5** [comment]
<img width="327" alt="Screenshot 2023-12-05 at 12 42 34" src="https://github.com/Koenkk/zigbee2mqtt/assets/1703002/f637dc7d-1061-45b0-9a5c-950ae7fe4f93">

As an example

**Comment by Koenkk** [comment]
Please provide the debug log.

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by samip5** [comment]
Currently running the dev version in which I don't see those appearing anymore so maybe it's not actually a problem?

**Comment by Koenkk** [comment]
Could already have been fixed there, closing this for now.
