### ISSUE TITLE
[dev] Error calling get_group_membership

### ISSUE THREAD

**Issue by juanjux** [Koenkk/zigbee2mqtt#2003]
# Bug Report

Doing an MQTT call to `get_group_membership` fails.

## What happened

Issuing a call for a device a device that in theory is in a group (added to the conf and returned by the groups mqtt call) but doesn't work inside (separate issue, I guess) like `zigbee2mqtt/bridge/device/TerrazaDespacho1/get_group_membership` writes on the log:

```
  zigbee2mqtt:debug 9/20/2019, 9:31:24 AM Received MQTT message on 'zigbee2mqtt/bridge/device/TerrazaDespacho1/get_group_membership' with data ''
  zigbee2mqtt:info 9/20/2019, 9:31:24 AM 0x0017880104a5d661 is in groups [] and its remaining group capacity is 25
  zigbee2mqtt:error 9/20/2019, 9:31:24 AM Failed to call 'DeviceGroupMembership' 'onMQTTMessage' (TypeError: this.publishEntityState is not a function
    at DeviceGroupMembership.onMQTTMessage (/app/lib/extension/deviceGroupMembership.js:39:14))
```

For other, working devices, it also fails and writes to the log:

```
  zigbee2mqtt:debug 9/20/2019, 9:35:47 AM Received MQTT message on 'zigbee2mqtt/bridge/device/PiscinaBalcon2/get_group_membership' with data ''
  zigbee2mqtt:error 9/20/2019, 9:35:47 AM Failed to call 'DeviceGroupMembership' 'onMQTTMessage' (TypeError: Cannot read property 'modelID' of null
    at Zigbee.resolveEntity (/app/lib/zigbee.js:154:82))
```

## What did you expect to happen

Get the group membership response on the logs.

## How to reproduce it (minimal and precise)

Using latest dev as of today.

## Debug Info
zigbee2mqtt version: 1.6.0-dev #e9a336f
CC253X firmware version: 20190619 (source_routing)

**Comment by Koenkk** [comment]
Fixed, thanks!
