### ISSUE TITLE
LEDVANCE 4058075729384 brightness transition from OFF to ON doesn't work

### ISSUE THREAD

**Issue by andarotajo** [Koenkk/zigbee2mqtt#20043]
### What happened?

When turning the light strip (https://www.zigbee2mqtt.io/devices/4058075729384.html) ON with a transition set up, it immediately jumps to the specified brightness instead of transitioning.

The other situations work with a transition from what I've tested:
- switching the state to OFF
- changing the brightness when it's ON

Noticed this first in Home Assistant but tried it on the frontend too

### What did you expect to happen?

Transitioning of the brightness when turning the light strip ON

### How to reproduce it (minimal and precise)

Set up a transition in the specific settings of the light strip and change the state from OFF to ON

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20210708

### Adapter

SONOFF ZBdongle-P

**Comment by arnevanhove** [comment]
This topic did not get any responses but I have exactly the same issue with https://www.zigbee2mqtt.io/devices/4058075729148.html#ledvance-4058075729148

Transitioning in HA doesn't work. When trying to configure a transition time in the bulb itself, it only works when the lamp goes from ON to OFF. The transition time doesn't seem to work from OFF to ON. Could this be a firmware issue? 

'0xf0d1b8be240b3217':
  friendly_name: Overloop 1ste lamp
  transition: 2
