### ISSUE TITLE
Legrand 067772

### ISSUE THREAD

**Issue by vlehko** [Koenkk/zigbee2mqtt#20041]
### What happened?

after last update of zigbee2mqtt I started to get an error message for Legrand 067772 in the log file once I tried to turn off dimmer option

error 2023-12-05 11:50:08: Publish 'set' 'device_mode' to 'Svetlo_Vstupna_Chodba' failed: 'Error: Write 0x0004740000241682/1 manuSpecificLegrandDevices({"0":{"value":256,"type":9}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

### What did you expect to happen?

after last update of zigbee2mqtt I started to get an error message for Legrand 067772 in the log file once I tried to turn off dimmer option
can you please help to fix this issue ?

error 2023-12-05 11:50:08: Publish 'set' 'device_mode' to 'Svetlo_Vstupna_Chodba' failed: 'Error: Write 0x0004740000241682/1 manuSpecificLegrandDevices({"0":{"value":256,"type":9}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by xygreg** [comment]
Hi,
I have the same issue ... same error with Status 'UNSUPPORTED_ATTRIBUTE' when I want to change dimmer_off to dimmer_on, brightness ...
I'am using conbee3 with jeedom z2m 1.39.1

some solution ?
I think that Legrand 067772 device is no more compatible with dimmer/brightness options ... maybe firmware update ?
thanks
