### ISSUE TITLE
BHT-002-GBLZBW erroneous values (spikes)

### ISSUE THREAD

**Issue by remezen** [Koenkk/zigbee2mqtt#20049]
### What happened?

[https://aliexpress.ru/item/4001290635850.html](https://aliexpress.ru/item/4001290635850.html)

Sometimes everything is ok:
![Снимок экрана 2023-12-05 205229](https://github.com/Koenkk/zigbee2mqtt/assets/2427989/3b8e762c-fb3d-4c00-b202-79194f5ba63f)

And sometimes it reports 1 million degrees temperature spikes
![Снимок экрана 2023-12-05 204017](https://github.com/Koenkk/zigbee2mqtt/assets/2427989/7a6af813-cc84-4415-bcdd-744be5af8249)

![Снимок экрана 2023-12-05 204320](https://github.com/Koenkk/zigbee2mqtt/assets/2427989/68c93b47-890a-4113-a70b-48ca39a15372)

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20220219

### Adapter

SONOFF ZB Dongle-P

**Comment by KameDomotics** [comment]
I also have some problems with the latest Z2m update.

**Comment by remezen** [comment]
Maybe give users an option to set limits for values in configuration? I see there's a lot of similar cases with different devices.
