### ISSUE TITLE
[New device support]: Haozee Human Presence Sensor, Tuya Zigbee Millimeter Radar Wave Presence Detection Sensor

### ISSUE THREAD

**Issue by northmendo** [Koenkk/zigbee2mqtt#20062]
### Link

https://www.amazon.com/dp/B0CG62MCFF?psc=1&ref=ppx_yo2ov_dt_b_product_details

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0xa4c138a46c0be017","nwkAddr":61477,"manufId":4417,"manufName":"_TZE204_kyhbrfyl","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1701819558663,"defaultSendRequestWhen":"immediate"}

### Comments

I got this message after pairing. Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE204_kyhbrfyl'

**Comment by Koenkk** [comment]
`_TZE204_kyhbrfyl` is supported now.
