### ISSUE TITLE
Sensor seems sporadic to be ignored

### ISSUE THREAD

**Issue by JW-Schuetz** [Koenkk/zigbee2mqtt#20074]
### What happened?

One of my temperatur/humidity/pressure sensors seems to be ignored after a couple of days working nice.
I see no more a change in measured values of this sensor.
The sensor is supported by Zigbee2MQTT:  Xiaomi WSDCGQ11LM.

Inspecting the Zigbee2MQTT-data of this sensor I see in the "Clusters" tab only one entry:

 -------------
| Endpoint 1 |
 ------------

which is empty.

I tested the sensor in an other context and it is working fine.

Trying to delete the sensor out of Zigbee2MQTT failed with the message "YAML-Exception: duplicated mapping key". Now I still see the sensor in the devices tab but cannot delete it. Restart MA don't help.

### What did you expect to happen?

That I receive actual measurement data from the sensor.

I would expect more clusters in the Zigbee2MQTT-data of this sensor. 
A working sensor has the following cluster-structure:

     -------------
    | Endpoint 1 |
     ------------
            |
            |                    ---------------
             ---------    | Input clusters |
            |                   ---------------
            |                             |
            |                            .
            |                            .
            |                            .
            |
            |                    -----------------
             ---------    | Output clusters |
                                ------------------
                                         |
                                         .
                                         .
                                         .

### How to reproduce it (minimal and precise)

That seems to be difficult because the effect is sporadic.

I am interested in some advice to enable debugging this effect, I am a newbee in Homeassistant/Zigbee2MQTT.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

0x26780700

### Adapter

conbee II

**Comment by alexmigf** [comment]
I have a similar problem. They were working just fine for a lot of months and not suddenly all of them stop working and don't update.

**Comment by lukas-kraus** [comment]
Same problem here 🥺

**Comment by alexmigf** [comment]
In my case it was the battery, because this sensors do a lot of pings every day and discharge faster. My steps:

* Force the removal on Zigbee2MQTT
* Replace the battery
* Sync again within Zigbee2MQTT
