### ISSUE TITLE
FUT035Z+ does not report status when turned on by dimmer contact

### ISSUE THREAD

**Issue by bzumik1** [Koenkk/zigbee2mqtt#20079]
### What happened?

Hello,

I currently have several Miboxer Zigbee Led Strip Controllers, specifically the FUT035Z CCT DC12-24V model, connected to Zigbee2mqtt. Interestingly, these controllers are detected as TuYa TS0502B devices.

Each of these controllers is equipped with an input for a manual push button, offering functionality such as short presses for on/off and long presses for dimming.

However, I've encountered an issue where using the manual push button doesn't trigger the controller to report its status back to Home Assistant. Consequently, if I employ the manual push button to turn on the device, Home Assistant remains unaware of the updated status (e.g., if it was turned on manually, Home Assistant still registers it as off).

I've taken the initiative to contact the manufacturer regarding this matter. They have responded and provided a video demonstrating that this is not an issue with their gateway. https://github.com/Koenkk/zigbee2mqtt/assets/32042186/c2025177-c17d-468c-a3ce-f4250a9ebc01

Despite this, the discrepancy persists, and I'm seeking further assistance or advice on how to address this and ensure that manual control changes are accurately reflected in Home Assistant.

Thank you for your time and assistance.

P.S. it is not only issue on my side, but others are facing this too https://community.home-assistant.io/t/miboxer-led-strip-controller-does-not-report-back-status/608884

### What did you expect to happen?

I expect the state of the light to be reported back to HomeAssistent/MQTT.

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

20230507

### Adapter

sonoff zigbee 3.0 usb

**Comment by modo1302** [comment]
Hi, any news on this case? I'm experiencing the same issue.
