### ISSUE TITLE
scene_store on devices doesn't work anymore

### ISSUE THREAD

**Issue by Luligu** [Koenkk/zigbee2mqtt#20076]
### What happened?

With MQTT:
& "C:\Program Files\mosquitto\mosquitto_pub" -h raspberrypi.local -t 'zigbee2mqtt/Guest room Wardrobe light strip/set' -m '{\"scene_store\":{\"ID\": 1, \"name\": \"OFF\"}}'
or directly with frontend you get 
Error 2023-12-06 17:35:19Publish 'set' 'scene_store' to 'Guest room Wardrobe light strip' failed: 'Error: Not a group'

### What did you expect to happen?

To be able to store a scene either with frontend or MQTT

### How to reproduce it (minimal and precise)

Just try to add a scene to a device with frontend or MQTT

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20230507

### Adapter

SONOFF 

### Debug log

Error 2023-12-06 17:35:19Publish 'set' 'scene_store' to 'Guest room Wardrobe light strip' failed: 'Error: Not a group'
Zigbee2MQTT version [1.34.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.34.0) commit: [56589dcc]
Coordinator type zStack3x0
Coordinator revision 20230507
Coordinator IEEE Address 0x00124b00257c8fee
Frontend version 0.6.147
Zigbee-herdsman-converters version 15.130.1
Zigbee-herdsman version 0.25.0

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
