### ISSUE TITLE
Wrong device PC311-Z-TY

### ISSUE THREAD

**Issue by Pmachat** [Koenkk/zigbee2mqtt#20095]
### What happened?

my device is recognized as _TZE200_rks0sgb7 but the data is incorrect.
![IMG_0900](https://github.com/Koenkk/zigbee2mqtt/assets/81045757/7dd54e8e-1c97-472d-95e6-a00f520b8319)
![IMG_0899](https://github.com/Koenkk/zigbee2mqtt/assets/81045757/b4b0a37b-e545-4a0f-b3a5-3c165f6f46f3)
![Z2M_EARU_Expose](https://github.com/Koenkk/zigbee2mqtt/assets/81045757/ada89f7e-39b9-4906-a7af-f1f8b97f5282)

I have no frequency values, a wrong voltage value.....

### What did you expect to happen?

I hope to have the right information: frequency, voltage, frequency

### Zigbee2MQTT version

    1.34.0 commit: 56589dcc

### Adapter firmware version

    20210708

### Adapter

sonoff usb stick

### Debug log

debug 2023-12-07 18:45:44Received Zigbee message from '0xb43a31fffe7b9138', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,74],"type":"Buffer"},"datatype":2,"dp":104}],"seq":43008}' from endpoint 1 with groupID 0
error 2023-12-07 18:45:44Exception while calling fromZigbee converter: Value '74' is not allowed, expected one of 0,1}
debug 2023-12-07 18:45:44Error: Value '74' is not allowed, expected one of 0,1 at Object.from (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:411:27) at Object.convert (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:1173:57) at Receive.onDeviceMessage (/opt/zigbee2mqtt/lib/extension/receive.ts:150:51) at EventEmitter.emit (node:events:402:35) at EventBus.emitDeviceMessage (/opt/zigbee2mqtt/lib/eventBus.ts:102:22) at Controller.<anonymous> (/opt/zigbee2mqtt/lib/zigbee.ts:108:27) at Controller.emit (node:events:390:28) at Controller.selfAndDeviceEmit (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14) at Controller.onZclOrRawData (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:738:18) at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70)

**Comment by Pmachat** [comment]
Hello,
It's ok with an external converter
[https://github.com/Koenkk/zigbee2mqtt/issues/18734](url)

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;
const {Buffer} = require('buffer');

const valueConverter = {
divideBy10: tuya.valueConverterBasic.divideBy(10),
divideBy100: tuya.valueConverterBasic.divideBy(100),
divideBy1000: tuya.valueConverterBasic.divideBy(1000),
};

const definition = {
fingerprint: [
{
modelID: 'TS0601',
manufacturerName: '_TZE200_rks0sgb7',
},
],
model: 'TS0601_Bidirectional_Energy_Meter_with_80A_Current_Clamp',
vendor: 'TuYa',
description: 'Bidirectional Energy Meter with 80A Current Clamp',
fromZigbee: [tuya.fz.datapoints],
toZigbee: [tuya.tz.datapoints],
onEvent: tuya.onEventSetTime,
configure: tuya.configureMagicPacket,
whiteLabel: [ tuya.whitelabel('Tuya', 'PJ-1203A', 'Bidirectional Energy Meter with 80A Current Clamp', ['_TZE200_rks0sgb7']), ],
// whiteLabel: [{vendor: 'EARU', model: 'PJ-1203A'}],
exposes: [ //only report data
e.ac_frequency(),
exposes.numeric('total_power_A', ea.STATE).withUnit('W').withDescription('Total power A'),
exposes.numeric('total_power_B', ea.STATE).withUnit('W').withDescription('Total power B'),
exposes.numeric('total_power_AB', ea.STATE).withUnit('W').withDescription('Total power A'),
exposes.numeric('voltage', ea.STATE).withUnit('V').withDescription('Voltage'),
exposes.numeric('current_A', ea.STATE).withUnit('A').withDescription('Current A'),
exposes.numeric('current_B', ea.STATE).withUnit('A').withDescription('Current B'),
exposes.numeric('power_factor_A', ea.STATE).withUnit('%').withDescription('Instantaneous measured power factor A'),
exposes.numeric('power_factor_B', ea.STATE).withUnit('%').withDescription('Instantaneous measured power factor B'),
exposes.numeric('power_direction A', ea.STATE).withDescription('Power direction A 0/1 for forward/reverse'),
exposes.numeric('power_direction B', ea.STATE).withDescription('Power direction B 0/1 for forward/reverse'),
exposes.numeric('energy_forward_A', ea.STATE).withUnit('kWh').withDescription('Total energy A forward'),
exposes.numeric('energy_forward_B', ea.STATE).withUnit('kWh').withDescription('Total energy B forward'),
exposes.numeric('energy_reverse_A', ea.STATE).withUnit('kWh').withDescription('Total energy A reverse'),
exposes.numeric('energy_reverse_B', ea.STATE).withUnit('kWh').withDescription('Total energy B reverse'),
exposes.numeric('update_frequency', ea.STATE).withUnit('sec').withDescription('Update frequency'),
],

meta: {
    tuyaDatapoints: [//only report data
      [111, 'ac_frequency', tuya.valueConverter.divideBy100],
      [101, 'total_power_A', tuya.valueConverter.divideBy10],
      [105, 'total_power_B', tuya.valueConverter.divideBy10],
      [115, 'total_power_AB', tuya.valueConverter.divideBy10],
      [112, 'voltage', tuya.valueConverter.divideBy10],
      [113, 'current_A', tuya.valueConverter.divideBy1000],
      [114, 'current_B', tuya.valueConverter.divideBy1000],
      [110, 'power_factor_A', tuya.valueConverter.divideBy100],
      [121, 'power_factor_B', tuya.valueConverter.divideBy100],
      [102, 'power_direction A', tuya.valueConverter.raw],
      [104, 'power_direction B', tuya.valueConverter.raw],
      [106, 'energy_forward_A', tuya.valueConverter.divideBy100],
      [108, 'energy_forward_B', tuya.valueConverter.divideBy100],
      [107, 'energy_reverse_A', tuya.valueConverter.divideBy100],
      [109, 'energy_reverse_B', tuya.valueConverter.divideBy100],
      [129, 'update_frequency' , tuya.valueConverter.raw],
    ],
},
};

module.exports = definition;`

**Comment by Koenkk** [comment]
Could you make a pull request to update the code?

**Comment by Pmachat** [comment]
I'm sorry but I don't know how to do it :-(

**Comment by Koenkk** [comment]
Your code looks the same as the [original one](https://github.com/Koenkk/zigbee-herdsman-converters/blob/83330486b73d23d71c539c4e6a6185d9f1758fdf/src/devices/tuya.ts#L6787), what changes did you make to fix your issues?

**Comment by OwlBawl** [comment]
> Your code looks the same as the [original one](https://github.com/Koenkk/zigbee-herdsman-converters/blob/83330486b73d23d71c539c4e6a6185d9f1758fdf/src/devices/tuya.ts#L6787), what changes did you make to fix your issues?

With the provided **original** code I have mismathed values exposed for 2 clamp _TZE200_rks0sgb7

But with the converter from git issue it's just fine for EARU clamp meter (the same as listed but 2 clamps)

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;
const {Buffer} = require('buffer');

const valueConverter = {
divideBy10: tuya.valueConverterBasic.divideBy(10),
divideBy100: tuya.valueConverterBasic.divideBy(100),
divideBy1000: tuya.valueConverterBasic.divideBy(1000),
};

const definition = {
fingerprint: [
{
modelID: 'TS0601',
manufacturerName: '_TZE200_rks0sgb7',
},
],
model: 'TS0601_Bidirectional_Energy_Meter_with_80A_Current_Clamp',
vendor: 'TuYa',
description: 'Bidirectional Energy Meter with 80A Current Clamp',
fromZigbee: [tuya.fz.datapoints],
toZigbee: [tuya.tz.datapoints],
onEvent: tuya.onEventSetTime,
configure: tuya.configureMagicPacket,
whiteLabel: [ tuya.whitelabel('TuYa', 'PJ-1203A', 'Bidirectional Energy Meter with 80A Current Clamp', ['_TZE200_rks0sgb7']), ],
// whiteLabel: [{vendor: 'EARU', model: 'PC311-Z-TY'}],
exposes: [ //only report data
exposes.numeric('frequency_ac', ea.STATE).withUnit('Hz').withDescription('Frequency'),
exposes.numeric('power_A', ea.STATE).withUnit('W').withDescription('Power A'),
exposes.numeric('power_B', ea.STATE).withUnit('W').withDescription('Power B'),
exposes.numeric('total_power', ea.STATE).withUnit('W').withDescription('Total power'),
exposes.numeric('voltage', ea.STATE).withUnit('V').withDescription('Voltage'),
exposes.numeric('current_A', ea.STATE).withUnit('A').withDescription('Current A'),
exposes.numeric('current_B', ea.STATE).withUnit('A').withDescription('Current B'),
exposes.numeric('total_current', ea.STATE).withUnit('A').withDescription('Total Current'),
exposes.numeric('power_factor_A', ea.STATE).withUnit('%').withDescription('Power factor A'),
exposes.numeric('power_factor_B', ea.STATE).withUnit('%').withDescription('Power factor B'),
exposes.numeric('consumption_reverse_A', ea.STATE).withUnit('kWh').withDescription('Consumption reverse A'),
exposes.numeric('consumption_reverse_B', ea.STATE).withUnit('kWh').withDescription('Consumption reverse B'),
exposes.numeric('total_consumption_reverse', ea.STATE).withUnit('kWh').withDescription('Total Consumption reverse'),
exposes.numeric('consumption_A', ea.STATE).withUnit('kWh').withDescription('Consumption A'),
exposes.numeric('consumption_B', ea.STATE).withUnit('kWh').withDescription('Consumption B'),
exposes.numeric('total_consumption', ea.STATE).withUnit('kWh').withDescription('Total Consumption'),
],

meta:{
tuyaDatapoints: [//only report data
[113, 'frequency_ac', tuya.valueConverter.raw],
[108, 'power_A', tuya.valueConverter.raw],
[111, 'power_B', tuya.valueConverter.raw],
[9, 'total_power', tuya.valueConverter.raw],
[106, 'voltage', tuya.valueConverter.divideBy10],
[107, 'current_A', tuya.valueConverter.divideBy1000],
[110, 'current_B', tuya.valueConverter.divideBy1000],
[105, 'total_current', tuya.valueConverter.divideBy1000],
[109, 'power_factor_A', tuya.valueConverter.raw],
[112, 'power_factor_B', tuya.valueConverter.raw],
[102, 'consumption_reverse_A', tuya.valueConverter.divideBy100],
[104, 'consumption_reverse_B', tuya.valueConverter.divideBy100],
[2, 'total_consumption_reverse', tuya.valueConverter.divideBy100],
[101, 'consumption_A', tuya.valueConverter.divideBy100],
[103, 'consumption_B', tuya.valueConverter.divideBy100],
[1, 'total_consumption' , tuya.valueConverter.divideBy100],
],
},
};

module.exports = definition;`

**Comment by Koenkk** [comment]
thanks, added it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
