### ISSUE TITLE
[New device support]: Paulmann LED Globe G125 E27

### ISSUE THREAD

**Issue by Mar1usW3** [Koenkk/zigbee2mqtt#20090]
### Link

https://de.paulmann.com/p/filament-230v-smart-home-zigbee-3.0-led-globe-g125-e27-600lm-7-5w-tunable-white-dimmbar-gold/29161

### Database entry

{"id":15,"type":"Router","ieeeAddr":"0xa4c13800ab391bfa","nwkAddr":33156,"manufId":4632,"manufName":"Paulmann Licht GmbH","powerSource":"Mains (single phase)","modelId":"CCT","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,4111],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"CCT","manufacturerName":"Paulmann Licht GmbH","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":2,"hwVersion":146,"swBuildId":"PCCT302"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":146,"swBuildId":"PCCT302","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1701965201556,"defaultSendRequestWhen":"immediate"}

### Comments

It is possible to connect and control the light but it is not recognized as the correct model and the Color temp startup is also not supported by the device. If the brightness is lower then 2 the lamp is off.
<img width="1260" alt="Bildschirmfoto 2023-12-07 um 17 54 05" src="https://github.com/Koenkk/zigbee2mqtt/assets/66533871/0adeaf41-716a-4278-a2b6-56e56479390a">

### Supported color modes

Color temp (cool, neutral, warm); Power-on behavior

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}

**Comment by Mar1usW3** [comment]
anyone can help here? In general the bulb is working but many times if i turn the bulb it is just flashing and need to turn it off and on again

**Comment by steffensc** [comment]
Same here, I noticed the behaviour is somehow related to the transition time. If you enter a relatively small value e.g. 0.1 (Settings (specific) -> Transition), it is possible to reliable switch the bulb on and off as long as the value for the brightness  ("Details" panel) is at least 8. Any transition value below 0.1 result in not beeing able to turn off the bulb, it stayts at appoy. 1% brightness.
