### ISSUE TITLE
Enbrighten 43080 does not report button press if it matches device's internal state (regardless of MQTT state)

### ISSUE THREAD

**Issue by jakelauer** [Koenkk/zigbee2mqtt#20091]
### What happened?

_Note - I have my Enbrighten 43080 switches hardwired, so they do not control power. I am unsure if this is a prerequisite to reproduce this problem or not._

If the device, from its own perspective, is "off" or "on", it will not report button presses that match that state, even if MQTT reports some other state. In other words, if the device is "off" and I press "off", it will not report. If I then press "on", it will report. If I turn the switch back off using software, it will still require a user to physically turn it off and on.

This appears to be unaffected by the state present in MQTT. I have automations which set the switch state to be "on" at all times (i.e. when a user turns a switch off, I detect that, run automations, and turn the switch back on in software). The MQTT state at that point does not appear to match the device's internal state. The switches require a physical toggle off & on in order to detect a change in state. 

```mermaid
sequenceDiagram
    participant User
    participant Device
    participant MQTT

    Note over Device: Initial State: Off

    User->>Device: Press Off
    Note over Device: State: Off
    Device-->>MQTT: No Report

    User->>Device: Press On
    Note over Device: State: On
    Device-->>MQTT: Report On

    MQTT->>Device: Turn Off (via software)
    Note over Device: State: On (Physical State Unchanged)
    Device-->>MQTT: No Physical Action, No Report

    User->>Device: Press Off (physically)
    Note over Device: State: Off
    Device-->>MQTT: Report Off

    User->>Device: Press On (physically)
    Note over Device: State: On
    Device-->>MQTT: Report On

```

### What did you expect to happen?

I expect to see an update in MQTT that the switch state changed

### How to reproduce it (minimal and precise)

1. (Unsure if necessary) Hardware switch to be always powered (e.g. wire the line and load wires to each other before they reach the switch)
2. Connect switch to MQTT
3. Automate the switch to turn on if it is turned off
4. Attempt to turn the switch off with the physical button
5. Observe that the switch will not turn off, unless you first turn it on again

### Zigbee2MQTT version

 1.33.2 commit: 9996c93

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB

**Comment by pseudoacacia** [comment]
It looks like the Enbrighten 43080 exposes the buttons on endpoint 2 which is ignored by the zigbee-herdsman-converter (after all, if you just want to control the light then following that state is sufficient). But I have a friend who recently switched from using ZHA and they had built automations like, "If the light is already on and *On* is pressed, start a 30-minute timer..." I could also imagine this to be useful for cycling through preset scenes.

Anyway, making an [external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-1-extending-the-external-definition) that binds this secondary endpoint and exposes it as an on/off action lets me track the on/off buttons without regard to the light's own status.

Here's what I've been using; hopefully it helps.

```javascript
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const reporting = require('zigbee-herdsman-converters/lib/reporting');

const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['43080'],
    model: '43080',
    vendor: 'Jasco Products',
    description: 'Using external converter to capture On/Off commands.',
    extend: [light({noConfigure: true})],
    fromZigbee: [fz.command_on, fz.command_off],
    exposes: [e.action(['on', 'off', 'up', 'down'])],
    toZigbee: [],
    configure: async (device, coordinatorEndpoint, logger) => {
        const secondary_endpoint = device.getEndpoint(2);
        await reporting.bind(secondary_endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
        await reporting.onOff(endpoint);
    }
};

module.exports = definition;
```
