### ISSUE TITLE
Status update no longer works since version 1.34.0 on some devices

### ISSUE THREAD

**Issue by OUARZA** [Koenkk/zigbee2mqtt#20100]
### What happened?

Since the update of 2023-12-05 08:57:15, some of my equipment no longer shows their condition.
This is the case of my lamps :
Model: 4058075047853 Manufacturer: LEDVANCE Seller: OSRAM Model ID: Gardenpole RGBW Z3

and my transformers :
Model: ICPSHC24-10EU-IL-1 Manufacturer: IKEA of Sweden Seller: IKEA Model ID: TRADFRI transformer 10W

### What did you expect to happen?

A return to normal state

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

26780700

### Adapter

ConBee2/RaspBee2

### Debug log

<small>2023-12-08 08:09:11</small>`MQTT publish: topic 'zigbee2mqtt/0x90fd9ffffe17157a', payload '{"brightness":180,"device":{"applicationVersion":17,"dateCode":"20211025","friendlyName":"0x90fd9ffffe17157a","hardwareVersion":1,"ieeeAddr":"0x90fd9ffffe17157a","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"ICPSHC24-10EU-IL-1","networkAddress":26394,"powerSource":"Mains (single phase)","softwareBuildID":"2.3.086","stackVersion":87,"type":"Router","zclVersion":1},"last_seen":"2023-12-07T20:49:00.829Z","level_config":{"on_level":"previous"},"linkquality":255,"power_on_behavior":"on","state":"ON","update":{"installed_version":587753009,"latest_version":587753009,"state":"idle"},"update_available":false}'

**Comment by tempus2016** [comment]
I think I have the same issue.  In HA, when I click on some devices to turn them on, they turn on but doesn't show the on state in HA and I'm unable to turn them off without going into Z2M and manually turning them off.

**Comment by sdotter** [comment]
I'm having same issue...
Already found fix?

**Comment by tempus2016** [comment]
> I'm having same issue... Already found fix?

I haven’t found a solution yet. Not sure if the recent HA or Z2M update has caused it. Finding the UI of Z2M a bit buggy also. Clicking a device link sometimes takes multiple clicks to access the device settings.

**Comment by sdotter** [comment]
Yeah i experience exact same issue(s)
Buggy / sometimes crash of zigbee2mqtt... a lot of times devices dont respond when turning then on or off.
It doenst matters if i use Home Assistant or Zigbee2Mqtt directly, then i get:

`Publish 'set' 'state' to 'Woonkamer Lamp' failed: 'Error: Command 0x385cfbfffe8b44d1/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57357 - 1 - 12 - 6 - 11 after 10000ms)'`

**Comment by OUARZA** [comment]
Hello, I solved the problem for all my equipment except 1 by restarting them electrically.

**Comment by sdotter** [comment]
Hi! Yeah i thought that i solved it also... but it didnt last...
I downgraded addon for home assistant:

`sudo docker pull zigbee2mqtt/zigbee2mqtt-aarch64:1.33.2-1
sudo docker tag zigbee2mqtt/zigbee2mqtt-aarch64:1.33.2-1 zigbee2mqtt/zigbee2mqtt-aarch64:1.34.0-1`

**Comment by OUARZA** [comment]
Hello I still have lots of errors with one of my devices :(

Publish 'set' 'state' to '0x7cb03eaa00b064a9' failed: 'Error: Command 0x7cb03eaa00b064a9/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (12))'

**Comment by tempus2016** [comment]
> Hello I still have lots of errors with one of my devices :(
> 
> Publish 'set' 'state' to '0x7cb03eaa00b064a9' failed: 'Error: Command 0x7cb03eaa00b064a9/3 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (12))'

I’m the same. Constant errors like this showing up and devices not reporting correct states.
