### ISSUE TITLE
GZCGQ01LM  - for some reason z2m tries to read a known unreadable parameter from the end device.

### ISSUE THREAD

**Issue by mrmaximas** [Koenkk/zigbee2mqtt#20102]
### What happened?

Very often I get error messages about devices like [GZCGQ01LM:](https://www.zigbee2mqtt.io/devices/GZCGQ01LM.html)

### What did you expect to happen?

For some reason z2m tries to read a known unreadable parameter from the end device.

DB Entry
{"id":2,"type":"EndDevice","ieeeAddr":"0x04cf8cdf3c786645","nwkAddr":35651,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sen_ill.mgl01","epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.sen_ill.mgl01","appVersion":21}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":11761}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,255,11,3,40,25,4,33,168,67,5,33,41,0,6,36,1,0,0,0,0,8,33,21,1,10,33,29,23,12,32,1,100,33,15,0]}}},"genPowerCfg":{"attributes":{"batteryVoltage":30}}},"binds":[{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[{"cluster":1024,"attrId":0,"minRepIntval":15,"maxRepIntval":3600,"repChange":500}],"meta":{}}},"appVersion":21,"interviewCompleted":true,"meta":{"configured":855622161},"lastSeen":1702033205469,"defaultSendRequestWhen":"immediate"}

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20221226

### Adapter

SONOFF ZB Dongle-P

### Debug log

Error 2023-12-08 14:06:44 Publish 'get' 'illuminance_lux' to 'Living Room Light Sensor' failed: 'Error: Read 0x04cf8cdf3c786645/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 35651 - 1 - 164 - 1024 - 1 after 10000ms)'

Debug 2023-12-08 14:06:44 Error: Read 0x04cf8cdf3c786645/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 35651 - 1 - 164 - 1024 - 1 after 10000ms) at Timeout._onTimeout (/Users/max/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:573:17) at processTimers (node:internal/timers:514:7)

Error 2023-12-08 14:07:07 Publish 'get' 'illuminance_lux' to 'Living Room Light Sensor' failed: 'Error: Read 0x04cf8cdf3c786645/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 35651 - 1 - 165 - 1024 - 1 after 10000ms)'

Debug 2023-12-08 14:07:07 Error: Read 0x04cf8cdf3c786645/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 35651 - 1 - 165 - 1024 - 1 after 10000ms) at Timeout._onTimeout (/Users/max/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:573:17) at processTimers (node:internal/timers:514:7)

**Comment by Koenkk** [comment]
An MQTT message is received to read this:

```
Publish 'get' 'illuminance_lux' to 'Living Room Light Sensor' failed
```

Figure out who sends this message and prevent it from being send.

**Comment by mrmaximas** [comment]
> Figure out who sends this message and prevent it from being send.

the only thing that comes to mind is z2m webui.....
