### ISSUE TITLE
[Wrong device]: picture/vendor/model

### ISSUE THREAD

**Issue by smart-ctrl** [Koenkk/zigbee2mqtt#20106]
### Link

https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector.html#tuya-ts0207_water_leak_detector

### Model

IH-K665

### Description

Water leak sensor

### Vendor

 Aubess

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/IH-K665.jpg

### Database entry

{"id":14,"type":"EndDevice","ieeeAddr":"0xREMOVED","nwkAddr":64143,"manufId":4417,"manufName":"_TZ3000_kstbkt6a","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0xe0798dfffeb77c53","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffeb77c53","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":491743244},"lastSeen":1702054472400,"defaultSendRequestWhen":"immediate"}

### Notes

Expected Link of this device (product page) https://www.zigbee2mqtt.io/devices/IH-K665.html

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
