### ISSUE TITLE
ZNQBKG25LM - right and left switch in decoupled operation mode

### ISSUE THREAD

**Issue by Rumlik** [Koenkk/zigbee2mqtt#20114]
### What happened?

If I switch the switch to decoupled operation mode, it does not recognize the difference between right and left button press. It only registers single or double.

### Zigbee2MQTT version

1.34.0-dev commit: a17f650

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee2mqtt/issues/20503
