### ISSUE TITLE
Tuya SH-SC07 hold Action not working 

### ISSUE THREAD

**Issue by panteLx** [Koenkk/zigbee2mqtt#20127]
### What happened?

Single and double click working fine but the hold button click isn’t working. 

It will detect every hold press as single press. 

### What did you expect to happen?

Hold press

### How to reproduce it (minimal and precise)

Hold button for 3 seconds. 

### Zigbee2MQTT version

1.34.0-dev

### Adapter firmware version

7.3.1.0 build 176

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by Markourai** [comment]
Hi, I've just got this button and confirms this issue.

**Comment by aantonelloborges** [comment]
Same for me.
