### ISSUE TITLE
[Xiaomi GZCGQ11LM] Device didn't respond to OTA reques

### ISSUE THREAD

**Issue by christianbalz** [Koenkk/zigbee2mqtt#20121]
### What happened?

Aqara T1 light intensity sensor device didn't respond to OTA reques

![image](https://github.com/Koenkk/zigbee2mqtt/assets/26635391/e2724290-1b22-426d-a82a-9f6abb9f4718)

### What did you expect to happen?

Device endpoint linked as expected in order to upgrade the firmware successfully

### How to reproduce it (minimal and precise)

Check OTA update

### Zigbee2MQTT version

1.34.0 commit: aae7312

### Adapter firmware version

2019www - Firmware build date 20200312

### Adapter

Aqara T1 light intensity sensor GZCGQ11LM

### Debug log

```
error 2023-12-09 12:49:44: Failed to check if update available for 'Sensor luminosidade sala' (Device didn't respond to OTA request)
debug 2023-12-09 12:49:44: Error: Device didn't respond to OTA request
    at requestOTA (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:202:15)
    at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:280:25)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:204:45)
```

**Comment by lux73** [comment]
you have to Push the pairing Button shortly on the Device after triggering OTA to set the Battery Device into OTA state

this Way works with my [Xiaomi RTCGQ14LM](https://www.zigbee2mqtt.io/devices/RTCGQ14LM.html)

**Comment by christianbalz** [comment]
> you have to Push the pairing Button shortly on the Device after triggering OTA to set the Battery Device into OTA state
> 
> this Way works with my [Xiaomi RTCGQ14LM](https://www.zigbee2mqtt.io/devices/RTCGQ14LM.html)

It's works fine. Thank you @lux73

**Comment by christianbalz** [comment]
the solution provided worked well

**Comment by christianbalz** [comment]
The solution provided worked well
