### ISSUE TITLE
Hue motion sensors temp and lux update issue

### ISSUE THREAD

**Issue by whcrg** [Koenkk/zigbee2mqtt#20135]
### What happened?

It seem hue motion sensors temperature and luminosity is updated very infrequently. Googling shows some people have updates every 5min, so I think it could be somehow done.

SmartThing driver seems to even have some sort of configuration for update intervals (line 288 on) but I havent yet gone deep enough to understand what it maybe sends to the device.
https://github.com/bogdanalexe90/hueMotionSensor/blob/master/devicetypes/bogdanalexe90/hue-motion-sensor.src/hue-motion-sensor.groovy

Could it be that there is some update interval settings somewhere, and for example the hue bridge sets such when pairing (and they maybe even carry over for people who move sensor from hue bridge to other systems?

### What did you expect to happen?

Update of temp I expect to get more often than every 30-60min. Every 2-5min would be what I suppose should happen.

### How to reproduce it (minimal and precise)

Buy new hue motion sensor, pair to z2m (never been paired to any other system) (I have two, the inside and the outside models)

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

not shown in settings/about

### Adapter

SkyConnect

### Debug log

The valiues keep repeating frequently but not actually updated in long time. Even several degree temperature change does not trigger faster update.

Debug 2023-12-10 11:15:55Received Zigbee message from 'LroomPIR03', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":0}' from endpoint 2 with groupID 0
Info 2023-12-10 11:15:55MQTT publish: topic 'zigbee2mqtt/LroomPIR03', payload '{"battery":100,"illuminance":8183,"illuminance_lux":7,"led_indication":false,"linkquality":164,"motion_sensitivity":"low","occupancy":false,"occupancy_timeout":2,"temperature":21.82}'
Info 2023-12-10 11:15:55MQTT publish: topic 'zigbee2mqtt/LroomPIR03', payload '{"battery":100,"illuminance":8183,"illuminance_lux":7,"led_indication":false,"linkquality":164,"motion_sensitivity":"low","no_occupancy_since":{"undefined":60},"occupancy":false,"occupancy_timeout":2,"temperature":21.82}'

**Comment by lux73** [comment]
there are some Aqara Movement Sensors available with integrated Lux measuring - they only update new lx Values if movement is registered

quite not usable - i don't know if the Hue Sensors are working similar ^^

i had to buy dedicated Lux Sensors to handle this Problem...

**Comment by mundschenk-at** [comment]
The actual update interval is something like 5 minutes, I believe. This is a known hardware/firmware limitation of the Hue motion sensors.

**Comment by whcrg** [comment]
I am getting around 20 updates per 24/h. Motion works perfect and lux is bit more regular and signal strength good. 
![Screenshot_20231213-065506](https://github.com/Koenkk/zigbee2mqtt/assets/46355292/a51eb45d-16f6-40b6-ac75-0e5719222b3e)

**Comment by mundschenk-at** [comment]
The update interval issue I was mentioning is specific to the lux measurement.

**Comment by whcrg** [comment]
Seems the reporting is configurable, have to just figure out how.
Hubitats drivers offer such. https://community.hubitat.com/t/philips-hue-motion-sensor-more-frequent-lux-reading/126477/9

**Comment by whcrg** [comment]
Maybe it just has it as the standard intends... pity my coding skills are not up to this task
![image](https://github.com/Koenkk/zigbee2mqtt/assets/46355292/675351c3-5d2d-417e-93c4-094292dc143e)

**Comment by whcrg** [comment]
Haa! Its apparently implemented and working in z2m and there is just something weird going on in my individual system and the reporting tab under device is empty and that is why I cannot see the settings.
