### ISSUE TITLE
ADEO SIN-4-1-21_EQU Working

### ISSUE THREAD

**Issue by inoxas78** [Koenkk/zigbee2mqtt#20137]
### Link

https://www.leroymerlin.fr/produits/chauffage-et-ventilation/radiateur/radiateur-electrique/kit-de-demarrage-economie-energie/module-connecte-on-off-radiateur-et-chauffe-eau-equation-87766423.html?src=clk

### Database entry

{"id":37,"type":"Router","ieeeAddr":"0x6c5cb1fffe87a6f8","nwkAddr":30751,"manufId":4727,"manufName":"Adeo","powerSource":"Mains (single phase)","modelId":"SIN-4-1-21_EQU","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,7,1794,4096],"outClusterList":[3,6,25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":103,"hwVersion":50,"dateCode":"2021","zclVersion":8,"interviewCompleted":false,"meta":{},"lastSeen":1702205861042,"defaultSendRequestWhen":"immediate"}

### Comments

Working converter

### External converter

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    zigbeeModel: ['SIN-4-1-21_EQU'],
    model: 'SIN-4-1-21_EQU',
    vendor: 'ADEO',
    description: 'Multifunction relay switch with metering',
    fromZigbee: [fz.on_off, fz.metering, fz.power_on_behavior],
    toZigbee: [tz.on_off, tz.power_on_behavior],
    exposes: [e.switch(), e.power(), e.energy(), e.power_on_behavior()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const ep = device.getEndpoint(1);
        await reporting.bind(ep, coordinatorEndpoint, ['genBasic', 'genIdentify', 'genOnOff', 'seMetering']);
        await reporting.onOff(ep, {min: 1, max: 3600, change: 0});
        await reporting.readMeteringMultiplierDivisor(ep);
        await reporting.instantaneousDemand(ep);
        await reporting.currentSummDelivered(ep);
    } // Removed semicolon here
};

module.exports = definition;


```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
