### ISSUE TITLE
Bad/Invalid auth_token is not rejected

### ISSUE THREAD

**Issue by TheQue42** [Koenkk/zigbee2mqtt#20152]
### What happened?

If I accidentally enter the wrong password for the auth_token, I still get (sort of) logged in, but with a dead dashboard, and I cant find anywhere to "log out".

The token seems to be stored in firefox'es local data(the cookie quick manager add on to firefox doesnt show a cookie for my site), but I cant find any method of deleting the data specific to ONLY this site.

Cleaning cookies in firefox for the *domain* will work, but I have a lot of different services running on xxxx.domain.com, and its quite annoying to have to loose all cookies, etc for ALL domains, just become I accidentally added the wrong pass for z2m.

### What did you expect to happen?

I would expect that invalid auth_tokens where rejected with 403, or that there at least was some way of logging out and entering a new token.

### How to reproduce it (minimal and precise)

just login with a bad token.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

n/a

### Adapter

n/a

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/zigbee2mqtt-frontend
