### ISSUE TITLE
Immax 07752L not fully supported

### ISSUE THREAD

**Issue by vladimirssa** [Koenkk/zigbee2mqtt#20158]
### What happened?

Immax 07752L is not reporting all values and reporting is not based on the L1 and L2 states; though the dev console is getting some of the values right.

![Home assistant](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/7dc01a52-b8e5-4213-b0e3-e98592a38c3e)
![TS011F_3](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/caa631d2-cc3d-4c56-aba5-887e99eed2b2)
![TS011F_2](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/5f787b36-bbec-4d48-a741-00efc649bb87)
![TS011F](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/1b3e1291-7549-4d68-991f-605954a3e5a3)

### What did you expect to happen?

All supported values are present.

### Zigbee2MQTT version

1.34.0 

### Adapter firmware version

20211115

### Adapter

zStack12

### Debug log

Info 2023-12-11 11:10:05MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:05+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'
Info 2023-12-11 11:10:05MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:05+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'
Info 2023-12-11 11:10:05MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:05+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'
Info 2023-12-11 11:10:06MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:06+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'
Info 2023-12-11 11:10:06MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:06+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'
Info 2023-12-11 11:10:06MQTT publish: topic 'zigbee2mqtt/Entertainment Room Socket', payload '{"child_lock":null,"current":null,"current_l1":0.51,"energy":0.01,"indicator_mode":"on","last_seen":"2023-12-11T11:10:06+01:00","linkquality":0,"power":null,"power_l1":81,"power_outage_memory":"restore","power_outage_memory_l1":"restore","state_l1":"ON","state_l2":"ON","voltage":null,"voltage_l1":241}'

**Comment by ReNeGaDe124** [comment]
Hello, I just bought this model yesterday and I think I found a workaround to properly show the Power, Current and Voltage sensors.

-  Copy the code from here (https://gist.github.com/Koenkk/e8587976de964e3c76c89c12b13b6266) and save it as `ext.js` in `/homeassistant/zigbee2mqtt/` 
- On line 40 change from     `meta: {multiEndpoint: true}`, to     `meta: {multiEndpoint: false}`,
- In `/homeassistant/zigbee2mqtt/` there should also be a file called `configuration.yaml`. At the end of it add:
```yaml
 external_converters:
   - ext.js
```
- Restart zigbee2mqtt

This is working for me. Hope it can help you as well. Maybe the developer can include this change in next release or find a better solution.

**Comment by vladimirssa** [comment]
@ReNeGaDe124 Thank you very much! It's working now in the same way as yours. The pity is that the home assistant got it wrong. Maybe it is HA-related. I am kind of a newbie to this stuff, although I was able to set up RPI with a home bridge and a HA on another device. If you have some idea of how to get around this in the HA, please share. Thanks again.


![Immax](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/caf72e4b-cf40-4e11-b438-67eee4abe8a7)

![Ha](https://github.com/Koenkk/zigbee2mqtt/assets/153081171/3017ba45-892a-493d-afdf-77f594c82cee)
