### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JayJay-Master** [Koenkk/zigbee2mqtt#20163]
### What happened?

Hello, you've found a bug. Congratulations!

    See attached from server downloaded report file
    Take a screenshot of this page and attach to the issue

### What did you expect to happen?

Don't know. Found this bug report.

### How to reproduce it (minimal and precise)

After reöoading the page everything themes ok. 

### Zigbee2MQTT version

1.33.2 commit: 9996c93

### Adapter firmware version

26720700

### Adapter

ConBee 2 Stick

### Debug log

![Screenshot](https://github.com/Koenkk/zigbee2mqtt/assets/80389556/f27c17fd-82e1-4a6d-9311-5e3554fa40d2)

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
