### ISSUE TITLE
Philips Hue White Ambiance E14 [LTU001] exposes non-supported colour attributes

### ISSUE THREAD

**Issue by uncle-fed** [Koenkk/zigbee2mqtt#20168]
### What happened?

The [Philips Hue white ambiance E14](https://www.zigbee2mqtt.io/devices/8719514491106.html#philips-8719514491106) is exposing `color_xy` and ` color_hs` attributes, but the bulb is only capable of changing its colour temperature, not colours.

### What did you expect to happen?

The `color_xy` and ` color_hs` attributes should be removed.

### Zigbee2MQTT version

1.34.0 commit: 56589dcc

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus (CC2652)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
