### ISSUE TITLE
[Wrong device]: AVATTO 1/2/3 Gang Tuya Zigbee Light Switch Module No Neutral Wire 

### ISSUE THREAD

**Issue by mrmaximas** [Koenkk/zigbee2mqtt#20162]
### Link

https://aliexpress.ru/item/1005003108226482.html

### Model

LZWSM16-1 LZWSM16-2 LZWSM16-3

### Description

Switch Module No Neutral Wire

### Vendor

AVATTO

### Picture (link)

https://ae04.alicdn.com/kf/Sf349a5bd87aa43439c30ebbf0b957ec9T.jpg_640x640.jpg
https://ae04.alicdn.com/kf/Sf0be5ca650fe449eab4fda802c3df6d7h.jpg_640x640.jpg
https://ae04.alicdn.com/kf/S5c4f3d2ec3f4467ebd2bcc99fcee7261q.jpg_640x640.jpg

### Database entry for 2 Gang

"id":51,"type":"EndDevice","ieeeAddr":"0xa4c13878f40e0e4c","nwkAddr":21543,"manufId":4417,"manufName":"_TZ3000_kpatq5pq","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":1}},"genBasic":{"attributes":{"65534":0,"stackVersion":0,"manufacturerName":"_TZ3000_kpatq5pq","zclVersion":3,"appVersion":68,"modelId":"TS0012","powerSource":3}},"manuSpecificTuya_3":{"attributes":{"switchType":0}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAA"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1794938824},"lastSeen":1701158961849,"defaultSendRequestWhen":"immediate"}

### Database entry for 3 Gang

{"id":52,"type":"EndDevice","ieeeAddr":"0xa4c138131fb22333","nwkAddr":35960,"manufId":4417,"manufName":"_TZ3000_sznawwyw","powerSource":"Mains (single phase)","modelId":"TS0013","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":2}},"genBasic":{"attributes":{"65506":55,"65508":1,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_sznawwyw","zclVersion":3,"appVersion":68,"modelId":"TS0013","powerSource":3}},"manuSpecificTuya_3":{"attributes":{"switchType":0}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAABAAA"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1331047771},"lastSeen":1701159663315,"defaultSendRequestWhen":"immediate"}

### Notes

I have 2 and 3 gang of this relays, 1-gang in transit.
This devices mistakenly recognised as
https://www.zigbee2mqtt.io/devices/TS0012.html
https://www.zigbee2mqtt.io/devices/TS0013.html

Devices must be recognized like this, but my relays are in a slightly different housing and there may be differences in the clusters:
https://www.zigbee2mqtt.io/devices/TS0012_switch_module.html
https://www.zigbee2mqtt.io/devices/TS0013_switch_module.html

**Comment by Koenkk** [comment]
Fixed! (pictures will be correct after the next release)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by mrmaximas** [comment]
@Koenkk arrived 2-gang new variant _TZ3000_ljhbw1c9 of  LZWSM16-2 (detected as wrong type of https://www.zigbee2mqtt.io/devices/TS0012.html)
Unfortunately, I forgot to order the 1-gang as promised.

{"id":66,"type":"EndDevice","ieeeAddr":"0xa4c138e3c5694c0b","nwkAddr":24142,"manufId":4417,"manufName":"_TZ3000_ljhbw1c9","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"H\u0000\u0000\u0000\u0012\u0001\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0011","65506":55,"65508":0,"65534":0,"modelId":"TS0012","manufacturerName":"_TZ3000_ljhbw1c9","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":0,"tuyaBacklightMode":1}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAA"}},"manuSpecificTuya_3":{"attributes":{"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1794938824},"lastSeen":1703105354632,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by mrmaximas** [comment]
> Fixed.
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Thanks. I just tried to update dev version of Zigbee2MQTT, but I get this message 
* [new branch] deps/zigbee-herdsman-converters -> origin/deps/zigbee-herdsman-converters
while the Zigbee2MQTT version remains the same.
1.34.0-dev commit: 27ccd1a5
Frontend version
0.6.149
Zigbee-herdsman-converters version
16.15.0
Zigbee-herdsman version
0.27.1
I see that Zigbee-herdsman-converters version 16.15.1 is not installed.
Is it possible to update individual components, namely zigbee-herdsman-converters ?
if yes, what is the right way to do it?

**Comment by Koenkk** [comment]
In the z2m folder, execute `npm i zigbee-herdsman-converters@16.15.1`

**Comment by mrmaximas** [comment]
> In the z2m folder, execute `npm i zigbee-herdsman-converters@16.15.1`
Thanks! I tried this, updated zigbee-herdsman-converters to 16.15.1 but _TZ3000_ljhbw1c9 is still visible as https://www.zigbee2mqtt.io/devices/TS0012.html.
![Screenshot 2023-12-22 at 10 58 22](https://github.com/Koenkk/zigbee2mqtt/assets/61165387/b56e7a1f-2e6f-4cb0-b3c0-c0b2625eae6d)
![Screenshot 2023-12-22 at 10 59 24](https://github.com/Koenkk/zigbee2mqtt/assets/61165387/251c2c4c-ec2b-4179-9c51-7c436e5cf36b)

**Comment by Koenkk** [comment]
Pushed another fix.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by mrmaximas** [comment]
@Koenkk 🙏🏻

**Comment by mrmaximas** [comment]
> pictures will be correct after the next release

forgot about pictures ;-)
![Screenshot 2023-12-26 at 17 16 04](https://github.com/Koenkk/zigbee2mqtt/assets/61165387/ec391d5d-dcdb-4039-80f9-525bf51cf019)

**Comment by Koenkk** [comment]
Pictures will be updated after the next release (1 January)

**Comment by mrmaximas** [comment]
@Koenkk sniffed for LZWSM16-2 aka _TZ3000_ljhbw1c9 (AVATTO 2-Gang Tuya Zigbee Light Switch Module No Neutral Wire)
https://drive.google.com/file/d/14OmGcs2_N6uPl9SU_TfxB2CnwftGiRZh/view?usp=share_link
1. found button type attribute 0xd030 53296 - value 0/1/2 toggle/state/momentary
2. backlight mode - is absent, I suggest to remove.

**Comment by mrmaximas** [comment]
{"id":39,"type":"EndDevice","ieeeAddr":"0xa4c1387232c6fd35","nwkAddr":37366,"manufId":4417,"manufName":"_TZ3000_ljhbw1c9","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":0,"tuyaBacklightMode":1}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAA"}},"manuSpecificTuya_3":{"attributes":{"switchType":0}},"genBasic":{"attributes":{"65534":0,"modelId":"TS0012","manufacturerName":"_TZ3000_ljhbw1c9","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1794938824},"lastSeen":1703722212387,"defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
@mrmaximas what is the cluster for the switch type? If it's `0xe001`/`57345` it should already work.

**Comment by mrmaximas** [comment]
> it should already work.

yes! it's works for me. I just don't understand when this parameter appeared, is it today? or was it previously? ;-)

**Comment by mrmaximas** [comment]
works on LZWSM16-2 and LZWSM16-3, i think should be works on LZWSM16-1

**Comment by Koenkk** [comment]
What's the data/database.db entry of the `LZWSM16-1`?

**Comment by mrmaximas** [comment]
> What's the data/database.db entry of the `LZWSM16-1`?

sorry, i don't have this model now ;-(

**Comment by mrmaximas** [comment]
@Koenkk I've been using latest dev branch for the year. After some update, the mains powered end device _TZ3000_ljhbw1c9 aka https://www.zigbee2mqtt.io/devices/LZWSM16-2.html are shown as battery powered. 
 
![Screenshot 2024-07-16 at 14 50 39](https://github.com/user-attachments/assets/f409469e-7415-412a-bd54-fcd891b2e614)
![Screenshot 2024-07-16 at 17 01 40](https://github.com/user-attachments/assets/40ae7a68-d64c-48d4-a44f-f75b0638f866)

**Comment by Koenkk** [comment]
Could you try to reconfigure the device via the frontend and restart z2m?

**Comment by mrmaximas** [comment]
@Koenkk I've done this many times - I've re-configured and re-paired through the gui.

**Comment by mrmaximas** [comment]
@Koenkk after a more than year I discovered that this _TZ3000_ljhbw1c9 and _TZ3000_sznawwyw devices has countdown timers.
It's possible to add this?

2CH version `_TZ3000_ljhbw1c9` z2m db entry

`"id":67,"type":"EndDevice","ieeeAddr":"0xa4c1384a94987855","nwkAddr":28566,"manufId":4417,"manufName":"_TZ3000_ljhbw1c9","powerSource":"Mains (single phase)","modelId":"TS0012","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"57344":{"attributes":{"53251":"AAAAAgAA"}},"genBasic":{"attributes":{"65503":"\u0011�Y/\u0011\u000f\u0001Z/\u0012","65506":55,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_ljhbw1c9","zclVersion":3,"appVersion":68,"modelId":"TS0012","powerSource":3}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":0}},"manuSpecificTuya_3":{"attributes":{"switchType":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[{"cluster":0,"attrId":0,"minRepIntval":60,"maxRepIntval":300,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1741114627516}`

2CH version TUYA DP mapping
```
{
        "name": "2CH Zigbee Switch Module No Neutral",
        "id": "xxx",
        "key": "xxx",
        "mac": "a4:c1:38:72:32:c6:fd:35",
        "uuid": "a4c1387232c6fd35",
        "sn": "100122350000A2",
        "category": "tdq",
        "product_name": "2CH Zigbee Switch Module No Neutral",
        "product_id": "ljhbw1c9",
        "biz_type": 18,
        "model": "LZWSM16-2",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/bay158538245316590My/0ae763c22168d5ac427a01cfd50604e9.png",
        "node_id": "a4c1387232c6fd35",
        "mapping": {
            "1": {
                "code": "switch_1",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "switch_2",
                "type": "Boolean",
                "values": {}
            },
            "7": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 43200,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "countdown_2",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 43200,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "relay_status",
                "type": "Enum",
                "values": {
                    "range": [
                        "0",
                        "1",
                        "2"
                    ]
                }
            },
            "19": {
                "code": "switch_inching",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "47": {
                "code": "switch_type",
                "type": "Enum",
                "values": {
                    "range": [
                        "flip",
                        "sync",
                        "button"
                    ]
                }
            }
        },

```



3CH version `_TZ3000_sznawwyw` z2m db entry

`{"id":131,"type":"EndDevice","ieeeAddr":"0xa4c138131fb22333","nwkAddr":40780,"manufId":4417,"manufName":"_TZ3000_sznawwyw","powerSource":"Mains (single phase)","modelId":"TS0013","epList":[1,2,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"57344":{"attributes":{"53251":"AAAAAgAABAAA"}},"genBasic":{"attributes":{"65506":55,"65508":1,"65534":0,"modelId":"TS0013","manufacturerName":"_TZ3000_sznawwyw","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":1}},"manuSpecificTuya_3":{"attributes":{"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a1aa3c4","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1741117367710}`

3CH version TUYA DP mapping
```
  {
        "name": "3\u8def\u901a\u65ad\u5668\u5355\u706b\u7248-zigbee",
        "id": "xxx",
        "key": "xxx",
        "mac": "a4:c1:38:13:1f:b2:23:33",
        "uuid": "a4c138131fb22333",
        "sn": "100098511001A0",
        "category": "tdq",
        "product_name": "3\u8def\u901a\u65ad\u5668\u5355\u706b\u7248-zigbee",
        "product_id": "sznawwyw",
        "biz_type": 18,
        "model": "EZB-ZC3H05N-B",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1562830083757AoBrF/0fb855cb32a4332675aed420c6cd9cef.png",
        "node_id": "a4c138131fb22333",
        "mapping": {
            "1": {
                "code": "switch_1",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "switch_2",
                "type": "Boolean",
                "values": {}
            },
            "3": {
                "code": "switch_3",
                "type": "Boolean",
                "values": {}
            },
            "7": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 43200,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "countdown_2",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 43200,
                    "scale": 0,
                    "step": 1
                }
            },
            "9": {
                "code": "countdown_3",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 43200,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "relay_status",
                "type": "Enum",
                "values": {
                    "range": [
                        "0",
                        "1",
                        "2"
                    ]
                }
            },
            "19": {
                "code": "switch_inching",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "47": {
                "code": "switch_type",
                "type": "Enum",
                "values": {
                    "range": [
                        "flip",
                        "sync",
                        "button"
                    ]
                }
            }
        },
  
```

Unfortunately I never got a single channel version of this relay without neutral, but I will assume countdown is DP only 7.
Thanks!

**Comment by mrmaximas** [comment]
@Koenkk this is working converter for 2 gang module, supported timers
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const modernExtend = require('zigbee-herdsman-converters/lib/modernExtend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [{modelID: 'TS0012', manufacturerName: '_TZ3000_ljhbw1c9'}],
    model: 'LZWSM16-2',
    description: '2 gang switch module - (without neutral)',
    vendor: 'AVATTO',
    extend: [tuya.modernExtend.tuyaOnOff({switchType: true, onOffCountdown: true, endpoints: ["left", "right"]})],
    endpoint: (device) => {
        return {left: 1, right: 2};
    },
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint);
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
    }, 
       
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
@mrmaximas 
Could you make a PR by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/tuya.ts)?

**Comment by mrmaximas** [comment]
> [@mrmaximas](https://github.com/mrmaximas) Could you make a PR by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/tuya.ts)?

done

**Comment by Ariel14ss14** [comment]
I have the 1 gang and it's don't work for me

**Comment by Ariel14ss14** [comment]
{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c138d599ae6794","nwkAddr":40062,"manufId":4417,"manufName":"_TZ3000_hbxsdd6k","powerSource":"Mains (single phase)","modelId":"TS0011","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"57344":{"attributes":{"53251":"AAAA"}},"genBasic":{"attributes":{"65503":"���/\u0011","65506":55,"65508":0,"65534":0,"modelId":"TS0011","manufacturerName":"_TZ3000_hbxsdd6k","powerSource":3,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":2}},"manuSpecificTuya_3":{"attributes":{"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0030db8f96","endpointID":1},{"cluster":10,"type":"endpoint","deviceIeeeAddress":"0x00124b0030db8f96","endpointID":1},{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00124b0030db8f96","endpointID":1},{"cluster":57345,"type":"endpoint","deviceIeeeAddress":"0x00124b0030db8f96","endpointID":1}],"configuredReportings":[{"cluster":57345,"attrId":53296,"minRepIntval":60,"maxRepIntval":3600,"repChange":0}],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1744652488194}

**Comment by mrmaximas** [comment]
@Ariel14ss14 please read this https://www.zigbee2mqtt.io/advanced/more/external_converters.html then try this converter code

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const modernExtend = require('zigbee-herdsman-converters/lib/modernExtend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [{modelID: 'TS0011', manufacturerName: '_TZ3000_hbxsdd6k'}],
    model: 'LZWSM16-1',
    description: '1 gang switch module - (without neutral)',
    vendor: 'AVATTO',
    extend: [tuya.modernExtend.tuyaOnOff({switchType: true, onOffCountdown: true})],
    configure: async (device, coordinatorEndpoint) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint);
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
    }, 
       
};

module.exports = definition;
```
