### ISSUE TITLE
[Feature request]: Exclude device from logging

### ISSUE THREAD

**Issue by mrmaximas** [Koenkk/zigbee2mqtt#20182]
### Is your feature request related to a problem? Please describe

I have one device that sends reports very often. It's normal for this device types.
https://www.zigbee2mqtt.io/devices/SPM01-D2TZ.html 
I think it would be appropriate to provide for excluding devices from logging, at your own risk of course.
Thanks!

### Describe the solution you'd like

/

### Describe alternatives you've considered

/

### Additional context

I would also like to make sure that the log lines are not duplicated, although I have this impression.

 2023-12-12 18:30:17MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.54,"energy":133.4,"linkquality":94,"power":1412,"produced_energy":0.15,"voltage":229.1}'
Info 2023-12-12 18:30:17MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.6,"energy":133.4,"linkquality":98,"power":1423,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:22MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.6,"energy":133.4,"linkquality":94,"power":1423,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:22MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.6,"energy":133.4,"linkquality":98,"power":1423,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:22MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.57,"energy":133.4,"linkquality":94,"power":1413,"produced_energy":0.15,"voltage":229.2}'
Info 2023-12-12 18:30:27MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.57,"energy":133.4,"linkquality":98,"power":1413,"produced_energy":0.15,"voltage":229.2}'
Info 2023-12-12 18:30:28MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.57,"energy":133.4,"linkquality":98,"power":1413,"produced_energy":0.15,"voltage":229.2}'
Info 2023-12-12 18:30:28MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.52,"energy":133.4,"linkquality":98,"power":1402,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:32MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.52,"energy":133.4,"linkquality":98,"power":1402,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:32MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.52,"energy":133.4,"linkquality":98,"power":1402,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:33MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":98,"power":1397,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:37MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":94,"power":1397,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:38MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":94,"power":1397,"produced_energy":0.15,"voltage":229.4}'
Info 2023-12-12 18:30:38MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":94,"power":1397,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:43MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":98,"power":1397,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:43MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.48,"energy":133.4,"linkquality":98,"power":1397,"produced_energy":0.15,"voltage":229.3}'
Info 2023-12-12 18:30:43MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.49,"energy":133.4,"linkquality":98,"power":1403,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:30:48MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.49,"energy":133.4,"linkquality":98,"power":1403,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:30:48MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.49,"energy":133.4,"linkquality":98,"power":1403,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:30:48MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1394,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:30:53MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1394,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:30:53MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1394,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:30:53MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1388,"produced_energy":0.15,"voltage":230.5}'
Info 2023-12-12 18:30:58MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":94,"power":1388,"produced_energy":0.15,"voltage":230.5}'
Info 2023-12-12 18:30:58MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1388,"produced_energy":0.15,"voltage":230.5}'
Info 2023-12-12 18:30:58MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1382,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:03MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1382,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:03MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1382,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:03MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:08MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:08MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:08MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":94,"power":1400,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:13MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1400,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:13MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1400,"produced_energy":0.15,"voltage":230.7}'
Info 2023-12-12 18:31:13MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:18MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:18MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:18MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1399,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:23MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":94,"power":1399,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:23MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.46,"energy":133.4,"linkquality":98,"power":1399,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:23MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:28MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:28MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:28MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1385,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:31:33MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":94,"power":1385,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:31:33MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1385,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:31:34MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1395,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:39MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1395,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:39MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.42,"energy":133.4,"linkquality":98,"power":1395,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:31:39MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1384,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:44MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1384,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:44MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1384,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:44MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:49MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:49MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.39,"energy":133.4,"linkquality":98,"power":1393,"produced_energy":0.15,"voltage":230.8}'
Info 2023-12-12 18:31:49MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1385,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:54MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1385,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:54MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.38,"energy":133.4,"linkquality":98,"power":1385,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:54MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.4,"linkquality":98,"power":1387,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:59MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.4,"linkquality":98,"power":1387,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:59MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.4,"linkquality":98,"power":1387,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:31:59MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1398,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:04MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1398,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:04MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1398,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:04MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.47,"energy":133.4,"linkquality":98,"power":1406,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:32:09MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.47,"energy":133.4,"linkquality":98,"power":1406,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:32:09MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.47,"energy":133.4,"linkquality":102,"power":1406,"produced_energy":0.15,"voltage":231}'
Info 2023-12-12 18:32:09MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:32:09MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:32:14MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:32:14MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":98,"power":1389,"produced_energy":0.15,"voltage":230}'
Info 2023-12-12 18:32:14MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.44,"energy":133.4,"linkquality":98,"power":1396,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:19MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.44,"energy":133.4,"linkquality":116,"power":1396,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:19MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.44,"energy":133.4,"linkquality":116,"power":1396,"produced_energy":0.15,"voltage":230.9}'
Info 2023-12-12 18:32:19MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":116,"power":1403,"produced_energy":0.15,"voltage":232.5}'
Info 2023-12-12 18:32:24MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":116,"power":1403,"produced_energy":0.15,"voltage":232.5}'
Info 2023-12-12 18:32:24MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.43,"energy":133.4,"linkquality":116,"power":1403,"produced_energy":0.15,"voltage":232.5}'
Info 2023-12-12 18:32:24MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1398,"produced_energy":0.15,"voltage":232.4}'
Info 2023-12-12 18:32:29MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1398,"produced_energy":0.15,"voltage":232.4}'
Info 2023-12-12 18:32:29MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1398,"produced_energy":0.15,"voltage":232.4}'
Info 2023-12-12 18:32:29MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1388,"produced_energy":0.15,"voltage":232.1}'
Info 2023-12-12 18:32:34MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1388,"produced_energy":0.15,"voltage":232.1}'
Info 2023-12-12 18:32:34MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.41,"energy":133.4,"linkquality":116,"power":1388,"produced_energy":0.15,"voltage":232.1}'
Info 2023-12-12 18:32:34MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.4,"linkquality":120,"power":1401,"produced_energy":0.15,"voltage":232}'
Info 2023-12-12 18:32:39MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.5,"linkquality":116,"power":1401,"produced_energy":0.15,"voltage":232}'
Info 2023-12-12 18:32:39MQTT publish: topic 'zigbee2mqtt/Power Monitor', payload '{"current":6.4,"energy":133.5,"linkquality":116,"power":1401,"produced_energy":0.15,"voltage":232}'
Info 2023-12-12 18:32:40MQTT publish: topic 'zigbee2mqtt/Power Monito

**Comment by mrmaximas** [comment]
> You might want to mess with your reporting thresholds (interval / change) in the device->Reporting tab (it would appear you have these set to quite an aggressive threshold) - this should reduce the amount the device sends and therefore reduce your log message count.

Thanks for you answer, page with Reporting tab looks like empty
![Screenshot 2023-12-14 at 16 38 00](https://github.com/Koenkk/zigbee2mqtt/assets/61165387/201dacf7-032e-4d9b-82a7-313e75c3732a)

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for checking! This device does look particularly chatty! I can look at adding some debounce logic, but I don't think that'd help much given the logs that you have added above.

I am not sure device specific log exclusions is a good route to go. If you were to have an issue with the device, how would you know it without logging?

**Comment by mrmaximas** [comment]
@danieledwardgeorgehitchcock this is the reason why I mention the requested feature - at the user's own risk ))

**Comment by danieledwardgeorgehitchcock** [comment]
But users have a habit of forgetting which could lead to a nightmare of false-fault finding on here. Appreciate what you are saying though :-)

**Comment by mrmaximas** [comment]
@danieledwardgeorgehitchcock this device is very chatty, that's normal for, but 95% of my log is filled with this device events.

**Comment by evelant** [comment]
I think there's a bug in z2m somewhere that causes this unrelated to the actually zigbee portion. I've had this happen too. Z2M started started endlessly sending these power monitor messages to mqtt every ~1s for a plug until I restarted z2m.

**Comment by mrmaximas** [comment]
> i'm using this workaround:
> 
> ```
>   '0xXXXXXX':
>     friendly_name: energy_input
>     debounce: 5
>     debounce_ignore:
>       - energy
>       - produced_energy
> ```

thanks!
