### ISSUE TITLE
Zigbee2MQTT requires node version ^18 || ^20 || ^21, you are running v16.20.2!

### ISSUE THREAD

**Issue by sdotter** [Koenkk/zigbee2mqtt#20186]
### What happened?

Zigbee2MQTT requires node version ^18 || ^20 || ^21, you are running v16.20.2!

Running latest dev

### Zigbee2MQTT version

Latest

### Adapter firmware version

6.10.3.0

### Adapter

Sonoff dongle e

**Comment by sjorge** [comment]
Exactly what it  says, the version of node you are using is too old. Might be you're running an older OS.

**Comment by sdotter** [comment]
Yeah sorry forget to mention that this is on home assistants z2m addon (docker sizzle stuff)

**Comment by sjorge** [comment]
Probably better to open an issue here https://github.com/zigbee2mqtt/hassio-zigbee2mqtt if that is the case.

**Comment by sdotter** [comment]
Yeah you are right 👍 thanks jorge
This issue is closed
