### ISSUE TITLE
SP-EUC01 not a Router

### ISSUE THREAD

**Issue by fabssor** [Koenkk/zigbee2mqtt#20184]
### What happened?

The Aqara EU Smart Plug does not report to be a router but an EndDevice
![image](https://github.com/Koenkk/zigbee2mqtt/assets/30718590/fc003973-c76c-4d29-b85d-7bfa080c3ef9)

### What did you expect to happen?

With ZHA the smart Plug can be a Router with Zigbee2MQTT sadly not possible.

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
