### ISSUE TITLE
IKEA Tredansen remotes won't upgrade firmware

### ISSUE THREAD

**Issue by pfurrie** [Koenkk/zigbee2mqtt#20218]
### What happened?

In Home Assistant, Zigbee2MQTT reports that our four Tredansen remotes have firmware updates.  It has reported this for *months*.  Two of those remotes have batteries at 70% and are within 12 inches of the Zigbee dongle on the HA server.  

Here's what I've been seeing in the update display:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/11449721/90b559a2-3ce7-499e-b72c-f9f0db69441d)

All four our our remotes (two others are not so close to the dongle) work to raise or lower the smart blinds from IKEA.  However, none of them will update their firmware, and the items in the update list are in a perpetual loop to install the firmware.

Any thoughts?  Adding a fresh battery seems like a wrong direction, unless the battery is close to empty..

### What did you expect to happen?

Expected the remtotes to upgrade their firmware.  

### How to reproduce it (minimal and precise)

- Install IKEA Tredansen remote with firmware version 587699761.
- Setup Tredansen remote in Hose Assistant
- Confire IKEA Tredeansen remotes with 
- Wait for HA to tell you have updates... it will find updates, but they won't install.

Thanks it.

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

don't know... how to determine this within Home Assistant.

### Adapter

Conbee II

**Comment by Nezz** [comment]
Sorry to bump an old issue, but it might be useful for someone searching for this: I had to install fresh batteries for the firmware update to work. The devices were not willing to do it with slightly used batteries.
