### ISSUE TITLE
[New device support]: Phillips Hue Centris (2 spots white)

### ISSUE THREAD

**Issue by wbsantos** [Koenkk/zigbee2mqtt#20215]
### Link

https://www.amazon.com/dp/B0CHN7MLXN?ref=ppx_yo2ov_dt_b_product_details&th=1

### Database entry

{"id":51,"type":"Router","ieeeAddr":"0x001788010ddde61b","nwkAddr":9402,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003621001_03","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003621001_03","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20230403","swBuildId":"1.104.2"}},"lightingColorCtrl":{"attributes":{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorCapabilities":31}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1702593070659,"defaultSendRequestWhen":"immediate"} {"id":52,"type":"Router","ieeeAddr":"0x001788010d4fe64b","nwkAddr":37966,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003621001_02","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003621001_02","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20230403","swBuildId":"1.104.2"}},"lightingColorCtrl":{"attributes":{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorPointGY":45875,"colorCapabilities":31}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1702593070499,"defaultSendRequestWhen":"immediate"} {"id":53,"type":"Router","ieeeAddr":"0x001788010c6432ed","nwkAddr":50640,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003621001_01","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929003621001_01","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2"}},"lightingColorCtrl":{"attributes":{"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorCapabilities":31}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b00258b7df9","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1702593071021,"defaultSendRequestWhen":"immediate"}

### Comments

Similar to the issue #12173, the model number seems to have changed.

Adding the entry bellow to src/devices/philips.ts should work (i checked the temp range already and it is the same as the others Centri models with 2 spots).

{
        zigbeeModel: ['929003621001_01', '929003621001_02', '929003621001_03'],
        model: '929003621001',
        vendor: 'Philips',
        description: 'Hue White & Color ambience Centris ceiling light (2 spots) (white)',
        extend: [philipsLight({colorTemp: {range: [153, 500]}, color: true})],
    },

### External converter

```shell
const hue = require('zigbee-herdsman-converters/devices/philips');

var extend = null;
for(var i = 0; i < hue.length; i++)
{
  if(hue[i].model == "5061030P7")
    extend = hue[i].extend;
}

const definition  = [
  {
      //zigbeeModel: ['5061031P7_01', '5061031P7_02', '5061031P7_03'],
      zigbeeModel: ['929003621001_01', '929003621001_02', '929003621001_03'],
      model: '929003621001',
      vendor: 'Philips',
      description: 'Hue White & Color ambience Centris ceiling light (2 spots) (white)',
      extend: extend
  },
];


module.exports = definition;
```

### Supported color modes

color temp, color

### Color temperature range

It is in the range of 153 and 500

**Comment by Koenkk** [comment]
Added, thanks!
