### ISSUE TITLE
question: Flashing-Light-Strobe

### ISSUE THREAD

**Issue by yaniv95** [Koenkk/zigbee2mqtt#2021]
is it possible to add flashing light strobe to zigbee2mqtt network/
https://www.alibaba.com/product-detail/HY-6108W-Wireless-Flashing-Light-Strobe_62100343582.html?spm=a2700.7724857.normalList.119.345c73e6aHJ4aD

is there a ready made product for that z2m (zigbee2mqtt) supports?

Thanks 

Yaniv

**Comment by Koenkk** [comment]
- This device is not supported yet, in case you want to support it follow: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
- You can check https://www.zigbee2mqtt.io/information/supported_devices.html if there are any comparable devices which are already supported.
