### ISSUE TITLE
[New device support]: 404118 // Tint Müller Licht LED Strip

### ISSUE THREAD

**Issue by Nina-Syrina** [Koenkk/zigbee2mqtt#20227]
### Link

https://www.mueller-licht.de/produktinformationen/artikel/?q=404118

### Database entry

{"id":41,"type":"Router","ieeeAddr":"0xa4c13800aa45370c","nwkAddr":27363,"manufId":4635,"manufName":"MLI","powerSource":"Mains (single phase)","modelId":"LED Strip","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,4111,65376],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"appVersion":0,"hwVersion":0}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":555}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDBELT501","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1702654219451,"defaultSendRequestWhen":"immediate"}

### Comments

Sorry for this very weird Issue. 

I am not a developer so I have no idea how to make pull requests. 

I added this external converter in my home assistant and it works. 

Would someone be so nice to add it to the müller_licht.ts? :) 

Thanks very much. 

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['LED Strip'],
    model: '404118', 
    vendor: 'Müller Licht', 
    description: 'tint LED-Strip white+color, 5 m', 
    fromZigbee: [], 
    extend: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 555], supportsHueAndSaturation: true}),
    toZigbee: extend.light_onoff_brightness_colortemp_color({colorTempRange: [153, 555], supportsHueAndSaturation: true}).toZigbee.concat([tz.tint_scene]), 
};

module.exports = definition;
```

### Supported color modes

color temperature, color (RGB)

### Color temperature range

{"colorTempPhysicalMin":153,"colorTempPhysicalMax":555}

**Comment by Koenkk** [comment]
Will be supported in the next release (added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6697)
