### ISSUE TITLE
[New device support]: 

### ISSUE THREAD

**Issue by maltbit** [Koenkk/zigbee2mqtt#20235]
### Link

https://www.amazon.de/dp/B0BWJHHK89?ref=ppx_yo2ov_dt_b_product_details&th=1

### Database entry

{"id":17,"type":"EndDevice","ieeeAddr":"0xa4c1384ce5516233","nwkAddr":39948,"manufId":4417,"manufName":"_TZE204_yjjdcqsq","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0011","65506":56,"65508":0,"65534":0,"appVersion":73,"modelId":"TS0601","manufacturerName":"_TZE204_yjjdcqsq","powerSource":3,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1335756102},"lastSeen":1702719845647,"defaultSendRequestWhen":"immediate"}

### Comments

This device is not supported using zigbee2mqtt version 1.34.0 commit 56589dcc.
It seems to be a clone of TuYa ZTH01 which is already supported by Zigbee2MQTT.
I managed to get it supported by adding an additional manufacturer fingerprint in the tuya.js file in 
directory  /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices  .
Could you please officially integrate this device into zigbee2mqtt?
Thank you.
[tuya_modified_zth01.tar.gz](https://github.com/Koenkk/zigbee2mqtt/files/13692360/tuya_modified_zth01.tar.gz)

### External converter

```shell
extract of /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/tuya.js with modification - making this device supported (entries '_TZE204_yjjdcqsq' added):

{
        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_yjjdcqsq', '_TZE200_9yapgbuv', '_TZE204_upagmta9', '_TZE200_cirvgep4', '_TZE200_upagmta9', '_TZE204_yjjdcqsq']),
        model: 'TS0601_temperature_humidity_sensor_2',
        vendor: 'TuYa',
        description: 'Temperature and humidity sensor',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        onEvent: tuya.onEvent({ queryOnDeviceAnnounce: true }),
        configure: async (device, coordinatorEndpoint, logger) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            // Required to get the device to start reporting
            await device.getEndpoint(1).command('manuSpecificTuya', 'dataQuery', {});
        },
        exposes: [e.temperature(), e.humidity(), tuya.exposes.batteryState(), tuya.exposes.temperatureUnit()],
        meta: {
            tuyaDatapoints: [
                [1, 'temperature', tuya.valueConverter.divideBy10],
                [2, 'humidity', tuya.valueConverter.raw],
                [3, 'battery_state', tuya.valueConverter.batteryState],
                [9, 'temperature_unit', tuya.valueConverter.temperatureUnitEnum],
            ],
        },
        whiteLabel: [
            tuya.whitelabel('TuYa', 'ZTH01', 'Temperature and humidity sensor', ['_TZE200_yjjdcqsq']),
            tuya.whitelabel('TuYa', 'ZTH02', 'Temperature and humidity sensor', ['_TZE200_9yapgbuv']),
            tuya.whitelabel('TuYa', 'ZTH05', 'Temperature and humidity sensor', ['_TZE204_upagmta9', '_TZE200_upagmta9']),
            tuya.whitelabel('TuYa', 'ZTH08-E', 'Temperature and humidity sensor', ['_TZE200_cirvgep4']),
            tuya.whitelabel('TuYa', 'ZTH01', 'Temperature and humidity sensor', ['_TZE0204_yjjdcqsq']),
        ],
    },
```

**Comment by Koenkk** [comment]
done!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
