### ISSUE TITLE
problem with Aqara body movement sensor in Domoticz

### ISSUE THREAD

**Issue by bartve66** [Koenkk/zigbee2mqtt#2023]
I updated zigbee2mqtt, firmware of coordinator and routers and the Domoticz plugin to the most recent versions  (I was on very old versions).
I want to use an Aqara body movement sensor (RTCGQ11LM) in Domoticz. I can pair the sensor, and zigbee2mqtt publishes this topic:
1:00:15 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0002d43eb2', payload '{"illuminance":77,"linkquality":39,"occupancy":true}'
Which looks good to me. But in Domoticz in the setup>devices page I *only* see the linkquality part, and not the others like illuminance and most importantly occupancy. 
In my old setup I could see those parts as separate sensors in Domoticz.
So I figure something goes wrong with the reading of the zigbee2mqtt topic in Domoticz?

**Comment by Koenkk** [comment]
From the zigbee2mqtt side it looks that things are OK. 

I will close this issue as it is not a zigbee2mqtt issue (issue seems with Domoticz). Please consult their forum for support.
