### ISSUE TITLE
HEIMAN HS2IRC - Error with command getlist

### ISSUE THREAD

**Issue by chris777c** [Koenkk/zigbee2mqtt#20250]
### What happened?

Hello,

When i send command 
`{
    "get_list": ""
}
`
like explain on user guide : [here](https://www.zigbee2mqtt.io/devices/HS2IRC.html#get-list-of-the-stored-devices-and-keys)

It don't work and on log I have show this message : 

`error 2023-12-17 08:54:41Publish 'set' 'get_list' to 'heiman-ircontrol' failed: 'Error: undefined is not a object, got string ("")'`

### What did you expect to happen?

I'd would like show me list of key record

### How to reproduce it (minimal and precise)

send command

### Zigbee2MQTT version

1.34

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Debug log

`debug 2023-12-17 08:54:41Received MQTT message on 'zigbee2mqtt/heiman-ircontrol/set' with data '{"get_list":""}'
debug 2023-12-17 08:54:41Publishing 'set' 'get_list' to 'heiman-ircontrol'
error 2023-12-17 08:54:41Publish 'set' 'get_list' to 'heiman-ircontrol' failed: 'Error: undefined is not a object, got string ("")'`

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by chris777c** [comment]
Thank you
