### ISSUE TITLE
Group definitions need to be fixed

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#2025]
Is there a way to fix the definition which device is in which group? My group definitions are (seldomly) modified by z2m. Not sure why but I'd rather have z2m stick to what the user defined in the group configuration.

**Comment by Koenkk** [comment]
Does this still occur in the latest dev branch?

**Comment by andreasbrett** [comment]
I'm on dev from September 19th (983f55ce3d8475c40a427d4b20d5927949d396cb)

**Comment by Koenkk** [comment]
Do you see any reasons why this happens in the logging?

**Comment by andreasbrett** [comment]
I think we can close this issue. I can't find relevant info in the logs as I can't pin down when the group got re-written. I'll raise another issue when this happens again.
