### ISSUE TITLE
Symfonisk dot_1 not reporting anymore since last update 

### ISSUE THREAD

**Issue by Begie1605** [Koenkk/zigbee2mqtt#20269]
### What happened?

The mqtt message when pressing the single dot on a symfonisk remote report as null.
Before update the reported Dot_1_initial_press, now it does not anymore. same for dot_2_initial press ...double press works still.
Removing and adding again did not solve

### What did you expect to happen?

After install of  1.34.0-1 Z2M

### How to reproduce it (minimal and precise)

Press DOT1 or DOT2....null reported

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

**Comment by Koenkk** [comment]
Already fixed in the  [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) (will be fixed in the 1 January release).
