### ISSUE TITLE
Lixee ZLinky_TIC Stopped reporting all three phases of Linky

### ISSUE THREAD

**Issue by Xalio** [Koenkk/zigbee2mqtt#20263]
### What happened?

Hi all,

after updating Zigbee2MQTT to 1.33.2-1 build my Lixee ZLinky_TIC device stopped reporting after some time.

I tried this update twice (with roll back to 1.33.1-1 that works well) twice the same issue happened.

![IMG_1122](https://github.com/Koenkk/zigbee2mqtt/assets/774362/2258e0a9-a7cf-4794-bae3-3af6da2d7ac5)

### What did you expect to happen?

Just work and report data as normal 

### How to reproduce it (minimal and precise)

I’ve reproduced it consistently with the update 1.33.2-1

### Zigbee2MQTT version

1.33.2-1

### Adapter firmware version

7.3.1.0 build 0

### Adapter

/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_787368ec5741ed1189db86a7ccf2b06c-if00-port0

### Debug log

[45df7312_zigbee2mqtt_2023-12-17T21-35-33.329Z.log](https://github.com/Koenkk/zigbee2mqtt/files/13697824/45df7312_zigbee2mqtt_2023-12-17T21-35-33.329Z.log)

**Comment by coubi64** [comment]
I'm having this problem with latest 1.35.2 version (EDF TEMPO). Some other Zlinky entities don't work either.
