### ISSUE TITLE
[New device support]: add new fingerprint Tuya TS0210  _TZ3000_jqge2fjx

### ISSUE THREAD

**Issue by wowrevv** [Koenkk/zigbee2mqtt#20272]
### Link

https://www.zigbee2mqtt.io/devices/TS0210.html

### Database entry

n/a

### Comments

added manually to tuya.js and seems to pick it up

<img width="1080" alt="Screenshot 2023-12-18 at 11 05 43 pm" src="https://github.com/Koenkk/zigbee2mqtt/assets/22498390/ef939703-25cc-486c-ba48-7ac835645c3e">

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
