### ISSUE TITLE
[dev] Not replying to group zigbee2mqtt/bridge/group/[GROUP_FRIENDLY_NAME]/add|remove MQTT commands

### ISSUE THREAD

**Issue by juanjux** [Koenkk/zigbee2mqtt#2027]
# Bug Report

## What happened

Issuing an MQTT message of `zigbee2mqtt/bridge/group/[GROUP_FRIENDLY_NAME]/add|remove` doesn't get any reply from z2mqtt logs, but it shows on my mosquitto log, so the add/remove command doesn't work.

## What did you expect to happen

Get some reply on the log and the add/remove command to be completed successfully.

## Debug Info
zigbee2mqtt version: #9d4705f
CC253X firmware version: 20190619 (source_routing)

**Comment by Koenkk** [comment]
Can you provide debug logs?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by juanjux** [comment]
That's the problem, there is no z2mqtt log for this, but I can see the MQTT call on mosquitto logs.

I'll update -dev again at home in a few hours when I return home and try again, tell me if there is something else I can doo to pinpoint the problem.

**Comment by juanjux** [comment]
I tried again and this time it worked. Who knows what happened the first time... T
