### ISSUE TITLE
question: Friendly Name as Paths (cant find docs)

### ISSUE THREAD

**Issue by rm2kdev** [Koenkk/zigbee2mqtt#2028]
This is just a quick question i couldn't find it on the docs (did read, extensively)

Does friendly_name support paths i.e
can i call my hue lights

friendly_name: Hue/Lights/Kitchen/Roof
friendly_name: Hue/Lights/Kitchen/Lamp
friendly_name: Hue/Lights/Bedroom/Roof
friendly_name: Hue/Lights/Hallway/Roof

and device like

friendly_name: Hue/Dimmers/Bedroom
friendly_name: Hue/Dimmers/Kitchen
friendly_name: Hue/Dimmers/Lounge
friendly_name: Sensors/Temp/Kitchen

**Comment by carldebilly** [comment]
It's not supported yet by Zigbee2MqttAssistant.. https://github.com/yllibed/Zigbee2MqttAssistant/issues/26

But I think I'll fix it soon if it's officially supported by Zigbee2Mqtt.

**Comment by Koenkk** [comment]
`/` within the friendly name is allowed and tested.
