### ISSUE TITLE
IKEA TRADFRI ON/OFF Switch shows 200% battery

### ISSUE THREAD

**Issue by lukasjakobi** [Koenkk/zigbee2mqtt#20299]
### What happened?

After updating the IKEA TRADFRI ON/OFF Switch (https://www.zigbee2mqtt.io/devices/E1743.html#ikea-e1743) to version     24.4.6 and later swapping the battery, it started showing 200% of battery and continued to the current state of 180%

### What did you expect to happen?

I expected the battery to be capped at a maximum of 100%

### How to reproduce it (minimal and precise)

Update the switch to 24.4.6, Swap battery

### Zigbee2MQTT version

1.29.2 commit: bb3e8f6

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

![Screenshot from 2023-12-19 17-21-51](https://github.com/Koenkk/zigbee2mqtt/assets/45894950/b4eb68b5-d836-4ca2-a5f8-7ce33b88dfa2)

**Comment by lukasjakobi** [comment]
i just updated to [1.34.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.34.0) and the issue still exists

**Comment by antti365** [comment]
@Koenkk I confirm there is such a problem, 1.34.0 commit: 56589dc. I also encountered it myself.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by jvuotila** [comment]
Still same problem with 1.40.1.

**Comment by matsahm** [comment]
Still same problem with 2.10.1. See Screenshot:

<img width="707" height="121" alt="Image" src="https://github.com/user-attachments/assets/8799ad8d-6575-409f-b79c-f10f9735cb5c" />
