### ISSUE TITLE
Philips 5047130P9

### ISSUE THREAD

**Issue by chris-1243** [Koenkk/zigbee2mqtt#20306]
### What happened?

On the latest dev branch, I unfortunately get this error:

error 2023-12-20 09:46:45: Publish 'get' 'color_temp' to 'Enzo lit' failed: 'Error: Read 0x0017880108c6ceb8/11 lightingColorCtrl(["colorMode","currentX","currentY","enhancedCurrentHue","currentSaturation","colorTemperature"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
error 2023-12-20 09:47:35: Publish 'get' 'color_temp' to 'Enzo plafonnier' failed: 'Error: Read 0x0017880109aebafe/11 lightingColorCtrl(["colorMode","currentX","currentY","enhancedCurrentHue","currentSaturation","colorTemperature"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 33270 - 11 - 9 - 768 - 1 after 10000ms)'

### What did you expect to happen?

To have the same behavior as 1.33.2

### Zigbee2MQTT version

1.34.0 latest-dev

### Adapter firmware version

20231112

### Adapter

Sonoff Dongle-P

### Debug log

[herdsman_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13725063/herdsman_log.txt)

**Comment by Koenkk** [comment]
Can you try reading the attributes one by one via the z2m frontend -> dev console -> read from lightingcolorctrl cluster attributes `colorMode","currentX","currentY","enhancedCurrentHue","currentSaturation","colorTemperature`, which one fails?

**Comment by chris-1243** [comment]
Below are the results:

"enhancedCurrentHue", "currentSaturation" are generating the errors

error 2023-12-20 21:23:36: Publish 'set' 'read' to 'Enzo lit' failed: 'Error: Read 0x0017880108c6ceb8/11 lightingColorCtrl(["enhancedCurrentHue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

error 2023-12-20 21:25:15: Publish 'set' 'read' to 'Enzo lit' failed: 'Error: Read 0x0017880108c6ceb8/11 lightingColorCtrl(["currentSaturation"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by Koenkk** [comment]
Thanks, should be fixed now!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by chris-1243** [comment]
It may not be the right place to ask but any major code change regarding Philips light ?

I have a bunch of them and different models. I need to provide you the errors and which attributes but I have been able to reproduce the same behaviour, same field with other lights.

The errors are not presents on version 1.33.2.

**Comment by Koenkk** [comment]
Which other lights?

**Comment by Koenkk** [comment]
I pushed a correct fix now (also for non Philips lights)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by chris-1243** [comment]
It seems to be solved with the latest-dev.

Thanks for you support
