### ISSUE TITLE
AVATTO ME167 - Z2M Gui, schedule examples are showing 6 values, Valve only accepts 4 values 

### ISSUE THREAD

**Issue by TrolliRolli** [Koenkk/zigbee2mqtt#20338]
### Link

https://www.zigbee2mqtt.io/devices/ME167.html

### Model

ME167

### Description

Heating Valve

### Vendor

AVATTO

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/ME167.jpg

### Database entry

{"id":22,"type":"EndDevice","ieeeAddr":"xxx","nwkAddr":286,"manufId":4417,"manufName":"_TZE200_6rdj8dzm","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"N�\u0016-iQ�\u0016-iT�\u0016-iW�\u0016-i]�\u0016-ib�\u0016-i �\u0016-i#�\u0016-i","65506":55,"65508":0,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_6rdj8dzm","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":xxx,"defaultSendRequestWhen":"immediate"}

### Notes

The examples within z2m gui details page of the device does show that the daily config needs 6 values, the system only accepts 4 values, so the example config is wrong.
Schedule for monday, format: "HH:MM/C HH:MM/C HH:MM/C HH:MM/C HH:MM/C HH:MM/C" 
should be
Schedule for monday, format: "HH:MM/C HH:MM/C HH:MM/C HH:MM/C"

**Comment by pgarnek** [comment]
same thing with ME168, bump
