### ISSUE TITLE
cache_state: false keeps storing states in state.json

### ISSUE THREAD

**Issue by soloam** [Koenkk/zigbee2mqtt#2033]
# Bug Report
## What happened
Advanced cache_state: false and state.json keeps storing data

## What did you expect to happen
No states stored in state.json and no state send in boot

## How to reproduce it (minimal and precise)
add cache_state: false to Advanced and the state.json keeps updating

## Debug Info
zigbee2mqtt version: 1.5.1

**Comment by Koenkk** [comment]
- It is expected for `state.json` to be updated even when `cache_state: false`
- On startup it indeed shouldn't publish the cached states when `cache_state: false` -> fixed in the dev branch.
