### ISSUE TITLE
[Wrong device]: 

### ISSUE THREAD

**Issue by barbaschela** [Koenkk/zigbee2mqtt#20332]
### Link

https://a.aliexpress.com/_Ewfzs0D

### Model

ZN231392 or TS0111_valve

### Description

Smart water/gas valve

### Vendor

Tuya

### Picture (link)

https://ae01.alicdn.com/kf/S3703391b26294f03ad76fe7547b17653p/V-lvula-de-agua-WiFi-Tuya-Zigbee-controlador-de-apagado-de-Gas-compatible-con-Alexa-asistente.jpg_80x80.jpg_.webp

### Database entry

{"id":56,"type":"Router","ieeeAddr":"0xa4c138ec3e995227","nwkAddr":43664,"manufId":4417,"manufName":"_TZ3000_wpueorev","po werSource":"Mains (single phase)","modelId":"TS0001","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256, "inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes": {"65503":"b \u0003-\u0012","65506":56,"65508":0,"65534":0,"stackVersion":0,"dateCode":"", "manufacturerName":"_TZ3000_wpueorev","zclVersion":3,"appVersion":83,"modelId":"TS0001","powerSource":1}}, "genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0, "tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":0,"switchType":0}}, "manuSpecificBosch":{"attributes":{"53251":"AAAA"}}},"binds":[{"cluster":6,"type":"endpoint", "deviceIeeeAddress":"0x00124b00214f2096","endpointID":1}],"configuredReportings":[], "meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{}, "binds":[],"configuredReportings":[],"meta":{}}},"appVersion":83,"stackVersion":0,"hwVersion":1,"dateCode":"", "zclVersion":3,"interviewCompleted":true,"meta":{"configured":153093895},"lastSeen":1703065946246, "defaultSendRequestWhen":"immediate"}

**Comment by Koenkk** [comment]
Fix for this is included in the next release (1 Jan).
