### ISSUE TITLE
IKEA LED2107C4 TRADFRI bulb E14 WS candle 470lm - Not discovered

### ISSUE THREAD

**Issue by mschut** [Koenkk/zigbee2mqtt#20342]
### What happened?

When trying to connect my new IKEA bulbs (LED2107C4) this version just wont be recognised. 

I have read other issues here about this bulb, and found out it was added in the Zigbee-herdsman-converters version 15.91.0. I have currently version 15.130.1 installed, so I would assume this is up to date. 

### What did you expect to happen?

It would show up in my discovered devices. 

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20210708

### Adapter

usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

**Comment by crudooper** [comment]
I have the same problem. How someone pair this device ? It's indicated into manual, toggle main switch 6x, but not in my case... I have a few other bulb from Ikea, no problem...

**Comment by crudooper** [comment]
I tried to update adapter firmware to the last version available (20230507), but it's still the same.

**Comment by nzottmann** [comment]
Have you been able to get the bulb discovered in the meanwhile @mschut ?

**Comment by nzottmann** [comment]
I found a solution for this. Seems like the bulb is quite sensitive about the timing of the reset procedure (turning it off and on 6 times). I could not get this working with flipping the switch manually, but it worked using a smart plug.

Waiting **800ms** between each toggle worked reliably.
