### ISSUE TITLE
[New device support]: IKEA Rodret W2328

### ISSUE THREAD

**Issue by Metti93** [Koenkk/zigbee2mqtt#20373]
### Link

There is no official Page, but i got it here

### Database entry

{"id":10,"type":"EndDevice","ieeeAddr":"0x5cc7c1fffe62b1b4","nwkAddr":58277,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"SOMRIG shortcut button","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0,1,3,4,32,4096,64636,64640],"outClusterList":[3,4,6,8,25,4096,64640],"clusters":{"genPollCtrl":{"attributes":{"checkinInterval":172800}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x1c34f1fffef2a639","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":6,"inClusterList":[0,3,4,64640],"outClusterList":[3,4,6,8,64640],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":113,"hwVersion":1,"dateCode":"20230308","swBuildId":"1.0.20","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1703452012147,"defaultSendRequestWhen":"active","checkinInterval":43200}

### Comments

i tried to follow this guide, but i got absolutly no information out of the device, after "Once finished, restart Zigbee2MQTT and trigger some actions on the device. You will see messages like:"
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

**Comment by Koenkk** [comment]
This device will be supported in the 1 January release
