### ISSUE TITLE
[Feature request]: add an option to assign Home Assistant entity_category from custom converter

### ISSUE THREAD

**Issue by osnwt** [Koenkk/zigbee2mqtt#20376]
### Is your feature request related to a problem? Please describe

Writing converter for DIY device for Home Assistant, I have not found an option to declare some entities as configuration or setting, etc. It seems to be hardcoded for known cases, but would be nice to have such option for converter, too.

### Describe the solution you'd like

Add an option to override entity_category in converters for Home Assistant.

### Describe alternatives you've considered

Maybe I missed such an option?

### Additional context

N/A

**Comment by slugzero** [comment]
Thank you for linking this to my feature request, and sorry, I wasn't aware of yours when I opened it.
With the latest `dev` version, you should now be able to do what you like by adding `.withCategory('config')` or `'diagnostic'` to your exposes.

**Comment by osnwt** [comment]
Thanks, excellent solution.
I'd close it as soon as it comes to a released version.
