### ISSUE TITLE
TO-Q-SY1-JZT precision/decimal places not working

### ISSUE THREAD

**Issue by nireins** [Koenkk/zigbee2mqtt#20372]
### What happened?

Hi, i use some TO-Q-SY1-JZT and i change the power_precision, current_precision and voltage_precision to 3, but only the current_precision shows 3 decimal places. 

![bild1](https://github.com/Koenkk/zigbee2mqtt/assets/69728116/f402c7ba-7668-44fd-8cdc-6d07741bde44)

Am I doing something wrong or can the device not do this?

### What did you expect to happen?

That the decimal places are displayed after setting.

### How to reproduce it (minimal and precise)

![bild2](https://github.com/Koenkk/zigbee2mqtt/assets/69728116/45ebd331-22d1-438f-89ef-1e8d32e247bc)

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

7.3.1.0 build 176

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by mrmaximas** [comment]
@nireins i'ts absolutely normal situation. If the device outputs integers, then whatever precision you set it to, it will be integers.

**Comment by Koenkk** [comment]
Z2M can only reduce the precision, not increase it (since the device simply doesn't report it).
