### ISSUE TITLE
Conbee III 

### ISSUE THREAD

**Issue by sw224** [Koenkk/zigbee2mqtt#20381]
### What happened?

Today I installed the conbee III coordinator, all devices work properly except the Aqara E1 roller shutter motor. The system adds it as an unsupported device. Everything worked correctly on the conbee II coordinator.

### Zigbee2MQTT version

 1.34.0-1

### Adapter firmware version

DE03110417

### Adapter

Conbee III

**Comment by T-IOOO** [comment]
I have slae.sh stick and homebridge adds an unsupported device ”coordinator” that crashes the entire z2m-plugin. A manual removal of the device from homebridge solves the problem temporally

**Comment by GustavFBrandsen** [comment]
I have exactly the same problem with the E1 Roller motor, and the ConBee III.
Have you found a solution to the problem?

**Comment by sw224** [comment]
Unfortunately not yet.

**Comment by GustavFBrandsen** [comment]
https://phoscon.de/en/conbee3/compatible

This list doesn't have the E1 Driver on it... It seems like someone needs to make it compatible first...

**Comment by GustavFBrandsen** [comment]
To anyone needing this: I managed to get it paired by updating the ConBee 3 to firmware 0x26500900 and Z2M at 1.35.3

**Comment by dyvyak** [comment]
conbee III doesn't work well with z2m. conbee II is much better. i learned that by hard way...
