### ISSUE TITLE
Ikea dimmer device toggles Aqara plug unintentionally

### ISSUE THREAD

**Issue by Alfy1080** [Koenkk/zigbee2mqtt#20397]
### What happened?

I have an Ikea SYMFONISK Sound Controller (https://www.zigbee2mqtt.io/devices/E1744.html#ikea-e1744) in Z2M connected directly to an Aqara EU smart plug router (https://www.zigbee2mqtt.io/devices/SP-EUC01.html#xiaomi-sp-euc01). Without configuring any automation for these devices, if i press the Ikea device's button, the Aqara router's power switch is toggled. This only happens if the Ikea device is connected directly to this particular Aqara router. If i pair the Ikea device to a different router or to the coordinator, this issue never happens.

The Ikea device can be found in the logs as Bedroom_Dimmer_2 and the Aqara device is Balcony_Plug.

### What did you expect to happen?

I expect that the button press on the Ikea device does nothing to any other devices unless specified in a Home Assistant automation.

### How to reproduce it (minimal and precise)

Pair an Ikea SYMFONISK Sound Controller in Z2M to an Aqara EU smart plug router, and then press the button of the Ikea device. The Aqara EU smart plug's switch will be toggled on every button press.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20230507

### Adapter

Sonoff ZB Dongle-P (CC2652P)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13775806/log.txt)

**Comment by Koenkk** [comment]
This is a bug of the Aqara devices, more info can be found [here](https://github.com/Koenkk/zigbee2mqtt/issues/16918)
