### ISSUE TITLE
[Wrong device]: IKEA LED2103G5

### ISSUE THREAD

**Issue by heviiguy** [Koenkk/zigbee2mqtt#20402]
### Link

https://www.zigbee2mqtt.io/devices/LED2103G5.html

### Model

TRÅDFRI LED 800lm

### Description

Should include "E26"

### Vendor

IKEA

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/LED2103G5.jpg

### Database entry

na

### Notes

The existing description shows this bulb having an E27 base (220 vAC)
This bulb is also available with an E26 base (110 vAC)

**Comment by Koenkk** [comment]
Done!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by heviiguy** [comment]
Thanks for this as well, Koen 👍
