### ISSUE TITLE
Error while trying to update device firmware: 'Self signed certificate in certificate chain'

### ISSUE THREAD

**Issue by Grandma-Betty** [Koenkk/zigbee2mqtt#20429]
### What happened?

While trying to update one of my Philips Hue Smart Plugs via OTA, the following error occurred:

`error 2023-12-29 10:28:20Update of 'HueSmartPlugCH07' failed (self signed certificate in certificate chain)`

Any hints what the problem could be?
Thanks!

### What did you expect to happen?

Update process of device firmware as usually.

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13792351/log.txt)

**Comment by rutgerhendriks** [comment]
I'm having the same error message with different Philips Hue devices:
Hue white and color ambiance E26/E27/E14
Hue white ambiance GU10

Those are the only ones that need an update, so I expect it happens for all Philips Hue?

**Comment by oedzesg** [comment]
+1. 

Exactly same problem over here since this morning. 
Also with Hue devices.

**Comment by kaechele** [comment]
Root Cause: Signify switched `https://otau.meethue.com` over to a self-signed certificate yesterday.
Matches my observations: I did successfully update one light two days ago but the others started failing to update yesterday.

**Comment by Sopka** [comment]
As a workaround: I am using the official docker image of zigbee2mqtt and included the self-signed root CA from Philips HUE:

```
-----BEGIN CERTIFICATE-----
MIIBwDCCAWagAwIBAgIJAJtrMkoTxs+WMAoGCCqGSM49BAMCMDIxCzAJBgNVBAYT
Ak5MMRQwEgYDVQQKDAtQaGlsaXBzIEh1ZTENMAsGA1UEAwwEcm9vdDAgFw0xNjA4
MjUwNzU5NDNaGA8yMDY4MDEwNTA3NTk0M1owMjELMAkGA1UEBhMCTkwxFDASBgNV
BAoMC1BoaWxpcHMgSHVlMQ0wCwYDVQQDDARyb290MFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEENC1JOl6BxJrwCb+YK655zlM57VKFSi5OHDsmlCaF/EfTGGgU08/
JUtkCyMlHUUoYBZyzCBKXqRKkrT512evEKNjMGEwHQYDVR0OBBYEFAlkFYACVzir
qTr++cWia8AKH/fOMB8GA1UdIwQYMBaAFAlkFYACVzirqTr++cWia8AKH/fOMA8G
A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0gAMEUC
IQDcGfyXaUl5hjr5YE8m2piXhMcDzHTNbO1RvGgz4r9IswIgFTTw/R85KyfIiW+E
clwJRVSsq8EApeFREenCkRM0EIk=
-----END CERTIFICATE-----
```

Save as `otau-meethue-com-root.crt` and use e.g. this Dockerfile:

```
FROM docker.io/koenkk/zigbee2mqtt:1.34.0

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY ./otau-meethue-com-root.crt /usr/local/share/ca-certificates/otau-meethue-com-root.crt
RUN update-ca-certificates
```

The OTA update will work again.

**Comment by UsernetFR** [comment]
I have just started installing the Philips Hue solution.... My bad.
OTA update is not possible -> "Update of   failed self signed certificate in certificate chain"

It starts badly :/

**Comment by jdaandersj** [comment]
> As a workaround: I am using the official docker image of zigbee2mqtt and included the self-signed root CA from Philips HUE:
> 
> ```
> -----BEGIN CERTIFICATE-----
> MIIBwDCCAWagAwIBAgIJAJtrMkoTxs+WMAoGCCqGSM49BAMCMDIxCzAJBgNVBAYT
> Ak5MMRQwEgYDVQQKDAtQaGlsaXBzIEh1ZTENMAsGA1UEAwwEcm9vdDAgFw0xNjA4
> MjUwNzU5NDNaGA8yMDY4MDEwNTA3NTk0M1owMjELMAkGA1UEBhMCTkwxFDASBgNV
> BAoMC1BoaWxpcHMgSHVlMQ0wCwYDVQQDDARyb290MFkwEwYHKoZIzj0CAQYIKoZI
> zj0DAQcDQgAEENC1JOl6BxJrwCb+YK655zlM57VKFSi5OHDsmlCaF/EfTGGgU08/
> JUtkCyMlHUUoYBZyzCBKXqRKkrT512evEKNjMGEwHQYDVR0OBBYEFAlkFYACVzir
> qTr++cWia8AKH/fOMB8GA1UdIwQYMBaAFAlkFYACVzirqTr++cWia8AKH/fOMA8G
> A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0gAMEUC
> IQDcGfyXaUl5hjr5YE8m2piXhMcDzHTNbO1RvGgz4r9IswIgFTTw/R85KyfIiW+E
> clwJRVSsq8EApeFREenCkRM0EIk=
> -----END CERTIFICATE-----
> ```
> 
> Save as `otau-meethue-com-root.crt` and use e.g. this Dockerfile:
> 
> ```
> FROM docker.io/koenkk/zigbee2mqtt:1.34.0
> 
> RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
> COPY ./otau-meethue-com-root.crt /usr/local/share/ca-certificates/otau-meethue-com-root.crt
> RUN update-ca-certificates
> ```
> 
> The OTA update will work again.

If, like me, you followed the linux installation guide (not docker), you need to do a bit extra.

1. Do as quoted above (on the linux host where z2m runs)
2. Edit `/etc/systemd/system/zigbee2mqtt.service` env config to this: `Environment=NODE_ENV=production NODE_OPTIONS=--use-openssl-ca`
3. Reboot linux host (should be possible to just reload systemctl then restart service but for some reason this didn't work for me)
4. OTA for hue lives again (until they use a new cert :/ )

**Comment by Koenkk** [comment]
Working on a proper fix in https://github.com/Koenkk/zigbee-OTA/issues/420

**Comment by MarkoMarjamaa** [comment]
>     3. Reboot linux host (should be possible to just reload systemctl then restart service but for some reason this didn't work for me)

systemctl daemon-reload 
worked for me.
