### ISSUE TITLE
How to support new devices with 1.6 dev in the docker?

### ISSUE THREAD

**Issue by alexsahka** [Koenkk/zigbee2mqtt#2042]
Any updated instructions?
Do I need to clone zigbee-shepherd-converters?
Or zigbee-herdsman.

What is the Docker Volume mapping to?
/app/node_modules/zigbee-shepherd-converters
Please help and Thanks!

**Comment by Koenkk** [comment]
You need to clone the zigbee-herdsman-converters branch from zigbee-shepherd-converters and map it to /app/node_modules/zigbee-herdsman-converters

I will make sure that the instructions will be updated before zigbee2mqtt 1.7.

**Comment by alexsahka** [comment]
Thanks
