### ISSUE TITLE
Inovelli Converter Missing Parameters and Wrongly Named Parameters

### ISSUE THREAD

**Issue by efaden** [Koenkk/zigbee2mqtt#20424]
### What happened?

For the VZM31 parameter 26 is missing.  

see: https://help.inovelli.com/en/articles/8189241-blue-series-2-1-switch-parameters#h_d74d1ef609

For the VZM35 a bunch of the parameters names/values are incorrect since they differ from the VZM31, but they aren't different in the converter.

see: https://help.inovelli.com/en/articles/8231399-blue-series-fan-switch-parameters

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20230507

### Adapter

Tubes POE

**Comment by Koenkk** [comment]
@InovelliUSA could you check this?

**Comment by efaden** [comment]
If I have time later I can run through them and submit a PR

**Comment by efaden** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6786
