### ISSUE TITLE
[New Device Support] Heiman Vibration Sensor 

### ISSUE THREAD

**Issue by Lollos60** [Koenkk/zigbee2mqtt#20433]
### Link

https://it.aliexpress.com/item/4001114731876.html?srcSns=sns_WhatsApp&spreadType=socialShare&bizType=ProductDetail&social_params=21332029181&aff_fcid=92fdd71448ce40a684dd091d10f41544-1703867782539-02666-_mrcfZp2&tt=MG&aff_fsk=_mrcfZp2&aff_platform=default&sk=_mrcfZp2&aff_trace_key=92fdd71448ce40a684dd091d10f41544-1703867782539-02666-_mrcfZp2&shareId=21332029181&businessType=ProductDetail&platform=AE&terminal_id=a0d62cf8bbd3443395016333b1d06ebf&afSmartRedirect=y

### Database entry

{"id":52,"type":"EndDevice","ieeeAddr":"0xec1bbdfffee4c978","nwkAddr":12530,"manufId":4619,"manufName":"_TYZB01_pbgpvhgx","powerSource":"Battery","modelId":"TS0210","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1280,2821],"outClusterList":[25],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":2,"hwVersion":16,"dateCode":"2019.4.1","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1703867629620,"defaultSendRequestWhen":"active","checkinInterval":3600}

### Comments

This vibration sensor looks the same as the Heiman HS1VS-EF and the HS1VS-N but is not supported yet and shown as TS0210 and labeled as unsupported device.

**Comment by Koenkk** [comment]
Will be supported in the z2m 1 January release!
