### ISSUE TITLE
linkquality is bad even with antenna

### ISSUE THREAD

**Issue by guitar9** [Koenkk/zigbee2mqtt#2044]
Hello, 
I have bought a CC2531 with antenna. But the linkquality is bad. I am 7 meters away from the stick with 2 walls between and the linkquality is 31.
Somebody can say me the connecting to the antenna is correct?
![WhatsApp Image 2019-09-27 at 20 25 12](https://user-images.githubusercontent.com/25721108/65793485-3b574680-e166-11e9-948f-7c15071c36aa.jpeg)
![WhatsApp Image 2019-09-27 at 20 25 12 (1)](https://user-images.githubusercontent.com/25721108/65793496-401bfa80-e166-11e9-9136-5bd5518b14d4.jpeg)

zigbee2mqtt version: 1.5.1
CC253X firmware version: 20190608

**Comment by guitar9** [comment]
I tried to soldering with another cc2531 like in this tutorial. https://hassiohelp.eu/2019/03/02/zigbee-cc2531-antenna/

But it is the same. linkquality 31 :( 
Maybe it has something to do with my wlan router? Should I try to change the channel of the cc2531?

**Comment by guitar9** [comment]
1.5 meters away from the stick behind a chair a get linkquality 47. And without antenna no connection. This is shit :dagger:

**Comment by guitar9** [comment]
Is it possible that my internet router sends on the same frequency and destroys my zigbee network? I have a speedport W724V

**Comment by Koenkk** [comment]
Did you already try https://www.zigbee2mqtt.io/how_tos/how_to_improve_network_range.html?

Note that the antenna on the CC2531 is actually quite good already (due to it's design).

**Comment by guitar9** [comment]
yes I have a usb extension cable and I tried to change to channel

**Comment by guitar9** [comment]
I solved with using a cc2531 flashed as routers
