### ISSUE TITLE
Transition time for bulbs not applied when state change from z2m groups

### ISSUE THREAD

**Issue by peikelias** [Koenkk/zigbee2mqtt#20447]
### What happened?

When changing states(brightness, color) from the group entity the light does not add the transition time to the zigbee message and the light shows no transition.

When sending the state change directly to the single bulb/bulbs when using the Home Assistant group helper function, i get the state change with transitions.

An addition may also have a seperate transition time for groups, that can be set in groups settings?
Like that if no group transition is set -> check if bulb has specific transition and use that instead -> if no group or bulb transition do instant state change?

[Bulbs in use](https://www.zigbee2mqtt.io/devices/929001953101.html#philips-929001953101)

### What did you expect to happen?

Light changes state with the transition time as specified for the light.

### How to reproduce it (minimal and precise)

Send command to the light group entity generated by z2m - **No transition**
Send command directly to the light entity - **Transition Works**

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by ashald** [comment]
@peikelias did you figure it out?
