### ISSUE TITLE
Gledopto GL-LB-001P missing settings

### ISSUE THREAD

**Issue by Gibbz** [Koenkk/zigbee2mqtt#20455]
### What happened?

Device supports a color mode setting: color_mode
However it cannot be set from mqtt, no converter available for set 'color_mode'

### What did you expect to happen?

color mode to work

### Zigbee2MQTT version

1.34.0 

### Adapter firmware version

20220219

### Adapter

zzh

### Debug log

2023-12-31 13:32:29No converter available for 'set' 'color_mode' (xy)
2023-12-31 13:32:32No converter available for 'set' 'color_mode' (color_temp)

**Comment by Koenkk** [comment]
The color mode can be changed by setting a color (xy or hs) or color temp
