### ISSUE TITLE
[New device support]: Hue Play Gradient Lightstrip 24"/27" (LCX005)

### ISSUE THREAD

**Issue by onlynow2** [Koenkk/zigbee2mqtt#20453]
### Link

https://www.philips-hue.com/de-de/p/lightstrips-hue-play-gradient-lightstrip-fur-pc/8719514434479

### Database entry

{"id":58,"type":"Router","ieeeAddr":"0x001788010b8a528d","nwkAddr":51196,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCX005","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LCX005","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230403","swBuildId":"1.104.2"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230403","swBuildId":"1.104.2","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1703984139390,"defaultSendRequestWhen":"immediate"}

### Comments

I just tried to pair the Philips Hue Play Gradient Lightstrip 24"/27".
The device (LCX005) is recognized as 'Not supported'.

Refering to Issue #20146 (which is the longer variant of this lightstrip: 32"/34", https://www.zigbee2mqtt.io/devices/929003498601.html) the device LCX006 was added.

I also checked the dev-branch, the device is still marked as 'Not supported'.

Is it possible to add this device as well?
Please let me know if there are more Informations necessary.

### External converter

```shell
I haven't tried any external converters yet, but I think all the endpoints and settings are the same as model LCX006.
```

### Color temperature range

unfortunately I received an timeout error quering the color temperature values following the guide.

**Comment by Koenkk** [comment]
Added! Will be supported in todays release.
