### ISSUE TITLE
Unable to change state of multiple devices after upgrading to v1.35.0

### ISSUE THREAD

**Issue by Atriusftw** [Koenkk/zigbee2mqtt#20478]
### What happened?

Multiple devices are unresponsive and throw errors when interacting with them. My power meter is also stuck on a constant usage and not reading new values.

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20210708

### Adapter

SONOFF Dongle-P

### Debug log

Publish 'set' 'state' to '0x90fd9ffffe86cbb0' failed: 'Error: Command 0x90fd9ffffe86cbb0/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

Publish 'set' 'state' to '0x2c1165fffe247337' failed: 'Error: Command 0x2c1165fffe247337/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

**Comment by ASNNetworks** [comment]
One of my 7 power meters was also stuck on usage and couldn't turn off/on through Z2M. Pressing the power button did work and also updated device state in Z2M. I simply took the plug out of the socket then put it back in. Worked fine again after that, no re-pair needed.

**Comment by Atriusftw** [comment]
I just ended up rolling back to 1.34.0. Too many devices failing. Among them are IKEA bulbs, SONOFF SNZB-03, Develco     EMIZB-132.

**Comment by lameritos** [comment]
i have all zigbee devices in NA state
and issues 
Error: Command 0x804b50fffe4e5db0/1 manuSpecificTuya.dataRequest({"seq":0,"dpValues":[{"dp":27,"datatype":2,"data":
failed (Data request failed with error: 'MAC channel access failure' (225))'
Sonoff P
z2m 1.35

**Comment by flowcool** [comment]
same here since this morning (updated during the night). Nothing was working anymore so I rolled back

**Comment by johnnykang** [comment]
> I just ended up rolling back to 1.34.0. Too many devices failing. Among them are IKEA bulbs, SONOFF SNZB-03, Develco EMIZB-132.

hi, how do i do the downgrade if i am using the HA add-on ?

**Comment by Atriusftw** [comment]
> > I just ended up rolling back to 1.34.0. Too many devices failing. Among them are IKEA bulbs, SONOFF SNZB-03, Develco EMIZB-132.
> 
> hi, how do i do the downgrade if i am using the HA add-on ?

You will have to restore from a backup if you created one before updating. (Settings -> System -> Backups)
