### ISSUE TITLE
[Feature request]: Notification Tab instead of Toasts

### ISSUE THREAD

**Issue by 0verEngineer** [Koenkk/zigbee2mqtt#20471]
### Is your feature request related to a problem? Please describe

The toast notifications are not a very good way to handle the notifications, a dedicated notification area and a hint that new notifications are available would do a way better job.

### Describe the solution you'd like

Remove toast notifications and add a notification area

### Describe alternatives you've considered

Nothing

### Additional context

Nothing

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
