### ISSUE TITLE
MOES MS-104CZ (3 gang) has disappeared from supported devices

### ISSUE THREAD

**Issue by jvcsw** [Koenkk/zigbee2mqtt#20474]
### What happened?

The device:

https://github.com/Koenkk/zigbee2mqtt/issues/14632

![210105595-7cf007dd-ee0f-4cfd-82ca-79acf3268764](https://github.com/Koenkk/zigbee2mqtt/assets/37216513/970f8a52-3d7f-4aa3-a464-cb392a4d7408)

now appears as 

https://www.zigbee2mqtt.io/devices/TS0003.html

![imagen](https://github.com/Koenkk/zigbee2mqtt/assets/37216513/e2368d36-b264-4581-950a-c096e45eb76d)

### What did you expect to happen?

It appeas as a Moes device as before.

This error does not appear:

https://github.com/Koenkk/zigbee2mqtt/issues/20354
 

### How to reproduce it (minimal and precise)

Update to last versión: 1.35
Check logs.
See zigbee2mqtt web UI to check the device brand.

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20211210

### Adapter

zzh

### Debug log

Failed to configure '0xXXXXXXXXXXXXXX', attempt 3 (Error: Read 0xXXXXXXXXXXXXXX/1 genOnOff(["startUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:113:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:139:25) at Configure.configure (/app/lib/extension/configure.ts:117:13))

**Comment by Koenkk** [comment]
Were you using an external converter for this device? If yes, it likely has become incompatible and needs to be upgraded.

**Comment by jvcsw** [comment]
I don't use any external converter.

Everything was working fine (for years) and now the device has changed and the indicated error appears.

**Comment by Koenkk** [comment]
Fixed now

**Comment by jvcsw** [comment]
Thanks @Koenkk
