### ISSUE TITLE
WS-EUK02 Aqara switch still not working correctly

### ISSUE THREAD

**Issue by davew21** [Koenkk/zigbee2mqtt#20480]
### What happened?

In ver 1.33 when controlling the switch from Domoticz it perofrmed correctly. In ver 1.34 this stopped working and pressing the button in Domoticz will turn on the light but the Domoticz icon stays showing off so you are unable to turn the switch off again. There have been post about Aqara issues previously and a response saying it's fixed in the dev branch so I assumed it was fixed in 1.35 but still does not function.

### What did you expect to happen?

Operation of switch to be correct as per ver 1.33

### How to reproduce it (minimal and precise)

Test with ver 1.33 then upgrade

### Zigbee2MQTT version

1.35

### Adapter firmware version

20211217

### Adapter

Electrolama zig-a-zig-ah

**Comment by daserra23** [comment]
I also have this issue, no change in switch state in the zigbee2mqtt webui when I manually toggle the switches.
