### ISSUE TITLE
1.35.0 - Bridge Connection state entity parsing undefined state key

### ISSUE THREAD

**Issue by RobertD502** [Koenkk/zigbee2mqtt#20489]
### What happened?

The Zigbee2Mqtt bridge entity `Connection state` is attempting to parse the `state` key, which is not present in the state_topic defined for this entity. As a result, Home Assistant raises two exceptions:

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:2318
First occurred: 5:21:04 PM (1 occurrences)
Last logged: 5:21:04 PM

Template variable error: 'value_json' is undefined when rendering '{{ value_json.state }}'
```

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:749
First occurred: 5:21:04 PM (1 occurrences)
Last logged: 5:21:04 PM

Error parsing value: 'value_json' is undefined (value: online, template: {{ value_json.state }})
```

As seen below, the entity is looking for the `state` key in the topic `zigbee/bridge/state`:

```json4
device:
  hw_version: zStack3x0 20200925
  identifiers:
    - zigbee2mqtt_bridge_0x00124b0021600270
  manufacturer: Zigbee2MQTT
  model: Bridge
  name: Zigbee2MQTT Bridge
  sw_version: 1.35.0
device_class: connectivity
entity_category: diagnostic
name: Connection state
object_id: zigbee2mqtt_bridge_connection_state
origin:
  name: Zigbee2MQTT
  sw_version: 1.35.0
  support_url: https://www.zigbee2mqtt.io
payload_off: offline
payload_on: online
state_topic: zigbee/bridge/state
unique_id: bridge_0x00124b0021600270_connection_state_zigbee
value_template: '{{ value_json.state }}'
platform: mqtt
```

However, Zigbee2MQTT publishes `online` / `offline` directly to the `zigbee/bridge/state` topic instead of within a `state` key at the `zigbee/bridge/state` topic. 

```
Received 5:21:04 PM
QoS: 0, Retained
Payload: online
```

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20200925

### Adapter

Electrolama

**Comment by hmmbob** [comment]
Fix could be as simple as dropping this line, as there's no value_template needed in this case.

https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.ts#L1812

**Comment by karmazinondrej** [comment]
@RobertD502 will this cause frequent disconnect of all sensors? Seems that all sensors I have are "reconnecting" frequntly, right after they are "Unavailable".

**Comment by hmmbob** [comment]
It shouldn't - the issue is in the code for the bridge specifically, not for the sensors. Looking at my own sensors, all seems fine.

**Comment by RobertD502** [comment]
^ correct. In particular this only affects the single entity within the Bridge Device that I mentioned in the title.

**Comment by mundschenk-at** [comment]
This is caused by having `legacy_availability_payload` enabled. 

@Koenkk Do you want a workaround or should legacy options be retired?

**Comment by RobertD502** [comment]
> This is caused by having `legacy_availability_payload` enabled. 
> 
> 
> 
> @Koenkk Do you want a workaround or should the legacy options be retired?

That indeed fixed it and started introducing the state key at said topic. Can't remember why I had that option enabled since it has been a few years.

**Comment by hmmbob** [comment]
Yeah, same here. Can't remember setting this actively

**Comment by Koenkk** [comment]
@mundschenk-at is there an easy way to do try/catch logic for the JSON parsing?

**Comment by mundschenk-at** [comment]
You can use conditional logic in the `value_template`, but since that is evaluated frequently, it would be preferable to handle this during the generation of the discovery topic.

**Comment by Koenkk** [comment]
Then I propose to do a check in `homeassistant.ts` to see if this option is enabled (you can skip adding test case for it, will ignore the coverage part). Would that be doable?

**Comment by mundschenk-at** [comment]
Sure.

**Comment by Koenkk** [comment]
Fixed, many thanks @mundschenk-at !

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
