### ISSUE TITLE
Error timeout Message : eWeLink ZB-SW01 since 1.35 : Failed to configure ....

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#20483]
### What happened?

Hi, since 1.35 version i have a message to my device eWeLink ZB-SW01  : (https://www.amazon.fr/gp/product/B09288V4SZ/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&th=1)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/9b2ea1d6-77f6-48f7-8788-f540913d4529)

### What did you expect to happen?

No message

### Zigbee2MQTT version

1.35

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E

### Debug log

` 2024-01-01 19:39:38Failed to configure 'Porte_Moteur_Garage', attempt 2 (Error: ConfigureReporting 0x00124b0024706702/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57186 - 1 - 4 - 6 - 7 after 10000ms) at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))`

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
