### ISSUE TITLE
TZ3000_b28wrpvx Measurement 0 when there is consumption

### ISSUE THREAD

**Issue by gedas07** [Koenkk/zigbee2mqtt#20493]
### What happened?

I have a bssed that, having a raspberry pi4 plugged in, its instantaneous consumption goes to zero, and remains at zero

### Zigbee2MQTT version

1.35.0-dev commit

### Adapter firmware version

0x26660700

### Adapter

ConBee2/RaspBee2

**Comment by nortuzar** [comment]
Same here, 
**What happened?**
After the 1.35.0 update, the consumption goes to 0

**Zigbee2MQTT version**
1.35.0-dev commit

**Adapter firmware version**
zStack3x0
ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus
Coordinator revision: 20230507

**Zigbee model**
    TS011F
**Zigbee Manufacturer**
    TZ3000_typdpbpg
**Model**
    [TS011F_plug_1](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/55258023/67937b02-f811-4534-8995-81504fa45a24)

**Comment by Koenkk** [comment]
Could you provide the debug log when power goes to 0 when it shouldn't?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by b2un0** [comment]
same for me
<img width="380" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/2155498/0c4d38ac-cc60-4d8e-a70f-99931d82f26a">
2 seconds later
<img width="365" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/2155498/525b8579-733f-4351-b1a3-a8ae3a08a8d3">


updated yesterday to 1.35 and this happened 
<img width="1246" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/2155498/a8408cab-b6ff-40d3-9f6d-66367bec30ba">

**Comment by netweaver1970** [comment]
same here, upgraded at 17:48
![image](https://github.com/Koenkk/zigbee2mqtt/assets/18028618/7d6711a1-8326-4dbb-b49b-50cc206f2fd8)

I have the issue on TS011F plugs (_TZ3000_amdymr7l) but not on the TS0121 devices.

**Comment by gedas07** [comment]
> Could you provide the debug log when power goes to 0 when it shouldn't?
> 
> See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

this?
info  2024-01-02 01:55:54: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.077,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T00:55:54.345Z","linkquality":255,"power":4,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'

info  2024-01-02 01:55:54: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T00:55:54.424Z","linkquality":255,"power":4,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":222}'
and when goes to 0 
info  2024-01-02 01:57:20: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T00:57:20.426Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":222}'

info  2024-01-02 01:57:25: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.077,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T00:57:25.421Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":222}'

**Comment by gedas07** [comment]
another 

debug 2024-01-02 11:35:01: Received Zigbee message from 'medidor_cuarto_z', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID null
info  2024-01-02 11:35:01: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.119,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T10:35:01.030Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":217}'

debug 2024-01-02 11:35:36: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":192}' from endpoint 1 with groupID null
info  2024-01-02 11:35:36: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.119,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T10:35:36.658Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":217}'

debug 2024-01-02 11:37:49: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,49]}' from endpoint 1 with groupID null
info  2024-01-02 11:37:49: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.119,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T10:37:49.240Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":217}'

debug 2024-01-02 11:37:49: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":8,"rmsCurrent":105,"rmsVoltage":218}' from endpoint 1 with groupID null
info  2024-01-02 11:37:49: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.105,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T10:37:49.315Z","linkquality":255,"power":8,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":218}'

debug 2024-01-02 11:38:24: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":192}' from endpoint 1 with groupID null
info  2024-01-02 11:38:24: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.105,"energy":0.49,"indicator_mode":"off/on","last_seen":"2024-01-02T10:38:24.437Z","linkquality":255,"power":8,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":218}'

debug 2024-01-02 11:38:56: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID null
info  2024-01-02 11:38:56: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.105,"energy":0.5,"indicator_mode":"off/on","last_seen":"2024-01-02T10:38:56.326Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":218}'
debug 2024-01-02 11:38:56: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID null
info  2024-01-02 11:38:56: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.105,"energy":0.5,"indicator_mode":"off/on","last_seen":"2024-01-02T10:38:56.369Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":218}'

**Comment by nortuzar** [comment]
Could be something related that the state of the plug is OFF? Thats weird because my desktop is up and running
```
{
    "child_lock": "UNLOCK",
    "current": 0.1,
    "energy": 1253.21,
    "indicator_mode": "on/off",
    "last_seen": "2024-01-02T15:52:13+00:00",
    "linkquality": 72,
    "power": 0,
    "power_outage_memory": "on",
    "state": "OFF",
    "update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "voltage": 226
}
```
After the update
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55258023/75e94d64-7cfd-48aa-ae57-163c30d2daff)

**Comment by Koenkk** [comment]
Does this always happen when the `current` drops to `0`? There was a change in z2m 1.35.0 which sets the power to 0 when current is 0.

**Comment by gedas07** [comment]
But my current is 0.105.
I don't know if in another version of z2m works fine , because i buyed the BSSED socket last week

**Comment by Koenkk** [comment]
Could you provide the debug log including the 20 seconds after this?

**Comment by gedas07** [comment]
> Could you provide the debug log including the 20 seconds after this?

https://github.com/Koenkk/zigbee2mqtt/issues/20493#issuecomment-1873863577

I think is this?

**Comment by nortuzar** [comment]
> Does this always happen when the `current` drops to `0`? There was a change in z2m 1.35.0 which sets the power to 0 when current is 0.

For my the current is mostly 0.1 A, but the watts stays in 0

**Comment by Koenkk** [comment]
@gedas07 

Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/ae87a0f0eda72586ba5fc9e750233510): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by gedas07** [comment]
> @gedas07
> 
> Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/ae87a0f0eda72586ba5fc9e750233510):
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if issue is fixed

ok thanks, I'm trying it, but how do I know it has taken the file?
Additionally, my socket is TZ3000_b28wrpvx and I don't see it in the ext_converter.js file, is this normal? Will it work the same?
And finally the photo doesn't match.

Thanks again

**Comment by Koenkk** [comment]
I updated the [converter](https://gist.github.com/Koenkk/ae87a0f0eda72586ba5fc9e750233510), to check if it is loaded correctly, go to the z2m frontend -> device and check the the description ends with `CUSTOM`.

**Comment by gedas07** [comment]
Yes , correct , i see CUSTOM
But in the ext_converter.js not see TZ3000_b28wrpvx is normal ? will it work the same?

**Comment by Koenkk** [comment]
> Yes , correct , i see CUSTOM
> 
> But in the ext_converter.js not see TZ3000_b28wrpvx is normal ? will it work the same? 
> 
> Thanks a lot 

yes thats normal, does it work OK  now?

**Comment by gedas07** [comment]
> > Yes , correct , i see CUSTOM
> > But in the ext_converter.js not see TZ3000_b28wrpvx is normal ? will it work the same?
> > Thanks a lot
> 
> yes thats normal, does it work OK now?

For the moment works perfectly , thanks a lot 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/caf380fb-51d4-4a6e-850e-f3342b8d1a4d)
And it,s possible to change the image ?
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/4e9c5fde-6b30-421e-b3e2-25a0bc1aaa91)

**Comment by gedas07** [comment]
Hello, 
yesterday around 1:00 p.m. when I copied the ext_converter.js file, I reinstalled zigbee2mqtt with version 1.35.0, and a raspberry is always installed in that socket, and this morning it has returned to 0 w sometimes, I attach photos.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/e013cfca-f659-4071-8830-c094a9aaa55a)



![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/848c2d69-1e89-4777-973d-db4e7d3fad46)

**Comment by nortuzar** [comment]
I load the converter an it didnt work for me
Zigbee Model:  TS011F
Zigbee Manufacturer: _TZ3000_typdpbpg
Description:  Smart plug (with power monitoring) CUSTOM

**State**
```
{
    "child_lock": "UNLOCK",
    "current": 0.09,
    "energy": 1254.5,
    "indicator_mode": "on/off",
    "last_seen": "2024-01-04T12:29:49+00:00",
    "linkquality": 69,
    "power": 0,
    "power_outage_memory": "on",
    "state": "ON",
    "update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "voltage": 225,
    "update_available": null
}
```

I dont know if its relevant, but when im inside the device details, a pop up appears with some kind of error
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55258023/4a7b0cc6-71ee-4108-8732-3a287db9e203)

**Comment by Koenkk** [comment]
@gedas07 

> raspberry is always installed in that socket, and this morning it has returned to 0 w sometimes, I attach photos.

please provide the log of that

@nortuzar your issue should be fixed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by nortuzar** [comment]
> @gedas07
> 
> > raspberry is always installed in that socket, and this morning it has returned to 0 w sometimes, I attach photos.
> 
> please provide the log of that
> 
> @nortuzar your issue should be fixed now.
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Awesome, will be waiting. When we can expect this on the main branch? (because i don't want to mess anything switching from branch lol)

Thank you very much for your nice and quick help

**Comment by gedas07** [comment]
> @gedas07
> 
> > raspberry is always installed in that socket, and this morning it has returned to 0 w sometimes, I attach photos.
> 
> please provide the log of that
> 
Sorry , 
But i don´t found the log in my folder at 4am , but today about 16:40 , another time , here the log
info  2024-01-04 16:48:57: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:48:57.657Z","linkquality":255,"power":6,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'

info  2024-01-04 16:49:03: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:48:57.657Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'


info  2024-01-04 16:49:27: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:49:27.317Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'

info  2024-01-04 16:49:52: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:49:27.317Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'

info  2024-01-04 16:52:07: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:52:07.189Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'

info  2024-01-04 16:53:19: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:53:19.023Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":221}'
info  2024-01-04 16:53:19: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:53:19.090Z","linkquality":255,"power":7,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":222}'

info  2024-01-04 16:53:20: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":1.37,"indicator_mode":"off/on","last_seen":"2024-01-04T15:53:20.691Z","linkquality":255,"power":7,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":222}'

I don´t Know how i find my debug log in my folder persitent docker 

I think that is enabled, i put this in my stack , but i don´t know if is correct

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/e2327c9d-a639-4100-add1-e9a2c6a7e5cf)

**Comment by Koenkk** [comment]
@gedas07  Look into the z2m data/log folder

**Comment by gedas07** [comment]
> @gedas07 Look into the z2m data/log folder
I have these logs, but in none of them do I get debug, only info
Do I have to do something else to make it come out?
And can the old ones be deleted?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/a96c45f9-653f-417f-bcc2-d193ed131d15)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/56a2af51-5617-49c3-aea8-37870d0a2276)

**Comment by Koenkk** [comment]
See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by gedas07** [comment]
Every day , again at 0

It is not a problem, but it is a wall outlet where I have to turn it off if it is more than 5 minutes without power.
It is a place where I charge cell phones, laptops, etc., and where I plug in the test raspberrys.
That's why it turns off when the consumption is 0, but sometimes I leave the pi on and it turns it off when giving that false consumption

![image](https://github.com/Koenkk/zigbee2mqtt/assets/42668878/8ebf56f5-cf4f-42bb-90f7-c67323befffb)
here the log 
debug 2024-01-07 07:47:20: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":192}' from endpoint 1 with groupID null
info  2024-01-07 07:47:20: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":2.11,"indicator_mode":"off/on","last_seen":"2024-01-07T06:47:20.704Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":220}'

debug 2024-01-07 07:49:22: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID null
info  2024-01-07 07:49:22: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":2.11,"indicator_mode":"off/on","last_seen":"2024-01-07T06:49:22.517Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":220}'

debug 2024-01-07 07:49:27: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":91}' from endpoint 1 with groupID null
info  2024-01-07 07:49:27: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":2.11,"indicator_mode":"off/on","last_seen":"2024-01-07T06:49:27.510Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":220}'


debug 2024-01-07 07:50:09: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,211]}' from endpoint 1 with groupID null
info  2024-01-07 07:50:09: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.091,"energy":2.11,"indicator_mode":"off/on","last_seen":"2024-01-07T06:50:09.919Z","linkquality":255,"power":0,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":220}'
debug 2024-01-07 07:50:09: Received Zigbee message from 'medidor_cuarto_z', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7,"rmsCurrent":84,"rmsVoltage":220}' from endpoint 1 with groupID null
info  2024-01-07 07:50:10: MQTT publish: topic 'zigbee2mqtt/medidor_cuarto_z', payload '{"child_lock":"UNLOCK","current":0.084,"energy":2.11,"indicator_mode":"off/on","last_seen":"2024-01-07T06:50:09.983Z","linkquality":255,"power":7,"power_outage_memory":"restore","power_phase_c":null,"state":"ON","update":{"installed_version":192,"latest_version":192,"state":"idle"},"update_available":false,"voltage":220}'
