### ISSUE TITLE
Aqara Zigbee 3.0 LED strip T1 no RGB-colors configurable

### ISSUE THREAD

**Issue by CrazyThunderbird** [Koenkk/zigbee2mqtt#20497]
### What happened?

I don't know exactly when it happened but i assum either the last z2m update or the ota broke something.
Because since then:
I'm no longer able to define any RGB colors!
I can just switch it on/off and define the white color temperature and brightness.

What did i do:
Completely removed the device from z2m and completely rebootet the system and then paired it again, didn't work
Unpowered it for approx an hour, also didn't fix anything
I switched to z2m edge for testing, also bummer :(

I didn't rename it was just repairing it for the 10th time or so
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/109760390/19c29af9-faaa-42f2-8c0d-ff1594614cdd)
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/109760390/92a05c06-9d94-4811-88a8-407e41c98dd5)

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus,Zigbee Gateway TI CC2652P + CP2102N

**Comment by KevinBalkoski** [comment]
Best I can tell, it may have been from these changes: https://github.com/Koenkk/zigbee-herdsman-converters/compare/v15.131.0...v18.3.0#diff-413b42ed3dc2bb32fbcfbc4db8b0242f76ff72d0e313986424e2f8a319baeb2bL979-L1060

zigbee-herdsman-converters got upgraded from 15.131.0 to 18.3.0 for zigbee2mqtt 1.35.0

**Comment by Koenkk** [comment]
Will be fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6812

**Comment by CrazyThunderbird** [comment]
When is the fix expected to drop? :)

Glad for this fast response

**Comment by Koenkk** [comment]
Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Additionally I will probably make a hotfix release somewhere in the coming week.

**Comment by CrazyThunderbird** [comment]
oh i'l give it a try in "edge" then and will report back :)

**Comment by CrazyThunderbird** [comment]
Tested the Edge branch:
It's fixed
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/109760390/24b17011-75a5-46f4-b976-41ab75e04133)

**Comment by Ot4eVash** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/115181275/069aefaa-5a14-4f7b-9002-9ce3b85ad01c)

I have the Edge. But it's not help((

**Comment by cablesandcoffee** [comment]
Any news on this? I have the same problem. Still does not work running z2m 1.39.1

**Comment by MadSpindel** [comment]
How do you put the LED Strip in pairing mode?
