### ISSUE TITLE
Coordinator node won't stop dancing on map :D

### ISSUE THREAD

**Issue by Daniel15** [Koenkk/zigbee2mqtt#20491]
### What happened?

It's dancing by itself 😆 

https://github.com/Koenkk/zigbee2mqtt/assets/91933/004857e2-9c15-4644-a05d-ff0b9a4dc463

It stops moving if I grab it, but grabbing it is the hard part.

### What did you expect to happen?

Peaceful map

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20221226

### Adapter

SMLIGHT SLZB-06

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
