### ISSUE TITLE
The Map display does not work reliably

### ISSUE THREAD

**Issue by merlinpimpim** [Koenkk/zigbee2mqtt#20514]
### What happened?

The map display will only operate close to a Z2M start/restart.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/113300765/30330dc4-9143-42c2-9948-8dbbc4fcb55e)

When Z2M has been running for some time, the map display enters an infinite loop.
You can restart Z2M to display the map again (but this will not last).
![image](https://github.com/Koenkk/zigbee2mqtt/assets/113300765/bf4a7fe6-c94e-45a7-9e93-bf3b4e488246)

### What did you expect to happen?

A Map display that works reliably at all times.

### How to reproduce it (minimal and precise)

Already explained above

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

 7.3.1.0 build 0

### Adapter

Skyconnect multi pan

**Comment by sdotter** [comment]
My experience is same but also think its got to do something with #20519
