### ISSUE TITLE
Makegood MG-AUZG01 Power Monitoring Sensor Entity Missing since v1.35.0

### ISSUE THREAD

**Issue by isngofoz** [Koenkk/zigbee2mqtt#20531]
### What happened?

I have 2x Makegood MG-AUZG01 power points, Zigbee Model TS011F, Zigbee Manufacturer _TZ3000_dd8wwzcy.  After the recent v1.35.0 update, the power sensor entity went missing. It seems like it is no longer available. There are other Zigbee devices still providing power monitoring sensor readings. 

### What did you expect to happen?

It has been working well before the update.

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle-P

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
