### ISSUE TITLE
[suggestion] Official Docker Node Images

### ISSUE THREAD

**Issue by RaymondMouthaan** [Koenkk/zigbee2mqtt#2054]
@Koenkk, you might wanna consider to use the official Node images as base, they are available for `arm32v6`, `arm32v7`, `arm64v8` and `amd64`, alpine based and for different versions of Node.

for example:
- `arm32v6/node:10-alpine`
- `arm32v7/node:10-alpine`
- `arm64v8/node:10-alpine`
- `amd64/node:10-alpine`

[ref](https://hub.docker.com/_/node?tab=tags&page=1&name=alpine)

**Comment by Koenkk** [comment]
Done!
