### ISSUE TITLE
Future incompatibility with HA core  2024.2.0

### ISSUE THREAD

**Issue by robitsrl** [Koenkk/zigbee2mqtt#20558]
### What happened?

I have several device using Zigbee2MQTT that are using Entity category `config`.
this will be deprecated in the future HA core 2024.2.0 as read in the HA logs:

Entity category `config` is invalid for sensors, ignoring. This stops working from HA Core 2024.2.0

### What did you expect to happen?

NEW RELEASE FOR ZIGBBETOMQTT

### Zigbee2MQTT version

1.35.0-1

### Adapter firmware version

N/A

### Adapter

Silicon Labs Multiprotocol ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

**Comment by Koenkk** [comment]
For what sensor do you get these/

**Comment by robitsrl** [comment]
Aquara Xiaomi WXKG15LM
SONOFF SNZB-06P
SONOFF SNZB-06P

**Comment by Koenkk** [comment]
What are the errors in the HA log?

**Comment by bernardesarthur** [comment]
From what I see, this error is the HA log:

`Entity category config is invalid for sensors, ignoring. This stops working from HA Core 2024.2.0
`

**Comment by robitsrl** [comment]
Yes I confirm the error is:

Entity category config is invalid for sensors, ignoring. This stops working from HA Core 2024.2.0 

I wrote to MQTT developer and they told me to use logger component to find out what sensor.
I do not install logger for now but i have download MQTT diagnostic and post it to MQTT developer and they confirm that the cause come from those sensor integrations

**Comment by bckthomas** [comment]
Hi 2024.2.0 is out and I have sensors with Entity category `config` :

- Ikea TRADFRI control outlet (E1603/E1702/E1708)
- Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)
- MHCOZY 4 channel relay (TYWB 4ch-RF)
