### ISSUE TITLE
Add Philips LWA031

### ISSUE THREAD

**Issue by doc305** [Koenkk/zigbee2mqtt#20561]
### Link

https://www.philips-hue.com/de-de/p/hue-white-e27---smarte-lampe-a67---1600/8719514343320

### Database entry

?

### Comments

The Device is similar to LWA009 that is supported well. Can you add the LWA031 please.

### External defintion

```shell
?
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
