### ISSUE TITLE
frient EMIZB-141 divisor

### ISSUE THREAD

**Issue by Dommoe** [Koenkk/zigbee2mqtt#20563]
### What happened?

Hello everyone,

I buy a frient EMIZB-141.
So far, it works on my electricity meter as well. I only have the problem that a standard electricity meter counts 1000 pulses. But my electricity meter has 10000 pulses. I've read that you have to change the divisor. Unfortunately, I can't find this in the settings. When I try to change the manual under the developer console, I get the error message that the divisor can only be read. Can I change the divisor manually?

Sorry for my English 
![Screenshot 2024-01-04 105131](https://github.com/Koenkk/zigbee2mqtt/assets/48207920/db428b7e-f1d1-4293-bf42-7b6333237897)

Thank you in advance

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

 zStack3x0

**Comment by joschaschultze** [comment]
Its under "details" the "Pulse Configuration". You have to change this value to 10.000.

**Comment by Dommoe** [comment]
If I set this value to 10000, then I get values around 400000 watts. It also says that it is a percentage value. I have now entered -90, then the values seem to be approximately correct. 

![IMG_1821](https://github.com/Koenkk/zigbee2mqtt/assets/48207920/541a8a12-78e5-48db-ab6d-1a46682e477c)

The energy sensor is also not working properly. But I don't know exactly why. If I change there in the settings, it also counts too fast. 

![IMG_1820](https://github.com/Koenkk/zigbee2mqtt/assets/48207920/36153b4a-447a-4896-8caa-dd05d985b0e8)

**Comment by MaxD16** [comment]
Hello,

I have the same exact issue. I can not find the option to change pulses to 10.000 pulses/kW.

**Comment by FrankTolksdorf** [comment]
have the same exact issue. I can not find the option to change pulses to 10.000 pulses/kW.

**Comment by thedotor** [comment]
I have added this device today, running Zigbee2MQTT 1.35.1-1 and missing the "Pulse Configuration" mine needs to be 4000 pulses/kW.
Thank you
