### ISSUE TITLE
No datapoint for preset on 1.35.0 for  thermostat GTZ06 (_TZE200_z1tyspqw)

### ISSUE THREAD

**Issue by pawol** [Koenkk/zigbee2mqtt#20598]
### What happened?

Cannot select presets when 1.35 installed. on 1.34 works okay

### How to reproduce it (minimal and precise)

just update 1.34 --1.35

### Zigbee2MQTT version

1.35.0 

### Adapter firmware version

20230507

### Adapter

egony cc2652p

### Debug log

debug 2024-01-05 21:31:50Received MQTT message on 'zigbee2mqtt/termostat_w_kuchni/set' with data '{"preset":"off"}'
debug 2024-01-05 21:31:50Publishing 'set' 'preset' to 'termostat_w_kuchni'
error 2024-01-05 21:31:50Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''
debug 2024-01-05 21:31:51Error: No datapoint defined for 'preset' at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:1108:27) at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52) at EventEmitter.emit (node:events:526:35) at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22) at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27) at WebSocket.emit (node:events:514:28) at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:514:28) at /opt/zigbee2mqtt/node_modules/ws/lib/receiver.js:608:16
info 2024-01-05 21:31:51MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''","meta":{"friendly_name":"termostat_w_kuchni"},"type":"zigbee_publish_error"}'
debug 2024-01-05 21:31:58Received MQTT message on 'zigbee2mqtt/termostat_w_kuchni/set' with data '{"preset":"auto"}'
debug 2024-01-05 21:31:58Publishing 'set' 'preset' to 'termostat_w_kuchni'
error 2024-01-05 21:31:58Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''
debug 2024-01-05 21:31:58Error: No datapoint defined for 'preset' at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:1108:27) at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52) at EventEmitter.emit (node:events:526:35) at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22) at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27) at WebSocket.emit (node:events:514:28) at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:514:28) at /opt/zigbee2mqtt/node_modules/ws/lib/receiver.js:608:16
info 2024-01-05 21:31:58MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''","meta":{"friendly_name":"termostat_w_kuchni"},"type":"zigbee_publish_error"}'

**Comment by Koenkk** [comment]
Already fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6819

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
