### ISSUE TITLE
LELLKI WP33-EU/WP34-EU: Single switch toggles all switches

### ISSUE THREAD

**Issue by MaxMSchneider** [Koenkk/zigbee2mqtt#20590]
### What happened?

LELLKI WP33-EU/WP34-EU shows same behavior than WP30-EU in issue #13843 

### What did you expect to happen?

Single switch does not toggle others

### How to reproduce it (minimal and precise)

Toggle any switch via Z2M frontend

### Zigbee2MQTT version

 1.35.0-dev commit: b17c22b

### Adapter firmware version

20210708

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Info 2024-01-05 14:03:32MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:34MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:35MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:35MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"ON"}'
Info 2024-01-05 14:03:36MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF"}'
Info 2024-01-05 14:03:38MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":75,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF"}'
Info 2024-01-05 14:03:38MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF"}'
Info 2024-01-05 14:03:38MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"ON","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF"}'
Info 2024-01-05 14:03:39MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"OFF","state_l5":"OFF"}'
Info 2024-01-05 14:03:39MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":75,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"OFF"}'
Info 2024-01-05 14:03:39MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"ON","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:45MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:45MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"ON","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:45MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"ON","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:45MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"ON","state_l5":"ON"}'
Info 2024-01-05 14:03:46MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"ON"}'
Info 2024-01-05 14:03:46MQTT publish: topic 'zigbee2mqtt/Vitrine_Multi', payload '{"linkquality":78,"power_on_behavior":"off","power_on_behavior_l1":"off","power_on_behavior_l2":"previous","power_on_behavior_l3":"previous","power_on_behavior_l4":"previous","power_on_behavior_l5":"previous","state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF","state_l5":"OFF"}'

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by MaxMSchneider** [comment]
> Fixed!
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Thanks! Much appreciate your work!
