### ISSUE TITLE
Unsupported attribute : ZB-SW02 and some timeouts

### ISSUE THREAD

**Issue by radek-kafka** [Koenkk/zigbee2mqtt#20600]
### What happened?

Hi,

I'm facing some troubles with 2ch module ZB-SW02. When trying to switch power_on_ behavior it is reporting error: unsupported attribute

Zigbee2MQTT:error 2024-01-05 22:40:18: Publish 'set' 'power_on_behavior' to 'Rele2CH' failed: 'Error: Write 0x00124b002459c4f4/1 genOnOff({"startUpOnOff":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

Also when restarting Z2M it is telling to me: 
 Zigbee2MQTT:error 2024-01-05 22:35:41: Failed to configure 'Rele2CH', attempt 2 (Error: ConfigureReporting 0x00124b002459c4f4/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14647 - 1 - 43 - 6 - 7 after 10000ms)

### What did you expect to happen?

Correct switching of the power_on_behavior attribute

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

SONOFF USBDONGLE PLUS

**Comment by vampywiz17** [comment]
I dont know it connect this problem or not, but i get this, if try to configure this device:

```
Error 2024-01-07 17:12:23Failed to configure '0x00124b00246ec8f6', attempt 4 (Error: ConfigureReporting 0x00124b00246ec8f6/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 55633 - 1 - 102 - 6 - 7 after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
```

```
Info 2024-01-07 17:12:23MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x00124b00246ec8f6"},"error":"Failed to configure (ConfigureReporting 0x00124b00246ec8f6/1 genOnOff([{\"minimumReportInterval\":0,\"maximumReportInterval\":65000,\"reportableChange\":1,\"attribute\":\"onOff\"}], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 55633 - 1 - 102 - 6 - 7 after 10000ms))","status":"error","transaction":"gkmkt-2"}'
```

it works regardless.
