### ISSUE TITLE
Support Gecko SDK v4.4.0

### ISSUE THREAD

**Issue by NewsGuyTor** [Koenkk/zigbee2mqtt#20602]
### What happened?

There were a [lot of Z2M breakage today](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/555) because Silicon Labs Multiprotocol 2.4.0 were released, and used Gecko SDK v4.4.0, which Z2M apparently doesn't support.

More info here:  
https://github.com/home-assistant/addons/issues/3386

@puddly:
`This is fixed by https://github.com/home-assistant/addons/pull/3388 but will break once the addon is updated once more. Until Z2M supports the latest SDK, you shouldn't update.`

Would be cool if it could be supported so the Silicon Labs Multiprotocol addon doesn't have to be rolled/held back to outdated versions.

### Zigbee2MQTT version

1.35.0 commit: unknown

### Adapter firmware version

7.3.1.0 build 0

### Adapter

SkyConnect

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee-herdsman/issues/854
