### ISSUE TITLE
New IKEA light bulb "TRADFRI bulb E27 WW 806lm" has no support

### ISSUE THREAD

**Issue by asimmetrico** [Koenkk/zigbee2mqtt#2061]
Hello, I purchased the new IKEA HS1919 (LED1836G9) light bulb. I successfully paired the bulb to Zigbee2mqtt but I got the following warning:

  zigbee2mqtt:warn 10/2/2019, 12:14:56 AM Device with modelID 'TRADFRI bulb E27 WW 806lm' is not supported.
  zigbee2mqtt:warn 10/2/2019, 12:14:56 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

I followed the proposed link but I couldn't find the "node_modules/zigbee-shepherd-converters/devices.js" file and probably it's over my skill.
Can you help me to add this light bulb? Probably will be useful for other users too.

This bulb has brightness control only, no spectrum.

Thanks for your help

Al

# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Koenkk** [comment]
This device is already supported in the dev branch (https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/devices.js#L830).

Either switch to the dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html) or wait for the next zigbee2mqtt release.
