### ISSUE TITLE
Notification Exception unknown

### ISSUE THREAD

**Issue by devildant** [Koenkk/zigbee2mqtt#20621]
### What happened?

hello, 
randomly I have exception notifications in zigbee2mqtt, but I don't know which device is affected

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8700106/b69e4c2c-c59b-43cf-9cb2-329d401bc9f3)

### Zigbee2MQTT version

 1.35.0

### Adapter firmware version

20210708

### Adapter

sonoff P

### Debug log

info  2024-01-06 20:22:15: MQTT publish: topic 'zigbee2mqtt/Prise ..cran 2', payload '{"child_lock":"UNLOCK","current":0.17,"energy":10.59,"indicator_mode":"off","linkquality":168,"power":0,"power_outage_memory":"restore","state":"OFF","
error 2024-01-06 20:22:15: Exception while calling fromZigbee converter: Cannot set properties of undefined (setting 'power')}
debug 2024-01-06 20:22:16: TypeError: Cannot set properties of undefined (setting 'power')
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:477:29)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:147:35)
debug 2024-01-06 20:22:16: Received Zigbee message from 'Prise ..cran 1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":0}' from endpoint 1 with groupID 0
debug 2024-01-06 20:22:16: Received Zigbee message from 'Prise ..cran 1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0

**Comment by devildant** [comment]
the device mentioned before and after in the log is a connected socket from the brand "nous" so nothing to do with tuya

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8700106/147c32a7-b78b-4bd3-a493-52144ceb3299)

**Comment by devildant** [comment]
it seems to come from this device

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8700106/395ca532-296b-4a32-bb72-84ba71f00eb7)

**Comment by Koenkk** [comment]
Will be fixed in the next release.
