### ISSUE TITLE
Still No datapoint defined for 'preset' on the latest 1.35.0 dev  (commit: 3d8f0fc3) for thermostat GTZ06 (_TZE200_z1tyspqw)

### ISSUE THREAD

**Issue by pawol** [Koenkk/zigbee2mqtt#20622]
### What happened?

Still No datapoint defined for 'preset' on the latest 1.35.0 dev  (commit: 3d8f0fc3) for thermostat GTZ06 (_TZE200_z1tyspqw)

### What did you expect to happen?

In theory it should be now fixed by https://github.com/Koenkk/zigbee2mqtt/issues/20598#event-11407569232

### How to reproduce it (minimal and precise)

just update 1.34.0 onto any 1.35.0 (dev or master)

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

egony cc2652p

### Debug log

debug 2024-01-06 21:12:39Received MQTT message on 'zigbee2mqtt/termostat_w_kuchni/set' with data '{"preset":"off"}'
debug 2024-01-06 21:12:39Publishing 'set' 'preset' to 'termostat_w_kuchni'
error 2024-01-06 21:12:39Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''
debug 2024-01-06 21:12:39Error: No datapoint defined for 'preset' at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:1108:27) at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52) at EventEmitter.emit (node:events:526:35) at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22) at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27) at WebSocket.emit (node:events:514:28) at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:514:28) at /opt/zigbee2mqtt/node_modules/ws/lib/receiver.js:608:16
info 2024-01-06 21:12:39MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'preset' to 'termostat_w_kuchni' failed: 'Error: No datapoint defined for 'preset''","meta":{"friendly_name":"termostat_w_kuchni"},"type":"zigbee_publish_error"}'
debug 2024-01-06 21:14:38Received Zigbee message from 'termostat_w_pokoju', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,195],"type":"Buffer"},"datatype":2,"dp":3}],"seq":62720}' from endpoint 1 with groupID 0
info 2024-01-06 21:14:38MQTT publish: topic 'zigbee2mqtt/termostat_w_pokoju', payload '{"alarm_switch":null,"battery":98,"boost_heating":"OFF","boost_time":null,"child_lock":"LOCK","current_heating_setpoint":20,"last_seen":"2024-01-06T20:14:38.518Z","linkquality":58,"local_temperature":19.5,"local_temperature_calibration":-2.5,"max_temperature":22,"min_temperature":15,"position":11,"preset":"auto","running_state":"heat","schedule_friday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_monday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_saturday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_sunday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_thursday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_tuesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_wednesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","system_mode":"auto","window":"CLOSE","window_detection":"ON"}'
debug 2024-01-06 21:14:38Received Zigbee message from 'termostat_w_pokoju', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,120],"type":"Buffer"},"datatype":2,"dp":102}],"seq":62976}' from endpoint 1 with groupID 0
info 2024-01-06 21:14:38MQTT publish: topic 'zigbee2mqtt/termostat_w_pokoju', payload '{"alarm_switch":null,"battery":98,"boost_heating":"OFF","boost_time":null,"child_lock":"LOCK","current_heating_setpoint":20,"last_seen":"2024-01-06T20:14:38.637Z","linkquality":58,"local_temperature":19.5,"local_temperature_calibration":-2.5,"max_temperature":22,"min_temperature":15,"position":12,"preset":"auto","running_state":"heat","schedule_friday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_monday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_saturday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_sunday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_thursday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_tuesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_wednesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","system_mode":"auto","window":"CLOSE","window_detection":"ON"}'
debug 2024-01-06 21:15:35Received Zigbee message from 'termostat_w_kuchni', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,197],"type":"Buffer"},"datatype":2,"dp":3}],"seq":11264}' from endpoint 1 with groupID 0
info 2024-01-06 21:15:35MQTT publish: topic 'zigbee2mqtt/termostat_w_kuchni', payload '{"alarm_switch":null,"battery":100,"boost_heating":"OFF","boost_time":null,"child_lock":"LOCK","current_heating_setpoint":20,"last_seen":"2024-01-06T20:15:35.532Z","linkquality":54,"local_temperature":19.7,"local_temperature_calibration":-2.4,"max_temperature":22,"min_temperature":15,"position":0,"preset":"auto","running_state":"idle","schedule_friday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_monday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_saturday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_sunday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_thursday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_tuesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","schedule_wednesday":"04:00/21.0 12:00/21.0 16:00/21.0 20:00/20.0","system_mode":"auto","window":"CLOSE","window_detection":"ON"}'
debug 2024-01-06 21:17:04Saving state to file /opt/zigbee2mqtt/data/state.json
debug 2024-01-06 21:17:12Received Zigbee message from 'termostat_w_pokoju', type 'commandMcuSyncTime', cluster 'manuSpec

**Comment by Koenkk** [comment]
The dev branch you are using is too old, update to the latest.
