### ISSUE TITLE
Last seen column is N\A

### ISSUE THREAD

**Issue by almirus** [Koenkk/zigbee2mqtt#20638]
### What happened?

When you first enter the interface, the LAST SEEN column shows N/A, but if you switch to any device and then back, the values are displayed correctly. 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16898685/4c3ebeff-e695-46ce-b543-02ded43cb869)

At this time, spam messages 'Unknown last_seen type undefined' in the console.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16898685/700445d6-75e3-4104-b0bb-3f21470733e9)

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

egony Stick V4

**Comment by almirus** [comment]
This occurs after switching to a specific device and back.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/16898685/ddf7b221-f4be-4b6e-9b3e-f022edf2a96c)

**Comment by Koenkk** [comment]
Should be fixed in z2m 1.35.1
