### ISSUE TITLE
Cannot start Zigbee2mqtt

### ISSUE THREAD

**Issue by MarcE85** [Koenkk/zigbee2mqtt#2064]
zigbee2mqtt version: 1.6.0.0
CC2531 firmware version: latest

Since my last update I'm not able to start the zigbee2mqtt service.
I already tried to replug the stick and also pressed the reset button, but nothing worked.

DEBUG log:
[debug start error log](https://pastebin.com/92dGG9m7)

Regards Marc

**Comment by way2many** [comment]
Same here on latest dev docker (which changed name?)

**Comment by Koenkk** [comment]
Please check https://www.zigbee2mqtt.io/information/zigbee2mqtt_fails_to_start.html

If that doesn't work try reflashing the stick.

**Comment by FouFouCode** [comment]
I've got the same crash, checked https://www.zigbee2mqtt.io/information/zigbee2mqtt_fails_to_start.html, reflashed twice the stick, unplugged the device, sometimes pushed the nearest button close to USB port, but still not able to start zigbee2mqtt with a CC2531.
Logs can be found at https://pastebin.com/Lp8JZdAc
Any help will be appreciated ;-)
Regards,

**Comment by Koenkk** [comment]
For the CC2531, you shouldn't set "rtscts":true in the `configuration.yaml`.

**Comment by FouFouCode** [comment]
It's already set to false. Here's my configuration.yaml:
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: xxx
  password: xxx
serial:
  port: /dev/ttyACM0
advanced:
  rtscts: false

**Comment by FouFouCode** [comment]
I found the (stupid) issue: I did receive a CC2540 instead of a CC2531. And, you know what: this is not working as expected...
My mistake.
Sorry for the noise!

**Comment by Koenkk** [comment]
Thanks, then I will close this as the OP didn't respond.
