### ISSUE TITLE
Error update 1.35.1 don't start :  Error: Cannot find module './dist/util/settings

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#20640]
### Is your feature request related to a problem? Please describe

I test this and don't work :  find : [#19318](https://github.com/Koenkk/zigbee2mqtt/issues/19318)
git pull
npm run build

### Describe the solution you'd like

update to 1.35.1

### Describe alternatives you've considered

![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/df4f98a6-63e6-48db-ba1b-5a49aac0bfeb)

### Additional context

`rrypi npm[2268596]: > node index.js
janv. 07 15:04:55 raspberrypi npm[2268642]: Error: Cannot find module './dist/util/settings'
janv. 07 15:04:55 raspberrypi npm[2268642]: Require stack:
janv. 07 15:04:55 raspberrypi npm[2268642]: - /opt/zigbee2mqtt/index.js
janv. 07 15:04:55 raspberrypi npm[2268642]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
janv. 07 15:04:55 raspberrypi npm[2268642]:     at Function.Module._load (node:internal/modules/cjs/loader:922:27)
janv. 07 15:04:55 raspberrypi npm[2268642]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
janv. 07 15:04:55 raspberrypi npm[2268642]:     at require (node:internal/modules/cjs/helpers:121:18)
janv. 07 15:04:55 raspberrypi npm[2268642]:     at start (/opt/zigbee2mqtt/index.js:90:22)
janv. 07 15:04:55 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
janv. 07 15:04:55 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
janv. 07 15:04:55 raspberrypi systemd[1]: zigbee2mqtt.service: Consumed 1.751s CPU time.
`

**Comment by Koenkk** [comment]
Try executing `rm -rf dist tsconfig.tsbuildinfo && npm run build`

**Comment by kwetnico** [comment]
> rm -rf dist tsconfig.tsbuildinfo && npm run build

hi, it's better and ok 👍 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/029cfe34-1855-43f4-90a9-a76e99ea4d2f)
1.35.1 :
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/ed4c922c-e8ee-4b5b-b792-1b2a3a672490)

**Comment by kwetnico** [comment]
Solution :
![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/cea46818-eeb5-4968-9408-517b6830e50b)
