### ISSUE TITLE
No light entity created for device Philips 9290018216A

### ISSUE THREAD

**Issue by nickagian** [Koenkk/zigbee2mqtt#20656]
### What happened?

Just today I updated my zigbee2mqtt Home Assistant addon to version 1.35, because I bought some Hue bulbs (Philips 9290018216A) I want to be able to use.

Once they have correctly joined my network, I can, through the zigbee2mqtt frontend, get their reports and interact with them through the exposed properties, such as turn them on/off and change their brightness.

However, when I go to the device created in HA, there is no such thing as light created, where I could write their state or brightness. Only thing I can do is change their reset state.

I'm using HA core 2023.3.6, so pretty old. Could that have an influence on things? Otherwise, what could I do to correct this behaviour?

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20210120

### Adapter

Cc2531 based

**Comment by Koenkk** [comment]
You need at least HA 2023.8.0
