### ISSUE TITLE
IKEA Tradfri Motion Sensor

### ISSUE THREAD

**Issue by maku79** [Koenkk/zigbee2mqtt#2065]
Hi, i tried to pair the IKEA Tradfri Motion Sensor Type E1745, with ioBroker zigbee adapter
i got following error message in the log:

 new dev 0x000d6ffffe4afa67 46185 TRADFRI motion sensor
zigbee.0 | 3 | error | Device 000d6ffffe4afa67 "TRADFRI motion sensor" not described in statesMapping.

**Comment by Koenkk** [comment]
This is the zigbee2mqtt issue tracker, please use the iobroker issue tracker for iobroker issues.
