### ISSUE TITLE
Unable to Configure/Reconfigure for Hej devices

### ISSUE THREAD

**Issue by star114** [Koenkk/zigbee2mqtt#20666]
### What happened?

all hej switch devices. ([zigbee2mqtt.io/supported-devices/#v=Hej](https://www.zigbee2mqtt.io/supported-devices/#v=Hej))

GLSK3ZB-1711
GLSK3ZB-1712
GLSK3ZB-1713
GLSK3ZB-1714
GLSK3ZB-1715
GLSK3ZB-1716

trying to Configure/reconfigure the device, get an error.
see log:
Failed to configure 'hej_3gang_library_light', attempt 7 (Error: ConfigureReporting 0x00158d00032e8503/2 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:665:22) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:55:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:111:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25) at Configure.configure (/app/lib/extension/configure.ts:120:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17))

### What did you expect to happen?

configure/reconfigure without error

### How to reproduce it (minimal and precise)

try to pair the device
or
click reconfigure button from frontend for each paired devices

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

 20210319

### Adapter

custom (zStack3x0)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
