### ISSUE TITLE
Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: Cluster with key '65280' does not exist)

### ISSUE THREAD

**Issue by Flagun** [Koenkk/zigbee2mqtt#2067]
# Bug Report
## What happened
After updating the hassio addon to 1.6.0 from 1.5.1 the addon doesn't start. An error occures: Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: Cluster with key '65280' does not exist). I installed the zigbee2mqtt-edge version of the addon and everything came to normal. However I would like to be on on non test branch of the addon :) 
## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version:

**Comment by Koenkk** [comment]
Great that it works with the edge add-on; I understand that you want to be on a non test branch however no modifications are going to be made to the legacy zigbee-shepherd (in zigbee2mqtt 1.6.0); the release will be zigbee2mqtt 1.7.0 and contain zigbee-herdsman (see #1888).
