### ISSUE TITLE
Cover device error: Invalid option for select.tuya_cover_set_bottom_limit and select.tuya_cover_set_upper_limit

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#20675]
### What happened?

See this error at log.
Error connected with zigbee device: cover [AM43-0.45/40-ES-EB](https://www.zigbee2mqtt.io/devices/AM43-0.45_40-ES-EB.html#moes-am43-0.45%252F40-es-eb)

### What did you expect to happen?

no error

### How to reproduce it (minimal and precise)

add this cover device zg2mqt and see error

### Zigbee2MQTT version

 1.35.1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

Logger: homeassistant.components.mqtt.select
Source: components/mqtt/select.py:129
Integration: MQTT (documentation, issues)
First occurred: 7 January 2024 19:08:05 (886 occurrences)
Last logged: 15:49:21

Invalid option for select.tuya_cover_set_bottom_limit: '{"factory_reset":null,"last_seen":"2024-01-08T15:39:19+01:00","linkquality":255,"motor_direction":null,"motor_speed":50,"opening_mode":null,"position":0,"running":false,"set_bottom_limit":true,"set_upper_limit":true,"state":"STOP"}' (valid options: ['SET'])
Invalid option for select.tuya_cover_set_upper_limit: '{"factory_reset":null,"last_seen":"2024-01-08T15:45:18+01:00","linkquality":255,"motor_direction":null,"motor_speed":50,"opening_mode":null,"position":0,"running":false,"state":"STOP"}' (valid options: ['SET'])
Invalid option for select.tuya_cover_2_set_bottom_limit: '{"factory_reset":null,"last_seen":"2024-01-08T15:45:18+01:00","linkquality":255,"motor_direction":null,"motor_speed":50,"opening_mode":null,"position":0,"running":false,"state":"STOP"}' (valid options: ['SET'])
Invalid option for select.tuya_cover_2_set_upper_limit: '{"factory_reset":null,"last_seen":"2024-01-08T15:49:20+01:00","linkquality":255,"motor_direction":null,"motor_speed":50,"opening_mode":null,"position":0,"running":false,"set_bottom_limit":true,"set_upper_limit":true,"state":"STOP"}' (valid options: ['SET'])

**Comment by adekloet** [comment]
As an alternatief, if you don't the select options (you have setvthe user and down limit on the device itself) you can disable these entities in MQTT and that does away with the error in HA. The device functions as expected.
