### ISSUE TITLE
Location of log file

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#207]
Tnx, nice job.
I managed to get zigbee2mqtt working with Domoticz on a Raspberry Pi.
I would like to have the logging to the tmpfs '/var/log'
Could it be possible to set the location of the logging in the config file?

**Comment by Koenkk** [comment]
Not yet, but this can be added as an feature.

**Comment by SargonofAssyria** [comment]
Perfect, I wait for it.

**Comment by tb-killa** [comment]
We could combine this via https://github.com/Koenkk/zigbee2mqtt/issues/182.

**Comment by Koenkk** [comment]
This is now possible (currently dev branch only).

```yaml
advanced:
  log_directory: /var/log
```

**Comment by tb-killa** [comment]
Works great, could be merged :)

**Comment by Koenkk** [comment]
I try to merge the dev branch into master every +- 2 weeks. However currently my time is very limited due to moving houses.
