### ISSUE TITLE
z2mqtt stops working randomly

### ISSUE THREAD

**Issue by nicolapejo** [Koenkk/zigbee2mqtt#20703]
### What happened?

I have a Z2mqtt installation on a docker in an Unraid server, it occasionally stops receiving data from zigbee devices and if I try to give any input it returns the error: _sendZclFrameToEndpointInternal_. Restarting the docker everything starts working properly again.

### What did you expect to happen?

Zigbee devices should send their status and buttons should send input.

### Zigbee2MQTT version

 1.35.1 commit: 9eaaa0f

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Debug log

info  2024-01-09 13:14:27: MQTT publish: topic 'zigbee2mqtt/sensore presenza camera', payload '{"detection_delay":0,"fading_time":5,"illuminance_lux":7,"linkquality":148,"maximum_range":1.2,"minimum_range":0.15,"presence":false,"radar_sensitivity":6,"target_distance":0}'
error 2024-01-09 19:23:45: Publish 'set' 'state' to 'luce camera 2' failed: 'Error: Command 0x60efabfffeeeaf13/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
error 2024-01-09 19:23:45: Publish 'set' 'state' to 'luce camera 1' failed: 'Error: Command 0x60efabfffef11725/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
error 2024-01-09 19:23:47: Publish 'set' 'state' to 'luce camera 2' failed: 'Error: Command 0x60efabfffeeeaf13/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)'
info  2024-01-09 19:36:09: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'

**Comment by usma0118** [comment]
Related: #19269

**Comment by usma0118** [comment]
Related #20715

**Comment by ottoketney** [comment]
I have same behavior

**Comment by apoltanov** [comment]
Same for me. Z2M is running as an add-on in HA and stops getting states from all devices at once. Log contains "Failed to ping..." entries due to availability feature.
Z2M keeps running for about 1 day long, and then all devices stop responding until z2m is reloaded. No any sign of an error in logs, except availability warnings.

**Comment by syrusfem** [comment]
I have the same problem, once a day (sometimes 2 or 3 times a day) all Z2M controlled devices stop responding until i reload the integration. i have Z2M as an add-on in HA. Reverting to 1.3.4 solved my problems so it seems correlatied with 1.3.5.1 (and 1.3.5.0) version.

**Comment by DarkVillager** [comment]
I have the same problem/

**Comment by nicjansma** [comment]
Having the same issue here once I went to 1.35.1

**Comment by AndreasFlach** [comment]
Have the same behavoir on Odroid M1 with Home Assistant OS and Zigbee2MQTT 1.35.1-1 Addin
HA Core 2024.1.3, Supervisor 2023.12.1, Operating System 11.4, Frontend 20240104.0.
Zigbee device stream dies, if you check with the overview card the error "lqi for 'coordinator' failed
Watchdog does not identify dead of Zigbee2MQTT.
Restart of Container solves it for a few hours, in this style not stable.
Stick: Aeotec Z-Stick 7

**Comment by lmarcelocc** [comment]
Same here running on a Raspberry Pi.

**Comment by fixed77** [comment]
Having the same issue, rolled back to 1.34.0 from backups.

**Comment by Koenkk** [comment]
Please provide the herdman debug log from starting z2m until the crash with 1.35.1

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by fixed77** [comment]
[4.txt](https://github.com/Koenkk/zigbee2mqtt/files/14014224/4.txt)
first failed timestamp: 2024-01-22T18:13:16.944Z

**Comment by Koenkk** [comment]
@fixed77 the coordinator crashes in your case, what fw are you using? If using `20230507` try [`20221226`](https://github.com/Koenkk/Z-Stack-firmware/releases/tag/Z-Stack_3.x.0_coordinator_20221226)

**Comment by fixed77** [comment]
> @fixed77 the coordinator crashes in your case, what fw are you using? If using `20230507` try [`20221226`](https://github.com/Koenkk/Z-Stack-firmware/releases/tag/Z-Stack_3.x.0_coordinator_20221226)

20221226

**Comment by fixed77** [comment]
> @fixed77 the coordinator crashes in your case, what fw are you using? If using `20230507` try [`20221226`](https://github.com/Koenkk/Z-Stack-firmware/releases/tag/Z-Stack_3.x.0_coordinator_20221226)

update to 20230507. my problem is resolved.

**Comment by nicolapejo** [comment]
> Please provide the herdman debug log from starting z2m until the crash with 1.35.1
> 
> See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

[log_zigbee2mqtt3.txt](https://github.com/Koenkk/zigbee2mqtt/files/14102673/log_zigbee2mqtt3.txt)
Here is my log, it has been a while since it froze

**Comment by nicolapejo** [comment]
problem solved with latest release
