### ISSUE TITLE
Cluster Attribute wrongly decoded

### ISSUE THREAD

**Issue by dduransseau** [Koenkk/zigbee2mqtt#20719]
### What happened?

Some seMetering attributes are not well decoded by zigbee-herdsman and the key of the attribute is present as integer in place of cluster attribute key defined cluster.ts. Some are correctly parsed.
Ex: attribute `"8451"` is present despite `owonReactivePowerSum: {ID: 0x2103, type: DataType.int24,manufacturerCode: ManufacturerCode.OWON}`, is correctly specified. 
However `owonL1PhasePower: {ID: 0x2000, type: DataType.int24,manufacturerCode: ManufacturerCode.OWON}`, is correctly parsed and the key in the attribute is `"owonL1PhasePower"`. 
I don't know where I should investigate this issue to try to fix it. For now I created a specific converter that manage specific attribute that are not parsed.
I tried to unpair/pair the device but it didn't changed

### What did you expect to happen?

Attributes "8451" (0x2103) should be decoded as "owonReactivePowerSum"
Attributes "12547" (0x3103) should be decoded as "owonCurrentSum"
Attributes "16643" (0x4103) should be decoded as "owonReactiveEnergySum"

### How to reproduce it (minimal and precise)

Having a look at seMetering attributes exposed by the device. 
To troubleshoot I created a extension that publish the full message of onDeviceMessage to a debug topic.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

0x26780700

### Adapter

conbeeII

### Setup

Add-On Home-Assistant OS

**Comment by dduransseau** [comment]
I think I understand the root cause of that issue: The device send frame per Phase and one for summation. The frame summation don't have the manufacturerCode specified, which cause that specific attribute are not well parsed. 
Maybe this is specific to my device firmware.

**Comment by danieledwardgeorgehitchcock** [comment]
I also cannot find reference to any decode logic for the attribute responses you list above:

[Owon](https://github.com/Koenkk/zigbee-herdsman-converters/blob/6939b177651897c964a577279103c22c7e58f372/src/devices/owon.ts#L21)

**Comment by dduransseau** [comment]
If fact decoding is already performed by fromZigbee.metering since the OWON attributes are specified in the cluster.
