### ISSUE TITLE
[New device support]: SCHNEIDER WISER CCTFR6500

### ISSUE THREAD

**Issue by alexxiiis-7** [Koenkk/zigbee2mqtt#20751]
### Link

https://www.se.com/fr/fr/product/CCTFR6500/wiser-prise-connect%C3%A9e-r%C3%A9p%C3%A9teur-zigbee-13a/

### Database entry

.

### Comments

Good morning,
I am disappointed because I just switched from Zigbee to JeeZigbee and my Schneider CCTFR6500 connected plugs are not recognized under the right model, recognized under the HEIMAN HS2SK model.
I have problems with ON/OFF action.
In the list of your compatible equipment, in Schneider connected socket I find only the model CCT711119 which obviously looks but an old version of my model.
How do I use my shots with JeeZigbee as before?
Thanks a lot for your help!

### External defintion

```shell
.
```

**Comment by danieledwardgeorgehitchcock** [comment]
Could you provide the fingerprint for this device from your Zigbee2MQTT database file?

Either that, or upload screenshots from your Z2M frontend of the device About tab and the Clusters tab?

**Comment by alexxiiis-7** [comment]
Good morning;
Thank you for your feedback.
You will find the screenshots of the tabs "Dev Console", "About" and "Clusters".
Hopefully this will meet your request.
I saw in the Dev Console that the model noted is the one that was found automatically but is not the right one.
Here was identified a HEIMAN plug while it is a Schneider CCTFR6500 plug.

Thank you very much in advance

![External Definition](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/30702ed6-f79c-4738-ab60-8051a2c6407c)
![About](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/7428af9f-5550-4509-a503-7a5ff6e97936)
![Clusters](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/07864920-ac50-47c5-8ed6-60d0ee4ece86)

**Comment by alexxiiis-7** [comment]
> Could you provide the fingerprint for this device from your Zigbee2MQTT database file or the auto generated converter?
> 
> Either that, or upload screenshots from your Z2M frontend of the device About tab and the Clusters tab?

**Comment by alexxiiis-7** [comment]
> Could you provide the fingerprint for this device from your Zigbee2MQTT database file or the auto generated converter?
> 
> Either that, or upload screenshots from your Z2M frontend of the device About tab and the Clusters tab?


Good morning;
Thank you for your feedback.
You will find the screenshots of the tabs "Dev Console", "About" and "Clusters".
Hopefully this will meet your request.
I saw in the Dev Console that the model noted is the one that was found automatically but is not the right one.
Here was identified a HEIMAN plug while it is a Schneider CCTFR6500 plug.

Thank you very much in advance

![External Definition](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/2f59a350-0c92-4e8e-999b-787f95544791)
![About](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/18e1eb37-2b8f-4e14-9b86-67ab01afee7c)
![Clusters](https://github.com/Koenkk/zigbee2mqtt/assets/156422621/47a3dda4-f386-4791-bc8e-30cc2c618090)

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for uploading the screenshots.

So, I can see that the device reports back that it is a Heiman plug so, there is not much we can do here.

Basically, certain manufacturers can 'whitelabel' products for other brands - this is a classic case of where this has occured. I.E. Heiman has their own brand of plug, but has also produced the same plug with branding for Schneider.

I will add the whitelabel to the Heiman device in the Herdsman Converters but, this will not change anything in the frontend / control.

The device should be fully functional with this converter.

**Comment by senna1992** [comment]
I am using some of these, also whitelabeled by schneider / wiser.

working fine but sometimes the total power does get mixed up by 1000x.
very annyoing, but seems to a firmware thing.

i am running versin 20220518"
