### ISSUE TITLE
[Wrong device]: Moes Smart Button ERS-10TZBVB-AA

### ISSUE THREAD

**Issue by Flavien06** [Koenkk/zigbee2mqtt#20757]
### Link

https://www.zigbee2mqtt.io/devices/ERS-10TZBVB-AA.html

### Model

ERS-10TZBVB-AA

### Description

Smart button

### Vendor

TuYa

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/ERS-10TZBVB-AA.jpg

### Database entry

{"id":14,"type":"EndDevice","ieeeAddr":"0x4c5bb3fffe2e8f95","nwkAddr":26465,"manufId":4098,"manufName":"_TZ3000_ja5osu5g","powerSource":"Battery","modelId":"TS004F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[0,1,3,4,6,4096,57345],"outClusterList":[25,10,3,4,6,8,4096],"clusters":{"genBasic":{"attributes":{"65506":31,"65508":1,"65534":0,"modelId":"TS004F","manufacturerName":"_TZ3000_ja5osu5g","powerSource":3,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"tuyaOperationMode":1}},"manuSpecificTuya_3":{"attributes":{"53265":"�\u0000\u0003�\u0003�\u0000Z\u0003�\u0003�\u0000\u0003�\u0000d\u0000�\u0003�\u0003�\u0000\u0001�\u0003 \u0001\u000e\u0003�\u0003�\u0001\u0001�\u0000\u0000\u0000�\u0000�\u0000�"}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c16cdb","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c16cdb","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-429758583},"lastSeen":1705078893389,"defaultSendRequestWhen":"immediate"} {"id":15,"type":"EndDevice","ieeeAddr":"0x6c5cb1fffefc8739","nwkAddr":62563,"manufId":4098,"manufName":"_TZ3000_ja5osu5g","powerSource":"Battery","modelId":"TS004F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[0,1,3,4,6,4096,57345],"outClusterList":[25,10,3,4,6,8,4096],"clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS004F","manufacturerName":"_TZ3000_ja5osu5g","powerSource":3,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"tuyaOperationMode":0}},"manuSpecificTuya_3":{"attributes":{"53265":"�\u0000\u0003�\u0003�\u0000Z\u0003�\u0003�\u0000\u0003�\u0000d\u0000�\u0003�\u0003�\u0000\u0001�\u0003 \u0001\u000e\u0003�\u0003�\u0001\u0001�\u0000\u0000\u0000�\u0000�\u0000�"}},"genPowerCfg":{"attributes":{"batteryVoltage":30,"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c16cdb","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c16cdb","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-429758583},"lastSeen":1705078749112,"defaultSendRequestWhen":"immediate"}

### Notes

My 2 Moes Smart Button ERS-10TZBVB-AA (id 14 and 15) is recognized as "Loginovo ZG-101ZL" https://www.zigbee2mqtt.io/devices/ZG-101ZL.html#loginovo-zg-101zl

**Comment by danieledwardgeorgehitchcock** [comment]
Hi.

Certain manufacturers can 'whitelabel' products for other brands and this is quite widespread in the TuYa platform - this is a classic case of where that has occured. I.E. Moes has their own brand of plug, but has also produced the same plug with branding for Loginovo (or Vice-Versa).

I've added the whitelabel to the TuYa device in the Herdsman Converters but, this will not change anything in the frontend / control.

The device should be fully functional with this converter.
