### ISSUE TITLE
Sengled E11-N1G No image available

### ISSUE THREAD

**Issue by CAT1210** [Koenkk/zigbee2mqtt#20756]
### What happened?

Looking to update Sengled E11-N1G devices by OTA, which says is supported here:
https://www.zigbee2mqtt.io/devices/E11-N1G.html
When I click 'Check for new updates', it says "Failed to check if update available for '[device]' (No image available for imageType '33171')"

### What did you expect to happen?

Being that it says that OTA is supported, I would expect it to check for an update and not error out.

### How to reproduce it (minimal and precise)

Install a Sengled E11-N1G, pair it with Z2M, go to OTA, click on "Check for new updates"

### Zigbee2MQTT version

1.34.0-dev

### Adapter firmware version

20210708

### Adapter

Sonoff 3.0

### Setup

Add-on Home Assistant

### Debug log

Debug 2024-01-12 09:40:42Received MQTT message on 'zigbee2mqttedge/bridge/request/device/ota_update/check' with data '{"id":"Sconce S","transaction":"q6n8g-2"}'
Info 2024-01-12 09:40:42Checking if update available for 'Sconce S'
Debug 2024-01-12 09:40:42Check if update available for '0xb0ce181400158435' (E11-N1G)
Debug 2024-01-12 09:40:42Using endpoint '1'
Debug 2024-01-12 09:40:44Received Zigbee message from 'Sconce S', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":15,"imageType":33171,"manufacturerCode":4448}' from endpoint 1 with groupID 0
Debug 2024-01-12 09:40:45Got OTA request '{"fieldControl":0,"manufacturerCode":4448,"imageType":33171,"fileVersion":15}'
Debug 2024-01-12 09:40:45ZigbeeOTA: downloaded main index
Info 2024-01-12 09:40:45MQTT publish: topic 'zigbee2mqttedge/bridge/response/device/ota_update/check', payload '{"data":{"id":"Sconce S"},"error":"Failed to check if update available for 'Sconce S' (No image available for imageType '33171')","status":"error","transaction":"q6n8g-2"}'
Error 2024-01-12 09:40:45Failed to check if update available for 'Sconce S' (No image available for imageType '33171')
Debug 2024-01-12 09:40:45Error: No image available for imageType '33171' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/zigbeeOTA.ts:79:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:347:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:338:29) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:45)
Debug 2024-01-12 09:40:48Received Zigbee message from 'Sconce S', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":15,"imageType":33171,"manufacturerCode":4448}' from endpoint 1 with groupID 0
Debug 2024-01-12 09:40:48Device 'Sconce S' requested OTA

**Comment by shad0wca7** [comment]
I'm also having the same issue, for [E1F-N5E]
