### ISSUE TITLE
Can't remove device 

### ISSUE THREAD

**Issue by marsv0** [Koenkk/zigbee2mqtt#20768]
### What happened?

Once I trayed to remove one device (last seen 19 hours ago) I got just error (see logs) ... device is still there

### How to reproduce it (minimal and precise)

just try to remove again

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on HA OS (RPi4)

### Debug log

```
Info 2024-01-13 18:01:27Removing device 'Aqara magnet 01' (block: false, force: false)
Error 2024-01-13 18:01:37Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device 'Aqara magnet 01' (block: false, force: false) (Error: {"address":37693,"clusterId":32820,"sequence":117} after 10000ms)'
Debug 2024-01-13 18:01:37Error: Failed to remove device 'Aqara magnet 01' (block: false, force: false) (Error: {"address":37693,"clusterId":32820,"sequence":117} after 10000ms) at Bridge.removeEntity (/app/lib/extension/bridge.ts:580:19) at Bridge.onMQTTMessage (/app/lib/extension/bridge.ts:128:34) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17)
```

**Comment by sjorge** [comment]
That happens sometimes if the device doesn't reply to the leave request, you can just toggle the 'force remove device' toggle in the frontend.
