### ISSUE TITLE
Bticino's OTA updates not work

### ISSUE THREAD

**Issue by leoogermenia** [Koenkk/zigbee2mqtt#20789]
### What happened?

I'm trying to update my switch (K4003C), but I recived multiple errors. Sometimes I can start the update, but when it arrives to 98/99% it fails

### How to reproduce it (minimal and precise)

Start update for the device

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E"

### Setup

Add-on on HA (Proxmox VM)

### Debug log

Update of 'Lampadario Cameretta' failed (OTA: Timeout, device did not request any image blocks)

**Comment by syntesys87** [comment]
I also have the same problem.

**Comment by leoogermenia** [comment]
> I also have the same problem.

Hi, at the end I was able to update it. Just try to click lots of time the update button and it updates

**Comment by syntesys87** [comment]
I tried one month clicking the update button of every device without solution..
