### ISSUE TITLE
GZCGQ01LM many timeout

### ISSUE THREAD

**Issue by lbarjak** [Koenkk/zigbee2mqtt#20817]
### What happened?

Lots of error messages:
...
Zigbee2MQTT:error 2024-01-15 12:39:14: Publish 'get' 'illuminance' to 'luxmérő_xz1' failed: 'Error: Read 0x54ef44100030234b/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 44566 - 1 - 35 - 1024 - 1 after 10000ms)'
Zigbee2MQTT:error 2024-01-15 12:39:34: Publish 'get' 'illuminance' to 'luxmérő_xz1' failed: 'Error: Read 0x54ef44100030234b/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 44566 - 1 - 43 - 1024 - 1 after 10000ms)'
Zigbee2MQTT:error 2024-01-15 12:39:54: Publish 'get' 'illuminance_lux' to 'luxmérő_xz1' failed: 'Error: Read 0x54ef44100030234b/1 msIlluminanceMeasurement(["measuredValue"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 44566 - 1 - 63 - 1024 - 1 after 10000ms)'
...

### How to reproduce it (minimal and precise)

it's always like this

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF ZigBee 3.0 Dongle E USB stick EFR32MG21

### Setup

standalone, nodejs, x86-64

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13938729/log.txt)

**Comment by Pardasus** [comment]
I have exactly the same problem with the same sensor since the update to 1.35.x
