### ISSUE TITLE
PIR Sensor Tuya 809WZT won't connect

### ISSUE THREAD

**Issue by juandelarocha** [Koenkk/zigbee2mqtt#20814]
### What happened?

Description of the issue

I have just bought a new Tuya 809WZT and there's no way I can manage to attach it to the zigbee network. The sensor has a working battery, it blinks when pressing the button, and the Zigbee2mqtt is obviously in "permit to join" mode. I have already more than 25 sensors in the network working flawlessly. The Zigbee adaptor is a sonoff dongle zbdongle. 

I have tried in different ways, pressing the button with the pin included in the box, pressing for more than 10 secs (as the instructions said) pressing only 5 secs, pressing right before changing the battery, but there's no trace of the device in the log of zigbe2mqtt. 

I confirm the device is a zigbee 3.0 sensor. 

Addon version
Current version: 1.35.1-1

Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

### Zigbee2MQTT version

1.35.1-1

### Adapter firmware version

20220219

### Adapter

Sonoff CC2652P

### Setup

Add-on on HomeAssistant setup in Intel NUC

**Comment by juandelarocha** [comment]
Solved. Don't know why, but managed to open the sensor and it worked when out of the plastic case.

**Comment by juandelarocha** [comment]
Solved. Don't know why, but managed to open the sensor and it worked when out of the plastic case.

**Comment by Col-Hogan** [comment]
Hi,
ich hatte heute das gleiche problem.
Ich denke das problem liegt am Minuspin. Die Ausstanzung trückt auf die Platine und deshalb kommt es zu falschem Minus Potenzial.

![Tuya 809WZT 1](https://github.com/Koenkk/zigbee2mqtt/assets/47892951/6e51cf9b-f7d6-4d20-96aa-3608fcb83f48)
![Tuya 809WZT 2](https://github.com/Koenkk/zigbee2mqtt/assets/47892951/eecd8890-9c60-4bdf-92b0-1a9f981b7991)

**Comment by andrefcarvalho** [comment]
i have the same problem, but with a broken component..
![IMG_20240218_110729](https://github.com/Koenkk/zigbee2mqtt/assets/43297899/b6bdd16d-0027-4187-87d9-ea4edb37e639)
i have to remove both, but one its broken, because of the metal clip
any one know what component is?
![IMG_20240218_111308](https://github.com/Koenkk/zigbee2mqtt/assets/43297899/63c793c2-46f2-4474-bbbc-b26f33a86295)

**Comment by andrefcarvalho** [comment]
litle sherch, can be a 100r resistor?
https://developer.tuya.com/en/docs/iot/wifi-tyde30-sch?id=K96gqp3brde85

![1](https://github.com/Koenkk/zigbee2mqtt/assets/43297899/269dada0-7891-4771-8162-4f6a732d761e)
![b9b9ba47c4f8434ab258561edec80306](https://github.com/Koenkk/zigbee2mqtt/assets/43297899/c6d167dc-4a2e-46e0-98af-89ff86d3df37)

**Comment by Soukyuu** [comment]
@Col-Hogan: you are spot on. Bending the punchout pin away from the board on both my devices made them finally pair correctly, needed 4-6 tries before that.

**Comment by marksev1** [comment]
Of the two pins in the picture which one is minus and which one is plus and how do they have to be bent when the battery is inserted?
