### ISSUE TITLE
AVATTO ME167 flooding the network

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#20829]
### What happened?

I'm getting this every second or two:

`2024-01-15 21:40:47Received Zigbee message from 'LR Thermostat', type 'commandDataReport', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,230],"type":"Buffer"},"datatype":2,"dp":5}],"seq":9728}' from endpoint 1 with groupID 0
Info 2024-01-15 21:40:47MQTT publish: topic 'zigbee2mqtt/LR Thermostat', payload '{"battery_low":false,"child_lock":"UNLOCK","current_heating_setpoint":22,"error":null,"frost_protection":"OFF","linkquality":87,"local_temperature":23,"local_temperature_calibration":3,"running_state":"idle","scale_protection":"OFF","schedule_friday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_monday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_saturday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_sunday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_thursday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_tuesday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","schedule_wednesday":"06:00/12.0 08:00/16.0 18:00/22.0 20:00/20.0","system_mode":"heat"}' `

### What did you expect to happen?

not getting so many messages

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20230507

### Adapter

Slaeh.sh CC2652RB

### Setup

HAOS VM on Proxmox

**Comment by Koenkk** [comment]
AFAIK TuYa does not support reducing the interval of these messages.
