### ISSUE TITLE
Salus Controls PS600 fails to update firmware

### ISSUE THREAD

**Issue by JohnConnett** [Koenkk/zigbee2mqtt#20840]
### What happened?

For several days Home Assistant has had a notification for an update for the Salus Controls PS600.

I opened the zigbee2mqtt Open Web UI and went to OTA where Update device firmware was highlighted in red, then clicked on Update device firmware.

### What did you expect to happen?

I expected that the firmware would be updated and the notification cleared.

### How to reproduce it (minimal and precise)

Happens automatically if you have a Salus Controls PS600.

### Zigbee2MQTT version

1.35.1-1 

### Adapter firmware version

Core: 2024.1.3; Supervisor: 2023.12.0; OS 11.4; Frontend: 20240104.0

### Adapter

Electrolama zig-a-zig-ah! (zzh!)

### Setup

Add-on on Home Assistant OS on Raspberry Pi 4

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13951088/log.txt)

**Comment by Great-Chart** [comment]
I included an example of the same issue for this device in #20863
I've got two of these PS600's and only one has this issue.
Subsequently I noted many error reports for assorted devices - such as #20658; with inference it's resolved which suggests it'll clear on next release (if not using dev version)
