### ISSUE TITLE
Supported device not recognized

### ISSUE THREAD

**Issue by valentinpx** [Koenkk/zigbee2mqtt#20857]
### What happened?

Hey,
I tried to add my [Moes AM43-0.45/40-ES-EB](https://www.zigbee2mqtt.io/devices/AM43-0.45_40-ES-EB.html) to my devices today.
While the device is successfully added, it is not recognized and I can't control it:
<img width="1224" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/28452631/7b133f37-e33d-4bab-9153-82ba325ce26a">
Here is what is displayed when I'm adding the device:
<img width="427" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/28452631/dbadb7a8-9ef7-4540-a278-c98daaa1365b">
<img width="1193" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/28452631/b8d9d764-5305-40f5-a063-40757a8091ba">
<img width="403" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/28452631/a9b32943-2ebb-45f9-a788-90e3ec4fec2a">
Is there something I'm missing ? Do you know if it's bug ? Should I use the "support new device" page in order to use it ?

Thanks :)

### Zigbee2MQTT version

 1.35.1

### Adapter firmware version

20210708

### Adapter

Sonoff Universal Zigbee 3.0 USB Dongle

### Setup

Add-on on Home Assistant running on an Odroid-2+

**Comment by FabriceC01** [comment]
Hello,
your problem seems similar to mine #20850

**Comment by Chicken123321** [comment]
My old AM43 works fine so I bought another recently and have the same problem.  I think they changed something in software

**Comment by Chicken123321** [comment]
@valentinpx did you managed to make it work?

**Comment by valentinpx** [comment]
@Chicken123321 no I didn't. Maybe we can try [adding a new device](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-add-device-picture-to-zigbee2mqtt-io-documentation). Do you have access to what was supported on your old device ?

**Comment by valentinpx** [comment]
Solved by the last update
