### ISSUE TITLE
Aqara Zigbee 3.0 LED strip T1 no RGB-colors configurable !!in Edge version!!

### ISSUE THREAD

**Issue by Ot4eVash** [Koenkk/zigbee2mqtt#20855]
### What happened?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/115181275/0d765ddb-b763-49ce-881e-25b8f4c374ac)

I know that this topic already existed, but in it the problem was solved by switching to the "Edge" version. I have the Edge version, but the problem remains.

### Zigbee2MQTT version

1.34.0-dev commit: 25de4fd

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus v2

### Setup

HA Addon

**Comment by Koenkk** [comment]
1.34.0-dev commit: https://github.com/Koenkk/zigbee2mqtt/commit/25de4fded9bd67bafb2e8a596490988c624dce88 is outdated, updating to the latest version fixed it
