### ISSUE TITLE
Unable to Configure/Reconfigure for Nue / 3A wall switch (HGZB-42)

### ISSUE THREAD

**Issue by dmeggyesy** [Koenkk/zigbee2mqtt#20867]
### What happened?

Nue / 3A HGZB-42 (2-gang wall switch) is unable to configure/reconfigure.  (May be related to #20666 ?)

Also have the 1-gang version of this switch and it seems to not have the issue (HGZB-41).

Log:
Failed to configure 'kitchen_dining_wall_switch_light', attempt 4 (Error: ConfigureReporting 0x00158d00025d8781/12 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:331:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:684:22) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:55:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:117:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25) at Configure.configure (/app/lib/extension/configure.ts:120:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

### What did you expect to happen?

configure / reconfigure not cause errors.

### How to reproduce it (minimal and precise)

Pair device, 
or,
on restart, zigbee2mqtt will attempt a number of times to reconfigure it.
or,
manually click reconfigure for said device.

### Zigbee2MQTT version

1.35.1-dev commit: 080f3b6

### Adapter firmware version

7.3.1.0 build 176

### Adapter

Sonoff ZBDongle-E

### Setup

x86-64 - running in a docker container.

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13977165/log.txt)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
