### ISSUE TITLE
[Wrong device]: Idinio Zigbee LED Rotary Dimmer 0140300 identifies as Dimmer-Switch-ZB3.0 0140302

### ISSUE THREAD

**Issue by L3nny5** [Koenkk/zigbee2mqtt#20878]
### Link

https://www.shada.nl/products/5453/zigbee-led-rotary-dimmer

### Model

0140300

### Description

Rotary Dimmer

### Vendor

Idinio

### Picture (link)

https://www.shada.nl/sites/default/files/styles/large/public/products/0140300/24841_140300_Pers2.jpg

### Database entry

{"id":27,"type":"Router","ieeeAddr":"0x000d6ffffec92137","nwkAddr":63536,"manufId":4714,"manufName":"idinio","powerSource":"Mains (single phase)","modelId":"Dimmer-Switch-ZB3.0","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"onOff":0,"startUpOnOff":0}}

### Notes

Device works, but Icon, Model and Description is incorrect.

**Comment by wkneppers** [comment]
Started today with adding 4 of these dimmers to my new Z2MQTT instance. Can see the wrong information as well, also, the commands are failing and it isn't working properly. 

`2024-02-05 21:37:08Publish 'set' 'state' to 'Dimmer TV lampen' failed: 'Error: Command 0x000d6ffffeca997d/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (44))'`
