### ISSUE TITLE
Deive deteced with RGB Support but only Supports cold, warmwhite, brightness

### ISSUE THREAD

**Issue by Mangomc** [Koenkk/zigbee2mqtt#20884]
### What happened?

Im using this devices:
https://www.zigbee2mqtt.io/devices/RB_278_T.html#innr-rb%2520278%2520t

They are working as expexted but Z2m thinks they are also suporting colormode what its wrong. They are only support warm and cold White and brightness 

Link to the vendor
https://www.innr.com/en/product/smart-bulb-comfort-e27-2-pack-2021/

### What did you expect to happen?

Remove the colormode Option 

### How to reproduce it (minimal and precise)

Pair the device 

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee Stick P

### Setup

HA Adson

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
