### ISSUE TITLE
"Trigger Hass.io build" CI step fails

### ISSUE THREAD

**Issue by gabe565** [Koenkk/zigbee2mqtt#2090]
The "Trigger Hass.io build" step is failing during the Azure Pipelines CI process.
Seems like the recent Azure Pipeline changes are trying to call a command called `TRAVIS_TOKEN` which does not exist. Also, the `curl` command is failing but the step still seems to pass.

The CI output is:
```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/4c54deb9-6fd2-4a3d-a3f0-ecb45e2a451d.sh
/home/vsts/work/_temp/4c54deb9-6fd2-4a3d-a3f0-ecb45e2a451d.sh: line 2: TRAVIS_TOKEN: command not found
{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
```

An example failed build is [here](https://dev.azure.com/koenkk/zigbee/_build/results?buildId=149&view=logs) and the relevant line is [here](https://github.com/Koenkk/zigbee2mqtt/blob/41c8c2a146d9b3f06b3da34f3ba06bc4120c79f9/azure-pipelines.yaml#L78).

I can't see environment variables, but is this meant to be `${TRAVIS_TOKEN}`?

**Comment by Koenkk** [comment]
Thanks, fixed! (https://dev.azure.com/koenkk/zigbee/_build/results?buildId=161)
