### ISSUE TITLE
[New device support]: Revise the code for Xiaomi QBKG18LM (Aqara T1 double rocker without neutral)

### ISSUE THREAD

**Issue by cloudyngcloudy** [Koenkk/zigbee2mqtt#20905]
### Link

https://www.zigbee2mqtt.io/devices/QBKG18LM.html

### Database entry

n/a

### Comments

Sorry that I have wrongly referred the code for QBKG18LM as "using the existing code for QBKG19LM", but which is not true (as shown in the following issue:-  https://github.com/Koenkk/zigbee-herdsman-converters/issues/5993)

Instead, this is the code (as below) I used before to make QBKG18LM work properly.  Glad to have your update to revise the code in Z2M.  Thank you.  Sorry for the inconvenience caused.

***************

```
const zigbeeHerdsmanConverters = require('zigbee-herdsman-converters');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const ea = exposes.access;
const e = exposes.presets;
const fz = zigbeeHerdsmanConverters.fromZigbee;
const tz = zigbeeHerdsmanConverters.toZigbee;

const device = {
    zigbeeModel: ['lumi.switch.b2lacn01'],
    model: 'QBKG18LM',
    vendor: 'Xiaomi',
    description: 'Aqara T1 double rocker without neutral',
    fromZigbee: [fz.on_off, fz.xiaomi_multistate_action],
    toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode_opple, tz.xiaomi_switch_power_outage_memory, tz.xiaomi_led_disabled_night, tz.xiaomi_flip_indicator_light],
    exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('right'), e.power().withAccess(ea.STATE), e.flip_indicator_light(), e.led_disabled_night(), e.linkquality(), e.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled']).withDescription('Decoupled mode for left button').withEndpoint('left'), e.enum('operation_mode', ea.ALL, ['control_relay', 'decoupled']).withDescription('Decoupled mode for right button').withEndpoint('right')],
    meta: {
        multiEndpoint: true,
    },
    endpoint: (device) => {
        return {
            'left': 1, 'right': 2,
        };
    },
};
module.exports = device;
```

### External defintion

```shell
n/a
```

**Comment by cloudyngcloudy** [comment]
After updating the external convertor, the log stated "Failed to load external converter file 'QBKG18LM.js' (xiaomi is not defined)".
Not sure how to define xiaomi in external convertor file, any idea?

**Comment by Koenkk** [comment]
Add this to the top of the file: `const xiaomi = require('zigbee-herdsman-converters/lib/xiaomi');`

**Comment by cloudyngcloudy** [comment]
it works thanks.

Koen Kanters ***@***.***> 於 2024年1月23日 週二 上午3:36寫道：
