### ISSUE TITLE
No status switch in HA after upgrade zigbee2mqtt 

### ISSUE THREAD

**Issue by ikey-ru** [Koenkk/zigbee2mqtt#20904]
### What happened?

Updated zigbee2mqtt and lost the ability to control many relays
There are no required entities in the home assistant system. (No on-off status switch).
All: "This entity is no longer provided by the mqtt integration"
Updating the home asistant does not help.
For example relays SONOFF ZBMINI, TuYa WHD02, TuYa TS0121_plug and others.
I don't understand why breaking everything? 

<img width="1001" alt="2" src="https://github.com/Koenkk/zigbee2mqtt/assets/47115676/2369ec44-0925-48cb-8c72-64431fba4b1c">
<img width="569" alt="1" src="https://github.com/Koenkk/zigbee2mqtt/assets/47115676/b532a37d-5fb2-4a03-a88c-eadd44ba52cc">

### What did you expect to happen?

That nothing's gonna break

### How to reproduce it (minimal and precise)

Try opening the relay settings in HA

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20211222

### Adapter

zStack30x

### Setup

x86-64

**Comment by HelloCore** [comment]
Hi @ikey-ru , I also found this problem, how did you fix it?

For me, I downgraded back to the old version 😭.

**Comment by ikey-ru** [comment]
It was necessary to update the Home assistant.
Before that, most likely you will have to update the python.
