### ISSUE TITLE
[New device support]: Purmo Yali Digital Plus electric heating radiator 

### ISSUE THREAD

**Issue by juntta** [Koenkk/zigbee2mqtt#20913]
### Link

https://global.purmo.com/en/products/heating-systems/electric-heating/electric-radiators/oil-filled-radiators/yali-digital-plus

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0x001e5e0902894744","nwkAddr":36924,"manufId":4216,"manufName":"computime","powerSource":"Unknown","modelId":"PUMM01102","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,3,513,516,2821,64515,64516,64522,64524],"outClusterList":[10,25,64515],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"dateCode":"20220817","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1705756292867,"defaultSendRequestWhen":"immediate"}

### Comments

Tried to add device but couldn't even get external definition created since device exposes tab was empty and "Generate external definition" wasnt even available at UI's Dev console

### External defintion

```shell
Not available
```

**Comment by guidok0127** [comment]
Hello, I also have Yali / Prada heaters from Purmo (sold by LVI Thermosoft in Australia).  I mainly use zigbee2mqtt with HA, however these Purmo devices are not yet supported.  However, ZHA does support them and attached is a **diagnostic JSON file**  (computime PUMM01102) which may help with clusters/attributes/commands etc.

Of particular interest would be to set the **front panel temperature** level.  The device-embedded control allows to set three levels (["no",90°C],["mid",75°C],["lo",60°C]).  When connecting to ZHA this resets to "no" and there is no configuration to set.  There is a sensor Pi_heating_demand (%) which provides the actual, but it cannot be configured.

[ZHA Diagnostics - computime PUMM01102 (for Yali Heaters from Purmo).json](https://github.com/Koenkk/zigbee2mqtt/files/14519854/ZHA.Diagnostics.-.computime.PUMM01102.for.Yali.Heaters.from.Purmo.json)

Anyone able to help?  I am happy to assist testing the device for zigbee2mqtt.
