### ISSUE TITLE
orvibo log error since 1.35.1 but working with automation

### ISSUE THREAD

**Issue by steve41200** [Koenkk/zigbee2mqtt#20918]
### What happened?

Error in log for my 3 orvibo RL804QZB since z2m 1.35.1
but they still work.
This is the error msg
`Failed to configure 'VMC GV', attempt 1 (Error: Bind 0x00124b0022c9bd9d/1 genOnOff from '0x00124b001ca1aed9/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:563:13) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:54:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:117:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25) at Configure.configure (/app/lib/extension/configure.ts:120:13) at Immediate.<anonymous> (/app/lib/extension/configure.ts:72:17))`

Since this update my Legrand teleruptor are difficult to control (automation works but directly order form z2M or HA not always)

I have install the devbrnahc to try a tip to reset and reconnect my Legrand device, it works (for the moment) but I always have the error for orvibo device

### Zigbee2MQTT version

1.35.1 and 1.35.1-dev commit: de7bc7c

### Adapter firmware version

20230507

### Adapter

zStack3x0  (CC1352P2)

### Setup

z2m addon form HAOSS (in a Proxmox VM on a NUC)

### Debug log

Failed to configure 'portail', attempt 3 (Error: ConfigureReporting 0x00124b0022cdc330/1 genOnOff([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 3192 - 1 - 90 - 6 - 7 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:499:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:681:28) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:55:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:117:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25) at Configure.configure (/app/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
