### ISSUE TITLE
Sonoff Dongle E Router not detected from Silabs Flasher

### ISSUE THREAD

**Issue by smartmatic** [Koenkk/zigbee2mqtt#20929]
### What happened?

I flashed my Sonoff Dongle E with Router firmware as described here in the Docs with the Silabs Flasher method: https://www.zigbee2mqtt.io/devices/ZBDongle-E.html
This works and i can use the Dongle as Router but now the Dongle is no longer detected by the Silabs Flasher. Means it is not possible to switch the Firmware back e.g. to Zigbee or Multipan.

### What did you expect to happen?

Choose any firmware which can be flashed with Silabs Flasher.

### How to reproduce it (minimal and precise)

Flash the Dongle with the Router firmware and after that try to connect the Dongle again with the Silabs Flasher. 

### Zigbee2MQTT version

1.35.1-1

### Adapter firmware version

 7.3.1.0 build 176

### Adapter

Sonoff Dongle E

### Setup

Home Assistant Add-On

**Comment by Gjuju** [comment]
Just, open it and press boot button when plugin it, you can release button after a couple of seconds.
It should work.
It's a common problem when those dongle-e are flashed with router firmware.

**Comment by smartmatic** [comment]
Ok, i will try also it is a really benefit that it was not necessary to open the Dongle when Silabs flasher is used for the other firmware variants.

**Comment by Gjuju** [comment]
If I understand well, thats a firmware limitation, not a problem with silabs web flasher.

The same behavior occur with elelabs firmware update utility.

**Comment by smartmatic** [comment]
Thank you. Solution worked.

**Comment by mariomare22** [comment]
I tried the solution above but I get the error:
The running firmware could not be detected.

**Comment by mariomare22** [comment]
reflashed coordinator firmware. all good

**Comment by blahnika** [comment]
> Just, open it and press boot button when plugin it, you can release button after a couple of seconds. It should work. It's a common problem when those dongle-e are flashed with router firmware.

awesome, that did it for me, thanks!

**Comment by darknessblade** [comment]
> Just, open it and press boot button when plugin it, you can release button after a couple of seconds. It should work. It's a common problem when those dongle-e are flashed with router firmware.

Weirdly this doesn't work for mine [2nd coordinator, I bought for Z2M] .
Not sure why.
I also got a error that drivers weren't found, so I used the guide from Silabs to update. [might be that my PC needs a restart as well, will test this later]

Store link:
https://aliexpress.com/item/1005008131612347.html?
