### ISSUE TITLE
VES-ZB-WAL-012 Battery 200%

### ISSUE THREAD

**Issue by tobiasg021** [Koenkk/zigbee2mqtt#20936]
### What happened?

The battery is on 200% 
![Screenshot_20240122_014802_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/145073106/62822478-3ec0-4d0c-8bce-709fe74cd936)
![Screenshot_20240122_014751_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/145073106/70280e3f-3cf0-4dce-a0f5-336d0d69e23e)

### What did you expect to happen?

100% or lower 

### How to reproduce it (minimal and precise)

Connect to Zigbee2mqtt 

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20230507

### Adapter

Sonoff dongle P 

### Setup

Zigbee2mqtt as Home assistant addons on Intel Nuc

**Comment by Koenkk** [comment]
@martyn-vesternet could you check this?

**Comment by tobiasg021** [comment]
1.5 years later, the converter no longer works. When will the change be implemented in series production? See log.

z2m: Invalid external converter 'VES-ZB-WAL-012_as_button_controller.js' was ignored and renamed to prevent interference with Zigbee2MQTT. (Cannot read properties of undefined (reading 'options')) 

PS:  warning: 	z2m: External converters are not meant for long term usage, but for local testing after which a pull request should be created to add out-of-the-box support for the device
