### ISSUE TITLE
[New device support]: Adding new Zigbee device model to an already supported device (Philips Hue Enrave Medium)

### ISSUE THREAD

**Issue by dimatx** [Koenkk/zigbee2mqtt#20934]
### Link

https://www.philips-hue.com/en-us/p/hue-white-ambiance-enrave-medium-ceiling-lamp/046677580773

### Database entry

Not sure how to retrieve, the model that it shows is 929003574301

### Comments

This device (929003574301) works out of the box despite being 'Not supported'.

It is a Philips Enrave Medium Celing Lamp.

This device (929003574301) is the same as an already supported device: https://www.zigbee2mqtt.io/devices/915005996701.html

![image](https://github.com/Koenkk/zigbee2mqtt/assets/24803941/520b66ad-10f4-49f6-90e5-5cabc1f23b8f)

### External defintion

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['929003574301'],
    model: '929003574301',
    vendor: 'Signify Netherlands B.V.',
    description: 'Automatically generated definition',
    extend: [philipsLight({"colorTemp":{"range":[153,454]}})],
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
