### ISSUE TITLE
Missing climate entity for Eurotronic SPZB0001

### ISSUE THREAD

**Issue by sti0** [Koenkk/zigbee2mqtt#2094]
# Bug Report
## What happened
Added a new Eurotronic SPZB0001 to zigbee2mqtt.

```
10/7/2019, 9:37:04 PM - info: New device 'SPZB0001' with address 0x00158d000192d0a1 connected!
10/7/2019, 9:37:04 PM - info: MQTT publish: topic 'homeassistant/sensor/0x00158d000192d0a1/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d000192d0a1","json_attributes_topic":"zigbee2mqtt/0x00158d000192d0a1","name":"0x00158d000192d0a1_linkquality","unique_id":"0x00158d000192d0a1_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d000192d0a1"],"name":"0x00158d000192d0a1","sw_version":"Zigbee2mqtt 1.6.0","model":"Spirit Zigbee wireless heater thermostat (SPZB0001)","manufacturer":"Eurotronic"},"availability_topic":"zigbee2mqtt/0x00158d000192d0a1/availability"}'
10/7/2019, 9:39:42 PM MQTT publish: topic 'zigbee2mqtt/0x00158d000192d0a1', payload '{"current_heating_setpoint":21,"eurotronic_system_mode":1,"local_temperature":20.87,"occupied_heating_setpoint":21,"unoccupied_heating_setpoint":16}'
10/7/2019, 9:39:49 PM Successfully configured 0x00158d000192d0a1 (0x00158d000192d0a1)
```

Only a linkquality sensor is exposed to Home Assistant.

## What did you expect to happen
Exposing a climate component.

## How to reproduce it (minimal and precise)

Join a Eurotronic SPZB0001 to z2m

## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version: 20190425

**Comment by sti0** [comment]
Battery information is also missing. The ioBroker implementation got the battery information for this device. That means it must be send (https://forum.iobroker.net/topic/20754/gel%C3%B6st-eurotronic-heizk%C3%B6rperthermostat-spirit-zigbee-einstellungen)

**Comment by Koenkk** [comment]
fixed in latest dev branch, can you confirm?

**Comment by sti0** [comment]
That was fast. Thanks.

Edge version on hassio starts up with

`zigbee2mqtt:info  2019-10-07T20:30:15: Starting zigbee2mqtt version 1.6.0 (commit #3e75108741a0d7328b278a8c26daaf8a5adf0934)`

Changes are not included in this commit.
I think it needs some time to get the newest commit. Is it right? Maybe I give it another try tomorrow.

**Comment by Koenkk** [comment]
Should be up now.

**Comment by sti0** [comment]
Still got the old commit. Even after a new installation of the zigbee2mqtt_edge addon.

`zigbee2mqtt:info  2019-10-08T16:55:42: Starting zigbee2mqtt version 1.6.0 (commit #3e75108741a0d7328b278a8c26daaf8a5adf0934)`

**Comment by sawfear** [comment]
I´m getting the newest commit on the edge addon and it seems now to be reading more stats (battery and temperature aswell as linkquality) But unfortunately the temperature can not be set automatically with Home Assistant Automation. Do you have any idea why? I tried with this config:

- id: '1570554579605'
  alias: Test
  trigger:
  - at: '19:25'
    platform: time
  action:
  - data:
      entitiy_id: climate.WC
      temperature: 22
    service: climate.set_temperature


The Home Assistant log shows this entry when firing the automation:

2019-10-08 20:35:33 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.test. Invalid data for call_service at pos 1: extra keys not allowed @ data['entitiy_id']

Your help is much appreciated!
Thanks

**Comment by stefanroelofs** [comment]
>     entitiy_id: climate.WC

Typo. Should be: entity_id

**Comment by sti0** [comment]
@sawfear quick offtopic question: I bought two of the thermostats. Both are very noisy on open/close. I think not useful in sleeping rooms. Could you confirm this?

**Comment by stefanroelofs** [comment]
I bought 1 this week. They do make noise, but I don't think it is too bad.
I think that when someone is sleeping they won't have to actuate much, so its no problem for me.

**Comment by sawfear** [comment]
> 
> 
> @sawfear quick offtopic question: I bought two of the thermostats. Both are very noisy on open/close. I think not useful in sleeping rooms. Could you confirm this?

Mine isn´t too noisy also.. I guess it is a little bit louder than other thermostates, but not that you will wake up, when it´s adjusting itself.. Unless you have a really light sleep.

**Comment by sti0** [comment]
I want to install it at my daughters room. It should heat a half hour before wake up. With that noise she will wake up immediately... I contacted the manufacture maybe a product failure. Right now I got a AVM Fritz 301 DECT on this radiator and this one is really quiet. (but could not be controlled instantly combined with window sensors).

**Comment by sti0** [comment]
Ok my fault. As learned by #63 a change in zigbee-shepherd/herdsman shows no new commit on zigbee2mqtt... (sounds logical). 

Climate entity + battery level is now pushed to HA. 

Think we're done here :) Thanks.

**Comment by sti0** [comment]
@Koenkk 
Is it possible to change HA state according to the zigbee2mqtt/[device]/set payload {"eurotronic_system_mode": XX} as mentioned in https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html ? Actually the state is always unknown.  
Changing the actions at the climate entity have no impact.
![image](https://user-images.githubusercontent.com/18382402/66519310-5ec7ad00-eae7-11e9-9965-cb8bf8f28868.png)

Its possible to set the device to off by setting {"eurotronic_system_mode": 32}. Is it possible to set this through the HA frontend (Action = off)? Even if the device is in normal heat or boost mode the state should be "heat".

**Comment by Koenkk** [comment]
@sti0 dor this you should adapt the toZigbee converters to resond to the correct attribute.

**Comment by Koenkk** [comment]
In toZigbee.js

**Comment by sti0** [comment]
Ok thanks. I will look into it and maybe come back to you if I have further questions :)
