### ISSUE TITLE
Inovelli Blue - Missing triggers. multiple related issues

### ISSUE THREAD

**Issue by wayne47git** [Koenkk/zigbee2mqtt#20943]
### What happened?

I'm thinking that the device interview is incomplete for Inovelli.

- Some triggers on Inovelli Blue switches are not available on initial paring. The specific trigger must be tripped, at which point, that individual trigger becomes available on that device. 
- This means that if a user wants to define double-up and double-down (etc.) events available in the "Add automation" menu for a new device, the user must pair the switch, then go to the switch and cause each desired trigger (_e.g._ double-up and a double-down), then return to the HA menu and define the automations, as the triggers will now be available in the dropdown.
- If an automation is already defined for one of these events and the the addon is restarted, all multi-tap triggers become undefined, so existing automations fail until the desired trigger is tripped. This means that on every addon restart, the user must go to each device and cause each multi-tap that is being used as a trigger. None of these initial triggers will cause anything to happen but this process causes the addon to realize that those triggers are now available at which point it re-associates the automation with the trigger and future triggers of that event on that device will work.

### What did you expect to happen?

All supported triggers to be available on initial pairing and after addon restart.

### How to reproduce it (minimal and precise)

Pair a new Inovelli Blue switch to cause the first problem.
Restart the addon with a multi-tap event associated with a Inovelli Blue switch.

### Zigbee2MQTT version

1.35.1-1

### Adapter firmware version

0.1.5 (2023-09-06 12:01:02.723464)

### Adapter

ZigStar UZG-01

### Setup

HA Addon

**Comment by stevemsefton** [comment]
same issue here
