### ISSUE TITLE
[New device support]: Frient Smart Humidity Sensor HMSZB-120

### ISSUE THREAD

**Issue by FabyGege** [Koenkk/zigbee2mqtt#20946]
### Link

https://frient.com/products/smart-humidity-sensor/

### Database entry

{"id":18,"type":"EndDevice","ieeeAddr":"0x0015bc0035002335","nwkAddr":1010,"manufId":4117,"manufName":"frient A/S","powerSource":"Battery","modelId":"HMSZB-120","epList":[1,38],"endpoints":{"1":{"profId":49353,"epId":1,"devId":1,"inClusterList":[3,5,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"38":{"profId":260,"epId":38,"devId":770,"inClusterList":[0,1,3,32,1026,1029],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{}},"genPollCtrl":{"attributes":{"checkinInterval":14400}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0xb4e3f9fffe947952","endpointID":1}],"configuredReportings":[],"meta":{}}},"dateCode":"20231025 18:44","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1705938271910,"defaultSendRequestWhen":"active","checkinInterval":3600}

### Comments

I'm trying to follow the supported device page, but I'm afraid I'll make a mistake that will crash my installation. Please do the integration. Thank you.

### External defintion

```shell
const {onOff, batteryPercentage, temperature, humidity, identify} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['HMSZB-120'],
    model: 'HMSZB-120',
    vendor: 'frient A/S',
    description: 'Automatically generated definition',
    extend: [onOff({powerOnBehavior: false}), batteryPercentage(), temperature(), humidity(), identify()],
};

module.exports = definition;
```

**Comment by sjorge** [comment]
I think we can just copy:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/6a0797ab702db6d92113bd1389f1ca29933c4ede/src/devices/develco.ts#L730-L746

This block, it's the previous version and I don't see any new features.

**Comment by FabyGege** [comment]
No it's a model with temperature sensor.

**Comment by sjorge** [comment]
> No it's a model with temperature sensor.

Then you should just be able to copy that one and update the model and zigbeeModel.

**Comment by FabyGege** [comment]
All right. but where should I copy this file? Or just the highlighted block?

**Comment by sjorge** [comment]
```node
import * as constants from '../lib/constants';
import * as exposes from '../lib/exposes';
import fz from '../converters/fromZigbee';
import tz from '../converters/toZigbee';
const e = exposes.presets;
const ea = exposes.access;

const develco = {
    configure: {
        read_sw_hw_version: async (device: Zh.Device, logger: Logger) => {
            for (const ep of device.endpoints) {
                if (ep.supportsInputCluster('genBasic')) {
                    try {
                        const data = await ep.read('genBasic', ['develcoPrimarySwVersion', 'develcoPrimaryHwVersion'],
                            manufacturerOptions);

                        if (data.hasOwnProperty('develcoPrimarySwVersion')) {
                            device.softwareBuildID = data.develcoPrimarySwVersion.join('.');
                        }

                        if (data.hasOwnProperty('develcoPrimaryHwVersion')) {
                            device.hardwareVersion = data.develcoPrimaryHwVersion.join('.');
                        }
                    } catch (error) {/* catch timeouts of sleeping devices */}
                    break;
                }
            }
        },
    },
};

const definition =  {
        zigbeeModel: ['HMSZB-110'],
        model: 'HMSZB-110',
        vendor: 'Develco',
        description: 'Temperature & humidity sensor',
        fromZigbee: [fz.battery, develco.fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.battery_low(), e.temperature(), e.humidity()],
        meta: {battery: {voltageToPercentage: '3V_2500_3200'}},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(38);
            await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg']);
            await reporting.temperature(endpoint, {min: constants.repInterval.MINUTE, max: constants.repInterval.MINUTES_10, change: 10});
            await reporting.humidity(endpoint, {min: constants.repInterval.MINUTE, max: constants.repInterval.MINUTES_10, change: 300});
            await reporting.batteryVoltage(endpoint, {min: constants.repInterval.HOUR, max: 43200, change: 100});
            await develco.configure.read_sw_hw_version(device, logger);
        },
    };

module.exports = definition;
```

Try with this one, I didn't test it as I am not at home now.

**Comment by FabyGege** [comment]
I'm sorry but I don't know where to put this file. Thank you for your help.

**Comment by sjorge** [comment]
> I'm sorry but I don't know where to put this file. Thank you for your help.

Copy the content into `hsmsb120.js` (Different name also OK as long as it ends in .js) and put it in the data/ directory from zigbee2mqtt.

Then update your configuration.yaml to include:

```
external_converters:
  - hsmsb120.js
```

If z2m gives an error starting up, undo the change to configuration.yaml.

**Comment by FabyGege** [comment]
OK. I will try and come back for the results

**Comment by FabyGege** [comment]
I did the test without success. the module is still recognized as Frient and the model is HMSZB-120 and not HMSZB-110 as in the definition.

**Comment by sjorge** [comment]
🤦‍♂️ I of course forgot to swap the model name! I’ve updated the previous comment.

**Comment by FabyGege** [comment]
So i'll try again. Thanks

**Comment by FabyGege** [comment]
Always nothing. I restarted zigbee first with no results. I then restarted the installation and did an inclusion each time without success. I will remove the file and undo the change in configuration.yaml. Note: my installation is under Jeedom

**Comment by sjorge** [comment]
I'm not sure how, or if you can load an external converter with jeedom. I'm fairly confident that the device definition is correct though, based on past experiences. I'll do a PR and then it should up in the next version.

**Comment by FabyGege** [comment]
Ok. thank you

**Comment by FabyGege** [comment]
Thank You for the job. It works well. It's not the right image but it doesn't matter. I close the topic

**Comment by FabyGege** [comment]
Thank you for the job. It works well. It's not the right image but it doesn't matter. I close the topic
