### ISSUE TITLE
[New device support]: Bosch devices Gen 1, 65 Char Installation codes

### ISSUE THREAD

**Issue by acosys** [Koenkk/zigbee2mqtt#20954]
### Link

https://www.bosch-smarthome.com/de/de/service/hilfe/hilfe-zum-produkt/hilfe-zum-tuer-fensterkontakt/

### Database entry

-

### Comments

Z2M actually supports Bosch devices with installation codes with >90 chars.
But what about devices of the first generation? They has codes with 65 chars, but Z2M do not support installation codes with this numbers of chars. Is it possible to change this to support these devices in principle? 

### External defintion

```shell
-
```

**Comment by danielpetrovic** [comment]
Most gen1 devices are not Zigbee, they run on 868Mhz . Which is why many gen1 devices are not supported on the Bosch SHC II either, as that lacks built in 868Mhz support.
