### ISSUE TITLE
[New device support]: Tuya TS0003 - manufacturer _TZ3000_lvhy15ix

### ISSUE THREAD

**Issue by darkobg79** [Koenkk/zigbee2mqtt#20961]
### Link

https://www.aliexpress.com/item/1005005748264739.html?spm=a2g0o.order_list.order_list_main.23.64dd1802kls5wR

### Database entry

{"id":140,"type":"Router","ieeeAddr":"0xa4c138a168d0e03b","nwkAddr":53127,"manufId":4417,"manufName":"_TZ3000_lvhy15ix","powerSource":"Mains (single phase)","modelId":"TS0003","epList":[1,2,3,242], "endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10], "clusters":{"genBasic":{"attributes":{"65503":"�\\B-\u0012\u0006\u0000\u0000\u0000\u0012","65506":56,"65508":0,"65534":0,"stackVersion":0,"dateCode":"", "manufacturerName":"_TZ3000_lvhy15ix","zclVersion":3,"appVersion":72,"modelId":"TS0003","powerSource":1}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":2, "tuyaBacklightMode":1}},"manuSpecificBosch":{"attributes":{"53251":"AAAAAgAABAAA"}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"switchType":0}}}, "binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xdc8e95fffe2578b3","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0xdc8e95fffe2578b3","endpointID":1}, {"cluster":0,"type":"endpoint","deviceIeeeAddress":"0xdc8e95fffe2578b3","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}], "meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}}, "binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xdc8e95fffe2578b3","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1, "manufacturerCode":null}],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[4,5,6],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}}, "binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xdc8e95fffe2578b3","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1, "manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0, "hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-150731130},"lastSeen":1706025713430}

### Comments

Hi,

please can you add new manufacturer for [TS0003_switch_module_2](https://www.zigbee2mqtt.io/devices/TS0003_switch_module_2.html#tuya-ts0003_switch_module_2). I can confirm that everything working. This is model with 3 channel.

New manufacturer is:  _TZ3000_lvhy15ix

    modelID: 'TS0003'
    model: 'TS0003_switch_module_2'
    manufacturerName: '_TZ3000_lvhy15ix'

 Thank you.

### External defintion

```shell
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;
const globalStore = require('zigbee-herdsman-converters/lib/store');

const definition = {
    fingerprint: [{
            modelID: 'TS0003',
            manufacturerName: '_TZ3000_lvhy15ix'
        }
    ],
    model: 'TS0003_switch_module_2',
    vendor: 'TuYa',
    description: '3 gang switch module',
    extend: tuya.extend.switch({
        switchType: true,
        endpoints: ['l1', 'l2', 'l3']
    }),

    endpoint: (device) => {
        return {
            'l1': 1,
            'l2': 2,
            'l3': 3
        };
    },
    meta: {
        multiEndpoint: true
    },
    configure: async(device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
