### ISSUE TITLE
zigbee2mqtt/bridge/config/reset  answers Fail.

### ISSUE THREAD

**Issue by domo86** [Koenkk/zigbee2mqtt#2096]
zigbee2mqtt : 1.6.0
CC2531 : 20190608 ( DEFAULT )
+ Home assistant

The MQTT command "zigbee2mqtt/bridge/config/reset" answers Fail.
I need it because I'm faced with issues with CC2531 which runs for a day, then stops running.

10/7/2019, 8:30:56 PM - debug: Received MQTT message on 'zigbee2mqtt/bridge/config/reset' with data ''
10/7/2019, 8:31:16 PM - error: Soft reset failed

If somebody could help?
Thanks a lot.

**Comment by Koenkk** [comment]
When the stick crashed  this indeed fails, your real issue is #2095
