### ISSUE TITLE
Xiaomi DLKZMK11LM Aqara single switch module T1 (with neutral) - Does not responsd to Turn On / Off

### ISSUE THREAD

**Issue by verticalsoft** [Koenkk/zigbee2mqtt#20974]
### What happened?

Since updating to 1.35.1 I can no longer toggle the Xiaomi DLKZMK11LM Aqara single switch module T1
It shows as online and if i manually toggle it via a hard wired switch the state is reported correctly.

I also have the Xiaomi SSM-U01 Aqara single switch module T1 (with neutral) which looks identical and works as expected.

### How to reproduce it (minimal and precise)

Toggle the on off from withing Home Assistant or Zigbee2MQTT front end.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20221226

### Adapter

Tubes POE

### Setup

Home Assiant Addin

### Debug log

Zigbee2MQTT:error 2024-01-24 08:09:03: Publish 'set' 'state' to 'Office Server Light' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:09:12: Publish 'set' 'state' to 'Office Server Light' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:09:29: Publish 'set' 'state' to 'Office Server Light' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:09:41: Publish 'set' 'state' to '0x54ef4410009249d7' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:10:07: Publish 'set' 'state' to '0x54ef4410009249d7' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:10:33: Publish 'set' 'state' to '0x54ef4410009249d7' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:11:01: Publish 'set' 'state' to '0x54ef4410009249d7' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:11:27: Publish 'set' 'state' to '0x54ef4410009249d7' failed: 'Error: Command 0x54ef4410009249d7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:error 2024-01-24 08:11:37: Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device 'Office Server Light' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms)'

**Comment by Clem-** [comment]
Might be similar to [!20526 No network route](https://github.com/Koenkk/zigbee2mqtt/issues/20526).

**Comment by IDmedia** [comment]
@verticalsoft 

I struggle with the same, did you ever find a solution?
