### ISSUE TITLE
 Tz.Converter and Fz.Converter cannot be used in Custom converter

### ISSUE THREAD

**Issue by Nailik** [Koenkk/zigbee2mqtt#20980]
### What happened?

Hi,

i tried creating a custom converter to test if it works correctly before opening a pull request.
However i need to access  `Tz.Converter` and `Fz.Converter` but it can't be access because 
`import {Definition, Fz, Tz, KeyValue}` from 'zigbee-herdsman-converters/lib/types';
results in `cannot use import statement outside a module`.

### What did you expect to happen?

Being able to import necessary definitions

**Comment by Koenkk** [comment]
You don't need to use these in the external converter, (so remove `satisfies Tz.Converter` from it)

**Comment by Koenkk** [comment]
You don't need it in a `.js` file, `Tz.Converter` is just typing information for `.ts` files only. There is no downside of not using it.

**Comment by Nailik** [comment]
Thanks looking at this https://github.com/Koenkk/zigbee-herdsman-converters/issues/5635 helped me.
