### ISSUE TITLE
Regression with Develco SPLZB-131

### ISSUE THREAD

**Issue by paranoidi** [Koenkk/zigbee2mqtt#20992]
### What happened?

After some update (I do not know which) all my SPLZB-131 sockets started reporting power consumption incorrectly where as previously they worked perfectly.

### What did you expect to happen?

Reported "Instantaneous measured power" should be correct. It seems to be off by orders of magnitude.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on home assistant OS

**Comment by fschaal** [comment]
Same here. My PC and 2 monitors are connected to the plug but It's saying power of 0.11W.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/3596547/28de9046-1b90-4db1-9e76-f25d296c3a52)

**Comment by oerik** [comment]
I had the same, removing the device and pair it again solved the wrong power measurement.

**Comment by paranoidi** [comment]
Issue was solved by upgrading the sockets firmware.
