### ISSUE TITLE
Permit join does not work on some devices. How do we find the cause?

### ISSUE THREAD

**Issue by mrmaximas** [Koenkk/zigbee2mqtt#21008]
### What happened?

I was experimenting with my free spare xiaomi and other devices like
 [WXKG01LM](https://www.zigbee2mqtt.io/devices/WXKG01LM.html#xiaomi-wxkg01lm)  
[ZNCZ02LM](https://www.zigbee2mqtt.io/devices/ZNCZ02LM.html#xiaomi-zncz02lm)
[RTCGQ01LM](https://www.zigbee2mqtt.io/devices/RTCGQ01LM.html#xiaomi-rtcgq01lm) 
[QS-Zigbee-D02-TRIAC-L_1](https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-L_1.html#lonsonho-qs-zigbee-d02-triac-l_1)
[ZWSM16-1-Zigbee](https://www.zigbee2mqtt.io/devices/ZWSM16-1-Zigbee.html#avatto-zwsm16-1-zigbee)
and found that not all routers on my network go into pairing mode.

### What did you expect to happen?

I expected that the new device can be paired with any router in my network, switched to pairing mode individually. With some routers like [ZWSM16-1-Zigbee](https://www.zigbee2mqtt.io/devices/ZWSM16-1-Zigbee.html#avatto-zwsm16-1-zigbee) or [ZWSM16-2-Zigbee](https://www.zigbee2mqtt.io/devices/ZWSM16-2-Zigbee.html#avatto-zwsm16-2-zigbee) even at a distance of 10 cm from the new paired device can not pass interviews. Visually nothing happens. It looks like the individually selected router is not in pairing mode. At the same time, the new devices perfectly paired with other router devices in the network.

### How to reproduce it (minimal and precise)

You should try pairing the new device with a individually router device in the network.

### Zigbee2MQTT version

1.35.1-dev commit: 51897288

### Adapter firmware version

20230922

### Adapter

Sonoff ZBDONGLE-P

### Setup

Mac OS catalina latest

**Comment by Koenkk** [comment]
The [coordinator check](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-coordinator-check) might help.

**Comment by mrmaximas** [comment]
> The [coordinator check](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-coordinator-check) might help.

how to do it via web ui?

**Comment by mrmaximas** [comment]
> The [coordinator check](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request-coordinator-check) might help.

{
  "data": {
    "missing_routers": []
  },
  "status": "ok"
}

**Comment by Koenkk** [comment]
This may then be some issues of the specific router, to figure this out traffic needs to be [sniffed](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html)
