### ISSUE TITLE
New device "ZLL-ColorTempera"

### ISSUE THREAD

**Issue by ptath** [Koenkk/zigbee2mqtt#2101]
Hello, new device:

> окт 08 19:27:26 dragon-hub npm[609]:   zigbee2mqtt:warn 2019-10-8 7:27:26 PM Device with modelID 'ZLL-ColorTempera' is not supported.

Looks like usual Trust lightbulb with color temperature regulation. Now trying to add it manually, but sure it should be an easier way =)

So here is it: https://github.com/Koenkk/zigbee-shepherd-converters/pull/676/commits/35d6f67f5657abe7bf9486065b70731e9fe5a88e Works fine

**Comment by Koenkk** [comment]
Added by https://github.com/Koenkk/zigbee-shepherd-converters/pull/674/files#diff-6c9a6acf22f90d1c6e524d9f3c5c1745R3277; will be supported in the dev branch soon.
