### ISSUE TITLE
Error when changing Measurement Pool Interval in Tuya BSD29_1

### ISSUE THREAD

**Issue by felipebraz** [Koenkk/zigbee2mqtt#21018]
### What happened?

I'm trying to change an specific configuration (Measurement Pool Interval) of the my Tuya BSD29_1

![image](https://github.com/Koenkk/zigbee2mqtt/assets/14303499/a68b5d9f-a601-490f-81c3-cba2b3614080)

After I added a value on this field this error start appearing: "Failed to apply calibration to 'power': 'power_calibration' is not a number, got string ()"

I already tried to go back to original value (empty) and filling the mentioned field (Power calibration) but this message keeps constantly appearing, even going back to the default values (all empty)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/14303499/cb9cdda3-4651-4b9d-a745-5453afc80e71)

### What did you expect to happen?

The pool interval being updated.

### How to reproduce it (minimal and precise)

Change the value on this field.

### Zigbee2MQTT version

1.35.1-1

### Adapter firmware version

20221226

### Adapter

Sonoff zigbee 3.0 usb dongle plus

### Setup

x86-64 containerized

**Comment by felipebraz** [comment]
Oh and changing the value the Measurement Pool Interval doesn't affect the update frequency.

**Comment by nARN** [comment]
I believe the error is not specific to the polling interval. It is caused by the empty power calibration field, right under polling. I suspect you focused on it after changing the polling interval and then unfocused, which is when, apparently, the UI attempt to update the configuration.

In this case the problem is that upon update an empty field is treated as an empty string instead of "use the default value", which it represented originally.

**Comment by nARN** [comment]
Regarding the apparent lack of reaction to your changes, it seems that you need to restart zigbee2mqtt to apply the new polling interval. I filed #21371 for that.

**Comment by Skallwar** [comment]
I noticed that anything under 30 seconds will not report anything back anymore

**Comment by nARN** [comment]
@Skallwar That's not my experience. After a restart, values as low as 1 second work like a charm. I actually see updates every second.

FWIW, my plug is model `TS011F`, manufacturer `_TZ3000_okaz9tjs`, app version `100`, which makes it `TS011F_plug_3`, IIUC.

**Comment by Skallwar** [comment]
I did not find the app version but other than that I have the same plug. I will try to put it closer to my usb dongle, maybe that's the issue, I have a 79 which is a tad low

**Comment by Skallwar** [comment]
Okay my bad, that was just a bad connection
