### ISSUE TITLE
Danfoss 	014G2461/014G2463

### ISSUE THREAD

**Issue by jhaveDK** [Koenkk/zigbee2mqtt#21026]
### What happened?

I have made a OTA update but now its shows AAAABBBBCCCCDDDD on some of the devices, its a mix of the new hardware version and the old one. 

<img width="820" alt="danfoss" src="https://github.com/Koenkk/zigbee2mqtt/assets/1891208/b5723e24-4e74-4194-b4fc-03fed2527052">

### What did you expect to happen?

Correct firmware version 

### How to reproduce it (minimal and precise)

OTA opdate 

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

 20230507

### Adapter

SLZB-06

### Setup

Z2M/HA on a VM (proxmox)

**Comment by shawly** [comment]
I have the same issue with my [014G2461](https://www.zigbee2mqtt.io/devices/014G2461.html#danfoss-014g2461). Removing the device from Z2M, restarting Z2M and then pairing the device again works for me usually.
