### ISSUE TITLE
No connection after server reboot

### ISSUE THREAD

**Issue by Xsev1** [Koenkk/zigbee2mqtt#2106]
Hello,
My coordinator lost connection after each reboot (reproducible).
I tested on my own server an a second installation by a friend. We run the maxstability 20190315 whitout problems for some months. After upgrade 20190610, you can pair everything, all ok but after rebooting your server the zigbee never connect again.
Testet hardware and versions:
-CC2531 Pi + Nuc (Debian) ioBroker
-CC2530-2591 Pi ioBroker
-Home1.2
-Source Routing 1.2
-Z-stack3

The new coordiantor firmware works fine at beginning but if i restart my server, it lost connection and i must repair the complete Network. This bug i had never before with an older coordinator firmware.
Thats a very big problem for me.

**Comment by Koenkk** [comment]
For iobroker issues please use the iobrokker issue tracker: https://github.com/ioBroker/ioBroker.zigbee/issues
