### ISSUE TITLE
Cannot read properties of null for update. All devices are requesting OTA in loop whole day

### ISSUE THREAD

**Issue by Hadatko** [Koenkk/zigbee2mqtt#21074]
### What happened?

All zigbee devices (OSRAM, Philips) are requesting OTA whole day. Manuall check is failing.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/13130700/18b579c2-e589-4a7d-a4bb-f8bfb6a6d584)

### What did you expect to happen?

Check for update do not trigger error

### How to reproduce it (minimal and precise)

pres ota button check for ota 

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

7.1.1.0 build 273

### Adapter

skyconnect

### Setup

addon in HA

### Debug log

```
Error 2024-01-27 20:32:14Failed to check if update available for 'chodba_3_svetlo_scena' (Cannot read properties of null (reading '1'))
Debug 2024-01-27 20:32:14TypeError: Cannot read properties of null (reading '1') at getImageMeta (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/ledvance.ts:25:55) at processTicksAndRejections (node:internal/process/task_queues:95:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:398:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:387:29) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:45) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17)
```

**Comment by Hadatko** [comment]
In log above is present also error which happen when i try manually check update

**Comment by Koenkk** [comment]
Can you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.
