### ISSUE TITLE
Nodon_SIN-4-RS-20_ Calibration 

### ISSUE THREAD

**Issue by moshiko2312** [Koenkk/zigbee2mqtt#21077]
### Is your feature request related to a problem? Please describe

hi I got the parameter calibration for the SIN-4-RS-20, can you please add this parameter

### Describe the solution you'd like

<img width="683" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/48163773/93ba2d60-2fba-486b-9120-b40d5d6b9e04">

### Describe alternatives you've considered

<img width="693" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/48163773/f184a7f8-ae34-4d36-95e5-0e982fae94d5">

### Additional context

Thanks

**Comment by lippertmarkus** [comment]
Implemented with https://github.com/Koenkk/zigbee-herdsman-converters/pull/7547

**Comment by acasajus** [comment]
Where did you get the protocol specs? I'd like to take a look 👁️

**Comment by moshiko2312** [comment]
From the nodon company
