### ISSUE TITLE
My network map looks...weird. Is my network the cause of slow response times?

### ISSUE THREAD

**Issue by timdonovanuk** [Koenkk/zigbee2mqtt#2107]
Motion sensors on my network sometimes are very slow to respond. Is there an issue with my network? Does it normally look so crazy like this, with lots of devices?

![image](https://user-images.githubusercontent.com/8156439/66472860-07452500-ea86-11e9-8bbf-34b584f5cf99.png)

**Comment by Koenkk** [comment]
Can you check with the latest dev branch?

**Comment by bochelork** [comment]
At least you have a lot of lines! Here I only have one end device with lines. Actually this device is offline since I last started zigbee2mqtt....
![download](https://user-images.githubusercontent.com/31744211/66555557-2bb90400-eb4f-11e9-8963-a90d524f1d57.png)

**Comment by carldebilly** [comment]
@bochelork did you try to compare with the map from https://github.com/yllibed/Zigbee2MqttAssistant ?

**Comment by bochelork** [comment]
> @bochelork did you try to compare with the map from https://github.com/yllibed/Zigbee2MqttAssistant ?

Haven't installed assistant yet. Running zigbee2mqtt on my synology (Realtek RTD1293 CPU). Can I install the assistant on a different machine?

**Comment by carldebilly** [comment]
You can install it anywhere, as soon it can connect to the MQTT server...

**Comment by james-fry** [comment]
@carldebilly - just tried Z2MA map and it really nice :) great work!
(I have some enhancement suggestions such as colors, but I think its a great start)

I have exactly the same missing connections (from end devices to router) in all the maps, hence I assume it must be down to the data being provided by Z2M to the renderer:

![image](https://user-images.githubusercontent.com/5823294/66666456-8f732800-ec48-11e9-9556-dcf869f71fcb.png)

![image](https://user-images.githubusercontent.com/5823294/66666475-94d07280-ec48-11e9-947d-74a1cfbcf5b7.png)

![image](https://user-images.githubusercontent.com/5823294/66666487-9b5eea00-ec48-11e9-9d90-48a1f98052aa.png)

**Comment by carldebilly** [comment]
We can see there's no "link back" from routers to coordinator.

**Comment by bochelork** [comment]
![download (1)](https://user-images.githubusercontent.com/31744211/66673975-15e83380-ec62-11e9-95ae-b29a2da99d42.png)
