### ISSUE TITLE
IKEA STYRBAR Zigbee2Mqtt not working

### ISSUE THREAD

**Issue by guy561** [Koenkk/zigbee2mqtt#21080]
### What happened?

when you press any button nothing happens with an automation or with a blueprint

### What did you expect to happen?

I want my automation to work with the requested action (ex: left arrow pressed-->light on

### How to reproduce it (minimal and precise)

I bought several styrbars which are all in 1.0.0.24.
Once paired, I still couldn't use it. So I followed another post on GitHUb to update to version 2.4.5. Even with this recent version, no automation or blueprint works
I see in the logs the actions published but nothing happens...

Thanks for your help

### Zigbee2MQTT version

1.32.2-dev commit: 6050428

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3 USB

### Setup

Home Assistant OS in a VM under virtual box

### Debug log

Info 2024-01-28 11:08:43MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"on","battery":null,"last_seen":"2024-01-28T10:08:43.619Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:43MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"","battery":null,"last_seen":"2024-01-28T10:08:43.619Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:43MQTT publish: topic 'zigbee2mqtt/Styrbar 2/action', payload 'on'
Info 2024-01-28 11:08:45MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"off","battery":null,"last_seen":"2024-01-28T10:08:45.099Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:45MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"","battery":null,"last_seen":"2024-01-28T10:08:45.099Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:45MQTT publish: topic 'zigbee2mqtt/Styrbar 2/action', payload 'off'
Info 2024-01-28 11:08:46MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"arrow_left_click","battery":null,"last_seen":"2024-01-28T10:08:46.734Z","linkquality":111,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:46MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"","battery":null,"last_seen":"2024-01-28T10:08:46.734Z","linkquality":111,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:46MQTT publish: topic 'zigbee2mqtt/Styrbar 2/action', payload 'arrow_left_click'
Info 2024-01-28 11:08:48MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"arrow_right_click","battery":null,"last_seen":"2024-01-28T10:08:47.827Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:48MQTT publish: topic 'zigbee2mqtt/Styrbar 2', payload '{"action":"","battery":null,"last_seen":"2024-01-28T10:08:47.827Z","linkquality":114,"update":{"installed_version":33816581,"latest_version":581,"state":"idle"},"update_available":false}'
Info 2024-01-28 11:08:48MQTT publish: topic 'zigbee2mqtt/Styrbar 2/action', payload 'arrow_right_click'

**Comment by kvikindi** [comment]
Did you find a solution? If so, could you please share it?
