### ISSUE TITLE
Switched from Conbee to Skyconnect, some devices unable to pair

### ISSUE THREAD

**Issue by coax** [Koenkk/zigbee2mqtt#21101]
### What happened?

Replaced Conbee II with SkyConnect adapter (+USB extension cable), deleted configuration.yaml and database.db, added all the other Aqara devices again but my blinds motor controllers [Lonsonho QS-Zigbee-C03](https://www.zigbee2mqtt.io/devices/QS-Zigbee-C03.html) are unable to join, says unsupported. They all worked fine on Conbee and are officially supported.
I tried adding, force deleting, restarting (as suggested in other threads) to no avail. I have 9 of these and none can join sucessfully.

Zigbee2MQTT v1.35.1 (Docker container)
SkyConnect EZSP v7.1.1 (NCP), also tried with newer firmware versions like 7.3.2

![Screenshot 2024-01-29 at 17-04-30 Zigbee2MQTT](https://github.com/Koenkk/zigbee2mqtt/assets/189817/2ca8c830-634b-4358-b117-246f796b7b6c)

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

7.1.1

### Adapter

SkyConnect

### Setup

Intel NUC, Docker

### Debug log

**info** MQTT publish: topic 'zigbee2mqtt/0xa4c138883cb7d2e8/availability', payload '{"state":"online"}'
**info** MQTT publish: topic 'zigbee2mqtt/0xa4c138883cb7d2e8', payload '{"last_seen":"2024-01-29T16:52:54+01:00"}'
**info** Device '0xa4c138883cb7d2e8' joined
**info** MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138883cb7d2e8","ieee_address":"0xa4c138883cb7d2e8"},"type":"device_joined"}'
**info** Starting interview of '0xa4c138883cb7d2e8'
**info** MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138883cb7d2e8","ieee_address":"0xa4c138883cb7d2e8","status":"started"},"type":"device_interview"}'
**error** Failed to interview '0xa4c138883cb7d2e8', device has not successfully been paired
**info** MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c138883cb7d2e8","ieee_address":"0xa4c138883cb7d2e8","status":"failed"},"type":"device_interview"}'

**Comment by chris-1243** [comment]
Have you tried the latest-dev ? Some work has been made on ezsp support. It might help you

**Comment by coax** [comment]
I tried latest 1.35.1-dev commit: [7e7d3c6](https://github.com/Koenkk/zigbee2mqtt/commit/7e7d3c6) and same problem.

**Comment by chris-1243** [comment]
Do you have routers close to those devices ? You may try to use the "permit join via device" and select a router as close as possible.
Not really the best option but if you pair the device really close to the coordinator. I had such problem once and solved it this way

**Comment by coax** [comment]
I appreciate the help Chris. Managed to pair it via router. Unfortunately, that router isn't turned on all the time (ambilight on TV) but I'll get another one which will be.
