### ISSUE TITLE
Feature request: post log to mqtt

### ISSUE THREAD

**Issue by neographikal** [Koenkk/zigbee2mqtt#2110]
It would be nice to have the option to post the logging to a separate mqtt topic so that web interfaces like zigbee2mqttassistant are able to trail the logging.

**Comment by carldebilly** [comment]
It would be the _console output_ logging of Z2M, the one we can see by checking the container's log or the equivalent on HASS.IO.

**Comment by CodeFinder2** [comment]
Any chance that this will be included at some time? :see_no_evil:

**Comment by kennymc-c** [comment]
I would also love to see this feature in the future

**Comment by twsI** [comment]
Same. Only problem is the current structure, as the mqtt module is logging while inistializing itself. Otherwise I would have already created a merge request.
