### ISSUE TITLE
[New device support]: Ikea Tretakt Switch 805.403.49

### ISSUE THREAD

**Issue by DL4DP** [Koenkk/zigbee2mqtt#21115]
### Link

https://csa-iot.org/csa_product/tretakt-smart-plug/

### Database entry

Device '0x8c6fb9fffe143e7b' with Zigbee model 'TRETAKT Smart plug' and manufacturer name 'IKEA of Sweden' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### Comments

![Unbenannt](http![IMG_20240130_202119576](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/5e57b726-b86e-4cb0-847b-2018966b4a1f)

![Unbenannt](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/cb3776cb-3116-4d1b-82c3-9f8b186bee67)

![IMG_20240130_202130065](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/bd49f072-042d-471c-8e79-2342ab7a2218)

![IMG_20240130_202148693](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/ed58149a-79f5-46b9-9e93-02beeb515b3f)

![IMG_20240130_202410917](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/7faffff9-01fc-48ee-a7a8-b36426dd2688)

### External defintion

```shell
TRETAKT Smart plug

Firmware date 20230206
Firmware version 2.4.4

IKEA of Sweden
Support status Unsupported

Device '0x8c6fb9fffe143e7b' with Zigbee model 'TRETAKT Smart plug' and manufacturer name 'IKEA of Sweden' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

According to the instructions I couldn't do it, unfortunately!

Received message from unsupported device with Zigbee model 'TRETAKT Smart plug' and manufacturer name 'IKEA of Sweden'

Hello everyone,

Since today I am the proud owner of the Tretract socket from Ikea 805.403.49.

This is probably a brand new socket from Ikea, unfortunately zigbee2mqtt says it doesn't support it. Can you insert them?

The new socket cannot even be found in the Ikea online shop.

Thanks! For your help, I suspect the devices will soon replace the old socket and then will definitely be sold and used a lot.

I would be happy if the socket was supported!

Thank you Dirk!
```

**Comment by Koenkk** [comment]
Please check if it works out-of-the-box with z2m 1.35.1

**Comment by DL4DP** [comment]
Hello and thank you for the feedback.

I updated my zigbee2mqtt to 1.35.1, I was really a bit behind in the version. Unfortunately the sockets are still not installed correctly. I deleted them and retrained them. Unfortunately it still doesn't work properly. I don't know if it's due to the firmware version of the socket. Maybe someone else has another solution to my problem.

Thank you Dirk

**Comment by Koenkk** [comment]
What do you get in the about screen with 1.35.1?

**Comment by DL4DP** [comment]
Hello and thank you for the feedback, do you mean this information?

- Zigbee2MQTT-Version:  [1.35.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.1)  commit: [4b6f50da](https://github.com/Koenkk/zigbee2mqtt/commit/4b6f50da)
- Coordinator-Typ:  EZSP v12
- Coordinator-Version: 7.3.1.0 build 176
- Coordinator IEEE Adresse: 0xe0798dfffeaabf1d
- Frontend-Version: 0.6.151
- Zigbee-herdsman-converters version: 18.9.0
- Zigbee-herdsman version: 0.30.0

**Comment by Koenkk** [comment]
I mean of the z2m frontend -> click on device -> about screen.

**Comment by DL4DP** [comment]
- Gerätename: 0x8c6fb9fffe143e7b

- Zuletzt gesehen:
 N/A
- Verfügbarkeit: [Deaktiviert](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
- Geräte-Typ: Router
- Zigbee-Modell: TRETAKT Smart plug
- Zigbee-Hersteller: IKEA of Sweden
- Unterstützungsstatus: Nicht unterstützt [(How to add support)](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html)
- IEEE-Adresse:  0x8c6fb9fffe143e7b
- Netzwerk-Adresse: 0x108D
- Firmware-Datum: 20230206
- Firmware-Version: 2.4.4
- Interview erfolgreich: Trifft zu

**Comment by Koenkk** [comment]
What is shown under the exposes tab?

**Comment by DL4DP** [comment]
Hello and thank you for the response, unfortunately I was away for a few days and am only now replying.

I took some pictures of the screen, I hope you find the information you are looking for.

![1](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/c12c8a0b-073a-47e4-8d84-5153b504dc01)

![2](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/7bd12168-388c-4a88-ac9f-9df3e9362666)

![3](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/3e44af18-12fd-438d-8f71-ed84973d4aac)

![4](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/c776b1db-5dfa-471b-93be-35ba3599145d)

![5](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/23b360f4-aac7-42f4-a469-eda02137ed1b)

![6](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/a9dc8d2a-fc56-4c41-9036-d0247619c85d)

![7](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/fd8f43cf-9159-4841-803f-fde94df3fdce)

![8](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/61ce357c-40ca-4407-9b9f-4a74993f5564)

![9](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/cf4d2076-19f5-48d7-946d-b11463089d85)

![10](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/ac9bf354-63d8-45c7-9286-fb98c449b130)


Thank you for your help, support and time.

Dirk

**Comment by Koenkk** [comment]
Does it work when changing the state under the exposes tab?

**Comment by DL4DP** [comment]
![100](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/991c80a7-219d-42b7-baf6-20e1c04a625b)

![101](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/c1a150ac-8d75-4ad7-ac65-e965c9a2cbfc)

![102](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/1de69e9b-516e-4af8-8da0-f43ffe3ede82)

![103](https://github.com/Koenkk/zigbee2mqtt/assets/101423128/df7768d2-bff9-4b0f-8724-a5ce2567130c)

The socket is also switched, and the "linkquality" values also change again and again.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
