### ISSUE TITLE
Issues with Sonoff SNZB-0 devices

### ISSUE THREAD

**Issue by gcardy** [Koenkk/zigbee2mqtt#21141]
### What happened?

I have been running into some  issues lately, specifically with my Sonoff SNZB devices.  I have multiple SNZB 01,02,03, and 04 devices on my network, as well as 9 Inovelli VZM31-SNs. What I have noticed lately is that 1 of my SNZB-02s is constantly dropping off the network and needs to be power cycled and/or force removed and re-added in order for it to start working again. This SNZB-02 is located roughly 3 meters away from a Inovelli VZM31-SN and roughly 5 meters away from the USB Dongle Plus V2.  What I have noticed with the SNZB-03s, is that they are constantly configuring themselves and then failing with the following message:

```
Failed to configure 'diningroom_motion', attempt 1 (Error: {"address":15570,"clusterId":32801,"sequence":75} after 10000ms at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at Driver.zdoRequest (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:667:43) at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:566:13 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:342:13) at Configure.configure (/app/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

I have added the ext_converter.js that I found recommended in multiple other issues, and it seems that may have resolved one of the issues that I was having with an SNZB-01 device. Though I did wind up force removing and re-adding that device before it started working.  The error for the SNZB-01 was:

```
error 2024-02-01 09:24:56: Failed to configure 'office_curtain_button', attempt 1 (Error: {"address":6717,"clusterId":32801,"sequence":104} after 10000ms
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at Driver.zdoRequest (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:667:43)
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:566:13
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:252:13)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

I did upgrade to the latest-dev per the instructions for creating an issue, and I have attached multiple versions of the debug logs to this issue.  I can provided any additional information that can assist in understanding what is happening here.

### What did you expect to happen?

Devices are fully configured after the first attempt. 

### How to reproduce it (minimal and precise)

I'm not sure if there is a way to reproduce this on another setup. I'm seeing these messages across zigbee2mqtt versions (I went back to 1.33.x before posting this to see if I could resolve the errors.  I don't recall seeing them in the past and I upgraded my zigbee2mqtt version at the beginning of 2024 (I don't have a way to go back and check the previous version).

### Zigbee2MQTT version

1.35.2 commit: 06b3395

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Zigbee 3.0 USB Dongle Plus V2 model (ZBDongle-E)

### Setup

Plain, containerized via Docker

### Debug log

Had to include my config in .txt or it wouldn't upload
[configuration.txt](https://github.com/Koenkk/zigbee2mqtt/files/14129312/configuration.txt)

[1.35.1.log](https://github.com/Koenkk/zigbee2mqtt/files/14129287/1.35.1.log)

[latest-dev.log](https://github.com/Koenkk/zigbee2mqtt/files/14129282/latest-dev.log)

[1.35.2.log](https://github.com/Koenkk/zigbee2mqtt/files/14129313/1.35.2.log)

[1.35.2 herdsman-debug.log](https://github.com/Koenkk/zigbee2mqtt/files/14129513/herdsman-debug.log)

**Comment by josemaX** [comment]
This happens me with all zigbee devices after upgrading. Restarted HA, cut power at home. Nothing solved. Restoring 1.35.1-1 makes all work again. Using conbee II as coordinator if it matters.

**Comment by gcardy** [comment]
> This happens me with all zigbee devices after upgrading. Restarted HA, cut power at home. Nothing solved. Restoring 1.35.1-1 makes all work again. Using conbee II as coordinator if it matters.

Interesting.  I did rollback this AM to 1.33.0, but still seeing the same errors.  I suppose that I should turn herdsman debugging on and try the rollback again.  Did you have to do anything after rolling back?  Removing previous state, etc?

**Comment by LucidityCrash** [comment]
remember that after an upgrade in order for the configure device step to work the device needs to be awake ... these battery devices are no awake all the time ... try actually using the button/triggering the motion detectors it might help ?

**Comment by gcardy** [comment]
> remember that after an upgrade in order for the configure device step to work the device needs to be awake ... these battery devices are no awake all the time ... try actually using the button/triggering the motion detectors it might help ?

That is part of the problem, when the devices "wake up," they try to configure themselves and that is when the error messages arrive in the logs.

**Comment by josemaX** [comment]
> > This happens me with all zigbee devices after upgrading. Restarted HA, cut power at home. Nothing solved. Restoring 1.35.1-1 makes all work again. Using conbee II as coordinator if it matters.
> 
> Interesting. I did rollback this AM to 1.33.0, but still seeing the same errors. I suppose that I should turn herdsman debugging on and try the rollback again. Did you have to do anything after rolling back? Removing previous state, etc?

For me, every device failed (wall and battery powered, no one worked). I did nothing more that restore the previous Zigbee2MQTT (backup) and everything worked again.

**Comment by gcardy** [comment]
> > > This happens me with all zigbee devices after upgrading. Restarted HA, cut power at home. Nothing solved. Restoring 1.35.1-1 makes all work again. Using conbee II as coordinator if it matters.
> > 
> > 
> > Interesting. I did rollback this AM to 1.33.0, but still seeing the same errors. I suppose that I should turn herdsman debugging on and try the rollback again. Did you have to do anything after rolling back? Removing previous state, etc?
> 
> For me, every device failed (wall and battery powered, no one worked). I did nothing more that restore the previous Zigbee2MQTT (backup) and everything worked again.

That make senses and is a reasonable approach.  However, I would prefer to understand what is happening and causing this behavior instead of just rolling back.

**Comment by Koenkk** [comment]
It may help to re-pair the device close to the coordinator, then wake it up and press the configure button from the frontend (yellow refresh icon)
