### ISSUE TITLE
Automation using the TuYa SH-SC07 button does not work

### ISSUE THREAD

**Issue by Fierys** [Koenkk/zigbee2mqtt#21143]
### What happened?

After updating Zigbee2MQTT from 1.35.1 to 1.35.2, automation using TuYa SH-SC07 buttons stopped working.
Zigbee2MQTT has buttons, clicks are processed. I tried to rebind, HA restarted.
After rolling back to Zigbee2MQTT 1.35.1 everything works fine.
2 buttons behave the same.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

20210319

### Adapter

dongle СC2652P. zStack3x0

### Setup

HAOS on x86-64 hardware (NUC)

**Comment by Jonno12345** [comment]
Similarly my TS0041 automations have stopped working. I think this is related as both our devices should have actions of 'single', 'double' or 'hold'. Since this update mine is reporting '1_single', as per multi button devices. I'm not sure if this was an intentional breaking change, simple enough to fix my automations but without knowing if this'll be reverted I don't know if I should..!

**Comment by coubi64** [comment]
Same here with Aqara WXKG11LM. Automatisation on "single action" for example (i didn't tried others) is not working anymore since update of Zigbee2MQTT to 1.35.2

**Comment by Fierys** [comment]
![1352](https://github.com/Koenkk/zigbee2mqtt/assets/13329786/d6b615a0-de70-4339-977d-b6bafe763b01)
![1351](https://github.com/Koenkk/zigbee2mqtt/assets/13329786/8252ee82-2d1c-4e2f-88f7-8dd17683bd8e)

**Comment by Chartreusito** [comment]
Same problem here.
Most likely related to https://github.com/Koenkk/zigbee2mqtt/issues/21158

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/21158

**Comment by mysleinic** [comment]
Folks,

I have the same exact trouble - problem is that when using "Device" as a trigger it no longer discovers "single", "double", etc. events on the list of the triggers... In my case just a battery state or button mode. It was working for some of my buttons for some time after upgrade and gradually all buttons gone! What is f... -> really annoying.

However - working workaround is to use "State" as trigger:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/139065142/2099d114-d8e3-41fa-aa2a-3b6e00aa696d)

Try it for yourself - watchout as action entity state names are case sensitive.

ps. I'm using Tuya Zigbee buttons via zigbee2mqtt

**Comment by Chartreusito** [comment]
@mysleinic please follow up in the [linked issue](https://github.com/Koenkk/zigbee2mqtt/issues/21158)
