### ISSUE TITLE
IKEA repeaters dead after update to 1.35.2-1

### ISSUE THREAD

**Issue by ur7x** [Koenkk/zigbee2mqtt#21147]
### What happened?

Upgrades to 1.35.2-1

All IKEA devices (buttons and Blinds) that need repeaters are dead.  Did a network map to see what is going on... ALL IKEA repeaters now fail pings from Zigbee hub

### What did you expect to happen?

An upgrade that did not take down 90% of my IKEA Zigbee devices

### How to reproduce it (minimal and precise)

Upgrade to 1.35.2-1 and boom... All the IKEA repeater are OFFLINE.

Tried rebooting all of the repeaters... No luck 

### Zigbee2MQTT version

1.35.2-1

### Adapter firmware version

20240104.0

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Add on to HA.  Running on a X86-64

**Comment by Seger85** [comment]
Thanks for reporting (read along once), just wanted to make an update and saw it here, wait and see if you could find a solution or a fix will clear it up. Thank you

**Comment by ur7x** [comment]
Working on it ... Might have been a new Pi4 (backup motioneye server) added to the server closet causing radio interference...

I have removed that..

Still rebooting every thing...

**Comment by svenso** [comment]
Same problem here, 4 hours after upgrading, 15 of 18 ubisys devices were offline. A restart fixed it. Will check the logs the next time.

**Comment by ur7x** [comment]
Not sure might have been the Pi4 and their infamous radio interference. 

But a second round of HA and IKEA repeater reboots and I think I'm back in business... At least all of the Ping errors seem to be gone...

**Comment by donagrejja** [comment]
Same issue here. Loads of devices stopped updating. Rolled back to previous version.

**Comment by SVH-Powel** [comment]
Which mqtt broker are you using? I am using the Mosquitto broker add-on version 6.2.1. Version 6.3.1 and 6.4.0 have known issues and can cause behavior like you have.

**Comment by janfuhlrott** [comment]
After Upgrade last night ALL devices offline. Ikea and non-Ikea devices. 
Coordinator-Type ConBee2, Coordinator-Version 0x26780700
HA Integration, current version.
Restore of Backup brought back all devices.

**Comment by BenjiBizz** [comment]
Same for all Osram smart plus plus. All offline. After restoring the Backup - all online again

**Comment by lukbe** [comment]
Same here, after the update on 1.35.2-1 all buttons stopped working.

**Comment by koenraadhaedens** [comment]
same here nothing works after upgrade to 1.35.2-1 restoring the backup worked. back on 1.35.1-1 now. Coordinator type
: ConBee2/RaspBee2 Coordinator revision: 0x26720700 on Home Assistant Blue / Hardkernel ODROID-N2/N2+

**Comment by Strixx76** [comment]
Same here. Upgraded from from 1.31.2 to 1.36.1 and all [IKEA E1746 signal repeaters](https://www.zigbee2mqtt.io/devices/E1746.html#ikea-e1746) went offline.

After the upgrade it started to reconfigure all of my devices in the entire network. But it as never able to configure the any of my four IKEA signal repeaters:
```
Zigbee2MQTT:error 2024-04-11 09:31:05: Failed to configure 'Repeater, Sovrum', attempt 1 (Error: Bind 0x5c0272fffec8abfb/1 genBasic from '0x00212effff05c9ff/1' failed (waiting for response TIMEOUT)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:776:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:895:13)
    at Configure.configure (/app/lib/extension/configure.ts:122:13)
    at Immediate.<anonymous> (/app/lib/extension/configure.ts:74:17))
```
When trying to look at the network map i got this error for all my repeaters:
`Zigbee2MQTT:error 2024-04-11 10:07:48: Failed to execute LQI for 'Repeater, Vardagsrum'`

Tried to factory reset one, force delete from Zigbee2MQTT and then it was possible to get it to join the network. But after that it is back to offline.

Coordinator is ConBee2/RaspBee2, with fw 0x264a0700

Bu on a fresh install (docker) with SONOFF Zigbee 3.0 USB Dongle Plus as adaptor (fw 20210708) the IKEA signal repeaters are working perfectly fine.

So I think this has nothing to do with the coordinator or adapter. It must have been something with the re-configuring of devices after the upgrade.

**Comment by RedNo7** [comment]
Would this be the same issue as my trying to pair (my first IKEA) E1746 and it showing as an "unsupported" manufacturer with "null" for exposes, settings and state?

I have lots of devices on my network but this is may first IKEA device and am utterly confused right now regarding pairing.
