### ISSUE TITLE
Sensors payload

### ISSUE THREAD

**Issue by guigaszf** [Koenkk/zigbee2mqtt#2115]
Hello!

Is it possible to see the sensors payload (before conversion) and how zigbee to mqtt interprets and converts then?

Thanks!

**Comment by sjorge** [comment]
I don't think you can, but you can easily check what zigbee2mqtt is doing for the conversion.

e.g. for the Aqara sensor
- check device config here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/devices.js#L512
- note down the fromZigbee functions: `fz.xiaomi_battery_3v, fz.occupancy_with_timeout,fz.generic_illuminance,fz.RTCGQ11LM_interval`
- lookup the functions in here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/converters/fromZigbee.js
- for example generic_illuminance is found here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/converters/fromZigbee.js#L716

From that we learn that it hooks into the `msIlluminanceMeasurement` cluster and will fetch the data from `msg.data['measuredValue']` (you might be able to add a logger here and log the raw value I guess). It then runs the value through `calibrateAndPrecisionRoundOptions` which is defined in the same file here: https://github.com/Koenkk/zigbee-shepherd-converters/blob/zigbee-herdsman-converters/converters/fromZigbee.js#L20

Which in this case does:
- read `illuminance_calibration` from the device config or use 0
- in the case if illumance it is treated as a percentage of the actual value (so raw = 10 with a calubration of 10 would get an offset of 1)
- add the offset to the raw data (so in our example it will be 10 + 1 so 11)
- this is then rounded to the certain percision via precisionRound, with a default of 0, so when using the default it will be 11 in our little example.
