### ISSUE TITLE
Aqara switch Z1 The middle switch of the triple rocker switch cannot be used.

### ISSUE THREAD

**Issue by gresgtehrtsher** [Koenkk/zigbee2mqtt#21153]
### What happened?

I found that the code for the triple rocker switch is almost the same as the two-key switch. Did you forget to write the code for the middle key switch after copying the triple rocker switch code?

@waterlou
https://github.com/Koenkk/zigbee-herdsman-converters/blob/cae265712bf75be74530d1c0458901f81c1adcc5/src/devices/lumi.ts#L3339

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

latest

### Adapter

docker

### Setup

docker

**Comment by waterlou** [comment]
An update is submit and should be available in next update.  The reason why old external converter not working is the major name change from Xiaomi to lumi in the recent update.  In the meantime, you can use the following external converter.

https://gist.github.com/waterlou/88d4f1e15a31db9edfcefb0dd4e71304

**Comment by leeaash** [comment]
I have made a lot of helper to change switch type to light on old external converters, they use button_1,2,3,4, I have tried this update, but I saw that all those helper were gone after I upgraded z2m to 1.35-2
Is there a way to keep my setting? or I have to re-change them one by one.
