### ISSUE TITLE
[Feature request]: Namron 4512770 sensitivity settings

### ISSUE THREAD

**Issue by kstormhansen** [Koenkk/zigbee2mqtt#21168]
### Is your feature request related to a problem? Please describe

The Namron 4512770 motion sensor supports changing the sensitivity of the sensor:
15 - Standard value
0 - deactivated
8-255 - possible sensitivity settings (8 highest, 255 lowest sensitivity)

Please expose this setting in Zigbee2mqtt.

### Describe the solution you'd like

Settings for PIR sensitivity exposed in Zigbee2mqtt

### Describe alternatives you've considered

N/A

### Additional context

![413918012_2803633606444683_1059257196746810895_n](https://github.com/Koenkk/zigbee2mqtt/assets/93662470/1a752fb1-f2e0-469b-bf63-d1826cabac6d)

**Comment by sirasjad** [comment]
Re-opening this issue. This is actually a Sunricher device (Sunricher HK-SENSOR-4IN1-A). And configuration of occupacy sensor is possible on the Sunricher device in Z2M. 

Link: https://www.zigbee2mqtt.io/devices/HK-SENSOR-4IN1-A.html
