### ISSUE TITLE
502: bad gateway and failed to start after update to 1.35.2-1 

### ISSUE THREAD

**Issue by WAlekseev** [Koenkk/zigbee2mqtt#21170]
### What happened?

After upgrade from previous version (1.35.1-1) to 1.35.2-1 i can't start z2m - 502 error and won't start

### What did you expect to happen?

Working z2m

### How to reproduce it (minimal and precise)

Just upgrade from previous version z2m, in my case from 1.35.1-1

### Zigbee2MQTT version

1.35.2-1

### Adapter firmware version

Firmware: 7.3.1-176, EZSP v12

### Adapter

EFR32MG21 ZB-GW04 V1.2

### Setup

Pi4 model B, 8 GB ram.

### Debug log

```
[16:13:54] INFO: Preparing to start...
[16:13:54] INFO: Socat not enabled
[16:13:56] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-02-02 16:14:02: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-02.16-14-02' filename: log.txt
Zigbee2MQTT:info  2024-02-02 16:14:02: Starting Zigbee2MQTT version 1.35.2 (commit #unknown)
Zigbee2MQTT:info  2024-02-02 16:14:02: Starting zigbee-herdsman (0.33.5)
Zigbee2MQTT:error 2024-02-02 16:14:05: Failed to start zigbee
Zigbee2MQTT:error 2024-02-02 16:14:05: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-02-02 16:14:05: Exiting...
Zigbee2MQTT:error 2024-02-02 16:14:05: Error: extenderElectricityMeter can accept only one endpoint
    at Array.extenderElectricityMeter (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:245:15)
    at addGenerators (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:128:51)
    at generateDefinition (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:132:15)
    at findDefinition (/app/node_modules/zigbee-herdsman-converters/src/index.ts:293:35)
    at Object.findByDevice (/app/node_modules/zigbee-herdsman-converters/src/index.ts:265:22)
    at Device.resolveDefinition (/app/lib/model/device.ts:36:31)
    at Zigbee.start (/app/lib/zigbee.ts:67:13)
    at Controller.start (/app/lib/controller.ts:106:27)
    at start (/app/index.js:107:5)
```

**Comment by fgibaux** [comment]
same error here, same version

**Comment by Nerivec** [comment]
@WAlekseev You seem to have a device that's causing trouble with the new update. It's a device that reports some kind of electrical measurement (meter, voltage, energy, etc). Mind giving me a list of possibilities (and [their pages](https://www.zigbee2mqtt.io/supported-devices/) would be great) based on your devices? The number of updates is massive, it will go a lot faster if I know which device to look for.

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7001 , thanks @Nerivec !

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by WAlekseev** [comment]
> @WAlekseev You seem to have a device that's causing trouble with the new update. It's a device that reports some kind of electrical measurement (meter, voltage, energy, etc). Mind giving me a list of possibilities (and [their pages](https://www.zigbee2mqtt.io/supported-devices/) would be great) based on your devices? The number of updates is massive, it will go a lot faster if I know which device to look for.

This one:

https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1


Thanks for reply! Mention that with last update 1.35.3-1 there is no problem!
