### ISSUE TITLE
_TZ3000_fa9mlvja tuya button triggers

### ISSUE THREAD

**Issue by iqubik** [Koenkk/zigbee2mqtt#21177]
### What happened?

_TZ3000_fa9mlvja tuya button
IH-K663
TS0041
====
Today ii update z2m to last version and my button is broke.
All problem is name of trigger is changed. Last correct name - "single", new incorrect name "1_single"
This button have 1 button and 1_single and 1_double is incorrect name for triggers

### Zigbee2MQTT version

1.35.2-1

### Adapter firmware version

20230507

### Adapter

zStack3x0

### Setup

rk3318 tv box

### Debug log

![Снимок экрана (367)](https://github.com/Koenkk/zigbee2mqtt/assets/22661808/af5074e6-90c8-41c7-bcef-d807b8cf0a1c)

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/21158
