### ISSUE TITLE
[Feature Request] Making devices "unavailable" in HA 

### ISSUE THREAD

**Issue by syphernl** [Koenkk/zigbee2mqtt#2117]
# Feature Request
Right now a Zigbee device can become unavailable, but HomeAssistant doesn't know about this. For instance, if a mains powered Tradfri light was turned off by using the light switch. 
HA doesn't know about this and keeps showing the toggle button. 

Is there a way to return an unavailable status somehow making it more clear that something is wrong instead of having to dive into the Zigbee2MQTT logs to see what is going wrong.

**Comment by Koenkk** [comment]
Already implemented, see #775
