### ISSUE TITLE
Heiman HS1WL-M ZHA1.2 no recognized

### ISSUE THREAD

**Issue by mihc** [Koenkk/zigbee2mqtt#21174]
### What happened?

Hi,

I paired a new device - a water leakage sensor Heiman HS1WL-M ZHA1.2, but it's not recognized.
It is this sensor: https://www.zigbee2mqtt.io/devices/HS1WL_HS3WL.html

Zigbee2mqtt finds this device as:
Zigbee Model: WATER_TPV13
Zigbee Manufacturer: Heiman

I tried to add custom js and configure a new device, but so far I did not manage to do that.

Is it possible to add this model as HEIMAN HS1WL https://www.zigbee2mqtt.io/devices/HS1WL_HS3WL.html which is already supported? 

### What did you expect to happen?

I would expect to recognize it as HEIMAN HS1WL https://www.zigbee2mqtt.io/devices/HS1WL_HS3WL.html

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle

### Setup

Docker container

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
