### ISSUE TITLE
Light Solutions 3137308 now discovered as 3137309 and no longer dimmable

### ISSUE THREAD

**Issue by senagel** [Koenkk/zigbee2mqtt#21183]
### What happened?

The Light Solutions 3137309 wire dimmer was newly added to the list of supported devices. Now my Light Solutions dimmer 3137308 (which I believe is technically the same) is no longer dimmable and only supports on/off. 

Note: It was dimmable until the last update of Zigbee2MQTT. Before the update it was discovered as a different, probably generic device. 

### What did you expect to happen?

The device should still be dimmable. 

### Zigbee2MQTT version

 1.35.2

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Setup

Zigbee2MQTT in Home Assistant

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
