### ISSUE TITLE
GLEDOPTO led driver model GL-C-002P 6A Mini 5in1 Controller doesn't get full brightness

### ISSUE THREAD

**Issue by 60github** [Koenkk/zigbee2mqtt#21194]
### What happened?

The led controller doesn't give you the full brightness for colors different than pure colors red, green or blue. For example, if you set:

1. (R=255,G=0,B=0), (R=0,G=255,B=0) or (R=0,G=0,B=255): the led strip when you set up brightness at 254, the brightness is full, the total power consumption is normal, and voltage output of the channel turned on is about 12.05V. With these colors it works ok.

2. (R=255,G=255,B=0), (R=255,G=0,B=255) or (R=0,G=255,B=255): the led strip when you set up brightness at 254, the brightness is not full, the total power consumption is half than it should be, and voltage output of the channels turned on is about 10.30V-10.60V (expected to be 12V each channel). With these colors it made less brightness than expected.

3. (R=255,G=255,B=255): the led strip when you set up brightness at 254, the brightness is less than when you only turn on 2 colors, the total power consumption is below 1/3 than it should be, and voltage output of the channels turned on is about 9.70V-9.90V (expected to be 12V each channel). With these colors it made much less brightness than expected.

It seams than when one color works, the output gives 100% of the maximum brightness, with 2 colors 50% of the maximum brightness and with 3 colors on 1/3 of the maximum brightness.

It works ok with Samrt Life App, so, it's not a faulty unit. This problems happens with all the modes that have RGB/RGBW/RGBCCT.

When the device is set up as RGB controller, it is detected in zigbee2mqtt as follows:

Zigbee model GL-C-003P
Zigbee Manufacturer GLEDOPTO
Description Zigbee LED Controller RGB (pro)
Firmware date 20230905
Firmware version 20451203
Manufacturer Gledopto
Model GL-C-003P

### What did you expect to happen?

If you set up the brightness to 254, the output should deliver the maximum brightness regarles the colour you set up.

### How to reproduce it (minimal and precise)

Set up the colors explained before, see the brightness, measure de voltage of each channel output and measure the total power consumption of the led strip.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

20221226

### Adapter

ZBDonlge-P

### Setup

Zigbee2MQTT as a container in a machine running Ubuntu Server 22.04.03 LTS with Docker 25.0.1

### Debug log

debug 	03/02/2024	16:50:09: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"state": "ON"}'
debug 	03/02/2024	16:50:09: 	Publishing 'set' 'state' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:10: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.3227,"y":0.329},"color_mode":"xy","linkquality":160,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:11: 	Received Zigbee message from 'Tira_led_pruebas', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":604057601,"imageType":5145,"manufacturerCode":4687}' from endpoint 11 with groupID 0
debug 	03/02/2024	16:50:11: 	Device 'Tira_led_pruebas' requested OTA
debug 	03/02/2024	16:50:15: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "255,0,0"}}'
debug 	03/02/2024	16:50:15: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:15: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.7006,"y":0.2993},"color_mode":"xy","linkquality":156,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:24: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "0,255,0"}}'
debug 	03/02/2024	16:50:24: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:24: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.1724,"y":0.7468},"color_mode":"xy","linkquality":160,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:32: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "0,0,255"}}'
debug 	03/02/2024	16:50:32: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:32: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.1355,"y":0.0399},"color_mode":"xy","linkquality":156,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:41: 	Received Zigbee message from 'Tira_led_pruebas', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":604057601,"imageType":5145,"manufacturerCode":4687}' from endpoint 11 with groupID 0
debug 	03/02/2024	16:50:41: 	Device 'Tira_led_pruebas' requested OTA
debug 	03/02/2024	16:50:41: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "255,255,0"}}'
debug 	03/02/2024	16:50:41: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:41: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.4442,"y":0.5166},"color_mode":"xy","linkquality":156,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:48: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "255,0,255"}}'
debug 	03/02/2024	16:50:48: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:48: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.3855,"y":0.1546},"color_mode":"xy","linkquality":160,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:50:56: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "0,255,255"}}'
debug 	03/02/2024	16:50:56: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:50:56: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.1513,"y":0.3425},"color_mode":"xy","linkquality":153,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:51:02: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"color": {"rgb": "255,255,255"}}'
debug 	03/02/2024	16:51:02: 	Publishing 'set' 'color' to 'Tira_led_pruebas'
info  	03/02/2024	16:51:02: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.3227,"y":0.329},"color_mode":"xy","linkquality":156,"power_on_behavior":"off","state":"ON","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'
debug 	03/02/2024	16:51:11: 	Received Zigbee message from 'Tira_led_pruebas', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":604057601,"imageType":5145,"manufacturerCode":4687}' from endpoint 11 with groupID 0
debug 	03/02/2024	16:51:11: 	Device 'Tira_led_pruebas' requested OTA
debug 	03/02/2024	16:51:16: 	Received MQTT message on 'zigbee2mqtt/Tira_led_pruebas/set' with data '{"state": "OFF"}'
debug 	03/02/2024	16:51:16: 	Publishing 'set' 'state' to 'Tira_led_pruebas'
info  	03/02/2024	16:51:16: 	MQTT publish: topic 'zigbee2mqtt/Tira_led_pruebas', payload '{"brightness":254,"color":{"x":0.3227,"y":0.329},"color_mode":"xy","linkquality":156,"power_on_behavior":"off","state":"OFF","update":{"installed_version":604057601,"latest_version":587280385,"state":"idle"},"update_available":null}'

**Comment by sirotkaslo** [comment]
Just bought the 201p model and it works the same. Have it set in CCT mode. Cold gives ful voltage, warn gives full voltage, everything in between lovers it.

**Comment by KaelWD** [comment]
RGBW is even worse, rgb values are about the same (10v for 255,255,0) but setting temperature to 50% results in just 9v on all outputs.
