### ISSUE TITLE
Filter option on device page not working as expected, opens a bug page instead.

### ISSUE THREAD

**Issue by acaminiti** [Koenkk/zigbee2mqtt#21218]
### What happened?

While checking the main page of a device, want to change to a different device. Noticed that I was able to change to a different device by clicking on the current device name (Above "About" tab.).

![device_page](https://github.com/Koenkk/zigbee2mqtt/assets/56757107/c6670b4a-dced-46ab-8ba4-8d1c26d62fbc)

After click, a filter menu is shown. but when trying to write a new device name instead of the filter working immediately got a bug found page.

![z2m_bug](https://github.com/Koenkk/zigbee2mqtt/assets/56757107/f536c13f-c6f8-4dd8-a421-33213fdb172c)

### What did you expect to happen?

Be able to type a device name instead.

### How to reproduce it (minimal and precise)

1. Go to the main page of a device.
2. Click on the device name above the "About" tab.
3. Filter box shows with option to either to type the name of a new device or scroll the list of devices.
4. Type any letter.
5. Bug page shows immediately. 

### Zigbee2MQTT version

1.35.2 commit: unknown

### Adapter firmware version

20230507

### Adapter

ZigStar Stick v4

### Setup

Add-on on Home Assistant on x86-64 machine

### Debug log

As recommended by page, downloaded zip file and provided here:

[initialState.json.zip](https://github.com/Koenkk/zigbee2mqtt/files/14157537/initialState.json.zip)

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
