### ISSUE TITLE
Namron 1402767 device power source unknown

### ISSUE THREAD

**Issue by EspenJQ** [Koenkk/zigbee2mqtt#21212]
### Link

https://www.namron.com/products/namron-zigbee-led-dimmer-2-pol-250w/

### Model

1402767

### Description

Zigbee LED dimmer 2-pole 250W

### Vendor

Namron

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/1402767.jpg

### Database entry

0xf4b3b1fffef93990

### Notes

Power source should be reported as mains single phase.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
