### ISSUE TITLE
[New device support]: Tuya 6 gang smart switch

### ISSUE THREAD

**Issue by hanzala-123** [Koenkk/zigbee2mqtt#21225]
### Link

https://a.aliexpress.com/_EyQ1gsN

### Database entry

0xa4c13845c0b37a16 (0x97BA)

### Comments

I tried to follow the instructions on how to add support but failed. This is the exact same or very similar but it was not discovered as this device: 
https://www.zigbee2mqtt.io/devices/SWS6TZ-WHITE.html

### External defintion

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE200_cduqh1l0',
    description: 'Automatically generated definition',
    extend: [],
};

module.exports = definition;
```

**Comment by mrmaximas** [comment]
> ### Link
> https://a.aliexpress.com/_EyQ1gsN
> 
> ### Database entry
> 0xa4c13845c0b37a16 (0x97BA)
> 

Please provide info from database.db file

**Comment by hanzala-123** [comment]
How do I access it

**Comment by mrmaximas** [comment]
> How do I access it

depending on OS but in the ~/zigbee2mqtt/data/database.db

**Comment by Koenkk** [comment]
Does your device support power monitoring?

**Comment by hanzala-123** [comment]
No

**Comment by hanzala-123** [comment]
> > How do I access it
> 
> depending on OS but in the ~/zigbee2mqtt/data/database.db

My OS is home assistant on raspberry Pi

**Comment by hanzala-123** [comment]
Hi, I’m struggling to find the database.db file on my home assistant OS

**Comment by hanzala-123** [comment]
> > ### Link
> > https://a.aliexpress.com/_EyQ1gsN
> > ### Database entry
> > 0xa4c13845c0b37a16 (0x97BA)
> 
> Please provide info from database.db file

{"id":12,"type":"Unknown","ieeeAddr":"0x84fd27fffe4370e2","nwkAddr":4872,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1708501156121}

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

> {"id":12,"type":"Unknown","ieeeAddr":"0x84fd27fffe4370e2","nwkAddr":4872,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1708501156121}

Make sure to re-pair again after updating, interview failed in this case (just retry until it succeeds)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by hanzala-123** [comment]
Thank you so much man ❤️Kind Regards, Hanzala Chaudry On 24 Feb 2024, at 08:14, Koen Kanters ***@***.***> wrote:﻿
Added!
Changes will be available in the dev branch in a few hours from now.

{"id":12,"type":"Unknown","ieeeAddr":"0x84fd27fffe4370e2","nwkAddr":4872,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1708501156121}

Make sure to re-pair again after updating, interview failed in this case (just retry until it succeeds)
Changes will be available in the dev branch in a few hours from now.

**Comment by hanzala-123** [comment]
Hi one of the switches works but the other ones say no converter available
