### ISSUE TITLE
Since new update Z2M stops working and the website can't be accessed either

### ISSUE THREAD

**Issue by Loeffelmaster** [Koenkk/zigbee2mqtt#21238]
### What happened?

Hello,

since new update Z2M stops working and the website can't be accessed either. Under AddOns I can't even stop Z2M, it doesn't reacts on the stop. Only a restart is possible.
When Z2M stopped working, the log is empty too. Where can I look to find the problem (different log file). As it only runs for a few hours now until it crashes again, I can't use it anymore.

### What did you expect to happen?

Z2M starts and runs normal.

### How to reproduce it (minimal and precise)

Restart HA or Z2M after some time Z2M stops working. There is no timeframe to be named.

### Zigbee2MQTT version

1.35.2-1 (on the about page  1.35.2 commit: unknown)

### Adapter firmware version

 7.1.4.0 build 389

### Adapter

EZSP v9 (SONOFF ZBDongle-E 3.0 USB Dongle Plus)

### Setup

Add-On to HA HP Elitedesk 800 G4

### Debug log

Debug activated /data/log folder doesn't exists, where can I find the

**Comment by snovo1** [comment]
Same issue, there are errors in the logs "error Adapter disconnected, stopping". Sometimes the adapter recovers after a while, but sometimes i have to reboot the mini pc. 

Zigbee2MQTT version
1.35.2
Coordinator type
EZSP v11 (SONOFF ZBDongle-E)
