### ISSUE TITLE
MCCGQ14LM  Firmware -1

### ISSUE THREAD

**Issue by Sonic62** [Koenkk/zigbee2mqtt#21232]
### What happened?

Firmawre invisible

### Zigbee2MQTT version

1.35.2-1

### Adapter firmware version

20221226

### Adapter

Sonoff P

### Setup

ADDONS HOME ASSISTANT

### Debug log

![Capture d'écran 2024-02-05 021231](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/e8c197a0-9562-4c61-834f-3a61038a67d7)
![Capture d'écran 2024-02-05 021249](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/5a8ebdb5-3403-420a-8565-28009c0a5423)

**Comment by Sonic62** [comment]
![Capture d'écran 2024-02-05 022249](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/274e41e4-8098-4584-983c-1793ff857e28)
![Capture d'écran 2024-02-05 022308](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/29199654-8894-4ffd-a906-bbc134e30fb9)
![Capture d'écran 2024-02-05 022711](https://github.com/Koenkk/zigbee2mqtt/assets/103725660/1634296d-614b-4818-8e9b-45f5f7d52b9d)

**Comment by Koenkk** [comment]
we don't have an OTA for this device ATM, disabled it

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
