### ISSUE TITLE
[Wrong device]: TS0207 water leak detector

### ISSUE THREAD

**Issue by guidokieboom** [Koenkk/zigbee2mqtt#21247]
### Link

https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector_2.html#tuya-ts0207_water_leak_detector_2

### Model

TS0207 water leak detector

### Description

water leak detector - wrong picture

### Vendor

Tuya / Aubess

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/IH-K665.jpg

### Database entry

can't open database.db

### Notes

<img width="1077" alt="Screenshot 2024-02-05 at 21 01 14" src="https://github.com/Koenkk/zigbee2mqtt/assets/65387179/deb0eb20-a1e2-46c3-aaf4-5918c8519b2c">
<img width="734" alt="Screenshot 2024-02-05 at 21 00 56" src="https://github.com/Koenkk/zigbee2mqtt/assets/65387179/e8ed0290-ce8c-4037-bb18-36301bcc00df">

I have 3 same water leak detectors. First 2 (waterleak1 and waterleak2) show the correct picture. The 3rd one (waterleak3) does not show the correct picture.

**Comment by guidokieboom** [comment]
It should be: https://www.zigbee2mqtt.io/devices/IH-K665.html

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by guidokieboom** [comment]
No problem. Could you help me where to find and how to get it to you?

**Comment by marcelhoogantink** [comment]
Just open Add-on 'Studio Code Server', (install it if you didn't before)
Goto config/zigbee2mqtt map. 
Find database.db file.
Right-click and download it to your system.
Put it in a ZIP file.
Drag this zip file into your reply on github, an send the reply.

**Comment by guidokieboom** [comment]
That worked. As I didn't like to share info of all my devices, I copied the 3 related lines and pasted into Excel sheet.
ID27 is the one that is discussed in this issue. The other two (20 and 21) devices gave the correct picture from the start.
Hope this helps for you.
[Book1.xlsx](https://github.com/Koenkk/zigbee2mqtt/files/14389064/Book1.xlsx)

**Comment by marcelhoogantink** [comment]
Thanks!
I looked into it. The data are almost the same, found no good difference to make a separate definition for global use.
I am going to overrule the icon locally.

Thanks for your time !!
