### ISSUE TITLE
ZC05M from GIDEALED is wrongly  recognized as TS0503B from TUYA

### ISSUE THREAD

**Issue by 19Shorty87** [Koenkk/zigbee2mqtt#21244]
### What happened?

Hello,

At first thank you for developing such an great Project. I have tried a new LED controller and have been running in following issue:

The LED controller ZC05M was TS0503B. I've tried several reconnections but this has not solved the issue.

database:
{"id":7,"type":"Router","ieeeAddr":"0xa4c1380b5d93ac62","nwkAddr":4384,"manufId":4417,"manufName":"_TZ3210_w7ge4ldo","powerSource":"Mains (single phase)","modelId":"TS0503B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devI>

### Zigbee2MQTT version

 1.35.1 commit: 3c96204

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Setup

Raspi_Zero_W runs on Raspbian 11 (bullseye)(No Container)

**Comment by KingKoerle** [comment]
same here

**Comment by Koenkk** [comment]
Please fill in https://github.com/Koenkk/zigbee2mqtt/issues/new?assignees=&labels=wrong+device&projects=&template=wrong_device.yaml&title=%5BWrong+device%5D%3A+
