### ISSUE TITLE
Device stops functioning properly after update to 1.35.2 ( Gledopto GL-SD-001 dimmer)

### ISSUE THREAD

**Issue by uncle-fed** [Koenkk/zigbee2mqtt#21259]
### What happened?

The [dimmer ](https://www.zigbee2mqtt.io/devices/GL-SD-001.html) stopped working properly after the recent update of z2m to version 1.35.2. The commands sent to the dimmer just time out for no reason. Going back to z2m version 1.35.1 immediately resolves these problems and everything works as before, stable and fine. 

> Side note (that may or may not be important here): the device has been confirmed to generate flood of messages when the state is changed, also it does not properly behave when `debounce`  is enabled. These two issues are being discussed [here](https://github.com/Koenkk/zigbee2mqtt/issues/21226) however that discussion is not exclusive to Gledopto and not just for v1.35.2.

This issue here concerns only the GL-SD-001. Immediately after update to v1.35.2 the device starts reacting to commands almost "randomly". Sometimes they work but mostly time out, causing the mayhem with subsequent commands (states and brightness wrongly reported, not doing anything and then suddenly catching up and starting performing all the commands at once, etc.)

It is very important to underline this: none of this happened with 1.35.1 and going back to 1.35.1 from 1.35.2 immediately fixes the behaviour.

### Zigbee2MQTT version

1.35.2 

### Adapter firmware version

20221226

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus-P

### Setup

Plain Z2M on Pi 4

**Comment by Koenkk** [comment]
Fixed!

Will be available in the 1.35.3 hotfix release.
