### ISSUE TITLE
Frontend is without any css styling: "Could not find specified theme"

### ISSUE THREAD

**Issue by sdotter** [Koenkk/zigbee2mqtt#21256]
### What happened?

Running frontend from port 8099 port as configured in:

<img width="718" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/11946839/e1905dee-8fb6-4c0b-87e8-df0abdfda763">

Results in frontend without any css styles etc:
<img width="845" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/11946839/98d54f24-cd50-44ee-b511-697e887306f7">

<img width="454" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/11946839/644c91c4-ec93-49ef-afdb-3d0084c0908a">

### Zigbee2MQTT version

Latest

### Adapter firmware version

6.10.3.0

### Adapter

Sonoff dongle e

### Setup

Add-on homeassistant docker rpi x64

**Comment by sjorge** [comment]
The frontend is in this repo https://github.com/nurikk/zigbee2mqtt-frontend

Best to file the issue there instead of here.

**Comment by sdotter** [comment]
Thanks!

**Comment by jehy** [comment]
Error description and solution here: https://github.com/nurikk/zigbee2mqtt-frontend/issues/1921
