### ISSUE TITLE
1.35.3-1 destroys Frontend in Home Assistant 

### ISSUE THREAD

**Issue by ZeloNoleZ** [Koenkk/zigbee2mqtt#21268]
### What happened?

After Update to the new Version, the Frontend isn't loaded propably. Stylesheets or similar seems to be missing/not loading. Restore of Backups returned the Frontend to normal.

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

7.3.1.0 build 0

### Adapter

EZSP v12

### Setup

Home Assistant Addon

**Comment by Tinuz97** [comment]
I can't even do the update, returning error. 


Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:23:00 (2 occurrences)
Last logged: 22:24:21

[140363640249024] Error updating Zigbee2MQTT: Can't install zigbee2mqtt/zigbee2mqtt-amd64:1.35.3-1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.35.3-1&fromImage=zigbee2mqtt%2Fzigbee2mqtt-amd64&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")
[140363640249024] Error updating Zigbee2MQTT: Can't install zigbee2mqtt/zigbee2mqtt-amd64:1.35.3-1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.35.3-1&fromImage=zigbee2mqtt%2Fzigbee2mqtt-amd64&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/zigbee2mqtt/zigbee2mqtt-amd64/manifests/1.35.3-1": Get "https://auth.docker.io/token?scope=repository%3Azigbee2mqtt%2Fzigbee2mqtt-amd64%3Apull&service=registry.docker.io": EOF")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install zigbee2mqtt/zigbee2mqtt-amd64:1.35.3-1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.35.3-1&fromImage=zigbee2mqtt%2Fzigbee2mqtt-amd64&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Zigbee2MQTT: Can't install zigbee2mqtt/zigbee2mqtt-amd64:1.35.3-1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.35.3-1&fromImage=zigbee2mqtt%2Fzigbee2mqtt-amd64&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")

**Comment by OddyAte** [comment]
What fixed it for me was to change back to light mode. After that it returned to normal.

**Comment by Tinuz97** [comment]
> What fixed it for me was to change back to light mode. After that it returned to normal.

Funny, that did the trick.
Thanks.

**Comment by HAIM359** [comment]
> What fixed it for me was to change back to light mode. After that it returned to normal.

Thank you!

**Comment by christovic** [comment]
Worked for me too. What a funny bug.

**Comment by Zeronozero** [comment]
I have change to light mode and come back but it still broken :-(

**Comment by alray31** [comment]
> I have change to light mode and come back but it still broken :-(

same here, had to restore previous version.
![Screenshot_20240206-204438_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/115857857/3392be53-765e-4d94-b67e-779828595743)

**Comment by alray31** [comment]
nvm, Switching from dark to light fixed it. I was trying to change the dark/light from the HA user config menu from, only to realize after uploading that picture that little sun icon in z2m

**Comment by fireheadman** [comment]
> nvm, Switching from dark to light fixed it. I was trying to change the dark/light from the HA user config menu, only to realize after uploading that picture that little sun icon in z2m frontend

worked for me tooo... looks like a smiley face when it is jacked up...

**Comment by fireheadman** [comment]
Very odd issue.. even flushing browser cache wouldn't help.

**Comment by Nisbo** [comment]
Same issue. Switching to light mode did NOT fix the problem.

**Comment by Nisbo** [comment]
Logging out from HA and logging in again fixed the problem.
Dont know why CTRL+F5 was not resolving the problem, maybe a cookie issue.

**Comment by rchiileea** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/21276 also some devices not responding with update (ikea blinds, aqara opple switches).

**Comment by Takacsk76** [comment]
The z2m dark/light mode solved the problem for me as well.  Thx!

**Comment by GaupeLnx** [comment]
Same here Switching Dark light mode did not work. But logging off and in again did

**Comment by oxivanisher** [comment]
The same issue (and the same fix worked) for my zigmee2mqtt which is behind a reverse proxy. No homeassistant is involved.

**Comment by kwetnico** [comment]
Hello , I have the same problem from my smartphone if I go to frontend with Chrome

**Comment by rchiileea** [comment]
Ok when i got back home this afternoon, I reinstalled the update again, same issue again, some ikea items not working, some aqara and front end messed up, I logged out of home assistant and logged back in and the front end is back to normal, I repaired the devices that were not responding by removing them and re adding them. so far so good, ill pop back on with a update tomorrow if its still the same.

**Comment by ExMacro** [comment]
Light / dark mode toggle switch worked. Everything ok now.

**Comment by Koenkk** [comment]
@nurikk sounds like a caching issue, so I guess we cannot do anything from the z2m side here?

**Comment by nurikk** [comment]
> @nurikk sounds like a caching issue, so I guess we cannot do anything from the z2m side here?

there was sudden change in how we store theme in local storage, the fix is in dev branch, but problem can be fixed by clicking on theme switch icon

**Comment by ZeloNoleZ** [comment]
Ok, strange behavior. But klicking on theme ucon also worked in my Installation.

**Comment by Koenkk** [comment]
I will lock this, so the solution is either to:
- Click the theme icon once (sun or moon)
- OR (not recommended) update to the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
