### ISSUE TITLE
Third Reality Smart Plug 3RSP02028BZ OTA firmware update failing

### ISSUE THREAD

**Issue by HalyconTron** [Koenkk/zigbee2mqtt#21262]
### What happened?

Last week I installed three Third Reality 3RSP02028BZ Smart Plugs. Out of the box, they had firmware 1.00.65 and I was able to successfully update to version 1.00.71 using Zigbee2MQTT OTA updates. I tried adding two more plugs today of the same model and same base firmware (1.00.65) and when trying to update the firmware it fails immediately with this error:

Update of 'device name' failed (Cannot read properties of undefined (reading 'data'))

I did move my Home Assistant to a new machine and restored from a backup so I'm not sure if that might have something to do with this. However, everything else in Z2M is working properly, all of my devices reconnected successfully and I haven't had any issues with devices dropping off the network.

### What did you expect to happen?

The firmware to update to version 1.00.71.

### How to reproduce it (minimal and precise)

Add a Third Reality Smart Plug 3RSP02028BZ to the Zigbee network. Navigate to OTA and initiate a firmware update for the added devices.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

Generic x86-64 HAOS install with Z2M add-on.

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14183537/log.txt)

**Comment by HalyconTron** [comment]
This may have been bad timing on my end. I tried again and both plugs successfully updated and the new firmware is 1.00.74. Maybe there was an update happening on the backend.

**Comment by dhia-e-rzig** [comment]
I'm having this issue with a new OTA update. Waited 24 hours but still has not been resolved.

**Comment by flam1111** [comment]
Have the same problem since yesterday.   Error is "(Cannot read properties of undefined (reading 'data'))"

**Comment by riddley** [comment]
I also had it for 24hrs or so and then today it magically started working ??

**Comment by leoherzog** [comment]
Are firmware updates like these ones supposed to be able to travel across the Zigbee network to the device that needs the update? My updates to these plug seem to fail unless I bring them close to my Home Assistant Yellow that's acting as the coordinator.

**Comment by blindguynar** [comment]
i've had issues with plugs becoming unavailable in 1.00.74.  Happy to see a new firmware today of 1.00.79.  hoping it can resolve the issues.  1.00.71 was very stable, but i've had lots of energy monitoring issues with 1.00.74 and plugs every once in a while need cycled to return to function.   

I really wish ThirdReality would publish release notes on their firmware more freq.  They do post, but normally pretty late after releases.  For example 1.00.79 is out now, but the release notes don't mention it.

https://github.com/thirdreality/release-note/blob/main/plug/release%20note

**Comment by cowbe0x004** [comment]
The new update to 1.00.79 just broke all my plugs, getting "Failed to ping" and they are all offline. Anyone having this issue?

**Comment by scatterthought** [comment]
I just updated my plug from 1.00.71 to 1.00.79 successfully, and it appears to be working properly. Did your plugs go offline immediately after the update?

**Comment by cowbe0x004** [comment]
> I just updated my plug from 1.00.71 to 1.00.79 successfully, and it appears to be working properly. Did your plugs go offline immediately after the update?

It's fixed, looks to be my network, had to restart zigbee2mqtt.
