### ISSUE TITLE
How to perform a fresh (re)install of Zigbee2mqtt without losing all devices and setting

### ISSUE THREAD

**Issue by Theo-NL** [Koenkk/zigbee2mqtt#21270]
### What happened?

Tried to update from a (trouble -free working) version v1.34.0 to any higher version, but failed, many errors, also updating nod js and npm failed.

A new installation from Zigbee2MQTT seems better to me. How do I tackle this, without losing all devices and settings, ect.?

e.g. 
1) First make a complete backup of the data dir (/opt/zigbee2mqtt/data), 
2) then RM -RF/OPT/ZigBEE2MQTT
3) Then follow the instructions on https://www.zigbee2mqtt.io/guide/ Installation/01_linux.html from "Installing", 
4) Restore the backup in the data dir.

Is this approach correct?

Thanks!

Gr. Theo.

My configuration:
RaspberryPi 3b
Booting/operating from 64 GB USB-flashdevice, no SD card
Raspbian GNU/Linux 10 (buster)
Domoticz version: Version: 2023.2 (build 15679)
Python Version: 3.7.3
Zigbee2mqtt:plugin: v.3.2.0-beta
Zigbee2mqtt: v1.34.0  (zStack3x0 20211114)
Zigbee Slaesh's CC2652RB coördinator USB-dongle
RTC DS1307

### What did you expect to happen?

Fresh install of latest Zigbee2mqtt version without losing devices, settings, etc. from existing working version

### Zigbee2MQTT version

v1.34.0  

### Adapter firmware version

 20211114

### Adapter

Zigbee Slaesh's CC2652RB

### Setup

RaspberryPi 3b / Domoticz

**Comment by Koenkk** [comment]
> Is this approach correct?

Yes, the `data` dir contains all the config.
