### ISSUE TITLE
LYWSD03MMC Temperature Sensors not shown on Dashboard (zigbee2mqtt Version 1.35.3-1)

### ISSUE THREAD

**Issue by Bloodpack** [Koenkk/zigbee2mqtt#21274]
### What happened?

LYWSD03MMC Temperature Sensors not shown on Dashboard but shown on Devices

Dashboard screenshot
![Dashboard](https://github.com/Koenkk/zigbee2mqtt/assets/26135135/4708f288-267c-49eb-800f-b882e884ce25)

Devices screenshot
![Devices](https://github.com/Koenkk/zigbee2mqtt/assets/26135135/a802945e-9949-44ba-8d31-e6211ee206bf)

### What did you expect to happen?

to be shown on the Dashboard

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

20231112

### Adapter

tubeszb-cc2652-poe-2023

### Setup

Addon on Homeassistant OS on Proxmox

**Comment by moodyblue** [comment]
In my case the dashboard does not show devices connected through routers, but shows all devices connected directly.

**Comment by sanyafifa** [comment]
the same problem

**Comment by Bloodpack** [comment]
Problem solved for me with the latest update to [v 1.37.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.37.0)
![Zigbee](https://github.com/Koenkk/zigbee2mqtt/assets/26135135/7a08c4ae-9c97-4783-8ac5-cc582c37a5da)
