### ISSUE TITLE
LELLKI Modèle WP33-EU/WP34-EU don't work

### ISSUE THREAD

**Issue by floow77** [Koenkk/zigbee2mqtt#21283]
### What happened?

When I try to update state of switch, I have this error:

`Publish 'set' 'state' to 'Multiprise Bureau' failed: 'Error: Command 0xa4c1384d12bb4cfb/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (144))'`

### What did you expect to happen?

I would like update state "On or Off"

### Zigbee2MQTT version

 1.35.3-1

### Adapter firmware version

Supervisor: 2024.01.1 ; Core: 2024.1.6

### Adapter

conbee2

### Setup

Home Assistant OS ; RPI4

### Debug log

```
Zigbee2MQTT:error 07-02-2024 / 13:45:31: Publish 'set' 'state' to 'Multiprise Bureau' failed: 'Error: Command 0xa4c1384d12bb4cfb/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (144))'
Zigbee2MQTT:info  07-02-2024 / 13:45:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Multiprise Bureau' failed: 'Error: Command 0xa4c1384d12bb4cfb/1 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (144))'","meta":{"friendly_name":"Multiprise Bureau"},"type":"zigbee_publish_error"}
```

**Comment by mrmaximas** [comment]
I saw your ticket and thought I'd check it out. 1.35.3-dev commit: [b7e19cc8] Sonoff P 20221226 - works Ok.
