### ISSUE TITLE
TuYa TS0012_switch_module (_TZ3000_jl7qyupf)

### ISSUE THREAD

**Issue by indevor** [Koenkk/zigbee2mqtt#21294]
### What happened?

TuYa TS0012_switch_module (2 gang switch module - without neutral):
https://www.zigbee2mqtt.io/devices/TS0012_switch_module.html

when two physical buttons are pressed simultaneously, only 1 channel is turned on (off), if you press them one by one, everything is in order.
If you turn on/off simultaneously through GUI interface (automation, calling services simultaneously for two channels) - everything is fine.
The problem is only if you simultaneously turn on/off physical buttons - two at a time.

### What did you expect to happen?

if this is an irrecoverable defect - add a warning here: https://www.zigbee2mqtt.io/devices/TS0012_switch_module.html

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20230507

### Adapter

SONOFF ZBDongle-P Zigbee

### Setup

Add-on on Home Assistant OS (x86-64)

**Comment by klu16** [comment]
It's not confirmed, but a while ago I wondered the same thing as you (I thought they are just faulty and wanted to return them) but many people told me that they just operate like that, so when you press them simultanously, only 1 channel will turn on. And actually, having you tested that both can be switched on at the same time via Z2M/HA, is pointing exactly to a hardware limitation.

If you want to know more or confirm it, just simply ask a vendor about it.

**Comment by jeppester** [comment]
I have the same issue. The problem is not only that simultaneous button presses registers as one; quickly flipping a switch twice only registers as a single button press.

I have several other switch modules that from the same label (avatto). They all work really well and have none of those issues - none of them are no-neutrals though.

This limitation makes the switch module borderline useless for me. I wonder if there is a way to install a firmware update to fix the issue.

Otherwise I'm on the lookout for other 2 channel no-neutral switches that work well.

**Comment by thewzed** [comment]
Same issue. UP.

**Comment by romasku** [comment]
Hi, the problem described here is a firmware bug. You can try [a replacement firmware](https://github.com/romasku/tuya-zigbee-switch) (developed by me) that fixes it.

**Comment by klu16** [comment]
> Hi, the problem described here is a firmware bug. You can try [a replacement firmware](https://github.com/romasku/tuya-zigbee-switch) (developed by me) that fixes it.

Thank you very much! I will definitely test it when I have a spare minute ;)

**Comment by klu16** [comment]
> Hi, the problem described here is a firmware bug. You can try [a replacement firmware](https://github.com/romasku/tuya-zigbee-switch) (developed by me) that fixes it.

Unfortunately, it bricked mine TS0012. It does not even react now to the physical press on the wall switch :( I tried to reset it on the device itself, but it did not help.

**Comment by klu16** [comment]
> > > Hi, the problem described here is a firmware bug. You can try [a replacement firmware](https://github.com/romasku/tuya-zigbee-switch) (developed by me) that fixes it.
> > 
> > 
> > Unfortunately, it bricked mine TS0012. It does not even react now to the physical press on the wall switch :( I tried to reset it on the device itself, but it did not help.
> 
> Same problem. I'll try unplugging it from the 220 power tomorrow.

I turned off/on the fuse for my lights for around 15 seconds and it did not help either... 🙄

**Comment by romasku** [comment]
Hello, 
I'm very sorry to hear that, I'll look into the problem. 
I'll be posting updates here https://github.com/romasku/tuya-zigbee-switch/issues/1

**Comment by klu16** [comment]
> I can recommend the new firmware from @romasku . It solves all the problems with this device and brings many new features.

I can also recommend it! 😊 Custom firmware fixed all the issues and the reaction time is A LOT quicker.
Hats off to you for developing it and for all the support, @romasku 🍻

**Comment by alwin006** [comment]
> Hi, the problem described here is a firmware bug. You can try [a replacement firmware](https://github.com/romasku/tuya-zigbee-switch) (developed by me) that fixes it.

Hi thank you very much ! I just installed your custom firmware on my switch (branded by AVATTO but looked identical to yours)

It is so much faster than before. I had a 1,5s delay every time I pressed the switch until the light turned on. Very annoying but now it's gone and responds instantaneously :)

**Comment by alwin006** [comment]
Is it just me or zigbee2mqtt 2.0 update removed some features @romasku added ?
![image](https://github.com/user-attachments/assets/1fbebcf5-ada1-4864-9045-9f30d9374661)

**Comment by romasku** [comment]
Zigbee2mqtt 2.0 update changed location for custom converters, so it fallbacks to autogenerated one. Now they are inside `external_converters` folder. Please move files and it will work as before. Please check https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/ota_flash.md for details.

**Comment by alwin006** [comment]
Oh I will try that, I did not notice you had updated the documentation. Thanks a lot!
