### ISSUE TITLE
Theme is missing after upgrade

### ISSUE THREAD

**Issue by mhdhamouday** [Koenkk/zigbee2mqtt#21296]
### What happened?

After upgrading to v1.35.3-1 the WEB UI show without CSS and in console there is error message: "Could not find specified theme".
I cleared the web cache but the problem still exists

<img width="1094" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/16991900/e81126cc-ee44-4cb2-a704-312e03a4bc48">

### Zigbee2MQTT version

v1.35.3-1

### Adapter firmware version

20240207.0

### Adapter

Sonsoff universal 

### Setup

add-on

**Comment by stratogk** [comment]
Press the light/dark mode button

**Comment by mhdhamouday** [comment]
@stratogk Thank you very much!

**Comment by ArellanoF** [comment]
Don't work press light/dark mode button, any solutions?
