### ISSUE TITLE
[Wrong device]: Ecodim G125 E27 Smokey gets detected as TuYa TS0502B light controller

### ISSUE THREAD

**Issue by inglenny** [Koenkk/zigbee2mqtt#21293]
### Link

https://www.ecodim.nl/nl/ed-10034.html

### Model

ED-10034

### Description

LED filament lamp dimmable E27, globe G125, Smokey 2000K-4000K

### Vendor

EcoDim

### Picture (link)

https://cdn.webshopapp.com/shops/68389/files/356110082/image.jpg

### Database entry

{"id":34,"type":"Router","ieeeAddr":"0xa4c138ad01f0aa16","nwkAddr":5684,"manufId":4417,"manufName":"_TZ3210_09hzmirw","powerSource":"Mains (single phase)","modelId":"TS0502B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"��T)\u0013��T)\u0012\u0001\u0000\u0000\u0000\u0012\u0001\u0000\u0000\u0000\u0012\u0001\u0000\u0000\u0000\u0012","65506":48,"65508":0,"65534":0,"modelId":"TS0502B","manufacturerName":"_TZ3210_09hzmirw","powerSource":1,"zclVersion":3,"appVersion":91,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"57344":0,"57600":[10,0],"61447":[],"61448":[],"61449":[],"61453":1,"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"tuyaRgbMode":0,"currentHue":null}},"genOnOff":{"attributes":{"61440":0,"onOff":0}},"genLevelCtrl":{"attributes":{"61440":10,"currentLevel":192}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a2ebaeb","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b002a2ebaeb","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0,"manufacturerCode":null},{"cluster":8,"attrId":0,"minRepIntval":1,"maxRepIntval":3600,"repChange":1,"manufacturerCode":null}],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":91,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-2027012541},"lastSeen":1707344862185}

### Notes

Bulb gets detected as TuYa TS0502B. It is fully functional. But the light values seem to be different and not correct. Bulb is much brighter with the same number of brightness compared to other bulbs.

**Comment by thilojaeggi** [comment]
Also have this, maybe they're using a Tuya chip?
