### ISSUE TITLE
Using longer mqtt topic (perhaps starting with /) won't work

### ISSUE THREAD

**Issue by peterforeman** [Koenkk/zigbee2mqtt#213]
I'm using RabbitMQ as MQTT broker (mixed AMQP/MQTT). To be able to mix these environments my MQTT topics must start with a slash. So I'm using a topic like:

 /myhouse/zigbee/...

So: starting with a slash, and two "entries" down (myhouse and zigbee).

Everything was working fine with some aqara sensors which I do not set data to but only read the mqtt messages. Now I added a Hue bulb which I wanted to control. Adding etc. worked fine, but controlling it via mqtt (via HASS) does not. I did not change the friendly name or any other configuration.

`2018-7-24 13:11:30 ERROR Cannot handle '/myhouse/zigbee/0x001788010342e000/set' because deviceID of 'myhouse' cannot be found`

I changed the topic to as default to "zigbee2mqtt/..." (without starting slash and without multiple entries) and now controlling does work. 

From line 408 in controller.js:
```
   handleMQTTMessageDevice(topic, message, withPrefix) {
        const friendlyName = topic.split('/')[1];
        const topicPrefix = withPrefix ? topic.split('/')[2] : '';

        // Map friendlyName to deviceID.
        const deviceID = settings.getIDByFriendlyName(friendlyName);

```
I now understand why it does not work. Perhaps there is a better way to define the mqtt topic and where to find the deviceID? Like:  base_topic: "/myhouse/{deviceID}" ?

**Comment by Koenkk** [comment]
Topic template is already discussed here: https://github.com/Koenkk/zigbee2mqtt/issues/179.

In order to fix this issue we should start parsing from the end instead of the start.

**Comment by peterforeman** [comment]
See #179, closing this.
