### ISSUE TITLE
Nue / 3A LXZB-02A dimmer does not respond to "brightness_move" command.

### ISSUE THREAD

**Issue by johncollaros** [Koenkk/zigbee2mqtt#21307]
### What happened?

Sent the dimmer the "brightness_move" command to brighten or dim
{"brightness_move": 40}
{"brightness_move": -40}

Nothing happened, nothing is registered in the z2m logs.

### What did you expect to happen?

I expected the light to move to full brightness, or dim to lowest brightness

### How to reproduce it (minimal and precise)

In the HomeAssistant MQTT Integration Configuration, using the publish a packet feature, send command to the light dimmer.
This worked for setting a specific brightness value, but not when using the brightness_move command.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

Add-on on Home Assistant Yellow

### Debug log

Debug 2024-02-08 22:57:40Received MQTT message on 'zigbee2mqtt/Kitchen North Overhead Light/set' with data '{"brightness_move": 100}'
Debug 2024-02-08 22:57:40Publishing 'set' 'brightness_move' to 'Kitchen North Overhead Light'

No other state change messages for the light dimmer are recieved.

**Comment by Koenkk** [comment]
Seems the firmware doesn't support this command, nothing we can do from the z2m side here.
