### ISSUE TITLE
IKEA and XIAOMI devices not working after 1.35.3-1 update (and broken frontend)

### ISSUE THREAD

**Issue by kayserjan** [Koenkk/zigbee2mqtt#21303]
### What happened?

1. After updating to 1.35.3-1 all of my IKEA devices (lights) stopped responding (Conbee II)
2. Also XIAOMI motion sensors seem down :/ (no log input, no entity state changes registered)
3. Also the frontend is corrupted on iOS and Android devices. Only on Windows all is fine...

Restore to 1.35.2-1 fixed all the issues.
I attempted 2nd install and it "produced" the same result.

### What did you expect to happen?

Get described fixes.

### How to reproduce it (minimal and precise)

Update Zigbee2MQTT addon 1.35.2-1 to 1.35.3-1

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Setup

HA OS, RPi3, Supervisor

### Debug log

[Info 2024-02-08 092402MQTT publish .txt](https://github.com/Koenkk/zigbee2mqtt/files/14207871/Info.2024-02-08.092402MQTT.publish.txt)

**Comment by alevike** [comment]
Exactly the same problem here. 

Setup
HA OS, Intel NUC, Supervisor

Adapter
ConBee2

**Comment by Creo2005** [comment]
![Screenshot 2024-02-08 125829](https://github.com/Koenkk/zigbee2mqtt/assets/10849149/1325a04b-74ab-43ef-93b9-a944ed9b5f02)
:(

**Comment by Chartreusito** [comment]
Click on the sun/moon button to enable/disable dark mode, it should at least bring the theme back.

**Comment by t-liu93** [comment]
> Click on the sun/moon button to enable/disable dark mode, it should at least bring the theme back.

Thank you @Chartreusito this works.

**Comment by Koenkk** [comment]
- Conbee https://github.com/Koenkk/zigbee2mqtt/issues/21162
- Frontend https://github.com/Koenkk/zigbee2mqtt/issues/21268

**Comment by Rempert** [comment]
Strange operation, I mainly read problems with the conbee II adapter. I use the UZG-01 from Zigstar (IP-based) and have not experienced any problems yet (>120 zigbee devices)
