### ISSUE TITLE
After most recent update (within HASS) plenty of error messages are in log [Zigbee2MQTT:error 2024-02-08 22:14:30: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}]

### ISSUE THREAD

**Issue by tomtom13** [Koenkk/zigbee2mqtt#21317]
### What happened?

Hi,
After updating to newest version 1.35.3, I get plenty of those errors in the log (and also those show up as overlay popups)
Zigbee2MQTT:error 2024-02-08 22:14:30: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Nothing in the system changed between updates.
I've tried rebooting HASS,
rebooting proxmox node - sine HASS is in VM in proxmox (usb passthrough)

### What did you expect to happen?

Not to get an avalanche of errors:
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:50Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:50Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:51Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:51Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:52Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:56Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:57Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:20:00Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:20:01Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}

### How to reproduce it (minimal and precise)

well, I'm using Zonoff USB dongle, passthrough to HASS. Z2M is within HASS. Rather large network (157 devices)

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20210708

### Adapter

zStack3x0 - Sonoff usb ZBDongleB

### Setup

HASS addon, within VM on proxmox

### Debug log

Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:49Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:50Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:50Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:51Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:51Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:52Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:53Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:56Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:57Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:58Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:19:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:20:00Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-08 22:20:01Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}

**Comment by Koenkk** [comment]
You are probably using an in compatible external converter

**Comment by tomtom13** [comment]
Can you please elaborate ? 
USB dongle is on a supported list (actually advised list). It's directly connected to the VM.

**Comment by Koenkk** [comment]
I misinterpreted the logging, can you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by tomtom13** [comment]
FYI, now issues seems to happen every 10-20 seconds (two entries in log)

Error 2024-02-11 22:54:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-11 22:54:59Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-11 22:55:16Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-11 22:55:17Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-11 22:55:28Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}
Error 2024-02-11 22:55:28Exception while calling fromZigbee converter: Cannot read properties of undefined (reading '1')}

I shal enable the debug loggin in a sec and get back to you.

**Comment by tomtom13** [comment]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14234399/log.txt)
here you go.

**Comment by Koenkk** [comment]
Can you provide your data/database.db?

Note to self: problematic device `56694`: `{"attrId":1024,"dataType":42,"attrData":502}`

**Comment by tomtom13** [comment]
from within the z2m container OR hass ?

**Comment by Koenkk** [comment]
z2m container

**Comment by tomtom13** [comment]
Sorry for being nagy - but maybe "what happened" ?
Also I've had a question in the past of how to get into dev / debug on z2m, and nobody gave any pointers (I'm a emb s eng, and I was considering making some small dev for the zigbee - would be nice to have some debug platform)
