### ISSUE TITLE
Value: 'warmest' not found in: [warmest, warm, neutral, cool, coolest]

### ISSUE THREAD

**Issue by duststorm** [Koenkk/zigbee2mqtt#21312]
### What happened?

Upon sending payload `{"color_temp": "warmest"}` to the /set topic of a HG06492A bulb, I get the following error:
`{"message":"Publish 'set' 'color_temp' to 'ledbulb' failed: 'Error: Value: 'warmest' not found in: [warmest, warm, neutral, cool, coolest]'","meta":{"friendly_name":"ledbulb"},"type":"zigbee_publish_error"}`

### What did you expect to happen?

since warmest is a correct setpoint, I expect it to stick

### How to reproduce it (minimal and precise)

Send "warmest" setpoint to the bulb using mqtt

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

20190608

### Adapter

CC2530

### Setup

raspberry pi 2 directly through mqtt

**Comment by mrmaximas** [comment]
In my case with the [ZNLDP13LM] neutral not working, both neutral and warmest are selected at the same time if neutral is pressed, but via z2m web ui
![Screenshot 2024-02-08 at 22 03 15](https://github.com/Koenkk/zigbee2mqtt/assets/61165387/4051e2b0-baca-44ed-950b-d6d0a786b890)
