### ISSUE TITLE
Support for ZN494622_01 Includes working converter -24Ghz Presence detection

### ISSUE THREAD

**Issue by bluestar888** [Koenkk/zigbee2mqtt#21328]
### What happened?

It is wrongly recognized as a  TuYa SZR07U  .
I created a working converter however the device has an ON/OFF virtual switch which Z2M does not trigger and it does not detect  presence until turned ON in the Tuya Smart app. ,so first paired with Tuya app ,enabled than deleted from Tuya and re-added in Z2M.
I tried adding to the converter (seems to be datapoint 102) however it does not pop up in the Z2M device screen.
The switch that shows there is mapped ot datapoint 101 which is the Power LED  which is not really needed if one has to choose :-) 
The device has an alarm as well which I was not able to map.
Cannot add the converter as  js file so added as text.
This what is detected as.
https://www.zigbee2mqtt.io/devices/SZR07U.html
![image](https://github.com/Koenkk/zigbee2mqtt/assets/92831303/204450d5-2019-49e3-9801-6dd2c87f5cab)

In reality it is  this:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/92831303/ddaa2745-042c-46a7-b221-ca3c2bcccbb8)

### What did you expect to happen?

Add support and be recognized properly  .Can't figure out how to contribute directly ,besides being my first try at this don't want to mess up the  repository.

### How to reproduce it (minimal and precise)

Add device ,detected wrong and not working without converter.

### Zigbee2MQTT version

 1.35.3-1

### Adapter firmware version

20220219

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Home Assistant OS - X86-64

### Debug log

[_TZE204_muvkrjr5.txt](https://github.com/Koenkk/zigbee2mqtt/files/14226654/_TZE204_muvkrjr5.txt)

**Comment by Koenkk** [comment]
@blakadder since you added this device in https://github.com/Koenkk/zigbee-herdsman-converters/pull/6712, can you check this?
