### ISSUE TITLE
Supported device is unsupported

### ISSUE THREAD

**Issue by kideg20** [Koenkk/zigbee2mqtt#21342]
### What happened?

I hawe bought Sonoff zigbee SNZB-02D and ZBMINIL2  (they are in supported devices list). 
But this happens when I try to add them to my HomeAssistant.
```
Zigbee2MQTT:warn  2024-02-10 21:32:21: Device '0x3c2ef5fffebc3ad1' with Zigbee model 'SNZB-02D' and manufacturer name 'SONOFF' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Zigbee2MQTT:warn  2024-02-10 21:41:50: Device 'ZBMINIL2' with Zigbee model 'ZBMINIL2' and manufacturer name 'SONOFF' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

### Zigbee2MQTT version

1.18.1-1

### Adapter firmware version

20210120

### Adapter

zStack3x0

### Setup

Ubuntu 22.04 KVM vm with HA as image.

**Comment by Koenkk** [comment]
You are using an heavily outdated version (1.18.1), switch to new [new addon](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt)
