### ISSUE TITLE
Zigbee2mqtt stops responding after random time 

### ISSUE THREAD

**Issue by wormvortex** [Koenkk/zigbee2mqtt#21378]
### What happened?

At a random point it will just stop responding and allowing me to control devices or tell that a device is online/offline.

I have it connected to 11 bulbs all controlled by dumb switches (I know this isn't ideal! but I like actual switches to control on/off states). 

At a random point in time the bulbs will all show as offline regardless as to whether I turn them on/off physically and the only way to fix it is to restart the docker container. The actual container is still running as I can see it writing to the logs though only the command "Saving state to file /app/data/state.json". I can also still access the UI and change settings etc...

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

6.7.8.0 build 373

### Adapter

Sonoff bridge

### Setup

docker contrainer on linux

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14257653/log.txt)

**Comment by Bigsmooth68** [comment]
Hi @wormvortex 
Did you checked the CPU and memory usage ?
I opened a similar issue just before finding yours #21393.

**Comment by Bigsmooth68** [comment]
My question was more about memory and cpu usage of nodejs process from z2m itself.
