### ISSUE TITLE
[Wrong device]: MiBoxer FUTC11ZR is shown as Tuya TS0505B

### ISSUE THREAD

**Issue by RaFromNE** [Koenkk/zigbee2mqtt#21382]
### Link

https://miboxer.com/product/12w-rgbcct-led-garden-light-zigbee-3-0-2-4g

### Model

FUTC11ZR

### Description

Outdoor light

### Vendor

MiBoxer

### Picture (link)

https://miboxer.com/wp-content/uploads/FUTC11.jpg

### Database entry

{ 	"id": 33, 	"type": "Router", 	"ieeeAddr": "0xa4c1387d20342431", 	"nwkAddr": 13226, 	"manufId": 4417, 	"manufName": "_TZB210_zmppwawa", 	"powerSource": "Mains (single phase)", 	"modelId": "TS0505B", 	"epList": [ 		1, 		242 	], 	"endpoints": { 		"1": { 			"profId": 260, 			"epId": 1, 			"devId": 269, 			"inClusterList": [ 				3, 				4, 				5, 				6, 				4096, 				8, 				768, 				61184, 				0 			], 			"outClusterList": [ 				25, 				10 			], 			"clusters": { 				"genBasic": { 					"attributes": { 						"modelId": "TS0505B", 						"manufacturerName": "_TZB210_zmppwawa", 						"powerSource": 1, 						"zclVersion": 3, 						"appVersion": 64, 						"stackVersion": 0, 						"hwVersion": 1, 						"dateCode": "" 					} 				}, 				"lightingColorCtrl": { 					"attributes": { 						"colorCapabilities": 29, 						"colorMode": 2, 						"currentX": 0, 						"currentY": 0, 						"currentHue": 16, 						"currentSaturation": 16, 						"colorTemperature": 0 					} 				}, 				"genOnOff": { 					"attributes": { 						"onOff": 1 					} 				}, 				"genLevelCtrl": { 					"attributes": { 						"currentLevel": 254 					} 				} 			}, 			"binds": [], 			"configuredReportings": [], 			"meta": { 				"onLevelSupported": false 			} 		}, 		"242": { 			"profId": 41440, 			"epId": 242, 			"devId": 97, 			"inClusterList": [], 			"outClusterList": [ 				33 			], 			"clusters": {}, 			"binds": [], 			"configuredReportings": [], 			"meta": {} 		} 	}, 	"appVersion": 64, 	"stackVersion": 0, 	"hwVersion": 1, 	"dateCode": "", 	"zclVersion": 3, 	"interviewCompleted": true, 	"meta": { 		"configured": 1842547789 	}, 	"lastSeen": 1707776994217, 	"defaultSendRequestWhen": "immediate" }

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
