### ISSUE TITLE
No converter available

### ISSUE THREAD

**Issue by chrkir** [Koenkk/zigbee2mqtt#21394]
### What happened?

Hi all,
I use a ESP32-H2(C6) and Software from ESP-IDF to connect via zigbee to a CC5231-basec coordinator. Everything is working except the state update of the toggle-switch. The customized model definition for the device I found doesn't catch the problem.
![Bildschirmfoto vom 2024-02-14 10-24-15](https://github.com/Koenkk/zigbee2mqtt/assets/31239652/7a6169e2-d9db-4b58-a125-e8be0fd995dc)
![Bildschirmfoto vom 2024-02-14 10-22-34](https://github.com/Koenkk/zigbee2mqtt/assets/31239652/1dfb40d1-e68e-4617-941c-80e137191e81)
![Bildschirmfoto vom 2024-02-14 10-22-00](https://github.com/Koenkk/zigbee2mqtt/assets/31239652/eb694dc8-0696-47d9-8367-2ea4f70d283f)

### What did you expect to happen?

If possible, could one please give me a hint how I could fix the Problem.

### How to reproduce it (minimal and precise)

I think the attached picture of traces are clear enough.

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

CC2531_default_20211115

### Adapter

CC2531

### Setup

For debug, npm start

### Debug log

debug 2024-02-14 10:18:47Device 'Keypad' announced itself
info 2024-02-14 10:18:47MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Keypad","ieee_address":"0x404ccafffe4b6c54"},"type":"device_announce"}'
debug 2024-02-14 10:18:49Retrieving state of 'Keypad' after reconnect
debug 2024-02-14 10:18:49Received Zigbee message from 'Keypad', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
info 2024-02-14 10:18:49MQTT publish: topic 'zigbee2mqtt/Keypad', payload '{"linkquality":110,"state":"OFF"}'
debug 2024-02-14 10:18:50Device 'Keypad' announced itself
info 2024-02-14 10:18:50MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Keypad","ieee_address":"0x404ccafffe4b6c54"},"type":"device_announce"}'
debug 2024-02-14 10:18:52Retrieving state of 'Keypad' after reconnect
debug 2024-02-14 10:18:52Received Zigbee message from 'Keypad', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
info 2024-02-14 10:18:52MQTT publish: topic 'zigbee2mqtt/Keypad', payload '{"linkquality":110,"state":"OFF"}'
debug 2024-02-14 10:19:06Received Zigbee message from 'Keypad', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
debug 2024-02-14 10:19:06No converter available for 'Keypad' with cluster 'genOnOff' and type 'commandOn' and data '{}'
debug 2024-02-14 10:19:42Received Zigbee message from 'Keypad', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
debug 2024-02-14 10:19:42No converter available for 'Keypad' with cluster 'genOnOff' and type 'commandOff' and data '{}'
debug 2024-02-14 10:20:46Received Zigbee message from 'Keypad', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
debug 2024-02-14 10:20:46No converter available for 'Keypad' with cluster 'genOnOff' and type 'commandOn' and data '{}'
debug 2024-02-14 10:21:55Saving state to file /opt/zigbee2mqtt/data/state.json

**Comment by Kazarnikov** [comment]
The problem is when publishing the temperature value in the topic "sensor_temp". It worked correctly before the update
[Aqara SRTS-A01](https://www.zigbee2mqtt.io/devices/SRTS-A01.html)


debug 2024-02-16 13:04:40Received MQTT message on 'zigbee2mqtt/0x54ef431000745a3b/set/sensor_temp' with data '25'
error 2024-02-16 13:04:40No converter available for 'sensor_temp' (25)
