### ISSUE TITLE
IKEA Devices (SYMFONISK E2123 and TRADFRI GU10 CWS) Connectivity Issues

### ISSUE THREAD

**Issue by Lymestone** [Koenkk/zigbee2mqtt#21399]
### What happened?

Dear all, 

I am experiencing connectivity issues with two IKEA devices in my Zigbee2MQTT setup. While other devices like Lidl Smart Lights, Tuya Thermostat, and IKEA TRADFRI ON/OFF switch are working correctly and the server receives payloads from them without issues, however the IKEA SYMFONISK Button (E2123) and the IKEA TRADFRI Bulb GU10 CWS 345lm encounter problems maintaining a connection.

**I am using Zigbee2mqtt on HomeAssistant OS, Raspberry Pi 4 with a Conbee III stick.** 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/76051233/f384e60a-286a-4ffd-a449-45812a36887a)

**IKEA SYMFONISK Button (E2123):** This device connects to the network initially but fails to sustain the connection. No button inputs are recognized at all.
**IKEA TRADFRI Bulb GU10 CWS 345lm:** Similar to the SYMFONISK Button, this device can connect to the network but fails to update or maintain the connection afterward (can't change color, turn off) 

Troubleshooting Steps Tried:

Ensured that Zigbee2MQTT is up to date.
Checked the range and interference, placing the problematic devices closer to the coordinator.
Restarted Zigbee2MQTT and the MQTT broker.
Removed and re-paired the devices multiple times.
Checked logs for any errors related to these devices but found none that could explain the connectivity issues.

The thing bothering me me most is definitely the Tradfari button. It connects but when connected does not receive anything from the button. 

Thanks in advance. 

### Zigbee2MQTT version

1.35.3.1

### Adapter firmware version

0x264f0900

### Adapter

Conbee III 

### Setup

Home Assistant OS, Raspberry Pi 4

### Debug log
_For the E2123 button_ happens when clicking reconfigure in zigbee2mqtt

Info 2024-02-14 18:47:21Configuring '0x385b44fffe390620'
Error 2024-02-14 18:48:22Failed to configure '0x385b44fffe390620', attempt 3 (Error: Bind 0x385b44fffe390620/1 genOnOff from '0x00212effff0e1c3d/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:776:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:1204:13) at Configure.configure (/app/lib/extension/configure.ts:120:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
Info 2024-02-14 18:48:22MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x385b44fffe390620"},"error":"Failed to configure (Bind 0x385b44fffe390620/1 genOnOff from '0x00212effff0e1c3d/1' failed (waiting for response TIMEOUT))","status":"error","transaction":"7d0a3-1"}'

_For the GU 10 LIGHT (which happens after changing the color in HAOSS:_
Error 2024-02-14 18:40:42Publish 'set' 'brightness' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genLevelCtrl.moveToLevelWithOnOff({"level":157,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (112))'
Info 2024-02-14 18:40:42MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":157,\"transtime\":0}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (112))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:43Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (114))'
Info 2024-02-14 18:40:43MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (114))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:43Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (113))'
Info 2024-02-14 18:40:43MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (113))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:44Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (116))'
Info 2024-02-14 18:40:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (116))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:44Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (115))'
Info 2024-02-14 18:40:44MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (115))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:45Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (120))'
Info 2024-02-14 18:40:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (120))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:45Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (119))'
Info 2024-02-14 18:40:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (119))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:45Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (118))'
Info 2024-02-14 18:40:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (118))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:45Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (117))'
Info 2024-02-14 18:40:45MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (117))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:46Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (123))'
Info 2024-02-14 18:40:46MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (123))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:46Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (122))'
Info 2024-02-14 18:40:46MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (122))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:46Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (121))'
Info 2024-02-14 18:40:46MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (121))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:54Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":38600,"colory":21561}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (125))'
Info 2024-02-14 18:40:54MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({\"transtime\":0,\"colorx\":38600,\"colory\":21561}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (125))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:54Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":38600,"colory":21561}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (124))'
Info 2024-02-14 18:40:54MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({\"transtime\":0,\"colorx\":38600,\"colory\":21561}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (124))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:55Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":38600,"colory":21561}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (127))'
Info 2024-02-14 18:40:55MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({\"transtime\":0,\"colorx\":38600,\"colory\":21561}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (127))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'
Error 2024-02-14 18:40:55Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({"transtime":0,"colorx":24313,"colory":15663}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (126))'
Info 2024-02-14 18:40:55MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color' to '0x30fb10fffe0479f5' failed: 'Error: Command 0x30fb10fffe0479f5/1 lightingColorCtrl.moveToColor({\"transtime\":0,\"colorx\":24313,\"colory\":15663}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received (126))'","meta":{"friendly_name":"0x30fb10fffe0479f5"},"type":"zigbee_publish_error"}'

**Comment by ctournayre** [comment]
+1 Same problem here, same SYMFONISK and TRADFRI with Conbee III.

**Comment by zurnib** [comment]
+1 same here with STYRBAR and Slaesh's CC2652RB stick

**Comment by ctournayre** [comment]
FIXED, found a workaround. For LED just after pairing successfully (all appears in HA) I switch off the LED physically (by turning the physical switch OFF). Then turn back ON and all the LED are working great now. No more desync.

**Comment by Lymestone** [comment]
Does that also fix the issue with the Symfonisk (pulling battery shortly after pairing)?
If so, gonna give it a try when i get back from work.
