### ISSUE TITLE
Group of blinds do not open/close due to "'TypeError: Cannot read properties of null (reading 'manufacturerName')'"

### ISSUE THREAD

**Issue by seniorgoon** [Koenkk/zigbee2mqtt#21417]
### What happened?

I have grouped together 16 blinds in Z2M under the name of "Blinds Group (All)". Using ConBee II stick. Within the group, I am able to control (i.e., open/close) all of the blinds independently without any errors; however, when I try to open/close the blinds within a HomeAssistant automation, I receive the following log:

```
Error 2024-02-15 13:27:29 Publish 'set' 'state' to 'Blinds Group (All)' failed: 'TypeError: Cannot read properties of null (reading 'manufacturerName')'

Info 2024-02-15 13:27:29 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Blinds Group (All)' failed: 'TypeError: Cannot read properties of null (reading 'manufacturerName')'","meta":{"friendly_name":"Blinds Group (All)"},"type":"zigbee_publish_error"}'

Debug 2024-02-15 13:27:29 TypeError: Cannot read properties of null (reading 'manufacturerName') at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/legacy.ts:6143:67) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:52) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23) at EventEmitter.emit (node:events:529:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:115:22) at MQTT.onMessage (/app/lib/mqtt.ts:141:27) at MqttClient.emit (node:events:517:28) at handlePublish (/app/node_modules/mqtt/src/lib/handlers/publish.ts:172:11) at handle (/app/node_modules/mqtt/src/lib/handlers/index.ts:29:17) at work (/app/node_modules/mqtt/src/lib/client.ts:726:17)
```

The manufacturer name for each of the blinds is simply "TuYa" and each blind within the group has TuYa listed as the manufacturer, so I do not know what "null" here could possibly mean.  I've tried reducing the group down to just 3 blinds and receive the same error.

Any ideas? I tried looking around and couldn't find anything, but am happy to even be pointed to resources.

edit: I actually initially had this as a helper group in HA. It worked for a few days 100% fine, but then a few of the blinds stopped working unless I manually re-launched the open/close action. I made the same group in Z2M after reading that that approach would hopefully work better since it seemed likely sending 16 requests was likely what was causing the random blinds to not respond.

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

0x26780700

### Adapter

Phoscon ConBee II

### Setup

Add-on on Home Assistant OS on Intel NUC

**Comment by Koenkk** [comment]
TuYa devices use a special protocol, which AFAIK doesn't support group commands..
