### ISSUE TITLE
z2m won't update state of Hue Go portable table lamp white if toggle it on/off manually

### ISSUE THREAD

**Issue by tuxiano** [Koenkk/zigbee2mqtt#21425]
### What happened?

Hi, if I press the button at the top of the Hue Go I can switch the lamp on/of or change its color. This works as expected. Unfortunately z2m does not update the state, color etc. This is causing issues in combination with the adaptive light integration for home assistant, because the lamp is still reported in state "on" it still receive instructions from the adaptive light integration, which finally causes that lamp is getting switched on again after 20-30 seconds.

If I hit the refresh button in the web-interface it updates the state correctly.

### What did you expect to happen?

I would expect, that z2m observes correctly the state, brightness etc. of the Hue Go, even if I switch it on/off manually

### How to reproduce it (minimal and precise)

1. Install the adaptive light integration in HA
2. Add the Hue GO to an adaptive light entry
3. Switching the Hue GO manually off (pressing the button at the top of the lamp)
4. Wait for 20-30 seconds
5. Lamp will turn on again

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

1.104.3

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus,Zigbee Gateway TI CC2652P + CP2102N

### Setup

Add-on in HA, Generic x64 image

**Comment by bmbob** [comment]
Had the same issue with mine, it has worked so farafter setting the onOff attribute in Reporting

![image](https://github.com/user-attachments/assets/f6c72644-f464-4200-ab38-9cd184071b77)
