### ISSUE TITLE
Legrand 064873 now unpairable

### ISSUE THREAD

**Issue by syntesys87** [Koenkk/zigbee2mqtt#21454]
### What happened?

Hello,

I had a zigbee2mqtt with two Legrand 064873 paired. This morning, I deleted one of these erroneously, but now is impossible to re-pair. I press the reset button, the pairing process starts even without enable the join from z2m, tle green led blinks and pair, but after 10-15 seconds it says 'the device left the network' and then starts the interviewing and then leave the network and so on, until I see and error message followed by 'Zigbee2MQTT has been started!'.

Failed to configure '0x0004740000cb7ef4', attempt 1 (Error: {"address":19576,"clusterId":32801,"sequence":127} after 10000ms at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at Driver.zdoRequest (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:667:43) at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:566:13 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/legrand.ts:418:13) at Configure.configure (/app/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

7.4.0.0 Build 0

### Adapter

EZSP v12 SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

HAOS

### Debug log

[log1.txt](https://github.com/Koenkk/zigbee2mqtt/files/14323028/log1.txt)
[log2.txt](https://github.com/Koenkk/zigbee2mqtt/files/14323029/log2.txt)
[log3.txt](https://github.com/Koenkk/zigbee2mqtt/files/14323030/log3.txt)

**Comment by Koenkk** [comment]
Probably the same as https://github.com/Koenkk/zigbee2mqtt/issues/21277
