### ISSUE TITLE
[Feature request]: LiXee ZLinky_TIC add expose in Tempo

### ISSUE THREAD

**Issue by Descagir** [Koenkk/zigbee2mqtt#21450]
### Is your feature request related to a problem? Please describe

I would like to monitor in HA the following expose (status_register_tempo_jour) :
<img width="812" alt="3" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/79df3444-9307-43ea-94b2-4f3ce3cb69bb">

I have the following setup :
<img width="640" alt="6" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/df8aee33-a8c9-401c-b04e-968636aaa8a9">

### Describe the solution you'd like

I am guessing that this is the following expose :
<img width="799" alt="5" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/0818bb54-971b-4029-88b4-cb1f7c0cdfb3">
<img width="811" alt="4" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/6a68f5d6-15cc-496a-a832-f7d9a46bf620">
But it is not enable in Tarif Standard Tempo. If I add "DEMAIN" in TIC command Whitelist, report of DEMAIN doestn't work.

### Describe alternatives you've considered

nope.

### Additional context

Any help is welcome.

**Comment by mildis** [comment]
According to reference doc [Enedis-NOI-CPT_54E](https://www.enedis.fr/media/2035/download), section 6.2.3.14, 'Registre de statuts', tomorrow_color is only set for *legacy mode*.  
For all others mode including 'standard mode', this value is set to 0, "not announced".

**Comment by Descagir** [comment]
Thank you for your time and answer. 
Nevertheless, as you can see in my first post and the following picture, the "status_register_tempo_jour : BLANC" is working and the value is in the log.
<img width="801" alt="2" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/b85a0bd2-6bf2-44c8-8eb0-5a55eef6f04a">
Is it possible to add this register, in the expose section ?
It's interesting to monitor the color of the day. In function, (ex: if it's ROUGE (RED)), we can turn off the switches.

**Comment by mildis** [comment]
You should get the current color in the `LTARF` exposed value.  
It matches the `current_price` key in the json.  

Status register provides tempo color (`tempo_jour`) and HP/HC (`tarif_dist` and `tarif_four`) separately.

**Comment by Descagir** [comment]
Indeed.
<img width="268" alt="2" src="https://github.com/Koenkk/zigbee2mqtt/assets/155376497/f631744d-5a25-42a7-a2dc-0f9f4830a20f">
I didn't guess that. Thank you.
Is it possible to only have the tempo color : "BLEU", "BLANC" et "ROUGE" ?
Thank you in advance.

**Comment by mildis** [comment]
Unfortunately no.  
This is a value sent by the provider, so different providers could name their tariff differently.  
Register status is decoded per Enedis specs until another provider arise.

**Comment by Descagir** [comment]
Ok.
In HA, is it possible to extract only the second term of the expose (so, the color) ? And put the second term in a new variable ? 
In Python, it's ok (=> str.split()[1]). But in HA..
Thank you for your time.

**Comment by mildis** [comment]
Sorry, I don't know HA (I'm using Jeedom :) )
Look for action/methods like 'contains' or 'endWith' to match the terms.
