### ISSUE TITLE
Group out of sync with reality/devices

### ISSUE THREAD

**Issue by jamesonuk** [Koenkk/zigbee2mqtt#21465]
My rooms generally have multiple IKEA GU10 bulbs assigned to a group and a Hue wall switch module bound to that group.   This works great but I keep ending up with the wrong status showing up.

Eg. I turned on bedroom lights via HA and turned it off via switch.   HA shows the group as on
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/59ffb5ae-777f-4f63-8f24-566ef76914bb)
because some of the lights in the group are still showing up as on (even though they are definitely off)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/672b68d7-d8a1-4c12-b01f-56433706b34c)
At this moment when I flick the switch to toggle the lights via the Hue wall switch then according to Z2M/HA it is essentially toggling the "Door Window" bulb but in reality it is toggling all six.;   When they get inconsistent I need to toggle it twice to bring it back into sync.

This isn't always exactly the same and I can't quite put my finger on a pattern.
Just turning the Study lights off and Z2M is correctly showing the full bulbs as off
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/3be4b46d-0c8b-468c-8d2d-33a65c20de72)
but HA is showing the group as on
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/59654b48-9476-4e69-8a8b-5dccbba8fdb6)

This is happening with multiple rooms and it isn't always the same bulbs / rooms.   Sometimes it works but rooms are often out of sync.   This seems to be mainly the case when the group is switched toggled by local binding or HA and then toggled by the other (eg. turned on via local switch and then off via HA or on via HA and then off via switch).   Turning on/off via the same method seems to be much better (but not 100%)

All the Hue wall switches are added to the groups and bound like this 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1040621/bc998e3a-0bb2-4e3c-a688-2366073c666c)

Any ideas on what is going on?

_Originally posted by @jamesonuk in https://github.com/Koenkk/zigbee2mqtt/discussions/21235_

**Comment by RezzZ** [comment]
I have the same problem when activating scenes from homeassistant.
The scenes get activated but sometimes (most times) group statuses are not updated. I have several overlapping groups and sometimes all update, most times only one group will update resulting in automations to fail.
Individual light statuses are still displayed correct in HA. It's only the group statuses that are out of sync.

**Comment by RezzZ** [comment]
Anyone able to look into this by any chance? groups are still out of sync when turning on a light/group.

I have the following groups:
Living
Living Duos
Dining
Living & Dining (with all device from Living & Dining)
Kitchen
Downstairs (with all devices in Living, Living Duos, Dining and Kitchen)

When triggering a scene in the group Living & Dining using my Hue Tab and the Switch Manager integration (from HACS), the lights go on perfectly, but the group status in Homeassistant stays off, sometimes only dining goes on, sometimes dining and Downstairs, sometimes only Living... Can wrap my head around this and why it is failing. Any help?
