### ISSUE TITLE
NodON SIN-4-FP-21 Mode

### ISSUE THREAD

**Issue by Cityloue15** [Koenkk/zigbee2mqtt#21469]
### What happened?

Hello, following the integration of the SIN-4-FP-21 module from NodON, I do not have modes such as comfort, eco etc...

### What did you expect to happen?

I was expecting to see the actions/information mode

### Zigbee2MQTT version

 1.33.2

### Adapter firmware version

26780700

### Adapter

ConBee2

### Setup

 Debian GNU/Linux 10 (buster) 64bits (aarch64)

**Comment by courville** [comment]
Perhaps could be considered as duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/21071

**Comment by MichaelMure** [comment]
Possibly related: https://github.com/Koenkk/zigbee2mqtt/issues/22068
