### ISSUE TITLE
Docker container on latest-dev failed to start

### ISSUE THREAD

**Issue by LCerebo** [Koenkk/zigbee2mqtt#2146]
# Bug Report
I'm trying the latest dev version of zigbee2mqtt docker container and I can't start it. I receive the following errors:
[logs](https://pastebin.com/embed_js/8PUghyma)

## How to reproduce it (minimal and precise)
Pull and run latest-dev docker container.
## Debug Info
zigbee2mqtt version: 1.6.0 (commit #4164f01)

**Comment by paskyecijano** [comment]
Same error

**Comment by Koenkk** [comment]
Fixed in latest dev.

**Comment by LCerebo** [comment]
Solved with referenced commit.
