### ISSUE TITLE
[New device support]: Paulmann LED Reflektor GU10

### ISSUE THREAD

**Issue by markaragnos81** [Koenkk/zigbee2mqtt#21472]
### Link

https://de.paulmann.com/p/standard-230v-smart-home-zigbee-3.0-led-reflektor-gu10-350lm-4-8w-rgbw-dimmbar-schwarz-matt/29148

### Database entry

0xa4c13800ab372095

### Comments

Please help me add this

### External definition

```shell
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const {} = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;
const definition = {
    zigbeeModel: ['291.48'],
    model: '291.48',
    vendor: 'Paulmann Licht GmbH',
    description: 'Paulmann LED Reflektor GU10 350lm 4,8W RGBW',
    extend: extend.light_onoff_brightness_colortemp_color(),
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Could you try with the [generated external converter](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition) instead?

**Comment by markaragnos81** [comment]
I have tried, but I am probably too stupid

**Comment by Isy99** [comment]
Is it possible to re-activate this issue?
The device Paulmann 29148 is detected as Paulmann 291.52 and shows error messages. On/off and white is controlable, color not.
`Error 2024-11-23 11:24:34z2m: Failed to read state of 'ku_Leuchte_Fenster_re' after reconnect (ZCL command 0xa4c13800ad3118f9/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 60687 - 1 - 62 - 6 - 1 after 10000ms))`
