### ISSUE TITLE
Bosch BTH-RA broken (PI heating demand, system mode, local temperature calibration)

### ISSUE THREAD

**Issue by apfffr** [Koenkk/zigbee2mqtt#21498]
### What happened?

I really only looked closer at this when the version came where the auto mode for the BTH-RA disappeared. It was not usefull but it made me look at this device closer.

I noticed the local temperature was at 23°C (confirmed by second thermometer) and the device would still have the valve open.  Heating setpoint was at no time above 21,5°C. I then tried around and noticed that even when I turn the thing to "off" it wouldn't close the valve.

I removed the device from the heating and put it back and did the calibration again and changed my automations from switching between off/19,5°C/21,5°C to just switch between 5°C/19°C/21,5°C.

This seemed to work at first but I monitored closer and found that the local temperature was 23°C, set point 19°C. PI heating demand was 11%. So even beeing above the mark it did still keep on heating.

Temperature dropped to 22°C, set point 19°C and PI heating demand went UP to 14%, still beeing solid 3°C aboce the set point.

I wanted to use local temperature calibration to counter this issue and set it to 3°C. Now the local temperature is shown as 9,7°C (other thermometer shown 22,6°C) so it's way off and no matter what value I put in local temperature calibration, it keeps staying at 9,7°C. And the best thing, I set set point to 5°C and it still has the valve at 10% open... What is this?

Also its confusing that PI heating demand is an actual input slider?? I think it should just display the value the system choses?

So issues:
- PI heating demand is set too high
- PI heating demand should not be an input slider
- Local temperature calibration does not work
- Setting system mode to off should close the valve (so 0% PI heating demand)

I am not sure how this is tied together. Maybe just one little thing made all this go crazy?

### Zigbee2MQTT version

 1.35.3

### Adapter firmware version

20210708

### Adapter

Electrolama zzh

### Setup

Node.js on Windows Server VM on Proxmox

**Comment by dierochade** [comment]
auto mode is reimplemented.

the heating algorithm is kinda special, there is a lot of resources and discussions out there. I do not think this is something related to zigbee/how the device connects to the network but the internal firmware? maybe this could be overriden by the bridge/homeassistant/whatever, but not with z2m?
