### ISSUE TITLE
Zigbee2mqtt keeps crashing? 

### ISSUE THREAD

**Issue by LuME3N** [Koenkk/zigbee2mqtt#21505]
### What happened?

Trying to setup zigbee2mqtt. 

### What did you expect to happen?

It should work

### How to reproduce it (minimal and precise)

Starting up zigbee2mqtt, it seems to work can load the ui. After that I try to chance configuration in ZHA. Then zigbee2mqtt stops and won't startup. 

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

20221031094351

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

Hp thin client

### Debug log

debug 2024-02-20 22:02:27: Loaded state from file /config/zigbee2mqtt/state.json
info  2024-02-20 22:02:27: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-20.22-02-27' filename: log.txt
debug 2024-02-20 22:02:27: Removing old log directory '/config/zigbee2mqtt/log/2024-02-06.19-39-07'
info  2024-02-20 22:02:27: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
info  2024-02-20 22:02:27: Starting zigbee-herdsman (0.33.8)
debug 2024-02-20 22:02:27: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031094351-if00"}}'
error 2024-02-20 22:03:37: Error while starting zigbee-herdsman
error 2024-02-20 22:03:37: Failed to start zigbee
error 2024-02-20 22:03:37: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-02-20 22:03:37: Exiting...
error 2024-02-20 22:03:37: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:364:19)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:158:13)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

**Comment by Koenkk** [comment]
You cannot use the same adapter for both ZHA and Z2M
