### ISSUE TITLE
Crash report - Opt-in - Issue Tracker

### ISSUE THREAD

**Issue by tech2mar** [Koenkk/zigbee2mqtt#21524]
### Is your feature request related to a problem? Please describe

First, I want to commend Koen and the entire community for the excellent work you’re doing with Zigbee2MQTT. Your efforts are truly appreciated.

However, our community has been experiencing some issues related to firmware, compilation, and device stability. It is sometimes unclear whether these issues stem from the devices themselves or other factors. Identifying and addressing these problems is crucial for improving our network reliability.

Given the importance of maintaining a stable network, especially for those of us with dependents relying on consistent service at home, I believe we need to adopt a new approach to tackle these challenges effectively.

I would like to suggest an opt-in feature for sending anonymous reports in the event of coordinator crashes or network outages. Specifically, if a device goes offline after a certain period without user interaction, this behavior should be tracked and reported automatically. This data could be invaluable for diagnosing and resolving issues more efficiently.

I understand this would involve filtering and interpreting a significant amount of information, but I am confident that this approach would help us enhance the performance and reliability of our networks.

Thank you for considering this suggestion. I am looking forward to any feedback or discussion on how we can implement this feature to better serve our community.

Best regards,  

### Describe the solution you'd like

1. Tracking Device Routing Problems: Collecting data on devices that cause routing issues, such as excessive route changes or failures in maintaining stable routes.
2. Monitoring Sleep Patterns of End Devices: Identifying end devices that exhibit non-standard sleep patterns, differing from the default configuration, which may affect network stability.
3. Automated Reporting: Automatically sending anonymous reports when a device goes offline after a specified period without user interaction. This would include details on the device type, firmware version, and any error messages or logs available.

### Describe alternatives you've considered

The alternatives are more complicated and take more time. 

### Additional context

No information

**Comment by tech2mar** [comment]
Thanks.

**Comment by Koenkk** [comment]
> device goes offline after x time without any user interaction, we should be able to track that kind of behaviour.

Although the idea sounds nice, what would you want to do with this info? You need a lot of context and probably sniffs to determine what happened, right?

**Comment by tech2mar** [comment]
Indeed not a simple thing, but creating some sniffing possibility to z2m?. I'm way to far from network engendering just asking questions and maybe asking for something impossible to do.

**Comment by tech2mar** [comment]
I know the firmware is different, I came from the Conbee world (using a Wireshark modified version. And a Conbee with a different fw for sniffing.... ...it is nothing that could be done overnight.
My take on this is that maybe we can collect more information about z2m behaviour...
Maybe we could send out logs automatically?
Something the community can do.
