### ISSUE TITLE
TS011F_plug_3 - described "energy reset" breaks energy, voltage and current measurement

### ISSUE THREAD

**Issue by oberschwabe** [Koenkk/zigbee2mqtt#21525]
### What happened?

wanted to reset total energy consumption on a BlitzWolf BW-SHP15 as described in the documentation:
_To reset "Sum of consumed energy", use the Dev console and execute: Endpoint: 1 Cluster: 0x00 Command: 0 Payload: (don't change this). Next time the plug gets polled, "Sum of consumed energy" will start from zero again._
However after execution of the command the sum of consumed energy starts from 0 but the measurement of current, power and voltage is now NULL and no measurement is taken any more.
remove and re-pair didn´t help.

### What did you expect to happen?

measurement of current, power and voltage is still working 

### How to reproduce it (minimal and precise)

execute same command on another device

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20230507

### Adapter

Sonoff

### Setup

plain on Pi 4b

**Comment by Koenkk** [comment]
This command sends a factory reset, to reconfigure the device use the yellow reconfigure button from the z2m frontend.
