### ISSUE TITLE
add device type filter to zigbee2mqtt.io page 

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#2152]
For Users who are on a fast search of supported Devices on Z2M it would be great if we could filter Device Types on https://www.zigbee2mqtt.io/information/supported_devices.html with simple filter like:

- Lights
- Relais
- Thermostat
-  .....

**Comment by Koenkk** [comment]
Is it possible to add dynamic elements to a Jekyll generated page?

**Comment by tb-killa** [comment]
Hmm doesn't seem so.
Maybe with categories?
https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/
