### ISSUE TITLE
Legrand shutter 067776 - Error setting/changing Attributes "Blink", "LED in dark" and "LED if on"

### ISSUE THREAD

**Issue by pickard1** [Koenkk/zigbee2mqtt#21589]
### What happened?

I use the HomeAssistant Addon

Pressing e.g. "Blink" in Details page results in an error 

### What did you expect to happen?

LED should blink

### How to reproduce it (minimal and precise)

Simple press "Blink" in Detail page

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

0x26450900

### Adapter

Conbee3

### Setup

Add-On Home Assistant on raspberry pi

### Debug log

Debug 2024-02-26 20:44:24Received MQTT message on 'zigbee2mqtt/Schlafzimmer.Rolladen/set' with data '{"identify":"blink"}'
Debug 2024-02-26 20:44:24Publishing 'set' 'identify' to 'Schlafzimmer.Rolladen'
Error 2024-02-26 20:44:24Publish 'set' 'identify' to 'Schlafzimmer.Rolladen' failed: 'Error: undefined is not a object, got string ("blink")'
Debug 2024-02-26 20:44:24Error: undefined is not a object, got string ("blink") at Object.assertObject (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:518:15) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:3749:19) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:52) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23) at EventEmitter.emit (node:events:529:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:115:22) at MQTT.onMessage (/app/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:130:27) at WebSocket.emit (node:events:517:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1209:20)
Info 2024-02-26 20:44:24MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'identify' to 'Schlafzimmer.Rolladen' failed: 'Error: undefined is not a object, got string (\"blink\")'","meta":{"friendly_name":"Schlafzimmer.Rolladen"},"type":"zigbee_publish_error"}'

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
