### ISSUE TITLE
Feature Request - Option to change zigbee channel for routers

### ISSUE THREAD

**Issue by aidbish** [Koenkk/zigbee2mqtt#216]
It would be good if the routers were able to operate on a different zigbee channel than the hard-coded channel 11 they use at the moment
this would allow you to set a channel that gets less interference with your or neighbours WIFI channels.

For me zigbee channel 11 is covered by WiFi channel 1, which i have to use to get decent Wifi in areas around the house that is not interfered with by neighbours WiFi signals.

See this article here for information on the zigbee and WiFi channels and how they overlap and interact.
https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html

**Comment by ptvoinfo** [comment]
@aidbish, I'll try to do this after my summer vacation time.

**Comment by aidbish** [comment]
@ptvoinfo much appreciated mate

**Comment by tb-killa** [comment]
If you look at the wiki page: https://github.com/Koenkk/zigbee2mqtt/wiki/Configuration
There is the Option for ``data/configuration.yaml`` at 
```# Optional: advanced settings
advanced:
# Optional: ZigBee channel
  channel: 11
```

**Comment by ryanbeaton** [comment]
@tb-killa yes but the router firmware by @ptvoinfo is hard coded to channel 11

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ptvoinfo** [comment]
@ryanbeaton, the channel number is not hard coded. But if a router cannot connect using the channel 11, it increments panId. This behavior of ZStack (not my code). It is necessary to dig deeply to the sources to find and fix this problem.

**Comment by ryanbeaton** [comment]
@ptvoinfo oh that’s what I read on your page. That’s why I though @aidbish must have been asking. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ptvoinfo** [comment]
@ryanbeaton, I've found this after my comment :)

**Comment by aidbish** [comment]
Hi, 
was there  any update on changing the zigbee channel for the routers?

**Comment by ryanbeaton** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/252#issuecomment-424951388

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
