### ISSUE TITLE
ROB_200-025-0 reports wrong battery state

### ISSUE THREAD

**Issue by TimBeekman** [Koenkk/zigbee2mqtt#21607]
### What happened?

ROB_200-025-0 shows 200% battery. ROB_200-007-0 does show the correct value.

### What did you expect to happen?

To see a max of 100% battery

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 Dongle Plus

### Setup

Home Assistant OS on ESXi with Zigbee2MQTT and mosquitto running within HA as add-ons

**Comment by Koenkk** [comment]
fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
