### ISSUE TITLE
No converter available for ‘state_L1’(“ON”)

### ISSUE THREAD

**Issue by hanzala-123** [Koenkk/zigbee2mqtt#21604]
### What happened?

Newly supported device
https://github.com/Koenkk/zigbee2mqtt/issues/21225#issuecomment-1962427705
Only the last switch works

### What did you expect to happen?

For all 6 switches to work 

### How to reproduce it (minimal and precise)

Use the zigbee2mqtt interface to try and  switch the light on and off

### Zigbee2MQTT version

1.35.3-dev

### Adapter firmware version

20210708

### Adapter

Sonoff zigbee dongle

### Setup

Homeassistant addon

**Comment by hanzala-123** [comment]
> Have you tried either a lower case L ?

It is with a lower case L my bad, but this is following on from the previous issue where they added support for the device. One switch works but the others throw up the error message

**Comment by sjorge** [comment]
@Koenkk I'm not familier with  TuYA device aside that they are pretty non standard zigbee... but I assume this

https://github.com/Koenkk/zigbee-herdsman-converters/blob/cb4d26d9a6fbc6816ecf95e547c1567d66448c27/src/devices/tuya.ts#L1834

Should at least map to different endpoint IDs ?

**Comment by Koenkk** [comment]
@sjorge that's expected for TuYa devices, all switches are controlled through the same endpoint.

This should have been fixed in https://github.com/Koenkk/zigbee2mqtt/pull/21576 , please update to the latest dev branch.

**Comment by hanzala-123** [comment]
I've updated, get it to work occasionally but I get this message 80% of the time ![image](https://github.com/Koenkk/zigbee2mqtt/assets/66522609/fed7e862-552e-408c-af79-019d93b729ab)

**Comment by Koenkk** [comment]
`No network route` indicates a connectivity issues, routers may not be relaying messages correctly, sometimes it also helps to re-pair the device.
