### ISSUE TITLE
Errors migrating to SLZB-06P7

### ISSUE THREAD

**Issue by derekoharrow** [Koenkk/zigbee2mqtt#21617]
### What happened?

Trying to move from a ZZH stick to an SLZB-06p7, both of which are based on the cc2652.

Most devices work, but some don't when moving to the cc2652.

I either get MAC not ACK errors in the log file, or NWK_TABLE_FULL errors.

Is there something I should be doing to migrate across?

I tried re-pairing some of the devices, but that was when I started to get the NWK_TABLE_FULL errors.

Do I need to start from scratch?

(Moving back to the ZZH stick has restored everything to working order).

ta

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20221226

### Adapter

SLZB-06p7

### Setup

Docker

**Comment by derekoharrow** [comment]
Turns out there was a bug in some of the devices they shipped this month

[](https://smlight.tech/product/slzb-06p7/)

After updating the core OS via their website (through the web gui didn't work) I could then update to the new firmware they released today and now it works.

**Comment by stiamon77** [comment]
Doesn't work, firmware v2.9.8
Trying to update Zigbee OTA update
Error REQ error: http_code -1
I have three SLZB-06P7 devices, all of them have this problem, how can I update Zigbee?
