### ISSUE TITLE
Zboss cant create account.... how are you performing packet sniffing on windows?

### ISSUE THREAD

**Issue by CamHaug** [Koenkk/zigbee2mqtt#2161]
According to the how-to here:
https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
I should use zboss on windows for packet sniffing, however I cannot create an account. 
Yes I have checked spam filtering.... :\

Any one have a copy of it?

Cheers 

-Cam

**Comment by CamHaug** [comment]
sooo no one does any packet sniffing on windows?

**Comment by sjorge** [comment]
I only every did sniffing on windows once as a test using a nRF52840-Dongle following https://infocenter.nordicsemi.com/index.jsp?topic=%2Fstruct_nrftools%2Fstruct%2Fnrftools_nrfsniffer.html&cp=6_4, but it never worked well.

I had more succes on my mac using both a nRF dongle or a ti dongle.

**Comment by Kryzek** [comment]
I did also try to download zboss firmware for sniffing for sniffing in Windows. Same problem, can't get newly made account to login there. Guess I need to pull out my linux laptop then and do sniffing on linux.

**Comment by zi-l** [comment]
In may case, I cannot log in until I have activated my account through an activation email. Maybe you should wait for the account activation mail.

**Comment by rmhomecouk** [comment]
Having the same issue - unable to receive the activation email. Does anyone have the file they could kindly share?

**Comment by zladukas** [comment]
Found mine in spam folder yesterday.
