### ISSUE TITLE
[New device support]: Adding new device model to already supported Philips Hue Enrave Medium

### ISSUE THREAD

**Issue by galligan** [Koenkk/zigbee2mqtt#21645]
### Link

https://www.philips-hue.com/en-us/p/hue-white-ambiance-enrave-medium-ceiling-lamp/046677580773

### Database entry

Unsure. Wasn't able to find that. The Zigbee Model is 929003531502.

### Comments

Like in #20934 I'm seeing that the light is supported, even with all features, but is not showing the correct accompanying data.

![CleanShot 2024-03-01 at 10 00 10@2x](https://github.com/Koenkk/zigbee2mqtt/assets/25037981/2e339eff-0d32-4ec3-8c36-162f02be4e74)

This appears to be a new, third model number, in addition to 929003574301 and [915005996701](https://www.zigbee2mqtt.io/devices/915005996701.html).

### External definition

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['929003531502'],
    model: '929003531502',
    vendor: 'Signify Netherlands B.V.',
    description: 'Automatically generated definition',
    extend: [philipsLight({"colorTemp":{"range":[153,454]}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
