### ISSUE TITLE
Thermostat AVATTO _TZE200_viy9ihs7

### ISSUE THREAD

**Issue by Liionboy** [Koenkk/zigbee2mqtt#21641]
### What happened?

Manual mode is wrong, when you set on manul thermostat is on auto and when you set on manual thermostat is on auto

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20230507

### Adapter

zStack3x0

### Setup

HASS OS

**Comment by kirtapix** [comment]
Hi !I'm having same behaviour with this device.
