### ISSUE TITLE
Candeo Switch Module C205 Incorrect Picture

### ISSUE THREAD

**Issue by chrisandsally** [Koenkk/zigbee2mqtt#21642]
### Link

https://candeo.io/store/zigbee-switch-module-with-or-without-neutral/

### Model

C205 

### Description

Switch Module

### Vendor

Candeo

### Picture (link)

https://i0.wp.com/candeo.io/wp-content/uploads/2024/02/C205-zigbee-switch-module-v3.jpg?fit=1000%2C1000&ssl=1

### Database entry

{"id":16,"type":"Router","ieeeAddr":"0xec1bbdfffead2163","nwkAddr":35556,"manufId":4107,"manufName":"Candeo","powerSource":"Mains (single phase)","modelId":"C205","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe9e862c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r54","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1709327462875}

### Notes

The Picture on the for the Candeo Switch Module is incorrect on [(https://www.zigbee2mqtt.io/supported-devices/#v=Candeo)] and the integration.  Please see correct link above or see #21435 or attached
![C205](https://github.com/Koenkk/zigbee2mqtt/assets/89684974/cf85ca62-4ac9-402b-ac68-faba10492a35)

**Comment by Koenkk** [comment]
Fixed!
