### ISSUE TITLE
[New device support]: Aqara Z1 PRO ZNQBKG45LM

### ISSUE THREAD

**Issue by Pickllo** [Koenkk/zigbee2mqtt#21668]
### Link

https://www.aqara.com/en/product/smart-wall-switch-z1-pro-sea/

### Database entry

{"id":5,"type":"EndDevice","ieeeAddr":"0x54ef441000b2640e","nwkAddr":38880,"manufId":4447,"manufName":"Aqara","powerSource":"DC Source","modelId":"lumi.switch.acn059","epList":[1,2,3,4,21],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[2820,1794,18,5,4,6,3,0,64704],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"appVersion":28,"modelId":"lumi.switch.acn059"}},"aqaraOpple":{"attributes":{"4":4,"247":{"type":"Buffer","data":[154,32,0]},"252":0,"512":1,"617":1,"645":0,"646":1,"648":0,"651":1,"1303":1}},"genOnOff":{"attributes":{"245":60284928,"onOff":1}},"genMultistateInput":{"attributes":{"presentValue":1}},"manuSpecificLumi":{"attributes":{"4":4,"247":{"type":"Buffer","data":[154,32,0]},"252":0,"512":1,"561":800,"562":-45.728641510009766,"563":-50.25125503540039,"617":1,"645":0,"646":1,"648":0,"651":1,"652":5,"769":800,"1303":1}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[18,5,4,6,64704],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"245":60284928,"onOff":0}},"aqaraOpple":{"attributes":{"512":1,"617":1,"645":0}},"manuSpecificLumi":{"attributes":{"512":1,"617":1,"645":0}},"genMultistateInput":{"attributes":{"presentValue":1}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[18,5,4,6,64704],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"245":60284928,"onOff":0}},"aqaraOpple":{"attributes":{"512":1,"617":1,"645":0}},"genMultistateInput":{"attributes":{"presentValue":1}},"manuSpecificLumi":{"attributes":{"512":1,"617":1,"645":0}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[18,64704],"outClusterList":[],"clusters":{"aqaraOpple":{"attributes":{"617":0}},"genMultistateInput":{"attributes":{"presentValue":1}},"manuSpecificLumi":{"attributes":{"617":0}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"profId":260,"epId":21,"devId":0,"inClusterList":[12],"outClusterList":[],"clusters":{"genAnalogInput":{"attributes":{"presentValue":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":28,"stackVersion":27,"hwVersion":1,"dateCode":"20230822","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1709538540585}

### Comments

This is similar to the Z1, but with the addition of the touch slider on the left. Anyone able to help get it into HA?

### External definition

```shell
const {deviceEndpoints, electricityMeter, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['lumi.switch.acn059'],
    model: 'lumi.switch.acn059',
    vendor: 'Aqara',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4,"21":21}}), electricityMeter(), onOff({"powerOnBehavior":false,"endpoints":{"1":1,"2":2,"3":3}})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by mrmaximas** [comment]
please provide database entry for ieeeAddr: 0x54ef441000b2640e from zigbee2mqtt_DIR/data/database.db file located depend of your os.

**Comment by Pickllo** [comment]
> please provide database entry for ieeeAddr: 0x54ef441000b2640e from zigbee2mqtt_DIR/data/database.db file located depend of your os.

Apologies, updated with the correct entry

**Comment by mrskycriper** [comment]
@Pickllo @MadMirza we are trying to figure out the slider in this [issue](https://github.com/Koenkk/zigbee2mqtt/issues/21687). Your help will be very much welcome.
