### ISSUE TITLE
[New device support]: Aqara Z1 Pro 2 Gang [ZNQBKG43LM]

### ISSUE THREAD

**Issue by LZXCorp** [Koenkk/zigbee2mqtt#21687]
### Link

https://aqara.com/en/product/smart-wall-switch-z1-pro-sea/

### Database entry

```json
{
	"id": 38,
	"type": "EndDevice",
	"ieeeAddr": "0x54ef441000b05060",
	"nwkAddr": 45653,
	"manufId": 4447,
	"manufName": "Aqara",
	"powerSource": "DC Source",
	"modelId": "lumi.switch.acn057",
	"epList": [1, 2, 3, 4, 21],
	"endpoints": {
		"1": {
			"profId": 260,
			"epId": 1,
			"devId": 0,
			"inClusterList": [2820, 1794, 18, 5, 4, 6, 3, 0, 64704],
			"outClusterList": [10, 25],
			"clusters": {
				"manuSpecificLumi": {
					"attributes": {
						"4": 4,
						"247": {
							"type": "Buffer",
							"data": [
								3, 40, 31, 5, 33, 11, 0, 9, 33, 0, 0, 10, 33, 89, 225, 12, 32,
								10, 13, 35, 28, 0, 0, 0, 17, 35, 1, 0, 0, 0, 100, 16, 1, 101,
								16, 0, 149, 57, 0, 0, 0, 0, 154, 32, 0
							]
						},
						"512": 1,
						"561": 1302,
						"562": 2.5125627517700195,
						"563": 2.5125627517700195,
						"617": 1,
						"645": 0,
						"646": 1,
						"648": 1,
						"651": 1,
						"652": 4,
						"769": 688,
						"1303": 1
					}
				},
				"genBasic": {
					"attributes": {
						"modelId": "lumi.switch.acn057",
						"manufacturerName": "Aqara",
						"appVersion": 28,
						"powerSource": 4,
						"zclVersion": 3,
						"stackVersion": 27,
						"hwVersion": 1,
						"dateCode": "20230822"
					}
				},
				"genOnOff": { "attributes": { "245": 45241600, "onOff": 1 } },
				"genMultistateInput": { "attributes": { "presentValue": 1 } },
				"haElectricalMeasurement": {
					"attributes": { "acPowerDivisor": 10, "acPowerMultiplier": 1 }
				}
			},
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		},
		"2": {
			"profId": 260,
			"epId": 2,
			"devId": 0,
			"inClusterList": [18, 5, 4, 6, 64704],
			"outClusterList": [],
			"clusters": {
				"genOnOff": { "attributes": { "245": 62018816, "onOff": 0 } },
				"genMultistateInput": { "attributes": { "presentValue": 1 } },
				"manuSpecificLumi": { "attributes": { "512": 1, "617": 1, "645": 0 } }
			},
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		},
		"3": {
			"profId": 260,
			"epId": 3,
			"devId": 0,
			"inClusterList": [64704],
			"outClusterList": [],
			"clusters": {
				"manuSpecificLumi": { "attributes": { "512": 1, "617": 1, "645": 0 } }
			},
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		},
		"4": {
			"profId": 260,
			"epId": 4,
			"devId": 0,
			"inClusterList": [64704],
			"outClusterList": [],
			"clusters": { "manuSpecificLumi": { "attributes": { "617": 0 } } },
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		},
		"21": {
			"profId": 260,
			"epId": 21,
			"devId": 0,
			"inClusterList": [12],
			"outClusterList": [],
			"clusters": { "genAnalogInput": { "attributes": { "presentValue": 0 } } },
			"binds": [],
			"configuredReportings": [],
			"meta": {}
		}
	},
	"appVersion": 28,
	"stackVersion": 27,
	"hwVersion": 1,
	"dateCode": "20230822",
	"zclVersion": 3,
	"interviewCompleted": true,
	"meta": {},
	"lastSeen": 1709654120462
}
```

### Comments

This is a 2 Gang Switch similar to the original Z1, except it has a slider on the left of it.

The switch supports Mode Switching for both switches.
It also has individual gang operation mode and lock relay control.

I would like to have the slider added.

### External definition

```js
const {deviceEndpoints, electricityMeter, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['lumi.switch.acn057'],
    model: 'lumi.switch.acn057',
    vendor: 'Aqara',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4,"21":21}}), electricityMeter(), deviceEndpoints({"endpoints":{"1":1,"2":2}}), onOff({"powerOnBehavior":false,"endpointNames":["1","2"]})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by mrskycriper** [comment]
> I would like to have the slider added.

Adding it is not a problem, figuring out the slider is. My guess is that slider reports on endpoint `21` using `genAnalogInput` cluster. But the values are unknown. Could you capture some debug logs with slider activity? It could be done by enabling zigbee-herdsman debug log

**Comment by mrskycriper** [comment]
Can you please capture some more values? Right now it looks like the slider is on the same endpoint (`1`) as the first button. The values seem nonsensical. But if we can at least determine their edges then I can add numeric sensor with one of those values

**Comment by mrskycriper** [comment]
Also, have you enabled zigbee-herdsman debug loging in configuration or simply switched logs to debug in web interface?

**Comment by mrskycriper** [comment]
Are you use Home Assistant? If so then use [this](https://www.zigbee2mqtt.io/guide/usage/debug.html#home-assistant-os-supervised-addon) instruction to enable them

**Comment by mrskycriper** [comment]
> Can you send me an example of the logs you need me to find? Cause I am kind of lost on what I am supposed to be looking for.

That is the fun part, I have no idea. What I'm really expecting is to see those messages above but with additional info in logs around. They should contain raw zigbee-herdsman data with commands and payloads. Debug logs above are showing the same thing but already processed and stripped of it's context. I need to see the emitter endpoint, types of commands and payloads.

**Comment by mrskycriper** [comment]
> Can you send me an example of the logs you need me to find? Cause I am kind of lost on what I am supposed to be looking for.
> 
> UPD: ![image](https://private-user-images.githubusercontent.com/107389832/310280244-419f03c3-dbe6-42ab-9738-6aafe6fe2fd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzMzNTQsIm5iZiI6MTcwOTY3MzA1NCwicGF0aCI6Ii8xMDczODk4MzIvMzEwMjgwMjQ0LTQxOWYwM2MzLWRiZTYtNDJhYi05NzM4LTZhYWZlNmZlMmZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMTEwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDJhMmNmMmI2YTVlMjExNWYxM2FjMjUwYTJlN2RiZTQ4MTY2ZDgzMGU3OGJhZWQwMTA1ZTJlMzllOTc4MzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pwYBLEkA8rgO0kLUYFORcES4CadulA4L2mHU24LaBXs) Based on these logs above, it seems that the slider stuff are from endpoint 1.

Good, endpoint `1` is confirmed now. Now I need to now the limits of those values.

**Comment by mrskycriper** [comment]
I'm think you can focus on keys `561` and `769`. They look more logical than `562` and `563`. Key `652` seems to be static with value `5`.

As for testing tips, try taping on the same points several times and see how close the values are. Also make sure to slide up and down as close to the edge as possible.

**Comment by mrskycriper** [comment]
H1 knob seems to use similar architecture:
```js
action_rotation_percent: msg.data[563],
action_rotation_percent_speed: msg.data[562],
action_rotation_time: msg.data[561],
```

`652` is probably also for direction
4 - bottom to top
5 - top to bottom

**Comment by mrskycriper** [comment]
Here is rotation converter from H1 knob

```js
lumi_knob_rotation: {
        cluster: 'manuSpecificLumi',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty(570)) {
                const act: KeyValueNumberString = {1: 'start_rotating', 2: 'rotation', 3: 'stop_rotating'};
                const state: KeyValueNumberString = {0: 'released', 128: 'pressed'};
                return {
                    action: act[msg.data[570] & ~128],
                    action_rotation_button_state: state[msg.data[570] & 128],
                    action_rotation_angle: msg.data[558],
                    action_rotation_angle_speed: msg.data[560],
                    action_rotation_percent: msg.data[563],
                    action_rotation_percent_speed: msg.data[562],
                    action_rotation_time: msg.data[561],
                };
            }
        },
    } satisfies Fz.Converter,
```

**Comment by mrskycriper** [comment]
May be `769` is some sort of absolute value? What happens with it if you slide all the way from top to bottom or in reverse? As close to the edge of a button as possible.

**Comment by mrskycriper** [comment]
Btw, I added converter prototype to the [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7160)

**Comment by mrskycriper** [comment]
> > May be `769` is some sort of absolute value? What happens with it if you slide all the way from top to bottom or in reverse? As close to the edge of a button as possible.
> 
> ![image](https://private-user-images.githubusercontent.com/107389832/310294075-529ef210-bacd-430e-a1ea-d1f4b3c7b585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzY4MzEsIm5iZiI6MTcwOTY3NjUzMSwicGF0aCI6Ii8xMDczODk4MzIvMzEwMjk0MDc1LTUyOWVmMjEwLWJhY2QtNDMwZS1hMWVhLWQxZjRiM2M3YjU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQyMjA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2RjNjJkMTE0MWEyYmY5MmZkNTg5YjM2YzY1YTQ2ZTlmMmJkMTY3NWZiNThiNWY2YWY3ODc5NTFjZjA3MjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6z3PCOrIChyUrHPEHV-T3QZUXPaNhlcJfQGaIo9H030)
> 
> `769` might be linked to `561`.

That is very strange

**Comment by mrskycriper** [comment]
Added as is for now. Aqara probably uses some complex algorithm on the hub to calculate the commands. Right now all the values are in the converter but to me they seem useless.

**Comment by cocolun** [comment]
I m new but recently bought z1 pro and added it into Zigbee2mqtt and can't firgure out how to get all the function working such as the slider and the 4th button.

Would you mind explaining or point me to where I could learn it.

Thanks

**Comment by MadMirza** [comment]
@LZXCorp Hi, Just pinging, since you contributed heavily to add support to this device in Z2M, as of current update (Z2M 1.39.1), the switch has issues for 'operating mode', the decouple mode for middle and bottom switch does not work unfortunately. #23767, Issue has been raised here, any help would be great!

**Comment by doddys** [comment]
Hi @LZXCorp, just curious, why this device is defined as EndDevice instead or router? This device has neutral line.

**Comment by LZXCorp** [comment]
> Hi [@LZXCorp](https://github.com/LZXCorp), just curious, why this device is defined as EndDevice instead or router? This device has neutral line.

All of the Z1 Pro models have support for a non-neutral line configuration, meaning to say the neutral wire is **optional** (since most homes in SEA don't have neutral line). Which could be the reason they placed defined it as EndDevice instead of router.

**Comment by gabrielleewl-max** [comment]
Hi wondering if can add support for the Aqara Z1 Pro 4 Gang (Chinese Ver)? So far only by adding external converter created by @waterlou will work,  but the slider action is not present.
