### ISSUE TITLE
Luminance door sensor TZE200_pay2byax

### ISSUE THREAD

**Issue by malac1** [Koenkk/zigbee2mqtt#21688]
### What happened?

I have 8 pieces Luminance door sensor Zigbee Model: TS0601, Zigbee Manufacturer: _TZE200_pay2byax, Manufacturer: TuYa
The sensors were integrated into my HomeAssistant system with Zigbee2MQTT without problems, the interview was done without any error messages. But I see one drawback. The contact works without problems, the status and entities "binary_sensor.door_contact" can be seen. These entities can be used to create automations.
The problem is with the luminance sensor. I can see the luminance value in Z2M - Exposes, but there are no entities associated with the luminance value.
![About](https://github.com/Koenkk/zigbee2mqtt/assets/143909108/4efdfedd-8b8b-4fc0-af8d-58e081680114)
![Exposes](https://github.com/Koenkk/zigbee2mqtt/assets/143909108/3236fb85-ca4e-4851-b1b5-6d077592b364)
![Device info](https://github.com/Koenkk/zigbee2mqtt/assets/143909108/481d3c25-9e60-45e2-b142-4b1be40a348a)
![Entities2](https://github.com/Koenkk/zigbee2mqtt/assets/143909108/263e8149-47b9-457f-a0b7-eb69d55d23dc)

### What did you expect to happen?

I would like to use the luminance value to create automations. For example "Turn on the light when the luminance value is less than 500lx". As it is, with this integration into HA the Luminance sensor cannot be used for anything.

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

Firmware: 1.36.0

### Adapter

ZigBee 3.0 Stick CC2652P Sonoff

### Setup

Add-on on Home Assistant OS on Intel x64

**Comment by Koenkk** [comment]
<img width="238" alt="Screenshot 2024-03-05 at 21 24 14" src="https://github.com/Koenkk/zigbee2mqtt/assets/2892853/b20df54b-46db-40e2-bf14-357c6325c8fd">

They are there but disabled by default, click on them to enable

**Comment by malac1** [comment]
Thanks Koenkk for the quick response and help! I'm new to HA and sometimes a detail gets stuck. I hope you understand. Kind regards and thanks again.
