### ISSUE TITLE
No converter available for 'hs_color'

### ISSUE THREAD

**Issue by u20p17** [Koenkk/zigbee2mqtt#21686]
### What happened?

I get the "No converter available for 'hs_color'" error when sending the following data via mqtt: {"state": "ON", "brightness": 190 , "hs_color": [30.58,70.55]}

### What did you expect to happen?

The Hue Spot should change the color accordingly without any error.

### How to reproduce it (minimal and precise)

Zigbee-Modell: 5060731P7_02
Zigbee-Hersteller: Philips
Beschreibung: Hue White & Color ambience Centris ceiling light (4 spots)

Send the following data via mqtt: {"state": "ON", "brightness": 190 , "hs_color": [30.58,70.55]}

### Zigbee2MQTT version

 1.36.0 commit: 86ed71c

### Adapter firmware version

20230507

### Adapter

Sonoff C2652P

### Setup

Intel Nuc with Unraid, zigbee2mqtt in docker 

### Debug log

Zigbee2MQTT:info  2024-03-05 16:52:52: MQTT publish: topic 'zigbee2mqtt/Büro Spot 4', payload '{"brightness":190,"color":{"x":0.535,"y":0.395},"color_mode":"xy","last_seen":"2024-03-05T15:52:52.133Z","linkquality":185,"power_on_behavior":"off","state":"OFF","update":{"installed_version":16785162,"latest_version":16785162,"state":"idle"},"update_available":null}'
Zigbee2MQTT:error 2024-03-05 16:52:52: No converter available for 'hs_color' ([30.58,70.55])

**Comment by sjorge** [comment]
hs_color is not a valid attribute. You want `{"state": "ON", "brightness": 190 , "color": {"hue": 30, "saturation": 70}}`

**Comment by u20p17** [comment]
thank you!
