### ISSUE TITLE
New version 1.36 : message Successfully configured ?

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#21681]
### What happened?

Hello, I updated z2m to 1.36, is it normal that for my devices it indicates "Successfully configured" each time ?

Thanks

![image](https://github.com/Koenkk/zigbee2mqtt/assets/55591810/121b974c-61e2-41e3-9721-fc8131d8e403)

### Zigbee2MQTT version

1.36

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E

### Setup

PI 4B

### Debug log

024-03-05 10:36:43MQTT publish: topic 'zigbee2mqtt/Presence_Salon', payload '{"battery":100,"device_temperature":21,"illuminance":60,"illuminance_lux":60,"last_seen":"2024-03-05T10:36:43+01:00","linkquality":88,"occupancy":true,"power_outage_count":112,"voltage":3025}'
Info 2024-03-05 10:36:43Successfully configured 'Presence_Salon'
Info 2024-03-05 10:36:44MQTT publish: topic 'zigbee2mqtt/Presence_Salon', payload '{"battery":100,"device_temperature":21,"elapsed":213,"illuminance":60,"illuminance_lux":60,"last_seen":"2024-03-05T10:36:44+01:00","linkquality":88,"occupancy":true,"power_outage_count":112,"voltage":3025}'
Info 2024-03-05 10:36:45Configuring 'Fenetre_Bureau'
Info 2024-03-05 10:36:45MQTT publish: topic 'zigbee2mqtt/Fenetre_Bureau', payload '{"battery":90,"contact":false,"device_temperature":18,"last_seen":"2024-03-05T10:36:45+01:00","linkquality":92,"power_outage_count":119,"voltage":2985}'
Info 2024-03-05 10:36:46Successfully configured 'Fenetre_Bureau'
Info 2024-03-05 10:36:48MQTT publish: topic 'zigbee2mqtt/Fenetre_Bureau', payload '{"battery":90,"contact":true,"device_temperature":18,"elapsed":2710,"last_seen":"2024-03-05T10:36:48+01:00","linkquality":92,"power_outage_count":119,"voltage":2985}'
Info 2024-03-05 10:37:00MQTT publish: topic 'zigbee2mqtt/Xiaomi_Prise', payload '{"consumption":803.1412963867188,"device_temperature":33,"energy":803.14,"last_seen":"2024-03-05T10:37:00+01:00","linkquality":96,"power":0,"power_outage_count":223,"state":"OFF","update":{"installed_version":92,"latest_version":92,"state":"idle"},"update_available":false}'
Info 2024-03-05 10:37:18MQTT publish: topic 'zigbee2mqtt/Sirene2', payload '{"alarm":false,"battery":100,"last_seen":"2024-03-05T10:37:18+01:00","linkquality":168,"voltage":5000,"volume":80}'

**Comment by zcaalock** [comment]
i have same issue with poping messages after each action, after few minutes zigbee2mqtt stopped working, even after full restart. I had to reload to version from few months ago that still works, non of the between updates works with my [TS0505B_1]. The version that still works is 1.35.1-1
