### ISSUE TITLE
Z2M Home Assistant Addon settings are ignored

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#21685]
### What happened?

I have rebuilt my Z2M network from scratch (taking five hours), setting channel 25 in the Z2M Home Assistant addon Settings. After setting everything up, I noticed this settings is completely ignored, and I'm still apparently using channel 11.

If these settings are ignored, remove it from the addon.

### What did you expect to happen?

For Z2M network to use Channel 25 as instructed.

### How to reproduce it (minimal and precise)

Install Z2M addon in HA, go to Addons/Zigbee2MQTT/Settings, Edit in YAML, edit Channel

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

20230507

### Adapter

Slae'sh 2652RB

### Setup

Add-on for Home Assistant (HA installedProxmox VM

### Additional info

here's the entire Addon config, which is apparently ignored:

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: a
serial:
  port: /dev/ttyUSB0
external_converters: []
devices: devices.yaml
zigbee_herdsman_debug: false
groups: groups.yaml
homeassistant: true
permit_join: true
advanced:
  log_level: info
  pan_id: 6754
  channel: 25
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
ota:
  disable_automatic_update_check: true

**Comment by lux73** [comment]
AFAIK the HA Addon will not provided by @Koenkk - you should get in touch with HA Developers

it shares some Code Base with z2m, that's all...

**Comment by Stooovie** [comment]
Will do, thanks, it's egregious

**Comment by brdcg** [comment]
I have a similar Problem.
Installed Z2M as Home Assistant Addon. Now I wanted to change the MQTT Server from mosquitto to EMQX.
When I change the mqtt server settings in configuraton.yaml, Z2M still tries to connect to mosquitto.
I have the suspicion that the configuration.yaml under config/zigbee2mqtt is being ignored.
