### ISSUE TITLE
[New device support]: Schneider Electric A9MEM1520

### ISSUE THREAD

**Issue by gatismu** [Koenkk/zigbee2mqtt#21695]
### Link

https://www.se.com/eg/en/product/A9MEM1520/energy-sensor-powertag-monoconnect-63a-1p+wire-top-and-bottom-position/

### Database entry

0x00000000e2008234

### Comments

Hello!
Maybe somebody can conver 3 pahse version support to 1phase? 
https://www.zigbee2mqtt.io/devices/A9MEM1570.html

Thansk!

Zigbee2MQTT:info  06-03-2024 13:20:33: Successfully interviewed '0x00000000e2008234', device has successfully been paired
Zigbee2MQTT:warn  06-03-2024 13:20:33: Device '0x00000000e2008234' with Zigbee model 'GreenPower_178' and manufacturer name 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

### External definition

```shell
const definition = {
    zigbeeModel: ['GreenPower_178'],
    model: 'GreenPower_178',
    vendor: '',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by jagjordi** [comment]
Any hopes on this?
