### ISSUE TITLE
wrong battery percentage indication

### ISSUE THREAD

**Issue by nklin** [Koenkk/zigbee2mqtt#217]
The battery percentage indication does not match the real voltage.
I have put in a new battery in the temperature sensor and the percentage indicator shows 43% but the measured voltage of the sensor is 3,015 V.

**Comment by Koenkk** [comment]
Can you check if this issue still exists in the dev branch: https://github.com/Koenkk/zigbee2mqtt/tree/dev

**Comment by tb-killa** [comment]
What type of device?

**Comment by Koenkk** [comment]
You can use the dev images: https://hub.docker.com/r/koenkk/zigbee2mqtt/tags/

**Comment by nklin** [comment]
the latest-dev image solved the problem. 
Many thanks.
