### ISSUE TITLE
Legrand 067773 and Legrand 067774 - no battery percentage report

### ISSUE THREAD

**Issue by cobch** [Koenkk/zigbee2mqtt#21702]
### What happened?

[Legrand 067773 ](https://www.zigbee2mqtt.io/devices/067773.html) and [Legrand 067774 ](https://www.zigbee2mqtt.io/devices/067774.html) devices do not send battery values , but battery is exposed). As can I see in device clusters it should support battery information:

![Screenshot 2024-03-06 at 22 46 40](https://github.com/Koenkk/zigbee2mqtt/assets/50397676/8eb15c25-8f1b-4168-877c-a68f04e6f780)
![Screenshot 2024-03-06 at 22 47 21](https://github.com/Koenkk/zigbee2mqtt/assets/50397676/2c644833-9ac1-4fa2-b57c-54efb0020cd5)

I'm using these devices for 6 months, so I waited a lot :)

### What did you expect to happen?

Battery level should be reported

### How to reproduce it (minimal and precise)

Just pair it and observe no battery values

### Zigbee2MQTT version

 1.36.0

### Adapter firmware version

7.1.1.0 build 273

### Adapter

Skyconnect EZSP v9

### Setup

Z2M hassio on a raspberry Pi 4

**Comment by Loic691** [comment]
It's working for me for 067773.
Z2m 1.26.1 on sonoff dongle E

**Comment by cobch** [comment]
Ok interesting. But I have only a question mark instead of the battery level. could you help me to fix that maybe?
![Screenshot 2024-04-04 at 09 58 26](https://github.com/Koenkk/zigbee2mqtt/assets/50397676/e67985fc-dff2-424f-8a9e-bb03d9736ea3)

**Comment by Loic691** [comment]
Strange, I think i have the same for double gangs... i try to look about that tomorrow

**Comment by Loic691** [comment]
Hey
I have a "?" for Home Away 067646

**Comment by cobch** [comment]
Do you know how it is possible you get battery status for you but not for me? I have latest z2m and using skyconnect.

**Comment by Loic691** [comment]
I don't know. It's obscur for me... Some users get it, others one no...
Legrand is a problem for users because it's frenco french and minority users use it...
Legrand is not very regardless on zigbee protocol...

**Comment by Loic691** [comment]
Hi
I updated my last post. Two device don't get battery state....

**Comment by Loic691** [comment]
Hey
Very very strange... Same device, same firmware ( 46 )
One device with battery status, other device no....

![image](https://github.com/Koenkk/zigbee2mqtt/assets/60837526/ed09466b-b704-46f7-a126-774cbe7c7bf5)
