### ISSUE TITLE
[Feature request]: OTA support for Aqara Switch WS-EUK04

### ISSUE THREAD

**Issue by AndreiArdelean1** [Koenkk/zigbee2mqtt#21706]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

OTA support for Aqara Switch WS-EUK04

### Describe alternatives you've considered

-

### Additional context

-

**Comment by julianfs** [comment]
Is there a firmware update available for this device?

**Comment by AndreiArdelean1** [comment]
I've checked using https://developer.aqara.com/console, and there is only one update with `releaseTime` 1638760510000 (December 6, 2021) that is problematic (https://github.com/Koenkk/zigbee2mqtt/discussions/16573)
