### ISSUE TITLE
TuYa WHD02 paired as TS0001

### ISSUE THREAD

**Issue by HD78** [Koenkk/zigbee2mqtt#21711]
### What happened?

Received few of these Aubess 16A 1-gang switches and they pair as TS0001 switch which has no setting for the toggle switch type.
https://www.aliexpress.com/item/1005006258685537.html

It has device vendor "_TZ3000_fdxihpp7"

Database:
{"id":40,"type":"Router","ieeeAddr":"0x70b3d52b6007fe45","nwkAddr":62383,"manufId":4660,"manufName":"_TZ3000_fdxihpp7","powerSource":"Mains (single phase)","modelId":"TS0001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,6,3,4,5,57345,2820,1794],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"manufacturerName":"_TZ3000_fdxihpp7","zclVersion":2,"appVersion":100,"modelId":"TS0001","powerSource":1}},"genOnOff":{"attributes":{"onOff":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a2ea64a","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":2,"dateCode":"20210625","swBuildId":"500+TZTDQ11Z3101","zclVersion":2,"interviewCompleted":true,"meta":{"configured":153093895},"lastSeen":1710257719510}

### What did you expect to happen?

Paired as WHD02

### Zigbee2MQTT version

1.36.0-dev commit: d37c164

### Adapter firmware version

20230507

### Adapter

SONOFF ZB Dongle -P 

### Setup

add-on on x86-64

**Comment by HD78** [comment]
For others having the same mode, I got it working with this external converter:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [{ modelID: 'TS0001', manufacturerName: '_TZ3000_fdxihpp7' }],
    model: 'WHD02',
    vendor: 'TuYa',
    whiteLabel: [{ vendor: 'TuYa', model: 'iHSW02' }, { vendor: 'Aubess', model: 'TMZ02' }],
    description: 'Wall switch module',
    extend: tuya.extend.switch({ switchType: true }),
    configure: async (device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(endpoint);
    },
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Integrated, thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
