### ISSUE TITLE
[Wrong device]: Tuya TS0207 is recognized as Aubess

### ISSUE THREAD

**Issue by marianob85** [Koenkk/zigbee2mqtt#21719]
### Link

https://zigbee.blakadder.com/Tuya_WL-898WZ.html

### Model

TS0207

### Description

Water Leak Sensor

### Vendor

Tuya

### Picture (link)

https://zigbee.blakadder.com/Tuya_WL-898WZ.html

### Database entry

{"id":11,"type":"EndDevice","ieeeAddr":"0xa4c13881ffbecaa9","nwkAddr":46792,"manufId":4417,"manufName":"_TZ3000_upgcbody","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002f8b3f17","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":74}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002f8b3f17","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":491743244},"lastSeen":1709274536223}

### Notes

I bought some time ago a Tyua water leak detector. It was correct recognized by zigbee2mqtt: https://www.zigbee2mqtt.io/devices/TS0207_water_leak_detector_1.html
With the recent version of zigbee2mqtt it shows as Aubess	IH-K665 https://www.zigbee2mqtt.io/devices/IH-K665.html#aubess-ih-k665 which is completely wrong. 

Database entry when device was recognized correctly: 
`{"id":11,"type":"EndDevice","ieeeAddr":"0xa4c13881ffbecaa9","nwkAddr":46792,"manufId":4417,"manufName":"_TZ3000_upgcbody","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002f8b3f17","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":74}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002f8b3f17","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":491743244},"lastSeen":1709274536223}`

Current data base entry when it recognized wrong: 
`{"id":11,"type":"EndDevice","ieeeAddr":"0xa4c13881ffbecaa9","nwkAddr":46792,"manufId":4417,"manufName":"_TZ3000_upgcbody","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b002f8b3f17","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":74}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002f8b3f17","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":491743244},"lastSeen":1709883701556}`

**Comment by hoodbyair** [comment]
I have the same issue
