### ISSUE TITLE
[New device support]: tuya  TS0601_TZE204_xpq2rzhq not supported sensor presence 

### ISSUE THREAD

**Issue by DNASystem** [Koenkk/zigbee2mqtt#21744]
### Link

https://www.amazon.it/dp/B0B3F8892T?psc=1&ref=ppx_yo2ov_dt_b_product_details

### Database entry

_TZE204_xpq2rzhq

### Comments

Hi, I don't know if this is the right section but I saw that the following sensor "_TZE204_xpq2rzhq" is not shown in the list of presence sensors, how can I add it? it tells me that it is not supported in the device list "tuya" is not shown

     {
         fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ikvncluo'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_lyetpprm'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_jva8ink8'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_holel4dk'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_xpq2rzhq'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_wukb7rhc'},
             {modelID: 'TS0601', manufacturerName: '_TZE204_xsm7l9xa'},
             {modelID: 'TS0601', manufacturerName: '_TZE204_ztc6ggyl'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_ztc6ggyl'},
             {modelID: 'TS0601', manufacturerName: '_TZE200_sgpeacqp'}],

![not supported](https://github.com/Koenkk/zigbee2mqtt/assets/77543840/995dc116-7158-49e1-8bef-3b5741b16be8)

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_xpq2rzhq',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Does it work when stopping z2m, changing the manufacturerName to `_TZE200_jva8ink8` in the `data/database.db` and starting z2m ?

**Comment by DNASystem** [comment]
sorry I didn't understand how to make it work

**Comment by DNASystem** [comment]
I'm running z2m with home assistant addon where I find the folder where the database file is located, I have the z2m folder in home assistant there database but I don't think that's the file

**Comment by Koenkk** [comment]
You may be able to find it with the [file browser addon](https://community.home-assistant.io/t/home-assistant-addon-filebrowser/282108)

**Comment by DNASystem** [comment]
hi, I also checked with file browser, I can't find the main zigbee2mqtt files where I can add this sensor, is there a possibility of adding it in an update?

**Comment by Koenkk** [comment]
It should be in the `/share/zigbee2mqtt` folder

**Comment by DNASystem** [comment]
hi, I saw in the folder you indicated but it is empty, I can't find the container and supervisor folder in HA_OS, is there a guide on how to reach the file installed in the device folder?

**Comment by Koenkk** [comment]
I've added it now, can you check if it works?

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by DNASystem** [comment]
hi, sorry again, I saw that it was inserted in the converter but I'm not very familiar with how do I update zigbee2mqtt, I tried to replace the files but it's not recognized anyway, is there an installation method? for the HA_OS addon I don't see a new version of the addon yet, can you explain to me how I update so I can see if it works? thanks and sorry again

**Comment by Koenkk** [comment]
I think its best to wait for the next update on 1 April
