### ISSUE TITLE
Zigbee2mqtt Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open

### ISSUE THREAD

**Issue by Balabonov73** [Koenkk/zigbee2mqtt#21747]
### What happened?

Raspberry PI OS on rasbperry pi 5
Dongle Conbee III : usb-dresden_elektronik_ConBee_III_DE03188475-if00-port0

Hello,

The USB stick is recognised

`ls -l /dev/serial/by-id/`
`total 0
lrwxrwxrwx 1 root root 13 Mar 10 15:12 usb-dresden_elektronik_ConBee_III_DE03188475-if00-port0 -> ../../ttyUSB0
`
I can't launch Zigbee2MQTT 

### How to reproduce it (minimal and precise)

`npm start
`

### Zigbee2MQTT version

1.36

### Adapter firmware version

latest

### Adapter

Conbee III

### Setup

Raspberry PI OS 

### Debug log

> `> zigbee2mqtt@1.36.0 start
> node index.js

Zigbee2MQTT:info  2024-03-10 15:16:08: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-10.15-16-08' filename: log.txt
Zigbee2MQTT:info  2024-03-10 15:16:09: Starting Zigbee2MQTT version 1.36.0 (commit #2a53b8e5)
Zigbee2MQTT:info  2024-03-10 15:16:09: Starting zigbee-herdsman (0.35.1)
Zigbee2MQTT:error 2024-03-10 15:16:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-03-10 15:16:09: Failed to start zigbee
Zigbee2MQTT:error 2024-03-10 15:16:09: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-03-10 15:16:09: Exiting...
Zigbee2MQTT:error 2024-03-10 15:16:09: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open usb-dresden_elektronik_ConBee_III_DE03188475-if00-port0'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/serialPort.ts:28:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:82:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:118:18
`

**Comment by chris-1243** [comment]
```
Error: No such file or directory, cannot open usb-dresden_elektronik_ConBee_III_DE03188475-if00-port0'
```

In your `configuration.yaml`, you should update the path of your adapter like this:

```
serial:
  adapter: /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03188475-if00-port0
```
