### ISSUE TITLE
Incorrect display of the negative temperature values ​​in the TS0601_temperature_humidity_sensor_1 sensor

### ISSUE THREAD

**Issue by lirtm** [Koenkk/zigbee2mqtt#21752]
### What happened?

I found this issue - https://github.com/Koenkk/zigbee2mqtt/issues/20774 . It talks about a different sensor — https://aliexpress.ru/item/1005005954597374.html , but with the same problem as mine. The sensor display shows -2.6°C and the Z2M shows 6551°C.
![1](https://github.com/Koenkk/zigbee2mqtt/assets/4773960/3206cfa5-de2e-4950-ad75-81ba4d978097)

### What did you expect to happen?

The values should match.

### How to reproduce it (minimal and precise)

Place the sensor in an environment where a temperature value below 0°C is expected.

### Zigbee2MQTT version

1.36.0-1 and EDGE

### Adapter firmware version

20230507

### Adapter

SONOFF ZB Dongle-P Zigbee 3,0 USB Dongle Plus

### Setup

Add-on in Home Assistant in Proxmox on NUC Beelink Mini S

**Comment by Koenkk** [comment]
can you provide the data/database.db entry of your device?

**Comment by Koenkk** [comment]
Should be fixed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by Koenkk** [comment]
Could you provide the debug log when running with z2m 1.36.1 and the incorrect value is published?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by Koenkk** [comment]
You are not running z2m 1.36.1: `Starting Zigbee2MQTT version 1.36.0-dev (commit #14e0440)`
