### ISSUE TITLE
Duplicate Device-ID on Homeassistant

### ISSUE THREAD

**Issue by embcla** [Koenkk/zigbee2mqtt#21764]
### What happened?

Sometimes, one of the Aqara temp sensors needs to be re-added.
So I re-added one, making sure I deleted the previous instance and cleaned the homeassistant-ID, but now it's seeing its home-assistant device ID string having a duplicate string

Namely device: "HygroTemp-Server" is now being called _sensor.hygrotemp_server_hygrotemp_server_temperature_

### What did you expect to happen?

That the device-id would be used only once in the homeassistant-ID (as has always been the case, as this setup has been running for 4y)

### How to reproduce it (minimal and precise)

I added a device and it's just doing this, nothing else on my part
The issue persists even when I modify the Device-ID from within zigbee2mqtt making sure I enable re-writing the homeassistant-ID

### Zigbee2MQTT version

1.18.1-1

### Adapter firmware version

20211217

### Adapter

zStack3x0

### Setup

HAOS on QNAP VM

### Debug log

Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'zigbee_apartment/HygroTemp-Server', payload ''
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/battery/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/temperature/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/humidity/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/pressure/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/voltage/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/linkquality/config', payload 'null'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/battery/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"battery","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada battery","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_battery_zigbee_apartment","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/temperature/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"temperature","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada temperature","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_temperature_zigbee_apartment","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/humidity/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"humidity","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada humidity","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_humidity_zigbee_apartment","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/pressure/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"pressure","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada pressure","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_pressure_zigbee_apartment","unit_of_measurement":"hPa","value_template":"{{ value_json.pressure }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/voltage/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"voltage","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada voltage","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_voltage_zigbee_apartment","unit_of_measurement":"V","value_template":"{{ value_json.voltage }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'homeassistant/sensor/0x00158d0005446d21/linkquality/config', payload '{"availability":[{"topic":"zigbee_apartment/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0005446d21"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"HygroTemp-Yadablada","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:signal","json_attributes_topic":"zigbee_apartment/HygroTemp-Yadablada","name":"HygroTemp-Yadablada linkquality","state_topic":"zigbee_apartment/HygroTemp-Yadablada","unique_id":"0x00158d0005446d21_linkquality_zigbee_apartment","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'zigbee_apartment/HygroTemp-Yadablada', payload '{"battery":100,"humidity":29.12,"pressure":996,"temperature":30.76,"voltage":3055}'
Zigbee2MQTT:info  2024-03-11 17:41:58: MQTT publish: topic 'zigbee_apartment/bridge/response/device/rename', payload '{"data":{"from":"HygroTemp-Server","homeassistant_rename":true,"to":"HygroTemp-Yadablada"},"status":"ok","transaction":"fjlbs-1"}'

"data": {
    "connected": true,
    "mqtt_config": {
      "broker": "192.168.101.4",
      "port": 1883,
      "username": "**REDACTED**",
      "password": "**REDACTED**",
      "birth_message": {
        "topic": "homeassistant/status",
        "payload": "online",
        "qos": 0,
        "retain": false
      },
      "will_message": {
        "topic": "homeassistant/status",
        "payload": "offline",
        "qos": 0,
        "retain": false
      },
      "discovery": true,
      "discovery_prefix": "homeassistant"
    },
    "device": {
      "id": "fcacf4f741f9ed868f779651589d7b25",
      "name": "HygroTemp-Yadablada",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_battery",
          "icon": null,
          "original_device_class": "battery",
          "original_icon": null,
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_battery",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "%",
              "device_class": "battery",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada battery"
            },
            "last_changed": "2024-03-11T16:41:58.477199+00:00",
            "last_updated": "2024-03-11T16:41:58.477199+00:00"
          },
          "unit_of_measurement": "%"
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_temperature",
          "icon": null,
          "original_device_class": "temperature",
          "original_icon": null,
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_temperature",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada temperature"
            },
            "last_changed": "2024-03-11T16:41:58.476857+00:00",
            "last_updated": "2024-03-11T16:41:58.476857+00:00"
          },
          "unit_of_measurement": "\u00b0C"
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_humidity",
          "icon": null,
          "original_device_class": "humidity",
          "original_icon": null,
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_humidity",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "%",
              "device_class": "humidity",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada humidity"
            },
            "last_changed": "2024-03-11T16:41:58.476672+00:00",
            "last_updated": "2024-03-11T16:41:58.476672+00:00"
          },
          "unit_of_measurement": "%"
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_pressure",
          "icon": null,
          "original_device_class": "pressure",
          "original_icon": null,
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_pressure",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "hPa",
              "device_class": "pressure",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada pressure"
            },
            "last_changed": "2024-03-11T16:41:58.476481+00:00",
            "last_updated": "2024-03-11T16:41:58.476481+00:00"
          },
          "unit_of_measurement": "hPa"
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_voltage",
          "icon": null,
          "original_device_class": "voltage",
          "original_icon": null,
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_voltage",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada voltage"
            },
            "last_changed": "2024-03-11T16:41:58.476193+00:00",
            "last_updated": "2024-03-11T16:41:58.476193+00:00"
          },
          "unit_of_measurement": "V"
        },
        {
          "device_class": null,
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_linkquality",
          "icon": null,
          "original_device_class": null,
          "original_icon": "mdi:signal",
          "state": {
            "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_linkquality",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "lqi",
              "icon": "mdi:signal",
              "friendly_name": "HygroTemp-Yadablada HygroTemp-Yadablada linkquality"
            },
            "last_changed": "2024-03-11T16:41:58.475836+00:00",
            "last_updated": "2024-03-11T16:41:58.475836+00:00"
          },
          "unit_of_measurement": "lqi"
        }
      ]
    },
    "mqtt_debug_info": {
      "entities": [
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_battery",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/battery/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "device_class": "battery",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada battery",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_battery_zigbee_apartment",
              "unit_of_measurement": "%",
              "value_template": "{{ value_json.battery }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        },
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_temperature",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/temperature/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "device_class": "temperature",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada temperature",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_temperature_zigbee_apartment",
              "unit_of_measurement": "\u00b0C",
              "value_template": "{{ value_json.temperature }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        },
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_humidity",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/humidity/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "device_class": "humidity",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada humidity",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_humidity_zigbee_apartment",
              "unit_of_measurement": "%",
              "value_template": "{{ value_json.humidity }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        },
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_pressure",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/pressure/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "device_class": "pressure",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada pressure",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_pressure_zigbee_apartment",
              "unit_of_measurement": "hPa",
              "value_template": "{{ value_json.pressure }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        },
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_voltage",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/voltage/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "device_class": "voltage",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada voltage",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_voltage_zigbee_apartment",
              "unit_of_measurement": "V",
              "value_template": "{{ value_json.voltage }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        },
        {
          "entity_id": "sensor.hygrotemp_yadablada_hygrotemp_yadablada_linkquality",
          "subscriptions": [
            {
              "topic": "zigbee_apartment/bridge/state",
              "messages": [
                {
                  "payload": "online",
                  "qos": 0,
                  "retain": 1,
                  "time": "2024-03-11T16:41:58.475374+00:00",
                  "topic": "zigbee_apartment/bridge/state"
                }
              ]
            },
            {
              "topic": "zigbee_apartment/HygroTemp-Yadablada",
              "messages": []
            }
          ],
          "discovery_data": {
            "topic": "homeassistant/sensor/0x00158d0005446d21/linkquality/config",
            "payload": {
              "availability": [
                {
                  "topic": "zigbee_apartment/bridge/state"
                }
              ],
              "device": {
                "identifiers": [
                  "zigbee2mqtt_0x00158d0005446d21"
                ],
                "manufacturer": "Xiaomi",
                "model": "Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)",
                "name": "HygroTemp-Yadablada",
                "sw_version": "Zigbee2MQTT 1.18.1"
              },
              "icon": "mdi:signal",
              "json_attributes_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "name": "HygroTemp-Yadablada linkquality",
              "state_topic": "zigbee_apartment/HygroTemp-Yadablada",
              "unique_id": "0x00158d0005446d21_linkquality_zigbee_apartment",
              "unit_of_measurement": "lqi",
              "value_template": "{{ value_json.linkquality }}",
              "platform": "mqtt"
            }
          },
          "transmitted": []
        }
      ],
      "triggers": []
    }
  }

**Comment by Koenkk** [comment]
You are using a very outdated z2m version, update to the new addon: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

**Comment by embcla** [comment]
Would you know why it does not show any available updates? Other modules work normally, but this one doesn't apparently
