### ISSUE TITLE
Tuya TS011F_plug_3  _TZ3000_cphmq0q7 WGH-JLCZ02

### ISSUE THREAD

**Issue by GeorgeWatch** [Koenkk/zigbee2mqtt#21770]
### What happened?

I bought two sockets from aliexpress. They look the same as before
models TS011F.
The problem is that they don't show:
Power, Current, Voltage.
How to solve it?
Thank you.

TUYA Cloud expose:
Product Name
WGH-JLCZ02
Device ID
bfd0aa95515cfc2c17quct
Product Category
cz
Device Status
Online

switch_1	Boolean	
"{true,false}"
countdown_1	Integer	
{
  "unit": "s",
  "min": 0,
  "max": 43200,
  "scale": 0,
  "step": 1
}
add_ele	Integer	
{
  "unit": "kwh",
  "min": 0,
  "max": 100000000,
  "scale": 3,
  "step": 100
}
cur_current	Integer	
{
  "unit": "mA",
  "min": 0,
  "max": 30000,
  "scale": 0,
  "step": 1
}
cur_power	Integer	
{
  "unit": "W",
  "min": 0,
  "max": 50000,
  "scale": 1,
  "step": 1
}
cur_voltage	Integer	
{
  "unit": "V",
  "min": 0,
  "max": 5000,
  "scale": 1,
  "step": 1
}
relay_status	Enum	
{
  "range": [
    "power_off",
    "power_on",
    "last"
  ]
}
light_mode	Enum	
{
  "range": [
    "none",
    "relay",
    "pos"
  ]
}
child_lock	Boolean	
"{true,false}"

### What did you expect to happen?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/46403712/a1f002be-6b3c-4bd8-89a2-91496fdc8988)

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

0x26780700

### Adapter

ConBeeII

### Setup

HomeAssistant OS

**Comment by mrmaximas** [comment]
depend of your os in the zigbee2mqtt folder please find /data/database.db then post db entry for this device.
