### ISSUE TITLE
bticino K4027C expose the unsupported titl capabilities

### ISSUE THREAD

**Issue by rdl987** [Koenkk/zigbee2mqtt#21781]
### What happened?

The bticino K4027C connected shutter control is recognized as Legrand 067776A and it show the tilt capabilities that a roller shutter hasn't.

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

2022126

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

Docker

**Comment by FabianMangold** [comment]
Hello @rdl987 ,

Could you please take a look at https://github.com/Koenkk/zigbee2mqtt/issues/19621
The root cause / fix is likely the same.
Could you please test the latest DEV branch ?

Cheers
