### ISSUE TITLE
Timeout issues - no response received (206)

### ISSUE THREAD

**Issue by shalak** [Koenkk/zigbee2mqtt#21792]
### What happened?

I've been experiencing frequent timeout issues with Zigbee2MQTT in Home Assistant since yesterday - for the majority of my devices. Most frequently it looks like the first request to a device, for example, toggling the left button, works fine. However, subsequent requests, like attempting to toggle the right button immediately after, result in a timeout. After couple of minutes the request goes through.

Although, this behavior is not consistent - sometimes I can get 10 consecutive requests working on, while then the 11th times out...

Here's a snippet of the log indicating the problem:

```
Publish 'set' 'state' to 'VR Room' failed: 'Error: Command 0x00124b002226f636/2 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (206))'
```

Devices affected:
- [TS0011](https://www.zigbee2mqtt.io/devices/TS0011.html#tuya-ts0011)
- [TS0012](https://www.zigbee2mqtt.io/devices/TS0012.html#tuya-ts0012)
- [TS0121_plug](https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121_plug)
- [ZB-SW01](https://www.zigbee2mqtt.io/devices/ZB-SW01.html#ewelink-zb-sw01)
- [ZB-SW02](https://www.zigbee2mqtt.io/devices/ZB-SW02.html#ewelink-zb-sw02)
- [ZB-SW03](https://www.zigbee2mqtt.io/devices/ZB-SW03.html#ewelink-zb-sw03)

However, the issues does not happen at all for those:

- [QS-Zigbee-S04-2C-LN](https://www.zigbee2mqtt.io/devices/QS-Zigbee-S04-2C-LN.html#lonsonho-qs-zigbee-s04-2c-ln)
- [TS011F_plug_1](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)
- [WS-EUK01](https://www.zigbee2mqtt.io/devices/WS-EUK01.html#aqara-ws-euk01)

HA Core: 2024.3.0
HA Supervisor: 2024.03.0
Z2M Add-On: 1.36.0-1
ConBee2/RaspBee2 version 0x26780700

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Setup

HA x86, as add-on

**Comment by kremik** [comment]
Having the same issue also with other devices
