### ISSUE TITLE
[New device support, Help needed multiple Endpoints]: 

### ISSUE THREAD

**Issue by Nailik** [Koenkk/zigbee2mqtt#21800]
### Link

https://merten.de/produkt/meg5172-0000-universal-dimmer-einsatz-2fach.html

### Database entry

{"id":12,"type":"Router","ieeeAddr":"0x540f57fffe306b17","nwkAddr":6330,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Mains (single phase)","modelId":"2GANG/DIMMER/2","epList":[3,4,21,22,242],"endpoints":{"3":{"profId":260,"epId":3,"devId":257,"inClusterList":[0,3,4,5,6,8,769,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"2GANG/DIMMER/2","manufacturerName":"Schneider Electric","powerSource":1,"zclVersion":3,"appVersion":2,"stackVersion":6,"hwVersion":2,"dateCode":"","swBuildId":"002.004.020 R"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe1695e8","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}},"4":{"profId":260,"epId":4,"devId":257,"inClusterList":[0,3,4,5,6,8,769,2821],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"dateCode":""}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe1695e8","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}},"21":{"profId":260,"epId":21,"devId":260,"inClusterList":[0,3,2821,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"22":{"profId":260,"epId":22,"devId":260,"inClusterList":[0,3,2821,65303],"outClusterList":[3,4,5,6,8,258],"clusters":{"genBasic":{"attributes":{"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":6,"hwVersion":2,"dateCode":"","swBuildId":"002.004.020 R","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1710440949781}

### Comments

Hi,

i want to support the Meg5172-0000 with 2 Channels but have issues using the Second Endpoint.
Unfortunately i can only modify the first endpoint and when i change something for the first Endpoint 21/right then the settings for 22/left change as well.
Also brightness is only shown once:

![Screenshot 2024-03-14 at 20 10 03](https://github.com/Koenkk/zigbee2mqtt/assets/13292441/de293452-9fc5-41d2-9c34-c29721c2030c)
![Screenshot 2024-03-14 at 20 09 51](https://github.com/Koenkk/zigbee2mqtt/assets/13292441/5bbf1a45-080e-46f2-8522-589a574491b8)

### External definition

```shell
const definition = {
    zigbeeModel: ['2GANG/DIMMER/2'],
    model: 'MEG5126-0300/MEG5172-0000',
    vendor: 'Schneider Electric',
    description: 'Merten MEG5172 PlusLink Dimmer insert with Merten Wiser System M Push Button (2fold)',
    fromZigbee: [fz.level_config, fz.wiser_lighting_ballast_configuration],
    toZigbee: [tz.level_config, tz.ballast_config, tz.wiser_dimmer_mode],
    exposes: [
        e.numeric('ballast_minimum_level', ea.ALL).withValueMin(1).withValueMax(254)
            .withDescription('Specifies the minimum light output of the ballast'),
        e.numeric('ballast_maximum_level', ea.ALL).withValueMin(1).withValueMax(254)
            .withDescription('Specifies the maximum light output of the ballast'),
        e.enum('dimmer_mode', ea.ALL, ['auto', 'rc', 'rl', 'rl_led'])
            .withDescription('Sets dimming mode to autodetect or fixed RC/RL/RL_LED mode (max load is reduced in RL_LED)'),
        e.action(['on', 'off', 'brightness_move_up', 'brightness_move_down', 'brightness_stop', 'recall_*']),
    ],
    extend: [
        deviceEndpoints({endpoints: {'left': 4, 'right': 3, 'left_btn': 22, 'right_btn': 21}}), 
        light({endpointNames: ['left', 'right'], configureReporting: true}), 
        switchActions('left_btn'), switchActions('right_btn'), 
        indicatorMode('left_btn'),
    ],
};
```

**Comment by Nailik** [comment]
Figured out allmost everything .. the only thing i cannot get to work is e.action() i get no reportings of any click on a button :/

**Comment by Koenkk** [comment]
what is loggen in the debug log when triggering actions on the device?

**Comment by Nailik** [comment]
@Koenkk do i need e.action to see it in the logs or should it always be shown ?

**Comment by Koenkk** [comment]
What action do you expect? This is not a remote right? It reports a physical state change which is good.

**Comment by Nailik** [comment]
i was hoping for it to also tell me when a button is pressed.
I recently added support for the 2 buttons / 1 dimmer model and i wanted to use the secondary button set for another device. However i only managed to setup the secondary buttons for a scene that's internally stored on the device (like store a brightness level and use the secondary buttons to go to this brightness level)

**Comment by Koenkk** [comment]
You can use the [state action](https://www.zigbee2mqtt.io/devices/046677552343.html#options) option for this

Since your external converter looks good, could you make a pull request?

**Comment by Nailik** [comment]
it was this pr https://github.com/Koenkk/zigbee-herdsman-converters/pull/7222
