### ISSUE TITLE
zigbee2mqtt restarting itself with no reason (or is some reason?)

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#21811]
### What happened?

zigbee2mqtt restarting with no reason, or maby is some reason.  I dont know. Since i thing Feb update maby January

<html>
<body>

Wersja | core-2024.3.1
-- | --
Typ instalacji | Home Assistant OS
Wersja deweloperska | false
Supervisor | true
Docker | true
Użytkownik | root
Środowisko wirtualne | false
Wersja Pythona | 3.12.2
Rodzina systemu operacyjnego | Linux
Wersja systemu operacyjnego | 6.6.20-haos
Architektura procesora | x86_64

</body>
</html>

<html>
<body>

System operacyjny hosta | Home Assistant OS 12.1
-- | --
Kanał aktualizacji | stable
Wersja Supervisora | supervisor-2024.03.0
Wersja agenta | 1.6.0
Wersja Dockera | 24.0.7
Pojemność dysku | 234.0 GB
Pojemność użyta | 29.8 GB
Zdrowy | true
Wspierany | true
Układ | generic-x86-64
API Supervisora | ok

</body>
</html>

### What did you expect to happen?

working without restarting

### How to reproduce it (minimal and precise)

i dont know, just install newest ver and wait for restart

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

### Setup

addon on HA  OS Generic x86-64

### Debug log

no debug log

**Comment by srett** [comment]
Without a z2m Log this is impossible to debug, might be fixed in the current dev version though if you can figure out how to install that.
