### ISSUE TITLE
Add update interval configuration to  _TZE204_81yrt3lo Energy Meter

### ISSUE THREAD

**Issue by flybrys** [Koenkk/zigbee2mqtt#21818]
### What happened?

Device works fine, however the manual I got with mine mentioned that the update interval could be changed in the Tuya Smart app. I can confirm you can set this as low as 3 seconds.

### What did you expect to happen?

I was hoping I could configure the update interval for the device via Zigbee2MQTT, however to do so I need to pair to a tuya hub and use the app to change, then pair it with Z2M again. the default 10 seconds is a little too long for live monitoring.

### How to reproduce it (minimal and precise)

Pair Device to Zigbee2MQTT
Discover ability to change update interval from 10s does not exist
Pair device to Tuya Hub and pair to Tuya Smart Life App
Enter in the calibration menu for the device and be able to change the interval

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20220219

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Home Assistant Add-on on Unraid VM

**Comment by Koenkk** [comment]
We need to reverse engineer the calls send by TuYa gateway in order to support this from z2m. Could you sniff the traffic when changing the reporting interval via the TuYa gateway? ([guide](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html))
