### ISSUE TITLE
Extension of Calibration Range for Thermostat  (AVATTO) ME168

### ISSUE THREAD

**Issue by DoWenzl94** [Koenkk/zigbee2mqtt#21828]
### What happened?

Extension of Calibration Range for Thermostat  (AVATTO) ME168 in Tuya.js

Currently, in the Tuya.js file, the calibration range for the thermostat (AVATTO) ME168 is limited to -3 to 3. However, there are scenarios where a wider calibration range is needed. I have successfully extended the calibration range from -3 to 3 to -9 to 9 by manually modifying the relevant section in the Tuya.js file.

I propose to officially extend the calibration range for the thermostat in Tuya.js to accommodate broader needs. This would provide users with greater flexibility and better customization options for their thermostats:

fingerprint: tuya.fingerprint('TS0601', [
            '_TZE200_bvu2wnxz', /* model: 'ME167', vendor: 'AVATTO' */
            '_TZE200_6rdj8dzm', /* model: 'ME167', vendor: 'AVATTO' */
            '_TZE200_p3dbf6qs', /* model: 'ME168', vendor: 'AVATTO' */
            '_TZE200_rxntag7i', /* model: 'ME168', vendor: 'AVATTO' */
        ]),
        model: 'TS0601_thermostat_3',
        vendor: 'TuYa',
        description: 'Thermostatic radiator valve',
        fromZigbee: [tuya.fz.datapoints],
        toZigbee: [tuya.tz.datapoints],
        whiteLabel: [
            tuya.whitelabel('AVATTO', 'ME167', 'Thermostatic radiator valve', ['_T>
            tuya.whitelabel('AVATTO', 'ME168', 'Thermostatic radiator valve', ['_T>
        ],
        onEvent: tuya.onEventSetTime,
        configure: tuya.configureMagicPacket,
        exposes: [
            e.child_lock(), e.battery_low(),
            e.climate()
                .withSetpoint('current_heating_setpoint', 5, 35, 1, ea.STATE_SET)
                .withLocalTemperature(ea.STATE)
                .withSystemMode(['auto', 'heat', 'off'], ea.STATE_SET)
                .withRunningState(['idle', 'heat'], ea.STATE)
                .withLocalTemperatureCalibration(-9, 9, 1, ea.STATE_SET),   <--------------- HERE

### What did you expect to happen?

By extending the calibration range, users can fine-tune the behavior of their thermostats more precisely, especially in scenarios where wider temperature variations need to be accommodated. This enhancement would improve the overall usability and flexibility of Zigbee2mqtt for users with diverse requirements.

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20230507

### Adapter

CC2652P

### Setup

Pi4

**Comment by Koenkk** [comment]
Updated.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by DoWenzl94** [comment]
Hi @Koenkk 

I would like to reopen / follow up on this topic with a request to further extend the local temperature calibration range.

After using the extended range (-9 to +9) for some time, I noticed that in real-world winter scenarios this is still not sufficient. In my setup, the AVATTO ME168 thermostat is mounted close to an entrance door. During winter, opening the door frequently causes a significant local temperature deviation compared to the actual room temperature.

In these cases, the difference can exceed 9°C, making it impossible to properly compensate using the current calibration limits. I therefore propose extending the calibration range further to -19 to +19:

.withLocalTemperatureCalibration(-19, 19, 1, ea.STATE_SET)

This change would not affect users who don’t need it, but would greatly improve usability for installations with challenging sensor placement (e.g. near doors, windows, or poorly insulated areas).

Since the device itself accepts higher calibration values without issues, exposing this wider range in Zigbee2MQTT would provide additional flexibility without negative side effects.

Thanks for considering this enhancement.

**Comment by Koenkk** [comment]
Done!

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.
