### ISSUE TITLE
what's the correlation between pan_id and panId

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#2182]
## Config
I have 2 different raspberry's, both running zigbee2mqtt

### SETUP 1
configuration.yaml:
`pan_id: 0x1a66`

log.txt
`"panId":6758`

### SETUP 2
configuration.yaml:
`  pan_id: 0x1a62`

log.txt
`"panId":6754`

## Questions
- What's the correlation between the value in the config and the value in the log?
- To avoid problems like https://github.com/Koenkk/zigbee2mqtt/issues/2181, shoud I always use my own custom pan_id so my neighbour can not mess with my zigbee network?

## Debug Info
Zigbee2mqtt version 1.6.0 
on bare-metal RPI3
CC2531_USB-stick (using an USB extension cable)
latest firmwareversion: CC2531_DEFAULT_20190608.zip

**Comment by Koenkk** [comment]
One is in hex, other one is in decimal (https://www.google.com/search?q=0x1a66+to+decimal&oq=0x1a66+to+decimal&aqs=chrome..69i57j6.1391j0j7&sourceid=chrome&ie=UTF-8)
