### ISSUE TITLE
Error: Cluster 'liXeePrivate' has no attribute 'motDEtat'

### ISSUE THREAD

**Issue by quentinus95** [Koenkk/zigbee2mqtt#21825]
### What happened?

Everytime the Lixee device is polled, Zigbee2MQTT displays the following error log:

> Error: Cluster 'liXeePrivate' has no attribute 'motDEtat'

The device works properly.

Maybe related to this commit (https://github.com/Koenkk/zigbee-herdsman-converters/pull/5970).

### What did you expect to happen?

No error in logs, or a way to silent it.

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20210708

### Adapter

Sonos

### Setup

Containerized Zigbee2MQTT

**Comment by Minims** [comment]
Same issue with the 1.37  version updated today

**Comment by Sabjul33** [comment]
Hi, Same thing for me V 1.36 updated to 1.37
Failed to read zigbee attributes: Error: Cluster 'liXeePrivate' has no attribute 'motDEtat'

**Comment by Koenkk** [comment]
@SilentT-FR it seems `motDEtat` is missing from the [cluster](https://github.com/Koenkk/zigbee-herdsman/blob/1b76db9a8afd599162340cf98e0bad0b6ad351c7/src/zcl/definition/cluster.ts#L4578), do you know the attribute ID and data type?

**Comment by scientas** [comment]
> @SilentT-FR it seems `motDEtat` is missing from the [cluster](https://github.com/Koenkk/zigbee-herdsman/blob/1b76db9a8afd599162340cf98e0bad0b6ad351c7/src/zcl/definition/cluster.ts#L4578), do you know the attribute ID and data type?

Hello, same problem...
Found that on instruction manual :
Add MOTDETAT value (from historic mode) --> Cluster : 0xFF66 - Attribut :
0x0009
Add null value for all of default metering properties
Add watchdog reset process when hardfault error
Fix duplicate voltage acquisition
Fix operator error for comparison
Hope this help...

**Comment by Koenkk** [comment]
Does the manual also mention the data type?

**Comment by scientas** [comment]
It seems to be "string" with "000000" default value

**Comment by Koenkk** [comment]
Added it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
