### ISSUE TITLE
IKEA TRADFRI bulb E27 CWS opal 600lm cannot publish ON/OFF

### ISSUE THREAD

**Issue by kremik** [Koenkk/zigbee2mqtt#21841]
### What happened?

Not able to interact with the device (RGB Lightbulb [LED1624G9]). Getting error mentioned below. E.g. when I want to turn it ON va Z2M/Expose. I'm getting this error with more IKEA devices (e.g. TRADFRI Driver 30W [ICPSHC24-30EU-IL-1]). Sometimes some are not responding and other do, other time the ones wich didn't respond are responding and the other not. TRADFRI Driver 30W log also included. Sometimes helps the entire restart of RPi, not only Z2M.

### What did you expect to happen?

That the device is will turn ON/OFF or interact anyhow.

### How to reproduce it (minimal and precise)

When I set in Z2M web interface Expose/State/ON I get the error and device not responding.

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20210211

### Adapter

CC2652P

### Setup

RPi 4B 64bit, plain NOT containerized

### Debug log

Debug 2024-03-17 08:47:25Received MQTT message on 'zigbee2mqtt/ikeabulb2rgb/set' with data '{"state":"ON"}'
Debug 2024-03-17 08:47:25Publishing 'set' 'state' to 'ikeabulb2rgb'
Error 2024-03-17 08:47:31Publish 'set' 'state' to 'ikeabulb2rgb' failed: 'Error: Command 0x842e14fffe77255a/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Debug 2024-03-17 08:47:31Error: Command 0x842e14fffe77255a/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:312:45 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:26) at Znp.request (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:27) at ZStackAdapter.dataRequest (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:965:24) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:387:46) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:357:25 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:26) at ZStackAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:355:27) at Request.func (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:274:35)
Info 2024-03-17 08:47:31MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'ikeabulb2rgb' failed: 'Error: Command 0x842e14fffe77255a/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"ikeabulb2rgb"},"type":"zigbee_publish_error"}'

FOR the IKEA LED [ICPSHC24-30EU-IL-1]

Debug 2024-03-17 08:52:12Received MQTT message on 'zigbee2mqtt/ikealed/set' with data '{"state":"ON"}'
Debug 2024-03-17 08:52:12Publishing 'set' 'state' to 'ikealed'
Error 2024-03-17 08:52:18Publish 'set' 'state' to 'ikealed' failed: 'Error: Command 0xb4e3f9fffe601396/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Debug 2024-03-17 08:52:18Error: Command 0xb4e3f9fffe601396/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:312:45 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:26) at Znp.request (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:27) at ZStackAdapter.dataRequest (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:965:24) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:387:46) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:357:25 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:26) at ZStackAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:355:27) at Request.func (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:274:35)
Info 2024-03-17 08:52:18MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'ikealed' failed: 'Error: Command 0xb4e3f9fffe601396/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"ikealed"},"type":"zigbee_publish_error"}'

**Comment by Koenkk** [comment]
It looks that your coordinator crashed, since you are using an old firmware, the [new firmware from this thread](https://github.com/Koenkk/Z-Stack-firmware/discussions/496) might help.
