### ISSUE TITLE
[New device support]: GiEX Water Valve GX02

### ISSUE THREAD

**Issue by dgaust** [Koenkk/zigbee2mqtt#21844]
### Link

https://www.aliexpress.com/item/1005006547328147.html

### Database entry

{"id":35,"type":"EndDevice","ieeeAddr":"0xa4c138bb891ac9d9","nwkAddr":11184,"manufId":4417,"manufName":"_TZE204_7ytb3h8u","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"G@ -\u0011","65506":56,"65508":0,"65534":0,"appVersion":73,"manufacturerName":"_TZE204_7ytb3h8u","zclVersion":3,"modelId":"TS0601","powerSource":3,"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1710669460078}

### Comments

This is an updated version of the QT06 devices that are currently supported by zigbee2mqtt, I have managed to create an external definitions file for the device which works. It's the same as the QT06_2 device, just a different fingerprint.

### External definition

```shell
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const MINUTES_IN_A_DAY = 1440;
const SECONDS_IN_12_HOURS = 43200;

module.exports = [
    {
        fingerprint: [
            {modelID: 'TS0601', manufacturerName: '_TZE204_7ytb3h8u'},
        ],
        model: 'GX02',
        vendor: 'GiEX',
        description: 'GX02 GiEX Water Valve',
        extend: [],
        meta: {},
        onEvent: tuya.onEventSetLocalTime,
        fromZigbee: [legacy.fromZigbee.giexWaterValve],
        toZigbee: [legacy.toZigbee.giexWaterValve],
        exposes: [
            e.battery(),
            e.binary(legacy.giexWaterValve.state, ea.STATE_SET, 'ON', 'OFF')
                .withDescription('State'),
            e.enum(legacy.giexWaterValve.mode, ea.STATE_SET, ['duration', 'capacity'])
                .withDescription('Irrigation mode'),
            e.numeric(legacy.giexWaterValve.cycleIrrigationNumTimes, ea.STATE_SET)
                .withValueMin(0)
                .withValueMax(100)
                .withDescription('Number of cycle irrigation times, set to 0 for single cycle'),
            e.numeric(legacy.giexWaterValve.irrigationStartTime, ea.STATE)
                .withDescription('Last irrigation start time'),
            e.numeric(legacy.giexWaterValve.irrigationEndTime, ea.STATE)
                .withDescription('Last irrigation end time'),
            e.numeric(legacy.giexWaterValve.lastIrrigationDuration, ea.STATE)
                .withDescription('Last irrigation duration'),
            e.numeric(legacy.giexWaterValve.waterConsumed, ea.STATE)
                .withUnit('L')
                .withDescription('Last irrigation water consumption'),
            e.numeric(legacy.giexWaterValve.irrigationTarget, ea.STATE_SET)
                .withValueMin(0)
                .withValueMax(SECONDS_IN_12_HOURS)
                .withUnit('seconds or litres')
                .withDescription('Irrigation target, duration in seconds or capacity in litres (depending on mode), ' +
                    'set to 0 to leave the valve on indefinitely, ' +
                    'for safety reasons the target will be forced to a minimum of 10 seconds in duration mode'),
            e.numeric(legacy.giexWaterValve.cycleIrrigationInterval, ea.STATE_SET)
                .withValueMin(0)
                .withValueMax(SECONDS_IN_12_HOURS)
                .withUnit('sec')
                .withDescription('Cycle irrigation interval'),
        ],
    },
];
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by robin0793** [comment]
Hi, i have the same device, but it reports as _TZE200_2ytb3h8u.
I added the external definition from the mentioned commit, seems to work fine.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/21172172/e41660d6-5c63-4db5-b139-983601d4af61)

**Comment by dgaust** [comment]
Interesting, wonder what the differences are (if any)
________________________________

**Comment by Federfox** [comment]
I have the exact same valve but it has a different Vendor ID, would it be possible to add manufacturerName _TZE284_7ytb3h8u ?
I have other identical tubes with a recognized vendor, I checked the board and it is identical.

Thank you!

**Comment by hazmemoria** [comment]
I have the exact same valve but it has a different Vendor ID, would it be possible to add manufacturerName _TZE284_7ytb3h8u ?
Thank You
![Screenshot 2024-07-01 10 29 17](https://github.com/Koenkk/zigbee2mqtt/assets/156531935/de70a78e-b6a0-4026-99ff-b1d1c140ba6e)

**Comment by acuszka** [comment]
> I have the exact same valve but it has a different Vendor ID, would it be possible to add manufacturerName _TZE284_7ytb3h8u ? Thank You ![Screenshot 2024-07-01 10 29 17](https://private-user-images.githubusercontent.com/156531935/344600969-de70a78e-b6a0-4026-99ff-b1d1c140ba6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjMyMTAsIm5iZiI6MTcxOTgyMjkxMCwicGF0aCI6Ii8xNTY1MzE5MzUvMzQ0NjAwOTY5LWRlNzBhNzhlLWI2YTAtNDAyNi05OWZmLWIxZDFjMTQwYmE2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwODM1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmMyZmM0M2VmZmJlZjQ2ZGU1NjE4NjNmYjYxZmJjNjc1NmFlY2VhYTgzZGNmNzIzNDI2MzRiMmI3MGIzY2RlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ftRg2umkrM6oyCT0UlFMMsEGMZrw22cjUS5v-h9PT0)

I also have _TZE284_7ytb3h8u and it shows as unsupported.

**Comment by oliverwoodings** [comment]
7ytb3h8u is already supported in the herdsman converters: https://github.com/Koenkk/zigbee-herdsman-converters/commit/dbef5e6b8c7b98ef230860880ac225eccfa2eb31

Likely you just need to wait for the next release of zigbee2mqtt so those changes get through. If you're impatient, switch to the dev branch and you'll get the latest version of herdsman (if you're using the HA addon, you need to switch to the 'Edge' version of z2m)

**Comment by acuszka** [comment]
> 7ytb3h8u is already supported in the herdsman converters: [Koenkk/zigbee-herdsman-converters@dbef5e6](https://github.com/Koenkk/zigbee-herdsman-converters/commit/dbef5e6b8c7b98ef230860880ac225eccfa2eb31)
> 
> Likely you just need to wait for the next release of zigbee2mqtt so those changes get through. If you're impatient, switch to the dev branch and you'll get the latest version of herdsman (if you're using the HA addon, you need to switch to the 'Edge' version of z2m)

I confirm it's working with new zigbee2mqtt 1.39

![image](https://github.com/Koenkk/zigbee2mqtt/assets/27306071/6dc836ec-b9cc-4877-a115-1964b34fa17e)

**Comment by feserdel** [comment]
Good morning, in my case, 

_TZE200_7ytb3h8u is detected wrongly as QT06_2 (but is GX02, the green one), however, another valve that I own _TZE204_7ytb3h8u is detected correctly as [GX02]

What is the solution?

![image](https://github.com/user-attachments/assets/842664ae-d3d7-415c-bce6-09cfc88a3572)
![image](https://github.com/user-attachments/assets/c2ccf270-1fd8-4769-b487-4876c7b9866a)

NOTE: Im using Home Assistant add-on

Versión de Zigbee2MQTT [1.39.1]
zigbee-herdsman-converters version 19.72.0

**Comment by hellomarb** [comment]
I have the same issue:

```
Zigbee-Model: TS0601
Zigbee-Manufacturer: _TZE200_7ytb3h8u
Model: QT06_2
``` 
But it should be the GX02

**Comment by heidle78** [comment]
Here the same issues, correlation to the right valve GX02 not working - I have the green version
![image](https://github.com/user-attachments/assets/2364d4e3-70f6-44ad-9ee3-811f18a387c9)

**Comment by heidle78** [comment]
Deleted the device again and took now the DEV branch - no change:

![image](https://github.com/user-attachments/assets/188f2adf-ef7e-4e47-bb06-0e9df64c40a5)

**Comment by jochenruben** [comment]
Hello,
I have the same problem three GX02 are recognised as QT06_2. Two of them are working. One can‘t be switched.
Will there be a solution?
Thanx a lot!

**Comment by jochenruben** [comment]
> Hello, I have the same problem three GX02 are recognised as QT06_2. Two of them are working. One can‘t be switched. Will there be a solution? Thanx a lot!

Zigbee2MQTT-Version
[1.39.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.39.1) commit: [unknown](https://github.com/Koenkk/zigbee2mqtt/commit/unknown) With the latest Version of HA as adon

**Comment by heidle78** [comment]
I updated the firmware and even there the same result:
![image](https://github.com/user-attachments/assets/b632a49f-b988-4a80-a26b-357359f0e505)

**Comment by heidle78** [comment]
It seems I can control, but the picture is definitely not correct - I have the green version

**Comment by jochenruben** [comment]
Think I've identified the problem. I bought three GX02-ZG. Supported by Z2MQTT is GX02 (https://www.zigbee2mqtt.io/devices/GX02.html). Both are green and GX02-ZG is the lates version.
Sims like GX02-ZG are recognized as QT06_2. I got all three work as QT06_2, but they need to have a very good connectivity.

**Comment by idogrf** [comment]
opened a PR to fix the GUI for `_TZE200_7ytb3h8u` - https://github.com/Koenkk/zigbee-herdsman-converters/pull/7935

**Comment by idogrf** [comment]
as of version `1.40.1`, `_TZE200_7ytb3h8u` now appears as the correct version in the GUI

**Comment by iLLNESS** [comment]
Is there a way to change the TZ this device reports for time?
