### ISSUE TITLE
ZLinky + current_tier1_summ_delivered

### ISSUE THREAD

**Issue by BenCaaaaA** [Koenkk/zigbee2mqtt#21856]
### What happened?

Hi,
I've got a problem with MQTT Manager to read my Linky data (the unit is on kWh and were on wH before my migration from the legacy zigged plugin). I'm use these plugin with Jeedom and the release of MQTT2 is 1.36.0.

It's a big problem to me about the "non precision" of data. As I describe, before the migration from Zigbee to JeeZigbee (and the installation to MQTT2), the data are accurate cause they are x1000.

Does someone have already this problem ? does it's another problem ? 
Thank you.

### What did you expect to happen?

A response to the regression or the manipulation to have the correct unit (the unit that the Zlinky_TIC I have before)

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

23/02/2024

### Adapter

EZSP

### Setup

Jeedom ATLAS

### Debug log

[z2md.json](https://github.com/Koenkk/zigbee2mqtt/files/14635618/z2md.json)
[z2m.json](https://github.com/Koenkk/zigbee2mqtt/files/14635619/z2m.json)

**Comment by Gouns68** [comment]
Hello, I had the same problem as you. I solved the problem in 2 steps. On Jeedom, I added the formula "#value#*1000" in the command configuration, rounding to 3. Then in Zigbee2MQTT, on the device, in "Settings (specific)", you set "kWh precision" to 3.
