### ISSUE TITLE
[New device support]: CK-BL702-ROUTER-01(7018)

### ISSUE THREAD

**Issue by tiagofontoura** [Koenkk/zigbee2mqtt#21858]
### Link

https://pt.aliexpress.com/item/1005006512670714.html?spm=a2g0o.order_list.order_list_main.11.423acaa4HK21rQ&gatewayAdapt=glo2bra

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0x7cb94c7834d10000","nwkAddr":31211,"manufId":4742,"manufName":"eWeLink","powerSource":"Unknown","modelId":"CK-BL702-ROUTER-01(7018)","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":8,"inClusterList":[0,3,4,5,6,4096,64599],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"hwVersion":0}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e29fde","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}}},"appVersion":1,"stackVersion":0,"hwVersion":0,"dateCode":"20210610-BL","swBuildId":"1.0.0","zclVersion":8,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1710768018458}

### Comments

please help! tks

### External definition

```shell
const {onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['CK-BL702-ROUTER-01(7018)'],
    model: 'CK-BL702-ROUTER-01(7018)',
    vendor: 'eWeLink',
    description: 'Automatically generated definition',
    extend: [onOff({"powerOnBehavior":false})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
