### ISSUE TITLE
Ikea Switch paired but log shows no messages

### ISSUE THREAD

**Issue by nezteew** [Koenkk/zigbee2mqtt#2185]
# Bug Report
## What happened
I bought an IKEA Switch (E1743) and paired it successfully:

info  2019-10-20T18:31:23: Currently 10 devices are joined:
info  2019-10-20T18:31:23: tradfri-switch-1 (0x14b457fffec8d6c4): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)

After a while I also see the following status message:
info  2019-10-21T14:01:12: MQTT publish: topic 'zigbee2mqtt/tradfri-switch-1', payload '{"battery":87,"linkquality":31}'

But that is the only thing what happens.
When i use the switch no messages are send and the logfile shows nothing.
So I can not use the buttons,

The firmware on my CC2531 is one year old. Can this be the reason? Do I have to update it in order to support the IKEA switch fully?

## What did you expect to happen
zigbee2mqtt generates MQTT messages for button presses.

## How to reproduce it (minimal and precise)
see above.

## Debug Info
zigbee2mqtt version: 1.6.0 (commit #ff9e6cd)
CC253X firmware version:
Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20180507}}'

**Comment by Koenkk** [comment]
You indeed need a newer CC253X firmware to use this device.
