### ISSUE TITLE
Moes/BAC BHT-001GCLZB 0.5 degree increments

### ISSUE THREAD

**Issue by nygma2004** [Koenkk/zigbee2mqtt#21864]
### What happened?

I have a BHT-001GCLZB which is recognized as a Moes [BHT-002-GCLZB](https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html#moes-bht-002-gclzb). The unit show setpoint and local temperature in 0.5 degree (centigrade) resolution. But the messages do not show fractionals. If I set the "current_heating_setpoint" to any 0.5 degree, the unit turns the setpoint to zero.

### What did you expect to happen?

Getting the temperature and setpoint values to 0.5 degree resolution

### How to reproduce it (minimal and precise)

Change the setpoint on the device and check the MQTT data

### Zigbee2MQTT version

 1.35.1 commit: 4b6f50da

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee USB Dongle: zStack3x0

### Setup

x85-64, zigbee2mqtt install not conteainerized

**Comment by robvanoostenrijk** [comment]
@nygma2004,

Sadly this is simply not supported. The Tuya datapoint messages from the device indicate this as well:

    // DP16: current_heating_setpoint (°C)
    {"dpValues":[{"data":{"data":[0,0,0,22],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1} // 22
    {"dpValues":[{"data":{"data":[0,0,0,23],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1} // 23
    {"dpValues":[{"data":{"data":[0,0,0,23],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1} // 23.5
    {"dpValues":[{"data":{"data":[0,0,0,26],"type":"Buffer"},"datatype":2,"dp":16}],"seq":1} // 26

You can see that `23` and `23.5` are both the same value when received via Zigbee from the device unit itself.
This is a limitation of the device itself and we cannot work around it.
