### ISSUE TITLE
Issue with binding between Moes MS-105BZ and styrbar ikea

### ISSUE THREAD

**Issue by mitch55500** [Koenkk/zigbee2mqtt#21915]
### What happened?

I can't bind  Moes MS-105BZ with styrbar ikea.

I think it's because the switch Moes hasn't clusterOnOff. 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/31507239/1662a18b-bad1-4363-8d14-038fe9671ffa)

I'd like to control the MOES switch with the Styrbar.
Is there a solution?

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20211217

### Adapter

CC2652R stick

### Setup

Add-on Home Assistant in a VM

**Comment by mrskycriper** [comment]
No On/Off cluster means no binding. Sometimes Tuya devices are too proprietary. The only possible fix is writing a custom firmware for the switch with proper Zigbee implementation.

**Comment by mitch55500** [comment]
Who can write this?

Can I do it?

**Comment by mrskycriper** [comment]
> Can I do it?

Probably not, otherwise you would have probably already done it ;)

Writing Zigbee firmware is not an easy thing to do :(

**Comment by mitch55500** [comment]
An other question : how to know which dimmer switch has On/Off cluster?

**Comment by mrskycriper** [comment]
> Thanks
> 
> 
> 
> An other question : how to know which dimmer switch has On/Off cluster?

If you don't have in on hand, then only by asking/searching. 

If you have it, then simply open clusters for this device tab in web interface and look for `genOnOff` in Output clusters sections.

**Comment by mitch55500** [comment]
I see.

I'm just looking. I can't find much.

**Comment by mitch55500** [comment]
I would like, using a Styrbar remote control from Ikea, to be able to operate the switch to be able to turn the light on or off or vary the light intensity of my lamp.

Input cluster? I have never seen this cluster on my devices.

I am not an expert, I search on [this page.](https://www.zigbee2mqtt.io/supported-devices/). Where can I see their Zigbee converters?
