### ISSUE TITLE
another WHD02 with manufacturerName _TZ3000_kycczpw8

### ISSUE THREAD

**Issue by sprut2** [Koenkk/zigbee2mqtt#21926]
### Link

https://de.aliexpress.com/item/1005005548042286.html

### Database entry

{"id":39,"type":"Router","ieeeAddr":"0xa4c138370453d04d","nwkAddr":27682,"manufId":4417,"manufName":"_TZ3000_kycczpw8","powerSource":"Mains (single phase)","modelId":"TS0001","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genOnOff":{"attributes":{"onOff":1}},"genBasic":{"attributes":{"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3000_kycczpw8","zclVersion":3,"appVersion":70,"modelId":"TS0001","powerSource":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002a2ebd58","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":153093895},"lastSeen":1711208872739}

### Comments

The Tuya-switch **WHD02** comes with many different manufacturerName-s but always with the modelID TS0001. The one I ordered is labeled iHSW02 and is identical to the other WHD02 switches:
"manufacturerName":"_TZ3000_kycczpw8",
"modelId":"TS0001"

Because its manufacturerName is missing in the zigbee-herdsman-converters it is miss-dentified as TS0001 instead of **WHD02**.
Please just add it in /src/devices/tuya.ts to the other manufacturerName-s of the WHD02.

I managed to use this device by replacing one entry in the WHD02 manufacturerName-list in my tuya.js with _TZ3000_kycczpw8, and can prove, that it works. I get correct available, link_quality, power_on_behavior, state, and switch_type. All this is working correctly with default WHD02-settings.

The switch is not reporting current, energy, load-power and voltage, its hardware is probably not supporting any measurements (could not find any measure-chip on the PCB). 

### External definition

```shell
not needed
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
