### ISSUE TITLE
LAN coordinator "connection lost", retry connection instead of crash [Feature request]: 

### ISSUE THREAD

**Issue by KHV8** [Koenkk/zigbee2mqtt#21921]
### Is your feature request related to a problem? Please describe

Current version of Z2M will crash if connection to the coordinator is lost. With a growing number of LAN based coordinators this behavior is not optimal. There might be a number of good reasons for the LAN network to be down for short periods, like switch updates or alike. Also manual errors by disconnecting wrong devices etc.

If using Home Assistant add-on, the watchdog feature should solve this by restarting Z2M. This works, however will only retry 10 times and then stop. This only takes app 30 seconds, hence the LAN network might not be ready yet.

### Describe the solution you'd like

Let Z2M continue to run, even with a lost connection to the coordinator. Set all devices in "offline" status and retry accessing the coordinator once every minute, forever.

### Describe alternatives you've considered

Using a Home Assistant automation to look for the Zigbee2mqtt add-on status and restart the add-on if down for 5 min.

### Additional context

.

**Comment by Wheemer** [comment]
This is a great suggestion and needs to happen. The fact that zigbee2mqtt crashes instead of just retrying the connection until it returns, seems like the wrong behaviour.
