### ISSUE TITLE
NWK_TABLE_FULL - way to flush that table?

### ISSUE THREAD

**Issue by olgru** [Koenkk/zigbee2mqtt#21920]
### What happened?

I got NWK_TABLE_FULL causing instable network. I'm running z2m with ha on latest stable releases. TheZigbee coordinator is UZG-01. Several reboots, even rollback to previous versions from proxmox backup didn't solve anything.
I just want to know, if there is any potential way to completely flush that NWK_TABLE_FULL and simply start from scratch with the whole network. I've 105 devices and expected to run around 200-300 devices without issues based on the UZG-01 specs. 

### What did you expect to happen?

A stable network...

### How to reproduce it (minimal and precise)

No idea, sorry.

### Zigbee2MQTT version

1.36.0 commit: unknown

### Adapter firmware version

20230507

### Adapter

CC2652P7 - UZG-01

### Setup

HAS on Proxmox; UZG via Network on same switch and segment

**Comment by Koenkk** [comment]
This should be fixed with the [new fw](https://github.com/Koenkk/Z-Stack-firmware/discussions/496), the P7 version will be available soon.
