### ISSUE TITLE
Status of bulb not correct after reset 

### ISSUE THREAD

**Issue by Tekno-man** [Koenkk/zigbee2mqtt#2193]
# Bug Report
## What happened
When HA restarts the status of both Hue bulbs is always off regardless of state and the true state is not reported until I cycle the light at power point or cycle the state in HA. Oddly enough the same thing happens when I restart the Z2M hassio addon but the bulbs default to on. 

## What did you expect to happen
On restart of the HA the bulbs true status should be displayed eventually. 

## Debug Info
zigbee2mqtt version: 1.6
CC253X firmware version: not sure how to check version?

**Comment by lolorc** [comment]
you might want to use ```retain: true``` for your bulbs
