### ISSUE TITLE
Remote control with 3 groups send only one MQTT Message

### ISSUE THREAD

**Issue by BAPMU** [Koenkk/zigbee2mqtt#21952]
### What happened?

The control have 3 group buttons. When I select one group to switch on/off  for example everythink works fine. When I select two groups the remote send 2 Zigbee messages but I get only one MQTT message

### What did you expect to happen?

to get or every Zigbee Message one MQTT message

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

20210708

### Adapter

Sunricher ZG2858A

### Setup

Home Assistant core 2024.3.3, OS 12.1

### Debug log

/* on/off with group 1

debug	2024-03-25 22:59:06Received Zigbee message from 'Fernbedienung Haus', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 43009

info 	2024-03-25 22:59:06MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"on_ep1","action_group":43009,"battery":100,"linkquality":45}'

info 	2024-03-25 22:59:06MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"","battery":100,"linkquality":45}'

info 	2024-03-25 22:59:06MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus/action', payload 'on_ep1'

/* on/off group 2

debug 	2024-03-25 22:59:12Received Zigbee message from 'Fernbedienung Haus', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 2 with groupID 43010

info 	2024-03-25 22:59:12MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"off_ep2","action_group":43010,"battery":100,"linkquality":51}'

info 	2024-03-25 22:59:12MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"","battery":100,"linkquality":51}'

info 	2024-03-25 22:59:12MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus/action', payload 'off_ep2'

/* on/off group 1 and 2

debug 	2024-03-25 22:59:18Received Zigbee message from 'Fernbedienung Haus', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 43009

debug 	2024-03-25 22:59:18Received Zigbee message from 'Fernbedienung Haus', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 2 with groupID 43010

info 	2024-03-25 22:59:18MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"on_ep1","action_group":43009,"battery":100,"linkquality":45}'

info 	2024-03-25 22:59:18MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus', payload '{"action":"","battery":100,"linkquality":45}'

info 	2024-03-25 22:59:18MQTT publish: topic 'zigbee2mqtt/Fernbedienung Haus/action', payload 'on_ep1'

**Comment by MrAyianaLex** [comment]
Hello,
the problem is still there. How can I find out if groups 1, 2 or 3 are activated?
