### ISSUE TITLE
Memory Leak (1.36.0)

### ISSUE THREAD

**Issue by Outsidewall** [Koenkk/zigbee2mqtt#21950]
### What happened?

Over a few hours approx 12 in this case, memory usage goes from 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/2562086/fff57de0-7558-48e5-9eeb-70f5e5e746a6)
to
![image](https://github.com/Koenkk/zigbee2mqtt/assets/2562086/331aa7f3-04ba-47c1-8117-4592434a475f)

No error messages in logs

zigbee2mqtt will not operate any smart switches, if you attempt to turn them on, they do not, again no error message.

A restart of the container, aka docker compose down;docker compose up -d
will allow operation again.

### What did you expect to happen?

No memory leak, and continued operation of the ability to turn smart sockets on/off

### How to reproduce it (minimal and precise)

Run in docker container.

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Dongle-E (EXSP v8) 6.10.3.0 build 297

### Setup

Linux Rocky 8 - docker 

### Debug log

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2562086/2b419145-116e-4fa0-a387-16c87bbd91a6)

**Comment by Koenkk** [comment]
I suggest to try out the new [ember adapter](https://github.com/Koenkk/zigbee2mqtt/discussions/21462)

**Comment by Outsidewall** [comment]
Thank you, I have had a read on that ember thread, and left a message.

**Comment by Outsidewall** [comment]
Update, Have updated dongle-e to 7.4.2, and the zigbee2mqtt memory leak has gone.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2562086/d797ec6a-d503-49dc-9e9b-b92a587d0920)

this is what it looked before

![image](https://github.com/Koenkk/zigbee2mqtt/assets/2562086/7e8b7acf-a4df-4327-ac9e-66b98e023357)

**Comment by theorlangur** [comment]
@Outsidewall , I seem to have a similar memory/stability issue with my dongle-e on 7.3 firmware with ezsp driver
How are your impressions after running 7.4 with ember since updating? Is the network stable, any glitches? Did you have to re-pair devices? How big is your network if you don't mind me asking)

**Comment by Outsidewall** [comment]
Hello, I updated to 7.4.2 and use the ember driver setting, no repairing needed. Also loaded the latest version of z2m. All working well, no memory leak, and so far reliable. Network is about 130 devices.
