### ISSUE TITLE
[New device support]: TS0601 similar to QT06_2

### ISSUE THREAD

**Issue by TacoRocket** [Koenkk/zigbee2mqtt#21954]
### Link

https://www.aliexpress.us/item/3256806361013395.html?spm=a2g0o.productlist.main.29.b37e4659R3PThC&algo_pvid=0bef9b2c-a47a-4f56-a172-7e267004aea7&aem_p4p_detail=202403260843561844925180503760000335109&algo_exp_id=0bef9b2c-a47a-4f56-a172-7e267004aea7-14&pdp_npi=4%40dis%21USD%2126.95%2123.40%21%21%21194.34%21168.78%21%402103010c17114678361356905e8074%2112000037932268336%21sea%21US%210%21AB&curPageLogUid=OgmYiXM9modX&utparam-url=scene%3Asearch%7Cquery_from%3A&search_p4p_id=202403260843561844925180503760000335109_4

### Database entry

Don't know how to open it

### Comments

This seems to be an updated version as described by the vendor. It would be great to have support for this!

If you can help show how to open database.db to get database I'm happy to do so.

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_7ytb3h8u',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`_TZE204_7ytb3h8u` will be supported in the 1 April release.
