### ISSUE TITLE
New Thermostat valve

### ISSUE THREAD

**Issue by Maurizion** [Koenkk/zigbee2mqtt#21961]
### Link

https://www.amazon.it/stores/Kblue/page/7955564D-378E-4D75-8FD5-E7A6C61C9621?ref_=ast_bln

### Database entry

not sure how to get it 

### Comments

Add **Kblue** line on file /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/tuya.js    :    
- - - - - - - - - - 
zigbeeModel: ['kud7u2l'],
        fingerprint: [
            { modelID: 'TS0601', manufacturerName: '_TZE200_ckud7u2l' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_ywdxldoj' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_do5qy8zo' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_cwnjrr72' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_pvvbommb' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_9sfg7gm0' }, // HomeCloud
            { modelID: 'TS0601', manufacturerName: '_TZE200_2atgpdho' }, // HY367
            { modelID: 'TS0601', manufacturerName: '_TZE200_cpmgn2cf' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_znlqjmih' },
            { modelID: 'TS0601', manufacturerName: '_TZE200_8thwkzxl' }, // Tervix eva2
            { modelID: 'TS0601', manufacturerName: '_TZE200_4eeyebrt' }, // Immax 07732B
            { modelID: 'TS0601', manufacturerName: '_TZE200_8whxpsiw' }, // EVOLVEO
            { modelID: 'TS0601', manufacturerName: '_TZE200_xby0s3ta' }, // Sandy Beach HY367
            { modelID: 'TS0601', manufacturerName: '_TZE200_7fqkphoq' }, // AFINTEK
            { modelID: 'TS0601', manufacturerName: '_TZE200_rufdtfyv' },
            **{ modelID: 'TS0601', manufacturerName: '_TZE200_lpwgshtl' }, // Kblue <<<<<<<------- add this line !**
        ],
        model: 'TS0601_thermostat',
- - - - - -- - - - - -

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE200_lpwgshtl',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
