### ISSUE TITLE
[New device support]: _TYST11_esvato7m (a TuYa Based Motion Sensor)

### ISSUE THREAD

**Issue by ohuc** [Koenkk/zigbee2mqtt#21977]
### Link

https://www.tatacliq.com/smartiqo-zigbee-pir-motion-sensor-white/p-mp000000012681210

### Database entry

{"id":4,"type":"EndDevice","ieeeAddr":"0xec1bbdfffec282f7","nwkAddr":5722,"manufId":0,"manufName":"_TYST11_esvato7m","powerSource":"Battery","modelId":"svato7m\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,3],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"svato7m\u0000","manufacturerName":"_TYST11_esvato7m","powerSource":3,"zclVersion":3,"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"20180727"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"20180727","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1711565756043}

### Comments

I tried adding it as a new device but could not, in the logs this is what i get when i triggeer the motion sensor:
"Zigbee2MQTT:debug 2024-03-28 16:54:32: No converter available for 'svato7m' with cluster 'manuSpecificTuya' and type 'commandDataResponse' and data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":1}],"seq":2816}'
Zigbee2MQTT:debug 2024-03-28 16:55:09: Saving state to file /config/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2024-03-28 16:55:36: Received Zigbee message from '0xec1bbdfffec282f7', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":3}],"seq":2816}' from endpoint 1 "

### External definition

```shell
const {identify} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['svato7m']
    model: 'svato7m'
    vendor: '_TYST11_esvato7m',
    description: 'Automatically generated definition',
    extend: [identify()],
    meta: {},
};

module.exports = definition;
```

**Comment by luiscamaral** [comment]
My Issue was closed pointing to this one. I could make my sensor work with the following after figuring out how to configure it:

 1. Device Signature

```json
  {
      "ieeeAddr": "0xbc33acfffe661633",
      "manufacturerName": "_TYST11_esvato7m",
      "modelId": "svato7m\u0000",
      "powerSource": "Battery",
      "endpoints": {
          "1": {
              "profId": 260,
              "epId": 1,
              "devId": 0,
              "inClusterList": [0, 3],
              "outClusterList": [3, 25],
              "clusters": {
                  "genBasic": {
                      "attributes": {
                          "modelId": "svato7m\u0000",
                          "manufacturerName": "_TYST11_esvato7m",
                          "powerSource": 3,
                          "zclVersion": 3,
                          "appVersion": 73,
                          "stackVersion": 0,
                          "hwVersion": 1,
                          "dateCode": "20180727"
                      }
                  }
              }
          }
      }
  }
```

  2. Working External Converter

```js
  const exposes = require('zigbee-herdsman-converters/lib/exposes');
  const tuya = require('zigbee-herdsman-converters/lib/tuya');

  const e = exposes.presets;

  const definition = {
      fingerprint: tuya.fingerprint('svato7m\u0000', ['_TYST11_esvato7m']),
      model: 'svato7m',
      vendor: 'Tuya',
      description: 'Presence detector ball sensor',
      extend: [tuya.modernExtend.tuyaBase({dp: true})],
      fromZigbee: [tuya.fz.datapoints],
      toZigbee: [tuya.tz.datapoints],
      exposes: [
          e.occupancy(),
      ],
      meta: {
          tuyaDatapoints: [
              [1, 'occupancy', tuya.valueConverter.trueFalse1],
              [3, 'occupancy', tuya.valueConverter.trueFalse1],
          ],
      },
  };

  module.exports = definition;
```

  3. Datapoints Observed

```text
  | DP  | Value     | Meaning                |
  |-----|-----------|------------------------|
  | 1   | [0] / [1] | Occupancy (false/true) |
  | 3   | [1] / [0] | Occupancy (true/false) |
```

  Both DPs report presence changes - mapped to occupancy binary sensor.

  4. Configuration

  File: `external_converters/svato7m.js`

  `configuration.yaml`:
```yaml
  external_converters:
    - svato7m.js
```

I only find data for presence detection and not battery. Could not identify OTA features neither. If anyone find out please share here.

```text
  | Feature                | Status                    |
  |------------------------|---------------------------|
  | Occupancy (DP 1, DP 3) | ✅ Working                |
  | Battery level          | ❌ Not reported by device |
  | OTA updates            | ❌ Not available          |
```
