### ISSUE TITLE
[New device support]: Tuya touch dimmer switch with glass TS0601 _TZE204_vevc4c6g

### ISSUE THREAD

**Issue by mrespin** [Koenkk/zigbee2mqtt#21980]
### Link

https://www.rtx24.pl/sciemniacz-dotykowy-1obw-bi-zigbee-tuya-rtx-sh-p-766.html

### Database entry

{"id":38,"type":"Router","ieeeAddr":"0xa4c138c36e85ec26","nwkAddr":44551,"manufId":4417,"manufName":"_TZE204_vevc4c6g","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"$��-f%��-\u00127��-f8��-\u0012C��-fD��-\u0012","65506":56,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_vevc4c6g","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1711024459064}

### Comments

Tuya touch dimmer TS0601 _TZE204_vevc4c6g glass up/down dimmer.

Similar supported devices with touch glass and 3 icons:
TS0601 _TZE200_3p5ydos3 glass +/- dimmer - very similar - supported
TS130F _TZ3000_wptayaqr glass blinds up/down - supported
TS130F _TZ3000_vsj5o7dm glass blinds up/down - supported

### External definition

```shell
const {deviceEndpoints, ota} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_vevc4c6g',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"242":242}}), ota()],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by mrespin** [comment]
External definition, where dimmer is working fine:
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
//const extend = require('zigbee-herdsman-converters/lib/extend'); // with new Z2M not working
const {} = require('zigbee-herdsman-converters/lib/modernExtend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const legacy = require('zigbee-herdsman-converters/lib/legacy')

const definition = {
    fingerprint: [
        {modelID: 'TS0601', manufacturerName: '_TZE204_vevc4c6g'},        
    ],
    model: 'TS0601_dimmer_Jac',
    vendor: 'TuYa',
    description: '1 gang smart dimmer',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    configure: tuya.configureMagicPacket,
    exposes: [tuya.exposes.lightBrightnessWithMinMax(), tuya.exposes.countdown(), tuya.exposes.lightType(),
        e.power_on_behavior().withAccess(ea.STATE_SET),
        tuya.exposes.backlightModeOffNormalInverted().withAccess(ea.STATE_SET)],
    meta: {
        tuyaDatapoints: [
            [1, 'state', tuya.valueConverter.onOff, {skip: tuya.skip.stateOnAndBrightnessPresent}],
            [2, 'brightness', tuya.valueConverter.scale0_254to0_1000],
            [3, 'min_brightness', tuya.valueConverter.scale0_254to0_1000],
            [4, 'light_type', tuya.valueConverter.lightType],
            [5, 'max_brightness', tuya.valueConverter.scale0_254to0_1000],
            [6, 'countdown', tuya.valueConverter.countdown],
            [14, 'power_on_behavior', tuya.valueConverter.powerOnBehavior],
            [21, 'backlight_mode', tuya.valueConverter.backlightModeOffNormalInverted],
        ],
    },
    whiteLabel: [
        {vendor: 'Larkkey', model: 'ZSTY-SM-1DMZG-EU'},
        {vendor: 'Earda', model: 'EDM-1ZAA-EU'},
        {vendor: 'Earda', model: 'EDM-1ZAB-EU'},
        {vendor: 'Earda', model: 'EDM-1ZBA-EU'},
        {vendor: 'Mercator Ikuü', model: 'SSWD01'},
        {vendor: 'Moes', model: 'ZS-USD'},
        {vendor: 'Moes', model: 'EDM-1ZBB-EU'},
        tuya.whitelabel('Mercator Ikuü', 'SSWM-DIMZ', 'Switch Mechanism', ['_TZE200_9cxuhakf']),
        tuya.whitelabel('Mercator Ikuü', 'SSWRM-ZB', 'Rotary dimmer mechanism', ['_TZE200_a0syesf5']),
    ],
};

module.exports = definition;

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by kasta002** [comment]
I have this light switch, it paired with a kidnapping, unfortunately not. It changes the status on the home assistance application if someone turns on the physical switch. It is possible for the option to be added to the official Updates. We are not in the business of adding anything ourselves, we only make updates.
