### ISSUE TITLE
Gledopto GL-C-006P color temperature controls brightness after firmware update

### ISSUE THREAD

**Issue by Swampen** [Koenkk/zigbee2mqtt#21988]
### What happened?

Got the new firmware update available over OTA with z2m and updated it (Version: 10276802, Date: 20210719). 
After the update the controller have been acting up and it now controls the brightness when I try to change the color temperature.
Normal brightness control works fine.
I had no issues before the firmware update so perhaps an issue with the firmware?

### What did you expect to happen?

Adjusting the color temperature should should control the led temperature and not the brightness

### How to reproduce it (minimal and precise)

1. Update to latest available firmware (Version: 10276802, Date: 20210719)
2. Control temperature
    1. Lowering the color_temp increases brightness
    2. Increasing the color_temp decreases the brightness

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-P

### Setup

Add-on on Home Assistant Yellow

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14795120/log.txt)
[herdsman_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14795121/herdsman_log.txt)

**Comment by Loic691** [comment]
Can you explain ?

**Comment by Loic691** [comment]
I will try this week with an other device which had been updated

**Comment by lux73** [comment]
try to re-pair the Device as complete new Device - some of my Danfoss TRV has some weird behaviour after OTA, after new re-pairing all is good

**Comment by Swampen** [comment]
> try to re-pair the Device as complete new Device - some of my Danfoss TRV has some weird behaviour after OTA, after new re-pairing all is good

Tried that now without any luck. Same behavior.

**Comment by Loic691** [comment]
I had test this morning the device wich be updated with the last firmware.
The cool circuit didn't work.
The warm one yes.
So I think it's normal for you to think controling temperature color adjust the brightness.
This because colours between cool and warm are just a sum af brigjtness.

So i asked to the manufacturer a new firmware. M

**Comment by Swampen** [comment]
@Loic691 I messaged Gledopto last week and got a new firmware this morning. I will try it later today.

**Comment by Loic691** [comment]
I messaged too. They advise to not provide firmware on OTA because they said me same device référence can have several hardware version...

**Comment by Loic691** [comment]
I suggest to wait your test and send me the firmware. I will test on my device

**Comment by Loic691** [comment]
I think the gledopto are not manage correctly. They should have one firmware for ine reference product. The firmware should manage different hardware version

**Comment by Loic691** [comment]
So if this exactly ,i will remove the firmware on ota

**Comment by Swampen** [comment]
> I suggest to wait your test and send me the firmware. I will test on my device

Sure. I attached the one I got. 
My device have Q.C. sticker date marked as 01/2021
[GL-C-006P_10476801_2020401.zip](https://github.com/Koenkk/zigbee2mqtt/files/14822780/GL-C-006P_10476801_2020401.zip)

**Comment by Loic691** [comment]
Thanks. Let me know about your test

**Comment by Swampen** [comment]
> Thanks. Let me know about your test

Just finished the OTA installation from [my fork](https://github.com/Swampen/zigbee-OTA/tree/gl-c-006p-firmware) and the behavior is back to normal again

**Comment by Loic691** [comment]
Great. I will try yours firmware.

**Comment by Swampen** [comment]
@Loic691 Did you manage to test the new firmware?

**Comment by Loic691** [comment]
Not enough time...
I started to gen json update file.
I hope this friday

**Comment by Loic691** [comment]
Hi @Swampen 
I just tried your firmware and it is working now for one of my device.
I will push it on a PR !
And try to update other device with real OTA (not locally)

**Comment by Swampen** [comment]
@Loic691 I only tested this with OTA from my [fork](https://github.com/Swampen/zigbee-OTA/tree/gl-c-006p-firmware), so I can just create a PR from that 🙂

**Comment by PskNorz** [comment]
Hey, yestarday i got a notification for update to 10476801, i did the update but now my controller is broken. I dont have warm colour, only natural and when i try to controll the colour temperature its controlling the brightness. Is there any way to roll back?

**Comment by Swampen** [comment]
@PskNorz Did it work fine with the previous update I had issue with? Do you have "QC" sticker on the back off your device? Perhaps it is a different hardware revision?

@Loic691 Do your original device work with the new firmware?

**Comment by PskNorz** [comment]
@Swampen Hey, it was first time that i used it, didnt make any update yestarday was the 1st and yes it was working fine. QC sticker is on the back yes.

**Comment by Swampen** [comment]
@PskNorz What is the date of the year and month on the sticker? Mine has 01/2021

**Comment by PskNorz** [comment]
> @PskNorz What is the date of the year and month on the sticker? Mine has 01/2021

![942DD452-840A-4147-84FF-DACBA59AC0B5](https://github.com/Koenkk/zigbee2mqtt/assets/80605468/be311be7-6adb-4aa1-a2ae-181a92d3e3de)

**Comment by polsup2** [comment]
The same issue for GL-C-006P. Got 3 down. Will re-pair them today, but expecting the same trouble. Looks like the OTA should be removed from PR.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/81100144/327172b8-32c9-4bc4-b5d5-eada62b9b063)

**Comment by Swampen** [comment]
@polsup2 Are the devices offline or is the color temperature the only issue? What is the year/month on your Q.C. stickers?

**Comment by polsup2** [comment]
> @polsup2 Are the devices offline or is the color temperature the only issue? What is the year/month on your Q.C. stickers?

Device became offline. I didn't re-pair them yet. They are installed in electric box , so I need to disassemble something to get the photos of production date. Will provide photos little bit later.

**Comment by polsup2** [comment]
> Will re-pair them today, but expecting the same tro

My expectations were wrong. After physical disconnection of power wire on controllers and re-pairing to network, everything works well: Brightness/wwcw.

I think it would be better to warn people that  OTA installation causes need to physically access the controller. In some cases,  this action is not easy.

Attaching the photo with production date.

![20240408_202337](https://github.com/Koenkk/zigbee2mqtt/assets/81100144/83f395e1-0f4b-4ac2-8306-4bcdfe5185f9)

**Comment by PskNorz** [comment]
After a alot of repairs, nothing changes for me.

**Comment by PskNorz** [comment]
@Swampen It is possible to reinstall the zip file that you have [here?](https://github.com/Koenkk/zigbee2mqtt/issues/21988#issuecomment-2029590352)

And if yes, can you explain me how?

**Comment by Swampen** [comment]
@Loic691 Did you try to update the device you had tested [here](https://github.com/Koenkk/zigbee-OTA/issues/461#issuecomment-2016828926) to the latest firmware?

I have sent a new email to Gledopto with this new information to see if there is any changes in hardware revision between these QC stickers. Hopefully there is a way to distinguish them.

@monoimoi and @PskNorz If you want to downgrade the firmware, you can do the following:
1. Add a local `index.json` file to your z2m config https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files
2. Add the following to your local `index.json`
```json
[
    {
        "fileSize": 281342,
        "manufacturerCode": 4687,
        "imageType": 0,
        "sha512": "ef83e88563221eeac951f7f6d1769891b7eb9f4df44b0acd2cdd5e473cdd9f2772fd4ec4540b5f852d93fcc14637b28567a2869fb6ea3809fcf76ea5a230572b",
        "modelId": "GL-C-006P",
        "url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Gledopto/GL-C-006P_V102.ota",
        "path": "images/Gledopto/GL-C-006P_V102.ota",
        "force": true
    }
]
```
3. Update the device

**Comment by nick-dijkshoorn** [comment]
After upgrading to the newest firmware, color temperature was also broken.
I fixed the issue by downgrading the firmware with a local OTA index.
`[
     {
         "fileVersion": 10,
         "fileSize": 281342,
         "manufacturerCode": 4687,
         "imageType": 0,
         "sha512": "ef83e88563221eeac951f7f6d1769891b7eb9f4df44b0acd2cdd5e473cdd9f2772fd4ec4540b5f852d93fcc14637b28567a2869fb6ea3809fcf76ea5a230572b",
         "modelId": "GL-C-006P",
         "url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Gledopto/GL-C-006P_V102.ota",
         "path": "images/Gledopto/GL-C-006P_V102.ota",
	 "force": true
     }
]`

**Comment by nyok92** [comment]
```
{
    "color_mode": "color_temp",
    "linkquality": 109,
    "state": "ON",
    "update": {
        "installed_version": 10,
        "latest_version": 12,
        "state": "available"
    },
    "update_available": null,
    "brightness": 125,
    "color_temp": 370
}
```
QC passed 21/22
FW ; 10276802
FW date : 20210719

OTA update is not working.
Z2MQTT logs :

```
Info 2024-04-12 11:09:43Updating '0xcc86ecfffe187e3e' to latest firmware
Info 2024-04-12 11:09:47Update of '0xcc86ecfffe187e3e' at 0.00%
Info 2024-04-12 11:09:47MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe187e3e', payload '{"color_mode":"color_temp","color_temp":370,"linkquality":109,"state":"ON","update":{"installed_version":10,"latest_version":12,"progress":0,"state":"updating"},"update_available":null}'
Info 2024-04-12 11:12:17MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe187e3e', payload '{"color_mode":"color_temp","color_temp":370,"linkquality":109,"state":"ON","update":{"installed_version":10,"latest_version":12,"state":"available"},"update_available":null}'
Info 2024-04-12 11:12:17MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"0xcc86ecfffe187e3e"},"error":"Update of '0xcc86ecfffe187e3e' failed (OTA: Timeout, device did not request any image blocks)","status":"error","transaction":"2mfdd-1"}'
Error 2024-04-12 11:12:17Update of '0xcc86ecfffe187e3e' failed (OTA: Timeout, device did not request any image blocks)Info 2024-04-12 11:09:43Updating '0xcc86ecfffe187e3e' to latest firmware
Info 2024-04-12 11:09:47Update of '0xcc86ecfffe187e3e' at 0.00%
Info 2024-04-12 11:09:47MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe187e3e', payload '{"color_mode":"color_temp","color_temp":370,"linkquality":109,"state":"ON","update":{"installed_version":10,"latest_version":12,"progress":0,"state":"updating"},"update_available":null}'
Info 2024-04-12 11:12:17MQTT publish: topic 'zigbee2mqtt/0xcc86ecfffe187e3e', payload '{"color_mode":"color_temp","color_temp":370,"linkquality":109,"state":"ON","update":{"installed_version":10,"latest_version":12,"state":"available"},"update_available":null}'
Info 2024-04-12 11:12:17MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"0xcc86ecfffe187e3e"},"error":"Update of '0xcc86ecfffe187e3e' failed (OTA: Timeout, device did not request any image blocks)","status":"error","transaction":"2mfdd-1"}'
Error 2024-04-12 11:12:17Update of '0xcc86ecfffe187e3e' failed (OTA: Timeout, device did not request any image blocks)
```

Then I can't control the device nymore:

`2024-04-12 11:14:54Failed to read state of '0xcc86ecfffe187e3e' after reconnect (ZCL command 0xcc86ecfffe187e3e/11 genLevelCtrl.read(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 51571 - 11 - 30 - 8 - 1 after 10000ms))`

Solved with re-pairing the device, but OTA update didn't worked.

**Comment by Loic691** [comment]
> @Loic691 Did you try to update the device you had tested [here](https://github.com/Koenkk/zigbee-OTA/issues/461#issuecomment-2016828926) to the latest firmware?

Yes localy and it's OK.
I have another device en V1.0.1 which I can't update.
The update fails with this error `failed (OTA: Timeout, device did not request any image blocks)`
And the device hangs. I have to reboot it and repair again in Z2M.

I think GLEDOPTO have different hardware version with different firmware and there is no issues to check which hardware version we have. I had discussion with GLEDOPTO and they advise to not process update if the device works correctly.

They are easily reachable by email.

**Comment by Loic691** [comment]
> Scratch that. I was looking at the wrong device.. I also have hwVersion 2..

Where we can find hardware version  ?

**Comment by Loic691** [comment]
Sorry I found  !
For information, the device I updated locallty is hwVersion 2

The other one I can't update have no hardware version in interview...

**Comment by nyok92** [comment]
Mine is hardware version 2 : 

Read result of 'genBasic': {"hwVersion":2,"appVersion":0,"zclVersion":3,"stackVersion":0,"modelId":"GL-C-006P","appProfileVersion":255,"swBuildId":"10276802","manufacturerName":"GLEDOPTO"}

**Comment by PskNorz** [comment]
> > Scratch that. I was looking at the wrong device.. I also have hwVersion 2..
> 
> Where we can find hardware version ?

Can you tell me how?

**Comment by Loic691** [comment]
In database.db file of Z2M config directory

**Comment by Loic691** [comment]
> Mine is hardware version 2 :
> 
> Read result of 'genBasic': {"hwVersion":2,"appVersion":0,"zclVersion":3,"stackVersion":0,"modelId":"GL-C-006P","appProfileVersion":255,"swBuildId":"10276802","manufacturerName":"GLEDOPTO"}

For mine which is OK for update firmware
`{"genBasic":{"attributes":{"modelId":"GL-C-006P","manufacturerName":"GLEDOPTO","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":2,"dateCode":"20240401","swBuildId":"10476801"}}`

For other one which update failed
`{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"dateCode":"","modelId":"GL-C-006P","zclVersion":3,"swBuildId":"V1.0.1"}}`

**Comment by PskNorz** [comment]
> database.db

I got only this.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/80605468/54b3005a-448e-41f6-9b1c-b8a6f2d040d9)

**Comment by monoimoi** [comment]
> @Loic691 Did you try to update the device you had tested [here](https://github.com/Koenkk/zigbee-OTA/issues/461#issuecomment-2016828926) to the latest firmware?
> 
> I have sent a new email to Gledopto with this new information to see if there is any changes in hardware revision between these QC stickers. Hopefully there is a way to distinguish them.
> 
> @monoimoi and @PskNorz If you want to downgrade the firmware, you can do the following:
> 1. Add a local `index.json` file to your z2m config https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files
> 2. Add the following to your local `index.json`
> ```json
> [
>     {
>         "fileSize": 281342,
>         "manufacturerCode": 4687,
>         "imageType": 0,
>         "sha512": "ef83e88563221eeac951f7f6d1769891b7eb9f4df44b0acd2cdd5e473cdd9f2772fd4ec4540b5f852d93fcc14637b28567a2869fb6ea3809fcf76ea5a230572b",
>         "modelId": "GL-C-006P",
>         "url": "https://github.com/Koenkk/zigbee-OTA/raw/master/images/Gledopto/GL-C-006P_V102.ota",
>         "path": "images/Gledopto/GL-C-006P_V102.ota",
>         "force": true
>     }
> ]
> ```
> 3. Update the device
> 

The update would fail repeatedly until I added "fileVersion": 10 on top of the json file (@nick-dijkshoorn 's example). I have now successfully reverted back to the older firmware and everything works as it used to.
Hardware version 2. Thanks everyone for your input.

**Comment by monoimoi** [comment]
> > database.db
> 
> I got only this.
> ![image](https://github.com/Koenkk/zigbee2mqtt/assets/80605468/54b3005a-448e-41f6-9b1c-b8a6f2d040d9)
> 
> 

You can also find hwVersion by using z2m web interface.
Go to devices tab then click the device you want to query.
Click "dev console" tab
Endpoint: "11" -> Cluster "genBasic" -> attributes "hwVersion" and then click read.

**Comment by PskNorz** [comment]
@monoimoi Thank you! I am a newbie and I am trying to learn how Z2M works.

So I think I have found the solution.

My hardware version is `Read result of 'genBasic': {"hwVersion":2} `
**Q.C Sticker 7/22**

I sent an email to Gledopto and I told them which Q.C Sticker I have, and they replied to me with an OTA Update file.

[GL-C-006P_10576802_20240412.zip](https://github.com/Koenkk/zigbee2mqtt/files/14961288/GL-C-006P_10576802_20240412.zip)

Because I am new to Z2M, I didn't know how to update it, so I switched back to Deconz because I knew how to do it. I updated the device and repaired it back to Z2M.

And it's done! Everything works as it should.

Thanks to everyone. I hope this helps others facing the same problem.

**Comment by fry42** [comment]
Hi!

My GL-C-006P is also broken after the update!
My Q/C Sticker says 10/22 so the GL-C-006P_10576802_20240412.zip should be the right one for me...

But: I can't get z2m to update/downgrade/force the firmware.
I just get a "Images currently unavailable for device 'GL-C-006P', hardwareVersion '2', manufacturerName GLEDOPTO, {"fieldControl":0,"manufacturerCode":4687,"imageType":5138,"fileVersion":604057601}'" message in the logs.

The solution suggested by @Loic691 / updated by @monoimoi does not work for me.
If I set the imageType to 5138 it "detects" an update but fails on imageType.

I don't have Deconz available (or a coordinator supported by dconz).

Any advice on how to fix this?

**Comment by Loic691** [comment]
I think it's better to remove OTA for this device....
There is several hardware version and we can't know how to manage them...
