### ISSUE TITLE
TO-Q-SY2-163JZT Problem Settings Protections

### ISSUE THREAD

**Issue by omarantelmi** [Koenkk/zigbee2mqtt#21999]
### What happened?

I recently purchased this device: TO-Q-SY2-163JZT
I can't set up the various protections.

### What did you expect to happen?

I expected the respective required values to be set.

### Zigbee2MQTT version

1.36.0 

### Adapter firmware version

 7.3.1.0 build 176

### Adapter

EZSP v12

### Setup

Addon on the Home Assistant operating system on Mini PC

### Debug log

![1](https://github.com/Koenkk/zigbee2mqtt/assets/97351449/59fc91ab-64e4-4a8d-9fa9-60a8a72ada14)
![2](https://github.com/Koenkk/zigbee2mqtt/assets/97351449/a3dc2aaa-96fe-4999-95a5-f4fe8e50dbab)
![3](https://github.com/Koenkk/zigbee2mqtt/assets/97351449/a35874b3-53ae-4ab2-a8b4-818dba420655)

**Comment by schwarzelise** [comment]
Hello i have exact the same device and configuration and the same PROBLEM!

**Comment by originalcom** [comment]
I have 3 of these. I have exactly the same problem. Dangerous to install as the device defaults to max amps i.e no overcurrent protection. Hopefully this can be fixed.

**Comment by jkl83** [comment]
> I have 3 of these. I have exactly the same problem. Dangerous to install as the device defaults to max amps i.e no overcurrent protection. Hopefully this can be fixed.

This device is supposed to be mounted WITH overcurrent circuit breaker. It says so in the manual.

**Comment by originalcom** [comment]
> > I have 3 of these. I have exactly the same problem. Dangerous to install as the device defaults to max amps i.e no overcurrent protection. Hopefully this can be fixed.
> 
> This device is supposed to be mounted WITH overcurrent circuit breaker. It says so in the manual.

No, this is definitely incorrect. The model I have does have current limiting: https://www.aliexpress.com/item/1005006139125562.html

The previous versions which I guess you are confusing these with were only adjustable on the Wifi models.

I did have further protection as it tripped the main 63A breaker. As a temporary measure until these are fully supported by Zigbee2mqtt I have these connected to a separate Tuya zigbee hub. The device settings in Tuya allow you to set a over current threshold and I can confirm it works as expected. I have tested this in multiple scenarios

Please, if it's possible delete your post as it may cause this issue not to be looked at / resolved.

**Comment by jkl83** [comment]
I have the same one.
Look at the manual inside the box.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/6525338/ab6eebd9-eda2-406a-99c2-8b37a1e1b35f)

https://elcb.net/product/zigbee-smart-circuit-breaker-over-current-under-voltage-protection-to-q-sy2-jzt/

https://elcb.net/wp-content/uploads/2024/02/SY1-SY2-Din-Rail-Smart-Switch-Operating-Manual.pdf

![image](https://github.com/Koenkk/zigbee2mqtt/assets/6525338/f42f8578-ccc2-4652-9a87-566e806db65b)

It's up to you. Matter of safety.

**Comment by originalcom** [comment]
> I have the same one. Look at the manual inside the box.
> 
> ![image](https://private-user-images.githubusercontent.com/6525338/321964079-ab6eebd9-eda2-406a-99c2-8b37a1e1b35f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIzMTUsIm5iZiI6MTcxMjkyMjAxNSwicGF0aCI6Ii82NTI1MzM4LzMyMTk2NDA3OS1hYjZlZWJkOS1lZGEyLTQwNmEtOTljMi04YjM3YTFlMWIzNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTE0MDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M0ZGMzMWZhNDZlNDc4MTRjYTYyY2EyOGZkNzQwMmUwMWUzOWY4YzlkZTYzZDg5NmIyMmMyNzk0N2E4ZjU2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bjkLiLThDxIVsHwNCVPxySsDjUCCaiUHr5MkyMbykzE)
> 
> https://elcb.net/product/zigbee-smart-circuit-breaker-over-current-under-voltage-protection-to-q-sy2-jzt/
> 
> https://elcb.net/wp-content/uploads/2024/02/SY1-SY2-Din-Rail-Smart-Switch-Operating-Manual.pdf
> 
> ![image](https://private-user-images.githubusercontent.com/6525338/321963201-f42f8578-ccc2-4652-9a87-566e806db65b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjIzMTUsIm5iZiI6MTcxMjkyMjAxNSwicGF0aCI6Ii82NTI1MzM4LzMyMTk2MzIwMS1mNDJmODU3OC1jY2MyLTQ2NTItOWE4Ny01NjZlODA2ZGI2NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTE0MDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRkNTM4ZjlmOWQ5ODIzYjAyM2E0MTBhZjUyMTgwZGI3ZTE4ZWZlNTZhZmNiZTY2NDhjYTdkOTZiNzZhMzQ3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dAX9znrvneCzryr6-mS_C-n34VZVDd_iLYDXs6UAdHI)
> 
> It's up to you. Matter of safety.

Yes correct hence the extra 63A breaker as described in my reply to you. They still have inbuilt current limiting enabling these to disconnect when the set current is exceeded. I think we should leave this discussion as it is I am only trying to get the full functionality of these supported by Zigbee2mqtt .

**Comment by originalcom** [comment]
> I had the same story. In my case the reason was incorrect passing of interview when connected through some router. Then I had selected permit to join to coordinator only and paired device again the interview passed successfully. I have the only problem couldn't set the overvoltage threshold more than 255V it seems some limit of converter.

I was hoping it was that simple but I've tried completely removing it from Zigbee2mqtt both normally and force remove then adding/interviewing it again. I've also tried it on my backup system with a clean Zigbee2mqtt install but still exactly the same problem.

**Comment by schwarzelise** [comment]
As seaman-git says
https://github.com/Koenkk/zigbee2mqtt/issues/21999#issuecomment-2053524181

Delete it and join it new to coordinaor ONLY, this worked perfect for me!
Thx Seaman-git

**Comment by omarantelmi** [comment]
Removing the device and reassociating it later solves the issue.

**Comment by originalcom** [comment]
> As seaman-git says [#21999 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/21999#issuecomment-2053524181)
> 
> Delete it and join it new to coordinaor ONLY, this worked perfect for me! Thx Seaman-git

Ok after doing this a few times this worked. Seems hit & miss but it does work eventually. Delete it and re add it and try changing the settings for amps etc. Repeat until it accepts the changes. I had to delete all 3 from my setup using force delete on the last one. Now all 3 added and working. Thank you

**Comment by iaxon** [comment]
> I had the same story. In my case the reason was incorrect passing of interview when connected through some router. Then I had selected permit to join to coordinator only and paired device again the interview passed successfully. I have the only problem couldn't set the overvoltage threshold more than 255V it seems some limit of converter.

I just opened [a pr](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7995) to fix the problem with the overvoltage treshold :)
