### ISSUE TITLE
[Wrong device]: Filament Bulb shown as LED Spot

### ISSUE THREAD

**Issue by nullzwei** [Koenkk/zigbee2mqtt#21990]
### Link

https://de.paulmann.com/p/filament-230v-smart-home-zigbee-3.0-led-kolben-st64-e27-600lm-7-5w-tunable-white-dimmbar-gold/29157

### Model

29157

### Description

Filament Bulb E27, 600 lumen, Dimmable, white spectrum

### Vendor

Paulmann

### Picture (link)

https://content.paulmann.com/media/14/6b/a7/1692646910/29157fr01.jpg

### Database entry

{"id":45,"type":"Router","ieeeAddr":"0xa4c13800ab391ba8","nwkAddr":24115,"manufId":4632,"manufName":"Paulmann Licht GmbH","powerSource":"Mains (single phase)","modelId":"CCT","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,4111],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":146,"swBuildId":"PCCT302","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1711658187336}

### Notes

Already tried to work around with external converter, but no success so far.  
Probably the ModelID is Used in both Models. Bulb working fine though, without any Problems. But would be nice to have it listed correct in die future.

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const extend = require('zigbee-herdsman-converters/lib/extend');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [
        {modelID: 'CCT', manufacturerName: 'Paulmann Licht GmbH', manufacturerID: 4632, endpoints: [
            {ID: 1, profileID: 260, inputClusters: [0, 3, 4, 5, 6, 8, 768, 4096, 4111],},
        ]}
    ],
    model: '29157',
    vendor: 'Paulmann',
    description: 'Filament Bulb E27, 600 lumen, dimmable, white spectrum',
    // Note that fromZigbee, toZigbee and exposes are missing here since we use extend here.
    // Extend contains a default set of fromZigbee/toZigbee converters and expose for common device types.
    // The following extends are available:
    // - extend.switch
    // - extend.light_onoff_brightness
    // - extend.light_onoff_brightness_colortemp
    // - extend.light_onoff_brightness_color
    // - extend.light_onoff_brightness_colortemp_color
   // extend: extend.light_onoff_brightness_colortemp_color(),
    
    extend: [light({colorTemp: {range: [153, 454]}})],
};

module.exports = definition;`

**Comment by Mar1usW3** [comment]
Same for https://de.paulmann.com/p/filament-230v-smart-home-zigbee-3.0-led-globe-g125-e27-600lm-7-5w-tunable-white-dimmbar-gold/29161 see https://github.com/Koenkk/zigbee2mqtt/issues/20090
