### ISSUE TITLE
[Feature request]: ZS-SR-EUC Backlight mode

### ISSUE THREAD

**Issue by seea2005** [Koenkk/zigbee2mqtt#22001]
### Is your feature request related to a problem? Please describe

Moes Star Ring series can adjust the mode of backlight, but in the cover device, it is not exposed like in the ZS-SR-EUD-2 is.

### Describe the solution you'd like

Can be backlight mode propertie shown in ZS-SR-EUC? Can it be added? Thanks

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by Alecto28** [comment]
Hello,
 I would also appreciate if the backlight mode option was available.

Regards.
