### ISSUE TITLE
[New device support]: Heiman PIR

### ISSUE THREAD

**Issue by aelsharawi** [Koenkk/zigbee2mqtt#22029]
### Link

https://www.alibaba.com/product-detail/Heiman-Ceiling-embedded-installation-tuya-zigbee_1600736227827.html

### Database entry

HS8OS-EF1-3.0

### Comments

HS8OS-EF1-3.0

I was able to make it work (basic functions) need help get the full potentials

here is the data sheet from the manfucutrer

[HS8OS-EF-.pdf](https://github.com/Koenkk/zigbee2mqtt/files/14829559/HS8OS-EF-.pdf)

### External definition

```shell
const {illuminance, occupancy, identify} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['HS8OS-EF1-3.0'],
    model: 'HS8OS-EF1-3.0',
    vendor: 'HEIMAN',
    description: 'Automatically generated definition',
    extend: [illuminance({"0x0400":["1"]}), occupancy({"0x0406":["1"]}), identify({"0x0003":["1"]})],
    meta: {},
};

module.exports = definition;
```

**Comment by aelsharawi** [comment]
any advise>?

**Comment by aelsharawi** [comment]
Where can I get this help?

**Comment by mrskycriper** [comment]
I'll look into this. Data-sheet is a gold mine of information.

**Comment by mrskycriper** [comment]
Also, can you please provide `database.db` entry for a good measure?

**Comment by aelsharawi** [comment]
how can I get the .db file please?

**Comment by aelsharawi** [comment]
thanks a lot for help ...is this enough?

**Comment by mrskycriper** [comment]
> thanks a lot for help ...is this enough?

It should be, thanks

**Comment by mrskycriper** [comment]
Sorry, I'm a bit overloaded lately and kinda just forgot

**Comment by aelsharawi** [comment]
Ok. No worries

**Comment by aelsharawi** [comment]
Hi again...just a gentle reminder

**Comment by mrskycriper** [comment]
> Hi again...just a gentle reminder

Hi, thanks for the reminder again. Is there any official model name and device name on the box? Heiman is not particularity good at documenting their devices. Also, can you confirm that it looks like this random picture I've found on aliexpress listing?

![HS8OS-EF1-3 0](https://github.com/Koenkk/zigbee2mqtt/assets/32013287/665ebca6-b019-4773-8747-0ea5c9ae2591)

**Comment by aelsharawi** [comment]
https://www.alibaba.com/product-detail/Heiman-Ceiling-embedded-installation-tuya-zigbee_1600736227827.html

yes it the correct picture above is the link where I bough it

thanks for the help
