### ISSUE TITLE
Support for dresden elektronik FLS-A2 broken

### ISSUE THREAD

**Issue by l-mb** [Koenkk/zigbee2mqtt#22036]
### What happened?

Upgraded to 1.36.1 commit: ffc2ff1 today, and my FLS-A2 dropped to "Unsupported". (Originally introduced with https://github.com/Koenkk/zigbee-herdsman-converters/pull/4889)

I assume this is related to the recent changes to the extension mechanism, and I'll look towards re-submitting an update, but wanted to get this into the tracker.

### What did you expect to happen?

Continued support or possibly an automated conversion to the new model, or maybe I missed a warning a few releases ago warning that the support would be depreciated?

### How to reproduce it (minimal and precise)

Upgrade to latest release if having a FLS-A2 in your network.

### Zigbee2MQTT version

    1.36.1 commit: ffc2ff1

### Adapter firmware version

20230507

### Adapter

SonOff

### Setup

Plain, containerized

**Comment by l-mb** [comment]
Sorry for getting back to this so late.

The automatic device definition generation didn't _quite_ work (it detected them as onOff rather than light, and didn't pull in all the definitions), but it was easy enough to fix (the following restores it to the exact state it was pre-migration):

```
const {deviceEndpoints, identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['FLS-A2 (1-10V)'],
    model: 'FLS-A2 (1-10V)',
    vendor: 'dresden elektronik',
    description: 'Zigbee controller for 1-10V/PWM',
    extend: [
        deviceEndpoints({"endpoints":{"l1":11,"l2":12,"l3":13,"l4":14}}),
        identify(),
        light({"powerOnBehavior":false,"endpointNames":["l1","l2","l3","l4"]})
    ],
    meta: {multiEndpoint: true, disableDefaultResponse: true },
};

module.exports = definition;
```

Since it's so much shorter than the other ones I saw in the collection I thought I'd run it by you before I create a new submit request :)

**Comment by Koenkk** [comment]
Could you try without the following line: `meta: {multiEndpoint: true, disableDefaultResponse: true },`? For the rest it looks good, please make a PR

**Comment by l-mb** [comment]
Ah, yes, the multiEndpoint is redundant (though it was suggested by the dev console), but the disableDefaultResponse is unfortunately still needed (see the original PR referenced).
I'll create a PR. Thanks!

**Comment by l-mb** [comment]
Just to wrap this up - I gave up on the devices and replaced them with other solutions since they kept interfering with my Zigbee network's stability.

**Comment by piotrpio** [comment]
Hi @l-mb 

I'm trying to get the FLS-A2 (1-10V) to work with power on behavior. Currently each device restart results in light switching on, I'd really like it to be able to set it to `previous`. I'm looking at the support page for FLS-A (https://www.zigbee2mqtt.io/devices/BN-600078.html), as I don't see one for FLS-A2 (to be fair I'm not sure what changed). The doc indicates power_on_behavior should work, but I cannot seem to set it. Since you've been working with this module, do you happen to know what can be done about that?

Sorry if this issue is the wrong place to ask.

**Comment by l-mb** [comment]
@piotrpio Sorry, no idea; even while I was still using the module I controlled the behaviour explicitly through Home Assistant and always left the device in the "power reset -> full light" mode so I could turn the lights on even if my zigbee networks were down in an emergency.

My best suggestion would be to contact the vendor. Good luck!

**Comment by piotrpio** [comment]
@l-mb thanks for the reply! I figured that the docs are probably invalid, with latest firmware `power_on_behavior` is unsupported.
