### ISSUE TITLE
hoch_din not supported anymore

### ISSUE THREAD

**Issue by thezjo** [Koenkk/zigbee2mqtt#22058]
### What happened?

Since legacy extend support is remove I can't use the hoch-din device anymore, I use an external converter for a 3 phase HOCH ZJSBL7-100Z in order to be able to set the over_leakage_current_threshold, over_current_threshold and to report the 2 phase on voltage, current and power. TS601_rcbo does not have this functionality. I believe this was sometime on the TODO list according this link https://github.com/Koenkk/zigbee-herdsman-converters/commit/1cbda1ba4521f23b2edfd3a5c2aa427c146ec6be 
The manufacturing code is _TZE200_hkdl5fmv.
Is there a possibility to extend the rcbo device with these extra exposed elements?
Current status from my device is:
{
    "alarm": "clear",
    "child_lock": "off",
    "countdown_timer": 0,
    "current": 15.12,
    "current_average": 0,
    "current_l1": 5.051,
    "current_l2": 5.038,
    "current_l3": 5.032,
    "energy": 2336.43,
    "energy_consumed": 2336.12,
    "leakage_current": 4,
    "linkquality": 207,
    "meter_number": "420100000001",
    "over_current_alarm": "on",
    "over_current_threshold": 16,
    "over_current_trip": "on",
    "over_leakage_current_alarm": "on",
    "over_leakage_current_threshold": 25,
    "over_leakage_current_trip": "on",
    "over_temperature_alarm": "off",
    "over_temperature_threshold": 60,
    "over_temperature_trip": "off",
    "over_voltage_alarm": "off",
    "over_voltage_threshold": 385,
    "over_voltage_trip": "off",
    "power": 3418,
    "power_l1": 1139.6,
    "power_l2": 1139,
    "power_l3": 1139.3,
    "power_on_behavior": "on",
    "self_test": "clear",
    "self_test_auto": "off",
    "self_test_auto_days": 0,
    "self_test_auto_hours": 0,
    "state": "on",
    "temperature": 34,
    "trip": "clear",
    "under_voltage_alarm": "off",
    "under_voltage_threshold": 20,
    "under_voltage_trip": "off",
    "voltage": 227.5,
    "voltage_average": 229.9,
    "voltage_l1": 227.5,
    "voltage_l2": 228.1,
    "voltage_l3": 227.9
}

### What did you expect to happen?

That this functionality migrated to the newer version

### Zigbee2MQTT version

1.36.1.1

### Adapter firmware version

20220219

### Adapter

zig a zig

### Setup

HAOS

**Comment by rmribeiro2024** [comment]
Here, same problem. My lock does not work more after this update.

**Comment by Koenkk** [comment]
Looks like you external converter broke, see [release notes](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.36.1) on how to fix it. Please consider creating a pull request for out-of-the-box support.

**Comment by mcapmari** [comment]
Hi @thezjo 
Could you explain how you are able to change over_leakage_current_threshold and over_current_threshold values?
I have similar device and I'm not able to adjust them.

**Comment by mcapmari** [comment]
Hi @thezjo 
Any chance you solved it? facing the same issue not being able to change over_leakage_current_threshold and over_current_threshold values.
