### ISSUE TITLE
Ledron LightWizar Zigbee(_TZ3000_zwszqdpy)

### ISSUE THREAD

**Issue by dinamik1488** [Koenkk/zigbee2mqtt#22067]
### What happened?

dont work in 19.13.0

### How to reproduce it (minimal and precise)

It is not defined. 
[https://github.com/Koenkk/zigbee-herdsman-converters/pull/7309](url)
But it works with such a converter
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS1002', manufacturerName: '_TZ3000_zwszqdpy'}],
        model: 'YK-16',
        vendor: 'Ledron',
        description: 'RGB+CCT Remote',
        fromZigbee: [fz.battery, fz.command_on, fz.command_off, fz.command_move_to_level, fz.command_move_to_color_temp, fz.command_step_color_temperature, fz.command_step],
        toZigbee: [],
        exposes: [e.battery(), e.battery_voltage(), e.action(['on', 'off', 'brightness_move_to_level', 'color_temperature_move'])],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
            await endpoint.command('genGroups', 'miboxerSetZones', {zones: [
                {zoneNum: 1, groupId: 101},
                {zoneNum: 2, groupId: 102},
                {zoneNum: 3, groupId: 103},
                {zoneNum: 4, groupId: 104},
                {zoneNum: 5, groupId: 105},
                {zoneNum: 6, groupId: 106},
                {zoneNum: 7, groupId: 107},
                {zoneNum: 8, groupId: 108},
            ]});
            await endpoint.command('genBasic', 'tuyaSetup', {}, {disableDefaultResponse: true});
        },
    };

module.exports = definition;

### Zigbee2MQTT version

1.36.1-dev

### Adapter firmware version

20230507

### Adapter

cc2652 sonoff dongle-p

### Setup

Beelink u5700

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by dinamik1488** [comment]
Thanks!
