### ISSUE TITLE
[New device support]: Insta Dimmaktor Mini

### ISSUE THREAD

**Issue by koenidet** [Koenkk/zigbee2mqtt#22072]
### Link

https://www.nexentro.de/produkte/

### Database entry

don't know how to get there

### Comments

I'm not experienced enough to follow the instructions for the creation of an external definition and therefore hope, you can include the device into your list of supported devices. I have added the open source information for the device from the vendor.
[57006000_picsnexentrozigbeedimmingactuatormini.zip](https://github.com/Koenkk/zigbee2mqtt/files/14863629/57006000_picsnexentrozigbeedimmingactuatormini.zip)

### External definition

```shell
const {deviceEndpoints, identify, onOff, commandsOnOff, commandsLevelCtrl, commandsColorCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['NEXENTRO Dimming Actuator'],
    model: 'NEXENTRO Dimming Actuator',
    vendor: 'Insta GmbH',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"2":2,"4":4}}), identify(), onOff({"powerOnBehavior":false}), commandsOnOff({"endpointNames":["4"]}), commandsLevelCtrl({"endpointNames":["4"]}), commandsColorCtrl({"endpointNames":["4"]})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Does it work with this external converter?
