### ISSUE TITLE
TS0601 _TZE204_pfayrzcw shows not supported in 1.36.1

### ISSUE THREAD

**Issue by looay103** [Koenkk/zigbee2mqtt#22070]
### What happened?

TS0601 _TZE204_pfayrzcw not work anymore after the lastest update 1.36.1. 
It shows "manufacturerName not supported".

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20221226

### Adapter

cp2102n

### Setup

Add-on Home Assistant OS running on Pi4

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee2mqtt/issues/22440
