### ISSUE TITLE
Allow secret.yaml for other fields (e.g. network_key)

### ISSUE THREAD

**Issue by airdrummingfool** [Koenkk/zigbee2mqtt#2209]
In #2201, you added the ability to store sensitive MQTT credentials in `secret.yaml` and reference that file in `configuration.yaml`, so that the configuration file could be saved in version control without leaking private information. I think this is a great feature, but it would be even better if it were available for any/all fields in the configuration file.

For example, I don't want my `network_key` entry saved into my git repository - I consider that sensitive information. Actually, that might be the only other field I'd be concerned with; perhaps best practice would also separate `channel`, `pan_id`, and `ext_pan_id`, but `network_key` is the important one in my opinion.

So, perhaps this feature request could be limited just to allowing a `secret.yaml` entry for `network_key`.

**Comment by Koenkk** [comment]
Implemented, thanks!

**Comment by airdrummingfool** [comment]
Thank you!
