### ISSUE TITLE
[Wrong device]:  TS0601_fan_and_light_switch recognized as TS0601_fan_switch

### ISSUE THREAD

**Issue by rodrigobutta** [Koenkk/zigbee2mqtt#22097]
### Link

https://cnwstele.en.made-in-china.com/product/lEDRoijJXVcw/China-Us-EU-Tuya-WiFi-Smart-Wall-Fan-Light-Switch-Ceiling-Lamp-Voice-Remote-Control-Speed-Control-Electrical-Fan-Light-Touch-Switch.html

### Model

TS0601_fan_and_light_switch

### Description

TS0601_fan_and_light_switch recognized as TS0601_fan_switch

### Vendor

Tuya

### Picture (link)

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMvugy5Tetuk6vzFSHCO-zCnp_5vgIXiRc-VAjl_zHKokrEjWD1598dw5qUVBipCfN5k8&usqp=CAU

### Database entry

`
{"id":17,"type":"Router","ieeeAddr":"0xa4c138e02eb939d4","nwkAddr":4428,"manufId":4417,"manufName":"_TZE200_lawxy9e2","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�\u000e�-i�\u000e�-i�\u000e�-f�\u000e�-\u0012","65506":54,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZE200_lawxy9e2","zclVersion":3,"appVersion":70,"modelId":"TS0601","powerSource":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1712335755381}
`

### Notes

Hi!

I'm trying for Z2M to recognize the right device (it´s listed) but with no luck. May be the device itself is saying the wrong model?

The device is
https://www.zigbee2mqtt.io/devices/TS0601_fan_and_light_switch.html

And it get recognized as
https://www.zigbee2mqtt.io/devices/TS0601_fan_and_light_switch.html

Thanks and let me know what can I do, since there is no need of a new device I think

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by rodrigobutta** [comment]
Wow man, you´re quick. I´ll check the commit so I can help with some PR in the future if needed. Thanks!
