### ISSUE TITLE
[New device support]: Tuya WZ5 missidentified as TS0505B

### ISSUE THREAD

**Issue by java-devil** [Koenkk/zigbee2mqtt#22095]
### Link

https://www.zigbee2mqtt.io/devices/WZ5_rgbcct.html

### Database entry

Is there perhaps a way to query this data without a full-blown SQL installation?

### Comments

Very similar issue to:
https://github.com/Koenkk/zigbee2mqtt/issues/13466#issuecomment-1209662389
(and many other similar issues related to the WZ5 line with recent firmware)

The consequence of this "miss-identification" is that Z2M is sending color information to WZ5 in the "xy" color mode → which it is not able to properly interpret → which results in white LEDs present in pure RGB color modes → which results in considerably desaturated color representation.

The ultimate proof of this is that manually sending a message via MQTT to set the color in "hs" mode results in much deeper RGBs than the same color set in HA/Z2M.

I tried modifying the snippet from the linked issue to comply with "modernExtend". However I'm no JS dev and I certainly mixed something up since the "xy" color slider on the "Exposes" tab was indeed substituted with an "hs" color slider, but the messages on MQTT still end up somehow transformed from "hs" values to "xy" even when using the "hs" color slider ;)

Short-Term Goal: Please help me realize the error of my ways in the snippet below.
Long-Term Goal: After confirming that this approach indeed works → perhaps incorporate those findings into Z2M?

### External definition

```shell
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
  fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZB210_3zfp8mki'}],
  model: 'TS0505B',
  vendor: 'TuYa',
  description: 'Zigbee RGB+CCT Light',
  extend: [light({color: {modes: ["hs"], applyRedFix: true}})],
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7349
