### ISSUE TITLE
Sylvania 73741 Won't Pair

### ISSUE THREAD

**Issue by warllo54** [Koenkk/zigbee2mqtt#2210]
I am unable to get the Sylvania 73741 down lights to pair. They are listed in the database as being compatible and are in a reset state but are not discovered. They are within 1 inch of the c2531 and I just paired some ikea bulbs without any issue. Hoping for some suggestions.

**Comment by warllo54** [comment]
For anyone else having this issue, I was able to resolve the issue by using the dev version. After switching to the development docker container these lights work great.

**Comment by stampeder** [comment]
I'm having the same issue with these 73741 bulbs and Zigbee2mqtt version 1.9 on my Raspberry PI. Running Zigbee2mqtt as deamon. Not docker. Any thoughts?
