### ISSUE TITLE
Issue with Sengled E11-G13 added temp color

### ISSUE THREAD

**Issue by Xavhorn** [Koenkk/zigbee2mqtt#22118]
### What happened?

As of  4/1/2024. zigbee2mqtt reports that the Sengled E11-G13 bulb supports temp color. This is not the case. 
It comes in 2 fixed colors 2700K and 5000K or RGB

**Expose to remove: 
    - Color temp startup
    - Color temp**
    
    MFG links for reference. 
    https://us.sengled.com/products/copy-of-zigbee-color-a19-e26-hub-required?_pos=1&_fid=c47d021e6&_ss=c
    https://us.sengled.com/products/zigbee-white-5000k-a19-e26-hub-required?_pos=4&_fid=386267c26&_ss=c
    https://us.sengled.com/products/zigbee-color-a19-e26-1-pack-hub-required?_pos=3&_fid=a2820698d&_ss=c

### What did you expect to happen?

not have the option for Color Temp on a bulb that will not support. 

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E

### Setup

add-on

### Debug log

Publish 'set' 'color_temp_startup' to 'Dinning Room - Light' failed: 'Error: ZCL command 0xb0ce181403623373/1 lightingColorCtrl.write({"startUpColorTemperature":250}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

Publish 'set' 'color_temp_startup' to 'Dinning Room - Light' failed: 'Error: ZCL command 0xb0ce181403623373/1 lightingColorCtrl.write({"startUpColorTemperature":250}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

**Comment by mrskycriper** [comment]
Already fixed this in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7317/commits/5af7e2c3dcf3e691217ec94419067322e9628e52
