### ISSUE TITLE
Sengled E21-N1EA RGBW bulbs no longer expose RGB

### ISSUE THREAD

**Issue by bat1939** [Koenkk/zigbee2mqtt#22137]
### What happened?

The Sengled E21-N1EA are no longer showing the ability to change RGB colors. Only white color temps are showing

### Zigbee2MQTT version

1.36.1-1

### Adapter firmware version

20210120

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Proxmox Home Assistant VM, Add-on in Home Assistant.

**Comment by jrob** [comment]
I am having the same issue. 
Same version
Same Adapter
Not sure about dongle firmware version
HA running on an Intel NUC

**Comment by jrob** [comment]
Reverting to 1.36.0 restored the rgb color settings.

**Comment by bat1939** [comment]
> Reverting to 1.36.0 restored the rgb color settings.

I have also reverted back to 1.36.0 and rgb color is back.

**Comment by Koenkk** [comment]
Already fixed in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by askmahesh1** [comment]
Is this merged into the main branch.

**Comment by Koenkk** [comment]
Fix is available in 1.37.0
