### ISSUE TITLE
AVATTO ME167 battery_low not working

### ISSUE THREAD

**Issue by Blastmun** [Koenkk/zigbee2mqtt#22133]
### What happened?

Hello, I am having a problem with my thermostatic valves. The "battery_low" field never changes to "True". So I never see when the valve has no more battery.
Thanks

### What did you expect to happen?

Change state

### How to reproduce it (minimal and precise)

Produc Picture: 
[https://img.tttcdn.com/product/xy/2000/2000/p/gu1/C/2/C-E0289-2/C-E0289-2-1-8031-jjP3.jpg
](url)

Product Link:
[https://www.cafago.com/fr/p-c-e0289-2.html
](url)

### Zigbee2MQTT version

1.36.1-1 

### Adapter firmware version

20211217

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Setup

Proxmox VM

**Comment by Blastmun** [comment]
Help?

**Comment by DoWenzl94** [comment]
i have the same issue, did you have found a solution? @Blastmun
