### ISSUE TITLE
The brightness is changing randomly on turn on/off for FUT035Z+

### ISSUE THREAD

**Issue by bzumik1** [Koenkk/zigbee2mqtt#22144]
### What happened?

Hi, I am having [FUT035Z+](https://www.zigbee2mqtt.io/devices/FUT035Z+.html) which should be fully supported device. I am facing issue that when the light is turned on the brightness start to change randomly which not only looks bad on the dashboard but also causes problems to my automations because the state of the light is always updated. This behaviour stops after 10-20s, but the final brightness is also random and does not correspond to real state of the controller. After few tries I am also getting this error and the light stop working. I am not sure if that can have something to do with that. 
<img width="408" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/32042186/a4c18684-a3b9-4f95-895e-fe9cea5bc5f6">

### What did you expect to happen?

I expect this light to work normally.

### Zigbee2MQTT version

1.36.1-1

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

Add-on on HAOS running on Intel NUC

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14911240/log.txt)

**Comment by bzumik1** [comment]
Hi, I am new on GitHub, should I somehow chase this issue or should I keep it like this and someone will pick it up?

**Comment by centeljon** [comment]
I can confirm this issue - i see the same behavior. i downgraded to 1.36.0 which runs errorfree for this device.

**Comment by bzumik1** [comment]
Thanks for response, let me try that.

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee2mqtt/issues/22078 !
