### ISSUE TITLE
Bticino K4027C disable Tilt mode

### ISSUE THREAD

**Issue by leoogermenia** [Koenkk/zigbee2mqtt#22169]
### What happened?

The device is connected to a roller shutter and it can do only direction mode, not tilt mode. This also gave error to Alexa that it cannot understand when opening or closing the shade.

### What did you expect to happen?

To have only direction mode

### How to reproduce it (minimal and precise)

Install device and see the two values

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

EZSP v8

### Setup

Add-on on Home Assistant

**Comment by leoogermenia** [comment]
The problem is the K4003C doesn't have the tilt function, but only the postion one.

**Comment by FabianMangold** [comment]
HI @leoogermenia,

The latest DEV branch of Z2m now features a toggle switch to disable tilt for covers that don't need it.
Another PR([#7413](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7413)) will hopefully be merged soon, so that the tilt control will be displayed in case required only.

Cheers

**Comment by leoogermenia** [comment]
Good!
I was able to solve the problem in HA by modifying the `supported_features` attribute of the cover entity. But if I can do via Z2M is better!

**Comment by FabianMangold** [comment]
Any chance you could test the latest DEV branch and let us know if it does the trick for you ?
Thanks a lot

**Comment by leoogermenia** [comment]
Atm I have the stable version with the HA component, if I can switch to the dev version without repairing everything I can test it

**Comment by FabianMangold** [comment]
OK understood. In the end, it's your call if you wish to test or not, if you have a working solution its probably best not to touch it anymore.
Having that said, just take a backup of your system, which you can revert to in case required.
Switching between Stable and DEV should not break anything really.

In case you are using a plain vanilla Z2M, you will find instructions on how to switch here:
https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

In case of an HA integration, you can simply switch to the Edge track, which will give you the latest DEV branch.

**Comment by leoogermenia** [comment]
<img width="589" alt="Screenshot 2024-04-21 at 11 46 38" src="https://github.com/Koenkk/zigbee2mqtt/assets/78269245/7b351c36-d008-4217-951c-9e79306d0165">

**Comment by FabianMangold** [comment]
OK i see, the "latest" PR has not yet been merged into the version you are running. This version would have done everything automatically.

Nevertheless, you can still use the "former manual way". You will find a toggle switch in the devices "Settings (Specific)" page. Can you take a look there ?

<img width="1215" alt="grafik" src="https://github.com/Koenkk/zigbee2mqtt/assets/141126144/cf2c658e-ee89-4d59-a988-c363c655f4da">

**Comment by leoogermenia** [comment]
![image](https://github.com/Koenkk/zigbee2mqtt/assets/78269245/063a3da4-d880-47e3-8ed3-23e1a22eec1f)

Yes I see it!

**Comment by leoogermenia** [comment]
Ok I tried to hide the Tilt function and remove the `supported_features` value change to hide in HA and everything works!

**Comment by FabianMangold** [comment]
Perfect, thanks a lot for your feedback, much appreciated.
For your info, this toggle button will no longer be present in the next DEV version, since Z2m will now determine if the tilt control needs to be displayed or hidden, based on the calibration mode of the switch.

Can we consider this issue closed ?
Wish you a nice day.

**Comment by leoogermenia** [comment]
> For your info, this toggle button will no longer be present in the next DEV version, since Z2m will now determine if the tilt control needs to be displayed or hidden, based on the calibration mode of the switch.

Ok, so I can switch to stable version again?

**Comment by leoogermenia** [comment]
I see also that is possible to change the identify effect. Is it possible to add also for led in the dark/led if on? Only change color, so an user can use different color on every each device?
But I think I need to open/see other request

**Comment by FabianMangold** [comment]
Yes sure, you can switch to stable again.

For the LED color, no that's not possible. This is not a Z2M limitation, simply the firmware not supporting it (unfortunately)

**Comment by leoogermenia** [comment]
Thanks!
I close the issue
Have a nice week!
