### ISSUE TITLE
New device: Ikea LED2110R3 (Replacement for LED1923R5, IKEA Colored GU10)

### ISSUE THREAD

**Issue by janerikvw** [Koenkk/zigbee2mqtt#22186]
Hi I have the new IKEA Tradfri lights, but they are not supported yet. They seem to have the exact same specs on the website as the previous ones.

### Link

https://www.ikea.com/nl/nl/p/tradfri-led-lamp-gu10-345-lumen-draadloos-dimbaar-gekleurd-en-wit-spectrum-70547474/

### Database entry

{"id":2,"type":"Unknown","ieeeAddr":"0x3410f4fffe67ef5e","nwkAddr":41403,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1712849529297}

### Comments

This is the updated version of the old Colored Ikea GU10 lights. Stated as here: https://www.zigbee2mqtt.io/devices/LED1923R5_LED1925G6.html

### External definition

```shell
-
```

**Comment by mrskycriper** [comment]
What zigbee model does it report? Database entry seems corrupted.

**Comment by janerikvw** [comment]
It seems that it was an error on my side. I reinstalled everything and now they are detected as: https://www.zigbee2mqtt.io/devices/LED1923R5_LED1925G6.html

**Comment by DeliusPit** [comment]
Today I accidentally bought a LED2210R3. The box says LED2210R3, the manual also mentions LED1923R5.

So far I haven't been able to pair it with zigbee2mqtt, in the zigbee2mqtt I can find the 1923, but not the 2210. Does that mean that the 2210 is indeed not supported (yet)?

**Comment by maxlojr** [comment]
Hello, same for me here

**Comment by ahb-bs** [comment]
I've add LED2110R3 to with my Conbee II / Deconz and they appear and show, but after a few minutes stop responding.

**Comment by temtekmedia** [comment]
any fixes? nothing works for me zigbee2mqtt cant find it

**Comment by ahb-bs** [comment]
I moved to a SLZB-06M in the end, as I got annoyed trying to make it work.
