### ISSUE TITLE
IKEA Badring E2202 not reporting water leak correctly

### ISSUE THREAD

**Issue by francisp2** [Koenkk/zigbee2mqtt#22184]
### What happened?

Bought 2 Badring water sensors, they pair, say supported, but stay like this
![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/0aa8503b-3f3c-40ff-a4a4-36ad0b0f3443)

So it made one a little wet, it said 'Leaking', but 36 hours later, it still said 'Leaking'. I removed it, paired again, back to water leak : Null

Related to  IKEA Badring E2202 not reporting water leak correctly #21794 but that one is closed.

### What did you expect to happen?

I expected it to return to 'Not leaking' or something after it dried

### How to reproduce it (minimal and precise)

make it a little bit wet, and let it dry

### Zigbee2MQTT version

    1.36.1 commit: ffc2ff1d

### Adapter firmware version

20230507

### Adapter

2020 model of TubeZB non POE Ethernet coordinator

### Setup

bare metal (npm install) , happens both on proxmox vm or bare metal on pi 4, both running dietpi bookworm

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14947917/log.txt)

**Comment by mrskycriper** [comment]
What happens in the logs while you test the sensor? The whole file is very long and not very informative. Can you make a controlled test of the sensor and copy the relevant results out of the log file?

**Comment by aurelmarius** [comment]
I have this sensor lying arround, i will do some testing.

**Comment by aurelmarius** [comment]
Can't reproduce the issue on 1.36.1-dev commit: [f774753] with SLZB-06 CC2652P fw 20230507. One difference is that mine doesn't expose Low Battery.
Some pictures and logs attached.

<img width="1679" alt="Screenshot 2024-04-11 at 21 46 28" src="https://github.com/Koenkk/zigbee2mqtt/assets/7074653/3039a7c2-96ca-4c11-a8d2-282993b09450">
<img width="1008" alt="Screenshot 2024-04-11 at 21 46 20" src="https://github.com/Koenkk/zigbee2mqtt/assets/7074653/fd555d2f-6ef2-4fe5-ad75-d71ab7265996">
<img width="950" alt="Screenshot 2024-04-11 at 21 46 00" src="https://github.com/Koenkk/zigbee2mqtt/assets/7074653/e750b5d6-77bd-4912-b4e6-1d9ef7e91c96">
[zigbee2mqtt_logs_badring.txt](https://github.com/Koenkk/zigbee2mqtt/files/14950203/zigbee2mqtt_logs_badring.txt)

**Comment by francisp2** [comment]
12 hours later, Zigbee network just consist of the Zigstar v4 and the Badring, still 'leaking'
[error.txt](https://github.com/Koenkk/zigbee2mqtt/files/14965155/error.txt)

**Comment by aurelmarius** [comment]
@francisp2 upgrade to dev branch, mine is working ok on dev.

**Comment by francisp2** [comment]
No. Installed dev, still 'Leaking', Exposes screen changed, but that is all.
![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/d25f7a3e-f23f-4872-8de4-6b3d229dadf7)
![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/99f6278e-7f5b-4993-821f-f85d5aa3ec7c)
[out.txt](https://github.com/Koenkk/zigbee2mqtt/files/14969432/out.txt)

**Comment by Great-Chart** [comment]
I've found that if I short out (via screwdriver) the underside pins to trigger the alarm / wet (leaking) event(s); then once the short has been removed the device will then reset to display clear and (appears to) then stay persistent.
Prior to that the device had stuck in a flashing leaking state as per the other posts above (in my case I left it overnight).

Not on a dev branch, running Sonoff Dongle-P.
Uncertain how long this might now remain displaying correctly or if it'll revert to leaking over an extended period.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/101117351/c14bfeec-e36f-4b9e-9d25-7f119ff5d1e9)

**Comment by francisp2** [comment]
still the case on 1.37.1

**Comment by francisp2** [comment]
still the case on 1.38

**Comment by dg7pc** [comment]
I can confirm the behaviour with 2 devices. With one the haning leak state cleared after using the fingers to shortcut the sensor. The second (same Firmware 1.0.7) does not clear and still shows a leak.
Updated to: Zigbee2MQTT version 1.38.0-dev (commit #6c123c2)

**Comment by Mark-64** [comment]
Same here with 2x BADRIG sensors and Z2M 1.37.1, both sensor stuck on wet.
If I shurtcut pins with the fingers mutliple times, then the sensors go back to dry, very unreliable.

**Comment by alexruffell** [comment]
I have the same issue with 2 Badring sensors. I found that if you short the contacts for a very short period of time (it varies but <3 seems to reproduce the issue reliably) it often stays stuck in wet. Another short and it reverts to dry. I use ZHA so the issue may be related to the firmware of the device more than Zigbee2MQTT or ZHA.

**Comment by where-is-s** [comment]
It's the same for me. IKEA Badring gets stuck on wet while working through Zigbee2MQTT 1.39.0. Did anyone manage to resolve this somehow?

**Comment by vasileio** [comment]
> It's the same for me. IKEA Badring gets stuck on wet while working through Zigbee2MQTT 1.39.0. Did anyone manage to resolve this somehow?

Just shorting the contacts again resets it. It definitely looks like a firmware issue, rather than a Z2M or ZHA one, as the behaviour is the same in either, and also on-device (it does keep on beeping)

**Comment by Elephantoplasty** [comment]
Another person who is finding the Badring gets stuck showing leaking after moisture activation.  And shorting the terminals also results in a leaking output, but it then resets back to normal within a few seconds.

**Comment by where-is-s** [comment]
> Just shorting the contacts again resets it. It definitely looks like a firmware issue, rather than a Z2M or ZHA one, as the behaviour is the same in either, and also on-device (it does keep on beeping)

Yeah, that works of course. But in my case device stops beeping correctly, only Zigbee reporting is broken. I have to short contacts 1-3 times in order to reset device's state back to "dry". It is highly inconvenient because I have big anti-leakage scenarios connected to the sensor and it is important to me that the sensor reports that it is wet only while it is actually wet. I thought maybe there is some kind of workaround that could make it work without having to manually short contacts.
