### ISSUE TITLE
Sengled  E21-N1EA lose color control

### ISSUE THREAD

**Issue by marc3k18** [Koenkk/zigbee2mqtt#22196]
### What happened?

Sengled  E21-N1EA lose color control in last update

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20210708

### Adapter

zStack3x0

### Setup

HA os on Laptop

**Comment by mrskycriper** [comment]
Already fixed in the dev branch.

**Comment by sopelt** [comment]
Have you seen https://github.com/Koenkk/zigbee2mqtt/issues/22137 ? Looks like a duplicate.
