### ISSUE TITLE
dimmer slow to report changes Iolloi ID-UK21FW09

### ISSUE THREAD

**Issue by duncanhancox** [Koenkk/zigbee2mqtt#22216]
### What happened?

with z2m 1.35 brightness changes with the rotary knob were reported immediately to z2m, but all versions after that take a few seconds to report brightness changes. however the devices still respond quickly to brightness settings via mqtt or the front end of z2m

### What did you expect to happen?

previous behaviour of quick reporting to be continued

### How to reproduce it (minimal and precise)

roll back to 1.35 and the good behaviour resumes - upgrade to any version after and its back to slow reporting
ive tested on 2 different networks and its the same behaviour
ive updated the dongle firmware but that hasnt solved the issue
ive tried swapping to ember mode but that hasnt solved the issue

### Zigbee2MQTT version

>1.35

### Adapter firmware version

7.4.1.0 and also previous versions

### Adapter

sonos dongle-e

### Setup

z2m plain on pi 4

**Comment by phoenixxie0** [comment]
The same broblem. Light controller: TuYa
 TS0502B. When I adjust the brightness on the lovelace interface, the brightness of the light has changed, but the brightness bar on the interface jumps back to 100.
