### ISSUE TITLE
Support for lumi.curtain.aq2

### ISSUE THREAD

**Issue by Dennisd80** [Koenkk/zigbee2mqtt#2221]
I would like to have the aqara roller motor to be supported.  

It's a roller blind motor by aqara/xiaomi ZNGZD11LM.I can't seems to add it to devices,js (using hassio) probally because i'm on zigbee2mqtt edge. Would somebody be so kind to add this device?

**Comment by Koenkk** [comment]
I think this can easily be done by changing https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L675 to `zigbeeModel: ['lumi.curtain', 'lumi.curtain.aq2'],`

**Comment by Dennisd80** [comment]
Unfortunately after changing devices.js i get the following error. zigbee2mqtt:warn 11/1/2019, 9:01:47 PM Device with modelID 'lumi.curtain.aq2' is not supported. (hassio addon)

**Comment by Koenkk** [comment]
Did you set `zigbee_shepherd_devices: true`?

**Comment by Dennisd80** [comment]
Yes, i did. It also recognizes the custom devices.js. But i saw i had a error that i't could copy the custom device.js  to node_module/zigbee2mqtt/herdsman-converter. (was on stable zigbee2mqtt), then i decided to try on zigbee2mqttedge and now it seems to work. Thanks!

**Comment by Koenkk** [comment]
So after this the device fully works?

**Comment by Dennisd80** [comment]
Yes 100%

**Comment by Koenkk** [comment]
Thanks, will be supported out of the box in the next zigbee2mqtt release.
