### ISSUE TITLE
[New device support]: Philips 6109331C5 new zigbeeModel LTC010

### ISSUE THREAD

**Issue by Kevin6872** [Koenkk/zigbee2mqtt#22230]
### Link

https://www.zigbee2mqtt.io/devices/6109331C5.html

### Database entry

{"id":43,"type":"Router","ieeeAddr":"0x001788010336ee56","nwkAddr":46678,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"LTC010","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"colorTemperature":250}},"genLevelCtrl":{"attributes":{"currentLevel":84}},"genBasic":{"attributes":{"zclVersion":1,"dateCode":"20230606","swBuildId":"1.108.5"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":2,"dateCode":"20230606","swBuildId":"1.108.5","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1713283952837}

### Comments

Hello, Philips 6109331C5 is in the supported list. My old Philips 6109331C5 also works well, but the newly purchased Philips 6109331C5 cannot be recognized by zigbee2mqtt after adding the device. I found that the zigbeeModel of the two is different. The old one is LTF002, and the new one is LTC010.it runs well using external definitions.

### External definition

```shell
const {identify} = require('zigbee-herdsman-converters/lib/modernExtend');
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['LTC010'],
    model: 'LTC010',
    vendor: 'Philips',
    description: 'Automatically generated definition',
    extend: [identify(), philipsLight({"colorTemp":{"range":[153,454]}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!


Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
