### ISSUE TITLE
Wrong device recognised

### ISSUE THREAD

**Issue by cfpandrade** [Koenkk/zigbee2mqtt#22234]
### What happened?

recognises this device TS011F_plug_1

### What did you expect to happen?

it should recognise TuYa TS011F_2_gang_2_usb_wall

### How to reproduce it (minimal and precise)

add this to zigbee2mqtt

### Zigbee2MQTT version

1.36.1-1

### Adapter firmware version

20220219

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Add-on Home Assistante

**Comment by mrmaximas** [comment]
please post db entry for this device
