### ISSUE TITLE
SIN-4-FP-21 - Different firmware updates for apparently same devices

### ISSUE THREAD

**Issue by nerthazrim** [Koenkk/zigbee2mqtt#22245]
### What happened?

I own 2 SIN-4-FP-21, ordered at the same time from the same vendor.
Both received a firmware update today, but they are not ending up with the same version after update.

### What did you expect to happen?

Both SIN-4-FP-21 to have the same version after having completed the update.

### How to reproduce it (minimal and precise)

I don't know... Except by buying a new one and updating it?

### Zigbee2MQTT version

1.36.1-1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

 EZSP v8

### Setup

Add-on on Home Assistant supervised in a Proxmox Debian 12 VM

### Debug log

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8452948/1c42f859-864a-4958-a2e9-a6d382c471d6)

**Comment by n0n0-44** [comment]
Hi,

Same problem for me, with 3 SIN-4-FP-21 ...
![Capture d'écran 2024-04-25 190921](https://github.com/Koenkk/zigbee2mqtt/assets/151221730/5db6adf0-ca1d-4218-9828-b4d7c7178c11)

**Comment by nerthazrim** [comment]
Fun fact, I got an update available for the one with the "oldest" version, today.
But they're still not at the same one 😁 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/8452948/fa720400-ab25-4094-adc8-82a893ccf7d2)

**Comment by n0n0-44** [comment]
The same here ...
![image](https://github.com/Koenkk/zigbee2mqtt/assets/151221730/50fe2993-b0ac-4dd6-804c-fb87ebe13036)

**Comment by Th-Ar** [comment]
Same here, 3 different versions :
![image](https://github.com/Koenkk/zigbee2mqtt/assets/21056626/fe50688b-b1c6-4aee-a7c0-903c402b771e)

**Comment by nerthazrim** [comment]
Hi,

New update available on both my SIN-4-FP-21 but still a difference in versions:
3.3.0-1.4.4 for one
3.3.0-1.4.5 for the other

**Comment by Najihel** [comment]
Hello,

Same issue here, sometimes "new version" is available but the upgrade failed eachtime

```
info 2024-09-04 12:50:53z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/buanderie-chauff', payload '{"energy":2.1,"linkquality":255,"pilot_wire_mode":"frost_protection","power":0,"state":"OFF","update":{"installed_version":768,"latest_version":771,"state":"available"},"update_available":true}'
info 2024-09-04 12:50:55z2m: Updating 'buanderie-chauff' to latest firmware
info 2024-09-04 12:50:55z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Updating 'buanderie-chauff' to latest firmware","meta":{"device":"buanderie-chauff","status":"update_in_progress"},"type":"ota_update"}'
info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/buanderie-chauff', payload '{"energy":2.1,"linkquality":255,"pilot_wire_mode":"frost_protection","power":0,"state":"OFF","update":{"installed_version":768,"latest_version":771,"state":"available"},"update_available":true}'
info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'buanderie-chauff' failed (No new image available)","meta":{"device":"buanderie-chauff","status":"update_failed"},"type":"ota_update"}'
info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"buanderie-chauff"},"error":"Update of 'buanderie-chauff' failed (No new image available)","status":"error","transaction":"va46c-3"}'
error 2024-09-04 12:50:58z2m: Update of 'buanderie-chauff' failed (No new image available)
```

<img width="1320" alt="image" src="https://github.com/user-attachments/assets/5b607ef1-95a2-4b3f-8ee1-04743ddde5c9">

**Comment by Th-Ar** [comment]
Hello,
For the same devices as before, I now have not 3 different versions, but 5.
![image](https://github.com/user-attachments/assets/d00f462d-87c6-41e8-ac96-53766d001d61)

**Comment by Najihel** [comment]
> Hello,
> 
> Same issue here, sometimes "new version" is available but the upgrade failed eachtime
> 
> ```
> info 2024-09-04 12:50:53z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/buanderie-chauff', payload '{"energy":2.1,"linkquality":255,"pilot_wire_mode":"frost_protection","power":0,"state":"OFF","update":{"installed_version":768,"latest_version":771,"state":"available"},"update_available":true}'
> info 2024-09-04 12:50:55z2m: Updating 'buanderie-chauff' to latest firmware
> info 2024-09-04 12:50:55z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Updating 'buanderie-chauff' to latest firmware","meta":{"device":"buanderie-chauff","status":"update_in_progress"},"type":"ota_update"}'
> info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/buanderie-chauff', payload '{"energy":2.1,"linkquality":255,"pilot_wire_mode":"frost_protection","power":0,"state":"OFF","update":{"installed_version":768,"latest_version":771,"state":"available"},"update_available":true}'
> info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'buanderie-chauff' failed (No new image available)","meta":{"device":"buanderie-chauff","status":"update_failed"},"type":"ota_update"}'
> info 2024-09-04 12:50:58z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"buanderie-chauff"},"error":"Update of 'buanderie-chauff' failed (No new image available)","status":"error","transaction":"va46c-3"}'
> error 2024-09-04 12:50:58z2m: Update of 'buanderie-chauff' failed (No new image available)
> ```
> 
> <img alt="image" width="1320" src="https://private-user-images.githubusercontent.com/1873677/364344231-5b607ef1-95a2-4b3f-8ee1-04743ddde5c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Nzc1NzUsIm5iZiI6MTczMTY3NzI3NSwicGF0aCI6Ii8xODczNjc3LzM2NDM0NDIzMS01YjYwN2VmMS05NWEyLTRiM2YtOGVlMS0wNDc0M2RkZGU1YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMTMyNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU3YjkxZTAxNDE4MmNhNDI2OWUyYTQ5ZmUwM2M5YWI0YWQyNzNiNWY5NjVlMDgyYzU0MDMzOTYyYzUyMmE1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.H7EM-wfi7z-iwkNhAz77gjJwSQeBvBIjTIzRsecy_JI">

Hello everyone,

I found a workaround :
* Download the Nodon Connect app : https://nodon.fr/nodon/application-nodon-connect/
* Create an account
* Associate all your modules (physical access is mandatory)
* Upgrade manually the firmware

Before

![image](https://github.com/user-attachments/assets/21238b4e-147a-4fa2-b2cf-2cef5973e2fb)

After

![image](https://github.com/user-attachments/assets/3937d3da-33ca-4ffe-9832-219898aea85a)

**Comment by nerthazrim** [comment]
Well, even after updating the modules with the Nodon Connect app, I still get different versions displayed in Z2M.
I guess I probably have 2 slightly different models without me knowing it so it's not a Z2M issue, I'm closing this :)

Thanks!

**Comment by Najihel** [comment]
> Well, even after updating the modules with the Nodon Connect app, I still get different versions displayed in Z2M.
> I guess I probably have 2 slightly different models without me knowing it so it's not a Z2M issue, I'm closing this :)
> 
> Thanks!

You have to re-interrogate the device (the "i" button) to show the new firmware version

**Comment by nerthazrim** [comment]
Oh, indeed! Thanks!
Well, let's keep it closed anyway, problem solved as far as I'm concerned ;-)
