### ISSUE TITLE
After version update wrong picture and device model selected TS0044 is shown as TS0044-1

### ISSUE THREAD

**Issue by Rifmaster-NL** [Koenkk/zigbee2mqtt#22255]
### Link

https://www.zigbee2mqtt.io/devices/TS0044.html

### Model

TS0044

### Description

Wireless switch with 4 buttons

### Vendor

Tuya

### Picture (link)

https://www.zigbee2mqtt.io/devices/TS0044_1.html

### Database entry

{"id":3,"type":"EndDevice","ieeeAddr":"0x943469fffe5f4715","nwkAddr":19473,"manufId":4098,"manufName":"_TZ3000_wkai4ga5","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"��],\u0011��^,\u0011T�^,\u0012F5`,\u0011�Md,\u0012�0e,\u0011P+g,\u0011��g,\u0012","65506":31,"65508":1,"65534":0,"modelId":"TS0044","manufacturerName":"_TZ3000_wkai4ga5","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":190,"batteryVoltage":29}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-708457359},"lastSeen":1713467508310}

### Notes

I have 2 Tuya TS0044 that where showing the correct picture after a update the picture was incorrect. Picture show is for the TS0044_1

**Comment by Koenkk** [comment]
Seems that the `_TZ3000_wkai4ga5` can be either the square or long remote, e.g. @brinzlee has a `_TZ3000_wkai4ga5` which is the square button: https://github.com/Koenkk/zigbee2mqtt/issues/21458#issuecomment-2042304419
