### ISSUE TITLE
Aqara smart plug SP-EUC01,  activePower attribute reporting is not supported

### ISSUE THREAD

**Issue by imammedo** [Koenkk/zigbee2mqtt#22269]
### What happened?

Power value is  updated sporadically  when the plug decides to send message on its own, sometimes it takes hours before value is update.

Manually attribute reading works fine, though
   `Read result of 'haElectricalMeasurement': {"activePower":33}`
and updates value.

An attempt to configure reporting for the plug results in error:
`ZCL command 0x54ef441000bdbeeb/1, haElectricalMeasurement.configReport([{"attribute":"activePower","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE')`

to rule out z2m, reading reporting configuration from deconz results in: 'unreportable attribute' error.
So I guess plug doesn't support reporting after all. (plug I have says firmware date is: 01-13-2023)

The only thing for which reporting works is seMetering: {currentSummDelivered}, the for rest (power/voltage/current) attempt to configure reporting fails.

### What did you expect to happen?

power/volatge/current values should be uptodate

(I've seen temperature have been switched to polling at hardcoded interval)
Can we poll these attributes with configurable interval, if reporting configuration failed for them?
Yep,  I know it's twice more taxing on network but at least it will be usable and user will be able to pick an interval that suits their need/network.

### How to reproduce it (minimal and precise)

Attempt to configure reporting for `'haElectricalMeasurement': {"activePower"}`

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20210708

### Adapter

SONOFF ZB Dongle-P Zigbee 3.0

### Setup

container on x86 host

**Comment by diego351** [comment]
@imammedo  Have you figured this out, perhaps?
