### ISSUE TITLE
[Feature request]: Search function in Map view

### ISSUE THREAD

**Issue by peter1rhodes** [Koenkk/zigbee2mqtt#22275]
### Is your feature request related to a problem? Please describe

I often want to check how a particular device connects into the network, i.e. what devices it speaks to and how clear the signal is. Although marvellous in many ways, the Z2M Map is a bit useless for this, with hundreds of lines criss-crossing everywhere, and the text all jumbled up and hard to read.

### Describe the solution you'd like

It would be great to able to find particular nodes in the map by having them highlighted when I enter a search term in a text box. For example, if I want to see the kitchen light, typing "kitchen" might make all devices containing "kitchen" to change text colour and be brought to the front

### Describe alternatives you've considered

Honestly, I can't think of another way. Right now I just have to do without, and this seems like a natural solution

### Additional context

![image](https://github.com/Koenkk/zigbee2mqtt/assets/51478811/4b315b05-7cdd-41c1-8edb-5006dbb6e2cd)

**Comment by timdonovanuk** [comment]
Control F in your browser...

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8156439/4dbdffee-8414-4ac3-b217-3c90a2b94364)

And then if you click on it, it singles it out:

![image](https://github.com/Koenkk/zigbee2mqtt/assets/8156439/8f4c467a-e77a-455d-93ac-f7691add5395)

**Comment by peter1rhodes** [comment]
Thank you, Ctrl-F is a really good suggestion. I think it would still be a useful feature for the map itself, but this will help me for now

> Control F in your browser...
> 
> ![image](https://private-user-images.githubusercontent.com/8156439/324398892-4dbdffee-8414-4ac3-b217-3c90a2b94364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzE0NTMsIm5iZiI6MTcxNjQ3MTE1MywicGF0aCI6Ii84MTU2NDM5LzMyNDM5ODg5Mi00ZGJkZmZlZS04NDE0LTRhYzMtYjIxNy0zYzkwYTJiOTQzNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTMzMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I3NmFmMjA2YmVhNjAzYzRhZWI2OWQ3ZjQ3Mjg1NjExZjM3YzQwMDY5NjRmNWE2M2JkNTRhYjVmMzExN2QyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3qrucFCWROdY9pSAooECvLqWaiNgRkviB8TnQkf4FR8)
> 
> And then if you click on it, it singles it out:
> 
> ![image](https://private-user-images.githubusercontent.com/8156439/324399016-8f4c467a-e77a-455d-93ac-f7691add5395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzE0NTMsIm5iZiI6MTcxNjQ3MTE1MywicGF0aCI6Ii84MTU2NDM5LzMyNDM5OTAxNi04ZjRjNDY3YS1lNzdhLTQ1NWQtOTNhYy1mNzY5MWFkZDUzOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTMzMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgwMzc3ODk3NmVkZGFhMjUzYmEyODZmYmEzNGZmN2YzYzVkMWViNjQwNmYzNGIxYzYxYzZhYzNiMzRjMmYxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0sXeZXflFAasRAh8dZiFuoc8wdfy8j-6RVQVIHbo5Wc)
