### ISSUE TITLE
Innr SP 222 Smart Plug

### ISSUE THREAD

**Issue by jameswarner62** [Koenkk/zigbee2mqtt#2228]
Trying to add an Innr SP 222 Smart Plug, it should support power monitoring, but just for simplicity to start.  Has anyone got this to work, or can anyone help?

database entry:

{"id":7,"type":"Router","ieeeAddr":"0x14b457fffe4289d8","nwkAddr":19225,"manufId":4454,"manufName":"innr","powerSource":"Mains (single phase)","modelId":"SP 222","epList":[1,242],"zclVersion":3,"appVersion":16,"stackVersion":101,"hwVersion":1,"swBuildId":"2.1","status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,8,2821,4096,64642],"outClusterList":[10,25],"clusters":{"64642":{"dir":{"value":1},"attrs":{}},"genBasic":{"dir":{"value":1},"attrs":{"9":5,"10":{},"11":"www.innr.com������","65533":1,"zclVersion":3,"appVersion":16,"stackVersion":101,"hwVersion":1,"manufacturerName":"innr","modelId":"SP 222","dateCode":"20190418-20","powerSource":1,"appProfileVersion":0,"deviceEnabled":1,"swBuildId":"2.1"}},"genIdentify":{"dir":{"value":1},"attrs":{"65533":1,"identifyTime":0}},"genGroups":{"dir":{"value":1},"attrs":{"65533":1,"nameSupport":0}},"genScenes":{"dir":{"value":1},"attrs":{"65533":1,"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":128}},"genOnOff":{"dir":{"value":1},"attrs":{"16387":255,"65533":1,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}},"genLevelCtrl":{"dir":{"value":1},"attrs":{"15":0,"16384":255,"65533":1,"currentLevel":254,"remainingTime":0,"onLevel":255}},"genTime":{"dir":{"value":2},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"haDiagnostic":{"dir":{"value":1},"attrs":{"65533":1,"aPSTxUcastSuccess":0,"aPSTxUcastRetry":0,"aPSTxUcastFail":0,"nwkFcFailure":0,"apsFcFailure":0,"apsUnauthorizedKey":0,"nwkDecryptFailures":0,"apsDecryptFailures":0,"packetBufferAllocateFailures":0,"phyToMacQueueLimitReached":0,"packetValidateDropCount":0,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":92,"lastMessageRssi":-77}},"lightLink":{"dir":{"value":1},"attrs":{"65533":1}}}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{"33":{"dir":{"value":2},"attrs":{}}}}},"dateCode":"20190418-20","_id":"0K5KTVIvAQmUHub3"}

 {
        zigbeeModel: ['SP 222'],
        model: 'SP 222',
        vendor: 'Innr',
        description: 'Smart Plug',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.onoff],

    },   
   

Getting following error:

,{"ieeeAddr":"0x14b457fffe4289d8","type":"Router","model":"SP 222","friendly_name":"0x14b457fffe4289d8","nwkAddr":19225,"manufId":4454,"manufName":"innr","powerSource":"Mains (single phase)","modelId":"SP 222","hwVersion":1,"swBuildId":"2.1","dateCode":"20190418-20"}]}'
/zigbee2mqtt-1.6.0/lib/extension/deviceReceive.js:109
                if (c.cid === cid) {
                      ^
TypeError: Cannot read property 'cid' of undefined
    at mappedDevice.fromZigbee.filter (/zigbee2mqtt-1.6.0/lib/extension/deviceReceive.js:109:23)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeMessage (/zigbee2mqtt-1.6.0/lib/extension/deviceReceive.js:105:52)
    at extensions.filter.forEach (/zigbee2mqtt-1.6.0/lib/controller.js:143:31)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeMessage (/zigbee2mqtt-1.6.0/lib/controller.js:143:14)
    at Zigbee.onMessage (/zigbee2mqtt-1.6.0/lib/zigbee.js:275:18)
    at ZShepherd.emit (events.js:198:13)
    at ZShepherd.<anonymous> (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/shepherd.js:157:14)
    at ZShepherd.emit (events.js:198:13)

**Comment by Koenkk** [comment]
Supported in latest dev.
