### ISSUE TITLE
Restricted environment problem

### ISSUE THREAD

**Issue by Alexofhiswalnut** [Koenkk/zigbee2mqtt#22296]
### What happened?

Hello, I noticed that if I put a connected socket in my cupboard next to 2 other wifi devices (watt meter clamps) and my coordinator, the connected socket bugs when I activate the switch and crashes Zigbee2mqtt.

However, if the connected socket is far from this poster, it works perfectly.

Do you think there may be a story of saturation in a restricted environment?

I had to update zigbee2mqqt on 5 different versions and it still crashes.

Do you have any solutions ?

Good day

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20221226

### Adapter

SONOFF-ZB Dongle-P

### Setup

Pi4

**Comment by mrmaximas** [comment]
what zigbee channel are you using? 
what wifi channel are you using?

**Comment by Alexofhiswalnut** [comment]
I use 5Ghz wifi only. I am on channel 11 in Zigbee

**Comment by Alexofhiswalnut** [comment]
My clamp wattmeters use zigbee and other 5ghz wifi wireless devices
