### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by incub77** [Koenkk/zigbee2mqtt#2229]
# Bug Report
## What happened
I found an error in my hass.io/zigbee2mqtt logs, with the request to open an issue here.
Both hassio and zigbee2mqtt are the latest versions. 

https://pastebin.com/yBtuGg1S

## What did you expect to happen
Nothing, just following the request. Haven't noticed anything not working yet.

## How to reproduce it (minimal and precise)
I have no clue :)

## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
Thanks for reporting, this has already been fixed in the latest-dev.
