### ISSUE TITLE
Issue with TuYa iH-F8260 support

### ISSUE THREAD

**Issue by vinodmishra** [Koenkk/zigbee2mqtt#22312]
### What happened?

Support was added as part of this issue. https://github.com/Koenkk/zigbee2mqtt/issues/21172
However it was added as a variant for the battery powered version while this device has no battery so Zigbee2mqtt log is full of errors related to ZCL commands 

error 2024-04-24 03:19:09Failed to configure '0xb0c7defffe7e90c4', attempt 1 (Error: ZCL command 0xb0c7defffe7e90c4/1 genPowerCfg.read(["batteryVoltage","batteryPercentageRemaining"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:762:22) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:404:24) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:369:13) at Configure.configure (/app/lib/extension/configure.ts:122:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
info 2024-04-24 03:19:09MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0xb0c7defffe7e90c4"},"error":"Failed to configure (ZCL command 0xb0c7defffe7e90c4/1 genPowerCfg.read(["batteryVoltage","batteryPercentageRemaining"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE'))","status":"error","transaction":"xhv48-1"}'

### What did you expect to happen?

No errors to be shown

### How to reproduce it (minimal and precise)

Just add this device to zigbee2mqtt and error shows up. To resolve it I am using the external converter at the moment.

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee USB Dongle P 

### Setup

Z2M and HA in containers

**Comment by Koenkk** [comment]
Fixed!
