### ISSUE TITLE
Deice Config Issue: measurement 'lx' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', '°F', 'K']

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#22332]
### What happened?

Entity sensor.upstairs_lux_climate_temperature (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'lx' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', '°F', 'K']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

### Zigbee2MQTT version

 1.36.1-dev commit: d9628df

### Adapter firmware version

20230922

### Adapter

Zigbee ESP32GW (Zigstar)

### Setup

HA Core on NUC Z2M Add ON

### Debug log

{"id":137,"type":"Router","ieeeAddr":"0xa4c1382c05da2078","nwkAddr":25136,"manufId":4417,"manufName":"_TZE200_rbbx5mfq","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�F�-i�F�-i�F�-i�F�-i�F�-i�F�-i�F�-i","65506":54,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZE200_rbbx5mfq","zclVersion":3,"appVersion":70,"modelId":"TS0601","powerSource":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-903893911},"lastSeen":1714290160556}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
