### ISSUE TITLE
Failing to pair Philips Hue bulb without any specific error message

### ISSUE THREAD

**Issue by seaside1** [Koenkk/zigbee2mqtt#2234]
I recently bought a couple of Philips hue. I have one left which I cannot get to pair:

`info  2019-10-30T17:05:24: Accepting joining non-banned device '0x00178801037064ab'
info  2019-10-30T17:05:24: Starting interview of 'huecolor10'
info  2019-10-30T17:05:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"huecolor10"}}'
info  2019-10-30T17:05:24: Accepting joining non-banned device '0x00178801037064ab'
debug 2019-10-30T17:05:24: Device 'huecolor10' announced itself
debug 2019-10-30T17:05:34: Received Zigbee message from 'huecolor10', type 'readResponse', cluster 'genBasic', data '{"modelId":"LCT015","manufacturerName":"Philips","powerSource":1}' from endpoint 11 with groupID 0
debug 2019-10-30T17:05:34: Received Zigbee message from 'huecolor10', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1,"appVersion":2,"stackVersion":1}' from endpoint 11 with groupID 0
error 2019-10-30T17:05:44: Failed to interview 'huecolor10', device has not successfully been paired
info  2019-10-30T17:05:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendly_name":"huecolor10"}}'
`

## Debug Info
zigbee2mqtt version: Latest Dev branch
CC253X firmware version: 
oordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190223}}'

**Comment by Koenkk** [comment]
- Can you try to re-pair again?
- If that fails, please update to the latest firmware (https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing)
- If it still fails, please provide the log when running with `DEBUG=zigbee-herdsman:controller* npm start`.

**Comment by seaside1** [comment]
Thanks I'll try this shortly, don't want to mess with it now, due to the current halloween setup :)

**Comment by seaside1** [comment]
Thanks for the help. This worked using the latest firmware (20190608)
