### ISSUE TITLE
ROBB ROB_200-024-0 battery reports 200%

### ISSUE THREAD

**Issue by zmstr** [Koenkk/zigbee2mqtt#22348]
### What happened?

I have two ROB_200-024-0 remotes which both reports a battery level of 200%
![Screenshot_20240429_143030_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/46542416/7983a2ee-a4db-4640-a213-597f4ac6471c)

### What did you expect to happen?

Battery level cannot exceed 100%

### How to reproduce it (minimal and precise)

Add new device and by default it reports 200%

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20210120

### Adapter

Sonoff 3.0 dongle zStack3x0

### Setup

As home assistant addon on rpi4

### Debug log

If needed I will provide but for now it looks like the same issue as https://github.com/Koenkk/zigbee2mqtt/issues/15767

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
