### ISSUE TITLE
TRADFRI bulb E27 WW 806lm

### ISSUE THREAD

**Issue by legolas0802** [Koenkk/zigbee2mqtt#2235]
I paired the lamp but I find myself with the following error in the log:

10/30/2019, 6:42:33 PM Device with modelID 'TRADFRI bulb E27 WW 806lm' is not supported.
  zigbee2mqtt:warn 10/30/2019, 6:42:33 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

can you add it?

**Comment by Koenkk** [comment]
This bulb is already supported in the dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
