### ISSUE TITLE
[Feature request]: Allow mqtt topics to end with number only level

### ISSUE THREAD

**Issue by magmilo** [Koenkk/zigbee2mqtt#22352]
### Is your feature request related to a problem? Please describe

I have set up a zigbee2mqtt node and would like to be able to configure topics that end with a device id. This is impossible, as zigbee2mqtt disallows topics to end on a string of numbers without any characters

### Describe the solution you'd like

Numbers should be allowed as the last characters in the topic string. It complies with mqtt specifications

### Describe alternatives you've considered

I'm currently adding a specific character at the end of my topic names

### Additional context

none

**Comment by LaurentChardin** [comment]
Can you provide some examples of what you are trying to do ?
