### ISSUE TITLE
Doesn't work function to change friendly name in mobile app and mobile browser 

### ISSUE THREAD

**Issue by zvezdochet2004** [Koenkk/zigbee2mqtt#22385]
![Screenshot_2024-05-02-02-17-07-547_io homeassistant companion android-edit](https://github.com/Koenkk/zigbee2mqtt/assets/78306956/86150adc-bfae-4977-9513-495aa50a6e05)
![Screenshot_2024-05-02-02-09-18-038_io homeassistant companion android-edit](https://github.com/Koenkk/zigbee2mqtt/assets/78306956/990294a7-2842-4d6e-95b2-0143e465c97b)
### What happened?

The button to change friendly name has disappeared in the mobile app and mobile version browser Chrome (OS Android)

### How to reproduce it (minimal and precise)

Open the device panel or device card

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

20210813

### Adapter

zStack3x0

### Setup

Addon in home assistant supervised

**Comment by tsloms** [comment]
Same problem here

**Comment by Milinator** [comment]
Same here

**Comment by jstaro** [comment]
Likewise, in the desktop version, you can no longer set "Description".

**Comment by timwnl** [comment]
Same issue here in iOS safari browsers, running in docker. Works fine in desktop browsers

**Comment by Koenkk** [comment]
@nurikk could you check this?

**Comment by serlinGi** [comment]
with android phone this feature rewards you by placing the phone horizontally

**Comment by TheRealWaldo** [comment]
The same is occurring in the Home Assistant application.

**Comment by Milinator** [comment]
> The same is occurring in the Home Assistant application.

Just found out: If you put your phone into horizontal mode the edit button appears. Strange because that wasn't the case before this update and I don't understand why that'd be a better approach. It worked like this.

**Comment by TheRealWaldo** [comment]
Also note: the 'also rename home assistant' switch is gone on both mobile AND web.

**Comment by Koenkk** [comment]
> Also note: the 'also rename home assistant' switch is gone on both mobile AND web.

This has already been fixed in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
