### ISSUE TITLE
Update Home Assistant entity ID is missing

### ISSUE THREAD

**Issue by rhug123** [Koenkk/zigbee2mqtt#22384]
### What happened?

When editing a name of a device, in the previous version it included a toggle to change the entity id as well.

### What did you expect to happen?

The toggle to be included when renaming a device

### How to reproduce it (minimal and precise)

Go to rename a device and there should be no toggle. See link below for example.
https://community.home-assistant.io/t/force-entity-id-update-for-discovered-entities/227167

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

0

### Adapter

Sonoff Zigbee Stick E

### Setup

Homeassistant in VM

**Comment by prokudin07** [comment]
+1
in mobile version absent "Rename device"

**Comment by bilfive** [comment]
The same problem. I have updated one instance.. And one not. At 1.36.1 this:
<img width="960" alt="2024-05-02_023753" src="https://github.com/Koenkk/zigbee2mqtt/assets/131676092/d141916a-d956-48c7-83f8-a6554a8f457d">
and now at 1.37.0 only this:
<img width="960" alt="2024-05-02_023815" src="https://github.com/Koenkk/zigbee2mqtt/assets/131676092/2c3f4810-42cc-4e55-8c7e-38d03276360d">

**Comment by harvindhillon** [comment]
I just did a quick test. I added a new device and renamed it. I see that the name in HA is updated as well automatically. I renamed it again after and it updated as well.

So maybe this is now the default behaviour and kind of makes sense to me :) I like it being someone who forgets to set it

**Comment by harvindhillon** [comment]
Okay silly me, all it does it renames the device, but not the entities, apologies, yes this is an annoying bug now 🙍‍♂️

**Comment by FWeinb** [comment]
This regression was already raised in https://github.com/nurikk/zigbee2mqtt-frontend/pull/2010. Will probably be fixed in the next release.

**Comment by Korvenwin** [comment]
@FWeinb until the next release, is there any other way to setup the name in Home Assitant?

**Comment by stefangries** [comment]
@FWeinb You can manually publish a message via MQTT to trigger a rename:
https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request

**Comment by Koenkk** [comment]
Fixed by @danroc , many thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
