### ISSUE TITLE
LOG not available

### ISSUE THREAD

**Issue by Destroyer061090** [Koenkk/zigbee2mqtt#22392]
### What happened?

Updating to last z2m version I have on log page of addon following error. I have updated z2m with core version 2024.4.4 anche checked also with 2024.5.0.

Impossibile ottenere i registri del componente aggiuntivo, No systemd-journal-gatewayd Unix socket available
![IMG_4907](https://github.com/Koenkk/zigbee2mqtt/assets/126196958/e83d634a-d934-456f-a6ac-fb9a3edc026a)

### What did you expect to happen?

I expect to see the log

### Zigbee2MQTT version

1.37.0-1

### Adapter firmware version

usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220210310-if00

### Adapter

/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230220210310-if00

### Setup

Core2024.4.4 or core2024.5.0 Supervisor2024.04.4 Frontend20240404.2

### Debug log

Not available

**Comment by SchoutenHans** [comment]
Same here version 1.37.0 does not log device payloads at all when log is set to all,info,warning or error!

**Comment by mathiaswyss** [comment]
Same here, not getting any device log entries since 1.37.0 on all log levels (for both frontend and log file).

**Comment by Destroyer061090** [comment]
I guess it is a general problem for all addon logs... can you check it?

**Comment by waltzy34** [comment]
Same here, no logs for addons, zigbee is down, can't even open frontend for Z2M

**Comment by LaurentChardin** [comment]
You might want to have a look as the documentation has been updated : 
https://www.zigbee2mqtt.io/guide/usage/debug.html and particularly this one: https://www.zigbee2mqtt.io/guide/usage/debug.html#publishing-to-mqtt-and-to-frontend
