### ISSUE TITLE
1.37.0-1 caused Aqara SJCGQ11LM to report {"water_leak": null}

### ISSUE THREAD

**Issue by mojaki8286** [Koenkk/zigbee2mqtt#22391]
### What happened?

After upgrading to 1.37.0-1 my Aqara SJCGQ11LM water leak sensors started reporting NULL in the water_leak attribute. 
I have removed, rejoined, removed, rejoined and still reports NULL. 

### Zigbee2MQTT version

1.37.0-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0 Dongle Plus

### Setup

Add-on P4

**Comment by julianfs** [comment]
If you get the device to change state (either dry > wet or wet > dry), does it then display correctly?

**Comment by mojaki8286** [comment]
It just doesn't change. It just stated NULL. However, overnight it somehow reverted to "Clear" so status changed by itself.
The problem now is even if it gets in contact with water it doesn't change to "Leaking", it just stays "Clear". 

I'll remove it again from the network and rejoin it and will report back. Until then I will have to manually kick off the sump pump

**Comment by mojaki8286** [comment]
Removed it, rejoined again. Water_leak = NULL and it just doesn't change the Water_Leak attribute status at all if it gets into contact with water. So this is a problem

**Comment by mojaki8286** [comment]
> If you get the device to change state (either dry > wet or wet > dry), does it then display correctly?

Removed it from the network, rejoined. Water_Leak attribute value is NULL. This status does not change when the sensor gets in contact with water. So this is definitely something that worked prior to the update.

**Comment by mojaki8286** [comment]
Hi so this is my summary,

After numerous testing. 

Removing, rejoining, resetting the device (Aqara SJCGQ11LM), 
adding to different router (I have 3 routers + 1 coordinator in my house). 
Restoring to the previous zigbee2mqtt version 1.36.1-1.
Restoring to hass core_2024.4.1. 

I got this to work. The water_leak attribute initially stated NULL, and would not change at all even if dumped into water.
All of a sudden it worked and changed from NULL to Leaking. Weird.

It took a day of testing but eventually came right.

**Comment by stigvi** [comment]
> Hi so this is my summary,
> 
> After numerous testing.
> 
> Removing, rejoining, resetting the device (Aqara SJCGQ11LM), adding to different router (I have 3 routers + 1 coordinator in my house). Restoring to the previous zigbee2mqtt version 1.36.1-1. Restoring to hass core_2024.4.1.
> 
> I got this to work. The water_leak attribute initially stated NULL, and would not change at all even if dumped into water. All of a sudden it worked and changed from NULL to Leaking. Weird.
> 
> It took a day of testing but eventually came right.

Do I understand you right that you got it working when you restored zigbee2mqtt to 1.36.1 and it is not working on 1.37.0?

**Comment by AntoineGS** [comment]
I also had to revert to 1.36.1 as all four of my SJCGQ11LM sensors stopped working on my Multi Pan SkyConnect.

**Comment by RezzZ** [comment]
I had a similar issue with my [aquara water leak sensors](https://www.zigbee2mqtt.io/devices/SJCGQ11LM.html#aqara-sjcgq11lm). Battery Low and Leak sensors were both NULL (messing up my offline devices report in homeassistant).
I forced a leak detection on one of them and both sensors are updated now. I'll do the same with my other 4 sensors and hopes this will be the end of the NULL values.

update: 2 weeks later and still all sensors available.

**Comment by silentroach** [comment]
Same for me with latest z2m

```json
{
    "battery": 100,
    "battery_low": null,
    "device_temperature": 25,
    "last_seen": "2025-12-03T20:08:48.668Z",
    "linkquality": 105,
    "power_outage_count": 8,
    "state": "OFF",
    "tamper": null,
    "update": {
        "installed_version": -1,
        "latest_version": -1,
        "state": null
    },
    "voltage": 3015,
    "water_leak": null
}
```
