### ISSUE TITLE
 4512707 Namron lost support

### ISSUE THREAD

**Issue by tore1980** [Koenkk/zigbee2mqtt#22400]
### What happened?

4512707 Namron lost support. The device has been working for some years.

### What did you expect to happen?

4512707 Namron support

### How to reproduce it (minimal and precise)

Update Z2m to 1.37.0-1 from 1.36.1-1 and updated serial configuration to "adapter: ember"

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

7.4.2

### Adapter

Sonoff 

### Setup

X86

**Comment by tore1980** [comment]
4512707 Namron  working with Z2M version 1.36.1-1, using Iluminize 511.10 converter. Newer Z2M versions has removed the converter.
https://www.elektroimportoren.no/namron-zigbee-5-kanal-led-kontroller/4512707/Product.html
![image](https://github.com/user-attachments/assets/8a484624-725e-4b09-b8cd-c86152d40fb5)

**Comment by tore1980** [comment]
![image](https://github.com/user-attachments/assets/45e455a1-9c05-411a-a34f-c83221fd6e43)

**Comment by tore1980** [comment]
Still a problem 1.39.0-1

**Comment by Koenkk** [comment]
Added!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `4512707.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by tore1980** [comment]
Great now it works! Tnx. I have added photo, it`s my first time so hope its correct.

**Comment by bjornarfjelldal** [comment]
@tore1980 can you confirm color and white balance control is working on this model? On the model page on z2m it does not say so, but the illuminaze one does
