### ISSUE TITLE
Z2M crash after i made restart

### ISSUE THREAD

**Issue by mihaitaiosub** [Koenkk/zigbee2mqtt#22406]
### What happened?

With version: 1.37.0-1,if i hit restart zigbee2mqtt bridge button,all mqtt devices became unavailable.the only solution to return to normal is to shut down HA(not restart but shutdown).After downgrade to 1.36.1 version.the problem disapear

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

20210120

### Adapter

zStack3x0 20210120

### Setup

add-on

**Comment by oliversweb** [comment]
Same happened to me, downgraded to 1.36 to get things working again. The error was 502 when trying to start the add on.
