### ISSUE TITLE
TypeError when trying to remove unconnected device.

### ISSUE THREAD

**Issue by TilmanK** [Koenkk/zigbee2mqtt#2241]
#Bug Report
## What happened
I tried to remove a device from zigbee2mqtt, that i unplugged from power (an Osram SmartPlug). Therefore, I've sent an MQTT message to zigbee2mqtt/bridge/config/remove with the device id. (Did this trough zigbee2mqtt assistant). Can be reproduced by sending mqtt message with MQTT.fx, even after restarting zigbee2mqtt.

## What did you expect to happen
Device is removed, even if not reachable.

## How to reproduce it (minimal and precise)
See above

## Debug Info
zigbee2mqtt version: latest dev from today (commit 7669682)
CC253X firmware version: {"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20190425}}

`Oct 31 17:38:04 NAS-Serenity npm[24976]: #033[34mzigbee2mqtt:debug#033[39m 2019-10-31T16:38:04: Received MQTT message on 'zigbee2mqtt/bridge/config/remove' with data '0x7cb03eaa0a012550'
Oct 31 17:38:04 NAS-Serenity npm[24976]: #033[31mzigbee2mqtt:error#033[39m 2019-10-31T16:38:04: Failed to call 'BridgeConfig' 'onMQTTMessage' (TypeError: Cannot read property 'settings' of null
Oct 31 17:38:04 NAS-Serenity npm[24976]:     at BridgeConfig.removeOrBan (/opt/zigbee2mqtt/lib/extension/bridgeConfig.js:245:72)
Oct 31 17:38:04 NAS-Serenity npm[24976]:     at BridgeConfig.remove (/opt/zigbee2mqtt/lib/extension/bridgeConfig.js:218:20)
Oct 31 17:38:04 NAS-Serenity npm[24976]:     at BridgeConfig.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/bridgeConfig.js:269:44)
Oct 31 17:38:04 NAS-Serenity npm[24976]:     at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:320:44)
Oct 31 17:38:04 NAS-Serenity npm[24976]:     at process._tickCallback (internal/process/next_tick.js:68:7))`

**Comment by Koenkk** [comment]
It looks that the issue is that the device is not in `configuration.yaml` anymore, is this the case? How can I reproduce this error?

**Comment by TilmanK** [comment]
Hi Koen,

yes, that's what I did, sorry, wasn't clear to me in the first place. I just reproduced the issue with an OSRAM SmartPlug:

1. Pair the plug.
2. Unplug the plug so that it can't be reached anymore.
3. Try to remove it via MQTT message to zigbee2mqtt/bridge/config/remove (This fails - I don't know if this step is actually necessary).
4. Remove it from configuration.yaml and restart. (The device is then still reported by zigbee2mqtt/bridge/config/devices)
5. Try to remove it again with a MQTT message.

Step 5 will then produce the TypeError.

I can't figure out, why the device will still be shown in zigbee2mqtt/bridge/config/devices. Also, the device is still in database.db.

Best Regards,
Tilman

**Comment by Koenkk** [comment]
- I added an extra check which prevents the exception
- I've added a `force_remove` option, see https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/mqtt_topics_and_message_structure.md#zigbee2mqttbridgeconfigremove

**Comment by carldebilly** [comment]
Oohh I'll add this feature to Zigbee2mqtt Assistant!

**Comment by james-fry** [comment]
Force remove used to exist but [it was taken out of Z2M.](https://github.com/Koenkk/zigbee2mqtt/issues/2029#issuecomment-535261250)
Is this a reversal of that decision? Or is this a new implementation that does more?
I used to use it all the time as non-powered devices tend not to respond to removal request.
Also there is the OP use case where a powered device was disconnected.

In summary its good that force removal is back as it allows users to maintain a clean DB.
The only possible problem is where a device thinks its still paired and was force removed. What will happen in that use case?

**Comment by Koenkk** [comment]
The current implementation does the same, but now it is explicit (separated command).

> In summary its good that force removal is back as it allows users to maintain a clean DB.
> The only possible problem is where a device thinks its still paired and was force removed. What will happen in that use case?

Force remove only removes it from database, so it still communicates with the network. It's explained here: https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/mqtt_topics_and_message_structure.md#zigbee2mqttbridgeconfigremove

**Comment by james-fry** [comment]
Thanks for the explanation, @Koenkk
