### ISSUE TITLE
"last_seen" is still part of MQTT message even when disabled

### ISSUE THREAD

**Issue by jamesmyatt** [Koenkk/zigbee2mqtt#22428]
### What happened?

I previously had "last_seen" enabled. However, this was bloating the HA database, so I disabled it again. However, it's still being reported in latest the MQTT messages as `last_seen: '2024-04-26T16:32:40.187Z'`, which is the time that I disabled it again.

### What did you expect to happen?

"last_seen" attribute removed when disabled, rather than retaining the last value.

### How to reproduce it (minimal and precise)

1. Set "last seen" to "ISO_8601"
2. Save, restart or reload config
3. Set "last seen" to "disable"
4. Save, restart or reload config
5. Observe MQTT messages

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

20230507

### Adapter

Sonoff USB

### Setup

Docker container

**Comment by jamesmyatt** [comment]
I have a separate issue that the last seen entities aren't removed from HA, but I think this is an HA issue since the discovery topics are missing.

**Comment by jchristianj** [comment]
Same issue here. Had enabled the last seen option, but my HA database became too large, so I disabled it. Any ZigBee device which had it once enabled, still has the last_seen in the state message.
Devices, which have been added after deactivation, do not have the last_seen information in the message.

Device which has been in network during last seen enable / disable:
`{
    "child_lock": "UNLOCK",
    "current": 0,
    "energy": 135.47,
    "indicator_mode": "off/on",
    "last_seen": "2024-04-23T09:01:07+02:00",
    "linkquality": 240,
    "power": 0,
    "power_outage_memory": "restore",
    "state": "ON",
    "update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "voltage": 225,
    "update_available": null
}`

Device which has been added after last seen enable / disable:
`{
    "child_lock": "LOCK",
    "countdown": 0,
    "current": 0,
    "energy": 4.04,
    "indicator_mode": "off/on",
    "linkquality": 140,
    "power": 0,
    "power_outage_memory": "off",
    "state": "ON",
    "update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "voltage": 227,
    "update_available": null
}`

**Comment by jamesmyatt** [comment]
This still affects me on v1.40.2.

**Comment by jamesmyatt** [comment]
This still affects v1.42.0.

**Comment by jamesmyatt** [comment]
@Koenkk any chance of including this in v2?

**Comment by Koenkk** [comment]
Did the `last_seen` end up in your `data/state.json` file? If yes, is it fixed after manually removing the entries from there?

**Comment by jamesmyatt** [comment]
Looks like it is in `data/state.json` and removing it removes it from the mqtt messages. But I think that the HA discovery has also been updated to not import all of the mqtt attributes as HA attributes, which fixes the main issue.

**Comment by jamesmyatt** [comment]
The confusing thing is that the Home Assistant entities aren't deleted but the discovery messages are gone :shrug:

**Comment by mundschenk-at** [comment]
@jamesmyatt That's a HA thing, as the discovery messages might be gone by accident, and they would not want to delete your data in that case.

**Comment by jamesmyatt** [comment]
> @jamesmyatt That's a HA thing, as the discovery messages might be gone by accident, and they would not want to delete your data in that case.

I can’t even manually delete them :shrug:

**Comment by mundschenk-at** [comment]
Did you try reloading the MQTT integration?

**Comment by h3llrais3r** [comment]
All the last_seen sensors in home assistant as disabled by default. 
Any idea how can they be removed?
