### ISSUE TITLE
Sonoff Dongle E - flashed wrong firmware (230400 baud)

### ISSUE THREAD

**Issue by jchristianj** [Koenkk/zigbee2mqtt#22430]
### What happened?

Hi, I need urgent help. It is not directly related to z2m, but I wanted tu try the new ember driver and accidentially flashed my dongle-e with here: https://darkxst.github.io/silabs-firmware-builder/
I used the firmware ncp-uart-hw-v7.4.2.0-zbdonglee-230400.gbl and it is not working. I can't go back to another firmware, as the dongle is not recognized by the darkxst web flasher. 
Is it bricked now, or is there a way to go flash the correct firmware.
Thanks in advance. 

### What did you expect to happen?

230400 would work?

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

7.4.2.

### Adapter

ZDongle-E

### Setup

z2m in LXC

### Debug log

none

**Comment by LDprg** [comment]
I had the same issue. Try flashing with python version of the flasher. If this doesn't work you may try pressing the boot button twice and flashing afterwards.

**Comment by litecross91** [comment]
Try this:
https://www.youtube.com/watch?v=BU9ha0Uaduc

**Comment by jchristianj** [comment]
Ok, thanks a lot, I'll check your proposals and let you know.
In the meantime at least I have the dongle up and running in z2m. Needed to add a parameter baudrate: 230400 and I switched over to ember. Seems to work fine.

**Comment by jchristianj** [comment]
> Try this: https://www.youtube.com/watch?v=BU9ha0Uaduc

Did it. And worked well. Stick is recognized by web flasher again, and works under z2m with default baud rate of 115200.

Thanks a lot for your support!
