### ISSUE TITLE
Z2M Frontend ist empty - Devices still connected and working

### ISSUE THREAD

**Issue by errormastern** [Koenkk/zigbee2mqtt#22434]
### What happened?

After a restart the frontend no longer shows any devices or configuration. 
In background all devices are still responding and reporting their state, etc..  

I updated the adapter short before to newest firmware, updated zigbee2mqtt and changed driver to ember. 
After that everything was fine, up an running like a charm. 

Things stopped working after machine was stopped unplanned because the power supply was temporarily unavailable

Frontend now looks like this:

<img width="1436" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/156222570/aa8b9728-daa5-476a-bebd-ce751352b045">

<img width="1436" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/156222570/71b4a68f-7edd-4b05-9f94-9a43fc265123">

Tried several times of restart, revert to previous z2m version. Nothing helped. In the logs I can't see anything strange - but I'm no expert. 

Any chance to get this back running?

### What did you expect to happen?

Frontend shows devices and configuration

### How to reproduce it (minimal and precise)

The machine was stopped unplanned because the power supply was temporarily unavailable.

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

7.4.2.0

### Adapter

Sonoff Dongle E

### Setup

Homeassistant running on x86 with Z2M Integration

### Debug log

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15204945/log.log)

**Comment by flyer331** [comment]
Hi !
I got the same problem 2 weeks ago.
Finally, I found a solution this morning after many tries like :

- data backup import
- delete mosquito and Z2M plugins and all directories
- modified many cache options in the Z2M configuration.yaml file 
- Sonoff dongle E firmware changes (I tried all FW from 7.x.x up to the latest)

and this morning I tried to delete all lines concerning devices only.

This action recreated database.db file but I lost all friendly names, so I imported the latest backup of configation.yaml (only lines of devices) and it worked.

Juste one tip, do not click here otherwise you will loose everything again ... -> 
![Z2M_do_not_click](https://github.com/Koenkk/zigbee2mqtt/assets/123252254/4ec5dbc4-d458-46dd-87d6-4fd86edf63ea)

If you got the latest firmware on the dongle (7.4.1), do not forget to change the adapter option : 
`serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_xxxxxxxxxxxxxx-yyyy
  adapter: ember`

Hope it will help you !

Damien.

**Comment by errormastern** [comment]
Hey Damien,

Thanks for your response. It's great to have a solution approach.

If I understood you correctly, you've performed the following steps:

1. Removed all devices from the configuration.yaml
2. Restarted - DB gets regenerated
3. Added devices again from the backup of configuration.yaml
4. Restarted, and devices are back

Is that correct?

> Juste one tip, do not click here otherwise you will loose everything again ... ->

Damn, you're probably right with your tip. I might have actually clicked that button the other day :o/ The issue likely arose on the next restart.

**Comment by BIGede** [comment]
I also gave my Dongel-E a new firmware and had exactly the same problem. Even after a downgrade to the old firmware, nothing has changed. 

I did not understand where the lines should be deleted so that the database is rebuilt. I don't want to break something like this with 90 devices :)

**Comment by errormastern** [comment]
I'm so glad, I got it running again. 
Thanks @flyer331, I got onto it through your hint and solution approach.

The button in the German translation has the label "Bild lokalisieren" (Translate image), which led to all 55 devices receiving an entry in the configuration with their images as Base64 png. 

I removed the icon: entries from all devices in configuration.yaml. Upon the next start of zigbee2mqtt, everything was back to normal.

@BIGede 
If you haven't icon entries for all or many of your devices, it seems to be another problem. After Flashing and Update I'd first no problems..

**Comment by BIGede** [comment]
No, I actually have exactly the same problem. So you have completely deleted the Icon: line and restarted Z2M?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/132294248/75323e69-6073-41d2-a224-43ca06a0ad90)

**Comment by errormastern** [comment]
Yes, exactly .. Delete all icon entries and restart.

**Comment by BIGede** [comment]
It works. Thanks for the help.

**Comment by hksthff** [comment]
Alternative: simply download your latest HA Backup and navigate to the file "homeassistant.tar.gz" > data > zigbee2mqtt > configuration.yaml -> copy & paste it in the file editor inside HA -> save & restart zigbee2mqtt
