### ISSUE TITLE
There isn't a way to reach zigbee2mqtt.io home page

### ISSUE THREAD

**Issue by RyuzakiKK** [Koenkk/zigbee2mqtt#2245]
Issues are disabled in the zigbee2mqtt.io repo, so I'm posting this here.

Problem:
If you open a page in the site zigbee2mqtt.io you are unable to reach its home page because it's not linked anywhere.

Steps to reproduce:
Go to https://www.zigbee2mqtt.io/how_tos/how_to_secure_network.html

Expected result:
A link to https://www.zigbee2mqtt.io somewhere in that page.
In the header the big `zigbee2mqtt.io` title is not clickable and `View on Github` points to https://github.com/Koenkk/zigbee2mqtt.io
In the footer the clickable `zigbee2mqtt.io` points instead to https://github.com/Koenkk/zigbee2mqtt.io

**Comment by carldebilly** [comment]
I agree it's a problem I often have while navigating on this site.

**Comment by Koenkk** [comment]
It would be great if someone with Jekyll knowledge can help improving the site.

**Comment by LukeHandle** [comment]
Never touched Jekyll, but appears to be a case of overriding the the theme - copy in the original template and update the needed bits:
https://github.com/pages-themes/cayman#layouts

**Comment by Koenkk** [comment]
Fixed, you can now click on *zigbeem2qtt.io* to navigate back to the home page.
