### ISSUE TITLE
MiBoxer FUT039Z broken on Z2M v1.37.0

### ISSUE THREAD

**Issue by ich777** [Koenkk/zigbee2mqtt#22450]
### What happened?

Since the last Z2M Docker update my MiBoxer FUT039Z are not usable anymore from HomeAssistant, it works fine from the Z2M WebInterface.

Here a screenshot from Z2M:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/28066518/900aac1b-900e-4fdf-bf53-343fccb92094)

And here what is reported in HA:
![grafik](https://github.com/Koenkk/zigbee2mqtt/assets/28066518/6bc2013c-9dd3-45be-879b-5252424b8e25)

Maybe I did something wrong but I just came home and saw that the host where Z2M is running on pulled an update.
Everything else is working just fine.

EDIT: After going back to version 1.36.1 everything is working again.

### What did you expect to happen?

Control the light from within HomeAssistant

### How to reproduce it (minimal and precise)

Update to latest Z2M version.

### Zigbee2MQTT version

1.37.0 commit: 46f34c8

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 TI CC2652P + CP2102N

### Setup

HomeAssitant Core on Debian

**Comment by ich777** [comment]
Same as #22404

**Comment by Koenkk** [comment]
Are you running at least HA `2024.4`

**Comment by ich777** [comment]
Thank you, issue solved!
