### ISSUE TITLE
Unavailable entities from operational device

### ISSUE THREAD

**Issue by dankarization** [Koenkk/zigbee2mqtt#22460]
### What happened?

I have a few devices throughout the house with this problem:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/26330178/3c77e43a-88d3-4faf-aa77-b3f2f47587b0)

1) They are fully operational from Z2M frontend, have more than good coverage (first 4 in the list below are directly under the coordinator in the same room with it), report nicely and had no such problems before as i believe.
2) They have several entities, but some of them (of course, by the will of fate, not the ones I really need) are operational from home assistant
3) All entities were working lately, and just became unavailable for some reason 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/26330178/aa6b1add-d087-499c-b507-f5eab0c484da)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/26330178/1b293d39-1e77-4480-9473-cf24794a0790)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/26330178/b7c1f230-a752-452f-ba42-a920fd2550dc)

### How to reproduce it (minimal and precise)

Idk, maybe turn off MQTT addon for some time.

### Zigbee2MQTT version

1.37.0-1

### Adapter firmware version

20240315

### Adapter

TZT HamGeek POE (ZigStarGW) with cc2652p2 chip

### Setup

Home Assistant OS with 2 addons for each floor and coordinator

### Debug log

In these logs look for problems with devices:
- Island LED
- Island floor
- Подсветка кухня шкаф
- Kitchen. Working light
- Led light. Sauna
- Wine cellar chandelier (it's a group of 3 lights: Люстра 1, Люстра 2, Люстра 3)

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15212201/log.log)
[log1.log](https://github.com/Koenkk/zigbee2mqtt/files/15212202/log1.log)
[log2.log](https://github.com/Koenkk/zigbee2mqtt/files/15212215/log2.log)

Failed to ping for all '(отключен)' ones is _ok'ish_ as they are physically disconnected from power.

log1.log file, line 7892, I see MQTT connection problems that were quickly resolved by itself. Aproximately at this time entities I talk about became unavailable and never came back (but almost all others are ok)

System restart (full system, not only HA) also does not help.

**Comment by dankarization** [comment]
UPD: restored 1.36.1-1 version backup and the problem is gone, but on the 1.36.1-1 i have a problem with brightness:1000 as many other people, why I updated to 1.37.0-1

**Comment by cloudbr34k84** [comment]
Yep same problem

**Comment by Koenkk** [comment]
What home assistant version are you using? Make sure to use at least 2024.4 as mentioned in the Z2M release notes.

**Comment by craigwitter** [comment]
Hasos 2024.5.1 here.

Thanks,
Craig

**Comment by cloudbr34k84** [comment]
I'm running beta

**Comment by craigwitter** [comment]
@Koenkk does this help? https://github.com/home-assistant/core/issues/116914

**Comment by Koenkk** [comment]
@craigwitter that's not about entities becoming unavailable as far as I can see

**Comment by popy2k14** [comment]
Use EMQX broker instead of mosquito.
See here: https://github.com/Koenkk/zigbee2mqtt/issues/18862

**Comment by MarcoGos** [comment]
@popy2k14 Thanks, that really helped. I used to use Mosquitto and had the same issue as described here. I swapped Mosquitto with EMQX, now a reboot of home assistant always restores all entities and no entities become unavailable anymore.

**Comment by popy2k14** [comment]
@MarcoGos You're welcome. Nice that it also solved the issue for you. Running EMQX for over a month now without a issue.

**Comment by popy2k14** [comment]
Running EMQX for 6 months now without facing this issue ever.
But i think this is not solved: https://github.com/Koenkk/zigbee2mqtt/issues/18862

PS.: Not tested mosquitto myself again

**Comment by MarcoGos** [comment]
@popy2k14 I can second that. I use EMQX for a couple of months now without this issue, where as using mosquitto gave me this issue often.

**Comment by dankarization** [comment]
I am still running mosquitto, on dozen different Zigbee coordinators and Z2M 1.39 and higher. The one exact device from my screenshot is connected to zStack3x0 with firmware 20240315. Problem is gone.

**Comment by popy2k14** [comment]
@MarcoGos Did you tried recent versions of Z2M and mosquitto?
Maybe issue is solved?
I think the right place to discuss further is this issue: https://github.com/Koenkk/zigbee2mqtt/issues/18862
