### ISSUE TITLE
Aurora Lighting AU-A1ZBDSS double socket power reading stale

### ISSUE THREAD

**Issue by jwheare** [Koenkk/zigbee2mqtt#22479]
### What happened?

Running as an add-on on Home Assistant Yellow.

I updated to 1.37.0-1 and the power (W) value for all of my Aurora double sockets got stuck and stopped reporting changed values. The values were still present in the state but unchanging. No errors in logs. Rolling back to 1.36.1-1 fixed the problem.

Device: https://www.zigbee2mqtt.io/devices/AU-A1ZBDSS.html

### Zigbee2MQTT version

1.37.0-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Home Assistant Yellow - Silicon Labs MGM210P Mighty Gecko Module

### Setup

Add-on on Home Assistant Yellow

**Comment by julianfs** [comment]
Fixed in #22464
