### ISSUE TITLE
[New device support]: Generic Zigbee 3.0 "Mini Smart Switch"

### ISSUE THREAD

**Issue by Shlokp** [Koenkk/zigbee2mqtt#22485]
### Link

https://www.aliexpress.com/item/1005006379052047.html?spm=a2g0o.order_list.order_list_main.4.1d331802SE1mgA

### Database entry

{"id":7,"type":"Unknown","ieeeAddr":"0x70b3d52b600aa863","nwkAddr":36884,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2,"switchType":0}},"genBasic":{"attributes":{"appVersion":100}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":100,"interviewCompleted":false,"meta":{},"lastSeen":1714999281469}

### Comments

This device appears to be an no-brand version of Aubess TMZ02 (Model WHD02 - https://www.zigbee2mqtt.io/devices/WHD02.html) however I am unable to get it to be identified.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/35976544/5618cb11-6be3-44b3-9c77-95a899a5e8d7)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/35976544/4333c04c-a31c-4605-82a6-08d4420b0c03)

On trying to pair the device, the following error comes up "interview failed because could not get node descriptor"
Then the device shows up 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/35976544/891f36e7-ff6c-441d-84ac-4d083ecf4eed)

Ive had a read of similar issues for the official Aubess Mini Smart Switch (https://github.com/Koenkk/zigbee2mqtt/issues/13929), however in my instance, there is no model number or manufacturer. 

I have tried adding a custom external definition but I cannot get it to assign.

Im using a Sonoff Zigbee Dongle P, Z2M version 1.37.0
I have other zigbee devices which work as expected.

I appreciate any help provided.

### External definition

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [{ieee_address: '0x70b3d52b600aa863'}],   // WARNING! Change this ieee_address for yours ieee_address!!!!
    description: 'Wall switch module',
    toZigbee: extend.switch().toZigbee.concat([tz.moes_power_on_behavior, tz.tuya_switch_type]),
    fromZigbee: extend.switch().fromZigbee.concat([fz.moes_power_on_behavior, fz.tuya_switch_type]),
    exposes: extend.switch().exposes.concat([e.power_on_behavior(), e.switch_type_2()]),
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);},
};

module.exports = definition;
```

**Comment by Shlokp** [comment]
Managed to get it working!

For those with similar issues, despite the manufactuer name and model not showing, when using the Dev console, it did indeed verify the product - "modelId":"TS0001","hwVersion":2,"manufacturerName":"_TZ3000_fdxihpp7"

Managed to fix it by making a custom external definition with the following code - https://gist.github.com/Koenkk/550c7c2b486173a8c019bc8ba764fad8

Even though this version doesnt support the power monitoring, the rest of the settings work as expected

**Comment by mahnunchik** [comment]
Related https://github.com/romasku/tuya-zigbee-switch/issues/517
