### ISSUE TITLE
[New device support]: COOLO EWelink Zigbee smart LED

### ISSUE THREAD

**Issue by beavis6511** [Koenkk/zigbee2mqtt#22493]
### Link

https://a.aliexpress.com/_EIHAZ0b

### Database entry

No entry

### Comments

Hello
I've tried to pair this LED but it does not work. Impossible to do the pairing.
Thanks

### External definition

```shell
No def
```

**Comment by beavis6511** [comment]
I've fixed my problem

**Comment by CarlosGtrz** [comment]
How did you get them to pair to zigbee2mqtt?

**Comment by HectorJRL** [comment]
It'd be nice if you'd share the fix.
