### ISSUE TITLE
Entity ID name does not change

### ISSUE THREAD

**Issue by m-landowski** [Koenkk/zigbee2mqtt#22537]
### What happened?

I would like to change the Entity ID for the newly added device in Z2m (HA add-on).

IN z2m set: 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/12528895/e9acb7cc-2131-4dc4-bf51-a1df504ad07a)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/12528895/21776bb4-b6b4-4dfe-be92-f4e73532f3eb)

 

### What did you expect to happen?

![image](https://github.com/Koenkk/zigbee2mqtt/assets/12528895/df91136c-28a1-4bd5-9680-62519b41a267)

### How to reproduce it (minimal and precise)

Please Add New Device in Z2M , and Set Friendly Name 

### Zigbee2MQTT version

 1.37.0

### Adapter firmware version

0x26580700

### Adapter

ConBee2/RaspBee2

### Setup

ADD On HA

**Comment by dyvyak** [comment]
same problem here. also on official android application is missing icon for renaming devices

**Comment by Koenkk** [comment]
It's fixed in https://github.com/nurikk/zigbee2mqtt-frontend/pull/2010, there will be a hotfix release in the coming days.
