### ISSUE TITLE
No more publish log messages since 1.37.0 using info log_level

### ISSUE THREAD

**Issue by roofburner** [Koenkk/zigbee2mqtt#22538]
### What happened?

I don't see any ```MQTT publish: topic``` log entries since I've upgraded to 1.37.0, using ```log_level: info```.
I see the publish messages using ```log_level: debug```.

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

???

### Adapter

Conbee2

### Setup

Docker

**Comment by maxifly** [comment]
Same for me

**Comment by roofburner** [comment]
Reference: https://github.com/Koenkk/zigbee2mqtt/issues/22063
