### ISSUE TITLE
Add device name to "failed to ping" message

### ISSUE THREAD

**Issue by copystring** [Koenkk/zigbee2mqtt#2256]
To be a lot more useful when checking the log would be possible to add the name of the device which failed to be pinged?

Maybe:
`zigbee2mqtt:error 2019-11-02T17:22:43: Failed to ping '0x7cb03eaa00b23e45' (WeihnachtsbeleuchtungKueche)
`

instead of:
`zigbee2mqtt:error 2019-11-02T17:22:43: Failed to ping '0x7cb03eaa00b23e45'`

**Comment by Koenkk** [comment]
Implemented.

**Comment by copystring** [comment]
Thanks for the update. This works fine for pings which succeed. However failed pings still only show the address.

**Comment by Koenkk** [comment]
Can you share your log and `configuration.yaml`?

**Comment by copystring** [comment]
My bad. I just happen to have 2 devices which I did not rename and it happened to be those two appearing in the log. Sorry about that. It works good. Thanks.
