### ISSUE TITLE
Ember eventbus crashing, and the. Adapter disconnect 

### ISSUE THREAD

**Issue by BradleyFord** [Koenkk/zigbee2mqtt#22567]
### What happened?

Sent command to lights to change color via Z2M UI and then bamm this error appeared 

![Screenshot_2024-05-10-01-11-21-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Koenkk/zigbee2mqtt/assets/322815/10bdf121-136a-4802-ae13-33166785ce77)

### What did you expect to happen?

Lights to change color as normal

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

7.4.1

### Adapter

SLZB-06M   FW 2.1.8, ZB 20240408

### Setup

Proxmox

**Comment by Nerivec** [comment]
Can you confirm this with 1.37.1 and post the log file?
