### ISSUE TITLE
Restarting Home Assistant makes the dev branch crash

### ISSUE THREAD

**Issue by x99percent** [Koenkk/zigbee2mqtt#2257]
# Bug Report
## What happened
zigbee2mqtt crashes when HA is restarted

## What did you expect to happen
No crash

## How to reproduce it (minimal and precise)
Restart Home Assistant

## Debug Info
zigbee2mqtt version: docker koenkk/zigbee2mqtt:latest-dev
CC253X firmware version: 20190608, I think

```
/app/lib/extension/homeassistant.js:1104
                this.zigbee.getAllClients().forEach((device) => {
                            ^

TypeError: this.zigbee.getAllClients is not a function
    at Timeout.setTimeout [as _onTimeout] (/app/lib/extension/homeassistant.js:1104:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-02T18_27_49_319Z-debug.log
```

This is the error shown in the docker log. The error doesn't show in the log file.

**Comment by Innanazmova83** [comment]
Хуй




Получить TypeApp для Android



На 2 нояб. 2019 г., 21:35, в 21:35, x99percent <notifications@github.com> написал:п>

**Comment by Koenkk** [comment]
Did you overwite homeassistant.js via a docker volume? (Probably to add support for new devices), if so remove this, the file you are using is outdated and not compatible.

**Comment by x99percent** [comment]
I was unaware that the homeassistant.js file was included in the dev container. The instructions indicate that you just have to switch to the "-dev" label, and that's it.
