### ISSUE TITLE
After flash update to ember. Z2M configurationnot excepting ember

### ISSUE THREAD

**Issue by canedje** [Koenkk/zigbee2mqtt#22582]
### What happened?

I just flashed my Sonoff ZBDongle-E to latest 7.4.2.0 build. Using this tutorial:
https://smarthomescene.com/guides/how-to-use-ember-driver-with-efr32mg21-zigbee-adapters/?fbclid=I
wZXh0bgNhZW0CMTAAAR3p8Cy-teqA7gg_Fn2xUkTDArGSTlTZRORNU7pgXl7__Rvuf9xVL1Dgtiw_aem_ASu41kv-OnrMVTE3Y8okCTbiHubgfS9SgUDMZtypAozlPWAd-tXbooK2_XYw36NmxHlptQOmm8gjzewfoWFZGqNV

Flashing worked fine.
But after changing mij configuration file adapter to ember.
My Z2M docker didn't start up with a CRC error.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/23150947/99dfb6bd-69eb-42d4-9736-4fbe85897c7c)
I did change the adapter type back to ezsp and Z2M did start up again.
At "about" in Z2M it gives indeed EZSP instead of ember. It gives the right build version:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/23150947/03044ac3-a106-45ef-bf7a-a8760a73f2b7)

I did use: https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.3.2.0-zbdonglee-none-115200.gbl as firmware update

EDIT: after first starting up after using ezsp as adapter I did change again to ember as adapter for a trial.
Now it is starting up in ember mode????
![image](https://github.com/Koenkk/zigbee2mqtt/assets/23150947/c5c5b365-13ac-4905-8f2b-df1480acb8a4)

### What did you expect to happen?

I Expected ember as type

### How to reproduce it (minimal and precise)

See above. Just change adapter in ember instead of EZSP

### Zigbee2MQTT version

1.37.1 commit: ea39d86

### Adapter firmware version

7.4.2.0 build 0

### Adapter

Sonoff ZBDongle-E 

### Setup

Z2M as a docker under Unraid

**Comment by wastez** [comment]
I think that not the crc error was the reason why it wasn’t starting. 
In the error below a old backup file triggered the error.

**Comment by canedje** [comment]
ahhhh okey.
Thanks. It could be possible because I did make a new backup file when running as EZSP.
After that I did retry the ember adapter

**Comment by wastez** [comment]
@canedje 
The backup is stored in home folder of z2m.
In case you use it as home assistant addon it is in /config/zigbee2mqtt.

**Comment by Nerivec** [comment]
An old backup file prevents ember from starting to avoid overwriting stuff without your knowledge and gives the error you posted that the version is not supported. If you move it out of the folder, or rename/delete it, then ember should start.
_PS: A CRC error is common on start, it's just noise on the port, there is a retry mechanism just for that._

Please see https://www.zigbee2mqtt.io/guide/adapters/emberznet.html#logging-specific-to-this-stack for ember-specific logging details.
