### ISSUE TITLE
Zigbee2MQTT requires node version ^18 || ^20 || ^21, you are running v22.1.0!

### ISSUE THREAD

**Issue by matlab22** [Koenkk/zigbee2mqtt#22595]
### What happened?

I installed zigbee2mqtt on a rp4 dietpi bookworm and could not start it with npm start

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20230507

### Adapter

SONOFF ZBDongle-P

### Setup

raspberry pi 4 DietPi v9.3.0

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
