### ISSUE TITLE
Better location for device configuration documentation?

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#2259]
I was looking for some info about device configuration and had a hard time locating it, I eventually found it on https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html by searching the github repo :|

Wouldn't it make more sense to move this to the proper device page? (If so, could take a jab at it)

**Comment by Koenkk** [comment]
Yes this should definitly moved to the device page, will do this
