### ISSUE TITLE
OTA Update error

### ISSUE THREAD

**Issue by rapdSagarbe** [Koenkk/zigbee2mqtt#22606]
### What happened?

Hi, I have problems with Z2M because all attempts to update any device end in error, no matter if it is an aqara t2, an IKEA remote or a sonoff sensor. They all fail with:

2024-05-12 21:34:25Failed to check if update available for 'Conmutada' (OTA: Device didn't respond to OTA request)
2024-05-12 21:36:04Failed to check if update available for 'btn 2 Salón' (OTA: Device didn't respond to OTA request)
![imagen](https://github.com/Koenkk/zigbee2mqtt/assets/63707617/38fb18f8-f854-466a-888e-d98e338a9ce1)
![imagen](https://github.com/Koenkk/zigbee2mqtt/assets/63707617/f61ea178-7c81-4762-97b3-128e20b872ef)
![imagen](https://github.com/Koenkk/zigbee2mqtt/assets/63707617/a0af4d14-2dca-4c27-91e2-1ed4a533d0da)
![imagen](https://github.com/Koenkk/zigbee2mqtt/assets/63707617/948ab2f5-bea6-4e4a-b208-b2428142600c)

I try to take offf baterry an put again, try everthing but no way.

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20210708

### Adapter

SON OFF 3.0 P

### Setup

RPI 3 with, ad Guard and mozquito

**Comment by Nerivec** [comment]
For battery devices, you may need to press a button on the device at regular intervals to keep it awake until the update is fully started (lots of Ikea stuff requires it for example, check the docs for the devices).
