### ISSUE TITLE
[New device support]: TRADFRI bulb E12 WS candle 450lm

### ISSUE THREAD

**Issue by zpartal** [Koenkk/zigbee2mqtt#22625]
### Link

https://www.ikea.com/us/en/p/tradfri-led-bulb-e12-450-lumen-wireless-dimmable-white-spectrum-chandelier-opal-10545500/

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0x048727fffe8fec3c","nwkAddr":52175,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E12 WS candle 450lm","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64636],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":250,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":3,"stackVersion":113,"hwVersion":1,"dateCode":"20230619","swBuildId":"3.0.8","zclVersion":8,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1715626022365}

### Comments

The bulb can be added and controlled, but the manufacturer is listed as unsupported. This bulb seems to be a new variant of the E12 bulb at Ikea, their website even lists it as "new". 

The model in zigbee2mqtt, `LED2107C4`, overlaps with a model that already exists in the `zigbee-herdsman-converters`. The difference is that this new bulb is an E12, where the one in the converters is an E14. 

![bulb](https://github.com/Koenkk/zigbee2mqtt/assets/1432346/15c7bc22-d66a-4770-93af-3aeeefcb2c22)

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TRADFRI bulb E12 WS candle 450lm'],
    model: 'TRADFRI bulb E12 WS candle 450lm',
    vendor: 'IKEA of Sweden',
    description: 'Automatically generated definition',
    extend: [identify(), light({"colorTemp":{"range":[250,454]}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
