### ISSUE TITLE
Timeout Error When Configuring Device TUYA ZTH02 (temperature sensor)

### ISSUE THREAD

**Issue by JPnux** [Koenkk/zigbee2mqtt#22631]
### What happened?

An error appeared in the logs when I appaired a temperature sensor (Tuya ZTH02)

That said, the device still functions correctly in Zigbee2MQTT. The values are accurate, and the temperature displays correctly. The error does not seem to cause any malfunction.

### What did you expect to happen?

I expected the device configuration to succeed without any error.

### How to reproduce it (minimal and precise)

Put the coordinator into pairing mode.
Start the pairing process for the device.
Observe the error in the logs.

### Zigbee2MQTT version

1.37.1 commit: ea39d86

### Adapter firmware version

7.4.3 [GA]

### Adapter

SonOff Dongle Plus (E) with ember

### Setup

Docker on Raspberry Pi

### Debug log

```
Info 2024-05-14 15:36:24Succesfully interviewed '0xa4c138da187297b3'
Info 2024-05-14 15:36:24Successfully interviewed '0xa4c138da187297b3', device has successfully been paired
Info 2024-05-14 15:36:24Device '0xa4c138da187297b3' is supported, identified as: TuYa Temperature and humidity sensor (ZTH02)
Info 2024-05-14 15:36:25Configuring '0xa4c138da187297b3'

Error 2024-05-14 15:36:35Failed to configure '0xa4c138da187297b3', attempt 1 (Error: ZCL command 0xa4c138da187297b3/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed ({"target":48783,"apsFrame":{"profileId":260,"clusterId":61184,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":254},"zclSequence":159,"commandIdentifier":11} timed out after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:194:23) at EmberOneWaitress.startWaitingFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:218:50) at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:3635:64) at EmberRequestQueue.dispatch (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/requestQueue.ts:117:46))

Info 2024-05-14 15:36:35Configuring '0xa4c138da187297b3'
Info 2024-05-14 15:36:46Successfully configured '0xa4c138da187297b3'
```

**Comment by Nerivec** [comment]
Looks like the device went to sleep, failed to finish configuring, but then succeeded on retry.
If that ever happens again and you can't get it to succeed on its own, try pushing a button on the device at 2-3 seconds intervals to prevent it from going to sleep until configure is done.
