### ISSUE TITLE
MOES UFO-R11 bad battery report 

### ISSUE THREAD

**Issue by guyguy333** [Koenkk/zigbee2mqtt#22648]
### What happened?

MOES UFO-R11 reported low battery. I did change battery two times, with a 1 week interval. However, battery level is "stuck" as low battery.

### What did you expect to happen?

Battery level for MOES UFO-R11 is correctly reported.

### How to reproduce it (minimal and precise)

Wait MOES UFO-R11 has low battery, change battery and check battery level in Z2M, even after 24 hours.

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20230507

### Adapter

SONOFF

### Setup

Docker

**Comment by marianob85** [comment]
+1

Same here: 

Zigbee2MQTT version
1.36.0-dev commit: [032b9a0](https://github.com/Koenkk/zigbee2mqtt/commit/032b9a0)
Coordinator type
zStack3x0
Coordinator revision
20240315
Coordinator IEEE Address
0x00124b002f8b3f17
Frontend version
0.6.161
zigbee_herdsman_converters_version
19.8.0
zigbee_herdsman_version
0.40.0

`{"id":39,"type":"EndDevice","ieeeAddr":"0x8c65a3fffeae2096","nwkAddr":41132,"manufId":4098,"manufName":"_TZ3290_ot6ewjvmejq5ekhl","powerSource":"Battery","modelId":"TS1201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":61440,"inClusterList":[0,4,5,3,1,60672,57348,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS1201","manufacturerName":"_TZ3290_ot6ewjvmejq5ekhl","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genPowerCfg":{"attributes":{"batteryVoltage":13,"batteryPercentageRemaining":68}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b002f8b3f17","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null},{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0,"manufacturerCode":null}],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1458185820},"lastSeen":1721303120204}`
