### ISSUE TITLE
TS0013 _TZ3000_wyhuocal turns off after 2 minutes

### ISSUE THREAD

**Issue by D3vil787** [Koenkk/zigbee2mqtt#22661]
### What happened?

If the device is connected to a Home assistant, it turns off any pressed button exactly 2 minutes after turning it on.
If you disconnect the device from the Home Assisatant, it works fine.

### Zigbee2MQTT version

zha

### Adapter firmware version

20210708

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

Pi3b

**Comment by 001Tycoon** [comment]
Have you seen this? Maybe it will help
[https://github.com/Koenkk/zigbee2mqtt/issues/6138](https://github.com/Koenkk/zigbee2mqtt/issues/6138)

**Comment by D3vil787** [comment]
> Have you seen this? Maybe it will help #6138

did not help me, as well as many in the comments to this incident
