### ISSUE TITLE
Eurotronic Spirit SPZB0001 is not pairing with zigbee2mqtt

### ISSUE THREAD

**Issue by omitpi** [Koenkk/zigbee2mqtt#2268]
# Bug Report
## What happened
I wanted to pair a Eurotronic Spirit zigbee thermostat to my zigbee2mqtt network. But it doesn't pair. I reset the device and put it in Join Mode (showing "Jin" on the display).
OSRAM-Smart Plugs are well connected for example. 
Some Specs: {"version":"1.6.0","commit":"e26ad2a","coordinator":20190608,"log_level":"info","permit_join":true}
The R-Pi 3B is running openhabian as OS. 

## What did you expect to happen
That it just connects like my OSRAM-Smart Plugs already did. Seeing it to appear in the MQTT Explorer.

## How to reproduce it (minimal and precise)
It happens all the time.

## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
It might be worth trying the dev branch as it has improved pairing behaviour.

**Comment by omitpi** [comment]
@Koenkk Thanks for your answer! :-)
Do you mean the "developement firmware version" for flashing the CC253X Dongle?

**Comment by Koenkk** [comment]
No, see https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by omitpi** [comment]
Okay, I did this and it says 
{"version":"1.6.0","commit":"00bc4de","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}
but no pairing either...I already switched the Eurotronic Spirit SPZB0001 but same issue...

Do you have any more advices?

**Comment by Koenkk** [comment]
- Did you pair any other devices to zigbee2mqtt?
- Is another zigbee hub running? (so that it could pair to a different network)
- Can you share your `database.db`.

**Comment by bredzim** [comment]
I have the same problem, using coordinator firmware revision: 20190425 and using dev branch, no success with Eurotronic SPZB0001 pairing (no any message seen in debug mode log).

Other devices (Aqara, Ikea Tradfri) are working fine.

**Comment by omitpi** [comment]
> * Did you pair any other devices to zigbee2mqtt?
> * Is another zigbee hub running? (so that it could pair to a different network)
> * Can you share your `database.db`.

1) Yes two OSRAM Smart Plugs.
2) No, just one hub.
3) Like this?
 {"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e1b2a9","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1572817679,"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList"$
{"id":2,"type":"Router","ieeeAddr":"0x7cb03eaa00b1f0f8","nwkAddr":13324,"manufId":48042,"manufName":"OSRAM","powerSource":"Mains (single phase)","modelId":"Plug 01","epList":[3],"endpoints":{"3":{"profId":49246,"epId":3,"devId":16,"inCl$
{"id":4,"type":"Router","ieeeAddr":"0x7cb03eaa0a025803","nwkAddr":25459,"manufId":48042,"manufName":"OSRAM","powerSource":"Mains (single phase)","modelId":"Plug 01","epList":[3],"endpoints":{"3":{"profId":49246,"epId":3,"devId":16,"inCl$

**Comment by Koenkk** [comment]
I found some interesting information here from @allofmex 

> What you may also try is holding all three button, then a counter starts and Spz resets.

Can you try this?

**Comment by omitpi** [comment]
I tried this several times already....No success!

Is there maybe a mistake in the pairing specifications?

**Comment by bredzim** [comment]
In my case this reset solved the problem - pairing done - many thanks Koen for the hint!

**Comment by omitpi** [comment]
What did you do exactly, bredzim?

**Comment by bredzim** [comment]
I pressed three buttons (boost, minus and plus simultaneously) until the counter on the LCD has reached 10 and LCD displayed "rES". After that thermostat started to pair and after few seconds finished with success.

Try this way, maybe it is also solution for you.

**Comment by allofmex** [comment]
And please have the CC253X fresh plugged. Depending on firmware, pairing may work within the first minutes after startup only!

**Comment by rob1n** [comment]
Resetting the device (by holding all three buttons) worked for me as well, even tho I'm not on `edge`.
Thanks y'all :)

**Comment by omitpi** [comment]
Alrigthy! I am travelling this whole week, will try it when I am home next week. Thank guys, let's see if this helps! :-)

**Comment by omitpi** [comment]
Okay Guys, got this finally working with the reset...you need to stay on the three buttons till the display is turned off. :-D

Is anyone of you using this with openhab? If yes how did you define your channels? 
The "Incoming value transformation" and JSONPATH?

Thanks.

**Comment by danergo** [comment]
> And please have the CC253X fresh plugged. Depending on firmware, pairing may work within the first minutes after startup only!

Do you have any idea on what changes after some minutes in the firmware that prevents the connection of this (and maybe other) kind of devices?

**Comment by allofmex** [comment]
> ...what changes after some minutes in the firmware that prevents the connection 
I did not found a firmware parameter to configure this timeout.

To clearify: this means, only **pairing of new** (factory default) devices works for first minutes only (Stack 1.2 firmware). 
If the device was paired before and just power cycled (example Eurotronic battery replaced), it rejoins any time.

**Comment by danergo** [comment]
> I did not found a firmware parameter to configure this timeout.

Have you sniffed the ZB traffic between Eurotronic and CC253x?
Do you know what is the request from the Eurotronic that goes through after freshly replugged CC253x, but stuck if you don't replug it?

> To clearify: this means, only **pairing of new** (factory default) devices works for first minutes only (Stack 1.2 firmware).
> If the device was paired before and just power cycled (example Eurotronic battery replaced), it rejoins any time.

That's fine yes, my intention is to improve the stack 1.2 fw so we don't need to unplug/replug on new device pairing situations.

**Comment by allofmex** [comment]
> Have you sniffed the ZB traffic between Eurotronic and CC253x?

I have this with all devices. I guess it is a security function in 1.2 z-stack. The coordinator publishes network key only at beginning. 
Would like to have this changed too, but not critical. Just need to be known to users.

**Comment by s00500** [comment]
Yes cool, just had the same after I changed my network key and then it would not show up anymore, holding the 3 buttons till the rest solved the issue immediately, needs to go into the docs, then this can be closed I guess :-)
