### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by iberisoft** [Koenkk/zigbee2mqtt#2269]
I would like to know a simple question: if the payload data of MQTT messages are always in JSON format? I think so but maybe there are some rare devices generating other formats, in theory.

**Comment by nldroid** [comment]
I'm not sure what the question is but Zigbee2mqtt (and not the device ) is creating the MQTT messages. Zigbee2mqtt reads info from the device and then creates the JSON based on that.

**Comment by iberisoft** [comment]
Ah OK, it will be always JSON after passing the broker. Thank you.
