### ISSUE TITLE
Report option enabled by default all the time

### ISSUE THREAD

**Issue by drbios** [Koenkk/zigbee2mqtt#2270]
## What happened
Report option enabled by default
## What did you expect to happen
If report=false ..report option should be disabled
## How to reproduce it (minimal and precise)
In home assistant lights bulbs always report their state to groups and vice versa
## Debug Info
zigbee2mqtt version: 1.6.0 dev branch
CC253X firmware version: cc2538+cc2592 @antst zstack3 cc2538znp

**Comment by Koenkk** [comment]
Once reporting is setup it indeed doesn't do an 'un-setup', I marked this as a bug.

**Comment by drbios** [comment]
@Koenkk Thanks for the attention 👌👌 
I am glad help a little

**Comment by sjorge** [comment]
Make this un stale, current behavior is not super intuitive

**Comment by Koenkk** [comment]
Unstale
