### ISSUE TITLE
error on either stop or restart z2m 

### ISSUE THREAD

**Issue by lysiong** [Koenkk/zigbee2mqtt#22710]
### What happened?

was changing from skyconnect USB dongle to SMLight SLZB-06(POE version) as skyconnect keep on generate routing error. After change to SLZB-06, re-generate the  pan_id, ext_pan_id & network_key using command below in yaml

`advanced:
  pan_id: GENERATE
  ext_pan_id: GENERATE
  network_key: GENERATE`

then re-pair all the devices. Z2M start-up nicely & all device work as usual but when manually stop or restart z2m, it will generate error below

`[2024-05-20 21:23:29] info: 	z2m: Stopped Zigbee2MQTT

/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:264
  var er = new ERR_STREAM_WRITE_AFTER_END();
           ^
Error: write after end
    at writeAfterEnd (/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:264:12)
    at DerivedLogger.Writable.write (/app/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:300:21)
    at DerivedLogger.log (/app/node_modules/winston/lib/winston/logger.js:252:14)
    at DerivedLogger.<computed> [as info] (/app/node_modules/winston/lib/winston/create-logger.js:95:19)
    at Logger.info (/app/lib/util/logger.ts:169:21)
    at Znp.onPortClose (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:113:16)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:529:35)
    at TCP.<anonymous> (node:net:350:12)`

### What did you expect to happen?

when stop that time shouldn't have that error as when using skyconnect, this stopping error never show up. 

### How to reproduce it (minimal and precise)

press stop or restart button at z2m addon page

### Zigbee2MQTT version

1.37.1-1

### Adapter firmware version

20240315

### Adapter

SMLight SLZB-06 (POE version)

### Setup

HAOS on promox

**Comment by wastez** [comment]
Wich firmware are you using exactly?
From the logs i see that it trys to connect with tcp, so i guess you are using the multiprotocol firmware, is that right?
Multiprotocol isn't supported by ember and probably will never will be because silabs it self detected that it isn't working as it should on bigger networks (because of speed issues which can't be fixed, serial adapter seem to be too slow), so we will se what will be with multiprotocol (if it will be stopped or something else).

If you are using the multiprotocol firmware you have to switch to adapter: ezsp or change the fimware to a ncp firwmare.

**Comment by wastez** [comment]
Sorry, wrote a post before, but thought the adapter you are using is the new emberznet chipset but i saw it is a zstack, so i deleted the old post.

Ok so the error just appear on the stop? So no problem during running?
Looks like the connection is cuted to early on stop.
But i think this should be no problem.
@Koenkk What do you think about it?

**Comment by lysiong** [comment]
> Sorry, wrote a post before, but thought the adapter you are using is the new emberznet chipset but i saw it is a zstack, so i deleted the old post.
> 
> Ok so the error just appear on the stop? So no problem during running? Looks like the connection is cuted to early on stop. But i think this should be no problem. @Koenkk What do you think about it?

Sorry didn't mention clearly, I'm using SMLight SLZB-06 in purely Zigbee mode which chipset is CC2652P. Yes, error only appear on stop, there is no problem on starting up, connection more stable than skyconnect, at least no routing error come out.

**Comment by Nerivec** [comment]
Can you post your `configuration.yaml`, the parts related to logging at least?

Just a side note. I don't think zstack has any feedback capabilities on routing issues, so if there are errors happening, you just would not see them, it doesn't mean they aren't happening. As mentioned before, they are not necessarily a "problem" as long as it works. It's just an indication that something, somewhere, is not going quite right. Could be a bad router, a bad device, interferences in a specific area...

**Comment by lysiong** [comment]
> Can you post your `configuration.yaml`, the parts related to logging at least?
> 
> Just a side note. I don't think zstack has any feedback capabilities on routing issues, so if there are errors happening, you just would not see them, it doesn't mean they aren't happening. As mentioned before, they are not necessarily a "problem" as long as it works. It's just an indication that something, somewhere, is not going quite right. Could be a bad router, a bad device, interferences in a specific area...

`homeassistant: true
advanced:
  pan_id: xx
  ext_pan_id:
    - 89
    - xx
    - 183
    - 38
    - 244
    - 96
    - 160
    - 9
  network_key:
    - 153
    - 213
    - 80
    - 96
    - xx
    - xxx
    - 204
    - xx
    - xx
    - 6
    - 84
    - 4
    - xxx
    - xx
    - 8
    - 252
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 20
  last_seen: ISO_8601_local
  log_level: info
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: xx
serial:
  port: tcp://x.x.x.x:6638
  adapter: zstack
  baudrate: 115200
  rtscts: false
frontend:
  port: 8099
device_options:
  legacy: false
devices:`

I didn't put the after device config there, If you need it, just let me know.
