### ISSUE TITLE
Payload is not supported (e.g. open, closed, opening, closing, stopped): stop

### ISSUE THREAD

**Issue by ercsey** [Koenkk/zigbee2mqtt#22711]
### What happened?

I have an Aqara ZNCLDJ14LM cover motor and I'm receiving these errors:

> Payload is not supported (e.g. open, closed, opening, closing, stopped): stop

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20211217

### Adapter

zzh! CC2652R Multiprotocol RF Stick

### Setup

Addon on HA Supervised with Debian under Proxmox

### Debug log

Logger: homeassistant.components.mqtt.cover
Source: components/mqtt/cover.py:416
integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: May 19, 2024 at 18:47:54 (236 occurrences)
Last logged: 17:31:03

Payload is not supported (e.g. open, closed, opening, closing, stopped): stop

**Comment by herky999** [comment]
Similar problem:

I have Roller shade driver E1 -ZNJLBL01LM and zigbee2mqtt recognizes it as TuYa model TS0044_1

Zigbee2MQTT - 1.36.1-1
Slaesh's CC2652RB stick - 20230507

HA VM Proxmox
Core 2024.5.4
Supervisor 2024.05.1
Operating System 12.3


Logger: homeassistant.components.mqtt.cover
Source: components/mqtt/cover.py:416
integration: MQTT (documentation, issues)
First occurred: 10:23:36 AM (11 occurrences)
Last logged: 10:34:03 AM

Payload is not supported (e.g. open, closed, opening, closing, stopped): stopped
