### ISSUE TITLE
'zigbee2mqtt/[DEVICE_ID]/get' issue/not working

### ISSUE THREAD

**Issue by rsalunga29** [Koenkk/zigbee2mqtt#2271]
`zigbee2mqtt/[DEVICE_ID]` and `zigbee2mqtt/[DEVICE_ID]/get` doesn't work whenever I try to subscribe or publish to these topics. Any help?

Device is a Aqara Smart LED Bulb. Zigbee2mqtt version is 1.6.0

P.S Documentation is already inaccurate

**Comment by rsalunga29** [comment]
I figured out a fixed for my problem. I should be subscribing to `zigbee2mqtt/[DEVICE_ID]`. However, `[DEVICE_ID]` is meant to be the `[FRIENDLY_NAME]`. @Koenkk can the documentation be updated? Since if doesn't really specify wether it's an actual device id (i.e ieeeAddr) or the friendly name. Thanks!

**Comment by Koenkk** [comment]
Thanks, will be in docs once zigbee2mqtt 1.7 is released.
