### ISSUE TITLE
Network unresponsive after x days

### ISSUE THREAD

**Issue by M1cN** [Koenkk/zigbee2mqtt#22723]
### What happened?

Once every few days zigbee2mqtt needs a restart because all powered ZigBee devices get a timeout.

### What did you expect to happen?

Stable zigbee network that does not require a restart once every x days

### How to reproduce it (minimal and precise)

randomly 

### Zigbee2MQTT version

 1.36.1

### Adapter firmware version

20221226

### Adapter

SONOFF ZigBee 3.0 P

### Setup

Z2M in docker on NUC N6005

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/15388500/log.txt)

**Comment by webnar** [comment]
Today it got unresponsive twice already
