### ISSUE TITLE
Zigbbee2mqtt does not start setting ember as adapter 

### ISSUE THREAD

**Issue by Patricen1** [Koenkk/zigbee2mqtt#22722]
### What happened?

Zigbbee2mqtt does not start 

### What did you expect to happen?

Start 🙂

### How to reproduce it (minimal and precise)

Change configuration.yaml, replace adapter from auto to ember, set rtscrs to false, docker compose up.

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

7.3.1.0 build 176

### Adapter

zbdongle-e EZSP v12

### Setup

Z2M on docker container using rpi3b

### Debug log

Tbd

**Comment by francisp2** [comment]
> Adapter firmware version
> 7.3.1.0 build 176

You need firmware 7.4.1 or 7.4.3 for ember, with 7.3.1 Zigbee2MQTT will not start

**Comment by Patricen1** [comment]
Oh thanks! I flashed my dongle using Silabs firmware flasher and it installed 7.3.1
I went to https://github.com/darkxst/silabs-firmware-builder/tree/main/firmware_builds/zbdonglee, downloaded requested gbl file and tried to flash it using custom firmware option but got the following error. Any clue?
![image](https://github.com/Koenkk/zigbee2mqtt/assets/34392672/d7c93583-c504-4528-ad35-819b35f3a09c)

**Comment by francisp2** [comment]
Be sure to download raw file

![afbeelding](https://github.com/Koenkk/zigbee2mqtt/assets/52328611/1f0843ce-53cf-430e-8a98-3d7c29dbf8b3)

**Comment by Patricen1** [comment]
Thanks a lot fot this valuable help, issue is now solved !
