### ISSUE TITLE
Sudden loss of occupancy reporting (3RSNL02043Z)

### ISSUE THREAD

**Issue by bokchilo** [Koenkk/zigbee2mqtt#22733]
### What happened?

3RSNL02043Z Devices are no longer reporting occupancy detection.

### What did you expect to happen?

Occupancy status should change when triggering hardware motion sensor.

### How to reproduce it (minimal and precise)

When attempting to trigger the physical motion sensor, the occupancy status is not changing.

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

N/a

### Adapter

zStack3x0

### Setup

Add on on home assistant running on rpi4-64

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee-herdsman-converters/issues/7521 which will be included in the next z2m release (1 June)
