### ISSUE TITLE
Innr SP120 warn message

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#2276]
I have 2 Innr SP120 power outlets but only one of them is triggering the following warning:

`No converter available for 'SP 120' with cluster 'genLevelCtrl' and type 'attributeReport' and data '{"currentLevel":254}'`

Looks to me as if the pairing did not complete successfully. Is there something I can check within the device database?

**Comment by Koenkk** [comment]
Besides this warning does it work as expected?

**Comment by andreasbrett** [comment]
Yes. Everything works. I can switch them on and off and get measurement readings regularly.

**Comment by Koenkk** [comment]
ok, I guess this message can be ignored (it doesn't make sense for this device). Warning won't be shown anymore in next zigbee2mqtt release. thanks!
