### ISSUE TITLE
Heiman HS2SK: null value reporter when no load present instead of 0

### ISSUE THREAD

**Issue by matejzero** [Koenkk/zigbee2mqtt#2277]
# Bug Report
## What happened
The switch is reporting `null` value when there is no load. Example: `MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7ad5b0', payload '{"state":"ON","linkquality":15,"power":null,"current":null,"voltage":236.95}'`.

## What did you expect to happen
That switch would report integer number such as 0 if there is no load.

The problem is that if `null` value is reported, home assistant converts it to `None` and that makes it impossible to use the `utility_meter` component.

In Home Assistant I see `2019-11-04 20:24:18 WARNING (MainThread) [homeassistant.components.utility_meter.sensor] Invalid state (None > None): [<class 'decimal.ConversionSyntax'>]` error.

I could manually add snesor and used a template to convert None to 0, but I like the autodiscovery:)

## How to reproduce it (minimal and precise)
Just pair the switch to zigbee2mqtt and check value in home assistant.

## Debug Info
zigbee2mqtt version: 1.6.0
CC253X firmware version: 20190608 I think.

**Comment by Koenkk** [comment]
Can you provide the debug log once the null value is published?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by matejzero** [comment]
Sure, I should do that in the first post, sorry.

Report, when there is not load aka 'null' usage:
```
zigbee2mqtt:debug 11/5/2019, 9:52:50 PM Received zigbee message of type 'attReport' with data '{"cid":"haElectricalMeasurement","data":{"rmsVoltage":22579}}' of device 'SmartPlug' (0x000d6f000b7ad5b0) of endpoint 1
zigbee2mqtt:info 11/5/2019, 9:52:50 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7ad5b0', payload '{"state":"ON","linkquality":5,"power":null,"current":null,"voltage":225.79}'
zigbee2mqtt:debug 11/5/2019, 9:52:50 PM Received zigbee message of type 'devChange' with data '{"cid":"haElectricalMeasurement","data":{"rmsVoltage":22579}}' of device 'SmartPlug' (0x000d6f000b7ad5b0) of endpoint 1
```

When there is usage aka XX W:
```
zigbee2mqtt:debug 11/5/2019, 9:53:45 PM Received zigbee message of type 'attReport' with data '{"cid":"haElectricalMeasurement","data":{"rmsVoltage":22683,"activePower":37}}' of device 'SmartPlug' (0x000d6f000b7ad5b0) of endpoint 1
zigbee2mqtt:info 11/5/2019, 9:53:45 PM MQTT publish: topic 'zigbee2mqtt/0x000d6f000b7ad5b0', payload '{"state":"ON","linkquality":10,"power":3.7,"current":null,"voltage":226.83}'
zigbee2mqtt:debug 11/5/2019, 9:53:45 PM Received zigbee message of type 'devChange' with data '{"cid":"haElectricalMeasurement","data":{"rmsVoltage":22683,"activePower":37}}' of device 'SmartPlug' (0x000d6f000b7ad5b0) of endpoint 1
```

**Comment by Koenkk** [comment]
It seems that this bug is already fixed in the latest dev branch. https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by matejzero** [comment]
Wow nice! I'll check it out.

Thanks.

**Comment by TheSkater** [comment]
I switched just to the developer version of zigbe2mqtt. 
I am using a HS2SK (Heiman Plug with power metering) and have still "null" values in my MQTT messages. This leads to an error when I take this result as input to a simple influxdb output node in NodeRed:

> "Error: A 400 Bad Request error occurred: {"error":"unable to parse 'zigbee2mqtt/Keller/Wasserwerk/Zigbee/Schalter current=null,linkquality=15,power=null,state=\"ON\",voltage=null': invalid number"}↵"

See coressponding MQTT message: 
`info  2019-11-10T20:28:56: MQTT publish: topic 'zigbee2mqtt/Keller/Wasserwerk/Zigbee/Schalter', payload '{"state":"ON","linkquality":15,"power":null,"current":null,"voltage":null}`

It seems that usage data like power or voltage are not read from the device.
I have the following device:
`{"ieeeAddr":"0x000d6f000b7a7240","type":"Router","networkAddress":15652,"model":"HS2SK","friendly_name":"Keller/Wasserwerk/Zigbee/Schalter","manufacturerID":4619,"**manufacturerName":"Heiman","powerSource":"Mains (single phase)","modelID":"SmartPlug","hardwareVersion":16,"dateCode":"2018.1.11**","lastSeen":1573417736631}`
`
