### ISSUE TITLE
Enable/disable devices using automation script

### ISSUE THREAD

**Issue by E30M20B20** [Koenkk/zigbee2mqtt#22773]
### Is your feature request related to a problem? Please describe

If I switch some devices on in a pair times a year, I can do this manually using checkbox in device's settings page. But if I have several losses of power supply a day (like I have it now in Kiev), it would be very useful to disable/enable devices automatically when 220V lost/reconnects

### Describe the solution you'd like

So I need an instrument to check/uncheck "disable" checkbox at device's settings using automation script, and next is restart z2m using existing feature, and here we go!

### Describe alternatives you've considered

Any kind of automatic switch on/off pings to router devices using automation script

### Additional context

![изображение](https://github.com/Koenkk/zigbee2mqtt/assets/167162523/84c27798-1c1d-4490-862c-90144fd8c3e2)

**Comment by ghoz** [comment]
Hi
Not tested but it might already be possible by sending an mqtt message to `zigbee2mqtt/bridge/request/device/options` with `disabled: true` as option

See:  https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html#zigbee2mqtt-bridge-request

**Comment by E30M20B20** [comment]
Yes, it works! Payload must be {"id": "friendly name of device", "options":{"disabled":1}}
Thank you!

**Comment by E30M20B20** [comment]
{"id": "friendly name of device", "options":{"disabled":true}} is better. Works both variants, but with "disabled":1 z2m do not start with errors "... must be boolean"
