### ISSUE TITLE
Ember issue

### ISSUE THREAD

**Issue by CurtisB123** [Koenkk/zigbee2mqtt#22783]
### What happened?

Updated Ember and get errors when trying to turn on any device

`2024-05-26 13:07:28Publish 'get' 'state' to 'Office Light' failed: 'Error: ZCL command 0xf082c0fffe5d8e95/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":115})'
Error 2024-05-26 13:07:32Publish 'set' 'state' to 'Office Light' failed: 'Error: ZCL command 0xf082c0fffe5d8e95/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":116})'`

SLZB-06M is on Core FW 2.2.7. Have also tried 2.2.2
Also tried ZB FW 20240510

### Zigbee2MQTT version

1.37.1-1

### Adapter firmware version

7.4.3

### Adapter

SLZB-06M

### Setup

HA OS

### Debug log

[log.log](https://github.com/Koenkk/zigbee2mqtt/files/15447405/log.log)

**Comment by Tarik2142** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/22189
