### ISSUE TITLE
 Colorock  CR-MNZ1  Zigbee version with energy monitor (UNREPORTABLE_ATTRIBUTE, consumption data is null)

### ISSUE THREAD

**Issue by nifelin123** [Koenkk/zigbee2mqtt#22808]
### What happened?

the data of the energy monitor is not pulled up. if you go to the developer console in the haElectricalMeasurement cluster and select the correct attributes there, the data can be read. There is also an error attached below (Status 'UNREPORTABLE_ATTRIBUTE') in the vine. Tried the converter from tuya.ts repository it didn't help. What else do you recommend to do?

![10](https://github.com/Koenkk/zigbee2mqtt/assets/165800487/a0a45fd9-0d61-4370-a63c-0413f6775c15)
![20](https://github.com/Koenkk/zigbee2mqtt/assets/165800487/1b1d6ab3-62aa-44fb-9791-6059e0345e76)
![30](https://github.com/Koenkk/zigbee2mqtt/assets/165800487/a8a15c79-14a2-4677-8505-2a4b5d6bdcfb)

### Zigbee2MQTT version

1.37.1 

### Adapter firmware version

20230507

### Adapter

CC2652P

### Setup

Intel NUC

### Debug log

Failed to configure '0x70b3d52b600b9d7a', attempt 1 (Error: ZCL command 0x70b3d52b600b9d7a/1 haElectricalMeasurement.configReport([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:315:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:770:26) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:556:9) at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:224:5) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:2943:13) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by alexps70** [comment]
I have the same device - no data on voltage/current/power

**Comment by andregoncalvespires** [comment]
The same here. Any developments?

**Comment by Koenkk** [comment]
In the reporting tab, do you get an `UNREPORTABLE_ATTRIBUTE` error for all these attributes?

- Cluster: `haElectricalMeasurement`, attributes `rmsVoltage`, `rmsCurrent`, `activePower`
- Cluster: `seMetering`, attributes: `currentSummDelivered`

If it gives an error for all we need to poll the attributes:

Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by nifelin123** [comment]
> In the reporting tab, do you get an `UNREPORTABLE_ATTRIBUTE` error for all these attributes?
> 
> * Cluster: `haElectricalMeasurement`, attributes `rmsVoltage`, `rmsCurrent`, `activePower`
> * Cluster: `seMetering`, attributes: `currentSummDelivered`
> 
> If it gives an error for all we need to poll the attributes:
> 
> Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa):
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if issue is fixed

I did everything according to your instructions. The situation has not changed. All indicators are zero. only state switching is available. With a hub from Tuya, this relay works and transmits all indicators. I am attaching the error from the log again.

Error 2024-07-17 22:34:25z2m: Failed to configure 'Boiler', attempt 3 (Error: ZCL command 0x70b3d52b600b9d7a/1 haElectricalMeasurement.configReport([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:316:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:771:26) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:557:9) at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:221:5) at Object.configure (/app/data/extension/externally-loaded.js:34:9) at Configure.configure (/app/lib/extension/configure.ts:126:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by nifelin123** [comment]
> > In the reporting tab, do you get an `UNREPORTABLE_ATTRIBUTE` error for all these attributes?
> > 
> > * Cluster: `haElectricalMeasurement`, attributes `rmsVoltage`, `rmsCurrent`, `activePower`
> > * Cluster: `seMetering`, attributes: `currentSummDelivered`
> > 
> > If it gives an error for all we need to poll the attributes:
> > Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa):
> > 
> > * save this as file next to `configuration.yaml` as `ext_converter.js`
> > * add it to `configuration.yaml`:
> > 
> > ```yaml
> > external_converters:
> >   - ext_converter.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * start z2m, check if issue is fixed
> 
> I did everything according to your instructions. The situation has not changed. All indicators are zero. only state switching is available. With a hub from Tuya, this relay works and transmits all indicators. I am attaching the error from the log again.
> 
> Error 2024-07-17 22:34:25z2m: Failed to configure 'Boiler', attempt 3 (Error: ZCL command 0x70b3d52b600b9d7a/1 haElectricalMeasurement.configReport([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:316:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:771:26) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:557:9) at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:221:5) at Object.configure (/app/data/extension/externally-loaded.js:34:9) at Configure.configure (/app/lib/extension/configure.ts:126:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
![2](https://github.com/user-attachments/assets/b2be8baf-5fcb-4c13-9222-9d2c5a854f77)
![3](https://github.com/user-attachments/assets/bd883df2-5d74-4833-ab55-01945be9e220)

![1](https://github.com/user-attachments/assets/dcafe326-b001-4298-abca-cdd5d4816fd5)

**Comment by nifelin123** [comment]
> In the reporting tab, do you get an `UNREPORTABLE_ATTRIBUTE` error for all these attributes?
> 
> * Cluster: `haElectricalMeasurement`, attributes `rmsVoltage`, `rmsCurrent`, `activePower`
> * Cluster: `seMetering`, attributes: `currentSummDelivered`
> 
> If it gives an error for all we need to poll the attributes:
> 
> Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa):
> 
> * save this as file next to `configuration.yaml` as `ext_converter.js`
> * add it to `configuration.yaml`:
> 
> ```yaml
> external_converters:
>   - ext_converter.js
> ```
> 
> * start z2m, check if issue is fixed

The situation has changed, now only energy data is NULL
![3](https://github.com/user-attachments/assets/3fcf50fd-7199-46ac-a1f6-926527daf7e7)

**Comment by lpt2007** [comment]
Hi,

@nifelin123 solution works, but readings not correct?

I connected only input to my Colorock CR-MNZ1 Zigbee version and device shows me those readings?
![18 07 2024_11 56 56_REC](https://github.com/user-attachments/assets/0e42d0c8-a533-4241-aa80-f1686d49e11d)

Any idea?

**Comment by andregoncalvespires** [comment]
We are close to a solution. The current reported by the device is in mA. Confirming the consumed energy reported in seMetering.currentSummDelivered

**Comment by Redram49RUS** [comment]
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa):

save this as file next to configuration.yaml as ext_converter.js
add it to configuration.yaml:
external_converters:
  - ext_converter.js
start z2m, check if issue is fixed

Have this error:
Integration error: external_converters - Integration 'external_converters' not found.

**Comment by Koenkk** [comment]
@Redram49RUS you have to add it to your z2m configuration.yaml, not the home assistant ons

**Comment by lpt2007** [comment]
Hi,

I try external converter. Now I get some values on W / A / V.
Current not show correctly, probably number is in mA not A as shown. 
Energy still Null? 

here i screenshot:
![20 07 2024_18 10 45_REC](https://github.com/user-attachments/assets/65363379-98e4-447d-b336-df656fa0739f)

**Comment by Redram49RUS** [comment]
> @Redram49RUS you have to add it to your z2m configuration.yaml, not the home assistant one

Thanks, it worked. The energy remained "Null".

**Comment by Koenkk** [comment]
I've updated the [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa), could you check it again after re-configuring the device by pressing the yellow refresh icon on the device page?

**Comment by nifelin123** [comment]
> I've updated the [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa), could you check it again after re-configuring the device by pressing the yellow refresh icon on the device page?

ok 10 min.

**Comment by nifelin123** [comment]
> I've updated the [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa), could you check it again after re-configuring the device by pressing the yellow refresh icon on the device page?

deleted the old converter, threw the new one and rebooted the system. Now all data has Null status. An error occurs when the yellow button is pressed.
ERROR

2024-07-21 13:07:08z2m: Failed to configure 'Boiler', attempt 5 (Error: ZCL command 0x70b3d52b600b9d7a/1 haElectricalMeasurement.configReport([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:316:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:771:26) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:557:9) at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:221:5) at Object.configure (/app/data/extension/externally-loaded.js:34:9) at Configure.configure (/app/lib/extension/configure.ts:126:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:56:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by Redram49RUS** [comment]
> I've updated the [external converter](https://gist.github.com/Koenkk/436c0291d93741b3ac261455b52722aa), could you check it again after re-configuring the device by pressing the yellow refresh icon on the device page?

 2024-07-21 21:21:31Failed to configure 'Варочная панель', attempt 7 (Error: ZCL command 0x70b3d52b600b9be7/1 haElectricalMeasurement.configReport([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:316:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:771:26) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:557:9) at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:224:5) at Object.configure (/app/data/extension/externally-loaded.js:34:9) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by Koenkk** [comment]
Are you sure you updated the external converter? Line 34 should be commented (which currently causes this `rmsVoltage` error)

**Comment by nifelin123** [comment]
> Are you sure you updated the external converter? Line 34 should be commented (which currently causes this `rmsVoltage` error)

![1](https://github.com/user-attachments/assets/85b03b26-715f-42da-b6e1-29ed2cb9ba4d)

**Comment by andregoncalvespires** [comment]
.js updated, z2m restarted.

![image](https://github.com/user-attachments/assets/d22c8a4c-b9fc-446c-b7fb-f3fa02b0d901)

![image](https://github.com/user-attachments/assets/56ff3201-ed3b-4e00-a4dc-1c9f949bbfb6)

**Comment by andregoncalvespires** [comment]
The values ​​have been corrected, although the UNREPORTABLE_ATTRIBUTE error continues to appear. I have doubts whether the energy value is being reported correctly by the device


Error 2024-07-22 16:14:50z2m: Failed to configure 'Luz Mesa', attempt 1 (Error: ZCL command 0xa4c138e5bdf24678/1 genLevelCtrl.configReport([{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":1,"attribute":"currentLevel"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:316:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:771:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:557:9) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:107:13) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:1006:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:190:21) at Configure.configure (/app/lib/extension/configure.ts:126:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

![image](https://github.com/user-attachments/assets/ad23c894-c331-448d-bffa-3968319c2249)

**Comment by Redram49RUS** [comment]
I also updated ext.js, now current and power readings are not transmitted when a 2 kW load is on.

**Comment by andregoncalvespires** [comment]
The energy measurement is really unreliable. The Tuya app already showed a large variation. Does anyone know if using calibration could help? Power and Current appear to be normal. Considering the variation between now and 14 hours ago, it shows a consumption of more than 200 kWh and it should be something around 10 kWh

![image](https://github.com/user-attachments/assets/743da419-04c2-43d7-953d-63e793e41b42)

**Comment by Koenkk** [comment]
@andregoncalvespires if the energy measurement via the Tuya gateway is also incorrect, it's not something that can be fixed by z2m

**Comment by andregoncalvespires** [comment]
It is clear @Koenkk . The question was considering the available calibration options. But I'm already discouraged by this device.
Thank you for the fabulous work you and everyone who contributes do.

**Comment by Brucepbd** [comment]
The external converter seems to be working for me.
![Screenshot 2024-09-24 122226](https://github.com/user-attachments/assets/df54911f-058a-4de8-b447-de00eb411ea6)

**Comment by lucasnz** [comment]
This fixed the missing data for me :)

**Comment by Brucepbd** [comment]
Although it is working.  I did get a random change in the energy level last week that through off my energy monitoring.  So I am relying on integrating the power to get more stable energy data.

**Comment by Brucepbd** [comment]
> I have two Colorock CR-MNZ1 with power monitoring and have added the extension from this thread but it doesn't work and they only update values if I manually poll via the Dev console. I don't know if it makes any difference but I am running Zigbee2MQTT version 2.0.0 so maybe the extension isn't compatiable.
> 
> Other than the updating not working.
> 
> Power is in Watts which is fine Current says Amp but is mA Voltage is Volts which is fine Energy is hard to figure out with out reliable data on the other values but it isn't kWh, the best I can figure is it needs to be divided by 100 which may get it about what I think it should be.

Same here.  The last time my history shows a power and current measurement was January 3rd 2025.  They have both been zero since then.  I have not been using the extension though.  I thought it was working without the extension, so I removed it.  I'll setup the extension and report back to see if it changes.

**Comment by Fograd** [comment]
@Koenkk with your external converter I managed to get `activePower` to poll (was able to read through Dev console)

But I cannot get it to automatically expose it through `Power` and the last value `Power` shows is the latest value that I polled from `activePower` manually. Am I doing something wrong?

Thanks in advance for your response. I have been banging my head against the wall for the past 4 hours trying to get it fixed...

**Comment by Brucepbd** [comment]
I'm not sure how github works.  Since this issue is closed I'm not sure if anyone will pay attention to our posts.

**Comment by Fograd** [comment]
> I'm not sure how github works. Since this issue is closed I'm not sure if anyone will pay attention to our posts.

@Brucepbd I managed to get help on Z2M discord channel that resolved my issue. Here is the response I got (shoutout to Rene):

If you are on z2m version 2.0, the location for external converters has changed
it now needs to be in `/homeassistant/zigbee2mqtt/external_converters` (essentially you need to create a sub-folder under `zigbee2mqtt` and put your `ext_converter.js` file above in there)

after you have replaced it:
1. Remove the following from your `/homeassistant/zigbee2mqtt/configuration.yaml` file as in the guide above:
```
external_converters:
  - ext_converter.js
``` 
2. restart z2m
3. open the most recent logdir in `/homeassistant/zigbee2mqtt/log`
4. open `log.log`
5. check if the converter is loaded or if loading gives an error. If no errors then force delete your device and re-pair it. (mine worked even without having to re-pair the device)

Let me know if you have any issues. Would be happy to help if I can!

**Comment by Brucepbd** [comment]
> > I'm not sure how github works. Since this issue is closed I'm not sure if anyone will pay attention to our posts.
> 
> @Brucepbd I managed to get help on Z2M discord channel that resolved my issue. Here is the response I got (shoutout to Rene):
> 
> If you are on z2m version 2.0, the location for external converters has changed it now needs to be in `/homeassistant/zigbee2mqtt/external_converters` (essentially you need to create a sub-folder under `zigbee2mqtt` and put your `ext_converter.js` file above in there)
> 
> after you have replaced it:
> 
> 1. Remove the following from your `/homeassistant/zigbee2mqtt/configuration.yaml` file as in the guide above:
> 
> ```
> external_converters:
>   - ext_converter.js
> ```
> 
> 2. restart z2m
> 3. open the most recent logdir in `/homeassistant/zigbee2mqtt/log`
> 4. open `log.log`
> 5. check if the converter is loaded or if loading gives an error. If no errors then force delete your device and re-pair it. (mine worked even without having to re-pair the device)
> 
> Let me know if you have any issues. Would be happy to help if I can!

Thank you!  It works now.  I remember seeing something about that in the release notes before I made the upgrade - but it looked like it was working after the upgrade was done (it was off and had zero for watts and current - which was correct).  I thought the converter was incorporated into the main z2m and not needed anymore.  So I forgot about the directory change and never followed through.  It wasn't until someone posted here that I took a closer look at the entity history and realized it was broken.

It will be great having all this information about this device in one place for others to get things working.  Thanks again for posting! :)

**Comment by nblount** [comment]
This appears to have worked for one and not the other will have to try re-pairing tomorrow.

**Comment by Brucepbd** [comment]
One thing that seems to be a continuing problem with this device is that the energy value makes large jumps during measurements.  As seen in the picture, for the same load it jumps from 53kWh to 107kWh.  It seems to happen during times when the load switches from off to on.  I don't know if this is a device problem or an external converter problem.  I had the same problem with a previous CR-MNZ1 and returned it.  I bought another one to replace it and it still has this problem.  So I can't use it for energy measurement.

![Image](https://github.com/user-attachments/assets/c88f6bbc-6d53-4e7d-a0f8-2f9777a8e91f)

**Comment by cagarrinho** [comment]
I bought a Colorock 30A Zigbee Relay and added it to Zigbee2MQTT in HomeAssistant. As you can see in the images, I can't get data for: Power, Current, and Voltage. I can only receive Energy data. Does anyone have the same device and can help me? I've already tried an external converter I found online, but that didn't work either.
![image](https://github.com/user-attachments/assets/b549323e-5c7d-4096-8750-6ca5de1bbcba)![image](https://github.com/user-attachments/assets/300070a9-fc8d-4545-a0b2-68ac2d37d0a5)

**Comment by nblount** [comment]
I don't have any of these devices active any more as they all failed. They don't seem to stand up well when connected to Washing Machines and Tumble Dryers. Had one replaced by supplier but ultimately they all failed again.

As to get all values can you query the other values via the Developer Console?
Have you tried re-pairing the device or initiating a re-interview?

**Comment by Brucepbd** [comment]
I returned all my devices.  I think the last one overheated and died from a 15A load at 240VAC.  The relay inside is probably not the actual 30A 240VAC rated.  I currently have a "made in USA" relay installed rated at 20A 240VAC, I installed it on one side so it's getting 15A 120VAC and it has been working without any problems since probably January 2025.

I had success with this external converter: (converter.js).  take this code, save it in a .js file, put it in the z2m main directory.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;
const legacy = require('zigbee-herdsman-converters/lib/legacy');
const lumi = require('zigbee-herdsman-converters/lib/lumi');
const utils = require('zigbee-herdsman-converters/lib/utils');

const definition =    {
    fingerprint: tuya.fingerprint('TS0001', [
        '_TZ3000_xkap8wtb',
        '_TZ3000_qnejhcsu',
        '_TZ3000_x3ewpzyr',
        '_TZ3000_mkhkxx1p',
        '_TZ3000_tgddllx4',
        '_TZ3000_kqvb5akv',
        '_TZ3000_g92baclx',
        '_TZ3000_qlai3277',
        '_TZ3000_qaabwu5c',
        '_TZ3000_hzlsaltw',
    ]),
    model: 'TS0001_power',
    description: 'Switch with power monitoring',
    vendor: 'Tuya',
    fromZigbee: [fz.on_off, fz.electrical_measurement, fz.metering, fz.ignore_basic_report, tuya.fz.power_outage_memory, tuya.fz.switch_type],
    toZigbee: [tz.on_off, tuya.tz.power_on_behavior_1, tuya.tz.switch_type],
    configure: async (device, coordinatorEndpoint) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint);
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
       // await reporting.rmsVoltage(endpoint, {change: 5});
        //await reporting.rmsCurrent(endpoint, {change: 50});
      //  await reporting.activePower(endpoint, {change: 10});
       // await reporting.currentSummDelivered(endpoint);
        endpoint.saveClusterAttributeKeyValue('haElectricalMeasurement', {acCurrentDivisor: 1000, acCurrentMultiplier: 1});
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
        device.save();
    },
    exposes: [
        e.switch(),
        e.power(),
        e.current(),
        e.voltage(),
        e.energy(),
        tuya.exposes.switchType(),
        e.enum('power_outage_memory', ea.ALL, ['on', 'off', 'restore']).withDescription('Recover state after power outage'),
    ],
    whiteLabel: [
        tuya.whitelabel('Nous', 'B2Z', '1 gang switch with power monitoring', ['_TZ3000_qlai3277']),
        tuya.whitelabel('Colorock', 'CR-MNZ1', '1 gang switch 30A with power monitoring', ['_TZ3000_tgddllx4']),
        tuya.whitelabel('Nous', 'L6Z', 'Switch with power monitoring', ['_TZ3000_qaabwu5c']),
        tuya.whitelabel('Tuya', 'TS0001_power_polling', 'Switch with power monitoring (via polling)', ['_TZ3000_x3ewpzyr']),
    ],
    onEvent: async (type, data, device, options) => {
        if (['_TZ3000_x3ewpzyr', '_TZ3000_tgddllx4'].includes(device.manufacturerName)) {
            await tuya.onEventMeasurementPoll(type, data, device, options, true, true);
        }
    },
};

module.exports = definition;

**Comment by cagarrinho** [comment]
Doesn't work for me that converter! 
Can anyone suggest me any reliable 30a to add to my homeassistant?
I think it's time to change device...

**Comment by ifurnadjiev** [comment]
@Koenkk Could you please rewrite the custom convertor to support Z2M 2.9.2? The existing one is renamed to "*.invalid" when used in 2.9.2. Thanks in advance!

**Comment by ifurnadjiev** [comment]
@Koenkk ... or maybe is best to fix it officially in Z2M. Currently, the measurement values are not updated and UNREPORTABLE_ATTRIBUTE error is thrown.

**Comment by ifurnadjiev** [comment]
@andrei-lazarov Can you help with updated custom convertor (based on the one above) that works with Z2M 2.9.2?

**Comment by andrei-lazarov** [comment]
Submitted PR, hope this converter works until it's merged and deployed: [colorock.js](https://github.com/user-attachments/files/26534095/colorock.js)

**Comment by ifurnadjiev** [comment]
@andrei-lazarov Thank you very much

**Comment by ifurnadjiev** [comment]
@andrei-lazarov Could you please also disable the reporting in your PR for device "_TZ3000_tgddllx4"? The 4 lines below throw an UNREPORTABLE_ATTRIBUTE error.

```
await reporting.rmsVoltage(endpoint, {change: 5});
await reporting.rmsCurrent(endpoint, {change: 50});
await reporting.activePower(endpoint, {change: 10});
await reporting.currentSummDelivered(endpoint);
```

Thanks again.

**Comment by andrei-lazarov** [comment]
Already did. For device `_TZ3000_tgddllx4` it only does:
`await reporting.bind(endpoint, coordinatorEndpoint, ["genOnOff"]);`
Does this fail as well?

Reportings for measurements are in the `else` block (when device is not `_TZ3000_tgddllx4`).

**Comment by ifurnadjiev** [comment]
Binding is fine. Only the 4 reporting above are problematic.
