### ISSUE TITLE
A lot of error messages "Default response to 0xf4ce3616efe4f5a3 failed" for Perenio PEHPL0X starting from Z2M 1.37.0

### ISSUE THREAD

**Issue by oyunets** [Koenkk/zigbee2mqtt#22818]
### What happened?

zigbee2mqtt was updated to the version 1.37.0
As a result, constantly error messages reported like "Default response to XXX failed" for [Perenio PEHPL0X](https://www.zigbee2mqtt.io/devices/PEHPL0X.html) devices.
zigbee2mqtt was updated to the version 1.37.1
Result the same.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/3874659/3a6e6467-8c15-4bdf-8236-640d6a76d771)

### What did you expect to happen?

No error messages

### How to reproduce it (minimal and precise)

1. Setup zigbee2mqtt]
2. Add device [Perenio PEHPL0X](https://www.zigbee2mqtt.io/devices/PEHPL0X.html)

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20210708

### Adapter

SONOFF ZBDongle-E

### Setup

Z2M container on Pi 4

**Comment by Koenkk** [comment]
Will be fixed in the Saturday release!
