### ISSUE TITLE
[New device support]: Philips Hue Dymera (LCW004)

### ISSUE THREAD

**Issue by CloudMass** [Koenkk/zigbee2mqtt#22828]
### Link

https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-dymera-indoor-and-outdoor-wall-light/046677585235

### Database entry

{"id":62,"type":"Router","ieeeAddr":"0x001788010de24e41","nwkAddr":16764,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LCW004","epList":[11,12,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"zclVersion":8}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":1,"currentX":11140,"currentY":45874,"enhancedCurrentHue":25600,"currentSaturation":254,"colorTemperature":153}},"genOnOff":{"attributes":{"onOff":1,"onTime":0}},"genIdentify":{"attributes":{"identifyTime":0}}},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":260,"epId":12,"devId":269,"inClusterList":[0,3,4,5,6,8,64515,768,64513],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"powerSource":1,"manufacturerName":"Signify Netherlands B.V."}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500}},"nearestGateway":{"attributes":{}},"genIdentify":{"attributes":{"identifyTime":0}},"genOnOff":{"attributes":{"onOff":1,"onTime":0,"globalSceneCtrl":1}},"genOnOffSwitchCfg":{"attributes":{}},"manuSpecificPhilips":{"attributes":{}},"manuSpecificPhilips2":{"attributes":{"state":{"type":"Buffer","data":[7,0,1,254,110,1]}}},"genGroups":{"attributes":{"nameSupport":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20230609","swBuildId":"1.109.1","zclVersion":8,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1717015419301}

### Comments

I tried to follow the great guide on adding support for the Philips Hue Dymera wall light. It has multiple endpoints, one for the top light (11) and one for the bottom light (12). The issue with my current version of the definition is that only the top light reacts to commands. Any pointers would be greatly appreciated.

Thx.

### External definition

```shell
const {deviceEndpoints, identify} = require('zigbee-herdsman-converters/lib/modernExtend');
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['LCW004'],
    model: 'LCW004',
    vendor: 'Philips',
    description: 'Dymera indoor and outdoor wall light',
    extend: [deviceEndpoints({"endpoints":{"11":11,"12":12}}), identify(), philipsLight({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"],"en>
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by pixolio** [comment]
Thanks for your post...i've exactly the same problem. If have installed three wall lights (PHILIPS Hue Dymera) in our garden and with the standard recognition from z2m only the top light could be controlled.

**Comment by Koenkk** [comment]
Added! Will be supported in the next release on Saturday.

**Comment by CloudMass** [comment]
@Koenkk That was a very quick response - Thanks!

I tested it by running the latest-dev docker image and I can now turn on/off, set brightness and temp individually for the top and bottom lights - That's great!

One issue is that I can only set the color for the top light. If I try to click the color buttons for the bottom light it just changes the top light color.

**Comment by CloudMass** [comment]
> @Koenkk That was a very quick response - Thanks!
> 
> I tested it by running the latest-dev docker image and I can now turn on/off, set brightness and temp individually for the top and bottom lights - That's great!
> 
> One issue is that I can only set the color for the top light. If I try to click the color buttons for the bottom light it just changes the top light color.

Quick note - The above described is when using the zigbee2mqtt web interface. I just noticed that if I use home assistant I can actually control the colors of the individual lights. Odd.
