### ISSUE TITLE
Invalid or incomplete color value

### ISSUE THREAD

**Issue by perseus177** [Koenkk/zigbee2mqtt#22838]
### What happened?

Repeated Warnings inserted into the Home Assitant log 

### What did you expect to happen?

No warnings

### How to reproduce it (minimal and precise)

Problematic device 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/25415840/215ef94a-efba-41b2-ba98-cccdd7307bd0)

## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4910
Installed Version | 1.33.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 219.4 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.7.1), MariaDB (2.6.1), Mosquitto broker (6.4.1), Zigbee2MQTT (1.37.1-1), Nginx Proxy Manager (0.12.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27. mája 2024 o 16:47
-- | --
current_recorder_run | 30. mája 2024 o 12:55
estimated_db_size | 72.17 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

7.3.1.0 build 176

### Adapter

EZSP v12

### Setup

Add-on on Home Assistant on RPI4

### Debug log

```
Logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:410
integration: MQTT (documentation, issues)
First occurred: 1:14:11 PM (112 occurrences)
Last logged: 4:04:19 PM

Invalid or incomplete color value '{'brightness': 255, 'color_mode': 'xy', 'color_power_on_behavior': None, 'do_not_disturb': None, 'linkquality': 180, 'state': 'OFF'}' received for entity light.0xa4c13875ef97827a
Invalid or incomplete color value '{'brightness': 255, 'color_mode': 'xy', 'color_power_on_behavior': None, 'do_not_disturb': None, 'linkquality': 172, 'state': 'OFF'}' received for entity light.0xa4c13830cd374221
Invalid or incomplete color value '{'brightness': 255, 'color_mode': 'xy', 'color_power_on_behavior': None, 'do_not_disturb': None, 'linkquality': 176, 'state': 'OFF'}' received for entity light.0xa4c13830cd374221
Invalid or incomplete color value '{'brightness': 255, 'color_mode': 'xy', 'color_power_on_behavior': None, 'do_not_disturb': None, 'linkquality': 176, 'state': 'OFF'}' received for entity light.0xa4c13875ef97827a
Invalid or incomplete color value '{'brightness': 255, 'color_mode': 'xy', 'color_power_on_behavior': None, 'do_not_disturb': None, 'linkquality': 172, 'state': 'OFF'}' received for entity light.0xa4c13875ef97827a
```

**Comment by LaurentChardin** [comment]
So `color_mode` is configured as `xy`, therefore HA is expecting another property called `xy_color`.
https://developers.home-assistant.io/docs/core/entity/light#color-modes:
`The light's color can be set using the xy_color parameter and read through the xy_color property. xy_color is an (x, y) tuple.`

**Comment by perseus177** [comment]
Any update ?
