### ISSUE TITLE
Ikea tradfri led

### ISSUE THREAD

**Issue by cima37** [Koenkk/zigbee2mqtt#2285]
Hi!  Is it possible to set the tradfri led's somewhere if you switch it off in the dimmed state with a switch, the next turn on has normal brightness again?  I have zigbee2mqtt running on a raspberry pi with cc2531 usb stick!

**Comment by nldroid** [comment]
You can do that from whatever home automation system you're using. I assume that you trigger the lamp via such a system.

**Comment by cima37** [comment]
yes I use fhem!  but the "problem" is that I homatic 2 channel switch I have installed and then the current to the led free and when I turn off then the led keeps the status and I can change this again when the switch is turned on again!  With the hue lamps there is an adjustment in the app that allows the lamps to give their own status when they get power again!  That's what I wanted to know if this is also in here, or how this is realized!

**Comment by lolorc** [comment]
I don't quite understand your setup, do you use a "normal" switch to cut the power to the bulb ?
If not, are you using a zigbee switch bound to your bulb ? in that case the switch communicates directly with the bulb, I would also like to know how to setup a default brightness level.
Or, if it's fhem telling the bulb to switch on, you could use the brightness attribute in the mqtt message.

**Comment by cima37** [comment]
I have a normal switch to cut the power!

**Comment by nldroid** [comment]
That's not something thats part of zigbee2mqtt. You could check if a message is sent over the mqtt channel when you put power back on. I'm not sure if that is the case but if there is a message, you could make a 'trigger' in fhem that catches it. The delay would be terrible probably.

I never cut the power off the bulbs but use a zigbee switch to turn it on and off.

**Comment by cima37** [comment]
Ok thanks! You can not use the bulb without zigbee, is that correct?

**Comment by nldroid** [comment]
Sure you can. But using switches that pass messages though a home automation system gives you more flexibility. One you cut the power, you cannot 'talk' to the bulb anymore.

**Comment by cima37** [comment]
Ok thanks! I close this!
