### ISSUE TITLE
TuYa CK-BL702-AL-01 Does not permit joining as a router

### ISSUE THREAD

**Issue by stm2roi3** [Koenkk/zigbee2mqtt#22856]
### What happened?

I have installed 8 GU10 Tuya light bulbs (TuYa CK-BL702-AL-01). None of them is able to connect to each other when permitting the join of other devices via zigbee2mqtt. When I enable all Zigbee devices to permit joins those Tuya light bulbs connect to a IKEA Tradfri Driver 10W.

### What did you expect to happen?

When I click on “permit join” on the first connected Tuya Light bulb I want to a second Tuya light bulb to pair to the first one.

### How to reproduce it (minimal and precise)

- Pair first Tuya light bulb
- Click on “permit join” in order to bring first Tuya light bulb into pairing mode
- power second Tuya light bulb and bring it to pairing mode
- See no connection between first and second light bulb

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20210120

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

Home Assistant 2024.5.5 on RPi4-64

**Comment by janfuhlrott** [comment]
Same Problem here. 
HA OS on MacMini.

**Comment by ccervigon** [comment]
Same problem here with home assistant. They are not able to connect to each other. Also they are not able to connect to another router only to sonoff.

**Comment by rmxs** [comment]
Same issue

**Comment by Koenkk** [comment]
This is probably a bug in the firmware of the bulb, not something that can be solved from z2m.
