### ISSUE TITLE
[New device support]: AduroSmart Eria 81815

### ISSUE THREAD

**Issue by ryanlocey** [Koenkk/zigbee2mqtt#22861]
### Link

https://adurosmart.com/product/eria-soft-white-br30-65w/

### Database entry

{"id":9,"type":"Router","ieeeAddr":"0x00158d0001a6faf2","nwkAddr":35993,"manufId":4151,"manufName":"AduroSmart\u0000","powerSource":"Mains (single phase)","modelId":"ZLL-DimmableLigh","epList":[1,2],"endpoints":{"1":{"profId":49246,"epId":1,"devId":256,"inClusterList":[0,4,3,6,8,5,65535,25],"outClusterList":[0,4,3,6,8,5,25],"clusters":{"genBasic":{"attributes":{"modelId":"ZLL-DimmableLigh","manufacturerName":"AduroSmart\u0000","powerSource":1,"zclVersion":1,"appVersion":4,"stackVersion":1,"hwVersion":2,"dateCode":"20180526","swBuildId":"1000-0004"}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":49246,"epId":2,"devId":4096,"inClusterList":[4096],"outClusterList":[4096],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"stackVersion":1,"hwVersion":2,"dateCode":"20180526","swBuildId":"1000-0004","zclVersion":1,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1717215811510}

### Comments

couldnt figure out the cloning part

### External definition

```shell
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['AD-DimmableLight3001'],,
    model: '81815',
    vendor: 'AduroSmart',
    description: 'ERIA BR30 Soft White Smart Bulb',
    extend: [light()],
	
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`AD-DimmableLight3001` is supported in z2m 1.38.0
