### ISSUE TITLE
 ZG-204ZM - Wrong options to set

### ISSUE THREAD

**Issue by Koterak** [Koenkk/zigbee2mqtt#22870]
### What happened?

In 1.38.0 you introduced new options to set "PiR, PiR+Radar, Radar". But options are probably wrong: there is "Dadar" instead of "Radar" and there is error in zigbee2mqtt that it doesn't know this option

![Zrzut ekranu 2024-06-01 115124](https://github.com/Koenkk/zigbee2mqtt/assets/35494920/8bc75919-ad1f-4d59-b11a-10d93713ccc6)

### What did you expect to happen?

Change "Dadar" to "Radar"

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20230922

### Adapter

EZSP-06

### Setup

Add-on on HASSIO

**Comment by truongbber** [comment]
I also got the same error

**Comment by truongbber** [comment]
> I also got the same error

![Uploading Ảnh chụp màn hình 2024-06-01 183859.png…]()

**Comment by mortanol** [comment]
Same error here. I was hoping that this option would help the radar to work. Currently, it's not. When I'm static, presence is set to none after fading time

**Comment by idogrf** [comment]
Same issue

**Comment by hfagelnour** [comment]
UP

**Comment by Angus774** [comment]
Same error

**Comment by stenly30** [comment]
Same error

**Comment by ArkadiuszNiemiec** [comment]
This is already fixed in the dev branch. If you are using docker you can switch the tag to latest-dev. It's still getting stuck with presence detected, so it's unusable for me.

**Comment by ArkadiuszNiemiec** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/issues/7590

**Comment by hfagelnour** [comment]
> This is already fixed in the dev branch. If you are using docker you can switch the tag to latest-dev. It's still getting stuck with presence detected, so it's unusable for me.

I have 6 of these, I am experiencing the same on 2 units of all 6 put in the same room in the same exact environment. the other 4 works flawlessly with the stable and now even better with the dev version (except for the cosmetic "Dadar" thing :) ). I guess what you are experiencing is a hardware issue.

**Comment by Koenkk** [comment]
Fixed in the dev branch (including the typo)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
