### ISSUE TITLE
[Wrong device]: Whitelabel of LEDVANCE AC26940/AC31266

### ISSUE THREAD

**Issue by LarsK1** [Koenkk/zigbee2mqtt#22884]
### Link

https://www.ledvance.de/consumer/produkte/smart-home/smart-home-komponenten/intelligente-aussensteckdose-mit-zigbee-technologie-zur-einbindung-von-elektrischen-geraete-ins-smart-home-system-c6308?productId=86309

### Model

AC26940/AC31266

### Description

Outdoor switch

### Vendor

LEDVANCE

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/AC26940-AC31266.png

### Database entry

 zigbeeModel: ['Plug 01'],     model: 'Plug 01',     vendor: 'OSRAM',     description: 'Automatically generated definition',     extend: [identify(), onOff({"powerOnBehavior":false}), electricityMeter({"cluster":"electrical"})],     meta: {},

### Notes

This is a whitelabel of the already existing https://www.zigbee2mqtt.io/devices/AC26940_AC31266.html

**Comment by Koenkk** [comment]
These devices use the same model ID (`Plug 01`), so we cannot distinguish them.
