### ISSUE TITLE
Problem accessing https://www.zigbee2mqtt.io

### ISSUE THREAD

**Issue by viama** [Koenkk/zigbee2mqtt#22916]
### What happened?

For the last couple of days I've been unable to access the https://www.zigbee2mqtt.io website from my home broadband

### What did you expect to happen?

The website would load (and device pictures populate in my z2m instance)

### How to reproduce it (minimal and precise)

access the website in a bowser

### Zigbee2MQTT version

1.38

### Adapter firmware version

20230507

### Adapter

Sonoff P

### Setup

debian docker

**Comment by wastez** [comment]
Dont know what you mean, it is working as it should.

**Comment by viama** [comment]
> Dont know what you mean, it is working as it should. 

I agree. The site is up and I can access it fine on mobile or over a VPN. For some reason my ISP seems unable to access this site. It feels like a firewall block. I've changed IP addresses without luck too.

**Comment by viama** [comment]
Looks like it's a broader BT wholesale issue with things hosted on GitHub.io reports from EE and Plusnet.

Closing this issue as clearly not a problem for here.

**Comment by viama** [comment]
For the record BT were blocking all GitHub.io pages. Been fixed now
