### ISSUE TITLE
Device LQI is always reflecting Coordinator connection

### ISSUE THREAD

**Issue by M1cN** [Koenkk/zigbee2mqtt#22929]
### What happened?

It seems that devices are not picking the best route for there primary connection.
 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/7816672/74af084e-9d34-4240-af34-b6acde326367)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/7816672/d527c1af-943a-4367-bf94-fbebe528c68e)

### What did you expect to happen?

To make the Router that is 5 meters away with the higher link quality the preferred route.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

 20221226

### Adapter

SLZB-06

### Setup

Docker

**Comment by Koenkk** [comment]
Z2M cannot influence how devices connect to each other, so this cannot be fixed from Z2m.
