### ISSUE TITLE
1.38.0 HA Addon - No Frontend

### ISSUE THREAD

**Issue by jerrm** [Koenkk/zigbee2mqtt#22923]
### What happened?

Using 1.38.0 HA Addon on HA 2024.5.5.

No devices, or any info for that matter is displayed in the front end.  All the menus are there, but no data.  Devices still work via HA, just Front End is missing.

Settings->Raw returns:
```
{
    "configSchema": {
        "properties": {},
        "required": []
    },
    "config": {
        "advanced": {}
    }
}
```

### What did you expect to happen?

Devices/Data to be there as in the past.

### How to reproduce it (minimal and precise)

Updated to 1.38.0 Addon via HA interface.

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20211028

### Adapter

ZBDongle-P

### Setup

HA Addon

**Comment by francisp2** [comment]
Try restarting the add-on

**Comment by jerrm** [comment]
Already restarted multiple times, also have done a full system reboot.

**Comment by niculw** [comment]
Experienced same behavior with a Dongle-E when updating to 1.38.0. Z2M frontend shows no devices, however devices are present in the "Raw" tab and available in HA

**Comment by jerrm** [comment]
Found a fix.  

My devices.yaml had an `icon:` entry for each device (the data:image line below is truncated for brevity).:
```
'0xb0ce1814036baacf':
  friendly_name: Plug Utility Room
  icon: >-
    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAA...
```

I removed all the `icon:` sections from devices.yaml with a quick grep command, and everything started working again.
