### ISSUE TITLE
New devices don't work after update

### ISSUE THREAD

**Issue by SaymonPhoenix** [Koenkk/zigbee2mqtt#22939]
### What happened?

Hello. My ceiling human presence sensor did not work. After the update it became supported, thank you for that. But:
1. It is displayed as a TuYa ZY-M100-24G model, although in fact it is ZY-M100-S_1 (also 24G)
2. In fact it doesn't work and I keep getting an error "Exception while calling fromZigbee converter: Value '5' is not allowed, expected one of 0,1,2}"

### Zigbee2MQTT version

1.38.0-1

### Adapter firmware version

20240501.1

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E (EFR32MG21) Firmware: 7.4.3-0

### Setup

Docker Container

**Comment by uveral** [comment]
same for me

**Comment by wwyyrrmm** [comment]
same to me

**Comment by Koenkk** [comment]
Could you provide the data/database.db entry of this device?
