### ISSUE TITLE
Xiaomi switch randomly toggling lights on or off

### ISSUE THREAD

**Issue by sneakybadger** [Koenkk/zigbee2mqtt#2293]
Hi all,

First post, so go gentle!

Using HA and Zigbee2MQTT with a CC2531 - noticed that when I set up either the Xiaomi Single wall switch or the little button wireless switch, everything worked well but the lights would (seemingly) at random toggle themselves on, or off. Configuration was:

- id: '1573020784695'
  alias: Lights
  description: ''
  trigger:
  - entity_id: sensor.0x00158d0003057d4b_click
    platform: state
  condition: []
  action:
  - data:
      entity_id: light.back_room
    service: light.toggle
  - data:
      entity_id: light.kitchen
    service: light.toggle

I lined it up with the timing and saw that it would do it every time the check would occur as per below:

  zigbee2mqtt:info 11/8/2019, 2:35:01 AM MQTT publish: topic 'zigbee2mqtt/0x00158d0003057d4b', payload '{"linkquality":68,"battery":100,"voltage":3075}'

There seems to be several issues out there where devices are toggling automatically. In my case, I resolved it with the following:

- id: '1573020784695'
  alias: Lights
  description: ''
  trigger:
  - entity_id: sensor.0x00158d0003057d4b_click
    to: 'single'
    platform: state
  condition: []
  action:
  - data:
      entity_id: light.back_room
    service: light.toggle
  - data:
      entity_id: light.kitchen
    service: light.toggle

Specifying the single click seemed to stop it. Just thought I might pass this on!

Cheers,
Mitch Frances.

# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Koenkk** [comment]
Thanks for sharing, a `to` is indeed required and also specified in the docs (https://www.zigbee2mqtt.io/integration/home_assistant.html#responding-to-button-clicks). Hopefully this will help somebody with the same problem.
