### ISSUE TITLE
SMART Socket EU Mini Plug

### ISSUE THREAD

**Issue by Martin004** [Koenkk/zigbee2mqtt#2295]
Hello I tried to add a new smart plug.

Do you add it for me please ?
info: PowerPlug1 (0x02124b00198a6a5b): unkown - undefined unknown (Router)
warn: Device with modelID 'Plug_01' is not supported.

Thanks a lot
Martin

**Comment by Koenkk** [comment]
This device is already supported in the latest dev branch (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L5494)
