### ISSUE TITLE
[New device support]: LEDVANCE TUBE_T8_CON_600_7.5W_840ZBV

### ISSUE THREAD

**Issue by Dis90** [Koenkk/zigbee2mqtt#22962]
### Link

https://www.ledvance.fi/ammattikaeyttoe/tuotteet/lamput/led-valoputket/led-valoputket/led-valoputket-c7065?productId=117603

### Database entry

{"id":35,"type":"Router","ieeeAddr":"0xf0d1b8000024a885","nwkAddr":55498,"manufId":4489,"manufName":"LEDVANCE","powerSource":"Mains (single phase)","modelId":"TUBE_T8_CON_600_7.5W_840ZBV\u0000","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,769,1794,2820,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"zclVersion":3}},"genOnOff":{"attributes":{"onOff":1}},"haElectricalMeasurement":{"attributes":{}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00257ca22c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":2,"swBuildId":"02036550","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1717693010784}

### Comments

I'm not sure about model name. I just copied it from here https://github.com/Koenkk/zigbee2mqtt/issues/18087

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TUBE_T8_CON_600_7.5W_840ZBV'],
    model: 'ST8EM-CON',
    vendor: 'LEDVANCE',
    description: 'SubstiTUBE T8 EM Connected 7.5 W/4000 K 600 mm',
    extend: [identify(), light({colorTemp: false, color: false})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Could you also submit a picture for the docs? This can be done by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/upload/master/public/images/devices). 

Make sure that:
- The filename is `MODEL.png` (update `model` accordingly) 
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
