### ISSUE TITLE
BLE-YL01:  Free Chlorine is 10x the value

### ISSUE THREAD

**Issue by mzakharo** [Koenkk/zigbee2mqtt#22985]
### What happened?

BLE-YL01 Reports Free Chlorine levels, and zigbee2mqtt integration reports the value to be 10x the actual value in ppm. For example, according to ORP/pH tables, found [online](https://github.com/mzakharo/tubby/blob/main/charts/servovendi.png), Free chlorine  for  ORP=632  and pH=7.5, the Free Chlorine value should be 0.6ppm, but the reported integration value is 6ppm.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/567867/5b8d835a-40a9-46f4-a4f8-47d0834731a8)

### What did you expect to happen?

chlorine ppm value reported should be multiplied by 0.1.

### How to reproduce it (minimal and precise)

Pair the BLE-YL01 and start using it

### Zigbee2MQTT version

 1.38.0 

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff E

### Setup

Docker container

**Comment by Burki24** [comment]
@Koenkk 
@mzakharo 

Can we please reverse this fix. The Chlor is meassured in mg/L I tested it with my prof. PoolLab 2. And there, I have 3,41 mg/l and in Z2M it is now 0,3 mg/l, so I think we have to use the .raw version:
![image](https://github.com/Koenkk/zigbee2mqtt/assets/20765982/6937014d-7e75-4c6b-b765-652715d2da3d)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/20765982/b4101050-0ea1-439c-a7fb-0de95834c550)

**Comment by mzakharo** [comment]
The value BLE-YL01 delivers is from the table mentioned above. They state this on the aliexpress page. The  0.1 fix is correct.
