### ISSUE TITLE
zigbee2mqtt does not respond to the MQTT topic

### ISSUE THREAD

**Issue by Sergej569** [Koenkk/zigbee2mqtt#22997]
### What happened?

zigbee2mqtt does not respond to the MQTT topic "Status". I cannot change the status. If I change it directly on the Zigbee2mqtt website, this status changes in the MQTT topic

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

 20210708

### Adapter

zStack3x0

### Setup

Pi

**Comment by hbk001** [comment]
Same with 1.38.0

**Comment by francisp2** [comment]
what exact message do you send ?

zigbee2mqtt/status ?

**Comment by Sergej569** [comment]
I send "on" or "off" but nothing happens on zigbee2mqtt.

**Comment by Koenkk** [comment]
Thats not a valid MQTT topic for z2m, look at the docs for your device for the correct topics

**Comment by hbk001** [comment]
Hope I got it correctly from Mqtt, this does not work on 1.38.0 but works fine on 1.37.0:
{"countdown":0,"linkquality":78,"power_on_behavior":"previous","state":"OFF","switch_type":"state"}
Just clicking a device on/off.

**Comment by Sergej569** [comment]
Thanks for the help. It works now
