### ISSUE TITLE
Issue with mosquitto:latest and large zigbee networks using z2m

### ISSUE THREAD

**Issue by bgreet** [Koenkk/zigbee2mqtt#22994]
### What happened?

Using eclipse-mosquitto:latest, devices populate into the HA integration but key controls do not (ie: switch on/off, light bulb on/off).  Certain data do populate like power consumption and other states.  All messages can be viewed when listening to /homeassistant/# from within the MQTT integration.  Additionally, when home assistant is restarted, all devices become unavailable until the coordinator is restarted.  I tried on fresh home assistant install with same outcome.  Tried to remove/readd mosquito home assistant integration with same issue.  Only able to fix the issue by rolling back to mosquitto:1.6 (though other versions newer than 1.6 and older than latest have not been tested)

Large device network (two zigbee networks each with individual mqtt topic, one network with 156 devices the other with 90) both using CC2652 coordinator by TubeZB.

### What did you expect to happen?

All entities would be available for all devices.  Restart would automatically allow all devices to be available.

### How to reproduce it (minimal and precise)

Use mosquitto:latest with large zigbee network.

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20221226

### Adapter

TubeZB (CC2652)

### Setup

Server is bare metal with home assistant , mosquito and zigbee2mqtt installed on docker

**Comment by richardstone** [comment]
I see the same. I'm using Mosquitto in docker with HA and z2m.

Recently updated z2m to 1.38.0 and all my devices became unavailable. When I deleted a device from HA, restarted z2m it got discovered but without any entities (i.e. switch/light, etc..)

Mosquitto: eclipse-mosquitto:2.0.15

**Comment by vvrockhound** [comment]
same issues with a small network - I have to downgrade z2m to 1.35 for it to respond to home assistant commands.
Mosquitto: eclipse-mosquitto:2.0.18
