### ISSUE TITLE
[New device support]: Please add support for frient SIRZB-111

### ISSUE THREAD

**Issue by wachtell** [Koenkk/zigbee2mqtt#22999]
### Link

https://frient.com/products/smart-siren/

### Database entry

{"id":"0x0015bc0041005a95","transaction":"umlhr-5"}' [2024-06-10 10:00:38] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/generate_external_definition', payload '{"data":{"id":"0x0015bc0041005a95","source":"const {deviceEndpoints, onOff, identify, battery, iasZoneAlarm, iasWarning} = require('zigbee-herdsman-converters/lib/modernExtend');\n\nconst definition = {\n    zigbeeModel: ['SIRZB-111'],\n    model: 'SIRZB-111',\n    vendor: 'frient A/S',\n    description: 'Automatically generated definition',\n    extend: [deviceEndpoints({\"endpoints\":{\"1\":1,\"43\":43}}), onOff({\"powerOnBehavior\":false}), identify(), battery(), iasZoneAlarm({\"zoneType\":\"generic\",\"zoneAttributes\":[\"alarm_1\",\"alarm_2\",\"tamper\",\"battery_low\"]}), iasWarning()],\n    meta: {\"multiEndpoint\":true},\n};\n\nmodule.exports = definition;"},"status":"ok","transaction":"umlhr-5"}

### Comments

I tried to follow the [support](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-2-adding-converter-s-for-your-device). However, the device still doesn't work. The SIRZB-110 is supported, but is 110 is going out of production, so the 111 will be the one to get going forward. I contacted the company and they said that the 110 driver should suffice.
Thank you in advance for looking at this. 

### External definition

```shell
const {deviceEndpoints, onOff, identify, battery, iasZoneAlarm, iasWarning} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['SIRZB-111'],
    model: 'SIRZB-111',
    vendor: 'frient A/S',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"43":43}}), onOff({"powerOnBehavior":false}), identify(), battery(), iasZoneAlarm({"zoneType":"generic","zoneAttributes":["alarm_1","alarm_2","tamper","battery_low"]}), iasWarning()],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
