### ISSUE TITLE
Sonoff SNZB-01 behaviour

### ISSUE THREAD

**Issue by BMWK1** [Koenkk/zigbee2mqtt#23029]
### What happened?

I have  succesfully integrated a Sonoff SNZB-01 button.
In MQTTExplorer i can see a first message sent with the right action message (e.g. "single"), but immediatly after, a second message is sent with an empty string ( action="") which means action off.

### What did you expect to happen?

I expect that for one press, there is only one message sent, either action="single" or "double" or "long", or empty string to switch off

### Zigbee2MQTT version

 1.29.2 commit: bb3e8f6

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP

### Setup

Synology x86-64/Docker/Domoticz

**Comment by Nerivec** [comment]
See https://github.com/Koenkk/zigbee2mqtt/issues/23089#issuecomment-2183695878

**Comment by Koenkk** [comment]
This is expected, see the [FAQ](https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty)
