### ISSUE TITLE
[New device support]: Mumubiz TH10 Temperature  Monitoring 4 Channel Switch 

### ISSUE THREAD

**Issue by atcom105** [Koenkk/zigbee2mqtt#23041]
TH10 Smart Temperature and Humidity Monitoring 4 Channel Switch Mumbiz

https://www.amazon.com/Mumubiz-Temperature-Monitoring-Compatible-Channel/dp/B0CSJZ2BKY/ref=sr_1_3?crid=FED8UIH117X0&dib=eyJ2IjoiMSJ9.INRiBZ04jpBjEhb5arVTX-bwO0aib5wENp_zBVdUNgPMrDfrcyxXganj-uj2vnGjbP3mu9c_tj5Zc0wg29LVQgcC0i64YF-kjs6Kx6ZvFBetzVSj7d7PsrJQhoXLFaEg1ROD2dpRgGdwXh5CV2YsOMfZnXvPeVa_OaaxrKq9NVtl0vMbJWmDoox7Jo45BVlB.5r7B28AHDPkHYFsGN9rij8oQzoUkbLhSnsi7YTB5LWc&dib_tag=se&keywords=Mumubiz&qid=1718310520&refresh=1&sprefix=mumubiz%2Caps%2C189&sr=8-3&th=1

### Database entry

{"id":24,"type":"Router","ieeeAddr":"0xa4c138d17e3b4f88","nwkAddr":46388,"manufId":4417,"manufName":"_TZ3218_ya5d6wth","powerSource":"Mains (single phase)","modelId":"TS000F","epList":[1,2,3,4,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,57345,57344,61184],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"dateCode":"","zclVersion":3}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[3,4,5,6,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":256,"inClusterList":[3,4,5,6,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":256,"inClusterList":[3,4,5,6,57345],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":100,"stackVersion":1,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1718308156189}

### Comments

Hi, I'm asking for help. I purchased this device but could not register it in HA ((((

### External definition

```shell
const {deviceEndpoints, identify, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS000F'],
    model: 'TS000F',
    vendor: '_TZ3218_ya5d6wth',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4}}), identify(), onOff({"powerOnBehavior":false,"endpointNames":["1","2","3","4"]})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by ivanfmartinez** [comment]
I got one of this devices also, I made the relays work using another device as reference, but was unable to make the temperature work using other tuya as example.

My device came from : https://pt.aliexpress.com/item/1005007040718331.html


```
// https://github.com/Koenkk/zigbee2mqtt/issues/23041
// https://pt.aliexpress.com/item/1005007040718331.html
// Based on https://github.com/Koenkk/zigbee-herdsman-converters/blob/53def671536f9ba0289e99d2dece68c03ada645b/src/devices/tuya.ts#L5048
//const {device Endpoints, identify, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const fz = require("zigbee-herdsman-converters/converters/fromZigbee");
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const reporting = require('zigbee-herdsman-converters/lib/reporting');M
const exposes = require("zigbee-herdsman-converters/lib/exposes");
const e = exposes.presets;

const definition = {
    zigbeeModel: ['TS000F'],
    model: 'TS000F',
    vendor: '_TZ3218_ya5d6wth',
    description: '4 channel relay and Temperature',
    extend: [tuya.modernExtend.tuyaOnOff({powerOnBehavior2: true, endpoints: ['l1', 'l2', 'l3', 'l4']})],
//    fromZigbee: [ fz.temperature],
    endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3, 'l4': 4};
        },
//    [ deviceEndpoints(
//          { "endpoints":{"l1":1,"l2":2,"l3":l3,"l4":4}}), 
//             identify(), 
//             onOff({"powerOnBehavior":false,
//             "endpointNames":["l1","l2","l3","l4"]})],
    configure: async (device, coordinatorEndpoint) => {
            await tuya.configureMagicPacket(device, coordinatorEndpoint);

            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff', 
//            'msTemperatureMeasurement'
            ]);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
            // Required to get the device to start reporting (-- Maybe needed? Copied this from another humidity sensor configuration)
//            await device.getEndpoint(1).command('manuSpecificTuya', 'dataQuery', {});
        },
    meta: { "multiEndpoint":true,
//            tuyaDatapoints: [
//                [1, 'temperature', tuya.valueConverter.divideBy10],
//                [2, 'humidity', tuya.valueConverter.raw],
//            ]
        },
    exposes: [ e.temperature(), e.humidity() ]
};

module.exports = definition;


```

![20240613_202428](https://github.com/Koenkk/zigbee2mqtt/assets/677001/4355a733-1393-4bbf-a65b-6c6baf20539a)
