### ISSUE TITLE
HS1CG-M is listed twice on the supported devices page

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#2304]
https://www.zigbee2mqtt.io/devices/HS1CG-M.html and https://www.zigbee2mqtt.io/devices/HS1CG_M.html

**Comment by sjorge** [comment]
Maybe another duplicate:
https://www.zigbee2mqtt.io/devices/HS1WL_HS3WL.html and https://www.zigbee2mqtt.io/devices/HS1-WL-E.html, or at least they look like they could be merged

**Comment by Koenkk** [comment]
This is true but unfortunately we cannot merge both, they use a different fromZigbee converter (see https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L3829)

**Comment by sjorge** [comment]
Bit confusing on the manufacturers part that they have 3 devices that are nearly identical but not quite :(
