### ISSUE TITLE
The zigbee2mqtt addon does not start

### ISSUE THREAD

**Issue by MrTrabucco** [Koenkk/zigbee2mqtt#23047]
### What happened?

Today I loaded an old backup from a few weeks ago where an old version of zigbee2mqtt was present... I updated to the new one, disabling and deleting the old one first, and now the situation is this:

The devices are all working correctly
The zigbee2mqtt addon does not start
In the log, I don't see any traces of it starting, but only the correct queries to the various devices, as if it was already started
Any suggestions?
Thanks

### Zigbee2MQTT version

1.38.0-1

### Adapter firmware version

0x26660700

### Adapter

Conbee2

### Setup

raspberry Pi4

**Comment by MrTrabucco** [comment]
Strange that whatever backup I reload, the same problem remains... the conbee2 should be working, since mqtt regularly sees the devices...

**Comment by francisp2** [comment]
Power off your Pi, and start it again.
