### ISSUE TITLE
Outdated dev dependency `@types/debounce`

### ISSUE THREAD

**Issue by Rotzbua** [Koenkk/zigbee2mqtt#23062]
### What happened?

`@types/debounce` is not required because `debounce` now includes types.
https://github.com/sindresorhus/debounce/releases/tag/v2.0.0 

### What did you expect to happen?

Remove it.

### Zigbee2MQTT version

dev

### Adapter firmware version

-

### Adapter

-

### Setup

git

**Comment by Koenkk** [comment]
Thanks for the PR!
