### ISSUE TITLE
IKEA LED1537R6 toggle not working anymore

### ISSUE THREAD

**Issue by eilmi** [Koenkk/zigbee2mqtt#2306]
## What happend
After updating to zigbee2mqtt 1.7.0 {"state": "TOGGLE"} is only turning off the lamp.
It worked in both directions in version 1.6.0
I also tried to repair the bulb.

## How to reproduce it (minimal and precise)
send {"state": "TOGGLE"} to lamp while it is OFF. Nothing will happen.

## Debug Info
zigbee2mqtt version: 1.7.0
CC253X firmware version:

**Comment by Koenkk** [comment]
Thanks, fixed in latest dev.
