### ISSUE TITLE
docs: No mention of server requirement on Windows

### ISSUE THREAD

**Issue by stevenh** [Koenkk/zigbee2mqtt#23067]
### What happened?

If you follow the instructions for [installing on Windows](https://www.zigbee2mqtt.io/guide/installation/05_windows.html) once you have your device setup you end up with the following error:
```
[2024-06-15 13:05:21] info:     z2m:mqtt: Connecting to MQTT server at mqtt://localhost:1883
[2024-06-15 13:05:21] error:    z2m:mqtt: MQTT error:
[2024-06-15 13:05:21] error:    z2m: MQTT failed to connect, exiting..
```

This is due to the fact there's no mention in the Windows guide about setting up the server, as there is in the [getting started guide, which uses docker](https://www.zigbee2mqtt.io/guide/getting-started/#installation). This left me confused and searching around with no mention of what might be the cause. 

It would be good to split out the setup of MQTT and the MQTT server in the [getting started guide](https://www.zigbee2mqtt.io/guide/getting-started/#installation) as well as detailing the steps needed for install the MQTT server in the [Windows install guide](https://www.zigbee2mqtt.io/guide/installation/05_windows.html) such as a mention of [mosquitto](https://mosquitto.org/download/).

### What did you expect to happen?

MQTT to start when running `npm start`

### How to reproduce it (minimal and precise)

Follow the [Windows install guide](https://www.zigbee2mqtt.io/guide/installation/05_windows.html), note there is no mention of the need to setup a MQTT server such as [mosquitto](https://mosquitto.org).

### Zigbee2MQTT version

1.38.0 (commit #f1847301)

### Adapter firmware version

7.4.2 [GA]

### Adapter

EZSP

### Setup

Windows

**Comment by Nerivec** [comment]
Will be added in docs in next release! 😉
