### ISSUE TITLE
zigbee2mqtt 1.7 problem with network map

### ISSUE THREAD

**Issue by jarzebski** [Koenkk/zigbee2mqtt#2307]
hi, after update to 1.7 I have issue with bad network map (zigbee2mqtt/bridge/networkmap/raw). some nodes missing link info, but they are physically connected correctly. After downgrade to 1.6 all is ok

**Comment by FedeBZ** [comment]
hello, me too

**Comment by jasimancas** [comment]
Same here

**Comment by Koenkk** [comment]
Should be fixed in latest dev (should give same behaviour as 1.6.0). (reference #1961 )

**Comment by jasimancas** [comment]
Update to dev versión to fix the bug?

**Comment by Koenkk** [comment]
yes

**Comment by jasimancas** [comment]
![image](https://user-images.githubusercontent.com/15717847/68572735-7a1b3480-0466-11ea-9043-4b236d1b858a.png)
Thanks!

**Comment by Koenkk** [comment]
Looks great (meshing). Closing this as the issue has been fixed.

**Comment by lolorc** [comment]
![map](https://user-images.githubusercontent.com/10393822/68579501-902ff180-0474-11ea-8c18-2fcdf1ce9290.png)

**Comment by Kryzek** [comment]
My network maps has never looked this good. Could be a bit sexier but some routers are not connected to mains currently. But mesh looks very good! Thanks you! 

![zb-nw-graph](https://user-images.githubusercontent.com/20900883/68605707-82e72700-04b5-11ea-891e-b805d092d3c6.png)
