### ISSUE TITLE
[New device support]:  SLZB-07

### ISSUE THREAD

**Issue by adriaanos** [Koenkk/zigbee2mqtt#23076]
### Link

https://smlight.tech/product/slzb-07/

### Database entry

{"id":34,"type":"Router","ieeeAddr":"0x9035eafffe74e8d2","nwkAddr":15226,"manufId":4098,"manufName":"SMLIGHT","powerSource":"Mains (single phase)","modelId":"SLZB-07","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,1,3,4,5,6,8,37,4096],"outClusterList":[25,2821],"clusters":{"genBasic":{"attributes":{"modelId":"SLZB-07","manufacturerName":"SMLIGHT","powerSource":1,"zclVersion":8,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"","swBuildId":"ə�����\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0026b844c0","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"","swBuildId":"ə�����\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1718543626229}

### Comments

Hi, my new router is coming up as not supported, it is a SLZB-07. It originally came as a Zigbee Coordinator but using [smartlight flasher](https://smlight.tech/flasher/#flashingFAQ) I flashed the ZB Router firmware. It is showing up on Z2M but is showing as Unsupported.

### External definition

```shell
const {battery, identify, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['SLZB-07'],
    model: 'SLZB-07',
    vendor: 'SMLIGHT',
    description: 'Automatically generated definition',
    extend: [battery(), identify(), onOff({"powerOnBehavior":false})],
    meta: {},
};

module.exports = definition
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
