### ISSUE TITLE
[New device support]: Gledopto gl-sd-001p

### ISSUE THREAD

**Issue by Seveensv** [Koenkk/zigbee2mqtt#23092]
### Link

https://www.gledopto.com/h-col-380.html

### Database entry

{"id":36,"type":"Router","ieeeAddr":"0xa4c138845b41eac3","nwkAddr":52042,"manufId":4687,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-SD-001P","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":257,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"GL-SD-001P","manufacturerName":"GLEDOPTO","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230822","swBuildId":"20351203"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":0,"colorTempPhysicalMin":158,"colorTempPhysicalMax":495}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":36}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20230822","swBuildId":"20351203","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1718699341385}

### Comments

The seller claims that the zigbee2mqtt gl-sd-001 and gl-sd-001p is the same product. When I use the switch to change the status, it does not automatically update in zigbee2mqtt.   Sorry if I wrote this in the wrong section and thanks in advance.
![Screenshot_20240616_163800_Chrome](https://github.com/Koenkk/zigbee2mqtt/assets/75184523/1349ff1f-9669-4348-8a85-828c59ac10e9)

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['GL-SD-001P'],
    model: 'GL-SD-001P',
    vendor: 'GLEDOPTO',
    description: 'Automatically generated definition',
    extend: [identify(), light()],
    meta: {},
};

module.exports = definition;
```

**Comment by dtsd** [comment]
+1

**Comment by Koenkk** [comment]
Will be supported in tomorrows release!
