### ISSUE TITLE
Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by zuhair68** [Koenkk/zigbee2mqtt#23097]
### What happened?

I get this error while using the frontend

### Zigbee2MQTT version

1.38

### Adapter firmware version

20221226

### Adapter

zzh zStack3x0

### Setup

stansalone on PI

### Debug log

[log.txt](https://github.com/user-attachments/files/15889610/log.txt)

**Comment by DavidKaub** [comment]
I get basically the same error in docker 
> igbee2mqtt  | Using '/app/data' as data directory
zigbee2mqtt  | Starting Zigbee2MQTT without watchdog.
zigbee2mqtt  | [2024-07-26 11:20:28] error: 	z2m: WebSocket error: Invalid WebSocket frame: RSV1 must be clear
zigbee2mqtt  | [2024-07-26 11:20:29] error: 	z2m: WebSocket error: Invalid WebSocket frame: RSV1 must be clear

**Comment by dash042** [comment]
I have the same issue...
