### ISSUE TITLE
When selecting checkboxes or typing in fields in device/settings the checkboxes/fields clear themselves

### ISSUE THREAD

**Issue by gyrex** [Koenkk/zigbee2mqtt#23101]
### What happened?

When selecting checkboxes (such as disabled or retain etc.) or typing in fields (eg. Home assistant name) within the settings page of a device, the checkboxes and/or fields clear themselves automatically. See video below for an example.

https://github.com/Koenkk/zigbee2mqtt/assets/9957205/69373725-47d6-46ab-b302-4e61606972d0

### What did you expect to happen?

I'd expect that the checkboxes retain the inputted values

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee-P

### Setup

Docker

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
