### ISSUE TITLE
Tuya Motion Sensor - ZG-204ZL - Setting Illuminance interval results in 'Data request failed with error: 'MAC transaction expired' (240)'

### ISSUE THREAD

**Issue by Scoff123** [Koenkk/zigbee2mqtt#23106]
### What happened?

After successfully adding a Tuya Motion sensor ZG-204ZL to my Z2M network, I set all other settings in the 'Exposes' tab fine, but upon trying to set the 'Illuminance interval' to ANY number from 1 to 60, nothing happens for a few seconds, the state display still shows either 'null' or the previous interval setting, and then an error message appears saying 'Data request failed with error: 'MAC transaction expired' (240)'
Sometimes the setting remains as the old value, but sometimes, even with the error, the new value does eventually appear in the 'state' tab against the illuminance_interval. 

Error 2024-06-18 11:24:30Publish 'set' 'illuminance_interval' to 'UpstairsPIR' failed: 'Error: ZCL command 0xa4c1387c36560ee4/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":102,"datatype":2,"data":[0,0,0,60]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Error 2024-06-18 11:25:28Publish 'set' 'illuminance_interval' to 'UpstairsPIR' failed: 'Error: ZCL command 0xa4c1387c36560ee4/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":102,"datatype":3,"data":[]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'
Error 2024-06-18 11:26:16Publish 'set' 'illuminance_interval' to 'UpstairsPIR' failed: 'Error: ZCL command 0xa4c1387c36560ee4/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":102,"datatype":2,"data":[0,0,0,60]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'

### What did you expect to happen?

The new illuminance interval value to be set and begin showing in the 'state' tab and back in Home Assistant in the illuminance_interval entity. 

### How to reproduce it (minimal and precise)

Join ZG-204ZL to network with usual pairing/interview process. Enter a number in the blank/null field next to illuminance_interval in the 'Exposes' tab of the device. 

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20230507

### Adapter

Sonoff Dongle P

### Setup

Add-on in Home Assistant OS running as a VM in Proxmox on a Dell Optiplex

### Debug log

[log.log](https://github.com/user-attachments/files/15901275/log.log)

**Comment by InventoCasa** [comment]
The issue is still there. Setting the illuminance interval does NOT work. That's quite a bummer, as the device is only updating the illuminance when the door is opened / closed this way!

**Comment by oerix** [comment]
Having a similar issue, where I change to 'illuminance_interval' from '60' to '1', through Z2M/HA and it sets, but after a while it resets again.

Maybe this a hardware issue? Please could this be looked at? 

Thanks
