### ISSUE TITLE
disabled device still pinged

### ISSUE THREAD

**Issue by srg777** [Koenkk/zigbee2mqtt#23127]
### What happened?

I have disabled my device to prevent it is been binged, but not a luck - I still receiving error messages about failed pings

### What did you expect to happen?

i expect that zigbe2mqtt will not ping disabled device

### How to reproduce it (minimal and precise)

come to devise setting page and check disabled option, in the device list it marked as disabled

### Zigbee2MQTT version

1.38.0-dev commit: a9b8808

### Adapter firmware version

20220103

### Adapter

MSH

### Setup

MSH device

**Comment by Koenkk** [comment]
Could you try with the latest dev branch?

**Comment by srg777** [comment]
I have 1.38.0-dev

**Comment by Koenkk** [comment]
But not the latest one (https://github.com/Koenkk/zigbee2mqtt/commit/a9b8808237554316c5c97e9d9c990048733779e8)

**Comment by srg777** [comment]
It seems I have the latest

https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.38.0
￼
