### ISSUE TITLE
The switch TS0001 (_TZ3000_hzlsaltw) does not display consumption data, as well as voltage

### ISSUE THREAD

**Issue by Iversat** [Koenkk/zigbee2mqtt#23143]
### What happened?

I purchased this relay unit via Aliexpress, but when connected to the z2m, it was identified only as a switch, but it does not output data (current and voltage)

### What did you expect to happen?

Relay with full output of indicators

### How to reproduce it (minimal and precise)

I don't know

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20220301

### Adapter

zstack сс2652

### Setup

huawei matebook d14 2020

### Debug log

![image](https://github.com/Koenkk/zigbee2mqtt/assets/140331321/49f248bc-5020-4b8f-9cd3-579aeb63ed42)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/140331321/7487873f-b75c-4250-8105-4993a83c666a)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/140331321/2c9185af-afd1-4644-9ba4-62ee432d7061)

**Comment by Anry777** [comment]
The same problem
Cant see consumption on this device in z2m.. But in ZHA it works correctly.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by Anry777** [comment]
It work correctly. Grazz!!
