### ISSUE TITLE
(Suggestion/Tip) Zigbee 3.0 Devices

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#2314]
Hi,

I have seen the clear benefits of the Zigbee 3.0 network versus 1.2.
Would it be possible that in the Supported Devices section (https://www.zigbee2mqtt.io/information/supported_devices.html) it would be indicated which version of Zigbee supports each one?

I understand that if I have all Zigbee 1.2 devices, I won't have the advantages of migrating to 3.0, will I?

A row with the Zigbee version of each device would be great (might help with some)

**Comment by ciotlosm** [comment]
Would be nice for that page to include a few more filters:
- Is Router
- Powered by (batter vs power line)
- Manufacturer
- Type (lightbulb, relay, switch, motion, etc)

**Comment by jasimancas** [comment]
And for example split data in few rows (description, command (on/off, brightness), etc)

**Comment by Koenkk** [comment]
The manufacturer is already there (vendor), the other information can be added to the meta (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L3774). 

Something like:
- `deviceType`: `Router` or `EndDevice`
- `powerSource`: `Battery` or `AC Mains`
-  `type`: `bulb`, `relay`, etc.

Feel free to make PR's, I will make sure they end up in the docs.

**Comment by jasimancas** [comment]
I can, for example, split the description in two rows, one for description and another for "events" (on/off, etc)

And add another row with the ZIGBEE version (for example Xiaomi Zigbee 1.2)

Do you see it well?

I do the PR directly editing the file?

**Comment by Koenkk** [comment]
Desciption and supports (events) are already splitted.

Yes please directly edit the files
