### ISSUE TITLE
Error: ZCL command

### ISSUE THREAD

**Issue by Soe-Koh** [Koenkk/zigbee2mqtt#23146]
### What happened?

Don't know exactly for how long , but at least for some weeks, I get a lot of these errors. Most of the time it seems like everything works, but seems like one or the other device needs longer then before to react.

The errors all belong to devices of this type:  https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html

Runing the neweset zigbee2mqtt version: 1.38.0

Error 2024-06-23 18:50:29Publish 'set' 'state' to 'GR_Charger_2' failed: 'Error: ZCL command 0xa4c1385e720a0e8b/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11640 - 1 - 10 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:50:30Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":10583,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:50:31Publish 'set' 'state' to 'GR_Charger_2' failed: 'Error: ZCL command 0xa4c1385e720a0e8b/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":6067,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:50:37Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 229 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:50:47Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Error 2024-06-23 18:50:53Publish 'set' 'state' to '00_FL_Treppe' failed: 'Error: ZCL command 0x7cb03eaa00a2c786/3 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Error 2024-06-23 18:50:57Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Error 2024-06-23 18:51:00Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 233 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:51:14Failed to read state of 'GR_Charger_2' after reconnect (ZCL command 0xa4c1385e720a0e8b/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":6067,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')))

### What did you expect to happen?

No errors;-)

### How to reproduce it (minimal and precise)

Just keep it running

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20210708

### Adapter

Electrolama

### Setup

Proxmox on a Intel NUC

### Debug log

Error 2024-06-23 18:53:53Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":10583,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:54:00Publish 'set' 'state' to 'GR_Charger_2' failed: 'Error: ZCL command 0xa4c1385e720a0e8b/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 46955 - 1 - 158 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:54:02Publish 'set' 'state' to 'GR_Charger_5' failed: 'Error: ZCL command 0xa4c138f1978323e4/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 25109 - 1 - 167 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:54:03Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 9 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:54:13Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":49594,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:54:18Failed to read state of 'GR_Battery_Out2' after reconnect (ZCL command 0xa4c1384384d15127/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":15896,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')))
Error 2024-06-23 18:54:24Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Error 2024-06-23 18:54:26Publish 'set' 'state' to 'GR_Charger_4' failed: 'Error: ZCL command 0xa4c1389c1a3e8fb3/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":10583,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:54:36Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 25 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:54:59Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 27 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:55:22Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 31 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:55:32Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":49594,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:55:35Publish 'set' 'state' to '01_FL_Licht' failed: 'Error: ZCL command 0x842e14fffe368aba/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 1729 - 1 - 194 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:55:39Publish 'set' 'state' to '00_FL_Treppe' failed: 'Error: ZCL command 0x7cb03eaa00a2c786/3 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Error 2024-06-23 18:55:44Failed to read state of 'GR_Charger_1' after reconnect (ZCL command 0xa4c138f36f07df11/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)))
Error 2024-06-23 18:55:55Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 37 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:56:09Publish 'set' 'state' to '00_FL_Treppe' failed: 'Error: ZCL command 0x7cb03eaa00a2c786/3 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Error 2024-06-23 18:56:18Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 41 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:56:41Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 42 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:57:04Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 46 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:57:27Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 50 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:57:37Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":49594,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Error 2024-06-23 18:58:00Failed to read state of 'GR_Charger_1' after reconnect (ZCL command 0xa4c138f36f07df11/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 7880 - 1 - 219 - 6 - 1 after 10000ms))
Error 2024-06-23 18:58:01Publish 'set' 'state' to 'GR_Charger_1' failed: 'Error: ZCL command 0xa4c138f36f07df11/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49594 - 1 - 56 - 6 - 11 after 10000ms)'
Error 2024-06-23 18:58:11Publish 'set' 'state' to '00_FL_Treppe' failed: 'Error: ZCL command 0x7cb03eaa00a2c786/3 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Error 2024-06-23 18:58:24

**Comment by Koenkk** [comment]
You are running a very old firmware, try the new one provided in https://github.com/Koenkk/Z-Stack-firmware/discussions/496 and provide your feedback there.
