### ISSUE TITLE
IKEA Parasoll does not send battery status in real time 

### ISSUE THREAD

**Issue by Lacimaci78** [Koenkk/zigbee2mqtt#23157]
### What happened?

After inserting a new battery and loading it for the first time, the device says the battery status is 100%, but this status will never change from 100% to less than that, even if in reality the battery only has 50% after the measurement

### What did you expect to happen?

Should the battery stab change to the actual value in the set time interval

### How to reproduce it (minimal and precise)

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['PARASOLL Door/Window Sensor'],
    model: 'E2013',
    vendor: 'IKEA',
    description: 'PARASOLL Door/Window Sensor',
    fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
    toZigbee: [],
    exposes: [e.battery(), e.contact()],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
        await reporting.batteryPercentageRemaining(endpoint, {min: 3601, max: 43200, change: 1});
        await endpoint.read('genPowerCfg', ['batteryPercentageRemaining']);
    },
};

module.exports = definition;

### Zigbee2MQTT version

    1.38.0

### Adapter firmware version

mberZNet 7.4.3 [GA]

### Adapter

Nabu_Casa_SkyConnect_v1.0_e4b56c1175d8ed119da9776162c613ac-if00-port0

### Setup

RPi 5 8GB 

### Debug log

z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Okno Test', payload '{"ac_status":false,"battery":100,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":140,"restore_reports":false,"supervision_reports":false,"tamper":false,"test":false,"trouble":false,"update":{"installed_version":16777241,"latest_version":16777241,"state":"idle"}}'

**Comment by lrgabriel** [comment]
Sorry if this is already linked, but the discussion of this issue is here: #23156
