### ISSUE TITLE
[New device support]:  model: 'TS0601', vendor: '_TZE204_fwondbzy'

### ISSUE THREAD

**Issue by Destroyer061090** [Koenkk/zigbee2mqtt#23161]
### Link

https://www.aliexpress.us/item/1005004148507209.html?spm=a2g0o.order_list.order_list_main.17.25a23696CjBMer&gatewayAdapt=4itemAdapt

### Database entry

{"id":23,"type":"Router","ieeeAddr":"0xa4c138e6873f79fd","nwkAddr":46683,"manufId":4417,"manufName":"_TZE204_fwondbzy","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE204_fwondbzy","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1719323586268}

### Comments

Just pared the device and Z2M say "not supported"

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_fwondbzy',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by XFNeo** [comment]
I'm really looking forward to support for this device.
Thanks!

**Comment by tommaineult** [comment]
For information:
Vendor : MOES
Ref : ZSS-QY-HP-MS

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/7801

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by TatoMCSE** [comment]
Does it also come with Edge version for HA?

**Comment by Koenkk** [comment]
Yes, dev = edge

**Comment by TatoMCSE** [comment]
Hmmm, should it work out of the box when switched to dev? Asking as it still shows as unsupported on zigbee2mqtt-edge v1.39.0-dev with herdsman converters v19.71.1 <crying>

**Comment by Koenkk** [comment]
Yes, otherwise wait for tomorrows z2m release.

**Comment by pehon** [comment]
I've updated zigbee2mqtt to 1.39.1 and the device works like a charm. Thank you!

**Comment by XFNeo** [comment]
But unfortunately this sensor is also spamming in to zigbee network =(
![image](https://github.com/user-attachments/assets/f52bcd78-3ab3-4404-a949-da1c44023d31)

**Comment by Destroyer061090** [comment]
> But unfortunately this sensor is also spamming in to zigbee network =( ![image](https://private-user-images.githubusercontent.com/37923089/354609710-f52bcd78-3ab3-4404-a949-da1c44023d31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTQ3MDIsIm5iZiI6MTcyMjc5NDQwMiwicGF0aCI6Ii8zNzkyMzA4OS8zNTQ2MDk3MTAtZjUyYmNkNzgtM2FiMy00NDA0LWE5NDktZGExYzQ0MDIzZDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE4MDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZDY3MmZlNWFiZDEyMGE0MTkzNGQ4ZTAxMTdjYmQ5OTRmMzhiMGViZjA4OTQ1NjY2YzRiNTQ5NTQwZWQwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zpoyJ7PY9WjY4xLXktTcAhro309z1Efl8AmZ-T8l_4Q)

What could be the side effect of this?

**Comment by XFNeo** [comment]
@Destroyer061090 you can read this topic
https://github.com/Koenkk/zigbee2mqtt/issues/19045

**Comment by arnevanhove** [comment]
Crap just ordered a ZSS-QY-HP from moes in the hopes it would not spam my zigbee network. Anybody knows if this device can be configured so it does not spam? for example, disabling the distance feature?
