### ISSUE TITLE
CO2 sensor TS0601 _TZE204_ogkdpgy2 defined but shows as not supported

### ISSUE THREAD

**Issue by zlobnic** [Koenkk/zigbee2mqtt#23205]
### What happened?

I have CO2 censor with ZigBee support (https://aliexpress.ru/item/1005003446514631.html). 

Zigbee2MQTT version 1.38.0 (HA 2024.6.4) can see it and also adds. But there's no support. Don't understand what to do... tried EDGE version, no luck.

![Sab72086cd54f4a04998f659b91f99f43I jpg_640x640](https://github.com/Koenkk/zigbee2mqtt/assets/39958947/dbb9a341-bae3-417e-856a-cefb4f3c05d4)
![CleanShot 2024-06-29 at 17 03 28@2x](https://github.com/Koenkk/zigbee2mqtt/assets/39958947/62c56104-b8fa-4679-bb29-e51396215b8d)
![CleanShot 2024-06-29 at 17 11 42@2x](https://github.com/Koenkk/zigbee2mqtt/assets/39958947/744a9624-e6f8-479a-b304-a13c55ff84db)
![Sda3ba359bb964ab9b5f902fdde7272f2t](https://github.com/Koenkk/zigbee2mqtt/assets/39958947/036b26d6-5e62-4972-9b18-780f4ec0b317)

Another ZigBee device works fine (Xiaomi Button)

### What did you expect to happen?

CO2 data...

In this video same sensor works fine: https://youtube.com/watch?v=4aQye8tArmM

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20201128

### Adapter

Wireless Zigbee CC2531 CC2540 Sniffer

### Setup

Addon @ H96Max

**Comment by zlobnic** [comment]
UPD: this tip worked for me: https://github.com/Koenkk/zigbee2mqtt/issues/23183#issuecomment-2198652112

**Comment by malexmnt** [comment]
for more understanding:
1.stop z2m
2. you need to change _TZE204_ogkdpgy2 to _TZE200_ogkdpgy2 in the text file /homeassistant/zigbee2mqtt/database.db
3.start z2m, and check if the device works.

**Comment by rokiden** [comment]
I have fixed flood bug of this device with [custom firmware](https://github.com/rokiden/Tuya_CO2_STC8/blob/tuya_co2/user/README.md).

**Comment by heisenberg2980** [comment]
> for more understanding: 1.stop z2m 2. you need to change _TZE204_ogkdpgy2 to _TZE200_ogkdpgy2 in the text file /homeassistant/zigbee2mqtt/database.db 3.start z2m, and check if the device works.

@malexmnt do you know if this workaround is still needed? I thought by now this device would have been added to z2m already

**Comment by vgdh** [comment]
> > for more understanding: 1.stop z2m 2. you need to change _TZE204_ogkdpgy2 to _TZE200_ogkdpgy2 in the text file /homeassistant/zigbee2mqtt/database.db 3.start z2m, and check if the device works.
> 
> @malexmnt do you know if this workaround is still needed? I thought by now this device would have been added to z2m already, but I just tried and z2m says the device is unsupported

I've just now tested the method and it works
