### ISSUE TITLE
[New device support]:Philips Hue Phoenix Table Lamp [31154]

### ISSUE THREAD

**Issue by Kevin6872** [Koenkk/zigbee2mqtt#23228]
### Link

https://www.amazon.sg/Philips-Phoenix-Dimmable-Requires-Assistant/dp/B00W1KYAZ8

### Database entry

{"id":64,"type":"Router","ieeeAddr":"0x0017880102323df6","nwkAddr":37468,"manufId":4116,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"HML005","epList":[11,242],"endpoints":{"11":{"profId":49246,"epId":11,"devId":544,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"HML005","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":11,"dateCode":"20140507","swBuildId":"5.38.1.14169"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"colorTemperature":370}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":11,"dateCode":"20140507","swBuildId":"5.38.1.14169","zclVersion":1,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1719863903602}

### Comments

Hi, at the moment these functions work fine with the auto-generated external definition: State, Brightness, Color temp, Effect. these functions give an error.

Color temp startup : z2m: Publish 'set' 'color_temp_startup' to '0x0017880102323df6' failed: 'Error: ZCL command 0x0017880102323df6/11 lightingColorCtrl.write({"startUpColorTemperature":153}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

Power-on behavior : z2m: Publish 'set' 'power_on_behavior' to '0x0017880102323df6' failed: 'Error: ZCL command 0x0017880102323df6/11 genOnOff.write({"startUpOnOff":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['HML005'],
    model: 'HML005',
    vendor: 'Philips',
    description: 'Automatically generated definition',
    extend: [identify(), light({"colorTemp":{"range":[153,454]}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `MODEL.png` (update `model` accordingly) 
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
