### ISSUE TITLE
Sonoff Basic ZBR3

### ISSUE THREAD

**Issue by ciB89** [Koenkk/zigbee2mqtt#2322]
This is not a bug report. 

I just found this new device by Sonoff ([video](https://www.youtube.com/watch?v=yFwJAQFndEo)) that instead of Wifi uses zigbee with a CC2530 ([Link](https://www.itead.cc/sonoff-basiczbr3.html)). It's quite cheap, although I only found one vendor on Ali-Express so far. I am pretty sure that many of you guys would be liking such a device!

**Comment by Koenkk** [comment]
Yes, it's already supported: https://www.zigbee2mqtt.io/devices/BASICZBR3.html :smile:

**Comment by ciB89** [comment]
Oh wow - great ty! 😄
