### ISSUE TITLE
[Wrong device]: Moes ZB-LZD10-RCW detected as Tuya TS0505B_1

### ISSUE THREAD

**Issue by wraeuk** [Koenkk/zigbee2mqtt#23230]
### Link

https://www.aliexpress.com/item/1005004382991985.html

### Model

ZB-LZD10-RCW

### Description

10W RGB+CCT Smart Downlight

### Vendor

Moes

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/ZB-LZD10-RCW.png

### Database entry

{"id":10,"type":"Router","ieeeAddr":"0xa4c1387c2a278a83","nwkAddr":4512,"manufId":4107,"manufName":"_TZ3210_jjqdqxfq","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,6280,4,5,6,8,768,10,4096,65518],"outClusterList":[25,4096,65518],"clusters":{"genLevelCtrl":{"attributes":{"61440":1000}},"genBasic":{"attributes":{"hwVersion":0}},"lightingColorCtrl":{"attributes":{"57344":1000,"57345":[1000,65536113],"61453":1,"colorCapabilities":8,"colorTempPhysicalMin":143,"colorTempPhysicalMax":500,"tuyaRgbMode":0}},"genOnOff":{"attributes":{"61440":0,"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":112,"stackVersion":2,"hwVersion":0,"swBuildId":"z.1.0","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1719886938850}

### Notes

Curiously I had one of the 15 lights correctly detect, despite all being bought at the same time (and looking physically identical.) Removing and repairing any of the incorrectly detected ones goes back to TS0505B_1, I haven't been game to re-pair the correctly detected one, but it's definitely detected incorrectly in the past.

The correctly detected device has the following db entry
{"id":11,"type":"Router","ieeeAddr":"0xa4c1386bac72e5b4","nwkAddr":22013,"manufId":4417,"manufName":"_TZ3210_s9lumfhn","powerSource":"Mains (single phase)","modelId":"TS0505B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[3,4,5,6,4096,8,768,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505B","manufacturerName":"_TZ3210_s9lumfhn","powerSource":1,"zclVersion":3,"appVersion":101,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":8880,"currentY":2615,"colorTemperature":168,"currentHue":170,"currentSaturation":254}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":39}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":101,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1719886887988}

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by Koenkk** [comment]
> The "correct" device has working brightness adjustment in color_xy whereas the others do not

I don't understand fully, can you explain in more detail what the issue is?

**Comment by wraeuk** [comment]
Yep, sorry.

The devices in question are physically identical.
The device with "manufName":"_TZ3210_s9lumfhn" is working as expected
The device with "manufName":"_TZ3210_jjqdqxfq" mostly works except when changing to color_xy, where the brightness adjustment doesn't do anything (stays at 100%, or goes to off at 0%). Brightness adjustment works fine when using color_temp.

I logged a new device support issue for this ages ago and never got around to looking at it harder (it aged out) https://github.com/Koenkk/zigbee2mqtt/issues/17570 which has some info from a tuya gateway if that helps make sense of it.

If this helps, the generated external converters for each

**_TZ3210_s9lumfhn**
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0505B'],
    model: 'TS0505B',
    vendor: '_TZ3210_s9lumfhn',
    description: 'Automatically generated definition',
    extend: [identify(), light({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"]}})],
    meta: {},
};

module.exports = definition;

**_TZ3210_jjqdqxfq**
const {identify} = require('zigbee-herdsman-converters/lib/modernExtend');
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['TS0505B'],
    model: 'TS0505B',
    vendor: '_TZ3210_jjqdqxfq',
    description: 'Automatically generated definition',
    extend: [identify(), philipsLight({"color":true})],
    meta: {},
};

module.exports = definition;

**Comment by Koenkk** [comment]
with the tuya gateway, did the brightness change when color_xy was used?

**Comment by wraeuk** [comment]
Yep, sure did.

**Comment by Koenkk** [comment]
From what I understand:
- `_TZ3210_s9lumfhn` -> uses standard commands
- `_TZ3210_jjqdqxfq` -> is controlled through datapoints?

**Comment by wraeuk** [comment]
That does seem to be the case. Here's a full listing of the datapoints from the tuya portal if that helps any

{
    "1": "ON/OFF",
    "2": "Mode",
    "209": "Cycle Timing",
    "210": "Vacation Timing",
    "3": "Brightness",
    "30": "Rhythms",
    "31": "Light to sleep",
    "32": "Light to wake",
    "33": "Power Off Memory",
    "34": "Do not Disturb",
    "35": "ON/OFF Gradient",
    "4": "Color Temp",
    "5": "Colorful",
    "6": "Scene",
    "7": "Timer",
    "8": "Music",
    "81": "zigbee light link threshold",
    "9": "Adjust"
}

The "Brightness" data point does *not* change when adjusting brightness when using the "Color" mode (dp2)

When set to the "white" mode (dp2) the Color Temp (dp4) and Brightness (dp2) points work, and are values from 0-1000

I'm not sure if this is standard, as I haven't looked at _TZ3210_s9lumfhn  on the tuya gateway, but I can if that would help.

**Comment by Koenkk** [comment]
Can you try to write a simple external converter using datapoints with e.g. just the `state`? You can find an example here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/1fe26bb1ed52f10ab7c7a7b219d500476f852958/src/devices/tuya.ts#L2001

**Comment by eerison** [comment]
@Koenkk 

I saw that you fixed some wrong model detection changing this "magical number/reference", how do I know what is the correct one for my device? I am stuck on this 🥲🥲.

**Comment by husnainali09** [comment]
Did you find a fix for this. Not working properly for me.

<img width="2338" height="1254" alt="Image" src="https://github.com/user-attachments/assets/a8ba8680-85e7-4951-ba99-8423e3ed0811" />

**Comment by husnainali09** [comment]
These lights work very inconsistently with Z2M. Is this a known issue ?

**Comment by husnainali09** [comment]
@wraeuk Did you manage to get these lights to work properly ?

**Comment by wraeuk** [comment]
I never got around to making colour + brightness work, but I don't have any issues with temp + brightness which is all I really use it for. If you're having other issues with standard operation I would guess it's another revision of the light which changes something inexplicably.

**Comment by husnainali09** [comment]
@wraeuk Do you mind sharing what it shows up as in Z2M. Mine show up at TS0505B ? They work but are inconsistent. Sometimes they will turn off and on correctly and sometimes they wont respond.

**Comment by wraeuk** [comment]
The two variants I have are
_TZ3210_jjqdqxfq (10W RGB+CCT Smart Downlight)
_TZ3210_s9lumfhn (10W RGB+CCT Smart Downlight)

jjqdqxfq has broken logic for RGB brightness, but is otherwise working perfectly.
s9lumfhn is fully working.

The typical Tuya curse is that the hardware will look identical but implement different logic and internal hardware arbitrarily and as I had happen to me, I had a different internal hardware from lights all bought in the same batch... but was lucky enough that they all mostly work anyway. Based on your screenshot, you technically have a completely different light to me and you'll need to poke around https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html

Or it's just a dud, or you have other Zigbee network related issues.

**Comment by FVerhamme** [comment]
The same light is detected at my side as _TZ3210_wbsgmojq 
Please also add the following to
[zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters/tree/master)/[src](https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/src)/[devices](https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/src/devices)
/tuya.ts

Line 2568
original:    tuya.whitelabel("Moes", "ZB-LZD10-RCW", "10W RGB+CCT Smart Downlight", ["_TZ3210_s9lumfhn", "_TZ3210_jjqdqxfq", "_TZ3210_dwzfzfjc"]),

new:  tuya.whitelabel("Moes", "ZB-LZD10-RCW", "10W RGB+CCT Smart Downlight", ["_TZ3210_s9lumfhn", "_TZ3210_jjqdqxfq", "_TZ3210_dwzfzfjc", "_TZ3210_wbsgmojq"]),

**Comment by pranjal-joshi** [comment]
Ordered bunch of these ZB-LZD10-RCW. Curious to know if they act as a zigbee router as well because they're always mains powered. 
@wraeuk @FVerhamme can you guys shed light on this?

**Comment by wraeuk** [comment]
They're routers for me, but it's tuya so YMMV

**Comment by FVerhamme** [comment]
Yes it's routing, but as @wraeuk said: It's Tuya
