### ISSUE TITLE
All Parameters in  Parameters can't stay active

### ISSUE THREAD

**Issue by cddu33** [Koenkk/zigbee2mqtt#23245]
### What happened?

When i click on "Retain" for exemple , 1s after, "Retain" is disable
![Vidéo sans titre ‐ Réalisée avec Clipchamp (1)](https://github.com/Koenkk/zigbee2mqtt/assets/59371705/6294dc81-2096-4895-a6e4-faee072b409c)

### What did you expect to happen?

Parameters stay active

### How to reproduce it (minimal and precise)

Select device, Select Parameters, click on Retain

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

 20230507

### Adapter

 zStack3x0 

### Setup

vm debian 11

**Comment by WarC0zes** [comment]
Hi,
I noticed the same behavior, when wanting to add an attribute filter.
![z2m dashboard](https://github.com/Koenkk/zigbee2mqtt/assets/91471397/173f5747-8661-49db-bff6-004b68f6a6e6)

**Comment by Koenkk** [comment]
Can you check if this is solved by disabling permit join?

**Comment by cddu33** [comment]
Hi , Permit Join is not active

**Comment by WarC0zes** [comment]
Hi,
Same, Permit join is set to false.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/91471397/26253d0e-7dab-477c-8468-ac59e9017cc5)
