### ISSUE TITLE
Problem with Button Light Recognition in Zigbee2MQTT

### ISSUE THREAD

**Issue by albertrsilva159** [Koenkk/zigbee2mqtt#23247]
### Link

https://shopee.com.br/AVATTO-Tuya-Smart-ZigBee-interruptor-De-Luz-4x4-Brasil-4-6-Gang-2-Vias-Controle-RF-Toque-Trabalho-Com-Alexa-Google-Home-i.857873964.23916435717?sp_atk=8761e804-1f44-4c47-a1ce-0255fbb0c753&xptdk=8761e804-1f44-4c47-a1ce-0255fbb0c753

### Database entry

I don't know

### Comments

The switch is recognized and works perfectly, but the feature to turn the button lights on and off is not recognized. The brand is Avatto and the switch has six buttons.
I am using Home Assistant with Zigbee2MQTT

### External definition

```shell
const {deviceEndpoints, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0006'],
    model: 'TS0006',
    vendor: '_TZ3000_jyupj3fw',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6}}), onOff({"powerOnBehavior":false,"endpointNames":["1","2","3","4","5","6"]})],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by nk2261** [comment]
Same issue with:
 https://www.zigbee2mqtt.io/devices/43084.html#enbrighten-43084
https://www.zigbee2mqtt.io/devices/43078.html#enbrighten-43078
