### ISSUE TITLE
Wrong firmware version displayed

### ISSUE THREAD

**Issue by Diaoul** [Koenkk/zigbee2mqtt#23279]
### What happened?

Zigbee2MQTT is showing outdated firmware information on paired devices:

#### Not working :-1: 
1. I had a Legrand 067773 paired to zigbee2mqtt showing version 0x2a
2. I removed it and paired it to the Legrand Gateway, it's now showing version 0x46 (70 in decimal)
3. I removed it and paired it again to zigbee2mqtt, it's showing the **incorrect** version 0x2a

Sometimes, it happened that I updated some devices outside zigbee2mqtt and when I paired them again they were still showing old firmware information.

#### Working :+1: 
Now if I do the same thing, but shut down zigbee2mqtt when the device is not paired anymore, it works:
1. I had a Legrand 067773 paired to zigbee2mqtt showing version 0x2a
2. I removed it and paired it to the Legrand Gateway, it's now showing version 0x46 (70 in decimal)
4. I stopped zigbee2mqtt then started it again
5. I removed it and paired it again to zigbee2mqtt, it's showing the **correct** version 0x46

:point_right: Obviously I don't want to do that for all my devices :grimacing:

### What did you expect to happen?

The correct firmware version is displayed without the need for a time-consuming exercise.

### How to reproduce it (minimal and precise)

This would be hard to reproduce... However, I'm interested in knowing when is a firmware version refreshed from the device? It smells like a cache invalidation issue.

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

20230507

### Adapter

tube_zb_gw_cc2652p2_poe

### Setup

Home Kubernetes

**Comment by Diaoul** [comment]
@Koenkk could this be causing other issues like on checking firmware versions online? :thinking:

**Comment by Loic691** [comment]
+1
Legrand battery device have very very strange issues....
It's not working at home...
Battery drain, event not catched, pairing issues,....
