### ISSUE TITLE
WSDCGQ01LM Temperature/humidity senson refresh rate very slow

### ISSUE THREAD

**Issue by RadekLorenc** [Koenkk/zigbee2mqtt#23284]
### What happened?

After last zigbee2mqtt update 1.39.0-1 WSDCGQ01LM Temperature/humidity senson refresh rate is very slow. One change of temeperature in couple of minutes... earlier wasn't problem with that at all
![screen](https://github.com/Koenkk/zigbee2mqtt/assets/85805905/c8f6a462-acb5-417a-91b0-ce48490966f6)

### What did you expect to happen?

I expect that this will be repaired

### Zigbee2MQTT version

1.39.0-1

### Adapter firmware version

20211217

### Adapter

CC2652P

### Setup

add-on

**Comment by lux73** [comment]
you are not able to change the polling Rate

Sometimes it changes the Temperature within 30 Seconds other time it does not change for 2 hours

I had to replace all cheap Aquara with Danfoss Temp Sensors - they will send an update at least all 30min
