### ISSUE TITLE
Danfoss Ally Pairing Failed 

### ISSUE THREAD

**Issue by schneili1** [Koenkk/zigbee2mqtt#23297]
### What happened?

I tried to Pair some Danfoss Ally Thermostats, bit it Failed Mutlible Times.
After checking the Model Nuber it turned Out the device is not Supportet yet (014G2420).
Is there a Soloution? 
Thanks in Advance :) 

Store Linkt to Danfoss ( https://store.danfoss.com/de/de/Climate-Solutions-W%C3%A4rmetechnik/Heizk%C3%B6rperthermostate/F%C3%BChlerelemente-f%C3%BCr-Heizk%C3%B6rper/Elektronischer-Heizk%C3%B6rperthermostat/Heizk%C3%B6rperthermostat%2C-Danfoss-Ally%E2%84%A2%2C-Adaptertyp%3A-RA%3B-M30%2C-2-4-GHz/p/014G2420 )

### Zigbee2MQTT version

1.39.0-1

### Adapter firmware version

latest

### Adapter

SkyConnect

### Setup

HomeAssitant

**Comment by lux73** [comment]
even its not supported yet - it should be possible to pair

**Comment by schneili1** [comment]
No, it's trying to pair but always fails

**Comment by lux73** [comment]
then anything is not correct in your Setup

pairing should be possible anytime

**Comment by schneili1** [comment]
I just tried another one, and it worked it's even Showing a Symbol and as Supported
