### ISSUE TITLE
Last upgrade(s) rename base_topic, entities are duplicated

### ISSUE THREAD

**Issue by lecourtb** [Koenkk/zigbee2mqtt#23294]
### What happened?

After upgrading Z2M from 1.36.0-1 to 1.39.0-1, all my zigbeee entities id are rediscovered and renamed with suffix "_2".
I noticed that in Z2M MQTT parameters, the **base topic** which was "**zigbee2mqtt**" before upgrade was renamed to "**zigbee2mqttHA**" after upgrade. 

I reproduced two times the problem (thanks to ha backups) and give up try to upgrade !

Later, I also tried a third upgrade with `base_topic: zigbee2mqtt` in `configuration.yaml` but without success.

Thanks for your help.

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20230507

### Adapter

zStack3x0

### Setup

add-on

**Comment by dermotos** [comment]
+1 
I get the same. It's fine after restarting the Zigbee2Mqtt Add on after updating. But after the next system restart, all Zigbee entities are renamed with an `_2` suffix. 
I've restored from backup and tried again and this consistently occurs.

**Comment by Koenkk** [comment]
Do you have a `base_topic` set in the Z2M addon configuration page? Try setting that to the correct topic.

**Comment by lecourtb** [comment]
I did it, but it was restored to zigbee2mqttHA each z2m restart

**Comment by Koenkk** [comment]
So if you change the `base_topic` in the z2m addon page (not the `configuration.yaml`!) to `zigbee2mqtt`, start the addon and restart it, it changes back to `zigbee2mqttHA`?

**Comment by Wendigogo** [comment]
I got the exact same issue (since 1.38.0-1 FYI). I had to rollback to 1.37.0-1 and remove all my "_2" devices.

> So if you change the `base_topic` in the z2m addon page (not the `configuration.yaml`!) to `zigbee2mqtt`, start the addon and restart it, it changes back to `zigbee2mqttHA`?

I did this and everything is fine now. I tried rebooting Z2M module and HA and my `base_topic` remains unchanged.
I still don't know why/how it had been changed BTW.

PS : I guess #23235 is a duplicate of this one.

**Comment by Wendigogo** [comment]
> I did it, but it was restored to zigbee2mqttHA each z2m restart

Have you changed it in the z2m addon page as said by @Koenkk or in Web UI page ?
I did it from addon page. Maybe you should try from here?

Enjoy!
