### ISSUE TITLE
Water irrigation valve  GiEX QT06_2 - inverted  STATE

### ISSUE THREAD

**Issue by janumix** [Koenkk/zigbee2mqtt#23308]
### What happened?

Hi

It seens to me that GiEX QT06_2 has inverted STATE value. It's reported to be ON whielst there are no water flow and vice versa. In order to start irrigation I need to switch it OFF but all flow parameters report zero (quite logical if valve is closed). 
Anyone suffer the same ?

Regards 
Janusz

### Zigbee2MQTT version

1.37.1 commit: cda867a3

### Adapter firmware version

20220507

### Adapter

 zStack3x0

### Setup

plain, PI3

**Comment by cigoe** [comment]
I am seeing this as well, the old model works as expected but the newer one is inverted. 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/giex.ts#L59-L89

Maybe adding an inverted state to the exposes for the newer model only would fix it?

`e.binary(legacy.giexWaterValve.state, ea.STATE_SET, 'OFF', 'ON').withDescription('State'),` would work?
