### ISSUE TITLE
SNZB-01P  bind not effective

### ISSUE THREAD

**Issue by liangjia2019** [Koenkk/zigbee2mqtt#23304]
### What happened?

I have two devices, SNZB-01P and SNZB-01, and there was an issue while executing a bind on them and another dual channel switching device 
SNZB-01 Perfect Execution
![图片](https://github.com/Koenkk/zigbee2mqtt/assets/52771300/978dc9a0-4996-4d2b-b666-267411bff030)
SNZB-01P binds normally, but the device has never been triggered to execute normally
![图片](https://github.com/Koenkk/zigbee2mqtt/assets/52771300/8fd78d39-9aa3-4f06-b172-4cd9e01aeef1)
![图片](https://github.com/Koenkk/zigbee2mqtt/assets/52771300/3a11b6f1-b1c8-4885-8aaa-6f5193fc7c9a)
[SNZB-01P_bind_Z2M.zip](https://github.com/user-attachments/files/16140048/SNZB-01P_bind_Z2M.zip)
![图片](https://github.com/Koenkk/zigbee2mqtt/assets/52771300/6cecf684-d4c7-4980-9cdc-96c620f95fd6)
From the perspective of network sniffing, devices do indeed have successful responses

Does he need more configuration or operation? Please let me know. Thank you

### Zigbee2MQTT version

1.39.0 commit: 03269267

### Adapter firmware version

20240709

### Adapter

skyconnect

### Setup

 x86-64

**Comment by liangjia2019** [comment]
@Koenkk can you help us

**Comment by Koenkk** [comment]
After they are bound, do you see the SNZB-01 sending on/off commands to the switch? If not, then this an issue of the SNZB-01, not of z2m.

**Comment by ilbarone87** [comment]
I have same issue, the pairing goes fine but no on/off triggering. 
Have force deleted many times (also force delete and restart container and then re-pair) but no luck.
 @liangjia2019 have you manage to solve this or is still an issue for you too

**Comment by ilbarone87** [comment]
Any reason why this reported as failed?

z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/bind', payload '{"data":{"clusters":["genOnOff"],"failed":[],"from":"0x003c84fffece4137/1","to":"led_cucina_top/1"},"status":"ok","transaction":"sgyhr-1"}'

**Comment by liangjia2019** [comment]
> After they are bound, do you see the SNZB-01 sending on/off commands to the switch? If not, then this an issue of the SNZB-01, not of z2m.

You're right. This is indeed a problem with SNZB-01P, and I will push the team to solve it

**Comment by liangjia2019** [comment]
> Any reason why this reported as failed?
> 
> `z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/bind', payload '{"data":{"clusters":["genOnOff"],"failed":[],"from":"0x003c84fffece4137/1","to":"led_cucina_top/1"},"status":"ok","transaction":"sgyhr-1"}'`

The key point when setting up is that you need to wake up the device through buttons or other means.
Unfortunately, there are some issues with the binding implementation mechanism of this device, and the effect cannot meet expectations

**Comment by ifurnadjiev** [comment]
> You're right. This is indeed a problem with SNZB-01P, and I will push the team to solve it

@liangjia2019 any progress on this? Are there any firmware update plans that address this issue?

**Comment by Jerepain** [comment]
I'ml looking forward to it as well

> > You're right. This is indeed a problem with SNZB-01P, and I will push the team to solve it
> 
> [@liangjia2019](https://github.com/liangjia2019) any progress on this? Are there any firmware update plans that address this issue?

**Comment by liangjia2019** [comment]
We are planning to sort out and correct the unreasonable implementation of the sensor. We can expect that it will be implemented normally

**Comment by Fohdeesha** [comment]
@liangjia2019 any update on new firmware for these?

**Comment by AlbertoKarakoutev** [comment]
Checking in for updates on this. It's the same behaviour for me - output clusters are there and binding completes normally, but nothing is actually controlled when pressing the button.

**Comment by PetitPhoenix** [comment]
Hello, I still have issues with binding and don't see any OTA update.

@liangjia2019 do you have any update?

**Comment by Fexiven** [comment]
@liangjia2019 this issue is sadly still open. Are there any updates?

**Comment by uschindler** [comment]
Any update on new firmware? The SNZB-01P is a nice small device, is there a firmware update planned?

I still have 0x00002200 firmware and Koenkk has no updates yet.

**Comment by sbraz** [comment]
I'll copy what another user mentioned in https://github.com/Koenkk/zigbee-OTA/pull/940: Sonoff declares that the SNZB-01P does not support binding, see https://sonoff.tech/en-us/products/sonoff-orb-4-in-1-zigbee-smart-scene-button-snzb-01m:

<img width="1333" height="580" alt="Image" src="https://github.com/user-attachments/assets/14ebde0f-5ab4-4eb9-a916-f8cf9c942409" />

**Comment by Fexiven** [comment]
I don't see why they wouldn't make it work. Isn't it just a tiny firmware update?

**Comment by liangjia2019** [comment]
I have communicated with the corresponding product manager again, and we will have a plan for future support of this feature. You can look forward to it

**Comment by wjarka** [comment]
> I have communicated with the corresponding product manager again, and we will have a plan for future support of this feature. You can look forward to it

That's awesome to hear. Are you aware of any timelines for this?

Not that it's urgent, just curious :)

**Comment by ifurnadjiev** [comment]
@liangjia2019 3 months later we are still looking forward and waiting for it. Any updates or ETA?

**Comment by ifurnadjiev** [comment]
I'm loosing hope that this issue will be resolved at all.

**Comment by Fexiven** [comment]
@liangjia2019 why are you letting us down? You said there are plans for it any yet we're waiting. :( This is such a wanted feature and it's getting ignored

**Comment by Fexiven** [comment]
Still nothing?

**Comment by ifurnadjiev** [comment]
I lost hope this issue to be fixed. 2 years past and nothing.

**Comment by Fexiven** [comment]
> I lost hope this issue to be fixed. 2 years past and nothing.

I did some research and was able to create a minimal firmware for the SNZB-01P, which supports binding, i will refine the code now and share my progress...

**Comment by Fexiven** [comment]
https://github.com/Fexiven/snzb01p-custom-firmware
