### ISSUE TITLE
[New device support]: Innr AE 262

### ISSUE THREAD

**Issue by zappydood** [Koenkk/zigbee2mqtt#23318]
### Link

https://www.amazon.com/innr-Zigbee-Philips-SmartThings-Dimmable/dp/B0CHM7WJXD?th=1

### Database entry

"id":29,"type":"Router","ieeeAddr":"0xa4c1380908e57e3b","nwkAddr":26592,"manufId":4454,"manufName":"innr","powerSource":"Mains (single phase)","modelId":"AE 262","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"AE 262","manufacturerName":"innr","powerSource":1,"zclVersion":8,"appVersion":21,"stackVersion":54,"hwVersion":1,"dateCode":"20231112","swBuildId":"1.5.3"}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":

### Comments

I am  new to zigbee2mqtt and I wanted to just make someone aware the ae262 by innr isnt supported but they have a ton of actually supported bulbs listed. I just got this from amazon today. I don't feel like I am experienced enough with zigbee2mqtt to get it fully supported myself, its a lot more complex than what I was used to with ZHA. I will probably poke around with it all, but again I am very new to this with zigbee2mqtt. Im still learning and honestly can't be sure if I even put the database entry in right, or if it was enough, or too much.. I figured I could at least submit this to make someone aware. The ae260 looks very similar and is supported, but at the same time I Cant be sure how similar. For now here is this and if I do figure out how to get this done right I night be back buuuut at the same time im so confused at times with zigbee2mqtt I dont know if I even have the time to fix what I break trying to do it :D we will see lol

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['AE 262'],
    model: 'AE 262',
    vendor: 'innr',
    description: 'Automatically generated definition',
    extend: [identify(), light()],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `AE-262.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
