### ISSUE TITLE
Zemismart TB26-3 incorrectly detected as TB26-1

### ISSUE THREAD

**Issue by jsamr** [Koenkk/zigbee2mqtt#23336]
### What happened?

I switched to Z2M edge version hoping to have my new TB26-3 setup and working. Initially, I thought it was working. After some testing, I realized the wrong model had been identified, and TB26-3 didn't work as expected, see section below.

## The device should work (2-ways sync)

- Physical presses on the devices should be reflected in Z2M
- Z2M switch presses should be reflected in the physical device

## The device model should be correctly detected

[Zemismart TB26-3](https://www.zemismart.com/products/tb26-3)

<img width="701" alt="image" src="https://github.com/user-attachments/assets/49535d01-1534-4f8d-8f52-fcb5847455e9">

### How to reproduce it (minimal and precise)

Pressing the switches from the "Exposes" tab _did_ work. I pressed the 3 UI switches and the 3 lights were switched on physically.
<img width="369" alt="image" src="https://github.com/user-attachments/assets/6fd8d795-809f-4867-b282-b4f6ce55e2b9">

Switching OFF these UI switches was also reflected physically.

After which I pressed the device physical button to turn light ON, it was NOT reflected in the UI
<img width="386" alt="image" src="https://github.com/user-attachments/assets/45d8a10b-57af-4876-9378-39cc38127672">

This is not always reproducible. At times, the state resulting from pressing physically on the device is reflected in the UI.

### Zigbee2MQTT version

1.39.0-dev commit: e3fa0bf

### Adapter firmware version

20210708

### Adapter

Sonoff ZBDongle Plus

### Setup

Add-on, HAOS Proxmox VM x86

### Debug log

*I did enable debug level logging, but couldn't find the `data/log` folder in HAOS. Checked in the docker container and couldn't find anything in `/data/log`*.

**Comment by jsamr** [comment]
Quick update: it seems my reporting missed one big feature I hadn't enabled: 
<img width="593" alt="image" src="https://github.com/user-attachments/assets/d81fb621-775c-4443-a82d-07ee084532a9">

After enabling this feature, the state is properly reported after pressing physical buttons. The mismatched model name doesn't seem so far to be an issue. Will test for a few days and confirm in this post.

**Comment by Koenkk** [comment]
It seems the wrong model name was used (just a cosmetic thing), updated it.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by jsamr** [comment]
@Koenkk Confirming it works perfectly fine, thanks!
