### ISSUE TITLE
Missing pairing instructions for the tuya zp01 motion sensor

### ISSUE THREAD

**Issue by Sniphs98** [Koenkk/zigbee2mqtt#23332]
### Link

https://www.zigbee2mqtt.io/devices/ZP01.html

### Model

zp01

### Description

Instructions how to pair the device

### Vendor

tuya 

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/ZP01.png

### Database entry

-

### Notes

Hello, this is my first issue. I hope I'm in the right place.
On the [www.zigbee2mqtt.io/devices](https://www.zigbee2mqtt.io/devices/ZP01.html) page, the description of how to connect the device is missing.
I think this could be quite useful because connecting the device is not straightforward, as it doesn't have a pairing button.
Unfortunately, I haven't figured out how to pair it yet, otherwise, I would include that information here.

**Comment by Edzilla2000** [comment]
I found the way to pair it: it has to be really close to the coordinator or a router, and you need to push for about 10 seconds with a needle in the hole at the top of the sensor.
