### ISSUE TITLE
Improved images of existing Zigbee devices for your repo/master

### ISSUE THREAD

**Issue by mackonsti** [Koenkk/zigbee2mqtt#23334]
### Is your feature request related to a problem? Please describe

I'd like to contribute with a bunch of cleaner images for existing devices in your database, that I own (and saw on front-end of Zigbee2MQTT) that I processed myself on Photoshop for their transparency.

1 x Temperature & Humidity sensor (no display)
1 x Alternative Temperature & Humidity sensor (no display)
1 x Temperature & Humidity sensor with display
2 x Motion Sensors (round) in different angles

### Describe the solution you'd like

Please check and accept my small contribution in the below PNG graphical elements.

### Describe alternatives you've considered

Keep using existing images but lower resolution and background not removed well.

### Additional context

These are 3+1 images here of devices that one can find on Asian sellers, I did my best to render them transparent, at least they are higher quality than existing ones. I hope you will approve them. I am not too familiar with git procedures (clone etc.) and there was no mention anywhere how to contribute with images only @Koenkk ! So apologies to use this type of submission, here. Let me know where I can keep contributing.

P.S. The existing door/window sensor PNG is in good quality so I am not submitting a replacement image.

![MOES Temperature Sensor](https://github.com/user-attachments/assets/16e07d3b-df1f-45c0-9296-6eda22ce3ebf)

![Motion Sensor A](https://github.com/user-attachments/assets/658dd8fe-5662-405f-bf18-23bfef72ad67)

![Motion Sensor B](https://github.com/user-attachments/assets/b77298aa-6c12-43ae-aa5d-9c3488a930b7)

![Simple Temperature Sensor](https://github.com/user-attachments/assets/da0fb666-e1b5-4bf2-ad65-5facab3f8963)

![Temperature Sensor With Display](https://github.com/user-attachments/assets/1c939b34-b94b-422e-99ce-6e6ae0706b60)

**Comment by Koenkk** [comment]
Thanks for your contribution, the following instructions can be used to update images:

-----------------

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `MODEL.png` (update `model` accordingly) 
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by mackonsti** [comment]
Thanks @Koenkk for this, I will try doing so this morning!
And thank you in general for this nice work 👍

**Comment by mackonsti** [comment]
@Koenkk if images are not so big such as 512x512 would you still accept transparent ones but smaller? (and square) e.g. 400x400 etc.? Thanks.

P.S. There are thousands of image files 😬 I wanted to link the generic files but seems I need to do more digging 😆

**Comment by Koenkk** [comment]
Images should either be 512x512 or 150x150
