### ISSUE TITLE
after updating to 1.39.0 zigbee_herdsman_converters_version still shows 19.62.0 and zigbee_herdsman_version 0.50.1

### ISSUE THREAD

**Issue by Ev15** [Koenkk/zigbee2mqtt#23340]
### What happened?

Hi, after updating to 1.39.0 zigbee_herdsman_converters_version still shows 19.62.0 and zigbee_herdsman_version 0.50.1.

![afbeelding](https://github.com/user-attachments/assets/27a77ea6-0ff6-443e-a6c5-cdee5bf7e899)

### What did you expect to happen?

Updating the herdsman_converters_version and zigbee_herdsman_version to respectively 19.68.0 and 0.53.1

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

20220219

### Adapter

Sonoff ZBDongle

### Setup

Pi

**Comment by Koenkk** [comment]
Those are the [correct versions](https://github.com/Koenkk/zigbee2mqtt/blob/032692673b533a10c9e0cb6af9af4681deee6b05/package.json#L64), if you want to use the latest switch to the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
