### ISSUE TITLE
[New device support]: Simon Smart Switches (Wall Light Switch, Curtain Switch, Scene Switch)

### ISSUE THREAD

**Issue by clerith21x** [Koenkk/zigbee2mqtt#23354]
### Link

https://www.simon-apac.com/contents/switches-sockets/simon-i7-smart.html

### Database entry

"Router",  "0xb0c7defffecbb3c2"

### Comments

Hi! I was hoping if I can get help in adding these new devices as I am pretty new at this and I am not sure how I can proceed. I have taken a look at the "Adding New Device" doc but was immediately overwhelmed. From what I've found out, these devices can be added in ZHA but I am willing to learn and try to add these to Z2M. 

The below are screenshots from Z2M. Do note this current device is a 4-Gang Wired Smart Switch and the manufacturer uses Tuya app to add these devices

1) ![image](https://github.com/user-attachments/assets/2690972c-a03e-4f42-bca5-77868843c6a9)
2) No exposes definitions
3) 
![image](https://github.com/user-attachments/assets/68097860-c217-4d62-b85d-6c93ca14a50d)
![image](https://github.com/user-attachments/assets/c320ef5d-6a81-4751-8f9b-176a2647753f)
![image](https://github.com/user-attachments/assets/4a37b53e-18c5-4df2-9196-16e4fa35e9a1)
(There are 5 endpoints under 'Clusters' with endpoint 1-4 being similar)
4) ![image](https://github.com/user-attachments/assets/756bdf75-7c65-46ed-801b-3cd1da46e1de)
![image](https://github.com/user-attachments/assets/66bb50db-0852-4ba6-a651-066176611c9c)

Any help is much appreciated. Feel free to request more info if needed. Many many thanks in advance!!!!

### External definition

```shell
I can't seem to create an external definition. The above are screenshots of the page in 'Dev Console'

```

**Comment by mrmaximas** [comment]
What about show db entry(s) for this device(s)??
