### ISSUE TITLE
_TZE200_dwcarsat:  The VOC value unit is incorrectly being displayed in ppm instead of the original ppb.

### ISSUE THREAD

**Issue by amosnet** [Koenkk/zigbee2mqtt#23362]
### What happened?

The VOC value unit is incorrectly being displayed in ppm instead of the original ppb.

### What did you expect to happen?

Correct the unit from ppm back to ppb, or divide the value by 1000 while keeping the unit ppm.

### How to reproduce it (minimal and precise)

_TZE200_dwcarsat and read the VOC value.

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

20240316

### Adapter

UZG-01

### Setup

Proxmox x86-64, Home Assistant OS VM, Z2M add-on in HA.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
