### ISSUE TITLE
[New device support]: Raex TQL25-2211 Tubular Motor

### ISSUE THREAD

**Issue by JKolanko** [Koenkk/zigbee2mqtt#23360]
### Link

https://www.amazon.com/dp/B0CL6KY5D9

### Database entry

{"id":17,"type":"EndDevice","ieeeAddr":"0x90ab96fffe77d53c","nwkAddr":37489,"manufId":4742,"manufName":"Raex","powerSource":"Battery","modelId":"TQL25-2211","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[0,1,3,6,258,64599,61184],"outClusterList":[3,6,25],"clusters":{"closuresWindowCovering":{"attributes":{"windowCoveringMode":1,"currentPositionLiftPercentage":100}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":192,"batteryVoltage":0}},"genBasic":{"attributes":{"modelId":"TQL25-2211","manufacturerName":"Raex","powerSource":3,"zclVersion":3,"appVersion":2,"hwVersion":0,"dateCode":"20230627","swBuildId":"1.0.4"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c28e39","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c28e39","endpointID":1},{"cluster":258,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c28e39","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10,"manufacturerCode":null},{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null},{"cluster":258,"attrId":8,"minRepIntval":1,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null}],"meta":{}}},"appVersion":2,"hwVersion":0,"dateCode":"20230627","swBuildId":"1.0.4","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1721250766913}

### Comments

I have the below external definition running mostly fine in home assistant. The issue I run into is when I try to raise or lower the blinds without setting a percentage. I get the following error in the logs which I do not know how to resolve:

```
2024-07-17 17:08:43z2m: Publish 'set' 'state' to 'Kitchen Blinds' failed: 'Error: 'open' not allowed, choose between: toggle,off,on'
2024-07-17 17:08:43z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Kitchen Blinds' failed: 'Error: 'open' not allowed, choose between: toggle,off,on'","meta":{"friendly_name":"Kitchen Blinds"},"type":"zigbee_publish_error"}'
```

Clicking the Off/On next to state opens & closes the blinds as expected. But clicking Open/Close/Stop throws an error.

<img width="1443" alt="Screenshot 2024-07-17 at 5 15 14 PM" src="https://github.com/user-attachments/assets/6eb566d2-463a-4c64-a725-ec63f861005d">

Thanks in advance for any help!

### External definition

```shell
const {battery, identify, onOff, windowCovering, commandsOnOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TQL25-2211'],
    model: 'TQL25-2211',
    vendor: 'Raex',
    description: 'Tubular motor',
    extend: [battery(), identify(), onOff({"powerOnBehavior":false}), windowCovering({"controls":["lift"]}), commandsOnOff()],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Can you try to remove `onOff({"powerOnBehavior":false})` and see if that fixes your issue?

**Comment by JKolanko** [comment]
Thank you! That did it! The shades are reacting as expected now. Do I need to open a PR to have this merged in?

```
const {battery, identify, windowCovering, commandsOnOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TQL25-2211'],
    model: 'TQL25-2211',
    vendor: 'Raex',
    description: 'Tubular motor',
    extend: [battery(), identify(), windowCovering({"controls":["lift"]}), commandsOnOff({commands: ['on', 'off', 'toggle']})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Yes please!
