### ISSUE TITLE
Error: Cluster with name '64529' does not exist" for SONOFF smart water valve SWV

### ISSUE THREAD

**Issue by jocamane** [Koenkk/zigbee2mqtt#23376]
### What happened?

After pair SONOFF SWV (https://www.zigbee2mqtt.io/devices/SWV.html#sonoff-swv) the power is not active and in cluster tab appeared 64529

After reconfigure (buttom) the following errors appear in the log: Error: Cluster with name '64529' does not exist"

tested with device version Firmware build date: 20240705 / Firmware version: 1.0.3

![image](https://github.com/user-attachments/assets/f0225199-5b8e-4a93-a578-39c399201c31)

![image](https://github.com/user-attachments/assets/09440f25-6498-4f49-b67c-72e2bca59119)

### What did you expect to happen?

The power field is populate and no exists errors in reconfigure

### How to reproduce it (minimal and precise)

Pair the device. after pair press reconfigure buttom

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

### Setup

Add-on on RPI 4b

### Debug log

LOG PAIR:

Info 2024-07-19 13:22:35MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"last_seen":"2024-07-19T13:22:35+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1}}'
Info 2024-07-19 13:22:35Interview for '0x0ceff6fffe17e71c' started
Info 2024-07-19 13:22:35Device '0x0ceff6fffe17e71c' joined
Info 2024-07-19 13:22:35MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0ceff6fffe17e71c","ieee_address":"0x0ceff6fffe17e71c"},"type":"device_joined"}'
Info 2024-07-19 13:22:35MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x0ceff6fffe17e71c"},"type":"device_connected"}'
Info 2024-07-19 13:22:35Starting interview of '0x0ceff6fffe17e71c'
Info 2024-07-19 13:22:36MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0ceff6fffe17e71c","ieee_address":"0x0ceff6fffe17e71c","status":"started"},"type":"device_interview"}'
Info 2024-07-19 13:22:36MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0ceff6fffe17e71c"},"type":"pairing"}'
Info 2024-07-19 13:22:37MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"last_seen":"2024-07-19T13:22:37+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1}}'
Info 2024-07-19 13:22:38MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"last_seen":"2024-07-19T13:22:38+01:00","linkquality":255,"update":{"installed_version":-1,"latest_version":-1}}'
Info 2024-07-19 13:22:38Succesfully interviewed '0x0ceff6fffe17e71c'
Info 2024-07-19 13:22:38Successfully interviewed '0x0ceff6fffe17e71c', device has successfully been paired
Info 2024-07-19 13:22:38Device '0x0ceff6fffe17e71c' is supported, identified as: SONOFF Zigbee smart water valve (SWV)
Info 2024-07-19 13:22:38MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee smart water valve","exposes":[{"access":1,"description":"Current water flow","label":"Flow","name":"flow","property":"flow","type":"numeric","unit":"m³/h"},{"access":5,"category":"diagnostic","description":"Remaining battery in %","label":"Battery","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":5,"description":"The water valve is in normal state, water shortage or water leakage","label":"Current device status","name":"current_device_status","property":"current_device_status","type":"enum","values":["normal_state","water_shortage","water_leakage","water_shortage & water_leakage"]},{"features":[{"access":7,"description":"On/off state of the switch","label":"State","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":7,"description":"Smart water valve cycle timing irrigation","features":[{"access":1,"description":"Number of times it has been executed","label":"Current count","name":"current_count","property":"current_count","type":"numeric","unit":"times"},{"access":3,"description":"Total times of circulating irrigation","label":"Total number","name":"total_number","property":"total_number","type":"numeric","unit":"times","value_max":100,"value_min":0},{"access":3,"description":"Single irrigation duration","label":"Irrigation duration","name":"irrigation_duration","property":"irrigation_duration","type":"numeric","unit":"seconds","value_max":86400,"value_min":0},{"access":3,"description":"Time interval between two adjacent irrigation","label":"Irrigation interval","name":"irrigation_interval","property":"irrigation_interval","type":"numeric","unit":"seconds","value_max":86400,"value_min":0}],"label":"Cyclic timed irrigation","name":"cyclic_timed_irrigation","property":"cyclic_timed_irrigation","type":"composite"},{"access":7,"description":"Smart water valve circulating quantitative irrigation","features":[{"access":1,"description":"Number of times it has been executed","label":"Current count","name":"current_count","property":"current_count","type":"numeric","unit":"times"},{"access":3,"description":"Total times of circulating irrigation","label":"Total number","name":"total_number","property":"total_number","type":"numeric","unit":"times","value_max":100,"value_min":0},{"access":3,"description":"Single irrigation capacity","label":"Irrigation capacity","name":"irrigation_capacity","property":"irrigation_capacity","type":"numeric","unit":"liter","value_max":6500,"value_min":0},{"access":3,"description":"Time interval between two adjacent irrigation","label":"Irrigation interval","name":"irrigation_interval","property":"irrigation_interval","type":"numeric","unit":"seconds","value_max":86400,"value_min":0}],"label":"Cyclic quantitative irrigation","name":"cyclic_quantitative_irrigation","property":"cyclic_quantitative_irrigation","type":"composite"},{"access":1,"category":"diagnostic","description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"SWV","options":[{"access":2,"description":"State actions will also be published as 'action' when true (default false).","label":"State action","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true}],"supports_ota":true,"vendor":"SONOFF"},"friendly_name":"0x0ceff6fffe17e71c","ieee_address":"0x0ceff6fffe17e71c","status":"successful","supported":true},"type":"device_interview"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Zigbee smart water valve","friendly_name":"0x0ceff6fffe17e71c","model":"SWV","supported":true,"vendor":"SONOFF"},"type":"pairing"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/flow/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Flow","object_id":"0x0ceff6fffe17e71c_flow","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_flow_zigbee2mqtt","unit_of_measurement":"m³/h","value_template":"{{ value_json.flow }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","object_id":"0x0ceff6fffe17e71c_battery","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/current_device_status/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Current device status","object_id":"0x0ceff6fffe17e71c_current_device_status","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_current_device_status_zigbee2mqtt","value_template":"{{ value_json.current_device_status }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/switch/0x0ceff6fffe17e71c/switch/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0x0ceff6fffe17e71c/set","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":null,"object_id":"0x0ceff6fffe17e71c","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/cyclic_timed_irrigation/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Cyclic timed irrigation","object_id":"0x0ceff6fffe17e71c_cyclic_timed_irrigation","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_cyclic_timed_irrigation_zigbee2mqtt","value_template":"{{ value_json.cyclic_timed_irrigation }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/cyclic_quantitative_irrigation/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":true,"json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Cyclic quantitative irrigation","object_id":"0x0ceff6fffe17e71c_cyclic_quantitative_irrigation","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_cyclic_quantitative_irrigation_zigbee2mqtt","value_template":"{{ value_json.cyclic_quantitative_irrigation }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Linkquality","object_id":"0x0ceff6fffe17e71c_linkquality","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/last_seen/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"device_class":"timestamp","enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:clock","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Last seen","object_id":"0x0ceff6fffe17e71c_last_seen","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_last_seen_zigbee2mqtt","value_template":"{{ value_json.last_seen }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/sensor/0x0ceff6fffe17e71c/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:update","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":"Update state","object_id":"0x0ceff6fffe17e71c_update_state","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/binary_sensor/0x0ceff6fffe17e71c/update_available/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"device_class":"update","enabled_by_default":false,"entity_category":"diagnostic","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":null,"object_id":"0x0ceff6fffe17e71c_update_available","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_update_available_zigbee2mqtt","value_template":"{{ value_json['update']['state'] == \"available\" }}"}'
Info 2024-07-19 13:22:38MQTT publish: topic 'homeassistant/update/0x0ceff6fffe17e71c/update/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/0x0ceff6fffe17e71c/availability"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/device/ota_update/update","device":{"identifiers":["zigbee2mqtt_0x0ceff6fffe17e71c"],"manufacturer":"SONOFF","model":"Zigbee smart water valve (SWV)","name":"0x0ceff6fffe17e71c","sw_version":"1.0.3","via_device":"zigbee2mqtt_bridge_0x00212effff07afaa"},"device_class":"firmware","entity_category":"config","entity_picture":"https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png","json_attributes_template":"{\"in_progress\": {{ iif(value_json['update']['state'] == 'updating', 'true', 'false') }} }","json_attributes_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","latest_version_template":"{{ value_json['update']['latest_version'] }}","latest_version_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","name":null,"object_id":"0x0ceff6fffe17e71c","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"payload_install":"{\"id\": \"0x0ceff6fffe17e71c\"}","state_topic":"zigbee2mqtt/0x0ceff6fffe17e71c","unique_id":"0x0ceff6fffe17e71c_update_zigbee2mqtt","value_template":"{{ value_json['update']['installed_version'] }}"}'
Info 2024-07-19 13:22:39MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":null,"cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:22:39+01:00","linkquality":255,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:08MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":null,"cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:08+01:00","linkquality":220,"state":null,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:08MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":null,"cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:08+01:00","linkquality":220,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:08MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":null,"cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:08+01:00","linkquality":255,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:11MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":null,"cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:11+01:00","linkquality":255,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:13MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:13+01:00","linkquality":255,"state":"ON","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:13MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:13+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:30MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:30+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:33MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:33+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:36MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:36+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:39MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:39+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-07-19 13:23:42MQTT publish: topic 'zigbee2mqtt/0x0ceff6fffe17e71c', payload '{"battery":null,"current_device_status":"normal_state","cyclic_quantitative_irrigation":null,"cyclic_timed_irrigation":null,"flow":null,"last_seen":"2024-07-19T13:23:42+01:00","linkquality":255,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'

LOG RECONFIGURE:

Info 2024-07-19 13:30:07Configuring 'Sistema Rega Fora'
Error 2024-07-19 13:30:10Failed to configure 'Sistema Rega Fora', attempt 6 (Error: Cluster with name '64529' does not exist at getClusterDefinition (/app/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:107:19) at Object.getCluster (/app/node_modules/zigbee-herdsman/src/zspec/zcl/utils.ts:237:29) at Function.create (/app/node_modules/zigbee-herdsman/src/zspec/zcl/zclFrame.ts:45:31) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:33) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:402:40) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/sonoff.ts:1046:28) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:173:21) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
Info 2024-07-19 13:30:10MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Sistema Rega Fora"},"error":"Failed to configure (Cluster with name '64529' does not exist)","status":"error","transaction":"xmfj3-3"}'

**Comment by paulz-gh** [comment]
Hi, I had the same errors but they seem to have disappeared when I updated to 1.39.0.

**Comment by jocamane** [comment]
> Hi, I had the same errors but they seem to have disappeared when I updated to 1.39.0.

Ok, I wait more 2 weeks to update to 1.39.0 and after that I report again

**Comment by jocamane** [comment]
However, after 6 hours I already have power value

**Comment by Kuechenfenster** [comment]
@jocamane,
can you please share your zigbee2mqtt details setting for this valve!

**Comment by jocamane** [comment]
Now, after install th Z2M [1.39.0] the tab "64529" disappeared, and if I reconfigure no more errors.

SOLVED


![image](https://github.com/user-attachments/assets/583574bb-ba16-4c0c-b78b-077c13485c83)
![image](https://github.com/user-attachments/assets/a1ba74d0-1a10-42a3-a061-b62e4a3e0b2e)
![image](https://github.com/user-attachments/assets/5dded6c3-3fad-46bc-b90d-b4c3630f8262)
![image](https://github.com/user-attachments/assets/33901c59-853e-40be-b936-a2e49ecac64f)
![image](https://github.com/user-attachments/assets/90f7c2bc-e2ac-4f98-a9b4-e51b5f547493)
![image](https://github.com/user-attachments/assets/ac0f97ba-334f-4a2c-9cb9-5635e59fb990)
![image](https://github.com/user-attachments/assets/596708db-9da4-4460-93d8-173a7c4ba251)

**Comment by quensen** [comment]
Hi @jocamane 

I am wondering if you needed to create an external converter for your SWV device? I do, but I never needed to create one before. Could you share yours, please?

Sorry for off-topicness.

Stefano

**Comment by isaga1234** [comment]
I'm having the same issue: using version [1.40.1] commit: [403d3c0]. I'll wait for the next release, maybe it gets fixed with an update
