### ISSUE TITLE
Z2M on Proxmox is using 100% of swap while memory remains free

### ISSUE THREAD

**Issue by nicola-spreafico** [Koenkk/zigbee2mqtt#23443]
### What happened?

I have Z2M installed as LXC on Proxmox 8.2.4, this morning I found the entire Zigbee network stuck (data were no longer being received), and after some analysis I found out that the SWAP Usage was at 100%

You can see here that a this hour the data stopped and no updates were available anymore, since I did a complete restart
![image](https://github.com/user-attachments/assets/0a7a36e6-da80-4157-833b-61c8f728cab9)

Right now it is not at 100% because first thing I did a reboot, but you can see even here that even if there is almost the entirely of the memory free, it is going on Swap
![image](https://github.com/user-attachments/assets/95c9e944-d248-4511-afd1-c4d60e2d925c)

Using 100% of Swap it should not be a problem per se (even if strange, there is free memory...) but it comes with a blocking problem of the software getting stuck and not working anymore.

Does anyone knows what can be the underlying issue of this? This container is working fine since several months and it is the firsrt time I encounter this kind of behaviour.  I found only a guide to reduce/disable the swapiness of linux, but I'm not sure it is the proper action considering it should be working by itself, like it did since today.

I now restored a backup from yesterday, before the "unknown event" of this knight that stopped the data being sent, but I feel the swap usage is raising again and I'm afraid in a bit of time I will reach again the 100%.

### Zigbee2MQTT version

 1.39.0 commit: 03269267

### Adapter firmware version

 7.4.1.0 build 0

### Adapter

SLZB-06M

### Setup

Z2M on Proxmox LXC

**Comment by jonnycastaway** [comment]
Give the LXC enough RAM and set Swap to 0 in Proxmox.
All my Containers running smoothing this setting.

My Z2M LXC config:
2 CPUs (Host has Core i5 Gen.10)
2048 RAM
no Swap
