### ISSUE TITLE
Sengled Z01-A19NAE26 exposes invalid capabilities (color_xy)

### ISSUE THREAD

**Issue by ljtilley** [Koenkk/zigbee2mqtt#23462]
### What happened?

I have several sengled bulbs and the device definition [here](https://www.zigbee2mqtt.io/devices/Z01-A19NAE26.html#sengled-z01-a19nae26) shows that this bulb has color_xy capabilities but it does not, it only can do color_temp.

When you try to get the color of the lamp you get the following error:

`z2m: Publish 'get' 'color' to 'Living Room Lamp' failed: 'Error: ZCL command 0xb0ce1814030309dc/1 lightingColorCtrl.read(["colorMode","currentX","currentY","enhancedCurrentHue","currentSaturation","colorTemperature"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

### What did you expect to happen?

I expected that the device definition would align with the capabilities of the bulb

### How to reproduce it (minimal and precise)

add a sengled Z01-A19NAE26 to z2m and see how it exposes color_xy based on the device defition

### Zigbee2MQTT version

1.39.0-1

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

addon on HassOS running as a VM on proxmox

**Comment by Koenkk** [comment]
Removed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
