### ISSUE TITLE
eWeLink SNZB-01P displayed the unsupported device.

### ISSUE THREAD

**Issue by Camblin** [Koenkk/zigbee2mqtt#23468]
### Link

https://zigbee.blakadder.com/Sonoff_SNZB-01P.html

### Model

SNZB-01P

### Description

wireless button

### Vendor

eWeLink

### Picture (link)

https://zigbee.blakadder.com/assets/images/devices/Sonoff_SNZB-01P.webp

### Database entry

{"id":6,"type":"EndDevice","ieeeAddr":"0x842712fffe3202a9","nwkAddr":29960,"manufId":4742,"manufName":"eWeLink","powerSource":"Unknown","modelId":"SNZB-01P","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,3,32,64599],"outClusterList":[3,6,25],"clusters":{"genBasic":{"attributes":{"modelId":"SNZB-01P","manufacturerName":"eWeLink","powerSource":0,"zclVersion":8,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"20230908","swBuildId":"2.2.0"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"20230908","swBuildId":"2.2.0","zclVersion":8,"interviewCompleted":true,"meta":{},"lastSeen":1722514869095}

**Comment by Koenkk** [comment]
`SNZB-01P` is supported in z2m 1.39.1
