### ISSUE TITLE
[New device support]: Alarm _TZE204_hcxvyxa5

### ISSUE THREAD

**Issue by duntik** [Koenkk/zigbee2mqtt#23463]
### Link

https://www.aliexpress.com/item/1005007170210038.html?spm=a2g0o.productlist.main.5.1251gaMhgaMhdl&algo_pvid=134d6321-a02a-4dfb-b2e8-382b17a8aac7&algo_exp_id=134d6321-a02a-4dfb-b2e8-382b17a8aac7-2&pdp_npi=4%40dis%21GBP%2127.84%215.02%21%21%21251.06%2145.28%21%4021039e0c17224683534215146e7531%2112000039685494402%21sea%21UK%210%21ABX&curPageLogUid=QIICS0PVyzUZ&utparam-url=scene%3Asearch%7Cquery_from%3A

### Database entry

{"id":14,"type":"Router","ieeeAddr":"0xa4c1382af139b44f","nwkAddr":7277,"manufId":4417,"manufName":"_TZE204_hcxvyxa5","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"U�;.\u0012_�;.f`�;.\u0012`�;.e��;.\u0012\u0006\u0000\u0000\u0000\u0012\u0010\u0000\u0000\u0000fs�;.\u0012","65506":56,"65508":0,"stackVersion":0,"dateCode":"","appVersion":74}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1722464891642}

### Comments

Hello, I'm newbie to this, tried to follow add new device support page, but got stuck how to get a data points. Sorry about that, hope there will be a video lesson on how to do this in details. 

Found this topics: 
https://github.com/home-assistant/core/issues/120374
https://github.com/zigpy/zha-device-handlers/issues/3255

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_hcxvyxa5',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by LaSScaR** [comment]
I am waiting for adding  _TZE204_hcxvyxa5 to ZigBee2Mqtt too.
![Screenshot_2024-08-18-20-38-18-81_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/fe43ef9d-4b63-4d63-89e0-32c31954b8e3)

Thanks.
