### ISSUE TITLE
Tuya ZG-205Z presence sensor - no luminance entity

### ISSUE THREAD

**Issue by Ramotny** [Koenkk/zigbee2mqtt#23478]
![Brak_luminancji](https://github.com/user-attachments/assets/cbbbcfa9-0216-4c91-ab7a-91819e9042b1)
### What happened?

In "exposed" list there is a "luminance" (numeric) but there is no access (entity) to it. Worked fine in native ZHA/Zigbee enviroinment.

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

0122052017

### Adapter

Sonoff Dongle Plus P

### Setup

Lenovo MiniPC

**Comment by Mikl-h** [comment]
You have to enable Illuminance entity in device settings:
![obrazek](https://github.com/user-attachments/assets/d8187391-a6e3-426f-8a3f-b426492776e0)

**Comment by uniquePWD** [comment]
Illuminance broke with the latest update for me too. It's stuck at 29lx

Zigbee Model: TS0225
Device Model: [ZG-205Z/A](https://www.zigbee2mqtt.io/devices/ZG-205Z_A.html#tuya-zg-205z%252Fa)

**Comment by VoltX** [comment]
> Illuminance broke with the latest update for me too. It's stuck at 29lx
> 
> Zigbee Model: TS0225 Device Model: [ZG-205Z/A](https://www.zigbee2mqtt.io/devices/ZG-205Z_A.html#tuya-zg-205z%252Fa)

Same problem for me, on HA you can setup specific parameters and fix multiplier
![image](https://github.com/user-attachments/assets/ff9d963f-5a47-4b95-b608-e897756535e2)

**Comment by uniquePWD** [comment]
> > Illuminance broke with the latest update for me too. It's stuck at 29lx
> > Zigbee Model: TS0225 Device Model: [ZG-205Z/A](https://www.zigbee2mqtt.io/devices/ZG-205Z_A.html#tuya-zg-205z%252Fa)
> 
> Same problem for me, on HA you can setup specific parameters and fix multiplier ![image](https://private-user-images.githubusercontent.com/3590072/354586242-ff9d963f-5a47-4b95-b608-e897756535e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDA5NTMsIm5iZiI6MTcyMjYwMDY1MywicGF0aCI6Ii8zNTkwMDcyLzM1NDU4NjI0Mi1mZjlkOTYzZi01YTQ3LTRiOTUtYjYwOC1lODk3NzU2NTM1ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTIxMDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM4YmZmYTFhZTFjN2I2YjQ4Y2U2Y2FmMTdjOTBmNGIxNWVhYTNkMjhkNzViYzc5NzViY2UzODBmMDhlNTE5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.msIbEPKRXDSVVzQFOkTr3YPGwoQtVHYgHQHA72U3Dxc)

Thanks, the 10000 multiplier fixed it. It doesn't seem as responsive now, but I'll test for a bit and find out for sure.
