### ISSUE TITLE
The switch TS0001 (_TZ3000_ikuxinvo) does not display consumption data, as well as voltage and other

### ISSUE THREAD

**Issue by SMiK1** [Koenkk/zigbee2mqtt#23471]
### What happened?

I purchased this relay unit via Aliexpress, but when connected to the z2m, it was identified only as a switch, but it does not output data (current and voltage)

### What did you expect to happen?

Relay with full output of indicators

### How to reproduce it (minimal and precise)

I don't know

### Zigbee2MQTT version

 1.39.0-dev commit: 7cc5209

### Adapter firmware version

6.10.3.0 build 297

### Adapter

 EZSP v8 

### Setup

Depo PC Stick

### Debug log

![image](https://github.com/user-attachments/assets/3fce24e7-c13b-4b21-ad42-81a0f324c3ff)
![image](https://github.com/user-attachments/assets/7a4ebe69-48d8-43e1-96a4-b0cf3c03efae)
![image](https://github.com/user-attachments/assets/864ee9f3-eaa6-473b-a31a-d796e840ce2e)

[2024-08-01 20:01:47] debug: 	z2m: Received Zigbee message from '0xa4c1381b784b283c', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"rmsCurrent":63}' from endpoint 1 with groupID 0
[2024-08-01 20:01:47] debug: 	z2m: No converter available for 'TS0001' with cluster 'haElectricalMeasurement' and type 'attributeReport' and data '{"rmsCurrent":63}'

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by SMiK1** [comment]
THANKS)
