### ISSUE TITLE
BLE-YL01 Orp is negative

### ISSUE THREAD

**Issue by NinjaTurtle85** [Koenkk/zigbee2mqtt#23488]
### What happened?

The Orp value is always negative

This means that the free chlorine value is not calculated.

Zigbee2MQTT-Version
    [1.39.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.39.0) commit: [03269267](https://github.com/Koenkk/zigbee2mqtt/commit/03269267)

Coordinator-Typ
    EmberZNet

Coordinator-Version
    7.4.1 [GA]

Coordinator IEEE Adresse
    0x804b50fffea7ed20

Frontend-Version
    0.7.2

Zigbee Herdsman Konverter Version
    19.62.0

Zigbee Herdsman Version
    0.50.1

### Zigbee2MQTT version

1.19.0

### Adapter firmware version

20240510

### Adapter

EmberZNet

### Setup

easy on a intelNUC

**Comment by backyardaussie** [comment]
its a pity that problem errors like this are left to sit stale and not be addressed. I recently purchased one of these and have the same problems and errors.
Setting the correct values in the `Exposes` resets on HA reboot
very annoying
