### ISSUE TITLE
Symfonisk remote generates too many events. 

### ISSUE THREAD

**Issue by freakshock88** [Koenkk/zigbee2mqtt#2349]
# Bug Report
## What happened
I bought a symfonisk remote and paired it to zigbee2mqtt without problems.
However, it is generating 2 'events' per action. For instance when I press the button: 

```
zigbee2mqtt:info  2019-11-16T13:56:42: MQTT publish: topic 'zigbee2mqtt/0xccccccfffebd8924', payload '{"linkquality":13,"rate":195,"brightness":14,"battery":87,"action":"play_pause"}'
zigbee2mqtt:info  2019-11-16T13:56:42: MQTT publish: topic 'zigbee2mqtt/0xccccccfffebd8924', payload '{"linkquality":13,"rate":195,"brightness":14,"battery":87,"action":""}'
zigbee2mqtt:info  2019-11-16T13:56:42: MQTT publish: topic 'zigbee2mqtt/0xccccccfffebd8924', payload '{"linkquality":15,"rate":195,"brightness":14,"battery":87,"action":"play_pause"}'
zigbee2mqtt:info  2019-11-16T13:56:42: MQTT publish: topic 'zigbee2mqtt/0xccccccfffebd8924', payload '{"linkquality":15,"rate":195,"brightness":14,"battery":87,"action":""}'
```
This causes double triggers on automations, of course. 

Especially then I turn the volume up (just slightly in one smooth go), a lot of events get generated:
https://pastebin.com/H6vg5TWQ
Especially turning the volume button locks up my HA instance for a while, and writes a lot to the recorder DB (I excluded it now). 

## What did you expect to happen
I expect button presses to only register once. 

## How to reproduce it (minimal and precise)
Pair symfonisk to zigbee2mqtt and press button once, for volume problem turn button once.

## Debug Info
zigbee2mqtt version: 1.7.0 (commit #551a58a)
CC253X firmware version: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'

**Comment by james-fry** [comment]
Same root cause as issue https://github.com/Koenkk/zigbee2mqtt/issues/2337
Looks like there needs to be some way to throttle the MQTT messages to <n> per second.

**Comment by freakshock88** [comment]
You are right, I solved the problem by adding the option to my device config:
`debounce: 1`
Thanks!

**Comment by tobimori** [comment]
> 
> 
> You are right, I solved the problem by adding the option to my device config:
> `debounce: 1`
> Thanks!

Didn't make it for me. I only get 'rotate_stop' or the click events.

**Comment by freakshock88** [comment]
That's the case also for me, but I just respond to rotate stop commands, and not rotate commands.

**Comment by tobimori** [comment]
@freakshock88 How do you determine the rotation direction? Could you send me your script?

**Comment by freakshock88** [comment]
> @freakshock88 How do you determine the rotation direction? Could you send me your script?

Here's what I have so far, it also supports multiple media players and runs actions on the currently active one:
https://pastebin.com/Y1SG3Tft

**Comment by tobimori** [comment]
> 
> 
> > @freakshock88 How do you determine the rotation direction? Could you send me your script?
> 
> Here's what I have so far, it also supports multiple media players and runs actions on the currently active one:
> https://pastebin.com/Y1SG3Tft

This works really well. Thanks!
