### ISSUE TITLE
[Wrong device]: EGLO 98843

### ISSUE THREAD

**Issue by josask** [Koenkk/zigbee2mqtt#23491]
### Link

https://www.zigbee2mqtt.io/devices/98847.html

### Model

EGLO 98843

### Description

Light

### Vendor

EGLO

### Picture (link)

https://www.eglo.sk/wp-content/uploads/2023/09/98843.jpg

### Database entry

{"id":85,"type":"Router","ieeeAddr":"0xa4c1381ec942e8cc","nwkAddr":6260,"manufId":4417,"manufName":"AwoX","powerSource":"Mains (single phase)","modelId":"TLSR82xx","epList":[1,3,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599,10],"outClusterList":[6],"clusters":{"genBasic":{"attributes":{"modelId":"TLSR82xx","manufacturerName":"AwoX","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":217}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":4751,"epId":3,"devId":268,"inClusterList":[65360,65361],"outClusterList":[65360,65361],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1722672002002}

### Notes

I have EGLO 98843 (it's looks same as EGLO 98847), but z2mqtt identifies as AWOX bulb 33957.
i tried to re-pairing several time but without success.

**Comment by Koenkk** [comment]
These devices are all Awox whitelabels (as can be seen in your database entry), there is no way to distinguish them since they all use the same modelID
