### ISSUE TITLE
[New device support]: EGLO HERRORA-Z ceiling light model 99639

### ISSUE THREAD

**Issue by huibuh420** [Koenkk/zigbee2mqtt#23498]
### Link

https://www.eglo.com/uk/ceiling-light-herrora-z-99639.html

### Database entry

{"id":8,"type":"Router","ieeeAddr":"0xa4c138e1956c6cad","nwkAddr":56868,"manufId":4417,"manufName":"AwoX","powerSource":"Mains (single phase)","modelId":"TLSR82xx","epList":[1,3,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096,64599,10],"outClusterList":[6],"clusters":{"genBasic":{"attributes":{"modelId":"TLSR82xx","manufacturerName":"AwoX","powerSource":1,"zclVersion":3,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017","appVersion":0}},"genOnOff":{"attributes":{"onOff":1}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370,"colorMode":2,"colorTemperature":153}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":4751,"epId":3,"devId":268,"inClusterList":[65360,65361],"outClusterList":[65360,65361],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1722691977133}

### Comments

I failed with the instructions to push the changes to github and to create the pull request. 
The light can change the color, aswell it is dimmable. Please include this device.
![TLSR82xx](https://github.com/user-attachments/assets/55853e43-eacc-45f3-8480-f3859596f430)

### External definition

```shell
const {deviceEndpoints, identify, light, commandsOnOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TLSR82xx'],
    model: '99639',
    vendor: 'AwoX',
    description: 'EGLO HERRORA-Z ceiling light',
    extend: [deviceEndpoints({"endpoints":{"1":1,"3":3}}), identify(), light({"colorTemp":{"range":[153,370]}}), commandsOnOff()],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Does it support both color (rgb) and color temp or only color temp?

**Comment by huibuh420** [comment]
Hi,
only white color temp

**Comment by Koenkk** [comment]
Without the external definition, how is it detected in z2m 1.39.1? (can you post a screenshot of the about tab)

**Comment by huibuh420** [comment]
![image](https://github.com/user-attachments/assets/9472e9b1-a659-4ec7-8bcf-2d26d5e82767)
![image](https://github.com/user-attachments/assets/63038711-96f5-4bd8-a86e-80bd89f09f96)

**Comment by huibuh420** [comment]
I hope that german is fine for you, otherwise I can change the language to english.

**Comment by Koenkk** [comment]
33957 supports the color temp, so I guess this is only a cosmetic issue? (wrong picture/description which cannot be fixed since all these devices use the same model id)
