### ISSUE TITLE
Update to 3.9 Problem

### ISSUE THREAD

**Issue by knozturk** [Koenkk/zigbee2mqtt#23518]
### What happened?

Every time I update to 3.9. All my current devices becomes unavailable and it creates second devices as _2 at the end. 

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20230507

### Adapter

CC2652

### Setup

Add on to Home Assistant

**Comment by Koenkk** [comment]
Try removing the `base_topic` from your Z2M HA addon configuration file.

**Comment by knozturk** [comment]
Do I do this before the update or after? Because everytime I update, I recover from my backup. Currently, I am still on 3.8. Thanks,Kaan OzturkOn Aug 4, 2024, at 4:19 PM, Koen Kanters ***@***.***> wrote:﻿
Try removing the base_topic from your Z2M HA addon configuration file.

**Comment by knozturk** [comment]
After removing base_topic, it has worked.
