### ISSUE TITLE
Robb Switch ROB_200-009-0 reports 200% battery level

### ISSUE THREAD

**Issue by voslucas** [Koenkk/zigbee2mqtt#23519]
### What happened?

ROBB Smart ROB_200-009-0 device reports 200% battery level.

![image](https://github.com/user-attachments/assets/1f5944cb-a35f-46f1-8934-a6b223f4166d)

### What did you expect to happen?

Battery level cannot be more than 100%

### How to reproduce it (minimal and precise)

It is similar to issue [16454](https://github.com/Koenkk/zigbee2mqtt/issues/16454) 

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20240710

### Adapter

UZG-01 with latest firmware

### Setup

HAOS addon

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
