### ISSUE TITLE
Need help submitting new device - Hue White and Color Ambiance BR30 - Bluetooth variant

### ISSUE THREAD

**Issue by skawt-tee** [Koenkk/zigbee2mqtt#2351]
I have some of the new Hue white/color BR30 floods, the new variant with Bluetooth. These are not yet supported in z2m, but I've followed the new device guidance and have them working via edits to devices.js.

I am not proficient with Git, so I'm hoping someone can assist by submitting the following device entry properly. Let me know if further info is needed.

   {
       zigbeeModel: ['LCB001'],
       model: '548727',
       vendor: 'Philips',
       description: 'Hue White and Color Ambiance BR30 with Bluetooth',
       extend: hue.light_onoff_brightness_colortemp_colorxy,
   },

**Comment by Koenkk** [comment]
I've added it, will be supported in the zigbee2mqtt dev branch soon. thanks!
