### ISSUE TITLE
Sonoff SNZB-03P always showing Battery Low as Null

### ISSUE THREAD

**Issue by irata-coder** [Koenkk/zigbee2mqtt#23522]
### What happened?

<img width="569" alt="Sonoff" src="https://github.com/user-attachments/assets/2e956318-b6d4-460c-b202-842509715f13">

<img width="344" alt="Sonoff2" src="https://github.com/user-attachments/assets/22318ffe-5369-40fa-a12e-80c064813e68">

"Battery low" therefore "Power" status is not supplied by the device

`{
    "battery": 100,
    "illumination": "bright",
    "last_seen": "2024-08-05T13:13:47+01:00",
    "linkquality": 248,
    "motion_timeout": 15,
    "occupancy": false,
    "update": {
        "installed_version": 8705,
        "latest_version": 8705,
        "state": "idle"
    },
    "voltage": 3100
}`

Therefore, power is always show in the frontend as ? on all front end screens.  Waiting 24 hours or more has no improvment.

### What did you expect to happen?

The battery percentage should be used to evaluate battery power and show correct battery icon based upon percentage.

### How to reproduce it (minimal and precise)

Add a Sonoff SNZB-03P, power is imediately shown as ? and remains so.

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

7.4.3

### Adapter

Zigbee Dongle-E

### Setup

plain install on x86.64 debian

**Comment by Koenkk** [comment]
This was a mistake in the definition, removed it.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by pezzy-o** [comment]
@irata-coder is this fixed for you? I’m still seeing a question mark for my battery state (although battery is reported as 100%).

**Comment by irata-coder** [comment]
I'm seeing the same, the battery percentage is now reported correctly but the power source is showing as a question mark.  The device does not appear to report its powerSource, which can only be battery.

**Comment by pezzy-o** [comment]
That's right - looks like powerSource isn't reported. Technically a different issue to the one you reported, but same outcome I think.

**Comment by kingp0dd** [comment]
Are you guys getting `illumination` value from this device? Mine in Z2M always reports `dim` value.

**Comment by pezzy-o** [comment]
> Are you guys getting `illumination` value from this device? Mine in Z2M always reports `dim` value.

Seems to be working for me. Note the comment on the config page: "Only updated when occupancy is detected"

**Comment by kingp0dd** [comment]
Confirmed my 2nd unit is working, 1st one seems to be defective

**Comment by pezzy-o** [comment]
> That's right - looks like powerSource isn't reported. Technically a different issue to the one you reported, but same outcome I think.

This has been raised in [https://github.com/Koenkk/zigbee-herdsman-converters/issues/8098](url)
