### ISSUE TITLE
Interview failed for Aqara Presence sensor FP1 with ConbeeIII

### ISSUE THREAD

**Issue by Voriaz** [Koenkk/zigbee2mqtt#23526]
### What happened?

Hi,

I'm unable to add Aqara Presence sensor FP1 (https://www.zigbee2mqtt.io/devices/RTCZCGQ11LM.html) to Zigbee2mqtt.
I get "Interview failed"  with error 'Error: Interview failed because can not get active endpoints'.

The issue is only happening with this specific device that I tried to pair several time without success although it is supportred by Z2M.

Does anyone can help with this issue ?

### What did you expect to happen?

Device to pair successfully

### How to reproduce it (minimal and precise)

Try to pair Aqara Presence Sensor FP1 with ConbeeIII adapter

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

0x26530900

### Adapter

ConbeeIII

### Setup

x86-64 VM without docker

### Debug log

[z2m_debug_log_interview_failed.log](https://github.com/user-attachments/files/16500994/z2m_debug_log_interview_failed.log)

**Comment by clowncracker** [comment]
I'm having the same issue with a SONOFF Zigbee 3.0 USB Dongle Plus.  I have 7 other of these devices connected, but I cannot add another.  I don't know when the issue started.
