### ISSUE TITLE
smart plug TS011F_plug_1 command works randomly

### ISSUE THREAD

**Issue by azertylr** [Koenkk/zigbee2mqtt#23530]
### What happened?

hello,
I have a TS011F_plug_1 and I've been using it with tasmota2mqtt for a while and I've decided to use this awesome project now!

I've paired it with my Sonoff Bridge-E and I can read the status of the switch. Link quality is around 100

But when I want to switch it, I have a lot of timeout. It works like 10% of the time.

### What did you expect to happen?

switch to turn on/off when the command is send

### How to reproduce it (minimal and precise)

appair the power switch and try to switch its state in the dashboard

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

7.4.3 [GA]

### Adapter

Sonoff ZBDongle-E

### Setup

Z2M on docker on VM

### Debug log

error 2024-08-06 10:48:00z2m: Publish 'set' 'state' to 'switch1' failed: 'Error: ZCL command 0xa4c1386562b22da3/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":149})'

**Comment by rvalitov** [comment]
Duplicate of #22973 ?
