### ISSUE TITLE
Tuya is correct but lacking one more socket entity

### ISSUE THREAD

**Issue by reylinux** [Koenkk/zigbee2mqtt#23542]
### What happened?

Correct device however only able to control one socket instead of two. I already removed and re added this more than 3 times and still got the same result
![image](https://github.com/user-attachments/assets/7f78a364-4d75-4d40-8d8a-77d8935926cd)

The actual device
![20240807_061620](https://github.com/user-attachments/assets/4bbb8d89-b1bc-40ab-8f70-dbcaadedacbf)

### What did you expect to happen?

Previously was working fine with ZHA. It's detected with the same model - TS011F but doesn't allow me to control two sockets like I used to with ZHA.

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20210708

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Add On with HA Green

**Comment by crembz** [comment]
I am having the same issue with this device. Only one of the two plugs show in z2m

**Comment by Koenkk** [comment]
Could you try to: stop z2m, in the `data/database.db` change `_TZ3000_qlmnxmac` to `_TZ3000_bep7ccew`, start z2m and check if it works?

**Comment by reylinux** [comment]
Hi thanks for the reply.

It exposes correctly however I still can't get them to work as expected.

![Screenshot_20240813_064642_Home Assistant](https://github.com/user-attachments/assets/f2a43bd8-c345-4d7c-8bce-a2cfbe38511b)


![Screenshot_20240813_064633_Home Assistant](https://github.com/user-attachments/assets/bc00d4b5-926a-426b-b797-cd2462af0d19)

**Comment by reylinux** [comment]
> Could you try to: stop z2m, in the `data/database.db` change `_TZ3000_qlmnxmac` to `_TZ3000_bep7ccew`, start z2m and check if it works?

Hi following this issue, I've changed the database to _TZ3000_8nyaanzb and it seems to be working ok now
![image](https://github.com/user-attachments/assets/aa8fa970-b067-45c2-b71f-89d29f436062)

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by crembz** [comment]
> > Could you try to: stop z2m, in the `data/database.db` change `_TZ3000_qlmnxmac` to `_TZ3000_bep7ccew`, start z2m and check if it works?
> 
> Hi following this issue, I've changed the database to _TZ3000_8nyaanzb and it seems to be working ok now ![image](https://private-user-images.githubusercontent.com/68408920/357608175-aa8fa970-b067-45c2-b71f-89d29f436062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzE1NDcsIm5iZiI6MTcyMzc3MTI0NywicGF0aCI6Ii82ODQwODkyMC8zNTc2MDgxNzUtYWE4ZmE5NzAtYjA2Ny00NWMyLWI3MWYtODlkMjlmNDM2MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODIwNmYzZDZmOTU5OWRmMmRhZDE4ZDVkYzVhYmRiYzBiZTdmZmFkNmY3N2ZlYzQwYjU0NGE4NGQ2NWJiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QZB2x-tdN0hci3DdaI0xFfahZ_pVBVt7l8r0-9cKOzk)
> 
> ![image](https://private-user-images.githubusercontent.com/68408920/357608570-7e41fa74-c48c-41a2-92ca-6a9561ccf4a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzE1NDcsIm5iZiI6MTcyMzc3MTI0NywicGF0aCI6Ii82ODQwODkyMC8zNTc2MDg1NzAtN2U0MWZhNzQtYzQ4Yy00MWEyLTkyY2EtNmE5NTYxY2NmNGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWFhYjgwOTkzNjA4MGQ2YmQ5MWIwZTgxNDBiNDhlZTlhMDI3MWZhZGVjMjM2MjcyYjA3ZjdhNDNhMDhkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NL_Ei3jap45zBJxxymC64nPr_SUkcTNzi713217jLrM)

I'm new to all this. Confirmed this worked for me last night. Can you please help me understand how you found what device code to use?

**Comment by reylinux** [comment]
> Added, thanks!
> 
> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Hi, thanks for the support. I was wondering if _TZ3000_8nyaanzb also supports power/energy monitoring just like _TZ3000_qlmnxmac? If I remember correctly, this device supports energy monitoring in ZHA (for both sockets)



![image](https://github.com/user-attachments/assets/d643a1e1-527a-430a-bfd0-b3d73b5f14f4)

**Comment by reylinux** [comment]
> > > Could you try to: stop z2m, in the `data/database.db` change `_TZ3000_qlmnxmac` to `_TZ3000_bep7ccew`, start z2m and check if it works?
> > 
> > 
> > Hi following this issue, I've changed the database to _TZ3000_8nyaanzb and it seems to be working ok now ![image](https://private-user-images.githubusercontent.com/68408920/357608175-aa8fa970-b067-45c2-b71f-89d29f436062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzE1NDcsIm5iZiI6MTcyMzc3MTI0NywicGF0aCI6Ii82ODQwODkyMC8zNTc2MDgxNzUtYWE4ZmE5NzAtYjA2Ny00NWMyLWI3MWYtODlkMjlmNDM2MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODIwNmYzZDZmOTU5OWRmMmRhZDE4ZDVkYzVhYmRiYzBiZTdmZmFkNmY3N2ZlYzQwYjU0NGE4NGQ2NWJiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QZB2x-tdN0hci3DdaI0xFfahZ_pVBVt7l8r0-9cKOzk)
> > ![image](https://private-user-images.githubusercontent.com/68408920/357608570-7e41fa74-c48c-41a2-92ca-6a9561ccf4a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzE1NDcsIm5iZiI6MTcyMzc3MTI0NywicGF0aCI6Ii82ODQwODkyMC8zNTc2MDg1NzAtN2U0MWZhNzQtYzQ4Yy00MWEyLTkyY2EtNmE5NTYxY2NmNGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWFhYjgwOTkzNjA4MGQ2YmQ5MWIwZTgxNDBiNDhlZTlhMDI3MWZhZGVjMjM2MjcyYjA3ZjdhNDNhMDhkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NL_Ei3jap45zBJxxymC64nPr_SUkcTNzi713217jLrM)
> 
> I'm new to all this. Confirmed this worked for me last night. Can you please help me understand how you found what device code to use?

Hi, I just got lucky as I have another device at home that was purchased from a different supplier and paired with _TZ3000_8nyaanzb. From there I then tried to change the _TZ3000_qlmnxmac  to this one and confirmed to work.

**Comment by crembz** [comment]
> > Added, thanks!
> > Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
> 
> Hi, thanks for the support. I was wondering if _TZ3000_8nyaanzb also supports power/energy monitoring just like _TZ3000_qlmnxmac? If I remember correctly, this device supports energy monitoring in ZHA (for both sockets)
> 
> ![image](https://private-user-images.githubusercontent.com/68408920/358440835-d643a1e1-527a-430a-bfd0-b3d73b5f14f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzIwMTcsIm5iZiI6MTcyMzc3MTcxNywicGF0aCI6Ii82ODQwODkyMC8zNTg0NDA4MzUtZDY0M2ExZTEtNTI3YS00MzBhLWJmZDAtYjNkNzNiNWYxNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmY4ZGEyMDJhNzAyZmI4OGUwODBmNDBjY2E0ZGY4ZjMyMDFhZTM0OGU5ZGZiYmMzNDliODE5OTVhMGZjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ycvQQrdCDJQMO-xKI_PhBm-80pD-ndjcGVSWKawnaFw)

Just looking at it now in zha and it only reports current and power for the device not for each socket.

**Comment by reylinux** [comment]
> > > Added, thanks!
> > > Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
> > 
> > 
> > Hi, thanks for the support. I was wondering if _TZ3000_8nyaanzb also supports power/energy monitoring just like _TZ3000_qlmnxmac? If I remember correctly, this device supports energy monitoring in ZHA (for both sockets)
> > ![image](https://private-user-images.githubusercontent.com/68408920/358440835-d643a1e1-527a-430a-bfd0-b3d73b5f14f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzIwMTcsIm5iZiI6MTcyMzc3MTcxNywicGF0aCI6Ii82ODQwODkyMC8zNTg0NDA4MzUtZDY0M2ExZTEtNTI3YS00MzBhLWJmZDAtYjNkNzNiNWYxNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmY4ZGEyMDJhNzAyZmI4OGUwODBmNDBjY2E0ZGY4ZjMyMDFhZTM0OGU5ZGZiYmMzNDliODE5OTVhMGZjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ycvQQrdCDJQMO-xKI_PhBm-80pD-ndjcGVSWKawnaFw)
> 
> Just looking at it now in zha and it only reports current and power for the device not for each socket.

Thanks for confirming. I don't have access for ZHA anymore. Yeah it's a shame otherwise it's good for tracking

**Comment by crembz** [comment]
Just to clarify ... ZHA supports power monitoring for this device as a total (not per socket). Currently z2m does not seem to expose power monitoring at all

![image](https://github.com/user-attachments/assets/5f2b1852-b5f8-4df5-bff6-5232c64336c9)

Any chance this can be added?

**Comment by crembz** [comment]
@reylinux can you try the device code _TZ3000_dd8wwzcy. It seems to be correctly reporting the power values as well as control for both sockets

**Comment by reylinux** [comment]
> @reylinux can you try the device code _TZ3000_dd8wwzcy. It seems to be correctly reporting the power values as well as control for both sockets

Hi Crembz thanks. How do you think you could figure out this time?
