### ISSUE TITLE
Device specific configuration - debounce should allow to filter out messages by specific key

### ISSUE THREAD

**Issue by frontend89** [Koenkk/zigbee2mqtt#2354]
While rotating IKEA Symfonisk **E1744** I have hundreds of messages with action rotate_right/left.
Currently there's no way to throttle them by specific key (in this case action).
When I use debounce it cut out all messages but rotate_stop which doesn't allow to create animation based on rotating in specific direction.

**Comment by frontend89** [comment]
https://github.com/Koenkk/zigbee2mqtt/pull/2370

**Comment by frontend89** [comment]
https://github.com/Koenkk/zigbee2mqtt.io/pull/164

**Comment by Koenkk** [comment]
Merged, thanks!
