### ISSUE TITLE
Xiaomi ZNJLBL01LM stops responding to /set commands

### ISSUE THREAD

**Issue by zengateway** [Koenkk/zigbee2mqtt#23550]
### What happened?

I have several Roller shade driver E1(ZNJLBL01LM) and they are sometimes stopped responding to z2m commands. Re-pairing fixed the issue for another 10-20 days.

Firmware ZNJLBL01LM is latest 10-09-2022

My observing
- the device works when it is linked to a router/coordinator in the network map
- after some time the device gets linked to something else, the link is not shown in the map and the device cannot be controlled wirelessly
- weird thing - it seems that using the physical buttons on the device WILL update the exposed values in the Z2M (e. g. motor running, position) but the commands sent from Z2M to the device will timeout

`Publish 'get' 'position' to 'FRIENDLY_NAME' failed: 'Error: Read 00x54ef4410006bbc0b/1 genAnalogOutput([85], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 32725 - 1 - 52 - 13 - 1 after 10000ms)'`

If the device didn't hop to another router, it would most likely work fine. :/

### Zigbee2MQTT version

1.39.1 

### Adapter firmware version

20230507

### Adapter

zStack3x0

### Setup

HAOS

**Comment by vaaarg** [comment]
same problem. Device stops working after several days. 
Pushing the pairing button and its working again (for now)

iobroker/zigbee adapter (latest github)
type:zStack30x
version:2-2.2.7.2.
revision:20211222
port:/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
channel:11
