### ISSUE TITLE
Tuya ZY-M100-24GV2 _TZE204_7gclukjs presence sensitivity and move sensitivity are divided by 10

### ISSUE THREAD

**Issue by monqui-ulia** [Koenkk/zigbee2mqtt#23582]
### What happened?

For example, if you set move sensitivity to 8, the value that is updated and displayed is 0.8

<img width="889" alt="Captura de pantalla 2024-08-10 a las 10 55 42" src="https://github.com/user-attachments/assets/aa84c645-1ae8-4065-9fad-f77c2cb650f3">

<img width="877" alt="Captura de pantalla 2024-08-10 a las 10 42 58" src="https://github.com/user-attachments/assets/4181dbf1-2fd6-4abf-ac80-f1d272784b40">

<img width="498" alt="Captura de pantalla 2024-08-10 a las 11 35 02" src="https://github.com/user-attachments/assets/f53f8272-c4ff-4e11-aae4-60b0d9360e13">

<img width="500" alt="WhatsApp Image 2024-08-11 at 10 54 56" src="https://github.com/user-attachments/assets/d1297785-76d0-47fd-984a-769f3559ba5d">

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on HAOS on miniPC

### Debug log

<img width="1128" alt="Captura de pantalla 2024-08-10 a las 11 41 44" src="https://github.com/user-attachments/assets/9353d2fc-870f-45ea-8d5c-e2b4bbc896d8">

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
