### ISSUE TITLE
[New device support]: TS0601  Manufacturer _TZE204_xnbkhhdr

### ISSUE THREAD

**Issue by damianrguez** [Koenkk/zigbee2mqtt#23611]
### Link

https://a.aliexpress.com/_EvidC6d

### Database entry

{"id":38,"type":"EndDevice","ieeeAddr":"0xa4c138105f6ec68c","nwkAddr":62855,"manufId":4417,"manufName":"_TZE204_xnbkhhdr","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"�OO.i\u0000SO.i_QO.i�RO.i;SO.i;SO.i�SO.i�SO.i","65506":56,"65508":0,"stackVersion":0,"dateCode":"","appVersion":73,"modelId":"TS0601","manufacturerName":"_TZE204_xnbkhhdr","powerSource":3,"zclVersion":3,"hwVersion":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1723642350302}

### Comments

https://www.zigbee2mqtt.io/devices/ZWT198_ZWT100-BH.html

76 / 5.000
The device appears as compatible but when adding it it says not supported

### External definition

```shell
https://a.aliexpress.com/_EvidC6d
```

**Comment by whisimon** [comment]
Ditto, me too.

**Comment by whisimon** [comment]
Looks like this is a new fingerprint. @Koenkk can you please add this fingerprint _TZE204_xnbkhhdr to the next build?

**Comment by whisimon** [comment]
> Looks like this is a new fingerprint. @Koenkk can you please add this fingerprint _TZE204_xnbkhhdr to the next build?

Apologies, I mean "is it possible to add this to the next build, or is there another way I can/ we can better address this?"

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by gpaolo969** [comment]
Good evening,
I have the same fingerprint, but the device is not supported. Maybe some break in new release ?

This is my data. The model is ZWT198.

Link
https://a.aliexpress.com/_EvidC6d

Database entry
{"id":39,"type":"EndDevice","ieeeAddr":"0xa4c138f82c8e3288","nwkAddr":42919,"manufId":4417,"manufName":"_TZE284_xnbkhhdr","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0,60672],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65487":14400,"65506":56,"65508":0,"appVersion":77,"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1738340758816}
Comments
https://www.zigbee2mqtt.io/devices/ZWT198_ZWT100-BH.html

76 / 5.000
The device appears as compatible but when adding it it says not supported

**Comment by Koenkk** [comment]
`_TZE284_xnbkhhdr` is supported in z2m 2.1.0

**Comment by tureka** [comment]
_TZE284_xnbkhhdr does not report battery state
