### ISSUE TITLE
[New device support]: MOES Smart ZigBee Wireless Switch, Self-powered 2/3 Gang ZT-LP-ZEU2S-WH-MS

### ISSUE THREAD

**Issue by CokACola44** [Koenkk/zigbee2mqtt#23618]
### Link

https://moeshouse.com/products/zigbee-wireless-self-powered-scene-switch?variant=45340934373691

### Database entry

{"id":43,"type":"GreenPower","ieeeAddr":"0x00000000de1db7f5","nwkAddr":47093,"manufId":null,"modelId":"GreenPower_2","epList":[242],"endpoints":{"242":{"epId":242,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":1723640434145}

### Comments

Hello,

I tried to add this self-powered Zigbee switch. The pairing works, but I don't see anything in the "expose" section, so I can't use it. The switch I am trying to add in Zigbee2MQTT has two buttons.

Thanks in advance for your support!

### External definition

```shell
const definition = {
    zigbeeModel: ['GreenPower_2'],
    model: 'GreenPower_2',
    vendor: '',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

**Comment by tshakah** [comment]
This is also being tracked in https://github.com/Koenkk/zigbee2mqtt/issues/19405

**Comment by gurrier** [comment]
I have the 3 button variant of this Moes branded greenpower switch.
I too get exactly the same External definition as the OP above.

If anyone has an understanding of what is required to get it to work or to develop a convertor, I would love to help.
