### ISSUE TITLE
[Wrong device]: Nous A1Z "Reset energy" chapter was removed

### ISSUE THREAD

**Issue by krusta4711** [Koenkk/zigbee2mqtt#23647]
### Link

https://www.zigbee2mqtt.io/devices/A1Z.html

### Model

A1Z

### Description

Reset energy

### Vendor

Nous

### Picture (link)

just the description might be wrong

### Database entry

just the description might be wrong

### Notes

The section "Reset energy" was removed from the descripton. Was this by purpose? At least for mine plugs the command still works.

**Comment by krusta4711** [comment]
@Koenkk It looks like you did the change in the repository. Was it by purpose. For me resetting the energy command still works fine.

**Comment by Koenkk** [comment]
Not on purpose, could you make a PR to add it back?

**Comment by krusta4711** [comment]
@Koenkk 
I created a PR for reintroducing the remove chapter:
https://github.com/Koenkk/zigbee2mqtt.io/pull/2956
