### ISSUE TITLE
[New device support]: Philips Hue White and Color 400lm (!!!) - Zigbee model code LCG006

### ISSUE THREAD

**Issue by wernerdaehn** [Koenkk/zigbee2mqtt#23675]
### Link

https://www.philips-hue.com/de-at/p/hue-white---color-ambiance-gu10---smarter-spot/8720169229754

### Database entry

I do not have access to that but it should be the same as the normal LCG002

### Comments

Hue has a new version of the LCG002 (350lm) with 400lm, the LCG006. 

### External definition

```shell
const {identify} = require('zigbee-herdsman-converters/lib/modernExtend');
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['LCG006'],
    model: 'LCG006',
    vendor: 'Signify Netherlands B.V.',
    description: 'Automatically generated definition',
    extend: [identify(), philipsLight({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"],"enhancedHue":true}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
`LCG006` will be supported in the next release and is already supported in the  [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
