### ISSUE TITLE
Third reality sensor needs to have power source changed to battery

### ISSUE THREAD

**Issue by rasmusson** [Koenkk/zigbee2mqtt#23694]
### What happened?

The third reality garage door tilt sensor 3RDTS01056Z is battery powered but is displayed as being connected to main. 
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/third_reality.ts

### What did you expect to happen?

It should be displayed as powered by battery

### Zigbee2MQTT version

1.39.1 commit: e132316

### Adapter firmware version

20230507

### Adapter

Slaesh CC2652R 

### Setup

Docker

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
