### ISSUE TITLE
[Feature request]: OWON PC 321 - Add clear measurement data

### ISSUE THREAD

**Issue by Lacrymal3** [Koenkk/zigbee2mqtt#23695]
### Is your feature request related to a problem? Please describe

Hello,

Sorry for my English.

I have a proposal for a modification to add a reset command for the counters of the OWON PC321 clamp meter.
![image](https://github.com/user-attachments/assets/86e158a5-eb9e-4470-bdcb-1c5f3bbcbf9c)

Thank you in advance.

### Describe the solution you'd like

Add a push button.
![image](https://github.com/user-attachments/assets/dc454f3d-570b-4d9f-9fd5-d749a6e4dba9)

### Describe alternatives you've considered

Attached is the modified code (you need to replace .txt with .js.):
[PC321.txt](https://github.com/user-attachments/files/16706833/PC321.txt)

The modifications :
```
const tzLocal = {
    PC321_clearMetering: {
        key: ['clear_metering'],
        convertSet: async (entity, key, value, meta) => {
            const endpoint = meta.device.getEndpoint(1);
            const group = 0xFFE0;
            const command = 0x00;
            const payload = {};

            await endpoint.command(group, command, payload, {disableDefaultResponse: true});
            meta.logger.info(`Sent clear command to ${entity.ieeeAddr}`);
        },
    },
};
```

`toZigbee: [tzLocal.PC321_clearMetering],`

`e.enum('clear_metering', ea.SET, ['Clear']).withDescription('Clear measurement data'),`

### Additional context

Datasheet (clear measurement data - sheet 12) :
[PC321 zha clusters and attributes v1.2.4.pdf](https://github.com/user-attachments/files/16706594/PC321.zha.clusters.and.attributes.v1.2.4.pdf)

**Comment by Koenkk** [comment]
Looks good, could you make a pull request for this?

**Comment by Lacrymal3** [comment]
Alright, i'm trying to make a pull request

**Comment by Lacrymal3** [comment]
Pull request : 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/7895
