### ISSUE TITLE
TS0001 state update

### ISSUE THREAD

**Issue by krzysztof-cislo** [Koenkk/zigbee2mqtt#23702]
### What happened?

I have two groups of light switches. One is identifying as [TS0001_switch_module](https://www.zigbee2mqtt.io/devices/TS0001_switch_module.html#tuya-ts0001_switch_module), another one is recognized as [TS0001](https://www.zigbee2mqtt.io/devices/TS0001.html#tuya-ts0001).

Problem which I experience is synchronizing physical device state. Whenever I turn on/off switch from zigbe2mqtt (via Home Assistant) it looks like the physical switch state is not updated and in result I have to "switch the switch" two times to turn the light off/on. It is very annoying for most of the household members because on the first glance it looks like switch broke).

It works fine the other way round (whenever I change status from the physical switch I can use HA normally because the status is correctly updated). 

I search over Internet, also this forum. I asked Chat GPT which suggested to set `retain` to `true` (didn't help) or to try to create an automation to try to propagate the state to the device (haven't tried yet)...

Is anyone experienced this issue maybe and is there a simpler solution than automation to fix it?

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

Notsure

### Adapter

deconz

### Setup

Add-on on Home Assistant OS on Raspberry PI 4

**Comment by Wikibear** [comment]
Doesn't matter which device. All devices I can't retain. This devices retained stay and I click on a new device retain the check will show for a second and then disapear. I have no chance to retain this device...

Zigbee2MQTT-Version
    [1.40.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.1) commit: [403d3c0](https://github.com/Koenkk/zigbee2mqtt/commit/403d3c0)

Coordinator-Typ
    ConBee2/RaspBee2

Coordinator-Version
    0x26780700

Frontend-Version
    0.7.4

Zigbee Herdsman Konverter Version
    20.12.1

Zigbee Herdsman Version
    0.57.3
