### ISSUE TITLE
Legrand Celiane LED won't switch off

### ISSUE THREAD

**Issue by mathgim** [Koenkk/zigbee2mqtt#23709]
### What happened?

I have two [067775/741811](https://www.zigbee2mqtt.io/devices/067775_741811.html#legrand-067775%252F741811) and one [199182](https://www.zigbee2mqtt.io/devices/199182.html#legrand-199182) Legrand Celiane Zigbee devices. It works well on my zigbee2mqtt Home Assistant addon apart from one thing: the LED stays green on each of those three devices. 

If I use Identify feature in zigbee2mqtt, the LED blinks properly from the color I picked but it comes back to green just after that. I did swith off "Led in dark" and "Led if on" but the LED remains green. I also tried to switch off the main device state but of course the LED remains green.
For the power outlet and for the wall switch.

What can I do to bring back the LED to work properly?

Exemplae of current state:
```
{
    "last_seen": "2024-08-22T23:44:56+02:00",
    "linkquality": 21,
    "power": 67,
    "power_apparent": 98,
    "state": "ON",
    "update": {
        "installed_version": 5916159,
        "latest_version": 5916159,
        "state": "idle"
    },
    "action": null,
    "elapsed": 2003,
    "led_if_on": "OFF",
    "led_in_dark": "OFF",
    "power_on_behavior": "off",
    "update_available": null
}
```

### What did you expect to happen?

LED should switch off with main device state if  "Led in dark" and "Led if on" are off.

### How to reproduce it (minimal and precise)

Switch off one of these devices and check the LED light.

### Zigbee2MQTT version

1.39.1-1

### Adapter firmware version

20220219

### Adapter

zStack3x0

### Setup

addon Pi 4

**Comment by apages2** [comment]
Hello

the solid green LED normally indicates that the Zigbee network is open

normally the LED should go out when you deactivate pairing or after 5 minutes
