### ISSUE TITLE
[New device support]: / Iluminize  5144.01 // 5144.11 // 5144.21 // --> working converters inside

### ISSUE THREAD

**Issue by senna1992** [Koenkk/zigbee2mqtt#23701]
### Link

https://www.iluminize.com/

### Database entry

dont know where to obtain these :/

### Comments

/// 5144.01
IEEE-Addresse "0x588e81fffe150d87"
Netzwerk-Adresse "0xA3F0 / 41968"

/// 5144.11
IEEE-Addresse "0x000d6f0013f069ad"
Netzwerk-Adresse "0x5C18 / 23576"

/// 5144.21

IEEE-Addresse "0x000d6f0013f0fc6a"
Netzwerk-Adresse "0x7646 / 30278"
[KEY-001.json](https://github.com/user-attachments/files/16709652/KEY-001.json)
[KEY-002.json](https://github.com/user-attachments/files/16709653/KEY-002.json)
[KEY-005.json](https://github.com/user-attachments/files/16709654/KEY-005.json)

i had to rename the file extension to .json from .js

### External definition

```shell
/// 5144.01

const {battery, identify, commandsOnOff, commandsLevelCtrl, commandsColorCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['ZGRC-KEY-005'],
    model: 'ZGRC-KEY-005',
    vendor: 'Sunricher',
    description: 'Automatically generated definition',
    extend: [battery(), identify(), commandsOnOff(), commandsLevelCtrl(), commandsColorCtrl()],
    meta: {},
};

module.exports = definition;



//// 5144.11

const {battery, identify, commandsOnOff, commandsLevelCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['ZGRC-KEY-001'],
    model: 'ZGRC-KEY-001',
    vendor: 'iluminize',
    description: 'Automatically generated definition',
    extend: [battery(), identify(), commandsOnOff(), commandsLevelCtrl()],
    meta: {},
};

module.exports = definition;


/// 5144.21

const {battery, identify, commandsOnOff, commandsLevelCtrl, commandsColorCtrl} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['ZGRC-KEY-002'],
    model: 'ZGRC-KEY-002',
    vendor: 'iluminize',
    description: 'Automatically generated definition',
    extend: [battery(), identify(), commandsOnOff(), commandsLevelCtrl(), commandsColorCtrl()],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Could you create a pull request by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/iluminize.ts)?

**Comment by senna1992** [comment]
> Could you create a pull request by clicking [here](https://github.com/Koenkk/zigbee-herdsman-converters/edit/master/src/devices/iluminize.ts)?

i dont know how to do that and therefore dont want to break stuff.
Please someone else do that :)
