### ISSUE TITLE
seMetering currentSummDelivered Reporting Configuration behaviour

### ISSUE THREAD

**Issue by martyn-vesternet** [Koenkk/zigbee2mqtt#23711]
### What happened?

@Koenkk what is the correct format for configuration in the currentSummDelivered attribute on the seMetering cluster?

In https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/modernExtend.ts I see this:

```
seMetering: {
            // Report change with every 5W change
            power: {attribute: 'instantaneousDemand', divisor: 'divisor', multiplier: 'multiplier', forced: args.power, change: 5},
            // Report change with every 0.1kWh change
            energy: {attribute: 'currentSummDelivered', divisor: 'divisor', multiplier: 'multiplier', forced: args.energy, change: 0.1},
            // produced_energy: {attribute: 'currentSummReceived', divisor: 'divisor', multiplier: 'multiplier', forced: args.energy, change: 0.1},
        },
```

Which suggests "0.1" format should be used and will equal 0.1kWh.

However some herdsman converters are using this format:

`await reporting.currentSummDelivered(endpoint, {min: 1, max: 600, change: [0, 5]});`

And some herdsman converters are using this format:

`await reporting.currentSummDelivered(endpoint, {min: 10, max: 3600, change: 5});`

In my testing, the divisor and multiplier are being read correctly from the device:

![image](https://github.com/user-attachments/assets/f13d2187-569c-4094-8a2b-6118a86475cc)

So this particular device counts 3,600,000 per kWh.

Something is amiss somewhere.

If I use this in an external converter:

`await reporting.currentSummDelivered(endpoint11, {min: 10, change: 0.1, max: 600});`

Then the result is this in the UI:

![image](https://github.com/user-attachments/assets/dbe1a6ff-50fe-4ea6-b36a-9d5c11d46ab6)

And 0 being sent to the device during pairing:

![image](https://github.com/user-attachments/assets/1a589950-1a86-4655-86d3-675b51f368b8)

On the other hand, if I use this in an external converter:

`await reporting.currentSummDelivered(endpoint11, {min: 10, change: [0, 1], max: 600});`

Then the result is this in the UI:

![image](https://github.com/user-attachments/assets/952fb614-aa8f-4e14-99c9-d48496d4cbb2)

And 1 being sent to the device during pairing:

![image](https://github.com/user-attachments/assets/c20abcf3-f491-477e-b40b-4f15d198b6a2)

Or if I use this in an external converter:

`await reporting.currentSummDelivered(endpoint11, {min: 10, change: [0, 360000], max: 600});`

This is the UI:

![image](https://github.com/user-attachments/assets/164cb7ee-b4c3-4ecd-ae8e-736ddc81c860)

And this is sent to the device during pairing:

![image](https://github.com/user-attachments/assets/91e5332c-4534-4dec-96de-84e4ea60a6e1)

If I use this in the external converter:

`await reporting.currentSummDelivered(endpoint11, {min: 10, change: 3600000, max: 600});`

Then this is the result in the UI:

![image](https://github.com/user-attachments/assets/0ab64f58-4a47-400f-81f6-bffb5ab6c3db)

But again, 0 is being sent to the device during pairing:

![image](https://github.com/user-attachments/assets/ba46554b-0049-4abe-999a-f02ea59582e0)

If all of these formats *should* be acceptable:

0.1
[0,1]
360000

Then presumably they should all produce the correct end result being sent to the device?

Finally, if I make a manual entry in the UI with any value, always 0 is sent to the device.

1000:

![image](https://github.com/user-attachments/assets/b5cd52c9-2187-492f-ae07-ec27f7205284)

0 is sent to the device:

![image](https://github.com/user-attachments/assets/5beaa590-28bc-4450-bb3f-fc09cb0037d8)

0.5:

![image](https://github.com/user-attachments/assets/38890914-431d-4aaf-b552-195058f681f9)

Again 0 to the device:

![image](https://github.com/user-attachments/assets/4f11f71d-6819-4ded-9485-0817890823aa)

3600000:

![image](https://github.com/user-attachments/assets/5934223c-c6a2-47d0-91fd-c80f46be2a4e)

Again 0 to the device:

![image](https://github.com/user-attachments/assets/c1ffad84-aae9-4499-b7f3-7af4bf9f1511)

Or even 1:

![image](https://github.com/user-attachments/assets/6694592f-34b2-4cea-8e97-0ebe65a7916a)

Again 0 to the device:

![image](https://github.com/user-attachments/assets/ba52e0b7-1769-4dad-84ff-44f578e0d8a2)

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

 EZSP v8

### Setup

Home Assistant Supervised Z2M addon

**Comment by Koenkk** [comment]
In modernExtend, the `change` for `currentSummDelivered` is converted here (according to divisor/multiplier):  https://github.com/Koenkk/zigbee-herdsman-converters/blob/8d7f1c4aa7c253646fef7603bb1e07a307d64349/src/lib/modernExtend.ts#L1680

- 0.1 -> should not be supported, only ints
- [0,1] -> ideally this should also not be supported (but a nodejs number cannot fit a uint48 afaik)
360000 -> only this should be supported

**Comment by Koenkk** [comment]
It's indeed wrong, I will put it on my backlog

**Comment by Koenkk** [comment]
Fixed now! Removed the `[number, number]`, it's always a `number` now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
