### ISSUE TITLE
Huge amount of "ROUTE_ERROR_ADDRESS_CONFLICT" and devices unresponsive

### ISSUE THREAD

**Issue by saveriol** [Koenkk/zigbee2mqtt#23712]
### What happened?

1.  Log flooded with ROUTE_ERROR_ADDRESS_CONFLICT, i.e.

`zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "13663"` (note: not limited to 13663 device, but nearly all devices)

2. Some devices unresponsive, errors like:

`z2m: Failed to read state of 'Luce studio' after reconnect (ZCL command 0xf4ce36e6f546ea3c/10 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":10,"options":4160,"groupId":0,"sequence":162}))`

### What did you expect to happen?

No conflicts, devices responsive

### How to reproduce it (minimal and precise)

Can't say.

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

7.4.3 [GA]

### Adapter

ember driver

### Setup

Home Assistant Yellow

### Debug log

[log.log](https://github.com/user-attachments/files/16727548/log.log)

**Comment by saveriol** [comment]
What I already tried: removing + resetting devices, rebuilding network with key regeneration, rejoin devices. Issue persists

**Comment by kylepyke** [comment]
How did you solve this?

**Comment by saveriol** [comment]
After updating to a next version of Z2M and updating all the vimar firmwares the issue resolved itself.
