### ISSUE TITLE
Unable to pair more than 1 Aqara Light Sensor T1 (GZCGQ11LM)

### ISSUE THREAD

**Issue by notownblues** [Koenkk/zigbee2mqtt#23714]
### What happened?

I have 3 x Aqara Light Sensor T1 (GZCGQ11LM) and I'm only able to pair one at a time.

I tried the following steps to no avail:
- Pair before 'Permit Join' for 10 seconds until pairing light comes on
- Pair after 'Permit Join' for 10 seconds until pairing light comes on
- Remove all Aqara Light Sensors T1 (I had 2 old ones paired)
- Stop Zigbee2MQTT and unplug the coordinator for 10 seconds
- Restart Home Assistant
- Restart Proxmox VM

### What did you expect to happen?

Successfully pair more than one GZCGQ11LM

### How to reproduce it (minimal and precise)

1. Click 'Permit Join'
2. Press pairing button on GZCGQ11LM until the pairing light comes on

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20230507

### Adapter

Sonoff Dongle Plus

### Setup

Home Assistant OS on Mini PC

### Debug log

Nothing useful I can see in the logs but here they are:

Info 2024-08-23 12:45:16z2m: Successfully changed options
Info 2024-08-23 12:45:16z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"p69lj-3"}'
Info 2024-08-23 12:45:19z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Fridge Door', payload '{"battery":100,"contact":true,"device_temperature":23,"linkquality":40,"power_outage_count":10,"trigger_count":0,"voltage":3025}'
Info 2024-08-23 12:45:20z2m: Zigbee: allowing new devices to join.
Info 2024-08-23 12:45:20z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"p69lj-4"}'
Info 2024-08-23 12:45:29z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Hallway Motion Sensor 2', payload '{"battery":100,"device_temperature":23,"illuminance":289,"illuminance_lux":289,"linkquality":40,"occupancy":true,"power_outage_count":39,"voltage":3035}'
Info 2024-08-23 12:45:35z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Stairs Motion Sensor', payload '{"battery":100,"illuminance":22652,"illuminance_lux":184,"led_indication":null,"linkquality":40,"motion_sensitivity":"high","occupancy":false,"occupancy_timeout":0,"temperature":22.07}'
Info 2024-08-23 12:45:41z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Kitchen Window Blind', payload '{"battery":49,"charging_status":null,"device_temperature":21,"linkquality":43,"motor_speed":"high","motor_state":"stopped","position":0,"power_outage_count":0,"running":false,"state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null}'
Info 2024-08-23 12:45:46z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Kitchen Presence Sensor', payload '{"action":null,"approach_distance":"medium","device_temperature":29,"linkquality":47,"monitoring_mode":"undirected","motion_sensitivity":"high","power_outage_count":28,"presence":true,"presence_event":"away","update":{"installed_version":58,"latest_version":54,"state":"idle"},"update_available":null}'
Info 2024-08-23 12:45:49z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Bedroom Presence Sensor', payload '{"action":null,"approach_distance":"medium","device_temperature":28,"linkquality":47,"monitoring_mode":"undirected","motion_sensitivity":"high","power_outage_count":0,"presence":false,"presence_event":"approach","update":{"installed_version":58,"latest_version":54,"state":"idle"},"update_available":null}'

**Comment by Chartreusito** [comment]
@notownblues were you able to solve your problem ?
