### ISSUE TITLE
npm ci takes forever after trying to use update.sh

### ISSUE THREAD

**Issue by its-Zeke** [Koenkk/zigbee2mqtt#23720]
### What happened?

I wanted to add a new zigbee device to my devices, but it wasnt working. Therefore i decided to update my z2m version using the update.sh script in the opt/z2m folder. 
After waiting for about 5h nothing more seemed to happen:
![image](https://github.com/user-attachments/assets/eb47edc0-dc1f-40ab-9755-36fc92b14603)

I tryed to use the dev branch, same behaviour. System completely stucks.
When i abort the script, this is the end of the logfile:
![image](https://github.com/user-attachments/assets/8441b687-d1ed-4519-b3f0-14528b24d96d)

Also since trying to update, my z2m service keeps crashing and restarting itself.

### What did you expect to happen?

I was expecting to use the update.sh script to update things that needs to get updates and done. 

### How to reproduce it (minimal and precise)

run './update.sh'

### Zigbee2MQTT version

1.39.1 at least thats what npm run build says, which also fails

### Adapter firmware version

20210708

### Adapter

sonoff stick

### Setup

plain

**Comment by its-Zeke** [comment]
This is now the status of the service :
![image](https://github.com/user-attachments/assets/b6e1ff19-7eb4-4916-b3ae-f71e41c89c17)

**Comment by lux73** [comment]
upgrade NodeJS to v20 minimum...

you are running 18.20.4 which is not supported anymore

**Comment by its-Zeke** [comment]
Hm, okay i updated the node version now to >20 using nvm, since npm didnt update version higher than 18..
Using the update.sh script i thought that it would check what node version i am using, but instead it installed further dependencies and killed my service :D
Now, after the update finally went throught, I'm having trouble starting the service because it cant find /usr/bin/node ? I guess thats due to the installation with nvm ?

**Comment by lux73** [comment]
correct...  thats not the correct way for upgrading

i am using this Way for my Debian based System: https://phoenixnap.com/kb/debian-install-nodejs - Method 2

**Comment by its-Zeke** [comment]
I added a symlink now as described here:
![image](https://github.com/user-attachments/assets/eabcb289-2455-4b00-9220-e3a12fb180bd)

Seems to work . Service started, GUI is finally accessable.

Lot of trouble just to add a new zigbee device :)

**Comment by lux73** [comment]
i don't know if these Hack is working in future Updates ^^

**Comment by its-Zeke** [comment]
Alright, the Pi just died again.. gonna check that
