### ISSUE TITLE
MüllerLicht Garden light

### ISSUE THREAD

**Issue by ericroessner** [Koenkk/zigbee2mqtt#23725]
### Link

https://hey-tint.de/products/tint-outdoor-led-gartenspots-flores-gen2-white-color-3er-set

### Database entry

"id":60,"type":"Router","ieeeAddr":"0xa4c13800aa411b54","nwkAddr":13715,"manufId":4635,"manufName":"MLI","powerSource":"Mains (single phase)","modelId":"Garden light","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096,4111,65376],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"Garden light","manufacturerName":"MLI","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDGARD401"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":555}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"swBuildId":"MDGARD401","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1724511839638}

### Comments

I am stuck in configuring this in Zigbee2MQTT. Lights worked in ZHA

### External definition

```shell
const {identify, light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['Garden light'],
    model: 'Garden light',
    vendor: 'MLI',
    description: 'Automatically generated definition',
    extend: [identify(), light({"colorTemp":{"range":[153,555]},"color":{"modes":["xy","hs"],"enhancedHue":true}})],
    meta: {},
};

module.exports = definition;
```

**Comment by Koenkk** [comment]
Does it work with this external definition? (can you control it through the z2m frontend exposes tab?)
