### ISSUE TITLE
Wrong model detection for watervalve Giex GX02 ; _TZE200_7ytb3h8u

### ISSUE THREAD

**Issue by Peppe21** [Koenkk/zigbee2mqtt#23732]
### What happened?

following firmware update of Tuya watervalve Giex GX02, it result in a new manufacturer ID  : _TZE200_7ytb3h8u
reported model in z2m is now incorrect as it shows : https://www.zigbee2mqtt.io/devices/QT06_2.html

### What did you expect to happen?

this device should be reported as GX02 Model instead :
https://www.zigbee2mqtt.io/devices/GX02.html

by checking : 
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/giex.ts

line 88 : whiteLabel: [tuya.whitelabel('GiEX', 'GX02', 'Water valve', ['_TZE204_7ytb3h8u', '_TZE284_7ytb3h8u'])]
looks missing a reference to manufacturer ID  : _TZE200_7ytb3h8u

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

EmberZNet 7.4.3

### Adapter

Dongle-E

### Setup

containerized

**Comment by mrmaximas** [comment]
How about publish database.db entry for this device?
