### ISSUE TITLE
[Feature request]: OWON PC321 - Power factor history graph

### ISSUE THREAD

**Issue by rommess** [Koenkk/zigbee2mqtt#23741]
### Is your feature request related to a problem? Please describe

It's not a problem, but improvement. 
I'd like to change the default statistics for OWON Meter Power factor l1 bar graph.
value can be between -1 to 1.

### Describe the solution you'd like

I'll like to be in line graph to be more "readable"

### Describe alternatives you've considered

i don't know in wich .yaml it can be changed.

### Additional context

![image](https://github.com/user-attachments/assets/0ec50b0a-665c-40e7-9139-1e4f87707136)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by rommess** [comment]
Beauty, Thank you very much.
