### ISSUE TITLE
TRADFRI  doesnt work, get error spinlock: flase

### ISSUE THREAD

**Issue by mpuff** [Koenkk/zigbee2mqtt#238]
hello,

i have a problem with a TRADFRI  gu10 bulb, i get the following error message when i turn off and on the bulb by a wall switch:
`Aug 01 17:12:30 zigbee2mqttpi npm[418]: spinlock: false []
Aug 01 17:12:30 zigbee2mqttpi npm[418]: device already in network
`

i also cant turn on and off the TRADFRI  by mqtt, i send the right code, but nothing happens.
i only get the following log entry:
`Aug 01 17:23:15 zigbee2mqttpi npm[418]: 2018-8-1 17:23:15 INFO Zigbee publish to '0x90fd9ffffe71aa3b', genOnOff - off - {} - null
Aug 01 17:23:15 zigbee2mqttpi npm[418]: 2018-8-1 17:23:15 INFO MQTT publish, topic: 'zigbee2mqtt/0x90fd9ffffe71aa3b', payload: '{"state":"OFF"}'
`

does someone has the same problem?

**Comment by Koenkk** [comment]
The spinlock false is not an error. 

Does the turning on/off work right after joining?

**Comment by mpuff** [comment]
it it normal that the bulb tries every time to join when i turn it on with the wall switch?
the buld does nothing when i try to turn it on or off.
i also doesn't get any status messages in which state the bulb is.
i have tried to delete it and rejoin, but this also doesnt help.
i have installed the first version of the zigbee2mqtt

**Comment by Koenkk** [comment]
@mpuff can you provide your whole log?

@kaelsaes could your first [remove](https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttbridgeconfigremove) and than repair?

**Comment by mpuff** [comment]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/2260690/log.txt)
these are my logs from the last days.

**Comment by jakolars** [comment]
I have a simular problem where my TRÅDFRI bulb periodically stops responding to commands.  This seems to happen more and more as the bridge has been online for longer and longer. Sometimes a restart\reboot helps, but after some time it starts happening again.
Here are a some logs from posting a command:
````
`2018-8-7 09:54:40 DEBUG Recieved mqtt message on topic 'zigbee2mqtt/BCLight/set' with data '{"state":"ON"}'
2018-8-7 09:54:40 INFO Zigbee publish to '0x000b57fffe441b7d', genOnOff - on - {} - null
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 17 +26s
  cc-znp:SREQ --> AF:dataRequest, { dstaddr: 4589, destendpoint: 1, srcendpoint: 1, clusterid: 6, transid: 17, options: 48, radius: 30, len: 3, data: <Buffer 01 11 01> } +2ms
  serialport write 18 bytes of data +2ms
  cc-znp:SRSP <-- AF:dataRequest, { status: 0 } +19ms
  zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0 +1ms
  cc-znp:AREQ <-- AF:dataConfirm, { status: 233, endpoint: 1, transid: 17 } +505ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: dataConfirm, msg: [object Object] +1ms
  zigbee-shepherd:msgHdlr IND <-- AF:dataConfirm, transId: 17 +1ms
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 18 +497ms
  cc-znp:SREQ --> AF:dataRequest, { dstaddr: 4589, destendpoint: 1, srcendpoint: 1, clusterid: 6, transid: 18, options: 48, radius: 30, len: 5, data: <Buffer 00 12 00 00 00> } +3ms
  serialport write 20 bytes of data +4ms
  cc-znp:SRSP <-- AF:dataRequest, { status: 0 } +15ms
  zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0 +2ms
  cc-znp:AREQ <-- AF:dataConfirm, { status: 233, endpoint: 1, transid: 18 } +45ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: dataConfirm, msg: [object Object] +2ms
  zigbee-shepherd:msgHdlr IND <-- AF:dataConfirm, transId: 18 +2ms
```

**Comment by Koenkk** [comment]
@mpuff I see you are using an old version of zigbee2mqtt.

```
2018-08-01T12:41:36.830Z - info: Starting zigbee2mqtt version 0.0.0 (commit #2ba2864)
```

Before further investigation, can you update to the latest zigbee2mqtt and make sure your are running the latest CC2531 firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531/bin

**Comment by mpuff** [comment]
my tradfri bulb was broken, i have changed it and now it works, i am also on the latest version of zigbee2mqtt
