### ISSUE TITLE
Issue in a fresh installation

### ISSUE THREAD

**Issue by adrianbeniel** [Koenkk/zigbee2mqtt#2382]
I am trying to do a new installation following the steps indicated in the following link: https://www.zigbee2mqtt.io/information/virtual_environment.html

When the "npm install" is executed, always fails.

The error: https://pastebin.com/nsevitgr

I'm trying to install in a Raspberry Pi 3B+ with Raspbian.

**Comment by jul3925** [comment]
Hey, I've you tried with "sudo npm install" ?
