### ISSUE TITLE
OTA Update LEDVANCE Outdoor Adapter Plug

### ISSUE THREAD

**Issue by pille89** [Koenkk/zigbee2mqtt#23828]
### What happened?

I am receiving an update for my LEDVANCE outdoor adapter plug model 4058075729322. Unfortunately, I cannot install the update via z2m. I get the error message: ‘z2m: Update of “ZS: Brunnen” failed (Size mismatch)’ 

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20240316

### Adapter

SMLIGHT SLZB-06P7

### Setup

Add-On in homeassistant

### Debug log

[log.log](https://github.com/user-attachments/files/16849133/log.log)

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/22687
