### ISSUE TITLE
[New device support]: Philips Hue Datura

### ISSUE THREAD

**Issue by coendaar** [Koenkk/zigbee2mqtt#23831]
### Link

https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-datura-plafondlamp--klein/8720169277618

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0x001788010e19a22f","nwkAddr":6971,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003736201_01","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"swBuildId":"1.116.5","zclVersion":8}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":29162,"currentY":26654,"colorTemperature":346}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.116.5","zclVersion":8,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1725369856326} {"id":31,"type":"Router","ieeeAddr":"0x001788010e19a21c","nwkAddr":13942,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003736201_02","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,64515,768,64513,64516],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"hwVersion":0,"zclVersion":8}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":29162,"currentY":26654,"enhancedCurrentHue":8594,"currentSaturation":121,"colorTemperature":346}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":254}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":8,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1725369687009}

### Comments

This devices contains 2 separate lights. One downlight, one uplight. And shows up as 2 zigbee devices (_01 and _02)
There also exists a datura in a different size, I don't know if that one has the same IDs.

The auto generated External convertor works fine. I've changed the name and  I've added both lights to the same id. Similar to how it's implementend for the Hue Ensis.

Need some help with:
- add to docs
- create transparant background for image (already sized at 512x512)
- add converter to repository
<img width="256" alt="datura" src="https://github.com/user-attachments/assets/b3c1272d-62ec-4bcf-b2b9-c407c0706f25">

### External definition

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['929003736201_01','929003736201_02'],
    model: '929003736201',
    vendor: 'Philips',
    description: 'Hue Datura',
    extend: [philipsLight({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"],"enhancedHue":true}})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Everything seems to work

**Comment by moritzps** [comment]
Hey! On this: 

> This devices contains 2 separate lights. One downlight, one uplight. And shows up as 2 zigbee devices (_01 and _02)

I have reset the Datura multiple times and paired again with Z2M but only one device shows up. It's impossible to control the uplight. Do you have any ideas how to ensure the second device shows up?
