### ISSUE TITLE
IKEA Lamp on/off not working in 1.40.0

### ISSUE THREAD

**Issue by kamaradclimber** [Koenkk/zigbee2mqtt#23863]
### What happened?

I switch off/on an IKEA light bulb. Light does not switch.

An error appears on zigbee2mqtt:
```
z2m: Publish 'set' 'state' to 'Lampe Francois' failed: 'TypeError: Invalid Version: 1.1.1.0-5.7.2.0'
```

![image](https://github.com/user-attachments/assets/3d7dffa6-1531-4f1d-aa7a-571ecff236a7)

![image](https://github.com/user-attachments/assets/ba08531e-6b10-4861-8f36-7745778c1bca)

It used to work in 1.35.1 (I've checked: it works up to 1.39.0).

### What did you expect to happen?

I expected the light to switch on/off

### How to reproduce it (minimal and precise)

- go to Exposes tab
- click off (if the light is on)

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

0x26680700

### Adapter

ConBee2/RaspBee2

### Setup

Z2M in docker, on x86-64

### Debug log

error 2024-09-05 19:00:32z2m: Publish 'set' 'state' to 'Lampe Francois' failed: 'TypeError: Invalid Version: 1.1.1.0-5.7.2.0'
info 2024-09-05 19:00:32z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Lampe Francois' failed: 'TypeError: Invalid Version: 1.1.1.0-5.7.2.0'","meta":{"friendly_name":"Lampe Francois"},"type":"zigbee_publish_error"}'

**Comment by Koenkk** [comment]
Fixed! (a hotfix release will be available in the coming days)

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by kamaradclimber** [comment]
Great news, thanks a lot !
