### ISSUE TITLE
Zigbee devices report power even during power outage

### ISSUE THREAD

**Issue by strybushnyi** [Koenkk/zigbee2mqtt#23860]
### What happened?

During the power outages (which we have here in Ukraine a lot) zigbee devices still report power, current and voltage. 
These are not included into overall energy usage count. However, during 4-6 hours outages zigbee devices show last reported values. 

### What did you expect to happen?

If device is not available and/or does not report any updates during some time, show power/current/voltage values as NULL or N/A or 0 (which is not correct i think) 

A lot of users may use this for determining whether the power is present from the city grid, however, since the values are stuck, it is not possible

### How to reproduce it (minimal and precise)

Plug off any plug/socket/energy monitor and watch 
![voltage](https://github.com/user-attachments/assets/ff58c0b2-8cea-4f9d-87fa-ab49ba41d826)

### Zigbee2MQTT version

1.40.0-1

### Adapter firmware version

20240315

### Adapter

SLZB-06

### Setup

HASS OS

**Comment by Ramotny** [comment]
This is general issue that also concerns battery powered devices - if they switch off Z2M continuously reports last status/data instead of "unreachable". I've noticed it on many units like 3phase monitor, humidty sensors and so on.
Very annoying.
