### ISSUE TITLE
SmartThings Multi-Sensor (3321-S) not reporting contact.

### ISSUE THREAD

**Issue by jonnyrider** [Koenkk/zigbee2mqtt#2386]
I know that the 3321-S is supported, and it is reporting link quality and temperature correctly, but the actual contact status is not reported.

The only thing in the add-on log is:
zigbee2mqtt:info  2019-11-22T09:08:17: MQTT publish: topic 'zigbee2mqtt/0x000d6f000bbaa7cc', payload '{"temperature":22.25,"linkquality":68}'

And an error appears in the developer log:
No matching payload found for entity: 0x000d6f000bbaa7cc_contact with state_topic: zigbee2mqtt/0x000d6f000bbaa7cc

## Debug Info
zigbee2mqtt version: 1.7.1
CC2531 firmware version: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
Device: 0x000d6f000bbaa7cc (0x000d6f000bbaa7cc): 3321-S - SmartThings Multi Sensor (2015 model) (EndDevice)

Thanks

**Comment by Koenkk** [comment]
Can you share `database.db`?

**Comment by jonnyrider** [comment]
[database.txt](https://github.com/Koenkk/zigbee2mqtt/files/3880283/database.txt)

**Comment by Koenkk** [comment]
Interviewing failed it seems. Can you try repairing the device when running with `DEBUG=* npm start`?

**Comment by jonnyrider** [comment]
I'm using hassio. If I turn on debug logging and re-pair will that give you
the same result?

**Comment by Koenkk** [comment]
For hassio  switch to edge and set `zigbee_herdsman_debug: true` in the config.

**Comment by bassicrob** [comment]
I'm having similar issue with standalone install of Zigbee2mqtt on separate Pi from Hassio.  Stopped working when I upgraded to 1.6.1-dev and still not reporting contact on 1.7.1. All other attributes report fine.

**Comment by jonnyrider** [comment]
[debug.txt](https://github.com/Koenkk/zigbee2mqtt/files/3885348/debug.txt)

Thanks

**Comment by Koenkk** [comment]
Can you check if this is fixed in the latest dev?

**Comment by jonnyrider** [comment]
Yes, it is. I had to remove and re-link it, but it works perfectly now.

Thanks very much!
