### ISSUE TITLE
Replace CC2531  with Ikea Tradfri Gateway

### ISSUE THREAD

**Issue by Jeoffreybauvin** [Koenkk/zigbee2mqtt#2388]
Hi there,

Simple question, did anyone tried to use the Ikea Tradfri Gateway instead of CC2531  ? Is it hackable, or something ?

I did some research, but no luck.

Thanks,

**Comment by 877dev** [comment]
https://www.youtube.com/watch?v=wS8Vj0ba4ic

**Comment by Jeoffreybauvin** [comment]
@877dev Thanks. I saw that, but with my understanding, you can use only Ikea bulbs, right ? I want to be able to  add some Xiaomi (Aquara) components too.

**Comment by 877dev** [comment]
I’m not sure to be honest. I’m curious why you want to use the gateway over a sniffer?
