### ISSUE TITLE
Flashing the CC2531 via an STM32F1xx board ("Blue Pill")

### ISSUE THREAD

**Issue by hwhw** [Koenkk/zigbee2mqtt#239]
Hi,

as I just couldn't wait for the cc debugger (and the adapter cable) to follow the CC2531 stick that arrived after just 8 days from China, I implemented the CC debug protocol on an STM32F1xx ("Blue Pill") board. It will show as an USB serial device that will read Intel hexfile encoded firmware files directly.
It's far from polished and so I'm hesitating to create a Wiki page at this moment. However, it worked fine to flash my CC2531, so I'm sharing this via this issue. I will update this issue if the software gets more polished.
More adventurous natures may just go on and use it. Please provide feedback if it worked for you, thanks! Also, feel free to fork, edit, augment, send PRs.

https://github.com/hwhw/stm32f1-ccprog

**Comment by kirovilya** [comment]
Great work! You need to add it to the wiki

**Comment by hwhw** [comment]
Thanks for the encouragement. I hope that I'll be able to write more documentation on the usage and conception of this software next weekend, afterwards I'll add it to the Wiki and will close this issue.

**Comment by metrorik** [comment]
Hello. Thanks for the work you've done.  Does this method only work for cc2531?
I tried to flash cc2530 through the STM32F1xx board. There is a problem after startup flash.sh. 
flash.log:
 :020000040000FA
flashing segment starting at 00000
:10000000021305022003FFFFFFFFFF02200BFFFF8B
unknown chip ID A5, aborting.
