### ISSUE TITLE
[New device support]: QS-Zigbee-ECC02

### ISSUE THREAD

**Issue by marco-bertani** [Koenkk/zigbee2mqtt#23902]
### Link

https://it.aliexpress.com/item/1005005300005871.html

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0xa4c1385f9c5cbf0a","nwkAddr":56518,"manufId":4417,"manufName":"_TZ3210_ol1uhvza","powerSource":"Mains (single phase)","modelId":"TS130F","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":514,"inClusterList":[4,5,258,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS130F","manufacturerName":"_TZ3210_ol1uhvza","powerSource":1,"zclVersion":3,"appVersion":129,"stackVersion":0,"hwVersion":1,"dateCode":""}},"closuresWindowCovering":{"attributes":{"32768":0,"tuyaMovingState":1,"currentPositionLiftPercentage":4,"moesCalibrationTime":310,"tuyaMotorReversal":0,"tuyaCalibration":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":129,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1725789145868}

### Zigbee2MQTT version

1.40.1

### Comments

I purchased this "no brand" curtain switch from AliExpress. When paired with Z2M it is detected as QS-Zigbee-C03. I works great, but when using the same device from the SmartLife/Tuya app, I get to change the switch type.
When I reset the device to pair with Z2M this option is reset.

![image](https://github.com/user-attachments/assets/f94804a7-c687-46bf-af68-692397e9fa9e)

Actually I don't even think this option is exclusive of QS-Zigbee-ECC02, but might be available also on QS-Zigbee-C03.
I tried to create a new definition to expose this option to Z2M, but I am struggling. The definition I created is taken from the original QS-Zigbee-C03 and changed adding the new Tuya endpoint.

When restarting Z2M my devices still show up as QS-Zigbee-C03 and not QS-Zigbee-ECC02; what am I doing wrong?🙁

### External definition

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [
        {modelID: 'TS130F', manufacturerName: '_TZ3000_zirycpws'},
        {modelID: 'TS130F', manufacturerName: '_TZ3210_ol1uhvza'},
    ],
    model: 'QS-Zigbee-ECC02',
    vendor: 'Lonsonho',
    description: 'Curtain/blind motor controller custom',
    fromZigbee: [tuya.fz.datapoints, fz.cover_position_tilt, fz.tuya_cover_options],
    toZigbee: [tuya.tz.datapoints, tz.cover_position_tilt, tz.tuya_cover_calibration, tz.tuya_cover_reversal],
    meta: {
        coverInverted: true,
        tuyaDatapoints: [
            [12, 'switch_type', tuya.valueConverterBasic.lookup({button: 0, flip: 1})],
        ],
    },
    exposes: [
        e.cover_position(),
        e.enum('moving', ea.STATE, ['UP', 'STOP', 'DOWN']),
        e.binary('calibration', ea.ALL, 'ON', 'OFF'),
        e.binary('motor_reversal', ea.ALL, 'ON', 'OFF'),
        e.numeric('calibration_time', ea.STATE).withUnit('s').withDescription('Calibration time'),
        e.switch_type(['button', 'flip']),
    ],
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Can't get the devices to show up as the device I configured

**Comment by Niedzwiedzw** [comment]
hey, I just got this device - have you managed to add it?
