### ISSUE TITLE
_TZE204_7gclukjs sensitivity setting error.

### ISSUE THREAD

**Issue by RyeongHoKim** [Koenkk/zigbee2mqtt#23906]
### What happened?

TS0601
_TZE204_7gclukjs

Move sensitivity
Presence sensitivity
Setting Error

### What did you expect to happen?

The presence sensitivity and the move sensitivity value may be set to a minimum of 1 and a maximum of 10.
The value should be set when set in the Exposes of the product.

### How to reproduce it (minimal and precise)

The value should be set when set in the Exposes of the product.
If you set the value to 10 and check it in the state window, it is normally set to 10.
However, after a while, the setting value changes to 1.
After a little more time, it changes to 0.1
It will eventually change to zero.

### Zigbee2MQTT version

1.40.1-1

### Adapter firmware version

 20221226

### Adapter

 zStack3x0

### Setup

Intel N100 HAOS Addon

**Comment by mrbean27123** [comment]
Same thing, and at that sensitivity the sensor started triggering on its own all the time
