### ISSUE TITLE
_TZ3000_ctbafvhm backlight mode not working

### ISSUE THREAD

**Issue by ctechmat** [Koenkk/zigbee2mqtt#23919]
### What happened?

When we click on the switch button of Backlight mode, the blue light doesn't turn off.
Link to that device : https://www.bseed.com/collections/zigbee-series/products/bseed-zigbee-shutter-switch-smart-wall-touch-switch

### How to reproduce it (minimal and precise)

Click on the switch button of Backlight mode.

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E USB Zigbee 3.0 USB Dongle plus

### Setup

Home Assistant Add-on

**Comment by ThorstenDtk** [comment]
According to https://www.bseed.com/de/products/bseed-new-zigbeedouble-touch-light-dimmer-smart-switch:

Q: Can your smart switch turn off the backlight?
A: At present, the switch of ZigBee series cannot turn off the backlight

I bought two of these devices - on one of them I can switch off the backlight, on the other one it doesn't work. So the statement above is (no longer?) true. 

Maybe both have different firmware versions. Does any of you know how to check? The firmware version is not shown in Z2M.
