### ISSUE TITLE
Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0"

### ISSUE THREAD

**Issue by sylarm27** [Koenkk/zigbee2mqtt#23921]
### What happened?

My zigbee2mqtt lxc container is running with ember firmware since 2 months, since yesterday I start receiving there errors:
"2024-09-09 12:03:42zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0"."
I receive one of this by minute

The only thing that happened was a reboot of the server.
My network have 58 devices mainly routers.

### What did you expect to happen?

no error

### How to reproduce it (minimal and precise)

is always Happening , all most every minute

### Zigbee2MQTT version

 1.40.0 commit: 6fa1dabe

### Adapter firmware version

7.4.3 [GA]

### Adapter

ZBDongle-E

### Setup

LXC on top of proxmox

### Debug log

info 2024-09-09 12:03:42zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0".
info 2024-09-09 12:06:20zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0".
info 2024-09-09 12:07:04zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0".
info 2024-09-09 12:09:06zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0".
info 2024-09-09 12:11:59zh:ember:ezsp: Received network/route error ROUTE_ERROR_ADDRESS_CONFLICT for "0".

**Comment by sylarm27** [comment]
Zigbee sniffing is maybe a way, I know how to sniff wifi (wireshark) but not zigbee. 
But the strange thing is after open this issue, I'm almost at 24h without that error. 
Just keep receiving "ROUTE_ERROR_MANY_TO_ONE_ROUTE_FAILURE...." but I think that is other topic

**Comment by Nerivec** [comment]
Since it seems to have disappeared, looks like something didn't sync up right after the restart; probably a device that was temporarily misbehaving. If it happens again, see about sniffing the traffic when it does (assuming you have another adapter handy).

About sniffing: https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html

**Comment by sylarm27** [comment]
Thank you
