### ISSUE TITLE
Tuya Mini Smart Switch WHD02: Switch Type wrong

### ISSUE THREAD

**Issue by quensen** [Koenkk/zigbee2mqtt#23948]
### What happened?

I am using Mini Smart Switch WHD02 ([link to docu](https://www.zigbee2mqtt.io/devices/WHD02.html#tuya-whd02))
It has the Switch Type property (`switch_type`) with values `toggle`, `state`, and `momentary`.
The switch's behaviour does not match these switch type value names from my point of view.

### What did you expect to happen?

When `switch_type` is `toggle`, I expect the switch to turn on when it is off and vice versa when the external switch is gated.
Instead, it _inverts_ the `state` once when the external switch is gated depending from the initial state.
This value should have a new name.

When `switch_type` is `state`, I expect the switch to match the current state of the input, off when the external switch is open, on when the external switch is gated.
Instead, it _inverts_ the `state` when the external switch is gated independant from the initial state.
This value should have a new name.

When `switch_type` is `momentary`, I expect the switch to turn on when the external switch is gated and off, when it's not.
Instead, it really toggles the `state` once the external switch is gated.
_This_ should be `toggle`.

### How to reproduce it (minimal and precise)

Wire the item (Lin and N) and attach an external switch to S1 and S2.
Try the 3 values for Switch Type and press the external switch once, keep it press, let go for each Switch Type.

### Zigbee2MQTT version

1.40.1 commit: 403d3c0

### Adapter firmware version

7.4.3 [GA]

### Adapter

Sonoff ZBDongle-E (V2 model, EFR32MG21)

### Setup

Plain on Raspberry with openHABian Linux 6.6.50-v8-16k+ with openHAB 4.2.1

**Comment by Gecko3600** [comment]
I have the same problem. switch type momentary does not work and does not send state changes.
The power is only interrupted when the switch is pressed several times...
