### ISSUE TITLE
[New device support]: linptech K9Z(TY) 2404019-0175

### ISSUE THREAD

**Issue by ovsch6** [Koenkk/zigbee2mqtt#23958]
### Link

https://aliexpress.ru/item/1005005469765581.html?spm=a2g2w.orderdetail.0.0.37fc4aa63lENeH&sku_id=12000033211493629

### Database entry

payload '{"data":{"id":"0x00000000c5155ba0","source":"\n\nconst definition = {\n zigbeeModel: ['GreenPower_2'],\n model: 'GreenPower_2',\n vendor: '',\n description: 'Automatically generated definition',\n extend: [],\n meta: {},\n};\n\nmodule.exports = definition;"},"status":"ok","transaction":"bxiem-3"}'

### Zigbee2MQTT version

1.40.1

### Comments

onst definition = {
    zigbeeModel: ['GreenPower_2'],
    model: 'GreenPower_2',
    vendor: '',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;

### External definition

```shell
2024-09-13 21:17:22z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"2gvc4-1"}'
Info 2024-09-13 21:17:24zh:controller:greenpower: Received commissioning from '35824'
Info 2024-09-13 21:17:25z2m: Device '0x000000002a818bf0' joined
Info 2024-09-13 21:17:25z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000000002a818bf0"},"type":"device_connected"}'
Info 2024-09-13 21:17:25z2m: Successfully interviewed '0x000000002a818bf0', device has successfully been paired
Warning 2024-09-13 21:17:25z2m: Device '0x000000002a818bf0' with Zigbee model 'GreenPower_2' and manufacturer name 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2024-09-13 21:17:25z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x000000002a818bf0","supported":false},"type":"pairing"}'
Info 2024-09-13 21:17:25z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000000002a818bf0","ieee_address":"0x000000002a818bf0"},"type":"device_joined"}'
Info 2024-09-13 21:17:25z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x000000002a818bf0","ieee_address":"0x000000002a818bf0","status":"successful","supported":null},"type":"device_interview"}'
```

### What does/doesn't work with the external definition?

DONT SUPPORT)

**Comment by Koenkk** [comment]
Do you see anything in the debug log when triggering actions?


See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.

**Comment by ovsch6** [comment]
Info 2024-09-19 19:53:49zh:controller:greenpower: Received commissioning from '20510'
Info 2024-09-19 19:53:49z2m: Device '0x00000000ca8e501e' joined
Info 2024-09-19 19:53:49z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x00000000ca8e501e"},"type":"device_connected"}'
Info 2024-09-19 19:53:49z2m: Successfully interviewed '0x00000000ca8e501e', device has successfully been paired
Warning 2024-09-19 19:53:49z2m: Device '0x00000000ca8e501e' with Zigbee model 'GreenPower_2' and manufacturer name 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2024-09-19 19:53:49z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x00000000ca8e501e","supported":false},"type":"pairing"}'
Info 2024-09-19 19:53:49z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00000000ca8e501e","ieee_address":"0x00000000ca8e501e"},"type":"device_joined"}'
Info 2024-09-19 19:53:49z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x00000000ca8e501e","ieee_address":"0x00000000ca8e501e","status":"successful","supported":null},"type":"device_interview"}'
Info 2024-09-19 19:53:54z2m: Successfully changed options
Info 2024-09-19 19:53:54z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"50fzc-4"}'
Info 2024-09-19 19:54:07z2m: Successfully changed options
Info 2024-09-19 19:54:08z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"50fzc-5"}'
Info 2024-09-19 19:54:22zh:controller:greenpower: Received commissioning from '278'
Info 2024-09-19 19:54:23z2m: Device '0x000000008dc90116' joined
Info 2024-09-19 19:54:23z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000000008dc90116"},"type":"device_connected"}'
Info 2024-09-19 19:54:23z2m: Successfully interviewed '0x000000008dc90116', device has successfully been paired
Warning 2024-09-19 19:54:23z2m: Device '0x000000008dc90116' with Zigbee model 'GreenPower_2' and manufacturer name 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html
Info 2024-09-19 19:54:23z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x000000008dc90116","supported":false},"type":"pairing"}'
Info 2024-09-19 19:54:23z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000000008dc90116","ieee_address":"0x000000008dc90116"},"type":"device_joined"}'
Info 2024-09-19 19:54:23z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x000000008dc90116","ieee_address":"0x000000008dc90116","status":"successful","supported":null},"type":"device_interview"}'
Info 2024-09-19 19:54:32z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/репитер', payload '{"linkquality":90}'

**Comment by Koenkk** [comment]
If it keeps sending the commissioning command (`Received commissioning from`) you probably need to confirm the channel by pressing a certain key combination on the device, consult the manual for this.

**Comment by choovick** [comment]
@ovsch6 did u figured it out. its not channel for me, 0 = channel 11 for me... just getting:

z2m: Device '0x0000000094c2c234' with Zigbee model 'GreenPower_2' and manufacturer name 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html

device is added, but without any properties

**Comment by andrazek** [comment]
Same here. Is there a hope to be supported by z2m?

**Comment by socram70** [comment]
You can get this switch to be added as supported by following [these instructions](https://github.com/Koenkk/zigbee2mqtt/issues/27182#issuecomment-2821180745). However, it will only work whilst in pairing mode (at least with my SLZB-06 (without M).
