### ISSUE TITLE
[New device support]:  ROB_200-004-1 (new HW revision of ROB_200-004-1-0)

### ISSUE THREAD

**Issue by william-sy** [Koenkk/zigbee2mqtt#23965]
### Link

https://www.robbshop.nl/robb-smarrt-zigbee-led-dimmer-voor-traditionele-schakelaar

### Database entry

{"id":56,"type":"Router","ieeeAddr":"0xf4b3b1fffe36ca86","nwkAddr":8438,"manufId":4644,"manufName":"ROBB smarrt","powerSource":"Mains (single phase)","modelId":"ROB_200-004-1","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"modelId":"ROB_200-004-1"}},"genLevelCtrl":{"attributes":{"currentLevel":36}},"genOta":{"attributes":{"currentFileVersion":57}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.9.2_r57","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1726319538523}

### Zigbee2MQTT version

1.40.1

### Comments

Its the same device as https://www.zigbee2mqtt.io/devices/ROB_200-004-0.html, but a new hardware revision it seems. 
Everything works once paired, just unsupported.

### External definition
Hopefully this is correct: 
```shell
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');
// Add the lines below
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const utils = require('zigbee-herdsman-converters/lib/utils');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['ROB_200-004-1'],
    model: 'ROB_200-004-1',
    vendor: 'ROBB smarrt',
    description: 'ZigBee AC phase-cut dimmer',
    meta: {},
    extend: [light({configureReporting: true})],
};
module.exports = definition;
```
### What does/doesn't work with the external definition?

Everything seems to work

**Comment by Koenkk** [comment]
Added, thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `ROB_200-004-1.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
