### ISSUE TITLE
Zigbee2mqtt not publishing to homeassistant topic even though homeassistant set to true in the config

### ISSUE THREAD

**Issue by Eleison667** [Koenkk/zigbee2mqtt#23985]
### What happened?

On the latest version of zigbee2mqtt I am not seeing entities updated in homeassistant. 

### What did you expect to happen?

I expected zigbee2mqtt to keep publishing to the homeassistant topic on the broker

### How to reproduce it (minimal and precise)

Updated to 1.40.1
while troubleshooting i did clear my database after which i saw one message to the topic homeassistant, after restoring my database it didnt work anymore. But I don't understand how those are related
using the config below:

```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.179.12'
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
devices:
  '0x90fd9ffffe888a64':
    friendly_name: studybutton
  '0x90fd9ffffe6fa8a5':
    friendly_name: '0x90fd9ffffe6fa8a5'
  '0x000b57fffe13c943':
    friendly_name: vision
  '0x000d6ffffe46f610':
    friendly_name: '0x000d6ffffe46f610'
  '0x14b457fffe4e195a':
    friendly_name: '0x14b457fffe4e195a'
  '0x000d6ffffe151cd5':
    friendly_name: '0x000d6ffffe151cd5'
  '0x14b457fffe34c0f3':
    friendly_name: '0x14b457fffe34c0f3'
  '0x00124b001eb0ac5f':
    friendly_name: 10vDimmer
  '0xec1bbdfffe992011':
    friendly_name: '0xec1bbdfffe992011'
  '0x00158d000464c6c9':
    friendly_name: bathroomsensor
  '0x00158d00046585f5':
    friendly_name: kitchensensor
  '0x086bd7fffe81ec30':
    friendly_name: '0x086bd7fffe81ec30'
  '0x000b57fffee64b07':
    friendly_name: poulsen
  '0x90fd9ffffe516219':
    friendly_name: colour
  '0x90fd9ffffe9c400e':
    friendly_name: bedroombutton
  '0x000b57fffed2d904':
    friendly_name: livingroombutton
  '0x000d6ffffed64932':
    friendly_name: switch2
  '0x000b57fffec0314e':
    friendly_name: studylamp
  '0x04cf8cdf3c7b2016':
    friendly_name: Xiaomi Socket
  '0x00124b001f586586':
    friendly_name: leddimmer
  '0x14b457fffe7e389b':
    friendly_name: '0x14b457fffe7e389b'
  '0x60a423fffeab47cf':
    friendly_name: TVR1
  '0x90fd9ffffed76b4c':
    friendly_name: floalt
  '0xb4e3f9fffea0db23':

```
### Zigbee2MQTT version

1.40.1

### Adapter firmware version

20240710

### Adapter

aliexpress sonoff knockoff

### Setup

Pi

### Debug log

[log.log](https://github.com/user-attachments/files/17012776/log.log)

**Comment by Eleison667** [comment]
another round of trial and error mostly error yielded some desired results!
zigbee2mqtt/bridge/request/options with payload {"options": {"homeassistant": true}} instead. got z2m publishing on the homeassistant topic again. Completely in the dark why the config didn't work.

**Comment by Eleison667** [comment]
Decided to reinstall homeassistant in docker so i could get the latest version and now its working again. Still in the dark why the debug setting didnt work from the config file but oh well.

**Comment by Eleison667** [comment]
Decided to reinstall homeassistant in docker so i could get the latest version and now its working again. Still in the dark why the debug setting didnt work from the config file but oh well.

**Comment by rubin110** [comment]
@Eleison667 I'm hitting a similar issue. Occasionally (too often during the day), MQTT will push new topic updates that is received from Z2M over to HA, however HA never shows them received in its logs. This lasts anywhere between 20-60 seconds. Sometimes the updates are dropped, other times they come rolling in after the delay. The annoying thing is updates from other non-Z2M devices come right through MQTT and HA gets them fine while the Z2M get stuck whenever that symptom is appearing.

Did you ever hit a regression of your issue again? Thanks!

**Comment by Eleison667** [comment]
I'm not sure, I noticed yesterday some devices were gone and updated zigbee2mqtt - now its not working at all and I haven't figured out what is going wrong now. I see nothing in the logs of homeassistant - which is communicating to mqtt and I can publish directly to devices which were still visible before I updated and control them that way. But all devices are unavailable in HA.

**Comment by Eleison667** [comment]
No sorry my problem was different. somehow my database got reset and all my devices have a new ID and need to be accessed via friendly name in home assistant. After fixing that I got most of it working again. except a few devices which are no longer connected but I guess thats just IKEA glitchyness x)
