### ISSUE TITLE
Giving each adevice a (friendly) name

### ISSUE THREAD

**Issue by ayavilevich** [Koenkk/zigbee2mqtt#24]
Great work.

I am using mqtt discovery with home-assistant and I see that each device gets identified by its device id.

https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-Home-Assistant mentions "friendly name" for the mqtt topic. So I wonder, is there a way to give more meaningful names to the devices?

**Comment by ciotlosm** [comment]
I guess the only place there is some detail on a bit more friendly name is: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/devices.js but then again you must make sure devices are unique so the id will need to be added as suffixed.

**Comment by ayavilevich** [comment]
Ok, nm, found it
https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge#3-optional-device-specific-configuration
