### ISSUE TITLE
Vibration Sensor Model TS0210 vendor: '_TZ3000_lzdjjfss'

### ISSUE THREAD

**Issue by Beer17HWAM** [Koenkk/zigbee2mqtt#24005]
### Link

https://nl.aliexpress.com/item/1005006286554833.html

### Database entry

{"id":18,"type":"EndDevice","ieeeAddr":"0xa4c1381d43b23081","nwkAddr":54384,"manufId":4417,"manufName":"_TZ3000_lzdjjfss","powerSource":"Battery","modelId":"TS0210","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,1280,0],"outClusterList":[25,10],"clusters":{"ssIasZone":{"attributes":{"currentZoneSensitivityLevel":0,"iasCieAddr":"0xe0798dfffebb52b8","zoneState":1}},"genBasic":{"attributes":{"stackVersion":0,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1726565988983}

### Zigbee2MQTT version

1.40.1

### Comments

It's working but the battery status is not correct:

{
    "battery_low": false,
    "last_seen": "2024-09-17T15:41:58+02:00",
    "linkquality": 236,
    "sensitivity": 0,
    "tamper": false,
    "vibration": false,
    "battery": null,
    "voltage": null
}

### External definition

```shell
const {battery, iasZoneAlarm} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0210'],
    model: 'TS0210',
    vendor: '_TZ3000_lzdjjfss',
    description: 'Automatically generated definition',
    extend: [battery(), iasZoneAlarm({"zoneType":"generic","zoneAttributes":["alarm_1","alarm_2","tamper","battery_low"]})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

It's working but the battery status is not correct:

{
    "battery_low": false,
    "last_seen": "2024-09-17T15:41:58+02:00",
    "linkquality": 236,
    "sensitivity": 0,
    "tamper": false,
    "vibration": false,
    "battery": null,
    "voltage": null
}

**Comment by Beer17HWAM** [comment]
Can you please fix this?

**Comment by GuyFromMars365** [comment]
Why is it not planned to correct battery status when the z2m website lists states this device lists batt & volage?
Reference: https://www.zigbee2mqtt.io/devices/TZ3000_lzdjjfss.html

**Comment by inigortega** [comment]
Any upgrades on getting battery status working on zha? Thanks in advance.
