### ISSUE TITLE
Z2M cannot connect to adapter

### ISSUE THREAD

**Issue by dam57950** [Koenkk/zigbee2mqtt#24010]
### What happened?

I installed HA, Mosquitto and Z2M with docker compose, at first it worked great but after leaving it alone for a few hour, Z2M frontend didn't worked anymore 

I tried restarting from scratch deploying a new stack with new configuration files but that doesn't help.
I tried using eszp instead of ember but no change

Looks like the adapter cannot be found by the Z2M instance but... it was just before and is still online at the same IP on the same network
I also tried to restart the host

Only thing I saw was the hour which is -2h in the logs, is it important?

### What did you expect to happen?

For Z2M to connect to my SLZB-06M

### How to reproduce it (minimal and precise)

Instal Z2M with adapter tcp address in the yaml file

### Zigbee2MQTT version

koenkk/zigbee2mqtt:latest

### Adapter firmware version

20240510

### Adapter

SLZB-06M

### Setup

Docker 

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /volume2/docker/homeassistant:/config
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /volume2/docker/homeassistant/mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - /volume2/docker/homeassistant/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:

### Debug log

[log-4.log](https://github.com/user-attachments/files/17035117/log-4.log)

**Comment by dam57950** [comment]
I found the problem, when tailscale is connected, z2m cannot find the coordinator, but why? I'm still searching, normally tailscale don't "disconnect" local network

**Comment by troylynch** [comment]
Following having the same problem after the update yesterday
