### ISSUE TITLE
Zigbee devices stopped responding and unable to re-pair after coordinator upgrade

### ISSUE THREAD

**Issue by EinSchwerd** [Koenkk/zigbee2mqtt#24034]
### What happened?

I used a USB ZBDongle-P as a coordinator. Since my Home Assistant server is relatively close to my WiFi AP, I upgraded to SLZB-06M to put it further away to avoid any interference and get better coverage.
After swapping the coordinators and changing the config all devices are discovered but no updates are sent to Z2M. I tried removing one device and re-pairing, but pairing failed as well. 

Z2M addon is running with the following config:
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: tcp://<IP of the coordinator>:6638
  baudrate: 115200
  adapter: ember
  rtscts: true
  disable_led: false
advanced:
  transmit_power: 20
  log_level: info
  log_namespaced_levels:
    z2m:mqtt: warning
    zhc: debug

### What did you expect to happen?

I am expecting to be able to use the devices with the coordinator after swapping coordinators or at minimum to be able to re-pair devices.expect

### Zigbee2MQTT version

1.40.1 commit: unknown

### Adapter firmware version

20240510

### Adapter

SLZB-06M with ember

### Setup

Z2M as a HA addon in a docker container on a Debian box

### Debug log

[log.log](https://github.com/user-attachments/files/17068958/log.log)

**Comment by DariuszJJ** [comment]
I will only add a comment that I did not have to pair the devices again, which seems strange without changing the IEE in the case of SLZB-06M and ember and Z2M
