### ISSUE TITLE
How to distinguish a CC2530 with CC2591 from other CC2530 variants?

### ISSUE THREAD

**Issue by hansblafoo** [Koenkk/zigbee2mqtt#2404]
Hi there,

it is not a question directly related to zigbee2mqtt (which is awesome btw!) but more regarding the supported adapters. Is there any way to distinguish a CC2530+CC2591 from other CC2530 with an external antenna? Is the CC2591 combo larger than the CC2530 or is there another hint to separate them from pictures?

Best regards
Hans

**Comment by pcb1962** [comment]
You should be able to see the 2591 chip quite clearly, if it has one, like on [this board](https://ae01.alicdn.com/kf/HTB1iSRLXtqUQKJjSZFIq6AOkFXaC/1pcs-CC2530-CC2591-ZigBee-Module-ZA2530-2591-With-PA-Remote.jpg)
