### ISSUE TITLE
All SONOFF device don’t connect

### ISSUE THREAD

**Issue by Prokopchini** [Koenkk/zigbee2mqtt#24042]
### What happened?

I reconnected all my devices to Z2M, and found that any SONOFF device does not connect to Z2M. All other devices - Moes, Tuya, Xiaomi connect without problems. Then I installed ZHA - and to ZHA all SONOFF devices connect without problems.

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

26530900

### Adapter

Conbee 3

### Setup

Add-on on HAOS

**Comment by Koenkk** [comment]
Looks like a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/23996
