### ISSUE TITLE
[New device support]: Aqara Presence sensor FP1E

### ISSUE THREAD

**Issue by brianegge** [Koenkk/zigbee2mqtt#24063]
### Link

https://www.zigbee2mqtt.io/devices/RTCZCGQ11LM.html

### Database entry

{"id":53,"type":"EndDevice","ieeeAddr":"0x54ef441000db7038","nwkAddr":52581,"manufId":4660,"manufName":"aqara","powerSource":"DC Source","modelId":"lumi.sensor_occupy.agl1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":65520,"inClusterList":[0,3,64704],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.sensor_occupy.agl1","appVersion":26,"swBuildId":""}},"manuSpecificLumi":{"attributes":{"223":{"type":"Buffer","data":[40,35,4,0,0,0,43,33,0,0,44,40,196,45,35,0,0,0,0]},"247":{"type":"Buffer","data":[3,40,28,5,33,1,0,8,33,26,1,10,33,0,0,12,32,20,16,32,1,18,32,0,101,32,0,102,32,1]},"322":0,"351":0,"352":2}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":26,"stackVersion":2,"hwVersion":1,"dateCode":"20240520","swBuildId":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1726975057339}

### Zigbee2MQTT version

 1.40.1 commit: 403d3c0

### Comments

I think the earlier version of this device is supported. I couldn't figure out how to create a diffinition for it, though I know it's been done in the zha project: https://github.com/zigpy/zha/blob/2b1368717a662bfc137625a987d7477cac7b2866/tests/data/devices/aqara-lumi-sensor-occupy-agl1.json#L5

### External definition

```shell
const definition = {
    zigbeeModel: ['lumi.sensor_occupy.agl1'],
    model: 'lumi.sensor_occupy.agl1',
    vendor: 'aqara',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

The external definition doesn't seem to find any capabilities

**Comment by marazmarci** [comment]
There's already an issue opened for this device, and there is already a (partly?) working external converter.

https://github.com/Koenkk/zigbee2mqtt/issues/23577
