### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by scootec** [Koenkk/zigbee2mqtt#2407]
Random question...

Any reason zigbee2mqtt is not published to NPM like herdsman?

Thanks! 😊

**Comment by scootec** [comment]
Let me if you want to go ahead with this, and I can do a pull request to docs with an npm installation method 👍

**Comment by Koenkk** [comment]
Good idea indeed, would be great if you could make a pr.

**Comment by X-dark** [comment]
I have tried to publish 1.11.0 on npm: https://www.npmjs.com/package/zigbee2mqtt/v/1.11.0
@Koenkk I gave you the rights.

**Comment by Koenkk** [comment]
@X-dark thanks, I assume that also some changes to the zigbee2mqtt repository are needed, could you make a PR for this?
