### ISSUE TITLE
Device already in network constantly 

### ISSUE THREAD

**Issue by paskyecijano** [Koenkk/zigbee2mqtt#241]
I see that the log is constantly trying to add some device which is already added in the network

The dongle is in permit_join mode = false

![image](https://user-images.githubusercontent.com/3083124/43641039-6b087384-9722-11e8-9ec3-4e93766d8cd8.png)

**Comment by Koenkk** [comment]
Do you have Ikea TRADFRI bulbs?

**Comment by paskyecijano** [comment]
Xiaomi devices

**Comment by Koenkk** [comment]
Ok, this is not really a problem and will not be shown anymore in the next version of zigbee2mqtt.
