### ISSUE TITLE
[RFC] Group Home Assistant Auto-discovery

### ISSUE THREAD

**Issue by timstanley1985** [Koenkk/zigbee2mqtt#2410]
Groups are not currently auto-discovered by home assistant.  Can an option be added so that zigbee2mqtt groups can announce themselves to home assistant discovery?  This would be particularly helpful for lighting groups as no manual configuration would be required

**Comment by sjorge** [comment]
I'm not sure how this would work though, as groups could contain a set of lights, but also a set of blinds for example.

How would we know which one to expose to HA?

**Comment by Koenkk** [comment]
@sjorge in that case both blinds and light should be discovered, bulbs will ignore the blinds commands and vice versa.

**Comment by nobodypb** [comment]
Are there currently any efforts to implement this? I would be very interested in the discovery of groups via the Home Assistant protocol. Because then I could easily implement this for WebThings Gateway and wouldn't have to query each device individually.

Or are pull requests welcome? I haven't poke that much into the code of zigbee2mqtt, yet. So I have no idea how complicated it would be to accomplish this, but I could give it a try. However, I would be very pleased if you could give me some hints for the implementation then.

**Comment by rindlerblabla** [comment]
It's a much wanted functionality for me as well!

**Comment by julien-w** [comment]
It would be a very big improvement. Perhaps the last must-have feature missing for me :-)

**Comment by rindlerblabla** [comment]
Am still interested in this feature.

**Comment by Koenkk** [comment]
HA group discovery is supported now for groups of lights, switches, locks and covers.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by mdehaas** [comment]
Hi @Koenkk, any planning on when this is going to be included in the stable branch?

**Comment by Koenkk** [comment]
@mdehaas next z2m release on 1 July

**Comment by jd1900** [comment]
How is this implemented?
When turning on/off is a Zigbee command for each device sent or a command for the Zigbee group? I guess that the latest.

And..., I've noticed that when bootstraped if lights from a group are "on", the group is not "on". But once it is turned on/off it "syncs" with the group.

**Comment by mdehaas** [comment]
Hi jd1900,

If lights from one group are partially on, the group is not on or off. But I feel that when creating a group in Zigbee the individual lights should not be controlled. What is your 'use-case'? And I think you are looking in HA? What do you see in the Z2M interface?

**Comment by jd1900** [comment]
> Hi jd1900,
> 
> If lights from one group are partially on, the group is not on or off. But I feel that when creating a group in Zigbee the individual lights should not be controlled. What is your 'use-case'? And I think you are looking in HA? What do you see in the Z2M interface?

It happened in the HA interface.
And in groups with just one device after a reboot.
So it is not a big deal actually.

**Comment by mdehaas** [comment]
I have a group with one light because I need to install the rest in the ceiling so I will try this tomorrow although I feel this is not a common scenario…

**Comment by onedr0p** [comment]
I am currently experiencing this issue in home assistant. I have groups of 2 lights defined in zigbee2mqtt the entity in the GIF. When I toggle the group in home assistant the state is not updated correctly, until it is pressed again. Is this a known limitation of the groups feature?

![2021-07-11 18 30 16](https://user-images.githubusercontent.com/213795/125211688-38afdd80-e276-11eb-9dca-9cf8df3a2c80.gif)

**Comment by Koenkk** [comment]
@onedr0p is this fixed after setting the color temperature once via HA?

**Comment by onedr0p** [comment]
> @onedr0p is this fixed after setting the color temperature once via HA?

I can confirm this fixes it, thanks!

**Comment by Morphy99** [comment]
How do we disable group discovery in HA? I don't need to use groups apart from when Binding my IKEA remotes to bulbs so I have them set up for this. But now I have extra entities in HA which are just duplicates of devices.
