### ISSUE TITLE
Mueller Licht Scene

### ISSUE THREAD

**Issue by kotarokun** [Koenkk/zigbee2mqtt#2411]
Hello, 

i just updated the Zigbee2MQTT from shepherd to herdsman. 
I noticed that Müller Licht unfortunately still doesn't have scene support. So I asked if this could be added to Müllerlicht. For this lamp 404000_404005_404012 supported RGB should support the following additional function.

toZigbeeConverter:
`light_scene: {
        key: ['scene'],
        convert: (key, value, message, type, postfix) => {
            const cid = 'genBasic';
            if (type === 'set') {
                return {
                    cid: cid,
                    cmd: 'write',
                    cmdType: 'foundation',  // 'functional',
                    zclData: [{
                        attrId: 16389,
                        dataType: 32,
                        attrData: value
		    }],
	            cfg: {
				manufSpec: 1,
        		 	manufCode: 0x121b,   
		          },
                };
            }
        },
    },`

and device.js:
`    toZigbee: [.... tz.light_scene,`

That worked for Sherperd. I haven't tested it for Herdsman yet. 
Like it stand [here](https://forum.fhem.de/index.php/topic,95246.msg909441/topicseen.html#msg909441)

thanks a lot

**Comment by Koenkk** [comment]
What exactly does it do?

**Comment by kotarokun** [comment]
The Müller Licht have 6 light-Scenes on Board, so i can choose them via Remote-Control. I also like to choose them via MQTT ^^

**Comment by Koenkk** [comment]
So what values can be put in? Could you write some documentation for this?

**Comment by kotarokun** [comment]
Sorry, of course. 
Here is MQTT used for KODI
`scene:1,2,3,4,5,6 zigbee2mqtt/0x00158d0003247a3c/set {"$EVTPART0":$EVTPART1}`

Like above, you can select 1 to 6 😅

**Comment by Koenkk** [comment]
thanks, could we map these numbers to some more friendly names? E.g. 1 = `fireplace`?

**Comment by Albarion** [comment]
Is this implemented? It seems like I cannot use the scene buttons on my müller remote.
