### ISSUE TITLE
[New device support]: TS0601 manufacturer _TZE284_nlrfgpny solar siren

### ISSUE THREAD

**Issue by peroanjo** [Koenkk/zigbee2mqtt#24149]
### Link

https://es.aliexpress.com/item/1005007022197993.html

### Database entry

{"id":11,"type":"EndDevice","ieeeAddr":"0xa4c138e5cdd4c8e4","nwkAddr":62092,"manufId":4417,"manufName":"_TZE284_nlrfgpny","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0,60672],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65487":14400,"65503":"�S�.f�S�.\u0012","65506":56,"65508":0,"appVersion":77,"stackVersion":0,"dateCode":"","modelId":"TS0601","manufacturerName":"_TZE284_nlrfgpny","powerSource":3,"zclVersion":3,"hwVersion":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1727637030467}

### Zigbee2MQTT version

 1.40.1

### Comments

Hello everyone,

It seems like this device is already supported as NAS-AB06B2 in the official z2m release. However _TZE284_nlrfgpny manufacturer is not registered.

Also, in the vendor page, there are comments of people saying it works with z2m. So it would seem like the seller recently modified the manufacturer id and is not recognized by z2m anymore.

Any help will be kindly appreciated!

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE284_nlrfgpny',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

I tried using an external definition I found in #19827. However I couldn't get it to work...

**Comment by averter** [comment]
Hello, indeed I am experiencing the same issue with a siren from the same vendor. Thanks for mentioning issue #19077 as it might be relevant to some extent.

**Comment by averter** [comment]
Recently updated to 
Zigbee2MQTT version
    [1.40.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.2) commit: [e06848db](https://github.com/Koenkk/zigbee2mqtt/commit/e06848db)

Coordinator type
    zStack3x0

Coordinator revision
    20230507

Coordinator IEEE Address
    0x00124b002c3a6118

Frontend version
    0.7.4

zigbee-herdsman-converters version
    20.21.0

zigbee-herdsman version
    2.1.3

and when I try to interview there is a new log message:

2024-10-05 07:33:07zh:controller:device: Device '0xa4c1382f18ffcfc2' is only compliant to revision '21' of the ZigBee specification (current revision: 23).

Any thoughts?

**Comment by peroanjo** [comment]
For me I can interview the siren just fine and I won’t see any errors. Are you getting this error consistently? I saw the issue with the new manufacturer has also been mentioned in https://github.com/Koenkk/zigbee2mqtt/discussions/17325#discussioncomment-10803048 #17325

**Comment by averter** [comment]
> For me I can interview the siren just fine and I won’t see any errors. Are you getting this error consistently? I saw the issue with the new manufacturer has also been mentioned in [#17325 (comment)](https://github.com/Koenkk/zigbee2mqtt/discussions/17325#discussioncomment-10803048) #17325

Based on the comment in #17325 could it be as simple as adding `_TZE284_nlrfgpny` to [this line](https://github.com/Koenkk/zigbee-herdsman-converters/blob/0fcc1eb52847c299d32fd80387131d9ea75bec1f/src/devices/neo.ts#L47)? As in

`        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_t1blo2bj','_TZE284_nlrfgpny', '_TZE204_t1blo2bj', '_TZE204_q76rtoa9']),`

**Comment by peroanjo** [comment]
I think so, yes. But I haven’t been able to test it yet, as I am using the HassOS addon and don’t have access to the z2m internal files. Are you able to modify it?

**Comment by averter** [comment]
Bingo!
![image](https://github.com/user-attachments/assets/ca0fce1e-3137-4dd5-9272-872365c413df)

I didn't even had to re-interview; simply had to restart zigbee2mqtt. 
Specifically, I'm using docker on a raspberry pi and had to change the above file, which is located in `/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/neo.js`
I'll create a PR as soon as possible. Thanks for directing me to the comment which provided the solution :-)

**Comment by averter** [comment]
Can't test those atm as I am not at home. I'd also note that the battery hasn't shown up yet, which is also known as a long-standing issue-

**Comment by gregoriusus** [comment]
Just for info. For me everything is working. Battery is shown, changing alarm mode is working. Melody haven't tested yet. Maybe it also depends on manufacturer.
![image](https://github.com/user-attachments/assets/0e71ea65-e348-4407-a91c-b14905772d29)

**Comment by averter** [comment]
@gregoriusus Interesting...just to confirm, your manufacturer is `_TZE284_nlrfgpny`?

**Comment by gregoriusus** [comment]
Hmm, no, I have:
![image](https://github.com/user-attachments/assets/62f55eca-9dfb-4de7-9865-41ce32967edc)

**Comment by averter** [comment]
@gregoriusus ok then it's not applicable to our case since it's not the same manufacturer.
@peroanjo I've now fully tested the siren and the alarm melody and alarm mode work perfectly. The only thing which does not work is the Battery SoC.

**Comment by averter** [comment]
There seems to be an active development on the battery issue though. See https://github.com/Koenkk/zigbee2mqtt/issues/19827

**Comment by peroanjo** [comment]
@averter that’s good news! I have switched to the dev branch and the siren got recognized perfectly, however I haven’t been able to test it to be working correctly as my siren ran out of battery and I don’t have physical access to it for now.
Thank you for your insight, I think we can then close this issue as the battery problem seems to be a general issue with this model.

**Comment by ioanvladcristian** [comment]
Now working with Zig2MQTT.
Tested with this device: 
https://www.aliexpress.com/item/1005007022197993.html?spm=a2g0o.order_list.order_list_main.76.5ff81802HxyZ7R

**Comment by averter** [comment]
> Now working with Zig2MQTT. Tested with this device: https://www.aliexpress.com/item/1005007022197993.html?spm=a2g0o.order_list.order_list_main.76.5ff81802HxyZ7R

But without the battery I presume? :-)

**Comment by ioanvladcristian** [comment]
> > Now working with Zig2MQTT. Tested with this device: https://www.aliexpress.com/item/1005007022197993.html?spm=a2g0o.order_list.order_list_main.76.5ff81802HxyZ7R
> 
> But without the battery I presume? :-)

Correct!

**Comment by averter** [comment]
Wow. I can't believe it but the battery percentage HAS FINALLY SHOWN UP! My manufaturer is the same as before i.e. `_TZE284_nlrfgpny` which was unreported as working as the sirens from @gregoriusus  and others, which were of different manufacturers.

<img width="1640" height="687" alt="Image" src="https://github.com/user-attachments/assets/200f4177-2523-4fe6-9318-5b81a842cf1b" />

<img width="740" height="105" alt="Image" src="https://github.com/user-attachments/assets/6d056afb-2cf3-49c7-9fa1-f255487ff0fe" />

I can confirm that their strategy is the way to go, i.e., keep the siren out of direct sunlight, and very importantly as well, keep constantly activating the lights to drain the battery as much as possible. I ended up doing this last step manually, but as said, it'd be useful to be able to do this with a script in an automated way. Hope this helps others.

**Comment by tomiisp** [comment]
I have exact same Zigbee model/Model and still battery reported as Null% not matter what I try to do (reconfig, repair, discharge (it was about 2 months active in closed box) ) and still no battery level... 

> Wow. I can't believe it but the battery percentage HAS FINALLY SHOWN UP! My manufaturer is the same as before i.e. `_TZE284_nlrfgpny` which was unreported as working as the sirens from [@gregoriusus](https://github.com/gregoriusus) and others, which were of different manufacturers.

> I can confirm that their strategy is the way to go, i.e., keep the siren out of direct sunlight, and very importantly as well, keep constantly activating the lights to drain the battery as much as possible. I ended up doing this last step manually, but as said, it'd be useful to be able to do this with a script in an automated way. Hope this helps others.

**Comment by averter** [comment]
> I have exact same Zigbee model/Model and still battery reported as Null% not matter what I try to do (reconfig, repair, discharge (it was about 2 months active in closed box) ) and still no battery level...
> 
> > Wow. I can't believe it but the battery percentage HAS FINALLY SHOWN UP! My manufaturer is the same as before i.e. `_TZE284_nlrfgpny` which was unreported as working as the sirens from [@gregoriusus](https://github.com/gregoriusus) and others, which were of different manufacturers.
> 
> > I can confirm that their strategy is the way to go, i.e., keep the siren out of direct sunlight, and very importantly as well, keep constantly activating the lights to drain the battery as much as possible. I ended up doing this last step manually, but as said, it'd be useful to be able to do this with a script in an automated way. Hope this helps others.

Sorry to hear that. Note that leaving the siren out of direct sunlight is not enough to make it discharge. The siren is incredibly  energy-efficient, and so unless you manually discharge it multiple times when out of sunlight it won't reach the 98% threshold. I spent a lot of time turning its lights on until the 98% showed up (I had lost hope to be honest). Good luck
