### ISSUE TITLE
[New device support]: TS0601 manufacturer  _TZE284_ltwbm23f

### ISSUE THREAD

**Issue by dobmeierr** [Koenkk/zigbee2mqtt#24167]
### Link

https://de.aliexpress.com/item/1005007658931092.html?spm=a2g0o.productlist.main.19.5d69knSwknSwk0&algo_pvid=f50fc6ea-79ad-468c-998e-0acdf7becc30&algo_exp_id=f50fc6ea-79ad-468c-998e-0acdf7becc30-9&pdp_npi=4%40dis%21EUR%2166.18%2159.39%21%21%21504.42%21452.67%21%40211b6c1917277912892317283e781a%2112000041690631106%21sea%21DE%210%21ABX&curPageLogUid=xcCLm3bqcbpN&utparam-url=scene%3Asearch%7Cquery_from%3A

### Database entry

{"id":102,"type":"EndDevice","ieeeAddr":"0xa4c138800c08e753","nwkAddr":29355,"manufId":4417,"manufName":"_TZE284_ltwbm23f","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0,60672],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65487":14400,"65503":" ��.i!��.f\"��.\u0012","65506":56,"65508":0,"stackVersion":0,"dateCode":"","appVersion":77}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":77,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1727790473389}

### Zigbee2MQTT version

1.40.1

### Comments

Please add support for this device.

### External definition

const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE284_ltwbm23f',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;

### What does/doesn't work with the external definition?

Haven't tried extending the external definition yet.

**Comment by psubbotin** [comment]
need support
