### ISSUE TITLE
TS0201 reporting data too many times

### ISSUE THREAD

**Issue by stefanopedraglio** [Koenkk/zigbee2mqtt#24164]
### What happened?

I added some TS0201 temperature and humidity sensors to my zigbee network. I used the same sensor in the past with no issues on other zigbee networks with older zigbee2mqtt versions.
Now all of the sensors are reporting each 60s, most of the times they report a couple of times each time they wake up.
Here the logging of the reported measurements.
![reporting](https://github.com/user-attachments/assets/2c268eb9-57ea-4f10-9b7f-97463bd65ace)
I tried to configure the reporting min interval and minimum variation. The writing of the configuration is successfull, but I see no changes in the behaviour.
![reporting_config](https://github.com/user-attachments/assets/7e843303-fa59-4434-9061-ac789411caa3)
Here the content of my database.db

{"id":2,"type":"EndDevice","ieeeAddr":"0xa4c1381004b134db","nwkAddr":35788,"manufId":4417,"manufName":"_TZ3210_ncw88jfq","powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[1,1026,1029,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"��.\u0012","65506":54,"65508":0,"65534":0,"stackVersion":0,"dateCode":"","manufacturerName":"_TZ3210_ncw88jfq","zclVersion":3,"appVersion":131,"modelId":"TS0201","powerSource":3,"hwVersion":1}},"msRelativeHumidity":{"attributes":{"measuredValue":598}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2300}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":38,"batteryVoltage":27}}},"binds":[{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0xb43522fffe03237d","endpointID":1},{"cluster":1029,"type":"endpoint","deviceIeeeAddress":"0xb43522fffe03237d","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0xb43522fffe03237d","endpointID":1}],"configuredReportings":[{"cluster":1026,"attrId":0,"minRepIntval":120,"maxRepIntval":3600,"repChange":255},{"cluster":1029,"attrId":0,"minRepIntval":120,"maxRepIntval":3600,"repChange":255},{"cluster":1,"attrId":33,"minRepIntval":120,"maxRepIntval":3600,"repChange":255},{"cluster":1,"attrId":32,"minRepIntval":120,"maxRepIntval":3600,"repChange":255}],"meta":{}}},"appVersion":131,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":217189513},"lastSeen":1727732655667}

It is quite strange to have similar issues with a so largely used sensor.
Thank very much for your help

### Zigbee2MQTT version

 1.40.1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

 EZSP v8

### Setup

Plain zigbee2mqtt on raspberry pi 5

**Comment by MaD-Do6pblu** [comment]
У меня аналогичная проблема с датчиками CO2 TS0601. Установлено 3 штуки. Шлют отчеты по нескольку раз в секунду, из-за чего тормозит Home Assistant, и лагает сеть ZigBee.
Как с этим бороться? Помогите пожалуйста.
![2024-10-02_12-52-38](https://github.com/user-attachments/assets/17853218-a48b-4643-8754-62edd91a451c)
