### ISSUE TITLE
NOUS DZ4 not recognized

### ISSUE THREAD

**Issue by DEFAYArnaud** [Koenkk/zigbee2mqtt#24182]
### What happened?

Hello,

I have just bought the NOUS DZ4 module (https://www.zigbee2mqtt.io/devices/D4Z.html).
But the problem is that it is not recognized and so it is “Not supported”.

<img width="1356" alt="Capture d’écran 2024-10-02 à 16 55 06" src="https://github.com/user-attachments/assets/181edee3-1255-49ce-a2b4-46e0026e745a">

How can I solve the problem please.

Thank you in advance

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

7.4.4

### Adapter

SKYCONNECT

### Setup

Home Assistant Green

**Comment by derspe** [comment]
Hi @DEFAYArnaud , I'm having the same problem here. How did you solve it. Thx in advance.

**Comment by DEFAYArnaud** [comment]
Hi @derspe, here's the solution : [https://github.com/Koenkk/zigbee-herdsman-converters/issues/8064](url)

**Comment by derspe** [comment]
Thx so much - made my day
