### ISSUE TITLE
Sonoff Smart Water Valve (SWV) cycle irrigation_interval value error

### ISSUE THREAD

**Issue by TomFahey** [Koenkk/zigbee2mqtt#24189]
### What happened?

When using the MQTT Publish action in Home Assistant with the exposed `cyclic_timed_irrigation`  feature, using a value >=`32640` for the `irrigation_interval` parameter results in different values being set on the SWV.

For example, requesting an `irrigation_interval` of `32640` results in an actual value of `32751` being set. Having tested a few different values, I noticed the following pattern:

- Requesting values <`32640` work without any issues
- Requesting values from `32640` result in the value `32751` being set
- Requesting values between ~`32800`-`60000 `result in the value `61375` being set
- Requesting values between `70000`-`72000` seem to work ok
- Requesting values between `75000`-`86400` result in values a few bits off from the correct one

I've tested this behaviour with two separate SWVs, one with firmware 4098, the other with 4100. 
The Zigbee coordinator is a Sonoff Zigbee Plus V2 (E) USB 3.0, tested with FWs 7.3.3.0 and 7.4.4.0, passed through to the Z2M Home Assistant add-on. 

Setting the `irrigation_interval` value directly from the Zigbee2MQTT Web UI works without any problems.

### What did you expect to happen?

`irrigation_interval` values are set correctly, across the full range (0-86400)

### How to reproduce it (minimal and precise)

![image](https://github.com/user-attachments/assets/7e80aadf-f455-402f-87d7-f76d9368caa1)

![image](https://github.com/user-attachments/assets/d0fb32c8-413c-491f-9837-ae017355f76f)

![image](https://github.com/user-attachments/assets/68d3c0f5-081d-439b-8ffb-33d74fccf0d4)

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

7.3.3.0 build 239, 7.4.4.0 build 0

### Adapter

Sonoff ZBDongle Plus V2 (E), tested with EZSP and ember drivers

### Setup

Add-on Home Assitant OS VM in Proxmox on Intel N400 Mini-PC

### Debug log

[SWV - Irrigation Interval 32639.log](https://github.com/user-attachments/files/17235780/SWV.-.Irrigation.Interval.32639.log)
[SWV - Irrigation Interval 32640.log](https://github.com/user-attachments/files/17235782/SWV.-.Irrigation.Interval.32640.log)

**Comment by mathmaniac43** [comment]
I am not experiencing the exact same behavior, but when I set to an interval of zero or one via MQTT, I get a huge negative number!

"irrigation_interval": -1078132736,
