### ISSUE TITLE
WARN No converter available for 'QBKG04LM' with cid 'genBasic',

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#242]
I have 2 QBKG04LM, with two scenes, but work randomly and this is the log:

> 2018-8-3 20:46:04 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":230.39,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:46:14 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":216.53,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:46:44 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":262.42,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:46:54 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":228.48,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:47:33 WARN No converter available for 'QBKG04LM' with cid 'genBasic', type 'attReport' and data '{"cid":"genBasic","data":{"65281":{"1":3300,"3":34,"5":21,"8":9749,"10":16012,"100":0,"101":0,"110":0,"111":255,"153":0,"155":0}}}'
2018-8-3 20:47:33 WARN Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
2018-8-3 20:47:33 WARN No converter available for 'QBKG04LM' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"65281":[null,3300,null,34,null,21,null,null,9749,null,16012,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,0,255,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,0]}}'
2018-8-3 20:47:33 WARN Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
2018-8-3 20:47:34 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":210.79,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:47:42 INFO MQTT publish, topic: 'zigbee2mqtt/pulsador_estudio', payload: '{"battery":"100.00","voltage":3042,"click":"single"}'
2018-8-3 20:47:42 INFO Zigbee publish to '0x00158d000159a8b3', genOnOff - on - {} - 2
2018-8-3 20:47:43 INFO MQTT publish, topic: 'zigbee2mqtt/interruptor_luz_estudio', payload: '{"state":"ON"}'
2018-8-3 20:47:43 INFO MQTT publish, topic: 'zigbee2mqtt/interruptor_luz_estudio', payload: '{"state":"ON"}'
2018-8-3 20:47:44 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_dormitorio_ja', payload: '{"power":0,"state":"ON","voltage":null,"consumption":82.03,"temperature":40}'
2018-8-3 20:47:45 INFO MQTT publish, topic: 'zigbee2mqtt/pulsador_estudio', payload: '{"battery":"100.00","voltage":3042,"click":"single"}'
2018-8-3 20:47:45 INFO Zigbee publish to '0x00158d000159a8b3', genOnOff - off - {} - 2
2018-8-3 20:47:45 INFO MQTT publish, topic: 'zigbee2mqtt/interruptor_luz_estudio', payload: '{"state":"OFF"}'
2018-8-3 20:47:45 INFO MQTT publish, topic: 'zigbee2mqtt/interruptor_luz_estudio', payload: '{"state":"OFF"}'
2018-8-3 20:47:53 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_leds_espejo_dormitorio', payload: '{"state":"OFF","power":0,"voltage":null,"consumption":375.19,"temperature":42}'
2018-8-3 20:48:24 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":241.39,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:48:44 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":220.83,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:50:24 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":246.64,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:50:34 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":229.91,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:51:04 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":212.71,"voltage":null,"consumption":128.5,"temperature":37}'
spinlock: false []
device already in network
2018-8-3 20:51:24 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":255.73,"voltage":null,"consumption":128.5,"temperature":37}'
2018-8-3 20:51:34 INFO MQTT publish, topic: 'zigbee2mqtt/enchufe_pc', payload: '{"state":"ON","power":225.61,"voltage":null,"consumption":128.5,"temperature":37}'

Any idea?

One of them is **zigbee2mqtt/interruptor_luz_estudio (0x00158d000159a8b3)**

And i dont know why say this: 

> spinlock: false []
> device already in network

All devices are paired.

**Comment by Koenkk** [comment]
For the QBKG12LM the `genBasic` report contains the power consumption. Looking at the log, this is not the case for the QBKG04LM. 

In the next version of zigbee2mqtt this message will not be shown anymore (ignored). Same goes for the `spinlock: false []`/`device already in network`.
