### ISSUE TITLE
Lupus roller shutter v2 with newest firmware 320 is not supportet

### ISSUE THREAD

**Issue by hl1972** [Koenkk/zigbee2mqtt#24208]
### What happened?

I bought a new switch which came with new firmware and is not supported
I already have switches like this with firmware 318 in the system. These were supported perfectly. A new switch with firmware 320 is not supported. You can't downgrade the firmware either.

### What did you expect to happen?

I expected that the roller shutter is supported  like the others in my system.
![Zigbee2mqtt ](https://github.com/user-attachments/assets/f9ae8c26-bd2a-461d-9e4b-770e79633b0b)

### Zigbee2MQTT version

1.40.2-1

### Adapter firmware version

320

### Adapter

port: >-   /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829190204-if00 adapter: ember

### Setup

Add on on Homeassistant on Intel Nuc

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
