### ISSUE TITLE
(BLE-YL01) no update data after version Z2m 1.40.2

### ISSUE THREAD

**Issue by aperezva** [Koenkk/zigbee2mqtt#24261]
### What happened?

after update my z2m to 1.40.2  my (BLE-YL01) pool monitor doesn´t send information. Ihave checked with a smartlife hub and it´s working.

### What did you expect to happen?

data updates after 10 muinutes.

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

 20221226

### Adapter

slzb 06

### Setup

lxc proxmox

**Comment by aperezva** [comment]
Aby feedback or information @Koenkk ?

**Comment by Koenkk** [comment]
Does it work again after downgrading z2m?

**Comment by aperezva** [comment]
Yes
 Correct. 
 
And I have two z2m databases in both is failing

**Comment by aperezva** [comment]
This command works before. Now it´s not working in both Z2m 

![image](https://github.com/user-attachments/assets/3944fcf9-0a49-414f-b393-df662ed62c02)

**Comment by Vaarinvaliliha** [comment]
Same thing here, interview goes fine but no data is moving :)

**Comment by aperezva** [comment]
> Does it work again after downgrading z2m?

But I don´t want to downgrade it for only one devices.

Any alternatives?

A new version?

**Comment by Koenkk** [comment]
Found the issue and fixed it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by aperezva** [comment]
Thanks

Will you upload to production, later this month?

BR

**Comment by Koenkk** [comment]
Yes, 1 November

**Comment by theimo1221** [comment]
@Koenkk It still might be happening, as even with herdsman V20.25.0 I don't get any values after pairing TS0202 and device sometimes get's stuck in a weird loop in which device leaves network directly after configure during interview.

**Comment by Koenkk** [comment]
@theimo1221 please open a new issue for that, it's not related to this device.

**Comment by theimo1221** [comment]
Thought it might be connected as it is a Tuya as well (considering your commit message)
Follow up issue:
https://github.com/Koenkk/zigbee2mqtt/issues/24314

**Comment by andresgomezfrr** [comment]
hey @aperezva @Koenkk, have you checked if the issue is solved after the latest release? I'm trying to pair the BLE-YL01 device and I cant send the command, this is the error:

```
zigbee2mqtt  | [2024-12-31 12:01:50] error: 	z2m: Publish 'set' 'command' to 'Piscina_Sensor' failed: 'Error: No datapoint defined for 'command''
```

I also see this error on the logs related to the same device:

```
zigbee2mqtt  | [2024-12-31 11:47:41] error: 	z2m: EventBus error 'OnEvent/deviceMessage': ZCL command 0x0cae5ffffee8c740/1 manuSpecificTuya.mcuVersionRequest({"seq":2}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))
```


Any help? please! 🙏🏼  and happy new year!! 🎉

**Comment by aperezva** [comment]
Hi,

It was solved versions before o n november versión i guess.

Remove from network and pair it again.

**Comment by ThePhantom79** [comment]
Hi, 
I a, slo using BLE-YL01 with Z2m. Pairing was successfull and I get one time the correct data. Sometimes after a while it will be renewed once or twice, but then : nothing. I dont get any new data from device. 


Z2M version:
2.1.1
Coordinator-Typ
zStack3x0
Coordinator-Version
20240710
Coordinator IEEE Adresse
0x00124b0031df5380
Frontend-Version
0.9.4
Zigbee Herdsman Konverter Version
21.31.0
Zigbee Herdsman Version
3.2.5

I dont know, what to do. With original Tuya Gateway everything worked well for the last weeks.

Any hints?

**Comment by juslex** [comment]
Some problem here

**Comment by OE5DRO** [comment]
+1

**Comment by Sylv157** [comment]
Same problem here. Can you solve this please?

**Comment by arnaud-cortisse** [comment]
+1

**Comment by juslex** [comment]
please check here https://github.com/Koenkk/zigbee2mqtt/issues/23946#issuecomment-2949219614 There is a new external converter that seems to have solved the problem

**Comment by Koenkk** [comment]
The fix is available in the dev branch, can you check if it works?

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.

**Comment by ThePhantom79** [comment]
For me unfortunately it doesnt  work ...
Repairing, Reconfigering,  Interviewing successfull, but then no data receiving ... :-(

**Comment by OE5DRO** [comment]
i dont use dev branche but external converter, but it does not work:

<img width="687" alt="Image" src="https://github.com/user-attachments/assets/7b7580e0-51f8-496f-a2da-869a2b9396fe" />

**Comment by xvolte** [comment]
any news on this ? i have same problem

**Comment by xvolte** [comment]
hello all,

Thanks to everyone, i was able i think to solve the issues.

I documented here : https://community.home-assistant.io/t/pool-monitoring-device-yieryi-ble-yl01-zigbee-ph-orp-free-chlorine-salinity-etc/659545/130?u=xvolte

Hope it works for you too :)

**Comment by ThePhantom79** [comment]
Hi, 
I tried it, and at least it' doing something. Some questions:

- Why you use the condition "if pool temperature is not availabe". For me this do not work, as even if the device do not send any NEW values, it never shows "not available". It shows me then the old value for hours ...For me, I will delte this condition. It should trigger every 15 minutes, regardless of any coditions.
- Why do you switch the backlight value for 24 time per trigger? Any special reason?

Your code is very appreciated - I just want to understand it.

Thanks!
