### ISSUE TITLE
Nous B3Z randomly switching off channel 1 light

### ISSUE THREAD

**Issue by peyn** [Koenkk/zigbee2mqtt#24288]
### What happened?

Hi,

I recently bought a Nous B3Z (https://www.zigbee2mqtt.io/devices/B3Z.html#nous-b3z) zigbee switch with 2 channels.
I connected it to the switch in the wall, successfully paired with my zigbee network and it was discovered by the Zigbee2MQTT addon in my Home Assistant installation. Added to the list of devices under name "Światło Mateusz".

The switch is set to power off the light when it loses and regains the power.
![image](https://github.com/user-attachments/assets/b37b9e83-2e26-4635-b614-e04edd807d4e)

The issue I am facing is that at random intervals the switch switches off the light connected to switch number 1.
Sometimes it's after an hour, sometimes it's after a few minutes (1st & 3rd row is switching off, 2nd & 4th switching on).
![image](https://github.com/user-attachments/assets/49c575b8-210c-449b-a0b3-a1ec4a8f1292)

I checked the wiring at least 3 times already. Tighten every screw. There is no way that something is not connected right.

I changed the "Power-on" value to "previous", but the light on switch number 1 was still switched off. It would seem this is not related to loss of power.

I removed the device from the Zigbee2MQTT configuration and switched on both lights. They were still on after 3 hours.
The conclusion is that it is related to Zigbee itself, either on the device or Zigbee2MQTT side.

I changed the device to another one of the same model - same issue with the switch number 1.

I also update Zigbee Coordinator software yesterday, but today the issue is still there - light on channel 1 is randomly switched off.

I do not use Alexa. I disabled the Apple Home (HASS Bridge) integration in Home Assistant.

Kind regards,
Mateusz

### What did you expect to happen?

I expect the light on channel 1 to stay switched on.

### How to reproduce it (minimal and precise)

No idea, it seems it happens randomly.

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

20240710

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on Home Assistant

### Debug log

This is 5 minutes just before the light went off. The whole log is more than 8MB.
[Zigbee Log Small.txt](https://github.com/user-attachments/files/17341530/Zigbee.Log.Small.txt)

**Comment by TFisch64** [comment]
I have the same problem with B3Z

Zigbee2MQTT version    1.40.2 commit: e06848d
Coordinator type  EmberZNet 
Coordinator revision   7.4.4 [GA]
    


12.10.24  0:43 man ON   1:04 auto OFF       21min
13.10.24 10:09 man ON   10:44 auto OFF      35min    
13.10.24 11:41 man ON   13:37 auto OFF      116min
13.10.24 15:15:49 man ON   18:55:57 auto OFF   220min

**Comment by Kontendesigner** [comment]
I had the same problem with 2 Z3B , mailed the NOUS support and got 2 new devices for free.

**Comment by peyn** [comment]
> I had the same problem with 2 Z3B , mailed the NOUS support and got 2 new devices for free.

Thank you for the information. I will check this option.

Kind regards,
Mateusz

**Comment by peyn** [comment]
Indeed the NOUS support confirmed that they know about the issue and will send a new device. 
Therefore I will close the issue.

Kind regards,
Mateusz

**Comment by peyn** [comment]
> To where do I have to return the old ones? 

No idea. I am not affiliated with NOUS nor the seller that provided you the devices.
Please ask them.

Kind regards,
Mateusz

**Comment by MaZe3D** [comment]
Hi, 
i am just curious if the devices you received from support are now working as expected or if they still have the issue of randomly switching on and off.
I would love to hear it.
Kind regards
Mark

**Comment by peyn** [comment]
I bought 3 devices and had 3 of them replaced by the support. I installed only one of them, though. It works fine.


Kind regards,
Mateusz

**Comment by cciciot** [comment]
I understand that you are experiencing random switching issues with your Tuya ZigBee device. Based on the Tuya DP (Data Point) protocol, some devices have a built-in Random Timing (DP=210) feature, which may cause unexpected on/off behavior.

To check if this feature is enabled on your device, please follow these steps in Zigbee2MQTT:

Read the current value of DP=210

Publish the following MQTT message to retrieve the status:
```
{
  "topic": `"zigbee2mqtt/YOUR_DEVICE_NAME/get",`
  "payload": "210"
}
```
If the returned value is non-zero (e.g., 1, 2, 3, etc.), the Random Timing function is enabled, which may be causing the issue.
Disable DP=210 if necessary

If DP=210 is not set to 0, try disabling it by publishing:
```
{
  "topic": "zigbee2mqtt/YOUR_DEVICE_NAME/set",
  "payload": { "210": 0 }
}
```
After doing this, observe if the random switching issue still occurs.
If DP=210 is already disabled but the issue persists, we may need to investigate ZigBee group bindings, network stability, or unintended Home Assistant automations. Let me know what value you get for DP=210, and we can troubleshoot further.

Looking forward to your feedback!

**Comment by MaZe3D** [comment]
I would like to try but I don't know how. Where do I have to enter those parameters in Zigbee2MQTT?

**Comment by cciciot** [comment]
> I would like to try but I don't know how. Where do I have to enter those parameters in Zigbee2MQTT?



> I would like to try but I don't know how. Where do I have to enter those parameters in Zigbee2MQTT?

I apologize for the earlier misinformation. The DP 210 (random timing)  functions require the Tuya Gateway or Tuya Cloud platform to query and modify; they cannot be directly operated via Zigbee2MQTT. I've reached out to the Tuya team and am awaiting their feedback. I'll update you as soon as I have more information. Thank you for your understanding!

**Comment by ahorseman** [comment]
> > I would like to try but I don't know how. Where do I have to enter those parameters in Zigbee2MQTT?
> 
> > I would like to try but I don't know how. Where do I have to enter those parameters in Zigbee2MQTT?
> 
> I apologize for the earlier misinformation. The DP 210 (random timing) functions require the Tuya Gateway or Tuya Cloud platform to query and modify; they cannot be directly operated via Zigbee2MQTT. I've reached out to the Tuya team and am awaiting their feedback. I'll update you as soon as I have more information. Thank you for your understanding!

Any update @cciciot ?
