### ISSUE TITLE
EnOcean PTM 215Z not registering button clicks (action)

### ISSUE THREAD

**Issue by Atiunderscore** [Koenkk/zigbee2mqtt#24287]
### What happened?

I've bought a 3-pack Friends of Hue Smart Switches and I'm in the process of connecting these in Home Assistant through Z2M. Connecting the first one was a breeze and everything functions as expected:

![image](https://github.com/user-attachments/assets/6ea87a7b-39e3-48e5-a5a5-0d61cf6f1b1e)
![image](https://github.com/user-attachments/assets/6b988036-4939-4ecf-962a-744493014de3)

So I just press the 'Permit join (All)' button within Z2M, on the switch itzelf click 2 random buttons and then hold the top-right button to join. Once joined I can use the action trigger in automations. Also when I press one of the buttons I can see within the device information in Z2M the 'Action' value rapidly changing to whatever button I pressed and reverting to status 'N/A'.

Joining the second switch also went easy, but from some reason this switch is nog registering the buttons when pressed. The state of action stays 'N/A':

![image](https://github.com/user-attachments/assets/a308f274-8a57-45ae-84b4-3916ecec896e)
![image](https://github.com/user-attachments/assets/de68b73f-c9cc-4c96-8eff-3ec5b851029b)

Because the action is not being registered I am also unable to select these as a trigger in an automation:

![image](https://github.com/user-attachments/assets/44a30a33-89fb-4afc-8d45-607d23b0fd0a)

In comparison to the first switch I joined:

![image](https://github.com/user-attachments/assets/adc0f7c1-ae11-49d9-b4d0-015a70414cf7)

I tried restarting Home Assistant, rejoining through various other Philips Hue devices and factory resetting the switch. Nothing seems to work. Is there anyone here that can help me resolve this issue?

Version and adapter information:

![image](https://github.com/user-attachments/assets/81bd9219-1811-46ac-b78f-7e753be1bbfa)

![image](https://github.com/user-attachments/assets/b52325b4-0be7-4f5f-ba57-ffd16239633d)

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

7.4.2

### Adapter

Nabu_Casa_SkyConnect_v1.0 (ember driver)

### Setup

Add-on on Home Assistant OS

**Comment by chris-1243** [comment]
I would factory reset all your PTM first. Then, strictly follow the pairing process. While pairing, do not play with the device. Only the buttons which are required during this process.

https://www.zigbee2mqtt.io/devices/PTM_215Z.html#enocean-ptm%2520215z

Some tips😉 check this [link](https://www.zigbee2mqtt.io/advanced/zigbee/01_zigbee_network.html#green-power-devices) before any pairing try. Avoid to pair thoses devices as `brodacast` as you will see some latency in your network. Try to use the `unicast` mode.

Never pair via the `permit join all`. Always select a router as close as possible and use the `permit join via "router_xy"`. If your router is not listed, don't worry and check the cluster tab. Find if the endpoint 242 is present. At least the `output cluster, greenPower` should be sufficient.

I have 7 PTM215Z and 1 PTM215ZE and they are all working perfectly.

**Comment by Atiunderscore** [comment]
> I would factory reset all your PTM first. Then, strictly follow the pairing process. While pairing, do not play with the device. Only the buttons which are required during this process.
> 
> https://www.zigbee2mqtt.io/devices/PTM_215Z.html#enocean-ptm%2520215z
> 
> Some tips😉 check this [link](https://www.zigbee2mqtt.io/advanced/zigbee/01_zigbee_network.html#green-power-devices) before any pairing try. Avoid to pair thoses devices as `brodacast` as you will see some latency in your network. Try to use the `unicast` mode.
> 
> Never pair via the `permit join all`. Always select a router as close as possible and use the `permit join via "router_xy"`. If your router is not listed, don't worry and check the cluster tab. Find if the endpoint 242 is present. At least the `output cluster, greenPower` should be sufficient.
> 
> I have 7 PTM215Z and 1 PTM215ZE and they are all working perfectly.

Thank you for the reply. I force deleted the PTM215Z switch from Z2M. After that I factory resetted the switch. I then checked the list on the following website to see which of my other Zigbee devices is best to pair with:

https://www.zigbee2mqtt.io/advanced/zigbee/01_zigbee_network.html#green-power-devices

I have a couple of "Philips 9290022169" bulbs, so I picked the one closest to the switch. Afer that I joined the switch on one of the closests bulbs by following the steps from page you linked, but still no luck. I also tried joining it to every single other Zigbee router, but also no success.

You are also talking about "endpoint 242", but I don't know exactly what this means. I do see it stated under clusters and dev console:

![image](https://github.com/user-attachments/assets/6613c7dc-639f-4dff-aa5e-fdc9bbad482f)

![image](https://github.com/user-attachments/assets/4cb43c0a-cb0c-4fda-aef1-0da66de97fc0)

Now I know these can work, because I have a PTM215Z switch with configurable actions. But sadly 2 of the same other switches don't. Do you or anyone else have any tips that may help?

**Comment by Atiunderscore** [comment]
Wow.. I was breaking my head on this one. I've read the instructions so many times, but I somehow read over the following:

"Once the device is paired you need to confirm the channel. To do this press A1 and B0 together. Important: don't press any other buttons between this and the pairing."

After confirming the channel it now works. Thank you for helping out @chris-1243

**Comment by chris-1243** [comment]
> "Once the device is paired you need to confirm the channel. To do this press A1 and B0 together. Important: don't press any other buttons between this and the pairing."

That is the most important part of the process !

Glad everything is now working
