### ISSUE TITLE
Can't get npm started with zigbee2mqtt (New to this) 

### ISSUE THREAD

**Issue by experiencingiot** [Koenkk/zigbee2mqtt#2429]
Hello,

I'm new to zigbee2mqtt and also raspberry even. What i want to do is to use zigbee2mqtt with iobroker mqtt server. Application is to get / send data to/from zigbee philips devices. 
My coordinator cc2531 is flashed with new firmware (just got it purchased).
However, when i run npm.. it never starts and displays some errors like can't open serial port.
I'm wondering that it happened 2 to 3 times that zigbee herdsmen got started (without any changing in the setup), however, never established connection with mqtt server.
But most of the times, herdsmen never starts. 
Please help me cover up this problem as a beginner. 

The link to npm log is given below:

https://pastebin.com/UgmfprxS

Looking for friendly responses.

**Comment by Koenkk** [comment]
Hi!

Did you check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start ?

**Comment by experiencingiot** [comment]
Yes, I have surely gone through this link. I'm having correct port in configuration.yaml file. Also i tested the command "test -w [PORT] && echo success || echo failure" which gives success to me every time. Any more hints?

**Comment by davet2001** [comment]
It looks more like npm is not starting properly rather than a port error. 

Did you run ‘npm install’ before ‘npm start’?
