### ISSUE TITLE
color（HS）use  wrong zigbee command

### ISSUE THREAD

**Issue by mosanwen** [Koenkk/zigbee2mqtt#24297]
### What happened?

when set color by "color(X/Y)" or "color (hs)",both of them send “move to color （XY）”
![微信截图_20241012114752](https://github.com/user-attachments/assets/8102835f-fbe2-4a46-8f8b-95e1814b26db)
![微信截图_20241012114841](https://github.com/user-attachments/assets/afdadf0d-987b-47cd-9967-6611003e59c1)

### What did you expect to happen?

 “color（hs）”should send “MOVE_TO_HUE_AND_SATURATION ”。

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

EZSP v8 6.10.3.0 build 297

### Adapter

SONOFF_Zigbee_3.0 _USB_Dongle_Plus_V2_20221029145826-if00

### Setup

on homeassistant

**Comment by Oggymator** [comment]
push

**Comment by Koenkk** [comment]
This is a frontend issue, please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend

**Comment by mosanwen** [comment]
> I used some GLEDOPTO products and has the same problem, using ZigStar USB and newest Version of Z2M. Anybody an idea?
go to MQTT->CONFIGIRE->Publish a pagclet.
![image](https://github.com/user-attachments/assets/3b560881-477e-4f62-9616-09e56b282297)
