### ISSUE TITLE
HK-DIM-A - Power_On_Behavior unsupported

### ISSUE THREAD

**Issue by Telk0** [Koenkk/zigbee2mqtt#24328]
### What happened?

Trying to get Power-on Behavior gives this error. the error randomly spams aswell.

![image](https://github.com/user-attachments/assets/c479870e-b02c-4742-b708-b0c38165acb1)
![image](https://github.com/user-attachments/assets/848c2ff8-05d0-447d-b9b4-b5888153c9a1)

### What did you expect to happen?

i would set the power-on behavior.

### How to reproduce it (minimal and precise)

Try change the setting.

### Zigbee2MQTT version

1.40.2-1

### Adapter firmware version

20220219

### Adapter

Sonoff Dongle-P - zStack3x0

### Setup

HA OS on Intel NUC x64 as add-on

### Debug log

![image](https://github.com/user-attachments/assets/330783da-89c3-4e96-875a-0d781dda5dbf)

**Comment by Telk0** [comment]
@Koenkk

**Comment by Koenkk** [comment]
The device does not support this (given the error), I removed it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
