### ISSUE TITLE
Duplicate packets published, problem with Gledopto bulb

### ISSUE THREAD

**Issue by redahb** [Koenkk/zigbee2mqtt#2432]
I have a couple of the new kind of Gledopto bulbs, E27, E14, etc. These are the 'PLUS' variants, e.g. GL-B-008ZS (note the **S** on the end). These bulbs offer proper fade in/out to mimic HUE bulbs. However, I noticed strange behavior. If I have a bulb on warm white, and then use the Home Assistant `light.turn_on` service with the `color_name: red` option, I see these messages sent by Zigbee2MQTT:

Message 0:
`{
    "state": "ON",
    "color_temp": 370,
    "color": {
        "x": 0.459857791746717,
        "y": 0.410598847355503
    },
    "brightness": 255
}`

Message 1:
`{
    "state": "ON",
    "color_temp": 37,
    "color": {
        "x": 0.701,
        "y": 0.299
    },
    "brightness": 255
}`

Visually this looks OK, the bulb fades from warm white to red. But I don't really know why 2 messages are needed. When I issue a new `light.turn_on` service with the `color_name: blue` option, I see these messages sent by Zigbee2MQTT:

Message 0:
`{
    "state": "ON",
    "color_temp": 37,
    "color": {
        "x": 0.701,
        "y": 0.299
    },
    "brightness": 255
}`

Message 1:
`{
    "state": "ON",
    "color_temp": 127,
    "color": {
        "x": 0.136,
        "y": 0.04
    },
    "brightness": 255
}`

Again, looks OK, the bulb fades from red to blue. But still, why 2 messages? It already was red, so why send `color_temp: 37` again?

Now, problems arise when I swith the bulb off (in HA, not physically) and then on again. I send `light.turn_off` and the message is:

`{
    "state": "OFF",
    "color_temp": 127,
    "color": {
        "x": 0.136,
        "y": 0.04
    },
    "brightness": 255
}`

Remember, the bulb was blue before turning off! So let's turn the bulb on, but have it be red. Again, I request the `light.turn_on` service with the `color_name: red` option, and see these messages:

Message 0:
`{
    "state": "ON",
    "color_temp": 127,
    "color": {
        "x": 0.136,
        "y": 0.04
    },
    "brightness": 255
}`

Message 1:
`{
    "state": "ON",
    "color_temp": 37,
    "color": {
        "x": 0.701,
        "y": 0.299
    },
    "brightness": 255
}`

As the bulb again receives 2 color commands (one blue (127) and one red (37)), the bulb turns on while fading into blue, and when it's blue it will fade into red. That's really bad, visually. It should simply turn on while fading into red, nobody asked for blue.

Why are 2 messages sent to the bulb? Is this by design? And if not, is it an issue in Zigbee2MQTT or within Home Assistant?

**Comment by Koenkk** [comment]
To debug this further the debug log is required. Please annotate it like you did above.

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
