### ISSUE TITLE
[Wrong device]: Moes TV02 recognized as  TV01-ZB

### ISSUE THREAD

**Issue by flubshi** [Koenkk/zigbee2mqtt#24335]
### Link

https://moeshouse.com/products/zigbee-002-trv?variant=39876451336273

### Model

TV02

### Description

Thermostat radiator valve

### Vendor

Moes

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/TV02-Zigbee.png

### Database entry

```json
{"id":5,"type":"EndDevice","ieeeAddr":"0xe8e07efffe40e4e1","nwkAddr":33764,"manufId":4098,"manufName":"_TZE200_kds0pmmv","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"���.\u0011\u0003��.\u0011=��.\u0011���.\u0011\u0004��.\u0011\u000e��.\u0011�\u0017�.\u0011�!�.\u0012","65506":31,"65508":1,"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_kds0pmmv","powerSource":3,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":217189513},"lastSeen":1728930602346}
```

### Notes

I bought a Moes TV02 (ZTRV-ZX-TV02-MS) on [aliexpress](https://de.aliexpress.com/item/1005006801953307.html). The device is recognized by z2m as a `TV01-ZB`. As a consquence, the device links to the z2m docs of [Moes TV01-ZB](https://www.zigbee2mqtt.io/devices/TV01-ZB.html#moes-tv01-zb). 
The device looks the same as the [TV02-Zigbee](https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html) and the description on the device package also confirms this device ID.

![image](https://github.com/user-attachments/assets/3d34b851-6ba9-4779-96a0-0bc80cfe2289)

I would expected:
- the device is recognized as `TV02-Zigbee` instead of `TV01`
- and links to the [Tuya TV02-Zigbee](https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html) docs, shows the right picture.

![image](https://github.com/user-attachments/assets/7455ab4d-0937-4ec9-a6df-9b43530d96e3)

I found an old Github issue which shows the device `_TZE200_kds0pmmv` correctly recognized as `TV02-Zigbee`: https://github.com/Koenkk/zigbee2mqtt/issues/19296

*Thanks for developing the awesome open source tool zigbee2mqtt!* :heart:

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
