### ISSUE TITLE
E1744 with duplicated commands 

### ISSUE THREAD

**Issue by soloam** [Koenkk/zigbee2mqtt#2434]
I paired for the first time the Ikea E1744 (sonos dimmer). And it's sending duplicated commands on the click, double click and triple click. If I click once I receive 2 inputs on the mqtt with the same json. Also the dim sends a lot of duplicate inputs to a micro rotation! If I make a very small rotation I receive around 22 messages. 

Thank you

**Comment by Koenkk** [comment]
@ssiegel could you help with this?

**Comment by ssiegel** [comment]
I think Koenkk/zigbee-herdsman-converters#792 should fix this.

The move messages are are synthesized by the ictcg1 function (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L94) which should, as I understand it, generate one message every 200ms. I still see more messages than that, and I still see two rotate_stop at the end of the movement. I currently can't figure out what might cause the duplication. In the debug log there is exactly one message “Received Zigbee message from 'Ikea Symfonisk E1744', type 'commandMove', cluster 'genLevelCtrl', data '{"movemode":0,"rate":195}' from endpoint 1 with groupID 0” when starting the rotation and one message “Received Zigbee message from 'Ikea Symfonisk E1744', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID 0” when stopping it.

**Comment by Koenkk** [comment]
@ssiegel did you check against the latest zigbee2mqtt dev?

**Comment by soloam** [comment]
I can try the latest DEV, is this submitted to the dev?

**Comment by Koenkk** [comment]
yes

**Comment by soloam** [comment]
I tried to update to the lates dev, now I can't start zigbee2mqtt

coordeinator CC1352P-2

The detailed log 
`
DEBUG=* npm start

> zigbee2mqtt@1.7.1 start /opt/zigbee2mqtt
> node index.js

winston:create-logger Define prototype method for "error"
winston:create-logger Define prototype method for "warn"
winston:create-logger Define prototype method for "info"
winston:create-logger Define prototype method for "http"
winston:create-logger Define prototype method for "verbose"
winston:create-logger Define prototype method for "debug"
winston:create-logger Define prototype method for "silly"
winston:create-logger Define prototype method for "error"
winston:create-logger Define prototype method for "warn"
winston:create-logger Define prototype method for "info"
winston:create-logger Define prototype method for "http"
winston:create-logger Define prototype method for "verbose"
winston:create-logger Define prototype method for "debug"
winston:create-logger Define prototype method for "silly"
zigbee2mqtt:info  2019-12-06 20:12:19: Logging to console and directory: 'data/log'
winston:file written true false
zigbee2mqtt:debug 2019-12-06 20:12:22: Loaded state from file /opt/zigbee2mqtt/data/state.json
winston:file written true false
winston:file logged 72 info  2019-12-06 20:12:19: Logging to console and directory: 'data/log'

winston:file logged 155 debug 2019-12-06 20:12:22: Loaded state from file /opt/zigbee2mqtt/data/state.json

winston:file ENOENT ok data/log/log.txt
winston:file stat done: log.txt { size: 0 }
winston:file create stream start data/log/log.txt { flags: 'a' }
winston:file create stream ok data/log/log.txt
winston:file file open ok data/log/log.txt
zigbee2mqtt:info  2019-12-06 20:12:22: Starting zigbee2mqtt version 1.7.1+dev (commit #3320136)
winston:file written true false
zigbee2mqtt:info  2019-12-06 20:12:22: Starting zigbee-herdsman...
winston:file written true false
zigbee2mqtt:debug 2019-12-06 20:12:22: Using zigbee-herdsman with settings: '{"network":{"panID":6758,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"}}'
winston:file written true false
  serialport/bindings loading LinuxBinding +0ms
  serialport/stream .list +0ms
winston:file logged 84 info  2019-12-06 20:12:22: Starting zigbee2mqtt version 1.7.1+dev (commit #3320136)

winston:file logged 139 info  2019-12-06 20:12:22: Starting zigbee-herdsman...

winston:file logged 568 debug 2019-12-06 20:12:22: Using zigbee-herdsman with settings: '{"network":{"panID":6758,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"}}'

  zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter' +0ms
  zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6758,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json"}' +0ms
  zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":true,"autoOpen":false} +0ms
  serialport/stream opening path: /dev/ttyACM0 +1s
  serialport/binding-abstract open +0ms
  serialport/stream _read queueing _read for after open +20ms
  serialport/bindings/poller Creating poller +0ms
  serialport/stream opened path: /dev/ttyACM0 +21ms
  serialport/stream _read reading { start: 0, toRead: 65536 } +7ms
  serialport/binding-abstract read +56ms
  zigbee-herdsman:adapter:zStack:znp:log Serialport opened +96ms
  zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload +6ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239] +0ms
  serialport/stream _write 1 bytes of data +46ms
  serialport/binding-abstract write 1 bytes +50ms
  serialport/bindings/unixWrite Starting write 1 bytes offset 0 bytesToWrite 1 +0ms
  serialport/bindings/unixRead Starting read +0ms
  serialport/bindings/unixWrite write returned: wrote 1 bytes +29ms
  serialport/bindings/unixWrite Finished writing 1 bytes +10ms
  serialport/stream binding.write write finished +91ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +38ms
  serialport/bindings/poller Polling for "readable" +179ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - version - {} +0ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,2,35] +1s
  serialport/stream _write 5 bytes of data +1s
  serialport/binding-abstract write 5 bytes +1s
  serialport/bindings/unixWrite Starting write 5 bytes offset 0 bytesToWrite 5 +1s
  serialport/bindings/unixWrite write returned: wrote 5 bytes +8ms
  serialport/bindings/unixWrite Finished writing 5 bytes +3ms
  serialport/stream binding.write write finished +26ms
  serialport/bindings/poller received "readable" +1s
  serialport/binding-abstract read +36ms
  serialport/bindings/unixRead Starting read +1s
  serialport/bindings/unixRead Finished read 19 bytes +8ms
  serialport/stream binding.read finished { bytesRead: 19 } +33ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,97,2,2,1,2,7,1,130,23,52,1,0,255,255,255,255,202] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,97,2,2,1,2,7,1,130,23,52,1,0,255,255,255,255,202] +9ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 1 - 2 - [2,1,2,7,1,130,23,52,1,0,255,255,255,255] - 202 +11ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20191106} +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +47ms
  zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack3x0' ({"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20191106}) +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +222ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +189ms
  serialport/stream _write 8 bytes of data +129ms
  serialport/binding-abstract write 8 bytes +153ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +179ms
  serialport/stream _read reading { start: 19, toRead: 65517 } +20ms
  serialport/binding-abstract read +20ms
  serialport/bindings/unixRead Starting read +164ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +24ms
  serialport/bindings/unixWrite Finished writing 8 bytes +3ms
  serialport/stream binding.write write finished +24ms
  serialport/bindings/unixRead Finished read 8 bytes +22ms
  serialport/stream binding.read finished { bytesRead: 8 } +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62] +114ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62] +5ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62 +7ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}} +155ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +15ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +132ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +119ms
  serialport/stream _write 8 bytes of data +65ms
  serialport/binding-abstract write 8 bytes +99ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +88ms
  serialport/stream _read reading { start: 27, toRead: 65509 } +13ms
  serialport/binding-abstract read +14ms
  serialport/bindings/unixRead Starting read +94ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +23ms
  serialport/bindings/unixWrite Finished writing 8 bytes +3ms
  serialport/stream binding.write write finished +25ms
  serialport/bindings/unixRead Finished read 8 bytes +19ms
  serialport/stream binding.read finished { bytesRead: 8 } +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62] +85ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62] +6ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62 +4ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}} +109ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +12ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid +107ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}} +106ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,132,0,0,174] +106ms
  serialport/stream _write 8 bytes of data +57ms
  serialport/binding-abstract write 8 bytes +90ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +78ms
  serialport/stream _read reading { start: 35, toRead: 65501 } +13ms
  serialport/binding-abstract read +16ms
  serialport/bindings/unixRead Starting read +86ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +24ms
  serialport/bindings/unixWrite Finished writing 8 bytes +3ms
  serialport/stream binding.write write finished +26ms
  serialport/bindings/unixRead Finished read 11 bytes +21ms
  serialport/stream binding.read finished { bytesRead: 11 } +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,97,8,0,4,0,8,0,0,99] +84ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,97,8,0,4,0,8,0,0,99] +5ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 3 - 1 - 8 - [0,4,0,8,0,0] - 99 +7ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":4,"value":{"type":"Buffer","data":[0,8,0,0]}} +106ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +11ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid +106ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}} +102ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,99,0,0,73] +102ms
  serialport/stream _write 8 bytes of data +53ms
  serialport/binding-abstract write 8 bytes +88ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +76ms
  serialport/stream _read reading { start: 46, toRead: 65490 } +15ms
  serialport/binding-abstract read +13ms
  serialport/bindings/unixRead Starting read +81ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +23ms
  serialport/bindings/unixWrite Finished writing 8 bytes +3ms
  serialport/stream binding.write write finished +24ms
  serialport/bindings/unixRead Finished read 8 bytes +21ms
  serialport/stream binding.read finished { bytesRead: 8 } +11ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,0,107] +79ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,0,107] +7ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,0] - 107 +4ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[0]}} +101ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +12ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid +102ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":98,"configid":98,"len":16,"offset":0,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}} +102ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,98,0,0,72] +103ms
  serialport/stream _write 8 bytes of data +53ms
  serialport/binding-abstract write 8 bytes +89ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +77ms
  serialport/stream _read reading { start: 54, toRead: 65482 } +14ms
  serialport/binding-abstract read +14ms
  serialport/bindings/unixRead Starting read +83ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +23ms
  serialport/bindings/unixWrite Finished writing 8 bytes +4ms
  serialport/stream binding.write write finished +25ms
  serialport/bindings/unixRead Finished read 23 bytes +19ms
  serialport/stream binding.read finished { bytesRead: 23 } +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,8,0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,104] +79ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,104] +6ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 8 - [0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 104 +5ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}} +103ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +12ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is valid +102ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":131,"len":2,"offset":0,"value":{"type":"Buffer","data":[102,26]}} +128ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,131,0,0,169] +132ms
  serialport/stream _write 8 bytes of data +83ms
  serialport/binding-abstract write 8 bytes +122ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +114ms
  serialport/stream _read reading { start: 77, toRead: 65459 } +23ms
  serialport/binding-abstract read +23ms
  serialport/bindings/unixRead Starting read +130ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +32ms
  serialport/bindings/unixWrite Finished writing 8 bytes +11ms
  serialport/stream binding.write write finished +47ms
  serialport/bindings/unixRead Finished read 9 bytes +32ms
  serialport/stream binding.read finished { bytesRead: 9 } +18ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,4,97,8,0,2,102,26,19] +157ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,4,97,8,0,2,102,26,19] +13ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 4 - 3 - 1 - 8 - [0,2,102,26] - 19 +7ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":2,"value":{"type":"Buffer","data":[102,26]}} +203ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +27ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'panID' is valid +216ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":45,"len":8,"offset":0,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}} +201ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,45,0,0,7] +220ms
  serialport/stream _write 8 bytes of data +136ms
  serialport/binding-abstract write 8 bytes +205ms
  serialport/bindings/unixWrite Starting write 8 bytes offset 0 bytesToWrite 8 +183ms
  serialport/stream _read reading { start: 86, toRead: 65450 } +39ms
  serialport/binding-abstract read +40ms
  serialport/bindings/unixRead Starting read +217ms
  serialport/bindings/unixWrite write returned: wrote 8 bytes +58ms
  serialport/bindings/unixWrite Finished writing 8 bytes +5ms
  serialport/stream binding.write write finished +47ms
  serialport/bindings/unixRead Finished read 15 bytes +23ms
  serialport/stream binding.read finished { bytesRead: 15 } +9ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,10,97,8,0,8,221,221,221,221,221,221,221,221,107] +177ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,8,0,8,221,221,221,221,221,221,221,221,107] +5ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 10 - 3 - 1 - 8 - [0,8,221,221,221,221,221,221,221,221] - 107 +5ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":8,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}} +198ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +10ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'extendedPanID' is valid +184ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> UTIL - getDeviceInfo - {} +174ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,39,0,39] +149ms
  serialport/stream _write 5 bytes of data +50ms
  serialport/binding-abstract write 5 bytes +98ms
  serialport/bindings/unixWrite Starting write 5 bytes offset 0 bytesToWrite 5 +73ms
  serialport/stream _read reading { start: 101, toRead: 65435 } +15ms
  serialport/binding-abstract read +13ms
  serialport/bindings/unixRead Starting read +77ms
  serialport/bindings/unixWrite write returned: wrote 5 bytes +19ms
  serialport/bindings/unixWrite Finished writing 5 bytes +5ms
  serialport/stream binding.write write finished +25ms
  serialport/bindings/unixRead Finished read 19 bytes +22ms
  serialport/stream binding.read finished { bytesRead: 19 } +8ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,103,0,0,67,11,166,28,0,75,18,0,254,255,7,0,0,196] +77ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,67,11,166,28,0,75,18,0,254,255,7,0,0,196] +6ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 7 - 0 - [0,67,11,166,28,0,75,18,0,254,255,7,0,0] - 196 +5ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b001ca60b43","shortaddr":65534,"devicetype":7,"devicestate":0,"numassocdevices":0,"assocdeviceslist":[]} +108ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +17ms
  zigbee-herdsman:adapter:zStack:startZnp Start ZNP as coordinator... +107ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - startupFromApp - {"startdelay":100} +106ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,37,64,100,0,3] +106ms
  serialport/stream _write 7 bytes of data +58ms
  serialport/binding-abstract write 7 bytes +93ms
  serialport/bindings/unixWrite Starting write 7 bytes offset 0 bytesToWrite 7 +81ms
  serialport/stream _read reading { start: 120, toRead: 65416 } +14ms
  serialport/binding-abstract read +12ms
  serialport/bindings/unixRead Starting read +84ms
  serialport/bindings/unixWrite write returned: wrote 7 bytes +19ms
  serialport/bindings/unixWrite Finished writing 7 bytes +5ms
  serialport/stream binding.write write finished +23ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +20ms
  serialport/bindings/poller Polling for "readable" +1s
  serialport/bindings/poller received "readable" +4s
  serialport/binding-abstract read +4s
  serialport/bindings/unixRead Starting read +4s
  serialport/bindings/unixRead Finished read 14 bytes +12ms
  serialport/stream binding.read finished { bytesRead: 14 } +4s
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,64,0,36,254,3,79,128,1,2,4,203] +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,64,0,36,254,3,79,128,1,2,4,203] +11ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 64 - [0] - 36 +6ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - startupFromApp - {"status":0} +4s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,1,2,4,203] +19ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [1,2,4] - 203 +4ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":1} +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +13ms
  serialport/stream _read reading { start: 134, toRead: 65402 } +82ms
  serialport/binding-abstract read +123ms
  serialport/bindings/unixRead Starting read +103ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +13ms
  serialport/bindings/poller Polling for "readable" +160ms
  serialport/bindings/poller received "readable" +154ms
  serialport/binding-abstract read +180ms
  serialport/bindings/unixRead Starting read +163ms
  serialport/bindings/unixRead Finished read 6 bytes +3ms
  serialport/stream binding.read finished { bytesRead: 6 } +195ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140] +213ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140] +3ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140 +3ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8} +230ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +7ms
  serialport/stream _read reading { start: 140, toRead: 65396 } +21ms
  serialport/binding-abstract read +32ms
  serialport/bindings/unixRead Starting read +29ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +4ms
  serialport/bindings/poller Polling for "readable" +41ms
  serialport/bindings/poller received "readable" +537ms
  serialport/binding-abstract read +547ms
  serialport/bindings/unixRead Starting read +543ms
  serialport/bindings/unixRead Finished read 22 bytes +5ms
  serialport/stream binding.read finished { bytesRead: 22 } +563ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,0,132,254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198] +576ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,0,132,254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198] +8ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [0] - 132 +8ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":0} +603ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198] +16ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198 +9ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8} +24ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198] +18ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198 +14ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8} +29ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +12ms
  serialport/stream _read reading { start: 162, toRead: 65374 } +104ms
  serialport/binding-abstract read +123ms
  serialport/bindings/unixRead Starting read +126ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +6ms
  serialport/bindings/poller Polling for "readable" +148ms
zigbee2mqtt:error 2019-12-06 20:13:27: Error while starting zigbee-herdsman
winston:file written true false
zigbee2mqtt:error 2019-12-06 20:13:27: Failed to start zigbee
winston:file written true false
zigbee2mqtt:error 2019-12-06 20:13:27: Exiting...
winston:file written true false
zigbee2mqtt:error 2019-12-06 20:13:27: Error: AREQ - ZDO - stateChangeInd after 60000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
winston:file written true false
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.7.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-06T20_13_27_712Z-debug.log


`

**Comment by soloam** [comment]
I rolled back to master branch and all is back online!

**Comment by soloam** [comment]
Ok I tested out the new "3320136" commit! The problem now is different.

MQTT from 90º rotation none stop, I think that it should be on rotate_left and one rotate_stop at the end. A none stopping rotation produced several rotate_stop.

```
{"action":"rotate_left","linkquality":0}
{"action":"rotate_left","rate":195,"linkquality":0}
{"action":"rotate_left","linkquality":0}
{"action":"rotate_left","rate":195,"linkquality":0}
{"action":"rotate_left","linkquality":0,"brightness":127}
{"action":"rotate_left","linkquality":0,"brightness":107}
{"action":"rotate_stop","brightness":92,"linkquality":0}
{"action":"rotate_stop","brightness":92,"linkquality":0}
{"action":"rotate_stop","brightness":92,"linkquality":0}
{"action":"rotate_stop","brightness":92,"linkquality":0}
```

A single click in the button generates 2 messages
```
{"action":"play_pause","linkquality":57}
{"action":"play_pause","linkquality":57}
```

Double click in the button generates 2 messages
```
{"action":"skip_forward","step_size":1,"transition_time":0,"linkquality":39}
{"action":"skip_forward","step_size":1,"transition_time":0,"linkquality":39}
```

Thank you

**Comment by Koenkk** [comment]
There are also some additional configuration recommendation, see https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/devices/E1744.md#recommendation (but for this you need to be on the dev branch).

**Comment by soloam** [comment]
Tested the config, and that solves the problem of duplicated outputs! A lot better, thank you! For me, I only have one problem with this, don't know if it's a limitation from the hardware part! The button, on rotate sends rotation followed by a stop, even if I keep spinning the wheel without stopping! This is a problem because I can't detect the speed that I'm spinning, if a I spin very fast I get only one rotation and one stop! I could use the brightness property to detect, but I would like the rotation to be relative to the actual state of the lamp, the bigness on the wheel is relative to the button! If my lamp is at 50% and I spin it right, I what to go up from 50%, and not get the brightness from the button to send it to the lamp! I could detect the difference from the bugging of the bigness of the wheel and the end, and calculate the delta, to increase or decrease that value from the lamp, but if the wheel is at 1 and I go down, or if it's 255 and I go up, the value is always the min or max!

Thank you for your hard work!

**Comment by elektrikal80** [comment]
Hello all, 
I am new here and a beginner,
Mij problem is : I have 2 traverdi ikea led's , one LED1836G9 and a LED1842G3, my system runs on a rasperry pi and cc2531 sniffer  with mqtt and zigbeemqtt with domoticz  all installe with the tutorial from [](https://github.com/Koenkk/zigbee2mqtt), now i can add the led 1842G3 in domoticz but the other led wil not connect and in domoticz  in the log file can i see strange things:

Received available devices list from bridge
Device **LED1842G3** 0x14b457fffe44d4ad (0x14b457fffe44d4ad)
Received available devices list from bridge
Device **LED1842G3** 0x14b457fffe44d4ad (0x14b457fffe44d4ad)
Device 0x14b457fffe2e953a (0x14b457fffe2e953a) doesn't have "model" attribute, skipped

the led that alreddy runs in domoticz is LED 1842G3, 
the led wich i want to add is 1836G9. nd not 1842G3
Hope that anyone can help me
