### ISSUE TITLE
[Wrong device]: SMLIGHT SLZB-06 in "router mode" detects as "ti.router" from Vendor = Custom devices (DiY)

### ISSUE THREAD

**Issue by dktrekkie** [Koenkk/zigbee2mqtt#24406]
### Link

https://www.zigbee2mqtt.io/devices/SLZB-06.html

### Model

SLZB-06

### Description

That the router is detected as SLZB-06 and not Custom devices (DiY) ti.router

### Vendor

SMLIGHT

### Picture (link)

https://www.zigbee2mqtt.io/images/devices/SLZB-06.png

### Database entry

{     "id": 99,     "type": "Router",     "ieeeAddr": "0x00124b002f8e52c8",     "nwkAddr": 46413,     "manufId": 0,     "manufName": "TexasInstruments",     "powerSource": "Mains (single phase)",     "modelId": "ti.router",     "epList": [8, 242],     "endpoints": {         "8": {             "profId": 260,             "epId": 8,             "devId": 255,             "inClusterList": [0, 3],             "outClusterList": [0],             "clusters": {                 "genBasic": {                     "attributes": {}                 }             },             "binds": [{                     "cluster": 0,                     "type": "endpoint",                     "deviceIeeeAddress": "0x00124b0026b88734",                     "endpointID": 1                 }             ],             "configuredReportings": [{                     "cluster": 0,                     "attrId": 0,                     "minRepIntval": 0,                     "maxRepIntval": 3600,                     "repChange": 0                 }             ],             "meta": {}         },         "242": {             "profId": 41440,             "epId": 242,             "devId": 97,             "inClusterList": [],             "outClusterList": [33],             "clusters": {},             "binds": [],             "configuredReportings": [],             "meta": {}         }     },     "hwVersion": 1,     "swBuildId": "20221102",     "zclVersion": 3,     "interviewCompleted": true,     "meta": {         "configured": -934152608     },     "lastSeen": 1729345363575 }

### Notes

I'm pretty sure that at one point this device was detected correctly as the SMLIGHT SLZB-06, But I had a faulty unit, and ended up removing the router and adding it again later. At that time it detected as the "ti.router" instead.

I'm unsure if this is "really an issue", and maybe it still works fine detected as this model, but I just find it odd that I does not report as the correct device and vendor.

I am using another SMLIGHT SLZB-06 as my coordinator BTW.

**Comment by geralltgriffiths** [comment]
I also have this issue and wondered if anything had been done to resolve it. While not immediately important, I wondered if it points to a larger issue that may cause issues elsewhere.  I'm using SMLIGHT SLZB-06 as both coordinator and as router in my set-up.

**Comment by andrei-lazarov** [comment]
Not an issue. Detection is only cosmetic in this case. It depends on which firmware the device is running.
