### ISSUE TITLE
"Add install code is not supported" with Conbee II and a BOSCH Twinguard Smoke Alarm

### ISSUE THREAD

**Issue by pax85** [Koenkk/zigbee2mqtt#24403]
### What happened?

When scanning the Install Code (QR Code) from the back of the BOSCH Twinguard and pasting into ZigBee2Mqtt > Tools > Add Install Code im receiving an error

`error 2024-10-19 11:07:24z2m: Request 'zigbee2mqtt/bridge/request/install_code/add' failed with error: 'Add install code is not supported'
info 2024-10-19 11:07:24z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/install_code/add', payload '{"data":{},"error":"Add install code is not supported","status":"error","transaction":"ja8aa-6"}'`

I've tried the shorter Install Code next to the QR Code, but this length is unsupported
`error 2024-10-19 10:48:30z2m: Request 'zigbee2mqtt/bridge/request/install_code/add' failed with error: 'Unsupported install code, got 26 chars, expected 95 or 91'
info 2024-10-19 10:48:30z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/install_code/add', payload '{"data":{},"error":"Unsupported install code, got 26 chars, expected 95 or 91","status":"error","transaction":"ja8aa-1"}'`

Any idea what the issue seems to be? Until now I've only used ZigBee for IKEA and other Lights successfully. This my first device of another category. 

Zigbee2MQTT version
[1.40.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.2) commit: [e06848d](https://github.com/Koenkk/zigbee2mqtt/commit/e06848d)
Coordinator type
ConBee2/RaspBee2
Coordinator revision
0x26680700
Frontend version
0.7.4
zigbee-herdsman-converters version
20.21.0
zigbee-herdsman version
2.1.3

### What did you expect to happen?

Expected the Device to enter Pairing Mode

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

0x26680700

### Adapter

ConBee2/RaspBee2

### Setup

Docker Container in Unraid

**Comment by Koenkk** [comment]
Conbee indeed doesn't support install codes, see https://github.com/Koenkk/zigbee2mqtt/issues/17492
