### ISSUE TITLE
[Feature request]: More descriptive confirmation prompt

### ISSUE THREAD

**Issue by dajomas** [Koenkk/zigbee2mqtt#24459]
### Is your feature request related to a problem? Please describe

No the request is not related to a problem

### Describe the solution you'd like

The only thing the confirmation prompt shows is the fact that it is a confirmation prompt and the question: "Are you sure?"

It would be really helpful if the prompt shows the action you want to perform 

for instance:

- Are you sure you want to update "Dining Table bulb 2"
- Are you sure you want to remove "Dimmer Switch Living Room"

### Describe alternatives you've considered

Not really

### Additional context

![image](https://github.com/user-attachments/assets/1b863dbf-6157-49e5-83f8-709152b7bdb1)

This prompt doesn't really mean anything and would be more useful when it said:
"Are you sure you want to update 'Aqara Smart Plug 004 - Heater'"

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
