### ISSUE TITLE
IKEA E2001/E2002 STYRBAR does not expose a action entity in home assistant

### ISSUE THREAD

**Issue by Sabering1** [Koenkk/zigbee2mqtt#24470]
### What happened?

After pairing the device it exposes update settings to home assistant but no action entity, i can see the action change in the Z2M but not in HA rendering the device useless, it worked fine in ZHA
I tried repairing, updating to latest firmware, reconfiguring, restarting HA Z2M and MQTT client and nothing worked

### What did you expect to happen?

Exposes the action entity just like the docs would say it should

### How to reproduce it (minimal and precise)

Pair the device, and check the device in HA it wont be there

### Zigbee2MQTT version

1.40.1 commit: 403d3c0

### Adapter firmware version

20240710

### Adapter

SLZB-06 SMLIGHT SLZB

### Setup

Docker

**Comment by Sabering1** [comment]
Okay i got that sorted out but there does not seem to a be any blueprints for this, all that i found still use the legacy action trigger. So i went and reenabled “Home Assistant legacy entity attributes” to fix it for now
This exposes the legacy action button.
If there are any blueprints that work with this "new" version please let me now.

**Comment by ahll19** [comment]
Was this ever actually fixed? I have this exact issue, and re-enabling legacy attributes does not seem to be the correct way to handle this.

My current workaround is subscribing to the topic in Home Assistant

**Comment by andrei-lazarov** [comment]
Add Trigger -> Device -> Styrbar, like in the screenshot

Or use experimental events

<img width="807" height="83" alt="Image" src="https://github.com/user-attachments/assets/8800f0d9-f60b-42f0-9053-c09ef19fa865" />
