### ISSUE TITLE
[New device support]: Phillips Hue Centris (4 spots white)

### ISSUE THREAD

**Issue by frest-de** [Koenkk/zigbee2mqtt#24485]
### Link

https://www.amazon.com/-/de/dp/B0CYZDM8GM

### Database entry

{"id":103,"type":"Router","ieeeAddr":"0x001788010e7fab62","nwkAddr":65273,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"929003808901_01","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genOnOff":{"attributes":{"onOff":0}},"genBasic":{"attributes":{"hwVersion":0,"zclVersion":2}},"lightingColorCtrl":{"attributes":{"colorCapabilities":31,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"colorMode":2,"currentX":26599,"currentY":25697,"colorTemperature":286}},"genLevelCtrl":{"attributes":{"currentLevel":157}}},"binds":[],"configuredReportings":[],"meta":{"onLevelSupported":false}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20210305","swBuildId":"1.82.10","zclVersion":2,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1729883751097}

### Zigbee2MQTT version

1.40.2

### Comments

Similar to the issue https://github.com/Koenkk/zigbee2mqtt/discussions/12173 and https://github.com/Koenkk/zigbee2mqtt/issues/20215, the model number seems to have changed.

Its:
929003808901_01
929003808901_02
929003808901_03
929003808901_04
929003808901_05

929003808901_02 - 929003808901_05 are GU10 White and color ambiance bulb, just with individual model numbers.

### External definition

```shell
unclear
```

### What does/doesn't work with the external definition?

unclear

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `929003808901.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by frest-de** [comment]
Thanks for your work!
I added the image.
