### ISSUE TITLE
Send Availability Topic State on device pair

### ISSUE THREAD

**Issue by SeLLeRoNe** [Koenkk/zigbee2mqtt#2452]
# Bug Report
## What happened
Everytime I need to re-pair a device, the availability topic is not updated, therefore those devices might not work in HA, this happen until I restart z2m, that way the availability topic is published and everyone is happy :)

## What did you expect to happen
On device pair, send the availability topic message.

## How to reproduce it (minimal and precise)
Just enable availability topic and pair a device.

## Debug Info
zigbee2mqtt version:  1.7.1+dev (commit #7d1635a)
CC253X firmware version: Stack 3 - 20190425

**Comment by Koenkk** [comment]
Fixed in latest dev, thanks!
