### ISSUE TITLE
[New device support]: Model TS0601_TZE204_wktrysab Tuya 8-gang wall touch switch board 

### ISSUE THREAD

**Issue by rhakbari** [Koenkk/zigbee2mqtt#24527]
### Link

https://www.aliexpress.com/item/1005005847728198.html?spm=a2g0o.order_list.order_list_main.22.27c11802GJYCK7

https://melery.com/products/melery-zigbee-interruptor-smart-light-switch-wall-touch-glass-panel-alexa-voice-control-google-home-signal-reapter-hub-required?sku=18065590718895405252651560

### Database entry

{   "FriendlyName": "Touch Switch board",   "Description": "Last seen",   "Availability": "Disabled",   "DeviceType": "Router",   "ZigbeeModel": "TS0601",   "ZigbeeManufacturer": "_TZE204_wktrysab",   "SupportStatus": "Not supported",   "IEEEAddress": "0xa4c138766e42ced8",   "NetworkAddress": "0x9837 / 38967",   "Power": "Interview completed",   "InterviewCompleted": true }

### Zigbee2MQTT version

1.40.2 

### Comments

Hi, 

I paired this 8-gang touch switch board on zigbee2mqtt but it is being shown unsupported in the listing and I am unable to operate the switches by zigbee2mqtt or by home assistant as I am using Tasmota Ewelink wired Zigbee gateway with it. 

Please help me with this issue .

Thanks

### External definition

Below file is written by me and is working as I have personally tested it

```shell
const tuya = require('zigbee-herdsman-converters/lib/tuya');

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE204_wktrysab',
        },
    ],
    model: 'TS0601_8_way_switch',
    vendor: 'Tuya',
    description: '8 way switch',
    fromZigbee: [tuya.fz.datapoints],
    toZigbee: [tuya.tz.datapoints],
    onEvent: tuya.onEventSetTime,
    configure: tuya.configureMagicPacket,
    exposes: [
        ...Array.from({length: 8}, (_, i) => tuya.exposes.switch().withEndpoint(`l${i + 1}`))
    ],
    endpoint: (device) => {
        return {
            'l1': 1, 'l2': 1, 'l3': 1, 'l4': 1,
            'l5': 1, 'l6': 1, 'l7': 1, 'l8': 1
        };
    },
    meta: {
        multiEndpoint: true,
        tuyaDatapoints: [
            [1, 'state_l1', tuya.valueConverter.onOff],
            [2, 'state_l2', tuya.valueConverter.onOff],
            [3, 'state_l3', tuya.valueConverter.onOff],
            [4, 'state_l4', tuya.valueConverter.onOff],
            [5, 'state_l5', tuya.valueConverter.onOff],
            [6, 'state_l6', tuya.valueConverter.onOff],
            [0x65, 'state_l7', tuya.valueConverter.onOff],
            [0x66, 'state_l8', tuya.valueConverter.onOff],
            [0x67, 'null', null],
            [0x68, 'null', null],
            [0x69, 'null', null],
            [0x6A, 'null', null],
            [0x6B, 'null', null],
            [0x6C, 'null', null],
            [0x6D, 'null', null],
            [0x6E, 'null', null],
            [0xB6, 'null', null],
            [0xB7, 'null', null],
            [0xB8, 'null', null],
            [0xB9, 'null', null],
            [0xBA, 'null', null],
            [0xBB, 'null', null],
            [0xBC, 'null', null],
            [0xBD, 'null', null],
        ],
    },
};

module.exports = definition;
```

**Comment by rhakbari** [comment]
I have contributed to the repo and added the support for the mentioned device with PR [#8224](https://github.com/Koenkk/zigbee-herdsman-converters/issues/8224)

**Comment by alisian1992-cmyk** [comment]
hi i bought the same device from the same AliExpress store but a 6 gang, you think this would work for me?

export default {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_cduqh1l0',
    description: 'Automatically generated 

I'm new to this and I've been trying to make it work for days now, any help would be appreciated.

https://www.aliexpress.com/item/1005005898017809.html?spm=a2g0o.order_list.order_list_main.22.68eb1802ixtSfy
its not advertised as a tuya device btw.
