### ISSUE TITLE
[Wrong device]: Phillips Hue FR Plug 9290022407 recognized as 046677552343

### ISSUE THREAD

**Issue by ALaDoffe** [Koenkk/zigbee2mqtt#24530]
### Link

https://www.assets.signify.com/is/content/PhilipsLighting/Assets/signify/global/20211028-Philips-Hue-Smart-Plug.pdf

### Model

9290022407

### Description

Hue Smart Plug

### Vendor

Philips

### Picture (link)

https://www.assets.signify.com/is/image/Signify/8718699689322_929002240701_p0-RTP?wid=1500&hei=1125&qlt=82

### Database entry

{"id":25,"type":"Router","ieeeAddr":"0x00178801080508ca","nwkAddr":43184,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LOM002","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":266,"inClusterList":[0,3,4,5,6,8,4096,64515],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"LOM002","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":8,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20240628","swBuildId":"1.116.5","appProfileVersion":0}},"genOnOff":{"attributes":{"onOff":0}},"manuSpecificPhilips2":{"attributes":{"state":{"type":"Buffer","data":[1,0,0]}}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b002291d5a3","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1,"manufacturerCode":null},{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20240628","swBuildId":"1.116.5","zclVersion":8,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1730196551618}

### Notes

The device is fully functional, but the picture is wrong and the most important is, i don't know if the firmware of 046677552343 is compatible with 9290022407 as Z2M offers me an OTA Update.

**Comment by Koenkk** [comment]
Fixed! It's only a cosmetic issue so you can upgrade safely.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
