### ISSUE TITLE
[New device support]: Philips Hue Datura - Big

### ISSUE THREAD

**Issue by markuswebert** [Koenkk/zigbee2mqtt#24540]
### Link

https://www.philips-hue.com/nl-be/p/hue-white-and-color-ambiance-datura-plafondlamp-groot/8720169277557

### Database entry

{   "modelZigbee": "929003736101_01",   "type": "Router",   "nwk": 55716,   "manuf_id": 4107,   "manufacturer": "Signify Netherlands B.V.",   "power": "Mains (single phase)",   "app_version": 2,   "hard_version": 0,   "zcl_version": 2,   "stack_version": 1,   "date_code": "20210305",   "build": "1.82.10",   "interviewed": true,   "configured": false,   "endpoints": [     {       "id": 11,       "profile": 260,       "input_clusters": [         {"id": "genBasic", "index": 0},         {"id": "genIdentify", "index": 3},         {"id": "genGroups", "index": 4},         {"id": "genScenes", "index": 5},         {"id": "genOnOff", "index": 6},         {"id": "genLevelCtrl", "index": 8},         {"id": "touchlink", "index": 4096},         {"id": "lightingColorCtrl", "index": 768},         {"id": "manuSpecificLegrandDevices", "index": 64513}       ],       "output_clusters": []     },     {       "id": 242,       "profile": 41440,       "input_clusters": [],       "output_clusters": [         {"id": "genOta", "index": 25},         {"id": "greenPower", "index": 33}       ]     }   ] },  {   "modelZigbee": "929003736101_02",   "type": "Router",   "nwk": 48689,   "manuf_id": 4107,   "manufacturer": "Signify Netherlands B.V.",   "power": "Mains (single phase)",   "app_version": 2,   "hard_version": 0,   "zcl_version": 2,   "stack_version": 1,   "date_code": "20210305",   "build": "1.82.10",   "interviewed": true,   "configured": false,   "endpoints": [     {       "id": 11,       "profile": 260,       "input_clusters": [         {"id": "genBasic", "index": 0},         {"id": "genIdentify", "index": 3},         {"id": "genGroups", "index": 4},         {"id": "genScenes", "index": 5},         {"id": "genOnOff", "index": 6},         {"id": "genLevelCtrl", "index": 8},         {"id": "touchlink", "index": 4096},         {"id": "lightingColorCtrl", "index": 768},         {"id": "manuSpecificLegrandDevices", "index": 64513}       ],       "output_clusters": []     },     {       "id": 242,       "profile": 41440,       "input_clusters": [],       "output_clusters": [         {"id": "genOta", "index": 25},         {"id": "greenPower", "index": 33}       ]     }   ] }

### Zigbee2MQTT version

-

### Comments

I think that it should be nearly the same like the small model added here https://github.com/Koenkk/zigbee2mqtt/issues/23831. The ZigBee models are 929003736101_01 and 929003736101_02. The database entry is not really extracted from the database.db but I created a json like structure from the iobroker.zigbee, information. Hope that helps!

### External definition

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['929003736101_01','929003736101_02'],
    model: '929003736101',
    vendor: 'Philips',
    description: 'Hue Datura',
    extend: [philipsLight({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"],"enhancedHue":true}})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Cannot test it unfortunately but I will try as soon as it ends up in iobroker.zigbee

**Comment by Koenkk** [comment]
Added, thanks!

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `929003736101.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))

**Comment by markuswebert** [comment]
Great, thank you! Will submit a picture, maybe I can use the one already added for the smaller version since they look identical (besides the size).

**Comment by markuswebert** [comment]
Thanks for merging! Wondered if everything is ok with my PR? Datura small page seems fine https://www.zigbee2mqtt.io/devices/929003736201.html, changes are applied but the Datura big seems incomplete https://www.zigbee2mqtt.io/devices/929003736101.html even if all GitHub Actions run successfully. Thanks!
