### ISSUE TITLE
[New device support]: Illuminance sensor _TS0222_TZ3000_hy6ncvmw

### ISSUE THREAD

**Issue by dimacoupe** [Koenkk/zigbee2mqtt#24577]
### Link

https://www.aliexpress.com/item/1005007877339487.html?spm=a2g0o.order_list.order_list_main.25.2ac31802RuRKVb

### Database entry

{"id":87,"type":"EndDevice","ieeeAddr":"0xa4c138e8b6628462","nwkAddr":35979,"manufId":4417,"manufName":"_TZ3000_hy6ncvmw","powerSource":"Battery","modelId":"TS0222","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":262,"inClusterList":[1,3,1026,1029,1024,1280,0],"outClusterList":[3,25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0222","manufacturerName":"_TZ3000_hy6ncvmw","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":7783}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200,"batteryVoltage":30}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0030e50aea","zoneState":1}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0030e50aea","endpointID":1},{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b0030e50aea","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10},{"cluster":1024,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":5}],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1730465890424}

### Zigbee2MQTT version

 1.41.0-1

### Comments

Bought new illuminance sensor never seen before.

![image](https://github.com/user-attachments/assets/7b645e04-bf9d-4532-ba56-bc3a64dff021)
![image](https://github.com/user-attachments/assets/8e41d94a-55c7-4b79-b9d6-a19cab2f708b)

### External definition

```shell
const {battery, illuminance} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
fingerprint: [
        {
            modelID: 'TS0222',
            manufacturerName: '_TZ3000_hy6ncvmw',
        },
    ],
    
    model: 'TS0222',
    vendor: 'Tuya',
    description: 'Lighting sensor',
    extend: [battery(), illuminance()],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

works 👌

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
