### ISSUE TITLE
[New device support]: philips millisikin with new model number

### ISSUE THREAD

**Issue by max-himself** [Koenkk/zigbee2mqtt#24599]
### Link

https://www.zigbee2mqtt.io/devices/929003047101.html

### Database entry

Dont know how to get it

### Zigbee2MQTT version

1.41.1

### Comments

I have several boxes of philips millsikin, but with a different model number then the ones in the list ofsupported devices.

in the bundle of three the model numbers are
[929003811101_01]
[929003811101_02]
[929003811101_03]

the single lamps have the model number
[929003811001]

the devices work out of the box, without any issues. They even get a firmware-update. But they are shown as not supported.

<img width="820" alt="image" src="https://github.com/user-attachments/assets/0b9c5d47-7e8b-43e7-b98e-a4389dffbf3d">

### External definition

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['929003811101_01'],
    model: '929003811101_01',
    vendor: 'Signify Netherlands B.V.',
    description: 'Automatically generated definition',
    extend: [philipsLight({"colorTemp":{"range":[153,454]}})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Everything seems to work - brightnes, color temperature, state etc.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
