### ISSUE TITLE
Patch for IKEA Bulbs to remove warnings

### ISSUE THREAD

**Issue by Wuppi68** [Koenkk/zigbee2mqtt#2460]
a diff for IKEA bulbs to blank out annoying messages

debug 2019-12-03T21:21:36: No converter available for 'LED1624G9' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1}'
debug 2019-12-03T21:21:38: No converter available for 'LED1546G12' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1}'

diff --git a/devices.js b/devices.js
index cf2d8e7..3e8e578 100755
--- a/devices.js
+++ b/devices.js
@@ -830,6 +830,7 @@ const devices = [
         vendor: 'IKEA',
         description: 'TRADFRI LED bulb E26/E27 950 lumen, dimmable, white spectrum, clear',
         extend: generic.light_onoff_brightness_colortemp,
+       fromZigbee:[fz.ignore_basic_report],
     },
     {
         zigbeeModel: ['TRADFRI bulb E27 opal 1000lm', 'TRADFRI bulb E27 W opal 1000lm'],
@@ -897,6 +898,7 @@ const devices = [
         vendor: 'IKEA',
         description: 'TRADFRI LED bulb E14/E26/E27 600 lumen, dimmable, color, opal white',
         extend: generic.light_onoff_brightness_colorxy,
+       fromZigbee:[fz.ignore_basic_report],
     },
     {
         zigbeeModel: [

**Comment by Koenkk** [comment]
Added, thanks!
