### ISSUE TITLE
Working Motion Sensors detected as Leak Detectors since 1.41.0

### ISSUE THREAD

**Issue by senrabyar** [Koenkk/zigbee2mqtt#24615]
### What happened?

I have a set of 4 Aubess Contact sensors which have been correctly identified and work fine until the release of 1.41.0

### What did you expect to happen?

to be detected as Contact

### How to reproduce it (minimal and precise)

problem is evident immediately on pairing ...

![image](https://github.com/user-attachments/assets/80989790-a205-4a15-9c0f-8b5f878ff148)
![image](https://github.com/user-attachments/assets/a93d1520-f11c-4728-9144-08ea3ccb7779)

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20210708

### Adapter

zStack3x0

### Setup

RPi5

**Comment by senrabyar** [comment]
Sorry it's late - perhaps I'm too tired - the devices are actually motion sensors not contact sensors - indeed they are listed by Z2M as SNZB-03 
Here's how some of them appear in HA
![image](https://github.com/user-attachments/assets/3b22d238-dfe2-4ecd-b72f-40819f226bb7)

**Comment by sqorpo** [comment]
I have the same issue. I think it was fixed in the dev build. I'll have to wait until it gets pushed to the home assistant add-on. until then I have lights controlled by "leak sensors" I guess..

**Comment by senrabyar** [comment]
Ahh but some of my lights do flash when my actual leak sensors are working.    No worries here being downstairs whilst the bath upstairs fills !

**Comment by NicCarlos** [comment]
Same problem with Tuya Motion Sensor ZMS-102.

**Comment by Koenkk** [comment]
Already fixed in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)!
