### ISSUE TITLE
Tuya TS0601_soil_3 battery state is 60% when full.

### ISSUE THREAD

**Issue by Jurgen-DOUCHY** [Koenkk/zigbee2mqtt#24611]
### What happened?

When placing new alkaline batteries in the device, it only reports 60% battery.
The batteries are brand new and 1.55V, so it should be full.
I tried with different batteries.

### What did you expect to happen?

Battery should be 100%

### How to reproduce it (minimal and precise)

new alkaline batteries and device reports 60%

### Zigbee2MQTT version

1.41.0 commit: unknown

### Adapter firmware version

20221226

### Adapter

usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Homeassistant on Rasberry PI 4, 

### Debug log

state:
{
    "battery": 60,
    "battery_state": "medium",
    "last_seen": "2024-11-02T21:06:57.568Z",
    "linkquality": 163,
    "soil_moisture": 73,
    "temperature": 20.3,
    "temperature_unit": "celsius"
}

**Comment by mrmaximas** [comment]
You need to wait for few next battery updates

**Comment by mrmaximas** [comment]
> nope, 3 days later, still 60%

have you tried to instal drained batteries?

**Comment by mrmaximas** [comment]
> I did, vas 6%

have you tried to connect this sensor to regular tuya hub?

**Comment by naitsimp** [comment]
Mine also shows 60% with new alkaline batteries.
I also have no hub.

**Comment by mrmaximas** [comment]
I think it's zigbee herdsman converter issue
@Koenkk please pay attention. thanks!

**Comment by RubenKelevra** [comment]
I think the converter reads the voltage and expects that this is a 3 V Lithium-Ion battery, like the CR2023 coin batteries.

**Comment by RubenKelevra** [comment]
Noop, I was wrong. The number is straight reported through from the device itself. So it looks like a firmware bug, where they changed them from 3 V Lithium-ion to accepting triple A batteries as pair and forgot to change the calibration of what 100% is.

**Comment by RubenKelevra** [comment]
Added a fix for this scaling issue.

**Comment by mafr95** [comment]
I use over 10 of the TS0601_soil_3, all with brand new batteries and each sensor shows me a maximum battery level of 50 percent. 

I am using the latest Zigbee2MQTT version 2.1.0 and the Zigbee Herdsman converter version 21.27.1. 

The problem should actually have been fixed with converter version 21.3.0. Unfortunately not for me.

Any ideas? Am I doing something wrong?

**Comment by RubenKelevra** [comment]
@mrmaximas I read the message, but without better calibration data provided this cannot be improved.

We need the maximum and minimum voltage reported by this device for a full or empty battery. The current calibration report is just based on what was provided by @Jurgen-DOUCHY.

**Comment by mrmaximas** [comment]
@mafr95 p.p.a.!

**Comment by tdm98-ai** [comment]
Seems that the "humidity" and "battery level" values are mixed up: https://github.com/Koenkk/zigbee2mqtt/issues/27346
