### ISSUE TITLE
network scan, missing links

### ISSUE THREAD

**Issue by sander816** [Koenkk/zigbee2mqtt#2462]
# Bug Report
## What happened
some devices not linked in network map

## Debug Info
zigbee2mqtt version: "1.7.1+dev
CC253X firmware version: 20181119

some devices in my network are not linked, but they are working ok.
Why is that happening?
see here: https://i.postimg.cc/zvGbztDv/2019-12-04-3.png

**Comment by Koenkk** [comment]
Duplicate of #2436
