### ISSUE TITLE
Ikea Inspelning power no change when socket is off

### ISSUE THREAD

**Issue by Alexofhiswalnut** [Koenkk/zigbee2mqtt#24627]
### What happened?

Hello, with my Ikea Inspelning plugs, when my washing machine finishes, the power consumption stays at 0.5W indefinitely, unless I press the refresh button in Z2M, which then brings it down to 0W.

What solution do you have to automatically refresh the plug to avoid showing the false residual power?

Have a good day.

### Zigbee2MQTT version

1.41

### Adapter firmware version

7.4.3 GA

### Adapter

Sonoff v2

### Setup

Pi4

**Comment by Alexofhiswalnut** [comment]
Non problem

**Comment by MaxRower** [comment]
You should fine tune the report intervals to fit your needs. I set them all to min 10s, max 10s, just like my tasmota plugs.

**Comment by nicola-spreafico** [comment]
Same problem here,

This morning (more than 10h ago), I switched off the printer using the plug switch, as you can see here:
![image](https://github.com/user-attachments/assets/5dcf7906-4c89-4e35-8571-19033b692a04)

Despite being off, the power consumption is reading 3.2W which is not possibile considering the device is not powered.

I went to Z2M interface and found this:
![image](https://github.com/user-attachments/assets/afb4b5a0-61d4-4a27-82ba-959d0235fbb0)
Only after I pressed the refresh button I got the actual 0.0 value
![image](https://github.com/user-attachments/assets/2096fa30-64cf-45c5-a508-48b78f5c7cfc)
