### ISSUE TITLE
 problem with links

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#2469]
Hello:

I am seeing that the final equipment is connected to the coordinator, there are times when this connection is very weak (linkquality 0-10), and although they have a rooter near them they do not change to connect to the node that better link quality. This way they give a lot of communication errors, I don't know if it's because I do something wrong or because it's like that.
Normally when I synchronize a team I do it near the coordinator and then place it at its destination. Is it better to synchronize the equipment in its final place or better near the coordinator and then move them?
Is there any way to make the devices look for other paths with a better link?

BR
## Debug Info
zigbee2mqtt version: 1.7.1
CC253X firmware version: "revision":20190608

**Comment by Koenkk** [comment]
Some devices indeed refuse to switch to different parent, re-paring them near the wanted parent can fix that.
