### ISSUE TITLE
Validation problems in Zigbee2MQTT device settings - page

### ISSUE THREAD

**Issue by jjarven** [Koenkk/zigbee2mqtt#24691]
### What happened?

Choose any device you have in your Zigbee2MQTT list.
Go to device's settings - tab. 
Fill in any field or click any on/off switch - after like 3 seconds, the value is removed byitself (before you can click submit).

### What did you expect to happen?

Field must stay as user has typed

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20240710

### Adapter

zStack3x0

### Setup

add-on, x86-64, as virtual host. web browser is Firefox 132.0.1

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
