### ISSUE TITLE
Xiaomi Button WXKG01LM / Aqara Wireless Switch E1 WXKG16LM / other Xiaomi buttons -- Action entity exposed as diagnostic

### ISSUE THREAD

**Issue by vit5041** [Koenkk/zigbee2mqtt#24720]
### What happened?

Action Entity is wrongly exprosed as Diagnostic.
Due to this it's not visible on Overview Dashboard.

![image](https://github.com/user-attachments/assets/b7e4fa11-6a49-43f0-81b6-6caecf7f578e)

### What did you expect to happen?

Expose Action Entity as Config so have it automatically displayed on Overview Dashboard 

### How to reproduce it (minimal and precise)

Take any of Xiaomi button and check how Action entity is presented in system. 

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20240710

### Adapter

Zigstar

### Setup

docker

**Comment by Koenkk** [comment]
`action` sensor will be completely removed in z2m 2.0.0 (https://github.com/Koenkk/zigbee2mqtt/discussions/24198), so will close this.
