### ISSUE TITLE
[Feature request]: Add switch type for TS110E _TZ3210_k1msuvg6

### ISSUE THREAD

**Issue by smodev** [Koenkk/zigbee2mqtt#24748]
### Is your feature request related to a problem? Please describe

The option to select the switch type for the device is not present.

### Describe the solution you'd like

Define switch_type for device

### Describe alternatives you've considered

/

### Additional context

The switch type is missing in the options, according to the seller it should be supported by the firmware.

**Comment by PaulFPV** [comment]
I need that too!

This seems quite similar: https://www.zigbee2mqtt.io/devices/TS110E_1gang_1.html

I don't know how to modify the converter to integrate the switch type selection even in the TS110E_1gang_2
