### ISSUE TITLE
Danalock V3 does not update state with latest FW 0.27.0

### ISSUE THREAD

**Issue by FredyReady** [Koenkk/zigbee2mqtt#24770]
### What happened?

I have been using Danalock V3 for over a year and half now and without major issues. I have just updated to the newest firmware 0.27.0 via app due to issues with calibration. The new firmware has more detailed calibration - great.

The firmware for zigbee module in Z2M is latest - 20231030.

Now the issue, **since the firmware update the state of the lock does not update automatically.**
I can control the lock without issue, but the state does not update, I have to trigger manual state update via Z2M UI then the state updates.

I do suspect that the firmware version for Z2M OTA might be outdated, when I access [Danalock website](https://danalock.com/zigbee-firmware-update?customize_changeset_uuid=#download ) latest firmware is:

"ZigbeeXM_101-029_E1_DanalockV3_17.7.0_20240201155008-secureboot"

It seems there has been also zigbee update in 2024.

There are steps on how to update the Zigbee firmware manually but I do not dare to do that as it might not be compatible with Z2M anymore and there is no way to revert back to 20231030.

Screenshots from Danalock app and Z2M UI when lock was unlocked via Z2M - State does update in the app, but not Z2M. If I reload the state it updates in 3s.

![app](https://github.com/user-attachments/assets/df14e2c1-d9c4-4ae4-b55d-6ca4fedc7ed8)
![Z2M](https://github.com/user-attachments/assets/493c9e32-be1b-45e4-8a0c-8e2e9f5b69cd)

### What did you expect to happen?

Danalock state will udpateautomatically after it changes either via app or Z2M or by manual operation.

### How to reproduce it (minimal and precise)

Update the lock to latest FW 0.27.0 via app.

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20240710

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-P

### Setup

Add-on on Home Assistant OS on Intel NUC

**Comment by BeFygo** [comment]
I've been using FW build 20240309 as shown in zigbee2mqtt (I assume its the zigbee FW) for some months without issues,
today I updated the device to FW 0.27.0 with the android app and tested without issues,
To be sure I used the windows APP to update the lock and with testing no issues so far.

Using zigbee2mqtt.latest-dev from today

**Comment by FredyReady** [comment]
> I've been using FW build 20240309 as shown in zigbee2mqtt (I assume its the zigbee FW) for some months without issues, today I updated the device to FW 0.27.0 with the android app and tested without issues, To be sure I used the windows APP to update the lock and with testing no issues so far.
> 
> Using zigbee2mqtt.latest-dev from today

Did you get the 20240309 OTA via Z2M or manually via the Danalock firmware updater like [here](https://danalock.com/zigbee-firmware-update)?

**Comment by BeFygo** [comment]
> > I've been using FW build 20240309 as shown in zigbee2mqtt (I assume its the zigbee FW) for some months without issues, today I updated the device to FW 0.27.0 with the android app and tested without issues, To be sure I used the windows APP to update the lock and with testing no issues so far.
> > 
> > Using zigbee2mqtt.latest-dev from today
> 
> Did you get the 20240309 OTA via Z2M or manually via the Danalock firmware updater like [here](https://danalock.com/zigbee-firmware-update)?

I actually don't remember, I've done this several months back.
My guess is via Z2M.

**Comment by FredyReady** [comment]
Weird, Z2M is not offering me this update OTA...

**Comment by Oliviakrkk** [comment]
I have the same problem - I updated via Danalock app.

**Comment by BeFygo** [comment]
> Weird, Z2M is not offering me this update OTA...

Then I think I just followed the guide from danalock
https://danalock.com/zigbee-firmware-update

**Comment by FredyReady** [comment]
Updated to the latest FW via Danalock update utility, Z2M still reports FW build "20231030".

Issue is gone, lock reports its state as it should, automatically.

**Result**
Update via Danalock utility helped and the latest FW is compatible with Z2M.

Thanks everyone for help.
