### ISSUE TITLE
zigbee2mqtt log not showing and error

### ISSUE THREAD

**Issue by liamlain** [Koenkk/zigbee2mqtt#24785]
### What happened?

![image](https://github.com/user-attachments/assets/0c6e328d-d89b-413e-899c-a559043eab82)

### How to reproduce it (minimal and precise)

click the log tab but no log showing and error message : Failed to get 9336c2b0_zigbee2mqtt logs, e.callApiRaw is not a function

### Zigbee2MQTT version

1.41.0-1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

Add on on Home Assistant pi4 8gb ram

**Comment by Ricc68** [comment]
I had the issue of log not loading and I resolved it by updating Home Assistant.
I don't know if it was a true incompatibility or updating HA reset something that was stuck.

**Comment by pilot1981** [comment]
> I had the issue of log not loading and I resolved it by updating Home Assistant. I don't know if it was a true incompatibility or updating HA reset something that was stuck.

so you solved updating HA?

**Comment by Ricc68** [comment]
Yes, updating HA solved the issue for me.

**Comment by Suffice** [comment]
Updating HA and doing a full restart fixed it for me as well.

**Comment by Nerivec** [comment]
This is not limited to Z2M addon and is a problem on HA side. Should be fixed after updating supervisor to [2024.11.3](https://github.com/home-assistant/supervisor/releases/tag/2024.11.3) or later.
