### ISSUE TITLE
Aqara Battery status always 100%

### ISSUE THREAD

**Issue by Baseje** [Koenkk/zigbee2mqtt#248]
In beta version i receive the status from my Aqara sensors,
But since version 0.1.1 there is always an status of 100%.

Also when i check the logs, zigbee2mqtt pushes always 100%;
2018-8-5 12:09:11 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0001b8f335', payload: '{"temperature":29.24,"humidity":44.77,"battery":"100.00","voltage":3025}'

Please let me know how to fix or if other persons had this problem to.

**Comment by Koenkk** [comment]
What do you expect it to be? As the Aqara sensors contain a 3 volt battery. Your sensor reports a voltage of 3.025V = 100%.

**Comment by Baseje** [comment]
When i firstly connect the sensors the status was 46% so i thought it was wrong now.

My appologise.

Van: Koen Kanters <notifications@github.com>
Verzonden: zondag 5 augustus 2018 13:14
Aan: Koenkk/zigbee2mqtt <zigbee2mqtt@noreply.github.com>
CC: Bas Jongeneel <Bas@Jongeneel.IT>; Author <author@noreply.github.com>
Onderwerp: Re: [Koenkk/zigbee2mqtt] Aqara Battery status always 100% (#248)


What do you expect it to be? As the Aqara sensors contain a 3 volt battery. Your sensor reports a voltage of 3.025V = 100%.

**Comment by ryanbeaton** [comment]
@Baseje you probably connected it before the calculations were updated. Mine went from 45% back up to 100%
See https://github.com/Koenkk/zigbee2mqtt/issues/142

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
