### ISSUE TITLE
[New Device Support]:  Devices that were supposed to be fixed now are detected as wrong devices again

### ISSUE THREAD

**Issue by MnM001** [Koenkk/zigbee2mqtt#24801]
### Link

https://vi.aliexpress.com/item/1005005857622120.html?spm=a2g0o.order_list.order_list_main.302.50651802W8lyGq&gatewayAdapt=glo2vnm

### Database entry

{"id":127,"type":"Router","ieeeAddr":"0xa4c138b049491060","nwkAddr":13991,"manufId":4417,"manufName":"_TZ3000_8nyaanzb","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"stackVersion":0,"dateCode":"","zclVersion":3}},"genOnOff":{"attributes":{"32768":0,"onOff":1,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1731839982568}

### Zigbee2MQTT version

1.41.0

### Comments

@Koenkk 

We have worked on this power point (ad more) last year. Please see here:

https://github.com/Koenkk/zigbee2mqtt/issues/20080

and

https://github.com/Koenkk/zigbee2mqtt/issues/20032

They were all fixed back then then but today I have added a new power point and is back to being detected as TS011F_plug_1 instead of RY-WS02Z (Rylike).

I would have thought that they will exist in Prod branch by now?

As before if these 3 can be fixed that will be great:

_TZ3000_rgpqqmbj
_TZ3000_8nyaanzb
_TZ3000_iy2c3n6p

Thanks

### External definition

```shell
N/A
```

### What does/doesn't work with the external definition?

N/A

**Comment by Koenkk** [comment]
They should still be detected as such: https://github.com/Koenkk/zigbee-herdsman-converters/blob/936e0f4f1b999f520676bc07076d1c4076624171/src/devices/tuya.ts#L1528

You don't have any external converters or something enabled?

**Comment by MnM001** [comment]
I see it in the tuya.ts

However, it didn't add it like that  :(
No external connectors at all.

This is the device:

![image](https://github.com/user-attachments/assets/80bb1091-c166-4b3b-a4b5-f9af7a49f135)

And the z2m information:

![image](https://github.com/user-attachments/assets/2cd2c1fb-accf-46f5-88df-80ebecf4bff9)

I can force delete it and add it again?

**Comment by MnM001** [comment]
Force removed and added it again - its the same, still showing the wrong device.

**Comment by Koenkk** [comment]
I cannot explain why one is detected correctly and the other one not, how are you running z2m? Bare metal installation? Docker image?

**Comment by MnM001** [comment]
I am running docker image for z2m

**Comment by MnM001** [comment]
Looking at the state of a working device it shows this:

``
{
    "backlight_mode": "high",
    "child_lock": "UNLOCK",
    "last_seen": "2024-11-20T08:31:18+08:00",
    "linkquality": 104,
    "power_on_behavior": "previous",
    "state_l1": "OFF",
    "state_l2": "ON",
    "update": {
        "installed_version": 192,
        "latest_version": 192,
        "state": "idle"
    },
    "update_available": null
}
``

This new device shows:

``
{
    "child_lock": "UNLOCK",
    "countdown": 0,
    "indicator_mode": "on/off",
    "last_seen": "2024-11-20T08:25:55+08:00",
    "linkquality": 80,
    "power_outage_memory": "restore",
    "state": "ON",
    "current": null,
    "energy": null,
    "power": null,
    "update": {
        "installed_version": 67,
        "latest_version": 192,
        "state": "available"
    },
    "update_available": null,
    "voltage": null
}
``

Should I update it? make it sort the issue out?

**Comment by MnM001** [comment]
Ended up updating the firmware. Force delete it from z2m and added it again - same problem :(

**Comment by MnM001** [comment]
This the DB entry of one that works OK. Maybe you can see something when comparing:

`
{"id":46,"type":"Router","ieeeAddr":"0xa4c138c87d62a895","nwkAddr":23147,"manufId":4417,"manufName":"_TZ3000_8nyaanzb","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,1794,2820,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"˛z.\u0016","65506":54,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_8nyaanzb","powerSource":1,"zclVersion":3,"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":2,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"53248":0,"53249":0,"53250":0,"53251":0,"53252":0,"53253":0,"powerOnBehavior":2,"switchType":0}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":192,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1324213189},"lastSeen":1732103278984}`

**Comment by Koenkk** [comment]
Can you provide me your complete `configuration.yaml` and `devices.yaml`. I added the database.db entry to my own database and its detected correctly (z2m 1.41.0)

<img width="971" alt="Screenshot 2024-11-21 at 21 52 14" src="https://github.com/user-attachments/assets/138c1727-6f07-4640-a39e-af2fbb5e144f">

**Comment by MnM001** [comment]
Hi @Koenkk - today I have shut down my server for a few hours as I needed to do some work on it.
After the reboot I can see that the device is actually detected as it should and has all the correct option. I have no idea why it only happened after the shut down.

![image](https://github.com/user-attachments/assets/4da8c551-a728-4f2b-bac4-4a986a35ffdc)

I have a couple more of these devices coming so I will test again and see. Will post in here the results of the new devices.

Also if you have some time can you please have a look at these 2 requests? Not power points but light switches this time :)

https://github.com/Koenkk/zigbee2mqtt/issues/24708

and

https://github.com/Koenkk/zigbee2mqtt/issues/24707

Many thanks.

**Comment by MnM001** [comment]
I have added 2 more devices and both of them added correctly.
No idea why it behaved the way it did before.

Guess can close this as all is working as it should.
