### ISSUE TITLE
Question: default color for Tradfri LED1624G9

### ISSUE THREAD

**Issue by neographikal** [Koenkk/zigbee2mqtt#2481]
# Bug Report
Can't reset color of the LED1624G9 to defaults. Once I have changed it in HomeAssistant I don't know what values represent the default color temperature. The default closely matches the other Ikea 2700K non-color bulbs, but I can't seem to get that back.

What values represent the default color settings of the bulbs coming out of the box?

## Debug Info
zigbee2mqtt version: 1.7.1-dev
CC253X firmware version: 3.0.x

**Comment by keteflips** [comment]
Same problem?

https://github.com/Koenkk/zigbee2mqtt/issues/3738
