### ISSUE TITLE
[New device support]: AVATTO Dimmer, possible wrong fingerprint

### ISSUE THREAD

**Issue by thepaulf** [Koenkk/zigbee2mqtt#24840]
### Link

https://a.aliexpress.com/_Evfwk8N

### Database entry

{{"id":14,"type":"Router","ieeeAddr":"0xa4c13803d4a606f1","nwkAddr":18886,"manufId":4417,"manufName":"_TZE204_jtbgusdc","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[4,5,61184,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"\u0006\u0000\u0000\u0000e\u0007\u0000\u0000\u0000\u0012","65506":56,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_jtbgusdc","powerSource":1,"zclVersion":3,"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":74,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1732128248253}

### Zigbee2MQTT version

 1.41.0 commit: 69f72829

### Comments

I've tried to write a extender, but failed
it looks like this is the same product:
https://www.zigbee2mqtt.io/devices/ZDMS16-2.ZDMS16-2html

### External definition

```shell
const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_jtbgusdc',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Nothing works, can't find how to extend, new to writing extenders

**Comment by Koenkk** [comment]
can you try to:

- Stop Z2M
- Open `data/database.db` with a text editor and change all occurrences of `_TZE204_jtbgusdc ` to `_TZE204_o9gyszw2`
- Start Z2M and see if the device now works

**Comment by thepaulf** [comment]
Perfect, works completely. Thank you for the solution

**Comment by thepaulf** [comment]
Oh no it didn't survive a reboot, how can I fix that?

Op do 21 nov 2024 21:44 schreef Koen Kanters ***@***.***>:

**Comment by Koenkk** [comment]
Not sure, but I added it now

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by EisDaveLO** [comment]
I got a new device name for the Avatto 1-gang dimmer, seems that there are a lot different vendors. 

How can I find the database.db on Homeassistant OS to add the device. Thanks for your help. 
The external definition:
`const definition = {
    zigbeeModel: ['TS0601'],
    model: 'TS0601',
    vendor: '_TZE204_nqqylykc',
    description: 'Automatically generated definition',
    extend: [],
    meta: {},
};

module.exports = definition;`

PS: currently running on the edge-version
