### ISSUE TITLE
1.7.0 upgrade docker startup issues

### ISSUE THREAD

**Issue by thenakuls** [Koenkk/zigbee2mqtt#2484]
# Bug Report
## Upgrade after 1.6.0 will not start with docker. The log present at: https://pastebin.com/Vf75qyeY

 #719 is probably related however, I cannot run this command:
`rm -rf node_modules && npm install`
because the image fails to start because of the error

**Comment by thenakuls** [comment]
I tried adding this to my docker-compose, but didn't help. 
- ./run.sh:/bin/sh -c "rm -rf node_modules && npm install && /run.sh"

**Comment by Koenkk** [comment]
Do you have a docker volume mapping `homeassistant.js` or `zigbee-shepherd-converters`? If so, remove this.

**Comment by thenakuls** [comment]
I did have a volume mapping to homeassistant.js
Thank you, removing it solved the issue
