### ISSUE TITLE
If (by accident) use a 'postfix' (rgb, left, right) as friendly name, all commands are ignored

### ISSUE THREAD

**Issue by rduivenvoorde** [Koenkk/zigbee2mqtt#2486]
# Bug Report

I like short (friendly) names, so gave my first rgb-lamp as friendlyname  'rgb' in the config
After that I was unable to set/get messages for that specific device.
Renaming to rgblamp fixed this, so at first the idea was that there was a minimal length of friendly name, but 'xx' also seemed to work on further testing

After some q&a on the discord-channel, people pointed to:

https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/util/utils.js#L30

So apparently 'rgb' ('left', 'right', 'center', 'bottom_left', 'bottom_right', 'l1', 'l2', 'default',
    'top_left', 'top_right', 'white', 'rgb', 'system', 'top', 'bottom', 'center_left', 'center_right',
    'ep1', 'ep2', ) are a sort of 'reserved keyword', and using it made all fail via: 

https://github.com/Koenkk/zigbee2mqtt/blob/b459c352191091af9b9eafec82a98f73069797e8/lib/zigbee.js#L167-L177

On Discord people proposed:

- put this info in docs
and/or
- "It should only check for postfixes if the thing in front of the postfix is a valid friendly name, I'd say."

## How to reproduce it (minimal and precise)

Just give a device 'rgb' or 'left' as friendly name and try to get/set messages

## Debug Info
zigbee2mqtt version 1.7.1 (commit #b459c35)

**Comment by Koenkk** [comment]
These postfixes are indeed not allowed as a `friendly_name`, zigbee2mqtt will now check for this and refuse to start int his case. Thanks!
