### ISSUE TITLE
Persist state across restarts

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#249]
When zigbee2mqtt is restarted all cached states of the sensors are lost.

Zigbee2mqtt should persist the state to a file in the following way:

- Save the state to every 5 minutes.
- Save the state on exit.

Follow-up of #245

**Comment by tb-killa** [comment]
What about use the available ``devbox`` and build a own database with it?

**Comment by Koenkk** [comment]
@tb-killa dumping the JSON object is enough :)

@cmorlok @hoangtuit can you checkout the dev branch and check if it solves your problem?

**Comment by cmille34** [comment]
Is this getting close to becoming production?  Retaining the values across reboots would help with some of the issues I've been annoyed with as well.

**Comment by Koenkk** [comment]
If you want to try it out you can use the dev branch for now.

**Comment by cmille34** [comment]
Is there a docker image with the dev branch? If not, any brief instructions on how I would use dev in a docker?

**Comment by Koenkk** [comment]
Yes, the [-dev](https://hub.docker.com/r/koenkk/zigbee2mqtt/tags/) images.

**Comment by lolorc** [comment]
@Koenkk can it be configurable ?
when I restart zigbee2mqtt it sends all the persisted states. And it's not what I want at all, I really don't want to risk feeding mqtt with very old outdated states...

**Comment by clockbrain** [comment]
Perhaps a specified time limit in configuration.yaml e.g. 60 (minutes)? On restart if saved state is within that limit it uses saved state otherwise it doesn't.

**Comment by lolorc** [comment]
@Koenkk  an option would be great, so it could either be a boolean or a integer to specify the retention period as @clockbrain proposed. 0 could be no retention, 1 could be 1sec/min/hour...
but lastseen attribute would be needed to do the retention thing ;-)
