### ISSUE TITLE
click_release for XIAOMO WXKG02LM

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#2492]
# Feature request: click_release for XIAOMO WXKG02LM
## What happened
Device:
- XIAOMI WXKG02LM, version 2016DP1247
- paired device to zigbee2mqtt dev:
  - zigbee2mqtt version 1.7.1+dev (commit #6bd9e74)
  - Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'

Button actions
- left
- left_double
- left_long

Is it possible to support 
- left_long_**release**

and if possible also the duration?

In example, my IKEA device has
- arrow_left_hold
- arrow_left_release
- duration

`{"linkquality":39,"action":"arrow_left_release","duration":1.135}`

## What did you expect to happen
support for
 - left_long_**release**

## Debug Info
zigbee2mqtt version: 1.7.1+dev (commit #6bd9e74)
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
I've just sniffed the traffic of my WXKG02LM again to be sure, but this device doesn't send anything when the button is released, therefore this cannot be supported.
