### ISSUE TITLE
device_temperature_calibration offset is ignored

### ISSUE THREAD

**Issue by Suchtaaa** [Koenkk/zigbee2mqtt#24929]
### What happened?

Yesterday I completed my setup with an sonoff ZigBee dongle version p, zigbee2mqtt on a raspberry pi 4. 

Everything works like it should. My three thermostats (Aqara SRTS-A01) are connected an can be controlled. The only thing which didn't work is the temperature offset (device_temperature_calibration). 

I've tried to set it with the "ui" and also direct in the configuration.yaml. I read that it can take some time to take action on the device, but 12 hours should be enough. 
The last thing I've tried was to restart the z2mqtt service.

But nothing changed. 

Here is my configuration.yaml:
`permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.24:41883
  user: Admin
  password: **********
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
advanced:
  network_key:
    - ***
    - ***
    - ***
    - 9
    - 137
    - 219
    - 35
    - 138
    - 170
    - 191
    - **
    - ***
    - ***
    - ***
    - **
    - **
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
frontend:
  port: 8080
device_options:
  legacy: false
devices:
  '0x54ef441000e15***':
    friendly_name: Thermostat_Livingroom
    thermostat_unit: celsius
    homeassistant:
      name: Wohnzimmerheizung
    optimistic: false
    device_temperature_calibration: -10
  '0x54ef441000b83***':
    friendly_name: Thermostat_Kitchen
    device_temperature_calibration: -5
    thermostat_unit: celsius
  '0x54ef441000b83***':
    friendly_name: Thermostat_Bathroom
    thermostat_unit: celsius
homeassistant:
  discovery_topic: homeassistant
  legacy_entity_attributes: true
  status_topic: hass/status
  legacy_triggers: true`

### What did you expect to happen?

Temperature should come up correct

### Zigbee2MQTT version

1.41.0 commit: cc31cea

### Adapter firmware version

20210708

### Adapter

Sonoff ZigBee 3.0 USB dongle Plus (CC2652P+ CP2102N)

### Setup

On a raspberry pi with docker

### Debug log

There are no errors.

**Comment by DaN66O** [comment]
The Aqara SRTS-A01 does not have such a parameter as device_temperature_calibration and temperature offset either

**Comment by Suchtaaa** [comment]
Oh yes, youre right.. sorry my fault. I thought it was the offset for the measured temperature.
But curious that it doesnt work directly with the radiator.

I did some tests and saw, that the temperature sensor measures a bit (0,7°C) to high.. but next week I get some external sensors, so the problem should be "solved" :)
