### ISSUE TITLE
ROB_200-008-0 battery 200% instead of 100%

### ISSUE THREAD

**Issue by sbruckmueller** [Koenkk/zigbee2mqtt#24930]
### What happened?

Zigbee 4 button wall switch ROB_200-008-0 is showing battery status of 200%. https://www.zigbee2mqtt.io/devices/ROB_200-008-0.html

### What did you expect to happen?

Showing 100% :)

### How to reproduce it (minimal and precise)

After waiting several hours still no change.

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

7.4.4

### Adapter

ZBDongle-E 3.0 USB Dongle Plus,EFR32MG21

### Setup

HASSIO und Pi 5

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
