### ISSUE TITLE
Tuya TS0203 Handling of poll check-in failed

### ISSUE THREAD

**Issue by leroyloren** [Koenkk/zigbee2mqtt#24938]
### What happened?

the error still appears in the log
zh:controller:device: Handling of poll check-in from 0xa... failed (ZCL command 0xa.../1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 11226 - 1 - 59 - 32 - 11 after 10000ms))

Zigbee Model
TS0203
Zigbee Manufacturer
_TZ3000_x8q36xwf
Description
Door sensor

### What did you expect to happen?

Do not show error

### How to reproduce it (minimal and precise)

pair and use the sensor

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20240710

### Adapter

SONOFF ZB Dongle-P

### Setup

HAOS addon

### Debug log

zh:controller:device: Handling of poll check-in from 0xa... failed (ZCL command 0xa.../1 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 11226 - 1 - 59 - 32 - 11 after 10000ms))

**Comment by KoLSMS** [comment]
same problem here, maybe anyone can help?

**Comment by Koenkk** [comment]
Is it fixed by unbinding `genPollCtrl` through the frontend -> device -> bind tab?

**Comment by KoLSMS** [comment]
> Is it fixed by unbinding `genPollCtrl` through the frontend -> device -> bind tab?

Hello,

unbinding is not possile, after unbinding it looks like this:

![Screenshot 2024-12-01 085007](https://github.com/user-attachments/assets/1c81d402-cd84-4020-8775-269980f9e2a9)

**Comment by lowerprofile** [comment]
I have the same issue with a Hive thermostat:

zh:controller:device: Handling of poll check-in from 0x001e5e090278b220 failed (ZCL command 0x001e5e090278b220/9 genPollCtrl.checkinRsp({"startFastPolling":false,"fastPollTimeout":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (Timeout - 61897 - 9 - 42 - 32 - 11 after 10000ms))

attempting to unbind genPollCtrl fails.

error: 	z2m: Failed to unbind cluster 'genPollCtrl' from 'hive_thermostat' to 'Coordinator' (Error: Unbind 0x001e5e090278b220/9 genPollCtrl from '0x00124b0021b7799c/1' failed (AREQ - ZDO - unbindRsp after 10000ms))
error: 	z2m: Failed to unbind

Started happening after upgrading to 1.41 from a version I can't remember unfortunately, but more than a year old.

**Comment by Koenkk** [comment]
Make sure to wakeup the device by triggering it right before unbinding

**Comment by KoLSMS** [comment]
> Make sure to wakeup the device by triggering it right before unbinding

Hello, i have triggerd and it ends in the result i have shown...

**Comment by lowerprofile** [comment]
Waking the thermostat up I was able to unbind genPollCtrl, and the error messages seem to have stopped, thanks. I'll keep an eye in it.

**Comment by KoLSMS** [comment]
> Make sure to wakeup the device by triggering it right before unbinding

Hello,

it was my mistake... now after unbinding it looks like this:

![Screenshot 2024-12-02 15 11 11](https://github.com/user-attachments/assets/6faab561-21bc-4c0c-997f-1ae9297d613d)

now the error in the logs is not showing again

**Comment by Koenkk** [comment]
Thanks, pushed a fix!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

**Comment by JanoAX** [comment]
I have same problem. zigbee-herdsman-converters version 23.2.0 Unbind seems to be not possible

**Comment by Teraskull** [comment]
For future visitors googling this issue, the same thing happens with the Aeotec SmartThings Multipurpose sensors.

https://www.zigbee2mqtt.io/devices/IM6001-MPP01.html

Unbinding `genPollCtrl` fixes this and does not affect their reporting.

**Comment by peufeu2** [comment]
> For future visitors googling this issue, the same thing happens 
> Unbinding `genPollCtrl` fixes this and does not affect their reporting.

Exact same thing here for Tuya door/window sensor.
https://www.zigbee2mqtt.io/devices/SNZB-04_eWeLink.html

I made a python script that listens on MQTT. When it sees the devices report, it publishes:

```
                pub_payload = {
                        "from"      : device_id, 
                        "to"        : "Coordinator", 
                        "clusters"  : ["genPollCtrl"]
                    }
                mqtt.publish( "z2m/bridge/request/device/unbind" , orjson.dumps( pub_payload ))

```

This causes z2m to unbind when the device is listening, which is a lot more convenient when I'm busy running through the house opening and closing all the windows to wake up the sensors...
