### ISSUE TITLE
Phillips Hue Twilight - resulting with "Not Supported"  (Z2MQTT compatability states it is supported)

### ISSUE THREAD

**Issue by wardwolfram** [Koenkk/zigbee2mqtt#24965]
### What happened?

I purchased the Phillips Hue Twilight lamp as it was compatible with Z2MQTT.

HA, Z2MQTT and the Twilight lamp are all up to date with FW.

After repeatedly pairing the Twilight, HA/Z2MQTT states "Not Supported"

The Twilight that I have identifies as:
Model: LGT003

The Z2MQTT compatibility website states the model supported = 929003711201
The box the Twilight came in has an unlabeled similar number of = 929003711401

Pairing is successful, but I have no control of any feature of the lamp.

Let me know how I can help.

### What did you expect to happen?

Ability to control the Twilight via Z2MQTT

### How to reproduce it (minimal and precise)

100% of the time each time that I tried to pair.

### Zigbee2MQTT version

1.41.0-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff 3.0 USB Dongle Plus - EZSP v8 6.10.3.0 build 297

### Setup

Home Assistant on a NUC

### Debug log

[log2.log](https://github.com/user-attachments/files/17963606/log2.log)

I am not sure how to 'refresh' logs, etc. so the error codes are captured.   Hope this is the correct one. 

[45df7312_zigbee2mqtt_2024-11-30T00-24-30.993Z.log](https://github.com/user-attachments/files/17963614/45df7312_zigbee2mqtt_2024-11-30T00-24-30.993Z.log)

**Comment by Koenkk** [comment]
Added! will be supported in tomorrows release.

**Comment by wardwolfram** [comment]
Hello Koenkk,  I updated Z2MQTT this morning and repaired the Twilight.  I continue to get the status of 'Unsupported'. Is their any other information that I can help provide?

![Z2MQTT Twilight2](https://github.com/user-attachments/assets/0b871a80-e10a-4aff-9a05-7216d802296d)

**Comment by wardwolfram** [comment]
Is their anything I can help with to get the Hue Twilight light supported?  Let me know. Thanks!

**Comment by Koenkk** [comment]
Whoops, found the issue and pushed a fix, will be included in the next release (1 Jan)

**Comment by wardwolfram** [comment]
Thanks for looking into this.
