### ISSUE TITLE
Failed to execute LQI for 'Coordinator'

### ISSUE THREAD

**Issue by milakov** [Koenkk/zigbee2mqtt#2498]
Hi, I am getting `Failed to execute LQI for 'Coordinator'` error message when doing network scan. The device is local, why could it happen? Using zigbee2mqtt 1.7.1, it worked fine on <1.7.0 versions.

**Comment by Koenkk** [comment]
In my cause the LQI for the coordinator succeeds, note that it does not only contain the link quality but also neighbour information, etc. Therefore I think it's completely valid to scan this.

**Comment by milakov** [comment]
I shut down the server, unplugged the coordinator, plugged it back, booted the server, and now it works!
