### ISSUE TITLE
Tuya Model WSD500A detected as TS0201 and vendor _TZ3000_xr3htd96 bad works

### ISSUE THREAD

**Issue by matata86** [Koenkk/zigbee2mqtt#25018]
### What happened?

The thermometer is unstable; it keeps disconnecting.
This product: https://www.aubess.net/products/aubess-tuya-smart-zigbee-temperature-and-humidity-sensor-work-with-alexa-google-home

Z2M detects it as:

Zigbee Model: TS0201
Zigbee Manufacturer: _TZ3000_xr3htd96
Manufacturer: Tuya
Model: WSD500A

### What did you expect to happen?

I tried re-pairing it, connecting it to different routers. Nothing helps.

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

0x26530900

### Adapter

Conbee III

### Setup

NUC

**Comment by rolandas-valantinas** [comment]
I think problem is back - I'm on `2.1.3` _TZ3000_rdhukkmi is detected as TS0201 though there is no screen.

![Image](https://github.com/user-attachments/assets/da817a99-878a-41c2-9998-36a08ff95dbe) 

I've added `landing sensor` a while ago and today I've added `outside sensor` - both came from same seller, is same item and look the same.
