### ISSUE TITLE
Iluminize 511.012

### ISSUE THREAD

**Issue by johnnychicago** [Koenkk/zigbee2mqtt#2502]
Just realized I posted this to an issue closed about half an eternity ago. Sorry.

I have a 511.012, which seems closely related. I added following to devices.js:

```
    {                
        zigbeeModel: ['511.012'],
        model: '511.012',
        vendor: 'Iluminize',
        description: 'Zigbee LED-Controller ',
        extend: generic.light_onoff_brightness,
    },

```

and I can switch the dimmer by publishing to the respective MQTT topic as mentioned earlier in the thread. However the device does not seem to find its way into my home assistant instance.
Can I ask you to add the 511.012 to devices.js, and would you by chance know where I should look to understand why it's not coming up in home assistant?

_Originally posted by @johnnychicago in https://github.com/Koenkk/zigbee2mqtt/issues/1446#issuecomment-563453949_

**Comment by Koenkk** [comment]
Added, see https://github.com/Koenkk/zigbee2mqtt/issues/1446#issuecomment-564675464
