### ISSUE TITLE
Devices paired between 1.42.0-1 and -2 missing

### ISSUE THREAD

**Issue by ki4hrg** [Koenkk/zigbee2mqtt#25027]
### What happened?

I have a device (a Third Reality plug model 3RSP019BZ if it matters) that I paired after upgrading to 1.42.0-1 and before upgrading to the -2 release earlier today that disappeared following the upgrade. Admittedly a bit of an edge case but could see the root issue causing issues down the line. 

### Zigbee2MQTT version

1.42.0-2

### Adapter firmware version

7.1.1.0 build 273

### Adapter

EZSP v9

### Setup

Add-on on HAOS on HA Green

**Comment by jamiegt10** [comment]
I have the same issue. i re-added all my devices after the 1.42.0-1 issue and now after the upgrade to -2 all are no longer there.

**Comment by Koenkk** [comment]
See https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/664#issuecomment-2514982450, lets' continue there.
