### ISSUE TITLE
Coordintor firmware changelog and when to upgrade

### ISSUE THREAD

**Issue by kiwinol** [Koenkk/zigbee2mqtt#2507]
CC2531 firmware version: 20190223

I would like to know how people decide when to upgrade the coordinator firmware.
I am most interested in bug fixes and stability.

Is there a changelog I can read for the coodinator firmware?

**Comment by pepp86** [comment]
Hi, 

you can find the Changelog in the github archive:
https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/CHANGELOG.md

I'm upgrading always to the latest release, as I am also running dev version of z2m.

If everything is stable for you, just stay where you are, if not, upgrade to latest firmware.

**Comment by kiwinol** [comment]
@pepp86 thanks, that is exactly what I was looking for :)_
