### ISSUE TITLE
Linkquality above 100??

### ISSUE THREAD

**Issue by z4rn0x** [Koenkk/zigbee2mqtt#2509]
# Bug Report
## What happened
Hello
I noticed since several days that one of my Aqara thermometer has a linkquality above 100...
Here is the MQTT message:
{"temperature":21.04,"linkquality":115,"humidity":37.73,"battery":74,"voltage":2955}

## What did you expect to happen
Is it a bug? Or something that I can fix?

## Debug Info
zigbee2mqtt version: 1.7.1
CC253X firmware version: 20190608

**Comment by Kryzek** [comment]
I am under impression that linkquality is a value from 0 to 255 and 255 is the best quality.

**Comment by Koenkk** [comment]
This is indeed a value between 0 and 255.

**Comment by CodeFinder2** [comment]
Does it make sense to map this to [0,100] (percentage) for improved readability?

Together with a '%' at the end, it would not allow for any misunderstanding.

**Comment by Koenkk** [comment]
Yes, but that will be a breaking change so can not be done easily.
