### ISSUE TITLE
[Wrong device]: _TZ3000_shopg9ss

### ISSUE THREAD

**Issue by Renata1999-pl** [Koenkk/zigbee2mqtt#25150]
### Link

https://allegro.pl/oferta/wzmacniacz-sygnalu-usb-repeater-zigbee-3-0-tuya-15079498562

### Model

none

### Description

repeater

### Vendor

Tuya

### Picture (link)

https://ibb.co/D7W4Qh9

### Database entry

{"id":5,"type":"Router","ieeeAddr":"0x14b457fffe385a20","nwkAddr":40115,"manufId":4098,"manufName":"_TZ3000_shopg9ss","powerSource":"Mains (single phase)","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":8,"inClusterList":[0,10,3],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0005","65506":22,"modelId":"TS0207","manufacturerName":"_TZ3000_shopg9ss","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0xbc026efffe22b831","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1733826213018}

### Notes

Detected as water_leak_sensor but it's not sensor. It's repeater i've bought from Allegro(Poland)

**Comment by Koenkk** [comment]
Added, thanks!


Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
