### ISSUE TITLE
[Feature request]: When configuring permit_join, would want to define the scope (e.g. Coordinator)

### ISSUE THREAD

**Issue by rickalm-wapo** [Koenkk/zigbee2mqtt#25185]
### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Besides True, the config item should accept a scope of the permit (device/Coordinator/etc..).

On my property I typically leave permit_join enabled (yes I understand security risks) but I find this easier for my situation. But setting it true seems to allow it to join to any router and this has caused issues in my network. 

Also the "permit" timer, which seems to be hardcoded to 5 minutes should be configurable as well

### Describe alternatives you've considered

I've considered setting up a postman to enable the feature but this is an anti-pattern

### Additional context

Nothing to add

**Comment by mundschenk-at** [comment]
I believe it will not be possible to leave `permit_join` enabled all the time starting with Z2M 2.0.0 by design.

**Comment by Koenkk** [comment]
This option will indeed be removed with z2m 2.0.0, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198 for more info.
