### ISSUE TITLE
Display stopped working and device is recognized as a different device in Z2M after upgrading firmware of TS0201

### ISSUE THREAD

**Issue by heisenberg2980** [Koenkk/zigbee2mqtt#25207]
### What happened?

I upgraded the firmware of my TS0201 in Z2M, and when the upgrade was complete the screen of the device when blank. I tried removing the batteries and putting them back after 30 minutes but the screen is still not working. I also realised the device is now recognized as LYWSD03MMC in Z2M, which is incorrect as the device is TS0201 (the picture of the device matches).

### What did you expect to happen?

Device should still work after upgrading the firmware

### How to reproduce it (minimal and precise)

Upgrade the firmware of the device. As a side note, for the upgrade to work without timing out, I had to keep pressing the button on the device again and again until the upgrade finished.

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

20230507

### Adapter

SMLIGHT SLZB-06

### Setup

Add-on

**Comment by heisenberg2980** [comment]
According to this thread, it seems more people have had the same issue of bricking the device by applying this update: https://community.home-assistant.io/t/tuya-ts0201-temperature-sensor-ota-not-working/804442/4

Is there anything that can be done to revert the update and restore the previous firmware? And can this update be removed from Z2M to avoid other people having the same issue?

**Comment by Koenkk** [comment]
Do you by any chance still have the logs of the update? Then I can check what fw was loaded and fix it.

**Comment by heisenberg2980** [comment]
@Koenkk I found this on the logs before the update, is this enough?

{"battery":39,"humidity":43.2,"last_seen":"2024-12-14T09:49:12.919Z","linkquality":94,"temperature":21,"update":{"installed_version":268513281,"latest_version":285224961,"state":"available"},"update_available":null,"voltage":null}

**Comment by Koenkk** [comment]
@heisenberg2980 yes, with z2m 2.0.0 (which is the latest [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) atm), you can downgrade fws. Docs: https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/docs/guide/usage/ota_updates.md#downgrade

**Comment by heisenberg2980** [comment]
@Koenkk I tried, but no luck

I guest as the device "thinks" it is not a different model, it does not find the previous firmware, is it possible to force a specific fw into the device rather than asking "downgrade to the previous available fw"?

![image](https://github.com/user-attachments/assets/40c34f0b-52c9-4fd4-9dff-5d5b26af87da)

**Comment by heisenberg2980** [comment]
@Koenkk I just sent you the log

**Comment by Koenkk** [comment]
I removed the firmwares in https://github.com/Koenkk/zigbee-OTA/pull/629/files, unfortunately we don't have the original TS0201 firmwares so I don't think it is possible to downgrade.

**Comment by dragonlost** [comment]
Hello. I wanted to update my peripherals and I had the same problem as you. Their screens remained frozen (so I didn't realize they were broken). I updated 4 of them before noticing!
Did any of you manage to get back to the previous version? I don't know what to do to catch up.
I've tried changing the batteries, but I can't get a picture or a connection.

My exact model : 
temperature and humidiy sensor, Brand : NEO
model: NAS-TH02B2

**Comment by Minz0r** [comment]
> I removed the firmwares in https://github.com/Koenkk/zigbee-OTA/pull/629/files, unfortunately we don't have the original TS0201 firmwares so I don't think it is possible to downgrade.

Hi, i think i found a Site with a Link to th original OTA Firmware and Custom Firmware.
[https://pvvx.github.io/TS0201_TZ3000/](url)

**Comment by Celexi** [comment]
for what is worth the one I have has no screen, I got a tuya gateway to check if it really had an update and there is no update. so either that update was for the one with a display, or an entirely different one.

**Comment by webgress** [comment]
> > I removed the firmwares in https://github.com/Koenkk/zigbee-OTA/pull/629/files, unfortunately we don't have the original TS0201 firmwares so I don't think it is possible to downgrade.
> 
> Hi, i think i found a Site with a Link to th original OTA Firmware and Custom Firmware. [https://pvvx.github.io/TS0201_TZ3000/](url)

@Minz0r any updates on this?
Did you try/succeed flashing the original FW?

I have 3 TS0201 screen devices, not round like on the site, but square. Either way, they do not report values to Z2M.
Numbers on screen seem to change but the charts have 1 straight line - no data.

**Comment by Celexi** [comment]
> > > I removed the firmwares in https://github.com/Koenkk/zigbee-OTA/pull/629/files, unfortunately we don't have the original TS0201 firmwares so I don't think it is possible to downgrade.
> > 
> > 
> > Hi, i think i found a Site with a Link to th original OTA Firmware and Custom Firmware. [https://pvvx.github.io/TS0201_TZ3000/](url)
> 
> [@Minz0r](https://github.com/Minz0r) any updates on this? Did you try/succeed flashing the original FW?
> 
> I have 3 TS0201 screen devices, not round like on the site, but square. Either way, they do not report values to Z2M. Numbers on screen seem to change but the charts have 1 straight line - no data. I don't remember exactly, but I don't think I've updated them.

zigbee2mqtt doesn't automatically update anything as far I know, so if you didn't update them, this would be a different issue of it being identified wrong. did you try resetting them?

**Comment by mattrj1975** [comment]
> I removed the firmwares in https://github.com/Koenkk/zigbee-OTA/pull/629/files, unfortunately we don't have the original TS0201 firmwares so I don't think it is possible to downgrade.

Then it must have accidentally crept back in to later Zigbee"MQTT updates, because I have the exact same issues after an update on a week or so old TS0201, following update 268513281 just 2 days ago.

**Comment by mattrj1975** [comment]
Running Z2M 2.1.1-1

**Comment by mechanig** [comment]
> According to this thread, it seems more people have had the same issue of bricking the device by applying this update: https://community.home-assistant.io/t/tuya-ts0201-temperature-sensor-ota-not-working/804442/4
> 
> Is there anything that can be done to revert the update and restore the previous firmware? And can this update be removed from Z2M to avoid other people having the same issue?

If you didn’t throw away the bricked device after the software update, you can flash new custom firmware from
https://github.com/pvvx/ZigbeeTLc/issues/107#event-22416527223, but this requires a simple hardware modification.

I have a working device after flashing at a customized USB-to-TTL adapter on the CH340 chip. (https://github.com/pvvx/TlsrComProg825x)
