### ISSUE TITLE
Сhanges in the control structure of switch topics Xiaomi LLKZMK11LM

### ISSUE THREAD

**Issue by directman66** [Koenkk/zigbee2mqtt#2522]
Hey. LLKZMK11LM  could previously be controlled through the topics  by sending the payload set  {"state_l1":"OFF"}  on ZigBeeCA20/0x00158D0001A24770/set  
Everything worked well. But after updating to version 1.7.0 the management topics changed. Now you can control it only by sending 
ZigBeeCA20/0x00158D0001A24770/l1/set by sending the payload   {"state_l1":"ON"}
I have already adapted the code and control methods when the result of the command corresponds to the command being sent. I do not like that sending the state parameter I see the result in the state_right topic. Can I add an old control option in addition to the existing one?

А similar problem was also solved earlier for the switch https://github.com/Koenkk/zigbee2mqtt/issues/2356

**Comment by Koenkk** [comment]
Did you try with the latest dev branch?
