### ISSUE TITLE
Changing Channel

### ISSUE THREAD

**Issue by agoralive** [Koenkk/zigbee2mqtt#2523]
When I change channel in configuration.yaml Zigbee2mqtt dosen't work anymore

No coordinator is found, when I look at the Node-Red Dashboard?

Beyond change the yaml (including the advanced: channel: 15 thing) is there anything I need to do except rebooting the pi?

**Comment by didiht** [comment]
You can try to reset / reflash the coordinator

**Comment by pixeldoc2000** [comment]
You need to repair your devices after changing your Zigbee Channel. Maybe Node-Red will not show your coordinator without paired devices?
