### ISSUE TITLE
[Wrong device]: Moes Flood Sensor wrong picture

### ISSUE THREAD

**Issue by razvancucu27** [Koenkk/zigbee2mqtt#25238]
### Link

https://moeshouse.com/products/zigbee-round-flood-sensor?variant=39798524674129

### Model

ZSS-QY-WL-C-MS

### Description

Flood Sensor Water Leakage Detector

### Vendor

Moes

### Picture (link)

https://moeshouse.com/cdn/shop/products/zigbee-flood-sensor-water-leakage-detector-2mqtt-setup-available-390407.jpg

### Database entry

{"id":54,"type":"EndDevice","ieeeAddr":"0xa4c138413cc7812b","nwkAddr":8796,"manufId":4417,"manufName":"_TZ3000_t6jriawg","powerSource":"Battery","modelId":"TS0207","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[1,3,1280,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0207","manufacturerName":"_TZ3000_t6jriawg","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"iasCieAddr":"0xbc026efffed0f599","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0xbc026efffed0f599","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":0}],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":543112114},"lastSeen":1734426111177}

### Notes

**The device is identifies as :**
Manufacturer: Tuya
Model: TS0207_water_leak_detector
Zigbee Model: TS0207
Zigbee Manufacturer: _TZ3000_t6jriawg

The device works ok but the picture is from TS0207_water_leak_detector

**External definition:** 
const {battery, iasZoneAlarm} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0207'],
    model: 'TS0207',
    vendor: '_TZ3000_t6jriawg',
    description: 'Automatically generated definition',
    extend: [battery(), iasZoneAlarm({"zoneType":"generic","zoneAttributes":["alarm_1","alarm_2","tamper","battery_low"]})],
    meta: {},
};

module.exports = definition;

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `ZSS-QY-WL-C-MS.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
