### ISSUE TITLE
[New device support]: Philips Hue Lightguide Globe G95

### ISSUE THREAD

**Issue by olivercjung** [Koenkk/zigbee2mqtt#25230]
### Link

https://www.philips-hue.com/de-de/p/hue-white-color-ambiance-g95-smarte-lampe-e27/8719514419155

### Database entry

I need help to find this...

### Zigbee2MQTT version

1.42.0-2

### Comments

When trying to pair that device, zigbee2mqtt says "[Device unknown](z2m: Device '0x001788010d83b1e1' with Zigbee model 'LCO001' and manufacturer name 'Signify Netherlands B.V.' is NOT supported, please follow https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html)".

Unfortunately, I do not know how to get to the "Database entry" which is asked for above. Please let me know and I will immediately do that.

### External definition

```shell
const {philipsLight} = require('zigbee-herdsman-converters/lib/philips');

const definition = {
    zigbeeModel: ['LCO001'],
    model: 'LCO001',
    vendor: 'Signify Netherlands B.V.',
    description: 'Automatically generated definition',
    extend: [philipsLight({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"],"enhancedHue":true}})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Works:
Off/On
Brightness
Color 
Color Temp

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `8719514419155.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
