### ISSUE TITLE
No converter available for 'osram_remember_state'

### ISSUE THREAD

**Issue by Nephiel** [Koenkk/zigbee2mqtt#2529]
# Bug Report
## What happened
Attempting to configure OSRAM AC03641 bulbs as per the [documentation](https://www.zigbee2mqtt.io/devices/AC03641.html) to remember a default state fails. 

## What did you expect to happen
The bulb to be configured to remember a default state of OFF.

## How to reproduce it (minimal and precise)
Once the bulb is added to the zigbee network, send a MQTT command of ```{"state": "OFF","osram_remember_state": true}``` to ```zigbee2mqtt/[FRIENDLY_NAME]/set``` using any MQTT client.

## Debug Info
zigbee2mqtt version: ```zigbee2mqtt version 1.7.1 (commit #b459c35)```
CC2531 firmware version: ```'{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}'```

Relevant log:
```
debug 2019-12-14T18:03:11: Received MQTT message on 'zigbee2mqtt/bombilla_lampara_salon_3/set' with data '{
  "state": "OFF",
  "osram_remember_state": true
}'
debug 2019-12-14T18:03:11: Publishing 'set' 'state' to 'bombilla_lampara_salon_3'
info  2019-12-14T18:03:11: MQTT publish: topic 'zigbee2mqtt/bombillas_lampara_salon', payload '{"state":"OFF","brightness":0}'
info  2019-12-14T18:03:11: MQTT publish: topic 'zigbee2mqtt/bombilla_lampara_salon_3', payload '{"state":"OFF","last_seen":"2019-12-14T19:03:11+01:00","brightness":0,"device":{"friendlyName":"bombilla_lampara_salon_3","ieeeAddr":"0x7cb0xxxxxxxxxxxx","networkAddress":yyyy,"type":"Router","manufacturerID":48042,"manufacturerName":"OSRAM","powerSource":"Mains (single phase)","applicationVersion":0,"stackVersion":2,"zclVersion":1,"hardwareVersion":1,"dateCode":"20140331CNEF****","softwareBuildID":"V1.04.12"}}'
error 2019-12-14T18:03:11: No converter available for 'osram_remember_state' (true)
```

**Comment by Koenkk** [comment]
Fixed in latest dev branch, thanks!
