### ISSUE TITLE
Add link to "report" page from "Binding" page

### ISSUE THREAD

**Issue by marrold** [Koenkk/zigbee2mqtt#2530]
There's no mention of the "report" function on the "binding" page. 

I think it would be a nice idea to add the link, for people (like me) expecting to get state updates when a switch bound to bulb / group / etc 

I would submit a PR to the docs themselves, but I don't know where they are hosted?

**Comment by sjorge** [comment]
They are hosted here https://github.com/Koenkk/zigbee2mqtt.io, the reporting page is https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/report.md

**Comment by Koenkk** [comment]
added, thanks!
