### ISSUE TITLE
[Feature request]: support Binding to Cluster (Closure) and scenes for TS0601 _TZE200_68nvbio9

### ISSUE THREAD

**Issue by kiwibayer** [Koenkk/zigbee2mqtt#25311]
### Is your feature request related to a problem? Please describe

I have multiple TS0601 _TZE200_68nvbio9 zigbee devices that are working well within Z2M. However I cannot bind them to a useful cluster with some of my zigbee remotes. Currenlty only the Groups Cluster is exposed, I would like to have a Closures Cluster exposed so I can bind the devies with my Remote. 

Addtional I would like to set scenes for the device 

### Describe the solution you'd like

Able to bind the device with a open / close remote that allows the currtain to open close without having to go via a coordinator

### Describe alternatives you've considered

Do this via Groups / Scenes, however Scenes are also not possible with the device 

### Additional context

![image](https://github.com/user-attachments/assets/e5c6c47d-0702-4c59-86fe-5c5f1acd743f)
![image](https://github.com/user-attachments/assets/1bdda4d5-1bff-4a2f-a48e-67f4ce256a33)

**Comment by Koenkk** [comment]
The device does not support this (most Tuya devices don't support the standard Zigbee clusters), this is not something that Z2M can fix unfortunately.
