### ISSUE TITLE
[New device support]: Innr Smart Filament Bulb E27 Tunable Globe RF 271 T

### ISSUE THREAD

**Issue by mauriceknarren** [Koenkk/zigbee2mqtt#25312]
### Link

https://www.innr.com/en/product/innr-smart-filament-bulb-e27-tunable-globe-2024/

### Database entry

{"id":121,"type":"Router","ieeeAddr":"0xa4c138e6fc289f07","nwkAddr":35266,"manufId":4454,"manufName":"innr","powerSource":"Mains (single phase)","modelId":"RF 271 T","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"RF 271 T","manufacturerName":"innr","powerSource":1,"zclVersion":8,"appVersion":23,"stackVersion":54,"hwVersion":1,"dateCode":"20240613","swBuildId":"1.7.16"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":556}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":170}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":23,"stackVersion":54,"hwVersion":1,"dateCode":"20240613","swBuildId":"1.7.16","zclVersion":8,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1734996465078}

### Zigbee2MQTT version

1.42.0

### Comments

OTA unavailable.
The RF 261 is supportted by z2m though (almost the same filament bulb) and does support OTA.

### External definition

```shell
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['RF 271 T'],
    model: 'RF 271 T',
    vendor: 'innr',
    description: 'Automatically generated definition',
    extend: [light({"colorTemp":{"range":[153,556]}})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

OTA unavailable.
The RF 261 is supportted by z2m though (almost the same filament bulb) and does support OTA.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) tomorrow. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198

Could you also submit a picture for the docs? This can be done by:
1. Create a fork by clicking [here](https://github.com/Koenkk/zigbee2mqtt.io/fork)
2. Go to the `public/images/devices` directory, *Add file* -> *Upload files*
3. Upload the files and press *Commit changes*
4. Press *Contribute* -> *Open pull request* -> update title/description -> *Create pull request*

Make sure that:
- The filename is `RF 271 T.png`
- The size is 512x512
- The background is transparent (use e.g. [Adobe remove background](https://new.express.adobe.com/tools/remove-background))
