### ISSUE TITLE
Crash at settings development in zigbee coordinator

### ISSUE THREAD

**Issue by gehtnixx** [Koenkk/zigbee2mqtt#25356]
### What happened?

![image](https://github.com/user-attachments/assets/9829516f-4b80-491d-a1e4-e934d7e746c0)
When i go to Entwickler Konsole it shows me a Bug to report
[initialState.json.zip](https://github.com/user-attachments/files/18266845/initialState.json.zip)
![image](https://github.com/user-attachments/assets/8bd836f9-dea6-44fa-9335-296787b2f812)

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

20230507

### Adapter

CZC-1.0

### Setup

Linux on ESXI

**Comment by Koenkk** [comment]
This has been fixed in the dev branch already

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
