### ISSUE TITLE
YRD226 TSDB Publish 'set' 'state' to 'entrance_lock' failed: 'Error: Timeout - 38588 - 1 - 2 - 257 - 11 after 15000ms'

### ISSUE THREAD

**Issue by kimet83** [Koenkk/zigbee2mqtt#2541]
When starting the program, the following error is reported:

error 2019-12-17 03:55:28: Publish 'set' 'state' to 'entrance_lock' failed: 'Error: Timeout - 38588 - 1 - 2 - 257 - 11 after 15000ms'
info  2019-12-17 03:55:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'entrance_lock' failed: 'Error: Timeout - 38588 - 1 - 2 - 257 - 11 after 15000ms'","meta":{"friendly_name":"entrance_lock"}}'

doorlock model is yale YRD226 TSDB
zigbee2mqtt version: 1.8.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
You probably have to disable the default response, example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L4697

Guide on how to reach to `devices.js`: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
