### ISSUE TITLE
 Lines are not drawn between devices. sonoff switch and xiaomi plug

### ISSUE THREAD

**Issue by kimet83** [Koenkk/zigbee2mqtt#2542]
other devices are ok. but  Lines are not drawn between some devices.

Problem devices include the following: SONOFF zigbee switch, xiaomi plug

## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version: 20190608

**Comment by pcb1962** [comment]
#2436

**Comment by Koenkk** [comment]
Indeed duplicate of #2436
