### ISSUE TITLE
get_group_membership do not answer with friendly names

### ISSUE THREAD

**Issue by FabienTregan** [Koenkk/zigbee2mqtt#2546]
# Bug Report
## What happened

`get_group_membership` do not answer with friendly names, it does with ieeeAddr

## What did you expect to happen

Either of:
 - Same answer with friendly name or ieeeAddr.
 - The [documentation](https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html) should tell to use ieeeAddr and not friendly_name.

## How to reproduce it (minimal and precise)

 - Give an ikea tradfri bulb the friendly name  `lum/salon/n6` (are slashes relevant ?)
 - Add it to group 1 (I did this through `configuration.yaml.`)
 - Check you can access it via either ieeAdd or firendlyName :
```
zigbee2mqtt/0xccccccfffe3c7387/get x
zigbee2mqtt/lum/salon/n6 {"state":"ON","brightness":0,"linkquality":120}
zigbee2mqtt/lum/salon/n6/get x
zigbee2mqtt/lum/salon/n6 {"state":"ON","brightness":0,"linkquality":115}
```
 - Try to get its groups memberships with friendly name:
```
zigbee2mqtt/bridge/device/lum/salon/n6/get_group_membership x
```
(no answer)
 - Try the same thing with ieeeAddr:
```
zigbee2mqtt/bridge/device/0xccccccfffe3c7387/get_group_membership x
zigbee2mqtt/lum/salon/n6 {"state":"ON","brightness":0,"linkquality":115,"group_list":[],"group_capacity":255}
```

## Debug Info
zigbee2mqtt version: zigbee2mqtt version 1.7.1 (commit #b459c35)
CC253X firmware version: CC2531_DEFAULT_20190608

**Comment by Koenkk** [comment]
Did you try with zigbee2mqtt 1.8.0?
