### ISSUE TITLE
Coordinator always red

### ISSUE THREAD

**Issue by Stoimie** [Koenkk/zigbee2mqtt#2549]
Hi, I have a problem, the coordinator in my map is always displayed in red, although there are active connections and they are displayed in green. However, I find the connection quality rather poor, although the sensors are less than 2m away. I connected the USB stick to the Raspberry with a 2m cable. The teach-in also only works after countless attempts. I already ordered a new stick in the hope that it is a hardware problem. Has anyone else had this problem?

<img width="522" alt="Bildschirmfoto 2019-12-17 um 20 50 12" src="https://user-images.githubusercontent.com/11144890/71029061-e137a300-210e-11ea-84b1-13ee9cb76826.png">

**Comment by Koenkk** [comment]
You are using iobroker, this is the zigbee2mqtt issue tracker. please open an issue there: https://github.com/ioBroker/ioBroker.zigbee/issues
