### ISSUE TITLE
New Device Homa 1001 RGB Controller

### ISSUE THREAD

**Issue by Haui74** [Koenkk/zigbee2mqtt#2555]
Can you please add support for this 4 channel RGBW controller.

Thanks a lot!!

![Bild](https://user-images.githubusercontent.com/59011775/71072347-96ee0a80-217e-11ea-97fd-2892fe50ad54.JPG)
![Kachel](https://user-images.githubusercontent.com/59011775/71072348-96ee0a80-217e-11ea-9276-34f203651325.JPG)
![MeldungLog](https://user-images.githubusercontent.com/59011775/71072349-96ee0a80-217e-11ea-9895-3fc4eb1fb1ca.JPG)

**Comment by Haui74** [comment]
Can you ?help me please

**Comment by Koenkk** [comment]
See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by Haui74** [comment]
Can you please add the device, its to complicated to me. Im not a programmer ;) Thank you very much!! :)
