### ISSUE TITLE
Need help to add Feller Smart Light Control EdizioDue

### ISSUE THREAD

**Issue by kalsan** [Koenkk/zigbee2mqtt#2569]
I'm attempting to support the new device Feller EdizioDue 1903fh, a product of the "Friends of Hue" program by Swiss manifacturer Feller. The cool thing about it is that it's piezo-electric, i.e. no batteries needed. According to the product page, a Hue v2 bridge is required. I fail to connect the device to zigbee2mqtt, the pairing does not seem to take place, the logs show nothing.

Here's a link to the product page: https://www.feller.ch/de/Produktangebot/Funktaster/Zusatzinformationen

Here's a video of how they pair it to an actual Hue bridge: https://www.youtube.com/watch?v=ox1YBWgCxoo&t=385s

When I set permit_join to true and attempt to connect as in the video, nothing happens. I'm new to zigbee, but I read that any zigbee/lightlink device should work with zigbee2mqtt.

Which further steps can I take to analyze and ideally solve the problem?

**Comment by kalsan** [comment]
After investigating a little more, I found out that the Feller switch uses Zigbee Green Power. According to #211, Z-Stack 3.0 is required for Green Power, which is still experimental according to #1445. I couldn't quite figure out from these issues whether Green Power already works with Z-Stack 3.0 or whether it's just possible to potentially make it work. I think I will give it a try, though.

**Comment by yvansandoz** [comment]
Did you find a workaround to connect your Feller EdizioDue with Zigbee2MQTT?

**Comment by UnconventionalMindset** [comment]
If anyone needs to know how, I managed with this guide: https://www.zigbee2mqtt.io/devices/PTM_215Z.html

**Comment by kalsan** [comment]
Indeed! Bought a Feller and it worked immediately after resetting using the procedure described in the PTM 215Z guide :+1:
