### ISSUE TITLE
CC2530-Esp8266 Socat is unnecessary

### ISSUE THREAD

**Issue by mr2c12** [Koenkk/zigbee2mqtt#2576]
Considering
https://www.zigbee2mqtt.io/information/connecting_cc2530.html
and
https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

I've just verified that you could completely skip the "socat part" to connect to the esp8266 running espeasy. You could just connect to it setting the tcp://ip:port as per the second guide.

**Comment by Koenkk** [comment]
Thanks for finding this out, updated the guide!
