### ISSUE TITLE
WXKG01LM - cannot get node descriptor

### ISSUE THREAD

**Issue by jeroenterheerdt** [Koenkk/zigbee2mqtt#258]
When I try to add my WXKG01LM I get the famous 'cannot get node descriptor' error. What I do get for every button press is:
`
2018-8-7 15:21:51 DEBUG Recieved zigbee message with data {"cid":"genAnalogInput","data":{"presentValue":39.15999984741211}}
`

I am not sure on how to solve this. I tried replacing battery as is in the wiki. The button works fine with the Xiaomi gateway. Is there anything I can do to debug this? Is there some output setting that might help?

**Comment by cmille34** [comment]
Ive paired  a few of these without too much trouble.  I found holding the pin hole button for 5-10 seconds until its blinking then repeatedly pressing it again every couple seconds until its full connected helped.  YMMV.

**Comment by jeroenterheerdt** [comment]
@cmille34 do you mean pressing the pin hole button every couple seconds? or the button itself?

**Comment by jeroenterheerdt** [comment]
never mind, the trick to push the pinhole every couple seconds worked. thanks.
