### ISSUE TITLE
Loosing link quality since update 1.7.1-1.8.0

### ISSUE THREAD

**Issue by Ormerod2** [Koenkk/zigbee2mqtt#2595]
#Bug Report 
Since Update 1.71 I keep having  issues with link quality. It was running fine before with good linkquality. Additionally I am having issues with osram plugs as well. Only when close to coordinator, they are running good. 

## What happened
All devices, most Xiaomi, are reporting lower link quality or lost connection 
![D56E86E4-B29A-49A3-A5F8-5E53F9CB21EC](https://user-images.githubusercontent.com/45901368/71377675-c4471800-25c5-11ea-8b0b-0c874a20d9f6.jpeg)

## What did you expect to happen
Remaining in the same quality as before

## How to reproduce it (minimal and precise)
Data’s are persistent. 

## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version: Dec 23 20:55:12 openHABianPi npm[22465]: zigbee2mqtt:info  2019-12-23 20:5                                                                        5:12: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version"                                                                        :"1.8.0","commit":"da4d26a","coordinator":{"type":"zStack12","meta":{"tran                                                                        sportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":                                                                        20190515}},"log_level":"info","permit_join":true}'

Additional information: running my own setup of hardware: 
![C0E17EB2-F677-4A40-9CB8-FD2DC06AAFD7](https://user-images.githubusercontent.com/45901368/71378341-b7c3bf00-25c7-11ea-89ff-35602781f78b.jpeg)

But haven’t touched hardware for months 

Feel free to close issue if not related to software.

**Comment by zhapwey** [comment]
hello could you say if that SHIELD for the adapter is yours or what is it ??

**Comment by Ormerod2** [comment]
Yes it is mine. Working on a release version right now. It come pretty handy with an 100mw amplifier. 1 coordinator for the entire house

**Comment by Ormerod2** [comment]
Found issue with antenna. Seems my vacuum robot pulled it of a little

Sorry for bordering
