### ISSUE TITLE
Increase device limit beyond 48 devices

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#26]
This is currently a limitation of the firmware for the CC2531.

Some resources:
* https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/p/509541/1848708

**Comment by ciotlosm** [comment]
Is there a way to get the a link to the firmware source code with details on how to build it as well?

**Comment by Koenkk** [comment]
@oskarn97 would it be possible to share any details on how you compiled this firmware?

**Comment by oskarn97** [comment]
It is not possible to increase the device limit beyond 48 devices since to memory limitation on the Chip. I compiled the Z Stack Home with IAR Embedded Workbench with some flags required for encryption and maximum device limit.

**Comment by Koenkk** [comment]
Would it be possible to reduce the size of the firmware so there is more memory left for devices? http://processors.wiki.ti.com/index.php/Optimizing_Flash_and_RAM_Usage_of_Z-Stack_for_CC2530

**Comment by Koenkk** [comment]
I doubt if `NWK_MAX_DEVICE_LIST` defines the maximum number of devices in the network. In this [official Texas Instruments document](http://www.compel.ru/wordpress/wp-content/uploads/2014/02/swra427b.pdf) chapter 4 Z-Stack Knobs they are talking about a 400+ nodes network while only having set `NWK_MAX_DEVICE_LIST` to `10`. I have the feeling that when adding more routers to your network you can add more nodes to your network.

Maybe 48 devices is not the limit at all....

**Comment by oskarn97** [comment]
Yes, the device limit refers to the number of devices that can be paired to a single coordinator. You can use more of course.

**Comment by ioudeveldhuis** [comment]
@oskarn97 Could you still tell us what you changed / done to compile the firmware and how to generate the .hex file ?

**Comment by oskarn97** [comment]
I've just increased the device limit and enabled secure link join. Apart from that I did not modify the default TI Z Stack Home.
<img width="626" alt="bildschirmfoto 2018-05-21 um 10 28 45" src="https://user-images.githubusercontent.com/1344990/40298164-6db66ebc-5ce2-11e8-9ed0-852e61c1c378.png">

**Comment by Koenkk** [comment]
By reducing the `MAXMEMHEAP` in `OnBoard.h` to e.g. 1000 I was able to compile with `NWK_MAX_DEVICE_LIST    90`.

@osarkn97 how did you enable secure link join?

**Comment by oskarn97** [comment]
add the "TC_LINKKEY_JOIN" compile on the preprocessor option

**Comment by ptvoinfo** [comment]
@Koenkk Is it safe to reduce MAXMEMHEAP?

**Comment by Koenkk** [comment]
@ptvoinfo we need to do some tests with it.

**Comment by Koenkk** [comment]
I think it's not possible to reduce the heap size, I'm getting the same error as #65 in this case.

**Comment by Koenkk** [comment]
I've created a [wiki page](https://github.com/Koenkk/zigbee2mqtt/wiki/ZigBee-network#network-size) which explains how to add more than 48 devices to your network.

**Comment by Koenkk** [comment]
@makuser maybe; but that setup is much more expensive.

For now I don't see any problem when using the CC2531/CC2530 with the current firmwares. It's stable even for larger networks.

**Comment by vpomax** [comment]
I have 32 xiaomi zigbee devices...
I need to use 1 coordinator e 2 router CC2531 to manage all 32 devices?

**Comment by Koenkk** [comment]
@vpomax could be a bit tricky, I would recommend adding another CC2531 router to be sure.

**Comment by cmorlok** [comment]
With the alternative firmware from
https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/CC2531/alternatives/max_devices/
it should be possible to use 44 devices with one CC2531 without router.

**Comment by Koenkk** [comment]
@cmorlok yes, but note that that firmware **could** have some downsides. It has less memory available which could lead to freezing and less responsive devices.

**Comment by cmorlok** [comment]
Is the limit for cc2530 the same?

**Comment by Koenkk** [comment]
Yes
