### ISSUE TITLE
 Will the Ferguson FS1SD smoke detector work with Zigbee2MQTT ?

### ISSUE THREAD

**Issue by lokomotionn** [Koenkk/zigbee2mqtt#260]
Hello, does the Ferguson FS1SD smoke detector "http://ferguson-digital.eu/en/smart-home-ferguson/smart-home-smoke-detector-fs1sd/" work with zigbee2mqtt? If so, what will have to be done. I am waiting for the shipment cc2530 and programmer, but in the meantime I would like to buy several modules for testing. Smoke detector by Ferguson is at a good price, but is it worth buying? I will not stay with a nice paper button ?

**Comment by ryanbeaton** [comment]
Note they are sold under other names on AliExpress. There is also a gas sensor and a CO sensor. I don’t have any, have just seen them listed before. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
