### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by CatMonster** [Koenkk/zigbee2mqtt#2600]
Unable to install zigbee2mqtt on orangePi Zero
Tried with node 10, 12, 13 and not working

# Bug Report
## What happened
Followed until point 2. to https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

## What did you expect to happen
After running `npm install` lot of errors are thrown, see paste -> https://paste.ubuntu.com/p/C6WzYzZftS/

## Debug Info
zigbee2mqtt version: 1.8.0
CC2531 firmware version: CC2531_20190425.zip 3.0.x

**Comment by jasperro** [comment]
Is your issue https://github.com/lovell/sharp/issues/1087? If so, you need to run `sudo apt-get install python-dev`
