### ISSUE TITLE
Installation fails with error on events.js

### ISSUE THREAD

**Issue by gischio** [Koenkk/zigbee2mqtt#2601]
Greetings,
I'm going crazy with the installation of zigbee2mqtt 1.8.0 on a Raspbian 4.19.88-v71+.
The error log is attached.
[errore_.txt](https://github.com/Koenkk/zigbee2mqtt/files/3998698/errore_.txt)

It seems to refer to events.js file, however I'm not familiar with this.
Did anybody experience something like this?
Thanks in advance,
gischio

**Comment by didiht** [comment]
`Error: Connection refused: Not authorized`

It seems you have wrong credentials for accessing your mqtt server.

**Comment by gischio** [comment]
It works now, thanks a lot!

**Comment by didiht** [comment]
You are welcome!

Since your problem is solved you should close this issue.

**Comment by gischio** [comment]
Sure!
