### ISSUE TITLE
Unable to connect a device anymore

### ISSUE THREAD

**Issue by oli-19** [Koenkk/zigbee2mqtt#2610]
Hi
I have a CC2531 ZigBee USB stick connected with the zigbee adapter on iobroker.
The devices I already connected work fine but unfortunately I can't add devices anymore.
I tried 2 xiaomi buttons and a Xiaomi human body sensor, both of which cannot be connected even though I have already connected both while ago.
The countdown to pair the devices is just runnig down without an error or any other message.

**Comment by Koenkk** [comment]
Please open an issue here https://github.com/ioBroker/ioBroker.zigbee/issues , this is the zigbee2mqtt issue tracker.
