### ISSUE TITLE
friendly_name vs device_id

### ISSUE THREAD

**Issue by runningman84** [Koenkk/zigbee2mqtt#2614]
It would be great to use the device_id as identifier in home assistant but use the friendly_name just as an additional attribute. This used to work just fine but I migrated my zigbee2mqtt instance and now all devices are lost in homeassistant and new devices are created with their friendly_name as device id:

before
sensor.0x00158d0001833b20_temperature
after
sensor.kitchen_temperature

Is this an expected behaviour?

## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version:

**Comment by Koenkk** [comment]
This is indeed expected behaviour, when you migrate zigbee2mqtt you can copy your configuration.yaml to avoid this.

**Comment by runningman84** [comment]
The funny thing is that I copied all files but still the sensors are renamed

**Comment by runningman84** [comment]
It would be great to have the option to have sensors with their unique device id and use the friendly_name just as a frriendly name as home assistant.

**Comment by runningman84** [comment]
Today I renamed all sensors in the configuration.yaml. According to the zigbee2mqtt logs everything is published with the new names.

But in home assistant the device id is still an old id but the friendly name is new (it matches the name in the configuration.yaml).

I had to remove the file ./.storage/core.entity_registry in order to force home assistant to use the new names...
