### ISSUE TITLE
Paring devices with fixed location

### ISSUE THREAD

**Issue by dbruggner** [Koenkk/zigbee2mqtt#2615]
Is it possible to somehow pair devices which have a fixed location (cannot be moved) assuming the coordinator also can't be moved?

For example the Philipse Hue bridge offers a discovery mode and entering of the serial number.

**Comment by Koenkk** [comment]
This Hue specific command has not been added to zigbee2mqtt yet (not sure if its possible).

**Comment by andreasbrett** [comment]
I do these kinds of pairings with a cc2530 (as a router) that is  powered via USB battery. Let's me get close to devices for pairing (especially useful for trådfri that need to be very close while pairing).
