### ISSUE TITLE
New Device: LWA005 - Philips Hue Single Filament Bulb w/Bluetooth

### ISSUE THREAD

**Issue by skawt-tee** [Koenkk/zigbee2mqtt#2619]
I've gone thru the new device support documentation and have confirmed the following as working using the 'hassio' method, but don't know git well enough to submit this properly. I'd appreciate if this could be added, thanks!

New Device addition request:
{
    zigbeeModel: ['LWA005'],
    model: '9290022411',
    vendor: 'Philips',
    description: 'White Single Filament Bulb A19 E26 with Bluetooth',
    extend: hue.light_onoff_brightness,
},

--------
homeassistant.js:
    '9290022411': [cfg.light_brightness],

**Comment by Koenkk** [comment]
Added, will be supported in dev branch within a few days.
