### ISSUE TITLE
Any plans for 1.8.1 ?

### ISSUE THREAD

**Issue by johntdyer** [Koenkk/zigbee2mqtt#2658]
I use hass.io plugin and I i'd love to get the fix from https://github.com/Koenkk/zigbee-herdsman-converters/issues/749 available to me... hoping you may comment on when you plan to cut a new release ? thanks again !

**Comment by nldroid** [comment]
If you really need it, you can always use the dev version:

https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

My experience is, is that it's stable enough. And when 1.8.1 is released, you can always go back to the normal releases.

**Comment by Koenkk** [comment]
You can indeed use the dev branch for now, no eta for 1.8.1/1.9 yet.
