### ISSUE TITLE
zigbee2mqtt with reporting enabled to set device as unavailable when it doesn't respond

### ISSUE THREAD

**Issue by ejalal** [Koenkk/zigbee2mqtt#2662]
# Bug Report
## What happened
I enabled reporting on my zigbee2mqtt installation (hassio official addon), so it gets states when my Hue light bulbs are switched on from the wall switch. The problem with the current implementation is that the lights stay ON on MQTT/hassio indefinitely when they are switched off from the wall switch as zigbee2mqtt can no longer get their current state 

```
zigbee2mqtt:error 2020-01-03 10:30:26: Failed to execute LQI for '0x086bd7fffe06bd8e' (This is an Ikea Tradfri wall switch that I unplugged)
zigbee2mqtt:error 2020-01-03 10:30:37: Failed to execute LQI for '0x001788010820bcd4' (This is an Hule light bulb switched off from wall switch)
zigbee2mqtt:error 2020-01-03 10:30:47: Failed to execute LQI for '0x00178801082723c1' (Same as above)
zigbee2mqtt:error 2020-01-03 10:30:57: Failed to execute LQI for '0x00178801081fe6f4' (Same as above)
zigbee2mqtt:error 2020-01-03 10:31:07: Failed to execute LQI for '0x001788010827cbd1' (Same as above)

```
## What did you expect to happen
I would like to be able to either
- Let Zigbee2mqtt decide of a default state set to "Unavailable" in Hassio, this can probably be acheived by deleting the last MQTT message from the device topic so Hassio understands the device is unavailable. 
- Let the user choose to force the state to OFF if the device doesn't respond to LQI request.

## How to reproduce it (minimal and precise)
Enable reporting as below, switch off a few light bulbs or wall outlets restart zigbee2mqtt and wait.
```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.0.1",
    "user": "user",
    "password": "password"
  },
  "serial": {
    "port": "/dev/ttyACM0",
    "disable_led": true
  },
  "advanced": {
    "report": true,                   #Add this line here
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  }
}

```
## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version: Z-Stack_Home_1.2 (CC2531_DEFAULT_20190608.zip)

**Comment by MaZZly** [comment]
Looking for a solution to the same problem I found this: https://community.home-assistant.io/t/zigbee2mqtt-light-still-showing-up-even-when-powered-off/140167

So try setting the `availability_timeout` setting if it works?
