### ISSUE TITLE
Sonoff Basic ZBR3 Stability Issue

### ISSUE THREAD

**Issue by delta010** [Koenkk/zigbee2mqtt#2663]
# Bug Report

2020-01-03 16:12:29: Publish 'set' 'state' to '0x00124b001e721b30' failed: 'Error: Data request failed with error: 'No network route' (205)'

## What happened

I am Using cc2531 Zigbee sniffer with Home assistant  aome time when i trun in the device nothing happend ,Random Time Out Error and No network route

## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version:  CC2531_DEFAULT_20190608

**Comment by SittingDuc** [comment]
Hello,
What distance is between the ZBR3 and the coordinator? 
How many other devices are connected to the coordinator?
