### ISSUE TITLE
Maximum ammount of routers - CC2531

### ISSUE THREAD

**Issue by tabnul** [Koenkk/zigbee2mqtt#2669]
Currently i have 1 CC2531 coordinator, ~10 ikea tradfri routers and 1 additional CC2531 router stick. And some end-devices connecting to the routers.
I want to expand ikea devices (so add more routers effectively).

I know the CC2531 stick has a limit of 15 devices, which can be expanded by adding routers.
But what if i implement more than 15 routers? They all connect directly to the CC2531 stick (and to each other). CC2531 will be flooded i guess? 
What will happen?

![network_map](https://user-images.githubusercontent.com/16493960/71763826-d0de4100-2ee0-11ea-8945-8446640ee64f.png)

**Comment by groenmarsmannetje** [comment]
You can add more without problem. I have now 36 routers and 29 end-points connected to one CC2531 coordinator. Mesh network is operating. Sometimes a device disconnects and need to be reconnected. But I had that also when the network had much less devices. I needed to start using the source routing firmware when I reached 40 devices.
