### ISSUE TITLE
MQTT Last will message

### ISSUE THREAD

**Issue by ualex73** [Koenkk/zigbee2mqtt#267]
At this moment zigbee2mqtt sends a message when it connects to the MQTT broker, but is it possible to also configure a last will? Then the MQTT broker will send a message when zigbee2mqtt disconnect at an error (and won't send an offline message).

The JS module should support this:
https://github.com/mqttjs/MQTT.js#client

will: a message that will sent by the broker automatically when the client disconnect badly. The format is:
    topic: the topic to publish
    payload: the message to publish
    qos: the QoS
    retain: the retain flag

**Comment by Koenkk** [comment]
Implemented in dev branch, can you check?

**Comment by ualex73** [comment]
I can confirm it works! Only I found another 'bug' with a docker restart, will report it separately.

**Comment by tb-killa** [comment]
@ualex73 Please report your ``bug`` here so @Koenkk could fix it asap (if he has the time!).
