### ISSUE TITLE
AC08562: Colour Temperature (Osram E14) supported but not OOB

### ISSUE THREAD

**Issue by DeliriousMetro** [Koenkk/zigbee2mqtt#2682]
# Bug Report
## What happened

The Osram AC08562 has a built in tunable colour temperature, which is not mentioned as being supported by the wiki but I have gotten it to work by adding the color_temp: true in the devices.yaml - maybe this could be added to work oob?

https://www.zigbee2mqtt.io/devices/AC08562.html

Model | AC08562
-- | --
Vendor | OSRAM
Description | SMART+ Candle E14 Dimmable White
Supports | on/off, brightness _**and colour temperature**_

## What did you expect to happen

All features to be working out of box. By adding a single line of color_temp: true, to devices.yaml this now works :)

## How to reproduce it (minimal and precise)

Add a new osram bulb to my zigbee network, the bulb functions normally but it is missing the colour temperature. All I ask for is to make it enabled as stock as it is something that can be done to help out new users.

## Debug Info
zigbee2mqtt version: 1.8.0
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
Updated, will be available in the latest dev brach in a few hours, documentation will automatically be updated on the next zigbee2mqtt release. thanks!
