### ISSUE TITLE
Hue a. Tradfri Brightness

### ISSUE THREAD

**Issue by R-Rosenow** [Koenkk/zigbee2mqtt#2694]
#Bug Report
##What happened
My Hue and Tradfri Bulbs are connected to a CC2531 with the latest firmware. ZigBee2mqtt runs at the latest firmware.

When I turn the bulbs on, they start with 10% Brightness an Color white. I want to have the same Color and Brightness as I turn them off.

At the Hue Bridge they start automatically at the old State.

##What did you expect to happen
The CC2531 runs on a RPi 3 B+ and the Mqtt Broker sends from OpenHAB.

**Comment by mr2c12** [comment]
I am using Home Assistant, but my tradfiri bulbs works as expected: when I turn them on, they have the same brightness and color temperature as when they were turn off. Could it be something related to openHab?
