### ISSUE TITLE
Make PIR sensor no_motion timeout configurable per device

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#27]
This timeout is now fixed to 3 minutes, it would be nicer if this could be overridden per device.

**Comment by ciotlosm** [comment]
This should be 1 minute to match what is currently used from the gateway and then make it configurable.

**Comment by dabont** [comment]
I would really like to see this implemented

**Comment by Koenkk** [comment]
Wiki has been updated: https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge#3-optional-device-specific-configuration
