### ISSUE TITLE
Missing docs for color values

### ISSUE THREAD

**Issue by sapkra** [Koenkk/zigbee2mqtt#271]
I have a color picker in openHAB and want to use these values for changing the color of my OSRAM light bulb but I can't find any documentation what kind of values x & y are expecting.

**Comment by Koenkk** [comment]
This provides information about the xy values:  http://www.developers.meethue.com/documentation/hue-xy-values .

In #272 this RGB to XY conversion will be implemented in zigbee2mqtt.

**Comment by tb-killa** [comment]
@sapkra we got now rgb converter too. 
Do you check?
Could we close this?

**Comment by sapkra** [comment]
The rgb values are also a solution for my problem. Thanks.
