### ISSUE TITLE
Forcing a flush of configuration.yaml

### ISSUE THREAD

**Issue by mikeage** [Koenkk/zigbee2mqtt#2724]
# Bug Report
## What happened
I accidentally erased (well, ran `git checkout .`) my configuration.yaml, but zigbee2mqtt is still running. Is there any way to tell it to dump the current configuration to the file?

## What did you expect to happen
n/a

## How to reproduce it (minimal and precise)
n/a

## Debug Info
zigbee2mqtt version: 260d290
CC253X firmware version: n/a

**Comment by Koenkk** [comment]
Unfortunately this is not possible

**Comment by mikeage** [comment]
ok, thanks! I'll try tonight

**Comment by mikeage** [comment]
I wasn't clear on whether I had to first create the group then assign a device, so I tried something else; setting `last_seen` to `disable` did the trick.

`mosquitto_pub -t zigbee2mqtt/bridge/config/last_seen -m 'disable' -h localhost -p 1883`

Thanks!
