### ISSUE TITLE
CC2531+Esp8266 Ser2Tcp, is it possible?

### ISSUE THREAD

**Issue by githubutilities** [Koenkk/zigbee2mqtt#2732]
Is it possible to setup TCP connection with CC2531+esp8266, I recently trying to 
connect it, but i just found [CC2530 solution](https://github.com/Koenkk/zigbee2mqtt/issues/665).

**Comment by linwinDE** [comment]
Maybe this can help you:   [https://github.com/arendst/Tasmota/wiki/Zigbee](url)

**Comment by githubutilities** [comment]
Tasmota solution is in early development states which does not support CC2531 chip.
