### ISSUE TITLE
Error: Cannot restore backup, backup is for 'undefined', current is 'zStack'

### ISSUE THREAD

**Issue by Ricco59163** [Koenkk/zigbee2mqtt#2747]
# Bug Report
## Debug Info
zigbee2mqtt version:1.8 master
CC253X firmware version:cc2531

**Comment by Ricco59163** [comment]
sorry i m  a newbie on z2m , can you help me for this fault?

Error: Cannot restore backup, backup is for 'undefined', current is 'zStack'

i have used all cc2531 firmware but it's always the same issues .... :(

thx team

**Comment by Koenkk** [comment]
see https://github.com/Koenkk/zigbee2mqtt/issues/2733#issuecomment-574082470
