### ISSUE TITLE
Gledopto GL-C-007 Timeout

### ISSUE THREAD

**Issue by CSchlipp** [Koenkk/zigbee2mqtt#2755]
# Bug Report
## What happened
I recently moved a Gledopto device from my Hue Bridge to Zigbee2Mqtt. Pairing was successful, but after a few hours of not using the device, every command sent to it times out:
```
zigbee2mqtt:info  2020-01-16 08:08:24: 0x00124b001d04e200 (0x00124b001d04e200): GL-C-007 - Gledopto Zigbee LED controller RGBW (Router)
zigbee2mqtt:error 2020-01-16 08:11:06: Publish 'set' 'state' to '0x00124b001d04e200' failed: 'Error: Timeout - 49780 - 11 - 2 - 6 - 11 after 15000ms'
zigbee2mqtt:info  2020-01-16 08:11:06: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x00124b001d04e200' failed: 'Error: Timeout - 49780 - 11 - 2 - 6 - 11 after 15000ms'","meta":{"friendly_name":"0x00124b001d04e200"}}'
```
If I disconnect the device from mains and reconnect, it's working again for a short amount of time. Restarting Z2M does not make any difference, the device is still unresponsive afterwards.

As this issue did never occur during Hue-Bridge usage, this is potentially no hardware failure of the device itself. 

Could it be that Z2M messages in the device are filling up a queue or the device is flooded with messages so it finally hangs up? (Just thinking out loud without having any deeper knowledge of zigbee internals...)

## What did you expect to happen
The device should change its state and respond correctly.

## How to reproduce it (minimal and precise)
Pair, wait, send Command.

## Debug Info
zigbee2mqtt version: v1.8.0-dev (commit #7d26873)
CC253X firmware version: CC2531_SOURCE_ROUTING_20190619

**Comment by soenkegissel** [comment]
Same for me. Unable to send any command for days.
