### ISSUE TITLE
About the Hassio add on management 

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/zigbee2mqtt#2765]
This is not the true issue, but since the repos https://github.com/danielwelch/hassio-zigbee2mqtt not active maintenance, and many user use it, many pull request but not one care and release slower than main project.
So I suggest @Koenkk give a proper solution like integrated it in the main project.

**Comment by Koenkk** [comment]
I see daniel recently commited (https://github.com/danielwelch/hassio-zigbee2mqtt/commits/master). Note that I also have access to this repo so I can already merge PRs.
