### ISSUE TITLE
OSRAM/SYLVANIA 73741 won't pair.

### ISSUE THREAD

**Issue by stampeder** [Koenkk/zigbee2mqtt#2770]
I've gone through all the facts on this. Try as I might they just won't pair. They fail interviews. I have two of them both of which I have reset to factory defaults many times.

## Debug Info
zigbee2mqtt version: 1.9
CC253X firmware version:cc2531_default_20190608

Log output:
info  2020-01-17 18:57:51: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-01-17.18-57-51'
info  2020-01-17 18:57:51: Starting zigbee2mqtt version 1.9.0 (commit #287f843)
info  2020-01-17 18:57:51: Starting zigbee-herdsman...
info  2020-01-17 18:57:54: zigbee-herdsman started
info  2020-01-17 18:57:54: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
info  2020-01-17 18:57:54: Currently 2 devices are joined:
info  2020-01-17 18:57:54: 0x00178801030c46f1 (0x00178801030c46f1): 9290011370 - Philips Hue white A60 bulb E27 (Router)
info  2020-01-17 18:57:54: 0x7cb03eaa00a8cdf9 (0x7cb03eaa00a8cdf9): Not supported (Router)
warn  2020-01-17 18:57:54: `permit_join` set to  `true` in configuration.yaml.
warn  2020-01-17 18:57:54: Allowing new devices to join.
warn  2020-01-17 18:57:54: Set `permit_join` to `false` once you joined all devices.
info  2020-01-17 18:57:54: Zigbee: allowing new devices to join.
info  2020-01-17 18:57:54: Connecting to MQTT server at mqtt://localhost
info  2020-01-17 18:57:54: Connected to MQTT server
info  2020-01-17 18:57:54: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2020-01-17 18:57:54: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.9.0","commit":"287f843","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
It seems to see my devices as routers and not end devices.
Thanks.
Glenn.

**Comment by Koenkk** [comment]
Can you provide the herdsman debug logging when pairing the device?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
