### ISSUE TITLE
error while setup with esp8266 and zigbee module

### ISSUE THREAD

**Issue by happylichuanxi** [Koenkk/zigbee2mqtt#2771]
hi,I have a problem while setup with esp8266 and zigbee module ::error while starting zigbee-shepherd!. Error: Error: No such file or directory, cannot open tcp://192.168.31.73:8880,I run it in iobroker,any help would be grateful.

**Comment by mr2c12** [comment]
Double check the esp8266/espeasy configuration. Is it working fine? Can you open a serial connection from another application?
