### ISSUE TITLE
Eurotronic SPIRIT SPZB0001 'Error: Data request failed with error: 'MAC transaction expired' (240)'

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#2775]
Hello, I connected the thermostat, but when I try to switch it there is always an error

https://pastebin.com/zeejwi9H

**Comment by sjorge** [comment]
There are a few other repots
koenkk/zigbee-herdsman-converters#715
koenkk/zigbee2mqtt#2500

**Comment by Koenkk** [comment]
Duplicate indeed, thanks @sjorge
