### ISSUE TITLE
Public Git(hub) repo history changed

### ISSUE THREAD

**Issue by AlexMekkering** [Koenkk/zigbee2mqtt#278]
I saw that some commits changed in this public repo (at least in the dev branch). This makes it very hard to keep forks synced and pull changes. I.e. The easiest way to keep my fork synced with this repo is to delete it and fork it again instead of just pulling/pushing commits.
A general rule of thumb is to not change commits which (may) exist outside your repository (please see https://git-scm.com/book/en/v2/Git-Branching-Rebasing#The-Perils-of-Rebasing). So please rebase the public branches as less as possible (ideally never).

**Comment by Koenkk** [comment]
Yes completely true! In this case I did it for the very exceptional case that I needed some commit in master immediately.
