### ISSUE TITLE
E180-ZG120B-TB support

### ISSUE THREAD

**Issue by szivgy** [Koenkk/zigbee2mqtt#2782]
Hi!

What code needs to be changed to support the E180-ZG120B-TB modules?

[Documentation](http://www.ebyte.com/en/pdf-down.aspx?id=1618)
[Buy](
https://www.aliexpress.com/item/4000531916570.html?spm=a2g0o.productlist.0.0.4ac63d48zwR2t3&algo_pvid=87e33758-f11b-4f94-8d69-261ed2ff1bf2&algo_expid=87e33758-f11b-4f94-8d69-261ed2ff1bf2-1&btsid=b5de8f90-879b-4d0b-b6d0-a45335b07be6&ws_ab_test=searchweb0_0,searchweb201602_6,searchweb201603_53)

I think it is same, but already in box.

[InBox](https://www.aliexpress.com/item/4000443313912.html?spm=a2g0o.productlist.0.0.2dd23b35qYtWjl&algo_pvid=64031655-e565-4078-a94e-dd7b83778224&algo_expid=64031655-e565-4078-a94e-dd7b83778224-5&btsid=5f2f7faf-eacc-4bc7-a76e-cb416bd8cbb8&ws_ab_test=searchweb0_0,searchweb201602_6,searchweb201603_53)

Best Regards,
Gyula

**Comment by kabturek** [comment]
One has to write a new adapter (probably for https://github.com/Koenkk/zigbee-herdsman as this is the future)

**Comment by Koenkk** [comment]
A new adapter has to be implemented indeed.
To add this the following interface needs to be implemented (https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts).

I will close this as it's not a zigbee2mqtt but a zigbee-herdsman issue.

**Comment by Hedda** [comment]
@szivgy & @kabturek FYI, I posted a request for zigbee-herdsman (zigbee2mqtt relies on) here:

https://github.com/Koenkk/zigbee-herdsman/issues/168

That request suggests adding support to all EFR32MG1 and not just E180-ZG120B based hardware.
