### ISSUE TITLE
 config issue "CC2530+CC2591" + "ESP8266 wemos d1 mini" coordinator

### ISSUE THREAD

**Issue by ohminy** [Koenkk/zigbee2mqtt#2794]
## Debug Info
zigbee2mqtt version: hassio addon lastest version now (2020-01-21)
CC253X firmware version: Z-Stack_Home_1.2 CC2530_CC2591_default_20190608.zip

first of all.. I'm very newby with zigbee2mqtt.

I have issue " CC2530+CC2591" + "ESP8266 wemos d1 mini" coordinator and zigbee2mqtt hassio add on.
I guess maybe it is tcp setting....
but I'm not sure.... ;;
there is so many difficult things for me..... some like.. TCP, network_key, socat.....

my setting... like this
I uploaded CCLib into esp8266(A) by ArduinoIDE (Done)
I flashed CC2530 + CC2591 (Done for about 1hour)
I installed espeasy into esp8266(B) (espeasy is works fine)
I connected CC2530 + CC2591 + esp8266(B)
https://www.zigbee2mqtt.io/information/connecting_cc2530.html
I install the add-on zigbee2mqtt in my hass.io on synology NAS
start

it was not started, so I installed zigbee2mqtt dev add on

but same,  does not works...

here is my config

{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://192.168.0.2:1883",
    "user": "********",
    "password": "********"
  },
  "serial": {
    "port": "tcp://192.168.0.41:1775"           # port: 'tcp://192.168.2.13:20108' is not working too.
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  }
}

I just edited serial port information from default config
  "serial": {
    "port": "tcp://192.168.0.41:1775"
}

my esp8266 IP is 192.168.0.41,

here is my log
Log
 ERR! zigbee2mqtt@1.9.0-dev start: `node index.js`
npm ERR! Exit status 1
npm 
ERR! 
npm 
ERR! Failed at the zigbee2mqtt@1.9.0-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2020-01-21T05_09_29_912Z-debug.log
2020-01-21T14:09:30: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-01-21T14:09:30: PM2 log: App [npm:0] starting in -fork mode-
2020-01-21T14:09:30: PM2 log: App [npm:0] online
> zigbee2mqtt@1.9.0-dev start /app
> node index.js
zigbee2mqtt:info  2020-01-21 14:09:32: Logging to console and directory: '/share/zigbee2mqtt/log/2020-01-21.14-09-32'
zigbee2mqtt:info  2020-01-21 14:09:33: Starting zigbee2mqtt version 1.9.0-dev (commit #cf1bb386ead98a78b6b3bfed01e8d151cc7e9c6c)
zigbee2mqtt:info  2020-01-21 14:09:33: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-01-21 14:09:36: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-01-21 14:09:36: Failed to start zigbee
zigbee2mqtt:error 2020-01-21 14:09:36: Exiting...
zigbee2mqtt:error 2020-01-21 14:09:36: Error: Error while opening socket
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:162:28)
    at Socket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm 
ERR! code ELIFECYCLE
npm ERR!
 errno 1
npm
 ERR! zigbee2mqtt@1.9.0-dev start: `node index.js`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.9.0-dev start script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-21T05_09_36_191Z-debug.log

so I uploaded again CCLib to esp8266(A)
and I flashed again CC2530 + CC2591

but same...

(I did not test yet direct connect CC2530 to synology NAS with CP2102
cause I haven't study yet about this way)

what should I do.... plz help...

**Comment by mr2c12** [comment]
You should check if the virtual uart is working.
Is espeasy working properly? How did you set it? What do you see in its logs?
If everything is ok on the espeasy side.. can you connect to the virtual uart with another serial client (e.g. "com" on linux)?
