### ISSUE TITLE
Docker Stop and Bridge Offline Message

### ISSUE THREAD

**Issue by Odianosen25** [Koenkk/zigbee2mqtt#280]
When the docker image is stopped using a command like `docker stop 746f7fc1f845` or when the system is shutdown, the brdige doesn't send an `offline` message. Is this normal and can this be added please?

If I am missing something, do kindly let me know.

Thanks

**Comment by tb-killa** [comment]
Normaly acutally on ``dev`` branch @Koenkk implemented [Last will message](https://github.com/Koenkk/zigbee2mqtt/issues/267).
Please check this.
Maybe this can answer your question?

**Comment by Odianosen25** [comment]
Hello @tb-killa,

Thanks for the response, but I don't understand where I am to edit or something.

I will just wait until there is an upgrade and it is moved from dev.

Regards

**Comment by tb-killa** [comment]
if I am not mistaken there are also docker images from the dev branch.
maybe just set up a new instance for the test, copy the content from the ``data`` directory over and stop the original container.
Afterwards everything should continue as in the original.
