### ISSUE TITLE
configuration.yaml  how to add two channels 25 26 together

### ISSUE THREAD

**Issue by AleksVM** [Koenkk/zigbee2mqtt#2808]
I have several switches on channel 26, I wanted to add channel 25 for devices konke sitting on the channel 10 15 25.
I did not understand how to register two channels. inserted such a configuration

"advanced": {
    "pan_id": 6754,
    "channel": 26,
    "channel": 25, 
    "network_key": [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13
    ],
    "availability_blacklist": []
  },
 
writes the wrong configuration on reboot and removes channel 25 , there is no description in the documentation about the use of several channels in the configuration ?

**Comment by Koenkk** [comment]
The coordinator can only function on 1 channel at a time so this is not possible.
