### ISSUE TITLE
Converting Output

### ISSUE THREAD

**Issue by 19Homer73** [Koenkk/zigbee2mqtt#281]
Good morning,

maybe you can help me with this:

The output in iobroker looks like this:
temperature":23.34,"humidity":39.74,"battery":"35.00","voltage":2975

But I would like to have this:
Temperature: 23.34 °C
Humidity: 39.74 %
Battery:   ##35.00
Voltage: 2.975 V

What do I have to change for that?
Many thanks in advance!

**Comment by tb-killa** [comment]
We leave the zigbe2mqtt output generally, your smart home system on the end should parse your variables as needing.
what you actually could do, if you use something like node-red .. you could build function for converting and adding own text to string..
i think this is in line with @Koenkk  .. or are you of another opinion?

**Comment by 19Homer73** [comment]
This is what I was afraid of.
I can't any solution for this on the internet :-(.

**Comment by tb-killa** [comment]
Tell us what system you're using or what you have in mind in general?
Maybe then we'll find a simple 3party application?

**Comment by Koenkk** [comment]
This conversion should indeed be part of your home automation system.

**Comment by tb-killa** [comment]
@19Homer73
I hope your question was answered (unfortunately not quite satisfactory).?

Is there something else on your mind?

Can we close this?

**Comment by tb-killa** [comment]
@19Homer73
I hope your question was answered (unfortunately not quite satisfactory).?

Is there something else on your mind?

Can we close this?
