### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by Frianik** [Koenkk/zigbee2mqtt#2810]
I tested all versions and only version where i can bind DIYRuZ_rspm is vanilla installed z2m trough' git clone -b dev' which is not available in hassio. There is no way to pair these devises to z2m in hassio. Please make a quick fix release with fresh converters.

**Comment by Koenkk** [comment]
There havent been any changes for this device since 1.9.0, to use dev on hassio use the edge version.
