### ISSUE TITLE
Show state of device

### ISSUE THREAD

**Issue by guitar9** [Koenkk/zigbee2mqtt#2815]
I am using zigbeeversion 1.9.0 and a CC1352P-2 with docker.
I paired my philips hue lamp successfully. 
After pairing there are no logging which payload I can send. 

I remember from past where I used CC2531 there was output about the device which payload I can use. (for example brightness, state, color, ....)

Is there a option to show the state of the device?

**Comment by nanobra1n** [comment]
I haven't used zigbee2mqtt long enough to be an arbiter of past behavior, but you can look up the supported capabilities of your devices here {follow the link of your device}:

https://www.zigbee2mqtt.io/information/supported_devices.html
