### ISSUE TITLE
Clarification: firmware change can leave all devices out?

### ISSUE THREAD

**Issue by subzero79** [Koenkk/zigbee2mqtt#282]
Just yesterday i attempted to flash the sniffer firmware into the dongle to some traffic capture, I don't if the firmware wasn't the correct one or i was just using the wrong software so it didn't work properly. Anyway after I gave up, i flashed the coordinator firmware, latest by pulling the repo so it wasn't the same original i was using with before i flashed the sniffer one.

Once i started zigbee2mqtt again, all devices where not recognised any more. I had to repair them again one by one. Tomorrow i have to do the plugs in the attic.

Is this expected behaviour? Whats the issue here? transport keys? should it be warned in the wiki maybe?

For know i learn, and I've already ordered another dongle for this kind of testing.

**Comment by cmille34** [comment]
I learned this the hard way as well. I reflashed my CC2531 to fix an "unknown 17" error. I was told if you reflash the usb dongle, you'll have to repair the devices.

**Comment by Koenkk** [comment]
Reflashing = clearing memory of CC2531 -> repair all devices.

**Comment by subzero79** [comment]
Thanks for the info. Is it possible to backup the current loaded memory with the cc-debugger? 
Also what does it get lost by flashing? The transport keys ?

**Comment by tb-killa** [comment]
@Koenkk  @ptvoinfo
I don´t know if this could help but this seems to be a good way:
https://sunmaysky.blogspot.com/2016/01/how-to-clone-existing-z-stack.html?m=1

Another Way (maybe..??)

Maybe we have to prebuild our firmware with options 
``NV_INIT
NV_RESTORE
`` 
to get them also working ?
But attention: http://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/685544?CC2531-NV-RESTORE-and-Flash-Life

**Comment by Koenkk** [comment]
@tb-killa that looks good! We could use cc-znp library to read and write.

**Comment by matchett808** [comment]
Is that now on the new firmware?

**Comment by tb-killa** [comment]
Actually no work. We are all busy, if i got some free time next week i could take a Look at this.

**Comment by lolorc** [comment]
the same way, I've replaced my cc2531 by a cc2530+cc2590 without repairing all devices. Just need to unplugged routers and shield the coordinator so that it doesn't detect the chan/panid is already used.
