### ISSUE TITLE
Device pairing even when permit_join: false

### ISSUE THREAD

**Issue by luckypants123** [Koenkk/zigbee2mqtt#2828]
Z2M dev branch on Buster Lite.

I have a strange situation where devices will pair regardless of the permit_join: true setting.

Log: https://pastebin.com/a2PhpmkN
Config: https://pastebin.com/KbcvEe4c

Snippets:
Starts up...then
```
info  2020-01-26 17:04:50: Zigbee: disabling joining new devices.
```
then
```
info  2020-01-26 17:05:14: Device '0x002446fffd01e4f3' joined
```
Device continues to pair.

Could I have something set incorrectly?

**Comment by Koenkk** [comment]
Was the device previously paired to z2m?

**Comment by luckypants123** [comment]
Ah - you are correct. 
I forgot that the devices still retain the pairing. 
Apologies - my mistake.
