### ISSUE TITLE
Current state of devices

### ISSUE THREAD

**Issue by magpern** [Koenkk/zigbee2mqtt#2829]
# Did you read the FAQ?
Well, kind of. There is alot. If I missed, my bad

# A question?
Yes. Is there a way to force zigbee2mqtt to send state of all currently known devices?
I use some Tasmota devices, and whenever Home Assistant is rebooted (or on command) a MQTT message is send which triggers all devices to resend discovery message, along with the state and GUI updates.

# Bug Report
If Home assistant is rebooted, devices are shown as turned off or if lights are turned off outside of home assistant, gui is not updated.

## What did you expect to happen
When a controller like Home Assistant starts up the GUI should reflect state of each device.
If device if physically turned off, show "Unavailable"

## How to reproduce it (minimal and precise)
Run Hassio (or Home assistant) in Docker
Run Zigbee2mqtt in docker.
Have some lights turned on true the controller GUI.
Restart Hassio docker (HA docker)
All deviced are reported as "Off"

If you restart zigbee2mqtt, devices update the status.
However, if device is physically turned off, it is still shown as On or Off whatever was last known.

**Comment by Koenkk** [comment]
> When a controller like Home Assistant starts up the GUI should reflect state of each device.

Zigbee2mqtt will resend all states to home assistant if you have the following in the home assistant `configuration.yaml`    https://www.zigbee2mqtt.io/integration/home_assistant.html#mqtt-discovery

> If device if physically turned off, show "Unavailable"

https://www.zigbee2mqtt.io/information/availability.html
