### ISSUE TITLE
Support RPI hat similar to Raspbee Module

### ISSUE THREAD

**Issue by ghost** [Koenkk/zigbee2mqtt#284]
I want the capability of zigbee2mqtt without the need for an external dongle attached to my Raspberry Pi.

How can I accomplish this?

Would the following device solve my problem https://www.dresden-elektronik.de/raspbee/  ?

Any other suggestions would be appreciated.

Thanks..

**Comment by tb-killa** [comment]
Actually only ti modules are compatible.

You could build your own via cc2530 with serial Header and use rpi onboard serial.
Build your own simple pcb and you got the same Module size ;)

**Comment by L00000813** [comment]
Thanks for the reply. Maybe you could provide more clarity on how exactly I can do this. Provide links to products etc..

**Comment by tb-killa** [comment]
If i got time (next two weeks im really busy) i tell more because working on this too.

**Comment by L00000813** [comment]
Ok, no worries.

I will wait to see how you implement this. If it is a success I will try after.

Thanks.

**Comment by k1ngf15h3r** [comment]
I am also intressted to get support for the raspbee module. I already have the module installed on my Raspberry so it would be nice to keep it running like it is. But I Need to upgrade my system with zigbee2mqtt so really looking forward to get it combined

**Comment by mailuminatti** [comment]
Hey @tb-killa by any chance was this moved forward? Quite interested in see this happening.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> If i got time (next two weeks im really busy) i tell more because working on this too.

*BUMP*
A raspbee support would be really nice.

**Comment by nukleuz80** [comment]
I‘m interested too in RaspBee ...

**Comment by sehraf** [comment]
https://koenkk.github.io/zigbee2mqtt/information/FAQ.html
RaspBee won't happen.

**Comment by Koenkk** [comment]
RaspBee indeed won't happen.
