### ISSUE TITLE
Niloé / Nereya switches x zigbee2mqtt

### ISSUE THREAD

**Issue by wagiotto** [Koenkk/zigbee2mqtt#2841]
Hello everyone.

I have legrand niloé / nereya switches and I can't connect them with the home assistant as they only communicate with each other.
With this zigbee2mqtt solution is it possible for me to be able to connect them with the raspberry pi for control via cell phone?
I leave here a link to the switches.

Please help me!

http://www.decorwatts.com.br/interruptor-zigbee.php

https://www.amazon.co.uk/Legrand-Niloé-Shutter-Switch-Zigbee®/dp/B00BD0EOSA

**Comment by sjorge** [comment]
The legrand stuff might already work: https://github.com/Koenkk/zigbee2mqtt/issues/2399

**Comment by wagiotto** [comment]
But my switches are of different models than these. They have no integration with the cell phone.
