### ISSUE TITLE
Xiaomi device (WXKG01LM) binding support

### ISSUE THREAD

**Issue by DhaenensT** [Koenkk/zigbee2mqtt#2842]
Thank you Koenk for this great project.

Im am trying to bind the WXKG01LM Xiaomi switch to an ikea light bulb by using the following guide: https://www.zigbee2mqtt.io/information/binding.html
Nothing is happening in de log output and I am unable to control de ikea light bulb. 
I was able to bind the Ikea switch (E1743) to the light bulb (LED1733G7)
Does the Xiaomi switch have an GenOnOff cluster to bind to the ikea bulb? 

Thanks!

**Comment by Koenkk** [comment]
The WXKG01LM cannot be bound (not supported by the device).

**Comment by rs-11** [comment]
Hi Koenkk, I recommend you write that on the product page at [link].(https://www.zigbee2mqtt.io/devices/WXKG01LM.html )
Thanks!

**Comment by Koenkk** [comment]
Done, thanks

**Comment by Se7enair** [comment]
How is ist possible that deconz is able to bind this device to a group?
I recently switched from deconz to z2m and was wondering  why binding is not possible.

Is deconz using a „fictional“ binding?
