### ISSUE TITLE
Dimmer IKEA battery status

### ISSUE THREAD

**Issue by antti365** [Koenkk/zigbee2mqtt#2849]
## Debug Info
zigbee2mqtt version: 1.9.0-dev
CC253X firmware version: 20190608
 
Hi,
I installed the latest version of the software and the latest stick firmware, connected dimmer ikea and found out that there is no battery value in the transmitted values ​​from the dimmer.  It seems that everything worked on older versions and the value was transferred - has something changed?  From the Xiaomi temperature sensor, the battery value comes without a problem ...

**Comment by mr2c12** [comment]
I am facing the same problem with an Ikea Remote (e1524). The battery percentage disappeared at some point.
Even when I had to restart from zero (changed coordinator fw, repaired every device) this has not been solved.

I am pretty sure it used to work.

**Comment by antti365** [comment]
I’ll check the switch E1743 in the evening, I’d like to check the motion sensor, I don’t have them unfortunately ...

**Comment by mr2c12** [comment]
![image](https://user-images.githubusercontent.com/2518332/73370115-fc700380-42b3-11ea-9592-dbc36eadae40.png)

E1743 and motion sensor are currently reporting the battery percentage in my network.

**Comment by antti365** [comment]
All the same, the dimmer came to his senses and sent me the battery value, before that it was necessary to wait for almost a day, apparently nothing has changed since then ... :)

**Comment by Koenkk** [comment]
@antti365 it indeed will take up to 1 day for the device to report it's battery level so this is expected.
