### ISSUE TITLE
Failed to interview: 7146060PU

### ISSUE THREAD

**Issue by TomMettam** [Koenkk/zigbee2mqtt#2851]
# Bug Report
## What happened
Attempting to pair a Philips Hue Go (7146060PU) fails with "Interview failed".

This device (at least the PU variant) is not in the supported devices list, however it should still pass the interview stage since zigbee2mqtt can pair with all zigbee devices.

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4129695/log.txt).

## Debug Info
zigbee2mqtt version:  287f843bbbc5265f
CC253X firmware version:  CC2531_DEFAULT_20190608

**Comment by Koenkk** [comment]
The latest zigbee2mqtt dev branch contains a fix related to Hue pairing, please try with that.

If it doesn't fix please provide the logging again.

**Comment by TomMettam** [comment]
The dev branch had the same issue. However, after the 12th(!!!!) attempt, it finally paired.

I guess there's some protocol unreliability here somewhere.
