### ISSUE TITLE
Interfaz web Administration

### ISSUE THREAD

**Issue by jondiez** [Koenkk/zigbee2mqtt#2854]
I would like to propose the implementation of a web interface for proper administration and monitoring of zigbee devices.  Something that greatly helps the end user for the correct configuration and implementation of the zigbee2mqtt system.
 Thank you!!

**Comment by Koenkk** [comment]
Its already there: https://github.com/yllibed/Zigbee2MqttAssistant

**Comment by jondiez** [comment]
Pero es compatible con Raspbian? En raspberry sin docker? No veo forma de instalarlo.

**Comment by jondiez** [comment]
But is it compatible with Raspbian? In raspberry without docker? I see no way to install it.

> Its already there: https://github.com/yllibed/Zigbee2MqttAssistant

**Comment by Koenkk** [comment]
For further support please open an issue here https://github.com/yllibed/Zigbee2MqttAssistant/issues
