### ISSUE TITLE
Inconsistency between aqara switches

### ISSUE THREAD

**Issue by condemil** [Koenkk/zigbee2mqtt#2857]
I have single-button and and two-button aqara switches and I see the inconsistency how single-button switch returns long click:

```
{"battery":100,"voltage":3085,"linkquality":21,"action":"hold"}
```

When for single click and double click it returns json with "click", not "action":

```
{"battery":100,"voltage":3085,"linkquality":31,"click":"single"}
{"battery":100,"voltage":3085,"linkquality":63,"click":"double"}
```

What I suggest is to add `click: "long"` to the json the same way as it works for to-button aqara switches. This way it simplifies automation logic as I need to look only at `click` for my automations.

**Comment by Koenkk** [comment]
Yes this should definitely be changed but can unfortunately not be done very easily as it will result in a breaking change.

Its on the list of changes to be done in zigbee2mqtt 2.0.0.

Closing this for now.
