### ISSUE TITLE
CC2530 router won't connect

### ISSUE THREAD

**Issue by Symphy24** [Koenkk/zigbee2mqtt#2859]
# Bug Report
https://pastebin.com/Rd5HnxU9
The router that is not connecting properly is "Router_inside"

## What happened
My CC2530 router will not connect to the coordinator when powered on vcc and gnd.
If I connect it to the cc debugger then it works. I started with connecting gnd and vcc to pin 1 and 2, then after waiting a few minutes without it connecting I tried adding the second vcc to pin 9, but it still would not connect. Then I connected RST to pin 7, then it connected to the coordinator within 1 minute.
(I unplugged the usb between connecting the wires)

## What did you expect to happen
I expected it to connect when powered just on vcc and gnd.
I have a second cc2530 that is much further away, and it connects perfectly every time.
I've tried re-flashing the router in question many times.

## How to reproduce it (minimal and precise)
I have no idea, seems like my CC2530 board might be failing, as I have a second one that works perfectly with the same setup.

## Debug Info
zigbee2mqtt version: 1.9.0
CC253X firmware version: CC2530_router_2019_02

**Comment by fabricioivanguedes** [comment]
I have the same problem, I have already downgraded the version and without success, I always get the same error version Sonoff Dongle Plus
