### ISSUE TITLE
Legrand 064888 not pairing

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#2860]
I am trying to synchronize the Legrand 064888 device. 
When the light is switched on, it turns red when the button is pressed for a few seconds, the light flashes, but no data is produced in zigbee2mqtt.
neither touchlink produces any effect.
Have you tried it and does it work?

## Debug Info
zigbee2mqtt version:1.9.0
CC253X firmware version:20190608

**Comment by Koenkk** [comment]
Please discuss Legrand stuff here: #2399
