### ISSUE TITLE
State of devices incorrect

### ISSUE THREAD

**Issue by michaeladam3010** [Koenkk/zigbee2mqtt#2864]
Hello,
I own one of the Müller Licht 404021 smart switches.
First, I used the switch with the IKEA Tradfri gateway and realized, that the IKEA app was always showing the correct state of the switch meaning, that it was showing that the light was switched on (or off), even when I switched it on (or off) at the switch.
zigbee2mqtt seem to not provide the actual state of the switch.

Environment:
zigbee2mqtt  1.9.0
hass.io

**Comment by Koenkk** [comment]
Try enabling the report feature: https://www.zigbee2mqtt.io/information/report.html

**Comment by michaeladam3010** [comment]
Enabling the report feature fixed the problem.
Thank you very much for your help and the really short response time :)
