### ISSUE TITLE
Pairing IKEA E1525/E1745

### ISSUE THREAD

**Issue by Eistee82** [Koenkk/zigbee2mqtt#2865]
I'm trying to pair an IKEA E1525/E1745

Tryed master and dev branch with latest firmware (CC2531_20190425.zip) on CC2531 USB stick.

I always got this:

`zigbee2mqtt:info  2020-01-31 19:23:45: Device 'szMotion' joined
zigbee2mqtt:info  2020-01-31 19:23:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"szMotion"}}'
zigbee2mqtt:info  2020-01-31 19:23:45: Starting interview of 'szMotion'
zigbee2mqtt:info  2020-01-31 19:23:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"szMotion"}}'
(node:26659) UnhandledPromiseRejectionWarning: Error: Timeout - 51041 - 1 - 2 - 0 - 1 after 10000ms
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:26659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
zigbee2mqtt:error 2020-01-31 19:24:11: Failed to interview 'szMotion', device has not successfully been paired
zigbee2mqtt:info  2020-01-31 19:24:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendly_name":"szMotion"}}'
zigbee2mqtt:warn  2020-01-31 19:24:18: Received message from unsupported device with Zigbee model 'undefined'
zigbee2mqtt:warn  2020-01-31 19:24:18: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:info  2020-01-31 19:24:19: Configuring 'szMotion'
zigbee2mqtt:info  2020-01-31 19:24:26: Successfully configured 'szMotion'
`

**Comment by Koenkk** [comment]
Please provide herdsman debug log when pairing this device on the latest **dev** branch.

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
