### ISSUE TITLE
Add support for Philips Hue Flourish white and color ambiance pendant light (4090631P7)

### ISSUE THREAD

**Issue by thomasja27** [Koenkk/zigbee2mqtt#2870]
Added manually, tested and working fine after adding it to devices. 
```
   {
        zigbeeModel: ['LCP003'],
        model: '4090631P7',
        vendor: 'Philips',
        description: 'Hue Flourish white and color ambiance pendant light',
        extend: hue.light_onoff_brightness_colortemp_colorxy,
    },
```
zigbee2mqtt:info  2020-02-01 10:58:11: Starting interview of '0x00178801062b9cf4'
zigbee2mqtt:info  2020-02-01 10:58:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x00178801062b9cf4"}}'
zigbee2mqtt:info  2020-02-01 10:58:31: Successfully interviewed '0x00178801062b9cf4', device has successfully been paired
zigbee2mqtt:info  2020-02-01 10:58:31: Device '0x00178801062b9cf4' is supported, identified as: Philips Hue Flourish white and color ambiance pendant light (4090631P7)
zigbee2mqtt:info  2020-02-01 10:58:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00178801062b9cf4","model":"4090631P7","vendor":"Philips","description":"Hue Flourish white and color ambiance pendant light","supported":true}}'

**Comment by Koenkk** [comment]
Added, will be supported in latest dev branch in a few hours. thanks!
