### ISSUE TITLE
Zigbee2mqtt over ESP8266 with serial port cc2530

### ISSUE THREAD

**Issue by roesl** [Koenkk/zigbee2mqtt#2874]
I want to connect a cc2530 over a software transparent serial port with ESP8266 ( e.g. ESPLink ) to build a independent Zigbee hub for use with my Synology NAS.
There is no VSP for Synology so I have to add a network connection to config file.
Is this possible with zwigbee2mqtt ?

# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by roesl** [comment]
no Idea ??

**Comment by Koenkk** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

**Comment by roesl** [comment]
thank you for the link.

**Comment by markuspeter** [comment]
Hi @roesl,
were you able to make this work ? Was there any additional configuration on the Synology NAS needed besides defining the port in the z2m configuration ?

**Comment by roesl** [comment]
I will order the cc2530 device this week in china, so I think it will arrive the next 6 week.
Then I will try to install

**Comment by roesl** [comment]
Hi,

 

Thank you for the link, but it doesnt work on my Synology NAS with zigbee2mqtt installed as docker container.

Is there a solution ?

 

Regards

Georg

 

Von: Koen Kanters [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. April 2020 13:06
An: Koenkk/zigbee2mqtt
Cc: roesl; Author
Betreff: Re: [Koenkk/zigbee2mqtt] Zigbee2mqtt over ESP8266 with serial port cc2530 (#2874)

 

https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

**Comment by roesl** [comment]
I got the devices today, but it doesnt work on my Synology with zigbee2mqtt installed in the docker container

**Comment by roesl** [comment]
I got it work on a virtual machine with Ubuntu 18 where I also installed IP-Symcon.
But now I have problems with the switches from IKEA - the can be connected to the coordinator but they dont work.
All other devices I use are working ( Aquara sensors, Aldi LEDs )
Maybe its a problem of the coordinator firmware for the SOC with 2530+2592

**Comment by roesl** [comment]
Now I installed the firmware from 
Z-Stack-firmware/coordinator/Z-Stack_Home_1.2/bin/default/
and it works fine.
Maybe someone get it work for a Synology Docker container - this would be easier to install.
Thanks to Koenkk for the great work !
