### ISSUE TITLE
After replaced CC2531 with version with antenna a lot of sensors do not works

### ISSUE THREAD

**Issue by vpomax** [Koenkk/zigbee2mqtt#2875]
I have a lot of problems with zigbee2mqtt.
I’m using 40 xiaomi devices (mainly human body, door/windows and temperature/humidity Xiaomi Aqara sensors).
Since some weeks ago I had a network of one CC2531 coordinator and two CC2531 routers… and all worked fine.

Then I bought three CC2531 with the antenna, I flashed one with last coordinator and other two with router last firmware and upgraded zigbee2mqtt to last version 1.9.0 on my Hassio v. 0.104.2. Then I replaced the old CC2531 without antenna with the new.
I shoutdown Hassio and restart again.
A lot of the zigbee devices are recognized by zigbee2mqtt (i see them in the log) but do not works.
Sometime after I try to make pairing again they works, but are not stable. Not all devices I’m able to pair again.
If I use Zigbee2mqtt Assistant I see that only few devices are linked to the routers.
What do you suggest to me?
I must delete share/zigbee2mqtt/database.db and restart from zero?
Please help me!!!

**Comment by derekoharrow** [comment]
I had similar when I tried to swap a CC2531 to one with an antenna - it just wouldn't see the devices in the network. 
Sorry to say, but I gave up getting it to work - I made sure I had backups of the data files, etc. but nothing worked. In the end I re-paired everything from scratch.
If you get it working, I'd love to know how as it would make future upgrades less worrying.
