### ISSUE TITLE
Feature Request: Transition saves previous brightness values on switch off to recover to these later

### ISSUE THREAD

**Issue by dreimer1986** [Koenkk/zigbee2mqtt#2883]
# Feature Request
## What happened

Light transition works for on/off again now (worked for a short period in the past already btw) but switching back on causes the lights to be at minimal brightness.

## What did you expect to happen

Maybe restoring the previous brightness value would be a nice addition.

## How to reproduce it (minimal and precise)

Just switch off a light with a transition enabled (2 sec in my case) and then back on.

## Debug Info
zigbee2mqtt version: a07a28cb65d30ca78e4554e301b5595b895f8e3f
CC253X firmware version: CC1352P_2_20191106

**Comment by Koenkk** [comment]
Is this the same bug as: https://github.com/Koenkk/zigbee2mqtt/issues/2850#issuecomment-580365633 ? Let's continue the discussion in #2850
