### ISSUE TITLE
Would I gain anything from installing newer firmware on my CC2513?

### ISSUE THREAD

**Issue by lancelon** [Koenkk/zigbee2mqtt#2885]
When I first installed Zigbee2Mqtt, I was using CC2531ZNP-Prod_20190109.zip and I see CC2531_DEFAULT_20190608 is now the recommended install file. Would I gain anything by replacing the January 2019 file with the June 2019 file? I **am** having [problems](https://github.com/Koenkk/zigbee2mqtt/issues/2353) pairing [new ](https://github.com/danielwelch/hassio-zigbee2mqtt/issues/288)devices. My working theory is that the stick won't "let go" of previously paired devices even though they have been deleted in theory. Thanks

**Comment by Koenkk** [comment]
If you don't have problems -> don't update
If you have problems -> update
