### ISSUE TITLE
 pairing problem,  after a while running

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#2887]
# Bug Report

After a while, zigbee2mqtt stops allowing new devices to be added.
Sometimes it gives me an interview_failed for all the sensors and other times they don't even try to synchronize me.
All devices that were linked work correctly for both reading and writing but there is no way to add new devices.

It is not a problem of equipment limit (5 or 6 connected devices), because I have had more at the same time and change permit join between true and false does not solve the problem.

The debug shows no errors of any kind just the interview_failed.

The only way to make it work again is to reset the zigbee2mqtt service and everything works again and I can add new devices

## What did you expect to happen

That would allow you to add new devices always

## How to reproduce it (minimal and precise)
I don't know how it happens, sometimes it happens to me before other times later.
## Debug Info
zigbee2mqtt version: 1.9
CC253X firmware version: "revision":20190608

**Comment by Koenkk** [comment]
Perhaps some old devices are still hanging in the coordinator, can you try reflashing the coordinator? (does not require repairing of currently paired devices)
