### ISSUE TITLE
Device with modelID 'SPZB0001' supported or not

### ISSUE THREAD

**Issue by Mr-Eternity** [Koenkk/zigbee2mqtt#2898]
According to the overview, the product SPZB001 should be compatible. However, after installation, it becomes clear that the MQTT statements cannot be processed. Does anyone have a solution? (Zigbee2mqtt is up to date)

Feb 05 23:17:37 srvglt npm[8899]:   zigbee2mqtt:warn 2020-2-5 23:17:37 Device with modelID 'SPZB0001' is not supported.
Feb 05 23:17:37 srvglt npm[8899]:   zigbee2mqtt:warn 2020-2-5 23:17:37 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
Feb 05 23:17:37 srvglt npm[8899]:   zigbee2mqtt:warn 2020-2-5 23:17:37 Cannot handle MQTT message on 'zigbee2mqtt/0x00158d0001ffc9ee/set' with data '{"current_heating_setpoint": 4.5}'

**Comment by Koenkk** [comment]
This device is indeed supported (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L5329)

Make sure you are on the latest zigbee2mqtt and did not manually edit your `devices.js`.
