### ISSUE TITLE
Not really an issue more a...boast? Or a query?

### ISSUE THREAD

**Issue by lancelon** [Koenkk/zigbee2mqtt#2900]
Is it just me or does anyone else get absolutely stellar coverage indoors with a single CC2531? It's on a USB extension lead, yes, hanging in the air not near any metal objects, but it's absolutely fantastic. It's in the basement yet it reaches to the fourth floor and covers the entire house [which looks a bit like this](https://c8.alamy.com/comp/B6DCC9/town-houses-townhouse-townhouses-house-terrace-york-north-yorkshire-B6DCC9.jpg). I'm just impressed is all and it appears this is highly unusual for the CC2531?!

**Comment by dstockhammer** [comment]
Any zigbee device that's connected to the power circuit (i.e. not battery operated) acts as repeater. So if you got things like light bulbs or plugs in your zigbee network the range will usually be boosted significantly.

I'm not using it myself, but I believe this plugin displays the network map with repeaters: https://github.com/rgruebel/ha_zigbee2mqtt_networkmap
