### ISSUE TITLE
Xiaomi Aqara Motion Sensor RTCGQ11LM - motion timeout 5s?

### ISSUE THREAD

**Issue by OliverWieland** [Koenkk/zigbee2mqtt#2903]
Regarding this:
https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html

> after detecting a motion the sensor ignores any movements for exactly 60 seconds

I would expect, that the Sensor doesn't detect any motion within 60 seconds after the last motion.
But I get all 5 seconds _two_ messages with "occupancy: true" when I move in front of the sensor.

Did I understand something wrong?

**Comment by Koenkk** [comment]
It will only do this in the first few minutes after paired.

**Comment by OliverWieland** [comment]
Thanks, I will watch this. Pairing was 4 hours ago and the messages still occurs every 5 seconds when moving.
