### ISSUE TITLE
Connect CC2530 to Raspberry Pi GPIO

### ISSUE THREAD

**Issue by der-eine** [Koenkk/zigbee2mqtt#291]
Hello everybody, 
today flashed the CC2530 and would like to connect it via the GPIO pins of the Raspberry Pi's.
Have him to the GPIO pins
1 -> VCC
8 -> P02
9 -> Ground
10 -> P03

connected. Is it correct that way?
How do I get the COM Port Name for the Zigbee Adapter in ioBroker?

Thanks in advance

**Comment by tb-killa** [comment]
Hi what type of Module you use?
You have to follow raspberry pi guide to activate onboard serial. 
What type of rpi you use?
Please check for right Voltage (3.3v tolerant pin on rpi and 5v (maybe) on Module side!
As i know there is something like Web console availabel, so rpi guide show you the right way ;)

**Comment by der-eine** [comment]
Hello tb-killa,
I use the CC2530 with either PCB antenna OR external antenna, and no RF frontend. I'll take a look at the guide, I'm still a beginner regarding the Raspberry Pi. I use a Raspberry Pi 3b +. Input voltage 2.1V - 3.6V so 3.3V on Raspberry.
thanks for the information :)

**Comment by tb-killa** [comment]
Rpi3 got some special because they has more then one uart (second one for wifi) so you have to change some stuff on configuration file(s).

**Comment by mark078** [comment]
@der-eine you can use this howto: http://heinz-otto.blogspot.com/2016/07/raspberry-pi-homematic-modul.html

You must also short-circuit P20 with GND on the CC2530 board.

**Comment by dzungpv** [comment]
I also try to connect both to PI UART and USB-TTL USB (CP2102) but it not work. This is the module i use https://www.aliexpress.com/store/product/Network-of-things-things-ZigBee-wireless-module-CC2530-development-kit-learning-board-intelligent-hardware-control/2980023_32806496292.html

**Comment by dronkeol** [comment]
Hi, 

i'm waiting for my cc2530 boards yet.  In the meantime, I have been gathering information for connect the board with my pi 3(b+).

From pi4j pinout info:

"On the Raspberry Pi Model 3B+ the hardware-based serial/UART device /dev/ttyAMA0 has been re-purposed to communicate with the the built-in Bluetooth modem and is no longer mapped to the serial RX/TX pins on the GPIO header. Instead, a new serial port "/dev/ttyS0" has been provided which is implemented with a software-based UART (miniUART). This software-based UART ("/dev/ttyS0") does not support PARITY and some have experienced some stability issues using this port at higher speeds. If you don't need Bluetooth functionality, you can disable the BT modem and configure the RPi to use a device-tree overlay to re-map the hardware-based serial UART ("/dev/ttyAMA0") back to the GPIO header pins for TX/RX."

you will need re-map the UART for pins 15-16 and disable bluetooth modem (https://openenergymonitor.org/forum-archive/node/12311.html), then connect the right pins to pi.

P0_2 < => RX (16)
P0_3 < => TX (15)
GND < => GND

I don't have the cc2530's boards yet for test this info.

**Comment by GoSpursGoNL** [comment]
I guess that info is outdated, since UART on the PI is on other GPIO pins.
Better read? https://www.raspberrypi.org/documentation/configuration/uart.md

My understanding:
P0_2 is for receiving data, so should be connected to TXD (transmitting) on the Pi.
P0_3 is for transmitting data, so should be connected to RXD (receiving) on the Pi.
Pinout: https://pinout.xyz/pinout/pin8_gpio14#

**Comment by ChumKiu** [comment]
Hi, I kindly ask you about some update on this subject, I'm also try to performa a my simple domotic application basing on a RPi and this TI module. Do you have any chance? Thank. Regards.

**Comment by ChumKiu** [comment]
Did someone have update on this subject (connecting CC2530 to a RPi)?
Regards

**Comment by GoSpursGoNL** [comment]
I got it working in the past but found out the range was still less than the Xiaomi Gateway, so I went with that. If I would use Zigbee2MQTT again in the future, I'd go with the easier usb stick 2531
