### ISSUE TITLE
OSRAM E14 bulb AC08562 does NOT support color temperature adjustments

### ISSUE THREAD

**Issue by CodeFinder2** [Koenkk/zigbee2mqtt#2916]
Hi,

in contrast to what is said in #2682, the OSRAM SMART+ Candle E14 Dimmable White (AC08562) **does not support changing the color temperature**. I don't know why @DeliriousMetro suggested this change. It is also printed on the bulb itself that it justs supports dimming at a fixed color temperature (2700K):
<img src="https://user-images.githubusercontent.com/20599588/74084980-a732af80-4a74-11ea-96a1-20443b268dac.jpg" alt="alt text" width="100"> (click on the image to enlarge it)

 If I change the color temperature for a bulb, nothing changes as you can (hopefully) see in the following pictures:
<img src="https://user-images.githubusercontent.com/20599588/74085069-ab130180-4a75-11ea-946c-18801666de3a.jpg" alt="alt text" width="100"> => <img src="https://user-images.githubusercontent.com/20599588/74085075-b49c6980-4a75-11ea-8355-22815cbc8010.jpg" alt="alt text" width="100">
<img src="https://user-images.githubusercontent.com/20599588/74085080-b9f9b400-4a75-11ea-81ae-8615ca6123ed.jpg" alt="alt text" width="100"> => <img src="https://user-images.githubusercontent.com/20599588/74085082-bebe6800-4a75-11ea-8745-7ebb56753f21.jpg" alt="alt text" width="100">

I am suggesting to revert commit https://github.com/Koenkk/zigbee-herdsman-converters/commit/dfbf703cde19588c6d2c5fac9c6ed8c84b104cf8 and update [the docs](https://www.zigbee2mqtt.io/devices/AC08562.html) accordingly (I guess, [this file](https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/AC08562.md) needs to be changed, right?). I've two such bulbs and tested with both.

Thanks!

**Comment by Koenkk** [comment]
Fixed, thanks, docs will be updated automatically at next zigbee2mqtt release.
