### ISSUE TITLE
Help needed: Tuya Wall Scene Switch

### ISSUE THREAD

**Issue by DaCHRIS** [Koenkk/zigbee2mqtt#2926]
Hi all, 

Please can someone help me with adding a new device? 

I bought some of the 2-button "Tuya Smart Remote Scene Switches (Zigbee EU Version)" at aliexpress:  https://bit.ly/2ScvZzb 

The Switch can be paired, but is not added until now as it seems. 

Ability on each button:
Single Click
Double Click
Long Press 

![tuya](https://user-images.githubusercontent.com/8064903/74127770-dd3e7380-4bdb-11ea-81e1-7bfcfd4ebdfe.png)

Details:
model: TS0042
type: EndDevice
nwk: 10435
manuf id: 4098
manufacturer: _TYZB02_keyjhapk
power: Battery
app version: 66
hard version: 0
zcl version: 3
stack version: 0
date code:
interviewed: true
configured: false

endpoint: 1
profile: 260
input clusters: 0,1,6
output clusters: 25

endpoint: 2
profile: 260
input clusters: 0,1,6
output clusters: 25

![Tuya_innen](https://user-images.githubusercontent.com/8064903/74128366-4ffc1e80-4bdd-11ea-8c82-f9b9db878dc2.png)

Thx in advance

Chris

**Comment by Garmin78** [comment]
Hi DaCHRIS,

How did you solve you issue ?
