### ISSUE TITLE
CC2530 could not work in Coordinator mode

### ISSUE THREAD

**Issue by dzungpv** [Koenkk/zigbee2mqtt#293]
I have exactly module list in the wiki https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices CC2530 from WEBEE, now the seller from aliexpress change to another model.
Image: https://camo.githubusercontent.com/9211fbb4c7f9c5c2298ed60e2e2d7fad60527eae/687474703a2f2f696d672e647863646e2e636f6d2f70726f64756374696d616765732f736b755f3432393437385f322e6a7067

I have try both firmware here https://github.com/kirovilya/files/blob/master/CC2530ZNP-Pro-Secure_LinkKeyJoin.hex and here https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/CC2530/bin/CC2530ZNP-Prod.hex

I also try 4 difference connection: Pi3B UART, CP2102 (include in Webee kit), FT232RL, CH341.

Wiring:
PI:

1 -> VCC
8 -> P02
9 -> Ground
10 -> P03
Connect P20 to GND and not to GND

USB2TTL:

VCC 3.3V ->Pin 4
RX -> P02
TX -> P03
Ground -> Pin 3
Connect P20 to GND and not to GND

Configuration:
Try both advance option: **rtscts: false**  and **rtscts: true**

I also try to swap TX<->RX and 3 difference CC2530 module

Error logs:
https://hastebin.com/mubowexuxi.js

**Comment by dzungpv** [comment]
I try this firmware and it work: http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/
But wiring for Webee CC2530 must be:
P0.2(P2, pin 7)->RS232 TX
P0.3(P2, pin 8)->RS232 RX

So all the firmware ware list in wiki and from KoenKK not work with this module

**Comment by mark078** [comment]
I have the same problem with the cc2530.: https://github.com/Koenkk/zigbee2mqtt/issues/270#issuecomment-413538006

There is a problem with the firmware of ptvo. The Xiaomi Motion sensors with Lux do not work.

**Comment by dzungpv** [comment]
When install Z-Stack Home it also has ZTool. You can try to plug the cc2530 to PC and test woth ztool, if it could connected, nearly it could work with zigbee2mqtt too. Ptvo firmware is not very good. He fixed channel 11, and can not change, also there are some problem. I will try to build new firmware next week.

**Comment by pleasanthill17** [comment]
I want to flash CC2530 with arduino as coordinator . Do you have any suggestions on wiring ? (I had success with CC2531 with arduino as detailed in wiki for alternative flashing.)

**Comment by mark078** [comment]
@dzungpv thanks for the tip with Ztool, I was looking for something like that.

Because of Channel 11 with the ptvo firmware. I had the firmware running with Channel 11, I mean is the default channel setting. But the XIaomi Motion with Lux didn't work with it. 
The other sensors, like switch, cube, water leak sensor and the motion sensor without lux work well. 

I still wonder why the other firmwares don't work for us. 

let me know if you have a firmware that works. I'm starting to think about taking the cc2531 stick + cc2530 router.

@pleasanthill17 is the same as the cc2531, only you have more space. :)
https://github.com/Koenkk/zigbee2mqtt/wiki/Alternative-firmware-flashing-methods
https://github.com/Koenkk/zigbee2mqtt/issues/239

**Comment by mark078** [comment]
@Koenkk I just flashed the FW of @dzungpv and paired a sensor (Xiaomi Motion with Lux). So far it looks good. 
The sensor reacts regularly and often. I'll let this go on overnight.

@dzungpv good work, what did you change to make it work? :)


```
2018-8-20 21:45:53 DEBUG Recieved zigbee message with data {"cid":"genBasic","data":{"modelId":"lumi.sensor_motion.aq2"}}
2018-8-20 21:45:53 INFO New device with address 0x00158d0002006aa6 connected!
2018-8-20 21:45:53 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_connected","message":"0x00158d0002006aa6"}'
2018-8-20 21:45:53 DEBUG Recieved mqtt message on topic 'zigbee2mqtt/bridge/config/devices' with data ''
2018-8-20 21:45:53 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"devices","message":[{"ieeeAddr":"0x00158d0002006aa6","type":"EndDevice","friendly_name":"0x00158d0002006aa6"}]}'
2018-8-20 21:46:00 DEBUG Recieved zigbee message with data {"cid":"msIlluminanceMeasurement","data":{"measuredValue":31}}
2018-8-20 21:46:00 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0002006aa6', payload: '{"illuminance":31}'
...
2018-8-20 21:53:21 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0002006aa6', payload: '{"illuminance":81,"occupancy":true}'
2018-8-20 21:53:21 DEBUG Recieved zigbee message with data {"cid":"msIlluminanceMeasurement","data":{"measuredValue":81}}
2018-8-20 21:53:21 DEBUG Recieved zigbee message with data {"cid":"msOccupancySensing","data":{"occupancy":1}}
2018-8-20 21:53:21 INFO MQTT publish, topic: 'zigbee2mqtt/0x00158d0002006aa6', payload: '{"illuminance":81,"occupancy":true}'

```

**Comment by 1981nick1982** [comment]
The firmware from @dzungpv  solved my problem #165 with the temperature sensors.

**Comment by hdo** [comment]
@dzungpv Do you mind building a router firmware (repeater) as well? Thanks ;-)

**Comment by dzungpv** [comment]
@hdo I will build it very soon

**Comment by Koenkk** [comment]
@dzungpv could you also build the router firmware with increased buffers? [like for the CC2531](https://github.com/Koenkk/Z-Stack-firmware/blob/increased_buffer/coordinator/CC2531/README.md).

**Comment by dzungpv** [comment]
@Koenkk Ok i will follow you guide

**Comment by hdo** [comment]
Great to hear ;-)

**Comment by dzungpv** [comment]
Off topic, i am testing CC2652R1. It could connect to zigbee2mqtt now. It is a very powerful chip, it could run Zigbee 3.0 , Bluetooth 5.0 and Thread. It use **free** CCS editor from TI both on Web and Desktop, if anyone want to play http://www.ti.com/tool/LAUNCHXL-CC26X2R1.

**Comment by dzungpv** [comment]
@Koenkk Following your guide it could not build because out of memory, what IAR version you use to build  CC2531 firmware?

**Comment by dzungpv** [comment]
@Koenkk , i make it work now check git readme https://github.com/dzungpv/Z-Stack-firmware/blob/master/coordinator/CC2530/README.md.
@hdo Router firmware there is no special, you can use ptvo firmware.
@mark078 @1981nick1982 use new firmare for CC2530 with more buffer size here: https://raw.githubusercontent.com/dzungpv/Z-Stack-firmware/master/coordinator/CC2530/bin/CC2530ZNP-Prod.hex

**Comment by mark078** [comment]
@dzungpv Thanks for the improvement, I'll flash it this weekend. :)

What makes more buffer size? Are more Zigbee devices possible with your new firmware? 

I know several reports from the Fhem forum, where from a certain number (20-40) devices no longer react and fail.

@kirovilya has written something about this, that the cc2530/cc2531 have too little memory:
https://github.com/Koenkk/zigbee2mqtt/issues/185#issuecomment-410621872

**Comment by dzungpv** [comment]
@mark078 Yes, it could handle more devices. But this is all experiment. Include zigbee2mqtt itself. Let try it and make it better because each user is a tester.

**Comment by 1981nick1982** [comment]
@dzungpv I will try it tomorrow.

**Comment by faronov** [comment]
@dzungpv and @Koenkk  this firmware https://github.com/dzungpv/Z-Stack-firmware/tree/master/coordinator/CC2530_CC2591 also contains @dzungpv fixes?
what must I add/change for make cc2591 enable?
how I can increase power when I use cc2591 (I know this must be set in the code) but don't know right numbers for cc2591
I read TI documentation about that, but not understood completely.

**Comment by dzungpv** [comment]
@faronov you can download it here https://github.com/Koenkk/zigbee2mqtt/issues/181#issuecomment-415667357 but it may not stable, i will publish to git repos soon

**Comment by faronov** [comment]
Thanks @dzungpv , did you try connect this to RPI3 serial ?
Also you found where to set power ? (I also see somewhere in znp that power signal can be setted from config)

**Comment by faronov** [comment]
I think this is place for that https://github.com/zigbeer/cc-znp/blob/master/lib/defs/zmt_defs.json#L61

**Comment by faronov** [comment]
from documentation
--------------------------
3.8.1.18 SYS_STACK_TUNE
Description
This command is used by the tester to tune intricate or arcane settings at runtime.
Usage
SREQ:
1 1 1 1 1
Length = 0x02 Cmd0 = 0x21 Cmd1 = 0x0F Operation Value
Attributes:
The tuning operation to be executed according to the STK_Tune_t enumeration:
Operation Value
Set the transmitter power level according to the value of the Value parameter
which should correspond to the valid values specified by the
ZMacTransmitPower_t enumeration (0xFD – 0x16)
0x00
Set RxOnWhenIdle off/on if the value of Value is 0/1; otherwise return the
current setting of RxOnWhenIdle.
0x01
SRSP:
1 1 1 1
Length = 0x01 Cmd0 = 0x61 Cmd1 = 0x0F Value
Attributes:
Attribute Length (byte) Description
Value 1 Applicable status of the tuning operation.
-------------

**Comment by faronov** [comment]
I'l try use this boards
http://www.cdebyte.com/en/product-view-news.aspx?id=123
http://www.cdebyte.com/en/product-view-news.aspx?id=121
It have cc2592 amplifier , but as I understood , in code , no differences , this is just amplifier , and have same connection

**Comment by dzungpv** [comment]
@faronov 
for PI:
1 -> VCC
8 -> P02
9 -> Ground
10 -> P03
The TX power set default by the firmware, I have test it, has better range compare to CC2530

**Comment by dzungpv** [comment]
@faronov it difference and not work with my firmware, you must build it your self. You can read this https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/p/485641/1758523?tisearch=e2e-quicksearch&keymatch=HAL_PA_LNA_CC2592%20ethan%20Chen#pi319568filter=all&pi319568scroll=false&pi319568=4

**Comment by faronov** [comment]
@dzungpv Thanks, but what you add more to that project cc2530+cc2591 than described in this readme https://github.com/dzungpv/Z-Stack-firmware/tree/master/coordinator/CC2530 ?

**Comment by dzungpv** [comment]
@faronov just add 1 more line to build tag HAL_PA_LNA nothing more:
```
FEATURE_SYSTEM_STATS
ASSERT_RESET
xPOWER_SAVING
FAKE_CRC_SHDW
TC_LINKKEY_JOIN
ENABLE_MT_SYS_RESET_SHUTDOWN
SECURE=1
INTER_PAN
ZTOOL_P1
CC2530_MK
HAL_LCD=FALSE
HAL_ADC=FALSE
HAL_UART_DMA_RX_MAX=128
NWK_MAX_DEVICE_LIST=15
MAX_NEIGHBOR_ENTRIES=10
MAXMEMHEAP=3120
INCLUDE_REVISION_INFORMATION
HAL_PA_LNA
```

**Comment by dzungpv** [comment]
@faronov You can also check this post https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/465007 But make sure the CDEbyte module schematic like TI ref device, or you can ask them about CC2592 wiring

**Comment by faronov** [comment]
@dzungpv Thanks again, I found good info from your link
http://processors.wiki.ti.com/index.php/Enabling_the_Support_of_CC259x_PA/LNA_with_Z-Stack-Home-Automation-1.2.1
CDEbyte well documented and have pinout table.

**Comment by faronov** [comment]
but I still confusing about  ZMacSetTransmitPower(), what I definitely know if you set value more than board supported, it will use the mask, and set it lower than expected.

**Comment by dzungpv** [comment]
@faronov check this https://github.com/dzungpv/Z-Stack-firmware/blob/master/coordinator/CC2530_CC2591/README.md

**Comment by faronov** [comment]
@dzungpv Thanks again, I will try to find the maximum for cc2592.

**Comment by faronov** [comment]
regarding this http://www.ti.com/product/cc2592 maximum is 22 for cc2592

**Comment by ciotlosm** [comment]
Was the firmware linked in the docs for CC2530 updated with the findings in this issue?

**Comment by dzungpv** [comment]
@ciotlosm I have fixed the firmware, but forget to close this.

**Comment by RodBr** [comment]
Hi all, what's the difference between this firmware and the firmware referenced here: [https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices](url)
I can't get that to work with my CC2530 so I'm searching for alternatives.

**Comment by kiwijunglist** [comment]
Hi

I have cc2530 with external aerial. i want to use it as co-ordinator with zigbee2mqtt running in hass.io on an intel nuc connected via usb-ttl cable.

Which firmware do i install?

thanks
kiwi
