### ISSUE TITLE
Please include:  IKEA LED1903C5, TRADFRI bulb E14 WS 470lm

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#2931]
Please include the new IKEA light bulb:  LED1903C5 - IKEA TRADFRI LED bulb E14 470 lumen, dimmable, white spectrum, opal white (Router)
It presents it self with: TRADFRI bulb E14 WS 470lm

{"ieeeAddr":"0x680ae2fffe875d1a","type":"Router","networkAddress":6526,"model":"LED1903C5","friendly_name":"LampEddy","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelID":"TRADFRI bulb E14 WS 470lm","hardwareVersion":1,"softwareBuildID":"2.1.022","dateCode":"20190312","lastSeen":1581419866107

https://www.ikea.com/nl/nl/p/ledare-led-lamp-e14-470-lumen-warm-dimmen-kaarslamp-opaalwit-60438588/
dimmable, color temperature and on/off

**Comment by sjorge** [comment]
```
    {
        zigbeeModel: ['TRADFRI bulb E14 WS 470lm'],
        model: 'LED1903C5',
        vendor: 'IKEA',
        description: 'TRADFRI bulb E14 WS 470 lumen, dimmable, white spectrum, opal white',
        extend: generic.light_onoff_brightness_colortemp,
        ota: ota.tradfri,
    },
```

I think the following entry should work, not tested as I do not have the bulb.

**Comment by sjorge** [comment]
You probably need to remove the `ota: ota.trodfri,` line if you are not on 1.10+dev

**Comment by SargonofAssyria** [comment]
Yes, that did work. This has now only to be included in the next beta.
And now I have to wait for the zigbee2mqtt-plugin, because it does not show up in Domoticz yet.

**Comment by sjorge** [comment]
I'll do a PR against converter repos to get this included.

**Comment by blakadder** [comment]
I'm only finding LEDARE bulbs under that model number... Is there a link to a Tradfri version?

**Comment by sjorge** [comment]
@blakadder I'm not sure, I based it off the database entry posted by @SargonofAssyria

**Comment by SargonofAssyria** [comment]
Its a new bulb, link in the first post. And it is working.

**Comment by blakadder** [comment]
do you have an SKU for the bulb  or some other item code?

**Comment by SargonofAssyria** [comment]
Yes I have, but currently I am on ski holliday, so after next saterday.

**Comment by SargonofAssyria** [comment]
On the box it states: Tradfri LED 470 lm 5.2W E14 LED1835C6
And under the barcode 704.243.12 19972
