### ISSUE TITLE
[SUGGESTION] Use npm ci in docs concerning raspberry pi instead of npm install

### ISSUE THREAD

**Issue by 9SMTM6** [Koenkk/zigbee2mqtt#2934]
This is NOT a bug, but on low-power devices like the Raspberry, especially if the used memory is low-power, you could get an potentially great speed improvement by using `npm ci` instead of `npm install`. `npm ci` is using the package-lock or shrinkwrap files instead of the package files, and should acess the memory less to verify the current state of the node packages.

**Comment by Koenkk** [comment]
Let's continue in #2918
