### ISSUE TITLE
Philips Hue Welcome white flood light new model number 1743630V7

### ISSUE THREAD

**Issue by misteriks** [Koenkk/zigbee2mqtt#2935]
I bought a new Philips Hue Welcome white flood light, but apparently it has a new model number and therefore not recognized out of the box 

warn  2020-02-10 23:45:18: Received message from unsupported device with Zigbee model '1743630**V**7'

It is similar as the already supported 1743630**P**7 so copy paste this model and updated devices.js and homeassistant.js in my HASSIO

    {
        zigbeeModel: ['1743630P7'],
        model: '17436/30/P7',
        vendor: 'Philips',
        description: 'Hue Welcome white flood light',
        extend: hue.light_onoff_brightness,
    },

can you add support for this model.

Thx!

**Comment by Koenkk** [comment]
added, thanks!
