### ISSUE TITLE
Sonoff BasicZBR3 - state not updated

### ISSUE THREAD

**Issue by hossamnagy** [Koenkk/zigbee2mqtt#2939]
# Bug Report
## What happened
When turning on BASICZBR3 switch through Lovelace card, The switch turn-on momentarily and then return to the OFF state. The device it self is turned ON 

From log files it appears that zigbee2mqtt is unable to parse the state reported by the device . 

## What did you expect to happen
The Switch should remain on the ON state until turned OFF . 

## Debug Info
zigbee2mqtt version: 1.10.0-dev
CC253X firmware version:{'type': 'zStack12', 'meta': {'transportrev': 2, 'product': 0, 'majorrel': 2, 'minorrel': 6, 'maintrel': 3, 'revision': 20190608}}

Debug  log below :
zigbee2mqtt:debug 2020-02-13 08:10:14: Received MQTT message on 'zigbee2mqtt/0x00124b001e731e73/set' with data 'ON'
zigbee2mqtt:debug 2020-02-13 08:10:14: Publishing 'set' 'state' to 'KitchenFan'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received MQTT message on 'zigbee2mqtt/0x00124b001e731e73/set' with data 'ON'
zigbee2mqtt:debug 2020-02-13 08:10:14: Publishing 'set' 'state' to 'KitchenFan'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:debug 2020-02-13 08:10:14: Received Zigbee message from 'KitchenFan', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'
zigbee2mqtt:info  2020-02-13 08:10:14: MQTT publish: topic 'zigbee2mqtt/KitchenFan', payload '{"state":"ON","linkquality":36}'

**Comment by Koenkk** [comment]
> From log files it appears that zigbee2mqtt is unable to parse the state reported by the device .

Please post the logs of these errors.

**Comment by hossamnagy** [comment]
Closing this issue as the problem is now resolved ! not sure what was the error .  the main change I did was to upgrade to the latest home assistant version this morning.
