### ISSUE TITLE
docker Error: Cannot find module 'axios'  

### ISSUE THREAD

**Issue by dartheide** [Koenkk/zigbee2mqtt#2940]
Hi All
I did a git pull origin master on the zigbee-herdsman-converters and a docker pull koenkk/zigbee2mqtt:latest.
Now the container doesn't start. 
I found an error Cannot find module 'axios'  

See for details the log file.
[zigbee-error.txt](https://github.com/Koenkk/zigbee2mqtt/files/4195479/zigbee-error.txt)

How do I resolve this problem?

**Comment by Koenkk** [comment]
You need to execute `npm ci` in the `zigbee-herdsman-converters` folder.

**Comment by addisonlynch** [comment]
@Koenkk same issue except running within a docker container. Any suggestions? Not a node expert.
