### ISSUE TITLE
Error after updating system

### ISSUE THREAD

**Issue by thomas1977mg** [Koenkk/zigbee2mqtt#2949]
Dear all - 
since today and after updating my system I get the following errors and I can´t get rid of it.
I updated the system a lot of time. Also npm update.
Xbridge will not start. What can I do?

`/opt/zigbee2mqtt $ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's js-yaml@3.12.0 does not satisfy js-yaml@^3.13.1
npm ERR! Invalid: lock file's nyc@13.1.0 does not satisfy nyc@^14.1.0
npm ERR!
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-02-14T22_43_42_203Z-debug.log`

**Comment by Koenkk** [comment]
What is the output of `git status`?
