### ISSUE TITLE
Xiaomi Aquara button WXKG11LM hold action not mapped to state

### ISSUE THREAD

**Issue by dstockhammer** [Koenkk/zigbee2mqtt#2953]
#  Bug Report
## What happened
I'm using a couple [Xiaomi WXKG11LM ](https://www.zigbee2mqtt.io/devices/WXKG11LM.html) buttons to trigger automations.
The `click` action is mapped to state in ha as expected; I can see the state changing to `single` or `double` respectively. However, `action` is not mapped. I can see the `action` attribute change as expected to `hold` and `release`, but the state remains empty. 
Is this expected? Here are the relevant messages that are coming through on holding and releasing the button:

```
zigbee2mqtt:info  2020-02-15 22:25:53: MQTT publish: topic 'zigbee2mqtt/xx', payload '{"battery":100,"voltage":3135,"linkquality":63,"action":"hold"}'
zigbee2mqtt:info  2020-02-15 22:25:53: MQTT publish: topic 'zigbee2mqtt/xx', payload '{"battery":100,"voltage":3135,"linkquality":63,"action":""}'
zigbee2mqtt:info  2020-02-15 22:25:56: MQTT publish: topic 'zigbee2mqtt/xx', payload '{"battery":100,"voltage":3135,"linkquality":63,"action":"release"}'
zigbee2mqtt:info  2020-02-15 22:25:56: MQTT publish: topic 'zigbee2mqtt/xx', payload '{"battery":100,"voltage":3135,"linkquality":63,"action":""}'
```

## What did you expect to happen
I would expect the state change to `holding` or something like that. That way automations can be triggered easily. Should `cfg.sensor_action` be configured in the [config mapping for the device](https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js#L511)?

## Debug Info
zigbee2mqtt version: 1.10.1
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
Added in the latest dev branch, thanks!
