### ISSUE TITLE
Can not start herdsman v.1.10

### ISSUE THREAD

**Issue by nickman80** [Koenkk/zigbee2mqtt#2959]
Hi Guys,
sorry to bother you, but i have been stuck for couple days with zigbee herdsman, would appreciate for any help, also i have checked Faq and everything seem to be good, re-flashed cc2531, re-install software and still same this is my log [https://pastebin.com/i30b2kYH](url) not sure why but url does not open, you have to copy and paste
thank you

_Originally posted by @nickman80 in https://github.com/Koenkk/zigbee2mqtt/issues/2891#issuecomment-586819902_

**Comment by Koenkk** [comment]
`Error: Error Resource temporarily unavailable Cannot lock port` means that other software on the system is already occupying the port, you need to find out which.

**Comment by nickman80** [comment]
Thank you for fast reply and your time, i have already checked ports on raspberry and AM0 is for zigbee and other one AM1 is for rflink, is there other way how to check them? Even when i had rflink port disconnected did not work.

**Comment by nickman80** [comment]
ok so, i have figured out, the same port ACM0 had been used in NodeRed, 
processes list using serial ports :
ls -l /proc/[0-9]*/fd/* |grep /dev/ACM0       ---replace ACM0 with actual port that you searching 
then you will get /proc/14683....your number will be different and then you have to run in terminal : ps aux     and from list you can find your proc number (PID) and see where is it linked to.
