### ISSUE TITLE
Feature request: notification of the pairing steps of a specific device

### ISSUE THREAD

**Issue by directman66** [Koenkk/zigbee2mqtt#2960]
I would like to add a visualization of the device pairing process in the same way as it was done in the IObroker. For this, it is necessary at the time of pairing to publish the current status of the device being added to a certain topic. Sending data is needed in a special topic of MQTT.

**Comment by Koenkk** [comment]
These things are already logged to MQTT:

- `device_connected` (https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L187)
- `interview_started` (https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L214)
- `interview_successful` (https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L205)
