### ISSUE TITLE
CC2531 issue (probably), no devices turn on/off

### ISSUE THREAD

**Issue by MonsieurSander** [Koenkk/zigbee2mqtt#2963]
Hi! 

I was sitting on my couch, not doing anything with hassio, when I noticed that the cc2351 produced a continuous green light instead of a blinking one as is usual. Curiously, I tried to turn on of my light, and it didn't work. I tried all other lights and the same issue was there. None of my zigbee devices could be actuated. Tried to power down the raspberry, replug the USB stick, restart both zigbee2mqtt and mosquito but none seems to work. Running zigbee2mqtt 1.10.0 and the stick is on 08062019. Bought the stick with the firmware installed, reckon I need to get a cc-debugger and see if that helps.

https://pastebin.com/FKywwjLK the log file

**Comment by Koenkk** [comment]
Probably your CC2531 crashed, I would recommend flashing the source routing firmware to improve stability. https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

**Comment by MonsieurSander** [comment]
Thanks for your reply, was thinking along the same lines, cc debugger will arrive next week. Will post the results in here for future reference

**Comment by MonsieurSander** [comment]
Reflashing the hub did the trick!

**Comment by Koenkk** [comment]
Good, I assume this can be closed now
