### ISSUE TITLE
Wrong Home Assistant config for OSRAM SMART+ Spot GU10 Multicolor (AC08559)

### ISSUE THREAD

**Issue by H3adcra5h** [Koenkk/zigbee2mqtt#2966]
# Bug Report
## What happened
In Home Assistant the "OSRAM SMART+ Spot GU10 Multicolor (AC08559)" isn't shown as multicolored. **"xy":true** is missing in the payload 

The bug is in lib/extension/homeassistant.js line 963
is: ` 'AC08559': [cfg.light_brightness_colortemp],`
should: ` 'AC08559': [cfg.light_brightness_colortemp_colorxy],`

the "Manual Home Assistant configuration" for this device "devices/AC08559.html" is also missing the property **xy: true**

## What did you expect to happen
**"xy":true** in the payload and manual Home Assistant configuration

## Debug Info
zigbee2mqtt version: 1.9.0
current payload:
```
topic 'homeassistant/light/0xf0d1b80000128614/light/config', payload '{"brightness":true,"color_temp":true,"schema":"json","command_topic":"zigbee2mqtt/0xf0d1b80000128614/set","state_topic":"zigbee2mqtt/0xf0d1b80000128614","json_attributes_topic":"zigbee2mqtt/0xf0d1b80000128614","name":"0xf0d1b80000128614_light","unique_id":"0xf0d1b80000128614_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0xf0d1b80000128614"],"name":"0xf0d1b80000128614","sw_version":"Zigbee2mqtt 1.9.0","model":"SMART+ Spot GU10 Multicolor (AC08559)","manufacturer":"OSRAM"},"availability_topic":"zigbee2mqtt/bridge/state"}'
```

**Comment by Koenkk** [comment]
Fixed in latest dev branch, thanks!
