### ISSUE TITLE
Disable led of QBCZ11LM

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#297]
Its possible disable the led of the QBCZ11LM?

MiHome have this option, is possible via MQTT?

**Comment by Koenkk** [comment]
Not yet, we have to see what zigbee command is used for this.

**Comment by jasimancas** [comment]
If you need help with this, tell me.

**Comment by ryanbeaton** [comment]
I hope it’s the same for the ZNCZ02LM. I’d like to see that

**Comment by ryanbeaton** [comment]
Does @subzero79 info help in https://github.com/Koenkk/zigbee2mqtt/issues/201#issuecomment-415231510

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasimancas** [comment]
Great! :D

**Comment by subzero79** [comment]
Also worth to mention i did notice that once the attribute is set via gateway, and then repairing with zigbee2mqtt the attribute stays, the same happens with restore power state. So if you want to disable the led just pair them with the gw, set it via app, then repair again. with zigbee2mqtt

**Comment by ryanbeaton** [comment]
Thanks @subzero79 That’s good to know. I’ve never had a bridge as started my purchasing after starting with Zigbee2MQTT, hmmmm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YES-Lee** [comment]
> If you need help with this, tell me.

Hi, how do you resolve this?
