### ISSUE TITLE
EcoSmart A9A19A60WESDZ02 device not supported (narrator: it is)

### ISSUE THREAD

**Issue by roygbiv856** [Koenkk/zigbee2mqtt#2972]
## What happened
When trying to pair EcoSmart A9A19A60WESDZ02 with new CC26X2R1 coordinator, I get message "Device not supported. Visit this link to support new devices"

## What did you expect to happen
I expected the bulb to pair successfully considering that it is indeed already is a supported device.

## How to reproduce it (minimal and precise)
Place coordinator into pairing mode, turn bulb off/on 5 times in 6 seconds

## Debug Info
zigbee2mqtt version: 1.6 (hassio add on)
CC253X firmware version: newest available

**Comment by Koenkk** [comment]
You are running an old zigbee2mqtt version, try updating to zigbee2mqtt 1.10.

**Comment by mkaatman** [comment]
zigbee2mqtt version: 1.25
zStack3x0 20211217

Same issue.
