### ISSUE TITLE
Schedule network scans

### ISSUE THREAD

**Issue by derekoharrow** [Koenkk/zigbee2mqtt#2973]
## What happened
Regular network scan is interfering with switches being turned on/off.

## What did you expect to happen
Would like to be able to set when the regular network scan runs, rather than at 00:00, 03:00, 06:00, 09:00, etc.

## Debug Info
zigbee2mqtt version: 1.10.0-dev
CC253X firmware version: 2.6.3 (20190608)

**Comment by carldebilly** [comment]
There is NO automated network scan in Z2M... but there's one in Z2MA (Zigbee2MqttAsssitant) and you can change it using the `NetworkScanSchedule` setting: <https://github.com/yllibed/Zigbee2MqttAssistant#settings>

**Comment by derekoharrow** [comment]
Thank you!
