### ISSUE TITLE
Timeout error with Tradfri LED1623G12

### ISSUE THREAD

**Issue by louismulder** [Koenkk/zigbee2mqtt#2976]
# Bug Report
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4230998/log.txt)

## What happened
An timeout error is given, when a get command is given.
The connection with the MQTT server is also short broken. 
Sometimes the device is working and sometimes not 
## What did you expect to happen
No timeout error
## How to reproduce it (minimal and precise)
It always happens
## Debug Info
zigbee2mqtt version:1.10.0
CC253X firmware version:20190608

**Comment by dani203** [comment]
I have the same issue with many of my Ikea lights, aswell as my Osram Smart Socket and my Osram Garden pole lights. Sometimes just a simple powercycle fixes it, sometimes i actually need to completely re- pair the lights in order to fix the Problem. Very annoying!

**Comment by Koenkk** [comment]
Please try with the latest dev branch. Yesterday I've pushed a fix to rediscover the route on timeout.

**Comment by dani203** [comment]
Just installed Z2M-edge, i will keep you updated if that fixes it.
Thank you for your work!

**Comment by louismulder** [comment]
I have installed the last dev branch and the good news is that the timeout error is gone, but the bad news is that it will took 18 seconds before the command is executed on the device.
See the logging:
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4236952/log.txt)

**Comment by Koenkk** [comment]
But after this does the bulb work as expected?

**Comment by louismulder** [comment]
Hi Koen,

Yes I can give Brightness, On and Off, but always executing with a delay of 18 seconds. So this is not a working situation.

**Comment by louismulder** [comment]
Here is the log with the DEBUG=zigbee-herdsman* 
[debug.txt](https://github.com/Koenkk/zigbee2mqtt/files/4237679/debug.txt)

**Comment by Koenkk** [comment]
- Do you really have only 1 device connected in your network?
- Is your CC2531 connected through a USB extension cable? (to avoid interference)
- How far is the bulb from the coordinator?
- Can you try with the source routing firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

**Comment by dani203** [comment]
I'm still encountering timeout issues even with the developement build (zigbee2mqtt-edge for home assistent/hassio)

the weird thing i noticed is, that it doesn't seem to happen when i call a light from a group, in that case it responds instantaniously. 

The Problem accours with "0x7cb03eaa00adfdd4", which is part of the group "balkon" as defined in the groups.yaml

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4242355/log.txt)

**Comment by louismulder** [comment]
> * Do you really have only 1 device connected in your network?
> * Is your CC2531 connected through a USB extension cable? (to avoid interference)
> * How far is the bulb from the coordinator?
> * Can you try with the source routing firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

I have tested it again with version 1.10.0 with the following:
I'am testing it with only one device
The CC2531 is connected with an USB extension cable
The bulb is 50 cm far from the coordinator
I have also tried source routing. Same result

**Comment by Koenkk** [comment]
@dani203 the zigbee2mqtt edge addon update takes a little bit longer (could be a few hours), please try again in a few hours and provide the herdsman debug logging. https://www.zigbee2mqtt.io/information/debug.html#hassio-addon

@louismulder could you also provide the herdmsan debug logging with the latest zigbee2mqtt dev branch? (https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging). Try turning the device on/off a few times.

**Comment by louismulder** [comment]
Here are the tests.
First one with zstack1.2 default
[debug_default.txt](https://github.com/Koenkk/zigbee2mqtt/files/4242464/debug_default.txt)

Second with zstack1.2 source
[debug_source.txt](https://github.com/Koenkk/zigbee2mqtt/files/4242465/debug_source.txt)

**Comment by Koenkk** [comment]
@louismulder very strange issue, could you sniff the traffic of this? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by dani203** [comment]
> @dani203 the zigbee2mqtt edge addon update takes a little bit longer (could be a few hours), please try again in a few hours and provide the herdsman debug logging. https://www.zigbee2mqtt.io/information/debug.html#hassio-addon
> 
Here is my Logfile, as you can see, trying to switch the lamp 0x7cb03eaa00adfdd4 directly ended in a timeout. However switching it's corresponding group "Balkon" worked flawlessley.
It doesn't always fail to switch by the way, sometimes it works great, often it doesn't.

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4249701/log.txt)

**Comment by Koenkk** [comment]
Via a group it's broadcast so all devices will receive it. Could you sniff the traffic?

**Comment by louismulder** [comment]
> @louismulder very strange issue, could you sniff the traffic of this? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

@Koenkk I have tried to setup a Zboss sniffer according the documentation, but I couldn't get it working.
I only see broadcast messages.
![image](https://user-images.githubusercontent.com/10274845/75285410-d8520480-5816-11ea-8b1e-3bb47f3f035e.png)

**Comment by dani203** [comment]
Sorry, can't help with that at the moment, i don't have a way of flashing software to the dongle, 
 since i bought it with the right firmware already on it. I will look into getting a programmer and a second dongle to sniff the traffic

**Comment by louismulder** [comment]
@Koenkk I have now found, why zboss didn't work:
ZBoss starts default with 0xC(12) but should start with 0xB(11)
Tomorrow I'll try to create the Wireshark dump.
![image](https://user-images.githubusercontent.com/10274845/75384855-f5eaa100-58de-11ea-869a-a94031760580.png)

**Comment by louismulder** [comment]
@Koenkk I think that the issue is solved.
I have a production environment (1.10.0) and a test environment (1.10.1). Only one environment could be active was my issue.
So I paused my production environment and started after that the test environment and now there are NO issues.

Pls can you add the settings for ZBoss in the documentation?

**Comment by Koenkk** [comment]
Good that you found the problem!

- When there are 2 networks using the same `pan_id` and `channel` you will indeed run into these strange problems.
- I've updated the sniffing ZBOSS documentation
