### ISSUE TITLE
Error: SRSP - SYS - osalNvWrite after 6000ms

### ISSUE THREAD

**Issue by timdonovanuk** [Koenkk/zigbee2mqtt#2977]
Just logging this as I seem to be breaking the record for new errors this week :)

Clean install of debian VM on proxmox. Clean install of docker, and z2m:

```
zigbee2mqtt:info  2020-02-20 14:06:46: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-02-20 14:07:32: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-02-20 14:07:32: Failed to start zigbee
zigbee2mqtt:error 2020-02-20 14:07:32: Exiting...
zigbee2mqtt:error 2020-02-20 14:07:32: Error: SRSP - SYS - osalNvWrite after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
```
CC1352P-2 with latest firmware.

**Comment by timdonovanuk** [comment]
> test -w /dev/ttyACM0 && echo success || echo failure
this reports success

Just saw the FAQ about needing to push the CC1352P-2 button on intel NUC. Tried that also.

**Comment by AndrzejOlender** [comment]
I had that error yesterday, the FAQ description worked.

**Comment by timdonovanuk** [comment]
The odd thing is I had the CC1352P-2 working "fine" in HassOS on Proxmox with USB passed through, never needing to push any button. Only just found out about this.

I've tried the button push thing anyway, no joy.

**Comment by timdonovanuk** [comment]
My CC1352P-2 seems to be bricked. Reflashed it even, still same thing.

**Comment by Koenkk** [comment]
Make sure to execute step 5 from https://www.zigbee2mqtt.io/information/flashing_via_uniflash.html

**Comment by timdonovanuk** [comment]
Pretty sure I did that (although it says not required in the steps) but tried again just to be sure. Different error this time but similar "Error: AREQ - SYS - resetInd after 30000ms", which is already logged elsewhere. I seem to get lots of different errors, but maybe this was caused by a missteps in flashing so will close for now. Cheers.
