### ISSUE TITLE
How to perform manual config copy and restore  ?

### ISSUE THREAD

**Issue by robin-s-007** [Koenkk/zigbee2mqtt#2981]
Hello,

Which files do I need to backup in order to manual restore my current config after a reinstall / update ?
Background:
I have been running zigbee2mqtt V1.6.0 with much joy for the past few months on a PI.
Now I wanted to upgrade to V1.10.0 using the update script in the zigbee2mqtt dir, but this resulted in a broken installation.
Fortunately I created a full zip backup, which I was able to restore.

Now I want to perform a full new install of V1.10.0 and manually restore my zigbee config in the new installation. But I do not know which files to selectively copy and restore.

Thanks in advance,

Robin

**Comment by Kryzek** [comment]
If you have everything from inside of data-directory backupped you should be fine.
