### ISSUE TITLE
No link quality for Tradfri bulb

### ISSUE THREAD

**Issue by sgofferj** [Koenkk/zigbee2mqtt#2983]
# Bug Report
## What happened
Added a Tradfri bulb to my network. Linkquality does not show in Homeassistant.
Did a little debugging as far as my knowledge goes. The linkquality does show in the network map addon I have installed but zigbee2mqtt does not report it to HA. It's also not in homeassistant/light/-zigbee-address-/light/config

## What did you expect to happen
Linkquality should be published to HA.

## How to reproduce it (minimal and precise)
Add a Tradfri bulb, I guess.

## Debug Info
zigbee2mqtt version: docker latest (as of opening time of this issue)
CC253X firmware version: CC2531_DEFAULT_20190608

**Comment by Koenkk** [comment]
You won't get linkquality reports be default as by default they don't send any messages to the coordinator. 

There are 2 ways this can be achieved:
- If you just want to measure it once create a networkmap: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgenetworkmap
- Enable the reporting feature, when this is enabled the bulb will report's it's state to the coordinator when it's turned on/off (= a message containing the linkquality). However note that this will increase the network traffic: https://www.zigbee2mqtt.io/information/report.html
