### ISSUE TITLE
Hue Dimmer latency for on/off buttons

### ISSUE THREAD

**Issue by patrickharris** [Koenkk/zigbee2mqtt#2985]
Ideally the on/off buttons on the dimmer should not support the 'on-hold' and 'on-hold-release' behaviour (only the two middle up and down buttons should) as this delays the output message. Ideally the on/off buttons would act instantly upon press, the way they do on the hue hub, meaning zero latency.

**Comment by ZzetT** [comment]
I agree. I found it very strange that there is such a long delay compared to the hub which acts immediately (although I only poll the state from the hub).
