### ISSUE TITLE
Lqi between router's and coordinator 0 or 1

### ISSUE THREAD

**Issue by Diddlik** [Koenkk/zigbee2mqtt#2989]
While building the ZigBee network I noticed that all routers have lqi 1 or 0 to the coordinator. E.g. DW.Testing (door contact) are much further than both routers. 
Coordinator: 1352P with external antenna (capacitor re-soldered).
RouterFlurEG -> CC1352 with Router Firmware
Router.TVLED -> Xiaomi Plug

## Debug Info
zigbee2mqtt version: 1.10.0
CC2531 firmware: CC2531_router_2019_02.zip
CC1352P firmware: 20191106 Z-Stack_3.x.0 firmware.

![grafik](https://user-images.githubusercontent.com/6010713/75113801-1c93a800-5651-11ea-96b5-2510d1a6ef02.png)

**Comment by xefil** [comment]
Hello!
Sorry for OT information, but how do you generate the map? Looks cool!
I'm having CC2531 routers with `CC2531_router_2019_02` 1.2 and I'm getting 'Failed to execute LQI'...
Thanks, Simon

**Comment by Diddlik** [comment]
Hi, i used Zigbee2MqttAssistant

**Comment by 1igeza** [comment]
I have the same with CC2530 coordinator and CC2530 routers. Zigbee2mqtt version 1.10.0-dev (commit #9cc84fe)

![indeks](https://user-images.githubusercontent.com/39980292/75277110-b309ca00-5807-11ea-935d-6a0a4c25ccfa.png)

**Comment by highlandr** [comment]
WiFi network most probably, move the WiFi away from channel 1.
Had the same...
