### ISSUE TITLE
WXKG02LM device

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#299]
Several times a day I get this message:
2018-8-21 12:39:17 - warn: No converter available for 'WXKG02LM' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"65281":[null,null,null,null,5032,51,[0,8],null,null,null,0]}}'

The device works fine, or am I missing something? So why the warning?

**Comment by Koenkk** [comment]
This message can be ignored, yesterday somebody submitted a PR for this: https://github.com/Koenkk/zigbee-shepherd-converters/pull/55 .

-> will be ignored in the next version of zigbee2mqtt.
