### ISSUE TITLE
Support for renaming groups

### ISSUE THREAD

**Issue by BlackLight** [Koenkk/zigbee2mqtt#2991]
I haven't yet found a way to rename a group, and the documentation doesn't seem to mention any such feature. What I've tried:

- Post to `zigbee2mqtt/bridge/config/rename` with the following payload:

```json
{"old":"Old Name", "new":"New Name"}
```

- Post to `zigbee2mqtt/Old Name/set` with the following payload:

```json
{"friendly_name":"New Name"}
```

None of these works and nothing is reported on the log about wrong syntax. Am I missing something?

**Comment by sjorge** [comment]
AFAIK `zigbee2mqtt/bridge/config/rename` only works for devices.

**Comment by Koenkk** [comment]
This was indeed missing, implemented in the latest dev branch.
