### ISSUE TITLE
Xiaomi Smoke Detector not pairing.. Maximum devices reached?

### ISSUE THREAD

**Issue by ljpaff** [Koenkk/zigbee2mqtt#2994]
# Bug Report
## What happened

I have xiaomi devices installed within a zigbee network with a coordinator and a router. I have attached the device map to the issue. When I try to pair another smoke detector, it is not able to join the current network. As I read the maximum number of devices including the link to the coordinator is 21 devices. Currently there are 20 but I find it strange that they do not let me connect such a device if I have another one installed.

![image](https://user-images.githubusercontent.com/27012839/75151776-cc2b5180-5707-11ea-859e-e0c6d77b65f7.png)

## What did you expect to happen
Joining device into Zigbee network.
## How to reproduce it (minimal and precise)
n/A
## Debug Info
zigbee2mqtt version: 1.9.0 (commit #287f843)
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
Can you try if reflashing the CC2531 fixes the problem? (doesn't require repairing).

**Comment by ljpaff** [comment]
> Can you try if reflashing the CC2531 fixes the problem? (doesn't require repairing).

Which one do i have to reflash, the coordinator, the router or both?

**Comment by Koenkk** [comment]
coordinator.

**Comment by ljpaff** [comment]
It worked!!!!!!. What is the problem that makes me reflash the coordinator?

**Comment by Koenkk** [comment]
I think that devices that were previously a child of the coordinator still occupy a place in the direct children table. I've added this to the FAQ (as I think it's not easy solvable as it has to be done in the firmware which is not developed anymore by Texas Instruments). https://www.zigbee2mqtt.io/information/FAQ.html#no-logging-is-shown-at-all
