### ISSUE TITLE
Duplicate entry in database.db

### ISSUE THREAD

**Issue by claudio-petrini** [Koenkk/zigbee2mqtt#2999]
Hello,
when pairing a Philips HUE model 9290012573A two entries are inserted in the database.db file:
- one has the key `modelId` and has `"type": "Router"`
- one doesn't have the key `modelId` and it's an `EndDevice`.

When trying to control the bulb by publishing to `zigbee2mqtt/${friendlyName}/set` we've noticed that only the entry with `modelId` can be controlled while the other generates the following warning:

```
Device with modelID 'undefined' is not supported.
```

Is the assumption correct that we can control only the entry with the `modelId` key defined?
Does the key `modelId` exist for all the supported devices?   

Thank you

**Comment by Koenkk** [comment]
I don't think it's the bulb but another device, could you share your `database.db`?

**Comment by claudio-petrini** [comment]
Hello @Koenkk, you were right there was another device that was connected to the coordinator. 
Apologize, and thank you again for the assistance.
