### ISSUE TITLE
Docker version 0.1.0

### ISSUE THREAD

**Issue by tweaker** [Koenkk/zigbee2mqtt#301]
How do I update the docker version?
I install:
```
docker run -it --restart always --name zigbee2mqtt -v zigbee2mqtt_data:/app/data --device=/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0014D9E292-if00 koenkk/zigbee2мктт
```

In log:
Starting zigbee2mqtt version 0.1.0 (commit # ae41b7b)

**Comment by Koenkk** [comment]
In the end put `koenkk/zigbee2mqtt:0.1.3` or remove the image before run `docker rmi -f zigbee2mqtt`
