### ISSUE TITLE
Status of Group with Tradfri Remote

### ISSUE THREAD

**Issue by R-Rosenow** [Koenkk/zigbee2mqtt#3022]
# Bug Report
## What happened
When I switch my Lights on with the Ikea E1810 Remote (via Group), then Zigbee2Mqtt don't send a State to my OpenHab Server. The remote has the update via OTA, but the solution for binding at groups don't work. It just work with the classic work with the original group ID of the remote.

Is there any Solution?

In the MQTT Messages via Zigbee2Mqtt.service nothing happen. Just the message of the toggle from the remote.

## What did you expect to happen
I want to see wenn my lights are on and off (Send a State when change).

## Debug Info
zigbee2mqtt version: latest release
CC1352P firmware version: latest firmware

**Comment by Koenkk** [comment]
For this you need to enable the report feature: https://www.zigbee2mqtt.io/information/report.html

**Comment by R-Rosenow** [comment]
Thank you! Exactly what I searching for.
