### ISSUE TITLE
Xiaomi MiJia light intensity sensor has float for battery

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3024]
```
zigbee2mqtt:info  2020-02-28 15:53:45: MQTT publish: topic 'zigbee2mqtt/bedroom/light_sensor', payload '{"battery":"100.00","voltage":3200,"linkquality":60,
"illuminance":10414,"illuminance_lux":10}'
```

All my devices with battery report `0-100` but this one reports a float? `100.00`, seems a bit odd.

**Comment by Koenkk** [comment]
Fixed in latest dev branch, the battery was reported as a string instead of a number for some devices. Thanks!
