### ISSUE TITLE
Source routing coordinator with more than 5 direct children

### ISSUE THREAD

**Issue by mr2c12** [Koenkk/zigbee2mqtt#3025]
Coordinator: cc2530+cc2591
Fw: info  2020-02-26 19:42:08: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}'
Flashed fw with sourcerouting.

![graph](https://user-images.githubusercontent.com/2518332/75605478-7d086680-5ae3-11ea-8623-3ef2d026f567.png)

Given the network map above, it seems to me that my coordinator has more children than expected.
Is it correct?
From the fw readme, I read that my coordinator flashed with source routing should have only 5 direct connections. How can I verify this?
Is it possibile that something went wrong when flashing the firmware? I used to have the same version/release but without source routing. When z2m starts, the firmware version logged seems the same to me.

**Comment by Koenkk** [comment]
I think the LQIs of 0 and 1 indicate there is not direct connection.

**Comment by mr2c12** [comment]
Good to know!
Thanks!
