### ISSUE TITLE
[Question] How do I pair the Modkam.ru / DIYRuZ 20 button remote?

### ISSUE THREAD

**Issue by Calimerorulez** [Koenkk/zigbee2mqtt#3039]
First of all sorry for opening an issue (it is more a question). I can't seen to find the answer anywhere :(

I see that the DIYRuZ 20 button remote (https://modkam.ru/?p=1114) is supported by zigbee2mqtt, and I built two of them, but I can't seem to pair it with my network.

Does anyone knows the button combination to pair the device?

Thanks in advance.

**Comment by mo6zes** [comment]
Did you get it to work? I am facing the same issue

**Comment by Calimerorulez** [comment]
@mo6zes Well, I managed to get it to work by using my Zigbee 1.2 USB stick. With my 3.0 coordinator it does not work.

You will have to press and hold key number 17 (that is what the file name of the firmware says), until the led starts to flash. Then release the button and press it again shortly...
