### ISSUE TITLE
Add support for Icasa ICZB-R11D.

### ISSUE THREAD

**Issue by filoor** [Koenkk/zigbee2mqtt#3042]
Please add support for 
Icasa ICZB-R11D.

	{
        zigbeeModel: ['ICZB-R11D'],
        model: 'ICZB-R11D',
        vendor: 'iCasa',
        description: 'ZigBee AC dimmer',
        extend: generic.light_onoff_brightness,
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await configureReporting.onOff(endpoint);
        },
    },`

**Comment by Koenkk** [comment]
added, thanks!

**Comment by filoor** [comment]
Thank you
