### ISSUE TITLE
Availability for battery powered devices

### ISSUE THREAD

**Issue by twsI** [Koenkk/zigbee2mqtt#3066]
https://www.zigbee2mqtt.io/information/availability.html states, that this only includes non-battery powered devices. I know, this puts a lot of traffic on the network and might drain the battery, but I'd love to enable this for battery powered devices as well, just with different and slightly higher intervalls. What do you guys think of two separated values?

**Comment by sjorge** [comment]
It actually sort of works with battery devices for a few months now.

It works under the assumtion that these devices will check in ~1x every 24h to send a battery state update. https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/extension/deviceAvailability.js#L83

**Comment by Koenkk** [comment]
This is already implemented, I've updated to docs a bit to be more clear about this.
