### ISSUE TITLE
Please add support for Philips Hue 1744630P7 (and others?)

### ISSUE THREAD

**Issue by misteriks** [Koenkk/zigbee2mqtt#3072]
There are a few different Philips Hue outdoor Fuzo light models
Currently only [1744530P7](https://www2.meethue.com/nl-nl/p/hue-white-fuzo-buitenlamp-op-sokkel/1744530P7) is supported bij zigbee2mqtt.

I bought the [1744630P7](https://www2.meethue.com/nl-nl/p/hue-white-fuzo-buitenlamp-op-sokkel/1744630P7) and changed the entry in devices.js to this to support it:

Can you add this to z2m to support it out of the box?
{
        zigbeeModel: ['1744530P7','1744630P7'],
        model: '8718696170625',
        vendor: 'Philips',
        description: 'Hue Fuzo outdoor wall light',
        extend: hue.light_onoff_brightness,
},

Philips mentions the model numbers in the URLs
Others Fuzo models that are available are: 
[1744430P7](https://www2.meethue.com/nl-nl/p/hue-white-fuzo-buitenlamp-op-sokkel/1744430P7)
[1744730P7](https://www2.meethue.com/nl-nl/p/hue-white-fuzo-sokkellamp/1744730P7)

**Comment by Koenkk** [comment]
Added all the 3 models, will be supported in the latest dev branch in a few hours.
