### ISSUE TITLE
New auto discovery message after rename device

### ISSUE THREAD

**Issue by svrooij** [Koenkk/zigbee2mqtt#3086]
# Bug Report

This isn't a bug report but I think it's a feature request.

## What happened

1. Device renamed with publish to `zigbee2mqtt/bridge/config/rename_last`
2. No new auto discovery message

## What did you expect to happen

A new auto discovery message, since the topics for this device changed, there needs to come an updated home assistant auto discovery message. So all apps using the auto discovery know the new topics.

## How to reproduce it (minimal and precise)

1. Subscribe to `homeassistant/#`
2. Add new device (for `rename_last` to work).
2. Rename a device by sending `new_name` to `zigbee2mqtt/bridge/config/rename_last`

## Debug Info
zigbee2mqtt version: 1.11.0
CC253X firmware version: latest

**Comment by sjorge** [comment]
This is fixed in the latest dev version I think:
https://github.com/Koenkk/zigbee2mqtt/commit/67b4bcf81550a2c6e87f8fe46d48ba913294738d

**Comment by svrooij** [comment]
Any idea when this will be in production?

I was testing my new diyhue integration and noticed this.

**Comment by sjorge** [comment]
@svrooij not sure, it depends on when @Koenkk does another release  Iguess.

**Comment by sjorge** [comment]
Not sure if you are using docker or not... but:
https://hub.docker.com/layers/koenkk/zigbee2mqtt/latest-dev/images/sha256-7c1219cc27d50e78c49b4813cf407727f46dd378433ed1c0a2ea495b4f8d1ad9?context=explore

Should have the fix, or if you are running it manually installed you can just switch to the dev branch and run npm ci again before restarting.

**Comment by svrooij** [comment]
I’ll try to change to dev tomorrow, thank for the help!!
