### ISSUE TITLE
New Paulmann device 939.99

### ISSUE THREAD

**Issue by RudmerBouwman** [Koenkk/zigbee2mqtt#3087]
Can someone add a paulmann device with partnumber 939.99?
It has the same functionality as a 500.48 but then for outdoor use.

I want to control this device in Home assistant. Already controling two 500.48 devices with succes.

**Comment by Koenkk** [comment]
Can you share your `datavase.db`?

**Comment by RudmerBouwman** [comment]
Without any actions (1 hour later) it showed up in MQTT integrations as [SmartHome Zigbee Dimmer or LED-stripe (50044/50045)]. I'm now able to control these lights as well so I will close now.

**Comment by julian2701** [comment]
@RudmerBouwman: Can you tell how you managed to pair Paulmann 939.99? Tried factory reset many times without success...
