### ISSUE TITLE
Xiaomi Relais Module LLKZMK11LM

### ISSUE THREAD

**Issue by chrneu122** [Koenkk/zigbee2mqtt#3094]
Hello, 

I have a proplem with the LLKZMK11LM Relais Module. 

There are no States in the Io Broker for the two switches only for the state of the Relais. 

Is it possible to use the divice with push button or only with switches ?

**Comment by Koenkk** [comment]
Please create IObroker issues here: https://github.com/ioBroker/ioBroker.zigbee/issues
