### ISSUE TITLE
Coordinator replacement

### ISSUE THREAD

**Issue by Markus1970** [Koenkk/zigbee2mqtt#3099]
Hi,

I have repalced my coorodinator with a new one ofthe same type. All devices are partial working but some of them don't report few status message. Saw in another post that thiscould be a result of the changed mAC Adress of the coordinator. So how can I check which MACadress has the the coordinator now and where needi to chnage it? Only in the database?

Found the issue... Repeater bewteen was not working correctly, repaiered and now it seesm to be fine.

Thanks

markus

**Comment by turboproc** [comment]
Hi,

indeed you should be able to find this in the database. To solve this, you could first try to reconfigure the device. If that doesn;t help, remove the device and pair it again.
