### ISSUE TITLE
modelId

### ISSUE THREAD

**Issue by MaxRei-dev** [Koenkk/zigbee2mqtt#3103]
Hi,
running 1.11.0. 
Can somone confirm that there is no modelId in the json ?
thanks

**Comment by MaxRei-dev** [comment]
I mean when a device is reporting..
Thanks

**Comment by MaxRei-dev** [comment]
no one ?

**Comment by sjorge** [comment]
I don't think there every was, aside from in the output published to `zigee2mqtt/bridge/devices`

**Comment by MaxRei-dev** [comment]
thanks. i can confirm that it was in older versions but not now. but anyways i will do things different. (i was using this to group the battery level of devices. eg lumi.sens, lumi.sensor_smoke,... and the react different to baettery level. eg. Smoke sensor -> acoustic alarm so i dont forget to change the battery, Motion sensor -> just an push notification and so on)
