### ISSUE TITLE
xiaomi vacuum cleaner gen 1

### ISSUE THREAD

**Issue by Riseryn** [Koenkk/zigbee2mqtt#3114]
Hello,
I have installed zigbee2mqtt and mosquitto.
I don't use home assistant.
I have an Ikea tradfri outlet that i can succesfully manage with zigbee2mqtt.
I also have a xiaomi rockrobo gen 1 but i can't find a way to use it with zigbee2mqtt.
Does someone can help me ?
Thanks
# Bug Report
## What happened
Impossible to connect to zigbee2mqtt
## What did you expect to happen
control the vacuum by mqtt
## Debug Info
zigbee2mqtt version: latest
CC253X firmware version: don't know how to find it

**Comment by MaxRei-dev** [comment]
Hi,
the Vacuum is WLAN based. You could use Valetudo or for example nodered to control it via mqtt.
Greets max

**Comment by Riseryn** [comment]
Hi 
I have valetudo re installed. But i can't find a clue about how to use mqtt with it.
Do you know where i can find informations about it, my google search does'nt  give me any result i can use( or understand)
thanks

**Comment by Koenkk** [comment]
Closing as this is not related to Zigbee2mqtt
