### ISSUE TITLE
Failed to interview

### ISSUE THREAD

**Issue by ressof** [Koenkk/zigbee2mqtt#3119]
# Bug Report
## What happened
Failed to interview
## Debug Info
zigbee2mqtt version: 1.11.0
CC253X firmware version:20190608

[https://pastebin.com/UknfTd72](url)

**Comment by vaceslav** [comment]
please provide more information.

Which device did you try to connect? Manufacturer?  Model?

**Comment by ressof** [comment]
It is a bulb from IKEA, LED1624G9

**Comment by vaceslav** [comment]
Did you follow instruction from docu page?
https://www.zigbee2mqtt.io/devices/LED1624G9.html

> While pairing, keep the bulb close the the CC2531 USB sniffer.
>
> What works is to use (very) short “on’s” and a little bit longer “off’s”. Start with bulb on, then off, and then 6 “on’s”, where you kill the light as soon as the bulb shows signs of turning on.

**Comment by ressof** [comment]
Yes
