### ISSUE TITLE
[Q] Distinguish switch events for relays

### ISSUE THREAD

**Issue by Sineos** [Koenkk/zigbee2mqtt#3126]
Is there any way to distinguish between "manual" switch events, e.g. pressing a button and "programmatic" switch events, e.g. sending state on, for relay / switch devices like https://www.zigbee2mqtt.io/devices/404021.html?

**Comment by Koenkk** [comment]
From the resulting payload you cannot detect this, however it can be known that right before a `zigbee2mqtt/DEVICE_ID/set` was send.

**Comment by Sineos** [comment]
Thanks. 👍
