### ISSUE TITLE
Device (Embertec power meter) leave the network

### ISSUE THREAD

**Issue by Melvictsa** [Koenkk/zigbee2mqtt#3129]
Hello,
I have a Embertec 4 channel power meter and when I try to pair it, it initially pair according to the log but in the end it leave the network again.
The configuration if the devices,js script:
 //EmberMeter
    {
        zigbeeModel: ['EMAU-ZN04-HA-01'], 
        model: 'EMAU-ZN04-HA-01',
        vendor: 'Embertec',
        description: 'Embermeter', 
        supports: 'power measurement',
        fromZigbee: [fz.metering_power], 
        toZigbee: [],
    },

Debug log:
https://hastebin.com/wayokadowa.coffeescript

Any pointers would be most welcome.

**Comment by Koenkk** [comment]
I've also seen this behaviour for other devices, after sniffing the traffic with the original gateway it appears that you need to send some "magic" payload in order for these devices to stay in the network. (https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/index.js#L39)

You would need to sniff the traffic when pairing it with the original gateway to figure this out.

**Comment by Melvictsa** [comment]
I eventually came round to this again, it took a while to get the sniffer.

[Emberpulse trace 20230601.zip](https://github.com/Koenkk/zigbee2mqtt/files/11645095/Emberpulse.trace.20230601.zip)

The Rejoin Request is at line 405.

Is there perhaps one device that I can modify to get this working?

Any help is much appreciated.
