### ISSUE TITLE
how to "analyze" health of network

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#3132]
# Bug Report
## What happened
I have quite some devices, al lot of (battery powered) sensors.
Sometimes I get some unexpected behaviour, I suspect my zigbee mesh that is mes(h)sing things up.
The only way I get some grip on the network is to take a look at 
zigbee_networkmap
![15-03-2020 13-08-09](https://user-images.githubusercontent.com/10470708/76701122-7fabb400-66be-11ea-8271-5b1a8091dec7.png)

or
Z2MA map
![15-03-2020 13-12-41](https://user-images.githubusercontent.com/10470708/76701143-b681ca00-66be-11ea-9346-71fb353e9c13.png)

The problem with both interfaces is 
- not searchable
- only for "nice" graphics, as @Koenkk mentioned somewhere

## What would you like to happen
some tool/interface/log where I could do some analysis

## Debug Info
RPI 3
CC2531 usb stick
hass.io

```
Hostname | HASSIO
System | HassOS 3.12
Deployment | production
```

Zigbee2mqtt Hass.io Add-on
```
info  2020-03-15 13:17:11: Logging to console and directory: '/share/zigbee2mqtt/log/2020-03-15.13-17-11' filename: log.txt
info  2020-03-15 13:17:13: Starting zigbee2mqtt version 1.11.0 (commit #unknown)
info  2020-03-15 13:17:13: Starting zigbee-herdsman...
info  2020-03-15 13:17:15: zigbee-herdsman started
info  2020-03-15 13:17:15: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
```

**Comment by carldebilly** [comment]
@bartplessers I'll be happy to implement a way to better represent the health of a network in Z2MA... :-)

You have more specific suggestions?

**Comment by bartplessers** [comment]
Well, an easy one could be
https://github.com/yllibed/Zigbee2MqttAssistant/issues/219

a sortable and searchable table, like
![76030637-65dbd580-5f36-11ea-8d92-a199804d45d1](https://user-images.githubusercontent.com/10470708/77202983-abc89a00-6aef-11ea-890a-565701ad58d0.png)

Maybe a possibility to add/remove columns?
At least I would like to have
  - name
  - friendly name
  - brand
  - last seen
  - battery
  - linkquality

**Comment by bartplessers** [comment]
Maybe it's possible to have a field to distinguish the "orphaned" items? 
![20-03-2020 21-25-01](https://user-images.githubusercontent.com/10470708/77203710-6311e080-6af1-11ea-9304-faffb22adfc6.png)

**Comment by bartplessers** [comment]
Maybe also a "clickable" map:
- You can click on an entity
- you will be redirected to the "datatables" view, filtered on the selected item
![20-03-2020 21-33-38](https://user-images.githubusercontent.com/10470708/77204283-ae78be80-6af2-11ea-89af-ff61de1a9c78.png)

**Comment by bartplessers** [comment]
a searchable map?
a dynamic search field where items will be highlighted if they match the search term?

**Comment by bartplessers** [comment]
VERY usefull: a dynamic searchfilter on the logfile.
The zigbee2mqtt log contains a lot of lines.
It would be great to enter a searchterm (ID, "error", etc...) and to see only the lines that match the searchterm
