### ISSUE TITLE
How to get device ‘vendor’ and ‘description’ ?

### ISSUE THREAD

**Issue by Westcott1** [Koenkk/zigbee2mqtt#3133]
When z2m starts, or a new device is added, its ‘description’ and ‘vendor’ are included in the log message.
Is it possible to get this information later on? The topic ‘zigbee2mqtt/bridge/config/devices/get’ does not return it.
Thanks!

**Comment by Koenkk** [comment]
Added to `zigbee2mqtt/bridge/config/devices` in the latest dev branch. thanks!
