### ISSUE TITLE
Missing the Toggle command for the Xiaomi LLKZMK11LM relay

### ISSUE THREAD

**Issue by artem-dudarev** [Koenkk/zigbee2mqtt#3138]
## Feature Request
Currently, the [Xiaomi LLKZMK11LM](https://www.zigbee2mqtt.io/devices/LLKZMK11LM.html) relay in zigbee2mqtt has only On and Off commands, while it supports the Toggle command as well.

Here is the command that Mi Home application sends to the relay (captured with ZBOSS Sniffer):
```
ZigBee Application Support Layer Data, Dst Endpt: 2, Src Endpt: 1
    Frame Control Field: Data (0x40)
    Destination Endpoint: 2
    Cluster: On/Off (0x0006)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 219
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
    Sequence Number: 6
    Command: Toggle (0x02)

0000   40 02 06 00 04 01 01 db 01 06 02
```
Please add the Toggle command to zigbee2mqtt.

## Debug Info
zigbee2mqtt version: 1.11.0

**Comment by Koenkk** [comment]
This is already supported, send `zigbee2mqtt/FRIENDLY_NAME/set` payload `{"state": "TOGGLE"}`
