### ISSUE TITLE
CPU locked in C2 package state

### ISSUE THREAD

**Issue by Bojan023** [Koenkk/zigbee2mqtt#3140]
# Bug Report
## What happened
CPU package can't reach lower C-states than C2 by running a Z2M container. CPU Cores are able to reach C7. My 14 other Docker containers, like HA, don't prevent package C-state to stay in C2.

## What did you expect to happen
CPU package to reach lower C-state than C2 with Z2M container running.
## How to reproduce it (minimal and precise)
Spin up Z2M Docker container and use Powertop to monitor CPU C-states

## Debug Info
zigbee2mqtt version: Docker, 1.11.0
**CC1352P-2** firmware version: CC1352P_2_20191106

**Comment by Bojan023** [comment]
It has been a while that I’ve opened this ticket and investigated the issue. As far as I know, newer versions of Z2M have not influenced this behaviour significantly. However, my CPU Package does reach lower C States than C2 (not as much as I’d like to see). Meanwhile, my setup has changed so I cannot ensure that Z2M still contributes to the problem or is the root cause.

`PowerTOP 2.15     Overview   Idle stats   Frequency stats   Device stats   T


           Pkg(HW)  |            Core(HW) |            CPU(OS) 0
                    |                     | C0 active   1.3%
                    |                     | POLL        0.0%    0.0 ms
                    |                     | C1          0.1%    0.1 ms
C2 (pc2)   46.1%    |                     |
C3 (pc3)    0.6%    | C3 (cc3)    0.1%    | C3          0.2%    0.1 ms
C6 (pc6)   39.1%    | C6 (cc6)    2.6%    | C6          2.9%    0.6 ms
C7 (pc7)    0.0%    | C7 (cc7)   91.8%    | C7s         0.1%    1.4 ms
C8 (pc8)    0.0%    |                     | C8          5.4%    1.0 ms
C9 (pc9)    0.0%    |                     | C9          0.6%    6.7 ms
C10 (pc10)  0.0%    |                     |
                    |                     | C10        86.5%   11.7 ms
                    |                     | C1E         0.5%    0.1 ms

                    |            Core(HW) |            CPU(OS) 1
                    |                     | C0 active   1.2%
                    |                     | POLL        0.0%    0.0 ms
                    |                     | C1          0.1%    0.1 ms
                    |                     |
                    | C3 (cc3)    0.1%    | C3          0.2%    0.1 ms
                    | C6 (cc6)    4.0%    | C6          4.4%    0.6 ms
                    | C7 (cc7)   90.4%    | C7s         0.0%    1.2 ms
                    |                     | C8          7.5%    1.0 ms
                    |                     | C9          0.1%    3.6 ms
                    |                     |
                    |                     | C10        83.7%   10.3 ms
                    |                     | C1E         0.7%    0.2 ms

                    |            Core(HW) |            CPU(OS) 2
                    |                     | C0 active   0.9%
                    |                     | POLL        0.0%    0.0 ms
                    |                     | C1          0.1%    0.1 ms

<ESC> Exit | <TAB> / <Shift + TAB> Navigate |                               
`

**Comment by popy2k14** [comment]
@Bojan023 thx for your answer.
I will also test it and give feedback here.

Than we can decide to reopen the issue or create a new one.

**Comment by popy2k14** [comment]
@Bojan023 I have tested Z2M with an usb connected "SONOFF Zigbee 3.0 USB Dongle Plus,TI CC2652P + CP2102(N)" stick.
On unraid i have used the newest docker template and have passed the stick to the container.

After issues with the "channel" which brought my network down (because i am an idiot and forgot to merge the channel setting), the network was up and running.

Also in my case it just reached C2 with Z2M running in this configuration.
After stopping the Z2M container it immediately reached C8 again with a high percentage.

So i can confirm the issue!

How we proceed?
I have some ideas:

- open a new issue
- maybe it's an usb-serial issue that prevents reaching higher C states!?
  Do you have an ethernet zigbee stick to test?

It would be so nice to have also HA + Z2M dockerized to my i3 unraid and ditch my Dell Wyse HA box.
Let me know your thoughts.

**Comment by popy2k14** [comment]
@Bojan023 I think that issue is not related to Z2M.
It seems an Intel issue, see here and the linked threads: https://community.intel.com/t5/Processors/High-power-consumption-when-using-USB1-1-serial-devices-under/td-p/1516435

It's so sad that that this issue is not fixed. 
It also happens up to gen 14.

Any ideas how to solve this

**Comment by popy2k14** [comment]
So to sum it up.
I have migrated (cloned IEEE) my zigbee network (132 devices) from the sonoff to an SLZB-06 (which has the same zigbee frontend CC2652P and an PoE ethernet port) flawlessly.

The CPU now reaches C8 again!

So yes, this is a workaround and Intel has an serious USB issue there!

Here are the stats with running Z2M conrainer + SLZB-06 (PoE):

![image](https://github.com/user-attachments/assets/3d303135-0474-4b19-8a44-65d221232a69)

**Comment by popy2k14** [comment]
Sadly i think thats an intel architecture issue which we cant solve.
The only workaround seems to be an network coordinator.

**Comment by Wireheadbe** [comment]
> [@Bojan023](https://github.com/Bojan023) I think that issue is not related to Z2M. It seems an Intel issue, see here and the linked threads: https://community.intel.com/t5/Processors/High-power-consumption-when-using-USB1-1-serial-devices-under/td-p/1516435 Ok, here is another thread (and my post) in the unraid forum: https://forums.unraid.net/topic/149579-sonoff-zigbee-usb-dongle-and-power-consumption/?do=findComment&comment=1466762 In this thread you can follow what i have already tried.
> 
> It's so sad that that this issue is not fixed. It also happens up to gen 14.
> 
> Any ideas how to solve this?

Actually, for this specific reason, I've done some testing:

-LAUNCHXL-CC26X2R1
-Disconnected the CC2652R chip from it's debugger, and wired in a..
-FT232**H** Single HS USB-UART/FIFO IC - which is _not_ a full speed USB1 device, but a proper high-speed device: Class=Vendor Specific Class, Driver=ftdi_sio, **480M** - note the "H" - it's really a USB Hi-Speed 480Mbps device instead, to which the Intel Errata does not apply.
-I have other devices I also replaced with this serial chip, because of that specific Intel bug (P1 logger, Radioactivity logger - all serial based), and they do not cause my system to cling to C2-state.
-**However** - the moment I launch Zigbee2MQTT - I get locked in the C2 state.

**Comment by popy2k14** [comment]
@Wireheadbe thx for testing this out!
So it's not hardware related and seems to be triggered by Z2M...

**Comment by Wireheadbe** [comment]
I think @Koenkk needs to file a bug report upstream to Node Serialport.. 

I wrote a simple example that opens your serial port using Node.js and https://serialport.io/docs/api-serialport (exactly what zigbee-herdsman is using). 


```
// index.js
import { SerialPort } from 'serialport';
import { ReadlineParser } from '@serialport/parser-readline';

// Create and open the serial port
const port = new SerialPort({
  path: '/dev/ttyZH',
  baudRate: 115200,
});

// Set up a parser to split data by newline (optional, you can also just listen to raw data)
const parser = port.pipe(new ReadlineParser({ delimiter: '\n' }));

// Handle raw binary data (without parser)
// port.on('data', (data) => {
//   console.log('Raw data:', data.toString());
// });

// Handle line-delimited text (with parser)
parser.on('data', (line) => {
  console.log('Received:', line);
});

// Handle errors
port.on('error', (err) => {
  console.error('Error: ', err.message);
});

// Confirm open
port.on('open', () => {
  console.log('Serial port opened on /dev/ttyZH at 115200 baud');
});

```

The moment I launch this, my CPU gets stuck in C2 state.

However - I have other script, using such a FT232H chip (not affected by that Intel Bug) - and using a simple pyserial nonblocking readline:
```
# Non-blocking readline - see https://github.com/pyserial/pyserial/issues/216
class ReadLine:
    def __init__(self, s):
        self.buf = bytearray()
        self.s = s
    
    def readline(self):
        i = self.buf.find(b"\n")
        if i >= 0:
            r = self.buf[:i+1]
            self.buf = self.buf[i+1:]
            return r
        while True:
            i = max(1, min(2048, self.s.in_waiting))
            data = self.s.read(i)
            i = data.find(b"\n")
            if i >= 0:
                r = self.buf + data[:i+1]
                self.buf[0:] = data[i+1:]
                return r
            else:
                self.buf.extend(data)
```
... and that one **does not** lock the CPU into C2 state.

**Comment by Wireheadbe** [comment]
Actually - scratch that last part. Even with pyserial elevated C state to some extent.

Bottomline: Intel 13th, 14th gen,... using any of: 600 / 700 / 800 series PCH all have the issue with the most basic USB devices:
600 series - item 13: [Errata list](https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/intel-600-series-chipset-family-platform-controller-hub-pch-specification-upd/003/errata-summary-table/#EST)  
  
700 series - item 11: [Errata list](https://edc.intel.com/content/www/us/en/design/products-and-solutions/700-series-chipset-family-platform-controller-hub-pch-specification-upd/errata-summary-table/#EST)  
  
800 series - item 01: [Errata list](https://edc.intel.com/content/www/us/en/design/products/platforms/details/arrow-lake-s/800-series-chipset-family-platform-controller-hub-pch-specification-upd/errata-details/#](https://edc.intel.com/content/www/us/en/design/products/platforms/details/arrow-lake-s/800-series-chipset-family-platform-controller-hub-pch-specification-upd/errata-details/))

So avoid these intel systems if you value low power 👎🏻
