### ISSUE TITLE
How to use zigbee2mqtt/[ieee_addr]/get , and Question on how to handle data.

### ISSUE THREAD

**Issue by adelwyr** [Koenkk/zigbee2mqtt#3141]
Hello,
1- I have read the [https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html](url) , but am confused how to use /get for a device , I publish a request to the address ('zigbee2mqtt/[ieee_addr]/get') with payload {"state": "" } (JSON), then where do I receive the data? (which topic should i listen to?).

2- Am building a paho python to handle the data recived from zigbee2mqtt. Currently my system is 
 
 zigbee2mqtt -> mosquito -> paho.mqtt.

Should I create one python file to listen to all topics and as well have functions inside of it to publish the necessary functionality for my application when needed?

Would like to know if you have any idea on how to handle the data.

**Comment by Koenkk** [comment]
1. You have to listen to `'zigbee2mqtt/[ieee_addr]`
2. It's totally up to you to design this :smile:
