### ISSUE TITLE
[help] SD Card dead

### ISSUE THREAD

**Issue by Kepro** [Koenkk/zigbee2mqtt#3142]
my SD card died I recover the only configuration.yaml but it will not recover devices :/ 

I don't want to repair all 20 devices :/ any idea how to do it? all I know that they need to be in database file but... 

zigbee2mqtt:info  2020-03-17 20:06:02: Currently 0 devices are joined:

**Comment by Koenkk** [comment]
If you don't have your `database.db` anymore you need to repair your devices.
