### ISSUE TITLE
Unable to pair ZNCZ02LM (Mi power plug)

### ISSUE THREAD

**Issue by ned-kelly** [Koenkk/zigbee2mqtt#3149]
Hi Guys,

I've tried several times to pair two different ZNCZ02LM's without any luck...

* Running the latest zigbee2mqtt docker build & firmware on my sniffer
* Have tried dev builds without any luck
* Can pair other Mi devices that are battery operated, however there's no luck pairing both the smart plugs and smart bulbs that are connected to 240v mains.

Does anyone have any suggestions?

**Comment by Koenkk** [comment]
Make sure to check https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair
