### ISSUE TITLE
Xiaomi Floras keep dropping connection

### ISSUE THREAD

**Issue by Routout** [Koenkk/zigbee2mqtt#3160]
I have cc2531 with 20190608 firmware using it on Hassio and zigbee2mqtt 1.11. Xiaomi Floras (5) connection drops after a while. 
Everything else seem to be working well, Ikea outlets and xiaomi movement and temperature sensors.
Is the older firmware available somewhere? I'm not sure if this started after I upgraded the firmware a while ago.

**Comment by Koenkk** [comment]
Xioami Floras are Bluetooth devices (???)

**Comment by Routout** [comment]
Damn, so they are,  sorry :D
