### ISSUE TITLE
Zigbee2MQTT keeps restarting if stick is not found

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#3166]
# Bug Report
## What happened
Zigbee2MQTT keeps restarting if stick is not found

```
zigbee2mqtt:error 2020-03-20 21:48:17: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-03-20 21:48:17: Failed to start zigbee
zigbee2mqtt:error 2020-03-20 21:48:17: Exiting...
zigbee2mqtt:error 2020-03-20 21:48:17: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
```

## What did you expect to happen
no attempt to start again after x (like 3) failures

**Comment by Koenkk** [comment]
Is this with Docker and the `--restart always` flag?

**Comment by bartplessers** [comment]
Its 
- rpi, buster
- docker
- hass.io in docker
- zigbee2mqtt addon in hass.io

I didn't configure anything in docker, all by GUI in hass.io

**Comment by Koenkk** [comment]
Zigbee2mqtt has no knowledge on how many times it has been started, I feel it's the responsibility of the supervisor to stop restarting a service once it fails to start after X times.

**Comment by bartplessers** [comment]
ok, fair enough
