### ISSUE TITLE
friendly_name including # char causes disconnects from mqtt server

### ISSUE THREAD

**Issue by JasperAlgra** [Koenkk/zigbee2mqtt#3175]
# Bug Report
## What happened
I found out that using hashtags in the `friendly_name` of device in configuration.yaml causes strange behaviour of zigbee2mqtt including dis/reconnect to the MQTT server.

Example from configuration.yaml
```
  '0x000d6ffffe19412f':
#    friendly_name: 'gu10 dimable white spectrum #1'
    friendly_name: '0x000d6ffffe19412f'
```

In my case I've got a bulb and a remote. When I push a button on the remote zigbee2mqtt breaks and resets the connection to the MQTT server (maybe more, I cannot see in the debug log).

## How to reproduce it (minimal and precise)
add a `friendly_name` with a hashtag in it. Press a button on the remote or trigger an action through Home Assistant.

## Debug Info
zigbee2mqtt version: 1.12.0 (commit #840b9d9
CC253X firmware version: default

# Logs:
With errors:
https://hastebin.com/sutavuxiba.pl
Without errors:
https://hastebin.com/owihifojot.apache

**Comment by Koenkk** [comment]
MQTT doesn't allow wildcards (`+`/`#`) to be used in topic names.

> Publishers are not allowed to use the wildcard characters in their topic names.

Source: https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/wildcard.html

Latest zigbee2mqtt dev refuses to start when this is set. Thanks!

**Comment by Girbie** [comment]
@JasperAlgra : I'm facing the same issue now. How did you resolve it? zigbee2mqtt doesn't start anymore and I can't access/change the device name.

**Comment by aro-git** [comment]
I'm facing the same issue right now. I named my device with fancy name with UTF-8 characters and slash (czujnik otwarcia / zamknięcia 3b - drzwi wiatrołap) and now I can't rollback it. I can't rename device and I can't access/change the device name (503: Service Unaviable).

**Comment by Koenkk** [comment]
@aro-git I've tried and it works fine in my case:

![image](https://user-images.githubusercontent.com/2892853/96374071-ca1f7280-1170-11eb-821d-eee10d249551.png)

You can always stop zigbee2qmtt, change the name in the configuration.yaml.

**Comment by aro-git** [comment]
Many thanks for instant reply.
I tried and changed this particular friendly name in devices.yaml file.
I very appreciate your fine work.
Greetings.
