### ISSUE TITLE
hue tap 

### ISSUE THREAD

**Issue by rmalchow** [Koenkk/zigbee2mqtt#3179]
hi,

i have two hue taps here that i love a lot. however, i can't pair them. so ... they're not in "the list", so i have tried to pair them anyway to figure out if / how i can help supporting them. pairing them with the "old" philips bridge (with hue essentials) works just fine, pressing the "four dots" button for ten seconds, then releasing it and pressing it again briefly. 

now i have turned up the logging on z2m ... and tried many, many times ... and yet i don't see anything in the log. my compose file:
```
 zigbee:
   image: koenkk/zigbee2mqtt
   restart: always
   privileged: true
   environment:
    - TZ=Europe/Berlin 
    - DEBUG=*
   volumes:
   - /run/udev:/run/udev:ro
   - /dev/ttyACM0:/dev/ttyACM0
   - ${home}/data:/app/data
```
should i bother? what am i looking for? what am i missing? do you take bribes?

**Comment by Koenkk** [comment]
The hue tap is a Zigbee green power device which is currently not supported. It's being worked on in https://github.com/Koenkk/zigbee-herdsman/issues/22 so please keep an eye on that.
