### ISSUE TITLE
Error reusing panId

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#318]
I've been trying to fix the PAN ID in configuration.yaml.
It was done automatically before, I looked in the log (I'm running the daemon in debug) and set up pan_id to `0x1a63`.
I restarted the daemon, I was expecting to use `panId=0x1a63`, => it uses `0x1a62`.
weird.

If I set pan_id to :0x1000 it uses 0x1000, but for some reason,  I can't use 0x1a63, neither can't I use 0x1a62 that was used by cc2530 before I swapped it for a cc2531.

Any reason for this ?

DEBUG=* npm start doesn't give any hint:

```
zigbee2mqtt:debug 2018-8-30 17:22:30 Using zigbee-shepherd with settings: '{"net":{"panId":6755,"channelList":[11]},"dbPath":"/home/pi/zigbee2mqtt/data/database.db","sp":{"baudRate":115200,"rtscts":false}}'
Thu, 30 Aug 2018 15:22:39 GMT zigbee-shepherd:init  >> PanId:      0x1a64
Thu, 30 Aug 2018 15:22:39 GMT zigbee-shepherd:init  >> Ext. PanId: 0xdddddddddddddddd
```

**Comment by lolorc** [comment]
there's really something very weird going on, I've just upgraded zigbee2mqtt, started it but forgot to copy my configuration.yaml back. stopped it, copied back correct configuration.yaml with my specified panid. It now selects panid+1.
I know have to either repair every sensors or find a way to make it use the panid I specified...
gonna try to restart it without any router running, if I flash my firmware again I'll have to repair everything anyway.

**Comment by Koenkk** [comment]
I've experienced the same issue, when choosing a different channel it works. 

My guess is that it's due to a zigbee network already existing with the same channel and panid.

**Comment by lolorc** [comment]
@Koenkk yep changing the channel does the trick, but I still don't get my sensors back. I need to repair them.
I think the firmware must be scanning for networks when powered on, and then refuses to use existing one. While it could be a good thing, I don't understand why it sometimes refuses to reuse its own network params.

**Comment by lolorc** [comment]
trying to understand, I just started a new network on another channel, just paired 2 osram plugs (router).
then I replaced the coordinator by another cc2531. I had to unplug the osram devices to have the new cc2531 accepting to use the specified panid. Otherwise It uses panid+1.

I already tried to put the cc2531 in tin foil so that it doesn't detect devices with the selected channel/panid. I guess I'll have to do that again with better shielding.
I might also try to see if I can disable this detection in the firmware. (haven't looked at compiling my own firmware yet)

**Comment by lolorc** [comment]
would NWK_MANAGER & NV_RESTORE help ?

**Comment by lolorc** [comment]
I managed to re-use my panid:
- reflashed cc2531
- unplugged all router
- put paper towel around cc2531 then a lot of tin foil connected to usb connector to act as a shield
- plugged cc2531/started zigbee2mqtt
=> yeeepeeeee ! good panid ! all devices back ! :-)
