### ISSUE TITLE
Add support for ORVIBO ZIGBEE RGB RL804CZB

### ISSUE THREAD

**Issue by OXOTH1K** [Koenkk/zigbee2mqtt#3183]
Thats work for me:

```
    // Orvibo
    {
        zigbeeModel: ['8643db61de35494d93e72c1289b526a3'],
        model: 'RL804CZB',
        vendor: 'Orvibo',
        description: 'Zigbee LED controller RGB + CCT or RGBW',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
        supports: 'on/off, brightness, color temperature or white, color',
    },
```
Device:
https://secur.ua/rele-pitanija-orvibo-zigbee-rgb-rl804czb.html

**Comment by Koenkk** [comment]
Thanks, will be supported in the dev branch in a few hours.

**Comment by cingolanifede** [comment]
Hi, I have this Orvibo rgb, it have 3 micro-switch and it gives 2 different zigbeemodels,
'e84c3be8030e494d8e29044f50ed45a4' & '6c155b46eb9a4dcbb64fb3dd858aa18e'. I 've added them to device.js, but I can't change the color. Only blue channel is working, i've tested and there is no mosfet burned. @OXOTH1K did you have this problem? Is there any kind of config to modify? thanks

**Comment by OXOTH1K** [comment]
> Hi, I have this Orvibo rgb, it have 3 micro-switch and it gives 2 different zigbeemodels,
> 'e84c3be8030e494d8e29044f50ed45a4' & '6c155b46eb9a4dcbb64fb3dd858aa18e'. I 've added them to device.js, but I can't change the color. Only blue channel is working, i've tested and there is no mosfet burned. @OXOTH1K did you have this problem? Is there any kind of config to modify? thanks

I use this device only with white led strip, sorry

**Comment by yuz123** [comment]
> Hi, I have this Orvibo rgb, it have 3 micro-switch and it gives 2 different zigbeemodels, 'e84c3be8030e494d8e29044f50ed45a4' & '6c155b46eb9a4dcbb64fb3dd858aa18e'. I 've added them to device.js, but I can't change the color. Only blue channel is working, i've tested and there is no mosfet burned. @OXOTH1K did you have this problem? Is there any kind of config to modify? thanks

I have the same issue. Did you resolve it?

**Comment by OXOTH1K** [comment]
> Hi @OXOTH1K. Please share your experience about connecting Orvibo RL804CZB. My Zigbee2MQTT does not find this device. Maybe I'm doing something wrong, I just didn't find anything about it on the internet. I apologize for disturbing and offtopic.

Oh, it’s hard to switch in paring mode. I’ll go to find instruction tomorrow.

**Comment by OXOTH1K** [comment]
![6F1D708C-029F-4E36-A212-CDA702AB9607](https://user-images.githubusercontent.com/19778219/154864244-ff10f9da-fdf3-4c7a-a16b-3bd68a04544c.jpeg)

**Comment by lxndrrl** [comment]
@OXOTH1K Thank you very much.

**Comment by tjunussov** [comment]
I have CC10ZW ( looks same as RL804CZB ) I successfully paired, and connected Warm+Cold White Led Strip to the W1 and W2 accordingly, but only Warm Channel is working, i could change brightness and turn on/off,, If i switch to Cool Channel nothing happens, no errors, only warm channel keeps on
