### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by geeano** [Koenkk/zigbee2mqtt#3188]
Dear Koen,

I faced a serious number of issues after upgrading of the latest Domoticz version yesterday.
I finally decided to build up a new system by fresh install of OS and relevant software.
I was able to re-use a backup of my Domoticz database, so all informaton is restored.

My final step in installation of zigbee2mqtt. Is there any precausions ?
Do I have to connect the CC2531 USB before starting the installation or afterwards. 
Is there a risk of repairing. 

Please let me now.

**Comment by Koenkk** [comment]
- Restore everything that was in the `data` directory (`database.db` and `configuration.yaml` are important here)
- Connect CC2531
- Start zigbee2mqtt

Good luck!

**Comment by geeano** [comment]
- disconnect cc2531
-  complete installation zigbee2mqtt
- stop zigbee2mqtt ( I assume ?)
- restore data directory
- connect cc2531
- start zigbee2mqtt

Please conform.
Thanks in advance
