### ISSUE TITLE
Konke

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#3190]
Dombo question..
I run zigbee2mqtt on channel 11
I wil buy some konke 
[https://www.zigbee2mqtt.io/devices/2AJZ4KPBS.html](url)
Only can i change the channel to 15, 20 or 25 without problems?
z2m stop change channel to 20
z2m start?

Or?

**Comment by Koenkk** [comment]
As can be read here: https://www.zigbee2mqtt.io/information/FAQ.html#requires-repairing changing channel requires repairing.
