### ISSUE TITLE
Yale YRD246HA20BP Configuration Not Found in devices.js

### ISSUE THREAD

**Issue by tthk** [Koenkk/zigbee2mqtt#3198]
# Bug Report
## What happened
I have the Yale Assure lock, model YRD246HA20BP.  This is not recognized by zigbee2mqtt eventhough the devices.js seems to have an entry for this model.

## What did you expect to happen
Expect zigbee2mqtt to properly identify and configure lock for HomeAssistant

## How to reproduce it (minimal and precise)
Add lock to zigbee2mqtt.  Lock is added, but not usable. 

## Debug Info
zigbee2mqtt version: 1.12.0
CC253X firmware version: Z-Stack_Home_1.2 (source_routing)

Everything seems to work fine when I changed the zigbeeModel line in:
node_modules/zigbee-herdsman-converters/devices.js:
`
    {
        zigbeeModel: ['YRD226/246 TSDB'],
        model: 'YRD226/246 TSDB',
        vendor: 'Yale',
        description: 'Assure lock',
 ...
`
to:
`
    {
        zigbeeModel: ['YRD246 TSDB'],
        model: 'YRD226/246 TSDB',
        vendor: 'Yale',
        description: 'Assure lock',
...
`
It seems that the intention of the original code was to support both YRD226 and YRD246, but the zigbeeModel:['YRD226/246 TSDB'] did not recognize my YRD246HA200BP lock.  Changing to  zigbeeModel: ['YRD246 TSDB'] recognized my lock.

Would splitting up the entry into two entries, one for YRD226 and one for YRD246 be the correct solution, capable of recognizing both YRD226 and YRD246 locks?  I don't have YRD226 lock to test.

~~I'm not sure if I should report this issue here (Koenkk/zigbee2mqtt) or at the hassio repo I'm using (danielwelch/hassio-zigbee2mqtt)?~~   EDIT: Found that danielwelch/hassio-zigbee2mqtt pulls in this Koenkk/zigbee2mqtt repo, so this is the right place to file this issue.

**Comment by Koenkk** [comment]
Added, thanks. 

Will be supported in the dev branch in a few hours.
