### ISSUE TITLE
Reflash firmware without CCDebugger/Arduino

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee2mqtt#320]
ZNP firmware for cc253* has a built-in bootloader that can be used to updated firmware via USB / UART into the cc2531 stick or simply the cc2530 chip without using CCDebugger or Arduino.

But this requires not a conventional hex-firmware, but a special sbl-firmware (Serial Boot Loader).

For the normal firmware, the process of assembling it is described here https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/CC2531
And for SBL firmware, everything is the same, but the assembly CC2531-ProdSBL (or CC2530) is selected. In this case, not a hex file (680Kb) is generated, but a bin-file (234Kb).
**And with one exception - it is necessary to specify MAKE_CRC_SHDW instead of FAKE_CRC_SHDW defined symbols.**

![prodspl](https://user-images.githubusercontent.com/8360230/44865017-cfb45880-ac89-11e8-9e0b-69f876ca8d5f.PNG)

This firmware must be flashed through SerialBootTool. It comes with IAR, or you can download it separately here http://processors.wiki.ti.com/index.php/File:SerialBootTool_1_3_2.zip

When starting SerialBootTool, you must select Zigbee family. Then select the SBL firmware (bin-file). And then select port and specify the parameters of the port where cc253* is connected.

![serialboottool](https://user-images.githubusercontent.com/8360230/44865037-dfcc3800-ac89-11e8-9115-91cce6eb7e4c.PNG)

After that, you need to re-insert the cc2531 stick or disconnect and reconnect the board with the cc2530 chip and click Load Image. **Only in first minute after the connection is available bootloader mode!**

![writeimage](https://user-images.githubusercontent.com/8360230/44865059-ece92700-ac89-11e8-8789-c93fbfdec207.PNG)

The firmware will be executed and the chip can be used again.

**Comment by ciotlosm** [comment]
@kirovilya will this allow to flash sticks in a way that maybe allow a RPI to update firmware without removing stick? I was thinking of a process for example where an addon like we have for hassio would be able to check current stable firmware against the one on the stick and update accordingly if needed?

@danielwelch

**Comment by lubeda** [comment]
Is there a download for the bin file available?

**Comment by tb-killa** [comment]
@kirovilya What about this informations: ?? http://processors.wiki.ti.com/index.php/CC253x_Serial_Boot_Loader#
There is the part: ``Reset on a Serial Command`` ..
Maybe it could help :)

**Comment by lubeda** [comment]
@kirovilya a download with a ready made .bin file would be very helpful for all without a cc-debugger. I planed to flash the cc2531 the arduino way until i found that it would take more than an hour...

**Comment by kirovilya** [comment]
@lubeda as I said, this method is suitable only for repeated firmware (not the first). since the bootloader must be flashed first.

**Comment by tb-killa** [comment]
@kirovilya yes the flashing should be complete alone. We could use some sort of api from App to zigbee shepherd for bring in reset. But this is feature :)

**Comment by tb-killa** [comment]
@kirovilya We should check this too: http://processors.wiki.ti.com/index.php/Optimizing_Flash_and_RAM_Usage_of_Z-Stack_for_CC2530
If we could build firmware with maximum available heap we could hopefully fix the error:17 problems.

**Comment by Chrischi-** [comment]
Here is my compiled .bin file for the CC2531. 
It's tested and uploaded it with SerialBootTool at my own CC2531 stick.

I did a optimization before compiling. I resized the XDATA Stack from 0x4D0 to 0x300.
It decreases the free RAM from 1232 bytes to 768 bytes.

After that we can define + allocate the space for the following no. of devices, neighbor

NWK_MAX_DEVICE_LIST=40
MAX_NEIGHBOR_ENTRIES=5

BIN File (242 KB): [CC2531ZNP-D40-N5.bin.zip](https://github.com/Koenkk/zigbee2mqtt/files/2401850/CC2531ZNP-D40-N5.bin.zip)

**Comment by roger-** [comment]
Is it possible to use SerialBootLoader to update a CC2531 that was previously flashed (and working) with the Arduino approach?

In Windows 10 this always gives "COM Port Open Error".

**Comment by michel72** [comment]
Hi, I purchased this module to try with zigbee to mqtt:
http://www.hexin-technology.com/1000m_TTL_to_ZigBee_Module-Product-566.html

I tried flashing it using and USB to serial adapter and this method, but I don't get a connection.

Can anybody tell mw how to flash this thing successfully either using this method or a cc debugger?

**Comment by ryanbeaton** [comment]
Hi @michel72
I’d say you’ll be connecting a debugger to the five pin holes.
![cf29ecb3-33d1-4d64-abcc-da93605c92a2](https://user-images.githubusercontent.com/15151543/52826186-d8470100-30fa-11e9-8f89-cf598fd9115a.jpeg)

**Comment by michel72** [comment]
Thx, do you know the pinout for this connection? It’s not documented anywhere.

**Comment by atzbert** [comment]
> Here is my compiled .bin file for the CC2531.
> It's tested and i uploaded it with SerialBootTool to my own CC2531 stick.
> 
> I did a optimization before compiling. I resized the XDATA Stack from 0x4D0 to 0x300.
> This decreases the free RAM from 1232 bytes to 768 bytes.
> 
> After that we can define + allocate the space for the following no. of devices, neighbor
> 
> NWK_MAX_DEVICE_LIST=40
> MAX_NEIGHBOR_ENTRIES=5
> 
> BIN File (242 KB): [CC2531ZNP-D40-N5.bin.zip](https://github.com/Koenkk/zigbee2mqtt/files/2401850/CC2531ZNP-D40-N5.bin.zip)

Does anyone have a newer version of this? Maybe? :)

**Comment by Chrischi-** [comment]
No because @Koenkk 's files are perfect for every situation right now.

Still waiting to get hands on a [zig-a-zig-ah](https://github.com/electrolama/zig-a-zig-ah) device

**Comment by atzbert** [comment]
Ok, I guess I was on the wrong track anyway. But maybe someone (@Chrischi- ?) can point me in the right direction.
I have two preflashed CC2531 coordinators (bought one with ext antenna later).
Now I'd like to make one of them a router to extend my network.
I don't have the hardware to flash it using CCDebugger. 
If I understand correctly I'd need a SBL router firmware for that.
But how to make one or where to find it?

**Comment by maxschloegl** [comment]
I tried to flash with SBL (SerialBootTool) but it does not show up there. I find it in my hardware manager in Windows 10 but the driver is missing. Can anybody tell me from where i can get the driver?
![grafik](https://user-images.githubusercontent.com/3726156/77763117-df00b100-703a-11ea-969f-1b35dbf16422.png)

BR

**Comment by Anon0ne** [comment]
Any change you can make me a  bin for router firmware? I cannot seem to make a proper bin with the methods on website. It is 256kb instead of 234 and obviously I cant choose to change CRC_SHADOW.

**Comment by Anon0ne** [comment]
> No because @Koenkk 's files are perfect for every situation right now.
> 
> Still waiting to get hands on a [zig-a-zig-ah](https://github.com/electrolama/zig-a-zig-ah) device

We need a router edition though? I not sure what software was used to make the .bin file because the link is broken.

**Comment by puddly** [comment]
I couldn't find a cross-platform version of SerialBootTool so I implemented it in [`zigpy-znp`](https://github.com/zha-ng/zigpy-znp). You can use it standalone to flash a CC2531 on any platform even if you don't use ZHA/zigpy:

```bash
$ pip install zigpy-znp
$ python -m zigpy_znp.tools.flash_read /dev/serial/by-id/radio -o flash.bin
$ python -m zigpy_znp.tools.flash_write /dev/serial/by-id/radio -i flash.bin
```

**Comment by h4nc** [comment]
Referencing to [#31](https://github.com/Koenkk/Z-Stack-firmware/issues/31#issuecomment-617502043) because questions about router bin files came up here too.

**Comment by TTLucian** [comment]
Can the router firmware be flashed by using this method (SBL) on a CC2531 USB dongle preloaded with CC2531ZNP-Prod firmware?

**Comment by sousaaguilherme** [comment]
> 
> 
> No because @Koenkk 's files are perfect for every situation right now.
> 
> Still waiting to get hands on a [zig-a-zig-ah](https://github.com/electrolama/zig-a-zig-ah) device

Hi  @Chrischi- 

Does that mean that I can follow this procedure with this firmware [CC2531_DEFAULT_20201127.zip](https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20201127.zip) without any changes to the bin and hex? Tks 😄

**Comment by iotinkognito** [comment]
Utilising the serial boot tool on CC2531 worked for me. Literally stop HA, plug into Windows 10 machine, run the tool, select the com port and then load image (Downloaded from here. https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default)... bam done.

**Comment by PLTorrent** [comment]
Hi, does anyone happen to have SNIFFER FW for CC2531 in this (bin) format? Is it possible to flash sniffer SW using this method?
