### ISSUE TITLE
UnhandledPromiseRejectionWarning during firmware update HUEDimmer

### ISSUE THREAD

**Issue by muellererwin** [Koenkk/zigbee2mqtt#3210]
zigbee2mqtt: 1.12.0 (Docker)
ConBeeII/ConBee2: 0x264a0700

Issue:
zigbee2mqtt:info  2020-03-27 15:03:24: Updating '0x0017880104f6d13e' to latest firmware
zigbee2mqtt:info  2020-03-27 15:03:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"ota_update","message":"Updating '0x0017880104f6d13e' to latest firmware","meta":{"status":"update_in_progress","device":"0x0017880104f6d13e"}}'
zigbee2mqtt:error 2020-03-27 15:04:25: Update of '0x0017880104f6d13e' failed (Cannot read property 'cancel' of null)
zigbee2mqtt:info  2020-03-27 15:04:25: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"ota_update","message":"Update of '0x0017880104f6d13e' failed (Cannot read property 'cancel' of null)","meta":{"status":"update_failed","device":"0x0017880104f6d13e"}}'
(node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of null
    at /app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:368:20
    at new Promise (<anonymous>)
    at Endpoint.waitForCommand (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:367:25)
    at requestOTA (/app/node_modules/zigbee-herdsman-converters/ota/common.js:100:44)
    at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/ota/common.js:174:27)
    at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/ota/zigbeeOTA.js:50:19)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.js:122:41)
    at async Controller.callExtensionMethod (/app/lib/controller.js:346:21)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

But I am also getting just in between sometimes:
(node:16) UnhandledPromiseRejectionWarning: undefined

(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Koenkk** [comment]
This is because the `waitFor` method has not been implemented yet in the Deconz adapter (https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/deconz/adapter/deconzAdapter.ts#L480). 

I've asked to implement this in the Deconz issue (https://github.com/Koenkk/zigbee-herdsman/issues/72#issuecomment-605210756) therefore I will close this one.
