### ISSUE TITLE
Support for Sengled E12-N1E RGBW Bulb

### ISSUE THREAD

**Issue by Botched1** [Koenkk/zigbee2mqtt#3211]
https://us.sengled.com/products/sengled-smart-led-multicolor-br30-bulb

Detected as not supported. I think this makes it work:

Adding this to devices.js:
```
    {
        zigbeeModel: ['E12-N1E'],
        model: 'E12-N1E',
        vendor: 'Sengled',
        description: 'Smart LED Multicolor (BR30)',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    },
```

Here is the database.db entry:
`{"id":13,"type":"EndDevice","ieeeAddr":"0xb0ce181403526626","nwkAddr":60295,"manufId":4448,"manufName":"sengled","powerSource":"Mains (single phase)","modelId":"E12-N1E","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[0,3,4,5,6,8,768,1794,2821,64515],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"E12-N1E","manufacturerName":"sengled","powerSource":1,"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":1}}},"binds":[]}},"appVersion":1,"stackVersion":0,"hwVersion":1,"zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1585326016701}`

**Comment by Koenkk** [comment]
added, will be supported in the dev branch in a few hours.
