### ISSUE TITLE
set Retain option via mqtt message

### ISSUE THREAD

**Issue by andreypopov** [Koenkk/zigbee2mqtt#3215]
Please, add possibility to set retain option same as friendly_name. Even it was not added in configuration.yaml before.

**Comment by Koenkk** [comment]
Added this, can now be done via https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigdevice_options 

Available in the latest dev branch

**Comment by andreypopov** [comment]
ok nice! works for device, but what about groups? (

**Comment by Koenkk** [comment]
It will also work for group, I know the naming is bad but that will be solved in #3281
