### ISSUE TITLE
Error when trying install to Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by olkitu** [Koenkk/zigbee2mqtt#323]
![image](https://user-images.githubusercontent.com/10426342/44869533-84547700-ac96-11e8-89fc-f66a82fe589e.png)

I tried install with `npm install` command to latest version to Ubuntu 18.04 LTS but i got error. I have npm version 6.4.1

**Comment by Koenkk** [comment]
This is not an error but a warning, does zigbee2mqtt work?

**Comment by olkitu** [comment]
I disabled npm audit check and reinstalled so then it works without warnings.
