### ISSUE TITLE
Permission to use the logo for a loxberry plugin

### ISSUE THREAD

**Issue by romanlum** [Koenkk/zigbee2mqtt#3232]
# Bug Report
## What happened
I currently creating a loxberry plugin for zigbee2mqtt

see https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt

I mostly finished the implementation and i am currently finalizing the plugin for first beta tests.
Therefore i would like to use the original logo of zigbee2mqtt.

Do you allow me to use the official logo for that particular plugin?

**Comment by Koenkk** [comment]
Yes feel free to use it.
