### ISSUE TITLE
report unavailable devices to mqtt

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#324]
Would it make sense to report the available/unavailable status of devices to mqtt ?
It would permit to use payload_available/payload_unavailable in home assistant.

**Comment by Koenkk** [comment]
yes, but the problem is that it is hard to determine if a device is online/offline.

**Comment by lolorc** [comment]
yes I guess it's tricky for sensors. don't you check online status for plugs/router/etc ?
