### ISSUE TITLE
Errors since Update to 1.0.3

### ISSUE THREAD

**Issue by KabaErdbeer** [Koenkk/zigbee2mqtt#3247]
Hello together,

ioBroker is running on a Raspberry 3+ with following versions:

pi@raspberrypi:/opt/iobroker $ node -v
v10.19.0
pi@raspberrypi:/opt/iobroker $ nodejs -v
v10.19.0
pi@raspberrypi:/opt/iobroker $ npm -v
6.13.4

After the update of the Zigbee Adapter to Version 1.0.3 is the adapter always yellow with the following errors in the log: 

zigbee.0 2020-03-29 10:51:48.661 error at binding.open.then.err (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12)
zigbee.0 2020-03-29 10:51:48.661 error at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.0 2020-03-29 10:51:48.661 error at SerialPort.serialPort.open (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:111:49)
zigbee.0 2020-03-29 10:51:48.661 error at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
zigbee.0 2020-03-29 10:51:48.661 error at new Promise (<anonymous>)
zigbee.0 2020-03-29 10:51:48.661 error at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
zigbee.0 2020-03-29 10:51:48.661 error at Generator.next (<anonymous>)
zigbee.0 2020-03-29 10:51:48.661 error at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:113:32)
zigbee.0 2020-03-29 10:51:48.661 error (3914) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
zigbee.0 2020-03-29 10:51:48.658 error (3914) Failed to start Zigbee
zigbee.0 2020-03-29 10:51:43.375 info (3914) Starting Zigbee...
zigbee.0 2020-03-29 10:51:43.374 info (3914) Try to reconnect. 1 attempts left
zigbee.0 2020-03-29 10:51:33.370 error at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
zigbee.0 2020-03-29 10:51:33.370 error at Generator.throw (<anonymous>)
zigbee.0 2020-03-29 10:51:33.370 error at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
zigbee.0 2020-03-29 10:51:33.370 error (3914) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee.0 2020-03-29 10:51:33.367 error (3914) Failed to start Zigbee
zigbee.0 2020-03-29 10:51:17.769 info (3914) Starting Zigbee...
zigbee.0 2020-03-29 10:51:17.710 info (3914) starting. Version 1.0.3 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.19.0
host.raspberrypi 2020-03-29 10:51:13.270 info instance system.adapter.zigbee.0 started with pid 3914
host.raspberrypi 2020-03-29 10:51:13.246 info "system.adapter.zigbee.0" enabled

I deinstalled/installed the adapter. I tried to pull out the stick (CC2531) and on again and changed the settings from /dev/serial/by-id/usb-Texas_Instruments... to /dev/ttyAMA0 - without any changes.

I hope, you could help?

Regards
Marius

**Comment by Koenkk** [comment]
This is the zigbee2mqtt issue tracker, for iobroker please see https://github.com/ioBroker/ioBroker.zigbee
