### ISSUE TITLE
UNSUPPORTED_ATTRIBUTE with Trådfri reporting setup for lightingColorCtrl

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3260]
# Bug Report
## What happened
Removed and joined back my `TRADFRI bulb E27 CWS opal 600lm"` reporting setup for lightingColorCtrl fails.

I think the messages also makes sense as there is no `colorTemperature` that can be reported on this bulb, just normal color value as it is a RGB bulb.

```
zigbee2mqtt:info  2020-03-31 23:31:16: Successfully setup reporting for '0x000d6ffffe197fe9' - 1 - genOnOff
zigbee2mqtt:info  2020-03-31 23:31:16: Successfully setup reporting for '0x000d6ffffe197fe9' - 1 - genLevelCtrl
zigbee2mqtt:error 2020-03-31 23:31:17: Failed to setup reporting for '0x000d6ffffe197fe9' - Error: ConfigureReporting 0x000d6ffffe197fe9/1 lightingColorCtrl([{"attribute":"colorTempe
rature","minimumReportInterval":3,"maximumReportInterval":300,"reportableChange":1},{"attribute":"currentX","minimumReportInterval":3,"maximumReportInterval":300,"reportableChange":1},{"attribute":"currentY","minimumReportInterval":3,"maximumReportInterval":300,"reportableChange":1}], {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)
```
## What did you expect to happen
Reporting to be setup correctly.

## How to reproduce it (minimal and precise)
Remove and pair a trådfri RGB bulb.

## Debug Info
zigbee2mqtt version: `1.12.0-dev (commit #defe6a5)`
CC253X firmware version: `{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":201906
08}}`

**Comment by Koenkk** [comment]
Fixed in latest dev, thanks for reporting.
