### ISSUE TITLE
Add Homeassistant autodiscovery for permit_join property

### ISSUE THREAD

**Issue by jeffreykog** [Koenkk/zigbee2mqtt#3262]
All zigbee devices discovered by Z2M are automaticly added to homeassistant by mqtt autodiscovery. On https://www.zigbee2mqtt.io/integration/home_assistant.html there is a list of sensors and switches that could be added manually in order to control joining and some other stuff from HA itself.

It would be really nice if some properties like the permit_join property got announced on autodiscovery to homeassistant, so no or minimal manual configuration is required.

Would it be logical/practical to add this? What is everyones view on this?

**Comment by presslab-us** [comment]
Personally I use Zigbee2MqttAssistant.  So adding those entities would be redundant for me.
