### ISSUE TITLE
Interview fails OSRAM Smart+ gardenpole 8.7W RGBW

### ISSUE THREAD

**Issue by julian2701** [Koenkk/zigbee2mqtt#3264]
# Bug Report
## What happened
Interviews fails every time when trying to pair "Smart+ gardenpole 8.7W RGBW"

## What did you expect to happen
Pair device

## How to reproduce it (minimal and precise)
Interviewed and resetted device many times, restarted zigbee2mqtt many times

## Debug Info
zigbee2mqtt version: 1.11.0
CC253X firmware version: 20190608
Log: https://pastebin.com/auAP4pWn

**Comment by Tom85649** [comment]
Hi Julian,
I've got 4 garden pole units, and all of them I can only pair directly with the coordinator. For me it never worked with routers in between.  Maybe you got the same prob ? So what I do is bring them close to the coordinator, pair them, and then bring them to their final destination.
KR Tom

**Comment by Koenkk** [comment]
Can you try again with the latest dev branch? (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by julian2701** [comment]
Thank you for your replies.

@Koenkk Installing dev-branch lead to a more detailed error, but interview failed although. Log: https://pastebin.com/YVH9se34

@Tom85649 Thank you, I will try to do that in the afternoon, need to get my gardenpoles out of the garden, because I managed to successfully join the LEDs 3 weeks ago until they were not reachable any more the last days ("no ack")

**Comment by Koenkk** [comment]
I've pushed another possible fix to the dev branch, can you try pairing it at the wanted location?

**Comment by julian2701** [comment]
> I've pushed another possible fix to the dev branch, can you try pairing it at the wanted location?

Thank you, Koenkk! I moved my raspberry just an hour before your answer right near to the gardenpoles, and from then on it was working fine. I think it was the distance and now also all other devices are working. Does the new dev branch and a log might also be interesting for you?

**Comment by Koenkk** [comment]
If its working OK now no further action is required, could you close this issue?

**Comment by odelma** [comment]
Hello, I am running 1.21.0-dev commit: fc2e8304. I tried to pair my Ledvance (I assume it is quite the same model as sold under OSRAM brand) Gardenpole Mini, but the interview process keeps failing with similar log info as presented here. Is the solution to try to pair it closer to controller (zzh)?

In database I only see:
`{"id":53,"type":"Unknown","ieeeAddr":"0x7cb03eaa0a078e9a","nwkAddr":23902,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":16xxxxxxxxxxx}` 

I assume this model should be supported?
![image](https://user-images.githubusercontent.com/10372952/132669264-1427af73-64b0-4747-90fa-67642d052e49.png)
