### ISSUE TITLE
IKEA E1525/E1745 Battery Status / OTA Update

### ISSUE THREAD

**Issue by ChrisSantiago82** [Koenkk/zigbee2mqtt#3266]
I have 8 Ikea Motion sensors in my system. Only 2 of them are sending the battery information. With the other sensors this information is missing in the payload.

I didn't buy all of them at the same time and because of this I'm pretty sure they have all different firmware status. The two that show the battery status, it says in the payload "update_available":false"
The once that don't show the battery status, it shows that an update is available. My idea is, if I update their firmware, then maybe it would show the battery status as well. But sadly I'm always getting a "Device didn't respond to OTA request". Even when I put brand new batteries into it.

The first Sensor I bought, at the beginning it would show the battery status, but now not anymore. Is it possible to make the zigbee2mqtt compatible to different firmware versions?

Has anyone experience or any ideas with that problem?

**Comment by maxill1** [comment]
Same problem here. I have 3 E1525 and 4 E1745 devices.
One of the E1745 is missing battery property:
`
{"elapsed":180005,"last_seen":1601063665479,"linkquality":93,"occupancy":false,"update_available":false}
`
The other 6 reports fine:
`{"battery":47,"elapsed":578721,"last_seen":1601064165719,"linkquality":93,"occupancy":true,"update_available":false}`

Tried repairing with no success.

I'm on 1.14.4 version and LAUNCHXL-CC26X2R1 with firmare:
`'{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20191106,"transportrev":2},"type":"zStack3x0"}'`
