### ISSUE TITLE
In Node Red want to use a aquara door sensor to turn on xiaomi gateway light when opening the door but time to time receive the same message when the door stay opened.

### ISSUE THREAD

**Issue by spider7611** [Koenkk/zigbee2mqtt#3273]
My problem is that the message arrive again and again after about 50 minutes. So the light turn on again and again while the door stay open. I need only one turn on message when the door opening. How can I solve this?

**Comment by FedeBZ** [comment]
Use a rbe node
https://flows.nodered.org/node/node-red-node-rbe

**Comment by Botched1** [comment]
RBE node, and this really sounds more like a Node-RED question than a z2m issue...

**Comment by spider7611** [comment]
Ok, sorry. Will go there. Thank You!
