### ISSUE TITLE
Stelpro smt402AD

### ISSUE THREAD

**Issue by TePazz** [Koenkk/zigbee2mqtt#3284]
Hello,
I can't get a Stelpro SMT402 thermosstat to work.
My hub detects it my tells me that it is not recognized.
In my opinion the problem is due to the fact that it is a new model the smt402AD. On the other hand I believe that it is exactly the same. I think I should only add it.

thank you.

**Comment by Koenkk** [comment]
This device is currently unsupported, please follow: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by TePazz** [comment]
hi, i made a pull requests for devices.js and homeassistant.js to add the 2 thermostat. I tested them and it works very well with this code. A big thank you to @carldebilly for the precious help on the files to be improved and much more.

**Comment by Koenkk** [comment]
merged the prs, thanks!
