### ISSUE TITLE
IKEA E1524 reporting 1/2 of actual battery percentage

### ISSUE THREAD

**Issue by vke** [Koenkk/zigbee2mqtt#3286]
# Bug Report
## What happened

IKEA E1524 five key remote sends half the actual battery charge for the newly inserted battery:

```
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x00)
    Destination Endpoint: 1
    Cluster: Power Configuration (0x0001)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 4
ZigBee Cluster Library Frame, Command: Report Attributes, Seq: 10
    Frame Control Field: Profile-wide (0x08)
        .... ..00 = Frame Type: Profile-wide (0x0)
        .... .0.. = Manufacturer Specific: False
        .... 1... = Direction: Server to Client
        ...0 .... = Disable Default Response: False
    Sequence Number: 10
    Command: Report Attributes (0x0a)
    Attribute Field
        Attribute: Battery Percentage Remaining (0x0021)
        Data Type: 8-Bit Unsigned Integer (0x20)
        Remaining Battery Percentage: 50,0 [%]
```
The same information in mqtt messages:

```
/zigbee2mqtt/fivekey_remote01:{"linkquality":156,"last_seen":1585931371613,"update_available":false,"battery":50}
```

Is it possible to add workaround for IKEA devices to show 100% instead of 50%?

## What did you expect to happen

100%

## How to reproduce it (minimal and precise)

Just insert a new battery into the device.

## Debug Info
zigbee2mqtt version:  1.12.0-dev (commit #496c532)
CC253X firmware version: cc1352p, `{"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20200312}}`

**Comment by Koenkk** [comment]
Fixed, thanks for reporting. Turns out it was already using the `battery_not_divided` converters but this converter was not dividing :smile:

Will be available in latest dev in a few hours.
