### ISSUE TITLE
ZigBee sniffing with ZBOSS

### ISSUE THREAD

**Issue by alflinusjonsson** [Koenkk/zigbee2mqtt#3287]
Hi,
Successfully installed zigbee2mqtt (cc2531) and running a mosquitto server on a rpi. Now i want to sniff the traffic, followed the guide provided here in the repository but cant download ZBOSS. Created an account but haven't received any confirmation mail from them allowing me to log in. Anyone else with similar problem? Or is there any other way to sniff the traffic?

Thanks in advance!

**Comment by Kryzek** [comment]
Check junkmail also of using Gmail.

**Comment by alflinusjonsson** [comment]
Checked junkmail, nothing there :(

**Comment by pixeldoc2000** [comment]
There is also https://www.ti.com/tool/PACKET-SNIFFER from TI. I've use it with good success.

https://sunmaysky.blogspot.com/2018/10/how-to-use-cc2531emk-and-wireshark-as.html

Use something like http://bugmenot.com/view/zboss.dsr-wireless.com to download ;-)

**Comment by alflinusjonsson** [comment]
The login details from your link worked, thanks a lot! :)

**Comment by alflinusjonsson** [comment]
Successfully installed ZBOSS and made all settings showed here:  [https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html](url)

But getting connection errors while running my zigbee2mqtt at the same time. Is it not possible to run zigbee2mqtt **and** sniff traffic with ZBOSS at the same time using cc2531?

If I close my zigbee2mqtt server, I´m allowed to sniff traffic. But it´s empty since my server is not running.

![3f6109fc9f89c2a011548df7a79ae0b3](https://user-images.githubusercontent.com/32966642/78470143-53b4a900-7727-11ea-801c-1add4d6a47ea.png)
![b86aa80db06324b58085f4bea544a31f](https://user-images.githubusercontent.com/32966642/78470144-544d3f80-7727-11ea-9887-14dd9450d51a.png)

**Comment by dinhchinh82** [comment]
@alflinusjonsson Have you set the zigbee channel & USB port correctly yet?

**Comment by alflinusjonsson** [comment]
Yes, ZigBee channel is set to (0x0B (11)) and USB port is COM3 (CC2531)

**Comment by alflinusjonsson** [comment]
But as I understand now, its different CC2531 firmwares for zigbee2mqtt and sniffing and therefore its not possible to sniff and run zigbee2mqtt on the **same** dongle at the **same** time.

**Comment by brendanmullan** [comment]
> 
> 
> But as I understand now, its different CC2531 firmwares for zigbee2mqtt and sniffing and therefore its not possible to sniff and run zigbee2mqtt on the **same** dongle at the **same** time.

Correct, you need the ZBOSS firmware installed to sniff traffic. Would suggest closing this issue to help keep the list clear :-)
