### ISSUE TITLE
My Gledopto monocolor Dimmer does not give the state itself, polling is required

### ISSUE THREAD

**Issue by daddvok** [Koenkk/zigbee2mqtt#3292]
Hi, i have Gledopto Zigbee Dimmer GL-C-009, everything is managed as needed, but.
I did direct binding with Ikea Tradfri wireless dimmer and when i change brightness through this dimmer, i dont get the state with the current brightness. 
could you do a regular polling of this device?
or please tell me how I can do it myself?

Z2M: 1.12
Coordinator: V3 CC2538 with ZStack 3.0

**Comment by Koenkk** [comment]
Soon a feature will be added allowing people to write custom extensions, for now you have to `devices.js` like https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L4236
