### ISSUE TITLE
Documentation error - Aqara opple Aqara Opple switch 1/2/3

### ISSUE THREAD

**Issue by DiGierre** [Koenkk/zigbee2mqtt#3301]
I think there a small error in the doc: Supported devices Aqara Opple switch 1 / 2 / 3 bands:

It's the part on changing to command mode, it states:
"To do this send to zigbee2mqtt/FRIENDLY_NAME/set payload {"operation_mode": "event"}"

I think this should be
"To do this send to zigbee2mqtt/FRIENDLY_NAME/set payload {"operation_mode": "command"}"

Because I assume to change it to command mode (from event mode) you need to send "command, not event...

**Comment by Koenkk** [comment]
fixed, thanks!
