### ISSUE TITLE
Failed to interview Nyce NCZ-3011-HA, device has not successfully been paired

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee2mqtt#3305]
#Bug Report 
## What happened
I rebuilt one of my ZB networks as some devices were hoping between them because they had the same network key.
I upgraded z2m to latest dev as well as firmware (see below).
Some of my devices do not join anymore (NYCE devices): 1 NCZ-3011-HA and 1 NCZ-3041-HA. I attach a debug log.
I did add some comments to the log: look for ************************ string.

## What did you expect to happen
Both devices were working before the upgrade
## How to reproduce it (minimal and precise)
I have tried the join process several times. No success.
## Debug Info
zigbee2mqtt version: 1.12.0-dev commit 552eec7
CC253X firmware version: CC2532P-2 20200328
The address of the NCZ-3011-Ha is 0x000d6f0004b72537 and it's name: MotionNyce1

Log: https://pastebin.com/LPsbeLxK

Txs.

**Comment by Koenkk** [comment]
Can you try replacing `/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/device.js` with https://gist.github.com/Koenkk/8fd00243c3c4ea5864ea867fe56f71dd and try again?

**Comment by ccorderod** [comment]
@Koenkk Fixed :-) their pair correctly now and send events. Txs Koen. Should I close the issue?

**Comment by Koenkk** [comment]
This can be closed indeed, this fix is included in Zigbee2mqtt 1.12.2.
