### ISSUE TITLE
Network Map Problem with CC2538 

### ISSUE THREAD

**Issue by gitbreiti** [Koenkk/zigbee2mqtt#3315]
I have a new CC2538 stick in use. I removed the stick during testing and after that the network map doesn't work anymore. I have already deleted the adapter and installed it fresh but the map doesn't work anymore. does anyone have an idea?

**Comment by artist67** [comment]
I have an issue with the network map in conjunction with an cc2538.
The map is somehow garbled, most of the devices have no lnks.
