### ISSUE TITLE
Adding Hue Attract to supported device list

### ISSUE THREAD

**Issue by ppent** [Koenkk/zigbee2mqtt#3316]
Hi!
I' tried adding Philips Hue Attract to supported devices. As I'm not too familiar with GitHub, it would be great if this could be supported officially.

Since there are already several Hue Lights supported, I only edited devices.js:
{
        zigbeeModel: ['1746130P7'],
        model: '1746130P7',
        vendor: 'Philips',
        description: 'Hue Attract',
        extend: hue.light_onoff_brightness_colortemp_colorxy,
    }

I'm using this as part of my iobroker installation. That's why I added the following in the devices.js of iobroker under "node_modules/iobroker.zigbee/lib/devices.js":
{
        vendor: 'Philips',
        models: ['1746130P7'],
        icon: 'img/philips_hue_1746130P7.png',
        states: lightStatesWithColor,
        syncStates: [sync.brightness],
    }

I will probably have to raise a similar issue on iobroker as well to have it officially supported?

Thank you!

**Comment by Koenkk** [comment]
Done, thanks
