### ISSUE TITLE
ptvo_switch_uart   value ep1 published in all messages

### ISSUE THREAD

**Issue by pdeprost** [Koenkk/zigbee2mqtt#3320]
Hello,

First of all thanks for the new UART support of PTVO router.

How to adapt the converter fromZigbee.js to avoid the last UART message to be repeated in the next MQTT messages (I need it only once, when received by the CC2530 serial port) 

     ptvo_switch_uart: {
         cluster: 'genMultistateValue',
         type: ['attributeReport', 'readResponse'],
         convert: (model, msg, publish, options, meta) => {
              return {'ep1': msg.data['stateText']};
         },
    },

Thank you!

Regards,

Pierre.

**Comment by Koenkk** [comment]
@ptvoinfo could you help with this?

**Comment by ptvoinfo** [comment]
@pdeprost, @Koenkk 
I don't know how to disable saving of the last state for a single value if the "cache_state" configuration option is active in "configuration.yaml" in zigbee2mqtt.

**Comment by pdeprost** [comment]
@Koenkk @ptvoinfo 
Yes but, if  ep1 is managed like an 'input'  button?
example
"click":"bottom_left_double"
appears only once in the message  (when the button is fired).

**Comment by ptvoinfo** [comment]
@pdeprost Yes, "click" is marked as "do not cache". But it is not possible to do the same for a custom value.

**Comment by pdeprost** [comment]
@Koenkk @ptvoinfo 
Ok, Thank you.  So I will add an incremental index number to the serial data to be able to distinguish a new message form the older repeated from the cache. 
Another question: 
How to send data from Z2M to CC2530 UART's output

**Comment by ptvoinfo** [comment]
@Koenkk Could I ask to add a feature to ignore caching for a single value for an individual device? Somehow, specify it in the returned response.

**Comment by pdeprost** [comment]
I find this a great idea!

Another question:
How to send data from Z2M to CC2530 UART's output?
mqtt topic "zigbee2mqtt/..../ep1/set" isn't working.

**Comment by ptvoinfo** [comment]
@pdeprost  zigbee2mqtt/[FRIENDLY_NAME]/set/ep1

**Comment by Koenkk** [comment]
I think the code should be changed form `return {'ep1': msg.data['stateText']};` to `return {'action': msg.data['stateText']};`. This will prevent the message from being cached.

**Comment by pdeprost** [comment]
Nice! It's working correctly! 
and to keep compatibility I changed it to : 
		return {'ep1': msg.data['stateText'], 'action': msg.data['stateText']};
Thank you

**Comment by Koenkk** [comment]
@ptvoinfo what do you think, does it make sense?

**Comment by ptvoinfo** [comment]
@Koenkk It is applicable in this particular case. But the meaning of the value is confusing.

**Comment by Koenkk** [comment]
I wil close this as the pull request has been merged. Thanks!

**Comment by pdeprost** [comment]
Thanks !
