### ISSUE TITLE
Adding/removing from group doesnt work

### ISSUE THREAD

**Issue by andreypopov** [Koenkk/zigbee2mqtt#3324]
ver 1.12.2:
Trying to add/remove device from group. No response on valid group/device names.   Please, check.

![2020-04-10_08-25-00](https://user-images.githubusercontent.com/1624839/78965164-ea58df80-7b04-11ea-9ce6-58781419ff51.png)

**Comment by Koenkk** [comment]
Can you provide the debug logging and your `configuration.yaml`?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by andreypopov** [comment]
![2020-04-17_07-33-06](https://user-images.githubusercontent.com/1624839/79533100-c571e880-807f-11ea-801a-756244f12eff.png)
`info  2020-04-17 07:46:29: Adding 'door1' to 'qwe1'
info  2020-04-17 07:46:31: Adding 'door2' to 'qwe1'
error 2020-04-17 07:46:34: Failed to call 'Groups' 'onMQTTMessage' (Error: Command 0x00158d000239cc0a/1 genGroups.add({"groupid":2,"groupname":""}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)
    at Endpoint.<anonymous> (/mnt/data/root/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:23)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/data/root/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
error 2020-04-17 07:46:36: Failed to call 'Groups' 'onMQTTMessage' (Error: Command 0x00158d0002b774d8/1 genGroups.add({"groupid":2,"groupname":""}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: AREQ - AF - dataConfirm after 5000ms)
    at Endpoint.<anonymous> (/mnt/data/root/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:23)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/data/root/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
error 2020-04-17 07:46:57: Device 'q4' does not exist
info  2020-04-17 07:46:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_group_add_failed","message":{"friendly_name":"q4","group":"test","error":"entity doesn't exists"}}'
`

**Comment by andreypopov** [comment]
![2020-04-17_07-47-44](https://user-images.githubusercontent.com/1624839/79533121-d6baf500-807f-11ea-8fda-a56aab997916.png)

**Comment by andreypopov** [comment]
any news here?

**Comment by Koenkk** [comment]
- Can you check with latest dev branch?
- What device is `0x00158d000239cc0a`?

**Comment by andreypopov** [comment]
**1.12.2-dev**
0x00158d000239cc0a: lumi.sensor_magnet

nothing changed with dev

**Comment by Koenkk** [comment]
This device does not supports groups

**Comment by andreypopov** [comment]
Can you add log with error? no messages right now

**Comment by andreypopov** [comment]
Also there is no error, when device is turned off. 

![2020-04-23_08-04-01](https://user-images.githubusercontent.com/1624839/80061129-0e6ee480-8539-11ea-8dff-6c3c48847e57.png)

**Comment by Koenkk** [comment]
- There is currently no list of devices that support group. Generally these are switches and bulbs
- The MQTT feedback will be fixed here #3281
