### ISSUE TITLE
Log messages 'No converter available for XX with cluster 'genOta'

### ISSUE THREAD

**Issue by Huppeltje16** [Koenkk/zigbee2mqtt#3327]
# Bug Report
## What happened
Log messages are generated like:
debug 2020-04-10 19:28:24: Received Zigbee message from 'XXXXX', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4107,"imageType":10221,"fileVersion":33}' from endpoint 1 with groupID 0
debug 2020-04-10 19:28:24: No converter available for 'ZG9101SAC-HP' with cluster 'genOta' and type 'commandQueryNextImageRequest' and data '{"fieldControl":1,"manufacturerCode":4107,"imageType":10221,"fileVersion":33}'
As my current install is not fully stable, I suspect this is part of the cause.

## What did you expect to happen
I expected not to get these messages.

## How to reproduce it (minimal and precise)
Connect a sunricher dimmer.
## Debug Info
zigbee2mqtt version: 1.12.0
CC253X firmware version:  '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}}'

**Comment by Koenkk** [comment]
These messages are not a problem and expected when the device supports OTA functionallity. They just inform you that the device has send this message and zigbee2mqtt doesn't publish it to MQTT (which makes sense for these messages).
