### ISSUE TITLE
Receiving multiple messages using zigbee2mqtt/[FRIENDLY_NAME]/get

### ISSUE THREAD

**Issue by samtherecordman** [Koenkk/zigbee2mqtt#3329]
# Bug Report
## What happened
When using zigbee2mqtt/[FRIENDLY_NAME]/get  (payload:{"state":"","brightness":""}) I receive two messages with both values as opposed to one message with both values. sometimes the messages don't have same values. Is this expected?
This is kind of related to [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/1477)
## What did you expect to happen
Receive one message with both values up to date
## How to reproduce it (minimal and precise)

1. change state of device (light/dimmer) outside of zigbee by manually turning it on
2. send a z2m/[device/get (payload:{"state":"","brightness":""}) message to the device
3. listen on the mqtt-in node and you should get two messages.

## Debug Info
zigbee2mqtt version: zigbee2mqtt@1.12.0-dev
CC253X firmware version: CC2531 Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}

**Comment by Koenkk** [comment]
These properties require 2 commands to be send to the device and therefore we will also get 2 Zigbee messages back = 2 MQTT messages.

In case you want to have them combined you can use the `debounce` option: https://www.zigbee2mqtt.io/information/configuration.html#all-devices
