### ISSUE TITLE
Error OTA

### ISSUE THREAD

**Issue by RudySixOw** [Koenkk/zigbee2mqtt#3336]
Hi, 

I try to update some devices but even if i use friendly name or not, i have always this error:

debug 2020-04-11 12:07:27: Received MQTT message on 'zigbee2mqtt/bridge/ota_update/update' with data '{bandeauled-cuisine}'
error 2020-04-11 12:07:27: Failed to call 'OTAUpdate' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Device not found or not a device
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.js:81:9)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:336:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5))

debug 2020-04-11 12:09:30: Received MQTT message on 'zigbee2mqtt/bridge/ota_update/update' with data '{0x7cb03eaa00a25908}'
error 2020-04-11 12:09:30: Failed to call 'OTAUpdate' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Device not found or not a device
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.js:81:9)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:336:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5))

But when i see the log, i see that: 

info  2020-04-11 12:10:22: MQTT publish: topic 'zigbee2mqtt/bandeauled-cuisine', payload '{"state":"OFF","linkquality":26,"brightness":1,"color_temp":146,"color":{"x":0.3805,"y":0.3769},"update_available":true}'

Sorry for my english and thanks for your work.

PS: I give you some information about my config:
info  2020-04-11 11:57:32: Logging to console and directory: 'data/log/' filename: log.txt
debug 2020-04-11 11:57:32: Loaded state from file /opt/zigbee2mqtt/data/state.json
info  2020-04-11 11:57:32: Starting zigbee2mqtt version 1.12.2-dev (commit #2d66145)
info  2020-04-11 11:57:32: Starting zigbee-herdsman...
debug 2020-04-11 11:57:32: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"},"adapter":{"concurrent":null}}'
info  2020-04-11 11:57:34: zigbee-herdsman started
info  2020-04-11 11:57:34: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
debug 2020-04-11 11:57:34: Zigbee network parameters: {"panID":6754,"extendedPanID":"0xdddddddddddddddd","channel":11}
info  2020-04-11 11:57:34: Currently 24 devices are joined:

**Comment by Koenkk** [comment]
The payload is wrong, it should be `bandeauled-cuisine` instead of `{bandeauled-cuisine}`.
