### ISSUE TITLE
problem with a Xiaomi Aqara single key wired wall switch (Router)

### ISSUE THREAD

**Issue by mpuff** [Koenkk/zigbee2mqtt#334]
Hello,

i cant get and send commands to a Xiaomi Aqara single key wired wall switch.
in my logs i can see this:

> 2018-9-4 21:04:34 - info: Xiaomi_wall_switch_Garage_mitte (0x00158d00024262ea): QBKG11LM - Xiaomi Aqara single key wired wall switch (Router)

> 2018-9-4 21:04:34 - info: 0x00158d0001568c0c (0x00158d0001568c0c): QBKG04LM - Xiaomi Aqara single key wired wall switch (Router)`

the first one 0x00158d00024262ea is working, but the secound not.
than i get these logs:

> 2018-9-4 21:07:16 - info: Zigbee publish to '0x00158d00024262ea', genOnOff - on - {} - null

> 2018-9-4  21:07:17 - info: MQTT publish, topic: 'zigbee2mqtt2/Xiaomi_wall_switch_Garage_mitte', payload: '{"state":"ON","linkquality":84,"power":135.56,"consumption":0.12,"temperature":24}

when i send an command, i get these error:

> 2018-9-4 22:33:29 - info: Zigbee publish to '0x00158d0001568c0c', genOnOff - on - {} - 2
2018-9-4 22:33:30 - error: Zigbee publish to '0x00158d0001568c0c', genOnOff - on - {} - 2 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
2018-9-4 22:33:51 - info: Zigbee publish to '0x00158d0001568c0c', genOnOff - off - {} - 2
2018-9-4 22:33:52 - error: Zigbee publish to '0x00158d0001568c0c', genOnOff - off - {} - 2 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.

i also have tried to rejoin the 0x00158d0001568c0c, but it doesnt work, these device does not rejoin a secound time.
Does someone know how to reset these switch? i have presset the button 5 secound and more, it lights red and than it blinks blue, but no entry in the logs that a new device joins in the network.

i have installed the latest 0.1.3 version of zigbee2mqtt.
The wall switch that works is a new version of the switch, the other one is an half year old, but was never in use, maybe it is not compatible?

**Comment by Koenkk** [comment]
Is the QBKG04LM within range of the coordinator (CC2531 stick), this looks like a range/connection problem.

**Comment by mpuff** [comment]
it is 3 ore 4 meters away, in the same room like the secound wall switch, the raspberry is also in the same room, no wall between the devices

**Comment by mpuff** [comment]
when i turn the switch on manually, i doesn't get a log info on the raspberry

**Comment by Koenkk** [comment]
Can you post your zigbee map? instructions: #252

**Comment by ciotlosm** [comment]
@mpuff any update here or is the problem now solved?

**Comment by mpuff** [comment]
the problem is not solved.
can you explain me how do i get thes zigbee map?
Do i need to send an mqtt message to the zigbee2mqtt?

**Comment by oischinger** [comment]
@ciotlosm 
I have exactly the same problem.
I get this when trying to set the switch from homeassistant:
`Oct 02 17:50:31 raspberrypi2 npm[21141]:   zigbee2mqtt:info 2018-10-2 17:50:31 Zigbee publish to '0x00158d00024f0e7f', genOnOff - on                                                
Oct 02 17:50:31 raspberrypi2 npm[21141]:         - {} - {"manufSpec":0,"disDefaultRsp":0} - 2                                                                                       
Oct 02 17:50:32 raspberrypi2 npm[21141]:   zigbee2mqtt:error 2018-10-2 17:50:32 Zigbee publish to '0x00158d00024f0e7f', genOnOff - on - {}                                          
Oct 02 17:50:32 raspberrypi2 npm[21141]:                     - {"manufSpec":0,"disDefaultRsp":0} - 2 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
`


My map is: 
`'[{"ieeeAddr":"0x00158d000213176b","nwkAddr":41403,"lqi":54,"parent":"0x00124b0014d9e14d","status":"online"},{"ieeeAddr":"0x00124b0014d9e135","nwkAddr":30585,"lqi":1,"parent":"0x00124b0014d9e14d","status":"online"},{"ieeeAddr":"0x00158d00024f0e7f","nwkAddr":40390,"lqi":93,"parent":"0x00124b0014d9e14d","status":"online"},{"ieeeAddr":"0x00158d000232bff3","nwkAddr":38596,"lqi":64,"parent":"0x00124b0014d9e14d","status":"online"}]'`

Funny thing is that the mqtt messages for the switch states (when pressing the buttons manually) are sent out just fine. Router firmware is up 2 date.


@mpuff 
The map can be generated by sending the following mqtt message:
zigbee2mqtt/bridge/networkmap/raw
Watch the output of zigbee2mqtt for the response.

**Comment by fantomnotabene** [comment]
Exactly **the same** (error code 205 and message) here (Athom Homey), possible cause is the _signal interference with 2.4ghz wi-fi_ signal. 
The same **~3 meters without walls between devices** but _another wired aqara wall switch_ - 2 keys, without neutral. 
With Homey I [can't change the channel](https://github.com/athombv/homey/issues/2398) (wtf?), and the router with wi-fi channel 1 somewhere nearby is not mine, so I can't change its channel too. 
But all of you, I think, can try. For example, [11 zigbee-channel and wi-fi channel 11 is a good case](https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html).

**Comment by mpuff** [comment]
@oischinger when i piblisch zigbee2mqtt/bridge/networkmap/raw i dosnt get an output, i also have subscribe zigbee2mqtt/bridge/#, here i only get the online satus

**Comment by fantomnotabene** [comment]
Thank you too, @oischinger. That "magic" (after re-pairing) worked fine. Exactly. One. Day. 
Right now I'm experiencing the same problem again...

**Comment by rgsertel** [comment]
Did somebody find solution for this problem, I has the same problem, If i delete the device and repair again, it only works a few hours...

**Comment by jvmonjo** [comment]
Same issue here.

**Comment by Koenkk** [comment]
Let's continue in #943
