### ISSUE TITLE
Binding two endpoints

### ISSUE THREAD

**Issue by cblims** [Koenkk/zigbee2mqtt#335]
Hi, is there any ways to bind to endpoints so they interact with each other? I see that zigbee-shepherd has support for this through bind function in the Endpoint class. But I can't see any implementation of this command in zigbee2mqtt. Is it possible in any ways, or is this on road map? 
https://github.com/zigbeer/zigbee-shepherd/wiki#bindcid-dsteporgrpid-callback

**Comment by subzero79** [comment]
It should be on the road map

https://github.com/Koenkk/zigbee2mqtt/issues/15
