### ISSUE TITLE
Zigbee2MQTT crash after adding unsupported device

### ISSUE THREAD

**Issue by macdelft** [Koenkk/zigbee2mqtt#3354]
## Bug Report

When pairing my SR-ZG9080A Curtain Motor Controller, Zigbee2MQTT crashes

## What did you expect to happen

The device seems to pair successfully (Added to configuration.yaml) however, Zigbee2MQTT crashes in the process. 
Pair seems to be successful;

`  zigbee2mqtt:info 4/13/2020, 10:19:17 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0xccccccfffe269b0e","meta":{"modelID":"Motor Controller"}}'
`

## Logs

Zigbee2MQTT debug-mode logging
https://pastebin.com/embed_js/8AT1wp3y

Crash:
`Apr 13 21:54:43 MacPi npm[8510]: /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:49
Apr 13 21:54:43 MacPi npm[8510]:         throw new Error(`Cluster with key '${key}' does not exist`);
Apr 13 21:54:43 MacPi npm[8510]:         ^
Apr 13 21:54:43 MacPi npm[8510]: Error: Cluster with key '33' does not exist
Apr 13 21:54:43 MacPi npm[8510]:     at Object.getCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:49:15)
Apr 13 21:54:43 MacPi npm[8510]:     at Object.getAttributeLegacy (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/index.js:39:27)
Apr 13 21:54:43 MacPi npm[8510]:     at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/shepherd.js:145:36
Apr 13 21:54:43 MacPi npm[8510]:     at Object._.forEach (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/busyman/index.js:411:27)
Apr 13 21:54:43 MacPi npm[8510]:     at ZShepherd.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/shepherd.js:144:11)
Apr 13 21:54:43 MacPi npm[8510]:     at ZShepherd.emit (events.js:198:13)
Apr 13 21:54:43 MacPi npm[8510]:     at dispatchIncomingMsg (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/af.js:565:41)
Apr 13 21:54:43 MacPi npm[8510]:     at Controller.zclIncomingMsgHandler (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/af.js:631:12)
Apr 13 21:54:43 MacPi npm[8510]:     at Controller.emit (events.js:198:13)
Apr 13 21:54:43 MacPi npm[8510]:     at Immediate.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/af.js:640:23)
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! code ELIFECYCLE
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! errno 1
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! Exit status 1
Apr 13 21:54:43 MacPi npm[8510]: npm ERR!
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Apr 13 21:54:43 MacPi npm[8510]: npm ERR! A complete log of this run can be found in:
Apr 13 21:54:43 MacPi npm[8510]: npm ERR!     /home/pi/.npm/_logs/2020-04-13T19_54_43_366Z-debug.log`

Zigbee-Herdsman Debug logs:
https://pastebin.com/embed_js/8AT1wp3y

## How to reproduce it (minimal and precise)

Factory reset SR-ZG9080A, this enables pairing mode to a coodinator network. Zigbee2MQTT picks up the device, tries to pair/pairs and crashes

## Debug Info
Zigbee2mqtt version: 1.6.0
Adapter hardware: CC2531
Adapter firmware version: Unknown

**Comment by Koenkk** [comment]
1.6.0 is quite an old version, make sure you are on the latest zigbee2mqtt first (1.12.2)

**Comment by macdelft** [comment]
Hi @Koenkk 
It's resolved after upgrading to the latest version. Sorry for disturbing!
