### ISSUE TITLE
last_seen report on Xiaomi Aqara RTCGQ11LM - human body movement and illuminance sensor

### ISSUE THREAD

**Issue by tonipetrovic** [Koenkk/zigbee2mqtt#3357]
# Bug Report
## What happened

When RTCGQ11LM is reports occupancy=1 and after time, when there is no occupancy any more, the sensor reports occupancy=0 but the last_seen parameter stays the same as in the first report.

## What did you expect to happen
I guess the last_seen parameter should be also updated since the sensor reports again?
## Debug Info
Zigbee2mqtt version: zigbee2mqtt version 1.12.0 (commit #840b9d9)
Adapter hardware: CC1352P-2
Adapter firmware version: N/A

**Comment by Koenkk** [comment]
This is expected as the sensor does not send occupancy false, occupancy false is an event generated by zigbee2mqtt when it hasn't received an occupancy true from the sensor for some time.
