### ISSUE TITLE
Unstable on RaspberryPi 1

### ISSUE THREAD

**Issue by raymonvdm** [Koenkk/zigbee2mqtt#3395]
# Bug Report
## What happened

I have installed Zigbee2Mqtt on a RaspberryPI 1B to place at a remote household to control some Ikea Tradfri outlets. The setup was done some weeks ago and i tried to pick it up again this week to fix the SSH access to the device and to place it at the household. If i recall correctly the outlets were working fine where is left it the last time. But now the not discovered correctly. 

## What did you expect to happen

Normal switching of outlets, and normal disovery / learning of new outlets

## How to reproduce it (minimal and precise)

Install Raspbian GNU/Linux 10 \n \l on a Pi 1 and use the normal installation steps for Zigbee2Mqtt

## Debug Info

Zigbee2mqtt version: 1.12.2
Adapter hardware: CC2531
Adapter firmware version: {'type': 'zStack12', 'meta': {'transportrev': 2, 'product': 0, 'majorrel': 2, 'minorrel': 6, 'maintrel': 3, 'revision': 20190608}}

## Note

I am also running another setup where the stick is placed in an ESXi Hypervisor (SuperMicro) and is running fine on version 1.08 i don`t know if it is possible to downgrade to this specific version to rule out version issue. Both sticks have the same firmware

**Comment by swissbyte** [comment]
Could you please tell us a little bit more about the exact behavior? You have written: "they are not discovered correctly now" how do you know that?

Could you please enable the debug mode of herdsman and post us your debug log file here?

Thank you
