### ISSUE TITLE
Feature request: Symlink current log to log/log.txt

### ISSUE THREAD

**Issue by mihalski** [Koenkk/zigbee2mqtt#340]
As a convenience, would it be possible to symlink the current log to log/log.txt to simplify debugging?

**Comment by pixiandreas** [comment]
+1

**Comment by tb-killa** [comment]
look at this:
https://github.com/Koenkk/zigbee2mqtt/commit/1f6f73e8d2ca95a16a40e03904b37bb923dc2e78
you could use your own log-destination via configuration.yaml

**Comment by mihalski** [comment]
Sure, but I'd still like a timestamped directory for each log.

**Comment by ciotlosm** [comment]
@mihalski why not use log rotate? I'd not see the purpose of directory timestamps. Rather rotate logs and ship them somewhere else if you really want to be more rigorous with logs.
