### ISSUE TITLE
Hive Signal Booster

### ISSUE THREAD

**Issue by sebastianovide** [Koenkk/zigbee2mqtt#3414]
Hello,

converted forum https://zigbee2mqtt.discourse.group/t/adding-new-support-for-hive-signal-booster/893 issue

I've added a Hive Signal Booster following the instructions from https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html . 

So I've added 

```
{
    zigbeeModel: ['SLB2'],
    model: 'SLB2b',
    vendor: 'Hive',
    description: 'HIVE SIGNAL BOOSTER',
    fromZigbee: [],
    toZigbee: [],
},
```

to devices.js

Also `'SLB2': [cfg.binary_sensor_router]`, to homeassistant.js. 

I see it being part of the mesh (it is acting as a router) but when I query it via mqtt (to get its state and the link quality) it appears not online (home assistant sees it but as offline)

any ideas ?

**Comment by Koenkk** [comment]
As there are no converters, you cannot query the device (which is fine for router only devices). Linkquality can be retrieved through the networkmap. `binary_sensor_router` sensor does not make sense as this device does not expose `state` (it doesn't expose anything as it has no fromZigbee converters).

**Comment by sebastianovide** [comment]
thanks @Koenkk . 

I have another router (a dongle flashed with your firmware) which is using CC2530.ROUTER. Homeassistant finds it and its has 2 entities: binary sensor (connected or not connected) and a link quality. 

I don't know how it does it nor how zigbe2mqtt does it.... or is HA that does some magic ?

Just getting the head around about the missing part so that HA can show also these 2 sensors for the SLB2 router. 

Copying from CC2530.ROUTER I've edited  devices.js

```
    {
        zigbeeModel: ['SLB2'],
        model: 'SLB2b',
        vendor: 'Hive',
        description: 'HIVE SIGNAL BOOSTER',
       supports: 'state, description, type, rssi',
       fromZigbee: [fz.CC2530ROUTER_state, fz.CC2530ROUTER_meta, fz.ignore_basic_report],
       toZigbee: [tz.ptvo_switch_trigger]
    },
```

and homeassistant.js

```
    'CC2530.ROUTER': [cfg.binary_sensor_router],
    'SLB2': [cfg.binary_sensor_router],
```

I'm lost ...

**Comment by Koenkk** [comment]
You cannot copy this, the CC2530 router has changes in the firmware to allow for this. You should compare your device with the tradfri signal repeater. (`E1746`)

**Comment by sebastianovide** [comment]
ok. just following the "trial an error" approach. I've tried

```
    {
        zigbeeModel: ['SLB2'],
        model: 'SLB2b',
        vendor: 'Hive',
        description: 'HIVE SIGNAL BOOSTER',
       toZigbee: [],
        supports: 'linkquality',
        fromZigbee: [fz.E1746_linkquality],
//        meta: {configureKey: 2},
//        configure: async (device, coordinatorEndpoint) => {
//            const endpoint = device.getEndpoint(1);
//            const payload = [{attribute: 'modelId', minimumReportInterval: 3600, maximumReportInterval: 14400}];
//            await bind(endpoint, coordinatorEndpoint, ['genBasic']);
//            await endpoint.configureReporting('genBasic', payload);
//        },
    },
```

Home assistant can see it but as not reachable and link quality unknown... as all the other devices have a link quality but I could not find any reference in the transformers, just wondering if it is built in zigbee2mqtt ?

**Comment by Koenkk** [comment]
To make that work you also need to uncomment the configure and meta lines. This configures the device to regulary send a message.

**Comment by sebastianovide** [comment]
I've initially tried it, but could not understand what configureKey: 2 and getEndpoint(1) were ? are those magic numbers depending on the specific device ?

The error I get is 

```
zigbee2mqtt      | 2020-04-27T16:49:21.062Z serialport/bindings/unixWrite Starting write 10 bytes offset 0 bytesToWrite 10
zigbee2mqtt      | zigbee2mqtt:error 2020-04-27 17:49:21: Failed to configure 'Hive Signal Booster', attempt 1 (TypeError: Cannot read property 'bind' of undefined
zigbee2mqtt      |     at bind (/app/node_modules/zigbee-herdsman-converters/devices.js:41:24)
zigbee2mqtt      |     at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices.js:2747:17)
zigbee2mqtt      |     at DeviceConfigure.configure (/app/lib/extension/deviceConfigure.js:93:45)
zigbee2mqtt      |     at DeviceConfigure.onZigbeeStarted (/app/lib/extension/deviceConfigure.js:61:28)
zigbee2mqtt      |     at Controller.callExtensionMethod (/app/lib/controller.js:336:44))
```

adding 
```
console.log(`**** SEB device: ${JSON.stringify(device)}`);
```
as the first line in the function I get

```
zigbee2mqtt      | **** SEB device: {"ID":15,"_type":"Router","_ieeeAddr":"0x001e5e090229f2fb","_networkAddress":62999,"_manufacturerID":4153,"_endpoints":[{"ID":9,"profileID":260,"deviceID":8,"inputClusters":[0,3],"outputClusters":[25],"deviceNetworkAddress":62999,"deviceIeeeAddress":"0x001e5e090229f2fb","clusters":{"genBasic":{"attributes":{"modelId":"SLB2","manufacturerName":"Computime","powerSource":1,"zclVersion":1,"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20161102"}}},"_binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0018e1f550","endpointID":1}]}],"_manufacturerName":"Computime","_powerSource":"Mains (single phase)","_modelID":"SLB2","_applicationVersion":21,"_stackVersion":2,"_zclVersion":1,"_hardwareVersion":1,"_dateCode":"20161102","_interviewCompleted":true,"_interviewing":false,"meta":{"reporting":1},"_lastSeen":1588005948698}
```

having an endpoint 9. I guess that it is hardcoded in the device (????)

even changing the 1 to 9, I don't get the error anymore, but I still don't see any linkquality.

Any other ideas ?

**Comment by Koenkk** [comment]
- configureKey docs: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L6
- based on your database.db entry it should indeed be endpoint 9
- the error means that your device does not support reporting this attribute, instead of `const payload = [{attribute: 'modelId', minimumReportInterval: 3600, maximumReportInterval: 14400}];` you could try `const payload = [{attribute: 'zclVersion', minimumReportInterval: 3600, maximumReportInterval: 14400}];`. If that also doesn't work it means that we cannot configure the device such that it regularly sends a message to the coordinator. AFAIK the only other way to retrieve the link quality would be a network scan (https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgenetworkmap)

**Comment by sebastianovide** [comment]
just to confirm that it didn't work. Therefore the device is not configurable. 

I guess that another way to fix it (for those devices that don't regularly report back the linkquality)  if we don't want to block the the systems for up to 2 minutes would be to query (pulling) only those devices that don't support reporting... (?) which I'm not sure if the effort would  be justifiable. How many devices don't report back regularly ?

**Comment by Koenkk** [comment]
Something we can do is read an attribute every X minutes (in the example below 1 minute). With this config do you get the linkquality every minute?
```js
    {
        zigbeeModel: ['SLB2'],
        model: 'SLB2b',
        vendor: 'Hive',
        description: 'HIVE SIGNAL BOOSTER',
       toZigbee: [],
        supports: 'linkquality',
        fromZigbee: [fz.E1746_linkquality],
        onEvent: async (type, data, device) => {
            if (type === 'stop') {
                clearInterval(store[device.ieeeAddr]);
            } else if (!store[device.ieeeAddr]) {
                store[device.ieeeAddr] = setInterval(async () => {
                    try {
                        await device.endpoints[0].read('genBasic', ['zclVersion']);
                    } catch (error) {
                        // Do nothing
                    }
                }, 1000 * 60 * 1);
            }
        },
    },
```

**Comment by sebastianovide** [comment]
yes, it works. It reports the linkquality correctly every 1 minute. The only part missing is the "state". Currently it is reported as "disconnected".

**Comment by Koenkk** [comment]
I'm not sure if basing the state on the read is a good idea because when the read fails it won't do anything. (I also forgot what connected/disconnected actually means for the CC2530 router, @ptvoinfo  could you explain this?). 

@sebastianovide in case you want to have the availability I suggest using: https://www.zigbee2mqtt.io/information/availability.html

**Comment by ptvoinfo** [comment]
@Koenkk @sebastianovide The state value means the state of the 'Green' LED indicator on CC2531. It is incorrectly interpreted as connected/disconnected.

**Comment by sebastianovide** [comment]
@Koenkk yes it makes sense. If the device is not available the linkquality sensor will display "unavailable". Which probably is enough for most HA configurations.

@ptvoinfo, the CC2531 provides also a binary sensor. In my case I see:

```
description: 41744/0x00124B001F669750
type:NEIGHBOR
rssi:1
linkquality:0
last seen:2020-04-29T08:37:10+01:00
state:true
led state:true
elapsed:6
```

removing fz.CC2530ROUTER_state from devices.js , the two sensors seem working as before. I cannot see any difference.


Just to make it work similarly to the CC2531, probably the SLB could display some of those (?) in a binary sensor ? (even though I could not think a good use of it yet)

**Comment by Koenkk** [comment]
@ptvoinfo fixed in latest dev branch

@sebastianovide device is supported in latest dev branch now, linkqualty is read every 30 minutes. 

Assuming this can be closed now.

**Comment by sebastianovide** [comment]
that's great @Koenkk . I've just added SLB2 in `homeassistant.js`

**Comment by jayjaytyper** [comment]
Are we able to add support for the signal booster SLB1 also on this?
