### ISSUE TITLE
No network route (Lamp)

### ISSUE THREAD

**Issue by aureliosaraiva** [Koenkk/zigbee2mqtt#3418]
# Bug Report
## What happened
I have one zigbee lamp, it was working, but it how does working more. I don't can to turn off or turn on.

## How to reproduce it (minimal and precise)
 I don't have as reproduce, but I have the log.

```
zigbee2mqtt:error 2020-04-23 17:51:43: Publish 'set' 'state' to '0xf0d1b8000005f532' failed: 'Error: Command 0xf0d1b8000005f532/1 genOnOff.off({}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'No network route' (205))'

zigbee2mqtt:error 2020-04-23 18:29:12: Entity '0xf0d1b8000005f532' is unknown

zigbee2mqtt:error 2020-04-23 18:32:33: Failed to interview '0xf0d1b8000005f532', device has not successfully been paired
```

My lamp is LIGHTIFY LED RGBW A19 (73693) by Sylvania

## Debug Info
Zigbee2mqtt version: 1.12.2
Adapter hardware: CC2531
Adapter firmware version: Zigbee2mqtt 1.12.2

**Comment by Koenkk** [comment]
Make sure to check https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair
