### ISSUE TITLE
ota update precision is not consistant

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3422]
# Bug Report
## What happened

The percentage done does not have the same precision.
```
zigbee2mqtt:info  2020-04-24 14:55:35: Update of 'bathroom/lamp/remote' at 10.21%, +- 78 minutes remaining
zigbee2mqtt:info  2020-04-24 14:56:06: Update of 'bathroom/lamp/remote' at 10.9%, +- 77 minutes remaining
```

## What did you expect to happen

The update percentage is not rounded the  same, having it go from 10.21 -> 10.90 is much more readable.

## How to reproduce it (minimal and precise)

Update a device and watch the mqtt log.

## Debug Info
Zigbee2mqtt version: 1.12.2-dev (commit #63ecc15)
Adapter hardware: CC2531
Adapter firmware version: `{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20200410}}`

**Comment by Koenkk** [comment]
Should be fixed in latest dev, thanks again!
