### ISSUE TITLE
GLEDOPTO only turn on at the second time

### ISSUE THREAD

**Issue by Ulli2k** [Koenkk/zigbee2mqtt#3426]
# Bug Report
## What happened
I am using two GLEDOPTO led controller. Since i made an update of zigbee2mqtt to the release 1.12.2 the two controller are not working properly.

Turning off the LEDs work like before.
To turn on the leds always needs to send the command twice. It never works at the first time.
Other devices like the IKEA led bulb are working as usual without any issue.

## Debug Info
Zigbee2mqtt version: 1.12.2
Adapter hardware: CC2531
Adapter firmware version: latest

**Comment by Koenkk** [comment]
Same bug as #3332  (fixed in latest dev)
