### ISSUE TITLE
[QUESTION] 3D Case Design

### ISSUE THREAD

**Issue by jwillmer** [Koenkk/zigbee2mqtt#343]
I'm working on a 3D case for a Raspberry Pi Zero combined with the CC2531 USB sniffer. Would there be an interest that I link the final project (files) in the wiki of this repository? 

Below you can see how it currently looks like. At the moment I am in the process of printing it to see if all the margins are correct.

![3d-raspberry-pi-zero-case](https://user-images.githubusercontent.com/1503577/45217142-46adaa80-b2a3-11e8-9604-c0400b551cec.png)

**Comment by Koenkk** [comment]
Yes! Feel free to add it to the [Useful information section](https://github.com/Koenkk/zigbee2mqtt/wiki#useful-information)

**Comment by jwillmer** [comment]
Prototype print of the lower half with low quality print settings:
![img_20180907_090100](https://user-images.githubusercontent.com/1503577/45238042-b9894680-b2e0-11e8-8f52-019270b39640.jpg)

**Comment by subzero79** [comment]
nice work @jwillmer! , any tests on coverage once the case is being closed with the top ?

**Comment by jwillmer** [comment]
@subzero79 I can make a few tests when I have the final print but in general I don't expect any changes. After all the CC2531 sniffer was designed with a plastic body around.

**Comment by ciotlosm** [comment]
Any chance for more 3d designs with some donation?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jwillmer** [comment]
Sure, why not. Just send me a mail with what you have in mind.

**Comment by ciotlosm** [comment]
@jwillmer something similar for RPI3B+ with support for an USB mSATA SSD or something similar for an OrangePI. I bet if you do a "support case" topic and specify costs for building each to make it worth your time, more people would be happy to contribute

**Comment by jwillmer** [comment]
I actually got my inspiration from this case: [Round Raspberry Pi Case](https://www.thingiverse.com/thing:2481024). The thing with the standard Raspberry Pi is that there are already [a lot of printable cases](https://www.thingiverse.com/search?q=raspberry+pi+case). If you need the space for an HDD then this case looks quite nice: [ownCloud Raspberry Pi Case + HDD](https://www.thingiverse.com/thing:1357022)

**Comment by ciotlosm** [comment]
@jwillmer I use an mSATA USB enclosure on one (aluminium) and  X850 mSATA SSD hat on the other. Your suggestions look really good and I might try one even if I get extra space around.

**Comment by jwillmer** [comment]
Quick update. I finally got the parts printed in a good quality and tested the margins and lock - all working as expected. Final step is now to print them with white ABS filament.

![img_20180913_130959](https://user-images.githubusercontent.com/1503577/45491154-46148880-b769-11e8-9bea-17bd50f3c142.jpg)
![img_20180913_150556](https://user-images.githubusercontent.com/1503577/45491155-46148880-b769-11e8-9a7f-b10ac4ee794b.jpg)
![img_20180913_150934](https://user-images.githubusercontent.com/1503577/45491156-46ad1f00-b769-11e8-890a-751f246c72ea.jpg)
![img_20180913_150957](https://user-images.githubusercontent.com/1503577/45491157-46ad1f00-b769-11e8-8cfd-9072fbb49faa.jpg)

**Comment by sebastianheierhoff** [comment]
This looks awesome. A case just for the USB stick itself would be great though. Has anyone found something usable or would be willing to create the 3d models?

**Comment by ciotlosm** [comment]
A case for the stick already exists.

**Comment by sebastianheierhoff** [comment]
Can you tell me, where I can find the case for the stick?

**Comment by jwillmer** [comment]
Have a look at [thingiverse.com](https://www.thingiverse.com/search?q=CC2531)

**Comment by cybe** [comment]
> Can you tell me, where I can find the case for the stick?

- https://www.thingiverse.com/thing:2947863
- https://www.thingiverse.com/thing:2803664

**Comment by jwillmer** [comment]
Quick update:
I printed the parts now with white ABS. As you can see from the pictures there are a few issues left:

- The ABS transformed a little while cooling and there is a small opening on the top of the case. I might need to add a sliding connector to prevent this.
- I printed the ventilation openings without support material so they bend a little.
- You can see the parts slightly trough the ABS filament. (This could be a feature for a Zigbee logo if someone decides to let the CC2531 LED on.) Maybe I try some black colour from the inside to prevent this - I don't want to make the walls much thicker.
 
![img_20180914_202509](https://user-images.githubusercontent.com/1503577/45570537-688acc80-b863-11e8-888b-0f455d9660f9.jpg)
![img_20180914_202625](https://user-images.githubusercontent.com/1503577/45570538-688acc80-b863-11e8-86a7-be46d07ac758.jpg)
![img_20180914_202802](https://user-images.githubusercontent.com/1503577/45570539-69236300-b863-11e8-9cff-98bbd8e9ba61.jpg)
![img_20180914_205850](https://user-images.githubusercontent.com/1503577/45570540-69236300-b863-11e8-8db1-3e25b4e414c1.jpg)

**Comment by jwillmer** [comment]
I added a new page called [3D case options](https://github.com/Koenkk/zigbee2mqtt/wiki/3D-Case-Options) to the wiki. I think we can close this question/issue now.
