### ISSUE TITLE
Not coherent illuminance values in RTCGQ11LM and GZCGQ01LM

### ISSUE THREAD

**Issue by soloam** [Koenkk/zigbee2mqtt#3454]
# Bug Report
The new light sensor from xiaomi GZCGQ01LM and the motion sensor RTCGQ11LM do not report coherent values in the illuminance

## What did you expect to happen
Coherent in matching fields

## How to reproduce it (minimal and precise)
I set both sensors aiming at the same direction, I triggered the motion on the RTCGQ11LM and waited for the report of the GZCGQ01LM. This where the results

RTCGQ11LM:
{"illuminance":7,"illuminance_lux":7,"linkquality":39,"occupancy":true}

GZCGQ01LM
{"illuminance":9031,"illuminance_lux":7,"linkquality":39}

The illuminance_lux match, but the illuminance don't... In the RTCGQ11LM they are always the same

## Debug Info
Zigbee2mqtt version: 1.12.2 (911cd58)
Adapter hardware: CC1352P-2
Adapter firmware version: 20191106

**Comment by Koenkk** [comment]
`illuminance` is deprecated and is know to have different values for different devices as the units are different between different devices. Therefore `illuminance_lux` should be used which is always the illuminance value in lux.
