### ISSUE TITLE
brightness_move: stop immediately turns bulb to state before dimming

### ISSUE THREAD

**Issue by mdhom** [Koenkk/zigbee2mqtt#3456]
# Bug Report
## What happened
When sending `{"state":"ON","brightness_move":40}` my bulb starts dimming up as expected. As soon as i send `{"state":"ON","brightness_move":"stop"}` the bulb immediately takes the state from before dimming. The same happens when dimming downwards.

## What did you expect to happen
The bulb should keep the currently reached brightness and not go dark / bright again.

## How to reproduce it (minimal and precise)
Send `{"state":"ON","brightness_move":40}`, wait 1-2 seconds until lamp goes brighter, then send `{"state":"ON","brightness_move":"stop"}' and see that bulb jumps before dimming state.

## Debug Info
Zigbee2mqtt version: 1.12.2, commit 7d27a54
Adapter hardware: CC2531
Adapter firmware version: zStack12 source routing rev 20190619

**Comment by Koenkk** [comment]
- With what bulb is this?
- Can you provide the logging when running with herdsman debug logging?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by mdhom** [comment]
- With all bulbs i have, tested with
  - Philips Hue Lightbar
  - Ikea Tradfri
- I have loggingg enabled via docker:
`docker run -d -it -v $(pwd)/zigbee2mqtt:/app/data --device=/dev/ttyACM0 -e TZ=Europe/Berlin -e DEBUG=* --restart always --name ZigbeeTwoMqtt koenkk/zigbee2mqtt`
You can find the log here: https://pastebin.com/NBbhv6rE (dimming started at line 236)

**Comment by Koenkk** [comment]
I think the issue occurs because you also provide the `state`.  (`'{"state":"ON","brightness_move":-40}'`, can you try without: `'{"brightness_move":-40}'`

**Comment by mdhom** [comment]
Actually i am setting the state because without, it seemed not to be possible to dimm up a switched off lamp, am i right?

**Comment by Koenkk** [comment]
I expect the `brightness_move` alone also to turn on the bulb (and turn off once brightness 0 has been reached).

**Comment by mdhom** [comment]
That seems not to be the case, i tested it right now and the bulb stays dark if currently switched off and dimming up..
State before test:
`{"state":"OFF","brightness":1,"linkquality":44}`
Command start move:
`{"brightness_move":40}`
Bulb stays dark...

**Comment by mdhom** [comment]
Also, if dimming down, it ends at brightness 1 and state ON. Don't know if that is expected behaviour or not...

**Comment by Koenkk** [comment]
That's indeed true. Should work after changing https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L289 to ` await entity.command('genLevelCtrl', 'moveWithOnOff', payload, getOptions(meta.mapped));`

**Comment by mdhom** [comment]
Thanks, tested it! Dimming up when lamp is initially off works now! When dimming completely down, the state is ON and brightness 1, is that how you would expect it to be? I think it should be off or at least brightness 0?

**Comment by Koenkk** [comment]
Implemented this, also fixed the state reading. Note that the brightens always stays at 1 (the bulb returns this value), but this is overruled by the state "OFF". Available in latest dev branch, assuming this can be closed.
