### ISSUE TITLE
Devices naming [feature request]

### ISSUE THREAD

**Issue by to4ko** [Koenkk/zigbee2mqtt#3469]
Hi! Will it be possible to change devices id naming convention when homeassistant: true found in configuration?

Reason - it's not possible to get entity last_updated\last_triggered for entities with id like 0x00158...

I know that it's possible to rename entities in HA. But what if there are 2-3 HA instances and qround 130+ devices?

 
# Bug Report
## What did you expect to happen
Get my devices in Ha with naming like 158000... without 0x00 in front
## Debug Info
Zigbee2mqtt version: 1.13
Adapter hardware: CC2538
Adapter firmware version: "type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200211}

**Comment by alting** [comment]
Confirm!

**Comment by sjorge** [comment]
Doesn't setting the friendly_name propagate to HA? I'm pretty sure it did last I looked at it.

**Comment by to4ko** [comment]
> Doesn't setting the friendly_name propagate to HA? I'm pretty sure it did last I looked at it.

nope ( 

friendly_name set in z2m devices.yaml to Test_Relay

![fr_name](https://user-images.githubusercontent.com/45161980/80839647-53171180-8c04-11ea-9562-68fda031d993.jpg)

**Comment by to4ko** [comment]
Looks like removing 0x00 nameing will not solve the case. It's HA that is not able to operate with entities name stating with number...

So only option - change naming to HA style sensor.temperature_0x00158 instead of sensor.0x00158...
