### ISSUE TITLE
Tuya Zigbee TYZB02 / TS0042 - NO COMPONENTS 

### ISSUE THREAD

**Issue by Ciubas** [Koenkk/zigbee2mqtt#3481]
This is the: TS0042 but recognize as: _TYZB02_keyjhapk | NO COMPONENTS Maybe this device is not (yet) supported by Zigbee2Mqtt?

Board: CC2531
Version of Zigbee2MqttAssistant (this software): 0.3.147 
Version of Zigbee2Mqtt: 1.8.0
Coordinator version: 20190608

![image](https://user-images.githubusercontent.com/53171052/80916261-dbf29200-8d57-11ea-9392-81022ec3d72f.png)

**Comment by robertcsakany** [comment]
I'm using it. It supperted from: https://github.com/Koenkk/zigbee-herdsman-converters/commit/cbbbbe653d525bdb51cf9ddf0c3e1575bcdf567d

**Comment by Ciubas** [comment]
> I'm using it. It supperted from: [Koenkk/zigbee-herdsman-converters@cbbbbe6](https://github.com/Koenkk/zigbee-herdsman-converters/commit/cbbbbe653d525bdb51cf9ddf0c3e1575bcdf567d)

How you update this file on your HA? :)

**Comment by Koenkk** [comment]
You are using a old version of zigbee2mqtt, first update to the latest one (1.13.0).

**Comment by Ciubas** [comment]
![Screenshot_20200517-135224_Home Assistant](https://user-images.githubusercontent.com/53171052/82143685-f5aad380-9845-11ea-9b02-b873d92b3a64.jpg)

This is my problem, how? Where? I read this 4 times and don't have clue where.

**Comment by Koenkk** [comment]
I expect to get some update notification, please ask this question here: https://github.com/danielwelch/hassio-zigbee2mqtt (I don't use hassio so don't know).

**Comment by Ciubas** [comment]
Thanks. I use supervisor in docker.

**Comment by Ciubas** [comment]
I find the problem - I dont know how, but the repo link in Addons deleted, so I dinn't have aupdates! Now its ok :D 

And its working! :D
