### ISSUE TITLE
INNR SP220 pairing impossible

### ISSUE THREAD

**Issue by Markus1970** [Koenkk/zigbee2mqtt#3482]
Hi All,
I use at the moment Version 1.13.0 on my Bridge. Tried today to pair a Innr Sp220 plug which seems to be the new type of the Innr Sp120 plug. But pairing fails. Also nothing visible in the Logfile. Is this one not supported at the moment? Is there something i can do to get it working?
As Coordinator Firmware is 001_CC2530_DEFAULT_20190608\CC2530ZNP-Prod.hex in use.
Several Senors and plugs are working fine. But this SP220 plug from Innr is impossible to pair :-(

Thanks

Markus

**Comment by Alexis6464** [comment]
Hi,
I have the same problem with my GLEDOPTO GL-S-007Z.
They work before, but i reinstalled my HASSIO in a new machine with the lastest version.

But all my xiaomi device is working fine.

I don't know why...

Thanks,
Alexis

**Comment by sjorge** [comment]
@markus1540 have you tried stopping z2m, removing and inserting the usb, starting z2m before you try to pair.

**Comment by markus1540** [comment]
> @markus1540 have you tried stopping z2m, removing and inserting the usb, starting z2m before you try to pair.

No but thanks for asking. 😬

**Comment by Markus1970** [comment]
I guess,I've found the issue.. I've swapped few weeks ago to another cc2530 Module. Connected now GND to P2_0 and pairing was working. Did thid always in the past on the CC2530 but forgotten to connect this on the last one.

Thanks 
Markus

**Comment by Alexis6464** [comment]
> Hi,
> I have the same problem with my GLEDOPTO GL-S-007Z.
> They work before, but i reinstalled my HASSIO in a new machine with the lastest version.
> 
> But all my xiaomi device is working fine.
> 
> I don't know why...
> 
> Thanks,
> Alexis

With HASSIO 0.109.3, my problem it's solved.
