### ISSUE TITLE
Symfonisk remote spams log with "no converter available" upon pairing

### ISSUE THREAD

**Issue by hutchinsane** [Koenkk/zigbee2mqtt#3489]
Upon pairing, the Symfonisk sound controller spams the z2m debug log with "no converter available for E1744..." messages. Controller works fine, with the CC2531, but I thought I'd report the bug anyways. The corresponding logs can be found at:
https://pastebin.com/zRDg3fix

**Comment by Koenkk** [comment]
This is expected for all devices when pairing (these messages don't have to be handled by zigbee2mqtt as it makes no sense to publish them to MQTT).
