### ISSUE TITLE
Tradfri devices cannot pair with z2m using the deconz stack "unsupported_attribute"

### ISSUE THREAD

**Issue by hutchinsane** [Koenkk/zigbee2mqtt#3490]
When trying to pair any Ikea/Tradfri Zigbee devices (Tried: Symfonisk sound controller, Tradfri On/Off switch, Tradfri light remote) the pairing process errors out during configuration with "unsupported attribute" and the devices cannot be used. 

Additionally, the z2m logs show a bunch of "no converters available" messages. The logs attached are specifically for the Symfonisk controller.

The corresponding logs can be found at:
https://pastebin.com/vGw1d41K

**Comment by Koenkk** [comment]
Besides the error, does it report battery?

**Comment by hutchinsane** [comment]
It does not finish the pairing process and never appears in my device list so I would assume not. Or do you mean in general? Because pairing with the CC2531 works and there it does report battery level.

**Comment by Koenkk** [comment]
On line 63 it does `zigbee2mqtt:info  2020-05-04 06:06:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xec1bbdfffe398315","model":"E1744","vendor":"IKEA","description":"SYMFONISK sound controller","supported":true}}'`. Only the configure fails therefore I ask if it reports battery.

**Comment by hutchinsane** [comment]
My apologies, I assumed that configure unsuccessful was equivalent to pairing unsuccessful. I've just repaired it and waited for a while, and it doesn't seem to reporting any battery status values, neither to the logs nor to the MQTT topic.

**Comment by Koenkk** [comment]
@hutchinsane the error is conbee specific, please post the log here so the team can take a look at it: https://github.com/Koenkk/zigbee-herdsman/issues/72

**Comment by ChrisHae** [comment]
Please try the new version of the deconz adapter. I uploaded some fixes. Please tell if it worked.

**Comment by hutchinsane** [comment]
@Koenkk Alright, thank you very much, I'll post the logs in the correct thread!
@ChrisHae Hi, I just reinstalled z2m and the issue still seems to persist, unfortunately!

**Comment by palitu** [comment]
is there a reason this was closed?  I am having the same issue.

**Comment by palitu** [comment]
@hutchinsane ?
is there a reason this was closed? I am having the same issue.

**Comment by ChrisHae** [comment]
Do you have retested it with the latest version of the dev-branch? With the fix i uploaded 14 days ago the unsupported attribute error should be gone.
