### ISSUE TITLE
Link to documentation page "connecting CC2530" missing on main page

### ISSUE THREAD

**Issue by Stefan300381** [Koenkk/zigbee2mqtt#3493]
Hi,

I found this website via google:
https://www.zigbee2mqtt.io/information/connecting_cc2530.html

Seems this is not linked on the main page under https://www.zigbee2mqtt.io/
Any specific reason?

PS: I'd like to make some changes to the page as it recommends to disable bluetooth completely instead of using it with miniuart.

Stefan

**Comment by Koenkk** [comment]
It's listed here: https://www.zigbee2mqtt.io/information/supported_adapters.html#texas-instruments-cc2530-optionally-with-a-cc2591-or-cc2592-rf-frontend

**Comment by Stefan300381** [comment]
ok, didn't expect it under "information", but OK. this can be closed
