### ISSUE TITLE
Identical step twice in Documentation

### ISSUE THREAD

**Issue by Andreyooo** [Koenkk/zigbee2mqtt#3495]
Hey, just a quick notice, in the page https://www.zigbee2mqtt.io/information/docker.html above step 6, the step "Start Docker event listener" is listed twice.

Have a great day!

**Comment by Koenkk** [comment]
I don't see it, one which look similar is Status and Start?

![image](https://user-images.githubusercontent.com/2892853/81046384-93061f00-8eb8-11ea-82aa-741fed935c39.png)

**Comment by Andreyooo** [comment]
Indeed... I grab my head right now. Sry for that.
