### ISSUE TITLE
Implement remove device from database

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt#35]
In case you have a defective device and want to disconnect it from your gateway, you need to run .remove for zigbee-shepard (https://github.com/zigbeer/zigbee-shepherd/wiki#removeieeeaddr-cfg-callback).

Ideal this would be an MQTT command that you can run.

**Comment by palitu** [comment]
yeah i agree.

**Comment by tb-killa** [comment]
@Koenkk Do you actually work on this ?

I think we should do: 
```
var dev = shepherd.find($device, 1).getDevice();
shepherd._devbox, 'remove', dev._getId()
shepherd._devbox, 'sync', dev._getId()
```

What type of mqtt topic whould we do ?

**Comment by Koenkk** [comment]
I haven't worked on this yet. 

The MQTT topic should be `zigbee2mqtt/bridge/config/remove` with the device `friendly_name` as the payload.

Functionality should be implemented here: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L153

**Comment by tb-killa** [comment]
@Koenkk : I work on this Issue but need some help for the remove function themselve:
Look at my Comments on: https://github.com/tb-killa/zigbee2mqtt
Maybe there are some Sort of Flawed thinking.

**Comment by Koenkk** [comment]
@tb-killa looks good, where can I find the comments?

**Comment by ciotlosm** [comment]
@tb-killa please open a PR with your changes against this repo. Use WIP in title to know that this wont' be merged quite yet. We can then help easier with review

**Comment by kirovilya** [comment]
For my app was made forceRemove in controller:
```
    forceRemove(deviceID, callback) {
        const device = this.shepherd._findDevByAddr(deviceID);
        // force
        return this.shepherd._unregisterDev(device, (err, result) => {
            return callback(err, result);
        });
    }
```

**Comment by tb-killa** [comment]
Okay I think it makes sense for us.
I will rework my "removedevice" function and will test again if i got the time.

**Comment by kirovilya** [comment]
@tb-killa xiaomi sensor "device" do not removed by classic method... but "router" do. if classic remove not success - force remove.

**Comment by ciotlosm** [comment]
@kirovilya why did you need a callback on force remove?

**Comment by kirovilya** [comment]
@ciotlosm For waiting remove from shepherd and then delete other app objects.

**Comment by ciotlosm** [comment]
Can you review my PR (I updated a bit the one from @tb-killa ) and let me know which other app objects to remove?

**Comment by kirovilya** [comment]
@ciotlosm ok. I remove objects in my app: states, history...

**Comment by ciotlosm** [comment]
@tb-killa  no worries. Sometimes I'm busy and happy when people assist with mine 👍 
@kirovilya states and history are not part of zigbee2mqtt right?

**Comment by kirovilya** [comment]
@ciotlosm yes, not zigbee2mqtt part

**Comment by ciotlosm** [comment]
@kirovilya can you review code here: #99  and let me know if you are happy with implementation?

**Comment by kirovilya** [comment]
@ciotlosm sorry, not today and not tomorrow. birthday :)

**Comment by ciotlosm** [comment]
Oh, no worries. Happy birthday. I'll have a drink for that!

**Comment by kirovilya** [comment]
@ciotlosm thank you! :)

**Comment by pcb1962** [comment]
Did this ever get implemented? I have devices which I don't use appear on my network map, I assume this is because they have entries in database.db, I would like to remove these. I guess it's not ok to just delete the relevant lines from database.db?

**Comment by pcb1962** [comment]
Thank you, apologies for not finding the relevant mqtt topic, I'm going to study that page now.

**Comment by mawi13** [comment]
Link is broken... new one:
https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove

**Comment by dmak** [comment]
Does it perform any validation of the message? I just posted `rubbish` via Home Assistant interface
![image](https://user-images.githubusercontent.com/366965/61183971-642c6d00-a648-11e9-977a-1262fd0f493b.png)
and I see the following in the log:
```
zigbee2mqtt:debug 7/14/2019, 1:51:34 PM Received MQTT message on 'zigbee2mqtt/bridge/config/remove' with data 'rubbish'
zigbee2mqtt:info 7/14/2019, 1:51:34 PM Successfully removed rubbish
zigbee2mqtt:info 7/14/2019, 1:51:34 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"rubbish"}'
```
It reports that it was successfully removed :)
