### ISSUE TITLE
Paulmann RGB Remote control support 500.67

### ISSUE THREAD

**Issue by probutus** [Koenkk/zigbee2mqtt#3505]
Dear Koenkk,

Referring to closed issue #2038 (Support for Paulmann RGB Remote 500.67 (#2038)). I checked the features and could not find any comment whether it is possible to support this remote or not. 

Is it possible to have the Paulmann remote control supported (especially because of the colour wheel)? Or is there a reason why this is not possible? I see that the Ikea button remote is supported so I assume it would be possible to have the paulmann working aswell.

I have a hue system with a color lamp, a living colors remote (gen2) aswell as the paulmann remote.

I can pair the paulmann with the hue lamp, then it is not controllable via the hue app or zigbee2mqtt anymore.

I also can pair the living colors remote with the lamp and the bridge but I can not pair the remote with zigbee2mqtt.

1) is there a way to get the paulmann remote or the living colors remote supported by zigbee2mqtt?
2) If not is there a colourwheel remote available which is supported?
3) I am already thinking of simulating a lamp by a cc2531 or modify the cc2531 router firmware for  to catch the zigbee messages from the remotes via debug uart and transform them to mqtt messages.

Feedback or a lillte guidance is very welcome

**Comment by Koenkk** [comment]
Let's reopen the original issue and continue there.
