### ISSUE TITLE
State issue with GLEDOPTO GL-C-007

### ISSUE THREAD

**Issue by pgScorpio** [Koenkk/zigbee2mqtt#3509]
# Bug Report
## What happened

When sending a color command like "{"r":255,"g":153,"b":255}" the leds turn on, but the reported state stays on "OFF".

## What did you expect to happen

The reported state should reflect the actual state.

## How to reproduce it (minimal and precise)

As said above:
subscribe to status.
make sure the leds are off.
send a color command i.e. "{"r":0,"g":0,"b":255}"
The leds turn on, but the returned "state" still says "OFF".

## Debug Info
Zigbee2mqtt version: 1.12.2
Adapter hardware: CC2530
Adapter firmware version: zStack12, dateCode: 20190608
GLEDOPTO GL-C-007, HardwareVersion: 1, softwareBuildID: 2.0.3 , dateCode: 20180920

**Comment by Koenkk** [comment]
Fixed in latest dev branch, thanks for reporting.
