### ISSUE TITLE
Devices loose binding to groups

### ISSUE THREAD

**Issue by magpern** [Koenkk/zigbee2mqtt#3515]
## What happened
Just one day, a few IKEA light bulbs and their remote did not work. They had just fallen out of the network.
I an not sure if it could have been the kids playing with the wall power button, and the bulb had reset. I have a CC1352p-2 and the "allow join" disables automatically and the devices do not re-join after kid-play-time is over.
Anyway, I enabled join and joined the light again.

The IKEA remote used for the light did not work anymore. I saw in the logfiles that when pressing a button it still send messages to the correct group. And in the configuratiob.yml the light buld was defined to be apart of the group.

So, problem is. When light re-joins, it looses its group. I restarted the zigbee2mqtt docker (dev) but still, light is not in group.

Running the mqtt command to add the bulb to the group works and remote starts to work again.

Samething happened this evening, when I accidentally reset my FYRTUR blind. After re-join, remote did not work. But after MQTT command add to group, it worked again. 

## What did you expect to happen
Ideally, that devices that reset re-join automatically, like on CC2351, and rejoin its groups
or at least that the group membership updates on reboot of zigbee2mqtt

## How to reproduce it (minimal and precise)
Reset a device bound to a remote

## Debug Info
Zigbee2mqtt version: dev branch - 4 days old
Adapter hardware: CC1352P-2
Adapter firmware version: latest

**Comment by Koenkk** [comment]
When your devices are reset, do they leave the network? (or what other traffic do you seen when doing this in the debug log).

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
