### ISSUE TITLE
Xiaomi\Aqara plugs\sockets Blue LED Control

### ISSUE THREAD

**Issue by to4ko** [Koenkk/zigbee2mqtt#3516]
# Feature Request
## What happened
There is a Blue LED on Aqara\Xiomi plugs\sockets. This led can be switched off via MI Home application. Would be great to have this option via Zigbee2MQTT

## What did you expect to happen
Have availability to turn ON\OFF Blue LED on Aqara\Xiaomi plugs\sockets

## Debug Info
Zigbee2mqtt version: 1.13
Adapter hardware: CC2538
Adapter firmware version:

**Comment by Koenkk** [comment]
Could you sniff the traffic of the Xiaomi bridge when setting this option? If you post the log here together with the network key of your Xiaomi bridge I can add it.

https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by ZZJHONS** [comment]
Does anybody know if this was implemented? Else I would need to buy a sniffer and an aqara hub to log this
