### ISSUE TITLE
Zemismart downlight

### ISSUE THREAD

**Issue by krasevych** [Koenkk/zigbee2mqtt#3523]
# Bug Report
## Debug Info
log: `zigbee2mqtt:warn  2020-05-09 13:14:05: Received message from unsupported device with Zigbee model 'LXT56-LS27LX1.6'`
device info:
```
Zigbee Id is 0x00158d000448cbcb.
Address on Zigbee Network is 0x2F7A.
Link quality is 61/255.
Model is LXT56-LS27LX1.6 by 3A Smart Home DE.
Hardware version is 1.
Firmware version is 1000-0001.
This device type is Router
```

**Comment by Koenkk** [comment]
Added, will be supported in the dev branch in a few hours.

**Comment by krasevych** [comment]
but I thought that it is `Zemismart` not Pry, is it?

**Comment by Koenkk** [comment]
I already reverted that change in favor of your pr

**Comment by krasevych** [comment]
thanks!
