### ISSUE TITLE
Possible to flash a hub/bridge?

### ISSUE THREAD

**Issue by buzurk26** [Koenkk/zigbee2mqtt#3530]
Seeking support for a NUE / Feibit Zigbee Bridge

Hi, i have a NUE / Feibit Zigbee bridge that i no longer use but would hope that i can repurpose, it would be good to flash it with something like zigbee2mqtt to then use in HAS

Anyone know if this would be possible, some photos below
https://imgur.com/a/ElM2MXh

**Comment by IVI053** [comment]
You could flash the CC2530 with the zStack-Firmware but you still need to get access to a linux running on this ARM chip to make use of the CC2530.

Considering the prices for a Pi Zero and a CC253x I would not consider doing this reasonable.
