### ISSUE TITLE
Easiest way to migrate to zigbee2mqtt from deCONZ

### ISSUE THREAD

**Issue by lnoc** [Koenkk/zigbee2mqtt#3531]
Hi everyone!
Is there an easy way to migrate from deCONZ to zigbee2mqtt without having to pair all the devices again? I simply tried to choose the network encryption key as used by deCONZ but that did not help. The log says that no devices is connected.

**Comment by Koenkk** [comment]
This requires repairing of all devices (because the zigbee2mqtt database needs to be populated with the device information).
