### ISSUE TITLE
TS0121 documentation update

### ISSUE THREAD

**Issue by vdbrink** [Koenkk/zigbee2mqtt#3532]
I bought this device https://a.aliexpress.com/_BT6iQ8 
It's recognized as "TuYa 10A UK smart plug (TS0121)",  This is already in the list with supported devices https://www.zigbee2mqtt.io/devices/TS0121.html but my model is an EU version maybe you can add that also to the page and add more pictures from the shop article to the TS0121.html page. My version is also 16A (that's whats on the site and on the box)

**Comment by Koenkk** [comment]
Fixed, documentation will automatically be updated on next zigbee2mqtt release.
