### ISSUE TITLE
Code erreur ELIFECYCLE

### ISSUE THREAD

**Issue by maximebsu** [Koenkk/zigbee2mqtt#3534]
# Bug Report
## What happened

zigbee2mqtt:info  2020-05-11 16:46:55: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-05-11.16-46-55' filename: log.txt
zigbee2mqtt:info  2020-05-11 16:46:55: Starting zigbee2mqtt version 1.13.0 (commit #55e6283)
zigbee2mqtt:info  2020-05-11 16:46:55: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-05-11 16:47:01: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-05-11 16:47:01: Failed to start zigbee
zigbee2mqtt:error 2020-05-11 16:47:01: Exiting...
zigbee2mqtt:error 2020-05-11 16:47:01: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:113:32)
    at Generator.next (<anonymous>)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
    at SerialPort.serialPort.open (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:111:49)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at binding.open.then.err (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.13.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-11T15_47_01_106Z-debug.log

## Debug Info
Zigbee2mqtt version:

homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
advanced:
  channel: 25
  network_key:
    - 73
    - 140
    - 145
    - 206
    - 47
    - 118
    - 132
    - 61
    - 212
    - 177
    - 85
    - 113
    - 235
    - 135
    - 118
    - 223

Adapter hardware: CC2531
Adapter firmware version:

**Comment by gald33** [comment]
I had a similar problem and it turns out that I didn't have the right permissions to the directory.
sudo chown [USER] [PORT] (e.g. sudo chown pi /dev/ttyACM0).
This solved my problem.
This is from the F.A.Q at https://www.zigbee2mqtt.io/information/FAQ.html
