### ISSUE TITLE
Documentation missing Ikea Sensor Channels

### ISSUE THREAD

**Issue by MORD0R** [Koenkk/zigbee2mqtt#3535]
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/E1525_E1745.md

I do not have Home Assistant. These 2 are missing.
requested_brightness_level
requested_brightness_percent

![image](https://user-images.githubusercontent.com/6746199/81590150-ab939f00-93ba-11ea-840f-5b59c9df8e5c.png)

It is the new version.

**Comment by Koenkk** [comment]
Added, thanks for reporting.

Documentation will be automatically updated on next zigbee2mqtt release. Assuming this can be closed.

**Comment by MarcR2000** [comment]
Hi, just added the motion sensor to my setup and the payload only includes occupancy and linkquality. Not even battery status, no update info and no brightness levels. Are you sure the documentation is correct or is there any issue in zigbee2mqtt? The Hardware is the newer model of the motion sensor. Thanks for any advice!

**Comment by MORD0R** [comment]
MarcR200 what if you use mqtt explorer? Are you sure you have the new version?

**Comment by MarcR2000** [comment]
Just updated to the newest version. Still the same in MQTT.fx

**Comment by MarcR2000** [comment]
I have now also tested another Tradfri Motion sensor (latest model) and it's the same. Newest software at all ends. Apparently brightness is not working for the newest model.

**Comment by MORD0R** [comment]
I have an E1745
mqtt and got this. (no update available)
![image](https://user-images.githubusercontent.com/6746199/84236480-fa3a7300-aaf7-11ea-9a9b-25f88120d8f7.png)

What if you press the buttons on the back a few times?

**Comment by MarcR2000** [comment]
Hi Mordor,

still this is all I get as a payload:

"occupancy":true,"linkquality":84,"battery":87,"update_available":false,"device":{"friendlyName":"Tradfri_Motion_Treppe","model":"E1525/E1745",....

**Comment by MORD0R** [comment]
Thats very strange i have no battery... I only have one tradifi sensor to test. 

I have attribute output on.

**Comment by MORD0R** [comment]
its related too https://github.com/Koenkk/zigbee-herdsman-converters/issues/519
