### ISSUE TITLE
Does zigbee2mqtt support 10 usb dongle meanwile？

### ISSUE THREAD

**Issue by zrainx** [Koenkk/zigbee2mqtt#3536]
Hi Koenkk，
     I have a case which needs to support 10 USB dongles working as 10 coordinator meanwhile.
     The 10 usb dongles generate 10 serial ports at the device tree of ubuntu operation system.
     Can I use only one zigbee2mqtt process to support 10 usb dongles?
     Or, Do I have to take 10 zigbee2mqtt processes to serve 10 usb dongles one by one?
Thanks a lot.

**Comment by Koenkk** [comment]
1 zigbee2mqtt instance = 1 donlge. In case you want to run 10 usb dongles on the same machine you need to have 10 zigbee2mqtt instances.
