### ISSUE TITLE
Retention flag for device

### ISSUE THREAD

**Issue by iStitch07** [Koenkk/zigbee2mqtt#3537]
Hello 
You not have examples in wiki for retention flag for device: its bool, int in ms. sec, min or hours

```
retention: Sets the MQTT Message Expiry (default: not enabled). Make sure to set mqtt.version to 5 (see mqtt configuration above)
```

I tried to look it in code and found some like this:
```
devices: {'0x0017880104e45519': {friendly_name: 'tain', retention: 900}},
```

Its mean what i need to add in configuration retention: int, where int ist value in seconds, right?

**Comment by Koenkk** [comment]
It's indeed an int value in seconds, updated the documentation to:

* `retention`: Sets the MQTT Message Expiry in seconds e.g. `retention: 900` = 15 minutes (default: not enabled). Make sure to set `mqtt.version` to `5` (see `mqtt` configuration above)


Thanks, assuming this can be closed.
