### ISSUE TITLE
[feature request] Possibility to remove auto-created sensors

### ISSUE THREAD

**Issue by to4ko** [Koenkk/zigbee2mqtt#3541]
# Feature request
## What happened
It' will be good to have possibility to switch off additional entitys auto-created in Home Assistant - for Xiaomi Plug there is 3  entities created -  switch, power and link quality. But last 2 of them are available as attributes in switch. It leads to additional DB recordings etc.
Yes they can be excluded from being recorded. But this is easy when 2 plug...and not so easy when 130+ devices .... simple option in config might solve this one very easily.

## Debug Info
Zigbee2mqtt version: 1.13
Adapter hardware: CC2538

**Comment by Morphy99** [comment]
+1

**Comment by to4ko** [comment]
as of now kinda solved by disabling un-needed entities from Configuration-Entities menu

**Comment by Koenkk** [comment]
You can skip the discovery of a sensor with the device specific options. E.g. to prevent a temperature sensor from being discovered:

```js
devices:
  '0x00158d0001d82999':
    friendly_name: 'my_occupancy_sensor'
    retain: true
    homeassistant:
      temperature: null
```

**Comment by to4ko** [comment]
> You can skip the discovery of a sensor with the device specific options. E.g. to prevent a temperature sensor from being discovered:
> 
> ```js
> devices:
>   '0x00158d0001d82999':
>     friendly_name: 'my_occupancy_sensor'
>     retain: true
>     homeassistant:
>       temperature: null
> ```

Thanks!!! need to do some changes in my config :)

**Comment by to4ko** [comment]
> You can skip the discovery of a sensor with the device specific options. E.g. to prevent a temperature sensor from being discovered:
> 
> ```js
> devices:
>   '0x00158d0001d82999':
>     friendly_name: 'my_occupancy_sensor'
>     retain: true
>     homeassistant:
>       temperature: null
> ```

is it possible to make this kind of settings for all the devices simultaneously? i have like 132 devices at the moment and it would be good to have possibility to list unwanted type of sensors.

**Comment by Koenkk** [comment]
In the latest dev branch this is now possibly by adding the following to your `configuration.yaml`.

```yaml
device_options:
  homeassistant:
    temperature: null
```

https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by to4ko** [comment]
@Koenkk am i doing something wrong?
here is devices.yaml
![image](https://user-images.githubusercontent.com/45161980/83925023-c75a4d00-a78e-11ea-948b-d6f77499150a.png)


and i'm still having battery and linkquality in HA
![image](https://user-images.githubusercontent.com/45161980/83925056-de993a80-a78e-11ea-9ea1-8f2cbf5e1049.png)

**Comment by Koenkk** [comment]
After this you probably need to clear the retained MQTT discovery message.

**Comment by vitoralvimb** [comment]
How can I do that with the "cover"?
I have my Curtain completely closed, position = 100, and the Home Assistant have the Up Arrow disabled and Down Arrow avaliable. If I open the curtain putting position = 0, the Down arrow stay disabled.

I'd like to invert it.
