### ISSUE TITLE
last_seen still sent after disabling and restarting

### ISSUE THREAD

**Issue by crowbarz** [Koenkk/zigbee2mqtt#3545]
# Bug Report
## What happened
`last_seen: ISO_8601` was removed from `configuration.yaml` and zigbee2mqtt was restarted. Subsequent MQTT device updates are now still including a `last_seen` property, although the actual datestamp is no longer updating as it did prior to disabling `last_seen`.

I also noticed that `last_seen` data still appears for devices in the `state.json` that is periodically dumped to disk.

## What did you expect to happen
If `last_seen` is set to `none`, then cached `last_seen` data should probably be purged. At a minimum, I would not expect stale data to continue to be sent in MQTT device updates.

## How to reproduce it (minimal and precise)
1. Enable `last_seen` in `configuration.yaml` and restart
2. Wait for devices to generate updates and update `last_seen`, and observe the property being sent in MQTT device updates
3. Disable `last_seen` and restart
4. Observe that MQTT messages sent after restarting still contains `last_seen` property, but with stale data.

## Debug Info
Zigbee2mqtt version: 1.13.0
Adapter hardware: CC2531
Adapter firmware version: 20190619

**Comment by Koenkk** [comment]
Fixed in latest dev branch. Make sure that `last_seen` is removed from `state.json` first. Assuming this can be closed now.
