### ISSUE TITLE
Philips Hue bulb - No STATE update after 'Device announced"

### ISSUE THREAD

**Issue by tsprivate** [Koenkk/zigbee2mqtt#3546]
Hi,

I have mostly IKEA bulbs in my house but as well a few from [Philips](https://www.zigbee2mqtt.io/devices/8718696449691.html).

When switching-on the IKEA bulbs via the main-switch I do receive a proper "Device announced" along with a STATE update that the bulbs are "ON"

On the [Philips bulb](https://www.zigbee2mqtt.io/devices/8718696449691.html) I just receive the "Device announced" but the STATE remains in its previous state.  (e.g the bulb is switched-on by the main-switch but STATE is OFF)

Anybody else seen this issue?

Debug Info
Zigbee2mqtt version: 1.13.0
Adapter hardware: CC26X2R1
Adapter firmware version: 3.x.0
Device count: 36

**Comment by sjorge** [comment]
Up to date philips hue bulbs don’t seem to report anything at all.
Once I have a bit of time I intent do write a polling extension to at least poll them every few minutes.
