### ISSUE TITLE
Philips Hue Dimmer Switch command is not always published?

### ISSUE THREAD

**Issue by paddenstoeltje** [Koenkk/zigbee2mqtt#3553]
# Bug Report
## What happened
I recently successfully paired a Philips Hue Dimmer Switch to control my Hue Lamps. In most cases, it works correct, however sometimes a button command is not published and the Dimmer Switch gives a red/orange/green blinking. I checked the debug log, and when it is not published I always get a commandHueNotification, commandOffWithEffect but then a Device 'Hue dimmer switch' announced itself? I suspect this to be the problem? 

Link quality should be fine, with a minimum of 46. I already reconfigured the device.

Below the debug logs of a working & a non-working CMD:

**Pushed button, and get a published CMD:**
- zigbee2mqtt:debug 2020-05-15 11:25:29: Received Zigbee message from 'Hue dimmer switch', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":4,"unknown1":3145728,"type":0,"unknown2":0,"time":0}' from endpoint 2 with groupID 0
- zigbee2mqtt:debug 2020-05-15 11:25:29: Received Zigbee message from 'Hue dimmer switch', type 'commandOffWithEffect', cluster 'genOnOff', data '{"effectid":0,"effectvariant":0}' from endpoint 1 with groupID 0
- zigbee2mqtt:debug 2020-05-15 11:25:29: Received Zigbee message from 'Hue dimmer switch', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":4,"unknown1":3145728,"type":2,"unknown2":0,"time":1}' from endpoint 2 with groupID 0
- zigbee2mqtt:info  2020-05-15 11:25:29: MQTT publish: topic 'zigbee2mqtt/Hue dimmer switch', payload '{"linkquality":31,"update_available":true,"counter":1,"brightness":255,"battery":71,"action":"off-press","duration":0}'
- zigbee2mqtt:info  2020-05-15 11:25:29: MQTT publish: topic 'zigbee2mqtt/Hue dimmer switch', payload '{"linkquality":31,"update_available":true,"counter":1,"brightness":255,"battery":71,"action":""}'
- zigbee2mqtt:info  2020-05-15 11:25:29: MQTT publish: topic 'zigbee2mqtt/Hue dimmer switch/action', payload 'off-press'

**Pushed button, and nothing is published:**
- zigbee2mqtt debug 2020-05-15 11:25:31: Received Zigbee message from 'Hue dimmer switch', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":4,"unknown1":3145728,"type":0,"unknown2":0,"time":0}' from endpoint 2 with groupID 0
- zigbee2mqtt:debug 2020-05-15 11:25:31: Received Zigbee message from 'Hue dimmer switch', type 'commandOffWithEffect', cluster 'genOnOff', data '{"effectid":0,"effectvariant":0}' from endpoint 1 with groupID 0
- _zigbee2mqtt:debug 2020-05-15 11:25:33: Device 'Hue dimmer switch' announced itself_
- zigbee2mqtt:info  2020-05-15 11:25:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"Hue dimmer switch"}}'
- zigbee2mqtt:debug 2020-05-15 11:25:34: Received Zigbee message from 'Hue dimmer switch', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":166}' from endpoint 2 with groupID 0
- zigbee2mqtt:info  2020-05-15 11:25:34: MQTT publish: topic 'zigbee2mqtt/Hue dimmer switch', payload '{"linkquality":31,"update_available":true,"counter":1,"brightness":255,"battery":83}

## What did you expect to happen
Every button press should be registered and published correctly.

## How to reproduce it (minimal and precise)
Happens randomly when pushing any button on the remote. In 4/5 cases it works, the last case nothing is published...

## Debug Info
Zigbee2mqtt version: Zigbee2Mqtt HA 1.13.0
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
Make sure to check: https://www.zigbee2mqtt.io/devices/324131092621.html#troubleshooting
