### ISSUE TITLE
How to config reverse_direction

### ISSUE THREAD

**Issue by anhtuanng98** [Koenkk/zigbee2mqtt#3559]
## What happened
I need to reverse direction of xiaomi curtain motor but I dont know how to config this
`{
    "options":{
        "reverse_direction": true,
        "hand_open": true,
        "reset_move": false
    }
}`
## What did you expect to happen
I tried to put it 
`{
    "options":{

        "reverse_direction": xxx,

        "hand_open": xxx,

        "reset_move": xxx
    }
}`
in state.js, devices.yaml like that

`'0x00158xxxxxxxxxx':

    friendly_name: KC - Curtain

    reverse_direction: true,

    hand_open: true,

    reset_move: false`
Or
`'0x00158xxxxxxxxxx':

    friendly_name: KC - Curtain

     options:

      reverse_direction: true,

      hand_open: true,

      reset_move: false`

But nothing happen.

Could you guide me how to config it?

## Debug Info
Zigbee2mqtt version: 1.13 on debian
Adapter hardware: CC2530
Adapter firmware version: 201902xx

Thank you so much!

**Comment by Koenkk** [comment]
You need to publish that to MQTT. It's documented here: https://www.zigbee2mqtt.io/devices/ZNCLDJ11LM.html#configuration-of-device-attributes
