### ISSUE TITLE
Regression: `transition` parameter influences brightness

### ISSUE THREAD

**Issue by Otah** [Koenkk/zigbee2mqtt#3563]
# Bug Report
## What happened
Regression of a bug #2220

That bug was already fixed half a year ago, but with one of the latest versions it was reintroduced. Briefly:

> When a light is on and has e.g. `brightness: 50`, sending a command `{"state": "ON", "transition": 1}` sets the brightness to maximum (255). Whereas if you send just `{"state": "ON"}`, nothing happens (= the light stays on with brightness at level 50).

## How to reproduce it (minimal and precise)
Exactly the same way as in case of #2220

## Debug Info
Zigbee2mqtt version: 1.13.0 (commit #ac0d17c)
(I have upgraded recently, ~but not sure what was the previous version I have had deployed, where it was working~ previously I was using 1.9.0 where _I think_ it was still working)

**Comment by Koenkk** [comment]
Fixed in latest dev branch. Added a test case this time to make sure it doesn't break another time :smile: Thanks for reporting!

**Comment by Otah** [comment]
Thanks a lot @Koenkk! That was pretty quick response, very appreciated! I have deployed the dev version and I confirm the fix is working well ;-)
