### ISSUE TITLE
new devices

### ISSUE THREAD

**Issue by Kat-CeDe** [Koenkk/zigbee2mqtt#3564]
Hi,
excuse me. I have 2 new devices which are similar to already included devices. I do not want to mess around with git as I am not familiar with it. Perhaps someone more suitable can add these devices.

1.Ferguson (Poland OEM) is the same as Heiman HS1HT
`    {
        zigbeeModel: ['TH-T_V14'],
        model: 'TH-T_V14',
        vendor: 'HEIMAN',
        description: 'Smart temperature & humidity Sensor',
        supports: 'temperature and humidity',
        fromZigbee: [fz.temperature, fz.humidity, fz.battery_3V],
        toZigbee: [],
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint1 = device.getEndpoint(1);
            await bind(endpoint1, coordinatorEndpoint, ['msTemperatureMeasurement']);
            const endpoint2 = device.getEndpoint(2);
            await bind(endpoint2, coordinatorEndpoint, ['msRelativeHumidity', 'genPowerCfg']);
            await configureReporting.temperature(endpoint1);
            await configureReporting.humidity(endpoint2);
            await configureReporting.batteryVoltage(endpoint2);
            await configureReporting.batteryPercentageRemaining(endpoint2);
        },
    },
`
2. GledOpto GL-B-001ZS is the same as GL-B-001Z
`    {
        zigbeeModel: ['GL-B-001ZS'],
        model: 'GL-B-001ZS',
        vendor: 'Gledopto',
        description: 'Smart 4W E14 RGB / CCT LED bulb',
        extend: gledopto.light,
        supports: 'on/off, brightness, color temperature, color',
    },
`
Ralf

**Comment by Koenkk** [comment]
Added, thanks! Will be available in the latest dev branch in a few hours.
