### ISSUE TITLE
restart after power off, why the Xiaomi MiJia light intensity sensor (GZCGQ01LM) data can not be received, must press a light sensor above the button once before returning to normal

### ISSUE THREAD

**Issue by hyzgit** [Koenkk/zigbee2mqtt#3568]
restart after power off, why the Xiaomi MiJia light intensity sensor (GZCGQ01LM) data can not be received, must press a light sensor above the button once before returning to normal

**Comment by hyzgit** [comment]
When you press the button, you print the log

zigbee2mqtt:debug 2020-05-15 17:56:06: Device '0x04cf8cdf3c772313' announced itself
,zigbee2mqtt:info  2020-05-15 17:56:06: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x04cf8cdf3c772313"}}'

**Comment by sjorge** [comment]
It's an issuew it most (all?) Xiaomi devices. They will not change parent once the existing one disapears for a bit.

Hitting the button will make it look for a new one. It's super annoying but this is something that z2m has no control over.

**Comment by hyzgit** [comment]
> It's an issue with most (all?) Xiaomi devices. They will not change parent once the existing one disapears for a bit.
> 
> Hitting the button will make it look for a new one. It's super annoying but this is something that z2m has no control over.

Is there no way to solve this problem? When connecting to Xiaomi Gateway, there should be no such problem, then how he realized it

**Comment by hyzgit** [comment]
Any friends have a good solution?

**Comment by hyzgit** [comment]
Still have this problem, any solution?

**Comment by Koenkk** [comment]
To debug this we would need to sniff the traffic of this issue: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
