### ISSUE TITLE
Exception when pressing UP button on Lutron LZL4BWHL01

### ISSUE THREAD

**Issue by dale3h** [Koenkk/zigbee2mqtt#3578]
# Bug Report
## What happened
Pressing button 1 (up) causes an exception when trying to publish payload to device's corresponding `action` topic.

## What did you expect to happen
Pressing button 1 (up) should publish the action without throwing an exception.

## How to reproduce it (minimal and precise)
1. Pair Lutron LZL4BWHL01.
2. Update settings in `configuration.yaml` (may not be related, but this is my configuration):
```
homeassistant: true
advanced:
  homeassistant_legacy_triggers: false
```
3. If settings were changed, restart Zigbee2mqtt.
4. Press button 1 (up) on Lutron LZL4BWHL01.

## Debug Info
Zigbee2mqtt version: 1.13.1
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20190608
Log Output: https://hastebin.com/upuziminin

**Comment by Koenkk** [comment]
Should be fixed in latest dev branch now
