### ISSUE TITLE
manifest for dwelch2101/zigbee2mqtt-amd64:1.13.1 not found

### ISSUE THREAD

**Issue by kcholewins001** [Koenkk/zigbee2mqtt#3581]
HI, I have an issue with installing a new ver. I'm running on version 1.13.0.
ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by alesoft73** [comment]
I have the same problem!
Many thanks.

**Comment by Koenkk** [comment]
Closing this in favour of https://github.com/danielwelch/hassio-zigbee2mqtt/issues/340
