### ISSUE TITLE
temperature/local_temperature has varying perscissions

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3595]
# Bug Report
## What happened

msTemperatureMeasurement always returns value that has 2 decimals once converted but mqtt will not have them if they are 0. 2000 -> 20, 2010 -> 20.1, ...

```
zigbee2mqtt:info  2020-05-22 19:32:04: MQTT publish: topic 'zigbee2mqtt/bedroom/motion', payload '{"battery":100,"linkquality":68,"occupancy":false,"temperature":20,"illuminance":5475,"illuminance_lux":3,"update_available":false}'
zigbee2mqtt:info  2020-05-22 19:57:16: MQTT publish: topic 'zigbee2mqtt/bedroom/motion', payload '{"battery":100,"linkquality":68,"occupancy":true,"temperature":18.49,"illuminance":5608,"illuminance_lux":3,"update_available":false}'
zigbee2mqtt:info  2020-05-22 20:07:14: MQTT publish: topic 'zigbee2mqtt/bedroom/motion', payload '{"battery":100,"linkquality":68,"occupancy":false,"temperature":18.2,"illuminance":6551,"illuminance_lux":4,"update_available":false}'
```

## What did you expect to happen
I expect the values to always have 2 decimals
2000 -> 20.00
2010 -> 20.10

I vaguely remember this already being fixed at some point? But it seems to be back.
...

## How to reproduce it (minimal and precise)

Have a sensor report msTemperatureMeasurement with trailing 0's

## Debug Info
Zigbee2mqtt version: 1.13.1-dev
Adapter hardware: CC2531
Adapter firmware version: `{"version":"1.13.1-dev","commit":"83215c3","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20200410}}`

**Comment by Koenkk** [comment]
Javascript automatically removes 0 decimals, so this cannot be fixed.
