### ISSUE TITLE
zigbee2mqtt automatically backup the database and create a new database

### ISSUE THREAD

**Issue by fantasyjqc** [Koenkk/zigbee2mqtt#3601]
# Bug Report
zigbee2mqtt automatically backup the database and create a new database, when i restore the backup, zigbee2mqtt can return to normal, i didn't change any configuration, it happened when I was sleeping
![image](https://user-images.githubusercontent.com/4988150/82745278-298d7800-9db5-11ea-9da4-75c5e1214db2.png)

## What did you expect to happen
due to power supply failure, the zigbee2mqtt will autorestart again and again, database will backup 
 and create a new database after last successful restart 

![image](https://user-images.githubusercontent.com/4988150/82745252-ce5b8580-9db4-11ea-916c-1964c611109f.png)

## Debug Info
Zigbee2mqtt version:1.12.2
Adapter hardware: CC2530
Adapter firmware version: 20190619

**Comment by Koenkk** [comment]
First make sure this still happens on 1.13.1, if so please share the herdsman debug log when this reset happens.

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
