### ISSUE TITLE
Philips Hue bulb brightness does not reset when turned off

### ISSUE THREAD

**Issue by Gio76** [Koenkk/zigbee2mqtt#3602]
# Bug Report
## What happened
Philips Hue bulb does not reset brightness to 0 when turned off

## What did you expect to happen
When turning off the bulb, I'm expecting the brightness slider in Home Assistant to go down to 0, behaving like my other smart bulbs; see below example with a Yeelight bulb:

![image](https://user-images.githubusercontent.com/26906928/82745596-833f7380-9db0-11ea-926f-cfab3e2741eb.png)

## How to reproduce it (minimal and precise)
Turn off Hue light. Check Home Assistant. The brightness level remains unchanged. see below screenshot:

![image](https://user-images.githubusercontent.com/26906928/82745575-48d5d680-9db0-11ea-8ff3-2d9fe39a6736.png)

## Debug Info
Zigbee2mqtt version: 1.13.0
Adapter hardware: CC2531 with USB extension cable
Home Assistant: 0.110.0

**Comment by Koenkk** [comment]
Isn't this a Home Assistant issue? I expect the slider to go down to 0% when the bulb is off.
