### ISSUE TITLE
Xiaomi QBKG12LM not pairing

### ISSUE THREAD

**Issue by JaspervRijbroek** [Koenkk/zigbee2mqtt#3604]
Hello all,

I am trying to pair a [Xiaomi QBKG12LM](https://www.zigbee2mqtt.io/devices/QBKG12LM.html) however I seem to get EAGAIN errors.

My log can be found here: https://gist.github.com/JaspervRijbroek/199b29c16fd8116afe94120f40ad3b1d

I press the buttons (both) for about 10 seconds, first they flash red, and then they start blinking blue untill they stop at some point. However the device doesn't seem to connect to the network.

Below a map of my network. I don't think that the link could be an issue as I paired a [Xiaomi MCCGQ11LM](https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html) at a further distance from the coordinator before.

![Overzicht - Home Assistant (1)](https://user-images.githubusercontent.com/1225017/82760263-b6a2f200-9df2-11ea-8f87-c7871e35473d.png)

**Version information**
zigbee2mqtt version 1.13.1
Coordinator firmware version: '{\"type\":\"zStack12\",\"meta\":{\"transportrev\":2,\"product\":0,\"majorrel\":2,\"minorrel\":6,\"maintrel\":3,\"revision\":20190608}}'\n","stream":"stdout","time":"2020-05-25T15:27:41.685544865Z"}

Could anybody help me paring this device?

Kind Regards and Thanks in Advance,

Jasper

**Update:**
I have even tried to move it closer to the coordinator (a cc2531) but to no avail. The buttons still aren't connecting.

**Comment by Koenkk** [comment]
These `EGAIN` errors are not a problem (normal logging of the underlying used serialport libary).

You probably want to check: https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair

**Comment by JaspervRijbroek** [comment]
@Koenkk Turns out that the particular device that I have has close to no range at all ;) Thanks for the support and amazing project!
