### ISSUE TITLE
Feature request: TCP connection to CC2531

### ISSUE THREAD

**Issue by hcsaustrup** [Koenkk/zigbee2mqtt#3606]
I'd like to decouple the server running zigbee2mqtt from the server with the CC2531. The CC2531 would be made available on a TCP port with socat, but zigbee2mqtt seems to lack the ability to connect to a TCP port instead of just a local serial port.

This would allow me to deploy the CC2531 on an ancient Raspberry Pi 1 unit located in the centre of my house, and having zigbee2mqtt running on a more powerful system elsewhere.

**Comment by sjorge** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

It should already work.

**Comment by hcsaustrup** [comment]
Sorry, I missed that - awesome! :-)
