### ISSUE TITLE
When pairing with GL-C-008-2ID debug log has misleading Received message from unsupported device with Zigbee model 'GL-C-007'

### ISSUE THREAD

**Issue by wojciechczyz** [Koenkk/zigbee2mqtt#3608]
# Bug Report
## What happened

With 1.13.1.1 finally "composite" 2ID gledopto devices are supported. Thank you a lot for this.
It works fine, however when pairing logging is a little misleading:

zigbee2mqtt:info  2020-05-25 14:45:14: Device '0x00124b001f79d63e' joined
zigbee2mqtt:info  2020-05-25 14:45:14: Starting interview of '0x00124b001f79d63e'
zigbee2mqtt:info  2020-05-25 14:45:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x00124b001f79d63e"}}'
zigbee2mqtt:info  2020-05-25 14:45:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x00124b001f79d63e"}}'
zigbee2mqtt:info  2020-05-25 14:45:14: MQTT publish: topic 'zigbee2mqtt/0x00124b001f79d63e/availability', payload 'online'
zigbee2mqtt:debug 2020-05-25 14:45:15: Device '0x00124b001f79d63e' announced itself
zigbee2mqtt:info  2020-05-25 14:45:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b001f79d63e"}}'
zigbee2mqtt:debug 2020-05-25 14:45:15: Device '0x00124b001f79d63e' announced itself
zigbee2mqtt:info  2020-05-25 14:45:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x00124b001f79d63e"}}'
zigbee2mqtt:debug 2020-05-25 14:45:15: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"modelId":"GL-C-007"}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:15: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:15: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"GLEDOPTO"}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20180920"}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:debug 2020-05-25 14:45:16: Received Zigbee message from '0x00124b001f79d63e', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"2.0.2"}' from endpoint 11 with groupID 0
zigbee2mqtt:warn  2020-05-25 14:45:16: Received message from unsupported device with Zigbee model 'GL-C-007'
zigbee2mqtt:warn  2020-05-25 14:45:16: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:info  2020-05-25 14:45:17: Successfully interviewed '0x00124b001f79d63e', device has successfully been paired
zigbee2mqtt:info  2020-05-25 14:45:17: Device '0x00124b001f79d63e' is supported, identified as: Gledopto Zigbee LED controller RGB + CCT (2 ID) (GL-C-008-2ID)
zigbee2mqtt:info  2020-05-25 14:45:17: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00124b001f79d63e","model":"GL-C-008-2ID","vendor":"Gledopto","description":"Zigbee LED controller RGB + CCT (2 ID)","supported":true}}'
zigbee2mqtt:info  2020-05-25 14:45:17: MQTT publish: topic 'homeassistant/light/0x00124b001f79d63e/light_rgb/config', payload '{"brightness":true,"xy":true,"schema":"json","command_topic":"zigbee2mqtt/0x00124b001f79d63e/rgb/set","brightness_scale":254,"state_topic":"zigbee2mqtt/0x00124b001f79d63e/rgb","json_attributes_topic":"zigbee2mqtt/0x00124b001f79d63e/rgb","name":"0x00124b001f79d63e_light_rgb","unique_id":"0x00124b001f79d63e_light_rgb_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001f79d63e"],"name":"0x00124b001f79d63e","sw_version":"Zigbee2mqtt 1.13.1","model":"Zigbee LED controller RGB + CCT (2 ID) (GL-C-008-2ID)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/0x00124b001f79d63e/availability"}'
zigbee2mqtt:info  2020-05-25 14:45:17: MQTT publish: topic 'homeassistant/light/0x00124b001f79d63e/light_cct/config', payload '{"brightness":true,"color_temp":true,"schema":"json","command_topic":"zigbee2mqtt/0x00124b001f79d63e/cct/set","brightness_scale":254,"state_topic":"zigbee2mqtt/0x00124b001f79d63e/cct","json_attributes_topic":"zigbee2mqtt/0x00124b001f79d63e/cct","name":"0x00124b001f79d63e_light_cct","unique_id":"0x00124b001f79d63e_light_cct_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001f79d63e"],"name":"0x00124b001f79d63e","sw_version":"Zigbee2mqtt 1.13.1","model":"Zigbee LED controller RGB + CCT (2 ID) (GL-C-008-2ID)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/0x00124b001f79d63e/availability"}'
zigbee2mqtt:info  2020-05-25 14:45:17: MQTT publish: topic 'homeassistant/sensor/0x00124b001f79d63e/linkquality/config', payload '{"icon":"mdi:signal","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00124b001f79d63e","json_attributes_topic":"zigbee2mqtt/0x00124b001f79d63e","name":"0x00124b001f79d63e_linkquality","unique_id":"0x00124b001f79d63e_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001f79d63e"],"name":"0x00124b001f79d63e","sw_version":"Zigbee2mqtt 1.13.1","model":"Zigbee LED controller RGB + CCT (2 ID) (GL-C-008-2ID)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/0x00124b001f79d63e/availability"}'

## What did you expect to happen
Logging that indicates that correct device is detected and well paired. I would not expect any warnings.

## How to reproduce it (minimal and precise)

Pair new GL-C-008-2ID with 2 IDs - composite device with separate RGB and CCT controller

## Debug Info
Zigbee2mqtt version:
1.13.1.1

Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

CC2531 newest with source rooting

**Comment by Koenkk** [comment]
This cannot be fixed from zigbee2mqtt as this is what the device actually returns. Gledopto messed up their firmware here putting the GL-C-007 modelID in to the one of the GL-C-008-2ID.
