### ISSUE TITLE
Aurora Smart Plug, Window Contact and PIR Sensor

### ISSUE THREAD

**Issue by realwillwright** [Koenkk/zigbee2mqtt#3622]
I have updated the PIR sensor with illuminance and added in the Smart Socket and Window Contact sensor. These are now working in zigbee2mqtt edge version. 
As I am using the hassio app from Daniel Welch, I can't edit the homeassistant.js file for them to be included as auto discovered sensors. I have added the code for this. Can someone add the code into a working version? In the future will a way be provided to update the homeassistant.js file similar to the devices file. Maybe the the from and to zigbee files.

lib/extension/homeassistant.js

'AU-A1ZBPIRS': [cfg.binary_sensor_occupancy, cfg.binary_sensor_battery_low, cfg.sensor_illuminance],
'AU-A1ZBDWS': [cfg.binary_sensor_contact, cfg.binary_sensor_battery_low],
'AU-A1ZBPIAB': [cfg.switch, cfg.sensor_power],

devices.js

    {
        zigbeeModel: ['MotionSensor51AU'],
        model: 'AU-A1ZBPIRS',
        vendor: 'Aurora Lighting',
        description: 'AOne PIR sensor',
        supports: 'occupancy',
        fromZigbee: [fz.ias_occupancy_alarm_1, fz.illuminance],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(39);
            await bind(endpoint, coordinatorEndpoint, ['msIlluminanceMeasurement']);
            await configureReporting.illuminance(endpoint);
        },
    },
	{
        zigbeeModel: ['SingleSocket50AU'],
        model: 'AU-A1ZBPIAB',
		vendor: 'Aurora Lighting',
        description: 'Power plug ZigBee EU',
		supports: 'on/off, power measurements',
		fromZigbee: [fz.identify, fz.on_off, fz.electrical_measurement_power],
        toZigbee: [tz.on_off],
        meta: {configureKey: 3},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genIdentify', 'genOnOff', 'haElectricalMeasurement']);
            await configureReporting.onOff(endpoint);
            //await readEletricalMeasurementPowerConverterAttributes(endpoint);
            //await configureReporting.activePower(endpoint);
        },
	},
	{
        zigbeeModel: ['WindowSensor51AU'],
        model: 'AU-A1ZBDWS',
        vendor: 'Aurora Lighting',
        description: 'Magnetic door & window contact sensor',
        supports: 'contact',
        fromZigbee: [fz.ias_contact_alarm_1, fz.battery],
        toZigbee: [],
		ota: ota.zigbeeOTA,
    },

**Comment by Koenkk** [comment]
Added, will be available in the latest dev branch in a few hours (edge for hassio).
