### ISSUE TITLE
Documentation unclear or contradictive

### ISSUE THREAD

**Issue by Nebula83** [Koenkk/zigbee2mqtt#3624]
# Bug Report
## What happened
While reading the docs here: https://www.zigbee2mqtt.io/information/alternative_flashing_methods.html
and here:
https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html

It seems that the statement: "NOTE: When you have already flashed the stick and paired devices to it, reflashing it requires to re-pair all your devices!" on https://www.zigbee2mqtt.io/information/alternative_flashing_methods.html is outdated.

## What did you expect to happen
To have clear and consistent documentation (which it is for the most of it).

## How to reproduce it (minimal and precise)
Read both documents.

**Comment by Koenkk** [comment]
Fixed, thanks!
