### ISSUE TITLE
Osram Smart+ Switch Mini

### ISSUE THREAD

**Issue by hoggerz** [Koenkk/zigbee2mqtt#3626]
# Bug Report
## What happened
Hi
I got an Osram Switch Mini thinking that it would be fairly simple to use with a group of lights or whatever I could assign it to, however it seems to be able to switch every single device on or off that I have in my house, even when I haven't bound it to anything, or specifically bound it to one device or group, and tried unbinding from others. Is there anything that can be done to stop this, or is it a limitation of the device?

## What did you expect to happen
Only control the devices I bind it to.

## How to reproduce it (minimal and precise)

Reset the device by pressing down and circle for 10 seconds, pair it to the CC2531 by holding circle and up for 3 seconds, bind it to a pre-defined group of lights while keeping the device active, then press on or up and all the lights (Ikea GU10 spotlights) in my house turn on instead of just those in the group.

## Debug Info
Zigbee2mqtt version:  1.13.0-dev
Adapter hardware: CC2531 source routing firmware (20190619), 2 x CC2531 running latest router firmware 
Adapter firmware version: 20190619

**Comment by steve41200** [comment]
I have exalte the same pb. And when it binds correctly with not this problem. I regularly see 
Zigbee2MQTT:info  2021-07-19 20:32:33: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"telecommande ext banne terrrasse","ieee_address":"0x00124b0022cdc6c8"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-07-19 20:32:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"telecommande ext banne terrrasse"},"type":"device_announced"}'

in the log. The device work correctly but often I need to reapair it
