### ISSUE TITLE
Adding a new device -> Device announced itself

### ISSUE THREAD

**Issue by wisekki** [Koenkk/zigbee2mqtt#3633]
I'm trying to add a new device to the zigbee2mqtt and I've followed the directions, but I can't make a device join the network fully or lack the skills on how to do it properly.

If I press the button it says "Device xxx announced itself" and if I keep clicking the buttons I get: 
<pre>`Received Zigbee message from '0x00...', type 'raw', cluster 'manuSpecificLegrandDevices', data '{"type":"Buffer","data":[21,33,16,1,9,206,105,130,0,0,116,4,0,1]}' from endpoint 1 with groupID 0`</pre>

But the data part does not change when pressing different buttons. I've added logging to the zigbee2mqtt and sometimes I get on-event type: 'commandOn' but never from the same ON-button. And after a few mins it's forgotten and starts again saying "device xxx announced itself."

This is Legrand remote switch with 2xswitches on/off (AG09596.) It might be with a differect product  code on other countries. Here's a pic of it [https://ibb.co/cyNjP1v](https://ibb.co/cyNjP1v)
Zigbee2mqtt says that this is: <pre>_manufacturerName: 'Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000',
_modelID: ' Double gangs remote switch\u0000\u0000\u0000\u0000'</pre>
Someone has already added some of Legrand products (please help! :) and I tried to copy the code but with no success.

**Comment by sjorge** [comment]
Those are very tricky devices to get to work, see https://github.com/Koenkk/zigbee2mqtt/issues/2399
