### ISSUE TITLE
How to change color of Ikea Tradfri RGB light (LED1624G9)

### ISSUE THREAD

**Issue by hdo** [Koenkk/zigbee2mqtt#364]
I just successfully paired a ikea tradfri rgb light bulb with zigbee2mqtt but don't know how to change the color.

However i can switch on and off without problems.

Can anybody point me to the right direction?

**Comment by Koenkk** [comment]
See: https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttdevice_idset

**Comment by hdo** [comment]
Oh great, thanks a lot. For some reason i must have missed that :-(



> See: https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttdevice_idset
