### ISSUE TITLE
HEIMAN co sensor occur UNSUPPORTED_ATTRIBUTE

### ISSUE THREAD

**Issue by nukusinji** [Koenkk/zigbee2mqtt#3641]
# Bug Report
## What happened
HEIMAN co sensor occur UNSUPPORTED_ATTRIBUTE
## What did you expect to happen

Model DB {"id":23,"type":"EndDevice","ieeeAddr":"0x000d6f000fadf4c2","nwkAddr":59122,"manufId":4619,"manufName":"HEIMAN","powerSource":"Battery","modelId":"COSensor-EM","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"COSensor-EM","manufacturerName":"HEIMAN","powerSource":3,"zclVersion":2,"appVersion":17,"hwVersion":16,"dateCode":"2017.10.31","swBuildId":"1.1.1"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b001ca604d7","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":70}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca604d7","endpointID":1}]}},"appVersion":17,"hwVersion":16,"dateCode":"2017.10.31","swBuildId":"1.1.1","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1590848012131}

## How to reproduce it (minimal and precise)
    info  2020-05-30 22:55:34: Configuring 'living_room_co'
    error 2020-05-30 22:55:42: Failed to configure 'living_room_co', attempt 2 (Error: ConfigureReporting 0x000d6f000fadf4c2/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
        at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
        at Generator.next (<anonymous>)
        at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
## Debug Info
Zigbee2mqtt version:
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

**Comment by Koenkk** [comment]
Fixed in the latest dev branch, thanks for reporting!
