### ISSUE TITLE
'GL-C-008 2ID' not published linkquality

### ISSUE THREAD

**Issue by nukusinji** [Koenkk/zigbee2mqtt#3648]
# Bug Report
## What happened
GL-C-008 not published linkquality.
## What did you expect to happen
GL-C-008 not published linkquality.
I think GL-C-007 2ID, too.

But, Network Map show linkquality. It is not showing status MQTT Topic
## How to reproduce it (minimal and precise)
    zigbee2mqtt:debug 2020-06-01 11:49:32: Received MQTT message on 'Ryan_home/zigbee2mqtt/living_room_curtain_light/cct/set' with 
    data '{"state": "OFF"}'                                                                                                        
    zigbee2mqtt:debug 2020-06-01 11:49:32: Publishing 'set' 'state' to 'living_room_curtain_light'                                 
    zigbee2mqtt:info  2020-06-01 11:49:33: MQTT publish: topic 'Ryan_home/zigbee2mqtt/living_room_curtain_light', payload '{"state_
    cct":"OFF","brightness_cct":0,"color_cct":{"x":0.526676280311873,"y":0.41329727450763},"color_temp_cct":500,"state_rgb":"OFF","
    brightness_rgb":0,"color_rgb":{"x":0.28,"y":0.288},"color_temp_rgb":106}'                                                      
    zigbee2mqtt:info  2020-06-01 11:49:33: MQTT publish: topic 'Ryan_home/zigbee2mqtt/living_room_curtain_light/rgb', payload '{"st
    ate":"OFF","brightness":0,"color":{"x":0.28,"y":0.288},"color_temp":106}'                                                      
    zigbee2mqtt:info  2020-06-01 11:49:33: MQTT publish: topic 'Ryan_home/zigbee2mqtt/living_room_curtain_light/cct', payload '{"st
    ate":"OFF","brightness":0,"color":{"x":0.526676280311873,"y":0.41329727450763},"color_temp":500}' 
## Debug Info
Zigbee2mqtt version: latest-dev
Adapter hardware: CC1352P-2
Adapter firmware version: 200416

**Comment by Koenkk** [comment]
This is expected behaviour, see https://github.com/Koenkk/zigbee2mqtt/issues/3353#issuecomment-613252332 for more details
