### ISSUE TITLE
One of three WSDCGQ11LM is intermittently unavailable

### ISSUE THREAD

**Issue by nikolaykasyanov** [Koenkk/zigbee2mqtt#3650]
# Bug Report
## What happened

One of my 3 Aqara temperature, humidity and pressure sensors started going unavailable in Home Assistant all of a sudden. It still reports data but after a sample is received it goes unavailable. Here's how the graph in HASS looks like:

<img width="363" alt="Screenshot 2020-06-01 at 13 08 59" src="https://user-images.githubusercontent.com/136644/83403471-1019ab00-a409-11ea-94d1-91c936000fed.png">

Here's some logs that look suspicious:

```
zigbee2mqtt_1  | zigbee2mqtt:info  2020-05-29 19:47:19: MQTT publish: topic 'zigbee2mqtt/living_room_climate', payload '{"battery":100,"voltage":3045,"temperature":22.78,"humidity":47.85,"pressure":1016,"linkquality":23,"last_seen":"2020-05-29T19:47:19+00:00"}'
zigbee2mqtt_1  | zigbee2mqtt:info  2020-05-29 19:47:19: MQTT publish: topic 'zigbee2mqtt/living_room_climate/availability', payload 'online'
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 19:48:53: Non-pingable device 'living_room_climate' was last seen '458737.656' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:info  2020-05-29 19:48:53: MQTT publish: topic 'zigbee2mqtt/living_room_climate/availability', payload 'offline'
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 19:53:53: Non-pingable device 'living_room_climate' was last seen '459037.656' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 19:58:53: Non-pingable device 'living_room_climate' was last seen '459337.657' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 20:03:53: Non-pingable device 'living_room_climate' was last seen '459637.658' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 20:08:53: Non-pingable device 'living_room_climate' was last seen '459937.659' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 20:13:53: Non-pingable device 'living_room_climate' was last seen '460237.66' seconds ago.
zigbee2mqtt_1  | zigbee2mqtt:debug 2020-05-29 20:18:53: Non-pingable device 'living_room_climate' was last seen '460537.66' seconds ago.
```

Messages like "device was last seen 458737.656 seconds ago" don't seem to make sense right after sending `'online'` to the availability topic. I figured it might be some internal state issue and tried removing and pairing the device again but no luck.

Replacing the battery didn't help either.

## What did you expect to happen

I expect it to stay available between updates.

## How to reproduce it (minimal and precise)

Not sure, no recent changes in my ZigBee network.

## Debug Info
Zigbee2mqtt version: 1.13.1
Adapter hardware: CC2531
Adapter firmware version: 20190619

**Comment by Koenkk** [comment]
I've pushed a possible fix to the latest dev branch, can you check if it fixes the issue? https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by nikolaykasyanov** [comment]
@Koenkk thanks, I'll switch to a recent dev docker image and see what happens.

**Comment by nikolaykasyanov** [comment]
@Koenkk looking good after almost 24 hours, thank you for the quick fix!
