### ISSUE TITLE
Xiaomi ZNCLDJ12LM curtain position and running status not reported live

### ISSUE THREAD

**Issue by jimtng** [Koenkk/zigbee2mqtt#3652]
Whenever I issued a close / open / position command to the [Xiaomi ZNCLDJ12LM](https://www.zigbee2mqtt.io/devices/ZNCLDJ12LM.html), Zigbee2mqtt would wait until the curtain motor has completed moving to the final requested position, before it then starts publishing the values all at once. 

So while the motor is moving, the position is not being reported, nor is "running" being reported. So I cannot check whether the motor is running or not.

So here's the sequence of events:

1.  the position is currently 100
2. send command to change position to 0
3. the motor will move the position to 0. This step takes several seconds to complete.
4.  once it has reached the position 0, and the motor has stopped moving, then
5.  zigbee2mqtt publishes the following all in one go, after the motor has stopped

```
zigbee2mqtt/masterbedroom-curtain {"position":2,"running":true,"linkquality":102,"last_seen":"2020-06-01T13:48:10.711Z"}
zigbee2mqtt/masterbedroom-curtain {"position":0,"running":true,"linkquality":99,"last_seen":"2020-06-01T13:48:10.716Z","elapsed":3}
zigbee2mqtt/masterbedroom-curtain {"position":0,"running":false,"linkquality":102,"last_seen":"2020-06-01T13:48:10.933Z","elapsed":218}
zigbee2mqtt/masterbedroom-curtain {"position":0,"running":false,"linkquality":105,"last_seen":"2020-06-01T13:48:11.161Z","elapsed":228}
```

It would be great if zigbee2mqtt can send the status "running: true" as soon as the motor started running, and sends "running: false" as soon as the motor stopped running. Periodic reporting of the motor's position while the motor is running would be great also.

Thank you!

**Comment by chris-chensy** [comment]
I wanted to add that the middle states (i.e., running:true) are not reflected in the HA entity attributes either.
