### ISSUE TITLE
Joining a hue bridge to the z2m network

### ISSUE THREAD

**Issue by alekslyse** [Koenkk/zigbee2mqtt#3654]
Would it be possible to join the hue bridge to the z2m network to be able to update the firmware of hue devices without having to move the bulbs over.

I see some had some success on deconz, but not sure how it works now

**Comment by alekslyse** [comment]
Or it seems like firmwares are now public. Can we use the firmwares on that site for its Philips in z2m

 https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions

**Comment by Koenkk** [comment]
- The hue bridge cannot join a z2m network
- Updating of Hue bulbs is already supported in the latest dev branch (for the ones we have a firmware for) https://www.zigbee2mqtt.io/information/ota_updates.html
