### ISSUE TITLE
zigbee2mqtt not working after migrating from raspberry pi to virtual box

### ISSUE THREAD

**Issue by echo4019** [Koenkk/zigbee2mqtt#3658]
Hi I've just moved Hassio over to a virtual machine after running it on a raspberry pi, my snapshot sucsessfully uploaded and everything is working except the zigbee2mqtt add on. 

getting the following error message in the log "zigbee2mqtt:error 2020-06-02 22:53:58: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'"

Any help appreciated.

**Comment by tricoos** [comment]
Well, did you virtualize the physical device - the Zigbee stick? Would this actually work? You need to be able to access the physical hardware here and probably have to change the device path.

**Comment by echo4019** [comment]
Yes that's what I thought. I've been looking for a guide to explain how to get the virtual machine to read the ZigBee stick plugged into the usb of the host pc?

**Comment by echo4019** [comment]
I installed Hassos on VirtualBox then restored my home assistant from a snapshot. What's the difference in using docker?

**Comment by bakerboy908** [comment]
Did you ever solver this issue, im trying to do the same with virtualbox, cant pass the usbthough so im trying to pass just the com port
