### ISSUE TITLE
 When will zigbee2mqtt update the version and use the latest version of the zigbee-herdsman-converters?

### ISSUE THREAD

**Issue by hyzgit** [Koenkk/zigbee2mqtt#3659]
When will zigbee2mqtt update the version and use the latest version of the zigbee-herdsman-converters?

**Comment by Koenkk** [comment]
The dev branch (almost always) points to the latest zigbee-herdsman-converters. https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html
