### ISSUE TITLE
Why is IKEA Tradfri LED1623G12 identified as type Router

### ISSUE THREAD

**Issue by tobang** [Koenkk/zigbee2mqtt#366]
When I pair the LED1623G12, it is added with type Router?

```
{"ieeeAddr":"0x000b57fffec2b95a","type":"Router","model":"LED1623G12","friendly_name":"PhLampe"}
```

Is this a bug? Maybe this is why I have trouble getting it to work through my CC2531 router. See #362 

Thank you

**Comment by Koenkk** [comment]
This is correct, all/most AC powered devices are routers: https://github.com/Koenkk/zigbee2mqtt/wiki/ZigBee-network#router

**Comment by alinelena** [comment]
sorry to comment on a closed issue..I am in the same situation all the ikea lights listed as routers.
is there a way to use them or disable them on will. (the router capability)

**Comment by Koenkk** [comment]
No that's not possible. But why would you want that?

**Comment by dirkclemens** [comment]
Dear @Koenkk but how can I switch a bulb, when it is recognized as a router? I would expect to send a mqtt message with a message like "on" to switch that bulb on (and off). Did I miss something?
