### ISSUE TITLE
Aqara QBKG12LM missing and false state reports after TOGGLE

### ISSUE THREAD

**Issue by pkedvessy** [Koenkk/zigbee2mqtt#3668]
Hi,

Sending a TOGGLE message to QBKG12LM is changing the physical state of the switch but
* there is no immediate status report as a feedback on the state change from the switch
* further status reports states the toggled switch in the state before the TOGGLE message

For instance:
* initial state of the left channel is OFF (by physical click)
* sending an MQTT message to the left channel with TOGGLE payload
* I'm expecting a status report with state_left ON but there is no any message from the switch
* after a while when the switch reports power consumption or the right channel gets physically clicked, state_left is shown as OFF meanwhile it's physical state is ON

I realized this issue after a couple of Zigbee2Mqtt update and after a coordinator firmware update so  I'm not sure about which update caused the issue.

Sending ON or OFF message (or physical clicks) are working as expected: status reports states the correct physical state of the switch both immediately and after a while as well.

Zigbee2Mqtt verision: 1.13.1
Coordinator: CC1352P_2 with firmware revision 20200417

Do you have any idea what's going wrong?

Thanks,
Peter

**Comment by Koenkk** [comment]
Fixed the issue in the latest dev branch, thanks for reporting! (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
