### ISSUE TITLE
New device support Lumi WS-USC01

### ISSUE THREAD

**Issue by poohbah** [Koenkk/zigbee2mqtt#3669]
Running latest hassio zigbee2mqtt-edge

Trying to add this newly released device:
https://www.aqara.com/us/smart_switch_no_neutral.html
Lumi WS-USC01
lumi.switch.b1laus01

The device is nearly identical to this device but a single rocker:
https://github.com/Koenkk/zigbee2mqtt/issues/3566

database.db entries:
{"id":8,"type":"EndDevice","ieeeAddr":"0x04cf8cdf3c75e34e","nwkAddr":51094,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.switch.b1laus01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,2,3,4,5,6,9],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.switch.b1laus01","manufacturerName":"LUMI","powerSource":1,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"07-23-2019"}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"07-23-2019","interviewCompleted":true,"meta":{},"lastSeen":1591317642073}

**Comment by Koenkk** [comment]
Added, will be supported in edge in a few hours.
