### ISSUE TITLE
Errors after a "clean" install Z2M will not start

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#3680]
Latest version
Odroid N2 with Domoticz latetst beta.

After a brute force some problems with log and therefore with memory. Unstable system and now a bit working again.

But I can no longer get the z2m up and running.

Backup made and everything removed.
Put back what is needed ...
But on a reboot:
`
> zigbee2mqtt@1.13.1 start /opt/zigbee2mqtt
> node index.js

zigbee2mqtt:info  2020-06-06 14:47:07: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-06-06.14-47-07' filename: log.txt
zigbee2mqtt:info  2020-06-06 14:47:07: Starting zigbee2mqtt version 1.13.1 (commit #2cb234c)
zigbee2mqtt:info  2020-06-06 14:47:07: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-06-06 14:47:07: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-06-06 14:47:07: Failed to start zigbee
zigbee2mqtt:error 2020-06-06 14:47:07: Exiting...
zigbee2mqtt:error 2020-06-06 14:47:07: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.open (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/database.js:17:35)
    at Controller.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:91:48)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.13.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.13.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-06T12_47_07_649Z-debug.log
pi@odroidn2:/opt/zigbee2mqtt$ ^C
pi@odroidn2:/opt/zigbee2mqtt$
`

The log:  also something with unsafe?
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.13.1~prestart: zigbee2mqtt@1.13.1
6 info lifecycle zigbee2mqtt@1.13.1~start: zigbee2mqtt@1.13.1
7 verbose lifecycle zigbee2mqtt@1.13.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.13.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.13.1~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.13.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.13.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.13.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.13.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zigbee2mqtt@1.13.1
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.6.15-meson64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.13.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.13.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
Hope you can help me.

**Comment by Koenkk** [comment]
I think the database is corrupted, try removing data/database.db

**Comment by Dylantje** [comment]
When i remove the DB 
All the devices are gone?

**Comment by Koenkk** [comment]
Yes, you can also post it here, maybe it's possible to fix it manually.

**Comment by Dylantje** [comment]
mmm try to open mwith sql lite expert.. still get an error..
[database.zip](https://github.com/Koenkk/zigbee2mqtt/files/4741997/database.zip)

**Comment by Koenkk** [comment]
It is a text file, so should be able to open in any text editor. However it appears to be corrupted. In case you don't have a backup the only way forward is to repair all devices.

**Comment by Dylantje** [comment]
ok. text is opening without any problem..
with notepad i see the fil.
What are my option to check if corrupt?

**Comment by Dylantje** [comment]
i see differents between the fist db and this one.
[database 1-6-2020.zip](https://github.com/Koenkk/zigbee2mqtt/files/4742022/database.1-6-2020.zip)

What can i remove in this file? i see a lot data that is not a device?
id 44 as example... looks to my not a device?

**Comment by Koenkk** [comment]
Can you try restoring just the `database.db` file from that zip? Looks fine (although there are a lot of duplicated which you can remove without problems, not sure how they ended up there).

**Comment by Dylantje** [comment]
Thanks Koenk!!! A live again....

I try to play with the db to get the doubles out of this db...

Offtopic only ...:-)
How can i remove a device?
Try a lot of things..
Remove from the db  and replace that db a option?

**Comment by Dylantje** [comment]
hi strange other problem..
when there is a reboot, the system runs for a lot of time... everything looks working fine.
Only then z2m is working not any more, and i see this:
![ScreenShot305](https://user-images.githubusercontent.com/5214969/83994474-d4299d00-a956-11ea-8d98-3a937bf693c1.png)
Perhaps an idea?

**Comment by Koenkk** [comment]
For removing see https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove

Can you provide the debug logging when executing the network scan?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by Dylantje** [comment]
@Koenkk 

Look that my zram is getting full because z2m logging.
There is a logging into the syslog .. when that log is full, my odroid is instable...

I did follow the wiki.. So did not change some settings.

So where it is going wrong...
[syslog.zip](https://github.com/Koenkk/zigbee2mqtt/files/4765761/syslog.zip)
