### ISSUE TITLE
IKEA TRADFRI LED1546G12 State problem

### ISSUE THREAD

**Issue by mredone** [Koenkk/zigbee2mqtt#369]
Hello.
I have problem with state info in Home Assistant with this led bulb
Everything works almost fine.
I can turn on/off change brightness and color temp.
But. When i turn off lamp with this bulb (power switch off on lamp) Home assistant don't update state of bulb and it remains on.
And when i try turn off it from HA dashboard, switch back to on possition
Is any method to get a real state of bulb.

I use code from Wiki to integrate it to HA

**Comment by mredone** [comment]
Here log

https://pastebin.com/4K1sJeMY

**Comment by mredone** [comment]
I have a big problem with debug log.
When i add `log_directory: /var/log/` bridge not start correctly.
When i delete it, everything work

**Comment by Koenkk** [comment]
When you turn off the bulb using the power switch the bulbs doesn't sends it power state. 

The toggle doesn't switch in home assistant because zigbee2mqtt cannot control the bulb anymore.

**Comment by mredone** [comment]
Ok. So maybe it must be change?
If zigbee2mqtt bridge lost connection to bulb, or other sensor, is any chance to send to mqtt status for this bulb/sensor `disconnected`

**Comment by Koenkk** [comment]
I don't know if this is possible. Must look into it.

**Comment by nismanoke** [comment]
I Would like to have this supported as well. I have physical switches in the bedrooms to turn off the ikea bulbs. Would be nice to have the status changed to unavailable or off in home assistant. Had this automated before with hue. When bulbs where unavailable for x min a automation turned off the bulb and group of those bulbs.

**Comment by ciotlosm** [comment]
@Koenkk I know Tasmota implements telemetry on a state topic and HA can use that in the setup (https://www.home-assistant.io/components/switch.mqtt/#state_topic) to determine if a device becomes unavailable. Maybe something similar could be developed here as enhancement. I don't have full picture on the complete flow but I know i've seen this with my sonoff tasmota switches.

**Comment by Koenkk** [comment]
@ciotlosm yes for sure! The problem for now is; how to determine if a device is online/offline?
