### ISSUE TITLE
 Philips Hue and zigbee2mqtt  - ZLL or ZHA profile?

### ISSUE THREAD

**Issue by alan-rpi** [Koenkk/zigbee2mqtt#3695]
New installation
Raspberry Pi 4 running Buster
Running Docker
Downloaded latest zigbee2mqtt image
Adapter USB CC2531 Sniffer https://www.ebay.co.uk/itm/CC2531-CC2540-Sniffer-Protocol-Analyzer-Dongle-BTool-USB-Downloader-for-Zigbee/372750849759 (ebay link)
Adapter firmware version: 0100 CC2531 CC Debugger 05CC 0041
Adapter Sniffer flashed with zigbee2mqtt firmware version 1.13.1
zigbee2mqtt:info 2020-06-07 19:18:51: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}',

This is more a possible potential issue

I have a Philips Hue Bridge and a number of bulbs but due to domestic issues (!) the Bridge is only on when we are on holiday.

Having just installed zigbee2mqtt I have noticed in the configuration file that the bulbs have been paired. 

Now, earlier today I read that Philips Hue uses ZLL profile and in a SmartThings network the bulbs  switch to ZHA and then the bulbs no longer work with the Hue Bridge. 

Could you please confirm if something similar happens with zigbee2mqtt?

Thanks
Alan

PS In due course I hope to control them via my Domoticz system and zigbee2mqtt (at least while on holiday) but may decide that domestically the answer is to switch to zigbee wall switches and use ordinary LED bulbs, but I've yet to find affordable UK no neutral wall switches plus I need to prove the stability and workability of my new set up.

**Comment by Koenkk** [comment]
I'm not aware of this. However I know for sure that you can repair bulbs to the Hue bridge after having them paired to Zigbee2mqtt (and vice versa, have done this multiple times).
