### ISSUE TITLE
Please add an alias for Flex Outdoor RGBW

### ISSUE THREAD

**Issue by basriram** [Koenkk/zigbee2mqtt#3699]
This is the same device as the Sylvania Outdoor Flex RGBW light strip but advertises as "Flex Outdoor RGBW". I have added this in my devices.js and it works great, even firmware update works fine -

    {
        zigbeeModel: ['Flex Outdoor RGBW'],
        model: '44891056853',
        vendor: 'OSRAM',
        description: 'Flex RGBW',
        extend: osram.light_onoff_brightness_colortemp_colorxy,
        ota: ota.ledvance,
    }

**Comment by Koenkk** [comment]
Added, will be supported in the latest dev branch  in a few hours.
