### ISSUE TITLE
Please modify Sylvania Lightify BR30 RGBW device

### ISSUE THREAD

**Issue by basriram** [Koenkk/zigbee2mqtt#3700]
The BR30 RGBW entry does is missing the ota attribute. As it is an ledvance device, adding "ota: ota.ledvance" helped me update all my bulb's firmware. I also changed the generic extender to use osram instead and it works fine.

    {
        zigbeeModel: ['LIGHTIFY BR RGBW', 'BR30 RGBW'],
        model: '73739',
        vendor: 'Sylvania',
        description: 'LIGHTIFY LED RGBW BR30',
        extend: osram.light_onoff_brightness_colortemp_colorxy,
        ota: ota.ledvance,
    },

**Comment by Koenkk** [comment]
Done (for all Sylvania bulbs), will be available in the dev branch in a few hours.
