### ISSUE TITLE
Setting 'colortemp_move' on group

### ISSUE THREAD

**Issue by knieschm** [Koenkk/zigbee2mqtt#3705]
# Bug Report
## What happened
If setting 'colortemp_move' on group of Ikea bulbs (e.g. 3x LED1537R6) zigbee2mqtt outputs 'No converter avaible for 'colortemp_move'. If setting the same attribute on a single bulb, there is no error message.
## What did you expect to happen
The color temperature of all lightbulbs in the group is changing until 'stop'-message is received. I expected the same behavior as for 'brightness_move'.
## How to reproduce it (minimal and precise)
Set 'colortemp_move' to e.g. '-20' on a group.
## Debug Info
Zigbee2mqtt version: 1.13.1
Adapter hardware: CC1352P-2
Adapter firmware version: 20200417

**Comment by Koenkk** [comment]
Fixed in latest dev branch.
