### ISSUE TITLE
Example for how configuration.yaml supports "device type specific" config?

### ISSUE THREAD

**Issue by kiddyfurby** [Koenkk/zigbee2mqtt#3708]
I was excited to read that `configuration.yaml` [supports "Device type specific" config](https://www.zigbee2mqtt.io/information/configuration.html#device-specific-configuration).

Could an example be provided to illustrate how the JSON style config should be translated into yaml?

For instance, the QBKG12LM has a [decoupled mode](https://www.zigbee2mqtt.io/devices/QBKG12LM.html#decoupled-mode).
How should one translate the mqtt topic `zigbee2mqtt/[FRIENDLY_NAME]/system/set` and the payload
```
{
  "operation_mode": {
    "button": "left",
    "state": "decoupled"
  }
}
```
into `configuration.yaml` entries so that the decouple options are initialized automatically upon (re-)pairing?

**Comment by Koenkk** [comment]
The decoupled mode is not a device specific configuration but rather a command you can send to this device. You should use an MQTT client to send this message.
