### ISSUE TITLE
Failed to enable unit: "multi-user.targe" is not a valid unit name.

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#3709]
Last beta Domoticz
Odroid N2 with latest armbian

Everthing looks running fine.
Until i will set:
` sudo systemctl enable zigbee2mqtt.service
`
I get this strange error?
`Failed to enable unit: "multi-user.targe" is not a valid unit name.
`
Did use google.
No thing found for this strange thing
Pi user does have sudo options
Only error with this command

z2m is running..

**Comment by Koenkk** [comment]
Probably you forgot to copy the last character a **t** (multi-user.target). See https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#5-optional-running-as-a-daemon-with-systemctl

**Comment by hctru68** [comment]
Thank you so much,
That link is useful for me. I fixed this bug by that link.
