### ISSUE TITLE
Kwikset 99140-005 (Control4) Pairing

### ISSUE THREAD

**Issue by srb37** [Koenkk/zigbee2mqtt#3711]
# Bug Report
## What happened
I am unable to pair the Kwikset 99140-005 which is the Control4 Zigbee variant of the of the Kwikset lock.  

I've updated devices.js with the following code, largely a copy/paste from SMARTCODE_DEADBOLT_10 with zigbeeModel changed to Smartcode and the addition of fz.ignore_basic_report to deal with some errors I was receiving.
`{
        zigbeeModel: ['Smartcode'],
        model: '9GED18000-C4',
        vendor: 'Weiser',
        description: 'SmartCode 10',
        supports: 'lock/unlock, battery',
        fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery, fz.ignore_basic_report],
        toZigbee: [tz.generic_lock],
        meta: {configureKey: 3},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(2);
            await bind(endpoint, coordinatorEndpoint, ['closuresDoorLock', 'genPowerCfg']);
            await configureReporting.lockState(endpoint);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
    },
`

The lock seems to successfully join, interview and pair, however immediately leaves the network never to be heard from again.  Debug information found below (MAC Address changed to KWIKSETMAC):
`zigbee2mqtt:info  2020-06-10 14:29:38: Device '0xKWIKSETMAC' joined
zigbee2mqtt:info  2020-06-10 14:29:38: Starting interview of '0xKWIKSETMAC'
zigbee2mqtt:info  2020-06-10 14:29:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xKWIKSETMAC"}}'
zigbee2mqtt:info  2020-06-10 14:29:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xKWIKSETMAC"}}'
zigbee2mqtt:debug 2020-06-10 14:29:38: Device '0xKWIKSETMAC' announced itself
zigbee2mqtt:info  2020-06-10 14:29:38: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0xKWIKSETMAC"}}'
zigbee2mqtt:debug 2020-06-10 14:29:38: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"modelId":"Smartcode"}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:38: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Kwikset"}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"appVersion":16}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{"hwVersion":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-10 14:29:39: Received Zigbee message from '0xKWIKSETMAC', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
zigbee2mqtt:info  2020-06-10 14:29:40: Successfully interviewed '0xKWIKSETMAC', device has successfully been paired
zigbee2mqtt:info  2020-06-10 14:29:40: Device '0xKWIKSETMAC' is supported, identified as: Weiser SmartCode 10 (9GED18000-C4)
zigbee2mqtt:info  2020-06-10 14:29:40: Configuring '0xKWIKSETMAC'
zigbee2mqtt:info  2020-06-10 14:29:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xKWIKSETMAC","model":"9GED18000-C4","vendor":"Weiser","description":"SmartCode 10","supported":true}}'
zigbee2mqtt:info  2020-06-10 14:29:40: Successfully configured '0xKWIKSETMAC'
zigbee2mqtt:debug 2020-06-10 14:29:41: Received Zigbee message from '0xKWIKSETMAC', type 'attributeReport', cluster 'closuresDoorLock', data '{"lockState":2}' from endpoint 2 with groupID 0
zigbee2mqtt:info  2020-06-10 14:29:41: MQTT publish: topic 'zigbee2mqtt/0xKWIKSETMAC', payload '{"state":"UNLOCK","linkquality":99,"battery":80}'
zigbee2mqtt:warn  2020-06-10 14:29:45: Device '0xKWIKSETMAC' left the network
zigbee2mqtt:info  2020-06-10 14:29:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0xKWIKSETMAC"}}'
`
For the purposes of testing I've located CC2531 right next to the lock.  

## What did you expect to happen
I also have a Kwikset 99140-008 which is the non-Control4 Zigbee varient of the lock.  It works just fine-no issues. 

## How to reproduce it (minimal and precise)
1. Edit devices.js with the changes listed above.
2. Start zigbee2mqtt with permit_join set to true.
3. Initiate pairing on the lock by pressing the A button 4 times.

## Debug Info
Zigbee2mqtt version: 1.13.1 (commit #2cb234c)
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
Can you do a sniff while pairing the device? (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by srb37** [comment]
I don't have another CC2531 to use as a sniffer.  I've ordered one and will try when it comes it.  If I can figure out the Control4 zigbee encryption key I'll also try to sniff the traffic to and from the Control4 controller.  I'm wondering if perhaps the lock is looking for some sort of extra confirmation from the controller to know that it should continue to stay paired.

**Comment by Koenkk** [comment]
Yes probably, I've fixed such cases earlier but it requires a sniff to determine what has to be changed. If you use the default Zigbee2mqtt network key the used keys are listed on the how to.

**Comment by srb37** [comment]
I found a viable work around for anyone else that comes across this issue.  Amazon sells the  [Kwikset 99140-110 Convert Smart Lock Conversion Kit - Amazon Key Edition](https://www.amazon.com/dp/B072NCJTNG/ref=cm_sw_em_r_mt_dp_U_m074EbYT2DSX8).  You can find less popular colors and used / open box versions cheap on their website.  I was able to swap the Zigbee chip from the 99140-110 into my 99140-005 and everything then worked perfectly.  It paired as a SMARTCODE_DEADBOLT_10_L.  I did receive some _"No converter available for '99140-002' with cluster 'genBasic' and type 'readResponse' and data"_ errors, but they were easily corrected by adding **fz.ignore_basic_report** to **devices.js**.  Not a perfect solution as it requires spending a little bit of money, but for those with existing Kwikset Control4 Zigbee locks this provides a viable option until the other issue is fixed.

**Comment by srb37** [comment]
I was able to sniff a successful pairing between my Control4 zigbee controller and the lock.  Does this give you what you need to help troubleshoot or do you need me to sniff the failed attempt with Zigbee2MQTT?

[C4ZigbeePairing.zip](https://github.com/Koenkk/zigbee2mqtt/files/4827291/C4ZigbeePairing.zip)

**Comment by Koenkk** [comment]
> or do you need me to sniff the failed attempt with Zigbee2MQTT

Can you also do this, this will make the comparison much easier.

**Comment by dseven** [comment]
So I'm trying, unsuccessfully. to get a 99140-111 / 914 ZB-AMZ CONVERT 15 to pair with a CC2531 with Z2M. AFAICT, this is the same as the 99140-110 mentioned above, just the case is a different colour (brass vs. nickel). These are the only ZB devices I have, so I'm not sure if one or the other is defective. Could someone tell me what the pairing process looks like? I'm suppose to push the 'A' button 4 times. When I do this, there's an orange LED that lights with each push, and a red LED that lights with the fourth push, then nothing else happens. Is this normal? I'm wondering if I should see further LED blinks as it tries to pair?

I think my next step will be to reflash my CC2531 with sniffer firmware, to see it I can see any traffic, but was hoping to confirm the expected LED behaviour of the lock when attempting to pair....?

**Comment by srb37** [comment]
The 99140-111 should pair, as you pointed out the only should be the color.  The button/color sequence you described is correct.  You will not see any additional lights indicating pairing in progress or successful pairing--you'll need to look at your Z2M logs.   

One thing you may want to try is putting the CC2531 right next to the lock--when I was doing the initial pairing I would actually pretty much touch it to the lock.  Once it was paired I could move the CC2531 elsewhere and also rely on some of the other devices to form the mesh, but for some reason that initial pairing never seemed to work unless the CC2531 was super close.  
One other thing you can try is pressing the B button 9 times to generate a disconnect message--not sure if that helped but I would always try that the reset everything.

For anyone else coming across this thread, as for my 99140-005 I wound up selling the chip on eBay for more money than it cost me to buy the 99140-110 so never got another change to do additional testing.

**Comment by dseven** [comment]
Thanks @srb37, particularly for the confirmation on the LED expectation. I have already tried all of the things you suggest (plus a full factory reset of the lock), but never see anything in the Z2M logs to indicate it has received anything from anyone. I'm increasingly suspecting that my CC2531 is deaf.

**Comment by schester44** [comment]
I'm having a similar issue... in z2m i'm seeing the following in zigbee2mqtt/bridge/log

```
{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x002446fffd080eee"}}
```

but thats it ... is there a step by step on how to get these SmartCode locks to join the network?
