### ISSUE TITLE
gyp WARN EACCES user "matthijs" does not have permission to access the dev dir "/home/root/.node-gyp/

### ISSUE THREAD

**Issue by matthijsfh** [Koenkk/zigbee2mqtt#3714]
Hello,

Currently running 1.10.0 and trying to upgrade. Followed the upgrade instructions on the website but ended up with a total mess.

The above message is not an exact copy, I closed the terminal with the error by accident, but it is very close. I am running the upgrade as root and it complains that the "normal user" matthijs (which is my normal account) cannot access the node-gyp cache. 

Solution according google seems to be adding "--unsafe-perm". Then things work better. 

But still no working bridge. It seems the 1.10 version is using an older gyp version or so. 

**--> Please provide a clear instuction how to do a total clean install of zigbee2mqtt. The website upgrade script used to work, but I think it would be usefull to have same sort of options for a clean install? Or am I overlooking something?** 

"npm ci" does not seem to do the job. 

Thanks,
Matthijs

**Comment by Koenkk** [comment]
- A possible solution can be found here: https://stackoverflow.com/questions/29468404/gyp-warn-eacces-user-root-does-not-have-permission-to-access-the-dev-dir
- For a clean install of zigbee2mqtt, remove `/opt/zigbee2mqtt` and reflash your stick.
