### ISSUE TITLE
Syslog type should be a string

### ISSUE THREAD

**Issue by MPM1107** [Koenkk/zigbee2mqtt#3725]
Just solved an issue someone on the discord was having. His z2m was crashing when he tried using the new syslog feature.

His config and log:
https://pastebin.com/6tMkKgN8
https://pastebin.com/xCTCkejK

Turns out that the type being set to 5424 was breaking it, because match() only works on strings, so setting it to '5424' fixed the issue. So this should either be clearly stated in the documentation, or some code should be added to cast the int to a string.

**Comment by Koenkk** [comment]
Fixed in latest dev branch, thanks for helping out!
