### ISSUE TITLE
Devices unavailable on Home Assistant restart

### ISSUE THREAD

**Issue by toxuin** [Koenkk/zigbee2mqtt#3740]
# Bug Report
## What happened

Upon restarting Home Assistant, devices' availability is not updated.

Home Assistant has `will_message` and `birth_message` set and I can see those being sent and received in zigbee2mqtt logs too.

Here's a snippet from Home Assistant's config:
```yaml
mqtt:
  ...
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```

Here is my [zigbee2mqtt config](https://hasteb.in/ifanohod.yaml)

Here are [the logs](https://hasteb.in/ihexabuk.log) with debug enabled.

I've been able to trace this to the [related code](https://github.com/Koenkk/zigbee2mqtt/blob/9009de24aca1027283bfbfbe399f9071254184db/lib/extension/homeassistant.js#L2068), but it does not seem like there is anything there that would re-send availability information (this, or I have not enough knowledge on the zigbee2mqtt architecture).

Please tell me what am I doing wrong as something as simple as this would probably catch attention of wise humans before me. Any help would be appreciated.

## What did you expect to happen

When Home Assistant comes back online, zigbee2mqtt would re-publish the availability state of devices.

## How to reproduce it

- start homeassistant
- start zigbee2mqtt
- wait for devices to become available in HA
- In HA, click "restart Home Assistant"
- watch home assistant publish `online` to `hass/status` and count to 30
- watch zigbee2mqtt logs to see re-publish devices' state (light levels and on/off state), but not availability
- in HA, zigbee devices are unavailable

## Debug Info
Zigbee2mqtt version: docker image `latest-dev`, `imagePullPolicy: always`
Adapter hardware: CC1352P2 over tcp socket on esp8266 (most likely irrelevant)
Adapter firmware version: `20200417`

**Comment by Koenkk** [comment]
Availability message are send with the retained flag and therefore don't have to be send again.

@emontnemery is there a way to debug received Home Assistant MQTT messages?

**Comment by emontnemery** [comment]
Sure (example from a Tasmota device):
![image](https://user-images.githubusercontent.com/14281572/84591111-07c76400-ae3c-11ea-9669-2001e9c9b2e0.png)
![image](https://user-images.githubusercontent.com/14281572/84591123-2594c900-ae3c-11ea-8546-889bedc246b8.png)

**Comment by toxuin** [comment]
I can see HA receiving the messages with `retain: true`, and received instantly after I subscribe to it (= broker's retain is working fine):

<img width="533" alt="Screenshot 2020-06-14 at 12 35 40 PM" src="https://user-images.githubusercontent.com/868268/84601219-e5354b00-ae3b-11ea-98a7-a81fbf19e8e4.png">

But in HA, after a restart, my devices are still greyed out:
<img width="350" alt="Screenshot 2020-06-14 at 12 39 28 PM" src="https://user-images.githubusercontent.com/868268/84601263-19107080-ae3c-11ea-9c51-0f1625f5c294.png">
Weirdly enough, when I click "MQTT INFO" for any zigbee device in HA, I get an empty list. Tasmota devices, on the other hand (wifi-only, not tasmota-zigbee) are fine and have content in it (exactly as @emontnemery posted before).

Here's what zigbee2mqtt device's MQTT INFO card looks like:

<img width="439" alt="Screenshot 2020-06-14 at 12 40 11 PM" src="https://user-images.githubusercontent.com/868268/84601325-82907f00-ae3c-11ea-9dc3-7c63c15f3581.png">

It all goes back to normal when I restart the zigbee2mqtt pod.

Is it a bug with Home Assistant? Seems like it can't detect what device even is and what it's availability topics are.

And hey, thanks a lot for looking into this. I am kind of lost and exhausted all sane options (switched brokers, tried various zigbee2mqtt versions, reflashed coordinator and connected it directly). I really appreciate your support!

**Comment by emontnemery** [comment]
Can you attach a home assistant log including all steps needed to reproduce (start + restart of HA) with MQTT debug enabled please? Have you configured client_id in HAs MQTT settings?

**Comment by toxuin** [comment]
Yes, `client_id` is set to be `homeassistant-core` in Home Assistant configuration.

Here is the very verbose [log of home assistant](https://gist.github.com/toxuin/6ea942000ff12da55d061de91cfa4680) with mqtt in debug mode. I tried to annotate it to the best of my ability.

Thanks!

**Comment by emontnemery** [comment]
The problem is not the availability, the problem is that the zigbee2mqtt devices aren't discovered until you restart zigbee2mqtt.

Tasmota retains the discovery messages, I don't think zigbee2mqtt does that, instead you need to setup zigbee2mqtt to send discovery messages when HA starts.

@Koenkk can you confirm this is the case?

**Comment by toxuin** [comment]
yes, I can see zigbee2mqtt pick up the HA's birth message. You can see it in the [logs](https://hasteb.in/ihexabuk.log) I've posted before:

` 2020-06-14 07:58:06: Received MQTT message on 'hass/status' with data 'online'`

Then, it proceeds to send the state messages.

**Comment by emontnemery** [comment]
It's not enough to send the state messages, it needs to send the discovery messages like this:
```
2020-06-14 19:09:50 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/sensor/0xd0cf5efffeda1b65/battery/config: b'{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee/On_Off_Remote","json_attributes_topic":"zigbee/On_Off_Remote","name":"On_Off_Remote_battery","unique_id":"0xd0cf5efffeda1b65_battery_zigbee","device":{"identifiers":["zigbee2mqtt_0xd0cf5efffeda1b65"],"name":"On_Off_Remote","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"TRADFRI ON/OFF switch (E1743)","manufacturer":"IKEA"},"availability_topic":"zigbee/On_Off_Remote/availability"}'
2020-06-14 19:09:50 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor 0xd0cf5efffeda1b65 battery
```

**Comment by emontnemery** [comment]
Just to be sure, does the behavior change if you don't set `client_id` in HA's config?

**Comment by toxuin** [comment]
Same behaviour when I comment out `client_id` in HA's config.

Here's what I see in [zigbee2mqtt log](https://gist.github.com/toxuin/98188f06bafa0a347ef6f9ef38ae5134) after 30 seconds after HA sends its' birth message.

**Comment by emontnemery** [comment]
Right, so there's no log of discovery messages sent as a result of receiving the birth message from HA.

**Comment by toxuin** [comment]
Is it something in my configuration or is it a bug in zigbee2mqtt? Thanks for looking into this.

**Comment by emontnemery** [comment]
Something may be wrong in your configuration.

Tasmota publishes it's discovery messages with retain flag set, and based on the code, so does zigbee2mqtt (I thought it doesn't, my mistake): https://github.com/Koenkk/zigbee2mqtt/blob/9009de24aca1027283bfbfbe399f9071254184db/lib/extension/homeassistant.js#L2052

However, HA receives the discovery messages *without* the retain flag set.

**Comment by toxuin** [comment]
When I subscribe to this topic from desktop client MQTT.fx (`homeassistant/sensor/0xd0cf5efffeda1b65/battery/config`) I get an instant message delivery with all the contents that indicate the message was sent with retained flag. I can also see this in Home Assistant:

<img width="355" alt="Screenshot 2020-06-15 at 10 42 26 AM" src="https://user-images.githubusercontent.com/868268/84683772-f2624080-aef4-11ea-8f00-ea5ff2102842.png">

Seems like zigbee2mqtt is indeed sending the discovery message properly, but Home Assistant is failing to pick it up.

**Comment by emontnemery** [comment]
OK, and what if you subscribe to `homeassistant/#` ?

**Comment by toxuin** [comment]
Nothing! Is that it? I don't get the retained messages when I subscribe to `homeassistant/#`.

Can it be my broker? I am using RabbitMQ with MQTT plugin with `rabbit_mqtt_retained_msg_store_ets` store.

**Comment by emontnemery** [comment]
Right, so this issue can be closed then.
I'd suggest to use mosquitto for broker btw, it for sure won't let you down by not supporting basic functionality.

**Comment by toxuin** [comment]
Thank you very much for looking into this!
