### ISSUE TITLE
configuration.yaml edit problem

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#3741]
Hello, I'm using the last version of z2m and have a little problem.

If I expand the configuration.yaml, z2m no longer starts, if I write back, it works again.
What am I doing wrong?

thats how it works:

`

- homeassistant: false
- permit_join: true
- mqtt:
-   base_topic: zigbee2mqtt
-   server: 'mqtt://localhost'
- serial:
-   port: /dev/ttyACM0
- devices:
-   '0x00178801086412ee':
-     friendly_name: '0x00178801086412ee'
- groups: {}

`

and this is not how it works:

`

- homeassistant: false
- permit_join: true
- mqtt:
-   base_topic: zigbee2mqtt
-   server: 'mqtt://localhost'
- serial:
-   port: /dev/ttyACM0
- devices:
-   '0x00178801086412ee':
-     friendly_name: '0x00178801086412ee'
- groups: {}
- advanced:
- pan_id: 0x1b63
- ext_pan_id: [0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF, 0xDG, 0xDH]
- channel: 20
- cache_state: true
- log_level: info
- log_directory: data/log/%TIMESTAMP%
- log_file: log.txt
- log_rotation: true
- log_output:
-     - console
-     - file
- rtscts: true
- soft_reset_timeout: 0
- network_key: [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]
- availability_blacklist:
-     - DEVICE_FRIENDLY_NAME or DEVICE_IEEE_ADDRESS
- 	availability_whitelist:
-     - DEVICE_FRIENDLY_NAME or DEVICE_IEEE_ADDRESS
- report: true
- timestamp_format: 'YYYY-MM-DD HH:mm:ss'
- experimental:
- output: 'json'
- map_options:
- graphviz:
- colors:
- fill:
-         enddevice: '#fff8ce'
-         coordinator: '#e04e5d'
-         router: '#4ea3e0'
- font:
-         coordinator: '#ffffff'
-         router: '#ffffff'
-         enddevice: '#000000'
- line:
-         active: '#009900'
-         inactive: '#994444'
- device_options: {}

`
`pi@raspberrypi:~ $ sudo journalctl -u zigbee2mqtt.service -f
-- Logs begin at Sat 2020-06-13 14:00:18 CEST. --
Jun 14 10:23:18 raspberrypi systemd[1]: Stopping zigbee2mqtt...
Jun 14 10:23:18 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=killed, status=15/TERM
Jun 14 10:23:18 raspberrypi npm[817]: zigbee2mqtt:info  2020-06-14 10:23:18: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
Jun 14 10:23:18 raspberrypi npm[817]: zigbee2mqtt:info  2020-06-14 10:23:18: Disconnecting from MQTT server
Jun 14 10:23:18 raspberrypi npm[817]: zigbee2mqtt:info  2020-06-14 10:23:18: zigbee-herdsman stopped
Jun 14 10:23:18 raspberrypi systemd[1]: zigbee2mqtt.service: Succeeded.
Jun 14 10:23:18 raspberrypi systemd[1]: Stopped zigbee2mqtt.
Jun 14 10:23:26 raspberrypi systemd[1]: Started zigbee2mqtt.
Jun 14 10:23:28 raspberrypi npm[2201]: > zigbee2mqtt@1.14.0 start /opt/zigbee2mqtt
Jun 14 10:23:28 raspberrypi npm[2201]: > node index.js
Jun 14 10:23:30 raspberrypi npm[2201]: /opt/zigbee2mqtt/lib/util/logger.js:12
Jun 14 10:23:30 raspberrypi npm[2201]: const output = settings.get().advanced.log_output;
Jun 14 10:23:30 raspberrypi npm[2201]:                                       ^
Jun 14 10:23:30 raspberrypi npm[2201]: TypeError: Cannot read property 'log_output' of null
Jun 14 10:23:30 raspberrypi npm[2201]:     at Object.<anonymous> (/opt/zigbee2mqtt/lib/util/logger.js:12:39)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
Jun 14 10:23:30 raspberrypi npm[2201]:     at require (internal/modules/cjs/helpers.js:72:18)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Object.<anonymous> (/opt/zigbee2mqtt/lib/mqtt.js:2:16)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jun 14 10:23:30 raspberrypi npm[2201]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! code ELIFECYCLE
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! errno 1
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! zigbee2mqtt@1.14.0 start: `node index.js`
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! Exit status 1
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR!
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! Failed at the zigbee2mqtt@1.14.0 start script.
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR! A complete log of this run can be found in:
Jun 14 10:23:30 raspberrypi npm[2201]: npm ERR!     /home/pi/.npm/_logs/2020-06-14T08_23_30_077Z-debug.log
Jun 14 10:23:30 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 10:23:30 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Jun 14 10:23:30 raspberrypi systemd[1]: zigbee2mqtt.service: Service RestartSec=100ms expired, scheduling restart.
Jun 14 10:23:30 raspberrypi systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 1.
Jun 14 10:23:30 raspberrypi systemd[1]: Stopped zigbee2mqtt.
Jun 14 10:23:30 raspberrypi systemd[1]: Started zigbee2mqtt.
Jun 14 10:23:31 raspberrypi npm[2229]: > zigbee2mqtt@1.14.0 start /opt/zigbee2mqtt
Jun 14 10:23:31 raspberrypi npm[2229]: > node index.js
Jun 14 10:23:33 raspberrypi npm[2229]: /opt/zigbee2mqtt/lib/util/logger.js:12
Jun 14 10:23:33 raspberrypi npm[2229]: const output = settings.get().advanced.log_output;
Jun 14 10:23:33 raspberrypi npm[2229]:                                       ^
Jun 14 10:23:33 raspberrypi npm[2229]: TypeError: Cannot read property 'log_output' of null
Jun 14 10:23:33 raspberrypi npm[2229]:     at Object.<anonymous> (/opt/zigbee2mqtt/lib/util/logger.js:12:39)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
Jun 14 10:23:33 raspberrypi npm[2229]:     at require (internal/modules/cjs/helpers.js:72:18)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Object.<anonymous> (/opt/zigbee2mqtt/lib/mqtt.js:2:16)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jun 14 10:23:33 raspberrypi npm[2229]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! code ELIFECYCLE
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! errno 1
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! zigbee2mqtt@1.14.0 start: `node index.js`
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! Exit status 1
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR!
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! Failed at the zigbee2mqtt@1.14.0 start script.
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR! A complete log of this run can be found in:
Jun 14 10:23:33 raspberrypi npm[2229]: npm ERR!     /home/pi/.npm/_logs/2020-06-14T08_23_33_625Z-debug.log
Jun 14 10:23:33 raspberrypi systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Jun 14 10:23:33 raspberrypi systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Jun 14 10:23:33 raspberrypi systemd[1]: zigbee2mqtt.service: Service RestartSec=100ms expired, scheduling restart.
Jun 14 10:23:33 raspberrypi systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 2.
Jun 14 10:23:33 raspberrypi systemd[1]: Stopped zigbee2mqtt.
`

**Comment by MPM1107** [comment]
Could you post your config file in a way that is a bit more readable? Like this it's impossible to see whether your formatting is correct or not. Preferably you should use a service like pastebin or hastebin to paste the config and then just post the link to the paste in here. From what I can see you don't have the required indentations in the yaml.

**Comment by salopette** [comment]
https://pastebin.com/aQ7b6w7q

**Comment by MPM1107** [comment]
As I suspected, your indentations are pretty messed up. Check this page carefully: [configuration](https://www.zigbee2mqtt.io/information/configuration.html) and look at the indentation levels (number of spaces before each option)

Just one example, but you have many errors like this one in your config, so make sure the check the whole file:

Your config:
```yaml
experimental:
output: 'json'
```

Should be:
```yaml
experimental:
  output: 'json'
```

**Comment by salopette** [comment]
I thought spaces didn't matter.
