### ISSUE TITLE
Brightness problem hue

### ISSUE THREAD

**Issue by Hydci** [Koenkk/zigbee2mqtt#3744]
I open a new issue to report the rest of my message the fix for the last message works for the Aqara and Ikea bulb range but the HUE range has the same problem as before the percentage is not retained after reboot
https://github.com/Koenkk/zigbee2mqtt/issues/3736#issuecomment-643783670

**Comment by Koenkk** [comment]
I've tested with a Hue white bulb but it works fine for me. Can you provide debug logging?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by Hydci** [comment]
Hello @Koenkk ,
Here is the log file as requesting the test light was 0x0017880104a1d8be
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/4781859/log.txt)
handling for the test:
reboot
We
set%
off
we
off

**Comment by Koenkk** [comment]
I never see you setting `0x0017880104a1d8be` on in this log
