### ISSUE TITLE
NEO Sirene / Temp / Humi sensors (0yu2xgi)

### ISSUE THREAD

**Issue by jvrrr** [Koenkk/zigbee2mqtt#3749]
Hi,
I have bought a Neo Sirene:
https://szneo.com/en/products/show.php?id=241

Features are:
-Sirene (multiple selectable tunes)
-Temp
-Humidity

Is there a way to make this work?
I like the selectable tunes...use it as door bell and alarm.

I have read this https://github.com/Koenkk/zigbee2mqtt/issues/2956
But I think it is never been finished, because my device is not reconized.

I like to help out, so what do I need to check?

**Comment by MPM1107** [comment]
Yes nothing from that conversation you linked was ever actually implemented. You will have to edit your devices.js file with the code from that issue to start playing around with it. This can help you with that part: [supporting new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html)
Your zigbee2mqtt log should be saying something about an unusupported device with a specific "model id". What model id does it show you?

**Comment by jvrrr** [comment]
I add this to devices.js:
{
    	zigbeeModel: ['0yu2xgi\u0000'],
    	model: 'neo_sirene',
    	vendor: 'neo',
    	description: 'Temperature & humidity sensor',
    	supports: 'temperature and humidity',
    	fromZigbee: [fz.neo_battery, fz.neo_temperature],
    	toZigbee: [tz.warning],
    },

Now I get this:

jun 16 00:15:49 zigbee npm[11310]:     at resolvedEntity.definition.fromZigbee.filter (/opt/zigbee2mqtt/lib/extension/receive.js:120:42)
jun 16 00:15:49 zigbee npm[11310]:     at Array.filter (<anonymous>)
jun 16 00:15:49 zigbee npm[11310]:     at Receive.onZigbeeEvent (/opt/zigbee2mqtt/lib/extension/receive.js:119:65)
jun 16 00:15:49 zigbee npm[11310]:     at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:352:44)
jun 16 00:15:49 zigbee npm[11310]:     at Controller.onZigbeeEvent (/opt/zigbee2mqtt/lib/controller.js:238:14)
jun 16 00:15:49 zigbee npm[11310]:     at Zigbee.emit (events.js:198:13)
jun 16 00:15:49 zigbee npm[11310]:     at Controller.herdsman.on (/opt/zigbee2mqtt/lib/zigbee.js:67:52)
jun 16 00:15:49 zigbee npm[11310]:     at Controller.emit (events.js:198:13)
jun 16 00:15:49 zigbee npm[11310]:     at Controller.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:496:22)

**Comment by MPM1107** [comment]
You cut off the important part of the error there but I'm guessing that you are missing the converter definitions in the toZigbee.js and fromZigbee.js files

**Comment by jvrrr** [comment]
Thanks!!

I add:
neo_temperature: {
    cluster: 'manuSpecificTuyaDimmer',
    type: 'raw',
    convert: (model, msg, publish, options) => {
      const temperature = parseFloat(msg.data['measuredValue']) / 100.0;
      return {temperature: temperature};
    },
},
neo_battery: {
    cluster: 'manuSpecificTuyaDimmer',
    type: ['raw'],
    convert: (model, msg, publish, options, meta) => {
        if (msg.data.hasOwnProperty('batteryPercentageRemaining')) {
            return {battery: msg.data['batteryPercentageRemaining']};
        }
    },
},

**Comment by jvrrr** [comment]
This is the only output I get:
{"ieeeAddr":"0xec1bbdfffe6c1edf","networkAddress":19143,"vendor":"-","description":"-","friendly_name":"0xec1bbdfffe6c1edf","lastSeen":1592335185459}]}'
jun 16 21:19:45 zigbee npm[19883]: zigbee2mqtt:info  2020-06-16 21:19:45: MQTT publish: topic 'domoticz/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0xec1bbdfffe6c1edf"}}'

**Comment by jvrrr** [comment]
How can I check if everything is working fine?

**Comment by kirovilya** [comment]
I am started https://github.com/kirovilya/zigbee-herdsman-converters/commit/ca19123a63dff1847a6c27f86b1b8e1f4c525a59

**Comment by jvrrr** [comment]
Great news!! 
I like to test It out.
How can I test it?

**Comment by kirovilya** [comment]
try dev branch of z2m

**Comment by juliend20** [comment]
Great news!! 
I'll try your dev branch tomorrow. 
How can I set alarm on/off?
Thank you.

**Comment by kirovilya** [comment]
you can to use dev version of z2m

**Comment by Julienhug** [comment]
I tested today. It's work fine. I receive info from siren. 
`{"linkquality":86,"alarm":false,"temperature_alarm":false,"humidity_alarm":false,"melody":6,"volume":"high","temperature_min":18,"temperature_max":27,"humidity_min":45,"humidity_max":80,"humidity":59,"temperature":"24.1"}`

The temperature is weird because I have 26°C on another sensor.

Thank you so much for your work. How did you know the information to be send to the siren? did you have a tuya gateway and you have sniff the zigbee protocol?

**Comment by kirovilya** [comment]
yes, I have a tuya gateway and I sniffed device communication with the gateway

**Comment by Julienhug** [comment]
ok great thanks. Have you a wrong value of temperature too?

**Comment by jvrrr** [comment]
I have the same issue  it is 29°C and is shows 27°C...so it is a issue.

Do you also have the issue is spontaneous sounds a melody?

**Comment by jvrrr** [comment]
Thanks for great job!!

**Comment by Julienhug** [comment]
@jvrrr I didn't find any problem with melody. But Can you be more precise? I'm not sure I understand meaning of "spontaneous sounds".

**Comment by Julienhug** [comment]
It has been released https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html We can use temperature calibration to add 2°C

**Comment by Julienhug** [comment]
@kirovilya Hello I saw in documentation that we can add temperature_calibration. So I tested with temperature_calibration: 2 but It doesn't work and I didn't find anything about  temperature_calibration in fromZigbee.js

**Comment by kirovilya** [comment]
@Julienhug Sorry, I didn’t write the documentation for the device and I don’t know why the calibration option is indicated there.

**Comment by jvrrr** [comment]
> @jvrrr I didn't find any problem with melody. But Can you be more precise? I'm not sure I understand meaning of "spontaneous sounds".

It spontaneouse plays a melody...I'm not sure why.

**Comment by Julienhug** [comment]
> 
> 
> @Julienhug Sorry, I didn’t write the documentation for the device and I don’t know why the calibration option is indicated there.

Ok, it'll be nice to have this option. Because I have an error on the temperature value. I'd like to add 2°C on it

**Comment by Julienhug** [comment]
> 
> 
> > @jvrrr I didn't find any problem with melody. But Can you be more precise? I'm not sure I understand meaning of "spontaneous sounds".
> 
> It spontaneouse plays a melody...I'm not sure why.

Ok it's very weird. Maybe you can launch zigbee mqtt with logs. To ensure that it's not something that trigger the alarm by mistake

**Comment by kirovilya** [comment]
The siren may be triggered by temperature or humidity. Check the relevant options

**Comment by huyphamnhu** [comment]
@kirovilya Hi, could you tell me how to manually trigger the alarm?

**Comment by kirovilya** [comment]
@huyphamnhu set alarm to true
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L2601

**Comment by pedroke** [comment]
Hi guys, do you know if it is possible to change the sound somehow? Btw, thanks Ilya for another great and affordable device supported!

**Comment by kirovilya** [comment]
@pedroke set melody from 1 to 18

**Comment by pedroke** [comment]
:) thanks... super!

**Comment by bochelork** [comment]
Sorry for steeling a closed topic, but I have a small issue. 
When I post:
{
  "melody": 6,
  "alarm": true
}
only the alarm is activated. the melody does not change. 

If I only post a melody, the melody is set. so I need 2 separate commands. Can this be solved?


```
Zigbee2MQTT:debug 2020-09-16 19:14:41: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data
'{
  "melody": 6,
  "alarm": true
}'
Zigbee2MQTT:debug 2020-09-16 19:14:41: Publishing 'set' 'alarm' to 'ALARM1'
Zigbee2MQTT:debug 2020-09-16 19:14:43: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[1],"type":"Buffer"},"dp":360,"fn":0,"status":0,"transid":4}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-16 19:14:43: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":true,"humidity":63,"last_seen":"2020-09-16T17:14:43.643Z","linkquality":48,"melody":4,"temperature":"21.1","volume":"high"}'
Zigbee2MQTT:debug 2020-09-16 19:14:53: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0,0,0,212],"type":"Buffer"},"dp":617,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-16 19:14:53: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":true,"humidity":63,"last_seen":"2020-09-16T17:14:53.223Z","linkquality":36,"melody":4,"temperature":"21.2","volume":"high"}'
Zigbee2MQTT:debug 2020-09-16 19:14:54: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0],"type":"Buffer"},"dp":360,"fn":0,"status":0,"transid":4}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-16 19:14:54: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":false,"humidity":63,"last_seen":"2020-09-16T17:14:54.317Z","linkquality":36,"melody":4,"temperature":"21.2","volume":"high"}'


Zigbee2MQTT:debug 2020-09-16 19:14:41: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data
'{
  "melody": 5
}
Zigbee2MQTT:debug 2020-09-16 19:18:21: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data '{"melody":5}'
Zigbee2MQTT:debug 2020-09-16 19:18:21: Publishing 'set' 'melody' to 'ALARM1'
Zigbee2MQTT:debug 2020-09-16 19:18:24: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[5],"type":"Buffer"},"dp":1126,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-09-16 19:18:24: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":false,"humidity":63,"last_seen":"2020-09-16T17:18:24.174Z","linkquality":36,"melody":5,"temperature":"21.1","volume":"high"}'
```

**Comment by misteriks** [comment]
> The siren may be triggered by temperature or humidity. Check the relevant options

The melody is indeed triggered by the humidity or temperature value min-max range

Zigbee2MQTT:info  2020-09-25 08:58:46: MQTT publish: topic 'zigbee2mqtt/Sirene', payload '{"alarm":false,"humidity":51,"**humidity_alarm":true,"**humidity_max":80,"humidity_min":45,"linkquality":60,"melody":5,"temperature":"18.2","**temperature_alarm":true**,"temperature_max":27,"temperature_min":18,"volume":"high"}'

Guess this are the default values for this device. 
Is there a way to change these values on the device so the get published to HA on next discovery?

**Comment by misteriks** [comment]
Ok, to disable the melody on temperature and humidity publish the flowing via the mqtt.publish service

Service Data:
topic: 'zigbee2mqtt/Sirene/set'
retain: true
payload: '{"temperature_alarm":false}'

or '{"humidity_alarm":false}'


I also found a small bug with it. Sending a value for humidity_max in the payload actually changed the humidity_min and vise versa.

**Comment by misteriks** [comment]
> Sorry for steeling a closed topic, but I have a small issue.
> When I post:
> {
> "melody": 6,
> "alarm": true
> }
> only the alarm is activated. the melody does not change.
> 
> If I only post a melody, the melody is set. so I need 2 separate commands. Can this be solved?
> 
> ```
> Zigbee2MQTT:debug 2020-09-16 19:14:41: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data
> '{
>   "melody": 6,
>   "alarm": true
> }'
> Zigbee2MQTT:debug 2020-09-16 19:14:41: Publishing 'set' 'alarm' to 'ALARM1'
> Zigbee2MQTT:debug 2020-09-16 19:14:43: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[1],"type":"Buffer"},"dp":360,"fn":0,"status":0,"transid":4}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-09-16 19:14:43: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":true,"humidity":63,"last_seen":"2020-09-16T17:14:43.643Z","linkquality":48,"melody":4,"temperature":"21.1","volume":"high"}'
> Zigbee2MQTT:debug 2020-09-16 19:14:53: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0,0,0,212],"type":"Buffer"},"dp":617,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-09-16 19:14:53: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":true,"humidity":63,"last_seen":"2020-09-16T17:14:53.223Z","linkquality":36,"melody":4,"temperature":"21.2","volume":"high"}'
> Zigbee2MQTT:debug 2020-09-16 19:14:54: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[0],"type":"Buffer"},"dp":360,"fn":0,"status":0,"transid":4}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-09-16 19:14:54: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":false,"humidity":63,"last_seen":"2020-09-16T17:14:54.317Z","linkquality":36,"melody":4,"temperature":"21.2","volume":"high"}'
> 
> 
> Zigbee2MQTT:debug 2020-09-16 19:14:41: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data
> '{
>   "melody": 5
> }
> Zigbee2MQTT:debug 2020-09-16 19:18:21: Received MQTT message on 'zigbee2mqtt/ALARM1/set' with data '{"melody":5}'
> Zigbee2MQTT:debug 2020-09-16 19:18:21: Publishing 'set' 'melody' to 'ALARM1'
> Zigbee2MQTT:debug 2020-09-16 19:18:24: Received Zigbee message from 'ALARM1', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[5],"type":"Buffer"},"dp":1126,"fn":0,"status":0,"transid":2}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-09-16 19:18:24: MQTT publish: topic 'zigbee2mqtt/ALARM1', payload '{"alarm":false,"humidity":63,"last_seen":"2020-09-16T17:18:24.174Z","linkquality":36,"melody":5,"temperature":"21.1","volume":"high"}'
> ```

Were you able to find a solution for this? I'm having the same issue

**Comment by bochelork** [comment]
> Were you able to find a solution for this? I'm having the same issue

I just set the alarm to true after the change of melody is detected.

**Comment by arduino43** [comment]
I recently purchased two of these devices but cannot get them to work.

Are their any specific pairing instructions? Holding the reset button for 5 seconds shows the unit blinking but no sign of connection attempts in logs.

1.) I've tried 1.15 and 15.0-dev
2.) Nothing appears in the logs, the device does not appear to attempt pairing.
3.) I've tried pairing with the unit powered by batteries only, USB only and batteries+USB.

**Comment by Peet1986** [comment]
Hey guys, i am new in zigbee2mqtt and maybe you can help me how to add this step by step, i have bought 2 of the NEO Sirene's and they only shown as unsupported. Where i have to enter the config? Where to go in Menue? :(  Thanks!
![image](https://user-images.githubusercontent.com/47334810/151703926-7b20de24-2c98-4a9d-b4f2-2921cf51294d.png)
