### ISSUE TITLE
re-pairing

### ISSUE THREAD

**Issue by shahglobal** [Koenkk/zigbee2mqtt#3750]
When I factory reset devices, like I hue bulb and motion sensors, the console shows up device e.g Device '0x00178801029907a4' left the network-
I tried re-pairing it by resetting it again and trying it again but the devices will not pair again. Is there any way to re-pair those devices without resetting the whole network.
Thanks

**Comment by Koenkk** [comment]
Try to use https://www.zigbee2mqtt.io/information/touchlink.html
