### ISSUE TITLE
Does zigbee2mqtt remember the PAN_ID and  frame Counter?

### ISSUE THREAD

**Issue by zrainx** [Koenkk/zigbee2mqtt#3764]
Does zigbee2mqtt remember the PAN_ID and  frame Counter when a USB dangle be replaced to another one?

In some situations, zigbee USB dangle（working as coodinator）maybe broken，Can I replace another USB dangle without change PAN_ID and frame Counter so that zigbee devices needn't to re-add network.

**Comment by Koenkk** [comment]
- Pan_id is specified through config (if none `0x1a62` is used)
- AFIAK frame counter doesn't have to be persistent.
- See https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices for further info
