### ISSUE TITLE
Nothing works after reflashing CC2531

### ISSUE THREAD

**Issue by kaelsaes** [Koenkk/zigbee2mqtt#378]
After reflashing my CC2531 with the latest firmware no Xiaomi device is reachable.

Do I have to install the newest zigbee2mqtt software also or is there something else I have to do?

Thx

**Comment by ryanbeaton** [comment]
Reflashing clears the memory on the CC2531 so you have to repair them (pair them again)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kaelsaes** [comment]
Ah okay. Thx.

**Comment by WagnerBeccard** [comment]
While youre repair them - can you leave the configuration untoutched and keep therefore the Friendly names?
Thinking of it. Didnt had to do this last time I upgraded the fw. Should be a reflash imo.

**Comment by lolorc** [comment]
it should be ok to keep the config untouched, that's what I did last time I upgraded the firmware.

**Comment by kaelsaes** [comment]
I didn't had to repair. After a few hours all device reappeared.
