### ISSUE TITLE
iasCieAddr not adjusted during re-pairing with different coordinator

### ISSUE THREAD

**Issue by Kosta-Github** [Koenkk/zigbee2mqtt#3783]
# Bug Report

[OSRAM Smart+ motion sensor](https://www.zigbee2mqtt.io/devices/AC01353010G.html) stopped reporting motion/occupancy.

## What happened

The sensor stopped reporting motion/occupancy after working flawlessly for a couple of weeks.

Since my general zigbee network stopped working, I wanted to debug the issue within a separate zigbee network with a different USB stick/coordinator.

After re-pairing the motion sensor with the new coordinator, no motion is reported anymore. This is probably because the address `iasCieAddr` is still pointing to the old coordinator (from the new `database.db`):

```
... "ssIasZone":{"attributes":{"iasCieAddr":"0x00124b000be95bf2","zoneState":1}} ...
```

How can the `iasCieAddr` be reset/adjusted to the correct/new coordinator after/during a re-pairing?

## Debug Info

Zigbee2mqtt version: 1.14
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
This is indeed a bug.

> How can the iasCieAddr be reset/adjusted to the correct/new coordinator after/during a re-pairing?

Currently only by removing and repairing it (https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove).
