### ISSUE TITLE
Clarify multiple devices configuration in Groups documentation

### ISSUE THREAD

**Issue by dunxd** [Koenkk/zigbee2mqtt#3786]
The [Groups documentation](https://www.zigbee2mqtt.io/information/groups.html) gives an example of configuring a group with only a single device in it.  Given that isn't going to be as common a requirement, it would be clearer if the documentation showed the configuration for a group with multiple devices in it. It would also help in the learning journey for YAML.

**Comment by Koenkk** [comment]
Done, thanks!
