### ISSUE TITLE
TRADFRI LED LED1835C6: Interview successful, but "NO COMPONENTS"...

### ISSUE THREAD

**Issue by DBa2016** [Koenkk/zigbee2mqtt#3795]
# Bug Report
## What happened
When joining a LED1835C6 LED to the network, I see log messages informing about the device joining, then interview start, and interview success.
https://hastebin.com/himiharije.js

Still, zigbee2mqttAssistant shows "no components" and also the device is not published to Home Assistant.

## What did you expect to happen
Same plus correct display in z2ma and more important publishing to HA.
## How to reproduce it (minimal and precise)
Put the coordinator (conbee2, if that matters) into "allow join" mode, reset LED1835C6 , wait it to join.
## Debug Info
Zigbee2mqtt version: "latest-dev" image
Adapter hardware: conbee2
Adapter firmware version: unknown right now

**Comment by Koenkk** [comment]
Is `homeassistant: true` set in your `configuration.yaml`?
