### ISSUE TITLE
Yale YMF40 Lock - Problem after update

### ISSUE THREAD

**Issue by matisaul** [Koenkk/zigbee2mqtt#3802]
# Bug Report
## What happened

Hi @Koenkk ,

I update this module to last version, from 1.7, and now My Yale YMF40 is publishing this to mosquitto:

```
zigbee2mqtt:debug 2020-06-23 20:26:59: Received Zigbee message from 'Cerradura Principal', type 'commandOperationEventNotification', cluster 'closuresDoorLock', data '{"opereventsrc":2,"opereventcode":10,"userid":0,"pin":0,"zigbeelocaltime":1770453224,"data":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-06-23 20:26:59: MQTT publish: topic 'zigbee2mqtt/Cerradura Principal', payload '{"linkquality":76,"action":"auto_lock","action_user":0,"action_source":2}'
zigbee2mqtt:info  2020-06-23 20:26:59: MQTT publish: topic 'zigbee2mqtt/Cerradura Principal', payload '{"linkquality":76,"action":""}'
zigbee2mqtt:info  2020-06-23 20:26:59: MQTT publish: topic 'zigbee2mqtt/Cerradura Principal/action', payload 'auto_lock'
```
So, is sending the correct message to MQTT broker, but inmediatly change this:

`{"linkquality":76,"action":"auto_lock","action_user":0,"action_source":2}`

To this:
`'{"linkquality":76,"action":""}'`

So, previous data is deleted by the last one.... Do you know why this is happened?

I tried to erase and repair the lock, but It happened anyway.

## Debug Info
Zigbee2mqtt version:
Adapter hardware: CC2531, 
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
Issue can be closed as a workaround was found in another issue
