### ISSUE TITLE
Javascript error when trying to add a not device supported

### ISSUE THREAD

**Issue by Shunete** [Koenkk/zigbee2mqtt#3804]
Hello,

I'm trying to add a new device not suported [https://support.meetviva.com/help/sercomm-relay-se-rz11](https://support.meetviva.com/help/sercomm-relay-se-rz11)

I'm trying to following your tutorial, but not sure what I'm doing bad.

I've just dowload your repository and I have copied it directle to the shared folder "\share\zigbee2mqtt" and then in the add-on configuration I've added the new tag "_zigbee_shepherd_devices: true".

Then restart the service and next error appears in log:
[https://pastebin.com/JevrzwS8](https://pastebin.com/JevrzwS8)

I'm using last version 1.14.0

Please, could you help me. Not sure that it's an issue or something that I'm not doing well.

Thanks in advance.

**Comment by Koenkk** [comment]
Can you try with the latest edge addon?
