### ISSUE TITLE
Issue with Serial "[Error: EAGAIN: resource temporarily unavailable, read]"

### ISSUE THREAD

**Issue by errolsancaktar** [Koenkk/zigbee2mqtt#3809]
# Bug Report
## What happened
Error:

` 2020-06-25T19:07:59.209Z serialport/bindings/unixRead waiting for readable because of code: EAGAIN
zigbee2mqtt    | 2020-06-25T19:07:59.211Z serialport/bindings/unixRead read error [Error: EAGAIN: resource temporarily unavailable, read] {
zigbee2mqtt    |   code: 'EAGAIN',`

## What did you expect to happen
Not reporting information correctly to qtt
## How to reproduce it (minimal and precise)
im just starting the docker container

## Debug Info
Zigbee2mqtt version: zigbee2mqtt@1.14.0 
Adapter hardware: CC2530
Adapter firmware version:
`[0m 2020-06-25T19:07:58.839Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}`

`winston:file logged 560 debug 2020-06-25 13:07:57: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0"},"adapter":{"concurrent":null}}'`

full logs attached from recent start
[error.log](https://github.com/Koenkk/zigbee2mqtt/files/4833374/error.log)

usb is connected via a powered usb hub.  zigbee is passed to TTYACM0 via docker.  also have a zwave adapter connected to another container

**Comment by Koenkk** [comment]
This is logging of the user serialport library (https://github.com/serialport/node-serialport) and AFAIK this is normal.

**Comment by errolsancaktar** [comment]
Thanks!
