### ISSUE TITLE
Windows. Cannot create log folder

### ISSUE THREAD

**Issue by ptvoinfo** [Koenkk/zigbee2mqtt#381]
I've downloaded the latest version to my Windows development machine. zigbee2mqtt\lib\util\logger.js cannot create a new log folder because ":" is prohibited in the folder name.

Possible solution: remove or change ":" to "-", "." in the date format string:

```
// Add start time to directory.
const directory = path.join(rootDirectory, moment(Date.now()).format('YYYY-MM-DD.HHmmss'));
```

**Comment by Koenkk** [comment]
Can you check if this has been fixed?

**Comment by stas-demydiuk** [comment]
It has been fixed on my machine with latest dev branch

**Comment by ptvoinfo** [comment]
Yes, fixed. Thank you!
