### ISSUE TITLE
Node Red -> Simple basic question (Turn on/ off with switch node a zigbee device)

### ISSUE THREAD

**Issue by get-command** [Koenkk/zigbee2mqtt#3811]
Hello community,

I am new here and need your help. i use the super device CC2531.

If I replace the switch node with an inject not, then I can switch the lamp/bulb on and off. When I change the zigbee-light-node with a RF433 light/bulb then function this very well. This is a sign that the switch node is set correctly. The command is passed on.   how can I start the execute node? I couldn't read it anywhere.

i get an error message:

Error: Command 0x00158d0XXXXXXXX/1 genOnOff.on({“onOff”:0}, {“timeout”:6000,“manufacturerCode”:null,“disableDefaultResponse”:false}) failed (Error: Timeout - 40061 - 1 - 210 - 6 - 11 after 6000ms)

I try to explain that with these screeshots:

![grafik](https://user-images.githubusercontent.com/67456251/85829796-aed8c380-b78b-11ea-96c5-44c20aca721c.png)

![grafik](https://user-images.githubusercontent.com/67456251/85829828-c1eb9380-b78b-11ea-9d91-94cdfd2c8a78.png)

Thank you in advance.

I try to explain in more detail:

![Unbenannt-1](https://user-images.githubusercontent.com/67456251/85834486-c320be80-b793-11ea-8ef3-cc4a8f95bdbf.jpg)

**Comment by sjorge** [comment]
I'm guessing you're using https://github.com/hobbyquaker/node-red-contrib-zigbee, might have better luck asking there for help.

**Comment by get-command** [comment]
> 
> 
> I'm guessing you're using https://github.com/hobbyquaker/node-red-contrib-zigbee, might have better luck asking there for help.

thank you for the tip. we have already solved it. here: https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/113
