### ISSUE TITLE
default for reject_unauthorized not false as per docs

### ISSUE THREAD

**Issue by lassieee** [Koenkk/zigbee2mqtt#3814]
The docs state:
```
  # Optional: disable self-signed SSL certificates (default: false)
  reject_unauthorized: true
```
which leds me to believe this allows self-signed certs by default, but I have to explicitly define `reject_unauthorized: false` to allow self-signed certificate authentication.
So I think the docs should be updated with: 
```
  # Optional: disable self-signed SSL certificates (default: true)
  reject_unauthorized: true
```
I'm using docker koenkk/zigbee2mqtt:1.14.0

**Comment by Koenkk** [comment]
This is indeed true, updated thanks!
