### ISSUE TITLE
Point of clarification re #3792

### ISSUE THREAD

**Issue by Pashovski** [Koenkk/zigbee2mqtt#3816]
Thank You! Replied before I realized it had been closed.

[I noticed you wrote the model](https://github.com/Koenkk/zigbee2mqtt/issues/3792#issuecomment-650548088) as the EAN/UPC - product number (046677548285), not the Material number (12NC) (929002039801) . Is there a reason for that? When I look on the device for a model number I see the Material number. That Is what I put in my files. Should I change it to the UPC?
https://imgur.com/WU9aN4a
https://imgur.com/3LG51Ov

**Comment by Koenkk** [comment]
Was a mistake, updated it. thanks!
