### ISSUE TITLE
Problem reading device specific configuration values.  e.g. occupancy_timeout, motion_sensitivity 

### ISSUE THREAD

**Issue by trankin** [Koenkk/zigbee2mqtt#3832]
# Bug Report
## What happened
I don't quite know how to "read" device specific value.  I'm successfully setting values with e.g. `zigbee2mqtt/[FRIENDLY_NAME]/set/occupancy_timeout`, but 
`zigbee2mqtt/[FRIENDLY_NAME]/get/occupancy_timeout` doesn't seem to do anything or return a value.

## What did you expect to happen
I expect that after making a call to `zigbee2mqtt/[FRIENDLY_NAME]/get/occupancy_timeout` that the response would show up in a topic, but I was unable to find it.

## How to reproduce it (minimal and precise)
I'm exploring the Hue Motion detector: https://www.zigbee2mqtt.io/devices/9290012607.html

I'm sending a set command and then a get command, and expecting some response.  I see a response in the debug log, but not in the mqtt topics.
```
zigbee2mqtt:debug 2020-06-30 16:36:15: Received MQTT message on 'zigbee2mqtt/0x0017880106f57f73/set/occupancy_timeout' with data '120'
zigbee2mqtt:debug 2020-06-30 16:36:15: Publishing 'set' 'occupancy_timeout' to '0x0017880106f57f73'

zigbee2mqtt:debug 2020-06-30 16:36:44: Publishing get 'get' 'occupancy_timeout' to '0x0017880106f57f73'
zigbee2mqtt:debug 2020-06-30 16:36:45: Received Zigbee message from '0x0017880106f57f73', type 'readResponse', cluster 'msOccupancySensing', data '{"pirOToUDelay":120}' from endpoint 2 with groupID 0
```

## Debug Info
Zigbee2mqtt version: 1.14.0
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20190608.zip

## Caveats
I'm super new to zigbee2mqtt, and am in the process of exploring this solution.  First impressions are very positive, and Zigbee in general seems pretty interesting.

One of the things that we do often in our environments is that we set custom values on the sensor devices.  This seems to be working very well in the zigbee2mqtt environment, and in fact is smoother and more seamless than what we've been doing with zWave.  However I'm having a hard time confirming that custom values have been set.

Many thanks,

Thomas

**Comment by trankin** [comment]
Apologies, I realize that I've destroyed the template provided.. I will reformat the original message momentarily.

**Comment by Koenkk** [comment]
Thanks for reporting, just fixed this. Now it will confirm to MQTT on both set and get. Changes will be available in the dev branch in a few hours: https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html

**Comment by trankin** [comment]
@Koenkk, thanks very much for the quick response.. I was reviewing the source code just a few minutes ago because I believed that I was understanding where it needed to go.. e.g. in the converters.. and I happened to notice that you had just put in the response: https://sharex.tomrankin.net/ShareX/2020/07/chrome_FaPxCgaQxH.png   I'm getting a better feel for the source, I'll be able to contribute soon.

**Comment by trankin** [comment]
@Koenkk, I added in a PR to add in motion_sensitivity as well.  Thanks for all of your work on this.

**Comment by Koenkk** [comment]
Cool, and congratz with your first pr, thanks!

I assume this can be closed now.
