### ISSUE TITLE
HY369RT.md

### ISSUE THREAD

**Issue by GuillaumeP01** [Koenkk/zigbee2mqtt#3836]
Hello,
First of all thank you for your development on the Zigbee.
On the page https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/HY369RT.md
it is indicated the reference HY369RT unfortunately I cannot find this model on Aliexpress.
However, we find this:
https://fr.aliexpress.com/item/4001161658482.html
https://fr.aliexpress.com/item/4001065414044.html
https://fr.aliexpress.com/item/4001065111037.html
The reference on Aliexpress is HY368 and not HY369. Could you confirm the model compatible with Zigbee2mqtt?
cordially
Guillaume

**Comment by Koenkk** [comment]
@sjorge do you maybe know something about this?

**Comment by sjorge** [comment]
Those look to also be TuYa, I got one of the essential branded ones from amazon.de before sending it back, the quality was poor (and no valve reporting).

Given the TuYa code we have seem to work for all Tuya TRV's so far, I would assume it will also work for the ones linked above. Maybe with a small change to devices.js to add them to the existing list.

**Comment by GuillaumeP01** [comment]
ok thank you very much

**Comment by GuillaumeP01** [comment]
I found on Aliexpress a version which seems compatible zigbee2mqtt according to a customer.

https://fr.aliexpress.com/item/4001043738901.html?spm=a2g0o.cart.0.0.56843c00fKcU6X&mp=1

**Comment by shirou93** [comment]
Hy369RT have the same zigbeemodel as this termostat.

https://zigbee.blakadder.com/MoesHouse_HY369-ZB-RVT.html

Can you confirm this compatible?

**Comment by shirou93** [comment]
> Hello,
> First of all thank you for your development on the Zigbee.
> On the page https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/HY369RT.md
> it is indicated the reference HY369RT unfortunately I cannot find this model on Aliexpress.
> However, we find this:
> https://fr.aliexpress.com/item/4001161658482.html
> https://fr.aliexpress.com/item/4001065414044.html
> https://fr.aliexpress.com/item/4001065111037.html
> The reference on Aliexpress is HY368 and not HY369. Could you confirm the model compatible with Zigbee2mqtt?
> cordially
> Guillaume

On aliexpress someone write  comment "in zigbee2mqtt this device is blind" hy368

**Comment by cadavre** [comment]
With 1.14.2 this valve (HY368) integrates well! There was a bug where valve was discovered as cover, but now it is fixed! I just paired mine.

**Comment by shirou93** [comment]
i have mqtt errors when i choice mode like eco etc.

![Przechwytywanie](https://user-images.githubusercontent.com/59237288/92268460-b7175280-eee2-11ea-9689-c2e2ecb4bc6b.PNG)

**Comment by shirou93** [comment]
i have mqtt errors when i choice mode like eco etc.

![Przechwytywanie](https://user-images.githubusercontent.com/59237288/92268460-b7175280-eee2-11ea-9689-c2e2ecb4bc6b.PNG)

Why entity like window open etc show as switch no binary sensor?

@GuillaumeP01  can you reopen issue?

**Comment by GuillaumeP01** [comment]
Hello, the subject was to check the reference in the documentation and not the integration of the valve to see the following subject:
https://github.com/Koenkk/zigbee2mqtt/issues/3821
