### ISSUE TITLE
Osram Plug no state update on the mqtt interface if the plug switch manual with the button on the plug

### ISSUE THREAD

**Issue by Maddin2020** [Koenkk/zigbee2mqtt#3856]
# Bug Report
## What happened
Osram Plug no state update on the mqtt interface if the plug switch manual with the button on the plug

## What did you expect to happen
That the state on the mqtt interface change too, if i manual switch the plug

## Debug Info
Zigbee2mqtt version:1.14.0
Adapter hardware: CC2538
Adapter firmware version: MODKAMRU_V3_USB

**Comment by lolorc** [comment]
If I recall correctly, that happened to me one time, and I re-paired the plug to make it work again.

**Comment by IVI053** [comment]
Could also be a connection issue. These devices have very bad antenna design.

**Comment by angryfish404** [comment]
I have the same issue, i guess since the last 2 versions. I can turn the osram plug on and off via mqtt, but the status is not updated, when I use the button on the plug

**Comment by Koenkk** [comment]
Try to reconfigure the device via https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure

**Comment by angryfish404** [comment]
wow, that worked like a charm. Thanks a lot!

**Comment by Koenkk** [comment]
Good to hear, assuming this fixes it for OP, so can be closed.
