### ISSUE TITLE
OTA Updates for Dresden Elektronik FLS-PP (available on GitHub)

### ISSUE THREAD

**Issue by kennymc-c** [Koenkk/zigbee2mqtt#3859]
I noticed that there is currently no OTA Update Support for Dresden Elektronik FLS-PP IP.

The manufacturer provides the firmware on GitHub: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/OTA-Image-Types---Firmware-versions#dresden-elektronik

Would it be possible to integrate this in the future?

**Comment by Koenkk** [comment]
Done! Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
