### ISSUE TITLE
0.1.4 (hue bulbs) color and brightness not correct

### ISSUE THREAD

**Issue by sknsean** [Koenkk/zigbee2mqtt#386]
When setting bulb color and brightness, the values from the mqtt message is getting lost somewhere...

https://paste.pound-python.org/show/w59WFIu3Snab51eGcDhw/

**Comment by ben423423n32j14e** [comment]
If there is going to be a re-release of 0.1.4, any chance of including this pull request?

https://github.com/Koenkk/zigbee-shepherd-converters/pull/74

**Comment by ben423423n32j14e** [comment]
Koenkk, thank you! 👍

**Comment by Koenkk** [comment]
Fixed in 0.1.5, thanks for reporting!

**Comment by sknsean** [comment]
I'm thanking you :-)
Great project :+1:
