### ISSUE TITLE
Auto remove device when removing group

### ISSUE THREAD

**Issue by nielsi** [Koenkk/zigbee2mqtt#3861]
Currently, when removing a group, it looks like devices linked to that group still remain grouped. 

After I created a new group with the same friendly name and added only a few of its previous devices in it, the other (by now renamed to new unique names) devices still responded to commands to their previous group. I expected that removing a group would automatically 'unlink' all devices in it. 

I realize this is easily achieved by first running the _remove_all_ topic and then the _remove_group_ but unless there is a specific reason not to, I can imagine automatically running the remove_all functionality before a group is removed makes more user friendly sense.

**Comment by Koenkk** [comment]
Implemented in the latest dev branch.
- `zigbee2mqtt/bridge/config/remove_group`: removes group + members
- `zigbee2mqtt/bridge/config/force_remove_group`: removes group (and not the members, useful in case members fail to respond).

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
