### ISSUE TITLE
problem with deconz over TCP Port

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#3862]
Hello, I have a Raspberry where Zigbee2mqtt with Conbee is installed and works well.
I have IoBroker on my Nuc, there I cannot get the connection to the Raspberry.

Pi: 192.168.178.37
sudo nano /etc/ser2net.conf
20108:raw:0:/dev/ttyACM0:115200 8DATABITS NONE 1STOPBIT

IoBroker:
tcp://192.168.178.37:20108

log:

zigbee.0 | 2020-07-03 21:57:31.231 | error | at /opt/iobroker/node_modules/@serialport/stream/lib/index.js:242:12
-- | -- | -- | --
zigbee.0 | 2020-07-03 21:57:31.231 | error | at SerialPort._error (/opt/iobroker/node_modules/@serialport/stream/lib/index.js:198:14)
zigbee.0 | 2020-07-03 21:57:31.231 | error | at SerialPort. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:89:45)
zigbee.0 | 2020-07-03 21:57:31.231 | error | at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
zigbee.0 | 2020-07-03 21:57:31.231 | error | at new Promise ()
zigbee.0 | 2020-07-03 21:57:31.231 | error | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
zigbee.0 | 2020-07-03 21:57:31.231 | error | at Generator.next ()
zigbee.0 | 2020-07-03 21:57:31.231 | error | at Driver. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:91:28)
zigbee.0 | 2020-07-03 21:57:31.231 | error | (10274) Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open tcp://192.168.178.37:20108'
zigbee.0 | 2020-07-03 21:57:31.231 | error | (10274) Failed to start Zigbee
zigbee.0 | 2020-07-03 21:57:31.076 | info | (10274) Starting Zigbee...

https://github.com/ioBroker/ioBroker.zigbee/issues/685

**Comment by sjorge** [comment]
Are you trying to connect to the device when zigbee2mqtt is running? I don’t think that will work.

**Comment by salopette** [comment]
That doesn't work either, it works with a CC2531, but not with the conbeeII-

**Comment by Koenkk** [comment]
Conbee over TCP port is not supported yet, you can request this feature here: https://github.com/Koenkk/zigbee-herdsman/issues/72 (Deconz team)

**Comment by zombielinux** [comment]
Crossposting this here. 

https://github.com/cminyard/ser2net/issues/35

ConbeeII cannot be piped over tcp at this moment. Vote for the feature. 

Also, ser2net's syntax has changed.

**Comment by cminyard** [comment]
I debugged this a bit with zombielinux, and I'm a bit confused by the issue.  Is this something that ser2net is doing wrong?  It should be able to open and read/write the device, I would think.

**Comment by ChrisHae** [comment]
Hi, I'm starting to look into this.

**Comment by ChrisHae** [comment]
TCP support for ConBeeII is now ready. Use it like descriped here: https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

(Wait until it is merged in zigbee2mqtt-dev or hassio addon)

@Koenkk Could you please add ConBeeII support to the readme(s)
