### ISSUE TITLE
Support for channel masks

### ISSUE THREAD

**Issue by alekslyse** [Koenkk/zigbee2mqtt#3867]
I see in Home Assistant and Deconz they have support for multiple channel masks for end devices,

example in HA: channels: [15, 20, 25]  # Channel mask to distribute to end devices.

Does z2m support channel masks too?

**Comment by Koenkk** [comment]
Channel mask are not supported, I've read about it but cannot understand what practical advantage it brings.

**Comment by alekslyse** [comment]
From what I understand it makes it easier for endpoints to expect a channel change if the current channel is too noisy. I never noticed it before, but the other implementations implemented it so it seems like it has some benefits?

**Comment by alekslyse** [comment]
Unstale. Should be implemented to follow functions of the other importations that all support channel masks
