### ISSUE TITLE
unable to pair WXKG11LM  aquara wireless switch

### ISSUE THREAD

**Issue by daksh1305** [Koenkk/zigbee2mqtt#3869]
Hey,

I am unable to pair my aqara wireless switch with zigbee2mqtt i am currently using version 1.14.1 when i try to interview the device the device is not recognized.

Please can somebody help me with this issue.

Thanks

**Comment by amownz** [comment]
it is a tricky one to pair
first of all check that pairing devices is enabled in the config.
after that pres the button(s) and keep holding them till the lights blink. Keep holding them till they blink a second time.
after that you can release and wait it can take up to 10 min to pair so give it time.

also the battery has to be 100% full to work properly so i recommend replacing the cell battery.

it can take a couple tries.
