### ISSUE TITLE
Bug Report - Stop reading from serial

### ISSUE THREAD

**Issue by mailart** [Koenkk/zigbee2mqtt#3879]
![image](https://user-images.githubusercontent.com/3700999/86994282-00ae2000-c174-11ea-9c49-bd023714fdc6.png)

I have my pi based zigbee2mqtt hangs all the time. It runs for mins then stop reading from serial, I need to kill the process, reconnect the usb dongle to get readings for next mins.

I noticed when it stops reading after Ctrl + C I can always see this line 

umpi:writer --> frame [254,26,36,2,2,253,255,0,0,0,0,0,0,242,0,0,242,33,0,2,0,30,6,0,25,3,2,11,0,0,20]

**Comment by Koenkk** [comment]
What firmware are you running?

**Comment by mailart** [comment]
> What firmware are you running?

Thanks Koenkk, I am using 20190608 with latest zigbee2mqtt. I have more than 40 sensors around, it seems the USB dongle does not response every 20,30 mins for me. and get retry. reload the cdc_acm USB driver does not help only reconnect and dongle can make it back.

Do you think it is a firmware issue? if the latest 3.0 one might fix that?

![image](https://user-images.githubusercontent.com/3700999/87100191-b8493d80-c219-11ea-8e78-d2cf7348b233.png)

**Comment by mailart** [comment]
![image](https://user-images.githubusercontent.com/3700999/87103646-a40a3e00-c223-11ea-875d-f3605ff5c81f.png)
 
another hang shown SYS - osalTimerExpired

**Comment by Koenkk** [comment]
It seems that your adapter crashes, with such a large network I would recommend switching to the source routing firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing
