### ISSUE TITLE
New Integration with Indigo

### ISSUE THREAD

**Issue by siclarkplugins** [Koenkk/zigbee2mqtt#3881]
Not an issue, but a notification of a new integration.  

We have now got [Indigo](https://www.indigodomo.com) connected to zigbee devices via MQTT and zigbee2mqtt.  

Thanks for the great work on this.

**Comment by Koenkk** [comment]
Is there any link I can add to https://www.zigbee2mqtt.io/#integration?

**Comment by siclarkplugins** [comment]
Of course, I am just writing up some documentation and then will send the link

**Comment by Koenkk** [comment]
Good, let me know once you have it. I will close this for now.
