### ISSUE TITLE
Hue Motion Sensor lux value not corect

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#3882]
Hello, I'm using v.1.14.1

for me the problem with the lux values from the Hue motion sensor.

The value of 22000 lux is displayed in z2m at 21:00, the same motion sensor in deconz shows a value of 100 lux at 21:00.

I think 100 lux at 21:00 is correct! How can I customize it in z2m?

**Comment by Koenkk** [comment]
The `illuminance` value are provided in the payload:
- `illuminance`: legacy value, kept to prevent a breaking change
- `illuminance_lux`: illuminance value in lux (formula: `Math.pow(10, illuminance / 10000) - 1`, so in your case 22000 would result in +- 157 which looks to be ok in your case
