### ISSUE TITLE
zigbee2mqtt with Busch Jaeger

### ISSUE THREAD

**Issue by FloW990** [Koenkk/zigbee2mqtt#3894]
Hello,
I'm new to the Zigbee world.
I have been trying to use my old Busch Jaeger built-in switches with a mqtt CC2531 stick for three days now, because I would like to process them in node-red for more functionality. To do this, I went along with the guide on zigbee2mqtt.io. I manage to learn the switch to the system, but I don't have access to the single button press.
Even reading here in the forum didn't really get me far. It looks like there is a solution but I don't understand the explanation.
It would be really great if someone could explain that to inexperienced. 

Thank you for any productive answer.

**Comment by Koenkk** [comment]
Is this the switch: https://www.zigbee2mqtt.io/devices/6735_6736_6737.html ? It doesn't provide a single click `action` it seems.
