### ISSUE TITLE
Crash of zigbee2mqtt container

### ISSUE THREAD

**Issue by valepe** [Koenkk/zigbee2mqtt#3906]
# Bug Report
## What happened

Sometime zigbee2mqtt crash and restart

## What did you expect to happen

Normal run

## How to reproduce it (minimal and precise)

Don't know

## Debug Info
Zigbee2mqtt version: 1.14.1 but also happened with 1.13.1
Adapter hardware: CC1352P-2
Adapter firmware version: 20200417

Zigbee2mqtt is running in a docker container on a Synology NAS.
I include an extract of the log. I noticed that every time that the container crash the last recorded item was from an aqara motion and illuminance sensor.

Never noticed this behavior with the CC2531. 

[https://pastebin.com/s5j17egs](https://pastebin.com/s5j17egs)

I add the config file (masked ):

```
# Required: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: true

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: false

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtt://xxx.xxx.xxx.xxx:yyyy'
  # Optional: MQTT server authentication user (default: nothing)
  user: MQTT_USER
  # Optional: MQTT server authentication password (default: nothing)
  password: MQTT_PASSWORD

# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/ttyACM0

# Optional: advanced settings
advanced:
  # Optional: ZigBee pan ID (default: shown below)
  pan_id: 0xMY_PANID
  # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
  # (default: 11)
  channel: 25
  # Optional: network encryption key, will improve security (Note: changing requires repairing of all devices) (default: shown below)
  network_key: [CUSTOM_NETWORK_KEY]

# Optional: experimental options
experimental:
  transmit_power: 19
```

**Comment by Koenkk** [comment]
It seems that the adapter disconnects for some reason: `No such device or address, cannot open /dev/ttyACM0`, can you try connecting the adapter via a powered usb hub?

**Comment by valepe** [comment]
> It seems that the adapter disconnects for some reason: `No such device or address, cannot open /dev/ttyACM0`, can you try connecting the adapter via a powered usb hub?

The adapter is connected with a 10m USB cable with signal amplifier. Maybe CC1353P-2 is more power hungry than CC2531. I'll try with a powered hub

**Comment by valepe** [comment]
After more than a week with no crashes, I close the issue.
Thank you for your help
