### ISSUE TITLE
Update Birth & Will Topic for Home Assistant

### ISSUE THREAD

**Issue by SirDeadlystrike** [Koenkk/zigbee2mqtt#3918]
Home Assistant as of 0.113 will now send birth and will messages by default, without requiring further configuration

They have chosen `homeassistant/status` as the topic to do this by default.

While customizable I think given that this is their new standard, it should be adopted. 

Opening this issue for discussion

**Comment by Koenkk** [comment]
Implemented, thanks for notyfing!
