### ISSUE TITLE
Slightly weird color_temperature for Immax Neo RGB 07004D

### ISSUE THREAD

**Issue by rotdrop** [Koenkk/zigbee2mqtt#3920]
# Not a Bug Report

Rather some notes.

## What happened

Device

-  Neo SMART LED E27 8,5W color, dimmable, Zigbee 3.0 (07004D)
- it behaves somehow like described by the manufacturer, i.e. 2.7 kK + color
  - the color_temperature behaves slightly weird: setting it to whatever value just resets the color values and sets the device to "warm white" 2.7kK.
  - when changing the color the device reports back a color_temperature value
  - example: RGB 7, 130, 255 (bluish), temperature 39
  - example: RGB 5, 69, 255 (bluish), temperature 2212

So I wonder what the reported color temperature really means. Perhaps it is just bogus and "dummy"?

## What did you expect to happen

Consistent color temperature reports. But perhaps the color temperature should just be ignored.

## How to reproduce it (minimal and precise)

- set the light color and watch the change in the color temperature
- try set the color temperature and see that the device resets to 2700K white

## Debug Info
Zigbee2mqtt version: dev branch commit 67f02adbd016f3154dd8730a5f102c6e9074dc68
Adapter hardware: CC2531
Adapter firmware version:
```Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}```

Kind thanks for all your good work!

**Comment by Koenkk** [comment]
Could you provide debug logging of the issue?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
