### ISSUE TITLE
device_options:   transition: x - not working

### ISSUE THREAD

**Issue by SaturnusDJ** [Koenkk/zigbee2mqtt#3922]
1.14.1

After reading https://www.zigbee2mqtt.io/information/configuration.html#changing-device-type-specific-defaults I got the understanding that putting
```
device_options:
  transition: 2
```
in configuration.yaml would result in all devices getting that *device specific configuration*, which of course applies to all lights. It does not work. Putting `transition` with individual device entries does work.

**Comment by Koenkk** [comment]
Fixed, thanks for reporting!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
