### ISSUE TITLE
Thermostat discovery error

### ISSUE THREAD

**Issue by banolka** [Koenkk/zigbee2mqtt#3924]
Hi,

I bought thermostats - https://pl.aliexpress.com/item/4001065130284.html they look like Moes HY369RT however they are discovered by zigbee2mqtt as 

Model is TS0601 by _TZE200_ckud7u2l.
Hardware version is 1.
Firmware version is unknown.

is there any way to make them to be discovered as Moes HY369RT? Now zigbee2mqtt thinks it is a cover and not the thermostat :/

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?
