### ISSUE TITLE
Support for MOES ZigBee Switch Module

### ISSUE THREAD

**Issue by MikeVRT** [Koenkk/zigbee2mqtt#3925]
Can be used from Smart Life and Tuya (from description).
[Item](https://aliexpress.com/item/4001065019839.html) in official MOES' store on AliExpress.
It's like Xiaomi relay (LLKZMK11LM) but with only one relay and one switch support. Can be placed behind switch.

![moes](https://user-images.githubusercontent.com/24420926/87818699-af88e500-c873-11ea-8c84-e9050309db0f.jpg)

**Comment by MikeVRT** [comment]
I bought a new one. If need help for add to device list, please give me advice what to do.

**Comment by Koenkk** [comment]
Please follow: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> I bought a new one. If need help for add to device list, please give me advice what to do.

Did you got your item? Can it measure something like watt or voltage?
