### ISSUE TITLE
Quest with experimental.output

### ISSUE THREAD

**Issue by dvv** [Koenkk/zigbee2mqtt#3928]
# Bug Report
## What happened

I set `experimental.output := attributes_and_json` (notice extra "s") and spent half-day finding out why I had been getting no MQTT activity from well-paired devices.
I admit it's my fault, RTFM, etc. I did use `attribute_and_json` on another setup previously (several months ago) and entered the setting value _by-heart_ )

## What did you expect to happen

A warning in the log from [here](https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L326) about wrong setting value, or a sane default equal to `attribute`.

## How to reproduce it (minimal and precise)

Set `experimental.output` to `"FOO"` and see no messages from well-paired devices.

## Debug Info
Zigbee2mqtt version:
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

**Comment by Koenkk** [comment]
Done! Zigbee2mqtt will now refuse & provide an error message in this case, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by dvv** [comment]
Thank you!
