### ISSUE TITLE
Error pairing E1734 Ikea Button

### ISSUE THREAD

**Issue by Dragon0501** [Koenkk/zigbee2mqtt#3930]
![Screenshot 2020-07-18 at 17 39 43](https://user-images.githubusercontent.com/59663011/87856200-c8e66b80-c91d-11ea-84ca-6cce02573692.png)
I tried to pair an Ikea device. It is an E1734. Everytime I push the pairing button an error occured. It doesn't matter at which accesspoint I try to pair.

![Screenshot 2020-07-18 at 17 31 18](https://user-images.githubusercontent.com/59663011/87856166-81f87600-c91d-11ea-9bed-a3666964feca.png)

**Comment by Dragon0501** [comment]
Problem solved. Waited for three or four hours. Retried and paired at first try...

**Comment by MattWestb** [comment]
Good that you get the E1734 pared.
Its can being that you have being hitted of the famous paring bug.
The Z2M team it's on the hunt and have have made some progress but still not implanted in the code / firmware.

**Comment by Dragon0501** [comment]
It still shows an error code when pairing but it works.

**Comment by MattWestb** [comment]
So both good and bad for you :-)  :-(
I'm not sure if its the paring bug described here https://github.com/Koenkk/zigbee2mqtt/issues/3177 and i have all my E1743 its in production state in the Ikea GW and deCONZ so i cant testing the paring in Z2M for the moment.
By the way: have you checking if the firmware its at the latest version in the E1743 ?
It was little crappy in the first Z30 releases.

**Comment by Dragon0501** [comment]
Firmware check failed,... device didn't respond to OTA request. I tried But impossible...

**Comment by MattWestb** [comment]
Did you waking up the E1743 and keeping it awake then sending the request to it ?
Sorry i was forgetting saying that :-(
Normally its enough pressing the off key with some second between repeating it for keeping it awake.

**Comment by Dragon0501** [comment]
Firmware checked. no update available.

**Comment by MattWestb** [comment]
That was good.
Then you continuing working with battery powered devices = end devices (and some exoitc mains powered) that is normally sleeping they must being waked up for listening on command the system its sending.
One example: if having one pared motion sensor and like to binding it to a group then its necessary triggering some motion for waking it up one short moment before sending the configuration command or its timing out = not working. Main powered devices = routers (the most of them) devices its normally not sleeping and is always online so no need to do anything then sending one command to them.
