### ISSUE TITLE
is it possible to designate a router for each device? when the coordinator offline some devices will be lost

### ISSUE THREAD

**Issue by fantasyjqc** [Koenkk/zigbee2mqtt#3937]
# Bug Report
## What happened
when the coordinator offline some devices will be lost, i use the CC2538 as a coordinator and there are more than 80 devices in the zigbee network, I guess the reason why this happens is when the coordinator offline the device connected directly to the coordinator will try to connect the router and the router cannot bear so many connections.

## What did you expect to happen
is it possible to designate a router for each device? 
or designatea parent node for each device?

## Debug Info
Zigbee2mqtt version: 1.14.1
Adapter hardware: CC2538
Adapter firmware version:  20200211

**Comment by Koenkk** [comment]
Zigbee devices itself are responsible for selecting it's parent, so from zigbee2mqtt this behaviour cannot be controlled.
