### ISSUE TITLE
Wifi rollershutter device works on zigbee?

### ISSUE THREAD

**Issue by Dylantje** [Koenkk/zigbee2mqtt#3946]
Dear....

Is this wifi device realy working with z2m??
[https://nl.aliexpress.com/item/4000201855781.html?spm=a2g0o.cart.0.0.1f343c00m9ADTW&mp=1](url)

Should:
[https://www.zigbee2mqtt.io/devices/mcdj3aq.html](url)

Is this option new, or are there more tua wifi devices that are working with z2m?

**Comment by Koenkk** [comment]
Wifi devices don't and will never work with zigbee2mqtt.

The device you linked is available in both wifi and [zigbee](https://nl.aliexpress.com/item/4000336263991.html?aff_platform=portals-tool&sk=_dW2lsE7&aff_trace_key=68933c8cc9a148ff8ae668762647c37c-1595317803145-02129-_dW2lsE7&terminal_id=6c88088d7a6a4b2299617990e9c5e530&tmLog=new_Detail&aff_request_id=68933c8cc9a148ff8ae668762647c37c-1595317803145-02129-_dW2lsE7). In case you want to control it with zigbee2mqtt buy the zigbee one.
