### ISSUE TITLE
Feature Request: Dresden Elektronik Phoscon to zigbee2mqtt configuration converter.

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#3961]
# Feature Request
## What happened
Cannot import Dresden Elektronik Phoscon configuration (JSON formatted .dat-file) into zigbee2mqtt.
## What did you expect to happen
Import Dresden Elektronik Phoscon configuration (JSON formatted.dat-file) into zigbee2mqtt successfully.

At least the coordinator- and device configuration, groups and bindings should be possible to import from the Phoscon App.
This would save hours to re-register 50+ end devices.

## How to reproduce it (minimal and precise)
Try to find e.g. a command-line  tool for this task.

## Debug Info
Zigbee2mqtt version: 1.14.1
Adapter hardware: Dresden Conbee II
Adapter firmware version: 26580700

**Comment by renne** [comment]
Stale ping

**Comment by samsam-rolon** [comment]
Very intrested in this feature ! My whole house is in Legrand and re-paring every device is just : PAINFUL
