### ISSUE TITLE
Apply device (specific) options to all devices of a certain model

### ISSUE THREAD

**Issue by SaturnusDJ** [Koenkk/zigbee2mqtt#3967]
Following the advise in the manual, I was planning to add a debounce (of value 2) for WSDCGQ11LM devices (https://www.zigbee2mqtt.io/devices/WSDCGQ11LM.html). 12 of those here.

Normally you have to either add this per device or add it as `device_option` in config to apply it to all devices, or groups should be possible too it seems. 

How about a config option to apply it to all devices of a certain type?

**Edit:**
Just found it should be possible already to apply it to groups, removing that from this issue.

**Comment by zhapwey** [comment]
if in the general device option you set debounce: 1 set this property for all devices? because I haven't gotten it to work.

**Comment by Koenkk** [comment]
> How about a config option to apply it to all devices of a certain type

How would you define a "certain type"? (like router/end devices?)

**Comment by SaturnusDJ** [comment]
@zhapwey 
Like in https://github.com/Koenkk/zigbee2mqtt/issues/3922.
That part is standalone in the config and applies to all device where it can be applied to.

@Koenkk 
I should have used the word model, that's how it is in the docs. E.g. `WSDCGQ11LM`.

**Comment by joshuaspence** [comment]
I am also looking for a way to do this.
