### ISSUE TITLE
Hue Philips Hue White Single bulb B22 (8718696449691) light alway showing a non-available whenever HA is restarted

### ISSUE THREAD

**Issue by jyavenard** [Koenkk/zigbee2mqtt#3969]
# Bug Report
## What happened:
The Philips Hue White Single bulb B22 (8718696449691) are always showing up as non-available whenever HA is restarted.
Same with a Philips Hue white ambiance E26/E27 (8718696548738)

This happens if
```
advanced:
  availability_timeout: 30
```
is set.
There is no error to ping the device.

Pair a "Philips Hue White Single bulb B22" device (similar to https://www.philips-hue.com/en-au/p/hue-white-1-pack-b22/8718699631185, though the end serial appear different)

When HA is restarted, z2m sent the following:
info  2020-07-25 20:36:40: MQTT publish: topic 'zigbee2mqtt/sebastien_light_2', payload '{"state":"OFF","brightness":0,"update_available":false}'
info  2020-07-25 20:45:26: MQTT publish: topic 'zigbee2mqtt/dressing_light_1', payload '{"state":"OFF","linkquality":48,"update_available":false,"brightness":0,"color_temp":366}'

here sebastien_light_2 will be marked as offline by HA while dressing_light_1 is available.

The only difference I can tell from the log is the linkquality property is missing.

## Debug Info
Zigbee2mqtt version: 1.14.1
Adapter hardware: CC26X2R1
Adapter firmware version: 4.10.00.78 CC26X2R1_20200417.zip

**Comment by Koenkk** [comment]
I don't expect the missing `linkquality` causing Home Assistant marking devices as unavailable (it is pretty common for bulbs to have no linkquality as they normally don't send messages to the coordinator). Are you using https://www.zigbee2mqtt.io/information/availability.html ?

**Comment by jyavenard** [comment]
> I don't expect the missing `linkquality` causing Home Assistant marking devices as unavailable (it is pretty common for bulbs to have no linkquality as they normally don't send messages to the coordinator). Are you using https://www.zigbee2mqtt.io/information/availability.html ?

I am yes. Would this have an impact?

**Comment by Koenkk** [comment]
Yes, if the device is not reachable zigbee2mqtt will mark them as unavailable when using this feature. (You can check the logs to see if ping fails or succeeds)

**Comment by jyavenard** [comment]
> 
> 
> Yes, if the device is not reachable zigbee2mqtt will mark them as unavailable when using this feature. (You can check the logs to see if ping fails or succeeds)

I never see any messages with those lights about a failure to ping them so long as they are powered (even if off).
There will be a message about the light not being reachable once the light is turned off at the wall.

However, they will always show up as offline as soon as HA is restarted.

So there's something missing in how z2m is communicating the state once it gets the hass/status via mqtt. don't know what that is though

**Comment by jyavenard** [comment]
I restarted z2m to test the behaviour according to availability_timeout;

And now the lights are all reported the linkquality, and all are marked as online!
Seems that restarting zigbee2mqtt fixed the issue.

**Comment by Koenkk** [comment]
Good! Are you able to reproduce the issue? If not please close.

**Comment by jyavenard** [comment]
I can't reproduce now.

I think this is related to me adding those devices and then restarting HA.
A recently added device seems to not have its status properly reported when HA restart.
