### ISSUE TITLE
Update complete with 3 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by hoangtuit** [Koenkk/zigbee2mqtt#397]
Hi, I update zigbee2mqtt to last version. I run 'npm install' and it's complete with  3 moderate severity vulnerabilities. I tried 'npm audit fix' but it's not work.

```
753 packages from 815 contributors and audited 1612 packages in 82.267s
found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

![image](https://user-images.githubusercontent.com/12227977/45876362-a5574600-bdc4-11e8-9986-21bf1435c306.png)

**Comment by Koenkk** [comment]
These issues are caused by dependencies of zigbee2mqtt -> when dependencies update it's dependencies this will be solved -> not within the scope of zigbee2mqtt.

**Comment by dirkclemens** [comment]
downgrade to node v v8.11.2, if your version is newer by running nvm (https://github.com/creationix/nvm)
