### ISSUE TITLE
Wrong identification of device

### ISSUE THREAD

**Issue by galzil** [Koenkk/zigbee2mqtt#3989]
[Lonsonho X711A](https://www.zigbee2mqtt.io/devices/X711A.html) light switch is identified as: TuYa Curtain motor (TS0601)
I'll appreciate help with this

**Comment by galzil** [comment]
I've removed both TS0601 items from devices.js
Curtain motor
TS0601_thermostat

there's a Lonsonho switch there, but it's not recognized
` {
        zigbeeModel: ['TS0011'],
        model: 'GDKES-01TZXD',
        vendor: 'TuYa',
        description: 'Smart light switch - 1 gang without neutral wire',
        supports: 'on/off',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
    },`

I've added
`{
		zigbeeModel: ['TS0601'],
		model: 'ZSQB-SFB-11ZG',
        vendor: 'Tuya',
        description: '1 gang one way switch no neutral',
        supports: 'on/off',
        fromZigbee: [fz.tuya_switch2, fz.ignore_time_read],
        toZigbee: [tz.tuya_switch_state],
    },`

which solves the problem locally

**Comment by galzil** [comment]
Maybe it's a newer version,
Had to add to the convertors as well

`tuya_switch3: {
        cluster: 'manuSpecificTuyaDimmer',
        type: ['commandSetDataResponse', 'commandGetData'],
        convert: (model, msg, publish, options, meta) => {
            const multiEndpoint = model.meta && model.meta.multiEndpoint;
            const dp = msg.data.dp;
            const state = msg.data.data[0] ? 'ON' : 'OFF';
            if (multiEndpoint) {
                const lookup = {257: 'l1', 258: 'l2', 259: 'l3'};
                const endpoint = lookup[dp];
                if (endpoint in model.endpoint(msg.device)) {
                    return {[`state_${endpoint}`]: state};
                }
            } else if (dp === 257) {
                return {state: state};
            }
            return null;
        },
    },`

**Comment by Koenkk** [comment]
Can you share your `data/database.db` entry of this device?

**Comment by galzil** [comment]
@Koenkk this is the line:
`{"id":3,"type":"Router","ieeeAddr":"0x842e14fffe13ceae","nwkAddr":5929,"manufId":4098,"manufName":"_TZE200_7tdtqgwv","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_7tdtqgwv","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[]}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1595912320360}`

**Comment by Koenkk** [comment]
Can you check if it works now?

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by galzil** [comment]
I will check it soon. 
Please note, I'm not sure it's the same as the other switch. It looks the same but there's also a small difference in the converter

**Comment by galzil** [comment]
This issue seems like it's the same device [ZTS-EUB1 moeshouse zigbee wall switch](https://github.com/Koenkk/zigbee2mqtt/issues/3970),
I was wrong referncing Lonsonho X711A,
I updates: tuya_switch2 to
`tuya_switch3: { cluster: 'manuSpecificTuyaDimmer', type: ['commandSetDataResponse', 'commandGetData'], convert: (model, msg, publish, options, meta) => { const multiEndpoint = model.meta && model.meta.multiEndpoint; const dp = msg.data.dp; const state = msg.data.data[0] ? 'ON' : 'OFF'; if (multiEndpoint) { const lookup = {257: 'l1', 258: 'l2', 259: 'l3'}; const endpoint = lookup[dp]; if (endpoint in model.endpoint(msg.device)) { return {[state_${endpoint}]: state}; } } else if (dp === 257) { return {state: state}; } return null; }, },`

**Comment by Koenkk** [comment]
What is the difference between tuya_switch3 ad tuya_switch2? I don't see it.

**Comment by galzil** [comment]
@Koenkk it's a very small difference, I added "commandSetDataResponse" which was missing for the status responce
`No converter available for 'ZSQB-SFB-11ZG' with cluster 'manuSpecificTuyaDimmer' and type 'commandSetDataResponse' and data '{"status":0,"transid":107,"dp":257,"fn":0,"data":{"type":"Buffer","data":[1]}}'`
`type: ['commandSetDataResponse', 'commandGetData'],`

**Comment by Koenkk** [comment]
I've already added that a few days ago (latest dev branch): https://github.com/Koenkk/zigbee-herdsman-converters/blob/259acf98cb8f0f0254c4a7aadc0d5b2347cd9667/converters/fromZigbee.js#L5114 , so that looks good!

Please let me know if it works out-of-the-box in the latest dev branch.

**Comment by Tontze** [comment]
@galzil Does your switch start pairing procedure atomatically (fast blinking) when you power it up ? Does it also have beep sound when operated ? Just want to make sure we have same switch :)

**Comment by galzil** [comment]
@Tontze Yes, it's the same one. 
It's blinking on powering and starts pairing. 
I got it to work with the changes I made. 
I will test the dev branch later when I get back home. It should work. 
I didn't know about the beep sound when I bought it, the seller told me it can't be muted, very annoying.

**Comment by Tontze** [comment]
@galzil yeah, beeping is very annoying. I have lonsonho also, its so much better. No beeping and much softer click too.

**Comment by galzil** [comment]
@Koenkk I've just tested the dev branch, the switch was paired out-of-the-box.
`Device '0x842e14fffe13ceae' is supported, identified as: Lonsonho 1 gang switch (X711A)`
Thank you so much for your work and quick responce

**Comment by Tontze** [comment]
Im having hard time to get it ti work, i see it pairing, and supported (X711A), but see also no converter found messages, do they matter ? It announces to mqtt, but doesnt respond to mqtt state on/off ?

**Comment by galzil** [comment]
@Tontze Did you update to the newest dev version?
You need to unpair and pair again (5 short presses and than 1 long press until it blinks)

**Comment by Tontze** [comment]
> 
> 
> @Tontze Did you update to the newest dev version?
> You need to unpair and pair again (5 short presses and than 1 long press until it blinks).
> I'm new to this too, learning as I go

i did yes

**Comment by galzil** [comment]
Very weired.
I just had to re-flash my cc2531 stick as it stopped working for some reason.
I re-installed the dev branch (as I went back to the master) and re-paired my devices, it was paired succesfully and works well.
Maybe try editing the FromZigbee.js yourself?
you need to change only one line, look for tuya_switch2
edit
`type:  'commandGetData',`
to
`type: ['commandSetDataResponse', 'commandGetData'],`

**Comment by Tontze** [comment]
As i am in dev branch, i have that edit allready.. This is what i see after resetting the device : 

warn  2020-07-30 17:17:12: Device '0xec1bbdfffe79ddee' left the network
info  2020-07-30 17:17:12: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0xec1bbdfffe79ddee"}}'
info  2020-07-30 17:17:15: Device '0xec1bbdfffe79ddee' joined
info  2020-07-30 17:17:15: Starting interview of '0xec1bbdfffe79ddee'
info  2020-07-30 17:17:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xec1bbdfffe79ddee"}}'
info  2020-07-30 17:17:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xec1bbdfffe79ddee"}}'
debug 2020-07-30 17:17:15: Device '0xec1bbdfffe79ddee' announced itself
info  2020-07-30 17:17:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0xec1bbdfffe79ddee"}}'
debug 2020-07-30 17:17:15: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"modelId":"TS0601"}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZE200_7tdtqgwv"}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"manufacturerName":"_TZE200_7tdtqgwv"}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"powerSource":1}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":3}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"appVersion":82}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"appVersion":82}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"stackVersion":0}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"hwVersion":1}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{"dateCode":""}'
debug 2020-07-30 17:17:16: Received Zigbee message from '0xec1bbdfffe79ddee', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:16: No converter available for 'X711A' with cluster 'genBasic' and type 'readResponse' and data '{}'
info  2020-07-30 17:17:16: Successfully interviewed '0xec1bbdfffe79ddee', device has successfully been paired
info  2020-07-30 17:17:16: Device '0xec1bbdfffe79ddee' is supported, identified as: Lonsonho 1 gang switch (X711A)
info  2020-07-30 17:17:16: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0xec1bbdfffe79ddee","model":"X711A","vendor":"Lonsonho","description":"1 gang switch","supported":true}}'
debug 2020-07-30 17:17:21: Received Zigbee message from '0xec1bbdfffe79ddee', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:26: Received Zigbee message from '0xec1bbdfffe79ddee', type 'attributeReport', cluster 'genBasic', data '{"65506":21,"appVersion":82}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:26: No converter available for 'X711A' with cluster 'genBasic' and type 'attributeReport' and data '{"65506":21,"appVersion":82}'
debug 2020-07-30 17:17:26: Received Zigbee message from '0xec1bbdfffe79ddee', type 'attributeReport', cluster 'genBasic', data '{"65503":"\u0015��&\u0012\u0017��&\u0013"}' from endpoint 1 with groupID 0
debug 2020-07-30 17:17:26: No converter available for 'X711A' with cluster 'genBasic' and type 'attributeReport' and data '{"65503":"\u0015��&\u0012\u0017��&\u0013"}'

**Comment by galzil** [comment]
@Tontze just to let you know, I just found out there's a way to turn the beep off. 
Click 4 times, keep pressing on the forth click. There will be a beep after a few seconds, keep holding until you hear 2 beeps. That's it. No more beeping!

**Comment by Tontze** [comment]
@galzil awesome, thnx for sharing!

**Comment by Koenkk** [comment]
Does it work as expected for you both now?

**Comment by Tontze** [comment]
Cant get it working :/ Log is few post up

**Comment by galzil** [comment]
Mine's working. 
The re-flashing was due to something else (not sure what).

**Comment by Tontze** [comment]
@galzil do you see those same "no convertor" messages as i do ? Im starting to think that i have received defective switch, i cannot get it to respond mqtt payloads :|

**Comment by galzil** [comment]
@Tontze sorry, it's working fine for me, no errors. 
Try ordering [X711A](https://a.aliexpress.com/_d7huMfK), 
although it's an End Device and not a Router like this one

**Comment by Tontze** [comment]
I have three X711A, they do work nicely :) one without neutral and 2 with neutral. Neutral ones are not installed yet tho. I think the ones with neutral wire do work as router ? Ones without obviously dont :)

**Comment by Tontze** [comment]
btw, is yours moeshouse switch with, or without neutral ?

**Comment by galzil** [comment]
Currently all my zigbee devices are without neutral.
I actually think my X711A and X712A are recognized wrongly. I'll look for a similar issue as they should be Routers

**Comment by Tontze** [comment]
Ok, now, my moes switch is with neutral, so after all, it is different switch than yours.
