### ISSUE TITLE
Device unresponsive issue, unknown devices issue, contents have been formatted as required.

### ISSUE THREAD

**Issue by likellindil** [Koenkk/zigbee2mqtt#3996]
# Bug Report # 1
## What happened
**Devices become unresponsive randomly.**

The system is built on the CC26X2R1 coordinator along with two CC2530 routers. 
My devices are Xiaomi motion sensors, light switches, power switches, door & window sensors, smoke sensors, and covers. 
It works well after the setup, however, every day some of the devices become unresponsive. 
I have to allow join in Z2MA and repair those devices every morning.
It can happen on any of those devices, not limited to those battery-powered sensors. 

## What did you expect to happen
It should work stably after being configured. 

## How to reproduce it (minimal and precise)
Nothing needs to be done, just check device status in Z2MA every day.

## Debug Info
Zigbee2mqtt version: 1.14.2 ( run as an add-on in HA )
Adapter hardware: CC26X2R1
Adapter firmware version: CC26X2R1_20200417

# Bug Report # 2
## What happened
**Unknown devices randomly joined.**

When I submitted this post, I thought it was the Ikea controller.
However, now more and more unknown devices have joined my network.

There are now 5 devices there with no model and component recognized.
There was only one yesterday when I checked it in Z2MA.
During the last 24 hours, join is not allowed at all in Z2MA.
Those devices can't be removed anyway and no entity is created in HA.

All devices in my house have been added into the network and work correctly so I have no idea where they come from.

## What did you expect to happen
Those unknown devices can be removed

## How to reproduce it (minimal and precise)
Nothing needs to be done, just check device status in Z2MA every day.

## Debug Info
Zigbee2mqtt version: 1.14.2 ( run as an add-on in HA )
Adapter hardware: CC26X2R1
Adapter firmware version: CC26X2R1_20200417

**Comment by fwelvering** [comment]
Hello,

I have the same issue, some of my devices get unresponsive.
Only way to fix this is re-pairing(joining) the device
