### ISSUE TITLE
WSDCGQ11LM sensors - check/send interval?

### ISSUE THREAD

**Issue by zigfrid-1** [Koenkk/zigbee2mqtt#401]
hello,

i'm using a few WSDCGQ11LM sensors and want to know if there is a settings to set an send/check interval?

is there any logic behind? how often will the sensor send it's data to zigbee2mqtt? because sometimes it is sending in a 10 minute inverval and sometimes i have to wait a hour to get a new state....

thank you!
-zig

**Comment by evildad** [comment]
It should be explained here :

https://github.com/Koenkk/zigbee2mqtt/issues/327

**Comment by ciotlosm** [comment]
@zigfrid-1 Do you need more information or are you ok to close this issue?
