### ISSUE TITLE
assist for adding support for new device 

### ISSUE THREAD

**Issue by hometheater13** [Koenkk/zigbee2mqtt#4024]
Need assist to add support for new devices   (Somgoms –Tuya : modelID : tdtqgwv, bordckq, hpb9yts)

Link's to Products :

Link to touch switch :

https://www.aliexpress.com/item/4000607858705.html?spm=a2g0o.productlist.0.0.35936519JifRv8&algo_pvid=38b7218d-5386-4120-8110-c5da754da9a7&algo_expid=38b7218d-5386-4120-8110-c5da754da9a7-36&btsid=0ab6f82115963453933602493e29d7&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

Link to touch switch curtain and dimmer :

https://www.aliexpress.com/item/4001242513879.html?spm=a2g0o.productlist.0.0.35936519JifRv8&algo_pvid=f00df4e7-30f3-4409-bf57-8aa2261eb99a&algo_expid=f00df4e7-30f3-4409-bf57-8aa2261eb99a-5&btsid=0ab6f83115963498468512114eedd9&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

My codes to make it work for all switches  :
fromZigbee
          
    tuya_dimmer1: {
        cluster: 'manuSpecificTuyaDimmer',
        type: 'commandSetDataResponse',
        convert: (model, msg, publish, options, meta) => {
            const key = msg.data.dp;
            const val = msg.data.data;
            if (key === 257) {
                return {state: (val[0]) ? 'ON': 'OFF'};
            } else {
                const level = val[2]*256 + val[3];
                const normalised = (level - 10) / (1000 - 10);
                return {brightness: Math.round(normalised * 254), level: level};
            }
        },
    },
	
    tuya_switch3: {
        cluster: 'manuSpecificTuyaDimmer',
        type: 'commandSetDataResponse',
        convert: (model, msg, publish, options, meta) => {
            const multiEndpoint = model.meta && model.meta.multiEndpoint;
            const dp = msg.data.dp;
            const state = msg.data.data[0] ? 'ON' : 'OFF';
            if (multiEndpoint) {
                const lookup = {257: 'l1', 258: 'l2', 259: 'l3'};
                const endpoint = lookup[dp];
                if (endpoint in model.endpoint(msg.device)) {
                    return {[`state_${endpoint}`]: state};
                }
            } else if (dp === 257) {
                return {state: state};
            }
            return null;
        },
    },
	
   tuya_curtain1: {
        cluster: 'manuSpecificTuyaDimmer',
        type: 'commandSetDataResponse',
        convert: (model, msg, publish, options, meta) => {
            const dp = msg.data.dp;

            // Protocol description
            // https://github.com/Koenkk/zigbee-herdsman-converters/issues/1159#issuecomment-614659802

            switch (dp) {
            case 1025: // 0x04 0x01: Confirm opening/closing/stopping (triggered from Zigbee)
            case 514: // 0x02 0x02: Started moving to position (triggered from Zigbee)
            case 1031: // 0x04 0x07: Started moving (triggered by transmitter oder pulling on curtain)
                return {'running': true};
            case 515: { // 0x02 0x03: Arrived at position
                const position = msg.data.data[3];

                if (position > 0 && position <= 100) {
                    return {running: false, position: position};
                } else if (position == 0) { // Report fully closed
                    return {running: false, position: position};
                } else {
                    return {running: false}; // Not calibrated yet, no position is available
                }
            }
            case 261: // 0x01 0x05: Returned by configuration set; ignore
                break;
            default: // Unknown code
                console.log(`owvfni3: Unhandled DP #${dp}: ${JSON.stringify(msg.data)}`);
            }
        },
    },	

toZigbee 
find similar from tuya that works  :  tuya_switch_state, tz.tuya_curtain_control, tz.tuya_dimmer_state, tz.tuya_dimmer_level
    
device.js
    {
        zigbeeModel: ['tdtqgwv'],
        model: 'ZSTY-SM-11ZG-US-W',
        vendor: ' Somgoms',
        description: '1 gang switch',
        supports: 'on/off',
        fromZigbee: [fz.tuya_switch3, fz.ignore_time_read, fz.ignore_basic_report],
        toZigbee: [tz.tuya_switch_state],
    },
    {
        zigbeeModel: ['bordckq'],
        model: 'ZSTY-SM-1CTZG-US-W',
        vendor: 'Somgoms',
        description: 'Curtain Switch',
        supports: 'open, close, stop, position',
        fromZigbee: [fz.tuya_curtain1, fz.ignore_basic_report],
        toZigbee: [tz.tuya_curtain_control, tz.tuya_curtain_options],
    },
	{
        zigbeeModel: ['hpb9yts'],
        model: 'ZSTY-SM-1DMZG-US-W',
        vendor: 'Somgoms',
        description: 'Dimmer Switch',
        supports: 'on/off, brightness',
        fromZigbee: [fz.tuya_dimmer1, fz.ignore_basic_report],
        toZigbee: [tz.tuya_dimmer_state, tz.tuya_dimmer_level],
       
    },
	

if u need can attache md files and pic for this product's 
	
don't know hot to pull this in project ..
Have a week! Great project.
P/s: If you need more details please ask and I try to provide it .

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
