### ISSUE TITLE
Future Request: Bind only specific cluster

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#4027]
It would be great to be able to bind  only to specific cluster when binding to a group or device.

For instance, if I have a remote which is able to use the OnOff cluster and regulate intensity, I may want to just use the OnOff, and don't bind the other cluster/s.

Is it possible right now?
Otherwise, could you implement it?

**Comment by sjorge** [comment]
This is already implemented on the current dev using the new api, you can optionally specify an array of clusters in the payload.

**Comment by jd1900** [comment]
> This is already implemented on the current dev using the new api, you can optionally specify an array of clusters in the payload.
> 
> [946ebe1](https://github.com/Koenkk/zigbee2mqtt/commit/946ebe16b6a375af179f248b578d9e48a950e279)

Great! 
Thank you for the information. I guess we'll need some time until getting into the main branch and update the docs.
