### ISSUE TITLE
Pairing Lupus 12050

### ISSUE THREAD

**Issue by rkupfer2020** [Koenkk/zigbee2mqtt#4029]
Hi folks,
during pairing multiple LUPUS 12050 I receive:
"qtip="zigbee2mqtt:warn  2020-08-03 17:00:53: Received message from unsupported device with Zigbee modelPSMP5_00.00.05.10TC'"

These are definitely Lupus 12050 which worked well with Phoscon / Conbee II

May be it's an older/newer firmware?
Any ideas/thoughts on that?

Best regards
Roger

**Comment by rkupfer2020** [comment]
sorry I am wrong. This is a LUPUS 12065 light sensor. Any chance to get it working with zigbee2mqtt?

**Comment by rkupfer2020** [comment]
Changed devices.js to 
zigbeeModel: ['PSM_00.00.00.35TC', 'PSMP5_00.00.02.02TC', 'PSMP5_00.00.05.10TC'], 
model: 'PSM-29ZBSR',

**Comment by Koenkk** [comment]
added, thanks!
