### ISSUE TITLE
How to pair Immax Neo bulb and Remote same time?

### ISSUE THREAD

**Issue by vampywiz17** [Koenkk/zigbee2mqtt#4032]
## Debug Info
Zigbee2mqtt version: 1.14.2 
Adapter hardware: CC2531
Adapter firmware version: 20190608

Hello there,

I successfully pair Immax Neo RGBW bulb (E14) . After that i try to pair the bulb to the remote:  https://www.immaxneo.cz/en/products/immax-neo-remote-control-rgbcct-zigbee-3-0/

But when i pair remote, zigbee2mqtt not working anymore.

If i think correctly, it need to somehow pair the bulb and the remote... But i not faund any documentation, how to pair a remote...

That is all that i found it: https://www.immaxneo.cz/wp-content/uploads/2018/10/Neo-navod-ovladac-A4-multilanguage-curves.pdf

My goal is simple. I do not want to manage the remote on zigbee2mqtt, only manage the bulb in this way. but besides i would like to manage the bulb directly with remote (i would like to work, that the zigbee2mqtt is not working)

**Comment by vannetta** [comment]
How do you pair Immax ?
