### ISSUE TITLE
group color_temp does not update group color.{x,y} and in reverse

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee2mqtt#4034]
# Bug Report
## What happened
When changing one bulbs color_temp or color value (x,y), the other gets recalculated and published, for example setting color_temp: 400 -> "x":0.476993298233858,"y":0.413675289942435

This does not however work for groups. Moreover, the bulb entities in the group don't update this value as well (eg setting color_temp for a group will update color_temp for each bulb, but not their x,y values). 

The reverse for x,y is true as well, color_temp does not get updated either for the group or the bulbs in the group

## What did you expect to happen
Group behaviour for attributes would be the same as entity attribute

## How to reproduce it (minimal and precise)
Create a group of 2 bulbs, 
change color_temp for one bulb, notice x,y following suit
change color_temp for the group, notice x,y is not changed

**Comment by Koenkk** [comment]
Fixed, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
