### ISSUE TITLE
IR blaster zigbee

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#4041]
Hi, I bought an ir blaster device, thinking it was compatible with z2m and it seemed like a great solution.
After receiving it I have seen that it is not compatible, if someone is interested in doing tests to see if they can get it to work I can supply the information they need or even send it to someone if they want to test with it because I am not able to send any message.

Regards

**Comment by NoWhere2Go19** [comment]
If it is not already supported, this is the first way to go
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

What's the model and manufacturer?
