### ISSUE TITLE
BlitzWolf duplicated in documentation

### ISSUE THREAD

**Issue by McGiverGim** [Koenkk/zigbee2mqtt#4047]
# Bug Report
## What happened
I don't know if this is the correct repo, but in the .io repo there is no option for open an issue.

![image](https://user-images.githubusercontent.com/2673520/89399683-14b55500-d713-11ea-80a5-5427924dae8b.png)

The BlitzWolf group appears twice, maybe the uppercase of the W is the culprit.

## What did you expect to happen
Only one BlitzWolf group

## How to reproduce it (minimal and precise)
Go to the official https://www.zigbee2mqtt.io/information/supported_devices.html

## Debug Info
Zigbee2mqtt version: -
Adapter hardware: -
Adapter firmware version: -

**Comment by Koenkk** [comment]
Thanks! I've updated the entry of `BW-SHP13` to use BlitzWolf instead of Blitzwolf.

When the documentation gets regenerated (on next z2m release, coming Wednesday) this issue will automatically be fixed.
