### ISSUE TITLE
Capteur Xiaomi contact inversé impossible

### ISSUE THREAD

**Issue by jonathanD91** [Koenkk/zigbee2mqtt#4052]
Je souhaite inverser l'information de mon capteur Xiaomi MCCGQ11LM.
J'ai basculé en binaire l'info du contact. Actuellement 1= fermé, 0= ouvert. Je clique sur "inversé " pour avoir 1= ouvert, 0= fermé. Malgré la commande inversé rien ne se passe et reste sur l'état d'origine.

**Comment by NoWhere2Go19** [comment]
English please

**Comment by jonathanD91** [comment]
Sorry, so i use google traduction: 

I want to invert the information of my Xiaomi MCCGQ11LM sensor.
I switched the contact info to binary. Currently 1 = closed, 0 = open. I click on "inverted" to have 1 = open, 0 = closed. Despite the reverse order, nothing happens and remains in the original state.
