### ISSUE TITLE
Adding a new device Oeeone E27 Smart Filament LED Lampe ZigBee 7W

### ISSUE THREAD

**Issue by wlauppe** [Koenkk/zigbee2mqtt#4071]
Hello, i use your excellent zigbee2mqtt software and am quite happy with it. 

All devices worked out of the box until now, But one bulb doesnt, and i tried to 
follow the guide: 

https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

to create a new configuration, but i need some help. 

The first question which i dont any clear answer to, is 

if i add a new device block in devices.js
how does zigbee2mqtt get an id of this specific device version and how does it make the connection to the device block? 

The device is called 

Oeeone E27 Smart Filament LED Lampe ZigBee 7W

and in the manual if found the following numbers: 

A191A60 LED smart bulb
PN120209P2
PN230172P2

does this help? 

In the log of zigbee2mqtt i just get this comment: 

```
zigbee2mqtt:warn  2020-08-10 13:23:30: Received message from unsupported device with Zigbee model 'undefined'
zigbee2mqtt:warn  2020-08-10 13:23:30: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

and the devices are paired correctly and can be found in the configuration.yaml

**Comment by Koenkk** [comment]
- Can you try repairing it a few times (first remove it through https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigremove). Do you always get `Received message from unsupported device with Zigbee model 'undefined'`? (I'm worried about the `undefined` part).
- If so, please share the `data/database.db` entry of this device
