### ISSUE TITLE
Updating zigbee2mqtt

### ISSUE THREAD

**Issue by kaelsaes** [Koenkk/zigbee2mqtt#408]
Does the update procedure explained in the wiki (git checkout HEAD -- npm-shrinkwrap.json
git pull) update all directories and all files?

**Comment by ciotlosm** [comment]
@kaelsaes probably not the npm part. What are you trying to achieve? I'd recommend for normal usage to use more the containers than a manual installation.

**Comment by kaelsaes** [comment]
@ciotlosm 
Thanks for your answer.

I want to update zigbee2mqtt to the newest version.

What would be the correct way?

**Comment by jboeddeker** [comment]
I have no idea about the "correct way", but i follow the wiki in that regard. 

Started with 0.1.0 (or 0.1.1) and now am on 0.1.6.

**Comment by kaelsaes** [comment]
@jboeddeker 

The question is if the update procedure in the wiki updates all parts of the software including converters and so on?

Do I have to install the newest firmware for the coordinator also?

**Comment by jboeddeker** [comment]
I don't think the update leaves some parts out, never thought of that.

I did install the latest firmware last time, but the 2 to 3 times before not. So, i guess it is not necessary all the time.

**Comment by jwillmer** [comment]
i mentioned before that a update function would be nice. This function could also inform if you will need to update (flash) the firmware of your zigbee hardware.
