### ISSUE TITLE
missing Voltage Output in Osram smart+ Plug

### ISSUE THREAD

**Issue by BremerButjer** [Koenkk/zigbee2mqtt#4080]
If the socket is addressed directly with Zigbee, the output is also the power consumption. In MQTT this is apparently not transmitted. Can this be built in?

https://www.zigbee2mqtt.io/devices/AB3257001NJ.html

**Comment by Koenkk** [comment]
AFAIK this plug does not support power metering.

**Comment by NoWhere2Go19** [comment]
There is a channel for this by the device somehow, but it is useless as it does not report the actual power. As @Koenkk  stated, the Osram plug does not support power metering
