### ISSUE TITLE
Lonsonho X712A works wrong

### ISSUE THREAD

**Issue by Machaeon** [Koenkk/zigbee2mqtt#4088]
Changing state from zigbee2mqtt not always triggers switch. E.g. 
Z2m: off, Switch: off
Z2m: on, Switch off
Z2m: off, Switch on

**Comment by cheshic** [comment]
Same problem.

**Comment by rkiller2006** [comment]
I have 3 switches X711A, which always toggle instead of turn_on or turn_off. Who knows how to solve it?

**Comment by Machaeon** [comment]
There some difference betweet Lonsonho and other devices log.
X712A - Message repeats 4 times:
INFO: MQTT publish: topic 'zigbee/Bathroom switch', payload '{"linkquality":99,"state_l1":"ON","state_l2":"OFF"}'
INFO: MQTT publish: topic 'zigbee/Bathroom switch', payload '{"linkquality":97,"state_l1":"ON","state_l2":"OFF"}'
INFO: MQTT publish: topic 'zigbee/Bathroom switch', payload '{"linkquality":97,"state_l1":"ON","state_l2":"OFF"}'
INFO: MQTT publish: topic 'zigbee/Bathroom switch', payload '{"linkquality":97,"state_l1":"ON","state_l2":"OFF"}'

eWeLink SA-003-Zigbee - message repets 2 times:
INFO: MQTT publish: topic 'zigbee/Amp Switch', payload '{"linkquality":162,"state":"ON"}'
INFO: MQTT publish: topic 'zigbee/Amp Switch', payload '{"linkquality":162,"state":"ON"}'

**Comment by rkiller2006** [comment]
Hello Machaeon:
MY X711A switches send 3 times:
INFO: MQTT publish: topic 'zigbee2mqtt/Hallway light', payload '{"linkquality":73,"state":"OFF"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Hallway light', payload '{"linkquality":44,"state":"OFF"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Hallway light', payload '{"linkquality":44,"state":"OFF"}'

Sometimes with different messages:
INFO: MQTT publish: topic 'zigbee2mqtt/Bathroom ventilation', payload '{"linkquality":44,"state":"ON"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Bathroom ventilation', payload '{"linkquality":44,"state":"OFF"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Bathroom ventilation', payload '{"linkquality":44,"state":"ON"}'

But always the second message is correct state:

**Comment by Machaeon** [comment]
In my case second and third message shows right state.
Sometimes there only one message - in that cases switch doesn't reacts on command.

**Comment by Machaeon** [comment]
It seems that z2m uses last message for state detection. Is it posible to make it to use another (e.g. second) message?

**Comment by mgrom** [comment]
@Machaeon @rkiller2006  does this switch work good or not? Does it behave as router or end-device? Thanks for answers :)

**Comment by Pete118** [comment]
> @Machaeon @rkiller2006 does this switch work good or not? Does it behave as router or end-device? Thanks for answers :)

I would appreciate this information,too :)

**Comment by rkiller2006** [comment]
Hello, the switches work wrong. It's is router devices.

**Comment by UndeRus** [comment]
Same problem with X713A

**Comment by mgrom** [comment]
@rkiller2006 @UndeRus could you please be more specific, please? It'd be great to know what are possible problems with those devices.

**Comment by UndeRus** [comment]
@mgrom 
when i try to set state "on" or "off" on X713A it behaves like toggle, but it also works not every call

**Comment by UndeRus** [comment]
Today i tried to send into mosquitto 
```
mosquitto_pub -h localhost -t zigbee2mqtt/cabinet_3_wall_switch/set -m '{"state_l1": "ON", "state_l2": "OFF", "state_l3": "OFF"}'
```
It works like toggle, not like turn on the switch

**Comment by densavage** [comment]
Same problem with X711A

**Comment by Machaeon** [comment]
Still no news?
