### ISSUE TITLE
New dongle zigbee2mqtt compatible

### ISSUE THREAD

**Issue by papperone** [Koenkk/zigbee2mqtt#4099]
I don't know if this is the right place but cannot find any more suitable and on Discord I got adviced to open issue on GitHub.
I saw in the zigbee2mqtt.io there's no CC2538 dongle mentioned, I do have a tested one on my tindie store, based on a open source project, PCB has been redesigned, tested extesively and then put on my tindie. It works perfectly, it has the best performances in terms of coverage and due to the CC2538 can accept more than 150 devices.
Thanks to let me know if it's possible to mention it in this list: https://www.zigbee2mqtt.io/information/supported_adapters.html

**Comment by Koenkk** [comment]
I'm fine adding this (also own the dongle myself now). There was a pr open some time ago: https://github.com/Koenkk/zigbee2mqtt.io/pull/208 , but it hasn't been merged because english instructions on how to flash the stick were missing.

**Comment by papperone** [comment]
yes my dongle is based on that project https://www.tindie.com/products/GiovanniCas/cc2538-cc2592-zigbee-dongle-new-zb30/

if you woudl like I can make instruction in English how to flash the module with JTAG programmer, as well (with new PCB release I'm making now) via USB interface, just let me know...

**Comment by Koenkk** [comment]
Yes, please make a pr.

**Comment by papperone** [comment]
> 
> 
> Yes, please make a pr.

Sorry to ask as I've never did it, do you have a template or instructions how to do it properly?

**Comment by Koenkk** [comment]
@papperone you can click the pencil button here: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/supported_adapters.md 

![image](https://user-images.githubusercontent.com/2892853/90725495-8a4b2480-e2c0-11ea-9e3b-236b7d6507c4.png)
