### ISSUE TITLE
Yale Lock making trouble

### ISSUE THREAD

**Issue by todfox** [Koenkk/zigbee2mqtt#410]
When I pair an unsupported device, Yale Door Lock, I now get this error.

```
{"message":"request unsuccess: 16","stack":"Error: request unsuccess: 16
    at /opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21
    at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:258:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at CcZnp.emit (events.js:211:7)
    at CcZnp._mtIncomingDataHdlr (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:360:14)
    at Immediate.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:336:22)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"}
```

**Comment by tb-killa** [comment]
Hi ..
which versions of node and npm are you using? 
Need to get the actual version (including hash) from your zigbee2mqtt instance.
which firmware for C22531 are you using?

**Comment by todfox** [comment]
I using the 2530 firmware from here
https://raw.githubusercontent.com/dzungpv/Z-Stack-firmware/master/coordinator/CC2530/bin/CC2530ZNP-Prod.hex

Node version = v8.11.4
Npm = 5.6.0

**Comment by tb-killa** [comment]
You use as Coordinator the type CC2530 ?
Please use the official supported firmware from wiki:
https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices
https://github.com/kirovilya/files/blob/master/CC2530ZNP-Pro-Secure_LinkKeyJoin.hex

Finally test again and report if status is working.

**Comment by todfox** [comment]
Yes I have a CC2530 mounted on a development board. When I use the
supported firmware, I get this error when trying to start zigbee2mqtt.

{"message":"request timeout","stack":"Error: request timeout\n    at
CcZnp.<anonymous>
(/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at
Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n
  at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous>
(/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at
ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at
Timer.listOnTimeout (timers.js:290:5)"}

**Comment by tb-killa** [comment]
Does this failure only apply if you add this type of device or is the error Generally?

**Comment by todfox** [comment]
Generally. I have rolled back my database to at state before I added the
Yale Lock. The program doesn't boot with the supported firmware.

Here is the hardware I am using.
https://www.aliexpress.com/item/ZigBee-CC2530-Sensor-Node-Baseboard-Functional-Module-Expansion-Board-USB-Port-24MHz-256KB/32767498002.html
and
https://www.aliexpress.com/item/CC2530-Zigbee-UART-Wireless-Core-Board-Development-Board-CC2530F256-Serial-Port-Wireless-Module-2-4GHz/32767470382.html

**Comment by tb-killa** [comment]
@Koenkk do you could help?

**Comment by Koenkk** [comment]
Could you reflash your device?

**Comment by Koenkk** [comment]
So do you still have this problem with a fresh CC2530 and a clean database.db file?

**Comment by todfox** [comment]
Start with a clean database? That's painful. I won't be able to try that
until I am back from traveling in three weeks.

**Comment by CanuckianOz** [comment]
> When I pair an unsupported device, Yale Door Lock, I now get this error.
> 
> ```
> {"message":"request unsuccess: 16","stack":"Error: request unsuccess: 16
>     at /opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/zdo.js:46:21
>     at CcZnp.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:258:13)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at CcZnp.emit (events.js:211:7)
>     at CcZnp._mtIncomingDataHdlr (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:360:14)
>     at Immediate.<anonymous> (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:336:22)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)"}
> ```

Hi todfox, 

Did you get anywhere with the Yale Lock? I can't get it to post any activity in the Zigbee2MQTT log when I lock or unlock it, so I can't begin to troubleshoot. Would be interested if you managed to get it to work.

**Comment by todfox** [comment]
Hi @CanukianOz. Sadly I haven't had the time to look into it. It is on my
long list of things to do. If you figure it out please let me know.
