### ISSUE TITLE
Support for Tuya Zigbee Signal Repeater

### ISSUE THREAD

**Issue by milobt** [Koenkk/zigbee2mqtt#4104]
Just wondering if anyone has tried to add the Tuya Zigbee Signal Repeater and if not how likely is it to be compatible?
At about £12 on Aliexpress is a fraction more expensive than the £8 Ikea one, but the Tuya offering is smaller and would easily plug into USB sockets on wall socket face plates etc without being noticed.

[https://www.aliexpress.com/item/4001230151655.html?spm=a2g0o.cart.0.0.71873c00I1WHPh&mp=1](https://www.aliexpress.com/item/4001230151655.html?spm=a2g0o.cart.0.0.71873c00I1WHPh&mp=1)

**Comment by Hedda** [comment]
Any news on compatibility with Tuya Zigbee 3.0 USB Range Extender (a.k.a. Zigbee Signal Repeater) as a Zigbee Router device?

Tuya SKU: RP280

It is however not clear if it really works as a Zigbee Router with third-party gateways or if need Tuya gateway as their description:

https://community.home-assistant.io/t/tuya-zigbee-signal-repeater-working-with-zha-and-conbee-2/249329

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4175

https://github.com/Koenkk/zigbee2mqtt/issues/4104

https://zigbee.blakadder.com/Tuya_TS0207.html

Signal Repeater Zigbee 3.0 Model TS0207 manufactured by Tuya

Zigbee ID: "TS0207"; "_TZ3000_m0vaazab"; "FNB54-WTS08ML1.0"

https://www.aliexpress.com/i/1005001459823340.html?spm=2114.12057483.top.4.55932e050QWoD7

https://www.aliexpress.com/i/1005001274714963.html

https://www.aliexpress.com/item/1005002441359324.html

https://www.aliexpress.com/i/1005002526017479.html

https://www.amazon.com/Extender-Protable-Amplifier-Gateway-Repeater/dp/B08MWBKK4P

https://www.amazon.com/Repeaters%EF%BC%8CKKmoon-Amplification-Transmitters-Enhancement-Compatible/dp/B08R3QC9X6/

![image](https://user-images.githubusercontent.com/6320001/117784884-4e882e80-b244-11eb-8c3a-3082308368dc.png)

![image](https://user-images.githubusercontent.com/6320001/117784454-dfaad580-b243-11eb-9a3f-b6262fdada58.png)

![image](https://user-images.githubusercontent.com/6320001/117784373-cb66d880-b243-11eb-968a-d3ea5c630117.png)

![image](https://user-images.githubusercontent.com/6320001/117785712-22b97880-b245-11eb-94a2-5781c0eccf8f.png)

![image](https://user-images.githubusercontent.com/6320001/117784561-fd783a80-b243-11eb-8f12-bb688ec1d2ec.png)

![image](https://user-images.githubusercontent.com/6320001/117784348-c3a73400-b243-11eb-818b-f680f4a1aa06.png)

![image](https://user-images.githubusercontent.com/6320001/117785280-b76fa680-b244-11eb-929e-01576ca2c3c9.png)
