### ISSUE TITLE
Shenzhen Homa HLD812-Z-SC Zigbee Dimmer added as ModelID: HOMA000A and so not recognised

### ISSUE THREAD

**Issue by milobt** [Koenkk/zigbee2mqtt#4105]
Recently added a Shenzhen Homa HLD812-Z-SC Zigbee Dimmer, but it was added as ModelID: HOMA000A and so not recognised

**Comment by derFeierabend** [comment]
Same problem here. I don't know how to get the device running.
Any hint is very welcome.

**Comment by odenisenko** [comment]
{
        zigbeeModel: ['HOMA000A'],
        model: 'HLD812-Z-SC',
        vendor: 'ShenZhen_Homa',
        description: 'Zigbee 3.0 Led Dimmen',
        extend: preset.light_onoff_brightness,
    },

![image](https://user-images.githubusercontent.com/44768566/105232966-dcdf8400-5b71-11eb-9b83-cbb5e75cea88.png)
