### ISSUE TITLE
Using Xiaomi Smoke Alarm as a Siren for alarm system w Home Assistant

### ISSUE THREAD

**Issue by redeyejoe** [Koenkk/zigbee2mqtt#4133]
I would like to be able to use the smoke detector as my siren for my home security alarm system. I am running home assistant and I am using a cc2531 dongle to connect to the smoke detectors, but with the current version of the integration it only pulls the sensor info for smoke and for the battery status.  I ready issue #420 which seems to be attempting to do the same, but there did not  seem to be a clear answer.  Is there a way to be able to send a command to the detector to self test or sound off as a siren?

**Comment by Koenkk** [comment]
AFAIK this is not possible. There is also no option for this with the original Xiaomi gateway.
