### ISSUE TITLE
Nodon zigbee relay

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#4140]
hello:

I am trying to synchronize this device with the z2m library, it is added correctly and works well, the problem is that you can turn the relay on and off without problem but when the relay is operated from the external contact it does not report the change.

**database.db**
{"id":7,"type":"Router","ieeeAddr":"0x14b457fffe37a1ad","nwkAddr":31122,"manufId":4747,"manufName":"NODON","powerSource":"Mains (single phase)","modelId":"SIN_2_1","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SIN_2_1","manufacturerName":"NODON","powerSource":1,"zclVersion":3,"app		Version":1,"stackVersion":0,"hwVersion":1,"dateCode":"11-2019","swBuildId":""}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001caa6e29","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":0,"hwVersion":1,"dateCode":"11-2019","swBuildId":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1,"reporting":1},"lastSeen":1597915869023}

**devices.js**
    //Nodon
    {
        zigbeeModel: ['SIN_2_1'],
        model: 'SIN_2_1',
        description: 'switch zigbee with input',
        supports: 'on/off',
        vendor: 'Nodon',
        fromZigbee: [fz.on_off,fz.ignore_genOta],
        toZigbee: [tz.on_off],
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint);
        },

    },

**Comment by Koenkk** [comment]
Do you see anything in the debug log when operating the switch manually?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
