### ISSUE TITLE
quick fix to support device with unsupported version to devices.js.

### ISSUE THREAD

**Issue by kerryandjane** [Koenkk/zigbee2mqtt#4148]
# Bug Report
## What happened
Supported device https://www.zigbee2mqtt.io/devices/HLC610-Z.html has many models it seems. 
I see 'HOMA1002', 'HOMA0019' versions have support already. Out of the box my device wasn't. Quick fix needed.
Seaching the devices.db I see it's got a different model.
Same devices, HLC610-Z  just the model is HOMA0006. 

Adding 'HOMA0006' to the device in node_modules/zigbee-herdsman-converters/devices.js gets this device working as expected.
So it looks like this: 
   
```
    {                                         
        zigbeeModel: ['HOMA1002', 'HOMA0019', 'HOMA0006'],
        model: 'HLC610-Z',                  
        vendor: 'Shenzhen Homa',            
        description: 'Wireless dimmable controller',
        extend: generic.light_onoff_brightness,
    },  
```

## What did you expect to happen
I expected the device to be supported by default. Can you add this permanently add this model to device.js to the next update please?
## How to reproduce it (minimal and precise)
Sometimes I lose the device from devices.js so I made a script to check for the model in devices.js and add it if its not.

## Debug Info
Zigbee2MQTT version: 1.14.3
Adapter hardware: CC2531
Adapter firmware version:latest

thankyou.

**Comment by huub66** [comment]
@Koenkk can you also add model '053' to devices.js for HCL-610-Z, as this version has been shipped to me. Following above procedure made it working. Or do I need to create a new issue?

**Comment by Koenkk** [comment]
@huub66 done.

**Comment by huub66** [comment]
> @huub66 done.
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Thnx!
