### ISSUE TITLE
Cannot pair Ikea Dimmer switch

### ISSUE THREAD

**Issue by glentakahashi** [Koenkk/zigbee2mqtt#416]
This might be a stupid question, but do you need the ikea gateway to be able to pair ikea dimmer switches with zigbee2mqtt? Did a lot of searching but wasn't able to find a clear answer. No matter what I do I can't get them to pair (literally see no info/logs about anything related to them in debug mode), but another thought I had was that the devices may need to have their firmware upgraded.

EDIT: another thought, I'm running a custom firmware with MAX_NEIGHBOR_ENTRIES=1. Do these switches count as routers?

**Comment by Koenkk** [comment]
Keep the dimmer close to the coordinator (CC2531) and press the button on the dimmer 4 times (red light should flash).

**Comment by glentakahashi** [comment]
Okay this was just very finnicky to pair, took me dozens of tries to eventually get it to work. Anecdotally, I think it may have helped to issue a permit_join false and then true to somehow reset the cc2531, but might be placebo effect and I literally have no idea how that works :)
