### ISSUE TITLE
Raspberry pi 4 documentation recommended edit.

### ISSUE THREAD

**Issue by NF8C** [Koenkk/zigbee2mqtt#4165]
Include Raspberry PI4 in instructions
https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html
I followed the instructions and found that the raspberry P I4 should probably be included in the following statement

"NOTE: If you are using a Raspberry Pi 1 or Zero AND if you followed this guide, replace ExecStart=/usr/bin/npm start with ExecStart=/usr/local/bin/npm start."

Suggested edit:
"NOTE: If you are using a Raspberry Pi 1, PI 4, or Zero AND if you followed this guide, replace ExecStart=/usr/bin/npm start with ExecStart=/usr/local/bin/npm start."

**Comment by Koenkk** [comment]
This shouldn't be needed when installing nodejs following: https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#2-installing . Did you install it that way?

**Comment by NF8C** [comment]
I followed it as closely as possible.  Node js failed and I had to deviate
from the instructions to get it installed.  This must have been an error on
my part.

**Comment by ginkage** [comment]
Is your Pi 4 running 32-bit or 64-bit OS?

**Comment by NF8C** [comment]
I am on 32 bit.
Linux DietPi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
RPi4 4G
