### ISSUE TITLE
Pairing issue with Blaupunkt SCM-S1

### ISSUE THREAD

**Issue by cody82** [Koenkk/zigbee2mqtt#4166]
During pairing of Blaupunkt SCM-S1 I get this error message with zigbee2mqtt v1.14.2 with CC2531:
`zigbee2mqtt:info  2020-08-23 12:07:15: Successfully interviewed '0x00124b00187bb2d7', device has successfully been paired`
`zigbee2mqtt:info  2020-08-23 12:07:15: Device '0x00124b00187bb2d7' is supported, identified as: Blaupunkt Roller shutter (SCM-S1)`
`zigbee2mqtt:info  2020-08-23 12:07:15: Configuring '0x00124b00187bb2d7'`
`zigbee2mqtt:info  2020-08-23 12:07:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x00124b00187bb2d7","model":"SCM-S1","vendor":"Blaupunkt","description":"Roller shutter","supported":true}}'`
`zigbee2mqtt:error 2020-08-23 12:07:15: Failed to configure '0x00124b00187bb2d7', attempt 1 (Error: ConfigureReporting 0x00124b00187bb2d7/1 genLevelCtrl([{"attribute":"currentLevel","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/home/cody/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
    at Endpoint.<anonymous> (/home/cody/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/cody/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))`

The device is then listed in configuration.yaml but I cant control it.(Or I used the wrong commands?)
There are some other issue reports here with this device but I dont know if mine is the same issue or different.

**Comment by Koenkk** [comment]
Can you share the `data/database.db` entry of this device?

**Comment by cody82** [comment]
`{"id":29,"type":"EndDevice","ieeeAddr":"0x00124b00187bb2d7","nwkAddr":17062,"manufId":0,"manufName":"ClimaxTechnology","powerSource":"Mains (single phase)","modelId":"SCM-2_00.00.03.15","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":512,"inClusterList":[0,3,4,5,6,8,256,2821],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"SCM-2_00.00.03.15","manufacturerName":"ClimaxTechnology","powerSource":1,"zclVersion":1,"appVersion":59,"hwVersion":0,"dateCode":"20180327        "}}},"binds":[{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a206b","endpointID":1}]}},"appVersion":59,"hwVersion":0,"dateCode":"20180327        ","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1598177358563}`

**Comment by Koenkk** [comment]
We can workaround the configure error, but I'm more worried about the controlling part (as you should still be able to do this even when configure is failing). What do you see in the Zigbee2MQTT debug log when e.g. sending to `zigbee2mqtt/0x00124b00187bb2d7/set` payload: `{"position": 40}` or `{"state":"OPEN"}`/`{"state":"CLOSE"}`

**Comment by cody82** [comment]
Control works, thank you. I used the wrong commands(just "OPEN" without "state"). However I am quite confused by the behavior of this device.

**Comment by Koenkk** [comment]
Stop should stop the roller while it's moving.

**Comment by cody82** [comment]
Ok I played with it and it still does not behave as expected:
- STOP sometimes starts the motor when it was already stopped. Maybe this only happens if it was stopped by the endpoint of the motor.
- When STOPPING during CLOSE, the next CLOSE command will not work.
- I did not try the position command yet. I wonder how that should work because the device can not know the position of the roller.
Of course this is probably not related to zigbee2mqtt. Is it just a shitty device? The Xiaomi 2 channel relay seems to work more deterministic and is much cheaper even though it is not specifically designed for this use case.

**Comment by Koenkk** [comment]
Sorry I was wrong, this device does NOT support the stop command. It only support setting a position, when sending open/close it will be translated to the 0/100 position.

**Comment by cody82** [comment]
But it somehow reacts to STOP.

**Comment by Koenkk** [comment]
@cody82 yes, it will be the same as sending `CLOSE` or position 0.

**Comment by IVI053** [comment]
Also see https://github.com/Koenkk/zigbee-herdsman-converters/issues/1024
