### ISSUE TITLE
Add support for Paulmann 500.47 RGBW Controller

### ISSUE THREAD

**Issue by redpiramide** [Koenkk/zigbee2mqtt#4167]
Hi,

i am trying to pair a new Paulmann 500.47 RGBW Controller ([Link](https://de.paulmann.com/innenleuchten/smart-home/zigbee/smarthome-zigbee-maxled-rgbw-controller-max.-72w/50047)) but this time it is unsupported. I already got a Paulmann 500.47 working, but it is considered as 50049 and working fine since a year.

Zigbee2MQTT version: 1.14.3
Adapter hardware: CC2531
Adapter firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190109}}

Here is the line for the unsupported device:
`{"id":13,"type":"Router","ieeeAddr":"0x00158d00042012f0","nwkAddr":7200,"manufId":4624,"manufName":"Paulmann Licht","powerSource":"DC Source",
"modelId":"500.47","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,4,3,6,8,5,768,4096],"outClusterList
":[25],"clusters":{"genBasic":{"attributes":{"modelId":"500.47","manufacturerName":"Paulmann Licht","powerSource":4,"zclVersion":3,"appVersion
":15,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swBuildId":"1400-0001"}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":97,"
inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":15,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swB
uildId":"1400-0001","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1598101302486}`

The already old working 500.47 has the `"modelId":"RGBW light "`, that was added in #602
Because it's basicly the same as the 50049, i tried to extend this entry in the devices.js
`{
    zigbeeModel: ['RGBW light', '500.49', '500.47'],
    model: '50049',
    vendor: 'Paulmann',
    description: 'SmartHome Yourled RGB Controller',
    extend: generic.light_onoff_brightness_colortemp_colorxy,
}`

I am very limited in the testing, because i am using the home assistant addon. I repaired the device and it seems to work. However the correct entry with a proper description in the devices.js would be:
`{
    zigbeeModel: ['500.47'],
    model: '500.47',
    vendor: 'Paulmann',
    description: 'SmartHome Zigbee MaxLED RGBW controller max. 72W 24V DC',
    extend: generic.light_onoff_brightness_colortemp_colorxy,
}`

I kindly request to add this device to the supported devices.
Please let me know, if I can help with additional information.

Best regards,
Markus

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
