### ISSUE TITLE
Visualise ZigBee network

### ISSUE THREAD

**Issue by 57k** [Koenkk/zigbee2mqtt#417]
Hi everybody,
in order to understand my current Zigbee Network more easily, I would like to use a simple software, that can visualize my network. Which tools are you using?
Thanks in advance
Jens

**Comment by 57k** [comment]
just publish via mqtt 

zigbee2mqtt/bridge/networkmap

the value

graphviz

at the same time subscribe to 

zigbee2mqtt/bridge/networkmap/graphviz

my next problem is that I do not get all attached devices.

**Comment by kimonm** [comment]
I think it'd be easier to read the graphs if the friendly names were used as labels (vs. the numerical code). Does it make sense?

**Comment by thomasvt1** [comment]
> I think it'd be easier to read the graphs if the friendly names were used as labels (vs. the numerical code). Does it make sense?

https://github.com/Koenkk/zigbee2mqtt/commit/845a5cdce89c69dbeb3e1303f7d9496c6e58f295

;)

**Comment by Koenkk** [comment]
@kimonm it's already in the dev branch (will be in new zigbee2mqtt release)

**Comment by hoangtuit** [comment]
Hi, 
I used this command:

`mosquitto_sub -h $MQTT_SRV -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz | sfdp -Tpng > /tmp/map.$(date +%Y%m%d%H%M%S).png`

It's created a image file in tmp folder, but nothing in there (0 KB).

**Comment by aidbish** [comment]
> just publish via mqtt
> 
> zigbee2mqtt/bridge/networkmap
> 
> the value
> 
> graphviz
> 
> at the same time subscribe to
> 
> zigbee2mqtt/bridge/networkmap/graphviz
> 
> my next problem is that I do not get all attached devices.

tried this, but in logfile i get
zigbee2mqtt:warn 2018-10-5 18:05:50 Cannot handle MQTT message with topic 'zigbee2mqtt/bridge/networkmap' and message 'graphviz

do i need to install anything extra, i am using the latest-dev docker image

**Comment by lolorc** [comment]
@hoangtuit does the command return immediatly ? you don't have to ctrl-c it do you ?
what's the result of mosquitto_sub -h $MQTT_SRV -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz
when you send the graphviz command ?
it should output graphviz text data that you could either use with graphviz commands or 
http://www.webgraphviz.com/

@aidbish looks like your not running the latest version (1.0.6 atm) sorry but I'm clueless about docker.

**Comment by aidbish** [comment]
it was the formatting of my publish command that was incorrect
i now can see a scan starting in the logs, but it finishes within 1 second and nothing is shown if i subscribe to the topic

i have tried the following sub commands

mosquitto_sub -h 10.0.0.18 -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz

mosquitto_sub -h 10.0.0.18 -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz | sfdp -Tpng | display -

i have to ctrl-c as they never seem to complete

**Comment by hoangtuit** [comment]
@lolorc the command don't return. When i run  graphviz command

mosquitto_sub -h $MQTT_SRV -C 1 -t zigbee2mqtt/bridge/networkmap/graphviz

Nothing to return. I have 1 coordinator and 10 devices in my network

**Comment by lolorc** [comment]
Are you both using dev with the latest commits ?
if so, a bug has be introduced with the latest network map change (display friendlyname).
You might want to check my PR to see if it fixes it https://github.com/Koenkk/zigbee2mqtt/pull/443
or you can also edit https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/extension/networkMap.js#L41
and replace
```
const friendlyName = settings.getDevice(item.ieeeAddr).friendly_name;
```
by
```
const friendlyName = settings.getDevice(item.ieeeAddr) ? settings.getDevice(item.ieeeAddr).friendly_name : "";
```

**Comment by hoangtuit** [comment]
I did. But nothing happen.

**Comment by lolorc** [comment]
dunno what you did :-) but you might want to join some debug log.

**Comment by hoangtuit** [comment]
My stupid, It worked. Tks @lolorc

**Comment by h4nc** [comment]
worked great with http://www.webgraphviz.com.

Is there a way to visualize this directly in home assistant. Maybe someone here  already did this?

hassio; zigbee2mqtt addon

**Comment by Koenkk** [comment]
yes, see https://github.com/Koenkk/zigbee2mqtt/pull/732

**Comment by RaveGun** [comment]
Hi, I have ZigBee2Mqtt running as a docker container on a RPi that is running the latest DietPie.

If I request the raw map I get an answer with some devices. I do not know if it's correct as I am not aware what are all the devices I have anyway.

If I try the graphviz mode I am not getting any answer. The docker logs are also not showing any reaction to the published topic. After this point there is also no response to a raw request anymore. I must restart the docker container to get raw working again.

I did install graphviz with: sudo apt install graphviz but there is still no response.

Does the docker container has the rights to run the graphviz.

Shall I switch to a normal installation as right now the container doesn't start automatically after a reboot.

Thank you.

**Comment by RaveGun** [comment]
Nevermind, I was running the release branch, not the Dev flavour of the docker container. Now it's working and the custom ipanel component in HA too.

**Comment by epicurean70** [comment]
> Nevermind, I was running the release branch, not the Dev flavour of the docker container. Now it's working and the custom ipanel component in HA too.

HI,Did you also install graphviz as a docker? If so , can you explain how the setup it up to show the zigbee2mqtt network map?

**Comment by thomasvt1** [comment]
> > Nevermind, I was running the release branch, not the Dev flavour of the docker container. Now it's working and the custom ipanel component in HA too.
> 
> HI,Did you also install graphviz as a docker? If so , can you explain how the setup it up to show the zigbee2mqtt network map?

Try using [webgraphviz](http://www.webgraphviz.com/) then you don't have to install anything

**Comment by epicurean70** [comment]
> > > Nevermind, I was running the release branch, not the Dev flavour of the docker container. Now it's working and the custom ipanel component in HA too.
> > 
> > 
> > HI,Did you also install graphviz as a docker? If so , can you explain how the setup it up to show the zigbee2mqtt network map?
> 
> Try using [webgraphviz](http://www.webgraphviz.com/) then you don't have to install anything

ok. Then how do you see your own network? what data do you put in that box?

**Comment by thomasvt1** [comment]
> > > > Nevermind, I was running the release branch, not the Dev flavour of the docker container. Now it's working and the custom ipanel component in HA too.
> > > 
> > > 
> > > HI,Did you also install graphviz as a docker? If so , can you explain how the setup it up to show the zigbee2mqtt network map?
> > 
> > 
> > Try using [webgraphviz](http://www.webgraphviz.com/) then you don't have to install anything
> 
> ok. Then how do you see your own network? what data do you put in that box?

My suggestion is to read the documentation;
https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

**Comment by epicurean70** [comment]
Sorry, real newbie here. 
What exactly should I be looking for in that documentation? Are those mqtt messages for me to publish,, and view in mqtt fx?
