### ISSUE TITLE
Kwikset Smart Lock 914: state still working, but actions stop working

### ISSUE THREAD

**Issue by laurentbeaumer** [Koenkk/zigbee2mqtt#4175]
Hi, 

I have:

- Ubuntu 18.04 running on armhf (odroid xu4)
- ConBee 2
- Zigbee2MQTT (1.14.3)
- Mosquitto
- Home Assistant
- Kwikset Smart ZigBee Lock 914

My installation is one week old, so I believe I am running the latest both software and firmware.

The state is still updated in home assistant, however the actions (i.e. lock/unlock) suddenly stop working.

I have rebooted the three services. I have inspected the logs and couldn't see any message related to the action (i.e. locking or unlocking).

There is a similar thread saying, it could be an issue with the authorization token not being refreshed at expiry.

Thanks

**Comment by laurentbeaumer** [comment]
![ZigBee network](https://user-images.githubusercontent.com/22333939/91149510-7e1af900-e6fe-11ea-81fd-c72ac3a0f529.png)

**Comment by Koenkk** [comment]
- Did you ever use and disabled the report feature? https://www.zigbee2mqtt.io/information/report.html
- Can you try to configure the device via: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure ? Does it work again after this? (make sure to wakeup the device before doing otherwise configure might fail).

**Comment by laurentbeaumer** [comment]
Thanks, I'll check

**Comment by laurentbeaumer** [comment]
Not sure if it helps, I have in the log: 
"Zigbee2MQTT:error 2020-08-25 07:42:37: Failed to execute routing table for 'Kwikset Smart Lock 914'"

**Comment by laurentbeaumer** [comment]
Worth noting that I add the lock manually in the configuration.yaml, and I couldn't lock/unlock.

**Comment by laurentbeaumer** [comment]
I remove the battery from the lock, and put them back. The lock is normally responding (i.e. locking and unlocking). I'll wait 1 or 2 days to see it the issue reappears, if not, I'll close the issue.

**Comment by laurentbeaumer** [comment]
The issue happened again after restarting zigbee2mqtt.io, the above solution fixed (again) the issue.

As long as the service is not restarted, the lock works normally.
