### ISSUE TITLE
Samotech SM311 stopped reporting values

### ISSUE THREAD

**Issue by PedroLamas** [Koenkk/zigbee2mqtt#4179]
# Bug Report

I have 2 Samotech SM311 (generic of Sunricher ZG2835RAC) that stopped reporting values since I updated to the latest release.

These were working fine before but now something must have changed to cause this problem!

Looking at the description, this might be related to https://github.com/Koenkk/zigbee2mqtt/issues/4178

## Debug Info
Zigbee2MQTT version: 1.14.3
Adapter hardware: CC26X2R1
Adapter firmware version: 20200417

**Comment by PedroLamas** [comment]
@Koenkk could this issue somehow be related with this change? https://github.com/Koenkk/zigbee-herdsman-converters/commit/7bd1eb8882803a03ad227723a4c249e56908c751

**Comment by PedroLamas** [comment]
Here are the full logs: https://pastebin.com/7EZTkqcy

**Comment by Koenkk** [comment]
- Did you ever use and disabled the report feature? https://www.zigbee2mqtt.io/information/report.html
- Can you try to configure the device via: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure ? Does it work again after this?

**Comment by PedroLamas** [comment]
I've never knowingly enabled the reporting feature (never needed it before).

Already use the forced device config message, got a success message on the log but unfortunately that didn't fix the problem.

**Comment by PedroLamas** [comment]
I just restarted the 2 Samotech SM311 dimmers I have (by turning the Lights mains power off and on) and now they are back working fine, so I guess this is a problem with the device... closing this issue for now, I'll keep an eye if this happens again!
