### ISSUE TITLE
Livolo switch as light

### ISSUE THREAD

**Issue by MiguelAngelLV** [Koenkk/zigbee2mqtt#4193]
## The bug
The livolo switchs shows a switch, but, in the most of cases, it are used to turn on / off lights, so, we need create a light using switch plataform

## What did you expect to happen

The livolo switch could be a parameter to shows a light o switch, with switch as default for compatibility.

**Comment by xppx99** [comment]
Hello, this is quite similar with the Aqara D1 smart switch. I totally agree with the sugestion MiguelAlgelLV does.

**Comment by MiguelAngelLV** [comment]
Will this feature be implemented? Should I create new issue or this will be reponed?

**Comment by Koenkk** [comment]
You can try the opposite of https://www.zigbee2mqtt.io/integration/home_assistant.html#exposing-switch-as-a-light
