### ISSUE TITLE
Fix SNZB-02

### ISSUE THREAD

**Issue by akonstster** [Koenkk/zigbee2mqtt#4197]
# Bug Report
SONOFF Temperature and humidity sensor (SNZB-02) doesnt display any data  after pairing.
Im use mqtt discovery home assistant create entitys, but states **Unknown**.
 ![2020-08-28-084328_1600x900_scrot](https://user-images.githubusercontent.com/70063053/91525809-fce48180-e90a-11ea-8dd4-83b78ca6cce9.png)

logs:
https://hastebin.com/cuwihuzake.py

database.db:

{"id":2,"type":"EndDevice","ieeeAddr":"0x00124b001f84e0f5","nwkAddr":63164,"manufId":0,"manufName":"eWeLink","powerSource":"Battery","modelId":"TH01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,3,1026,1029,1],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{"modelId":"TH01","manufacturerName":"eWeLink","powerSource":3,"zclVersion":1,"appVersion":4,"hwVersion":1,"dateCode":"20200718"}}},"binds":[{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x0000000000000000","endpointID":1},{"cluster":1029,"type":"endpoint","deviceIeeeAddress":"0x0000000000000000","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x0000000000000000","endpointID":1}]}},"appVersion":4,"hwVersion":1,"dateCode":"20200718","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1598593360733}

devices.yaml

'0x00124b001f84e0f5':
  friendly_name: temp_hum_snzb02

## Debug Info
Zigbee2MQTT version:  1.14.3
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by nanobra1n** [comment]
Did you wait long enough? Mine reports only every hour especially if the ambient temperature is pretty stable.

**Comment by tomdudu38** [comment]
hi, ùy sensor snzb-04 do not work anymore seems to be since 1.14.2
my logs
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/372

**Comment by tomdudu38** [comment]
hello, mine report nothings.

**Comment by akonstster** [comment]
Wait 1 week, and nothing happens.

**Comment by nanobra1n** [comment]
How far away from the coordinator is your sensor? The CC2531's range isn't great especially through walls. If it isn't already, try placing it close to the coordinator. 

For what it's worth, I removed and repaired mine today and it reports at least every hour (1.14.3 with a CC1352P-2).

**Comment by tomdudu38** [comment]
hi,i did same,removed and repaired and it seems to work .
it saw an hour, or less.,( few minutes)ex today:
Zigbee2MQTT:info  2020-08-31 17:31:55: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23.07,"linkquality":92,"humidity":62,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:32:35: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23.07,"linkquality":92,"humidity":60.5,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:33:15: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23.07,"linkquality":94,"humidity":61.8,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:33:32: MQTT publish: topic 'zigbee2mqtt/0x00124b001b781d08', payload '{"temperature":23.91,"linkquality":52,"humidity":52.61,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:34:11: MQTT publish: topic 'zigbee2mqtt/0x00124b001b795657', payload '{"state":"OFF","linkquality":52}'
Zigbee2MQTT:info  2020-08-31 17:38:05: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23.07,"linkquality":94,"humidity":60.6,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:38:39: MQTT publish: topic 'zigbee2mqtt/0x00124b001b781d08', payload '{"temperature":23.91,"linkquality":52,"humidity":51.59,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:39:11: MQTT publish: topic 'zigbee2mqtt/0x00124b001b795657', payload '{"state":"OFF","linkquality":52}'
Zigbee2MQTT:info  2020-08-31 17:40:48: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23,"linkquality":92,"humidity":60.6,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:40:59: MQTT publish: topic 'zigbee2mqtt/0x00124b001b781d08', payload '{"temperature":23.91,"linkquality":52,"humidity":50.52,"battery":80,"voltage":2900}'
Zigbee2MQTT:info  2020-08-31 17:42:21: MQTT publish: topic 'zigbee2mqtt/0x00124b001b783bed', payload '{"temperature":23,"linkquality":94,"humidity":60.6,"battery":80,"voltage":2900}'
