### ISSUE TITLE
illuminance_lux now returns 1 for 0 reading

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#4211]
# Bug Report
## What happened
```{"illuminance":0,"illuminance_lux":1,"linkquality":63,"occupancy":false,"temperature":18.95,"update":{"progress":35.56,"remaining":682,"state":"updating"}}```

## What did you expect to happen
The minimal reading for illuminance_lux is now 1, i would expect this to be 0 for a 0 measurement value!

## How to reproduce it (minimal and precise)
This was introduce in a recent converter change that updated the way lux is calculated, I think the new calculation matches the spec, but 0 should probably still be treated at 0 as it is pitch dark in the room.

## Debug Info
```
[root@amethyst /opt/zigbee2mqtt]# mosquitto_sub -t zigbee2mqtt/bridge/info | jq .
{
  "commit": "6452500",
  "coordinator": {
    "meta": {
      "maintrel": 3,
      "majorrel": 2,
      "minorrel": 6,
      "product": 0,
      "revision": 20200728,
      "transportrev": 2
    },
    "type": "zStack12"
  },
  "log_level": "info",
  "network": {
    "channel": 11,
    "extended_pan_id": "0x31d4151f5fefd6c3",
    "pan_id": 6753
  },
  "permit_join": false,
  "version": "1.14.3-dev"
}
```

Hope this format is OK, It's easier to just grab the bridge/info output these days as it has the retain falg set too!

**Comment by Koenkk** [comment]
Indeed not expected behaviour, wondering if the calculation is correct. Let's continue in https://github.com/Koenkk/zigbee-herdsman-converters/issues/1506
