### ISSUE TITLE
MQTT lock state is not updating automatically

### ISSUE THREAD

**Issue by Rurouni** [Koenkk/zigbee2mqtt#4230]
Hi, 
I have Danalock V3 integrated into HA via MQTT discovery.
Everything works but the state update is not happening automatically, I have to manually publish empty payload to `zigbee2mqtt/<friendlyLockName>/get` and then it immediately updates in HA to correct state. 
I don't know what side is responsible for publishing update into `state_topic` is it zigbee2mqtt side or HA should poll... reading docs on "MQTT lock" in HA it feels like they just expect the message to be retained in state topic and updated on every change...

I've tried adding :
```
    retain: true
    retrieve_state: true
```
to device in configuration.yaml and also tried adding:
```
advanced:
  report: true
```
but neither had any effect and there no errors in logs and now I am stuck and need some pointers for where to start looking next

### Debug Info
Zigbee2Mqtt: 1.14.0
Adapter hardware: CC2531
Adapter firmware version: zStack12 (20190608)
Home Assistant 0.111.2
All running in docker

Thank you!

**Comment by Koenkk** [comment]
Can you try to reconfigure the device via https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure , while doing so look at the log if it went OK.

**Comment by Rurouni** [comment]
Yes, that did the trick, thank you!

**Comment by VincentSC** [comment]
This worked for me too. My guess is the that this was caused by the lock not being calibrated yet when I first connected. When I calibrated, I had to switch the rotation-direction for locking the door.

**Comment by Hooshee** [comment]
> 
> 
> Yes, that did the trick, thank you!

Coulc you please tell me what exactly you have done/post your relevant current devices topic content? I have the same issue, but as a relatively newby to the z2m, I'm a bit stuck... thank you :)

**Comment by Koenkk** [comment]
It's https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestdeviceconfigure now

**Comment by philibertc** [comment]
Hello @Koenkk,
Thank you for your support. It worked for an outlet with an integrated button on it that didn't report its status.
But for a tradfri light when I click on "Reconfigure" the lqi of the lamp doesn't change and nothing happens.

**Comment by frogale** [comment]
@Koenkk I have this problem wit non-reporting lock state very often (every 1-2 weeks). Every time I remove my Danalock and pair it again, it is ok for some time. But this reconfigure feature also works and it is much faster for me. Is it a problem with Z2M or Danalock itself? I have the latest firmware and the latest version of Z2M. Maybe I could perform preventive reconfigures every few hours or so, but that is not the solution.

**Comment by Koenkk** [comment]
@frogale it's a guess, but I think the problem is at the Danalock side, the device shouldn't lose it configuration.

**Comment by VincentSC** [comment]
Also think it's the Danalock, based on their bug discussions and my own experience. Their code seems to be a mess and not thought through. For instance battery levels are incorrect and their app has more spelling-errors than the website of AliExpress.

It's a shame, as I was doubting between Nuki and Danalock and Z2M's support was the reason I chose for the latter.

**Comment by arcanatigris** [comment]
It seems this occurs when the route changes, like through a repeater or the like.

**Comment by InToSSH** [comment]
> It seems this occurs when the route changes, like through a repeater or the like.

Yes, I had an IKEA repeater and when the lock switched to it, it stopped responding. But even after disconnecting the repeater and lock sitting idle for a while, it still lock/unlocks but doesn't report it's state.
