### ISSUE TITLE
adapter_concurrent: Not Working

### ISSUE THREAD

**Issue by cjsteward** [Koenkk/zigbee2mqtt#4250]
I receive the following error when trying to configure the "adapter_concurrent: 16" variable under "advanced" in the config

**Hardware**:
Hassio 0.114.4 Running on Ubuntu server 18.04 on Intel NUC.
Latest release of Zigbee2mqtt
CC1352P-2 Coordinator with latest firmware

**Error in Supervisor:**
WARNING (MainThread) [supervisor.addons.validate] Unknown options adapter_concurrent

**Zigbee2mqtt debug log:** **(Does not throw error here)**
debug 2020-09-02 23:40:32: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[26],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
info  2020-09-02 23:40:34: zigbee-herdsman started
info  2020-09-02 23:40:34: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200805,"transportrev":2},"type":"zStack3x0"}'
debug 2020-09-02 23:40:34: Zigbee network parameters: {"channel":26,"extendedPanID":"0xdddddddddddddddd","panID":6754}
info  2020-09-02 23:40:34: Currently 38 devices are joined:

**Config**
data_path: /share/zigbee2mqtt
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: SecretPassword123
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  channel: 26
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 15
  availability_blacklist: []
  last_seen: ISO_8601_local
  elapsed: true
  availability_timeout: 10
  report: true
  log_level: debug
  adapter_concurrent: 16
ban: []
whitelist: []
queue: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

**Comment by Koenkk** [comment]
This is an issue of the addon since Zigbee2MQTT accepts it just fine. Please open an issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
