### ISSUE TITLE
UnhandledPromiseRejectionWarning for MKS-CM-W5

### ISSUE THREAD

**Issue by HB9VCT** [Koenkk/zigbee2mqtt#4252]
## Bug Report
Issue with 2 gang switch identified as "1, 2, 3 or 4 gang switch (MKS-CM-W5)
by Norklmes".
Most probably misinterpreted device since the real manufacturer is not Norkmles.

## What happened
UnhandledPromiseRejectionWarning when sending the command to the device.
Nothing received from the device.

## What did you expect to happen
Ideally it should handle this device correctly. 

## How to reproduce it (minimal and precise)
Join the ZigBee switch and send On or Off command.

## Debug Info
Zigbee2MQTT version: 1.14.4
Adapter hardware: CC2531
Adapter firmware version: "maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2
Log:
Zigbee2MQTT:info  2020-09-03 10:07:09: MQTT publish: topic 'zigbee2mqtt/0xec1bbdfffe782154', payload  {"state_l1":"ON","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF"}'
(node:234) UnhandledPromiseRejectionWarning: Error: Command 0xec1bbdfffe782154/1 manuSpecificTuyaDimmer.setData({"status":0,"transid":84,"dp":257,"fn":0,"data":[1,1]}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no ack' (233))
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:311:27)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
(node:234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by HB9VCT** [comment]
This is what the device send when the button 1 is pressed and switch 1 is going to ON state:

Zigbee2MQTT:debug 2020-09-03 11:34:28: Received Zigbee message from '0xec1bbdfffe782154', type 'commandSetDataResponse', cluster 'manuSpecificTuyaDimmer', data '{"data":{"data":[1],"type":"Buffer"},"dp":257,"fn":0,"status":0,"transid":59}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-09-03 11:34:28: No converter available for 'MKS-CM-W5' with cluster 'manuSpecificTuyaDimmer' and type 'commandSetDataResponse' and data '{"data":{"data":[1],"type":"Buffer"},"dp":257,"fn":0,"status":0,"transid":59}'

**Comment by HB9VCT** [comment]
Here is the link to the seller:
https://www.aliexpress.com/item/4001133814342.html?spm=a2g0s.9042311.0.0.27424c4d3wZFuR

**Comment by Koenkk** [comment]
- Fixed `UnhandledPromiseRejectionWarning`
- Marked it as TuYa and added Somgoms as whitelabel
- Fixed ` No converter available for`
- `MAC no ack' (233))` might still appear, this means the device is not reachable from the coordinator. Make sure to connect the CC2531 through a USB extension cable to improve range.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by HB9VCT** [comment]
I can confirm that the updated version solved this issue. Thanks.
