### ISSUE TITLE
QBKG03LM temperature is not parsed correctly

### ISSUE THREAD

**Issue by MisterVSK** [Koenkk/zigbee2mqtt#4284]
Temperature data from QBKG03LM now uses generic_device_temperature converter, bit it is incompatible. Temperature comes in format similar to QBKG12LM where it is parsed in xiaomi_power_from_basic converter.
So I had to replace generic_device_temperature with xiaomi_power_from_basic in devices.js to get temperature work.

Zigbee2MQTT version: 1.14.4
Adapter hardware: CC2538
Adapter firmware version: zStack3

**Comment by Koenkk** [comment]
Please make a PR to fix this.
