### ISSUE TITLE
Ikea Fyrtur blinds battery state

### ISSUE THREAD

**Issue by amaia81** [Koenkk/zigbee2mqtt#4295]
Hi,

After updating via OTA my Fyrtur blind it doesnt report the battery state anymore. I tried to repair it and no luck so I removed it, restarted zigbee2mqtt and paired it again but the issue remained. Any suggestion?

Thanks!

**Comment by EfficientSetting** [comment]
I have the same issue, battery is always reported as 0

**Comment by ThomasSig** [comment]
I also have the same issue. Two identical devices, identical configuration and firmware (2.2.009). One with battery state and the other shows N/A. Any suggestions?

**Comment by EfficientSetting** [comment]
I needed to click "configure" on the Z2M interface for battery to be reported. Worked afterwards. 

I believe this has to do with the recent per device reporting that was implemented.

**Comment by ThomasSig** [comment]
> I needed to click "configure" on the Z2M interface for battery to be reported. Worked afterwards.
> 
> I believe this has to do with the recent per device reporting that was implemented.

This also fixed it for me. "Configure" and some patience :-)
Thanks,

**Comment by aiolive** [comment]
@ThomasSig: i have the same issue, but i can't find the "configure" setting on the Z2M interface.... can you help me plese :)

**Comment by filikun** [comment]
And where did you find that "configure" setting?

**Comment by ThomasSig** [comment]
> > @ThomasSig: i have the same issue, but i can't find the "configure" setting on the Z2M interface.... can you help me plese :)
> > edit: it's fixed after a long time :)
> 
> And where did you find that "configure" setting?

@filikun : Sorry, I moved to the integrated zigbee feature in Home Assistant, because off some issues that eat-up the batteries  in just 1-2 weeks. 
As I remember out from some screenshots... 
Go to "Device" view in the web interface and in the right side of the Ikea Fyrtur device, click on the yellow button to re-configure. Be patience because it will take some time to update...

**Comment by filikun** [comment]
> > And where did you find that "configure" setting?
> Go to "Device" view in the web interface and in the right side of the Ikea Fyrtur device, click on the yellow button to re-configure. Be patience because it will take some time to update...

Thanks m8, I did a reboot of Z2M and then re-configure. After some time it all worked again 👍

**Comment by mgrcic** [comment]
hello, 
I have the similar issue. I am integrating this device into the 3rd party hub and the battery measurement reports are always 0.
This is confirmed by the ZigBee sniffer logs.
The configure report command was successfully processed by the roller blind, but it always reports 0 for battery voltage and battery percentage remaining attributes.
The device firmware version is 1.99.34-2.2.009
Do you have any suggestions?
