### ISSUE TITLE
Ikea outlet E1603 letting current through when OFF

### ISSUE THREAD

**Issue by way2many** [Koenkk/zigbee2mqtt#4297]
Hi all,
Not really an issue with Z2M but this weekend I installed some 12V garden lights behind an Ikea outlet. Nothing fancy, some cheap LED with a 220V to 12V transformer. Every few seconds they flash, as if a condensator is discharging. This reminds me of the issues with a batch of Ikea GU10 which were also flashing (there are some discussion here about this).

Anybody experienced the same with an Ikea outlet? Should I be worried that it may be a faulty unit?

Thanks for help

**Comment by bartekluk** [comment]
It probably is, I had a similar problem with mine. Relay would switch the power was still goging through despite the status led chaning state. Never got to return it since it was in the middle of covid.

**Comment by way2many** [comment]
Ok great thanks. I will try to exchange it.
