### ISSUE TITLE
How to Sniff network on MacOS ?

### ISSUE THREAD

**Issue by dongvanthinh** [Koenkk/zigbee2mqtt#4304]
Hi Guys,

I want Sniff network on MacOS, please help me!

Thanks all!

**Comment by nurikk** [comment]
I'm using virtual machine(vmware fusion) to run Windows and inside run sniffer.

**Comment by sjorge** [comment]
I'm using a nRF52840 with their own sniffing firmware, works fine in native wireshark without issue.

Never got the ti based sticks to work though.

**Comment by Tobias007** [comment]
I recommend to use VirtualBox and install inside VBox Ubuntu Desktop .. then you can follow the sniffing instructions.
I had to install the VirtualBox Extension Pack to get USB3.0 with CC2531 running. USB1.0 didn't work for me...
