### ISSUE TITLE
Start using issue types in this Github project

### ISSUE THREAD

**Issue by VincentSC** [Koenkk/zigbee2mqtt#4306]
Request: use multiple issue types in this project. See https://github.blog/2018-05-02-issue-template-improvements/
- bug report
- feature request
- new hardware
- documentation request
- ...
- other

This way, it's also easier for me to see where I can help out. Now it's a bit too messy for me.

**Comment by Koenkk** [comment]
Added https://github.com/Koenkk/zigbee2mqtt/issues/new/choose, thanks!
