### ISSUE TITLE
New HUE Device supported LCT012

### ISSUE THREAD

**Issue by mfhotdog** [Koenkk/zigbee2mqtt#431]
Hello all, 

there are some new HUE RGB devices (E14) they are useable with zigbee2mqtt but they need to be added to the devices.js next to the other HUE RGB bulbs (LCT010, LCT015.....) 

Maybe this can be done with the next update. 

Thank you, greetings.

**Comment by Koenkk** [comment]
Could you make a PR here: https://github.com/koenkk/zigbee-shepherd-converters ?
