### ISSUE TITLE
info Migration from CC2531 to ConBee II

### ISSUE THREAD

**Issue by Maurotb** [Koenkk/zigbee2mqtt#4311]
Hi,
i have cc2531+antenna with zigbee2mqtt , but i have some problem for range and i can't add a extender.
If i replace my cc2531 with conbee ii , i need to repair all device or is transparent?
Thanks

**Comment by Koenkk** [comment]
Officially you should (https://www.zigbee2mqtt.io/information/FAQ.html#requires-repairing) but I've read stories where it worked without. So I would first try without, in case of any problem you can always repair.
