### ISSUE TITLE
Full support for Sinope TH1124ZB same as TH1123ZB

### ISSUE THREAD

**Issue by MRobi1** [Koenkk/zigbee2mqtt#4312]
I'd like to request full support for the Sinope TH1124ZB.
The device should be the same as the TH1123ZB except they support higher wattage outputs so it should support all the same options.

I'm trying to get current local temperature into home assistant and it is not auto discovered and doesn't come up with manual configuration either using:

  - platform: mqtt
    state_topic: "zigbee2mqtt/thermostat_bathroom"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.local_temperature }}"

**Comment by arnonel** [comment]
+1
