### ISSUE TITLE
Zigbee identifier collision / not existing

### ISSUE THREAD

**Issue by ditek** [Koenkk/zigbee2mqtt#4313]
This is somewhat a meta question about identifying devices and not concerning a specific case. It just occurred to me after adding support for one of my devices.

When we add support for new devices, we use the `ModelIdentifier` attribute from the Basic cluster to identify devices. However, this attribute is optional, so it's not unlikely that the manufacturer chooses not to provide it. For example, I have seen Cree lamps with empty `ModelIdentifier` attribute.

Also, as I understand, those identifiers don't need to be unique. For example, model identifiers for SmartThings devices include `water` and `motion`. It is easy to imagine that another manufacturer would pick those exact names for their devices causing a collision. How could support for such devices be added in that case?

**Comment by Koenkk** [comment]
The model identifier is the preferred way of identifying a device as it's very easy. For cases where device have a duplicate model identifier or don't have one at all the fingerprint mechanism can be used.

- Duplicate model example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/a2d3c9e1ffaa2a1a61a988f01e5e9c906e5d1572/devices.js#L5625 https://github.com/Koenkk/zigbee-herdsman-converters/blob/a2d3c9e1ffaa2a1a61a988f01e5e9c906e5d1572/devices.js#L5654
- ModelID undefined example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/a2d3c9e1ffaa2a1a61a988f01e5e9c906e5d1572/devices.js#L4617

Hope this helps!
