### ISSUE TITLE
Miele DGC 6805 XL

### ISSUE THREAD

**Issue by Pferdebockwurst** [Koenkk/zigbee2mqtt#4324]
## Information about the device + link
Miele DGC 6805 combined steamer and oven
https://www.miele.lu/de/c/combi-dampfgarer-1473.htm?mat=09505230&name=DGC_6805
https://www.miele.de/pmedia/ZGA/TX0021/9848220-000-01_09848220_001_0214.pdf
https://www.miele.de/pmedia/ZGA/TX2070/9895770-000-00_09895770_000.pdf

This is one of the earlier smart home capable devices from Miele. Later they switched to Wifi+Cloud, but this device (and several others) are using Zigbee. It is intended to be used with a gateway from Miele (XGW 3000) or Qivicon (Home Base).

The device was able to join my zigbee network:

`info  2020-09-09 20:20:42: Device '0x001d63fffe0206fc' joined
info  2020-09-09 20:20:42: Starting interview of '0x001d63fffe0206fc'
info  2020-09-09 20:20:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x001d63fffe0206fc"},"type":"device_connected"}'
info  2020-09-09 20:20:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x001d63fffe0206fc"},"type":"pairing"}'
info  2020-09-09 20:20:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001d63fffe0206fc"},"type":"device_announced"}'
info  2020-09-09 20:20:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001d63fffe0206fc"},"type":"device_announced"}'
info  2020-09-09 20:20:42: Successfully interviewed '0x001d63fffe0206fc', device has successfully been paired
warn  2020-09-09 20:20:42: Device '0x001d63fffe0206fc' with Zigbee model 'undefined' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
info  2020-09-09 20:20:42: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x001d63fffe0206fc","supported":false},"type":"pairing"}'
info  2020-09-09 20:34:25: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'`

This is what I have added to the devices.js afterwards:

`    {
        zigbeeModel: ['undefined'],
        model: 'DGC 6805',
        vendor: 'Miele',
        description: 'Combined Steamer and Oven',
        supports: 'unknown', // Actions this device supports (only used for documentation)
        fromZigbee: [], // We will add this later
        toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
        },
`

Unfortunately i wasn't able to get a report about unknown actions, even after triggering them by using the combi steamer. Maybe there is some special configuration needed, like the documentation suggests, but I don't know what and where to start. I'm really lost now, so please tell me how to go on. I could also buy the gateway, they only cost about 10 Euros, and try to sniff some traffic...

**Comment by Pferdebockwurst** [comment]
@Koenkk Sorry for the reminder - what do you think about this one?

**Comment by Koenkk** [comment]
@Pferdebockwurst sniffing the traffic with the original gateway should allow you to figure out what commands can be send (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by Pferdebockwurst** [comment]
OK, then I will buy the gateway and try to sniff the traffic. But I hope
you will help to analyze the traffic...?

----------
Von: Koen Kanters notifications@github.com
Datum: 13. September 2020 15:12:48
An: Koenkk/zigbee2mqtt zigbee2mqtt@noreply.github.com
CC: Pferdebockwurst enyce@gmx.de, Mention mention@noreply.github.com
Betreff: Re: [Koenkk/zigbee2mqtt] Miele DGC 6805 XL (#4324)

@Pferdebockwurst sniffing the traffic with the original gateway should
allow you to figure out what commands can be send
(https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by Koenkk** [comment]
I can only provide limited support

**Comment by Pferdebockwurst** [comment]
That should be enough. Thanks, that keeps me motivated.

----------
Von: Koen Kanters notifications@github.com
Datum: 13. September 2020 15:35:01
An: Koenkk/zigbee2mqtt zigbee2mqtt@noreply.github.com
CC: Pferdebockwurst enyce@gmx.de, Mention mention@noreply.github.com
Betreff: Re: [Koenkk/zigbee2mqtt] Miele DGC 6805 XL (#4324)

I can only provide limited support
