### ISSUE TITLE
Xiaomi MCCGQ01LM doesn't update HA frontend under binary_sensors platform.

### ISSUE THREAD

**Issue by HKC001** [Koenkk/zigbee2mqtt#433]
Using the Xiaomi MCCGQ01LM door sensor under the binary_sensors platform, state changes are updated in the zigbee2mqtt logs, but not in the front end.

Using the same sensors under the sensors platform, everything it works fine. 

```
- platform: mqtt
  name: "contact 1"
  state_topic: "zig/0x00158d00024e1a0a"
  availability_topic: "zig/bridge/state"
  payload_on: "false"
  payload_off: "true"
  value_template: "{{ value_json.contact }}"
  device_class: "door"
  qos: 0
  retain: true
  optimistic: false
```

**Comment by Koenkk** [comment]
Is this an homeassistant issue?

**Comment by HKC001** [comment]
I'm not sure. I switched to auto discovery and everything seems to work fine now. Closing issue, thanks!
