### ISSUE TITLE
HomeAssistant discovery and Xiaomi Aqara sensor causes entities with duplicate attributes

### ISSUE THREAD

**Issue by voltagex** [Koenkk/zigbee2mqtt#4333]
## What happened
I'm not sure if this is "as designed", but why do Z2M devices end up with duplicate attributes on every entity?

e.g. 

![image](https://user-images.githubusercontent.com/159567/92927855-9bcbba80-f481-11ea-8a63-ec7538ebfd8f.png)

![image](https://user-images.githubusercontent.com/159567/92927963-c9186880-f481-11ea-867c-c36f53580685.png)

The battery entity also has temperature data (the same happens for each of the entities that are automatically created)

This causes issues if you're automatically pushing data to Influx/Grafana and the like as you end up with multiple copies of the same data (e.g. 0xfff_battery.temperature, 0xfff_temperature.temperature)

## What did you expect to happen
Either one entity with all attributes, or each entity only having the attributes that are related to it (battery only has battery level, temperature only has degrees C)

## How to reproduce it (minimal and precise)
* Follow the bare-metal instructions, enable home assistant integration and pair a Xiaomi Aqara sensor
## Debug info
Zigbee2MQTT version: 1.14.4 (commit #8129093)

Adapter hardware: CC2531
Adapter firmware version: zStack12

**Comment by voltagex** [comment]
A quick fix for this is to remove https://github.com/Koenkk/zigbee2mqtt/blob/812909363b611b6eb5581f23dbae68e0cc5d8a3e/lib/extension/homeassistant.js#L2172 which makes the sensor in Home Assistant look like: 
![image](https://user-images.githubusercontent.com/159567/92931779-51e5d300-f487-11ea-982e-27880679e90d.png) - I think I'd rather put this behind a config setting with the default being the current behaviour.

**Comment by Koenkk** [comment]
You should be able to override this for all devices by setting the following in the Zigbee2mqtt `configuration.yaml`:

```yaml
device_options:
  homeassistant:
    json_attributes_topic: null
```

**Comment by voltagex** [comment]
Thanks @Koenkk.

This should solve the issue, @82amp
