### ISSUE TITLE
Migrating old database into new instance results in network issue

### ISSUE THREAD

**Issue by simonwood0609** [Koenkk/zigbee2mqtt#4352]
I was using the Home Assistant addon **zigbee2mqtt** running in a VM in **Proxmox**, with my **CC2531** ([flashed using these instructions](https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html)) plugged directly into that machine.

I need to offload **zigbee2mqtt** to a Raspberry pi so I can shift the VM to another PC in the garage while keeping the zigbee2mqtt controller inside the house.

I set up the Raspberry Pi following [these basic instructions](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html).

I then copied the following files out of the addon data directory into the Z2M data directory on the raspberry pi:
• configuration.yaml
• database.db
• devices.yaml
• groups.yaml
• state.json

When starting zigbee2mqtt, it connects to my broker successfully, and the entities in Home Assistant become available again - however none of them are functional.  It feels like they're not actually connected with the CC2531.

Here's an example of an error from the log file:
https://pastebin.com/Aggq4gLc

Any clues for a lost soul like me?

EDIT:  Even after moving the CC2531 back onto the host computer, the same problem exists.  This indicates that it isn't a configuration issue.

Could it potentially be because I started up the zigbee2mqtt service on the raspberry pi several times **before** copying the database.db file from the old instance?

How can I fix this without re-pairing everything :(

**Comment by TheStigh** [comment]
@simonwood0609 

Seems you missed the coordinator_backup.json
After done the copying of all files, re-flash the CC2351 and then reconnect it.
