### ISSUE TITLE
Zigbee2mqtt randomly closes

### ISSUE THREAD

**Issue by Dustinhoefer** [Koenkk/zigbee2mqtt#4369]
The zigbee2mqtt program randomly closes multiple times throughout the day.
Sometimes the stick got temporarily disconnected and zigbee2mqtt crashed

zigbee2mqtt should keep trying to find the stick and not crash completely

Start zigbee2mqtt with "npm start" in a windows cmd
Pull out the stick

**Comment by Koenkk** [comment]
Please provide the herdsman debug log of this issue.

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
