### ISSUE TITLE
Z2M crashes when it cannot save the state

### ISSUE THREAD

**Issue by syphernl** [Koenkk/zigbee2mqtt#4388]
## What happened
Because of the issues in #4307 I switched to the dev-branch. However, it crashes every 5 minutes. 
`supervise-daemon` restarts the process and 5 minutes later it happens again. 

The last line of each log was `Saving state to file /opt/zigbee2mqtt/data/state.json`. I looked in to this and found out that that file was not writable for the Z2M user.

## What did you expect to happen
An error to be shown that the state could not be saved and Z2M not to crash / exit because it cannot write to the state file.

## How to reproduce it (minimal and precise)
- Ensure the `data/state.json` is not writable for the Z2M user (in my case it was `root:root` with `0644` permissions while Z2M runs as `zigbee2mqtt` user)
- Start Z2M
- After 5 minutes Z2M will stop with exit code 1.

## Debug info
Zigbee2MQTT version: 1.14.4-dev (9c2fd10d8fa871b2f5ad046041681e990db38b47)
Adapter hardware: CC2531
Adapter firmware version: 20190619

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
