### ISSUE TITLE
Mix of picture between EcoDim Zigbee : 4 button wall switch AND 2 button wall switch

### ISSUE THREAD

**Issue by roumano** [Koenkk/zigbee2mqtt#4406]
On the https://www.zigbee2mqtt.io/information/supported_devices.html
the images of : 
* EcoDim Zigbee 4 button wall switch (action)
* EcoDim Zigbee 2 button wall switch (action)

Need to be swapped between them

**Comment by Koenkk** [comment]
Fixed, thanks!
