### ISSUE TITLE
Can't pair devices anymore

### ISSUE THREAD

**Issue by cor-vo** [Koenkk/zigbee2mqtt#4417]
# Bug Report
## What happened
Can't pair devices on new installation. (Home assistant) with an CC2531 on virtualbox

## What did you expect to happen
Devices can pair/connect like before.

## How to reproduce it (minimal and precise)
Always

## Debug Info
Zigbee2MQTT version: 1.14.4.1
Adapter hardware: CC2531
Adapter firmware version: ?

I just migrated my old, unsupported, installation to a new HassOS installation inside Virtualbox on a Mac Mini. After installation of the addons i started pairing all my Zigbee devices. Mostly IKEA Tradfri bulbs and Xiaomi Aqara sensors. At first i could pair 3 bulbs and a sensor without any issues but the 5th device wouldn't connect. I tried another bulb and another Aqara sensor but i couldn't pair a 5th device. Because i run out of options to removed the entire Virtualbox machine and started all over. But now i can't even pair a single device. I'm really out of options now, also because i don't see a single error message in the logs.

Anyone here wou could point me into a new direction to figure out what's wrong?

Thnx in advance!

**Comment by Koenkk** [comment]
Check: https://www.zigbee2mqtt.io/information/FAQ.html#no-logging-is-shown-at-all
