### ISSUE TITLE
LQI,FailedroutingTable

### ISSUE THREAD

**Issue by cndian** [Koenkk/zigbee2mqtt#4427]
Hello,

I have some problems with the mesh of my network.

I use 4 Gledopto WW spots (show as router in Zigbee2mqtt tab) and 3 Gledopto RGBW spots (also show as router), 2 Gledopto RGB/CCT bulbs and 4 end-devices from Aqara.

But when I open the Network map in Domoticz I see  some spots and end devices are connected directly to the coordinator the rest is not connected to anything. And by all the spots it says LQI,FailedroutingTable.

How does this come? And why everything connects to the coordinator when the bulbs and spots are routers? Everything does work.

Many thanks.

**Comment by Sandriekus** [comment]
@cndian 
i've had this exact same problem.
try to remove the power from the devices (complete, so disconnect from 220v or flip the switch in head fuse box)
after 1 minute restore the power. Turn on and off the lights a couple of times via Home Assistant and start the zigbee network discovery again.

this resolved the issue in my case
