### ISSUE TITLE
rename and rename_last does not clean up old availability topic

### ISSUE THREAD

**Issue by svh1985** [Koenkk/zigbee2mqtt#4432]
## Is your feature request related to a problem? Please describe
I think the rename and rename_last are not complete; I would expect z2m to clean up the retained messages for its previous name. 

Currently when use rename_last or rename `0x001788234200589e` to `Kitchen Lamp`, the old avalabiltity topic remains there (retained) with value `zigbee2mqtt/0x001788234200589e/availability` `online` 

After some testing, it also seems that the new device does not get the availability topic.

## Describe the solution you'd like
I would expect z2m to clean up the old topic or at least set the `availability` to `offline`

## Describe alternatives you've considered
Currently, we have to manually remove the retained messages with an MQTT client.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
