### ISSUE TITLE
Power attribute not showing anymore in different devices

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#4435]
## What happened
After some upgrade (I don't know which) power in Watts for two different devices with different brands don't appear anymore.
Devices are:
- Legrand Power socket with power consumption monitoring (067775)
- Ubisys Power switch S1 (S1)

None of them report the W anymore.

The rest of the attributes in those devices and every other devices are working fine.

Has any of the recent versions made any change with regard to Watts or power consumption? 

UPDATE: Xiaomi - Aqara wireless relay controller (LLKZMK11LM) works fine. But not the other two devices. Nothing (despite having debug active) in the log regarding W.
However, looking at the code, Xiaomi uses its own fromZigbee 'xiaomi_power_from_basic', that takes the information from an attribute. Whereas the other two use 'fz.metering_power'. I don't know if there is something related to that.

## What did you expect to happen
Report the power in Watts.

## How to reproduce it (minimal and precise)
Try to see the power in W.

## Debug info
Zigbee2MQTT version: 1.14.4.2
Adapter hardware: CC26X2R1
Adapter firmware version: CC26X2R1_20191106.zip 20191106 Z-Stack_3.x.0 firmware.

**Comment by Koenkk** [comment]
Try reconfiguring the device via https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure

**Comment by jd1900** [comment]
It did the trick. 

Thank you!
