### ISSUE TITLE
Sylvania Light Strip Won't Connect

### ISSUE THREAD

**Issue by Mallowpuffs** [Koenkk/zigbee2mqtt#4437]
## What happened

Whenever I try to connect my Sylvania 73773 strips to my Zigbee2MQTT(Home Assistant addon), it says "Received message from unsupported device with Zigbee model 'Flex RGBW Pro'". However, last week they worked(different HA install) and I checked and they're definitely on the supported device list.

## What did you expect to happen

I want them to connect to my Home Assistant! :)

## How to reproduce it (minimal and precise)

They just simply won't connect. I have tried uninstalling and reinstalling practically everything.

## Debug info
Zigbee2MQTT version: 1.14.4
Adapter hardware: CC2531
Adapter firmware version: Downloaded from here: https://www.zigbee2mqtt.io/getting_started/flashing_the_cc2531.html

Thanks!

**Comment by Koenkk** [comment]
Yours seems to be slightly different from the already supported one. Just added support for it.

Changes will be available in the latest dev branch tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
