### ISSUE TITLE
Error Starting ZigBee2MQTT

### ISSUE THREAD

**Issue by joemadd3n** [Koenkk/zigbee2mqtt#4441]
Error from Log:
https://pastebin.com/vsLwwqyA

Running on:
Ubuntu 20.04.1 LTS
Docker version 19.03.11

## Debug info
Zigbee2MQTT version: **1.14.4.2** 
Adapter hardware: **CC2531**
Adapter firmware version: **Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'**

**Comment by PedroLamas** [comment]
How did you set the MQTT server address in the configuration?

Please ensure you prefix the IP address with "mqtt://" as indicated in the configuration options here: https://www.zigbee2mqtt.io/information/configuration.html#configuration

**Comment by joemadd3n** [comment]
> How did you set the MQTT server address in the configuration?
> 
> Please ensure you prefix the IP address with "mqtt://" as indicated in the configuration options here: https://www.zigbee2mqtt.io/information/configuration.html#configuration

Yes! This worked, my fault entirely.
Thank you.
