### ISSUE TITLE
Lost entity sensor.0x00158d0002f8xxx_click after upgrade Zigbee2mqtt

### ISSUE THREAD

**Issue by xMariusz** [Koenkk/zigbee2mqtt#4442]
## What happened

After upgrade Zigbee2mqtt 1.14.4.1 I lost entity sensor.0x00158d0002f8xxx_click, however I see entity like sensor.0x.0x00158d0002f8xxx_battery and  sensor.0x.0x00158d0002f8xxx_linkquality. Automations stopped working

## What did you expect to happen
When I press button, automation should turn the light

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531

**Comment by OzGav** [comment]
Have you tried re-pairing the button?

**Comment by xMariusz** [comment]
Yes. Issue concerns Xiaomi Aqara products buttons/sensors

**Comment by OzGav** [comment]
Not sure. I have a number of these and they are working fine on 1.14.4.2 

I have seen in the past entities getting renamed. Have you had a good look to see if that has happened? Might be under the friendly name?

**Comment by Koenkk** [comment]
Can you share your `configuration.yaml`?

**Comment by xMariusz** [comment]
I solved my problem. My steps:

1. Remove zigbee device from HA (Configuration -> Devices)
![a](https://user-images.githubusercontent.com/21967796/94299997-abaaca80-ff68-11ea-9f3f-06c00a37b55e.png)
2. Unplug coordinator
3. Plug coordinator
4. Paring device
5. Solved
