### ISSUE TITLE
MOES HY369RT / TS0601 thermostat - temperature calibration not changing to negative values

### ISSUE THREAD

**Issue by Macieyo16** [Koenkk/zigbee2mqtt#4453]
Hi,

I am using radiator thermostat MOES HY369RT that are presented in Z2M assistant as TS0601. I want to use external temperature sensor to calibrate thermostat (using local_temperature_calibration value) when values on both sensors are not equal. 

When i send msg.payload with  value <0 (for example -5.0) to topic zigbee2mqtt/FRIENDLY_NAME/set/local_temperature_calibration

local_temperature_calibration is changing to value as sent but without minus (-) (for example 5.0)

I expect it to change to proper negative value. Radiator thermostat supports negative values what can be seen when changing it manualy with touch buttons.

## Debug info
Zigbee2MQTT version: dev branch
Adapter hardware: CC2531

**Comment by artkrz** [comment]
This was already mentioned and resolved in other issue. Please search before posting. I've posted working example here: https://github.com/Koenkk/zigbee2mqtt/issues/3821#issuecomment-699493188
