### ISSUE TITLE
Cant add LED1537R6/LED1739R5

### ISSUE THREAD

**Issue by peterselieman** [Koenkk/zigbee2mqtt#4454]
## What happened
I Bought a 3pack of LED1537R6/LED1739R5 GU10 spots.
I paired them to the bridge, and it shows up in the Zigbee2Mqtt plugin page.
but i cant add them to domotics. it wont show up on the devices list

## What did you expect to happen

pair and add the bulb

## How to reproduce it (minimal and precise)
pair it with domoticz

## Debug info
Zigbee2MQTT version: v.1.14.3
Adapter hardware: Conbee II
Adapter firmware version: latest firmware

**Comment by Koenkk** [comment]
Probably device is missing from https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin, create an issue here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
