### ISSUE TITLE
Can't pair any additional device

### ISSUE THREAD

**Issue by pepp86** [Koenkk/zigbee2mqtt#446]
Hi Team,

I am running the latest zigbee2mqtt release and the latest dev branch. I've got some Osram+ Plugs working fine, but not able to connect new Plugs or light bulbs.

Pairing seems to be fine, but the server is not sending anything to mqtt about the new devices. Any Ideas?

Log: https://pastebin.com/mW1M06h5

**Comment by ben423423n32j14e** [comment]
Did you read the wiki?

https://github.com/Koenkk/zigbee2mqtt/wiki/ZigBee-network

**Comment by pepp86** [comment]
Yes of course. 

Actually my network consists of 5 Osram plugs which are routers and one Philips hue motion sensor. 

Far away from the Zigbee network limit.

**Comment by pepp86** [comment]
Ok. Found a solution. zigbee2mqtt is not creating the inital topic on the mqtt server.
After creating the topic with a mqtt client, there is date in it.

Any idea how to solve it? Any input required?

**Comment by lolorc** [comment]
this initial topic issue sounds weird to me.
But I have had issues pairing devices surrounded by my osram plugs acting as router. Had to pair very close to the coordinator or shut the routers down.
