### ISSUE TITLE
Xiaomi Flood Sensor False Positives

### ISSUE THREAD

**Issue by ben423423n32j14e** [Koenkk/zigbee2mqtt#448]
A week ago I installed four Xiaomi Flood Sensors in my apartment connected to Zigbee2MQTT. So far two of the sensors have had “false positive” events in which all of a sudden without any obvious reason the sensor reports a flood and gets stuck on until I put it in a small amount of a water and remove it.

Each hour or so the sensor checks in to say there is still a flood until fixed as per above. Could be a Zigbee2MQTT issue although I am not sure.

Anyone else seeing problems with these sensors?

**Comment by oischinger** [comment]
I have exactly the same problem. One sensor actually was wet but it never changed back to dry.
The other one has always been dry and suddenly changed to wet. It's in that state since about 20 hours or so.

First i thought the dry state was somehow lost on the network or similar. 
Is there a way ot trigger an update from the sensor by sending an mqtt message?

**Comment by ben423423n32j14e** [comment]
There goes a third sensor, been going off for about 5 hours now.

I think the issue has to be with the Zigbee2MQTT implementation, surely I can't have 3 out of 4 sensors with actual false positives?

**Comment by tb-killa** [comment]
This could be a bug in combination with ``ssIasZone`` because for the ``SJCGQ11LM_water_leak`` we use the ``statusChange`` event to get our return.

 Does someone of you guys in use of another ``ssIasZone`` devices ?
Please search in ``database.db`` for `´ssIasZone`` and provide content via pastebin or another service.

**Comment by ben423423n32j14e** [comment]
Yep, I'm using the lumi.sensor_smoke

`{"id":14,"type":"EndDevice","ieeeAddr":"0x00158d000153b9ff","nwkAddr":58222,"manufId":4151,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sensor_smoke","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,12,18,1280],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genPowerCfg":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genAnalogInput":{"dir":{"value":1},"attrs":{}},"genMultistateInput":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"ssIasZone":{"dir":{"value":1},"attrs":{}}}}},"_id":"RcEAAeTieFp2OX5q"}`

**Comment by tb-killa** [comment]
Okay that shouldnt be the problem ... will do some more investigation.
I´m actually working on global ``ssIasZone`` implementation.

**Comment by JLeandroFreitas** [comment]
I have the same problem. Please let me know when here is a solution.

**Comment by tb-killa** [comment]
@Koenkk @kirovilya does somebody of you could help ?

**Comment by Koenkk** [comment]
I have this sensor, going to connect it to my network and wait until it reports a false positive.

**Comment by ben423423n32j14e** [comment]
@Koenkk, you should see a false positive within a few days. 2 out of my 4 sensors are currently in false positive state.

**Comment by tb-killa** [comment]
Does this reported false positive with the original gateway ?

**Comment by Koenkk** [comment]
I have it running for a week now and no report, could you provide the message all messages of this sensor (`grep`)

**Comment by oischinger** [comment]
@Koenkk : I've reset all my sensors and now I'm waiting for another false positive. Is log_level: info enough?

**Comment by ben423423n32j14e** [comment]
Two out of my four sensors are currently in false positive state, unfortunately my logging is as good as fried due to Zigbee2MQTT console logging everytime I request devices via mqtt for zigbee2mqtt admin console (node-red), I really wish that wasn't logged in console.

`
"0x00158d0002704b87": {
        "water_leak": false,
        "linkquality": 36,
        "battery": "100.00",
        "voltage": 3035
    },
    "0x00158d00017200f2": {
        "pressure": 995.58,
        "linkquality": 76,
        "battery": "42.00",
        "voltage": 2985,
        "temperature": 18.21,
        "humidity": 54.12
    },
    "0x00158d0002705396": {
        "water_leak": false,
        "linkquality": 23,
        "battery": "99.00",
        "voltage": 3015
    },
    "0x00158d0002704b82": {
        "water_leak": true,
        "linkquality": 31,
        "battery": "99.00",
        "voltage": 3005
    },
    "0x00158d00013f79d1": {
        "battery": "99.00",
        "voltage": 3015,
        "linkquality": 52,
        "occupancy": false
    },
    "0x00158d000153b9ff": {
        "battery": "100.00",
        "voltage": 3055,
        "linkquality": 89
    },
    "0x00158d0002704b5c": {
        "water_leak": true,
        "linkquality": 47,
        "battery": "99.00",
        "voltage": 3025
`

**Comment by Koenkk** [comment]
I see, but I need your debug logging to check which message is triggering it.

**Comment by Koenkk** [comment]
@ben423423n32j14e can you check if this has been fixed in the dev branch?

**Comment by oischinger** [comment]
I did not experience the issue anymore since I upgraded to the dev branch. Seems fixed!
Thanks alot for your help!

**Comment by Koenkk** [comment]
Great!
