### ISSUE TITLE
SAMOTECH SM309 no States in iobroker 

### ISSUE THREAD

**Issue by chrineuh** [Koenkk/zigbee2mqtt#4498]
Hello I have an Propem by adding the SAMOTECH SM309
I can pair it but i have no stats in the iobroker Objekts tap.

I can t contoll in in iobroker 

![grafik](https://user-images.githubusercontent.com/60777681/94623067-ae345980-02b3-11eb-88fa-518919168ef7.png)

![grafik](https://user-images.githubusercontent.com/60777681/94623091-b7bdc180-02b3-11eb-9e72-2f2341ed59ce.png)

**Comment by Koenkk** [comment]
Please create an issue here: https://github.com/ioBroker/ioBroker.zigbee/issues
