### ISSUE TITLE
add new device Osvalla

### ISSUE THREAD

**Issue by purche42** [Koenkk/zigbee2mqtt#4507]
Hi 

I have added new IKEA Tradfri device Osvalla to my config.
Anything works fine with my device and I want to contribute to your great project.

Not sure how I put the changes to a markdown file so I kindly ask if you can point me to the guide how I create the markdown file out of my short device.js addition.

{
        zigbeeModel: ['TRADFRI Light Engine'],
        model: 'T2011',
        description: 'Osvalla panel round',
        vendor: 'IKEA',
        ota: ota.tradfri,
        extend: generic.light_onoff_brightness_colortemp,
    },

The Addition of  150x150 image to the  Git Clone was the easy part ;)

![osvalla](https://user-images.githubusercontent.com/67458050/94715082-4af70580-034d-11eb-9b14-bb572a39f7d2.jpg)

Peter

**Comment by Koenkk** [comment]
Added, will be supported in tomorrows Zigbee2MQTT release.
