### ISSUE TITLE
Request to add Danfoss icon floor heating system

### ISSUE THREAD

**Issue by mihail4anov** [Koenkk/zigbee2mqtt#4518]
I would like to ask to add the **Danfoss icon floor heating system** to **Z2M** please.
I am not a programmer, and I cant do it myself.

## Information about the device + link
[Link to the device](https://icon.danfoss.com/)
This is the link to [API](https://drive.google.com/file/d/1n5MqOSaBiPYZAXqRsyglrGSwGzOSjZUA/view?usp=sharing) which I received from Danfoss.

**Comment by haukurk** [comment]
+1
