### ISSUE TITLE
Innr FL 120 C does not report LQI

### ISSUE THREAD

**Issue by wzbfyb** [Koenkk/zigbee2mqtt#4528]
## What happened
My two Innr FL 120 C lightstrips do not report LQI, and on one of them I see strange "set" commands in MQTT:

zigbee2mqtt/Kinderzimmer Kasten/set
{"battery":11,"linkquality":37,"update":{"state":"idle"},"update_available":false}

zigbee2mqtt/Kinderzimmer Kasten
{"brightness":254,"color":{"x":0.351580493324198,"y":0.356691135100592},"color_temp":209,"state":"ON"}

## What did you expect to happen
link quality to be present on 
zigbee2mqtt/Kinderzimmer Kasten
and not seeing set commands with LQI and battery

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: Conbee II
Adapter firmware version: zigbee2mqtt/Kinderzimmer Kasten

**Comment by Koenkk** [comment]
This is expected behaviour, see https://github.com/Koenkk/zigbee2mqtt/issues/3353#issuecomment-613252332
