### ISSUE TITLE
How to reset Philips Hue without a Dimmer Switch?

### ISSUE THREAD

**Issue by orientalsniper** [Koenkk/zigbee2mqtt#454]
I have it paired with the Philips Bridge, but I don't want to spend more money to buy the Dimmer Switch.

**Comment by WinSCaP** [comment]
Well, in that case I have bad news for you, there is no real other solution. My advise would be to invest in a dimmerswitch because it's really handy with other ZigBee lights as well.

**Comment by orientalsniper** [comment]
Just found this: http://thingsthataresmart.wiki/index.php?title=How_to_Reset_Philips_Hue_Bulbs

And it worked! But my zigbee2mqtt docker container is still not pairing the bulb, I'm going to have to open a new thread.

**Comment by exetico** [comment]
@orientalsniper It's working here too, but i can't get it to connect with zigbee2mqtt. How did you manage to fix that part?

**Comment by frankiej911** [comment]
I've also issues with the Philips Bulbs. No remote control, so i've tried it with the API debugging tool. Bulb is blinking 3 times and ending at full brightness. Turn off and on the bulb and it was not found by the Zigbee2mqtt and it's still posible to control the bulb with the Hue. Another touchlink true command was also working, same thing happened... But undiscoverable en still paired with the Hue.

**Comment by exetico** [comment]
@frankiej911 - Same issue here. I've also tried to take the power in the middle of the blinks on different times, but it doesn't help.

My four spots is LTW013 according to Hue Essentials.

Do you really ting that we need to pick up a Philips Hue Switch to reset the buld? :-) Let me know if you make any progress!

**Comment by orientalsniper** [comment]
It worked, but what I did was to eliminate the bulbs in the Hue App and zigbee2mqtt automatically pair with the bulbs, had to remove some bulbs multiple times.

**Comment by orientalsniper** [comment]
> 
> 
> @orientalsniper It's working here too, but i can't get it to connect with zigbee2mqtt. How did you manage to fix that part? (My bulbs is model 9290012576 - i can't find them on the list)

If device is unsupported you have to manually add it to a file (forgot name) in the wiki.

**Comment by orientalsniper** [comment]
Yeah, it was a combination of using the Philips API and removing the bulbs in the Hue app in my phone.

**Comment by ygreq** [comment]
I have the same problem. I don't have a Hue Hub. I managed to reset it once and paired it with ZHA. Now I switched to Z2M and try to reset once more, but to no avail. 

Any suggestions on how to reset it with the on and off combination? Do you know how many times and how fast?
Thank you!

**Comment by exetico** [comment]
Use touchlink? :-) 
https://www.zigbee2mqtt.io/information/touchlink.html
