### ISSUE TITLE
IKEA TRADFRI wireless dimmer (ICTC-G-1) - link quality

### ISSUE THREAD

**Issue by MiloshCZ** [Koenkk/zigbee2mqtt#457]
Hi,
i have found, that "IKEA TRADFRI wireless dimmer" doesnt send link quality.

there is link quality in debug visible
`cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 8, srcaddr: 33153, srcendpoint: 1, dstendpoint: 1, wasbroadcast: 0, linkquality: 68, securityuse: 0, timestamp: 6181132, transseqnumber: 0, len: 3, data: <Buffer 11 41 07> } +5ms`

but not in MQTT output:
`zigbee2mqtt:info 2018-10-8 16:31:32 MQTT publish, topic: 'zigbee2mqtt/0x000b57fffe29ee14', payload: '{"brightness":1,"device":{"ieeeAddr":"0x000b57fffe29ee14","friendlyName":"0x000b57fffe29ee14","type":"EndDevice","nwkAddr":33153,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI wireless dimmer","status":"offline"}}'`

**Comment by h4nc** [comment]
It looks like it only reports brightness in the mqtt output.

Would be nice to see the battery state also.
