### ISSUE TITLE
Heiman SMOK_WD_V10 

### ISSUE THREAD

**Issue by BillX86** [Koenkk/zigbee2mqtt#458]
Hi! 

i tried to add support for the "Heiman SMOK_WD_V10". 
I am aware of this topic: https://github.com/Koenkk/zigbee2mqtt/issues/384

I have tried the "usual way" and also tried the way described in the topic above but i still had no luck .... 

In the database is still: " "ssIasZone":{"dir":{"value":1},"attrs":{"zoneState":0,"zoneType":40,"zoneStatus":32,"iasCieAddr":"0x0000000000000000","zoneId":0,"numZoneSensitivityLevelsSupported":2,"currentZoneSensitivityLevel":0}}"

If i check the debug output it says frist ... 

  zigbee-shepherd-converters:devices Configured '(cb) => device.foundation('ssIasZone', 'write', [ writeRecArgs_ssIasZone ], { direction: 0}, cb)' with result 'OK' +0ms
.....
 zigbee-shepherd-converters:devices Configured '(cb) => device.functional('ssIasZone', 'enrollRsp', [ enrollRspArgs_ssIasZone ], cb)' with result 'OK' +3s

and later on:

  zigbee-shepherd-converters:devices Configured '(cb) => device.report('ssIasZone', 'zoneStatus', 0, 30, null, cb)' with result 'unreportableAttribute' +8s
  zigbee2mqtt:error 2018-10-8 17:04:46 Failed to configure 0x005043c9a3363e6a 0x005043c9a3363e6a

Any idea?

**Comment by JLFN** [comment]
Check out https://github.com/Koenkk/zigbee2mqtt/issues/279
