### ISSUE TITLE
Moes HY369RT (AKA TuYa TS0601) Battery Status Unavailable In Home Assistant

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee2mqtt#4582]
## What happened
Added the Moes HY369RT (AKA TuYa TS0601) in Zigbee2MQTT and can see that status of the battery in the new beta frontend.

## What did you expect to happen
Battery status reported in HomeAssistant - it is shown as unavailable (battery with exclamation mark)

## How to reproduce it (minimal and precise)
Add Moes HY369RT (AKA TuYa TS0601) to Zigbee2MQTT and enable MQTT integration with auto device generation in HomeAssistant.

## Debug info
Zigbee2MQTT version: 1.15 beta
Adapter hardware: CC26X2R1

**Comment by drdownload** [comment]
Same for 1.14 and CC2531

**Comment by mcsshs** [comment]
I have the same problem
Z2M 1.15.0 and CC2531

**Comment by danieledwardgeorgehitchcock** [comment]
Just to add, it appears that Zigbee2MQTT only detects these devices as being powered by batteries (no battery discharge status is collected) - Looking at a sniff of one of these devices on a TuYa network, it would appear that the status is reported so, Zigbee2MQTT just doesn't seem to be converting these values.

I can provide sniff logs if required..

**Comment by ARNik** [comment]
The same issue with zigbee2mqtt and CC2538 coordinator.

**Comment by Blueforcer** [comment]
Same with conbee II

**Comment by groenmarsmannetje** [comment]
It does report the battery_low status but not the %. I can see that now flashing on and off when the motor is busy adjusting the valve.

**Comment by Kalypox** [comment]
Same with PiZiGate

**Comment by markheloking** [comment]
> The same issue with zigbee2mqtt and CC2538 coordinator.

Same here also with zigbee2mqtt and CC2538 coordinator.
