### ISSUE TITLE
Aqara curtain(blinds) motor (ZNCLDJ11LM) Xiaomi does not publish its state after receiving the STOP command...

### ISSUE THREAD

**Issue by Trigger001** [Koenkk/zigbee2mqtt#4585]
### What happened

Aqara curtain(blinds) motor (ZNCLDJ11LM) Xiaomi does not publish its state after receiving the STOP command..
I made an automation in Node Red with a curtain and a switch. I wanted to make automation like in mihome one button open-stop-close

### How to reproduce it (minimal and precise)

Add Aqara curtain(blinds) motor (ZNCLDJ11LM) Xiaom to Zigbee2MQTT and enable MQTT integration with auto device generation in HomeAssistant. Then send a stop command to the curtains and watch the log

### Debug info
![Inked2020-10-07_10-21-08_LI](https://user-images.githubusercontent.com/60311952/95377825-c1ff4180-08eb-11eb-8d5f-3eaa49c4d2b5.jpg)

Zigbee2mqtt Current version: 1.15.0
Adapter hardware: CC2538

**Comment by Koenkk** [comment]
Fixed. Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Trigger001** [comment]
Super!!! Coffee from me :-))
