### ISSUE TITLE
Add bindings table in web-interface/frontend

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#4589]
## Is your feature request related to a problem? Please describe
If there are conflicting bindings one has to click through devices to find leftover bindings.

## Describe the solution you'd like
A table listing all bindings with a delete check-box per binding.

## Describe alternatives you've considered
Clicking through all devices to find mis-configured bindings.

**Comment by Koenkk** [comment]
Please create issues related to the frontend here: https://github.com/nurikk/z2m-frontend/issues
