### ISSUE TITLE
Repeat configuration attempt (bindings, groups, etc.) when device is online

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#4591]
## Is your feature request related to a problem? Please describe
A lot of battery powered Zigbee sensors are hard to trigger (e.g. battery powered motion detectors which do not react for 3 minutes after first activity). Because of that device configuration attempts often fail.

## Describe the solution you'd like
If a configuration attempt fails repeat the configuration of a device when it comes online.

## Describe alternatives you've considered
Jumping and waving in front of a motion detector with no success.

**Comment by Koenkk** [comment]
This has also been requested before, let's reopen the original request: https://github.com/Koenkk/zigbee-herdsman/issues/104
