### ISSUE TITLE
Can't unblock a device anywhere if I accidentally blocked it

### ISSUE THREAD

**Issue by richardtrinks** [Koenkk/zigbee2mqtt#4599]
Have two devices that I see in the RAW data that they are blocked, but cannot unblock them anywhere via the interface. At least I can't find it.

**Comment by danieledwardgeorgehitchcock** [comment]
You will need to edit the configuration.yaml - you will find the blocked devices in there

**Comment by richardtrinks** [comment]
Checked everything in the file and all included files. But unfortunately cannot find anything about the affected devices. Any suggestions?

**Comment by richardtrinks** [comment]
Yes I found it, there is a configuration.yaml file in Home Assistant, but in the folder share/zigbee2mqtt there is still a configuration.yaml file. Thank you for thinking along and coming up with the solution.

**Comment by richardtrinks** [comment]
Yes I found it, there is a configuration.yaml file in Home Assistant, but in the folder share/zigbee2mqtt there is still a configuration.yaml file. Thank you for thinking along and coming up with the solution.
