### ISSUE TITLE
Moes BHT-002 precision

### ISSUE THREAD

**Issue by vladtsit** [Koenkk/zigbee2mqtt#4610]
Hi! Is it possible to increase precision of current and set temperature to 1/10 degrees?

**Comment by insipiens** [comment]
I did check this when creating the code.

Unfortunately the Moes device and App both use integer values for communicating set temperature . Even though on the device you can manually change it by 0.5 degree.

**Comment by vladtsit** [comment]
Thanks for your efforts! I used to control temperature with better precision.
