### ISSUE TITLE
Neo NAS-AB02B0 Alarm

### ISSUE THREAD

**Issue by arduino43** [Koenkk/zigbee2mqtt#4612]
Did you read the FAQ?
Yes

Zigbee2MQTT fails to start?
No

Having issues when using a CC2531?
No

Unsupported device?
No

Device does not pair or interview fails?
No

Bug report?

1.) Setting humidity_max sets the value for humidity_min as the values are reversed.
2.) Not sure if this is an issue or just the functionality, but communications have a delay of 3-5 seconds.

## What happened
humidity_max sets the value for humidity_min

## What did you expect to happen
humidity_max sets the value for humidity_max
humidity_min sets the value for humidity_min

## How to reproduce it (minimal and precise)
zigbee2mqtt/0x842e14fffedb834d/set {"humidity_min":10}
zigbee2mqtt/0x842e14fffedb834d/set {"humidity_max":5}

zigbee2mqtt/0x842e14fffedb834d {"alarm":false,"device":{"applicationVersion":73,"dateCode":"20180727","friendlyName":"0x842e14fffedb84d8","hardwareVersion":1,"ieeeAddr":"0x842e14fffedb84d8","manufacturerID":0,"manufacturerName":"_TYST11_d0yu2xgi","model":"NAS-AB02B0","networkAddress":6152,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"humidity":45,"humidity_alarm":true,**"humidity_max":10**,**"humidity_min":5**,"linkquality":93,"melody":5,"temperature":"17.8","temperature_alarm":true,"temperature_max":100,"temperature_min":0,"volume":"low"}

## Debug info
Zigbee2MQTT version:
CC26X2R1 / v 1.15.0
Adapter firmware version:
3

**Comment by Koenkk** [comment]
@kirovilya do you know about this?

**Comment by kirovilya** [comment]
check on the weekend

**Comment by kirovilya** [comment]
yes. it is a bug :)
621 - humidity_min
622 - humidity_max
