### ISSUE TITLE
After renaming a device it starts to report as undefined. 

### ISSUE THREAD

**Issue by danielo515** [Koenkk/zigbee2mqtt#4626]
## What happened
After renaming certain devices they stopped working. 
They are all aqara devices. I renamed them using hassio integration. After renaming if I check the logs I can see errors about undefined devices popping everytime I activate one of the renamed devices. 
Xiaomi button and a ikea bulb renames without problem, but the rest of aqara devices suffer from this problem. 

## What did you expect to happen
To rename them and still work

## Debug info
Will post later this info 
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by Haxiboy** [comment]
I was looking for the opposite a few days ago. Renaming the device changes the name of the entities (this is my expected behavior). There should be a dialog like in home assistant renaming system if we want to rename the entities too.

**Comment by danielo515** [comment]
> Renaming the device changes the name of the entities
Isn't that exactly what is expected? For some sensors it works (home assistant recognizes the new name) but for some others it just doesn't work because the explained behavior

**Comment by Koenkk** [comment]
The new api allows to specify wether to also update Home Assistant entity IDs, see https://github.com/Koenkk/zigbee2mqtt.io/blob/new_api/docs/information/mqtt_topics_and_message_structure.md#device `zigbee2mqtt/bridge/request/device/rename` , to enable the new api see https://github.com/Koenkk/zigbee2mqtt/issues/3281

**Comment by danielo515** [comment]
Thanks @Koenkk, for now I repaired the decides and they picked the new name (in hassio they also have the new name, but they use the Mac as id). I'll check the new api if I get a chance
