### ISSUE TITLE
Ikea e1743 don’t show payload on or off

### ISSUE THREAD

**Issue by dustardly** [Koenkk/zigbee2mqtt#4635]
USB CC2531
Ikea tradfri 1743
After paired , pairing the ikea switch ok, but after complete pairing  don’t show anythings in action, don’t show payload on or off or brightness up or down

Tested on rpi 3+ and on rpi4 4gb
Last version ha 0.116.2

## Debug info
Zigbee2MQTT version:1.15.0
Adapter cc2531
Adapter firmware version: 20190410

**Comment by dustardly** [comment]
Only xiaomi button give payload hold release while tradfri payload is empty

https://hastebin.com/yutewajage.rust

**Comment by Koenkk** [comment]
- Try updating to the latest firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default
- If that doesn't help try to force configure device via https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure make sure to wakeup the device right before doing so (by clicking a button on it) and check the logs if executed successfully.

**Comment by dustardly** [comment]
after upgrade firmware on cc2531 all working again! Thanks!

**Comment by neerdoc** [comment]
Mine works too now. I think I accidentally had an IKEA lamp too close to the switch while pairing (I was pairing lots of stuff one after the other). It all worked out once I removed the battery from the switch -> re-paired the lamp -> moved the lamp to another room -> chose "Forget device" for the switch -> rebooted Raspberry Pi -> put the battery back in the switch -> factory reset the switch (4 clicks within 5 seconds) -> re-paired the switch.
