### ISSUE TITLE
Add JSON key for color temperature in Kelvin unit

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#4639]
## Is your feature request related to a problem? Please describe
The color temperature has to be entered in 'Mirek' unit. Average Joes see 'Kelvin' unit on the bulb package an have no idea what 'Mirek' unit is.

## Describe the solution you'd like
I suggest a JSON key `{ "color": { "kelvin": <value> } }` to set the color temperature in Kelvin unit.

## Describe alternatives you've considered
Pointing average joes to the Zigbee2MQTT documentation and let them convert Mirek to Kelvin just causes confusion.

**Comment by Aragur** [comment]
Is it possible to reopen this issue?  
I'm using NodeRED with the Google Assistant, the color temperature is only returned in Kelvin.  
Or is there a formula I can use, to calculate Mirek to Kelvin?
