### ISSUE TITLE
zigbee_publish_error after restart of Raspberry PI

### ISSUE THREAD

**Issue by Pigotka** [Koenkk/zigbee2mqtt#4654]
## What happened
I have my CC2531 stick connected to Raspberry PI. Sometimes when RPI restarts (power outage etc.) it does not resume correctly. Immediately after Zigbee2MQTT start log starts filling with this errors:
`error 2020-10-13 10:40:06: Publish 'set' 'state' to 'PowerPlugWatterPump' failed: 'Error: Command 0x680ae2fffe6fc40b/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (SRSP - AF - dataRequest after 6000ms)'
`
Best solution I found for this issue is to replug the USB stick. 
No devices are working.
I have 20+ devices but mainly routers.

## What did you expect to happen
To start correctly after reboot.

## How to reproduce it (minimal and precise)
Turn off/on power adapter for RPI.

## Debug info
Zigbee2MQTT version: 1.14.3
Adapter hardware: CC2531
Adapter firmware version: 2.6

**Comment by Koenkk** [comment]
Looks that your stick crashed, if it doesn't work after a restart reflash it. Also make sure to upgrade to Zigbee2MQTT 1.15.0, it contains some stability fixes for CC2531.

**Comment by Pigotka** [comment]
> Looks that your stick crashed, if it doesn't work after a restart reflash it. Also make sure to upgrade to Zigbee2MQTT 1.15.0, it contains some stability fixes for CC2531.

I check my FW and I'm running 20190608. Checked there is only 2 updates I'm missing and none of them addressing stability. I updated the plugin to 1.15 and will test but I don't expect improvements. Based on your comments it seems that I might need new and more powerful stick.

**Comment by Koenkk** [comment]
I also recommend the source routing firmware in that case (improves stability: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing)

**Comment by dirkam** [comment]
I have similar problem(s). @Pigotka what makes you think that you need a more powerful stick and what would you recommend?
@Koenkk is it needed to re-pair devices after reflashing? (or changing to source routing?)

Thanks

**Comment by Pigotka** [comment]
I think that because the cheap basic CC2531 is hard to update FW without additional HW and my network is very large (~40 devices). I think sooner I will do this better as it requires repairing. 
I selected zzh stick and it is on the way.
Btw. zigbee2mqtt 1.15 is awesome release but did not solve the issue.

**Comment by dirkam** [comment]
@Pigotka did you have a chance to set up the new stick? Does it perform better?

**Comment by Pigotka** [comment]
I ended up buying zzh stick and it works much better. I think my network was just too big to handle with cc2531 and I don't have debugger cables to flash it. I would maybe close this issue.
