### ISSUE TITLE
[Xiaomi Aqara RTCGQ11LM] No connect to router CC2531

### ISSUE THREAD

**Issue by Boia11** [Koenkk/zigbee2mqtt#4679]
## What happened
I have 3 Motion Sensor [Xiaomi Aqara RTCGQ11LM](https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html) but they connect only to coordinator and one of this sensor is too far.
I also try to add one router make with CC2531 flash as router with firmware [2020_09_29 std ](https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/CC2531/bin/CC2531_router_2020_09_29.zip) but nothing change.

## What did you expect to happen
Motion Sensor connect to other router (mostly with generic router make with CC2531).

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC2530+CC2592
Adapter firmware version: zStack12 - 20190608

![NetworkScan](https://user-images.githubusercontent.com/10048197/96178678-01eba780-0f30-11eb-928b-72e8400408c4.png)
![NetworkScan_complete](https://user-images.githubusercontent.com/10048197/96178679-02843e00-0f30-11eb-8cb7-8a860bded82c.png)

**Comment by onlinegill** [comment]
I have same issue no matter what i do none of sensor's are connecting to CC2531 routers.

**Comment by Boia11** [comment]
no news

**Comment by Koenkk** [comment]
Xiaomi sensor typically stick to the router/coordinator it was initially paired to, repairing the device close to the desired router helps (sometimes).

**Comment by Boia11** [comment]
No router pairing at 20 cm
