### ISSUE TITLE
unable to start zigbee2mqtt after reinstall

### ISSUE THREAD

**Issue by sander816** [Koenkk/zigbee2mqtt#4699]
## What happened
Reinstalled hassio and zigbee2mqtt

## What did you expect to happen
start zigbee2mqtt as usual

## Debug info
Zigbee2MQTT version: 1.15
Adapter hardware: cc2652rb_stick
Adapter firmware version: ?

pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.15.0 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2020-10-17 20:44:18: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-10-17.20-44-18' filename: log.txt
Zigbee2MQTT:info  2020-10-17 20:44:20: Starting Zigbee2MQTT version 1.15.0 (commit #ed8b4e5)
Zigbee2MQTT:info  2020-10-17 20:44:20: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-10-17 20:44:22: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-10-17 20:44:22: Failed to start zigbee
Zigbee2MQTT:error 2020-10-17 20:44:22: Exiting...
Zigbee2MQTT:error 2020-10-17 20:44:22: Error: SREQ '--> SYS - osalNvWrite - {"id":1,"offset":0,"osal":true,"product":-1,"value":[153,4,204,33,0,75,18,0],"len":8}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.15.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-10-17T19_44_22_906Z-debug.log

**Comment by Koenkk** [comment]
I'm not sure what happend, but is seems that the firmware got corrupted. Reflashing should fix it.
