### ISSUE TITLE
Allow to configure QoS

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#47]
I think it would be a relief if we could also activate the permit_join via mqtt.
This would help if you use the system in combination with the appropriate smarthome system and use your zigbee2mqtt headless.

Another improvement could be the Intergration of QoS.
This would help if we prioritize different Type of Devices and their mqtt Data.
This extension should be configurable for every device themselve.

**Comment by Koenkk** [comment]
This already possible: https://github.com/Koenkk/zigbee2mqtt/wiki/MQTT-topics-and-message-structure#zigbee2mqttbridgeconfigpermit_join

**Comment by tb-killa** [comment]
Mea culpa!
I constantly browse the wiki and have actually skipped it.
Okay, now ticked off a dot on the list thanks to your hint.
what do you think about the other idea ?

**Comment by ptvoinfo** [comment]
QoS is not possible yet. If you agree I can add it

**Comment by Koenkk** [comment]
Updated wiki: https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge#3-optional-device-specific-configuration

**Comment by Herwigvd** [comment]
Short question.

Should QoS work now?
I installed some time ago:
- Zigbee2MQTT version 1.27.0 (commit #a9b88082) with zigbee-herdsman (0.14.46)
- mosquitto 2.0.11

I put for some bulbs and plugs a 'QoS: 1' in configuration.yaml and also when subscribing in python, I give as parameter '1' for QoS (client.subscribe([(PlugKitchen, 1), (BulbDriveway, 1)])
But I see no difference in response in the logging between QoS=0 or QoS=1 (or even QoS=2)

Mean goal is to verify somehow if a device is present (and reachable).

Anyone uses this QoS already?

**Comment by bronger** [comment]
I see that I can set the QoS per device. Does this apply to both incoming and outgoing messages? I need to assure the message ordering of the commands to one of my devices, so I need the zigbee2mqtt _subscriptions_ to have a QoS of 2.
