### ISSUE TITLE
Ledvance 4058075208339 missing RGB command

### ISSUE THREAD

**Issue by klorydryk** [Koenkk/zigbee2mqtt#4700]
The led wire Ledvance 4058075208339 is available [in the documentation](4058075208339) but is incomplete: there is no information about the way we can set the RGB color.

**Comment by Koenkk** [comment]
See https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttfriendly_nameset how to set RGB color for lights supporting color.
