### ISSUE TITLE
PGC410 (US model) SmartThings Presence sensor will not pair

### ISSUE THREAD

**Issue by FoxConsult** [Koenkk/zigbee2mqtt#4704]
## What happened
I have a PGC410, US model (Not the EU model PGC410EU) SmartThings Presence sensor that will not pair.

## Debug info
I have posted debug log and zigbee-herdsman log as a comment to issue [4055](https://github.com/Koenkk/zigbee2mqtt/issues/4055).

**Comment by Koenkk** [comment]
This device requires a special CC2531 firmware, you can use this one: https://github.com/Koenkk/zigbee2mqtt/issues/4632#issuecomment-706691967

**Comment by FoxConsult** [comment]
Flashed special CC2531 firmware as per #4632 and the PGC410 now pairs. Thank you.
Will the code in the special CC2531 firmware branch make into the main branch?

**Comment by Koenkk** [comment]
@FoxConsult these changes will be integrated in https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2 later
