### ISSUE TITLE
Sort of log

### ISSUE THREAD

**Issue by phillipmj** [Koenkk/zigbee2mqtt#4716]
## Is your feature request related to a problem? Please describe
nope :3

## Describe the solution you'd like
It would be nice to have the log display in the top of the screen instead to the botten, When you have large network, it can be little hard to filter a divice out.

**Comment by sjorge** [comment]
I'm assuming this is for the web frontend? 

If yes, issues/features request for that should go here: https://github.com/nurikk/z2m-frontend/issues

**Comment by phillipmj** [comment]
Yes it is, and thanks to point me in the right direction here.
