### ISSUE TITLE
Support for Lonsonho Tuya Zigbee 1 Gang Dimmer Module

### ISSUE THREAD

**Issue by milobt** [Koenkk/zigbee2mqtt#4718]
## Information about the device + link
[https://www.aliexpress.com/item/4001279149071.html?spm=a2g0s.9042311.0.0.6f2a4c4dJnKQ0n](https://www.aliexpress.com/item/4001279149071.html?spm=a2g0s.9042311.0.0.6f2a4c4dJnKQ0n)

## data/database.db entry of the device

{"id":83,"type":"Router","ieeeAddr":"0xbc33acfffe65568e","nwkAddr":16123,"manufId":4098,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1603036906931}

**Comment by Krolik1988** [comment]
Already have support. I have one.

**Comment by milobt** [comment]
Support has since been added. 
Thanks.
