### ISSUE TITLE
Add entry of unsupported device in [..]/devices.js in case of a docker container

### ISSUE THREAD

**Issue by kooskaspers** [Koenkk/zigbee2mqtt#472]
I'm following this guide: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
in order to add compatibility for [this](https://tweakers.net/nieuws/143785/ikea-is-begonnen-met-verkoop-slimme-stekkerdozen-in-nederland.html) new Ikea wall socket switch:

https://cdn.smarthomemagazine.nl/wp-content/uploads/2018/09/Ikea-Smart-Plug-2-1-770x440.jpg

Paring was succesful:

```
zigbee2mqtt:info 2018-10-13 12:52:53 New device with address 0x90fd9ffffe31fb3f connected!
'{"type":"device_connected","message":"0x90fd9ffffe31fb3f"}'
zigbee2mqtt:warn 2018-10-13 12:52:53 Device with modelID 'TRADFRI control outlet' is not supported.
```

I'm running the zigbee2mqtt code in docker so I guess "node_modules/zigbee-shepherd-converters/devices.js" should be a file I need to alter inside this container.

When I want to get a shell:
`docker exec -it zigbee2mqtt /bin/bash`
It seems the container doesn't have this binary:
`ERROR: No such service: /bin/bash`

So whats the trick here to edit this devices.js file?

**Comment by Koenkk** [comment]
The new tradfri sockets is already supported, update to latest-dev container.

**Comment by kooskaspers** [comment]
Thanks Koen, updated to the latest dev container, and I'm able to control the socket now.
