### ISSUE TITLE
New Philips Hue Iris (Generation 2)

### ISSUE THREAD

**Issue by SamNitro** [Koenkk/zigbee2mqtt#4722]
hey I have a new Philips Hue Iris (Generation 2)

but it have a different model number.

```
    {
        zigbeeModel: ['929002376101'],
        model: '929002376101',
        vendor: 'Philips',
        description: 'Hue Iris (Generation 2)',
        meta: {turnsOffAtBrightness1: true},
        extend: hue.light_onoff_brightness_colorxy,
        ota: ota.zigbeeOTA,
    },
```

this is working for me

![images](https://user-images.githubusercontent.com/30635514/96470553-b4708280-122e-11eb-8d95-4e662728b3cd.jpeg)

And I have update by app, now I have a warning
`WARNING: Firmware on '0x0017880108575129' is newer than latest firmware online. `

**Comment by Koenkk** [comment]
Added the device!

About the firmware, we need to grab the latest firmware and add it to https://github.com/Koenkk/zigbee-OTA (but I'm not sure how to grab the firmware).

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
