### ISSUE TITLE
touchlink factory reset command fails

### ISSUE THREAD

**Issue by firex2** [Koenkk/zigbee2mqtt#4729]
## What happened

zigbee2mqtt throwing errors after sending the touchlink factory reset command.

My Adapter hardware: slae.sh cc2652rb stick (https://pastebin.com/Q626P49N)

i tested with two configuration sets:

1.)
Zigbee2MQTT version: 1.15.0 (commit #ed8b4e5)
Adapter firmware version: Z-Stack 3.x.0 20200925 firmware (CC2652RB_20200925.zip / znp_CC2652RB_LAUNCHXL_tirtos_ccs.hex)
Logs: https://pastebin.com/J7S4cGQz

2.)
Zigbee2MQTT version: 1.15.0-dev (commit #466e963)
Adapter firmware version: Z-Stack_3.x.0 20201017 firmware (CC2652RB_20201017.zip / CC2652RB_20201017.hex)
Logs: https://pastebin.com/KnuZYhbE

## What did you expect to happen

the command should reset my Hue Bulb so i can pair it with zigbee2mqtt

## How to reproduce it (minimal and precise)

just send the command

**Comment by Koenkk** [comment]
I've also seen this issue, it seems the firmware crashes (sometimes, not always) because of these commands. It something that cannot be fixed from Zigbee2MQTT but should be fixed by Texas Instruments in the firmware.
