### ISSUE TITLE
New Aqara wireless mini switch

### ISSUE THREAD

**Issue by kaelsaes** [Koenkk/zigbee2mqtt#473]
Okt 13 17:36:28 Raspberry-MQTT npm[2498]:   zigbee2mqtt:warn 2018-10-13 17:36:28 Device with modelID 'lumi.remote.b1acn01
Okt 13 17:36:28 Raspberry-MQTT npm[2498]:   zigbee2mqtt:warn 2018-10-13 17:36:28 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices

{"ieeeAddr":"0x00158d0001ef679e","type":"EndDevice","model":"lumi.remote.b1acn01\u0000\u0000\u0000\u0000\u0000\u0000","friendly_name":"0x00158d0001ef679e"}

**Comment by Koenkk** [comment]
Seems its already supported, could you update to the latest dev branch? https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L82

**Comment by kaelsaes** [comment]
@Koenkk 

Thanks.

How can I update the dev branch?

Is my devices.js overwritten with the update?

**Comment by Koenkk** [comment]
That can be done by checking out the dev branch (https://github.com/koenkk/zigbee2mqtt/tree/dev) and then: `rm -rf node_modules && npm install`. Your `devices.js` will be overwritten.
