### ISSUE TITLE
Data request failed with error: 'undefined' (241)

### ISSUE THREAD

**Issue by liquid-motion** [Koenkk/zigbee2mqtt#4735]
## What happened
All of a sudden my complete Zigbee network is failing.

- Network scan gives this LQI-error for all my devices:
`Zigbee2MQTT:error 2020-10-21 11:29:52: Failed to execute LQI for 'Spot-midden'`
- When I try to switch a light off, I get this message:
`Zigbee2MQTT:error 2020-10-21 11:31:08: Publish 'set' 'state' to 'Spot-keuken' failed: 'Error: Command 0x000d6ffffed64eed/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'undefined' (241))'`
- Network map shows my devices only connected to CC2531, but all with link-strength 0. There are no other routes anymore.

## What I tried so far
- I didn't update or change anything. It went down all of a sudden.
- I restarted Zigbee2Mqtt.
- I rebooted Hassio.
- I powered down the Rpi and changed the CC2531 to other USB ports.
- I rejoined devices to the network.

## Debug info
Zigbee2MQTT version: 1.15.0 (on Hassio)
Adapter hardware: CC2531
Adapter firmware version: zStack12 (20190223)

**Comment by Koenkk** [comment]
Does this still occur with the latest firmware? (I recommend this one: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing)

**Comment by ljan** [comment]
I get the same errors since about 2 days
CC2531 firmware is revision: CC2531_DEFAULT_20190608.zip

**Comment by liquid-motion** [comment]
> Does this still occur with the latest firmware? (I recommend this one: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing)

I have no idea. It was working fine with the firmware I'm using... until a few days ago.

**Comment by jti989** [comment]
I am observing the same behavior since today.
Discovered on the latest-dev docker image from yesterday, downgraded to 1.15.0 (which worked with my stick before), but no luck.
CC2531 firmware is revision: CC2531_DEFAULT_20190608.zip

I can help with logs if you want, just let me know.

**Comment by jti989** [comment]
I have reflashed the firmware, still using CC2531_DEFAULT_20190608, now it is works again.
Not sure what happened.

**Comment by Mocem1** [comment]
I had the same issue. For me unplugging the USB and restarting HA, Zigbee2mqtt and mosquito solved the problem.
