### ISSUE TITLE
Slaesh zigbee stick

### ISSUE THREAD

**Issue by cndian** [Koenkk/zigbee2mqtt#4736]
Hello,

I just received the Slaesh zigbee stick. I currently have the cc2531 stick.

I know I have to change the pan_id but have two questions about it.

Do I change the ID before unplug the old stick or can I put the new stick in first and then change the ID?

And when I've done I know I need to repair my devices. Should I first delete everything in domoticz or does it still know.my friendly names and settings after repair the devices?

Many thanks.

**Comment by flrahe** [comment]
Did you get any reply? I will have to do the same, except I'm using Homeassistant...

**Comment by cndian** [comment]
Not yet

**Comment by artist67** [comment]
I would recommend to stop z2m, then change the pan_id, swap the sticks an start z2m again.
Also check if the new stick is visible as ttyACM0 or ttyUSB0 and update the config file accordingly.
As I'm using Openhab, I cannot help further.

**Comment by Koenkk** [comment]
- Stop zigbee2mqtt
- Unplug CC2531, plug CC2652RB
- Update serial port path in `configuration.yaml` and change pan_id
- Start Zigbee2MQTT and start repairing
  - If repairing fails make sure to completely power down the old network first (power off all routers)

**Comment by flrahe** [comment]
Thank you for the reply. I had one open question:Where to change the pan_id to.
But there is a extended thread telling more details (i wished I found it earlier): [Easiest way to migrate from CC1352P-2 to zzh?](https://zigbee2mqtt.discourse.group/t/easiest-way-to-migrate-from-cc1352p-2-to-zzh/1304)
Just increase it by 1.

**Comment by Koenkk** [comment]
The default one is `0x162a`, so you can use `0x163a`

**Comment by cndian** [comment]
Thanks Koen, 

So I don't have to delete the devices?

**Comment by Koenkk** [comment]
@cndian nope, zigbee2mqtt will automatically reset the database when it creates a network (which is done when the panid changes)
