### ISSUE TITLE
XHK1-UE Keypad - Interview failed because can not get node descriptor

### ISSUE THREAD

**Issue by Rockman18** [Koenkk/zigbee2mqtt#4747]
Hello

I try to add compatibility with the [XHK1-UE keypad](https://www.ebay.fr/itm/XHK1-UE-Keyboard-Security-System-for-Home-Xfinity-With-4-Batteries/254207297775) but i can't manage to pair the device. Here are the logs + pcap sniff + database.db

I don't have the original gateway to compare the pairing process.

I have  tried the steps in: https://www.zigbee2mqtt.io/information/FAQ.html#interview-fails.
I have tried :
- reboot
- directly next to stick
- directly plugged in without extension cable
- replace the batteries of the keypad
- resetting + re-pairing quite a few times
- reflashing the stick, multiple times
- move in another room
- ...

Sometimes in an extremely rare situation the pairing process is better and the device announce itself then nothing more but sorry I can't reproduce that so I don't have logs.

I can pair other devices from Xiaomi without any issue.
I hope you can help me to go further

[logs.zip](https://github.com/Koenkk/zigbee2mqtt/files/5425983/logs.zip)

PS: FYI the pairing LED of the keypad stops blinking after the 3rd attempt in the logs, even by pressing the buttons it goes to sleep after 1 minute

EDIT : better logs [logs2.zip](https://github.com/Koenkk/zigbee2mqtt/files/5426235/logs2.zip)

**Comment by Rockman18** [comment]
@Koenkk : can you take a look and give me an advice on this issue please ?

**Comment by Rockman18** [comment]
For the first time since 5 days the pairing go further with the device announcing itself. Sadly my sniffer wasn't plugged in at this time so I don't have the pcapng file. But here is the zigbee-herdsman log file

[pairing_keypad_announce.log](https://github.com/Koenkk/zigbee2mqtt/files/5448575/pairing_keypad_announce.log)

**Comment by Koenkk** [comment]
@Rockman18 I've checked your log but the problem is the device does not stay in the network. In the sniff you can see that it keeps rejoining (Association request). I have no clue why, sometimes it helps to compare it with the original gateway but no guarantees here.

**Comment by Rockman18** [comment]
So sad. I hope to find a solution soon. Thanks

**Comment by Rockman18** [comment]
@Koenkk : I've changed my CC2531 by another one and this time it works...
