### ISSUE TITLE
SONOFF ZBMINI ZIGBEE TWO WAY SMART SWITCH

### ISSUE THREAD

**Issue by taifunk** [Koenkk/zigbee2mqtt#4752]
## Information about the device + link
SONOFF ZBMINI ZIGBEE TWO WAY SMART SWITCH got just released today. Right now it is only available from ITEAD site. I'm allready ordering mine and hope to see it's support  included in the next releases soon :thumbsup:
https://www.itead.cc/sonoff-zbmini-zigbee-smart-switch.html
..

**Comment by Koenkk** [comment]
I'm really interested in this device, I've ordered two :smile:

**Comment by way2many** [comment]
Ah damn, just bought the Lonsonho 1 gang switch for 17€. This 2 gang switch is 12€.

I hope that a dimming switch will come out soon enough.

**Comment by Koenkk** [comment]
@way2many it's not a 2 gang switch, its a 1 gang that can be controlled to way

Device is supported now.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by regenbieger** [comment]
thx for the speed, your faster then the delivery of itead ;)

**Comment by gcb2018** [comment]
@Koenkk Thanks! Stupid question but I am not an expert at all: but would the ZBMINI support dimming lights?

I am looking to replace the KAKU [Mini Inbouwdimmer](https://klikaanklikuit.nl/product/mini-inbouwdimmer/)

**Comment by Koenkk** [comment]
@gcb2018 no it doesn't support this.

**Comment by deviantintegral** [comment]
I've only ever been able to get this device to bind to a single group at a time. I had errors to the effect of `STATUS.TABLE_FULL` with `zha`, and trying this out in zigbee2mqtt it's not working, but I'm also not getting any errors, even with debug logging on.
