### ISSUE TITLE
MQTT Password in plain text

### ISSUE THREAD

**Issue by sti0** [Koenkk/zigbee2mqtt#4763]
## What happened
After pressing the "Permit Join" Button, the MQTT password gets logged in plain text.

![image](https://user-images.githubusercontent.com/18382402/97085734-91274800-161f-11eb-96e4-21152ab753fa.png)

## What did you expect to happen
For security reasons the password shouldn't be logged in plain text.

## How to reproduce it (minimal and precise)
Permit Join, check the log.

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment]
This has already been fixed in the latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
