### ISSUE TITLE
TS0601_Thermostat 

### ISSUE THREAD

**Issue by miromartinov** [Koenkk/zigbee2mqtt#4772]
## What happened
I have 4 tuya zigbee valves that are recognised as T0608_thermostat. They sucsessfully paired with CC2531 stick and Z2M version 1.15 install on Home assistant 0.116.4.
I receive info from valves - temperature , lock but I can not set temperature from HA - no errors in logs.

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version:

**Comment by insipiens** [comment]
Not TS0601 ?

**Comment by miromartinov** [comment]
The problm was in the valve - after FW upgrade everything works fine
