### ISSUE TITLE
"throw err" and "Error: Cannot find module 'semver'"

### ISSUE THREAD

**Issue by ChrisX1809** [Koenkk/zigbee2mqtt#4773]
Hey,

ive got a problem with running zigbee2mqtt. I had to reinstall my openhab system and installed at the openhabian-config mosquitto. With the help of the installation advises from the zigbee2mqtt page i tried to install. While starting with npm start i get the following failure:

Found this error message in combination with hassio that i dont use. 
I hope someone can help me. 

`
Oct 25 15:28:33 openHABianDevice npm[22732]: > node index.js
Oct 25 15:28:33 openHABianDevice npm[22732]: internal/modules/cjs/loader.js:834
Oct 25 15:28:33 openHABianDevice npm[22732]:   throw err;
Oct 25 15:28:33 openHABianDevice npm[22732]:   ^
Oct 25 15:28:33 openHABianDevice npm[22732]: Error: Cannot find module 'semver'
Oct 25 15:28:33 openHABianDevice npm[22732]: Require stack:
Oct 25 15:28:33 openHABianDevice npm[22732]: - /opt/zigbee2mqtt/index.js
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Module.require (internal/modules/cjs/loader.js:903:19)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at require (internal/modules/cjs/helpers.js:74:18)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Object.<anonymous> (/opt/zigbee2mqtt/index.js:1:16)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Module.load (internal/modules/cjs/loader.js:879:32)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
Oct 25 15:28:33 openHABianDevice npm[22732]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
Oct 25 15:28:33 openHABianDevice npm[22732]:   code: 'MODULE_NOT_FOUND',
Oct 25 15:28:33 openHABianDevice npm[22732]:   requireStack: [ '/opt/zigbee2mqtt/index.js' ]
Oct 25 15:28:33 openHABianDevice npm[22732]: }
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! code ELIFECYCLE
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! errno 1
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! zigbee2mqtt@1.15.0 start: `node index.js`
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! Exit status 1
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR!
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! Failed at the zigbee2mqtt@1.15.0 start script.
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Oct 25 15:28:33 openHABianDevice npm[22732]: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR! A complete log of this run can be found in:
Oct 25 15:28:33 openHABianDevice npm[22732]: npm ERR!     /home/openhabian/.npm/_logs/2020-10-25T14_28_33_867Z-debug.log
Oct 25 15:28:33 openHABianDevice systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 15:28:33 openHABianDevice systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Oct 25 15:28:34 openHABianDevice systemd[1]: zigbee2mqtt.service: Service RestartSec=100ms expired, scheduling restart.
Oct 25 15:28:34 openHABianDevice systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 616.
Oct 25 15:28:34 openHABianDevice systemd[1]: Stopped zigbee2mqtt.

`

**Comment by Koenkk** [comment]
You probably forgot the `npm ci` step of https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#2-installing. In the directory where you execute `npm start`, execute `npm ci` once.
