### ISSUE TITLE
Osram Classic A60 RGBW firmware struggle

### ISSUE THREAD

**Issue by HannesDi** [Koenkk/zigbee2mqtt#478]
i have started up switching from gateways to the stick and all works fine exept 1 bulb

... before started switching i made firmware updates from all bulbs...

zigbee2mqtt:debug 2018-10-14 18:54:37 Recieved zigbee message of type 'devStatus' with data '"online"' of device '0x57424752203036412063697373616c43' (0x8418260000cb8de8)

very strange because when i hex-convert this....
0x57424752203036412063697373616c43
-> hex-convert: WBGR 06A cissalC
-> flipped: Classic A60 RGBW

so its a : Osram Classic A60 RGBW
so it should be a: "AC03845" ???

so i have tried to follow the instructions for adding new devices and ended up with:

{
        zigbeeModel: ['Classic A60 RGBW v2'],
        model: '0x57424752203036412063697373616c43',
        vendor: 'OSRAM',
        description: 'Lightify Classic A60 RGBW v2',
        supports: generic.light_onoff_brightness_colortemp_colorxy().supports,
        fromZigbee: generic.light_onoff_brightness_colortemp_colorxy().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colortemp_colorxy().toZigbee,
    },

problem is i am running on HASSIO with the community plugin
i could edit the node_modules/zigbee-shepherd-converters/devices.js as described in the document
but after restarting the container it bombed out my edits...

could anybody update that so it appears in one of the next releases ?

best regards 
hannes

**Comment by Koenkk** [comment]
Looks like the same issue as in https://github.com/Koenkk/zigbee2mqtt/issues/388 which has already been fixed. Can you try updating to the latest version to verify that this has been solved?

**Comment by HannesDi** [comment]
Hi,

- i have switched off the osram bulb
- removed it from zigbee2mqtt database
- uninstalled the zigbee2mqtt plugin 
- reset the lamp complete by switching on/off 5seconds. 5times
- installed the zigbee2mqtt-edge 
- started up the join process
- switched bulb on again

result (cut down)

zigbee2mqtt:info 2018-10-16 09:11:19 Starting zigbee2mqtt version 0.1.7 (commit #b063e67)
zigbee2mqtt:info 2018-10-16 09:11:19 Starting zigbee-shepherd
zigbee2mqtt:debug 2018-10-16 09:11:19 zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":11,"panId":"0x1a63","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b00120234fa","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20180815},"startTime":1539673879,"joinTimeLeft":0}
zigbee2mqtt:info 2018-10-16 09:11:19 zigbee-shepherd started
zigbee2mqtt:info 2018-10-16 09:11:19 Coordinator firmware version: '20180815'
zigbee2mqtt:info 2018-10-16 09:11:19 Currently 9 devices are joined:
.
.
.
zigbee2mqtt:info 2018-10-16 09:11:19 0x8418260000cb8de8 (0x8418260000cb8de8): unkown - undefined unknown (Router)

so the long hex string is gone... but now its empty ;-(
no winning at all... whats next?

did you mean the "edge" version with latest version or the normal release 0..1.6 (which  allready was installed before)

**Comment by Koenkk** [comment]
Can you try repairing? This means the device has not been paired properly.

**Comment by HannesDi** [comment]
i have tried this this steps

- i have switched off the osram bulb
...
- switched bulb on again

3 times with same result

ill try it later again but with the normal/regular release 0.1.6 to check the software finds then the long hex string again

**Comment by HannesDi** [comment]
Wow.... there is something really strange going on....
I have now successful paired the Bulb with edge relase 0.1.7 as "AA69697" and not as "AC03845" but ok its fine...

The strage things going on is what i have seen during pairing process...
it used 20 - 30 trys to end up with a empty string....

so i have stopped the complete thing and moved away the registry/database file.

started up the service again and then it takes 15 seconds and only one try to say OK paired as "AA69697" 

so i have stopped the whole thing again and moved back my old database
and then it got really strange....

nodered dashboard showed me up for a second 82 devices and jumped back to the correct 9 (8 plus the wrong detected empty osram) so i used again the remove button 

and again the remove button it told me again removed...

so i take a look on the database file....

interesting... duplicate on duplicate on duplicate
so i slashed the remove button for a while and then the magic happens...
BING! successful paired....

so my conclusion.. i think there is need for a duplicate check in the database like check for double id's and drop all exept 1 

for me its solved but strange...... very strange....

**Comment by Koenkk** [comment]
@HannesDi I've seen similar issues with devices that had already been connected to the network, but happy to see your problem has been solved.
