### ISSUE TITLE
Essentials 120112 ESS-HK-TRV-6103 same Siterwell GS361A-H04 ?

### ISSUE THREAD

**Issue by lister3003** [Koenkk/zigbee2mqtt#4786]
## Information about the device + link
Hi
i have essentials Smart Home Heizkörperthermostat Premium (item no.  120112) with label ESS-HK-TRV-6103
Is this thermostat same as GS361A-H04 ?

[iobroker.2020-10-25.txt](https://github.com/Koenkk/zigbee2mqtt/files/5441580/iobroker.2020-10-25.txt)

LINK: [essentials Smart Home Heizkörperthermostat Premium](https://www.wesmartify.de/heizung/heizkoerperradiator/281/essentials-smart-home-heizkoerperthermostat-premium/?number=120112)

![01 Essentials 120112](https://user-images.githubusercontent.com/73495735/97217405-84ddef00-17c7-11eb-8241-a82932ada762.JPG)
![02 Essentials 120112](https://user-images.githubusercontent.com/73495735/97217409-85768580-17c7-11eb-8105-e959c8d5e18d.jpg)
![03 Essentials 120112](https://user-images.githubusercontent.com/73495735/97217413-86a7b280-17c7-11eb-801e-4d2540c7368a.jpg)

## data/database.db entry of the device
..

**Comment by sjorge** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices.js#L13812

Yes, it's marked as a while label ... both are from the same TuYa design.
