### ISSUE TITLE
Tradfri not pairing

### ISSUE THREAD

**Issue by jonasled** [Koenkk/zigbee2mqtt#4790]
## What happened
I tried pairing 2 new tradfri bulbs, with my zigbee2mqtt using a CC2531 Stick. The problem is, it never shows up in the log (does not start pairing). I tried already a different PC and a different CC2531 Stick and also reflashed one. Pairing with the original tradfri bridge works flawlessly (of course I've reseted the bulb afterwards). Permit join is also enabled (repairing a old bulb works)

## What did you expect to happen
Device pairs with the bridge.

## How to reproduce it (minimal and precise)
Try to pair a E14 tradfri bulb with the newest firmware.

## Debug info
Zigbee2MQTT version: 1.15.0 (hass.io)
Adapter hardware: CC2531
Adapter firmware version:{"meta": "maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}

**Comment by io53** [comment]
Does the bulb flash when you have reset it? I've had some trouble resetting trådfri e14, turned out I was doing the 6 on/off too fast (a problem I've not had with gu10 nor e27 bulbs).

**Comment by jonasled** [comment]
No, they don't flash, but first I tried pairing them to the homeassistant and afterwards paired them successfully with the tradfri bridge, so the were resetted I think.

**Comment by jonasled** [comment]
Hmm, interesting. I tried the bulb I thought is dead with the tradfri GW and it works there also, but pairing with the homeassistant doesn't work.

**Comment by jonasled** [comment]
Ok, some progress. After a lot of tries I've got them reset again. Now they blink forever, but don't pair.

**Comment by jonasled** [comment]
I get them slowly to repair after resetting everything to factory defaults. The reset just needs some very hard timing, GG ikea.
