### ISSUE TITLE
OTA Update fails with ECONNREFUSED

### ISSUE THREAD

**Issue by kianusch** [Koenkk/zigbee2mqtt#4794]
When trying to update my IKEA Bulb via the current version of zigbee2mqtt I get an error:

{
  "message": "Update of 'AZ.E27.01' failed (connect ECONNREFUSED 13.225.25.117:80)",
  "meta": {
    "device": "AZ.E27.01",
    "status": "update_failed"
  },
  "type": "ota_update"
}

... could it be, that the IKEA Firmware Site (13.225.25.117) is down?

**Comment by lorek123** [comment]
http://fw.ota.homesmart.ikea.net/feed/version_info.json looks fine here, maybe there is something that preventing zigbee2mqtt from connection to the server?

**Comment by kianusch** [comment]
What happens if you connect to 13.225.25.117:80 from your browser?

I get a "403 ERROR".

**Comment by kianusch** [comment]
Okay - seemed to be a problem with my docker host.  After rebooting everything works fine now.
