### ISSUE TITLE
Possibility to capture NodeJs crash messages to a log file

### ISSUE THREAD

**Issue by ptvoinfo** [Koenkk/zigbee2mqtt#48]
It will be very useful to capture crash messages and all console output to a log file. It will help to diagnose problems with new functionality on headless systems or if the script works in the service mode.

**Comment by Koenkk** [comment]
Zigbee2mqtt log is already written to `data/log.txt`. 

For the exception, I prefer the accepted solution from https://stackoverflow.com/questions/10122245/capture-node-js-crash-reason (your process manager is responsible of this).

**Comment by ptvoinfo** [comment]
In this case I will get 2+ log files. In case of a problem I must open both files and sync these files by time. If debug output is enabled this process can be hard.

**Comment by ciotlosm** [comment]
You can run tail on multiple files with "-f": tail -f /var/log/auth.log /var/log/daemon.log

**Comment by Koenkk** [comment]
In that case you would do: `npm start 1> log.out 2> log.out`

**Comment by ciotlosm** [comment]
@danielwelch Maybe add this setup for https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/run.sh#L16 for easier debugging. It does makes sense to keep one log with timestamps when debugging.

**Comment by ciotlosm** [comment]
@ptvoinfo can this issue be closed?

**Comment by ptvoinfo** [comment]
@ciotlosm yes, please. I'm using the method:

> npm start 1> log.out 2> log.out
