### ISSUE TITLE
Xiaomi Gateway

### ISSUE THREAD

**Issue by hanross2323** [Koenkk/zigbee2mqtt#480]
Hi guys

I know the main purpose for this brilliant addon is precisely to get rid of them but, is it possible to connect the xiaomi gateway via zigbee and be able to control its speaker and light through MQTT messages?

Regards

**Comment by ptvoinfo** [comment]
From my point of view, the Xiaome gateway acts as a coordinator. It builds an own network and cannot connect to another one. Therefore zigbee2mqtt cannot control it. It is possible to the gateway from the server side, emulation a server protocol.
