### ISSUE TITLE
Immax Neo Smart Thermostatic Head (07703L) - OEM ETOP HT-10

### ISSUE THREAD

**Issue by jakliimre** [Koenkk/zigbee2mqtt#4811]
Please add support for the Immax NEO Smart Thermostatic Head type 07703L!

I could run them (16 valves setup) successfully (in HA) for more than a week using ETOP HT-10 device as a template.
It is an OEM version of that, picture is the same. The "HT-10" type is mentioned once in the manual, probably left 
there accidentally. :-)

I haven't checked all functionality yet (e.g. daily temperature program programming), but the basic functions
are working well: temperature readouts, temperature settings, mode switching etc. 
Implementation is in aggreement with my Zigbee captures using the Immax gateway, except one: original gateway using
UNIX timestamp for setting date and time, but the one implemented also accepted by the devices.
I haven't experienced any issues yet!

Thank you!

Kind regards, Imre

```
zigbee-herdsman-converters/devices.js:
    {
        zigbeeModel: ['losfena\u0000'],
        fingerprint: [{modelID: 'losfena\u0000', manufacturerName: '_TYST11_losfena'}],
        model: '07703L',
        vendor: 'Immax',
        description: 'Immax NEO Smart Thermostatic Head',
        supports: 'thermostat, temperature',
        fromZigbee: [
            fz.tuya_thermostat_weekly_schedule,
            fz.etop_thermostat,
            fz.ignore_basic_report,
            fz.tuya_ignore_set_time_request, // handled in onEvent
        ],
        toZigbee: [
            tz.etop_thermostat_system_mode,
            tz.etop_thermostat_away_mode,
            tz.tuya_thermostat_child_lock,
            tz.tuya_thermostat_current_heating_setpoint,
            tz.tuya_thermostat_weekly_schedule,
        ],
        onEvent: tuya.setTime,
        meta: {
            thermostat: {
                weeklyScheduleMaxTransitions: 4,
                weeklyScheduleSupportedModes: [1], // bits: 0-heat present, 1-cool present (dec: 1-heat,2-cool,3-heat+cool)
                weeklyScheduleFirstDayDpId: 101,
            },
        },
    },
```

I asked the Czech company selling them. They have sent the following files about packet formats.
![Page1](https://user-images.githubusercontent.com/73639540/97551410-3dc44980-19d3-11eb-8041-d451c94f5f71.png)
![Page2](https://user-images.githubusercontent.com/73639540/97551412-3ef57680-19d3-11eb-887a-22c233d9d54a.png)
![Page3](https://user-images.githubusercontent.com/73639540/97551415-3ef57680-19d3-11eb-91d5-d4deedcf07e5.png)
They are basically the same what I have seen somewhere related to ETOP HT-10.

**Comment by Koenkk** [comment]
This device is already supported https://github.com/Koenkk/zigbee-herdsman-converters/blob/e802bff38450f15363959470dc135eb96944303c/devices.js#L9709, in case you want to make any changes to the current definition please create a pull request.
