### ISSUE TITLE
Problem with Legrand Netatmo wired shutter switch 067776

### ISSUE THREAD

**Issue by Riseryn** [Koenkk/zigbee2mqtt#4819]
# Bug Report
## What happened
The parameter "position" only work with 0(closed) and 100(open) value.
Other value doesn't work.
## What did you expect to happen
I expect position: 50 to half open the store
## Debug Info
Zigbee2MQTT version: 1.15
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

**Comment by Koenkk** [comment]
@cemonneau  does this work for you?

**Comment by Riseryn** [comment]
using mqtt.fx 1.7.1 to retrieve informations.
when I manually activate the shutter control button I get 3 messages which are:

zigbee2mqtt/shutter
{
  "action" : "moving",
  "linkquality" : 26,
  "position" : 50
}

{
  "linkquality" : 26,
  "position" : 50
}

{
  "linkquality" : 28,
  "position" : 50
}

 "position" : 50 corresponds to the last requested position and not to the actual position of the shutter.

**Comment by Riseryn** [comment]
No ideas about this issue?

**Comment by eRJe79** [comment]
@Riseryn did you get any further with this?

**Comment by Riseryn** [comment]
Hi,
absolutely not.
Im unable to move at a specified position. Only open and close.

**Comment by eRJe79** [comment]
@Koenkk can we reopen this issue?

**Comment by alapasset** [comment]
@Koenkk  can we reopen this issue?

**Comment by cyrilphoenix71** [comment]
Hello I have the same problem with white version 067726, use position slide bar doesn't work, I have always 50 in position state.
Could you help us ? @Koenkk

**Comment by Koenkk** [comment]
For this device standard zigbee commands are used. First impresion is that this device simply doesn't support intermediate positions (but someone should check this with the original hub)

**Comment by benjR** [comment]
Same issue for me, unfortunately I don't have the Legrand Hub to test.

**Comment by cyrilphoenix71** [comment]
I hear about new firmware on this device that open functionnality but I don't know how can I do that

**Comment by benjR** [comment]
@cyrilphoenix71 do you have a link?

**Comment by bemble** [comment]
> I hear about new firmware on this device that open functionnality but I don't know how can I do that

Where did you get this? The device is not listed on Legrand compatible list..: https://developer.legrand.com/documentation/compatible-product/

**Comment by bemble** [comment]
As said on #12655, not even possible on legrand app, we have to wait for firmware upgrade that brings it.
