### ISSUE TITLE
Home Assistant Scenes Discovery

### ISSUE THREAD

**Issue by kiall** [Koenkk/zigbee2mqtt#4821]
## Describe the solution you'd like

The new Scenes support is great, but configuring Home Assistant to use them reminds me of the bad old days :D We should add discovery support.

I've submitted a PR to HA to add MQTT Scenes: https://github.com/home-assistant/core/pull/42639 & https://github.com/home-assistant/home-assistant.io/pull/15497 - I'd love some review of that PR to ensure it'll suit current and future plans. For now (and at least IMO, for a long time..), Home Assistant only needs to be able to activate/recall a scene - so that's what I've implemented.

## Describe alternatives you've considered

Manually configuring scripts and buttons and so on in HA to configure scenes.

## Additional Context

Related to https://github.com/Koenkk/zigbee-herdsman-converters/pull/1531

**Comment by Koenkk** [comment]
Looks good! Once it's implemented we can look into the Z2M implementation.

**Comment by kiall** [comment]
Still WIP over at HA: https://github.com/home-assistant/core/pull/42639

**Comment by kiall** [comment]
And, support has merged to HA & is included in the just announced v1.0.0 rc.

**Comment by sjorge** [comment]
Just wonder if there is also view and remove support on the hass side, we don't have it yet in z2m... but should probably at least add scene_remove and maybe scene_remove_all, it's on my way to long list of things to do -_-

**Comment by kiall** [comment]
On the HASS side, no - just the ability to activate a scene for now. I don't think it supports anything other than activating an external scene, but I could be wrong on that!

**Comment by sjorge** [comment]
Ah so only scene_recall! I guess pushing complex scenes to the group/device might be a bit complicated to implement yeah.

**Comment by kiall** [comment]
Yep - I figured that would be by far the most useful thing, so it's all I set out to do :) Though, on the way through doing it, I've figured it's likely not possible to add other actions anyway!

**Comment by MattWestb** [comment]
Good to implanting in HA is save scene / groupe command being sent to Z2M. Also for the default scene groupe 0x0000 (and IKEA remote 0xff09).

**Comment by ndfred** [comment]
For those wanting to try scene integration in HA, it is not in the official release just yet. Adding this section causes an error message `Setup failed for scenes: Integration not found` in the HA logs:

    scenes:
      - platform: "mqtt"
        name: Living Room Bright
        unique_id: living_room_bright
        command_topic: "zigbee2mqtt/living_room/set"
        payload_on: '{"scene_recall": 4}'

      - platform: "mqtt"
        name: Living Room Dimmed
        unique_id: living_room_dimmed
        command_topic: "zigbee2mqtt/living_room/set"
        payload_on: '{"scene_recall": 5}'

      - platform: "mqtt"
        name: Living Room Nightlight
        unique_id: living_room_nightlight
        command_topic: "zigbee2mqtt/living_room/set"
        payload_on: '{"scene_recall": 6}'

I'll wait until the next HA release comes out and try this again, apparently the next one should be on the [first Wednesday in January](https://www.home-assistant.io/blog/2020/12/13/release-202012/).

**Comment by kiall** [comment]
MQTT scenes support has definitely landed in the 2020.12 release, no need to wait till January!

Your config example looks correct, I don't know why you would be seeing that error. Are you sure HA's MQTT is setup correctly?

**Comment by ndfred** [comment]
I am on 2020.12.1 and am getting this error message though, and indeed your changes are [listed in the changelog](https://www.home-assistant.io/blog/2020/12/13/release-202012/). Found why that was the case, I had this default section in my config file that I never really used since this is my first time leveraging HA scenes:

    scene: !include scenes.yaml

This means I would have redefined the scene section which YAML wouldn't have been keen on, but really my mistake was to introduce a `scenes` rather than `scene` section. I just moved my stuff over to `scenes.yaml` and there is :

    - platform: "mqtt"
      name: Living Room Bright
      unique_id: living_room_bright
      command_topic: "zigbee2mqtt/living_room/set"
      payload_on: '{"scene_recall": 4}'

    - platform: "mqtt"
      name: Living Room Dimmed
      unique_id: living_room_dimmed
      command_topic: "zigbee2mqtt/living_room/set"
      payload_on: '{"scene_recall": 5}'

    - platform: "mqtt"
      name: Living Room Nightlight
      unique_id: living_room_nightlight
      command_topic: "zigbee2mqtt/living_room/set"
      payload_on: '{"scene_recall": 6}'

If I go to Configuration > Scenes in HA they're all there and work really well! Thanks for the pointers, and sorry for my silly mistakes :)

**Comment by RobertMe** [comment]
I've been searching for this feature and could only find this ticket. As it's closed without any PR or commits being linked I think this feature request has gone stale and isn't implemented, am I correct?

The part on Home Assistants end obviously has been added, but nu discovery support has been added to Zigbee2mqtt? As this would be my last hurdle to ditch the Hue Bridge.

**Comment by jkaberg** [comment]
Dumb bot, no cookie for you

**Comment by GhostPunk** [comment]
Is this feature still on the roadmap? Manually defining scenes work like a charm since HASS merged the PR but obviously would be better if it would be automatic.

**Comment by RobertMe** [comment]
I might be able to work on this.

But checking the code I'm really confused on how to get a proper list of scenes and what they are bound to. I did find  `Endpoint.meta?.scene` and `Group.meta?.scene` which could be used, but this means having to iterate over all devices and groups, getting their scenes, splitting the "code" (being `<scene id>_<group id>`) checking if the scene is for a group (`group_id` not being `0`) and using the groups friendly name in that case or if the scene is for the device itself (`group_id` being `0`) using the friendly name of the device itself which would be the topic to invoke. And what further complicates this is that when changing the group or device name the topic will obviously change as well so in that case the HA discovery must be re-done too. Furthermore the scene name is stored as part of the scene metadata on the device/endpoint. So it even is possible that a group with two devices will have a different scene name set, so which name should be used then? As IMO this should be the auto generated entity name in HA.

**Comment by timdonovanuk** [comment]
Sooo...is this added or going to be added? Really confusing info in this thread! It doesn't seem like z2m scenes are mqtt auto discovered by HA yet.

**Comment by chinconl** [comment]
Could you copy the behavior from Hue/HA? It works fine there.

**Comment by ukmgranger** [comment]
I assume that this never got added / implemented?  Would be really useful to be able to see / use scenes easily in HA.

**Comment by radclif** [comment]
I would also love it if Z2M scenes where synced to HA and not having to redefine every scene in the YAML. I have 200+ zigbee devices and it's a big pain to manage it all. I am a PHP programmer (I know some Python) and I would love to help on this but I don't know where to start.
