### ISSUE TITLE
Nue 3a single gang switch not responding to HA commands

### ISSUE THREAD

**Issue by grantleyring** [Koenkk/zigbee2mqtt#4824]
![screenshot-10-10-10-120-8123-config-info-1604128381254](https://user-images.githubusercontent.com/41449958/97773543-ccd48b80-1ba4-11eb-99a5-9b9722d0340e.png)

 I have several Nue 3a Zigbee switches connect to HA, 2 and 3 gang variants (no issues with these multi gang switches). I connected a single gang switch some weeks ago and could see the switch in developer tools states but could not contol the switch via HA panels. After exhausting efforts to get it working, I concluded the switch must be faulty and purchased a second switch, which has exactly the same issue.

The attached Image below shows one of the switches installed. **Notice filter states show the state of the switch as off whilst attributes show the state is on**. This is the result of turning the switch on at the physical switch. When operating the switch from HA dashboard there is no response from the physical switch.

## What happened
This is a response I get from MQTT topic when i turn the switch on/off from the physical switch

Message 260 received on zigbee2mqtt/0x00158d000476b312 at 6:08 PM:
{
    "linkquality": 70,
    "state": "ON"
}
Message 384 received on zigbee2mqtt/0x00158d000476b312 at 6:08 PM:
{
    "linkquality": 92,
    "state": "OFF"
}

 This is the MQTT response when I try to operate the switch from the HA dashboard.

Message 510 received on zigbee2mqtt/0x00158d000476b312/set at 6:10 PM:
True
QoS: 0 - Retain: false

Switch Config:
 - platform: mqtt
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/0x00158d000476b312/set"
    device: 
      identifiers: 
      - zigbee2mqtt_0x00158d000476b312
      manufacturer: "Nue / 3A"
      model: "Smart one gang wall switch (HGZB-41)"
      name: 0x00158d000476b312
      sw_version: "Zigbee2MQTT 1.15.0"
    json_attributes_topic: "zigbee2mqtt/0x00158d000476b312"
    name: 0x00158d000476b312_switch
    payload_off: OFF
    payload_on: ON
    state_topic: "zigbee2mqtt/0x00158d000476b312"
    unique_id: 0x00158d000476b312_switch_zigbee2mqtt
    value_template: "{{ value_json.state }}"

An extract from the Zigbee2mqtt debug log below appears to indicate the switch is unsupported but this is contrary to the documentation and the model is also listed in the file: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Zigbee2MQTT:warn  2020-10-31 21:54:02: Received message from unsupported device with Zigbee model 'undefined'
Zigbee2MQTT:warn  2020-10-31 21:54:02: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:debug 2020-10-31 21:54:06: Received MQTT message on 'zigbee2mqtt/0x00158d000476b312/set' with data 'True'
Zigbee2MQTT:error 2020-10-31 21:54:06: Invalid JSON 'True', skipping...

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC2531
Adapter firmware version:

Hardware config:
serial:
  - /dev/ttyACM0
  - >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0001570D8B-if00
  - /dev/ttyAMA0
input: []
disk:
  - /dev/mmcblk0
  - /dev/mmcblk0p1
  - /dev/mmcblk0p2
  - /dev/mmcblk0p3
  - /dev/mmcblk0p4
  - /dev/mmcblk0p5
  - /dev/mmcblk0p6
  - /dev/mmcblk0p7
  - /dev/mmcblk0p8
gpio:
  - gpiochip504
  - gpiochip0
usb:
  - /dev/bus/usb/001/001
  - /dev/bus/usb/001/002
  - /dev/bus/usb/001/003
  - /dev/bus/usb/002/001
audio:
  '0':
    name: bcm2835_alsa - bcm2835 ALSA
    type: ALSA
    devices:
      - chan_id: '0'
        chan_type: digital audio playback
      - chan_id: '1'
        chan_type: digital audio playback
      - chan_id: '2'
        chan_type: digital audio playback
![screenshot-10-10-10-120-8123-developer-tools-state-1604132384391 (2)](https://user-images.githubusercontent.com/41449958/97774763-a0be0800-1bae-11eb-9e8a-fe2757ad8ac4.png)

**Comment by Koenkk** [comment]
Can you provide the Zigbee2MQTT debug log when controlling the device via HA?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by grantleyring** [comment]
Thankyou for being so quick absolutely fantastic. I think I am supposed to supply a link to this file, but I don,t know how to do that so I added a copy of the log in a file here, I have editied the file at the bottom to show where I controlled the switch from HA. It also shows the other single gang switch that has the same issue.

Hope this is what you want and thanks again.

[Zigbee2mqtt_log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5470009/Zigbee2mqtt_log.txt)

**Comment by Koenkk** [comment]
```
Zigbee2MQTT:debug 2020-11-01 11:11:25: Received MQTT message on 'zigbee2mqtt/0x00158d000476b312/set' with data 'True'
Zigbee2MQTT:error 2020-11-01 11:11:25: Invalid JSON 'True', skipping...
Zigbee2MQTT:debug 2020-11-01 11:11:26: Received MQTT message on 'zigbee2mqtt/0x00158d000476b312/set' with data 'False'
Zigbee2MQTT:error 2020-11-01 11:11:26: Invalid JSON 'False', skipping...
```

HA does send an incorrect payload when controlling the device, could you make a small gif/video how you control the device via HA?

**Comment by grantleyring** [comment]
Thanks @Koenkk 

Hope these files are OK.
I have simply created an entities card with a single switch pointing to the entity. Notice the switch does not remain on and goes of by itself after approx 2 seconds.

![screenshot-10-10-10-120-8123-lovelace-test-1-1604227703618](https://user-images.githubusercontent.com/41449958/97801062-2b296900-1c8e-11eb-9412-43548fd0028e.png)
![captured](https://user-images.githubusercontent.com/41449958/97801063-2c5a9600-1c8e-11eb-9e14-530093c55f4e.gif)
![screenshot-10-10-10-120-8123-lovelace-test-1-1604227665184](https://user-images.githubusercontent.com/41449958/97801066-2ebcf000-1c8e-11eb-806f-659831f8b05b.png)

**Comment by Koenkk** [comment]
Can you post the debug log of the Zigbee2MQTT startup? (+- first 30 seconds?)

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by grantleyring** [comment]
This is the Zigbee2mqtt configuration file and the logfile following a restart of HA.
If it would make life any easier for you, let me know and I will create an account for you to login as I use nabu casa which I am assuming you can use to get to my system (as long as you dont laugh at my novice setup ).

Regards,
Grant

[Zigbee2mqtt_config.txt](https://github.com/Koenkk/zigbee2mqtt/files/5470844/Zigbee2mqtt_config.txt)
[Zigbee2mqtt_startup.txt](https://github.com/Koenkk/zigbee2mqtt/files/5470845/Zigbee2mqtt_startup.txt)

**Comment by Koenkk** [comment]
@grantleyring I think you grabbed the log from the page as the log does not start at the Zigbee2MQTT start. I think you can grab the complete log file from the `data/log` directory (which is next to the Zigbee2MQTT configuration.yaml file).

**Comment by grantleyring** [comment]
Hope this one is better.
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5470897/log.txt)

**Comment by Koenkk** [comment]
This looks like a Home Assistant bug to me, the discovery information states to use `ON`/`OFF` but `true`/`false` is sent. I have no clue why this does not occur people (for me this is working fine).

Discovery payload: `{"availability_topic":"zigbee2mqtt/bridge/state","command_topic":"zigbee2mqtt/0x00158d000476b312/set","device":{"identifiers":["zigbee2mqtt_0x00158d000476b312"],"manufacturer":"Nue / 3A","model":"Smart one gang wall switch (HGZB-41)","name":"0x00158d000476b312","sw_version":"Zigbee2MQTT 1.15.0"},"json_attributes_topic":"zigbee2mqtt/0x00158d000476b312","name":"0x00158d000476b312_switch","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x00158d000476b312","unique_id":"0x00158d000476b312_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}`

@emontnemery  is this a known issue?

**Comment by grantleyring** [comment]
This got above my pay grade after "Starting Zigbee2MQTT version 1.15.0"  (LOL) is there anything I can do?
Regards,
Grant.

**Comment by emontnemery** [comment]
From the issue description it seems like @grantleyring has manually configured the switch instead of relying on MQTT discovery.

There are a few things about that which are not obvious:
- `device` configuration is not possible through `configuration.yaml`, this is mentioned in the HA docs
- YAML is **extremely** particular in how it treats unquoted strings. One gotcha is that the following unquoted strings will be parsed as booleans:  y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF

**Comment by grantleyring** [comment]
Hi @emontnemery ,

You are absolutely correct I have manually configured these switches which I do in switches.yaml. I do this only because after attempting to enable auto discovery and multiple reinstallations of both MQTT and Zigbee2MQTT I was unable to get auto discovery working (in spite of reading the documation several times). I assume this is ignorance on my part but I do not want to consume the valuable and busy time of people like yourselves who have far more important problems to solve.

So my process is to read the MQTT (Listen to a topic) in the pairing phase convert the json to yaml via an online program and put this into my switches file. It appears to work for all but the single gang switches.

Is the solution as simple as placing quotes within the switch definition?

Regards,
Grant.

**Comment by grantleyring** [comment]
Yes the solution is to Quote the payload parameters.  Tried it and all is good
My sincere thanks to all that helped in this great stuff guys,
Reagrds,
Grant.
