### ISSUE TITLE
OSRAM SMART+ 4x switch version AB371860155|x1117

### ISSUE THREAD

**Issue by Plazmin** [Koenkk/zigbee2mqtt#4827]
This switch is recognized as "Switch 4x EU-LIGHTIFY" model: '4058075816459' Short and long presses work properly but the switch does not report battery status. Where is the problem? Do I need to configure something extra?
![switch](https://user-images.githubusercontent.com/62091912/97788402-e97abe80-1bb8-11eb-9940-0b69bf6c3580.png)

**Comment by Koenkk** [comment]
Battery can take up to 24 hours to report after pairing, did you wait this long?

**Comment by Plazmin** [comment]
Yes. I waited a few days, but there is no information about the battery status. Osram SMART + Motion Sensors (AC01353010G) send information about the battery every time. Is it different with the 4x switch? Maybe the switch only reports if the battery is low?

**Comment by Koenkk** [comment]
Well found that is indeed a battery report, fixed this.

Changes will be available in the latest dev branch tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Plazmin** [comment]
Thank you for your quick reply and your work. I have a question. Will this patch also work with my version of the switch, i.e. AB371860155|x1117 ?

**Comment by Koenkk** [comment]
Yes

**Comment by Plazmin** [comment]
Now, after changing the firmware from the dev branch and pairing the switch again, everything works fine. Thank you Koenkk.
