### ISSUE TITLE
zigbee2mqtt autostart with systemd fails on first try

### ISSUE THREAD

**Issue by Invento3D** [Koenkk/zigbee2mqtt#4829]
I have set up the following service to start at boot:
```                                                        
[Unit]
Description=zigbee2mqtt
After=network.target

[Service]
ExecStartPre=/bin/sleep 5
ExecStart=/usr/bin/npm start
WorkingDirectory=/opt/zigbee2mqtt
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target
```

However, it doesn't work. After rebooting my system, I get the following in the zigbee2mqtt log:
![grafik](https://user-images.githubusercontent.com/27298166/97792330-00330c80-1bdd-11eb-926e-6c9b11e53c1c.png)

The thing is, if I now start zigbee2mqtt again manually via `sudo systemctl start zigbee2mqtt.service`, it starts up correctly.
As you can see I already tried to delay the autostart of the service a bit by `ExecAfter`, but that didn't seem to be the issue here.

I'm running zigbee2mqtt in combination with Home Assistant on an Ubuntu 20.04-based lxc container inside Proxmox.

**Comment by Koenkk** [comment]
Please provide the herdsman debug log of the startup error.

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by Invento3D** [comment]
I found the problem.
The service was not even auto-starting anymore.
After re-enabling it with `sudo systemctl disable zigbee2mqtt.service && sudo systemctl enable zigbee2mqtt.service` it works again.
