### ISSUE TITLE
Zemismart Tubular motor not recognized

### ISSUE THREAD

**Issue by rodrigorsdev** [Koenkk/zigbee2mqtt#4839]
The Zemismart Tubular ZM25TQ engine is available on compatible devices, but is not recognized.

I get the message:

Zigbee2MQTT:warn  2020-11-01 12:56:05: Received message from unsupported device with Zigbee model 'TS0601'
Zigbee2MQTT:warn  2020-11-01 12:56:05: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by Koenkk** [comment]
Can you share the `data/database.db` entry of this device?

**Comment by rodrigorsdev** [comment]
this is it?

{"id":16,"type":"Router","ieeeAddr":"0x5c0272fffe8a5a2b","nwkAddr":23355,"manufId":4098,"manufName":"_TZE200_fzo2pocs","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,10,4,5,61184],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"65503":"��\u0004'\u0013\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0005\u0000\u0000\u0000\u0000\u0012\u0000\u0000\u0000\u0000\u0013","65506":21,"modelId":"TS0601","manufacturerName":"_TZE200_fzo2pocs","powerSource":1,"zclVersion":3,"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"meta":{}}},"appVersion":82,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1604340041164}

**Comment by Koenkk** [comment]
Added, please confirm.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by rodrigorsdev** [comment]
How can I test de dev version on Hassio?

**Comment by Koenkk** [comment]
@rodrigorsdev use the edge version of the addon.

**Comment by rodrigorsdev** [comment]
It worked, thanks
