### ISSUE TITLE
Battery warnings after update 0.1.7

### ISSUE THREAD

**Issue by kaelsaes** [Koenkk/zigbee2mqtt#484]
After update to 0.1.7 the battery levels are wrong.

**Comment by Koenkk** [comment]
A lookup is now used to determine the battery voltage (as this is non linear), see https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L14.

**Comment by Koenkk** [comment]
Then probably the lookup is wrong, do you know at which voltage the sensors stop working?

**Comment by kaelsaes** [comment]
No, I don't know when they stop working.

What do you mean with lookup?

**Comment by jpmassena** [comment]
> Then probably the lookup is wrong, do you know at which voltage the sensors stop working?

Can I ask where did you get the data for the lookup values?

**Comment by evildad** [comment]
@jpmassena 
https://github.com/Koenkk/zigbee-shepherd-converters/pull/77
