### ISSUE TITLE
permit_join' failed with error

### ISSUE THREAD

**Issue by Aiace88** [Koenkk/zigbee2mqtt#4841]
## What happened
when i click to device join, i have this message and in the logs nothing the new sensor / device.
https://hastebin.com/equnadapez.apache

![2020-11-01 20_29_47-Window](https://user-images.githubusercontent.com/35429685/97812735-ad606000-1c83-11eb-9532-83002aa226cb.jpg)

## Debug info
Zigbee2MQTT version: 1.6
Adapter hardware: CC2531
Adapter firmware version: 1.2  19062019

**Comment by Koenkk** [comment]
Does this always happen? Right before doing this did you execute a lot of commands?
