### ISSUE TITLE
Position status when joining E1757 Fyrtur blind with repeater E1746

### ISSUE THREAD

**Issue by mattydanby** [Koenkk/zigbee2mqtt#4842]
## What happened
I don't receive position status when the E1757 Fyrtur blind is paired via the E1746 repeater and the interview message isn't reported in the beta web interface.

## What did you expect to happen
I would expect to see the blind position in the same way as when the blind is paired directly to the co-ordinator.

## How to reproduce it (minimal and precise)
If I join the blind (blind held next to co-ordinator, both buttons held until the light flashes, lights go out, then the light pulses whilst the interview messages are reported and light goes out) to the co-ordinator directly, I receive the position of the blind in homeassistant as expected.

However, if I perform a join first with the E1746 and then perform the blind join (blind held next to the repeater, both buttons held until the light flashes, lights go out, then the light pulses and then light goes out) via the repeater the position status isn't reported but I can move the blind with the slider.

Am I doing something wrong with the adapter joining process as the interview message isn't reported in the beta web interface but it works from a command perspective?

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC1352P-2
Adapter firmware version: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200925,"transportrev":2},"type":"zStack3x0"}'

Thanks

**Comment by pcurt** [comment]
I had the same problem.
To fix it update the E1746 firmware then pair again the E1757 Fyrtur next to the repeater
