### ISSUE TITLE
ELKO Smart RS16 Super TR RF PH - Thermostat

### ISSUE THREAD

**Issue by Gaute2000** [Koenkk/zigbee2mqtt#4856]
**ELKO Smart RS16 Super TR RF PH - Thermostat**

**Technical specifications:** 
_Voltage: 230 V/50-60 Hz.
Max load: 2300W
Electronic short circuit fuse
Temperature sensor: Airsensor, floorsensor or regulator (%)
Choose between different suppliers floorsensors
Simple and easy to use saving program.
Antifreeze function
Big display - adjustable brightness
Input for external control_

**devices.js**
{
        zigbeeModel: ['Super TR'],
        model: 'Super TR RF',
        vendor: 'ELKO',
        description: 'In-Wall Thermostat for floor heating',
        supports: 'Temperature sensor: Airsensor, floorsensor or regulator, Saving program, Child-lock',
        fromZigbee: [fz.thermostat_att_report, fz.thermostat_weekly_schedule_rsp, fz.hvac_user_interface],
        toZigbee: [
            tz.factory_reset, tz.thermostat_local_temperature, tz.thermostat_local_temperature_calibration,
            tz.thermostat_occupancy, tz.thermostat_occupied_heating_setpoint,
            tz.thermostat_temperature_display_mode, tz.thermostat_keypad_lockout,
            tz.thermostat_setpoint_raise_lower, tz.thermostat_remote_sensing,
            tz.thermostat_control_sequence_of_operation, tz.thermostat_system_mode, tz.thermostat_weekly_schedule,
            tz.thermostat_clear_weekly_schedule, tz.thermostat_relay_status_log,
            tz.thermostat_temperature_setpoint_hold, tz.thermostat_temperature_setpoint_hold_duration,
        ],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['hvacThermostat', 'genBasic', 'genIdentify']);
            await configureReporting.thermostatTemperature(endpoint);
            await configureReporting.thermostatSystemMode(endpoint);
            await configureReporting.thermostatOccupiedHeatingSetpoint(endpoint);
            await configureReporting.thermostatSystemMode(endpoint);
        },

This is what Im using now, I guess some of it could be removed. Since Im only able to see under "state" Last_seen, linkquality, local_temperature, occupied_heating setpoint, system_mode.
I have also linked to confirmed Vendor Specific attributes under information about the device, maybe someone that know how to do this programming to add the correct code to device.js

Followed: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html 

**Information about the device**
[Datasheet](https://proff.elko.no/getfile.php/13124139/produkter/doc/EKO05677/Datasheet4523433.pdf)
[Device product page](https://proff.elko.no/elko-smart-super-termostat/elko-smart-rs16-super-tr-rf-ph-article2621-2970.html)
[Vendor Specific attributes](https://github.com/prj84/com.Elko/blob/master/drivers/ESHSUPERTR/ST_Code/Elko%20Thermostat%20-%20Vendor%20Specific%20attributes.txt)
**Database**
[database.zip](https://github.com/Koenkk/zigbee2mqtt/files/5503997/database.zip)

**Comment by Gaute2000** [comment]
Please let me know, if its some logfiles or data I can provide to assist to make this device supported.
For information Im running bare-metal of zigbee2mqtt on a Pi4 with a Electrolama zig-a-zig-ah! (zzh!) stick with firmware CC26X2R1_20200925 installed.

**Comment by Gaute2000** [comment]
Still active and a open issue

**Comment by sluquet** [comment]
Would love to have this added :-)

**Comment by henrikrox** [comment]
Would also love this to be added

**Comment by henrikrox** [comment]
@Gaute2000 I tried your code in devices.js, but i get alot of 

ReferenceError: bind is not defined at Object.configure, it sees the device, but "something" is messed up. @Koenkk Will this device get added? Or is it something i can do.

**Comment by Koenkk** [comment]
Changing the content of `configure` to below should fix this:

```js
const endpoint = device.getEndpoint(1);
await reporting.bind(endpoint, coordinatorEndpoint, ['hvacThermostat', 'genBasic', 'genIdentify']);
await reporting.thermostatTemperature(endpoint);
await reporting.thermostatSystemMode(endpoint);
await reporting.thermostatOccupiedHeatingSetpoint(endpoint);
await reporting.thermostatSystemMode(endpoint);
```

**Comment by sluquet** [comment]
Did any of you get this to work? No luck here.
