### ISSUE TITLE
[recomendation] Zigbee switch that takes 230V and only reports state

### ISSUE THREAD

**Issue by opensourcerebel** [Koenkk/zigbee2mqtt#4857]
Hello, 

I was looking through: https://www.zigbee2mqtt.io/information/supported_devices.html to find a device that I can put behind an existing light switch that will only report the state of the switch but all that I find only control a small relay that turns the lamp on or off. Do you know of such addon device exists?

p.s.
the setup is this:
Old installation where the light switch directly turns the lamp on off.
Now I have a smart zigbee light that can be controlled with a zigbee remotely.
Problem: The old switch must be always on in order to keep power to the smart bulb.
Solution: I have hardwired the the cable from the lamp to always have power and I am using a Shelly1 (built in behind the switch) to push info about the switch state to a RaspberryPi and then on the RPi I have the zigbee stick that actually turns the lamp on and off (wallswitch->shelly1->Rpi->zigbee2mqtt->lamp). It works but the moment the wifi goes down the wall switches stop working. It would be way better to be able to make a group then put the lamp and the switch monitor in this group and have the wall switch device directly control the light.
Arch problem: I cannot find such device :) I hope someone more experienced than me can point me to such a device that can replace my shelly1 or tell me some trick one can do with one of the existing devices that support mounting behind the wall switch.

p.p.s.
If that is not the correct place to ask, please tell me where to repost?

Best Regards

**Comment by Koenkk** [comment]
Please use the forum or discord for this: https://www.zigbee2mqtt.io/#support
