### ISSUE TITLE
Wall switch Lonsonho X703A is recognized as Zemismart ZM-L03E-Z

### ISSUE THREAD

**Issue by szeryf85** [Koenkk/zigbee2mqtt#4858]
Hello,
I have four wall switches Lonsonho X703A (with neutral), and all of them are recognized as Zemismart ZM-L03E-Z.
The switches work fine, but although they are recognized as a router, no other device wants to connect to them. Could the problem be in the wrong identification of the switch?

Regards,
Lukas

**Comment by Koenkk** [comment]
These are actually the same device (both are whitelabel from TuYa). How Zigbee2MQTT recognises them doesn't affect the functionality, also Zigbee2MQTT control the routers a device use. Try to repair the device close to the desired router helps sometimes.

**Comment by klami85** [comment]
Same here, but all works fine (including router functionality).
Only photo is incorrect.
