### ISSUE TITLE
NeoCoolCam siren options not available in HA

### ISSUE THREAD

**Issue by Mecallie** [Koenkk/zigbee2mqtt#4881]
When I add the NeoCoolCam siren I see all the available options and it is recognized by z2m as far as I can tell.
However, in HomeAssistant I cannot change any option. Eg.: turn on the siren, set the melody or set the humidity alarm percentage.

I would like to be able to change the user configurable options via HomeAssistant. I am not sure, but I think this request might also be solved by [RFC] Exposing device capabilities #4466 ?

Device info (if you need more, other info let me know and how to find it):

ID: 0xec1bbdfffe6c1f48
Name: Temperature & humidity sensor and alarm (NAS-AB02B0)
door Neo 

Status attributes for "binary_sensor.ncc_sirene_alarm":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
friendly_name: NCC sirene_alarm
```

Status attributes for "binary_sensor.ncc_sirene_humidity_alarm":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
friendly_name: NCC sirene_humidity_alarm
```

Status attributes for "binary_sensor.ncc_sirene_temperature_alarm":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
friendly_name: NCC sirene_temperature_alarm
```
Status attributes for "sensor.ncc_sirene_humidity":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
unit_of_measurement: '%'
friendly_name: NCC sirene_humidity
device_class: humidity
```
Status attributes for "sensor.ncc_sirene_linkquality":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
unit_of_measurement: lqi
friendly_name: NCC sirene_linkquality
icon: 'mdi:signal'
```

Status attributes for "sensor.ncc_sirene_temperature":
```
alarm: true
humidity: 86
humidity_alarm: true
humidity_max: 80
humidity_min: 45
linkquality: 24
melody: 5
temperature: '20.2'
temperature_alarm: true
temperature_max: 27
temperature_min: 18
volume: high
unit_of_measurement: °C
friendly_name: NCC sirene_temperature
device_class: temperature
```

**Comment by Koenkk** [comment]
@kirovilya can you extend exposes with this? Then these options can be changed from the Zigbee2MQTT frontend.
