### ISSUE TITLE
New device: Ajax AJ_ZB30_GU10 RGB-CCT GU10 30 deg

### ISSUE THREAD

**Issue by ademobile** [Koenkk/zigbee2mqtt#4882]
Could you please add the following device as supported.

## Information about the device + link
https://www.ajaxonline.co.uk/product/zigbee-gu10-spotlight-bulb/

This is the 30 degree version

added to devices.js to enable support:

   {
        zigbeeModel: ['AJ_ZB30_GU10'],
        model: 'AJ_ZB30_GU10',
        vendor: 'Ajax Online',
        description: 'RGB-CCT GU10 30 deg',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    },

## data/database.db entry of the device
{"id":69,"type":"Router","ieeeAddr":"0x60a423fffe025003","nwkAddr":30173,"manufId":4098,"manufName":"Ajax online Ltd","powerSource":"Unknown","modelId":"AJ_ZB30_GU10","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"AJ_ZB30_GU10","manufacturerName":"Ajax online Ltd","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"","swBuildId":"V_0_1"}}},"binds":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"","swBuildId":"V_0_1","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1604335015966}

Not sure why power source is unknown

**Comment by Koenkk** [comment]
Added.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
