### ISSUE TITLE
Glodepto new device GL-C-008P

### ISSUE THREAD

**Issue by th0m3k** [Koenkk/zigbee2mqtt#4888]
Please help me out with adding new device
Glodepto  GL-C-008P

**Comment by wojciechczyz** [comment]
On 1.16.1 I am also still not getting it paired.
Seems upcoming 1.16.2 will fix this:
- GL-C-008P Gledopto Zigbee LED controller RGB + CCT pro model
https://github.com/Koenkk/zigbee2mqtt/releases

For now it was still not supported:
Zigbee2MQTT:warn  2020-12-01 21:44:28: Received message from unsupported device with Zigbee model 'GL-C-008P'
Zigbee2MQTT:warn  2020-12-01 21:44:28: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by Koenkk** [comment]
Supported in Zigbee2MQTT 1.16.2
