### ISSUE TITLE
Last update => Port '8485' is already in use by something else on the host

### ISSUE THREAD

**Issue by ABRT29** [Koenkk/zigbee2mqtt#4889]
Hello,

I have just corrected the update of zigbee2mqtt but cannot restart it displays the following error :
**Port '8485' is already in use by something else on the host.**

I didn't add anything more (add-on, plugin or other) to my system.

Thank you!

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC2531
Home Assistant version: 0.117.5

**Comment by sjorge** [comment]
You can try changing the port the frontend runs on to avoid the error.

**Comment by klumpler** [comment]
Same situation here. No other Home Assistant config change, just add-on update to 1.16.1 and suddenly unable to start it. Port '8485' is already in use by something else on the host.

**Comment by klumpler** [comment]
One more info - after update to HassOS 4.16 and full reboot, the problem dissapeared. Everything is running now... Strange.

**Comment by FaBRiK74** [comment]
Today morning the Z2M has stopped to work. When I wanted to restart, I got the same error that port 8485 is used by something else. But I didn't change anything in the morning.
What is the solution?

**Comment by Lesani** [comment]
and today, after updating to 2023.1.7 I get this message as well, I did not change anything apart from letting Homeassistant Core update and reboot

**Comment by ToMs77130** [comment]
Same for me, I've checked port with netstat but it doesn't seems to be used, despite the message.
I've changed port from 8485 to 8486 and z2m started again.

**Comment by kwint** [comment]
Same issue here, zigbee2mqtt seems to stop working randomly., and when I start it again I get this error

**Comment by Gandizzle91** [comment]
Same here.
After i changed the Port i dont get the Message anymore. But it still dont start without any error

**Comment by wojciechczyz** [comment]
Same problem with latest version upgrade

**Comment by squromiv** [comment]
After updating to Home Assistant Core 2023.5 got the same issue.

**Comment by satwiz-md** [comment]
me too I'm not a beta tester!!!!

**Comment by DanielNagy** [comment]
Also had this issue with trying to start z2m and nut server add ins. Seems a ha issue if you have exposed port configured in respective add in. 
To make zigbee2mqtt start, remove the 8485 configured exposed port in the addin config, and it will start.

**Comment by albertombl** [comment]
Same situation today. Z2m not working because the port 8485 is already been used. Is there any final solution to the problem or just remove 8485 from addon configuration ?

**Comment by BardaktakiAdam** [comment]
Same situation. I have updated the zigbee2mqtt, and it starts to Port '8485' is already in use by something else on the host

**Comment by FaBRiK74** [comment]
> same her, what ist the solution?

As above, just change the port to e.g. 8486
