### ISSUE TITLE
(Frontend) Link to the "supported devices" webpage on the "about" page of the frontend

### ISSUE THREAD

**Issue by grostim** [Koenkk/zigbee2mqtt#4892]
I think it would be great to have a link to the relevant devices page from zigbee2mqtt.io on the "about" page of each device.

Typically, on this page: 
<img width="1099" alt="Capture d’écran 2020-11-07 à 14 01 27" src="https://user-images.githubusercontent.com/3714755/98441934-de1c1b80-2101-11eb-95af-bac1fada630c.png">
I would like a link pointing towards this page:
https://www.zigbee2mqtt.io/devices/WXCJKG21LM.html

**Comment by Koenkk** [comment]
Feature requests for the frontend should be created here: https://github.com/nurikk/z2m-frontend/issues
