### ISSUE TITLE
Possible enhancement: battery statuses report

### ISSUE THREAD

**Issue by mr2c12** [Koenkk/zigbee2mqtt#4893]
Just an idea.
Could z2m expose on some topic a complete list of battery levels?
When dealing with a lot of devices, it can be used to get a very simple "report" of the remaining power in the battery powered devices. I could, in that case, avoid to create the required entities in Home Assistant (or equivalent system) and just run a periodic check on this topic.

Does it make sense?

**Comment by sjorge** [comment]
I’d you have the output thing (forgot the name) set to json_and_attributes you can subscribe in #/battery and you get all the last published battery values (assuming retain is set), not perfect but usable in the mean time.
