### ISSUE TITLE
Issue to recognize device: HGZB-01A

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#4897]
Hi

I don"t know why, but when I paired my HGZB-01A device, I got this line:

`zigbee2mqtt    | Zigbee2MQTT:warn  2020-11-07 19:49:26: Device '0x086bd7fffe3f3739' with Zigbee model 'LXN59-1S7LX1.0' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

Not sure to understand why it says: model 'LXN59-1S7LX1.0'.

What I'm supposed to do ? Add manually the device ? 

Is there an issue on Z2M to recognize the good device ? 

## Debug info
Zigbee2MQTT version: 1.15.0
Adapter hardware: CC1352P-2
Adapter firmware version: 20201026

Thank you in advance

Regards

**Comment by Koenkk** [comment]
This device has been addd in Zigbee2MQTT 1.16.0 so just update to the latest version.

**Comment by kevincaradant** [comment]
Ah yes you're right it works well in 1.16.1.

Thank you

**Comment by kevincaradant** [comment]
Hi

Just to know is it possible to fix the AC power issue and the icon (image) of the Switch which is wrong ?

I'm running with this one:
![image](https://user-images.githubusercontent.com/6093175/102083509-f6bfd580-3e13-11eb-9e83-8038d5310a9d.png)

And I have this under Z2M:
![image](https://user-images.githubusercontent.com/6093175/102083583-16ef9480-3e14-11eb-888d-d2c24f43f156.png)

**Comment by kevincaradant** [comment]
Alright Thanks :)

**Comment by Koenkk** [comment]
- Can you provide your zigbee2mqtt debug log?
- Can you provide the data/database.db entry of this device.

**Comment by kevincaradant** [comment]
Hi 

My apologies, not sure if it was because I just did a restart instead of down / up with my docker or because I pulled it a little bit too soon yesterday from the docker hub but today it's working fine ;)

**Comment by kevincaradant** [comment]
Hi

Finally I didn't notice but the picture is the generic picture of zigbee "Z" red but not really the device :)

Is it normal? 

![Screenshot_20201222-194343_Chrome](https://user-images.githubusercontent.com/6093175/102922392-40e92c80-448e-11eb-9957-b36451573dde.jpg)

**Comment by Koenkk** [comment]
Yes, https://github.com/Koenkk/zigbee2mqtt/issues/4897#issuecomment-744638206

> Picture will be fixed on new z2m release.
