### ISSUE TITLE
MQTT Command to restart z2m

### ISSUE THREAD

**Issue by svh1985** [Koenkk/zigbee2mqtt#4899]
## Is your feature request related to a problem? Please describe
Quite regularly I have one or two devices which are unresponsive. Even though I have a powerful zigbee stick (zzh). So, what I do to solve; is restarting the z2m bridge manually. 

## Describe the solution you'd like
Because I’m using HA, I could of course automate this. All that is missing, is a command to restart the bridge via mqtt. This way I could setup an automation.

An additional benefit is that this also makes restarting z2m somewhat easier.

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of the device being unresponsive?  (because that should not happen in the first place)

**Comment by svh1985** [comment]
You're right, once it happens again I will upload the log here.

But I do think it's nice to have a way to restart the bridge via an MQTT-command.
