### ISSUE TITLE
TRV TS0601_thermostat wrong temperature range

### ISSUE THREAD

**Issue by pedroke** [Koenkk/zigbee2mqtt#4910]
## What happened

Thermostatic radiator valve Moeshouse defined as TS0601_thermostat is presented with wrong range of target temperatures 5C - 30C. Although device itself can be set 5C - 35C.
I can see in devices.js for modelID: kud7u2l

exposes.climate().withSetpoint('current_heating_setpoint', 5, 30, 0.5).withLocalTemperature()

so this should be probably changed to:

exposes.climate().withSetpoint('current_heating_setpoint', 5, 35, 0.5).withLocalTemperature()

But I'm not sure if it was an intention or mistake. I have a valve with LCD display and blue backlight and it allows 5-35C.

## What did you expect to happen

I would expect the temperature range to match the device possibilities.

## How to reproduce it (minimal and precise)

pls. see above

## Debug info
Zigbee2MQTT version: all
Adapter hardware: all
Adapter firmware version: all

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
