### ISSUE TITLE
Moes BHT-002 spamming queue

### ISSUE THREAD

**Issue by Courty40** [Koenkk/zigbee2mqtt#4911]
## What happened
When in user the Moes BHT-002 thermostat doesn't send one message, it seems to send 30 in one go, all repeats of the last but with new message serial numbers

## What did you expect to happen
Single message every X seconds or on change

## How to reproduce it (minimal and precise)
Add Moes BHT-002 to ZIGBEE2MQTT, monitor the /# queue and change the temp. queue gets flooded with a chain of messages

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC26X2R1
Adapter firmware version: Latest (did same on CCCC2531 as well)

**Comment by 1300371** [comment]
Hello, you can use the `debounce` parameter like 
```
'0xfffffffffffffffffffffffffff':
  friendly_name: thermostat
  debounce: 1
```

See https://www.zigbee2mqtt.io/information/configuration.html#all-devices

**Comment by Courty40** [comment]
debounce: 1   defo helps a lot but concerned that it sends so much to the queue. reading up on it, it looks like a few other devices do this too. poor hardware/firmware design by the looks of it.
Thanks for the nudge in the right direction..

**Comment by 1300371** [comment]
Yes. It's a pity

**Comment by Falconpage** [comment]
Thanks for this tip, debounce: 1 solve my logs spam issue
