### ISSUE TITLE
Can't set temperature tuya smart valve from google home

### ISSUE THREAD

**Issue by ale1800** [Koenkk/zigbee2mqtt#4914]
Hi everyone. Received, added and updated TS0601 tuya smart valve in z2m and everything works just fine through lovelace and alexa but not with google home. Through Google Home app I can only see the current temperature of the valve but can't set any mode or temperature or turn on and off. Also with voice I can't do anything. I have the official google home and alexa integrations thanks to Nabucasa. What can i do?
Thank you everyone!

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC2531
Adapter firmware version:
![screen-thermostat](https://user-images.githubusercontent.com/53172176/98703521-de275000-237b-11eb-833c-7250ae6ec18a.jpg)

**Comment by StimpyMGS** [comment]
Have you synced your devices in Google home? Say "hey Google sync devices" and try again

**Comment by ale1800** [comment]
Sure, i can see trv from the app but i can't do anything

**Comment by scoofz** [comment]
I have the exact same problem and it's a shame since I bought the google nest hub mainly to contol temperature but the same problem happens even when connected without using z2m and connecting with a zigbee hub and the tuya smart app... I also noticed there was no other mode than eco ...

**Comment by ale1800** [comment]
I think a workaround can be creating a generic thermostat and linking It to the mqtt thermostat

**Comment by ale1800** [comment]
Ok i found the solution. Now i'm able to set temperature from google nest hub. you have to create a fake generic thermostat and with this custom component https://github.com/daenny/climate_group you can create a "group" labeled as climate. Now you can use this new group on google nest hub to control the thermostat. I only solved for temperature settings. Not for modes, I think it's quite difficult.
![photo5382232937384227178](https://user-images.githubusercontent.com/53172176/102010569-2bae2880-3d3f-11eb-954e-c04a616c884a.jpg)

**Comment by tiefenthaler** [comment]
Same here, I can properly add the device to google home. But I cannot set temperature or configure it within the google home app. Only the current status is displayed
