### ISSUE TITLE
IKEA E1744 legacy disable documentation contradiction

### ISSUE THREAD

**Issue by jurkstas** [Koenkk/zigbee2mqtt#4919]
## What happened
Documentation says both `legacy: false` and `legacy: true` disable the legacy integration.
## What did you expect to happen
Documentation to be consistent.
## How to reproduce it (minimal and precise)
Check IKEA E1744 documentation on https://www.zigbee2mqtt.io/devices/E1744.html#legacy-integration and https://www.zigbee2mqtt.io/devices/E1744.html#device-type-specific-configuration

**Comment by Koenkk** [comment]
Should be legacy: false, just fixed the docs. Thanks!
