### ISSUE TITLE
Nouvel adaptateur

### ISSUE THREAD

**Issue by AGOUDY** [Koenkk/zigbee2mqtt#4920]
## Information about the device + link
..

## data/database.db entry of the device
..
Bonjour,
très intéressé par le projet
serait-il possible d'utiliser un adaptateur pizigate (https://zigate.fr/produit/pizigate-v1-0/) à la place du CC2530 ou 31
Merci de votre assistance
Alain

**Comment by Koenkk** [comment]
Englisch only.
