### ISSUE TITLE
cc253x router firmware, source code

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#494]
Hi,

I'd like to be able to compile my router firmware myself, would it be possible to provide the changes, source and instructions ?
I guess it could be hosted by https://github.com/Koenkk/Z-Stack-firmware

Thanks in advance

**Comment by Koenkk** [comment]
I don't have the source code instructions. @ptvoinfo could you share this?

**Comment by leejaeuk** [comment]
This is what i want.

**Comment by lolorc** [comment]
That would be nice to compile a router with z-stack 3.0 as well, as far as I've understand it should be backward compatible.
