### ISSUE TITLE
zigbee2mqtt doesn't start

### ISSUE THREAD

**Issue by rzettler** [Koenkk/zigbee2mqtt#4940]
Hi all,
my zigbee2mqtt docker container usually just starts fine.
But as soon as I map the zigbee2mqtt-herdsman-converters (which I got via: git clone https://github.com/Koenkk/zigbee-herdsman-converters.git; cd zigbee-herdsman-converters, npm ci) into the container I get the following error:

zigbee2mqtt    | Using '/app/data' as data directory
zigbee2mqtt    |
zigbee2mqtt    | > zigbee2mqtt@1.16.1 start /app
zigbee2mqtt    | > node index.js
zigbee2mqtt    |
zigbee2mqtt    | assert.js:386
zigbee2mqtt    |     throw err;
zigbee2mqtt    |     ^
zigbee2mqtt    |
zigbee2mqtt    | AssertionError [ERR_ASSERTION]: 'TS0601_thermostat' has manual mapping and exposes
zigbee2mqtt    |     at HomeAssistant.populateMapping (/app/lib/extension/homeassistant.js:413:17)
zigbee2mqtt    |     at new HomeAssistant (/app/lib/extension/homeassistant.js:407:14)
zigbee2mqtt    |     at new Controller (/app/lib/controller.js:80:34)
zigbee2mqtt    |     at Object.<anonymous> (/app/index.js:25:20)
zigbee2mqtt    |     at Module._compile (internal/modules/cjs/loader.js:1015:30)
zigbee2mqtt    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
zigbee2mqtt    |     at Module.load (internal/modules/cjs/loader.js:879:32)
zigbee2mqtt    |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
zigbee2mqtt    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
zigbee2mqtt    |     at internal/main/run_main_module.js:17:47 {
zigbee2mqtt    |   generatedMessage: false,
zigbee2mqtt    |   code: 'ERR_ASSERTION',
zigbee2mqtt    |   actual: false,
zigbee2mqtt    |   expected: true,
zigbee2mqtt    |   operator: '=='
zigbee2mqtt    | }
zigbee2mqtt    | npm ERR! code ELIFECYCLE
zigbee2mqtt    | npm ERR! errno 1
zigbee2mqtt    | npm ERR! zigbee2mqtt@1.16.1 start: `node index.js`
zigbee2mqtt    | npm ERR! Exit status 1
zigbee2mqtt    | npm ERR!
zigbee2mqtt    | npm ERR! Failed at the zigbee2mqtt@1.16.1 start script.
zigbee2mqtt    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
zigbee2mqtt    |
zigbee2mqtt    | npm ERR! A complete log of this run can be found in:
zigbee2mqtt    | npm ERR!     /root/.npm/_logs/2020-11-11T12_47_42_423Z-debug.log
zigbee2mqtt exited with code 1

What is the problem?

**Comment by Koenkk** [comment]
You should use the latest dev branch of zigbee2mqtt, the latest zigbee-herdsman-converters version is not compatible with Zigbee2MQTT 1.16.1 but only with the latest dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
