### ISSUE TITLE
Custom Zigbee prototype using CC2531 and python

### ISSUE THREAD

**Issue by Shukk** [Koenkk/zigbee2mqtt#4967]
Hello,

We are currently working on a ZigBee ecosystem, and building a prototype.
Our ecosystem is composed of 2 CC2531 dongles : one coordinator and one router flashed with the firmwares recommended by the zigbee2mqtt doc. 
The coordinator works as follows: it is plugged in a raspberry pi 4 with zigbee2mqtt on it and we connected the router and a ZigBee occupancy sensor to it. 
The router is plugged in a linux machine.

We need to send data at least from the coordinator to the router and it would be good if we could send data in the other direction too.
We tried some ZigBee python library on the router side to send and receive data but unfortunately it didn't work.
On the coordinator side, we tried to send mqtt messages with the mosquitto_pub command by tweaking zigbee-herdsman-converters (toZigbee.js especially) ...without results except a buffer_not_available error.

Any ideas on how to implement our prototype using open source libraries, so we can send our custom data back and forth?

**Comment by andredebuisne** [comment]
I have a very similar problem, any help would be great! :)
