### ISSUE TITLE
Moes BHT-002 stops working with the latest edge

### ISSUE THREAD

**Issue by Falconpage** [Koenkk/zigbee2mqtt#4970]
Hi,

I tried today the latest edge build, it broked my BHT-002, "current_heating_setpoint" can't be interpreted by the converter (fromzigbee).

Roll back to the master build 1.16.1 fix the problem.

**Comment by Westcott1** [comment]
Does it work for non-integer values?
If I try to set to (say) 21.5, it actually sets to 0

**Comment by Falconpage** [comment]
No we need to set only vales like 20 21 22.
I didn't take time to have a look to the "tozigbee" commands.
