### ISSUE TITLE
Delete all my network ?

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#4971]
## Information about the device + link
..
Raspberry PI4 
29 devices Xiaomi and Heiman
Zigbee2mqtt master 1.16.1
## data/database.db entry of the device

Hello,

I just bought a Conbee2 key to replace my CC2531 key, I would like to destroy my network so that the devices match my new key and less on my routers, since it supports up to 100 devices maximum.

How to do ? With my CC2531 I just had to reflash it and manually re-pair all the devices (I have 29 from xiaomi and heiman).
Is there a command (i don't want destroying my database and my configuraiton.yaml so that my devices are orphaned?

Thank you

**Comment by Koenkk** [comment]
To switch you need to repair, do the following:

- Remove database.db
- Turn off existing Zigbee network by disconnecting all AC powered devices
- Start Zigbee2MQTT with Conbee II
- Pair all devices.
