### ISSUE TITLE
Supported Nordtronic 98425031 reporting new zigbee model

### ISSUE THREAD

**Issue by mmstw** [Koenkk/zigbee2mqtt#4977]
## Information about the device + link
Nordtronic 98425031 is already nominally supported by zigbee2mqtt ([https://www.zigbee2mqtt.io/devices/98423051.html](url)). However, it seems that new/some versions are reporting slightly diferent zigbee model:

    warn  2020-11-13 21:35:49: Device '0xec1bbdfffead2fd1' with Zigbee model 'BoxDIMZ 98425031' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Adding this model into the existing entry in `devices.js` as

            zigbeeModel: ['BoxDIM2 98425031', '98425031', 'BoxDIMZ 98425031'],

enables support for the new version as well. On/off and dimming work.

## data/database.db entry of the device
This is after modifying `devices.js`

    {"id":4,"type":"Router","ieeeAddr":"0xec1bbdfffead2fd1","nwkAddr":4584,"manufId":4107,"manufName":"Nordtronic A/S","powerSource":"Mains (single phase)","modelId":"BoxDIMZ 98425031","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"BoxDIMZ 98425031","manufacturerName":"Nordtronic A/S","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r49"}}},"binds":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r49","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1605296184971}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
