### ISSUE TITLE
TuYa TS0044 not support in 1.16 zigbee2mqtt

### ISSUE THREAD

**Issue by inhibitz** [Koenkk/zigbee2mqtt#4982]
can not pair the zigbee device https://www.zigbee2mqtt.io/devices/TS0044.html. although it is officially on the support list. there are not even logs. what could be the problem?

**Comment by martinUB** [comment]
Hey there,
same issue in my case. Can't get device to pair. I don't get any message from the switch in the home assistant zigbee2mqtt log.
If some further information is needed, just ask for it :) 
Looking forward for a solution.

**Comment by martinUB** [comment]
Hey inhibitz.
In my case it was a device independent issue. Try unplugging your coordinator, then plug it in again and after that restart the zigbee2mqtt or in my case complete home assistant. I was able to pair the device then. Check if join(all) is allowed.
Cheers
Martin

**Comment by tnijkes** [comment]
Same here.
Anyone got it working yet?
