### ISSUE TITLE
Internal converter is prioritized over external converter

### ISSUE THREAD

**Issue by xyzroe** [Koenkk/zigbee2mqtt#4990]
When connecting an external converter for a device with model ID for which there is already, 
an internal one in zigbee-herdsman-converters, the internal converter has priority over the external converter.

Repeats on both master and dev branches.

**Comment by Koenkk** [comment]
Redefinition of a device is indeed not possible currently.

**Comment by xyzroe** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/1821
