### ISSUE TITLE
Aqara b1 hand_open option not onby default, json error.

### ISSUE THREAD

**Issue by Dennisd80** [Koenkk/zigbee2mqtt#4997]
## What happened:  Aqara b1curtain doesn't open by hand, therefor i've made and automation,(home assistant but with this automation it says: ERROR: Invalid JSON '{ 'options': { 'hand_open': true } }', skipping...

automation 
`- alias: handmatig gordijen
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Gordijnen Jayden Zolder/set
      payload: '{ ''options'': { ''hand_open'': true } }'`

## Debug info
Zigbee2MQTT version: Latest dev  1.16.1-dev
Adapter hardware: CC2531
Adapter firmware version:

**Comment by Koenkk** [comment]
Instead of `''` use `"`.

**Comment by Dennisd80** [comment]
Your the best
