### ISSUE TITLE
CC2530: displayed wrong firmware build in zigbee2mqtt-GUI

### ISSUE THREAD

**Issue by Maik-100** [Koenkk/zigbee2mqtt#5006]
Hi,
I opened an issue because in the GUI of Zigbee2MQTT is displayed the wrong firmeware build date.

see: nurikk/z2m-frontend#140

Please check source code of firmware of CC2530.

**Comment by Koenkk** [comment]
I think the firmware build date was not updated, @ptvoinfo is it indeed set to 2018-09-26?

**Comment by ptvoinfo** [comment]
@Koenkk yes, I forgot to update the date. We can ignore this. I'll update it on the next version.

**Comment by Koenkk** [comment]
@ptvoinfo thanks, closing this because the shown firmware data is correct

**Comment by Maik-100** [comment]
Thanks, but this issue is present on the router firmware for the CC2531, 
too.

So please update and check the firmware data before you publish a new 
firmware version, it is very easy to check.
This helps to reduce misunderstandings and improves quality of the firmware.

Am 18.11.2020 um 15:20 schrieb Koen Kanters:
