### ISSUE TITLE
Paul Neuhaus lamp does not support 'red' color

### ISSUE THREAD

**Issue by redahb** [Koenkk/zigbee2mqtt#5011]
## Device information:
Description: Various RGBW lights (e.g. 100.110.39)
Firmware build date: 20150821
Firmware version: 1001-0007
Vendor: Paul Neuhaus
Model: NLG-RGBW light 

## What happened:
When I select 'red' as color in HA or if I send color_name: red as a service, the lamp does not respond. Other lamps (Hue, Osram) do respond to the red color just fine. Also, this lamp responds to colors like 'blue' and 'green' just fine. I have 5 of these expensive lamps, and they all act the same.

## What did you expect to happen:
The lamp would turn red.

## How to reproduce it (minimal and precise):
Send color_name: 'red' or send x: 0.701 & 'y': 0.299. This does not do antything on the lamp. Sending x: 0.68 & 'y': 0.301 does make the lamp change to some shade very close to red, possibly even actual red.

## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC2652RB
Adapter firmware version: 20201026

## Debug Log
```
Zigbee2MQTT:debug 2020-11-19 10:54:55: Received MQTT message on 'zigbee2mqtt/lamp_gang_beneden_spiegel/set' with data '{"state": "ON", "color": {"x": 0.701, "y": 0.299}}'
Zigbee2MQTT:debug 2020-11-19 10:54:55: Skipping state because of Home Assistant
Zigbee2MQTT:debug 2020-11-19 10:54:55: Publishing 'set' 'color' to 'lamp_gang_beneden_spiegel'
Zigbee2MQTT:info  2020-11-19 10:54:55: MQTT publish: topic 'zigbee2mqtt/lamp_gang_beneden_spiegel', payload '{"brightness":254,"color":{"x":0.701,"y":0.299},"color_temp":37,"linkquality":69,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-19 10:55:14: Received Zigbee message from 'lamp_gang_beneden_spiegel', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":2,"imageType":4624,"manufacturerCode":4151}' from endpoint 2 with groupID 0

Zigbee2MQTT:debug 2020-11-19 10:55:18: Received MQTT message on 'zigbee2mqtt/lamp_gang_beneden_spiegel/set' with data '{"state": "ON", "color": {"x": 0.68, "y": 0.301}}'
Zigbee2MQTT:debug 2020-11-19 10:55:18: Skipping state because of Home Assistant
Zigbee2MQTT:debug 2020-11-19 10:55:18: Publishing 'set' 'color' to 'lamp_gang_beneden_spiegel'
Zigbee2MQTT:info  2020-11-19 10:55:18: MQTT publish: topic 'zigbee2mqtt/lamp_gang_beneden_spiegel', payload '{"brightness":254,"color":{"x":0.68,"y":0.301},"color_temp":193,"linkquality":72,"state":"ON"}'
```

## Other remarks
Is this something that can/should be fixed in zigbee2mqtt (because I highly doubt the manufacturer will ever release new firmware, they're not big enough as a smart home player), or should I fix this by using a hue_correction map? I'm not sure that would work because all the other colors render just fine, only red doesn't.

**Comment by Koenkk** [comment]
Can you check if adding `meta: {applyRedFix: true},` to the device definition fixes this problem? Example: https://github.com/Koenkk/zigbee-herdsman-converters/blob/6df75aaa15adfa9adaa24e85898a3813fe095a12/devices.js#L5543

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to modify devices.js
