### ISSUE TITLE
Xiaomi Aqara Opple WXCJKG13LM only button_X_single

### ISSUE THREAD

**Issue by leranp** [Koenkk/zigbee2mqtt#5037]
## What happened
The remote only gives button_X_single , and hold for buttons 3-6
The same problem like in this issue:
https://github.com/Koenkk/zigbee2mqtt/issues/2884

## What did you expect to happen
Triple, double click for all the buttons
## Debug info
Zigbee2MQTT version: 1.16.1
Adapter hardware: CC2531
Adapter firmware version:

**Comment by niqu1982** [comment]
Try to push single, dual and hold action if no reset to default, pair, wekup and send configure from Z2M

**Comment by leranp** [comment]
> Try to push single, dual and hold action then restart HA if no reset to default, pair, wekup and send configure from Z2M

Thanks, repair worked

**Comment by kiclaw** [comment]
> 
> 
> Try to push single, dual and hold action then restart HA if no reset to default, pair, wekup and send configure from Z2M

Could you please specify this operation? I can't get it. I need to restart while button pressed?

**Comment by niqu1982** [comment]
after press all buttons and actions try restart HA
