### ISSUE TITLE
Neo zigbee siren causes UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by lenemeth** [Koenkk/zigbee2mqtt#5038]
# Bug Report
## What happened

Several minutes after adding NAS-AB02B0 - Neo Temperature & humidity sensor and alarm device to the network zigbee2mqtt start throwing the following messages in an endless loop (rejection id is being incremented):

`
Zigbee2MQTT:info  2020-11-21 12:54:29: MQTT publish: topic 'zigbee2mqtt/siren/livingroom-0x842e14fffedb8556', payload '{"alarm":false,"humidity":41,"humidity_alarm":false,"humidity_max":99,"humidity_min":1,"linkquality":39,"melody":8,"temperature":"18.0","temperature_alarm":false,"temperature_max":27,"temperature_min":-1,"volume":"high"}'
(node:16) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
`

Other devices were not able to communicate with the zigbee2mqtt: once I've added this Neo siren then all other devices stopped sending updates.

I've removed the device from the network and also I had to restart raspberry pi entirely. Docker restart didn't solve the issue. 

## How to reproduce it (minimal and precise)

Simply connect a Neo siren to the network

## Debug Info
Zigbee2MQTT version: 1.16.1 (commit #6b32f30) 
Adapter hardware: CC2531
Adapter firmware version: {"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'

**Comment by Koenkk** [comment]
Looks like your coordinator crashed, I recommend switching to the source routing firmware which provides more stability: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing
