### ISSUE TITLE
adding QS-Zigbee-D02-TRIAC-LN and LXN59-2S7LX1.0

### ISSUE THREAD

**Issue by jefdemas** [Koenkk/zigbee2mqtt#5039]
Hi, 

the two devices are recognized bij the zigbee2mqtt
but doesn't show up in de device list in domoticz.

Where do i have to look?

regards

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment]
They probably have to be added to the domoticz-zigbee2mqtt-plugin, create an issue here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
