### ISSUE TITLE
Tuya smart Dimmer Switch Touch integration in zigbee2mqtt

### ISSUE THREAD

**Issue by jordibadiag** [Koenkk/zigbee2mqtt#5045]
Hi, I'm trying to integrate a new tuya dimmer buyed in aliexpress, but zibbee2mqtt seems that not support it. this is the device:
https://es.aliexpress.com/item/1005001505847911.html?spm=a2g0s.9042311.0.0.2d4a63c08XojPn

This is what I get in my zigbee2mqtt log:

## Information about the device + link
Zigbee2MQTT:info  2020-11-21 22:50:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0xbc33acfffef4cdc7"},"type":"device_announced"}'
Zigbee2MQTT:warn  2020-11-21 22:50:21: Received message from unsupported device with Zigbee model 'TS0601'

And this is what I have in my dd file, last device:

## data/database.db entry of the device
{"id":26,"type":"Router","ieeeAddr":"0xbc33acfffef4cdc7","nwkAddr":33218,"manufId":4098,"manufName":"_TZE200_9i9dt8is","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_9i9dt8is","powerSource":1,"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"meta":{}}},"appVersion":64,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1605992160565}

Is there any way to integrate it? I will be very gratefull
Thans so much!
Jordi

**Comment by Koenkk** [comment]
This device is already supported in the latest dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
