### ISSUE TITLE
Log directory 

### ISSUE THREAD

**Issue by ster1um** [Koenkk/zigbee2mqtt#5062]
## What happened
change log directory

## What did you expect to happen
change log directory to tmp

## How to reproduce it (minimal and precise)
ever

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version: 1.2
OS: debian > home assistant on docker

I try to change the location of directory of log via config and sylink without success.
Do you have any suggestions?

**Comment by Koenkk** [comment]
See `log_directory` option https://www.zigbee2mqtt.io/information/configuration.html
