### ISSUE TITLE
Automatic edge build trigger for `zigbee2mqtt/hassio-zigbee2mqtt`

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt#5065]
## Is your feature request related to a problem? Please describe
Automatic edge build trigger for `zigbee2mqtt/hassio-zigbee2mqtt` when dev gets updated. 

## Describe the solution you'd like
Automatic edge build trigger for `zigbee2mqtt/hassio-zigbee2mqtt` when dev gets updated. Similar to:
```
    - name: Trigger danielwelch/hassio-zigbee2mqtt build
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      run: |
        curl -s \
          --request POST \
          --header "Content-Type: application/json" \
          --data '{"definition": {"id": 1}}' \
          -u ${{ secrets.HASSIO_TRIGGER_SECRET }} \
          "https://dev.azure.com/danielwelch2101/hassio-zigbee2mqtt/_apis/build/builds?api-version=5.1"
```

Discussed with @danielwelch as well that we will try migration to the new org for the repo.

Update 1: Pipeline link: https://dev.azure.com/zigbee2mqtt/Zigbee2mqtt%20Add-on/_build
Update 2: Edge specific pipeline link: https://dev.azure.com/zigbee2mqtt/Zigbee2mqtt%20Add-on/_build?definitionId=9

**Comment by Koenkk** [comment]
Can you make a PR for https://github.com/Koenkk/zigbee2mqtt/blob/4978d09eb1e18bf7e83a15e8087b2fe226e069bd/.github/workflows/ci.yml#L71 ? Note that you need to give me admin access to the azure pipeline.

**Comment by ciotlosm** [comment]
@Koenkk you should be a member of that org and have admin access. I will double check and make a PR. I'm a bit unsure on the API URL, but I will try.

**Comment by ciotlosm** [comment]
I've checked access and I think it should be there:
![Screenshot 2020-11-23 at 21 55 02](https://user-images.githubusercontent.com/7738048/100008815-991d0800-2dd6-11eb-8e59-8f66cb427e20.png)
