### ISSUE TITLE
Problem after upgrade - Sensor get "lost"

### ISSUE THREAD

**Issue by inode-** [Koenkk/zigbee2mqtt#5070]
Yesterday after 1 year of perfect functioning I decided to update zigbee2mqtt. Everything has always worked out well.

The update took some time (about 2 hours) and I changed some parts of the system as well. From then on I started having problems. When the system came back "online" the devices (mainly Aqara thermometers) did not resume transmitting. The only way I found was to re-bind.

Last night the system crashed again and now I find myself in the same situation, the devices transmit only after having re-associated them. Is there no way to "wake up" the devices that have not seen the router for a while?

Is this normal behavior or can it be caused by something?

When I do the binding again I get:
`Nov 24 12:41:25 radio npm[1053]: Zigbee2MQTT:info  2020-11-24 12:41:25: MQTT publish: topic 'myhome/zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00158d0004086348"},"type":"device_announced"}'`

and then the device start working again.

Thank you

**Comment by joonas-fi** [comment]
I have the same issue with version `1.16.1`:

- Added a device, it transmits data
- Confirm the device is added in `configuration.yaml`
- Docker stop
- Docker start
- Zigbee2mqtt starts with `Currently 0 devices are joined` message and the sensor's data does not appear in zigbee2mqtt anymore before I re-join it
