### ISSUE TITLE
Power plug Immax Neo started to report current and voltage entities which are not supported.

### ISSUE THREAD

**Issue by daha76** [Koenkk/zigbee2mqtt#5072]
## What happened
Power plug Immax Neo started to report current and voltage entities, but obviously this power plug does not support it. Values are always 0. I tried to delete the plug from ZigBee network and pair it back, but even than the current and voltage is reported. Reconfigure didn't help either.

## What did you expect to happen
Not supported attributes are not reported.

## Debug info
Zigbee2MQTT version: Zigbee2MQTT 1.16.1
Adapter hardware: CC2531
Adapter firmware version:

**Comment by Koenkk** [comment]
According to @hanzz it works for some: https://github.com/Koenkk/zigbee-herdsman-converters/pull/1002

**Comment by salopette** [comment]
with me the values are not there either.

![sshot-3](https://user-images.githubusercontent.com/32480002/100144289-df39a080-2e96-11eb-84d5-e79ad80cda69.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/100144291-dfd23700-2e96-11eb-82bd-0afaf12330f6.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/100144292-e06acd80-2e96-11eb-9653-2c3a4596a1af.jpg)

**Comment by daha76** [comment]
> According to @hanzz it works for some: [Koenkk/zigbee-herdsman-converters#1002](https://github.com/Koenkk/zigbee-herdsman-converters/pull/1002)

The discussion there is about power measurement in Watts. This works for me, but for some reason zigbee2mqtt started to report also AC Voltage and Current which seems to be not supported.

**Comment by sheppi72** [comment]
Same for me, only the power value reported.

```
Firmware build date   20190709-164
Firmware version      2.0
Vendor                Immax
Model                 07048L
```

**Comment by salopette** [comment]
.db

`{"id":31,"type":"Router","ieeeAddr":"0xccccccfffeeaae60","nwkAddr":62832,"manufId":4151,"manufName":"Immax","powerSource":"Mains (single phase)","modelId":"Plug-230V-ZB3.0","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,4,5,6,1794,2820,64642],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"Plug-230V-ZB3.0","manufacturerName":"Immax","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20190709-164","swBuildId":"2.0"}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca168ea","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca168ea","endpointID":1}],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":2,"hwVersion":1,"dateCode":"20190709-164","swBuildId":"2.0","zclVersion":3,"interviewCompleted":true,"meta":{"configured":9},"lastSeen":1609221249507}
`

**Comment by salopette** [comment]
DEBUG: Received Zigbee message from 'Baum Licht', type 'read', cluster 'genTime', data '["time"]' from endpoint 1 with groupID 0
DEBUG: Received MQTT message on 'zigbee2mqtt/Baum Licht/set' with data '{"state":"ON"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:26.975Z","linkquality":75,"power":0,"state":"ON"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:26.983Z","linkquality":78,"power":0,"state":"ON"}'
DEBUG: Received Zigbee message from 'Baum Licht', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":3}' from endpoint 1 with groupID 0
DEBUG: Received Zigbee message from 'Baum Licht', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7}' from endpoint 1 with groupID 0
DEBUG: Received MQTT message on 'zigbee2mqtt/Baum Licht/set' with data '{"state":"OFF"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:42.945Z","linkquality":75,"power":7,"state":"OFF"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:42.951Z","linkquality":75,"power":7,"state":"OFF"}'
DEBUG: Received Zigbee message from 'Baum Licht', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0
DEBUG: Received MQTT message on 'zigbee2mqtt/Baum Licht/set' with data '{"state":"ON"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:50.833Z","linkquality":75,"power":0,"state":"ON"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Baum Licht', payload '{"last_seen":"2020-12-29T06:24:50.839Z","linkquality":72,"power":0,"state":"ON"}'
DEBUG: Received MQTT message on 'zigbee2mqtt/Baum Licht/get' with data '{"power":""}'
DEBUG: Received Zigbee message from 'Baum Licht', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":3}' from endpoint 1 with groupID 0
DEBUG: Received Zigbee message from 'Baum Licht', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":7}' from endpoint 1 with groupID 0

**Comment by Koenkk** [comment]
@hanzz can you confirm that your plug supports current and voltage reportings? And if so share your data/database.db entry here?

**Comment by salopette** [comment]
please do not close, it is not repaired!

**Comment by daha76** [comment]
I just ignore those values.

**Comment by Koenkk** [comment]
Since I did get no response on https://github.com/Koenkk/zigbee2mqtt/issues/5072#issuecomment-752020610 I've removed them.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
