### ISSUE TITLE
Xiaomi vibration DJT11LM, reset strength after time without vibration

### ISSUE THREAD

**Issue by MiguelAngelLV** [Koenkk/zigbee2mqtt#5076]
## Is your feature request related to a problem? Please describe
I have a DJT11LM and, after vibration, the strength retain the value "forever" instead become in 0 after X minutes without any vibration.
## Describe the solution you'd like
The strength if send each 300 seconds ( 5 mins). But, if the device is not touched, the last strength is remain forever... Maybe can reset after 600 seconds (arbitrary) without any action or change value.

**Comment by markheloking** [comment]
I would also like to see this feature implemented, as this would make using the device states much more usefull/easy to work with in automation systems.
