### ISSUE TITLE
Unresponsiveness, unreliability and broken network 

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#5083]
# Bug Report
## What happened
I have a testing network in a different place where I've tested all my zigbee devices and they work perfectly.
Most of the devices are within a group and I have several actuators bound to those groups.

However, I've moved to a new house where I've connected all the ZigBee at once, and..., then the errors came.
When zigbee2mqtt is not connected I can use all of the remotes bound to groups and the response is great.
However, once I start zigbee2mqtt problems start to arise.
Bindings start to fail, the work randomly (not always) and very laggy.
Zigbee network seems to be VERY slow. It takes sometimes a few seconds to deliver a command. Sometimes it just timeout (10000ms timeout according to logs), and also I get same 'no network route'.

Devices appear and disappear randomly. 

So..., in summary, when I start Zigbee2Mqtt:
- Network unreliability.
- Very laggy.
- Works randomly.
- Lots of timeouts.
- "Breaks" bindings.
- No network routes.

When I finish Zigbee2Mqtt, bindings start working fine again.

I have several devices (around 30) from different brands, but currently I was only connecting (basically) from two different companies:
- Gledopto (all of them connected).
- Legrand (most of them connected, so I assume router as well, and some actuators).

I've tried disconnecting all of the Gledopto devices, but it still fails even less devices are connected.

Network mesh doesn't seem to work.

I'm on default channel (11). 

I've also tried disabling reporting (https://www.zigbee2mqtt.io/information/report.html) and seems (not really sure) to improve "a little bit". But nothing magical at all.

## What did you expect to happen
Work fine.

## How to reproduce it (minimal and precise)
???

## Debug Info
Zigbee2mqtt version: 1.16.1
Adapter hardware: CC26X2R1
Adapter firmware version: CC26X2R1_20200417

**Comment by jd1900** [comment]
I've updated the firmware version to the latest one (CC26X2R1_20201026) and still no changes.

I've also looked into the frequency interferences, and the channel seems to be fine:
![image](https://user-images.githubusercontent.com/63632981/100358556-9e589d80-2ff6-11eb-999e-761787b05319.png)
![image](https://user-images.githubusercontent.com/63632981/100358565-a31d5180-2ff6-11eb-9cbc-15ddab022e05.png)

![image](https://user-images.githubusercontent.com/63632981/100358580-a9133280-2ff6-11eb-8dd1-5972bd8c729c.png)
![image](https://user-images.githubusercontent.com/63632981/100358596-afa1aa00-2ff6-11eb-829c-563642d92b9b.png)

Any help of how to have a reliable network?
Once I start Zigbee2Mqtt everything is a nightmare and nothing works.

**Comment by Koenkk** [comment]
Actually your channel is not great at all, zigbee channel != wifi channel, wifi channel 1 interferes a lot with zigbee channel 11, see: https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html . Try with channel 25 (note changing channel requires repairing everything)

I also recommend switching to https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin because it increases the transmit power.

**Comment by jd1900** [comment]
Thank you. I'll try that.

If I switch back to the old channel, will I still keep already paired devices paired?

**Comment by Koenkk** [comment]
No, once you switch channel everything is cleared.

**Comment by jd1900** [comment]
Thank you again.

Two more questions:
- Why channel 25 and not channel 26? Channel 26 should be "clearer", right?
- Why when the coordinator and Zigbee2mqtt is not up, everything works smoothly? I have a group with 7 devices, all around the house (for the shutter), and they all works smoothly. When the coordinator is up, it doesn't work. Why is that? 
When a device is not connected to the coordinator, does it use a different channel?
Or just it routes differently? 
I don't fully get why it works fine without coordinator and just binding, but everything fails when the coordinator is up.

**Comment by Koenkk** [comment]
- Some devices might not work on channel 26
- I also don't understand why this does not work (there should be no difference)

**Comment by jd1900** [comment]
Thank you.

After changing the channel to 25, I had to go back due to incompatibilities with Legrand devices and a channel different from 11.
But changing to that firmware got me a little bit of better coverage. I've bough an ZZH and I hope that with the antenna I can have a better user experience.
