### ISSUE TITLE
support for Melinera Smart Led String lights (sold by LIDL).

### ISSUE THREAD

**Issue by Ruftie** [Koenkk/zigbee2mqtt#5089]
Device is reconsigned as TS0601 and no further actions are possible. 

https://www.lidl.nl/nl/p/smart-home/200-rgb-led-verlichtingsketting/p43246

    Manufacturer: _TZE200_s8gkrkxk
    Model identifier: TS0601
    Device type : Light

**Comment by Koenkk** [comment]
Just merged: https://github.com/Koenkk/zigbee-herdsman-converters/pull/1799

Changes will be available in the latest dev branch tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Ruftie** [comment]
thanks will update to dev tomorrow.

**Comment by Ruftie** [comment]
updated to dev still the same problem.

**Comment by meisterfuu** [comment]
Was just testing this on dev. Unsupported device. Does it still take some time, or do you need some more information?

**Comment by Ruftie** [comment]
in domoticz it is visible but cant do anything with the device.
![afbeelding](https://user-images.githubusercontent.com/60474547/100447706-5b0f3500-30b1-11eb-8813-3460655b59b3.png)

**Comment by meisterfuu** [comment]
After pairing it again a few times it seems to get recognised correctly.

**Comment by Ruftie** [comment]
> 
> 
> After pairing it again a few times it seems to get recognised correctly.

will try that to.

**Comment by meisterfuu** [comment]
Works perfectly well. Can control it through the new zigbee2mqtt web ui.

**Comment by Ruftie** [comment]
> 
> 
> Works perfectly well now. Can control it through the new zigbee2mqtt web ui.
New webgui? picture?

**Comment by meisterfuu** [comment]
https://www.zigbee2mqtt.io/information/frontend.html

**Comment by Ruftie** [comment]
Loading devices takes too long time. 

error...

**Comment by Ruftie** [comment]
got it to work with the zigbee2mqtt web UI, next job is to get the effects working and make switches in Domoticz.
