### ISSUE TITLE
Incorrect ext_pan_id works for current process lifecycle but after z2m restart devices stop communicating

### ISSUE THREAD

**Issue by joonas-fi** [Koenkk/zigbee2mqtt#5090]
## What happened

I had configured too long, incorrect `ext_pan_id` (16 bytes instead of 8)

Sensor joins network and sends data successfully, but after restart of zigbee2mqtt communication with sensor stops and its entry is removed from `database.db`.

More info on other issue's comment: https://github.com/Koenkk/zigbee2mqtt/issues/5070#issuecomment-734253908

## What did you expect to happen

Z2m to yell at me for giving incorrect `ext_pan_id` OR (less good option) communication to keep working after z2m restart.

## How to reproduce it (minimal and precise)

- Specify incorrect `ext_pan_id` (16 bytes instead of 8)
- Start z2m
- Join device, see that it works and sends data
- Restart z2m
- Doesn't work anymore

More info on other issue's comment: https://github.com/Koenkk/zigbee2mqtt/issues/5070#issuecomment-734253908

## Debug info

Zigbee2MQTT version: 1.16.1
Adapter hardware: CC2531
Adapter firmware version: 20190223

## Suggested fix

Validate all important parameters, including `ext_pan_id`, and stop if user supplied incorrect data.

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
