### ISSUE TITLE
Device not supported, but there is support for it in devices.js

### ISSUE THREAD

**Issue by AlexThePotter** [Koenkk/zigbee2mqtt#5092]
# Bug Report
## What happened
Using the home assistant integration v1.6.0 -  tried to connect new device (hive TRV) i get the following error:
```
zigbee2mqtt:debug 11/26/2020, 6:30:18 PM Received zigbee message of type 'endDeviceAnnce' with data '"0x842e14fffe269a11"' of device 'TRV001' (0x842e14fffe269a11) of endpoint 1
  zigbee2mqtt:warn 11/26/2020, 6:30:18 PM Device with modelID 'TRV001' is not supported.
  zigbee2mqtt:warn 11/26/2020, 6:30:18 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```
## What did you expect to happen
I've checked the devices.js online, there is an entry for this device. Though the model number doesn't seem to be present on my device. I tried adding it to a device.js file under /share/zigbee2mqtt/ and setting the appropriate config flag but that didn't seem to work either 
## How to reproduce it (minimal and precise)
pair hive trv001 to stick 
## Debug Info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
> Using the home assistant integration v1.6.0 

Make sure you are on the latest zigbee2mqtt (1.16.1)
