### ISSUE TITLE
Support for SilverCrest/Lidl Smart extension lead (with USB)

### ISSUE THREAD

**Issue by lvefferen** [Koenkk/zigbee2mqtt#5097]
## Information about the device + link
The device is sold as SilverCrest/Lidl Smart extension lead (with USB), its a zigbee 3.0 device. the device already pairs with Z2M as a TuYa TS011F device only it only exposes the first (of 3) outlet sockets. an adition to devices.js must be made:

// Silvercrest
    {
        fingerprint: [
            {modelID: 'TS011F', manufacturerName: '_TZ3000_wzauvbcs'},
            {modelID: 'TS011F', manufacturerName: '_TZ3000_1obwwnmq'},
        ],
        model: 'SPSZ 3 A1',
        vendor: 'Silvercrest',
        description: '3 gang switch, possibly with USB',
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3')],
        extend: generic.switch,
        meta: {configureKey: 1, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint) => {
            for (const ID of [1, 2, 3]) {
                await bind(device.getEndpoint(ID), coordinatorEndpoint, ['genOnOff']);
            }
        },
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3};
        },
    },

https://community.home-assistant.io/t/silvercrest-lidl-smarthome/243561/64

## data/database.db entry of the device
{"id":48,"type":"Router","ieeeAddr":"0xec1bbdfffea811b4","nwkAddr":28060,"manufId":4098,"manufName":"_TZ3000_1obwwnmq","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242,3],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_1obwwnmq","powerSource":1,"zclVersion":3,"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[3,4,5,6],"outClusterList":[],"clusters":{},"binds":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":266,"inClusterList":[3,4,5,6],"outClusterList":[],"clusters":{},"binds":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"meta":{}}},"appVersion":69,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1606468148406}

**Comment by Koenkk** [comment]
This change is already in the latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
