### ISSUE TITLE
Zigbee2MQTT on a unsupported Zigbee Adapter

### ISSUE THREAD

**Issue by mcatinoto** [Koenkk/zigbee2mqtt#5105]
# Bug Report
using Zigbee2MQTT on a new unsupported adapter
## What happened
I would write a new firmware for a device that should be compatible with zigbee2mqtt, is there any guideline to write it?
I think that zigbee2mqtt require some input by my device through the TTY interface, is there any template or input format?

## Debug Info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

**Comment by Koenkk** [comment]
There are 2 options here:
- If the adapter has no interface yet implement the zStack firmware interface, docs: https://github.com/Koenkk/zigbee-herdsman/blob/master/docs/Z-Stack%20Monitor%20and%20Test%20API.pdf
- Create a new interface implementing https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts
