### ISSUE TITLE
Securifi Zigbee Motion Sensor

### ISSUE THREAD

**Issue by ben423423n32j14e** [Koenkk/zigbee2mqtt#511]
A nice looking motion sensor this one, I've ordered a unit, should be delivered in a couple of weeks.

https://www.amazon.com/gp/product/B00TBXG0TW

CR123A battery should have good life expectancy.

**Comment by pleasanthill17** [comment]
Did you get this working ?

**Comment by ben423423n32j14e** [comment]
@pleasanthill17 It's still shipping to Australia, should be here end of this week.

**Comment by ben423423n32j14e** [comment]
@Koenkk @tb-killa I now have this motion sensor, need some assistance adding it:

1) Joining debug log:

`  zigbee2mqtt:debug 2018-11-10 15:33:16 Received zigbee message of type 'devInterview' with data '"0x000d6f000ab51414"'
  zigbee2mqtt:debug 2018-11-10 15:33:17 Received zigbee message of type 'devInterview' with data '"0x000d6f000ab51414"'
  zigbee2mqtt:debug 2018-11-10 15:33:17 Received zigbee message of type 'devInterview' with data '"0x000d6f000ab51414"'
  zigbee2mqtt:debug 2018-11-10 15:33:18 Received zigbee message of type 'devInterview' with data '"0x000d6f000ab51414"'
  zigbee2mqtt:debug 2018-11-10 15:33:19 Received zigbee message of type 'devInterview' with data '"0x000d6f000ab51414"'
  zigbee2mqtt:debug 2018-11-10 15:33:19 Received zigbee message of type 'devIncoming' with data '"0x000d6f000ab51414"' of device 'SZ-PIR02_SF' (0x000d6f000ab51414)
  zigbee2mqtt:info 2018-11-10 15:33:19 Device incoming...
  zigbee2mqtt:info 2018-11-10 15:33:19 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:debug 2018-11-10 15:33:19 Received zigbee message of type 'devStatus' with data '"online"' of device 'SZ-PIR02_SF' (0x000d6f000ab51414)
  zigbee2mqtt:warn 2018-11-10 15:33:20 Device with modelID 'SZ-PIR02_SF' is not supported.
  zigbee2mqtt:warn 2018-11-10 15:33:20 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices`

2) devices.js entry:
`    // Securifi
    {
        zigbeeModel: ['SZ-PIR02_SF'],
        model: 'SZ-PIR02',
        vendor: 'Iris',
        description: 'Motion Sensor',
        supports: 'occupancy',
        fromZigbee: [],
        toZigbee: [],
    },`

This is the database.db entry:

`{"id":2,"type":"EndDevice","ieeeAddr":"0x000d6f000ab51414","nwkAddr":65241,"manufId":4401,"manufName":"Sercomm Corp.","powerSource":"Battery","modelId":"SZ-PIR02_SF","epList":[1],"status":"online","joinTime":1542373751,"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[3],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{"zclVersion":1,"appVersion":19,"stackVersion":84,"hwVersion":16,"manufacturerName":"Sercomm Corp.","modelId":"SZ-PIR02_SF","dateCode":"20161128","powerSource":3}},"genPowerCfg":{"dir":{"value":1},"attrs":{"batteryVoltage":29,"batterySize":0,"batteryQuantity":2,"batteryAlarmMask":255,"batteryVoltMinThres":25,"batteryVoltThres1":26,"batteryVoltThres2":26,"batteryVoltThres3":27,"batteryAlarmState":0}},"genIdentify":{"dir":{"value":3},"attrs":{"identifyTime":0}},"genPollCtrl":{"dir":{"value":1},"attrs":{}},"msTemperatureMeasurement":{"dir":{"value":1},"attrs":{"measuredValue":0,"minMeasuredValue":0,"maxMeasuredValue":0,"tolerance":0}},"ssIasZone":{"dir":{"value":1},"attrs":{"zoneState":0,"zoneType":13,"zoneStatus":36,"iasCieAddr":"0x0000000000000000","zoneId":255}},"haDiagnostic":{"dir":{"value":1},"attrs":{"macTxUcastRetry":11,"aPSTxUcastSuccess":20,"aPSTxUcastFail":0,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":255,"lastMessageRssi":-44}}}}},"_id":"ZbFqqZwswGturTPK"}`

No output in debug terminal is displayed when triggering motion, where to go from here?

**Comment by Koenkk** [comment]
As this is an ias device it needs to be enrolled. Can you try with (may require repairing):

```js
{
    zigbeeModel: ['SZ-PIR02_SF'],
    model: 'SZ-PIR02',
    vendor: 'Iris',
    description: 'Motion Sensor',
    supports: 'occupancy',
    fromZigbee: [],
    toZigbee: [],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);
        const actions = [
            (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
            (cb) => device.report('ssIasZone', 'zoneStatus', 0, 30, null, cb),
            (cb) => device.functional('ssIasZone', 'enrollRsp', {
                enrollrspcode: 1,
                zoneid: 23
            }, cb),
        ];

        execute(device, actions, callback);
    },
},
```
