### ISSUE TITLE
Add support for GL-FL-005TZP

### ISSUE THREAD

**Issue by passy05** [Koenkk/zigbee2mqtt#5114]
I got a Gledopto floodlight GL-FL-005 Pro detected by zigbee2mqtt as GL-FL-005TZP which is not supported.

As I am using the Home Assistant Add-on, I got the devices.js for zigbee-herdsman-converters for v12.0.224 and I added it to my data_path folder. 
I was able to pair the device successfully after replacing GL-FL-005TZ by GL-FL-005TZP:

    {                                    
        zigbeeModel: ['GL-FL-005TZP'],
        model: 'GL-FL-005TZP',
        vendor: 'Gledopto',
        description: 'Zigbee 30W floodlight RGB CCT pro',
        extend: gledopto.light_onoff_brightness_colortemp_colorxy,
    },

Please could you add the GL-FL-005TZP to the list of supported devices.

I have noticed that the effects in Home Assistant (like blink) don't really work for me. Is it a know issue with Gledopto?

**Comment by Koenkk** [comment]
Added!

**Comment by passy05** [comment]
Thank you!
