### ISSUE TITLE
Zigbee2Mqtt Assistant

### ISSUE THREAD

**Issue by rapid1985** [Koenkk/zigbee2mqtt#5116]
Hello

I would like to install the Zigbee2Mqtt Assistant on Docker on a Raspberry Pi 1 with Rasp OS Lite, but it always restarts and can therefore not work.

`sudo docker run -p 8880:80 -e "Z2MA_SETTINGS__MQTTSERVER=192.168.0.50" -e "Z2MA_SETTINGS__MQTTUSERNAME=<mqttusername>" -e "Z2MA_SETTINGS__MQTTPASSWORD=<mqttpassword>" -e "Z2MA_SETTINGS__MQTTPORT=1024" --restart unless-stopped carldebilly/zigbee2mqttassistant`

`pi@raspberrypi:~ $ sudo docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                           PORTS               NAMES
85c335009d6b        carldebilly/zigbee2mqttassistant   "dotnet Zigbee2MqttA…"   2 hours ago         Restarting (139) 8 seconds ago                       quirky_tesla
`

What can I do?
Thank you Alex

**Comment by tavalin** [comment]
Zigbee2mqtt assistant is not part of this project so you should ask over at the ZigBee2mqtt assistant repo

**Comment by rapid1985** [comment]
Thank you for the information

**Comment by Koenkk** [comment]
For zigbee2mqtt assistant create an issue here; https://github.com/yllibed/Zigbee2MqttAssistant/issues
