### ISSUE TITLE
Hornbach FLAIR Viyu Smart GU10 RGBW lamp

### ISSUE THREAD

**Issue by VincentSC** [Koenkk/zigbee2mqtt#5117]
Webpage: https://www.hornbach.nl/shop/FLAIR-Viyu-Smart-LED-lamp-GU10-6W-reflectorvorm-RGBW/10297666/artikel.html?sourceArt=10297667&url=10297666&trackArticleCrossType=se

Adding to node_modules/zigbee-herdsman-converters/devices.js is straightforward: 
```
   {
        zigbeeModel: ['VIYU_GU10_350_RGBW_10297666'],
        model: '10297666',
        vendor: 'HORNBACH',
        description: 'FLAIR Viyu Smart GU10 RGBW lamp',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    },
```
Under `// HORNBACH` line 13760.

No converter problems, so a good starter device :smile: 

PS: other Hornbach lamps have a typo "lampE" in devices.js.

**Comment by Koenkk** [comment]
Added, thanks
