### ISSUE TITLE
SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by christianblessing-me** [Koenkk/zigbee2mqtt#5119]
I restarted my RPi2 after the Zigbee2MQTT installation, now Zigbee2MQTT won't start due to the JS error w/ an unexpected token in index.js - it worked perfectly fine before the reboot of the RPi2, didn't change a line of code there.

Debug log: https://hastebin.com/abutoderax.sql

**Comment by Koenkk** [comment]
The following command may fix it `cd /opt/zigbee2mqtt && npm ci`
