### ISSUE TITLE
Centralite Micro Motion Sensor

### ISSUE THREAD

**Issue by ben423423n32j14e** [Koenkk/zigbee2mqtt#512]
Ordered one of these, should arrive within a couple of weeks.

https://www.amazon.com/gp/product/B0713STYJQ

Powered by CR2450 battery.

**Comment by jke9703** [comment]
Fucking about y ung

**Comment by ben423423n32j14e** [comment]
@Koenkk I've got this device, I've spent over an hour attempting to pair it with Zigbee2MQTT trying every combination of removing the battery, pressing, holding reset etc...

The problem is Zigbee2MQTT doesn't seem to allow enough time to join?

zigbee2mqtt:error 2018-11-11 16:32:15 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)

**Comment by ryanbeaton** [comment]
Sounds like the MiJia devices, you have to keep them ‘awake’

https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices

**Comment by ben423423n32j14e** [comment]
@ryanbeaton Yes I am well aware of this requirement, unfortunately the sensor does not appear to support that function. Once I initiate the pairing it appears to ignore any further presses of the pairing button for a duration of time.

**Comment by ben423423n32j14e** [comment]
@Koenkk @tb-killa I need help with this one.

The sensors pairing process is automatic, pressing buttons on the sensor does not assist with the pairing process (see above).

Here is terminal log output over a 5 minute period, the sensor just retries non-stop to pair with Zigbee2MQTT.

`  zigbee2mqtt:error 2018-11-17 01:52:03 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:52:23 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:52:52 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:53:13 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:53:33 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:53:53 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:54:13 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:debug 2018-11-17 01:54:32 Saving state to file /opt/zigbee2mqtt/data/state.json
  zigbee2mqtt:error 2018-11-17 01:54:33 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:54:53 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:55:48 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:56:08 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:56:28 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:56:48 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)
  zigbee2mqtt:error 2018-11-17 01:57:08 Cannot get the Node Descriptor of the Device: 0x000d6f0010c0ca22 (Error: Timed out after 10000 ms)`

Any ideas?

**Comment by Koenkk** [comment]
It probably requires the ias enroll request to be send while pairing which require some changes in zigbee-shepherd. 

Let's first add support for your other motion sensors.
