### ISSUE TITLE
Problem with Aqara door sensor et switch button : Status in the logs are different

### ISSUE THREAD

**Issue by diazovitch** [Koenkk/zigbee2mqtt#5120]
Hi,
My installation has been working fine for several months.
The only recent change: I renamed my devices. Since my various Aqara sensors only transmit "On" / "Off".
My blockys do not work because for the door sensors, I use the Open / Closed status. I now have to use "On" / "Off".
Also for my switch button with which I used several statuses: Click / double click / triple click / Quadruple click, I can only use "On".
I updated the plugin.
Do you have an idea ?
I also recently had several successive blackouts.

**## Debug info**
**Domoticz 2020.2** on the raspberry pi 3B+ and SSD disk
Zigbee2MQTT version: **v.1.16.1 (zStack12 20181024)**
Adapter hardware: **CC2531**
![Device](https://user-images.githubusercontent.com/48931195/100537876-5b800b00-322c-11eb-93b9-312e050d8e6a.JPG)
![Données log](https://user-images.githubusercontent.com/48931195/100537879-5cb13800-322c-11eb-8831-bfb1ab89a464.JPG)
![Text Log](https://user-images.githubusercontent.com/48931195/100537881-5f139200-322c-11eb-894f-8a5ca3dd39fb.JPG)

**Comment by salopette** [comment]
You have to set up a shutdown delay for the switch in Domoticz.

![sshot-1](https://user-images.githubusercontent.com/32480002/100550407-15ea2f00-327a-11eb-94d5-64bc1a5a4e1a.jpg)
