### ISSUE TITLE
Every few hours the network fails with MEM_ERROR

### ISSUE THREAD

**Issue by jum** [Koenkk/zigbee2mqtt#5123]
## What happened

Every few hours z2m stops with MEM_ERROR.

## What did you expect to happen

Should continue to run for more than a few hours.

## How to reproduce it (minimal and precise)

Run on my network (all Ikea devices, all latest firmware) for a few hours and it happens. All devices are paired properly and put into groups. Some groups are bound to remotes, and one group to a motion sensor.

## Debug info
Zigbee2MQTT version: 1.16.1 (commit #cb9699e)
Adapter hardware: CC2531
Adapter firmware version: znp version 'zStack12' ({"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619})
Source Routing version

Full Debug log of a typical run here:

https://anubis.mager.org/nextcloud/s/aTNiJ4ymBDRmwYx

**Comment by Koenkk** [comment]
You have quite some devices connected (36), looks that the CC2531 is not powerful enough to handle that. I recommend upgrading to a more powerful adapter. https://www.zigbee2mqtt.io/getting_started/what_do_i_need.html#supported-zigbee-adapter
