### ISSUE TITLE
CC2531 not pairing

### ISSUE THREAD

**Issue by joy079** [Koenkk/zigbee2mqtt#5130]
Hello, i have une coordinator usb cc2531 programmed correctly, i have configured to work on domoticz but when i go to pairing the device they not do any !! I show te log of device in realtime but al the device not send any info.. Can help me ?

log..

nov 30 10:11:40 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:11:40: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
nov 30 10:11:40 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:11:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[],"type":"groups"}'
nov 30 10:11:40 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:11:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9b6db","lastSeen":1606727500900,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"}],"type":"devices"}'
nov 30 10:11:40 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:11:40: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"cb9699e","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.1"}'
nov 30 10:12:18 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:18: Zigbee: disabling joining new devices.
nov 30 10:12:18 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:18: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"cb9699e","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":false,"version":"1.16.1"}'
nov 30 10:12:18 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:18: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d9b6db","lastSeen":1606727538769,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"}],"type":"devices"}'
nov 30 10:12:19 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[],"type":"groups"}'
nov 30 10:12:22 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:22: Zigbee: allowing new devices to join.
nov 30 10:12:23 raspberrypi npm[16724]: Zigbee2MQTT:info  2020-11-30 10:12:23: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"cb9699e","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.1"}'

**Comment by kevincaradant** [comment]
Hi

I think you should specify what devices you're tryning to pair ;)

And use 
```
This is more easy to read the log like that
```

And to finish, try to put you Z2M in debug mode :)
https://www.zigbee2mqtt.io/information/debug.html
