### ISSUE TITLE
Expose version in interface ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [Koenkk/zigbee2mqtt#5158]
## Is your feature request related to a problem? Please describe
I would like to get the current verison of z2m via the new user interface.

## Describe the solution you'd like

Maybe like http://z2m/version ?

**Comment by osos** [comment]
Have a look at Settings -> About

**Comment by Jeoffreybauvin** [comment]
Yes,  I saw this @osos, but it requires a full parsing of the html page...

**Comment by Koenkk** [comment]
Issues related to the frontend should be created here: https://github.com/nurikk/z2m-frontend/issues
