### ISSUE TITLE
OSRAM AC03648 + zigbee2mqtt pairing failed

### ISSUE THREAD

**Issue by davisdmg** [Koenkk/zigbee2mqtt#5181]
Hi!

I wasnt unsure where to post this. I got this light that it is supposed that it is supported, however once I pair it, I get "unsupported".

Only thing that works is to use it as "router"

Zigbee Id is 0x7cb03eaa00ac7ec1.
Address on Zigbee Network is 0xDC47.
Link quality is unknown/255.
Model is unknown by unknown.
Hardware version is unknown.
Firmware version is unknown.
This device type is Router

I already reset it several times. I also tried to add it manually as the documentation says:
https://www.zigbee2mqtt.io/devices/AC03648.html

Zigbee2MQTT version: Zigbee2mqtt 1.16.2.2
Adapter hardware: CC2531
Adapter firmware version: Latest (installed 2 weeks ago)

Am I doing something wrong?

Thanks for taking your time with this :)

**Comment by luchtgitaar** [comment]
I have the same problem.

**Comment by Buva79** [comment]
Did you try updating everything to latest version?

**Comment by davisdmg** [comment]
I did. Nothing changed :( (Updated everything today again).

**Comment by pixeldoc2000** [comment]
Look at https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Post your database.db entry for the Device.

Does the database.db record for the Device have `"interviewCompleted":true` ?

If not try to bring the Device closer to your Coordinator or maybe try a Zigbee Repeater nearby.
