### ISSUE TITLE
iolloi Zigbee Dimmer 5-200W - pairing

### ISSUE THREAD

**Issue by Garbracht** [Koenkk/zigbee2mqtt#5183]
I have purchased a "**iolloi Zigbee Dimmer 5-200W**, 230V Phasenabschnitt-Drehdimmer für Dimmbare LED und Halogen Lampen, kompatibel mit Philips Hue, Alexa und Google Home" on Amazon.

https://www.amazon.de/dp/B08L6JBJVD?psc=1&ref=ppx_pop_dt_b_product_details

I wanted to connect the device to my ioBroker with Zigbee adapter. Wiring and manual operation went very well. When pairing the device was identified by ioBroker but produced an error message: 
 
Error: Device 0x086bd7fffe5cde07 "Eco-Dim.07" not described in statesMapping.. undefined 

I think the device is notlisted in your list. 

Maybe you have planned to add this dimmer to your list. Can you give me some advice how to proceed?

**Comment by Koenkk** [comment]
This is not the iobroker issue tracker, see https://github.com/ioBroker/ioBroker.zigbee/issues
