### ISSUE TITLE
Disable reporting for specific device/devices

### ISSUE THREAD

**Issue by yabbah** [Koenkk/zigbee2mqtt#5190]
## Is your feature request related to a problem? Please describe
Everytime I restart z2m addon I have to wait a couple of minutes for my hue bulb to gives error for setting up reporting. Its gives like this in the log:

```
Zigbee2MQTT:error 2020-12-03 22:36:49: Failed to setup reporting for '0x00178801044ae222' - Error: ConfigureReporting 0x00178801044ae222/11 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":300,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 39467 - 11 - 8 - 6 - 7 after 10000ms)
    at Timeout._onTimeout (/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

After I wait for those timeouts everything goes fine. I have most IKEA bulbs in my 100+ network, but also some 10+ hue devices.

## Describe the solution you'd like
As I want reporting on, to get the state to home assistant when turn on the lights with binded remotes, I would like to be able to disable reporting for specific devices in devices.yaml for example with
`reporting: false`
for those specific devices.

## Describe alternatives you've considered
None

## Additional context
Dont have anything.

**Comment by fwelvering** [comment]
+1

**Comment by frso80** [comment]
+1
