### ISSUE TITLE
zigbee2mqtt/bridge/config/devices and .../groups lost

### ISSUE THREAD

**Issue by fnfid** [Koenkk/zigbee2mqtt#5191]
At the moment i do not get either device list nor group list the easy way by zigbee2mqtt/bridge/config/devices  or ...groups. This stopped working in master 1.16.2 (and in develeoper tree some week ago). This may be not a part of legacy to get rid of as its still in the documentation, and its a helpful thing.

How to reproduce it (minimal and precise)

send whatever payload to zigbee2mqtt/bridge/config/devices and listen to zigbee2mqtt/bridge/log with unfortunally no answer, .../groups the same

 Debug info
Zigbee2MQTT version: 1.16.2 (master) or latest dev same
Adapter hardware: CC1352P-2
Adapter firmware version: 20201026

**Comment by Koenkk** [comment]
can you provide your configuration.yaml?

**Comment by fnfid** [comment]
Shure, things haven't been changed here for a while: (sorry for pasting)

homeassistant: false
permit_join: false
experimental:
  new_api: true
frontend:
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost:1883'
  include_device_information: true
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 6754
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  channel: 11
  cache_state: true
  report: true
  availability_timeout: 0
  log_level: debug
  log_directory: /media/pi/SICHERUNG/Log/%TIMESTAMP%
  log_file: log.txt
devices:
  '0xec1bbdfffe19af4b':
    friendly_name: Wohn_Fern
  '0x000d6ffffe5b0bde':
    friendly_name: Master_Fern
  '0xec1bbdfffe0242a0':
    friendly_name: Schlaf_Fern
  '0xec1bbdfffe1a8073':
    friendly_name: Ess_Fern
  '0xec1bbdfffe181510':
    friendly_name: Oben_Fern
  '0xec1bbdfffea7c6c3':
    friendly_name: Treppe_Fern
  '0x680ae2fffe10c871':
    friendly_name: Wecker_Dim
  '0xec1bbdfffea17ea6':
    friendly_name: Kaffee_2
  '0xec1bbdfffe3dbe33':
    friendly_name: Motion_Keller_1
  '0x00178801089cfba0':
    friendly_name: Kelleru_Dose
  '0x000d6ffffe6366f5':
    friendly_name: Esslampe
  '0xccccccfffebcd62e':
    friendly_name: Kellerlampe
  '0xccccccfffe8d854a':
    friendly_name: Buerolampe1
  '0x14b457fffe399b4b':
    friendly_name: '0x14b457fffe399b4b'
  '0xccccccfffec8a8cf':
    friendly_name: Obenlampe1
  '0x000d6ffffe6163a5':
    friendly_name: Obenlampe2
  '0xccccccfffedf659c':
    friendly_name: Obenlampe3
  '0xec1bbdfffe36185d':
    friendly_name: Obenlampe4
  '0xccccccfffe3ef247':
    friendly_name: Kaffee_1
  '0x00178801083be0f9':
    friendly_name: Wohnlampe1
  '0x00178801083bdce5':
    friendly_name: Wohnlampe2
  '0x0017880106bae95b':
    friendly_name: Wohnlampe4
  '0x00178801083bad31':
    friendly_name: Wohnlampe6
  '0x00178801068fe230':
    friendly_name: Wohnlampe8
  '0x00178801068fce22':
    friendly_name: Wohnlampe3
  '0x00178801083b9fd6':
    friendly_name: Wohnlampe5
  '0x0017880106bafda8':
    friendly_name: Wohnlampe7
  '0x00124b001ca60d6e':
    friendly_name: '0x00124b001ca60d6e'
  '0x000d6ffffe9f7931':
    friendly_name: Repeater
  '0xec1bbdfffe43156e':
    friendly_name: Badlampeu1
  '0xccccccfffe92eb62':
    friendly_name: Badlampeu2
  '0xccccccfffe92eeec':
    friendly_name: Badlampeu3
  '0xccccccfffef24128':
    friendly_name: Mixi_Dim
  '0xf0d1b800001351cc':
    friendly_name: '0xf0d1b800001351cc'
  '0x00158d0004600b10':
    friendly_name: Ambient_1
    temperature_precision: 1
    temperature_calibration: 0
    humidity_precision: 1
    pressure_precision: 1
    pressure_calibration: 33.2
  '0x00158d000271bbfe':
    friendly_name: Wasser_Keller
  '0x00158d00032c8a68':
    friendly_name: Cube_Master
  '0xccccccfffedd422f':
    friendly_name: Küchendecke2
  '0xccccccfffed7878d':
    friendly_name: Küchendecke4
  '0xec1bbdfffe2de076':
    friendly_name: Küchendecke1
  '0xccccccfffe92e7aa':
    friendly_name: Küchendecke3
  '0xccccccfffea8c896':
    friendly_name: Küchendecke5
  '0x14b457fffe78121e':
    friendly_name: Schlaflampe
  '0x04cf8cdf3c759a30':
    friendly_name: Ketteo_Dose
  '0x680ae2fffe32ecbb':
    friendly_name: Motion_Keller_2
  '0x14b457fffe39a25f':
    friendly_name: '0x14b457fffe39a25f'
  '0xccccccfffeab3280':
    friendly_name: TreppeOben
  '0xccccccfffe294da0':
    friendly_name: Badu_Dim
  '0x7cb03eaa0a00a320':
    friendly_name: Aussen_Dose
  '0x001788010862af2f':
    friendly_name: Kaffee_Dose
  '0x7cb03eaa0a090df9':
    friendly_name: Makita_Dose
  '0x7cb03eaa0a090e3a':
    friendly_name: '0x7cb03eaa0a090e3a'
  '0x7cb03eaa0a0a2731':
    friendly_name: Mixi_Dose
  '0x7cb03eaa0a06f437':
    friendly_name: Schmink_Dose
  '0x7cb03eaa00b0d663':
    friendly_name: Receiver_Dose
  '0x000d6ffffe12ed3b':
    friendly_name: Leptiter
  '0x0017880103be0685':
    friendly_name: Treppe
  '0x680ae2fffead7a5e':
    friendly_name: Naehlampe1
  '0x680ae2fffeb14132':
    friendly_name: Naehlampe2
  '0x680ae2fffeb13b66':
    friendly_name: '0x680ae2fffeb13b66'
  '0x680ae2fffe39b314':
    friendly_name: Motion_Keller_3
  '0x680ae2fffe14a359':
    friendly_name: Babyliss_Color
  '0x588e81fffe2cbc31':
    friendly_name: Aussen
  '0xec1bbdfffeb7f350':
    friendly_name: Terassenlampe1
  '0x588e81fffe1743c5':
    friendly_name: Ess_Dim
  '0x588e81fffe2e37c8':
    friendly_name: Oben_Dim
  '0xec1bbdfffea68116':
    friendly_name: Bado_Fern
  '0x680ae2fffea22836':
    friendly_name: Küche_Fern
  '0x000d6ffffeff4fc2':
    friendly_name: Terassenlampe2
  '0x680ae2fffeacae19':
    friendly_name: Küchenunter1
  '0x680ae2fffead2b18':
    friendly_name: '0x680ae2fffead2b18'
  '0x680ae2fffe83a12a':
    friendly_name: '0x680ae2fffe83a12a'
  '0x680ae2fffebeb1aa':
    friendly_name: Badlampeo1
  '0x680ae2fffebf4675':
    friendly_name: Badlampeo2
  '0x680ae2fffea66ceb':
    friendly_name: Badlampeo3
  '0x680ae2fffebf4c3f':
    friendly_name: Badlampeo4
  '0x680ae2fffea66b83':
    friendly_name: Badlampeo5
  '0x680ae2fffebf4fe8':
    friendly_name: Hinterschrank
  '0xd0cf5efffeec0dca':
    friendly_name: '0xd0cf5efffeec0dca'
  '0x588e81fffe22be49':
    friendly_name: Essunter1
  '0x588e81fffe3e9ff1':
    friendly_name: Küche_Dim
  '0x680ae2fffe813436':
    friendly_name: Buero_Dim
  '0xec1bbdfffeb1d1de':
    friendly_name: Mixiunter1
  '0x680ae2fffe974dca':
    friendly_name: Babyliss
  '0x588e81fffebccce0':
    friendly_name: Ketteu_Dose
  '0x588e81fffebccaf5':
    friendly_name: Badu_Dose
  '0x588e81fffe61d183':
    friendly_name: Naeh_Dose
  '0x588e81fffe609c3a':
    friendly_name: '''0x588e81fffe609c3a'''
  '0xccccccfffeba5a68':
    friendly_name: Phantom
  '0x842e14fffe47e01d':
    friendly_name: '0x842e14fffe47e01d'
  '0xbc33acfffe13c509':
    friendly_name: '0xbc33acfffe13c509'
groups:
  '1':
    friendly_name: Wohn
    devices:
      - 0x00178801068fe230/11
      - 0x00178801083be0f9/11
      - 0x00178801083bdce5/11
      - 0x00178801068fce22/11
      - 0x0017880106bae95b/11
      - 0x00178801083b9fd6/11
      - 0x00178801083bad31/11
      - 0x0017880106bafda8/11
  '2':
    friendly_name: Schlaf
    devices:
      - 0x14b457fffe78121e/1
  '3':
    friendly_name: Oben
    devices:
      - 0xccccccfffec8a8cf/1
      - 0x000d6ffffe6163a5/1
      - 0xccccccfffedf659c/1
      - 0xec1bbdfffe36185d/1
  '4':
    friendly_name: Badu
    devices:
      - 0xec1bbdfffe43156e/1
      - 0xccccccfffe92eb62/1
      - 0xccccccfffe92eeec/1
  '5':
    friendly_name: Küchendecke
    devices:
      - 0xccccccfffedd422f/1
      - 0xccccccfffed7878d/1
      - 0xec1bbdfffe2de076/1
      - 0xccccccfffe92e7aa/1
      - 0xccccccfffea8c896/1
  '6':
    friendly_name: Buero
    devices:
      - 0xccccccfffe8d854a/1
  '7':
    friendly_name: Naehtisch
    devices:
      - 0x680ae2fffead7a5e/1
      - 0x680ae2fffeb14132/1
  '8':
    friendly_name: Schreibtisch
    devices:
      - 0x000d6ffffe12ed3b/1
  '9':
    friendly_name: Bado
    devices:
      - 0x680ae2fffebeb1aa/1
      - 0x680ae2fffebf4675/1
      - 0x680ae2fffea66ceb/1
      - 0x680ae2fffebf4c3f/1
      - 0x680ae2fffea66b83/1
  '10':
    friendly_name: Küchenunter
    devices:
      - 0x680ae2fffeacae19/1
  '11':
    friendly_name: Essunter
    devices:
      - 0x588e81fffe22be49/1
  '12':
    friendly_name: Mixiunter
    devices:
      - 0xec1bbdfffeb1d1de/1

**Comment by Koenkk** [comment]
Can you provide the debug log of starting zigbee2mqtt?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by fnfid** [comment]
Here's the logfile from this morning, rest of the code is running extremely well:-)

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5643633/log.txt)

**Comment by Koenkk** [comment]
To get the list your first have to publish to `zigbee2mqtt/bridge/config/devices/get` (https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigdevicesget). I don't see this in your log

**Comment by fnfid** [comment]
thats correct. Formerly i send an empty payload to zigbee/bridge/config/devices and get the answer from ../bridge/config, this does not work anymore.
Your solution works fine! Thanks a lot!
The old version is still documented in the mqtt_topics_and_message_structure.html , a few lines above, and may be removed as legacy not working anymore. Its in the zigbee/bridge/log section found near "list of all devices".
Thanks!

**Comment by Koenkk** [comment]
> Formerly i send an empty payload to zigbee/bridge/config/devices and get the answer from ../bridge/config, this does not work anymore.

The documentation is wrong on this, this was never intended to work.

Anyway with the next release a new api will be released (already enabled by default in 1.16.2-dev)

**Comment by fnfid** [comment]
Use this already:-)
Still for the records: Recent way to get device list is perfect, still groups list my be done same way similar to zigbee2mqtt/bridge/config/groups/get instead of empzy payload to zigbee2mqtt/bridge/config/groups (as this works so far this way only)
This can be closed, Thank for the support!
