### ISSUE TITLE
Hassio and firmware 20190608 wont be able to pair devices

### ISSUE THREAD

**Issue by jtomasrl** [Koenkk/zigbee2mqtt#5199]
## What happened
After moving all my home automation from Home Assistant to Hassio (on a RPI 3), all my Aqara sensors (almost) stopped working. I reinstalled my whole network by:
1.- Upgrading my CC2531 to firmware version 20190608
2.- Installed Zigbee2Mqtt on Hassio 1.16.2
3.- Destroying all my database and config files, factory reset all my devices

So far I've just been able to pair my Aqara motion sensor. I own a few vibration, light switches, temperature sensors and zonoff on/off switches and none of them are able to pair into my network. Im not getting any output on my console either (using debug on log_level.

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> ./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
> [Info] Socat is DISABLED and not started
> 2020-12-05T00:57:10: PM2 log: Launching in no daemon mode
> 2020-12-05T00:57:10: PM2 log: App [npm:0] starting in -fork mode-
> 2020-12-05T00:57:10: PM2 log: App [npm:0] online
> > zigbee2mqtt@1.16.2 start /zigbee2mqtt-1.16.2
> > node index.js
> Zigbee2MQTT:debug 2020-12-05 00:57:14: Loaded state from file /share/zigbee2mqtt/state.json
> Zigbee2MQTT:info  2020-12-05 00:57:14: Logging to console and directory: '/share/zigbee2mqtt/log/2020-12-05.00-57-13' filename: log.txt
> Zigbee2MQTT:debug 2020-12-05 00:57:14: Removing old log directory '/share/zigbee2mqtt/log/2020-12-04.23-49-38'
> Zigbee2MQTT:info  2020-12-05 00:57:14: Starting Zigbee2MQTT version 1.16.2 (commit #1.16.2)
> Zigbee2MQTT:info  2020-12-05 00:57:14: Starting zigbee-herdsman (0.13.37)
> Zigbee2MQTT:debug 2020-12-05 00:57:14: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
> Zigbee2MQTT:info  2020-12-05 00:57:16: zigbee-herdsman started
> Zigbee2MQTT:info  2020-12-05 00:57:16: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:16: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
> Zigbee2MQTT:info  2020-12-05 00:57:16: Currently 1 devices are joined:
> Zigbee2MQTT:info  2020-12-05 00:57:16: 0x00158d0003465048 (0x00158d0003465048): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
> Zigbee2MQTT:warn  2020-12-05 00:57:16: `permit_join` set to  `true` in configuration.yaml.
> Zigbee2MQTT:warn  2020-12-05 00:57:16: Allowing new devices to join.
> Zigbee2MQTT:warn  2020-12-05 00:57:16: Set `permit_join` to `false` once you joined all devices.
> Zigbee2MQTT:info  2020-12-05 00:57:16: Zigbee: allowing new devices to join.
> Zigbee2MQTT:info  2020-12-05 00:57:16: Started frontend on port 0.0.0.0:8099
> Zigbee2MQTT:info  2020-12-05 00:57:17: Connecting to MQTT server at mqtt://core-mosquitto
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Using MQTT login with username: mqtt-iot
> Zigbee2MQTT:info  2020-12-05 00:57:17: Connected to MQTT server
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/0x00158d0003465048', payload '{"battery":100,"illuminance":38,"illuminance_lux":38,"occupancy":true,"voltage":3015}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/bridge/info', payload '{"commit":"1.16.2","config":{"advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":0,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221],"homeassistant_discovery_topic":"homeassistant","homeassistant_legacy_triggers":true,"homeassistant_status_topic":"hass/status","last_seen":"disable","legacy_api":true,"log_directory":"/share/zigbee2mqtt/log/%TIMESTAMP%","log_file":"log.txt","log_level":"debug","log_output":["console","file"],"log_rotation":true,"log_syslog":{},"pan_id":6754,"report":false,"soft_reset_timeout":0,"timestamp_format":"YYYY-MM-DD HH:mm:ss"},"ban":[],"blocklist":[],"device_options":{},"devices":{"0x00158d0003465048":{"friendly_name":"0x00158d0003465048"}},"experimental":{"new_api":true,"output":"json"},"external_converters":[],"frontend":{"port":8099},"groups":{},"homeassistant":true,"map_options":{"graphviz":{"colors":{"fill":{"coordinator":"#e04e5d","enddevice":"#fff8ce","router":"#4ea3e0"},"font":{"coordinator":"#ffffff","enddevice":"#000000","router":"#ffffff"},"line":{"active":"#009900","inactive":"#994444"}}}},"mqtt":{"base_topic":"zigbee2mqtt","force_disable_retain":false,"include_device_information":false,"server":"mqtt://core-mosquitto","user":"mqtt-iot"},"passlist":[],"permit_join":true,"queue":{},"serial":{"disable_led":false,"port":"/dev/ttyACM0"},"whitelist":[]},"coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extended_pan_id":"0xdddddddddddddddd","pan_id":6754},"permit_join":true,"version":"1.16.2"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/bridge/devices', payload '[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]}},"11":{"bindings":[],"clusters":{"input":["ssIasAce"],"output":["ssIasZone","ssIasWd"]}},"110":{"bindings":[],"clusters":{"input":[],"output":[]}},"12":{"bindings":[],"clusters":{"input":[],"output":[]}},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]}},"2":{"bindings":[],"clusters":{"input":[],"output":[]}},"242":{"bindings":[],"clusters":{"input":[],"output":[]}},"3":{"bindings":[],"clusters":{"input":[],"output":[]}},"4":{"bindings":[],"clusters":{"input":[],"output":[]}},"47":{"bindings":[],"clusters":{"input":[],"output":[]}},"5":{"bindings":[],"clusters":{"input":[],"output":[]}},"6":{"bindings":[],"clusters":{"input":[],"output":[]}},"8":{"bindings":[],"clusters":{"input":[],"output":[]}}},"friendly_name":"Coordinator","ieee_address":"0x00124b00193672fa","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"definition":{"description":"Aqara human body movement and illuminance sensor","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates whether the device detected occupancy","name":"occupancy","property":"occupancy","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Raw measured illuminance","name":"illuminance","property":"illuminance","type":"numeric","unit":"lx"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"RTCGQ11LM","vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]}}},"friendly_name":"0x00158d0003465048","ieee_address":"0x00158d0003465048","interview_completed":true,"interviewing":false,"network_address":28414,"power_source":"Battery","supported":true,"type":"EndDevice"}]'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/bridge/groups', payload '[]'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"1.16.2","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.2"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"1.16.2","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.16.2"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'homeassistant/sensor/0x00158d0003465048/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_battery","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'homeassistant/binary_sensor/0x00158d0003465048/occupancy/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"motion","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'homeassistant/sensor/0x00158d0003465048/illuminance/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"illuminance","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_illuminance","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_illuminance_zigbee2mqtt","unit_of_measurement":"lx","value_template":"{{ value_json.illuminance }}"}'
> Zigbee2MQTT:info  2020-12-05 00:57:17: MQTT publish: topic 'homeassistant/sensor/0x00158d0003465048/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_linkquality","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_battery","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/illuminance/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"illuminance","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_illuminance","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_illuminance_zigbee2mqtt","unit_of_measurement":"lx","value_template":"{{ value_json.illuminance }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_linkquality","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/binary_sensor/0x00158d0003465048/occupancy/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"motion","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_battery","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/binary_sensor/0x00158d0003465048/occupancy/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"motion","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_occupancy","payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_occupancy_zigbee2mqtt","value_template":"{{ value_json.occupancy }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/illuminance/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"device_class":"illuminance","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_illuminance","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_illuminance_zigbee2mqtt","unit_of_measurement":"lx","value_template":"{{ value_json.illuminance }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:17: Received MQTT message on 'homeassistant/sensor/0x00158d0003465048/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x00158d0003465048"],"manufacturer":"Xiaomi","model":"Aqara human body movement and illuminance sensor (RTCGQ11LM)","name":"0x00158d0003465048","sw_version":"Zigbee2MQTT 1.16.2"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x00158d0003465048","name":"0x00158d0003465048_linkquality","state_topic":"zigbee2mqtt/0x00158d0003465048","unique_id":"0x00158d0003465048_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
> Zigbee2MQTT:debug 2020-12-05 00:57:21: Received Zigbee message from '0x00158d0003465048', type 'attributeReport', cluster 'msIlluminanceMeasurement', data '{"measuredValue":35}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-12-05 00:57:21: MQTT publish: topic 'zigbee2mqtt/0x00158d0003465048', payload '{"battery":100,"illuminance":35,"illuminance_lux":35,"linkquality":107,"occupancy":true,"voltage":3015}'
> Zigbee2MQTT:debug 2020-12-05 00:57:21: Received Zigbee message from '0x00158d0003465048', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
> Zigbee2MQTT:info  2020-12-05 00:57:21: MQTT publish: topic 'zigbee2mqtt/0x00158d0003465048', payload '{"battery":100,"illuminance":35,"illuminance_lux":35,"linkquality":107,"occupancy":true,"voltage":3015}'

## What did you expect to happen
Being able to pair my devices

## How to reproduce it (minimal and precise)
Fresh install and try to pair new devices

## Debug info
Zigbee2MQTT version: 1.16.2 (hassio)
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by ccantill** [comment]
Had the same issue here; suddenly my zigbee devices stopped working in HomeAssistant. There were errors in the HA log about parsing the availability bit of the entity descriptors. Commenting out that part of the code in lib/extensions/homeassistant.js fixed it for me (lines 684-687).
