### ISSUE TITLE
Xiaomi switch status message is reset immediately, no switching possible

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#5207]
Hello, since the last update, the status signals are only transmitted very briefly, so that switching is not possible.

In the frontend it is only displayed briefly and is immediately empty again.
It does not stop at the click or dooble click.

![sshot-3](https://user-images.githubusercontent.com/32480002/101273227-b7e6ab80-3793-11eb-98c1-fcc83efba054.jpg)
![sshot-4](https://user-images.githubusercontent.com/32480002/101273228-b87f4200-3793-11eb-96c3-2f15d8240d60.jpg)
![sshot-1](https://user-images.githubusercontent.com/32480002/101273230-b917d880-3793-11eb-83da-88380b062ed5.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/101273231-b917d880-3793-11eb-956c-081a2c51c617.jpg)

**Comment by salopette** [comment]
I discovered the bug
it only happens when I activate home assistant support.

When it is turned off, it works normally.

![sshot-5](https://user-images.githubusercontent.com/32480002/101273294-30e60300-3794-11eb-9ab1-08e7da49fe50.jpg)

**Comment by Koenkk** [comment]
This is expected behaviour, for Home Assistant to trigger the action property needs to be cleared again, otherwise automations don't trigger. See https://github.com/Koenkk/zigbee2mqtt/issues/1155#issuecomment-467094619
