### ISSUE TITLE
Silvercrest HG06337 Smart Plug (switch) UK version

### ISSUE THREAD

**Issue by nottledim** [Koenkk/zigbee2mqtt#5208]
I added this to fingerprint array in devices.js for Silvercrest HG06337.  I think it's different because it's UK version first sold 6-Dec-2020 
{modelID: 'TS011F', manufacturerName: '_TZ3000_00mk2xzy'}

It seems to work

**Comment by rock-lobster** [comment]
Ahha, someone beat me to it. Picked up a few this afternoon and yep, different manufacturer name (feels wrong, should be a custom model but hey ho).

Zigbee model 'TS011F' and manufacturer name '_TZ3000_00mk2xzy' is NOT supported

**Comment by Koenkk** [comment]
Just supported.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by haggard71** [comment]
I see Silvercrest smart plug (EU, CH, FR, BS) now, but no sub devices are created.....

**Comment by johnhamelink** [comment]
I've just moved to zigbee2mqtt edge in Home Assistant and my switches now pair nicely!

**Comment by LifeBandit666** [comment]
Still not supported for me using HA addon Z2M Edge. Do I need to do anything extra (it should be auto updating and I have no updates).

**Comment by LifeBandit666** [comment]
its an HG06337-bs

**Comment by rock-lobster** [comment]
are you running the latest edge? It doesn't (AFAIK) auto update on edge - the readme says:

**Updating the Edge add-on**
To update the edge version of the add-on, you will need to uninstall and re-install the add-on.

so if you've not updated for a while, it might be worth backing up the conf, uninstalling and reinstalling and then trying again after resinstalling latest edge. This is what I now see (and the version)

![image](https://user-images.githubusercontent.com/23248543/102078755-5e215980-3e03-11eb-9608-94eb343a90d9.png)

**Comment by LifeBandit666** [comment]
That did it, turns out it was a PICNIC (Problem In Chair Not In Computer) error again. Thanks rock-lobster
