### ISSUE TITLE
Gledopto GL-S-004Z GU10 bulbs ignoring transition value and changing instantly

### ISSUE THREAD

**Issue by jkempson** [Koenkk/zigbee2mqtt#5217]
## What happened
When I change the brightness of the GL-S-004Z bulb with a transition they change instantly.
I have other types of bulb that work fine.
## What did you expect to happen
I expected the bulb to respect the transition value
## How to reproduce it (minimal and precise)
Send Turn On or Turn Off command to bulb with transition value set
## Debug info
Zigbee2MQTT version:  1.16.1-dev
Adapter hardware: CC2652
Adapter firmware version:20200805

**Comment by Koenkk** [comment]
This is a known issue in the firmware of non pro Gledopto products, see point 8 and 9 of https://www.reddit.com/r/Gledopto/comments/it4bed/what_is_pro_gledopto_new_product_series/ 

Since Gledopto does not provide OTA updates the chances of this being solved by Gledopto are 0.
