### ISSUE TITLE
Add device_class for temperature and humidity to homeassistant.js

### ISSUE THREAD

**Issue by RodBr** [Koenkk/zigbee2mqtt#522]
Can "device_class: temperature" and "device_class: humidity" be added to the temperature and humidity sensors in homeassistant.js and remove the custom icon setting?  This will bring them into line with default appearance for temperature and humidity sensors from non-MQTT sensors.

**Comment by Koenkk** [comment]
Good idea, could you make a pr for this?

**Comment by felixtriller** [comment]
I opened a pull request.
