### ISSUE TITLE
Flash CC2530 router firmware using rPi0

### ISSUE THREAD

**Issue by pedroxns** [Koenkk/zigbee2mqtt#5222]
## What happened
Flashed cc2530 with zigbee router firmware using a rPi but can't get it to work.

## What did you expect to happen
Power on CC2530 and get it connected to my zigbee network.

## How to reproduce it (minimal and precise)
```
root@DietPi:~/flash_cc2531# ./cc_erase
  ID = a524.
  erase result = 00a2.
root@DietPi:~/flash_cc2531# ./cc_write router-cc2530-std.hex
  ID = a524.
  reading line 12420.
  file loaded (12422 lines read).
writing page  98/ 98.
verifying page  98/ 98.
 flash OK.
root@DietPi:~/flash_cc2531# 
```
## Debug info
Zigbee2MQTT version:1.16.1
Adapter hardware: CC2530
Adapter firmware version: https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2530

**Comment by Koenkk** [comment]
Since this is not directly a Zigbee2MQTT I recommend to create a new discussion here: https://github.com/Koenkk/zigbee2mqtt/discussions
