### ISSUE TITLE
Error: extra keys not allowed

### ISSUE THREAD

**Issue by Gibbz** [Koenkk/zigbee2mqtt#5230]
## What happened
Home assistant gives errors when trying to apply settings to mqtt devices using zigbee2mqtt and fails to apply settings.
Error bellow from the log.

```
2020-12-09 11:53:57 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140712335312832] Error handling message: extra keys not allowed @ data['disabled_by']. Got None

```
## What did you expect to happen
No errors, should handle the empty fields appropriately

## How to reproduce it (minimal and precise)
I reset my zigbee2mqtt database for a new device. Now I cannot apply HAS settings.

## Debug info
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531
Adapter firmware version: n/a

**Comment by Koenkk** [comment]
Does not look to be a bug in Zigbee2MQTT (disabled_by is not even used by Zigbee2MQTT). Please create an issue here: https://github.com/home-assistant/core/issues
