### ISSUE TITLE
TuYa TS0601_thermostat - several properties read only

### ISSUE THREAD

**Issue by s4nf4n** [Koenkk/zigbee2mqtt#5233]
## What happened

I cannot set following properties via MQTT by using `zigbee2mqtt/[FRIENDLY_NAME]/set`:

- comfort_temperature
- eco_temperature
- boost_time

Might be more.

Additionally several properties/states are not exposed or exposed with "state"-name to Zigbee2Mqtt GUI and thus cannot be changed. 
Trying to change a state of "state" results in `No converter available for 'state' (OFF)` Toast.
See Screenshot:

![image](https://user-images.githubusercontent.com/10939500/101602599-ad7c1a00-39fe-11eb-8ce2-9ebe8e6bf0ba.png)

## What did you expect to happen

- for values to be successfully changed on TuYa TS0601_thermostat
- GUI exposing properties correctly

For reference GUI from 1.16 from https://github.com/Koenkk/zigbee2mqtt/issues/4879

![image](https://user-images.githubusercontent.com/45555966/98361379-b8244780-202b-11eb-8b2d-81d3884fe336.jpg)

## How to reproduce it (minimal and precise)

e.g. publish `zigbee2mqtt/[FRIENDLY_NAME]/set` for TS0601_thermostat with payload `{"comfort_temperature":23}`

## Debug info
Zigbee2MQTT version: 1.16.2
zigbee-herdsman version: 0.13.37
Adapter hardware: CC26X2R1
Adapter firmware version: CC26X2R1_20201026
zigbee2mqtt log: https://hastebin.com/ukodukagib.apache

**Comment by groenmarsmannetje** [comment]
I can confirm that temperatures can now be set in dev version. Boost time is still not possible to set.

**Comment by s4nf4n** [comment]
Thank you @drzony! I can now confirm as well, that I can set `comfort_temperature` and `eco_temperature` with dev branch. `boost_time` still doesn't work.

The Zigbee2mqtt GUI is still missing those temps and the true/false states are not working from UI.

**Comment by drzony** [comment]
@s4nf4n Devices do not accept floats, so z2m cannot do it.

**Comment by drzony** [comment]
@s4nf4n I don;t have this TRV, so I cannot check it, there seem to be no errors in `boost_time` have you tried setting higher/lower (i.e. 100, 200, 250, 300, 350, 400) values? Maybe there is some limit on the device?

**Comment by s4nf4n** [comment]
I have tried to publish i.e. `{"boost_time":240}` in steps of 60 mostly. State of `boost_time` doesn't get updated as when i set other values. I haven't tried to actually look at how long the device actually boosts in boost mode. I might be able to try tomorrow.

**Comment by s4nf4n** [comment]
> I have tried to publish i.e. `{"boost_time":240}` in steps of 60 mostly. State of `boost_time` doesn't get updated as when i set other values. I haven't tried to actually look at how long the device actually boosts in boost mode. I might be able to try tomorrow.

Ok. Boost time really doesn't change.

**Comment by drzony** [comment]
@s4nf4n Try sending low values like 1,2,3,4. As I said I do not have such TRV so it's hard for me to test this. If you feel comfortable with setting up a development version of zigbee-herdsman-converters, then I would be able to help further. If not, then I'm out of options, but maybe someone else can help here.

**Comment by groenmarsmannetje** [comment]
I tried setting Boost time with latest dev build. And now it is changing.

When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 1, it is set to 0
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 60, it is set to 0
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 100, it is set to 100
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 200, it is set to 200
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 240, it is set to 200
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 300, it is set to 300
When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 400, it is set to 400

So it is working now, but be aware that it rounds the values to 100.

**Comment by s4nf4n** [comment]
Thank you @groenmarsmannetje . I will try 5o confirm tomorrow. 

@drzony can I actually debug herdsmen-converters?

**Comment by s4nf4n** [comment]
> I tried setting Boost time with latest dev build. And now it is changing.
> 
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 1, it is set to 0
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 60, it is set to 0
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 100, it is set to 100
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 200, it is set to 200
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 240, it is set to 200
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 260, it is set to 200
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 300, it is set to 300
> When I publish zigbee2mqtt/kantoor_thermostaat/set/boost_time with payload 400, it is set to 400
> 
> So it is working now, but be aware that it rounds the values down to multiple of 100.

With a freshly pulled dev build I can set boost_time now as well. It behaves exactly like @groenmarsmannetje said.

**Comment by drzony** [comment]
@s4nf4n Can you close this issue then? Exposes in web interface are still experimental, so those problems should either be in #4266 or a separate issue.

**Comment by s4nf4n** [comment]
Ok. Thanks for helping.

`comfort_temperature`, `eco_temperature`, `boost_time` can be set successfully now.
