### ISSUE TITLE
Saswell SEA802 TRV program Schedule mode feature

### ISSUE THREAD

**Issue by r-glebov** [Koenkk/zigbee2mqtt#5257]
## Is your feature request related to a problem? Please describe

This feature request is about possibility to program schedule mode with time and temperatures user needs, but not the ones which are prebuilt, e.g. 16 degrees after 10pm each day. Currently only default temperature values are available for Schedule mode, which makes this integration not so usable. The other thing I noticed in [documentation](https://www.zigbee2mqtt.io/devices/SEA802-Zigbee.html#saswell-sea802-zigbee), is that there is only one value for "preset" property, which is "Schedule", and that looks strange, I guess there should be "manual" too.

Had to switch back to Tuya zigbee hub to do such adjustments.

<img src="https://user-images.githubusercontent.com/8741712/101828902-79097a80-3b32-11eb-9cc0-b1b3f15d4159.png" width="250" height="450">

## Additional context

And one more thing, not sure if it is possible to change temperature calibration value, at least there is no word in [docs](https://www.zigbee2mqtt.io/devices/SEA802-Zigbee.html#saswell-sea802-zigbee) about that.

**Comment by dev-2-4-h** [comment]
Hi 
I have an adapter that works, I have no knowledge how to submit the code to git but here is a zip-file containing the code.

[saswell.zip](https://github.com/Koenkk/zigbee2mqtt/files/5747814/saswell.zip)

Place the folder 'saswell' into the folder 'adapters' and edit '__init__.py' adding '`from adapters.saswell import saswell_adapters`' and '`**saswell_adapters,`'

Once done - pair the TRV - you will find several new devices.

I could not find a way to actually code the TRV in the way the Tuya app does.
This maybe possible for someone with more knowledge, however this works for me.

**Here are the new devices and their function:**
- SWITCH - **Device**, this is the on or off switch for the TRV 
- SWITCH - **Schedule**, this defines the mode or who controls the Schedule. 'Device' means AUTO mode, 'Domoticz' means MANUAL mode.
- SWITCH - **Away**, switches between normal operation and frost protection. 
- UTILITY - **Setpoint**, here you change the room temperature, use the 'Timers' as schedule.
- TEMPERATURE - **Temperature**, the actual (local) temperature of the area the TRV is installed.

In my home I use the 'Away' switch, allowing me to set the whole home into hibernation, the 'Setpoint' to control the temperature and the temperature sensor for information. I found no use for the other two switches. I simply set the TRV manually to the mode 'MANU'. 

Please share any feedback or ask questions about this solution directly, outside this Issue Tracker.
I created a new topic here: https://zigbee2mqtt.discourse.group/t/domoticz-saswell-sea802-trv/1926?u=screwitfix

**Comment by dev-2-4-h** [comment]
Hi, 
as I understand the zigbee2mqtt project has no graphical user interface. There is one project ( https://github.com/yllibed/Zigbee2MqttAssistant ) that provides a gUI but even for them, this would be off-topic.

This Blog ( https://medium.com/@dzegarra/zigbee2mqtt-how-to-add-support-for-a-new-tuya-based-device-part-1-b20227251d46 ) may provide some additional information.

However, I use Domoticz to control the SEA802 TRV directly, bypassing the device own programming by changing the 'SETPOINT' with my timer (Schedule) function. More info here: https://zigbee2mqtt.discourse.group/t/domoticz-saswell-sea802-trv/1926
