### ISSUE TITLE
CC2652, Eurotronic SPZB0001 'MAC no ack' (233))' or MAC transaction expired' (240))'

### ISSUE THREAD

**Issue by TIMSCHMITZ** [Koenkk/zigbee2mqtt#5272]
# Bug Report
## What happened
Paired Thermostat 
Vendor
Eurotronic
Model
SPZB0001
2 works 2 get Mac error while changing Temperatur via hassio 
## What did you expect to happen
The thermostat sets the given temperature
## How to reproduce it (minimal and precise)
Via Hassio Webfrontend set the Temperatur in Lovelace or via zigbee2mqtt webui change the occupied_heating_setpoint
The following error shows up in logs:

Zigbee2MQTT:error 2020-12-12 08:01:00: Publish 'set' 'occupied_heating_setpoint' to '0x00158d00053d2dd3' failed: 'Error: Write 0x00158d00053d2dd3/1 hvacThermostat({"occupiedHeatingSetpoint":2450}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC no ack' (233))'

ERROR: Publish 'set' 'occupied_heating_setpoint' to 'Badtemperatur' failed: 'Error: Write 0x00158d000369786e/1 hvacThermostat({"occupiedHeatingSetpoint":2400}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC transaction expired' (240))'

The issue describes my problem with different coordinator Hardware
https://github.com/Koenkk/zigbee2mqtt/issues/2500
The given solution isn’t working so I opened a new ticket.

## Debug Info
Zigbee2MQTT version: 1.16.2.2 
Adapter hardware: CC2652
https://electrolama.com/projects/zig-a-zig-ah/
Adapter firmware version:
{"disable_led":false,"port":"/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0"},"whitelist":[]},"coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200417,"transportrev":2},"type":"zStack3x0"},

**Comment by jo930** [comment]
Interesting, I am experiencing what seems to be the same issue: I have 2 Eurotronic SPZB0001, both worked for some time, then one stopped working and when I want to adjust the temperature, I see this error in the log:

ERROR: Publish 'set' 'occupied_heating_setpoint' to 'heater_livingRoom' failed: 'Error: Write 0x00158d00053d3797/1 hvacThermostat({"occupiedHeatingSetpoint":2000}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC transaction expired' (240))'

Also, if I adjust the temperature at the device, it is not reported back to HomeAssistant (it remains unchanged).
I am running Home Assistant 2020.12.0 on a Pi4, Zigbee2mqtt version 1.16.2.2, adapter hardware CC2652 (from slaesh).
