### ISSUE TITLE
OSRAM AC03645 doesn't expose effect

### ISSUE THREAD

**Issue by Mr-Groch** [Koenkk/zigbee2mqtt#5283]
## What happened
OSRAM AC03645 (https://www.zigbee2mqtt.io/devices/AC03645.html) doesn't expose effect, but it is working when I publish {"effect": "okay"} (and "breathe", "blink", etc) to it.

## What did you expect to happen
Effect attribute should be exposed for this bulb

## How to reproduce it (minimal and precise)
Observe that after pairing, there is no effect exposed, but pubisging set effect to it is working

## Debug info
Zigbee2MQTT version: 1.16.2 
Adapter hardware:  CC26X2R1 zzh!
Adapter firmware version: 20201113

**Comment by Koenkk** [comment]
Fixed, docs will be updated with next z2m release.
