### ISSUE TITLE
Add Support for Lidl ZigBee Plugs (UK)

### ISSUE THREAD

**Issue by bedfelllow** [Koenkk/zigbee2mqtt#5284]
https://www.lidl.co.uk/our-products/smart-home
https://zigbeealliance.org/zigbee_products/lidl-home-smart-plug/
https://i.ibb.co/HqgdC3R/IMG-20201213-095206.jpg

Appears to be the UK variant of this: https://www.zigbee2mqtt.io/devices/HG06337.html
..
WARNING:  `Device 
'0x842e14fffecd080c' with Zigbee model 'TS011F' and manufacturer name 
'_TZ3000_00mk2xzy' is NOT supported, please follow 
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`
..

**Comment by Koenkk** [comment]
Already supported in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by danstreeter** [comment]
Thanks @Koenkk - Is there a commit I can track for when it merges so I can shift back onto stable?

**Comment by Koenkk** [comment]
You can switch back to stable when a new version of z2m gets released (1 january)

**Comment by emarcin** [comment]
any news about the support?

**Comment by Koenkk** [comment]
Supported in Zigbee2MQTT 1.17.0

**Comment by bedfelllow** [comment]
> any news about the support?

An update to HomeAssistant plugin has been released. I installed it yesterday and it works fine with these now.

@Koenkk, thanks for the update.

**Comment by emarcin** [comment]
Now it works! Thanks a lot!

**Comment by ximon** [comment]
Does this device report its state when the button on the device is pressed? I.e are we able to get updates when the socket is turned off via its built in button?

**Comment by bedfelllow** [comment]
> Does this device report its state when the button on the device is pressed? I.e are we able to get updates when the socket is turned off via its built in button?

Zigbee2mqtt reports the state correcting when the button is pressed.

**Comment by ximon** [comment]
> > Does this device report its state when the button on the device is pressed? I.e are we able to get updates when the socket is turned off via its built in button?
> 
> Zigbee2mqtt reports the state correcting when the button is pressed.

Is there something I need to change / do for this to work? I dont get state updates if I change the state of the socket via its built in button - I dont see any traffic in the logs when pressing the button after enabling logging.

**Comment by bedfelllow** [comment]
> 
> 
> > > Does this device report its state when the button on the device is pressed? I.e are we able to get updates when the socket is turned off via its built in button?
> > 
> > 
> > Zigbee2mqtt reports the state correcting when the button is pressed.
> 
> Is there something I need to change / do for this to work? I dont get state updates if I change the state of the socket via its built in button - I dont see any traffic in the logs when pressing the button after enabling logging.

I never had to change any configuration, it just worked as default.

If you open the device in Zigbee2MQTT web UI, in the 'Exposes' tab do you see the switch toggle when you press the socket button?

![image](https://user-images.githubusercontent.com/20281271/105916474-dbf29a80-6028-11eb-868a-5f329f372c60.png)
![image](https://user-images.githubusercontent.com/20281271/105916531-f7f63c00-6028-11eb-8635-7bb36fd4371c.png)

**Comment by ximon** [comment]
It doesn't toggle automatically, but it does when i click the refresh button next to 'state'
I have four of these devices and its the same for all four.

**Comment by RobvanSuilen** [comment]
I have the same problem, using a raspberry pi, homeassistant, mosquitto and zigbee2mqtt
