### ISSUE TITLE
OSRAM 4058075816459 (4x Switch) - Actions missing

### ISSUE THREAD

**Issue by Jogobo** [Koenkk/zigbee2mqtt#5286]
I started a new test with the Osram 4X Switch. I came across the issue that all button actions are send except for "left_bottom_hold" and "left_bottom_release".
Another issue with this switch: the "hold" action for "right_top" and "right_bottom" is send twice
And last: there is no battery information (example: "{"action":"right_bottom_click","linkquality":21})

**Comment by UweLoyal** [comment]
I have also the same effect with "hold" action for "right_top" and "right_bottom" sending twice

Rgds
UweLoyal
