### ISSUE TITLE
Devices no longer log to zigbee2mqtt/bridge/log (this breaks Z2M dashboard)

### ISSUE THREAD

**Issue by rekcodocker** [Koenkk/zigbee2mqtt#5289]
### Situation after upgrade to 1.6.2:
I just upgraded to 1.6.2 from 1.6.1.
It seems that behaviour for logging the devicelist has changed.   If so then this breaks Z2M dashboard.

### Error:
I use Z2M dashboard.  
It no longer list devices. A bit of debugging shows that it expects a devicelist in "zigbee2mqtt/bridge/log".  It triggers this every 5 seconds by posting in "zigbee2mqtt/bridge/config/devices/get" 

### Analysis:
However, the devicelist is reported in "zigbee2mqtt/bridge/config/devices"  and not in "zigbee2mqtt/bridge/log".

### Inconsistency in documentation:
The documentation of the MQTT topics reads:

**zigbee2mqtt/bridge/log #**
Zigbee2MQTT will output log to this endpoint.
"devices": a list of all devices, this message can be triggered by sending a message to zigbee2mqtt/bridge/config/devices/get (payload doesn’t matter).

**zigbee2mqtt/bridge/config/devices/get #**
Allows you to retrieve all connected devices. Publish an empty payload to this topic. Response will be published to zigbee2mqtt/bridge/config/devices.

So, one says "Post to config/devices/get" and the results will be posted in "/bridge.log".  The other says "result will be posted in bridge/config/devices". 

### Suggested fix:
I think posting the device-list to bridge/config/devices is much better than just vomiting it to bridge/log. 
However, groups are still reported in bridge/log.
Suggested fix:

1. Update the reporting of groups to the new standard (log it in bridge/groups)
2. Notify the author of Z2M
3. Update the documentation on the MQTT topics.

**Comment by Koenkk** [comment]
Fixed (behaviour is same as 1.16.1 now).

Note that this api will be deprecated with the next Z2M release and will be replaced with the new api (https://github.com/Koenkk/zigbee2mqtt/issues/3281)
