### ISSUE TITLE
Requesting a config option to opt-out from json_attributes_topic / Make entities attribute-less

### ISSUE THREAD

**Issue by u17194907425** [Koenkk/zigbee2mqtt#5293]
## Is your feature request related to a problem? Please describe
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I'm always frustrated when I look at the Home Assistant Database file size where I save stated of ZigBee-related entities (e.g. smart switches). The size is quite big because each entity state is accompanied (and saved into the DB) with all the attributes in JSON format.

E.g. with a socket switch entity `switch.bedroom_humidifier_socket` there is always the following line of attributes:
`{"consumption": 2.8, "energy": 2.8, "linkquality": 69, "power": 0, "state": "OFF", "temperature": 31, "voltage": null, "friendly_name": "bedroom_humidifier_socket_switch"}`

So even if I want to keep information about state of the switch (on/off), HA will save any change in the attribute. Meaning every time a `linkquality` changes, there is a new line inside the DB. Looks like this: https://i.imgur.com/Nszk2N9.png

As far as I understand the root cause for this is the configuration for MQTT discovery saying
`"json_attributes_topic": "zigbee2mqtt/bedroom_humidifier_socket"` for every entity (switch, sensors of power consumption, temperature and so on. 

## Describe the solution you'd like
_A clear and concise description of what you want to happen._
I would like to have a configurable option to opt-out from all the attributes in the discovered entities.

E.g. I go into the config file and say `"json_attributes_topic_enabled": false` and all the ZigBee devices are discovered without attributes.

## Describe alternatives you've considered
_A clear and concise description of any alternative solutions or features you've considered._
I was thinking about manually configuring the sensors and switches, and probably I'll try going this way as a workaround.

## Additional context
_Add any other context or screenshots about the feature request here._
None

**Comment by Koenkk** [comment]
You can do this by adding the following to your `configuration.yaml`.

```yaml
device_options:
  homeassistant:
    json_attributes_topic: null
```
