### ISSUE TITLE
Müller Licht 404037 flickers irregularily - looks similiar to effect "channel change"

### ISSUE THREAD

**Issue by XRyu** [Koenkk/zigbee2mqtt#5295]
## What happened
I own several Müller Licht Lights - most of them are of the Warm+Cold-white Retro LED Bulbs 404037 - they irregularily flicker - the effect looks veeeery similiar to the integrated effect "channel change". This happens in every state, even when the lights state is off. In the logs i dont see what this might be. I just gathered the log after it happened - attached below. This happened to the light "Licht - Wohnzimmer Essbereich - Esstisch - Filament Q" = 0x00158d00013b1dce

## What did you expect to happen
no flickering :)
## How to reproduce it (minimal and precise)
Use Müller Licht - 404037
## Debug info
Zigbee2MQTT version: 1.16.2 commit: 04c15f7
Adapter hardware: CC1352P-2
Adapter firmware version: 20201113

´´´
Zigbee2MQTT:info  2020-12-13 23:44:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'Licht - Flur' failed: 'Error: Command 0x000b57fffe98737e/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":13,\"transtime\":10}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Timeout - 9746 - 1 - 202 - 8 - 11 after 10000ms)'","meta":{"friendly_name":"Licht - Flur"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:debug 2020-12-13 23:44:46: Publishing 'set' 'transition' to 'Licht - Flur'
Zigbee2MQTT:debug 2020-12-13 23:44:53: Received Zigbee message from 'Licht - Arbeitszimmer Thomas - Schreibtisch - Filament O', type 'attributeReport', cluster 'lightingColorCtrl', data '{"currentY":21396}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:44:53: MQTT publish: topic 'zigbee2mqtt/Licht - Arbeitszimmer Thomas - Schreibtisch - Filament O', payload '{"brightness":24,"color":{"x":0.3151,"y":0.3265},"color_temp":153,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Arbeitszimmer Thomas - Schreibtisch - Filament O","hardwareVersion":1,"ieeeAddr":"0x00158d00013dcc45","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":16243,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":32031,"last_seen":1607899493128,"linkquality":60,"state":"OFF"}'
Zigbee2MQTT:debug 2020-12-13 23:44:53: Received MQTT message on 'zigbee2mqtt/Licht - Flur/set' with data '{"state": "OFF", "transition": 1.0}'
Zigbee2MQTT:debug 2020-12-13 23:44:53: Publishing 'set' 'transition' to 'Licht - Flur'
Zigbee2MQTT:debug 2020-12-13 23:44:53: Publishing 'set' 'state' to 'Licht - Flur'
Zigbee2MQTT:debug 2020-12-13 23:44:56: Received Zigbee message from 'Licht - Arbeitszimmer Thomas - Decke - Filament N', type 'attributeReport', cluster 'lightingColorCtrl', data '{"currentY":21396}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:44:56: MQTT publish: topic 'zigbee2mqtt/Licht - Arbeitszimmer Thomas - Decke - Filament N', payload '{"brightness":24,"color":{"x":0.3151,"y":0.3265},"color_temp":153,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Arbeitszimmer Thomas - Decke - Filament N","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1ecc","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":41365,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":32257,"last_seen":1607899496035,"linkquality":57,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:44:58: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament J', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":26}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:44:58: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament J', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament J","hardwareVersion":1,"ieeeAddr":"0x00158d00013dc5c8","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":23660,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":13253,"last_seen":1607899498156,"linkquality":42,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:01: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:01: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament Q","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1dce","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":6004,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":98638,"last_seen":1607899501889,"linkquality":42,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:06: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', type 'attributeReport', cluster 'lightingColorCtrl', data '{"colorTemperature":500}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:06: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament Q","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1dce","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":6004,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":5015,"last_seen":1607899506904,"linkquality":48,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:09: Received Zigbee message from 'Licht - Outdoor Lightstrip A', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":655368546,"imageType":1793,"manufacturerCode":4454}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:14: Received Zigbee message from 'Licht - Filament I', type 'attributeReport', cluster 'lightingColorCtrl', data '{"colorTemperature":500}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:14: MQTT publish: topic 'zigbee2mqtt/Licht - Filament I', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4174},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Filament I","hardwareVersion":1,"ieeeAddr":"0x00158d00013dbf4b","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":43697,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":142845,"last_seen":1607899514534,"linkquality":51,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:14: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":26}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:14: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament Q', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament Q","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1dce","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":6004,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":8090,"last_seen":1607899514995,"linkquality":39,"state":"ON"}'
Zigbee2MQTT:error 2020-12-13 23:45:16: Publish 'set' 'state' to 'Licht - Flur' failed: 'Error: Command 0x000b57fffe98737e/1 genLevelCtrl.moveToLevelWithOnOff({"level":0,"transtime":10}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 9746 - 1 - 206 - 8 - 11 after 10000ms)'
Zigbee2MQTT:debug 2020-12-13 23:45:16: Error: Command 0x000b57fffe98737e/1 genLevelCtrl.moveToLevelWithOnOff({"level":0,"transtime":10}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 9746 - 1 - 206 - 8 - 11 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Zigbee2MQTT:info  2020-12-13 23:45:16: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Licht - Flur' failed: 'Error: Command 0x000b57fffe98737e/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":0,\"transtime\":10}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Timeout - 9746 - 1 - 206 - 8 - 11 after 10000ms)'","meta":{"friendly_name":"Licht - Flur"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:debug 2020-12-13 23:45:25: Received Zigbee message from 'Licht - Filament I', type 'attributeReport', cluster 'lightingColorCtrl', data '{"currentX":34517}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:25: MQTT publish: topic 'zigbee2mqtt/Licht - Filament I', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4174},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Filament I","hardwareVersion":1,"ieeeAddr":"0x00158d00013dbf4b","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":43697,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":10866,"last_seen":1607899525400,"linkquality":51,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:25: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament R', type 'attributeReport', cluster 'lightingColorCtrl', data '{"colorTemperature":500}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:25: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament R', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament R","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1b0d","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":28386,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":87418,"last_seen":1607899525736,"linkquality":0,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:26: Received Zigbee message from 'Licht - Filament I', type 'attributeReport', cluster 'lightingColorCtrl', data '{"currentY":27347}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:26: MQTT publish: topic 'zigbee2mqtt/Licht - Filament I', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Filament I","hardwareVersion":1,"ieeeAddr":"0x00158d00013dbf4b","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":43697,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":954,"last_seen":1607899526354,"linkquality":51,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:34: Received Zigbee message from 'Licht - Outdoor Spots B', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":655368546,"imageType":1795,"manufacturerCode":4454}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:35: Received Zigbee message from 'Licht - Outdoor Spots A', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":655368546,"imageType":1795,"manufacturerCode":4454}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:36: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament R', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:36: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament R', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament R","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1b0d","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":28386,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":10980,"last_seen":1607899536716,"linkquality":15,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:36: Received Zigbee message from 'Licht - Outdoor Spots C', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":655368546,"imageType":1795,"manufacturerCode":4454}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:47: Received Zigbee message from 'Licht - Arbeitszimmer Thomas - Schrankbeleuchtung (C)', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":24}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:47: MQTT publish: topic 'zigbee2mqtt/Licht - Arbeitszimmer Thomas - Schrankbeleuchtung (C)', payload '{"brightness":24,"device":{"applicationVersion":17,"dateCode":"20170529","friendlyName":"Licht - Arbeitszimmer Thomas - Schrankbeleuchtung (C)","hardwareVersion":1,"ieeeAddr":"0x680ae2fffe8012d7","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","model":"ICPSHC24-10EU-IL-1","networkAddress":33373,"powerSource":"Mains (single phase)","softwareBuildID":"1.2.245","stackVersion":87,"type":"Router","zclVersion":1},"elapsed":145636,"last_seen":1607899547131,"linkquality":63,"state":"ON","update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:debug 2020-12-13 23:45:49: Received Zigbee message from 'Licht - Wohnzimmer Essbereich - Esstisch - Filament R', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":26}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:49: MQTT publish: topic 'zigbee2mqtt/Licht - Wohnzimmer Essbereich - Esstisch - Filament R', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Wohnzimmer Essbereich - Esstisch - Filament R","hardwareVersion":1,"ieeeAddr":"0x00158d00013b1b0d","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":28386,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":13241,"last_seen":1607899549957,"linkquality":18,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:50: Received Zigbee message from 'Licht - Terrasse - Filament C', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:50: MQTT publish: topic 'zigbee2mqtt/Licht - Terrasse - Filament C', payload '{"brightness":229,"device":{"applicationVersion":16,"dateCode":"20190705-350","friendlyName":"Licht - Terrasse - Filament C","hardwareVersion":1,"ieeeAddr":"0xccccccfffe2e4612","manufacturerID":4454,"manufacturerName":"innr","model":"RF 263","networkAddress":53232,"powerSource":"Mains (single phase)","softwareBuildID":"2.1","stackVersion":101,"type":"Router","zclVersion":3},"elapsed":268575,"last_seen":1607899550415,"linkquality":15,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:53: Received Zigbee message from 'Licht - Wannen-Bad - Decke A (GU10_A)', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":285343746,"imageType":20497,"manufacturerCode":4635}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:54: Received Zigbee message from 'Licht - Filament I', type 'attributeReport', cluster 'genLevelCtrl', data '{"currentLevel":26}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-12-13 23:45:54: MQTT publish: topic 'zigbee2mqtt/Licht - Filament I', payload '{"brightness":26,"color":{"x":0.5267,"y":0.4173},"color_temp":500,"device":{"applicationVersion":1,"dateCode":"20190601","friendlyName":"Licht - Filament I","hardwareVersion":1,"ieeeAddr":"0x00158d00013dbf4b","manufacturerID":4137,"manufacturerName":"MLI","model":"404037","networkAddress":43697,"powerSource":"Mains (single phase)","softwareBuildID":"TDU18650B01","stackVersion":1,"type":"Router","zclVersion":2},"elapsed":28638,"last_seen":1607899554992,"linkquality":51,"state":"ON"}'
Zigbee2MQTT:debug 2020-12-13 23:45:55: Received Zigbee message from 'Licht - Terrasse - Filament F', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16782596,"imageType":274,"manufacturerCode":4107}' from endpoint 11 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:45:55: Check if update available for '0x0017880108a04723' (LWV001)
Zigbee2MQTT:debug 2020-12-13 23:45:55: Is new image available for '0x0017880108a04723', current '{"fieldControl":0,"manufacturerCode":4107,"imageType":274,"fileVersion":16782596}', latest meta '{"fileVersion":16782596,"fileSize":420884,"url":"https://storage.googleapis.com/firmware-hue/100b-112/16782596/6eeaf8f7-e2cc-4881-b58d-c985c409df16/100B-0112-01001504-ConfLightBLE-Lamps-EFR32MG13.zigbee"}'
Zigbee2MQTT:debug 2020-12-13 23:45:55: Update available for '0x0017880108a04723': NO
Zigbee2MQTT:info  2020-12-13 23:45:55: MQTT publish: topic 'zigbee2mqtt/Licht - Terrasse - Filament F', payload '{"brightness":229,"device":{"applicationVersion":2,"dateCode":"20200124","friendlyName":"Licht - Terrasse - Filament F","hardwareVersion":1,"ieeeAddr":"0x0017880108a04723","manufacturerID":4107,"manufacturerName":"Philips","model":"929002241201","networkAddress":48521,"powerSource":"Mains (single phase)","softwareBuildID":"1.65.9_hB3217DF4","stackVersion":1,"type":"Router","zclVersion":2},"last_seen":1607899555719,"linkquality":12,"state":"ON","update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:debug 2020-12-13 23:46:05: Received Zigbee message from 'Licht - Terrasse - Filament F', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16782596,"imageType":274,"manufacturerCode":4107}' from endpoint 11 with groupID 0
Zigbee2MQTT:debug 2020-12-13 23:46:15: Received Zigbee message from 'Licht - Terrasse - Filament F', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16782596,"imageType":274,"manufacturerCode":4107}' from endpoint 11 with groupID 0

**Comment by thunder-62** [comment]
Hi, I had a similar behaviour when my Paulmann Amaris LED Panel was only paired with the coordinator but not bound to a Switch. Might be an idea to bind a wwitch directly to your device....

**Comment by XRyu** [comment]
Thank you for the tip @thunder-62  :)
But currently i dont want to bind any switches directly (primary using the IKEA 1810 with HA-appdeamon-configs).
But when Paulman has this too, there might be an issue in some kind of Communication with Z2M :)

**Comment by XRyu** [comment]
still happening

**Comment by Koenkk** [comment]
I don't see much activity from this device from the log, don't think it comes from Zigbee2MQTT itself. Did it crash at this time?

```js

Zigbee2MQTT:debug 2021-01-21 23:24:23: Received Zigbee message from 'Licht - Schlafzimmer - Decke - Filament K', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

2021-01-21T22:24:23.816Z zigbee-herdsman:controller:endpoint DefaultResponse 0x00158d00013d3a1d/1 6(10, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null})

2021-01-21T22:24:23.816Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0x00158d00013d3a1d:47011/1 (0,0,1)
```

I previously saw flickers with IKEA bulb which turned out to be a crashing/rebooting bulb (issue in the firmware). Hard to judge if that is also the case here.

**Comment by XRyu** [comment]
Yes, this was the time when it happened. (also to mention - but definitely minor bug -  the time-discrepancy between the Zigbee2Mqtt and Herdsman Debug log :D)

Hmmm, i am not sure. When i had these at the "old" Hue Bridge it worked without this. And some versions ago it did not happen. So not sure about this.

i also seem to have this happen irregulary (sadly pretty often), and after restarting the Coordinator everything is fine for around a half up to two days when i have to restart the container again.


Is there anything i could enable in docker, to get a even better trace where you might see more of the communications of the problematic bulbs?

**Comment by Koenkk** [comment]
@XRyu sniffing the traffic of the moment it flickers is the best way to debug this I think: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by XRyu** [comment]
@Koenkk Thank you! I will try to capture when it happens next time :)
I have setuo the sniffer right now, i can see the Zigbee Data flowing - but do you have any idea why so many of the lines show "Malformed Packet" ? :)

![image](https://user-images.githubusercontent.com/131995/105746673-087eb780-5f40-11eb-8df4-17d1b9706167.png)

**Comment by Koenkk** [comment]
This happens when you are out of range. Moving closer to the device sending it should fix it.

**Comment by DerMega** [comment]
> Hi, I had a similar behaviour when my Paulmann Amaris LED Panel was only paired with the coordinator but not bound to a Switch. Might be an idea to bind a switch directly to your device....

@thunder-62 what do you mean by "switch"? Do I have to buy a physical switch to get rid of that problem?
I recently bought a Paulmann Amaris and it flashes while beeing switched off like every 10 Minutes :(

**Comment by tbrtje** [comment]
Hi, 

> > Hi, I had a similar behaviour when my Paulmann Amaris LED Panel was only paired with the coordinator but not bound to a Switch. Might be an idea to bind a switch directly to your device....
> 
> @thunder-62 what do you mean by "switch"? Do I have to buy a physical switch to get rid of that problem? I recently bought a Paulmann Amaris and it flashes while beeing switched off like every 10 Minutes :(
> 
> Link Quality is 60 what is strange because its 1.5m to the next zigbee device.

Hi,
I am having the same issue with my Paulmann LED Panel. Have you been able to resolve this issue?

Best regards

**Comment by thunder-62** [comment]
> Hi,
> 
> > > Hi, I had a similar behaviour when my Paulmann Amaris LED Panel was only paired with the coordinator but not bound to a Switch. Might be an idea to bind a switch directly to your device....
> > 
> > 
> > @thunder-62 what do you mean by "switch"? Do I have to buy a physical switch to get rid of that problem? I recently bought a Paulmann Amaris and it flashes while beeing switched off like every 10 Minutes :(
> > Link Quality is 60 what is strange because its 1.5m to the next zigbee device.
> 
> Hi, I am having the same issue with my Paulmann LED Panel. Have you been able to resolve this issue?
> 
> Best regards

I paired it to a Zigbee Switch and it worked. Today, I use the Amaris with the Paulman Remote as I had repetitive issues with it :-(

**Comment by tbrtje** [comment]
> I paired it to a Zigbee Switch and it worked. Today, I use the Amaris with the Paulman Remote as I had repetitive issues with it :-(

What were the other issues you had?
I fixed the flickering by disabling auto_join.
The flickering only occurs when new devices are allowed to join the network.

**Comment by GregWoods** [comment]
> 

PaulMann Amaris RGBW. Flickers every 6-7 minutes, as regular as clockwork!
I thought I'd fixed by having the "Disable Join (All)" option selected. 
I also had the Home Assistnant Integration "Enable newly added entities." set to DISABLED
I was convinced it was this second setting that had fixed it.

To my disappointment, after a reboot of my docker host, the lamp is back to flicking on/off/on every 6-minutes.
My settings are as they were above.

Regarding pairing the remote....
I do have the PaulMann remote somewhere. Can I pair it after it has already been paired to the coordinator?
