### ISSUE TITLE
Conbee2 does not report to the map of devices connected to it to the map of zigbee2mqtt

### ISSUE THREAD

**Issue by ctm514** [Koenkk/zigbee2mqtt#5296]
The devices connected to Conbee2 appear loose on the map because conbee2 does not inform the zigbee2mqtt map during a search for devices that are connected to it ... How to solve this?

**Comment by Koenkk** [comment]
Englisch only

**Comment by ctm514** [comment]
problem fixed, can you open the topic?

**Comment by MattWestb** [comment]
deCONZ adapters have 2 firmware bugs that making the map being wrong.
1 (sleeping) end devices that is direct connected to the coordinator is not reported as children => they is not showing up or disappearing in the map.
2 Pulling routers for their neighbour the LQI is not the same as received messages with LQI (see the main thread for Cornbee implantation).
