### ISSUE TITLE
Silvercrest FB20-002  typo in state name

### ISSUE THREAD

**Issue by cm610** [Koenkk/zigbee2mqtt#5297]
https://www.zigbee2mqtt.io/devices/FB20-002.html#action-enum

The state name **brightenss_step_up** is wrong, the name should be **brightness_step_up**.

Due to this typo the respective button action is not recognized.

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

Docs will be updated with next release.
