### ISSUE TITLE
Sunricher SR-ZG9040A-S

### ISSUE THREAD

**Issue by automaten** [Koenkk/zigbee2mqtt#5303]
Tested out on:

Zigbee2MQTT:info  2020-12-14 17:55:51: Starting Zigbee2MQTT version 1.16.2-dev (commit #dd68d1d)
Zigbee2MQTT:info  2020-12-14 17:55:51: Starting zigbee-herdsman (0.13.41)

## Information about the device + link
[Sunricher Zigbee dimmer](https://www.sunricher.com/media/resources/manual/SR-ZG9040A%20instruction.pdf)

## data/database.db entry of the device
{"id":12,"type":"Router","ieeeAddr":"0xbc33acfffee2f8a2","nwkAddr":63650,"manufId":4107,"manufName":"Sunricher","powerSource":"Mains (single phase)","modelId":"HK-SL-DIM-A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,1794,2820,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"HK-SL-DIM-A","manufacturerName":"Sunricher","powerSource":1,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.5.3_r49"}}},"binds":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"NULL","swBuildId":"2.5.3_r49","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1607965130759}

**Comment by Koenkk** [comment]
Added.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
