### ISSUE TITLE
ZigBee Smart Power Strip TZ3000_o005nuxx

### ISSUE THREAD

**Issue by toko007** [Koenkk/zigbee2mqtt#5308]
Hello,
Could you please add this device to servise zigbee2mqtt?

Link: https://www.aliexpress.com/item/4000981707898.html?spm=a2g0s.9042311.0.0.27425c0fbf00pe

Zigbee2MQTT:warn  2020-12-15 10:03:40: Device '0x60a423fffe0435f2' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_o005nuxx' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

{
fingerprint: [{modelID: 'TS011F', manufacturerName: '_TZ3000_o005nuxx'}],
model: 'SM-SO306E/K/M',
vendor: 'UseeLink',
description: '4 gang switch, with USB',
exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3'), e.switch().withEndpoint('l4'), e.switch().withEndpoint('l5')],
extend: generic.switch,
meta: {configureKey: 1, multiEndpoint: true},
configure: async (device, coordinatorEndpoint) => {
for (const ID of [1, 2, 3, 4, 5]) {
await bind(device.getEndpoint(ID), coordinatorEndpoint, ['genOnOff']);
}
},

**Comment by Koenkk** [comment]
Device is already supported in the dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
