### ISSUE TITLE
Trust ZYCT-202 not recognized

### ISSUE THREAD

**Issue by efmuurman** [Koenkk/zigbee2mqtt#5313]
https://www.zigbee2mqtt.io/devices/ZYCT-202.html#trust-zyct-202
so i think should be supported. But in database is the following :
..

{"id":5,"type":"EndDevice","ieeeAddr":"0x00158d00038e5ff4","nwkAddr":52456,"manufId":4653,"epList":[1,2],"endpoints":{"1":{"profId":49246,"epId":1,"devId":2080,"inClusterList":[0,4,3,6,8,4096],"outClusterList":[0,4,3,6,8,4096],"clusters":{},"binds":[],"meta":{}},"2":{"epId":2,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1608057771338}

..

**Comment by timoline** [comment]
perhaps a relation with  #5170
