### ISSUE TITLE
TuYa TS011F based switch unsupported in 1.16.2

### ISSUE THREAD

**Issue by poonab** [Koenkk/zigbee2mqtt#5333]
## What happened

Lidl TuYa TS011F based switch that works in 1.16.1 is shown as unsupported in 1.16.2

## What did you expect to happen

Device to continue working after upgrade

## How to reproduce it (minimal and precise)

Upgrade from 1.16.1 to 1.16.2

## Debug info
Zigbee2MQTT version: 
Adapter hardware: CC2531
Adapter firmware version:

**Comment by Koenkk** [comment]
should already be fixed in the latest dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

If not, re-open and provide your data/database.db entry of this device.
