### ISSUE TITLE
Heiman COsensor-EF-3.0 unsupported

### ISSUE THREAD

**Issue by patrickarkenbout** [Koenkk/zigbee2mqtt#5335]
Hi,

I use more heiman devices without a problem, with my last order i ordered 1 COsensor without looking in the list of support devices. Now i turn out that this devices is not supported

Device '0xbc33acfffe01087e' with Zigbee model 'COSensor-EF-3.0' and manufacturer name 'HEIMAN' is NOT supported

## Information about the device + link
According the site it is a model M414

https://www.aliexpress.com/item/4000209418201.html?spm=a2g0o.productlist.0.0.30f23bf3fNxbm2&algo_pvid=d0b6bf95-e364-4c04-950e-9845f6a7a770&algo_expid=d0b6bf95-e364-4c04-950e-9845f6a7a770-0&btsid=2100bdca16082402888164765ecb88&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by sjorge** [comment]
Try updating this block in devices.js:

```
    {
        zigbeeModel: ['COSensor-EM', 'COSensor-N'],
        model: 'HS1CA-E',
        vendor: 'HEIMAN',
        description: 'Smart carbon monoxide sensor',
        fromZigbee: [fz.ias_carbon_monoxide_alarm_1, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
        exposes: [e.carbon_monoxide(), e.battery_low(), e.tamper(), e.battery()],
    },
```

To the following

```
    {
        zigbeeModel: ['COSensor-EM', 'COSensor-N', 'COSensor-EF-3.0'],
        model: 'HS1CA-E',
        vendor: 'HEIMAN',
        description: 'Smart carbon monoxide sensor',
        fromZigbee: [fz.ias_carbon_monoxide_alarm_1, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
        exposes: [e.carbon_monoxide(), e.battery_low(), e.tamper(), e.battery()],
    },
```

**Comment by patrickarkenbout** [comment]
It took me a while to figure out how to edit devices.js. The above suggestion did not seem to work. Finally I copied and modified the above config to and add this to devices.js
{
         zigbeeModel: ['COSensor-EF-3.0'],
         model: 'M414',
         vendor: 'HEIMAN',
         description: 'Smart carbon monoxide sensor',
         fromZigbee: [fz.ias_carbon_monoxide_alarm_1, fz.battery],
         toZigbee: [],
         meta: {configureKey: 1},
         configure: async (device, coordinatorEndpoint) => {
             const endpoint = device.getEndpoint (1);
             await bind (endpoint, coordinatorEndpoint, ['genPowerCfg']);
             await configureReporting.batteryPercentageRemaining (endpoint);
         },
         exposes: [e.carbon_monoxide (), e.battery_low (), e.tamper (), e.battery ()],
     },
This turned out to work.

**Comment by sjorge** [comment]
Odd, as there doesn't seem to be any difference in fromZigbee and configure step between the one I suggested and the one that ended up working.

To get this in the next release you can do a PR against https://github.com/Koenkk/zigbee-herdsman-converters to get it added. Or wait, koenkk usually picks them up form here when he has time.

**Comment by patrickarkenbout** [comment]
I will try again, maybe i made a mistake.

**Comment by sjorge** [comment]
> I will try again, maybe i made a mistake.

The only difference is that the one I listed was grouped with 2 other Heiman CO sensors that had a similar model name:
`COSensor-EM`, `COSensor-N`. 

But if it is your first time messing with devices.js, things are indeed confusing :)

**Comment by patrickarkenbout** [comment]
Now it works, I made a typo or something else. It worked with your suggestion. Thank you for your help

**Comment by szaman-89** [comment]
@Koenkk Did you include this fix in current version of z2m? I paired this device with zigbee2mqtt but still "Unsupported".

**Comment by Koenkk** [comment]
@szaman-89 it is in 1.17.0, if you are on this version share your data/database.db entry of this device

**Comment by szaman-89** [comment]
> @szaman-89 it is in 1.17.0, if you are on this version share your data/database.db entry of this device

Entry of this device:

{"id":9,"type":"Unknown","ieeeAddr":"0x000d6f0014f90f70","nwkAddr":22552,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1611167575864}

**Comment by Koenkk** [comment]
@szaman-89 the interview failed, force remove first through https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestdeviceremove and pair again (https://www.zigbee2mqtt.io/information/FAQ.html#interview-fails)

**Comment by szaman-89** [comment]
Sensor can be paired only with combining Touchlink scan. In permit join option only z2m cant get any pairing information. After launching Touchlink scan device can be paired but became unspported.

**Comment by sjorge** [comment]
It paired pretty easy for me:
1. enable pairing
2. pull the battery pull tab
3. hold the button to enter pairing mode

It showed up a few seconds later, like maybe 10 or so.

**Comment by szaman-89** [comment]
> It paired pretty easy for me:
> 
> 1. enable pairing
> 2. pull the battery pull tab
> 3. hold the button to enter pairing mode
> 
> It showed up a few seconds later, like maybe 10 or so.
> 
> <img alt="image" width="1143" src="https://user-images.githubusercontent.com/379665/105226382-35a62100-5b60-11eb-8ad0-1b91669c0443.png">

I did exactly how you described but z2m won't find any device. Last new device was added couple days ago and everything works like a charm.

**Comment by jorismathijssen** [comment]
Did not want to make a new issue for just a question, maybe @szaman-89 or @sjorge can answer it. 

My CO sensor will not report any information. When I press the test button a payload message is send but no battery level is included.

MQTT publish: topic 'zigbee2mqtt/0x000d6f00156570ce', payload '{"battery_low":false,"carbon_monoxide":true,"linkquality":57,"tamper":false}'

![image](https://user-images.githubusercontent.com/1663370/106296511-0ffcd400-6252-11eb-8d45-50caff67767d.png)

Any suggestions?

**Comment by szaman-89** [comment]
> Any suggestions?

When did you pair co sensor? Maybe you should wait for this informations. If you did it long time ago I would try to re-pair it.

**Comment by jorismathijssen** [comment]
> > Any suggestions?
> 
> When did you pair co sensor? Maybe you should wait for this informations. If you did it long time ago I would try to re-pair it.

I just re-paired the device but last time i have waited 2 weeks :) 

Maybe this repair fixed it, lets wait a couple of hours/days
