### ISSUE TITLE
No mqtt log message while requesting device list

### ISSUE THREAD

**Issue by jchmielniak** [Koenkk/zigbee2mqtt#5341]
## What happened
No mqtt Log message while requesting device list

## What did you expect to happen
Expected is mqtt messge: 
zigbee2mqtt/bridge/log {"message": ".......", "type":"devices"

Received mqqt message:
zigbee2mqtt/bridge/config/devices [{"dateCode":"20201113","friendly_name":"Coordinator","ieeeAddr": .....

## How to reproduce it (minimal and precise)
send message:
zigbee2mqtt/bridge/config/devices/get (any payload)

## Debug info
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version: zStack3x0

**Comment by Koenkk** [comment]
Should already be fixed in the latest dev branch (https://github.com/Koenkk/zigbee2mqtt/issues/5289)  (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
