### ISSUE TITLE
Docker container not reading hidden folder

### ISSUE THREAD

**Issue by soxhi8** [Koenkk/zigbee2mqtt#5348]
## What happened
I installed the Zigbee2MQTT container with the official guide: https://www.zigbee2mqtt.io/information/docker.html
But I changed the path from `$(pwd)/data:/app/data` to `$(pwd)/.zigbee2mqtt:/app/data`, to retain a clean user-directory and know exactly what the folder is referring to.
The setup generated the folders fine, but any changes made in the configuration.yaml would not be applied at run-time. Moving the folder from `.zigbee2mqtt` to `zigbee2mqtt` fixed the problem.
## What did you expect to happen
The container to read the configuration from `$(pwd)/.zigbee2mqtt`.
## How to reproduce it (minimal and precise)
Follow the official Docker installation guide, but change the folder mapping to `$(pwd)/.zigbee2mqtt:/app/data`.
## Debug info
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531
Adapter firmware version:

**Comment by Koenkk** [comment]
Zigbee2MQTT has no knowledge of where the /app/data directory is mapped to on the host. Probably a setup or Docker problem.
