### ISSUE TITLE
1.16.2-dev (commit #c174163) breaks previous devices with Failed to call 'Receive' 'onZigbeeEvent' error

### ISSUE THREAD

**Issue by timdonovanuk** [Koenkk/zigbee2mqtt#5358]
## What happened

I pushed a button (https://www.zigbee2mqtt.io/devices/WXKG01LM.html#xiaomi-wxkg01lm) and an error is produced:

`ERROR: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'constructor' of undefined at getEntityKey (/app/node_modules/zigbee-herdsman-converters/converters/store.js:6:16) at Object.getValue (/app/node_modules/zigbee-herdsman-converters/converters/store.js:21:23) at Object.convert (/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3504:33) at /app/lib/extension/receive.js:159:41 at Array.forEach (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:158:20) at Controller.callExtensionMethod (/app/lib/controller.js:381:44))`

## What did you expect to happen

Z2M doesnt fail, and sends an event, as per previous versions (even the previous dev version was fine)

## Debug info
Zigbee2MQTT version: 1.16.2-dev (commit #c174163)
Adapter hardware:  CC1352P-2
Adapter firmware version: latests: CC1352P_2_20201026

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
