### ISSUE TITLE
Adding Centralite Plug

### ISSUE THREAD

**Issue by EagleAdam** [Koenkk/zigbee2mqtt#536]
Hi all,
I am running zigbee2mqtt in HASS.IO on a Raspberry Pi 3. I'm quite a newbie... thanks in advance for your patience.

I struggled initially but managed to get my stick flashed and connected to my Philips Hue Go - so I know the USB stick, the zigbee2mqtt and mosquito broker are working fine. I can turn the Hue Go off, change colors, etc.
I followed the steps to pair the centralite plug with the controller, I created a custom [devices.js](https://pastebin.com/W1qPY7Dj) (and was quite proud of myself until this point in time 😄 )

I restarted everything and then went to the outlet and pressed the on/off button to generate some traffic hoping for the famous error messages.... Nothing. I tried to understand how to enable the sheperd debugging in hass.io but I don't seem to be getting anywhere.

This is the latest [log file with debug enabled](https://pastebin.com/8z5krUNi) and [database.db](https://pastebin.com/xyXAQ3RF)

Could someone explain what steps I can take to go from here? Of course the bare minimum is to be able to use the device as a switch from home assistant - but if I could read the power consumption and status that would be cool... Thanks!

**Comment by tb-killa** [comment]
Hi nice to see that more and more cool devices join the project.
Normaly we see for this type of device that we need some sort of reporting configuration.

Lets test this snipped and report back via debug enabled log.

```
// Centralite Swiss Plug
{
	zigbeeModel: ['4256251-RZHAC'],
	model: '4256251-RZHAC',
	vendor: 'CentraLite',
	description: 'White Swiss power outlet switch with power meter',
	supports: 'switch and power meter', 
	fromZigbee: [], 
	toZigbee: [],
	configure: (ieeeAddr, shepherd, coordinator, callback) => {
		const device = shepherd.find(ieeeAddr, 1);
		const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
		const actions = [
			(cb) => device.bind('genOnOff', coordinator, cb),
			(cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
			(cb) => device.report('haElectricalMeasurement', 'rmsVoltage', 10, 1000, 1, cb),
			(cb) => device.report('haElectricalMeasurement', 'rmsCurrent', 10, 1000, 1, cb),
			(cb) => device.report('haElectricalMeasurement', 'activePower', 10, 1000, 1, cb),
		];

		execute(device, actions, callback);
	},
},
```

**Comment by EagleAdam** [comment]
Thanks for your help - ok some more readable data appeared. 

I replaced the devices.js with what you suggested, restarted the plugin and cycled the power switch on the device four times. [Here is the log](https://pastebin.com/BAy9dnkp)

The values shown make sense (I'm in Europe so 230V is normal here)

I was going to try the next step but can I do that from hass.io or do I need to ssh into the debug mode and go into the docker image?

**Comment by tb-killa** [comment]
hi nice to read that you see some results.
**we could also add report for ``acFrequency`` if needing ?**

we should check if we could add now some sort of converters:
replace the ``fromzigbee`` with this one:
```
fromZigbee: [fz.ignore_onoff_change, fz.generic_state, fz.ignore_electrical_change,fz.CentraLite_4256251_power]
```
and ``tozigbee`` with this ones
```
toZigbee: [tz.onoff],
```
on ``converters/fromZigbee.js`` add this section to get them complete working:

```
CentraLite_4256251_power: {
        cid: 'haElectricalMeasurement',
        type: 'attReport',
        convert: (model, msg, publish, options) => {
            return {
                power: msg.data.data['activePower'],
                current: msg.data.data['rmsCurrent'],
                voltage: msg.data.data['rmsVoltage'],
            };
        },
    },
```

please test with debug log and check with defined constant load like a lamp with 60w so we could check if we need some math to get the value correct returned.

**Comment by EagleAdam** [comment]
Done:
```
  zigbee2mqtt:info 2018-10-26 13:35:25 MQTT publish, topic: 'zigbee2mqtt/0x000d6f0001b96588', payload: '{"state":"ON","linkquality":63,"voltage":233}'
  zigbee2mqtt:debug 2018-10-26 13:35:39 Received zigbee message of type 'devChange' with data '{"cid":"haElectricalMeasurement","data":{"rmsCurrent":121,"activePower":175}}' of device '4256251-RZHAC' (0x000d6f0001b96588)
```
I plugged in a 15W bulb (well I guess a 17.5W from what I can read!)

**Comment by EagleAdam** [comment]
Done, cool - my first contribution to an open source project :)
Now I will try to get the device to show up in homeassistant… I might post back if I need help. Thanks for your guidance in getting this set up!

**Comment by Koenkk** [comment]
@EagleAdam nice! update to the latest dev branch and it should show in homeassistant.
