### ISSUE TITLE
Merge new NEO version (S4503-2) of smart alarm in existing one (NAS-AB02B0)

### ISSUE THREAD

**Issue by ArJay60** [Koenkk/zigbee2mqtt#5365]
New version of older NEO alarm/siren model NAS-AB02B0 has become available. Type on the box of the newer version is NEO 4503-2. Can the new version be merged in the devices.js with the older version by adding fingerprints? Fingerprint of new version is:

        fingerprint: [
            {modelID: 'TS0601', manufacturerName: '_TZE200_d0yu2xgi'},
        ],

Newer version is working correct with definitions of older version.

**Comment by Koenkk** [comment]
Already available in dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
