### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by Odianosen25** [Koenkk/zigbee2mqtt#537]
@Koenkk , Please just a simple request for release notes.

I can see zigbee2mqtt is now on 0.1.8. Though I have been running 0.1.3 and its been fine for me, so haven't had a reason to upgrade yet. I might add new devices soon, so was looking at upgrading. 

But before I upgrade, I will like to kindly know what changes or features have been made or added? If there was some History doc or release notes that will be great thanks.

Regards

**Comment by clockbrain** [comment]
Refer here https://github.com/Koenkk/zigbee2mqtt/releases

**Comment by Odianosen25** [comment]
Oh thanks @clockbrain, for some reason didn't see it. 

Silly me.

Closing now
