### ISSUE TITLE
Saswell SEA801-Zigbee is recognized as SEA802-Zigbee

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#5374]
Hello, my thermostat is Saswell [SEA801-Zigbee](https://www.zigbee2mqtt.io/devices/SEA801-Zigbee.html) is recognized as [SEA802-Zigbee](https://www.zigbee2mqtt.io/devices/SEA802-Zigbee.html).

`{"id":54,"type":"EndDevice","ieeeAddr":"0x5c0272fffec23f51","nwkAddr":29313,"manufId":4098,"manufName":"_TZE200_c88teujp","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0601","manufacturerName":"_TZE200_c88teujp","powerSource":3,"zclVersion":3,"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca168ea","endpointID":1}],"meta":{}}},"appVersion":85,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1608653648154}
`

![sshot-1](https://user-images.githubusercontent.com/32480002/102913222-c369f000-447e-11eb-9767-583fce8c18f6.jpg)
![sshot-2](https://user-images.githubusercontent.com/32480002/102913224-c4028680-447e-11eb-9134-6b083860f6ba.jpg)

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by drzony** [comment]
@Koenkk 801 and 802 have the same model and manufaturer now. So now my 802 are recognized as 801. I'll make a pull request to do a single 80x. Is it possible to add 2 pictures to zigbee2mqtt.io?
