### ISSUE TITLE
nRF52840 modern arm dongle

### ISSUE THREAD

**Issue by sknsean** [Koenkk/zigbee2mqtt#539]
Have anyone looked into using an nRF52840 dongle instead of the 8051 based cc devices?

**Comment by ryanbeaton** [comment]
The prerequisite for Zigbee Shephard is the Texas Instrumenta stack (TI). Does it support that. The CC2538 is ARM Cortex-M3-based and support the TI stack.

**Comment by sknsean** [comment]
Okay I get it :-)
But the CC2538 is quite expensive vs the nordic semiconductor dongle...
