### ISSUE TITLE
AC dimmer HLC721-Z support

### ISSUE THREAD

**Issue by dementeb** [Koenkk/zigbee2mqtt#5393]
Good day. I have triac dimmer https://www.aliexpress.com/item/10000219022289.html. Its like HLC610-Z but 300W.
For now I just replace HOMA1002 to HOMA000F in the string "zigbeeModel: ['HOMA1002', 'HOMA0019', 'HOMA0006']," devices.js and all work like a charm.

Sorry, I'm not fully understand new device instruction, but I can do something if needed.
Thank you for you work so much.

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
