### ISSUE TITLE
 Bitron AV2010/25 (watt comsumption wrong)

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#5399]
Hi

Please, could you fix the value in "watt" ? Since latest version in dev branch, I have some wrong values. I think you forget a division by 10 :)

![image](https://user-images.githubusercontent.com/6093175/103103060-6a858d80-461f-11eb-9445-1c75d2f4c496.png)
 
![image](https://user-images.githubusercontent.com/6093175/103103074-7e30f400-461f-11eb-9886-84794cc639dc.png)

Thank you :)

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by kevincaradant** [comment]
still having the issue ;)

**Comment by Koenkk** [comment]
Can you try experimenting with the divisor and check when you get correct values? To do this update devices.js and edit the `divisor` value. Currently it's `100`, but try with e.g. `1000` and, restart zigbee2mqtt and do a reconfigure via the zigbee2mqtt ui.

```js
{
    zigbeeModel: ['902010/25'],
    model: 'AV2010/25',
    vendor: 'Bitron',
    description: 'Video wireless socket',
    fromZigbee: [fz.on_off, fz.metering],
    toZigbee: [tz.on_off],
    exposes: [e.switch(), e.power()],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
        await reporting.instantaneousDemand(endpoint);
        endpoint.saveClusterAttributeKeyValue('seMetering', {divisor: 100, multiplier: 1});
    },
},
```

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to modify devices.js

**Comment by kevincaradant** [comment]
I did some tests and I got the real value using divisor at 10000

However, under HA I have a value but honestly I don't know why ... it's not documented and I don't understand what is it 'energy'

![image](https://user-images.githubusercontent.com/6093175/103179581-e2f18600-488d-11eb-8704-0d667ef22a84.png)

The power consumption is 'power' but 'energy' should not exist ?

**Comment by Koenkk** [comment]
Energy is the sum of the measured power in kWh, I've fixed the divisor.
