### ISSUE TITLE
Support for Hue motion sensor SML001

### ISSUE THREAD

**Issue by dabont** [Koenkk/zigbee2mqtt#54]
In this issue I will capture the steps taken in order to implement support for the Hue motion sensor. Both for myself and the community in order to learn.

Step1: Pairing the sensor

The sensor was previously paired to the Hue bridge. After pressing the setup button at the back for 1 second the led on the device flashed green and orange. After 30 seconds it was sucessfully paired.

the following message was displayed.

```
2018-5-19 10:15:22 WARN Device with modelID 'SML001' is not supported.
2018-5-19 10:15:22 WARN Please create an issue on https://github.com/Koenkk/zigbee2mqtt/issues to add support for your device
2018-5-19 10:15:22 WARN Device with modelID 'SML001' is not supported.
2018-5-19 10:15:22 WARN Please create an issue on https://github.com/Koenkk/zigbee2mqtt/issues to add support for your device
```

Next step adding it to `lib/devices.js`

To be continued

**Comment by dabont** [comment]
Added the following lines to `lib/devices.js`

```
'SML001': {
        model: 'SML001',
        vendor: 'Philips',
        description: 'Hue Motion Sensor',
        supports: 'occupancy, illuminance and temperature'
    },
```
The device is now recognized

`2018-5-19 15:07:08 INFO 0x001788010213a536 (0x001788010213a536): SML001 - Philips Hue Motion Sensor`

I still do not receive any messages that a converter is missing. Lets dig into this later.

**Comment by Koenkk** [comment]
Perhaps we need to setup reporting like we also did for https://github.com/Koenkk/zigbee2mqtt/pull/44. What is the content of your `data/database.db`?

**Comment by TheCellMC** [comment]
Any update on this?

**Comment by tb-killa** [comment]
Maybe this could help ??
https://peeveeone.com/?p=166#comment-254

It seems to be that HUE use fixed zigbee channel and need Key to decrypt the traffic:
https://peeveeone.com/?p=166#comment-24

**Comment by TheCellMC** [comment]
I've tried this again with the latest version and this is still not working.
I'm not getting any logs asking for a converter.
