### ISSUE TITLE
[dev] No power information receive BW-SHP13 (TS0121)

### ISSUE THREAD

**Issue by Kalypox** [Koenkk/zigbee2mqtt#5404]
Is it necessary to open issues for the dev branch ?

## What happened
My BW-SHP13 no longer send power informations (the value in W).
It works on the image:latest but not on the image:latest-dev

## How to reproduce it (minimal and precise)
Pull the state of the device with "get" and payload `state : ""` and the returned value for power is 0

**Comment by 1igeza** [comment]
For me it's working OK on newest dev. 
```
zigbee2mqtt version
    1.16.2-dev commit: 99c77d2
coordinator type
    zStack3x0
coordinator revision
    20201113
frontend version
    0.2.110
```
```
Dec 26 00:01:49 zigbee2mqt npm[19744]: Zigbee2MQTT:debug 2020-12-26 00:01:49: Received MQTT message on 'zigbee2mqtt/SHP13/get/state' with data ''
Dec 26 00:01:49 zigbee2mqt npm[19744]: Zigbee2MQTT:debug 2020-12-26 00:01:49: Publishing get 'get' 'state' to 'SHP13'
Dec 26 00:01:49 zigbee2mqt npm[19744]: Zigbee2MQTT:debug 2020-12-26 00:01:49: Received Zigbee message from 'SHP13', type 'readResponse', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Dec 26 00:01:49 zigbee2mqt npm[19744]: Zigbee2MQTT:info  2020-12-26 00:01:49: MQTT publish: topic 'zigbee2mqtt/SHP13', payload '{"current":0.01,"energy":15.03,"last_seen":"2020-12-26T00:01:49+01:00","linkquality":135,"power":2,"state":"ON","voltage":228}'

```

**Comment by Kalypox** [comment]
@1igeza,

I just tried to update my docker : it works now !

Developers are faster than me ^^
My release date from 12/23.

**Comment by Kalypox** [comment]
I reopen because the problem is still here.
The power value is stuck on 600W

As you can see:
![Screenshot_20201226-020427.png](https://user-images.githubusercontent.com/2879180/103143846-2b3e6600-471f-11eb-9c2c-22f6f7f5cdee.png)

The energy doesn't grow up, because the switch is OFF but the power say 600W

Thanks !

**Comment by Kalypox** [comment]
The 1.17.0 fixed that
