### ISSUE TITLE
Move zigbee Stick to another machine

### ISSUE THREAD

**Issue by pepp86** [Koenkk/zigbee2mqtt#541]
Hi,

is it possible to transfer the stick and configuration to a different machine without repairing?

Thanks!

**Comment by Koenkk** [comment]
Yes if you also copy your database.db

**Comment by pepp86** [comment]
Worked perfectly. Thank you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Anon0ne** [comment]
I moved my stick to a new machine, the OS is Ubuntu running in ProxMox. I seem to have an issue with several of my devices not wanting to write states.

Error: Data request failed with error: 'MAC no ack' (233))

**Comment by nilskuehme** [comment]
I have the same problem.
