### ISSUE TITLE
Add !secret support in config file

### ISSUE THREAD

**Issue by caddyblack** [Koenkk/zigbee2mqtt#5410]
In the config file I have to fill in the MQTT server login details.
Request to have !secret support for these parameters.

**Comment by deosrc** [comment]
I believe this is already a feature: https://www.zigbee2mqtt.io/information/configuration.html#specifying-mqtt-userpassword-and-network_key-in-a-different-file

**Comment by deosrc** [comment]
Probably worth noting that this is not available for the frontend auth_token:

https://github.com/Koenkk/zigbee2mqtt/blob/04c15f7fe8abaa9534ea565b0fa0cd796652d69e/lib/util/settings.js#L318

**Comment by Koenkk** [comment]
As @deosrc this is already supported.

**Comment by caddyblack** [comment]
Thanks for your reply.  The !secret works well. It has to be in quotes like **'!secret mqttpw'**
Issue can be closed

**Comment by teeling** [comment]
In my configuration.yaml I have:
auth_token: '!secret frontend_auth_token'
but the front end doesn't let me in with the string in the secret.yaml, but with the string '!secret frontend_auth_token' instead.

Would it be possible to add this for the "auth_token" setting in the configuration.yaml as well?
