### ISSUE TITLE
Unknown options ext_pan_id

### ISSUE THREAD

**Issue by andrew-yu** [Koenkk/zigbee2mqtt#5412]
# Bug Report
## What happened
Can't set ext_pan_id option.
Livolo switch configuration required to set configuation options:
```
advanced:
  ext_pan_id: [33,117,141,25,0,75,18,0]
  channel: 26
```
But when the Zigbee2MQTT plugin started the log contains record
`:{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":0,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":26,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221] ...`

And Supervisor log contains:
`WARNING (MainThread) [supervisor.addons.validate] Unknown options ext_pan_id`

So ext_pan_id set in configuration but ignored as unknown option.

## What did you expect to happen
Expected to see required ext_pan_id value in the Zigbee2MQTT log.

## How to reproduce it (minimal and precise)
Set ext_pan_id in Zigbee2MQTT config, run Zigbee2MQTT, see Zigbee2MQTT and Supervisor logs.

## Debug Info
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20190608

**Comment by Koenkk** [comment]
This error is logged by the addon, not Zigbee2MQTT itself, please create an issue here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues
