### ISSUE TITLE
Ubisys D1: does not pair until reboot

### ISSUE THREAD

**Issue by wb441** [Koenkk/zigbee2mqtt#5439]
## What happened

The device does not pair.
The only way to make it pair is to reboot the host system (Raspberry Pi).

## What did you expect to happen

By factory resetting the device, that the device pairs.

## How to reproduce it (minimal and precise)

Fresh install of Raspbian Buster + IOTstack.
The dimmer was factory reset (cycling power 3 times, confirmed by the light flashing three times).

## Debug info
Zigbee2MQTT version: latest, not dev, downloaded two hours ago.
Adapter hardware: CC2652 from Tindie
Adapter firmware version: CC26X2R1_20201026.hex

**Comment by Koenkk** [comment]
The only way to debug such issues is by sniffing the traffic (assuming you see nothing in the log when attempting to pair). Could you sniff the traffic and provide it here together with your network key? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html
