### ISSUE TITLE
OTA Update Failed for Ikea E1603/E1702

### ISSUE THREAD

**Issue by AshtonKem** [Koenkk/zigbee2mqtt#5457]
## What happened

Attempted OTA update for Ikea Tradfri outlet. This update failed with the following logs:

```
INFO: Updating 'Ikea Switch' to latest firmware
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Updating 'Ikea Switch' to latest firmware","meta":{"device":"Ikea Switch","status":"update_in_progress"},"type":"ota_update"}'
INFO: MQTT publish: topic 'zigbee2mqtt/Ikea Switch', payload '{"linkquality":0,"state":"ON","update":{"state":"available"},"update_available":true}'
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'Ikea Switch' failed (Image is truncated: not long enough to contain a valid tag)","meta":{"device":"Ikea Switch","status":"update_failed"},"type":"ota_update"}'
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Ikea Switch"},"error":"Update of 'Ikea Switch' failed (Image is truncated: not long enough to contain a valid tag)","status":"error"}'
ERROR: Update of 'Ikea Switch' failed (Image is truncated: not long enough to contain a valid tag)
INFO: MQTT publish: topic 'zigbee2mqtt/Ikea Switch', payload '{"linkquality":0,"state":"ON","update":{"state":"available"},"update_available":true}'
INFO: Update available for 'Ikea Switch'
INFO: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update available for 'Ikea Switch'","meta":{"device":"Ikea Switch","status":"available"},"type":"ota_update"}'
```

Here is the switch's current status.

![image](https://user-images.githubusercontent.com/199201/103299738-12011800-49b2-11eb-965f-354b2ab94f8f.png)

## What did you expect to happen

OTA to update successfully.

## How to reproduce it (minimal and precise)

Attempt OTA update on the appropriate Ikea device.

## Debug info
Zigbee2MQTT version: 1.16.2.2
Adapter hardware: CC2531
Adapter firmware version: Unknown

**Comment by Koenkk** [comment]
Known issue (see https://github.com/Koenkk/zigbee2mqtt/discussions/2921). Fix is in the dev branch, check https://github.com/Koenkk/zigbee2mqtt.io/blob/df55aff35f63475838bf8bbffd1158f61122c909/docs/information/ota_updates.md#ikea-tradfri-ota-failing (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
