### ISSUE TITLE
Reset coordinator with the frontend version 0.2.125 ?

### ISSUE THREAD

**Issue by zibous** [Koenkk/zigbee2mqtt#5468]
## What happened
I had a router (OSRAM Smart+ plug) failure today and the devices that were connected are offline.

![Bildschirmfoto 2020-12-30 um 12 08 59](https://user-images.githubusercontent.com/30198737/103347697-012ad200-4a98-11eb-999c-0140b35db8b9.png)

## Debug info
Zigbee2MQTT version: 1.16.2-dev commit: 897f5a9
Adapter hardware: ConBee2/RaspBee2
Adapter firmware version: 26660700

1. What does "Reset coordinator" do with the frontend version 0.2.125? 
    **Will all devices be reset and do I have to reconnect them?**

2. Reconnect devices
I had a router failure today and the devices that were connected to it are no longer accessible or I am no longer receiving measurement data. 
**Do I have to reconnect the orphaned devices to another router or to the coordinator?**

**Comment by Koenkk** [comment]
> What does "Reset coordinator" do with the frontend version 0.2.125?

@nurikk can you remove this reset option from the frontend? It's not working correctly and also not included in the new api. Seems to only cause confusion.

> I had a router failure today and the devices that were connected to it are no longer accessible or I am no longer receiving measurement data.

First try re-powering them/re-insert batteries. If that doesn't help repair.

**Comment by nurikk** [comment]
I've added `config/reset` call for @Hacker-CB, if it not required anymore I can remove it from ui

**Comment by Hacker-CB** [comment]
@nurikk I don't remeber I asked for this. 
I don't know what this option do. I never used it.
May be somebody else asked for this?

**Comment by Hacker-CB** [comment]
Is this discussion is about "Reset Coordinator" option? Or other one?

**Comment by timoline** [comment]
I think it comes from this discussion?
https://github.com/nurikk/z2m-frontend/issues/202

**Comment by zibous** [comment]
this one: frontend version 0.2.125

![Bildschirmfoto 2020-12-30 um 16 17 37](https://user-images.githubusercontent.com/30198737/103363184-c7b78e00-4aba-11eb-9067-2cb241ec18d7.png)

**Comment by nurikk** [comment]
> this one: frontend version 0.2.125
> 
> ![Bildschirmfoto 2020-12-30 um 16 17 37](https://user-images.githubusercontent.com/30198737/103363184-c7b78e00-4aba-11eb-9067-2cb241ec18d7.png)

I have removed this feature in the latest update

**Comment by zibous** [comment]
removed see: frontend version 0.2.129
