### ISSUE TITLE
Publishing to cascaded topic in mqtt

### ISSUE THREAD

**Issue by omer1141** [Koenkk/zigbee2mqtt#5493]
I want to write some command line scripts to set certain properties for devices (triggered by my home automation system). I managed to do it for simple 1-level topics (like the ones described in the official zigbee2mqtt documentation). But I did not manage to set values for more complex values (like e.g. the issuing of actions for a HEOMAN HS2IRC. What do I need to do to trigger the following action (send keycode 1 for device 1):
{
    "send_key": {
        "id": 1,
        "key_code": 1,
    }
}

Is it somethings like this:

mosquitto_pub -h <IP Address> -t "zigbee2mqtt/<nice_name>/set/send_key -m ????

Could someone please help me further on this?

Thanks

Raymond

**Comment by Koenkk** [comment]
`mosquitto_pub -h -t "zigbee2mqtt/<nice_name>/set" -m '{"send_key":{"id":1,"key_code":1}}'`

Converting this to a discussion since it's not directly a z2m issue.
