### ISSUE TITLE
Home Assistant MQTT discovery isn't working

### ISSUE THREAD

**Issue by biscuit-316** [Koenkk/zigbee2mqtt#5494]
## What happened
When I add a device to zigbee2mqtt, the device is not automatically added to Home Assistant.

## What did you expect to happen
I expected that after a reboot the light would appear in Home Assistant.

## How to reproduce it (minimal and precise)
When I add my first device to zigbee2mqtt it shows up in the web interface. It can be operated from there. But the device is not automatically added to Home Assistant.

When I use the ["Manual Home Assistant configuration"](https://www.zigbee2mqtt.io/devices/LED1733G7.html#manual-home-assistant-configuration) the light appears in Home Assistant. And is fully controllable.

I had added the [MQTT Discovery](https://www.zigbee2mqtt.io/integration/home_assistant.html) details, although they are no longer needed. (MQTT Discovery is enabled by default).

The addon configuration contains: "homeassistant: true".

edit:
[here is the log of adding the light](https://pastebin.com/WA0xR3HR)
The log showes clearly that the discovery message has been send.

To test it I had enabled the Home Assistant listener on topic "homeassistant". (configuration -> integration -> MQTT -> Listen to topic)

I also made a simple automation to turn on an input boolean when an mqtt message with the topic "homeassistant" arrives.
both nodered and the listener had not received the mqtt message.

## Debug info
zigbee2mqtt addon in Home Assistant (version: 1.16.2.2)
Adapter hardware: CC2531
Mosquitto broker addon in Home Assistant (version: 5.1)
Home Assistant (version: 2020.12.2)
Home Assistant OS 5.9

**Comment by IlmLV** [comment]
same issue for me

Home Assistant 2020.12.1 (docker)
Zigbee2MQTT version 1.17.0 (commit #07cdc9d)
Mosquitto version 1.6.12
Adapter: Conbee2

**Comment by Koenkk** [comment]
When subscribing to `homeassistant/#` using a MQTT client and starting z2m, do you see any messages?

**Comment by biscuit-316** [comment]
When I started listening for `homeassistant/#` and restart zigbee2mqtt. [7 messages](https://pastebin.com/iYUJg7GS) came in. so mqtt works, what's next?

**Comment by Koenkk** [comment]
Those are the discovery messages, so looks like the problem is on the HA side.

**Comment by biscuit-316** [comment]
okay, then i will raise a issue with home assistant.

Thanks for your quick responses.
