### ISSUE TITLE
Voltage and Current problem with immax-07048l

### ISSUE THREAD

**Issue by janky69** [Koenkk/zigbee2mqtt#5498]
Hi, 
i have problem with plug Immax 07048. Device not sending voltage and current. Publish /get with payload {"voltage":""} not work. 

Thank you for you time and your great work!!!

**Comment by salopette** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/5072

**Comment by Koenkk** [comment]
Fixed, see https://github.com/Koenkk/zigbee2mqtt/issues/5072
