### ISSUE TITLE
Xiaomi Wireless Wall Button Picture lost

### ISSUE THREAD

**Issue by arripeo** [Koenkk/zigbee2mqtt#5510]
## What happened
The Picture for the Xiaomi WXKG02LM wireless 2 key wall switch is lost, propably after update of the name in repository with underscore for rev n

## What did you expect to happen
How can I update or change my picture

## Debug info
Zigbee2MQTT version: Add on on Hassio 1.6.2.2
Adapter hardware: CC2531
Adapter firmware version: zigbee 3.0

**Comment by Koenkk** [comment]
This device has been renamed (to `WXKG02LM_rev1` or `WXKG02LM_rev2`) therefore also the pictures have been renamed. Updating to Zigbee2MQTT 1.17.0 will fix it (but you have to wait since the addon update is not available yet).
