### ISSUE TITLE
Power Outage Memory for Xiaomi LLKZMK11LM (relay)

### ISSUE THREAD

**Issue by Kalypox** [Koenkk/zigbee2mqtt#5530]
Hello !

## Describe the solution you'd like
Add support for power_outage_memory for Xiaomi LLKZMK11LM to allow reset the kWh counter if we want

## Describe alternatives you've considered
Today we can't reset this counter with zigbee2mqtt

## Additional context
I saw in the last update that the power_outage_memory  was added for TuYa TS0121_plug
https://www.zigbee2mqtt.io/devices/TS0121_plug.html

Thanks !

**Comment by GoNzCiD** [comment]
same here
