### ISSUE TITLE
Incorrect image for SONOFF S31 Lite

### ISSUE THREAD

**Issue by Woodcat64** [Koenkk/zigbee2mqtt#5533]
## What happened
Incorrect image of SONOFF S31 Lite is displayed Zigbee2mqtt web ui and https://www.zigbee2mqtt.io/devices/S31ZB.html
https://raw.githubusercontent.com/Koenkk/zigbee2mqtt.io/master/docs/images/devices/S31ZB.jpg
![S31ZB_old](https://user-images.githubusercontent.com/50119854/103487898-9a2e5580-4dd6-11eb-9f61-2a25130673c0.jpg)

## What did you expect to happen
To see this image https://cdn-media.itead.cc/media/catalog/product/0/4/04_1_1.jpg
![S31ZB](https://user-images.githubusercontent.com/50119854/103487801-fc3a8b00-4dd5-11eb-8d9f-115fb6bdca15.jpg)

## How to reproduce it (minimal and precise)
When paired, it's on "Devices" tab. https://www.zigbee2mqtt.io/devices/S31ZB.html
## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: CC2531, CC2530, Conbee II
Adapter firmware version:
any

**Comment by Koenkk** [comment]
Fixed, image will be fixed after a refresh of the frontend (but maybe you need to wait till caches are cleared).
