### ISSUE TITLE
Philips Hue Go - Won’t Connect

### ISSUE THREAD

**Issue by hay11mac** [Koenkk/zigbee2mqtt#5541]
Hey,

desperate for some help / advice, I hope I’m posting in the correct place.

I have a Philips Hue Go Lamp that I’ve had connect to my Hue Bridge absolutely fine, however the lamp was no longer required so I deleted the lamp from my Hue app etc and sold the lamp, however the buyer has told me that they can connect to the lamp they have even tried searching for it by serial number, I’ve tried finding a solution but have been unsuccessful. The only thing I have come across is somehow resetting it with a Hue Remote which the buyer doesn’t own. The only other thing I’ve seen is let the battery full deplete (assuming turning the lamp on with no power cord?) and once depleted search again my serial number and should connect, can anyone confirm this will work?

I’d be so grateful for some advice on how they can connect to this lamp.

thanks in advance

Hay

**Comment by Koenkk** [comment]
This is the Zigbee2MQTT issue tracker, not a Hue support forum.
