### ISSUE TITLE
Supported devices not recognized after update.

### ISSUE THREAD

**Issue by rodrigorsdev** [Koenkk/zigbee2mqtt#5560]
## What happened
Hello,

I recently updated my home assistant and zigbee2mqtt.

Multiple supported devices are no longer recognized like HEIMAN HS1CG-M, TuYa SNTZ007 and others.

Logs: https://hastebin.com/axewixatig.apache

How can I  add this devices, listed on supported devices, without open a request?

## Debug info
Zigbee2MQTT version: 1.17.0.1
Adapter hardware: CC2531
Adapter firmware version: 20190608

Thanks.

**Comment by Koenkk** [comment]
Can you share your data/database.db?

**Comment by rodrigorsdev** [comment]
Sure,

https://hastebin.com/uxukoxuqum.json

**Comment by Koenkk** [comment]
I'm not sure what/how it happend but all modelIDs are gone from your database (for the unsupported device). I'm afraid you have to repair those (though it would be nice if there is some way to reproduce this so I can fix it)

**Comment by rodrigorsdev** [comment]
How can I fix this? 

I created a new Home Assistant server and installed zigbee2mqtt, I still have the old server and zigbee2mqtt database.

**Comment by Koenkk** [comment]
Can you copy over the database of your old server to the new one (make a backup of the new one first, and stop z2m before replacing)

**Comment by rodrigorsdev** [comment]
The devices appeared, but with unknown status and does not work.

![image](https://user-images.githubusercontent.com/5364277/103691479-fdee8500-4f74-11eb-840d-83affcf9a4b6.png)

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log now when triggering it?

**Comment by rodrigorsdev** [comment]
it's here

https://hastebin.com/edakogutis.rust

**Comment by Koenkk** [comment]
Did you click it during this log (this is only the first 4 seconds of zigbee2mqtt)

**Comment by rodrigorsdev** [comment]
It's the first 4 seconds: https://pastebin.com/441Veuz

**Comment by sneakythr0ws** [comment]
I have the same problem with Tuya TS0601 'Interview failed'

**Comment by Koenkk** [comment]
@rodrigorsdev  getting : 
![image](https://user-images.githubusercontent.com/2892853/104057862-1d92e100-51f3-11eb-88d5-770fc83be49c.png)

**Comment by rodrigorsdev** [comment]
I´m sorry

https://hastebin.com/hupojidije.yaml

**Comment by rodrigorsdev** [comment]
there is a little more

https://hastebin.com/ejumuluwuk.yaml

**Comment by Koenkk** [comment]
Logs are still short. If you are running the HA addon I suggest just grab the logs by executing `docker logs -f [CONTAINER_ID]` on the z2m container (use ssh to login)

**Comment by rodrigorsdev** [comment]
how can I do that in hassio?

**Comment by Koenkk** [comment]
@rodrigorsdev there are some tutorials available I see; https://www.google.com/search?q=ssh+into+hassio&oq=ssh+into+hassio&aqs=chrome..69i57j0l2j0i22i30l2.2080j0j7&sourceid=chrome&ie=UTF-8

**Comment by rodrigorsdev** [comment]
I know how to connect, I don't know how to list the docker containers

![image](https://user-images.githubusercontent.com/5364277/104064660-11038e00-51dd-11eb-84f9-6732114328f7.png)

**Comment by Koenkk** [comment]
Does it work with: `sudo docker ps` ?

**Comment by rodrigorsdev** [comment]
No, 

![image](https://user-images.githubusercontent.com/5364277/104065281-3e9d0700-51de-11eb-8f0c-c1f90823412b.png)

**Comment by rodrigorsdev** [comment]
I reinstalled zigbee2mqtt and when adding some sensors it worked normally, however the xiaomi sensors are not found and does not generate any record in the log.

**Comment by Koenkk** [comment]
Make sure to check https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair

**Comment by rodrigorsdev** [comment]
I flashed the CC2531 coordinator and worked.

Thanks for help.
