### ISSUE TITLE
Philips 6916531PH Living Whites

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee2mqtt#557]
any ideas ??

**Comment by WagnerBeccard** [comment]
Wich Ideas? Is it supported? 
https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices#philips - Nope 
if there ll be support? 
https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices - maybe. After Its Philipps it's likely they used the same protocol.
From some Amazon ratings you need to use Touchlink to pair the device.

**Comment by arteck** [comment]
the problem is this Plug can not connected direct to the Bridge.
Touchlink  is here the magic word... ok

**Comment by vladitep** [comment]
it can connected direct to bridge. To pair it with bridge you need to put 6916531PH  close to bridge, just put it on the bridge and it connects. In old bridge firmware it does. I have one of this and its work ok couple years, when i got it and connect to bridge. But now, when i removed it from bridge, i cant connect it again.

**Comment by karolzlot** [comment]
@Koenkk  can you reopen?

I have this device: 6916531PH

It has no buttons, so I think it should be possible to link it by Touchlink. I can help with logs, but I am not sure where to start.

I tried to put it near zigbee2mqtt cooridinator and permit, but nothing happens.

**Comment by Koenkk** [comment]
Try putting the device close to the coordinator (almost against it), and press the scan button on the touchlink page of the z2m frontend: 
<img width="1086" alt="Screenshot 2021-07-05 at 21 13 17" src="https://user-images.githubusercontent.com/2892853/124511209-e41fe480-ddd5-11eb-8143-4561c61b02ec.png">

If it detects it click the factory reset button

**Comment by karolzlot** [comment]
@Koenkk 

I tried a few times. Usually detected nothing.
Once it detected one of my already connected devices. (Osram plug).

![20210705_213213](https://user-images.githubusercontent.com/11590960/124513106-55619680-ddda-11eb-830b-8843b39f72a8.jpg)

**Comment by Koenkk** [comment]
That's strange, is it really Zigbee?

**Comment by karolzlot** [comment]
More information:

> Hi, LivingWhite products can't be paired to deCONZ since these use a security key only known and supported by Philips Hue bridge. They predate Hue products which use inter-operable security keys.

https://github.com/ebaauw/homebridge-hue/issues/291#issuecomment-366313967

---



Manual:

![20210705_160411](https://user-images.githubusercontent.com/11590960/124515728-70370980-dde0-11eb-97f1-e79068e704f1.jpg)
![20210705_160431](https://user-images.githubusercontent.com/11590960/124515732-70cfa000-dde0-11eb-8c48-2fe4a5a50fdd.jpg)
![20210705_160447](https://user-images.githubusercontent.com/11590960/124515735-7200cd00-dde0-11eb-8eaf-8b583fb1a34a.jpg)
![20210705_160452](https://user-images.githubusercontent.com/11590960/124515736-72996380-dde0-11eb-8546-ee57ec0bc932.jpg)

**Comment by Koenkk** [comment]
> LivingWhite products can't be paired to deCONZ since these use a security key only known and supported by Philips Hue bridge. They predate Hue products which use inter-operable security keys.

This explains why this won't work.
