### ISSUE TITLE
TS0601_thermostat functions not fully in frontend 

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#5574]
Hello, I made a request here, but seems to be the wrong one.
Must be fixed in the z2m.

https://github.com/nurikk/z2m-frontend/issues/243

**Comment by Koenkk** [comment]
Added all except: holidays, window_detection_params, workdays. Those are complex types which we don't support yet.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by salopette** [comment]
Window detection was already available !?

![sshot-1](https://user-images.githubusercontent.com/32480002/103688986-f8079c80-4f92-11eb-8b65-644100cb7590.jpg)

**Comment by Koenkk** [comment]
window_detection_params not window_detection

**Comment by salopette** [comment]
A lot has happened! Many Thanks!
Can you still add "local_temperature_calibration": to it?

**Comment by nurikk** [comment]
> A lot has happened! Many Thanks!
> Can you still add "local_temperature_calibration": to it?

Check how Koen did this before and try to do like him. First time it would be difficult, but eventually you'll learn how to do this. 
https://github.com/Koenkk/zigbee-herdsman-converters/commit/1976109d7462eb3c072848d1140807d34f5212e0

**Comment by salopette** [comment]
I am unfortunately only a user, not a programmer.
my knowledge of English is also 0.

**Comment by Koenkk** [comment]
> A lot has happened! Many Thanks!
> Can you still add "local_temperature_calibration": to it?

added.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
