### ISSUE TITLE
Add SNTZ003 it is TS0201(already supported) but different manufacture 

### ISSUE THREAD

**Issue by snp88** [Koenkk/zigbee2mqtt#5575]
Helllo 
Could you add to supported devices temperature and humidity sensor SNTZ003 I think it is the same hardware as TS0201 but different manufacturer. Looks the same
I manually add to devices.js bellow code and work like a charm 

`{
        zigbeeModel: ['SNTZ003'],
        model: 'SNTZ003',
        vendor: 'TuYa',
        description: 'Temperature & humidity sensor with display',
        fromZigbee: [fz.battery, fz.temperature, fz.humidity],
        toZigbee: [],
        exposes: [e.battery(), e.temperature(), e.humidity()],
    },`

## Information about the device + link
Temperature and humidity sensor that look like TS0201 already supported 

## data/database.db entry of the device

Database entry after successfully connected with modify device.js 

`{"id":10,"type":"EndDevice","ieeeAddr":"0xbc33acfffe5b9366","nwkAddr":52947,"manufId":4098,"powerSource":"Battery","modelId":"TS0201","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,1,1026,1029],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TS0201","powerSource":3,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2250}},"msRelativeHumidity":{"attributes":{"measuredValue":3940}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"binds":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1609844487254}
`

**Comment by Koenkk** [comment]
Added, thanks.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
