### ISSUE TITLE
Add "error" attribute for failed set commands

### ISSUE THREAD

**Issue by arcanefoam** [Koenkk/zigbee2mqtt#5579]
## Is your feature request related to a problem? Please describe
When I send a set command and the device does not respond (usually a timeout) I have no way to know that the command failed.

## Describe the solution you'd like
An attribute in the device (e.g. setResult) or a mqtt topic in which I can check that the set command completed.

## Additional context
This is in particular for the Wiser TRVs (which are temperamental buggers that don't always answer to commands) but could be of used to other devices.

**Comment by Morphy99** [comment]
There is no way apart from in the logs and in the Z2M front end the error will flash up. You could set a sensor up in HA (if that's what you're using) to create a notification for related mqtt error messages.

As I mentioned [here](https://github.com/Koenkk/zigbee2mqtt/issues/775#issuecomment-759494664) perhaps Z2M should set the device as unavailable if the timeout occurs.
