### ISSUE TITLE
Previously paired devices do not re-pair automatically

### ISSUE THREAD

**Issue by BigValen** [Koenkk/zigbee2mqtt#5588]
## Is your feature request related to a problem? Please describe
If a previously paired device is accidentally unpaired, it will not be able to rejoin. There are no debug messages rejecting the pairing attempt. Logs, in debug mode, just show 'Saving state to file /var/lib/zigbee2mqtt/state.json'.

## Describe the solution you'd like
When I worked out what had happened, I removed the device (HG06104A) from database.db manually,  and zigbee2mqtt was restarted. The device immediately re-paired, with log messags.

It would be best if previously seen devices can be re-paired, and a log message generated.

## Describe alternatives you've considered
A 'warning' level log, saying that a pairing attempt has been rejected would also be almost as useful.

## Additional context
The HG06104A factory resets after three power-on events in a short time. Easy to do.

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of this?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
