### ISSUE TITLE
LED1623G12 E26 version not supported 

### ISSUE THREAD

**Issue by oakbrad** [Koenkk/zigbee2mqtt#56]
Thank you for this project, just getting started with your Docker container.

I have the Ikea Tradfri LED1623G12 model bulb, but in E26 plug.

```
0 19:30:00 INFO New device with address 0x000b57fffe2f1df7 connected!
0 19:30:00 WARN Device with modelID 'TRADFRI bulb E26 opal 1000lm' is not supported.
```

Seems this would be a simple addition, but I am not sure how to edit the device files with the Docker container. Can you advise how best to do this with Docker? Can the needed files be written to a volume so that I can edit them?

**Comment by Koenkk** [comment]
Isn't the correct model id LED16**22**G12? Got it from Technical information part of https://m.ikea.com/ca/en/catalog/products/art/00339435/.

**Comment by oakbrad** [comment]
LED1623G12 is what is printed on my bulb - my model supports different color temperatures same as what's listed in the supported devices. What you linked I think is only the basic "warm white" version.

I think just different plug type for different markets? I am in US where E26 is most common

**Comment by Koenkk** [comment]
The LED1623G12 only supports on/off and brightness (no color temperature). As far as the models I've seen LED15xxxxx = color temperature, LED16xxxxx = no color temperature.

**Comment by oakbrad** [comment]
Sorry you are correct, no color temp, got my bulbs mixed up.

It does appear to be the same as the 1622 linked, the color temp, watts, and lumens match. Mine definitely has 162**3** printed on it though and is E26. If I remember right this was part of a kit with a dimmer puck.

**Comment by Koenkk** [comment]
Ok, no problem! I will add support for it tomorrow.

**Comment by Koenkk** [comment]
Supported now.
