### ISSUE TITLE
Hue Lightstrips always offline despite being listed as routers

### ISSUE THREAD

**Issue by ben423423n32j14e** [Koenkk/zigbee2mqtt#560]
An interesting observation regarding Hue Lightstrips v2

They function fine but are always reported as offline in Zigbee2MQTT despite being listed as a router.

See Graphviz screenshot below, in the center is a Xiaomi power plug and either side are Hue Lightstrips

![lightstripsoffline](https://user-images.githubusercontent.com/3908759/47955782-2ffca900-dff1-11e8-9ba7-017e9c028fd0.JPG)

Here is the complete Graphviz, all Hue Lightstrips report offline (but still work fine)
![graphvizcomplete](https://user-images.githubusercontent.com/3908759/47955820-b0230e80-dff1-11e8-9fa5-0756b895427a.png)

**Comment by davekr8** [comment]
I see the same issue with my osram plugs. I think it's a generic issue with the online/offline state.

Additionally, I have seen devices with no edge to an upstream router/coordinator - but being fully functional an present in my mesh. The network layout seems to be misleading to some extend.

**Comment by ben423423n32j14e** [comment]
After I reflashed my CC2531 and created a new network, I notice that Hue Lightstrips are acting as router and listed as online. Closing ticket.
