### ISSUE TITLE
TuYa valve TS0601: Problem setting force:open/close value

### ISSUE THREAD

**Issue by kremik** [Koenkk/zigbee2mqtt#5601]
## What happened
When set force:open value, or any of allowed values via `zigbee2mqtt/FRIENDLY_NAME/set` it is ignored and not set. 
```
{
      "force": "open"
}
```

There is no way how to change the force value.

In log there is a following message
`Zigbee2MQTT:error 2021-01-06 20:14:42: No converter available for 'force' (open)`

## What did you expect to happen

I expect to send force:open or force:close to change the state of the valve - total open or total close.

## How to reproduce it (minimal and precise)
Send the set command with values above and see the devices response.

## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: CC2531
Adapter firmware version: 3.2.6
Accessory:
https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

**Comment by salopette** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/5578#issuecomment-755583940

**Comment by marcin77** [comment]
I have the same problem, the heating has gone down

**Comment by kremik** [comment]
It seems to be a problem also for all /get parameters - getting this error also via web frontend when refresh button is pressed in Exposes tab.

**Comment by Koenkk** [comment]
This was removed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1983 by @mgrom. @mgrom can this be re-added?

**Comment by mgrom** [comment]
@Koenkk I've just created PR but some errors occured not related to my change.

**Comment by Koenkk** [comment]
@mgrom big thanks again! 

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Lipown** [comment]
Still ave the problem... I am on latest Z2M 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/57076375/2646b1ad-64e3-42dd-a71e-56db65cd745f)
