### ISSUE TITLE
Cant control multiple devices without delay

### ISSUE THREAD

**Issue by jrosum** [Koenkk/zigbee2mqtt#561]
If I send two or more messages to different end devices via MQTT without delay something crashes and the zigbee2mqtt is disabled for around 15 Seconds. Sometimes, some of the lamps change their states after that time

Controlling one device at the same time works. But I think, I'm not the only person wants to control some GU10 Hues at the same time

Zigbee Devices used:
- IKEA Tradfri
- Philips Hue
- CC2531

Computer and OS:
- Dell Optiplex 9020 Ultra small form factor
- Ubuntu Bionic (18.04.1) & Node v10.12.0 & NPM 6.4.1

**Comment by Koenkk** [comment]
This has been fixed in https://github.com/Koenkk/zigbee2mqtt/issues/529
