### ISSUE TITLE
Error : internal error while starting Zigbee2MQTT

### ISSUE THREAD

**Issue by sentinelle59** [Koenkk/zigbee2mqtt#5621]
Hello!

First of all, sorry for my not so good english...
I've some troubles when starting Zigbee2MQTT on my DS414 Synology, and got some specificities : 
- I don't have Docker
- actually I don't have any adapter, I wanted to test the server before buying one

I managed to execute npm install successfully.

## What happened
I've got an error when I start node :
https://hastebin.com/cojigazasi.swift

## Debug info
Zigbee2MQTT version: v1.17.0
 
My yaml :
https://hastebin.com/xikobegoje.yaml

Thanks for all help you could provide!

**Comment by Twit123** [comment]
If you don't have a coordinator on /dev/ttyS0 then it will fail to start.
