### ISSUE TITLE
homeassistant link quality with WXKG11LM

### ISSUE THREAD

**Issue by dmwyatt** [Koenkk/zigbee2mqtt#563]
My Xiaomi WXKG11LM reports a `linkquality` attribute which is currently not supported in `homeassistant.js` where it's configured to use `configurations.sensor_click`.

```{"battery":"100.00","voltage":3165,"linkquality":26,"click":"single"}```

I'm getting ready to add the linkquality attribute to MQTT discovery for this device.  I was just going to add it to `configurations.sensor_click`, but I'm not sure if that is supposed to be more generic or if there's some reason `linkquality` isn't in there already?

**Comment by Koenkk** [comment]
`linkquality` should be added to all `json_attributes`. Can you make a pr?

**Comment by dmwyatt** [comment]
Yep, I'll get one out today.

**Comment by dmwyatt** [comment]
Done, see PR #566
