### ISSUE TITLE
No logs in frontend when initial log_level is set to warn

### ISSUE THREAD

**Issue by Mr-Groch** [Koenkk/zigbee2mqtt#5635]
## What happened
No log output on frontend Logs tab when zigbee2mqtt is started with configuration:
`"log_level": "warn",`
Logs will not be outputed to frontend Logs tab even after changing log_level to info or debug in frontend (output to file works then)

## What did you expect to happen
Logs should be properly outputed to Logs tab in frontend at all initial log levels

## How to reproduce it (minimal and precise)
1. Set in configuration:
`"log_level": "warn",`
2. Restart zigbee2mqtt
3. Observe no logs output in frontend Logs tab
4. Change log level to info or debug in frontend
5. Observe still no logs in Logs tab

## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: CC26X2R1 zzh!
Adapter firmware version: 20201113

**Comment by Koenkk** [comment]
Fixed, thanks for reporting.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
