### ISSUE TITLE
Zigbee2mqtt crashing during device pairing

### ISSUE THREAD

**Issue by yevgenb** [Koenkk/zigbee2mqtt#5636]
## What happened

Zigbee2mqtt crashing during device pairing. Started after upgrade from v 1.14.2 - worked fine before.

## Debug info
Zigbee2MQTT version:  1.17.0 
Adapter hardware: cc2530 + cc2591
Adapter firmware version: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'

**Comment by yevgenb** [comment]
[z2m.log](https://github.com/Koenkk/zigbee2mqtt/files/5788822/z2m.log)

**Comment by yevgenb** [comment]
Configuration:

{
  "external_converters": [],
  "devices": [
    "devices.yaml"
  ],
  "groups": [
    "groups.yaml"
  ],
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://core-mosquitto",
    "user": "mqtt",
    "password": "...."
  },
  "serial": {
    "port": "/dev/ttyUSB0"
  },
  "advanced": {
    "log_level": "info",
    "pan_id": 6754,
    "channel": 11,
    "network_key": [ ....  ],
    "availability_blocklist": [],
    "availability_passlist": []
  },
  "device_options": {},
  "blocklist": [],
  "passlist": [],
  "queue": {},
  "frontend": {
    "port": 8099
  },
  "experimental": {
    "new_api": true
  }
}

**Comment by Koenkk** [comment]
`Zigbee2MQTT:error 2021-01-08 10:17:45: Adapter disconnected, stopping` looks that the USB adapter disconnected, can happen for many reason. Suggestions on how to fix can be found under: https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start

**Comment by yevgenb** [comment]
As I mentioned - it was working fine for 6 month and started to crash after upgrade to 1.17.0. The hardware is the same, no updates to OS.

**Comment by yevgenb** [comment]
Forgot to mention - it's same device that was paired and worked with zigbee2mqtt before.

**Comment by yevgenb** [comment]
Hmm - very strange, after plugging and unplugging stick it started to work again. Closing issue - thank you Koen!
