### ISSUE TITLE
Bitron AV2010 / 32 has no valve, but is displayed as NA? (pi_heating_demand)

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#5651]
Hello, Bitron AV2010 / 32 recently started to watch pi_heating_demand, this is not correct because it has no Venitl.

Can you fix it please.
Thanks.

zigbee2mqtt version
1.17.0-dev commit: 77a6ec0
coordinator type
zStack3x0
coordinator revision
20201026
frontend version
0.3.2

![sshot-1](https://user-images.githubusercontent.com/32480002/104093276-d4da3700-5289-11eb-87a2-2ceeece210bd.jpg)

**Comment by Koenkk** [comment]
Done.

Changes will be available in the latest dev branch in tomorrow (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
