### ISSUE TITLE
Want to change device's Configure Reporting Interval 

### ISSUE THREAD

**Issue by zijings** [Koenkk/zigbee2mqtt#5664]
## Want to change device's Configure Reporting Interval(or heartbeat something) but do not know how
I want to change device's Configure Reporting Interval while do not change and flash the firmware. Zigbee3.0 seems to support this, but I do not sure whether zigbee2mqtt can do this, or how to implement?

**Comment by sledzik1984** [comment]
Yeah! That would be great feature. I have some WSDCGQ11LM sensors. That sensors reporting interval is quite long and charts made from data that came from that sensor are ugly. 

I have managed how to change reporting interval of Sonoff SNZB-02 but doing it was pretty hard and time consuming.

**Comment by Koenkk** [comment]
This is supported since Zigbee2mqtt 1.17.0, see https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestdeviceconfigure_reporting . Can also be done via the frontend, click on your device and go to the reporting tab.

**Comment by crowbarz** [comment]
I wanted to modify the reporting interval/min change settings as well to dial down updates from chatty devices (typically temperature, illumination and current), and had been patching zigbee-herdsman-converters (and rebasing after every z2m upgrade!) to change the model defaults until I discovered this feature.

Are the manually configured reporting changes persistent across z2m restarts, device reconfigures and/or z2m upgrades? I'm pretty sure that to date I have only seen the Zigbee configure commands being sent immediately after the initial interview at join time, but have not analysed the code to verify this.

**Comment by EnsuingRequiem** [comment]
> what are the units of measure in the reporting view?

I checked in the PDF referenced and it indicates the units are in seconds

> Allows to send a Zigbee configure reporting command to a device. Refer to the Configure Reporting Command in the ZigBee Cluster Library for more information.)

**Comment by spry-salt** [comment]
Do you find your sensors are still burning through their batteries at a fast rate?

**Comment by spry-salt** [comment]
Did you figure out how to slow down the reporting rate from these devices using z2m? I've got some Smartthings Multipurpose Sensors that are reporting every minute and I need to slow them down because they're burning through their batteries.

@EnsuingRequiem @crowbarz @sledzik1984

**Comment by crowbarz** [comment]
> This is supported since Zigbee2mqtt 1.17.0, see https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgerequestdeviceconfigure_reporting . Can also be done via the frontend, click on your device and go to the reporting tab.

Did you try this from a few posts earlier: https://github.com/Koenkk/zigbee2mqtt/issues/5664#issuecomment-757493678

**Comment by spry-salt** [comment]
> Did you try this from a few posts earlier: [#5664 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/5664#issuecomment-757493678)

Thanks, I did but it either refused to change them (any of the attributes to do with the accelerometer) or it had no effect on the reporting frequency (temperature, battery). Were you successful?

**Comment by crowbarz** [comment]
IIRC the accelerometer reporting settings would update as long as the sensor was reporting to the controller just before/after you clicked Apply (as with all battery operated sensors), **and** you changed the settings immediately after removing and re-adding them to Z2M. But my own Smartthings multipurpose sensors (note there are many different versions of these) have long ago been replaced with far simpler Sonoff contact sensors that were not so painful to manage.
