### ISSUE TITLE
aqara motion/illunimance

### ISSUE THREAD

**Issue by tarbax** [Koenkk/zigbee2mqtt#567]
i have two aqara motion/illunimance model: rtcgq11lm

1 of the 2 works with a:
sensor.0x00158d0002b43af8_illuminance
binary_sensor.0x00158d0002b43af8_occupancy

but the second device gives this:
![image](https://user-images.githubusercontent.com/34491557/48021300-80cae980-e138-11e8-8935-b8081ef73eeb.png)
in the zigbee2mqtt log: 
unkown - undefined unknown (EndDevice)

**Comment by Koenkk** [comment]
Remove all entries with that ieeAddr from `database.db` and repair (make sure you correctly follow the pairing procedure).

**Comment by tarbax** [comment]
`  zigbee2mqtt:info 2018-11-5 21:43:18 Zigbee: allowing new devices to join.
  zigbee2mqtt:info 2018-11-5 21:43:44 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:43:44 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:08 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:08 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:11 New device with address 0x00158d0002b47b8c connected!
  zigbee2mqtt:info 2018-11-5 21:44:11 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"device_connected","message":"0x00158d0002b47b8c"}'
  zigbee2mqtt:info 2018-11-5 21:44:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":1,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:44:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"0/0x00124B0018ED3C74","type":"COORD","rssi":25,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:44:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"55130/0x0017880103CBAE9B","type":"CHILD_RFD","rssi":14,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:44:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":1,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:44:34 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:34 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":73,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:53 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:44:53 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:45:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":1,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:45:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"0/0x00124B0018ED3C74","type":"COORD","rssi":25,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:45:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"55130/0x0017880103CBAE9B","type":"CHILD_RFD","rssi":14,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:45:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":3,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:45:14 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:45:14 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:45:26 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:45:26 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:46:04 MQTT publish, topic: 'zigbee2mqtt/0x0017880103cbae9b', payload: '{"battery":100,"linkquality":31}'
  zigbee2mqtt:info 2018-11-5 21:46:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":3,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:46:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"0/0x00124B0018ED3C74","type":"COORD","rssi":24,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:46:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"55130/0x0017880103CBAE9B","type":"CHILD_RFD","rssi":10,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:46:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":2,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:46:14 Device incoming...
  zigbee2mqtt:info 2018-11-5 21:46:14 MQTT publish, topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"pairing","message":"device incoming"}'
  zigbee2mqtt:info 2018-11-5 21:46:17 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:46:17 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:46:41 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":65,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:46:41 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":65,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":2,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:47:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"0/0x00124B0018ED3C74","type":"COORD","rssi":25,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:47:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"55130/0x0017880103CBAE9B","type":"CHILD_RFD","rssi":10,"linkquality":31,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:47:12 MQTT publish, topic: 'zigbee2mqtt/0x00124b0018ed3d9d', payload: '{"description":"40653/0x001788010302CA10","type":"NEIGHBOR","rssi":1,"linkquality":28,"state":false}'
  zigbee2mqtt:info 2018-11-5 21:47:13 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:13 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":68,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:23 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:23 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:29 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:29 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":70,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:41 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":73,"occupancy":true}'
  zigbee2mqtt:info 2018-11-5 21:47:41 MQTT publish, topic: 'zigbee2mqtt/0x00158d0002b43af8', payload: '{"illuminance":1000,"linkquality":73,"occupancy":true}'`

**Comment by tarbax** [comment]
3rd try after deleting the adresses:
Failed to configure 0x0017880103cbae9b 0x0017880103cbae9b

**Comment by lolorc** [comment]
for undefined entries, I edit database.db, keep one entry for the specified ieeeAddr and add the missing fields, most of the time it's missing manufName, powerSource and modelId.

**Comment by Koenkk** [comment]
@tarbax what kind of device is: 0x0017880103cbae9b?

**Comment by Koenkk** [comment]
But thats a different device then you are having problems with, right?

**Comment by tarbax** [comment]
> But thats a different device then you are having problems with, right?

0x00124b0018ed3d9d is the problem

**Comment by Koenkk** [comment]
`0x00124b0018ed3d9d` is the CC2530 router?

**Comment by tarbax** [comment]
sorry im getting confused it is 0x00158d0002b47b8c
it stated connected but didnt show up anywhere :-/

**Comment by tarbax** [comment]
after a reinstall it is working. i think i had something screwed up in the database to delete some entities
