### ISSUE TITLE
zcl frame format of Read current brightness level of hue device?what will be payload to read data?

### ISSUE THREAD

**Issue by jinujosefrancis** [Koenkk/zigbee2mqtt#569]
Unsupported device
First check: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices

Bug report
- First make sure your on the latest version of zigbee2mqtt.
- Make sure you are running the latest CC253X firmware from https://github.com/koenkk/z-stack-firmware.
- Provide a clear description of the problem.
- If applicable, provide steps how to reproduce the problem.
- Provide a log with `log_level` set to `debug`, see https://github.com/Koenkk/zigbee2mqtt/wiki/Configuration
- DON'T copy logs directly here, post a link to https://hastebin.com/ or https://pastebin.com/.

**Comment by Koenkk** [comment]
Read commands will be implemented here: https://github.com/Koenkk/zigbee2mqtt/issues/518
