### ISSUE TITLE
Add Sunricher Single-Line switch/dimmer & philips hue giant bulb

### ISSUE THREAD

**Issue by philyholiday** [Koenkk/zigbee2mqtt#5693]
Hi,

Thank you so much for working on this project, this is freaking amazing.
I'm very sorry to open an issue, but I added support for new sunricher single-line switches in devices.js using docker.
All is working perfectly fine but I don't know how to pull/push/merge, etc.

Entries added to devices.js:

{
        zigbeeModel: ['SR-ZG9040A-S'],
        model: 'SR-ZG9040A-S',
        vendor: 'Sunricher',
        description: 'ZigBee AC phase-cut dimmer single-line',
        extend: preset.light_onoff_brightness,
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await reporting.onOff(endpoint);
        },
    },

AND

{
        zigbeeModel: ['Micro Smart OnOff'],
        model: 'SR-ZG9100A-S',
        vendor: 'Sunricher',
        description: 'Zigbee AC in wall switch single-line',
        extend: preset.switch,
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1) || device.getEndpoint(3);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint);
        },
    },

I also added support for new philips hue giant bulb model "9290024592".

{
        zigbeeModel: ['LWV003'],
        model: '9290024592',
        vendor: 'Philips',
        description: 'Hue White Filament ST72 Giant Edison',
        meta: {turnsOffAtBrightness1: true},
        extend: preset.hue.light_onoff_brightness,
        ota: ota.zigbeeOTA,
    },

no new converters, etc. needed.
Would be awsome if you could include those in a new release. If you need pictures or more info, I'm happy to help, just need some guidance. :-)

**Comment by Koenkk** [comment]
Added, the `9290024592` is already supported (in the dev branch only)

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
