### ISSUE TITLE
Xiaomi WXKG11LM cannot be bound

### ISSUE THREAD

**Issue by samtun** [Koenkk/zigbee2mqtt#5695]
I just bought a Xiaomi WXKG11LM (modelID: lumi.remote.b1acn01) and followed the docs to integrate it:
- I added `legacy: false` to the device's configuration
- The device is seen by the coordinator and click, double, hold and release actions are correctly reported in the log

The entry in my configuration looks like this:
```
'0x00158d0004019781':
  friendly_name: OfficeSwitch
  legacy: false
```
## What happened

Trying to bind this device to any lamp or group just gives me this:
```
...: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"from":"OfficeSwitch","to":"office"},"type":"device_bind_failed"}'
...: Nothing to bind
```

I tried the following bind commands (office is my group name, I also tried other lamps friendly names and ids):
```
mosquitto_pub -t zigbee2mqtt/bridge/bind/OfficeSwitch -m "office"
mosquitto_pub -t zigbee2mqtt/bridge/bind/OfficeSwitch/1 -m "office"
```

## What did you expect to happen

The button should be bound to the lamp / group of lamps

## Debug info
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531
Adapter firmware version: latest from https://github.com/jmichault/flash_cc2531

**Comment by Koenkk** [comment]
This device doesn't support binding.
