### ISSUE TITLE
Ledvance Smart+ Motion Sensor

### ISSUE THREAD

**Issue by CBismark** [Koenkk/zigbee2mqtt#5701]
Hello everyboy,

I tried to pair a Ledvance Smart+ Motion Sensor, but that didn't work. I was under the impression that this device is basically an OSRAM Smart+ Motion sensor, which is supported. However, that didn't turn out to be the truth.

Below the database entry generated by zigbee2mqtt.

`{"id":22,"type":"EndDevice","ieeeAddr":"0x000d6f000bb30004","nwkAddr":29656,"manufId":4174,"epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[25],"clusters":{},"binds":[],"meta":{}},"2":{"epId":2,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1610388791828}`

As you cansee, the interview doesn't complete.

Any chance this device can be supported?

Kind Regards,

Christoph

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when pairing it?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by CBismark** [comment]
From the point where I started the pairing process:

`zigbee-herdsman:controller:log Device '0x000d6f000bb30004' joined +22s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' accepted by handler +0ms
  zigbee-herdsman:controller:log New device '0x000d6f000bb30004' joined +0ms
  zigbee-herdsman:controller:log Creating device '0x000d6f000bb30004' +1ms
Zigbee2MQTT:info  2021-01-11 20:07:41: Device '0x000d6f000bb30004' joined
  zigbee-herdsman:controller:log Interview '0x000d6f000bb30004' start +39ms
Zigbee2MQTT:info  2021-01-11 20:07:41: Starting interview of '0x000d6f000bb30004'
  zigbee-herdsman:controller:device:log Interview - start device '0x000d6f000bb30004' +0ms
Zigbee2MQTT:info  2021-01-11 20:07:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x000d6f000bb30004"},"type":"device_connected"}'
Zigbee2MQTT:info  2021-01-11 20:07:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6f000bb30004"},"type":"pairing"}'
  zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x89af EP:0 SeqNr. 37 request id: 7 +97ms
  zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 7 status: 0 +99ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110 +584ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +583ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110 +7ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +7ms
  zigbee-herdsman:deconz:driver query aps data confirm +9ms
  zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 38 +100ms
  zigbee-herdsman:deconz:driver query aps data indication +0ms
  zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x89af request id: 7 confirm status: 0 +111ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:driver query aps data indication +1ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 39 +97ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 39 srcAddr: 0x89af destAddr: 0x0 profile id: 0x0 cluster id: 0x8002 +100ms
  zigbee-herdsman:deconz:frameParser response payload: 7,0,175,137,2,64,128,78,16,82,82,0,0,0,82,0,0 +0ms
  zigbee-herdsman:deconz:adapter resolve data request without a transSeq Nr. +22s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:deconz:adapter RECEIVING NODE_DESCRIPTOR - addr: 0x89af type: EndDevice manufacturer: 0x104e +1ms
  zigbee-herdsman:controller:device:log Interview - got node descriptor for device '0x000d6f000bb30004' +866ms
  zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x89af EP:0 SeqNr. 41 request id: 8 +97ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 40 +0ms
  zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 8 status: 0 +100ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr.: 40 status: 5 +3ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +639ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +642ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110 +50ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +50ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110 +6ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +6ms
  zigbee-herdsman:deconz:driver query aps data confirm +3ms
  zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 42 +98ms
  zigbee-herdsman:deconz:driver query aps data indication +2ms
  zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x89af request id: 8 confirm status: 0 +103ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +1ms
  zigbee-herdsman:deconz:driver query aps data indication +0ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 43 +97ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 43 srcAddr: 0x89af destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +101ms
  zigbee-herdsman:deconz:frameParser response payload: 2,253,255,4,1,0,1,0,5 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +4ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 44 +97ms
  zigbee-herdsman:deconz:driver query aps data indication +2ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 44 srcAddr: 0x89af destAddr: 0x0 profile id: 0x0 cluster id: 0x8005 +100ms
  zigbee-herdsman:deconz:frameParser response payload: 8,0,175,137,2,1,2 +1ms
  zigbee-herdsman:deconz:adapter resolve data request without a transSeq Nr. +1s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +1ms
  zigbee-herdsman:deconz:adapter ACTIVE_ENDPOINTS - addr: 0x89af EP list: 1,2 +1ms
  zigbee-herdsman:controller:device:log Interview - got active endpoints for device '0x000d6f000bb30004' +1s
  zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x89af EP:0 SeqNr. 46 request id: 9 +96ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 45 +1ms
  zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 9 status: 0 +98ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +1ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr.: 45 status: 5 +3ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110 +589ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +592ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110 +8ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +8ms
  zigbee-herdsman:deconz:driver query aps data confirm +0ms
  zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 47 +99ms
  zigbee-herdsman:deconz:driver query aps data indication +2ms
  zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x89af request id: 9 confirm status: 0 +101ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +0ms
  zigbee-herdsman:deconz:driver query aps data indication +1ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 48 +97ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 48 srcAddr: 0x89af destAddr: 0x0 profile id: 0x0 cluster id: 0x8004 +100ms
  zigbee-herdsman:deconz:frameParser response payload: 9,0,175,137,24,1,4,1,2,4,0,7,0,0,1,0,3,0,32,0,2,4,0,5,5,11,1,25,0 +0ms
  zigbee-herdsman:deconz:adapter resolve data request without a transSeq Nr. +898ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:adapter RECEIVING SIMPLE_DESCRIPTOR - addr: 0x89af EP:1 inClusters: 0,1,3,32,1026,1280,2821 outClusters: 25 +1ms
  zigbee-herdsman:controller:device:log Interview - got simple descriptor for endpoint '1' device '0x000d6f000bb30004' +897ms
  zigbee-herdsman:controller:endpoint Read 0x000d6f000bb30004/1 genBasic(["modelId"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) +24s
  zigbee-herdsman:deconz:adapter zclFrame.payload: +4ms
  zigbee-herdsman:deconz:adapter [ { attrId: 5 } ] +0ms
  zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x89af EP:1 SeqNr. 50 request id: 10 +98ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 49 +1ms
  zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 10 status: 0 +101ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr.: 49 status: 5 +2ms
  zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 51 +2s
  zigbee-herdsman:deconz:frameParser device state: 10100010 +2s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +5s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +5s
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +6ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +6ms
  zigbee-herdsman:deconz:driver query aps data indication +81ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 52 +96ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 52 srcAddr: 0x17a2 destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +178ms
  zigbee-herdsman:deconz:frameParser response payload: 3,253,255,4,1,0,1,70,252 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +1ms
  zigbee-herdsman:deconz:driver query aps data indication +3ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 53 +96ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 53 srcAddr: 0x17a2 destAddr: 0xfffd profile id: 0x0 cluster id: 0x13 +100ms
  zigbee-herdsman:deconz:frameParser response payload: 130,162,23,4,0,179,11,0,111,13,0,128 +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' joined +10s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' accepted by handler +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' is already in database with different networkAddress, updating networkAddress +0ms
  zigbee-herdsman:controller:log Not interviewing '0x000d6f000bb30004', completed 'false', in progress 'true' +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110 +358ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +357ms
  zigbee-herdsman:deconz:driver query aps data confirm +47ms
  zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 54 +94ms
  zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x89af request id: 10 confirm status: 0 +142ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +1ms
  zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 6 +8s
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +1s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +1s
  zigbee-herdsman:deconz:driver query aps data indication +24ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 55 +93ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 55 srcAddr: 0x17a2 destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +119ms
  zigbee-herdsman:deconz:frameParser response payload: 4,253,255,4,1,0,1,0,5 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 56 +3s
  zigbee-herdsman:deconz:frameParser device state: 10100010 +3s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +7s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +7s
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +6ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +6ms
  zigbee-herdsman:deconz:driver query aps data indication +74ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 57 +99ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 57 srcAddr: 0x448f destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +175ms
  zigbee-herdsman:deconz:frameParser response payload: 5,253,255,4,1,0,1,70,252 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:driver query aps data indication +99ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 58 +99ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 58 srcAddr: 0x448f destAddr: 0xfffd profile id: 0x0 cluster id: 0x13 +201ms
  zigbee-herdsman:deconz:frameParser response payload: 131,143,68,4,0,179,11,0,111,13,0,128 +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' joined +12s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +4ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' accepted by handler +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' is already in database with different networkAddress, updating networkAddress +0ms
  zigbee-herdsman:controller:log Not interviewing '0x000d6f000bb30004', completed 'false', in progress 'true' +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +2s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +2s
  zigbee-herdsman:deconz:driver query aps data indication +76ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 59 +100ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 59 srcAddr: 0x448f destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +178ms
  zigbee-herdsman:deconz:frameParser response payload: 6,253,255,4,1,0,1,0,5 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 60 +1s
  zigbee-herdsman:deconz:frameParser device state: 10100010 +1s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +8s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +8s
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +6ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +6ms
  zigbee-herdsman:deconz:driver query aps data indication +3ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 61 +100ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 61 srcAddr: 0xa384 destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +106ms
  zigbee-herdsman:deconz:frameParser response payload: 7,253,255,4,1,0,1,70,252 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:deconz:driver query aps data indication +98ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 62 +100ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 62 srcAddr: 0xa384 destAddr: 0xfffd profile id: 0x0 cluster id: 0x13 +200ms
  zigbee-herdsman:deconz:frameParser response payload: 132,132,163,4,0,179,11,0,111,13,0,128 +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' joined +12s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' accepted by handler +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' is already in database with different networkAddress, updating networkAddress +0ms
  zigbee-herdsman:controller:log Not interviewing '0x000d6f000bb30004', completed 'false', in progress 'true' +2ms
  zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 63 +1s
  zigbee-herdsman:deconz:frameParser device state: 10100010 +1s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +2ms
  zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010 +115ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1 +115ms
  zigbee-herdsman:deconz:driver query aps data indication +89ms
  zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 64 +99ms
  zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 64 srcAddr: 0xa384 destAddr: 0xfffd profile id: 0x0 cluster id: 0x6 +191ms
  zigbee-herdsman:deconz:frameParser response payload: 8,253,255,4,1,0,1,0,5 +0ms
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms`

**Comment by Koenkk** [comment]
Can you provide it till interview failed?

**Comment by CBismark** [comment]
I added the full log. But if I unterstand you correctly, you wanted the log until an interview failed happens and, well that doesn't really happen.
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/5804742/log.txt)

As you can see, repeatedly the device rejoins,gets an updated network address and then it says: not interviewing:

`  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' joined +2s
  zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1 +3ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' accepted by handler +0ms
  zigbee-herdsman:controller:log Device '0x000d6f000bb30004' is already in database with different networkAddress, updating networkAddress +1ms
  zigbee-herdsman:controller:log Not interviewing '0x000d6f000bb30004', completed 'false', in progress 'true' +2ms`

Not sure whats going on there. I also can't seem to get the device into the state from the beginning, no matter how long I leave the battery out and how long or short I press the button during inserting the battery again.
Tried it the way it says for the OSRAM sensor: https://www.zigbee2mqtt.io/devices/AC01353010G.html

Kind Regards,

Christoph

**Comment by Koenkk** [comment]
Very strange, I'm afraid we have to sniff the traffic while joining to get more info: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by CBismark** [comment]
Hm okay sounds doable. I got some extra CC2531 lying around here, but no programmer to flash them. Maybe I can get one and then try that. I'll be in contact once I got results!

**Comment by CBismark** [comment]
I bought a CCDebugger and flashed an old CC2531 with it, sniffed while powering on the motion sensor. Here is the result as a Wireshark Capture File. Where it says 'Beacon' is when I put the battery in the sensor.
[sniff.zip](https://github.com/Koenkk/zigbee2mqtt/files/5816601/sniff.zip)

**Comment by Koenkk** [comment]
I think the devices keeps resetting because the `Match descriptor request` is never answered. This device expects cluster `0x0500` as an output cluster.  @chrishae can you add this cluster

![image](https://user-images.githubusercontent.com/2892853/104767160-02345280-576c-11eb-811f-1f0016f9b211.png)

**Comment by ChrisHae** [comment]
There is already the Cluster 0x500 in the deCONZ adapter.
@CBismark Which FW version do you use? You should updat to the latest: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
You can also try to re-pair the motion sensor when you delete it from the z2mqtt database first.
@Koenkk Shouldn't the IAS Zone enroll Request be independent of the match descriptor request?

**Comment by CBismark** [comment]
Did a Firmware update and the problem persists. Sniffed again, maybe you can make something out of it:
@ChrisHae I usually delete from configuration and database (while zigbee2mqtt is stopped), then try to pair.
[sniff2.zip](https://github.com/Koenkk/zigbee2mqtt/files/5830423/sniff2.zip)

**Comment by ChrisHae** [comment]
@CBismark Do you have deCONZ installed? You could already check if the cluster 0x500 is missing. The Z2mqtt code is coming soon.
![image](https://user-images.githubusercontent.com/12135523/105036931-81bc6d00-5a5d-11eb-9400-bb66799c76af.png)

**Comment by CBismark** [comment]
@ChrisHae I don't have a Linux with a GUI installed, only running OpenHAB on the standard openHabian (Raspian). If I would install deconz as a service, can I also check for the Cluster?

**Comment by ChrisHae** [comment]
Ok, I have added the simple descriptor and cluster check to zigbee-herdsman code. Wait until new z2mqtt release and then try it again. It should be visible in the debug log during startup. If this does not solve the problem, then it must be something else.

**Comment by Koenkk** [comment]
@ChrisHae your fix is available in the latest dev now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by CBismark** [comment]
Thank you both a lot for the quick help. With dev branch interviewing and pairing worked and the device is now recognized as a Motion Sensor-A.
I'll close this now.
