### ISSUE TITLE
Add Devices

### ISSUE THREAD

**Issue by rodrigorsdev** [Koenkk/zigbee2mqtt#5726]
Hello, I'm trying to add devices that are on the list of supported, but have not been recognized:

## 1. Information about the device + link
https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html

## data/database.db entry of the device
`{"id":11,"type":"Unknown","ieeeAddr":"0x00158d0003faf120","nwkAddr":22339,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65281":{"1":3005,"3":38,"4":17320,"5":45,"6":[0,0],"10":53917,"11":173,"100":0}}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":72}},"msOccupancySensing":{"attributes":{"occupancy":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1610484328465}`

## 2. Information about the device + link
https://www.zigbee2mqtt.io/devices/WXKG01LM.html

## data/database.db entry of the device
`{"id":15,"type":"EndDevice","ieeeAddr":"0x00158d00033ef5e9","nwkAddr":24361,"manufId":4151,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":1},{"elmType":33,"elmVal":3012},{"elmType":33,"elmVal":17320},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":1003},{"elmType":32,"elmVal":80}]}}},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1610487436689}`

## 3. Information about the device + link
https://www.zigbee2mqtt.io/devices/BW-IS3.html

## data/database.db entry of the device
{"id":16,"type":"Unknown","ieeeAddr":"0x00158d00035fe9f0","nwkAddr":7907,"epList":[1],"endpoints":{"1":{"epId":1,"inClusterList":[],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"65281":{"1":3045,"3":30,"4":17320,"5":38,"6":[0,2],"10":53917,"11":0,"100":0}}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":56}},"msOccupancySensing":{"attributes":{"occupancy":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":false,"meta":{},"lastSeen":1610488402490}

Thanks

**Comment by Koenkk** [comment]
These devices are supported, that's not the issue. The issue here is that the interview failed: `"interviewCompleted":false,`. Check: https://www.zigbee2mqtt.io/information/FAQ.html#interview-fails
