### ISSUE TITLE
SNZB-02 Sonoff Temperatura Sensor paired but not return data 

### ISSUE THREAD

**Issue by srtxema** [Koenkk/zigbee2mqtt#5729]
Zigbee2mqtt paired snzb-02 after press for 5 seconds but 2 hours after then it don´t return data yet

![image](https://user-images.githubusercontent.com/18092080/104434504-95faf880-558b-11eb-82e4-a19eed7cfc92.png)
![image](https://user-images.githubusercontent.com/18092080/104434541-a01cf700-558b-11eb-98a5-03c4a039c323.png)

**Comment by passy05** [comment]
Mine is working fine, I can see the following message in the log:
info  2021-01-13 09:47:33: MQTT publish: topic 'zigbee2mqtt/Sonoff Temperature', payload '{"battery":100,"humidity":66.13,"linkquality":18,"temperature":23.13,"voltage":3200}'

**Comment by srtxema** [comment]
I use conbee broker. I have snzb-03 and 04 that works correctly but this not return data

**Comment by sjorge** [comment]
> I use conbee broker. I have snzb-03 and 04 that works correctly but this not return data

What does the reporting tab show?

**Comment by srtxema** [comment]
i have removed for 3 times and aften then i obtain data
![image](https://user-images.githubusercontent.com/18092080/104454632-71604a00-55a6-11eb-8fad-d3c6bf6ffcae.png)
thanks!

**Comment by sjorge** [comment]
That looks correct, make sure to force remove them, they don't seem to want to leave. 
After a force remove they usually pair OK for me.

**Comment by srtxema** [comment]
Thanks sjorge!
