### ISSUE TITLE
Split out device config from configuration.yml

### ISSUE THREAD

**Issue by xoxys** [Koenkk/zigbee2mqtt#573]
Hi,
i try to setup zigee2mqtt with ansible but it is very hard to manage zigbee2mqtt with a config management system if you have a config file with static and dynamic values (like devices). So i would love to see an option to specify a separate file for device informations.

Maybe something like:
```yaml
devices:
    file: /opt/zigbee2mqtt/data/devices.yml
```

Thanks for your great work
Edit: If you accept pull requests, i can give it a try and dig into it

**Comment by xoxys** [comment]
I like it! Will have a look on this at the next days

**Comment by thinkl33t** [comment]
Is anyone looking at this?  It would be very useful for our ansible-orchestrated zigbee2mqtt systems :)

**Comment by xoxys** [comment]
I have done some first steps locally. But i can't find a good library for that the most of them are outdated. 

The other way is to use a simple string compare/regex to detect !import but it feels a little bit hacky and dirty. @Koenkk what do you think?

**Comment by Koenkk** [comment]
That feels indeed hacky, could you find out how home assistant does this?

**Comment by clockbrain** [comment]
Don't know how home assistant does it but surely leveraging something like [https://www.npmjs.com/package/yaml-include](https://www.npmjs.com/package/yaml-include)
 or 
[https://www.npmjs.com/package/yaml-import](https://www.npmjs.com/package/yaml-import) would be the way to go about it.

**Comment by thinkl33t** [comment]
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/util/yaml.py

Looks like they've extended the yaml parser.

**Comment by xoxys** [comment]
@clockbrain yes that are the libraries i am talking about. But both of them are outdated and i am not sure if one of them is a solid base to start with..

**Comment by scoootec** [comment]
@Koenkk could we consider having a seperate devices.yaml by default?

That way configuration.yaml is limited to static configuration only. It would allow much easier automatic config generation in a hassio-addon as an example.

**Comment by xoxys** [comment]
I think this would be easier to achieve as struggling around with an include setup. Because this would be a breaking change we can make it optional with an opt-in attribute in the config.

**Comment by rasmusson** [comment]
@xoxys any chance of this coming to life?

**Comment by xoxys** [comment]
Devices and groups can be managed in a dedicated file already https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#extract-config-to-separate-files

**Comment by rasmusson** [comment]
Awesome I interpreted the stale notice as it just died
