### ISSUE TITLE
Pairing Problems CC2531

### ISSUE THREAD

**Issue by paulhonka** [Koenkk/zigbee2mqtt#574]
New Xiaomi Aqara temperature sensors, window sensors and Xiaomi Honywell smoke sensors can not be paired.
That's no problem with old sensors.
On the Xiaomi MiHome Hub that works without problems.

**Comment by pixeldoc2000** [comment]
Please provide Log Output from zigbee2mqtt. Otherwise we have to information to help you.

Look at: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-debug
