### ISSUE TITLE
Adding new device - problems

### ISSUE THREAD

**Issue by clem983** [Koenkk/zigbee2mqtt#5742]
## Information about the device + link
Hello, I'm trying to add a Zigbee roller shutter into Zigbee2Mqtt. Here is the link. Sorry, it's only French : https://www.profalux-pro.com/documentations/1.%20Notices,%20Plans,%20Technique/1.%20Volets%20roulants/3.%20Moteurs%20Commandes%20et%20Accessoires/1.%20Moteur/Moteur%20Profalux%20Zigbee/

I dont find the zigbeeModel in the logs, I have only this kind of things : 

`info  2021-01-14 19:35:17: 0x20918a00000cb984 (0x20918a00000cb984): Not supported (EndDevice)`
`info  2021-01-14 19:35:17: 0x20918a00000cb983 (0x20918a00000cb983): Not supported (Router)`

So, I don't know what to put for the key zigbeeModel of devices.js

Could you help me please ? :)

Thank you

## data/database.db entry of the device
```JSON
{"id":4,"type":"EndDevice","ieeeAddr":"0x20918a00000cb984","nwkAddr":14981,"manufId":4368,"powerSource":"Unknown","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":513,"inClusterList":[0,3,21],"outClusterList":[3,4,5,6,8,256,64544,64545],"clusters":{"genBasic":{"attributes":{"powerSource":0,"zclVersion":1,"dateCode":"20170309` NA 064"}}},"binds":[]}},"dateCode":"20170309 NA `064","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1609279596779}
```

```JSON
{"id":5,"type":"Router","ieeeAddr":"0x20918a00000cb983","nwkAddr":39762,"manufId":4368,"powerSource":"Mains (single phase)","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":512,"inClusterList":[0,3,4,5,6,8,10,21,256,64544,64545],"outClusterList":[3,64544],"clusters":{"genBasic":{"attributes":{"powerSource":1,"zclVersion":1,"dateCode":"20180723102c104"}}},"binds":[]}},"dateCode":"20180723102c104","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1606418803570}
```

**Comment by pixeldoc2000** [comment]
Looks like the the Device need addition commands to get more Info from it as your database has `"interviewCompleted":true` .

"manufId":4368
"devId":512

Enable debug logging set in configuration.yaml and repair the Device:

```
advanced:
  log_level: debug
```

Check: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
