### ISSUE TITLE
Xiaomi Magic Cube (MFKZQ01LM) side attribute broken in HA when legacy: false

### ISSUE THREAD

**Issue by Mr-Groch** [Koenkk/zigbee2mqtt#5744]
## What happened
If I set `legacy: false` for [Xiaomi Magic Cube (MFKZQ01LM) ](https://www.zigbee2mqtt.io/devices/MFKZQ01LM.html#xiaomi-mfkzq01lm) then `side` attribute that is exposed to HA in auto discovery is not updating (`action_side` attribute in MQTT topic is updating for a short time only, but this is not permanent attribute in HA)

## What did you expect to happen
Also for `legacy: false` setting it shoul be possible to always read on what side cude is in HA entity

## How to reproduce it (minimal and precise)
1. Set `legacy: false` in devices.yaml for [Xiaomi Magic Cube (MFKZQ01LM) ](https://www.zigbee2mqtt.io/devices/MFKZQ01LM.html#xiaomi-mfkzq01lm)
2. Flip cube and observe that `side` attribute is not updating

## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware:  CC26X2R1 zzh!
Adapter firmware version: 20201113

**Comment by Koenkk** [comment]
Fixed, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
