### ISSUE TITLE
How should it be configured in multi-network？

### ISSUE THREAD

**Issue by CaptainNeil** [Koenkk/zigbee2mqtt#5745]
## What happened
When I set the PAN ID to 0xFFFF, the coordinator automatically assigned a PAN ID. But when I restarted the coordinator, the coordinator's PAN ID changed again, causing me to need to repair the device.
## What did you expect to happen
I want the coordinator to automatically assign the PAN ID on the first boot and remember that it won't change on the next boot
@Koenkk 
## Note
I found some solutions online.I need the firmware source code and recompile it.
[https://www.ti2k.com/39806.html](https://www.ti2k.com/39806.html)

## Debug info
Zigbee2MQTT version:Lates version
Adapter hardware: CC2531, CC26X2R1
Adapter firmware version:CC2531_SOURCE_ROUTING_20190619,CC26X2R1_20201026

**Comment by CaptainNeil** [comment]
I found a solution to this problem.
Add the ZDNwkMgr defined symbols  when compiling firmware.
![image](https://user-images.githubusercontent.com/38662864/104696123-bf14b800-5748-11eb-89e0-a60a9736706a.png)
How to resolve PAN ID conflicts is described in the official documentation.

![image](https://user-images.githubusercontent.com/38662864/104696253-ee2b2980-5748-11eb-9b78-b3425dcf2f4e.png)

**Comment by CaptainNeil** [comment]
> I found a solution to this problem.
> Add the ZDNwkMgr defined symbols when compiling firmware.
> ![image](https://user-images.githubusercontent.com/38662864/104696123-bf14b800-5748-11eb-89e0-a60a9736706a.png)
> How to resolve PAN ID conflicts is described in the official documentation.
> 
> ![image](https://user-images.githubusercontent.com/38662864/104696253-ee2b2980-5748-11eb-9b78-b3425dcf2f4e.png)

This method is only valid for CC2530/1, not for CC26X2，I need your help

**Comment by CaptainNeil** [comment]
This method is only valid for CC2530/1, not for CC26X2，I need your help @Koenkk

**Comment by Koenkk** [comment]
The `0xFFFF` panID is currently not allowed. You have to define a static panID. I've modified zigbee-herdsman to throw an error in this case.

**Comment by CaptainNeil** [comment]
When the PAN ID is set to 0xFFFF, the coordinator will generate a random PAN ID, which effectively avoids the problem of PAN ID conflicts.Why disable 0xffff. @Koenkk

**Comment by Koenkk** [comment]
Because of:

> When I set the PAN ID to 0xFFFF, the coordinator automatically assigned a PAN ID. But when I restarted the coordinator, the coordinator's PAN ID changed again, causing me to need to repair the device.

and this is not something that can be fixed easily

**Comment by sjorge** [comment]
> Because of:
> 
> > When I set the PAN ID to 0xFFFF, the coordinator automatically assigned a PAN ID. But when I restarted the coordinator, the coordinator's PAN ID changed again, causing me to need to repair the device.
> 
> and this is not something that can be fixed easily

I guess we could go the GENERATE route like for network_key, to get a similar effect... were we pick one at random and write it back to the configuration file.

Of course we could still hit a duplicate though, and I don't think there is an easy way to check/catch that.

**Comment by CaptainNeil** [comment]
> > Because of:
> > > When I set the PAN ID to 0xFFFF, the coordinator automatically assigned a PAN ID. But when I restarted the coordinator, the coordinator's PAN ID changed again, causing me to need to repair the device.
> > 
> > 
> > and this is not something that can be fixed easily
> 
> I guess we could go the GENERATE route like for network_key, to get a similar effect... were we pick one at random and write it back to the configuration file.
> 
> Of course we could still hit a duplicate though, and I don't think there is an easy way to check/catch that.

This is exactly what I want. Because we need to deploy multiple coordinators in our office building. Assigning a static PAN ID to each coordinator is not very realistic. And this can easily cause PAN ID conflicts.

**Comment by CaptainNeil** [comment]
In addition, I recompiled the CC2531 firmware, adding ZDNwkMgr and NV_RESTORE predefined at compile time. When I set pan_id to 0xffff, the coordinator randomly generates a PAN ID. And the PAN ID will not be regenerated the next time ZigBee2MQTT is started.

However, this approach does not work with CC2652, which baffles me.
![image](https://user-images.githubusercontent.com/38662864/104901037-cee60380-59b7-11eb-91e4-e274aeb449cb.png)

**Comment by Koenkk** [comment]
@sjorge the `GENERATE` is indeed a good idea.

Implemented this now:

```yaml
advanced:
  pan_id: GENERATE
```

**Comment by CaptainNeil** [comment]
Thanks for your modification, is there any way to get the PAN ID of the surrounding network? Remove the duplicated PAN ID when generating the new PAN ID.

**Comment by Koenkk** [comment]
@CaptainNeil this information is not passed from the adapter to z2m, I think you can only get it by sniffing.

Assuming this can be closed now.

**Comment by CaptainNeil** [comment]
> @CaptainNeil this information is not passed from the adapter to z2m, I think you can only get it by sniffing.
> 
> Assuming this can be closed now.

Thank you very much
