### ISSUE TITLE
HLD812-Z-SC SUPPORT

### ISSUE THREAD

**Issue by pterodaktil02** [Koenkk/zigbee2mqtt#5753]
I  pluged HLD812-Z-SC  with  model no: HLD812-Z-SC-BS-1C_IA36V-OTA-3.0
By default it dont work in z2m it show another  model (not HOMA1008)
So i modified node_modules/herdsman-converters/devices.js to 
```
{
        zigbeeModel: ['HOMA1002', '00A'],
        model: 'HLD812-Z-SC',
        vendor: 'Shenzhen Homa',
        description: 'Smart LED driver',
        extend: preset.light_onoff_brightness,
    },
```
and all work fine pls update it

**Comment by Koenkk** [comment]
Done, thanks!
