### ISSUE TITLE
New version of Philips Hue Iris 2nd Version with BLE

### ISSUE THREAD

**Issue by trial-n-error** [Koenkk/zigbee2mqtt#5755]
Hi,

I bought a Philips Hue Iris (Generation 2) (similiar to https://github.com/Koenkk/zigbee2mqtt/issues/4722).

It broadcasts a different/new model ID 929002376201

To make it work I added to ./node_modules/zigbee-herdsman-converters/devices.js an additional zigbeeModel to the existing block:

    {
        zigbeeModel: ['929002376101', '929002376201'],
        model: '929002376101',
        vendor: 'Philips',
        description: 'Hue Iris (generation 2)',
        meta: {turnsOffAtBrightness1: true},
        extend: preset.hue.light_onoff_brightness_colorxy,
        ota: ota.zigbeeOTA,
    },

## Information about the device + link
Philips Hue Iris 2nd Version with BLE support

## data/database.db entry of the device
{"id":2,"type":"Router","ieeeAddr":"0x0017880109225507","nwkAddr":55450,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"929002376201","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":269,"inClusterList":[0,3,4,5,6,8,4096,768,64513],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"929002376201","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20190529","swBuildId":"1.56.7_r29434"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20190529","swBuildId":"1.56.7_r29434","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1610716370658}

**Comment by Koenkk** [comment]
Added, thanks!
