### ISSUE TITLE
HS2WD-E via Home Assistant ?

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#5779]
Hi

I bought a HS2WD-E model (siren) but I don't understand how can we trigger the alarm ON / OFF on Home Assistant ? 

Is it a easy way to do it ? 

I saw only LQI and Battery level on it. But I didn't see nothing around actions ect like Xiaomi switches for example :)

Thanks 

Regards

![image](https://user-images.githubusercontent.com/6093175/104821095-d54e7100-5839-11eb-8474-a529fa3713cd.png)

Not sure it's an issue according to the doc, indeed, I see only two values exposed (lqi and battery) so I'm a little bit confused to understand how it works.

**Comment by Koenkk** [comment]
Add the warning to exposes, can you check if it works correctly?

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by kevincaradant** [comment]
OK I will look it in few hours :)

Thanks

BTW: I was surprised that you have nothing about melodies and the volume of this siren.

I found a thread and at the end of this one, people seems have the choise about melody and almost the volume of the siren.

Why we haven't this choice with Z2M ? :)

Thanks

**Comment by Koenkk** [comment]
Good, can this issue be closed? The sound effect is controlled through the `mode`.

**Comment by kevincaradant** [comment]
Mhh I thought we will close this issue when the sound level will be fixed ? 

![image](https://user-images.githubusercontent.com/6093175/104836782-b9d27d00-58b0-11eb-9d24-68776e960412.png)


Low level here is very very strong as I said yesterday, pretty sure it doesn't work ;)

**Comment by Koenkk** [comment]
@kevincaradant I expect the sound level issue is in the firmware of the device (since the commands we send are according to the Zigbee spec) I think it doesn't support different sound levels, only way to be sure is to check it with the original gateway.

**Comment by kevincaradant** [comment]
oh alright. If we can't do nothing because it's a firmware issue ( very annoying in my case to setup my use cases :P) 
By consequence, I close this issue :)

Thanks

**Comment by kevincaradant** [comment]
One last thing @Koenkk 

Why I can't have the state ON / OFF on HA ? 

I removed the device from Z2M and pair it again with the latest version to be sure to have the state of the siren.

I have nothing in HA except battery and linkquality of the siren :/

![image](https://user-images.githubusercontent.com/6093175/104854418-e4e7bb80-5906-11eb-919a-8254acf9b566.png)

Any idea why ?

**Comment by Koenkk** [comment]
Because the alarm is not a simple on/off switch. You have to define a mode, sound level, duration, etc.

**Comment by kevincaradant** [comment]
alright I will try to look into it using mqtt requets thank you

**Comment by kovaga** [comment]
my 2 cents
Firmware: 2018.03.21

Setting the "level" values does make any difference, sounds the same.
Setting the "mode" values dpoesnt make any difference, sounds the same. (police_panic, fire_panic, emergency_panic are not accepted)

Has anyone actually verifed those with the original gateway?

**Comment by sebvdk** [comment]
I have the same issue. When I send warning payload :

`"warning": {
    "mode": "burglar",
    "level": "low",
    "strobe": true,
    "duration": 2
  }`

All working fine, except mode and level. However, this attributes are specified in documentation : https://www.zigbee2mqtt.io/devices/HS2WD-E.html#warning-composite

Thank you,

Zigbee2MQTT : 1.17.1
Device firmware : 2018.03.21

**Comment by orxaz** [comment]
Same here, mode and level have no effect.
Somebody know if it possible to upgrade siren firmware?

**Comment by mUbsta** [comment]
> Somebody know if it possible to upgrade siren firmware?

I've just received one of these with device firmware reporting 2021.2.19.  Unfortunately both mode & level still have no effect.

**Comment by 10der** [comment]
mode & level still have no effect.

**Comment by psy0rz** [comment]
same here..can anyone verify with the original gateway?

**Comment by MilorES** [comment]
I've just received one of these with device firmware reporting 2019.6.23. Unfortunately both mode & level still have no effect.

I have no original gateway to test. :(

**Comment by jhonny001** [comment]
Just received a new one and still none of the options work. It is just an ON/OFF alarm with the volume too high... Did any one find a solution?

**Comment by ovizii** [comment]
I'm also trying to figure this out, would love to hear from anyone who made any progress and doesn't mind sharing.

**Comment by MilorES** [comment]
No, still waiting for them to fix it.

**Comment by Iceman248** [comment]
I just bought one of them and same thing, mode and volume level cannot be changed.

**Comment by MilorES** [comment]
How could be done to fix it? (I guess some data is missing... or something)

**Comment by calas80** [comment]
same problem. News?

**Comment by baradetsky** [comment]
> @baradetsky can you please explain what works and what/where to insert this code you shared?

This is the code for setting the HS2WD-E siren as a switch in z2m home assistant. This is the usual yaml markup, for example, for a configuration file

**Comment by baradetsky** [comment]
> is this just an extra config to create a switch from the device which was added already via Z2M?
exactly!! this is the code for configuratoin.yaml in HA, not for z2m config
just replace the entity names with your own

**Comment by Iceman248** [comment]
> 

I did this, replacing the name in zigbee2mqtt with mine, but it just says not available. Even after restarting zigbee2mqtt, only the battery and link quality are reported through MQTT about my Siren.

**Comment by solarmill** [comment]
same.  Apparently the payload to turn it in needs to include 
```
"strobe_duty_cycle": VALUE
``` 
without this I could not get it to fire, but with it I could send a manual MQTT payload to activate.  Still no level control, and only one sound effect.  But if you send an on payload followed quickly (120ms) by an off payload you can make it chirp.
