### ISSUE TITLE
Issue with Hue Lux Bulbs

### ISSUE THREAD

**Issue by Imperial-Guard** [Koenkk/zigbee2mqtt#579]
Got last few days some issues with my Hue bulbs, this morning i repaired them and for the first couple of minutes it seems to be ok but after some minutes the following errors showed up:

I used this software for the CC2531: https://github.com/Koenkk/zigbee2mqtt/issues/533#issuecomment-433957384

2018-11-10 08:18:38 - info: Logging to directory: '/share/zigbee2mqtt/log/2018-11-10.08-18-38'
2018-11-10 08:18:39 - info: Starting zigbee2mqtt version 0.1.8 (commit #unknown)
2018-11-10 08:18:39 - info: Starting zigbee-shepherd
2018-11-10 08:18:42 - info: Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
2018-11-10 08:19:42 - info: Starting zigbee-shepherd
2018-11-10 08:19:49 - info: zigbee-shepherd started
2018-11-10 08:19:49 - info: Coordinator firmware version: '20180820'

`  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100e583da', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100e583da', genLevelCtrl - moveToLevelWithOnOff - {"level":255,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100e5818c', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100e5818c', genLevelCtrl - moveToLevelWithOnOff - {"level":255,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100de5366', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:40 Zigbee publish to '0x0017880100de5366', genLevelCtrl - moveToLevelWithOnOff - {"level":255,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:55 Zigbee publish to '0x0017880100e5818c', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:55 Zigbee publish to '0x0017880100e583da', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:21:56 Zigbee publish to '0x0017880100de5366', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:04 Zigbee publish to '0x0017880100e583da', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:04 Zigbee publish to '0x0017880100e5818c', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:04 Zigbee publish to '0x0017880100de5366', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:05 Zigbee publish to '0x0017880100e5818c', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:05 Zigbee publish to '0x0017880100e5818c', genLevelCtrl - moveToLevelWithOnOff - {"level":80,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:05 Zigbee publish to '0x0017880100e5818c', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:05 Zigbee publish to '0x0017880100e5818c', genLevelCtrl - moveToLevelWithOnOff - {"level":255,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:08 Zigbee publish to '0x0017880100e583da', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms
  zigbee2mqtt:error 2018-11-10 08:22:08 Zigbee publish to '0x0017880100e583da', genLevelCtrl - moveToLevelWithOnOff - {"level":255,"transtime":0} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Timed out after 30000 ms`

**Comment by Koenkk** [comment]
Could you:
- stop zigbee2mqtt
- press reset button on CC2531 (the one close to the usb outlet)
- start zigbee2mqtt

**Comment by Imperial-Guard** [comment]
Tried that last weekend several times, issues came up after some time again. 

Currently running a test with the coordinator and only Xiaomi battery powered devices and no issues since the last days.
