### ISSUE TITLE
Issue on Frontend

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#5796]
Hi

It's required to report it so I push it here :)

![image](https://user-images.githubusercontent.com/6093175/104849097-49dfe900-58e8-11eb-8499-dde8b3fffe1f.png)

I tried to search a specific device into logs using `*` in the field as first caracters and this happens ;)

**Comment by sjorge** [comment]
I think this should be fined here https://github.com/nurikk/z2m-frontend where the frontend lives.

**Comment by kevincaradant** [comment]
Thanks. Done

**Comment by Koenkk** [comment]
Should indeed be created in the frontend repo. Thanks @sjorge
