### ISSUE TITLE
How to pair Gledopto

### ISSUE THREAD

**Issue by khzd** [Koenkk/zigbee2mqtt#580]
Hello
Got a Gledopto and would like to know how to pair it
Any one do this operation ?
Thanks

**Comment by khzd** [comment]
Any news ?

**Comment by kirovilya** [comment]
@Koenkk no, but I know who has :)
We tried 2 devices:
007 - connected correctly and worked (although 008 is written in the converters)
008 - connected without the model name - did not work

I think the whole reason is either ZLL or Zigbee 3.0.

**Comment by khzd** [comment]
Thanks @kirovilya if you can share how to pair it ?
Cheers

**Comment by khzd** [comment]
Thanks @kirovilya if you can share how to pair it ?
Thanks @Koenkk for your support 
Cheers

**Comment by khzd** [comment]
Hi all,
here is the procedure
Ensure the zigbee2mqtt enable pairing (see wiki)
put the Gledopto close to the coordinator
swich on and off 5 times the Gledopto
the Gledopto joins the network after tree retries :) , more if necessary 
Thanks @Koenkk for this great job

**Comment by khzd** [comment]
Help

I get it paired but I cannot control it with HA:
after pairing: 
2018-11-17 19:07:29 - info: rgbcct_01 (0x00124b001ad70f04): GL-C-008 - Gledopto Zigbee LED controller RGB + CCT (Router)

I got systematically :  
2018-11-17 19:07:30 - debug: Recieved mqtt message on topic 'zigbee2mqtt/rgbcct_01/set' with data '{"state": "ON"}'
2018-11-17 19:07:30 - info: Zigbee publish to '0x00124b001ad70f04', genOnOff - on - {} - null
2018-11-17 19:08:00 - error: Zigbee publish to '0x00124b001ad70f04', genOnOff - on - {} - null failed with error Error: Timed out after 30000 ms

in the log , I have some lines !!! 
 2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'
2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'
2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'
2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'
2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'
2018-11-17 19:11:31 - debug: Recieved zigbee message of type 'devInterview' with data '"0x00124b001ad70f04"'

**Comment by dcsg** [comment]
Any news? I have the device and I was able to have it connected to the zigbee network but now I don't understand how do I control it on home-assistant. Any idea?

**Comment by DJTerentjev** [comment]
> 
> 
> Any news? I have the device and I was able to have it connected to the zigbee network but now I don't understand how do I control it on home-assistant. Any idea?

So you got it paired!  Do you have modelID or it is 'undefined' ? 
If you got model ID, you can try in Home assistant:

`light:`
`  - platform: "mqtt"`
`    name: "Gledopto" # Change to your model name`
`    state_topic: "zigbee2mqtt/0x00124b001b6aea81" # Change to your device ID or friendly name `
`    availability_topic: "zigbee2mqtt/bridge/state" `
`    brightness: true`
`    color_temp: true`
`    xy: true`
`    command_topic: "zigbee2mqtt/0x00124b001b6aea81/set" # Change to your device ID or friendly name`

I have GLEDOPTO, but couldn't connect because it's doesn't provide modelID:
https://github.com/Koenkk/zigbee2mqtt/issues/682

**Comment by dcsg** [comment]
Indeed! I got the same :/

```
  zigbee2mqtt:warn 2018-12-22 10:48:56 Device with modelID 'undefined' is not supported.
  zigbee2mqtt:warn 2018-12-22 10:48:56 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
  zigbee2mqtt:warn 2018-12-22 10:48:56 Device with modelID 'undefined' is not supported.
  zigbee2mqtt:warn 2018-12-22 10:48:56 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
```

**Comment by sehraf** [comment]
How long have you paired it? It took my Xiaomi devices almost a minute to actually fully pair. Often there were multiple `Device with modelID 'undefined' is not supported.` messages and it only works after the `Device incoming...` message. During this i had to constantly press the reset button as you have to do it for Xiaomi devices.
```
zigbee2mqtt:info 20.12.2018, 21:26:13 New device with address 0x00158d0002451e22 connected!
zigbee2mqtt:info 20.12.2018, 21:26:13 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002451e22"}'
zigbee2mqtt:warn 20.12.2018, 21:26:13 Device with modelID 'undefined' is not supported.
zigbee2mqtt:warn 20.12.2018, 21:26:13 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
zigbee2mqtt:info 20.12.2018, 21:26:14 MQTT publish: topic 'homeassistant/sensor/0x00158d0002451e22/temperature/config', payload '{"unit_of_measurement":"°C","device_class":"temperature","value_template":"{{ value_json.temperature }}","json_at>
zigbee2mqtt:info 20.12.2018, 21:26:14 MQTT publish: topic 'homeassistant/sensor/0x00158d0002451e22/humidity/config', payload '{"unit_of_measurement":"%","device_class":"humidity","value_template":"{{ value_json.humidity }}","json_attributes":>
zigbee2mqtt:warn 20.12.2018, 21:26:14 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:15 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:17 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:18 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:20 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:21 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:22 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:24 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:25 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:26 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:28 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:29 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:31 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:32 Message without device!
zigbee2mqtt:warn 20.12.2018, 21:26:33 Message without device!
zigbee2mqtt:info 20.12.2018, 21:26:33 Device incoming...
zigbee2mqtt:info 20.12.2018, 21:26:33 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
zigbee2mqtt:info 20.12.2018, 21:26:58 MQTT publish: topic 'zigbee2mqtt/0x00158d0002451e22', payload '{"temperature":26.38,"linkquality":136}'
zigbee2mqtt:info 20.12.2018, 21:26:58 MQTT publish: topic 'zigbee2mqtt/0x00158d0002451e22', payload '{"temperature":26.38,"linkquality":136,"humidity":64.31}'
```

**Comment by dcsg** [comment]
I tried 3 or 4 times, but then I added some data in `database.db` and it seems to recognize it but does not accept the commands :/

**Comment by dcsg** [comment]
I don't have errors anymore when sending commands but I cannot control it 🤔 this is my configuration in home assistant:

```
light:
  - platform: "mqtt"
    name: "Gledopto" # Change to your model name
    state_topic: "zigbee2mqtt/0x00124b001ad74041" # Change to your device ID or friendly name
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    xy: true
    command_topic: "zigbee2mqtt/0x00124b001ad74041
```

![image](https://user-images.githubusercontent.com/744921/50373915-9196c800-05dd-11e9-8474-2da217cfc461.png)

Should it have the possibility to control the RGB of the Led?

**Comment by dcsg** [comment]
also I'm having some of those:

```
 zigbee2mqtt:warn 2018-12-22 11:34:37 Message without device!
 zigbee2mqtt:warn 2018-12-22 11:35:07 Message without device!
```

**Comment by dcsg** [comment]
I got it to work when I can the `publish.mqtt` service with this message:

```
{"topic": "zigbee2mqtt/0x00124b001ad74041/set", "payload": "{\"state\":\"ON\",\"color\":{\"x\":0.501,\"y\":0.599},\"color_temp\":211,\"brightness\":52}"}
```

So I guess my homeassistant configuration is not correct, any ideas?

**Comment by DJTerentjev** [comment]
Daniel,
I am also new to this. I just check and I have same error (although it was working before ). But I have additionally in HA: 

`mqtt:`
`  discovery: true`
`  broker: 192.168.1.51`
`  port: 1883`
`  username: djterentjev`
`  password: 11111111`
  
`  birth_message:`
`    topic: 'hass/status'`
`    payload: 'online'`
`  will_message:`
`    topic: 'hass/status'`
`    payload: 'offline'`

And I it give me second atuo-discovered record (0x00124b001b6aea81): 
![default](https://user-images.githubusercontent.com/1267473/50374040-d5e39180-05f8-11e9-9317-aa55c1fac2ad.png)

My HA 0.84.1 - recently the were some changes

I am not sure if it is OK to have 3 record in DB, but I have 3 for each devise.

**Comment by dcsg** [comment]
Got it to work 🎉

**Comment by DJTerentjev** [comment]
Good! What exact model of your Gledopto?

**Comment by dcsg** [comment]
@DJTerentjev RGB+CCT

**Comment by khzd** [comment]
hi all
i have a couple of GL-C-008 and one of them was not working this morning
i had to modify the device.js addig bold part
        ep: (device) => {
            if (device.epList.toString() === '11,12,13' ) {
                return {'': 12};
            } else if (device.epList.toString() === '10,11,13' **|| device.epList.toString() === '11,13')** {
                return {'': 11};
            } else {
                return {};
            }
        },

for HA, to have full functionality, try : 
light:
  - platform: "mqtt"
    schema: "json"
    name: "My Office Light RGBW"
    state_topic: "zigbee2mqtt/rgbcct_01"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    xy: true
    command_topic: "zigbee2mqtt/rgbcct_01/set"
    qos: 1
    optimistic: false
    retain: true
    rgb: true
    color_temp_min: 0
    color_temp_max: 100
    white_value: true
    effect: true
    #Effect list 0=Full, 1=White, 2=RGB, 3=Full hard, 4=Disco, 5=Red Flash, 6=Green Flash, 7=Blue Flash, 8=White Flash]
    effect_list: [0, 1, 2, 3, 4 ,5, 6, 7, 8]
    transition: true

**Comment by DJTerentjev** [comment]
Hi khzd,
I got mine working by manually send MQTT messages to zigbee2mqtt. I used your HA setup, but it can only turn it on. Looks like the device is handling command,  but it zigbee2mqtt not getting respons from device. I suspect I have wrong device.js.
I believe, I never modify it, but I have now:

    // Gledopto
    {
        zigbeeModel: ['GLEDOPTO'],
        model: 'GL-C-008',
        vendor: 'Gledopto',
        description: 'Zigbee LED controller RGB + CCT',
        supports: generic.light_onoff_brightness_colortemp_colorxy().supports,
        fromZigbee: generic.light_onoff_brightness_colortemp_colorxy().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colortemp_colorxy().toZigbee,
    },
I think is missing part you mentioned above. Could you please publish compleat Gledopto converter.

**Comment by dcsg** [comment]
@khzd how did you get the effect to work? what is your gledopto device? RGB+CCT?

**Comment by DJTerentjev** [comment]
> 
> 
> @khzd how did you get the effect to work? what is your gledopto device? RGB+CCT?

I also would like to know. Should I add something to  devices.js? 
Messages in the log:  `No converter available for 'effect'`

**Comment by andreapx** [comment]
Hi,
I've read this and other posts, but I still can't control my GC-C-008.
When I've tried to pair it I've got in the log:
`May 06 19:45:17 RaspiMaster npm[18718]:   zigbee2mqtt:warn 2019-5-6 19:45:17 Device with modelID 'GL-C-008' is not supported.
May 06 19:45:17 RaspiMaster npm[18718]:   zigbee2mqtt:warn 2019-5-6 19:45:17 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices
May 06 19:45:17 RaspiMaster npm[18718]:   zigbee2mqtt:warn 2019-5-6 19:45:17 Device with modelID 'GL-C-008' is not supported.
May 06 19:45:17 RaspiMaster npm[18718]:   zigbee2mqtt:warn 2019-5-6 19:45:17 Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices`

In the DB I have:
`{"$$deleted":true,"_id":"HRAyY1XBPf4YRgbI"}
{"id":22,"type":"Router","ieeeAddr":"0x00124b001ba73a79","nwkAddr":3934,"manufId":0,"epList":[11,13],"status":"online","joinTime":1557164686,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"6AfE9QjucxBcukMu"}
{"id":22,"type":"Router","ieeeAddr":"0x00124b001ba73a79","nwkAddr":3934,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-008","epList":[11,13],"status":"online","joinTime":1557164686,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"6AfE9QjucxBcukMu"}
{"id":22,"type":"Router","ieeeAddr":"0x00124b001ba73a79","nwkAddr":3934,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-C-008","epList":[11,13],"status":"online","joinTime":1557164686,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768],"outClusterList":[],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}}}},"13":{"profId":49246,"epId":13,"devId":528,"inClusterList":[4096],"outClusterList":[4096],"clusters":{"lightLink":{"dir":{"value":3},"attrs":{}}}}},"_id":"6AfE9QjucxBcukMu"}`

If I try to control it with 
`mosquitto_pub -h localhost -t "zigbee2mqtt/0x00124b001ba73a79/green/set" -m '{ "brightness": "255", "state":"on" }'`
I get in the log
`Cannot handle MQTT message on 'zigbee2mqtt/0x00124b001ba73a79/green/set' with data '{ "brightness": "255", "state":"on" }'`

Thanks!

**Comment by Mioze** [comment]
I have a model 2 channel (2 ID) May control in Home Assistant only RGB channel CCT channel is not displayed. 2 channel should find the other device of ZigBee? or all of the same control on the same channel? How to control the white light?
