### ISSUE TITLE
Adding Support for device: Osram SMART+ Candle E14 Dimmable White

### ISSUE THREAD

**Issue by hamstie** [Koenkk/zigbee2mqtt#582]
My devices.js entry:
    {   
        zigbeeModel: ['B40 DIM Z3'],
        model: 'AC08562',
        vendor: 'OSRAM',
        description: 'SMART+ Candle E14 Dimmable White',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: generic.light_onoff_brightness().fromZigbee,
        toZigbee: generic.light_onoff_brightness().toZigbee,
    },

- found no errors in log but if i try to switch the lamp i see no traffic (serialport) to the coordinator for sending:
e.g.
> mosquitto_pub -h 192.168.1.35  -t  haus/gw/zb/wz_lamp_wall/set -m '{"state":"ON","brightness": 100}'
will end up in:
 zigbee2mqtt:debug 2018-11-10 12:50:47 Received mqtt message on topic 'haus/gw/zb/wz_lamp_wall/set' with data '{"state":"ON","brightness": 100}'
- nothing happened after this print, no sending on serial
- device is zw_lamp_wall (only friendly name will work)
- bridge main topic is haus/gw/zb 
- if i trigger a unknown device, wrong payload i got a error print (parser is working)
- device is connected/online
- network scan via mqtt will work, serial debugs will printed 

node[shape=record];
  "0x00124b001b7b2ca4" [label="{0x00124b001b7b2ca4|Coordinator|No model information available|online}"];
  "0x00124b001b7b2ca4" -> "0xf0d1b8000010767c" [label="255"]
  "0xf0d1b8000010767c" [label="{wz_lamp_wall|Router|OSRAM Smart+ Candle E14 (AC08562)|online}"];
  "0xf0d1b8000010767c" -> "0x00124b001b7b2ca4" [label="18"]
}

- something wrong in topic payload ?

**Comment by Koenkk** [comment]
Can you provide your complete log?

**Comment by hamstie** [comment]
https://pastebin.com/L3xEPA1k
-Start Bridge
-Switch OSRAM device on
-trigger some invalid and valid mqtt publish to the device

**Comment by hamstie** [comment]
> @hamstie
> Have you ever cleared your database?
> What shows your `log` if you do a `get`?

yes i cleared my database before
what is a get?
- publish a  ../<DEVICE>/get with a special payload?
- subscribe to ../<DEVICE> ?

**Comment by Chrischi-** [comment]
@hamstie 

```
on_off: {
        key: 'state',
        convert: (value, message, type) => {
            const cid = 'genOnOff';
            const attrId = 'onOff';

            if (type === 'set') {
                return {
                    cid: cid,
                    cmd: value.toLowerCase(),
                    cmdType: 'functional',
                    zclData: {},
                    cfg: cfg.default,
                };
            } else if (type === 'get') {
                return {
                    cid: cid,
                    cmd: 'read',
                    cmdType: 'foundation',
                    zclData: [{attrId: zclId.attr(cid, attrId).value}],
                    cfg: cfg.default,
                };
            }
        },
},
```

**Comment by hamstie** [comment]
> @hamstie
> 
> ```
> on_off: {
>         key: 'state',
>         convert: (value, message, type) => {
>             const cid = 'genOnOff';
>             const attrId = 'onOff';
> 
>             if (type === 'set') {
>                 return {
>                     cid: cid,
>                     cmd: value.toLowerCase(),
>                     cmdType: 'functional',
>                     zclData: {},
>                     cfg: cfg.default,
>                 };
>             } else if (type === 'get') {
>                 return {
>                     cid: cid,
>                     cmd: 'read',
>                     cmdType: 'foundation',
>                     zclData: [{attrId: zclId.attr(cid, attrId).value}],
>                     cfg: cfg.default,
>                 };
>             }
>         },
> },
> ```

No debug output for any ../DEVICE/get publish !!
- tested invalid topic too, no output e.g ../DEVICE_INVALID/get  , nothing happened
mosquitto_pub  -h 192.168.1.35 -t haus/gw/zb/wz_lamp_wall/get -m '{"state":""}', (valid topic) , nothing
only /DEVICE_INVALID/set will trigger an error.

**Comment by Chrischi-** [comment]
@hamstie 
btw. doesn't the `Z3` from `B40 DIM Z3` stand for Zigbee 3.0??

**Comment by hamstie** [comment]
found the issue:
i run zigbee2mqtt as a docker container and used  the zigbee-shaperd-converter as a volume.
but at this time the converter is broken (new Version problem #127)
i compiled  zigbee2mqtt and edit devices.js and now i can switch the lamp as a charm
