### ISSUE TITLE
Guide for cod.m CC2538-CC2592 Raspberry Pi module

### ISSUE THREAD

**Issue by MarijnPessers** [Koenkk/zigbee2mqtt#5838]
Hi I bought a cod.m CC2538 + CC2592 Rapsberry Pi addon and got it working. It was not on your site of supported hardware so I thought I would submit it since I wrote a how-to guide.
Below you will find the link to the device and a link to the guide.

I am not affiliated with cod.m, I just want to provide easy information for people like me who are trying to get it set up.

## Information about the device + link
https://shop.codm.de/automation/zigbee/29/zigbee-cc2538-raspberry-pi-modul
https://github.com/MarijnPessers/cod.m-CC2538-CC2592-for-Home-Assistant/

## data/database.db entry of the device
..

**Comment by Koenkk** [comment]
Cool, please make a PR for https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/supported_adapters.md , you can add it under the CC2538 hat
