### ISSUE TITLE
Need support for device: A60 TW Value II (Very similar to bulps that are already supported)

### ISSUE THREAD

**Issue by FrandsAndersen** [Koenkk/zigbee2mqtt#5849]
Hi. I have tried to add this device: LEDVANCE Classic E27 Tunable White, model A60 TW Value II. The model number is AC25702. I am running Home Assistant OS, and when I try do use a custom device.js file, I get the exact same problem as mentioned here: https://github.com/Koenkk/zigbee2mqtt/issues/5385. I would like to be able to add new devices for my own system, but it seems that it can't find the referenced lib and converter folder. It is possible to make a guide for this?

![image](https://user-images.githubusercontent.com/47597577/105345239-4ef0b100-5be4-11eb-920f-c4f23879ad79.png)

Based on the other OSRAM models with same configuration, I would like this to be added to the device.js.

{
        zigbeeModel: ['A60 TW Value II'],
        model: 'AC25702',
        vendor: 'LEDVANCE',
        description: 'Classic E27 Tunable White',
        extend: preset.ledvance.light_onoff_brightness_colortemp(),
        ota: ota.ledvance,
},

Even better would be to know how to do it myself, but the guides does not cover how to reference the lib and converter folders from the custom device.js file inside the share/zigbee2mqtt folder.
![image](https://user-images.githubusercontent.com/47597577/105345946-33d27100-5be5-11eb-929b-0c6b0f60edab.png)

Thanks in advance. 
Have a good day.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
