### ISSUE TITLE
Need support for LEDVANCE device: B40 TW Value

### ISSUE THREAD

**Issue by FrandsAndersen** [Koenkk/zigbee2mqtt#5861]
Hi again.

Yesterday I made this request: https://github.com/Koenkk/zigbee2mqtt/issues/5849. Thanks for the update, it works just great! The thing is I have the exact same problem with the E14 model of this one.

Here is the needed code:

{
        zigbeeModel: ['B40 TW Value'],
        model: 'AC25704',
        vendor: 'LEDVANCE',
        description: 'Classic E14 Tunable White',
        extend: preset.ledvance.light_onoff_brightness_colortemp(),
        ota: ota.ledvance,
},

Is it possible to add this device to the dev branch just as easy as you did with the last light bulp for LEDVANCE? You are doing a great work.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
