### ISSUE TITLE
Lonsonho TS0043 проблема соединения с CC2538 CC2592

### ISSUE THREAD

**Issue by sergey81-81** [Koenkk/zigbee2mqtt#5892]
## What happened
Lonsonho TS0043 проблема соединения с CC2538 CC2592. Два ранее подключенных TS0043 работают без проблем. приобретен еще один TS0043 при подключении ничего не происходит. Через СС2531 подключается с первой попытки и работает без проблем.
## What did you expect to happen
Необходимо подключить TS0043 к zigbee2mqtt через CC2538 CC2592
## Debug info
Zigbee2MQTT version:1.17.0
Adapter hardware: CC2538 CC2592
Adapter firmware version:20201010

**Comment by Koenkk** [comment]
Englisch only.
