### ISSUE TITLE
CC2253 LED Disable without using the Backend

### ISSUE THREAD

**Issue by boyi01** [Koenkk/zigbee2mqtt#5911]
I flashed a CC2253 with the zigbee2mqtt firmware, but i don't use it with  zigbee2mqtt, i use it direcetly with openhab, but i can't disbale the led anymore

Any possiblity to disable the LED without using zigbee2mqtt software ohne server only on the stick

**Comment by Koenkk** [comment]
Please create this issue in the openhab issue tracker, this has nothing to do with Zigbee2MQTT.

**Comment by boyi01** [comment]
i would say it's easier in the firmware... maybe it's possible to set the parameter file flashing forever?
