### ISSUE TITLE
Sending `color_temp` = null in MQTT payloads for color_temp capable lights

### ISSUE THREAD

**Issue by johnsonnc** [Koenkk/zigbee2mqtt#5918]
## What happened

https://pastebin.com/vi8hZmHv
For HUE lights (at least, could be other) z2m is sending null values for 'color_temp' attribute. This has the side effect of causing an exception in HA (bug filed for that here: https://github.com/home-assistant/core/issues/45576). 

## What did you expect to happen
'color_temp' != null 

## How to reproduce it (minimal and precise)
Change state of any light with the 'color_temp' capability, look at logs. 

## Debug info
Zigbee2MQTT version: 1.17.0 commit: 07cdc9d
Adapter hardware:  Conbee II
Adapter firmware version: 0x26680700

**Comment by Koenkk** [comment]
Let's track this in the HA tracker since it will be fixed from the HA side (https://github.com/home-assistant/core/issues/45576#issuecomment-767764212)
