### ISSUE TITLE
Lidl HG06467 change of effect-type 

### ISSUE THREAD

**Issue by hytrek** [Koenkk/zigbee2mqtt#5919]
Hi there
glad you now support these device. Bit unfortunatly change of the "effect-type" results in:

`

host.ioBroker2-raspberrypi | 2021-01-26 18:47:27.794 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --

zigbee.0 | 2021-01-26 18:47:26.578 | error | (9652) The state contains the forbidden properties effect, speed, colors!
-- | -- | -- | --
zigbee.0 | 2021-01-26 18:47:26.578 | error | at processImmediate (internal/timers.js:463:21)
zigbee.0 | 2021-01-26 18:47:26.578 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26 18:47:26.578 | error | at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26 18:47:26.578 | error | at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26 18:47:26.578 | error | (9652) Error: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.577 | error | (9652) unhandled promise rejection: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.577 | error | (9652) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26 18:47:26.572 | error | (9652) The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.571 | error | at processImmediate (internal/timers.js:463:21)
zigbee.0 | 2021-01-26 18:47:26.571 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26 18:47:26.571 | error | at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26 18:47:26.571 | error | at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26 18:47:26.571 | error | (9652) Error: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.570 | error | (9652) unhandled promise rejection: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.569 | error | (9652) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26 18:47:26.566 | error | (9652) The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.565 | error | at processImmediate (internal/timers.js:463:21)
zigbee.0 | 2021-01-26 18:47:26.565 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26 18:47:26.565 | error | at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26 18:47:26.565 | error | at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26 18:47:26.565 | error | (9652) Error: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.564 | error | (9652) unhandled promise rejection: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.563 | error | (9652) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-01-26 18:47:26.558 | error | (9652) The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.557 | error | at processImmediate (internal/timers.js:463:21)
zigbee.0 | 2021-01-26 18:47:26.557 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:238:38)
zigbee.0 | 2021-01-26 18:47:26.557 | error | at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5935:21)
zigbee.0 | 2021-01-26 18:47:26.557 | error | at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5848:23)
zigbee.0 | 2021-01-26 18:47:26.557 | error | (9652) Error: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.550 | error | (9652) unhandled promise rejection: The state contains the forbidden properties effect, speed, colors!
zigbee.0 | 2021-01-26 18:47:26.549 | error | (9652) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi

`

**Comment by Koenkk** [comment]
Since you are using iobroker create this issue here: https://github.com/ioBroker/ioBroker.zigbee/issues
