### ISSUE TITLE
OTA update from URL or local file

### ISSUE THREAD

**Issue by SimonThoustrup** [Koenkk/zigbee2mqtt#5923]
## Is your feature request related to a problem? Please describe
Danfoss is publishing OTA files for the Ally thermostat (https://www.zigbee2mqtt.io/devices/014G2461.html) on their website - https://www.danfoss.com/en/products/smart-heating/dhs/smart-heating/danfoss-ally/danfoss-ally-support/#tab-software

## Describe the solution you'd like
To provide the URL for the OTA file or drop the OTA file in a folder in the zigbee2mqtt directory structure and then initiate the OTA upgrade as for other devices where OTA is already supported.

## Additional context
I believe this could be useful for other devices as well ref. https://github.com/Koenkk/zigbee2mqtt/discussions/2921#discussioncomment-312151

**Comment by hellcry37** [comment]
up for ota update from local folder

**Comment by ipeacocks** [comment]
Can't update one TRV. How to force that?
