### ISSUE TITLE
INNR BF265

### ISSUE THREAD

**Issue by tda2806** [Koenkk/zigbee2mqtt#5951]
Please add support for the Innr device BF265, this is the same as RF265 from the same manufacturer. I believe the same is true of the of the BF263=RF263, BY265=RY265 and BY285=RY285

**Comment by intrinseca** [comment]
https://github.com/Koenkk/zigbee2mqtt.io/pull/590
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2177

The others are probably the same mapping, but the BF 265 is the one we've tested.
