### ISSUE TITLE
Zigbee2mqtt requires node version >=8.11 10

### ISSUE THREAD

**Issue by HKC001** [Koenkk/zigbee2mqtt#596]
Hi, when running zigbee2mqtt 0.2.0 + the latest release of Hass.IO and supervisor, I get the following error:

```
> zigbee2mqtt@0.2.0 start /zigbee2mqtt-0.2.0
> node index.js
		Zigbee2mqtt requires node version >=8.11 10, you are running v8.11.4!
```

Any way to fix this?

**Comment by dedors** [comment]
Just started to setup my Zigbee2mqtt and got stuck at this too

**Comment by Koenkk** [comment]
Thanks, fixed in the dev branch.
