### ISSUE TITLE
Version 0.2.0 stops working with error regarding usuccess request: 17

### ISSUE THREAD

**Issue by pepp86** [Koenkk/zigbee2mqtt#598]
Using zigbee2mqtt with your docker container on a raspberrypi running libreelec, latest version.

When updating from 0.1.8 to 0.2.0 I get the following errors in my log and the whole docker container restarts.

https://pastebin.com/00nzAg8f

**Comment by Koenkk** [comment]
Can you try:

- stopping zigbee2mqtt
- pressing the reset button on the stick (the one close to the usb port)
- start zigbee2mqtt

**Comment by pepp86** [comment]
Hi.

Did not help. No chance to get it up and running

**Comment by Koenkk** [comment]
If a reboot/reset doesn't fix the problem I think the only way to fix it is to reflash the stick.

**Comment by pepp86** [comment]
Still same issue with latest firmware and a brand new stick

**Comment by Koenkk** [comment]
Can you try a different usb port?

**Comment by pepp86** [comment]
I will try it. But actually it happens on two different machines with different sticks

**Comment by pepp86** [comment]
Hi,

it works with latest version 1.0.1 on both machines with different sticks and stick firmware.

Issue can be closed.
