### ISSUE TITLE
Please add Lidl HG06337-DK support

### ISSUE THREAD

**Issue by Flemming-G-DK** [Koenkk/zigbee2mqtt#6005]
Danish version of the Lidl Silvercrest Smart Plug HG06337 is not supported:
https://www.zigbee2mqtt.io/devices/HG06337.html
Relevant log entry:
Zigbee2MQTT:warn  2021-01-31 19:25:08: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TZ3000_upjrsxh1'
TIA
Flemming

**Comment by Koenkk** [comment]
Added, will be supported in tomorrows new release (1.17.1)
