### ISSUE TITLE
Lidl Home Smart Wireless Door Bell

### ISSUE THREAD

**Issue by Varming73** [Koenkk/zigbee2mqtt#6007]
I got this Lidl Home Smart Wireless Door Bell (https://zigbeealliance.org/zigbee_products/lidl-home-smart-wireless-door-bell/) and would like to add it - but don't fully understand how to do what is asked in the "How to support new devices".

The device is paired and I see this in the log: WARNING: Device '0x842e14fffef80f14' with Zigbee model 'TS0211' and manufacturer name '_TZ1800_ladpngdx' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

When I press the button (only this it basically can do) I see this in the log:
Zigbee2MQTT:warn  2021-01-31 19:50:01: Received message from unsupported device with Zigbee model 'TS0211' and manufacturer name '_TZ1800_ladpngdx'

I can provide any info asked if somebody could help me getting this added.

**Comment by Koenkk** [comment]
Already supported in the dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
