### ISSUE TITLE
it does not work 50049 Paulmann SmartHome Yourled RGB Controller (on/off, brightness, color xy) 

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#602]
Hello, I'm trying to pair a Paulmann 50049 controller, but that does not seem to work.

https://pastebin.com/Zrnw59Yk

database.db

https://pastebin.com/byRH3TQc

**Comment by Koenkk** [comment]
Looks good, can you try following: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices

**Comment by Koenkk** [comment]
Can you provide your `database.db`?

**Comment by bochelork** [comment]
This is the Paulmann line from database.db. Let me know if you need more data.

`{"id":27,"type":"Router","ieeeAddr":"0x00158d0002931234","nwkAddr":24243,"manufId":4509,"manufName":"Paulmann Licht GmbH ","powerSource":"Mains (single phase)","modelId":"RGBW light ","epList":[1],"status":"offline","joinTime":null,"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}}},"_id":"XbnhHSBK1KuB2FUQ"}
`

**Comment by Koenkk** [comment]
@bochelork should be fixed in the latest dev branch, can you check?

**Comment by bochelork** [comment]
Checked, seems so work fine. Had some difficulties updating to dev but now everything is working like a charm.

**Comment by Koenkk** [comment]
Great!
