### ISSUE TITLE
Link Quality Index - Acting suspiciously?

### ISSUE THREAD

**Issue by MDSDM** [Koenkk/zigbee2mqtt#6028]
The LQI for my devices starts very low (<20) and then slowly builds up to high (>200).
When I graphed the LQI over time, I see that the progress is strictly linear. In this case, I've decided to fill with 0, so each spike is a new measurement. Then it suddenly drops and starts over.

![Screenshot 2021-02-01 at 17 03 33](https://user-images.githubusercontent.com/28918930/106484086-8b0ef600-64af-11eb-843b-4e8d0223accf.png)

Perhaps it's sometime in the LQI calculation that makes it improve over time. But several days looks a bit odd..

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4039
