### ISSUE TITLE
OTA on TS0601 thermostat fail

### ISSUE THREAD

**Issue by copystring** [Koenkk/zigbee2mqtt#6036]
I have a few of these: https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

Wanted to perform OTA but it says no new image available although a link to the new image is visible in the log.

https://pastebin.com/MXAjp8Nh

Shouldn't there be a version visible in the web interface? I guess it is not reporting the version and fails because of that?

![image](https://user-images.githubusercontent.com/1298861/106514716-e7d0d780-64d4-11eb-9a66-38a9680a6b9c.png)

Edit: in the log it shows: "update_available":true
Same for the web interface: 
![image](https://user-images.githubusercontent.com/1298861/106516328-2cf60900-64d7-11eb-8cf0-52945669287f.png)

Clicking on Update OTA shows no new version available.

**Comment by bruvv** [comment]
@copystring could you open this again? I have the same issue. Running 1.19.1 of zigbee

**Comment by wimpie007** [comment]
same issue here.

**Comment by VikeDragon** [comment]
same issue here.

**Comment by GamerClassN7** [comment]
Same here any progress ?
