### ISSUE TITLE
Impossible to create a device with light bulb LIDL HG06106C

### ISSUE THREAD

**Issue by diazovitch** [Koenkk/zigbee2mqtt#6039]
Version plugin zigbee2mqtt : v.1.17.1 (zStack12 20181024)
Version domoticz : 2020.2

When i associate the bulb with my sniffer CC2531, we can see a line with "Livarno Lux E27 bulb RGB" which appears in the top table. But normally when i clic on this line, a second table below have to appears and in my case it don't appear. What is the problem please ?

![zigbee2](https://user-images.githubusercontent.com/48931195/106516149-ed2f2180-64d6-11eb-9408-2c217310dc57.JPG)

![zigbee1](https://user-images.githubusercontent.com/48931195/106516135-eaccc780-64d6-11eb-946a-976f6b2805c3.JPG)

**Comment by Koenkk** [comment]
Looks like it's not directly a z2m issue, please create it here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
