### ISSUE TITLE
python cc_info.py -p COM5 ERROR: unicode strings are not supported, please encode to bytes: 'ð\x00\x00\x00'

### ISSUE THREAD

**Issue by RWGaMeR** [Koenkk/zigbee2mqtt#604]
Good morning,
I use the latest version of the project for flashing with arduino only giving the command to verify the key (python cc_info.py -p COM5) always this error : ERROR: unicode strings are not supported, please encode to bytes: 'ð\x00\x00\x00' , you know how to fix or what I was wrong?

**Comment by kirovilya** [comment]
Use python 2.7 instead python 3.*

**Comment by RWGaMeR** [comment]
I have a new problem
Traceback (most recent call last):
  File "cc_info.py", line 20, in <module>
    from cclib import hexdump, renderDebugStatus, renderDebugConfig, getOptions, openCCDebugger
  File "C:\CCLib\Python\cclib\__init__.py", line 20, in <module>
    from cclib.ccdebugger import *
  File "C:\CCLib\Python\cclib\ccdebugger.py", line 19, in <module>
    from cclib.ccproxy import CCLibProxy
  File "C:\CCLib\Python\cclib\ccproxy.py", line 22, in <module>
    import serial
ImportError: No module named serial

**Comment by RWGaMeR** [comment]
@kirovilya with cclib i have a this problem 

> Traceback (most recent call last):
> File "cc_info.py", line 20, in 
> from cclib import hexdump, renderDebugStatus, renderDebugConfig, getOptions, openCCDebugger
> File "C:\CCLib\Python\cclib__init__.py", line 20, in 
> from cclib.ccdebugger import *
> File "C:\CCLib\Python\cclib\ccdebugger.py", line 19, in 
> from cclib.ccproxy import CCLibProxy
> File "C:\CCLib\Python\cclib\ccproxy.py", line 22, in 
> import serial
> ImportError: No module named serial

**Comment by sehraf** [comment]
> ImportError: No module named serial

you don't seem to have the python serial module installed (for python 2.7)

**Comment by RWGaMeR** [comment]
> > ImportError: No module named serial
> 
> you don't seem to have the python serial module installed (for python 2.7)

i have resolve, but it does not detect a ccclib_proxy device even if I put the sketch on the arduino uno

**Comment by RWGaMeR** [comment]
What is the configuration for arduino uno?

**Comment by RWGaMeR** [comment]
@kirovilya I have this is error (ERROR: Could not find CCLib_proxy device on port COM5)

**Comment by RWGaMeR** [comment]
@kirovilya now from this error (ERROR: The chip is not responding. Check your connection and/or wiring!)

**Comment by RWGaMeR** [comment]
@kirovilya 
If you change position you have wires give me this error (ERROR: Short-circuit or wrong wiring detected. Check your connection and/or wiring!)
