### ISSUE TITLE
A Tuya/ CR smart home TS0202 look-alike?

### ISSUE THREAD

**Issue by tpaulic** [Koenkk/zigbee2mqtt#6054]
**Information about the device + link**

https://wooxhome.com/new-c8/woox-r7046-smart-pir-motion-sensor-p46

**data/database.db entry of the device**

{"id":41,"type":"EndDevice","ieeeAddr":"0xbc33acfffe11f25f","nwkAddr":48237,"manufId":4098,"manufName":"_TYZB01_2b8f6cio",powerSource":"Battery","modelId":"TS0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,1280],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0202","manufacturerName":"_TYZB01_2b8f6cio","powerSource":3,"zclVersion":3,"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":""}},"ssIasZone":{"attributes":{"61441":1,"iasCieAddr":"0x00124b0021cc4b5a","zoneState":1,"currentZoneSensitivityLevel":1}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1612300207895}

**Adding the fingerprint to devices.js fixed it:**

   {
        fingerprint: [{modelID: 'TS0202', manufacturerName: '_TYZB01_jytabjkb'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_ef5xlc9q'},
            {modelID: 'TS0202', manufacturerName: '_TYZB01_2b8f6cio'}],
        model: 'TS0202',
        vendor: 'TuYa',
        description: 'Motion sensor',
        fromZigbee: [fz.ias_occupancy_alarm_1, fz.battery, fz.ignore_basic_report],
        toZigbee: [],
        exposes: [e.occupancy(), e.battery_low(), e.tamper(), e.battery()],
    },

**Comment by Koenkk** [comment]
Added, thanks!
Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
