### ISSUE TITLE
Lidl HG06106C (E27 RGB Bulb) not turning red via homeassistant

### ISSUE THREAD

**Issue by aveseli** [Koenkk/zigbee2mqtt#6059]
When choosing the red color ( `"color":{"x":0.701,"y":0.299}` ) on home assistant, it is ignored by the bulb.

I can see that the command was issued and accepted by zigbee2mqtt, since it reports the state back to mqtt. Still, the bulb wont change to the color.

Log:

```
Debug Received MQTT message on 'zigbee2mqtt/lidl_bulb/set' with data '{"state": "ON", "color": {"x": 0.701, "y": 0.299}}'

Debug Skipping state because of Home Assistant

Debug Publishing 'set' 'color' to 'lidl_bulb'

Info MQTT publish: topic 'zigbee2mqtt/lidl_bulb', payload '{"brightness":50,"color":{"x":0.701,"y":0.299},"last_seen":"2021-02-02T21:48:57.189Z","linkquality":45,"state":"ON"}'
```

The funny thing is, it only ignores when setting "color":{"x":0.701,"y":0.299}.

Zigbee2MQTT version: 1.17.1
Adapter hardware: CC26X2R1 (slaesh)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
