### ISSUE TITLE
Ikea LED 1623G12 Error on 0.2.0

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#606]
problem with Ikea LED 1623G12 after update .

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/37

when downgrading to 0.1.8 it works normally without errors

**Comment by salopette** [comment]
no idea?

**Comment by Koenkk** [comment]
Can you provide the zigbee2mqtt log?

**Comment by salopette** [comment]
Log is here:

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin

**Comment by Koenkk** [comment]
Thats not the zigbee2mqtt log but the domoticz plugin log.

**Comment by salopette** [comment]
Today I have again made update to 0.2.0 and it works!

**Comment by salopette** [comment]
Here is my Log

https://pastebin.com/g6dSmQd4

**Comment by salopette** [comment]
here is the same Problem

https://github.com/Koenkk/zigbee2mqtt/issues/632

**Comment by Koenkk** [comment]
Nice, thats indeed the same issue. Let's continue in #632, I mentioned a probably fix and a temporary workaround is also posted there.
