### ISSUE TITLE
Lidl / Silvercrest smart motion sensor doesn't send any data after battery change

### ISSUE THREAD

**Issue by mrTuomoK** [Koenkk/zigbee2mqtt#6065]
## What happened
Hi. The problem with this [motion sensor from Lidl](https://www.zigbee2mqtt.io/devices/HG06335.html#lidl-hg06335) is such that everything works just fine until I swap the battery (even quickly power it off). After battery change the only thing in logging I see is just that it announces itself but doesn't send any tamper/battery or occupancy events/data (nothing else on zigbee2mqtt log). Currently the only solution is to remove it from the network & repair to get it working again.

## What did you expect to happen
For the sensor to continue sending events as usual

## How to reproduce it (minimal and precise)
Just cut the power of the sensor and power on again

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC2531 & Slaesh CC2652RB (both tested)
Adapter firmware version: both newest...

How should I start debugging this properly? All other devices work just fine (lots of bulbs, sensors, switches and so on). I have a couple of these motion sensor and all are the same.

**Comment by dxaudio** [comment]
I have 4 of these sensors. All behaves the same as mentioned. If battery needs replacement, i shall repair sensor otherwise it never sends data again.

**Comment by dxaudio** [comment]
I see mrTuomoK from Finland, i bought my sensors in Finland too. Has anybody from other countries experience the same issue or we just in Finland were unlucky to get kind of broken sensor version..?
