### ISSUE TITLE
Home assistant with Conbee II is working but map doesn't show connected

### ISSUE THREAD

**Issue by riyas1980** [Koenkk/zigbee2mqtt#6067]
## What happened

I am using Home Assistant with Conbee II. It's working (eventhough the range is not good at all (less than 5m). But when I click on map, the devices are not showing connected 

![Zigbee](https://user-images.githubusercontent.com/35848952/106740135-4ce21580-661a-11eb-8df7-aae1a515d8d1.png)

I've clicked many times to wake the remote but it's still not showing connected

## Debug info
Zigbee2MQTT version: 1.17.0.1
Adapter hardware: Conbee II
Adapter firmware version: not quite sure how to check. Firmware updated 5 days back

**Comment by indomus** [comment]
same here.

**Comment by gomble** [comment]
i have the same problem
