### ISSUE TITLE
Retry connecting to zigbee adapter if fail

### ISSUE THREAD

**Issue by Gibbz** [Koenkk/zigbee2mqtt#6077]
## Is your feature request related to a problem? Please describe
Every time i reboot the machine with zigbee2mqtt the first few times the adapter fails to connect.

## Describe the solution you'd like
A retry option in the config file, possibly a number of times and a delay between retries. Or infinite retries.

## Describe alternatives you've considered
Currently doing it manually every reboot.

## Additional context
It might also be nice to have the adapter listed with status in the devices screen so the user can see if it is connected at a glance..

**Comment by Gibbz** [comment]
bump

**Comment by Koenkk** [comment]
Can this already be achieved systemd? (https://ma.ttias.be/auto-restart-crashed-service-systemd/)
