### ISSUE TITLE
Lonsonho switches work with errors

### ISSUE THREAD

**Issue by sergey81-81** [Koenkk/zigbee2mqtt#6086]
## What happened
Problems began with the connection of the Lonsonho Tuya touch switches. Some connected from the first time, others connected from several attempts. The latter was able to connect only by changing the channel to 15. Switches are defined in the system: TS0011, TS0012, TS0013. All switches operate but do not respond periodically. Sometimes you have to reconnect the switch to restore normal operation, sometimes this is not required.
error 2021-02-03 21:03:01: Publish 'set' 'state' to '0x680ae2fffe01d2f8' failed: 'Error: Command 0x680ae2fffe01d2f8/3 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 14856 - 3 - 118 - 6 - 11 after 10000ms)'
error 2021-02-04 09:25:04: Publish 'set' 'state' to '0x5c0272fffecacddc' failed: 'Error: Command 0x5c0272fffecacddc/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 6020 - 1 - 245 - 6 - 11 after 10000ms)'
error 2021-02-04 17:39:36: Publish 'set' 'state' to '0x5c0272fffecad5c0' failed: 'Error: Command 0x5c0272fffecad5c0/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC channel access failure' (225))'
## What did you expect to happen
You must adjust the operation of the switches without errors.
## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: CC2538+CC2592
Firmware version: 20201010 zStack30x

**Comment by Koenkk** [comment]
`MAC channel access failure` indicates there is signal interference, see https://www.zigbee2mqtt.io/information/FAQ.html#common-error-codes what you can do about it. 

Closing this as this cannot be solved from Zigbee2MQTT.
