### ISSUE TITLE
NetworkMap bug?

### ISSUE THREAD

**Issue by jasimancas** [Koenkk/zigbee2mqtt#609]
This is my map:
![descarga](https://user-images.githubusercontent.com/15717847/48718699-33f90f80-ec1c-11e8-8c8d-a169414b3d21.png)

Why are some devices not linked?

**Comment by lolorc** [comment]
good question, I have the same problem here.
If you repair those devices, they'll come ok. But I'd also say there's an issue with the network map (or zigbee-sheperd)

**Comment by apeinspace** [comment]
I may have a similar problem - either my network map is broken or the routing in my zigbee network has turned in a complete mess for days now.

wether related or not I dont know, but I remember this situation appearing around the time of the upgrade to 0.2.0.

Can anyone point me into a direction on how to troubleshoot a routing problem without having to trust the network map ? All ideas appreciated. thx

**Comment by jasimancas** [comment]
> My problem seems solved - after removing a router via MQTT from the bridge the entire network recovered and my network map now looks normal again. I chose to believe it triggered a "reset" of some sort ... is that possible ?
> 
> Of course I cant say for sure wether just the network map or the network itself had a problem ... ?

Number of devices?

Can you post the map?

**Comment by apeinspace** [comment]
this is how it looks now:

![download](https://user-images.githubusercontent.com/37478615/48832415-5e141400-ed79-11e8-986b-0f61c135cfb7.png)

Before I did delete the router, I hade 5-6 sensors without connection, the coordinator had 5 connections and one router was holding all other connections. that router was the one with very low link quality to almost all sensors, as I only used it to extend the network into the garage.

The picture now more or less looks like I would expect it, based on the proximity/placement of the routers and sensors.

its weird though, that all my routers are marked as "offline" although they work just fine.

does that usually happen with you guys too ?

**Comment by jasimancas** [comment]
My problem is that my routers don't seem to "route", everything always connects to the coordinator, and I don't know what to do, xiaomi problem maybe?

Anyone have this problem too?

**Comment by apeinspace** [comment]
delete a router from the bridge and observe whats happening in the network map. It did the trick for me and the network "reset" the routing.

**Comment by jasimancas** [comment]
> delete a router from the bridge and observe whats happening in the network map. It did the trick for me and the network "reset" the routing.
> 
> btw: Im sure there must be a more elegant way - but I simply dont know another way

Same result.

**Comment by jasimancas** [comment]
![descarga 1](https://user-images.githubusercontent.com/15717847/49007937-f3921800-f16c-11e8-832e-27380f098b0f.png)

Two devices without route, and all to coordinator?

**Comment by Koenkk** [comment]
The network map is indeed still buggy and this has to be fixed. But to be honest, currently it is not high on my priority list.

**Comment by jasimancas** [comment]
No problem, thanks!
