### ISSUE TITLE
Unbind Action causes ".flat is not a function" javascript error

### ISSUE THREAD

**Issue by EfficientSetting** [Koenkk/zigbee2mqtt#6093]
## What happened
Trying to unbind a switch from a device causes an uncaught exception/crash in bind.js

## What did you expect to happen
Unbind to work

## How to reproduce it (minimal and precise)
Any unbind causes the error message blow now

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC2531
Adapter firmware version: zStack12, 20190608

`Failed to call 'Bind' 'onMQTTMessage' (TypeError: this.zigbee.getClients(...).map(...).flat is not a function at Bind.disableUnnecessaryReportings (/opt/zigbee2mqtt/lib/extension/bind.js:312:87) at Bind.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/bind.js:238:32))`

**Comment by Koenkk** [comment]
What node version are you using (execute `node --version`)

**Comment by EfficientSetting** [comment]
I'm running node 10.15.0 on a Raspberry Pi using nvm for this user.

**Comment by EfficientSetting** [comment]
Update: Still happens under 10.23.0. 
Works under v12.20.1 - closing
