### ISSUE TITLE
FAQ - Under-voltage detected

### ISSUE THREAD

**Issue by WollyWonka** [Koenkk/zigbee2mqtt#6095]
Hi Koen, 
experiencing issues with "Under-voltage detected" and being remote, I was not able to switch power supplies. Running around the web for a solution, some tips were given elsewhere suggesting a relationship between the  "Under-voltage detected" issue and the RP firmware.

I was running 4.9-72 and, bold as I am, updated to 5.10. The messages have now disappeared from the log and  Zigbee2MQTT is running again.

It might be worth to add a suggestion to update the RP firmware, if this issue remains persistent.

Thanks for all your effort.
Regards, Wolly

**Comment by Koenkk** [comment]
Please make a pull request to update the FAQ (click the pencil icon in the right corner over here: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/FAQ.md)
