### ISSUE TITLE
CC Tool changed file / folder structure

### ISSUE THREAD

**Issue by frauhottelmann** [Koenkk/zigbee2mqtt#610]
It's not really a problem of zigbee2mqtt, but the file/folder structure of cc tool changed. The instructions are now outdated. There is no configure any more
`./configure` therefore doesn't work any more.
I downloaded an old version from sourceforge to easily get it to work :)

**Comment by Koenkk** [comment]
Could you update the wiki?

**Comment by frauhottelmann** [comment]
I updated the wiki...

**Comment by Koenkk** [comment]
Thanks!
