### ISSUE TITLE
Networkmap error (Failed to execute LQI for router)

### ISSUE THREAD

**Issue by mabusdogma** [Koenkk/zigbee2mqtt#6101]
## What happened
There’s an error when I try to get the networkmap in the zigbee2mqtt API in Home Assistant.
Before I could visualize all the devices and the mesh.

![9aca5049079b6ff66d98efad6fb759e168690c25_2_500x1000 (1)](https://user-images.githubusercontent.com/19146242/107045278-a175c400-67c5-11eb-8a40-abd6a9fcc2ec.png)

But now I see a message when its refreshing:

`Failed to execute LQI for Router`

![8d8376b5723fd9826bac16b9eb976d22e3b5fcb3](https://user-images.githubusercontent.com/19146242/107045321-ac305900-67c5-11eb-8df4-6dae3ed8374c.png)

And I get a map with some devices apparently out of the network, and no mesh at all
And even if they appear to be offline, all devices are working just fine! So I guess they are connected in some other way, or it’s just a visualization problem.

## What did you expect to happen
Get the whole networkmap with coordinator, router and devices.

## How to reproduce it (minimal and precise)
Home Assistant -> zigbee2mqtt -> Map

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC2531 (coordinator and router)
Adapter firmware version: 3.0

**Comment by m0wlheld** [comment]
I have the same, LQI cannot be read for a CC2531 (+ Ampflifier) device, running ptvo.info firmware.

**Comment by leranp** [comment]
Same here

**Comment by andyshilton** [comment]
I can confirm this is an issue with the TI Launchxl-CC1352P-2 as well. The map fails to load the LQI of any devices.
Home Assistant: 2021.2.1
zigbeetomqtt: 1.17.1
Adapter: TI LAUNCHXL-CC1352P-2
Adapter firmware: CC1352P2_CC2652P_launchpad_coordinator_20210120.hex

Only addition to this is that Uniflash updated the firmware of the board before flashing it with the adapter firmware. Unfortunately I didn't grab the version and now I'm struggling to figure out what version it's on. If it is needed, please let me know and I'll hunt some more.

![image](https://user-images.githubusercontent.com/16556349/107122220-54115980-688e-11eb-92c6-8bfb3a4806be.png)

![image](https://user-images.githubusercontent.com/16556349/107122268-9fc40300-688e-11eb-82f6-677cb759de28.png)

**Comment by Koenkk** [comment]
Failed to execute LQI can happen for 2 reasons
1. The network is congested and therefore no responses are send. Try increasing the sleep between network scans, change e.g. https://github.com/Koenkk/zigbee2mqtt/blob/99274c72c26ba21347908af8238fa8dfdb4fb99d/lib/extension/networkMap.js#L215 to `await utils.sleep(5);`
2.  The device doesn't support an LQI request (I know this is the case for e.g. non-pro Gledopto devices). Cannot be solved from z2m side

**Comment by andyshilton** [comment]
@Koenkk  Thanks for the information. Having left it overnight to settle, mine is responding a lot better. It does seem to be to be with network congestion.

**Comment by DieNummerEins** [comment]
I have the same problem. I 

Zigbee2mqtt version: 1.18.1-1

I tried 2 CC2531-sticks, one with antenna and one without. And i tried both new firmares default and source routing from
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default
https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

this error message appears even if no end device is in the network, as you can see below
![zigbee2mqtt-error](https://user-images.githubusercontent.com/60155534/116232674-bd508c80-a75a-11eb-8425-9e4a17cfc21f.png)

**Comment by DieNummerEins** [comment]
I deinstalled and reinstalled z2m and now it works with default and sorce-routing firmware, i don't see the error message anymore. But i found out, that not every tradfri device works perfectly with the sorce-routing fw, dimmer and motion sensor don't. i have 2 cc2531-sticks, one with default and the other with source-routing fw. i only can join them to my network with the default fw. i get the button-events but the map function works only with the stick, with which i joined the device with my network. reconfiguring the device with the other stick shows me the error below.
![error-dimmer-motionsensor](https://user-images.githubusercontent.com/60155534/116247746-728b4080-a76b-11eb-99c5-b5e08806aef8.jpg)

**Comment by DieNummerEins** [comment]
after the error message above i cannot join any other device. after the initial pairing message nothing happens. nothing is helping (restart z2m, unplug the stick from usb). i think, i should flash the fw and start from beginning.

**Comment by DieNummerEins** [comment]
the problem seems to be the source routing fw. with the default fw i am able to get all my devices correctly mapped (with lqi). some devices (ikea tradfri) i can reconfigure, i get the error message above too, but after this reconfiguring try they are all shown correctly in the map. the other devices i can delete and rejoin again.

the default fw seems to be more stable.

now i will join all my devices (22x) and maybe it will work.

**Comment by SpitFireRSA** [comment]
@DieNummerEins

> the problem seems to be the source routing fw. with the default fw i am able to get all my devices correctly mapped (with lqi). some devices (ikea tradfri) i can reconfigure, i get the error message above too, but after this reconfiguring try they are all shown correctly in the map. the other devices i can delete and rejoin again.
> 
> the default fw seems to be more stable.
> 
> now i will join all my devices (22x) and maybe it will work.

I am experiencing the same issues reported here when using the source routing.  

Did reverting back to the default firmware prove to be more stable?

**Comment by DieNummerEins** [comment]
yes, it did.

**Comment by SpitFireRSA** [comment]
Thanks. I reverted and stable now.

**Comment by slemik99** [comment]
> Failed to execute LQI can happen for 2 reasons
> 
> 1. The network is congested and therefore no responses are send. Try increasing the sleep between network scans, change e.g. https://github.com/Koenkk/zigbee2mqtt/blob/99274c72c26ba21347908af8238fa8dfdb4fb99d/lib/extension/networkMap.js#L215
>     to `await utils.sleep(5);`
> 2. The device doesn't support an LQI request (I know this is the case for e.g. non-pro Gledopto devices). Cannot be solved from z2m side

Hi,
Is it possible to solve this in HA add-on mode for z2m?
I can't reach networkMap.js on my installation (
Can it be put to settings?

**Comment by eoryb** [comment]
> > Failed to execute LQI can happen for 2 reasons
> > 
> > 1. The network is congested and therefore no responses are send. Try increasing the sleep between network scans, change e.g. https://github.com/Koenkk/zigbee2mqtt/blob/99274c72c26ba21347908af8238fa8dfdb4fb99d/lib/extension/networkMap.js#L215
> >    
> >    to `await utils.sleep(5);`
> > 2. The device doesn't support an LQI request (I know this is the case for e.g. non-pro Gledopto devices). Cannot be solved from z2m side
> 
> Hi, Is it possible to solve this in HA add-on mode for z2m? I can't reach networkMap.js on my installation ( Can it be put to settings?

My question would be exactly the same?!
How can I do this modification under HAOS installation?!
