### ISSUE TITLE
Stability, restarting and can’t see devices.

### ISSUE THREAD

**Issue by psyciknz** [Koenkk/zigbee2mqtt#6112]
## What happened

I tend to have issues with devices not being pingable.   It normally seems to occur if my docker container stops or has an upgrade to the container.

I end upon the situation where the adapter can't be accessed (it's in the system, but zigbee2mqtt can't access it - time out).

So then I unplug the adapter and reinsert.   And so then zigbee2mqtt will start, but devices are not pingable. 

Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht20' was last seen '269995.382' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht08' was last seen '65577.183' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mct04' was last seen '269062.712' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht13' was last seen '268958.958' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht19' was last seen '269050.478' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht17' was last seen '598269.099' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mht21' was last seen '271439.656' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:18: Non-pingable device 'z2mct12' was last seen '268807.13' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:52:23: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:52:30: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:53:23: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:53:29: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:53:36: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:54:29: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:54:35: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:54:42: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:55:35: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:55:41: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:55:48: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:56:41: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:56:47: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:56:54: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:57:13: Saving state to file /app/data/state.json,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht03' was last seen '270004.662' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht02' was last seen '268731.516' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht06' was last seen '269755.648' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht01' was last seen '269617.843' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht11' was last seen '65888.994' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht20' was last seen '270295.382' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht08' was last seen '65877.183' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mct04' was last seen '269362.712' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht13' was last seen '269258.958' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht19' was last seen '269350.478' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht17' was last seen '598569.098' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mht21' was last seen '271739.656' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:18: Non-pingable device 'z2mct12' was last seen '269107.132' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 09:57:47: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:57:53: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:58:00: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:58:53: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 09:58:59: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 09:59:06: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 09:59:59: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:00:00: Received MQTT message on 'sensors/zigbee2mqtt/bridge/config/devices/get' with data '',
Zigbee2MQTT:info  2021-02-06 10:00:00: MQTT publish: topic 'sensors/zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d93118","lastSeen":1612558800005,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht03","hardwareVersion":30,"ieeeAddr":"0x00158d000227acd7","lastSeen":1612288633378,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":27087,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht02","hardwareVersion":30,"ieeeAddr":"0x00158d00023a0931","lastSeen":1612289906528,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":3192,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht06","hardwareVersion":30,"ieeeAddr":"0x00158d000227ee82","lastSeen":1612288882417,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":53083,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter05","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95853","lastSeen":1612492850325,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":8632,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter03","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95984","lastSeen":1612492866245,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":25299,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht01","hardwareVersion":30,"ieeeAddr":"0x00158d0002b969c7","lastSeen":1612289020248,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":15832,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter06","hardwareVersion":1,"ieeeAddr":"0x00124b0014d962da","lastSeen":1612492854680,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":7907,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht11","ieeeAddr":"0x00158d000253861e","lastSeen":1612492749110,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":57045,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht20","ieeeAddr":"0x00158d000358bc18","lastSeen":1612288342744,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":799,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht08","hardwareVersion":30,"ieeeAddr":"0x00158d0002b72519","lastSeen":1612492760971,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":40970,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"-","friendly_name":"z2mct04","ieeeAddr":"0x00158d00027bac3a","lastSeen":1612289275468,"manufacturerID":4151,"networkAddress":45104,"type":"EndDevice","vendor":"-"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht13","hardwareVersion":30,"ieeeAddr":"0x00158d0002e2af65","lastSeen":1612289379244,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":13712,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht19","ieeeAddr":"0x00158d0002e28ede","lastSeen":1612289287747,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":28120,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht17","ieeeAddr":"0x00158d0002e28e20","lastSeen":1611960069154,"manufacturerID":4151,"model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":58470,"type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht21","hardwareVersion":30,"ieeeAddr":"0x00158d000444a168","lastSeen":1612286898629,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":56383,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia door & window contact sensor","friendly_name":"z2mct12","ieeeAddr":"0x00158d00028b58a1","lastSeen":1612289531156,"manufacturerID":4151,"manufacturerName":"LUMI","model":"MCCGQ01LM","modelID":"lumi.sensor_magnet","networkAddress":12105,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"}]',
Zigbee2MQTT:debug 2021-02-06 10:00:00: Received MQTT message on 'sensors/zigbee2mqtt/bridge/config/devices' with data '[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d93118","lastSeen":1612558800005,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht03","hardwareVersion":30,"ieeeAddr":"0x00158d000227acd7","lastSeen":1612288633378,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":27087,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht02","hardwareVersion":30,"ieeeAddr":"0x00158d00023a0931","lastSeen":1612289906528,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":3192,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht06","hardwareVersion":30,"ieeeAddr":"0x00158d000227ee82","lastSeen":1612288882417,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":53083,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter05","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95853","lastSeen":1612492850325,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":8632,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter03","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95984","lastSeen":1612492866245,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":25299,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht01","hardwareVersion":30,"ieeeAddr":"0x00158d0002b969c7","lastSeen":1612289020248,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":15832,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter06","hardwareVersion":1,"ieeeAddr":"0x00124b0014d962da","lastSeen":1612492854680,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":7907,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht11","ieeeAddr":"0x00158d000253861e","lastSeen":1612492749110,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":57045,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht20","ieeeAddr":"0x00158d000358bc18","lastSeen":1612288342744,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":799,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht08","hardwareVersion":30,"ieeeAddr":"0x00158d0002b72519","lastSeen":1612492760971,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":40970,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"-","friendly_name":"z2mct04","ieeeAddr":"0x00158d00027bac3a","lastSeen":1612289275468,"manufacturerID":4151,"networkAddress":45104,"type":"EndDevice","vendor":"-"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht13","hardwareVersion":30,"ieeeAddr":"0x00158d0002e2af65","lastSeen":1612289379244,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":13712,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht19","ieeeAddr":"0x00158d0002e28ede","lastSeen":1612289287747,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":28120,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht17","ieeeAddr":"0x00158d0002e28e20","lastSeen":1611960069154,"manufacturerID":4151,"model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":58470,"type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht21","hardwareVersion":30,"ieeeAddr":"0x00158d000444a168","lastSeen":1612286898629,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":56383,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia door & window contact sensor","friendly_name":"z2mct12","ieeeAddr":"0x00158d00028b58a1","lastSeen":1612289531156,"manufacturerID":4151,"manufacturerName":"LUMI","model":"MCCGQ01LM","modelID":"lumi.sensor_magnet","networkAddress":12105,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"}]',
Zigbee2MQTT:info  2021-02-06 10:00:00: MQTT publish: topic 'sensors/zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b0014d93118","lastSeen":1612558800011,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht03","hardwareVersion":30,"ieeeAddr":"0x00158d000227acd7","lastSeen":1612288633378,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":27087,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht02","hardwareVersion":30,"ieeeAddr":"0x00158d00023a0931","lastSeen":1612289906528,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":3192,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht06","hardwareVersion":30,"ieeeAddr":"0x00158d000227ee82","lastSeen":1612288882417,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":53083,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter05","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95853","lastSeen":1612492850325,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":8632,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter03","hardwareVersion":1,"ieeeAddr":"0x00124b0014d95984","lastSeen":1612492866245,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":25299,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht01","hardwareVersion":30,"ieeeAddr":"0x00158d0002b969c7","lastSeen":1612289020248,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":15832,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"2018-09-26","description":"[CC2530 router](http://ptvo.info/cc2530-based-zigbee-coordinator-and-router-112/)","friendly_name":"z2mrouter06","hardwareVersion":1,"ieeeAddr":"0x00124b0014d962da","lastSeen":1612492854680,"manufacturerID":4447,"manufacturerName":"LUMI","model":"CC2530.ROUTER","modelID":"lumi.router","networkAddress":7907,"powerSource":"Mains (single phase)","type":"Router","vendor":"Custom devices (DiY)"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht11","ieeeAddr":"0x00158d000253861e","lastSeen":1612492749110,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":57045,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht20","ieeeAddr":"0x00158d000358bc18","lastSeen":1612288342744,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":799,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht08","hardwareVersion":30,"ieeeAddr":"0x00158d0002b72519","lastSeen":1612492760971,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":40970,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"-","friendly_name":"z2mct04","ieeeAddr":"0x00158d00027bac3a","lastSeen":1612289275468,"manufacturerID":4151,"networkAddress":45104,"type":"EndDevice","vendor":"-"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht13","hardwareVersion":30,"ieeeAddr":"0x00158d0002e2af65","lastSeen":1612289379244,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":13712,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht19","ieeeAddr":"0x00158d0002e28ede","lastSeen":1612289287747,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":28120,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia temperature & humidity sensor","friendly_name":"z2mht17","ieeeAddr":"0x00158d0002e28e20","lastSeen":1611960069154,"manufacturerID":4151,"model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":58470,"type":"EndDevice","vendor":"Xiaomi"},{"dateCode":"20160516","description":"MiJia temperature & humidity sensor","friendly_name":"z2mht21","hardwareVersion":30,"ieeeAddr":"0x00158d000444a168","lastSeen":1612286898629,"manufacturerID":4151,"manufacturerName":"LUMI","model":"WSDCGQ01LM","modelID":"lumi.sensor_ht","networkAddress":56383,"powerSource":"Battery","softwareBuildID":"3000-0001","type":"EndDevice","vendor":"Xiaomi"},{"description":"MiJia door & window contact sensor","friendly_name":"z2mct12","ieeeAddr":"0x00158d00028b58a1","lastSeen":1612289531156,"manufacturerID":4151,"manufacturerName":"LUMI","model":"MCCGQ01LM","modelID":"lumi.sensor_magnet","networkAddress":12105,"powerSource":"Battery","type":"EndDevice","vendor":"Xiaomi"}],"type":"devices"}',
Zigbee2MQTT:debug 2021-02-06 10:00:05: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:00:12: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:01:05: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:01:11: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:01:18: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:02:11: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:02:13: Saving state to file /app/data/state.json,
Zigbee2MQTT:debug 2021-02-06 10:02:17: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht03' was last seen '270304.662' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht02' was last seen '269031.515' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht06' was last seen '270055.647' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht01' was last seen '269917.844' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht11' was last seen '66188.993' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht20' was last seen '270595.382' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht08' was last seen '66177.183' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mct04' was last seen '269662.713' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht13' was last seen '269558.958' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht19' was last seen '269650.479' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht17' was last seen '598869.099' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mht21' was last seen '272039.657' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:18: Non-pingable device 'z2mct12' was last seen '269407.131' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:02:24: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:03:17: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:03:23: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:03:30: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:04:23: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:04:29: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:04:36: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:05:29: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:05:35: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:05:42: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:06:35: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:06:41: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:06:48: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:07:13: Saving state to file /app/data/state.json,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht03' was last seen '270604.665' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht02' was last seen '269331.516' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht06' was last seen '270355.648' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht01' was last seen '270217.845' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht11' was last seen '66488.993' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht20' was last seen '270895.383' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht08' was last seen '66477.183' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mct04' was last seen '269962.713' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht13' was last seen '269858.958' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht19' was last seen '269950.479' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht17' was last seen '599169.098' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mht21' was last seen '272339.658' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:18: Non-pingable device 'z2mct12' was last seen '269707.133' seconds ago.,
Zigbee2MQTT:debug 2021-02-06 10:07:41: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:07:47: Failed to ping 'z2mrouter06',
Zigbee2MQTT:debug 2021-02-06 10:07:54: Failed to ping 'z2mrouter03',
Zigbee2MQTT:debug 2021-02-06 10:08:47: Failed to ping 'z2mrouter05',
Zigbee2MQTT:debug 2021-02-06 10:08:53: Failed to ping 'z2mrouter06',

Sorry for the formatting, on phone 
## Debug info
Zigbee2MQTT version:

Latest stable 17.1ish I this. 

Ubuntu 19.04 with docker
Cc2531 coordinator and 4 routers. 
Mostly xiaomi humidity temperature sensors 

Firmware 1.2 or something the 201902 seemed to be the only stable. 

Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by bbrendon** [comment]
I updated to a newer kernel and I still have to reinsert or reboot. Any solutions? I didn't have this problem a long time ago. I think it started 6-12 months ago.

I have  Product: TI CC2531 USB CDC 
Linux ha 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux
