### ISSUE TITLE
Add device status message online / offline on regular time (eg. 30s)

### ISSUE THREAD

**Issue by poki123** [Koenkk/zigbee2mqtt#614]
Hello,

is it possible to add MQTT status online / offline for every registered device?

- for every online device publish MQTT message "online" every 30s (global configuration in the config file)
- one-time message "offline" (or LWT) in case of loss connection

**Comment by Koenkk** [comment]
For enddevices no (because they are asleep most of the time). For routers not yet, this will be addressed in https://github.com/Koenkk/zigbee2mqtt/issues/151
