### ISSUE TITLE
Support Calex LED bubl

### ISSUE THREAD

**Issue by Fossdal** [Koenkk/zigbee2mqtt#618]
Please add suport for CALEX LED bulb
it is this bulb 
https://www.calex.nl/en/catalogue/product/LEDNLE27A60-8-5W-2700-6500ZIGBEE/

have tested it and works. after adding this to devices

    {
        zigbeeModel: ['EC-Z3.0-CCT '],
        model: '421786',
        vendor: 'Calex',
        description: 'Calex LED A60 Zigbee GLS-lamp',
        supports: generic.light_onoff_brightness().supports,
        fromZigbee: generic.light_onoff_brightness().fromZigbee,
        toZigbee: generic.light_onoff_brightness().toZigbee,
    }

**Comment by blawford** [comment]
Why don't you create a Pull Request with the above code then?

**Comment by Fossdal** [comment]
me and git are not best friends :-)

**Comment by Koenkk** [comment]
Added, thanks!
