### ISSUE TITLE
Tuya TS0041 - no battery percentage and voltage

### ISSUE THREAD

**Issue by Mr-Groch** [Koenkk/zigbee2mqtt#6180]
## What happened
[Tuya TS0041](https://www.zigbee2mqtt.io/devices/TS0041.html#tuya-ts0041) device does not send battery values (no voltage and no percentage, but battery is exposed). As can I see in device clusters it should support battery information: 

![image](https://user-images.githubusercontent.com/20594810/107275933-aa2efa00-6a52-11eb-9150-c3dda39c9ae8.png)

I'm using this device 2 months, so I waited a lot :) 

## What did you expect to happen
Battery level should be reported

## How to reproduce it (minimal and precise)
Just pair it and observe no battery values

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC26X2R1 zzh!
Adapter firmware version: 20210120

**Comment by Koenkk** [comment]
Can you try changing the devices.js definition to below? If this config is OK battery should immediately show up after a successful configure.

```js
    {
        zigbeeModel: ['TS0041'],
        model: 'TS0041',
        vendor: 'TuYa',
        description: 'Wireless switch with 1 button',
        whiteLabel: [{vendor: 'Smart9', model: 'S9TSZGB'}, {vendor: 'Lonsonho', model: 'TS0041'}],
        exposes: [e.battery(), e.action(['single', 'double', 'hold'])],
        fromZigbee: [fz.tuya_on_off_action, fz.battery],
        toZigbee: [],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
            await reporting.batteryPercentageRemaining(endpoint);
        },
    },
```

**Comment by Mr-Groch** [comment]
Thanks! I've added this to devices.js and after z2m restart, configuration was done automatically at start, and I see now 100% battery is status message. It is possible, because I didn't use it much ;)

**Comment by Koenkk** [comment]
Added the fix.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
