### ISSUE TITLE
Immax 07005L is paired as 07004D

### ISSUE THREAD

**Issue by standa4** [Koenkk/zigbee2mqtt#6201]
## What happened

Light bulb Immax 07005L is paired as 07004D. 

I bought Immax light bulb (https://www.immaxneo.cz/en/products/immax-neo-smart-led-e14-5w-color-dimmable-zigbee-3-0/) and I planned to make a pull request (or at least experiment with adding new device) because it is not on the list of supported devices. But this light bulb is marked as different one after successfull pairing.

Log says: `identified as: Immax Neo SMART LED E27 8,5W color, dimmable, Zigbee 3.0 (07004D)`

In fact it is: `Immax Neo SMART LED E14 5W color, dimmable, Zigbee 3.0 (07005L)`

## What did you expect to happen

I've expected that the device is not supported because it is not listed in supported devices list. I've planned to add this new device but while it is paired as different one I don't know how to fix it.

## How to reproduce it (minimal and precise)

Pair Immax 07005L light bulb. It is paired as 07004D.

## Debug info
Zigbee2MQTT version: Zigbee2MQTT version 1.17.1 (commit #99274c7)
Adapter hardware: zzh! CC2652R Multiprotocol RF Stick
Adapter firmware version: 20210120

**Comment by Koenkk** [comment]
These seem to share the same model ID, so we cannot distinguish between both. I've changed the model to `07004D/07005L`.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
