### ISSUE TITLE
starting Container in QNAP cannot copy configuration.yaml

### ISSUE THREAD

**Issue by bluesailor45** [Koenkk/zigbee2mqtt#6224]
after having installed image on QNAP Container Station and created container, I get the following error during start of container:
---------------------
Using '/app/data' as data directory                                                                                                   
Creating configuration file...                                                                                                        
/usr/local/bin/docker-entrypoint.sh: line 14: cp: not found                                                                           
Using '/app/data' as data directory                                                                                                   
Creating configuration file...                                                                                                        
/usr/local/bin/docker-entrypoint.sh: line 14: cp: not found    
------------------------**
I already tried to add the following to the 'advanced settings' in the 'shared folders settings'
    /appdata              (to)   /app/data    

(I have created a shared folder '/appdata with read/write privilege in QNAP File structure.

Please help: how can I add the 'configuration.yaml' to docker.

Thank you very much

**Comment by m0wlheld** [comment]
The error message looks like the 'cp' command cannot be found, which is a bit strange.

You could try to avoid this error by providing a [default](https://github.com/Koenkk/zigbee2mqtt/blob/master/data/configuration.yaml) or already configured `configuration.yaml` in your shared folder.
