### ISSUE TITLE
innr SP120 plug has problems to report power, energy and current

### ISSUE THREAD

**Issue by ardu1** [Koenkk/zigbee2mqtt#6231]
Hello, 

I have 3 innr SP120 plugs. I paired them with the Zigbee adapter under ioBroker. The ioBroker has the version 4.2.1, the Zigbee adapter has the version 1.4.3. and I use a Conbee II coordinator. 

1. problem

In the objects list I only find at the SP120 plug this information: Load Power, Switch State, Link Quality, Available and Groups. There is no current and no energy, how is described here:

https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/SP_120.md

2. problem

I connected my water pump with the plug. At the pump is a pressure switch, that starts the motor when the pressure is down. The pump runs about 4-5 time a day. When I want to see the working time from the pump in Grafana I was wondering, that the value Power shows nothing. Then I connected a lamp with 150W and it is showing the correct power value? The problem I have with all three new plugs. 

Does anyone has an ideate solve the problem and to bring current an energy in m?

Thanks and best regards!

 

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment]
For iobroker issues please use https://github.com/ioBroker/ioBroker.zigbee/issues
