### ISSUE TITLE
Lasamot HC-T010

### ISSUE THREAD

**Issue by inext-gr** [Koenkk/zigbee2mqtt#6232]
Please kindly request support for the model in question, we have performed this configuration in the device.js file

{
        fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_ztvwu4nk'}],
        model: 'BHT-002-GCLZB',
        vendor: 'Lasamot',
        description: 'Lasamot series Thermostat',
        supports: 'thermostat, temperature',
        fromZigbee: [fz.moes_thermostat,fz.moes_thermostat_sensor],
        toZigbee: [tz.moes_thermostat_child_lock, tz.moes_thermostat_current_heating_setpoint, tz.moes_thermostat_mode,
            tz.moes_thermostat_standby, tz.moes_thermostat_sensor, tz.moes_thermostat_calibration, tz.moes_thermostat_min_temperature],
        exposes: [exposes.climate().withSetpoint('current_heating_setpoint', 5, 30, 1, ea.STATE_SET).withLocalTemperature(ea.STATE).withSystemMode(['off', 'heat'], ea.STATE)
            .withPreset(['hold', 'program'])],
        onEvent: tuya.onEventSetTime,
    },

we are able to set the setpoint but we cannot detect the current temperature detected. withLocalTemperature(ea.STATE) is N/A

## Information about the device + link
..

## data/database.db entry of the device
..

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
