### ISSUE TITLE
zigbee2mqtt stops working while upgrading HomeAssistant

### ISSUE THREAD

**Issue by jensbri** [Koenkk/zigbee2mqtt#625]
I had a fully running configuration and after updating to hassio-zigbee2mqtt Version 0.2.0 it refused to work. 

@danielwelch asked to post this issue here as well. 
More details can be found over here:
https://github.com/danielwelch/hassio-zigbee2mqtt/issues/71

Thanks for all support!

**Comment by dnaphreak** [comment]
I had this same issue after upgrading today.

**Comment by Koenkk** [comment]
Let's continue here: https://github.com/Koenkk/zigbee2mqtt/issues/617
