### ISSUE TITLE
Hue Bulb Color Temp 

### ISSUE THREAD

**Issue by jcf6288** [Koenkk/zigbee2mqtt#627]
Request the color_temp parameter be converted internally from 0-454 to 0-100.  My hue bulbs are expected the 0-454 range but that makes things difficult for a dimmer in openhab.  Thanks

**Comment by Koenkk** [comment]
We need to somehow distinguish the mireds value (0-454) of the % value (0-100). Would it be possible to add an extra attribute to this message? Or provide the value as: {"color_temp": "80%"}?

**Comment by jcf6288** [comment]
I would say to add a variable similar to RGB and HSV,  I was thinking that if a percentage is sent then it would just multiply it by 454 to  not interfere with the established format.  I don't know how to do this but it would make sense for it to recognize both a number and a percent and do the math internally before sending it on.  Is that possible?

**Comment by Koenkk** [comment]
brightness and color_temp are now accepted in %, can you test this by checking out the dev branch?

**Comment by jcf6288** [comment]
how do I install the dev branch?
________________________________

**Comment by Koenkk** [comment]
How are you running zigbee2mqtt? (via https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge)

**Comment by jcf6288** [comment]
On  stretch lite via a RPI2
________________________________

**Comment by jcf6288** [comment]
I figured it out, what is the correct syntax for the message.  I have tried
{
  "color_temp": 0,
}
and
{
  "color_temp": 0%,
}

**Comment by jcf6288** [comment]
I installed the dev branch and my Hue bulb would go online them immediately offline.

**Comment by jcf6288** [comment]
For a color bulb is it possible to accept the format
{color: { rgb: "12,43,112" }}

**Comment by Koenkk** [comment]
Currently 

```js
{
  "color": {
    // RGB color
    "r": 46,
    "g": 102,
    "b": 193
  }
}
```

is supported, is this ok for you?

**Comment by jcf6288** [comment]
It works but requires a proxy item and rule to convert to a usable format.  For openhab it would simplify things if it could accept either the format mentioned above or and HSB value.

**Comment by Koenkk** [comment]
This is supported know in the dev branch.

For domoticz and home assistant we have instructions on how to integrate with zigbee2mqtt.

Would you mind doing this for openhab? (https://github.com/Koenkk/zigbee2mqtt#integrations)

**Comment by jcf6288** [comment]
I could give it a shot, I will get to work and send you a preview when it is ready.  I will test out the dev branch and let you know.
________________________________

**Comment by jcf6288** [comment]
I set up a new instance of Zigbee2MQTT with the dev installed and my hue bulbs will show connected then go offline.  I cycle power to them and they go online then immediately offline.  Any ideas?

**Comment by jcf6288** [comment]
If I send a RGB such as {"color": {"r":25,"g":0,"b":0}} and the light is off, shouldn't it turn on to a brightness of 10?

**Comment by Koenkk** [comment]
No, that is only the case for brightness (because this is supported by ZCL, not for colortemp and color). To also turn it on send: `{"state": "ON", "color": {"r":25,"g":0,"b":0}}`

**Comment by jcf6288** [comment]
Understand all any ideas why I am having disconnect issues with the dev version?

**Comment by Koenkk** [comment]
Can you provide the log? (maybe zigbeem2qtt crashes)

**Comment by jcf6288** [comment]
I figured out the disconnect issue, it was my fault.  Color Temp works great.  
For color is this the correct format added?
{color: { rgb: "12,43,112" }}

**Comment by Koenkk** [comment]
yes, that format is supported.

**Comment by jcf6288** [comment]
The new format is working sort of, if I send
{"color":{ "rgb": "5,0,0" }} then {"color":{ "rgb": "255,0,0" }}
the output is the exact same, shouldn't the first be dimmer?

**Comment by jcf6288** [comment]
[New Text Document.txt](https://github.com/Koenkk/zigbee2mqtt/files/2636169/New.Text.Document.txt)

**Comment by jcf6288** [comment]
[RGB0,0,0.txt](https://github.com/Koenkk/zigbee2mqtt/files/2636171/RGB0.0.0.txt)

**Comment by Koenkk** [comment]
I think this is due to the xy color conversion (not a bug), see: https://stackoverflow.com/questions/29834556/why-there-is-no-brown-or-grey-in-the-cie-xy-color-space

**Comment by jcf6288** [comment]
After playing with the dev for a few days is it possible to instead accept
{
"color_temp_percent": XX
}
{
"brightness_percent": XX
}

This would significantly improve and simplify the integration with openhab.

**Comment by Koenkk** [comment]
Supported in the dev branch.

**Comment by jcf6288** [comment]
Everything is working great, the last thing would be to accept an HSB value but that isn't necessary to make it work.

**Comment by Koenkk** [comment]
Why? Does openhab send both RGB and HSB values?

**Comment by jcf6288** [comment]
I can send either, with other bindings if you change the color with RGB the brightness follows so 255,0,0 would be 100 percent brightness on the red channel. 2.55,0,0 would be 1 percent brightness.  The difference with Zigbee2MQTT is the user would have to send a brightness command then a color command unless there is a way to have Zigbee2MQTT interpret RGB with a Brightness value, if that makes sense.
________________________________

**Comment by jcf6288** [comment]
So after digging around I found this
`// sRGB luminance(Y) values
const double rY = 0.212655;
const double gY = 0.715158;
const double bY = 0.072187;

// Inverse of sRGB "gamma" function. (approx 2.2)
double inv_gam_sRGB(int ic) {
    double c = ic/255.0;
    if ( c <= 0.04045 )
        return c/12.92;
    else 
        return pow(((c+0.055)/(1.055)),2.4);
}

// sRGB "gamma" function (approx 2.2)
int gam_sRGB(double v) {
    if(v<=0.0031308)
        v *= 12.92;
    else 
        v = 1.055*pow(v,1.0/2.4)-0.055;
    return int(v*255+0.5); // This is correct in C++. Other languages may not
                           // require +0.5
}

// GRAY VALUE ("brightness")
int gray(int r, int g, int b) {
    return gam_sRGB(
            rY*inv_gam_sRGB(r) +
            gY*inv_gam_sRGB(g) +
            bY*inv_gam_sRGB(b)
    );
}`

Would it be possible to send this 
{"color":{ "rgb": "255,0,0" }}

have it calculate the brightness and send both in sequence?  brightness_percent then color?

**Comment by jcf6288** [comment]
https://stackoverflow.com/questions/596216/formula-to-determine-brightness-of-rgb-color is the forum I pulled it from.

**Comment by Koenkk** [comment]
What about

```js
{"color":{ "rgb_brightness": "255,0,0" }}
```

I don't want to change the current behaviour for all RGB commands.

**Comment by jcf6288** [comment]
That would work just fine
________________________________

**Comment by jcf6288** [comment]
Did you implement this?

{"color":{ "rgb_brightness": "255,0,0" }}

Also the new Hue app updates the hue bulbs so that when power returns they can be set to remain off,  is that something that can be implemented?

**Comment by Koenkk** [comment]
Not yet, could you perhaps make a pull request for adding the functions to https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js
