### ISSUE TITLE
Mijia light difference between illuminance and illuminance_lux

### ISSUE THREAD

**Issue by avvalex** [Koenkk/zigbee2mqtt#6285]
I have noticed that the two readings of the same sensor are different. I thought there was only a conversion from illuminance to illuminance_lux, but the graph is not (proportionally) the same (look around 9:00).
Is it normal?
Another thing: close to this sensor I have also an Aqara motion, and it gives a lux value from x2 to x3 than the Mijia.
Perhaps is there a wrong conversion?
![Screenshot_20210214-213538](https://user-images.githubusercontent.com/60694870/107888789-dd6c0000-6f0e-11eb-9c00-5d695b9b7f58.jpg)

**Comment by Koenkk** [comment]
Values look ok to me, the conversion from illuminance to -> illuminance lux is: `Math.pow(10, (illuminance - 1) / 10000)`.


For the RTCGQ11LM check https://github.com/Koenkk/zigbee2mqtt/issues/6202
