### ISSUE TITLE
Image is truncated not long enough to contain a valid Tag

### ISSUE THREAD

**Issue by 885narrow** [Koenkk/zigbee2mqtt#6286]
I tried to update my IKEA Gunnarp lamp. 
It fails with this message.

Zigbee2MQTT:info  2021-02-14 22:28:52: MQTT publish: topic 'zigbee2mqtt/badezimmerlampe/update-state', payload 'available'
Zigbee2MQTT:info  2021-02-14 22:28:52: MQTT publish: topic 'zigbee2mqtt/badezimmerlampe/update_available', payload 'true'
Zigbee2MQTT:info  2021-02-14 22:28:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'badezimmerlampe' failed (Image is truncated: not long enough to contain a valid tag)","meta":{"device":"badezimmerlampe","status":"update_failed"},"type":"ota_update"}'
Zigbee2MQTT:info  2021-02-14 22:28:52: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"0x60a423fffeeecd67"},"error":"Update of 'badezimmerlampe' failed (Image is truncated: not long enough to contain a valid tag)","status":"error"}'
Zigbee2MQTT:info  2021-02-14 22:28:52: MQTT publish: topic 'zigbee2mqtt/badezimmerlampe/linkquality', payload '28'
Zigbee2MQTT:error 2021-02-14 22:28:52: Update of 'badezimmerlampe' failed (Image is truncated: not long enough to contain a valid tag)

sorry , I am totally new to zigbee2mqtt
thank you very much..and thank you for your great work!!

# Bug Report
## What happened
IKEA Gunnarp update failed due to truncated file?

## Debug Info
Zigbee2MQTT version: latest ...
Adapter hardware: CC2531

**Comment by 885narrow** [comment]
Will try to use testserver Ikea

**Comment by 885narrow** [comment]
[https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/ota_updates.md#using-the-ikea-tradfri-test-server](url)

**Comment by 885narrow** [comment]
advanced:
ikea_ota_use_test_url: true

With this setting it does not start and give an script error.
Any help appreciated.. Thx

**Comment by Wauxadd** [comment]
Having same problem with some of my ikea bulbs.
`Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Keittiö Kahvi L"},"error":"Update of 'Keittiö Kahvi L' failed (Image is truncated: not long enough to contain a valid tag)","status":"error","transaction":"nmdve-1"}'
Error Update of 'Keittiö Kahvi L' failed (Image is truncated: not long enough to contain a valid tag)
Debug Received Zigbee message from 'Keittiö Kahvi L', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553788977,"imageType":16901,"manufacturerCode":4476}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Keittiö Kahvi L', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553788977,"imageType":16901,"manufacturerCode":4476}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Keittiö Kahvi L', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"fileVersion":553788977,"imageType":16901,"manufacturerCode":4476}' from endpoint 1 with groupID 0 `

**Comment by Wauxadd** [comment]
> advanced:
> ikea_ota_use_test_url: true
> 
This worked!

**Comment by JsBergbau** [comment]
Also for update of TRADFRI bulb E27 WW 806lm it is currently necessary to use
```
advanced:
  ikea_ota_use_test_url: true
```

**Comment by pklebba** [comment]
Is IKEA still didn't fix the images?

**Comment by mmakaay** [comment]
Yeah, I'm still getting the same error (tried it just now) when not using the test URL.
After switching to the test URL, it works.

**Comment by Coedy** [comment]
> WARNING: Use at your own risk!
> 
> advanced: ikea_ota_use_test_url: true

Thanks for this! Have been struggling for ages to get my oldest bulb to update!

**Comment by flatsiedatsie** [comment]
My bulbs are updating ok without the test server so far, but I'm seeing this issue with a Tradfri Control Outlet instead (v. 2.0.022).

**Comment by akentner** [comment]
I have the same issue with Dresden Elektronik | Mega23M12. 
Any ideas on that device? It's not IKEA, so I can't switch to `ikea_ota_use_test_url`

```
Update of 'terraceroom22_background_highboard' failed (Image is truncated: not long enough to contain a valid tag)
```

**Comment by gavilaso** [comment]
when you said to add
advanced:
ikea_ota_use_test_url: true

are you talking to added to the zigbee2mqtt configuration.yaml or to the regular one... 

can you provide a screenshot on how it should look once it added?

**Comment by pklebba** [comment]
@gavilaso to the configuation.yaml file:

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: warn
  ikea_ota_use_test_url: true
frontend:
  port: 8099
```

**Comment by gavilaso** [comment]
Thanks!
