### ISSUE TITLE
Mijia light illuminance sensor, no data sent/received

### ISSUE THREAD

**Issue by golddragon007** [Koenkk/zigbee2mqtt#6287]
## What happened
No measurements are received/sent from xiaomi Mijia light illuminance sensor.
I have a small problem with one of my previous device that worked previously. I see this in the bind tab
![image](https://user-images.githubusercontent.com/8385152/107890651-56bd2000-6f1a-11eb-8428-d5740a523d01.png)
it connects to the network, but there's no data (illuminance) sent, while this is how it looks like a working one
![image](https://user-images.githubusercontent.com/8385152/107890659-63da0f00-6f1a-11eb-9559-482fd8f1ed50.png)
it doesn't seem that it want to work by it's own
![image](https://user-images.githubusercontent.com/8385152/107890666-6b99b380-6f1a-11eb-8ea8-e967da691077.png)
I also tried to add the missing bind, but I get this:
![image](https://user-images.githubusercontent.com/8385152/107890677-7ce2c000-6f1a-11eb-8cf0-d9e2e399ed77.png)
and this is the only one way that I can press the bind button
![image](https://user-images.githubusercontent.com/8385152/107890688-8bc97280-6f1a-11eb-8505-4843436ba0f1.png)
I've also tried to repair, but nothing. The same issue. How can I fix it? Or the device became faulty?

## What did you expect to happen
Receive illuminance data.

## How to reproduce it (minimal and precise)
Pass.

## Debug info
Zigbee2MQTT version: 1.17.1-1
Adapter hardware: cc2652rb
Adapter firmware version: zStack3x0 20201113

**Comment by golddragon007** [comment]
This is still an existing problem...

**Comment by vomov** [comment]
I'm seeing the same issue; three sensors that used to work, do not work anymore. However:

- When Zigbee2MQTT restarts, I get one (old?) message
- When I press and hold the pairing button, I do see 'device announced'. Nothing else, and I cannot seem to change this behaviour (as in; it'll never say 'left network' or 'paired' or anything else.

**Comment by golddragon007** [comment]
Ok, a little update, I think this was a bug in the controller firmware, I've updated my controller, and now it started to work again with the previously not working sensor. I don't know if a fix was or the flash process itself solved this issue, but now it seems it works.
And I can confirm previously I had the same that @vomov wrote down in his comment.
