### ISSUE TITLE
How could I delete a device ?

### ISSUE THREAD

**Issue by ardu1** [Koenkk/zigbee2mqtt#6322]
Hello, 

I use a ZigBee adapter (1.4.4) together with a ConBee II stick in my ioBroker. During I tried to add some smoke detectors HEIMAN HS1SA some did´t want to pair. They started the interview and nothing more happened. After I tried to pair again the interview did´t start any more. So I asked the Heiman support and they told me, may be there are any fragments of the first pairing, so an other pairing is not possible. If that is true, how could I find this fragments and how could I delete them?

Thanks and best regards!

Before submitting an issue make sure you've searched for a similar issue and read the documentation: https://www.zigbee2mqtt.io/.

Rules (don't ignore these, your issue will be closed without further notice):
- English only
- Make sure you are on the latest Zigbee2MQTT version
- Provide a clear description of the problem
- DON'T copy logs directly here, post a link to https://hastebin.com/ or https://pastebin.com/.
- Make sure you are running the latest firmware https://github.com/koenkk/z-stack-firmware.

Did you read the FAQ?
- https://www.zigbee2mqtt.io/information/FAQ.html

Zigbee2MQTT fails to start?
- https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start

Having issues when using a CC2531?
- Make sure the CC2531 is connected through a USB extension cable
- Try the source routing firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing
- With larger networks (30/40+) devices, your CC2531 might not be powerful enough. This will cause weird issues, in this case it's advised to use a more powerful adapter: https://www.zigbee2mqtt.io/information/supported_adapters.html#texas-instruments-cc26x2r1

Unsupported device?
- https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Device does not pair or interview fails?
- https://www.zigbee2mqtt.io/information/FAQ.html#why-does-my-device-not-or-fail-to-pair

Bug report?
- If applicable, provide steps how to reproduce the problem.
- Provide the herdsman debug logging: https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

-->

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by Koenkk** [comment]
For iobroker zigbee issues use: https://github.com/ioBroker/ioBroker.zigbee/issues
