### ISSUE TITLE
Special charecter in the modelID (FLS-PP3)

### ISSUE THREAD

**Issue by csu-csu** [Koenkk/zigbee2mqtt#633]
HI!

I would like to config a dresden-elektronik FLS-PP controller. 
I made a costum devices.js on my hass.io but It seems there is a special character within the modelID, so it's not working. 
![fls-pp3_error](https://user-images.githubusercontent.com/45321803/48974037-4aa0cb80-f04d-11e8-86da-d5d802476584.PNG)

Any idea how can I handle it?

**Comment by khzd** [comment]
Hi
Did you try to delete this special caractère in the DB ?
I had the same issue for a Xiaomi device

**Comment by Koenkk** [comment]
Can you post your database.db?

**Comment by csu-csu** [comment]
First of all I was able to make it work!
@khzd, You gave me a good idea! I saw what is the special character  in the DB and I write it to the devices.js. And it's work! Otherways it was: "\u0000"

@Koenkk here is my databese if you want to use.

thanks both of you...
[database.zip](https://github.com/Koenkk/zigbee2mqtt/files/2613488/database.zip)

**Comment by khzd** [comment]
EZ :)
