### ISSUE TITLE
New name of Tuya TS0601

### ISSUE THREAD

**Issue by daddvok** [Koenkk/zigbee2mqtt#6335]
Tried to add this motor here https://www.zigbee2mqtt.io/devices/TS0601_cover.html 
See in debug: {"level":"warning","message":"Received message from unsupported device with Zigbee model 'zo2pocs\u0000' and manufacturer name '_TYST11_fzo2pocs'"}
I heard that they do not differ in any way in the way of management, except for the name, can you add to the release?

**Comment by Koenkk** [comment]
Added the device.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
