### ISSUE TITLE
Unable to pair RTCGQ01LM

### ISSUE THREAD

**Issue by tb205gti** [Koenkk/zigbee2mqtt#636]
zigbee2mqtt 0.1.6
npm v6.4.1
node v8.12.0

I'm completely unable to pair a new Xiaomi motion sensor, RTCGQ01LM. I do get the incoming device message, and I can see in the log that it tries to connect, but every single time I get a timeout error.

I can perfectly pair other xiaomi sensors (motion/ambience, door and temp/humid), but not this single RTCGQ01LM. I have almost tried everything now, and it will just not work. 

What do I need to do to make it work?

**Comment by Koenkk** [comment]
Have you followed the pairing procedure from: https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices#xiaomi ?

**Comment by tb205gti** [comment]
Yes, tried everything :/

**Comment by Koenkk** [comment]
Can you try replacing the battery?

**Comment by tb205gti** [comment]
Also tried that :/

**Comment by Koenkk** [comment]
Can you remove all the entries of the device from  `database.db` and try again? (stop zigbee2mqtt before doing)

**Comment by tb205gti** [comment]
if I make a backup of the database.db and the configurations.yaml - will I then be able to restore to the current setup if needed?

**Comment by MaximKraev** [comment]
Anyone got it working? I am having the same issue

**Comment by akuky** [comment]
I successfully installed  zigbee2mqtt ( bridge?)  on RPI3B+ and have Hassio and Mosquitto broker on Ubuntu 18.04 2 Server (docker) } 
Have the "Xiaomi Smart Human Body Sensor" SKU YTC4016CN , paired with zigbee2mqtt as "RTCGQ01LM"
From the log: MQTT publish: topic 'homeassistant/sensor/0x00158d0002717c27/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/MotionSensor","json_attributes_topic":"zigbee2mqtt/MotionSensor","name":"MotionSensor_battery","unique_id":"0x00158d0002717c27_battery_zigbee2mqtt","device" {"identifiers":"zigbee2mqtt_0x00158d0002717c27","name":"MotionSensor","sw_version":"Zigbee2mqtt 1.1.1","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}' 

No problems on Motion detection but no Values or log entries(?) for the battery
Any suggestions? ( The link above is 404)
![nobatteryreading](https://user-images.githubusercontent.com/24996370/52979724-eb7cf980-33a4-11e9-9302-1ebc18a8a031.JPG)
Thanks

**Comment by akuky** [comment]
Yay - got battery voltage in the log - now i just need to figure out how to display it ;)
I unplugged the keyboard for RPI and restarted "npm start" - weird
