### ISSUE TITLE
Blitzwolf BW-SS7 recognized as Zemismart ZM-L03E-Z

### ISSUE THREAD

**Issue by leroyloren** [Koenkk/zigbee2mqtt#6360]
## What happened

Device BW-SS7 (https://www.zigbee2mqtt.io/devices/BW-SS7.html) recognized as https://www.zigbee2mqtt.io/devices/ZM-L03E-Z.html#zemismart-zm-l03e-z

## What did you expect to happen

Recognized as BW-SS7

## Debug info
Zigbee2MQTT version: 1.17.1-4
Adapter hardware: CC2531
Adapter firmware version: 20201127

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by leroyloren** [comment]
I see that the same closed issue exists:

https://github.com/Koenkk/zigbee2mqtt/issues/5263
