### ISSUE TITLE
2nd zigbee2mqtt Gateway

### ISSUE THREAD

**Issue by karsten-jgm** [Koenkk/zigbee2mqtt#6363]
Hi there,

I have HA on Raspberry 4 succesfull installed, incl. zigbee2mqtt.

Because of connection problems (big distances between devices) I have installed 2nd Raspberry3 with only zigbee2mqtt.

Config was successfull and its running. 
HA ist receiving mqtt from external z2m, 

```
Debug Received MQTT message on 'zigbee2mqtt/0x00158d000395123a' with data '{"action":"single","linkquality":136}'
Debug Received MQTT message on 'zigbee2mqtt/0x00158d000395123a' with data '{"click":"single","linkquality":136}'_
```

Is it possible to add this device(s) in HA?

Thanks in advance...

**Comment by m0wlheld** [comment]
https://www.zigbee2mqtt.io/information/FAQ.html#how-do-i-run-multiple-instances-of-zigbee2mqtt

HA will automatically discover, if MQTT discovery is enabled in both HA and Zigbee2MQTT.
