### ISSUE TITLE
CC2531 crashed, then now "MAC transaction expired' (240)" with Moes Tuya TS0601 radiator valve

### ISSUE THREAD

**Issue by 877dev** [Koenkk/zigbee2mqtt#6367]
## What happened

This is possibly two separate issues. Mainly it's the cc2531 crashing..

1) I woke up and all my zigbee devices are offline, I fixed this by restarting the Docker container and power cycling the CC2531 co-ordinator. See attached log, it crashed 04:07am and I restarted at 10:37am: (https://github.com/Koenkk/zigbee2mqtt/files/6009650/zigbee2mqtt_logs_19-02-2021.log)

1a) UPDATE: just crashed again 1:08pm for no apparent reason:

```
Zigbee2MQTT:error 2021-02-19 13:08:18: Adapter disconnected, stopping
Zigbee2MQTT:debug 2021-02-19 13:08:18: Saving state to file /app/data/state.json
Zigbee2MQTT:info  2021-02-19 13:08:18: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
Zigbee2MQTT:info  2021-02-19 13:08:18: Disconnecting from MQTT server
Zigbee2MQTT:error 2021-02-19 13:08:18: Failed to stop Zigbee2MQTT
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! Failed at the zigbee2mqtt@1.17.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-19T13_08_18_130Z-debug.log
```

2) After power cycling/restarting container, it all works, except sending mqtt command to the radiator valve, it does not respond, and in Portainer logs I get these errors in the log: [tuya_error.log](https://github.com/Koenkk/zigbee2mqtt/files/6009669/tuya_error.log)

## What did you expect to happen
1) the cc2531 not to crash randomly.
2) the valve to operate as requested, and the valve to report back to mqtt.

## How to reproduce it (minimal and precise)
1) Not sure why the cc2531 crashes have occurred, it's been rock solid for many months until today. 
   Should I update to the latest coordinator and router firmwares? https://github.com/koenkk/z-stack-firmware
  I assume I will need to re-pair all devices.

2) Maybe the cc2531 crashing has caused the radiator valve to need re-pairing?

## Debug info
Zigbee2MQTT version: Docker1.17.1-dev (commit #a16635d) & Zigbee-herdsman : (0.13.71)
Adapter hardware: CC2531 coordinator and several CC2531 routers
Adapter firmware version: Coordinator FIRMWARE_CC2531_DEFAULT_20190608, Routers CC2531_router_2019_02 (router-cc2531-std.hex)

## Herdsman debugging
As I'm using Docker compose I don't see instructions, however I configured my docker-compose.yml like this, but still do not see any extra herdsman debugging:
```
  zigbee2mqtt:
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
    - ./volumes/zigbee2mqtt/data:/app/data
    restart: unless-stopped
    network_mode: host
    environment: DEBUG=*
```

## Network map
Tuya radiator valve is 2nd on top row, map shows in current state with "MAC transaction expired" error:
![image](https://user-images.githubusercontent.com/46575282/108501786-b5cbbd80-72a9-11eb-93f3-6eff087b31c7.png)

**Comment by Koenkk** [comment]
CC2531 crashes are not uncommon, this is because the adapter is not very powerful. Switching to the source routing firmware might provide more stability: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing . Else a more powerful adapter is needed: https://www.zigbee2mqtt.io/getting_started/what_do_i_need.html#supported-zigbee-adapter

**Comment by 877dev** [comment]
@Koenkk thank you, i have added more devices recently so that's why it's crashing perhaps. 

I will flash source routing, so I also need to reflash my cc2531 routers?

And when I swap to zzh stick, can I still use all the cc2531 routers, or best to change them all to zzh?

Thank you

**Comment by Koenkk** [comment]
> I will flash source routing, so I also need to reflash my cc2531 routers?

No repairing needed

> And when I swap to zzh stick, can I still use all the cc2531 routers, or best to change them all to zzh?

You can still use your cc2531 routers but you will have to repair all devices when switching to the zzh

https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices

**Comment by 877dev** [comment]
Thank you! 
For some reason I did have to repair all my devices, but it was quite a quick process.

All is working again now, I will be purchasing a zzh or similar as soon as stock is available.
