### ISSUE TITLE
Aqara Bulb

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee2mqtt#637]
Who will be the first? :)

![image](https://user-images.githubusercontent.com/8360230/49081184-054fea00-f257-11e8-9d71-f617f5c4628c.png)

Aqara Bulb ZNLDP12LM
https://aliexpress.com/item/Xiao-mi-Aqara-ZNLDP12LM/32955853941.html

**Comment by kiwinol** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/621

**Comment by kirovilya** [comment]
Oh.
