### ISSUE TITLE
Lidl HG06106B color red no light

### ISSUE THREAD

**Issue by luca-iodice** [Koenkk/zigbee2mqtt#6383]
## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by luca-iodice** [comment]
When I set the light of Lidl HG06106B to red 255 the lamp doesn't turn on.
Sometimes trying to change the color to reddish color doesn't do anything ( I have to trigger multiple times)

**Comment by Chekedaudau** [comment]
Hey, I fixed it temporary with the applyredfix: https://github.com/Koenkk/zigbee2mqtt/issues/5011
But thats not a final solution.

**Comment by Koenkk** [comment]
@Chekedaudau `applyRedFix` is enabled by default in the latest zigbee2mqtt
