### ISSUE TITLE
TS0503B color calibration problem

### ISSUE THREAD

**Issue by FaBRiK74** [Koenkk/zigbee2mqtt#6386]
## What happened
The colors are not correct. E.g. total red contains even blue and green. Total Blue contains a very little red.
can't set yellow at all.
When I try to set colors manually with the RGB there are some interesting issues: Below a given value the related color switches off, then sets back the value to 0 or 255: R below 43, G below 58 and B below 75 switches off. Thet means the following RGB codes gives totally switch off: 42,0,0; 0,57,0; 0,0,74
When I set 255,0,0 it goes back 255,0,17

The module and the LED strip itself have no any problem. Withouh Z2M (with its button) I can set full Red, Green and Blue as well.

Zigbee2MQTT version: Z2M Edge (reinstalled for the latest)
Adapter hardware: CC2531 (Sonoff)

**Comment by FaBRiK74** [comment]
Is there any solution for this issue?

**Comment by FaBRiK74** [comment]
The issue still exists.

**Comment by FaBRiK74** [comment]
The problem still exists

**Comment by FaBRiK74** [comment]
The issue still exists

**Comment by FaBRiK74** [comment]
Unfortunately still exists.

**Comment by pawelbudynek** [comment]
Maybe the hue_correction parameter could fix that? I have similar problem but I am not sure how to use this parameter from documentation...
