### ISSUE TITLE
IKEA LED1624G9 Control Color Temperature | opal white

### ISSUE THREAD

**Issue by jardin-de** [Koenkk/zigbee2mqtt#6388]
I own two IKEA LED1624G9 and would like to control warm and cold white with them.

https://www.zigbee2mqtt.io/devices/LED1624G9.html

Unfortunately, the lamps cannot be controlled with color_temp. Is there a specific reason for this?

**Comment by Koenkk** [comment]
Bulb doesn't support this (https://github.com/Koenkk/zigbee2mqtt/issues/4845)
