### ISSUE TITLE
AB3257001NJ - Osram smart plug crashes in 0.20 

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#639]
As soon i switch from ON/OFF it crashes. This worked flawless before i updated to 0.20
Se log
https://paste.ubuntu.com/p/D3QSq43VwM/

**Comment by Koenkk** [comment]
Can you check if it works in the dev branch?

**Comment by Koenkk** [comment]
This has been fixed in the dev branch. https://github.com/Koenkk/zigbee2mqtt/issues/632

**Comment by salopette** [comment]
last dev crashed

https://pastebin.com/CTgvHAzU

**Comment by Koenkk** [comment]
@salopette see https://github.com/Koenkk/zigbee-shepherd-converters/issues/148#issuecomment-442588584
