### ISSUE TITLE
support sensor-gas GASSensor-EF-3.0 m414-5E

### ISSUE THREAD

**Issue by maverik80** [Koenkk/zigbee2mqtt#6391]
hello, unfortunately this device is detected as unsupported and I tried to follow the guide for the support of new products but I did not succeed, I kindly ask if it is possible to support this product, I leave product links to facilitate recognition

https://it.aliexpress.com/item/32840620167.html?spm=a2g0s.9042311.0.0.395e4c4dBt1RC8

this is debug:

Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x842e14fffef80e6e","supported":false},"type":"pairing"}'
Debug Received Zigbee message from '0x842e14fffef80e6e', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'raw', cluster 'genBasic', data '{"data":[13,11,18,56,241,255,71,65,83,83,101,110,115,111,114,45,69,70,45,51,46,48,18,2,0,0,0,0,1,2,4,1,255,43,0,32,0,255,255,255,255,255,255,255],"type":"Buffer"}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"modelId":"GASSensor-EF-3.0"}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"HEIMAN"}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"appVersion":18}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"hwVersion":32}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{"dateCode":"2020.8.20"}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":0}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00212effff053895","zoneState":1}' from endpoint 1 with groupID null
Received Zigbee message from '0x842e14fffef80e6e', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 1 with groupID null
LQI succeeded for '0x842e14fffef80e6e'

thank you very much

**Comment by sjorge** [comment]
You can try with adding this to devices.js

```javascript
    {
        zigbeeModel: ['GASSensor-EF-3.0'],
        model: 'HS1CG-E',
        vendor: 'HEIMAN',
        description: 'Combustible gas sensor',
        fromZigbee: [fz.ias_gas_alarm_1],
        toZigbee: [],
        exposes: [e.gas(), e.battery_low(), e.tamper()],
    },
```

**Comment by maverik80** [comment]
ok soon I'll try this and let you know

**Comment by maverik80** [comment]
sorry if I stress you but I have recently approached this world even I know I already have 20napparecchiature connected, where can I find the file device.js in raspbian in docker?

**Comment by sjorge** [comment]
I'm not 100% as I don't use docker, but I'd assume a `find /path/to/docker/root -name devices.js` should find it.

**Comment by maverik80** [comment]
I try to see if I find it because I have no idea where to put the code you passed me

**Comment by sjorge** [comment]
Once you find the file, just add it somewhere along the Heiman section. Order shouldn’t  matter.

**Comment by maverik80** [comment]
Unfortunately I'm trying to look for it but I don't know where it is, I hope to be able to find it

**Comment by maverik80** [comment]
can the device.js file be the device.yaml file? but inside I see only the friendly names, then I have the addon's configuration.yaml file of z2m

**Comment by sjorge** [comment]
No devices.yaml is not the correct file

**Comment by maverik80** [comment]
I guessed it wasn't the right one but I really can't find this file, I start to get nervous 😂

**Comment by sjorge** [comment]
https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#2-adding-your-device

Maybe this is helpful

**Comment by maverik80** [comment]
I am following the guide but I stop when I need to add volumes to the container, I enter" docker run -v /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters" and I get this

root@raspberrypi:/opt/zigbee-herdsman-converters# docker run -v /opt/zigbee-herdsman-converters:/app/node_modules/zigbee-herdsman-converters
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
-------------------------
i don't really understand how to enter this command and add volumes to container

**Comment by maverik80** [comment]
after all my trials to add volume to the container i always get this, i don't know what to do,
![log](https://user-images.githubusercontent.com/62015384/108688765-924a8200-74f8-11eb-9aa4-cdc7f1d251dc.png)

**Comment by sjorge** [comment]
Hopefully someone with docker experience comes along, as I have no idea on the error.

**Comment by maverik80** [comment]
hopefully, I'm going crazy

**Comment by BFFonseca** [comment]
> You can try with adding this to devices.js
> 
> ```js
>     {
>         zigbeeModel: ['GASSensor-EF-3.0'],
>         model: 'HS1CG-E',
>         vendor: 'HEIMAN',
>         description: 'Combustible gas sensor',
>         fromZigbee: [fz.ias_gas_alarm_1],
>         toZigbee: [],
>         exposes: [e.gas(), e.battery_low(), e.tamper()],
>     },
> ```

Would this work on the HomeAssistant Z2M addon?
Do you know where I can find the 'devices.js' file?

**Comment by BFFonseca** [comment]
Was able to make it work on the Z2M HA addon.
Created the file '/config/zigbee2mqtt/devices.js' and added 
```
"external_converters": [
    "devices.js"
  ]
```

to the Z2M 'config.yaml' file.

The "devices.js" file contains:
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const device = {
    zigbeeModel: ['GASSensor-EF-3.0'],
    model: 'HS1CG-E',
    vendor: 'HEIMAN',
    description: 'Combustible gas sensor',
    fromZigbee: [fz.ias_gas_alarm_2],
    toZigbee: [],
    exposes: [e.gas(), e.battery_low(), e.tamper()],
};
module.exports = device;
```
With `fz.ias_gas_alarm_1` it wasn't reporting the status when I pressed the "test" button on the device. Changing this to `fz.ias_gas_alarm_2` made it work

**Comment by maverik80** [comment]
the problem is that I work in supervised and I am unable to mount it

**Comment by Koenkk** [comment]
@BFFonseca added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by maverik80** [comment]
i entered manually as you advised me and it worked, thanks a lot BBFonseca
