### ISSUE TITLE
OTA update toast should use ≈ and not +-

### ISSUE THREAD

**Issue by ndoo** [Koenkk/zigbee2mqtt#6397]
+- (±) is used to represent (in mathematics) 2 values, or (in engineering) a tolerance, when specified with a number.

Thus, ≈ is a more appropriate symbol to use in the OTA toast, as it is displaying an approximate time remaining.

https://github.com/Koenkk/zigbee2mqtt/blob/07cdc9d549a9db4aa94a259388241b71aec4e12d/lib/extension/otaUpdate.js#L202

**Comment by Koenkk** [comment]
Changed!

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
