### ISSUE TITLE
Aqara Wall Switch (Double Rocker) not working in branch DEV

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#640]
After switching to DEV branch for some other feature my Aqara Wall Switches now don't fire MQTT publishes anymore when pressing them.

Running zigbee2mqtt in debug mode I see that the press is registered but not processed further. Looks like something broke from master -> dev.

Debug is at https://pastebin.com/DDbq4aH7

**Comment by Koenkk** [comment]
This has been fixed in the dev branch, can you confirm?

**Comment by andreasbrett** [comment]
There hasn't been any new commit since my testing 8 hours ago. I already was on the dev branch for zigbee2mqtt.

**Comment by andreasbrett** [comment]
What I reverted was:

https://github.com/Koenkk/zigbee-shepherd-converters/blob/4cc2abbf0079e8b40e8bd103d787f296f3e0e4af/converters/fromZigbee.js#L503-L505

https://github.com/Koenkk/zigbee-shepherd-converters/blob/4cc2abbf0079e8b40e8bd103d787f296f3e0e4af/devices.js#L128-L130

**Comment by Koenkk** [comment]
Can you provide the whole log?

**Comment by andreasbrett** [comment]
Problem is: when I switch to the dev branch for zigbee2mqtt, clean all node modules and run npm install I won't get the dev branch for zigbee-shepherd (at least looked like to me). So what I did afterwards is to remove the zigbee-shepherd folder in node_modules and clone it directly from github (and of course switching to dev).

**Comment by andreasbrett** [comment]
Yes, now it works. zigbee-shepherd-converts latest version gets pulled during npm install. My wall switches work again with zigbee2mqtt on dev.
