### ISSUE TITLE
No white channel on RGBW controller 'TS0504B'

### ISSUE THREAD

**Issue by rmickael62** [Koenkk/zigbee2mqtt#6408]
I just bought the same model of controller "TS0504B" but I do not understand how to control the white channel? 
![TS0504B](https://user-images.githubusercontent.com/34349993/108692191-98426200-74fc-11eb-8356-16f8d0829f1f.PNG)

_Originally posted by @rmickael62 in https://github.com/Koenkk/zigbee2mqtt/issues/6299#issuecomment-783249778_

**Comment by rmickael62** [comment]
devices.js
{
        fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
        model: 'TS0504B',
        vendor: 'TuYa',
        description: 'Zigbee smart mini led strip controller 5V/12V/24V RGBW',
        extend: preset.light_onoff_brightness_colorxy(), <=  **_preset.light_onoff_brightness_colortemp_colorxy() ?_**
        meta: {applyRedFix: true},
    },

**Comment by Koenkk** [comment]
The Zigbee ZCL spec does not define anything like a `white_value`. Did you try with `preset.light_onoff_brightness_colortemp_colorxy() ` does it work then? 

Can you also share the data/database.db entry of this device?

**Comment by rmickael62** [comment]
preset.light_onoff_brightness_colortemp_colorxy() => does not work.

database.db :
{"id":52,"type":"Router","ieeeAddr":"0x60a423fffee28dac","nwkAddr":60195,"manufId":4098,"manufName":"_TZ3000_ukuvyhaa","powerSource":"Mains (single phase)","modelId":"TS0504B","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,3,4,5,6,4096,8,768],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0504B","manufacturerName":"_TZ3000_ukuvyhaa","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1614102988277}

**Comment by Koenkk** [comment]
Given that is only has 1 endpoint. It seems the white channel is controlled in some non standard way. You will need to sniff the traffic with the original gateway while controlling the white channel and post it here: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by rmickael62** [comment]
I don't have an original gateway, is it possible with a sonoff zigbee bridge? knowing that the device is compatible with tuya and alexa.

**Comment by Koenkk** [comment]
I don't know if you can set it with a sonoff zigbee bridge, you can try.

**Comment by jti989** [comment]
Hi @rmickael62,
I have the same problem. Have you been able to solve it?

**Comment by rmickael62** [comment]
Hi
I think that the white channel cannot be controlled directly in zigbee (obligation to use the button) I would use this module only for RGB.

**Comment by bluefish007** [comment]
Hopefully a solution can be found. Unfortunately, I can not control white either.

**Comment by jti989** [comment]
I spent some time with the controller and recognised that there are zigbee messages that may be useful for implementing this.
When I first changed the color mode to white (coming from RGB) with the hardware button, there was this message:

`Zigbee2MQTT:debug 2021-03-23 12:30:26: Received Zigbee message from '0x60a423fffe94d1d8', type 'attributeReport', cluster 'lightingColorCtrl', data '{"tuyaRgbMode":2}' from endpoint 1 with groupID 0`

When changing colors afterwards there are messages like this:
`Zigbee2MQTT:debug 2021-03-23 12:40:43: Received Zigbee message from '0x60a423fffe94d1d8', type 'raw', cluster 'lightingColorCtrl', data '{"data":[24,15,10,3,240,72,10,2,0,14,13,0,15,0,0,232,232],"type":"Buffer"}' from endpoint 1 with groupID 0`

And when switching to white again the message is longer:
`Zigbee2MQTT:debug 2021-03-23 12:40:51: Received Zigbee message from '0x60a423fffe94d1d8', type 'raw', cluster 'lightingColorCtrl', data '{"data":[24,17,10,3,240,72,18,4,3,70,70,120,240,232,232,0,0,70,70,120,192,232,10,0,0],"type":"Buffer"}' from endpoint 1 with groupID 0`

I don't know how to decode these messages, but I have the feeling that the information we need is in it.
Could we reopen this topic @Koenkk  and @rmickael62 ?

**Comment by mramirezd** [comment]
Me too! Thank you

**Comment by bluefish007** [comment]
Problem still exists :(

**Comment by bluefish007** [comment]
Unfortunately it still does not work!

**Comment by bluefish007** [comment]
Still not working!

**Comment by MattiaFochesato** [comment]
I managed to get it to work with this code:

``` 
const definition = {
        fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
        model: 'TS0504B',
        vendor: 'TuYa',
        description: 'Zigbee RGBW light',
        toZigbee: [tz.on_off, tz.tuya_led_control],
        fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
        exposes: [e.light_brightness_colortemp_colorhs([498, 500]).removeFeature('color_temp_startup')],
        meta: {applyRedFix: true, enhancedHue: false},
};
```

Just set any value as color temperature and the controller deactivates the RGB output and activates the W output with the respective brightness set.

It's not the best solution but at least it works. Better than nothing

**Comment by bluefish007** [comment]
@MattiaFochesato 

Thanks for this idea! But how to go back to RGB? I do not come back when I enter a color...

And I can't control brightness after this change...

**Comment by fastplayer95** [comment]
Hey there @MattiaFochesato,

first of all, thanks for your solution.
For me it works!

However i do get Errors:

'''
Zigbee2MQTT:error 2021-07-20 10:05:27: Publish 'set' 'color_temp' to 'led_strip' failed: 'TypeError: Cannot read property 'hasOwnProperty' of undefined'
Zigbee2MQTT:error 2021-07-20 10:07:38: No converter available for 'color_temp' (500)
Zigbee2MQTT:error 2021-07-20 10:09:44: No converter available for 'color_temp' (499)
Zigbee2MQTT:error 2021-07-20 10:09:46: No converter available for 'color_temp' (498)
'''

**Comment by Omirax** [comment]
Better than nothing, but we need full integration.

**Comment by untitledH** [comment]
> const definition = {
>         fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
>         model: 'TS0504B',
>         vendor: 'TuYa',
>         description: 'Zigbee RGBW light',
>         toZigbee: [tz.on_off, tz.tuya_led_control],
>         fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
>         exposes: [e.light_brightness_colortemp_colorhs([498, 500]).removeFeature('color_temp_startup')],
>         meta: {applyRedFix: true, enhancedHue: false},
> };

This works within zigbee2mqtt but not with hass, something is wrong when it convert the colorxy value to a colorhs value.

**Comment by rodrigoscoelho** [comment]
Same problem here

**Comment by rodrigoscoelho** [comment]
> I managed to get it to work with this code:
> 
> ```
> const definition = {
>         fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
>         model: 'TS0504B',
>         vendor: 'TuYa',
>         description: 'Zigbee RGBW light',
>         toZigbee: [tz.on_off, tz.tuya_led_control],
>         fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
>         exposes: [e.light_brightness_colortemp_colorhs([498, 500]).removeFeature('color_temp_startup')],
>         meta: {applyRedFix: true, enhancedHue: false},
> };
> ```
> 
> Just set any value as color temperature and the controller deactivates the RGB output and activates the W output with the respective brightness set.
> 
> It's not the best solution but at least it works. Better than nothing

Did you get it working with HA? On mine, I don't have option for Color temperature on HA.

Thanks.

**Comment by deeja** [comment]
> I managed to get it to work with this code:
> 
> ```
> const definition = {
>         fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
>         model: 'TS0504B',
>         vendor: 'TuYa',
>         description: 'Zigbee RGBW light',
>         toZigbee: [tz.on_off, tz.tuya_led_control],
>         fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
>         exposes: [e.light_brightness_colortemp_colorhs([498, 500]).removeFeature('color_temp_startup')],
>         meta: {applyRedFix: true, enhancedHue: false},
> };
> ```
> 
> Just set any value as color temperature and the controller deactivates the RGB output and activates the W output with the respective brightness set.
> 
> It's not the best solution but at least it works. Better than nothing

@MattiaFochesato I'm new here. Where does this code go?

**Comment by deeja** [comment]
> @MattiaFochesato
> 
> Thanks for this idea! But how to go back to RGB? I do not come back when I enter a color...
> 
> And I can't control brightness after this change...

`zigbee2mqtt/[ID here]/set`
To white:
```json
{"color_temp": 1}
```
to get [back to color](https://www.zigbee2mqtt.io/devices/TS0504B.html):
```json
{"color":{"hex":"#547CFF"}}
````

**Comment by pawelbudynek** [comment]
The problem still exist, I do have original gateway, so I can try to help, but I need instructions :)

**Comment by rodrigoscoelho** [comment]
Yes. It is not working as expected. And it is a product with a high number
os sells. It would be great to have it working 100%.


Enviado utilizando um Galaxy S10...

Em ter., 5 de out. de 2021 10:54, pawelbudynek ***@***.***>
escreveu:

**Comment by th3d00d** [comment]
any solution to use it in Home Assistant so far?

**Comment by rodrigoscoelho** [comment]
Nope. We really need an expert help on this

Enviado utilizando um Galaxy S10...

Em sáb., 6 de nov. de 2021 20:16, th3d00d ***@***.***>
escreveu:

**Comment by pchrzaszczewski** [comment]
I have the same problem with 7 controllers and I have no idea how to solve it.
Please help!

**Comment by ferrarii1** [comment]
I have a controller like this and a zigbee sniffer. When you press the button on the controller to turn on white, it doesn't send anything. How else can you catch the inclusion of white?

**Comment by ferrarii1** [comment]
sniff zigbee traffic from the zigbee gateway tuya to the led stripe.
link to the video that I clicked [https://youtu.be/c2Sy4lzHor0](url)
link yo pcap file [https://drive.google.com/file/d/1lWOpJUaLwiAmXNT-6Kf3t8kBtMO2b-ng/view?usp=sharing](url)

**Comment by Koenkk** [comment]
@ferrarii1 do you have the network key for me?

**Comment by ferrarii1** [comment]
@Koenkk 6f9c97b9bb168b7236017d86be11ee61

**Comment by Koenkk** [comment]
What happens when you change the color temperature when using the following external converter?

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;


const definition = {
    fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
    model: 'TS0504B',
    vendor: 'TuYa',
    description: 'RGB+CCT LED _ EXTERNAL CONVERTER',
    toZigbee: [tz.on_off, tz.tuya_led_control],
    fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
    exposes: [e.light_brightness_colortemp_colorhs([153, 500]).removeFeature('color_temp_startup')],
},;

module.exports = definition;

```

(after adding the converter and restarting z2m, make sure it loaded it by going to the frontend, the description of this device should now be: `RGB+CCT LED _ EXTERNAL CONVERTER`)

How to user external converter: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions

If that doesn't help, you will need to reverse engineer the TuYa commands that control the white mode, examples in your sniff are no. 41, no. 63

**Comment by pawelbudynek** [comment]
Guys that's a breakthrough indeed!

**Comment by rodrigoscoelho** [comment]
THE GUY is on. Now it will work. 😂

Em sex., 19 de nov. de 2021 às 16:38, Koen Kanters ***@***.***>
escreveu:

**Comment by ferrarii1** [comment]
Do you need a pcap? or tell how the LED strip behaves?

**Comment by ferrarii1** [comment]
> What happens when you change the color temperature when using the following external converter?
> 
> ```js
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const e = exposes.presets;
> const ea = exposes.access;
> 
> 
> const definition = {
>     fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}],
>     model: 'TS0504B',
>     vendor: 'TuYa',
>     description: 'RGB+CCT LED _ EXTERNAL CONVERTER',
>     toZigbee: [tz.on_off, tz.tuya_led_control],
>     fromZigbee: [fz.on_off, fz.tuya_led_controller, fz.brightness, fz.ignore_basic_report],
>     exposes: [e.light_brightness_colortemp_colorhs([153, 500]).removeFeature('color_temp_startup')],
> },;
> 
> module.exports = definition;
> ```
> 
> (after adding the converter and restarting z2m, make sure it loaded it by going to the frontend, the description of this device should now be: `RGB+CCT LED _ EXTERNAL CONVERTER`)
> 
> How to user external converter: https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions
> 
> If that doesn't help, you will need to reverse engineer the TuYa commands that control the white mode, examples in your sniff are no. 41, no. 63

Do you need a pcap? or tell how the LED strip behaves?

**Comment by Koenkk** [comment]
tell how the strip behaves when changing the color temperature

**Comment by ferrarii1** [comment]
does not react to temperature changes. 
but at least from the color mode can be displayed in white. Ideally, make sure that when you press white, it turns on not the RGB white, but white LEDs.
![image](https://user-images.githubusercontent.com/90213726/142697460-bd178829-8528-4e5b-b476-b64c65927332.png)
the converter is written for RGB+CCT, and this controller is RGB+W.

**Comment by Koenkk** [comment]
@ferrarii1 could you provide a which only contains setting the white channel from the TuYa gateway?

**Comment by ferrarii1** [comment]
pcap file where did I include white?

**Comment by Koenkk** [comment]
@ferrarii1 yes, produced by:
- start sniffing
- control white channel **once**
- stop sniffing

**Comment by ferrarii1** [comment]
no. 163 on white channel
no 174-192  white channel from 0% minimum to 100% maximum
no 210 off
(https://drive.google.com/file/d/1bxewenq0aso8AGhMUt816zOme78IxVSB/view?usp=sharing)

**Comment by Koenkk** [comment]
Coud you
- update to the latest dev branch
- add the following external converter: (see https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#instructions how to do this)
```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const tzLocal = {
    test_1: {
        key: ['test_1'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaWhite', {data: [0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x33, 0x33, 0x34, 0x30, 0x33, 0x65, 0x38]});
        },
    },
    test_2: {
        key: ['test_2'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaRgbMode2', {data: [0]});
        },
    },
}

const definition = {
    fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}, {modelID: 'TS0504B', manufacturerName: '_TZ3210_ttkgurpb'}],
    model: 'TS0504B',
    vendor: 'TuYa',
    description: 'Zigbee RGBW light - EXTERNAL DEFINTION',
    exposes: extend.light_onoff_brightness_color().exposes,
    toZigbee: [...extend.light_onoff_brightness_color().toZigbee, tzLocal.test_1, tzLocal.test_2],
    fromZigbee: extend.light_onoff_brightness_color().fromZigbee,
    meta: {applyRedFix: true},
};

module.exports = definition;
```
- open the frontend, make sure the external converter work, the of the device should be `Zigbee RGBW light - EXTERNAL DEFINTION'` now
- if yes, what happens when you send to `zigbee2mqtt/DEVICE_FRIENDLY_NAME/set`
  - payload: `{"test_1":""}`
  - payload: `{"test_2":""}`

**Comment by ferrarii1** [comment]
debug Received MQTT message on 'zigbee2mqtt/0x9035eafffe583b6d/set' with data '{"test_1":""}'
error No converter available for 'test' (undefined)
debug Received MQTT message on 'zigbee2mqtt/0x9035eafffe583b6d/set' with data '{"test_2":""}'
error Device '0x9035eafffe583b6d' has no endpoint '2'
![image](https://user-images.githubusercontent.com/90213726/143215101-e992a979-457b-4c20-a5ba-954238f54c1b.png)
![image](https://user-images.githubusercontent.com/90213726/143215267-1d74cc26-be64-4b39-878c-fd6377129754.png)

**Comment by Koenkk** [comment]
@ferrarii1 can you check with:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const tzLocal = {
    test_1: {
        key: ['test1'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaWhite', {data: Buffer.from([0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x33, 0x33, 0x34, 0x30, 0x33, 0x65, 0x38])});
        },
    },
    test_2: {
        key: ['test2'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaRgbMode2', {data: Buffer.from([0])});
        },
    },
}

const definition = {
    fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}, {modelID: 'TS0504B', manufacturerName: '_TZ3210_ttkgurpb'}],
    model: 'TS0504B',
    vendor: 'TuYa',
    description: 'Zigbee RGBW light - EXTERNAL DEFINTION',
    exposes: extend.light_onoff_brightness_color().exposes,
    toZigbee: [...extend.light_onoff_brightness_color().toZigbee, tzLocal.test_1, tzLocal.test_2],
    fromZigbee: extend.light_onoff_brightness_color().fromZigbee,
    meta: {applyRedFix: true},
};

module.exports = definition;

```

**Comment by ferrarii1** [comment]
@Koenkk, ok.
[test1.txt](https://github.com/Koenkk/zigbee2mqtt/files/7599801/test1.txt)
[test2.txt](https://github.com/Koenkk/zigbee2mqtt/files/7599802/test2.txt)

**Comment by Koenkk** [comment]
And with:

```js
const Buffer = require('buffer');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const tzLocal = {
    test_1: {
        key: ['test1'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaWhite', {data: Buffer.from([0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x33, 0x33, 0x34, 0x30, 0x33, 0x65, 0x38])});
        },
    },
    test_2: {
        key: ['test2'],
        convertSet: async (entity, key, value, meta) => {
            await entity.command('lightingColorCtrl', 'tuyaRgbMode2', {data: Buffer.from([0])});
        },
    },
}

const definition = {
    fingerprint: [{modelID: 'TS0504B', manufacturerName: '_TZ3000_ukuvyhaa'}, {modelID: 'TS0504B', manufacturerName: '_TZ3210_ttkgurpb'}],
    model: 'TS0504B',
    vendor: 'TuYa',
    description: 'Zigbee RGBW light - EXTERNAL DEFINTION',
    exposes: extend.light_onoff_brightness_color().exposes,
    toZigbee: [...extend.light_onoff_brightness_color().toZigbee, tzLocal.test_1, tzLocal.test_2],
    fromZigbee: extend.light_onoff_brightness_color().fromZigbee,
    meta: {applyRedFix: true},
};

module.exports = definition;
```

**Comment by ferrarii1** [comment]
@Koenkk 

debug Received MQTT message on 'zigbee2mqtt/0x9035eafffe583b6d/set' with data '{"test2":""}'
debug Publishing 'set' 'test2' to '0x9035eafffe583b6d'
error Publish 'set' 'test2' to '0x9035eafffe583b6d' failed: 'TypeError: Buffer.from is not a function'
debug TypeError: Buffer.from is not a function at Object.convertSet (/opt/zigbee2mqtt/dist/util/externally-loaded.js:20:85) at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:247:52) at EventEmitter.emit (events.js:412:35) at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:95:22) at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:113:27) at MqttClient.emit (events.js:400:28) at MqttClient._handlePublish (/opt/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12) at MqttClient._handlePacket (/opt/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12) at work (/opt/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12) at Writable.writable._write (/opt/zigbee2mqtt/node_modules/mqtt/lib/client.js:335:5)
info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'test2' to '0x9035eafffe583b6d' failed: 'TypeError: Buffer.from is not a function'","meta":{"friendly_name":"0x9035eafffe583b6d"},"type":"zigbee_publish_error"}'

**Comment by ferrarii1** [comment]
const Buffer = require('buffer').Buffer;
work

**Comment by Koenkk** [comment]
Is it possible to change the white brightness when setting it in white mode now?

**Comment by ferrarii1** [comment]
yes, with the slider the brightness in the exposes

**Comment by Anatol6868** [comment]
Command: Unknown (0xf0)  
159	22.067717	0x0000	0xb77a	ZigBee HA	50	ZCL Level Control: Unknown Command, Seq: 52
[https://github.com/Koenkk/zigbee2mqtt/issues/8575](url)
Help Wanted ?

**Comment by ferrarii1** [comment]
![IMG_20211127_072804_516](https://user-images.githubusercontent.com/90213726/143667984-2a3bf402-0c53-44c9-8361-4afe2be027ed.jpg)
the dimmer works in this model

**Comment by Koenkk** [comment]
@ferrarii1 So if I understand correctly test2 is enough to control the white channel? e.g.
- Device is in rgb mode
- send test 2
- rgb mode is now disabled, white activated
- white brightness can be controlled now with brightness slider
- to switch back to rgb mode simply set a color

**Comment by ferrarii1** [comment]
Yes that's right. I think that will be enough. 

but how can you solve the issue with color rendition?
when you turn on the red, pink is displayed on the LED strip. yellow with a tint of green.

**Comment by Koenkk** [comment]
@ferrarii1 could you provide me an aliexpress link where you bought the device? I believe it will be too hard to integrate this device without having it.

**Comment by bluefish007** [comment]
@Koenkk I ordered here aliexpress.com/item/1005001865233095.html

**Comment by pchrzaszczewski** [comment]
@Koenkk I ordered this one https://aliexpress.com/item/1005002554523847.html

**Comment by Koenkk** [comment]
thanks, ordered it.

**Comment by bluefish007** [comment]
@Koenkk Thanks for integrating the controller now. MANY THANKS

**Comment by peyvandcarsales** [comment]
Hello,
any updates on this issue? I also cannot set the white color

**Comment by Koenkk** [comment]
didn't receive it yet.

**Comment by uspass** [comment]
@Koenkk
Last week a ceiling lamp could be found at Lidl.
It reports being TS0504B.

Cheers

![20211219_203658](https://user-images.githubusercontent.com/42880649/146688364-d2a9d1c2-ed45-495b-b9b9-f00adf86b546.jpg)
s

**Comment by ferrarii1** [comment]
@uspass Hi, does it have a white temperature adjustable?

**Comment by uspass** [comment]
@ferrarii1 
Unfortunately no. 
Actually, on the box says 4000 K, 16 millions colours. 
From what I have checked ( I bought it just yesterday), with the last Koenkk external converter, it creates an entity in HA. If one chooses to set the entity in Lovelace, one gets the Brightness slider, the rainbow palette and an Effect drop down list.

![Untitled](https://user-images.githubusercontent.com/42880649/146802415-e1a9ecb6-729d-4b6a-82a5-df8c8deda6ea.png)

But one can choose to change the white color to something similar to, say, 2700 K.

**Comment by Koenkk** [comment]
Putting the following [file](https://gist.github.com/Koenkk/fbe399801fe098280d90a65709ef5c5a) under `data/TS0504B.js` and adding `external_converters: [TS0504B.js]` to the `configuration.yaml` will give you control of the white channel when sending to `zigbee2mqtt/MY_LIGHT/set` one of the following payloads:
1. `{"color":{"rgb":"255,255,255"}}`
1. `{"color":{"hex":"#FFFFFF"}}`
1. `{"color":{"x":0.3125, "y": 0.32894736842105265}}` this is the x/y value send by the zigbee2mqtt frontend when you select the white color
1. `{"color":{"x":0.323, "y": 0.329}}` this is the x/y value send by Home Assistant when you select the white color (middle of the color picker wheel)

Technical details:
While implementing this I had to make some choices on how to expose this. IMO there are 2 possibilities to implement white channel support for lights which can only be in 1 mode at a time (this is the first I've encountered so far), with both having its cons and pros:
1. Through color (like done now):
    - Pro: supported by Home Assistant (since Home Assistant doesn't support xy + white channel lights, only rgbw)
    - Pro: easier for the user
    - Con: gets messy when setting via x/y values (see magic values in payload 3 and 4 above)
2. Having a separate white color mode with a property `white` where the value represents the brightness of the white channel (e.g. `{"white: 50}`)
    - Pro: enabling the white channel gets explicit
    - Con: not supported by Home Assistant
    - Con: duplicate values in the payload, since in this case the value of `white` would always be identical to the `brightness` value
    - Con: requires more work to implement (changes to the frontend, Home Assistant integration and documentation generation)

**Comment by uspass** [comment]
> Putting the following [file](https://gist.github.com/Koenkk/fbe399801fe098280d90a65709ef5c5a) under `data/TS0504B.js` and adding `external_converters: [TS0504B.js]` to the `configuration.yaml` will give you control of the white channel when sending to `zigbee2mqtt/MY_LIGHT/set` one of the following payloads:
> 
>     1. `{"color":{"rgb":"255,255,255"}}`
> 
>     2. `{"color":{"hex":"#FFFFFF"}}`
> 
>     3. `{"color":{"x":0.3125, "y": 0.32894736842105265}}` this is the x/y value send by the zigbee2mqtt frontend when you select the white color
> 
>     4. `{"color":{"x":0.323, "y": 0.329}}` this is the x/y value send by Home Assistant when you select the white color (middle of the color picker wheel)
> 
> 
> Please let me know if it works for you, then I can add this directly to zigbee2mqtt.
> 

I confirm 1 to 4 working for Lidl's lamp modelID TS0504B, manufacturerName _TZ3210_sroezl0s.
Also in HA Lovelace rainbow chart, when middle point (white) is selected the lamp changes to full intensity white.

**Comment by Koenkk** [comment]
@uspass if effects don't work they are probably not supported by the device (at least not via the standard Zigbee way)

**Comment by MetanoKid** [comment]
Can confirm payloads work for manufacturer `_TZ3000_ukuvyhaa`. No effects either (surely not supported, as @Koenkk mentioned).
Thank you very much 👍

**Comment by Koenkk** [comment]
Thanks for confirming added this now

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by peysab** [comment]
Thanks for the effort @Koenkk 
I'm using Home Assistant and also using edge version, I did update but nothing changed for me, still not showing the white channel.
I uninstalled the edge version and reloaded the repo and installed again

**Comment by Koenkk** [comment]
@peysab white channel is not shown as something separate, it will be turned on when you click the center (white color) of the color wheel

**Comment by peysab** [comment]
@Koenkk , yes just noticed, thanks

**Comment by uspass** [comment]
please add support for _TZ3210_sroezl0s. It works.
Thanks.

**Comment by Koenkk** [comment]
@uspass  added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by osanchez21** [comment]
> @peysab white channel is not shown as something separate, it will be turned on when you click the center (white color) of the color wheel

Hello everyone. I tell you that the white channel was working perfectly in home assistant but I installed the latest z2m update and the white channel no longer works with the center of the color wheel in home assistant. I have looked at some configurations but I can only change the white channel in the expose tab of the device in z2m but in home assistant the white channel is not activated at all. Your help please and thank you very much in advance for the great effort.

**Comment by pchrzaszczewski** [comment]
I have the same problem as above after one of the zigbee2mqtt updates. I can only select the white color from the zigbee2mqtt GUI - When I set the white color on the HA color picker it sets the color incorrectly (sets the white color on the RGB lines, instead of the W lines).

**Comment by osanchez21** [comment]
> > @peysabel canal blanco no se muestra como algo separado, se encenderá cuando haga clic en el centro (color blanco) de la rueda de color
> 
> Hola a todos. Les cuento que el canal blanco andaba perfectamente en home Assistant pero instalé la última actualización de z2m y ya no funciona el canal blanco con el centro de la rueda de colores en home Assistant. He mirado algunas configuraciones, pero solo puedo cambiar el canal blanco en la pestaña de exposición del dispositivo en z2m, pero en el asistente doméstico, el canal blanco no está activado en absoluto. Su ayuda por favor y muchas gracias de antemano por el gran esfuerzo.

Hola @Koenkk  tu ayuda por favor en las actualizaciones recientes aun no se ha corregido este error por favor tu ayuda de antemano muchas gracias.

**Comment by LasseTheDude** [comment]
Did anyone fix this issue?
