### ISSUE TITLE
node.js died once a week node:7966 UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by brommetje** [Koenkk/zigbee2mqtt#6415]
pi@snoepie:~ $ sudo service zigbee2mqtt status
â zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-02-17 18:02:22 CET; 4 days ago
 Main PID: 7926 (node)
    Tasks: 23 (limit: 2182)
   CGroup: /system.slice/zigbee2mqtt.service
           ââ7926 npm
           ââ7965 sh -c node index.js
           ââ7966 node index.js

Feb 21 18:06:12 snoepie npm[7926]:     at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
Feb 21 18:06:12 snoepie npm[7926]:     at listOnTimeout (internal/timers.js:554:17)
Feb 21 18:06:12 snoepie npm[7926]:     at processTimers (internal/timers.js:497:7)
Feb 21 18:06:12 snoepie npm[7926]: (node:7966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wi
Feb 21 18:07:31 snoepie npm[7926]: Zigbee2MQTT:debug 2021-02-21 18:07:31: Saving state to file /opt/zigbee2mqtt/data/state.json
Feb 21 18:09:30 snoepie npm[7926]: (node:7966) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
Feb 21 18:09:30 snoepie npm[7926]:     at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
Feb 21 18:09:30 snoepie npm[7926]:     at listOnTimeout (internal/timers.js:554:17)
Feb 21 18:09:30 snoepie npm[7926]:     at processTimers (internal/timers.js:497:7)
Feb 21 18:09:30 snoepie npm[7926]: (node:7966) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wi

## What happened
Zigbee2mqtt not responding once a week, "service zigbee2mqtt restart" not working, after stop and start it runs for a few days. 

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC2652RB Sleash
Adapter firmware version: 20201026
node -v  : v12.20.1

**Comment by Koenkk** [comment]
Probably same as https://github.com/Koenkk/zigbee2mqtt/discussions/6019 . Latest firmware might fix it: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin
