### ISSUE TITLE
Request: MQTT - Homeassistant

### ISSUE THREAD

**Issue by forfrossen** [Koenkk/zigbee2mqtt#6423]
Would it be possible to populate z2m properties of devices via homeassistant? Values like "last_seen" and "enlapsed".

I tried auto discovery on openhab for a couple of contact sensors and realized they only have their 'exposes' properties.
In openhab you're not able manually edit auto-discovered things. So I could not get the values from above.

In the discord channel I was told to create an issue here asking for it to be implemented.

**Comment by RubenKelevra** [comment]
You can enable this in Home Assistant's integration of zigbee2mqtt:

![Screenshot_20210224_225149-1](https://user-images.githubusercontent.com/614929/109070717-22541b80-76f3-11eb-99cb-a411379e2562.png)

**Comment by forfrossen** [comment]
I'm afraid, I think that was misleading from my side. I already did that.
The MQTT topics exist and when I manually configure them in openhab everything works.
I was asking to get them to be auto-discovered. As far as I can see the channels are not added to the homeassistant config topics.

**Comment by RubenKelevra** [comment]
> I'm afraid, I think that was misleading from my side. I already did that.
> The MQTT topics exist and when I manually configure them in openhab everything works.
> I was asking to get them to be auto-discovered. As far as I can see the channels are not added to the homeassistant config topics.

Not sure what you're referring to, the timestamps are being displayed and can be used in HA:

![Screenshot_20210329_163217-1](https://user-images.githubusercontent.com/614929/112852672-706e8d00-90ac-11eb-8b3a-fef649f88528.png)
