### ISSUE TITLE
Ikea devices always reporting 60% battery

### ISSUE THREAD

**Issue by bummzulu** [Koenkk/zigbee2mqtt#6425]
# Bug Report
## What happened
I have 5 IKEA Tradfri E1525/E1745 presence sensors installed. This has been working fine now for many months. I noticed that all devices constantly report "battery: 60" although for 2 of them the battery has already been completely empty.

Example log entry
`info  2021-02-23 19:17:08: MQTT publish: topic 'zigbee2mqtt/Praesenz3', payload '{"battery":60,"linkquality":189,"occupancy":false,"update":{"state":"idle"},"update_available":false}'`

## What did you expect to happen
Battery information reflecting the actual state so I can replace the battery before the system stops working.

## How to reproduce it (minimal and precise)
Reading the battery information of IKEA Tradfri E1525/E1745

## Debug Info
Zigbee2MQTT version: 1.17.1
Adapter hardware: CC2652R
Adapter firmware version: 20200805

Is anybody else seeing similar issues?

**Comment by m0wlheld** [comment]
> Is anybody else seeing similar issues?

I have 3, 1 month old. They are currently reporting 60%, but they have been at 37% when it was cold. 

I don‘t think it‘s a reliable value.

**Comment by sjorge** [comment]
Mine fluctuate also, one of mine was < 10% and for a week but still worked and now its at 37% again. It's probably based on the battery's voltage which can fluctuate with temperature and such. I don't have an official gateway to compare if it also fluctuates there.

**Comment by bummzulu** [comment]
Thanks for your inputs. Mine always stays at 60 and it never fluctuated so far. What adapters do you use?

**Comment by sjorge** [comment]
I'm using a prototype stick that has a CC2652P on it.

**Comment by m0wlheld** [comment]
Raspee II

**Comment by pavax** [comment]
Hi there, I just started using Z2M a couple of days ago. 

![image](https://user-images.githubusercontent.com/5336841/108897882-d59b1280-7616-11eb-8ad3-305486be7534.png)

I did not yet replace a cr2032-battery yet, but I did charge the lithium battery of the KADRILJ roller blind (was < 20%) and it did go up to 100% and is now at 99%

Specs:
Zigbee2MQTT version: 1.17.1
Adapter hardware: Conbee II
Integration: Home Assistant Addon
Adapter firmware version: 0x26680700
