### ISSUE TITLE
CR Smart Home TS0207 won't complete interview - but work fine

### ISSUE THREAD

**Issue by RubenKelevra** [Koenkk/zigbee2mqtt#6442]
## What happened

I got a device that zigbee2mqtt identifies as `CR Smart Home TS0207` (water leak detector with a wired probe).

#### Pictures:
<details>

![853652296-455494282](https://user-images.githubusercontent.com/614929/109063004-ee73f880-76e8-11eb-99f0-38261e59482d.jpg)
![-761810031525319187](https://user-images.githubusercontent.com/614929/109063012-f03dbc00-76e8-11eb-8653-60322884d264.jpg)
![-1087850665-2043759634](https://user-images.githubusercontent.com/614929/109063068-00ee3200-76e9-11eb-946d-dc545ac3afa6.jpg)

</details>

I have already 32 other devices in my network, which work flawlessly. But this one gave me some trouble: While it works and sends sensor data via zigbee2mqtt to my Home Assistant it is still showing as `Interview completed: No`:

![Screenshot_20210224_214346-1](https://user-images.githubusercontent.com/614929/109063563-95589480-76e9-11eb-9406-515976822e7d.png)

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: Slaesh's CC2652RB stick
Adapter firmware version: ?

**Comment by Koenkk** [comment]
- Have you already tried force removing the device (click red bin icon -> force remove) and repair?
- Can you provide the herdsman debug log of failed pairing

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
