### ISSUE TITLE
TOGGLE command not working correctly on some wall switches without neutral (tested TS0011 / TS0013)

### ISSUE THREAD

**Issue by rsteininger** [Koenkk/zigbee2mqtt#6444]
I have a very strange phenomenon with one particular brand of wall switches without neutral (e.g. single gang TS0011 and tripple gang TS0013). I am using node red with mosquitto MQTT broker and the latest version of zigbee2mqtt (1.17.1). 
I can control these wall switches with on and off commands, no problem! However. When I use the "toggle" command, the zigbee gateway reports back, that the device has toggled but the power unit (the relay of the device) does NOT follow that state change! This works fine with other brand wall switches (e.g. the aqara ones QBKG04LM do not show such a problem). 

## What happened
mqtt command for on / off work as expected with the relay changing state. However, with toggle the zigbee gateway (?) reports back a change of state but the switch/relay does not! 

## What did you expect to happen
the power state of the switch / relay should toggle / change state with the "toggle" command

## How to reproduce it (minimal and precise)
Using node red v1.2.9, with both, the zigbee nodes (node-red-contrib-zigbee2mqtt), connected to a "toggle" inject node yields above result. Inject node with "on"  or "off" works fine.  
Same result by using a MQTT send node with "topic" configured to match switch. Once more, "on" / "off" works, but "toggle" does not change the power state of the relay / switch (only the mqtt state feedback makes it look it worked. 

## Debug info
Zigbee2MQTT version: 1.17.1
Adapter hardware: zStack3x0
Adapter firmware version: 20200925 (zigbee v3)

Happy to provide more information / test if I am told what or how! 

THANKS

**Comment by ndrewpj** [comment]
Have same issue with HA core-2021.9.7 Zigbee2mqtt v.1.21.2-1. Toggle is not switching ON/OFF modes.
```

 Received MQTT message on 'zigbee2mqtt/0x84fd27fffe6032f8/set' with data '{"state":"TOGGLE"}'
Debug Publishing 'set' 'state' to '0x84fd27fffe6032f8'
Debug Received Zigbee message from '0x84fd27fffe6032f8', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":1,"fn":0,"status":0,"transid":42}' from endpoint 1 with groupID 0
```
...and nothing happens.

How can I help with troubleshooting this? 

Regards,
Andy
