### ISSUE TITLE
OTA Updates for Aurora AOne Dimmer

### ISSUE THREAD

**Issue by jonbrunt123** [Koenkk/zigbee2mqtt#6448]
## Is your feature request related to a problem? Please describe

I use 2 Aurora AOne dimmer that support OTA updates. I have been discussing with the developers who have offered to provide the necessary support for Zigbee2MQQT to allow OTA updates.

## Describe the solution you'd like

Aurora devices support OTA updates.

**Comment by Koenkk** [comment]
Please post the OTA images here, then I can add them.

**Comment by proffalken** [comment]
@jb123567 - did you ever get a chance to connect Aurora with the z2m folks?

**Comment by jb123567** [comment]
No, annoyingly my contact seems to no longer work for them!

**Comment by tszyszko** [comment]
Wonder if anyone else has been able to get hold of these files, the 100% flicker bug is very annoying!
