### ISSUE TITLE
NEW Devicesupport! BHT-002-GALZBW (Water Floor Heating)

### ISSUE THREAD

**Issue by RBroks** [Koenkk/zigbee2mqtt#6461]
Hello!

Add please floor thermostat, it bean recognized as GCLZBW model, for gas boiler, help pls.

https://www.moeshouse.com/collections/zigbee-thermostat/products/white-zigbee-smart-thermostat-programmable-temperature-controller-zigbee-hub-required-for-water-floor-heating

Robert

**Comment by insipiens** [comment]
The gas boiler version also handles the other types as its just a change in which sensor it is set to use. The sensor selection can be changed via an MQTT message. The Z2M device page describes how to do that.

**Comment by insipiens** [comment]
I checked and the page now doesn't mention that you can set the source of the external temperature.

From the home assistant MQTT integrations you can publish a message to the topic with payload sensor = either 0,1,or 2 where they correspond to IN/AL/OU choices, or using any MQTT message utility.

My choice is internal so I published 0 to it:

![image](https://user-images.githubusercontent.com/68975498/110222031-63081d80-7ec7-11eb-8f3f-5fe4e4e5f6bb.png)

**Comment by RBroks** [comment]
Ou i will try it out!

**Comment by RBroks** [comment]
Is there any chance to get  reading in one message to get values of In (room sensor) and Ou (floor sensor)?
