### ISSUE TITLE
WXKG12LM battery drain very fast

### ISSUE THREAD

**Issue by nogueirasa** [Koenkk/zigbee2mqtt#6465]
Does anybody is having problem with WXKG12LM battery drain very fast? Change the battery almost 3 times and continuos drain in less than a week.

**Comment by passy05** [comment]
I have two of them and the battery is fine with them.

**Comment by nogueirasa** [comment]
> I have two of them and the battery is fine with them.

Thanks @passy05 , looks like a hardware problem
