### ISSUE TITLE
zigbee2mqtt docker container keeps alternating between ttyUSB0 and ttyUSB1

### ISSUE THREAD

**Issue by MarsWarrior** [Koenkk/zigbee2mqtt#6469]
# Bug Report
## What happened
On every reboot, the container alternates between ttyUSB0 and ttyUSB1 for the zigbee adapter.
This means I have to change the configuration.yaml file on every reboot of my little NUC server.

In the container definition, a /dev/serial/by-id device is mapped to ttyUSB0, but that seems to be ignored.

## What did you expect to happen
ttyUSB0 stays ttyUSB0.

## How to reproduce it (minimal and precise)
On reboot.

## Debug Info
Zigbee2MQTT version: 1.17.0, 1.17.1, 1.16.2
Adapter hardware: CC26X2R1
Adapter firmware version: One from 2020.

**Comment by m0wlheld** [comment]
Assignment of ttyUSBx is done on host-level, not inside the container. 

> In the container definition, a /dev/serial/by-id device is mapped to ttyUSB0, but that seems to be ignored.

Please show how you do this, I will try to help.

**Comment by lux73** [comment]
so why don't you use /dev/serial/by-id/[yourDevice] in your Config?
this prevents the anytime change between ttyUSB0 & ttyUSB1 on your Host...

**Comment by MarsWarrior** [comment]
The Portainer definition uses the following mapping:
![image](https://user-images.githubusercontent.com/1220775/109385239-ba6c2380-78f2-11eb-94c5-356083a2ce12.png)

I have changed the device now to ttyUSB3, as USB0 and USB1 are always present in the Alpine container. The Alpine container does not have a serial/by-id mapping.

The configuration.yaml also contains the port ttyUSB3 now.
```yaml
serial:
  port: /dev/ttyUSB3
  disable_led: false
  adapter: zstack
```

I must check if USB3 solves the problem. Using USB0 or USB1 had problems, as I had to change the port number in the configuration.yaml (the docker mapping remained the same?!?!?!?!?!) after EVERY reboot / restart of Docker.

**Comment by m0wlheld** [comment]
I makes absolutely no sense to change the serial path *inside* the container multiple times, if the serial path *outside* the container is stable. 

My recommendation is to map /dev/serial/... to `/dev/ttyACM0` and adjust the serial port in configuration.yaml for the last time.

**Comment by MarsWarrior** [comment]
I will try that.

The weird thing is, is that I'm also using zwave2mqtt, ie another usb stick - also using the by-id mapping, and that that container has never had any problems after a reboot or upgrade of docker under Ubuntu 20.04 LTS.

**Comment by m0wlheld** [comment]
> So it might be caused - in my case - by the different container image.

Maybe. But /dev/ttyACM0 seems safe for both.

**Comment by MarsWarrior** [comment]
Indeed!

Will report back if I have done some testing...

**Comment by luismalddonado** [comment]
> # Bug Report
> ## What happened
> On every reboot, the container alternates between ttyUSB0 and ttyUSB1 for the zigbee adapter.
> This means I have to change the configuration.yaml file on every reboot of my little NUC server.
> 
> In the container definition, a /dev/serial/by-id device is mapped to ttyUSB0, but that seems to be ignored.
> 
> ## What did you expect to happen
> ttyUSB0 stays ttyUSB0.
> 
> ## How to reproduce it (minimal and precise)
> On reboot.
> 
> ## Debug Info
> Zigbee2MQTT version: 1.17.0, 1.17.1, 1.16.2
> Adapter hardware: CC26X2R1
> Adapter firmware version: One from 2020.

I had similar problems; finally I had to bind the USB devices to static names and then use those names for the binding
https://www.domoticz.com/wiki/PersistentUSBDevices

**Comment by MarsWarrior** [comment]
Well, by using an undefined USB number - USB3 in my case - the problem is solved. I can reboot my NUC without problems: zigbee2mqtt can find the stick!
