### ISSUE TITLE
Unbind Error

### ISSUE THREAD

**Issue by srtxema** [Koenkk/zigbee2mqtt#6477]
I have a conbee2 coordinator with a lot of device.
i have 2 Xiamit switch https://www.zigbee2mqtt.io/devices/WXCJKG12LM.html#xiaomi-wxcjkg12lm connect with a shelly roller and in the kitchen 2 https://www.zigbee2mqtt.io/devices/TS0121_plug.html#tuya-ts0121_plug
buttons and switch are not connected but from last week when i down roller the tuya switch is on and when i up is off

i have looking for information and i have found bind option.
in web interface i see it

Tuya Bind
![image](https://user-images.githubusercontent.com/18092080/109390733-a5ec5300-7913-11eb-985e-b55021f6c005.png)

Button Bind
![image](https://user-images.githubusercontent.com/18092080/109390722-94a34680-7913-11eb-9ac3-7a7acd165fc8.png)

i havent connected it but it is like this

i have try to unbind pressing heart broken button but it show error

![image](https://user-images.githubusercontent.com/18092080/109390710-8523fd80-7913-11eb-86c5-d1eaf14cb5aa.png)

![image](https://user-images.githubusercontent.com/18092080/109390680-632a7b00-7913-11eb-90ca-f7ba138689ca.png)

any help please?
i want that both devices will be unbind
Thanks!

**Comment by sjorge** [comment]
You might need to press a button on the device immediately after hitting the bind/unbind button. If it is sleeping you get a timeout like shown above.

**Comment by srtxema** [comment]
it´s with reset button affet unbind! thanks!!
