### ISSUE TITLE
Email battery warning

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#6479]
## Is your feature request related to a problem? Please describe
I'm always frustrated when our Zigbee devices fail with dead batteries.

## Describe the solution you'd like

1. Add configuration options for SMTP-server
 - hostname
-  port
-  encryption TLS/SSL
-  sender email address
-  recipient email address

2. Send battery warnings when Zigbee devices reach critical battery level

## Describe alternatives you've considered
Checking zigbee battery status regularly -> wastes time and gets forgotten :-(

**Comment by Koenkk** [comment]
This is out of scope for Zigbee2MQTT, use e.g. node red or home assistant for this.
