### ISSUE TITLE
How to view my current pan_id & channel?

### ISSUE THREAD

**Issue by quarcko** [Koenkk/zigbee2mqtt#650]
Just a question for devs:

I started my journey with this module on all default settings,
did not specified any 'advanced' options, and really don't see any need now, but...

i saw some posts where people mention that USB CC dongle sometimes (power cycle?)
looses and refuses to reuse pan id?? it is my worst nightmare now, 
especially since pairing each Xiaomi device takes like 20-30 tries (for EACH device!!).

So... i want to know, how can i view my current pan_id and channel, just to write it down
somewhere, and in case of emergency i could reuse it in 'advanced' configuration...
Thanks! :)

**Comment by h4nc** [comment]
@Koekk does everyone get the same panID with the standard config? 
Would you recommend changing the panID.

I have to re-pair my devices because I changed my network key. If it's more secure to change the panID, it would be better to know that before re-pairing all devices.

**Comment by Koenkk** [comment]
@h4nc yes, by default `0x162a`. Using the same panID isn't less secure, it's used to operate multiple zigbee networks on the same channel.

**Comment by h4nc** [comment]
Thats weird I didn't change something at the panID and I don't habe `0x162a`.

I got `0x1a63`. Should I change it to `0x162a`.

**Comment by Koenkk** [comment]
When a panID is already occupied a new one will be picked (this cannot be forced, it's part of the zigbee stack on the CC2531).

**Comment by h4nc** [comment]
Ok I updated my coordinator some days ago, so this explains why it went from`0x1a62` too `0x1a63`.

But above you mentioned `0x162a` as default. docs say `0x1a62`. Only the letter a is at an other place. Perhaps a typing mistake?

**Comment by Koenkk** [comment]
sorry, yes that was a typo

**Comment by h4nc** [comment]
Ok, thanks. So my last question on this one, as I'm still not sure about that.

Should I change it back to `0x1a62` from `0x1a63`?

And from your information above it is not a security risk, that I published my `panID` here, right?
Security is what the `network_key` provides, right?

Just want to know all of that before I re-pair all those devices. Hopefully the last time for a while.

**Comment by Koenkk** [comment]
Changing the panid requires repairing of devices.

You can view panID as something similar to the channel, it's just a configuration setup and has nothing to do with security.

`network_key` is what provides the security indeed.

**Comment by h4nc** [comment]
@Koenkk Thanks for your patiency and clearing that up for me. 

By the way (don't want to open an issue for that): Is there a way to reset the cc2530 router to re-pair it? Or do I have to reflash the device to get it connected again?

**Comment by Koenkk** [comment]
@h4nc you have to reflash it.

**Comment by h4nc** [comment]
I suspected that. Thanks

**Comment by emc02** [comment]
is it possible to make the Pan ID static and to get perfect clones? I would need that for a big project to pair devices once and use them on differnet places but with same networks without repairing them. Thanks!
