### ISSUE TITLE
QS-Zigbee-D02-TRIAC-L

### ISSUE THREAD

**Issue by Ne0k** [Koenkk/zigbee2mqtt#6512]
## What happened
If the QS-Zigbee-D02-TRIAC-L is off, and I change the dimmer level to 75% in Domoticz the device doesn't go on.
I see in the Zibee2MQTT plugin that the devices is switched on, but in real life the device is still off.
Even if I create a group in domoticz and set the level on 75% the device doesn't go on.

I think is a bug, because it's working with the HGZB-04D and the QS-Zigbee-D02-TRIAC-2C-LN.

## Debug info
Zigbee2MQTT version: v.1.18.0 (zStack3x0 20210120)
Adapter hardware: CC2652
Adapter firmware version: CC26X2R1_20201026.hex

**Comment by dariusz-goc** [comment]
I have the same issue
