### ISSUE TITLE
TS0012 marked as battery device

### ISSUE THREAD

**Issue by Mr-Groch** [Koenkk/zigbee2mqtt#6520]
## What happened
TS0012 is marked as battery device:

![image](https://user-images.githubusercontent.com/20594810/109610410-00acc700-7b2d-11eb-9f8a-5ed90b828bb5.png)

## What did you expect to happen
It should be marked as AC powered device like TS0011 #6190 

## Debug info
Zigbee2MQTT version: 1.18.0
Adapter hardware: CC26X2R1 zzh
Adapter firmware version: ..

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
