### ISSUE TITLE
Sonoff SNZB-01 no long click

### ISSUE THREAD

**Issue by MarkStephan89** [Koenkk/zigbee2mqtt#6538]
Hi, 
I use iobroker with the zigbee adapter. 
The Sonoff SNZB-01 (https://www.zigbee2mqtt.io/devices/SNZB-01.html) is paired and single click and double click is working.

But the long click do not work. 

Does anyboby have the same problem?

## Debug info
Zigbee2MQTT version:
Adapter CC26X2R1
Adapter firmware version:

thank you for the great work!

**Comment by Koenkk** [comment]
Please create iobroker zigbee issues here: https://github.com/ioBroker/ioBroker.zigbee/issues
