### ISSUE TITLE
Color Wheel not working properly

### ISSUE THREAD

**Issue by T-IOOO** [Koenkk/zigbee2mqtt#6540]
When adjusting the temperature wheel to cold in homekit, the dot will jump to another position upon release.
It's as if only 1/4 of the wheel is working, a very narrow adjustment around the warm area of the wheel.
When I adjust the temperature value and at the same time looking at the log, the temp value reaches 250 on the warmer area of the wheel and the rest 3/4 of the temp. wheel is only staying at 250
I have only tested with IKEA light bulbs

## Debug info
Zigbee2MQTT version: 1.18.1
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by sjorge** [comment]
Trådfri WS bulbs have a minColorTemp of 250 mireds and a maxColorTemp of 454 mireds.

They can't output color temp outside this range.

**Comment by T-IOOO** [comment]
I am aware of that, but the temperature wheel is not working as it should. It was working just fine before the two latest updates.
See the areas in the image. The red area is the only area that is chaning the values
![issue](https://user-images.githubusercontent.com/59575587/109820223-19080900-7c35-11eb-8bef-4e348f7511eb.jpg)

**Comment by sjorge** [comment]
The blue area you marked sends values < 250 for me, so it makes sense that they are not making the light cooler.

**Comment by T-IOOO** [comment]
The values were spread evenly from cold to warm before.
If I lift my finger anywhere in the blue area the marker will snap back to the area where the red/blue meet.
It's not supposed to act like that and hasn't before.

**Comment by sjorge** [comment]
I did some more digging, looks hass.io is not passing the minValue and maxValue correctly to homekit.
![IMG_6A2EF4F19FED-1](https://user-images.githubusercontent.com/379665/109823379-2bd00d00-7c38-11eb-84a8-ba976c415572.jpeg)

When maxValue=454 and minValue=250 is passed, the color temperature picker looks slightly different, but now the coolest spot returns 250 and the warmest returns 454

**Comment by T-IOOO** [comment]
my temperature picker is not changing like that.
Did the marker "snap" to that position?

**Comment by sjorge** [comment]
On 2021-03-03 15:58, T-IOOO wrote:

> my temperature picker is not changing like that.
> Did the marker "snap" to that position?
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

When the range is properly passed to homekit, it does not snap. Because 
all positions on the wheel will are within range of the bulb.

Not sure if the issue is how z2m passes the info to hass.io or how 
hass.io passes it to homekit.

-- 
~ sjorge

Links:
------
[1] 
https://github.com/Koenkk/zigbee2mqtt/issues/6540#issuecomment-789774509
[2]

**Comment by sjorge** [comment]
https://github.com/Koenkk/zigbee2mqtt/blob/a43d1f3917fee5516429bf1bf80419f1d2e0e7f8/lib/extension/homeassistant.js#L103-L106

Looks like z2m is passing it to ha, I guess ha is ignoring those then or not passing them to homekit.

**Comment by sjorge** [comment]
ha is also hardcoding it, https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_lights.py#L88-L93 should probably use the discovery_payload values if available.

**Comment by T-IOOO** [comment]
Maybe I should mention that I am using Homebridge and not Home Assistant

**Comment by sjorge** [comment]
Which plugin? It's probably the same issue of it not setting min/max for homekit.

**Comment by T-IOOO** [comment]
”Homebridge Zigbee2MQTT”

**Comment by T-IOOO** [comment]
Someone who's willing or able to fix this issue? 😊

**Comment by sjorge** [comment]
It’s not a z2m issue, I believe it was properly fixed in https://github.com/itavero/homebridge-z2m 

However there is a non finished discussion on the correctness of the fix in the issue there https://github.com/itavero/homebridge-z2m/issues/88 I mention I no longer have a gateway from ikea to verify if the behavior is the same or not. If it is indeed not that same a form of mapping should be done at the home ridge side.
