### ISSUE TITLE
GIRIER - MODEL: JR-ZDS01

### ISSUE THREAD

**Issue by Miguelin96** [Koenkk/zigbee2mqtt#6541]
## Information about the device + link

GIRIER - MODEL: JR-ZDS01

https://es.aliexpress.com/item/1005002180575797.html?spm=a2g0o.productlist.0.0.6a05614elhjdox&algo_pvid=3e169af9-fc88-4544-b55e-4f4899312d6e&algo_expid=3e169af9-fc88-4544-b55e-4f4899312d6e-3&btsid=0b0a119a16147750602321149e5d9f&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

## data/database.db entry of the device
..

**Comment by mrIngrid** [comment]
Hello, i have the same device. Works well, but have a little issue on model and pic. This is my situation.
![Hf5848bf343c74b24bcb3e6bec7cb4c1bh jpg_q50](https://user-images.githubusercontent.com/38946221/111391773-9318a300-86b5-11eb-8bd9-45f21f5bda89.jpg)
![Screenshot_20210317-001031](https://user-images.githubusercontent.com/38946221/111391791-9b70de00-86b5-11eb-914d-7f17f6c31e08.jpg)
