### ISSUE TITLE
Supported device is "not supported"

### ISSUE THREAD

**Issue by Alexalex89** [Koenkk/zigbee2mqtt#655]
Hello,

I just paired one Gledopto 'GL-C-008' and get the message "Device with modelID 'GL-C-008' is not supported." though it is listed as supported device here: https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices
I'm running the latest master version.

Here is my log: https://hastebin.com/weratudoji.js

Do you have an idea why it fails?

Thanks in advance!
Alex

**Comment by Koenkk** [comment]
Can you provide the contents of your `database.db`?

**Comment by Alexalex89** [comment]
Sure! Just the part regarding the Gledopto. If you need the full db, let me know!
https://hastebin.com/abexejuqiy.json

**Comment by Alexalex89** [comment]
That did the trick. Thanks!
Now I just need to figure out which JSON to use...

**Comment by Koenkk** [comment]
@davekr8  are you on the dev branch?
