### ISSUE TITLE
Get information from state.json

### ISSUE THREAD

**Issue by fennec622** [Koenkk/zigbee2mqtt#6561]
Hi

fonction get is not implement for all devices so very long time to have value like temperature 

So is it possible to get last information from state.json ?

Example with mqttthing

"startPub": {
                "zigbee2mqtt/temperaturekitchen/state/get": ""
            }
return immedialtly last values

thanks

**Comment by Koenkk** [comment]
The MQTT way to do is is to set `retain: true` for this device. In this way you will always get the latest state when subscribing to `zigbee2mqtt/temperaturekitchen`

- https://www.zigbee2mqtt.io/information/configuration.html#all-devices
- https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/
