### ISSUE TITLE
Impossible to disable file log output

### ISSUE THREAD

**Issue by foxylion** [Koenkk/zigbee2mqtt#6569]
## What happened

I tried to disable the file log, because I'm using the console output that is persisted in "docker logs".

```
log_output:
  - console
```

When I restart zigbee2mqtt a new logfile is still created and the log is still written to the file.

## What did you expect to happen

No logfile created, only log output to the console.

## How to reproduce it (minimal and precise)

Start zigbee2mqtt with a configuration file containing only the following:

```
log_output:
  - console
```

## Debug info
Zigbee2MQTT version: docker (koenkk/zigbee2mqtt:1.18.1)
Adapter hardware: CC2652RB
Adapter firmware version: unknown

**Comment by juslex** [comment]
Same here

**Comment by foxylion** [comment]
Okay, I reviewed the source code (and the documentation).
The configuration needs to be under

```
advanced:
  log_output:
    - console
```
