### ISSUE TITLE
[Docs] AC03647 not supporting float transition

### ISSUE THREAD

**Issue by ai-xyz** [Koenkk/zigbee2mqtt#6574]
## What happened
Tried to use the transition command for AC03647 in device settings or as MQTT command with float value.
Every float value gets somehow ignored and is evaluated as 1 second (manually time counting).
Integer values are working fine as expected.

## What did you expect to happen
I expected float values to work according to the docs, but seems like they are not supported.

## How to reproduce it (minimal and precise)
```
mosquitto_pub -h localhost -t 'zigbee2mqtt/arbeitszimmer/set' -m '{"brightness":254,"state":"OFF", "transition":"10"}'
mosquitto_pub -h localhost -t 'zigbee2mqtt/arbeitszimmer/set' -m '{"brightness":254,"state":"ON", "transition":"10"}'
```
works as expected and takes 10 seconds each command while
```
mosquitto_pub -h localhost -t 'zigbee2mqtt/arbeitszimmer/set' -m '{"brightness":254,"state":"OFF", "transition":"10.1"}'
mosquitto_pub -h localhost -t 'zigbee2mqtt/arbeitszimmer/set' -m '{"brightness":254,"state":"ON", "transition":"10.1"}'
```
takes approx. 1 second

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC26X2R1
Adapter firmware version:20210120

I assume the AC03647 just does not support float values so we should update the docs.
I am using the AC03647 version mit bajonett connection.

**Comment by Koenkk** [comment]
Seems bulb's don't support it indeed. Please create a PR to update the docs.
