### ISSUE TITLE
Firmware version not updated after device OTA update (Legrand)

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#6579]
## What happened
I'm trying to add Legrand devices OTA support.
However, after upgrading a device, the "firmware version" showed in the OTA tab in the GUI is not updated.
The device is properly updated, as when I try to check for new firmware, it returns the proper version, but even after a few reboots and turning off phisically the devices, they don't change at all.

## What did you expect to happen
Change to update the new firmware version.

## Debug info
Zigbee2MQTT version: 1.18.1
Adapter hardware: CC26X2R1

**Comment by Koenkk** [comment]
> The device is properly updated,

How you do you know this?

**Comment by jd1900** [comment]
> > The device is properly updated,
> 
> How you do you know this?

Because it has new functionallity from the update. 
And when changed to the original gateway, it says it is updated.

**Comment by Koenkk** [comment]
After removing and repairing, does the new version show up? If not they probably didn't updated the firmware version in the fw. (which can happen since this is not used to determine if a newer fw version is available)

**Comment by jd1900** [comment]
Yes, it does.

But in the test I have repaired in the official gateway, so it was not a perfect test.
