### ISSUE TITLE
No longer getting any response from Sengled Element bulbs.

### ISSUE THREAD

**Issue by dmwyatt** [Koenkk/zigbee2mqtt#658]
Check out the debug log here: http://termbin.com/p6aw

Right at the end you can see zigbee2mqtt receiving `set` messages but it doesn't do anything with them.  

These worked in the past, but I'm not sure if they stopped working after some update to zigbee2mqtt or not.

**Comment by Koenkk** [comment]
Do they work when running the release version (non-dev branch)?

**Comment by dmwyatt** [comment]
I kept my data directory and moved to the release version and it's the same problem.

**Comment by dmwyatt** [comment]
Should I try with a fresh data directory?

**Comment by Koenkk** [comment]
Do they work again when repairing?

**Comment by dmwyatt** [comment]
No.

**Comment by Koenkk** [comment]
After updating, did you do a

```
rm -rf node_modules
npm i
```

**Comment by dmwyatt** [comment]
Well the thing you're not considering is that I'm a huge dummy and I forgot to do that.

After wiping node_modules and doing an `npm i` the latest release version is back to working.  

I'm heading out on vacation shortly but I'll add a reminder to my calendar for when I get back to switch back to the latest version from the repo and double check that things are or are not working there.
