### ISSUE TITLE
Support for Philips Hue Fugato - White and Color - 4-spots 5063431P7

### ISSUE THREAD

**Issue by Ruftie** [Koenkk/zigbee2mqtt#6584]
Please support for Philips Hue Fugato  - White and Color - 4-spots 5063431P7 the 5063331P7 is supported the (3 spots version) but he 4 spots version isn't.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?
