### ISSUE TITLE
zigbee2mqtt stopped working after updated to HA 2021.3.1

### ISSUE THREAD

**Issue by waternsw-chrischen** [Koenkk/zigbee2mqtt#6588]
## What happened
Previously connected devices stopped response and cannot control. Temperature and binary sensors do not update.
The update also brought the supervisor version 2021.03.4. I cannot downgrade the version of supervisor to 2021.02.x
## What did you expect to happen
Connected devices reporting their states and being controlled through mqtt 
## How to reproduce it (minimal and precise)
Since the update, it does not work anymore.
## Debug info
Zigbee2MQTT version:1.17.1-1

debug info only listed all devices and the previous mqtt massage. No further information posted.

**Comment by ced1442** [comment]
Same for me, but I'm not sure it come from zigbee2mqtt because logs are ok. The communication with my devices is ok.

**Comment by m0wlheld** [comment]
HA Container 2021.3.1 works with 1.18.1. This is not a Zigbee2mqtt issue.

**Comment by juslex** [comment]
Mosquitto 5.1.1 have a bug. Check it.

**Comment by christoph-luebbe** [comment]
Yes this is the same with Zwave2mqtt and the newer ZwaveJS2mqtt. They all suffer from mosquitto 5.1.1
