### ISSUE TITLE
No battery info to fronted

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#6593]
Hello,

Why in Fronted power is "?" while the battery information is sent, on my Xiaomi Temperature AQARA 👍 
![1](https://user-images.githubusercontent.com/55591810/110200186-f48e7580-7e5c-11eb-9899-6ea49af614da.jpg)
![2](https://user-images.githubusercontent.com/55591810/110200188-f6583900-7e5c-11eb-8c2f-704cef34fa94.jpg)
![3](https://user-images.githubusercontent.com/55591810/110200281-68c91900-7e5d-11eb-87a7-6d7bc20164a2.jpg)

Thanks

## Debug Info
Zigbee2MQTT version: 1.18.1 (master)
Adapter hardware: Conbee 2

**Comment by Koenkk** [comment]
Fixed. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
