### ISSUE TITLE
Timeline for next rls ? Osram plug and Ikea e27 crasches!

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#660]
Hey ,
I have big troubles with my routers osram plug an also Ikea e27 i cant use them , this worked on 0.18, it might be the extra device information. Please help me out with that rows that have been change so i can change on mine 0.20 .
 I already using the newest zigbee-shepherd-converters from devbranch.
Thank you in advance.

**Comment by Koenkk** [comment]
Until the next version is released, you can use the dev branch.

**Comment by JLFN** [comment]
@Koenkk  Cant i make this False ? 
```.js 
        if (appSettings.mqtt.include_device_information) {
            messagePayload.device = this.getDeviceInfoForMqtt(device);
        }

        this.mqtt.publish(friendlyName, JSON.stringify(messagePayload), options);
    }
```
