### ISSUE TITLE
IKEA Tradfri Devices can't be paired and breaks pairing all (also non-IKEA) Devices

### ISSUE THREAD

**Issue by drdownload** [Koenkk/zigbee2mqtt#6618]
I run zigbee2mqtt as home-assistant addon, till now it works quite well, build a network with some devices at 3 locations. Right now I use the CC2501 flashed with 3.0 coordinator firmware (latest).

I bought some IKEA remotes and lights (well because I went to IKEA to buy some other stuff and quick checked if supported by zigbee2mqtt)

Tried to add 2 different IKEA remotes and nothing happens no matter how close I bring the remote to the coordinator.

Funny thing: since I tried to add the IKEA remote also I cant add other devices like Xiaomi TH sensors that worked in another network.

**Comment by mad2xlc** [comment]
Same here with a conbee2. already paired devices from IKEA do not send their status and also no pairing ist possible.
On a Osram E14 light i have the same problem
