### ISSUE TITLE
Firmware CC1352P2_CC2652P_launchpad_router_20210128 does not work on LAUNCHXL-­CC1352P-­2

### ISSUE THREAD

**Issue by maichai** [Koenkk/zigbee2mqtt#6635]
## What happened

The last working firmware on my LAUNCHXL-­CC1352P-­2 was CC1352P_2_20191106.hex

I updated the uniflash app on my macOS machine to 6.0.0. To be able to erase the flash the launchpad needed an automated firmware upgrade was done on the launchpad.Flash erase was successful. Writing CC1352P2_CC2652P_launchpad_router_20210128.hex was also successful according to uniflash, the verification was successful.

When connecting to the server, the launchpad used a slightly different device name, which I adapted accordingly for the docker container.

When starting the container, the connection to the launchpad fails: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

I already tried re-attaching the launchpad to powercycle it, which did not help.

What has gone wrong, how to fix?

For now I have put CC1352P_2_20191106.hex pack on the launchpad, and the connect to this old version does work. So it is not a problem with the internal upgrade of the launchpad, it must be a problem with the CC1352P2_CC2652P_launchpad_router_20210128 firmware?

## Debug info
Zigbee2MQTT version: 1.18.1 (commit #a43d1f3)
Adapter hardware: launchpad CC1352P-2
Adapter firmware version: CC1352P2_CC2652P_launchpad_router_20210128.hex

**Comment by Koenkk** [comment]
To be used with Zigbee2MQTT you need to flash the coordinator firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

You now used the router firmware, see https://www.zigbee2mqtt.io/information/zigbee_network.html on what the differences are.
