### ISSUE TITLE
Is there a way to pair device using the ID number?

### ISSUE THREAD

**Issue by jobabi** [Koenkk/zigbee2mqtt#6642]
I had to reinstalll zigbee2mqtt because the devices had a large delay and few devices were not reacting. Now, I have the problem that few device are hard to reach for a repair (it is inside a church)
I still have the old files of the data folder (configuration.yaml, etc ). I tried to copy these files into the folder of the new installed zigbee2mqtt, which was not working .......
Is there a way to enter the ID of the device (in configuration.yaml, ...) to pair them to the network (without physical access to the device) ?

**Comment by Koenkk** [comment]
No, you need to factory reset a device to put it in pairing mode. (joining is something requested from the device, not the coordinator).
