### ISSUE TITLE
SR-ZG9100A-S shows up as unsupported device even though it is supported.

### ISSUE THREAD

**Issue by frso80** [Koenkk/zigbee2mqtt#6644]
## What happened
When I'm adding an SR-ZG9100A-S it gets added as unsupported device even though it is supported. It identifies as 0x60a423fffebcedc9 (friendly name and IEEE address) and Model: HK-SL-RELAY-A
## What did you expect to happen
That it would identify as a SR-ZG9100A-S and that it should work.
## How to reproduce it (minimal and precise)
Push permit join all in Zigbee2MQTT and the push the reset button 5 times on the SR-ZG9100A-S to reset it and for it to join.
## Debug info
Zigbee2MQTT version:
Adapter hardware: zzh! CC2652R
Adapter firmware version: 20210120

Some of the log from herdsman debug:
https://pastebin.com/EfXym9bf

**Comment by Koenkk** [comment]
Looks like your device has a slightly different modelID, try following https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Probably you can just add the model to: https://github.com/Koenkk/zigbee-herdsman-converters/blob/dea9058af3b8ba44d04eff81f278d3fca3d30be7/devices.js#L11969
