### ISSUE TITLE
Ghost device joining? 0x0000000000000000

### ISSUE THREAD

**Issue by jd1900** [Koenkk/zigbee2mqtt#6661]
I'm seeing something like this:
![image](https://user-images.githubusercontent.com/63632981/110745472-9afec000-823b-11eb-8d18-b5945f301ae9.png)

From time to time, despite having joining disabled.

I force remove it, and disable joining again, but after a few hours or days a new ghost device appears again. The "(0xC3C2)" part after the "0x0000000000000000" part changes. The 0x0000000000000000 remains the same.

## Debug info
Zigbee2MQTT version: 1.18.1-1 
Adapter hardware: zzh
Adapter firmware version: CC2652R_coordinator_20210120

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of when  this device pairs?

See https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by jd1900** [comment]
I've added it.
But I'll be quite difficult to find it, as it is not anything that appears all the time.
And if the log disappears...

**Comment by jd1900** [comment]
I haven't been able to collect the logs before the dissapear. 

For instance right now I have this:
![image](https://user-images.githubusercontent.com/63632981/114346276-7b70f500-9b63-11eb-8c00-278accefbf97.png)
