### ISSUE TITLE
Please add device - Hue Fair (4034030P6)

### ISSUE THREAD

**Issue by forfrossen** [Koenkk/zigbee2mqtt#6666]
Hi,

i recently purchased a Hue Fair, as it was listed as a supported device in here but it turned out to be a slightly different model.

The specs and functions are all the same like the model: 4034031P6

My model is a: 4034030P6

Please clone 4034031P6 for model 4034030P6.

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
