### ISSUE TITLE
Xiaomi GZCGQ01LM not support ?

### ISSUE THREAD

**Issue by inhibitz** [Koenkk/zigbee2mqtt#6678]
the documentation says that there is support. but oh it doesn't work for me. 

1. Zigbbe USB Stick 
2. zigbee2mqtt v1.8.1

Mar 12 20:40:10 ihome npm[2112]: Zigbee2MQTT:warn  2021-03-12 20:40:10: Device '0x04cf8cdf3c7ca4f7' left the network
Mar 12 20:40:10 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:10: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"iee             e_address":"0x04cf8cdf3c7ca4f7"},"type":"device_leave"}'
Mar 12 20:40:10 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"lef             t_network","meta":{"friendly_name":"0x04cf8cdf3c7ca4f7"},"type":"device_removed"}'
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: Device '0x04cf8cdf3c7ca4f7' joined
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"fri             endly_name":"0x04cf8cdf3c7ca4f7","ieee_address":"0x04cf8cdf3c7ca4f7"},"type":"device_joined"}'
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: Starting interview of '0x04cf8cdf3c7ca4f7'
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"fri             endly_name":"0x04cf8cdf3c7ca4f7","ieee_address":"0x04cf8cdf3c7ca4f7","status":"started"},"type":"device_interview"}'
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"fr             iendly_name":"0x04cf8cdf3c7ca4f7"},"type":"device_connected"}'
Mar 12 20:40:28 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"int             erview_started","meta":{"friendly_name":"0x04cf8cdf3c7ca4f7"},"type":"pairing"}'
Mar 12 20:40:29 ihome npm[2112]: Zigbee2MQTT:debug 2021-03-12 20:40:29: Device '0x04cf8cdf3c7ca4f7' announced itself
Mar 12 20:40:29 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:29: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"fri             endly_name":"0x04cf8cdf3c7ca4f7","ieee_address":"0x04cf8cdf3c7ca4f7"},"type":"device_announce"}'
Mar 12 20:40:29 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"ann             ounce","meta":{"friendly_name":"0x04cf8cdf3c7ca4f7"},"type":"device_announced"}'
Mar 12 20:40:49 ihome npm[2112]: Zigbee2MQTT:error 2021-03-12 20:40:49: Failed to interview '0x04cf8cdf3c7ca4f7', device has not successfully been paired
Mar 12 20:40:49 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:49: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x04cf8cdf3c7ca4f7","ieee_address":"0x04cf8cdf3c7ca4f7","status":"failed"},"type":"device_interview"}'
Mar 12 20:40:49 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:40:49: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x04cf8cdf3c7ca4f7"},"type":"pairing"}'
Mar 12 20:41:56 ihome npm[2112]: Zigbee2MQTT:warn  2021-03-12 20:41:56: Device '0x04cf8cdf3c7ca4f7' left the network
Mar 12 20:41:56 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:41:56: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"ieee_address":"0x04cf8cdf3c7ca4f7"},"type":"device_leave"}'
Mar 12 20:41:56 ihome npm[2112]: Zigbee2MQTT:info  2021-03-12 20:41:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x04cf8cdf3c7ca4f7"},"type":"device_removed"}'

**Comment by tpftpf** [comment]
I can confirm that this device is supported and works just fine.
