### ISSUE TITLE
Z2M does not start with latest DEV

### ISSUE THREAD

**Issue by ALaDoffe** [Koenkk/zigbee2mqtt#6691]
## What happened
Just updated to latest dev commit 036aab2e2ec6a250460950663405bbd544ec28b1
Z2M does not start anymore with errors

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY

Refusing to start because configuration is not valid, found the following errors:
- devices['0x001788010446ae58']['retrieve_state'] should be string
- devices['0x00158d0004484817']['occupancy_timeout'] should be string
- devices['0x00158d0004484817']['homeassistant'] should be string
- devices['0x01124b001baff38b']['homeassistant'] should be string
- devices['0x00158d00042abfe9']['homeassistant'] should be string
- devices['0x00158d0004100531']['occupancy_timeout'] should be string
- devices['0x00158d0004100531']['homeassistant'] should be string
- devices['0x01124b001bb00e16']['homeassistant'] should be string
- devices['0x0017880104c0b0aa']['retrieve_state'] should be string
- devices['0x01124b001bb00844']['homeassistant'] should be string
- devices['0x00124b001bafeceb']['homeassistant'] should be string
- devices['0x00124b001bafeceb']['legacy'] should be string
- devices['0x00124b001bb0054d']['homeassistant'] should be string
- devices['0x00124b001bb0054d']['legacy'] should be string

If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

## What did you expect to happen
Start normally

## How to reproduce it (minimal and precise)
Update to latest dev 

## Debug info
Zigbee2MQTT version: latest-dev
Adapter hardware: CC2531
Adapter firmware version: latest

**Comment by nurikk** [comment]
Fixed this

**Comment by ALaDoffe** [comment]
Fixed indeed.

Thank you very much for your great job.
