### ISSUE TITLE
Expose switch as light

### ISSUE THREAD

**Issue by biau** [Koenkk/zigbee2mqtt#6697]
## Is your feature request related to a problem? Please describe
I'm using z2m with hass and installing zigbee switch micro modules behind my house wall switch.
If te module is a dimmer then z2m expose the endpoints as lights.
If the module is a simple switch, entity is a switch and is not displayed as a light in hass.

## Describe the solution you'd like
Having the opportunity to tell z2m to expose the switch endpoint as light

## Additional context
Actually I'm using the light switch platform in hass but choosing the type in hass like we can do it in tasmota for example would be great!

**Comment by m0wlheld** [comment]
See https://www.zigbee2mqtt.io/integration/home_assistant.html#exposing-switch-as-a-light and close this issue, please.

**Comment by biau** [comment]
Really sorry that I missed that.
Thanks for the link
