### ISSUE TITLE
Eurotronic Spirit Zigbee

### ISSUE THREAD

**Issue by schamu** [Koenkk/zigbee2mqtt#6699]
Eurotronic Spirit Zigbee
Since the update this morning, the set temperature (Occupied Heating Setpoint) is no longer sent from the thermostat to Z2M. I have the current dev version.

Adapter slash with the newest Firmware.

**Comment by sjorge** [comment]
#4571 known issue, without a good fix atm.

**Comment by dr3men** [comment]
A similar problem. Didn't find a solution?
