### ISSUE TITLE
30000ms timeout when changing light color

### ISSUE THREAD

**Issue by lettore** [Koenkk/zigbee2mqtt#670]
Hi,
I'm living with this issue from long time and through many versions of zigbee2mqtt and cc2530 firmware versions.
My problem is when I try to change brightness, color temp or rgb color I have a high chance to hit a 30000ms timeout error or 233 no ack.
This happens rarely when I simply turn on or off the lights.
I should also say that happens more often with Osram lights.
The fact that the light won't respond quickly is acceptable for me, but what is unacceptable it's the complete freeze of the whole system for 30 sec.
I'm using the latest Hassio 0.2.0 addon version and zigbee2mqtt:info 2018-12-8 09:22:05 Coordinator firmware version: '20180815'
  zigbee2mqtt:debug 2018-12-8 09:22:05 zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":11,"panId":"0x1a64","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b0014d9db85","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20180815},"startTime":1544257325,"joinTimeLeft":0}
  zigbee2mqtt:info 2018-12-8 09:22:05 Currently 22 devices are joined:

 https://pastebin.com/sSzUiUKt

**Comment by Koenkk** [comment]
The 233 error happens due to bad stability of the zigbee network, try adding more routers and avoid interference with wifi (https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence)

**Comment by lettore** [comment]
Thank you for the reply, yes i had a wifi router using a channel overlapping with zigbee. I changed the channel of wifi network and now all seems to work better.
