### ISSUE TITLE
Cannot pair Paul Neuhaus Q-remote 

### ISSUE THREAD

**Issue by benalla** [Koenkk/zigbee2mqtt#6722]
I have this new ceiling lamp from Paul Neuhaus which uses a remote.
This remote seems to be supported:
https://www.zigbee2mqtt.io/devices/100.462.31.html

Using a CC2531, I did a factory reset on the remote a few times, but device is not detected as new.
Mind you: I have not yet connected the ceiling lamp.

**Comment by DavidFFerreira** [comment]
@benalla did you get this remote working?
