### ISSUE TITLE
Buying advice: 220v AC Dimmer/switch compatible with Zigbee2MQTT

### ISSUE THREAD

**Issue by hwijers** [Koenkk/zigbee2mqtt#673]
It is not really an issue, but I do not know where else I can ask this question..
I'm looking for an AC Dimmer that is also suitable for dimming normal 220v AC LED lighting. 
Does someone use something like this in combination with this project?
Had already seen 3 solutions:

1. [iCasa ZigBee 3.0 AC Dimmer](https://www.wifimedia.eu/nl/icasa-dimmer.html) or [sr-zg9101sac-hp](https://www.sunricher.com/zigbee-ac-phase-cut-dimmer-sr-zg9101sac-hp.html)
2. [Paulmann 50044](https://www.reichelt.nl/smart-light-zigbee-cephei-dim-schakelcontroller-plm-50044-p217730.html?PROVID=2788&gclid=EAIaIQobChMIns_WzKGQ3wIV0eR3Ch3zcANuEAQYAiABEgKJ5_D_BwE&&r=1)
3. a Wi-Fi alternative, for example an ESP8266: [AC MAINS Dimmer - MPDMv7.5](https://www.tindie.com/products/nEXT_EVO1/ac-mains-dimmer-mpdmv75/)

I do not have any Z-Wave products and would like to limit myself to Zigbee and Wifi (ESP8266) products.

**Comment by ciB89** [comment]
Can't recommend anything yet for Zigbee (because of pricing), but if you want something cheap and can rely on wifi, check out [Shelly1](https://shelly.cloud/shelly1-open-source/)

**Comment by hwijers** [comment]
I ordered a number of Shelly's yesterday.
Have also asked if they also develop a dimmer.

**Comment by khzd** [comment]
I have a couple of gledopto from AliExpress , working fine with zigbee2mqtt.
We worked to enhance some minor releases of the same product
Gl-c-008 see wiki

**Comment by Koenkk** [comment]
+1 for shelly devices (have about 15 of them in my house).

**Comment by matejzero** [comment]
I would love to have some ZigBee dimmers, but it looks like there is no luck for us EU guys:) Or they cost as much/more then Zwave alternatives.

I'm currently talking with Sunricher if they could send me a few samples to test out. But it gets quite expensive with tax, import tax and shipping.

I hear shelly's are great, but I'm still waiting for a dimmer. @hwijers's news are exciting:)

**Comment by james-fry** [comment]
There are three I am looking at (Im in UK, but happy to buy from China):

- https://arc-led.co.uk/controller/609-arc-led-ac-phase-cut-dimmer-with-zigbee-control-interface-white.html
Looks the same as the iCasa, the instructions are [here](https://www.sunricher.com/media/resources/manual/SR-ZG9101SAC-HP%20instruction%20V1.pdf)

- https://www.ebay.co.uk/itm/220V-240V-ZigBee-ZLL-Triac-LED-Dimming-Controller-Trailing-Edge-For-Echo-Plus/273527053337
Looks like it contains the guts of a zigbee ZLL bulb - i.e. no persistent power

- https://www.ebay.co.uk/itm/ZigBee-AC100V-240V-Triac-LED-Controller-Driver-Dimmer-300W-For-Gateway-Echo-Plus/113393934228

Currently leaning toward the 1st.

**Comment by matejzero** [comment]
The first one is Sunricher for sure... But the price is quite high for my usecase, since I would also need to replace the switches (I have toggle switches now). At the end, it's cheaper for me to go with Fibaro's dimmer, which can use toggle switch.

At the moment, I'm testing Shelly1 wifi relay, which works great, but I'm having a bit of a problem with the range (I'm missing the mesh function of zigbee/zwave here).

**Comment by robbz23** [comment]
Did you guys buy any of these?  @james-fry  did you find a source for the sunricher from china?

**Comment by james-fry** [comment]
Yes I bought the ebay one:
https://www.ebay.co.uk/itm/220V-240V-ZigBee-ZLL-Triac-LED-Dimming-Controller-Trailing-Edge-For-Echo-Plus/273527053337
It works great with Philips Hue hub AND now I see its supported in z2m in V1.3.0 :) (although I didnt try it with z2m yet)

I didnt get the sunricher as (1) it was more expensive and (2) needs a push button switch to control. 
I dont have a source for the sunricher from CN either, I'm afraid.

**Comment by robbz23** [comment]
Great.  Unfortunately it doesn't have a the pushbutton control the the sunricher has.  Our current non-smart solution uses these style dimmers in the wall controlled by momentary switches so it would be great to continue to use in addition to zigbee remotes.  

Does it work well with dimmable LED bulbs? I tried to replace one circuit that had 2 bulb on it with Ikea dimmable dumb bulbs, but they weren't enough of a load to dim properly and kept getting stuck.  That's what led me down this path to look for new dimmers that are also zigbee.

**Comment by james-fry** [comment]
It worked perfectly with a single philips dimmable LED (filament style).

**Comment by Huppeltje16** [comment]
Hi,
I've bought three sunricher dimmers and installed them, but my Zigbee2MQTT install on a RPi 3B has quite some problems registering them in the network. At last I have 2 of them joined, and registered in Zigbee2MQTT, but the third never gets recognised as such. It joins, but doesn't register right in the controller.
Furthermore Domoticz only assigns a switch and a linkquality device to the registered ones, so I cannot use them as dimmers, anly as (on/off) switches.
Does anyone recognize this or can anyone suggest how to handle this situation?

Kind regards, Petro

**Comment by tavoc** [comment]
has anyone bought the Paulmann 50044?

I tried to pair it yesterday and got no warnings. But it did not appear in FHEM. Do I miss something?



2019-10-16 8:42:41 PM - info: New device 'Dimmablelight ' with address 0x00158d0002927e11 connected!
2019-10-16 8:42:41 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002927e11","meta":{"modelID":"Dimmablelight "}}'
2019-10-16 8:42:42 PM - info: Device incoming…


2019-10-16 8:45:01 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', {"ieeeAddr":"0x00158d0002927e11","type":"Router","model":"50045","friendly_name":"0x00158d0002927e11","nwkAddr":58864,"manufId":4509,"manufName":"Paulmann Licht GmbH ","powerSource":"Mains (single phase)","modelId":"Dimmablelight ","hwVersion":1,"swBuildId":"1218-0909","dateCode":"20160300"}]}'

**Comment by MaZZie** [comment]
> has anyone bought the Paulmann 50044?
> 
> I tried to pair it yesterday and got no warnings. But it did not appear in FHEM. Do I miss something?
> 
> 2019-10-16 8:42:41 PM - info: New device 'Dimmablelight ' with address 0x00158d0002927e11 connected!
> 2019-10-16 8:42:41 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002927e11","meta":{"modelID":"Dimmablelight "}}'
> 2019-10-16 8:42:42 PM - info: Device incoming…
> 
> 2019-10-16 8:45:01 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', {"ieeeAddr":"0x00158d0002927e11","type":"Router","model":"50045","friendly_name":"0x00158d0002927e11","nwkAddr":58864,"manufId":4509,"manufName":"Paulmann Licht GmbH ","powerSource":"Mains (single phase)","modelId":"Dimmablelight ","hwVersion":1,"swBuildId":"1218-0909","dateCode":"20160300"}]}'

I'm working on this one but can't pair it. I have no remote for it. How did you manage to pair it?

**Comment by tavoc** [comment]
I don't have a remote. I have seen in the manual that you can pair it if you put power in it and then 5 times on off with max 2 seconds pause in between.
I have to look at the manual again. Best if you have a lamp connected because if it is in pair mode the lamp is pulsing
