### ISSUE TITLE
How to detect a device which is offline

### ISSUE THREAD

**Issue by Hambootje** [Koenkk/zigbee2mqtt#674]
Hi,

I'm struggling with zigbee devices in openHAB using the integrated zigbee binding. The problem is that device are reporting a online status even when they are not powered at all.

I was wondering if zigbee2mqtt offers this functionality?
Is there a possibility to do a regular polling and get the current status of a device.
For lamps you know soon enough when it's not responding, but for door contacts which are used for a poor mans alarm system, it is needed that the device is checked on regular basis.

Thanks!

**Comment by Koenkk** [comment]
Door contacts are end devices, which are most of the time offline in order to save energy (so no)
