### ISSUE TITLE
Config for Immax lightbulb

### ISSUE THREAD

**Issue by fuxoft** [Koenkk/zigbee2mqtt#6743]
I have created the devices.js entry for Immax 07088L lightbulb, I attempted to do a pull request but I am not sure if it went through correctly. I have never done a pull request before and, sorry. Adding the code below to devices.js shows the lightbulb as supported and it works correctly:

```
    {
        zigbeeModel: ['E27-filament-Dim-ZB3.0'],
        model: '07088L',
        vendor: 'Immax',
        description: 'Neo SMART LED filament E27 6.3W warm white, dimmable, Zigbee 3.0',
        extend: preset.light_onoff_brightness(),
    },
```

## data/database.db entry of the device

`{"id":4,"type":"Router","ieeeAddr":"0xccccccfffe3ccffd","nwkAddr":32144,"manufId":4151,"manufName":"Immax","powerSource":"Mains (single phase)","modelId":"E27-filament-Dim-ZB3.0","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"E27-filament-Dim-ZB3.0","manufacturerName":"Immax","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190401-99","swBuildId":"2.0"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[64642],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190401-99","swBuildId":"2.0","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1616002031712}
`

**Comment by Koenkk** [comment]
Added! 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
