### ISSUE TITLE
TuYa Thermostatic Valve: system_mode error

### ISSUE THREAD

**Issue by kremik** [Koenkk/zigbee2mqtt#6749]
## What happened
Getting quite frequently an error about setting the 'system_mode'. Error reported as zigbee_publish_error. Setting system mode is done automatically, I'm not sure if it is generated by Homebridge after restart but anyway it should work.

Device: https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#tuya-ts0601_thermostat

`Mar 18 15:54:40 raspberrypi4 npm[21873]: Zigbee2MQTT:info  2021-03-18 15:54:40: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'system_mode' to 'valve1livingroom' failed: 'Error: Command 0x5c0272fffec9d6c1/1 manuSpecificTuya.setData({\"status\":0,\"transid\":0,\"dp\":106,\"datatype\":4,\"length_hi\":0,\"length_lo\":1,\"data\":[0]}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'MAC transaction expired' (240))'","meta":{"friendly_name":"valve1livingroom"},"type":"zigbee_publish_error"}'`

## What did you expect to happen
set the system mode to the right value

## How to reproduce it (minimal and precise)
don't know 

## Debug info
Zigbee2MQTT version:1.18.1
Adapter hardware: CC2531
Adapter firmware version: {"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20201127,"transportrev":2},"type":"zStack12"}

**Comment by Koenkk** [comment]
`Data request failed with error: 'MAC transaction expired' (240)` looks like the same as #6506
