### ISSUE TITLE
Undefined / unknown due to pairing issues

### ISSUE THREAD

**Issue by WebSpider** [Koenkk/zigbee2mqtt#675]
Hi!

Running the latest zigbee2mqtt-edge hassio add-on, I'm running into some issues with seemingly incomplete pairing. The zigbee device (in both cases a sensor, one is a xiaomi door sensor, the other a xiaomi humidity sensor) acts as if it's joined perfectly, but the sent messages, of the device description never makes it into mqtt.

This is only for 2 devices, of which I already have another one configured, so I know they are supposed to work.

I'd like to make the zigbee network (and zigbee2mqtt+cc2531+ha) forget about the devices and try pairing again. Just repairing the sensors doesn't trigger anything unfortunately, they are never removed from the network, and when the sensors repair, I get no notices about incoming devices in logfiles.

When I start zigbee2mqtt, these are my logs, and the offending devices are marked Undefined/unknown as you can see at https://gist.github.com/WebSpider/5bff7f128ab200ca77d7d0b9fa901f58

Any help would be greatly appreciated!

**Comment by WebSpider** [comment]
Hmm, I actually may have a few defective components, since I just managed to get a new motion sensor to join just fine

**Comment by EagleAdam** [comment]
Hi, not sure if this is related, but I tried to pair a Xiaomi Aqara button - WXKG11LM. The pairing seems to work fine at first, but it is showing as an unknown device. With debug mode on, when I press the button I get [this message](https://pastebin.com/iZ5vqMDR). Here is the line from the [database.db file](https://pastebin.com/7Jwt0m6T)

**Comment by Koenkk** [comment]
@EagleAdam did you try the procedure from: https://github.com/Koenkk/zigbee2mqtt/issues/675#issuecomment-445563927?
