### ISSUE TITLE
ADDING Tuya zigbee Wall Socket with Power Monitoring

### ISSUE THREAD

**Issue by Kinnoon** [Koenkk/zigbee2mqtt#6762]
Hello,
I can pair this device but it's don't have metering function
and I tried to add Tuya zigbee Wall Socket with Power Monitoring function, but it's to complicated for me. T T

## Information about the device + link
[Link to shopee](https://shopee.co.th/Tuya-Wi-Fi-Wall-Socket-with-Power-Monitoring-%E0%B8%9B%E0%B8%A5%E0%B8%B1%E0%B9%8A%E0%B8%81%E0%B8%9C%E0%B8%B1%E0%B8%87%E0%B8%9C%E0%B8%99%E0%B8%B1%E0%B8%87%E0%B9%80%E0%B8%9B%E0%B8%B4%E0%B8%94%E0%B8%9B%E0%B8%B4%E0%B8%94%E0%B8%9C%E0%B9%88%E0%B8%B2%E0%B8%99%E0%B9%81%E0%B8%AD%E0%B8%9E-%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B9%84%E0%B8%9F%E0%B8%9F%E0%B9%89%E0%B8%B2%E0%B9%84%E0%B8%94%E0%B9%89-%E0%B8%A3%E0%B8%AD%E0%B8%87%E0%B8%A3%E0%B8%B1%E0%B8%9A-Google-Home-Alexa-i.1714264.3413864948)

## data/database.db entry of the device

{"id":10,"type":"Router","ieeeAddr":"0xec1bbdfffe6dbf5b","nwkAddr":40624,"manufId":4098,"manufName":"_TZ3000_raviyuvk","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,6,1794,2820],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_raviyuvk","powerSource":1,"zclVersion":3,"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"moesStartUpOnOff":1}},"seMetering":{"attributes":{"currentSummDelivered":[0,0]}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":81,"inClusterList":[4,5,6,1794,2820],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":68,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1616157733966}

![wall socket with power metering](https://user-images.githubusercontent.com/63036794/111787990-2e965780-88f2-11eb-9753-65d1e3692092.png)
![wall socket with power metering2](https://user-images.githubusercontent.com/63036794/111788000-2f2eee00-88f2-11eb-9cdd-66a5e58cf6c1.png)

**Comment by lockkp1** [comment]
also looking for help on this, have a similar item
