### ISSUE TITLE
LQI issue

### ISSUE THREAD

**Issue by Ivano62** [Koenkk/zigbee2mqtt#6776]
I've installed zigbee2mqtt 1.18.1 on raspberry pi3 B with a RaspBee II, I've several Xiaomi Aqara Temperature Sensor and some sonoff ZBMINI. The problem is the difference between signal strength visualized on map and on dashboard. On dashboard the values are the same for all sensors and they are different from those displayed on the map . I think it isn't normal.
I haven't signal strength problems, I observe that the application displays discordant values, among other things on the dashboard they are all identical q this I don't think is correct.
Thank you
![zigbee2mqtt - dashboard](https://user-images.githubusercontent.com/43061741/111906979-9adc9c80-8a53-11eb-9101-00c4c9caf0c1.png)
![zigbee2mqtt - map](https://user-images.githubusercontent.com/43061741/111906980-9b753300-8a53-11eb-8dfe-5042780ba756.png)

**Comment by m0wlheld** [comment]
LQI with Raspbee/Conbee is broken and a fix is of low interest. See https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4234
