### ISSUE TITLE
Lowes Iris Gen2 Contact Sensor 

### ISSUE THREAD

**Issue by mattvirus** [Koenkk/zigbee2mqtt#6793]
Zigbee model '1116-S' and manufacturer name 'iMagic by GreatStar'

I'm a github noob and I'm sure to foul-up the PR - this device works fine using the following config in devices.js   
Had this working with external devices.js, but an upgrade broke it.  Attempting to add proper support now with some help from the community here

devices.js  modification:

`    {
        zigbeeModel: ['1116-S'],
        model: 'iMagic by GreatStar IL06_1 Lowes Iris',
        vendor: 'Iris',
        description: 'Contact and temperature sensor',
        fromZigbee: [fz.ias_contact_alarm_1, fz.temperature, fz.battery],
        toZigbee: [],
        meta: {battery: {voltageToPercentage: '3V_2100'}, configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['msTemperatureMeasurement', 'genPowerCfg']);
            await reporting.temperature(endpoint);
            await reporting.batteryVoltage(endpoint);
        },
        exposes: [e.contact(), e.battery_low(), e.tamper(), e.temperature(), e.battery()],
    },`

Log Output:

`Zigbee2MQTT:warn  2021-03-22 21:40:15: Received message from unsupported device with Zigbee model '1116-S' and manufacturer name 'iMagic by GreatStar'`

Device Link:
https://www.lowes.com/pd/Iris-Iris-Indoor-Door-and-Window-Sensor/1000509585

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
