### ISSUE TITLE
Failed to package into binary executable file

### ISSUE THREAD

**Issue by ffzwadd** [Koenkk/zigbee2mqtt#6797]
Hardware: Raspberry PI 3B+
OS: Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
zigbee2mqtt version:  commit hash: b6085fceaed1361a0992cb42f0c82a1a126a9e96
log:
pi@raspberrypi:/opt/zigbee2mqtt $ pkg -t node6-linux index.js
> pkg@4.5.0
> Warning Cannot resolve '`object-assign-deep`'
  /opt/zigbee2mqtt/lib/util/settings.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve ''../../node_modules/' + depend + '/package.json''
  /opt/zigbee2mqtt/lib/util/utils.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'moduleName'
  /opt/zigbee2mqtt/lib/util/utils.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot stat, ENOENT
  /opt/zigbee2mqtt/lib/util/externally-loaded.js
  The file was required from '/opt/zigbee2mqtt/lib/util/utils.js'
> Warning Cannot resolve '`object-assign-deep`'
  /opt/zigbee2mqtt/lib/extension/bridge.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Failed to make bytecode node6-armv7 for file /snapshot/zigbee2mqtt/index.js error (write EPIPE)
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at fabricate (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:131:15)
    at /usr/lib/node_modules/pkg/lib-es5/fabricator.js:144:23
    at Socket.onError (/usr/lib/node_modules/pkg/lib-es5/fabricator.js:83:5)
    at Socket.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:314:20) {
  code: 'ERR_STREAM_DESTROYED'
}

**Comment by sjorge** [comment]
I guess that error makes sense, z2m does some dynamic loading for external_converters and user_extensions.
Which whatever packer you're using is complaining about because the path is only known at runtime.
