### ISSUE TITLE
New coordinator design based on RF-STAR modules (chips cc2652p / cc1352p)

### ISSUE THREAD

**Issue by drbios** [Koenkk/zigbee2mqtt#6815]
Hi
I would like to share this excellent work from Egony who created this new design with RF-STAR cc2562p modules.
I was able to replicate his work without problems by following his instructions and I am really happy with this excellent coordinator. after several cups of coffee and bad language I was able to assemble this coordinator. works with 20db with great penetration power in concrete walls to devices on the second floor

The project page can be found here
https://github.com/egony/cc2652p_cc1352p_RF-STAR/wiki

![20210324_105900](https://user-images.githubusercontent.com/39960438/112323111-39edd800-8c90-11eb-8854-c0171f53e569.jpg)
![20210324_105851](https://user-images.githubusercontent.com/39960438/112323124-3e19f580-8c90-11eb-8893-9fced41e05a2.jpg)

if possible add this layout to the list of supported coordinators

greetings from Chile
Jed anderson

**Comment by drbios** [comment]
> If English instructions are available I'm happy to accept a PR to add this to the supported adapters list.

Which information do you need?
(I use Google translate to read all the instructions)

**Comment by Koenkk** [comment]
A guide on how to create the device yourself (BOM and assembly instructions) + how to flash (and with which firmware)

**Comment by egony** [comment]
> > If English instructions are available I'm happy to accept a PR to add this to the supported adapters list.
Welcome.
https://github.com/egony/cc2652p_cc1352p_RF-STAR/wiki/Home-EN

**Comment by egony** [comment]
Same for E72 boards:
https://github.com/egony/cc2652p_E72-2G4M20S1E/wiki/Home-EN

**Comment by drbios** [comment]
> > > If English instructions are available I'm happy to accept a PR to add this to the supported adapters list.
> 
> Welcome.
> https://github.com/egony/cc2652p_cc1352p_RF-STAR/wiki/Home-EN

Thanks a lot

**Comment by drbios** [comment]
@egony can you explain the auto BSL flashing procedure ? (I have mine running on a raspberry pi with raspberry os lite)
Best regards

**Comment by Koenkk** [comment]
Cool, please make a PR for both https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md and https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/supported_adapters.md

**Comment by egony** [comment]
> @egony could you explain the auto BSL flashing procedure ? (I have mine running on a raspberry pi with raspberry os lite)
> Best regards

Hi! Sorry for delay. Auto BSL means that you need no pressing buttons for bootloader activation. Flashing software puts dongle into bootloader mode automatically. But it works with not all flashing software.

**Comment by egony** [comment]
> Cool, please make a PR for both https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/README.md and https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/supported_adapters.md

Hi!

https://github.com/Koenkk/zigbee2mqtt.io/pull/735
https://github.com/Koenkk/Z-Stack-firmware/pull/288

Done.
