### ISSUE TITLE
EasyCodeTouch - E-Life Zigbee module - EasyAccess

### ISSUE THREAD

**Issue by stolevegen** [Koenkk/zigbee2mqtt#6822]
## Information about the device + link
EasyAccess EasyCodeTouch - E-Life Zigbee module. 
https://easyaccess.no/product/easycodetouch/

## data/database.db entry of the device
https://pastebin.com/91BYdAFC

Issues and notes at bottom.

Planning to create a pull request as: 
Lock/unlock is working.
Battery is working (will know for sure once capacity drops)
Link Quality is working
Added "action" attribute to track lock operation source (Zigbee, keypad, manual, RFID tag)
(Tested in Home Assistant)

Lock also supports setting; 
- Sound volume
- Auto re-lock

Autorelock locks about 7 seconds after unlocking. This is enabled by default. Would be beneficial to have the ability to disables the autorelock, but I'm not sure how to implement it in toZigbee.js. No (EasyAccess) gateway available yet, so can't sniff this command. 

**AutoRelockTime**
Attribute : "AutoRelockTime" 
ID : 0x0023
Type : Write, Reporting
Commands : Enable = 0x01, Disable = 0x00. Default is Enabled. Reported when changed.

**SoundVolume**
Attribute : "SoundVolume" 
ID : 0x0024
Type : Write, Reporting
Commands : Off = 0x00, Low = 0x01 Normal = 0x02. Default is normal. Reported when changed.

Adapter hardware: CC2531
Adapter firmware version: 20190608

**ISSUES AND NOTES:**  

1. Unsure how to set AutoRelockTime through Z2M. 

2. 
```
zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":26,"manufacturerCode":null,"commandIdentifier":1},"Payload":{"status":0},"Command":{"ID":1,"parameters":[{"name":"status","type":32}],"name":"unlockDoorRsp"}},"address":62222,"endpoint":11,"linkquality":0,"groupID":0}' +4s

zigbee-herdsman:controller:log Skipping command 'unlockDoorRsp' because it is missing from the lookup +0ms

```
3.
``` 
zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":26,"manufacturerCode":null,"commandIdentifier":0},"Payload":{"status":0},"Command":{"ID":0,"parameters":[{"name":"status","type":32}],"name":"lockDoorRsp"}},"address":62222,"endpoint":11,"linkquality":5,"groupID":0}' +50ms
 
zigbee-herdsman:controller:log Skipping command 'lockDoorRsp' because it is missing from the lookup +2ms
```

**Comment by Koenkk** [comment]
Please continue in #6379
