### ISSUE TITLE
Tuya TS0042 - no battery percentage and voltage

### ISSUE THREAD

**Issue by DavidFFerreira** [Koenkk/zigbee2mqtt#6832]
What happened
Tuya TS0042 device does not send battery values (no voltage and no percentage, but battery is exposed). As can I see in device clusters it should support battery information, and it was working on ZHA:

image
![image](https://user-images.githubusercontent.com/32928749/112557282-07dd9280-8dc4-11eb-852c-cf2fc91deff1.png)
![image](https://user-images.githubusercontent.com/32928749/112557323-20e64380-8dc4-11eb-8f5d-8d4bb8eecbea.png)

  "manufacturer": "_TZ3400_keyjhapk",
  "model": "TS0042",
  "class": "zhaquirks.tuya.ts0042.BenexmartRemote0042"

What did you expect to happen
Battery level should be reported

How to reproduce it (minimal and precise)
Just pair it and observe no battery values

Debug info
Zigbee2MQTT version: 1.18.1-dev commit: fda0270
Adapter hardware: CC2652R zzh!
Adapter firmware version: 20210120

**Comment by Koenkk** [comment]
Might be that configure fails. You can reconfigure it by clicking on the yellow refresh icon in the frontend: 

![image](https://user-images.githubusercontent.com/2892853/112671351-5a6d8c00-8e62-11eb-96c2-dc0fb647ee8e.png)


If this fails make sure to wake it up by clicking a button on it right before executing the reconfigure.
