### ISSUE TITLE
after you upgraded to a new version everything stopped here at home

### ISSUE THREAD

**Issue by vpereiradn** [Koenkk/zigbee2mqtt#6834]
after you upgraded to a new version everything stopped here at home i have 22 lamps here none lights up anymore, it changed from the share folder to the config folder ..
what is the solution

**Comment by m0wlheld** [comment]
> what is the solution

What is the actual problem? What are „config folder“ and „share folder“?

**Comment by vpereiradn** [comment]
Hi! Good Morning.
Thanks more I already decided, I had to uninstall everything and pair all devices, and it worked.
it is more complicated because every time you update you have this kind of problem, thank you very much!

**Comment by m0wlheld** [comment]
> it is more complicated because every time you update you have this kind of problem

That is not correct. Yet, you haven't provided any details on what you did and what errors it caused.

**Comment by vpereiradn** [comment]
[state.json.zip](https://github.com/Koenkk/zigbee2mqtt/files/6253235/state.json.zip)

i lost all my devices after upgrading to 1.18.2

**Comment by vpereiradn** [comment]
I left the status to see what the error

**Comment by vpereiradn** [comment]
deu certo aqui obrigado. desinstalei e instalei novamente e refiz todo pareamento dos dispositivos.
