### ISSUE TITLE
GLEDOPTO GL-C-007P RGBW LED controller - White color not working (with fix proposal)

### ISSUE THREAD

**Issue by garywr72** [Koenkk/zigbee2mqtt#6836]
Hi,

I bought a  GLEDOPTO GL-C-007P RGBW LED controller. 

Device supported but without white color. RGB control works fine.

Perhaps problem can be fixed by adding colortemp property in devices.js (similar to the issue [https://github.com/Koenkk/zigbee2mqtt/issues/4424](https://github.com/Koenkk/zigbee2mqtt/issues/4424))

zigbeeModel GL-C-007P
Original > "extend: preset.gledopto.light_onoff_brightness_color(),"
Replaced by > "extend: preset.gledopto.light_onoff_brightness_colortemp_color(),"

Right now controller works in RGB mode only.

**Comment by Koenkk** [comment]
Did you test if it works?

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to edit `devices.js`.

**Comment by garywr72** [comment]
Finally I added as a new device in hassio-zigbee2mqtt - I'm a beginner yet :) 
It works, but I get error: No converter available for 'color_temp' and No converter available for 'color_temp_startup'
Probably not fully configured yet.
However, I can change colors and turn on white.

**Comment by Koenkk** [comment]
How do you change the color temp to white now?

**Comment by garywr72** [comment]
I can change the color temp by clicking on color_temp in menu Exposes - similar like in another controller GL-C-008P fully supported in zigbee2mqtt.

**Comment by Koenkk** [comment]
Cool! Added the fix.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
