### ISSUE TITLE
Log file naming after rotation

### ISSUE THREAD

**Issue by Masterz69** [Koenkk/zigbee2mqtt#6852]
## What happened

As far I see log rotation happened and after that they have following names:

log_2021-03-14.15-31-13.txt
log_2021-03-14.15-31-131.txt

![image](https://user-images.githubusercontent.com/15225823/112731165-56af3780-8f3e-11eb-9064-f00029311f7e.png)

## What did you expect to happen
IMHO some divider to be put, like: log_2021-03-14.15-31-13.1.txt or log_2021-03-14.15-31-13_1.txt

## Debug info
info  2021-03-14 15:31:14: Logging to console and directory: '/config/zigbee2mqtt/log' filename: log_2021-03-14.15-31-13.txt
info  2021-03-14 15:31:14: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
info  2021-03-14 15:31:14: Starting zigbee-herdsman (0.13.71)
info  2021-03-14 15:31:17: zigbee-herdsman started
info  2021-03-14 15:31:17: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200921,"transportrev":2},"type":"zStack3x0"}'

**Comment by Koenkk** [comment]
Zigbee2MQTT uses winston for logging, I've checked the docs (https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport) but it seems they don't allow to specify any postfix divider. You can add this yourself by adding the following to your configuration.yaml

```yaml
advanced:
  log_file: 'log_%TIMESTAMP%_.txt'
```
