### ISSUE TITLE
Tuya compatible Skydance 5-in-1 LED Controller WZ5 (TS0601)

### ISSUE THREAD

**Issue by blazewicz** [Koenkk/zigbee2mqtt#6867]
## Information about the device + link

*ZigBee & RF 5 in1 LED Controller WZ5* manufactured by *SKYDANCE*

![Zrzut ekranu 2021-03-29 o 11 01 43](https://user-images.githubusercontent.com/13185945/112813119-2969a300-907e-11eb-89e3-8d3bacbe6dfd.png)

Product page: http://www.iskydance.com/index.php?c=product_show&a=index&id=1584

This device can be reconfigured to one of 5 modes, each is discovered as different device and have different capabilities. All devices share same `modelId` "TS0601".

| # | mode    | manufacturerName
|---|---------|------------------
| 1 | DIM     |                  | 
| 2 | CCT     | _TZE200_gz3n0tzf
| 3 | RGB     |                  | 
| 4 | RGBW    |                  | 
| 5 | RGB+CCT | _TZE200_mde0utnv

## data/database.db entry of the device

Entry for "CCT" Mode

```json
{
    "id": 24,
    "type": "Router",
    "ieeeAddr": "0x60a423fffe043994",
    "nwkAddr": 25068,
    "manufId": 4098,
    "manufName": "_TZE200_gz3n0tzf",
    "powerSource": "Mains (single phase)",
    "modelId": "TS0601",
    "epList": [
        1
    ],
    "endpoints": {
        "1": {
            "profId": 260,
            "epId": 1,
            "devId": 81,
            "inClusterList": [
                0,
                4,
                5,
                61184
            ],
            "outClusterList": [
                25,
                10
            ],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "TS0601",
                        "manufacturerName": "_TZE200_gz3n0tzf",
                        "powerSource": 1,
                        "zclVersion": 3,
                        "appVersion": 66,
                        "stackVersion": 0,
                        "hwVersion": 1,
                        "dateCode": ""
                    }
                }
            },
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "appVersion": 66,
    "stackVersion": 0,
    "hwVersion": 1,
    "dateCode": "",
    "zclVersion": 3,
    "interviewCompleted": true,
    "meta": {
        "configured": 2
    },
    "lastSeen": 1617004825542
}
```

Entry for RGB+CCT mode:

```json
{
    "id": 26,
    "type": "Router",
    "ieeeAddr": "0x60a423fffe043cc3",
    "nwkAddr": 27430,
    "manufId": 4098,
    "manufName": "_TZE200_mde0utnv",
    "powerSource": "Mains (single phase)",
    "modelId": "TS0601",
    "epList": [
        1
    ],
    "endpoints": {
        "1": {
            "profId": 260,
            "epId": 1,
            "devId": 81,
            "inClusterList": [
                0,
                4,
                5,
                61184
            ],
            "outClusterList": [
                25,
                10
            ],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "TS0601",
                        "manufacturerName": "_TZE200_mde0utnv",
                        "powerSource": 1,
                        "zclVersion": 3,
                        "appVersion": 66,
                        "stackVersion": 0,
                        "hwVersion": 1,
                        "dateCode": ""
                    }
                }
            },
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "appVersion": 66,
    "stackVersion": 0,
    "hwVersion": 1,
    "dateCode": "",
    "zclVersion": 3,
    "interviewCompleted": true,
    "meta": {
        "configured": 1
    },
    "lastSeen": 1617121681864
}
```

## Implementation attempt

Current progress can be tracked in related PR: https://github.com/Koenkk/zigbee-herdsman-converters/pull/2437

---

Its my first time adding new device so any help or advice is much appreciated.

**Comment by blazewicz** [comment]
I've tried contacting the manufacturer via [Contact Us](http://www.iskydance.com/index.php?c=content&a=index&id=69) page, lets see what we can get from them.

**Comment by blazewicz** [comment]
By experimenting I found that it uses same color encoding and `dataPoint` as [Lidl HG06467](https://www.zigbee2mqtt.io/devices/HG06467.html) (impl: [toZigbee](https://github.com/Koenkk/zigbee-herdsman-converters/blob/04b6bbced058003eb7e2cf3b7a67f06ded7f3d3d/converters/toZigbee.js#L4349), [fromZigbee](https://github.com/Koenkk/zigbee-herdsman-converters/blob/04b6bbced058003eb7e2cf3b7a67f06ded7f3d3d/converters/fromZigbee.js#L2304)).

**Comment by blazewicz** [comment]
This device appears to be straight implementation of Tuya generic RGBCW light source, all functions are directly from the creator that can be found [here](https://iot.tuya.com) after signing up and starting new project (see screenshot below).

Currently I'm working on generic implementation of Tuya specific protocol for light sources.

![Zrzut ekranu 2021-04-7 o 14 40 49](https://user-images.githubusercontent.com/13185945/113867802-435a6280-97af-11eb-90fb-53eb9828cd9a.png)

**Comment by tbornon** [comment]
Hi,
I'm really interested by your work. Have you been able to successfully make it work with Zigbee2MQTT ?
Regards
