### ISSUE TITLE
Groups - more info please

### ISSUE THREAD

**Issue by 877dev** [Koenkk/zigbee2mqtt#6876]
I am unclear about [Groups](https://www.zigbee2mqtt.io/information/groups.html), maybe the documentation could be updated a little?

Can different lamps only be added to one group at a time?
e.g. could I have the below configuration?

**Group 1:**
Light 1
Light 2

**Group 2:**
Light 3
Light 4

**Group 3:**
Light 1
Light 2
Light 3
Light 4

The reason this would be useful, is that if lights can also be added to one group, they could all flash when doorbell is pressed/fire alarm is active.

**Comment by Koenkk** [comment]
Yes this is possible (due to the nature of how zigbee groups works: https://www.zigbee2mqtt.io/information/groups.html#how-do-groups-work)
