### ISSUE TITLE
I need support for the zigbee module of the YMF40 lock

### ISSUE THREAD

**Issue by diegolz83** [Koenkk/zigbee2mqtt#6878]
I bought the Yale YMF40 lock which is shown as supported in the zigbee2mqtt project documentation. When I try to pair it with my home assistant system using the CC2531 coordinator, the addon log says that the device is not supported, something curious because that lock is in the list of supported devices.
Attached to this message is the description of the zigbee module that my device has and the
[Log.txt](https://github.com/Koenkk/zigbee2mqtt/files/6225499/Log.txt)
![Zigbee module](https://user-images.githubusercontent.com/67612218/112919126-0c5bc100-90cc-11eb-80a3-d942d44e6907.PNG)

 addon log.

**Comment by Faustino-ai** [comment]
I am not sure if what you've shown on the picture is the yale lock... But Yale YMF40 lock is supposed to look like this:
![image](https://user-images.githubusercontent.com/54425937/112950464-e6d2c400-916c-11eb-9a4f-0cf9511d42b2.png)
Are you sure you bought the right thing? Can you show a picture of your real product?

**Comment by diegolz83** [comment]
Yes, I'm sure.

![image](https://user-images.githubusercontent.com/67612218/112983787-b450a900-9123-11eb-98c3-0e2a0eec251c.jpeg)

**Comment by juslex** [comment]
Same problem here with the same zigbee module. In my case the lock is the ydf 40.

**Comment by juslex** [comment]
> Yes, I'm sure.
> 
> ![image](https://user-images.githubusercontent.com/67612218/112983787-b450a900-9123-11eb-98c3-0e2a0eec251c.jpeg)
> 
> In lationiamerica the lock has a red zigbee module that is sold separately and is the one shown in the first photo sent, its brand is "ASSA ABLOY iRevo" and the website says ASSA ABLOY Yale is a Zigbee member
> 
> ![Zigbee](https://user-images.githubusercontent.com/67612218/113043273-d537ef00-9161-11eb-9ee7-c3ce24cb5789.PNG)
> 
> It´s strange that zigbe2mqtt detects the device, ends the interview but then generates an unsupported device message:
> 
> Zigbee2MQTT:info 2021-03-29 18:30:02: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload **'{"message":"interview_successful","meta":{"friendly_name":"0x000d6f00168a65bb","supported":false}**,"type":"pairing"}'
> Zigbee2MQTT:warn 2021-03-29 18:30:06: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'ASSA ABLOY iRevo'
> 
> ![image](https://user-images.githubusercontent.com/67612218/113076884-9d4a9f00-9195-11eb-91a2-9d339c3ea4a8.jpeg)

Hello,

I managed to integrate manually. Please send me which version of z2m you are using. Also send me a print of the z2m front end screen of the lock, I need the zigbee model number. The screen you sent is from the zigbee2mqtt assistant, I need the original z2m front end.

**Comment by diegolz83** [comment]
Sure, I'll try to send this as soon as possible.

**Comment by diegolz83** [comment]
Hi @juslex 

My current zigbee2mqtt version: 1.18.1-1. I attached the screens that you asked me

![modulo_zigbee](https://user-images.githubusercontent.com/67612218/114946316-95832f80-9e10-11eb-818e-4880824b7f4d.jpg)
![Zigbee2mqtt](https://user-images.githubusercontent.com/67612218/114946318-96b45c80-9e10-11eb-9f73-069e09d58ac5.PNG)
![Zigbee2mqtt_log](https://user-images.githubusercontent.com/67612218/114946321-96b45c80-9e10-11eb-9986-ed62ac97d0a9.PNG)
![Zigbee2mqtt_map](https://user-images.githubusercontent.com/67612218/114946322-96b45c80-9e10-11eb-9c7d-83c214592fa5.PNG)

Thanks and I´ll be attentive

**Comment by juslex** [comment]
> Hi @juslex
> 
> My current zigbee2mqtt version: 1.18.1-1. I attached the screens that you asked me
> 
> ![modulo_zigbee](https://user-images.githubusercontent.com/67612218/114946316-95832f80-9e10-11eb-818e-4880824b7f4d.jpg)
> ![Zigbee2mqtt](https://user-images.githubusercontent.com/67612218/114946318-96b45c80-9e10-11eb-9f73-069e09d58ac5.PNG)
> ![Zigbee2mqtt_log](https://user-images.githubusercontent.com/67612218/114946321-96b45c80-9e10-11eb-9986-ed62ac97d0a9.PNG)
> ![Zigbee2mqtt_map](https://user-images.githubusercontent.com/67612218/114946322-96b45c80-9e10-11eb-9c7d-83c214592fa5.PNG)
> 
> Thanks and I´ll be attentive

I need the model name to try to help you with the same solution i used

**Comment by diegolz83** [comment]
What only appear on zigbee module is ASSA ABLOY iRevo Brand and the serial number shown on picture.

**Comment by juslex** [comment]
I need this information:

![68B8128F-6EEC-482C-916F-61BCC1472A49](https://user-images.githubusercontent.com/66561713/114949195-dbe38900-9e26-11eb-9395-b034370584bf.jpeg)

**Comment by diegolz83** [comment]
Appear empty 😔

**Comment by juslex** [comment]
Delete the device removing from database in frontend. Stop zigbee2mqtt try to repair the lock more closer to the coordinator.

**Comment by diegolz83** [comment]
Ok, I'll do so

**Comment by diegolz83** [comment]
@juslex 

![Zigbee_model](https://user-images.githubusercontent.com/67612218/114961460-a93d8e80-9e2e-11eb-8792-f2e0127b659e.PNG)

**Comment by juslex** [comment]
strange this zigbee model is already on devices.js it was supposed to be recognized

**Comment by diegolz83** [comment]
A new error, 
![Zigbee_error](https://user-images.githubusercontent.com/67612218/114962029-9ecfc480-9e2f-11eb-98c9-96165ccf43cf.PNG)

My lock was already recognize but it has errors and entities don´t work

![Captura](https://user-images.githubusercontent.com/67612218/114962434-48af5100-9e30-11eb-817a-7b7f2a92ed0b.PNG)

It never changes from unlocked to locked

**Comment by juslex** [comment]
Try to reconfigure it.

**Comment by diegolz83** [comment]
I have eliminated and integrated it 4 times but the entities don´t respond to the commands. what can i do more?

**Comment by Roger4R** [comment]
Hello, 
Can you help me please?
I have the same problem. Support status = Unsupported. Zigbee model = c700000202. Yale YDF40. 
The LQI is low (just 5) because raspberry is in the other room.

**Comment by diegolz83** [comment]
I have still this problem, appear unsupported device. You can solve the LQI problem installing a zigbee router as a CC2530+CC2591 device, it has a good power and I think you would have no problem if your Raspberry is in another room.

**Comment by Faustino-ai** [comment]
If you are using the latest zigbee2mqtt you might want to read the how to add support for new devices again because there are some changes. You can try to add support yourself according to the guide. If it works until the point where you receive something like no converters available, you can proceed the copy the remaining parts of the code from the existing implementation of YMF40 lock.

**Comment by clferraz** [comment]
I have same problem… 😞
![6B58DF65-A7EC-4A63-B7D5-B7CFDA7B03D7](https://user-images.githubusercontent.com/7823740/121807602-35034980-cc2b-11eb-96b0-327de603b313.png)

**Comment by Gera1974** [comment]
Hi sirs,

I am facing exactly the same issue. Did you manage to find any solution for this ?

Thanks,
