### ISSUE TITLE
zigbee-herdsman:adapter:ezsp:uart Socket error

### ISSUE THREAD

**Issue by kai74** [Koenkk/zigbee2mqtt#6887]
## What happened
I can't start Zigbee2mqtt Edge, it worked perfectly, but for some reason, I now get the following message
## What did you expect to happen
To run as it did earlier :)  
## How to reproduce it (minimal and precise)
Start Zigbee2MQTT edge.
## Debug info
Zigbee2MQTT version: Edge
Adapter hardware: Sonoff ZHABridge
Adapter firmware version: 9.3.1.2(zbbridge)

Logs : https://pastebin.com/YSn7U9yb

**Comment by Koenkk** [comment]
Since EZSP is in the alpha stage currently, please keep discussion here: https://github.com/Koenkk/zigbee-herdsman/issues/319
