### ISSUE TITLE
Setting up the bridge

### ISSUE THREAD

**Issue by motoolfan** [Koenkk/zigbee2mqtt#69]
On a fresh install of raspbian stretch, is there any dependencies that need to install prior to setting up the bridge? I'm trying to minimize issues, if at all possible. Btw, This will be installed on a zero W.
Thanks,

**Comment by Koenkk** [comment]
Just follow https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge

**Comment by motoolfan** [comment]
I've followed the guide and getting errors on setting up the bridge, I'll try and attach the log.
[2018-05-27T19_23_05_987Z-debug.log](https://github.com/Koenkk/zigbee2mqtt/files/2044894/2018-05-27T19_23_05_987Z-debug.log)

**Comment by ciotlosm** [comment]
Can you double check your node and npm versions?

**Comment by motoolfan** [comment]
node --version v10.2.1
npm --version 6.1.0

**Comment by ciotlosm** [comment]
I know there were at least some restrictions on node. In the docs it's specified to use:
```
node --version  # Should output v8.X.X (at time of writing v8.11.2)
npm --version  # Should output > 5.X.X (at time of writing 5.6.0)
```

**Comment by motoolfan** [comment]
I'll uninstall the newer versions and install those versions.

**Comment by Koenkk** [comment]
nodejs 10 is not supported

**Comment by Koenkk** [comment]
Feel free to reopen in case you require more help.
