### ISSUE TITLE
Tuya TS0012 Smart light switch - 2 gang

### ISSUE THREAD

**Issue by Roysteroonie** [Koenkk/zigbee2mqtt#6900]
## What happened
When using {"state_right": "TOGGLE"} (or state_left) the switches toggle in the UI Exposes, yet the physical switch doesn't respond. If I use ON and then OFF as a workaround it does work. I re-paired the device as a precaution, but this didnt help. 
If I use the On/Off in Exposes then it also works, just not TOGGLE

## What did you expect to happen
Expected the switch to TOGGLE as per normal

## How to reproduce it (minimal and precise)
I guess you must have the device firstly. 
Using Node Red, I'm sending {"state_right": "TOGGLE"} as documented [here](https://www.zigbee2mqtt.io/devices/TS0012.html#tuya-ts0012)

## Debug info
Zigbee2MQTT version: **1.18.1-dev commit: ddbfa02**
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, **Conbee II**
Adapter firmware version: **firmware version 26680700**

**Comment by Koenkk** [comment]
Since this is a TuYa device and we know TuYa devices often deviate from the Zigbee spec I expect this device doesn't support the toggle command.
