### ISSUE TITLE
Changing from one CC2652 Adapter to another does not work

### ISSUE THREAD

**Issue by pepp86** [Koenkk/zigbee2mqtt#6902]
Hi,

i tried to set up a backup environment with a second CC2652 Adapter. I shut down the productive z2m environment, transfered the whole data directory and started z2m on the backup machine with this result:

Zigbee2MQTT:debug 2021-03-31 17:54:19: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6757},"serialPort":{"path":"/dev/CC2652"}}'
Zigbee2MQTT:error 2021-03-31 17:55:21: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-31 17:55:21: Failed to start zigbee
Zigbee2MQTT:error 2021-03-31 17:55:21: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-03-31 17:55:21: Exiting...
Zigbee2MQTT:error 2021-03-31 17:55:21: Error: AREQ - ZDO - stateChangeInd after 60000ms
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:67:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.18.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-31T15_55_21_512Z-debug.log

Is it not possible to switch to a second system with a second CC2652 Adapter?

**Comment by pepp86** [comment]
Just to add, a fresh configuration.yaml starts without problems on this machine. Even after the error above.

**Comment by pepp86** [comment]
DEBUG log of herdsman:

`> zigbee2mqtt@1.18.2-dev start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:debug 2021-04-06 10:22:28: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2021-04-06 10:22:28: Logging to console and directory: 'data/log/' filename: log.txt
Zigbee2MQTT:info  2021-04-06 10:22:29: Starting Zigbee2MQTT version 1.18.2-dev (commit #1726899)
Zigbee2MQTT:info  2021-04-06 10:22:29: Starting zigbee-herdsman (0.13.89)
Zigbee2MQTT:debug 2021-04-06 10:22:29: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6757},"serialPort":{"path":"/dev/CC2652"}}'
  zigbee-herdsman:adapter Path '/dev/CC2652' is valid for 'ZStackAdapter' +0ms
  zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6757,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/CC2652"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}' +0ms
  zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/CC2652 and {"baudRate":115200,"rtscts":false,"autoOpen":false} +0ms
  zigbee-herdsman:adapter:zStack:znp:log Serialport opened +7ms
  zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload +458ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239] +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1} +0ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32] +1s
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,1,89,6,61] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,1,89,6,61] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 1 - [89,6] - 61 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - ping - {"capabilities":1625} +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +4ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - version - {} +16ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,2,35] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,10,97,2,2,1,2,7] +5ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,2,2,1,2,7] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [1,200,97,52,1,0,242] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,2,2,1,2,7,1,200,97,52,1,0,242] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 10 - 3 - 1 - 2 - [2,1,2,7,1,200,97,52,1,0] - 242 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120} +9ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
  zigbee-herdsman:adapter:zStack:adapter Adapter concurrent: 16 +0ms
  zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack3x0' ({"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}) +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +9ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +9ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62] +11ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}} +13ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +12ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62] +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62 +1ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}} +11ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid +11ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}} +11ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,132,0,0,174] +11ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,97,8,0,4,0,8] +13ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,97,8,0,4,0,8] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,0,99] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,97,8,0,4,0,8,0,0,99] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 3 - 1 - 8 - [0,4,0,8,0,0] - 99 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":4,"value":{"type":"Buffer","data":[0,8,0,0]}} +16ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid +16ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}} +16ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,99,0,0,73] +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,0,107] +13ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,0,107] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,0] - 107 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[0]}} +14ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid +14ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":98,"configid":98,"len":16,"offset":0,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}} +14ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,98,0,0,72] +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,8,0,16,1,3] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,1,3] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [5,7,9,11,13,15,0,2] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,1,3,5,7,9,11,13,15,0,2] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [4,6,8,10,12,13,104] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,104] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 8 - [0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 104 +1ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}} +16ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is valid +16ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":131,"len":2,"offset":0,"value":{"type":"Buffer","data":[101,26]}} +16ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,131,0,0,169] +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,4,97,8,0,2,101,26] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,4,97,8,0,2,101,26] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [16] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,4,97,8,0,2,101,26,16] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 4 - 3 - 1 - 8 - [0,2,101,26] - 16 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":2,"value":{"type":"Buffer","data":[101,26]}} +14ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'panID' is valid +14ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":45,"len":8,"offset":0,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}} +14ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,45,0,0,7] +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,10,97,8,0,8,221,221] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,8,0,8,221,221] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [221,221,221,221,221,221,107] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,8,0,8,221,221,221,221,221,221,221,221,107] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 10 - 3 - 1 - 8 - [0,8,221,221,221,221,221,221,221,221] - 107 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":8,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}} +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:startZnp Item 'extendedPanID' is valid +14ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> UTIL - getDeviceInfo - {} +14ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,39,0,39] +14ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,103,0,0,124,177,159] +10ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,124,177,159] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [33,0,75,18,0,254,255,7] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,124,177,159,33,0,75,18,0,254,255,7] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,0,69] +3ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,124,177,159,33,0,75,18,0,254,255,7,0,0,69] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 7 - 0 - [0,124,177,159,33,0,75,18,0,254,255,7,0,0] - 69 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b00219fb17c","shortaddr":65534,"devicetype":7,"devicestate":0,"numassocdevices":0,"assocdeviceslist":[]} +15ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
  zigbee-herdsman:adapter:zStack:startZnp Start ZNP as coordinator... +16ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - startupFromApp - {"startdelay":100} +16ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,37,64,100,0,3] +16ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,64,0,36,254,3] +2s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,64,0,36,254,3] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 64 - [0] - 36 +1ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - startupFromApp - {"status":0} +2s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [79,128,1,2,4,203] +2ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,1,2,4,203] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [1,2,4] - 203 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":1} +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140] +299ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8} +300ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,0,132,254,3] +566ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,0,132,254,3] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [0] - 132 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":0} +569ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [79,128,8,2,0,198,254,3,79,128,8,2,0,198] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8} +2ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198] +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198 +0ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8} +1ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
Zigbee2MQTT:error 2021-04-06 10:23:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-06 10:23:31: Failed to start zigbee
Zigbee2MQTT:error 2021-04-06 10:23:31: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-06 10:23:31: Exiting...
Zigbee2MQTT:error 2021-04-06 10:23:31: Error: AREQ - ZDO - stateChangeInd after 60000ms
`

**Comment by Koenkk** [comment]
Currently you need to reflash the stick before you can restore a backup to it. Otherwise you will get the `AREQ - ZDO - stateChangeInd after 60000ms`. This will be solved once https://github.com/Koenkk/zigbee-herdsman/pull/303 is merged

**Comment by pepp86** [comment]
Thank you! Never tried a fresh flashed board.

Have now migrated to another machine and board and back. Now both boards should work fine serving the network, right?

**Comment by castorw** [comment]
> Have now migrated to another machine and board and back. Now both boards should work fine serving the network, right?

Hi there, not sure what you mean. Do you expect both coordinators to work in the same wireless coverage area simultaneously? Because that won't work - you can only have one coordinator on the network. The other one can be considered "rogue" and won't work, only cause your devices to possibly float between networks and lots of conflict ZigBee messages to be produced.

**Comment by pepp86** [comment]
No, that's not what I meant. Sorry to be unclear. 

I want to have the second system as a backup which I can move over without being onsite. So, as the second machine and board are now started once with the configuration, it should be possible to just shutdown the main system, transfer data folder and start the backup system with that configuration.

**Comment by castorw** [comment]
Yeah that's theoretically possible, however if you wish to continue serving the same network from another hardware you would want to have the backup loaded. Even after Koenkk/zigbee-herdsman#303 this won't happen automatically since the adapter  will have the same network parameters and won't be considered "out-of-sync". So in order to do such you will need to wipe the adapter's NV memory first and then the backup would be restored. So if one of your adapter fails, you wipe the other one and start Z2M with the other (freshly cleared) adapter (meaning after the PR mentioned above).

To clear the adapter's NV memory you could use a script embedded with Z2M (https://github.com/Koenkk/zigbee2mqtt/blob/master/scripts/zStackEraseAllNvMem.js) and then start Z2M with the other adapter 😊

Why this is important?
* Restore network key frame counters - failing to do so would cause most devices to ignore messages from coordinator,
* Restore APS keys - failing to do so would cause APS security devices to stop working at all.

**Comment by pepp86** [comment]
Ok. Understand.

Fow now I have a manuel solution as a backup and will wait for the mentioned PR to be executed to habe a more "automated" solution for a backup without the need to reflash the adapter before pushing a backup onto it.

Thank you!
