### ISSUE TITLE
Zigbee2MQTT restart every 5 seconds since last update

### ISSUE THREAD

**Issue by freakbn777** [Koenkk/zigbee2mqtt#6912]
# Bug Report
## What happened
Since update done by 'git pull' today, Zigbee2MQTT restart every ~5 seconds
I flashed the latest firmware on my CC2531
I updated Node (14.16.0) and NPM (6.14.11)
I also reseted the key (2s button push)
And notthing in FAQ regarding usual CC2531 problems allow me to solve that issue

Debug log: 
https://pastebin.com/zZyZLeFE

## Debug Info
Zigbee2MQTT version: Latest
Adapter hardware: CC2531
Adapter firmware version: Latest

**Comment by freakbn777** [comment]
I used debug mode and that showed me that few modules are missing or too old, I installed and updated then, now service don't restart every second.

But since I have copy back my /data folder, I have this message and /data/log/xxxx/log.txt is created but empty.
https://pastebin.com/5eXdtnWT

**Comment by Koenkk** [comment]
- First log looks like you need to execute: `cd /opt/zigbee2mqtt && npm ci`
- Second log shows a permission error (run z2m as root or fix your permission on the data directory).

**Comment by freakbn777** [comment]
Thanks, When I installed it, it was done with Pi user but now it disable and I use an another account, I made chown -R regarding your reply, and also the first command. Everything is running again, devices are coming back automatically.

Many thanks for your help :)
