### ISSUE TITLE
Livarno Lux E27 bulb RGB UNSUPPORTED_ATTRIBUTE when try restore color on expose

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#6921]
## What happened
![Screenshot_20210402-070643](https://user-images.githubusercontent.com/59237288/113382634-49e97400-9382-11eb-96fc-8f8af79278d7.jpg)
When try restore color got this error:

(Propably this issue have all Lidl livarno bulbs)

Zigbee2MQTT:error 2021-04-02 07:02:30: Publish 'get' 'color' to 'Światło Pokój' failed: 'Error: Read 0x842e14fffe1b95c6/1 lightingColorCtrl(["currentX","currentY","enhancedCurrentHue","currentSaturation"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

## What did you expect to happen
Restore color 
## Debug info
Zigbee2MQTT version: 1.18.2-1
Adapter hardware: CC2652RB
Adapter firmware version: CC2652RB_coordinator_20210120.zip

**Comment by sjorge** [comment]
Can you try using the read convertor to see if it is enhancedCurrentHue that is causing the issue, the bulb might only support the non enhanced version.

(Make sure to use your friendly_name)
```
mosquitto_pub -t zigbee2mqtt/0x14b457fffe2bd760/set/read -m '{"attributes": ["enhancedCurrentHue"], "cluster": "lightingColorCtrl"}'
 ```

It only logs to debug logging, so you need to enable that too, if that fails you can try reading the non enhanced variant.

```
mosquitto_pub -t zigbee2mqtt/0x14b457fffe2bd760/set/read -m '{"attributes": ["currentHue"], "cluster": "lightingColorCtrl"}'
```

**Comment by shirou93** [comment]
bash: mosquitto_pub: command not found - container in HomeAssistant

**Comment by nurikk** [comment]
> Can you try using the read convertor to see if it is enhancedCurrentHue that is causing the issue, the bulb might only support the non enhanced version.
> 
> (Make sure to use your friendly_name)
> 
> ```
> mosquitto_pub -t zigbee2mqtt/0x14b457fffe2bd760/set/read -m '{"attributes": ["enhancedCurrentHue"], "cluster": "lightingColorCtrl"}'
> ```
> 
> It only logs to debug logging, so you need to enable that too, if that fails you can try reading the non enhanced variant.
> 
> ```
> mosquitto_pub -t zigbee2mqtt/0x14b457fffe2bd760/set/read -m '{"attributes": ["currentHue"], "cluster": "lightingColorCtrl"}'
> ```

hey guys, @sjorge @shirou93 I've implemented UI for this api, try to update on latest dev branch

@sjorge I would like to hear your feedback for future improvements
 
<img width="942" alt="Screenshot 2021-04-03 at 15 42 05" src="https://user-images.githubusercontent.com/1525421/113483098-51209700-94d4-11eb-8a93-3932bab6695b.png">

**Comment by sjorge** [comment]
@nurikk seems to work well enough, I did notice a minor issue with the results not being cleared when doing a new read.
e.g. read genBasic.zlcVersion, then read OnOff.onOff both results are displayed below. Aside from that, it's very usable.

I'm not sure we should show this by default though, it was only ever intended to help us (us being developers) to get a way to have a user test something in a quick and easy way. cc: @Koenkk any opinion on this? Should this be hidden after a configuration property? Or just have it show up for everyone?

**Comment by shirou93** [comment]
Hey guys, we getting off the point ... How do I use this tool to help fix the issue?

**Comment by sjorge** [comment]
> Hey guys, we getting off the point ... How do I use this tool to help fix the issue?

If you can get on the latest dev release, you should now be able to use the frontend and try to reed this the attribute mentioned earlier.

<img width="1820" alt="image" src="https://user-images.githubusercontent.com/379665/113491949-c42a0d80-94d4-11eb-9f52-13c71b1196cc.png">

Is what it looks like when it's not supported, which I suspect is the case for the Livarno.

If it is support it will look like this (other hue value most likely though)

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/379665/113491974-ede33480-94d4-11eb-8465-a69306ed743b.png">

**Comment by shirou93** [comment]
> > Hey guys, we getting off the point ... How do I use this tool to help fix the issue?
> 
> If you can get on the latest dev release, you should now be able to use the frontend and try to reed this the attribute mentioned earlier.
> 
> <img alt="image" width="1820" src="https://user-images.githubusercontent.com/379665/113491949-c42a0d80-94d4-11eb-9f52-13c71b1196cc.png">
> 
> Is what it looks like when it's not supported, which I suspect is the case for the Livarno.
> 
> If it is support it will look like this (other hue value most likely though)
> 
> <img alt="image" width="1189" src="https://user-images.githubusercontent.com/379665/113491974-ede33480-94d4-11eb-8465-a69306ed743b.png">

what exactly type on textbox attribute?

**Comment by sjorge** [comment]
> what exactly type on textbox attribute?

It's actually a drop down, you select 'enhancedCurrentHue'

**Comment by shirou93** [comment]
> > what exactly type on textbox attribute?
> 
> It's actually a drop down, you select 'enhancedCurrentHue'

![Screenshot_20210403-234209](https://user-images.githubusercontent.com/59237288/113492225-47982e80-94d6-11eb-9139-6db484e2db77.jpg)

**Comment by sjorge** [comment]
Cluster => LColorCtrl
Attribute => enhancedCurrentHue

**Comment by shirou93** [comment]
> Cluster => LColorCtrl
> Attribute => enhancedCurrentHue

Thx. 
![Screenshot_20210403-234605](https://user-images.githubusercontent.com/59237288/113492310-d3aa5600-94d6-11eb-8d32-688e6ae8d620.jpg)

**Comment by sjorge** [comment]
I opened a PR that marks enhancedHue as unsupported for this device, it should fall back to reading the non enhanced variant. https://github.com/Koenkk/zigbee-herdsman-converters/pull/2445

**Comment by shirou93** [comment]
All Lidl bulbs? Propably all this bulbs have same firmware

**Comment by sjorge** [comment]
Does the E14 get the same result when reading the attribute manually? If so I’ll update the PR.

I could indeed be all Lidl bulbs, but just making that assumption is risky.

**Comment by shirou93** [comment]
> Does the E14 get the same result when reading the attribute manually? If so I’ll update the PR.
> 
> I could indeed be all Lidl bulbs, but just making that assumption is risky.

On Lidl  online store this bulbs is one product with another thread. I'm pretty sure this is same  supported atributes.

**Comment by shirou93** [comment]
![Screenshot_20210404-002002](https://user-images.githubusercontent.com/59237288/113492954-9eeccd80-94db-11eb-8a77-0954a3597919.jpg)

**Comment by sjorge** [comment]
@Koenkk are you OK with applying this to all RGB bulbs from Lidl?

**Comment by Koenkk** [comment]
@sjorge yes, they probably share the same fw.

**Comment by shirou93** [comment]
@sjorge  thanks for fix. I have one more question. This issue causes change color bulp in home assistant ui on default choised from zigbee2mqtt? When i change different color on HomeAssistant UI after a while in UI HomeAssistant color change to last choised in zigbee2mqtt ui (bulb no change color phisicly). It's wery strange
![image](https://user-images.githubusercontent.com/59237288/113780149-15353e00-972f-11eb-82bf-d2d39a600597.png)

**Comment by sjorge** [comment]
I’m not using homeassisant so I’m not sure what the problem could be.

**Comment by shirou93** [comment]
@sjorge I tryed only on z2m ui and looks like when change RGB color and after change color temp, color rgb last state rgb return to ui without change state phisicly in bulp. 
![image](https://user-images.githubusercontent.com/59237288/113783456-10bf5400-9734-11eb-99d0-73c591c81c1e.png)

**Comment by shirou93** [comment]
@sjorge SMART+ CLASSIC MULTICOLOUR 60 10W E27 (AC25697) have same issue 
"when change RGB color xy and after change color temp, color rgb xy last state rgb return to ui without change state phisicly in bulb."

**Comment by sjorge** [comment]
Can you read the same attribute like for the lidl one? If it shows the same log entry it’s an easy fix.

**Comment by shirou93** [comment]
I thought it was related.  Ledvance  not have issue UNSUPPORTED_ATTRIBUTE.

**Comment by sjorge** [comment]
There are currently a few know issues with color_temp/xy/hs not being in sync when changing one.
There are 2 PR open to address this, one is making some good progress the other is on hold waiting for the other one.

It's a not so trivial issue is a mix of read/report/set and each play a part, and it's not one size fits all unfortunately.

**Comment by shirou93** [comment]
@sjorge  thanks for your help.
