### ISSUE TITLE
Update FAQ - Better workaround for users unable to access device.

### ISSUE THREAD

**Issue by sibero80** [Koenkk/zigbee2mqtt#6936]
Used Node.js installation method.
Faced permission issues accessing device.
Tried the suggested method in the FAQ with no success.

Found this https://github.com/esp8266/source-code-examples/issues/26 forum that provided the following approach:

Add user to the `uucp ` ,  `tty `  ,  `dialout `   groups:
```
sudo usermod -a -G uucp $USER
sudo usermod -a -G tty $USER
sudo usermod -a -G dialout $USER
```

The particular group that would make it work depends on the type of serial connection and linux distribution.

I think this would be a more simple solution but just wanted to bring some light to this with the hopes that someone more knowledgeable could provide a more educated opinion.

Cheers!

**Comment by Koenkk** [comment]
Thanks, please make a pull request by clicking the pencil icon here:  https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/FAQ.md
