### ISSUE TITLE
i lost all my devices after upgrading to 1.18.2

### ISSUE THREAD

**Issue by vpereiradn** [Koenkk/zigbee2mqtt#6945]
Hey Good afternoon!
everything stopped here again at home, all devices no longer respond, and this error occurs when triggering

i lost all my devices after upgrading to 1.18.2

[state.json.zip](https://github.com/Koenkk/zigbee2mqtt/files/6253230/state.json.zip)
](url)

**Comment by kashesandr** [comment]
Experiencing the same

**Comment by vpereiradn** [comment]
nao entendi!!

**Comment by kashesandr** [comment]
I had to reconnect all the devices after the zigbee2mqtt upgrade...

**Comment by vpereiradn** [comment]
I ended up doing it too, I had to pair all devices here at home, now everything is working perfectly

**Comment by kevincaradant** [comment]
Hi

Is it normal @Koenkk ? I'm currently hesitate to upgrade on 1.18.2 in this case. I have a lot of devices and some are difficulties to reach physically :)

thank you

**Comment by kevincaradant** [comment]
Alright thank you for your answer :). I was scared to miss some breaking changes on this version.
