### ISSUE TITLE
Fail to connect to the adapter (CC2530)

### ISSUE THREAD

**Issue by M10TrungPhan** [Koenkk/zigbee2mqtt#6965]
I have an issues.
I run zigbee2mqtt on Windows. I use module CC2530.
What happened
zigbee2mqtt cannot connect to adpater
Zigbee2MQTT:info  2021-04-05 17:02:22: Logging to console and directory: 'C:\Users\DELL\zigbee2mqtt-master\data\log\2021-04-05.17-02-21' filename: log.txt
Zigbee2MQTT:info  2021-04-05 17:02:22: Starting Zigbee2MQTT version 1.18.1 (commit #unknown)
Zigbee2MQTT:info  2021-04-05 17:02:22: Starting zigbee-herdsman (0.13.71)
Zigbee2MQTT:error 2021-04-05 17:02:42: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-05 17:02:42: Failed to start zigbee
Zigbee2MQTT:error 2021-04-05 17:02:42: Exiting...
Zigbee2MQTT:error 2021-04-05 17:02:42: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (C:\Users\DELL\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\adapter\z-stack\adapter\zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\DELL\zigbee2mqtt-master\node_modules\zigbee-herdsman\dist\adapter\z-stack\adapter\zStackAdapter.js:25:65)

**Comment by TheStigh** [comment]
Done all [here](https://www.zigbee2mqtt.io/information/FAQ.html#) ?
