### ISSUE TITLE
Interview failed

### ISSUE THREAD

**Issue by bricololo44** [Koenkk/zigbee2mqtt#6969]
## What happened
My Switch Opple (WXCJKG13LM - 6 buttons) unpaired and now not pairing correctly
Il worked well before
It does not work on my raspberry with CC2652RB dongle
For test : It pairs well on another raspberry with another CC2531 dongle
For the pairing, I check https://www.zigbee2mqtt.io/information/FAQ.html#interview-fails

In Frontend it is not recognized it is indicated Unsupported
I did not remove the device correctly because it is unresponsive.
I have to force to remove

## What did you expect to happen
A good pairing

## How to reproduce it (minimal and precise)
At each pairing

## Debug info   zigbee-herdsman

zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":36137,"extaddr":"0x04cf8cdf3c798836","parentaddr":0} +12s
  zigbee-herdsman:controller:log Device '0x04cf8cdf3c798836' joined +12s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +6ms
  zigbee-herdsman:controller:log Device '0x04cf8cdf3c798836' accepted by handler +3ms
  zigbee-herdsman:controller:log New device '0x04cf8cdf3c798836' joined +1ms
  zigbee-herdsman:controller:log Creating device '0x04cf8cdf3c798836' +0ms
Zigbee2MQTT:info  2021-04-05 20:38:34: Device '0x04cf8cdf3c798836' joined
Zigbee2MQTT:info  2021-04-05 20:38:34: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x04cf8cdf3c798836","ieee_address":"0x04cf8cdf3c798836"},"type":"device_joined"}'
  zigbee-herdsman:controller:log Interview '0x04cf8cdf3c798836' start +117ms
Zigbee2MQTT:info  2021-04-05 20:38:34: Starting interview of '0x04cf8cdf3c798836'
Zigbee2MQTT:info  2021-04-05 20:38:34: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x04cf8cdf3c798836","ieee_address":"0x04cf8cdf3c798836","status":"started"},"type":"device_interview"}'
  zigbee-herdsman:controller:device:log Interview - start device '0x04cf8cdf3c798836' +0ms
  zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":36137,"nwkaddrofinterest":36137} +12s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,41,141,41,141,35] +12s
Zigbee2MQTT:info  2021-04-05 20:38:34: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x04cf8cdf3c798836"},"type":"device_connected"}'
Zigbee2MQTT:info  2021-04-05 20:38:34: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x04cf8cdf3c798836"},"type":"pairing"}'

AND AFTER FEW SECONDS

zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x04cf8cdf3c798836', attempt 3 +23s
  zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":36137,"nwkaddrofinterest":36137} +10s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,41,141,41,141,35] +10s
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102] +10s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102 +2ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0} +10s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms

i feel like something bad is memorized in the key

Zigbee2MQTT version  1.18.1 commit: b6085fce
Coordinator type   CC2652RB   zStack3x0
Coordinator revision     20210120

**Comment by BFFonseca** [comment]
I'm having the same issue on the Home Assistant Z2M addon with Mosquitto Broker 5.1 addon.
Running on a Raspberry 4 with a CC2531 (Z-stack Zigbee 3.0.X)

I've had this setup run properly before. It stopped working after I moved it (diferent location and network).

Right now this is what happens:
Only one device pairs (always the same)
Another one is picked up by z3m but fails the interview (exactly like OP said)
The rest of my devices never even show up as an interview attempt.

Here's my log on debug level:
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/6280592/log.txt)
