### ISSUE TITLE
Request help with new device, Tuya based temperature display

### ISSUE THREAD

**Issue by Peterpc58** [Koenkk/zigbee2mqtt#6978]
The device does not give a ModelID, it reports this:
Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
What do I fill in at ModelID and manufacturerName?
## Information about the device + link
Tuya ZigBee Smart Home Temperature And Humidity Sensor With LED Screen Works With Google Assistant and Tuya Zigbee Hub
https://nl.aliexpress.com/item/4000843004202.html?spm=a2g0s.9042311.0.0.27424c4d6KGtOH

## data/database.db entry of the device
How can I read this file? Tried DB browser for SQ lite, but have to fill in a Password.

**Comment by kizio1000** [comment]
Same here. I have bought it but much to my surprise ( regarding facet that it look very similar to already supported devices ) it's not working with z2m.

**Comment by vajpeters** [comment]
Yups, confirmed: same problem here. Old version was detected, I bought two new ones and guess what: new version. Any succes yet?

**Comment by kizio1000** [comment]
After switching to edge I have support for this sensor.
![Screenshot 2021-05-12 091321](https://user-images.githubusercontent.com/76654878/117933886-573f3a00-b302-11eb-94a1-0b7dbaea4fa0.jpg)
![Screenshot 2021-05-12 091404](https://user-images.githubusercontent.com/76654878/117934005-76d66280-b302-11eb-8dbe-b4fa657e06ea.jpg)

**Comment by vajpeters** [comment]
![Screenshot_20210512-093858](https://user-images.githubusercontent.com/19168848/117937294-19dcab80-b306-11eb-88de-e51b79909743.png)

**Comment by kizio1000** [comment]
Try pairing couple times. Yesterday I have moved from CC2531 to CC2652p and had to pair him 4 times before he was correctly interviewed.

**Comment by vajpeters** [comment]
Ok, latest edge version solves the issue! Issue van be close!
