### ISSUE TITLE
Home Assistant config fields `xy` and `hs` are getting deprecated

### ISSUE THREAD

**Issue by blazewicz** [Koenkk/zigbee2mqtt#6983]
> Feature flags `color_temp`, `hs`, `rgb`, `white_value`, `xy` are all deprecated and support will be removed in 2021.10.

source: https://github.com/home-assistant/core/pull/47993

related z2m code:

https://github.com/Koenkk/zigbee2mqtt/blob/abd8a0926403d2b6d6c9a1a175f917262926c72f/lib/extension/homeassistant.js#L87-L101

**Comment by Koenkk** [comment]
Thanks for creating this issue, will add this after some time to give z2m users some time to upgrade their HA instances

**Comment by Koenkk** [comment]
Fixed in #7057
