### ISSUE TITLE
Multiple types of links (176 / 36)

### ISSUE THREAD

**Issue by avvalex** [Koenkk/zigbee2mqtt#6989]
In the frontend's map it's explained that "values with / represents "... But what does that means exactly?
For example, the Sonoff ZBMINI "Luce Alex" has a LQI of 36, and apparently seems connected only with the coordinator. The link quality measurement is always around 28-39 (it lowers when the switch is on, maybe caused by EMI), nothing strange so far.
But also the other number changes, between 172 and 178. Where this number il taken from? Maybe one is the LQI from Coordinator to Sonoff and the other is the LQI from Sonoff to Coordinator?
Perhaps this should be better clarified in the guides.
Thanks!

<img width="1152" alt="111841802-d1ed6980-88fe-11eb-90e4-401ea04947ea" src="https://user-images.githubusercontent.com/60694870/113896842-97bf0b80-97ca-11eb-94d9-7020e7b86344.png">

**Comment by Koenkk** [comment]
As requested in https://github.com/Koenkk/zigbee2mqtt/issues/new/choose please create frontend issues here: https://github.com/nurikk/z2m-frontend/issues
