### ISSUE TITLE
Ikea Styrbar remote is not supported although it is in supported list

### ISSUE THREAD

**Issue by ProgoX** [Koenkk/zigbee2mqtt#7010]
## What happened
I tried to connect the Ikea Styrbar Remote Control(W2049) to zigbee2mqtt. According to the supported device list it should be supported: https://www.zigbee2mqtt.io/devices/W2049.html

But the remote is added to the device list with "Unsupported Manufacturer". 
Also I get the log output when pressing a button:
"Received message from unsupported device with Zigbee model 'Remote Control N2' and manufacturer name 'IKEA of Sweden'"

## How to reproduce it (minimal and precise)
Problems occurs everytime, even after deleting and rebinding it.

## Debug info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: Conbee II

**Comment by Koenkk** [comment]
It has been added in 1.18.2 (it's not supported in 1.18.1).
