### ISSUE TITLE
HLD833-Z-SC 

### ISSUE THREAD

**Issue by l0r3nt-domo** [Koenkk/zigbee2mqtt#7015]
I pluged HLC833-Z-SC with model no: HLD833-Z-SC-BS-PM-1C-IA-R-WP-OTA-PRO

By default it dont work in z2m.

So i modified node_modules/herdsman-converters/devices.js to

 {
        zigbeeModel: ['HOMA1064', '012'],
        model: 'HLC833-Z-SC',
        vendor: 'Shenzhen Homa',
        description: 'Wireless dimmable controller',
        extend: preset.light_onoff_brightness(),
    },

And all work fine can you update please

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
