### ISSUE TITLE
FrankEver Smart Water Valve - Al files there - Need help to get them into release

### ISSUE THREAD

**Issue by ArJay60** [Koenkk/zigbee2mqtt#7019]
Created support of a new device with the option of external converter in configuration.yaml. Need assistance to fold this into regular supported device. In zip are md-file, image-file and the external converter js that used and is working.

[FrankEver.zip](https://github.com/Koenkk/zigbee2mqtt/files/6287073/FrankEver.zip)

device link: http://www.frankever.com/product_nei.aspx?id=1485

**Comment by ArJay60** [comment]
@Koenkk . Can you help me to fold this external converter and supporting files in a new release? I am not familiar with git. Regards.

**Comment by Koenkk** [comment]
Created https://github.com/Koenkk/zigbee-herdsman-converters/pull/2491 , let's continue discussion there.
