### ISSUE TITLE
Namron Zigbee 2 channel switch K4  - Black

### ISSUE THREAD

**Issue by bjornidar** [Koenkk/zigbee2mqtt#7023]
Seems like Namron has release a new version of the Zigbee 2 channel switch K4, 4512729 which is unsupported.
Will this be added to the "supported devices" list? 
As I can see from the docs, the only difference is the color(?)

Edit:
I've never made a pull request so I'm not sure how to do it, but it worked for me by copying the 4512719 device and replacing it with 4512729
```
    {
        zigbeeModel: ['4512729'],
        model: '4512729',
        vendor: 'Namron',
        description: 'Zigbee 2 channel switch K4 Black',
        fromZigbee: [fz.command_on, fz.command_off, fz.battery, fz.command_move, fz.command_stop],
        meta: {multiEndpoint: true},
        exposes: [e.battery(), e.action(['on_l1', 'off_l1', 'brightness_move_up_l1', 'brightness_move_down_l1', 'brightness_stop_l1',
            'on_l2', 'off_l2', 'brightness_move_up_l2', 'brightness_move_down_l2', 'brightness_stop_l2'])],
        toZigbee: [],
        endpoint: (device) => {
            return {l1: 1, l2: 2};
        },
    },
```

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
