### ISSUE TITLE
Zigbee goes to sleep

### ISSUE THREAD

**Issue by zizebra** [Koenkk/zigbee2mqtt#7039]
## What happened
My Zigbee network seems to go into what appears to be standy mode. In this mode, the zigbee is still running, but there are no messages recieved from the devices. I found out that when i send a command to turn on of the light bulbs, then device comes alive. I start seeing messages from the rest of the devices. It will work for about 30min to 1 hour before it stops recieving messages.
## What did you expect to happen
My expectation is that this zigbee network never sleeps. It must keep recieving and processing messages and the messages to MQTT

## How to reproduce it (minimal and precise)
I restart my raspberry pi and wait 30min to 1hour. It will stop recieving messages.
## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version: "maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"

**Comment by shirou93** [comment]
@zizebra  flash new firmware and check https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20201127.zip
