### ISSUE TITLE
zigbee2mqtt not forming a mesh network

### ISSUE THREAD

**Issue by kiwijunglist** [Koenkk/zigbee2mqtt#705]
Problem: in mesh graph all devices either connect directly to the co-ordinator or don't have an arrow to anything in the map. However all devices seem to be functioning correctly when reporting status etc.

hass.io version: 0.84.1
zigbee2mqtt version: edge (latest version)

Co-ordinator: cc2531 (x1)
Routers: cc2531 (x2) & xiaomi zigbee plugs (x3)
End devices: mixture of mija & aqara door sensors and occupancy sensors.

Total devices: 22 (incl router / co-ordinator)

Log: https://pastebin.com/KTCgGjWD
Graph: https://pastebin.com/RftGYbGr

Thanks

**Comment by Koenkk** [comment]
It is, but it's just not shown in the networkmap, see #652.
