### ISSUE TITLE
Ading known problems section to 

### ISSUE THREAD

**Issue by shaggyone** [Koenkk/zigbee2mqtt#7050]
The idea is related to https://github.com/Koenkk/zigbee2mqtt.io

## Is your feature request related to a problem? Please describe
Some devices have issues, such as weird behaviour. So, it'd be useful to have such information at one place.

For example. I have 2 https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-LN.html, and 2 https://www.zigbee2mqtt.io/devices/QS-Zigbee-D02-TRIAC-2C-LN.html

I found, that one gang dimmers do not save state on power failure, but two gang dimmer do. I've found that some other people experience the same problem and want to share solution.

## Describe the solution you'd like
I suggest adding a section named "known issues" section to each 

## Describe alternatives you've considered
-

## Additional context
-

**Comment by Koenkk** [comment]
Please create a PR for this by clicking the pencil button here; https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/QS-Zigbee-D02-TRIAC-2C-LN.md
