### ISSUE TITLE
battery_low and tamper never published for SJCGQ11LM

### ISSUE THREAD

**Issue by McGiverGim** [Koenkk/zigbee2mqtt#7067]
## What happened

The SJCGQ11LM sensor (Xiaomi water leak) defines `battery_low` and `tamper` attributes, but it seems they are never published. I think this device does not publish this values, so it seem they must be removed.
Or at least my version does not publish them. I don't know if there are variants and some of them does it.

## What did you expect to happen

This attributes have some value or not exist at all.

## How to reproduce it (minimal and precise)

Look at the UI:
![image](https://user-images.githubusercontent.com/2673520/114568955-e100d680-9c74-11eb-8690-b509eecd29c0.png)
![image](https://user-images.githubusercontent.com/2673520/114569040-f118b600-9c74-11eb-9d57-216c93a1e6a7.png)

## Debug info
Zigbee2MQTT version: Hassio addon 1.18.2-1
Adapter hardware: CC2531
Adapter firmware version: zStack12.20201128

**Comment by VOVAiS** [comment]
I do not agree
the sensor sends data
but sends them only if it finds a leak
![2883B52C-AF02-4AAC-BC32-B78BC5E1BDFF](https://user-images.githubusercontent.com/50547786/115109316-30514a80-9f86-11eb-9c39-9776e0477ce4.png)
![F0E76739-85FF-4371-AFA0-73F78CF692B4](https://user-images.githubusercontent.com/50547786/115109317-33e4d180-9f86-11eb-9a83-3eff1db1f639.png)

**Comment by McGiverGim** [comment]
Ups, I didn't notice it... this is closed, I don't know if @Koenkk will see an close issue. Maybe is better to open a new issue referencing this one.

**Comment by VOVAiS** [comment]
Do not open a new Issue
  I think @Koenkk will see

**Comment by Koenkk** [comment]
@VOVAiS thanks, reverted!
