### ISSUE TITLE
zigbee2mqtt restarting continuously

### ISSUE THREAD

**Issue by pirracas77** [Koenkk/zigbee2mqtt#7070]
## What happened

the daemon restart continuosly. I have solved installing DEV branche.

root@jeedom:/opt/zigbee2mqtt/data/log# sudo systemctl status zigbee2mqtt
● zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-04-13 18:27:58 CEST; 12s ago
 Main PID: 29457 (npm)
    Tasks: 11 (limit: 2346)
   Memory: 31.7M
   CGroup: /system.slice/zigbee2mqtt.service
           └─29457 npm

abr 13 18:28:10 jeedom npm[29457]:     at Object.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/linux.js:2:36)
abr 13 18:28:10 jeedom npm[29457]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
abr 13 18:28:10 jeedom npm[29457]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
abr 13 18:28:10 jeedom npm[29457]: npm ERR! code ELIFECYCLE
abr 13 18:28:10 jeedom npm[29457]: npm ERR! errno 1
abr 13 18:28:10 jeedom npm[29457]: npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
abr 13 18:28:10 jeedom npm[29457]: npm ERR! Exit status 1
abr 13 18:28:10 jeedom npm[29457]: npm ERR!
abr 13 18:28:10 jeedom npm[29457]: npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
abr 13 18:28:10 jeedom npm[29457]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## How to reproduce it (minimal and precise)

reboot linux and the daemon never start after this

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2531
Adapter firmware version: zStack12

**Comment by pbackx** [comment]
I had the same issue after running the update.sh script without activating the Zigbee2mqtt environment.

If you use journalctl you should be able to see the full error message:

`$ journalctl -u zigbee2mqtt.service -f`

I got this one: 

    apr 19 09:47:10 bash[2746]: was compiled against a different Node.js version using
    apr 19 09:47:10 bash[2746]: NODE_MODULE_VERSION 83. This version of Node.js requires
    apr 19 09:47:10 bash[2746]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
    apr 19 09:47:10 bash[2746]: the module (for instance, using `npm rebuild` or `npm install`).
    apr 19 09:47:10 bash[2746]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    apr 19 09:47:10 bash[2746]:     at Module.load (internal/modules/cjs/loader.js:599:32)

The reason for this is that `npm ci` (in update.sh) was run with the wrong version.

Luckily this is easily fixed. First run `source /opt/zigbee2mqtt/bin/activate`. And now rerun the update script. Or just cd into /opt/zigbee2mqtt and run `npm ci`
