### ISSUE TITLE
Is there any way to set the level of precision for temp/humidity sensors?

### ISSUE THREAD

**Issue by mihalski** [Koenkk/zigbee2mqtt#708]
I normally use one decimal point of precision for my temp/humidity sensors and I searched but could not find any way to do this with zigbee2mqtt.

I know I could manually do it in a Home Assistant template but this would prevent the use of MQTT auto-discovery.

Thanks in advance.

P.S. Oh and I set pressure to zero decimal points of precision (ie whole numbers).

**Comment by Koenkk** [comment]
Implemented, see [documentation](https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/configuration/device_specific_configuration.md) on how to use it.

**Comment by mihalski** [comment]
Thank you!

Would it also make sense to have a global config equivalent to the device specific config in the main section of the configuration.yaml for when you always want parameters measured with a particular level of precision (including all future sensors)?

**Comment by mihalski** [comment]
I also noticed that even with precision set to 1 if the value returned by the sensor happens to be a whole number it returns an int rather than a float (ie missing the .0)

**Comment by justmvg** [comment]
I've installed 1.0.0 yesterday and made changes to the configuration.yaml to set the precision to 1 decimal instead of the default of 2. Restarted zigbee2mqt but still receiving data with 2 decimals.
Is there anything else I should change?

**Comment by Koenkk** [comment]
- Precision for whole numbers is not possible in javascript (see https://www.w3schools.com/js/js_numbers.asp)
- Device type specific default can now be set via `device_options` (see https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/configuration/device_specific_configuration.md#changing-device-type-specific-defaults)

**Comment by justmvg** [comment]
> @justmvg checkout the dev branch

Thank you. I managed to make it work with the dev branch.

**Comment by mihalski** [comment]
Thank you so much for implementing device type specific defaults!
Granted, I don't really know what I am talking about and this is based on a quick google search, but couldn't you just use `.toFixed(precision)` where `precision` is a variable containing the number of decimal points of precision desired?

**Comment by Koenkk** [comment]
The problem of `toFixed` is that it returns a string, the values should be kept numerical.

**Comment by mihalski** [comment]
Does it matter when the intended output is a JSON string? Internally it can be numerical, but when being reported as part of a MQTT JSON string it could be considered seperate.

**Comment by mihalski** [comment]
My understanding of MQTT was that value types were inferred from the presentation of the JSON string. But I am about as far from an expert in the field as is possible.

**Comment by Koenkk** [comment]
Yes that's true, but this JSON string can contains string and numerical values.

**Comment by mihalski** [comment]
I guess trying it and seeing what happens is the only ay to be sure.

**Comment by mateuszdrab** [comment]
Hey guys, I'm running the latest version of zigbee2mqtt and after adding the following, I'm still seeing the messages get sent with default precision settings.

`device_options:
  temperature_precision: 1
  humidity_precision: 1
  pressure_precision: 1`

**Comment by Koenkk** [comment]
@mateuszdrab are you using the dev branch?

**Comment by mateuszdrab** [comment]
> @mateuszdrab are you using the dev branch?

I'm on master, makes sense.

**Comment by zerofruchtshake** [comment]
> * Device type specific default can now be set via `device_options` (see https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/configuration/device_specific_configuration.md#changing-device-type-specific-defaults)
The link is not working any more :(

**Comment by Koenkk** [comment]
@zerofruchtshake http://www.zigbee2mqtt.io/configuration/device_specific_configuration.html#changing-device-type-specific-defaults

**Comment by cigas4** [comment]
> 
> 
> @zerofruchtshake http://www.zigbee2mqtt.io/configuration/device_specific_configuration.html#changing-device-type-specific-defaults

Where should I put this:

device_options:
  occupancy_timeout: 130
  temperature_precision: 1

If I put this to HA configuration.yaml, I get error "Component error: device_options - Integration device_options not found."

Also tried HA Configuration - > Customization -> Entitty: Humidity sensor -> add other attribute -> name: humidity_precision value: 1 -> Reboot
But this also does not work.

**Comment by KuChar91** [comment]
> > @zerofruchtshake http://www.zigbee2mqtt.io/configuration/device_specific_configuration.html#changing-device-type-specific-defaults
> 
> Where should I put this:
> 
> device_options:
> occupancy_timeout: 130
> temperature_precision: 1
> 
> If I put this to HA configuration.yaml, I get error "Component error: device_options - Integration device_options not found."
> 
> Also tried HA Configuration - > Customization -> Entitty: Humidity sensor -> add other attribute -> name: humidity_precision value: 1 -> Reboot
> But this also does not work.

Put it in devices.yaml or configuration.yaml (add-on) not HA.

**Comment by settler-als** [comment]
Hello,
i try use this options in configuration zigbee2mqtt (stable and edge):

device_options:
  retain: true
  temperature_precision: 1
  humidity_precision: 1

 temperature_precision: 1 - the option works and it can be seen in the interface lovelace or z2m web ui 
humidity_precision: 1 - this option does not work globally for all sensors.

When i check config in web ui -> Settings -> Raw  :
when I checked the config file in web ui -> Settings -> Raw , i see only:

 "device_options": {
            "temperature_precision": 1
        },

no  "retain: true" and "humidity_precision: 1".

Why?
