### ISSUE TITLE
LED Driver TuYa TS0503B  RGB UNSUPPORTED_ATTRIBUTE when try restore color

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#7088]
## What happened
Zigbee2MQTT:error 2021-04-15 12:55:56: Publish 'get' 'color' to '0x60a423fffe69dc24' failed: 'Error: Read 0x60a423fffe69dc24/1 lightingColorCtrl(["currentX","currentY","enhancedCurrentHue","currentSaturation"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
## What did you expect to happen
Restore color on z2m UI
## Debug info
Zigbee2MQTT version: 1.18.2-1
Adapter hardware: CC2652RB
Adapter firmware version: CC2652RB_coordinator_20210120.zip

https://www.zigbee2mqtt.io/devices/TS0503B.html#tuya-ts0503b

**Comment by shirou93** [comment]
@sjorge this is same issue as: https://github.com/Koenkk/zigbee2mqtt/issues/6921?

**Comment by sjorge** [comment]
> @sjorge this is same issue as: #6921?

Likely, can you try the same read as in #6921 ?

**Comment by shirou93** [comment]
Same log when i try restore in ui

![image](https://user-images.githubusercontent.com/59237288/114861853-1c72e080-9dee-11eb-8cfb-5fee7202b819.png)

**Comment by sjorge** [comment]
I mean the manual read of only the one attribute as mentioned here https://github.com/Koenkk/zigbee2mqtt/issues/6921#issuecomment-812929925

**Comment by shirou93** [comment]
![image](https://user-images.githubusercontent.com/59237288/114868843-a626ac00-9df6-11eb-8718-83f2fd14a869.png)

**Comment by sjorge** [comment]
PR opened to disable enhancedHue for this device.

**Comment by sjorge** [comment]
Merged

**Comment by shirou93** [comment]
@sjorge  TuYa TS0505B https://www.zigbee2mqtt.io/devices/TS0505B.html#tuya-ts0505b same issue :)
