### ISSUE TITLE
WIKI questions

### ISSUE THREAD

**Issue by jwillmer** [Koenkk/zigbee2mqtt#709]
- How can I propose wiki changes now that the wiki is hidden in GitHub?
- Can you update the GitHub page since there are no links to the menu. It is messier then before - just looks nicer.

**Comment by Koenkk** [comment]
Pages source is here: https://github.com/Koenkk/zigbee2mqtt/tree/master/docs 

You can change it by opening a PR.

**Comment by ryanbeaton** [comment]
Now in:

https://github.com/Koenkk/zigbee2mqtt.io
