### ISSUE TITLE
No converter available for 'local_temperature' () TS0601

### ISSUE THREAD

**Issue by copystring** [Koenkk/zigbee2mqtt#7096]
Hi,

sending {"local_temperature": ""} to my TS0601_thermostat results in: No converter available for 'local_temperature' ()

Help? :)

The thermostat does send the temperature on it's own but it is not possible to directly get the current value via /get
Looking at https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html this should work fine.

My exact model: _TZE200_ckud7u2l

Zigbee2MQTT version: 1.18.2-dev commit: 93c0a8a
Adapter hardware: zzh
Adapter firmware version: 20210120

![image](https://user-images.githubusercontent.com/1298861/115001496-fad43080-9ea3-11eb-893f-0831e682c629.png)

**Comment by copystring** [comment]
Still an issue even with latest version.

**Comment by Koenkk** [comment]
`/get` on `local_temperature` is not supported for TuYa devices, updated the docs.
