### ISSUE TITLE
Philips Hue Garnea - Unsupported Error

### ISSUE THREAD

**Issue by beasthouse-au** [Koenkk/zigbee2mqtt#7113]
Trying to pair my Philips Hue Garnea lights with z2m. A couple have worked, however the others are saying that they are unsupported, even though the [documentation would indicate otherwise](https://www.zigbee2mqtt.io/devices/5110131H5.html).

I get the following error code in the logs:

`Failed to interview '0x0017880108d4474b', device has not successfully been paired`

Then it does appear in devices:

https://imgur.com/pUwoF1Z

https://imgur.com/xVgKv5d

All devices were updated in the Hue app prior to bringing across to z2m

Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210120

**Comment by danieledwardgeorgehitchcock** [comment]
Could you capture a debug log during one of the failed devices pairing, and post it up here?

**Comment by beasthouse-au** [comment]
Waited 24 hours, tried again and they worked fine. No idea what caused it, go Zigbee!
