### ISSUE TITLE
Aqara vibration sensor -  add command

### ISSUE THREAD

**Issue by jerome6994** [Koenkk/zigbee2mqtt#7135]
Hello

on this aqara vibration sensor there are x, y and z angle digital info control available.
Can you reassemble them natively so like the other commands please

Today the alternative is to enter in manual the commands angle_x, angle_y, angle_z

Thank you in advance for your changes

```
{
    "battery": 10,
    "device": {
        "applicationVersion": 8,
        "friendlyName": "0x00158d0003132788",
        "ieeeAddr": "0x00158d0003132788",
        "manufacturerID": 4151,
        "manufacturerName": "LUMI",
        "model": "DJT11LM",
        "networkAddress": 47581,
        "powerSource": "Battery",
        "type": "EndDevice"
    },
    "linkquality": 22,
    "voltage": 2535,
    "action": "vibration",
    "angle": 64,
    "angle_x": 1,
    "angle_x_absolute": 89,
    "angle_y": -1,
    "angle_y_absolute": 91,
    "angle_z": 88
}
```

**Comment by mguyard** [comment]
Yes i also use these informations to control my garage position.
Si it can be very interesting to expose these informations
