### ISSUE TITLE
Smart9 Smoke Detector

### ISSUE THREAD

**Issue by chrisrock1984** [Koenkk/zigbee2mqtt#7136]
## Information about the device + link
https://de.aliexpress.com/item/1005001383340876.html?spm=a2g0s.9042311.0.0.27424c4dU1zRb8

## data/database.db entry of the device
{"id":77,"type":"EndDevice","ieeeAddr":"0x842e14fffefxxxxx","nwkAddr":61489,"manufId":0,"manufName":"_TYST11_t5p1vj8r","powerSource":"Battery","modelId":"5p1vj8r\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,3],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"5p1vj8r\u0000","manufacturerName":"_TYST11_t5p1vj8r","powerSource":3,"zclVersion":3,"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"20180727"}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001caxxxxx","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":73,"stackVersion":0,"hwVersion":1,"dateCode":"20180727","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1618857051940}

Hi,

I was able to add the device to zigbee2mqtt but failing now to apply the correct converters. It's a Tuya device and therefore not straight forward to be added easy - maybe only for me.

I created an external converter, so that zigbee2mqtt recognizes the device as "supported". Please see below:

`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

const device = {
    zigbeeModel: ['5p1vj8r'],
    model: '5p1vj8r',
    vendor: 'Smart9',
    description: 'Smart9 Smoke',
    fromZigbee: [
		fz.tuya_data_point_test],
    toZigbee: [],
    exposes: [],
	meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint, logger) => {
		const endpoint = device.getEndpoint(1);
		await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg']);
		try {
			await reporting.batteryPercentageRemaining(endpoint);
		} catch (error) {/* Fails for some: https://github.com/Koenkk/zigbee2mqtt/issues/6313 */}
	},
};

module.exports = device;`

And here is the log I get after adding the device and pressing the button on the smoke alarm
`Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":1,"fn":0,"status":0,"transid":8}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":14,"fn":0,"status":0,"transid":9}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"appVersion":73}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20180727"}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Info Successfully interviewed '0x842e14fffefxxxxx', device has successfully been paired
Info Device '0x842e14fffefxxxxx' is supported, identified as: Smart9 Smart9 Smoke (5p1vj8r)
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Smart9 Smoke","exposes":[],"model":"5p1vj8r","supports_ota":false,"vendor":"Smart9"},"friendly_name":"0x842e14fffefxxxxx","ieee_address":"0x842e14fffefxxxxx","status":"successful","supported":true},"type":"device_interview"}'
Info Configuring '0x842e14fffefxxxxx'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Smart9 Smoke","friendly_name":"0x842e14fffefxxxxx","model":"5p1vj8r","supported":true,"vendor":"Smart9"},"type":"pairing"}'
Debug Received MQTT message on 'zigbee2mqtt/bridge/config/device_options' with data '{"friendly_name":"0x842e14fffefxxxxx","options":{"retain":true}}'
Info Changed device specific options of '0x842e14fffefxxxxx' ({"retain":true})
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0],"type":"Buffer"},"datatype":4,"dp":1,"fn":0,"status":0,"transid":10}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Debug Received Zigbee message from '0x842e14fffefxxxxx', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":1,"fn":0,"status":0,"transid":11}' from endpoint 1 with groupID 0
Error Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined at /app/lib/extension/receive.js:117:42 at Array.filter (<anonymous>) at Receive.onZigbeeEvent (/app/lib/extension/receive.js:116:65) at Controller.callExtensionMethod (/app/lib/controller.js:388:44))
Info Successfully configured '0x842e14fffefxxxxx'`

Any help is appreciated!!

Thx

**Comment by chrisrock1984** [comment]
I was able to get the smoke sensor running on a non docker zigbee2mqtt installation using the information from #7029
Everything is working except the battery low warning.
Can this device now be added? Can someone help me with the battery low information?

CONVERTER used -> 
	tuya_smoke: {
        cluster: 'manuSpecificTuya',
        type: ['commandGetData'],
        convert: (model, msg, publish, options, meta) => {
            const dp = msg.data.dp;
            const value = tuya.getDataValue(msg.data.datatype, msg.data.data);

            switch (dp) {
            case tuya.dataPoints.state:
                return {smoke: value === 0 ? true : false};
            default:
                meta.logger.warn(`zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #${
                    dp} with data ${JSON.stringify(msg.data)}`);
            }
        }
    },




DEVICE ->
 	{
		zigbeeModel: ['5p1vj8r'],
		model: '5p1vj8r',
		vendor: 'Smart9',
        description: 'smoke sensor',
        fromZigbee: [fz.tuya_smoke,
            fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
            fz.tuya_data_point_dump], // This is a debug converter, it will be described in the next part
        toZigbee: [tz.tuya_data_point_test], // Another debug converter
        meta: {
            configureKey: 1,
        },
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
        },
        exposes: [e.smoke(), e.battery_low()]
		
	},

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by chrisrock1984** [comment]
Thank you very much!!
