### ISSUE TITLE
Moes (Tuya) TS011F Power On behavior

### ISSUE THREAD

**Issue by emc2cube** [Koenkk/zigbee2mqtt#7154]
As supported for other devices (ex: https://github.com/Koenkk/zigbee2mqtt/issues/5213 ) could Power On behaviour be added for these devices too (Moes MS-104Z / TS011F) ?

It seems this is officially supported using the Tuya App / bridge, as described on  https://www.aliexpress.com/item/1005001605349292.html

Happy to help / test on my side too.

Thanks!

**Comment by codeitnos** [comment]
Yes, I would also like to add this device. Only I have a slightly different look, but the code TS011F is exactly the same.
https://aliexpress.ru/item/1005002344798281.html

**Comment by emc2cube** [comment]
still interested in this if possible to implement  ;)
