### ISSUE TITLE
EcoDim does not honour transition time

### ISSUE THREAD

**Issue by maxjos** [Koenkk/zigbee2mqtt#7164]
## What happened
EcoDim.07 dimmer immediately switch to target brightness or on/off state without honouring the transition time both if defined via device or if sent via mqtt payload.

## What did you expect to happen
brightness to increase/decrease over time as per defined by transition time

## How to reproduce it (minimal and precise)
send mqtt payload e.g. '{"brightness":155,"transition":10}'
or
set 'transition: 10' on the device in configuration.yaml

## Debug info
Device: EcoDim.07
Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2531
Adapter firmware version: 20201127

**Comment by Koenkk** [comment]
If this doesn't work your bulb doesn't support it.

**Comment by jelmerkk** [comment]
I inquired to the manufacturer, and they are condidering support in a future OTA update

**Comment by dvandonkelaar** [comment]
The EcoDim isn't supported in zigbee2mqtt OTA, also the manufacutrers documentation do not mention OTA.
My setup contains multiple EcoDim.07 dimmers and the documentation does not mention OTA either.

Did they explain how to apply this OTA update?

**Comment by jelmerkk** [comment]
They are considering enabling the OTA channel, it would then first need to be supported by Z2M ofc. The hardware does support it, so it will respond to future OTA commands
