### ISSUE TITLE
Cannot pair any device since yesterday (CC2652R)

### ISSUE THREAD

**Issue by plantoschka** [Koenkk/zigbee2mqtt#7165]
## What happened
Yesterday suddenly my Aqara relais stopped working and with this some of my sensors also stopped working because the device acted as a router. I then tried to repair it within Zigbee2MQTT but was not successful. The device paired fine with my Aqara Hub. Today I removed a Aqara button and tried to repair it and this also does not work. Both devices also disappeared from the device list in Zigbee2MQTT.
Tried to pair a new door & windows sensor right next to the Adapter and this also did not work. I don't see any message in my log file. Existing device in my network work fine.

I always enable permit join and I've read the FAQ and tried to disconnect my device for a couple of minutes, restart Zigbee2MQTT, reboot my raspberry pi. For me it seems like permit join does not work correctly anymore.

## What did you expect to happen
Pairing should work

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210120

**Comment by plantoschka** [comment]
I've also just tried to reflash the adapter. Unfortunately this did not help.

**Comment by lamboid** [comment]
same hear. 
Two aqara motion sensors dropped and cannot rejoin.
Tried battery out on the sensors (worked before) but nothing.
Logs show nothing about devices trying to join.
I have a few new sensors in the post so will try them once they arrive.

**Comment by plantoschka** [comment]
So I had to setup everything from scratch and then I was able to pair devices again. Not 100% sure what was the issue but it might be related to the Xiaomi LLKZMK11LM which acted as a router.

**Comment by lamboid** [comment]
I was playing about and found I had almost 500 logs file.
Cleared down to last 7 days and was able to reconnect one of the sensors straight away. Will do the other one when I can find a step ladder!!!
Quick daily cron job to clear down files older than 7 days and fingers crossed we are good to go.
