### ISSUE TITLE
Support for Wiser (Schneider Electric) MEG5011-0001

### ISSUE THREAD

**Issue by DjFabFab** [Koenkk/zigbee2mqtt#7170]
## Information about the device + link
Reported Zigbee Model: PUCK/SWITCH/1
Vendor P/N: MEG5011-0001
[https://www.se.com/de/de/product/MEG5011-0001/wiser-schaltaktor-1fach-up/](url)

This device should be able to set and get it's on/off state.

## data/database.db entry of the device
`{"id":13,"type":"Router","ieeeAddr":"0x000d6ffffeb3dee8","nwkAddr":64343,"manufId":4190,"manufName":"Schneider Electric","powerSource":"Mains (single phase)","modelId":"PUCK/SWITCH/1","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"PUCK/SWITCH/1","manufacturerName":"Schneider Electric","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":5,"hwVersion":1,"dateCode":"","swBuildId":"001.000.009 R"}},"genOnOff":{"attributes":{"onOff":1}},"haDiagnostic":{"attributes":{"lastMessageLqi":200,"lastMessageRssi":-50}}},"binds":[{"cluster":7,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1},{"cluster":2821,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1},{"cluster":25,"type":"endpoint","deviceIeeeAddress":"0x00124b001cd483ef","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":5,"hwVersion":1,"dateCode":"","swBuildId":"001.000.009 R","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1619122047090}`

## Description
Hey!

First of all, I really like your hard work for supporting many different devices and vendors for improving the experience with zigbee devices.
Discovering IoT and it's possibilities is so cool and a lot of fun to me.
**Thank You!** 😊

I'm new to Homeassistant with zigbee2mqtt and only added some supported TRVs by Schneider Electric using the WebUI yet.
So I am not very experienced in scripting/working with YAML and .js.
However, i've got a MEG5011-0001 which i want to use for switching my light on and off but is currently not supported.

My Homeassistant setup is build up of a Raspberry Pi4 running Debian and Home Assistant Supervised.

Following your instructions at
[https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html](url)
and
[https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/zigbee2mqtt/DOCS.md#adding-support-for-new-devices](url)
I paired my device succesfully and tried to edit the devices.js file inside the container to add my device to mqtt.
Unfortunately this file seems to be overridden when restarting the Zigbee2MQTT docker container.

**So how do I add this DiY devices to my configuration?
How does the config needs to look like if i want to send on/off commands to my device?**

Right now i am a bit confused and i don't want to mess things up, so I am asking for your assistance.

(BTW: Your documention looks like its missing the "Hassio section" (?):
[https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#hassio-addon](url))

## Additional Info

Zigbee2MQTT receives debug messages like
`Received Zigbee message from 'Light Fabian', type 'commandQueryNextImageRequest', cluster 'genOta', data 
'{"fieldControl":1,"fileVersion":16779775,"imageType":13,"manufacturerCode":4190}' from endpoint 1 with groupID 0`
and
`Received Zigbee message from 'Light Fabian', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0`

![grafik](https://user-images.githubusercontent.com/68521979/115786100-a60f4900-a3c0-11eb-9d7e-ddc18a586272.png)

**Comment by rindlerblabla** [comment]
Would be much appreciated from me as well. Have the Schneider PUCK/DIMMER/1 and NHROTARY/DIMMER/1 still connected to Homey , but would like to move them and the switches to z2m as well. Could provide an interview (similar information as above) from Homey, but haven't managed to do the same with z2m yet.
