### ISSUE TITLE
Aqara Vibration Sensor reporting as unsupported even though the model number is listed as a supported device

### ISSUE THREAD

**Issue by vatsanvasu** [Koenkk/zigbee2mqtt#7173]
## What happened
Aqara Vibration sensor model ID : 22635-DJT11LM is listed as supported but comes up as unsupported in the web UI

## What did you expect to happen
Expected it to be a supported device

## How to reproduce it (minimal and precise)
![image](https://user-images.githubusercontent.com/29559478/115797894-53617b80-a418-11eb-8d0b-e062a17381c8.png)

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210120

**Comment by McGiverGim** [comment]
I had this problem sometimes, but it is fixed joining again the device. Have you tried to join it again?

**Comment by vatsanvasu** [comment]
yes...still said unsupported.

**Comment by vatsanvasu** [comment]
Hi Miguel,

I kept trying and after a few tries it worked.
