### ISSUE TITLE
Broken link: Alternate flashing method

### ISSUE THREAD

**Issue by abhaysbharadwaj** [Koenkk/zigbee2mqtt#718]
Hello,
In this URL: https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/getting_started/flashing_the_cc2531.md

This URL for "Alternative Firmware Flashing" Seems to be broken: https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/useful_information/alternative-firmware-flashing-methods.md

https://koenkk.github.io/zigbee2mqtt/useful_information/alternative-firmware-flashing-methods.md

I had checked it a few days back and it was working. Can you kindly look into this and help me out.

**Comment by Iv4nS** [comment]
I think they are trying to move the docs to Github Pages but this is accessible at the moment: https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/information/alternative_flashing_methods.md

**Comment by Koenkk** [comment]
Thanks, fixed!

**Comment by timdonovanuk** [comment]
They are all broken again :(

**Comment by Koenkk** [comment]
Documentation has been moved to https://www.zigbee2mqtt.io

**Comment by FrancYescO** [comment]
If someone interested on flashing with RPi this method without CCDebbuger is very easy https://notenoughtech.com/home-automation/flashing-cc2531-without-cc-debugger/
