### ISSUE TITLE
1.18.2 has high cpu usage

### ISSUE THREAD

**Issue by hfcheng66** [Koenkk/zigbee2mqtt#7194]
## What happened

Running koenkk/zigbee2mqtt image under ubuntu 18.4

After upgrade to 1.18.2, noticed the cpu usage is high, constantly around 10%.
Revert back to 1.17.1, the cpu usage is around 1%

Using Conbee II stick.
Have 7 zigbee bulbs and 4 xiaomi buttons.

## Debug info
Zigbee2MQTT version: 1.18.2
Adapter hardware: Conbee II

**Comment by Koenkk** [comment]
Duplicate of #7004
