### ISSUE TITLE
Ikea Trådfri motion sensor (E1745) battery shows `?` in "Devices", but correct value in "Exposes"

### ISSUE THREAD

**Issue by davidstosik** [Koenkk/zigbee2mqtt#7200]
## What happened

On the Zigbee2MQTT dashboard, in the devices list, the power level of my IKEA Trådfri motion sensor (E1745) shows a question mark (`?`).

<img width="500px" src="https://user-images.githubusercontent.com/816901/115978567-3913d300-a5bb-11eb-88d8-718dccab84a7.png" />

The device's screen displays the same question mark in "power source".

<img width="500px" src="https://user-images.githubusercontent.com/816901/115978589-63fe2700-a5bb-11eb-883d-d7029ea63323.png" />

However, the device's "exposes" screen displays a numeric percentage in "battery".

<img width="500px" src="https://user-images.githubusercontent.com/816901/115978614-8db74e00-a5bb-11eb-886a-5953bfe756f1.png" />

## What did you expect to happen

I would expect the "devices" screen and the "about" screen to display the correct battery level.

## How to reproduce it (minimal and precise)

Not sure... 🤔 
I just set Zigbee2MQTT a few days ago and only paired 3 devices so far. I tried restarting Zigbee2MQTT, I tried removing the sensor's batteries for 10 seconds, I'd even tried waiting for more than 24 hours before that.

## Debug info

- Zigbee2MQTT 1.18.2-1 in Home Assistant's supervisor
- Home Assistant 2021.4.5 running in a VM on macOS
- CC2531 coordinator with firmware 20201127
- [log.txt](https://gist.github.com/davidstosik/d2d6db515dd76eb7a5b527fa50c458bc)
- I can try and provide zigbee-herdsman logs if necessary

**Comment by Koenkk** [comment]
Fixed. 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

After updating to the dev branch (or wait for next release on 1 May). Wakeup the device by triggering it and right after that click the yellow refresh icon on the device page, then the problem should be fixed.

**Comment by davidstosik** [comment]
Thank you!
