### ISSUE TITLE
Prevent OTA for individual devices

### ISSUE THREAD

**Issue by 00pi** [Koenkk/zigbee2mqtt#7201]
## Is your feature request related to a problem? Please describe
Unfortunately, firmware updates do sometimes bring unwanted (in this case: undocumented) side effects. Refer #6403

## Describe the solution you'd like
provide a device specific configuration option to exclude this particular device from OTA in order to prevent stupid me from updating it manually

**Comment by timstanley1985** [comment]
Hi, was this feature request ever implemented?  I would like to exclude some of my Tradfri switches from OTA - #7716

**Comment by shbatm** [comment]
Would also like this implemented. My 2 of my OSRAM/Sylvania bulbs turn on by themselves when they check for OTA updates.
