### ISSUE TITLE
Legrand 741811 is wrong identified as Legrand 067775

### ISSUE THREAD

**Issue by pirracas77** [Koenkk/zigbee2mqtt#7202]
## Information about the device + link
Legrand 741811 is identified as Legrand 067775 but it is not the same device.
`info  2021-04-24 16:50:16: Device '0x000XXXXXXXXXXXX' is supported, identified as: Legrand Power socket with power consumption monitoring (067775)`

`info  2021-04-24 16:50:16: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Power socket with power consumption monitoring","exposes":[{"features":[{"access":7,"description":"On/off state of
the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"act
ion","type":"enum","values":["identify"]},{"access":1,"description":"Instantaneous measured power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":1,"description":"Measured electrical potential value","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":1,"description":"Instantaneous measured electrical current","name":"current","property":"current","type":"numeric","unit":"A"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"067775","supports_ota":false,"vendor":"Legrand"},"friendly_name":"0x000XXXXXXXX","ieee_address":"0x000XXXXXXXXX","status":"successful","supported":true},"type":"device_interview"}'`

It is almost the same as Legrand 067775

https://www.grupolegrand.es/e-catalogo/vista-producto.php?product=741811

The information about the firmware is showed weird.

![image](https://user-images.githubusercontent.com/18216098/115990631-89436300-a5c4-11eb-9a01-7d5297d5262d.png)

It seems that this device doesnt expose Current  and Voltage.

## data/database.db entry of the device
..
`{"id":40,"type":"Router","ieeeAddr":"0x000XXXXXXXXX","nwkAddr":48488,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Mains (single phase)","modelId":" Connected outlet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,6,5,64513,2820],"outClusterList":[0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" Connected outlet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":1,"zclVersion":2,"appVersion":0,"stackVersion":64,"hwVersion":1,"dateCode":" \u000020181218\u0000\u0000\u0000\u0000\u0000","swBuildId":"016\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!"}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":0,"acVoltageDivisor":0,"acCurrentMultiplier":0,"acCurrentDivisor":0,"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0}},"genIdentify":{"attributes":{"identifyTime":60}}},"binds":[{"cluster":3,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d98060","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d98060","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d98060","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":2820,"attrId":1291,"minRepIntval":5,"maxRepIntval":3600,"repChange":1}],"meta":{}}},"appVersion":0,"stackVersion":64,"hwVersion":1,"dateCode":" \u000020181218\u0000\u0000\u0000\u0000\u0000","swBuildId":"016\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 \u0002\u0000\u0001\u0000 \u0002\u0000\u0002\u0000!\u0012\u0000\u0000\u0000\u0000��\u0003\u0000\u0010\u0002\u0001\u0004\u0000\u0018\u0002\u0000��!","zclVersion":2,"interviewCompleted":true,"meta":{"configured":3},"lastSeen":1619347642836}
`

**Comment by pirracas77** [comment]
.

**Comment by Koenkk** [comment]
These device use the exactly same modelID, therefore we cannot distinguish them . Changed the model to `067775/741811`.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
