### ISSUE TITLE
[Supported adapters] RF TO USB CC2530 + CC2591

### ISSUE THREAD

**Issue by Krolik1988** [Koenkk/zigbee2mqtt#7236]
Hello, [THIS](https://www.aliexpress.com/item/1005001587860129.html?spm=a2g0s.9042311.0.0.3d2b4c4dABT61F) dongle as well works with your plugin. Can be added to [Supported adapters](https://www.zigbee2mqtt.io/information/supported_adapters.html). Only here is one moment, it's how you are installing pin connector. It must be installed "upside down"

![20210428_100804](https://user-images.githubusercontent.com/52775223/116395325-44b60280-a824-11eb-93b1-8215290fc0a7.jpg)

Checked it wit Aquara door sensor. Receiving msgs from it. 

Have a good day.

**Comment by Koenkk** [comment]
Added, thanks!
