### ISSUE TITLE
Network map

### ISSUE THREAD

**Issue by timota** [Koenkk/zigbee2mqtt#725]
Hi, 

previously, before wiki changed - there was manual how to use(configure) Network MAP for Homeassistant. 
Now it has been removed. Can it be moved back to a new wiki please. 

Thanks

**Comment by JLFN** [comment]
Here you go.
https://github.com/JLFN/zigbee2mqtt/blob/master/docs/integration/home_assistant.md

**Comment by timota** [comment]
great, many thanks
