### ISSUE TITLE
RTCGQ13LM can`t change settings

### ISSUE THREAD

**Issue by satedone** [Koenkk/zigbee2mqtt#7255]
My device Aqara high precision motion sensor RTCGQ13LM connected fine and works in zigbee2mqtt but can't change settings.
I've tried changing motion_sensitivity and occupancy_timeout.
An error is displayed in the logs.

`error Publish 'set' 'motion_sensitivity' to 'motion_sensor' failed: 'Error: Write 0x54ef441000023819 / 1 aqaraOpple ({"268": {"value": 3, "type": 32}}, {"timeout": 10000, "disableResponse": false, "disableRecovery": false, "disableDefaultResponse": true, "direction": 0, "srcEndpoint": null, "reservedBits": 0, "manufacturerCode": 4447, "transactionSequenceNumber": null, "writeUndiv ": false}) failed (Timeout - 33564 - 1 - 54 - 64704 - 4 after 10000ms) ' `

**Comment by Koenkk** [comment]
Probably need to wake it up right before sending the command.

**Comment by satedone** [comment]
Thanks for the answer. Unfortunately, this does not work.

**Comment by satedone** [comment]
> 
> 
> Probably need to wake it up right before sending the command.

You were right. To accept the change in settings, you just need to confirm it by pressing the button. Everything worked out. Thank you
