### ISSUE TITLE
After update to 1.18.3 : message Tamper to dashboard frontend

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#7290]
Hello, I have 28 zigbee devices but since the update to 1.18.3 I have a Tamper message under the frontend dashboard on my Xiaomi SJCGQ11LM and heiman smoke detector HS1SA devices (see the photo).

![dashboard](https://user-images.githubusercontent.com/55591810/116815973-65ea5c00-ab60-11eb-8393-22d00a5da06f.jpg)

In the device menu it's ok:
![devices](https://user-images.githubusercontent.com/55591810/116815976-67b41f80-ab60-11eb-9818-5d4eacdc0658.jpg)
![dev2](https://user-images.githubusercontent.com/55591810/116815991-7ac6ef80-ab60-11eb-8e06-ae6e4530d69f.jpg)

Rapsberry pi4
Zigbee2MQTT version: 1.18.3
Adapter hardware: Conbee II
Adapter firmware version: the last

**Comment by Koenkk** [comment]
@VOVAiS @McGiverGim does the tamper provide any meaningful value or can it be removed?

**Comment by McGiverGim** [comment]
I can't say. I don't use it for nothing. If you want that I do some test please tell me.

**Comment by Koenkk** [comment]
@McGiverGim what value do you currently have for `tamper`? And does it change when e.g. removing the battery cover?

**Comment by McGiverGim** [comment]
I've a N/A for the water leak sensor, and clear for the smoke sensor. I will try tomorrow to remove the battery cover.

**Comment by McGiverGim** [comment]
I've tried to remove the battery cover from the Xiaomi Smoke sensor and the Xiaomi water leek. I've not seen any change in the `tamper` attribute for any of them. I don't know what need to happen to change.

**Comment by Koenkk** [comment]
@McGiverGim thanks for checking, I was already expecting this since tamper makes no sense for this device.

Removed the tamper now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
