### ISSUE TITLE
Danalock V3-BTZBE support

### ISSUE THREAD

**Issue by Jopand** [Koenkk/zigbee2mqtt#7350]
I know the Danalock V3-BTZB is supported. However I got a replacement with a different model name: 
V3-BTZBE.

It shows up as an unsupported device, and I know, that I'm supposed try and add it myself, however:

I tried to shut down my zigbee2mqtt docker and open the db. I found the V3-BTZBE and simply removed the trailing 'E' 2 places in that line. Started up zigbee2mqtt again at it all works fine. So maybe it would make sense for you to use the same implementation that you have for V3-BTZB??

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
