### ISSUE TITLE
OW-ZSL1 Owyean RGBCCT 5W GU10 Bulb

### ISSUE THREAD

**Issue by smoke0leg** [Koenkk/zigbee2mqtt#7351]
Hello.
I tying connect Owyean RGBCCT 5W GU10 Bulb with Home Assistant. https://zigbee.blakadder.com/Owyean_OW-ZSL1.html
When I pair with stick zigbee cc2531 zigbee2mqtt assistant show me 

![Снимок экрана 2021-05-05 в 11 57 10](https://user-images.githubusercontent.com/72770522/117118138-180c6880-ad99-11eb-9ac0-e5bc5793085d.png)
But in home assistant I see only link quality with unknown status. 

![Снимок экрана 2021-05-05 в 12 01 03](https://user-images.githubusercontent.com/72770522/117118907-05466380-ad9a-11eb-8bd9-d482579aacf8.png)

Maybe some body have any ideas?

**Comment by smoke0leg** [comment]
![Снимок экрана 2021-05-05 в 13 09 17](https://user-images.githubusercontent.com/72770522/117126270-34ad9e00-ada3-11eb-8d5c-954a16a82790.png)

Logger: homeassistant.util.logging
Source: util/logging.py:99 
First occurred: 12:32:20 PM (1 occurrences) 
Last logged: 12:32:20 PM

Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'brightness': True, 'brightness_scale': 254, 'color_mode': True, 'command_topic': 'zigbee2mqtt/sidelight_1/set', 'device': {'identifiers': ['zigbee2mqtt_0x00124b0023442650'], 'manufacturer': 'Lonsonho', 'model': 'Zigbee 3.0 LED-bulb, RGBW LED (ZB-RGBCW)', 'name': 'sidelight_1', 'sw_version': 'Zigbee2MQTT 1.18.3-dev'}, 'json_attributes_topic': 'zigbee2mqtt/sidelight_1', 'max_mireds': 370, 'min_mireds': 153, 'name': 'sidelight_1', 'schema': 'json', 'state_topic': 'zigbee2mqtt/sidelight_1', 'supported_color_modes': ['xy', 'color_temp'], 'unique_id': '0x00124b0023442650_light_zigbee2mqtt', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 152, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 25, in validate_mqtt_light return schemas[value[CONF_SCHEMA]](value) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['color_mode']

**Comment by Koenkk** [comment]
You need to be at least on Home Assistant version 2021.4.5 (https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.18.3)

**Comment by smoke0leg** [comment]
> You need to be at least on Home Assistant version 2021.4.5 (https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.18.3)

Thank you) Was a :stable version, but after I changed to latest it start working
