### ISSUE TITLE
Xiaomi Aqara Door Sensor Keeps showing on UI even when Hidden

### ISSUE THREAD

**Issue by jonaspaulo** [Koenkk/zigbee2mqtt#736]
- Latest version of zigbee2mqtt being used (1.0.1) with latest CC2530 fw
- On the latest HA update 0.84.5 one of the Xiaomi Sensors (Aqara door contact) keeps appearing on the frontend dashboard after a restart of HA, despite the fact that I have a customize option to keep it hidden. The only way to re-hide it again (and that only lasts until the next restart) is to remove the hide from UI option and add it again.

**Comment by Koenkk** [comment]
Isn't this an home assistant issue?
