### ISSUE TITLE
Add support for nodejs 16.x

### ISSUE THREAD

**Issue by buckket** [Koenkk/zigbee2mqtt#7378]
Hi, I’m packaging z2m for Arch Linux which now ships nodejs 16.x per default.

z2m’s package.json pins node versions 10.x - 15.x, which leads to warnings/error messages.

> Zigbee2MQTT requires node version ^10 || ^12 || ^14 || ^15, you are running v16.0.0!
Zigbee2MQTT:error: Error while starting zigbee-herdsman
Zigbee2MQTT:error: Failed to start zigbee

**Comment by Koenkk** [comment]
Already done in https://github.com/Koenkk/zigbee2mqtt/pull/7297 (available in the dev branch). (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
