### ISSUE TITLE
Disable zigbee router function 

### ISSUE THREAD

**Issue by kwetnico** [Koenkk/zigbee2mqtt#7384]
Hello,

I have HEIMAN HS2WD-E  Siren on my coordinator Conbee.
I regularly have LQI errors with my siren under z2m.
Is it possible to deactivate the router function (under frontend or other) for this device? If yes, how ?

Thank you

Rapsberry pi4
Zigbee2MQTT version: 1.18.3
Adapter hardware: Conbee II
Adapter firmware version: the last

**Comment by Koenkk** [comment]
No this is not possible, this would require a different firmware on the siren.

**Comment by sMartjeB** [comment]
I run zigbee at a raspberry and in the past I managed to modify the database file as discussed here:
[https://github.com/Koenkk/zigbee2mqtt/issues/2380](url)

changed the type from 'Router' to 'EndDevice' in the database.db file

I did work, but since I changed the coordinator, I'm not able to change and keep the change.

Isn't there a way to manipulate a device file so a device won't use the router function?

**Comment by Koenkk** [comment]
> Isn't there a way to manipulate a device file so a device won't use the router function?

You cannot, changing this line won't affect the functionality of the device. The only way to make it a router is to flash a custom firmware on your router.

**Comment by sMartjeB** [comment]
Like TS I would like to disable the router function of that "enddevice" with router function.
Zigbee should not pass messages for other devices through that special "router-disabled" device.


I my case it is a TS0121_plug which normally acts a a router, but interrupts the commands to my other devices.
When I had that database file modified, zigbee2mqtt showed the TS0121_plug as enddevice and all devices ran perfectly.

The firmware was not changed.

Can't we modify for example /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices.js and disable the router part of the device?
Or which file(s) should we modify?

**Comment by Koenkk** [comment]
@sMartjeB this is not how it works, we can't change the device from a router to end device from Zigbee2MQTT

**Comment by sctale** [comment]
@sMartjeB Hello, I have the same requirement for changing router to enddevice. Do you mind to share the way that you used to change the database.db, I tried, but failed.

**Comment by sctale** [comment]
@Koenkk Hello Super Koenkk, thanks a lot for your z2m addon, it is amazing. I have another thought, if there is a way to stop the enddevices connecting to the router automaticly when the device type can't be changed?
