### ISSUE TITLE
Attempting to unbind an IKEA dimmer controller from a Hue bulb fails.

### ISSUE THREAD

**Issue by gaussey** [Koenkk/zigbee2mqtt#7390]
Attempting to unbind an IKEA IKEA ICTC-G-1 from a HUE bulb fails with :

error 2021-05-08 02:33:24: Nothing to unbind from 'ikeadimmer1' to 'front'
info  2021-05-08 02:33:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"from":"ikeadimmer1","to":"front"},"type":"device_unbind_failed"}'
info  2021-05-08 02:33:24: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/unbind', payload '{"data":{"clusters":[],"failed":[],"from":"ikeadimmer1/1","to":"front/11"},"error":"Nothing to unbind","status":"error","transaction":"7gzhd-1"}'
error 2021-05-08 02:33:24: Nothing to unbind

The reason for unbinding is that it’s controlling the brightness on the light and so interfering with my automations.

## What did you expect to happen
Unbinding 
## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by MattWestb** [comment]
All IKEA controlling devices can only being bonded to groups. 
Is you trying unbinding it from the light or the one group that the light is member of ?
