### ISSUE TITLE
Readme for device missing pairing info (Philips Hue dimmer v2 929002398602)

### ISSUE THREAD

**Issue by 877dev** [Koenkk/zigbee2mqtt#7395]
Hi,

Just a simple bit of missing info in the docs:.

https://www.zigbee2mqtt.io/devices/929002398602.html is v2 of the Philips Hue dimmer, and is missing the Notes section.

It should be the same as v1 dimmer here: 
https://www.zigbee2mqtt.io/devices/324131092621.html

Thank you!

**Comment by timoline** [comment]
Adde PR
https://github.com/Koenkk/zigbee2mqtt.io/pull/743
