### ISSUE TITLE
Bticino N4003CW and LN4003CWI are incorrectly identified as Legrand 067773?

### ISSUE THREAD

**Issue by vadercent** [Koenkk/zigbee2mqtt#7421]
It seems both Bticino devices are wrongly registered as Legrand wireless remote switch.

## Information about the device + link
https://catalogue.bticino.com/BTI-N4003CW-EN
https://catalogue.bticino.com/BTI-LN4003CWI-EN

## data/database.db entry of the device
BTI-N4003CW:
{"id":14,"type":"EndDevice","ieeeAddr":"0x0004740000af85e4","nwkAddr":2967,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000
0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Battery","modelId":" Remote switch\u0000\u0000\u0000\u0000\u00
00\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[0,3,15
,32,1,64513],"outClusterList":[3,6,8,0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" Remote switch\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00
00\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000
\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":3,"zclVersion":2,"appVersion":0,"stackVersion":65,"swBuildId":"001e"}},"genPowerCfg":{"attribu
tes":{"batteryVoltage":31}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc36ba","endpointID":1},{"cluster":6,"type":"endpoint","device
IeeeAddress":"0x00124b0021cc36ba","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc36ba","endpointID":1}],"configuredReportings":[]
,"meta":{}}},"appVersion":0,"stackVersion":65,"swBuildId":"001e","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1620590114491}

BTI-LN4003CWI
{"id":12,"type":"EndDevice","ieeeAddr":"0x0004740000a28741","nwkAddr":54331,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00
00\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Battery","modelId":" Remote switch\u0000\u0000\u0000\u0000\u0
000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":260,"inClusterList":[0,3,1
5,32,1,64513],"outClusterList":[3,6,8,0,64513,25],"clusters":{"genBasic":{"attributes":{"modelId":" Remote switch\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0
000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","manufacturerName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000
0\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":3,"zclVersion":2,"appVersion":0,"stackVersion":66,"hwVersion":2,"dateCode":" \u000020210325\u
0000\u0000\u0000\u0000\u0000","swBuildId":"002e"}},"genPowerCfg":{"attributes":{"batteryVoltage":29}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"
0x00124b0021cc36ba","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc36ba","endpointID":1},{"cluster":8,"type":"endpoint","deviceIe
eeAddress":"0x00124b0021cc36ba","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":66,"hwVersion":2,"dateCode":" \u000020210325\u0
000\u0000\u0000\u0000\u0000","swBuildId":"002e","zclVersion":2,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1620592074782}

**Comment by Koenkk** [comment]
These are actually the same devices (I believe Legrand use Bticino for Italy). We cannot distinguish them since they are the same.
