### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by hbkhalil** [Koenkk/zigbee2mqtt#7422]
Hi there, 
I have tried an install on windows, it seems that it does not recognise that it is running on windows and returns this message.
`gitrepo\zigbee2mqtt\node_modules\unix-dgram\src\unix_dgram.cc(9,10): fatal error C1083: Cannot
 open include file: 'unistd.h': No such file or directory [C:\Users\hbkha\Documents\gitrepo\zigbee2mqtt\node_modules\un
ix-dgram\build\unix_dgram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hbkha\Documents\gitrepo\zigbee2mqtt\node_modules\unix-dgram
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
added 922 packages in 19.083s`

**Comment by arozhankov** [comment]
i have the same problem
