### ISSUE TITLE
last_seen attribute is not updated in topic for some devices

### ISSUE THREAD

**Issue by Enzokot** [Koenkk/zigbee2mqtt#7423]
## What happened
Last_seen attribute is not updated in topic zigbee2mqtt for some devices, only updates in database.db.
For example: [TuYa TS0601_thermostat](https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html) and [Moes MS-104Z](https://www.zigbee2mqtt.io/devices/MS-104Z.html)
![image](https://user-images.githubusercontent.com/43236573/117689108-1b9d5680-b1c2-11eb-9740-f5673a0b7074.png)
## What did you expect to happen
Last_seen attribute in topic zigbee2mqtt is equal data from database.db
## How to reproduce it (minimal and precise)
Do not send any commands to device, just idle
## Debug info
Zigbee2MQTT version: 1.18.3
Adapter hardware: CC26X2R1
Adapter firmware version: zStack3x0 20210218

**Comment by Enzokot** [comment]
and same with [Moes AM43-0.45/40-ES-EB](https://www.zigbee2mqtt.io/devices/TS0601_cover.html)

**Comment by RedShuhart88** [comment]
https://www.zigbee2mqtt.io/devices/TS0115.html and https://www.zigbee2mqtt.io/devices/TS0601_dimmer.html

**Comment by Enzokot** [comment]
The same with 1.19.0

**Comment by Enzokot** [comment]
The same with 1.20.0

**Comment by Koenkk** [comment]
The `last_seen` is only updated when a message MQTT is published. (it's not updated standalone)

**Comment by Enzokot** [comment]
> The `last_seen` is only updated when a message MQTT is published. (it's not updated standalone)

But why another devices publish last_seen, minimal one time at hour. For example, Xiaomi MCCGQ01LM, but TuYa TS0601_thermostat save and update last only in database.db
If it is possible to make this device also report like some others. That would be great.

**Comment by Koenkk** [comment]
Because a MQTT is published for this Zigbee message, if you can catch a `Received zigbee message..` without  a `MQTT publish` from this device I can add it. (requires debug log)

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by Enzokot** [comment]
I catch. Device name 'Left shades drive motor kitchen' and 'Bedroom valve with thermostat'
[example.txt](https://github.com/Koenkk/zigbee2mqtt/files/6758509/example.txt)

**Comment by Koenkk** [comment]
Should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Enzokot** [comment]
The fix work for me. Thank you very much!

**Comment by Enzokot** [comment]
@Koenkk the fix has been broken in the release `1.21.2`. Debug log in attachment. For example - `Right shades drive motor kitchen`
[example.txt](https://github.com/Koenkk/zigbee2mqtt/files/7271067/example.txt)

**Comment by Koenkk** [comment]
Should be fixed now and be better than before. It will now rely on the internal last seen changed events which is also updated when e.g. device announces, changed network address or when a command to it is successfully send. 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by tteck** [comment]
groups don't change last seen.

**Comment by Koenkk** [comment]
That is expected, with a group command you don't know if a device actually received it.

**Comment by Enzokot** [comment]
Thanks!

**Comment by Enzokot** [comment]
@Koenkk after 1.22.1 release it's broken again. For example, TuYa TS0601_cover

**Comment by Enzokot** [comment]
@Koenkk sorry, I forget about it.
For example `Right shades drive motor kitchen`
Debug log:
[example.txt](https://github.com/Koenkk/zigbee2mqtt/files/7643726/example.txt)

**Comment by Koenkk** [comment]
Should be fixed again.

**Comment by Enzokot** [comment]
Thanks!
