### ISSUE TITLE
Zigbee led dimmer draai 0-200W, universeel - Pro

### ISSUE THREAD

**Issue by mrblwd-058** [Koenkk/zigbee2mqtt#7434]
Before buying this device I first searched on google for people that were using this device in HA. After pairing it z2m says de device is unsupported. I really don't know what to do to make it work by myself. I tried to follow the article but really have no clue. It would be great if this device can added to the supported devices. 

Thanks a lot!

## Information about the device + link
..
https://www.ecobright.nl/led-dimmer/smart-led-dimmer-zigbee-zwave-0-200w-voor-alle-afdekramen/?utm_campaign=googleshopping&utm_content=&utm_source=google&utm_medium=organic&utm_term=Zigbee+led+dimmer+draai+0-200W,+universeel+-+Pro&gclid=CjwKCAjw1uiEBhBzEiwAO9B_HVsIl_FLRBVf6-x1tZYBwSR7Srv5bqQoKS9lAYoew1PaLoLb5LRUvBoCzCwQAvD_BwE
## data/database.db entry of the device
..
 Edit:

I see different forum post about the device that it's unsupported in several versions.

Versions I tried:

1.17
1.18.3-1
1.18.3-dev

None of them supports de device.

**Comment by mrblwd-058** [comment]
Hi guys, any update / feedback on this request?

**Comment by Koenkk** [comment]
Can you share the data/database.db entry of this device?

**Comment by mrblwd-058** [comment]
Hi Koen,

This is what I can find in the database.db file:

{"id":26,"type":"Unknown","ieeeAddr":"0xec1bbdfffe9f865d","nwkAddr":6416,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1620307741572}

**Comment by Koenkk** [comment]
It looks that interviewing failed therefore we don't have a modelID which is needed to add it. Can you try pairing it again close to the coordinator?

**Comment by mrblwd-058** [comment]
Hi Koen,

I removed the entry and started a new pair and now the device is interviewed and supported :)

Friendly name
0x086bd7fffe5d37f0
Last seen
N/A
Device type
Router
Zigbee Model
Dimmer-Switch-ZB3.0
description
Zigbee & Z-wave dimmer
Support status
Supported

IEEE Address
0x086bd7fffe5d37f0
Network address
0x3A75
Firmware build date
20200701
Firmware version
3.09
Manufacturer
EcoDim
Model
Eco-Dim.07
Power
Interview completed
True

Thanks for your time and support!

**Comment by Koenkk** [comment]
Good :)
