### ISSUE TITLE
Websocket support for home assistant

### ISSUE THREAD

**Issue by alekslyse** [Koenkk/zigbee2mqtt#7450]
After seeing how easy and fast zwavejs2mqtt became with disable mqtt and enable ws ti home assistant I think it would be a really nice addition to this project. That way it can be a deeper and faster integration

**Comment by LorbusChris** [comment]
Could this be reopened? I think this would be a great feature and possibly make for even better integration into Home Assistant

**Comment by LorbusChris** [comment]
Looks like this is a dupe of https://github.com/Koenkk/zigbee2mqtt/issues/3621
