### ISSUE TITLE
Support phillips hue power on behaviour

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#746]
In the latest hue light firmware  (SW 1.46.13_r26312) support has been added for allowing the bulb to return to its previous state after a power outage.

I've capture the zigbee traffic when setting a bulb to have the option and the following is the dump.

Can we add support for specifying this.

Setting it to  Power loss recovery (last used colour and brightness) generates the following two packets
![image](https://user-images.githubusercontent.com/1100397/50372355-118e5380-0619-11e9-8bb8-f01c14b679d4.png)

![image](https://user-images.githubusercontent.com/1100397/50372349-e572d280-0618-11e9-952a-12f1bc0aec4c.png)

Setting it to off (light always powers on with warm white full brightness) generates the following two packets
![image](https://user-images.githubusercontent.com/1100397/50372365-308ce580-0619-11e9-981d-198661df7151.png)

![image](https://user-images.githubusercontent.com/1100397/50372371-3edb0180-0619-11e9-9360-527ed5aed518.png)

**Comment by danpowell88** [comment]
I think I've managed to get part of the way there.

Looks like it requires changes in https://github.com/zigbeer/zcl-id/blob/master/definitions/cluster_defs.json

to add the following

to 'genOnOff'
`"powerOnCtrl":{"id":16387,"type":"enum8"}},`

to 'genLevelControl'
"powerOnCtrl":{"id":16384,"type":"uint8"}},

then in zigbee-shepherd-converters something like 
```
configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.write('genOnOff', 'powerOnCtrl', 255, cb),
				(cb) => device.write('genLevelCtrl', 'powerOnCtrl', 255, cb)
            ];
            execute(device, actions, callback);
        }	
```	

To all hue bulbs.

Unfortunately after doing this I get an error that z2mqtt failed to configure the lights, and I cant see any more debug information, even when running with debug log level and the DEBUG environment variable

**Comment by Koenkk** [comment]
Instead of adding it to `configure` I think it's better to have a converters for this. 

Please checkout https://github.com/Koenkk/zigbee-shepherd-converters/tree/hue_power_behaviour

You should be able to control the power on by sending to `zigbee2mqtt/[DEVICE_ID]/set` value:

```
{
  "power_on_behaviour_1": "recover",   // recover or off
  "power_on_behaviour_2": "recover",  // recover or off
}
```

**Comment by danpowell88** [comment]
Didnt appear to work

```
[31m zigbee2mqtt:error[39m 2018-12-26 11:03:45 Zigbee publish to '0x00178801035609f4', genOnOff - {

"power_on_behaviour_1": "recover",
"power_on_behaviour_2": "recover",
} - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Unrecognized command
```

**Comment by Koenkk** [comment]
I don't understand why this error is thrown, are you on the latest (clean) dev branch?

**Comment by danpowell88** [comment]
@Koenkk Tried it again on a clean rapsberry pi with the full dev branch

```
zigbee2mqtt:info 12/28/2018, 7:28:44 AM Starting zigbee2mqtt version 1.0.1 (commit #5e4e6d8)
zigbee2mqtt:info 12/28/2018, 7:28:44 AM Starting zigbee-shepherd
zigbee2mqtt:info 12/28/2018, 7:28:46 AM zigbee-shepherd started
zigbee2mqtt:info 12/28/2018, 7:28:46 AM Coordinator firmware version: '20181024'  
zigbee2mqtt:info 12/28/2018, 7:29:13 AM Zigbee publish to device '0x00178801035609f4', genOnOff - {  "power_on_behaviour_1": "recover",   // recover or off  "power_on_behaviour_2": "recover",  // recover or off} - {} - {"manufSpec":0,"disDefaultRsp":0} - null
zigbee2mqtt:error 12/28/2018, 7:29:13 AM Zigbee publish to device '0x00178801035609f4', genOnOff - {  "power_on_behaviour_1": "recover",   // recover or off  "power_on_behaviour_2": "recover",  // recover or off} - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: Unrecognized command
```

I also manually modified the package.json to change the following 

`"zigbee-shepherd-converters": "git+https://github.com/Koenkk/zigbee-shepherd-converters.git#6d49008e91c7606c9067be8c469e898cb2e5a0b2"`

Taking a quick look at toZigbee.js in converts it appeared to have the power on change so I assume this was correct

**Comment by danpowell88** [comment]
Just figured it out!

It was the comment in the json that was causing the issue, will test it now

**Comment by danpowell88** [comment]
@Koenkk success, tested with recover and off and both worked as expected

**Comment by danpowell88** [comment]
I'll give it a go

**Comment by danpowell88** [comment]
Brightness if maintained but not colour, I'll have to pull out the sniffer again and see if something different is sent for the colour retention

**Comment by danpowell88** [comment]
Also just a note along with comments it doesnt like a trailing comma on the final attribute

**Comment by Koenkk** [comment]
And what is send for the normal behaviour?

**Comment by Koenkk** [comment]
@Chrischi- great, could you make a pr?

**Comment by Chrischi-** [comment]
@Koenkk 
any idea to put this into one converter?

if you switch on the behavior, you should have the possibility to set 
the color, color-temperature and brightness. since i don't have 
colored lamps (only color temperature and brightness), i can't 
create a converter for it

**Comment by Koenkk** [comment]
I don't think that these converters should be merged together, they each serve a different purpose.

Could you prefix the keys with `hue_`? (as this is hue specific, e.g. `key: 'hue_power_on_color_temperature'],`

Ofcourse all the attributes can be set using 1 MQTT message:

```json
{
  "hue_power_on_behavior": "on",
  "hue_ power_on_level": 200,
  "hue_power_on_color_temperature": 300
}
```

**Comment by bepece1** [comment]
Also work right in Tuya, Tadfradi or Sonoff lights????

**Comment by victoriano95** [comment]
Hi, I'm trying to set this option and it'is not working, these are the details:
Topic: zigbee2mqtt/friendlyName/set
Payload:
```
{
    "hue_power_on_behavior": "recover"
}
```
When I cut the power to the bulb and I restore it again it turns on.
The log output is:`{"ieeeAddr":"0x001788010424184b","type":"Router","networkAddress":14471,"model":"8718696548738","friendly_name":"0x001788010424184b","manufacturerID":4107,"manufacturerName":"Philips","powerSource":"Mains (single phase)","modelID":"LTW010","hardwareVersion":1,"softwareBuildID":"1.50.2_r30933","dateCode":"20191218","lastSeen":1583688566569}]}'`

**Comment by Chrischi-** [comment]
> Hi, I'm trying to set this option and it'is not working, these are the details:
> Topic: zigbee2mqtt/friendlyName/set
> Payload:
> 
> ```
> {
>     "hue_power_on_behavior": "recover"
> }
> ```
> 
> When I cut the power to the bulb and I restore it again it turns on.

**recover - lamps on after power loss with last state**

**Comment by victoriano95** [comment]
I want to recover or power off the bulbs when the power is restored but I when I send the command I can't see nothing on the log and it is not activating the option on the bulb

**Comment by sjorge** [comment]
@victoriano95 after upgrading my bulb yesterday with the experimental hue update support.
I too thought it did not work, but it did for me. Before the bulb recovered to the previeus state it had to be without power for a good few seconds.

And indeed, there is no logging for the command.

**Comment by victoriano95** [comment]
> @victoriano95 after upgrading my bulb yesterday with the experimental hue update support.
> I too thought it did not work, but it did for me. Before the bulb recovered to the previeus state it had to be without power for a good few seconds.
> 
> And indeed, there is no logging for the command.

Can you explain me what commands are you sending and what is the correct mqtt toppic? I have tried to leave the bulb a few minutes unplugged and it's still on when the power is recovered.
Thanks
@sjorge

**Comment by sjorge** [comment]
In my case it was
```json
{
    "hue_power_on_behavior": "recover",
}
```

to `zigbee2mqtt/<friendlyname>/set`

But also pay attemtion to
```
Rules:

    * hue_power_on_behavior value always has to be provided
    * hue_power_on_brightness, hue_power_on_color_temperature and hue_power_on_color can only be provided when hue_power_on_behavior = on
    * hue_power_on_color_temperature and hue_power_on_color cannot be provided together, only one can be set
    * When setting hue_power_on_behavior = on, any not provided values will be reset to their factory defaults

```

**Comment by victoriano95** [comment]
When you send this command the bulb turns off? it's ok the comma?
```
{
    "hue_power_on_behavior": "recover",
}
```
I'm sending the same command at the correct toppic, when I send it without comma it's not any output at the log and when I send it with the comma this is the output:
`MQTT publish: topic 'zigbee2mqtt/0x001788010424194b', payload '{"state":"OFF","brightness":0,"color_temp":451}'`

**Comment by sjorge** [comment]
The comma was an error, I correct it above. When I sent it there was no response in the logs. That is normal.

I then turned off the bulb, cut the power to the bulb for 15sec and when I restored the power the bulb remained of.

I then turned on the bulb, cut the power to the bulb for 15sec and when I restored the power the bulb turned on again... so I think it is working.

**Comment by victoriano95** [comment]
@sjorge Thanks, the problem was my zigbee2mqtt version, I have updated it and it works fine.

**Comment by kedare** [comment]
Is there a way to set this using the web interface ? If not it's not very clear how to inject messages in the MQTT ? ('m using home assistant with the embedded mosquitto)

**Comment by PostLogical** [comment]
> Is there a way to set this using the web interface ? If not it's not very clear how to inject messages in the MQTT ? ('m using home assistant with the embedded mosquitto)

Just went through this myself. I'm using Home Assistant in a docker container, so apologies if anything is different for HA OS or others, but you should be able to go to your Integrations page in Home Assistant and click on Configure for the MQTT integration. Then there are only a few things on the screen including "Publish a packet." Put in the topic as discussed above zigbee2mqtt/FRIENDLYNAME/set. And then put in the payload below that (see above for options). There isn't any feedback once you click Publish, so to confirm your command reached zigbee2mqtt, you might go to your Zigbee2MQTT interface and open the log and choose debug as log level before publishing the command. If you did it right, the command will appear in the log under debug (and only under debug).
