### ISSUE TITLE
Tuya plug TS011F unsupported 

### ISSUE THREAD

**Issue by razmoket89** [Koenkk/zigbee2mqtt#7463]
Just bought a tuya plug, it's pairing fine but is unsupported. I read thé howto add à New device but it's way over my competencies.

Do you need anything to make it work ?

![IMG_20210513_225901](https://user-images.githubusercontent.com/46903790/118187240-fc5f2d00-b43e-11eb-9cca-8e0a7b3f20c7.jpg)

**Comment by shvirik** [comment]
I think there are a lot of different device with the same external case. In this thread:

https://github.com/Koenkk/zigbee2mqtt/issues/7405 

we have similar issue. I bought 3, and 2 works as TS0121 plug and one as Unsupported TS011F. The boxes had the same device label code: A5C-16B7-08.

**Comment by Koenkk** [comment]
Let's continue in #7405
