### ISSUE TITLE
GLEDOPTO PR missing case device.epList.toString() === '11,13'

### ISSUE THREAD

**Issue by khzd** [Koenkk/zigbee2mqtt#747]
Hi @Koenkk 
to manage a GLEDOPTO missing case,  may you update the GLEOPTO device.js with the bold part?
{
zigbeeModel: ['GLEDOPTO', 'GL-C-008'],
model: 'GL-C-008',
vendor: 'Gledopto',
description: 'Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer',
supports: generic.light_onoff_brightness_colortemp_colorxy().supports,
fromZigbee: generic.light_onoff_brightness_colortemp_colorxy().fromZigbee,
toZigbee: generic.light_onoff_brightness_colortemp_colorxy().toZigbee,
ep: (device) => {
if (device.epList.toString() === '11,12,13' ) {
return {'': 12};
} else if (device.epList.toString() === '10,11,13' **|| device.epList.toString() === '11,13'**) {
return {'': 11};
} else {
return {};
}
},
},

**Comment by Koenkk** [comment]
done, thanks!
