### ISSUE TITLE
Minor issue: Heiman HS3SA-E recognized as HS1SA

### ISSUE THREAD

**Issue by alexw1982** [Koenkk/zigbee2mqtt#7471]
## What happened
I've successfully paired two Heiman HS3SA-E Zigbee 3.0 smoke detectors - the only minor issue is that the devices are shown as HS1SA devices. 

## Debug info
Zigbee2MQTT version: docker:latest
Adapter hardware: CC2531

**Comment by etatto** [comment]
It is fixed in the dev branch, please see https://github.com/Koenkk/zigbee2mqtt/discussions/6790 and https://github.com/Koenkk/zigbee-herdsman-converters/commit/d39d576fbc0b804e9897f32688c20949e6d9dea8.
Mine are now correctly detected as HS3SA.

**Comment by alexw1982** [comment]
Thanks! Closing the issue
