### ISSUE TITLE
QS-Zigbee-S05-L hardware switch handling

### ISSUE THREAD

**Issue by izipuho** [Koenkk/zigbee2mqtt#7472]
# Bug Report
## What happened
1. QS-Zigbee-S05-L has wrong image. It has to be simmilar to QS-Zigbee-D02-TRIAC-2C-L but with 1 gang.
2. Real bug: device doesn't send mqtt message on handling hardware switch.
## What did you expect to happen and how2 reproduce
When pressing hardware switch I wait for message zigbee2mqtt/devicename/set:{"state":"ON"} (or OFF), but I don't get any.
Comparing to QS-Zigbee-D02-TRIAC-2C-L, which sends {"state_left":"OFF","state_right":"OFF"}

## Debug Info
Zigbee2MQTT version: 1.18.1, 1.18.3
Adapter hardware: CC2625RB

**Comment by vezyr** [comment]
I have the same situation with the QS-Zigbee-S05-L module.

When I press the hardware switch there is no message with changed state (I've checked the DEBUG log), so the state displayed in software (ie. Home Assistant's Dashboard) is different then actual state.

If I manually press the button in Home Assistant to update state, messages are sent and the module responds correctly - the state in the software is updated then. 
```
Zigbee2MQTT:debug 2021-08-02 11:46:00: Received MQTT message on 'zigbee2mqtt/[DEVICE_NAME]/get' with data '{"state":""}'
Zigbee2MQTT:debug 2021-08-02 11:46:00: Publishing get 'get' 'state' to '[DEVICE_NAME]'
Zigbee2MQTT:debug 2021-08-02 11:46:00: Received Zigbee message from '[DEVICE_NAME]', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID null
Zigbee2MQTT:info  2021-08-02 11:46:00: MQTT publish: topic 'zigbee2mqtt/[DEVICE_NAME]', payload '{"linkquality":255,"state":"OFF"}'
```
