### ISSUE TITLE
Luminosity | Humidity | Temperature sensor (Moes House)

### ISSUE THREAD

**Issue by DavidFFerreira** [Koenkk/zigbee2mqtt#7474]
![image](https://user-images.githubusercontent.com/32928749/118314791-8913f480-b4ec-11eb-8fe5-52cb879d8b4c.png)

Zigbee model 'TS0222' and manufacturer name '_TYZB01_kvwjujy9'

debug Received Zigbee message from '0x5c0272fffe0a4792' type 'attributeReport' cluster 'genPowerCfg' data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792' type 'attributeReport' cluster 'msIlluminanceMeasurement' data '{"measuredValue":22254}' from endpoint 1 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792' type 'attributeReport' cluster 'msRelativeHumidity' data '{"measuredValue":4132}' from endpoint 2 with groupID 0
debug Received Zigbee message from '0x5c0272fffe0a4792' type 'attributeReport' cluster 'msTemperatureMeasurement' data '{"measuredValue":2741}' from endpoint 2 with groupID 0

**Comment by DavidFFerreira** [comment]
up

**Comment by DavidFFerreira** [comment]
up

**Comment by Koenkk** [comment]
Same as  https://github.com/Koenkk/zigbee2mqtt/issues/7535, supported in the dev branch now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by DavidFFerreira** [comment]
it stills dont work, I have the edge in my HA. I did a force remote. Take out the battery and wait a few minuts. After try to pair again, I got this log:
`Info Successfully interviewed '0x5c0272fffe0a438d', device has successfully been paired
Warning Device '0x5c0272fffe0a438d' with Zigbee model 'TS0222' and manufacturer name '_TYZB01_kvwjujy9' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":null,"friendly_name":"0x5c0272fffe0a438d","ieee_address":"0x5c0272fffe0a438d","status":"successful","supported":false},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x5c0272fffe0a438d","supported":false},"type":"pairing"}'
Warning Received message from unsupported device with Zigbee model 'TS0222' and manufacturer name '_TYZB01_kvwjujy9'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.`

**Comment by Koenkk** [comment]
@DavidFFerreira then you are probably using the wrong repo, has been changed to https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation
