### ISSUE TITLE
Namron

### ISSUE THREAD

**Issue by nisse1991github** [Koenkk/zigbee2mqtt#7482]
hi, 

Hi,

Can anyone help me integrate these two? I do not understand and can not add these two devices.

## Information about the device + link

(Art No.: 4512727)
https://www.namron.com/products/namron-zigbee-foh-bryter-k4-328/

(Art No.: 3802960)
https://www.namron.com/products/led-paere-9w-dim-e27-zigbee/

**Comment by Hodnen** [comment]
Please add this.
4512727
