### ISSUE TITLE
New thermostatic valve from Aliexpress

### ISSUE THREAD

**Issue by thierryspath** [Koenkk/zigbee2mqtt#7483]
Hi ,

[(https://fr.aliexpress.com/item/1005002433582947.html?spm=a2g0s.9042311.0.0.18eb6c37LITHje)]

Device automaticaly paired as TuYa TS0201 and don't work ...

![image](https://user-images.githubusercontent.com/25227091/118366052-73133c00-b59f-11eb-944e-18388a29f5ce.png)

for my point of view this is something like  TuYa TS0601_thermostat but i don't have the capacities to manage this change

Someone can help me ?

Best

Thierry

**Comment by stones80** [comment]
Hello,
i have the same problem, i'm trying using "external_converters" on add-on with hassio, with no big success.
thanks
