### ISSUE TITLE
SMaBiT AV2010/21C Ultra-Flat magnetic contact sensor

### ISSUE THREAD

**Issue by cdemi** [Koenkk/zigbee2mqtt#7485]
Hi,

I have recently purchased a [SMaBiT AV2010/21C Ultra-Flat magnetic contact sensor](https://bv.smabit.eu/index.php/smart-home-produkte/ultraflacher-magnetkontakt/).

It looks like this device is not supported in ZigBee2MQTT so I have followed the instructions on how to [support new devices](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html). I am pleased to say that it now works :) The instructions were very helpful and clear.

I would like to contribute back the external converter file for this device. I would open a Pull Request but I do not know exactly where I should put it or if you have any standards in place.

In any case this is the file:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['AV2010/21C'],
    model: 'AV2010/21C',
    vendor: 'SMaBiT',
    description: 'Ultra-Flat magnetic contact sensor ',
    fromZigbee: [fz.ias_contact_alarm_1],
    toZigbee: [],
    exposes: [e.contact(), e.battery_low(), e.tamper()]
};

module.exports = definition;
```

Manual for this device can be found here: https://manuals.smabit.eu/len/av2010_21c.html
Product site is here: https://bv.smabit.eu/index.php/smart-home-produkte/ultraflacher-magnetkontakt/

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
