### ISSUE TITLE
Zigbee (Tuya) Door Sensors

### ISSUE THREAD

**Issue by jeremysharp** [Koenkk/zigbee2mqtt#7486]
Trying to get these door sensors to work, following the howto for adding unsupported devices:

https://www.aliexpress.com/item/1005002348194512.html

But it doesn't give me any IDs to use in the logging:

`Zigbee2MQTT:warn 2021-05-04 13:46:33: Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'`

**Comment by DavidFFerreira** [comment]
you need to debug to get some clusters info, without that, devs can do anything =)

**Comment by So871** [comment]
I'm trying to understand this procedure, but is there a video or an "simplified" how to on how to add Unsupported Tuya devices ?

**Comment by jeremysharp** [comment]
> you need to debug to get some clusters info, without that, devs can do anything =)

I'm just following https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html which suggests the output will include IDs, like this:

```
Zigbee2MQTT:info  2019-11-09T12:19:56: Successfully interviewed '0x00158d0001dc126a', device has successfully been paired
Zigbee2MQTT:warn  2019-11-09T12:19:56: Device '0x00158d0001dc126a' with Zigbee model 'lumi.sens' and manufacturer name 'some_name' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
```

...eg '0x00158d0001dc126a' where mine shows 'defined'. There's no mention of additional debug settings on that link?

**Comment by jeremysharp** [comment]
What should I do given the unpopulated ID fields?

**Comment by So871** [comment]
this is what i get in debug 

Debug Received Zigbee message from 'ZM-CG206', type 'attributeReport', cluster 'ssIasZone', data '{"zoneStatus":0}' from endpoint 1 with groupID null
Debug Received Zigbee message from 'ZM-CG206', type 'attributeReport', cluster 'ssIasZone', data '{"zoneStatus":1}' from endpoint 1 with groupID null

**Comment by robert-pajak** [comment]
I think this issue is a duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/7548 (these issues could be probably be merged)

**Comment by mastertape** [comment]
Is there  a working Solution for this device ? Have it also here....
