### ISSUE TITLE
TS0601 - support for "windows_detection_params"

### ISSUE THREAD

**Issue by pawol** [Koenkk/zigbee2mqtt#7500]
TRV Moes HY368 (TS0601) - support or bug fix of converter for "windows_detection_params"

## Information about the device + link
HY368 (TS0601) with the latest TuYa firmware + CC2531 (zStack12 2020112) + zigbee2mqtt 1.18.3-dev

## data/database.db entry of the device
TS0601_thermostat =  new Device('EndDevice', '0x0017882104a44559', 6544,4151, [new Endpoint(1, [], [], '0x0017882104a44559')], true, "Mains (single phase)", 'kud7u2l');

A lot of features of HY368 (TS0601) is implemented now. I see that "window_detection_params: minutes and temperature" writes are not properly supported yet by Z2M. 

It seems that there is bug in current converters regarding windows_detection_params  and window_detection in 
/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/toZigbee.js
and
/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js
It look that we have wrong implementation. on/off and params should be split

Allowed ranges are:
minutes: 5-60 (step: 1 unit)
temperatures: 5 - 25 (step: 1 unit)

Sample of logs (it is possible to read params):
MQTT publish: topic 'zigbee2mqtt/termostat_w_pokoju', payload '{"auto_lock":"MANUAL","away_mode":"OFF","away_preset_days":0,"away_preset_temperature":17,"battery_low":false,"boost_time":300,"child_lock":"UNLOCK","comfort_temperature":21,"current_heating_setpoint":5,"eco_temperature":19,"force":"normal","holidays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":21},{"hour":11,"minute":30,"temperature":21},{"hour":12,"minute":30,"temperature":21},{"hour":17,"minute":30,"temperature":21},{"hour":21,"minute":0,"temperature":19}],"linkquality":34,"local_temperature":18.5,"local_temperature_calibration":-2,"max_temperature":25,"min_temperature":5,"position":0,"preset":"manual","system_mode":"auto","update":{"state":"idle"},"update_available":false,"week":"7","window_detection":"OFF","window_detection_params":{"minutes":115,"temperature":94},"workdays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":21},{"hour":11,"minute":30,"temperature":21},{"hour":12,"minute":30,"temperature":21},{"hour":17,"minute":30,"temperature":21},{"hour":21,"minute":0,"temperature":19}]}'

Interesting piece of logs is there:
,"window_detection_params":{"minutes":115,"temperature":94},
We see completly random values - not aligned with values set manually

I have tried a lot of variants of an mqtt message and everytime I get a response similar to that:
zigbee2mqtt/termostat_w_pokoju/set {"window_detection_params": {"minutes": 5,"temperature": 1}}
zigbee2mqtt/bridge/logging {"level":"error","message":"No converter available for 'window_detection_params' ([object Object])"}

**Comment by wizu** [comment]
#6073

**Comment by pawol** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/6073
