### ISSUE TITLE
Support for Tuya Smart Air Box

### ISSUE THREAD

**Issue by TheOriginal92** [Koenkk/zigbee2mqtt#7519]
Hello, 
there seems to be a quite new ZigBee based "Tuya Smart Air Sensor".

Measuring a few interesting parameters like CO2, Formaldehyde, VOC, Temperature and Humidity.

Example: Tuya Air Box
https://a.aliexpress.com/_v0gA0X

Does Z2M already beta-support this device as I can’t find it on the devices list?

If not so I will help integrating it as soon as it arrives by mail :)

Thank all of you very much!

**Comment by TheOriginal92** [comment]
Finally the device arrived. I took it apart and found.. not much.

The board looks pretty empty and uses minimal parts count. 
Its equipped with an DHT11 for Temperature and Humidity. The second sensor is unknown to me. 

![D963DA34-E3BF-4773-9A18-0FC268E0F200](https://user-images.githubusercontent.com/36191265/118860827-1fc12680-b8dc-11eb-9509-b40a6cfd1e9b.jpeg)
![3BB0C4FF-B36E-472C-8653-820802D7F618](https://user-images.githubusercontent.com/36191265/118860846-2485da80-b8dc-11eb-9562-4a9b79210b0f.jpeg)
![6AE23AF5-15FA-4FFF-B247-27E8EB249D27](https://user-images.githubusercontent.com/36191265/118860857-26e83480-b8dc-11eb-80e6-4f44b529b781.jpeg)

Next up is adding the converter.

**Comment by meisterlampe** [comment]
You can find a WIP-Converter here: https://github.com/Koenkk/zigbee2mqtt/discussions/7299#discussioncomment-769443

**Comment by artemzaharov** [comment]
Hello guys! Thanks for your work, so finally this device will be add to zigbee2mqtt and work from box?
