### ISSUE TITLE
force device to connect with router instead of coordinator

### ISSUE THREAD

**Issue by trekker25** [Koenkk/zigbee2mqtt#752]
is there a way to have an end device (aqara motion sensor) to connect to the nearest router instead of the coordinator?

The stick is in my utillity closet and next to it is my toilet with a Hue bulb (router) and Aqara motion sensor. The router and sensor are only 30 cm away from each other and it would be logical the sensor connects to the router instead of coordinator (thick wall between). 

Now there is a link quality of 20 - 30 for the motion sensor, and connecting to the router would make more sense.

Battery in and out? Or how to solve this?

EDIT i pulled out the battery and put back in. Now all devices (including routers) are directly connected to coordinator and not router (in hue remote was connected to router)

is there a command to activate a heal / optimize of the zigbee network?

**Comment by lolorc** [comment]
is pairing through routers working ?

**Comment by Koenkk** [comment]
This is hard to say, depends on the router.

**Comment by h4nc** [comment]
Does it work with a CC2530 router?

**Comment by Koenkk** [comment]
I`m not sure, @ptvoinfo is this supported?

**Comment by nickrout** [comment]
Can anyone tell me if it work to pair to a router with a Xiaomi Power Plug ZNCZ02LM?

**Comment by hvddrift** [comment]
I also would like to know the answer to this one.

> Can anyone tell me if it work to pair to a router with a Xiaomi Power Plug ZNCZ02LM?

**Comment by ptvoinfo** [comment]
@hvddrift Both devices are routers and should be paired with a coordinator. You cannot pair a router to a router.

**Comment by hvddrift** [comment]
I am still trying to understand how this should work...

I have the following network
![chrome_2019-01-19_22-31-44](https://user-images.githubusercontent.com/972926/51427080-1279cb80-1c3f-11e9-8fa0-e505afe9d628.png)

The Motion sensor is 1 meter away from a Xiaomi Plug (router), and yet it joins back to the controller with a link strenth of 1. Is this intended? Should it try to join the router (I assume the signal strength would be stronger)

**Comment by Koenkk** [comment]
@hvddrift I would recommend updating to the latest dev branch, this will show the mesh network better (as one node can be connected to multiple)

**Comment by hvddrift** [comment]
Noob, question. Are there instructions for updating to the dev branch?

Thanks
dank je

**Comment by hvddrift** [comment]
I worked it out.. Found another thread. 

So, this is my network map now. Has some more information. But the Motion Sensor still bypasses the router. What makes the device connect to a router or direct to the controller?

![chrome_2019-01-20_00-34-56](https://user-images.githubusercontent.com/972926/51428103-989c0f00-1c4b-11e9-941d-c2b330796664.png)

**Comment by Koenkk** [comment]
@hvddrift the device self decides about this, sometimes it helps to repair the device while having it close to the router you want to pair it to.

**Comment by hvddrift** [comment]
And another basic question... To "repair" a device simply means to remove it and repair it?

**Comment by h4nc** [comment]
Yes, remove it (you can find how to remove files in the docs) and than pair it again.

**Comment by tuinstoelen** [comment]
> Yes, remove it (you can find how to remove files in the docs) and than pair it again.

This comment finally allowed me to solve my Aqara Temperature sensors not connecting to a router, but only to the main hub. It turns out, that if i first explicitly remove the sensor in MQTT, then allow pairing only to a specific router (by using the drop down button), the sensor would connect to the router.

It seems like the sensor remembers which hub/router it was connected to, and will not connect to any other router if you just press the button for 7(?) seconds. First explicitly removing it from MQTT solved this for me.
