### ISSUE TITLE
TS0014 with neutral wire and manufacturer name '_TZ3000_r0pmi2p3'

### ISSUE THREAD

**Issue by sMartjeB** [Koenkk/zigbee2mqtt#7521]
I modified the tuya.js file in /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/

added the _TZ3000_r0pmi2p3 which works fine.
Could you please add the manufacturer name '_TZ3000_r0pmi2p3'

In my case the switch has zero connected.
Any chance it might be able to work as a router?
Can I add some data in a new tuya.js file to test it?

 {
        fingerprint: [{modelID: 'TS0014', manufacturerName: '_TZ3000_jr2atpww'}, {modelID: 'TS0014', manufacturerName: '_TYZB01_dvakyzhd'},
            {modelID: 'TS0014', manufacturerName: '_TZ3210_w3hl6rao'}, {modelID: 'TS0014', manufacturerName: '_TZ3000_r0pmi2p3'}],
        model: 'TS0014',
        vendor: 'TuYa',
        description: 'Smart light switch - 4 gang without neutral wire',
        extend: extend.switch(),
        exposes: [e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'), e.switch().withEndpoint('l3'),
            e.switch().withEndpoint('l4')],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2, 'l3': 3, 'l4': 4};
        },
        whiteLabel: [{vendor: 'TUYATEC', model: 'GDKES-04TZXD'}, {vendor: 'Vizo', model: 'VZ-222S'}],
        meta: {configureKey: 2, multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            try {
                for (const ID of [1, 2, 3, 4]) {
                    const endpoint = device.getEndpoint(ID);
                    await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
                }
            } catch (e) {
                // Fails for some: https://github.com/Koenkk/zigbee2mqtt/issues/4872
            }
            device.powerSource = 'Mains (single phase)';
            device.save();
        },
    },

**Comment by gkozlowski-git** [comment]
Any info about _TZ3000_r0pmi2p3 support?
