### ISSUE TITLE
Add picture for Fantem ZB006-X (TS110F / _TZ3210_lfbz816s)

### ISSUE THREAD

**Issue by AlexKay88** [Koenkk/zigbee2mqtt#7532]
I read instructions on how to support new devices and update documentation, but failed to clone zigbee2mqtt.io and make a pull request, because I have never done that before.

Could someone pls help to make device picture available in docs?
Desired path and filename of picture:
zigbee2mqtt.io/docs/images/ZB006-X.jpg

Device is already added to devices/fantem.js by commit 
https://github.com/Koenkk/zigbee-herdsman-converters/commit/eee136051f5b41cdd5ce862aa94ebd252e6d538d

Picture to add:
![ZB006-X](https://user-images.githubusercontent.com/22791283/118881406-57879880-b8f3-11eb-9024-7fe6f6b629fa.jpg)

**Comment by Koenkk** [comment]
Thanks for the image, right before every release I add images of devices (so on 1 june).
