### ISSUE TITLE
Added support for Elko "SmartDim Puck Uni 200W" and "SmartRele puck 10AX"

### ISSUE THREAD

**Issue by bjornidar** [Koenkk/zigbee2mqtt#7533]
I'm not sure if I've added all the functionality (possibly not) but I got to turn on/off the relay/ dimmer and are also able to adjust the brightness for the dimmer.

eko07144.js - SmartRele puck 10AX
-----------------
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
//const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['PUCK/SWITCH/1'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'EKO07144', // Vendor model number, look on the device for a model number
    vendor: 'Elko', // Vendor of the device (only used for documentation and startup logging)
    description: 'Elko SmartRele puck 10AX ', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
        toZigbee: [tz.on_off],
        fromZigbee: [fz.on_off, fz.linkquality,],
        exposes: [e.switch(), e.linkquality(),],
};

module.exports = definition;`

eko07090.js - SmartDim Puck Uni 200W
-----------------
`const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
//const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['PUCK/DIMMER/1'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'EKO07090', // Vendor model number, look on the device for a model number
    vendor: 'Elko', // Vendor of the device (only used for documentation and startup logging)
    description: 'Elko SmartDimmer puck Uni 200W', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
        toZigbee: [tz.light_onoff_brightness, tz.ignore_transition, tz.ignore_rate, tz.light_brightness_move,
            tz.light_brightness_step, tz.level_config,tz.power_on_behavior],
        fromZigbee: [fz.on_off, fz.brightness, fz.level_config, fz.power_on_behavior, fz.ignore_basic_report, fz.linkquality],
        exposes: [e.light_brightness(),e.linkquality()],
};

module.exports = definition;
`

![eko07090](https://user-images.githubusercontent.com/53019262/118882268-4b500b00-b8f4-11eb-8b93-21aeb727e289.jpg)
![eko07144](https://user-images.githubusercontent.com/53019262/118882270-4c813800-b8f4-11eb-8f93-1d72ac8217ac.jpg)

**Comment by Koenkk** [comment]
Thanks, these device are already supported in the latest dev under the schneider variant, added these as a whitelabel.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
