### ISSUE TITLE
using docker for flashing

### ISSUE THREAD

**Issue by kifeo** [Koenkk/zigbee2mqtt#7547]
I've installed a firmware with docker and would like to document it, where is the documentation repository located ?
Here is what I would like to add (in a best written way).
http://kifeo.blogspot.com/2021/05/use-docker-for-flashing-opensource.html

**Comment by Koenkk** [comment]
The docs can be found here: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/flashing_the_cc2531.md
