### ISSUE TITLE
Question: Zigbee stick new firmware

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#755]
I saw that there is a new firmware version vor cc2531. 

newest version: 20181024
installed version: 20180515

Should I upgrade my firmware?
Do I have to reconnect all devices again when I load a new firmware to the stick? So is the connection stored at the stick or in the hassio addon?

**Comment by ryanbeaton** [comment]
You will need to re-pair after upgrade. There is another way with a different compile of the new firmware in one of the issues here. You don’t even need to use the Debugger with that compile 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ryanbeaton** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/543#issuecomment-433951590

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by h4nc** [comment]
Ok, thanks.

Shipley normal users update their Stick with every new firmware update.

I have a debugger. Is there a benefit not using it or only if you don’t have one?

**Comment by Ingo1977** [comment]
I have the same question.
I don't have a Debugger but want to update my stick.
How can I do the upgrade to the latest firmware?
Thanks.

**Comment by Koenkk** [comment]
@Ingo1977 https://koenkk.github.io/zigbee2mqtt/information/alternative_flashing_methods.html
