### ISSUE TITLE
Expose link quality of all devices to home assistant 

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#757]
Is it possible to create a sensor link is done for the router link quality for all devices? I see that information is in the mqtt payload its just not setup to have the link quality in home assistant, was there a particular reason it was only done for the router?

**Comment by khzd** [comment]
Hello 
Any news about link quality implementation ?
Thanks

**Comment by Koenkk** [comment]
Linkquality sensor is now discovered for all devices, can this be closed?
