### ISSUE TITLE
RaspBee II on Hoobs PI

### ISSUE THREAD

**Issue by Stetocasa** [Koenkk/zigbee2mqtt#7573]
Hi, I’m losing hours to understand how work Zigbee2Mqtt via hoobs trough a RaspBee II

Mqtt server and all packages for Zigbee2Mqtt was installed and the configuration also

The issue is to identity the right location of the RaspBee

Trough the common input ls -l /dev/ttyACM0 a message shows that no permission to access 
![E533253B-5E98-4160-B0C7-9BFB505336AD](https://user-images.githubusercontent.com/70729310/119280415-9d18ce00-bc31-11eb-9032-022740456d58.png)

The service running 
![55956BB5-40F5-49AC-AA22-E0B0DEACA74D](https://user-images.githubusercontent.com/70729310/119280798-3bf1fa00-bc33-11eb-9382-a0f68a81aa90.jpeg)
 But npm instal fail

![E1CAC5EF-2CF9-4797-BFD4-E3664D016A4D](https://user-images.githubusercontent.com/70729310/119281401-e23eff00-bc35-11eb-82c2-eaed9b8806a1.png)

Somebody could help me to solve and check if the raspbee is right connected? I already tried all FAQ

**Comment by robertalexa** [comment]
Hi,

The error message about permission is not actually about permission but rather the device is not at that address

![image](https://user-images.githubusercontent.com/9019306/119321218-4f718500-bc74-11eb-8773-42c0604e430a.png)

I think your adapter might actually be at /dev/ttyUSB0 and not /dev/ttyACM0.

Try that in your config instead.

If that still fails, can you run `lsusb -t` and paste the output?

**Comment by Stetocasa** [comment]
> Hi,
> 
> The error message about permission is not actually about permission but rather the device is not at that address
> 
> ![image](https://user-images.githubusercontent.com/9019306/119321218-4f718500-bc74-11eb-8773-42c0604e430a.png)
> 
> I think your adapter might actually be at /dev/ttyS0 and not /dev/ttyACM0.
> 
> Try that in your config instead.
> 
> If that still fails, can you run `lsusb -t` and paste the output?

hoobs@hoobs:~ $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 480M

**Comment by robertalexa** [comment]
Sorry dude, I think I have edited my post while you were at it

Can you try in your config /dev/ttyS0 ?

PS: My bad aboud lsusb, that won't give you anything good in this case cause your device is not usb.

**Comment by Stetocasa** [comment]
Seems that the device in not found
hoobs@hoobs:~ $ sudo GCFFlasher_internal -l
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

**Comment by Stetocasa** [comment]
No detected 

hoobs@hoobs:~ $ ls -l /dev/ttyS0
crw-rw---- 1 root dialout 4, 64 Feb 14  2019 /dev/ttyS0

**Comment by robertalexa** [comment]
Could you have a look at the last post in this thread
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3898

I have a feeling that this is not a problem just for you. You might need to do some changes on your raspberry pi.

PS: i do not own your adapter, just trying to help

**Comment by Stetocasa** [comment]
I did that:

sudo nano config.txt


enable_uart=1                                                                 
dtoverlay=miniuart-bt                                                     
force_turbo=1  

Save
Reboot

Nothing changed

**Comment by robertalexa** [comment]
Silly question, but have you followed the instruction for this device?
https://phoscon.de/en/raspbee2/install#raspbian

In your case, you probable need everything UP TO deCONZ Installation

**Comment by Stetocasa** [comment]
Deconz is already installed
![FCF97E4C-EDA7-4A5A-9C1E-A7246E5677ED](https://user-images.githubusercontent.com/70729310/119327503-56ec5a80-bc83-11eb-84c7-75e3986c146a.jpeg)

**Comment by robertalexa** [comment]
I meat the drivers for the board - basically RTC Installtion.

If that is all done, I am afraid I do not know what to suggest. Maybe someone else with this board can have some input.

Though I suggest you dig online with regards to why the board is not recognised rather than hoobs or z2m specific. They will all fail if the device is not found basically.

**Comment by zhapwey** [comment]
Hello:
You may not have done the step:
![image](https://user-images.githubusercontent.com/19235498/119382593-879fb480-bcc2-11eb-8f04-503d7c242bd4.png)
Attention that the first question is no and the second yes.

**Comment by Stetocasa** [comment]
> Hello:
> 
> You may not have done the step:
> 
> ![image](https://user-images.githubusercontent.com/19235498/119382593-879fb480-bcc2-11eb-8f04-503d7c242bd4.png)
> 
> Attention that the first question is no and the second yes.

Already done! (And after your message checked again)
No way to detect the device
