### ISSUE TITLE
Zigbee2MQTT

### ISSUE THREAD

**Issue by alansms** [Koenkk/zigbee2mqtt#7590]
# Bug Report
## Debug Info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1 or CC1352P-2
Adapter firmware version:

**Comment by andrewigali** [comment]
Zigbee2MQTT
1.18.3-1

Home Assistant
core-2021.5.5
supervisor-2021.04.3

Problem:
for example with Aqara RTCGQ11LM.
I can't fix the device settings on Device - Settings(specific) page.
If I write:
Property name: occupancy_timeout
Type: Number
Value: 5
and after click the Submit button, nothing happens.

https://user-images.githubusercontent.com/73789218/120222949-12dbf580-c241-11eb-9827-8455f183b372.mp4
