### ISSUE TITLE
Osram AC03642 failed ping

### ISSUE THREAD

**Issue by Calimerorulez** [Koenkk/zigbee2mqtt#7595]
I'm trying to add an Osram AC03642. Pairing went OK, but after a while zigbee2mqtt tries to ping the bulb, and it fails, so it shows offline in HA.

But, the bulb does reports it status, so it shows itself agian. This repeats itself on and on.

```
Zigbee2MQTT:info  2021-05-25 15:55:19: MQTT publish: topic 'zigbee2mqtt/O_La_Slaapkamer', payload '{"brightness":254,"color_mode":"color_temp","color_temp":370,"linkquality":87,"state":"OFF","update":{"state":"idle"},"update_available":false}'
```

```
Zigbee2MQTT:info  2021-05-25 15:58:13: MQTT publish: topic 'zigbee2mqtt/O_La_Slaapkamer/availability', payload 'offline'
Zigbee2MQTT:error 2021-05-25 15:58:13: Failed to ping 'O_La_Slaapkamer'
```

```
Device type Router
Zigbee Model CLA60 TW OSRAM
Description SMART+ CLASSIC A 60 TW
Firmware build date 20140331CNEF****
Firmware version V1.05.10
Manufacturer OSRAM
Model AC03642
```

I'm using a CC1352P-2 as coordinator, with the latest 3.x.0 firmware (januari 2021), and the latest dev-build.

**Comment by ALaDoffe** [comment]
Same issue for me with same devices. All other devices are OK.
After migrating from CC2531 to CC2652P all OSRAM bulbs became unstable.
