### ISSUE TITLE
Lidl livarno HG06104A reparing.

### ISSUE THREAD

**Issue by a323870** [Koenkk/zigbee2mqtt#7596]
## What happened

I replaced in a RPI4 a CC2531 with CC2652R and rerun the paring of the devices.
All device repairing ok except one.

The repairer of Lidl livarno HG06104A is not successful.
How can I do a factory reset for this device that keeps the old paring?

## What did you expect to happen
Factory reset of HG6104A for start paring with new CC2652R

## Debug info
Zigbee2MQTT version: 1.18.3
Adapter hardware: CC26X2R1 zzh!
Adapter firmware version: CC2652R_coordinator_20210120

**Comment by a323870** [comment]
I resolvet to turno on/off for 3 times the devices.

**Comment by 26tajeen** [comment]
I've got this issue but the strip won't repair even with the turn off/on three times fix
