### ISSUE TITLE
Running Zigbee2MQTT & TTY config in configuration.yaml

### ISSUE THREAD

**Issue by fab-gh** [Koenkk/zigbee2mqtt#7601]
The 'Running Zigbee2MQTT' section of 'Getting Started', says:

"As an alternative, the device can also be mapped by an ID. This can be handy if you have multiple serial devices connected to your Raspberry Pi. [...]"

Yes, the Raspberry Pi seems to assign TTY numbers first come - first served, so there's no
guarantee the Zigbee adapter will still be on the same TTY after a reboot. 

As I found out.

So, a different wording could have saved me quite a bit of time,  maybe something like:

"If you have multiple USB devices on a Raspberry Pi, edit the configuration.yaml file,
replacing

 port: /dev/ttyACM0

by

 port:  /dev/serial/by-id/[....]

to be sure your zigbee adapter can always be found. Don't use the TTY number /dev/ttyUSB0 etc."

**Comment by Koenkk** [comment]
Sounds like a good improvement, please create a PR by clicking the pencil icon here: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/getting_started/running_zigbee2mqtt.md
