### ISSUE TITLE
2021 New Gledopto Dimmer GL-SD-001 is Unsupported

### ISSUE THREAD

**Issue by ildmgithub** [Koenkk/zigbee2mqtt#7604]
Hello,
I ordered the new gledopto dimmer GL-SD-001 but it is not supported by zigbee2mqtt. I tried to follow the instructions for adding a new device, but I am stuck.  The instruction to add new devices is not clear for me.

![image](https://user-images.githubusercontent.com/83982417/119563778-ac725580-bdb0-11eb-8fdc-80634b4ea118.png)

## Information about the device + link
https://www.gledopto.eu/zigbee-flush-mounted-triac-dimmer-control-unit-controller-230v-eng

**Comment by ildmgithub** [comment]
Still actually problem

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by bernd-uhl** [comment]
Still actual problem

**Comment by Koenkk** [comment]
Should be fixed now thanks to @Julusian 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by ildmgithub** [comment]
Hello 
When I run zigbee2mqtt edge I see that it is still unsupported.
![image](https://user-images.githubusercontent.com/83982417/132119976-c54d481e-212d-46ee-b6c8-5353758eb981.png)

**Comment by xdmore70** [comment]
I have the same problem, Gledopto device works fine but the frontend report unsopported
![light](https://github.com/user-attachments/assets/646656f2-9fbf-439f-8799-f0e9bf6e0c98)

I use last release frontend and last coordinator firmware
![Screenshot 2024-10-08 150559](https://github.com/user-attachments/assets/e1862474-9010-42d6-a45e-894be5ed8531)

I find this old post, I hope some can help me
