### ISSUE TITLE
Hama 00176593 Thermostat WiFi/Zigbee how to connect ??

### ISSUE THREAD

**Issue by zibous** [Koenkk/zigbee2mqtt#7607]
## Information about the device + link
Signalübertragung | WiFi/Zigbee

https://de.hama.com/00176593/hama-heizungssteuerung-wlan-2x-smartes-heizkoerperthermostat-+-zentrale#technical-details

![Bildschirmfoto 2021-05-26 um 10 07 10](https://user-images.githubusercontent.com/30198737/119625154-2edb3380-be0a-11eb-89f6-4ac5707b46b8.png)

## data/database.db entry of the device
???

```
Zigbee2MQTT version
1.18.3-dev commit: 7fa04cf1
Coordinator type
ConBee2/RaspBee2
Coordinator revision
0x26660700
Frontend version
0.4.1
```

Is there any way to integrate the Hama 00176593?
When I insert the battery, "LA" flashes on the display and when I look in the log, no connection is established

Am I doing something wrong ??

**Comment by zibous** [comment]
Sorry it is working as Saswell SEA801-Zigbee/SEA802-Zigbee 
![p1](https://user-images.githubusercontent.com/30198737/119630408-37823880-be0f-11eb-8019-f4f3b7c7804b.png)

![p2](https://user-images.githubusercontent.com/30198737/119630431-3b15bf80-be0f-11eb-9b71-d23045bcc8ae.png)

**Comment by zibous** [comment]
What am I doing wrong, because the "running_state" is not displayed or is it due to the model 00176593 ???

`running_state:  N/A` ??


![Bildschirmfoto 2021-05-26 um 14 02 41](https://user-images.githubusercontent.com/30198737/119656535-19c2cc80-be2b-11eb-80a0-1a6b206bf546.png)


```json
{
    "anti_scaling": "ON",
    "away_mode": "OFF",
    "battery_low": false,
    "child_lock": "UNLOCK",
    "current_heating_setpoint": 26,
    "frost_detection": "ON",
    "last_seen": "2021-05-26T13:58:17+02:00",
    "local_temperature": 24.6,
    "local_temperature_calibration": 0,
    "preset_mode": "none",
    "system_mode": "heat",
    "window_detection": "ON",
    "device": {
        "applicationVersion": 85,
        "dateCode": "",
        "friendlyName": "thermostat-bad",
        "hardwareVersion": 1,
        "ieeeAddr": "0x5c0272fffec213cd",
        "manufacturerID": 4098,
        "manufacturerName": "_TZE200_yw7cahqs",
        "model": "SEA801-Zigbee/SEA802-Zigbee",
        "networkAddress": 62847,
        "powerSource": "Battery",
        "stackVersion": 0,
        "type": "EndDevice",
        "zclVersion": 3
    },
    "linkquality": 21,
    "elapsed": 24385
}
```

**Comment by NoWhere2Go19** [comment]
Through I don't know which key in the payload the frontend tries to catch to display the "running_state" item, does it really matter here? You are getting all the results you would need and thus can operate the thermostat?
