### ISSUE TITLE
Osram Plug Smart+ connected via Philips Hue Bulb as router

### ISSUE THREAD

**Issue by chrisdaloa** [Koenkk/zigbee2mqtt#762]
I have a Osram Plug Smart+ linked to a Philips Hue Bulb that act as router.

When I try to turn on or turn off it It return this error, both when I use the home assistant switch and when I use MQTT topics
 
> Dec 27 00:08:06 hassbian npm[29985]:   zigbee2mqtt:error 27/12/2018, 00:08:06 Zigbee publish to '0x7cb03eaa0a01ead5', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null failed with error Error: AF data request fails, status code: 233. MAC no ack.

The Plug is connected and visibile as shown in this pictures.

![osram](https://user-images.githubusercontent.com/44293834/50459529-58a77c00-096c-11e9-9c99-1d3b7ca7367a.png)

I tried to delete the db, the config and I tried to pair again all devices but without results.

Thanks

**Comment by Koenkk** [comment]
Does it work when moving it closer to the hue bulb? Keep in mind that the network map is not 100% accurate. 255 is also suspicious link quality as this 100% (which is practically not possible).

**Comment by chrisdaloa** [comment]
The closest attach I have is at lessa than 3 mt. Do you think it's too far?.
 If I put the plug between the bulb and the coordinator, the bulb connect itself to the plug and all works 
![13327c6c-026d-4d21-b823-9951a28096a8](https://user-images.githubusercontent.com/44293834/50496803-ce761b00-0a32-11e9-953f-99069b9c2720.png)
well.

**Comment by Koenkk** [comment]
That would be strange, but keep in mind that zigbee devices can also communicate in a star and tree topology. Something which is not shown in the network map. Unless you are having problems I wouldn't care too much about the networkmap.

**Comment by chrisdaloa** [comment]
My problem is that it does not work where I need it, but It works in other places so it's not a zigbee2mqtt problem, I think :)
Thank you.

**Comment by Koenkk** [comment]
Perhaps there is a lot of interference. https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence explains it quite well.
