### ISSUE TITLE
Second adapter on a remote location

### ISSUE THREAD

**Issue by RedWheiler80** [Koenkk/zigbee2mqtt#7627]
I'm breaking my head around this one, not sure if it's even possible.

I'm using a CC2531 as my adapter in my Raspberry Pi 4.
Besides that, in my house I use also 2 CC2530 routers.

Now I want on a more remote location in my garden (about 50m from my house) also to get on the same network. Of course without placing CC2530 routers all around my garden...

I've a couple of things I can work with: Raspberry Pi Zero W, wifi on that location and another CC2531. Maybe I've even some other things laying around somewhere.

Thank you for this great tool!

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/discussions/7624
