### ISSUE TITLE
Implement binding 

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#765]
Binding allows Zigbee devices to directly control other Zigbee devices and groups without the intervention of zigbee2mqtt or home automation software.

Adding this feature makes it (probably) possible to supported the following devices:
- TRADFRI dimmer (already supported but not really usable as the interval of reports is very low)
- TRADFRI motion sensor
- TRADFRI five button remote

Note that the above devices will still not send any information to MQTT, but this at least makes them usable.

**Comment by trekker25** [comment]
is it possible to add binding without the bridge? Would be awesome if you could bind Hue dimmer remote to Tradfri groups etc

**Comment by Koenkk** [comment]
What do you mean with without the bridge?

**Comment by Koenkk** [comment]
Implemented, see #782

**Comment by dmak** [comment]
Am I right saying that correct binding procedure for Tradfri groups usecase is ([see here](https://community.home-assistant.io/t/ikea-tradfri-gateway-zigbee/14788/140)):
> (1) Peer the remote control with the base/gateway/hub
> (2) Then you go with the prepared remote control to the light and peer that with the remote control.

**Comment by Koenkk** [comment]
First pair it to zigbee2mqtt, then bind it to the bulb

**Comment by msadeghz** [comment]
@Koenkk is it possible to bind a device to hub?

**Comment by Koenkk** [comment]
@msadeghz if by hub you mean coordinator, yes, many `configure` sections for devices do this.

**Comment by msadeghz** [comment]
@Koenkk what do you mean about configure sections? where are them?

**Comment by Koenkk** [comment]
Via MQTT it's not possible, why you want to do this?

**Comment by msadeghz** [comment]
> Via MQTT it's not possible, why you want to do this?

the manufacture said I should bind to receive the device status when I push the physical button on the device.

**Comment by Koenkk** [comment]
@msadeghz this is something that can be done in the `configure` sections, example: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L532
