### ISSUE TITLE
Support for 'LIGHTIFY A19 ON/OFF/DIM 10 Year'

### ISSUE THREAD

**Issue by jeromelaban** [Koenkk/zigbee2mqtt#766]
Version 1.0.1 says the following:

`Device with modelID 'LIGHTIFY A19 ON/OFF/DIM 10 Year' is not supported.`

The device is a `Lightify LED Smart Connected Light A19 Bulb` soft white.

Other references:
`FCCID: DZO-IQHOME`
`IC: 11099A-IQHOME`
`LED10A19/DIM/0FD/10YLFY`

Thanks !

**Comment by Koenkk** [comment]
It is (recently). Please update to the dev branch.

**Comment by jeromelaban** [comment]
Sorry about that! Forgot to look at the converters :)

Also, awesome work on this project!
