### ISSUE TITLE
Philips 9290019758 Hue Motion Sensor no longer supported 

### ISSUE THREAD

**Issue by alexfisch79** [Koenkk/zigbee2mqtt#7663]
After updating Zigbee2MQTT the Philips Hue Motion Sensor has stopped working and is displayed as 
not supported.
Please fix!

Debug info
Zigbee2MQTT version: 1.19.0
Adapter hardware: CC2652RB
Adapter firmware version:

**Comment by rindlerblabla** [comment]
Got two of them as well, and they're still supported in my setup. Running latest dev 1.19.0.

**Comment by alexfisch79** [comment]
After re pairing it works again
