### ISSUE TITLE
Misleading German button translation concerning 'Join all'

### ISSUE THREAD

**Issue by Fridolin34** [Koenkk/zigbee2mqtt#7669]
Hi all,

from my point of view, the text of this button is slightly wrong and leads to confusion.
![image](https://user-images.githubusercontent.com/73740504/120510048-56fa0200-c3c9-11eb-90e7-4b8e88e66437.png)

The text says, currently 'permit join' is active. If you click that, the following is shown:
![image](https://user-images.githubusercontent.com/73740504/120510353-a0e2e800-c3c9-11eb-942c-4ed1d2913c95.png)

That means, joining is not active right now.

I would suggest changing the text to:
'Anlernen aktivieren' and 'Anlernen deaktivieren'

This would make it clear that after clicking the button for the first time, joining all becomes active and the second click would set it back to normal.

Regards,
Fridolin

**Comment by ssiergl** [comment]
Hi,

please open the issue in the frontend repository

https://github.com/nurikk/z2m-frontend

but yes you are right...currently it is wrong translated.
