### ISSUE TITLE
QS-Zigbee-D02-TRIAC-2C-L  (dimmer function not available)

### ISSUE THREAD

**Issue by RafaelDuncan** [Koenkk/zigbee2mqtt#7692]
## What happened
I just added the dimmer to Domiticz and it is recognized immediately by Zigbee2mqtt.
The device is recognized within Domoticz as a Light/Switch. and get 2 types of functions.
- Link Quality
- State (On/Off)

strangely enough, I do not see a dimmer function, while the device does have a dimming function.

## What did you expect to happen
I would expect that the device would also show a separate dimming function.

## Debug info
Zigbee2MQTT version: 1.19.0
Adapter hardware:  CC2652Rb
Adapter firmware version: zStack3x0 20200715

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by RafaelDuncan** [comment]
hello @Koenkk, thanks for your quick response. I hereby send you the requested information. it's about ID9

{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0021cc3b2c","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"10":{"profId":260,"epId":10,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[1281],"outClusterList":[1280,1282],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}
{"id":2,"type":"EndDevice","ieeeAddr":"0xbc33acfffe5273d3","nwkAddr":4971,"manufId":4619,"manufName":"_TZ1800_fcdjzz3s","powerSource":"Battery","modelId":"TY0202","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TY0202","manufacturerName":"_TZ1800_fcdjzz3s","powerSource":3,"zclVersion":1,"appVersion":65,"stackVersion":2,"hwVersion":1,"dateCode":"2019.12.12"}},"ssIasZone":{"attributes":{"iasCieAddr":"0x00124b0021cc3b2c","zoneState":1}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":2,"hwVersion":1,"dateCode":"2019.12.12","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1622964307668}
{"id":3,"type":"Router","ieeeAddr":"0x60a423fffe5e2870","nwkAddr":53436,"manufId":4098,"manufName":"_TZ3000_zmy1waw6","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":9,"inClusterList":[0,4,5,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_zmy1waw6","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1622959354824}
{"id":4,"type":"Router","ieeeAddr":"0x842e14fffe3a4886","nwkAddr":29162,"manufId":4098,"manufName":"_TZ3000_g5xawfcq","powerSource":"Mains (single phase)","modelId":"TS0121","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,6,1794,2820],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_g5xawfcq","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,110]}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1,"rmsVoltage":230,"rmsCurrent":0,"activePower":0}},"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0001575efd","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0001575efd","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1},"lastSeen":1622964316528}
{"id":5,"type":"Router","ieeeAddr":"0x00124b002265dfa0","nwkAddr":33929,"manufId":0,"manufName":"eWeLink","powerSource":"Mains (single phase)","modelId":"ZB-SW01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6],"outClusterList":[0],"clusters":{"genBasic":{"attributes":{"modelId":"ZB-SW01","manufacturerName":"eWeLink","powerSource":1,"zclVersion":1,"appVersion":4,"hwVersion":1,"dateCode":"20201026","swBuildId":"1.0.3"}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":4,"hwVersion":1,"dateCode":"20201026","swBuildId":"1.0.3","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1622964111993}
{"id":6,"type":"Router","ieeeAddr":"0x086bd7fffe5d7e99","nwkAddr":62737,"manufId":4098,"manufName":"Wisdom","powerSource":"Mains (single phase)","modelId":"Dimmer-Switch-ZB3.0","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"Dimmer-Switch-ZB3.0","manufacturerName":"Wisdom","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":6,"hwVersion":1,"dateCode":"20200101","swBuildId":"1.1"}},"genLevelCtrl":{"attributes":{"currentLevel":76}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":8,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":1}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":6,"hwVersion":1,"dateCode":"20200101","swBuildId":"1.1","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-526939472},"lastSeen":1622963074282}
{"id":7,"type":"Router","ieeeAddr":"0x086bd7fffe2a1010","nwkAddr":15021,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E14 W op/ch 400lm","epList":[1],"endpoints":{"1":{"profId":49246,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI bulb E14 W op/ch 400lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":1,"appVersion":17,"stackVersion":87,"hwVersion":1,"dateCode":"20170302","swBuildId":"1.2.214"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":17,"stackVersion":87,"hwVersion":1,"dateCode":"20170302","swBuildId":"1.2.214","zclVersion":1,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1622190455214}
{"id":8,"type":"Router","ieeeAddr":"0x086bd7fffe531fe3","nwkAddr":12450,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Mains (single phase)","modelId":"TRADFRI bulb E14 W op/ch 400lm","epList":[1],"endpoints":{"1":{"profId":49246,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,8,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI bulb E14 W op/ch 400lm","manufacturerName":"IKEA of Sweden","powerSource":1,"zclVersion":1,"appVersion":17,"stackVersion":87,"hwVersion":1,"dateCode":"20170302","swBuildId":"1.2.214"}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":17,"stackVersion":87,"hwVersion":1,"dateCode":"20170302","swBuildId":"1.2.214","zclVersion":1,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1622961755496}
{"id":9,"type":"Router","ieeeAddr":"0x842e14fffe19ee52","nwkAddr":61990,"manufId":4098,"manufName":"_TZ3000_92chsky7","powerSource":"Mains (single phase)","modelId":"TS110F","epList":[1,2],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,4,5,6,8],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS110F","manufacturerName":"_TZ3000_92chsky7","powerSource":1,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"64512":255,"currentLevel":254}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":257,"inClusterList":[4,5,6,8],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"64512":255,"currentLevel":236}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b0021cc3b2c","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-419401481},"lastSeen":1622755852036}

**Comment by Koenkk** [comment]
This looks to be an error on the domoticz side, if you see the dimmer slider through the frontend (https://www.zigbee2mqtt.io/information/frontend.html) you should create an issue here instead: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues

**Comment by RafaelDuncan** [comment]
good afternoon Ken,

 

thanks for your comment. I just created a ticket on the other page. thanks for thinking along.

 

Gr. Rafael

 

 

Van: Koen Kanters ***@***.***> 
Verzonden: maandag 7 juni 2021 10:04
Aan: Koenkk/zigbee2mqtt ***@***.***>
CC: RafaelDuncan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Koenkk/zigbee2mqtt] QS-Zigbee-D02-TRIAC-2C-L (dimmer function not available) (#7692)

 

This looks to be an error on the domoticz side, if you see the dimmer slider through the frontend (https://www.zigbee2mqtt.io/information/frontend.html) you should create an issue here instead: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
