### ISSUE TITLE
failed with error: 'SRSP - UTIL - ledControl after 6000ms'

### ISSUE THREAD

**Issue by acuadulza** [Koenkk/zigbee2mqtt#7693]
## What happened
-  clicking on "permit join" I get  the error shown in the attached picture.
![error](https://user-images.githubusercontent.com/74366767/120711558-d23ddf80-c4bf-11eb-918d-cca7eab04393.png)
- please note that the actual zigbee network works well, but due to this error I am not allowed to add new devices.

## Debug log
![log](https://user-images.githubusercontent.com/74366767/120712257-b4bd4580-c4c0-11eb-9428-19954f2fd96f.png)

## Fixing attempts
- restarted the coordinator
- unistalled and reinstalled zigbee2mqtt
- rebooted Home Assistant 
- added "disable_led: false" to the zigbee2Mqtt configuration as found in previous issues (I also tried with disable_led: true)

## Debug info
HASSIO Version core-2021.5.4
Zigbee2MQTT version 1.19.0 
Coordinator type  zStack12   (CC2530 + CC2592 )
Coordinator revision 20190608
Frontend version 0.4.16

## Network devices
coordinator zStack12   (CC2530 + CC2592)
3 x Aqara temperature/Humidity sensors WSDCGQ11LM
1 x Aqara PIR sensor RTCGQ11LM
1 x Aqara door sensor MCCGQ11LM
![map](https://user-images.githubusercontent.com/74366767/120712441-ec2bf200-c4c0-11eb-81d0-d8f54a988319.png)

**Comment by Fridolin34** [comment]
I don't know, where this is coming from, but occasionally I see the same error. What helps in my case is to shut down HA, unplug the coordination (I'm using cc2531 and CC1352P-2 in two different locations) for like 30 seconds and then restart everything.

**Comment by acuadulza** [comment]
Unfortunately this does not work in my case. The zigbee network works well,
but I cannot add further devices....

Il ven 4 giu 2021, 11:45 Fridolin34 ***@***.***> ha scritto:

**Comment by ykiv63** [comment]
Hi. I've the same Issue with Cc2530

**Comment by Koenkk** [comment]
Fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
