### ISSUE TITLE
 TUYA Light intensity sensor TS0222 problem, no reporting

### ISSUE THREAD

**Issue by HAwidmo** [Koenkk/zigbee2mqtt#7706]
## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by sjorge** [comment]
I briefly had one of those before giving it away, I couldn't configure the reporting settings either. It just send the info when it felt like it (making it hard to get nice consistent graphs). 

Also it max out pretty quickly around 10k IIRC.

**Comment by hankanman** [comment]
Facing the same issue here, can pair them and interview but z2m cannot configure them it seems, haven't seen either of the two I've got report any value other than lqi

**Comment by mgrom** [comment]
Looks like more tuya devices are going to work that way so maybe it's time to figure it out :) I think the best way is to have possibility to replicate 100% identical communication that Tuya GW is sending to the device during configuration. I've spent some time on #7695 and till now no luck with reporting, but tuya gw is able to "force" the device to report.

**Comment by btouchard** [comment]
Same problem
I have a CC2652RB, paring with TS0222 working fine, device appear on devices list.
But no one data on "expose" panel

![image](https://user-images.githubusercontent.com/4984372/124030805-d396f500-d9f6-11eb-80b2-41c7b07cb3c9.png)

Ben

**Comment by elgerg** [comment]
I have a similar Moes Lux display and while i can get reporting working (looks like):
![image](https://user-images.githubusercontent.com/24628571/127658476-94f04522-4c7a-49d1-8d68-57c7d212eeeb.png)

I get some proper random results:
![image](https://user-images.githubusercontent.com/24628571/127658508-c25602b4-c0ea-4e32-a0a7-7026e10e4b68.png)

![image](https://user-images.githubusercontent.com/24628571/127658546-d52f6ea1-616d-4317-a7a1-f74901a18121.png)

Does anyone know what the reporting values should be to make it report the status correctly?

I also suspect that the battery percentage reporting just doesnt work as I did have what i thought was a low battery but it's reporting as 100%..

Any ideas?

Thanks!

**Comment by iglu-sebastian** [comment]
I've got mine to reporting after trying to bind some random endpoints, then it suddenly started.
![image](https://user-images.githubusercontent.com/71284889/129313445-89a3a98a-8f7f-408a-9238-42b00937e576.png)
