### ISSUE TITLE
Ikea Fyrtur battery level always 0%

### ISSUE THREAD

**Issue by jimmyd-be** [Koenkk/zigbee2mqtt#7713]
## What happened
Battery level of Fyrtur is always 0%. Also just after full charge.

## What did you expect to happen
A better reading of the level.

## How to reproduce it (minimal and precise)
Let Fyrtur joins the network and voila 0% battery readings.

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version: 20201127

**Comment by jimmyd-be** [comment]
Fixed automaticly after one hour and a firmware update.

**Comment by MattWestb** [comment]
Great to knowing the new firmware for the blinds is working :-)))
