### ISSUE TITLE
Errors from Sonoff SNZB-04 in version 1.19.1-1

### ISSUE THREAD

**Issue by urkoin** [Koenkk/zigbee2mqtt#7721]
No data from the Sonoff SNZB-04. when trying to reconfigure, got this error:

Zigbee2MQTT:error 2021-06-07 13:39:42: Failed to configure 'Sensor_Puerta_Casa', attempt 1 (Error: Bind 0x00124b00226af5c2/1 genPowerCfg from '0x00124b001ccdf646/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7))

It is happening with all sonoff zigbee devices of the same model.

## Debug info
Zigbee2MQTT version: 1.19.1-1
Adapter hardware: CC2531
Adapter firmware version:

**Comment by sjorge** [comment]
Try pushing the button a few times while z2m restarts, looks like a previous configure() was not completed.
