### ISSUE TITLE
Send friendly name instead of IEEE address when a device leave the network

### ISSUE THREAD

**Issue by rindlerblabla** [Koenkk/zigbee2mqtt#7725]
## What happened
Just eight seconds after Z2M received a power state from Innr sp120 it left the network. Don't know why, really. However, the json that was posted included the message 
```
info  2021-06-06 02:16:10: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"ieee_address":"0x00158d0003288af0"},"type":"device_leave"}'
info  2021-06-06 02:16:10: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"left_network","meta":{"friendly_name":"0x00158d0003288af0"},"type":"device_removed"}'
```
Have now set up an automation in HA which listens to bridge/log events with payload `left_network` (I think, hehe), but the device name being posted is not the friendly_name but the IEEE address.

## What did you expect to happen
That the `friendly_name` would include the friendly_name, not the IEEE address.  Then it would be easier to understand what device really left the network.

## Debug info
Zigbee2MQTT version 1.19.0-dev commit: 9f02eb3
Coordinator type zStack3x0
Coordinator revision 20210120
Frontend version 0.4.16

**Comment by Koenkk** [comment]
Implemented.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
