### ISSUE TITLE
Problem with cover after updating Home Assistant

### ISSUE THREAD

**Issue by Lastik-Lastikov** [Koenkk/zigbee2mqtt#7744]
Home Assistant 2021.6 have that in release notes:
Peviously deprecated features of MQTT cover have been removed:

Using **value_template** to use for extracting position is no longer allowed an error will be raised if this configuration is used, Instead of using value_template, **position_template** should be used.
tilt_invert_state is removed, instead tilt_min and tilt_max should be used, error will be raised if this is found in configuration.

After update HA the curtains stopped working

So, at zigbee2mqtt v1.18.1  Home Assistant integration have incorrect config, **value_template** need to replace to **position_template**:
```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "command_topic": "zigbee2mqtt/Curtain1floor/set",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x00158d00054b4530"
    ],
    "manufacturer": "Xiaomi",
    "model": "Aqara curtain motor (ZNCLDJ11LM)",
    "name": "Curtain1floor",
    "sw_version": "Zigbee2MQTT 1.18.1"
  },
  "json_attributes_topic": "zigbee2mqtt/Curtain1floor",
  "name": "Curtain1floor",
  "position_topic": "zigbee2mqtt/Curtain1floor",
  "set_position_template": "{ \"position\": {{ position }} }",
  "set_position_topic": "zigbee2mqtt/Curtain1floor/set",
  "unique_id": "0x00158d00054b4530_cover_zigbee2mqtt",
  "position_template": "{{ value_json.position }}"
}
```

**Comment by Koenkk** [comment]
Already fixed in z2m 1.19.0, if you don't see the update check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
