### ISSUE TITLE
Need help for adding GLEDOPTO GL-SD-001

### ISSUE THREAD

**Issue by BudBundi** [Koenkk/zigbee2mqtt#7750]
## Information about the device + link
Hello, I try to add support for the GLEDOPTO GL-SD-001
https://www.gledopto.eu/zigbee-flush-mounted-triac-dimmer-control-unit-controller-230v-eng
It is a Zigbee 3,0 Smart Home Triac AC Dimmer
it looks similar to the Namron ZigBee dimmer 400W https://www.zigbee2mqtt.io/devices/4512700.html
so I try to copy the converter
I add an external converter with this content

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['GL-SD-001'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'GL-SD-001', // Vendor model number, look on the device for a model number
    vendor: 'GLEDOPTO', // Vendor of the device (only used for documentation and startup logging)
    description: 'GELDOPTO Zigbee 3.0 Smart Home Triac AC Dimmer', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    extend: extend.light_onoff_brightness({noConfigure: true}),
        configure: async (device, coordinatorEndpoint, logger) => {
            await extend.light_onoff_brightness().configure(device, coordinatorEndpoint, logger);
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff', 'genLevelCtrl']);
            await reporting.onOff(endpoint);
        },
};

module.exports = definition;
```

it seems to work, but I get an error in the logs if I try to change the brightness
```
Zigbee2MQTT:error 2021-06-10 22:03:56: Publish 'set' 'brightness' to '0x84fd27fffebb91db' failed: 'Error: Command 0x84fd27fffebb91db/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 34852 - 1 - 105 - 8 - 11 after 10000ms)'
Zigbee2MQTT:debug 2021-06-10 22:03:56: Error: Command 0x84fd27fffebb91db/1 genLevelCtrl.moveToLevelWithOnOff({"level":254,"transtime":0}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 34852 - 1 - 105 - 8 - 11 after 10000ms)
```

## data/database.db entry of the device
`{"id":100,"type":"Router","ieeeAddr":"0x84fd27fffebb91db","nwkAddr":34852,"manufId":4687,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-SD-001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,4096],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"GL-SD-001","manufacturerName":"GLEDOPTO","powerSource":0,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"20210322","swBuildId":"v_1_1_3"}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":200}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca15641","endpointID":1},{"cluster":8,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca15641","endpointID":1}],"configuredReportings":[{"cluster":8,"attrId":0,"minRepIntval":3,"maxRepIntval":300,"repChange":1},{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":1,"dateCode":"20210322","swBuildId":"v_1_1_3","zclVersion":3,"interviewCompleted":true,"meta":{"reporting":1,"configured":1461352984},"lastSeen":1623355093964}`

**Comment by w00dwind** [comment]
I have the same issue. On-off works good, but brightness change don't work
