### ISSUE TITLE
npm install reports npm ERR! fetch failed

### ISSUE THREAD

**Issue by niekvlessert** [Koenkk/zigbee2mqtt#776]
When running npm install I got npm ERR! fetch failed on (I guess) all dependencies.

Just 2 of them:
npm ERR! fetch failed https://registry.npmjs.org/object-visit/-/object-visit-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/objectbox/-/objectbox-0.3.0.tgz

The report stated I had bad network settings, but that was not the case, wget on those URLs works just fine.

Eventually I changed all entries in npm-shrinkwrap.json from https to http and the problems were gone. It was just a random try to find out the problem, no idea why it changed anything. Everything works fine now. Thanks for all the effort btw!!

It's on the latest Raspbian on a Pi 1B. I followed https://koenkk.github.io/zigbee2mqtt/getting_started/running_zigbee2mqtt.html, but in there is  sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - which won't work on ArmV6. So I used the Raspbian versions. Which, as stated, work fine!

**Comment by niekvlessert** [comment]
No, or the default Raspbian installation is doing things I don't know. But since wget works fine on the same URL on https I guess it's not that.

I guess it will be hard to figure out what it is, maybe just close the ticket and when someone has this issue they can find this workaround in the issue history...

**Comment by Koenkk** [comment]
It seems to be a npm issue.
