### ISSUE TITLE
Ikea Tradfri LED1934G3

### ISSUE THREAD

**Issue by sliwma** [Koenkk/zigbee2mqtt#7780]
## Information about the device + link
According to the z2m's list, currently not supported.
https://www.ikea.com/pl/pl/p/tradfri-zarowka-led-e27-250-lumenow-bezprzewodowy-przyciemniany-cieply-bialy-kula-przezroczysta-40439254/ (PL)
Not available in my city (yet), I'll try to check them as soon as I got them.

**Comment by Koenkk** [comment]
Added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/2741

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
