### ISSUE TITLE
Restore to last known states after a powerloss

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee2mqtt#7782]
If there are a power loss in the house and the power are restored after lets say 15 minutes, all devices connected to the mains get turned on. This includes lights, power plugs etc.

This is not a good behavior.

Z2M constantly stores all states and are well aware of every devices last state. Upon a power loss/restore, on startup Z2M should restore all devices back to the last known state.

Example:
My summer house has power plugs for fan control and 16 lights. If there are a power loss followed with a restore, all lights are suddenly on, and the power plug (Philips) are turned on.

**Comment by sjorge** [comment]
You can use the `power_on_behavior` attribute to set the desired state: https://github.com/Koenkk/zigbee-herdsman-converters/blob/7b54db86ca5fcc7d719cd4325cace2426cd7c4fc/converters/toZigbee.js#L81

However this doesn't work for all bulbs/plugs...
For me it works for trådfri, tint, innr, but it doesn't work for osram.

For Hue there is a `hue_power_on_behavior` https://github.com/Koenkk/zigbee-herdsman-converters/blob/7b54db86ca5fcc7d719cd4325cace2426cd7c4fc/converters/toZigbee.js#L1534

As I have a few of those devices that don't work or are buggy (looking at you Ubisys) I also wrote this https://github.com/Koenkk/zigbee2mqtt/discussions/7642 

I just use this to set all my in wall switches to ON and all the remaining lights to OFF.
