### ISSUE TITLE
Crash when calling remove_all

### ISSUE THREAD

**Issue by YodaDaCoda** [Koenkk/zigbee2mqtt#7785]
Running z2m v1.19.1

Following the [groups](https://www.zigbee2mqtt.io/information/groups.html) documentation to call `zigbee2mqtt/bridge/request/group/members/remove_all` with a device specified results in a traceback and z2m restarts. This occurs whether or not a group is specified in the payload (docs specifically say it can be excluded for `remove_all` but I checked with and without).

Pastebin of log output: https://pastebin.ubuntu.com/p/3nPBnMmcsm/

**Comment by Koenkk** [comment]
Should be fixed now, can you confirm?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by YodaDaCoda** [comment]
@Koenkk Sorry, I lost track of this. Was it included in the v1.20 release or do I still need to switch to the dev branch to test?

**Comment by Koenkk** [comment]
It is in 1.20.0 indeed
