### ISSUE TITLE
Aldi 141L100RC show up as unsupported. 

### ISSUE THREAD

**Issue by maximklein** [Koenkk/zigbee2mqtt#7798]
Hello folks,

I got some of the Aldi Remotes real cheap, and wanted to use them via zigbee2mqtt. Pairing works great, but they wont show up as supported, although they are listed in the supported devices list. I hope someone can help me. 

Really appreciate the great work you´re doing here!
# Bug Report
## What happened

Wanted to pair some of the Aldi 141L100RC Remotes. But they show up as unsupported. 

## What did you expect to happen

Expected them to work because they are listed in the supported device database.

## How to reproduce it (minimal and precise)

Tried to repair it for minimum 10 times but they wont work

## Debug Info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: CC2538

**Comment by Koenkk** [comment]
This device has been added in 1.18.3, you are on 1.18.1, 
If you don't see the update check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0
