### ISSUE TITLE
LLKZMK11LM. How downgrade to firmware build date 02-27-2019?

### ISSUE THREAD

**Issue by xrays72** [Koenkk/zigbee2mqtt#7828]
Hello. Early versions of z2m had an ota update feature for LLKZMK11LM. I did this and got Firmware build date 8-6-2020 and stopped receiving data on tempurature, energy and voltage. I tried to remove the device in force mode and renew connected but that didn't solve the problem. Yesterday I bought another LLKZMK11LM relay, which by default has Firmware build date 02-27-2019 and received data on temperature, energy and voltage on this LLKZMK11LM.
Please help me to downgrade to firmware build date 02-27-2019 or advise what I can do.
Thank you.

**Comment by Koenkk** [comment]
Dupe of #7112
