### ISSUE TITLE
Nue / 3A HGZB-20A Power on behavior

### ISSUE THREAD

**Issue by kmorrow429** [Koenkk/zigbee2mqtt#7834]
I know that power_on_behavior can be set for a number of devices on z2m, but it doesn't seem to work for the Nue / 3A HGZB-20A plug.

When I run the command:
zigbee2mqtt/friendly name/set {"power_on_behavior": "on"}

I get this from the log:
"No converter available for 'power_on_behavior' (on)"

As the product is compatible with hue I had tried hue_power_on_behavior as well, but this also doesn't work.

Is it possible that this feature can be implemented for this device? Thanks.

**Comment by kmorrow429** [comment]
Bump

**Comment by Koenkk** [comment]
Can you try adding `tz.power_on_behavior`, then it might work with: `zigbee2mqtt/friendly name/set` `{"power_on_behavior": "on"}` (or `off`, `toggle` or `previous`). If it doesn't work this device does not support the standard Zigbee command. Then it could be that Nue implemented a manufacturer-specific command (like hue) but this would require enabling this functionality with the original gateway (if it even has this functionality).
