### ISSUE TITLE
Support for Zigbee 3.0 Itead Dongle

### ISSUE THREAD

**Issue by neuman1812** [Koenkk/zigbee2mqtt#7842]
## Information about the device + link

https://itead.cc/product/zigbee-3-0-usb-dongle/

## data/database.db entry of the device
..

**Comment by Koenkk** [comment]
Support is already experimental: https://www.zigbee2mqtt.io/information/supported_adapters.html (Silicon Labs EZSP v8), more info https://github.com/Koenkk/zigbee-herdsman/issues/319
