### ISSUE TITLE
Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms

### ISSUE THREAD

**Issue by rogu22** [Koenkk/zigbee2mqtt#7847]
_Every few days, my Zigbee devices stop responding. 
The only way to fix the problem is to unplugging and replugging adapter cc2530 
and it all works perfectly again for a few days until it happens again._

I found in this tutorial https://www.zigbee2mqtt.io/information/FAQ.html
that this problem appered than maybe consider upgrading to more powerful adapter?

## What happened
Zigbee2MQTT:error 2021-06-17 11:42:06: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-06-17 11:42:06: Failed to start zigbee
Zigbee2MQTT:error 2021-06-17 11:42:06: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-06-17 11:42:06: Exiting...
Zigbee2MQTT:error 2021-06-17 11:42:06: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:93:31)
    at Generator.throw [(<anonymous>)]
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.19.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.19.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-17T09_42_06_529Z-debug.log

debug  #herdsman: attached as log1 and log2 because paste bin can accept only 512kb

[log1.txt](https://github.com/Koenkk/zigbee2mqtt/files/6689220/log1.txt)
[log0.txt](https://github.com/Koenkk/zigbee2mqtt/files/6689215/log0.txt)

## Debug info
Zigbee2MQTT version: 1.19.1-1
Adapter hardware: CC2530+CC2591
Adapter firmware version:
Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20190523,"transportrev":2},"type":"zStack30x"}'
Home Assistant 2021.6.6
supervisor-2021.06.3

mqtt configuration:
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.60:1883
  user: mqtt
  password: mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
advanced:
  pan_id: 6754
  channel: 11
  rtscts: false
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true

**Comment by Koenkk** [comment]
See second point of https://www.zigbee2mqtt.io/information/FAQ.html#error-srsp---sys---ping-after-6000ms

- I see you are running the zstack 3.0.x firmware on a cc2530, this is not recommended since the cc2530 is not powerful enough. Switching to https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing might improve it 
- If that doesn't help update to a more powerful adapter as mentioned in the FAQ.
