### ISSUE TITLE
Lonsonho QS-Zigbee-C01 - Problem cover entity with 'state'

### ISSUE THREAD

**Issue by falbalala** [Koenkk/zigbee2mqtt#7859]
## What happened
There is a problem with the channel exposes "cover".
For this device, the "cover" channel manages "state" and "position". 
For "position", no problem. On the other hand, it is "state" or there is a problem. Unable to retrieve its value with "GET" or to assign a new state with "SET". Its value is always "null".
In the loginfo I have the following error: `No converter available for 'get' 'state' ()`

## How to reproduce it (minimal and precise)
```
{
    "calibration": "OFF",
    "linkquality": 76,
    "motor_reversal": "OFF",
    "moving": "STOP",
    "position": 100,
    "state": null
}
```

## Debug info
Zigbee2MQTT version: 1.19.1
Adapter hardware: CC2531
Adapter firmware version: zStack12 20201127

**Comment by SimonSezKossel** [comment]
I think i have the same problem.

Suddenly having a greyed out move blind entity.
Adding a new device does not even add this entity. 
![image](https://user-images.githubusercontent.com/17459997/125103083-4a5d7d80-e0dc-11eb-95d7-8102f1715fbb.png)

In the Zigbee2mqtt its just functional:
![image](https://user-images.githubusercontent.com/17459997/125103477-acb67e00-e0dc-11eb-9c0f-df2a166f1ad3.png)

**Comment by RamblingGeekUK** [comment]
I'm having the same issue with IKEA E1926, it works in Zigbee2MQTT but can't see position, open, close state's in HA.  This was working, I had to start due to SD card corruption, and now it's not pulling through.

**Comment by s3rgi** [comment]
I'm having the same issue, when re-pairing the device does not even add "cover" entity, only sensors like quality, motor_reversal and moving are available

**Comment by SimonSezKossel** [comment]
I was able to solve my isssues by updating to the latent version of zigbee2mqtt.
