### ISSUE TITLE
Invalid checksum for motion sensor RTCGQ11LM

### ISSUE THREAD

**Issue by peterforeman** [Koenkk/zigbee2mqtt#786]
I have three RTCGQ11LM's paired with my CC2530. Running latest coordinator firmware and zigbee2mqtt 1.0.1. After pairing they never report motion ("occupancy"), only a message every hour or so.

Debugging gives me this:

```
  cc-znp Error: Invalid checksum
  cc-znp     at CcZnp._parseMtIncomingData (/app/node_modules/cc-znp/lib/ccznp.js:323:19)
  cc-znp     at Unpi.parseMtIncomingData (/app/node_modules/cc-znp/lib/ccznp.js:92:18)
  cc-znp     at emitOne (events.js:116:13)
  cc-znp     at Unpi.emit (events.js:211:7)
  cc-znp     at Dissolve.<anonymous> (/app/node_modules/unpi/index.js:107:14)
  cc-znp     at emitOne (events.js:116:13)
  cc-znp     at Dissolve.emit (events.js:211:7)
  cc-znp     at Dissolve.<anonymous> (/app/node_modules/dissolve-chunks/index.js:73:29)
  cc-znp     at emitNone (events.js:106:13)
  cc-znp     at Dissolve.emit (events.js:208:7) +8s
```
(complete log: https://pastebin.com/aPHPbNgF)

Tried re-pairing, flashing CC2530 again etc.etc..

After commenting out the checksum check and waving my hand in front of the sensor it immediately gives this:

```
cc-znp { sof: 254,
  cc-znp   len: 28,
  cc-znp   type: 'AREQ',
  cc-znp   subsys: 'AF',
  cc-znp   cmd: 'incomingMsg',
  cc-znp   payload:
  cc-znp    { groupid: 0,
  cc-znp      clusterid: 1024,
  cc-znp      srcaddr: 6981,
  cc-znp      srcendpoint: 1,
  cc-znp      dstendpoint: 1,
  cc-znp      wasbroadcast: 0,
  cc-znp      linkquality: 34,
  cc-znp      securityuse: 0,
  cc-znp      timestamp: 9586059,
  cc-znp      transseqnumber: 0,
  cc-znp      len: 8,
  cc-znp      data: <Buffer 18 14 0a 00 00 21 07 00> },
  cc-znp   fcs: 254,
  cc-znp   csum: 27 } +14s
  cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 1024, srcaddr: 6981, srcendpoint: 1, dstendpoint: 1, wasbroadcast: 0, linkquality: 34, securityuse: 0, timestamp: 9586059, transseqnumber: 0, len: 8, data: <Buffer 18 14 0a 00 00 21 07 00> } +1ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: [object Object] +1ms
  zigbee-shepherd:msgHdlr IND <-- AF:incomingMsg, transId: 0 +2ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: [object Object] +1ms
  zigbee2mqtt:info 2018-12-31 15:32:26 MQTT publish: topic 'zigbee2mqtt/0x00158d0001dda9cd', payload '{"illuminance":7,"linkquality":34,"occupancy":false,"battery":99,"voltage":3015}'
```

As you can see the fcs != csum, and occupancy is still "false".

Any ideas?

**Comment by Koenkk** [comment]
Could you post your log with `log_level: debug` ? (https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html)

**Comment by chaertl1** [comment]
I've got the same problem with an Aqara motion sensor

**Comment by Koenkk** [comment]
How is the CC2530 connected?

**Comment by Koenkk** [comment]
Which pins did you connect?

**Comment by chaertl1** [comment]
CC2530  CP210X
VCC       3V3 
P02        TXD
P01        RXD
GND      GND

**Comment by peterforeman** [comment]
Same for me. Attached with USB<>Serial CP210X with same pins. Everything worked fine, except for the motion sensor which reported wrong checksums.

**Comment by Koenkk** [comment]
I will check this once I receive my CP210x

**Comment by chaertl1** [comment]
Good morning.
I also tested with a CH340 USB->serial converter with the same results.
I will try to find a controller that supports rtscts.

**Comment by chaertl1** [comment]
@peterforeman 
Can you reopen this topic please.
It looks like more people are having problems with the human body sensors on a cc2530

**Comment by wimpie007** [comment]
got the samen issue.
Body sensor RTCGQ11LM stops working after upgrading.
Sensor reports data, and is seen in the log, but "Device with modelID 'undefined' is not supported" show up.... Sensor useless on this moment.
Both in 'stable' and in edge version (hassio)
