### ISSUE TITLE
How to make manual sensors for sensor's batteries now?

### ISSUE THREAD

**Issue by MikeVRT** [Koenkk/zigbee2mqtt#787]
Befor 1.0.x zigbee2mqtt and 0.84.x HASS we make manual battary sensor like this (sensors.yaml in HASS):

- platform: mqtt
    state_topic: "zigbee2mqtt/sensor_name"
    name: hall_thp_battery
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_available: "online"
    payload_not_available: "offline"
    unit_of_measurement: '%'
    device_class: battery
    value_template: "{{ value_json.battery|round(0) }}"
    json_attributes:
      - "voltage"
      - "linkquality"

Where sensor_name - friendly_name from zigbee2mqtt's configuration.yaml

Now, after last breaking changes in zigbee2mqtt & HASS...
Battery sensors made like this (sensor_name takes from HASS' GUI) reports:
1. 'unknown' for sensors like temperature
2. for binary sensors like door&window, smoke, water leak - we have in HASS's intergration separated battery sensor (not manual!) - it works ok.

So. How now to build list of batteries from all sensors without separated battery sensor?

**Comment by Koenkk** [comment]
For `sensor` the battery is included in the sensor itself (see screenshot below). If you want a separate sensor for those, the above configuration is OK. Just make sure you put the correct `state_topic`.


![image](https://user-images.githubusercontent.com/2892853/50575996-ea016d00-0e08-11e9-8f08-7c73cc9d4b54.png)

**Comment by MikeVRT** [comment]
> Just make sure you put the correct `state_topic`

As I see - now sensor generates 3 named sensors:
sensor.sensor_name_temperature
sensor.sensor_name_pressure
sensor.sensor_name_humidity
May I use any of this or must use "core" not named sensor like "zigbee2mqtt/0x00193d00023235d8" like MQTT publish topic in log?

**Comment by Koenkk** [comment]
Once the device is discovered by hass, the name in hass wont update when changing the friendly_name in the zigbee2mqtt configuration.yaml. You can only change it via hass itself after that.

**Comment by MikeVRT** [comment]
Thx, manual rename in core.device_registry (value in "name") works well - after that I can use in manual sensors not MAC but friendly name.

**Comment by MikeVRT** [comment]
I made additional rename tests - friendly_names from zigbee2mqtt's works good. After restarts all updated in HASS.

But another part - precision - ignored by HASS :(
> devices:
>   '0x00158d000936335c1':
>     friendly_name: hall_thp
>     temperature_precision: 1
>     humidity_precision: 0
>     retain: false

**Comment by talondnb** [comment]
> Another thing - "buildin" binary sensors's battery sensors have no '%' unit_of_measurement and uses "1D histogram" instead graphic. So, list of mixed manual and buildin batteries looks not so good :)
> 
> p.s. may be someone know - why binary sensors have separated "buildin" battery sensors and ordinary sensors - not?

I second this; would be good to have the '%' unit of measurement built into the sensors to conform with other battery entities.

https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/551

**Comment by Koenkk** [comment]
- battery sensor now has a % unit.
- devices which support battery now have a separate battery sensor.

**Comment by MikeVRT** [comment]
@Koenkk, excellent work. I'll update.

p.s. temperature_precision & humidity_precision still broken?

**Comment by Koenkk** [comment]
@MikeVRT fixed in the dev branch, can this be closed?

**Comment by MikeVRT** [comment]
Ok (when planning release 1.0.2?)

**Comment by Koenkk** [comment]
@MikeVRT hope within a week, need to verify the stability of the new firmware with group support first.
