### ISSUE TITLE
Weird brightness behaviour of GL-C-007-1ID after plugging in

### ISSUE THREAD

**Issue by arturdobo** [Koenkk/zigbee2mqtt#7883]
## What happened

I experience weird behavior of the brightness setting after GL-C-007-1ID is plugged in, see scenario below. I own 2 devices and both work exactly the same

## What did you expect to happen

Similar to GL-C-009, after plugging in brightness setting is kept

## How to reproduce it (minimal and precise)

* set brightness to anything different than max
* plug out electricity source
* plug it in again
* brightness is set to max

## Debug info
Zigbee2MQTT version: 1.19.1
Adapter hardware: CC2652R (zzh)
Adapter firmware version: 20201026

**Comment by Koenkk** [comment]
This cannot be solved from z2m since it's the behavior of the firmware on the device. Many Zigbee bulbs restore their brightness after getting connected to electricity again.
