### ISSUE TITLE
Incorrect device type

### ISSUE THREAD

**Issue by Anonymenet77** [Koenkk/zigbee2mqtt#7895]
Hello,

Device type incorrectly identified TS0216 not a router.

Best regards,

<a href='https://www.casimages.com/i/210628025642244393.jpg.html' target='_blank' title='Mon image'><img src='https://nsa40.casimages.com/img/2021/06/28/210628025642244393.jpg' border='0' alt='Mon image' /></a>

**Comment by Koenkk** [comment]
Fixed.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
@rindlerblabla that depends on the device itself, how z2m recognises it is only a cosmetic thing, it doesn't have any influence on the actual behaviour of the device.
