### ISSUE TITLE
ajouter un appareil TRADFRIbulbE27WWclear250lm -Ampoule LED IKEA

### ISSUE THREAD

**Issue by VASNIER** [Koenkk/zigbee2mqtt#7908]
Hello
Je souhaiterai pouvoir intégrer un nouvelle ampoule LED IKEA (TRADFRIbulbE27WWclear250lm) en Zigbee2MQTT dans Gladys.

Merci pour votre aide

{
  "name": "0x680ae2fffe4c9018",
  "external_id": "zigbee2mqtt:0x680ae2fffe4c9018",
  "model": "TRADFRIbulbE27WWclear250lm",
  "features": [],
  "should_poll": false,
  "service_id": "8f5634d8-e97e-43f8-806f-bd8ed12a4811",
  "supported": false
}

**Comment by toxictaste1981** [comment]
opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/ikea.js

add this

{
        zigbeeModel: ['TRADFRI bulb E27 WW clear 250lm', 'TRADFRI bulb E26 WW clear 250lm'],
        model: '1934G3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 WW clear 250 lumen, dimmable',
        extend: tradfriExtend.light_onoff_brightness(),
    },

after this
{
        zigbeeModel: ['TRADFRI bulb E27 WW clear 250lm', 'TRADFRI bulb E26 WW clear 250lm'],
        model: 'LED1842G3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 WW clear 250 lumen, dimmable',
        extend: tradfriExtend.light_onoff_brightness(),
    },

**Comment by toxictaste1981** [comment]
change in file /opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices
`
    {
        zigbeeModel: ['TRADFRI bulb E27 WW clear 250lm', 'TRADFRI bulb E26 WW clear 250lm'],
        model: 'LED1842G3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 WW clear 250 lumen, dimmable',
        extend: tradfriExtend.light_onoff_brightness(),
    },
`
to
`
	{
        zigbeeModel: ['TRADFRI bulb E27 WW clear 250lm', 'TRADFRI bulb E26 WW clear 250lm','TRADFRIbulbE27WWclear250lm'],
        model: 'LED1842G3/1934G3',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E27 WW clear 250 lumen, dimmable',
        extend: tradfriExtend.light_onoff_brightness(),
    },
`
after that it run for me

**Comment by VASNIER** [comment]
Hello
Je n'ai pas de fichier "opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/ikea.js"
Où devrait-il se trouver?
