### ISSUE TITLE
Docker image - config file not respected?

### ISSUE THREAD

**Issue by greynoO** [Koenkk/zigbee2mqtt#791]
I am trying to run the latest docker image on a Raspberry PI 3B+. Everything was done as described here:

https://koenkk.github.io/zigbee2mqtt/information/docker.html

First of all, the `--device` command does nothing for me, the created configuration.yaml still has `/dev/ttyACM0` but I want `/dev/tty/USB0`.

Even after I modify the config accordingly and restart the container with this command:
```
docker run \
   -it \
   -v $(pwd)/data:/app/data \
   koenkk/zigbee2mqtt:arm32v6
```
I still get this error:

```
{"message":"Error: No such file or directory, cannot open /dev/ttyACM0","stack":"Error: Error: No such file or directory, cannot open /dev/ttyACM0"}
```

So the config file is not respected at all.

Any help would be appreciated! Thanks!

**Comment by greynoO** [comment]
Was only an issue when using as standalone installation not with hass.io

**Comment by Koenkk** [comment]
`--device` is a docker command, it's not related to zigbee2mqtt. 

`--device` is need to map the device inside the docker image. This device than has to be specified in `configuration.yaml`.

**Comment by greynoO** [comment]
Thanks, maybe add 

`--device=/dev/ttyACM0`: Location of CC2531 USB sniffer (as defined in configuration.yaml)

to make that clear. Maybe I was just too tired already :)
