### ISSUE TITLE
SilverCrest HG06335 Motion Sensor tamper-value seems to be incorrect, (possibly) resulting in incorrect working device

### ISSUE THREAD

**Issue by raemeijer** [Koenkk/zigbee2mqtt#7919]
_Good day! This is my first ever GitHub-post and logged issue, so I assume I might have made some error and/or did not supply all the required and/or relevant information. If this is the case, please feel free to let me know. Thanks in advance for looking at this issue!_

### **## What happened**
After succesfully pairing my supported HG06335 Motion Sensor with Zigbee2MQTT, the "tamper"-property value defaults to "true" while the tamper button (on the device backside) is not being pressed, and despite registering motions, the motion sensor is the only device that does not seem to work together using Zigbee2MQTT, while my other Zigbee-appliances work properly.

### **## What did you expect to happen**
The Zigbee2MQTT.io page states an unpressed tamper button should result in value "false" for property "tamper", while the opposite is actually true - I did not expect this to happen. I'm not 100% certain yet, but I fear the tamper property-value might be interpreted as "true" while it is actually "false".

### **## How to reproduce it (minimal and precise)**
- Pair HG06335 with Lidl Home Hub, create automations based on motion sensor triggers, and registered motion results in succesful automation.
- Disconnect from Lidl Home Hub, pair with Zigbee2MQTT CC2652RB, create automations, and registered motion does not result in succesful automation.

### **## Debug info**
Zigbee2MQTT version: 1.19.1
Adapter hardware: CC2652RB
Adapter firmware version: Zigbee2MQTT

[https://www.zigbee2mqtt.io/devices/HG06335.html#tamper](https://www.zigbee2mqtt.io/devices/HG06335.html#tamper)

**Comment by DavyRoswinkel** [comment]
I think you are making a mistake. If the tamper button is pressed then it's not tampered with ( mounted securely on a wall of ceiling, it's pressed) If the button is released the sensor is being tampered with.  Maybe the text on zigbee2mqtt.io is a bit off...( eh..wrong)
