### ISSUE TITLE
Unable to open or close cover group

### ISSUE THREAD

**Issue by supercrw** [Koenkk/zigbee2mqtt#7922]
Hi,

I tried out the new group feature that publishes an entity to Home Assistant. I have tried to add two FYRTUR covers from IKEA but I am receiving and error when trying to open and close the covers. 

There seems to be an issues with the command that is sent from Home Assistant to Z2M. I have attached a link to the log. 

https://pastebin.com/j5AT1GWV

**Comment by Koenkk** [comment]
This should be fixed now, if not, make sure that your group contains only covers.
