### ISSUE TITLE
TS004F Switch Buttons not working, only Battery Status

### ISSUE THREAD

**Issue by J-117** [Koenkk/zigbee2mqtt#7925]
TS004F will only Report when you press the upper left button, then it reports Battery Status and Link Strength,

Other Buttons will not Report any State (Logs in Debug Mode)

Using Standard Configuration just adding the Device through learn, also tryed multiple devices -> same Problem

**Comment by heroiamarelo1** [comment]
I'm having the same issue.
Zigbee Dongle USB - Sonoff CC2531

![Screenshot_20210708-234706_Home Assistant](https://user-images.githubusercontent.com/86858065/125005570-fad36f00-e053-11eb-9aa1-0352ee3f149e.jpg)
![Screenshot_20210708-234710_Home Assistant](https://user-images.githubusercontent.com/86858065/125005573-fb6c0580-e053-11eb-9ca3-53723768bc30.jpg)
![Screenshot_20210708-235329_Home Assistant](https://user-images.githubusercontent.com/86858065/125005574-fc049c00-e053-11eb-825d-6c9ec6982566.jpg)

**Comment by J-117** [comment]
Yes i get the exact same Messages, maybe its the Dongle? Is your Dongle already flashed, mine should be as i bought it as flashed, maybe someone has another Dongle to try,

Kind Regards,

**Comment by J-117** [comment]
Tested with a Conbee 2, and it works, all Buttons send their respective individual Payload, seems to be a Problem with the Dongle

**Comment by heroiamarelo1** [comment]
Hello. Sorry for the offtopic but how did you do it? I added my switches to conbee II and conbee assumes the switches are lights. Two of the commands work to power on and off the lights (no idea why!) the other two buttons do nothing. I can't sign any commands because they are considered lights instead of switches, even in home assistant.
