### ISSUE TITLE
Problem to connect LEGRAND 067726 (white version of 067776) Only Router device

### ISSUE THREAD

**Issue by SMJ33160** [Koenkk/zigbee2mqtt#7930]
## What happened
Only the router device is recognized not dimmer device in domoticZ
I have warn message like "Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined" in status message of zigbee2MQTT

## What did you expect to happen
I expect to have a dimmer device in DOMOTICZ inteface -using Zigbee2MQTT plugin last version

## Debug info
Zigbee2MQTT version: 1.19.1
Adapter hardware: CC2531
Adapter firmware version:20201127

**Comment by cyrilphoenix71** [comment]
Is there any news about support this white version 067776 ?
