### ISSUE TITLE
lidl mood light (14148906L) Not displayed properly.

### ISSUE THREAD

**Issue by stack0423** [Koenkk/zigbee2mqtt#7932]
Hello, 
lidl mood light (14148906L)
Not displayed properly in domoticz not as rgbw. seems to display well in zigbee2mqtt.
![Naamloos2](https://user-images.githubusercontent.com/84093737/124364362-4dbaba00-dc41-11eb-8521-c220b5d672d2.png)

**Comment by Koenkk** [comment]
If it display well in z2m but not in Domoticz it's probably a bug in https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues (please create an issue there).
