### ISSUE TITLE
Ledvance AC25697 recognized as OSRAM AC03647

### ISSUE THREAD

**Issue by gaetan-steijaert** [Koenkk/zigbee2mqtt#7933]
## What happened

First connection with device registration went smoothly but wrong device was recognized.

## What did you expect to happen

Ledvance AC25697 to be added to my linked devices, but OSRAM AC03647 was added.

## How to reproduce it (minimal and precise)

On device reset linking works perfectly but wrong device is recognized. Have to try with the Ledvance 4058075208414 & Ledvance AC25702 also, will update this request with that information once I have the time to set them up.

## Debug info
Zigbee2MQTT version: 1.19.1
Adapter hardware: CC2531

**Comment by Koenkk** [comment]
Ledvance and osram are the same brand, it seems that the modelID `CLA60 RGBW Z3` is used for both Ledvance and osram bulbs. That means we cannot distinguish them, note that this is just a cosmetic thing.
