### ISSUE TITLE
Moes BRT-100-TRV not reporting after OTA update

### ISSUE THREAD

**Issue by wizu** [Koenkk/zigbee2mqtt#7941]
## What happened
Z2M showed me, that my TRV have an OTA update available, so I've updated it's firmware.
https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html#moes-brt-100-trv
After successful upgrade I couldn't control it any more. I've removed it from Z2M and added again serveral times, but it didn't help.
Not it only reports:
{
    "child_lock": "UNLOCK",
    "eco_mode": "OFF",
    "linkquality": 34,
    "update": {
        "state": "idle"
    }
}
and there is nothing abnormal in the logs, about this device.
Changing child lock from Z2M works, but nothing more.

## Debug info
Zigbee2MQTT version: 1.20.0 commit: 41b67fd
Adapter hardware: CC2538 + CC2592
Adapter firmware version: zStack30x 20200211

**Comment by CVKBaca** [comment]
I have the same problem. TVR does not respond after firmware upgrade but nothing abnormal in the logs..

Zigbee2mqtt version: 1.20.0-1
adapter: CC2652RB development stick with zigbee2mqtt firmware

**Comment by vladi1234** [comment]
Hi, whether thermostat itself works? And what firmware version now shows thermostat?

**Comment by wizu** [comment]
Termostat works ok and show firmware U1, or UI

**Comment by vladi1234** [comment]
Does z2m pairing work correctly?

**Comment by wizu** [comment]
Yes, I have tried that several times and it worked every time, but no difference.

**Comment by vladi1234** [comment]
I need more information.

![Bildschirmfoto vom 2021-07-12 22-46-23](https://user-images.githubusercontent.com/45510877/125354881-9fabc000-e364-11eb-8ec1-cbecc3f12273.png)

I need result.

**Comment by CVKBaca** [comment]
sorry I dont see fw version :(
[image: image.png]

po 12. 7. 2021 o 21:13 vladi1234 ***@***.***> napísal(a):

**Comment by wizu** [comment]
`Read result of 'genBasic': {"appVersion":87,"zclVersion":3,"stackVersion":0,"hwVersion":1,"manufacturerName":"_TZE200_b6wax7g0","modelId":"TS0601","dateCode":"","powerSource":3}`

**Comment by vladi1234** [comment]
Read result of 'genBasic': {"zclVersion":3,"appVersion":64,"stackVersion":0,"hwVersion":1,"manufacturerName":"_TZE200_b6wax7g0","modelId":"TS0601","dateCode":"","powerSource":3}

On my thermostat "appVersion" is: 64. I did not update.

**Comment by CVKBaca** [comment]
![image](https://user-images.githubusercontent.com/77513646/125357943-9886b100-e368-11eb-807b-27a5cd2789d9.png)

**Comment by vladi1234** [comment]
Moes BRT-100-TRV thermostat does not have a firmware update yet.
I think the thermostat got the wrong firmware update from Tuya.

Look here:
https://github.com/Koenkk/zigbee-OTA/commit/8c9017844d110ea8d499da0158e0e4c85d8aa1d5

**Comment by wizu** [comment]
Is there a way to get it back to old firmware? @Koenkk

**Comment by vladi1234** [comment]
Tuya and Moes have the same "modelId": "TS0601".
That is not right.
We have to speak to @Koenkk that he differentiates according to "manufacturerName": "_ TZE200_b6wax7g0" and not according to "modelId": "TS0601".

**Comment by vladi1234** [comment]
Tuya and Moes also have the same "manufacturer code": 4098,

**Comment by vladi1234** [comment]
```
{
	"id": 17,
	"type": "EndDevice",
	"ieeeAddr": "0xcc86ecfffebxxxxx",
	"nwkAddr": 53108,
	"manufId": 4098,
	"manufName": "_TZE200_b6wax7g0",
	"powerSource": "Battery",
	"modelId": "TS0601",
	"epList": [
		1
	],
	"endpoints": {
		"1": {
			"profId": 260,
			"epId": 1,
			"devId": 81,
			"inClusterList": [
				0,
				4,
				5,
				61184
			],
			"outClusterList": [
				25,
				10
			],
			"clusters": {
				"genBasic": {
					"attributes": {
						"65503": "�f|(\u0012�f|(\u0012",
						"65506": 31,
						"65508": 0,
						"modelId": "TS0601",
						"manufacturerName": "_TZE200_b6wax7g0",
						"powerSource": 3,
						"zclVersion": 3,
						"stackVersion": 0,
						"hwVersion": 1,
						"dateCode": "",
						"appVersion": 64
					}
				},
				"genDeviceTempCfg": {
					"attributes": {}
				},
				"genLevelCtrl": {
					"attributes": {}
				},
				"msTemperatureMeasurement": {
					"attributes": {}
				}
			},
			"binds": [
				{
					"cluster": 0,
					"type": "endpoint",
					"deviceIeeeAddress": "0x00124b0022812735",
					"endpointID": 1
				},
				{
					"cluster": 61184,
					"type": "endpoint",
					"deviceIeeeAddress": "0x00124b0022812735",
					"endpointID": 1
				}
			],
			"configuredReportings": [],
			"meta": {}
		}
	},
	"appVersion": 64,
	"stackVersion": 0,
	"hwVersion": 1,
	"dateCode": "",
	"zclVersion": 3,
	"interviewCompleted": true,
	"meta": {},
	"lastSeen": 1626155319566
}
```

**Comment by wizu** [comment]
problem still exists

**Comment by CVKBaca** [comment]
I confirm the same problem. I also found out that after the OTA firmware update, it is no longer possible to set the device to pairing mode. I tried to reset the device manually via the AE function and entering a value "01", but even that didn't help.

**Comment by vladi1234** [comment]
> Is it possible to force an update manually for HY-368 (white moes clone) by means of zigbee2mqtt?
> 
> Here is binary and I know that it works well with my TRVs.
> https://github.com/Koenkk/zigbee-OTA/tree/master/images/Tuya
> 
> At the moment it looks that OTA update is locked in zigbee2mqtt

What "manufacturerName:" does "HY-368" TVR have?
Do you mean this "1615190575-si32_zg_uart_connect_sleep_ZS5_ty_OTA_1.1.7.bin" file?

**Comment by pawol** [comment]
Do you mean this "1615190575-si32_zg_uart_connect_sleep_ZS5_ty_OTA_1.1.7.bin should be fine for 
this TRV:
https://pl.gearbest.com/smart-home-controls/pp_009269115611.html

At the moment I have 3 pieces of TRV updated and 1 not updated. I would like to do it but OTA is locked now

**Comment by vladi1234** [comment]
I still need to know which 
`"manufacturerName:"` 
has "HY-368" TVR?

**Comment by bruvv** [comment]
![afbeelding](https://user-images.githubusercontent.com/3063928/132002257-dd3e8e1b-22a0-4794-853b-26ced0482302.png)

**Comment by wizu** [comment]
Model Zigbee
TS0601
zigbee_manufacturer
_TZE200_cwnjrr72

**Comment by pawol** [comment]
Since Augusto OTA update worked with it:
![trv](https://user-images.githubusercontent.com/13277626/132003300-f2854d9c-376e-4b76-8b9d-77eb93f6f1bd.JPG)

**Comment by bruvv** [comment]
Well this is what it is showing on my end in the OTA field:
![afbeelding](https://user-images.githubusercontent.com/3063928/132003459-53b2fc8b-aa6f-42a1-bb65-3a84e896b127.png)

**Comment by vladi1234** [comment]
Thanks!

**Comment by vladi1234** [comment]
> Model Zigbee
> TS0601
> zigbee_manufacturer
> _TZE200_cwnjrr72
> 
> And I also have _TZE200_ckud7u2l
> 
> Thats two of my HY-368

@wizu are you sure that the _TZE200_cwnjrr72 and _TZE200_ckud7u2l are compatible?

**Comment by wizu** [comment]
I bought 10 of _TZE200_cwnjrr72 a week ago and they look the same. But had no chance to update it so I don't know if they will work with this firmware - I think they will.
I will try to update one of them when the OTA will be available.

**Comment by wizu** [comment]
@vladi1234 so yes, let's assume that they are compatible and I will check that on my own TRV.

**Comment by MattWestb** [comment]
Keep in mind that most tuya TRVs is coming with 2 different Zigbee modules TZE200 and TYST11 and can having the same tuya MCU and if flashing the wrong version is very likely not working or braking the zigbee module or changing the comport so it cant communicating with the tuya MCU.

Also the Zigbee OTA file is only updating the Zigbee module on TS0601 device and not the tuya MCU that must being done with tuya (DP) commands.

So updating the Zigbee module is not helping with problems in the tuya MCU that is the TRV controller only fixing "zigbee problems" like bad cluster setting or reporting settings from zigbee cluster (that is barley not used on this devices) then the tuya MCU is only using the Zigbee module as one "tunneling" device for its communication with tuya cloud.

**Comment by artkrz** [comment]
I think z2m should have an option to mark device with "ignore fw update checks" or something similar. If device works well enough it doesn't have to be updated.

**Comment by vladi1234** [comment]
> Ich denke, z2m sollte eine Option haben, um das Gerät mit "Ignore fw update checks" oder ähnlichem zu markieren. Wenn das Gerät gut genug funktioniert, muss es nicht aktualisiert werden.

![Bildschirmfoto vom 2021-09-05 09-21-34](https://user-images.githubusercontent.com/45510877/132119021-d78d4aba-8255-4105-b581-4f71674d970d.png)

You can switch off here.


If the device works well enough, it doesn't need to be updated. ------> Then just don't do it!

**Comment by vladi1234** [comment]
First part of my OTA update PR has already been merged with z2m, but the second part of PR has to wait another 2 months, then it will be merged.
Reason see here:
https://github.com/Koenkk/zigbee-OTA/pull/50#issuecomment-913736281

**Comment by wizu** [comment]
Great, thanks @vladi1234

**Comment by CVKBaca** [comment]
is there any chance of repairing malfunction devices (_ TZE200_b6wax7g0) in the future with correct firmware via OTA update?

**Comment by vladi1234** [comment]
The possibility exists only if we have OTA update file.

**Comment by muddy79** [comment]
> First part of my OTA update PR has already been merged with z2m, but the second part of PR has to wait another 2 months, then it will be merged.
> Reason see here:
> [Koenkk/zigbee-OTA#50 (comment)](https://github.com/Koenkk/zigbee-OTA/pull/50#issuecomment-913736281)

Well, I understand the reason, but it means there will be people like me who are unable to update their MOES TS0601 devices (_TZE200_ckud7u2l), which is crucial to get them working properly: without update, the device goes to sleep state and it's not possible to use it via HA. I've just installed 6 of them, the heating season is about to start at my area, and I just found out the OTA update is not possible... :( Any suggestions?

**Comment by MattWestb** [comment]
OTA can checking the version of Z2M and if its old its blocking the update and if in pace with Z2M is allowing the update but its need some more code being added and all use dont need waiting so long.

**Comment by Safs** [comment]
Is any news about TS0601 update?

**Comment by jmarfer** [comment]
Good Morning. I cannot use this valve for my automations because it does not show system mode (to be able to switch HVAC between heat, auto and off). Would this be contemplated in the next update? When is it expected?

Thanks

**Comment by vladi1234** [comment]
Moes BRT-100-TRV thermostat does not have to have a 'system mode' either.
It works very well in any automation scenario.

1. For this you have to use the 'manual' position.

2. Set 'current_heating_setpoint' that what you need room target temperature.

3. Set 'eco_temperature' to '0', or '5' in any case less than the target room temperature.

4. To switch off the heating you have to use 'eco-mode_on'
and to switch on 'eco-mode_off'.

**eco-mode_on = off**
**eco-mode_off = auto**
**boost_heating_on = heat**

In any case, I am very satisfied with it.

**Comment by jmarfer** [comment]
> boost_heating_on

Thanks for the quick reply.

Actually I need to create a thermostat and dispense with the valve temperature sensor, using an external one. I only need a valve opening and closing switch. With another valve I have succeeded but with this I am not capable.

Following your indications, when I put "boost_heating_on = heat" the valve changes but in a while it returns to its original position.

Is there a way to get a "clean" valve open / close switch to use in a climate?

Thanks again

**Comment by vladi1234** [comment]
@jmarfer Then try this:

1. For this you have to use the 'manual' position.

2. Set 'current_heating_setpoint' 35°C room target temperature.

3. Set 'eco_temperature' to '0', or '5' in any case less than the target room temperature.

4. To switch off the heating you have to use 'eco-mode_on' and to switch on 'eco-mode_off'.

**eco-mode_on = off**
**eco-mode_off = on**

**Comment by jmarfer** [comment]
> @jmarfer Then try this:
> 
> 1. For this you have to use the 'manual' position.
> 2. Set 'current_heating_setpoint' 35°C room target temperature.
> 3. Set 'eco_temperature' to '0', or '5' in any case less than the target room temperature.
> 4. To switch off the heating you have to use 'eco-mode_on' and to switch on 'eco-mode_off'.
> 
> **eco-mode_on = off** **eco-mode_off = on**

Perfect @vladi1234, now it works for me. There has been a time when the 'current_heating_setpoint' dropped to 35 and I did not understand why. I will follow up.

One last thing. By putting the switch indicated in the climate, it works the other way around, that is, when it has to heat the valve it closes and when it has to go off the valve opens. Can I reverse this?

**Comment by vladi1234** [comment]
@jmarfer If you write automation scenario, it doesn't really matter 'on' or 'off'.
I don't think you can optically swap things around.

**Comment by sokol07** [comment]
Any information about fix of this issue?
I wanted to implement these TRVs in whole house, fortunately I bought only one but at the moment after a while the device is loosing any communication and I can't update the firmware (as I don't have a standalone tuya gateway)...

**Comment by vladi1234** [comment]
> Any information about fix of this issue? I wanted to implement these TRVs in whole house, fortunately I bought only one but at the moment after a while the device is loosing any communication and I can't update the firmware (as I don't have a standalone tuya gateway)...

@sokol07 Which TRV do you mean?

**Comment by sokol07** [comment]
Good question, I've bought it as "GTZ04 (Moes TS0601)" but it is listed in Z2M as `_TZE200_cwnjrr72`.
The OTA update is, as mentioned earlier, impossible due to the "No image available for imageType '5634'", which I guess means that the OTA is still disabled for this model?

**Comment by vladi1234** [comment]
> Good question, I've bought it as "GTZ04 (Moes TS0601)" but it is listed in Z2M as `_TZE200_cwnjrr72`. The OTA update is, as mentioned earlier, impossible due to the "No image available for imageType '5634'", which I guess means that the OTA is still disabled for this model?

OTA update is currently deactivated for this TRV.

https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-913752102

**Comment by sokol07** [comment]
Yeah, I've read the topic, I now about the deactivation, I was just curious if you have any forecast about fixing this issue - is it "while" like 2 weeks or more lika 2 months?

**Comment by vladi1234** [comment]
On November 1st, PR will be merged.

**Comment by vladi1234** [comment]
@wizu  worked for you with OTA update?

**Comment by wizu** [comment]
@vladi1234 yes, I have updated one of my TRV and it looks like it is working ok. Tommorow I will try to update the rest of them

**Comment by vladi1234** [comment]
@wizu Super! Thanks!

**Comment by oopiicaa** [comment]
I can confirm too, upgrade went through okay, everyrhing seems to work.

**Comment by vladi1234** [comment]
Thanks!

**Comment by Coollision** [comment]
Hi sorry to poke a closed thread, but I recently acquired a Moes thermostat (HY368 _TZE200_cwnjrr72).
 first thing I did was an ota update, and now it only reports its temp (also acts) once an hour even when heating so yeah small room == major overheating. is there a way arround this or a fix?

**Comment by amarce** [comment]
Hi,

The update is not appearing for me, I keep getting the error "No image available for imageType '5634'"

Mine is reported as _TZE200_b6wax7g0 and the firmware build date appears empty under the OTA section. 

I'm using the version of zigbee2mqtt that comes with the last home assistant, should I update it or something?

Thanks a lot!

**Comment by vladi1234** [comment]
>"No image available for imageType '5634'"

No image available Is correct, because Moes BRT-100-TRV "_TZE200_b6wax7g0" thermostat doesn't have its own firmware update yet.

"appVersion" 64 is the last current version.

**Comment by amarce** [comment]
Hi Vladi,

Understood.

Thanks a lot for the reply!

**Comment by romek92** [comment]
Update _TZE200_cwnjrr72 by OTA is safe now?

**Comment by henkiejan1** [comment]
Hi, i got yesterday this TRV and Zigbee2MQTT report also there is a update available from version 67 to 192. And more importantly it will not brick the device? Is there someone who could say it's safe to upgrade? I upgraded my Tuya TS011F powerplugs also from 67 to 192 without anyproblems. But a thermostat is not a power plug. ;)

**Comment by sgilyin** [comment]
> Hi, i got yesterday this TRV and Zigbee2MQTT report also there is a update available from version 67 to 192. And more importantly it will not brick the device? Is there someone who could say it's safe to upgrade? I upgraded my Tuya TS011F powerplugs also from 67 to 192 without anyproblems. But a thermostat is not a power plug. ;)

DO NOT INSTALL THIS!!!
Today my thermostat was broken after this ota update ;-(

**Comment by ilvits** [comment]
Today my thermostat was broken too...

**Comment by HrzM83** [comment]
One more broken... @Koenkk please disable OTA for these TRVs!

**Comment by Koenkk** [comment]
@HrzM83 will be disabled in the 1 November update.

**Comment by falconslag** [comment]
Hello,

I've got 2 of my TVR (Moes BRT-100-TRV) which got updated to version192 and I cannot pair them too.

I've contacted Moes Support but I don't expect much from them.

How can I ensure none of my other TVR have the same issue?
I only know 1 is at version 67 with the update button available.
All others display nothing except "idle":
 "update": {
        "state": "idle"
    },

I uderstand the OTA will be disabled the 1st November, but it may be useful for us if a downgraded firmware can be pushed to our TVR (Ex: Version 67) to ensure we won't be blocked in the future when we change battery for example.

And for those which do not pair using standard procedure,  if someone can find any combinaison that work, he will be welcome.

Regards

**Comment by jonathh21** [comment]
Has anyone the ability to check if this is still an issue or are these devices destined to obsolete themselves with no updates?

Thanks

**Comment by falconslag** [comment]
Hi Jonath21,

I still have 3 of these which cannot be paires after the update and I can't find a way to downgrade them.

BUT as they were new, I manage to have them replaced for free.

If someone has got skill and component to play with them, I can see to send one for testing. 

Regards.
