### ISSUE TITLE
States not changing with new device

### ISSUE THREAD

**Issue by dbroome1978** [Koenkk/zigbee2mqtt#7943]
Hello.  I've been working on this and have it where I can detect the states for all of the buttons on the switch but I cannot send it commands

[Moes 4 Gang](https://www.moeshouse.com/collections/tuya-zigbee-switch/products/zigbee-wall-touch-smart-light-switch-with-neutral-wire-no-neutral-wire-no-capacitor-needed-smart-life-tuya-2-3-way-muilti-control-association-hub-required-4-gang-white-us)

I borrowed the configs from here [tuya.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/75a13064874174606c7434d8afa380467d46d686/devices/tuya.js) and [moes.js](https://github.com/Koenkk/zigbee-herdsman-converters/blob/f22b305fa7324498bc38246db0ce27bf7235dc79/devices/moes.js)

[Here](https://paste.ubuntu.com/p/2hqPV4Trh9/) is my converter.

I am able to see now the states all 4 switches but I cannot change them

`mosquitto_pub` -t "zigbee2mqtt/0xbc33acfffeb12f9a/l1/set" -h 192.168.1.45 -m  `{\"state_l1\":\"ON\"}`
or 
`mosquitto_pub` -t "zigbee2mqtt/0xbc33acfffeb12f9a/l1/set" -h 192.168.1.45 -m  {\"state\":\"ON\"}`

I get this error

> Error` Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: Cannot read property 'includes' of undefined at /app/lib/extension/publish.js:187:60 at Array.find (<anonymous>) at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:187:42) at Controller.callExtensionMethod (/app/lib/controller.js:386:44) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5))

[Here](https://paste.ubuntu.com/p/mRyNkKQSzY/) is the log.  I've included when the state changes from physically changing the switch and when I try it over the server

## Debug Info
Zigbee2MQTT version: 1.19.1 commit: 9bd4693
Adapter hardware: CC2652R
Adapter firmware version: zzh (newest)

**Comment by dbroome1978** [comment]
I reposted this on the forum as well.  The edit to my post here is simply cleaning it up and making it more readable

**Comment by Koenkk** [comment]
Try with: 
```
mosquitto_pub -t "zigbee2mqtt/0xbc33acfffeb12f9a/l1/set" -h 192.168.1.45 -m '{"state":"ON"}'
```

**Comment by dbroome1978** [comment]
I get back the same error

> Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: Cannot read property 'includes' of undefined at /app/lib/extension/publish.js:187:60 at Array.find (<anonymous>) at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:187:42) at Controller.callExtensionMethod (/app/lib/controller.js:386:44) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5))

**Comment by Koenkk** [comment]
Could you post some more logging of this? (what happens before?)

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by dbroome1978** [comment]
Here you go 
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/6772111/log.txt)
If you need the raw output from docker, I can do that as well.
I'm not sure if there is a way to have it only report logs for the specific device
The device ID is 0xbc33acfffeb12f9a

**Comment by dbroome1978** [comment]
Here is an extra one with a physical button press as well as using mqtt
[deug with button press vs mqtt.txt](https://github.com/Koenkk/zigbee2mqtt/files/6772351/deug.with.button.press.vs.mqtt.txt)

**Comment by Koenkk** [comment]
The issue is in your external converter, it uses `fz.tuya_switch2`, this converter does not exist anymore. You can probably just remove it from `fromZigbee` since `fz.tuya_switch` should be good.

Let me know if that works, then I can add support for this device out-of-the-box.

**Comment by dbroome1978** [comment]
I receive the same error with or without fz.tuya_switch2
I did reconfigure after making the change.  Do I need to do a full remove and pair?

**Comment by Koenkk** [comment]
@dbroome1978 try to make `fromZigbee` empty, then add converters one by one until you see the errors.

**Comment by dbroome1978** [comment]
Ok - i removed all and have it no converters listed.  Now this is odd.  If I try to change the state once, I get "No converter available" but when I try a second time, i get the old error

> Debug Received MQTT message on 'zigbee2mqtt/0xbc33acfffeb12f9a/l1/set' with data '{"state_l1":"OFF"}'
> Error No converter available for 'state' (undefined)
> 

> Debug Received MQTT message on 'zigbee2mqtt/0xbc33acfffeb12f9a/l1/set' with data '{"state_l1":"OFF"}'
> Error Failed to call 'EntityPublish' 'onMQTTMessage' (TypeError: Cannot read property 'includes' of undefined at /app/lib/extension/publish.js:187:60 at Array.find (<anonymous>) at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:187:42) at Controller.callExtensionMethod (/app/lib/controller.js:386:44) at processTicksAndRejections (internal/process/task_queues.js:95:5))
>

**Comment by dbroome1978** [comment]
I believe it's working and will double check when I get home.
The 'tz' line had been commented out.  Changing that and changing the formatting to match 'fz' lines got it working.

**Comment by dbroome1978** [comment]
I lost my container and am setting up from scratch.  Just an FYI that this does not yet seem to be supported out of the box.  The converter does work, though
