### ISSUE TITLE
Copy effect from lights into group with autodiscovery

### ISSUE THREAD

**Issue by Alfiegerner** [Koenkk/zigbee2mqtt#7945]
## Is your feature request related to a problem? Please describe

Awesome job on making groups auto discoverable. It would be great if light effects came through too.

## Describe the solution you'd like

If all lights in a group share the same effects to bring those into the group properties that exposed.

## Describe alternatives you've considered

Group effects can be achieved via client manual config in HomeAssistant, but would be good to move over automatically.

**Comment by ASNNetworks** [comment]
To add: when previously configuring groups through configuration.yaml as mqtt light groups, you could add variables like effects and rgb_color. With the latest update that uses auto-discovery, we can't set this anymore. I now lost the rgb color picker and effects list.

Please allow settings like effect, rgb_color etc. Or allow turning auto-discovery off so I can manually configure like before.
