### ISSUE TITLE
Light group turned on and off by supervisor

### ISSUE THREAD

**Issue by snippem** [Koenkk/zigbee2mqtt#7959]
## What happened
Lights goes off and on again 

## What did you expect to happen
That my lights stay on when they supposed to

## How to reproduce it (minimal and precise)
Happens out off the bleu
## Debug info
Zigbee2MQTT version:1.20.0-1
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_4F_3F_95-if00-port0

This happens frequently see screenshots any idea on what is the cause?
![Screenshot_20210706-010106](https://user-images.githubusercontent.com/60006674/124523174-3cff7500-ddf6-11eb-8b93-74492f47f17a.jpg)
![Screenshot_20210706-010054](https://user-images.githubusercontent.com/60006674/124523177-425cbf80-ddf6-11eb-9a04-593b7955b8c8.jpg)

**Comment by Koenkk** [comment]
This is not a zigbee2mqtt but Home Assistant issue. Ask for support for on the Home Assistant forum.
