### ISSUE TITLE
Tuya TS0601_cover. Value "position" problem 

### ISSUE THREAD

**Issue by martkotur** [Koenkk/zigbee2mqtt#7969]
Need help. Tuya TS0601_cover. Default payload Z2M {"position": VALUE} where VALUE is a number between 0 and 100. My device - between 1...100.  Send open - final position -100, STATE Open. Good. Send close - final position 1 and STATE Open... Manually set position 0 in Z2M GUI - STATE Close.
What can i modifed for correct work? https://www.zigbee2mqtt.io/devices/TS0601_cover.html#device-type-specific-configuration
Custom converter? What is add to *.js for min and max position?

        fromZigbee: [fz.tuya_cover, fz.ignore_basic_report],
        toZigbee: [tz.tuya_cover_control, tz.tuya_cover_options],
        exposes: [
            e.cover_position().setAccess('position', ea.STATE_SET),
            exposes.composite('options', 'options')
                .withFeature(exposes.numeric('motor_speed', ea.STATE_SET)
                    .withValueMin(0)
                    .withValueMax(255)
                    .withDescription('Motor speed'))],
    },

**Comment by ASNNetworks** [comment]
Not fixed with 1.20
