### ISSUE TITLE
After upgraded to 1.20, node-red Z2M Admin doesn't work anymore

### ISSUE THREAD

**Issue by hi1000** [Koenkk/zigbee2mqtt#7971]
After upgraded zigbee2mqtt to 1.20, Z2M admin doesn't work anymore.

Below is the nodejs and npm version in Raspberry Pi 4
soll@localhost:~/log $ node -v
v14.17.2
soll@localhost:~/log $ npm -v
6.14.13

**Comment by sjorge** [comment]
There was a big rework in how the zigbee2mqtt/bridge endpoint works. It now also comes with it's own WebUI which IMHO is way better than the node-red one.

You can restore the old behavior by setting `legacy_api` to true under `advanced` in the configuration.

**Comment by hi1000** [comment]
Thanks Jorge for your reply. Will try the WebUI.
