### ISSUE TITLE
take over excisting zigbee network

### ISSUE THREAD

**Issue by HerrieMan72** [Koenkk/zigbee2mqtt#799]
Hi,
this is not an issue, more a question for help, but I can't find any blog or forum related to zigbee2mqtt so decided to try here.
I have a running Zigbee network with Homey as controller and ~50 zigbee devices connected, around half of them are Ikea Tradfri lights, other half are Xiaomi Aqara sensors&switches.
I'm a bit disappointed with the stability of this network, it happens very often that devices are not correctly switched by Homey, i have a suspicion that the zigbee implementation of Homey is a bit shaky.
So I would like to try zigbee2mqtt as an alternative, but rebuilding my whole network is a hurdle i'm a bit hesitant to take. Is it somehow possible that I can use zigbee2mqtt to take-over the controller role in my existing zigbee network ?

**Comment by Koenkk** [comment]
No, this is not possible. I would recommend start moving a few devices to zigbee2mqtt to verify that it works for you.
