### ISSUE TITLE
Device - model 'TS011F' and manufacturer name '_TZ3000_jvzvulen'

### ISSUE THREAD

**Issue by kotyla** [Koenkk/zigbee2mqtt#8020]
Hello,

I've got another TS011F plug not supported. I've tried to use instruction how to support new devices but I failed (seems too complicated for me). I've also tried dev branch.

Is it possible to add it ?
Thank you.

`Device '0x60a423fffeff96db' with Zigbee model 'TS011F' and manufacturer name '_TZ3000_jvzvulen' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

![ts011f-2](https://user-images.githubusercontent.com/8727347/124599598-209b2100-de66-11eb-8405-72ecdf156108.JPG)
![ts011f-1](https://user-images.githubusercontent.com/8727347/124599599-21cc4e00-de66-11eb-93f7-293108052d48.JPG)

**Comment by DavidFFerreira** [comment]
you need to folow de labels for request a  new device...and this device i think is only add a name to an existing code device =)

**Comment by Koenkk** [comment]
Added it, please let me know if the power monitoring works correctly.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by kotyla** [comment]
It's working in HA after update to 1.21.0-1. Thank you very very much.
