### ISSUE TITLE
Problem with binding

### ISSUE THREAD

**Issue by umutcelebi** [Koenkk/zigbee2mqtt#8022]
First of all i am a verry new with Home Assistant and Z2M.
I am trying to do easy and simple things like this but getting stuck.
Also the bulbs are verry slow going on and off.
All the LQI is 150+ so i was thinking the binding would help?
But cant do that..
If you need more info please ask me because i am not sure if i do this right.

## What happened
I want to bind my all 4 GU10 IKEA TRADFRI bulbs to my remote from IKEA to work.
## What did you expect to happen
It is not binding and giving a error
## How to reproduce it (minimal and precise)
In the UI just choose group "Keuken" and select OnOff and click Bind

## Debug info
Zigbee2MQTT version: 1.18.1 commit: 1.18.1
Adapter hardware: CC2531
Adapter firmware version: Coordinator revision
20201128

Link log:
https://pastebin.com/ZHVgPsbM

**Comment by MattWestb** [comment]
Is you trying binding the remote to one light or to one light group ?

IKEA controlling devices is only supporting binding to light groups and not direct to devices so first making one group for the lights and the binding the remote to the group.

**Comment by umutcelebi** [comment]
Yes it is using light group. Otherwise it is probably going more wrong.

**Comment by MattWestb** [comment]
Looks like one timeout then sending the bind request.
Did you "waking" the remote up then sending the commands so its not sleeping ?

(The IKEA test firmware is supporting device binding but no grope but its very likely some wrong in the firmware then its not moved to the production feed for around on mouth.)

**Comment by umutcelebi** [comment]
I think it is now bound to the group. But when i turn off my z2m then i cant use them. Do i need to do anything special after binding?

**Comment by MattWestb** [comment]
Normally not. If light is in the group and the remote is bonded to it then it shall working also if the coordinator is off line. But it can being that the remote is having the coordinator as its parent and need some time for finding one new router for connecting the the network before its working OK

**Comment by umutcelebi** [comment]
Hmm okay, it did not work. Do i need to wait like 5 to 10 minutes or so? Also when i check the map i do not see them bounded with each other. And 2 spots are not even connected to the coordinator or as router.![20210713_132618.jpg](https://user-images.githubusercontent.com/85175718/125444110-dfb79d75-2022-4952-b22e-d19402855a5f.jpg)

**Comment by MattWestb** [comment]
No is only need some seconds for doing  the binding.

But on the map its looks like you remote is having the light as its parent = good but  the parent dont have connection to the coordinator so its perhaps was not getting  the bind command you was sending.

**Comment by umutcelebi** [comment]
First of all thanks for your fast responses!
What can i do?

**Comment by umutcelebi** [comment]
Issue seems to be solved after moving to celeron minipc from rpi3.

**Comment by MattWestb** [comment]
If the PI is running Z2M and the celeron is having USB3 ports with connected devices it can blocking the radio with interference so nothing is working at all (normal with CornBee radio adapters that need one USB extrication cable for working OK) but many other things can doing the same like WiFi, Bluetooth, Ethernet and power supply adapters.

Great that you was getting it working well !!

**Comment by umutcelebi** [comment]
I think that i had to many integrations and addons on my rpi3 which slowered up everything.
