### ISSUE TITLE
Support for S-LUX-ZB

### ISSUE THREAD

**Issue by Koterak** [Koenkk/zigbee2mqtt#8036]
I tried several times to add device support for S-LUX-ZB. 

Link to the device where I bought it: https://aliexpress.com/item/1005002835450510.html

Received message from unsupported device with Zigbee model 'isltm67' and manufacturer name '_TYST11_pisltm67'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

I tired to add this device with such code for tuya devices:

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [
        {
            modelID: 'isltm67\u0000',
            manufacturerName: '_TYST11_pisltm67'
        },
    ],
    model: 'S-LUX-ZB',
    vendor: 'INNOPRO',
    description: 'Light Sensor',
    fromZigbee: [
        fz.battery, 
        fz.illuminance
    ],
    toZigbee: [
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.battery(), 
        e.illuminance(), 
        e.illuminance_lux()
    ],
};

module.exports = definition;
```

And it's a bit successfull.. Because the device got recognised. But all data which I got is N/A unfortunatly. 
Screen from zigbee2mqtt:
![obraz_2021-07-13_223726](https://user-images.githubusercontent.com/35494920/125521397-8b005407-b8d3-4114-9b13-4a04924dc0e2.png)
![obraz_2021-07-13_223749](https://user-images.githubusercontent.com/35494920/125521441-61d3e4ca-e220-4c13-beeb-5b5b72c1f49b.png)
![obraz_2021-07-13_223809](https://user-images.githubusercontent.com/35494920/125521476-285db5a9-dccf-4121-a997-2a983b5c5abc.png)

In addition screen from logs:
![obraz_2021-07-13_223856](https://user-images.githubusercontent.com/35494920/125521560-7a8d51c0-8e56-4d90-bff6-16ee9a807c23.png)

Is there anything else I can do? Or can you maybe add support for this device?

**Comment by Koterak** [comment]
I managed to get some data from device. Maybe this will help?
![obraz_2021-07-14_202115](https://user-images.githubusercontent.com/35494920/125672755-81f1abb4-8a78-4213-b37d-c456d1a82d15.png)

**Comment by Koterak** [comment]
I added something like this to fromZigbee:

```
s_lux_zb_illuminance: {
    cluster: 'manuSpecificTuya',
    type: ['commandGetData', 'commandSetDataResponse'],
    convert: (model, msg, publish, options, meta) => {
        const dp = msg.data.dp; // First we get the data point ID
        const value = tuyaGetDataValue(msg.data.datatype, msg.data.data); // This function will take of converting the data to proper JS type

        switch (dp) {
        case tuya.dataPoints.sluxIlluminance: // DPID that we added to common
            return {illuminance_log: value.toFixed(1)}; // value is already converted to a number in JS, and we deduced that it needs to be divided by 10
        default:
            meta.logger.warn(`s_lux_zb_illuminance: NOT RECOGNIZED DP #${
                dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
    },
},
```

And in tuya.js I added 
`sluxIlluminance :4`

But I got error:
![obraz_2021-07-14_211702](https://user-images.githubusercontent.com/35494920/125679938-bca038b6-5aa8-4833-b316-807bb0816abf.png)

**Comment by Koenkk** [comment]
Try with this external converter, this will make it completely standalone so no changes to zigbee-herdsman-converters are required:

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const illuminanceConverter = {
    cluster: 'manuSpecificTuya',
    type: ['commandGetData', 'commandSetDataResponse'],
    convert: (model, msg, publish, options, meta) => {
        const dp = msg.data.dp; // First we get the data point ID
        const value = tuyaGetDataValue(msg.data.datatype, msg.data.data); // This function will take of converting the data to proper JS type

        console.log(`Received: ${dp} - ${value}`);
        switch (dp) {
        case 4: // DPID that we added to common
            return {illuminance_log: value.toFixed(1)}; // value is already converted to a number in JS, and we deduced that it needs to be divided by 10
        default:
            meta.logger.warn(`s_lux_zb_illuminance: NOT RECOGNIZED DP #${
                dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
        }
    },
};

const definition = {
    fingerprint: [
        {
            modelID: 'isltm67\u0000',
            manufacturerName: '_TYST11_pisltm67'
        },
    ],
    model: 'S-LUX-ZB',
    vendor: 'INNOPRO',
    description: 'Light Sensor',
    fromZigbee: [illuminanceConverter],
    toZigbee: [
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.battery(), 
        e.illuminance(), 
        e.illuminance_lux()
    ],
};

module.exports = definition;
```

**Comment by Koterak** [comment]
Now I got this error:
![obraz_2021-07-15_190439](https://user-images.githubusercontent.com/35494920/125828253-4c69497a-940a-4c66-8400-14f2d4b010fc.png)

**Comment by Koenkk** [comment]
Try changing `const value = tuyaGetDataValue(msg.data.datatype, msg.data.data);` to `const value = tuya.getDataValue(msg.data.datatype, msg.data.data);`

**Comment by Koterak** [comment]
Thank you very much! It's working now. And now what I will have to do to add it as homeassistant entity? How to make this data exposed?

**Comment by Koenkk** [comment]
Can you provide your converter so I can add this for support out of the box?

**Comment by Koterak** [comment]
I just edited it a little from code which you give me. 

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const illuminanceConverter = {
    cluster: 'manuSpecificTuya',
    type: ['commandGetData', 'commandSetDataResponse'],
    convert: (model, msg, publish, options, meta) => {
        const dp = msg.data.dp; // First we get the data point ID
        const value = tuya.getDataValue(msg.data.datatype, msg.data.data); // This function will take of converting the data to proper JS type

        console.log(`Received: ${dp} - ${value}`);
        switch (dp) {
        case 2: // DPID that we added to common
            return {illuminance_lux: value.toFixed(0)}; // value is already converted to a number in JS, and we deduced that it needs to be divided by 10
        case 4: // DPID that we added to common
            return {battery: value.toFixed(1)};
        case 1:
            return {battery_low: value.toFixed(1)};                    
        default:
            meta.logger.warn(`s_lux_zb_illuminance: NOT RECOGNIZED DP #${
                dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
        }
    },
};

const definition = {
    fingerprint: [
        {
            modelID: 'isltm67\u0000',
            manufacturerName: '_TYST11_pisltm67'
        },
    ],
    model: 'S-LUX-ZB',
    vendor: 'INNOPRO',
    description: 'Light Sensor',
    fromZigbee: [illuminanceConverter],
    toZigbee: [
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.battery(), 
        e.illuminance_lux(),
        e.battery_low(),
    ],
};

module.exports = definition;
```

Today I checked all the values and it's working for now.

**Comment by Koenkk** [comment]
Thanks, added

**Comment by hossface** [comment]
I have found another variation of this device with a different manfucturer name.
I just tweaked the above code and added as an external converter to get it working.

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const illuminanceConverter = {
    cluster: 'manuSpecificTuya',
    type: ['commandGetData', 'commandSetDataResponse'],
    convert: (model, msg, publish, options, meta) => {
        const dp = msg.data.dp; // First we get the data point ID
        const value = tuya.getDataValue(msg.data.datatype, msg.data.data); // This function will take of converting the data to proper JS type

        console.log(`Received: ${dp} - ${value}`);
        switch (dp) {
        case 2: // DPID that we added to common
            return {illuminance_lux: value.toFixed(0)}; // value is already converted to a number in JS, and we deduced that it needs to be divided by 10
        case 4: // DPID that we added to common
            return {battery: value.toFixed(1)};
        case 1:
            return {battery_low: value.toFixed(1)};                    
        default:
            meta.logger.warn(`s_lux_zb_illuminance: NOT RECOGNIZED DP #${
                dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
        }
    },
};

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_pisltm67'
        },
    ],
    model: 'S-LUX-ZB',
    vendor: 'INNOPRO',
    description: 'Light Sensor',
    fromZigbee: [illuminanceConverter],
    toZigbee: [
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.battery(), 
        e.illuminance_lux(),
        e.battery_low(),
    ],
};

module.exports = definition;

**Comment by hossface** [comment]
I have found a variation of this device with TZE200 instead of TYST11
I have tweaked the code and added as an external converter it worked for me.

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const illuminanceConverter = {
    cluster: 'manuSpecificTuya',
    type: ['commandGetData', 'commandSetDataResponse'],
    convert: (model, msg, publish, options, meta) => {
        const dp = msg.data.dp; // First we get the data point ID
        const value = tuya.getDataValue(msg.data.datatype, msg.data.data); // This function will take of converting the data to proper JS type

        console.log(`Received: ${dp} - ${value}`);
        switch (dp) {
        case 2: // DPID that we added to common
            return {illuminance_lux: value.toFixed(0)}; // value is already converted to a number in JS, and we deduced that it needs to be divided by 10
        case 4: // DPID that we added to common
            return {battery: value.toFixed(1)};
        case 1:
            return {battery_low: value.toFixed(1)};                    
        default:
            meta.logger.warn(`s_lux_zb_illuminance: NOT RECOGNIZED DP #${
                dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
        }
    },
};

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_pisltm67'
        },
    ],
    model: 'S-LUX-ZB',
    vendor: 'INNOPRO',
    description: 'Light Sensor',
    fromZigbee: [illuminanceConverter],
    toZigbee: [
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        e.battery(), 
        e.illuminance_lux(),
        e.battery_low(),
    ],
};

module.exports = definition;
```
