### ISSUE TITLE
add philips hue struana ceiling

### ISSUE THREAD

**Issue by Pepeuch** [Koenkk/zigbee2mqtt#8044]
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['3418931P6'],
    model: '3418931P6',
    vendor: 'Philips',
    description: 'Hue white ambiance Struana bathroom ceiling with bluetooth 2400lm',
    fromZigbee: [],
    toZigbee: [],
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
};
module.exports = definition;
..

## data/database.db entry of the device
{"id":3,"type":"Router","ieeeAddr":"0x00178801097fa464","nwkAddr":20871,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"3418931P6","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"3418931P6","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20201012","swBuildId":"1.76.10"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20201012","swBuildId":"1.76.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1626283715394}

thanks

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
