### ISSUE TITLE
SmartThings: Unknown power source

### ISSUE THREAD

**Issue by The-Deep-Sea** [Koenkk/zigbee2mqtt#8062]
## What happened

Various SmartThings devices are shown with an unknown power source in the frontend.
Specifically, this applies to models STS-WTR-250 and STS-IRM-251 for me.

## What did you expect to happen

Battery should be displayed as the power source for both devices.

## Additional info

Could it be that this is a general problem with SmartThings?
Because for other devices there are also fixes of this kind, e.g.: https://github.com/Koenkk/zigbee-herdsman-converters/blob/d0fe66d5408ebfa037b03f68044cd8e59ecd039e/devices/smartthings.js#L206

## Debug info
Zigbee2MQTT version: 1.20.0 commit: 41b67fd
Adapter hardware: CC2652RB
Adapter firmware version: 20210120

**Comment by Koenkk** [comment]
Added the same fix as https://github.com/Koenkk/zigbee-herdsman-converters/blob/d0fe66d5408ebfa037b03f68044cd8e59ecd039e/devices/smartthings.js#L206

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
