### ISSUE TITLE
Unique IDs not unique

### ISSUE THREAD

**Issue by frenck** [Koenkk/zigbee2mqtt#8079]
## What happened

Z2M seems to be re-using a unique ID at some place.

## What did you expect to happen

For zigbee2mqtt to produce consistent unique IDs

## How to reproduce it (minimal and precise)

Update to dev? I'm not sure where it is coming from. Groups support maybe?

## Debug info
Zigbee2MQTT version: 1.20.0-dev commit: 46e2a77
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version: 0x26660700

## Additional

![image](https://user-images.githubusercontent.com/195327/126223123-8f67f33b-c38a-4c67-92ae-3199120b9d93.png)

Search shows it as well

![image](https://user-images.githubusercontent.com/195327/126223701-b6dcf7b2-788b-488a-9f4c-4fcfe779660f.png)

**Comment by Koenkk** [comment]
I think this is due to https://github.com/Koenkk/zigbee2mqtt/commit/679d2317438a3f15b2dbc912919122558f0befdf , the old topics are not cleaned up. Can you confirm this by clearing the `homeassistant/light/1/light` message?

**Comment by frenck** [comment]
Yep! Missed that one, thanks @Koenkk 👍

**Comment by Koenkk** [comment]
@frenck thanks for confirming, modified the code to also clear it automatically now.
