### ISSUE TITLE
Upgrade from CC2531 to CC2652R end devices not connecting through router points

### ISSUE THREAD

**Issue by damomay** [Koenkk/zigbee2mqtt#8081]
Runing the latest zibgee2mqtt in HA 1.18.1-1
Previous usb coordinator was a CC2531
Upgraded to a CC2652R flashed with CC2652R_coordinator_20210120 firmware
Coordinator on a 2m Extension USB lead ( used with previous coordinator stick )
Runnning HA on A VM inside a MAC mini ( 18 months )
15 plus Nue 3a light switches through out the house
4 Sonoff temp / humidity sensors
1 Sonoff Motion sensor
1 Smartthings multi purpose sensor (2018)

Prior to upgrading the USB stick everything worked and paired ok  in their respective locations through out the house albeit some of the sonoff sensors dropping of the network and having to repair them occasionally and two of the nue 3a dimmer switches droping off ocasionally for days on end.
After upgrading to the CC2652R stick the stability of the nue 3a switches have improved heaps with no drop off in a month, How ever all of the Sonoff sensors have dropped off completely and I can not repair them to the network even though a Nue 3a switch is within a couple of meters, Even moving the sensor next to the switch it will not pair, Bringing the sensor back to the Coordinator within a couple of meters and they will pair on the network with strong LQI signals. Moving them about halfway  towards their original location and close to a Nue 3a switch and repairing them they will rejoin the network with a poor LQI signal. Looking at the netwok map also shows me they are connecting through the coordinator not routers as expected.

It appears they will only pair with the network through the coordinator, setting the permit to join to a particular device doesn't work with the CC2652R coordinator but reverting back to the old CC2531 stick will allow the sonoff devices to join the network through the Nue 3a switches.
I have changed thje batteries on all the sonoff devices and removed them from the network before attempting to repair them.

Has anyone had this problem or Does anyone have any suggestions.
Cheers
Damo

**Comment by RaffoNin** [comment]
Same thing happens to me even with the last version of Zigbee2Mqtt and Stack for CC2652R. Were you able to solve this issue?
