### ISSUE TITLE
New Home Assistant select entities all enabled by default

### ISSUE THREAD

**Issue by frenck** [Koenkk/zigbee2mqtt#8083]
## What happened

Extracted this comment into this issue: <https://github.com/Koenkk/zigbee2mqtt/pull/7980#issuecomment-882789802>

Introduced in #7980, also related to #8078

![image](https://user-images.githubusercontent.com/195327/126213629-cff523f6-dac8-48a3-9cd7-703069765271.png)

These entities are not really "common". As in, they can be useful, but probably most people won't use them in their automation or dashboards in general. Therefore, it is recommended to send a disabled by default in Home Assistant. This allows a user to enable them when needed, but not overwhelm the user with entities they do not need or pollute the (historical) database unneeded.

Can we adjust this for this feature before release it to the public?

## What did you expect to happen

To have less common entities disabled by default, keeping setups nice and tidy.

## Debug info

Zigbee2MQTT version: 1.20.0-dev commit: 46e2a77
Adapter hardware: Conbee II
Adapter firmware version: 0x26660700

**Comment by ruifung** [comment]
The same could be said of the older sensor entity used to expose enums though, and that is still used to expose composite exposes.

**Comment by frenck** [comment]
> sensor entity used to expose enums though

This has been corrected in #7684 and released in 1.20.0.
It will only affect new devices.

**Comment by ruifung** [comment]
Well, according to that PR, that behavior is not applied to the enum / text / composite expose types though. 

Personally, I'm not entirely sure if the entire category of enum exposes can be classified as to be disabled by default.

**Comment by frenck** [comment]
> In fact, when I authored that PR, I was mostly following existing behavior of those 3 expose types which are epxosed as sensor entities that were enabled by default.

Actually, you are right! 👍
I do have sensors for those already (although all manually disabled).

> Personally, I'm not entirely sure if the entire category of enum exposes can be classified as to be disabled by default.

Maybe just enum isn't specific enough to decide on exposing it with, so instead, we can add them to the lookup table and handle it that way.
