### ISSUE TITLE
Cusom device icon is not used in the Map tab

### ISSUE THREAD

**Issue by kajkokokoszewski** [Koenkk/zigbee2mqtt#8095]
## What happened
I've added an external converter for my device and changed the icon of my new device in the settings. The new icon shows in the Devices tab of the frontend but the Map tab still displays the generic Zigbee icon.

## What did you expect to happen
The icon provided in the device settings should be used in all the views in the frontend, including Map.

## How to reproduce it (minimal and precise)
Customize the icon and refresh the Map view.

## Debug info
Zigbee2MQTT version: 1.20.0
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by Koenkk** [comment]
Please create frontend issues here: https://github.com/nurikk/z2m-frontend/issues
