### ISSUE TITLE
The homeassistant_legacy_entity_attributes parameter removes the last_seen and device attributes

### ISSUE THREAD

**Issue by Enzokot** [Koenkk/zigbee2mqtt#8096]
## What happened
If I set `homeassistant_legacy_entity_attributes` to `false`, then the `last_seen` and `device` attributes will be removed from all sensors.
## What did you expect to happen
The `homeassistant_legacy_entity_attributes` option does not remove the `last_seen` and `device` attributes
## How to reproduce it (minimal and precise)
Set  `"homeassistant_legacy_entity_attributes": false`, `"last_seen": "epoch"` and `"include_device_information": true`
## Debug info
Zigbee2MQTT version: 1.20.0
Adapter hardware: CC26X2R1
Adapter firmware version: zStack3x0 20210218

**Comment by Koenkk** [comment]
`homeassistant_legacy_entity_attributes` will indeed disable all attributes on the discovered HA entities (including `last_seen`) so that is expected.

**Comment by Enzokot** [comment]
Great option, thanks!
