### ISSUE TITLE
Xiaomi SJCGQ11LM does not automatically create linkquality sensor in Home Assistant

### ISSUE THREAD

**Issue by TASSDevon** [Koenkk/zigbee2mqtt#8097]
All my other z2m Aqara sensors have a linkquality sensor automatically created in HA, this one does not. Is this intentional?

**Comment by Koenkk** [comment]
As of 1.20.0 (#7684) less common entities are disabled by default. You should be able the enable the in HA.

**Comment by TASSDevon** [comment]
Thanks, somehow I missed this!
