### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#81]
Allow to configure different log_levels (e.g. only WARN/ERROR).

**Comment by ciotlosm** [comment]
@Koenkk would be nice to be able to change this through mqtt while running.

**Comment by tb-killa** [comment]
We should also ADD this type of "enable extended Zigbee-Package debugging" like mentioned here: https://github.com/Koenkk/zigbee2mqtt/issues/36#issuecomment-394095615

**Comment by Koenkk** [comment]
@tb-killa this can be easily done by using the debug module.

https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L8
https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L180

Would you mind doing a PR?

**Comment by ciotlosm** [comment]
It seems that changing log levels is possible also during runtime. See https://github.com/winstonjs/winston#using-logging-levels: `You may also dynamically change the log level of a transport:`

**Comment by ciotlosm** [comment]
@tb-killa if you can point me in the right direction based on comments form @Koenkk happy to have a look.

**Comment by ciotlosm** [comment]
@Koenkk added in commit https://github.com/Koenkk/zigbee2mqtt/pull/110/commits/c65bd2b60b34e0372a52aefb88d09495260195f7

**Comment by Koenkk** [comment]
I think this issue is done, what do you think @ciotlosm ?

**Comment by ciotlosm** [comment]
I think so too
