### ISSUE TITLE
Tuya door sensor ZM-CG205

### ISSUE THREAD

**Issue by andrey170183** [Koenkk/zigbee2mqtt#8118]
Hi.
Please help me, maybe I'm doing something wrong. I'm new to this business. I connected the CC2531 stick to the Home Assistant and configured it. When the ZigBee sensor is paired, this warning appears. Is it possible to connect it to the Home Assistant somehow?
![1](https://user-images.githubusercontent.com/42129962/126861031-cdcf43ed-fe1e-4221-860a-c7d3a173d497.jpg)
![2](https://user-images.githubusercontent.com/42129962/126861036-28e7a508-e347-45cb-a4d8-4820007d9b38.jpg)

**Comment by Koenkk** [comment]
Looks the same as https://github.com/Koenkk/zigbee2mqtt/issues/7553 (working on it)
