### ISSUE TITLE
Echo Plus (2.Gen) as router

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#813]
Is is technically possible to add the amazon echo plus to the zigbee2mqtt network to use it as a router?

If yes, will this be available in the future (or is already implemented)?

**Comment by Koenkk** [comment]
My first impression is that the echo plus is a coordinator itself, meaning it cannot join another zigbee network. If that is indeed the case, no.

**Comment by h4nc** [comment]
Ok thanks for your answer!
