### ISSUE TITLE
Aqara S2 Pro lock don't report "lock_opened" and "door_closed"

### ISSUE THREAD

**Issue by utegental** [Koenkk/zigbee2mqtt#8140]
Aqara S2 pro reports "ring_bell" on unlocking the door. And yet it properly reports "locked" action on locking.

Proper actions: door_closed, lock_opened Changing the state LOCK / UNLOCK.

## How to reproduce it (minimal and precise)
Lock the door. Unlock the door. Look at the action values.

## Debug info
Zigbee2MQTT version: 1.20.0
Adapter hardware: Conbee II

**Comment by vostrikov98** [comment]
Were you able to solve this problem?
