### ISSUE TITLE
Unsupported devices: Ubisys

### ISSUE THREAD

**Issue by petterpet** [Koenkk/zigbee2mqtt#815]
Is it possible to include the devices from [Ubisys](https://www.smarthome-store.de/de/ubisys-home-automation-product.html).
They you use the ZigBee-Protocol too.

**Comment by Koenkk** [comment]
Maybe, if you have one you could follow: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html

**Comment by petterpet** [comment]
A friend has one. 
But I think we both don't know enough about JS. So we aren't able to integrate it without help.

By the way: Do you speak german?

**Comment by Koenkk** [comment]
I don't speak german.

You don't need to know a lot about JS, just follow the tutorial above, in case you got stuck you can always ask for help here.
