### ISSUE TITLE
Blacklist/block devices from joining?

### ISSUE THREAD

**Issue by simonvanderveldt** [Koenkk/zigbee2mqtt#816]
It seems like there are a couple devices in my vicinity that are joined to zigbee2mqtt as soon as I enable joining. Is there a way to block/blacklist specific devices from being allowed to join?

I couldn't find any info on this in the issues or documentation.

**Comment by Koenkk** [comment]
Implemented in dev branch, can you verify this feature?

**Comment by simonvanderveldt** [comment]
Cool, thanks! I can check it this week, at the latest this weekend. Is that OK?

**Comment by Koenkk** [comment]
No problem :)

**Comment by tb-killa** [comment]
@Koenkk your implementation use the defined function for remove devices.
As I see this on different devices it seems not work as it should do. 
I think we should rebuild this and use a defined way to prevent them joining again. 

How about add to our devices configuration part something like banned with the addr per device. 
On controller side we should do something like this :
https://github.com/zigbeer/zigbee-shepherd/wiki#API_acceptDevIncoming

This would be a solid way.

**Comment by Koenkk** [comment]
Implemented!

Documentation: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/configuration/configuration.md (`ban`)

Devices banned through `zigbee2mqtt/bridge/config/ban` will also be added to this list.

**Comment by simonvanderveldt** [comment]
Sorry, had some personal things get in the way. Should I still validate/test this?

**Comment by Koenkk** [comment]
@simonvanderveldt yes, please :)

**Comment by Koenkk** [comment]
Any updates?
