### ISSUE TITLE
Aqara E1 single & double wall switch with neutral wire (QBKG40LM & QBKG41LM)

### ISSUE THREAD

**Issue by ilvi80** [Koenkk/zigbee2mqtt#8160]
please add Aqara E1 single & double wall switch with neutral wire

'lumi.switch.b1nc01': ["Aqara", "Single Wall Switch E1", "QBKG40LM"]

'lumi.switch.b2nc01': ["Aqara", "Double Wall Switch E1", "QBKG41LM"]

**Comment by xfzha0** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2831

**Comment by dzarlax** [comment]
> [Koenkk/zigbee-herdsman-converters#2831](https://github.com/Koenkk/zigbee-herdsman-converters/pull/2831)

How can I use it, while running z2m in docker?

**Comment by xfzha0** [comment]
@dzarlax Waiting for the image update .
