### ISSUE TITLE
Disconnect when exposed to a new device, pairing not possible (BlitzWolf BW-SHP13)

### ISSUE THREAD

**Issue by sbbe** [Koenkk/zigbee2mqtt#8163]
# Bug Report
Zigbee2MQTT shuts itself down when exposed to a new BlitzWolf BW-SHP13. After the reboot, pairing fails (unknown device), similar to #6441

## What did you expect to happen
Pairing should be succesful, because I have 2 other paired sockets which work fine.

## Debug Info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: CC2531 with an USB extension
Adapter firmware version: Z-Stack_Home_1.2

# Logs:

## Reboot after exposing to a new device:
Device '0xcc86ecfffe35bbe6' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xcc86ecfffe35bbe6","ieee_address":"0xcc86ecfffe35bbe6"},"type":"device_joined"}'
Info Starting interview of '0xcc86ecfffe35bbe6'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xcc86ecfffe35bbe6","ieee_address":"0xcc86ecfffe35bbe6","status":"started"},"type":"device_interview"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0xcc86ecfffe35bbe6"},"type":"device_connected"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0xcc86ecfffe35bbe6"},"type":"pairing"}'
Debug Device '0xcc86ecfffe35bbe6' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xcc86ecfffe35bbe6","ieee_address":"0xcc86ecfffe35bbe6"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0xcc86ecfffe35bbe6"},"type":"device_announced"}'
Error Adapter disconnected, stopping

## Error messages about the unknown device:
Received Zigbee message from '0xcc86ecfffef3c937', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,0]}' from endpoint 1 with groupID 0
Warning Received message from unsupported device with Zigbee model 'undefined' and manufacturer name 'undefined'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by Piscator74** [comment]
I have plenty of "BlitzWolf BW-SHP13" connected to my zigbee network (version 1.20.0), but with a different adapter running 
Z-Stack_3.x.0. My guess is that it could be related to that.
