### ISSUE TITLE
TS0121 plug image update

### ISSUE THREAD

**Issue by KixMan28** [Koenkk/zigbee2mqtt#8170]
## Is your feature request related to a problem? Please describe

Hi! Could you please update/change the image for the TS0121 plug. The current device image is barely visible. 

## Describe the solution you'd like

Any of the following images would be better, in my opinion.

![TS0121_BW-SHP13 top](https://user-images.githubusercontent.com/33165356/127411767-7db01d8a-0a90-46b8-b18d-8b1ec0cfc273.jpg)
![TS0121_BW-SHP13 side](https://user-images.githubusercontent.com/33165356/127411769-1bdcbf82-841e-42e7-bd81-3d33d7b382e6.jpg)

**Comment by Koenkk** [comment]
Done

**Comment by KixMan28** [comment]
Thank you for your quick reply. I appreciate your on this integration.
