### ISSUE TITLE
Develco (Frient) HESZB-120 test mode

### ISSUE THREAD

**Issue by Theo-NL** [Koenkk/zigbee2mqtt#8171]
Hello,

I have two Frient HESZB-120 heat detectors installed (recognized and installed as Develco HESZB-120), both work within Domoticz and the plugin (heat detection / temp / batt / signal). 
Only the test mode doesn't work, (no respons in Domoticz, etc.) in the Domoticz log appears always the message " 2021-07-28 23:14:03.494 Error: Zigbee2MQTT: (Zigbee2MQTT) Brandmelder keuken: can not process binary item "test"
2021-07-28 23:14:03.496 Error: Zigbee2MQTT: (Zigbee2MQTT) Brandmelder schuur: can not process binary item "test" 

I updated Zigbee2mqtt (1.2.0.0) and the plugin (1.3.0.0)

What could be the problem ?

Thanks in advance !

Regards, Theo (NL).

**Comment by Koenkk** [comment]
I think you used the wrong issue tracker, https://github.com/Koenkk/zigbee2mqtt/discussions/8169#discussioncomment-1085784 (should be https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues )
