### ISSUE TITLE
CTHS-317-ET - CASA.IA - Zigbee temp sensor with cable

### ISSUE THREAD

**Issue by Toukite** [Koenkk/zigbee2mqtt#8172]
## Information about the device + link
..
CASA.IA - Zigbee temp sensor with cable (for swimming pools for example)
Ref CTHS-317-ET

URLs: 
https://casaia.fr/product/sonde-de-temperature-zigbee/
or 
https://www.domadoo.fr/fr/peripheriques/5572-casaia-sonde-de-temperature-deportee-sur-cable-zigbee-3770021021052.html

Someone managed to start something using the documentation (https://community.jeedom.com/t/capteur-temperature-cths-317-et-je-pense-lutiliser-pour-la-temperature-dune-piscine/64436)

Below is the code of his CTHS-317-ET.JS file:
```
module.exports = [
    {
        zigbeeModel: ['CTHS317ET'],
        model: 'CTHS-317-ET',
        vendor: 'CASAIA',
        description: 'Sonde de température',
        exposes: [e.battery(), e.temperature()],
        fromZigbee: [fz.temperature, fz.battery],
        toZigbee: [],
        meta: {battery: {voltageToPercentage: '3V_2500'}},
        whiteLabel: [{vendor: 'CASAIA', model: 'CTHS-317-ET'}],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint3 = device.getEndpoint(3);
            await reporting.bind(endpoint3, coordinatorEndpoint, ['msTemperatureMeasurement']);
            await reporting.bind(endpoint3, coordinatorEndpoint, ['genPowerCfg']);
            await reporting.temperature(endpoint3);
            await reporting.batteryVoltage(endpoint3);
            await reporting.batteryPercentageRemaining(endpoint3);
        },
        exposes: [e.temperature(), e.battery_low(), e.battery()],
    },

];
```

==> Would it be possible to make this device officially supported ?

**Comment by Koenkk** [comment]
Added, 
Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
