### ISSUE TITLE
tamper shows up as [object Object]

### ISSUE THREAD

**Issue by evilpie** [Koenkk/zigbee2mqtt#8178]
## What happened

- `tamper` shows up as `[object Object]` in the "Exposes" tab in the device view

## What did you expect to happen

- Something else like `true` / `false`, similar to `battery_low`

## How to reproduce it (minimal and precise)

- Installed Home Assistant add-on
- Went to the Zigbee2MQTT dashboard
- Clicked on my ZS110050078 door/window sensor
- Selected "Exposes"

## Debug info
Zigbee2MQTT version: 1.20.0
Adapter hardware: CC2531
Adapter firmware version: ?

**Comment by nurikk** [comment]
Hi!
Can you attach complete state.json file from `Settings -> Tools -> Download state` ?

**Comment by evilpie** [comment]
[state.json.zip](https://github.com/Koenkk/zigbee2mqtt/files/6907085/state.json.zip)

**Comment by nurikk** [comment]
Fixed, thanks
