### ISSUE TITLE
What info is stored in routers ?

### ISSUE THREAD

**Issue by HerrieMan72** [Koenkk/zigbee2mqtt#820]
Hi,
I currently have a zigbee network running with ~25 routers (Ikea tradfri lights) and ~25 endpoints (Xiaomi aqara switches/sensors) running on my Homey.
I read that zigbee2mqtt is able to address 20 endpoints directly and that via routers the network can be bigger. I'm wondering what data is stored on the routers, or what function they have to help the coordinator in expanding the network.
In my case part of the routers are still behind a conventional wall-switch, so these routers are not always available. Does a zigbee network automatically correct for routers that are offline ? or can this lead to troubles when these routers are needed to expand the network to all endpoints ?

**Comment by Koenkk** [comment]
Zigbee can rediscover path when a router goes offline (but of course another router must be in range).

**Comment by AnhDuc85** [comment]
@Koenkk how long does it take for an end device to discover a new path?

**Comment by Koenkk** [comment]
@AnhDuc85 it probably depends on a lot of factors, like how close another router is. The best wat to find this out is to try it yourself.

**Comment by HerrieMan72** [comment]
ok, that's good to know, I think that would work for my setup.
But consider the following use-case:
- 1 coordinator
- 2 routers
- 30 endpoints (e.g. 10 directly connected to coordinator and 2 x 10 connected to each router)

What would then happen if 1 of the routers goes offline, would the 10 connected endpoints automatically connect to either the other router or the coordinator ? (assumed that both are in reach)
What would happen if the second router goes offline, would then 10 of the 30 endpoints stop working because the coordinator only supports 20 endpoints ?
What if the routers then come back online, would the network restore itself and will all 30 endpoints be available again, or would these be lost from the network and needs re-pairing ?

I ask this because on my current Homey setup I see very often things like this happening, parts of the network suddenly stop working and don't come back online. I'm very curious whether or not this is zigbee related.

**Comment by Koenkk** [comment]
You have quite few routers, I would recommend adding some more (+- 2) which are always ON. Preferable a CC2530 as it has good range (https://github.com/Koenkk/zigbee2mqtt/blob/dev/docs/how_tos/how_to_create_a_cc2530_router.md)

**Comment by apeinspace** [comment]
In my experience the switching of end-devices varies greatly from one to another. Most of my Xiaomi enddevices (sensors and button-switches) for example are lazy(hours to almost a day) to switch to new routers once their initial router becomes unavailable. 

I can not technically explain why this is the case.

But I remember that the guys writing the deconz software/firmware did test quite extensively - the situation seems to become more complicated the more different vendors you use in your network - IKEA bulps and Xiaomi may behave peculiar together.

see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/912 and https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/End-device-Polling

**Comment by HerrieMan72** [comment]
Hi Koen,
it was a theoretical use-case, in fact I have ~25 routers and ~25 endpoints, see first post above.
I just wanted to know what would happen in a setup like described to get better insight in how zigbee behaves.
The links provided by apeinspace provide some useful info, will study that in more detail because the used devices are also what I use here at home (ikea tradfri combined with xiaomi aqara), thanks for the info.

**Comment by Koenkk** [comment]
> ok, that's good to know, I think that would work for my setup.
> But consider the following use-case:
> 
> * 1 coordinator
> * 2 routers
> * 30 endpoints (e.g. 10 directly connected to coordinator and 2 x 10 connected to each router)
> 
>1.  What would then happen if 1 of the routers goes offline, would the 10 connected endpoints automatically connect to either the other router or the coordinator ? (assumed that both are in reach)
> 2. What would happen if the second router goes offline, would then 10 of the 30 endpoints stop working because the coordinator only supports 20 endpoints ?
> 3. What if the routers then come back online, would the network restore itself and will all 30 endpoints be available again, or would these be lost from the network and needs re-pairing ?
> 

1. Yes, they will try to, how long this takes is unknown (e.g. for some Xiaomi sensor this can take a few hours, for TRADFRI bulbs this seems to go much faster (minutes/seconds)). Of course the router or coordinator should still have space left.
2. Yes
3. They will be available again (same as 1.)
