### ISSUE TITLE
Xiaomi DJT11LM strength is sent as "string" instead of numeric.

### ISSUE THREAD

**Issue by MiguelAngelLV** [Koenkk/zigbee2mqtt#8200]
## What happened

The strength signal is sent as string to Home Assistant, so, is very hard read it

![image](https://user-images.githubusercontent.com/638110/127759740-d10bdb1c-a607-4a0e-8cce-02e4c4720909.png)

## What did you expect to happen

The values may sent as numeric to and home assistant show them in time series chart.

## How to reproduce it (minimal and precise)

Use DTJL11LM with Home Assistant, move it and show the values.

## Debug info
Zigbee2MQTT version: 1.20
Adapter hardware: CC2531
Adapter firmware version:  20201127

**Comment by Koenkk** [comment]
Can you provide the zigbee2mqtt debug log when a new `strength` is published?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by MiguelAngelLV** [comment]
```
Debug Received Zigbee message from 'Puerta garaje', type 'attributeReport', cluster 'genBasic', data '{"65282":[{"elmType":16,"elmVal":0},{"elmType":33,"elmVal":3045},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,3]},{"elmType":33,"elmVal":252},{"elmType":32,"elmVal":85}]}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Puerta garaje', payload '{"battery":100,"contact":true,"linkquality":44,"voltage":3045}'
Debug Received Zigbee message from 'Movimiento sótano', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Movimiento sótano', payload '{"battery":100,"linkquality":42,"occupancy":true,"voltage":3035}'
Debug Received Zigbee message from 'Movimiento despensa', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Movimiento despensa', payload '{"battery":100,"linkquality":42,"occupancy":true,"voltage":3045}'
Debug Received Zigbee message from 'Movimiento entrada', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Movimiento entrada', payload '{"battery":100,"linkquality":47,"occupancy":true,"voltage":3065}'
Debug Received Zigbee message from 'Lavadora', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":1}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Lavadora', payload '{"action":"vibration","angle":9,"angle_x":-3,"angle_x_absolute":93,"angle_y":78,"angle_y_absolute":12,"angle_z":12,"battery":86,"linkquality":31,"sensitivity":"high","strength":8,"voltage":2975}'
Info MQTT publish: topic 'zigbee2mqtt/Lavadora', payload '{"action":"","angle":9,"angle_x":-3,"angle_x_absolute":93,"angle_y":78,"angle_y_absolute":12,"angle_z":12,"battery":86,"linkquality":31,"sensitivity":"high","strength":8,"voltage":2975}'
Info MQTT publish: topic 'zigbee2mqtt/Lavadora/action', payload 'vibration'
Debug Received Zigbee message from 'Estufa Baño', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/Estufa Baño', payload '{"linkquality":31,"state":"OFF"}'

```
In the payload is show as number, but Home Assistant show it as string...

I removed all states of devices from Home Assistant database, but it did not resolve the problem.

**Comment by Koenkk** [comment]
@emontnemery do you know why this happens? The value is send as a number but displayed as a string in HA.

**Comment by MiguelAngelLV** [comment]
I checked and in the mqtt payload is sent as numeric too.

![image](https://user-images.githubusercontent.com/638110/128072016-6120f507-9e95-40e9-9a63-7f1617091852.png)


So, the problem is HA... Maybe HA require explicit numeric definition? Any attribute (state class, measurement...) ?

The angles are numeric and they are show as string...

![image](https://user-images.githubusercontent.com/638110/128072265-7e8a55a8-fb95-4c65-b511-74cd3042f778.png)

Battery and link quality they are show as numeric in a chart.
