### ISSUE TITLE
"tsc not found" in v1.21.0 start

### ISSUE THREAD

**Issue by 11csive** [Koenkk/zigbee2mqtt#8208]
## What happened
npm start fails with "tsc not found"

## What did you expect to happen
zigbee2mqtt to start without errors

## How to reproduce it (minimal and precise)
Follow https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html until the "npm start" step.

## Debug info
Zigbee2MQTT version: 1.21.0

Having had a quick look at the new version, I assume this is caused by Typescript being set as a devDependency, and the documentation instructs users to use the --production argument, which causes the devDependencies to not be installed.

Running npm ci without the --production argument makes it start as normal. :)

**Comment by 11csive** [comment]
Nevermind, I just noticed that the documentation was updated to include this. I guess we are waiting for the cdn to update the website.. :)

**Comment by Koenkk** [comment]
Fixed with https://github.com/Koenkk/zigbee2mqtt.io/pull/844
