### ISSUE TITLE
Adding info to 'Supported Devices' if device is a router?

### ISSUE THREAD

**Issue by DerMattes** [Koenkk/zigbee2mqtt#821]
Hi,
I am missing the information which of the supported devices are confirmed zigbee routers from the [list of supported devices](https://koenkk.github.io/zigbee2mqtt/information/supported_devices.html).
There is contradictory information out there, like _"Hue bulbs only route Hue devices"_, _"every zigbee device that is not on battery power is a router"_, etc.
I looked around this "issue-forum" and the only confirmed router I found was the Osram Smart+ plug.
As the range 'problem' is affecting everyone here, I think the confirmation if a device is acting as a router with zigbee2mqtt would be very beneficial for planning the mesh.

@Koenkk: Thank you for your work in this!

**Comment by sehraf** [comment]
Just check the log, it tells you which device is a router and which is an endpoint
```bash
cat 2019-01-05.14-08-34/log.txt | grep Router | sed -e 's/.*\:\s//g' | sort | uniq
8718696449691 - Philips Hue White Single bulb B22 (Router)
8718696485880 - Philips Hue white and color ambiance GU10 (Router)
AB3257001NJ - OSRAM Smart+ plug (Router)
LED1623G12 - IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, opal white (Router)
```
I'm not aware of any devices that "do not speak" to other brands (also i would assume that these devices are not conforming the zigbee standard)

Based on my network map my Hue devices are routing Xiaomi devices (and they are connected to the coordinator through a IKEA bulb). So i would call BS on *"Hue bulbs only route Hue devices"*

**Comment by DerMattes** [comment]
Thank you for your answer, this helps a lot.
This topic is currently quite confusing for me, as I am deciding which devices to buy. I currently have a couple of Xiaomi Aqara sensors and more are on the way.
But they will not be placed in range to the RPi with the coordinator, so I need routers. To know which devices work as routers would help me in deciding what to buy. Ikea, Osram, Hue, etc.

**Comment by sehraf** [comment]
I'd go with *"every zigbee device that is not on battery power is a router"*. 
See also https://github.com/Koenkk/zigbee2mqtt/issues/52#issuecomment-451918301

For the record: Based on my network map i have the following (interesting) routes:
>coordinator <-> IKEA <-> Phillips <-> Xiaomi
>coordinator <-> IKEA <-> Osram <-> Xiaomi

**Comment by DerMattes** [comment]
Thanks!

**Comment by Chrischi-** [comment]
IKEA is now also selling Routers (only) with USB Ports.

[https://www.ikea.com/de/de/catalog/products/10400408/](https://www.ikea.com/de/de/catalog/products/10400408/)

**Comment by goldiiii** [comment]
> IKEA is now also selling Routers (only) with USB Ports.
> 
> https://www.ikea.com/de/de/catalog/products/10400408/

Ikea wrote on their homepage that it only extends ikea devices.

**Comment by Chrischi-** [comment]
I'm almost sure the router will also support other devices if it acts as a router as defined by the zigbee Alliance.

We'll see as soon as someone could buy it.

**Comment by matejzero** [comment]
Even better then the new repeater is their plug: https://www.ikea.com/at/de/p/tradfri-steckdose-funkgesteuert-90356166/

At least to me, since with the router, the socket becomes usb charger only, but with the plug, you still have full functionality. And it's bit narrower, so you can hide it behind a closet if you have a socket there:)
