### ISSUE TITLE
Zigbee model 'TS0202' and manufacturer name '_TYZB01_qjqgmqxr'

### ISSUE THREAD

**Issue by vjiggi** [Koenkk/zigbee2mqtt#8213]
I tried the how to but seemed to be lost. Sorry, I am out of my depth here.
## Information about the device + link
Zigbee model 'TS0202' and manufacturer name '_TYZB01_qjqgmqxr'
https://www.ikuu.com.au/product/motion-detector/
I think it might be a https://www.zigbee2mqtt.io/devices/TS0202_CR.html
## data/database.db entry of the device
..

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
