### ISSUE TITLE
DC Switch module not identified correctly

### ISSUE THREAD

**Issue by svisso** [Koenkk/zigbee2mqtt#8224]
Hi there
I have bought two DC Switch Modules, one with 2 gangs and one with 4 gang. Pairing succeeded. But the modules were differently identified:
2gang: eWeLink ZB-SW02
4gang: TuYa TS0004

# Bug Report
## What happened
Both devices start working correctly. All channels do switch, tested both from Zigbee2MQTT Dashboard and Node Red.
But after some time, the 4 channel device becomes unresponsive, causing Zigbee2MQTT log entries like "no network route (205)", being followed by subsequent publish errors. 

## What did you expect to happen
Expectation was both modules to function identically correct.

## How to reproduce it (minimal and precise)
When unresponsive, power cycle the switch module.
This brings working state back.
Wait for some hours.
Device stops communicating again. (While unresponsive, the four channels can be operated manually on the pcb controls)

## Debug Info
Zigbee2MQTT version: 1.20
Adapter hardware: CC2531, supposedly. It is a TI in a USB stick. 28 more devices controlled by it.
Adapter firmware version: I don't know how to find this.
Here is the error I consider to be crucial: 
Zigbee2MQTT:info  2021-08-02 16:51:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'TuYa 4Gang Switch Module' failed: 'Error: Command 0xa4c1389088a86afe/1 genOnOff.on({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"TuYa 4Gang Switch Module"},"type":"zigbee_publish_error"}'

Any help being greatly appreciated. 
Thank you great Masters in advance.

Cheers, Michael

**Comment by MattWestb** [comment]
`"no network route (205)"` = the device can getting one route to the coordinator or the other way = network problems.
