### ISSUE TITLE
Very high latency with an outdoor sonoff zbmini 

### ISSUE THREAD

**Issue by ahocquet** [Koenkk/zigbee2mqtt#8227]
# Bug Report
## What happened

Hello,

I own a ZZH coordinator adapter backed up with five CC2530 DC powered routers (homemade built thanks to the guide on z2m website).

I have placed on of these router outside close to my garden sheds, 10m away from my kitchen. In this garden shed, I have a Sonoff ZBMINI that I use to control some lights.

The problem is that I have a very high latency (more than 10s) controlling this zonoff zbmini switch. I have other zbmini switches indoor without any problems.

I've mapped my setup and here's the result. My outdoor zbmini name is "Eclairage guirlande" whereas my CC25430 router close to it is named "CC2530 Router E - Local piscine"

![image](https://user-images.githubusercontent.com/1451308/127921794-46dc4b55-69cb-461d-870d-a9d6e2a81e6a.png)
![image](https://user-images.githubusercontent.com/1451308/127921943-f8ebe848-edbd-4c44-b41f-13692977e0ae.png)
![image](https://user-images.githubusercontent.com/1451308/127922487-288a4c98-7f77-43a9-a9a9-64c96b4e69d1.png)

The funny thing is that when I restart Z2M, then the first time I activate the switch it reacts quite fast. But then it starts to lags a lot, like if it was trying to use a slower route than the one with the closest router "CC2530 Router E - Local piscine". I've red-circled the other possible routers that might be used for this switch but that are way further in distance.

[Logs here](https://hastebin.com/ufujoqayir.apache)
[More logs](https://hastebin.com/owesuhatuk.apache)
## What did you expect to happen
I'd expect a low latency around 1 second.

## How to reproduce it (minimal and precise)
Just using it.

## Debug Info
Zigbee2MQTT version: 1.21.0-dev commit: 62d7636 
Adapter hardware: ZZH coordinator and five CC2530, routers
Adapter firmware version: 
 - CC2652R_coordinator_20210120
 - CC2530_CC2591_router_2020_09_29

**Comment by emms007** [comment]
I am having the same issue, using two ZBMINI that are pretty close in an garden electrical box (10cm away).
Some action would go there pretty fast, some other would timeout.

I wonder if the problem is not that the routers are not too close, as I am reading in the solution of https://github.com/Koenkk/zigbee2mqtt/issues/3748

How close is the distance of routers in your case?

**Comment by ahocquet** [comment]
@emms007 sorry for the late reply. I didn't want to spend to much time in solving this issue so I've replaced these sonoff zbmini with shelly relays. Problem solved :)
