### ISSUE TITLE
Map link problem with the coordinator

### ISSUE THREAD

**Issue by larod241** [Koenkk/zigbee2mqtt#8228]
## What happened

I have just redo the installation of all my sensors taking advantage of making the FW maj of the Combee II and Zigbee2MQTT (1.21.0)
After a few hours, all the coordinator-related sensors are no longer related in the MAP display.
They still work however

They were all a few hours before!

I restarted zigbee2mqtt, but same problem.

Just after the pairing
<a href="https://ibb.co/gJcvvMD"><img src="https://i.ibb.co/GRrssvV/220088575-164695338983144-5004296597586510147-n.png" alt="220088575-164695338983144-5004296597586510147-n" border="0"></a>

After a while 
<a href="https://ibb.co/xLHsbxQ"><img src="https://i.ibb.co/1Q6nNFx/Capture-d-cran-2021-08-03-03-53-03.png" alt="Capture-d-cran-2021-08-03-03-53-03" border="0"></a>

## Debug info
Zigbee2MQTT version: 1.21.0
Adapter hardware: Conbee II
Adapter firmware version: 0x266f0700

**Comment by nukleuz80** [comment]
Hi,

i have the same setup and same issue you subscribed.

**Comment by Koenkk** [comment]
I've added an explanation on why this happens to the FAQ: https://www.zigbee2mqtt.io/information/FAQ.html#why-are-some-links-missing-from-my-networkmap . This is not something that can be fixed from zigbee2mqtt.

**Comment by xekil** [comment]
same problem, and thanks for the FAQ

In my case, I have xiaomi plugs which are not Zigbee 2 and which nevertheless behave like this, the same for certain xiaomi modules which are directly with the coordinator.
