### ISSUE TITLE
Tuya TS0501B with manufacturerName: _TZ3000_12sxjap4

### ISSUE THREAD

**Issue by fairyfeller** [Koenkk/zigbee2mqtt#8232]
Works like a charm with config below

## Information about the device + link
https://aliexpress.ru/item/1005002733507274.html

## data/database.db entry of the device
`const definition = {
    fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3000_12sxjap4'}],
        model: 'TS0505B',
        vendor: 'TuYa',
        description: 'Zigbee RGB+CCT light',
        whiteLabel: [{vendor: 'Tuya', model: 'A5C-21F7-01'}],
        extend: extend.light_onoff_brightness_colortemp_color(),
        meta: {applyRedFix: true, enhancedHue: false},
};`

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
