### ISSUE TITLE
Latest CC2531 firmware for flash via Arduino/ESP8266(alternative flashing method)

### ISSUE THREAD

**Issue by simpat1zq** [Koenkk/zigbee2mqtt#824]
So I was able to flash using the alternative method a couple months ago, and everything has been OK. However, I'm seeing now that this method used a special build of the firmware from a year ago. There have been many updates to it since them. Is there an updated firmware to flash via the alternative method? Can I just use the regular build, or does the arduino method still need a special build?

**Comment by Chrischi-** [comment]
you can take the normal .hex version of the firmware from [here](https://github.com/Koenkk/Z-Stack-firmware) and remove the second last line

**-**`:0400000500002D7357`

**Comment by roger-** [comment]
Is the only significant change in that version the ability to support more devices?

**Comment by Chrischi-** [comment]
for the C2531 there are currently 2 firmware versions available from @Koenkk  

- normal, ~16 devices and ~16 routers
- max devices, 44 devices and 1 router

the dev branch is currently working on an improved firmware. 
therefore i would wait with an update.

**Comment by simpat1zq** [comment]
Cool. Thanks guys. I don't have many devices now, so I guess I'll just wait for the latest firmware update before I do anything.

**Comment by adn77** [comment]
I read somewhere that the .bin versions of the firmware can be flashed directly via the TI tool (without the debugger).
If that was true, how do we generate a .bin file from the .hex?

**Comment by Chrischi-** [comment]
It needs to be compiled. You can't convert the bin file.
