### ISSUE TITLE
_TZ3000_ebar6ljy Not supported

### ISSUE THREAD

**Issue by ggdijkstra** [Koenkk/zigbee2mqtt#8240]
Friendly name
Sensor Voordeur
Last seen
N/A
Device type
EndDevice
Zigbee Model
TS0203
Zigbee Manufacturer
_TZ3000_ebar6ljy
Support status
Not supported

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
