### ISSUE TITLE
Tuya sensor zigbee ty-zdr06 problem

### ISSUE THREAD

**Issue by NunoSampaio** [Koenkk/zigbee2mqtt#8257]
I have a tuya zigbee 3.0 door sensor model ty-zdr06 , But it is not recognized by smartthings. I can't integrate, And it doesn't even appear as "things"

Can you help?

This model:

https://a.aliexpress.com/_msWLvu3

**Comment by Koenkk** [comment]
This is the zigbee2mqtt issue tracker not the smart things one.
