### ISSUE TITLE
LELLKI WP33-EU not supported

### ISSUE THREAD

**Issue by bernd-uhl** [Koenkk/zigbee2mqtt#8276]
## What happened
Hello I would like to teach a LELLKI WP33-EU to Z2M but this does not work:
[https://www.zigbee2mqtt.io/devices/WP33-EU.html](url)
I've been trying this for months now in the hope that this will work out at some point.
Thank you very much for the help.
## How to reproduce it (minimal and precise)
get the following information in the logs:
![zigbee2mqtt5](https://user-images.githubusercontent.com/84871139/128501302-6d843323-625b-498a-a64b-2a07e2f4041d.JPG)
![zigbee2mqtt](https://user-images.githubusercontent.com/84871139/128501352-2ec17676-7b69-4970-b56a-e2176ef0d083.JPG)
## Debug info
Zigbee2MQTT version: 1.21.0-dev commit: 10615e29
Coordinator Typ: zStack3x0
Coordinator Version: 20210320
Frontend Version: 0.5.19

**Comment by bernd-uhl** [comment]
https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/WP33-EU.md

**Comment by Koenkk** [comment]
This version is already supported in the latest dev branch (second fingerprint of https://github.com/Koenkk/zigbee-herdsman-converters/blob/c629717fa7cabde128371253df09befaaf0a1585/devices/lellki.js#L11)
