### ISSUE TITLE
Philips Hue power-on behavior/settings

### ISSUE THREAD

**Issue by Chrischi-** [Koenkk/zigbee2mqtt#828]
Is anybody already working on implementing this?

Philips Hue power-on behavior/settings
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1014#

ClusterID: 6
Attr.ID: 0x4003 / 16387
dataType: 48 / enum8

0 Off
1 On
255 previous

with "on" you have to set further settings. Brightness, Temperature or Color

     cid    |     attrid
0x0008 | 0x4000 A uint8
0x0300 | 0x4010 PowerOn colour temperature
0x0300 | 0x0003 Current X
0x0300 | 0x0004 Current Y

The settings are retained until the lamp is reset. After that the "default" settings are active again. Exactly what a factory reset is responsible for. ;)

To use this function you need the latest firmware from Nov/Dec '18.

> Nov 28, 2018
> Software version: 1.46.13_r26312
> 
>     Affected products (Hue Bulbs (E26/E27/E12/E14/BR30/GU10), Hue Lightstrips, Hue Lamps);
>     Reliability, behavioural and security improvements;
>     Smoothening of light transitions in entertainment mode;
>     Enabling power-on behavior feature.

**Comment by Koenkk** [comment]
Yes, please see #746
