### ISSUE TITLE
Add sensor.last_seen when homeassistant_legacy_entity_attributes is false

### ISSUE THREAD

**Issue by Enzokot** [Koenkk/zigbee2mqtt#8287]
## Is your feature request related to a problem? Please describe
If I set `homeassistant_legacy_entity_attributes` to false, then the `last_seen` and `device` attributes will be removed from all sensors,  that is expected.

## Describe the solution you'd like
Please, add `sensor.ieeeAddr_last_seen` for all devices when `homeassistant_legacy_entity_attributes` is `false` and advanced option `last_seen` is `on`

## Describe alternatives you've considered
I don't know any alternative ways to solve the problem.

## Additional context
-

**Comment by andrew-d** [comment]
Not stale

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by andrew-d** [comment]
Speaking personally, I have a notification that goes out periodically that tells me what devices are unreachable, and having the 'last seen' date is helpful to know if it's temporary (i.e. I ignore devices that are only "unavailable" for short periods).

**Comment by Enzokot** [comment]
Thanks!

**Comment by Enzokot** [comment]
@Koenkk when I open `mqtt` integration frontend page this error appears: 
```
Logger: frontend.js.latest.202111090
Source: components/system_log/__init__.py:190
First occurred: 18:24:34 (1 occurrences)
Last logged: 18:24:34

http://homeassistant.local:8123/frontend_latest/20a1269e.js:1:351 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
```
My configuration contains `last_seen: epoch` and this add `sensor.*_last_seen` with `device_class: timestamp` but `timestamp` is only for: `Datetime object or timestamp string (ISO 8601)`

**Comment by Koenkk** [comment]
Should be fixed now.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Enzokot** [comment]
Thanks!

**Comment by jschwalbe** [comment]
Can anyone explain how to make this show up in HA?

It's showing up correctly in MQTT:
<img width="322" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/8005921/e3b5f00f-14ca-4c95-bd76-3665878b2ba9">

But HA won't let me see the last_seen value:
<img width="502" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/8005921/ec408e31-a465-4b56-a6cc-0d2ba0c4196a">

Any thoughts? Thanks!
