### ISSUE TITLE
No converter available for 'linkquality' _TYZB01_qeqvmvti (TS0011)

### ISSUE THREAD

**Issue by elgerg** [Koenkk/zigbee2mqtt#8288]
Hi,
I have a couple of these TS0011 devices. They when turned on or off report no converter for link quality.

## What happened
![image](https://user-images.githubusercontent.com/24628571/128597468-ebdac28b-4586-48f9-ac28-fc2d1ae629a3.png)

However sometimes it must report properly as it does seem to work:
![image](https://user-images.githubusercontent.com/24628571/128597504-1952d134-1c58-4daf-a841-b6e3f5a90126.png)

## What did you expect to happen
I expected the link quality to be updated

## How to reproduce it (minimal and precise)
Turn the switch on or off or wait for it to announce itself on the network

## Debug info
Zigbee2MQTT version:1.21.0
Adapter hardware: CC2531
Adapter firmware version: 3.0

**Comment by Koenkk** [comment]
Can you provide the debug log of this?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by xychix** [comment]
[no action needed, purely for future reference]

I was about to post logs for this issue when I found my issue.
getting a json from a dimmer and sending that to a lamp / other dimmer failed as it had the linkquality field in the json.

using a node-red change object to delete that msg.payload.linkquality field before sending the json out solved this.
