### ISSUE TITLE
ZNCLDJ12LM (Aqara B1 curtain motor) OTA update not working

### ISSUE THREAD

**Issue by Chriserus** [Koenkk/zigbee2mqtt#8297]
## What happened

OTA update for ZNCLDJ12LM (Aqara B1 curtain motor) is not working. I get "Failed to check if update available for 'Curtain' (Cannot read property 'ID' of undefined)", the same goes for manual command for checking for update and trying to directly update the device "Update of 'Curtain' failed (Cannot read property 'ID' of undefined)" (as explained on OTA wiki page https://www.zigbee2mqtt.io/information/ota_updates.html#manually-check-if-an-update-is-available and https://www.zigbee2mqtt.io/information/ota_updates.html#update-to-latest-firmware ). I am running the latest z2mqtt version, my curtain motor: Build date: 20190329, Firmware version: 2019www. 

## What did you expect to happen

An update to occur / is update available check success for Aqara B1 curtain motor.

## How to reproduce it (minimal and precise)

I hope it's replicable with the above mentioned device and newest z2mqtt version.

## Debug info
Zigbee2MQTT version: 1.21.0-1
Adapter hardware: CC2531

**Comment by Koenkk** [comment]
Please provide the debug log of this.

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by Chriserus** [comment]
Here's a complete log from manual update check: https://pastebin.com/QqjZ2MZ0
And here's a log from trying to manually update the device: https://pastebin.com/DXWm7jXQ

**Comment by Koenkk** [comment]
Added some more logging, can you update to the latest dev branch and provide the debug logging again? (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Chriserus** [comment]
Sorry for the delay, here are the logs:
OTA check https://pastebin.com/E3gB68a2
OTA update https://pastebin.com/pRUG4Eur
I hope this helps :)

**Comment by Koenkk** [comment]
I've made the error more human friendly now, but the root cause is that your device does not have an OTA endpoint. Please share your data/database.db entry so I can confirm this.

**Comment by Chriserus** [comment]
Here is the database.db entry of my device: https://pastebin.com/ckeJiHKw

**Comment by Chriserus** [comment]
If that's the case, that my device does not support OTA, we should also update the wiki page for the device, to not mislead people (if that's the case, that it shows like it is possible/supported but it is not)

**Comment by Koenkk** [comment]
Your device indeed does not have the OTA cluster, what you can try is adding it and see if it works:
- stop z2m
- add `25` to the `outClusterList` of your ZNCLDJ12LM 
- start z2m and attempt the ota update, does this work?
-

**Comment by Chriserus** [comment]
I have followed your instructions and indeed, the update has started! Here are the logs from requesting an update for the device after adding 25 to outClusterList: https://pastebin.com/F24aBBQG

It takes some time, I'll let you know if it succeeds.

**Comment by Chriserus** [comment]
It seems like it succeeded, but I don't see a version change, see finishing logs here https://pastebin.com/MYLCPWF6

**Comment by Koenkk** [comment]
can you try repairing the device?

**Comment by z-x-f** [comment]
delete it and rejoin.

**Comment by Chriserus** [comment]
Repairing, like, repair a car, why didn't I think about pairing the device again? :D 
I did it, it then showed that an update is available, I did an update, it was successfull, but the version is still old, nothing changed.

**Comment by jeroenvdd** [comment]
This motor is still not getting the correct OTA info, update via xiami hub is far more recent

**Comment by Hessenpower01** [comment]
Same here, mine ist stuck on version 2019www. dated 20200803

tried adding "25" to outclusterlist, no effect

**Comment by Rig820** [comment]
How do you add to the outClusterLIst?

**Comment by Jarikk** [comment]
The same question: How I can manually add OTA cluster?
Mine is also stuck at the :
Firmware build date 20190329
Firmware version 2019www.

I added it to the Mi account via Xiaomi Gateway 3 - but there are no any firmware updates available in the Mi Home application.

**Comment by Hessenpower01** [comment]
In here: /config/zigbee2mqtt/database.db

**Comment by new-kirte** [comment]
@Koenkk adding 25 to outClusterLIst works fine - firmware updates appear and getting applied. Is if possible to add this endpoint automatically for Aqara B1 curtains?

**Comment by Jarikk** [comment]
@new-kirte Are you sure that new firmware has actually been downloaded to your motor? I added 25 to the clusters list, ran available OTA update for my curtains and after an hour of updating the device firmware version remains the same as it was before updating.

**Comment by new-kirte** [comment]
> @new-kirte Are you sure that new firmware has actually been downloaded to your motor? I added 25 to the clusters list, ran available OTA update for my curtains and after an hour of updating the device firmware version remains the same as it was before updating.

Yes it does. The version number is changing
