### ISSUE TITLE
Remove firmware confusion

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt#83]
There are too many places for the firmware:
https://github.com/Koenkk/zigbee2mqtt/tree/master/firmware
https://github.com/Koenkk/zigbee2mqtt-firmware/tree/master/coordinator/Z-Stack%20Home%201.2.2a.44539/Projects/zstack/ZNP/CC253x/dev

Documentation points to the second and there have been several revisions linked in some of the issues. 

Recommendation:
- [x] Remove firmware from https://github.com/Koenkk/zigbee2mqt
- [x] Remove firmware from https://github.com/Koenkk/zigbee2mqtt-firmware/tree/master/coordinator/Z-Stack%20Home%201.2.2a.44539/Projects/zstack/ZNP/CC253x/dev 
- [x] Create a folder in root of https://github.com/Koenkk/zigbee2mqtt-firmware with a way to identify latest "stable"
- [x] Create a folder in root of https://github.com/Koenkk/zigbee2mqtt-firmware for testing firmwares with maybe a readme in the folder describing the function
- [x] Include separation of coordinator vs router firmware

**Comment by Koenkk** [comment]
I think everything is done here.

**Comment by keesschollaart81** [comment]
What is the difference between 
https://github.com/Koenkk/Z-Stack-firmware
and
https://github.com/Koenkk/zigbee2mqtt-firmware

**Comment by Koenkk** [comment]
zigbee2mqtt-firmware will be removed soon (contains TI Z-stack code). 

Z-stack is the new one.

**Comment by keesschollaart81** [comment]
If I flashed with the 'old' version (3 weeks ago), might there be a reason to upgrade?

**Comment by Koenkk** [comment]
Only when you are having stability problems. (but currently this only happens with larger networks, 15+ nodes).
