### ISSUE TITLE
MOEs ZigBee Dimmer Module (AliExpress) 1-ch support

### ISSUE THREAD

**Issue by gert3d** [Koenkk/zigbee2mqtt#8302]
Hi there,
I have no clue what to do with the information on:
https://github.com/Koenkk/zigbee-herdsman-converters/commit/eba65cddc4f4abe5f1e7661e8145ed3bed2c8b6b
to add support for a 1-ch moes module (I am using Domoticz).
Can anyone direct me to some explanation of steps to be taken?
thanks
![Dimmer-Moes](https://user-images.githubusercontent.com/2662896/128631864-00b581dd-6bb1-4aa5-80b4-103d71e78f3a.jpg)

**Comment by robertalexa** [comment]
The device should be supported. You shouldn't need to do anything more than pairing. Support is available in z2m 1.21.0. Make sure you are on the latest version
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.21.0
![image](https://user-images.githubusercontent.com/9019306/128637364-a083c90e-4b9c-4463-8f64-dc34433d4302.png)

**Comment by gert3d** [comment]
Thanks. 
However ... next problem: I cannot find information how to update zigbee2mqtt running with Domoticz.
Is it as simple as swapping for new file(s)?
Probably not the right place to ask this, sorry for that.

**Comment by robertalexa** [comment]
https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#6-for-later-update-zigbee2mqtt-to-the-latest-version

**Comment by gert3d** [comment]
Thanks, I'll give it a try.
