### ISSUE TITLE
Regular z2m freezes when working with a stick based on EFR32 (SM-011)

### ISSUE THREAD

**Issue by khaidakin** [Koenkk/zigbee2mqtt#8320]
## What happened
At least once a day, there is a short-term freeze (up to one minute) of Zigbee2Mqtt on the Efr32 stick. Suspension occurs at the moment of sending relay control commands (WHD02 and ptvo.switch). At the same time, if at the time of suspension you manually control these devices, then their status changes in Z2M, but it is impossible to control. After approximately 1 minute of time, work is restored and at the time of recovery, all commands that were sent at the time of the hang are processed at once.

## What did you expect to happen
Stable network operation, as it happens on sticks based on cc2538 and cc2652

## How to reproduce it (minimal and precise)
Connect multiple devices to an Efr32 based stick including multiple relays and make simple automation or control these relays in Frontend

## Debug info
Zigbee2MQTT version: 1.21.0-dev commit: db61a623
Adapter hardware: EZSP v8 - EFR32MG21A020F768IM32 (SM-011)
Adapter firmware version: 6.7.8.0 build 373
https://pastebin.com/LZKnpzKM

**Comment by Koenkk** [comment]
The ERF32 is still in a very experimental phase. Please post your feedback here: https://github.com/Koenkk/zigbee-herdsman/issues/319
