### ISSUE TITLE
install package.json files for extensions to root node_modules

### ISSUE THREAD

**Issue by burstMembrane** [Koenkk/zigbee2mqtt#8328]
Hi, I've got an extension which is running inside the data/extensions/ folder of /opt/zigbee2mqtt

the extension folder has it's own node_modules directory and package.json listing it's dependencies.

The problem is when I run npm start from the root directory it can't find the modules required in my extension code. 

Is there a way of adding the node_modules folder from a subdirectory to the root zigbee2mqtt package.json (without having to install the package manually from the /opt/zigbee2mqtt root)?

Thanks in advance for your help and please let me know if you need more info!

**Comment by Koenkk** [comment]
If the `node_modules` folder (of your extension) is next to your `extension.js` you can include things with e.g. `const mymodule = require('../node_modules/mymodule');`
