### ISSUE TITLE
Smart plug TuYa Model Zigbee TS0121

### ISSUE THREAD

**Issue by amy92000** [Koenkk/zigbee2mqtt#8330]
Hello
I have some zigbee plugs of the TuYa TS0121 model
but I have no energy back.
when I look at the documentation I see this
thanks in advance.

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.energy }}"
    unit_of_measurement: "kWh"
    device_class: "energy
![Scree](https://user-images.githubusercontent.com/88776729/129021795-43cb5133-f8b2-4e77-8863-fb32882444e6.jpg)
![Screens](https://user-images.githubusercontent.com/88776729/129021797-e0e7ddc9-0f4a-436c-8571-7d9930f19913.jpg)

**Comment by Plawasan** [comment]
FWIW I have the same power socket and I do get an energy readout... (still no way to reset it though..)

From HA Device info (don't have access to z2m dashboard right now):
10A UK or 16A EU smart plug (TS0121_plug)
by TuYa
Firmware: Zigbee2MQTT 1.21.0

Fridge Current 0.37 A
Fridge Energy 29.48 kWh
Fridge Power 89 W
Fridge power outage memory On

**Comment by Plawasan** [comment]
FWIW I have the same power socket and I do get an energy readout... (still no way to reset it though..)

From HA Device info (don't have access to z2m dashboard right now):
10A UK or 16A EU smart plug (TS0121_plug)
by TuYa
Firmware: Zigbee2MQTT 1.21.0

Fridge Current 0.37 A
Fridge Energy 29.48 kWh
Fridge Power 89 W
Fridge power outage memory On

**Comment by GSzabados** [comment]
Something is fishy here. I have just lost the energy reading for that plug. (Or I just noticed it...)

@Plawasan, can you restart HA and Z2M just for a check that it shows up normally after?

**Comment by GSzabados** [comment]
@Plawasan - Never mind, I think, I've found the issue.

https://github.com/Koenkk/zigbee2mqtt/issues/8201

@amy92000 - Are you still on HA 2021.7.X as I am? I haven't updated to 2021.8.X yet, but that seems to fix my Unknown issue and I guess it should fix yours as well.

**Comment by amy92000** [comment]
This is what HA my outlet is connected via the ZigbeeLinker plugin (zigbee2mqtt)

**Comment by GSzabados** [comment]
> This is what HA my outlet is connected via the ZigbeeLinker plugin (zigbee2mqtt) Jeedom

Ah, OK. By the way, have you used that plug at least that much that it would show any energy?

Try to re-interview the plug as well.

**Comment by stevetz** [comment]
I'm also having the same issue - re-interviewed. run for 30 hours. I also changed the poll interview to 30s, with no luck changing. energy is showing as `null`

**Comment by amy92000** [comment]
it's the same with me too "energy": null

**Comment by amy92000** [comment]
I found the solution you have to go to Z2M selection not taken and you go to the report you will have to add commands as in the photo and then you [work.]
<img width="940" alt="z2m" src="https://user-images.githubusercontent.com/88776729/129933806-722bc6e1-0d0d-4705-8aa8-755be9c1ad24.png">

**Comment by amy92000** [comment]
you just have to add up to line in z2m reports and you would have the value Energy
![z2m good](https://user-images.githubusercontent.com/88776729/129939325-c85cd30c-1162-416f-be7e-cdd2a6980321.png)

**Comment by stevetz** [comment]
@amy92000 merci, this works perfectly!

**Comment by amy92000** [comment]
Super contente pour toi👍👍😂😂

**Comment by csszokolai** [comment]
> I found the solution you have to go to Z2M selection not taken and you go to the report you will have to add commands as in the photo and then you [work.]
> <img alt="z2m" width="940" src="https://user-images.githubusercontent.com/88776729/129933806-722bc6e1-0d0d-4705-8aa8-755be9c1ad24.png">

It works for me! Thank you!
