### ISSUE TITLE
Nyce NCZ-3043-HA reporting null for battery, temperature and humidity

### ISSUE THREAD

**Issue by greggotcher** [Koenkk/zigbee2mqtt#8336]
## What happened
I added the Nyce NCZ-3043-HA to zigbee2mqtt without any problem.  It is reporting the following:
{
"battery":null,
"battery_low":false,
"humidity":null,
"linkquality":108,
"occupancy":false,
"tamper":false,
"temperature":null
}
As you can see, battery, humidity and temperature are all reporting null.
I thought that it just might take a bit of time to report correctly, but it has been over 12 hours now and still reporting null for these three values.

## What did you expect to happen
I was expecting see the battery level, the temperature and humidity all be reported with a numerical value like the zigbee2mqtt product page says it would be.

## How to reproduce it (minimal and precise)
Not sure how to reproduce, all that I did was pair the device and I am not getting the readings I expected.

## Debug info
Zigbee2MQTT version: 1.21.0 commit: 70891ee
Adapter hardware: cc2652rb
Adapter firmware version: not sure where to find this

**Comment by eblau** [comment]
I'm seeing the same thing. Did anyone figure this out? The same device was working just fine on an older version of Home Assistant using ZHA.
