### ISSUE TITLE
Switching between identical coordinators

### ISSUE THREAD

**Issue by EricVdB** [Koenkk/zigbee2mqtt#8342]
Hi,

I have 2 Texas Instruments LAUNCHXL-CC26X2R1 boards. Can I upgrade the firmware on the spare board, connect the spare board to zigbee2mqtt and test everything without re-joining all devices? 

Kind regards.
Eric

**Comment by Koenkk** [comment]
Yes, see https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices
