### ISSUE TITLE
Migration from CC2531 to CC2652p - issue with pairing old devices 

### ISSUE THREAD

**Issue by izane** [Koenkk/zigbee2mqtt#8345]
Hi all!

I'm fighting with that one month and... needed to created this issue.

## What happened
I have changed my old CC2531 coordinator on CC2652p, performed all needed changes in configuration (changed port and PanID). Zigbee2mqtt addon is starting normally but when I want to pair my devices (for example aqura water leak sensor ) nothing is happening. Previous firmware 20210107 was flashing green light, yesterday I have updated firmware to newest one 20210708 and after that red LED is still on after starting addon. 

In logs one thing is weird - that coordinator after turn on is receiving some MQTT topic so I also tried to take off antenna (I have read somewhere about that) but it's still receiving those MQTT topics. In my zigbee network I have only 3 leak sensors, 4 aquara temp sensors, 2x move sensors and one open door sensor. 
Tried also:
- uninstall and delete everything from zigbee2mqtt directory and installed again
- changed in configuration PanID, channel, network_key, port (from short to full name), rtscts false and true
- flashing stick 
- changing ports where stick in Raspberry Pi4B

Please find logs below with full debug option on:
https://pastebin.com/bp0nmsjP

Below my actual configuration:
https://pastebin.com/VK0Uhw1M

## Debug info
Zigbee2MQTT version:  1.21.0-1
Adapter hardware: CC2652p
Adapter firmware version: CC1352P2_CC2652P_other_coordinator_20210708

**Comment by spetrenko** [comment]
Hi. I have exactly the same issue with same symptoms. The additional info, that I can provide is, that the following device (https://www.zigbee2mqtt.io/devices/GL-C-008S.html) survived migration, but none of mine xiaomi sensors do well (https://www.zigbee2mqtt.io/devices/WSDCGQ12LM.html).
Is there any ETA for this issue? Thanks in advance.

**Comment by izane** [comment]
Still nothing, trying everything during last 3 weeks - and issue is the same... with CC2652p I can't pair devices. When I install old CC2531 I can repair old devices and they are working fine.....
Have last idea - to go out with my RasPi and CC2652p with only one sensor... to avoid getting info about zigbee network from another devices
