### ISSUE TITLE
Aqara DJT11LM - no action value

### ISSUE THREAD

**Issue by cyablo** [Koenkk/zigbee2mqtt#8350]
Hi, I recently got a pair of Aqara DJT11LM vibration sensors to track my garage door and paired them to Z2M Version 1.21.0 .(home assistant addon). The x/y/z angles and strength attributes work nicely, but action doesn't.

It's eiter shown as "null" or "empty_string":

![image](https://user-images.githubusercontent.com/3456720/129231880-c1553ef0-5ffa-4c60-86e9-556e1623d0d6.png)

![image](https://user-images.githubusercontent.com/3456720/129231957-d8095ce6-5d97-413c-b368-ca8964ba3bec.png)

Zigbee debug messages:

> Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":1}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":1}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"1283":7,"85":2}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"1288":[64949,3604566]}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"1285":10878976}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"1288":[1361,3276861]}' from endpoint 1 with groupID 0
Debug Received Zigbee message from 'Garagentor', type 'attributeReport', cluster 'closuresDoorLock', data '{"85":1}' from endpoint 1 with groupID 0

Because every other attribute works, I suspect the problem not to be my setup.

Regards

Daniel

**Comment by danieledwardgeorgehitchcock** [comment]
The action field is momentary meaning that it reports the value when the action happens, then reverts back to the NULL or Empty String.

If you look at your debug logs, when you are tilting or shaking the device, you should see something come through

**Comment by Koenkk** [comment]
@danieledwardgeorgehitchcock is right, this is expected behaviour when the Home assistant integration is enabled. Added this to the FAQ: https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/information/FAQ.md#why-is-the-action-property-always-empty
