### ISSUE TITLE
YSRSAI YSR-MINI-01_rgbcct Failed to setup reporting in logs

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#8352]
Errors in logs when start  Z2M

Zigbee2MQTT version: 1.21.0
Adapter hardware: CC2652RB
Adapter firmware version:  20210708

`Zigbee2MQTT:error 2021-08-12 19:30:39: Failed to setup reporting for '0x00124b0022ed47f2' - Error: ConfigureReporting 0x00124b0022ed47f2/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":300,"reportableChange":0}], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 46828 - 1 - 5 - 6 - 7 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)`

**Comment by Koenkk** [comment]
The report feature is deprecated, see second point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.17.1 on how to migrate.

**Comment by shirou93** [comment]
@Koenkk "The report feature (report: true) is now deprecated. This feature was mostly used for getting state changes of bound devices. With this release Zigbee2MQTT will automatically setup reporting when binding devices" this is not true. Reporting mostly used when example turn bulp directly power on by traditional switch. When i disable report i must config all bulbs report separe?

**Comment by Koenkk** [comment]
>  When i disable report i must config all bulbs report separe (ikea bulbs don't report state when disable report in config)?

Yes you need to configure those separately (can easily be done via the frontend).
