### ISSUE TITLE
Group Home Assistant Auto-discovery Update Home Assistant System ID

### ISSUE THREAD

**Issue by Danit2** [Koenkk/zigbee2mqtt#8358]
## Is your feature request related to a problem? Please describe
The function that groups are automatically displayed in the HA is great.
However, if a group is adjusted, this is not adopted in the HA.

## Describe the solution you'd like
A slider with "Update Home Assistant System ID" would be great, as is the case with the devices.

**Comment by Koenkk** [comment]
> However, if a group is adjusted, this is not adopted in the HA.

What do you mean with "adjusted"?

**Comment by Danit2** [comment]
Sorry i mean „edited“.

**Comment by Koenkk** [comment]
Can you be more concrete here, what do you mean with edit? Add a device, change name?

**Comment by Danit2** [comment]
Ahh, Sorry.

I mean, when i editing a name of a group it don't changes in HA.
Also when i delet a group it don't delet them in HA. 

Nice woud be the same as by the devices. with the slider :"Update Home Assistant System ID"

Sorry for my english.

**Comment by Koenkk** [comment]
Agree, will add this later.
