### ISSUE TITLE
FUT035Z Addition to miboxer.js for cct dimmer [fully working]

### ISSUE THREAD

**Issue by fluffymadness** [Koenkk/zigbee2mqtt#8359]
This is the CCT model of the led controller. This is what I needed to add for the device to work
```
,
{
        fingerprint: [{modelID: 'TS0502B', manufacturerName: '_TZ3210_frm6149r'}],
        model: 'FUT035Z',
        description: 'Dual White LED controller',
        vendor: 'Miboxer',
        extend: extend.light_onoff_brightness_colortemp(),
 }
```

**Comment by fluffymadness** [comment]
right now i'm looking into how I can remove the color temp startup feature since this seems to do nothing

**Comment by danieledwardgeorgehitchcock** [comment]
I think you are looking for the disableColorTempStartup option

**Comment by fluffymadness** [comment]
@danieledwardgeorgehitchcock 
Thanks that did the job, everything is fully working now.

**Comment by danieledwardgeorgehitchcock** [comment]
@fluffymadness do you want me to add this and create a pull request for you?

**Comment by fluffymadness** [comment]
I've already made one, but thx for the offer.
