### ISSUE TITLE
Disable router led

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#836]
Is it possible to disable both the router leds completely on a cc2531?

Would be handy if it could somehow be controlled via the yaml configuration for the router.

**Comment by marcotini** [comment]
Modify your `configuration.yaml` with:

```
serial:
  disable_led: true
  port: /dev/ttyACM0
```

**Comment by danpowell88** [comment]
That is for coordinators only

**Comment by Koenkk** [comment]
AFAIK this is not possible with the router firmware.

**Comment by dmak** [comment]
Just in case somebody finds this issue: `disable_led: true` worked fine for me for CC2531 on firmare [Z-Stack_Home_1.2 Default](https://raw.githubusercontent.com/Koenkk/Z-Stack-firmware/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20190608.zip).

**Comment by emilklindt** [comment]
In case that anyone is here, looking for ways to disable the LED on a CC2531 (with [Z-Stack router firmware for CC2531](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2531)). It can simply be done by powering on the dongle and pressing the S1 button – this is the button not saying debug next to it.

**Comment by barrymossel** [comment]
> In case that anyone is here, looking for ways to disable the LED on a CC2531 (with [Z-Stack router firmware for CC2531](https://github.com/Koenkk/Z-Stack-firmware/tree/master/router/CC2531)). It can simply be done by powering on the dongle and pressing the S1 button – this is the button not saying debug next to it.

Didn't work for me. Heat shrink did work though!

**Comment by JiriFurda** [comment]
`disable_led: true` works but it needs to be added to the zigbee2mqtt addon configuration not the general `configuration.yaml`

**Comment by realjax** [comment]
> `disable_led: true` works but it needs to be added to the zigbee2mqtt addon configuration not the general `configuration.yaml`

What is 'zigbee2mqtt addon configuration', where do I find that ?

**Comment by emkamphuis** [comment]
For the router, pressing S1 button turns green LED on/off, but red LED keeps flashing. Have not found a way to disable flashing light.

**Comment by Sloth-on-meth** [comment]
CC2531 routers still have this problem, any news?

**Comment by 877dev** [comment]
> For the router, pressing S1 button turns green LED on/off, but red LED keeps flashing. Have not found a way to disable flashing light.

This worked for me, thanks.

**Comment by izocor** [comment]
You can disable led in zigbee2mqtt add-on configuration. You need install this add-on and configure before this manipulation.
This configuration file you can find Supervisor->Dashboard->Zigbee2mqtt->Configuration in section 
serial:
  disable_led: true #Just add this line
  port: /dev/ttyACM0
Save config and restart add-on

**Comment by Sloth-on-meth** [comment]
This is for ROUTERS not COORDINATORS

**Comment by cagarrinho** [comment]
disable_led: true
Works for me

**Comment by Sloth-on-meth** [comment]
Again this is for ROUTERS NOT COORDINATORS

**Comment by AbeltjeNL** [comment]
Facing this same question. PTVO.info has the option to make a configurable firmware:

https://ptvo.info/zigbee-switch-configurable-firmware-v2-210/

Option: 'Status LED'.

Didn't try this yet but planning so on doing this week.

**Comment by michaelmcdonald** [comment]
Has there been any progress on this? I find the blinking red LED on my router sticks rather annoying, especially at night. I can use a physical hack to cover it / block it, but would prefer something cleaner.

**Comment by AbeltjeNL** [comment]
> Has there been any progress on this? I find the blinking red LED on my router sticks rather annoying, especially at night. I can use a physical hack to cover it / block it, but would prefer something cleaner.

Yes. I've tried the configurable firmware and yes you can disable the led.

**Comment by michaelmcdonald** [comment]
> > Has there been any progress on this? I find the blinking red LED on my router sticks rather annoying, especially at night. I can use a physical hack to cover it / block it, but would prefer something cleaner.
> 
> Yes. I've tried the configurable firmware and yes you can disable the led.
> You can also change it from the red to the green led, invert it or change the blinking interval in seconds.

Can you share an example?

**Comment by AbeltjeNL** [comment]
@michaelmcdonald and @duceduc,

Sorry. Didn't get a notification for the previous post. What do you want to see? A photo of the CC2531 with the led off or how to use the configurable firmware file?

**Comment by duceduc** [comment]
Hi. Thanks for the reply. I have a CC2531 and have flash with the latest router firmware. I wish to disable the red LED.
 
Yes, how to use the configurable firmware file for the CC2531.

**Comment by duceduc** [comment]
Hi. Thank you very much for the steps. I have saved the custom firmware with the LED box unchecked.
For steps 12 & 13, do we really need to have zigbee2mqtt `permit join` set to true during the flashing?

**Comment by AbeltjeNL** [comment]
> Hi. Thank you very much for the steps. I have saved the custom firmware with the LED box unchecked.
> 
> For steps 12 & 13, do we really need to have zigbee2mqtt `permit join` set to true during the flashing?

Well, no. But the LED is turned off so you couldn't tell when the router is booting, searching for a network or joined a network. To be sure that the router joins your network after flashing, enable permit join. If you don't want to, enable it as soon as the flashing is done.

**Comment by duceduc** [comment]
@AbeltjeNL 
Hello. Well, I successfully paired the router to coordinator during the time of flashing. I had to reset my coordinator and repair all devices including the cc2531 router. Now, I cannot get it to pair. There are 2 buttons on the board. S1 and S2. Does pressing the S2 to start repairing works? I have tried, but it doesn't work.

**Comment by AbeltjeNL** [comment]
@duceduc, Nice to read that you got your router paired again. 

For the description and image part, i already told @ptvoinfo and @Koenkk.

**Comment by AbeltjeNL** [comment]
FYI:

I stopped using these routers. 5 to be exact. My network is much more responsive and quicker. The CC2531 is a bit out of date and the fact that there is still no Zigbee 3.0 firmware out there made me decide to terminate these suckers. 
My network now only communicates with and through 3.0 devices and that is a big jump in performance. 

Not implementing that the Zigbee 1.2 firmware is bad or crap, it just wasn't working very well in my setup 👍🏻
