### ISSUE TITLE
Add Phillips pendant cher 4076131P6

### ISSUE THREAD

**Issue by Pepeuch** [Koenkk/zigbee2mqtt#8367]
Hi, please add my another phillips hue ;-)

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
zigbeeModel: ['4076131P6'],
model: '4076131P6',
vendor: 'Philips',
description: 'Hue white ambiance suspension Cher with bluetooth 3000lm',
fromZigbee: [],
toZigbee: [],
extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
};
module.exports = definition;

{"id":23,"type":"Router","ieeeAddr":"0x001788010987c762","nwkAddr":26127,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"4076131P6","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"4076131P6","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20201012","swBuildId":"1.76.10"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":0,"dateCode":"20201012","swBuildId":"1.76.10","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1628717732929}

![4295FF6E-8AC4-4F9D-825F-9AEF0CA8FFB2](https://user-images.githubusercontent.com/44699883/129440711-05c89a95-0b1a-49b7-9b1b-968e0f211587.jpeg)

Thanks!!!

**Comment by Koenkk** [comment]
Added, thanks!
