### ISSUE TITLE
Enabling home assistant integration breaks zigbee2mqtt wire

### ISSUE THREAD

**Issue by rvalle** [Koenkk/zigbee2mqtt#8378]
## What happened

I have enabled home assistant integration, to enable discovery in OpenHAB. I can see new MQTT messages published under ```homeassistant``` subject tree. However I also noted that native zigbee2mqtt messaging is behaving very differently.

For example, when home assistant integration is disabled, this is what appends if I turn of a switch:

```
z2m/switch2 {"action":"off","battery":87,"click":"off","linkquality":21}
```

If I enable home assistant integration, the same action generates this:

```
z2m/switch2 {"action":"off","battery":87,"click":"off","linkquality":222}
z2m/switch2 {"action":"","battery":87,"linkquality":222}
z2m/switch2 {"action":null,"battery":87,"click":"","linkquality":222}
z2m/switch2/action off
z2m/switch2/click off
```

## What did you expect to happen

New MQTT messages to appear in ```homeassistant``` subjects. Everything else remains the same.

## How to reproduce it (minimal and precise)

turn on home assistant integration

## Debug info
Zigbee2MQTT version
    1.21.0 commit: 70891ee 
Coordinator type
    zStack3x0
Coordinator revision
    20210120
Frontend version
    0.5.18

**Comment by Koenkk** [comment]
This is expected, see https://www.zigbee2mqtt.io/information/FAQ.html#why-is-the-action-property-always-empty
