### ISSUE TITLE
cc2530 normal router output

### ISSUE THREAD

**Issue by danpowell88** [Koenkk/zigbee2mqtt#838]
Im using a cc2530 hooked up to a usb ttl.

Its currently outputting 

> ▒▒▒H▒TexasIstrumens   Sample Light▒▒H▒IEEE: 00124B001BC743BA▒▒H▒IEEE:  00124B001BC743BA▒▒H▒Router: 7C62 Parent: 7469▒▒H▒Router: 762 SW5: Help       ▒▒H▒Router: 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒H▒Match Desc Req Non Matched▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒H▒Match Desc Req Non Matched▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒H▒Match Desc Req Non Matched▒▒H▒Match Desc Req Non Matched▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒!H▒ZR: 1A62 11 7C62 SW5: Help       ▒▒H▒Match Desc Req Non Matched▒▒H▒Match Desc Req Non Matched

@ptvoinfo what does this mean exactly, I assume the 11 is the zigbee channel as my is currently channel 11

The router itself is not showing as paired in zigbee2mqtt and not appearing in the database, it did at one time and i wasnt sure if it was working so deleted it via a mqtt message and then reflashed it.

7C62 and 7469 dont appear to match any device ids on my network that I can tell

**Comment by MiloshCZ** [comment]
Hi, I have same problem. CC2530 flashed with `router-cc2530-std.hex` but router not joining network.
```
Coordinator firmware version: '20190223'
PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'
```
