### ISSUE TITLE
Availability timeout settings defults

### ISSUE THREAD

**Issue by miketm1986** [Koenkk/zigbee2mqtt#8390]
I use 1.21.0.1  version of zigbee2mqtt in HA. I have changed availibility timeout to 60 to check if my devices stay online, but I found that sometimes it goes default, that as you now is 0. Why does it happen? Thank you.

**Comment by miketm1986** [comment]
Any ideas?)

**Comment by Koenkk** [comment]
The current availability feature will be replaced with the new one, I suggest to use that instead: https://github.com/Koenkk/zigbee2mqtt/issues/6281
