### ISSUE TITLE
Attempt 3 pings before marking device as unavailable and 1 when device is already unavailable. #6281 makes the network slow!

### ISSUE THREAD

**Issue by salopette** [Koenkk/zigbee2mqtt#8401]
With the last dev update, the Zigbee network has become slow.
Can that have anything to do with it?

Zigbee2MQTT Version
1.21.0-dev commit: 773de256
Coordinator Typ
zStack3x0
Coordinator Version
20210708
Frontend Version
0.5.25

**Comment by Koenkk** [comment]
No, this functionality is not enabled, see https://github.com/Koenkk/zigbee2mqtt/pull/8243#issuecomment-898898580
