### ISSUE TITLE
YSRSAI YSR-MINI-01_rgbcct color temp range max 370 mireds on HA 500 on web panel z2m

### ISSUE THREAD

**Issue by shirou93** [Koenkk/zigbee2mqtt#8408]
Zigbee2MQTT version: 1.21.0
Adapter hardware: CC2652RB
Adapter firmware version: 20210708

https://www.zigbee2mqtt.io/devices/YSR-MINI-01_rgbcct.html#ysrsai-ysr-mini-01_rgbcct

max on ha:
![image](https://user-images.githubusercontent.com/59237288/129763480-10ecb1c8-b9f5-4959-98e9-429165114dd7.png)

z2m panel:
![image](https://user-images.githubusercontent.com/59237288/129763737-277d0111-6419-459e-8b3a-4a0ad3ad3232.png)

**Comment by Koenkk** [comment]
Could you provide the color temp range? https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html#31-retrieving-color-temperature-range-only-required-for-lights-which-support-color-temperature

**Comment by shirou93** [comment]
` MQTT publish: topic 'zigbee2mqtt/Kuchnia LED', payload '{"brightness":254,"color":{"h":133,"hue":133,"s":100,"saturation":100,"x":0.164,"y":0.588},"color_mode":"xy","color_temp":111,"last_seen":"2021-08-18T19:17:52+02:00","linkquality":78,"state":"OFF"}'

Info Read result of 'lightingColorCtrl': {"colorTempPhysicalMin":160,"colorTempPhysicalMax":370}`

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
