### ISSUE TITLE
Adapter docs mangled

### ISSUE THREAD

**Issue by DubhAd** [Koenkk/zigbee2mqtt#8423]
## What happened

The latest update to the Adapter docs have a formatting issue

## What did you expect to happen

Not be mangled?

## How to reproduce it (minimal and precise)

Look at https://www.zigbee2mqtt.io/information/supported_adapters.html

```
Zigbee2MQTT officially supports the following adapters:

</table> </div> ## Notes Before buying an adapter, please read the notes below! - Recommended adapters are the ones with a **CC2652R**, **CC2652P**, **CC2652RB** or **CC1352P** chip 
```

## Debug info
Zigbee2MQTT version: 1.21.0
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version: all

**Comment by Koenkk** [comment]
Fixed in https://github.com/Koenkk/zigbee2mqtt.io/pull/871
