### ISSUE TITLE
State not updating if made manually turn on/off

### ISSUE THREAD

**Issue by Drealine** [Koenkk/zigbee2mqtt#8429]
## What happened
When I turn on a light or outlet manually (not using HA), the state is not retrieve. I've to force manually to refresh the state directly into the web Z2M interface.

## What did you expect to happen
The state would be updated

## How to reproduce it (minimal and precise)
If I turn on the light from an interuptor, I have to force the status update to know that the light is on.

## Debug info
Zigbee2MQTT version: 1.21.0-4
Adapter hardware: Conbee II
Adapter firmware version: 0x26680700

**Comment by danieledwardgeorgehitchcock** [comment]
This may be the default behaviour of your light. Most devices send their state when they are turned on - Zigbee2MQTT has no way of knowing otherwise what the state is

**Comment by Drealine** [comment]
As discuss on Discord, it is possible to make like this ? : 

![image](https://user-images.githubusercontent.com/61891683/130089869-31e9a361-e136-4b24-a5fb-4e13c3ea4fcb.png)

**Comment by Rira1234** [comment]
I have the same problem with my dimmer switch (Model: Eco-Dim.05) (Zigbee Model: EcoDim-Zigbee 3.0).
 @Drealine: I don't fully understand your comment. Could you elaborate how this would update the state (on/off and dimmer level) of the device?

**Comment by Drealine** [comment]
Yes. You can close.

**Comment by rafareusch** [comment]
> Yes. You can close.
@Drealine 

Do you mind sharing what did you do to solve it? I'm having the same issue.

**Comment by jzielke84** [comment]
How I hate those people like @Drealine ...
