### ISSUE TITLE
Manage Security Keys

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#843]
Hi friends,
I want to manage the security keys in the hub using a trust center on it.
How can I do it?

**Comment by Koenkk** [comment]
See #685

**Comment by msadeghz** [comment]
is it possible to use ZNP firmware which doesn't have security. in fact I want to use "CC2531ZNP-Pro.hex" from "TI ZigBee Home Automation Gateway reference design" but when I flash the ZNP the zigbee2mqtt can't recognize the ZNP. 
I have some end-devices and want to add to the network. the devices are HA1.2 profile Zigbee devices but I don't see anything in zigbee2mqtt.
