### ISSUE TITLE
Xiaomi Smoke Detector  JTYJ-GD-01LM/BB

### ISSUE THREAD

**Issue by saveriospeziali** [Koenkk/zigbee2mqtt#8436]
## Information about the device + link
JTYJ-GD-01LM/BB

Hi Just arrived from Aliexpress an **JTYJ-GD-01LM/BB** instead of JTYJ-GD-01LM/BW

It seem it is the last Xiaomi Version 

I am unable to pair, I suspect it is no ZigBee

Does anyone know this new device?

Regards

**Comment by z-x-f** [comment]
May be bluetooth.
