### ISSUE TITLE
Neo Water Leak Sensor (NAS-WS02)

### ISSUE THREAD

**Issue by jaconejero** [Koenkk/zigbee2mqtt#8450]
Hi all,

I have a water leak sensor, at the box it says NAS-WS02. At blackadder it shows it's supported by zigbee2mqtt but when I tried to add it, it didn't work, so trying to follow the instructions to add support I finally suceeded to get it working, but not sure if I did it right or how to share it with you all.

What I did is to search at Tuya.js in Koenkk/zigbee-herdsman-converters and used it in my own file changing the fingerprint, so I guess it could be just added to tuya.js.

My file (currently working) is:

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_qq9mpfhw'}],
    model: 'TS0601_water_sensor',
    vendor: 'TuYa',
    description: 'Water leak sensor',
    fromZigbee: [fz.tuya_water_leak, fz.ignore_basic_report],
    exposes: [e.water_leak()],
    toZigbee: [],
};

module.exports = definition;

Would this be enough to add support? Should I include anything else?

## Information about the device + link
.. https://zigbee.blakadder.com/Neo_NAS-WS02B0.html

## data/database.db entry of the device
..

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
