### ISSUE TITLE
Ikuu \ Tuya TS0011 - No status update with manual operation

### ISSUE THREAD

**Issue by activex** [Koenkk/zigbee2mqtt#8451]
## What happened
Device: Mercator Ikuu - Single Gang Switch - SSW01 - [Link](https://www.ikuu.com.au/product/single-switch/)

Identified as: Tuya TS0011

- Device added to Z2M
- Can toggle state on the dashboard
- Can operate switch manually

When the switch is operated manually, the status in Z2M is not updated.
The status can be updated when hitting the refresh button under Exposes -> State

## What did you expect to happen

Status in Z2M is updated when switch is operated manually.

## How to reproduce it (minimal and precise)

Remove switch, re-add switch, toggle switch manually, status does not update

## Debug info
Zigbee2MQTT version: 1.18 and updated to 1.21 - same issue
Adapter hardware: Conbee II
Adapter firmware version: ? - not sure how to find this.

Raspberry Pi 4 - Conbee on extension cord
~ 17 other Zigbee Devices
Switch LQI ~120
Z2M -> Homebridge -> HomeKit on Raspberry Pi

**Comment by activex** [comment]
Updated the issue formatting as it was copying all from the discussion.

**Comment by ddemidov** [comment]
Same issue with Lonsonho 1gang switch (qs-zigbee-s05-l) identified as Tuya TS0011 by Z2M. Manual state change is not reflected in Z2M, refresh button under Exposes/State works.
