### ISSUE TITLE
Develco/Frient smoke detector - false (?) battery values?

### ISSUE THREAD

**Issue by rindlerblabla** [Koenkk/zigbee2mqtt#8457]
## What happened
I've got 6 pretty new (like two months old) Frient smoke detectors. Three of them now says "Battery 42%" (not 41, 38 or something else, the rest 100%. It also differs through the day, between 42% and 100%. Seems like there's some issue with the battery reporting?

![battery](https://user-images.githubusercontent.com/28257974/130276208-cc97ec3b-89ab-4fa5-b286-b5a00885c53b.png)

## Debug info
zigbee2mqtt_version 1.21.0-dev commit: f9451ff
coordinator_type zStack3x0 (zzh)
coordinator_revision 20210120

(@theStigh)

**Comment by sjorge** [comment]
I have a few of these and this is ‘normal’ behavior, they don’t support reporting batteryPercentageRemaining, so the battery % is based on voltage.

Which isn’t as accurate, voltage also fluctuates for me based on temperature so battery hops around a lot, usually twice uses day/night.

**Comment by TheStigh** [comment]
@rindlerblabla This is not a Z2M issue, it would be what the device reports.

Are you using a Develco or Frient product, and what is the firmware version? Why do you refer to Develco/Frient?

**Comment by rindlerblabla** [comment]
Okey! Then maybe it is better to "listen" to the binary `battery_low` or is that also based on a calculation on the voltage?

Those devices are SMSZB-120, branded Frient, but that's only the name on the box, it's the same company/products. Don't know what firmware, only the build date (20210531 01:34) is shown in the setting list.

**Comment by sjorge** [comment]
I only added support for the develop air quality sensor, but for that one the technical document mentions the voltage cutoff or use for setting battery_low. Not sure for the other devices but I assume they are similar as all of them only support reporting of batteryVoltage

https://github.com/Koenkk/zigbee-herdsman-converters/blob/ba43a6efd4ef24d35df59d2d8803c7b6b27dd30a/converters/fromZigbee.js#L1563

**Comment by rindlerblabla** [comment]
To me it looks like it's part of the IAS cluster and that the device report battery_low itself when the battery is below 2.8 VDC.

Anyhow, all my devices report `batteryVoltage":29` or `batteryVoltage":30`. 29 is calculated to 42% and 30 to 100%.

`debug 2021-08-21 21:43:59: Received Zigbee message from 'Brandvarnare trapphuset', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryAlarmState":0,"batteryVoltage":29}' from endpoint 35 with groupID 0`

**Comment by sjorge** [comment]
Right the fire/smoke detector uses IAS, the air quality sensor does not, so it’s probably not keyed on batteryVoltage.

~ sjorge

**Comment by rindlerblabla** [comment]
According to the manual, https://www.develcoproducts.com/media/1742/smszb-120-technical-manual-smoke-alarm.pdf

> Note: The attribute “BatteryVoltage” is measuring the battery voltage, in units of 100mV.  

So 29 = 2900 mV (~97% battery, not 42%).

**Comment by sjorge** [comment]
@Koenkk i wonder if I used the wrong battery template then?

**Comment by TheStigh** [comment]
> 
> 
> Okey! Then maybe it is better to "listen" to the binary `battery_low` or is that also based on a calculation on the voltage?
> 
> Those devices are SMSZB-120, branded Frient, but that's only the name on the box, it's the same company/products. Don't know what firmware, only the build date (20210531 01:34) is shown in the setting list.

![image](https://user-images.githubusercontent.com/43895442/130349566-dff914c5-159c-42cc-a00e-903e214b7340.png)

**Comment by rindlerblabla** [comment]
I am on firmware 4.0.2 as well.

**Comment by Koenkk** [comment]
Maybe a different `voltageToPercentage` can be used, e.g. `3V_2500` 

https://github.com/Koenkk/zigbee-herdsman-converters/blob/46cdb1c63dc5b4a317ba84e5c7ec20e8adb2d5bd/devices/develco.js#L148

**Comment by sjorge** [comment]
That definitely seems to give a reading for my Air Quality sensors, they now show closer to what I would expect given the battery age, I also swapped in a near deplete set and it showed < 20% and battery_low=true. I didn't have the correct batteries in a near depleted state to check the smoke and heat detectors.

**Comment by rindlerblabla** [comment]
@sjorge Are your heat and smoke detectors showing 100% or less? Saw that you didn't have any near depleted batteries bug have you tried with ``3V_2500`` for the batteries you already have in place?

**Comment by sjorge** [comment]
The one I have easy access too is at a 100% so it made no difference when testing.

~ sjorge
