### ISSUE TITLE
battery level at null for Moes_ZS-SR4-2169 / TS0044

### ISSUE THREAD

**Issue by kevincaradant** [Koenkk/zigbee2mqtt#8461]
Hi

I bought this remote.
https://zigbee.blakadder.com/Moes_ZS-SR4-2169.html

Everything works well but it's recognized as this one:
https://www.zigbee2mqtt.io/devices/TS0044.html

The issue is just I don't have the battery level ( and the picture is wrong but as it's detected as TS0044, I understand that Z2M displays an other picture than my device).

The main issue is just that I have "NULL" as value

![image](https://user-images.githubusercontent.com/6093175/130316629-748fcd72-db27-4b0d-a60c-bd97d827f14b.png)

How to fix this issue ? What can I do ? 

Thank you 

Regards

**Comment by snp88** [comment]
look similar to my problem 
https://github.com/Koenkk/zigbee2mqtt/issues/8500

**Comment by kevincaradant** [comment]
Hi

Using the question of the #8500 issue. 

this is my database entry:

```
{"id":89,"type":"EndDevice","ieeeAddr":"0x60a423fffea63d99","nwkAddr":59157,"manufId":4098,"manufName":"_TZ3000_abci1hiu","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0044","manufacturerName":"_TZ3000_abci1hiu","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1629819374595}
```

manufacturer: TS3000_abci1hi

**Comment by kevincaradant** [comment]
Hi

I'm still blocked with this issue and I don't know how to help, thank you

Regards

**Comment by kevincaradant** [comment]
Don't close the issue

Thank you

**Comment by MJeka** [comment]
Hi.
I have the same problem. Battery state is null

_TZ3000_ufhtxr59

{"id":56,"type":"EndDevice","ieeeAddr":"0x60a423fffe8affcd","nwkAddr":47829,"manufId":4098,"manufName":"_TZ3000_ufhtxr59","powerSource":"Battery","modelId":"TS0044","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,6],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0044","manufacturerName":"_TZ3000_ufhtxr59","powerSource":3,"zclVersion":3,"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":""}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":0,"inClusterList":[1,6],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":66,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1635887453343}

**Comment by kobuki** [comment]
Same device, same problem here, too.

I tried reconfiguring it, but I only get an error when trying to do so:

```
MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x1234123412341234"},"error":"Device '0x1234123412341234' cannot be configured","status":"error","transaction":"x2oyk-14"}'
```

**Comment by kevincaradant** [comment]
@Koenkk, could you please reopen it?

Do your hunk you can fix it?

Thank you

**Comment by Koenkk** [comment]
@kevincaradant did an attempt to fix it:
- update to the latest dev branch in a few hours from now (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
- Configure device via frontend (press yellow refresh button), right before doing that make sure to wakeup the device by pressing a button on it.

**Comment by kevincaradant** [comment]
Perfect thank you it's fixed

Regards
