### ISSUE TITLE
Adding a new device Aqara QBKG38LM 1 key without zero line.

### ISSUE THREAD

**Issue by dumbodumbos** [Koenkk/zigbee2mqtt#8468]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/8463

<div type='discussions-op-text'>

<sup>Originally posted by **dumbodumbos** August 21, 2021</sup>
Hi. Aqara QBKG39LM, QBKG40LM have been added to the stable version for a long time. And they forgot about QBKG38LM. Please add it to the next release of the stable version. I use docker for this without updating either</div>

**Comment by danieledwardgeorgehitchcock** [comment]
It looks like this has already been added to the codebase and should be available (if not already) in the next stable release. See Koenkk/zigbee2mqtt#7625

**Comment by dumbodumbos** [comment]
OK thanks.  made a convector, everything worked.  but still please remember to add in the next issue.

**Comment by Koenkk** [comment]
Already added indeed, available in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
