### ISSUE TITLE
Failed to start zigbee

### ISSUE THREAD

**Issue by ClewerWild** [Koenkk/zigbee2mqtt#8469]
#Bug Report

What happened
Good afternoon.
After launching the Zigbee2mqtt add-on in the web interface, the inscription (502: Bad Gateway)
Here are the logs: https://pastebin.com/m1PgvUy0
Help me please.

What did you expect to happen
Correct launch zigbee2mqtt

How to reproduce it (minimal and precise)
add-on config: https://pastebin.com/T9VnFpAW

Debug info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: CC2531
Adapter firmware version: I took already stitched by the Chinese

**Comment by lux73** [comment]
Zigbee2MQTT:error 2021-08-21 17:15:40: Error: Error while opening serialport **'Error: Error: No such file or directory, cannot open /dev/ttyACM0'**

your Stick cannot be found by the System...

**Comment by AlexUaDuo** [comment]
> 
> 
> Zigbee2MQTT:error 2021-08-21 17:15:40: Error: Error while opening serialport **'Error: Error: No such file or directory, cannot open /dev/ttyACM0'**
> 
> your Stick cannot be found by the System...

I made some progress, now I know the right port.
Only a new problem has appeared, something has no permissions there. 

Zigbee2MQTT:error 2021-08-22 19:44:55: Error: Error while opening serialport 'Error: Error: Operation not permitted, cannot open /dev/bus/usb/001/003'

**Comment by lux73** [comment]
you must add your User which is running zigbee2mqtt to the "dialout" Group

sudo adduser YOUR_USER dialout

**Comment by AlexUaDuo** [comment]
> 
> 
> you must add your User which is running zigbee2mqtt to the "dialout" Group
> 
> sudo adduser YOUR_USER dialout
> 
> /edit
> 
> btw your USB Path seems weird - please check: https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

![изображение](https://user-images.githubusercontent.com/54753304/130365068-51aab0df-cd01-40e7-9a33-4811b15a29cb.png)
![изображение](https://user-images.githubusercontent.com/54753304/130365075-cf72843a-9cfd-4e59-bde7-70f555f63f48.png)
![изображение](https://user-images.githubusercontent.com/54753304/130365095-23097afa-87a1-48ee-b11e-fc13311decbd.png)
Doesn't work anyway

**Comment by lux73** [comment]
Docker...  havent used Docker before

could imagine that you Pass-Through your USB Device to your Docker Container: https://forums.unraid.net/topic/47595-how-do-i-pass-through-a-usb-device-to-a-docker-container/

if that not Help i dont know, sorry...

**Comment by AlexUaDuo** [comment]
Unfortunately, it didn’t help.
But thanks anyway for the help.
Maybe someone else can help me.
