### ISSUE TITLE
Template variable warning when rendering '{{ value_json.alarm }}'

### ISSUE THREAD

**Issue by jkpe** [Koenkk/zigbee2mqtt#8471]
## What happened
Home Assistant logs the following warning endlessly:
`Template variable warning: 'dict object' has no attribute 'alarm' when rendering '{{ value_json.alarm }}'`

## What did you expect to happen
No warnings

## How to reproduce it (minimal and precise)
I believe the warning is generated as a result of my Develco SMSZB-120 Smoke Alarms having no 'alarm' status by default (there is a question mark in the frontend between OFF and START buttons.

## Debug info
Zigbee2MQTT version: 1.21.0
Adapter hardware: zzh!
Adapter firmware version: zStack3x0 20210120

**Comment by mamrai1** [comment]
Yes it's true.. Also with the develco fire detector HESZB-120 after testing new converter
