### ISSUE TITLE
Détecteur vibration aqara  DJT11LM

### ISSUE THREAD

**Issue by Fafitude** [Koenkk/zigbee2mqtt#8478]
Hello,

since the last update, I have not been able to change the sensitivity of the sensor.
Do you know why ? 

![Zigbee2MQTT - Google Chrome](https://user-images.githubusercontent.com/83011165/130365292-c7f37873-e136-4e1c-8882-3e16f896a7be.jpg)

`error Publish 'set' 'sensitivity' to 'Vibration porte garage 2 (Z2M)' failed: 'Error: Write 0x00158d000577b6f5/1 genBasic({"65293":{"value":21,"type":32}}, {"sendWhenActive":false,"timeout":35000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'`

Thanks in advance.

**Comment by McGiverGim** [comment]
The vibration sensors of Aqara always give me a lot of trouble for this, they go to sleep mode very fast.
I need to press the button of the sensor, and repeat each 3-5 seconds while changing the sensitivity to be sure that the sensor is active.
Did you try pressing the sensor button?

**Comment by coom** [comment]
To change the sensivity you have to push the button on the device after sending the new settings.

**Comment by Fafitude** [comment]
Hello,

Thank you, the probleme is solved.
