### ISSUE TITLE
update.sh get error

### ISSUE THREAD

**Issue by itajackass** [Koenkk/zigbee2mqtt#849]
when I run sudo ./update.sh I get this error message.

```
Stopping zigbee2mqtt...
Creating backup of configuration...
Updating...
Aggiornamento di b0d3c2f..9380bbc
error: Your local changes to the following files would be overwritten by merge:
        .eslintignore
        .github/ISSUE_TEMPLATE.md
        .github/stale.yml
        .travis.yml
        README.md
        docker/Dockerfile.amd64
        docker/Dockerfile.arm32v6
        docker/Dockerfile.arm64v8
        lib/controller.js
        lib/extension/devicePublish.js
        lib/extension/networkMap.js
        lib/extension/routerPollXiaomi.js
        lib/extension/softReset.js
        lib/mqtt.js
        lib/state.js
        lib/util/settings.js
        lib/zigbee.js
        package.json
        test/data.test.js
        test/devicePublish.test.js
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        docgen/docgen.js
        docgen/integrating-with-homeassistant.js
        docgen/supported-devices.js
        docs/_config.yml
        docs/configuration/configuration.md
        docs/configuration/device_specific_configuration.md
        docs/getting_started/flashing_the_cc2531.md
        docs/getting_started/pairing_devices.md
        docs/getting_started/running_zigbee2mqtt.md
        docs/getting_started/what_do_i_need.md
        docs/how_tos/how_to_debug.md
        docs/how_tos/how_to_support_new_devices.md
        docs/how_tos/how_to_support_new_devices_on_hassio.md
        docs/images/cc2530.jpg
        docs/images/cc2530_cc2591.jpg
        docs/images/cc2530_rfx2401.png
        docs/images/cc2531.jpg
        docs/images/cc_debugger.jpg
        docs/images/connected.jpg
        docs/images/devices/22670.jpg
        docs/images/devices/3210-L.jpg
        docs/images/devices/3216331P5.jpg
        docs/images/devices/324131092621.jpg
        docs/images/devices/3261030P7.jpg
        docs/images/devices/3320-L.jpg
        docs/images/devices/3326-L.jpg
        docs/images/devices/4052899926110.jpg
        docs/images/devices/4052899926158.jpg
        docs/images/devices/4058075036147.jpg
        docs/images/devices/4058075036185.jpg
        docs/images/devices/4058075816718.jpg
        docs/images/devices/4058075816794.jpg
        docs/images/devices/421786.jpg
        docs/images/devices/4256251-RZHAC.jpg
        docs/images/devices/433714.jpg
        docs/images/devices/45852GE.jpg
        docs/images/devices/45857GE.jpg
        docs/images/devices/50045.jpg
        docs/images/devices/50049.jpg
        docs/images/devices/53170161.jpg
        docs/images/devices/7146060PH.jpg
        docs/images/devices/7199960PH.jpg
        docs/images/devices/72922-A.jpg
        docs/images/devices/7299355PH.jpg
        docs/images/devices/7299760PH.jpg
        docs/images/devices/73693.jpg
        docs/images/devices/73740.jpg
        docs/images/devices/73742.jpg
        docs/images/devices/74282.jpg
        docs/images/devices/74283.jpg
        docs/images/devices/74696.jpg
        docs/images/devices/8718696449691.jpg
        docs/images/devices/8718696485880.jpg
        docs/images/devices/8718696548738.jpg
        docs/images/devices/8718696598283.jpg
        docs/images/devices/8718696695203.jpg
        docs/images/devices/900008-WW.jpg
        docs/images/devices/915005106701.jpg
        docs/images/devices/915005733701.jpg
        docs/images/devices/9290002579A.jpg
        docs/images/devices/9290011370.jpg
        docs/images/devices/9290012573A.jpg
        docs/images/devices/9290012607.jpg
        docs/images/devices/A6121.jpg
        docs/images/devices/AA68199.jpg
        docs/images/devices/AA69697.jpg
        docs/images/devices/AA70155.jpg
        docs/images/devices/AB3257001NJ.jpg
        docs/images/devices/AB32840.jpg
        docs/images/devices/AB35996.jpg
        docs/images/devices/AB401130055.jpg
        docs/images/devices/AC01353010G.jpg
        docs/images/devices/AC03641.jpg
        docs/images/devices/AC03642.jpg
        docs/images/devices/AC03645.jpg
        docs/images/devices/AC03845.jpg
        docs/images/devices/AC08562.jpg
        docs/images/devices/AV2010-22.jpg
        docs/images/devices/BY-165.jpg
        docs/images/devices/BY-185-C.jpg
        docs/images/devices/CC2530.ROUTER.jpg
        docs/images/devices/DJT11LM.jpg
        docs/images/devices/DL-110-N.jpg
        docs/images/devices/DL-110-W.jpg
        docs/images/devices/DNCKATSW001.jpg
        docs/images/devices/DNCKATSW002.jpg
        docs/images/devices/DNCKATSW003.jpg
        docs/images/devices/DNCKATSW004.jpg
        docs/images/devices/E11-G13.jpg
        docs/images/devices/E11-G23-E11-G33.jpg
        docs/images/devices/E11-N1EA.jpg
        docs/images/devices/E1603.jpg
        docs/images/devices/F7C033.jpg
        docs/images/devices/FB56+ZSW05HG1.2.jpg
        docs/images/devices/GL-C-008.jpg
        docs/images/devices/HALIGHTDIMWWE27.jpg
        docs/images/devices/HS1DS.jpg
        docs/images/devices/HS1SA.jpg
        docs/images/devices/HS1WL.jpg
        docs/images/devices/HS3SA.jpg
        docs/images/devices/ICPSHC24-10EU-IL-1.jpg
        docs/images/devices/ICPSHC24-30EU-IL-1.jpg
        docs/images/devices/ICTC-G-1.jpg
        docs/images/devices/JTQJ-BF-01LM-BW.jpg
        docs/images/devices/JTYJ-GD-01LM-BW.jpg
        docs/images/devices/K2RGBW01.jpg
        docs/images/devices/KS-SM001.jpg
        docs/images/devices/KTBL01LM.jpg
        docs/images/devices/KTBL02LM.jpg
        docs/images/devices/L1527.jpg
        docs/images/devices/L1528.jpg
        docs/images/devices/L1529.jpg
        docs/images/devices/LED1536G5.jpg
        docs/images/devices/LED1537R6.jpg
        docs/images/devices/LED1545G12.jpg
        docs/images/devices/LED1546G12.jpg
        docs/images/devices/LED1622G12.jpg
        docs/images/devices/LED1623G12.jpg
        docs/images/devices/LED1624G9.jpg
        docs/images/devices/LED1649C5.1.jpg
        docs/images/devices/LED1649C5.jpg
        docs/images/devices/LED1650R5.jpg
        docs/images/devices/MCCGQ01LM.jpg
        docs/images/devices/MCCGQ11LM.jpg
        docs/images/devices/MFKZQ01LM.jpg
        docs/images/devices/MG-AUWS01.jpg
        docs/images/devices/Mega23M12.jpg
        docs/images/devices/NL08-0800.jpg
        docs/images/devices/PL-110.jpg
        docs/images/devices/PLUG-EDP-RE-DY.jpg
        docs/images/devices/PSS-23ZBS.jpg
        docs/images/devices/QBCZ11LM.jpg
        docs/images/devices/QBKG03LM.jpg
        docs/images/devices/QBKG04LM.jpg
        docs/images/devices/QBKG11LM.jpg
        docs/images/devices/QBKG12LM.jpg
        docs/images/devices/RB-145.jpg
        docs/images/devices/RB-165.jpg
        docs/images/devices/RB-175-W.jpg
        docs/images/devices/RB-185-C.jpg
        docs/images/devices/RB-248-T.jpg
        docs/images/devices/RB-285-C.jpg
        docs/images/devices/RS-125.jpg
        docs/images/devices/RS-128-T.jpg
        docs/images/devices/RTCGQ01LM.jpg
        docs/images/devices/RTCGQ11LM.jpg
        docs/images/devices/SJCGQ11LM.jpg
        docs/images/devices/SL-110-M.jpg
        docs/images/devices/SL-110-N.jpg
        docs/images/devices/SL-110-W.jpg
        docs/images/devices/SP-120.jpg
        docs/images/devices/ST-110.jpg
        docs/images/devices/STS-PRS-251.jpg
        docs/images/devices/STSS-MULT-001.jpg
        docs/images/devices/UC-110.jpg
        docs/images/devices/WSDCGQ01LM.jpg
        docs/images/devices/WSDCGQ11LM.jpg
        docs/images/devices/WXKG01LM.jpg
        docs/images/devices/WXKG02LM.jpg
        docs/images/devices/WXKG03LM.jpg
        docs/images/devices/WXKG11LM.jpg
        docs/images/devices/WXKG12LM.jpg
        docs/images/devices/Z01-A19NAE26.jpg
        docs/images/devices/Z01-CIA19NAE26.jpg
        docs/images/devices/Z809A.jpg
        docs/images/devices/ZLED-2709.jpg
        docs/images/devices/ZNCZ02LM.jpg
        docs/images/downloader_cable.png
        docs/images/home_assistant_change_name.png
        docs/images/home_assistant_device_registry.png
        docs/images/logo.png
        docs/images/pi.jpg
        docs/images/smartrf.png
        docs/images/xiaomi_sensors.jpg
        docs/index.md
        docs/information/3d_cases.md
        docs/information/alternative_flashing_methods.md
        docs/information/cc_sniffer_devices.md
        docs/information/docker.md
        docs/information/mqtt_topics_and_message_structure.md
        docs/information/supported_devices.md
        docs/information/zigbee_network.md
        docs/integration/home_assistant.md
        images/architecture.png
        images/logo.png
        lib/extension/bridgeConfig.js
        lib/extension/deviceConfigure.js
        lib/extension/deviceReceive.js
        lib/extension/extensionTemplate.js
        lib/extension/homeassistant.js
        lib/extension/markOnlineXiaomi.js
        lib/zapp/cie.js
        test/controller.test.js
        test/deviceReceive.test.js
        test/docgen.test.js
        test/homeassistant.test.js
        test/images.test.js
        test/utils.js
Please move or remove them before you merge.
Aborting
```

**Comment by Koenkk** [comment]
Before https://github.com/Koenkk/zigbee2mqtt/blob/master/update.sh#L10 can you add `git reset --hard HEAD` and try again?

**Comment by itajackass** [comment]
same result: Aborting

New log:

Stopping zigbee2mqtt...
Creating backup of configuration...
Updating...
HEAD ora si trova a b0d3c2f 0.2.0
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 45 (delta 21), reused 43 (delta 19), pack-reused 0
Unpacking objects: 100% (45/45), done.
Da https://github.com/Koenkk/zigbee2mqtt
   dccdc5a..9605e72  dev        -> origin/dev
Aggiornamento di b0d3c2f..9380bbc
error: The following untracked working tree files would be overwritten by merge:
        docgen/docgen.js
        docgen/integrating-with-homeassistant.js
        docgen/supported-devices.js
        docs/_config.yml
        docs/configuration/configuration.md
        docs/configuration/device_specific_configuration.md
        docs/getting_started/flashing_the_cc2531.md
        docs/getting_started/pairing_devices.md
        docs/getting_started/running_zigbee2mqtt.md
        docs/getting_started/what_do_i_need.md
        docs/how_tos/how_to_debug.md
        docs/how_tos/how_to_support_new_devices.md
        docs/how_tos/how_to_support_new_devices_on_hassio.md
        docs/images/cc2530.jpg
        docs/images/cc2530_cc2591.jpg
        docs/images/cc2530_rfx2401.png
        docs/images/cc2531.jpg
        docs/images/cc_debugger.jpg
        docs/images/connected.jpg
        docs/images/devices/22670.jpg
        docs/images/devices/3210-L.jpg
        docs/images/devices/3216331P5.jpg
        docs/images/devices/324131092621.jpg
        docs/images/devices/3261030P7.jpg
        docs/images/devices/3320-L.jpg
        docs/images/devices/3326-L.jpg
        docs/images/devices/4052899926110.jpg
        docs/images/devices/4052899926158.jpg
        docs/images/devices/4058075036147.jpg
        docs/images/devices/4058075036185.jpg
        docs/images/devices/4058075816718.jpg
        docs/images/devices/4058075816794.jpg
        docs/images/devices/421786.jpg
        docs/images/devices/4256251-RZHAC.jpg
        docs/images/devices/433714.jpg
        docs/images/devices/45852GE.jpg
        docs/images/devices/45857GE.jpg
        docs/images/devices/50045.jpg
        docs/images/devices/50049.jpg
        docs/images/devices/53170161.jpg
        docs/images/devices/7146060PH.jpg
        docs/images/devices/7199960PH.jpg
        docs/images/devices/72922-A.jpg
        docs/images/devices/7299355PH.jpg
        docs/images/devices/7299760PH.jpg
        docs/images/devices/73693.jpg
        docs/images/devices/73740.jpg
        docs/images/devices/73742.jpg
        docs/images/devices/74282.jpg
        docs/images/devices/74283.jpg
        docs/images/devices/74696.jpg
        docs/images/devices/8718696449691.jpg
        docs/images/devices/8718696485880.jpg
        docs/images/devices/8718696548738.jpg
        docs/images/devices/8718696598283.jpg
        docs/images/devices/8718696695203.jpg
        docs/images/devices/900008-WW.jpg
        docs/images/devices/915005106701.jpg
        docs/images/devices/915005733701.jpg
        docs/images/devices/9290002579A.jpg
        docs/images/devices/9290011370.jpg
        docs/images/devices/9290012573A.jpg
        docs/images/devices/9290012607.jpg
        docs/images/devices/A6121.jpg
        docs/images/devices/AA68199.jpg
        docs/images/devices/AA69697.jpg
        docs/images/devices/AA70155.jpg
        docs/images/devices/AB3257001NJ.jpg
        docs/images/devices/AB32840.jpg
        docs/images/devices/AB35996.jpg
        docs/images/devices/AB401130055.jpg
        docs/images/devices/AC01353010G.jpg
        docs/images/devices/AC03641.jpg
        docs/images/devices/AC03642.jpg
        docs/images/devices/AC03645.jpg
        docs/images/devices/AC03845.jpg
        docs/images/devices/AC08562.jpg
        docs/images/devices/AV2010-22.jpg
        docs/images/devices/BY-165.jpg
        docs/images/devices/BY-185-C.jpg
        docs/images/devices/CC2530.ROUTER.jpg
        docs/images/devices/DJT11LM.jpg
        docs/images/devices/DL-110-N.jpg
        docs/images/devices/DL-110-W.jpg
        docs/images/devices/DNCKATSW001.jpg
        docs/images/devices/DNCKATSW002.jpg
        docs/images/devices/DNCKATSW003.jpg
        docs/images/devices/DNCKATSW004.jpg
        docs/images/devices/E11-G13.jpg
        docs/images/devices/E11-G23-E11-G33.jpg
        docs/images/devices/E11-N1EA.jpg
        docs/images/devices/E1603.jpg
        docs/images/devices/F7C033.jpg
        docs/images/devices/FB56+ZSW05HG1.2.jpg
        docs/images/devices/GL-C-008.jpg
        docs/images/devices/HALIGHTDIMWWE27.jpg
        docs/images/devices/HS1DS.jpg
        docs/images/devices/HS1SA.jpg
        docs/images/devices/HS1WL.jpg
        docs/images/devices/HS3SA.jpg
        docs/images/devices/ICPSHC24-10EU-IL-1.jpg
        docs/images/devices/ICPSHC24-30EU-IL-1.jpg
        docs/images/devices/ICTC-G-1.jpg
        docs/images/devices/JTQJ-BF-01LM-BW.jpg
        docs/images/devices/JTYJ-GD-01LM-BW.jpg
        docs/images/devices/K2RGBW01.jpg
        docs/images/devices/KS-SM001.jpg
        docs/images/devices/KTBL01LM.jpg
        docs/images/devices/KTBL02LM.jpg
        docs/images/devices/L1527.jpg
        docs/images/devices/L1528.jpg
        docs/images/devices/L1529.jpg
        docs/images/devices/LED1536G5.jpg
        docs/images/devices/LED1537R6.jpg
        docs/images/devices/LED1545G12.jpg
        docs/images/devices/LED1546G12.jpg
        docs/images/devices/LED1622G12.jpg
        docs/images/devices/LED1623G12.jpg
        docs/images/devices/LED1624G9.jpg
        docs/images/devices/LED1649C5.1.jpg
        docs/images/devices/LED1649C5.jpg
        docs/images/devices/LED1650R5.jpg
        docs/images/devices/MCCGQ01LM.jpg
        docs/images/devices/MCCGQ11LM.jpg
        docs/images/devices/MFKZQ01LM.jpg
        docs/images/devices/MG-AUWS01.jpg
        docs/images/devices/Mega23M12.jpg
        docs/images/devices/NL08-0800.jpg
        docs/images/devices/PL-110.jpg
        docs/images/devices/PLUG-EDP-RE-DY.jpg
        docs/images/devices/PSS-23ZBS.jpg
        docs/images/devices/QBCZ11LM.jpg
        docs/images/devices/QBKG03LM.jpg
        docs/images/devices/QBKG04LM.jpg
        docs/images/devices/QBKG11LM.jpg
        docs/images/devices/QBKG12LM.jpg
        docs/images/devices/RB-145.jpg
        docs/images/devices/RB-165.jpg
        docs/images/devices/RB-175-W.jpg
        docs/images/devices/RB-185-C.jpg
        docs/images/devices/RB-248-T.jpg
        docs/images/devices/RB-285-C.jpg
        docs/images/devices/RS-125.jpg
        docs/images/devices/RS-128-T.jpg
        docs/images/devices/RTCGQ01LM.jpg
        docs/images/devices/RTCGQ11LM.jpg
        docs/images/devices/SJCGQ11LM.jpg
        docs/images/devices/SL-110-M.jpg
        docs/images/devices/SL-110-N.jpg
        docs/images/devices/SL-110-W.jpg
        docs/images/devices/SP-120.jpg
        docs/images/devices/ST-110.jpg
        docs/images/devices/STS-PRS-251.jpg
        docs/images/devices/STSS-MULT-001.jpg
        docs/images/devices/UC-110.jpg
        docs/images/devices/WSDCGQ01LM.jpg
        docs/images/devices/WSDCGQ11LM.jpg
        docs/images/devices/WXKG01LM.jpg
        docs/images/devices/WXKG02LM.jpg
        docs/images/devices/WXKG03LM.jpg
        docs/images/devices/WXKG11LM.jpg
        docs/images/devices/WXKG12LM.jpg
        docs/images/devices/Z01-A19NAE26.jpg
        docs/images/devices/Z01-CIA19NAE26.jpg
        docs/images/devices/Z809A.jpg
        docs/images/devices/ZLED-2709.jpg
        docs/images/devices/ZNCZ02LM.jpg
        docs/images/downloader_cable.png
        docs/images/home_assistant_change_name.png
        docs/images/home_assistant_device_registry.png
        docs/images/logo.png
        docs/images/pi.jpg
        docs/images/smartrf.png
        docs/images/xiaomi_sensors.jpg
        docs/index.md
        docs/information/3d_cases.md
        docs/information/alternative_flashing_methods.md
        docs/information/cc_sniffer_devices.md
        docs/information/docker.md
        docs/information/mqtt_topics_and_message_structure.md
        docs/information/supported_devices.md
        docs/information/zigbee_network.md
        docs/integration/home_assistant.md
        images/architecture.png
        images/logo.png
        lib/extension/bridgeConfig.js
        lib/extension/deviceConfigure.js
        lib/extension/deviceReceive.js
        lib/extension/extensionTemplate.js
        lib/extension/homeassistant.js
        lib/extension/markOnlineXiaomi.js
        lib/zapp/cie.js
        test/controller.test.js
        test/deviceReceive.test.js
        test/docgen.test.js
        test/homeassistant.test.js
        test/images.test.js
        test/utils.js
Please move or remove them before you merge.
Aborting

**Comment by Koenkk** [comment]
I would recommend doing a fresh checkout of zigbee2mqtt and copy your `data` directory.
