### ISSUE TITLE
new tuya device

### ISSUE THREAD

**Issue by rbrokken** [Koenkk/zigbee2mqtt#8513]
Hello, 
I am a total noob in this. I have red the section about how to support a new device, but for me thats the same as reading Chinese language (at least that works a kind of in google translate ;) )

But i have a new tuya device: https://www.aliexpress.com/item/1005002716718315.html?pm=a2g0s.9042311.0.0.3d8c4c4dnLiYd0
it is not supported yet, but when i paste this in the tuya.js it works fine:

{
        fingerprint: [{modelID: 'TS000F', manufacturerName: '_TZ3000_m9af2l6g'},
            {modelID: 'TS000F', manufacturerName: '_TZ3000_m9af2l6g'}],
        model: 'TS000F_wall_outlet',
        vendor: 'TuYa',
        description: 'In-wall outlet',
        extend: extend.switch(),
        whiteLabel: [{vendor: 'DIY', model: 'WHD02'}],
    },

Is it possible to get this standard in the tuya.js so i don't have to edit this file after every update?

Hopefully it is
Greetings Rob

**Comment by Koenkk** [comment]
Added, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
