### ISSUE TITLE
Moes BRT-100-TRV not reporting valve positon

### ISSUE THREAD

**Issue by wizu** [Koenkk/zigbee2mqtt#8533]
I've installed a few Moes BRT-100-TRV thermostatic valves and have problems with them.

## What happened
Valve don't report valve position, It's get stuck and won't change even when i can see that, valve is moving. I'm changing set temperature and reported valve position stays the same, even after an hour.

## What did you expect to happen
I would like to use valve position to control my boiler, but it's value doesn't change.

## How to reproduce it (minimal and precise)

Change set temperature bolow or above local temerature and position don't change.

## Debug info
Zigbee2MQTT version: 1.21.0 commit: 70891ee
Adapter hardware: CC2538
Adapter firmware version: 20200211

**Comment by vladi1234** [comment]
@wizu This is not the fault of a Z2M integration. This is how TVR works, is how it was designed, I think this, it looks like it has something to do with the Stand-by function.
This cannot be changed.
Maybe at some point we will get an official update from the manufacturer with an improved Vintilposition function.

**Comment by wizu** [comment]
@vladi1234 That's what I was afraid of. I've already ordered 10pcs of https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html and will have to sell BRT-100TRV.
Thanks for info.

**Comment by TheDukeSr** [comment]
Just a tip.
When changing setting "AD" - "Standby screen Brightness" > 0

pro: _Display stays on and Valve reporting works all the time._
con: _I don't know (yet) how much extra battery this will drain._

**Comment by moskovskiy82** [comment]
> @vladi1234 That's what I was afraid of. I've already ordered 10pcs of https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html and will have to sell BRT-100TRV. Thanks for info.

The ones you have ordered have a hardware flow. Lid breaks over time

**Comment by killkenny** [comment]
Hi all,
I would like to know if there is any update to solve the issue related the the valve position (original issue in this ticket). I have also few BRT-100-TRV and I'm facing to this problem. The valve position is only reported when the screen is active.
I tested also changing the standby screen but no difference, with values 0 or 9 it will switch off after few second (change to inactive).
Looking for information but no good news, so I'm asking here as this looks to be the original issue reported.
Maybe a firmware update should fix it and we need to wait MOES to release it....
thank you!
