### ISSUE TITLE
[FUT105Z] Miboxer FUT105Z RGB+CCT Bulb, working but brightness slider bug

### ISSUE THREAD

**Issue by fluffymadness** [Koenkk/zigbee2mqtt#8599]
Bought the following bulb
https://www.futlight.com/light/xqy/fut105z.html
It is working with some small issues

```
{
        fingerprint: [{modelID: 'TS0505B', manufacturerName: '_TZ3210_wslkvrau'}],
        model: 'FUT105Z',
        description: '12W RGB+CCT LED Bulb',
        vendor: 'Miboxer',
        extend: extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),
 },
```
**Bugs:**

- Setting Colors: Via homeassistant red is red, via webinterface red is pink (webinterface bug??=
CCT Brightness:  Brightness slider stops at 127, each further increment changes nothing, when changing to rgb color mode however slider works correctly from 0-254

- Bulb reports the wrong color temperature. Its reported range is [153,500] However in real life it stops at [153,370].
This results in color issues in home assistant when trying to set the target color temperature.
However changing the colorTempRange in the converter to [153,370] will just clamp the value and it won't be able to reach 2700k anymore.

**Comment by fluffymadness** [comment]
Brightness controls for color have the correct range from 0-254
only cct range seems to be halved.
However color mode only has half he brightness.
 It seems this device needs some extra work

I tried to add the following 
```
fromZigbee: [
        fz.ignore_basic_report, // Add this if you are getting no converter for 'genBasic'
        fz.tuya_data_point_dump, // This is a debug converter, it will be described in the next part
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
```
in the hope to get some debug files. (Using zigbee2mqtt via homeassistant)
I connected to the docker container,but there is nothing in /data/
accessing the zigbee2mqtt directory via samba share. Also no  log files :(
Does anyone know where to find the logs.

**Comment by fluffymadness** [comment]
Ok, color controls via homeassistant work fine, however are broken via webinterface.
If i set red via color xy in zigbee2mqtt interface it is pink, with homeassistant however it works fine

**Comment by fluffymadness** [comment]
unstale

**Comment by Koenkk** [comment]
I see, but that is not something we can be fixed in z2m (should be fixed by the manufacturer)
