### ISSUE TITLE
spaces in friendly names

### ISSUE THREAD

**Issue by wtabingh** [Koenkk/zigbee2mqtt#86]
if a friendly name contains spaces, it possible to read from a sensor device. However if the device is an actuation device, the message is not accepted. I found this while controlling my Tradfree light. removing the space in the friendly name solves the issue. However this is not a symmetrical solution. We should either never accept spaces or accept them for both types of devices.

**Comment by Koenkk** [comment]
Thanks! Spaces are now accepted in MQTT device commands.
