### ISSUE TITLE
NPM ENOENT

### ISSUE THREAD

**Issue by nmeen** [Koenkk/zigbee2mqtt#862]
Hello,

I have a raspberry pi,

When i run npm install, i get this: "npm WARN tar ENOENT: no such file or directory, open '/opt/zigbee2mqtt/node_modules/.staging/zcl-id-67ebab72/test/argumentType.test.js'

Can someone help me.

**Comment by Koenkk** [comment]
Can you provide the complete log?

**Comment by Koenkk** [comment]
@nmeen are you using a non-release version of npm? `2 info using npm@6.6.0-next.1` ?

**Comment by nmeen** [comment]
I have bought a new raspberry pi, (version 3 instead of 1) and now its working.
