### ISSUE TITLE
Documentation contains outdated references to CC2531 adapter

### ISSUE THREAD

**Issue by TobiasBg** [Koenkk/zigbee2mqtt#8626]
(I'm reporting this here as Koenkk/zigbee2mqtt.io has Issues turned off.)

The documentation contains a number of outdated references to the CC2531 adapter in the pairing instructions for some devices - probably from the times back when the CC2531 adapter was the only available adapter.
See e.g. https://github.com/Koenkk/zigbee2mqtt.io/search?q=close+to+the+CC2531+USB+sniffer

I suggest to replace these references with a more general sentence like
"While pairing, keep the bulb close to the USB adapter (coordinator)."

**Comment by Koenkk** [comment]
Fixed! thanks for reporting.
