### ISSUE TITLE
Home Assistant HassOS 6.3 issues

### ISSUE THREAD

**Issue by ahmaddxb** [Koenkk/zigbee2mqtt#8647]
After updating Home Assistant OS to v6.3 Xiaomi zigbee devices take so long to respond e.g (button). Ikea buttons still respond quick.

After restoring my virtual machine from backup to where Home Assistant OS is v6.2 Xiaomi devices respond quick.

Current working state
Zigbee2mqtt 1.21.0-dev commit: a380df4
HA Core 2021.9.3
HA Supervisor 2021.09.0
Home Assistant OS 6.2

Coordinator CC2652R zzh
Coordinator type zStack3x0
Coordinator revision 20210708

**Comment by bossgos** [comment]
Same here  :(

**Comment by Koenkk** [comment]
Same as #8623
