### ISSUE TITLE
Please add this device : NodOn SIN-4-2-20

### ISSUE THREAD

**Issue by XLDom** [Koenkk/zigbee2mqtt#8689]
Hello,

Can you integrate this device please. Thanks :-)

## Information about the device + link
2 Relays Light switch 2 x 690W
https://nodon.fr/nodon/module-eclairage-on-off-zigbee/
![image](https://user-images.githubusercontent.com/90308906/132464410-9f939cdd-3700-4e52-957c-3ef9019214b7.png)

## data/database.db entry of the device
`{"id":2,"type":"Router","ieeeAddr":"0x5c0272fffe7d3675","nwkAddr":12021,"manufId":4747,"manufName":"NodOn","powerSource":"Mains (single phase)","modelId":"SIN-4-2-20","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,7,8,4096,64599],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"SIN-4-2-20","manufacturerName":"NodOn","powerSource":1,"zclVersion":3,"appVersion":17,"stackVersion":103,"hwVersion":0,"dateCode":"2020"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022982996","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6,7,8],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0022982996","endpointID":1}],"configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":17,"stackVersion":103,"hwVersion":0,"dateCode":"2020","zclVersion":3,"interviewCompleted":true,"meta":{"configured":1620506091},"lastSeen":1631045670295}`

**Comment by sjorge** [comment]
```node
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        zigbeeModel: ['SIN-4-2-20'],
        model: 'SIN-4-2-20',
        vendor: 'NodOn',
        description: 'Double LED Relay',
        exposes: [
            e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'),
        ],
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const ep1 = device.getEndpoint(1);
            const ep2 = device.getEndpoint(2);
            await reporting.bind(ep1, coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(ep2, coordinatorEndpoint, ['genOnOff']);
        },
};

module.exports = definition;

```

Try with this, see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to use the file.

**Comment by XLDom** [comment]
> Try with this, see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to use the file.
Yes, it's ok. Thanks !

Do you know how to do to import options like "On with timed off" ?
This module have many options

**Comment by sjorge** [comment]
> > Try with this, see https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html on how to use the file.
> > Yes, it's ok. Thanks !
> 
> Do you know how to do to import options like "On with timed off" ?
> This module have many options
If the device supports it, it should already working https://github.com/Koenkk/zigbee-herdsman-converters/blob/715b05f2dfcc25c6d94308780fd88155906562ad/converters/toZigbee.js#L258

Well assuming that the definition I posted earlier today works.

**Comment by XLDom** [comment]
Ho other thing, the definition work on direction z2m -> switch : z2m can change the state of the two switch.
but not on direction switch -> z2m : 
When i activate the relay with S1 input. The state is not update on z2m.
Do you know why ?

**Comment by sjorge** [comment]
Try with this one instead
```node
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const definition = {
        zigbeeModel: ['SIN-4-2-20'],
        model: 'SIN-4-2-20',
        vendor: 'NodOn',
        description: 'Double LED Relay',
        exposes: [
            e.switch().withEndpoint('l1'), e.switch().withEndpoint('l2'),
        ],
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        endpoint: (device) => {
            return {'l1': 1, 'l2': 2};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const ep1 = device.getEndpoint(1);
            const ep2 = device.getEndpoint(2);
            await reporting.bind(ep1, coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(ep2, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(ep1);
            await reporting.onOff(ep2);
        },
};

module.exports = definition;
```

**Comment by XLDom** [comment]
don't work to.
If i click on refresh : 
![image](https://user-images.githubusercontent.com/90308906/132580321-7e40ef1e-ca4a-4113-aed6-20c634820904.png)
The state is updated on z2m.

Other think, there is no log entry on z2m (debug mode) when i push, or release my button on S1.

**Comment by sjorge** [comment]
Did you hit the reconfigure button for the device after updating the file?

Can you also grab a screenshot of the cluster tab in the frontend.

**Comment by XLDom** [comment]
ok, i've try to reconfigure : same.
I've try to reset the node, and do a new join : 
Error Failed to configure '0x5c0272fffe7d3675', attempt 1 (Error: Bind 0x5c0272fffe7d3675/1 genOnOff from '0x00124b0022982996/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))

Here is the cluster tab : 
![image](https://user-images.githubusercontent.com/90308906/132582621-2f86e060-457a-4166-a4f4-555bdd72f015.png)
![image](https://user-images.githubusercontent.com/90308906/132582647-dcc208f1-2b5d-4a16-952b-068533d70410.png)
![image](https://user-images.githubusercontent.com/90308906/132582686-9e206e63-e337-4d2d-ae4f-f293e5b371cc.png)

**Comment by sjorge** [comment]
There doesn't seem to be any output cluster on ep1 and ep2 aside from genIdentity so I don't think we can get 'actions' for when the buttons are pressed.

Odd that it's throwing timeouts, what if you add the reporting for onOff manually using the reporting tab?

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/379665/132635636-6dee2974-0fd4-4cf3-b215-e3316c603731.png">

**Comment by Nivek-domotic** [comment]
Hi sjorge, i read something in the user manual of this device

----------------------------------------------------------------
3.2.5. On/Off
The Device supports the On/Off Cluster:
- As Server to allow the control of the Output 1 through these commands:
o Off
o On
o Toggle
o Off with effect
o On with recall global scene
o On with timed off

...
-------------------------------------------------------------
I'm all right with this on/off/toogle, but it's the first time i seen the other option


So how can we use the other options?

**Comment by sjorge** [comment]
By sending the extra property in the payload as mentioned https://github.com/Koenkk/zigbee2mqtt/issues/8689#issuecomment-915510685

**Comment by sjorge** [comment]
```bash
mosquitto_pub -t zigbee2mqtt/0x0123456789/set -m '{"state": "ON", "on_time": 60}'
```

Should turn it on for 1 minute

**Comment by XLDom** [comment]
> ```shell
> mosquitto_pub -t zigbee2mqtt/0x0123456789/set -m '{"state": "ON", "on_time": 60}'
> ```
Hello,

ok this is working. The relay stay ON and go to OFF after the on_time.

I don't understand why there is no report on direction node -> z2m.
I've change max rep on 900. (i don't know what it's for) : no change for report :)

**Comment by sjorge** [comment]
It could be the device doesn’t support reporting.

~ sjorge

**Comment by XLDom** [comment]
Hello,
we have test with the node model SIN-4-1-20 and there is the reporting when we activate the S button....
Probable a firmware problem on my node (i will to test).

For information, i've test the SIN-4-1-20 (1 relay node) with this (and it's ok): 
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;

const definition = {
        zigbeeModel: ['SIN-4-1-20'],
        model: 'SIN-4-1-20',
        vendor: 'NodOn',
        description: 'Simple LED Relay',
        exposes: [
            e.switch().withEndpoint('l1'),
        ],
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        endpoint: (device) => {
            return {'l1': 1};
        },
        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const ep = device.getEndpoint(1);
            await reporting.bind(ep, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(ep);
        },
};

module.exports = definition;
```

Do you see something to change on the definition file ?

How to do a request now ? to improve the 2 nodes definition on z2m ? please

**Comment by XLDom** [comment]
Other question : and how to give the OTA firmware update files to z2m ?
thanks

**Comment by sjorge** [comment]
>Other question : and how to give the OTA firmware update files to z2m ?
thanks

If you have the firmware files, they need to be added here https://github.com/Koenkk/zigbee-OTA

> we have test with the node model SIN-4-1-20 and there is the reporting when we activate the S button....
> Probably a firmware problem on my node (i will to test to upgrade him this week-end).

Good news! I'll try and get a PR open then against zhc to add support, hopefully you can sort the non responding one.

**Comment by XLDom** [comment]
Hello, sorry for that, but since last upgrade, the NodOn is unsupported, and detected like that : 
![image](https://user-images.githubusercontent.com/90308906/133942660-fec54b44-640b-4849-b647-595620c379f2.png)

In database, i've got : 
`{"id":2,"type":"Router","ieeeAddr":"0x5c0272fffe7d3675","nwkAddr":51949,"manufId":4747,"manufName":"NodOn","powerSource":"Mains (single phase)","modelId":"SIN-4-RS-20\u0000\u0000\u0000\u0000\u0014\u0000\u0000\u0000ï¿½ï¿½\u0000 9\u0002\u0001\u0000ï¿½\u0000\u0000\u0000ï¿½","epList":[1,2,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,4,5,6,7,8,4096,64599],"outClusterList":[3,6,25],"clusters":{"genBasic":{"attributes":{"modelId":"SIN-4-RS-20\u0000\u0000\u0000\u0000\u0014\u0000\u0000\u0000ï¿½ï¿½\u0000 9\u0002\u0001\u0000ï¿½\u0000\u0000\u0000ï¿½","manufacturerName":"NodOn","powerSource":1,"zclVersion":3,"appVersion":35,"stackVersion":103,"hwVersion":0,"dateCode":"2020"}}},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":256,"inClusterList":[0,3,4,5,6,7,8],"outClusterList":[3,6],"clusters":{"genBasic":{"attributes":{"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":35,"stackVersion":103,"hwVersion":0,"dateCode":"2020","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1632084060087}`

do you have any idea what the problem is ?

**Comment by sjorge** [comment]
You’re running on the dev branch? It hasn’t made it into a release yet.

**Comment by XLDom** [comment]
> You’re running on the dev branch? It hasn’t made it into a release yet.

yes in dev branch.
My problem is the appearance of these characters:
before : "modelId":"SIN-4-RS-20"
after upgrade of NodOn firmware (or z2m ? i don't know) : `"modelId":"SIN-4-RS-20\u0000\u0000\u0000\u0000\u0014\u0000\u0000\u0000ï¿½ï¿½\u0000 9\u0002\u0001\u0000ï¿½\u0000\u0000\u0000ï¿½"`

**Comment by sjorge** [comment]
Hmmm yeah that not going to March the device code then. How did you update the firmware? Seems like there is some random data behind the model now.

**Comment by XLDom** [comment]
Last firmware and is push with android EFR with bluetooth.
You confirm to me that this data comes from the equipment (the node) and not from zigbee2mqtt? (if is the case, i will ask to NodOn)

**Comment by sjorge** [comment]
The data is send (well, actually read) during interview from the genBasic cluster so z2m can identify it.

**Comment by XLDom** [comment]
> You can also read it via the dev console, e.g. for a random ikea bulb I have: `Read result of 'genBasic': {"modelId":"TRADFRI bulb GU10 WS 400lm","manufacturerName":"IKEA of Sweden"}`

yes, i've try
but the answer is : 
![image](https://user-images.githubusercontent.com/90308906/133944019-e26f0d78-bf5a-4f7f-b412-6af6caafd3f0.png)

(lol)

i will ask to NodOn if they have an idea

**Comment by sjorge** [comment]
@Koenkk can we allow the raw read converters for unsupported devices?

**Comment by XLDom** [comment]
Hello,

the NodOn Developper don't find solution for the `\u0000` caracters after the modelId.

Into zigbee2mqtt, can you do to stop the modelId before the first `\u0000` find ?

i that can help, on the legrand.js there is similar witout random : 
```
module.exports = [
    {
        zigbeeModel: [' Contactor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'+
            '\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'],
        model: 'FC80CC',
```

**Comment by XLDom** [comment]
Hello @Koenkk

i've try, i'm on last dev, and the result is : 
![image](https://user-images.githubusercontent.com/90308906/137017623-ab653a39-c4f1-4739-bcee-b8e85a85c8b5.png)

**Comment by mrgreenfr** [comment]
> Is this the roller shutter module? Your device has modelId `SIN-4-RS-20` which matches with https://shop.smarthome-europe.com/en/peripheriques/4923-nodon-zigbee-30-roller-shutter-module-3700313925201.html

God... my bad. The roller shutter module is not in the definitions files.
Yes it is. Can you add him into the converter please ?
Construtor link : https://nodon.fr/nodon/module-volet-roulant-zigbee/
Image link : https://nodon.fr/wp-content/uploads/2021/04/SIN-4-RS-20_ISO-600x600.jpg

Thanks

**Comment by titou4307** [comment]
Hi...
Is the firmware of the Nodon products can be updated by the zigbee2mqtt network ??

Best regard

**Comment by furieuxjk** [comment]
@XLDom - did you managed to get SIN-4-1-20 device reporting the state if changed by external switch (without refreshing Z2M exposes page)?

Another way how to manually refresh is by just sending json payload {"state": ""} to the MQTT topic zigbee2mqtt/FRIENDLY_NAME/get - then topic "state" is updated.

Regards
