### ISSUE TITLE
zigbee2mqtt freezes from time to time

### ISSUE THREAD

**Issue by kalatos86** [Koenkk/zigbee2mqtt#8690]
Hi there!

Since the last update of the HA OS, Ha Core and zigbee2mqtt I am struggling with the issue of stability. I mean that from time to time (randomly) it seems for some reasons I am not able to control the devices. After some period of time everything back to the normal and stable work.

Here is the set of the versions I am currently using:

- Zigbee2mqtt Current version: 1.21.1-1 (Changelog)
- HA  core-2021.9.4 
- HA supervisor-2021.09.0
- Home Assistant OS 6.3
- Conbee II with the newest firmware (August 2021)

I have a lot of such logs as shared below consist of all the devices I am trying to call:

_Zigbee2MQTT:error 2021-09-08 09:16:27: Publish 'set' 'state' to 'WLWentylacjaWCDol' failed: 'Error: Command 0x84fd27fffe80c42d/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'_

What is also new here and might be useful is that. Since I upgraded the HA to the one of the latest version is the new integration visible with Conbee II 

![image](https://user-images.githubusercontent.com/75856476/132473978-556d1def-914e-4ddd-8d93-f944ce889158.png)

After trying to configure it:

![image](https://user-images.githubusercontent.com/75856476/132474428-bccd9862-84db-4721-bde6-a0b3c751777f.png)

![image](https://user-images.githubusercontent.com/75856476/132474571-c5526908-66a8-4672-9b53-aef380eb44b6.png)

**Comment by sjorge** [comment]
If you want to use zigbee2mqtt you definitely want to hit ignore on the 'Zigbee Home Automation' that is the ha's native zigbee integration, which will then grab the USB device before zigbee2mqtt can. Or if zigbee2mqtt already is running zha will fail to grab it.

It shows up due to the recent added USB discovery.

**Comment by kalatos86** [comment]
I did exactly as you wrote. I mentioned about it because I through i might influence stable way of working of zigbee devices. Even though I did ignore on  'Zigbee Home Automation' from time to time I am struggling with stability of zigbee2mqtt. Do you have idea why?

**Comment by Koenkk** [comment]
I don't know what usb-to-serial chip the Conbee II uses, but hassos 6.3 is affected by https://github.com/Koenkk/zigbee2mqtt/issues/8663, I would suggest to first update to hassos 6.4 or downgrade to 6.2

**Comment by kalatos86** [comment]
Thank you so mych for info. For me the hasos is not yet available:

![obraz](https://user-images.githubusercontent.com/75856476/132517555-e765e0d7-26aa-433c-b792-32edb3b9f3f9.png)

**Comment by dekamilv** [comment]
> I don't know what usb-to-serial chip the Conbee II uses, but hassos 6.3 is affected by #8663, I would suggest to first update to hassos 6.4 or downgrade to 6.2

On 6.4 same problems with freezes .... Thinking to downgrade to 6.2.
