### ISSUE TITLE
Extend Configuration for MQTT

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#87]
It should be possible to define own mqtt Server Port because sometimes the Broker listen on another port like the default one.

**Comment by ciotlosm** [comment]
@tb-killa this is already possible, just include the port in your setup:

mqtt://host:port

**Comment by tb-killa** [comment]
Okay, thanks for that information.
should be mentioned inside the wiki documentation.

**Comment by Koenkk** [comment]
Updated: https://github.com/Koenkk/zigbee2mqtt/wiki/Configuration
