### ISSUE TITLE
Add BlitzWolf BW-SHP15 / Tuya XH-002P

### ISSUE THREAD

**Issue by Malz1902** [Koenkk/zigbee2mqtt#8706]
Add the tuya 16A EU Smartplug 
Model XH-002P

https://a.aliexpress.com/_m0AQAcb

**Comment by HollyFredD** [comment]
Same here :-)
+1

**Comment by HollyFredD** [comment]
Looks like it's fixed after upgrading in 1.21.1
From my perspective this issue can be closed
