### ISSUE TITLE
OTA for Danfoss Ally doesn't find newest version

### ISSUE THREAD

**Issue by frauhottelmann** [Koenkk/zigbee2mqtt#8707]
Hey, I have a couple of Danfoss Ally. The one I got first was updated by z2m to firmware date 20200721 and firmware version 01.02.0008 01.02.
And the new one got delivered with firmware date 20210316 and firmware version 01.08.0008 01.08.
The 01.08 version is on their website at https://files.danfoss.com/download/Heating/Ally/Ally%20eTRV%201.08%20OTA%20file.zip. The same version appears to be at https://github.com/Koenkk/zigbee-OTA/tree/master/images/Danfoss.

When I check the OTA for the old one z2m doesn't find the new one.

## Debug info
Zigbee2MQTT version: 1.21.1-1 (Home Assistant Supervised)
Adapter hardware: Slaesh's CC2652RB stick
Adapter firmware version: zStack3x0 20200715

``
Check if update available for '0x842e14fffe293880' (eTRV0100)
Debug Using endpoint '1'
Debug Received Zigbee message from 'Heizung Wohnzimmer', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":264,"imageType":256,"manufacturerCode":4678}' from endpoint 1 with groupID 0
Debug Got OTA request '{"fieldControl":0,"manufacturerCode":4678,"imageType":256,"fileVersion":264}'
Debug Device 'Heizung Wohnzimmer' requested OTA
Debug Is new image available for '0x842e14fffe293880', current '{"fieldControl":0,"manufacturerCode":4678,"imageType":256,"fileVersion":264}', latest meta '{"fileVersion":264,"fileSize":501899,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Danfoss/1246-0100-01080108.0002_%28DF4ECCE1%29.ota","sha512":"8640b203d1925f527f1b212547d649212ddb9ca534e96b9296d192356ab4893c36daf65bf0a0780f003c5152d44db3643d79d34e10d96480c090ea8146493495"}'
Debug Update available for '0x842e14fffe293880': NO
``

**Comment by WouterKr** [comment]
Hi, the Danfoss Ally I am using does not update by OTA either.
Hope this will and can be solved.

**Comment by frauhottelmann** [comment]
I was able to update to the new firmware.
