### ISSUE TITLE
Legrand 067771 setting min\max brightness

### ISSUE THREAD

**Issue by airens** [Koenkk/zigbee2mqtt#8708]
In original app there are options for setting minimal and maximal brightness which, sometimes, is really needed, but Z2M doesn't seem to support it. Tell me, please, how can I add support for these options? What clusters to look for?

**Comment by danieledwardgeorgehitchcock** [comment]
You would probably need to sniff the Zigbee traffic when the device is joined to its native hub and the setting is applied to find out how that works.

Once you have this, it should be able to be added to the device handler

**Comment by airens** [comment]
Added support in [this](https://github.com/Koenkk/zigbee-herdsman-converters/pull/3021) pull request
