### ISSUE TITLE
ota support for HESZB-120 (similar to SMSZB-120)

### ISSUE THREAD

**Issue by HerrieMan72** [Koenkk/zigbee2mqtt#8718]
The HESZB-120 is supported ok in zigbee2mqtt, but the ota function is missing.
My guess is this should be similar to the other Develco/Frient devices, e.g. the SMSZB-120 does have ota support.
Can this be added to zigbee2mqtt ?

**Comment by Koenkk** [comment]
In order for support this, you should retrieve the OTA image (contact manufacturer/reverse engineer from gateway) and add it here: https://github.com/koenkk/zigbee-ota
