### ISSUE TITLE
 Develco IO Module IOMZB-110

### ISSUE THREAD

**Issue by gf-a** [Koenkk/zigbee2mqtt#8733]
Hi

Can someone please look into adding support for  Develco IO Module IOMZB-110.
I see that there is several other devices from Develco that is supported.

I use the device for opening my garage doors, 2 NC/NO relay contact connected to the  potential free contacts om my garage door motors.
The device also support input from up to 4 external devices with NC/NO contacts.

https://www.develcoproducts.com/products/smart-relays/io-module/

**Comment by rindlerblabla** [comment]
Not to be rude, but did you try pairing it with z2m? Guess it is easier to get help with adding it if you post the database entry.

> VERY IMPORTANT: Before submitting a request, first (try to) follow: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Dumping just the info about this device without actually attemping adding support yourself will likely lead into this issue being ignored.
Clearly indicate what you tried and where you got stuck.
