### ISSUE TITLE
"device_interview" skipped/missing after joining device to zigbee2mqtt

### ISSUE THREAD

**Issue by archerixx** [Koenkk/zigbee2mqtt#8755]
Hi all,

I started experiencing issues with "device_interview" stage on Zigbee2mqtt. Among logs, only thing that comes up after adding device is "device_joined" and "device_anounce", after which device starts to act normally. 

Since I created system on which I recognise devices added by "successful" interview stage, this causes me some issues.
I had to make workaround with "device_joined" for now, but unfortunately that step sometimes does not add device completely.

Link to "Debug log":
https://hastebin.com/idinurasuk.apache

Bug report?
This started happening after updating to latest Zigbee2mqtt version.
To reproduce, add device for first time. Remove it. Then add it again. After that, it will skip "device_interview" stage.

Keep in mind, this does not happen to all devices and it sometimes works. But currently, it is happening most of time.

I tried search for similar issues, but could not find any at the moment.

## Debug info
Zigbee2MQTT version: 1.21.1
Adapter hardware:  RaspBee II

**Comment by RobLeighton67** [comment]
Had the same problem with a Develco Smart Plug Mini on updating to 1.21.1 - I also built my application to support interview status handling.

Pi Zero W - CC2531 (ext antenna)
