### ISSUE TITLE
Adding Ikea Tradfri Control Outlet (E1603) to Domoticz

### ISSUE THREAD

**Issue by Dunkie66** [Koenkk/zigbee2mqtt#8760]
Hi all,

I'am running the latest version of zigbee2mqtt v1.21.1.
My 4 x Aquara door sensor are visible under Custom tab AND under Devices, so they are working fine.
I also have connected 3 x Ikea Tradfri Control Outlets (E1603), but they are only visible under Custom tab and NOT under Devices. So I can not use them.

How can I get those outlets also visible under Devices?

Regards,

Erik

**Comment by Koenkk** [comment]
Issues related to the domitcz plugin should be created here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues
