### ISSUE TITLE
Battery status unknown for Aqara Curtains motor B1

### ISSUE THREAD

**Issue by rusjoan** [Koenkk/zigbee2mqtt#8763]
# Bug Report
## What happened
Battery percentage is not updating for Aqara Curtains motor B1. It always gives value “32” in “battery” field of device topic payload.
Previously I was using v1.10 and it was ok, but on latest versions, from v1.20, this bug appears.

## How to reproduce it (minimal and precise)
Use Aqara Curtains motor B1
Use zigbee dongle 2538
Use zigbee2mqtt on latest version 1.21.1
See mqtt status of device. Mine is 100% charged but I see old cached value “32” in “battery”

## Debug Info
Zigbee2MQTT version:
Adapter hardware: CC2538
Adapter firmware version: n/a

Could you help please, what I can try to resolve this issue?

**Comment by new-kirte** [comment]
same here. battery is stuck at 55%
