### ISSUE TITLE
TuYa TS0202 motion sensor no battery + tamper

### ISSUE THREAD

**Issue by dcboy87** [Koenkk/zigbee2mqtt#8805]
## What happened

I paired [this ](https://www.aliexpress.com/item/1005003036701978.html) motion sensor, everything works so far, exept tamper and Battery level. It seems, this device doesn't support both values. Also in frontend, where power source is indicated, theere is only a flashing red % symbol

![grafik](https://user-images.githubusercontent.com/45015463/133921590-c78fe443-f24c-48bc-87c2-93fe217daae1.png)

Edit: now after about 4 hours it seems to have the correct battery value, also the red % symbol is gone!

## What did you expect to happen
- ~~showing right power source~~
- working tamper  or remove tamper
- ~~correct battery level or remove battery level~~

## How to reproduce it (minimal and precise)
pair and see
## Debug info

Zigbee2MQTT version
    1.21.1-dev commit: 27b36b31

Coordinator type
    zStack30x

Coordinator revision
    20190425

Frontend version
    0.6.7

**Comment by adriannowaq** [comment]
You need to write your own converter for this

**Comment by adriannowaq** [comment]
You should try these:
[HOW TO SUPPORT NEW DEVICES](https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
)

```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['TS0202'], 
    model: 'TS0202', 
    vendor: 'undefined',
    description: 'motion sensor', 
    fromZigbee: [fz.ias_contact_alarm_1_report, fz.battery], 
    toZigbee: [], 
    exposes: [e.battery(), e.occupancy(), e.tamper(), e.linkquality() ], 
};

module.exports = definition;
```
