### ISSUE TITLE
(Dashboard display) Issues with Siterwell GS361A-H04

### ISSUE THREAD

**Issue by ovizii** [Koenkk/zigbee2mqtt#8813]
I connected a new Siterwell GS361A-H04 which is supposed to be supported according to: https://www.zigbee2mqtt.io/devices/GS361A-H04.html#siterwell-gs361a-h04 

It is now showing up in zigbee2mqtt but I can see a few quirks and am unsure if this is a bug or if I can solve it myself via some magic configuration.

z2mqtt dashboard, 3x state doesn't really help. 
Why is running state shown as N/A?
![image](https://user-images.githubusercontent.com/837902/133986395-10b9abea-2daa-4738-9e05-ae78bf571e10.png)

The info seems to be there just not displayed in the dashboard
![image](https://user-images.githubusercontent.com/837902/133986819-e95ad0fa-64f6-4b22-bafb-ea69698ac3dd.png)

![image](https://user-images.githubusercontent.com/837902/133986910-e6878848-7b70-499c-a118-6d613d9e6b74.png)

## Debug info
Zigbee2MQTT version: 1.21.1-1
Adapter hardware: cc2652rb 
Adapter firmware version: not sure where to find it but I am using a recommended adapter: Slaesh's CC2652RB stick

**Comment by datag** [comment]
Here too:

Sending `{"current_heating_setpoint": ""}` to the `*/get` topic results in
`Zigbee2MQTT:error 2021-10-21 22:40:05: No converter available for 'get' 'current_heating_setpoint' ()`

manufacturerName of my device: `_TZE200_jeaxp72v`

Also running latest dev branch. Willing to debug but might need some hints.

**Comment by jufo84** [comment]
Same here both values shows null

**Comment by Andy-Hennah** [comment]
![screenshot-83e04bb0](https://user-images.githubusercontent.com/53600645/174007884-9396def8-3b7f-4843-83ca-1832ff60fd7d.jpg)

I'm seeing the the thing.  I'm happy to provide logs etc. (but I might need a little guidance).  This is on z2m version 1.25.2.

**Comment by Andy-Hennah** [comment]
This is what the state looks like (from the z2m interface)
![screenshot-acd298eb](https://user-images.githubusercontent.com/53600645/174009271-4e6cb50a-3369-46fb-8b5a-e8d02fdfbb9f.jpg)

**Comment by Woodpeckercz** [comment]
Same here, I have two of these and both show position n/a and running state null

**Comment by toby1984** [comment]
Same here, anyone know how to debug this ?

**Comment by BalassaMarton** [comment]
+1 :(

**Comment by Dark-Gizmoa** [comment]
exact the same problem :-(

**Comment by minmaxat** [comment]
+1

**Comment by GamerClassN7** [comment]
Hame problem here any news ?

**Comment by josephfh** [comment]
Same problem here. I can provide logs if anyone can help

**Comment by GamerClassN7** [comment]
> Same problem here. I can provide logs if anyone can help

Unforchunatelly, noone is responding , do you have same probles foloved with problem of sending manualy set values to home assitant ? as well ?  thanks for answer

**Comment by GamerClassN7** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/17365 I created new  Issue dedicated to reading data from device :) hopefully it gets some notice :)

**Comment by Setka20** [comment]
I have the same problem.

**Comment by massenmacher** [comment]
For me also still a problem :/

**Comment by bit-factor** [comment]
same here. :-(

**Comment by veeroohre** [comment]
+1

**Comment by veeroohre** [comment]
why is this issue closed?

**Comment by Soulfly999** [comment]
The Problem still exists! Zigbee2MQTT-Version [2.3.0]
