### ISSUE TITLE
Silvercrest Garden Plug is not correct recognized

### ISSUE THREAD

**Issue by BigDi** [Koenkk/zigbee2mqtt#8816]
Bought this device
[Silvercrest Garden Plug](https://www.lidl.de/p/silvercrest-gartenspiess-mit-2-steckdosen-zigbee-smart-home/p100329849)
and it is recognized as TuYa TS0101

I work with iobroker zigbee and the issue is there marked as zigbee herdsman converters problem.
It seems that the garden plug is a variation of a TuYa TS 0101.

**Comment by McMornan** [comment]
Hi, I can confirm that issue. However I think this is due to it not being in the database :) At least I did not find it in supported devices. Same issue for this outdoor plug: https://www.lidl.de/p/silvercrest-aussen-steckdosen-adapter-zigbee-smart-home/p100333688

**Comment by BigDi** [comment]
![grafik](https://user-images.githubusercontent.com/11903065/142899916-9795f5e8-75fd-4ba8-be8e-1be5b6b315c0.png)

**Comment by BigDi** [comment]
It seems to be a Tuya device. How to go on?

**Comment by BigDi** [comment]
With changes in the devices/lidl.js I can control the plug. Only the icon is missed
{
     fingerprint: [{modelID: 'TS0101', manufacturerName: '_TZ3000_br3laukf'},
         {modelID: 'TS0101', manufacturerName: '_TZ3000_br3laukf'}],
     model: 'TS0101_HG06620',
     vendor: 'Lidl',
     description: 'Garden Spike with 2 sockets Smart Home',
     extend: extend.switch(),
     whiteLabel: [{vendor: 'Lidl', model: 'HG06620'}],
 },

**Comment by Tonvandermark** [comment]
Same problem here:
![Schermafbeelding 2021-12-10 om 11 19 39](https://user-images.githubusercontent.com/82510574/145558281-f4e56372-0183-48a0-8c30-2c18c7fe7fa3.png)
Is there any planning to add this device to the supported database?
