### ISSUE TITLE
Linkquality of routers doesn't show as graph

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#883]
I noticed that the linkquality isn't shown as graph in home assistant. Looks like homeassistant takes the state as a string because every number gehts its on color in a bar (see picture).

<img width="353" alt="bildschirmfoto 2019-01-18 um 13 01 20" src="https://user-images.githubusercontent.com/25117255/51385997-2fb87800-1b21-11e9-9124-80687818b7c0.png">

**Comment by Koenkk** [comment]
Thanks, fixed

**Comment by h4nc** [comment]
I have zigbee2mqtt edge. Do I myself have to change something too fix that in HA, but for now I see it like before.

**Comment by Koenkk** [comment]
Update to latests edge and restart home assistant should be enough.

**Comment by h4nc** [comment]
I still get not graph. Do I have to delete the old data from the database?

**Comment by h4nc** [comment]
After reinstalling edge the linkquality shows as graph.

But now I noticed that it says 
Linkquality: x RSSI 

RSSI isn‘t a unit and also we get values for linkquality AND RSSI

**Comment by Koenkk** [comment]
So in order to have the graph shown the sensor should have a unit, what would be a good unit for the linkquality?

**Comment by h4nc** [comment]
I see, so we need to set a unit so that the graph is shown. Isn't there a way to set it unitless.

There are some value in physics that don't have a unit like the Mach-number.

If it's not possible to set it a unitless number than your solution to set it as RSSI is good enough until there is a way to set it unitless.
Maybe something like that should be implemanted in ha, unless it it isn't already.

Do you knwo which units are allowed in ha?

**Comment by Koenkk** [comment]
@h4nc there isn't really a unit, https://www.avrfreaks.net/comment/1162131#comment-1162131

**Comment by Koenkk** [comment]
yes, updated to `-`

**Comment by h4nc** [comment]
I updated edge and the unit is gone in the attributes but I still get the unit RSSI in the state.

<img width="349" alt="bildschirmfoto 2019-01-21 um 19 59 33" src="https://user-images.githubusercontent.com/25117255/51493924-1d576c00-1db7-11e9-91f4-353ebb30d8b3.png">
<img width="334" alt="bildschirmfoto 2019-01-21 um 19 59 39" src="https://user-images.githubusercontent.com/25117255/51493926-1f212f80-1db7-11e9-81ad-3e097658b5b1.png">

**Comment by Koenkk** [comment]
Did you restart home assistant?

**Comment by h4nc** [comment]
Yes, I did. Tried it again, still RSSI

**Comment by MarsWarrior** [comment]
> Yes, I did. Tried it again, still RSSI

I think you have to remove the sensor from home assistants device registry in the .strorage folder. You should finf the rssi sensor in one or more of the core.* files.

Remove entry and restart home assistant!

**Comment by Koenkk** [comment]
A build issue prevented the build from regenerated, should be up in an hour.

**Comment by h4nc** [comment]
Nice, thanks for letting us know.
