### ISSUE TITLE
Snzb-02 dont give temperature and humidity valors

### ISSUE THREAD

**Issue by maiflaii** [Koenkk/zigbee2mqtt#8835]
Cc2531 z-stack 1.2 
Zigbee2mqtt version 1.21.1-1 
Ha Versión
core-2021.9.7
supervisor-2021.09.0

When I try connect a new device of this,temperature and humidity dont show me the valor,show null both

**Comment by chimcanhcut1112** [comment]
> Cc2531 z-stack 1.2
> Zigbee2mqtt version 1.21.1-1
> Ha Versión
> core-2021.9.7
> supervisor-2021.09.0
> 
> When I try connect a new device of this,temperature and humidity dont show me the valor,show null both

rollback core version 9.6, will fine.

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/8971
