### ISSUE TITLE
Frontend map fails with 'Cannot read property' error

### ISSUE THREAD

**Issue by Westcott1** [Koenkk/zigbee2mqtt#8836]
## What happened
Frontend map failed to draw.

info  2021-09-21 19:40:29: Starting network scan (includeRoutes 'false')
~ ~ ~ ~
info  2021-09-21 19:41:13: Network scan finished
info  2021-09-21 19:41:13: MQTT publish: topic 'zigbee2mqtt/bridge/response/networkmap', payload '{"data":{},"error":"Cannot read property 'ieeeAddr' of undefined","status":"error","transaction":"9rqku-10"}'

I'm guessing that there is some incomplete device data somewhere.
There is nothing obviously wrong (to me!) in the database.
Where should I look?

## Debug info
Zigbee2MQTT version: 1.21.1-dev (this evening)
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210708

**Comment by tteck** [comment]
Same

**Comment by Koenkk** [comment]
Can you update to latest-dev in 1 hour from now and provide the debug logging again?

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by tteck** [comment]
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/7206051/log.txt)

Line 616

**Comment by Koenkk** [comment]
Can you check if it has been fixed?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by tteck** [comment]
Yes, I'll check. I'm running bare metal, so it should be a little faster

**Comment by tteck** [comment]
It is indeed fixed!

**Comment by Koenkk** [comment]
Thanks!
