### ISSUE TITLE
QBKG03LM does not find route after some time installed

### ISSUE THREAD

**Issue by hanross2323** [Koenkk/zigbee2mqtt#884]
Hi

Aqara Wall Switch (no neutral - double key) loses routing after some time correctly connected to zigbee2mqtt.

`  zigbee2mqtt:error 2019-1-18 13:33:32 Zigbee publish to '0x00158d0002c03208', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - 3 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.`

Coordinator version:

`Coordinator firmware version: '20181024'`

Zigbee2mqtt 1.0.1

**Comment by Koenkk** [comment]
When having `log_level` `debug` (https://koenkk.github.io/zigbee2mqtt/configuration/configuration.html) do you see `Check online` logging of this device?

**Comment by brtwrs** [comment]
I'm having the same problems as @hanross2323. I do see "Check online" logging for this device in my logs

2019-1-22 09:24:12 - debug: Check online 0x00158d0001660bfe 0x00158d0001660bfe
2019-1-22 09:37:13 - debug: Check online 0x00158d0001660bf9 0x00158d0001660bf9

Both my switches worked perfect for a few days

Im on your latest dev branch btw

**Comment by Koenkk** [comment]
@brtwrs what's the linkquality of the device, could you also post the networkmap?

**Comment by brtwrs** [comment]
They dont show linkquality. But there are mulitple IKEA lightbulbs in the same room which are always working so I guess range is not the problem.

Here is my networkmap:

`{
node[shape=record];
  "0x00124b0009eb0446" [label="{0x00124b0009eb0446|Coordinator|No model information available|online}"];
  "0x00124b0009eb0446" -> "0x90fd9ffffe35aaf7" [label="76"]
  "0x00124b0009eb0446" -> "0xd0cf5efffe7a4825" [label="66"]
  "0x00124b001b6aec4e" [label="{0x00124b001b6aec4e|Router|No model information available|offline}"];
  "0x000b57fffed9c663" [label="{0x000b57fffed9c663|Router|IKEA TRADFRI LED bulb E12/E14 400 lumen, dimmable, white spectrum, opal white (LED1536G5)|offline}"];
  "0x000b57fffed9c663" -> "0x00124b0009eb0446" [label="92"]
  "0x000b57fffed9c663" -> "0x000b57fffe9a3260" [label="50"]
  "0x000b57fffed9c663" -> "0xd0cf5efffe7a4825" [label="14"]
  "0x000b57fffe9a3260" [label="{0x000b57fffe9a3260|Router|IKEA TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (LED1649C5)|offline}"];
  "0x000b57fffe9a3260" -> "0x00124b0009eb0446" [label="19"]
  "0x000b57fffe9a3260" -> "0x90fd9ffffe35aaf7" [label="94"]
  "0x000b57fffe9a3260" -> "0xd0cf5efffe7a4825" [label="37"]
  "0x000b57fffeae4fba" [label="{0x000b57fffeae4fba|Router|IKEA TRADFRI LED bulb E27/E26 600 lumen, dimmable, color, opal white (LED1624G9)|offline}"];
  "0x00158d00016da6c8" [label="{0x00158d00016da6c8|Router|Xiaomi Aqara double key wired wall switch (QBKG03LM)|online}"];
  "0x000b57fffe9a8c12" [label="{0x000b57fffe9a8c12|Router|IKEA TRADFRI LED bulb E26/E27 980 lumen, dimmable, white spectrum, opal white (LED1545G12)|offline}"];
  "0x000b57fffe9a8c12" -> "0x00124b0009eb0446" [label="97"]
  "0x000b57fffe9a8c12" -> "0x000b57fffe9a3260" [label="108"]
  "0x000b57fffe9a8c12" -> "0xd0cf5efffe7a4825" [label="66"]
  "0x00158d00016c4843" [label="{0x00158d00016c4843|EndDevice|Xiaomi Aqara wireless switch (WXKG11LM)|online}"];
  "0x000b57fffe9de3df" [label="{0x000b57fffe9de3df|Router|IKEA TRADFRI LED bulb E27/E26 600 lumen, dimmable, color, opal white (LED1624G9)|offline}"];
  "0x000b57fffe9de3df" -> "0x00124b0009eb0446" [label="35"]
  "0x000b57fffe9de3df" -> "0x000b57fffe9a3260" [label="60"]
  "0x000b57fffe9de3df" -> "0x90fd9ffffe35aaf7" [label="166"]
  "0x000b57fffe9de3df" -> "0xd0cf5efffe7a4825" [label="91"]
  "0x000b57fffe9c2eb6" [label="{0x000b57fffe9c2eb6|Router|IKEA TRADFRI LED bulb E27/E26 600 lumen, dimmable, color, opal white (LED1624G9)|offline}"];
  "0x000b57fffe9c2eb6" -> "0x00124b0009eb0446" [label="85"]
  "0x000b57fffe9c2eb6" -> "0x000b57fffe9a3260" [label="92"]
  "0x000b57fffe9c2eb6" -> "0x90fd9ffffe35aaf7" [label="148"]
  "0x000b57fffe9c2eb6" -> "0xd0cf5efffe7a4825" [label="90"]
  "0x000b57fffe48ba2a" [label="{0x000b57fffe48ba2a|Router|IKEA TRADFRI LED bulb E12/E14/E17 400 lumen, dimmable warm white, chandelier opal (LED1649C5)|offline}"];
  "0x000b57fffe48ba2a" -> "0x00124b0009eb0446" [label="69"]
  "0x000b57fffe48ba2a" -> "0x000b57fffe9a3260" [label="204"]
  "0x000b57fffe48ba2a" -> "0x90fd9ffffe35aaf7" [label="133"]
  "0x000b57fffe48ba2a" -> "0xd0cf5efffe7a4825" [label="60"]
  "0x000b57fffe3635d7" [label="{0x000b57fffe3635d7|Router|IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, opal white (LED1623G12)|offline}"];
  "0x000b57fffe3635d7" -> "0x00124b0009eb0446" [label="72"]
  "0x000b57fffe3635d7" -> "0x000b57fffe9a3260" [label="93"]
  "0x000b57fffe3635d7" -> "0x90fd9ffffe35aaf7" [label="62"]
  "0x90fd9ffffe676907" [label="{0x90fd9ffffe676907|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|offline}"];
  "0x90fd9ffffe676907" -> "0x000b57fffe9a3260" [label="49"]
  "0x90fd9ffffe676907" -> "0x90fd9ffffe35aaf7" [label="214"]
  "0x90fd9ffffe676907" -> "0xd0cf5efffe7a4825" [label="25"]
  "0x90fd9ffffe16ad09" [label="{0x90fd9ffffe16ad09|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|online}"];
  "0x90fd9ffffe16ad09" -> "0x000b57fffe9a3260" [label="91"]
  "0x90fd9ffffe16ad09" -> "0x90fd9ffffe35aaf7" [label="255"]
  "0x90fd9ffffe16ad09" -> "0xd0cf5efffe7a4825" [label="118"]
  "0x90fd9ffffe35aaf7" [label="{0x90fd9ffffe35aaf7|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|online}"];
  "0x90fd9ffffe35aaf7" -> "0x00124b0009eb0446" [label="36"]
  "0x90fd9ffffe35aaf7" -> "0x000b57fffe9a3260" [label="98"]
  "0x90fd9ffffe35aaf7" -> "0xd0cf5efffe7a4825" [label="105"]
  "0x000b57fffed740f7" [label="{0x000b57fffed740f7|Router|IKEA TRADFRI driver for wireless control (10 watt) (ICPSHC24-10EU-IL-1)|offline}"];
  "0x000b57fffea15468" [label="{0x000b57fffea15468|Router|IKEA TRADFRI driver for wireless control (10 watt) (ICPSHC24-10EU-IL-1)|offline}"];
  "0x000b57fffea15468" -> "0x00124b0009eb0446" [label="63"]
  "0x000b57fffea15468" -> "0x90fd9ffffe35aaf7" [label="91"]
  "0x000b57fffea15468" -> "0xd0cf5efffe7a4825" [label="136"]
  "0x90fd9ffffe29ea1e" [label="{0x90fd9ffffe29ea1e|Router|IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, opal white (LED1623G12)|offline}"];
  "0x90fd9ffffe29ea1e" -> "0x00124b0009eb0446" [label="55"]
  "0x90fd9ffffe29ea1e" -> "0x000b57fffe9a3260" [label="81"]
  "0x00158d0001df0140" [label="{0x00158d0001df0140|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x000b57fffe301837" [label="{0x000b57fffe301837|Router|IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, opal white (LED1623G12)|online}"];
  "0x000b57fffe301837" -> "0x000b57fffe9a3260" [label="39"]
  "0x000b57fffe301837" -> "0xd0cf5efffe7a4825" [label="0"]
  "0x00158d0001dbd69d" [label="{0x00158d0001dbd69d|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0001dbd69d" -> "0x000b57fffe9a3260" [label="255"]
  "0x00158d0001d6f861" [label="{0x00158d0001d6f861|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0001d6f861" -> "0x000b57fffe9a3260" [label="255"]
  "0x00158d000171410e" [label="{0x00158d000171410e|EndDevice|Xiaomi Aqara wireless switch (WXKG11LM)|online}"];
  "0x00158d000171410e" -> "0x90fd9ffffe35aaf7" [label="255"]
  "0x00158d0001d9265b" [label="{0x00158d0001d9265b|EndDevice|Xiaomi MiJia human body movement sensor (RTCGQ01LM)|online}"];
  "0x00158d0001a66931" [label="{0x00158d0001a66931|EndDevice|Xiaomi Aqara wireless switch (WXKG11LM)|online}"];
  "0x00158d0001a66931" -> "0x90fd9ffffe35aaf7" [label="255"]
  "0x00158d0001ab1cd6" [label="{0x00158d0001ab1cd6|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d0002a523a6" [label="{0x00158d0002a523a6|EndDevice|Xiaomi Aqara vibration sensor (DJT11LM)|online}"];
  "0x00158d0002a22b94" [label="{0x00158d0002a22b94|EndDevice|Xiaomi Aqara vibration sensor (DJT11LM)|online}"];
  "0x00158d0002a22b94" -> "0x00124b0009eb0446" [label="85"]
  "0xd0cf5efffeef2107" [label="{0xd0cf5efffeef2107|Router|IKEA TRADFRI control outlet (E1603)|offline}"];
  "0xd0cf5efffeef2107" -> "0x00124b0009eb0446" [label="0"]
  "0xd0cf5efffeef2107" -> "0x000b57fffe9a3260" [label="64"]
  "0xd0cf5efffeef2107" -> "0x90fd9ffffe35aaf7" [label="118"]
  "0xd0cf5efffeef2107" -> "0xd0cf5efffe7a4825" [label="86"]
  "0xd0cf5efffe7a4825" [label="{0xd0cf5efffe7a4825|Router|IKEA TRADFRI control outlet (E1603)|offline}"];
  "0xd0cf5efffe7a4825" -> "0x00124b0009eb0446" [label="31"]
  "0xd0cf5efffe7a4825" -> "0x90fd9ffffe35aaf7" [label="101"]
  "0x00158d0001244204" [label="{0x00158d0001244204|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d0001244204" -> "0x00124b0009eb0446" [label="59"]
  "0x00158d0001fa282d" [label="{0x00158d0001fa282d|Router|Xiaomi Mi power plug ZigBee (ZNCZ02LM)|online}"];
  "0x00158d0001fa282d" -> "0x00124b0009eb0446" [label="97"]
  "0x00158d0001fa282d" -> "0x000b57fffe9a3260" [label="84"]
  "0x00158d0001fa282d" -> "0x90fd9ffffe35aaf7" [label="124"]
  "0x00158d0001ad6c9e" [label="{0x00158d0001ad6c9e|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d0001ab22b9" [label="{0x00158d0001ab22b9|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d0001d665bb" [label="{0x00158d0001d665bb|EndDevice|Xiaomi MiJia human body movement sensor (RTCGQ01LM)|online}"];
  "0x00158d0001d665bb" -> "0x00124b0009eb0446" [label="49"]
  "0x00158d0001656eb5" [label="{0x00158d0001656eb5|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d0001df047d" [label="{0x00158d0001df047d|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d00016d0eeb" [label="{0x00158d00016d0eeb|EndDevice|Xiaomi MiJia temperature & humidity sensor  (WSDCGQ01LM)|online}"];
  "0x00158d00016d0eeb" -> "0x00124b0009eb0446" [label="75"]
  "0x00158d000238796c" [label="{0x00158d000238796c|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0001244153" [label="{0x00158d0001244153|EndDevice|Xiaomi Aqara human body movement and illuminance sensor (RTCGQ11LM)|online}"];
  "0x00158d000238789f" [label="{0x00158d000238789f|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d000238789f" -> "0x00124b0009eb0446" [label="78"]
  "0x00158d0001a5dc94" [label="{0x00158d0001a5dc94|EndDevice|Xiaomi MiJia door & window contact sensor (MCCGQ01LM)|online}"];
  "0x00158d0001660bfe" [label="{0x00158d0001660bfe|Router|Xiaomi Aqara double key wired wall switch (QBKG03LM)|online}"];
  "0x000b57fffeaf7c65" [label="{0x000b57fffeaf7c65|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|offline}"];
  "0x000b57fffeaf7c65" -> "0x00124b0009eb0446" [label="42"]
  "0x000b57fffeaf7c65" -> "0x000b57fffe9a3260" [label="97"]
  "0x000b57fffeaf7c65" -> "0x90fd9ffffe35aaf7" [label="184"]
  "0x000b57fffeb00408" [label="{0x000b57fffeb00408|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|online}"];
  "0x000b57fffeb00408" -> "0x00124b0009eb0446" [label="31"]
  "0x000b57fffeb00408" -> "0x90fd9ffffe35aaf7" [label="117"]
  "0x000b57fffeb00408" -> "0xd0cf5efffe7a4825" [label="191"]
  "0x90fd9ffffe6dfd5f" [label="{0x90fd9ffffe6dfd5f|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|offline}"];
  "0x90fd9ffffe6dfd5f" -> "0x00124b0009eb0446" [label="31"]
  "0x90fd9ffffe6dfd5f" -> "0x000b57fffe9a3260" [label="101"]
  "0x90fd9ffffe6dfd5f" -> "0x90fd9ffffe35aaf7" [label="169"]
  "0x90fd9ffffe6dfd5f" -> "0xd0cf5efffe7a4825" [label="122"]
  "0x000b57fffebfc857" [label="{0x000b57fffebfc857|Router|IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (LED1650R5)|offline}"];
  "0x000b57fffebfc857" -> "0x00124b0009eb0446" [label="0"]
  "0x000b57fffebfc857" -> "0x000b57fffe9a3260" [label="54"]
  "0x000b57fffebfc857" -> "0x90fd9ffffe35aaf7" [label="120"]
  "0x000b57fffebfc857" -> "0xd0cf5efffe7a4825" [label="171"]
  "0x00158d0001660bf9" [label="{0x00158d0001660bf9|Router|Xiaomi Aqara double key wired wall switch (QBKG03LM)|online}"];
  "0x00158d00016fd1cf" [label="{0x00158d00016fd1cf|EndDevice|Xiaomi MiJia temperature & humidity sensor  (WSDCGQ01LM)|online}"];
  "0x00158d0001d76c39" [label="{0x00158d0001d76c39|EndDevice|Xiaomi Aqara water leak sensor (SJCGQ11LM)|online}"];
  "0x00158d0001daee67" [label="{0x00158d0001daee67|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x000b57fffe229fe5" [label="{0x000b57fffe229fe5|EndDevice|IKEA TRADFRI wireless dimmer (ICTC-G-1)|online}"];
  "0x00158d0001ab1d02" [label="{0x00158d0001ab1d02|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d0001824d4e" [label="{0x00158d0001824d4e|EndDevice|Xiaomi MiJia temperature & humidity sensor  (WSDCGQ01LM)|online}"];
  "0x00158d000238798f" [label="{0x00158d000238798f|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0001209e60" [label="{0x00158d0001209e60|EndDevice|Xiaomi MiJia human body movement sensor (RTCGQ01LM)|online}"];
  "0x00158d0001d6be87" [label="{0x00158d0001d6be87|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
  "0x00158d0001d6be8a" [label="{0x00158d0001d6be8a|EndDevice|Xiaomi Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)|online}"];
}'`

**Comment by Koenkk** [comment]
Let's continue in #943
