### ISSUE TITLE
Errors in log due to problems on OSRAM OTA website

### ISSUE THREAD

**Issue by tabnul** [Koenkk/zigbee2mqtt#8864]
The OSRAM OTA url has issues, it has an invalid/expired SSL certificate and throws all kinds of errors.
_https://update.ledvance.com/firmware-overview_

As a result i see errors in the zigbee2mqtt logs.

`Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: certificate has expired `

I dont think zigbee2mqtt could help this, maybe by adding a capability for enabling or disabling brand-specific OTA functionality.
Still logging it for other people that might report this.

**Comment by vogler** [comment]
Same here with `ikea_ota_use_test_url: true` ([doc](https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/information/ota_updates.md#using-the-ikea-tradfri-test-server)):
~~~
Zigbee2MQTT:debug 2021-09-24 12:16:03: Device 'Osram_Strip_RGBW_Kitchen' requested OTA
Zigbee2MQTT:debug 2021-09-24 12:16:03: Check if update available for '0x7cb03eaa00a9e97e' (LIGHTIFY Indoor Flex RGBW)
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +21ms
Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
~~~
