### ISSUE TITLE
CC2652P MEM_ERROR since FW update to 20210901 from egony repo.

### ISSUE THREAD

**Issue by ALaDoffe** [Koenkk/zigbee2mqtt#8878]
## What happened

Hello 

I recently updated my cc2652p_E72-2G4M20S1E  firmware from 20210211 to 20210901
I followed the procédure https://github.com/egony/cc2652p_E72-2G4M20S1E/wiki/Flashing-EN 

Flash was sucessfull and erased NVRAM at the end as described.
  
Since I got regulary 0x10: MEM_ERROR and Data request failed with error: 'MAC no resources' (26)

Need to unplug/plug the stick and work for a while. 

I have only 28 devices and most of them are routers.

## What did you expect to happen

Work as before

## Debug info

Zigbee2MQTT version: Zigbee2MQTT version 1.21.1-dev (commit #58957a30) on RPI 3B+ Venv install
Adapter hardware: CC2652P E72-2G4M20S1E
Adapter firmware version: CC2652P_E72_20210901

[zigbee2mqtt.zip](https://github.com/Koenkk/zigbee2mqtt/files/7229749/zigbee2mqtt.zip)

**Comment by Koenkk** [comment]
Since this issue is with a non-standard firmware (not in https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin), I suggest creating an issue in that repository instead
