### ISSUE TITLE
Possible risks with "permit_join: true"

### ISSUE THREAD

**Issue by leobel96** [Koenkk/zigbee2mqtt#889]
By default "permit_join: true". In my opinion this could led to conflicts (a neighbour could not succeed in connecting his device to his coordinator) or vulnerabilites (a malicious device can be connected by a stranger with zero effort) if a user isn't warned about the risks. It should be false by default and a timer should automatically set it to false after some time for me.

**Comment by Koenkk** [comment]
The user is warned about this when you start zigbee2mqtt.

**Comment by leobel96** [comment]
Yes but in my opinion it is not enough. A timer is necessary as in commercial gateways...

**Comment by Koenkk** [comment]
@Landrash looks good, can you make a pr?

**Comment by Landrash** [comment]
@Koenkk Doing it now and I'll update this with the PR #X

**Comment by leobel96** [comment]
The solution proposed by @Landrash seems ok for me. I think the issue can be closed.
