### ISSUE TITLE
TuYa TS0503B

### ISSUE THREAD

**Issue by galdaka** [Koenkk/zigbee2mqtt#8892]
# Bug Report

## What happened

The light is always in red color. **Only the on / off button works properly.**

## What did you expect to happen

Which can change color and operate with the controller normally

## How to reproduce it (minimal and precise)

1) Connect controller to led strip and pair it. 
2) Enter Supervisor => Zigbee2mqtt => Controller device => Exposes=> And try to change the color or operate.

## Debug Info
Zigbee2MQTT version: 1.18.1-1
Adapter hardware: CC2531
Adapter firmware version: cc2530_io_1.2.2a.44539

**Comment by francisp2** [comment]
Not stale
