### ISSUE TITLE
TuYa TS0601 (Moes) thermostat shows redundant attributes for each sensor/switch

### ISSUE THREAD

**Issue by groenmarsmannetje** [Koenkk/zigbee2mqtt#8902]
## What happened
The different sensors/switches/selects that are created for this thermostat device contain a lot of attributes that are redundant. In Home Assistant this duplicate information is just waste especially when the recorder also logs all this redundant information in the database.

## What did you expect to happen
Only include attributes for a device once and add it to the main climate component or to a sensor/switch/select when it has any relevance to that sensor, switch or select.

## How to reproduce it (minimal and precise)
Look at the attributes of the several sensors that are created and see that they are a just copy of each other.

## Debug info
Zigbee2MQTT version: latest
Adapter hardware: zzh
Adapter firmware version: latest

**Comment by Plawasan** [comment]
You can get rid of those by disabling legacy attributes in Z2M config however be aware of this impact at the moment - https://github.com/Koenkk/zigbee2mqtt/issues/8807

**Comment by groenmarsmannetje** [comment]
> You can get rid of those by disabling legacy attributes in Z2M config however be aware of this impact at the moment - #8807

Thanks, I did not know that. Will check if it works for me without any side effects.

**Comment by groenmarsmannetje** [comment]
I tried it, but it did not work for me, because I use some attributes in my automations.
And as it removes all attributes from all entities, these automations do not work anymore.
So I had to enable legacy attributes again.

**Comment by groenmarsmannetje** [comment]
Relates to #9269
