### ISSUE TITLE
Can't discover any devices

### ISSUE THREAD

**Issue by thehiddentruth** [Koenkk/zigbee2mqtt#8920]
I Installed Mosquitto and Zigbee2MQTT and using C2531 Adapter. But I can't see any devices on the network. The CC2531 green light in constant on. I start the system by running the "npm start" command, but I can't see any available Zigbee devices. I have a Aqara Mini Wireless, which i make enter the "pairing mode" but still don't discover it.

## Debug Info
Zigbee2MQTT version: 1.21.1
Adapter hardware: CC2531
Adapter firmware version: No idea. According to the seller it should be flashed with "latest firmware version". Is there a way to check this without CC debugger?

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

Have have you added the device to your configuration.yaml and set up your MQTT client?

You can find instructions on how to do that [here](https://www.zigbee2mqtt.io/information/configuration.html)

Please make sure that all of the mandatory entries are populated, your MQTT server is accepting connections, and your device is accessible by Zigbee2MQTT.

**Comment by thehiddentruth** [comment]
**This is what confirmationguration.yaml looks like**
`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.141.184:1883
  user: MQTT
  password: admin
serial:
  port: /dev/ttyACM0
\n\nadvanced:\n    network_key: GENERATE
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
  channel: 11
  log_level: debug`

I don't know what to do else. I followed this exact guide on [Zigbee2MQTT](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html)

**Comment by danieledwardgeorgehitchcock** [comment]
You’ve got the advanced key declared twice and a bunch of new line characters which likely wouldn’t help

**Comment by thehiddentruth** [comment]
So multiple things

### First try
**When my configuration.yaml looks like this:**
`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.141.184:1883
  user: MQTT
  password: admin
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  host: 0.0.0.0
`

**I get this in the terminal:** 
`Zigbee2MQTT:info  2021-09-30 15:29:00: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-09-30.15-28-59' filename: log.txt
Zigbee2MQTT:info  2021-09-30 15:29:00: Starting Zigbee2MQTT version 1.21.1 (commit #4a51e0c0)
Zigbee2MQTT:info  2021-09-30 15:29:00: Starting zigbee-herdsman (0.13.138)
Zigbee2MQTT:info  2021-09-30 15:29:02: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2021-09-30 15:29:02: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
Zigbee2MQTT:info  2021-09-30 15:29:02: Currently 0 devices are joined:
Zigbee2MQTT:warn  2021-09-30 15:29:02: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2021-09-30 15:29:02: Allowing new devices to join.
Zigbee2MQTT:warn  2021-09-30 15:29:02: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2021-09-30 15:29:02: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2021-09-30 15:29:02: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2021-09-30 15:29:02: Connecting to MQTT server at mqtt://192.168.141.184:1883
Zigbee2MQTT:info  2021-09-30 15:29:02: Connected to MQTT server
Zigbee2MQTT:info  2021-09-30 15:29:02: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2021-09-30 15:29:03: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"4a51e0c0","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"info","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.21.1"}'
`

### Second try
**When I add the advanced network generate:**
`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.141.184:1883
  user: MQTT
  password: admin
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
  network_key: GENERATE 
`

I can't get to start the service when I run npm start. I get this error log:

`> zigbee2mqtt@1.21.1 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2021-09-30 15:35:00: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-09-30.15-34-59' filename: log.txt
Zigbee2MQTT:info  2021-09-30 15:35:00: Starting Zigbee2MQTT version 1.21.1 (commit #4a51e0c0)
Zigbee2MQTT:info  2021-09-30 15:35:00: Starting zigbee-herdsman (0.13.138)
Zigbee2MQTT:error 2021-09-30 15:35:02: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2021-09-30 15:35:02: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2021-09-30 15:35:02: - Extended PAN ID: configured=00124b001949d6a8, adapter=dddddddddddddddd
Zigbee2MQTT:error 2021-09-30 15:35:02: - Network Key: configured=25a0c367e94c8746da7c15882cc559d0, adapter=01030507090b0d0f00020406080a0c0d
Zigbee2MQTT:error 2021-09-30 15:35:02: - Channel List: configured=11, adapter=11
Zigbee2MQTT:error 2021-09-30 15:35:02: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2021-09-30 15:35:02: If you wish to re-commission your network, please remove coordinator backup at /opt/zigbee2mqtt/data/coordinator_backup.json.
Zigbee2MQTT:error 2021-09-30 15:35:02: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2021-09-30 15:35:02: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-09-30 15:35:02: Failed to start zigbee
Zigbee2MQTT:error 2021-09-30 15:35:02: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-09-30 15:35:02: Exiting...
Zigbee2MQTT:error 2021-09-30 15:35:02: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.js:66:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.js:110:27)
    at start (/opt/zigbee2mqtt/index.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.21.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.21.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-30T13_35_02_640Z-debug.log`

When I take a look at the configuration.yaml again, now it looks like this: 

`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.141.184:1883
  user: MQTT
  password: admin
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
  network_key:
    - 37
    - 160
    - 195
    - 103
    - 233
    - 76
    - 135
    - 70
    - 218
    - 124
    - 21
    - 136
    - 44
    - 197
    - 89
    - 208`

**Comment by danieledwardgeorgehitchcock** [comment]
Ok - It looks like your first try should have worked.

It has connected to the MQTT server, and has generated a network key for you.

I do notice that your coordinator firmware isn't as up-to-date as the seller would have you believe (2019-06-08 Z-Zstack 1.2)

Were you able to join any devices on the first try?

**Comment by thehiddentruth** [comment]
No. I press the aqara mini wireless button on the reset button to enter pairing mode, but it still don’t show up as a device.

**Comment by thehiddentruth** [comment]
Any ideas on what I can do?

**Comment by danieledwardgeorgehitchcock** [comment]
Have you got any other decives other than Aqara? They can be a bit difficult to get connected.

If all you have is Aqara, make sure that once Zigbee2MQTT is in join mode, and your Aqara device is also in join mode, to keep the device awake by periodically pressing the button.

You could also try enabling the Zigbee2MQTT frontend GUI in your settings which would be a lot more user-friendly than the command line.

As a final thing, you could aslo enable debug logging and set it to route to the command line so you can see all messages logged by Zigbee2MQTT

**Comment by thehiddentruth** [comment]
I will try with my IKEA Tradfri E27 later tonight, and see if that's any better.

Actually I've already enabled frontend, but still nothing appears in the overview of devices.

Can you please explain on how to "_As a final thing, you could aslo enable debug logging and set it to route to the command line so you can see all messages logged by Zigbee2MQTT_"? A tutorial would also be very good if there's any. Thanks in advance.

**Comment by danieledwardgeorgehitchcock** [comment]
All of this can be found in the configuration guidance on the [zigbee2mqtt.io](zigbee2mqtt.io) website. See [Configuration](https://www.zigbee2mqtt.io/information/configuration.html) and [Debug](https://www.zigbee2mqtt.io/information/debug.html)

Under your `advanced` section in your config file, you will need to add the following:

```yaml
  log_level: debug
  log_output:
    - console
    - file
```

**Comment by thehiddentruth** [comment]
So I added the following to my configuration.yaml file
`homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.141.184:1883
  user: MQTT
  password: admin
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
  host: 0.0.0.0
advanced:
 log_level: debug
 log_output:
    - console
    - file
`

And started the service again, and still nothing. And I've tried both with IKEA Tradfri bulb and Aqara button, and stil nothing shows up on the frontend or anywhere else... This is what console looks like 


`> zigbee2mqtt@1.21.1 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:debug 2021-10-01 14:44:10: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2021-10-01 14:44:10: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-10-01.14-44-10' filename: log.txt
Zigbee2MQTT:debug 2021-10-01 14:44:10: Removing old log directory '/opt/zigbee2mqtt/data/log/2021-09-30.15-32-46'
Zigbee2MQTT:info  2021-10-01 14:44:10: Starting Zigbee2MQTT version 1.21.1 (commit #4a51e0c0)
Zigbee2MQTT:info  2021-10-01 14:44:10: Starting zigbee-herdsman (0.13.138)
Zigbee2MQTT:debug 2021-10-01 14:44:10: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:info  2021-10-01 14:44:13: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2021-10-01 14:44:13: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
Zigbee2MQTT:info  2021-10-01 14:44:13: Currently 0 devices are joined:
Zigbee2MQTT:warn  2021-10-01 14:44:13: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2021-10-01 14:44:13: Allowing new devices to join.
Zigbee2MQTT:warn  2021-10-01 14:44:13: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2021-10-01 14:44:13: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2021-10-01 14:44:13: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2021-10-01 14:44:13: Connecting to MQTT server at mqtt://192.168.141.184:1883
Zigbee2MQTT:debug 2021-10-01 14:44:13: Using MQTT login with username: MQTT
Zigbee2MQTT:info  2021-10-01 14:44:13: Connected to MQTT server
Zigbee2MQTT:info  2021-10-01 14:44:13: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Received MQTT message on 'zigbee2mqtt/bridge/info' with data '{"commit":"4a51e0c0","config":{"advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":0,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":11,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221],"homeassistant_discovery_topic":"homeassistant","homeassistant_legacy_entity_attributes":true,"homeassistant_legacy_triggers":true,"homeassistant_status_topic":"hass/status","last_seen":"disable","legacy_api":true,"log_directory":"/opt/zigbee2mqtt/data/log/%TIMESTAMP%","log_file":"log.txt","log_level":"debug","log_output":["console","file"],"log_rotation":true,"log_symlink_current":false,"log_syslog":{},"pan_id":6754,"report":false,"soft_reset_timeout":0,"timestamp_format":"YYYY-MM-DD HH:mm:ss"},"ban":[],"blocklist":[],"device_options":{},"devices":{},"experimental":{"output":"json"},"external_converters":[],"frontend":{"host":"0.0.0.0","port":8080},"groups":{},"homeassistant":false,"map_options":{"graphviz":{"colors":{"fill":{"coordinator":"#e04e5d","enddevice":"#fff8ce","router":"#4ea3e0"},"font":{"coordinator":"#ffffff","enddevice":"#000000","router":"#ffffff"},"line":{"active":"#009900","inactive":"#994444"}}}},"mqtt":{"base_topic":"zigbee2mqtt","force_disable_retain":false,"include_device_information":false,"server":"mqtt://192.168.141.184:1883","user":"MQTT"},"ota":{"disable_automatic_update_check":false,"update_check_interval":1440},"passlist":[],"permit_join":true,"serial":{"disable_led":false,"port":"/dev/ttyACM0"},"whitelist":[]},"config_schema":{"definitions":{"device":{"properties":{"debounce":{"description":"Debounces messages of this device","title":"Debounce","type":"number"},"debounce_ignore":{"description":"Protects unique payload values of specified payload properties from overriding within debounce time","examples":["action"],"items":{"type":"string"},"title":"Ignore debounce","type":"array"},"filtered_attributes":{"description":"Filter attributes from publish payload.","examples":["temperature","battery","action"],"items":{"type":"string"},"title":"Filtered publish attributes","type":"array"},"filtered_optimistic":{"description":"Filter attributes from optimistic publish payload when calling /set. (This has no effect if optimistic is set to false).","examples":["color_mode","color_temp","color"],"items":{"type":"string"},"title":"Filtered optimistic attributes","type":"array"},"friendly_name":{"description":"Used in the MQTT topic of a device. By default this is the device ID","readOnly":true,"title":"Friendly name","type":"string"},"icon":{"description":"The user-defined device icon for the frontend. It can be a link to an image (not a path to a file) or base64 encoded data URL like: image/svg+xml;base64,PHN2ZyB3aW....R0aD","title":"Icon","type":"string"},"optimistic":{"default":true,"description":"Publish optimistic state after set","title":"Optimistic","type":"boolean"},"qos":{"description":"QoS level for MQTT messages of this device","title":"QoS","type":"number"},"retain":{"description":"Retain MQTT messages of this device","title":"Retain","type":"boolean"},"retention":{"description":"Sets the MQTT Message Expiry in seconds, Make sure to set mqtt.version to 5","title":"Retention","type":"number"}},"required":["friendly_name"],"type":"object"},"group":{"properties":{"devices":{"items":{"type":"string"},"type":"array"},"filtered_attributes":{"items":{"type":"string"},"type":"array"},"friendly_name":{"type":"string"},"optimistic":{"type":"boolean"},"qos":{"type":"number"},"retain":{"type":"boolean"}},"required":["friendly_name"],"type":"object"}},"properties":{"advanced":{"properties":{"adapter_concurrent":{"description":"Adapter concurrency (e.g. 2 for CC2531 or 16 for CC26X2R1) (default: null, uses recommended value)","requiresRestart":true,"title":"Adapter concurrency","type":["number","null"]},"adapter_delay":{"description":"Adapter delay","requiresRestart":true,"title":"Adapter delay","type":["number","null"]},"availability_blacklist":{"items":{"type":"string"},"readOnly":true,"requiresRestart":true,"title":"Availability blacklist (deprecated, use availability_blocklist)","type":"array"},"availability_blocklist":{"description":"Prevent devices from being checked for availability","items":{"type":"string"},"requiresRestart":true,"title":"Availability Blocklist","type":"array"},"availability_passlist":{"description":"Only enable availability check for certain devices","items":{"type":"string"},"requiresRestart":true,"title":"Availability passlist","type":"array"},"availability_timeout":{"default":0,"description":"Availability timeout in seconds when enabled, devices will be checked if they are still online. Only AC powered routers are checked for availability","minimum":0,"requiresRestart":true,"title":"Availability Timeout","type":"number"},"availability_whitelist":{"items":{"type":"string"},"readOnly":true,"requiresRestart":true,"title":"Availability whitelist (deprecated, use passlist)","type":"array"},"baudrate":{"description":"Baud rate speed for serial port, this can be anything firmware support but default is 115200 for Z-Stack and EZSP, 38400 for Deconz, however note that some EZSP firmware need 57600","examples":[38400,57600,115200],"requiresRestart":true,"title":"Baudrate","type":"number"},"cache_state":{"default":true,"description":"MQTT message payload will contain all attributes, not only changed ones. Has to be true when integrating via Home Assistant","title":"Cache state","type":"boolean"},"cache_state_persistent":{"default":true,"description":"Persist cached state, only used when cache_state: true","title":"Persist cache state","type":"boolean"},"cache_state_send_on_startup":{"default":true,"description":"Send cached state on startup, only used when cache_state: true","title":"Send cached state on startup","type":"boolean"},"channel":{"default":11,"description":"Zigbee channel, changing requires repairing all devices! (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)","examples":[15,20,25],"maximum":26,"minimum":11,"requiresRestart":true,"title":"ZigBee channel","type":"number"},"elapsed":{"default":false,"description":"Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg","title":"Elapsed","type":"boolean"},"ext_pan_id":{"description":"Zigbee extended pan ID, changing requires repairing all devices!","items":{"type":"number"},"requiresRestart":true,"title":"Ext Pan ID","type":"array"},"homeassistant_discovery_topic":{"description":"Home Assistant discovery topic","examples":["homeassistant"],"requiresRestart":true,"title":"Homeassistant discovery topic","type":"string"},"homeassistant_legacy_entity_attributes":{"default":true,"description":"Home Assistant legacy entity attributes, when enabled Zigbee2MQTT will add state attributes to each entity, additional to the separate entities and devices it already creates","title":"Home Assistant legacy entity attributes","type":"boolean"},"homeassistant_legacy_triggers":{"default":true,"description":"Home Assistant legacy triggers, when enabled Zigbee2mqt will send an empty 'action' or 'click' after one has been send. A 'sensor_action' and 'sensor_click' will be discoverd","title":"Home Assistant legacy triggers","type":"boolean"},"homeassistant_status_topic":{"description":"Home Assistant status topic","examples":["homeassistant/status"],"requiresRestart":true,"title":"Home Assistant status topic","type":"string"},"ikea_ota_use_test_url":{"default":false,"description":"Use IKEA TRADFRI OTA test server, see OTA updates documentation","requiresRestart":true,"title":"IKEA TRADFRI OTA use test url","type":"boolean"},"last_seen":{"default":"disable","description":"Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message","enum":["disable","ISO_8601","ISO_8601_local","epoch"],"title":"Last seen","type":"string"},"legacy_api":{"default":true,"description":"Disables the legacy api (false = disable)","requiresRestart":true,"title":"Legacy API","type":"boolean"},"log_directory":{"description":"Location of log directory","examples":["data/log/%TIMESTAMP%"],"requiresRestart":true,"title":"Log directory","type":"string"},"log_file":{"default":"log.txt","description":"Log file name, can also contain timestamp","examples":["zigbee2mqtt_%TIMESTAMP%.log"],"requiresRestart":true,"title":"Log file","type":"string"},"log_level":{"default":"info","description":"Logging level","enum":["info","warn","error","debug"],"title":"Log level","type":"string"},"log_output":{"description":"Output location of the log, leave empty to supress logging","items":{"enum":["console","file","syslog"],"type":"string"},"requiresRestart":true,"title":"Log output","type":"array"},"log_rotation":{"default":true,"description":"Log rotation","requiresRestart":true,"title":"Log rotation","type":"boolean"},"log_symlink_current":{"default":false,"description":"Create symlink to current logs in the log directory","requiresRestart":true,"title":"Log symlink current","type":"boolean"},"log_syslog":{"properties":{"app_name":{"default":"Zigbee2MQTT","description":"The name of the application (Default: Zigbee2MQTT).","title":"Localhost","type":"string"},"eol":{"default":"/n","description":"The end of line character to be added to the end of the message (Default: Message without modifications).","title":"eol","type":"string"},"host":{"default":"localhost","description":"The host running syslogd, defaults to localhost.","title":"Host","type":"string"},"localhost":{"default":"localhost","description":"Host to indicate that log messages are coming from (Default: localhost).","title":"Localhost","type":"string"},"path":{"default":"/dev/log","description":"The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).","examples":["/var/run/syslog"],"title":"Path","type":"string"},"pid":{"default":"process.pid","description":"PID of the process that log messages are coming from (Default process.pid).","title":"PID","type":"string"},"port":{"default":123,"description":"The port on the host that syslog is running on, defaults to syslogd's default port.","title":"Port","type":"number"},"protocol":{"default":"tcp4","description":"The network protocol to log over (e.g. tcp4, udp4, tls4, unix, unix-connect, etc).","examples":["udp4","tls4","unix","unix-connect"],"title":"Protocol","type":"string"},"type":{"default":"5424","description":"The type of the syslog protocol to use (Default: BSD, also valid: 5424).","title":"Type","type":"string"}},"title":"syslog","type":"object"},"network_key":{"description":"Network encryption key, changing requires repairing all devices!","oneOf":[{"title":"Network key(string)","type":"string"},{"items":{"type":"number"},"title":"Network key(array)","type":"array"}],"requiresRestart":true,"title":"Network key"},"pan_id":{"description":"ZigBee pan ID, changing requires repairing all devices!","oneOf":[{"title":"Pan ID (string)","type":"string"},{"title":"Pan ID (number)","type":"number"}],"requiresRestart":true,"title":"Pan ID"},"report":{"description":"Enables report feature (deprecated)","readOnly":true,"requiresRestart":true,"title":"Reporting","type":"boolean"},"rtscts":{"description":"RTS / CTS Hardware Flow Control for serial port","requiresRestart":true,"title":"RTS / CTS","type":"boolean"},"soft_reset_timeout":{"description":"Soft reset ZNP after timeout","minimum":0,"readOnly":true,"requiresRestart":true,"title":"Soft reset timeout (deprecated)","type":"number"},"timestamp_format":{"description":"Log timestamp format","examples":["YYYY-MM-DD HH:mm:ss"],"requiresRestart":true,"title":"Timestamp format","type":"string"}},"title":"Advanced","type":"object"},"ban":{"items":{"type":"string"},"readOnly":true,"requiresRestart":true,"title":"Ban (deprecated, use blocklist)","type":"array"},"blocklist":{"description":"Block devices from the network (by ieeeAddr)","items":{"type":"string"},"requiresRestart":true,"title":"Blocklist","type":"array"},"device_options":{"type":"object"},"devices":{"patternProperties":{"^.*$":{"$ref":"#/definitions/device"}},"propertyNames":{"pattern":"^0x[\\d\\w]{16}$"},"type":"object"},"experimental":{"properties":{"output":{"description":"Examples when 'state' of a device is published json: topic: 'zigbee2mqtt/my_bulb' payload '{\"state\": \"ON\"}' attribute: topic 'zigbee2mqtt/my_bulb/state' payload 'ON' attribute_and_json: both json and attribute (see above)","enum":["attribute_and_json","attribute","json"],"title":"MQTT output type","type":"string"},"transmit_power":{"description":"Transmit power of adapter, only available for Z-Stack (CC253*/CC2652/CC1352) adapters, CC2652 = 5dbm, CC1352 max is = 20dbm (5dbm default)","requiresRestart":true,"title":"Transmit power","type":["number","null"]}},"title":"Experimental","type":"object"},"external_converters":{"description":"You can define external converters to e.g. add support for a DiY device","examples":["DIYRuZ_FreePad.js"],"items":{"type":"string"},"requiresRestart":true,"title":"External converters","type":"array"},"frontend":{"properties":{"auth_token":{"description":"Enables authentication, disabled by default","requiresRestart":true,"title":"Auth token","type":["string","null"]},"host":{"default":" 0.0.0.0","description":"Frontend binding host","requiresRestart":true,"title":"Bind host","type":"string"},"port":{"default":8080,"description":"Frontend binding port","requiresRestart":true,"title":"Port","type":"number"}},"title":"Frontend","type":"object"},"groups":{"patternProperties":{"^.*$":{"$ref":"#/definitions/group"}},"propertyNames":{"pattern":"^[\\w].*$"},"type":"object"},"homeassistant":{"default":false,"description":"Home Assistant integration (MQTT discovery)","title":"Home Assistant integration","type":"boolean"},"map_options":{"properties":{"graphviz":{"properties":{"colors":{"properties":{"fill":{"properties":{"coordinator":{"type":"string"},"enddevice":{"type":"string"},"router":{"type":"string"}},"type":"object"},"font":{"properties":{"coordinator":{"type":"string"},"enddevice":{"type":"string"},"router":{"type":"string"}},"type":"object"},"line":{"properties":{"active":{"type":"string"},"inactive":{"type":"string"}},"type":"object"}},"type":"object"}},"type":"object"}},"title":"Networkmap","type":"object"},"mqtt":{"properties":{"base_topic":{"description":"MQTT base topic for Zigbee2MQTT MQTT messages","examples":["zigbee2mqtt"],"requiresRestart":true,"title":"Base topic","type":"string"},"ca":{"description":"Absolute path to SSL/TLS certificate of CA used to sign server and client certificates","examples":["/etc/ssl/mqtt-ca.crt"],"requiresRestart":true,"title":"Certificate authority","type":"string"},"cert":{"description":"Absolute path to SSL/TLS certificate for client-authentication","examples":["/etc/ssl/mqtt-client.crt"],"requiresRestart":true,"title":"SSL/TLS certificate","type":"string"},"client_id":{"description":"MQTT client ID","examples":["MY_CLIENT_ID"],"requiresRestart":true,"title":"Client ID","type":"string"},"force_disable_retain":{"default":false,"description":"Disable retain for all send messages. ONLY enable if you MQTT broker doesn't support retained message (e.g. AWS IoT core, Azure IoT Hub, Google Cloud IoT core, IBM Watson IoT Platform). Enabling will break the Home Assistant integration","requiresRestart":true,"title":"Force disable retain","type":"boolean"},"include_device_information":{"default":false,"description":"Include device information to mqtt messages","title":"Include device information","type":"boolean"},"keepalive":{"default":60,"description":"MQTT keepalive in second","requiresRestart":true,"title":"Keepalive","type":"number"},"key":{"description":"Absolute path to SSL/TLS key for client-authentication","examples":["/etc/ssl/mqtt-client.key"],"requiresRestart":true,"title":"SSL/TLS key","type":"string"},"password":{"description":"MQTT server authentication password","examples":["ILOVEPELMENI"],"requiresRestart":true,"title":"Password","type":"string"},"reject_unauthorized":{"default":true,"description":"Disable self-signed SSL certificate","requiresRestart":true,"title":"Reject unauthorized","type":"boolean"},"server":{"description":"MQTT server URL (use mqtts:// for SSL/TLS connection)","examples":["mqtt://localhost:1883"],"requiresRestart":true,"title":"MQTT server","type":"string"},"user":{"description":"MQTT server authentication user","examples":["johnnysilverhand"],"requiresRestart":true,"title":"User","type":"string"},"version":{"default":4,"description":"MQTT protocol version","examples":[5],"requiresRestart":true,"title":"Version","type":["number","null"]}},"required":["base_topic","server"],"title":"MQTT","type":"object"},"ota":{"properties":{"disable_automatic_update_check":{"default":false,"description":"Zigbee devices may request a firmware update, and do so frequently, causing Zigbee2MQTT to reach out to third party servers. If you disable these device initiated checks, you can still initiate a firmware update check manually.","title":"Disable automatic update check","type":"boolean"},"update_check_interval":{"default":1440,"description":"Your device may request a check for a new firmware update. This value determines how frequently third party servers may actually be contacted to look for firmware updates. The value is set in minutes, and the default is 1 day.","title":"Update check interval","type":"number"}},"title":"OTA updates","type":"object"},"passlist":{"description":"Allow only certain devices to join the network (by ieeeAddr). Note that all devices not on the passlist will be removed from the network!","items":{"type":"string"},"requiresRestart":true,"title":"Passlist","type":"array"},"permit_join":{"default":false,"description":"Allow new devices to join (re-applied at restart)","title":"Permit join","type":"boolean"},"serial":{"properties":{"adapter":{"default":"auto","description":"Adapter type, not needed unless you are experiencing problems","enum":["deconz","zstack","zigate","ezsp","auto"],"requiresRestart":true,"title":"Adapter","type":["string"]},"disable_led":{"default":false,"description":"Disable LED of the adapter if supported","requiresRestart":true,"title":"Disable led","type":"boolean"},"port":{"description":"Location of the adapter. To autodetect the port, set null","examples":["/dev/ttyACM0"],"requiresRestart":true,"title":"Port","type":["string","null"]}},"title":"Serial","type":"object"},"whitelist":{"items":{"type":"string"},"readOnly":true,"requiresRestart":true,"title":"Whitelist (deprecated, use passlist)","type":"array"}},"required":["mqtt"],"type":"object"},"coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extended_pan_id":"0xdddddddddddddddd","pan_id":6754},"permit_join":true,"restart_required":false,"version":"1.21.1"}'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Received MQTT message on 'zigbee2mqtt/bridge/devices' with data '[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"10":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"11":{"bindings":[],"clusters":{"input":["ssIasAce"],"output":["ssIasZone","ssIasWd"]},"configured_reportings":[]},"110":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"12":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]},"configured_reportings":[]},"2":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"3":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"4":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"47":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"5":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"6":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"8":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00124b001949d6a8","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"}]'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Received MQTT message on 'zigbee2mqtt/bridge/groups' with data '[]'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Received MQTT message on 'zigbee2mqtt/bridge/config' with data '{"commit":"4a51e0c0","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.21.1"}'
Zigbee2MQTT:debug 2021-10-01 14:44:13: Received MQTT message on 'zigbee2mqtt/bridge/extensions' with data '[]'
Zigbee2MQTT:info  2021-10-01 14:44:13: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"4a51e0c0","coordinator":{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.21.1"}'`

**Comment by thehiddentruth** [comment]
Suggestions on what to try next?

**Comment by thehiddentruth** [comment]
I ended up solving the issue by change the channel in confirguration.yaml and coordination backup.json from channel 11 to Chanel 25, and that seems to have solved the issue. I can now see all devices.
