### ISSUE TITLE
Hue Dimmer Switch 3241310926211 not sending anything

### ISSUE THREAD

**Issue by hmrc87** [Koenkk/zigbee2mqtt#8921]
## What happened
I successfully paired my remote https://www.zigbee2mqtt.io/devices/324131092621.html#philips-324131092621 with my zigbe2mqtt installation.

The debug log shows nothing related to this device whenever I click something on the switch. It also does not appear in the MQTT zigbee2mqtt topic. BUT it appears on the homeassistant topic since I turned the feature on - is that the problem? I turned it on in order to use it with diy hue

## What did you expect to happen
When I click a button on the switch an Action should be send and be visible in MQTT

## How to reproduce it (minimal and precise)
- Pair the switch
- press any button

## Debug info
Zigbee2MQTT version
1.21.1 commit: eb5750d
Coordinator type ConBee/RaspBee
Coordinator revision 0x26400500
Frontend version0.6.0

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

It sounds like your device might have been added to Zigbee2MQTT but may have not completed its interview, or is too far away from a node that can route back to the co-ordinator.

If you have access to the gui, or the filesystem for Zigbee2MQTT, you can check the interview by clicking on the device and looking in the about screen. If you don't have the gui, you can do this by opening the database.db file in a text editor, then searching for the device.

If you struggle, please post your database.db entry here and we can have a look!

**Comment by hmrc87** [comment]
Thanks, Daniell but the Device finished its interview
![image](https://user-images.githubusercontent.com/1226017/135462642-1a0d6e8e-4bf9-4794-9cd6-feeef199d611.png)

**Comment by hmrc87** [comment]
I tested with two of my Tradfri (round) remotes and see the same behaviour. No data is transmitted from those devices. Lights and Switches though work perfectly fine

**Comment by BigT-CZE** [comment]
Hello @hmrc87 I successfully paired Philips 324131092621. I first reseted it by holding setup button for 10s, waited to join to Zigbee2MQTT and then pressed all buttons for 4s on a front. Then I received message, that device was successfully paired. Now all button presses are logged properly into zigbee2mqtt log

**Comment by hmrc87** [comment]
> Hello @hmrc87 I successfully paired Philips 324131092621. I first reseted it by holding setup button for 10s, waited to join to Zigbee2MQTT and then pressed all buttons for 4s on a front. Then I received message, that device was successfully paired. Now all button presses are logged properly into zigbee2mqtt log

Thanks for the hint - i tried it like 3 times. It pairs, the interview is completed but the intersting thing is that the device has no state in stage.json and does not appear in MQTT.

Now I see the following in the log:
` Failed to configure 'HUE DIMMER SWITCH2', attempt 1 (Error: Bind 0x0017880106eabacb/1 genOnOff from '0x00212effff041184/1' failed (waiting for response TIMEOUT)`

**Comment by hmrc87** [comment]
I actually never got this running. After getting rid of zigbe2mqtt and using the Remote directly with the Phoscon App it works perfectly.

**Comment by shanelord01** [comment]
I have this issue with one of my Hue Dimmer Switches but not the other. 

Tried everything I did with the other one. This unit though I get no battery state, no bind to coordinator. Nothing.

The other one everything shows correctly.
