### ISSUE TITLE
Philips Hue motion sensor not reporting any data

### ISSUE THREAD

**Issue by f-bader** [Koenkk/zigbee2mqtt#893]
I tried to add the Philips Hue motion sensor to zigbee2mqtt (version 1.0.1 (commit #84593a5)) and the device is joined successful.
But after that no data is received from the motion sensor at all.

I then
* restarted zigbee2mqtt with debug on
* removed the motion sensor with "zigbee2mqtt/bridge/config/remove"
* reset the motion sensor itself (10 second press in the setup hole)
* rejoined the motion sensor

Still no change in behaviour. The motion sensor does not send any data.
If I restart it (Short press in the setup hole) it blinks orange for a second and then switches to green.

Debug Log:
https://pastebin.com/YS2gvVu8

Has anybody an idea what I can try to narrow the problem further down.

Thank you.

**Comment by f-bader** [comment]
Maybe the network graph will help

> digraph G {
node[shape=record];
  "0x00124b0018ed111c" [label="{0x00124b0018ed111c|Coordinator|No model information available|online}"];
  "0x00124b0018ed111c" -> "0x84182600000fee7a" [label="30"]
  "0x8418260000100286" [label="{0x8418260000100286|Router|OSRAM Smart+ plug (AB3257001NJ)|offline}"];
  "0x8418260000100286" -> "0x00178801104d9901" [label="148"]
  "0x00158d00024e2a78" [label="{0x00158d00024e2a78|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d00024e2a78" -> "0x00124b0018ed111c" [label="67"]
  "0x00158d00024a732d" [label="{0x00158d00024a732d|EndDevice|Xiaomi Aqara water leak sensor (SJCGQ11LM)|online}"];
  "0x00158d00024a732d" -> "0x8418260000100286" [label="255"]
  "0x84182600000d7bf6" [label="{0x84182600000d7bf6|Router|OSRAM Smart+ plug (AB3257001NJ)|offline}"];
  "0x84182600000d7bf6" -> "0x84182600000fee7a" [label="64"]
  "0x84182600000e78c1" [label="{0x84182600000e78c1|Router|OSRAM Smart+ plug (AB3257001NJ)|offline}"];
  "0x84182600000e78c1" -> "0x84182600000fee7a" [label="58"]
  "0x7cb03eaa00a71253" [label="{0x7cb03eaa00a71253|Router|OSRAM Smart+ plug (AB3257001NJ)|offline}"];
  "0x7cb03eaa00a71253" -> "0x84182600000fee7a" [label="32"]
  "0x0017880110348471" [label="{0x0017880110348471|Router|Philips Hue white A60 bulb E27 (9290011370)|offline}"];
  "0x0017880110348471" -> "0x84182600000fee7a" [label="48"]
  "0x00178801104d9901" [label="{0x00178801104d9901|Router|Philips Hue white A60 bulb E27 (9290011370)|online}"];
  "0x00178801104d9901" -> "0x84182600000fee7a" [label="32"]
  "0x001788011039b157" [label="{0x001788011039b157|EndDevice|Philips Hue dimmer switch (324131092621)|offline}"];
  "0x001788010201c313" [label="{0x001788010201c313|EndDevice|Philips Hue motion sensor (9290012607)|offline}"];
  "0x001788010201c313" -> "0x00178801104d9901" [label="255"]
  "0x00158d00024e5ffe" [label="{0x00158d00024e5ffe|EndDevice|Xiaomi Aqara door & window contact sensor (MCCGQ11LM)|online}"];
  "0x00158d00024e5ffe" -> "0x00124b0018ed111c" [label="46"]
  "0x84182600000fee7a" [label="{0x84182600000fee7a|Router|OSRAM Smart+ plug (AB3257001NJ)|online}"];
  "0x84182600000fee7a" -> "0x00178801104d9901" [label="255"]
}

**Comment by Koenkk** [comment]
Can you try:
- stop zigbee2mqtt
- remove device from `database.db` (note that there could be multiple entries)
- start zigbee2mqtt
- repair the device while having it close to the coordinator
- verify that a `Successfully configured...` message appeared in the log (this is necessary, otherwise it won't work)
- verify that it functions correctly when having it close to the coordinator.

**Comment by f-bader** [comment]
@koenkk Thank you, i will give it a try as soon as I'm home

**Comment by f-bader** [comment]
@Koenkk I tried your steps and was successful. But it works only if the Motion Sensor is really near to the Coordinator (<1m)
As soon as I move it to a location 5m away it stops working. I can see that the motion sensor detects motion (red led) but no messages published to the MQTT broker.

I have two Hue light bulbs in the same room as the motion sensor and have no problem reaching them?
Could that be related to battery?

**Comment by f-bader** [comment]
Yes it was related to the battery. I switch out the battery and now the data is just coming in like crazy ;)

Thanks
