### ISSUE TITLE
GZCGQ01LM not working

### ISSUE THREAD

**Issue by mkania11** [Koenkk/zigbee2mqtt#8931]
## What happened
GZCGQ01LM not working, illuminance_lux show null
## Debug info
Zigbee2MQTT version: 
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II GZCGQ01LM MiJia light intensity sensor
Adapter firmware version: 2019www.

**Comment by kocmocgim** [comment]
same problem
after zigbee network restart

**Comment by kocmocgim** [comment]
![2021-10-02_01-48-42](https://user-images.githubusercontent.com/24375347/135684649-1167ed74-cb49-4f1c-95c2-26913c0acfb9.png)

**Comment by kocmocgim** [comment]
![2021-10-02_01-48-42](https://user-images.githubusercontent.com/24375347/135685790-3cfef061-c753-4ff5-bd42-a74d9564f5e9.png)
re add both properties
