### ISSUE TITLE
BTICINO L4003C

### ISSUE THREAD

**Issue by acaonweb** [Koenkk/zigbee2mqtt#8941]
## Debug info
Zigbee2mqtt
v.1.21.0 (zStack3x0 20210120)

**Comment by Koenkk** [comment]
Issues related to the domitcz integration should be created here https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues

**Comment by acaonweb** [comment]
> Issues related to the domitcz integration should be created here https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues

Sorry, I'm newbie 😄
