### ISSUE TITLE
No issue, but why is manual hass intergration missing in the devices section? 

### ISSUE THREAD

**Issue by Gerard-Oedzes** [Koenkk/zigbee2mqtt#8950]
`Configuration when NOT using Home Assistant MQTT discovery #
Visit the device page (Supported devices, click on the model number) to see the Home Assistant configuration when not using MQTT discovery.`

no information annymore?

**Comment by Koenkk** [comment]
I've removed it because it created a lot of maintenance and was not fully correct. The exposes section provide a better overview of what the device actually exposes.

> Configuration when NOT using Home Assistant MQTT discovery # Visit the device page (Supported devices, click on the model number) to see the Home Assistant configuration when not using MQTT discovery.

Removed this from the docs.
