### ISSUE TITLE
Add support for Zemismart LED light bulb 

### ISSUE THREAD

**Issue by xvrijdag** [Koenkk/zigbee2mqtt#8952]
I finally found a light bulb to replace my dumb light bulb. However, it is currently not supported in Z2M. Would it be possible to add it to the supported devices:

The link to the product:
https://www.aliexpress.com/item/1005002594002993.html

The information when pairing the device:
Device '0x50325ffffea04b2f' with Zigbee model 'TS0502B' and manufacturer name '_TZ3210_psgq7ysz' is NOT supported

The light bulb can be dimmed and the light temperature can be changed.

please let me know if you need additional information.

kind regards,

Xavier

**Comment by Koenkk** [comment]
Already supported in Zigbee2MQTT 1.21.2
