### ISSUE TITLE
Moes 4-Gang Touch switch

### ISSUE THREAD

**Issue by jrb5665** [Koenkk/zigbee2mqtt#8968]
Hi,

First, thanks for all the great work.

I have a 4-Gange variant of the Moes touch switch which is supported up to 3 gang in the moes.js file

I added the follow and it works fine, so I would like to request that it be included in a future release.

`     {
          fingerprint: [{modelID: 'TS0601', manufacturerName: '_TZE200_1ozguk6x'}],
          model: 'ZTS-EU_4gang',
          vendor: 'Moes',
          description: 'Wall touch light switch (4 gang)',
          exposes: [e.switch().withEndpoint('l1').setAccess('state', ea.STATE_SET),
              e.switch().withEndpoint('l2').setAccess('state', ea.STATE_SET), e.switch().withEndpoint('l3').setAccess('state', ea.STATE_SET), 
  	    e.switch().withEndpoint('l4').setAccess('state', ea.STATE_SET)],
          fromZigbee: [fz.ignore_basic_report, fz.tuya_switch],
          toZigbee: [tz.tuya_switch_state],
          meta: {multiEndpoint: true},
          endpoint: (device) => {
              // Endpoint selection is made in tuya_switch_state
              return {'l1': 1, 'l2': 1, 'l3': 1, 'l4': 1};
          },
          configure: async (device, coordinatorEndpoint, logger) => {
              await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
              if (device.getEndpoint(2)) await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
              if (device.getEndpoint(3)) await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
              if (device.getEndpoint(4)) await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
              // Reports itself as battery which is not correct: https://github.com/Koenkk/zigbee2mqtt/issues/6190
              device.powerSource = 'Mains (single phase)';
              device.save();
          },
      },
`

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
