### ISSUE TITLE
ignore missing devices from availability blacklist/passlist and make these lists work with regexp

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#8977]
dev from today

If you add devices to availability blocklist and passlist and then remove the devices from z2m, z2m can't restart because the devices are still mentioned in the list.
I've just been encountering this with availability passlist with named devices.

Could it be possible not to fail when the devices in those lists don't exist (anymore) ?
z2m won't start if availability passlist has a reference to a non-existing device.

Or when you remove a device from z2m, could it be possible to remove their references from the passlists and blocklists ?

I use a device naming related to the device itself (brand/type/role), could it be possible to have regexps in availability passlist/blocklist ?

dealing with regexps would end up in the same kind of logic: check device names and regexps against the actual devices list and only worry about the existing matching ones instead of failing.

**Comment by Koenkk** [comment]
With the new availability feature the availability passlist and blocklist are deprecated (https://github.com/Koenkk/zigbee2mqtt/issues/6281). I suggest to migrate to the new configuration instead. (note this is currently only available in the latest dev branch and will be released with the next z2m release).
