### ISSUE TITLE
Lidl Silvercrest Außensteckdose 2-fach mit Erdspieß

### ISSUE THREAD

**Issue by mblass** [Koenkk/zigbee2mqtt#8999]
When trying to pair the Lidl Outdoor Plug (should be similar to https://www.zigbee2mqtt.io/devices/HG06619.html) the zigbee adapter restarts by sending this log:
zigbee.0 | 2021-10-04 15:15:06.049 | info | terminating with timeout
zigbee.0 | 2021-10-04 15:15:05.022 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-10-04 15:15:05.020 | info | terminating
zigbee.0 | 2021-10-04 15:15:04.523 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-10-04 15:15:04.519 | info | cleaned everything up...
zigbee.0 | 2021-10-04 15:15:04.516 | error | Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 15:15:04.515 | error | TypeError: Cannot read property 'toZigbee' of null at /opt/iobroker/node_modules/iobroker.zigbee/main.js:494:43 at Array.forEach (<anonymous>) at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:452:19)
zigbee.0 | 2021-10-04 15:15:04.514 | error | unhandled promise rejection: Cannot read property 'toZigbee' of null
zigbee.0 | 2021-10-04 15:15:04.513 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-10-04 15:14:08.767 | info | Successfully interviewed '0x60a423fffe154b0d', device has succesfully been paired
zigbee.0 | 2021-10-04 15:13:54.440 | info | Starting interview of '0x60a423fffe154b0d'
zigbee.0 | 2021-10-04 15:13:53.197 | info | Zigbee: allowing new devices to join.

The device is recognized as TS0101 and can be switched. Availability and link quality is not sent.
I did the pairing twice, same restart of adapter, same missing data objects.

Unfortunately I'm not very skilled in programming so "How to support new devices" doesn't work for me.

**Comment by Koenkk** [comment]
Since you are using iobroker, please open an issue here: https://github.com/ioBroker/ioBroker.zigbee/issues
