### ISSUE TITLE
Home Assistant Discovery

### ISSUE THREAD

**Issue by dgomes** [Koenkk/zigbee2mqtt#9]
This:

https://www.home-assistant.io/docs/mqtt/discovery/

Can be seamlessly integrated instead of the wiki page, no ?

**Comment by Koenkk** [comment]
Good idea, going to integrate this :)

**Comment by Koenkk** [comment]
First device done,  I will add more devices soon!

**Comment by Koenkk** [comment]
Things to do: 

- [ ] Support all devices 
- [ ] Update documentation
- [ ] Autogenerate [Integrating with home assistant](https://github.com/Koenkk/zigbee2mqtt/wiki/Integrating-with-home-assistant.io) for those who don't want to use automatic discovery.
