### ISSUE TITLE
Cube joining problem

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee2mqtt#90]
Today I can not join Cube to Shepherd (cc2531)... 

![cube1](https://user-images.githubusercontent.com/8360230/40887735-a6157104-6755-11e8-948b-3c484d9bb327.PNG)

Interview process do not start, only "ZDO:tcDeviceInd" event received.

I've seen similar problems here:
https://github.com/Koenkk/zigbee2mqtt/issues/25#issuecomment-388045812 
https://github.com/zigbeer/zigbee-shepherd/issues/25

**Comment by ciotlosm** [comment]
This is by far the most annoying to pair. I will try again tonight, maybe I can document a pattern

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ciotlosm** [comment]
I was able to pair it. I will try to make a clip and upload to youtube.

**Comment by kirovilya** [comment]
@ciotlosm Thank you. I successfully connect a cube many times before. But now...

**Comment by ciotlosm** [comment]
@kirovilya video will show up here: https://youtu.be/uhMrcIAdGxg . Quality will be low until processing is finished.

**Comment by Koenkk** [comment]
@ciotlosm I've added your video to the wiki: https://github.com/Koenkk/zigbee2mqtt/wiki/Pairing-devices

Can this issue be closed?

**Comment by kirovilya** [comment]
Yes. Thanks to everyone
