### ISSUE TITLE
Edge version not working

### ISSUE THREAD

**Issue by andiukas** [Koenkk/zigbee2mqtt#9013]
After zigbee2mqtt update, not working Edge version!

**Comment by djtrue** [comment]
I confirm. plugin configuration fails validation

**Comment by DavyRoswinkel** [comment]
If getting an error about expecting boolean:

replace
availability: bool?

with:

availability:
  active_timeout: 10
  passive_timeout: 1500

**Comment by andiukas** [comment]
> Should be fixed now, can you check with the latest edge? (please wait at least one hour before updating since build needs to finish first)
update zigbee2mqtt, unistall old Edge version, install Edge version and error with boolean

**Comment by KitHubek** [comment]
Uninstall edge, install again and checked now, and the same error:  expected boolean

**Comment by andiukas** [comment]
work :)
