### ISSUE TITLE
tuya thermostat not supported

### ISSUE THREAD

**Issue by daviddewaard** [Koenkk/zigbee2mqtt#9025]
Hi i have buyed 5 Tuya radiator thermostats , an is try to add them th HA Zigbee2mqqt- edge 

I get the following error : Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_hhrtiq0x'

I looks like this one : https://www.zigbee2mqtt.io/devices/GS361A-H04.html

who can help me fixing this??

**Comment by KitHubek** [comment]
today came  4 pcs. the same valve. At tuya app. i see that this is Siterwell  but in zigbee2mqt mark as unsupported, manufacturer: TZE200_jeaxp72v model: TS0601.
Please add this to supported device

**Comment by daviddewaard** [comment]
I got them working now!,  im using zigbee2mqqt-edge instead of zigbee2mqqt.
the problem was that it did not had the lastest repo,   

to do this:

backup config from: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration
Uninstall: Supervisor → Dashboard → Zigbee2mqtt Edge → Uninstall
Refresh repo: Supervisor → Add-on store → ⋮ → Reload
Re-install: Supervisor → Add-on store → Zigbee2mqtt Edge → Install
Restore config to: Supervisor → Dashboard → Zigbee2mqtt Edge → Configuration

after this they are supported ;-)

**Comment by KitHubek** [comment]
iam using zigbee2mqqt official release stable. How to change it to edge? I have a lot of devices and automations, dont want to lost it

**Comment by KitHubek** [comment]
ok, do it, but when try start service see error: expected boolean.

**Comment by KitHubek** [comment]
i click STOP and then try to start edge. result - error above. I dont see options to disable normal zigbee2mmqt, only can: start, stop, restart and uninstall
