### ISSUE TITLE
zemismart zigbee m515egbztn not change of speed

### ISSUE THREAD

**Issue by Whastie** [Koenkk/zigbee2mqtt#9030]
I have this m515egbztn engine model from zemismart.
This model works in zigbee directly with the coordinator without problems.
Before linking it to the zigbee coordinator, a double press on the raise or lower button changed the motor from slow to fast speed.
But, it seems that by linking it with the zigbee coordinator this speed change functionality has disappeared.
In the properties within the zigbee network if the possibility of changing the speed appears, but it does not pay attention. always runs at slow speed.

![velocidad](https://user-images.githubusercontent.com/89639919/136191122-6ec3c05a-ad86-4fed-8ba0-98f2a3722178.JPG)

Can someone help me, to make it go at the speed that is selected from the zigbee panel?

Thank you

**Comment by robertalexa** [comment]
The device does not actually supported. I have the same device and Zemismart confirmed it is not supported. At the minute, the only motor that supports it is AM43 model.

Unfortunately there is nothing that can be done. This has been discussed before in other threads.

**Comment by Whastie** [comment]
Hello there
Thank you so much .

Just ask more about this topic.
What is strange to me is that when I remove the link with the zigbee2mqtt, it works both speeds.
In other words, the engine is compatible with the two speeds, but the one that is not compatible is the zigbee2mqtt software?

Thanks
