### ISSUE TITLE
send command to different endpoints in single device

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#904]
Hi friends,
I can't find the guide of how can I send "set" or "get" commands to different endpoints of a device. for example 2-gangs Aqara switch. can anyone help me? 
thank you.

**Comment by Koenkk** [comment]
`zigbee2mqtt/[DEVICE_ID]/left/set` and `zigbee2mqtt/[DEVICE_ID]/right/set`

**Comment by msadeghz** [comment]
thank you,
where can I find the complete guides?

**Comment by Koenkk** [comment]
https://koenkk.github.io/zigbee2mqtt/information/mqtt_topics_and_message_structure.html

**Comment by msadeghz** [comment]
I'm confused
I want to send command but {'state':'on'} not works, but just 'on' works
moreover I can't send command to the endpoints based on the way you said

device.js
![device](https://user-images.githubusercontent.com/22853649/54082007-11524a00-4324-11e9-999f-025cb0e203f0.JPG)

toZigbee.js
![to zigbee](https://user-images.githubusercontent.com/22853649/54082010-1adbb200-4324-11e9-8821-6a77366c84f3.JPG)

when I publish "mosquitto_pub -t zigbee2mqtt/0x00124b0014dc270b/set -m {'state':'on'}"
![image](https://user-images.githubusercontent.com/22853649/54082021-465e9c80-4324-11e9-9842-9a16df1d78fd.png)

when I publish "mosquitto_pub -t zigbee2mqtt/0x00124b0014dc270b/a/set -m {'state':'on'}"
![image](https://user-images.githubusercontent.com/22853649/54082032-87ef4780-4324-11e9-8aea-d2ab9dd41cb1.png)

**Comment by Koenkk** [comment]
The postfix has to be in this list (otherwise it will not be parsed): https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/devicePublish.js#L7

Your ep function should e.g. look like:

```js
return {'top': 16, 'center': 17, 'bottom': 18};
```

**Comment by msadeghz** [comment]
thank you @Koenkk , got it.
and how about `'state'` key. when I set the mqtt paylaod `{"state":"on"}` or` {"state":"on",}`, it doesn't work. when I set it `"on"`, it works.

**Comment by Koenkk** [comment]
Can you post a more complete log of this?
