### ISSUE TITLE
Re-pairing Philips Hue dimmer switch V2

### ISSUE THREAD

**Issue by Josov** [Koenkk/zigbee2mqtt#9048]
Pairing a new Philips Hue dimmer switch V2 works without any problem. Switching the device from one to another Zigbee network is difficult. Re-pairing a device which existed before on the network is (for me) impossible. This will only go after changing the Pan id and re-commissioning all devices. I tried to reset the device (10 sec's using a pin). The device pairs again. All looks OK:

![image](https://user-images.githubusercontent.com/41926094/136377351-59cec1be-6ce5-4f08-a8b9-39142a4253d6.png)

But the switch does not work anymore. What I get is this:

Zigbee2MQTT:debug 07-10-2021 13:29:59: Received Zigbee message from 'Overloop HUE dimmer', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  07-10-2021 13:29:59: MQTT publish: topic 'zigbee2mqtt/Overloop HUE dimmer', payload '{"action":null,"battery":null,"device":{"applicationVersion":2,"dateCode":"20200622","friendlyName":"Overloop HUE dimmer","hardwareVersion":1,"ieeeAddr":"0x001788010927908f","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"929002398602","networkAddress":3294,"powerSource":"Battery","softwareBuildID":"2.42.0_h1F5E860","stackVersion":1,"type":"EndDevice","zclVersion":2},"last_seen":"2021-10-07T13:29:59+02:00","linkquality":183}'

Pressing a button generates "action": null, not what I expected.

**Comment by klim123123** [comment]
I'm having the same problem "action": null
but with Hue wall switch module

Model 9290030171
connect it directly to hue hub, to check latest firmware.
re-connected back to z2m, still the same problem
