### ISSUE TITLE
the cluster list of connected device is not complete

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#905]
Hi guys,
I have a device and want to check its compatibility with zigbee2mqtt,
It can connect and pair to the network but the cluster list is not complete. you can check the file attached. 
the device send the alarm by " IASzoneChangeNotifications" which is not in the cluster list.
how can I solve the problem?

**Comment by Koenkk** [comment]
`IASzoneChangeNotifications` is not a cluster, it should be part of the `ssIasZone` cluster.

**Comment by msadeghz** [comment]
excuse me, cluster attributes, I've checked and is not in the attributes of the ssIasZone cluster. a more general question: If I have a device which is HA v1.2 profile compatible which is modified (for example extra attributes with different id and ...) is it possible to modify the firmware to support that device?

**Comment by Koenkk** [comment]
I don't have any experience with this but I guess https://github.com/Koenkk/zcl-id/blob/master/definitions/cluster_defs.json has to be updated.
