### ISSUE TITLE
Xiaomi Door&Window Sensor doesn't send messages properly

### ISSUE THREAD

**Issue by r0bertreh** [Koenkk/zigbee2mqtt#9052]
## What happened
I don't know when this started, but my Xiaomi Aqara Door sensor is just sending data, when other devices in the zibee network are sending data. So when I trigger the sensor, nothing happens. I can repeat that and nothing happens. But when I either push the button or another sensor is sending data I'll get all messages at one. In my network I have 2 TRADFRI lamps and a few Aqara temperature sensors and both groups work properly. I also got today a second aqara sensor and fresh batteries, both haven't changed anything.

## What did you expect to happen
This sensor to work properly.

## How to reproduce it (minimal and precise)
Confifure a Aqara Door sensor. 

## Debug info
Zigbee2MQTT version: 1.12.2
Adapter hardware: ZigStar Stick v4
Adapter firmware version: latest
Channel: 20 (tried a few from 11 to 25)

Here's my first test with a button click: 
`Zigbee2MQTT:debug 2021-10-07 16:20:05: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:debug 2021-10-07 16:20:05: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'true'

Zigbee2MQTT:debug 2021-10-07 16:20:05: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:debug 2021-10-07 16:20:05: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genBasic', data '{"65281":{"1":3005,"10":0,"100":1,"3":30,"4":5032,"5":66,"6":[0,0]},"modelId":"lumi.sensor_magnet.aq2"}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '114'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '126'

Zigbee2MQTT:info  2021-10-07 16:20:05: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '102'`

Second test - triggered the sensor a few times, waited a bit and triggered then another sensor.
`Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'true'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'true'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'true'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_DOOR', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/contact', payload 'false'

Zigbee2MQTT:debug 2021-10-07 16:29:32: Received Zigbee message from 'XIAOMI_CLIMATE_OFFICE', type 'attributeReport', cluster 'genBasic', data '{"modelId":"lumi.weather"}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/voltage', payload '3005'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/battery', payload '100'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/temperature', payload '30'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '120'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '117'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '117'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '114'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '117'

Zigbee2MQTT:info  2021-10-07 16:29:32: MQTT publish: topic 'zigbee2mqtt/XIAOMI_DOOR/linkquality', payload '117'

Zigbee2MQTT:debug 2021-10-07 16:29:36: Received Zigbee message from 'XIAOMI_CLIMATE_OFFICE', type 'attributeReport', cluster 'msTemperatureMeasurement', data '{"measuredValue":1841}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/temperature', payload '18.41'

Zigbee2MQTT:debug 2021-10-07 16:29:36: Received Zigbee message from 'XIAOMI_CLIMATE_OFFICE', type 'attributeReport', cluster 'msRelativeHumidity', data '{"measuredValue":7418}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/temperature', payload '18.41'

Zigbee2MQTT:debug 2021-10-07 16:29:36: Received Zigbee message from 'XIAOMI_CLIMATE_OFFICE', type 'attributeReport', cluster 'msPressureMeasurement', data '{"measuredValue":968,"scale":-1,"scaledValue":9684}' from endpoint 1 with groupID 0

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/temperature', payload '18.41'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/humidity', payload '59.84'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/humidity', payload '74.18'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/humidity', payload '74.18'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/pressure', payload '968'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/pressure', payload '968'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/pressure', payload '968'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/linkquality', payload '156'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/linkquality', payload '159'

Zigbee2MQTT:info  2021-10-07 16:29:36: MQTT publish: topic 'zigbee2mqtt/XIAOMI_CLIMATE_OFFICE/linkquality', payload '159'`

**Comment by Koenkk** [comment]
This is due to https://github.com/Koenkk/zigbee2mqtt/issues/8663
