### ISSUE TITLE
MiJia light intensity sensor pairs but fails the rest (GZCGQ01LM)

### ISSUE THREAD

**Issue by Ferrari2** [Koenkk/zigbee2mqtt#9058]
Hi

I am using zigbee2mqtt under Home Assistant and the pairing seems OK (interview completed = true) and I can see the light sensor device in the zigbee2mqtt UI.

Unfortunately the light sensor doesn't work and I see this error in the log:
error Failed to configure '0x04cf8cdf3c7ccd0c', attempt 2 (Error: Bind 0x04cf8cdf3c7ccd0c/1 genPowerCfg from '0x00124b001949c4d8/1' failed (SRSP - ZDO - bindReq after 6000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))

MiJia light intensity sensor FW: _2019www._

I am running zigbee2mqtt v1.21.2-1

The light sensor works fine many versions ago...

Best ragards
Bjarke

**Comment by silversmarty** [comment]
same thing here : device is paired, but nothing else works 

![2021-10-12 11_03_29-Zigbee2mqtt - Home Assistant](https://user-images.githubusercontent.com/17980711/136926340-4fc3b79f-fbd2-4258-adf5-c0b80e28080b.png)

Logs:

> Zigbee2MQTT:error 2021-10-12 07:29:33: Failed to configure 'z_lumi', attempt 1 (Error: Bind 0x04cf8cdf3c81a4e9/1 genPowerCfg from '0x00212effff074a3d/1' failed (waiting for response TIMEOUT)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:757:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:500:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/xiaomi.js:1251:13)
    at Configure.configure (/app/lib/extension/configure.ts:119:13)
    at Configure.onMQTTMessage_ (/app/lib/extension/configure.ts:60:21))

**Comment by m-novitsky** [comment]
It's the same with me. The three sensors are pairing but not working. Error - as in the first message.

**Comment by Ferrari2** [comment]
Yes, the same here using Zigbee2MQTT v1.22.0-2...

**Comment by m-novitsky** [comment]
The problem was solved by changing the coordinator channel to 15. And by re-pairing all devices :(

**Comment by Ferrari2** [comment]
OK - better than nothing :-)
Where did you exactly change the coordinator channel to 15? My question is just because I can't find the spot :-)

**Comment by m-novitsky** [comment]
zigbee2mqtt/data/configuration.yaml
![image](https://user-images.githubusercontent.com/46490655/141655340-3d456880-9aca-4a7d-a443-0a1d9a6b1a9a.png)

**Comment by Ferrari2** [comment]
It seem like I have an issue concerned the adapter settings as it remains on ch. 11...

Zigbee2MQTT:error 2021-11-14 00:00:44: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2021-11-14 00:00:44: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2021-11-14 00:00:44: - Extended PAN ID: configured=00124b001949c4d8, adapter=dddddddddddddddd
Zigbee2MQTT:error 2021-11-14 00:00:44: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
Zigbee2MQTT:error 2021-11-14 00:00:44: - **Channel List: configured=15, adapter=11**
Zigbee2MQTT:error 2021-11-14 00:00:44: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2021-11-14 00:00:44: If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json.
Zigbee2MQTT:error 2021-11-14 00:00:44: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2021-11-14 00:00:44: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-11-14 00:00:44: Failed to start zigbee
Zigbee2MQTT:error 2021-11-14 00:00:44: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-11-14 00:00:44: Exiting...

**Comment by m-novitsky** [comment]
The key phrase is "If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json." Do it :)

**Comment by DJTerentjev** [comment]
Same issue for me.

**Comment by DJTerentjev** [comment]
Looks like this can help:
https://github.com/Koenkk/zigbee2mqtt/issues/8931
