### ISSUE TITLE
Experimental output works but we need input from attribute

### ISSUE THREAD

**Issue by AlexanderSch90** [Koenkk/zigbee2mqtt#9068]
I used the experimental output feature for read-only attributes, but now I have an IKEA light bulb and would like to control it without using json.

Is it possible?
Can zigbee2mqtt automatic generate the relevant topics for Input?

**Comment by Koenkk** [comment]
What do you mean with:

> is automaticically generatet but zigbee2mqtt/my_bulb/set/brightness i had to generate manual


What do you mean with "the parameter":
> additional question: Is it also possible to set the parameter with true/false instead of on/off?
