### ISSUE TITLE
new mqtt command to shutdown zigbee2mqtt

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#908]
a mqtt cmd and a proper response to SIGTERM to cleanly shutdown zigbee2mqtt would allow to:
- shutdown & compact database.db see https://community.home-assistant.io/t/zigbee2mqtt-getting-rid-of-your-proprietary-zigbee-bridges-xiaomi-hue-tradfri/52108/809?u=lolorc
- flush/close serial so that it restarts without any hangups (just an assumption)

**Comment by Koenkk** [comment]
Looks good, the compacting can be added here: https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/controller.js#L149
