### ISSUE TITLE
Lidl Livarno Lux E27 A60 HG06462A TS0501A _TZ3000_nosnx7im not supported 

### ISSUE THREAD

**Issue by Zarysss** [Koenkk/zigbee2mqtt#9095]
## What happened
I tried to pair this bulb https://zigbee.blakadder.com/Lidl_HG06462A.html it's recognized as:
`{"id":4,"type":"Router","ieeeAddr":"0xbc33acfffeecfe23","nwkAddr":28074,"manufId":4098,"manufName":"_TZ3000_nosnx7im","powerSource":"Mains (single phase)","modelId":"TS0501A","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0501A","manufacturerName":"_TZ3000_nosnx7im","powerSource":1,"zclVersion":3,"appVersion":81,"stackVersion":0,"hwVersion":1,`
I found similar problem with that same Zigbee Manufacturer number _TZ3000_nosnx7im but with different bulb 
https://githubmemory.com/repo/Koenkk/zigbee2mqtt/issues/8777
## What did you expect to happen
I think bulb should be recognized as "_TZ3000_7dcddnye"
## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC2652P
Adapter firmware version: 20210319

**Comment by Koenkk** [comment]
Added. 

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
