### ISSUE TITLE
Thermostat valve not supported: model TS0601 manufacturer name '_TZE200_jeaxp72v'

### ISSUE THREAD

**Issue by KitHubek** [Koenkk/zigbee2mqtt#9098]
Iam using HA core, zigbee2mqt official release hass.io

Trying add thermostat valve, and its unsupported.

warn  2021-10-10 00:17:24: Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_jeaxp72v'
warn  2021-10-10 00:17:24: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

This is 1:1 the same as Siterwell https://www.zigbee2mqtt.io/devices/GS361A-H04.html Have this one from another seller, and its added ok, and supported full options. 

Please add support for it, so add just manufacturer name  _TZE200_jeaxp72v to GS361A-H04 device and its all
thanks

**Comment by Koenkk** [comment]
Added.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
