### ISSUE TITLE
Problems after moving to RPi 4

### ISSUE THREAD

**Issue by TyroTechSoft** [Koenkk/zigbee2mqtt#9102]
Good day!
I have an RPi3 on which I have no problems so far.
I followed the instructions and installed it.

Everything is up to date.

The devices are displayed as "Removed" during pairing via the front end in the logs.

I hope you can help me.

Best regards
Tyro

**Comment by Tonio16** [comment]
Hello

Your description of your problem is not clear at all for me.

Antoine

**Comment by TyroTechSoft** [comment]
My Problem is, i can't add Devices on my RaspberrPi 4.
During pairing, the device reports to the front end with ID 0x ........
But it doesn't show up and it's not connected.

**Comment by Tonio16** [comment]
Don’t use the usb3 port. If not yet done. 

A usb2 hub is also better: usb stick to close of the pi is suffering of some interferences.

Antoine
