### ISSUE TITLE
device MFKZQ01LM  action_from_side/action_to_side always empty at HA level

### ISSUE THREAD

**Issue by QluseQ** [Koenkk/zigbee2mqtt#9103]
What happened - device MFKZQ01LM  action_from_side/action_to_side always empty at HA level, it seems like second message override first which is much more important (all details in there)

What did you expect to happen - get information flip from site X to site Y

How to reproduce it (minimal and precise) - I got many versions of HA, z2mqtt, mosquito servers (1.6 to 2.0.10.X), for me it is always the same issue, and not changed. I got two MFKZQ01LM - the same issue.

Debug info
Zigbee2MQTT version: 1.21.2-1
Adapter hardware: CC2652P
Adapter firmware version: 20210319

Log:
Info MQTT publish: topic 'zigbee2mqtt/0x00158d000530d734', payload '{"action":"flip90","action_angle":null,"action_from_side":5,"action_side":3,"action_to_side":3,"angle":-76.3,"battery":91,"from_side":5,"linkquality":51,"side":3,"to_side":3,"voltage":2985}'
Info MQTT publish: topic 'zigbee2mqtt/0x00158d000530d734', payload '{"action":"","action_angle":null,"action_from_side":null,"action_side":null,"action_to_side":null,"angle":-76.3,"battery":91,"linkquality":51,"side":3,"voltage":2985}'
Info MQTT publish: topic 'zigbee2mqtt/0x00158d000530d734/action', payload 'flip90'

Best Regards,
Q

**Comment by Koenkk** [comment]
This is expected when the HA integration is enabled, see https://www.zigbee2mqtt.io/information/FAQ.html#why-is-the-action-property-always-empty

**Comment by QluseQ** [comment]
Thanks, I did not found that. All seems to work fine!!
