### ISSUE TITLE
Sudden failure connecting to adapter

### ISSUE THREAD

**Issue by VB-ICT** [Koenkk/zigbee2mqtt#9105]
Just purchaced a CC2652RB adapter flashed as controller and several devices.
Installed all the most recent software and everything worked just fine until yesterday. Devices were added so I was very happy.
Running upgraded Buster, latest Python and so on.

I tried everything I could find online to solve the problem, even re-flashed the CC2652RB but the problem stays.

This is the flow whre things go wrong.
I would be gratefull on any info helping me solve this.

![Herdsman fout](https://user-images.githubusercontent.com/6863773/136700127-b6916876-64cd-4c57-b58c-ef26ed56dba8.JPG)

## Debug info
Zigbee2MQTT version: LATEST
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II LATEST
Adapter firmware version: LATEST

**Comment by VB-ICT** [comment]
Hello Koen,
Here is the debug log made this morning.
Hope it gives you a clue, perhaps the CC2652 is defect (after 1 day...)?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.21.2~prestart: zigbee2mqtt@1.21.2
6 info lifecycle zigbee2mqtt@1.21.2~start: zigbee2mqtt@1.21.2
7 verbose lifecycle zigbee2mqtt@1.21.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.21.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.21.2~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.21.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.21.2~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.21.2~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.21.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zigbee2mqtt@1.21.2
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.10.17-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.24.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.21.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.21.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Summer88** [comment]
Hi, same issue, can't start at all,  here's advanced log output:

`tt$ npm start`
```

> zigbee2mqtt@1.21.2 start
> node index.js

Zigbee2MQTT:debug 2021-10-15 12:46:13: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2021-10-15 12:46:13: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-10-15.12-46-12' filename: log.txt
Zigbee2MQTT:debug 2021-10-15 12:46:13: Removing old log directory '/opt/zigbee2mqtt/data/log/2021-10-15.12-24-12'
Zigbee2MQTT:info  2021-10-15 12:46:13: Starting Zigbee2MQTT version 1.21.2 (commit #44922120)
Zigbee2MQTT:info  2021-10-15 12:46:13: Starting zigbee-herdsman (0.13.149)
Zigbee2MQTT:debug 2021-10-15 12:46:13: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:error 2021-10-15 12:46:34: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-10-15 12:46:34: Failed to start zigbee
Zigbee2MQTT:error 2021-10-15 12:46:34: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-10-15 12:46:34: Exiting...
Zigbee2MQTT:error 2021-10-15 12:46:34: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:63:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.js:116:27)
    at start (/opt/zigbee2mqtt/index.js:95:5)
```

```
ls -l /dev/serial/by-id
totale 0
lrwxrwxrwx 1 root root 13 15 ott 12.45 usb-Silicon_Labs_BV_2010_10_01380FB1-if00-port0 -> ../../ttyUSB0

```

**Comment by tomwagner** [comment]
I upgraded from 1.17.0 to latest 1.21.2 using docker image. And same `Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)`. When i downgrade, need to restore backuped files and physically reconnect dongle otherwise same error appeared. Hope it helps.

```
ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Oct 15 20:11 usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB0
```
