### ISSUE TITLE
homecloud (TUYA) temperature sensor TY-SZT not supported in zigbee2mqtt

### ISSUE THREAD

**Issue by raf610** [Koenkk/zigbee2mqtt#9107]
I have Zigbee2mqtt on raspberry pi zero with CC2531 coordinator.
I bought the nice temperature sensor T&H TY-SZT (model n. TT001-ZA) but I can't pair it in any way on zigbee2mqtt.

it looks like zigbee doesn't see it despite trying to reset it and remove the battery.

Has anyone solved the issue?

thank you

**Comment by raf610** [comment]
no it is not!
I can't find this device in the list of supported devices yet

![photo_2021-10-16_18-14-55](https://user-images.githubusercontent.com/92255582/137594802-6ccb5c42-fea3-41cf-a10b-146d143a71ea.jpg)

**Comment by janpieper** [comment]
Yeah, the picture in the zigbee2mqtt documentation looks wrong. Mine looks exactly like yours.

---

![20211017_122122](https://user-images.githubusercontent.com/426371/137623081-a7d2d235-6c0a-4382-b30b-34a94afd0b49.jpg)

---

![tuya-tt001zav20](https://user-images.githubusercontent.com/426371/137622984-684e1990-7c04-425a-b97b-ff85ccc09543.png)

**Comment by raf610** [comment]
So do you think that to solve the problem I have to replace CC2531 with CC2652P?
It seems strange to me that when I try to pair the devices, Zigbee2mqtt doesn't see anything
