### ISSUE TITLE
Add router device without reflashing?

### ISSUE THREAD

**Issue by RIMperator** [Koenkk/zigbee2mqtt#913]
If I understood the issue 367 correctly, there is no possibility to remove a battery operated device to replace it with a power supplied device (router) to gain additional slots to add devices. Is this really correct or is there any work around that would not need to reflash and repair all existing devices? 
https://github.com/Koenkk/zigbee2mqtt/issues/367

I guess also manually removing devices from configuration.yaml as well as database.db will not have the correct effect?

**Comment by Koenkk** [comment]
Does https://github.com/Koenkk/zigbee2mqtt/issues/900 answer your question?
