### ISSUE TITLE
Xiaomi WS-EUK03 (lumi.switch.n1aeu1) unknown index and zigbee2mqtt crash

### ISSUE THREAD

**Issue by zen2** [Koenkk/zigbee2mqtt#9133]
## What happened
I recently installed a rocker switch Xiaomi WS-EUK03 and everything was working as expected but since a couple of days 
zigbee2mqtt suddenly stop working without nothing in usual info log. Once relaunched that can work few hours but not 24h in a row. So on the last crash I set debug mode on both zigbee2mqtt and zigbee-herdsman.

Note: I have force remove some enddevices that was not responding because of bad localisation/LQI right after I install this new device.

## What did you expect to happen
No crash and no "lumi.switch.n1aeu1: unknown index" messages.

## How to reproduce it (minimal and precise)
Add a lumi.switch.n1aeu1 switch device on zigbee network.

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC1352P-2
Adapter firmware version: coordinator 3.x 20210708
NodeJS: 16.10.0

## Logs
-  [zigbee2mqtt log](https://pastebin.com/GSng05YM) (password: zigbee2mqtt)
- [zigbee2mqtt-herdsman log](https://pastebin.com/PNxxFFJX) (password: zigbee2mqtt)

**Comment by Koenkk** [comment]
The `unknown index` is expected, we don't know yet what these data points mean. The crash isn't but I don't see this in yours logs, can you provide the logs of this?

**Comment by zen2** [comment]
> @zen2 fixed the z2m crash when a converter fails now.
> 
> Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

@Koenkk: thanks a lot for your reactivity. I will try the dev branch as soon as possible to remove my cron task to restart z2m if its process disappears...

**Comment by PeterVoronov** [comment]
> @PeterVoronov seems something goes wrong in the `xiaomi_switch_opple_basic` converter (added in https://github.com/Koenkk/zigbee-herdsman-converters/pull/1318/files) on line: https://github.com/Koenkk/zigbee-herdsman-converters/blob/3979583feb36fafa1369feb1d937fa4a0949c798/converters/fromZigbee.js#L4451 , could you check this?
> 
> Trace:
> 
> ```
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: Received Zigbee message from 'light.ch_amis_pf', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,0,3,40,29,152,57,0,0,0,0,149,57,240,212,3,59,150,57,41,236,19,69,151,57,0,0,0,0,5,33,2,0,154,32,0,9,33,4,25,11,32,0,13,35,22,11,0,0,14,35,0,0,0,0,15,35,55,213,57,177],"type":"Buffer"}}' from endpoint 1 with groupID 0
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: lumi.switch.n1aeu1: unknown index 5 with value 2
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: lumi.switch.n1aeu1: unknown index 154 with value 0
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: lumi.switch.n1aeu1: unknown index 9 with value 6404
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: lumi.switch.n1aeu1: unknown index 11 with value 0
> �[34mZigbee2MQTT:debug�[39m 2021-10-12 10:23:53: lumi.switch.n1aeu1: unknown vtype=35, pos=45


Done. 
Root cause is "unknown **vtype=35**, pos=45"
Please see a https://github.com/Koenkk/zigbee-herdsman-converters/pull/3179

**Comment by fdski** [comment]
Hi, is there a chance of this fix being included in a main branch at any point ?
