### ISSUE TITLE
Woox R7049 smoke detector: Error "Unrecognized DP #8" when triggering manual smoke alarm test

### ISSUE THREAD

**Issue by solid80** [Koenkk/zigbee2mqtt#9147]
## What happened
I paired the Woox R7049 smoke detector with zigbee2mqtt. The interview was successful. Afterwards, the following MQTT message report is generated regularly:
`npm[21960]: Zigbee2MQTT:info  2021-10-13 22:29:28: MQTT publish: topic 'zigbee2mqtt/0xb4e3f9fffe9094bf', payload '{"battery_low":false,"linkquality":162,"smoke":false}'`

However, when I press the test alarm button on the device, no MQTT message is generated. Instead I get the following error message in the zigbee2mqtt log:
`npm[21960]: Zigbee2MQTT:warn  2021-10-09 10:12:21: zigbee-herdsman-converters:tuya_smoke: Unrecognized DP #8 with data {"status":0,"transid":27,"dp":8,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[1]}}`

It might be that the message sent from the device is different when triggering a test alarm.

## What did you expect to happen
I expect that a message with payload "smoke: true" is generated.

## How to reproduce it (minimal and precise)
The error can be reproduced by pressing and holding for 3s the test alarm button on the Woox R7049 device.
## Debug info
Zigbee2MQTT version:  Zigbee2MQTT version 1.21.2 (commit #dc2e2a97) / zigbee-herdsman (0.13.149)
Adapter hardware: Slaesh CC2652RB
Adapter firmware version:  `'{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200925,"transportrev":2},"type":"zStack3x0"}'`

**Comment by solid80** [comment]
I've been looking into the herdsman converters, and I found out where the issue is. It should be enough to specify a new Tuya datapoint and use it when parsing the message from Zigbee. It seems that the manual test button is generating a different message than a real smoke detection.
In principle, there are two options here:
1. do not change the MQTT structure: just send "smoke = true" also in case of test. This option would be fine for my application. Assuming that smoke = false is generated when the test is stopped.
2. add a kind of "smoke_test" entry in the MQTT. This would probably require more changes.

**Comment by Koenkk** [comment]
A new guide has been written recently on how to reverse engineer this: https://www.zigbee2mqtt.io/how_tos/how_to_find_tuya_data_points.html

**Comment by solid80** [comment]
Fixed by https://github.com/Koenkk/zigbee-herdsman-converters/pull/3193
