### ISSUE TITLE
Sonoff Zigbee 3.0 Dongle Plus - Device Timeouts

### ISSUE THREAD

**Issue by eximo84** [Koenkk/zigbee2mqtt#9150]
## What happened

Switched over from CC2531 device to new Sonoff Zigbee 3.0 USB Dongle Plus, zigbee2mqtt starts fine and i can see my existing devices populate.  Xiaomi Window and Door Sensors appear to work ok however all lights (Hue, Ikea and Lidl) are refusing to change state either via the HA interface or directly if i publish a set state on command via MQTT.

I have also repaired one of the Lidl lights and can see it disjoins the network and joins again however the light still fails to be controlled.

Export from log here: https://hastebin.com/litijinuza.apache

## What did you expect to happen

Lights to work as they did with the CC2531 coordinator

## Debug info
Zigbee2MQTT version: Zigbee2MQTT version 1.21.2 (commit #4492212)
Adapter hardware: Sonoff Zigbee 3.0 USB Dongle Plus
Adapter firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210120,"transportrev":2},"type":"zStack3x0"}'

**Comment by eximo84** [comment]
Sniff from switching on the Lidl Light

Frame 185: 52 bytes on wire (416 bits), 50 bytes captured (400 bits) on interface \\.\pipe\zboss_sniffer_COM4, id 0
    Interface id: 0 (\\.\pipe\zboss_sniffer_COM4)
        Interface name: \\.\pipe\zboss_sniffer_COM4
    Encapsulation type: IEEE 802.15.4 Wireless PAN (104)
    Arrival Time: Oct 15, 2021 17:30:45.391775000 GMT Summer Time
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1634315445.391775000 seconds
    [Time delta from previous captured frame: 0.266342000 seconds]
    [Time delta from previous displayed frame: 0.266342000 seconds]
    [Time since reference or first frame: 219.206775000 seconds]
    Frame Number: 185
    Frame Length: 52 bytes (416 bits)
    Capture Length: 50 bytes (400 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: wpan:zbee_nwk:zbee_aps:zbee_zcl:zbee_zcl_general.onoff]
IEEE 802.15.4 Data, Dst: 0x5f4a, Src: 0x0000
    Frame Control Field: 0x8861, Frame Type: Data, Acknowledge Request, PAN ID Compression, Destination Addressing Mode: Short/16-bit, Frame Version: IEEE Std 802.15.4-2003, Source Addressing Mode: Short/16-bit
        .... .... .... .001 = Frame Type: Data (0x1)
        .... .... .... 0... = Security Enabled: False
        .... .... ...0 .... = Frame Pending: False
        .... .... ..1. .... = Acknowledge Request: True
        .... .... .1.. .... = PAN ID Compression: True
        .... .... 0... .... = Reserved: False
        .... ...0 .... .... = Sequence Number Suppression: False
        .... ..0. .... .... = Information Elements Present: False
        .... 10.. .... .... = Destination Addressing Mode: Short/16-bit (0x2)
        ..00 .... .... .... = Frame Version: IEEE Std 802.15.4-2003 (0)
        10.. .... .... .... = Source Addressing Mode: Short/16-bit (0x2)
    Sequence Number: 139
    Destination PAN: 0x1a62
    Destination: 0x5f4a
    Source: 0x0000
    [Extended Source: TexasIns_00:18:df:5b:6c (00:12:4b:00:18:df:5b:6c)]
    [Origin: 7]
ZigBee Network Layer Data, Dst: 0x0f62, Src: 0x0000
    Frame Control Field: 0x0648, Frame Type: Data, Discover Route: Enable, Security, Source Route Data
        .... .... .... ..00 = Frame Type: Data (0x0)
        .... .... ..00 10.. = Protocol Version: 2
        .... .... 01.. .... = Discover Route: Enable (0x1)
        .... ...0 .... .... = Multicast: False
        .... ..1. .... .... = Security: True
        .... .1.. .... .... = Source Route: True
        .... 0... .... .... = Destination: False
        ...0 .... .... .... = Extended Source: False
        ..0. .... .... .... = End Device Initiator: False
    Destination: 0x0f62
    Source: 0x0000
    Radius: 30
    Sequence Number: 61
    [Extended Source: TexasIns_00:18:df:5b:6c (00:12:4b:00:18:df:5b:6c)]
    [Origin: 7]
    Source Route, Length: 1
        Relay Count: 1
        Relay Index: 0
        Relay 1: 0x5f4a
    ZigBee Security Header
        Security Control Field: 0x28, Key Id: Network Key, Extended Nonce
            ...0 1... = Key Id: Network Key (0x1)
            ..1. .... = Extended Nonce: True
        Frame Counter: 17924
        Extended Source: TexasIns_00:18:df:5b:6c (00:12:4b:00:18:df:5b:6c)
        Key Sequence Number: 0
        Message Integrity Code: 5385af78
        [Key: 01030507090b0d0f00020406080a0c0d]
        [Key Label: ]
ZigBee Application Support Layer Data, Dst Endpt: 1, Src Endpt: 1
    Frame Control Field: Data (0x00)
        .... ..00 = Frame Type: Data (0x0)
        .... 00.. = Delivery Mode: Unicast (0x0)
        ..0. .... = Security: False
        .0.. .... = Acknowledgement Request: False
        0... .... = Extended Header: False
    Destination Endpoint: 1
    Cluster: On/Off (0x0006)
    Profile: Home Automation (0x0104)
    Source Endpoint: 1
    Counter: 249
ZigBee Cluster Library Frame
    Frame Control Field: Cluster-specific (0x01)
        .... ..01 = Frame Type: Cluster-specific (0x1)
        .... .0.. = Manufacturer Specific: False
        .... 0... = Direction: Client to Server
        ...0 .... = Disable Default Response: False
    Sequence Number: 3
    Command: Off (0x00)

**Comment by eximo84** [comment]
Ah well now ive done myself in.  Flashed the CC2531 back to the latest 1.2 source routing and now everything is really laggy and i am getting no network route errors.  Knew something would go wrong.

**Comment by Koenkk** [comment]
Could you give me the `pcapng` file + network key?

**Comment by Koenkk** [comment]
- What firmware were you using on the cc2531? (1.2 or 3.0 firmware)
- Can you also provide a sniff when you repair a device and fail to control it aferwards
- To be sure, can you also upgrade the fw of your sonoff? You can download the latest from here: https://www.zigbee2mqtt.io/information/supported_adapters.html

**Comment by eximo84** [comment]
> - What firmware were you using on the cc2531? (1.2 or 3.0 firmware)
> 
> - Can you also provide a sniff when you repair a device and fail to control it aferwards
> 
> - To be sure, can you also upgrade the fw of your sonoff? You can download the latest from here: https://www.zigbee2mqtt.io/information/supported_adapters.html

1.2 latest version on the CC2531. 

Last night I decided to keep the sonoff plugged in and see if things worked them selves out. I assumed it would be fairly quick as when switching back to the CC2531 everything responded instantly. 

Anyway after leaving it overnight all the sensors and lights appear to be working ok. Any that had a lag or delay I put into pairing mode and let them leave and rejoin and so far no problems. 

Only problematic device was a xiaomi Aqara motion sensor which was showing ok in zigbee but in HA wasn't working. Had to remove that and readd it again. 

I will look to flash the sonoff with the latest if you think that will help stability and speed?

I think these timeouts might just be me being impatient so I'm sorry if that is the case. I am new to zigbee so assumed it would be quicker.
