### ISSUE TITLE
BRT-100-TRV temperature accuracy

### ISSUE THREAD

**Issue by michalk-k** [Koenkk/zigbee2mqtt#9158]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/9155

<div type='discussions-op-text'>

<sup>Originally posted by **michalk-k** October 14, 2021</sup></div>

## What happened
Moes BRT-100-TRV provides 0.5 degree of Celsius accuracy. It is mentioned in its manual as well as exposed on its display.
Such accuracy is available for local temperature as well as for programmed temperatures (target)

Z2M exposes temperature without fraction of degrees. In fact it rounds it up (because 0.5 rounded to 1)

## What did you expect to happen
Exposing temperatures with original (0.5) accuracy by Z2M

## How to reproduce it (minimal and precise)
1. set up target temperature on TRV to 22.5
2. observe target temperature in Z2M (23 will be shown)

**Comment by vladi1234** [comment]
Hi @michalk-k,
You are right, it is exactly as you wrote.

> Moes BRT-100-TRV provides 0.5 degree of Celsius accuracy. It is mentioned in its manual as well as exposed on its display.
> Such accuracy is available for local temperature as well as for programmed temperatures (target)
>
> Z2M exposes temperature without fraction of degrees. In fact it rounds it up (because 0.5 rounded to 1)

I also programmed that with rounding on purpose.

Why?

But you cannot expect that TRV Zigbee data transport will work with an accuracy of 0.5 ° C.
This information is not available in the manual either.

In reality, TRV-Zigbee-data transport works with 1 ° C exactly, I tested that.

That's why I also programmed z2m converters with a rounding function.

In my opinion you don't need such an accuracy either.
1 ° exactly is sufficient.
I am fully satisfied with the BRT-100-TRV.

**Comment by michalk-k** [comment]
If TRV doesn't send data with 0.5 degree, why to round it at all?

**Comment by vladi1234** [comment]
> If TRV doesn't send data with 0.5 degree, why to round it at all?

Do you have an idea how to do better?
Offer that.

**Comment by michalk-k** [comment]
If you lead me to some article about how can I debug communication with zigbee device then I can try it on my own.

However what I was asking above is related to kind of inconsistency in what you wrote. I understood you wrote that the TRV doesn't provide fraction of degree. At the same time you wrote you are rounding those values. I cannot see point of rounding if there are no fraction of units in received data.

**Comment by tieuwe** [comment]
Hi, it seems i have the same question..
In order to program the TRV and to keep the temperature stable, i wonder if it is possible to retrieve a temperature with 1 digit behind the dot (or comma). Currently it makes my automations only able to switch on or off in whole degrees Celcius, which is quite a wide range.. 

So in short:
Is it possible to retrieve a value of the current temparature measured by the TRV with one digit behind the dot (or comma)?

**Comment by vladi1234** [comment]
If you meant local_temperature to read 26.0 ° C, then that is a totally different question. 
I answer yes, it is possible.

**Comment by tieuwe** [comment]
Thanks! Probably that is partly what i meant. 

Imagine there is a separate thermometer next to the TVR
If both indicate exactly 26.0 than it is accurate if the TVR sends 26.0
However..
If the separate thermometer shows 26.3
Is it than possible for the TRV to send a value of 26.3?
Or, as a second best solution, (since values in steps of 0.5 are indicated on the TVR itself) to send a value of 26.5?

**Comment by vladi1234** [comment]
It can only be displayed in the same way as with TVR with 0.5 steps.

**Comment by tieuwe** [comment]
That would still be great! Than we can regulate the temperature with a margin of 0.5 degrees.
Since I don't have the skills to support in programming for Zigbee2MQTT i wonder if this can be achieved with changing settings, or does this require an update in the converter / Zigbee2MQTT?
Thanks again!

**Comment by vladi1234** [comment]
```
local_temperature             With 0.5 ----> yes   Is possible
current_heating_setpoint      With 0.5 ----> no    Not possible
```
**I have already written several times to regulate with 0.5 not possible!!!**

**Comment by tieuwe** [comment]
Appologies for not being very clear.
Would be happy already if I am able to get a reading from the TRV local_temperature with 0.5 precision :)

The only thing is that I don't know how to achieve this..? Can it be achieved simply with settings in Zigbee2MQTT? If so, could somebody point me where I can find it or how to do it? Or does it require programming of the converter / Zigbee2MQTT?

**Comment by vladi1234** [comment]
I've already changed code and made a pull request. It may take a while to finish.

**Comment by vladi1234** [comment]
@tieuwe FYI: It has always worked like this with a number after koma (.5) and now it also works when the temperature is right.
See example:
![image](https://user-images.githubusercontent.com/45510877/146636386-079ddbca-49db-4031-87a8-a085bb197d78.png)

But only whole number is seen more often than (.5).

**Comment by tieuwe** [comment]
Mind is blown...! Just checked it in my own history of the sensor i created of the local temperature attribute and you're right! Very few times it is .5 degrees already. That is weird. Never noticed it before..

[cid:8F503EE0-FD9A-497A-ADB1-EB7DD440CCAC-L0-001]

Don't know what you mean when you say "and now it also works when the temperature is right."

Also i find it strange that the .5 degrees values is skipped almost always.

Any idea why?

Op 18 dec. 2021 om 10:52 heeft Vladimir ***@***.***> het volgende geschreven:

﻿

@tieuwe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftieuwe&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BQRY2Uu4Zh5fplAN6PlF0OazeYfrCL%2FG9flguLg%2Bg6c%3D&reserved=0> FYI: It has always worked like this with a number after koma (.5) and now it also works when the temperature is right.
See example:
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F45510877%2F146636386-079ddbca-49db-4031-87a8-a085bb197d78.png&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6g4CQu%2FkVJxEDCDoLGgxSlDlL9lurXoTEckNwzO%2BsnU%3D&reserved=0>

But only whole number is seen more often than (.5).

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKoenkk%2Fzigbee2mqtt%2Fissues%2F9158%23issuecomment-997178418&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rsrwjLz7Do%2FKgCaS9S4RHBpmuaWxBA2gC3HMxGc1M30%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS3ZNDCBPMPBRHUVKLFNQ3TURRKWDANCNFSM5GBN6TFQ&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LG27NPILmU8S7V2k5HraSTHsZ4KoJX54TvVA2k8sCHo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5JtgYuEdxSi3SIXCng3AgWomMJZMDCNvgNjlAPv8sxw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C40146a41767643f1acc408d9c20c1dd5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637754179554104361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AKjjZSbc6%2FxMl27xdNbxj2QYbb8xIT9hfrhFgngV49A%3D&reserved=0>.

**Comment by vladi1234** [comment]
I have no idea why, but this is definitely not a fault of converter.
Maybe TVR Manufacturers wanted that. Maybe we will get an improvement update.

**Comment by vladi1234** [comment]
> Don't know what you mean when you say "and now it also works when the temperature is right."

I mean, if temperature 20.0 then 20.0 is not displayed but only 20, so it is shortened (zero after koma is not displayed) and if 20.5 then exactly 20.5 is displayed.

**Comment by michalk-k** [comment]
> @tieuwe FYI: It has always worked like this with a number after koma (.5) and now it also works when the temperature is right. See example: ![image](https://user-images.githubusercontent.com/45510877/146636386-079ddbca-49db-4031-87a8-a085bb197d78.png)

I have most recent zigbee2mqtt (1.22.2-1) but in my case those TRVs still report temperatures with 1 degree resolutions. 
What am I missing?
I'm aware about some recent changes in z2m GUI (ie precision setting), but this page for my TRVs is empty.

**Comment by vladi1234** [comment]
It happens very rarely with my two TRVs and the third TRV has never displayed .5.

**Comment by KaHeMu** [comment]
I have observed the same behavior. In very rare cases the local_temperature reported by TRV through z2m comes with a  .5 resolution, i.e. 20.5°C. Whereas by far most of the time the number reported looks like an integer, i.e. 20  
(I'm using z2m ver. 1.22.1 commit: c2b5229)

**Comment by TheDukeSr** [comment]
Tested with MQTT Explorer.
Setting temp change on device itself, and monitor MQTT explorer for results.

Manual set: 16
Explorer report: "current_heating_setpoint": 16
Manual set: 16,5
Explorer report: "current_heating_setpoint": 16
Manual set 17
Explorer report: "current_heating_setpoint": 17
Etc etc..

Tested many times, Not one time a half .5 degree in report. So it seems this device just wont send it out!
Maybe others do send out .5 sometimes, but not the one i tested.
I believe a TRV should export in .5 degrees, but this one just wont. 

Hope this helps understanding why the dev can't fix this in Z2M.
