### ISSUE TITLE
Devices.js file - where is it?

### ISSUE THREAD

**Issue by agoralive** [Koenkk/zigbee2mqtt#9162]
I have updated my system, and once again z2m cannot find my Philips Lamp, I usually input this:

{
zigbeeModel: ['4023330P6'],
model: '4023330P6',
vendor: 'Philips',
description: 'Hue white ambiance suspension Amaze',
meta: {turnsOffAtBrightness1: true},
extend: hue.light_onoff_brightness_colortemp,
ota: ota.zigbeeOTA,
},

Into the devices.js file, and then everything works just fine, BUT where can I find this file in the installation on a raspberry pi?

**Comment by sjorge** [comment]
You can create a pr against zigbee-herdsman-converters where you update https://github.com/Koenkk/zigbee-herdsman-converters/blob/f5e1643d9b83cad885c33b4812774d27f2646a43/devices/philips.js#L1159 to list `4023330P6` in addition to `4023330P7`. That should do the trick, then the next time zhc gets merged into zigbee2mqtt dev you can update to that and have the light supported.

**Comment by francisp2** [comment]
on my pi, it is in /opt/zigbee2mqtt/dist/model
