### ISSUE TITLE
Mark group as unavailable when all members are unavailable

### ISSUE THREAD

**Issue by definitio** [Koenkk/zigbee2mqtt#9176]
## Is your feature request related to a problem? Please describe
I have a group of light bulbs. It stays on when bulbs turned off by switch.

## Describe the solution you'd like
I want availability support for groups.

**Comment by eloo** [comment]
I second that request.
It seems with the currently setup is easy to setup a proper behaviour of a group of lights. 

E.g. when the lights are switched off the entity in homeassistant and also the last message in mqtt is "State: On".
Nevertheless that all members are offline. Further the last_seen is also not propagated to the group.

So it would be really nice if we could get an attribute which matches the real state of the group. 

Thanks

**Comment by Lerbaek** [comment]
I third this.
While it could be easily worked around by just creating logical groups in Home Assistant instead, I find that using zigbee2mqtt groups is the only way to have the bulbs act simultaneously, and so, for those of us with physical wall switches, this is actually quite the issue.

**Comment by eloo** [comment]
AFAIK this is still open

**Comment by eloo** [comment]
not stale

**Comment by eloo** [comment]
not stale

**Comment by deviantintegral** [comment]
I was able to get close to this, in that the Sengled bulbs I have can report when they lose power. I set up the following reporting on each bulb, which causes the group to turn off and reset itself when they are turned back on.

Unfortunately, the group still stays available, and HA acts as if commands are successful. With ZHA, the group becomes marked unavailable (after 10 minutes?) so you know you can't send it commands.

While I have most of my physical switches set up with guards, so they are never off, I do have one guest bedroom where I want the physical switch to work so guests can't possibly be woken by a misclick.

<img width="1896" alt="Screen Shot 2022-02-23 at 8 31 47 AM" src="https://user-images.githubusercontent.com/255023/155329786-8dbf31d0-ca86-4ab7-813b-737bbd20c583.png">

**Comment by Koenkk** [comment]
This has now been implemented ([docs](https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/guide/configuration/device-availability.md#groups))

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by definitio** [comment]
Thanks!

**Comment by eloo** [comment]
@Koenkk seems to work as expected 👍 
thanks
