### ISSUE TITLE
Aqara Motion Sensor - Sensor does not report correct data

### ISSUE THREAD

**Issue by Ingo1977** [Koenkk/zigbee2mqtt#918]
Hello,

I use the latest Firmware for the Zigbee Stick. All Aqara sensors seem to work correctly except this Motion sensor. See my result attached here, I already removed the battery, deleted and paired the sensor again, without success. I use the latest Version of the Zigbee Adapter 0.8.9999.

Any idea?
![report](https://user-images.githubusercontent.com/41122855/51563711-74c80b80-1e8d-11e9-9282-0c18d9fad841.jpg)

**Comment by Koenkk** [comment]
Are you using iobroker?

**Comment by Ingo1977** [comment]
Yes, I use IOBroker.

**Comment by Koenkk** [comment]
This is the zigbee2mqtt issue tracker, please open this issue on the iobroker issue tracker.
