### ISSUE TITLE
Blitzwolf SHP-13 not pairing - unsupported device

### ISSUE THREAD

**Issue by hrosak88** [Koenkk/zigbee2mqtt#9187]
Hi! I have several zigbee plugs blitzwolf shp-13. All worked well, but now some of them stopped working. I cannot pair them again, it shows unsupported device :-(

Version: zigbee2mqtt stable 1.21.2-1
Coordinator: slaesh CC2652RB

Thank you for your help.

**Comment by Nenodema** [comment]
Have you fixed your issue? I’m encountering the same issue.

**Comment by hrosak88** [comment]
> Have you fixed your issue? I’m encountering the same issue.
> 
> I have created a new issue for this #11703

Yes, you must update coordinator to newest firmware. Works like a charm 🙂

**Comment by Nenodema** [comment]
> > Have you fixed your issue? I’m encountering the same issue.
> > I have created a new issue for this #11703
> 
> Yes, you must update coordinator to newest firmware. Works like a charm 🙂

Thanks for your reply. Please check my post, it seems that i have a new version of the SHP-13 which is currently not supported.
