### ISSUE TITLE
TS0501B TuYa support

### ISSUE THREAD

**Issue by zhvial** [Koenkk/zigbee2mqtt#9192]
It is stated that TuYa TS0501B is supported by zigbee2mqtt, but i've got "unknown device" error. I've checked tuya.js converter file on github and saw that manufacturerName differs from what i get from my devce. My device reports manufacturerName as 
_TZ3210_9q49basr . Could you please add it to fingerprints so this divice could be suported? 

   fingerprint: [{modelID: 'TS0501B', manufacturerName: '_TZ3000_4whigl8i'},
            {modelID: 'TS0501B', manufacturerName: '_TZ3210_4whigl8i'}],
        model: 'TS0501B',
        description: 'Zigbee light',
        vendor: 'TuYa',
        extend: extend.light_onoff_brightness(),    },
 
![2021-10-17 140436](https://user-images.githubusercontent.com/60042073/137624610-f7775024-1c7a-4dda-8521-2d6954b97c2e.png)

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by zhvial** [comment]
Thank you!
