### ISSUE TITLE
zigbee2mqtt died after pairing Xiaomi Aqara human body movement and illuminance sensor

### ISSUE THREAD

**Issue by YamiFrankc** [Koenkk/zigbee2mqtt#920]
Hello, today I got some of these Xiaomi Aquara movement sensors(they are in the supported devices list), and as soon as tried pairing it, the led in the usb stick turned off.
I lost all control and access to other already paired devices. So i restarted the device and nothing changed. When I remove the stick and plug it in again, the led stays on for a few seconds before turning of.
When I restart the zigbee2mqtt service it doesnt say anything else besides stating that it started.
I tried reflashing the stick, but it still doesnt work.

Has this happened to anyone else? Does anyone have a fix?

**Comment by Landrash** [comment]
Start from the beginning with reflashing the controller and reinstall the software.

Since there's no errror this is most likely the quickest way to get you back up and running.
