### ISSUE TITLE
RGB led strip contoller -> CCT controller

### ISSUE THREAD

**Issue by thve25** [Koenkk/zigbee2mqtt#9206]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/9148

<div type='discussions-op-text'>

<sup>Originally posted by **thve25** October 14, 2021</sup>
Hi,

I have a TuYa TS0503B RGB led strip controller connected to a dual white LED strip. 

I connected channel red to cool white, channel green to warm white, channel blue not connected.

I want zigbee2mqtt to expose this on mqtt as color_temp instead of color_xy, so that i can change color_temp in home assistant.

Is this possible? 

Thanks
</div>

**Comment by michalk-k** [comment]
I doubt you will get functionality of emulated CCT from two random color channels. It's pretty custom requirement.
I suggest  to create mqtt light from data reported by z2m. You had to do that on your own, but I'm afraid it's the only way.

This way I combined R and G channels into CCT light. using xy_colors is kind of similar. I can provide my light entity declaration if you wish
