### ISSUE TITLE
Snzb03 pairs correctly but no communication afterwards 

### ISSUE THREAD

**Issue by jamiekris** [Koenkk/zigbee2mqtt#9210]
Hi,

I have a snzb03 paired to home assistant using zigbee2mqtt that uses a cc2531. One of my snzb03s stopped working, I tried to repair it several times, but each time the pairing goes successfully, however, if I check the device's MQTT info afterwards, the topic corresponding to that particular device has zero history. I manually move in front of the device and it does what it usually does (blinking red light), but this still does not trigger any messages on zigbee2mqtt.

What could be the issue here? Thanks!

Note: other snzb03s seem to be working fine.

**Comment by dsduarte** [comment]
looks like all sonoff zigbee have this issue...
you can track it  here: https://github.com/Koenkk/zigbee2mqtt/issues/8971
