### ISSUE TITLE
HA type error due to null water_leak property in MQTT payload

### ISSUE THREAD

**Issue by pabigot** [Koenkk/zigbee2mqtt#9236]
I've got a [Aqara water leak sensor](https://www.zigbee2mqtt.io/devices/SJCGQ11LM.html#xiaomi-sjcgq11lm), feeding data to Home Assistant (2021.10.6) with zigbee2mqtt version 1.21.2 (both in docker containers).

When the sensor reports Home Assistant (2021.10.6) complains:
```
2021-10-19 09:26:48 INFO (MainThread) [homeassistant.components.mqtt.binary_sensor]
 No matching payload found for entity: AqWS1 water leak with state topic: zigbee2mqtt/AqWS1.
 Payload: '{"battery":100,"battery_low":null,"linkquality":255,"voltage":3055,"water_leak":null}',
 template output: 'None', with value template 'Template("{{ value_json.water_leak }}")'
```

After it's been triggered, the `null` gets replaced by a binary which HA accepts:

```
Zigbee2MQTT:info  2021-10-19 09:31:53: MQTT publish: topic 'zigbee2mqtt/AqWS1', payload '{"battery":100,"battery_low":null,"linkquality":255,"voltage":3055,"water_leak":null}'
Zigbee2MQTT:info  2021-10-19 09:32:45: MQTT publish: topic 'zigbee2mqtt/AqWS1', payload '{"battery":100,"battery_low":false,"linkquality":255,"tamper":false,"voltage":3055,"water_leak":true}'
Zigbee2MQTT:info  2021-10-19 09:33:07: MQTT publish: topic 'zigbee2mqtt/AqWS1', payload '{"battery":100,"battery_low":false,"linkquality":255,"tamper":false,"voltage":3055,"water_leak":false}'
```

It's not obvious to me where the property gets processed, or I'd try to provide a patch to initialize it to the correct type.

**Comment by Koenkk** [comment]
@emontnemery seems that the binary sensor doesn't allow the unknown (`None`) value, is this something that can be supported?

**Comment by emontnemery** [comment]
Sorry, I missed the ping @Koenkk
What do you expect MQTT binary sensor to do if it gets a `None` value?
It is a binary_sensor after all, so can only be on, off or unavailable.

**Comment by Koenkk** [comment]
@emontnemery I would expect its value to be `unknown` similar to e.g. number

**Comment by emontnemery** [comment]
Home Assistant binary sensors only have on+off states. The only other possibility is to set it to unavailable.

**Comment by Koenkk** [comment]
@emontnemery I see, unavailable doesn't cover it imo. Lets leave it like this.

**Comment by emontnemery** [comment]
This will allow binary sensors to have an unknown state: https://github.com/home-assistant/core/pull/60193,

**Comment by Koenkk** [comment]
Awesome! I will close this then since it will be solved in HA
