### ISSUE TITLE
Xiaomi WXKG0[2|3]LM battery level

### ISSUE THREAD

**Issue by b4dpxl** [Koenkk/zigbee2mqtt#925]
Is it possible to get the battery state of the WXKG02LM and WXKG03LM switches in the JSON? I'm using Home Assistant discovery, and it would be good to be able to check the battery state the same as I can with Tradfri devices with the Ikea gateway.

**Comment by jasiek** [comment]
I've discovered that some Xiaomi sensors will only start reporting battery information after being connected for a few hours.

**Comment by jasiek** [comment]
No, the payload is like this:

```
{"humidity":75.59,"linkquality":44,"temperature":6.8,"battery":23,"voltage":2945}
```

I've no idea what battery=23 means though.

**Comment by b4dpxl** [comment]
Hmm, this is for a switch, not a sensor. I wonder if it's different.

**Comment by Koenkk** [comment]
batter = 23%

**Comment by b4dpxl** [comment]
@Koenkk is it possible to get battery state for these switches? devices.js has “fz.xiaomi_battery_3v” for them, which suggests to me that it can receive it. Thanks

**Comment by b4dpxl** [comment]
Ok, thanks for this, and the great work on this project.
