### ISSUE TITLE
Salcar TRV602 / Yet another tuya thermostat not supported

### ISSUE THREAD

**Issue by gulasch** [Koenkk/zigbee2mqtt#9265]
## Information about the device + link
Salcar smart TRV with OLED display
Model ID printed on backside of device is "TRV602"
Log Zigbee model 'TS0601' and manufacturer name '_TZE200_a4bpgplm'

Out of the box z2m does not support the device and exposes nothing.

I bought the device on Amazon.de
https://www.amazon.de/dp/B09BMYJM23/

## Datapoint Research
I run z2m as HA addon, version 1.21.2-1
I tried to follow the howto and while the guide made sense I couldn't really make it work. Then I borrowed a tuya gateway for easy access to the datapoints.
I compared them to some of the existing tuya thermostats, however the only matches seem to be temp_set and temp_current.

Next step would be to test the datapoints, find matching existing converters and adjust the external converter until device works?

EDIT: I won't have much time to fiddle around next 2 weeks, hence documenting my progress. Maybe someone else can jump in and help with external converters.

## Data from Tuya IOT Platform

|Name   |datapoint    |type   |data   |
|--------|--------------|------------|------|
|mode   |1   |enum   |"range": ["auto","manual","off"]   |
|temp_set   |2   |integer   |{"unit": "°C","min": 50,"max": 350,"scale": 1,"step": 5}   |
|temp_current   |3   |integer   |{"unit": "°C","min": -100,"max": 500,"scale": 1,"step": 5}   |
|switch_rapid   |4   |boolean   |{true,false}   |
|countdown_rapid   |5   |integer   |{"unit": "min","min": 0,"max": 720,"scale": 0,"step": 10}   |
|Temp Calib   |101   |   |   |
|work_state   |6   |enum   |{"range": ["closed","opened"]}   |
|Valve   |102   |   |   |
|window_state   |7   |enum   |{"range": ["closed","opened"]}   |
|window_check    |8   |boolean   |{true,false}   |
|child_lock   |12   |boolean   |{true,false}   |
|battery_percentage   |13   |integer   |{"unit": "%","min": 0,"max": 100,"scale": 0,"step": 1}   |
|Fault alarm   |14   |   |   |
|lower_temp   |15   |integer   |{"unit": "°C","min": 50,"max": 150,"scale": 1,"step": 5}   |
|upper_temp   |16   |integer   |{"unit": "°C","min": 200,"max": 350,"scale": 1,"step": 5}   |
|Week program   |17   |   |   |
|Week program Tuesday   |18   |   |   |
|Week program Wednesday   |19   |   |   |
|Week program Thursday   |20   |   |   |
|Week program Friday   |21   |   |   |
|Week program Saturday   |22   |   |   |
|Week program Sunday   |23   |   |   |
|Soft Version   |150   |   |   |

## external converter

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");

const definition = {
    fingerprint: [
        {
            modelID: 'TS0601\u0000',
            manufacturerName: '_TZE200_a4bpgplm'
        },
    ],
    model: 'RV1',
    vendor: 'Salcar',
    description: 'Thermostatic radiator valve',
    supports: 'thermostat, temperature',
    onEvent: onEventSetLocalTime, //was getting no converter for 'commandSetTimeRequest' using tuya.setTime  
    fromZigbee: [
        fz.ignore_basic_report,
        fz.tuya_data_point_dump,
        fz.ignore_tuya_set_time // was getting no converter for 'commandSetTimeRequest' without
    ],
    toZigbee: [
        tz.tuya_data_point_test, // Another debug converter
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [     ],
};

module.exports = definition;

## data/database.db entry of the device
`{"id":55,"type":"EndDevice","ieeeAddr":"deleted","nwkAddr":43874,"manufId":4098,"manufName":"_TZE200_a4bpgplm","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"b�\u0003)\u0011\u0014�\u0004)\u0012\u0015�\u0004)\u0012\u0000\u0000\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0011\u0000\u0000\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0011","65506":31,"65508":1,"modelId":"TS0601","manufacturerName":"_TZE200_a4bpgplm","powerSource":3,"zclVersion":3,"stackVersion":0,"hwVersion":1,"dateCode":"","appVersion":72}}},"binds":[{"cluster":0,"type":"endpoint","deviceIeeeAddress":"deleted","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":72,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1634842731641}`

**Comment by gulasch** [comment]
I ended up returning the device

**Comment by jhf2442** [comment]
Also bought such a device, operating it with Z2M 1.22.2 (1a0a9a6eabf58855d3a6feda60bb79a1c34d17f8)
Is recognized as TuYa / TS0601_thermostat_1
Setting temperature, battery report etc is working out of the box even from HA, but time sync is not working

**Comment by foice** [comment]
I have just added this device to home assistant, but it exposes no entities ... so far I have no idea how to use it ...

**Comment by mattleh** [comment]
Just for clarification Home Assistant ZHA module doesn't use Zigbee2MQTT it uses zigpy so i guess the problem is there.

**Comment by jhf2442** [comment]
there is a (zigbee2)mqtt integration into HA !

**Comment by mattleh** [comment]
i did not deny it. i wanted to clarify for the users that don't know that "ZHA" what a lot of users use on Home Assistant is not related to Zigbee2MQTT but to zigpy. and the people that wrote that it doesn't expose entities probably are using "ZHA". where they would need a custom quirk for it to work.

**Comment by jhf2442** [comment]
Can't speak for OP, but in my case I'm not using ZHA, so my/the issue is with the native zigbee2mqtt integration

**Comment by mh166** [comment]
I'm wondering about the current state: is this device (https://www.amazon.de/dp/B09BMYJM23/) supported by Z2M? Or is it only supported by ZHA using those quirks?

I'm asking, because I can't find this device being listet on the Z2M's [list of compatible devices](https://www.zigbee2mqtt.io/supported-devices/). If it's supported I'm gonna buy it. ;)

**Comment by mh166** [comment]
For others who might be wondering: by buying them I found out they _are_ supported. 😊

**Comment by PeteSSMMSS** [comment]
@mh166 I got the same ones today: https://www.amazon.de/gp/product/B0BHHQYVPT/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

but it seems Z2M don't support them? Are these the same ones you have?

![SCREENSHOT-2022-11-30 at 19-36-38](https://user-images.githubusercontent.com/54634565/204881004-fcfff1d0-e0ab-4a2e-b0d8-bff431a51ee8.png)

**Comment by mh166** [comment]
You're lucky: you got a newer model that is quieter and a lot faster. The newest of my four thermostats is of the same type. Unfortunately, it is not yet in the z2m database. Or at least it wasn't until [my PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5039) got merged. 😉 So with the next release of z2m it should be included, I think.

If you don't want to wait for it, you can add support manually. For that, please follow carefully [this step by step guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/02_support_new_tuya_devices.html).

In step 2, you'll have to provide a `definition` object (starting from line 10) with all the required information about your device. This basic definition from the guide needs to be replaced with this one:

```js
const definition = {
        fingerprint: [
            {modelID: 'TS0601', manufacturerName: '_TZE200_z1tyspqw'},
        ],
        model: 'RV1',
        vendor: 'Salcar',
        description: 'Thermostatic radiator valve',
        whiteLabel: [
            {vendor: 'Unknown/id3.pl', model: 'GTZ06'},
        ],
        onEvent: tuya.onEventSetLocalTime,
        fromZigbee: [fz.ignore_basic_report, fz.ignore_tuya_set_time, fz.haozee_thermostat],
        toZigbee: [
            tz.haozee_thermostat_system_mode, tz.haozee_thermostat_current_heating_setpoint, tz.haozee_thermostat_boost_heating,
            tz.haozee_thermostat_boost_heating_countdown, tz.haozee_thermostat_window_detection,
            tz.haozee_thermostat_child_lock, tz.haozee_thermostat_temperature_calibration, tz.haozee_thermostat_max_temperature,
            tz.haozee_thermostat_min_temperature, tz.haozee_thermostat_preset,
        ],
        exposes: [
            e.battery(), e.child_lock(), e.max_temperature(), e.min_temperature(),
            e.position(), e.window_detection(),
            exposes.binary('window', ea.STATE, 'CLOSED', 'OPEN').withDescription('Window status closed or open '),
            exposes.binary('heating', ea.STATE, 'ON', 'OFF').withDescription('Device valve is open or closed (heating or not)'),
            exposes.climate()
                .withLocalTemperature(ea.STATE).withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
                .withLocalTemperatureCalibration(-30, 30, 0.1, ea.STATE_SET).withPreset(['auto', 'manual', 'off', 'on'],
                    'MANUAL MODE ☝ - In this mode, the device executes manual temperature setting. ' +
                    'When the set temperature is lower than the "minimum temperature", the valve is closed (forced closed). ' +
                    'AUTO MODE ⏱ - In this mode, the device executes a preset week programming temperature time and temperature. ' +
                    'ON - In this mode, the thermostat stays open ' +
                    'OFF - In this mode, the thermostat stays closed')
                .withSystemMode(['auto', 'heat', 'off'], ea.STATE_SET),
            exposes.composite('programming_mode').withDescription('Auto MODE ⏱ - In this mode, ' +
                    'the device executes a preset week programming temperature time and temperature. ')
                .withFeature(exposes.text('monday_schedule', ea.STATE))
                .withFeature(exposes.text('tuesday_schedule', ea.STATE))
                .withFeature(exposes.text('wednesday_schedule', ea.STATE))
                .withFeature(exposes.text('thursday_schedule', ea.STATE))
                .withFeature(exposes.text('friday_schedule', ea.STATE))
                .withFeature(exposes.text('saturday_schedule', ea.STATE))
                .withFeature(exposes.text('sunday_schedule', ea.STATE)),
            exposes.binary('boost_heating', ea.STATE_SET, 'ON', 'OFF').withDescription('Boost Heating: press and hold "+" for 3 seconds, ' +
                'the device will enter the boost heating mode, and the ▷╵◁ will flash. The countdown will be displayed in the APP'),
            exposes.numeric('boost_heating_countdown', ea.STATE_SET).withUnit('min').withDescription('Countdown in minutes')
                .withValueMin(0).withValueMax(1000),
        ],
    };
```

Then, after you added this external converter and restarted z2m, you'll find the thermostat to be available as expected.

Should you not want to go through this hassle manually, you have to wait for the next z2m release. Then it will work out of the box.

**Comment by PeteSSMMSS** [comment]
wow! thank you very much for the detailed instructions, really appreciated it! Just one question, I have the Z2M Addon for Home Assistant; where do I have to add the external .js file? In /config/zigbee2mqtt?

**Comment by PeteSSMMSS** [comment]
Oh cool, just got it working, thanks for the help! In case somebody else is looking with Home Assistant: Place the .js file into  /config/zigbee2mqtt then open Zigbee2MQTT addon, go to settings - extern converter and add the .js (without path), click submit and restart the addon

**Comment by gulasch** [comment]
Awesome work guys!
Great that the TRVs are now supported, I might order some (again) in near
future. I guess the issue can be closed.

PeteSSMMSS ***@***.***> schrieb am Do., 1. Dez. 2022, 17:25:

**Comment by GrohmS2977** [comment]
Unfortunately, I can't manage to program the internal schedule ("monday_schedule" etc). Can anyone help me with the correct syntax for the payload?

**Comment by PavelZav** [comment]
Hi, I ran into the same problem. Can anyone help?
