### ISSUE TITLE
Datek HLU2909K (Apex plug) unavailable for Home Assistant energy astatistics 

### ISSUE THREAD

**Issue by Naguz** [Koenkk/zigbee2mqtt#9294]
## What happened 
Datek HLU2909K (https://www.zigbee2mqtt.io/devices/HLU2909K.html#datek-hlu2909k) does not appear as a source/device for energy tracking in the Home Assistant Energy dashboard/tracking. I'm guessing this has something to do about not having a state class or similar set as described here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics however I'm unable to figure out where I can check if that is the case. 

I saw in another issue that this was enabled as of z2m 1.21, and I'm currently running 1.21.2, but perhaps this device has not gotten the necessary bits added. I tried removing and re-adding the device while running 1.21.2.

## What did you expect to happen
I expected the plug to be available for Home Assistant for energy usage tracking

## How to reproduce it (minimal and precise)
Add the Apex plug (Datek HLU2909K) successfully. Try to add it to the Home Assistant  Grid consumption tracker.

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC2531 
Adapter firmware version: 20190619(?) Source routing

The device does provide relevant energy measurement entities:
![image](https://user-images.githubusercontent.com/3607221/138559112-06143edd-fa11-4dfc-807d-7d7ec4d35d8e.png)

**Comment by jd1900** [comment]
I have several devices which report W usage but not kWh.
And none of them appears in the UI of "Energy Grid".

I have two types:
- DIN power consumption module (412015) by Legrand
- Power switch S1-R (S1-R) by Ubisys

And none of them show up.

**Comment by Naguz** [comment]
Based on what you and I are seeing, I'm guessing z2m has so far only implemented correct reporting of devices reporting a total amount. As far as I understand, HA should now support inclusion of sensors with state class measurement without a Riemann sum integral or similar extra integrations. I might be mistaken here, though.
