### ISSUE TITLE
State topic should be online only if usb stick is found and shepherd is running 

### ISSUE THREAD

**Issue by drogfild** [Koenkk/zigbee2mqtt#930]
Hi,

Currently zigbee2mqtt/bridge/state is 'online' right after Hass.io addon has started. It's online, even if usb stick isn't found and Shepherd fails to start. That means that currently it doesn't indicate if system is really functioning or not. It also fails to indicate if usb stick has been unplugged.

I think that it should be online only after shepherd has successfully started and Zigbee network is functioning. Alternative solution would be to create another state topic for tracking real online status.

**Comment by Koenkk** [comment]
Can you check if this is still present in the latest `-edge`. When I start zigbee2mqtt without the CC2531 it doesn't publish to `zigbee2mqtt/bridge/state`. Log: https://hastebin.com/qisusitoco.sql

**Comment by drogfild** [comment]
Thanks! With latest edge this if fuctioning correctly. Tested multiple ways and even got back online after replugging usb. Good work guys!
