### ISSUE TITLE
Add support for the new Zigbee Management Panel in HA

### ISSUE THREAD

**Issue by leobel96** [Koenkk/zigbee2mqtt#933]
With the last release (0.86), Home Assistant has added a new interesting feature: the [Zigbee Management Panel](https://www.home-assistant.io/blog/2019/01/23/release-86/). It lets you easily control you Zigbee devices from a nice UI without having you to create a custom UI as explained in your wiki. The problem is that the ZMP supports only the devices supported by the zigpy library which are directly controlled by the python substrate of HA. In my opinion, a great feature, would be to make it possible to control zigbee2mqtt from that UI adding a substrate that makes mqtt requests to zigbee2mqtt from that UI or adding support to zigbee2mqtt in [Zigbee Home Automation](https://www.home-assistant.io/components/zha/).

**Comment by sehraf** [comment]
That was my first idea, too, when i read the change-log. [Controlling Zigbee2mqtt via Home Assistant](https://koenkk.github.io/zigbee2mqtt/integration/home_assistant.html) is doing a good job already when it comes to controlling zigbee2mqtt. Maybe this can be extended in the future including auto discovery (as long as HA's mqtt discovery is capable)
