### ISSUE TITLE
Centralite 3156105

### ISSUE THREAD

**Issue by anthr76** [Koenkk/zigbee2mqtt#9334]
## Information about the device + link

Centralite thermostat sometimes provided from Cable Providers. I've recentley gotten my hands on one. I'm a two day user of zigbee and have no idea where to start.

https://community.smartthings.com/t/centralite-ha-thermostat/3317/16
https://www.amazon.com/Centralite-Thermostat-Xfinity-Comcast-3156105/dp/B00IUN4K3C
https://www.manualslib.com/manual/1828381/Centralite-Zigbee-Alliance-Home-3156105.html?page=3#manual

## data/database.db entry of the device

```
       "808 Themostat": {
            "device": {
                "applicationVersion": 2,
                "friendlyName": "808 Themostat",
                "hardwareVersion": 2,
                "ieeeAddr": "0x000d6f0003588aa3",
                "manufacturerID": 49887,
                "manufacturerName": "CentraLite Systems",
                "model": "unknown",
                "networkAddress": 815,
                "powerSource": "Mains (single phase)",
                "type": "EndDevice",
                "zclVersion": 1
            },
            "last_seen": "2021-10-25T21:56:24.625Z",
            "linkquality": 90
        }
    },
    "touchlinkDevices": [],
    "touchlinkScanInProgress": false,
    "touchlinkIdentifyInProgress": false,
    "touchlinkResetInProgress": false,
    "networkGraph": {
        "links": [],
        "nodes": []
    },
    "networkGraphIsLoading": false,
    "groups": [],
    "bridgeState": "online",
    "bridgeConfig": {},
    "bridgeInfo": {
        "commit": "4492212\n",
        "config": {
            "advanced": {
                "adapter_concurrent": null,
                "adapter_delay": null,
                "availability_blacklist": [],
                "availability_blocklist": [],
                "availability_passlist": [],
                "availability_timeout": 0,
                "availability_whitelist": [],
                "cache_state": true,
                "cache_state_persistent": true,
                "cache_state_send_on_startup": true,
                "channel": 11,
                "elapsed": false,
                "ext_pan_id": [
                    221,
                    221,
                    221,
                    221,
                    221,
                    221,
                    221,
                    221
                ],
                "homeassistant_discovery_topic": "homeassistant",
                "homeassistant_legacy_entity_attributes": false,
                "homeassistant_legacy_triggers": true,
                "homeassistant_status_topic": "homeassistant/status",
                "last_seen": "ISO_8601",
                "legacy_api": false,
                "log_directory": "/data/log/%TIMESTAMP%",
                "log_file": "log.txt",
                "log_level": "info",
                "log_output": [
                    "console"
                ],
                "log_rotation": true,
                "log_symlink_current": false,
                "log_syslog": {},
                "pan_id": 6754,
                "report": false,
                "rtscts": false,
                "soft_reset_timeout": 0,
                "timestamp_format": "YYYY-MM-DD HH:mm:ss"
            },
            "ban": [],
            "blocklist": [],
            "device_options": {
                "legacy": false,
                "retain": true
            },
 ```

**Comment by bertabus** [comment]
@anthr76 tried your code and with a little editing got the temperature editable in Homeassistant, mostly. It looks like it's only allowing an "auto" mode where you set both the top and bottom extremes, could be a Homeassistant issue, not sure.
```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['3156105'],
    model: '3156105',
    vendor: 'Centralite',
    description: 'Centralite (xfinity/comcast) zigbee HVAC Thermostat',
    fromZigbee: [fz.battery, fz.thermostat, fz.fan, fz.ignore_time_read],
    toZigbee: [tz.factory_reset, tz.thermostat_local_temperature, tz.thermostat_local_temperature_calibration,
        tz.thermostat_occupied_heating_setpoint, tz.thermostat_occupied_cooling_setpoint,
        tz.thermostat_setpoint_raise_lower, tz.thermostat_remote_sensing,
        tz.thermostat_control_sequence_of_operation, tz.thermostat_system_mode,
        tz.thermostat_relay_status_log, tz.fan_mode, tz.thermostat_running_state], // ,tz.thermostat_temperature_setpoint_hold],
    exposes: [e.battery(),
        // exposes.binary('temperature_setpoint_hold', ea.ALL, true, false)
        // .withDescription('Prevent changes. `false` = run normally. `true` = prevent from making changes.'), 
        exposes.climate().withSetpoint('occupied_heating_setpoint', 10, 30, 0.1).withLocalTemperature()
        .withSystemMode(['heat', 'cool', 'auto', 'off'])
        .withRunningState(['idle', 'heat', 'cool', 'fan_only']).withFanMode(['auto', 'on'])
        .withSetpoint('occupied_cooling_setpoint', 10, 30, 0.1).withLocalTemperatureCalibration(-30, 30, 0.1)],
    meta: {battery: {voltageToPercentage: '3V_1500_2800'}},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const binds = ['genBasic', 'genIdentify', 'genPowerCfg', 'genTime', 'hvacThermostat', 'hvacFanCtrl', 'hvacUserInterfaceCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, binds);

        await reporting.thermostatSystemMode(endpoint);
        await reporting.batteryVoltage(endpoint);
        await reporting.thermostatRunningState(endpoint);
        await reporting.thermostatTemperature(endpoint);
        await reporting.thermostatOccupiedHeatingSetpoint(endpoint);
        await reporting.thermostatOccupiedCoolingSetpoint(endpoint);
        await reporting.fanMode(endpoint);
        // await reporting.thermostatTemperatureSetpointHold(endpoint);
    },
};

module.exports = definition;

```

**Comment by 3h50** [comment]
> [@anthr76](https://github.com/anthr76) tried your code and with a little editing got the temperature editable in Homeassistant, mostly. It looks like it's only allowing an "auto" mode where you set both the top and bottom extremes, could be a Homeassistant issue, not sure.
> 
> const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
> const tz = require('zigbee-herdsman-converters/converters/toZigbee');
> const exposes = require('zigbee-herdsman-converters/lib/exposes');
> const reporting = require('zigbee-herdsman-converters/lib/reporting');
> const extend = require('zigbee-herdsman-converters/lib/extend');
> const e = exposes.presets;
> const ea = exposes.access;
> 
> const definition = {
>     zigbeeModel: ['3156105'],
>     model: '3156105',
>     vendor: 'Centralite',
>     description: 'Centralite (xfinity/comcast) zigbee HVAC Thermostat',
>     fromZigbee: [fz.battery, fz.thermostat, fz.fan, fz.ignore_time_read],
>     toZigbee: [tz.factory_reset, tz.thermostat_local_temperature, tz.thermostat_local_temperature_calibration,
>         tz.thermostat_occupied_heating_setpoint, tz.thermostat_occupied_cooling_setpoint,
>         tz.thermostat_setpoint_raise_lower, tz.thermostat_remote_sensing,
>         tz.thermostat_control_sequence_of_operation, tz.thermostat_system_mode,
>         tz.thermostat_relay_status_log, tz.fan_mode, tz.thermostat_running_state], // ,tz.thermostat_temperature_setpoint_hold],
>     exposes: [e.battery(),
>         // exposes.binary('temperature_setpoint_hold', ea.ALL, true, false)
>         // .withDescription('Prevent changes. `false` = run normally. `true` = prevent from making changes.'), 
>         exposes.climate().withSetpoint('occupied_heating_setpoint', 10, 30, 0.1).withLocalTemperature()
>         .withSystemMode(['heat', 'cool', 'auto', 'off'])
>         .withRunningState(['idle', 'heat', 'cool', 'fan_only']).withFanMode(['auto', 'on'])
>         .withSetpoint('occupied_cooling_setpoint', 10, 30, 0.1).withLocalTemperatureCalibration(-30, 30, 0.1)],
>     meta: {battery: {voltageToPercentage: '3V_1500_2800'}},
>     configure: async (device, coordinatorEndpoint, logger) => {
>         const endpoint = device.getEndpoint(1);
>         const binds = ['genBasic', 'genIdentify', 'genPowerCfg', 'genTime', 'hvacThermostat', 'hvacFanCtrl', 'hvacUserInterfaceCfg'];
>         await reporting.bind(endpoint, coordinatorEndpoint, binds);
> 
>         await reporting.thermostatSystemMode(endpoint);
>         await reporting.batteryVoltage(endpoint);
>         await reporting.thermostatRunningState(endpoint);
>         await reporting.thermostatTemperature(endpoint);
>         await reporting.thermostatOccupiedHeatingSetpoint(endpoint);
>         await reporting.thermostatOccupiedCoolingSetpoint(endpoint);
>         await reporting.fanMode(endpoint);
>         // await reporting.thermostatTemperatureSetpointHold(endpoint);
>     },
> };
> 
> module.exports = definition;

Was the auto mode ever added?  My thermostat is on auto, and z2m reports auto, but ha throws an error because z2m saus only off, heat, cool, and emergency heat are the only modes
