### ISSUE TITLE
TS0601 ZTS-EU_1gang with neutral wire not a router?

### ISSUE THREAD

**Issue by ciB89** [Koenkk/zigbee2mqtt#9346]
## What happened
I have recently bought the following device: https://de.aliexpress.com/item/1005002868874787.html (I have one one-gang and one two-gang switch)

In zigbee2mqtt it is displayed as "ZTS-EU_1gang" / "TS0601". Manufacturer is "_TZE200_amp6tsvy".

## What did you expect to happen
The picture that is displayed is wrong, since it is not a touch panel but a switch. It also a an optional neutral wire which I have attached. Yet, the device is shown as an EndDevice in z2m. In addition, the documentation shows that you should be able to turn on/off the background led which there is no option for in z2m. 
On the packaging under model it says 'ZTS-EUB'. Is this a different device?

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: slaesh CC2652RB 
Adapter firmware version: 20210708

**Comment by ciB89** [comment]
Also from the shop description it should be possible to turn off the status led and bind one switch to another switch.

**Comment by f0gster** [comment]
I've added a new issue #14962, to me it looks the same... Also, there is one more, which to me looks the same - #11665
