### ISSUE TITLE
HEIMAN HS1SA still error on dev branch

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#935]
Hey
I have updated to DEV branch and i get still error when i press the test button of HEIMAN HS1SA .
The workaround works but i thought it suppose to work on dev branch.

https://github.com/Koenkk/zigbee2mqtt/issues/801#issuecomment-457106315
See the log.
https://hastebin.com/sohafohanu.makefile

**Comment by Koenkk** [comment]
It's not included in the dev branch yet, we are still finding the best solution. Please keep an eye on #801.
