### ISSUE TITLE
Automatically try to reconnect when unable to open socket

### ISSUE THREAD

**Issue by martinjuhasz** [Koenkk/zigbee2mqtt#9366]
## Is your feature request related to a problem? Please describe
I'm running slaeshs CC2652RB on a pi and use ser2net to expose it to my zigbee2mqtt docker instance running on another machine in the network. If the pi goes down and comes back up, network connection is lost, or ser2net crashes and reloads, also zigbee2mqtt docker will crash with `Error: Error while opening socket`.

## Describe the solution you'd like
 It would be nice to have an option in the settings to enable zigbee2mqtt to catch this error and gracefully retry.

**Comment by toxuin** [comment]
It’s a legit improvement I’d love to see in zigbee2mqtt.
