### ISSUE TITLE
Child Lock SEA802-Zigbee doesn't work

### ISSUE THREAD

**Issue by maz3max** [Koenkk/zigbee2mqtt#9375]
## What happened
If I set the state exposed in z2m to "unlocked" it really disables the child lock function.
If the device is currently locked, it is unlocked and cannot be locked again until I enable it via z2m.
Setting the state to "lock" doesn't lock the device but rather enable me to lock it manually.

## What did you expect to happen
Z2M knows whether the device is actually locked or not and can change lock state.
(@Chekedaudau confirmed the function to work with Tuya.)

## How to reproduce it (minimal and precise)
* Long Press on Device
* Device shows LC and is locked
* Disable Lock in Z2M
* Device is unlocked
* Long Press on Device
* Lock will not engage
* Enable Lock in Z2M
* Device is not locked
* Long Press on Device
* Device is locked

## Debug info
Zigbee2MQTT version: 1.21.2 commit: 4492212 
Adapter hardware: CC2650P
Adapter firmware version: 20210708

I think the Child Lock State is a different Data ID than we currently use.

Enabling Debug mode doesn't show any reports when engaging child mode manually.
I have the devices and would like to help! (But I don't have the gateway)

**Comment by maz3max** [comment]
I dug deeper and got my hands on a tuya gateway. I discovered following DP IDs using the web site:
| Name (translated)                                    | Name (original)             | DP ID |
|------------------------------------------------------|-----------------------------|-------|
| working condition                                    | working condition           | 3     |
| Window                                               | Window                      | 8     |
| Antifreeze                                           | Antifreeze                  | 10    |
| Temperature calibration                              | Temperature calibration     | 27    |
| Lock                                                 | Lock                        | 40    |
| Switch                                               | Switch                      | 101   |
| Current                                              | Current                     | 102   |
| Setting temperature                                  | Setting temperature         | 103   |
| Heating Time                                         | Heating Time                | 104   |
| Battery level alarm                                  | 电池电量报警                | 105   |
| Away                                                 | Away                        | 106   |
| Programming mode                                     | 编程模式                    | 107   |
| Programming switch                                   | Programming switch          | 108   |
| Programming data (obsolete, don’t delete first)      | 编程数据（作废，先别删）    | 109   |
| Historical data protocol (day-set temperature)       | 历史数据协议（日-设定温度） | 110   |
| System time synchronization                          | 系统时间同步                | 111   |
| Historical data protocol (week-set temperature)      | 历史数据协议（周-设定温度） | 112   |
| Historical data protocol (month-set temperature)     | 历史数据协议（月-设定温度） | 113   |
| Historical data protocol (year-set temperature)      | 历史数据协议（年-设定温度） | 114   |
| Historical data protocol (day-current temperature)   | 历史数据协议（日-当前温度） | 115   |
| Historical data protocol (week-current temperature)  | 历史数据协议（周-当前温度） | 116   |
| Historical data protocol (month-current temperature) | 历史数据协议（月-当前温度） | 117   |
| Historical data protocol (year-current temperature)  | 历史数据协议（年-当前温度） | 118   |
| Historical data protocol (day-motor opening)         | 历史数据协议（日-电机开度） | 119   |
| Historical data protocol (week-motor opening)        | 历史数据协议（周-电机开度） | 120   |
| Historical data protocol (month-motor opening)       | 历史数据协议（月-电机开度） | 121   |
| Historical data protocol (year-motor opening)        | 历史数据协议（年-电机开度） | 122   |
| Programming data (Monday)                            | 编程数据（周一）            | 123   |
| Programming data (Tuesday)                           | 编程数据（周二）            | 124   |
| Programming data (Wednesday)                         | 编程数据（周三）            | 125   |
| Programming data (Thursday)                          | 编程数据（周四）            | 126   |
| Programming data (Friday)                            | 编程数据（周五）            | 127   |
| Programming data (Saturday)                          | 编程数据（周六）            | 128   |
| Programming data (Sunday)                            | 编程数据（周日）            | 129   |
| Water scale proof                                    | Water scale proof           | 130   |

There are only two things different from the z2m code:
* DP 3 is not used
* Heating Time (104) is called valve pos
Is there a reason for that? (@drzony)

I also tested the child lock function in the official app and it works just like in z2m.
Maybe we should rename it to "Enable Child Lock Feature" or something.

**Comment by drzony** [comment]
I was translating it from the documentation from the manufacturer. The main problem here is how thermostats work in Home Assistant, there is no 1 to 1 mapping of the functions. Also my TRV never reported DP 104 (as far as I remember), so I was not able to test it.

**Comment by maz3max** [comment]
> I was translating it from the documentation from the manufacturer. The main problem here is how thermostats work in Home Assistant, there is no 1 to 1 mapping of the functions. Also my TRV never reported DP 104 (as far as I remember), so I was not able to test it.

That sounds great! Looks like this device is already very well supported by z2m. Could you maybe send me this documentation? (max@netz39.de)
I monitored my TRV for the last days using TuYa and it didn't report DP 3 or PD 104.

**Comment by drzony** [comment]
See here: https://github.com/zigpy/zha-device-handlers/pull/576#issuecomment-739243337

**Comment by LorbusChris** [comment]
This is still an issue, please reopen

**Comment by LorbusChris** [comment]
Actually, this might be a firmware issue on the device itself - once the LOCK feature is enabled, the actual locking/unlocking actions do not seem to send any zigbee messages.
