### ISSUE TITLE
	HEIMAN	HS2WD-E bug

### ISSUE THREAD

**Issue by Bartekn86** [Koenkk/zigbee2mqtt#9380]
The "warning" compound type, is not published to MQTT  so domoticz can not see the device, tested with gizmocuz using mqtt explorer so if you could  bring out the 'warning' component type to the homeassistant config
![1](https://user-images.githubusercontent.com/69695376/139272598-28cffc7f-5bba-441d-beee-3af792fa6a98.png)

here we have warning in device name, could you fix it please
![1](https://user-images.githubusercontent.com/69695376/139272943-0f7b1419-0b29-4457-a8cb-f86a4bbcbd12.png)
 ?
![1](https://user-images.githubusercontent.com/69695376/139273610-fed572b1-928a-4f2f-bcbb-5e58d88a91eb.png)

**Comment by Bartekn86** [comment]
Could sb look at the problem please ?

**Comment by Bartekn86** [comment]
hi, Could you look ad the problem   please  ? @Koenkk

**Comment by Koenkk** [comment]
It is not published to home assistant because HA doesn't not provide a proper entity to expose this. It is in fact published to `zigbee2mqtt/bridge/devices` and therefore it shows in the z2m frontend.

**Comment by Bartekn86** [comment]
Thank you for respond, 
So what can we do ?

**Comment by Koenkk** [comment]
I don't know if it can be done in Domticz, but in HA it is possible to send an MQTT message, that would be the easiest way to do this.

**Comment by Bartekn86** [comment]
gizmocuz  from domoticz told that it should be done in HA, i do not have knowlage how to do it ;( could you help with it ? I

**Comment by Koenkk** [comment]
domoticz should be able to send messages to mqtt but im not a domoticz user so i dont know how to do that

**Comment by Bartekn86** [comment]
gizmocuz said that the warning should be added to to HA config, and thats all
https://www.zigbee2mqtt.io/devices/HS2WD-E.html  here is information how to trigger it,   actualy using web interface we can trigger it, there is no posibility to do it by homeasistant.

**Comment by Koenkk** [comment]
The problem is that HA doesn't not support such discover type, so you have to trigger it directly via MQTT.

**Comment by Bartekn86** [comment]
what can we do to make ha supports that discover type ?

**Comment by Koenkk** [comment]
That would be a feature request for HA, but I believe that will be quite difficult, if they would even implement it at all.

I recommend that you send an MQTT message from Domoticz instead, I think the following topic might help you to send a mqtt message from Domitcz: https://domoticz.com/forum/viewtopic.php?t=31462 . The topic and payload to use can be found on https://www.zigbee2mqtt.io/devices/HS2WD-E.html#triggering-the-alarm
