### ISSUE TITLE
last seen not showing up

### ISSUE THREAD

**Issue by sbcrumb** [Koenkk/zigbee2mqtt#9398]
## What happened
New Install just a few devices and last seen of the bulbs is not being reported. 
Availability is set to 60. last seen did prev work in HA on a ZHA with the same devices.
## What did you expect to happen
Last seen to been shown on front end and in home assistant.
## How to reproduce it (minimal and precise)
Link to config file
[https://www.toptal.com/developers/hastebin/efoxavolod.yaml](url)

## Debug info
Zigbee2MQTT version:
Adapter hardware: CircuitSetup CC2652P 
Adapter firmware version: Z-Stack 3.x.0 20210708

**Comment by sbcrumb** [comment]
Ok and is there any difference or does it really just not matter?

**Comment by sjorge** [comment]
I assume the format would be different, but I’ve never enabled it myself.

**Comment by sbcrumb** [comment]
Ok picking one seems to have worked. Thank you.

**Comment by VesleSlotten** [comment]
Well, after upgrading til Zigbee2MQTT version 1.22.1 the “last_seen” attribute is showing up as “disabled by the integration”. 
It’s possible to enable it in the HA UI, but that is a time-consuming way to update this.  
For the “last_seen” attribute it’s not that important for me, but also other attributes are now “disabled by integration”.  

I’m using the illuminance attribute, that comes with the “Aqara human body movement and illuminance sensor” (RTCGQ11LM), in a few automations, and they stopped working until I manually enabled the attribute again.

Would be nice if this could be fixed, unfortunately I don’t have the programming skills required to help out with the coding .

**Comment by Lefuneste83** [comment]
Yes same super annoying issue here. Every time I repair my Zigbee network all my devices show up in HA with basic state information, but with many disabled entities. Considering I am conducting many tests of various coordinators I have to redo it on a daily basis.

In particular : 
For all devices : 
-Last Seen
-Link Quality
-Battery Voltage in Volts (not Battery Level in %)

For Metering Plugs : 
-All the above
-Current Drawn
-Voltage
-Outage Memory

So I have to manually edit, enable the entities one by one, then restart HA. Consider 25+ devices time between 3 and 5 entities to manually enable by hand. This is insane ! The entities do have an associated Payload, it's just that for some obscure reason, HA decides that it is not worth enabling them by default. What am I doing wrong here ? Is there a setting in Z2M to force publish these entities with an active state ? Again there is a Payload behind each of these entities. I can see it in Z2M GUI and in my MQTT broker.

**Comment by gizmocuz** [comment]
From a fresh newby, I also wondered why 'last seen' was always NA, if it's not configured, maybe do not display this line ?
But even better, why not set this to enabled by default (local time)
Not that it would make any difference in the TCP packet being send to the MQTT broker as the MTU is 1500+ bytes
I think it's a great feature to detect if some sensor is still functional
