### ISSUE TITLE
Best Livolo alternative.....

### ISSUE THREAD

**Issue by jvrrr** [Koenkk/zigbee2mqtt#9406]
I found the best Livolo alternative, after a month there is still no one that can help me out.
Please is there someone that can give me some tips/tricks to get this device supported by zigbee2mqtt?
https://github.com/Koenkk/zigbee2mqtt/issues/8911

Thanks!

**Comment by Koenkk** [comment]
Please don't open multiple issues with the same subject, #8911 try following https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html or wait till someone more experienced has time to help.
