### ISSUE TITLE
Belkin Wemo F7C033 OTA updates?

### ISSUE THREAD

**Issue by tmugan** [Koenkk/zigbee2mqtt#9419]
## Is your feature request related to a problem? Please describe
I've resurrected some old Belkin Wemo bulbs now that I have a Zigbee network (Rasp Pi running HomeAssistant and Zigbee2MQTT with a CC2531 USB).  They do not appear on the OTA tab of Z2M (but Hue bulbs do, so it is working).

## Describe the solution you'd like
Any chance of adding this functionality so that they get their firmware updates?

## Describe alternatives you've considered
The Belkin Wemo app does update OTA but it is the unreliable Wemo Zigbee receiver that made me abandon the bulbs in the first place.

**Comment by Koenkk** [comment]
For this you will need to retrieve the firmware files (try e.g. contacting the manufacturer of these devices)
