### ISSUE TITLE
Philips Hue GU10 White Ambiance 5047131P6 / 9290019533

### ISSUE THREAD

**Issue by Fluke242** [Koenkk/zigbee2mqtt#9428]
Hi, I'm new to z2m and got several products already connected. Unfortunately, above mentioned GU10 is marked "unsupported". I'v already found instructions about the mentioned 9290019533 but that's referring to 5309030P9 not mine being  5047131P6: https://githubmemory.com/repo/Koenkk/zigbee2mqtt/issues/8502
Any efforts by resetting the bulb, updating FW via direct-connect via BT and trying to adjust above mentioned instructions to 5047131P6 didn't help.

## Information about the device + link
https://www.philips-hue.com/de-de/p/hue-white-ambiance-buckram-einzelspot-erw/5047131P8
Unfortunately, this leads to 5047131P8 instead of 5047131P6
## data/database.db entry of the device
{"id":8,"type":"Router","ieeeAddr":"0x0017880109785a63","nwkAddr":43426,"manufId":4107,"manufName":"Philips","powerSource":"Mains (single phase)","modelId":"5047131P6","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64514,768],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"5047131P6","manufacturerName":"Philips","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B"}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":3,"dateCode":"20200327","swBuildId":"1.65.11_hB798F2B","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1635688360995}

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

I have added your device fingerprint to the converters. Once the above PR is merged, you can switch to the Dev / Edge branch for device support or wait for a month for the release to Production

**Comment by Fluke242** [comment]
Thanks all!
