### ISSUE TITLE
SRSP - ZDO - mgmtPermitJoinReq after 6000ms Zigbee2Mqtt did only work on one of my two debian systems.

### ISSUE THREAD

**Issue by KartoffelToby** [Koenkk/zigbee2mqtt#9431]
## What happened
Failed to use zigbee2mqtt on a debian based home-server.
On one System i got the error Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'SRSP - ZDO - mgmtPermitJoinReq after 6000ms'

I used the same Docker command and config on both systems:

Both Systems are Debian with Linux XXX 5.10.0-9-amd64 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
i also tried different usb ports

Here is the Log file from the working system i can pair my door sensor: https://pastebin.com/rmhiJT67
And here from the Failing System: https://pastebin.com/H8KTw4JU

## What did you expect to happen
Working on both systems 

## How to reproduce it (minimal and precise)
Here is the problem, i didn't know any differences between the both systems except hardware

## Debug info
Zigbee2MQTT version: 1.21.2-dev and 1.21.2 and 1.20.0
Adapter hardware: Sonoff Zigbee 3.0 USB Dongle Plus
Adapter firmware version: CC1352P2_CC2652P_launchpad_coordinator_20210708

**Comment by azsystem** [comment]
Same issue:

Zigbee2MQTT version
    [1.32.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.32.2) commit: [1ec1e572](https://github.com/Koenkk/zigbee2mqtt/commit/1ec1e572)

Coordinator type
    zStack3x0

Coordinator revision
    20221226

Coordinator IEEE Address
    0x00124b0022xxxxx

Frontend version
    0.6.133

Stats

        Total 37
        By device type
        Router: 22
        End devices: 15
