### ISSUE TITLE
Aqara Switch E1 device options

### ISSUE THREAD

**Issue by k0t3n** [Koenkk/zigbee2mqtt#9434]
Please add support of specific device options  (power outage, operation modes etc.) for the device same as in #3907

## Information about the device + link
[Aqara E1 Switch](https://www.zigbee2mqtt.io/devices/QBKG39LM.html)

## data/database.db entry of the device
..

**Comment by z-x-f** [comment]
Try updating to the latest version.

**Comment by z-x-f** [comment]
Try to use Z2M frontend or use mqtt publish.

**Comment by k0t3n** [comment]
Is there a way to do it declaratively?
