### ISSUE TITLE
Texas Instruments SampleLight

### ISSUE THREAD

**Issue by Raptor5** [Koenkk/zigbee2mqtt#945]
Hi,

I'm trying to add a new device wich as a Texas Instruments SampleLight application. Zigbee2Mqtt pairs with that device but this device can't send any data because it has only following input cluster list
const cId_t zclSampleLight_InClusterList[] =
{
  ZCL_CLUSTER_ID_GEN_BASIC,
  ZCL_CLUSTER_ID_GEN_IDENTIFY,
  ZCL_CLUSTER_ID_GEN_GROUPS,
  ZCL_CLUSTER_ID_GEN_SCENES,
  ZCL_CLUSTER_ID_GEN_ON_OFF
#ifdef ZCL_LEVEL_CTRL
  , ZCL_CLUSTER_ID_GEN_LEVEL_CONTROL
#endif
};
and doesn't have output cluster list. I can basically receive only on off commands.
I have succesfully added an entry into node_modules/zigbee-shepherd-converters/devices.js and Zigbee2Mqtt now recognizes my device.
Next step is to trigger some actions on the device but I can not, becuse it can only receice on/off commands.

What configurations do I need to do to send on/off commands to this device?
I'm also using Domoticz plugin. The plugin did add any new device toDomoticz device list.

Thanks ahead.

**Comment by Koenkk** [comment]
Could you show what you added to `devices.js`? `toZigbee: [tz.on_off]` should allow you to control it.

**Comment by Raptor5** [comment]
This is what I added to devices.js. I'll try it as you said.
    {
        zigbeeModel: ['TI0001          '],
        model: 'Texas',
        vendor: 'SHARsoft',
        description: 'Wireless light',
        supports: 'single',
        fromZigbee: generic.light_onoff_brightness().fromZigbee,
        toZigbee: generic.light_onoff_brightness().toZigbee,
    },

**Comment by Raptor5** [comment]
Device doesn't show up in Domoticz Devices panel.

Here is Zigbee2Mqtt log:

2019-1-26 19:59:36 - debug: Received zigbee message of type 'devInterview' with data '"0x00124b000cc086e0"'
2019-1-26 19:59:36 - warn: Message without device!
2019-1-26 19:59:36 - debug: Received zigbee message of type 'devInterview' with data '"0x00124b000cc086e0"'
2019-1-26 19:59:36 - warn: Message without device!
2019-1-26 20:00:06 - debug: Received zigbee message of type 'devInterview' with data '"0x00124b000cc086e0"'
2019-1-26 20:00:06 - warn: Message without device!
2019-1-26 20:00:06 - debug: Received zigbee message of type 'devIncoming' with data '"0x00124b000cc086e0"' of device 'TI0001          ' (0x00124b000cc086e0)
2019-1-26 20:00:06 - info: Device incoming...
2019-1-26 20:00:06 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
2019-1-26 20:00:06 - debug: Received zigbee message of type 'devStatus' with data '"online"' of device 'TI0001          ' (0x00124b000cc086e0)
2019-1-26 20:02:13 - debug: Received MQTT message on 'zigbee2mqtt/bridge/config/devices' with data '0x00124b000cc086e0'
2019-1-26 20:02:13 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b000cc086e0","type":"Router","model":"Texas","friendly_name":"0x00124b000cc086e0"}]}'
2019-1-26 20:03:10 - debug: Saving state to file /app/data/state.json

**Comment by Koenkk** [comment]
Let's first try to control it via MQTT, afterwards the domticz plugin has to be updated.

Can you try sending to `zigbee2mqtt/0x00124b000cc086e0/set` `ON` or `OFF`.

**Comment by Raptor5** [comment]
Yes. Using zigbee2mqtt/0x00124b000cc086e0/set it works!

**Comment by Koenkk** [comment]
Some custom devices are supported: https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/information/supported_devices.md#custom-devices-diy as the used software is open-source (Texas Instruments SampleLight) I don't see a reason why I can't :smile:
