### ISSUE TITLE
Zigbee2mqtt initial build fail (npm run build contains 2 errors)

### ISSUE THREAD

**Issue by Faustino-ai** [Koenkk/zigbee2mqtt#9453]
## What happened
Zigbee2mqtt refuses to start. Using `npm start` returns error as shown in https://pastebin.com/xQcNbEu4

** The log is as shown in https://pastebin.com/9ymghQm1 **

Tried `npm run build` as mentioned in other threads, however it returns with 2 errors as shown in https://pastebin.com/J8CNsUV7

** The log is as shown in https://pastebin.com/RmFH2SSQ **

## What did you expect to happen
Zigbee2mqtt start as usual. Version 1.19 started without any issue.

## How to reproduce it (minimal and precise)
`npm start` and `npm run build`

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2652P (zzh)
Adapter firmware version: CC2652R_coordinator_20210708

**Comment by danieledwardgeorgehitchcock** [comment]
Have you done what it suggests, and use the `--scripts-prepend-node-path` option?

**Comment by Faustino-ai** [comment]
> Have you done what it suggests, and use the `--scripts-prepend-node-path` option?

I don't think I did that. May I know where to find relevant information on this? I didn't see this suggestion at all.

**Comment by danieledwardgeorgehitchcock** [comment]
It’s in your error logs
