### ISSUE TITLE
the website is full of 404

### ISSUE THREAD

**Issue by bkarlson** [Koenkk/zigbee2mqtt#9463]
I'm new to Z2M, trying to google all the problems I encounter and 99% of the links are dead (404). Examples:

https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#1-determine-location-of-the-adapter-and-checking-user-permissions

https://www.zigbee2mqtt.io/information/configuration.html

... and the same for almost every link mentioned in issues here or on the web elsewhere. 

As I understand, the new version of the website was launched today, but due to oversight the old link structure was not preserved. It's a huge PIA for new users, proper 301/302 redirects should had been established prior transition. Hope this can be fixed.

**Comment by Koenkk** [comment]
See https://github.com/Koenkk/zigbee2mqtt/discussions/9450#discussioncomment-1575717
