### ISSUE TITLE
New webpage yields 404 errors in Google searches

### ISSUE THREAD

**Issue by smokey42** [Koenkk/zigbee2mqtt#9470]
While the new webpage is nice, [cool URIs don't change](https://www.w3.org/Provider/Style/URI). Multiple searches for example `zigbee2mqtt config` now lead to dead pages. Of course you can access the specific pages from the menu, but having dead pages is not good advertising (frustrates users) and leads to a worse ranking in search engines.

Examples of dead pages:

https://www.zigbee2mqtt.io/information/configuration.html
https://www.zigbee2mqtt.io/integration/home_assistant.html
https://www.zigbee2mqtt.io/information/FAQ.html
https://www.zigbee2mqtt.io/how_tos/how_to_secure_network.html

Suggestion:

Place redirectinig HTML files on the old location which specify the canonical new location. After a while (when all search engines updated their index) you can remove those again.

An example can be found in this gist: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by psi-4ward** [comment]
Yes ... see https://github.com/Koenkk/zigbee2mqtt/discussions/9450
