### ISSUE TITLE
Moes HY368 thermostat (TS0601_thermostat) gives errors about unrecognized DP #13 and #115 

### ISSUE THREAD

**Issue by groenmarsmannetje** [Koenkk/zigbee2mqtt#9477]
## What happened

The thermostats frequently raise these errors in the log.

```
zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #13 with data {"status":182,"transid":184,"dp":13,"datatype":5,"fn":0,"data":{"type":"Buffer","data":[0]}}
zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #115 with data {"status":182,"transid":201,"dp":115,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[0]}}
```

## What did you expect to happen

No errors

## How to reproduce it (minimal and precise)

I added to zigbee2mqtt and after that I see the errors in the log file.

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: ZZH
Adapter firmware version: 20210708

**Comment by Sdahl1234** [comment]
I have the same issue. Same thermostat,, version 1.22.0-2

`zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #13 with data {"status":6,"transid":49,"dp":13,"datatype":5,"fn":0,"data":{"type":"Buffer","data":[0]}}

zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #115 with data {"status":6,"transid":74,"dp":115,"datatype":1,"fn":0,"data":{"type":"Buffer","data":[0]}}
`

**Comment by josvink66** [comment]
Same issue here! I think the issue started after the last version.

**Comment by Koenkk** [comment]
A guide can be found here on how to reverse engineer what these data points mean: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#requirements-and-caveats

**Comment by josvink66** [comment]
Thanks @Koenkk hopefully someone can perform the steps. Unfortunately I don't have the Tuya Zigbee Gateway. So I cannot look it up.

**Comment by Enzokot** [comment]
Same here and  I don't have the Tuya Zigbee Gateway too

**Comment by Koterak** [comment]
I checked for myself:
DP 13: 
`Fault alarm`
![image](https://user-images.githubusercontent.com/35494920/143294912-64b404a4-94e0-4206-b801-5671b638df2d.png)

DP 115:
`Window status`
![image](https://user-images.githubusercontent.com/35494920/143295163-b4afa650-7a83-4e55-bcf4-e600ed75f6a2.png)

So probably both are boolean

**Comment by Enzokot** [comment]
Still need fix

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
Keep alive

**Comment by Sdahl1234** [comment]
Now it seems we only need DP13 to be added 👍 
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3992

**Comment by Sdahl1234** [comment]
I have a valve that very often get stuck when it calibrates during battery change.
first it reports:
zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #13 with data {"dp":13,"datatype":5,"data":{"type":"Buffer","data":[0]}}
as soon as its stuck and displays E1 it reports:
zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #13 with data {"dp":13,"datatype":5,"data":{"type":"Buffer","data":[2]}}

E1 is motor fault
E2 is sensor fault

i dont know what data is sends with sensor fault but with only 2 error codes it would be diffrent from 0 and 2

Hope someone can use this information and implement it.

**Comment by Sdahl1234** [comment]
Added the valve to tuya again to verify the fault.

![image](https://user-images.githubusercontent.com/80645006/162169347-1b1d1e91-f1fb-49ce-96c7-07f1d432fbf6.png)

**Comment by Sdahl1234** [comment]
![image](https://user-images.githubusercontent.com/80645006/162170424-e69e5ab3-0105-498e-aca8-2e23e4345b4e.png)

**Comment by Enzokot** [comment]
Keep alive

**Comment by Enzokot** [comment]
The log is clean for me

**Comment by Enzokot** [comment]
Still for me
`zigbee-herdsman-converters:tuyaThermostat: Unrecognized DP #13 with data {"dp":13,"datatype":5,"data":{"type":"Buffer","data":[0]}}`

**Comment by Koenkk** [comment]
@Enzokot see https://github.com/Koenkk/zigbee2mqtt/issues/9477#issuecomment-968699420

**Comment by Enzokot** [comment]
> @Enzokot see [#9477 (comment)](https://github.com/Koenkk/zigbee2mqtt/issues/9477#issuecomment-968699420)

Sorry, but I don't have the Tuya Gateway

**Comment by groenmarsmannetje** [comment]
Reopened. I still see this error in logging
