### ISSUE TITLE
is there any way to unban device banned while deletion

### ISSUE THREAD

**Issue by lotohov** [Koenkk/zigbee2mqtt#9492]
i accidentaly push ban device while removing it from network.
and cant find any way to get them back . putting it on whitelist and reinstalling from scratch doesn help

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531, CC2530, CC26X2R1, CC1352P-2, Conbee II
Adapter firmware version:

**Comment by danieledwardgeorgehitchcock** [comment]
If you edit your configuration.yaml, the blacklist is at the bottom and you should find your device in there

**Comment by lotohov** [comment]
configuration.yaml refer to homeassistant. i just reinstall all from scrath. and dropped mqtt topics related to zigbee2mqtt
