### ISSUE TITLE
Moes BHT-002-GCLZB shows factor 10 too low temperature

### ISSUE THREAD

**Issue by shintomon** [Koenkk/zigbee2mqtt#9505]
The Moes BHT-002-GCLZB with manufacturer _TZE200_ztvwu4nk shows a factor 10 too low value for local_temperature in the details and status tab.
Calibration value and all other things are and work correct.
The temperature is shown correct on the thermostat display and in the smart life app.

**Comment by Westcott1** [comment]
The unsupported _TZE200_ye5jkfsb has the same behaviour.
Although a white label, it uses Moes endpoints.

**Comment by regissg** [comment]
This problem is still there with 1.23.0-dev commit: [6394d0f4].

Has anyone found a solution?

**Comment by chrisazzopardi** [comment]
Still an issue. When can this be fixed?

**Comment by regissg** [comment]
This has been fixed. See [#11980](https://github.com/Koenkk/zigbee2mqtt/issues/11980)
