### ISSUE TITLE
Invalid default value for `frontend.host` when editing in UI

### ISSUE THREAD

**Issue by Hacker-CB** [Koenkk/zigbee2mqtt#9507]
## What happened

There is extra leading space in the UI while editing `frontend.host` parameter:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/4232995/140437772-6689f3bc-a330-4f7d-9b72-25b7d55c6dda.png">

As a result, saved config is invalid:

```yaml
frontend:
  port: 8099
  host: ' 0.0.0.0'
```
## How to reproduce it (minimal and precise)

Just click `submit` in the UI `frontend` tab.

## Debug info

Zigbee2MQTT version: b3e9afaf3ee55e2d62f6775dc0c62e8550b8fef1

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee2mqtt/pull/9508
