### ISSUE TITLE
beacon enabled communication network 

### ISSUE THREAD

**Issue by msadeghz** [Koenkk/zigbee2mqtt#951]
Hi friends,
I've bought a smart switch and socket of a chinese company and want to add them to the network. I used SmartRF packet sniffer and found that the end devices send beacon request and when I use their specific hub, the hub responses to the request. 
is anyway to zigbee2mqtt hub supports beacon communication mode?

**Comment by Koenkk** [comment]
AFAIK this shouldn't be a problem. 

Did you try to pair it with zigbee2mqtt?

**Comment by msadeghz** [comment]
from the end-device side I see the join message and get the network PANID and the network address. I receive "tcDeviceInd" message in hub.
![image](https://user-images.githubusercontent.com/22853649/51823760-93972980-22f5-11e9-8625-c3f91e91859a.png)

**Comment by Koenkk** [comment]
In https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/components/controller.js#L107 you see that that is already done (https://github.com/Koenkk/zigbee-shepherd/blob/master/lib/components/controller.js#L115)
