### ISSUE TITLE
Philips Hue white ambiance E27 800lm (8719514328242) not supported

### ISSUE THREAD

**Issue by Eagleman7** [Koenkk/zigbee2mqtt#9527]
I bought the Philips Hue White Ambiance E27 800 lumen Bluetooth yesterday, however when pairing it with zigbee2mqtt it shows as non supported. It seems the 1100lm version is supported:
![image](https://user-images.githubusercontent.com/4787591/140605524-b94cfbf2-0e79-4fe1-bf3a-7188ac94479f.png)

I would like support for the regular 800lm version.

**Comment by sjorge** [comment]
Can you post the database entry, should be relatively easy to add it.

**Comment by Eagleman7** [comment]
Not sure exactly what you mean, maybe this helps:

![image](https://user-images.githubusercontent.com/4787591/140607001-901e8208-7cab-4fe9-971b-9b052d464a3b.png)
Friendly name
0x001788010b637b8d

**Comment by Eagleman7** [comment]
Thanks for the PR @sjorge

**Comment by Eagleman7** [comment]
@sjorge now that is addded do I need to do anything in zigbee2mqtt to get it to a supported state?

**Comment by sjorge** [comment]
Wait for the next release or switch to the dev release

**Comment by Eagleman7** [comment]
Thanks!
