### ISSUE TITLE
Suggestions for monitoring service

### ISSUE THREAD

**Issue by johntdyer** [Koenkk/zigbee2mqtt#953]
I would like to know how I can test the service to ensure it is in fact up and working.  I currently have jus teh most basic process test but I am hoping you have some suggestions on how I might confirm its working with a functional test via my monitoring tool

**Comment by JLFN** [comment]
You have it here sensor for bridge state https://github.com/Koenkk/zigbee2mqtt/blob/master/docs/integration/home_assistant.md
