### ISSUE TITLE
Moes BRT-100-TRV - programming schedule : how does it works ?

### ISSUE THREAD

**Issue by NebzHB** [Koenkk/zigbee2mqtt#9530]
Hi,

i don't understand how to use the programing part of that valve : 
https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html#programming-mode-composite

it seems the doc have been generated wrongly...

here is what the state looks like : 
![image](https://user-images.githubusercontent.com/28622481/140613926-426052bd-a6b8-40a5-b30b-6b8432311c0b.png)

i've tried to provide a schedule object (as @vladi1234 suggested in the device creation issue #7674) in the set topic (instead of program_saturday or the others) but in z2m interface it's said he doesn't find any converter. (and he doesn't find program_saturday or any others). obvi undefined doesn't work either...

![image](https://user-images.githubusercontent.com/28622481/140614272-552579fc-10e9-4a29-afb3-eabdb1411f7c.png)

how should i use it ?

**Comment by vladi1234** [comment]
Hi,
you cannot use this to set the schedule yet, but only for information on how the schedule is set.
It's not completely finished yet, but I'm working on it.

**Comment by ialtuhov** [comment]
Hi
I'm trying to connect a Moes BRT-100-TRV device, but I get a response - Not supported.
I use Supervisor HA.
In the logs: A message was received from an unsupported device with the Zigbee model "TS 0601" and the manufacturer's name "_tze200_b6wax7g0".

In the list of supported devices, I see that it should be supported.
I'm asking for help, I don't know what to do.

**Comment by vladi1234** [comment]
Hello, I did new PR for schedule today.

With BRT-100-TRV programming mode can now be set directly via fronted.

![Bildschirmfoto vom 2021-11-16 22-08-55](https://user-images.githubusercontent.com/45510877/142257077-9517f4c8-e848-4c3b-92d4-06e531c7e6c1.png)

**Comment by NebzHB** [comment]
great ! what's the topic ?

**Comment by vladi1234** [comment]
???

**Comment by NebzHB** [comment]
the mqtt topic to publish on ? is it programming_mode ? schedule ? (see my first post)

**Comment by vladi1234** [comment]
>Hi,
you cannot use this to set the schedule yet, but only for information on how the schedule is set.
It's not completely finished yet, but I'm working on it.

@NebzHB I have now changed everything, it looks completely different and it works completely differently.

What do you want with (see my first post)?

If you want to know anything, just ask, but be specific!

**Comment by NebzHB** [comment]
my specific question is : what do I have to publish in mqtt in order to change the schedule ?

should i publish :
htis object :
{"programming_mode": "06:00/23°C  11:30/21°C  13:30/22°C  17:30/23°C  06:00/24°C  12:00/23°C  14:30/22°C  17:30/21°C  06:00/19°C  12:30/20°C  14:30/21°C  18:30/20°C"}
in the topic zigbee2mqtt/FRIENDLY_NAME/set ?

how to set saturday/sunday/weekday ?

as there is an holiday preset mode, is there an holiday programming mode ? or an holiday temperature (like the eco one) ?

**Comment by vladi1234** [comment]
>my specific question is : what do I have to publish in mqtt in order to change the schedule ?

Answer to first question.

You don't have to publish anything in MQTT to be able to change schedules. Such a function was not planned.

> With BRT-100-TRV programming mode can now be set directly via fronted.

The answer to the second question is automatically omitted.

**Comment by NebzHB** [comment]
ok, only from the frontend then, not in mqtt.

**Comment by NebzHB** [comment]
my other question are still valid in the frontend, how to separate the weekdays/saturday/sunday ? does max 4 stages/periods means 4 stages/periods mandatory ? if not how to do 3 periods, with a 4th 00:00/00°C ? if not how ?

**Comment by vladi1234** [comment]
> my other question is still valid in the frontend, how to separate the weekdays/saturday/sunday ?

I have already tried to display the days separately, but it does not work, it does not work with conversion.
I've already tried the separator, it doesn't work either.
Fronted mask optically, is unfortunately not yet so flexible to show separation or periods.
You have to use it as it is, all numbers in a row.

**Comment by vladi1234** [comment]
If you only need two or three periods, then the next period must be the same as the last.

`06:00/23°C  11:30/21°C  19:30/22°C  19:30/22°C`

**Comment by NebzHB** [comment]
ok thx

**Comment by vladi1234** [comment]
The important thing is that it works. :)
thx

**Comment by vladi1234** [comment]
Oh by the way @NebzHB  , I just tested it.
It also works great with JSON!

Example:

topic zigbee2mqtt/FRIENDLY_NAME/set

```
{
  "programming_mode": "19:00/23°C  11:30/21°C  13:30/22°C  17:30/23°C  06:00/24°C  12:00/23°C  14:30/22°C  17:30/21°C  06:00/19°C  12:30/20°C  14:30/21°C  18:30/20°C"
}
```

**Comment by NebzHB** [comment]
great ! even more perfect that way !

**Comment by tom-ch1** [comment]
The payload format is not documented on https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html

**Comment by BeFygo** [comment]
> Hi, I am new to zigbee2mqtt and want to configure a weekly schedule for my thermostat TS0601. When I use the above example for 2 or 3 periods and paste this into the workdays_schedule field I allway will get an error message like "Publish set holidays_schedule ... Type Error: can not read properties of undefined. Any Idea how to fix this?

Hey erwano1957,

Publishing the following in MQTT works for me:

topic:
`zigbee2mqtt/YOUR DEVICE NAME/set`

Payload:
`{"schedule": {"week_day": "friday","schedule":"05:00/20 06:00/21 22:00/20 24:00/20"}}`

**Comment by erwano1957** [comment]
Hey,

Thx a lot for your reply ... I will give it a try later on.



Von: BeFygo ***@***.***>
Gesendet: Freitag, 30. Dezember 2022 20:20
An: Koenkk/zigbee2mqtt ***@***.***>
Cc: erwano1957 ***@***.***>; Comment ***@***.***>
Betreff: Re: [Koenkk/zigbee2mqtt] Moes BRT-100-TRV - programming schedule : how does it works ? (Issue #9530)


Hi, I am new to zigbee2mqtt and want to configure a weekly schedule for my thermostat TS0601. When I use the above example for 2 or 3 periods and paste this into the workdays_schedule field I allway will get an error message like "Publish set holidays_schedule ... Type Error: can not read properties of undefined. Any Idea how to fix this?

Hey erwano1957,

Publishing the following in MQTT works for me:

topic:
zigbee2mqtt/YOUR DEVICE NAME/set

Payload:
{"schedule": {"week_day": "friday","schedule":"05:00/20 06:00/21 22:00/20 24:00/20"}}

-
