### ISSUE TITLE
Cannot change reporting interval of Tuya TS011F mains socket switch with monitoring

### ISSUE THREAD

**Issue by kbfifi** [Koenkk/zigbee2mqtt#9536]
## What happened
Changing the reporting interval settings of Tuya TS011F mains socket switch has no effect

## What did you expect to happen
I expect to see more frequent MQTT updates of the monitoring state of this device

## How to reproduce it (minimal and precise)
I tried to add minimal interval settings like so:
![Schermafbeelding 2021-11-06 201517](https://user-images.githubusercontent.com/35601089/140621239-ecd54184-19e8-4b17-854b-02ee01e6d2dc.jpg)

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: CC2531
Adapter firmware version: flashed with CC2531_DEFAULT_20201127 
TS011F, appVersion 69
![Schermafbeelding 2021-11-06 202754](https://user-images.githubusercontent.com/35601089/140621558-d76e58f8-f66e-4c50-97ad-a9cbd6efc6c3.jpg)

**Comment by Koenkk** [comment]
appVersion 69 doesn't support reporting so this cannot be solved from z2m.
