### ISSUE TITLE
Green Wave Meter Reality Reader RA11D5

### ISSUE THREAD

**Issue by JLFN** [Koenkk/zigbee2mqtt#955]
I have Green Wave Meter  Reality Reader RA11D51-A11-GR  that i cant get in with 2.4Ghz i tried different channels.
I have open it and i has an CC2530 256kb chip .
Please give me any tips.
This product.
https://www.ebay.de/itm/Green-Wave-Meter-Reader-RA11D51-Nr-217-51-/322743925739

**Comment by JLFN** [comment]
Looks like its running on Channel 15.
![image](https://user-images.githubusercontent.com/22047436/51857968-e263b400-2333-11e9-9e35-a48134621d73.png)

**Comment by khzd** [comment]
You have to switch to channel 15 to pair :( se configuration.yaml

**Comment by JLFN** [comment]
> You have to switch to channel 15 to paire :( se configuration.yaml

Yes iam running Chanel 15 now what about the panid ?

```.yaml 
  # Optional: ZigBee pan ID
  pan_id: 0x1a62
```

**Comment by JLFN** [comment]
@Koenkk  You have any tips?

**Comment by JLFN** [comment]
@Koenkk Do you have any tips?
![image](https://user-images.githubusercontent.com/22047436/51862817-bd753e00-233f-11e9-82bc-7dc03a89c814.png)

**Comment by Koenkk** [comment]
@JLFN looks similar, are you unable to pair it with zigbee2mqtt?

**Comment by JLFN** [comment]
@Koenkk I cant pair, i cant even get incomming device. No changed when i start debug mode neither. I wonder if its something that need extPanId? Do you have any tips where to begin?

**Comment by ptvoinfo** [comment]
@JLFN It is necessary to capture traffic between a working coordinator and the device like we did it for Livolo.

**Comment by JLFN** [comment]
@ptvoinfo cc2531 or cc2530 with zigbee2mqtt or you do mean the official gateway of the vendor?

**Comment by ptvoinfo** [comment]
@JLFN I mean the official gateway.

**Comment by JLFN** [comment]
@ptvoinfo  I have recorded the gateway with the device . Please help me out
[Greenwave reader.zip](https://github.com/Koenkk/zigbee2mqtt/files/2813912/Greenwave.reader.zip)

**Comment by ptvoinfo** [comment]
@JLFN Is it possible to capture traffic for a pairing process of the official gateway and the reader?

**Comment by JLFN** [comment]
@ptvoinfo tried that but doenst give any security header with z.bee-seckey .

**Comment by ptvoinfo** [comment]
Strange. At the pairing stage, the gateway should send unencrypted data.

**Comment by JLFN** [comment]
@ptvoinfo  This you see this part ?
![image](https://user-images.githubusercontent.com/22047436/52053507-cfcac400-2559-11e9-925b-23852ece88de.png)

**Comment by ptvoinfo** [comment]
Look here:
https://www.youtube.com/watch?v=4vG4CVNAm_A

**Comment by JLFN** [comment]
@ptvoinfo  Yes i know it works i did it on my other zigbee networks and got the z.bee key easy but here its not showing the same behavor.

**Comment by endor-force** [comment]
I just got myself one of these. 
There is a serial interface on the board, 4 pins on the top left, 1 = VCC, 2 = RX, 3 =TX 4 = GND. 
Terminal 8n1 115200bps
Note, 3,3V - do not use 5v serial interfaces.


When it is powered on it outputs this data, replaced some values with X to obfuscate.:
N: GR0B-1108-00221
IEEE: D4AXX802000000XX
Key: A5ADE3AF48AD3720FAF219DBCBXXXXXX
FW: 0.63
HW: 3
CH: 0x6718000
Z-Stack: 2.5.1
P1 type: 1, scale: u, res: u, base: u, count: u
P1 on: 500 us, poll: 50 ms
P1 IR state: 0, cal: 0, thres: 0
P2 type: 4, scale: u, res: u, base: u, count: u
P2 on: 500 us, poll: 50 ms
P2 IR state: 0, cal: 0, thres: 0
Meter state: 0

**Comment by JLFN** [comment]
@endor-force  Can help out in anyway? How did you get the key ?

**Comment by JLFN** [comment]
@endor-force did you use this key with whireshark to try to decode? I have two gateways but nothing happens when i try to pair. like it doenst want to pair.

**Comment by endor-force** [comment]
Nope have not connected wireshark yet, i'm actually having a deconz / conbee setup but i can not see the device in their ui.. will test with wireshark as well.

**Comment by JLFN** [comment]
@endor-force I have a sniffer i speak Swedish also can we talk on discord or some place please?

**Comment by endor-force** [comment]
@JLFN I'm in home assistant discord server as endor.
https://discord.gg/Y56RSW

**Comment by JLFN** [comment]
802.15.4 JenNet is used not Zigbee.
