### ISSUE TITLE
Missing Support - Philips Hue Daylo Outdoor wall lamp

### ISSUE THREAD

**Issue by hoeselr** [Koenkk/zigbee2mqtt#9550]
missing Philips Device

## Information about the device + link
https://www.philips-hue.com/de-at/p/hue-white---color-ambiance-daylo-outdoor-wandleuchte/1746530P7

## data/database.db entry of the device
Geräte Typ
Router
Zigbee Modell
1746547P7
Zigbee Hersteller
Philips
Unterstützungsstatus
nicht unterstützt
IEEE Addresse
0x0017880109819431
Netzwerk Adresse
0x4CD7
Firmware Datum
20210331
Firmware Version
1.88.1
Spannungsversorgung
Interview erfolgreich
Ja

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

Please can you upload your data/database.db entry for the device so that I can add it?
