### ISSUE TITLE
New Fingerprint for Tuya smoke detector

### ISSUE THREAD

**Issue by morphygee** [Koenkk/zigbee2mqtt#9555]
Hi
I bought e new tuya smoke detector. One of this one: https://www.zigbee2mqtt.io/devices/TS0601_smoke.html
But mine has a new fingerprint with a new fingerprint: _TZE200_uebojraa

this new detector works without problem after adding a second entry to the  fingerprint in node_modules/zigbee-herdsman-converters/devices/tuya.js

I think it is worth to be added there for ever 
..

**Comment by Koenkk** [comment]
Added!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
