### ISSUE TITLE
Ikea LED1949C5 new device recently added but not recognized

### ISSUE THREAD

**Issue by aliessum** [Koenkk/zigbee2mqtt#9573]
## What happened
Tried to add this new Ikea LED1949C5. Pairing is ok, but it is not recognized. See log

## What did you expect to happen
I checked the zigbee-herdsman-converters/devices/ikea.js file and I can see that the device is recently added (at the end of the file).
## How to reproduce it (minimal and precise)
Tried to add the device the same way like I did several times before with others.
To check if I did not make a mistake I paired a Sonoff zigbee motion sensor with succes.

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2531
Adapter firmware version: CC2531_SOURCE_ROUTING_2019061
Zigbee2MQTT version   1.18.1 commit: 1.18.1
Coordinator type zStack12
Coordinator revision 20190619
Frontend version 0.3.76

![IMG_9-202111313_1111](https://user-images.githubusercontent.com/77691832/140910892-c73c4335-b4fc-4514-b6e9-93744e600650.jpg)
9

**Comment by sjorge** [comment]
1.18.1 is rather old, it's probably not in that release. The latest is 1.22.0 which is a lot newer.

**Comment by aliessum** [comment]
Hi Sjorge,
Thanks for your reply!
It seems that Z2M is not updated automatically from within HA. I found an issue about this (#7478).
After removing the repositorie and reinstalling, problem solved!
Thanks!
