### ISSUE TITLE
Wireless Switch 2 Gang (ZBWS02) doesn't send actions

### ISSUE THREAD

**Issue by eemorozov** [Koenkk/zigbee2mqtt#9581]
## What happened
Add [my wireless switch](https://zigbee.blakadder.com/Lerlink_ZBWS02.html) to Zigbee2MQTT. It's connected as [TuYa TS0042](https://www.zigbee2mqtt.io/devices/TS0042.html#tuya-ts0042) and doesn't expose action (it's null).
When I'm clicking on switch buttons nothing appears in the logs. Only clicking on the pair button produces this [log line](https://www.toptal.com/developers/hastebin/awezesuwon.apache).
Also after clicking on Reconfigure button [this error appears in logs](https://www.toptal.com/developers/hastebin/itufiduvog.apache).

## What did you expect to happen
I want to set up some automation in Home Assistant with sensor.action. But can use only battery. Action is None.

## Debug info
Zigbee2MQTT version: 1.22.0 commit: 0a1fccf
Adapter hardware: Xiaomi Gateway DGNWG05LM zigate
Adapter firmware version: de8e

**Comment by smaartscz** [comment]
Hey, did you solved this problem? I'm stuck with same issue...
