### ISSUE TITLE
SONOFF BASICZBR3 doesn't responding to a change state from OFF to ON

### ISSUE THREAD

**Issue by padziu** [Koenkk/zigbee2mqtt#9597]
## What happened
I connected SONOFF BASICZBR3 (https://www.zigbee2mqtt.io/devices/BASICZBR3.html) without problems and is visible on the network map but device doesn't respond to change the state.
Logs: https://www.toptal.com/developers/hastebin/pepoquboci.rust
The interesting fact is that physical button in device changes state but with zigbee this is not possible.
![obraz](https://user-images.githubusercontent.com/36339705/141188963-497adb01-a2ae-4e8c-875e-7034c3871073.png)
![obraz](https://user-images.githubusercontent.com/36339705/141189152-2f4f86ee-b1fc-439b-a54c-1c8cc0e6ded9.png)

## What did you expect to happen
The switch should change status to on.
## How to reproduce it (minimal and precise)
Just change the state from off to on.
## Debug info
Zigbee2MQTT version: 1.22.0-2
Adapter hardware: zStack12 (CC2531)
Adapter firmware version: 20201127

**Comment by ipeacocks** [comment]
I have absolutely the same device and it works well. Have you tried to repair it?

**Comment by padziu** [comment]
I changed the channel from 11 to 25 and the device works fine.
![2fa03d15dd0a963475c38cb03d776b8e8750c9b5](https://user-images.githubusercontent.com/36339705/141310361-7f80401e-f2f2-44ac-88ad-5f1c4f82388a.png)
