### ISSUE TITLE
With "legacy: false", Xiaomi WXKG01LM buttons don't work at all

### ISSUE THREAD

**Issue by Stooovie** [Koenkk/zigbee2mqtt#9601]
I'm trying to get rid of `Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'` by adding "legacy: false", but that renders my Xiaomi WXKG01LM buttons inoperable.

Z2M log is [here](https://hastebin.com/cepurafato). I see the actions there but no actual automation was carried out. 

Nothing in main log. HA 2021.11.2, Z2M 1.22.0-2. Also, simply removing legacy: false from the config and restarting Z2M addon does not restore the function. I have to restore a HA backup to regain Zigbee function.

**Comment by Koenkk** [comment]
When using `legacy: false` an `action` is send instead of `click, see the docs: https://www.zigbee2mqtt.io/devices/WXKG01LM.html#deprecated-click-event

**Comment by Stooovie** [comment]
Of course, I didn't adjust the automations! Doh. Thank you!
