### ISSUE TITLE
No zigbee2mqtt issue! - Heiman smoke detector HS3SA vs. HS1SA

### ISSUE THREAD

**Issue by h4nc** [Koenkk/zigbee2mqtt#961]
Does someone here know the difference between the two Heiman smoke detectors?

There are two models HS3SA and HS1SA?

They look a little different. 
Which one is newer? Is the one an updated version of the other one?

edit: also I’d like to know if it’s also possible to trigger the siren of the device. 
What information does it provide? The docs only say “smoke”. Does it also report the battery state?

**Comment by agehring80** [comment]
Hello.

Nothing new ? I cannot find a detailed description.
What are the features, what is the difference ?

Please.

**Comment by h4nc** [comment]
I ordered a HS1SA and got a HS3SA.

So I have the HS3SA now. 
I don’t think there is difference.

Also there are different endings like -N and -M.
Reseller told me they are both Zigbee.

**Comment by dfsx1** [comment]
I hope someone can answer this, as HS3SA device is not in their official product list?
http://www.heimantech.com/product/smart_zigbee.html
