### ISSUE TITLE
Saswell SEA801-Zigbee/SEA802-Zigbee hysteresis

### ISSUE THREAD

**Issue by iksrd** [Koenkk/zigbee2mqtt#9643]
Good afternoon! Does anyone know how to change hysteresis from 1 to 0.5?

**Comment by KartoffelToby** [comment]
I'm also intressted if the TRV has a valve status looks like it has one internal (little flame icon) but does it expose it?

**Comment by toki-it** [comment]
Any updates? I'm also interested
