### ISSUE TITLE
MS-105B Dimmer - "No converter available" when using comands other then zigbee2mqtt/FRIENDLY_NAME/set "brightness": XXX and "state": ON/OFF

### ISSUE THREAD

**Issue by Pitdelux** [Koenkk/zigbee2mqtt#9645]
Hi everyone,

I'm having issues using my Moes MS-105B Smart dimmer module (2 gang).

When I publish the following commands in MQTT, everything works as expected:
- zigbee2mqtt/FRIENDLY_NAME/set with payload {"state_l1": "ON"}, {"state_l1": "OFF"}
- zigbee2mqtt/FRIENDLY_NAME/set with payload {"brightness_l1": VALUE} where VALUE is a number between 0 and 254

The following command doesn't work:
- zigbee2mqtt/FRIENDLY_NAME/set with payload {"state_l1": "TOGGLE"}

Command zigbee2mqtt/FRIENDLY_NAME/set with payload {"brightness_l1":156,"transition":3} brings the brightness to 156 but without any transition.  I get a message mentionning that "No converter available for 'transition' " 

And when using the following commands, nothing happens and I get a message mentionning that "No converter available" for the called command in Z2M
- zigbee2mqtt/FRIENDLY_NAME/set {"brightness_move_l1": -40}
- zigbee2mqtt/FRIENDLY_NAME/set {"brightness_step_l1": 40} 

It's the same for both gangs (_l1 and _l2).  What works (or doesn't) for one works for the other.

Can anyone help with this?

![Capture4](https://user-images.githubusercontent.com/91699421/141660789-84554bbe-6b38-4790-a5dc-90da7471c029.PNG)

Many thanks in advance.
David

**Comment by knallhare** [comment]
Hi David,

I'm struggeling with the same issues. Have you had any luck on this yet?

**Comment by sniicker** [comment]
Hi Guys,

i have the same problem. Very frustrating. Did not found a way till now.

**Comment by knallhare** [comment]
Yeah, it's very frustrating. I have both MS-105Z and MS-105B. None of them work.

**Comment by somik321** [comment]
the problem is not solved
