### ISSUE TITLE
[FR] donation/patreon link

### ISSUE THREAD

**Issue by SamJongenelen** [Koenkk/zigbee2mqtt#970]
Dude, awesome software. Congratulations on the 1.10 release! This package & documentation is now really going to help me remove 3rd party bridges 👍 
Will restart my Hassio tonight, since it hasn't detected a new version yet..

I'd like a feature request; patreon/donate link for the project so I can buy you a beer.

**Comment by JLFN** [comment]
@SamJongenelen  there is a link already  https://www.paypal.me/koenkk

**Comment by frankforpresident** [comment]
@Koenkk, I would like to donate some BAT earned with my brave browser. If you register I could send  you some. https://creators.brave.com/sign-up

**Comment by Koenkk** [comment]
@frankforpresident done (koenkanters94@gmail.com). thanks!

**Comment by frankforpresident** [comment]
> @frankforpresident done ([koenkanters94@gmail.com](mailto:koenkanters94@gmail.com)). thanks!

Maybe not linked to github yet? Can't send them via email (or not sure how)

> NOTE: This creator has not yet signed up to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.Learn more.

**Comment by Koenkk** [comment]
@frankforpresident it seems that in order to receive assets I need to fully verify my uphold account. This would require me to send my passport and other personal information which I don't want to do for now. So unfortunately I cannot accept it.

**Comment by frankforpresident** [comment]
> @frankforpresident it seems that in order to receive assets I need to fully verify my uphold account. This would require me to send my passport and other personal information which I don't want to do for now. So unfortunately I cannot accept it.

no problem. Just donated via paypal 😉
