### ISSUE TITLE
Last seen status is N/A on all devices

### ISSUE THREAD

**Issue by burnworld3d** [Koenkk/zigbee2mqtt#9707]
## What happened

On all devices, the last seen status is N/A

## What did you expect to happen

Get a proper last seen status, indicating how many seconds or minutes 

## How to reproduce it (minimal and precise)

https://puu.sh/IpKhv/819e5535bb.png

## Debug info
Zigbee2MQTT version: latest stable one
Adapter hardware: Conbee II
Adapter firmware version: latest stable one

**Comment by francisp2** [comment]
You need to set ‘last_seen’ under the advanced section, the default is disabled.

**Comment by burnworld3d** [comment]
> You need to set ‘last_seen’ under the advanced section, the default is disabled.

Can you please specify where is that option?
I can't see it, searched on all tabs, like https://puu.sh/IpKnP/1cb798f6d6.png and i don't find that option

**Comment by burnworld3d** [comment]
ok i reply myself:

  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
  last_seen: 'disable'

needs to be added in advanced inside zigbee2mqtt config file
