### ISSUE TITLE
Starting Zigbee2MQTT stops at  "Using experimental new availability feature"

### ISSUE THREAD

**Issue by Propland** [Koenkk/zigbee2mqtt#9735]
Hello,

I have installed Ubuntu Server 20.04.3 LTS 64bit on my RPI4 and use the CC2531.
I have flashed the stick and then followed https://www.zigbee2mqtt.io/guide/installation/01_linux.

I had two small problems but could fix both:
 - as i ran "node-pre-gyp info ok" the output was "/usr/bin/env: ‘nodejs’: No such file or directory" but i fixed it with "sudo ln -s /usr/bin/node /usr/bin/nodejs"
 - as I tried to start Zigbee2MQTT in /opt/zigbee2mqtt with "npm start" I  had an "Error whie starting zigbee-herdsman" but fixed it with https://www.zigbee2mqtt.io/guide/usage/debug.html#enabling-logging

My current problem is when I try to start the application in /opt/zigbee2mqtt with "npm start" it tries to use an experimental new feature.. it stops there and nothing will happen.
![grafik](https://user-images.githubusercontent.com/94647169/142497677-e465dfe0-45d3-469b-9928-fea289224b7f.png)

I even added "availability: false" to the configuration.yaml hopefully, but this doesnt solve the problem.
This change makes the startup-output-code (or however you call it) very long, but stops at the same line:
![grafik](https://user-images.githubusercontent.com/94647169/142498076-87f542c0-d590-4294-a5ba-c57a738c4442.png)
![grafik](https://user-images.githubusercontent.com/94647169/142498104-5b8e7b31-dde0-453f-99c9-b3f35ccc656d.png)
sorry for the long pictures..
This long output doesnt go away, even if i delete the added line in the configuration.yaml or set it in true.

I really hope you can help me.
Thanks in advance.

**Comment by Propland** [comment]
I even tried https://www.zigbee2mqtt.io/guide/installation/01_linux on my laptop with ubuntu and on the other with mint.
On both the startup hangs up at "using an experimental new feature".
Am I the only one? Do you know this Problem?

**Comment by Koenkk** [comment]
This issue may already have been fixed in the dev branch, could you check that? (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Propland** [comment]
This doesnt help.
It keeps trying to use the availability feature and stops there

**Comment by Koenkk** [comment]
Could you provide the herdsman debug logging when trying to start?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by Propland** [comment]
I start z2m with DEBUG=zigbee-herdsman* npm start, but it stops again at:
(sorry again for these long pictures, but theres much code. Can i send the pictures next time in a better way e.g. minimize the pictures somehow?)
![grafik](https://user-images.githubusercontent.com/94647169/142710417-dafdefd2-0015-4c25-a40f-b99ebc311a9b.png)
Every Minute or so a new one of the similar code blocks appear.


When I Strg+c:
![grafik](https://user-images.githubusercontent.com/94647169/142710639-029b51cc-5cfc-4abd-8b1c-59b858ca824d.png)
![grafik](https://user-images.githubusercontent.com/94647169/142710647-4bc944e8-d7b9-4e39-9c59-5658085617d5.png)
I had to press Strg+c again that ubuntu@ubuntu:/opt/zigbee2mqtt$ show in the last line

In the state.json file theres just:   {}

**Comment by Koenkk** [comment]
Could you try flashing the source routing fw on your cc2531? https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

**Comment by Propland** [comment]
Unfortunately it still stops at the same line..
![grafik](https://user-images.githubusercontent.com/94647169/142777084-994082fb-26a9-411e-a4a6-3542fc29435c.png)

**Comment by Koenkk** [comment]
Could you provide your data/database.db and configuration.yaml?

**Comment by Propland** [comment]
My configuration.yaml
![grafik](https://user-images.githubusercontent.com/94647169/142854224-22873d90-2879-4df2-8c8f-8f8549c32843.png)

I think my database.db is empty
![grafik](https://user-images.githubusercontent.com/94647169/142855023-02b548a6-538a-4823-95e3-8562bd7d8ea3.png)

**Comment by francisp2** [comment]
I don't think it is a sqlite database. Just use nano to open database.db.

**Comment by Propland** [comment]
oh.. sry:
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b0018e19044","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,8,10,11,12,13,47,110,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"10":{"profId":260,"epId":10,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[1281],"outClusterList":[1280,1282],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"interviewCompleted":true,"meta":{},"lastSeen":null}

**Comment by Koenkk** [comment]
I just checked but this is actually the last thing being logged once starting is completed

> My current problem is when I try to start the application in /opt/zigbee2mqtt with "npm start" it tries to use an experimental new feature.. it stops there and nothing will happen.


What do you expect to happen after this?

**Comment by Propland** [comment]
It won't start.
![grafik](https://user-images.githubusercontent.com/94647169/142944787-ae5dac04-c545-4bcf-be07-bb3f05ffb9f5.png)

**Comment by Koenkk** [comment]
What if you enable the frontend in your configuration: https://www.zigbee2mqtt.io/guide/configuration/frontend.html and execute `npm start` in the z2m install dir, can you open the frontend after this?

**Comment by Propland** [comment]
Yes I can open the frontend. Thank you very much.

But I still cant start the deamon:
![grafik](https://user-images.githubusercontent.com/94647169/143140595-c0629672-3aa9-4abe-bed8-43b3f911733c.png)

this is my systemctl file in /etc/systemd/system/zigbee2mqtt.service
![grafik](https://user-images.githubusercontent.com/94647169/143140688-193303e6-ca4d-4e50-9f05-a2db8ffb7bf3.png)

**Comment by Koenkk** [comment]
This probably means the permissions of the user you are running the deamon as are incorrect, try fixing that or change `User` to `root` in `zigbee2mqtt.service`.

**Comment by Propland** [comment]
I tried to run the daemon as root but it failed again:
![grafik](https://user-images.githubusercontent.com/94647169/143463421-14f5870e-3304-47a7-97ca-7baa46908d64.png)
