### ISSUE TITLE
Lutron Aurora (Z3-1BRL) missing battery entity in HA

### ISSUE THREAD

**Issue by deatondg** [Koenkk/zigbee2mqtt#9736]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/9585

I am moving this discussion to an issue in order for more visibility. I have added battery support to the Lutron Aurora through a custom converter, but I am missing the Home Assistant battery entity that appears for devices like the Sonoff SNZB-02. 

<div type='discussions-op-text'>

<sup>Originally posted by **deatondg** November 10, 2021</sup>
I have some Sonoff SNZB-02 thermometers, and these devices each have a battery entity in HA. The current converters don't support battery reporting for the Lutron Aurora Z3-1BRL, but after reading through the discussion [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2305), I was able to create a custom converter which seems to work.

```
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const ota = require('zigbee-herdsman-converters/lib/ota');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const e = exposes.presets;
const ea = exposes.access;

module.exports = [
    {
        zigbeeModel: ['Z3-1BRL'],
        model: 'Z3-1BRL',
        vendor: 'Lutron',
        description: 'Aurora smart bulb dimmer',
        fromZigbee: [fz.battery, fz.legacy.dimmer_passthru_brightness],
        toZigbee: [],
        exposes: [e.battery(), e.action(['brightness']), exposes.numeric('brightness', ea.STATE)],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genLevelCtrl', 'genPowerCfg']);
            await reporting.batteryPercentageRemaining(endpoint, {min: 900, max: 900, change: 4});
        },
        ota: ota.zigbeeOTA,
    },
];
```

With this, the action entity in HA has a battery attribute which appears to have the correct value, but I don't get a battery entity, and I don't understand what is different about my converter and the Sonoff converter that is resulting in this difference between the two devices. 

Hopefully I am just missing something simple. I greatly appreciate all assistance! :)</div>

**Comment by fractalcounty** [comment]
As far as I can tell, the Z3-1BRL fully supports battery reporting. It's been a few years- can we get an update on this?
