### ISSUE TITLE
WS-EUK02: only left switch can be set to report state

### ISSUE THREAD

**Issue by mnn** [Koenkk/zigbee2mqtt#9746]
## What happened

Setting reporting for right switch fails:

<img width="903" alt="2021-11-19_13-29" src="https://user-images.githubusercontent.com/1975567/142623117-bba2a95b-d716-4b39-aafe-8716c3c7617b.png">

`
Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x54ef4410002459e3/2 genOnOff([{"attribute":"onOff","minimumReportInterval":"0","maximumReportInterval":3600,"reportableChange":0}], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE')'
`

## What did you expect to happen

It works the same as with left switch (setting the reporting doesn't end with error and reporting works).

## How to reproduce it (minimal and precise)

After fresh pairing just fill in the values in the screenshot (Endpoint 2, Cluster OnOff, Attribute onOff, Min. rep interval 0) and click Apply.

---

I read in some thread/issue that decoupled mode is supposed to help. It does not. The device (or Zigbee2MQTT) doesn't send actions (when switch is pressed), so then there is no way operate the light with the switch (actions don't work for both switches - left and right).

I am not sure how bindings work, I kept the default ones (which so far worked for all other "pressable" devices; it looks like 1, 2 and 242 are bound to coordinator).

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: Conbee II
Adapter firmware version: don't know ("coordinator revision" says 0x26580700, not sure if that's it)
Device description: Aqara smart wall switch H1 EU (no neutral, double rocker)

**Comment by vcirstea** [comment]
Hi, any thoughts on why may be happening?
