### ISSUE TITLE
Temp offset not working RTCGQ11LM

### ISSUE THREAD

**Issue by tungmeister** [Koenkk/zigbee2mqtt#9747]
I've just setup some new RTCGQ11LM's. Everything appears to be working however setting a temperature offset is having no impact on the reported temp.
the temperature is being reported as 5 degrees over the correct value:
![image](https://user-images.githubusercontent.com/127809/142628146-c6701d8b-1141-4912-a73e-f72d13ee71fd.png)
I've adjusted to compensate and confirmed this is in the config file:
![image](https://user-images.githubusercontent.com/127809/142628276-e98be49e-9cff-4c0b-a083-b165000b29c0.png)
![image](https://user-images.githubusercontent.com/127809/142628534-79463451-b523-42b9-8533-650c3f4d6473.png)
however, the temperature is still being reported as 30.

I've restarted zigbee2mqtt and applied a bit of heat to the unit however it's still reading 5 degrees over.

**Comment by Koenkk** [comment]
This will be applied on the next temperature report of the sensor (could take some time, few hours)

**Comment by tungmeister** [comment]
ah - I figured hitting it with the hairdryer would force it to report a new value - does it not provide the value every time it reports a new motion detection?

**Comment by Koenkk** [comment]
No, only on an interval basis (the use case of its temperature sensor is therefore limited)

**Comment by lux73** [comment]
the Temperature Value from the Aqara Motion Sensors are not reliable - even the Brightness Reports are ridiculous...

therefore using dedicated Xiaomi GZCGQ01LM Light Sensor for Brightness

some of my Aqara Door Contacts measure Temperatures 6-8 Degrees higher than my Aqara Temperatur Sensors - i would not trust them anymore ;-)

**Comment by tungmeister** [comment]
Yeah, I'm not going to rely on it for anything, but it's nice to get an approximate temperature in a couple of rooms that didn't have sensors prevously. After 5 hours or so it started updating and adopting the offset value so working as expected.
