### ISSUE TITLE
TS0601_dimmer dropped off the network and will not re-pair

### ISSUE THREAD

**Issue by elgerg** [Koenkk/zigbee2mqtt#9748]
I have a TS0601_dimmer that seems to refuse to re-pair to my network. It was working fine for months then seemed to disappear.

Each time I try to re-pair it (using warning only logs) I get:
Warning Device 'SpareRoomLight' left the network
Warning Device 'SpareRoomLight' left the network
Warning Device 'SpareRoomLight' left the network

## What happened
The device "left" the network multiple times

## What did you expect to happen
I expected the device to re-join the network

## How to reproduce it (minimal and precise)
Press the power button 5 times then hold on the 6th
I'm not sure why this one dimmer will not re-pair. I can see it in the devices db:

            "0x5c0272fffec61638": {
                "friendly_name": "SpareRoomLight"
            },

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: Slaesh's CC2652RB stick
Adapter firmware version:
Coordinator type zStack3x0
Coordinator revision 20210708

**Comment by elgerg** [comment]
Any ideas?

**Comment by elgerg** [comment]
@Koenkk 
What is the best way of removing the device from the db file?
Thanks
Alex

**Comment by elgerg** [comment]
@Koenkk  Any ideas?
Thanks

**Comment by Koenkk** [comment]
Could you make a sniff when trying to pair this device?

https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#with-cc2531

When sharing the `.pcapng` file please also share your network key

**Comment by elgerg** [comment]
Sure will do when I have some time..

**Comment by elgerg** [comment]
Still trying to get time to do the sniffing..
