### ISSUE TITLE
Aqara Motion Sensor not showing model.

### ISSUE THREAD

**Issue by HJKLMN** [Koenkk/zigbee2mqtt#976]
Connected 2 new Aqara motion sensors today. 
 first one has no model in DB. 2nd one is ok.

From the log:
1/30/2019, 6:11:13 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":
.......................
{"ieeeAddr":"0x00158d0002e35208","type":"EndDevice","friendly_name":"0x00158d0002e35208"},{"ieeeAddr":"0x00158d0002e3500f","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"0x00158d0002e3500f"}]}'

I know perhaps deleting from DB and readding might help, but just wanted to report it.
The log from joining failed device:
1/30/2019, 8:54:34 PM - info: New device with address 0x00158d0002e35208 connected!
1/30/2019, 8:54:34 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002e35208"}'
1/30/2019, 8:54:34 PM - warn: Device with modelID 'undefined' is not supported.

What is the best way to troubleshoot/fix?

**Comment by Koenkk** [comment]
- Stop zigbee2mqtt
- Remove all entries of `0x00158d0002e35208` from `database.db
- Start zigbee2mqtt
- Repair using https://koenkk.github.io/zigbee2mqtt/getting_started/pairing_devices.html#xiaomi

**Comment by HJKLMN** [comment]
Solved, THX
