### ISSUE TITLE
update miboxer.js device FUT038Z to be able to select color_xy (RGBW controller)

### ISSUE THREAD

**Issue by Ramonlambal** [Koenkk/zigbee2mqtt#9779]
Excuse me if I am not describing it well here, quite new to github, so if more info is needed, let me know. 

Currently device FUT038Z (in miboxer.js), is defined as: 
extend: extend.light_onoff_brightness_colortemp({disableColorTempStartup: true, colorTempRange: [153, 500]})
however, in this way it is difficult to change the RGB value.
I changed it locally to be:
extend: extend.light_onoff_brightness_colortemp_color({disableColorTempStartup: true, colorTempRange: [153, 500]}),

This makes color selection a lot easier for this device.

**Comment by Koenkk** [comment]
Changed, thanks!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
