### ISSUE TITLE
Tradfri color bulb E12 450 Lumen

### ISSUE THREAD

**Issue by CzechSebastian** [Koenkk/zigbee2mqtt#9783]
Hi,
I just bought an Ikea Trader color bulb and it's not support by the HA Addon.
I also change to edge version and it's the same.
Can you give more about this integration ?
If you want more picture of the bulb or the box, just let me know .
Thanks a lot
<img width="1136" alt="Capture d’écran, le 2021-11-21 à 17 19 10" src="https://user-images.githubusercontent.com/46093860/142782869-346ab272-88d2-4ee4-9bcf-36e9ab810a64.png">

Edit: I just see that this bulb is "already supported" 
https://www.zigbee2mqtt.io/devices/LED1925G6.html
But mine's not... 
On the bulb description, it say 470lm but mine is 450lm, and it's the same version LED1925G6, weird...

## Information about the device + link
Ikea Tradfri Bulb E12 450 Lumen
https://www.ikea.com/ca/en/p/tradfri-led-bulb-e12-450-lumen-wireless-dimmable-color-and-white-spectrum-globe-opal-white-20439194/

**Comment by Koenkk** [comment]
Added it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by CzechSebastian** [comment]
If I want update the edge version on HA , I need to uninstall , reload add on and install it right ?
Can you send me a message here, when it will be deployed ?

Thanks a lot

**Comment by Koenkk** [comment]
> If I want update the edge version on HA , I need to uninstall , reload add on and install it right ?

yes

> Can you send me a message here, when it will be deployed ?


4 hours from now

**Comment by CzechSebastian** [comment]
Thanks
