### ISSUE TITLE
Temperature Support for MCCGQ14LM (lumi.magnet.acn001)

### ISSUE THREAD

**Issue by DanPatten** [Koenkk/zigbee2mqtt#9785]
## Is your feature request related to a problem? Please describe
I have the latest edge version of zigbee2mqtt (HA) and got the sensor working but I am not seeing a temperature reading for my latest aqara contact sensor (MCCGQ14LM). 

## Describe the solution you'd like
It looks like this is possible, see ZHA's version, which has a draft PR: https://github.com/zigpy/zha-device-handlers/pull/1151. Should be able to read the sensor's temperature reading. 

Thank you!

**Comment by danieledwardgeorgehitchcock** [comment]
I am not sure where you are looking, but it doesn't appear this device reports back temperature values on any standardised clusters..

Are you sure this is something that the device supports if it is linked to its native hub?

The pull request that you referenced above seems to be part of a larger refactor for the new Aqara E1 / T1 devices so, the new references to temperature are only used if the device (such as the new lumi weather) supports / reports it.

The lumi magnet only seems to report generic (for general device attributes) and IAS Zone (for open / close events)

**Comment by Koenkk** [comment]
@dmulcahey can you confirm this device supports temperature measurements? It is not clear to me based on https://github.com/zigpy/zha-device-handlers/pull/1151

**Comment by DanPatten** [comment]
I think someone did get it working in deconz (assuming that the value isnt static or something. It's obviously not very accurate but I think that same thing occurred with the older version. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-972172659

**Comment by danieledwardgeorgehitchcock** [comment]
I see that in the comments someone has indeed mentioned the temperature, and looking at the above comments, this may come from a Xiaomi / Aqara specific cluster.

However, looking at the [Deconz REST Plugin device handler](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/devices/xiaomi/xiaomi_mccgq14lm_openclose_sensor.json), I cannot see any mention of temperature. I also tried decoding the hex attributes that were mentioned in [this comment](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-950730003) and cannot get anything like a temperature reading

**Comment by Koenkk** [comment]
@DanPatten could you check if the temperature is in the published payload now? (could take one day to show up)

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by blcetux** [comment]
@Koenkk, I'm using same MCCGQ14LM device. With "koenkk/zigbee2mqtt:latest-dev" docker image, I can see the temperature:
```
zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:10:05: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20211115,"transportrev":2},"type":"zStack12"}'
(...)
zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:10:05: 0x54ef4410002bc16d (0x54ef4410002bc16d): MCCGQ14LM - Xiaomi Aqara E1 door & window contact sensor (EndDevice)
(...)
zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:15:01: MQTT publish: topic 'zigbee2mqtt/0x54ef4410002bc16d/temperature', payload '25'
```

For now, the value is much higher than other sensors. This shows 25C while others on the same room show 19C. I will wait a couple of hours and check it again.

**Comment by avi9899** [comment]
> @Koenkk, I'm using same MCCGQ14LM device. With "koenkk/zigbee2mqtt:latest-dev" docker image, I can see the temperature:
> 
> ```
> zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:10:05: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20211115,"transportrev":2},"type":"zStack12"}'
> (...)
> zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:10:05: 0x54ef4410002bc16d (0x54ef4410002bc16d): MCCGQ14LM - Xiaomi Aqara E1 door & window contact sensor (EndDevice)
> (...)
> zigbee2mqtt    | Zigbee2MQTT:info  2021-12-18 10:15:01: MQTT publish: topic 'zigbee2mqtt/0x54ef4410002bc16d/temperature', payload '25'
> ```
> 
> For now, the value is much higher than other sensors. This shows 25C while others on the same room show 19C. I will wait a couple of hours and check it again.

Did you get it working?
It's 25C all the time!!

**Comment by julien100** [comment]
any update?

**Comment by Koenkk** [comment]
@z-x-f do you know if this device has a temperature sensor?

**Comment by ToXinE** [comment]
how can this device (a door sensor) could have a temperature sensor ?
