### ISSUE TITLE
Officially supported devices cannot be added and recognized（PRZ01（J.XUAN））

### ISSUE THREAD

**Issue by Tao173** [Koenkk/zigbee2mqtt#9787]
I tried possible solutions, but I have no way to fix it.
The official support list device cannot be paired normally.
This is the official support link:
https://www.zigbee2mqtt.io/devices/PRZ01.html

What happened:
It can be recognized after resetting, but Vendor cannot be recognized. As far as the signal strength can be displayed, all other information is not available.
What did you expect to happen:
It is in the official list of supported devices, and I hope it can be accessed normally, including icons, human body induction information, and battery information.
How to reproduce it:
I think anyone who pairs this device will have this problem, which means that it is not really "officially supported". Another issue from a Chinese user:
https://github.com/Koenkk/zigbee-herdsman-converters/issues/2666

Debug info
Docker log:
https://pastebin.com/AEVTVidV
Z2M log:
https://pastebin.com/xCbPzPV9
Zigbee2MQTT version:1.22.0-3 (installed in hassio)
Adapter hardware: CC2652P2
Adapter firmware version:Z-Stack 3.x.0 20210708 (https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20210708.zip)

**Comment by ryangu** [comment]
@GWan1234 did you solve this problem？need some help！
