### ISSUE TITLE
First pairing device (supported project) - unsupported

### ISSUE THREAD

**Issue by fast0490f** [Koenkk/zigbee2mqtt#9791]
HI
I have a door sensor xiaomi / aqara
If I do the first pairing with the coordinator, i am getting an unsupported device.
I see only device_joined, device_interview, no see device_announce 

If restart Z2M or (wait 2 minutes , see device_announce) - device works fine!
How many times have I tried to remove and add a device the situation is repeated
this does not happen with all devices

Is this a hardware feature of the zigbee network or the software bug of Z2M?

**Comment by fast0490f** [comment]
Если сразу после собеседования перезапустить сервис Z2M, то все сразу заработает
В противном случае нужно подождать 1-2 минуты до Приходит сообщение device_anonce.

после перезагрузки получается пройти собеседование сразу, навсегда

**Comment by lrodorigo** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/10214

I think we are in the same boat... when do you restart Z2M service to  complete the interview?
