### ISSUE TITLE
Multiple mqtts publishes?

### ISSUE THREAD

**Issue by robertalexa** [Koenkk/zigbee2mqtt#9800]
Hi @Koenkk 

I was wondering if you could shed some light on this, something i have noticed after the latest update. For one of my automations i basically used a toggle when the action = single. Now i have noticed that this stopped working, or even, it doubles up in fact.

At a quick glance in the z2m logs i have found this:
```
Info MQTT publish: topic 'zigbee2mqtt/Steph's Nightstand Light Switch', payload '{"action":"single","battery":92,"last_seen":1637619612680,"linkquality":99}'
Info MQTT publish: topic 'zigbee2mqtt/Steph's Nightstand Light Switch/action', payload 'single'
```

To your knowledge, did anything change recently that would duplicate these MQTT messages like this? In my case all of this goes through HA

Thanks

**Comment by Koenkk** [comment]
Does the problem go away when setting `last_seen` to `disable` in `configuration.yaml`?

**Comment by sjorge** [comment]
Is this not because output is set to json + attrubute ?
