### ISSUE TITLE
Show database.db entry in Frontend - "Nice to have" feature

### ISSUE THREAD

**Issue by chrisrock1984** [Koenkk/zigbee2mqtt#9806]
## Is your feature request related to a problem? Please describe

To request a new device more easily, it would be nice to show the database entry in the frontend. 

## Describe the solution you'd like

Add a new tab which shows the database entry of that device

## Describe alternatives you've considered
-

## Additional context

An "upload new request" to github would be nice to have, which automatically adds the database entry within the template for adding a new device

**Comment by danieledwardgeorgehitchcock** [comment]
I raised this a while back.

Please see answers here nurikk/zigbee2mqtt-frontend#822

**Comment by Koenkk** [comment]
Let's continue in https://github.com/nurikk/zigbee2mqtt-frontend/issues/822
