### ISSUE TITLE
Ledvance/Osram AC25697 Colors are off by a bit, only Hue/Saturation gives the right colors.

### ISSUE THREAD

**Issue by tom1422** [Koenkk/zigbee2mqtt#9807]
## What happened
When changing the color through color_xy, the color changes to a less saturated version of what I was expecting, mostly affects the more red colors. This also translates into Home Assistant where changing the color on the wheel gives a slightly different version of that color on the bulb. If using the Exposes tab and changing the color_hs instead, the color changes to exactly what I set it to. 
## What did you expect to happen
I expected the color_xy to do the same as color_hs but there may be an issue with conversion.
## How to reproduce it (minimal and precise)
Using the color_xy and setting it to the first color (Red), you observe a more orange color on the bulb.
Using the color_hs and setting it to the same red, you see a much darker red.
## Debug info
Zigbee2MQTT version: 1.18.1 commit: 1.18.1
Adapter hardware: CC2652RB
Adapter firmware version: 20210128

**Comment by danieledwardgeorgehitchcock** [comment]
It might be that these bulbs need the `applyRedFix` applying see [here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/4b6e0d271897445d54044b215b2df601948bf1ac/converters/toZigbee.js#L967)
