### ISSUE TITLE
Aeotec (Smartthings) Multipurpose Sensor IM6001-MPP03

### ISSUE THREAD

**Issue by Papi77** [Koenkk/zigbee2mqtt#9811]
## Information about the device + link
Add support for latest version of Multipurpose Sensor from Aeotec. There is currently already support for the older version of a similar device from [Smartthings (2018)](https://www.zigbee2mqtt.io/devices/IM6001-MPP01.html). This request if for the newer version: https://aeotec.freshdesk.com/support/solutions/articles/6000242293

When pairing I'm getting the device recognized but number of entities are missing:

![image](https://user-images.githubusercontent.com/26800136/143037339-3a232ec4-aa01-47da-ac50-ccfecd89a7c2.png)

## data/database.db entry of the device
..

**Comment by danieledwardgeorgehitchcock** [comment]
Please add the data/database.db for this device

**Comment by Papi77** [comment]
Sorry, but I don't know what data/database.db is :(

**Comment by danieledwardgeorgehitchcock** [comment]
How are you using Z2M? Through HA addon? Through Docker image? other?
