### ISSUE TITLE
Immax NEO LITE Smart E27 bulb identified wrongly as GU10 bulb

### ISSUE THREAD

**Issue by domsvoboda** [Koenkk/zigbee2mqtt#9814]
## What happened
I bought pack of Immax RGB E27 bulbs, however two of them shows as GU10 bulbs from Tuya. Zigbee model is TS0505A and the Zigbee manufacturer is _TZ3000_hlijwsai. Also the red light on these bulbs doesn't work when i choose it from HA. I guess this needs the red color fix.

## What did you expect to happen
I have another bulbs from Immax and they are showing correctly as Immax and the red color work.

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: CC2531
Adapter firmware version: zStack12, 20190608

**Comment by pborky** [comment]
Same issue here.

**Comment by standahabich** [comment]
Immax NEO 07115L

reporting:
`Read result of 'genBasic': {"manufacturerName":"_TZ3000_hlijwsai","modelId":"TS0505A"}`

but identify as "TuYa TS0505A" and full red color not worked.
