### ISSUE TITLE
Only 1 button hold option in Home Assistant

### ISSUE THREAD

**Issue by Unthred** [Koenkk/zigbee2mqtt#9819]
Using TuYa TS0044 4 buttons paired fine using Zigbee2Mqtt Edge build.
Have single and double click on all buttons

## What happened
Creating an automation via the gui, after selecting the device in Triggers the dropdown list is missing entries
"3_hold" action exists but 1, 2 and 4 do not
1,2,3,4 single click and double click actions are all correct and work fine

## What did you expect to happen
The dropdown list to contain entries for 1_hold, 2_hold, 3_hold and 4_hold

## How to reproduce it (minimal and precise)
Select the TuYa TS0044 device in Triggers and look in the Trigger dropdown

## Debug info
Zigbee2MQTT version: 1.22.0-dev commit: 6ca8d35
Adapter hardware:  ConBee2 & 2x CC2530 routers
Adapter firmware version: 0x26720700 (Coordinator revision I think its the same thing)
Frontend version: 0.6.31

**Comment by junknstuff** [comment]
Any updates to this ticket? I have a similar issue except I can only see - and successfully configured Automations in Home Assistant - the "Single" and "Double" actions and NO "Hold" actions on the Triggers drop-down list.

Device Info:
Zigbee Model: TS0044
Zigbee Manufacturer: _TZ3000_wkai4ga5

Zigbee2MQTT version: 1.27.2 commit: unknown

Coordinator type: zStack30x
Coordinator revision: 20201227
Frontend version: 0.6.110

Z2M is running as an Add-on to Home Assistant 2022.9.2, Supervisor 2022.08.6, Operating System 8.5

![Screen Shot 2022-09-12 at 08 48 38](https://user-images.githubusercontent.com/11420141/189564954-8e3f1da2-d99e-4e6a-bc1b-3fa24e52a13f.jpg)
![Screen Shot 2022-09-12 at 09 38 34](https://user-images.githubusercontent.com/11420141/189564969-ee5295fc-c860-4401-88e6-74845c60b0dd.jpg)
