### ISSUE TITLE
TuYa TS0601_thermostat_1 can not set schedule

### ISSUE THREAD

**Issue by biejay** [Koenkk/zigbee2mqtt#9820]
## What happened
I got the TuYa TS0601_thermostat_1 working, but in the manual it says that for setting the schedule I have to publish to "zigbee2mqtt/FRIENDLY_NAME/set". But i can not set any schedule data. 
Inserting my thermostat name here works fine for the current heatpoint, so thats not the matter.

But The payload in the manual `"{"undefined": {"monday_schedule": VALUE, "tuesday_schedule": VALUE, "wednesday_schedule": VALUE, "thursday_schedule": VALUE, "friday_schedule": VALUE, "saturday_schedule": VALUE, "sunday_schedule": VALUE}}"` does not work. 

I replaced VALUE by `" 6h:0m 20°C,  12h:0m 15°C,  18h:0m 22°C,  22h:0m 15°C "` but Zigbee2mqtt tells me **`"No converter found for undefined" `**
## What did you expect to happen
Setting the schedule to my preferred times.

## Debug info
Zigbee2MQTT version: 1.22.0-3
Adapter hardware: slae.sh_cc2652rb_stick

**Comment by Koterak** [comment]
Try instead of "undefined": 
- "workdays"
- "holidays"

**Comment by biejay** [comment]
Also not working.

**Comment by biejay** [comment]
Still no luck after update to 1.22.1-1

**Comment by biejay** [comment]
Push

**Comment by maciekn** [comment]
I am struggling with this issue as well. @biejay were you able to set the schedule?

**Comment by chodar** [comment]
any update here? I'm facing the same issue.
