### ISSUE TITLE
config problem in addon

### ISSUE THREAD

**Issue by michaelduijkers** [Koenkk/zigbee2mqtt#985]
after updating to 1.1.0 my zigbee2mqtt stopped working.
i uninstalled it from home assistant and tried again, with no luck, where in the old version it was plug and play, maybe i'm missing something.

{
  "data_path": "/share/zigbee2mqtt",
  "homeassistant": true,
  "permit_join": false,
  "mqtt_base_topic": "zigbee2mqtt",
  "mqtt_server": "mqtt://192.168.1.13",
  "serial_port": "/dev/ttyACM0",
  "devices": []

}

don't know how to use hastebin so sorry for that...

the message i get is

not a valid value for dictionary value @ data['options']. Got {'data_path': '/share/zigbee2mqtt', 'homeassistant': True, 'permit_join': False, 'mqtt_base_topic': 'zigbee2mqtt', 'mqtt_server': 'mqtt://192.168.1.13', 'serial_port': '/dev/ttyACM0', 'devices': []}

i got no port for ssl -> checked my hardware on HA

i'm pretty new on this

**Comment by JLFN** [comment]
You are in the wrong place you should go to https://github.com/danielwelch/hassio-zigbee2mqtt
