### ISSUE TITLE
Moes MS-105BZ brightness not exposed in Domoticz Z2M plugin 

### ISSUE THREAD

**Issue by ptaudio** [Koenkk/zigbee2mqtt#9869]
The Moes MS105BZ dimmer does  not have the brightness feature exposed so it can't be controlled from Domoticz.
Only the state and link quality are exposed. According the description here : https://www.zigbee2mqtt.io/devices/MS-105B.html
this should be available.
I'm running v.1.22.0 (zStack30x 20190425) and Domoticz version 2021.1
CC2531 is connected through 2 meter extension cable.
I'm able to control the brightness with the hardware button,so dimmer is working fine.
Also when adjust i the brightness with the hardware button the dimmer slider in Domoticz moves.

## Debug info
Zigbee2MQTT version: 1.22.0
Adapter hardware: CC2531
Adapter firmware version: Z-stack3.0.x

![Schermafbeelding 2021-11-27 om 20 52 55](https://user-images.githubusercontent.com/17804745/143720449-643f8a1c-b47d-413e-b04a-ddcd358d43da.png)

**Comment by Koenkk** [comment]
Please create issues related to the domticz addon here: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin
