### ISSUE TITLE
Console and Syslog log formats are different

### ISSUE THREAD

**Issue by IgorAga** [Koenkk/zigbee2mqtt#9872]
When logging to both Console and Syslog I'm getting completely different format of log entries:

Example:

`Zigbee2MQTT:info  2021-11-28 15:29:56: Currently 8 devices are joined:` in Console entry

`2021-11-28T12:29:56.860+03:00 192.168.0.2 zigbee2mqtt - - - Currently 8 devices are joined:<134>1` **without new line** in Syslog entry for most of entries.

As a result Syslog becomes completely unreadable, while Console output is clear.

My logging settings are as following:

>  log_level: info
>  log_output: ['console', 'syslog']
>  log_syslog:
>    app_name: zigbee2mqtt
>    host: 192.168.0.6
>    localhost: 192.168.0.2
>    pid: process.pid
>    port: 514
>    protocol: tcp4
>    type: '5424'

Another point is that `log_level:` parameter works fine for Console output, however Syslog always logs in `log_level: debug` mode.

My rsyslog.service is running on 192.168.0.6 and is serving several other logs without any problem.

And yes, I am in timezone UTC+3... but don't see any need to remind me in every log entry about that.

Thanks in advance.

**Comment by amadeo-alex** [comment]
The messages being one big chunk of text might be a bug (please see PR referenced above).
Regarding the log format itself, dirty copying *format* parameter from file logger unfortunately ends up with this:
![obraz](https://user-images.githubusercontent.com/68441479/143786683-b67aa93c-7195-44d0-87c1-93ab0e6aed32.png)

This is because zigbee2mqtt is not directly responsible for the syslog messages format. As far as I've been able to quickly check, the formatting is done by [#glossy](https://github.com/squeeks/glossy) (used by [#winston-syslog](https://github.com/winstonjs/winston-syslog). z2m just passed message content.

This could be changed by providing *customProducer* to glossy.

**Comment by amadeo-alex** [comment]
Interesting, the PR solved the issue for me on Kiwi Syslog Server (windows syslog server), but when I pointed z2m to my rsyslog server it failed miserably with:
![obraz](https://user-images.githubusercontent.com/68441479/143788329-1de9ef93-2046-4639-9a5c-c908925ce1cc.png)
The first message starts with:
![obraz](https://user-images.githubusercontent.com/68441479/143788371-40603b43-35d3-4c90-bd59-43c3c59a06c5.png)
and ends with:
![obraz](https://user-images.githubusercontent.com/68441479/143788426-6c857ca7-9291-4856-b60d-3c44fc991177.png)

The same happens with "vanilla" z2m, something is not right here. Seems like z2m is not sending proper line endings?

**Comment by amadeo-alex** [comment]
"Interesting intensifies"
I've switched to UDP as a means of transport:
![obraz](https://user-images.githubusercontent.com/68441479/143789502-33fc8d2c-e012-4a6e-b3d9-2d2be05022cc.png)
As you can see, this time there is no newline issue (afaik each UDP message is treated as a separate message, that would explain this). The interesting thing is the "\n" at the end of each message.

My EOL settings:
![obraz](https://user-images.githubusercontent.com/68441479/143789581-f4fdd560-d968-4b48-b7a7-9cf446cf239a.png)

I've searched a bit after that and found this: https://issueexplorer.com/issue/winstonjs/winston-syslog/150
Seems like exactly the same issue. This person has "<13>" between the messages, if you look closely in my case, when TCP is selected as a means of transport, there are "<134>" between the messages (in addition to "\n" specified in the z2m config).

**Comment by IgorAga** [comment]
I tried to switch to UDP - and yes, it solves newline issue (I do not have `eol: \n` in my configuration).

> Nov 29 06:19:27 192.168.0.2 zigbee2mqtt Logging to console only'
> Nov 29 06:19:27 192.168.0.2 zigbee2mqtt Starting Zigbee2MQTT version 1.22.0 (commit #df0543d4)
> Nov 29 06:19:27 192.168.0.2 zigbee2mqtt Starting zigbee-herdsman (0.13.164)

Funny thing, however, is that with UDP configured it shows timestamp in different format and UTC only (local time is 09:19:27 i this case).

That's definitely better, but raises another issue with the timestamp :)

**Comment by IgorAga** [comment]
Interesting point is that timestamp in Console output is in local timezone:

> Zigbee2MQTT:info  2021-11-29 09:40:40: Logging to console only'
> Zigbee2MQTT:info  2021-11-29 09:40:41: Starting Zigbee2MQTT version 1.22.0 (commit #df0543d4)
> Zigbee2MQTT:info  2021-11-29 09:40:41: Starting zigbee-herdsman (0.13.164)

while the same entries in Syslog are in UTC:

> Nov 29 06:40:40 192.168.0.2 zigbee2mqtt Logging to console only'
> Nov 29 06:40:41 192.168.0.2 zigbee2mqtt Starting Zigbee2MQTT version 1.22.0 (commit #df0543d4)
> Nov 29 06:40:41 192.168.0.2 zigbee2mqtt Starting zigbee-herdsman (0.13.164)
