### ISSUE TITLE
TuYa TS0601_thermostat_1 apparently does not have modes defined

### ISSUE THREAD

**Issue by losip** [Koenkk/zigbee2mqtt#9890]
## What happened
Thermostat based on this radiator valve has all modes displayed, even inappropriate ones such as 'cool'

## What did you expect to happen
Need to see just Off, Heat and Auto like its brother TuYa TS0601_thermostat. Modes definiton missing?

## How to reproduce it (minimal and precise)
Create thermostat and see six modes displayed

## Debug info
Zigbee2MQTT version: Zigbee2mqtt Edge
Adapter hardware: CC26X2R1
Adapter firmware version:
![Zigbee1](https://user-images.githubusercontent.com/91874520/143884333-d27a10c1-77c5-4f68-aa07-50cfcf18a6ad.jpg)

**Comment by vladi1234** [comment]
Look here:

https://github.com/Koenkk/zigbee-herdsman-converters/issues/2937#issuecomment-917696264

**Comment by vladi1234** [comment]
I think that doesn't leave any point if it works.
You can program with extra code so that HA is correct as the default, but that makes problems with other home automation programs. It doesn't make TVR as flexible as it should be.

**Comment by losip** [comment]
Thanks for the advice
