### ISSUE TITLE
TuYa Blind Motor Zigbee Manufacturer: _TZE200_r0jdjrvi Model: TS601

### ISSUE THREAD

**Issue by serhatVIRT** [Koenkk/zigbee2mqtt#9895]
I tried to add this device according to the manual on the zigbee2mqtt site. But the device is still unsupported. Can this device added to Zigbee2Mqtt? :)

Friendly name
0xa4c138b0d8e0df43
Last seen
N/A
Device type
Router
Zigbee Model
TS0601
Zigbee Manufacturer
_TZE200_r0jdjrvi
Support status
Not supported
IEEE Address
0xa4c138b0d8e0df43
Network address
0x74FF
Power
Interview completed
True

Debug Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"0xa4c138b0d8e0df43","transaction":"9er6z-1"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0xa4c138b0d8e0df43"},"error":"Device '0xa4c138b0d8e0df43' cannot be configured","status":"error","transaction":"9er6z-1"}'
Debug Saving state to file /config/zigbee2mqtt/state.json
Debug Received Zigbee message from '0xa4c138f4ccffc7e6', type 'attributeReport', cluster 'genBasic', data '{"65506":48,"65508":0,"appVersion":68}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0xa4c138b0d8e0df43', type 'attributeReport', cluster 'genBasic', data '{"65506":48,"65508":0,"appVersion":68}' from endpoint 1 with groupID 0
Warning Received message from unsupported device with Zigbee model 'TS0601' and manufacturer name '_TZE200_r0jdjrvi'
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by alsbi** [comment]
+1

**Comment by serjo77** [comment]
+1

**Comment by serjo77** [comment]
`
const fz = require( 'zigbee-herdsman-converters/converters/fromZigbee' );
const tz = require( 'zigbee-herdsman-converters/converters/toZigbee' );
const exposes = require( 'zigbee-herdsman-converters/lib/exposes' );
const reporting = require( 'zigbee-herdsman-converters/lib/reporting' );
const extend = require( 'zigbee-herdsman-converters/lib/extend' );
const tuya = require( 'zigbee-herdsman-converters/lib/tuya' );
const e = exposes.presets;
const ea = exposes.access;

const definition = {
        zigbeeModel: [
            'owvfni3\u0000', 'owvfni3', 'u1rkty3', 'aabybja', // Curtain motors
            'mcdj3aq', 'mcdj3aq\u0000', // Tubular motors
            ],
        fingerprint: [
            { modelID: 'TS0601', manufacturerName: '_TZE200_r0jdjrvi' },
            ],
        model: 'TS0601',
        vendor: 'TuYa',
        description: 'Curtain motor/roller blind motor/window pusher/tubular motor',
//        whiteLabel: [
//            {vendor: 'Tuya', model: 'M515EGZT'},
//            ],
        fromZigbee: [
            fz.tuya_cover,
            fz.ignore_basic_report,
            ],
        toZigbee: [
            tz.tuya_cover_control,
            tz.tuya_cover_options,
            ],
        exposes: [
            e.cover_position().setAccess('position', ea.STATE_SET),
            ],
    };

module.exports = definition;`
