### ISSUE TITLE
battery value not correct

### ISSUE THREAD

**Issue by timoline** [Koenkk/zigbee2mqtt#9898]
https://www.zigbee2mqtt.io/devices/ICZB-RM11S.html#icasa-iczb-rm11s

just added a few new batteries in this device but always shows 50%

If I put the same batteries in another device it shows 100%

![image](https://user-images.githubusercontent.com/680252/143926010-d7cbb353-9bc2-483a-b0f0-5314db5683f0.png)

**Comment by sjorge** [comment]
I’m guessing it might need the flag to tell it not to device the value, or if it’s using voltage it might je tagged wrong https://github.com/Koenkk/zigbee-herdsman-converters/blame/master/README.md#L32

**Comment by Koenkk** [comment]
Should be fixed now, please confirm.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by timoline** [comment]
just pulled the dev branch and unfortunatly still 50%

**Comment by Koenkk** [comment]
Make sure you are on #c90171d2cc3022f88987cf1e9be978bd7fa7ecd8 and wait until the next battery report comes in (could take a day)

**Comment by timoline** [comment]
ok good point, I'll let you know

**Comment by timoline** [comment]
looking good now, thx

![image](https://user-images.githubusercontent.com/680252/144286544-4b9abff6-e06b-43d8-9e2c-a5e712e4d026.png)
