### ISSUE TITLE
Hue Smart Plug not supported - Serial Number AE4D41 - LOM008

### ISSUE THREAD

**Issue by emic68** [Koenkk/zigbee2mqtt#9936]
Hi Guys,

My new Hue Smart Plug is not supported by Zigbee2mqtt. 
I can see it in the device list but I have an error message. The only information
In the map, I see that it is a router. But I have no possibility to activate the switch.

I have around 23 devices, the system is updated and also the firmware of the plug.
All devices are functioning very well.

I have already do a factory reset of the plug, try another Hue Smart plug... it is always the same issue. I suppose that all Philips Hue devices are supported ?

## Information about the device + link
Hue Smart Plug  - Serial Number AE4D41 - LOM008

## data/database.db entry of the device
Type de Périph : Router
Modèle Zigbee : LOM008
Constructeur Zigbee : Signify Netherlands B.V.
Supporté : Non supporté
Adresse IEEE : 0x0017880109d5de79
Adresse réseau : 0xE210
Date Firmware : 20201117
Version Firmware : 1.76.11
Alim
Interview terminé : Vrai

Thanks for your help !

**Comment by Koenkk** [comment]
Supported in zigbee2mqtt 1.22.1
