### ISSUE TITLE
New device GASSensor-EM  model: 'HS1CG-E' does not act

### ISSUE THREAD

**Issue by FRFrancisqueti** [Koenkk/zigbee2mqtt#994]
Hello friends, I need help.
I have a gas sensor that was not supported by zigbee2mqtt (HEIMAN HS1CG-E), I used the Koen tutorial and now it is recognized and also acts when the test button is pressed and also when it detects the presence of gas, but the value of the variable gas remains in "false" even when actuated.
Does anyone have something similar to help me?

These are the log's:

 zigbee2mqtt:debug 2019-2-1 13:39:40 Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":32}' of device 'GASSensor-EM' (0x000d6f00104b7c97)
  zigbee2mqtt:info 2019-2-1 13:39:40 MQTT publish: topic 'zigbee2mqtt/0x000d6f00104b7c97', payload '{"gas":false,"linkquality":81,"device":{"ieeeAddr":"0x000d6f00104b7c97","friendlyName":"0x000d6f00104b7c97","type":"Router","nwkAddr":44244,"manufId":4619,"manufName":"HEIMAN","powerSource":"Mains (single phase)","modelId":"GASSensor-EM","status":"offline"}}'
  zigbee2mqtt:debug 2019-2-1 13:39:40 Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":48}' of device 'GASSensor-EM' (0x000d6f00104b7c97)
  zigbee2mqtt:info 2019-2-1 13:39:40 MQTT publish: topic 'zigbee2mqtt/0x000d6f00104b7c97', payload '{"gas":false,"linkquality":81,"device":{"ieeeAddr":"0x000d6f00104b7c97","friendlyName":"0x000d6f00104b7c97","type":"Router","nwkAddr":44244,"manufId":4619,"manufName":"HEIMAN","powerSource":"Mains (single phase)","modelId":"GASSensor-EM","status":"offline"}}'
  zigbee2mqtt:debug 2019-2-1 13:39:41 Saving state to file C:\opt\zigbee2mqtt\data\state.json

Database:
https://pastebin.com/jMyAHH1z

Devices.js:
{
        zigbeeModel: ['GASSensor-EM'],
        model: 'HS1CG-E',
        vendor: 'HEIMAN',
        description: 'GAS Sensor',
        supports: 'gas',
        fromZigbee: [
            fz.JTQJBF01LMBW_gas_HEIMAN,
            fz.JTQJBF01LMBW_sensitivity_HEIMAN,
            fz.JTQJBF01LMBW_gas_density_HEIMAN,
            fz.ignore_basic_change,
        ],
        toZigbee: [],   //tz.JTQJBF01LMBW_sensitivity, tz.JTQJBF01LMBW_selfest],
		configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
                (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
            ];

            execute(device, actions, callback, 1000);
        },
    },

FromZigbee.js:
JTQJBF01LMBW_gas_HEIMAN: {
        cid: 'ssIasZone',
        type: 'statusChange',
        convert: (model, msg, publish, options) => {
            return {gas: msg.data.zoneStatus === 1};
        },
    },

JTQJBF01LMBW_gas_density_HEIMAN: {
        cid: 'genBasic',
        type: 'attReport',
        convert: (model, msg, publish, options) => {
            const data = msg.data.data;
            if (data && data['65533']) {
                const basicAttrs = data['65533'];
                if (basicAttrs.hasOwnProperty('100')) {
                    return {density: basicAttrs['100']};
                }
            }
        },
    },

JTQJBF01LMBW_sensitivity_HEIMAN: {
        cid: 'ssIasZone',
        type: 'devChange',
        convert: (model, msg, publish, options) => {
            const data = msg.data.data;
            const lookup = {
                '1': 'low',
                '2': 'medium',
                '3': 'high',
            };

            if (data && data.hasOwnProperty('65533')) {
                const value = data['65520'];
                if (value && value.startsWith('0x020')) {
                    return {
                        sensitivity: lookup[value.charAt(5)],
                    };
                }
            }
        },
    },

Thank you.

**Comment by khzd** [comment]
Hi
Can you replace 
gas: msg.data.zoneStatus === 1}; By
gas: msg.data.zoneStatus == 1}; ?
Cheers

**Comment by FRFrancisqueti** [comment]
Hi, thanks for the answer, but the same thing continues ...
