### ISSUE TITLE
Problem with adding new devices on CC2652P2

### ISSUE THREAD

**Issue by mmychu** [Koenkk/zigbee2mqtt#9940]
## What happened
After I switched from Conbee2 to CC2652P2 Based Zigbee to Ethernet Serial Coordinator, I have problems with adding new devices to my network. Devices added before migration, works fine.
I have 20 devices working, but when I'm trying to add 3 more powered devices, I have warning that "Device left the network"

This is the log with warning:
![image](https://user-images.githubusercontent.com/25245131/144320198-86e6a41d-0cea-4981-9c2d-4c43d796129a.png)
 
This is my map:
![image](https://user-images.githubusercontent.com/25245131/144320352-686bab3b-fa5e-4323-88ce-3bd1003033e6.png)

## Debug info
Zigbee2MQTT version: 1.22.1-1
Adapter hardware: CC2652P2
Adapter firmware version:

**Comment by phillipgreenii** [comment]
@mmychu i am looking into getting a CC2652P2, were you able to get things working? Was the problem related to CC2652P2?
