### ISSUE TITLE
EZSP - the publish set state get stuck - timeout - adapter reset

### ISSUE THREAD

**Issue by perexg** [Koenkk/zigbee2mqtt#9951]
## What happened

EZSP - the switch on/off commands are stuck sometimes. The timeout handler resets the whole adapter.

## What did you expect to happen

Normal operation. Send Zigbee sequences as quickly as possible.

## How to reproduce it (minimal and precise)

Connect a zigbee plug. Turn it on/off quickly using the  mqtt set commands.

## Debug info
Zigbee2MQTT version 1.22.0-dev (commit #ed9d09a)
zigbee-herdsman (0.13.176)
Coordinator firmware version: '{"meta":{"maintrel":"8 ","majorrel":"6","minorrel":"7","product":8,"revision":"6.7.8.0 build 373"},"type":"EZSP v8"}'

Debug log: https://gist.github.com/perexg/b7811a2991c3ff3d874eb3140aace738

**Comment by Koenkk** [comment]
The ezsp is currently experimental without any active developers, please report the issue here: https://github.com/Koenkk/zigbee-herdsman/issues/319
