### ISSUE TITLE
Aqara MCCGQ14LM not sending state

### ISSUE THREAD

**Issue by NdR91** [Koenkk/zigbee2mqtt#9965]
## What happened

After the pairing, two of my brand new MCCGQ14LM are not sending any state except the LQI.
I tried to repair both of them, but without any result.

![Schermata 2021-12-02 alle 20 53 25](https://user-images.githubusercontent.com/52299148/144493949-5905eea9-e618-4b2d-8926-2ddccde26a59.jpg)

## What did you expect to happen

Receiving the states of Contact, Battery and Voltage

## How to reproduce it (minimal and precise)

Pair a MCCGQ14LM device

## Debug info
Zigbee2MQTT version: 1.22.1
Adapter hardware: CC2652
Adapter firmware version:  Z-Stack 3.x.0 20210708

**Comment by NdR91** [comment]
Sorry, my bad.

I updated to the latest FW (didn't see the develop branch): Z-Stack_3.x.0 20211114

I ha dto re-pair again the device, now it's working perfectly

**Comment by orbsmiv** [comment]
@Koenkk Is this 3.x.0 firmware on the develop branch good to use or should I wait on a master branch release?

**Comment by NdR91** [comment]
> @Koenkk Is this 3.x.0 firmware on the develop branch good to use or should I wait on a master branch release?

I'm using it since 2 days and no issue found.

My ZigBee network counts abt 40 devices of different brands.

**Comment by Koenkk** [comment]
> @Koenkk Is this 3.x.0 firmware on the develop branch good to use or should I wait on a master branch release?

Should be fine, running it for 2 weeks already and no problems, will probably made official with the next z2m release.
