### ISSUE TITLE
Ability to expose switch as light from inside WebUI

### ISSUE THREAD

**Issue by thinkl33t** [Koenkk/zigbee2mqtt#9973]
## Is your feature request related to a problem? Please describe
I currently use zigbee2mqtt almost exclusively through the web interface, which is amazing!  However, for the light switches in my house, i use Xiaomi QBKG04LM light switches, which by default show up to homeassistant (and hence google assistant) as switches.

## Describe the solution you'd like
I'd like a setting added to the device in the webui which allows automatically sets up the [correct config](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light) for homeassistant autodiscovery, without having to log into the docker host, stop z2m, edit the config file manually for 20+ devices, and restart it.  A simple checkbox or dropdown would be perfect.

This would also allow for keeping the autodiscovery code updated and working on new homeassistant releases, to avoid [issues](https://github.com/Koenkk/zigbee2mqtt/issues/8033) like we saw in July.

## Describe alternatives you've considered
Current alternative is editing the config file manually, which can be a bit error prone.

**Comment by adizag** [comment]
@Koenkk  It is marked as closed, but there is still no GUI option for exposing as light. Couldn't find it in the guide as well.
That option is very necessary, could be great  to have it please.

**Comment by cwildfoerster** [comment]
ping @Koenkk

**Comment by thargy** [comment]
Yeah, this has me stumped, can never find the place in the docs with the example of how to configure in YAML and couldn't get it working.  Would love a simpler GUI way of doing this.

**Comment by b2un0** [comment]
+1

**Comment by teras** [comment]
+1

**Comment by thargy** [comment]
For anyone else, you may wish to look at the Home Assistant Helper - "Change device type of a switch", which you can create to change a switch to a light.

**Comment by flackovic** [comment]
> For anyone else, you may wish to look at the Home Assistant Helper - "Change device type of a switch", which you can create to change a switch to a light.

After following [steps their documentation](https://www.zigbee2mqtt.io/guide/usage/integrations/home_assistant.html#exposing-switch-as-a-light) three times, unsucessfully, this worked with 2 clicks. Thanks!

**Comment by rickvand** [comment]
+1

**Comment by tequilaj-gh** [comment]
+1

**Comment by fedd** [comment]
would be nice to declare the switch as light without an HA helper. We have "Home Assistant name" setting and even an icon, why not add a light there
