### ISSUE TITLE
Aqara E1 / QBKG39LM Switch binding

### ISSUE THREAD

**Issue by kiall** [Koenkk/zigbee2mqtt#9981]
## What happened

Binding the buttons on an "Aqara E1 2 gang switch (without neutral)" / QBKG39LM is not possible, as the `genOnOff` etc output clusters aren't detected.

## What did you expect to happen

The various output clusters to be detected, assuming they exist :)

It's possible the clusters need to be re-scanned after changing the device into decoupled mode?

It's also possible these clusters just don't exist on this device and it doesn't support binding at all!

As an aside, I see in the [documentation page](https://www.zigbee2mqtt.io/devices/QBKG39LM.html) for these devices a note for the required firmware versions, I've the latest for the CC26X2R1 - however this doesn't contain the changes introduced recently in the listed firmware. 

## How to reproduce it (minimal and precise)

1. Pair a QBKG39LM with Z2M
2. Set the `operation_mode` of the left and right buttons to decoupled mode
3. Attempt to bind either button to a light & observe the only available bind target clusters are `Ota` and `genTime`.

![screencapture](https://user-images.githubusercontent.com/52713/144632554-ed415d1d-4d03-41fc-ae05-4b624282b086.png)

## Debug info

Zigbee2MQTT version: 1.22.1
Adapter hardware: CC26X2R1 
Adapter firmware version: zStack3x0 20210708

**Comment by Anonym-tsk** [comment]
Same issue, please reopen

**Comment by SergioRius** [comment]
Same issue with [WXKG07LM](https://www.zigbee2mqtt.io/devices/WXKG07LM.html#xiaomi-wxkg07lm), please consider reopening the issue.

**Comment by rishab123s** [comment]
I have the same issue with QBKG39LM Switch binding, please reopen the issue.

**Comment by danlex-corp** [comment]
I have the same issue with **QBKG41LM** Switch binding, please reopen the issue.

**Comment by lsteelandt** [comment]
This issue remains on Zigbee2Mqtt version 1.30.2.
Using an Sonos Coordinator (EZSP v8 with 6.10.3.0 build 297)

Used Aqara switches : [QBKG39LM](https://www.zigbee2mqtt.io/devices/QBKG39LM.html#xiaomi-qbkg39lm) and [QBKG38LM](https://www.zigbee2mqtt.io/devices/QBKG38LM.html#xiaomi-qbkg38lm)

**Comment by GigaVik** [comment]
This issue remains on Zigbee2Mqtt version 1.33.1.

**Comment by GigaVik** [comment]
Please open. This issue remains on Zigbee2Mqtt version 1.33.2.

**Comment by Koenkk** [comment]
AFAIK this device doesn't send out standard ZCL commands so this is not possible.

**Comment by aleks-mariusz** [comment]
> AFAIK this device doesn't send out standard ZCL commands so this is not possible.

can you elaborate how to determine this ? and what the implications are for binding?  or more info?

i ran into this after setting up some new switches all over the house, seems pretty lame to not be able to bind aqara switches to aqara light bulbs 🤦

**Comment by Koenkk** [comment]
> can you elaborate how to determine this ?

This device does not have a `genOnOff` cluster (as you can see in the OP). This means it cannot send on/off commands.

**Comment by aleks-mariusz** [comment]
> > can you elaborate how to determine this ?
> 
> This device does not have a `genOnOff` cluster (as you can see in the OP). This means it cannot send on/off commands.

@Koenkk thanks for the explanation.  but i have to wonder tho, can ANYTHING be done about this? i mean I am guessing z2m cannot add support somehow to introduce this functionality then, right?

what about aqara, what would be needed from them? a fw update? 

i don't understand why they would intentionally not include support for this.. do you suppose it could be purposeful, or just an oversight?

i'm just really baffled why my aqara wall switch cannot control my aqara bulb ffs.. is this type of info available somehow to check before you buy a product? i mean i would have thought twice about this model if i knew something basic like this wouldn't be currently possible. and i really don't wanna replace all my switches because of this but i'm going to have to think twice about getting aqara products if this is intentionally crippled this way.

**Comment by Koenkk** [comment]
> what about aqara, what would be needed from them? a fw update?

A fw update from them indeed, nothing can be done from the z2m side.

**Comment by wlfbck** [comment]
Ah, found this issue while trying to figure why i cannot bind them. A shame. I suggest emailing support@aqara.com so they do something about this.
