### ISSUE TITLE
IKEA E1524/E1810 remote control does not pair anymore with new version

### ISSUE THREAD

**Issue by pfischbach** [Koenkk/zigbee2mqtt#9983]
## What happened
Updated to latest version, now IKEA E1524 does not pair anymore 
Used 3 different remotes new batteries no success. Remotes pair with IKEA Hub
![image](https://user-images.githubusercontent.com/3976786/144651463-357dc17c-3265-48a6-9e0c-97388f3bec10.png)
[https://pastebin.com/8s2bHKdX](url)
## What did you expect to happen
remote pairs correct like before

## How to reproduce it (minimal and precise)
Bring remote into pairing mode, and wait for pairing log.

## Debug info
Zigbee2MQTT version: Zigbee2MQTT version 1.22.1-dev (commit #dae66fd)
Adapter hardware: CC2531
Adapter firmware version:
Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20211116,"transportrev":2},"

**Comment by 00joshi** [comment]
I had some issues with pairing but after force deleting, and rebooting zigbee2mqtt, i managed to pair the device.


### Debug info
Zigbee2MQTT Version
    1.22.1 commit: 48b790cb
Coordinator Typ
    zStack3x0
Coordinator Version
    20201026

**Comment by pfischbach** [comment]
Thanks for the feedback. 
Yes with the older coordinator it worked for me too. But had other issues with Eurotronics Thermostats
Just tried again. delete, restart and re-pairing without success Remote does not pair

**Comment by Megacheezy** [comment]
had this issue as well after applying update, i managed to get past it by touchlinking the remote to an already paired lightbulb. then the remote popped up in Z2M.

**Comment by lafin** [comment]
I recently had the same problem. I removed everything except configuration.yaml, then restarted zigbee2mqtt and tried to connect to the coordinator again and everything went well after that.
