### ISSUE TITLE
TuYa TS011F_plug_3 no set recover state after power outage

### ISSUE THREAD

**Issue by ster1um** [Koenkk/zigbee2mqtt#9987]
this plug are supposed in dev branch but not work all.
It’s impossible to set recover state after power off.

Log 

```
Debug Received Zigbee message from '0xa4c138329b21d2b9', type 'attributeReport', cluster 'manuSpecificTuya_3', data '{"53264":2}' from endpoint 1 with groupID 0
Debug No converter available for 'TS011F_plug_3' with cluster 'manuSpecificTuya_3' and type 'attributeReport' and data '{"53264":2}'
```

this is the variant of the tuya plug
![A1AF798A-F24E-41B1-8BDA-935131538263](https://user-images.githubusercontent.com/59310478/144680791-083575c5-2a6a-4532-9dec-9a44c1a28ff6.jpeg)

**Comment by Inferi0r** [comment]
Agreed. I have 10 of the same new Plugs. power_outage_memory can be changed to 'restore' of 'on', but result will be 'off' for all devices.

**Comment by ster1um** [comment]
> Agreed. I have 10 of the same new Plugs. power_outage_memory can be changed to 'restore' of 'on', but result will be 'off' for all devices.

Yes, same behaviour.

**Comment by taimaiduc** [comment]
I have the same problem.

**Comment by ster1um** [comment]
I set optimistic to false but don’t change nothing!

**Comment by sergey-1976** [comment]
I have 3 of the same new Plugs. (TS011F_plug_3 _TZ3000_typdpbpg)
I set "power_outage_memory", but result always is 'off'.

**Comment by sergey-1976** [comment]
You need to update the firmware via the Tuya Hub. After that, everything works fine.

**Comment by carloda** [comment]
Can you see the consumption values ​​with the NAS-WR01B model?
