### ISSUE TITLE
ZNCZ04LM specific setting 'temperature_precision' has no effect

### ISSUE THREAD

**Issue by degreal** [Koenkk/zigbee2mqtt#9991]
## What happened
Specific option 'temperature_precision: 2' has no effect. Still reporting temperature with 1 degree precision.
## What did you expect to happen
Temperature reading of '24.12' degrees instead of '24' degrees.

## How to reproduce it (minimal and precise)
Open device tab 'Settings (specific)'
Slide value from 0 to 2
Wait for next temperature update
![pilt](https://user-images.githubusercontent.com/4028600/144690195-2b445306-6bdd-46c6-a36f-53d6aac52848.png)

## Debug info
Zigbee2MQTT version: 1.22.1-1
Adapter hardware: CC2652P
Adapter firmware version: zStack3x0 20210708
ZNCZ04LM firmware version: 09-06-2019

</body>
</html>

Logs of changing precision setting and waiting for temperature update
https://www.toptal.com/developers/hastebin/ebapecucol.apache

**Comment by Koenkk** [comment]
The calibration is applied as soon as the device reports a new temperature.

**Comment by degreal** [comment]
> The calibration is applied as soon as the device reports a new temperature.

Yes. I can confirm that temperature_calibration works but temperature_precision does not. Or am misundestanding the temperature_precision setting?

**Comment by Koenkk** [comment]
@degreal it could be that this device does not support more precise power measurements.
