### ISSUE TITLE
Philips Hue Aurelle 929003099001

### ISSUE THREAD

**Issue by pvdburgt-new** [Koenkk/zigbee2mqtt#9994]
I added a convertor file with this specific device. But entities are still not available

## Information about the device + link
..
https://www.lamp123.nl/merken/hue/detail/13836/plafondlamp-philips-hue-white-ambiance-aurelle-929003099001.html

## data/database.db entry of the device
..

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

If you could post what you have in your external converter file along with your database.db entries for this device, and also the [colour temperature](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_3-adding-converter-s-for-your-device) values, I can add this for you or assist in getting it merged into the main code base.
